### ISSUE TITLE
German translation for jizz.ppy.sh

### ISSUE THREAD

**Issue by miterosan** [ppy/osu#1]
"de.users": {
            login: {
                username: "Benutzername"
                , password: "Passwort"
                , button: "Login"
                , remember: "Eingeloggt bleiben"
                , title: "Bitte logge dich ein um fortzufahren"
                , failed: "Inkorrekte Logininformationen"
                , register: "Noch keinen Account? Klicke :here!"
                , forgot: "Du hast ein Passwort vergessen? Setze es :here zurück!"
                , beta: {
                    main: "Der Zugriff auf die Beta-Inhalte in momentan nur privilegierten Nutzern möglich."
                    , small: "(Supporters bekommen es bald auch!)"
                }
                , here: "hier"
            }
            , anonymous: {
                login: "Einloggen"
                , username: "Gast"
            }
            , logout: {
                _: "Ausloggen"
                , confirm: "Bist du sicher das du dich ausloggen möchtest? :("
            }
        }
        , "de.help": []
        , "de.ranking": []
        , "de.common": {
            count: {
                item: ":count unit|:count units" //dunno what is meant with that so I cant translate this
            }
            , pagination: {
                previous: "verherige"
                , next: "nächste"   // ae 
            }
        }
        , "de.layout": {
            menu: {
                home: {
                    _: "home"
                    , getNews: "news"
                    , getChangelog: "changelog"
                    , getDownload: "download"
                    , getIcons: "icons"
                }
                , help: {
                    _: "help"
                    , getWiki: "wiki"
                    , getFaq: "faq"
                    , getSupport: "support"
                }
                , beatmaps: {
                    _: "beatmaps"
                    , getListing: "listing"
                    , getPacks: "Pakete"
                    , getCharts: "charts"
                    , getModding: "modding"
                    , moddingreact: "modding"
                    , index: "listing"
                }
                , ranking: {
                    _: "ranking"
                    , getOverall: "Generell"
                    , getCountry: "Land"
                    , getCharts: "charts"
                    , getMapper: "mapper"
                    , index: "Generell"
                }
                , community: {
                    _: "community"
                    , getForum: "forum"
                    , getChat: "chat"
                    , getLive: "live"
                    , profile: "profil"
                    , "forum-topics-create": "forum"
                    , "forum-topics-show": "forum"
                    , "forum-forums-index": "forum"
                    , "forum-forums-show": "forum"
                }
                , error: {
                    _: "Fehler"
                    , 404: "Nicht verfügbar"
                    , 403: "Verboten"
                    , 401: "Unbefugt"
                    , 500: "Irgend etwas ist kapputgegangen"
                    , 503: "Wartungsarbeiten"
                }
                , user: {
                    _: "user"
                    , getLogin: "Einloggen"
                    , disabled: "Gesperrt"
                    , register: "Registeren"
                    , reset: "Wiederherstellen"
                    , "new": "Neu"
                    , logout: "Ausloggen"
                }
                , store: {
                    _: "store"
                    , getListing: "listing"
                    , getCart: "Einkaufswagen"
                    , getAdmin: "admin"
                    , getCheckout: "Bezahlen"
                    , getInvoice: "invoice"
                    , getProduct: "produkt"
                    , "new": "Neu"
                    , home: "home"
                    , index: "home"
                    , thanks: "Danke"
                }
            }
            , errors: {
                404: {
                    error: "Seite nicht verfügbar"
                    , description: "Entschuldigung, aber die Seite die du angefordert hat gibt es nicht!"
                    , link: !1
                }
                , 403: {
                    error: "Du solltest nicht hier sein."
                    , description: "Du kannst natürlich versuchen woanders hinzugehen."
                    , link: !1
                }
                , 401: {
                    error: "Du solltest nicht hier sein."
                    , description: "Du kannst natürlich versuchen woanders hinzugehen. Oder du loggst dich ein."
                    , link: !1
                }
                , 500: {
                    error: "Oh nein! Irgendetwas ist kapputgegangen! ;_;"
                    , description: "Wir werden automatisch von diesen Fehler benachrichtigt."
                    , link: !1
                }
                , fatal: {
                    error: "Oh nein! Irgendetwas ist schlimm kapputgegangen! ;_;"
                    , description: "Wir werden automatisch von jeden Fehler benachrichtigt."
                    , link: !1
                }
                , 503: {
                    error: "Wartungsarbeiten!"
                    , description: "Wartungsarbeiten finden innerhalb 5 Sekunden bis 10 Minuten statt. Falls wir dann immernoch nicht erreichbar sind, klicke diesen :link für mehr Informationen."
                    , link: {
                        text: "@osustatus"
                        , href: "https://twitter.com/osustatus"
                    }
                }
                , reference: "Just in case, here's a code you can give to support!"
            }
        }
        , "de.community": {
            profile: {
                404: "Benutzer wurde nicht gefunden! ;_;"
                , avatar: ":username's Avatar"
                , current_location: "Befindet sich momentan in :location."
                , first_members: "ist schon ein Mitglied von Osu! seit dem Osu! existiert"
                , is_supporter: "osu!Supporter"
                , lastvisit: "Letzes mal gesehen :date."
                , joined_at: "Spieler seit :date"
                , origin: "Von :country."
                , plays_with: {
                    _: "Plays with"
                    , keyboard: "Tastertur"
                    , mouse: "Maus"
                    , tablet: "Tablet"
                    , touch: "Touch Screen"
                }
                , missingtext: "Du hast dich vielleicht verschrieben! (oder der Benutzer wurde gebannt)"
                , stats: {
                    hit_accuracy: "Treffgenauigkeit"
                    , level: "Level :level"
                    , maximum_combo: "Maximale Combo"
                    , play_count: "Runden gespielt"
                    , ranked_score: "Ranked Score"
                    , replays_watched_by_others: "Aufzeichnungen, welche von anderen geschaut wurden"
                    , score_ranks: ""
                    , total_hits: "Ingesammte Treffer"
                    , total_score: "Ingesammter Score"
                }
                , title: "profil / :username"
            }
        }
        , "en.beatmaps": {
            moddingreact: "modding"
            , listing: {
                search: {
                    prompt: "Schreibe in Stichworten..."
                    , options: "Mehr Suchoptionen"
                }
                , mode: "Modus"
                , status: "Rank Status"
                , all: "Alle"
                , "ranked-approved": "Ranked & Approved"
                , faves: "Favoriten"
                , modreqs: "Mod Requests"
                , pending: "Pending"
                , "mapped-by": "erstellt von :mapper"
                , source: "from :source"
                , "load-more": "Lade mehr..."
            }
            , modding: {
                portal: "Modding Portal"
                , discussion: "Beatmap Discussion"
                , metadata: {
                    title: "Titel"
                    , artist: "Künstler"
                    , tags: "Tags"
                    , source: "Quelle"
                    , unicode: {
                        artist: "Unicode Künstler"
                        , title: "Unicode Titel"
                    }
                }
                , comments: {
                    comment: "Geben sie ein Kommentar ein..."
                    , time: "Geben sie eine Zeit and (Optional)"
                    , reply: "Schreibe hier um zu antworten..."
                    , missing: "Es scheint wo als wäre hier nichts. Tut mir leid deswegen."
                }
                , feedback: {
                    feedback: "Generelles Feedback"
                    , difficulty: "Difficulty Specific"
                    , praise: "Praise|Praise"
                    , suggestion: "Vorschlag|Vorschläge"
                    , problem: "Problem|Probleme"
                    , nominate: "Nominierter|Nominierte"
                    , resolved: "Resolved"
                }
                , helptext: {
                    time: "Kopiere hier aus den Editor eine Zeit rein (CTRL+C, CTRL+V)"
                    , nominate: "See the :ranking for a list of criteria that beatmaps must meet to pass into qualification."
                    , ranking: "ranking criteria"
                    , warning: "Don't just nominate because you like the mapper; nominate because a map is ready to be ranked."
                    , comment: "Leave a comment with your mod or praise, and if possible, attach the mod to your post!"
                    , confirm: "I acknowledge that nominating maps with objective issues will lead to losing mod score, or having my ability to nominate removed."
                }
                , errors: {
                    type: "You didn't specify a comment type!"
                    , "Zugriff verweigert": "Du bist hierzu nicht befugt."
                    , invalid: "Your mod was automatically rejected. Mods should be between 15 and 800 characters long."
                    , silenced: "You cannot post mods while silenced. Please try again later."
                    , missing: "Beatmap not found. It may have been deleted after you loaded the page!"
                    , beatmap: "You tried to comment on a beatmap that is not part of this set."
                    , unknown: "Ein unbekannter Fehler ist aufgetreten. Wir wunden ebenfalls Informiert!"
                    , "Kein kommentar": "Du musst ein Kommtar hinterlassen."
                }
                , success: {
                    comment: "Kommentar Geposted!"
                    , reply: "Antwort Geposted!"
                    , nomination: "Nomination Posted!"
                    , edit: "Post Editiert!"
                }
            }
            , "bat-tools": {
                buttons: {
                    "lösche-map": "Lösche Beatmap"
                    , "unrank-map": "Unranke Beatmap"
                    , "lösche-scores": "Lösche Scores"
                    , "graveyard-map": "Graveyard Map"
                }
            }
            , bss: {
                errors: {
                    missing: "Tut mir leid aber die Beatmap existiert nicht."
                    , "zugriff-verweitert": "Diese Beatmap gehört nicht dir."
                    , ranked: "Disese Beatmap ist bereits geranked"
                    , graveyarded: "Diese Beatmap ist auf den Friedhof. Gehe zu deiner Beatmap auf der Beatmapseite um sie wiederzubeleben"
                }
            }
        }
        , "de.home": {
            news: {
                slogan: "Rhytmus ist nur ein *klick* entfernt!"
            }
        }
        , "de.store": {
            admin: {
                warehouse: "Warenhaus"
            }
            , checkout: {
                pay: "Bezahle mit Paypal"
            }
            , order: {
                item: {
                    quantity: "Anzahl"
                }
            }
            , product: {
                name: "Name"
            }
        }
        , "de.api": {
            errors: {
                csrf: "Zugriff verweigert"
                , missing: "Nicht gefunden"
            }
        }
        , "de.forum": {
            pinned_topics: "Gepinnente Themen"
            , post: {
                create: {
                    advanced: {
                        hide: "Verstecke erweiterten Editor"
                        , show: "Zeige erweiterten Editor"
                    }
                }
                , confirm_delete: "Willst du wirklich den Post löschen?"
                , edited: "Zuletzt von :user am :when, editiert. :count Mal wurdes insgesammt editiert ."
                , posted_at: "posted :when"
            }
            , search: {
                go_to_post: "Gehe zu Post"
                , post_number_input: "Geben sie die Post nummer ein"
                , total_posts: ":posts_count Posts insgesammt"
            }
            , subforums: "Subforums"
            , title: "osu!community"
            , topic: {
                create: {
                    placeholder: {
                        body: "Schreibe hier deinen Inhalt rein"
                        , title: "Klicke hier um den Titel zu setzen"
                    }
                    , preview: "Vorschau"
                    , submit: "Veröffentlischen"
                }
                , go_to_latest: "Zeige letzen Post"
                , latest_post: ":when von :user"
                , latest_reply_by: "letze Antwort von :user"
                , new_topic: "Poste neues Thema"
                , post_edit: {
                    cancel: "Abbrechen"
                    , post: "Editieren"
                }
                , post_reply: "Post"
                , reply_box_placeholder: "Schreibe hier um zu antworten"
                , started_by: "von :user"
            }
            , topics: "Themen"
        }
        , "de.bbcode": {
            bold: "Bold"
            , heading: "Header"
            , image: "Image"
            , italic: "Italic"
            , link: "Link"
            , list: "Liste"
            , list_numbered: "Numerierte Liste"
            , size: {
                _: "Schriftgröße"
                , tiny: "Wintzig"
                , small: "Klein"
                , normal: "Normal"
                , large: "Groß"
            }
            , spoilerbox: "Spoiler Box"
            , strikethrough: "Durchgestrichen"
        }

**Comment by marcostudios** [comment]
There's the osu-web repo for the jizz.ppy.sh, also the translations for the website will be done in the same document as the client translation

**Comment by Hatsuney** [comment]
@marcostudios this was posted nearly 2 months ago

**Comment by failedxyz** [comment]
wrong repo brah

**Comment by Hatsuney** [comment]
@failedxyz this was posted nearly 2 months ago

**Comment by failedxyz** [comment]
:+1:
