### ISSUE TITLE
Touchscreen input completely don't work on Linux

### ISSUE THREAD

**Issue by brainrom** [ppy/osu#10013]
I tried to play osu!lazer with the Silead touchscreen (upstream mainline kernel driver) and encounted, that osu completely do not register touchscreen moving events (only click). Using Wayland. On Xorg osu doesn't register even click events. Other software and classic osu! via Wine works fine. osu!lazer with Wacom tablet also works fine.

**osu!lazer version:** 
Current master

**Comment by peppy** [comment]
Thanks for the report. We can't support individual input devices on linux just yet, but recommend you try with the `--sdl` flag to see if that helps.

**Comment by brainrom** [comment]
Thanks, it actually works with SDL. How I can contribute to make it works with "normal" mode?

**Comment by bdach** [comment]
It's probably not worth the effort as we're looking to replace the current default opentk-derived backend entirely in the longer perspective due to a multitude of platform-specific issues.
