### ISSUE TITLE
Auto attempts to spin spinners that are impossible to complete

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#10011]
**Describe the bug:** 
Not a big problem, close this if you want.
In rare cases, when the spinner is extremely short and is stacked on a hitcircle, it will cause acc drop.
Beatmap: https://osu.ppy.sh/beatmapsets/814850#osu/1901200
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=Yu2Oy1KgTdM
**osu!lazer version:** 
2020.825.0
**Logs:**
Not needed

**Comment by peppy** [comment]
Missing beatmap link. Missing timestamp. Video unclear.

**Comment by Joehuu** [comment]
The beatmap is https://osu.ppy.sh/beatmapsets/814850#osu/1901200. The video is all from lazer with the first half showing a replay from an actual player and the other half being autoplay. Not sure why the OP showed the first half.

FWIW autoplay also attempts to spin on stable, but it misses most of the circles at that part of the map. While in lazer it gets everything, although it's not 100% accuracy. I think this issue wants 100% accuracy on this loved/broken beatmap.

**Comment by PercyDan54** [comment]
> 
> 
> Missing beatmap link. Missing timestamp. Video unclear.

Just as @Joehuu commented
It's really not a big deal, I understand auto can't always be perfect, but this is the problem that auto had with spinners that has length≈0
