### ISSUE TITLE
"Press F2 to save your replay" is always in English

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu#10024]
Most minor issue ever but when you fail a song, the "Press F2 to save your replay" message is always in English, regardless of language. Not sure if this was overlooked or an update to the other languages has not rolled out yet.

Only posting since I only noticed this recently and hadn't seen anyone mention it before.

![image](https://user-images.githubusercontent.com/30021847/91749253-1d396800-ebb9-11ea-800b-eb40be882d09.png)
![image](https://user-images.githubusercontent.com/30021847/91749263-1f9bc200-ebb9-11ea-868b-17342845a4fc.png)

**Comment by bdach** [comment]
Wrong repository. This applies to https://github.com/ppy/osu-stable-issues/.
