### ISSUE TITLE
Separate sound channels for beatmap music and SFX

### ISSUE THREAD

**Issue by Thesola10** [ppy/osu#10025]
**Describe the new feature:** 

I am currently using an effects chain to enhance my listening experience on Linux (ViPER4Linux). It's really nice, except it adds ~200ms worth of latency to the audio. As a result, I can't play with the effects volume higher than 0% because the delay would throw off my rhythm, but I also don't want to give up sound effects, or my effects chain.

My proposal is that the effects would be played back as a different PulseAudio "application" (at least on Linux) so that I can route them away from my effects and cut the latency, while still applying the effects to the music itself.

**Proposal designs of the feature:** 

The latency offset option would still affect the music "channel" as-is. It may be desirable to add a toggle for the feature, as it is kind of niche and could cause problems depending on the system setup.

If possible, the "split channels" option being enabled would add a second device drop-down labeled "Music output" or something.

**Comment by Thesola10** [comment]
PS: I want to fiddle with osu code and implement a prototype myself, but I'm not familiar with the project's code structure or the .NET Core workflow (I _do_ know C# and .NET however). Some advice would be welcome!

**Comment by bdach** [comment]
Sorry to say, but I'm not sure that even if you were to develop something like this, that we would be willing to upstream it. What you're proposing sounds like an awful amount of work (both in development *and* maintenance later) for a benefit that is extremely negligible to 99.9999% of users (and which we couldn't probably even regression test later).

I can definitely say that you definitely *would* have to do the work yourself if you really want that setup to happen.

**Comment by smoogipoo** [comment]
Yeah this isn’t going to happen. I don’t know if it’seven possible at a BASS level - it tends to follow more of a singleton model w.r.t devices.

That’s not to stop you from trying, most code is in TrackBass, SampleBass, and AudioManager.

**Comment by Thesola10** [comment]
thanks for the info, I was just told in osuchat#lazer to create a github issue for it so i thought "might as well give it a try"

if it turns out not to be an ugly hack, I _might_ open a pull request. Might.
