### ISSUE TITLE
Help! osu lazer problem ..

### ISSUE THREAD

**Issue by Emilia33** [ppy/osu#1002]
Problem Details:
hello... i really wanted to know about when i launched the osu lazer .. it give me this error ( A new guard page for the stack cannot be created ) and then i get not responding..
*sorry for bad english ^^

Video or screenshot showing the problem:

http://prntscr.com/ftdtav 

osu!l lazer version: 2017.616.0

**Comment by SlowLogicBoy** [comment]
Readme.md:
> Status
>
>This is still heavily under development and is not intended for end-user use. This repository is intended for developer collaboration. You're welcome to try and use it but please do not submit bug reports without a patch. Please do not ask for help building or using this software.
