### ISSUE TITLE
Media Keys no longer work

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10048]
**Describe the bug:** As title. Media keys (<kbd>next track</kbd>/<kbd>previous track</kbd> and <kbd>play/pause track</kbd>) don't seem to work anymore. Trying to change their keybinds doesn't make them work anyway.

**osu!lazer version:** 2020.903.0

**Comment by frenzibyte** [comment]
Seems like `MusicController` has been moved way too above from such functionality to work, above the `GlobalActionContainer`, as a direct internal child of `OsuGameBase`, I'll work on moving the `OsuGame`-dependent functions to another class instead.

**Comment by peppy** [comment]
can it not just be moved back

**Comment by frenzibyte** [comment]
All tests that DI `MusicController` would have to cache their own `MusicController` in that case, was looking for a way to only fix this issue in a simple way without doing any major changes.

**Comment by peppy** [comment]
On a quick check, changing `AddInternal` to `Add` seems to work as expected?

**Comment by frenzibyte** [comment]
It will only fix the global actions not passed to `MusicController`, but the controller itself attempts to resolve `OnScreenDisplay` to display the actions that have been performed, which is added and cached at `OsuGame` (and doesn't make sense to move it to `OsuGameBase`). 

So it would be kind of a half-assed fix, I'll check if it's feasible and PR what I proposed above and you can decide from there.

**Comment by peppy** [comment]
huh? isn't it coded to handle a null resolution of the OSD..?

**Comment by frenzibyte** [comment]
Yes, but it'll never be able to resolve the OSD anyways, because it's loaded and added to the game hierarchy before OSD is cached, not sure if it's correct for `OsuGameBase` components to depend on `OsuGame` cached components anyways.
