### ISSUE TITLE
Dashboard description goes off-screen

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10049]
It should probably "expand" the description to the left rather than the right, like the "now playing" one.

**Screenshots or videos showing encountered issue:** 
![dashboard](https://user-images.githubusercontent.com/43073074/92128480-bb6c3e80-ee02-11ea-8e7c-17b8bc315a43.png)

**osu!lazer version:** 2020.903.0

**Comment by peppy** [comment]
I saw this while implementing, but disagree that it should just go to the left, unless we apply that to *all* of the icons on the right hand side of the toolbar.

**Comment by peppy** [comment]
Closed via #11420.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/11420.
