### ISSUE TITLE
Menu does not work and does not open

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#10052]
**Describe the bug:** 
As title.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/wvJyVuDHvWk
**osu!lazer version:** 
2020.093.0

**Comment by peppy** [comment]
Please re-read the issue template and follow it properly.

**Comment by Moltanicaa** [comment]
It is impossible to open the settings menu, neither through the icon, nor through Ctrl + O. The 8 second video shows it.

**Comment by peppy** [comment]
Please re-read the [issue template](https://github.com/ppy/osu/issues/new/choose) and follow the instructions properly.
