### ISSUE TITLE
Home and notifications toolbar tooltip titles are title cased while others are lowercased

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#10054]
**Describe the bug:** For this specific issue, the casing regressed as we are now sharing code with overlays. Should all of them be lowercased?

As for all strings, we can avoid casing UI regressions by writing all strings in code lowercase, and then using their methods (e.g. `ToLower{Invariant}`) for the UI.

**Screenshots or videos showing encountered issue:**
![osu!_2v5xWrYkTy](https://user-images.githubusercontent.com/35318437/92151112-6ebe3e80-edd5-11ea-81f7-d3b4a708ee64.png)
![image](https://user-images.githubusercontent.com/35318437/92151162-8269a500-edd5-11ea-9890-9d2ca9027383.png)

**osu!lazer version:** 2020.903.0

**Logs:** not needed

**Comment by bdach** [comment]
My immediate thought is that toolbar text should probably not be all lower-cased if the description isn't. Upper case makes more sense to me.

Humanizer is better suited for capitalisation than `To{Lower,Upper}` - we should be using that.

**Comment by peppy** [comment]
going by the website, the title links are lower case. so maybe we should make both lower in that case..

**Comment by bdach** [comment]
I could agree with both lower too. As long as they're not mixed.
