### ISSUE TITLE
Now playing overlay doesn't animate correctly any more

### ISSUE THREAD

**Issue by peppy** [ppy/osu#10055]
![2020-09-04_09-50-42](https://user-images.githubusercontent.com/191335/92187231-2e71c580-ee94-11ea-9a1b-c2ef5c97c583.gif)

**Comment by frenzibyte** [comment]
Seems to be an issue with `MusicController` track change propagation, these lines:
https://github.com/ppy/osu/blob/ebed7d09e3412206660666a3231b406e4550206d/osu.Game/Overlays/MusicController.cs#L325-L328

are causing `TrackChanged` event to be invoked twice, once with the actual track change direction retrieved via `queuedDirection`, and second time with `TrackChangeDirection.None` as the queued direction has been flushed already, causing the now-playing-overlay background to be reloaded once again with no transforms to the old one.

The lines came from https://github.com/ppy/osu/commit/308d9f59679033e0585cd96b4d5e550c9d2b31d0, removing them don't seem to do any harm, and I can't find the reason they're staying as-is, but I'm not entirely sure about doing so as I haven't fully witnessed all the changes to the "move beatmap track" PR, @peppy seeing that you committed these changes, can you confirm if it's fine to remove them?

**Comment by frenzibyte** [comment]
Nevermind what I proposed above about removing these lines, I can see now why they're necessary (such that `MusicController` doesn't cause a `WorkingBeatmap` change propagation to one that doesn't have its track loaded yet), I believe just early-returning if the provided beatmap `newWorking` is same as the current one should do enough, will PR.
