### ISSUE TITLE
rate changing option in Difficulty Adjust

### ISSUE THREAD

**Issue by PeterBarofsky** [ppy/osu#10065]
Players need more options than 0.75x and 1.5x.
current way to do rate change is rate changer, having this option could minimize the mappack size too.

**Comment by peppy** [comment]
Do you mean speed adjust? If so you can already do that via "double time" or "half time"

**Comment by PeterBarofsky** [comment]
> Do you mean speed adjust? If so you can already do that via "double time" or "half time"

Ok, looks I'm not running the newest lazer
