### ISSUE TITLE
Chrome OS apk crashed a few sends after starting.

### ISSUE THREAD

**Issue by Nella52** [ppy/osu#10068]
**Describe the crash:** 
after starting osu!lazer on Chrome OS using the .apk the game crashed before anything happens
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/62504841/92316443-bd2c3280-efb9-11ea-809c-d49a9f7d7e46.png)

**osu!lazer version:** 
2020.903.0
**Logs:**
 N/A

**Computer Specifications:**

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.
