### ISSUE TITLE
Continues running as a background process after exiting

### ISSUE THREAD

**Issue by JajaUmaOfficial** [ppy/osu#10067]
**Describe the bug:** 
osu! lazer continues running as a background process even after exiting.
I cloned the repo and built locally; running on Windows 10 64-bit.

**Screenshots or videos showing encountered issue:** 
https://imgur.com/a/n1QZZVa

**osu!lazer version:** 
2020.903.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/5178589/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5178590/runtime.log)
[database.log](https://github.com/ppy/osu/files/5178591/database.log)
[network.log](https://github.com/ppy/osu/files/5178592/network.log)

**Comment by bdach** [comment]
Can reproduce, but it's not consistent. It's usually accompanied by star ratings on song select not showing before, so background calculations are the immediate suspect.

**Comment by JajaUmaOfficial** [comment]
I don't think this is what's happening for me; this occurs consistently, even when I just open osu! lazer and exit without opening any menus.
CPU usage is 0 and I see no running tasks after closing and pausing execution in debug mode.
Reattaching the debugger to the process shows a constant memory usage of ~427MB and no CPU usage.

**Comment by bdach** [comment]
then could you please give more details as to what's happening? any weird operations going on any of the remaining threads?

**Comment by peppy** [comment]
creating a memory dump from task manager and sending to pe@ppy.sh would be appreciated

**Comment by JajaUmaOfficial** [comment]
Sent memory dump.

I did some testing on another windows 10 (19041.450) machine and there's no issue.
I tried comparing thread names between the 2 machines[ just before the program exits](https://github.com/ppy/osu/blob/master/osu.Desktop/Program.cs#L63). 
Lists of thread names are attached; nothing looks out of the ordinary as far as I can tell.

[Threads-Good.pdf](https://github.com/ppy/osu/files/5179068/Threads-Good.pdf)
[Threads-Bad.pdf](https://github.com/ppy/osu/files/5179069/Threads-Bad.pdf)

Let me know if there's any better info I can provide; thanks.

**Comment by bdach** [comment]
The raw number of threads in the "bad" example is higher. If I were to bet I would suspect one of the worker threads, although it's impossible to tell without stack traces, but hopefully they'll be visible in the dump you sent anyway.

**Comment by JajaUmaOfficial** [comment]
Ok, I'm 95% sure it's something to do with a midi device and another application; the osu! lazer process ends properly when I my midi kyeboard is unplugged.

I did some more testing on another account on the same machine and I don't see the same issue, so I'm thinking it has to do with an app that's only running on my main account.
There's an error that shows up as a notification sometimes (not consistently) that's something like: "midi device is being used" (sorry for vagueness; I can't reproduce that error notification).

**Comment by peppy** [comment]
I looked into your dump and it does seem like something is getting stuck in the sound or game controller department (one thread is remaining, stuck in `winmmbase`).

![image](https://user-images.githubusercontent.com/191335/92348756-f9bd7280-f10e-11ea-94c9-4333af7c2b27.png)

Hopefully our framework-side [fix](https://github.com/ppy/osu-framework/pull/3870) will alleviate this, but will leave this open to track your specific issue. Please give the next release a try (should be in a few days) and report back.

**Comment by JajaUmaOfficial** [comment]
Issue still exists with osu-framework ver 2020.907.0

**Comment by peppy** [comment]
The fixes are not in the live version yet, please check the next release.

**Comment by JajaUmaOfficial** [comment]
Issue still exists in latest [commit](https://github.com/ppy/osu/commit/6dc382fff5cb82ab7224290c7bc0714dcc0af1d6) running on osu-framework ver 2020.911.0  (Looks like [fix](https://github.com/ppy/osu-framework/commit/e75d6ccf19978652b2e51ea4339bbc2e936e1f78) you linked is included in that release).

**Comment by peppy** [comment]
@JajaUmaOfficial could you please test again after the *next* release (should happen over the next few days)? There have been some more fixes around game controller / midi implementations which may have since resolved this issue.

**Comment by JajaUmaOfficial** [comment]
This issue no longer exists; thanks.
Application now takes awhile to start (5+ seconds as a background process until any window/UI appears); can open a new issue if it isn't already tracked.
