### ISSUE TITLE
osu!lazer doesn't open

### ISSUE THREAD

**Issue by Spellz-etilen** [ppy/osu#10066]
**Describe the crash:** 
I'm just reinstall a clean version of Windows 10. And after I install the game and open, it doesn't show anything
And when I check the Logs folder, very strange that the Logs folder is empty. I have tried to install .Net Core but seems doesn't work

**Screenshots or videos showing encountered issue:** 
Ask me and I will answer with screenshots or something else...

**osu!lazer version:** 
2020.903.0

**Logs:**
Unknown

**Computer Specifications:** 
CPU: Intel Core i3 6098P 3.60GHz

GPU: Intel HD Graphics 510

RAM: 8GB DDR4

**Comment by smoogipoo** [comment]
Check Event Viewer for any application errors.

**Comment by Spellz-etilen** [comment]
> Check Event Viewer for any application errors.

Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5f1757ad
Faulting module name: ntdll.dll, version: 10.0.17763.1, time stamp: 0xa369e897
Exception code: 0xc0000409
Fault offset: 0x00000000000a3550
Faulting process id: 0x7c0
Faulting application start time: 0x01d683588847c25a
Faulting application path: C:\Users\Owner\AppData\Local\osulazer\app-2020.903.0\osu!.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 9f412bc4-0cc1-431a-a570-eebecdc5440c
Faulting package full name: 
Faulting package-relative application ID: 

![image](https://user-images.githubusercontent.com/70795404/92300659-cea81700-ef86-11ea-96d0-0f230ca3464c.png)

**Comment by enoslayd** [comment]
did you install all drivers especially the graphics driver?

**Comment by Spellz-etilen** [comment]
> did you install all drivers especially the graphics driver?

Yes I installed everything

**Comment by bdach** [comment]
We've actually seen similar failures before (see #8686) but currently we don't have a resolution for you there, and it's likely that it's somehow specific to your hardware configuration, which makes this very hard to debug.

Please double-check whether you've restored all drivers after the reinstall; I'm not sure we can provide much more support beyond that part on just these details alone.

**Comment by Spellz-etilen** [comment]
> We've actually seen similar failures before (see #8686) but currently we don't have a resolution for you there, and it's likely that it's somehow specific to your hardware configuration, which makes this very hard to debug.
> 
> Please double-check whether you've restored all drivers after the reinstall; I'm not sure we can provide much more support beyond that part on just these details alone.

well, i just checked Windows Update and install some Security and driver update and it works perfectly now

**Comment by bdach** [comment]
Good to hear. Closing as resolved.
