### ISSUE TITLE
adjust rank threshold requirements to different values

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#10075]
the current ranks thresholds in lazer are:
(pink-plat)SS+=100% with a reading impacting mod
(pink-gold)SS=100%
(blue-plat)S+=95% with a reading impacting mod
(blue-gold)S=95%
(green)A=90%
(yellow)B=80%
(orange)C=70%
(red)D=other
(gray)F=failed

i suggest to change this to:
(pink-plat)SS+=100% with a reading impacting mod
(pink-gold)SS=100%
(purple-plat)S+=98% with a reading impacting mod
(purple-gold)S=98%
(blue-plat)AA+=95% with a reading impacting mod
(blue-gold)AA=95%
(green)A=91%
(yellow)B=85%
(orange)C=77%
(red)D=65%
(light gray)E=other
(darkish gray)F=failed

the S and AA grade in the proposed system are to differentiate between current lower-acc S and higher-acc S 
the raised values on other grades(expect SS) are to encourage players to improve their accuracy

**Comment by Firmatorenio** [comment]
I personally like the idea of an extra rank differentiating between low-acc S and high-acc S, though I'd rather get rid of the double letter grades in general and replace them with + signs. That said, I also like the nice and rounded numbers currently used and generally like the current thresholds. My suggestion would be keeping the current system, but replacing SS with an S+ and adding a new A+ rank in between A and S, like so (H denotes platinum ranks as they are currently):

- SH+ (100% +HD/FL)
- S+ (100%)
- SH (98-100% +HD/FL)
- S (98-100%)
- AH+ (95-98% +HD/FL)
- A+ (95-98%) 
- A (90-95%)
- B (80-90%)
- C (70-80%)
- D (<70%).

An entirely different suggestion would be to simply add a plus sign on any grade that is a full combo, so you can easily tell which maps are mostly perfected - a regular A would be just a score with 90-95% accuracy, but an A+ would be a 90-95% score with a full combo.

These two suggestions kind of clash with each other but I'd adore to see both added in one way or another.

**Comment by peppy** [comment]
We are not getting rid of SS. If you are going to continue discussion here, please make it of the cutoffs specifically, not changing terms.

**Comment by iSimpFor** [comment]
i don't mind rounding out the numbers for grade cutoffs
these values can work then
(pink-plat)SS+=100% with a reading impacting mod
(pink-gold)SS=100%
(purple-plat)S+=98% with a reading impacting mod
(purple-gold)S=98%
(blue-plat)AA+=95% with a reading impacting mod
(blue-gold)AA=95%
(green)A=90%
(yellow)B=80%
(orange)C=70%
(red)D=60%
(light gray)E=under 60%
(darkish gray)F=failed

**Comment by frenzibyte** [comment]
I'm not sure whether it's fine having two issues open both suggesting to change the same thing to different things, but there is this thread https://github.com/ppy/osu/issues/9585.

**Comment by peppy** [comment]
Let's close this in favour of the other one. It looks like a better place to continue discussion.
