### ISSUE TITLE
Taiko kiai glow should be disabled on legacy skins

### ISSUE THREAD

**Issue by blackfate** [ppy/osu#10083]
When you reach a Kiai section in taiko, every time you hit a circle, a pink or blue vertical glow shows up, indicating that you hit a don or kat. Problem is: like several options in the game it confuses players, making it hard to see next notes and confuses you to clicking the opposite note instead.

![opera_AlpsiSVRmj](https://user-images.githubusercontent.com/23140655/92416952-2fc21d00-f136-11ea-9b13-3d6d51b63d4f.png) ![opera_nxZCLmAcmG](https://user-images.githubusercontent.com/23140655/92417131-0655c100-f137-11ea-9c90-9e4c3f6e7eb6.png)

Would be amazing to have a feature to disable it, as no skinning element from stable nor any menu option is able to disable this, and specially with Spotlights coming up with a new season and players wanting to play it more and more. Having more accessibility would be great!

**Comment by Eeveelution** [comment]
I would agree on having the option to enable/disable this, In my experience this can make gameplay quite distracting

**Comment by MandL27** [comment]
This should be a skin-level option imo, disabled by default on legacy skins. In current lazer, the glow shows even on osu!classic.

**Comment by smoogipoo** [comment]
The glow shouldn't be present on legacy skins. Renamed the issue to mention as such.
