### ISSUE TITLE
Overlay pop up sounds in gameplay even though overlays cannot pop up in game

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#10096]
**Describe the bug:** don't know if this a bug or intentional but when im trying to open settings (and other overlays) while in game, the pop up open sounds even though no overlays can pop up

**Screenshots or videos showing encountered issue:** not needed? If needed ill provide a video

**osu!lazer version:** master

**Logs:**
Not needed

**Comment by frenzibyte** [comment]
That's a known bug which has not been fixed yet due to not being a straightforward fix if you look at the PR implementing it. 

Something to do with how the `OsuFocusedOverlayContainer` currently handles being requested to open while in disabled overlay activation mode.
