### ISSUE TITLE
Settings cannot be opened while in gameplay

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#10095]
**Describe the bug:** Settings cannot be opened while in gameplay except when in pause screen or breaks since #9766 being merged. in my opinion it should be an exception since one lazer's advantage over stable is that it allows you to change any settings anywhere in the game.

**Screenshots or videos showing encountered issue:** 
i guess not needed but if you want i can provide one
**osu!lazer version:** master

**Logs:**
not needed?

**Comment by peppy** [comment]
How are you going to change settings while actively playing?

**Comment by bdach** [comment]
you should be able to pause the game to change the settings, as the updated disclaimer screen tip says.

**Comment by enoslayd** [comment]
1. Sometimes when I feel like lost motivation midgame i would change a random setting (ofc it should have no fail first)
2. I have a separate taiko skin from my other skin used in other game modes and i always forget to change them. Ill just open settings change skin then esc then play. (I dont use the pause screen that much in taiko only when im disturbed by someone and pausing is kinda too long for me but it shouldn't be discussed here)

**Comment by peppy** [comment]
And you do this while just missing notes/objects? Sounds like a weird use case to me. Maybe we can make the game auto-pause on attempting to open an overlay.

**Comment by enoslayd** [comment]
I don't really care about those misses.

**Comment by smoogipoo** [comment]
Neither of the above are valid reasons to me. Stable doesn't allow you to do this either, and neither in the pause screen.

If anything, I think the accessibility of options is going to be limited more, not less, once competitive play is considered.

**Comment by peppy** [comment]
Safe to close this for now, I think, as expected behaviour. Feel free to open another issue regarding the sound effects as that does sound like a bug.
