### ISSUE TITLE
when importing a skin, overwrite skins with the same metadata as the skin your importing

### ISSUE THREAD

**Issue by igontusuwu** [ppy/osu#10115]
i suggest this so that we can avoid having duplicate/entries with a element changed when the intention is to just update the skin

this reduces clutter and duplicates on the skin selection tab

**Comment by enoslayd** [comment]
Iirc, If you didnt change anything in skin.ini it will overwrite the existing one

**Comment by peppy** [comment]
This should already be the case, correct.

Can you provide more details of what you're seeing? Perhaps the skin in question doesn't have a `skin.ini` file?

**Comment by enoslayd** [comment]
Example. You imported a skin then change just one detail (e.x. colour1 value) and reimported it. It wont overwrite the first imported one cause of different hash value (idk the right term) so lazer treats them as two different skin even though they have the same name and author (and maybe even the skin version). But if you change an asset instead (e.g. hitcircle.png) but didnt touch the skin.ini, it will be overwritten and put at the bottom of the list. Thats how i understand/think it works

**Comment by peppy** [comment]
I'm hoping to get an answer from the opening poster, since changing the skin.ini is quite rare.

**Comment by enoslayd** [comment]
Changing skin.ini is not a rare occurence (at least for me).  Especially since most of mania's advanced skin configs (e.g. placing the playfield to the left or center) is in skin.ini

**Comment by enoslayd** [comment]
Changing skin.ini is not a rare occurence (at least for me).  Especially since most of mania's advanced skin configs (e.g. placing the playfield to the left or center) is in skin.ini

**Comment by igontusuwu** [comment]
i did a bit of test and i found that:
putting a skin in with different metadata than another skin makes it a separate skin
putting a skin with the same metadata overwrites the old skin, regardless of element changes

it seems like everything is working normally but i'm not sure how there are duplicate skins in my skin tab, i think it's related to a small metadata change or something
i'll close this now
