### ISSUE TITLE
Show PP earned as a decimal

### ISSUE THREAD

**Issue by SilverMK6** [ppy/osu#10110]
Make it so when you submit a new play or improve a current score, the amount of total pp gained should be shown as a decimal because, with lower plays, it'll often show, for example where I am, I'll usually see "+0 pp" even though decimal pp values are a thing, so I think it should show something like "+0,5 pp", because it's a bit annoying not knowing how much you gain off a play, no matter how small

**Comment by enoslayd** [comment]
This sounds like a stable issue?

**Comment by smoogipoo** [comment]
Use https://github.com/ppy/osu-stable-issues for all osu!stable issues.
