### ISSUE TITLE
Storyboard sound samples continue to play when pausing.

### ISSUE THREAD

**Issue by manmathew** [ppy/osu#10112]
I realized this issue when playing tutorial v2, but for maps like the tutorial that have sounds in the storyboard, they continue to play when you pause. It doesn't resume or start over when you resume playing. It's not that big of an issue since few maps have sounds in the storyboard, but it is a bug nevertheless, so eventually it will need to be fixed.

Video of the issue: [https://youtu.be/PPFSqqGd7qw](https://youtu.be/PPFSqqGd7qw)

osu!lazer 2020.903.0

Not sure if logs are really necessary for this issue.

**Comment by peppy** [comment]
This has since been resolved.
