### ISSUE TITLE
Replay SPM depends on playback rate

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#10119]
**Describe the bug:** 
(Probably duplicate of #9821 ? But this is with replays.)
When Autoplay:
If playback rate>1, SPM will be more than 477, up to 955 SPM with 2x playback rate
If playback rate<1, SPM will be less than 477, down to 238 SPM with 0.5x playback rate

You can use a random replay without Autoplay and it's also able to reproduce this
**Screenshots or videos showing encountered issue:** 
![osu_2020-09-10_18-58-52](https://user-images.githubusercontent.com/50285552/92720791-b7f32d00-f397-11ea-9c49-ae8022c5c2b0.jpg)
![osu_2020-09-10_18-58-55](https://user-images.githubusercontent.com/50285552/92720819-c04b6800-f397-11ea-8184-1133d3da0803.jpg)

**osu!lazer version:** 
2020.903.0
**Logs:**
Not needed

**Comment by peppy** [comment]
Counter must be measuring in real-time..

**Comment by PercyDan54** [comment]
> 
> 
> Counter must be measuring in real-time..

The _area_ tag should be _replay_ instead of _gameplay_?

**Comment by bdach** [comment]
I was aware of this when submitting my spinner fixes, but never got around to it. This is because the auto replay generator does not account for mods when generating spinner frames.

Adjusting `ApplyModsTo{Rate,Time}` should fix it if I remember correctly, but I never got around to figuring out the structure of applying rate-adjusting mods to autoplay mods.

**Comment by PercyDan54** [comment]
> 
> 
> I was aware of this when submitting my spinner fixes, but never got around to it. At least the autoplay part is because the auto replay generator does not account for mods when generating spinner frames.
> 
> Adjusting `ApplyModsTo{Rate,Time}` should fix it if I remember correctly, but I never got around to figuring out the structure of applying rate-adjusting mods to autoplay mods.
> 
> Not 100% sure why other replays would be affected, though.

This also happens _without_ Auto.
And I don't think it's an issue with mods, I've tried with AT+DT/ AT+HT and it's all the same.
I think it's with the replay viewer somehow?
