### ISSUE TITLE
Adding the ability to add a map to the collection in the "options" section

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#10123]
**Describe the new feature:** 
In the stable, we can click on f3 (options will open), then we can click on 1, after which the collection editing screen will open, where we can add a map. Here you can do the same, because it is quite convenient (in two clicks).
![image](https://user-images.githubusercontent.com/59089206/92761394-4ff21600-f39a-11ea-9332-6475bc0602db.png)

**Comment by Joehuu** [comment]
Do we want stable's order? Right now the order is wrong:
![osu!_eVaTCtW6RY](https://user-images.githubusercontent.com/35318437/92964224-97bf7e80-f428-11ea-83f3-a0ff32542ade.png)

I would change it to this (please see if the design works):
![dotnet_0RUkih5Weu](https://user-images.githubusercontent.com/35318437/92964307-bcb3f180-f428-11ea-931d-ffdb54113f3e.png)

For multi, should we restrict it to this?
![osu!_yJil7OejRL](https://user-images.githubusercontent.com/35318437/92964399-dead7400-f428-11ea-9a51-842afe516ed9.png)

Played/unplayed will be visible from the beatmap carousel once it's implemented, but the leaderboards are not shown in multi song select now. Only edit is restricted for now.
![dotnet_buIjju1IfD](https://user-images.githubusercontent.com/35318437/92964493-0c92b880-f429-11ea-865f-4c5d68df3034.png)

**Comment by peppy** [comment]
Order isn't too important, make it whatever makes sense.
