### ISSUE TITLE
osu! editor border cuts off all hit objects and approach circles on top and bottom

### ISSUE THREAD

**Issue by signedinteger** [ppy/osu#10124]
**Describe the bug:** 
- hit objects and approach circles to the left and right remain visible
- everything above and below the editor border gets cut off

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/7279624/92768589-b8f18200-f3ca-11ea-90df-5d30d3a758d4.png)

**osu!lazer version:** 2020.903.0

**Logs:**
[performance-audio.log](https://github.com/ppy/osu/files/5203495/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5203496/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5203497/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5203498/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5203499/updater.log)
[database.log](https://github.com/ppy/osu/files/5203501/database.log)
[performance.log](https://github.com/ppy/osu/files/5203503/performance.log)

**Comment by peppy** [comment]
ah yes, meant to fix this one a couple of days ago.
