### ISSUE TITLE
Song select tests intermittently fail

### ISSUE THREAD

**Issue by bdach** [ppy/osu#10127]
Opening for longer form discussion, as I consider this not fit for discord.

Song select tests have [begun](https://ci.appveyor.com/project/peppy/osu/builds/35136187) [to](https://ci.appveyor.com/project/peppy/osu/builds/35137301) [fail](https://ci.appveyor.com/project/peppy/osu/builds/35137619) a lot. As far as I can tell the failures are *not* due to the beatmap fail exceptions (they're a red herring, everything falls back gracefully, *although* the exceptions should probably be silenced to not mislead), but they are indirectly caused by the music controller changes.

Here's one of the relevant parts of one failing test:

https://github.com/ppy/osu/blob/8d550a7b29c90940163fd3d67546087f6f01cd2b/osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs#L385-L396

Because the maps in the scene don't have actual tracks, they use the default 1s virtual track. `MusicController` has a callback registered on track completion, to automatically navigate to the next track:

https://github.com/ppy/osu/blob/d09289b1ce52eefbed3dee61413187ae50e9ba52/osu.Game/Overlays/MusicController.cs#L347-L348

Because of this, it is possible for the following thing to happen:

* The first step succeeds, beatmap and rulesets are changed correctly
* In between that step's completion and one of the asserts the virtual track completes
* Once the virtual track completes, the beatmap is changed away to another one
* The assert fails because the new map is not the one the test is looking for

"Funnily" enough, because of the above scenario running normally will very often be fine locally, but if you breakpoint at the steps, it'll fail every time because the audio thread has the time to execute the track completion callback in the background. Breakpointing at the ruleset value set (so one line after the beatmap is set) pretty much guarantees losing the race every time.

The best idea I've had so far of dealing with this is the following very stupid patch:

```diff
diff --git a/osu.Game/Beatmaps/WorkingBeatmap.cs b/osu.Game/Beatmaps/WorkingBeatmap.cs
index d9780233d..ac1225234 100644
--- a/osu.Game/Beatmaps/WorkingBeatmap.cs
+++ b/osu.Game/Beatmaps/WorkingBeatmap.cs
@@ -264,7 +264,7 @@ public IBeatmap Beatmap
         private Track loadedTrack;
 
         [NotNull]
-        public Track LoadTrack() => loadedTrack = GetBeatmapTrack() ?? GetVirtualTrack(1000);
+        public Track LoadTrack() => loadedTrack = GetBeatmapTrack() ?? GetVirtualTrack(Math.Max(BeatmapInfo.Length, 1000));
 
         /// <summary>
         /// Transfer a valid audio track into this working beatmap. Used as an optimisation to avoid reload / track swap
```

which allows to simulate long tracks by passing the length in metadata, but I'm 200% aware how dumb of an idea that is. (Or, use an actual backing track for the map, I suppose...)

Because the test uses `BeatmapManager` directly, there's not much leeway to work with here without entirely ripping out the manager and swapping it for something we can instrument/mock (which sort of defeats the purpose as it was a good integration test to begin with...)

I suppose the tests affected can also take the snapshot of both bindable values and assert on that instead, but that still doesn't really eliminate the race entirely and also weakens the test to the point that I'm not entirely sure it'd be useful anymore anyway.

Edit: This also very visibly falls over in test browser.

**Comment by peppy** [comment]
The weird part about that explanation that I can't understand is that song select sets `Looping=true` on the track, which should stop `MusicController` from changing the track..

https://github.com/ppy/osu/blob/d09289b1ce52eefbed3dee61413187ae50e9ba52/osu.Game/Overlays/MusicController.cs#L379-L380

**Comment by bdach** [comment]
Good point, I completely failed to spot that. The track in question does not have `Looping` set to true - resolving whatever causes that should be enough to fix the test.
