### ISSUE TITLE
(Manjaro Linux) Lag when playing an osu! map on latest commit

### ISSUE THREAD

**Issue by JapaneseText** [ppy/osu#10151]
**Describe the bug:** 
The gameplay seems to have more lag, after comparing it with the latest release.
The steps to recreating this are to just build osu!lazer and play a beatmap, if I'm not missing something.

**Screenshots or videos showing encountered issue:** 
[https://cdn.discordapp.com/attachments/537757557406695444/754878200441733130/lazerlagproblem-2020-09-13_21.35.23.webm](url)
The lag isn't very noticeable, but it's there.
**osu!lazer version:** 
Commit b2fb175
**Logs:**
[database.log](https://github.com/ppy/osu/files/5215749/database.log)
[network.log](https://github.com/ppy/osu/files/5215750/network.log)
[performance.log](https://github.com/ppy/osu/files/5215751/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5215752/runtime.log)

**Comment by peppy** [comment]
you are linking a commit which touches nothing that could affect anything. likely your end.

**Comment by JapaneseText** [comment]
I have forgotten that you have to add `-c Release` to `dotnet run --project osu.Desktop`, thanks for helping with the issue anyway, since it's the first one I've made here.
