### ISSUE TITLE
Boxes overlapping on the home page

### ISSUE THREAD

**Issue by idontwantagirlfriend** [ppy/osu#10154]
---Bug description---
On 2560x1440 resolution, the client brief box (where beatmap count, playing time and current time are shown) overlaps with the now playing box when the song has unusually long title. Maybe this also happens with other non-widescreen resolutions? 

---Screenshot---
https://osu.ppy.sh/ss/15545263/eb60
![eb60](https://user-images.githubusercontent.com/34613980/93099327-7a194000-f6da-11ea-90ff-627efa230b5f.jpg)

---Logs---
[runtime.log](https://github.com/ppy/osu/files/5219136/runtime.log)

**Comment by bdach** [comment]
You're in the wrong place. See https://github.com/ppy/osu-stable-issues/ (although I imagine this might not be very easy to fix so I wouldn't hold my breath as stable is feature-locked).
