### ISSUE TITLE
Create/Edit buttons for osu!editor in main menu

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10153]
**Describe the new feature:** Right now you can only _create_ a beatmap by pressing the osu!editor button from the main menu, and the only way to _edit_ a beatmap is by going to `Play` > `Solo` > `Right Click` > `Edit` (or using the edit option in the F3 menu).
My idea is to change this by splitting the osu!editor button into two buttons (in a sub-menu):
- A `create` button.
- An `edit` button, which would lead to a "new" carousel (maybe something similar to the stable one, where you just ""play"" the beatmap and the game brings you to the editor), I think maybe it can help some people that are used to the old system.

**Proposal designs of the feature:** I managed to make an example of what I mean by adding some code: [**here's a clip**](https://drive.google.com/file/d/1010FpZpdPLawPv07NGoYhYmBjCP4gqpf/view?usp=sharing) (obviously, the "edit" button just opens the current carousel in my example).

Here's an image for reference:

![editor menu buttons](https://user-images.githubusercontent.com/43073074/93082211-cd66a080-f690-11ea-8c04-454920c3dd39.png)

Actually, I don't know if you have already something in mind for this specific change. If so, then you can reject this proposal.

**Comment by smoogipoo** [comment]
This doesn't make sense coming from main menu. Closing as the plan is to add a selection-type screen.
