### ISSUE TITLE
Failed to retrieve submission score

### ISSUE THREAD

**Issue by sh3zb0t** [ppy/osu#10155]
**Describe the bug:** 
unable to join mutliplayer game (lobby works fine I guess)
**Screenshots or videos showing encountered issue:** 
https://imgur.com/a/74DpgQD
**osu!lazer version:** 
osu-lazer-git-2020.910.0.r60.16d32f5246-1
 archlinux
**Logs:**

[database.log](https://github.com/ppy/osu/files/5219662/database.log)
[network.log](https://github.com/ppy/osu/files/5219664/network.log)
[performance.log](https://github.com/ppy/osu/files/5219665/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5219666/runtime.log)

**Comment by peppy** [comment]
Please use the appimage to play multiplayer.
