### ISSUE TITLE
"osu! lazer" does not start

### ISSUE THREAD

**Issue by kenny-beep** [ppy/osu#10174]
well, i always liked osu and nowadays i found out that there is "osu! lazer" that i really want to play, so i downloaded and did everything right, but when i start the game it doesn't start it appears in the task manager for a few seconds, but then vanish Could someone help me with this?

![image](https://user-images.githubusercontent.com/71408862/93389526-a94ac100-f842-11ea-8397-79a5b112342a.png)

version 2020.910.0

AppData\Roaming\osu\logs:
[runtime.log](https://github.com/ppy/osu/files/5234783/runtime.log)

**Comment by bdach** [comment]
Please adhere to the issue template and attach all logs you have present.

Closing until relevant details are provided.

**Comment by kenny-beep** [comment]
> Siga o modelo de problema e anexe todos os registros que você possui.
> 
> Fechando até que os detalhes relevantes sejam fornecidos.

ready now can you help me?

**Comment by bdach** [comment]
This is suspect:

```
2020-09-16 20:32:29 [verbose]: GL Initialized
2020-09-16 20:32:29 [verbose]: GL Version:                 1.1.0
2020-09-16 20:32:29 [verbose]: GL Renderer:                GDI Generic
2020-09-16 20:32:29 [verbose]: GL Shader Language version:
2020-09-16 20:32:29 [verbose]: GL Vendor:                  Microsoft Corporation
2020-09-16 20:32:29 [verbose]: GL Extensions:              GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
```

We've seen this before with older Intel graphics cards. Please attach DirectX diagnostic info by performing the following steps:

1. Press <kbd>Windows</kbd>+<kbd>R</kbd>, type `dxdiag` in the appearing window and press <kbd>Enter</kbd>.
2. You could be prompted if you'd want Windows to check if the device drivers are signed - there should be no harm in agreeing to that.
3. In the *DirectX Diagnostic Tool* window that will appear, click *Save All Information...* and choose a file to save to.
4. Attach the saved file to this issue.

**Comment by kenny-beep** [comment]
hm ok 
[DxDiag.txt](https://github.com/ppy/osu/files/5234825/DxDiag.txt)

**Comment by bdach** [comment]
It seems that you have an Intel card, most likely from the GMA line, and for some reason Windows is using default drivers that have no support for OpenGL beyond the bare minimum of 1.1.

Please check whether there are device driver updates that resolve your problem. If there aren't, then I'm afraid we might not be able much to do now, as lazer requires OpenGL to work in its current state. Adding DirectX support is planned, but is not likely to happen soon.

**Comment by kenny-beep** [comment]
in windows events this was written 

Application: osu!.exe CoreCLR Version: 4.700.20.26901 .NET Core Version:  Description: The process was terminated due to an internal error in the .NET  Runtime at IP 00007FFFE08E1D5B (00007FFFE0750000) with exit code c0000005.
--

**Comment by bdach** [comment]
That's an access violation error code, which tells us almost next to nothing on its own and will most likely be correlated to the driver. As I said, a driver update (if available) has the biggest chance of resolving this issue for you in the short term.

**Comment by kenny-beep** [comment]
well I'm updating here if it works I speak but if not ... thank you anyway
