### ISSUE TITLE
Changing skin settings during gameplay causes some judgements to show a wrong animation

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10172]
**Describe the bug:** If you change any skin setting (_beatmap hitsounds_ for example) during gameplay, you can notice some judgements with a wrong animation. It seems to happen only with the default skin, but I'm not 100% sure.

**Screenshots or videos showing encountered issue:** 
![Judgement animation](https://user-images.githubusercontent.com/43073074/93328372-e94a7d80-f81b-11ea-8e71-eecd84b05e58.gif)

Very weird, but the wrong animation looks like the osu!classic's one (is it just a coincidence?)

**osu!lazer version:** 2020.910.0

**Comment by peppy** [comment]
The cause of this is `DrawableOsuJudgement` applying transforms on the skinnable content (`JudgementText`) which is being recycled on skin change. I had a look at fixing this but the fix would involve basically rewriting this whole structure to be more like our modern skin implementations.

That said, this should be automatically fixed when #10195 is addressed.

**Comment by Gabixel** [comment]
Looks _mostly_ fixed: there are still some artifacts (is it the correct term?).
- As you can see by [this short video](https://drive.google.com/file/d/1TwZpQwu6hMXN5-vMdxYZG3TD32YjtIpl/view?usp=sharing) (mapset: [Kuba Oms - My Love](https://osu.ppy.sh/beatmapsets/163112#osu/397535)), they still appear, but mostly at the beginning of the map. Also, they disappear without any fade-out effect.
- Here's a closer look with a gif:
![judgements](https://user-images.githubusercontent.com/43073074/100009827-a682c400-2dcf-11eb-9735-5fd07e6081c5.gif)

**Comment by bdach** [comment]
the reproduction scenario is the same as in the OP, correct? asking to confirm whether this is still an issue on `master` (there have been other fixes to judgement animations that might catch this, too).

**Comment by Gabixel** [comment]
Yes, the scenario is the same: load a beatmap and change any skin setting. Tested on latest release ([2020.1121.0](https://github.com/ppy/osu/releases/tag/2020.1121.0)).
One little difference is that it seems easier to reproduce if the skin settings are changed during the player loader.
