### ISSUE TITLE
Option for the old layout

### ISSUE THREAD

**Issue by josedanielsteller** [ppy/osu#10187]
**Describe the new feature:** 
I personally prefer the playfield layout of the old version (this includes the life meter, score, combo, etc.) over the osu!lazer layout, and I'm pretty sure a bunch of other people also would. You should probably add a "legacy layout" option or something for those that dislike the new layout.

**Proposal designs of the feature:** 
Not too sure about this part... Try adding it as an option in the settings or something.

**Comment by peppy** [comment]
One skin implementation is complete, this will be what you see with legacy skins.

**Comment by josedanielsteller** [comment]
> Duplicate of #4632

Uh...whoops. I'm not too familiar with Github, OK??

**Comment by peppy** [comment]
no worries, just housekeeping.
