### ISSUE TITLE
EditorBeatmap.HitObjectUpdated event probably should be fired after post-process

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#10181]
Currently it's fired before.
Or, if current implementation is intentional, would be nice to have an event, which will be fired after, so we can kinda "subscribe" to post-process.
**Why**: I'm making a ruleset with playfield transforms which depends on hitobject properties, which are being calculated in the post-process. So I can't really update these transforms properly with the current implementation.

**Comment by peppy** [comment]
@smoogipoo can you chime in on this one for confirmation that this sounds correct?

**Comment by smoogipoo** [comment]
Yeah I'd say this probably makes sense.

**Comment by peppy** [comment]
@EVAST9919 on checking the code, they already are. Are you per chance talking about `HitObjectUpdated`? This is the only exception.

**Comment by EVAST9919** [comment]
Oh. After https://github.com/ppy/osu/pull/10140 pr, the way `EditorBeatmap` works has been changed, so with these changes in mind - yes.

**Comment by peppy** [comment]
To confirm, you also need `HitObjectUpdate` to be changed?

**Comment by EVAST9919** [comment]
Yes. I'd like it to be fired after post-process as well
