### ISSUE TITLE
Fake note pre-empt mod

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#10197]
in all modes, all notes will have 2 fake objects appear a randomized distance from(but not at) the location where the object is supposed to be hit

then, all fake objects move toward the location of where you're supposed to hit the object near the time you're supposed to hit the object

to help explain what i'm talking about, here's a picture:
![Untitled](https://user-images.githubusercontent.com/44514667/93735313-2c04b080-fba2-11ea-923e-74ff35db860b.png)

**Comment by enoslayd** [comment]
similar to #8835

**Comment by enoslayd** [comment]
also why there are notes outside of taiko and mania playfields?

**Comment by igontusuwu** [comment]
it's supposed to be notes moving in an unintended way to the location you're supposed to hit the note so that you have the read and adapt continuously
