### ISSUE TITLE
osu lazer stopped working

### ISSUE THREAD

**Issue by winosu** [ppy/osu#10194]
guys im using windows 7 and i try osu lazer oldest version and it runs but it stopped working
im installed netframework 4.5 and visuall cc 2010

![screenshot 2](https://user-images.githubusercontent.com/71572261/93690831-62d9b880-fb07-11ea-8a5d-790ac1cb7c35.jpg)

**Comment by bdach** [comment]
What do you mean by "oldest" version? Why not the newest?

As this issue is missing information required by the template, I'm closing until the necessary details are provided. Please provide logs or anything else that we can go on.
