### ISSUE TITLE
Playlist of beatmaps in osu direct and download all button in osulazer

### ISSUE THREAD

**Issue by zzhenryquezz** [ppy/osu#10192]
**Describe the new feature:** 
I have a lot of situations that I lost all my current maps like formating pc, change to linux, pc crash, etc...

So I think it could be nice to have a way to create a playlist in osu direct section and have a button to download all the maps in that playlist.

If the playlist is linked with the user I think that it will be also posible to edit the playlist in the site too.

**Proposal designs of the feature:** 
- Playlist linked with the user profile
- button to download all maps of the playlist

**Comment by bdach** [comment]
Collections will eventually be stored web-side (#9809). Whether "download collection" be a thing I'm not sure but from what I know downloading absolutely all maps is a no-go (#2351).

Going to close this for now as the scope is already somewhat covered by previous requests and we're not at a stage where we would want to actively look into this yet.
