### ISSUE TITLE
Beatmap freezes if restart button is held seconds before the song ends

### ISSUE THREAD

**Issue by SiegeLex** [ppy/osu#1020]
If you **hold the restart button** (the one below the Escape Key on an English Keyboard) **one second after the beatmap ends** or before the last note, the beatmap will freeze.

Following the instructions above, the beatmap restarts. **The beatmap freezes at -0:01 seconds**, **no sounds**, while being able to view the starting circles and the ending circles at the same time.

If you hold the restart button again, the beatmap restarts. **The beatmap's song is working**, but t**he beatmap still freezes at -0:01 seconds**.

If you restart it for the third time, the beatmap works again.

EDIT:
[**Link to the video**](https://youtu.be/sx7-Niequ48) showing the glitch.

Image below (When the beatmap freezes and you hear nothing)
![Freeze](https://user-images.githubusercontent.com/20806483/28233362-39e62e96-68c4-11e7-9610-172634b8e956.png)

**Comment by EVAST9919** [comment]
Can't reproduce anymore

**Comment by Joehuu** [comment]
Closing as this is an old issue/bug. Can't reproduce also.
