### ISSUE TITLE
Mod Customisation container doesn't absorb input correctly

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10210]
**Describe the bug:** (The best way to reproduce this is by increasing the UI size a lot.)
The customisation container shows the mods' tooltip (and the hover sound) when hovering a mod inside of it. I guess that's the wrong UX.
You can also select/deselect a mod by right-clicking it (but not left-clicking).

**Screenshots or videos showing encountered issue:** [Video](https://drive.google.com/file/d/1RyyK4vzkvvt4D9PIPYob0TU_JEbwtLyY/view?usp=sharing) (sorry for bad quality, but it should be enough)

**osu!lazer version:** 2020.910.0

**Comment by stanleyarmstrong** [comment]
So what needs to be fixed is when it's overlayed you should be able to left-click on the mod as well instead of just right clicking?

**Comment by smoogipoo** [comment]
you shouldn't be able to click on the mod at all

**Comment by stanleyarmstrong** [comment]
Oh, ok that makes sense. Would you mind if I try tackling this issue? I will probably have time to do it this Friday

**Comment by smoogipoo** [comment]
Go for it :)

**Comment by bdach** [comment]
I'd ask that you make sure that you're familiar with the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md) and the [primer on input handling in o!f](https://github.com/ppy/osu-framework/wiki/Handling-input-events). The latter is slightly outdated (I'll try to update it over the coming days), but the fundamentals are the same and I believe you should see an easy resolution to this issue if you read it.

**Comment by Visis00** [comment]
Hello, we are a group of student trying a good first issue to solve as part of our studies. Could we try this one ?

**Comment by peppy** [comment]
Go for it.
