### ISSUE TITLE
When streaming, key presses can double it seems

### ISSUE THREAD

**Issue by Reyder95** [ppy/osu#1021]
This really just started when I re-downloaded osu!lazer on a new computer with the latest update (but this never happened before)

https://i.gyazo.com/ef01d29d73dd7e2e2a1e66ff244e94aa.mp4
(not the smartest with github, but here is the video I managed to capture of the issue occurring)

I made sure to turn on key overlay so you could see my key presses (and they don't seem to be going way too fast for the stream) however I end up getting 50s due to overstreaming... anybody else experience this?

Changed refresh rate, tried both fullscreen / windowed mode, but no difference on either.

**Comment by Kontorted** [comment]
A better way to notice this is to press both keys and let go. One of the keys will usually press again, even though input wasn't given. Haven't found the culprit continuing to monitor

**Comment by MrTheMake** [comment]
A video showing this behavior: https://streamable.com/gwjqp. To hit a note/slider, I always pressed both z and x simultaneously. Notice how the key counts gets out of sync. I didn't notice any unintended behavior when hitting the notes themselves so it could just be an issue with the key counter in this case.

**Comment by MrTheMake** [comment]
Here is a better video showing this: https://streamable.com/qm3kk. 
Once again, I was pressing both z and x simultaneously. Notice how the third note is hit even though I didn't press anything.

**Comment by Reyder95** [comment]
@MrTheMake Yes, it seems that it counts K2 when hit and let go as two individual presses. Unsure if it would do the same for K1.

**Comment by bl4ckout31** [comment]
I don't know if it's related, but when I reproduce this, the characters of the keys are typed into the search bar like this: https://streamable.com/v74ph ("à" for z and "y" for x respectively). 
If you listen closely you can even hear the keyboard sound effect.

**Comment by peppy** [comment]
Is this still reproducible?

**Comment by PsYcHo96** [comment]
Just tested. Still reproducible. When both keys are held the first key to release counts as another key press. Does not work for mouse buttons, only keyboard buttons. Happens to either key, it's just whichever is released first

**Comment by PsYcHo96** [comment]
This behaviour isn't limited to key releases. If one button is held and then another is pressed, both actions will trigger. If you hold the left key and hover over 2 overlapping circles and press the right key, both will be hit.
