### ISSUE TITLE
Notification overlay should close automatically if it was opened because of new play starting

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#10222]
To my knowledge, this only happens with "The score overlay is currently disabled ..." notification. It's opened once per run when starting playing. When such a notification causes the notification overlay to open, the overlay should automatically close few seconds after the beatmap has finished loading.

**osu!lazer version:** 
2020.923.0

**Comment by peppy** [comment]
The actual path forward is that these notifications should appear as toasts, and the overlay should not even expand.
