### ISSUE TITLE
DoubleTime, but this time actually 2x and not 1.5

### ISSUE THREAD

**Issue by Bollehumus32** [ppy/osu#10220]
The doubletime modification, but just like NC is added as an extra to the normal "DT" modification, a modification that ACTUALLY doubles the speed of the song added after NC again with extra score multiplier would be cool.

**Comment by smoogipoo** [comment]
Use the mod settings.

**Comment by Bollehumus32** [comment]
Aren't the customizable settings unranked?

**Comment by smoogipoo** [comment]
Lazer doesn't have "ranking" yet. If you're talking about timeshift then they are "ranked".

**Comment by Bollehumus32** [comment]
I see there is an option for adjusting the speed increase of DT, however, when lazer gets a ranking system, will this function be able to give PP and score, by simply adjusting score multiplier according to the value of speed increase? or will it simply be an unranked adjustment?

**Comment by smoogipoo** [comment]
It will give pp and score.

**Comment by Bollehumus32** [comment]
I see. Thank you
