### ISSUE TITLE
Game performance is low when using tablet in fullscreen

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#10223]
**Describe the bug:** 

When I use the tablet, the performance (not only in-game but in general), is reduced, this only happens when using fullscreen mode.
I will attach a video regarding this problem (please look at the input), at first I play this song https://osu.ppy.sh/beatmapsets/37292#osu/120030 using my mouse (Logitech g102), and as you can see, I get always about 8-10ms of input (I usually get less but recording the screen is a bit heavy for my shitty pc) but no more. then I pause the song and disable raw input so I can use my tablet, and as you can see as long as I start moving the cursor it gets big lag spikes, and I get about 11-15ms in gameplay (compared to the 8ms with mouse), but this also happens in song select, or anywhere I use the tablet as the cursor, but only in fullscreen.

**Screenshots or videos showing encountered issue:** 

the video: https://drive.google.com/file/d/1rkqGkO_OML7CU-ZgrF2Y7nH_Vd-dnDnZ/view?usp=sharing

**osu!lazer version:** 

2020.923.0

**Logs:**
[performance-audio.log](https://github.com/ppy/osu/files/5270383/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5270385/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/5270387/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/5270388/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5270389/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5270391/updater.log)
[database.log](https://github.com/ppy/osu/files/5270392/database.log)
[network.log](https://github.com/ppy/osu/files/5270394/network.log)
[performance.log](https://github.com/ppy/osu/files/5270395/performance.log)

**Comment by bdach** [comment]
Please try this scenario again but with performance logging enabled (<kbd>Ctrl</kbd>+<kbd>F2</kbd>) and reattach logs.

Is there a particular reason you're using single-threaded mode?

**Comment by Gonzalo-Bruna** [comment]
> Please try this scenario again but with performance logging enabled (Ctrl+F2) and reattach logs.
> 
> Is there a particular reason you're using single-threaded mode?

yes, there is a reason, i am not sure if it is related or not, but when i changed to single-threaded mode i really felt less input lag while playing, and other people has noticed about that too.

should i record a new video with performance logging enabled or just re-attach the logs?

**Comment by bdach** [comment]
> yes, there is a reason, i am not sure if it is related or not, but when i changed to single-threaded mode i really felt less input lag while playing, and other people has noticed about that too.

This sounds wrong, I sincerely doubt it's input lag. The input thread runs at 1000fps. Were you running with the frame limiter off?

> should i record a new video with performance logging enabled or just re-attach the logs?

I'm mostly looking for the logs, particularly from the input thread.

**Comment by Gonzalo-Bruna** [comment]
> This sounds wrong, I sincerely doubt it's input lag. The input thread runs at 1000fps. Were you running with the frame limiter off?
yeah i know it sounds wrong, I've seen that number but it feels slower, i thought it was my particular case but on the lazer chat a few days ago someone said he was feeling input lag and i told him to change to single-threaded mode, he said it felt much better.

> I'm mostly looking for the logs, particularly from the input thread.

here are the new logs, replicated the scenario, played the same song, first with the mouse, then restart the map, then use the tablet, the lags are only when i move the cursor with the tablet, because i have it always connected.

[performance-draw.log](https://github.com/ppy/osu/files/5271661/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/5271662/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/5271663/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5271664/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5271666/updater.log)
[database.log](https://github.com/ppy/osu/files/5271667/database.log)
[network.log](https://github.com/ppy/osu/files/5271668/network.log)
[performance.log](https://github.com/ppy/osu/files/5271669/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5271672/performance-audio.log)

**Comment by bdach** [comment]
There are slow frames, but that's about as much as I can tell from the logs attached. No stacks, either.

Essentially nothing to go on as far as I can see here. I guess you could post your hardware specs (and the make/model of the tablet in question) but without proper profiling/tracing I can't see us resolving this.

**Comment by Gonzalo-Bruna** [comment]
> There are slow frames, but that's about as much as I can tell from the logs attached. No stacks, either.
> 
> Essentially nothing to go on as far as I can see here. I guess you could post your hardware specs (and the make/model of the tablet in question) but without proper profiling/tracing I can't see us resolving this.

sad to hear that, maybe it is just my particular case.
my specs are good in general, but the problem is i don't have a graphic card, i use the integrated one.

Intel core i5-8250U
12 gb ram
Intel UHD graphics 620
512 gb ssd

the tablet is a Wacom CTL-470

i tested using multi-threaded mode and it seems like it is better when using the tablet, i guess i should close the issue then.

**Comment by Gonzalo-Bruna** [comment]
I just discovered this happens only when holding the pen in the air, if i attach the pen to the tablet it works fine, really weird.

**Comment by bdach** [comment]
Given that you're turning raw input off for the tablet, this might be a case of the input thread being blocked on waiting for inputs from the tablet - as far as I know lifting the pen off more than a few centimetres causes the capacitors in the actual tablet to not receive input.

Why is raw input required for the tablet?

**Comment by Gonzalo-Bruna** [comment]
> Given that you're turning raw input off for the tablet, this might be a case of the input thread being blocked on waiting for inputs from the tablet - as far as I know lifting the pen off more than a few centimetres causes the capacitors in the actual tablet to not receive input.
> 

I mean i lift the pen enough to be able to move the cursor with the tablet, but when i attach it to the tablet the lag goes away. 

> Why is raw input required to be off for the tablet?

because otherwise, the cursor moves to the left corner

**Comment by Joehuu** [comment]
> because otherwise, the cursor moves to the left corner

try unchecking `windows ink` (which can also cause lag/latency and gonna change behavior of pen, but not needed in osu!) in your tablet driver and it should work with raw input.

**Comment by peppy** [comment]
Something is blocking your input thread (`WndProc` time according to your video). This means that either another application on your system is hooking your input, or your tablet driver is actually broken. If you're not on the latest manufacturer drivers, try updating as a first step.

But it's safe to say your issue is not at our end. Feel free to continue discussion in this thread, but I'm going to preemptively close it as not-our-fault.
