### ISSUE TITLE
Support replacing beatmap's song file

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#10221]
**Describe the new feature:** 
On stable you can just go to beatmap's folder and replace the mp3 (it won't even affect the beatmap's ranked status). On lazer it isn't that simple because all the files are hashed. 

Swapping out the mp3 file might be preferred if the original file is low quality or has some other weird artifacts. 

**Proposal designs of the feature:** 
It would probably be a menu where you can select a beatmap, then see it's current mp3 (maybe with its waveform), select a new mp3 and apply an offset to it (mp3 files are notoriously difficult to save in a way that results in same amount of silence at the start as the original mp3)

**Comment by bdach** [comment]
I feel that if this happens it should be an editor feature more than anything, and I'd say it's quite low priority anyway since you can export maps to good old `.osz`s through editor anyway.

**Comment by LittleEndu** [comment]
> you can export maps to good old .oszs through editor anyway

But there should be logic to replace the hashed mp3 file instead of creating a new hash. I changed the mp3 of the 5 minute Wonder Stella edit (because the edit is just so bad, sorry nathan) and you would need to change all 3 maps manually. I feel like this could be easier with lazer.

**Comment by bdach** [comment]
Each file in storage should be stored under a filename that reflects its own hash. If the file is changed, so should the hash. Hashing the new .mp3 under the old hash is actively wrong and misses the point of the hashing scheme entirely.

I imagine this could be done via setup screen, but am still of the opinion that it should still modify the map/hashes. If the source audio of a map with leaderboards is bad, I'd say it should be fixed via enforcing ranking criteria or otherwise. Just allowing a substitution like that opens a loophole for abuse.

**Comment by LittleEndu** [comment]
What I meant by "replace" is that if the file is used by 10 mapsets and I replace it in one, it would be replaced for all of them. Of course it should be saved under the new hash.

About abuse tho, I don't see mp3 swapping opening any avenues for abuse that couldn't already exist by just playing a external audio source with in-game music muted. But I don't think github is a place to discuss this.

**Comment by bdach** [comment]
It would make it *significantly* easier to overlay a click track/metronome over the actual audio to help with timing, for example, which I would say is abuse. Playing audio externally would require synchronisation.

I imagine if it was an editor feature, you should be able to just swap the audio on all difficulties of a set. I'm not sure how multiple sets could end up using one "bad" mp3 - it feels like an incredibly niche situation.

**Comment by Poliwrath** [comment]
For what it's worth, some maps (like [Toumei Elegy](https://osu.ppy.sh/beatmapsets/219380#osu/790048)) have a osz with a alternative mp3 in the description for a different singer. If a metronome provided any actual benefits I'm sure this would've been abused for years like the million other loopholes, and players could just start a external one when they press the enter key to restart a map or whatever... (not hard to sync)

**Comment by peppy** [comment]
This will be feasible via the editor.
