### ISSUE TITLE
Broken latency on Android version

### ISSUE THREAD

**Issue by tsunadegodaime** [ppy/osu#10256]
On build 2020.910.0 everything was fine with latency but starting from 2020.923.0 latency is broken. I"ve added +50ms and game become almost playable but still doesn't feel consistent like on 2020.910.0.

Version: 2020.925.0 (Android)

Logs:
[logs.zip](https://github.com/ppy/osu/files/5286785/logs.zip)

**Comment by bdach** [comment]
Probably will be the nativelibs bump at https://github.com/ppy/osu-framework/pull/3891... Might need to report back to un4seen that this is an issue. Who knows, this might be even a perf regression from the floating point stuff.

**Comment by peppy** [comment]
Need more reports from other android users to figure if this is global or device specific.

**Comment by tsunadegodaime** [comment]
On build 2020.1005.0 issue not exist anymore,
