### ISSUE TITLE
Noticeable Performance Drop after last update

### ISSUE THREAD

**Issue by octo-kumo** [ppy/osu#10269]
**Describe the bug:** 
After the last update, performance has been dropping and there are frequent lag spikes, where the screen just freeze and I get tons of misses.
(I was able to get stable fps 60)

**Screenshots or videos showing encountered issue:** 
<img width="165" alt="Screenshot 2020-09-28 at 1 28 44 PM" src="https://user-images.githubusercontent.com/26460801/94393849-8d261880-018e-11eb-9434-d8c297b4a447.png">

**osu!lazer version:** 
2020.925.0

**Logs:**

_not applicable_

**Comment by peppy** [comment]
Please confirm you have tested against a previous build to rule out the fact it could be something local to your PC. Test back and forth at least 4 times to confirm this.

**Comment by octo-kumo** [comment]
Sorry to leave this thread for so long, I think #10298 explained the issue alot better than I did
