### ISSUE TITLE
Cursor hidden on iOS

### ISSUE THREAD

**Issue by shiro-h** [ppy/osu#10276]
**Describe the bug:** cursor is not showing wright (missing) on gameplay or not on gameplay this is on ios 
Using touchscreen
**Screenshots or videos showing encountered issue:** ![image](https://user-images.githubusercontent.com/68083850/94400020-03c91300-019b-11eb-9841-80a2fa2a849b.png)
![image](https://user-images.githubusercontent.com/68083850/94400033-09265d80-019b-11eb-9a84-b254b57fdea1.png)
**osu!lazer version:** 
Newest (0.1) 2020.925.0
**Logs:**

**Comment by smoogipoo** [comment]
While using touchscreen, or while using external devices (mouse/tablet)? Because this is intended when using touchscreen.

**Comment by shiro-h** [comment]
While using touchscreen

**Comment by smoogipoo** [comment]
When/why do you require seeing the cursor? I don't think this is what we want.

**Comment by shiro-h** [comment]
I need the cursor in game and on main hud cuz i plan to use mouse and keyboard on iOS Already bought the items

**Comment by peppy** [comment]
The cursor will display if you use a mouse.

**Comment by smoogipoo** [comment]
Closing as answered.

**Comment by peppy** [comment]
Have tested and confirmed it does, indeed, display.

**Comment by shiro-h** [comment]
Could have just said earlier thanks!
