### ISSUE TITLE
Snaking offsets slider position in editor drag

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#10278]
This video should explain everything: https://drive.google.com/file/d/10zjBO5RDHe1Qf47anxZV-Iu4lWW9jSxb/view?usp=sharing

If I had to take a guess, it's that the `ScreenSpaceSelectionPoint` of the slider is tracking the head of the slider instead of pointing to the start of the path.

**Comment by peppy** [comment]
Does this happen on release builds?

**Comment by peppy** [comment]
yes, it does. at least not a regression *wipes sweat*.
