### ISSUE TITLE
Fully faded objects can be selected in Editor

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10295]
I tried mapping a bit in lazer just to get a feel for it. One thing that tripped me up a lot though was that fully faded objects could be selected. This probably shouldn't be the case if we're trying to match osu!stable behaviour

Video (next object): https://pennek.s-ul.eu/JgsuRhrO.mp4
Video (previous object): https://pennek.s-ul.eu/k48YKWXl.mp4
osu!lazer version: 2020.925.0

**Comment by peppy** [comment]
this has changed in the next release and should be somewhat better.

**Comment by peppy** [comment]
I've tested this against the latest master and confirmed that it feels better. Please leave a comment after the next release if you still feel it is incorrect.
