### ISSUE TITLE
Add "slider velocity" visualisation in editor

### ISSUE THREAD

**Issue by TheEZIC** [ppy/osu#10293]
Add timing point visualization that will simplify the mapping of SV maps
![Screenshot_2123](https://user-images.githubusercontent.com/35061249/94547820-7b10ac80-0258-11eb-89ab-0825a140b046.png)
You can also add quick editing on click

**Comment by peppy** [comment]
This will be done in a way that can be used across all rulesets, and likely on a hitobject level.
