### ISSUE TITLE
ScoreProcessor is missing tests for all scoring relationships

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#10318]
`ScoreProcessorTest` should ensure that all relationships defined in https://github.com/ppy/osu/wiki/Scoring#hit-results are satisfied - that the correct score portions are affected and the correct `MinResult` is set for each corresponding `MaxResult`.

Additionally, the `HitResultExtensions` methods should also be tested.

**Comment by LittleEndu** [comment]
The wiki is wrong actually, pretty sure ``HitCircle`` can't get Perfect judgments.

**Comment by bdach** [comment]
it'll get fixed soon. scoring is sort of unstable right now, we're addressing that and will update the docs again when that's done. the code is the ground truth anyways, and once the tests come in so will they.

**Comment by LittleEndu** [comment]
Writing a test for the ``HitResultExtensions`` was basically copy-paste ([commit here if anyone wants to continue making this test](https://github.com/LittleEndu/osu/commit/d87e4c524c1c03539881df35fa97ccf800751aae)) but I can't think of any good way to write a test for relationships outside of just having a beatmap with 4 objects that can be judged the certain type we are testing and intentionally judging the 3rd one with ``MinResult`` so the achieved combo is 2/4

**Comment by smoogipoo** [comment]
Even just having those tests would be great.
