### ISSUE TITLE
Several (2 on settings, 1 on mania)

### ISSUE THREAD

**Issue by DeenyBoi** [ppy/osu#10311]
bug 1: keypadmultiply  and keypaddivide on search bar and key configurations wont work (Haven't tried on chat or other chat-related things)
bug 2: on settings, clicking an option wouldn't highlight the part, instead, highlighting the one above
bug 3: mania; changing note speed also changes audio delay
video: https://youtu.be/jawa4-czaXA
might not answer some of the questions because I don't check it quite often

**Comment by smoogipoo** [comment]
Please open one issue for each problem.

**Comment by bdach** [comment]
Second bug is also a duplicate. Please search before opening.
