### ISSUE TITLE
osu! HP drain too harsh after scoring unification changes

### ISSUE THREAD

**Issue by Kaj4r** [ppy/osu#10337]
**Describe the bug:** 
I was playing some beatmaps and when there's a waiting section in the beatmap the HP bar drains faster than it should be and I lose. I played the beatmaps on osu!stable, there's no problem at all.

**osu!lazer version:** 2020.1002.0

**Logs:**

[logs.zip](https://github.com/ppy/osu/files/5319435/logs.zip)

**Comment by bdach** [comment]
We're aware. Will be a consequence of recent scoring standardisation changes (https://github.com/ppy/osu/pull/10288).

**Comment by poly000** [comment]
93.3acc HP 6.5
failed

![图片](https://user-images.githubusercontent.com/34085039/94988127-a1f31980-059d-11eb-8c4d-7372b150d56d.png)

**Comment by shiro-h** [comment]
This happens to me too
