### ISSUE TITLE
Game crashes when moving playback to a spinner in editor

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#10335]
**Describe the crash:** The game crashes when you move the timeline playback to the moment a spinner occurs.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=o-1qRrhwW8M

**osu!lazer version:** 2020.1002.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/5319303/network.log)
[performance.log](https://github.com/ppy/osu/files/5319304/performance.log)
[database.log](https://github.com/ppy/osu/files/5319305/database.log)
[updater.log](https://github.com/ppy/osu/files/5319306/updater.log)
[runtime.log](https://github.com/ppy/osu/files/5319307/runtime.log)

**Computer Specifications:** 
![image](https://user-images.githubusercontent.com/19843905/94949255-e8367300-04e0-11eb-8440-dacf5b0221ef.png)

**Comment by bdach** [comment]
As [stated on discord](https://discord.com/channels/188630481301012481/188630652340404224/761637489336516648) a more reliable reproduction method is to seek back and forth rapidly across the entire beatmap.

It looks like `DrawableSpinnerTick.TriggerResult(false)` can fired on a tick that's already been judged as a miss. Unsure if it should be bypassed locally, or is a symptom of larger breakage, as I haven't read the recent editor autoplay support code.
