### ISSUE TITLE
Editor change handler no-op comparison is expensive

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#10332]
When clicking a hitobject, the ternary state updates trigger value changes that try to add change states, in-turn causing the beatmap to be re-encoded.
This is a no-op because the change states match by checksum, but the performance impact of this is very noticeable on long maps like https://osu.ppy.sh/beatmapsets/121591#osu/311269

![image](https://user-images.githubusercontent.com/1329837/94909012-7f013080-04dd-11eb-9ede-bf6b05e6caba.png)

**Comment by peppy** [comment]
Renamed this issue slightly because I think we actually want to improve this as part of the work which will be done on the change handler in the future (it should be better able to handle no-ops like this so we don't need to code around them locally, IMO).

**Comment by bdach** [comment]
This has been mitigated by https://github.com/ppy/osu/pull/28387, but the proper fix, as mentioned, is probably in scope of https://github.com/ppy/osu/issues/11901, so closing.
