### ISSUE TITLE
Limited to 30 fps

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#10336]
Idk why and with all possible settings i'm still at 30 fps. I have a GTX 1050 3GB and Intel i5-9300H and 8 Gb of RAM.

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

**Comment by MTGPROD** [comment]
Never mind it's just when the PC is not in AC mode it save battery and perfomance is bad

**Comment by Gonzalo-Bruna** [comment]
> Never mind it's just when the PC is not in AC mode it save battery and perfomance is bad

Your pc will perform slower in case you're running out of battery to avoid spending battery when it's needed, it's normal and it will happen with any laptop.
You can change this behaviour in your battery settings.

**Comment by bdach** [comment]
i think @MTGPROD realised that already.

we should probably look into bringing back the stable toast notification reminding users they're on battery power at some point.
