### ISSUE TITLE
Unusual change in star rate when activating Difficulty Adjust Mod.

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#10344]
**Describe the bug:** 
If you enable the appropriate mod, then for some reason the star rate of the last difficulty decreases to 1.72-1.74 *.
It doesn't matter which values you include. It's enough just to enable the mod, which affects the star rate.
https://osu.ppy.sh/beatmapsets/874#osu/6097 
https://osu.ppy.sh/beatmapsets/12483#osu/47875
**Screenshots or videos showing encountered issue:** 
![osu_2020-10-03_04-11-07](https://user-images.githubusercontent.com/59089206/94979934-7b49ca00-052e-11eb-853a-dcf07e66176f.jpg)
![osu_2020-10-03_04-13-20](https://user-images.githubusercontent.com/59089206/94979987-c95ecd80-052e-11eb-92df-44efddfb6213.jpg)
![osu_2020-10-03_04-13-32](https://user-images.githubusercontent.com/59089206/94979990-cfed4500-052e-11eb-8ec5-9a5f624ee44a.jpg)
**osu!lazer version:** 
2020.1002.0

**Comment by smoogipoo** [comment]
This is part of the greater issue which is that mod adjustments don't cause SR to be recalculated (https://github.com/ppy/osu/issues/9669). The difficulty-adjustment values used for recomputation are those set by default for the original (easier) map you had selected first.

**Comment by Theighlin** [comment]
I've confronted 2020.1002.0 against 2021.907.0 and the issue seems to have been resolved, so this issue can be closed.
