### ISSUE TITLE
Android mouse pointer duplication

### ISSUE THREAD

**Issue by tytydraco** [ppy/osu#10345]
**Describe the bug:** 
With an external mouse connected to an Android device, the osu!lazer cursor and the Android system cursor overlap each other.

**Screenshots or videos showing encountered issue:** 
https://photos.app.goo.gl/PZBL3eMvcBsPk7ts9

**osu!lazer version:** 
2020.01002.0

**Logs:**
N/A

**Suggested Patch**
Add a setting toggle to hide the osu! cursor for devices with system-level cursors.

**Comment by bdach** [comment]
Closing in favour of https://github.com/ppy/osu-framework/issues/4373.
