### ISSUE TITLE
Snapping lazer window in Win10 causes window to flicker and have seizures on multiple display setups

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#10342]
**Describe the bug:** When snapping the window anywhere, it can cause that erratic behavior that happens on my two displays.

Can 99.9% reproduce when snapping to the right on the left monitor, and vice versa. Tested on a generic two monitor desktop setup and laptop w/ TV setup. Happens in framework too.

Fixed in SDL as of latest release (2020.1002.0). Just tracking in hope that SDL will go out quicker or get fixed with the current one as it really makes me uncomfortable when it happens.

**Screenshots or videos showing encountered issue:** https://puu.sh/GyPTd/a02ab11122.mp4 (30 fps, don't question about my desktop customization application (Rainmeter) as I can reproduce without it too)

**osu!lazer version:** not SDL started around [2020.508.2](https://osu.ppy.sh/home/changelog/lazer/2020.508.2)

**Logs:** not needed

**Comment by KoleckOLP** [comment]
I got the same issue I had my osu!lazer windowed on my second monitor snapped to the left half of my screen (two 1920x1080 monitors), then I dragged it to my primary monitor and hit <ALT>+<ENTER> to go fullscreen, the window started flickering across both monitors.

video here: https://twitter.com/Koleck0LP/status/1325861775359815683

I have no clue why it happens, I would not blame my graphics card as this never happens with any other game or software. I also don't use any custom snapping zones or anything pretty much stock windows 10.

**Comment by RBRat3** [comment]
How were you snapping your window? It works fine on my end with winkey+arrows its the dragging across monitors that triggers it for me, might have something to do with DPI scaling on asymmetrically sized monitors like in my case dragging from 4K to 1080 sets it off but I dunno.

**osu!lazer version:** 2020.1121.0

**Comment by Joehuu** [comment]
Yep, just dragging reproduces it as seen on the video. I don't have any DPI scaling here, can reproduce on two exact same resolutions (the laptop/tv setup both 1920x1080).

And right, I have to minimize to fix it.

Anyway, the devs are trying to make SDL the default at the moment and no further comments are needed.

**Comment by Joehuu** [comment]
I actually made the duplicate of https://github.com/ppy/osu/issues/9501, closing as resolved.
