### ISSUE TITLE
[mobile] Entering editor causes game to crash

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#10340]
**Describe the crash:** 
Happens with any map, when you go in the editor on iOS, you will get a major stutter then an “Unhandled error” in the notification  center or if you have the log overlay enabled, you’ll see tons of those. Also, the game will continue running (as evidenced by FPS counter) but touch, keyboard and mouse input completely stop working. After a few seconds, the game will then crash to the ios home screen on its own.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/5oy5u3
[Image 1](https://user-images.githubusercontent.com/10524728/94968600-764d3200-04be-11eb-8480-c9e9d5b2e4c7.png)
[Image 2](https://user-images.githubusercontent.com/10524728/94968691-9aa90e80-04be-11eb-8c01-7f5982f20a44.png)

**osu!lazer version:** 
2020.1002.0 to 2020.1020.0

**Logs:**
(I was able to get these since my iPad is jailbroken)
[runtime.log](https://github.com/ppy/osu/files/5320217/runtime.log)
[database.log](https://github.com/ppy/osu/files/5320219/database.log)
[network.log](https://github.com/ppy/osu/files/5320220/network.log)
[performance.log](https://github.com/ppy/osu/files/5320221/performance.log)
Ignore the internet connection errors, school internet is firewalled :)

**Computer Specifications:** 
(From neofetch)
OS: iOS 13.5
Host: iPad Pro 4 (11 Inch)
Kernel: 19.5.0
CPU: Apple A12Z Bionic (8) @ 2.49GHz
GPU: Apple A12Z Bionic GPU
Memory: 931/5690MiB

**Comment by bdach** [comment]
You seem to have failed to attach the logs required.

**Comment by ThatsNiceGuy** [comment]
Got them in.

**Comment by bdach** [comment]
Very weird... crash site seems to be somewhere around

https://github.com/ppy/osu/blob/148e2769c84a24ffd4b70bab4e405402e63006fd/osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/GroupVisualisation.cs#L29-L44

but there's no list access in sight... perhaps invalid build-time optimisations somehow? No idea. Does not reproduce on my linux install, even after trying the beatmap mentioned in the log.

**Comment by peppy** [comment]
Can reproduce, for what it's worth.
