### ISSUE TITLE
Readd sliderend judgments with added leniency

### ISSUE THREAD

**Issue by MandL27** [ppy/osu#10351]
**Describe the new feature:** 
On osu!stable, hitting every tick of the slider except the tail gives a 100/ok for the slider, and the tail neither increments nor breaks combo. In lazer prior to 2020.710.0, sliderends gave a 300/great if hit and broke combo if missed. As of 2020.710.0, sliderends don't affect combo at all; hitting them does not increment combo, and missing them does not break combo. This is a proposal for going closer to stable's behavior: give an imperfect judgment on sliderends if missed, but don't break combo.

**Proposal designs of the feature:** 
Scenario A: holding the slider for its entire duration. This would give a 300/great for the tail, as in older lazer.  
Scenario B: releasing between the last tick and the tail. This would give a 50/meh for the tail. 
Scenario C: releasing before the last tick. This would sliderbreak before the tail and, assuming the slider isn't reclicked, miss the tail entirely.

Like stable, A and B would preserve combo, while C would break combo. Unlike stable, B would still be eligible for a full combo, like current lazer.

**Comment by peppy** [comment]
This is changing in https://github.com/ppy/osu/pull/10349, but not in the way you ask for. Accuracy based judgements are given for actual timed hits now, which slider ends are not. Please check the latest changelog and read up on the new approach to scoring, and wait for the next release to see how it feels with the incoming changes.
