### ISSUE TITLE
Editor creates empty mapsets

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10356]
Entering the Editor always creates a new mapset, even if it is immediately exited and no song/info is given.

Video: https://pennek.s-ul.eu/IjkUBQvd.mp4
osu!lazer version: 2020.1002.0

**Comment by bdach** [comment]
Yep, [was aware of this](https://github.com/ppy/osu/pull/10047#discussion_r483227905). Might as well have an issue tracking this, though.
