### ISSUE TITLE
Some hitsounds will play even if missed

### ISSUE THREAD

**Issue by Contextualist** [ppy/osu#10354]
**Describe the bug:**

When a spinner reach the end (either in a gameplay or in replay), the hit sound sounds like it only plays halfway and then stopped. This is observed every time in every spinner of any map.

**Screenshots or videos showing encountered issue:**

Videos of a spinner in version 2020.1002.0 vs in version 2020.925.0: 
[spinner-end-hitsound.zip](https://github.com/ppy/osu/files/5322139/spinner-end-hitsound.zip)

**osu!lazer version:** 2020.1002.0

**Logs:** [logs.zip](https://github.com/ppy/osu/files/5322094/logs.zip)

**Comment by bdach** [comment]
Slider tick sounds will also play even if the slider isn't tracking. Both issues will be fixed by #10343.
