### ISSUE TITLE
Newly imported beatmaps aren't immediately shown in play screen

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10355]
Newly downloaded beatmaps aren't immediately shown when entering the play screen. This goes for both osu!direct and manual downloads. In osu!stable, entering the play/edit screen after an import immediately shows the imported song

Video: https://pennek.s-ul.eu/eT1F5FPh.mp4
osu!lazer version: 2020.1002.0

**Comment by bdach** [comment]
If you click the import notification, you should be led to the newly-downloaded map. Given that I'm unsure whether we'll be bringing the old behaviour back in its entirety, although maybe it would be nice to bring back anyway?

**Comment by peppy** [comment]
This won't be changing, but the notification will become a toast to make it more obvious/accessible in the future.
