### ISSUE TITLE
Hitsounds cut out abruptly at hitobject end

### ISSUE THREAD

**Issue by SadJefffff** [ppy/osu#10358]
So, basically the problem is that no matter what skin i use or what map i play the hitsounds dont work as intended, the audio cuts when I hit a note so it's very annoying. I never had this kinda error before and I'm a casual player.

I's not the same problems other players had, like the one where the hitsound plays but its the default one, in this case its the skin hitsound that tries to play when you hit a single note but for some reason it only plays the start and then cuts to silence, and in some cases it doesn't even play a sound. The only notes not affected are the long notes who plays the normal hitsound from the skin you are using.
If someone has this issue pls let me know so I can know its not something that affects my pc.

I tried recording my problem but i'm having problems with the recording software so i'm trying to explain my problem.

osu! version: Lazer 2020.1002.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/5322436/runtime.log)
[session.log](https://github.com/ppy/osu/files/5322437/session.log)

**Comment by bdach** [comment]
Did the sounds work properly in the previous release? If so, this is probably #10354 again.

**Comment by SadJefffff** [comment]
They did yesterday. But i played today and suddenly the sounds didn't work as usual.

**Comment by SadJefffff** [comment]
It's in osu!mania btw

**Comment by bdach** [comment]
Did your game auto-update yesterday? Also, if you can't attach the video, at least please attach the skin you're seeing this on. Currently we have nothing to go on here to even begin looking into it as your textual description doesn't tell me much.

**Comment by SadJefffff** [comment]
How can i know if it auto-update?
And about the skin, It's not a skin issue, because it is happening on every skin i use. Even the lazer or the classic one. 
I didn't tweak any option about the sound before the issue started. It may be a auto-update related issue but i don't really know because i'm a casual player and only played few times, so I don't play that much attention to those details. I'm sorry if i am making this harder.

**Comment by SadJefffff** [comment]
The only other option is to reinstall the game, but ill lose everymap and skin i have, right?

**Comment by bdach** [comment]
Can reproduce. This is a regression from #10286. mania has pretty tight lifetime constraints, and so the end of each objects cuts out the samples abruptly.

**Comment by SadJefffff** [comment]
ok thank you! But how do i implement that fix? i'm new to github and how it works.

**Comment by bdach** [comment]
If you're asking for advice for how to fix this issue I'd advise against trying to as a first contribution, as it's a pretty involved and difficult one to address. My comment above is not a fix, merely a diagnosis of what is happening.

**Comment by bdach** [comment]
I've tried the idea of extending the hit objects' lifetime until the sample playback is completed, but I can't say that what I have seems like it can be PRed. [WIP branch here](https://github.com/ppy/osu/commit/0ec75915dc25efd1ce2a2c0af9d59eed5a826743).

To sum up: setting the lifetime is fine for singular hitobjects but breaks down for nested structures, as the parent hitobject also kills its children when its lifetime ends:
