### ISSUE TITLE
"L tick" value in STD mode

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#10353]
Why sometime in standard mode a value called "L tick" appears in the results screen? This isn't only for the CTB mode this?
Sometime he appears, but sometimes this value is missing:

_1. Result screen in Solo Mode:_
![osu_2020-10-03_17-57-01](https://user-images.githubusercontent.com/57914482/94996319-41b3a600-05a4-11eb-8ce8-09f796b18c77.jpg)

_2. Result screen in Multiplayer room:_
![osu_2020-10-03_18-07-12](https://user-images.githubusercontent.com/57914482/94996333-6019a180-05a4-11eb-8fbb-f3ad06ca0c58.jpg)

_3. Result screen in Solo mode 2 (with only GREAT and MEH)_
![osu_2020-10-03_18-19-23](https://user-images.githubusercontent.com/57914482/94996587-cb17a800-05a5-11eb-8e38-d53313d9ee91.jpg)

_4. Global ranking of a map_
![osu_2020-10-03_18-10-46](https://user-images.githubusercontent.com/57914482/94996350-8d664f80-05a4-11eb-91d2-7de2d49b70ff.jpg)

In the case when the score have a least 1 OK and 1 MEH, this value doesn't appears... Except on global ranking of solo mode, I guess...

osu version: 2020.1002.0

**Comment by peppy** [comment]
This shows the count of slider ticks currently and is intended. The display naming will need to be improved to make this more obvious.
