### ISSUE TITLE
tablet tracking froze

### ISSUE THREAD

**Issue by Daraxus** [ppy/osu#10350]
**Describe the bug:** 
i was playing with a tablet (veikk A30) and then suddenly tracking stopped. when i restarted it it worked again.
**Screenshots or videos showing encountered issue:** 
i wasnt recording and couldnt take a screenshot
**osu!lazer version:** 
2020.1002.0
**Logs:**

im not sure how to check the logs

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.
