### ISSUE TITLE
Missing while using the inverse mod causes error messages

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#10369]
Missing a lot while using the inverse mod causes `[important]: DrawableHoldNote applied an invalid hit result (Miss) when IgnoreMiss or IgnoreHit is expected.` errors to show up. This has only started happening since the recent update to 2020.1002.0 and according to the error message, support was supposed to be dropped months ago which is why I'm reporting this as a bug.

**Screenshots or videos showing encountered issue:** https://streamable.com/zngfi2 

**osu!lazer version:** 2020.1002.0

**Logs:** https://www9.zippyshare.com/v/r8Npz1Cr/file.html

**Comment by bdach** [comment]
Will be fixed next release with #10343.
