### ISSUE TITLE
Game crashes when resuming gameplay on a spinner

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10362]
**Describe the bug:** (~~I don't know if it's similar to / the same issue of #10335~~, I guess it has nothing to do with this)
If you pause the gameplay on a spinner and resume, the game crashes and gives an `ArgumentException` about a NaN scaling.

**Screenshots or videos showing encountered issue:** [Video](https://drive.google.com/file/d/1hgwHi7Prpmllm0SFEitfKuK-1cFXOsZK/view?usp=sharing)

**osu!lazer version:** 2020.1002.0

**Logs:** [This is the exception](https://pastebin.com/BneaVE81) (I could also put the entire runtime log, but it just spammed this exception and it's bigger than 10MB).

**Comment by bdach** [comment]
Different issue, regression from #10201. `TrueGameplayRate` is `NaN` on the frame after unpause:

```
[runtime] 2020-10-04 11:56:34 [verbose]: true rate before adjustments = -0
[runtime] 2020-10-04 11:56:34 [verbose]: true rate after adjustments = NaN
```

https://github.com/ppy/osu/blob/db78a0edf4a7b08d1f2fb5c6ab21703777809eb7/osu.Game/Screens/Play/GameplayClock.cs#L39-L54
