### ISSUE TITLE
iOS Compiling Issue

### ISSUE THREAD

**Issue by EzzPrograms** [ppy/osu#10364]
**Describe the bug:** During compilation, all of the rulesets (the four main rulesets) fail to compile due to a linker/MTOUCH issue.
It seems that it couldn't read the Linker.xml file based on the error code that is given.

**osu!lazer version:** 2020.1002.0 Source

**Logs:**
Short log:
`MTOUCH : error MT2017: Could not process XML description: Failed to resolve assembly: 'osu.Game.Rulesets.Catch, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'`

Full log: https://pastebin.com/66CEQnbZ

**Comment by bdach** [comment]
Did you build the entire solution before trying to run the ruleset test projects? It might be that you're trying to run one ruleset test project, but the others are not built yet (because rulesets are independent of each other).

**Comment by EzzPrograms** [comment]
If you mean the osu.iOS part of the solution, then yes. All the other part compile just fine, but the rulesets do fail to compile.

**Comment by peppy** [comment]
Please build the solution, not the csproj. According to the logs you are only building the csproj.

`osu.iOS.slnf` is what you are looking for (or `osu.sln` if your IDE doesn't have `slnf` support)

**Comment by EzzPrograms** [comment]
This is a snippet from the log from Visual Studio. I can give the full log that is given if that helps.

> `osu.iOS.slnf`  is what you are looking for (or `osu.sln` if your IDE doesn't have `slnf` support)
I'm currently using Visual Studio 2019 for Mac and I'm using the slnf file to open the project.

**Comment by peppy** [comment]
Not really sure what to say, other than "it works here" from a fresh checkout. Please check you have all the required dependencies and troubleshoot from your end. Also the fact that the `slnf` works with VS2019 is weird, since it doesn't work here. Maybe that's a good place to start debugging what you have wrong.
