### ISSUE TITLE
Sliderend skins doesn't appear correctly

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#10379]
**Describe the bug:** 
(May caused by #10323)
There's a weird white circle at the slider ends, but not in Stable
Appeared after updating to 2020.1005.0 from 2020.1002.0
**Screenshots or videos showing encountered issue:** 
Lazer:
Non-reverse sliders:
![0toCSs.png](https://s1.ax1x.com/2020/10/06/0toCSs.png)
Reverse sliders:
![0toSYQ.png](https://s1.ax1x.com/2020/10/06/0toSYQ.png)
Stable:
![0toAmV.png](https://s1.ax1x.com/2020/10/06/0toAmV.png)
**osu!lazer version:** 
2020.1005.0
**Logs:**
not needed
**Skin:**
[ALColle 2 - Kaga.zip](https://github.com/ppy/osu/files/5330792/ALColle.2.-.Kaga.zip)

**Comment by bdach** [comment]
Resolved by #10385

**Comment by PercyDan54** [comment]
> 
> 
> Resolved by #10385

Seems fine in local debug.
