### ISSUE TITLE
osu! lazer freeze/crash on startup

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#10375]
**Describe the crash:** 
i just started osu! lazer and it crashed/freezed right away. this never happened before and i can't reproduce this issue.
i just felt like opening an issue even tho this is not the latest osu! lazer version because i'm not sure if this is a rare crash.

**osu!lazer version:** 
2020.925.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/5328787/network.log)
[performance.log](https://github.com/ppy/osu/files/5328788/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5328789/runtime.log)

**Computer Specifications:** 
OS: windows 10 pro 64 bit
CPU: intel core i5-4440
iGPU: intel hd graphics 4600
ram: 8 gb

**Comment by bdach** [comment]
Freaky... Crash site is somewhere here:

https://github.com/ppy/osu/blob/3630aa30d4e3cae2ee6a3e739d9169a1cb10a144/osu.Game/Screens/Menu/Disclaimer.cs#L112-L121

Not sure how a `null` child could ever appear in the text flow, though... Could be that the bind is incorrect? The direct bind is a little suspect.

**Comment by peppy** [comment]
Okay this is a very odd one. Initially looks like an API level issue (missing schedule) but not actually the case. What's happening:

- `Disclaimer` is asynchronously loaded (implicitly by `LoadScreen`).
- During its load process it binds to `currentUser` with a `BindValueChanged` + `runImmediately` parameter, so starts populating the support text flow. (**<- thread access 1**)
- While this is happening, the API finishes a login, schedules the user change to the `API` itself, and runs another game loop which triggers this scheduler to run waiting work.
- From the API scheduler (main thread), the `currentUser.BindValueChanged` is invoked a second time (**<- thread access 2**)

One of the dangers of doing bind callbacks from asynchronous load contexts...
