### ISSUE TITLE
Moving second object before the first one in the timeline causing unexpected behavior

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#10372]
![anim](https://user-images.githubusercontent.com/22874522/95045058-bd6b3b00-06e9-11eb-9c51-e53ab1e748a9.gif)

**Comment by peppy** [comment]
Probably because you're moving before 0ms. Not because you're moving before the first.

**Comment by EVAST9919** [comment]
Not the case:
![anim2](https://user-images.githubusercontent.com/22874522/95045273-42eeeb00-06ea-11eb-97e1-c7dff6ca39e3.gif)

**Comment by peppy** [comment]
Because the first object isn't set to new combo any more?

**Comment by peppy** [comment]
So I began looking into this and though "oh it'll be easy – i'll add forced-`NewCombo` for the first HitObject in `BeatmapProcessor.PreProcess` (see branch: https://github.com/ppy/osu/compare/master...peppy:fix-first-hitobject-must-be-combo?expand=1).

Little did I know that this will run after *every* hitobject change, including `LegacyEditorBeatmapPatcher`, which runs this loop:

![image](https://user-images.githubusercontent.com/191335/95187582-4aa3b200-0806-11eb-92ae-c39a93dfdcbe.png)

Not only is this a pretty large performance concern (it's running `Pre`/`PostProcess` for every hitobject that has changed in the state) but it causes new combos to be fired all over the place and break the implementation.

@smoogipoo thoughts? The only path I can think of is exposing a method in `EditorBeatmap` like `ApplyHitObjectChanges(Action<List<HitObject>> function)` to allow the change handler to perform all its changes in one batch.

**Comment by smoogipoo** [comment]
What do you mean by "after every hitobject change"? Are you saying that the setting of `NewCombo` is changing the index/etc set for other hitobjects in the same loop, and each of those creates a patch?

**Comment by peppy** [comment]
each RemoveAt is calling `PreProcess` / `PostProcess` (see `EditorBeatmap` implementation), so yes.

**Comment by smoogipoo** [comment]
Aha, well not having some sort of debounce there is kinda rough... Not sure how to handle yet.

**Comment by peppy** [comment]
are you against the function method i mention above?

**Comment by smoogipoo** [comment]
I'd probably be okay with that.
