### ISSUE TITLE
Where did the skin folder button go?

### ISSUE THREAD

**Issue by BojayB** [ppy/osu#10376]
This time I DID search and I couldn't find an open or closed issue, so I'm making one. Maybe I just need help and we can close this as soon as possible.
**Describe the bug:** 
I can't seem to find the "Open Skins Folder" button. Even if the button was removed or you're never going to add it back, I'm having trouble finding my skin folder in my directories. I don't see it in my /.local/share/osu folder at all. I even exported and re-imported the skin I was using to see if it would do anything, and I also downloaded a zipped skin and extracted it in the Skins folder I made in that directory. Both results showed negative feedback. I just want to know where my skins folder went :)
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/41974762/95112547-126d7800-070f-11eb-9b05-8776559c2da9.png)

**osu!lazer version:** 
2020.1005.0
**Logs:**

[database.log](https://github.com/ppy/osu/files/5329113/database.log)
[network.log](https://github.com/ppy/osu/files/5329114/network.log)
[performance.log](https://github.com/ppy/osu/files/5329115/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5329116/runtime.log)

**Comment by bdach** [comment]
There is no equivalent of the skins folder in the current system and there will not be, as the skin files are no longer easily human-explorable. All files that are imported to lazer are stored under filenames that reflect their SHA-256 hashes, in the `~/.local/share/osu/files` folder.

For example, a file with the SHA-256 hash of

```
1a47929b6056d34d25a95eeb2012395ceed66af6f40cc37c898a08482d6325d2
```

shall be stored under

```
~/.local/share/osu/files/1/1a/1a47929b6056d34d25a95eeb2012395ceed66af6f40cc37c898a08482d6325d2
```

This is to save storage space by preventing duplicates of the same file from being persisted to disk, and to prevent users from easily tampering with files that should not be tampered with. All inconveniences from stable that arise from this choice have been either addressed by allowing exports or will be adressed in due time by new features (such as an in-game skin editor that allows for changing skin settings).

For now the procedure to modify skins is to export the skin, delete it, and then reimport it again with your desired changes.

**Comment by BojayB** [comment]
I am glad to know the answer to this, thank you!
