### ISSUE TITLE
The cursor behaves like crazy with enabled raw mode (osu!lazer)

### ISSUE THREAD

**Issue by Andryshik345** [ppy/osu#1039]
Hello. When you try to drag the stylus on a graphic tablet, the cursor starts behaving like a crazy(only in raw mode), but there is no such problem on the mouse(in both modes). Well, you can see it on the video.
And there is no such problem on the old client.(osu!latest)

Video: https://streamable.com/zh6a9

P.S: sry, for google translate and ratio on video

**Comment by peppy** [comment]
We are aware that tablets are not yet supported. This is a [framework-level](https://github.com/ppy/osu-framework) issue.
