### ISSUE TITLE
Allow background dimming and blurring in editor

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#10397]
Sometimes the backgrounds are way too bright to work with

![osu!_iPvikLSxvp](https://user-images.githubusercontent.com/35473621/95191743-d9e6a080-07d9-11eb-8416-e11d2a743396.png)

Design can be similar or same to what you already have

**Comment by GSculerlor** [comment]
#7376

**Comment by RaiLTC** [comment]
> #7376

Damn. Couldn't find anything when looked through the issues
