### ISSUE TITLE
Discord Hook Causing Discord Crashes

### ISSUE THREAD

**Issue by hamcoremusic** [ppy/osu#10409]
**Describe the bug:** 
This is a weird one, but every time I launch osu!lazer (and it only happens with this game), it breaks Discord and an error message comes up from it (see screenshot below). I don't know if it directly caused by lazer, or if it is a Discord bug, but as I said earlier, it only happens with lazer.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/28895283/95339656-4917cf80-0882-11eb-95fe-a5c44665111c.png)

**osu!lazer version:** 
2020.10005.00

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/5341083/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5341084/updater.log)
[database.log](https://github.com/ppy/osu/files/5341085/database.log)
[network.log](https://github.com/ppy/osu/files/5341086/network.log)
[performance.log](https://github.com/ppy/osu/files/5341087/performance.log)

**Comment by peppy** [comment]
I would suggest reinstalling discord. It looks like something has corrupt in its update process.

Alternatively, try deleting that "pending" folder.
