### ISSUE TITLE
Osu! In android

### ISSUE THREAD

**Issue by rafavilla3** [ppy/osu#10402]
**Describe the new feature:** I ask to add more compatibility in mobile phones.  The gameplay experience is horrible on cell phones, so I ask you to do it like osu!  droid that thought about compatibility with portable screens making the buttons bigger.  And I also ask for compatibility with skins on Android that is still non-existent.  I really hope you can fix this
**Proposal designs of the feature:** 
I dont know what i put in here.

**Comment by bdach** [comment]
* UI scale can be increased by the UI scale setting in options
* Gameplay input is covered by #4201
* Skin import is covered by #6525 

Closing as duplicate. Please understand that mobile development is not the biggest priority (we're aiming for parity with stable first and foremost) and please search for existing issues in the future.
