### ISSUE TITLE
Fullscreen/Borderless Issues

### ISSUE THREAD

**Issue by hamcoremusic** [ppy/osu#10410]
**Describe the bug:** 
This one is a couple all mashed into one really.

1. When I start osu!lazer, it always opens fullscreen on my second monitor. I need to switch to windowed to bring it back.
2. Alt+Enter does not seem to change the display type when pressed
3. Switching to borderless in the menu crashes the game (has been present for a few months now)

**Screenshots or videos showing encountered issue:** 
I don't really have any screenshots or videos of it happening right now.
**osu!lazer version:** 
2020.1005.00
**Logs:**

[runtime.log](https://github.com/ppy/osu/files/5341125/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5341126/updater.log)
[database.log](https://github.com/ppy/osu/files/5341127/database.log)
[network.log](https://github.com/ppy/osu/files/5341128/network.log)
[performance.log](https://github.com/ppy/osu/files/5341129/performance.log)

**Comment by peppy** [comment]
Please check when using the `--sdl` argument on your lazer shortcut.

**Comment by hamcoremusic** [comment]
Looks like that fixed all 3 of my issues! (I moved the window to the main monitor and made it fullscreen, it now launches on my main monitor every time)

Is it okay to leave the `--sdl` argument in the shortcut for now then?

**Comment by bdach** [comment]
There are some features still missing in SDL (raw input, among others) compared to our current default osuTK backend but if it works for you it should continue to work for now - one day it might not even be required anymore if we do decide to fully migrate.

**Comment by hamcoremusic** [comment]
Ah okay. The raw input thing might suck for a bit but is there no harm in going back? I managed well for now just moving the window over and using the menu to make it windowed/fullscreen again.

Would it be a bad move to put a display picker in the display menu? Just a thought!

**Comment by bdach** [comment]
Could possibly happen at some point. Not exactly a pressing issue, though.

**Comment by hamcoremusic** [comment]
Okay! Thank you both for your help on this.

**Comment by bdach** [comment]
Closing as SDL is now the primary windowing backend (and raw input support has been brought back on windows for it).
