### ISSUE TITLE
Numpad symbol keys aren't recognized.

### ISSUE THREAD

**Issue by Ironkeroro** [ppy/osu#10415]
I use a split on both corners of my keyboard. (`,1,) and (*,-)
the symbol keys on the numpad (/,*,-,+,.) aren't recognized for binding or gameplay.

**Comment by peppy** [comment]
Could you please run the game with the `--sdl` argument and see if this helps?

**Comment by Ironkeroro** [comment]
That works. I've made myself a .bat for now.

**Comment by Joehuu** [comment]
Fixed in SDL as of now.
