### ISSUE TITLE
Game crash upon setting current time on a timing point

### ISSUE THREAD

**Issue by daviskyLV** [ppy/osu#10412]
**Describe the crash:** 
After creating a timing point and using the "Use current time" button to set its time - the game simply crashes. This only happens if the timing point has no attributes, if it has any then it simply logs the error.

**osu!lazer version:** 
2020.1005.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5342913/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5342915/performance.log)
[network.log](https://github.com/ppy/osu/files/5342917/network.log)

**Computer Specifications:** 
OS: Linux Manjaro Cinnamon
Kernel version: 5.8.11-1
RAM: 8GB
i5-7500 and RTX 2060 Super graphics card

**Comment by bdach** [comment]
It'll also crash if a control point group without any attributes is created, albeit on a different exception.
