### ISSUE TITLE
~0ms bar on the extended results screen is overweighted compared to others

### ISSUE THREAD

**Issue by Firmatorenio** [ppy/osu#10426]
**Describe the bug:** The central bar on the timing distribution graph takes more judgements than others and ends up being way taller as a result of bad rounding.
https://github.com/ppy/osu/blob/8dddd8aff56ac819ee8165e42155a9400b5eb9d1/osu.Game/Screens/Ranking/Statistics/HitEventTimingDistributionGraph.cs#L69
`(int)` floors the value, so on the screenshots below (`binSize == 2`) this line of code results in all judgements between (but not equal to) -2ms and +2ms to be put into the ~0ms bar (4ms worth of judgements total), whereas all the other bars only include 2ms worth of judgements.

**Screenshots or videos showing encountered issue:** I played the same map 5 times with different global offset, having noticed the bar in question peaking way out of place way too often. I normally play with +25ms offset. The issue is most visible on +6 and +36ms screenshots, but is still kind of prominent on some others.
![image](https://user-images.githubusercontent.com/12499153/95488826-d6107500-09b7-11eb-9a11-35fc5a03402c.png)
![image](https://user-images.githubusercontent.com/12499153/95488851-df014680-09b7-11eb-88d1-df33b0fa9f4f.png)
![image](https://user-images.githubusercontent.com/12499153/95488893-ea547200-09b7-11eb-9dd2-75d084133c40.png)
![image](https://user-images.githubusercontent.com/12499153/95488920-f2acad00-09b7-11eb-983a-efc30367e38c.png)
![image](https://user-images.githubusercontent.com/12499153/95488941-fa6c5180-09b7-11eb-9309-e9f4e6ce298e.png)

**osu!lazer version:** 2020.1005.0

**Comment by peppy** [comment]
Nice catch, explains why it has always felt way too tall.

**Comment by Firmatorenio** [comment]
I think this gets fixed as easily as replacing `(int)` with `Math.Round` in the referenced line, but I have no idea how to work with git, so better leave it to the pros.
