### ISSUE TITLE
Add a keyboard shortcut to toggle extended results screen

### ISSUE THREAD

**Issue by Firmatorenio** [ppy/osu#10424]
**Describe the new feature:** As a quality of life thing for keyboard-only modes, having some key to toggle extended results (Spacebar or Tab should be good) would be nice.

Alternatively, there could be an option to display extended results by default.

**Comment by Joehuu** [comment]
Should we bind both space and tab for now?

**Comment by peppy** [comment]
at very least the "Select" binding should activate it.
