### ISSUE TITLE
Background dim togleble in the Editor

### ISSUE THREAD

**Issue by KoleckOLP** [ppy/osu#10421]
**Describe the new feature:** 
Dim 100% (black BG) togleble in the editor

**Proposal designs of the feature:** 
maybe a toggle in the to toolbar of the osu editor to make the background black, like ve can enable and disable video.

**Comment by peppy** [comment]
At this point I'd recommend you give your beatmap a solid black png background. If you can't edit your map with a background visible, do you expect people to play with it?

**Comment by KoleckOLP** [comment]
I find that no matter what skin I use I lose my circles in the coloful backgrounds, So I'd like to hide the BG while mapping, I actually play with background dimm too. Or mapbe map with 95% dim.
The best idea would be if background dim settings applied to the editor, but you could toggle it off right in the editor.

**Comment by KoleckOLP** [comment]
Also are there any players that play with 0% background dim, I don't mean to shame I'm actually curious, I see that most players use 100% talking about standard.

**Comment by Gabixel** [comment]
Duplicate of / similar to #7376?

**Comment by bdach** [comment]
Closing as duplicate.

**Comment by Pasi4K5** [comment]
Not sure what happened to the issue this supposedly is a duplicate of, but if it doesn't exist anymore this one should probably be reopened.
