### ISSUE TITLE
Shakers with a finish sample appear big

### ISSUE THREAD

**Issue by Firmatorenio** [ppy/osu#10429]
**Describe the bug:** If a taiko shaker (spinner) has a finish sample assigned to it, it appears unnaturally big (yet gives the same score).

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=hmPkolRrWNQ

**osu!lazer version:** 2020.1005.0

**Comment by bdach** [comment]
This'll be the strong hit = finish logic applying incorrectly to swells.

**Comment by Firmatorenio** [comment]
It appears that both `TaikoBeatmapConverter`
https://github.com/ppy/osu/blob/02d45529fcd46401c773074a2b1a11c237cd9936/osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs#L82 and `DrawableTaikoHitObject`
https://github.com/ppy/osu/blob/02d45529fcd46401c773074a2b1a11c237cd9936/osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs#L155 take the samples (and check for `HIT_FINISH`) from the hitobject individually, but `TaikoBeatmapConverter` applies the correct logic and omits swells from being strong, while `DrawableTaikoHitObject` just applies `isStrong` to anything that has `HIT_FINISH`.

**Comment by bdach** [comment]
That's what I meant, yes.
