### ISSUE TITLE
i cant run osu lazer

### ISSUE THREAD

**Issue by sherouzan** [ppy/osu#10439]
i tried following this problem but its still not fixed
https://github.com/ppy/osu/issues/3966

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

**Comment by sherouzan** [comment]
here is my osu lazer log
[SquirrelSetup.log](https://github.com/ppy/osu/files/5352145/SquirrelSetup.log)

here is my osu standard log
[runtime.log](https://github.com/ppy/osu/files/5352149/runtime.log)
[session.log](https://github.com/ppy/osu/files/5352150/session.log)
[update_success.log](https://github.com/ppy/osu/files/5352151/update_success.log)
