### ISSUE TITLE
Crash in Editor when using 'use current time' button

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10436]
Editor crash after adding a new timing point and using the `use current time` button in a new beatmap. This also happens on timed maps but pops up as an [error](https://i.imgur.com/WJCGSxA.png) instead

video: https://youtu.be/7aZgMbKVGIE (video shows me using 50% playback speed, but I also encounter this issue at 100%)
osu!lazer version: 2020.1005.0

Logs:
[runtime.log](https://github.com/ppy/osu/files/5351744/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5351745/updater.log)
[database.log](https://github.com/ppy/osu/files/5351746/database.log)
[network.log](https://github.com/ppy/osu/files/5351747/network.log)
[performance.log](https://github.com/ppy/osu/files/5351748/performance.log)

**Comment by Joehuu** [comment]
Can you compile `master` and see if it still happens, probably fixed via https://github.com/ppy/osu/pull/10414.

**Comment by peppy** [comment]
Already fixed via https://github.com/ppy/osu/pull/10414.
