### ISSUE TITLE
Error while saving in editor

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10435]
I was trying to `CTRL`+`S` after having finished the Song Setup screen of a new beatmap

screenshot: https://i.imgur.com/BxdVOHU.png
osu!lazer version: 2020.1005.0

Logs:
[runtime.log](https://github.com/ppy/osu/files/5351715/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5351716/updater.log)
[database.log](https://github.com/ppy/osu/files/5351717/database.log)
[network.log](https://github.com/ppy/osu/files/5351719/network.log)
[performance.log](https://github.com/ppy/osu/files/5351727/performance.log)

**Comment by peppy** [comment]
If you aren't attached to your database, please try deleting `client.db`. It looks like yours is in a bad state from a previously failed import.

**Comment by peppy** [comment]
Should be resolved with realm.
