### ISSUE TITLE
osu lazer crashes

### ISSUE THREAD

**Issue by sherouzan** [ppy/osu#10442]
it shows in the task manager for a second then it gets terminated
and i downloaded the last NET.Framework 4.8
and it didn't work
i disabled the windows defender and it didn't work
deleting it and installing it again didn't work
changing the file location didn't work

i tried following this problem but its still not fixed
#3966

 Screenshot:https://prnt.sc/uvv58c

osu!lazer version 2020.1005.0

here is my osu lazer log
[SquirrelSetup.log](https://github.com/ppy/osu/files/5352955/SquirrelSetup.log)

here is my osu standard log
[runtime.log](https://github.com/ppy/osu/files/5352956/runtime.log)
[session.log](https://github.com/ppy/osu/files/5352957/session.log)
[update_success.log](https://github.com/ppy/osu/files/5352958/update_success.log)

%appdata%/osu/logs
[runtime.log](https://github.com/ppy/osu/files/5353116/runtime.log)

i am using win 8.1 pro x64
intel HD graphics [integrated] 64mb vram
processor intel core I5 520m 2.4ghz
RAM: 6gb

**Comment by enoslayd** [comment]
it should be .net core not .net framework. also your logs are not uploaded properly

**Comment by GSculerlor** [comment]
Please just update your previous issue instead of creating a new one. And also you're not attaching any logs here

**Comment by sherouzan** [comment]
i installed the .net core too and still not working

**Comment by sherouzan** [comment]
> Please just update your previous issue instead of creating a new one. And also you're not attaching any logs here
i fixed it and sorry i created a new one

**Comment by sherouzan** [comment]
> it should be .net core not .net framework. also your logs are not uploaded properly
> edit: you dont need osu stable logs either

fixed the logs

**Comment by enoslayd** [comment]
so, theres no logs at %appdata%/osu/logs ?

**Comment by sherouzan** [comment]
> so, theres no logs at %appdata%/osu/logs ?
fixed it srry

**Comment by smoogipoo** [comment]
Please check event viewer for any application errors.

**Comment by sherouzan** [comment]
ok i found 4
1.Application: osu!.exe
CoreCLR Version: 4.700.20.36602
.NET Core Version: 
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFE697B1D5B (00007FFE69620000) with exit code c0000005.

2.Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5f1757ad
Faulting module name: coreclr.dll, version: 4.700.20.36602, time stamp: 0x5f10946b
Exception code: 0xc0000005
Fault offset: 0x0000000000191d5b
Faulting process id: 0x1db4
Faulting application start time: 0x01d69e11dcaa8226
Faulting application path: C:\Users\Sherou\AppData\Local\osulazer\app-2020.1005.0\osu!.exe
Faulting module path: C:\Users\Sherou\AppData\Local\osulazer\app-2020.1005.0\coreclr.dll
Report Id: 1bf4d8d8-0a05-11eb-8345-0023186f6a7c
Faulting package full name: 
Faulting package-relative application ID: 

3.Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

4.svchost (5860) Instance: The database engine detached a database (1, C:\ProgramData\Microsoft\Windows\AppRepository\PackageRepository.edb). (Time=0 seconds) 
 
Internal Timing Sequence: [1] 0.000, [2] 0.000, [3] 0.000, [4] 0.000, [5] 0.000, [6] 0.000, [7] 0.000, [8] 0.000, [9] 0.000, [10] 0.109, [11] 0.031, [12] 0.000. 
Revived Cache: 0 0

**Comment by sherouzan** [comment]
and more
Log Name:      Application
Source:        Windows Error Reporting
Date:          10/9/2020 4:03:22 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      sherouzan
Description:
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: osu!.exe
P2: 0.0.0.0
P3: 5f1757ad
P4: coreclr.dll
P5: 4.700.20.36602
P6: 5f10946b
P7: c0000005
P8: 0000000000191d5b
P9: 
P10: 

Attached files:

These files may be available here:
C:\Users\Sherou\AppData\Local\Microsoft\Windows\WER\ReportQueue\AppCrash_osu!.exe_faaa311954768bbc8faa8241f9f3234853e3a47a_50d1e379_204eaa99

Analysis symbol: 
Rechecking for solution: 0
Report Id: e59f616b-0a05-11eb-8345-0023186f6a7c
Report Status: 4100
Hashed bucket: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-09T08:03:22.000000000Z" />
    <EventRecordID>173055</EventRecordID>
    <Channel>Application</Channel>
    <Computer>sherouzan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5f1757ad</Data>
    <Data>coreclr.dll</Data>
    <Data>4.700.20.36602</Data>
    <Data>5f10946b</Data>
    <Data>c0000005</Data>
    <Data>0000000000191d5b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>C:\Users\Sherou\AppData\Local\Microsoft\Windows\WER\ReportQueue\AppCrash_osu!.exe_faaa311954768bbc8faa8241f9f3234853e3a47a_50d1e379_204eaa99</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>e59f616b-0a05-11eb-8345-0023186f6a7c</Data>
    <Data>4100</Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          10/9/2020 4:03:21 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      sherouzan
Description:
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5f1757ad
Faulting module name: coreclr.dll, version: 4.700.20.36602, time stamp: 0x5f10946b
Exception code: 0xc0000005
Fault offset: 0x0000000000191d5b
Faulting process id: 0x23c0
Faulting application start time: 0x01d69e12a7364fc9
Faulting application path: C:\Users\Sherou\AppData\Local\osulazer\app-2020.1005.0\osu!.exe
Faulting module path: C:\Users\Sherou\AppData\Local\osulazer\app-2020.1005.0\coreclr.dll
Report Id: e59f616b-0a05-11eb-8345-0023186f6a7c
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-09T08:03:21.000000000Z" />
    <EventRecordID>173054</EventRecordID>
    <Channel>Application</Channel>
    <Computer>sherouzan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5f1757ad</Data>
    <Data>coreclr.dll</Data>
    <Data>4.700.20.36602</Data>
    <Data>5f10946b</Data>
    <Data>c0000005</Data>
    <Data>0000000000191d5b</Data>
    <Data>23c0</Data>
    <Data>01d69e12a7364fc9</Data>
    <Data>C:\Users\Sherou\AppData\Local\osulazer\app-2020.1005.0\osu!.exe</Data>
    <Data>C:\Users\Sherou\AppData\Local\osulazer\app-2020.1005.0\coreclr.dll</Data>
    <Data>e59f616b-0a05-11eb-8345-0023186f6a7c</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          10/9/2020 4:03:21 PM
Event ID:      1023
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      sherouzan
Description:
Application: osu!.exe
CoreCLR Version: 4.700.20.36602
.NET Core Version: 
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFE695E1D5B (00007FFE69450000) with exit code c0000005.

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-09T08:03:21.000000000Z" />
    <EventRecordID>173053</EventRecordID>
    <Channel>Application</Channel>
    <Computer>sherouzan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
CoreCLR Version: 4.700.20.36602
.NET Core Version: 
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFE695E1D5B (00007FFE69450000) with exit code c0000005.
</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        edgeupdatem
Date:          10/9/2020 4:01:54 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      sherouzan
Description:
The description for Event ID 0 from source edgeupdatem cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Service stopped

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="edgeupdatem" />
    <EventID Qualifiers="0">0</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-09T08:01:54.000000000Z" />
    <EventRecordID>173052</EventRecordID>
    <Channel>Application</Channel>
    <Computer>sherouzan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Service stopped</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        edgeupdate
Date:          10/9/2020 4:01:54 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      sherouzan
Description:
The description for Event ID 0 from source edgeupdate cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Service stopped

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="edgeupdate" />
    <EventID Qualifiers="0">0</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-09T08:01:54.000000000Z" />
    <EventRecordID>173051</EventRecordID>
    <Channel>Application</Channel>
    <Computer>sherouzan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Service stopped</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        edgeupdate
Date:          10/9/2020 4:00:48 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      sherouzan
Description:
The description for Event ID 0 from source edgeupdate cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Service stopped

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="edgeupdate" />
    <EventID Qualifiers="0">0</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-09T08:00:48.000000000Z" />
    <EventRecordID>173050</EventRecordID>
    <Channel>Application</Channel>
    <Computer>sherouzan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Service stopped</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        edgeupdatem
Date:          10/9/2020 4:00:48 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      sherouzan
Description:
The description for Event ID 0 from source edgeupdatem cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Service stopped

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="edgeupdatem" />
    <EventID Qualifiers="0">0</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-09T08:00:48.000000000Z" />
    <EventRecordID>173049</EventRecordID>
    <Channel>Application</Channel>
    <Computer>sherouzan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Service stopped</Data>
  </EventData>
</Event>

**Comment by smoogipoo** [comment]
Please install any updates you have for your system. You should also check additional requirements for your OS: https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31#additional-deps (but these would be included via Windows update too).

Closing as this is an issue with your OS.
