### ISSUE TITLE
Editor crashes when deleting a control point group

### ISSUE THREAD

**Issue by elweojus** [ppy/osu#10456]
**Describe the crash:** 
Osu crash when you try to delete high bpm timing in the editor, in my case I used 1000bpm
Update: I try with more slowly bpms as 250, 300 and 500 and continues crashing
**Screenshots or videos showing encountered issue:** 
https://youtu.be/zKopdMcnuWI
**osu!lazer version:** 
2020.1009.0
**Logs:**

[network.log](https://github.com/ppy/osu/files/5355911/network.log)
[performance.log](https://github.com/ppy/osu/files/5355912/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5355913/runtime.log)
[database.log](https://github.com/ppy/osu/files/5355914/database.log)

**Computer Specifications:** 
8Gb ram
Intel I3-6006U (2.0Ghz)
Intel HD Graphics 520
Windows 10

**Comment by bdach** [comment]
The BPM value is entirely unrelated. The underlying issue is https://github.com/ppy/osu-framework/issues/3919.

Will keep open for tracking.

**Comment by bdach** [comment]
I'm poking `TextBox` a little bit to see if I can try to get a couple of issues with it fixed, but in the process I noticed this could be band-aided by doing

```diff
diff --git a/osu.Game/Screens/Edit/Timing/GroupSection.cs b/osu.Game/Screens/Edit/Timing/GroupSection.cs
index d76b5e740..c7d55d3ec 100644
--- a/osu.Game/Screens/Edit/Timing/GroupSection.cs
+++ b/osu.Game/Screens/Edit/Timing/GroupSection.cs
@@ -84,13 +84,13 @@ private void load()
                 if (group.NewValue == null)
                 {
                     textBox.Text = string.Empty;
+                    textBox.ReadOnly = true;
 
-                    textBox.Current.Disabled = true;
                     button.Enabled.Value = false;
                     return;
                 }
 
-                textBox.Current.Disabled = false;
+                textBox.ReadOnly = false;
                 button.Enabled.Value = true;
 
                 textBox.Text = $"{group.NewValue.Time:n0}";
```

Not sure if worth PRing, would be good to actually fix textbox but the extensive git history and not enough tests compared to that has me *very* scared...

**Comment by peppy** [comment]
Seems like a fair patch to avoid rewriting the whole class. If you add it, make sure to leave an inline comment explaining what it's doing.
