### ISSUE TITLE
Could not load this beatmap sucessfully

### ISSUE THREAD

**Issue by Nox04** [ppy/osu#1045]
I'm testing osu! on Linux (Manjaro), everything is smooth but when I try to play any beatmap I got that message. I've tried multiple maps, same result. 

Sorry if this's not the place to report this stuff, I just want to let you know about this issue.

This is the runtime.log:

> 7/21/2017 1:57:38 AM: Could not load this beatmap sucessfully (System.NotImplementedException: The method or operation is not implemented.
> 7/21/2017 1:57:38 AM: at osu.Game.Beatmaps.DummyWorkingBeatmap+DummyRulesetInfo+DummyRuleset.CreateHitRendererWith (osu.Game.Beatmaps.WorkingBeatmap beatmap, System.Boolean isForCurrentRuleset) [0x00001] in <4c60a2d2f761405dab9644e1aafffb76>:0
> 7/21/2017 1:57:38 AM: at osu.Game.Screens.Play.Player.load (osu.Framework.Audio.AudioManager audio, osu.Game.Database.BeatmapDatabase beatmaps, osu.Game.Configuration.OsuConfigManager config, osu.Game.OsuGame osu) [0x00163] in <4c60a2d2f761405dab9644e1aafffb76>:0 )!

![gojy1ee](https://user-images.githubusercontent.com/1222006/28446768-9c5bbee2-6d92-11e7-8506-cc67aa13d7d4.png)

PS: I'll try to find some solution and I'll let you know if I get something.

**Comment by peppy** [comment]
Make sure you're on the latest upstream master. This looks like an issue from a previous commit.

**Comment by Nox04** [comment]
You were right. It's fixed in the latest version. Thanks, Mr peppy.
