### ISSUE TITLE
windows key cannot be used in autoplay/replays

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#10467]
**Describe the bug:** when watching autoplay (or any replays), windows key cannot be used. if the lazer window is selected, it will open the start menu once but pressing the windows key again wont close it (essentially, the key cannot be used again). when the lazer window is not selected, pressing windows key wont open the start menu. this also affects shortcuts that has wiindows key in it (e.g. win + r for run dialog box). on sdl, windows key cannot be used. not even opening the start menu once like in osutk nor when the lazer window is delected and shortcuts is affected.

**Screenshots or videos showing encountered issue:** 
(sorry for uploading here, i cant access drive for some reason)
This was made while lazer is in osutk. i used onscreen keyboard for demonstration but its the same when using a physical keyboard
[kjkn.mkv.zip](https://github.com/ppy/osu/files/5358391/kjkn.mkv.zip)

**osu!lazer version:** 2020.1009.0 on windows 10 2004 19041.508

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5358397/runtime.log)

**Comment by peppy** [comment]
This brings up two issues:

- `WindowsKeyBlocker` needs to be updated to ready for `LocalUserInGameplay` state
- Windows key blocking needs to be turned off by us when the window becomes inactive
