### ISSUE TITLE
Dragging bottom timeline while song is playing leads to distorted audio

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10463]
Dragging the bottom timeline while the song is playing leads to distorted sound. Pausing the track until the cursor is released would fix this and match what the top timeline does.

video: https://youtu.be/KCrRC2qEKzs
osu!lazer version: 2020.1009.0

**Comment by peppy** [comment]
This sounds fine for now. Eventually we'll have better effects for seeking audio.
