### ISSUE TITLE
Dragging upper timeline and playing song causes audio to freeze

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10461]
Dragging the upper timeline while the song is paused and then playing the song causes audio to freeze. Somehow I've also been able to drag and start the audio at the same time, causing weird half freezing/stuttering behaviour. (Seen last in the video)

video: https://youtu.be/UMahcTCbTuc
osu!lazer version: 2020.1009.0

**Comment by bdach** [comment]
I don't even think drag makes sense as an action if the timeline is scrolling due to the track playing. Should possibly be disabled entirely?

**Comment by peppy** [comment]
Dragging cancels playback, but this seems like an edge case. Should probably not allow playing while a drag is in progress or something.
