### ISSUE TITLE
New slider curve specifications don't save

### ISSUE THREAD

**Issue by peppy** [ppy/osu#10475]
Using legacy encoder = loss of data. Probably need to add basic support in legacy encoder for now.

**Comment by smoogipoo** [comment]
The encoder already has support for this iirc?

**Comment by peppy** [comment]
If it does, it's not working as intended

before save:
![image](https://user-images.githubusercontent.com/191335/95659509-81f2c580-0b5c-11eb-80be-ede83df8f045.png)

after save:
![image](https://user-images.githubusercontent.com/191335/95659513-8a4b0080-0b5c-11eb-90d0-54fe3c7a4bb2.png)
