### ISSUE TITLE
Timings list in Lazer

### ISSUE THREAD

**Issue by GamingWithJanko** [ppy/osu#10481]
The normal Osu!Stable has this feature:
https://osu.ppy.sh/ss/15658057/ff30

But Lazer doesn't.
There's no timing list when hovering over anything of the map stats. (I tried everything)

I'm not sure, if there's a formula too, or if the timings are stricter/looser.

I need your help to get that into Osu!Lazer.

Greetings from germany,
JGD

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/6202

**Comment by GamingWithJanko** [comment]
Whoops... Sorry. ^^'
