### ISSUE TITLE
OsuDbContext is not disposed in some cases, causing exceptions later on.

### ISSUE THREAD

**Issue by ms2mml** [ppy/osu#10484]
**Describe the bug:** 
There are certain cases where `OsuDbContext` is not disposed properly. This seems to happen because the `usageCompleted()` method in *DatabaseContextFactory.cs* only disposes the underlying context if either the `usage.PerformedWrite` is true, or if `usage.Errors` is non-empty. If these conditions are false, and this happens to the last "use" of a `DatabaseWriteUsage.GetForWrite()` for that thread, then the `recycleThreadContexts()` will no longer be called, and the `OsuDbContext` is never disposed of.

For me, this ends up causing a failure during the folder migration process. At the end of the `Migrate()` method, there is a call to `deleteRecursive(source)`, which fails because the `OsuDbContext` is not disposed of.

**Repro steps (Windows, debugging osu.Desktop):**
1. Delete the `%AppData%/Roaming/osu` folder for a "fresh install"
2. Set a breakpoint at line 266 of *OsuGameBase.cs*: `KeyBindingStore.Register(globalBindings);`
3. Reach that point in the code, then set a breakpoint at line 48 of *KeyBindingStore.cs*: `foreach (var insertable in group.Skip(count).Take(aimCount - count))`
4. Note that the breakpoint in step 3 is never hit, meaning no writes are done at this step.
5. Attempt to use the *Change folder location...* feature to change the osu folder. This will throw an exception when trying to delete the files at the end.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/70926398/95679957-f47a9a00-0b8a-11eb-8d14-34ffcf40dab6.png)
![image](https://user-images.githubusercontent.com/70926398/95680048-84204880-0b8b-11eb-8dc2-8a5fa0d80172.png)

**osu!lazer version:**
Commit 8507327fa6cc6fe03d1dccc7a34231a6234a2e80 on master branch.

**Logs:**
I have added logging to the constructor and dispose method of `OsuDbContext`, as well as a guid to each instance. The following logs are from starting up osu until the main menu loads. The log contains Open/Dispose, ThreadId, ProcessId, Guid of the instance of `OsuDbContext`, and a hash of the stack trace during the call to the constructor.
```
Open		Thread: 1	Process: 20940	Guid: 26924190-3955-41bf-8e7b-232b73ec7544	ee7edb56f4816c86f502e6d025e4349b0649a1f33838f458bb2086cd62862466
Dispose		Thread: 1	Process: 20940	Guid: 26924190-3955-41bf-8e7b-232b73ec7544
Open		Thread: 1	Process: 20940	Guid: f31b5b2a-5301-4236-9a02-92e24d839570	0867b085304cb5a4f4c832c8221f13e1c6ea4033517525e3977c955e9c4a5717
Dispose		Thread: 1	Process: 20940	Guid: f31b5b2a-5301-4236-9a02-92e24d839570
Open		Thread: 1	Process: 20940	Guid: 00329830-3610-4e0d-a673-3c206975a9ec	482b502a7a7f63ade4a4e62f537a3877120570fe13ef5b9f3235a73d7a4f7251
Dispose		Thread: 1	Process: 20940	Guid: 00329830-3610-4e0d-a673-3c206975a9ec
Open		Thread: 1	Process: 20940	Guid: 980249bf-2caa-4426-a05f-4246760eb132	06fa713cb119fb85dc917bbbded0bf8579877f932ed516b1ed5f2168bad1502a
Dispose		Thread: 1	Process: 20940	Guid: 980249bf-2caa-4426-a05f-4246760eb132
Open		Thread: 1	Process: 20940	Guid: e34a2031-2747-402b-b760-6feaf1c8b2ff	a4e0b93700b3ba20bda0318d384a6686e1dbd36873561a578ac99e9cc0a76236
Dispose		Thread: 1	Process: 20940	Guid: e34a2031-2747-402b-b760-6feaf1c8b2ff
Open		Thread: 1	Process: 20940	Guid: 7921b381-aa9e-4279-a2d1-dd61bafb3c23	1ffc8fe99210a5c5d9457c17a19e69d5c543c008f4fd1e9ec24b8c8042cce106
Dispose		Thread: 1	Process: 20940	Guid: 7921b381-aa9e-4279-a2d1-dd61bafb3c23
Open		Thread: 1	Process: 20940	Guid: cdcee667-ab05-4412-b5be-453f9ec446e5	0ffaf689d7378fda7961672a5e95ea0d1c4f5493df68a44cb195bd5e9aed127d
Dispose		Thread: 1	Process: 20940	Guid: cdcee667-ab05-4412-b5be-453f9ec446e5
Open		Thread: 1	Process: 20940	Guid: b517489b-985f-417f-8e6d-8310d0a2abe4	1ab77077dd2cdc08b8910174bffa1afa010cc11e2c57184658b502ac1253b35a
Open		Thread: 12	Process: 20940	Guid: dfefa244-4830-4842-b410-e46e605d49b9	33419c9a489e321358292b8433033575e10c370f78d852cd05506f7ef5f0d76e
Open		Thread: 35	Process: 20940	Guid: d3eb1323-f783-4688-afa4-724c3c381790	9e88a28f139e90d9282c94a4b02d743adc3570e03dc4c5f9fda7ac0a4851eb80
Open		Thread: 34	Process: 20940	Guid: b5904635-5f35-4102-ab86-1b6880ca0e8d	394189a5682a6535564002696a1562d911d8d25247b4a433209287bd1ff962e6
Open		Thread: 45	Process: 20940	Guid: 95083b88-04da-4221-804f-6406a48b9c50	d5cf0617fc90083bc903bba2b78c64b5d8bf1d2876ca2a7be9f4b406f2d61a74
Dispose		Thread: 45	Process: 20940	Guid: 95083b88-04da-4221-804f-6406a48b9c50
Open		Thread: 45	Process: 20940	Guid: 7957cf0c-0f55-4524-a0d0-8723c8e5fa42	d5cf0617fc90083bc903bba2b78c64b5d8bf1d2876ca2a7be9f4b406f2d61a74
Dispose		Thread: 45	Process: 20940	Guid: 7957cf0c-0f55-4524-a0d0-8723c8e5fa42
Open		Thread: 45	Process: 20940	Guid: 870664ec-789d-4ebf-abf0-38adf1386484	8bd2055204b19ac5a92260060351009a80ed03bafbca9c6690111d2b8717f2e2
Open		Thread: 24	Process: 20940	Guid: 7b93f215-3c1d-48e3-bb33-d2f79723fd3a	aaed2da90af09e24609ab3faab3b312b74c8b4beb48ca1431a6b24fcae5911aa
Dispose		Thread: 24	Process: 20940	Guid: 7b93f215-3c1d-48e3-bb33-d2f79723fd3a
Open		Thread: 34	Process: 20940	Guid: 5b4417f3-9d9a-4db3-91a9-bd0a8eaf3674	13dc05ba106e31edf31dad3d725804f60f21715f876c39df6967ea6765274da0
Dispose		Thread: 34	Process: 20940	Guid: 5b4417f3-9d9a-4db3-91a9-bd0a8eaf3674
Open		Thread: 34	Process: 20940	Guid: be0286f1-df4c-41e3-ac68-36d07b3cfed8	aa4a4162d47e6929135489fb868238dfb5d022315772b4a8d41026c2512a48a5
Open		Thread: 35	Process: 20940	Guid: 06f60c2c-bea5-4de1-b1dc-030855acce9a	901fb1273e2ff7b0a97796e6da73d69553af879178b9764a1117595c02652233
Dispose		Thread: 2	Process: 20940	Guid: d3eb1323-f783-4688-afa4-724c3c381790
Dispose		Thread: 2	Process: 20940	Guid: dfefa244-4830-4842-b410-e46e605d49b9
Open		Thread: 36	Process: 20940	Guid: d4b2b18d-82cf-42d2-98ea-c0797701fe2d	f06106fb1adde6dc765ebdb39c66aa8bb3f0d7dddd6c3c20c2ba5ad3a2984026
```
Note that the `OsuDbContext` with Guid b517489b-985f-417f-8e6d-8310d0a2abe4 is never disposed, and the stack trace corresponds to line 266 of *OsuGameBase.cs*.

There are a total of 6 stack traces in the log above where the `OsuDbContext` isn't disposed:
[osu.8bd2055204b19ac5a92260060351009a80ed03bafbca9c6690111d2b8717f2e2.stacktrace.txt](https://github.com/ppy/osu/files/5361181/osu.8bd2055204b19ac5a92260060351009a80ed03bafbca9c6690111d2b8717f2e2.stacktrace.txt)
[osu.901fb1273e2ff7b0a97796e6da73d69553af879178b9764a1117595c02652233.stacktrace.txt](https://github.com/ppy/osu/files/5361182/osu.901fb1273e2ff7b0a97796e6da73d69553af879178b9764a1117595c02652233.stacktrace.txt)
[osu.394189a5682a6535564002696a1562d911d8d25247b4a433209287bd1ff962e6.stacktrace.txt](https://github.com/ppy/osu/files/5361183/osu.394189a5682a6535564002696a1562d911d8d25247b4a433209287bd1ff962e6.stacktrace.txt)
[osu.aa4a4162d47e6929135489fb868238dfb5d022315772b4a8d41026c2512a48a5.stacktrace.txt](https://github.com/ppy/osu/files/5361184/osu.aa4a4162d47e6929135489fb868238dfb5d022315772b4a8d41026c2512a48a5.stacktrace.txt)
[osu.f06106fb1adde6dc765ebdb39c66aa8bb3f0d7dddd6c3c20c2ba5ad3a2984026.stacktrace.txt](https://github.com/ppy/osu/files/5361185/osu.f06106fb1adde6dc765ebdb39c66aa8bb3f0d7dddd6c3c20c2ba5ad3a2984026.stacktrace.txt)
[osu.1ab77077dd2cdc08b8910174bffa1afa010cc11e2c57184658b502ac1253b35a.stacktrace.txt](https://github.com/ppy/osu/files/5361186/osu.1ab77077dd2cdc08b8910174bffa1afa010cc11e2c57184658b502ac1253b35a.stacktrace.txt)

**Comment by peppy** [comment]
Thanks for the report.

This is actually expected. Migration is best-effort. We have a database rewrite in progress which will fix this.

This is why we recommend you migrate the folder *before* interacting with the game.

**Comment by peppy** [comment]
To give more context to "why contexts are left open if read", we do that for performance reasons. There is one per thread, via `ThreadLocal`.

**Comment by ms2mml** [comment]
Thanks for the additional context. What are the intended steps for doing a folder migration? Use the *Change folder location*, run into the delete error, then restart the game?

It also seems like there are some other issues with the migration other than contexts being left open. I.e. the cache directory is not copied over, so if you *Change folder location*, then try to import beatmaps from osu stable without exiting the game first, you will run into cache folder not existing under the new folder, which will cause the game to crash. It seems strange to me that the cache folder is ignored under migration, then it is recreated under the new folder anyways after a game restart.

**Comment by peppy** [comment]
That's interesting, I'll double check on that. Leaving the cache folder at the original location is intended, but it should not cause issues before a restart.
