### ISSUE TITLE
Freeze and crash

### ISSUE THREAD

**Issue by AuracleTech** [ppy/osu#10482]
Situation is pretty complex... Game lag spike so bad it freezes then crash.

[Freeze 1](https://clips.twitch.tv/IntelligentFragilePepperDancingBaby) Game slowly comes to a stop, pretty spooky
[Freeze 2](https://clips.twitch.tv/CuriousBlushingWhalePunchTrees) The gameplay stop responding instantly, yet UI still respond (You can't see it in the video unfortunately as I watch the playback, but the B1 and B2 key bottom right still worked and I could still access Escape menu, then it crashed)

Note : Both crashes are on the same map now that I check replays, but I experience lag everywhere

A peer on stream confirmed he had issues too.

Lazer 2020.1009.0

Ryzen 7 2700 RTX 2060 1 TB NVMe 16GB ram

[runtime.log](https://github.com/ppy/osu/files/5360327/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5360328/updater.log)
[database.log](https://github.com/ppy/osu/files/5360329/database.log)
[network.log](https://github.com/ppy/osu/files/5360330/network.log)
[performance.log](https://github.com/ppy/osu/files/5360331/performance.log)

**Comment by bdach** [comment]
If it only freezes on one particular map, please link it. Also I believe the logs attached are not from the lazer runs shown in any of the clips above.

**Comment by AuracleTech** [comment]
Impossible to reproduce.

I think I know what caused it, a memory leak in my web app, Osu stable could handle low ram avalaible but not lazer on long maps.

Not 100% sure. Either way I'm closing it.
