### ISSUE TITLE
Textures and fonts cant be loaded

### ISSUE THREAD

**Issue by PholomBalam** [ppy/osu#10491]
I downloaded lazer today and when I finished the installation it did not load the textures of the game, it did not load the font.
Try to change the resolution or change the skin but it is inaccessible.

![imagen](https://user-images.githubusercontent.com/72754615/95766854-82cd4980-0c79-11eb-9900-3ba21ff5f270.png)
![imagen](https://user-images.githubusercontent.com/72754615/95766900-92e52900-0c79-11eb-9afd-675703b5ae7e.png)
![imagen](https://user-images.githubusercontent.com/72754615/95766924-9c6e9100-0c79-11eb-9034-a6fe034e027a.png)

Version:Last one, and older too

[DxDiag.txt](https://github.com/ppy/osu/files/5366355/DxDiag.txt)

**Comment by bdach** [comment]
Please attach the full untruncated log files, as well as a dxdiag report by performing the following steps:

1. Press <kbd>Windows</kbd>+<kbd>R</kbd>, type `dxdiag` in the appearing window and press <kbd>Enter</kbd>.
2. You could be prompted if you'd want Windows to check if the device drivers are signed - there should be no harm in agreeing to that.
3. In the *DirectX Diagnostic Tool* window that will appear, click *Save All Information...* and choose a file to save to.
4. Attach the saved file to this issue.

**Comment by peppy** [comment]
Need more information about your system. This is going to be a hardware or drivers isue.

**Comment by PholomBalam** [comment]
Thanks for the advice, i have already updated it

**Comment by bdach** [comment]
The graphics card reported by dxdiag is Radeon X1300/X1550 Series - the Internet states its release date to be somewhere between 2005 and 2007. Some websites are reporting that the card only supports OpenGL up to version 2.0, which is not enough for lazer's use cases.

Unfortunately we cannot do much about this in the short term. We are planning to try alternative graphics backends like Vulkan or DirectX in the indeterminate future, which might yield better results, but for now unfortunately it seems your hardware is incompatible with our current requirements.

**Comment by smoogipoo** [comment]
One thing I'd be curious about is if you go into settings (Ctrl+O), scroll to the bottom, and click the last checkbox, does anything change?
![image](https://user-images.githubusercontent.com/1329837/95807624-9a720400-0d45-11eb-85a1-35273ff8e953.png)

Also interesting that the osu! cookie becomes hidden, which looks like some texture filtering issue that we've had with mipmaps previously.
