### ISSUE TITLE
Local scores don't sort properly

### ISSUE THREAD

**Issue by Firmatorenio** [ppy/osu#10517]
**Describe the bug:** I tried to look into each score, it doesn't seem to me they're even sorted by date. As additional data, these all are taiko scores.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/12499153/96183318-88b47a80-0f58-11eb-85c6-5527c417c621.png)
![image](https://user-images.githubusercontent.com/12499153/96183364-966a0000-0f58-11eb-9dc4-19fac271c4b2.png)
![image](https://user-images.githubusercontent.com/12499153/96183381-9c5fe100-0f58-11eb-8e9e-98f38fe2b82e.png)
![image](https://user-images.githubusercontent.com/12499153/96186065-b3083700-0f5c-11eb-8a17-757e1e17b737.png)
![image](https://user-images.githubusercontent.com/12499153/96186125-cb785180-0f5c-11eb-80aa-52109267dd99.png)

**osu!lazer version:** 2020.1009.0

**Comment by bdach** [comment]
Known issue from #10106, but I guess it can stay open for tracking.

**Comment by Theighlin** [comment]
I think this issue has since been fixed and can be closed.

**Comment by bdach** [comment]
Not entirely (#14664).

**Comment by smoogipoo** [comment]
This one can be closed though.
