### ISSUE TITLE
Changing volume in replay causes lags

### ISSUE THREAD

**Issue by Kolonsky** [ppy/osu#10515]
**Describe the bug:**
The game starts lagging when changing master volume in replay.
Looks like it happening not in the very beginning of replay. In example below it's 1:50. 

**Screenshots or videos showing encountered issue:**
https://youtu.be/_LNaLyzl0yI

**osu!lazer version:**
2020.1009.0

Logs:
[runtime.log](https://github.com/ppy/osu/files/5385936/runtime.log)

**Comment by peppy** [comment]
This is a known issue and will be resolved with hitobject pooling.

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/6129
