### ISSUE TITLE
Extended replay information is not saved

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#10513]
**Describe the bug:** 
It can be watched once - when the replay has been viewed. After entering the menu, everything is lost. Works with both replays of old laser versions and new replays.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/jt-1OKY7QKE
**osu!lazer version:** 
2020.1009.0

**Comment by smoogipoo** [comment]
Extended replay information will likely not ever be saved. There'll probably be a background process to calculate it if anything.

**Comment by Moltanicaa** [comment]
#14472
