### ISSUE TITLE
Combo fonts with custom directories don't appear

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#10525]
**Describe the bug:** skins with fonts with a custom directory defined in skin.ini doesnt appear in lastest master although other skins like the classic skin appears. additionally an error appears on notification panel. although osu catch combo counter still works.

**Screenshots or videos showing encountered issue:** 
skin with custom paths
![osu_2020-10-16_14-40-22](https://user-images.githubusercontent.com/41866328/96221807-c0094280-0fbd-11eb-8415-9e5b724539a5.png)

classic skin
![image](https://user-images.githubusercontent.com/41866328/96221914-f777ef00-0fbd-11eb-90eb-a38450caefa1.png)

eorror
![osu_2020-10-16_14-39-51](https://user-images.githubusercontent.com/41866328/96222340-aa484d00-0fbe-11eb-8c10-4aba0bcda535.png)

skin: https://github.com/enoslayd/outline-skin (the folder outline is the skin)

**osu!lazer version:** master (with acc/score/combo prs already merged)

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5389671/runtime.log)
[database.log](https://github.com/ppy/osu/files/5389672/database.log)

**Comment by peppy** [comment]
See https://github.com/ppy/osu/pull/10522#discussion_r506089410

**Comment by enoslayd** [comment]
but it doesnt include comboprefix??

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/10522.
