### ISSUE TITLE
Additional digit on score display in legacy skins

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#10535]
**Describe the new feature:** in stable, score displays 8 digits and by default they display zeros. What i propose is that in lazer, when in standardized scoring, it should display 7 digits instead of currently 6, and when in classic, it should imitate stable with 8 digits instead of currently 6.

**Proposal designs of the feature:** Just an additional digit

Edit: ooff, sorry this just a nitpick of mine

**Comment by bdach** [comment]
This is easy enough to resolve in the most obvious manner but I'm unconvinced it makes sense to display 8 digits if standardised scoring is on. Should probably only be the case with classic.

**Comment by enoslayd** [comment]
> This is easy enough to resolve in the most obvious manner but I'm unconvinced it makes sense to display 8 digits if standardised scoring is on. Should probably only be the case with classic.

Ummm, thats what i said in my post

**Comment by enoslayd** [comment]
so..... the classic score display is fine now but the standardized is still using 6 digits

**Comment by peppy** [comment]
Yes. This is intended.
