### ISSUE TITLE
Offical 3DS Port? (Continued)

### ISSUE THREAD

**Issue by TheNamesGregoryAndounuts** [ppy/osu#10533]
Hi, my issue (https://github.com/ppy/osu/issues/10529) got closed before I could ask a few questions regarding peppy's response;

>https://github.com/echojc/osu-ds This is the closest you'll get.
>lazer is not made to run on the 3DS.

_Originally posted by @peppy in https://github.com/ppy/osu/issue_comments/709927715_

So why isn't lazer 3DS optimized? (Don't be afraid to get too technical.) Why aren't the team looking into this? And what am I supposed to do with this repository?

**Comment by peppy** [comment]
You are in the wrong place. osu! is targeted at platforms which support the underlying technologies we are using.

You are welcome to make your own fan project targeting other platforms but we know for a fact this version of osu! will never run on 3DS. Switch? yes, that is already feasible. 3ds? no.
