### ISSUE TITLE
Some skins have problem with UI scaling and don't have the options in Autoplay

### ISSUE THREAD

**Issue by elweojus** [ppy/osu#10538]
**Describe the bug:** 
Some skins have next problems:
- Don't scale properly
- Offset on autoplay options (huge)
UI scaling maybe, but I'm not sure

**Screenshots or videos showing encountered issue:** 
**Scale**: 1x Works fine
![osu_2020-10-16_12-10-24](https://user-images.githubusercontent.com/50848502/96290774-263d9780-0fb5-11eb-94ab-f98dda8791ea.jpg)
**Scale**: 1.15x (has some problems on the overlay)
![osu_2020-10-16_12-09-55](https://user-images.githubusercontent.com/50848502/96290839-41100c00-0fb5-11eb-88ec-914285a34346.jpg)
**This skin doesn't have autoplay options**
![osu_2020-10-16_12-12-49](https://user-images.githubusercontent.com/50848502/96290900-54bb7280-0fb5-11eb-8e80-16b78dda5dee.jpg)

**Skins**:
http://www.mediafire.com/file/l3573ohbh1xm9l8/skins.rar/file

**osu!lazer version:** 

2020.1017.0

**Comment by bdach** [comment]
Using skin UI elements to add a playfield border was always a workaround at best and therefore I'm not sure we should put in effort to support it. I don't know what "autoplay options" are supposed to mean in this context, either.

**Comment by elweojus** [comment]
Sorry for the misundertood 
**Scale**: 0.8x, playback and input settings
![osu_2020-10-16_13-06-05](https://user-images.githubusercontent.com/50848502/96293626-0dcf7c00-0fb9-11eb-8409-ecef8e511626.jpg)

**Comment by bdach** [comment]
Ok, that *is* pretty bad. Thanks for clarifying.

**Comment by peppy** [comment]
We probably want to limit the size of texture reads for such cases to a sane maximum.

**Comment by Steinosu** [comment]
This also happens with lower than x1 scaling

[https://i.imgur.com/qcFQpep.png](url)

**Comment by peppy** [comment]
That will also be resolved by either updating your skin, or from the elements being forcefully trimmed.

**Comment by Joehuu** [comment]
Can we just put it below accuracy counter temporary for now? All this hard coded layout stuff will break/get removed anyway when user customization gets implemented.

Works with legacy skins with the *playfield border* health displays. Don't really want breaking things with trimming at the moment, as that'll cause confusion and false issues.

```diff
diff --git a/osu.Game/Screens/Play/HUDOverlay.cs b/osu.Game/Screens/Play/HUDOverlay.cs
index c3de249bf..af5e2b80e 100644
--- a/osu.Game/Screens/Play/HUDOverlay.cs
+++ b/osu.Game/Screens/Play/HUDOverlay.cs
@@ -208,17 +208,9 @@ protected override void Update()
         {
             base.Update();

-            float topRightOffset = 0;
+            // for now align with the accuracy counter. eventually this will be user customisable.
+            topRightElements.Y = ToLocalSpace(AccuracyCounter.Drawable.ScreenSpaceDrawQuad.BottomRight).Y;

-            // fetch the bottom-most position of any main ui element that is anchored to the top of the screen.
-            // consider this kind of temporary.
-            foreach (var d in mainUIElements)
-            {
-                if (d is SkinnableDrawable sd && (sd.Drawable.Anchor & Anchor.y0) > 0)
-                    topRightOffset = Math.Max(sd.Drawable.ScreenSpaceDrawQuad.BottomRight.Y, topRightOffset);
-            }
-
-            topRightElements.Y = ToLocalSpace(new Vector2(0, topRightOffset)).Y;
             bottomRightElements.Y = -Progress.Height;
         }
```
