### ISSUE TITLE
Chat dropdown can extend beyond the screen

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10541]
The chat dropdown can extend beyond the screen if the conversation list is sufficiently large, cutting off the last couple of entries and making them unclickable. (the bar on the right of the context menu shows what is going on best)

video: https://www.youtube.com/watch?v=hq5q8p7tIK4
osu!lazer version: 2020.1017.0

**Comment by kyekiller** [comment]
Small workaround for you is to upper the size of the chat so you are able to press the channels that you desire. 

As shown in this small video.

https://user-images.githubusercontent.com/30637943/103818321-3323d180-5060-11eb-8f03-9d0ea711e54f.mp4

**Comment by bdach** [comment]
@kyekiller this is not an appropriate workaround for this issue. this should be fixed properly.

**Comment by kyekiller** [comment]
@bdach It's just a workaround to access the channels people can't while I'm looking for a solution to the issue or if anyone else does.
