### ISSUE TITLE
Pop-up to choose key layout for gameplay

### ISSUE THREAD

**Issue by Tudi20** [ppy/osu#10549]
Special pop-up on first load of the game, could ask for (or just do this in the background and check for current system one), which key layout would they like to apply: QWERTY, QWERTZ, AZERTY, QZERTY, Dvorak, etc.

**Comment by bdach** [comment]
This is not going to happen. The game should be respecting the system-wide keyboard layout. If it isn't, it's a bug which should be fixed without adding "special pop-ups".

**Comment by peppy** [comment]
I think the intention here is to provide better defaults for non-qwerty keyboards, which is something we may want (but wouldn't need to be a user choice/prompt).
