### ISSUE TITLE
Allow pausing music on the results screen

### ISSUE THREAD

**Issue by Firmatorenio** [ppy/osu#10546]
**Describe the bug:** The nowplaying-overlay (accessed with Ctrl+T) doesn't let you stop the music on the results screen.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=NuLAHLykN90 (end of the video)

**Comment by Lolihunter1337** [comment]
Pretty sure that is intended

**Comment by bdach** [comment]
I'm not sure why pause should be allowed on that screen, to be honest, but that's my opinion I guess.

**Comment by Firmatorenio** [comment]
Well, the music can be paused on the song select screen now, you can pause the entire game while in gameplay, but the only way to silence the game on the results screen is to turn the volume all the way down. The music just finishes playing out on the screen and nothing plays afterward anyway - but some maps (especially WIPs) have huge unmapped sections in the end.

**Comment by peppy** [comment]
What's the scenario where you want to silence the music? Are you alt-tabbing away from the game and don't want to listen to it any more? Curious because it already dims the volume in such scenarios (and you can set the dim to go to 0% if you prefer that).

**Comment by Firmatorenio** [comment]
Most of the time I don't actually want the music to stop playing when I tab out onto the other screen - unless I'm gonna watch a video someone posted on discord (in which case I'll pause the music - very thankful I can do it on the song select,) I want the music to actually keep playing.

The other primary scenario for me is playtesting/modding, where I want to analyze my play, look at the summary while focusing my thoughts into what I'm about to type about it (silence is very useful when you try to type things right in a language you're not native in - not to say I can't chat casually while music is playing, but making a semi-formal post takes some focus, and I often had to exit to main menu to pause the music there on Stable).

~~I first stumbled onto it was when I was testing something by recording a video and then immediately checking the recording without exiting the results screen, and I just happen to test things on a 5min long song that I only map first 15 seconds of~~

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/10714.
