### ISSUE TITLE
Changing controls doesn't affect welcome tips.

### ISSUE THREAD

**Issue by Ayfri** [ppy/osu#10543]
**Describe the bug:** 
When you change your controls, the welcome tips like "Press CTRL - O to access options" don't change, I put CTRL - W for settings but it shows CTRL - O in the tip (see this on the screen).

**Screenshots or videos showing the encountered issue:** 
![Welcome Screen](https://user-images.githubusercontent.com/34159136/96320429-a514ed80-1012-11eb-8271-cce444034503.png)
![Controls](https://user-images.githubusercontent.com/34159136/96320425-a2b29380-1012-11eb-9bbc-fc00cea62f8a.png)

**osu!lazer version:** 
2020.1017.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5394607/database.log)
[network.log](https://github.com/ppy/osu/files/5394608/network.log)
[performance.log](https://github.com/ppy/osu/files/5394609/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5394610/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5394611/updater.log)

**Comment by peppy** [comment]
If you changed the binding you don't need the tip. you already know the binding.
