### ISSUE TITLE
Manual lobby closing support

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu#10548]
**Describe the new feature:** The users should be able to manually close their lobbies even before the closing time.

**Proposal designs of the feature:** Maybe a button to close the lobby when the owner is currently in their lobby (and a confirm dialog).

**Comment by bdach** [comment]
Requires web-side / infrastructural changes, I'd imagine.

**Comment by smoogipoo** [comment]
Going to close this one for now as we're rethinking multiplayer.
