### ISSUE TITLE
HP bar doesn't show on some skins

### ISSUE THREAD

**Issue by HyperXinon** [ppy/osu#10551]
So i have an Problem with my Health bar where i dont see it in any Beatmaps:

BTW: I know, its in auto right now but pretend its not because it looks the same without auto too.

If anybody has an idea why this is like it is now, please tell me.

I've made a Reddit post on r/osugame too: https://www.reddit.com/r/osugame/comments/jd4qx6/my_health_bar_is_gone/
 
Its so irritating to play without a healthbar to see how much health i have left.

This is how it looks to me:
https://user-images.githubusercontent.com/62767605/96371987-f9c87d80-1164-11eb-835e-73babb348ecb.PNG

Im not sure why this is so but it is like it is.

**Comment by HyperXinon** [comment]
and yes, it is the newest Build if anyones asking:       osu!lazer 2020.1017.0 [ Development Build ]

**Comment by bdach** [comment]
Please attach your skin.

**Comment by HyperXinon** [comment]
how do i do that?

**Comment by bdach** [comment]
There's an option to export skins in the settings menu. Please export the skin you've taken the screenshot on, and attach it to this issue by dragging and dropping the `.osk` into the comment box (will require renaming/changing extension to `.zip` beforehand).

If the skin is too big then an online link to it would also suffice.

**Comment by HyperXinon** [comment]
It wont get Processed. Its says it when i ´ll try to coment

**Comment by bdach** [comment]
is there an online source the skin can be downloaded from? osu! forum link, some third party skin website, whatever?

if you can't link the skin then we can't help you. it's likely an issue specific to it.

**Comment by HyperXinon** [comment]
if i use the normal lazuer skin it will work i see

**Comment by HyperXinon** [comment]
yes, i use the nromal Whitecat CK skin. let me get the link real quick!

**Comment by HyperXinon** [comment]
https://skins.osuck.net/index.php?newsid=1107

**Comment by HyperXinon** [comment]
i just see it doesnt work on any skin other than the "default laze"r and "normal" one!
In none of my other skins it works, if i try to play them in stable they work perfectly fine!

**Comment by bdach** [comment]
Can't reproduce with the skin linked:

![osu_2020-10-18_17-31-40](https://user-images.githubusercontent.com/20418176/96372664-2af67d00-1168-11eb-9ccc-d2e255351a6a.jpg)

Does this happen on a specific beatmap? If so, please link it and try disabling beatmap skins.

**Comment by HyperXinon** [comment]
it happens on every beatmap, and on any custom skin. (other than default stable skin and default lazer skin)

**Comment by HyperXinon** [comment]
how do you even upload direct pictures in github without a link?

**Comment by HyperXinon** [comment]
because if i try, it says upload completed and gives a link?

**Comment by bdach** [comment]
Then I have no idea what the issue is, sorry. Try reimporting the skins and seeing if it helps.

**Comment by HyperXinon** [comment]
ok :(

**Comment by GamerProYT54** [comment]
maybe reinstall osu!lazer?

**Comment by smoogipoo** [comment]
Please find a way to upload the skin that was exported from lazer. We can't help you otherwise.

**Comment by bdach** [comment]
Since there's been no response one way or another I'll tentatively close this for now.

@HyperXinon Please leave a comment here if you manage to get the skin uploaded - we'll reopen if needed.

**Comment by LemonJuicer** [comment]
Reopen the issue! Using "-        # re;owoTuna v1.0 『Selyu』 #        -.osk"
Link: https://drive.google.com/drive/folders/1O9AUAf63xtXAXPmy6NGqutZa0n48rnKM

**Comment by LemonJuicer** [comment]
Still works on some other skins

**Comment by St-Elystia** [comment]
My skin has the same HP bar like this skin: http://www.mediafire.com/file/6dvu2lpvc4ao8wu/Celeste_V1.osk/file and it has the same issue. Is there any way to fix it? (All other skins are fine except my main skin) - osu!lazer 2021.502.0

**Comment by St-Elystia** [comment]
idk but somehow the scorebar of this skin https://drive.google.com/file/d/1B7aZJLBgspzKdIB5vpYghMU8kVIMXXR4/view still can animated. ``scorebar-bg@2x`` is 2732x1536

**Comment by bdach** [comment]
This will only manifest on skins that also have a `scorebar-marker` sprite, I believe.

**Comment by peppy** [comment]
This sounds like an easy fix: we should still be supporting animations in the new style fill, right?

**Comment by bdach** [comment]
Yeah, I think that would suffice. Was going to grab that as a quick one but never got round to it.
