### ISSUE TITLE
Collections getting deleted

### ISSUE THREAD

**Issue by kihure** [ppy/osu#10561]
**Describe the bug:**  I was playing and my game got laggy ( which isn't something new ) so I restarted it and error showed up, and my collections were gone. It happened yesterday and looks like logs are from today...

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/72034974/96474307-f8658680-1232-11eb-9592-a034b64f49e9.png)

**osu!lazer version:** 2020.1017.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5403055/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5403056/updater.log)
[database.log](https://github.com/ppy/osu/files/5403057/database.log)
[network.log](https://github.com/ppy/osu/files/5403058/network.log)
[performance.log](https://github.com/ppy/osu/files/5403059/performance.log)

**Comment by peppy** [comment]
Did that error appear after the restart? Your logs don't contain anything about the error, unfortunately.

**Comment by kihure** [comment]
> Did that error appear after the restart? Your logs don't contain anything about the error, unfortunately.

Yes. It also happened before as well. For some reason it didn't show my collections so i restarted the game and they were back, After the error that time restarting didn't help. And unfortunately i didn't know i had to submit the issue straightaway so logs are gone.

**Comment by bdach** [comment]
A video isn't likely to have enough information we need. We'll probably need the logs from a run on which this has happened.

**Comment by kihure** [comment]
> A video isn't likely to have enough information we need. We'll probably need the logs from a run on which this has happened.

Sorry. Next time i see any issues I'll create an issue straightaway.

**Comment by kihure** [comment]
> A video isn't likely to have enough information we need. We'll probably need the logs from a run on which this has happened.
