### ISSUE TITLE
Multi throws you out when trying to play a map on any room

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#10564]
**Describe the bug:** 

So i tried to improve one of my scores in the beatmap spotlights room, but osu! throws me an error (see images above) saying "Fail to retrieve a score submission token" and it says it only happen when you run an outdated or non-official release, but i am playing in the last official version updated directly from the game itself, i even tried dowloading the .exe again from github (lastest release) but the problem remains the same.
I thought it was my fault, maybe a computer problem, but i found a message in the chat, someone had the same problem, as you can see here: 

![chat](https://user-images.githubusercontent.com/41755816/96538091-1d2b1f80-126e-11eb-9980-15c353afe05f.jpg)

**Screenshots or videos showing encountered issue:** 

![osu_2020-10-19_17-15-55](https://user-images.githubusercontent.com/41755816/96538187-56638f80-126e-11eb-9e45-5f7cf265fe3a.jpg)

**osu!lazer version:** 

2020.1017.0

**Logs:**
[performance-input.log](https://github.com/ppy/osu/files/5406109/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/5406110/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5406111/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5406112/updater.log)
[database.log](https://github.com/ppy/osu/files/5406113/database.log)
[network.log](https://github.com/ppy/osu/files/5406114/network.log)
[performance.log](https://github.com/ppy/osu/files/5406115/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5406116/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5406117/performance-draw.log)

**Comment by peppy** [comment]
Fixed, regressed earlier today when I did some server clean-up.
