### ISSUE TITLE
Very poor editor performance on maps with large amounts of hitobjects

### ISSUE THREAD

**Issue by Fvern** [ppy/osu#10577]
I don't see an issue covering this, so I'm making one.
The editors for mania, taiko and possibly catch (can't confirm because the editor crashes for me, will make another issue in the future) are very laggy for me.

Mania (the worst, probably due to it having the most objects out of all the modes):
https://osu.ppy.sh/beatmapsets/861816#mania/1802831 
On this map, the loadtime in lazer was 18 seconds, but in stable it's basically unnoticable. 
When letting the map play in the editor, I get an unusable 8fps in both update and draw, with 40% CPU usage and 7.5% GPU usage, as opposed to stable where I get 288fps (the fps cap) with around 12% CPU and GPU usage.
Seeking (skipping forward) for the first time freezes the game for a good 5-6 seconds, and spikes my CPU usage to 95%. The timeline at the top of the screen and the gameplay doesn't load properly for quite a while longer. This is instant in stable.

Taiko:
https://osu.ppy.sh/beatmapsets/812539#taiko/1704294
Load times are higher than those loading any osu!/mania map in stable, but negligible. 
Letting the end of the map play gives me around 108fps (usable, but below my monitor's 144hz refresh rate), with similar CPU and GPU usage to mania.
Seeking works alright, unlike mania.

It's worth a mention that the osu! ruleset's editor reaches 60% CPU usage on a fast map (on my medium tier CPU, imagine this on a weaker PC) and has a non-negligible load time for longer maps, but manages to run above 144fps for me.

PC Specs: 
OS: Windows 10 
CPU: i5-8400 (6 core)
GPU: Geforce GTX1060 3GB
RAM: 2x8GB DDR4 @2400Mhz
Running osu! stable off of an HDD, and osu! lazer off of an SSD (yet the loadtimes are still worse).
Display: Viewsonic XG2401 (144hz 1080p)
 
Tests were performed at a 2x refresh rate (288fps) cap, to match stable, and the osu! lazer default skin.
osu!lazer version: 2020.1012.0

Logs for the session:
[network.log](https://github.com/ppy/osu/files/5417765/network.log)
[performance.log](https://github.com/ppy/osu/files/5417759/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5417760/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5417761/updater.log)
[database.log](https://github.com/ppy/osu/files/5417762/database.log)

**Comment by bdach** [comment]
There hasn't been much work on editor performance yet, as its structure has been largely in flux. I'm unsure whether this issue is worth keeping open for that reason. We obviously are aware of shortcomings in that area (try pressing <kbd>Ctrl</kbd>+<kbd>A</kbd>...)

**Comment by peppy** [comment]
Going to close this as it should be 99% alleviated by pooling. Do note that mania will still be subpar as we haven't completed the migration to pooling yet. You can track that at https://github.com/ppy/osu/issues/12026.
