### ISSUE TITLE
Add back the Offset Wizard

### ISSUE THREAD

**Issue by matteoturini** [ppy/osu#10572]
**Describe the new feature:** 
The offset wizard from osu!stable

**Comment by frenzibyte** [comment]
Based on what I get from this, this should be a duplicate of https://github.com/ppy/osu/issues/9866? if so, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)

**Comment by smoogipoo** [comment]
Yep. Closing as duplicate.
