### ISSUE TITLE
Shift + Tab not working as expected

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#10570]
**Describe the bug:** 

After last additions of display modes to HUD overlay, shift + tab don't work as expected, it always moves between "Never" and "Hide during gameplay", no matter the option selected.

In the video below I do the next:

-Open menu search for HUD options and select "always" (in this case it was already selected)
-Play a beatmap in auto
-Press shift + tab 2 times (it changes to "Hide during gameplay")
-Press again shift + tab (now it changes to "Never")

I do this 4 or 5 times, and always it moves between this 2 options.

In auto it does not look bad, if you press shift + tab it hides the elements, and if you press again it shows them again, but if you are in gameplay, the elements are never shown.

**Screenshots or videos showing encountered issue:** 

https://drive.google.com/file/d/1qmdmTd8ciPgKO8ELsULhfBw3dNGVN67k/view?usp=sharing

**osu!lazer version:** 

2020.1020.0

**Logs:**

I don't think logs are needed, if they are please ask for them and I will attach them quickly.

**Comment by peppy** [comment]
Ouch, that's an oversight

**Comment by bdach** [comment]
Not sure what the expected behaviour would be here - cycling across all available options, or always going [current user setting that isn't hidden] <-> hidden?

**Comment by Gonzalo-Bruna** [comment]
I think this makes more sense
> [current user setting that isn't hidden] <-> hidden?

**Comment by bdach** [comment]
So I got a branch that I thought would resolve this, but then started doubting it. The primary issue is what happens if player is exited with the overlay off.

* Should the setting be reverted to what it was at the beginning of the map?
* Should it remain off for the rest of the session, or forever?
* If it's the last one, then if you press <kbd>Shift</kbd>-<kbd>Tab</kbd> in a week from now, should it go back to the value you had before, or can it go back to "Hide during gameplay" now?

The branch I have has a "memory span" of a single beatmap, as in if you exit with it off, the old value of the setting is lost irrecoverably without manual intervention, which doesn't feel like much of a fix. As it turns out having this setting no longer binary brings much larger a headache than maybe expected...

**Comment by peppy** [comment]
I think the best way to think of the Shift-Tab disable is a per session variable. It should probably not save to config.

At which point, maybe we should remove the "never" display setting from settings completely. I doubt there are many people who want the HUD permanently disabled, maybe defaulting to "during breaks" is a good compromise, along with the above.

Interested in thoughts from players that use shift-tab regularly.

**Comment by Game4all** [comment]
I play with HUD disabled on stable, which I enable back when entering breaks (a setting already covers this in lazer) but I also sometimes shift+tab very briefly in a middle of a map to check my accuracy / combo.

What would make most sense to me is to have Shift+Tab work as a toggle forcing the HUD to show or hide depending of your current HUD visibility settings to permit still doing this in game.

**Comment by bdach** [comment]
I gave making the <kbd>Shift</kbd>-<kbd>Tab</kbd> a go as a session-wide variable, but without further conveyance it still sucks. It's incredibly unclear as to when the HUD is supposed to be showing or not, and the hidden session state is either not shown anywhere or, if I add it to settings, just screams "this is way too complicated for what it needs to be":

![2020-10-27-001934_515x192_scrot](https://user-images.githubusercontent.com/20418176/97238624-1f4f2a00-17ea-11eb-87d7-087721d653fe.png)

Like, I'm not even sure how I'm supposed to word these better. Not to mention that pressing the shortcut with i.e. "HUD only during gameplay" set sometimes seemingly does nothing and sometimes actually does what it's supposed to.

I'm half inclined to propose disabling the shortcut entirely on "only during gameplay" and "only during breaks" and toggle normally between the two remaining settings.

**Comment by peppy** [comment]
I don't think the state needs to be shown for the session state, similar to stable. In stable, it shows a notification when the HUD is hidden (just once, similar to volume muted), and will reset on game restart anyway, if a user really doesn't know how they hid it.
