### ISSUE TITLE
Display the resultant difficulty settings after speed/rate changing

### ISSUE THREAD

**Issue by vernonlim** [ppy/osu#10580]
Currently, only the star rating display is changed with DT/speed changes, with no indication that other settings like AR or OD are affected. In stable, a small arrow is put next to the difficulty setting to indicate that it is raised (or lowered with HT), and the millisecond values displayed when hovered over are changed. 

However, this isn't the terminology players use. In scoreposts and conversation, players use the AR/OD values calculated with formulas when discussing rate changed maps. An example is referring to AR9 + DT as AR10.3/AR10.33 and OD10 + DT as OD11/OD11.11 (decimals are usually omitted for convenience). It would be much less confusing for players if these values were displayed directly in the menu. 

Instead of just SR, the other difficulty settings could be made red and increased to their values with the speed change (EDIT: in this case DT).
![image](https://user-images.githubusercontent.com/25032854/96833992-d6a71200-1473-11eb-8272-ee1c9924d29f.png)

An example of this already implemented in the third party client McOsu, though without SR calculation due to it not being implemented. This implementation actually displays values rounded to 1 decimal place in the menu, and values rounded to 2 in the mod menu (in lazer, this should probably be all made 2 to be consistent with SR)
![image](https://user-images.githubusercontent.com/25032854/96834255-474e2e80-1474-11eb-93bf-b65e38778fcb.png)
![image](https://user-images.githubusercontent.com/25032854/96834371-7b295400-1474-11eb-8369-d1a1a631c771.png)

For ease of gameplay customization, this should somehow be applied to the 'Difficulty Adjust' mod as well (like it is in McOsu).
![image](https://user-images.githubusercontent.com/25032854/96834850-479af980-1475-11eb-9b87-1ba9e1191cb4.png)

First, the values could be displayed permanently somewhere. Having to hover over a slider in order to see what value it is at is very inconvenient. (Could be another issue, but is required for this)

Then values after speed changing could be displayed next to the original values when DT/HT is selected. This way, players can see what the original value they are setting is, and what value they are going to get when playing with the selected speed. 

The display of both original and after-speed-changing values is important since otherwise it would get confusing when working with complicated combinations of difficulty settings and speed changes (this is a flaw with McOsu's implementation from my own experience).

**Comment by GameBoyYeet** [comment]
> First, the values could be displayed permanently somewhere. Having to hover over a slider in order to see what value it is at is very inconvenient. (Could be another issue, but is required for this)

This is especially true for mobile.

**Comment by bdach** [comment]
@GameBoyYeet [we know already](https://github.com/ppy/osu/issues/8377)

**Comment by Fvern** [comment]
I forgot one of the most important things in the original post — BPM.
Currently, resultant BPM with DT/speed increase isn't displayed anywhere in the UI (unlike stable where it actually is in song select), so without a calculator/good mental math, players have no idea what speed the map is going to be.
It should be displayed clearly in both the song select menu and the mod customization menu.

**Comment by smoogipoo** [comment]
I’m gonna milestone this since I agree it’s important. At the very least BPM has to happen, the rest are QOL improvements that stable doesn’t have.

**Comment by bdach** [comment]
@Game4all I don't know anything about a design, but if you're planning to give this a shot, make sure you're handling `ModTimeRamp` correctly in the adjusted BPM calculations.

**Comment by Game4all** [comment]
Yeah, so far what I got locally seems to work fine but doesn't handle the non trivial case of wind up / down mods.

**Comment by bdach** [comment]
I believe accurately computing BPM bounds, given a linearly-changing BPM like in the case of `ModTimeRamp`, requires enumerating over all timing control points, and calculating minimum/maximum BPM within each section delineated by them.

**Comment by mk56-spn** [comment]
going to  give fixing the length not adjusting with DT / HT a shot, unless someone is already on that

**Comment by bdach** [comment]
AR/OD now updates after https://github.com/ppy/osu/pull/24642, but beatmap length is still not correct.

**Comment by Joehuu** [comment]
Beatmap length has since been updated in https://github.com/ppy/osu/pull/26060. Closing as completed
