### ISSUE TITLE
Default text box value should disappear when text box becomes active

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#10589]
**Describe the bug:** 
In the editor setup menu, clicking on artist or title text boxes does not remove the default text inside them

**Screenshots or videos showing encountered issue:** 
![textbox](https://user-images.githubusercontent.com/11320483/97092970-e92a7280-1650-11eb-9459-9a57689c0aef.gif)

**osu!lazer version:** 
2020.1020.0

**Comment by bdach** [comment]
Those are default values, not placeholders.

https://github.com/ppy/osu/blob/89797d7a57e6c86bb9c15c03fd67e4b60cedbfaa/osu.Game/Beatmaps/BeatmapManager.cs#L104-L126

I imagine eventually they'll go away but validation needs to be implemented to avoid letting users save with empty metadata.
