### ISSUE TITLE
Touch input not working as expected

### ISSUE THREAD

**Issue by Awesome-Aasim** [ppy/osu#10581]
**Describe the bug:** 
On osu!lazer on desktop, when I try to use touch, it does not recognize my touch until I either drag my finger or let go of the screen.  This lack of touch optimization results in me missing notes left and right.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2020.1020.0
**Logs:**

**Comment by frenzibyte** [comment]
Tracked in https://github.com/ppy/osu-framework/issues/1514, this can be closed as a duplicate of it.
