### ISSUE TITLE
Osu Android Build Crash

### ISSUE THREAD

**Issue by lilRufi** [ppy/osu#10583]
**Describe the crash:** 
Downloaded Xamarin and tried to run:

dotnet build osu.Android

**Screenshots or videos showing encountered issue:** 
<img width="1276" alt="C516161apture" src="https://user-images.githubusercontent.com/33981808/96909475-c2303d00-14a6-11eb-92b2-790766cd1f1d.PNG">

**osu!lazer version:** 
lts

**Comment by bdach** [comment]
Please read and follow the error message.

**Comment by lilRufi** [comment]
Did everything on error message.

**Comment by bdach** [comment]
I don't know what to tell you except for "it works here, so it must be something with your xamarin installation".

**Comment by lilRufi** [comment]
I Installed VS Professional 2019 with Xamarin.

**Comment by bdach** [comment]
Drip feeding bits of information one comment at a time is not helpful.

[Possibly relevant thread.](https://developercommunity.visualstudio.com/content/problem/1107111/the-reference-assemblies-for-monoandroidversionv10.html) If not, you're going to have to look at msbuild logs and figure it out yourself.

**Comment by smoogipoo** [comment]
You cannot use dotnet to build Xamarin projects. Open osu.Android.slnf in VS.

**Comment by smoogipoo** [comment]
This is actually documented in the README. Please make sure to read it thoroughly.
