### ISSUE TITLE
Taskbar icon not working

### ISSUE THREAD

**Issue by Cyliann** [ppy/osu#10588]
**Describe the bug:** 
When osu!lazer is on pinned on windows taskbar and running, the actual program icon is next to it, and it doesn't show the icon.

**Screenshots or videos showing encountered issue:** 
![icon](https://user-images.githubusercontent.com/33868960/97080415-53b0c380-15fb-11eb-94ae-d8674da40ff0.png)

**osu!lazer version:** 
2020.1020.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/5432785/database.log)
[network.log](https://github.com/ppy/osu/files/5432786/network.log)
[performance.log](https://github.com/ppy/osu/files/5432787/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5432788/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5432789/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5432790/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5432791/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5432792/updater.log)

**Comment by bdach** [comment]
Has been reported before (#5917)

**Comment by peppy** [comment]
is this fixed if you run with `--sdl` (add to your shortcut)?

**Comment by bdach** [comment]
This might be due to our distribution method (i.e. the pinned executable is the `%localappdata%/osulazer/osu!.exe`, while the launched one is `%localappdata%/osulazer/[version]/osu!.exe` - similarly to #10550.

**Comment by peppy** [comment]
it's an unfortunate side effect of the way squirrel operates. need to check on other apps that also use squirrel (visual studio code?) to see if they are doing anything special.

or just replace squirrel.

**Comment by caesay** [comment]
This should probably get re-labelled to area:installer (so I can track it easier) and it will be closed when 3.0.0 of Squirrel drops.
