### ISSUE TITLE
Search bar from the song selection bug with "<" and ">" on AZERTY keyboard.

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#10587]
I use a AZERTY frenck keyboard. In the search bar, when I want to put the caracters "<" or ">" (for exemple to write "hp<5"), when I type "<" or ">", the search bar seems isn't updated (the caracter isn't displayed). But when I type a other caracter, the search bar is updated, and display all of the text.

Example:
The state of the search bar after the action I describe before -> `[ ]`
- I press the H button. `[h]`
- I press the P button. `[hp]`
- I press the < button. `[hp]`
- I press the = button. `[hp<=]`
- I press the num5 button. `[hp<=5]`

![osu_2020-10-23_19-36-56](https://user-images.githubusercontent.com/57914482/97036131-a771cd00-1567-11eb-8108-8b92bf571099.jpg)
![osu_2020-10-23_19-37-11](https://user-images.githubusercontent.com/57914482/97036144-aa6cbd80-1567-11eb-9ab9-52428be9bcef.jpg)

**osu!lazer version:** 2020.1020.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5430974/database.log)
[network.log](https://github.com/ppy/osu/files/5430975/network.log)
[performance.log](https://github.com/ppy/osu/files/5430976/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5430977/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5430978/updater.log)

**Comment by jorolf** [comment]
Very likely related to https://github.com/ppy/osuTK/pull/67#issuecomment-709641664

**Comment by bdach** [comment]
Should be fixed in SDL after https://github.com/ppy/osu-framework/pull/3950.

**Comment by bdach** [comment]
Closing for now as resolved on the current primary windowing backend (SDL).
