### ISSUE TITLE
Scrolling while selecting within the timeline causes unexpected behavior 

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#10594]
Title

https://puu.sh/GGDv1/5de23802dd.mp4

**osu!lazer version:** 2020.1020.0

**Comment by FamousPig** [comment]
I tried tackling this I issue and [this is what I've got so far.](https://github.com/ppy/osu/compare/master...FamousPig:fix-timeline-drag-select-weirdness)(code is not cleaned up yet). The selection box no longer expands out into infinity but it is still wiggling during the zoom transition. I'm mainly commenting so people know this exists. Additionally if this is obviously the wrong way I would love to know.

![drag-select](https://user-images.githubusercontent.com/22643729/97212048-295c3300-17c0-11eb-8b82-ec2661a8b124.gif)

**Comment by bdach** [comment]
* I haven't checked but you probably want to apply the correction to `selection2` to fix the wiggle.
* Have you looked at using `ToSpaceOfOtherDrawable` or similar helper functions provided in the framework? Ideally `lastZoom` should not be a thing.
