### ISSUE TITLE
Raw Input Greyed Out

### ISSUE THREAD

**Issue by darkralts** [ppy/osu#10592]
![image](https://user-images.githubusercontent.com/16366107/97095692-bec8bd00-1630-11eb-94a3-6aaa3a3a375e.png)
![image](https://user-images.githubusercontent.com/16366107/97095699-c8522500-1630-11eb-9871-30cc789fb471.png)

**Comment by darkralts** [comment]
OS: Void Linux 64x
Using AppImage

**Comment by swoolcock** [comment]
Raw input is not currently supported on macOS or Linux.

**Comment by darkralts** [comment]
oooOO
