### ISSUE TITLE
Committing to editing a timing point should not move the timeline

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#10590]
**Describe the bug:** 
Often when timing a song you would move around the entire timeline and do changes to BMP or offset. It's annoying to have to move back to where you were in the timeline any time you change the timing point

**Screenshots or videos showing encountered issue:** 
![timeline](https://user-images.githubusercontent.com/11320483/97093197-a8335d80-1652-11eb-9d64-8ee2eefbb338.gif)

**osu!lazer version:** 
2020.1020.0

**Comment by bdach** [comment]
I don't know that this should be this big of a deal. In what sort of scenario you would be making changes so drastic such that you would be getting rewound back to the start from the middle of a song? Not a mapper so genuinely don't know.

**Comment by LittleEndu** [comment]
> Not a mapper

I'm not really either, but you would check if you got the right BPM by going to the end of the song and seeing if the beats still line up. Labeling this as proposal sounds fair

**Comment by bdach** [comment]
Ah, ok, so on the gif a point far back in the past is being moved, therefore scrolling back to the very start. Makes sense, maybe there should be a cutoff for the scrolling behaviour...?
