### ISSUE TITLE
master won't build for iOS

### ISSUE THREAD

**Issue by Naville** [ppy/osu#10604]
**Describe the bug:** 
 Build failed. See attached screenshot
**Screenshots or videos showing encountered issue:** 
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/5205699/97271868-1606a180-186c-11eb-8bfc-c0ebd9254b3d.png">

**osu!lazer version:** 
19e58dc4fc244bbadb992942f07a35dbed00142d
**Logs:**
N/A

I personally see no reason to not release IPAs since your TestFlight limit clearly isn't near enough for us supporters. But you just be you I guess since I've already cancelled my sub

**Comment by peppy** [comment]
Please follow the instruction in the `README`, or wait for the next reset of testflight.

We have already confirmed on multiple occasions that it builds out-of-the-box.
