### ISSUE TITLE
Long notes disappear when moving back in the bottom timeline in editor screen (osu!mania)

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#10600]
**Describe the bug:** 

I realized while i was moving in the editor,  that when you move back in time in the bottom timeline, long notes just disappear out of the stage (but they stay in the top timeline) and they never appear again.
This only happen with long notes, and only with the bottom timeline.

**Screenshots or videos showing encountered issue:** 

I hope this video clarify things
https://drive.google.com/file/d/1Um09ikmcBqtJ0jTwwFV3O-Nqj_KXcS22/view?usp=sharing

**osu!lazer version:** 

2020.1020.0

**Logs:**

[performance-draw.log](https://github.com/ppy/osu/files/5442893/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/5442894/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/5442895/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5442896/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5442897/updater.log)
[database.log](https://github.com/ppy/osu/files/5442898/database.log)
[network.log](https://github.com/ppy/osu/files/5442899/network.log)
[performance.log](https://github.com/ppy/osu/files/5442900/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5442901/performance-audio.log)

**Comment by bdach** [comment]
This is caused by the hit objects' state not reverting from `Hit`/`Miss` to `Idle`. What causes that I'm not yet sure. It may be that the instantaneous seek confuses things and the hit objects don't get the chance to run `Update()` to revert.

**Comment by Gonzalo-Bruna** [comment]
after a long time, I tried to reproduce this bug again and I wasn't able to, so this was solved somehow? I'll close this issue for now, please re-open if this bug persist for anyone else

**Comment by frenzibyte** [comment]
Regardless, I think https://github.com/ppy/osu/issues/10455 should cover this one.

**Comment by H1N1-dev** [comment]
I still have this bug.
