### ISSUE TITLE
embeds for osu screenshot links

### ISSUE THREAD

**Issue by darkralts** [ppy/osu#10617]
**Describe the new feature:** 
when you send an osu screenshot (eg https://osu.ppy.sh/ss/6000000) to a friend or maybe even in a chat, have an option for embedding it 
**Proposal designs of the feature:**

**Comment by LittleEndu** [comment]
Disagree with embedding it, that just isn't what the chat is for. If anything it could load a preview when hovering over the link.

**Comment by enoslayd** [comment]
What if when screen shot link was clicked there will be an inclient viewer?

**Comment by darkralts** [comment]
ah that would be cool too

**Comment by Game4all** [comment]
I think that before worrying about how screenshots links should be rendered in the client, we should probably assessing first whether we want to  port to lazer the ability to upload screenshots present on stable.

**Comment by enoslayd** [comment]
Thats given
