### ISSUE TITLE
Crash on entering a beatmap

### ISSUE THREAD

**Issue by GopoBoi** [ppy/osu#10610]
**Describe the crash:** 
Whenever I open any beatmap the game outright crashes

**osu!lazer version:** 
Current Master build
**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5450511/runtime.log)

**Computer Specifications:** 
Windows 10 1903
CPU: AMD Athlon X4 880K
GPU: Nvidia GTX 1050

**Comment by bdach** [comment]
It seems that your configuration file might have got into a bad state - there is a mismatch in one config setting's type (float vs double). Are you able to debug which setting it might be?

**Comment by GopoBoi** [comment]
okay, it was my fault, forgot to rollback a class that I played with, sorry for wasting your time.
