### ISSUE TITLE
darken long notes when they aren't being held properly

### ISSUE THREAD

**Issue by igontusuwu** [ppy/osu#10612]
darkening long notes when not being held gives feedback to the player that they are not holding the long note properly 
currently, long notes don't darken in any case

**Comment by enoslayd** [comment]
#8594

**Comment by smoogipoo** [comment]
Closing as duplicate of https://github.com/ppy/osu/issues/8594

**Comment by igontusuwu** [comment]
yea, i think
i'll add suggestions to the other post
