### ISSUE TITLE
Raw input causes the mouse (and background in menu) to move incorrectly, out of screen.

### ISSUE THREAD

**Issue by maramowicz** [ppy/osu#10616]
**Describe the bug:** 

I am sorry, my Englishis bad. 
Bug as in the title and I sending a video showing this bug.

**Screenshots or videos showing encountered issue:** 

https://drive.google.com/file/d/1Kcy9Z9vJOhY7ucVmPbTFpjD6bi5C-ZuN/view?usp=sharing

**osu!lazer version:** 

2020.1020.0
Windows 10 Home (If useful: Insider Preview/Build 20236.rs_prerelease.201009-1631)

**Comment by bdach** [comment]
#10465
