### ISSUE TITLE
Hitsounds out of sync with music

### ISSUE THREAD

**Issue by memesnightmares** [ppy/osu#10624]
**Describe the bug:**

I have to play with hitsounds off because they are not in sync with the music. They lag behind consistently by what feels like ~50ms?

**Screenshots or videos showing encountered issue:**

https://gofile.io/d/Xpu7o7

**osu!lazer version:** 2020.1020.0

**Comment by OniCado** [comment]
I have the same issue as it seems form the video, the beatmap pauses/lags/freezes for a short time on the first hitobject, presumably causing offset the from the music and depending on the suverity making the first note unreadable.
I am also using Audio Compatability Mode on Stable to not have random offsets on maps, not sure if that is in any way connected to this issue.

Windows 10 Pro N 2004
Build 19041.572
Realtek HD Audio Driver 6.0.1.8210
nvidia Driver 456.71 but has happened on older drivers as well
using 2GPUs in system attatched to different displays

A video of the issue behaviour can also be uploaded, but it seems to be exaclty the same as the video provided by memesnightmares.
If i can provide any more details to help, please let me know

**Comment by memesnightmares** [comment]
@OniCado I could be wrong, but what you're talking about seems to be more like #6242, a different issue that I have.

**Comment by memesnightmares** [comment]
@bdach I see that you've tagged my report as missing-details, if there's anything I've neglected to provide please do let me know so that I can clarify!

**Comment by bdach** [comment]
To be frank at this point it's hard to say conclusively what info might be necessary. Without at least some entry-level investigation/debugging on your side it's going to be difficult to bring this to a conclusion as there are too many possibilities regarding what might be going wrong, and playing guessing games isn't really all this productive.

**Comment by memesnightmares** [comment]
Could you give me some pointers on what I should be trying to debug? I'd be happy to do a bit of digging, I'm just not sure where to start / what could be at fault.

**Comment by memesnightmares** [comment]
Nevermind, for some reason I'd mentally ruled out pulseaudio as being the culprit since it showed osu as one unified device, however turns out that https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Laggy_sound solved my issue (setting the following settings in `/etc/pulse/daemon.conf`)

```
default-fragments = 5
default-fragment-size-msec = 2
```
