### ISSUE TITLE
osu overwrites auto records when auto is enabled

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [ppy/osu#10633]
**Describe the bug:** 
osu overwrites auto records when auto is enabled

**Screenshots or videos showing encountered issue:** 
[Record. Play on osu!stable and osu!lazer](https://github.com/ppy/osu/files/5468974/Auto%2B.-.TheFatRat.-.Mayday.feat.Laura.Brehm.2B.Calling.Out.Mayday.2020-02-23.Osu-1.zip)

**osu!lazer version:** 
2020.1031.0

**Logs:**
There is no tree logs here.

**Comment by bdach** [comment]
would you mind explaining in more detail? i have no idea what this report is trying to say.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
> would you mind explaining in more detail? i have no idea what this report is trying to say.

[Record. Play on osu!stable and osu!lazer](https://github.com/ppy/osu/files/5468974/Auto%2B.-.TheFatRat.-.Mayday.feat.Laura.Brehm.2B.Calling.Out.Mayday.2020-02-23.Osu-1.zip)

**Comment by bdach** [comment]
still don't understand, sorry. i can see you've linked some sort of replay in a zip. i don't know what the replay is or how it came to be.

are you saying that lazer and stable auto end up with different scores at the end of the map?

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
yes, and they plays differently

**Comment by bdach** [comment]
this is intended. neither the scoring algorithm, nor the auto replay generation algorithm, are 100% accurate with stable.
