### ISSUE TITLE
The cursor can go out of the screen.

### ISSUE THREAD

**Issue by AngelCMHxD** [ppy/osu#10635]
**Describe the bug:** I can move the cursor out of the screen in the lobby and song select menu. You can put it again in the screen using Alt + Tab and resume osu!lazer. (Sorry, I didn't speak English very well...)

**Screenshots or videos showing encountered issue:** I can't record the screen, the screen recorder crash when the cursor go out of the screen. But here is a picture of the background moving out the screen because it's follow the cursor: https://i.imgur.com/wmBnLFe.png

**osu!lazer version:** 2020.1031.0

**Logs:** There isn't any Logs of osu!lazer, there is a log of osu! stable.

**Comment by bdach** [comment]
#10465
