### ISSUE TITLE
Osu!Lazer wont open. When I install it and try to open it no window pops up, but it shows it in task manager.

### ISSUE THREAD

**Issue by OsuTheBest** [ppy/osu#10638]
**Describe the bug:** 
osu!lazer won't open when installed
**Screenshots or videos showing encountered issue:** 
N/A
**osu!lazer version:** 

**Logs:**
<!--
*please attach logs here, which are located at:*
%AppData%/osu/logs

**Comment by bdach** [comment]
Please fill the issue template. Closing until that is done properly.
