### ISSUE TITLE
ConfirmExitDialog interferes with auto exit when installing an update

### ISSUE THREAD

**Issue by hbnrmx** [ppy/osu#10630]
**Describe the bug:** 
On Windows, after downloading a new release, clicking the `UpdateCompleteNotification` 
("Update ready to install. Click to restart!") will start a 2 second exit timer,
but it also triggers a `ConfirmExitDialog`.

This creates a weird UX issue where the user can either
* click "Goodbye" -> exit right away
* click "Just a little more" -> asks again 2 seconds later
* take more than 2 seconds to act -> exits automatically

I don't see the point in showing a dialog if the user cannot abort either way,
although the method doc seems to suggest this is somewhat intended... (?)
https://github.com/ppy/osu/blob/ea007af57260f0a0121c57c2d2d4aaad7bb46730/osu.Game/OsuGame.cs#L925-L929

**osu!lazer version:** 
2020.1031.0 (Windows)

**Comment by bdach** [comment]
sounds like this does need to be fixed. can't imagine it was intended.

**Comment by Gabixel** [comment]
Looks similar to #6265 (I guess it no longer needs the _proposal_ label if that's the correct solution for this)

**Comment by bdach** [comment]
That would be *a* solution for this, sure, but I'm not necessarily sure it's *the* solution. I think the user should still have a chance to delay the restart (i.e. if they clicked the notification by accident).

**Comment by peppy** [comment]
Right now, the second call seems to quit the game, where it probably shouldn't (should remain at the blocking screen until the user acts on dismissing it).
