### ISSUE TITLE
Add better support for custom tablet area specification

### ISSUE THREAD

**Issue by MissingSemi-Colon** [ppy/osu#10645]
Hi everyone,

I found this issue with letterboxing in lazer. 

When you scale to different sizes, the area which the tablet inputs are mapped to remains the fullscreen area, instead of the new scaled osu window. This makes it basically unplayable for anyone using screen scaling, unless we go to the tablet drivers and manually limit the screen area to the new scaled window size, which is kind of a bad solution.

Not sure if I made myself clear. In normal osu! when we use letterboxing and and have this option activated the mapping area changes to the new resolution size and in Lazer it remains fullscreen. 

Is it possible to make a quick change and to map the absolute input to the scaled window?

Best regards!

**Comment by peppy** [comment]
We will not be adding this option in lazer, but we *will* be providing better control over tablet area specification (so using drivers to make changes will not be required).

**Comment by LittleEndu** [comment]
Can we open an issue per missing feature or should all missing features be listed under this issue?

**Comment by bdach** [comment]
Separate would be best I think. This issue is vague enough already that I don't know whether it can be closed or not after adding custom tablet area controls in the last release.

**Comment by bdach** [comment]
Going to close this in favour of #12098, since the two seem to be talking about the exact same issue but that one is less vague than simply
 "better support".
