### ISSUE TITLE
Erase music from your phone

### ISSUE THREAD

**Issue by ZKanerZ** [ppy/osu#10643]
I downloaded a song and then I couldn't delete it because I didn't have the option, please create it!

**Comment by Joehuu** [comment]
Press `options`, then `Delete all difficulties`.

![osu!_7oaYs9hYuF](https://user-images.githubusercontent.com/35318437/97794742-031d0580-1bbb-11eb-95a5-9dd20a38d792.png)

**Comment by ZKanerZ** [comment]
thanks man! I was trying to delete a song for a long time.

Em dom, 1 de nov de 2020 00:53, Joseph Madamba <notifications@github.com>
escreveu:
