### ISSUE TITLE
Add commonly used editor shortcuts

### ISSUE THREAD

**Issue by UberFazz** [ppy/osu#10668]
Flip shortcuts (ctrl+g, h, j) and hitsound shortcuts for samples/additions (ctrl/shift+q, w, e, r) aren't present.

**Comment by camellirite** [comment]
j and k to shift objects by a tick too

**Comment by UberFazz** [comment]
forgot to mention ctrl+left click on a white anchor to make it red as well

**Comment by Joehuu** [comment]
If they are in the [Shortcut key reference wiki page](https://osu.ppy.sh/help/wiki/Shortcut_key_reference#beatmap-editor), they will probably be all implemented.

Stable shortcuts should be all documented in wiki anyway.
