### ISSUE TITLE
Editor shortcuts

### ISSUE THREAD

**Issue by camellirite** [ppy/osu#10669]
**Describe the new feature:** Shortcuts in the editor! 

**Proposal designs of the feature:** Shortcut to: create a control point, create a timing point, reverse selection, flip horizontaly/vertically, rotate selected objects, scale selected objects, create polygon circles, and convert slider to stream are all very useful ones, I don't think many people will notice other shortcuts missing :p

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/10668
