### ISSUE TITLE
Wrong starrate and freeze on the map

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#10683]
**Describe the bug:** 
https://osu.ppy.sh/beatmapsets/885178#osu/1850114
Freeze - 0:58-1:00 (big slider)
Starrate 17.88* instead 7.02*
This is not a big problem. Just to note that the lazer is hard to work with this map.
**osu!lazer version:** 
2020.1031.0

**Comment by peppy** [comment]
Please report in https://github.com/ppy/osu/issues/10683
