### ISSUE TITLE
Osu goes blackscreen when online

### ISSUE THREAD

**Issue by Lorgborg** [ppy/osu#10688]
**Describe the crash:** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:**

**Computer Specifications:**

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

**Comment by Lorgborg** [comment]
> We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

Sorry, but it seems I miss-clicked enter and accidentally sent the issue before further describing the details.

**Comment by imTCA** [comment]
> > We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.
> 
> Sorry, but it seems I miss-clicked enter and accidentally sent the issue before further describing the details.
Understandable. Happens sometimes.

**Comment by peppy** [comment]
Your report looks like it's related to stable, not lazer.

Also I can tell you ahead of time that the information you've appended doesn't help at all. If it's only when you have internet, check other applications on your PC that may be running when you have internet.

You can contact osu@ppy.sh for further help.
