### ISSUE TITLE
virustotal detected a virus in osu! lazer

### ISSUE THREAD

**Issue by sphixy** [ppy/osu#10687]
**Describe the bug:** 
virustotal detected a virus in osu! lazer
I don't know if it is a virus so I put it here

**Screenshots or videos showing encountered issue:** 
![Capture d’écran 2020-11-04 144448](https://user-images.githubusercontent.com/62815044/98119370-d0218d00-1eac-11eb-9790-c0c505b12af0.png)

**Comment by bdach** [comment]
The hash is legitimate and matches the 2020.1031.0 EXE binary from github:

```
dachb@dachb-7559 $ sha256sum install.exe 
9a22e3e0e96a60cb10b20bb69c6fff89dffcfd7a1b47886d9c14f1f07d0ebe66  install.exe
```

Please report as a false positive. It's likely that the detection was triggered by some invalid heuristic.
