### ISSUE TITLE
Full health mod

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#10686]
**Describe the new feature:** can compliment #9584. a mod for taiko (or other rulesets if applicable) that requires players to fully fill the healthbar before the beatmap ends. if the health is not fully filled, the play will fail even if the health is already in the passing mark.

**Comment by cainy-a** [comment]
I'm interested in giving this a try actually. Might have a look this evening.

**Comment by peppy** [comment]
Did you mean to say "before the end" rather than "until the end"?

**Comment by enoslayd** [comment]
Before sorry
