### ISSUE TITLE
Edits to existing map are not saved until re-entering the editor

### ISSUE THREAD

**Issue by Muffyn** [ppy/osu#10709]
**Describe the bug:** 
I wanted to make a practice difficulty, so I tried to delete the start of the map and save. When I tried to play the map, it gave me the original map. When I entered the editor again, the edits I made were still there. After exiting (with or without saving) the map updated properly.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/o3t0p2

**osu!lazer version:** 
2020.1031.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5498031/database.log)
[network.log](https://github.com/ppy/osu/files/5498032/network.log)
[performance.log](https://github.com/ppy/osu/files/5498033/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5498034/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5498035/updater.log)

**Comment by peppy** [comment]
I think we've since resolved this via working beatmap cache changes. I can't repro.
