### ISSUE TITLE
Stats not showing on the osu!lazer (macOS)

### ISSUE THREAD

**Issue by 1tsJustR0n** [ppy/osu#10704]
I can play each beatmap and the program runs smoothly, although I don't see any of my stats, its as if i've never played before. Does anyone have a fix for this? 
![Screen Shot 2020-11-05 at 9 27 49 AM](https://user-images.githubusercontent.com/60608663/98257454-b2f0cb00-1f4d-11eb-9413-9a21450ca1ee.png)

**Comment by bdach** [comment]
lazer does not record gameplay statistics yet. This will happen at a later date.

**Comment by 1tsJustR0n** [comment]
> lazer does not record gameplay statistics yet. This will happen at a later date.

Do we have any idea on when this will happen?

**Comment by peppy** [comment]
No. Stay tuned.
