### ISSUE TITLE
Enable music pausing in multiplayer rooms

### ISSUE THREAD

**Issue by Muffyn** [ppy/osu#10708]
**Describe the new feature:** 
The pause button should work while in a multiplayer room, to match how it works in stable. 

Players may wish to pause the music after they finish a map so they can type in the chat in peace.

Image shows the button disabled.

![osu_2020-11-04_16-56-36](https://user-images.githubusercontent.com/33764011/98297702-d2561b00-1f82-11eb-86ad-ce5461ad89ff.jpg)

**Comment by peppy** [comment]
Probably worth figuring out the flow for this (maybe splitting up the leased screen control into an enum or two bools).
