### ISSUE TITLE
osu!direct textbox works incorrectly when it's off-screen

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10703]
**Describe the bug:** Basically, if you try to input something when the osu!direct textbox is off-screen, all pressed characters will appear at the same time when the textbox is visible again. This also seems to cause the caret to act strangely, as you can see by its position at the end of the example below.

**Screenshots or videos showing encountered issue:**
- [Video](https://drive.google.com/file/d/11F9iZ_uFxesH7IxgIU5bFU5E_cAZ7bni/view?usp=sharing) (the video was recorded in version 2020.712.0, and I forgot to post it 😅, but you can still reproduce this)

- I guess this can be fixed by making it always visible when you scroll down, like how the website does: it sticks the textbox to the top of the page with a smaller version:
![website listing](https://user-images.githubusercontent.com/43073074/98252733-8dc68180-1f7a-11eb-9bc3-37e6862ec6cd.png)

**osu!lazer version:** 2020.1031.0

**Comment by Joehuu** [comment]
It will also block `esc` if it's off-screen with characters typed before.
