### ISSUE TITLE
Spinner does not display spins per minute counter until a key is pressed, even if the key press is not for the spinner 

### ISSUE THREAD

**Issue by muffyn** [ppy/osu#10706]
**Describe the bug:** 
The video describes it the best. The counter does not display when the user would expect. This is especially jarring when there is a spinner right at the start of the map or after a break, as the user might not realize that a spinner exists. This would probably not be as much of an issue for users using skins that have spinners that are implemented correctly.

I would suggest having the spins per minute counter always appear when a spinner is on screen.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/py5o3d

First, I show no spinner skin and no key presses. The counter does not appear until a key is pressed. 
Then I show playing a map as normal, but not spinning the spinner at all. My key presses were all for the hit objects before, but the spin counter still showed up with 0 spin.
I then repeated the same process with the default skin, which has a visible spinner.

**osu!lazer version:** 
2020.1031.0

Also related to https://github.com/ppy/osu/issues/7023

**Comment by bdach** [comment]
This is indeed how it is implemented currently. See:

https://github.com/ppy/osu/blob/3e652fdf9c5a52e326cced6fb705d6d83f9be10e/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs#L238-L239

and

https://github.com/ppy/osu/blob/3e652fdf9c5a52e326cced6fb705d6d83f9be10e/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs#L227-L228

A "no spinner skin" sounds broken to all hell and I'm not sure why anyone would want this, but I suppose there will be complaints it won't work as it does in stable. Maybe this behaviour should be a part of the legacy SPM counter implementation whenever that lands.

**Comment by frenzibyte** [comment]
This has since been changed to match title for legacy skins only (upon testing), which should be enough to close this thread as default skin is intended to display only on key press I believe.
