### ISSUE TITLE
Split sensitivity for gameplay and menus

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu#10705]
I use 4.25x sensitivity with my tablet and I'd prefer using my mouse for menus. However my mouse-cursor is too sensitive now so I'm forced to use the tablet. It could be nice to have a different sensitivity while in menus.

**Comment by bdach** [comment]
I find that the menus are pretty stylus-usable as they are, but that's just my opinion.

**Comment by peppy** [comment]
Sensitivity should really be per input device.
