### ISSUE TITLE
Add free mod to playlists

### ISSUE THREAD

**Issue by Muffyn** [ppy/osu#10707]
**Describe the new feature:** 
There should be a way to allow players to choose which mods they want to play each map with, like how stable's concurrent multiplayer lets you. 

**Proposal designs of the feature:** 
Speed modifications could also be allowed, as players do not need to run the map concurrently like in the old multiplayer style. 
Potentially add a separate check box for each type of mod (difficulty, speed, visibility, fun mods) to say that they are allowed or disallowed.
Could also force certain mods (1.1x speed, perhaps) but allow players to add difficulty or visibility mods if they wish.

**Comment by bdach** [comment]
Currently timeshift playlist item mods seem to be coming in via the `required_mods` property from API, so this might have been intended. Marking as proposal as such.

**Comment by peppy** [comment]
This has been added. Tracking a bug where the mods are not yet selectable (see #11737).
