### ISSUE TITLE
Rendering quality where resolution changes are not possible

### ISSUE THREAD

**Issue by Wilker-a** [ppy/osu#10716]
this idea would be about making a workaround on easing the processing weight on drawing the screen and screen effects, by allowing for the user to make the game draw less pixels on the screen where more restricted or limited operating systems won't allow for changing the screen resolution.

![A screenshot of the application GLSL Shader Editor in F-Droid. in yellow, a list box is highlighted showing various divisions by multiples of 2 as options.](https://user-images.githubusercontent.com/10854855/98380323-2d414e00-2027-11eb-83b6-1f0fb8168adc.png)
###### a screenshot of GLSL Shader Editor (MIT License) for Android, with the relevant setting being highlighted in yellow.

the intention is that it would be as simple as dividing the required drawn pixels by multiples of 2, with optional settings to divide the storyboards and video renders, GUIs and gameplay elements separately, as well as choosing from different filters to be applied to keep readability (e.g Nearest Neighbor, Bilinear, etc.)

because this setting can make texts and other elements unreadable, either a limit should be set considering the current screen resolution, or, simply a failsafe to change it back like it is done in most OSes and desktop environments, and/or, some changes to the UI to ensure readability. in the former, i'd suggest that a limit to the screen for a 360 pixels (upper) minimum in both dimentions would be readable (so for a screen with its smaller dimension being 1080px, the furthest would be 1/2 to reach 540px), but non-important elements such as the storyboard and background images would have a more flexible limit to divide even further (for extra smooth shiny squares yay)

what do you think? :3

**Comment by jai-x** [comment]
I believe the common term for this is render scaling.

Also, I don't think adding a render scaling option will be considered until after osu!lazer has had several passes to optimise performance as it seems like last ditch attempt.

**Comment by bdach** [comment]
Performance improvements are constantly being worked on. Possible optimisations should and will be considered before kneecapping graphics quality in this way.

**Comment by peppy** [comment]
Also please refrain from reporting potential optimisations without first asserting that it would help at all.

**Comment by Wilker-a** [comment]
understandable. sorry for that.
