### ISSUE TITLE
Hit circles and sliders are dimmer at start time with Hidden mod

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#10719]
**Describe the bug:** Regressed in https://github.com/ppy/osu/pull/10696. When playing any higher diff maps (tested on https://osu.ppy.sh/beatmapsets/1079554#osu/2267030), circles and sliders appear dimmer. When rewinding in replay, it fixes itself in already played sections. Also fixes itself when changing skins.

**Screenshots or videos showing encountered issue:** 
![INQQ0L1IzX](https://user-images.githubusercontent.com/35318437/98421268-d004c700-203d-11eb-8593-85308b7ddb6d.gif)

**osu!lazer version:** After https://github.com/ppy/osu/pull/10696

**Logs:** not needed

**Comment by bdach** [comment]
The `TimeFadeIn` adjustment is happening too late after that PR:

https://github.com/ppy/osu/blob/16f55de4952be72c7ec32549d7a66b456e8dc209/osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs#L29-L30

`ApplyCustomUpdateState` is too late as the value is being read inside `UpdateInitialTransforms()`:

https://github.com/ppy/osu/blob/16f55de4952be72c7ec32549d7a66b456e8dc209/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs#L147

**Comment by peppy** [comment]
Not too sure on the best solution here. Doesn't seem like an easy one to fix if continuing to use `ApplyCustomUpdateState`, unless we have an event hook that is guaranteed to run before any state application is performed.

Still not 100% sure on why this can't remain as it was before, so probably need to look into the flow of events with pooling before making a call on this, but we could potentially just add a new event hook as above, to resolve the issue quickly.

**Comment by smoogipoo** [comment]
> Still not 100% sure on why this can't remain as it was before

Because as I mentioned in the original PR, `ApplyToDrawableHitObjects` isn't guaranteed to occur in-order from the first object in the beatmap, and is only called once per DHO (of which will be less than the total number of objects after pooling).

I think the best solution here is to get https://github.com/ppy/osu/pull/10717 merged in first, and expose an event like `HitObjectApplied`, and bind to that instead.
