### ISSUE TITLE
Slider end circles don't fade out when rewinding with Hidden mod

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#10720]
**Screenshots or videos showing encountered issue:** 
![iclFta1fe1](https://user-images.githubusercontent.com/35318437/98421853-2fafa200-203f-11eb-8f56-3616f48bde1d.gif)

**osu!lazer version:** 2020.1031.0

**Logs:** not needed

**Comment by bdach** [comment]
Also regressed with https://github.com/ppy/osu/pull/10696 - the following two values need to be invalidated upon a rewind or calculated separately for each DHO:

https://github.com/ppy/osu/blob/16f55de4952be72c7ec32549d7a66b456e8dc209/osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs#L43-L44

**Comment by Joehuu** [comment]
It didn't regress in that PR, as I could reproduce on 2020.1031.0. Maybe it was already broken since slider end circle support for hidden was implemented.

**Comment by bdach** [comment]
On another look, you're right, it seems to have been broken since `sliderendcircle` support went in.

**Comment by peppy** [comment]
Initial checking shows that this has regressed in the same way as seen in https://github.com/ppy/osu/issues/10719, causing wrong initial value to be read. May not be the only issue at play here, but should probably wait for that to be resolved before attempting any fix here.
