### ISSUE TITLE
Increased memory usage when changing window focus during gameplay

### ISSUE THREAD

**Issue by alexcher-im** [ppy/osu#10727]
**Describe the bug:** 
When watching someone playing beatmap (including osu autoplay), if you switch between osu and some another window, memory usage increases more and more and never drops. This depends on size of beatmap, and the longer map is - more memory used each time you switch between windows. Also, when you close current play and start another (it may be a osu autoplay for the same map), memory from previous maps is not freed, but looks like reused: it stays on relatively same level, but it increases if you continue switching between windows

**Screenshots or videos showing encountered issue:** 
![изображение](https://user-images.githubusercontent.com/43251717/98441963-d5801100-2112-11eb-808e-20b914ec4a29.png)

**osu!lazer version:** 
osu 2020.1031.0.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/5504790/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5504791/runtime.log)

**Comment by bdach** [comment]
Just to clarify, by "watching someone playing", you mean watching a replay, correct?

**Comment by alexcher-im** [comment]
Yep. I was testing on osu autoplays

**Comment by peppy** [comment]
Can you please open the ctrl-f2 view and take screenshots of all the stats contained in it (once getting your game into the bad state)?

**Comment by alexcher-im** [comment]
<details>
<summary>When using about 9-10GB of RAM as windows task manager says</summary>

![img](https://user-images.githubusercontent.com/43251717/98443337-a752ff00-211b-11eb-9a99-8124d00c5891.png)

![img](https://user-images.githubusercontent.com/43251717/98443341-b3d75780-211b-11eb-9485-b96c3d43690b.png)

![img](https://user-images.githubusercontent.com/43251717/98443352-c487cd80-211b-11eb-91d6-93bd7c9ac332.png)

</details>

**Comment by peppy** [comment]
Those are probably false alarms caused by the memory usage being so high in the first place. Very hard to tell what is going on, but we may be able to look into it further if you can send a memory dump via email (pe@ppy.sh). You can create one from task manager's right click menu. Please make sure to compress it as it may be quite large.

**Comment by alexcher-im** [comment]
Sending a memory dump is a bit difficult for me since i have problems with my internet connection now

I found out that if i force garbage collection after replay stopped, memory usage becomes normal
Also, i took 2 snapshots at the start of the replay and after i switched between windows about 30 times, compared them and noticed that there are a lot of spawned `ConcurrentQueueSegment<Task>` object and their content (`Task`, `Action` and `ContingentProperties`) use a lot of RAM


<details>
<summary> dotMemory screenshots</summary>

comparison of snapshots, most memory used:
![img](https://user-images.githubusercontent.com/43251717/98462945-eab77700-21c8-11eb-80ed-364155a5ffee.png)

ConcurrentQueueSegment objects:
![img](https://user-images.githubusercontent.com/43251717/98463554-00c73680-21cd-11eb-9e5e-bac45b975125.png)


snapshot with increased memory usage, object sizes:
![img](https://user-images.githubusercontent.com/43251717/98462993-379b4d80-21c9-11eb-9039-629043b4b1e1.png)


</detail>

**Comment by peppy** [comment]
I guess my suspections were correct then.

![image](https://user-images.githubusercontent.com/191335/98463775-3259f500-2201-11eb-91c2-e1d2a4dfbb0a.png)

Does this only happen if you first seek the replay towards the middle/end of a beatmap? I'm guessing it's via the `InvalidateState` path whenever the samples are dimmed in volume or otherwise:

![image](https://user-images.githubusercontent.com/191335/98463834-b8763b80-2201-11eb-86cd-14c9b2830520.png)

This will actually be heavily alleviated by hitobject pooling (coming in soon), but we should probably also fix the underlying issue. The above invalidate call should probably be added using a `Scheduler.AddOnce` or similar, I'll look into this.

**Comment by alexcher-im** [comment]
I tried to seek to the end, osu now uses 4.5GB of ram (as task manager says), but if i seek to random locations memory usage does not grows, or what do you mean i should try?
By the way, is this a public discord server on your first screenshot? Can i get a link? :P

**Comment by peppy** [comment]
I mean if you try to perform this while still at the beginning of the map, the overhead should be much lower, in theory (because the samples are not yet initialised).

That said, I still cannot reproduce. Can you confirm your audio thread is running at 1000hz?

**Comment by alexcher-im** [comment]
Memory usage grows when focusing osu window even at the beginning of the map (i'm trying on 22 minutes long map)

Audio thread runs at 1000hz when window focused and 60hz otherwise

**Comment by peppy** [comment]
Are you using a custom skin? Does this happen with the default skin? Have you customised any other settings that could potentially trigger something like this?

**Comment by bdach** [comment]
For what it's worth I can also see some kind of gen2 memory accumulation when the window is unfocused on linux, although not on that big of a scale. Does not seem to be cleaned up afterward.

**Comment by alexcher-im** [comment]
Yes, i'm using default skin. Most settings are set to default, and the only changed audio settings are volume, but i dont think it's related :D 

Try to reproduce this on long maps (20 minutes long or more)
i'm trying on https://osu.ppy.sh/beatmapsets/899518, last diff

And yes, memory usage grows in gen2, but i found it happens on focusing window, not unfocusing

**Comment by peppy** [comment]
This whole discourse could have been avoided if you mentioned it was only happening in said beatmap. This is unrelated to window focus or anything else and completely to do with the beatmap being played. Would be appreciated if such details were included from the start in future reports, thanks!

On a quick check it's related to the storyboard.

**Comment by alexcher-im** [comment]
No, i see the same thing on other maps, but i found that is the most demonstrative

Another map, it has no storyboard:
If i focus-unfocus osu window about 30-40 times, i see 1.5GB more memory used
Map: https://osu.ppy.sh/beatmapsets/1016805
