### ISSUE TITLE
Failed to import beatmap 33842

### ISSUE THREAD

**Issue by Muffyn** [ppy/osu#10733]
**Describe the bug:** 
https://osu.ppy.sh/beatmapsets/33842/#osu/110638
I cannot import this specific beatmap, ranked 9 years ago. Downloading from osu!direct. Other beatmaps are working fine. It seems other players are able to play this beatmap on lazer as there is a pass in the multiplayer lobby. Restarting the client didn't work either. Logs will probably show what went wrong.

**Screenshots or videos showing encountered issue:** 
![osu_2020-11-07_17-00-36](https://user-images.githubusercontent.com/33764011/98452289-d0738f80-211b-11eb-9342-2ed9482440ee.jpg)

**osu!lazer version:** 
2020.1031.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5505545/database.log)
[network.log](https://github.com/ppy/osu/files/5505546/network.log)
[performance.log](https://github.com/ppy/osu/files/5505547/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5505548/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5505549/updater.log)

edited to fix logs

**Comment by bdach** [comment]
Your database seems to have gotten into a broken state somehow. If you're don't mind resetting your database, the temporary workaround for this is to generally move away or delete `%AppData%/osu/client.db` and reimport everything from stable - in the long term we will be looking into fixing those sorts of errors properly, but our database system is in a bit of a limbo as we're waiting for a possible alternative to the solution we're currently using.

Not sure whether there's much more we can do regarding this right now; closing.
