### ISSUE TITLE
Not stable FPS in osu!lazer

### ISSUE THREAD

**Issue by MikelvGP** [ppy/osu#10739]
**Describe the crash:** 
Lags in game on my pc. 
**Screenshots or videos showing encountered issue:** 
https://youtu.be/KAPXGpmTTK0
**osu!lazer version:** 
2020.1031.0
**Logs:**

**Computer Specifications:** 
PC:
CPU:Amd ryzen 3 1200
GPU:Amd radeon 550
Ram:8GB DDR4 2633Ghz
3 Hard Drive.

**Comment by PercyDan54** [comment]
In the video it reached 200FPS which is enough

**Comment by bdach** [comment]
The video doesn't show the in game FPS counter, but from whatever it is in the upper left corner I infer you might be running with the frame limiter off. If you are, please turn it back on.

If that is not the case this issue doesn't contain enough information to begin investigating (no FPS counter, no logs, no Ctrl-F2 view). Closing as inactionable, will reopen if details are provided.

**Comment by peppy** [comment]
On top of that, frame times look normal. Maybe you aren't running full screen.
