### ISSUE TITLE
Crashes due to null drawables in some storyboard animations

### ISSUE THREAD

**Issue by cadon0** [ppy/osu#10748]
**Describe the crash:** 

Some storyboard animations result in crashes due to null drawables being created

It seems more common that sprites for storyboard animations take the filename declared for the animation in the `.osb` file
and append numbers, starting from 0. I have found two exceptions
 
**Screenshots or videos showing encountered issue:** 

1) The first (0th) sprite has no 0 appended to the animation filename, from [beatmap 192137](https://osu.ppy.sh/beatmapsets/192137)

    ```
    Animation,Background,Centre,"noise\noise_0000.jpg",320,240,10,1,LoopForever
     F,0,49813,,1
     M,0,49813,50313,320,240
     M,0,50313,,320,240
    ```
    Note the filename is `"noise\noise_0000.jpg"` with four zeroes

    Then note that the first sprite matches this exactly, and the rest append their index as expected

    ![image](https://user-images.githubusercontent.com/25311843/98547336-e1c7c200-22fc-11eb-9099-e1d8e64c6141.png)

    This crash will occur at any time the animation is expected to play, the first being just before the 50 second mark

1) Animations intentionally declared with more frames than sprites to cause a blinking effect, from [beatmap 5381](https://osu.ppy.sh/beatmapsets/5381)

    ```
    Animation,Foreground,TopLeft,"spr\play-skip.png",525,410,3,1000,LoopForever
     S,0,-44000,,0.8
     F,0,-44000,,1
     F,0,-1000,,0
     F,0,0,,1
     F,0,29900,,0
    ```
    Note the `,3,` in line 1, I assume this number represents the number of frames

    Then note that there are only two sprites

    ![image](https://user-images.githubusercontent.com/25311843/98545850-f5722900-22fa-11eb-88d2-e7b93412e4a3.png)

    When playing this beatmap in osu!stable you are be able to see the custom skip button blinking in the corner. In current osu!lazer the third frame becomes a null drawable, causing an almost immediate crash (since the skip button is scheduled for the very start)

1) This is just an example of a storyboard animation without issues, also from [beatmap 5381](https://osu.ppy.sh/beatmapsets/5381):

    ```
    Animation,Background,BottomLeft,"bg\gavel.png",0,480,5,300,LoopOnce
     F,0,22543,23705,1
    ```
    ![image](https://user-images.githubusercontent.com/25311843/98545512-7a107780-22fa-11eb-8536-9b48f7a5a9d6.png)

**osu!lazer version:** 

Built from latest master

**Solution:**
I have a [work in progress fix](https://github.com/cadon0/osu/pull/1). While it does resolve both crashes:
1) I am not sure this is the best approach. Advice would be appreciated. A check to see if the file exists would be much nicer than waiting for `CreateSpriteFromResourcePath(...)` to return `null`, but the assets seem to be managed by stores. Is that a path worth going down?
2) It does not allow the blinking effect - this seems like it might be a deeper issue that should be tackled separately
3) There's no tests yet 🙂

**Comment by peppy** [comment]
Honestly the best approach sounds like inserting empty drawables for missing frames. The logic in your linked branch seems to have much more logic than required.

**Comment by peppy** [comment]
@cadon0 for case 1 no special treatment is required. stable will actually *not* read the `0000` file, so in your implementation it can be added as a `Drawable.Empty()` along with other cases of missing files.

![image](https://user-images.githubusercontent.com/191335/98637997-9816c000-236c-11eb-8109-170309aaa043.png)

**Comment by cadon0** [comment]
Oh interesting, that simplifies things. Thanks, I've rewritten what I had
