### ISSUE TITLE
[iOS] Game doesn’t respond to touch input

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#10749]
**Describe the bug:** 
The game will not respond to touch input.
EDIT 1: what’s weird is that the parallax on the main menu still occurs when I tap or drag on the display.

EDIT 2: tested with Magic Trackpad 2 over Bluetooth, pointer tracking works fine but clicking doesn’t work and makes the cursor disappear until I move it again. EDIT 3: also hovering over UI elements such as the osu! cookie will not trigger the respective actions that would normally happen.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/z2i3GbBbw6k

**osu!lazer version:** 
2020.1109.0

**Logs:**
Can’t get em, not jailbroken anymore.

Happens on my iPhone X and iPad Pro 2020 11”, both running iOS 14.1

**Comment by peppy** [comment]
The build has been revoked.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu-framework/pull/3988. Need to wait for next release though.
