### ISSUE TITLE
osu not letting my use my cursor when i click insert and open it back up.

### ISSUE THREAD

**Issue by OsuTheBest** [ppy/osu#10741]
**Describe the bug:** 
When i click insert key on my keyboard and re-open it my osu cursor is gone and my mouse cursor is there, so i can't click anything so i have to spam alt f4 or go to task manager.
**Screenshots or videos showing encountered issue:** 
N/A
**osu!lazer version:** 
N/A
**Logs:**
<!--
*please attach logs here, which are located at:*
%AppData%/osu/logs

**Comment by bdach** [comment]
Cannot reproduce locally, and issue has no attached video, no screenshots, no OS information. Please do not open issues unless you can actually provide all necessary information.
