### ISSUE TITLE
Keyboard doesnt work

### ISSUE THREAD

**Issue by Zen1thOrSomething** [ppy/osu#10754]
Im not sure if this is a bug or not but when I plug in my keyboard it doesnt work, I also cannot turn on on "raw imput"

im using version 2020.1020.0

**Comment by bdach** [comment]
You have provided no information about your platform of choice and haven't filled out the issue template. Closing until that bare minimum is fulfilled.

**Comment by Zen1thOrSomething** [comment]
I use an 12.9-inch iPad Pro (3rd generation) with a ducky one2 mini plugged throught a female to male usb-c adapter

**Comment by bdach** [comment]
Raw input has little sense on mobile platforms and is only enabled on windows for now as the current implementation has issues everywhere else. As to why the keyboard is broken, no idea as I don't own a device to test. People apparently have had success with smart keyboards.

**Comment by Zen1thOrSomething** [comment]
ok, thanks for the help

**Comment by Zen1thOrSomething** [comment]
seems like its working
but my stylus aint woking as a mouse

**Comment by bdach** [comment]
Judging by this I assume it's actually working.

![2020-11-09-215006_499x138_scrot](https://user-images.githubusercontent.com/20418176/98594911-94842a00-22d5-11eb-8dd9-81321a8afeb5.png)

Closing again.
