### ISSUE TITLE
Earn too much PP on Classic Score display mode in osu!mania Gamemode

### ISSUE THREAD

**Issue by DomiZone1** [ppy/osu#10752]
If the Score display mode is set to "Classic". The player earns way to much PP on osu!mania.

I tested this with a few maps, and it seems to work reliably on all osu!mania maps (which i could beat aka below 3* and 4k only)!  osu!standard and Score display mode "Classic" is seemingly correct.

Map: flowers feat. nori by in love with a ghost [4k bloom]
The link to the map (if needed): https://osu.ppy.sh/beatmapsets/962550#mania/2016814

The scores:
![Scores_flowers feat  nori - in love with a ghost by -MysticEyes  4k bloom](https://user-images.githubusercontent.com/74203314/98575819-f59e0480-22b9-11eb-8032-8294dca27393.png)

On Score display mode: Classic
![Score_Classic_flowers feat  nori - in love with a ghost by -MysticEyes  4k bloom](https://user-images.githubusercontent.com/74203314/98575771-e15a0780-22b9-11eb-8ce4-97bc45fcac81.png)

On Score display mode: Standardised
![Score_Standardised_flowers feat  nori - in love with a ghost by -MysticEyes  4k bloom](https://user-images.githubusercontent.com/74203314/98575807-ee76f680-22b9-11eb-847f-cb248dd8ade4.png)

osu!lazer version: 2020.1109.0
OS: Linux Ubuntu 20.04

Logs:
[runtime.log](https://github.com/ppy/osu/files/5512283/runtime.log)

[database.log](https://github.com/ppy/osu/files/5512275/database.log)

[network.log](https://github.com/ppy/osu/files/5512277/network.log)

[performance.log](https://github.com/ppy/osu/files/5512279/performance.log)

**Comment by bdach** [comment]
My immediate thought was to recalculate the score locally in the performance calculator using standardised, but I think the better way forward might actually be to always import standardised total scores to DB. Right now it's whatever mode is currently set which is a little messy - now that we have dynamic recalculation it might be a good time to normalise.
