### ISSUE TITLE
Game crash after pressing too many F9s to find a player to spectate

### ISSUE THREAD

**Issue by dolkilu** [ppy/osu#10753]
**Describe the crash:** 
Game crash after pressing too many F9s to find a player to spectate
I was trying to find someone worth watching, lots of them are online 20days ago or too low rank.
Because osu doesnt have a back button, I have to press lots of F9 to go back to the online players page, and the game crashes.
**osu!lazer version:** 
2020.1109.0
**Logs:**
[performance.log](https://github.com/ppy/osu/files/5512687/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5512689/runtime.log)
**Computer Specifications:** 
i7-9700k
2080

**Comment by bdach** [comment]
It's not due to "too many F9s". It's a crash from the profile page, more specifically the user rank graph.

**Comment by peppy** [comment]
Just for the record, "online 20 days" ago users are still live. It just means they haven't visited the website and only played on lazer (which doesn't update the last-visit time just yet).
