### ISSUE TITLE
game should not play an applause if you use autoplay

### ISSUE THREAD

**Issue by igontusuwu** [ppy/osu#10762]
you shouldn't get an applause for something you didn't do

the game shouldn't play an applause for viewing a score either

**Comment by bdach** [comment]
Also probably applies to opening not-own scores from the leaderboard.

**Comment by peppy** [comment]
I did it this way intentionally. Can see how strongly people feel about this.

**Comment by Game4all** [comment]
It feels weird to have applause sound playing when looking at scores set by other people in the leaderboard, or when opening the results screen from song select.

I'm of the opinion it should only ever play after setting a score.

**Comment by peppy** [comment]
Are you okay with it playing when arriving at the results screen while spectating someone?

**Comment by Game4all** [comment]
I don't think it would bother me, as long as the applause sound is played on entering results screen after completing a map (be it while spectating, watching a replay , or after setting a score)
