### ISSUE TITLE
Lazer wont launch/open

### ISSUE THREAD

**Issue by Boomy639** [ppy/osu#10779]
**Describe the crash:** 
Double clicked on osu lazer-shows a loading icon for maximum of around 4 seconds,then just dissapears and nothing happens
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
osulazer-2020.1109.0
**Logs:**
there are none

**Computer Specifications:** 
4 GB Ram
Pentium (R) Dual-Core CPU E5800 @3.20 GHz
Intel G41 Express Chipset
(Normal osu! works fine, osu!lazer wont run

**Comment by bdach** [comment]
Please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by Boomy639** [comment]
ok

**Comment by Boomy639** [comment]
how do i atach the windows event viewer logs here?

**Comment by Joehuu** [comment]
Seems like the chipset doesn't support > OpenGL 3 as documented in https://www.intel.com/content/dam/www/public/us/en/documents/product-briefs/g41-chipset-brief.pdf and https://en.wikipedia.org/wiki/Intel_GMA.

**Comment by Boomy639** [comment]
so...i need 3.0?

**Comment by bdach** [comment]
Please make a ZIP archive with the file and drag and drop it into the comment box.

That said if this is due to lack of opengl support we will not be able to help you for now. There is a plan to add alternate graphics backends such as directx but that is not likely to happen in the near future.

**Comment by Boomy639** [comment]
[logs.zip](https://github.com/ppy/osu/files/5519306/logs.zip)

**Comment by Boomy639** [comment]
Application: osu!.exe
CoreCLR Version: 4.700.20.36602
.NET Core Version: 
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFB09D71D5B (00007FFB09BE0000) with exit code c0000005.

**Comment by Boomy639** [comment]
i also found this

**Comment by bdach** [comment]
That's an unspecific access violation exception (see #10639, #10174, #5708), and indicates some kind of problem or incompatibility with your machine. Please try to install Windows updates and any device driver updates you can find and try again, but other than that we might not be able to help you for now.

**Comment by Boomy639** [comment]
alright well thanks anyway
