### ISSUE TITLE
Incorrect storyboard animation speed

### ISSUE THREAD

**Issue by cadon0** [ppy/osu#10772]
**Describe the bug:** 
The `play-skip` animation cycle in [beatmap 5318](https://osu.ppy.sh/beatmapsets/5318) is much slower than on stable.

Animations in other storyboards, such as [beatmap 100049](https://osu.ppy.sh/beatmapsets/100049), match stable as expected.

In this example `play-skip`s `FrameDelay` of 1000 is given to each sprite. Upon dividing the `FrameDelay` by the number of frames the animation speed looks correct - but this will break animations in other maps.

`Animation,Foreground,TopLeft,"spr\play-skip.png",525,410,3,1000,LoopForever`
![image](https://user-images.githubusercontent.com/25311843/98654392-20b05300-23a3-11eb-8be2-ada580ea53d6.png)

**Screenshots or videos showing encountered issue:** 

![2020-11-10_22-26-21](https://user-images.githubusercontent.com/25311843/98655352-3bcf9280-23a4-11eb-9914-548956bb2e5e.gif)

**Comment by peppy** [comment]
```csharp
    if (BeatmapManager.Current != null && BeatmapManager.Current.BeatmapVersion < 6)
        Animation.FrameDelay = Math.Round(0.015 * frameDelay) * 1.186 * GameBase.SIXTY_FRAME_TIME; //backwards compatibility for older storyboards.
    else
        Animation.FrameDelay = frameDelay;
```
