### ISSUE TITLE
Hard crash when missing on LN maps

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#10771]
**Describe the crash:** when missing on LN maps, lazer will hard crash because "A DrawableHoldNote was hit before it became hittable!". This can very easily be reproduced by playing a dense LN map and missing, after which lazer will be almost guaranteed to crash. (audio offset is set to 0ms)

**Screenshots or videos showing encountered issue:** https://streamable.com/onu9lo

**osu!lazer version:** 2020.1109.0.0

**Logs:** https://www46.zippyshare.com/v/X2RCNlA8/file.html

**Computer Specifications:** i5-7500, GTX 1060, 8GB RAM, Windows 10 2004

**Comment by bdach** [comment]
This'll be the notelock implementation playing up, although I'm unsure as to why or if I can ever reproduce this myself without months of mania training...

**Comment by Joppe27** [comment]
I forgot to mention that this bug is not present in 2020.1031.0 and as far as I know, nothing has changed to notelock since then which is why I reported this crash in the first place.

**Comment by bdach** [comment]
That is pretty important information, albeit I can't immediately point to one change from the last release that could cause this.

**Comment by Firmatorenio** [comment]
I can reproduce the crash pretty easily by spamming some 1/8 long notes into the same column at OD0 and just spamming a button through them, but that doesn't exactly point to anything for me, maybe breakpoints will help.
https://www.youtube.com/watch?v=YurNZ5-lRaw
[runtime.log](https://github.com/ppy/osu/files/5517784/runtime.log)

After experimenting with holds to try and get a more specific pointer, I couldn't get the game to actually crash, but it sometimes fails to show me the results screen: https://www.youtube.com/watch?v=ZQDT6BfEIzA

After dropping it down to just one long slider, that particular behavior mostly gets reproduced by spamming the button through the hold (and resulting in a Meh): https://www.youtube.com/watch?v=COV3jHBe0nA

I'm not sure if it's the same exact issue, but it might be related.
