### ISSUE TITLE
taiko strong hit drum samples are extraordinarily loud

### ISSUE THREAD

**Issue by bdach** [ppy/osu#10778]
Steps for best reproduction:

1. Open a map with many strong hits (i.e. https://osu.ppy.sh/beatmapsets/546820#osu/1158221, as a convert)
2. Start autoplay, seek to a part with strong hits
3. Change focus to another window
4. Strong hits will start playing very loudly while unfocused

This is also sometimes reproducible when seeking backward while the window is focused, but less so.

Broke with https://github.com/ppy/osu-framework/pull/3980. Presumably linked with the lifetime management parts of `InputDrum` and `DrumSampleContainer`.

Not much idea how to fix yet as unsure of the cause. Definitely some kind of result of the ordering changes, just not sure how exactly. *Presumably* going to have to get fixed in framework but not 100% sure.

**Comment by peppy** [comment]
I'm sure we already fixed this once. The cause is going to be the sample playing twice (or more) from multiple sources.

It's probably only audible when the window is not focused because there's more headroom to increase volume. The same effect can likely be observed by just turning down game volume.

**Comment by peppy** [comment]
On checking this, it actually does look like it's somehow completely bypassing volume setting.

**Comment by smoogipoo** [comment]
May be related, but I've noticed recently that sometimes osu! starts without my 0% global volume getting applied. Not sure how to reproduce it though.

**Comment by peppy** [comment]
Is it momentary? Or does the track continue to play at non-zero volume indefinitely?

**Comment by smoogipoo** [comment]
It's only affected samples, specifically the beating of the osu!logo when hovered (that's all I can conclusively point towards). The track itself is at 0%.
