### ISSUE TITLE
Significant cursor lag when mouse polling rate set to 1000 Hz (which is fixed by ctrl-F2???)

### ISSUE THREAD

**Issue by signedinteger** [ppy/osu#10780]
**Screenshots or videos showing encountered issue:** 
[500 Hz polling rate]: https://streamable.com/7r94dr
[1000 Hz polling rate]: https://streamable.com/4xw2tx

**osu!lazer version:** 2020.1109.0

**Logs:**
[500 Hz]
[logs.zip](https://github.com/ppy/osu/files/5519779/logs.zip)

[1000 Hz]
[logs.zip](https://github.com/ppy/osu/files/5519815/logs.zip)
(I turned on ctrl-F2 at roughly 19:42:55, and I cannot reproduce the lag afterwards)

**Comment by bdach** [comment]
The input thread is definitely dipping below 1ms frame times on the second video, but I don't know that that should cause such bad delays...

**Comment by peppy** [comment]
Videos are pointless without showing the frame graph (Ctrl-F11 again).

99.99% your mouse drivers, or something else on your system hooking system-wide input.

**Comment by signedinteger** [comment]
500 Hz polling with frame graph: https://streamable.com/ed1zc0
1000 Hz                                       : https://streamable.com/f9dzq2

**Comment by peppy** [comment]
This confirms it. The issue is the white spikes on the "input" thread. This is another application on your system taking time on the main window loop, blocking lazer from being able to run.

This will affect all applications on your system, although you may not notice it as much as in a game.
