### ISSUE TITLE
How the extended result screen should look like...

### ISSUE THREAD

**Issue by MitsukaiDokuro** [ppy/osu#10808]
How it currently (2020.1109.0) looks:
![image](https://user-images.githubusercontent.com/68403898/98945295-9ecf3f80-24f2-11eb-8ab3-762864cb7a73.png)

How I would design it:
![image](https://user-images.githubusercontent.com/68403898/98945231-83fccb00-24f2-11eb-933b-7d5a44ddb189.png)

- Insert bars in the timing distribution graph for the maps' difficulty parameters (hit window for a 300, 100 and 50)
- Overlay a normal distribution fitted to the values over the timing distribution graph
- Move the labels for the unstable rate in the gravitational center below the normal distribution if there is enough space, else 
above - or make it only show while hovering over the normal distribution
- Add the unit given (ms)as label to the x axis
- Rename "Timing Distribution" to "Timing", "Accuracy Distribution" to "Positioning" to avoid naming conflicts. Alternatively I would suggest "Accuracy" and "Precision"
- Attach related numerical information to "Timing" and "Positioning" labels
- Move the "~~Accuracy~~ Positioning Heatmap" to the left half of the "Positioning" panel
- Add a distribution graph similar to the one for "Timing", but for "Positioning" to the right half of the "Positioning" panel

Related issues: #9990, #9395

**Comment by peppy** [comment]
what is the point of two of the same graph

**Comment by bdach** [comment]
This is not the final look of this screen. See https://github.com/ppy/osu/issues/8314#issuecomment-679161847 for a preview. I believe that design should address most of your issues.

**Comment by MitsukaiDokuro** [comment]
@peppy it's not supposed to be the same graph, my painting is just copy pasta. lower graph contains timing delta values based on OD, while the lower one contains positioning delta values (distance-from-center) values based on CS.
@bdach Definitly looks better, but my feedback is still valid please don't ignore it, thanks...

**Comment by bdach** [comment]
OK, let's take it one by one then:

> Insert bars in the timing distribution graph for the maps' difficulty parameters (hit window for a 300, 100 and 50)

Can be addressed by the redesign linked above. For extra bonus might also color-code the bars of the distribution graph.

> Overlay a normal distribution fitted to the values over the timing distribution graph

Disagree. Not many people are aware of what a normal distribution is. osu! is a game, not a statistics toolkit.

> Add the unit given (ms)as label to the x axis

Sure, I guess.

> Rename "Timing Distribution" to "Timing", "Accuracy Distribution" to "Positioning" to avoid naming conflicts. Alternatively I would suggest "Accuracy" and "Precision"

I don't understand how that's unclear.

> Attach related numerical information to "Timing" and "Positioning" labels

Can be done when *that's actually implemented*.

> Move the labels for the unstable rate in the gravitational center below the normal distribution if there is enough space, else above - or make it only show while hovering over the normal distribution
> Move the "Accuracy Positioning Heatmap" to the left half of the "Positioning" panel

Screen will be reorganised. Current alignment is temporary.

> Add a distribution graph similar to the one for "Timing", but for "Positioning" to the right half of the "Positioning" panel

What would be the value of such a graph be?

**Comment by MitsukaiDokuro** [comment]
>Can be addressed by the redesign linked above. For extra bonus might also color-code the bars of the distribution graph.
Ok fair point, even though I have trouble fully understanding the WIP implementation.

> Disagree. Not many people are aware of what a normal distribution is. osu! is a game, not a statistics toolkit.
But then again why show the unstable rate and not explain? I mean, both the fitted normal distribution and the UR should probably be hidden somewhere or only while hovering.

> I don't understand how that's unclear.
Well, I, as a player associate the term "accuracy" with the percentage in the results screen. Since OD heavily influences that number (along with HardRock & Easy) I then associate it heavily biased towards timing accuracy, so reusing the term for a the hit/miss concept is misleading. Using the term precision still isn't quite the solution either. That's why I split it to "Timing" and "Positioning".

> What would be the value of such a graph be?
The heatmap doesn't show any numbers, I would love to see an alternative form of showing how well someone performed. I always aim for the center of hit circles which is shown in my skin. If two graphs for the same set of samples is inconvenient, how about making it cycle its display form on click?
