### ISSUE TITLE
no internet on linux

### ISSUE THREAD

**Issue by darkralts** [ppy/osu#10809]
**Describe the bug:** 
i open the game i cant download maps or look at leaderboards and i cant log in
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/16366107/98977517-af79b880-24e6-11eb-90b5-ca2d52dc7bda.png)

**osu!lazer version:** 

**Logs:**

**Comment by bdach** [comment]
Do not open issues if you're going to thoroughly disregard the issue template.
