### ISSUE TITLE
Moving through timeline in the editor while the beatmap is still loading breaks object drawing.

### ISSUE THREAD

**Issue by OwczarekGit** [ppy/osu#10806]
**Describe the bug:** 
As the title says, see attached gif for more info.
That somehow forces redraw of all the objects, you can also select objects that are not "close enough" on the timeline.

**Screenshots or videos showing encountered issue:** 
![out](https://user-images.githubusercontent.com/32412218/98933613-2c099880-24e1-11eb-8b0f-f06351940ea9.gif)

**osu!lazer version:** 
2020.1109.0
Linux AppImage

**Logs:**
[database.log](https://github.com/ppy/osu/files/5530265/database.log)
[network.log](https://github.com/ppy/osu/files/5530266/network.log)
[performance.log](https://github.com/ppy/osu/files/5530267/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5530268/runtime.log)

**Comment by peppy** [comment]
Can't seem to break things any more. Likely fixed by pooling.
