### ISSUE TITLE
Sliderhead triangles are updated every frame

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10814]
Sliderhead triangles are updated every frame when interacting with sliders ~~in the Editor.~~
I feel like I've seen this be fixed before, but I couldn't find anything when searching through.

Video: https://i.imgur.com/m6Z2iB6.gif
osu!lazer version: 2020.1109.0

**Comment by peppy** [comment]
This is known and is a limitation of the triangle display (it does not know its "start time").

**Comment by Joehuu** [comment]
This does not happen anymore.
