### ISSUE TITLE
Sliders arent fully drawn as they are created

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10821]
Only when the sliderend has been placed is the slider fully drawn as it would be during gameplay. This doesn't match osu!stable behaviour.

video: https://i.imgur.com/rGzd30U.gif
osu!lazer version: 2020.1109.0

**Comment by bdach** [comment]
I'm relatively certain that was intentional. Is this a problem when mapping? The only thing you might not be seeing when placing right now is the combo index as far as I can tell.

**Comment by peppy** [comment]
This is the intentional behaviour of blueprints.

**Comment by Pennek** [comment]
huh really? guess i'll just have to see what's coming up

>  Is this a problem when mapping?

most sliders are initially drawn as rough sketches and then adjusted afterwards, meaning visuals matter. Feels backwards that visuals aren't trying to match what happens during gameplay. mostly a minor inconvenience

**Comment by peppy** [comment]
The blueprint should give you all the details required. If there's something missing/wrong please point that out specifically.

**Comment by Pennek** [comment]
I'd prefer if the slider was fully drawn as it'd look like in gameplay, but I'll leave it as is. I'm guessing it's just a preference thing and I'll get used to blueprints soon enough
