### ISSUE TITLE
Notes under Hidden Mod appears to be dimmer than osu! stable

### ISSUE THREAD

**Issue by koyaiba** [ppy/osu#10824]
**Description:**
As the title described. The screenshot shows the brightness comparison between osu! stable (top) and osu! lazer (bottom) at the exact frame.

**Screenshot:**
![image](https://user-images.githubusercontent.com/25640063/99067678-1336db00-25e6-11eb-845d-2677ae5a4965.png)

**osu! lazer version:** 2020.1109.0

**Comment by bdach** [comment]
#10719
