### ISSUE TITLE
Mouse confinement not working as expected when alt-tabbing in windowed mode

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#10833]
**Describe the bug:** 
Having mouse confinement set to "gameplay only", this setting seems to affect the mouse cursor even if osu!lazer isn't even the focused window, by alt-tabbing right after starting to load a map. This makes it impossible to move the mouse further than lazer's window size until lazer is focused again.

Afterwards, alt-tabbing twice causes kind of the opposite to happen; the mouse cursor can move "outside the window" while lazer is focused, but won't actually appear outside the window, this might be related to #10465.
 
**Screenshots or videos showing encountered issue:** 
https://streamable.com/zxvjrw

**osu!lazer version:** 
2020.1114.0

**Windows version:**
Windows 10 Pro x64 build 10.0.20257.1

**Comment by peppy** [comment]
Sounds like focused state is not being updated correctly? Are you able to test with `--sdl` and see if the same thing happens?

**Comment by Morilli** [comment]
Hm no, both issues disappear using `--sdl`.

**Comment by Joehuu** [comment]
Fixed in SDL as of now.
