### ISSUE TITLE
LifetimeStart is not being set to expected time implicitly

### ISSUE THREAD

**Issue by LumpBloom7** [ppy/osu#10834]
**Describe the bug:** 
The `LifetimeStart` of `DrawableHitObject`s aren't implicitly set to `HitObject.StartTime - InitialLifetimeOffset`, leading to performance and/or visual problems in rulesets that doesn't manually calculate `LifetimeStart`.

**Screenshots or videos showing encountered issue:** 
N/A

**osu!lazer version:** 
2020.1114.0

**Logs:**
N/A

**Comment by bdach** [comment]
As far as I can see, that logic has been moved to `HitObjectLifetimeEntry` and will run on adding pooled drawables to playfield:

https://github.com/ppy/osu/blob/aae59dc3cf0e1b518d1b6872de1162eb22457d74/osu.Game/Rulesets/Objects/HitObjectLifetimeEntry.cs#L105-L108

but it'll *only* run in the pooled case as non-pooled objects don't get a HOLE:

https://github.com/ppy/osu/blob/aae59dc3cf0e1b518d1b6872de1162eb22457d74/osu.Game/Rulesets/UI/Playfield.cs#L121-L129

https://github.com/ppy/osu/blob/aae59dc3cf0e1b518d1b6872de1162eb22457d74/osu.Game/Rulesets/UI/Playfield.cs#L226-L237

**Comment by smoogipoo** [comment]
Yeah it needs to run in both situations. It might be as simple as just setting `LifetimeStart` where it used to be.
