### ISSUE TITLE
Delete ALL skins option freezes the game

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#10837]
**Describe the bug:** 
Using the ``Delete ALL skins`` option freezes the game. Current song will continue playing audio in the background but next song never starts. After restating the game, skins are still there.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/JIo0vTg0JDw

**osu!lazer version:** 
2020.1114.0

**Logs:**
Don't seem useful at all but here they are
[performance.log](https://github.com/ppy/osu/files/5540647/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5540648/performance-audio.log)
[performance-update.log](https://github.com/ppy/osu/files/5540649/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5540650/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5540651/updater.log)
[database.log](https://github.com/ppy/osu/files/5540652/database.log)
[network.log](https://github.com/ppy/osu/files/5540653/network.log)

**Comment by peppy** [comment]
I can't seem to reproduce this locally after multiple tries.. Are you able to share your client.db and potentially check the state of threads when this happens?

**Comment by LittleEndu** [comment]
> I can't seem to reproduce this locally after multiple tries..

Weird, it happens 100% of the time for me.

> Are you able to share your client.db

This should be done via email, right?

> check the state of threads when this happens

that I don't know how

**Comment by bdach** [comment]
> This should be done via email, right?

`client.db` doesn't really contain *very* sensitive data - well, aside from your keybindings and the beatmaps/skins/scores you have imported (but only the metadata, not the actual files). If you don't want those to be publically posted then email is fine. Memory dumps are the ones that need to be watched out for.

> that I don't know how

Any IDE should have a "threads" view when breakpointing/pausing execution that you can switch threads in and check their current call stack (not sure about VS Code, but that's not much of an IDE really). This is the sort of view (from rider) that I mean:

![2020-11-15-155203_919x489_scrot](https://user-images.githubusercontent.com/20418176/99188110-895c4e80-275a-11eb-933a-65bc08cf994c.png)

**Comment by LittleEndu** [comment]
https://gist.github.com/LittleEndu/fe7c0086385b35626262fa9f6a0095ac for the threads

https://drive.google.com/file/d/1_JgwnXI7MgJLu9ln61jHYt2ZQk7l22-N/view?usp=sharing for client.db

Hope this helps.

**Comment by bdach** [comment]
On an immediate glance looks a bit like a deadlock at `LockedWeakList`. Update thread (tid 7508) and a worker thread (tid 2764) are most likely trying to enter the same monitor.

Call sites are:

https://github.com/ppy/osu/blob/7156682efa21026c4c21d8a6c785aa24297e099d/osu.Game/OsuGame.cs#L203

and

https://github.com/ppy/osu/blob/7156682efa21026c4c21d8a6c785aa24297e099d/osu.Game/Overlays/Settings/Sections/SkinSection.cs#L109

Sure looks like we might have a feedback loop on our hands...
