### ISSUE TITLE
Beatmap Listing textbox uses a different selection color

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10839]
**Describe the bug:**  As title. The Beatmap Listing overlay has a different selection color for its textbox. It's very strange because it seems to be the only one using a gray version.

**Screenshots or videos showing encountered issue:** 
- Gray version (visible only in the Beatmap Listing overlay):
![gray selection](https://user-images.githubusercontent.com/43073074/99146731-fe585700-267a-11eb-93b6-da045ac8af8c.png)

- Pink version (visible anywhere else in lazer):
![pink selection](https://user-images.githubusercontent.com/43073074/99146669-90ac2b00-267a-11eb-9659-e7fe1577cb87.png)

**osu!lazer version:** 2020.1114.0

**Comment by bdach** [comment]
I believe for full parity with web design this should use the overlay theming system/`OverlayColourProvider`:

![2020-11-14-135016_558x133_scrot](https://user-images.githubusercontent.com/20418176/99147324-5b0a4080-2680-11eb-9863-7dd977c0ffad.png)

although maybe at this point better to forego and just have one colour everywhere...?

**Comment by peppy** [comment]
If you check the web, selection colour is themed per section so this is the intended direction.
