### ISSUE TITLE
Auto mod bugged when using Transform

### ISSUE THREAD

**Issue by joshdee** [ppy/osu#10848]
Duplicate of #10847 because I forgot to add labels, but turns out I can’t set any.

**Describe the bug:** When playing back a beatmap with said mods, the cursor somehow clicks way out of place, and looks like if it’s doing some sort of “hard rock” (if you know what I mean) sometimes it hits the circles, sometimes it doesn’t. 

**Screenshots or videos showing encountered issue:** https://youtu.be/E6hD5l59IOE

**osu!lazer version:** 2020.1114.0 (TestFlight build on iPhone 12, iOS 14.2 [18B92])

**Logs:** no logs

**Comment by PercyDan54** [comment]
Is making every object transform to their original position the intended behavior?
Chaing the call from `drawable.Position` to `hitObject.StackedPosition` seems to reslove Autoplay issue but the mod's behavior changed(though the original behavior seems broken)
Before:
![osu_2020-11-15_13-29-56](https://user-images.githubusercontent.com/50285552/99177648-cae2fe80-2746-11eb-8d5f-b73870551d7e.jpg)
After:
![osu_2020-11-15_13-28-46](https://user-images.githubusercontent.com/50285552/99177653-d0d8df80-2746-11eb-9293-fa0a37c5ba91.jpg)

**Comment by bdach** [comment]
@joshdee issue reporters are not permitted to add labels. one of the maintainers will do so.

@PercyDan54 seems correct from what I can tell. guessing this broke with pooling - feel free to PR that change.
