### ISSUE TITLE
Add a Right-Click Type of System for the mobile Osu Editor

### ISSUE THREAD

**Issue by GithubMagic360** [ppy/osu#10855]
**Describe the new feature: As of now, because of a lack of right clicking, you can not place sliders or spinners in the Standard, Taiko, and CTB editor on IOS devices (I assume android is also affected by this, however I don't own an android so I can't test) [Note, the mania editor's note and hold options are both usable] This addition would make mapping more possible on phone.

**Proposal designs of the feature: For sliders, you could make it so that when you press select after adding all the nodes and that ends the slider, and that could be the same for spinners or for spinners you could make it so you tap once for the start and once for the end. You could also just add a virtual right click button.

**Comment by bdach** [comment]
It is too early yet to talk about the editor on mobile, given that the core gameplay isn't even properly handled for all rulesets.

Closing for now. This will be revisited at a later date and/or tracked alongside the rest of #4201.
