### ISSUE TITLE
Crash after entering the "currently playing" tab

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#10852]
**Screenshots or videos showing encountered issue:** 
https://youtu.be/gL_3urGVWlI

**osu!lazer version:** 
2020.1114.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5542552/database.log)
[network.log](https://github.com/ppy/osu/files/5542553/network.log)
[performance.log](https://github.com/ppy/osu/files/5542554/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5542555/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5542556/updater.log)

**Computer Specifications:** 
OS: windows 10
CPU: i5-4440
iGPU: intel hd graphics 4600
RAM: 8 GB

**Comment by bdach** [comment]
Seems that the API request batch limiting code failed somehow:

```
2020-11-15 14:41:47 [error]: ---> System.ArgumentException: GetUsersRequest calls only support up to 50 IDs at once
2020-11-15 14:41:47 [error]: at osu.Game.Online.API.Requests.GetUsersRequest..ctor(Int32[] userIds)
```
