### ISSUE TITLE
Song selection doesn't display enough map metadata

### ISSUE THREAD

**Issue by 20Attila03** [ppy/osu#10869]
**Describe the new feature:**

I would like to make it possible that the following features are visible on one tab in the map selector:
- Duration
- BPM
- Circle Count
- Slider Count
- Spinner Count
- Circle Size
- HP Drain
- Accuracity
- Approach Rate
- Star Difficulty
- Rating
- Ranking

**Reason behind the request:**
Those are the main thing that we look at when selecting a beatmap and it would make sense if you wouldn't have to change tabs while looking at those datas.
I personally get annoyed by the need of swapping tabs, as I like to see my rankings / friends rankings and the beatmap difficulty at the same time.

**Proposal designs of the feature:** 
Design from the current stable release:
![Screenshot 2020-11-16 135423](https://user-images.githubusercontent.com/46813521/99254822-41e5c900-2813-11eb-804b-a9b707e603f3.png)

**Comment by smoogipoo** [comment]
Not sure if it's worth keeping an issue open for this, but sure. We have a redesign in progress which has all of these and more:

![image](https://user-images.githubusercontent.com/1329837/99256508-da526c80-2858-11eb-902a-4a07780c8f75.png)

**Comment by 20Attila03** [comment]
Really great, also I would make it toggleable, so more place can be allocted to rankings. The most important informations could be placed next to the name of the map when collapsed.
Also, Circle count Slider count having a bar does not make sense. what is the maximum ammount?

It would overwelm new players, so I would hide it at first, and have the options to make it visible.
And would make a detailed informatin for newbies about what the data means, and how does this affect the gameplay.

I would reccomend keeping it as an open topic, so discussion could be done here, not with new tickets.

**Comment by peppy** [comment]
going to close this for now until implementation and designs are completed. discussion on specifics can happen after that.
