### ISSUE TITLE
Catch.Tests/TestSceneFruitObjects regression

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu#10880]
The test scene should show fruits in several skins, but doesn't show any fruits.
Bisected to <https://github.com/ppy/osu/commit/cead67d51209a1f3a1869448d15345b9d78577f5> this commit but I'm not sure how to fix the issue.

**Comment by bdach** [comment]
I'd probably override `OnApply` or subscribe to `HitObjectApplied` and then reapply the `NegativeInfinity` lifetime start there.
