### ISSUE TITLE
Some hitsounds delayed 10ms

### ISSUE THREAD

**Issue by cg505** [ppy/osu#10885]
**Describe the bug:** 
My hitsounds were feeling weird and I was getting a lot lower accuracy than on stable, To test, I played the same replay on stable and on lazer and recorded the audio output. Random hitsounds appear to be delayed by ~10ms in the lazer replay.

**Screenshots or videos showing encountered issue:** 
One example:
![image](https://user-images.githubusercontent.com/1581504/99435920-a6616080-28c5-11eb-94c6-4e456004166f.png)
[Replay used](https://i.fluffy.cc/512fqLgHhP4vL6b2FlkZkrVsxllS10P6.osr)

**osu!lazer version:** 2020.1114.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5555692/database.log)
[network.log](https://github.com/ppy/osu/files/5555693/network.log)
[performance.log](https://github.com/ppy/osu/files/5555694/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5555695/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5555696/updater.log)

**Comment by bdach** [comment]
Possibly related to this?

https://github.com/ppy/osu/blob/851c7d524fe6f3ce6b638718ec4abf454c58d2df/osu.Game/Screens/Play/GameplayClockContainer.cs#L87-L89

**Comment by cg505** [comment]
Possibly, but I'm not sure why it would only apply to _some_ hitsounds instead of all of them.

**Comment by bdach** [comment]
Are you able to tell whether the delayed hitsounds are the same sounds (as in playing from the same particular files), or just purely random? Also, is this replicable on one map, or many?

**Comment by cg505** [comment]
The sound itself does not seem to matter. I'll test other maps.

**Comment by bdach** [comment]
Also have a look at the FPS counter if you can to make sure the audio thread is not dropping frames for some reason (although that would have to be ~10 frames at a time at the typical resolution it runs at).

**Comment by cg505** [comment]
I tested on a few other maps, and with another skin, and saw the same result, arbitrary hitsounds seeing pretty consistent 10ms of delay. As for the audio fps, it stays quite consistent within 998-1002 fps.

**Comment by smoogipoo** [comment]
Do you get the same if you change to single-threaded mode?

![image](https://user-images.githubusercontent.com/1329837/99482827-2e1b9d80-29a0-11eb-88c1-717337173596.png)

Does it become more consistent? Just want to rule out any cross thread/1-frame issues.

**Comment by cg505** [comment]
I'm in the wrong OS right now, but I can try single threading mode tomorrow.

> Also I see this issue is marked with the "replay" label, but you've experienced this in gameplay too, correct?

From earlier:
> I should clarify that this is obviously really hard to test during actual gameplay, but I do believe it happens there as well (as opposed to just during replays).

**Comment by cg505** [comment]
Single thread mode does not seem to matter.

**Comment by peppy** [comment]
Are they always different hitsounds in the same play of the same beatmap? Is it completely random or always at certain points in time?

**Comment by cg505** [comment]
It seems like it's correlated, but not consistent. I recorded three times with the same map, and most (90+%) of the hitsounds are timed correctly. However, it seems like when there is a delayed hitsound in one of the recordings, it's also much more likely to see the same hitsound delayed in another. So it's very common to see 2/3 or 3/3 recordings delayed on the same hitsound, which should be improbable if it was truly random.

They also often (not always) appear to be somewhat grouped together, often ~3 delayed out of a string of 4 or 5 hitsounds.

Anyway, the more I write, the more I realize just how cursed this is. I'm sorry. I'd be glad to share my Audacity project with the recordings if you think it would be helpful.

**Comment by peppy** [comment]
It's fine. I don't have the time to go through your audacity recordings and trust you can do that part of the analysis. I also haven't tried to reproduce this yet, but intend to do so. Just trying to reduce the scope of the issue, so here's a couple more questions:

- Does rewinding back over the same section cause different results each time (using the seek bar in replay mode)?
- Can you confirm you are not using the legacy audio mode in stable?

**Comment by cg505** [comment]
> * Does rewinding back over the same section cause different results each time (using the seek bar in replay mode)?

Yes. I played through the entire replay, scrubbed back to the beginning, and played it again. The second time, the 10ms delays were not necessarily correlated with the delays the first time. I also noticed that during the first playback, hitsounds were within 1ms of stable (except for when they had the 10ms delay), but during the second playback, hitsounds were usually 5ms earlier than stable (and 5ms later when they had the 10ms delay).

Also, I noticed that scrubbing is completely broken in single-threaded mode. I assume this is known.

> * Can you confirm you are not using the legacy audio mode in stable?

Yes. ![screenshot](https://osu.ppy.sh/ss/15908477/3881)

**Comment by peppy** [comment]
The last question I have is: are you sure stable is the more correct playback here? Are you able to test in a way you can confirm the late playback is actually out of sync with expectations? Basically, it would seem you are using osu-stable as ground truth but the settings we have for audio playback match 1:1, so there is a possibility that the issue is also (randomly) happening on stable as well.

It may be beneficial to test with the [offset wizard](https://osu.ppy.sh/beatmapsets/4659#osu/24854) where you can be sure that the audible result is as expected (from the waveform alone).

**Comment by peppy** [comment]
It's been quite a while since this issue was reported so I'm going to close for now. We've made quite a few fixes to audio.

Please report back if you are able to.
