### ISSUE TITLE
change binding for in-game interface toggle.

### ISSUE THREAD

**Issue by ghost** [ppy/osu#10887]
There should be a binding setting for "toggle in-game interface" it would be gladly appreciated by me and people who's part of the keyboard dosen't work.
![osu!_cu9fdPFwiq](https://user-images.githubusercontent.com/55044319/99935785-2ece7e00-2d6a-11eb-8a9c-cd4f9a7a42e6.png)

**Comment by smoogipoo** [comment]
This is an osu-stable issue, right?

**Comment by Schip3s** [comment]
yes, it's an osu-stable issue

**Comment by smoogipoo** [comment]
This is the wrong repository. Please post an issue in https://github.com/ppy/osu-stable-issues instead.

**Comment by peppy** [comment]
also note we generally aren't adding new features to osu-stable so posting there is not recommended.

**Comment by Schip3s** [comment]
uh.. well this also isn't in lazer

**Comment by bdach** [comment]
Reopening as a lazer feature proposal.
