### ISSUE TITLE
Editor object snapping only snaps position to first object in selection

### ISSUE THREAD

**Issue by InfinityGhost** [ppy/osu#10898]
**Describe the bug:** 
Selecting a group of objects in the editor only snaps position to the first object relative to time in the selection. 

**Screenshots or videos showing encountered issue:** 
https://streamable.com/icn2j3

**osu!lazer version:** 
development build @ ecd6d096002c8e64f3a33e792f5b5b5554c48c8c

**Logs:**

[database.log](https://github.com/ppy/osu/files/5561773/database.log)
[network.log](https://github.com/ppy/osu/files/5561777/network.log)
[performance.log](https://github.com/ppy/osu/files/5561775/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5561776/runtime.log)

**Comment by peppy** [comment]
that's how snapping works (and indeed how it should)? you may be wanting quantizing support which we will add later.

unless you are hoping for it to snap based on the hovered object?

**Comment by bdach** [comment]
I think the expectation here is for snapping to work for all possible anchor points within the selection (so any of the three circles should be able to snap to the slider head).

**Comment by peppy** [comment]
so we're taking about positional snapping, not time? that isn't mentioned anywhere.

**Comment by InfinityGhost** [comment]
I should have clarified that it was positional snapping I was referring to.

**Comment by peppy** [comment]
So you expect it to positionally snap based on the hovered object, correct?

**Comment by InfinityGhost** [comment]
I expect it to snap to any of the objects that are selected as for feature parity with stable's editor.
https://streamable.com/2aqyat
