### ISSUE TITLE
Artifacts in hit objects when scrolling backwards in the editor

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#10895]
**Describe the bug:** 
When scrolling backwards in the osu! standard editor all sorts of weird stuff happens with the hit objects. All the examples I've observed are:
- Hit circles fading in too early.
- Slider repeats facing the wrong direction.
- Slider repeats appearing in the wrong location before the slider appears.
- Sliders without any sliderhead. (only saw this one in local debug version)
- Ghost version of every slider. (if you skipped forwards in the timeline)

It's recreatable by going into the editor with any map, scrolling or skipping forwards a bit, and then slowly scrolling backwards in time.
Might be related to #10893 .

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/17460441/99557562-1f92ad80-29c3-11eb-8903-d1b1ab7bd17a.png)
![image](https://user-images.githubusercontent.com/17460441/99557602-291c1580-29c3-11eb-9bae-57703f117d82.png)
![image](https://user-images.githubusercontent.com/17460441/99557618-2de0c980-29c3-11eb-87f8-1484dd0904cf.png)
![image](https://user-images.githubusercontent.com/17460441/99557640-333e1400-29c3-11eb-9e09-3234b5f4aad6.png)
![image](https://user-images.githubusercontent.com/17460441/99557656-3802c800-29c3-11eb-8146-43ee4a2ba0ee.png)
![image](https://user-images.githubusercontent.com/17460441/99557864-6da7b100-29c3-11eb-8694-e89ab71f2bab.png)

**osu!lazer version:** 
2020.1114.0

**Logs:**

**Comment by bdach** [comment]
I think this'll be similar to [issues I spotted yesterday](https://github.com/ppy/osu/pull/10884#issuecomment-729096234). Let's just track them under this issue I guess.

**Comment by peppy** [comment]
basically https://github.com/ppy/osu/issues/10893 but i guess we can leave this to track the editor version?

**Comment by bdach** [comment]
Might honestly be, I haven't checked whether the two have the same root cause(s).

**Comment by smoogipoo** [comment]
There's a bunch of issues and it's difficult to explain. I'll just post my standup notes:
```
> Several issues:
> 1. Sliders don't have HitWindows so their Result.TimeOffset isn't automatically clamped.
> 2. Expire() is still weird because it max()'s with the clock's current time (which, if we're in the future, will take precedence even though we're applying transforms way in the past).
> 3. Editor's pool also calling Expire() which goes back into (2).
> 4. A lot of smaller issues like `DrawableSliderTick` not calling `base.UpdateInitialTransforms()`.
```
This is on my list of tasks to fix.
