### ISSUE TITLE
Maps fail to import after being deleted.

### ISSUE THREAD

**Issue by nitsuga5124** [ppy/osu#10901]
**Describe the bug:** 

When a map is deleted and then redownloaded, if the map has an update, then the map fails to import due to a database error.

**Screenshots or videos showing encountered issue:** 

[Screenshot of the error happening](https://imgur.com/pCJWiey)

**osu!lazer version:** 

commit `e7c0cf093bf1ec9f83ce0507af1b58c929556276`
Though, it has happened for over a year now.
The game is compiled from source on Arch Linux using the following command:
`dotnet publish osu.Desktop --framework netcoreapp3.1 --configuration Release --runtime linux-x64 --self-contained false --output ~/.local/lib/osu-lazer`

**Logs:**

Zip contains the logs folder; errors are located on the database logs.
[logs.zip](https://github.com/ppy/osu/files/5565238/logs.zip)

**Comment by bdach** [comment]
See #10737, #9966, #9319. Closing for now as duplicate.

**Comment by nitsuga5124** [comment]
I do not think this is duplicate, as those 3 issues talk about crashing or black screens, but in this case, there's no crash, and the game keeps working fine after restarting; this is not a database corruption either.

**Comment by bdach** [comment]
Logs show the a similar foreign key constraint error, and the first linked issue does mention a failed import after deletion. You can upload `client.db` if you want to be extra sure but I'm 99% sure this'll be the same issue (and as stated in one of the issues, the database system is in a bit of a limbo as we're possibly going to be migrating away from sqlite entirely).
