### ISSUE TITLE
osu!lazer never worked for me and still ...

### ISSUE THREAD

**Issue by Janaijanai** [ppy/osu#10902]
when i download lazer it doesnt open to install or anything, after i click on it to open the downloaded file, a black window appears for like 2 seconds then "osu! has stopped working" window pop up ( but in the 2nd try and so on, when i try to open it no black screen anymore i just got the message in the screenshot
![Capture](https://user-images.githubusercontent.com/74438696/99637646-121a0980-2a3d-11eb-952e-bc61172f5f01.PNG)

rest of problem details shown in the window
 Exception Code:	c0000005
  Exception Offset:	0000000000191d5b
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1036
  Additional Information 1:	f425
  Additional Information 2:	f425748a82fa3ff1bfb6279a2851b08f
  Additional Information 3:	2e12
  Additional Information 4:	2e122e6222bf717ffdb653de607b1ae9

**osu!lazer version: apparently the last one 2020.1114.0

**Logs: since the game didn't install maybe thats why i cant access logs they aren't there in the folder

Computer Specifications: he is a[ link](https://support.hp.com/id-en/document/c01538039) showing all specs since i dunno what should i include here

**Comment by smoogipoo** [comment]
Windows 7 is not supported my Microsoft anymore. They [specify](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md) that you'll need [Extended Security Updates](https://docs.microsoft.com/en-gb/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq) which is a paid-for add-on. I don't know if this will fix your issue, but I would just advise you upgrade off Windows 7 instead.

**Comment by enoslayd** [comment]
If you dont want to upgrade, I would suggest that you update windows 7 and install all of its security updates (and maybe include the optional updates) as i was able to run lazer on windows 7 before
