### ISSUE TITLE
BASS faulted with error code -1: Unknown. 

### ISSUE THREAD

**Issue by puar1** [ppy/osu#10908]
Build loaded with no audio and a notification saying "BASS faulted with error code -1: Unknown."

https://i.imgur.com/sW0Ncpx.png

osu!lazer 2020.1114.0

[osulogs1.zip](https://github.com/ppy/osu/files/5568953/osulogs1.zip)

(Processor:AMD Ryzen 5 1600 Six-Core Processor  3.20 GHz  on Windows 10 Home Version 1909

**Comment by bdach** [comment]
This error alone is not enough to even begin putting hypotheses as to what might be going wrong. Please describe your audio devices and setup (what sort of audio card? input/output device? atypical setup?).

**Comment by puar1** [comment]
I just restarted my computer and it fixed itself sorry, it was probably something with my audio devices sorry
