### ISSUE TITLE
Sliderball gets brighter the farther it goes

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10910]
Sliderball becomes fully white when ~20-30% of the slider has been passed. This happens both in editor and during gameplay. Unsure if this is intended behaviour.

video: https://youtu.be/jex9f0-HC3w
osu!lazer version: 2020.1114.0

![](https://i.imgur.com/GVYz6Rg.png) ![](https://i.imgur.com/FcFBgmq.png)

**Comment by bdach** [comment]
I can't seem to be able to reproduce this. Would you be able to attach a screenshot or video with this happening, and also the draw visualiser's transform view open? (press <kbd>Ctrl</kbd>+<kbd>F1</kbd>, click `choose target`, then highlight and click the sliderball, and then double-click the `Box` underneath it, press `toggle inspector` and open the `Transforms` tab). This is what it should roughly look like:

![2020-11-19-205548_1137x627_scrot](https://user-images.githubusercontent.com/20418176/99717502-c3ef1f80-2aa9-11eb-88e0-aa1046871f59.png)

Either that or more info on how to repeat this would be appreciated.

**Comment by peppy** [comment]
That video looks like it's brighter than it should actually be (almost as if there's more than one ball there)

**Comment by RaiLTC** [comment]
I managed to reproduce this by scrolling back and forth at the start of the slider (until it becomes a white circle)
![osu!_Pi5MPq7EGh](https://user-images.githubusercontent.com/35473621/99826730-6f0ee000-2b61-11eb-93c6-35b2495eec73.png)

**Comment by bdach** [comment]
@RaiLTC I can't say that I can see the issue described in the original post on your video.

**Comment by RaiLTC** [comment]
I seemed to have misunderstood then. What is the intended behavior?

**Comment by bdach** [comment]
I was expecting to see full white as in the OP. I've compared frames at the start of your video and at the end and to my eye there is no difference in slider ball opacity on it.

**Comment by RaiLTC** [comment]
Ah. So getting brighter is the intended behavior. I'll try to reproduce that

**Comment by RaiLTC** [comment]
Haven't managed to reproduce so far. However I got similar results on yellow / blue backgrounds with blue colored sliders where the sliderball is completely white, it wasn't the case when I was moving the sliders around to see if the background behind is visible, which is was. If you manage to reproduce this, can you try the same on similar colored backgrounds and yellow backgrounds? Good example is Something Good '08 (Radio Edit) mapset by xDololow

**Comment by Pennek** [comment]
I am unable to open the draw visualizer for now as `Ctrl` + `F1` does nothing for me. Will try to reproduce again whenever I can

**Comment by peppy** [comment]
As a temporary measure, you can run with `--sdl` to get around this bug.

**Comment by smoogipoo** [comment]
This looks correct. There is a fade from 0-1 at the higher level (over 300ms), and another from 0-0.6 at the lowest level (over 200ms). So at its brightest it's 0.6 alpha additively blended over a pretty light background.

For comparison, here's how it'd look with normal blending:
![image](https://user-images.githubusercontent.com/1329837/100342151-ebea0000-3020-11eb-81cd-45c4c1f2defe.png)

**Comment by peppy** [comment]
I'm not sure we actually want it to get brighter over time.. may consider removing this?

Also looking at the opening post, it's somehow higher than `0.6f` in the right-hand screenshot, but seemingly no one has been able to reproduce this?

**Comment by smoogipoo** [comment]
![image](https://user-images.githubusercontent.com/1329837/100366001-9b37ce80-3043-11eb-9a31-8dbd6088c7d8.png)

![image](https://user-images.githubusercontent.com/1329837/100366040-abe84480-3043-11eb-8a1e-30a4622648bc.png)

Same slider, same map, just different combo colour. It's just the lightness of the colours that pushes it close to looking like it's brighter when additive blending is applied.

**Comment by peppy** [comment]
I think we want to reduce the additive effect then (it's not supposed to hit white like that)
