### ISSUE TITLE
AllowSliderBallTint isn't applied

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#10913]
Noticed this while trying to reproduce 10910 myself.

**Describe the bug:** 
When user has set ``AllowSliderBallTint: 1`` in their ``skin.ini``, the slider ball is supposed to be tinted the color of the combo.

**Screenshots or videos showing encountered issue:** 
Current release:
![osu_2020-11-19_23-36-40](https://user-images.githubusercontent.com/11320483/99727064-19cec200-2ac0-11eb-99ab-63557bbfe40c.png)

2020.1031.0:
![osu_2020-11-19_23-39-49](https://user-images.githubusercontent.com/11320483/99727384-8d70cf00-2ac0-11eb-90fd-77c67f646873.png)

**osu!lazer version:** 
2020.1114.0

**Comment by bdach** [comment]
#10863
