### ISSUE TITLE
The game crashes if you edit any CTB map

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#10912]
**Screenshots or videos showing encountered issue:** 
https://youtu.be/Upr3aluv_1E

**osu!lazer version:** 
commit 7f3c8ad744df80079bc377b63c570ca6243426f9

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5569571/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5569572/updater.log)
[database.log](https://github.com/ppy/osu/files/5569573/database.log)
[network.log](https://github.com/ppy/osu/files/5569574/network.log)
[performance.log](https://github.com/ppy/osu/files/5569575/performance.log)

**Comment by bdach** [comment]
catch editor work has not started at all yet, so this is mostly expected. i guess we could make it not-crash for now, though.

**Comment by mouzedrift** [comment]
i'm pretty sure that there was a placeholder for unimplemented editors and it didn't crash before so i'm kinda surprised that it does now
