### ISSUE TITLE
Transformed sliders stay faded out after rewind

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10939]
If a slider is transformed after fading out it will stay invisible after rewinding. Occasionally, modifying a control point after pausing will also crash the game yielding the following [logs](https://github.com/ppy/osu/files/5578616/runtime.log).

**video:** https://youtu.be/_EAaENpiZYs
**osu!lazer version:** 2020.1121.0

**Comment by peppy** [comment]
I can't reproduce any more with https://github.com/ppy/osu-framework/pull/4017 applied, so potentially fixed.

**Comment by bdach** [comment]
I still seem to be able to, for what it's worth. I'll take a look at possible causes if I get the chance within the next few hours.
