### ISSUE TITLE
Add support for legacy skinning of the key overlay

### ISSUE THREAD

**Issue by ghost** [ppy/osu#10944]
Request to add key overlay support 
![image](https://user-images.githubusercontent.com/55044319/99939071-eb780d80-2d71-11eb-9b2b-809ad627cded.png)

**Comment by peppy** [comment]
What is this even asking for? This is already implemented. If you're asking to have this enabled during non-replays, you can do that via the settings.

**Comment by Schip3s** [comment]
i cannot see this:
![osu!_UoqIfKpCLJ](https://user-images.githubusercontent.com/55044319/99939533-f2535000-2d72-11eb-933e-cf05cca4c4aa.png)

**Comment by Joehuu** [comment]
Added in https://github.com/ppy/osu/pull/29027.
