### ISSUE TITLE
Random lag spike after merging master branch of 2020.1121.0

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#10940]
**Describe the bug:** 
Random lag spike after I merged master branch of 2020.1121.0.
I'm running a custom build but I'm quite sure it's not my problem

**Screenshots or videos showing encountered issue:** 
The FPS graph looks like this when lagging:
![图片](https://user-images.githubusercontent.com/50285552/99896153-c9768080-2cc8-11eb-9407-3e9b4631ba37.png)
Video: https://www.youtube.com/watch?v=KT014Y3k-EY
Lagged at the beginning of the video, 0:32, 1:06
**osu!lazer version:** 
https://github.com/PercyDan54/osu/tree/custom
**Logs:**
[performance.log](https://github.com/ppy/osu/files/5579031/performance.log)
(Only sending performance because it spams something about texture)

**Comment by peppy** [comment]
I'm sorry but we cannot support forks. Please reproduce on master or the latest official release.

**Comment by PercyDan54** [comment]
> 
> 
> I'm sorry but we cannot support forks. Please reproduce on master or the latest official release.

Checked out master and reproduced:
https://www.youtube.com/watch?v=-zyEzyvvVBc
0:36 , 1:06, 2:11

**Comment by peppy** [comment]
Thanks. A next step would be bisecting backwards to see if you can figure which commit or PR it started on.

And before even doing this, try a previous release and make sure it is definitely a regression, and not something on your end.

**Comment by PercyDan54** [comment]
> 
> 
> Thanks. A next step would be bisecting backwards to see if you can figure which commit or PR it started on.
> 
> And before even doing this, try a previous release and make sure it is definitely a regression, and not something on your end.

This is awkward.
It's not the problem of this update. I reset master branch to 2020.1114.0 and also got lags

**Comment by smoogipoo** [comment]
Just going to say before you point out that you're experiencing lag spikes in another version - you should not be doing performance testing in debug, and especially not with the debugger attached as VS does by default. There's many differences between debug and release builds - handling of cancellation tokens/async state machines, logging, assertions, etc, which have clost-to-0 cost in release builds.
