### ISSUE TITLE
osu! lazer on android can't connect to the internet

### ISSUE THREAD

**Issue by LucyFurrMorningstsr** [ppy/osu#10946]
I'm using the latest release (2020.1121.0)

My Wi-Fi runs on ipv4, I checked any app that could potentially block internet access but there seems to be nothing, I tried changing my DNS as well, tried reinstalling and no go.
The only response I'm able to get is from "check updates", other than that everything just keeps loading

[network.log](https://github.com/ppy/osu/files/5583763/network.log)

**Comment by bdach** [comment]
This might be due to #3507, but then again there is essentially nothing to go on here - you'll have to investigate this on your side. Closing for now - if you find out more about why this might be happening please comment and we'll decide whether to reopen.

**Comment by LucyFurrMorningstsr** [comment]
I still couldn't find the source of the problem after hours, most likely due to my connection. A VPN seems to have fixed it, probably the only way to solve it as of now
