### ISSUE TITLE
Individual SV for osu!mania notes

### ISSUE THREAD

**Issue by TsavyPrince** [ppy/osu#10947]
**Describe the new feature:** 
Allow mappers to give individual notes SV instead of the whole playfield in osu!mania, allowing for different notes to scroll at different speeds at the same time.
**Proposal designs of the feature:** 
Idk.

**Comment by peppy** [comment]
This has already been given some thought (see https://github.com/ppy/osu/pull/10416 / https://github.com/ppy/osu/pull/10417) and will come at a later point in time.

**Comment by peppy** [comment]
Closing as duplicate of https://github.com/ppy/osu/issues/7882
