### ISSUE TITLE
Raw input for mac users

### ISSUE THREAD

**Issue by strikingacorn** [ppy/osu#10957]
it would be nice if you could add the raw input setting for mac users. i've be told that linux already has the feature so please add it for mac as well.

**Comment by bdach** [comment]
That's wrong. The only platform that currently has raw input is windows.

The toggle will return to all platforms when it's ready. It was removed exactly due to lots of reports of it not working properly everywhere except windows (and it's not perfect on windows, either).

**Comment by strikingacorn** [comment]
Do you know when it’s going to come back?

**Comment by bdach** [comment]
No. We don't do deadlines. It'll be back when it's ready.
