### ISSUE TITLE
Clicking the pause button does not prompt you to click orange cursor to resume

### ISSUE THREAD

**Issue by chipscaped** [ppy/osu#10965]
**Describe the bug:** 
Clicking the pause button in the bottom left does not prompt you to click orange cursor to resume unlike pressing escape and this let's you move cursor where ever you would like before unpausing.
**Screenshots or videos showing encountered issue:** 
Here is a video of the issue
https://youtu.be/I3_EbDlxIxw
**osu!lazer version:** 
2020.1121.0

**Comment by peppy** [comment]
This is intended by design. The orange cursor is there to ensure you are at the same location on screen as previously, but in the case you reached for the pause button there's no need to do so.
