### ISSUE TITLE
Hit objects are white when placed on timeline

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10978]
Hit objects are white when first placed on the timeline (or `Ctrl` + `Z` is used) regardless of the current combo colour. This is corrected when sprites are redrawn

**video:** https://youtu.be/2wY_vt-HMrw
**osu!lazer version:** 2020.1121.0

**Comment by peppy** [comment]
This should probably be fixed on master (via https://github.com/ppy/osu/pull/10971), can you test?

**Comment by Pennek** [comment]
has been fixed on master
