### ISSUE TITLE
Beatmap set Import Error

### ISSUE THREAD

**Issue by Cryotechnic** [ppy/osu#1097]
During the beatmap import from stable task, quite a few beatmaps failed to import with the following error:

Error: ERROR: Could not import beatmap set

Error: System.NullReferenceException: Object reference not set to an instance of an object.     at osu.Game.Beatmaps.Formats.OsuLegacyDecoder.ParseFile(Stream Reader stream, Beatmap beatmap)      at osu.Game.Beatmaps.Formats.OsuLegacyDecoder.ParseFile(StreamReader stream)     at osu.Game.Beatmaps.Formats.OsuLegacyDecoder.ParseFile(StreamReader stream)     at osu.Game.Beatmaps.Formats.OsuLegacyDecoder.Decode(StreamReader stream)     at osu.Game.Beatmaps.BeatmapManager.importToStorage(ArchiveReader reader)     at osu.Game.Beatmaps.BeatmapManager.<>c__DisplayClass27_0.<Import>b__0()     at SQLite.Net.SQLiteConnection.RunInTransaction(Action action)     at osu.Game.Beatmaps.BeatmapManager.Import(ArchiveReader archiveReader)     at osu.Game.Beatmaps.BeatmapManager.Import(String[] paths)

Out of the 175 imported beatmaps, 18 failed. I have not yet tried to reproduce this issue. I am also unable to determine which ones, out of the 175 are missing. 

Could it possibly be an error somewhere along the Importer code? Let me know what I can do to resolve this issue.

**Comment by peppy** [comment]
Right now issues like this are not useful. If you are willing to debug the code then that is productive, but just providing errors is not. We are aware there are a lot of maps which don't successfully import.
