### ISSUE TITLE
Button 1 not registering on sliders and circles

### ISSUE THREAD

**Issue by WillMexe** [ppy/osu#10989]
Button one in std in my case z is not acting as pressed when playing. It is working fine when in the menu so i think its a bug with standard haven't tested the other gamemodes.

(sorry for the bad filming i hope its good enough)
https://youtu.be/TwjPINpvz1Y

version 2020.1031.0

[database.log](https://github.com/ppy/osu/files/5609303/database.log)
[network.log](https://github.com/ppy/osu/files/5609304/network.log)
[performance.log](https://github.com/ppy/osu/files/5609305/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5609306/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5609307/updater.log)

**Comment by CSharpProgramming** [comment]
Looks like you're dragging, did you disable mouse buttons? (F10)

**Comment by bdach** [comment]
Can't reproduce this. @WillMexe:

- What keyboard layout are you using? Is the <kbd>Z</kbd> key the leftmost key in the third row on your layout? (can't discern from the quick glimpse on the video)
- Are the inputs showing on the key counter overlay on the lower right? (enable in settings if not visible)

**Comment by WillMexe** [comment]
It is the Third most left key after shift and a button for arrows and I'm using a Swedish layout

**Comment by Morilli** [comment]
I assume the display is incorrect, aka it's showing z but that is referring to another key (for example y). I remember I had this issue too in some way, and you just need to change the assigned key to the one you actually press.

**Comment by peppy** [comment]
Have you tried re-binding the key? If that still doesn't work, could you try running with `--sdl` specified in your shortcut's arguemnts?

**Comment by WillMexe** [comment]
Sorry for the late reply. I had disabled mouse buttons when this was recorded although today or yesterday the bug doesn't seem to appear. Nothing about my install has changed to my knowledge. I will send again if this bug reappears but as for now since i can't reproduce it anymore i will just blame my hardware.
