### ISSUE TITLE
Anchor points are unmanageable with small circles

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10991]
Shown on [this map](https://osu.ppy.sh/beatmapsets/914372) which uses CS9. Best seen on sliders like 02:33:233 - 02:35:516 - 
Scaling anchor point size with circle size might be a way forward.

**osu!lazer version:** 2020.1121.0

![xVBfqiL](https://user-images.githubusercontent.com/20502902/100488650-bbcd5a80-310f-11eb-893b-23f59971c5e8.png) 
![ZsIfz4M](https://user-images.githubusercontent.com/20502902/100488829-c63c2400-3110-11eb-97b0-9b1cdeb42896.png)

**Comment by bdach** [comment]
Not 100% sure scaling down is a good idea either, as it makes the anchor points harder to hit, but I guess it's an easy-ish immediate solution.
