### ISSUE TITLE
Audio controller without exit to root menu

### ISSUE THREAD

**Issue by 4llower** [ppy/osu#10998]
![image](https://user-images.githubusercontent.com/56319745/100547708-3cf43100-3279-11eb-98ec-796498a4fc04.png)
This controller located only in root menu and when you need to switch to other application you need to perform a many actions so that the music from the osu does not interfere with doing other things

I propose to make this controller available in the carts selection menu

**Comment by LittleEndu** [comment]
This repo isn't for osu-stable issues, and I fail to see this as even an issue. 

In lazer, the now playing overlay is already available everywhere.
