### ISSUE TITLE
Could not load ruleset from directory on android

### ISSUE THREAD

**Issue by F2GH** [ppy/osu#10995]
It doesn't allow me to do anything like logging in or downloading beatmaps.

![Screenshot_2020-11-29-02-43-35-260](https://user-images.githubusercontent.com/75180498/100523764-d70e9780-31ed-11eb-8a62-4a17cf67de40.png)

2020.1128.0(version of osu lazer)

I don't know how to resolve this problem on my phone as I can't do things like Appdata.
It's also my first time downloading osu!lazer on my phone so I am kind of inexperienced.
And I know this is the same as #6507 but I still couldn't understand how to resolve this problem.

**Comment by bdach** [comment]
* There is nothing you can do to resolve this.
* Please don't open duplicates.
* Not being able to log in or download beatmaps are not related to the ruleset loading error.
