### ISSUE TITLE
Keyboard language bug in chats

### ISSUE THREAD

**Issue by ItIsApachee** [ppy/osu#10994]
osu!lazer have some issue with keyboard languages in chats. I encountered 2 bugs:
1. Switching languages using Win+Space bugs out keyboard, so that you can't type anything in chat. Moreover, it also bugs out Escape key, so you just can't use it, unless you refocus osu!lazer window (Alt+Tab seems to fix the issue)
2. When language selected is Russian, keymapping is broken. For example, typing 'а' would result in 'à', 'й' - 'é', and so on.

Here you can see what it types, when I'm using Russian keyboard layout.
![screenshot](https://user-images.githubusercontent.com/22821748/100521501-271d3800-31b5-11eb-96ee-05da266425a5.png)

osu!lazer version: 2020.1128.0

[performance.log](https://github.com/ppy/osu/files/5610950/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5610951/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5610952/updater.log)
[database.log](https://github.com/ppy/osu/files/5610953/database.log)
[network.log](https://github.com/ppy/osu/files/5610956/network.log)

**Comment by LittleEndu** [comment]
IMEs and non-english keyboards are known to be broken. Many issues are opened, most listed in #3326

**Comment by bdach** [comment]
As above (ctrl+space is also known to be broken) - closing.
