### ISSUE TITLE
Multiplayer room name has no character limit

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#11000]
Pressing `Create` with too many characters will sometimes yield an error and [load the lobby infinitely](https://i.imgur.com/735YaYb.png). Other times a lobby will be created but the room name [will not fit the UI](https://i.imgur.com/EHtAJ2R.png)

**osu!lazer version:** 2020.1128.0

**Comment by Joehuu** [comment]
The UI problem is tracked in https://github.com/ppy/osu-framework/issues/2982.

**Comment by smoogipoo** [comment]
@nanaya / @notbakaneko what's the length limit of a timeshift room name?

**Comment by nanaya** [comment]
100... I think.
