### ISSUE TITLE
osu! Editor not snapping to Timeline ticks after Timing Point has Changed

### ISSUE THREAD

**Issue by Eeveelution** [ppy/osu#11018]
**Describe the bug:** 
When setting timing for the first time in a Map and going back to the Compose tab, When trying to scroll in the Timeline you'd expect the Cursor to Snap to the Individual Timeline ticks, but in this case It doesn't.

Steps to recreate (hopefully):
1. Start mapping a new Song
2. Create a new Timing Point
3. Set it to some BPM
3. Go to Compose Tab and Scroll for a bit
4. Try Scrolling a bit
5. Change the BPM of the Timing Point to something lower/higher
6. Go Back and Try Scrolling, It won't snap to Timeline ticks anymore after 

**Screenshots or videos showing encountered issue:** 
https://streamable.com/o31u9t

**osu!lazer version:** 
2020.1128.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/5617455/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5617456/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5617458/updater.log)
[database.log](https://github.com/ppy/osu/files/5617459/database.log)
[network.log](https://github.com/ppy/osu/files/5617460/network.log)

I hope my recreation steps arent too rough and actually work. I hope i can help with this somewhat.
Ill be happy to help incase any more information is needed!

**Comment by bdach** [comment]
I can't seem to be able to reproduce this, or at least not reliably. The timeline ticks did update for me here, although a scroll was required for the update to take place

**Comment by Eeveelution** [comment]
for me it just didnt update at all, ill see if i can recreate it again

**Comment by Eeveelution** [comment]
i think i got it,

You have to have a timing point,
go to the compose tab then playback the music and pause so the timeline cursor is outside of the timeline ticks
then change the timing points bpm, and the scrolling will be off beat

though ive noticed that scrolling far enough makes this reset completly. not sure why the bug was so persistant in the video ive linked

**Comment by bdach** [comment]
Right, that makes it easier to reproduce, yes. Being able to pause that far in the future after the track is done is actually yet another bug (#8134) which exacerbates this.
