### ISSUE TITLE
osu!catch hit objects should be visually confined to the playfield area

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu#11012]
**Describe the bug:** 

When the window is vertically long, the top edge of the catch playfield doesn't align with the top edge of the window. In this situation, the hit objects will be visible right from the start of the lifetime of the hit object. Normally there is a short time after the start of the lifetime when only a fraction of the hit object is visible.

![image](https://user-images.githubusercontent.com/32995012/100606420-bf99f080-334c-11eb-8be1-41ef8d07bcf6.png)

Because more visibility means more time to react to a hit object, a vertically long screen will have a slight competitive advantage. I don't think this is intended.

Either hit object drawing should be masked or a big black rectangle should be placed on the top of the playfield.

**Comment by peppy** [comment]
The original method of avoiding this (also used in taiko on stable, i believe) is to have the objects fade in so close to the edge of the playfield that the advantage of extending is negligible. May visually look better than masking as well, so something to consider.

**Comment by ekrctb** [comment]
When a hit object with nested hit objects is loaded, all child hit objects become alive for one frame but immediately become dead due to scrolling position calculation. It makes the entire nested hit objects to appear for one frame and then disappears.
With #11113, the nested hit object positions in this one frame appear in the correct position, but it is still an issue for a vertically-long screen.

**Comment by frenzibyte** [comment]
This has long been resolved in https://github.com/ppy/osu/pull/27162
