### ISSUE TITLE
Error when auto exiting for update while being inside the editor screen

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#11016]
**Describe the crash:** 
i tried to get the logs but the game already overwrote them during the update restart. dunno if there is a better way to test this since it requires an old version of osu!lazer to reproduce it

**osu!lazer version:** 
2020.1128.0

**Comment by bdach** [comment]
Can't say much without the logs. We should really have better test coverage of the update process...

**Comment by peppy** [comment]
You can easily test this by removing the squirrel update folder for the latest version and pointing your shortcut at the previous one. Squirrel will always keep the last version on disk so you should still have it.

**Comment by peppy** [comment]
Going to close this one for now. Nothing to work with here.
