### ISSUE TITLE
Sliders not showing up in Editor when Slider is changed while not fully visible in Playfield

### ISSUE THREAD

**Issue by Eeveelution** [ppy/osu#11020]
**Describe the bug:** 
When you Edit a Slider in the Editor after It faded out (Change the anchor position, add/remove anchors) and scrolling back to the Sliders position, The Slider just disappears

Steps to Recreate:
1. Place a Slider and Select it,
2. Scroll the timeline forward enough so that the slider is no longer visible
3. Change and of the Anchors on the slider
4. Scroll Back
5. Slider will have disappeared, to get the slider to render again you have to scroll far back/forwards in the timeline and go back to the Point in time where the slider is

**Screenshots or videos showing encountered issue:** 
https://streamable.com/gj275s

**osu!lazer version:** 
2020.1128.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/5617729/network.log)
[performance.log](https://github.com/ppy/osu/files/5617730/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5617731/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5617732/updater.log)
[database.log](https://github.com/ppy/osu/files/5617733/database.log)

**Comment by bdach** [comment]
See #10939. Will be fixed in next release.

**Comment by Eeveelution** [comment]
aa sorry
