### ISSUE TITLE
Sliderends fade out much later than other parts of sliders

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#11022]
Sliderends fade out much later than other parts of sliders in the Editor. Checking by eye, they fade out almost two whole beats later. This makes the editor look clustered when sliders are used in rapid succession. Especially noticeable when approach rate is lower.

Example: [Four sliderends ](https://i.imgur.com/TgC5mXO.jpeg) which have been hit are shown alongside the [following elements](https://i.imgur.com/Whhk91m.jpg).

**osu!lazer version:** 2020.1128.0

**Comment by smoogipoo** [comment]
I agree it's pretty jarring, but it was done this way to increase their visibility:

![image](https://user-images.githubusercontent.com/1329837/100678483-9f038200-33b0-11eb-9158-1122531601c8.png)

**Comment by peppy** [comment]
Not sure if this is the same issue, but with legacy skins the end circles just fade away, while in stable i'm pretty sure they explode. Has always caught me off-guard.

**Comment by peppy** [comment]
@Pennek this is also the case on the stable editor (as @smoogipoo mentioned, to increase visibility for snapping to previous objects which are no longer visible temporally). Are you proposing that this is removed to improve visibility? Do you see the current implementation as being somehow more visibility impeding than what is present on stable?

**Comment by Pennek** [comment]
> Do you see the current implementation as being somehow more visibility impeding than what is present on stable?

Short answer; yes

On stable the whole slider is [faded out at once](https://i.imgur.com/eSYU83X.png) which means that both the head, body and tail of the slider is fully visible up until the point that the slider is gone. With the current lazer implementation it is impossible to tell where the sliderbody is once it has snaked. [This for example](https://i.imgur.com/eux17CI.png), could be a multitude of different things whereas [on stable](https://i.imgur.com/MC9C5z4.png) there is no confusion due to the path being visible. This becomes even more apparent with [hit animations off](https://i.imgur.com/CNeBawH.png).

Thinking it over again, I don't think sliderend visibility is actually a problem. It's more that sliderbodies aren't shown alongside them, which also confused me.

**Comment by peppy** [comment]
This can already be toggled (slider snaking in settings), but maybe we need a better display in the case it is disabled, because I can agree the above is indeed confusing.

**Comment by peppy** [comment]
This looks to have since regressed in behaviour (the ends are no longer being delayed). Maybe it's fine to remain this way, but we should investigate why it failed and remove the code which was performing this override if it's deemed as something we don't want.
