### ISSUE TITLE
Color vs. Colour; Code Uniformity

### ISSUE THREAD

**Issue by TheShadowEevee** [ppy/osu#11026]
While browsing through the code investigating a separate issue, I noticed the lack of uniformity between "Color" and "Colour".
I have locally renamed all the variables, and ran all the tests along with playing a few maps to ensure that it all works, however one issue stands.

Which to choose?

`"Color":` Shorter to type, all external libraries spell it "Color" anyway.
`"Colour":` While this would create an issue where external libraries use "Color", a majority of existing code is written as "Colour".
`Neither:` Leave it as it is; this would cause less uniformity but it also means there is less trouble enforcing one or the other.

There is also the issue of OsuTK and `OSU.Framework.Graphics` using the variable "Colour4" (or "Color4" depending) after the rename, so a decision will be needed on what to call that variable going forward. For now it's called fColour4 for "Framework" Colour4
I have code ready to go for pull requests to both the osu and osu-framework repositories if a decision is made. 
My personal suggestion is to use "Color" for uniformity with external libraries like SDL and OsuTK, but I'm also from the US where that is the common spelling anyway so take that with a grain of salt.

**Comment by smoogipoo** [comment]
We use British spellings, so "Colour" is correct. `Colour4` was not really supposed to be a thing until osuTK is removed, but it is interchangeable with `Color4`.

I don't think this issue needs to remain open.
