### ISSUE TITLE
Object size doesn't include full 0-10 range

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#11049]
**osu!lazer version:** 2020.1128.0

**Comment by Joehuu** [comment]
Change should be relatively easy, if you or anyone else wants to take credit.

https://github.com/ppy/osu/blob/f214cc6fb31b89a0a1083098a1f0edf69f85e483/osu.Game/Screens/Edit/Setup/DifficultySection.cs#L33-L44

**Comment by Pennek** [comment]
Sure, I can probably do this
