### ISSUE TITLE
Pressing home button do not hide panels

### ISSUE THREAD

**Issue by Muchaszewski** [ppy/osu#1105]
This is more of a suggestion, but it would be more intuitive that way.

All panels should hide when pressing the home button in any state in addition to hiding windows. For the best experience, it should work like Escape button.

- Social browser,
- Chat
- Current song played
- Osu!Direct panel
- Settings (optional, or with triple step Settings->Panel->Mode)

**Comment by Zethnix** [comment]
Was just going to request this, very unintuitive when the home button doesn't work elsewhere than in the song selection.

**Comment by MrTheMake** [comment]
Can be closed as well
