### ISSUE TITLE
osu!catch hitsounds are cut off

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu#11057]
Regressed by #11011

It sounds like some hit sound is stopped after very short time while playing.

**Comment by bdach** [comment]
Never mind, just checked myself, it's a separate issue. Most likely lifetimes being too stringent and not letting the hitsounds play out until the end.

**Comment by ekrctb** [comment]
Indeed this issue is fixed if the expiration is delayed for 1s (an arbitrary duration).

```diff
diff --git a/osu.Game.Rulesets.Catch/Objects/Drawables/DrawableCatchHitObject.cs b/osu.Game.Rulesets.Catch/Objects/Drawables/DrawableCatchHitObject.cs
index 1faa6a5b0..1e0563e00 100644
--- a/osu.Game.Rulesets.Catch/Objects/Drawables/DrawableCatchHitObject.cs
+++ b/osu.Game.Rulesets.Catch/Objects/Drawables/DrawableCatchHitObject.cs
@@ -64,6 +64,9 @@ protected override void UpdateHitStateTransforms(ArmedState state)
 
                 case ArmedState.Hit:
                     this.FadeOut();
+
+                    if (LifetimeEnd == double.MaxValue)
+                        LifetimeEnd = LatestTransformEndTime + 1000;
                     break;
             }
         }
```

However, some custom beatmap hit sound is longer than 1s.
I think the proper way to solve the issue is to either:

- don't expire until every hit sound is stopped,
- or make hit sound detached from the DHO (not sure).

Then, I'm sure this issue is present in standard too. Because a hit circle has some animation after being hit, a longer hit sound is required to cause this issue, however.

**Comment by smoogipoo** [comment]
Could this be done inside `DHO.updateState()`? Instead of the way it currently expires, make it `Math.Max()` with the sample lifetimes?
