### ISSUE TITLE
Chat Panels closing when not fully visible when pressing in a specific location

### ISSUE THREAD

**Issue by Eeveelution** [ppy/osu#11058]
**Describe the bug:** 
When the Chat Panel is smaller than the normal size and you click on it, you may be able to close it before it has a chance to appear,

**Screenshots or videos showing encountered issue:** 
https://streamable.com/wzyqli

**osu!lazer version:** 
2020.1128.0
(to be more specific, this commit on master: https://github.com/ppy/osu/commit/33b88e09cdba9e3e28f4613ca0b1ecd29d678fcf)

**Logs:**
[performance.log](https://github.com/ppy/osu/files/5630816/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5630817/runtime.log)
[database.log](https://github.com/ppy/osu/files/5630818/database.log)
(network.log didnt want to send through github wtf?)
network.log: https://eevee-sylveon.s-ul.eu/0y1LL1oR

To recreate simply open chat, open a new user tab, and on that Small Chat panel try to pinpoint a position where the cursor would open the tab and at the same time close that tab with the close button.

**Comment by bdach** [comment]
Isn't this just #10128?

**Comment by Eeveelution** [comment]
aaaaaaaaa sorry, yes. my bad for not checking
