### ISSUE TITLE
Decreased performance with autoplay on hitobject-heavy beatmaps (ie. centipede)

### ISSUE THREAD

**Issue by l4kr** [ppy/osu#11061]
Hi! I've been attempting to play Osu! Lazer for months now but I always seem to have some stuttering issues. 
I've decided to test it with Centipede on Autoplay and got 2-digit FPS, extremely laggy. 
The current, classic Osu! client runs like butter under the exact same conditions with the same settings (both have the 960 FPS cap, 1440p resolution, 144Hz monitor...). 
I've noticed in task manager that when the map starts showing notes, the CPU and GPU usage goes drastically down, even less than in song selection.

PC specs: AMD Ryzen 5 1600, GTX 1070, 16GB RAM

**Screenshots or videos showing encountered issue:** 
**Song selection:**
![Screenshot_1](https://user-images.githubusercontent.com/73653844/100925607-81363a00-34e2-11eb-9edd-87cacebf57b9.png)
![osu_2020-12-02_21-01-44](https://user-images.githubusercontent.com/73653844/100925490-5a780380-34e2-11eb-953c-33feed446898.jpg)
**Gameplay:**
![Screenshot_2](https://user-images.githubusercontent.com/73653844/100925603-809da380-34e2-11eb-873a-9b7c5932300b.png)
![osu_2020-12-02_21-00-54](https://user-images.githubusercontent.com/73653844/100925508-6368d500-34e2-11eb-9580-f53db010350b.jpg)

**osu!lazer version:** 
2020.1128.0
**Logs:**
[network.log](https://github.com/ppy/osu/files/5631785/network.log)
[performance.log](https://github.com/ppy/osu/files/5631786/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5631787/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5631788/updater.log)
[database.log](https://github.com/ppy/osu/files/5631789/database.log)

**Comment by jai-x** [comment]
Performance is a constant work in progress in every release.

**Comment by bdach** [comment]
We're aware that centipede is not up to par with stable performance yet. That is actually *the* benchmark map we use - but it is in no way, shape or form representative of actual gameplay. Stutters during normal gameplay will almost certainly not be related to whatever the current issue with centipede is.

"Low CPU & GPU usage" is also not a problem in itself. What is *actually* the problem here is long update frames. The biggest and most immediate issue currently to investigate in that regard is actually autoplay *itself*. Try running with no fail - it should be significantly better. There will be dips if the drawable pool happens to run out, but with NF you should be seeing framerates to the tune of 60fps.

I guess I'll change this issue to track the autoplay performance dip if anything.

**Comment by l4kr** [comment]
Oh, alright. So I tried NF and it runs around 60 fps as you said. 
I'm still running Lazer on lower performance in general compared to classic in normal gameplay (again, same exact conditions). 
That means occasional micro stutters throughout the gameplay and a lower draw FPS. It is barely noticeable but still noticeable enough to see a difference (compared to classic)
Is this normal then?

**Comment by bdach** [comment]
Difficult to tell for sure - depends on your settings (if you're running unlimited FPS, don't - 2x or 4x should be more than fine, stable works differently to lazer). We would require more information to attempt to draw up any conclusions, such as a video with the expanded fps graph (<kbd>Ctrl</kbd>+<kbd>F11</kbd> twice from a hidden state) and the performance display (<kbd>Ctrl</kbd>+<kbd>F2</kbd>)

**Comment by peppy** [comment]
Closing this for now (we aren't ready to deal with general user performance issues). If you pinpoint to something specific with logs then we can revisit this, but apart from that know that we are doing ongoing optimisations. Also note that lower draw fps does not necessarily mean worse playability if you are running multithreaded.

@bdach if there's an issue specific to autoplay please reopen a separate issue (not aware of this myself.. thought it was just the overhead of judgement results?)
