### ISSUE TITLE
Textbox receives key presses from gameplay exit sequence

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#11075]
When using a quick retry key combination that includes a dead key (eg. alt+`), that key should not be remembered since it was pressed during gameplay. It does get remembered now which causes the modifier to show up in front of every input in a text field after a quick retry, when it's not intended.
![f9c0bc41cb5c](https://user-images.githubusercontent.com/56885706/101034762-dde53380-357a-11eb-9a29-e111f497d285.gif)
I'm fine with this being low priority since it's just a minor annoyance, but would be nice if this got fixed eventually.

**Comment by peppy** [comment]
Likely going to require a fix in textbox handling (it really shouldn't be processing any text that is the result of a key down operation when it wasn't present).

**Comment by Susko3** [comment]
Fixed by https://github.com/ppy/osu-framework/pull/4865. Since text input is disabled when no text boxes are active, dead keys are ignored.
