### ISSUE TITLE
Catcher is invisible

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#11074]
**Describe the bug:** catcher is invisible on lazer default skin but not on classic skin. visible on 2020.1114.0 (since that was the last version i have before updating to the latest

**Screenshots or videos showing encountered issue:** 
![osu_2020-12-03_21-21-46](https://user-images.githubusercontent.com/41866328/101023608-f7ec3980-35ad-11eb-9dbd-b5baa3c04f89.png)

**osu!lazer version:** 2020.1203.0

**Logs:** (doubt that this will help)
[runtime.log](https://github.com/ppy/osu/files/5636314/runtime.log)

**EDIT:** i havent tried --tk but ill do it later

**Comment by peppy** [comment]
It's visible here. Can you 100% confirm you aren't using a custom skin?

**Comment by enoslayd** [comment]
nope the screenshot uses lazer skin. also using --tk solved it. and apparently switching temporarily to tk and then start again in sdl solves it tho i encountered another problem that may be specific to older devices

**Comment by peppy** [comment]
this makes no sense.

**Comment by enoslayd** [comment]
i know im confused too but since it solved itself 🤷‍♂️
