### ISSUE TITLE
Judgements display incorrectly

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#11078]
**Describe the bug:** Hit judgements seem to display in a weird and incorrect way on my skin, which they didn't do before.
Seems to have regressed in #10890 at around 94886a09b23b2c7d850781eaa20c07b0697a2d3c.
Skin I use: https://drive.google.com/file/d/1-MY-jJgOSvi8X1_oC_xDE4uq3V79MN1C/view?usp=sharing

**Screenshots or videos showing encountered issue:** 
Correct (previously): https://streamable.com/f646fn
Incorrect (now): https://streamable.com/dmqe95

**osu!lazer version:** 
latest / 2020.1203.0

**Comment by peppy** [comment]
Your skin is being treated as the wrong version for whatever reason (it's using the newer judgement animation rather than old). Possibly due to the presence or absence of `particle` textures. No doubt stable has some silly conditionals which use old transforms when they aren't there or something.
