### ISSUE TITLE
SampleInfo hash code does not produce consistent results even with identical data

### ISSUE THREAD

**Issue by LumpBloom7** [ppy/osu#11079]
**Describe the bug:** 
Discord mention pt1: https://discordapp.com/channels/188630481301012481/188630652340404224/784041378886713384
Discord mention pt2: https://discordapp.com/channels/188630481301012481/188630652340404224/784061008187883540

In `SampleInfo`, the `GetHashCode` doesn't return a consistent hash code even if `sampleNames` contain the same strings. 

This caused a problem within Sentakki where a new `SamplePool` is being created every time a `PausableSkinnableSound` is added to a DHO, causing massive performance drops because thousands of Pools end up being created. (This doesn't happen when `PoolableSkinnableSample` is used)

<https://github.com/LumpBloom7/sentakki/blob/e8430b9345437a654f8a7924cb85ab56af840123/osu.Game.Rulesets.Sentakki/Objects/Drawables/DrawableSentakkiLanedHitObject.cs#L27>

**Screenshots or videos showing encountered issue:** 
N/A
**osu!lazer version:** 
2020.1203.0
**Logs:**
N/A

**Comment by bdach** [comment]
[I did say this could be an issue.](https://github.com/ppy/osu/pull/10905#discussion_r527226584) Fixing is easy enough, I suppose.
