### ISSUE TITLE
Hidden mod causes the game to crash due to an KeyNotFoundException 

### ISSUE THREAD

**Issue by RORIdev** [ppy/osu#11082]
**Describe the bug:**   
When playing with hidden the game crashes after ~2 seconds of playing. This issue seems to be exclusive to hidden as far as I could test. This also happens when the HitObject is a HitCircle.

**Screenshots or videos showing encountered issue:**  
https://youtu.be/M_ZA0Bw_e4Q

**osu!lazer version:**  
2020.1203.0.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/5637672/logs.zip)

**Comment by bdach** [comment]
#11015
