### ISSUE TITLE
crashing when i use hidden

### ISSUE THREAD

**Issue by thegfgtdd** [ppy/osu#11086]
**Describe the crash:** when I use hidden automatically the second it crashes the game for no apparent reason

**Screenshots or videos showing encountered issue:** i cant film the screen

**osu!lazer version:** 2020.1203.0

**Logs:**

**Computer Specifications:** amd ryzen 3 3100, rx 570 8gb, 8gb ram 2333mhz and 1tb hdd

**Comment by bdach** [comment]
#11015

please search
