### ISSUE TITLE
Game freeze after start the beatmap using hidden mod.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#11081]
**Describe the crash:** Game freeze after start the beatmap using hidden mod.

**Screenshots or videos showing encountered issue:** 
(S*it play)
(1 - HD only after start) https://streamable.com/vrh9cl
(2 - Tried NM then HD. same map.) (It may long, you can skip.) https://streamable.com/2qeknk
(3 - Tried NM then HR(for non visual impaired test) then each of visual impaired mods., then HD. same map.) (It may very long, you can skip.) https://streamable.com/r0p9pu

**osu!lazer version:** 2020.1203.0

**Logs:**
(1)
[database.log](https://github.com/ppy/osu/files/5637487/database.log),[network.log](https://github.com/ppy/osu/files/5637488/network.log),[performance.log](https://github.com/ppy/osu/files/5637489/performance.log),[runtime.log](https://github.com/ppy/osu/files/5637490/runtime.log),[updater.log](https://github.com/ppy/osu/files/5637491/updater.log)
(2)
[database.log](https://github.com/ppy/osu/files/5637595/database.log),[network.log](https://github.com/ppy/osu/files/5637596/network.log),[performance.log](https://github.com/ppy/osu/files/5637597/performance.log),[runtime.log](https://github.com/ppy/osu/files/5637598/runtime.log),[updater.log](https://github.com/ppy/osu/files/5637600/updater.log)
(3)
[database.log](https://github.com/ppy/osu/files/5637650/database.log),[network.log](https://github.com/ppy/osu/files/5637651/network.log),[performance.log](https://github.com/ppy/osu/files/5637652/performance.log),[runtime.log](https://github.com/ppy/osu/files/5637653/runtime.log),[updater.log](https://github.com/ppy/osu/files/5637654/updater.log)

**Computer Specifications:** 
CPU : Intel i5-6600k
GPU : Nvidia GTX960
RAM : 8 GB
Using HDD for beatmap directory and SSD for game directory.

**Comment by bdach** [comment]
#11015

**Comment by IkaWaAyuMu** [comment]
Closed due to duplicate.
