### ISSUE TITLE
Game crash when using Hidden mod.

### ISSUE THREAD

**Issue by 3pixl** [ppy/osu#11088]
**Describe the crash:** 
I played a beatmap with hidden mod enabled. After starting beatmap I clicked a few circles and then game crashed.
**Screenshots or videos showing encountered issue:** 
https://drive.google.com/file/d/1KoTTOiDqezBmQSmJW9WZ4lCPJOl0ukHi/view?usp=sharing
**osu!lazer version:** 
2020.1203.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/5641469/database.log)
[network.log](https://github.com/ppy/osu/files/5641470/network.log)
[performance.log](https://github.com/ppy/osu/files/5641472/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5641473/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5641474/updater.log)
**Computer Specifications:** 
Processor: AMD A10-5800K
Videocard: Zotac GeForce GT 730 4GB
RAM: HyperX Fury DDR3 8GB
The game is installed on an SSD

**Comment by smoogipoo** [comment]
https://github.com/ppy/osu/issues?q=is%3Aissue+is%3Aclosed
