### ISSUE TITLE
Game crashes suddenly

### ISSUE THREAD

**Issue by coinworld** [ppy/osu#11090]
**Describe the crash:** 
I don't know how to describe it. It crashed 3 times so far out of nowhere

**osu!lazer version:** 
2020.1203.0

**Logs:**
https://gist.github.com/coinworld/56ef9fad230280fb37bec956a338350a

**Computer Specifications:** 
Ryzen 5 2600, 16GB RAM, Ubuntu MATE 20.10, RX570

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/issues/11015

**Comment by smoogipoo** [comment]
Fixed ^^

**Comment by coinworld** [comment]
Sorry, I just found it is duplicate :(
