### ISSUE TITLE
Confine mode setting dropdown has no effect when in exclusive fullscreen

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu#11097]
**Describe the bug:** 

Whatever option I choose, the mouse cursor is always confined both in game and menu. This did not happen on yesterday's release.

**Screenshots or videos showing encountered issue:** 

Quick demo: https://wala.s-ul.eu/IczCzITf

Monitor setup:

![20201204T203432-1837237546](https://user-images.githubusercontent.com/36758269/101215475-2c2f2b00-367e-11eb-813e-b9dd33774cdf.png)

**osu!lazer version:** 
Latest release 2020.1204.0 / 9064ca9

**Logs:**

[logs.zip](https://github.com/ppy/osu/files/5645406/logs.zip)

**Comment by bdach** [comment]
If you're using fullscreen, this is intended (#11092). If not, then it's a bug.

Please confirm what display mode you're seeing this on.

**Comment by Walavouchey** [comment]
It's on exclusive fullscreen - closing as intended. Maybe the other two settings should be grayed out and disabled in such case to make it clear.

**Comment by bdach** [comment]
Sounds like a decent idea. Reopening to track that as more of an UX issue.
