### ISSUE TITLE
Watching replays with hidden mod causes hard crash

### ISSUE THREAD

**Issue by integerrr** [ppy/osu#11093]
Tested with other mods e.g. HR only, NM, FL only, DT only, doesn't exhibit this 

**Screenshots or videos showing encountered issue:** 
https://streamable.com/pkxib3

**osu!lazer version:** 2020.1203.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/5642697/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5642698/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5642699/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5642700/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5642701/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5642702/updater.log)
[database.log](https://github.com/ppy/osu/files/5642703/database.log)
[network.log](https://github.com/ppy/osu/files/5642704/network.log)

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/issues/11015, please search
