### ISSUE TITLE
Hold-to-confirm activation time set to zero messes up UI

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#11095]
When `Esc` is pressed, it brings up the "Are you sure you want to exit?"-screen with a messed up UI

**osu!lazer version:** 2020.1204.0

<img alt="image" width="400" src="https://i.imgur.com/4W8UXPU.png">

**Comment by frenzibyte** [comment]
That is intended, otherwise someone might press the escape button by mistake and have his game closed instantly.

What would you expect it to display in this case? such that this could be improved better.

**Comment by bdach** [comment]
Not sure what the "mess up" in the UI is here - is it that everything's black?

**Comment by Pennek** [comment]
the blackness mostly. shouldve probably mentioned that in the opening post. background was not black previously
