### ISSUE TITLE
Play again button on map end-screen exits to song select

### ISSUE THREAD

**Issue by GhtGhoster** [ppy/osu#11104]
**Describe the new feature:** 
A button to replay the map you've just finished on the end-screen with score assessment etc.

**Proposal designs of the feature:** 
 Just as in current stable.

**Comment by bdach** [comment]
This already exists.

![obraz](https://user-images.githubusercontent.com/20418176/101268552-7d194f00-3764-11eb-8334-31add8e1e231.png)

**Comment by GhtGhoster** [comment]
> This already exists.
> 
> ![obraz](https://user-images.githubusercontent.com/20418176/101268552-7d194f00-3764-11eb-8334-31add8e1e231.png)

I guess that makes this a bug report then. Takes me to map select. Am trying to record screen rn

**Comment by GhtGhoster** [comment]
Here's the vid, getting GeFroce running is a pain..
https://youtu.be/xqR0HoTe14E

**Comment by bdach** [comment]
Reopening for investigation.

**Comment by Joehuu** [comment]
@GhtGhoster is your back binding set to anything weird? I see the back button flashing in your video, and the only two reasons that happen is directly clicking the button or pressing any of the keys bound.

![dotnet_aSU6gh8aF1](https://user-images.githubusercontent.com/35318437/101269606-833c0b00-3725-11eb-93de-212436f7f922.jpg)

**Comment by GhtGhoster** [comment]
Oh crap you're right. I bought a new G502 and haven't looked into the settings. Works as intended now, my bad, thanks for the fix!
The issue for anyone to whom this might happen was basically me holding the mouse weird and pressing the side buttons without realizing I haven't rebound/unbound them. Sorry for the locomotion.

**Comment by bdach** [comment]
Closing as resolved.
