### ISSUE TITLE
Permanent green bars through the game on the latest release.

### ISSUE THREAD

**Issue by MakelMagus** [ppy/osu#11136]
Greetings, I'd like to add to this issue by presenting another graphic error, this one occurring in Windows 10, when opening the game from the latest release (2020.1204.0), in which the game is fully playable, but those lines are just... there, since the moment I open the game.
I've got no knowledge of C# to be able to help by prying on the code, but I'll send more images at different points of the game, and try to record a song playing.
## For additional information:
GPU: Intel(R) HD Graphics 630 
CPU: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
![image](https://user-images.githubusercontent.com/40347489/101690448-1047d280-3a4c-11eb-83e4-81cc3c22cc35.png)

_Originally posted by @MakelMagus in https://github.com/ppy/osu/issues/10603#issuecomment-742074622_

**Comment by bdach** [comment]
Card is listed as supporting OpenGL 4.4, so it theoretically should be working okay.

For additional information, please attach DirectX diagnostic info by performing the following steps:

1. Press <kbd>Windows</kbd>+<kbd>R</kbd>, type `dxdiag` in the appearing window and press <kbd>Enter</kbd>.
2. You could be prompted if you'd want Windows to check if the device drivers are signed - there should be no harm in agreeing to that.
3. In the *DirectX Diagnostic Tool* window that will appear, click *Save All Information...* and choose a file to save to.
4. Attach the saved file to this issue.

I would also ask you to check if there are any available device driver updates for your graphics card and try installing them if there are some.

**Comment by MakelMagus** [comment]
Will do, I just now did a video showing play, is uploading that of any use?

**Comment by bdach** [comment]
The more information the better, provided we're working with what's likely an issue specific to your hardware which most likely won't reproduce anywhere else. Due to that I can't exactly promise we'll able to resolve it, however.

**Comment by MakelMagus** [comment]
Additional Information:
[DxDiag - System Information - Osu! Lazer Artifact.txt](https://github.com/ppy/osu/files/5669007/DxDiag.-.System.Information.-.Osu.Lazer.Artifact.txt)
(currently converting video .mkv to .mp4)

**Comment by bdach** [comment]
From the attached dxdiag, as far as I can tell your drivers are about 5 months behind the latest release. Trying the newer version probably has the highest likelihood of resolving this.

**Comment by MakelMagus** [comment]
Oh ok, I'll close the issue and if the problem keeps happening after, I'll open it  again.

And by the way that is pretty odd, but not unexpected; I have the intel driver updater installed, and last week I ran a manual check and it kept telling me I had something to update, even after I did the download procedures, 3 times..,
