### ISSUE TITLE
Kegare Naki Bara Juuji (yf_bmp) just won't load

### ISSUE THREAD

**Issue by l4kr** [ppy/osu#11142]
**Describe the bug:** 
I can't seem to launch this beatmap (both difficulties). I have tried deleting and redownloading the map and restarting the client, is this a global problem? Other maps run fine.
**Screenshots or videos showing encountered issue:** 
![osu_2020-12-10_13-21-39](https://user-images.githubusercontent.com/73653844/101771891-e98ca900-3aea-11eb-9e11-9e8fc0ba53ca.jpg)
**osu!lazer version:** 

2020.1204.0
**Logs:**

[performance.log](https://github.com/ppy/osu/files/5672627/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5672628/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5672630/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5672631/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5672632/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5672633/updater.log)
[database.log](https://github.com/ppy/osu/files/5672634/database.log)
[network.log](https://github.com/ppy/osu/files/5672635/network.log)

**Comment by LittleEndu** [comment]
Please link the beatmap

**Comment by l4kr** [comment]
https://osu.ppy.sh/beatmapsets/448818#osu/1003565

**Comment by bdach** [comment]
The map in question has a quite chonky storyboard, with 57.5k seemingly identical elements on one layer:

![2020-12-10-185926_564x275_scrot](https://user-images.githubusercontent.com/20418176/101811090-e826a500-3b19-11eb-9b7f-c630f0a58946.png)

Nothing a bit of pooling wouldn't fix, but still, load times *are* bound to get pretty bad in the current state of things...

**Comment by bdach** [comment]
Actually, seeing that we have #4976 open, let's just track this there instead. Closing as duplicate.
