### ISSUE TITLE
Sound for the enitre client is gone (BASS faulted with error code -1)

### ISSUE THREAD

**Issue by Skrubbadubba** [ppy/osu#11144]
**Describe the bug:** 
So simply put, there is no sound at all. The error "BASS faulted with error code -1: unknown" pops up whenever I start the game.
The bug started happening after I followed some instructions in this guide: https://www.reddit.com/r/osugame/comments/hqoakj/tutorial_removing_perceivable_latency_for_good/
Specifically, after I run the REAL application that can be found here: https://github.com/miniant-git/REAL/releases/tag/updater-v2
It's supposed to minimize Windows Audio Buffer Latency.
If I remember correctly I didn't do anything other than running that application that might have done something with the sound, although I'm not sure.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/75796723/101789333-7a6e7f00-3b01-11eb-9d3f-fd112a8e2f86.png)

**osu!lazer version:** 
currently on 2020.1204.0, altough I've experienced this error for 1 or 2 months I think

**Logs:**

[database.log](https://github.com/ppy/osu/files/5673668/database.log)
[debug.log](https://github.com/ppy/osu/files/5673670/debug.log)
[network.log](https://github.com/ppy/osu/files/5673673/network.log)
[performance.log](https://github.com/ppy/osu/files/5673674/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5673675/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5673676/updater.log)

**Comment by peppy** [comment]
Please undo any hacks you applied to your system. We cannot support this.
