### ISSUE TITLE
Profile header should imply it is loading new content when the user is changed

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#11155]
**Describe the bug:** 
When clicking on a new profile, the header will keep the old content active until the new content to replace it has been loaded. Instead, all the content should be replaced with placeholders while the new content is loading. 

**Screenshots or videos showing encountered issue:** 
https://youtu.be/ejpO3HY1bIE

**osu!lazer version:** 
2020.1204.0

**Comment by EVAST9919** [comment]
https://github.com/ppy/osu/pull/5254 was intended to fix this one (in some sort)

**Comment by peppy** [comment]
If this is to be done it needs to be done in a way that looks good. Using some kind of loading screen and/or placeholders.

Likely *not* even clearing the previous content but just showing that it's loading new content.
