### ISSUE TITLE
Transition times are faster when entering player loader

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#11168]
**Screenshots or videos showing encountered issue:**
Last release: 
![xpYrMi2WcY](https://user-images.githubusercontent.com/35318437/102032583-0c7abf80-3d6e-11eb-843b-6f07a3eda4ae.gif)

Latest release:
![aQaDk70Lfs](https://user-images.githubusercontent.com/35318437/102032584-0dabec80-3d6e-11eb-9084-a3e9afb80df0.gif)

**osu!lazer version:** 2020.1212.0

**Comment by peppy** [comment]
This does look like a regression.
