### ISSUE TITLE
.desktop file for lazer on Linux

### ISSUE THREAD

**Issue by Cyliann** [ppy/osu#11178]
**Describe the new feature:** 
I'm not sure if it's a feature, but it would be nice to have a .desktop file for linux. Currently I'm launching it from .appimage and I have to make a .desktop file myself.

**Comment by bdach** [comment]
A `.desktop` file is [already bundled inside of the AppImage](https://github.com/ppy/osu-deploy/blob/master/osu!.AppDir-template.zip). Not sure what the purpose of having it outside would be - you can always extract it out of the AppImage yourself instead of making one on your own.
