### ISSUE TITLE
Adjustable mania hit position not correctly clamped

### ISSUE THREAD

**Issue by MasterZitron** [ppy/osu#11184]
**Describe the bug:** One circle skin I have makes the notes zoom by the screen, making it impossible to hit. Increasing scroll speed makes them appear earlier, but out of sync with the song. Every other skin works fine

**Screenshots or videos showing encountered issue:** 
[Video](https://streamable.com/2mcq4e)

**osu!lazer version:** 2020.1212.0

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/5700259/performance.log)
[updater.log](https://github.com/ppy/osu/files/5700260/updater.log)
[database.log](https://github.com/ppy/osu/files/5700261/database.log)
[runtime.log](https://github.com/ppy/osu/files/5700262/runtime.log)

Skin with the problem: 
[kiyo circle dance therapy lower_hitposition.zip](https://github.com/ppy/osu/files/5700269/kiyo.circle.dance.therapy.lower_hitposition.zip)

**Comment by smoogipoo** [comment]
![image](https://user-images.githubusercontent.com/1329837/102304509-f3a62000-3fa0-11eb-9efa-affaa5315e2b.png)

In stable the allowable hit position from the skin is clamped: `HitPosition = Math.Max(240, Math.Min(HitPosition, 480));`

**Comment by peppy** [comment]
(as a temporary fix you can change the value in the skin.ini of your skin to 480)

**Comment by MasterZitron** [comment]
Had to re-import skins since I'm not sure how to reload, but works fine now. Thanks!

**Comment by peppy** [comment]
Issue is fine to remain open. We'll want to clamp this at a code level still.
