### ISSUE TITLE
Spinners sometimes don't play any audio

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#11194]
**Describe the bug:** 
Unsure if and what this is related to. Seems to happen regardless if you spin CW or CCW, but audio gets restored when you change direction mid spinner.

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/11320483/102546325-25fa6f00-40c0-11eb-8c90-3b19def24498.mp4

**osu!lazer version:** 
2020.1212.0

**Comment by bdach** [comment]
Mind expounding on the "glitched" part? I'm not hearing anything out of the ordinary in the video attached.

**Comment by LittleEndu** [comment]
Well, it sounds (when on legacy skin anyway) nothing like it does on stable so I assumed it was glitched.

**Comment by bdach** [comment]
The video does not use legacy skin...? I guess I'll go check myself but if you've already gone and added a video then might show everything you have to show on it...

**Comment by LittleEndu** [comment]
I do have a vid on legacy skin too, give me a second

**Comment by LittleEndu** [comment]
https://user-images.githubusercontent.com/11320483/102547396-d74dd480-40c1-11eb-9243-79753e3d2104.mp4

**Comment by bdach** [comment]
seems like the default skin audio is used? that's probably a failing skin lookup & therefore a separate issue. please attach the skin, too.

**Comment by LittleEndu** [comment]
This is the skin: https://mega.nz/file/7kNSRRiK#9nve6CszZ6r2o7wKHAml1tuBkTylc0AEHw9BiGDaFrY

**Comment by bdach** [comment]
skin attached has no `spinnerspin.wav` sample, therefore the lazer default skin one is used, while it should be using the legacy default skin's. that is tracked under #8019; removing that part from the scope of this issue.

**Comment by bdach** [comment]
I can reproduce this, easiest is with autoplay with any map that has 2 spinners in the beginning.

OP used https://osu.ppy.sh/beatmapsets/371128#osu/814293, but I can also reproduce on others like https://osu.ppy.sh/beatmapsets/397905#osu/865344.

Probably not going to able to root-cause it today, but as a hint of sorts, removing the `Stop()` in the below call seems to resolve:

https://github.com/ppy/osu/blob/bb586f3175c17fb43b71d953120ff1404fa3485d/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs#L138

Unsure if such a local fix is valid. My current best (unconfirmed) suspicions are:

* interference from enqueued events from a previous sample usage (this is definitely a thing that happens for sure, just not sure if it has any influence),
* and that stopping pooled samples might be freeing channels.

**Comment by bdach** [comment]
Never mind, found it, pretty gnarly cause. Following stack trace should be enough to figure out what's happening.

```
PausableSkinnableSound.Stop() at /home/dachb/Dokumenty/opensource/osu/osu.Game/Skinning/PausableSkinnableSound.cs:line 84
DrawableSpinner.<updateSpinningSample>b__25_0() at /home/dachb/Dokumenty/opensource/osu/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs:line 141
TransformSequence<PausableSkinnableSound>.<>c__DisplayClass35_0.<OnAbort>b__0()
TransformSequence<PausableSkinnableSound>.onTransformAborted()
TargetGroupingTransformTracker.invokePendingRemovalActions()
TargetGroupingTransformTracker.AddTransform()
Transformable.AddTransform()
TransformableExtensions.TransformTo<osu.Game.Skinning.PausableSkinnableSound>()
TransformableExtensions.TransformBindableTo<osu.Game.Skinning.PausableSkinnableSound, double, osu.Framework.Graphics.Transforms.DefaultEasingFunction>()
AdjustableAudioComponentExtensions.VolumeTo<osu.Game.Skinning.PausableSkinnableSound, osu.Framework.Graphics.Transforms.DefaultEasingFunction>()
AdjustableAudioComponentExtensions.VolumeTo<osu.Game.Skinning.PausableSkinnableSound>()
DrawableSpinner.updateSpinningSample() at /home/dachb/Dokumenty/opensource/osu/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs:line 136
Bindable<bool>.TriggerValueChange() [2]
Bindable<bool>.SetValue() [2]
Bindable<bool>.TriggerValueChange() [1]
Bindable<bool>.SetValue() [1]
Bindable<bool>.set_Value()
SpinnerRotationTracker.Update() at /home/dachb/Dokumenty/opensource/osu/osu.Game.Rulesets.Osu/Skinning/Default/SpinnerRotationTracker.cs:line 74
```

**Comment by peppy** [comment]
I'm having a hard time getting the same stack trace to occur as you posted above... even though it seems like it should 100% trigger (`OnFinally` is supposed to run on abort/interruption, which is precisely what is happening here). @bdach are you still able to repro this one? Curious if something we did framework side has changed the behaviour..

Also if you can repro, does changing the `Finally` to an `OnComplete` help (see https://github.com/ppy/osu/pull/11502)?

**Comment by bdach** [comment]
From what I recall off the top of my head, hitting this required the drawable spinner instance to have been used at least once before, so testing required a map with at least 2 spinners spaced apart far enough wherein they can get the same pooled instance. Will test the linked PR when I can do that.
