### ISSUE TITLE
Green flickering screen on the newest build.

### ISSUE THREAD

**Issue by Awoolanche** [ppy/osu#11192]
**Describe the bug:** 
Green flickering screen after launching. Tried changing various settings, no result. Windows 10, I5-10210U, 8GB RAM, GeForce MX230.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/76163840/102487312-a68e8080-406a-11eb-84b7-069df947bab6.png)

**osu!lazer version:** 
2020.1212.0
**Logs:**

[performance.log](https://github.com/ppy/osu/files/5709301/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5709302/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5709303/updater.log)
[database.log](https://github.com/ppy/osu/files/5709304/database.log)

**Comment by frenzibyte** [comment]
Relevant to https://github.com/ppy/osu/issues/11136, have you tried updating your GPU driver to the latest version?

**Comment by Awoolanche** [comment]
All of my drivers are up to date.

**Comment by Awoolanche** [comment]
Issue fixed. It seems Lazer have set the wrong GPU as a main one, causing those green lines.
