### ISSUE TITLE
Game registers mouse clicks and scroll events when unfocused

### ISSUE THREAD

**Issue by sr229** [ppy/osu#112]
This can be easily replicated on the current `master` branch (102.27.16)

**Replication Procedure:**
- Compile osu! on Any Arch or Configuration
- Open another program of choice
- try scrolling or clicking while the game is unfocused and the 2nd program on the foreground

(Note:  program from Step 2 should be within the Game Window)

**Comment by huoyaoyuan** [comment]
Already noticed.
There can be some work to do in osu-framework.

**Comment by huoyaoyuan** [comment]
Will be fixed in ppy/osu-framework#239.
