### ISSUE TITLE
Approach circle behaviour when it reaches perfect hit moment doesn't match stable

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#11209]
**Describe the bug:** 
On stable, after it's the perfect moment to hit the circle, approach circle ~~keeps getting smaller~~ instantly disappears. On lazer, it just stops.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/11320483/102653873-46860000-4178-11eb-8316-68278e01826e.mp4

https://user-images.githubusercontent.com/11320483/102653882-4b4ab400-4178-11eb-8ed5-63b30bba2c5f.mp4

**osu!lazer version:** 
2020.1212.0

**Comment by bdach** [comment]
As far as I know the animation transforms are the exact same as in stable. However, the following adjustment will probably have something to do with it - removing it seems to alleviate (@LittleEndu - would like your confirmation that it does):

https://github.com/ppy/osu/blob/0abe2b36b262c3f5662192f3b88a5f9c3c4ba4bb/osu.Game.Rulesets.Osu/Skinning/Default/ApproachCircle.cs#L42-L44

I guess the way forward would be to trim the sprite over at resources and get rid of this?

**Comment by LittleEndu** [comment]
![circles](https://user-images.githubusercontent.com/11320483/102656916-610ea800-417d-11eb-90b8-062e0ca6cd29.png)

Unless I'm doing something wrong (I'm just commenting out that line) I see no difference

**Comment by bdach** [comment]
On checking the actual skin's assets they actually seem to have this 1px-ish gap built in.

![2020-12-18-211557_825x798_scrot](https://user-images.githubusercontent.com/20418176/102657627-47b62d80-4176-11eb-975b-3c495a0c80f7.png)

This is `hitcircle.png` overlaid on top of `approachcircle.png`. Unsure how it's working on stable but also unsure whether this should be supported going forward.

**Comment by LittleEndu** [comment]
The circle actually instantly disappears.

https://user-images.githubusercontent.com/11320483/102660283-771f6700-4183-11eb-8e3c-6023610a47eb.mp4

**Comment by bdach** [comment]
lazer also has a very short (~3 frames-ish) fade out time:

https://github.com/ppy/osu/blob/0abe2b36b262c3f5662192f3b88a5f9c3c4ba4bb/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs#L171-L172

but it plays on miss, which in this case is probably too late due to the miss hit window leniency.

**Comment by LittleEndu** [comment]
So isn't the simplest solution to just add ``.Then().FadeOut(50)`` to this: 

https://github.com/ppy/osu/blob/0abe2b36b262c3f5662192f3b88a5f9c3c4ba4bb/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs#L149-L158

**Comment by bdach** [comment]
Possibly. Would like more opinions on whether that is the correct thing to do first.

**Comment by frenzibyte** [comment]
For reference, here's how it looks like on master "before", and with the change proposed here "after" (all in 0.1x speed):

https://user-images.githubusercontent.com/22781491/102680262-c38c9600-41c7-11eb-8243-ae724dc4150e.mov

https://user-images.githubusercontent.com/22781491/102680254-b5d71080-41c7-11eb-9a2a-91236dd0d249.mov

I personally would choose the proposed behaviour over the current one, looks nicer than having the approach circle frozen until the object gets interacted.

**Comment by peppy** [comment]
I actually did this intentionally, but I'd also lean towards the old style being visually better, so not against changing this (including the lazer default skin).

**Comment by peppy** [comment]
The behaviour on stable (where it immediately disappears) actually looks to be a bug. This was never my intention. The code reads as if it should be fading along with the rest of the object.

Given that this has been the default behaviour for god knows how long, I think adding the fade is a good compromise for now (since this seems to rub a lot of users the wrong way when switching to lazer).

**Comment by peppy** [comment]
For reference, this is the source of the bug on stable. The fade out is supposed to be 60ms, but the initial alpha value is being read at a point where the approach circle has an alpha of 0, so the fade is never occurring:

![20210323 190226 (iTerm2)](https://user-images.githubusercontent.com/191335/112129096-63fcb700-8c0a-11eb-9d27-62ece0a311cd.png)
