### ISSUE TITLE
Objects not yet loaded/visible do not respect the selection box resizing

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#11203]
**Describe the bug:**
To avoid making a video that explains step by step:
- create a beatmap
- save it with some objects (to reproduce the problem as soon as possible)
- re-open the beatmap in the editor
- select objects that are not yet visible in the playfield from the timeline
- resize the selection box

**Screenshots or videos showing encountered issue:** 
![selection](https://user-images.githubusercontent.com/43073074/102613650-26801d80-4133-11eb-84cb-24da0ff40898.gif)

**osu!lazer version:** 2020.1212.0

**Comment by Gabixel** [comment]
Actually, I think it's the opposite: the selection for some reason doesn't visually update(?)

**Comment by peppy** [comment]
This looks like an issue specific to the beatmap you are editing.  Can you describe the full flow for which you are using to reproduce this? For some reason the hitobjects in your beatmap are seemingly not loaded (doesn't happen when editing an existing beatmap for me).

**Comment by Gabixel** [comment]
I _can_ reproduce this on some existing beatmaps (~80% of the time), so I would ask you to try again with any other beatmap to confirm this.

The full flow to reproduce the issue is actually simpler than the one described in my original post: just open a map in the editor and select some objects (including some not yet visible/loaded), and you can reproduce this. [Here's an example](https://user-images.githubusercontent.com/43073074/103365165-c3da3a80-4abf-11eb-8f4a-b7505853986a.mp4).

Sliders seem to alleviate the issue, but the issue can also be reproduced with them if you drag their control points:
![slider](https://user-images.githubusercontent.com/43073074/103365442-567ad980-4ac0-11eb-8bf0-f7578e4711a9.gif)
