### ISSUE TITLE
Choosing where to display the combo counter for the osu!mania

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#11211]
**Describe the new feature:** 
When legacy skins are supported, the combo counter for this mode is displayed on the left, although this should not be. I think it's worth giving the players the choice of how to display the counter.
Now:
![image](https://user-images.githubusercontent.com/59089206/102685430-863cfe00-41f1-11eb-8407-8b80c2138f57.png)
Stable:
![screenshot016](https://user-images.githubusercontent.com/59089206/102685467-e03dc380-41f1-11eb-8819-1d6c2134f16a.jpg)

**Comment by bdach** [comment]
#10526
