### ISSUE TITLE
Main menu gets stuck with editor placeholder background after trying to close window twice in editor

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#11214]
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/35318437/102700985-3b2de580-4207-11eb-81e3-09c75f3078a3.mp4

**osu!lazer version:** After https://github.com/ppy/osu/pull/10608

**Comment by Gabixel** [comment]
Also, if you close lazer, that background doesn't change dim and it's visible during the closing effect:
![dim](https://user-images.githubusercontent.com/43073074/102701325-37757f80-4256-11eb-90b4-b168c5a27644.gif)
