### ISSUE TITLE
Classic intro song doesn't loop flawlessly

### ISSUE THREAD

**Issue by Eveydude** [ppy/osu#11215]
Not necessarily a bug, so I'll just keep it in feature requests since it fits best.
The loop for nekodex - welcome to osu! is kind of bad, it's not like horrible, but it's just not satisfying for a song so good. Also, yes, I am aware that it is literally just a title theme.

**Comment by frenzibyte** [comment]
I don't get the point of this, how do we fix it, what is wrong about it?

**Comment by Joehuu** [comment]
If you played osu! in ~2015, it used to loop. The loop is there for nostalgia for past users.

**Comment by peppy** [comment]
Could you please provide a video for reference? This is probably due to encoding changes (can't remember if that was a thing that happened when bringing across).

**Comment by PercyDan54** [comment]
> If you played osu! in ~2015, it used to loop. The loop is there for nostalgia for past users.

Stable fallback still loops
