### ISSUE TITLE
MAC OS X top half screen glitching even after closes up.

### ISSUE THREAD

**Issue by mongoliank** [ppy/osu#11220]
**It is weird i can discribe it:** 

**![20201220_193815.jpg](https://user-images.githubusercontent.com/60033343/102715719-576a7900-4312-11eb-8507-8bb4e3d3e11b.jpg)**

**Comment by bdach** [comment]
If this remains even after the game's closed this is either a hardware failure or a firmware problem, neither of which is really in scope for this project.

**Comment by mongoliank** [comment]
I don't know. It is fine until open up osu?

**Comment by bdach** [comment]
Nothing the game does should be corrupting the entire internal state of the graphics card to the degree in which the artifacts would remain after it's closed. If it did, we'd probably be aware of that already.
