### ISSUE TITLE
osu lazer beat maps not being found from stable

### ISSUE THREAD

**Issue by lukethegreat1232** [ppy/osu#11224]
**Describe the bug:** 
alright im trying to convert my osu stable songs into the osu lazer but osu only locates 3000 whene i have 7746 in stable and i dont know that to do i can not find any thing on the probleme
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** latest as of 12/20/2020

**Logs:**

**Comment by bdach** [comment]
I'm pretty sure this is because stable counts individual beatmaps (as in individual difficulties) on the main menu screen, while the lazer import notification counts beatmap *sets*. Maybe the message could be clarified but I believe there should be no such discrepancy.
