### ISSUE TITLE
Fix load/isalive issues

### ISSUE THREAD

**Issue by smoogipooo** [ppy/osu#1123]
OnScreenDisplay should have a light the first time it's called. Apparently MusicController is also expiring the previous panels too early, but I can't replicate this.

**Comment by smoogipooo** [comment]
Fixed by https://github.com/ppy/osu/commit/61182092004e43ac597ef1492e29a7bc0acaf63a. Let's debug the MusicController one separately, especially since I can't replicate it myself.

**Comment by peppy** [comment]
should be one issue per issue anyway
