### ISSUE TITLE
"Raw input" locked on Linux

### ISSUE THREAD

**Issue by Cyliann** [ppy/osu#11242]
**Describe the bug:** 
I cannot switch on "Raw input" on. It's locked.
I read that raw input on Linux is broken, but I can't even turn it on.
Distro: Arch

**Screenshots or videos showing encountered issue:** 
![Screenshot from 2020-12-21 11-12-11](https://user-images.githubusercontent.com/33868960/102766003-c204ce80-437d-11eb-9789-1bd84182625c.png)

**osu!lazer version:** 
2020.1212.0

**Comment by bdach** [comment]
It was disabled precisely because it was broken and we were getting multiple duplicates reporting that. It will return when it's in a better working state.
