### ISSUE TITLE
Hitsounds not playing on certain sliders

### ISSUE THREAD

**Issue by Eveydude** [ppy/osu#11245]
Sliders with combo number 10 will not play their hitsounds. This seems to be exclusive to combo number 10, and circles will still play their hitsounds even if they have combo number 10.

A video would explode my computer... sorry

2020.1212.0 (Latest as of 21 December)

**Comment by bdach** [comment]
Can you at least link a map that uses such hitsounds?

**Comment by Nikosgr121** [comment]
btw not only that i find few maps with very sort sliders to not have sound
hmm i thing 1 map i find that is liquicity mix 2015 some pars have very sort sliders and no sound came from them also some onther tech maps have same thing very sort slider no sound

**Comment by bdach** [comment]
@Nikosgr121 as mentioned above, please actually link the maps in question instead of vaguely mentioning "tech maps" so we don't have to guess.

**Comment by minasminas** [comment]
I've noticed this too, and I found a pretty good map to demonstrate this I think:
https://osu.ppy.sh/beatmapsets/1313084#osu/2722818

Especially the "Hard" difficulty seems to have some (slider)hitsound problems in the beginning part. I think the sound of the Sliderends doesn't go away completely, but the volume is jumping around a lot. It doesn't sound right at all I think.

**Comment by peppy** [comment]
Going to close this issue for now as we've made a lot of improvements to sample playback, and also there has been no further information given in this issue as to which beatmaps were seen a a problem.
