### ISSUE TITLE
Option to modify song audio

### ISSUE THREAD

**Issue by volume11** [ppy/osu#11241]
**Describe the new feature:** 

Due to twitch's new issues surrounding copyright, an option to warp the audio for streams would be nice. Some kind of pitch shift or similar to avoid copyright detection. This would mean copyright avoidance could be handled in the client rather than in obs which would also warp hitsounds and other sound effects.

**Comment by bdach** [comment]
Bypassing IP protection measures is not the proper way to go about this. The proper way is the featured artist system.
