### ISSUE TITLE
How to delete all data for osu! lazer?

### ISSUE THREAD

**Issue by tigwersparkz** [ppy/osu#11243]
Lazer is installed on the wrong disk, and i want to move its installation place but every time i "uninstall" and reinstall it, it automatically gets reinstalled where it last was and i doesn't give me the option to change it. So i want to know if deleting all the data for lazer will allow me to change it's installation place.
Including the imported songs because i ran out of disk storage on that disk it was installed in and now i can't find where the songs got imported to and it's taking up all my storage.

Thanks in advance.

**Comment by frenzibyte** [comment]
`Change folder location...` button in settings should help you with that.

**Comment by peppy** [comment]
There's also an "open folder" button in settings.
