### ISSUE TITLE
Large imports starve the TPL thread pool

### ISSUE THREAD

**Issue by Game4all** [ppy/osu#11251]
**Describe the bug:** 

As discovered in https://github.com/ppy/osu/pull/11212#discussion_r546351755, launching large imports with an `ArchiveModelManager` will spawn a lot of tasks which are in turn awaiting on a task with a harshly limited concurrency, starving the TPL thread pool and causing a noticeable slowdown of things relying on async stuff (ie: loading the game main menu). 

This is noticeable especially on mobile where cpu cores aren't many.

**Comment by peppy** [comment]
Awaiting on a task with limited concurrency will not consume threads. that's not how `await` works. so while the issue may exist, your diagnosis is likely not correct.

**Comment by Game4all** [comment]
It seems that throttling the number of tasks being spawned at a time in ArchiveModelManager.Import() to a reasonable count using SemaphoreSlim allows to halve the startup time when importing a lot of beatmaps upon launching.

However, before PR'ing anything, I'm not sure whether to apply this throttling per archive manager or globally across all managers (as I guess the latter would probably hurt import perf when importing simultaneously beatmaps and skins)

Commit for reference: https://github.com/Game4all/osu/commit/f4b22a0593ea6d6d654cf6636461ec6a3a1a15af

**Comment by bdach** [comment]
Have you looked at why the time is apparently halved? All things considered, the points of contention (the `imported` lock and the single-threaded underlying import scheduler) remain the same, so I'm curious why this makes any difference - maybe it's the async wait on the throttler, which maybe lets TPL free up the waiting thread for the pool...?

**Comment by Game4all** [comment]
Haven't really looked up at what may cause gains in startup time when throttling, I'll try to look at that in the week-end if i manage to find time ... Also, I didn't publish the results of my approximative benchmarking of the startup time** , so here it is:


Launch type | Startup time (avg of 3 measures) |
----------|----------------------------------|
Normal launching (No imports)    | 12,3 s 
Importing beatmaps upon startup (No Throttling) | 47.5 s
Importing beatmaps upon startup (Throttled to 4 tasks) | 19.2 s
Importing beatmaps upon startup (Throttled to 8 tasks ) | 23.2s

Benchmarking done on a Samsung Galaxy A8 2018 (Octa core CPU: 2x2.2 GHz Cortex-A73 & 6x1.6 GHz Cortex-A53)

**I mean by the startup time, the time spent starting from launching the app to having the loading spinner in the bottom right disappear.

**Comment by Game4all** [comment]
This issue seems to be another instance of #11198 ( same underlying issue that on desktop, it's just more noticeable on mobile due to the less much count of cores. ), as such I guess this can be closed?.

**Comment by peppy** [comment]
Might be best to keep this open as it is potentially slightly different (related to startup time increase). But yeah, there's a change a fix for one will fix both.

**Comment by Game4all** [comment]
Upon checking out master again and benchmarking again, #11802 indeed solves this (startup time when importing 20 beatmaps went from 45s to less than 13s), closing.
