### ISSUE TITLE
Enter The game always show "Never Played" instead of actual player stats on left up corner

### ISSUE THREAD

**Issue by 1e1000000** [ppy/osu#11258]
**Describe the bug:** It should be show lv11, 0 pp and 78.62% acc (yesterday status), see below screenshot for bugged image

**Screenshots or videos showing encountered issue:** 
![unknown](https://user-images.githubusercontent.com/54700438/102899145-73eaea80-44a5-11eb-9988-eddab4d0fcc9.png)

**osu!lazer version:** b20201210.2

**Logs:** No

**Comment by peppy** [comment]
Wrong place. Also you're probably looking at the wrong play mode (change your selection).
