### ISSUE TITLE
Nested hit objects are leaked when parent hit object is edited or deleted

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu#11261]
1. Inspect `Playfield.lifetimeEntryMap.Count` while editing a slider shape.
2. See the number is increasing rapidly.

Nested hit objects should be removed when the parent hit object is removed or when the nested hit objects are recreated by `ApplyDefaults`.

It is a visual issue for osu!catch editor because new nested hit objects will be stacked every frame while the parent object is edited, resulting in a massive amount of stacked objects.

**Comment by peppy** [comment]
Came across this one again while investigating #20208.

![Parallels Desktop 2022-09-12 at 08 44 26](https://user-images.githubusercontent.com/191335/189610945-fd7e4496-f931-4dfc-9d17-c92cc8a206cf.png)
