### ISSUE TITLE
Virus IDP.Generic

### ISSUE THREAD

**Issue by Arutosio** [ppy/osu#11272]
when i try to run osu this is the problem
![image](https://user-images.githubusercontent.com/30377429/103024119-84579f80-454f-11eb-9462-24eceeef056b.png)

**Comment by bdach** [comment]
Judging from the name of the detected "virus" (see "generic") this is a false positive.

If you're very worried, please attach the checksum of the executable you're trying to run, but as long as you downloaded from safe sources (i.e. github), this should very much be a false detection.
