### ISSUE TITLE
Dim volume in multiplayer lobbies while waiting for game to start

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#11298]
**Describe the new feature:** 
Optional feature to turn down volume of the music during multiplayer lobbies while not in-game. The music should return to normal level when playing or when leaving the lobby.

This feature would be usefull to me because I often want to listen to other stuff or talk (without tabbing out of osu) while I'm waiting for the multiplayer lobby to start a new map, so I turn down the volume manually. Then when the map actually starts I forget to turn it back to normal volume and I mess up my gameplay.

**Proposal designs of the feature:** 
This option can be added in the volume section of the options similar to the "Master (window inactive)" slider, but as this could add too many sliders in the future I propose changing the "Master (window inactive)" to something generic like "Master (dimmed)" and adding additional radio buttons for "Dim volume when window inactive" and "Dim volume when in multiplayer lobby" which control when to dim the volume.

If this design gets the greenlight then I might implement it myself.

**Comment by bdach** [comment]
I'm pretty sure the volume should be dimmed if the window is not in focus. If that is not happening for you, then that might be a framework bug - do you mind stating your platform and whether you can observe the volume dimming when changing the focused window?

**Comment by bdach** [comment]
On re-reading I might have misunderstood by what you mean by "in game". You mean "in the room but not actively playing", right?

I'll rename the issue to reflect that better. Not sure whether it should be a separate slider, probably just a checkbox...?

**Comment by OliBomby** [comment]
The volume does get dimmed when the window is not in focus. There are no issues with that. 
In this issue I ask for volume dimming while the window **is** in focus. That's why I added "(without tabbing out of osu)" in the description. I think you misunderstood my wording a bit.

Volume should be dimmed when you are in the multiplayer Room screen with the osu! window in focus.

**Comment by OliBomby** [comment]
> Not sure whether it should be a separate slider, probably just a checkbox...?
I had the same thought, but it's also nice to be able to control how much dimming happens, so I proposed changing the "Master (window inactive)" to something generic like "Master (dimmed)" and adding additional radio buttons for "Dim volume when window inactive" and "Dim volume when in multiplayer room" which control when to dim the volume.

That way you can control **when** and **how much** dimming should happen and it leaves room to add more areas to control the volume dimming.

**Comment by bdach** [comment]
To be honest, from our side, the less setting menu items the better, really. The settings menu is super cluttered as is anyway; I'd prefer it to apply automatically (maybe after the player has readied up) and universally (with no setting to control it) over a setting, and a single setting (can be a combo box) over two radio buttons.

**Comment by OliBomby** [comment]
I see why you want less stuff in the settings menu, but this volume dimming while waiting for a game to start is preference, so there still should be some control over it.

The problem with automatic dimming when readied up is people who want to listen to the music have to deal with the dimming and people who want the dimming have to wait for the next person to pick a song. 

Maybe the problem isn't that big. I forgot if you can ready up at any time in this version of multiplayer, but at least in osu! stable you can't ready up when the host is picking a song.
For people who want to listen to the music, they can just set the dimmed volume to 100% with the already existing slider.

I think this is an approach that can work, but it's also introducing these convoluted workarounds for control of the dimming which might be more confusing than 2 extra options in the settings menu. 
I personally think the settings menu isn't very cluttered if you use the search function effectively and I like having options for everything.

**Comment by peppy** [comment]
I'd rename the "inactive" volume setting to "dimmed" and then just have checkboxes or a dropdown for when the dimming should happen.

**Comment by smoogipoo** [comment]
I really don't understand this / don't agree with this. @OliBomby just to confirm, you _dim_ the track to listen to something else, instead of muting altogether? Do you also dim the other application when the match starts?

Imo dimming like this should be a user action, not something the game does for you.

**Comment by peppy** [comment]
The proposal is that this should be done by the game in the lobby, because it can happen that you are waiting for the lobby to start for 10-20 minutes while listening to the same loop of a 1 minute song the whole time.

**Comment by smoogipoo** [comment]
I understand the proposal, I just don't understand the reasoning. If you're waiting 10-20 minutes for a lobby to start, it takes 1 second to open the music controller and press pause. More UX like this just gets complicated/messy/unintuitive/leads to cognitive overload.
Because, for example, what if you don't want this in one particular case? Should an option then be added to quick-disable this setting because the user actually wants to listen to the track at full volume? Do we then make it full volume only for the first loop but then dim it for the second-onwards? It basically just becomes a whole tree of UX implementation for something that's effectively one click away.

**Comment by peppy** [comment]
I agree it's pretty bad UX. Leaving this in a proposal state for that reason (wouldn't consider unless it gains traction).

**Comment by smoogipoo** [comment]
I only brought it up because there's a PR already active, with the author asking for comments/a path forward/looking to make the changes to multiplayer itself (hence leading to another PR), and us disagreeing with the path taken.

Will close PR and redirect back here for further discussion.

**Comment by OliBomby** [comment]
The reasoning behind my proposal is that when I play osu! multi with friends, I like to talk over discord while waiting for the game to start and when we start playing we don't talk anymore. It's specific to the multiplayer waiting screen. The music pause button is hidden behind the "now playing" menu, so it's 2 clicks every time you get sent to the multiplayer waiting screen and I rather still have dampened music volume for bg music, so dampening music is better than pausing it completely. If the game dampens audio automatically that would be much nicer, because I dont have to manually correct the audio myself every single time.

About the UX concern, it doesn't have to be that complicated. If it's just one opt-in option, users can enable it for their convenience and disable it when they want to blast their ears with music again. 
Or we could have no option at all: Just always dampen music in the multiplayer waiting screen. If someone for whatever reason wants to listen to the music full volume, they can turn up the volume with Alt+scroll and the game will un-dampen the music. I think this design makes sense because the first thing someone will do if they want to turn up the volume, is to turn up the volume.
