### ISSUE TITLE
Failed to retrieve a score submission token on android

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#11296]
**Describe the bug:** Happens on both playlists and multiplayer. Just tracking as it has been lost in discord (thought it was a simple hash change to fix).

**osu!lazer version:** 2020.1225.0

**Comment by bdach** [comment]
From what I remember android uses the version number as hash. Maybe that one has slipped by, not sure.

**Comment by peppy** [comment]
Sorry about that, made a typo in a piece of deployment that really shouldn't be manual. Should be resolved now.

**Comment by Joehuu** [comment]
Seems broken again as of now, reopening again until there is a proper system in place...?

Source: https://osu.ppy.sh/comments/1416174 and me

**Comment by peppy** [comment]
Has been resolved. Build script was still referencing 2020
