### ISSUE TITLE
Autoplay can be selected in multiplayer rooms

### ISSUE THREAD

**Issue by nathannino** [ppy/osu#11293]
**Describe the bug:** 
While autoplay doesn't seem to be allowed when creating a room, autoplay can be added to the lists of mods after creating the room. Speeding up and slowing down autoplay works, and both leaderboards and score submission doesn't seem to work
**Screenshots or videos showing encountered issue:** 
https://youtu.be/691cbAIu1TE
**osu!lazer version:** 
master (checked on commit : 4e21bd0108f508ce9cdba8dd521bf8ebfc4f2a80)
(It also works in 2020.1225.0, I was just too slow in writing this issue)
**Logs:**
[network.log](https://github.com/ppy/osu/files/5740215/network.log)

**Comment by peppy** [comment]
Closing as this is addressed on the client. Tracking for server via https://github.com/ppy/osu-server-spectator/issues/45.
