### ISSUE TITLE
Ingame leaderboard avatars of players should not be clickable

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#11295]
i dont think the ingame leaderboard avatars should be clickable since its weird when you hover over them and see the popup text/hear the hover sound

https://user-images.githubusercontent.com/43358824/103103043-52157300-461f-11eb-8d97-3fe1c0a41849.mp4

**Comment by frenzibyte** [comment]
It should not be possible to hover over them in gameplay, but I think it would be a cool feature to do so when spectating them and otherwise.

**Comment by mouzedrift** [comment]
probably not possible on widescreen resolutions but definitely possible on smaller resolutions like 4:3 or 5:4
