### ISSUE TITLE
Random music gets played after seeking to the completion in AutoPlay or Replay visual tests

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu#11301]
Somehow `MusicController` thinks the current music is ended and tries to play the next music. I causes massive lag for some reason, and the test step will be timed out.
It is only reproducible if there is at least one beatmap imported.
Bisected to #9792 @smoogipoo.

**Comment by bdach** [comment]
This is known but not yet tracked.

**Comment by peppy** [comment]
For the test-side track, that sounds like an amazing fix (feel free to PR).

As for `TrackVirtual` itself: this is used in cases where beatmaps may not have an audio track (ie. all music content comes from hitsounds), so I don't think that's what we want. `TrackVirtual` is intended as a stand-in track which behaves as you'd expect from an actual track.
