### ISSUE TITLE
Difficulty adjust not working in multiplayer

### ISSUE THREAD

**Issue by Nikosgr121** [ppy/osu#11305]
**Describe the bug:**  i pick 7.5 AR map i change it in multy 10 AR and not workin

**Screenshots or videos showing encountered issue:** https://cdn.discordapp.com/attachments/776536792400134194/791989673043820575/unknown.png

**osu!lazer version:** latest  12/25/20

**Logs:**

**Comment by frenzibyte** [comment]
Will look into this one.

**Comment by Nikosgr121** [comment]
Tnx happy holidays!
