### ISSUE TITLE
[Feature/Question] Old data folder restore

### ISSUE THREAD

**Issue by Hexality** [ppy/osu#11327]
HI, came here to ask if there's any way of restoring my old osu!lazer folder, since I changed the default location to my osu! hard drive, I turned it into a portable folder. I've reformatted my pc 1h ago and when I tried to re-set the folder back to the portable, my notification center opened showing me an error, which said that the folder contained files and couldn't be selected, and then it created a temporary folder inside it instead, which gets deleted after closing the game.
Is there any way of restoring it? 
![image](https://user-images.githubusercontent.com/17398632/103159436-25409780-47a8-11eb-97ea-9215bc12bcaf.png)

**Comment by bdach** [comment]
You can edit `%AppData%/osu/storage.ini` and point it at the correct folder (guessing that it would be

```ini
FullPath = D:\osu!lazer
```

from the attached screenshot).

**Comment by Hexality** [comment]
![image](https://user-images.githubusercontent.com/17398632/103159515-2d4d0700-47a9-11eb-9471-727240d10d68.png)
thanks
