### ISSUE TITLE
Show score meter when HUD overlay is hidden

### ISSUE THREAD

**Issue by LeaPhant** [ppy/osu#11322]
The score meter should still be visible while the HUD overlay (accuracy, progress, combo etc.) is hidden. This would match stable behavior and is what most players expect. 

Could also be a toggle like this:

![image](https://user-images.githubusercontent.com/14080165/103151992-7db16e00-4783-11eb-90a5-150c0b4be35c.png)

**Comment by peppy** [comment]
We plan on giving more control over individual elements in a skin editor, rather than adding more settings and exceptions like this.

**Comment by bdach** [comment]
Let's track over at #4924 then if that's the intended direction.
