### ISSUE TITLE
Setting a keybind to horizontal scroll wheel causes a crash on linux

### ISSUE THREAD

**Issue by bob8677** [ppy/osu#11326]
**Describe the crash:** 
When setting a keybinding, the game crashes if I touch the horizontal scroll on my mouse. It also crashes on startup if I try to open it again. I had to delete client.db to start osu again.
**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/68208828/103158562-fd0c6500-47b6-11eb-979d-5bfd23a4f60a.mov

**terminal output:**
[error.txt](https://github.com/ppy/osu/files/5743577/error.txt)

**osu!lazer version:** 
2020.1225.0 - linux appimage

**Logs:**
[database.log](https://github.com/ppy/osu/files/5743573/database.log)
[network.log](https://github.com/ppy/osu/files/5743574/network.log)
[performance.log](https://github.com/ppy/osu/files/5743575/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5743576/runtime.log)

**Computer Specifications:** 
Distro: Arch 
Mouse: MX Master 2S

**Comment by bdach** [comment]
Do you mind attaching a `client.db` that crashes afterwards? Due to the specificity of the hardware needed to reproduce it'll be hard to fix this up otherwise, as there is no indication in any of the logs what possible unexpected value this secondary scroll wheel might have yielded.

**Comment by bob8677** [comment]
I added .txt to the end because github won't let me upload .db files
This is before the crash - [client.db.txt](https://github.com/ppy/osu/files/5743595/client.db.txt)
This is after the crash - [client.db.txt](https://github.com/ppy/osu/files/5743599/client.db.txt)

**Comment by bob8677** [comment]
Way to reproduce this without a mouse would be to run `sleep 5 && xdotool click 6` in a terminal and then start changing a keybind in osu within 5 seconds. Mouse buttons 6 and 7 are for horizontal scrolling.
