### ISSUE TITLE
Osu!lazer don't work

### ISSUE THREAD

**Issue by RedLogitech** [ppy/osu#11335]
I can't play anymore on Osu!lazer, I can't take new beatmaps, I can't play and I can't even connect to my Osu account. I've tried multiple times to delete the game and install it again but nothing changes, I can't do nothing, if someone get the same problem, did you found a solution. Thanks.

**Comment by peppy** [comment]
Please follow the template. We cannot help you with a report like this. You have given zero useful anything.
