### ISSUE TITLE
osu! is registered to open all file types on Android

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#11334]
**Describe the bug:** 

After installing the latest update, when opening most file types, osu! is presenting itself as an application that can open that file type. Notable examples are PDFs, APKs, etc.

Looking at osu!'s androidmanifest.xml, osu! is registered to open all mime types matching `application/*`

```xml
<intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <action android:name="android.intent.action.SEND"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <data android:mimeType="application/*"/>
    <data android:pathPattern=".*.osz"/>
    <data android:pathPattern=".*.osk"/>
</intent-filter>
```

[This](https://stackoverflow.com/questions/1733195/android-intent-filter-for-a-particular-file-extension) suggests to use `.*\\.osz` and to specify `android:scheme` and `android:host`

I believe that if you don't use backslashes, a file named `fileosz` would get matched in addition to `file.osz`. Some comments suggest using four backslashes, so test those two filenames with the modified androidmanifest.xml

**osu!lazer version:** 2020.1225.0

**Device information:**

Realme 6, Android 10
LG G Pad 8.3, Android 7.1.2

**Logs:**

Not needed as the issue is outside of osu!

**Comment by Susko3** [comment]
https://github.com/ppy/osu/blob/69fab7de7717e05948bde4239dd6724ed5e4628c/osu.Android/OsuGameActivity.cs#L19

This is the troubled line that is generating the androidmanifest.xml

**Comment by peppy** [comment]
Does this mean we should drop the mimetype specification completely and rely on path/pattern matching?

**Comment by bdach** [comment]
Looks like we might have to, judging from android docs. Apparently the data clauses in an intent filter are an "OR" not an "AND", which is dumber of the two choices if you ask me, but as it's android, I'm not sure I should be surprised at this point.

Not sure about two/four backslashes either. Will test later on windows.

**Comment by Game4all** [comment]
The intent filters probably need to be split as well since the `View` one will match exclusively with the URI components (host, scheme, pathPattern) and the `Send` one requires only the shared content's mime type.

**Comment by bdach** [comment]
I don't think there's a mime type that's safe to match on in our case? `application/zip` would probably be closest but not 100% there. It definitely can't be `application/*` as done currently due to reasons stated above.

**Comment by Game4all** [comment]
yeah `application/zip` is the closest MIME type out there for the archive types but we should probably add `application/octet-stream` as well because depending on where the files are stored / downloaded from, the files may flag as `octet-stream`. Altough I guess it's fine to have only `application/zip` registered in a first time to check things are going well and then add `octet-stream` if the need arises?

**Comment by Susko3** [comment]
Android (and all file file managers I've tested, including built-it Files app) don't treat `.osz` and `.osk` files as `application/zip`. They treat them as `application/octet-stream` -- this seems like a simple band-aid fix until we can get Android to recognize `.osz` as a file you can open with osu!

I've tried to get the intent filter to make Android treat osu! as `.osz` opener, but can't get it to work.

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/1705 is relevant here.

**Comment by Game4all** [comment]
To make things even worse, pattern matching on the URI may not work because content URIs don't always reflect the actual name / extension of the file, so the game may have to behave accordingly with only the MIME type being provided.

**Comment by Susko3** [comment]
Finally figured it out, string arrays are the devil. Using more than one `android:pathPattern` or `android:scheme` will break it.

So the new IntentFilters should be:
```cs
[IntentFilter(
        new[] { Intent.ActionDefault, Intent.ActionSend },
        Categories = new[] { Intent.CategoryDefault },
        DataScheme = "content",
        DataHost = "*",
        DataPathPattern = ".*\\\\.osz",
        DataMimeType = "*/*"
        )]
```

Four in total for two filetypes (`osz` and `osk`) and two schemes (`file` and `content`)

I feel like using mime type `*/*` is best, in case a file manager app misidentifies the file.

I'll make a PR in a bit. First time using this PR stuff on GitHub, so it'll take me a bit of time.

**Comment by Game4all** [comment]
Note that the game only handles content uris for the moment so that should only make two intent filters to commit. Also I think that the send intent should be moved to its own intent filter as the only thing used to match for those are the accepted mime types.

**Comment by Susko3** [comment]
Since Intent.ActionSend cannot use DataPathPattern, I'll be putting `application/octet-stream`. Should I also add `application/zip`? I think most file managers will use octet-stream for .osz files, and we don't want to receive random .zip files.

**Comment by bdach** [comment]
`application/octet-stream` is even more generic than `application/zip`. It's essentially a codename for "it's a stream of bytes but I don't know what the hell this actually is". I'm not sure there's much of a reason to receive the former but not the latter.
