### ISSUE TITLE
Osu!Lazer don't work

### ISSUE THREAD

**Issue by RedLogitech** [ppy/osu#11336]
I can't play anymore on osu!lazer, I can't play, can't take new beatmaps on osu direct or even connect to my osu account.

![Osu bug 1](https://user-images.githubusercontent.com/76672440/103186686-c40ce700-48c1-11eb-9cf6-03a5c31cb292.PNG)
![Osu bug 2](https://user-images.githubusercontent.com/76672440/103186693-c66f4100-48c1-11eb-9893-e7cda05b0a9b.PNG)
![Osu bug 3](https://user-images.githubusercontent.com/76672440/103186695-c8390480-48c1-11eb-9c45-0711b5a97917.PNG)

I'm on the Osu!Lazer 1225.0

C:\Users\\AppData\Local\osulazer\osu!.exe

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

**Comment by RedLogitech** [comment]
I've literally gived all the informations the template ask me but okay. I'll just stop playing Osu! faster and easier solution.

**Comment by peppy** [comment]
Logs are missing, the most important part of the template, which allows us to actually discern what your issue is, rather than guessing from pixels in screenshots. This sounds like a misconfigured ipv6 setup on your network (duplicate of #3507) on a quick check.

**Comment by RedLogitech** [comment]
What do you mean by logs ?

**Comment by Joehuu** [comment]
The part of the template you've deleted has the details:

![image](https://user-images.githubusercontent.com/35318437/103189739-f77c5100-4882-11eb-9f23-b9d7e2478e3c.png)

**Comment by RedLogitech** [comment]
Ah yeah sorry, I missunderstood, uhm wich file do you need ?

**Comment by Joehuu** [comment]
Just the `network.log` is fine in this case. If unsure for future issues, upload all of them.

**Comment by RedLogitech** [comment]
[network.log](https://github.com/ppy/osu/files/5745899/network.log) There is it ( Sorry for the time taken to send it )

**Comment by Joehuu** [comment]
Confirmed duplicate of https://github.com/ppy/osu/issues/3507. Can't do anything else here but to wait or change some settings on your end (like https://github.com/ppy/osu/issues/10920#issuecomment-731025695).

I have hit this issue very rarely in the past, just restarting the computer or reconnecting to the internet worked for me.

**Comment by RedLogitech** [comment]
I think I know why this isn't working, I'll try later cause now I can't. Thanks for the help :)
