### ISSUE TITLE
In-game leaderboard got grayed out and didn't update its values

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#11345]
**Describe the bug:** At the start of the match my panel in leaderboard became gray and did not update throughout the beatmap

**Screenshots or videos showing encountered issue:** 
![osu_2020-12-28_17-27-45](https://user-images.githubusercontent.com/53346335/103226390-ac227b00-4934-11eb-9223-07536f3a0b7c.png)

**osu!lazer version:** 2020.1228.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/5747897/runtime.log)
[network.log](https://github.com/ppy/osu/files/5747898/network.log)

**Comment by Gonzalo-Bruna** [comment]
shouldn't this issue be closed by #11351 ?
