### ISSUE TITLE
osu-lazer crashes instantly when loading an unranked map

### ISSUE THREAD

**Issue by SethBarberee** [ppy/osu#1134]
Version is the latest commit from master (if needed) (41072640)

Steps to reproduce:
* Be logged in to your account (I couldn't reproduce when I wasn't logged in)
* Select an unranked beatmap from the carousel in the song select screen
* Osu-lazer will crash with the following:

[log here](https://gist.github.com/SethBarberee/02197b5dfc7de3a225caeb0833d5ae73)

**Comment by swoolcock** [comment]
Which map was it?

**Comment by SethBarberee** [comment]
I noticed the problem with beatmap 1 (linked below) and then I verified with a different unranked map labeled beatmap 2 (linked below)

[beatmap 1](https://osu.ppy.sh/s/504005)
[beatmap 2](https://osu.ppy.sh/s/377440)

**Comment by swoolcock** [comment]
Can confirm that it crashes, but only when logged in.

**Comment by smoogipooo** [comment]
Have determined the cause of the issue, will be PRing a patch. Thanks @SethBarberee
