### ISSUE TITLE
osu!lazer screen bug.

### ISSUE THREAD

**Issue by index-cpu** [ppy/osu#11355]
![image](https://user-images.githubusercontent.com/74940490/103253028-67efa480-494d-11eb-80b0-474df2bc3dbc.png)

Everytime I join osu!lazer, this happens.

**Comment by Joehuu** [comment]
Please do the following:
1. Press WinKey+R
2. Type "dxdiag"
3. In the window that opens, click "Save All Information..."
4. Post it here.

**Comment by index-cpu** [comment]
Nevermind, I fixed it.

**Comment by Joehuu** [comment]
Can you explain how you fixed it, there have been like a few reports of the same thing (https://github.com/ppy/osu/issues/11192, https://github.com/ppy/osu/issues/11136, etc.) and the fix for them was to update drivers / change GPU.

**Comment by index-cpu** [comment]
I was missing some of the assets.
