### ISSUE TITLE
osu!lazer shows older version as the available update

### ISSUE THREAD

**Issue by Malmik** [ppy/osu#11352]
**Describe the bug:** 
Everytime I open osu!lazer, I get a notification stating that new update is available, but the version is actually older.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/30472695/103239899-2bbd4380-494f-11eb-81ec-b8418a12637a.png)

**osu!lazer version:** 
most recent

That was a joke: 2020.1228.0 (Linux)

**Logs:**
[network.log](https://github.com/ppy/osu/files/5748616/network.log)
[runtime.log](https://github.com/ppy/osu/files/5748617/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5748618/performance.log)
[database.log](https://github.com/ppy/osu/files/5748619/database.log)

**Comment by bdach** [comment]
This is because 2020.1228.0 was temporarily pulled due to some regression. Please stay tuned for another version in the coming days.

**Comment by Malmik** [comment]
Wow, that was fast, also thanks for the info.
Do you think I should open issue named "Osu doesn't compare it's version number to the most recent update"?

**Comment by bdach** [comment]
This is not required. Pulling builds is an exceptional situation, not something that ordinarily happens, and as such there is not much point in investing much time in handling this.
