### ISSUE TITLE
Recent Participants list does not show users anymore

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#11366]
**Describe the bug:** Downgraded to 2020.1225.0 to confirm, and it does work fine there, while in the latest release it doesn't

**Screenshots or videos showing encountered issue:** 
![osu_2020-12-29_18-00-16](https://user-images.githubusercontent.com/53346335/103296884-beb5b680-49ff-11eb-9f9f-a6e5ac9368f8.png)
**osu!lazer version:** 2020.1229.0

**Logs:**

[network.log](https://github.com/ppy/osu/files/5751286/network.log)
[runtime.log](https://github.com/ppy/osu/files/5751287/runtime.log)

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu/pull/11462.
