### ISSUE TITLE
Green and black artifacts when changing resolution.

### ISSUE THREAD

**Issue by n-loo** [ppy/osu#11378]
**Describe the bug:** 

Screen has green and black bars after changing resolution and after changing between fullscreen and windowed modes.
I am still able to move about the game screen but it is green and black. If I reopen the program it goes back to normal (i.e. without green/black bars) with whatever resolution I put it to. This occurs both when I've set windows to use the integrated graphics or the discrete graphics card.

System: 
(laptop with both discrete and integrated graphics cards) 
OS Name	        Microsoft Windows 10 Home
Processor	Intel(R) Core(TM) i7-10750H CPU
GPU                 Nvidia GTX 1650-TI max-q 

**Screenshots or videos showing encountered issue:** 

[screenshot](https://media.discordapp.net/attachments/253317809126375425/793557938219253790/unknown.png?width=1267&height=738)

**osu!lazer version:** 

2020.1229.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/5756233/database.log)
[network.log](https://github.com/ppy/osu/files/5756234/network.log)
[performance.log](https://github.com/ppy/osu/files/5756235/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5756236/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5756237/updater.log)

**Comment by peppy** [comment]
This is happening at a driver or hardware level. Please try updating your drivers to begin with.
