### ISSUE TITLE
main menu not loading without sudo

### ISSUE THREAD

**Issue by Alib234** [ppy/osu#11375]
**Describe the bug:** 
Main menu not loading without sudo
**Screenshots or videos showing encountered issue:**
[Screenshot](https://ibb.co/6mxhxW8)
**osu!lazer version:** 
2020.1204.0.0
**Logs:**
[Logs](https://paste.ubuntu.com/p/xC8D4yCJF5)
I'm on Arch Linux and lazer seems to not want to load the main menu without sudo and nothing really shows why, and no there is no errors in the terminal. I also tried other versions and it happens on every version of linux lazer I try.

**Comment by bdach** [comment]
I can assure you that I can run appimage on ubuntu without root.

Which user is the filesystem owner of the lazer files directory (`~/.local/share/osu`)?

**Comment by Alib234** [comment]
well for me the same thing happens on the appimage
`[alib234@Alib234PC ~]$ ls -l ~/.local/share/osu
total 37960
drwxr-xr-x 3 alib234 users     4096 12-30 18:16 cache
-rw-r--r-- 1 alib234 users   208896 12-30 18:17 client.db
-rw-r--r-- 1 alib234 users    32768 12-30 18:17 client.db-shm
-rw-r--r-- 1 alib234 users   103032 12-30 18:17 client.db-wal
-rw-r--r-- 1 alib234 users        8 12-30 18:17 collection.db
drwxr-xr-x 2 alib234 users     4096 12-30 18:16 exports
drwxr-xr-x 4 alib234 users     4096 12-30 18:16 files
-rw-r--r-- 1 alib234 users      452 12-30 18:17 framework.ini
-rw-r--r-- 1 alib234 users     1627 12-30 18:17 game.ini
drwxr-xr-x 2 alib234 users     4096 12-30 18:17 logs
-rw-r--r-- 1 alib234 users 38486016 12-30 18:16 online.db
drwxr-xr-x 2 alib234 users     4096 12-30 18:16 rulesets
drwxr-xr-x 2 alib234 users     4096 12-30 18:16 screenshots
`
doesn't look correct, but that's how it created

**Comment by bdach** [comment]
Looks correct to me? Unless `alib234` is the super user?

Either way we don't do anything special to change filesystem owner of the folder or anything of the sort, and there are no actual errors in the logs you've provided. I'm inclined to say this is going to be due to some misconfiguration in your setup; please debug this yourself.

Closing as there is not enough info to begin investigating.
