### ISSUE TITLE
Allow the use of custom paths for all skinning elements

### ISSUE THREAD

**Issue by TheWeatherKill** [ppy/osu#11383]
**Describe the new feature :** In osu! actually some skinning elements can be custom pathed like combo char, osu!mania notes, keys ... etc ...
It could be very interesting to expand this feature to all skinning elements for making skins a lot more easier to make and to modify.

**Proposal designs of the feature :** Instead of putting everything in the root folder of the skin, use the skin.ini file to describe path to every custom pathed elements and keep old behavior for old skin or lazzy skinners :smile:

- Add a section Paths in skin.ini file for interface and shared elements.
**Exemple :**
```ini
[Paths]
Cursor: cursor\cursor
Applause: sfx\applause
GradeSmallB: grades\anynamecanwork
```
- Add parameters to Mode focused elements on its own section
**Exemple :**
```ini
[CatchTheBeat]
Grape: CatchTheBeat\fruits\grape
GrapeOverlay: CatchTheBeat\fruits\grape-overlay
```

**Comment by peppy** [comment]
The whole concept of "paths" is going to be removed with the upcoming changes to skinning, so I'm not sure this is valid.

**Comment by TheWeatherKill** [comment]
Can I have more info on that ?

**Comment by Joehuu** [comment]
Not sure of the structure, but editing skins will only be done in the client. There'll probably be UI to filter elements per game mode and/or type (e.g. hitobjects, interface, sounds).

**Comment by TheWeatherKill** [comment]
ok thank 👍
