### ISSUE TITLE
Can't join or create multiplayer room on android

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#11385]
**osu!lazer version:** 2020.1229.0 (works on last release, maybe a manual setting again?)

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5758314/runtime.log) (when joining)

**Comment by bdach** [comment]
This is not the submission token. It's this line:

https://github.com/ppy/osu/blob/575a00dd7deafdc6a9194dec59d79737db44e0ad/osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs#L115

I guess `getRoomUsers()` timed out. Probably need to increase the timeout from 100ms?

**Comment by peppy** [comment]
@Joehuu was this once-off, or did it just occur once randomly?

**Comment by Joehuu** [comment]
It happens all the time.

**Comment by bdach** [comment]
On checking, being in multi-threaded mode seems to make this go away for me, which was perhaps to be expected (especially given that single threaded gives me just a little above 15fps).

**Comment by peppy** [comment]
Even at 15fps, it seems weird that we're hitting 100ms here. Is the overhead of starting an async operation that high on android? I'd be hesitant to blindly increase the timeout without understanding exactly where this time is being lost.

**Comment by bdach** [comment]
I have a pull I want to double-test on android this week still, so when I'm at it I'll poke more on an actual device and see what falls out.

**Comment by peppy** [comment]
@bdach this one still on your radar?

**Comment by bdach** [comment]
Correct. I just need to find time to look at it.
