### ISSUE TITLE
Compatibility issue with OBS Studio

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#11391]
**Describe the crash:** 
When you try to record osu!lazer(in fullscreen mode) with OBS set to "Capture specific window", when the game window lost focus, OBS will get black screen. And going back to the game crashes it.

**Screenshots or videos showing encountered issue:** 
Note that in 0:30, osu!lazer screen flashed in the OBS window
https://user-images.githubusercontent.com/50285552/103435820-27df3900-4c4f-11eb-9f2c-3aa117063eef.mp4

**osu!lazer version:** 
2020.1229.0
**Logs:**
[performance.log](https://github.com/ppy/osu/files/5758753/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5758755/runtime.log)
[crash.zip](https://github.com/ppy/osu/files/5758766/crash.zip)

**Computer Specifications:** 
OBS: 26.1.10 64 bit

**Comment by bdach** [comment]
I can capture on linux in the way mentioned above just fine, and the log shows no useful error messages. Please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by PercyDan54** [comment]
> I can capture on linux in the way mentioned above just fine, and the log shows no useful error messages. Please attach Windows Event Viewer info by performing the following steps:
> 
> 1. Type `Event viewer` in the Windows search bar (shortcut: Windows+S) and press Enter, or open the _Run..._ button (Windows+R), type in `eventvwr` and press Enter.
> 2. The _Event viewer_ window will appear. Expand _Windows Logs_ on the left and choose _Application_. It might take a while to load.
> 3. In the _Actions_ pane on the right click _Save All Events As..._, then choose a location to save to.
> 4. On the _Display Information_ popup, select the second option, then the checkbox to show all available languages, then _English (UK)_ (US would also do fine).
> 5. Append the resulting `.evtx` file to this issue.

[crash.zip](https://github.com/ppy/osu/files/5758766/crash.zip)

**Comment by bdach** [comment]
From the attached file:

> Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FF9879B1D5B (00007FF987820000) with exit code c0000005.

We've seen [many of these](https://github.com/ppy/osu/search?q=c0000005+is%3Aissue&type=Issues) and usually they indicate driver-level failures. Please try updating your graphics card drivers and seeing if they fix the problem.

Closing until there's conclusive proof that this is something the game actually needs to deal with.
