### ISSUE TITLE
Changes to beatmap control point lists can persist in beatmap cache

### ISSUE THREAD

**Issue by bdach** [ppy/osu#11408]
Originally spotted in https://github.com/ppy/osu/pull/11354, but this is a deeper issue. I don't believe this has been reported yet, quite amazingly?

This affects any mod that might want to change control points to alter gameplay, but also the editor. Reproduction scenario for the latter:

1. Choose map in song select
2. Edit said map
3. Change something very visibly in control points (e.g. set a ridiculous difficulty control point like 5x or something)
4. Quit out without saving
5. Play map
6. Changes to control points will persist in gameplay

We probably want to ensure proper change revert everywhere where this can be changed, i.e. via leasing or something (not sure if supported for `BindableList`?)

**Comment by peppy** [comment]
on exiting the editor, the (working) beatmap needs to be completely reloaded, bypassing any cache. we can't deal with these scenarios on a per-bindable level because things will just get too complex.

**Comment by bdach** [comment]
True; that should probably also be the case after exiting gameplay with any mod that implements `IApplicableToBeatmap` (or maybe some sort of new interface?) because those also potentially fiddle with control points (as the PR linked in OP does).
