### ISSUE TITLE
When selecting songs with multi mode difficulty, it have chance to change the selected mode.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#11406]
**Describe the bug:** When selecting songs with multi mode difficulty, it have chance to change the selected mode. especially if `show converted` is disabled.

**Screenshots or videos showing encountered issue:** https://streamable.com/42vf5c

**osu!lazer version:** 2020.1229.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5760317/database.log),[network.log](https://github.com/ppy/osu/files/5760318/network.log),[performance.log](https://github.com/ppy/osu/files/5760319/performance.log),[runtime.log](https://github.com/ppy/osu/files/5760320/runtime.log),[updater.log](https://github.com/ppy/osu/files/5760321/updater.log)

**Comment by frenzibyte** [comment]
Intended, see https://github.com/ppy/osu/issues/8838 and https://github.com/ppy/osu/issues/9017. Also please search for existing closed issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue).

**Comment by IkaWaAyuMu** [comment]
> Intended, see #8838 and #9017. Also please search for existing closed issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue).

I've search it, but I may not found that keyword, sorry.
