### ISSUE TITLE
my osu!lazer keeps freezing on a black screen and crashing

### ISSUE THREAD

**Issue by ChickenHumanPerson** [ppy/osu#11412]
So, basically whenever i try opening osu!lazer, it goes to a black screen or crashes upon opening

![Capture](https://user-images.githubusercontent.com/53623885/103472760-5f3d0b00-4d5f-11eb-9961-a2fff4cfa326.PNG)

Im Using Version 2020.1229.0

Logs:
[updater.log](https://github.com/ppy/osu/files/5761270/updater.log)
[database.log](https://github.com/ppy/osu/files/5761271/database.log)
[network.log](https://github.com/ppy/osu/files/5761272/network.log)
[performance.log](https://github.com/ppy/osu/files/5761273/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5761274/runtime.log)

My Specs:
CPU: Intel i5 9400f
GPU: NVIDIA GTX 1660
Ram: 32gb
System: Windows 10 (x64)

**Comment by peppy** [comment]
Could you please provide logs specifically after the crash? The ones you provided show the game running correctly.

Also why does your window decoration look like it's from windows 7? and why does the screenshot not contain your full screen?

**Comment by ChickenHumanPerson** [comment]
> Could you please provide logs specifically after the crash? The ones you provided show the game running correctly.
> 
> Also why does your window decoration look like it's from windows 7? and why does the screenshot not contain your full screen?

im not sure where to find the logs that happen after the crash, and i did screen shot the full screen cause it was working earlier but suddenly stopped working, and idk why the decoration looked like windows 7 there tbh

**Comment by peppy** [comment]
Sounds like the game might just be running at an unsupported resolution? Can you try hitting alt-enter?

**Comment by ChickenHumanPerson** [comment]
> Sounds like the game might just be running at an unsupported resolution? Can you try hitting alt-enter?

![osu lazer](https://user-images.githubusercontent.com/53623885/103473216-2ce1dc80-4d64-11eb-8170-c3408cbe889c.PNG)
i pressed alt-enter and it became windowed

**Comment by ChickenHumanPerson** [comment]
then crashed after

**Comment by peppy** [comment]
After it crashes, please attach the same log files you did above (specifically runtime.log)

A screenshot showing the crash window may also be helpful.

**Comment by ChickenHumanPerson** [comment]
> After it crashes, please attach the same log files you did above (specifically runtime.log)
> 
> A screenshot showing the crash window may also be helpful.

apparently it just fixed itself

**Comment by ChickenHumanPerson** [comment]
so thats good
