### ISSUE TITLE
Starting up lazer causing crash 

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#11414]
**Describe the crash:** 

I just start up lazer and it crashes without showing anything

**Screenshots or videos showing encountered issue:** 
N/A
**osu!lazer version:** 
Latest commit cd7a5ca and 2020.1229.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5762475/database.log)
[network.log](https://github.com/ppy/osu/files/5762476/network.log)
[performance.log](https://github.com/ppy/osu/files/5762477/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5762478/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5762479/updater.log)

**Computer Specifications:** 
Windows 10 Pro x64 20H2, i3-6100, GTX1050Ti, 8GB RAM

**Comment by frenzibyte** [comment]
```
2021-01-03 23:44:13 [error]: ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
2021-01-03 23:44:13 [error]: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
2021-01-03 23:44:13 [error]: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
2021-01-03 23:44:13 [error]: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
```

your database has blew up, do you recall performing any operations that caused the game to start behaving weirdly? might help figuring out how your database has been broken.

as for solution, there is no solution to this for now, you'll have to delete your database file `client.db` and start all over again

**Comment by Lolihunter1337** [comment]
@frenzibyte yea thanks i wiped my database and that fixes it. it happend a couple of times in the past for me. it seems to be happening more common after i import my skins from stable tho. but its way to inconsistent that i could point it to that

**Comment by frenzibyte** [comment]
this can be closed then, there won't be any point to keep this open anymore.
