### ISSUE TITLE
osu preview point dont match with my setting

### ISSUE THREAD

**Issue by Furozzu** [ppy/osu#11442]
video: https://streamable.com/lcxvv9

so, this thing really bugging me because preview point didnt match with my setting in-game, but on website and lazer is fine. this occasionally happen to me, especially when using long songs, and when i add red line in middle of the song for metronome reset

i wish this thing get fixed since it really bothering me a lot

**Comment by peppy** [comment]
This sounds like a stable issue. It is likely due to using a vbr track (which means the location may not be perfect). This isn't getting fixed in stable, but as you've noticed, works correctly in lazer, which will replace that version eventually.

**Comment by Furozzu** [comment]
oh i somehow fixed it

yeah it maybe because i using 320kbps with vbr track. and after i convert into 192kbps cbr, it got fixed

anyway thanks for the reply
