### ISSUE TITLE
Most-used BPM is incorrect

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#11446]
The longest-used BPM is not correct on lazer. Not a new bug, it was also here in previous versions.

lazer: ![afbeelding](https://user-images.githubusercontent.com/56885706/104051005-bde30880-51e7-11eb-887c-39f7df75ff6d.png) stable: ![afbeelding](https://user-images.githubusercontent.com/56885706/104051033-c63b4380-51e7-11eb-9323-c60bc89e80a7.png)
The 178 BPM part in this [map](https://osu.ppy.sh/beatmapsets/664522#osu/1406449) is also just one second long which makes it pretty obvious that something's wrong here. Bug appears on any map with BPM changes, most of them will be wrong.

version: 2021.109.0

**Comment by bdach** [comment]
This does appear to be the case. The "mostly" BPM is calculated thusly:

https://github.com/ppy/osu/blob/8a7a1fc40a6e2acc5a12de07dcd868fbeac8d0ee/osu.Game/Beatmaps/ControlPoints/ControlPointInfo.cs#L104-L109

The mode is taken over the set of timing points disregarding their duration which doesn't seem to make a whole lot of sense (if all timing points in a song have unique BPM, then the first one will be picked as you stated).
