### ISSUE TITLE
Editor crashing on enter if login overlay was previously opened

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#11449]
**Describe the crash:** 
Clicking on "edit" when the default OSU theme is playing causes the application to freeze and "no beatmap available" (top right). In this state, the application can even be minimized (sound distortion will begin), but upon reopening it will simply have an endless black screen. The error always occurs, even if you have downloaded maps.
**Screenshots or videos showing encountered issue:** 
![Screenshot_2021-01-09-06-31-09-27_25a1a32208bbcdc1d450b7aa854bb161.jpg](https://user-images.githubusercontent.com/59089206/104082154-d33a5000-5244-11eb-814f-cfe63aed230a.jpg)
**osu!lazer version:** 
2021.109.0 
Android 10

**Comment by bdach** [comment]
This has nothing to do with the "default theme" and in fact will be fixed by #11448.
