### ISSUE TITLE
Add "Use beatmap skin color" option

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#11458]
### Describe the new feature

> A independent option that allows osu! to use the colors from beatmap skin, not all sprites. 

### Proposal designs of the feature:

> Add an option that allows the player to toggle beatmap skin color.

### Reason

> The overall atmosphere (background, music, color) of some beatmaps is designed to be very immersive, but the embedded skin is hard to read. Allow users to use its color will be good.

**Comment by peppy** [comment]
Can agree with this one. I'd almost be for making this forced on, but I can already hear the mobs raging if such a decision was to be made.

To clarify: currently the beatmap skin checkbox toggles both skin and combo colours. This is proposing to split that out into two checkboxes to allow users to respect the mapper's combo colour choice without necessarily changing the skin visually.

**Comment by Mysfit** [comment]
I can work on this feature request. I've looked into it a little bit and think I have an idea of how to accomplish it. I'll just need to implement it and the new tests to see if my idea had any unintended effects.

_This is proposing to split that out into two checkboxes to allow users to respect the mapper's combo colour choice without necessarily changing the skin visually._ 
Would/should this also include allowing the player to use the selected beatmap's skin but with their selected skin's colouring (essentially the opposite of this request)? Or should selecting the "Use beatmap's skin" option force the beatmap's colouring to be selected as well.

**Comment by bdach** [comment]
> Would/should this also include allowing the player to use the selected beatmap's skin but with their selected skin's colouring (essentially the opposite of this request)? Or should selecting the "Use beatmap's skin" option force the beatmap's colouring to be selected as well.

Well, if there are to be two check boxes for this, then handling the skin on / combo colours off case should probably happen? Although at that point the question arises *which* combo colours to use as they technically *are* part of the skin, so I'm not entirely sure on that one.

**Comment by Mysfit** [comment]
If the checkbox follows the same naming style with something like "Beatmap colours" I think it would be a bit clearer, but players could assume that disabling the "Beatmap skin" option would disable the beatmap colours option by default as well.

I have the contributing guidelines pulled up and will read through it before starting, thanks!

**Comment by cainy-a** [comment]
I'd looked at doing this and got as far as adding a checkbox in the settings panel

**Comment by bdach** [comment]
@Mysfit If one checkbox being enabled would disable another, then I think we should be aiming for a dropdown instead maybe? The less potentially confusing UI interactions between controls, the better, I'd say.

**Comment by Mysfit** [comment]
That's a good point, I do think a dropdown could be a better option here if the checkboxes would be affecting each other. Perhaps it is be better to just implement the dropdown with the additional option of using the Beatmap's colors since the other scenario I mentioned (user's skin with beatmap's colours) isn't part of this request.

**Comment by peppy** [comment]
As a player, I wouldn't think of combo colours as "part of the skin", in the case of a beatmap and disagree with a dropdown.
