### ISSUE TITLE
[osu!Direct / Beatmap Listing] Reloading layers should not cover the search criteria area.

### ISSUE THREAD

**Issue by LamGC** [ppy/osu#11471]
**Describe the new feature:** 
When searching the beatmap, the reload overlay will be displayed to prevent changing the search criteria and wait for the search results to be displayed. 
Is this to prevent the server from being pressed by frequent changes in search criteria?
In my opinion, the search criteria area should not be covered to prevent frequent interruption of user's search criteria input and reduce the situation of invalid initial search (for example, the search results do not meet the needs of players or the results are few due to the selection of limited criteria).

**Proposal designs of the feature:** 
Reload overlay:
![Reload overlay](https://user-images.githubusercontent.com/16975255/104426831-7381d300-55bd-11eb-811d-533099a9737b.png)

In order to prevent frequent changes in search conditions from putting pressure on the server, I think we can execute the search results in order. When the user starts to input the search criteria, the search result area displays the reload overlap layer, but the search does not start. When the user stops inputting for a period of time (for example, 750ms), the search starts and does not respond to the change of the subsequent search criteria until the end of the search. After the current search, if the search criteria change compared with the previous search, the search is performed again.

Areas that need to overlap:
![Areas that need to overlap](https://user-images.githubusercontent.com/16975255/104426477-f3f40400-55bc-11eb-9c01-60f25c502c42.png)

Through delayed search, the unnecessary search requests caused by incomplete search conditions can be reduced.

**Comment by peppy** [comment]
Actually this change was just because it is quite hard to make it only cover the bottom part, due to how the layout code is structured. I'd hope we can do exactly what you suggest in a future update.

**Comment by LamGC** [comment]
> Actually this change was just because it is quite hard to make it only cover the bottom part, due to how the layout code is structured. I'd hope we can do exactly what you suggest in a future update.

Thank you for your reply. This is just a proposal. If it can't be realized at this stage, it can be ignored.
