### ISSUE TITLE
Cursor drops from 1000 fps to 0 fps when i use my tablet

### ISSUE THREAD

**Issue by Famine1234** [ppy/osu#11486]
**Describe the bug:** 
Whenever i open up osu!lazer i can use my mouse just fin i have 1000 fps for input. then when i try to use my tablet my frames for only the input drops to 0-10 fps.
**Screenshots or videos showing encountered issue:** 
![screenshot](https://user-images.githubusercontent.com/77460547/104639022-8bfcf680-566c-11eb-80f2-a21eafc1c58e.png)
![screenshot](https://user-images.githubusercontent.com/77460547/104639237-ccf50b00-566c-11eb-8c9e-1fc3d9b809b5.png)

**osu!lazer version:** 
latest

**Logs:**

[performance.log](https://github.com/ppy/osu/files/5816625/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5816627/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5816628/updater.log)
[database.log](https://github.com/ppy/osu/files/5816629/database.log)
[network.log](https://github.com/ppy/osu/files/5816630/network.log)

**Comment by bdach** [comment]
This is strangely suspicious. In order for us to be able to tell what sort of tablet it is, please attach DirectX diagnostic info by performing the following steps:

1. Press <kbd>Windows</kbd>+<kbd>R</kbd>, type `dxdiag` in the appearing window and press <kbd>Enter</kbd>.
2. You could be prompted if you'd want Windows to check if the device drivers are signed - there should be no harm in agreeing to that.
3. In the *DirectX Diagnostic Tool* window that will appear, click *Save All Information...* and choose a file to save to.
4. Attach the saved file to this issue.

Also, do you have any custom tablet drivers installed?

**Comment by Famine1234** [comment]
> 4. Attach the saved file to this issue.
> 
[DxDiag.txt](https://github.com/ppy/osu/files/5816776/DxDiag.txt)

> Also, do you have any custom tablet drivers installed?
zyes i have the xp-pen g640

**Comment by bdach** [comment]
Please try uninstalling/disabling the custom drivers and checking whether the input persists with them off.

**Comment by Famine1234** [comment]
> Please try uninstalling/disabling the custom drivers and checking whether the input issue persists with them off.

this didnt work it still is really slow

**Comment by bdach** [comment]
In that case I'm not sure what else to recommend, sorry. I can assure you tablets work on my setup just fine, and so this might be difficult to resolve without debugging on the same exact hardware as yours.

Is there a chance you might be able to upload a video of how this performance drop looks? Maybe that will provide some kind of clue.

**Comment by Famine1234** [comment]
> Is there a chance you might be able to upload a video of how this performance drop looks? Maybe that will provide some kind of clue.
Maybe but i dont know where to upload it. i tried uploading a video before but i just wouldnt work

**Comment by bdach** [comment]
If github doesn't want to comply with videos, then unlisted youtube/google drive/streamable link could do instead.

**Comment by Famine1234** [comment]
ok ill try

**Comment by Famine1234** [comment]
file:///D:/Genymotion/OBS%20Studios/obs-studio/bin/64bit/Videos/2021-01-14%2013-17-00.mp4

**Comment by bdach** [comment]
that's a local file path. nobody except you can access that.

**Comment by Famine1234** [comment]
oh
then how would i put it here with drive

**Comment by bdach** [comment]
you need to attach a web link to somewhere where the video can be viewed. please use google to find out how to do that.

**Comment by Famine1234** [comment]
https://kapwi.ng/c/ep4J1Q34

**Comment by peppy** [comment]
Could you please first of all try to update your tablet drivers (as in the real drivers, from your manufacturer)? This came up for another user in the past and they were faulty.

The general issue here is that your tablet driver is blocking when we request information from it. There's a high likelihood that this needs to be fixed at their end rather than ours. You could help us confirm this by opening Ctrl+F2 performance overlay, moving your cursor around via your tablet for 5 or 10 seconds, then attaching Performance.Input.log (from your lazer's Logs folder).

**Comment by Joehuu** [comment]
Closing since there is a tablet driver integrated now. If it still happens, it may be something specific to your system.
