### ISSUE TITLE
Scrolling on the timeline and play field acts differently

### ISSUE THREAD

**Issue by camellirite** [ppy/osu#11497]
**Describe the bug:** Scrolling on the timeline goes up in 148ms increments, scrolling on the play field automatically snaps to the ticks on the snap divisor, I feel like it should act that way for the timeline as well

Don't know if I should put this in another issue but flinging the timeline around makes scrolling on the play field stop until the timeline completely stops moveing, is it possible to make scrolling override that behaviour?

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=BMbN8q_fsDY

**osu!lazer version:** 2021.109.0

**Logs:** n/a

**Comment by peppy** [comment]
Do you have a precision scrolling device? If so, the timeline is going to be scrolling in precise amounts, with your input.

**Comment by peppy** [comment]
The second point you mention is an actual issue, for sure. I've been meaning to fix that for a while.

**Comment by camellirite** [comment]
precision scrolling device meaning a trackpad? I use a steelseries rival 600 which doesn't mention precision scrolling on the product page. I don't have the steelseries engine software which might cause an issue. I'm not sure otherwise.

**Comment by peppy** [comment]
It doesn't sound like it. So there may actually be an issue in that case, will look into it.

**Comment by peppy** [comment]
@camellirite could you please test this again? I made a couple of tweaks which may resolve all your issues. Please leave a comment if you are still encountering any unexpected behaviour and I will revisit.

**Comment by camellirite** [comment]
I updated to 2021.118.1, scrolling on the timeline is fixed, but im still unable to interrupt flick-scrolling on the timeline

**Comment by peppy** [comment]
Ah, apologies, the second fix is not merged yet. It will be live in the *next* release so check back again when that happens in a few days.

**Comment by camellirite** [comment]
it works in the latest version! thank you
