### ISSUE TITLE
Tourney Client videos pause

### ISSUE THREAD

**Issue by jibzballeza** [ppy/osu#11490]
So I just put videos in my tourney client and it plays fine until it pauses. The video is supposed to be a loop but it pauses after 20 seconds and takes a second and plays again. Do I just need to make the video longer or is there something wrong?

https://user-images.githubusercontent.com/41009875/104676846-32211e80-56b6-11eb-86d2-314727999c3d.mp4 - Shown here

**Comment by peppy** [comment]
This doesn't look like an official release of lazer. Have you made manual modifications? We can't troubleshoot unless you use the official release, sorry.

Also, please attach the video rather than a video or the video.

**Comment by jibzballeza** [comment]
I don't think I have made manual modifications, how do I get the official release? Also here is the video used https://www.youtube.com/watch?v=VPEw46y2hXc

**Comment by peppy** [comment]
How did you download and consume the video? If you are having issues with the video, I really need the raw mp4 file you are using, not a youtube link.

**Comment by jibzballeza** [comment]
Sorry for being clueless with what you needed. Here is the raw video
https://user-images.githubusercontent.com/41009875/104677646-c770e280-56b7-11eb-9446-06bc7a631023.mp4

**Comment by peppy** [comment]
Thanks. Indeed it looks like something specific to this video, which will require some investigation on the framework side of things. Instead of looping correctly, it thinks the video is super out-of-sync and attempts a seek:

```

[runtime] 2021-01-19 06:01:14 [verbose]: Video too far out of sync (18234.87777777778), seeking to 2501.3062883333296
[runtime] 2021-01-19 06:01:32 [verbose]: Video too far out of sync (18234.87777777778), seeking to 2500.451557666667

```

**Comment by peppy** [comment]
Further investigation shows the backwards seek is failing (but has a successful return code of 0) triggered from https://github.com/ppy/osu-framework/blob/ae5a10b6e6f7f7cfd7d3f0be9b1f1ce01857ada8/osu.Framework/Graphics/Video/VideoDecoder.cs#L458-L461. Weirdly, it works when called from the out-of-sync function, via the same call.
