### ISSUE TITLE
Playlist changes position during the transition between song selection and match settings

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#11509]
**Describe the bug:** As you transition between song selection and match settings, you may notice that the playlist moves to another position.

**Screenshots or videos showing encountered issue:** 
![playlist](https://user-images.githubusercontent.com/43073074/104811863-c1394e00-57fe-11eb-84b7-f26a60e4bdf3.gif)

**osu!lazer version:** 2021.109.0

**Comment by frenzibyte** [comment]
That looks like it's showing the room screen as you transition to song select
