### ISSUE TITLE
Change Mania's Scoring/Leaderboard System

### ISSUE THREAD

**Issue by xKibitz** [ppy/osu#11508]
As we all know, Mania scoring depends FULLY on Ratio and Accuracy. Mania is also the ONLY mode that caps score at 1m exactly. This has led to most leaderboards being covered with low ranking players, with good accuracy rather than good players using difficulty applying mods mostly DT being on the bottom. I would like to propose to have Mania revert back to the other modes scoring system where the leaderboards prioritize mods such as DT but still favour accuracy. An example of this would be:  Say, a 2 star map has a number of Full Marvelous (320) score, however with the new scoring system, a player with Full Marvelous but with DT has a much higher (not necessary)  score than the NM play. This is just a recommendation, I have no idea how much work this will take but this is just coming from a concerned player who is unsatisfied with looking at the same names on the leaderboard who I know I am better than but due to the setback of ratio, can't beat.

**Comment by peppy** [comment]
We are actually going in the opposite direction for leaderboards, likely removing mod multipliers from other rulesets too. This will be revisited later this year.
