### ISSUE TITLE
Check for update incorrectly reports running the latest release

### ISSUE THREAD

**Issue by camellirite** [ppy/osu#11524]
**Describe the bug:** Checking for updates prompts a notification saying it's running the latest release when its not

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=nEzpTWe_0SI

**osu!lazer version:** 2021.109.0

**Logs:** [logs.zip](https://github.com/ppy/osu/files/5827815/logs.zip)

**Comment by peppy** [comment]
That is the latest release. The changelog is wrong.
