### ISSUE TITLE
Failed to join and still in the room after that (multiplayer) 

### ISSUE THREAD

**Issue by elweojus** [ppy/osu#11549]
**Describe the bug:** 
This issue happened when i tried to join to a new big multi lobby but somehow failed, after sometime my user appeared in the room but I'm not in there

**Screenshots or videos showing encountered issue:** 
![osu_2021-01-19_20-53-32](https://user-images.githubusercontent.com/50848502/105117261-35dbe900-5a9a-11eb-845d-2d97e1ed815f.jpg)

**osu!lazer version:** 
2021.118.1
**Logs:**
This log are after the issue because I restarted the game before (idk if this helps)

[runtime.log](https://github.com/ppy/osu/files/5839710/runtime.log)

**Comment by bdach** [comment]
The error is nondescript here - this issue will probably need server log inspection to determine what might have gone wrong.

**Comment by peppy** [comment]
This was caused by server-side inconsistencies which have since been fixed.
