### ISSUE TITLE
When playing in a Playlist Multi Lobby in Taiko some maps don't End

### ISSUE THREAD

**Issue by Eeveelution** [ppy/osu#11545]
**Describe the bug:** 
I just tried playing the osu!taiko Winter 2021 Playlists, and the 2nd map you can play it perfectly, but the Map Itself never ends, making it impossible to finish the map and gain score off it,

**Screenshots or videos showing encountered issue:** 
I forgot to record or make screenshot anything but it can be replicated by playing the official taiko winter 2021 playlist's 2nd map till the very end.

**osu!lazer version:** 
2021.118.1
**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5836072/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5836073/updater.log)
[database.log](https://github.com/ppy/osu/files/5836074/database.log)
[network.log](https://github.com/ppy/osu/files/5836075/network.log)
[performance.log](https://github.com/ppy/osu/files/5836076/performance.log)

**Comment by smoogipoo** [comment]
Bumping this up to immediate priority.

Added a simple assert in `DHO.OnKilled()`:
```
[runtime] 2021-01-20 13:25:13 [error]: System.InvalidOperationException: DrawableDrumRoll
[runtime] 2021-01-20 13:25:13 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.OnKilled() in /home/smgi/Repos/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 704
[runtime] 2021-01-20 13:25:13 [error]: at osu.Game.Rulesets.UI.HitObjectContainer.removeDrawable(HitObjectLifetimeEntry entry) in /home/smgi/Repos/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 129
[runtime] 2021-01-20 13:25:13 [error]: at osu.Game.Rulesets.UI.HitObjectContainer.entryBecameDead(LifetimeEntry entry) in /home/smgi/Repos/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 102
[runtime] 2021-01-20 13:25:13 [error]: at osu.Framework.Graphics.Performance.LifetimeEntryManager.updateChildEntry(LifetimeEntry entry, Double startTime, Double endTime, Boolean isNewEntry, Boolean mutateActiveEntries)
[runtime] 2021-01-20 13:25:13 [error]: at osu.Framework.Graphics.Performance.LifetimeEntryManager.Update(Double startTime, Double endTime)
[runtime] 2021-01-20 13:25:13 [error]: at osu.Game.Rulesets.UI.HitObjectContainer.CheckChildrenLife() in /home/smgi/Repos/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 216
[runtime] 2021-01-20 13:25:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateChildrenLife()
[runtime] 2021-01-20 13:25:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```
`DrawableDrumRoll` expiring before all its nested hitobjects are judged - in particular the strong hits.

**Comment by bdach** [comment]
I guess at the point that they're expiring, it would make sense to just apply misses, right? Not like they can ever be hit past that point.

**Comment by bdach** [comment]
Looked into it some more and it's not as easy, obviously. What I've managed to ascertain, on top of the above, is that this code path is failing to do its job on missed *strong drum roll* ticks:

https://github.com/ppy/osu/blob/7da7079ef29d8f680549c8b82f224b95715641b8/osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRollTick.cs#L88-L91

which causes nested strong hits of strong ticks not to be judged, therefore blocking gameplay. Now *why* that might be, no idea. They're seemingly not hitting any of the two possible paths through which `CheckForResult()` can happen (not seeing any hits on `UpdateAfterChildren()` nor `OnKilled()`, at least not at the times I'd expect to see them).
