### ISSUE TITLE
Can't open .osz files from Chrome's downloads on Android

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#11558]
**Describe the bug:** 

Tapping on `.osz` files from Chrome Downloads on Android doesn't bring up osu! as an app that can open those type of files.

This is because our current intent filter only captures `content://` URIs that end in `.osz` or `.osk`
https://github.com/ppy/osu/blob/1ae3f1b9eb6048374a8c555f5dd8a21ad2b53ff6/osu.Android/OsuGameActivity.cs#L21-L22

But Chrome sends the following URI when tapping on files in Downloads: (the number is different for every file)
```
content://media/external/downloads/31299
```

Unfortunately, we can't capture those URIs with a simple path suffix filter. Luckily, when opening files from Chrome, the original MIME type that was sent by the server is used. For example, when downloading a beatmap from the official osu! website, the server serves the file with MIME type `application/download` and that same MIME type is passed on by Chrome when opening the file. This same MIME type also is passed on when sharing the file(s) from Chrome.

I think we should incorporate https://github.com/ppy/osu/issues/1705 (Official MIME types) use those MIME types when serving files from the beatmap download server and create a new intent filter with those MIME types.

**Comment by Susko3** [comment]
I see that you've marked this issue as `low-pririty` and I understand that this issue is that. As a temporary workaround, I suggest we add `application/download` to the share intent, so users can at least use the share option in Chrome to open beatmaps downloaded from the official website. That MIME type is uncommon and we can safely add it to our intent filter, without causing too much false positives.

We could also add a new VIEW intent filter with MIME type `application/download`, but I'm not so sure.

**Comment by bdach** [comment]
`application/download` seems way too broad to apply even if uncommon, same way that I was opposed to applying `application/octet-stream`.

**Comment by Susko3** [comment]
I think it's okay to be more broad in the share intent filter:

When a user shares a file, they expect a lot of apps to appear in the share sheet. I don't think that displaying osu! here (only for some MIME types!) is going to be much trouble for the user.

The bigger problem is osu! not appearing, because one can't import beatmaps from within the app. Telling users to load beatmaps from their file manager is a valid workaround, but I think that instructing them to share the .osz files to osu! is a more elegant and faster solution.

Using `application/download` in the view intent filter could be more problematic. osu! would likely be the only app that can open those files on a user's phone; thereby opening without confirmation on any `application/download` file. Since osu! is a demanding app, we don't want someone accidentally launching it.

**Comment by peppy** [comment]
My opinion is that as long as it is not triggering an automatic startup of the app, then it's fine to be more lenient in when we show the app. Until users complain about that at least.

**Comment by Susko3** [comment]
We currently have:

- `application/octet-stream`
- `application/zip`

I suggest we add:

- `application/download` (served from official osu!website)
- `application/x-zip` (used by Google Drive for zips that aren't `.zip` extension)
- `application/x-zip-compressed` (also a possible MIME type we could encounter)

I'll make a pull request if everyone is fine with that.

**Comment by peppy** [comment]
i think that sounds fine.
