### ISSUE TITLE
Osu lazer bug

### ISSUE THREAD

**Issue by UnoDaFirma** [ppy/osu#11555]
**Describe the bug:** 
osu is running with SDL restricts mouse cursor

that problem is happening at all new versions 
**Screenshots or videos showing encountered issue:** 
https://youtu.be/36Zac2I3YNA**osu!lazer version:** 
something like that
**Logs:**

**Comment by bdach** [comment]
You've taken the video from an existing closed issue (https://github.com/ppy/osu/issues/10927). I'm going to close this one and reopen that one instead.

Next time this happens, just post in the closed issue and we'll reopen it as well.

**Comment by UnoDaFirma** [comment]
didn't know that case already exists. i'm sorry 
and tank you for reopening that old one

**Comment by UnoDaFirma** [comment]
didn't that case already exists, I'm sorry.
and thank you for reopening the old one

**Comment by UnoDaFirma** [comment]
didn't know that case already exists, I'm sorry.
and thank you for reopening the old one
