### ISSUE TITLE
Fresh installing lazer on windows adds a Microsoft .NET shortcut to desktop

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#11554]
**Describe the bug:** ~Seems like it also doesn't add the lazer shortcut.~ Nevermind. May be .NET 5, but haven't done research.

**osu!lazer version:** 2021.118.1

**Comment by PercyDan54** [comment]
In my case it adds _both_ .NET and osu! shortcut

**Comment by Joehuu** [comment]
Seems to still happen.

Ref: https://osu.ppy.sh/comments/1469057 and me

**Comment by peppy** [comment]
Still to the same `createdump` target?

**Comment by peppy** [comment]
Can reproduce. I guess something was missed in the squirrel fix.

**Comment by peppy** [comment]
Should be resolved in the next build (see https://github.com/ppy/osu-deploy/commit/f2fe88980532ff381f84c83f64af684e0939a13d).
