### ISSUE TITLE
Menu Parallax going off screen

### ISSUE THREAD

**Issue by Joshua-Usi** [ppy/osu#11563]
**Describe the bug:** 
It appears that in the main menu the cursor is allowed to go out of the screen bounds. Due to this, it can cause the background image to move causing the black imageless background to show 

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/49742616/105444167-749fb800-5cc1-11eb-8155-8e2725d64fe0.mp4

**osu!lazer version:** 
2021.109.0

**Logs:**

**Comment by peppy** [comment]
This is likely a duplicate of https://github.com/ppy/osu-framework/issues/4134.
