### ISSUE TITLE
Non color skin has color in Lazer

### ISSUE THREAD

**Issue by Tresquel** [ppy/osu#11575]
**Describe the bug:** 
A non color skin in osu!lazer looks like it's a color one.

**Screenshots or videos showing encountered issue:** 
[video](https://youtu.be/vN6S3ZDDUo8)

**osu!lazer version:** 
2021.118.1

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5860205/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5860206/updater.log)
[database.log](https://github.com/ppy/osu/files/5860207/database.log)
[network.log](https://github.com/ppy/osu/files/5860208/network.log)
[performance.log](https://github.com/ppy/osu/files/5860209/performance.log)

**Comment by bdach** [comment]
You have beatmap skin colours turned on.

**Comment by Tresquel** [comment]
> 
> 
> You have beatmap skin colours turned on.

sorry i didnt notice this function was in the game

**Comment by bdach** [comment]
It's a recent addition.

**Comment by peppy** [comment]
I guess we should have applied a better default in migration for the last release to handle this (default for beatmap colour should have taken from the beatmap skin value).
