### ISSUE TITLE
Chat not scrolling itself anymore after switch out of mappool screen

### ISSUE THREAD

**Issue by akuponcture** [ppy/osu#11588]
**Describe the bug:** When the client switches from the Mappool to the gameplay screen, sometimes, the chat will stay at his current position and not scroll anymore, then you will have to manually scroll down to make it work again. But it doesn't do it all the time, I can't seem to figure out why it does that. Bug has been in the game forever i believe, and it is not only happening to me but rather everyone.

**Screenshots or videos showing encountered issue:** https://i.imgur.com/VzT442I.png
On the screenshot you can see the chat is still going below but decide to stick here

**osu!lazer version:** 2021.118.1

**Comment by peppy** [comment]
We've never seen this happen on official tournaments. Could you please provide a video of this occurring next time it does?

**Comment by akuponcture** [comment]
> We've never seen this happen on official tournaments. Could you please provide a video of this occurring next time it does?

In this clip you can see the chat going up so I had to scroll down when I realized it, it actually happens more than before nowadays. Probably happened 10 times in 3 matches
https://clips.twitch.tv/CrypticExuberantDogeBatChest

**Comment by peppy** [comment]
The clip you link is unfortunately no longer available..

**Comment by akuponcture** [comment]
> The clip you link is unfortunately no longer available..

I don't know who deleted it, i clipped it again. 
https://clips.twitch.tv/WanderingPleasantCobblerDogFace

Perma link: https://file.aku.lu/twitchclip.mp4

**Comment by frenzibyte** [comment]
Can see why this happens now, it's because of a too long message getting wrapped down as the chat contracts back, causing the chat to appear as if its scrolled up:

https://user-images.githubusercontent.com/22781491/106369136-f47fef00-635f-11eb-8ca1-124bf6eeb37c.mov

(video of me going frame-by-frame)

Will look at fixing this.

**Comment by akuponcture** [comment]
> Can see why this happens now, it's because of a too long message getting wrapped down as the chat contracts back, causing the chat to appear as if its scrolled up:
> 
>  Screen.Recording.2021-01-31.at.1.01.19.AM.mov 
> (video of me going frame-by-frame)
> 
> Will look at fixing this.

Thanks a lot! If you want to see more example you can access all the VODs here https://www.twitch.tv/customallosu
