### ISSUE TITLE
Settings Menubar Cursor Lacks Behind

### ISSUE THREAD

**Issue by WillMexe** [ppy/osu#11580]
**Describe the bug:** 
In the settings menu the bar at the side's cursor lacks behind what is shown on screen. This only happens if the previously selected section was above the one that was just selected. It doesn't happen if the newly selected is further up.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/NpJBx5DGCnw

**osu!lazer version:** 
2921.118.1

**Logs:**
[performance.log](https://github.com/ppy/osu/files/5860984/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5860985/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5860986/updater.log)
[database.log](https://github.com/ppy/osu/files/5860987/database.log)
[network.log](https://github.com/ppy/osu/files/5860988/network.log)

**Comment by bdach** [comment]
Already fixed in #9196, the fix will be out next release
.
