### ISSUE TITLE
Show amount of used keys/rows in the song overview for osu!mania.

### ISSUE THREAD

**Issue by bee395** [ppy/osu#11587]
### Problem:
When I select a level in Osu!mania I select them mostly on the amount of keys/rows are used in that level.
But to know the amount of keys that are used in that level. I need to start the level and wait until it's loaded.
If the level has more keys than I expected, I need to exit and select another level.

### Proposed solution:
I would like to see the amount of keys used in the selection overview, together with the BPM, Note Count and Note Hold Count.

**Comment by frenzibyte** [comment]
Duplicate of https://github.com/ppy/osu/issues/9453 along with https://github.com/ppy/osu/issues/5668 which would solve your issue even better.

Please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue).

**Comment by bee395** [comment]
Thanks, I was unable to find a duplicate issue.
Thanks for your help.
