### ISSUE TITLE
Seemingly "random" crash on startup

### ISSUE THREAD

**Issue by DomiZone1** [ppy/osu#11590]
**Describe the crash:** 
Starting up osu!lazer as per usual. I got through the startup sequenc i saw the main and ca 4 error logs popup and the game crashed. Starting it back up after that with no issue!

**osu!lazer version:** 
2021.118.1

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5863267/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5863268/performance.log)
[network.log](https://github.com/ppy/osu/files/5863269/network.log)
[database.log](https://github.com/ppy/osu/files/5863270/database.log)

**Computer Specifications:** 
CPU: AMD R7 1800X
GPU: NVIDIA GTX 1080ti
Ram: 16GB

OS: Linux Ubuntu 20.04

**Comment by peppy** [comment]
@DomiZone1 just to confirm: this was a once-off crash for you, not a common occurrence right?

**Comment by peppy** [comment]
On a quick check neither of these nullrefs look like thing which should be possible to throw. No idea how this one could happen...

The only suspicious thing is the bass fault on startup:

![image](https://user-images.githubusercontent.com/191335/105668524-d578fb80-5f20-11eb-8115-bee2bc554628.png)

It's likely the game was in a completely unexpected state of startup or shutdown or something local to your system causing this. If you find a way to reproduce, please leave a comment and we'll investigate further, but as it stands this is beyond our comprehension.
