### ISSUE TITLE
System.AccessViolationException when trying to record with OBS

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#11599]
**Describe the crash:** 
A System.AccessViolationException is thrown if you tab out of osu then come back. And followed by a crash
**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/50285552/105696759-b12c1780-5f3e-11eb-81c8-21cd607868a3.mp4
**osu!lazer version:** 
osu: latest
OBS: 26.1.1
NVIDIA driver: 461.09 (the latest I can get)
**Logs:**
nothing useful
**VS Studio output (Chinese):**
“System.AccessViolationException”类型的未经处理的异常在 osu.Framework.dll 中发生 
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

程序“[3244] osu!.exe”已退出，返回值为 -1073741819 (0xc0000005) 'Access violation'。
程序“[3244] osu!.exe: 程序跟踪”已退出，返回值为 0 (0x0)。

**VS Studio output (Google Translated):**
An unhandled exception of type "System.AccessViolationException" occurred in osu.Framework.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

The program "[3244] osu!.exe" has exited and the return value is -1073741819 (0xc0000005)'Access violation'.
The program "[3244] osu!.exe: Program Trace" has exited and the return value is 0 (0x0).

**Comment by smoogipoo** [comment]
Can you check on an older driver version? The latest NV drivers have been causing problems all around at the moment and it's hard to say what the cause is.

**Comment by PercyDan54** [comment]
> Can you check on an older driver version? The latest NV drivers have been causing problems all around at the moment and it's hard to say what the cause is.

Which one exactly?

**Comment by peppy** [comment]
Try going further back (jump back half a year or a year) and see if it still occurs. If you are willing to put in further effort, you can binary search the range between working and non-working to find the exact driver too.

**Comment by smoogipoo** [comment]
I'm able to reproduce this one.

**Comment by smoogipoo** [comment]
Can you confirm that this doesn't happen if you use Window Capture instead of Game Capture?

**Comment by PercyDan54** [comment]
> Can you confirm that this doesn't happen if you use Window Capture instead of Game Capture?

This does not happen if I have an exteral display connected

**Comment by LamGC** [comment]
> Try going further back (jump back half a year or a year) and see if it still occurs. If you are willing to put in further effort, you can binary search the range between working and non-working to find the exact driver too.

I tried to use the NVIDIA video card driver with version 445.75, and played a game with obs in the form of recording, but the problem did not recur.

Driver version: 445.75 ( According to the online information, it is speculated that this version will be updated in March 2020 )
osu version: 2021.118.1
OBS version: 26.1.1
Capture settings: OBS determines the OSU window in the form of matching window title through game source;  OSU played a game in full screen, borderless and window mode respectively.

**Comment by PercyDan54** [comment]
> > Try going further back (jump back half a year or a year) and see if it still occurs. If you are willing to put in further effort, you can binary search the range between working and non-working to find the exact driver too.
> 
> I tried to use the NVIDIA video card driver with version 445.75, and played a game with obs in the form of recording, but the problem did not recur.
> 
> Driver version: 445.75 ( According to the online information, it is speculated that this version will be updated in March 2020 )
> osu version: 2021.118.1
> OBS version: 26.1.1
> Capture settings: OBS determines the OSU window in the form of matching window title through game source; OSU played a game in full screen, borderless and window mode respectively.
> 
> > Due to some tedious reasons, I can't view the video provided, so I'm not sure if my steps are consistent with the video, sorry.

Did you tab out?

**Comment by LamGC** [comment]
> > > Try going further back (jump back half a year or a year) and see if it still occurs. If you are willing to put in further effort, you can binary search the range between working and non-working to find the exact driver too.
> > 
> > 
> > I tried to use the NVIDIA video card driver with version 445.75, and played a game with obs in the form of recording, but the problem did not recur.
> > Driver version: 445.75 ( According to the online information, it is speculated that this version will be updated in March 2020 )
> > osu version: 2021.118.1
> > OBS version: 26.1.1
> > Capture settings: OBS determines the OSU window in the form of matching window title through game source; OSU played a game in full screen, borderless and window mode respectively.
> > > Due to some tedious reasons, I can't view the video provided, so I'm not sure if my steps are consistent with the video, sorry.
> 
> Did you alt+tab out then back?

Yes, I often use this shortcut key to switch windows, and I also use this shortcut key to reproduce problems

**Comment by PercyDan54** [comment]
> > > > Try going further back (jump back half a year or a year) and see if it still occurs. If you are willing to put in further effort, you can binary search the range between working and non-working to find the exact driver too.
> > > 
> > > 
> > > I tried to use the NVIDIA video card driver with version 445.75, and played a game with obs in the form of recording, but the problem did not recur.
> > > Driver version: 445.75 ( According to the online information, it is speculated that this version will be updated in March 2020 )
> > > osu version: 2021.118.1
> > > OBS version: 26.1.1
> > > Capture settings: OBS determines the OSU window in the form of matching window title through game source; OSU played a game in full screen, borderless and window mode respectively.
> > > > Due to some tedious reasons, I can't view the video provided, so I'm not sure if my steps are consistent with the video, sorry.
> > 
> > 
> > Did you alt+tab out then back?
> 
> Yes, I often use this shortcut key to switch windows, and I also use this shortcut key to reproduce problems.
> 
> I can see the video you provided, and I am now trying to reproduce the problem according to the video process.
> 
> Update:
> According to the steps provided in the video, I can't reproduce the problem.
> Video: https://1drv.ms/v/s!AuZ8JMPu3cmega8qsHBA3o9DWtXFOQ?e=FP9Wv9

Questions: Are you using a laptop? If yes, did you use an external display?

**Comment by LamGC** [comment]
I tested it on a desktop computer. If necessary, I will use a laptop to test it later, but I am currently not sure if the graphics card driver has been updated.

**Comment by PercyDan54** [comment]
> I tested it on a desktop computer. If necessary, I will use a laptop to test it later, but I am currently not sure if the graphics card driver has been updated.

It may be related to graphic card output because laptops using iGPU while desktops use dGPU

**Comment by LamGC** [comment]
Can you tell me the graphics card settings on your laptop (only Nvidia graphics card or open all), and the type of graphics card used by obs (use Nvidia graphics card or intel graphics card)?

**Comment by PercyDan54** [comment]
> Can you tell me the graphics card settings on your laptop (only Nvidia graphics card or open all), and the type of graphics card used by obs (use Nvidia graphics card or intel graphics card)?

Both set to use NVIDIA GPU

**Comment by LamGC** [comment]
> > Can you tell me the graphics card settings on your laptop (only Nvidia graphics card or open all), and the type of graphics card used by obs (use Nvidia graphics card or intel graphics card)?
> 
> Both set to use NVIDIA GPU.
> But the integrated display is output by iGPU, external display output from dGPU
> [DxDiag.txt](https://github.com/ppy/osu/files/5893998/DxDiag.txt)

If I understand correctly, the notebook console is set to only independent graphics card, OBS uses independent graphics card to run, and so is the game.
The integrated graphics card used in the built-in display should be the reason for the notebook design, not that you have enabled the Intel graphics card, right?

Original: 微星控制台设置为独显模式，OSU 和 OBS 都用了独显，然后接入一个外屏，但又用内置显示器来显示，对吧？

**Comment by LamGC** [comment]
> > > Can you tell me the graphics card settings on your laptop (only Nvidia graphics card or open all), and the type of graphics card used by obs (use Nvidia graphics card or intel graphics card)?
> > 
> > 
> > Both set to use NVIDIA GPU.
> > But the integrated display is output by iGPU, external display output from dGPU
> > [DxDiag.txt](https://github.com/ppy/osu/files/5893998/DxDiag.txt)
> 
> If I understand correctly, the notebook console is set to only independent graphics card, OBS uses independent graphics card to run, and so is the game.
> The integrated graphics card used in the built-in display should be the reason for the notebook design, not that you have enabled the Intel graphics card, right?
> 
> Chinese: 微星控制台设置为独显模式，OSU 和 OBS 都用了独显，然后接入一个外屏，但又用内置显示器来显示，对吧？

Through the above environment, this problem can not be reproduced.
通过上述环境，未能复现这个问题。

## environmental information
osu version: 2021.118.1 ( Using NVIDIA graphics card )
OBS version: 26.0.0 x64 ( Using NVIDIA graphics card )
Graphics card: RTX 2070
Graphics driver version: 456.38 ( According to the network information, it will be released in September 2020 )
Display information: 1 internal display, 1 external display, copy mode (same display content)
Graphics hardware settings: turn off Intel graphics and use NVIDIA graphics only

**Comment by PercyDan54** [comment]
> > > Can you tell me the graphics card settings on your laptop (only Nvidia graphics card or open all), and the type of graphics card used by obs (use Nvidia graphics card or intel graphics card)?
> > 
> > 
> > Both set to use NVIDIA GPU.
> > But the integrated display is output by iGPU, external display output from dGPU
> > [DxDiag.txt](https://github.com/ppy/osu/files/5893998/DxDiag.txt)
> 
> If I understand correctly, the notebook console is set to only independent graphics card, OBS uses independent graphics card to run, and so is the game.
> The integrated graphics card used in the built-in display should be the reason for the notebook design, not that you have enabled the Intel graphics card, right?
> 
> Chinese: 微星控制台设置为独显模式，OSU 和 OBS 都用了独显，然后接入一个外屏，但又用内置显示器来显示，对吧？

我不是微星控制台，我是win10自带的图形设置

**Comment by LamGC** [comment]
> > > > Can you tell me the graphics card settings on your laptop (only Nvidia graphics card or open all), and the type of graphics card used by obs (use Nvidia graphics card or intel graphics card)?
> > > 
> > > 
> > > Both set to use NVIDIA GPU.
> > > But the integrated display is output by iGPU, external display output from dGPU
> > > [DxDiag.txt](https://github.com/ppy/osu/files/5893998/DxDiag.txt)
> > 
> > 
> > If I understand correctly, the notebook console is set to only independent graphics card, OBS uses independent graphics card to run, and so is the game.
> > The integrated graphics card used in the built-in display should be the reason for the notebook design, not that you have enabled the Intel graphics card, right?
> > Chinese: 微星控制台设置为独显模式，OSU 和 OBS 都用了独显，然后接入一个外屏，但又用内置显示器来显示，对吧？
> 
> 我不是微星控制台，我是win10自带的图形设置

唔，核显没关闭？win10自带的图形设置能设置啥。。。？
Well, the Intel graphics card isn't turned off? What are the settings in Windows 10?

**Comment by PercyDan54** [comment]
> > > > > Can you tell me the graphics card settings on your laptop (only Nvidia graphics card or open all), and the type of graphics card used by obs (use Nvidia graphics card or intel graphics card)?
> > > > 
> > > > 
> > > > Both set to use NVIDIA GPU.
> > > > But the integrated display is output by iGPU, external display output from dGPU
> > > > [DxDiag.txt](https://github.com/ppy/osu/files/5893998/DxDiag.txt)
> > > 
> > > 
> > > If I understand correctly, the notebook console is set to only independent graphics card, OBS uses independent graphics card to run, and so is the game.
> > > The integrated graphics card used in the built-in display should be the reason for the notebook design, not that you have enabled the Intel graphics card, right?
> > > Chinese: 微星控制台设置为独显模式，OSU 和 OBS 都用了独显，然后接入一个外屏，但又用内置显示器来显示，对吧？
> > 
> > 
> > 我不是微星控制台，我是win10自带的图形设置
> 
> 唔，核显没关闭？win10自带的图形设置能设置啥。。。？
> Well, the Intel graphics card isn't turned off? What are the settings in Windows 10?

osu和OBS设置成“高性能”
Set osu! and OBS to "High Performance"

**Comment by LamGC** [comment]
> > > > > > Can you tell me the graphics card settings on your laptop (only Nvidia graphics card or open all), and the type of graphics card used by obs (use Nvidia graphics card or intel graphics card)?
> > > > > 
> > > > > 
> > > > > Both set to use NVIDIA GPU.
> > > > > But the integrated display is output by iGPU, external display output from dGPU
> > > > > [DxDiag.txt](https://github.com/ppy/osu/files/5893998/DxDiag.txt)
> > > > 
> > > > 
> > > > If I understand correctly, the notebook console is set to only independent graphics card, OBS uses independent graphics card to run, and so is the game.
> > > > The integrated graphics card used in the built-in display should be the reason for the notebook design, not that you have enabled the Intel graphics card, right?
> > > > Chinese: 微星控制台设置为独显模式，OSU 和 OBS 都用了独显，然后接入一个外屏，但又用内置显示器来显示，对吧？
> > > 
> > > 
> > > 我不是微星控制台，我是win10自带的图形设置
> > 
> > 
> > 唔，核显没关闭？win10自带的图形设置能设置啥。。。？
> > Well, the Intel graphics card isn't turned off? What are the settings in Windows 10?
> 
> osu和OBS设置成“高性能”
> Set osu! and OBS to "High Performance"

英伟达控制面板中设置为“高性能NVIDIA处理器”还是电源选项设置为“高性能”电源计划？
Is the NVIDIA control panel set to "high performance NVIDIA processor" or the power option set to "high performance" power plan?

**Comment by PercyDan54** [comment]
> > > > > > > Can you tell me the graphics card settings on your laptop (only Nvidia graphics card or open all), and the type of graphics card used by obs (use Nvidia graphics card or intel graphics card)?
> > > > > > 
> > > > > > 
> > > > > > Both set to use NVIDIA GPU.
> > > > > > But the integrated display is output by iGPU, external display output from dGPU
> > > > > > [DxDiag.txt](https://github.com/ppy/osu/files/5893998/DxDiag.txt)
> > > > > 
> > > > > 
> > > > > If I understand correctly, the notebook console is set to only independent graphics card, OBS uses independent graphics card to run, and so is the game.
> > > > > The integrated graphics card used in the built-in display should be the reason for the notebook design, not that you have enabled the Intel graphics card, right?
> > > > > Chinese: 微星控制台设置为独显模式，OSU 和 OBS 都用了独显，然后接入一个外屏，但又用内置显示器来显示，对吧？
> > > > 
> > > > 
> > > > 我不是微星控制台，我是win10自带的图形设置
> > > 
> > > 
> > > 唔，核显没关闭？win10自带的图形设置能设置啥。。。？
> > > Well, the Intel graphics card isn't turned off? What are the settings in Windows 10?
> > 
> > 
> > osu和OBS设置成“高性能”
> > Set osu! and OBS to "High Performance"
> 
> 英伟达控制面板中设置为“高性能NVIDIA处理器”还是电源选项设置为“高性能”电源计划？
> Is the NVIDIA control panel set to "high performance NVIDIA processor" or the power option set to "high performance" power plan?
> （如果是英伟达控制面板设置为高性能的话，那我这边测试应该是没问题的了，其实换句话来说，无论哪边设置了高性能，都没啥问题，电源不影响显卡只影响性能，英伟达控制面板设置高性能就等于 OBS 和 OSU 都使用独显，没啥区别的吧）

N卡面板没动过

**Comment by bdach** [comment]
this is an english-speaking repository and issue thread. please use english.

**Comment by LamGC** [comment]
> this is an english-speaking repository and issue thread. please use english.

Sorry, I just hope to communicate with the author quickly to add the details of the question. There is no difference between the Chinese in the comment and the English translation attached. :O

**Comment by MiraiSubject** [comment]
It's not just OBS fwiw, managed to reproduce it using Discord as well by selecting osu-framework's/my project's visual tests as the application to stream. Stumbled upon this while trying to demo a component of my own project. 

I did manage to pull out a stacktrace on 2021.128.0 of osu-framework:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at osuTK.Graphics.ES30.GL.TexSubImage2D(osuTK.Graphics.ES30.TextureTarget2d, Int32, Int32, Int32, Int32, Int32, osuTK.Graphics.ES30.PixelFormat, osuTK.Graphics.ES30.PixelType, IntPtr)
   at osu.Framework.Graphics.OpenGL.Textures.TextureGLSingle.DoUpload(osu.Framework.Graphics.Textures.ITextureUpload, IntPtr)
   at osu.Framework.Graphics.OpenGL.Textures.TextureGLSingle.Upload()
   at osu.Framework.Graphics.OpenGL.GLWrapper.Reset(osuTK.Vector2)
   at osu.Framework.Platform.GameHost.DrawFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

```

![image](https://user-images.githubusercontent.com/803255/106368615-4ec28500-634b-11eb-914a-a6a5f01edc79.png)

NVIDIA Graphics Driver is 460.79

**Comment by PercyDan54** [comment]
Closing as seems resovled by driver update (never happened again)
