### ISSUE TITLE
Searching for a beatmap id in a different category makes the overlay load endlessly

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#11602]
**Describe the bug:** As title. For example, if you search for a ranked beatmap in the graveyard section using its id, the overlay loads endlessly.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/105699366-8377ac00-5f07-11eb-99dc-f4a80a9f8039.mp4

**osu!lazer version:** `2021.118.1`

**Logs:**
[network.log](https://github.com/ppy/osu/files/5866188/network.log) (everything seems normal?)

**Comment by frenzibyte** [comment]
Been happening multiple times for me while I was doing relevant work as well, will investigate this.

**Comment by frenzibyte** [comment]
Fwiw this isn't specifically about beatmap ID, triggering a transition between "found" and "not found" for 3 times will reproduce it:

https://user-images.githubusercontent.com/22781491/105769955-a6d64180-5f6f-11eb-91b5-ff76c5d36ea4.mov

PR incoming anyways
