### ISSUE TITLE
Game crashing on launch

### ISSUE THREAD

**Issue by Its-Dragon** [ppy/osu#11608]
Every time I launch the game it will load until the fps counter and other information counters appear in the bottom right and it will remain at a black screen and then it will close. Before it started doing this the game just randomly closed after changing some of the scaling settings and then it hasn't started since.

Edit: I have already tried completely reinstalling and it leads to the same issue.

**Comment by peppy** [comment]
Delete client.db from your lazer data folder.

**Comment by Its-Dragon** [comment]
I deleted client.db and it still does the same thing at launch

**Comment by frenzibyte** [comment]
Please attach your game logs, wherever you set your game location to be at, `%AppData%/osu` otherwise.

**Comment by Its-Dragon** [comment]
[database.log](https://pastebin.com/Dy9w4bBx)
[network.log](https://pastebin.com/62HZhWju)
[performance.log](https://pastebin.com/wEzHnBWj)
[runtime.log](https://pastebin.com/Uh2PtpUC)
[updater.log](https://pastebin.com/RTyNzhr6)

**Comment by frenzibyte** [comment]
Hmm.. for some reason BASS is initialized twice in a row:
```
2021-01-26 17:39:40 [verbose]: BASS Initialized
2021-01-26 17:39:40 [verbose]: BASS Version:               2.4.15.26
2021-01-26 17:39:40 [verbose]: BASS FX Version:            2.4.12.1
2021-01-26 17:39:40 [verbose]: Device:                     Speakers (Realtek High Definition Audio)
2021-01-26 17:39:40 [verbose]: Drive:                      {0.0.0.00000000}.{a7cb5e0a-3dc6-4c3f-bfb3-984cfc6daf2f}
2021-01-26 17:39:40 [verbose]: BASS Initialized
2021-01-26 17:39:40 [verbose]: BASS Version:               2.4.15.26
2021-01-26 17:39:40 [verbose]: BASS FX Version:            2.4.12.1
2021-01-26 17:39:40 [verbose]: Device:                     Speakers (Realtek High Definition Audio)
2021-01-26 17:39:40 [verbose]: Drive:                      {0.0.0.00000000}.{a7cb5e0a-3dc6-4c3f-bfb3-984cfc6daf2f}
```

Screen stuck at black with FPS counter probably means the intro track failed to start, can't remember if double BASS init would lead to it.

**Comment by Its-Dragon** [comment]
> Hmm.. for some reason BASS is initialized twice in a row:

> Screen stuck at black with FPS counter probably means the intro track failed to start, can't remember if double BASS init would lead to it.
Occasionally (before reinstalling) I could get to the main menu but it would crash if I clicked anything/interacted with anything but now it doesn't even get to the main menu.

**Comment by bdach** [comment]
There is still not enough information to go on here to reopen, but if you were able to get to menu before, then I'm thinking this might be another instance of https://github.com/ppy/osu/issues/6391 (see: nvidia graphics card in log). Please try updating your graphics drivers.

---

If that doesn't help, please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by Its-Dragon** [comment]
[Event Viewer File](https://drive.google.com/file/d/1j1sr_Flk99R7WdX3JaNyzdkl2_DbdrqX/view?usp=sharing)

**Comment by bdach** [comment]
Yep, it's an nvidia issue. Last error from today (timestamped 20:58):

```
Unable to recover from a kernel exception. The application must close.


Error code: 3 (subcode 7)
 (pid=1916 tid=22940 osu!.exe 64bit)

Visit http://www.nvidia.com/page/support.html for more information.
```

There is nothing we can do about this one except advise you to update graphics drivers again.

---

That said, going over the file I also found this one:

```
Exception Info: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (No such host is known.)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped)
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass100_1.<handleException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.GameHost.windowUpdate()
   at osu.Framework.Platform.SDL2DesktopWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args)
```

which is very worrying because it seems like a network exception that killed the game process, but there is no context as to *which one it is* at all... I would reopen for this but it's essentially looking for a needle in a haystack, so I'm not sure whether it's worth to?

**Comment by Its-Dragon** [comment]
I had a graphics driver update earlier and I installed it and then restarted my pc so I don't think it's that but I can try reinstalling it again and seeing if it fixes it. If it's the network exception then I am essentially screwed when it comes to that. I have no intention of searching for the needle in a haystack honestly. Thanks for the help.
