### ISSUE TITLE
Reimplement mania reversing capability

### ISSUE THREAD

**Issue by smoogipooo** [ppy/osu#1160]
Currently, it is broken in various ways. Scale shouldn't be used for this and was removed in https://github.com/ppy/osu/pull/1159.

There are a few aspects to this:
1) Have to invert the content in the columns separately from the hit objects.
2) For now, let's not worry about the designs from the default skin lining up - this needs to be fixed when we get to implementing skinning.
3) The origins for hit objects needs to be flipped somehow - mania uses TopCentre for notes which would affect judgement for reversed playfields. This could be done by passing in the Reversed bool to the hit objects.

**Comment by peppy** [comment]
moving to tomorrow
