### ISSUE TITLE
Selecting a settings menu always highlights the one above it

### ISSUE THREAD

**Issue by TheEpicRedstoner** [ppy/osu#11609]
**Describe the bug**
When selecting a settings menu it always highlights the one above it. This only happens when selecting a menu that's lower than the one already selected. Happens consistently with no change since I first installed lazer. Not a big game breaking issue, just something small that could probably be fixed so I posted it here.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/78019740/105830399-bf714680-5fc5-11eb-9a01-14f7462b6351.mp4

**osu!lazer version:** 
osu!lazer 2021.118.1

**Logs:**
Don't know if these will be useful at all but here you go:
[updater.log](https://github.com/ppy/osu/files/5872667/updater.log)
[database.log](https://github.com/ppy/osu/files/5872668/database.log)
[performance.log](https://github.com/ppy/osu/files/5872670/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5872671/runtime.log)

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu/pull/11259
