### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by MarbleMann** [ppy/osu#11619]
So i downloaded osu! from https://osu.ppy.sh/home/download and i scanned it for viruses and 1 engine flagged it, im probably overreacting but i just want to ask if its a False Positive or a  virus.

Virus scan: 
https://www.virustotal.com/gui/file/81f0717ef7933a3d8ad4c1a71d0d1e591819ef116ec28009012855818957179b/detection

**Comment by PercyDan54** [comment]
Should be in [osu-stable-issues](https://github.com/ppy/osu-stable-issues).
Anyway the 1/69 is definitely a false positive

**Comment by MarbleMann** [comment]
So i will not get a virus if i download it from there and run it?

**Comment by PercyDan54** [comment]
> So i will not get a virus if i download it from there and run it?

That's the official website and you can totally trust it.

**Comment by smoogipoo** [comment]
There's no virus, it's a false-positive.

**Comment by MarbleMann** [comment]
Okay thank you!
