### ISSUE TITLE
Lazer android control

### ISSUE THREAD

**Issue by Xsenoxsogolik** [ppy/osu#11629]
**osu standart**
I would like the same control as in the fan game "osu!droid", that is, one finger to enter on the screen, and the other to press in another part of the screen (this is like a replacement z and x). 
**osu!taiko**
It's easy, the drum is in the center (red notes), and outside the drum are blue notes
**osu!catch**
It's even easier than taiko, put your finger on the screen and come up with something with a boost
**osu!mania**
The hardest, but at the same time the easiest. Notes at the bottom and map from above

**Comment by bdach** [comment]
#4201
