### ISSUE TITLE
Perfomance issue

### ISSUE THREAD

**Issue by MikelvGP** [ppy/osu#11627]
**Describe the bug:** 
I wanted to write about this a month and a half ago, but now I am completely convinced that this is a bug. A month ago, I was playing Osu! lazer and started going through Cyberpunk 2077 with pain in my eyes. And then I came up with the idea to use the software overclocking, which is available in the video card settings. For Cyberpunk 2077, everything became more stable, and I was happy. After that, I decided to go to osu! lazer and saw a low fps. I immediately thought that this is most likely due to overclocking, but disabling it did not help. We are transported to our time. I decided to reinstall Windows, and I go to osu! lazer and see 1000fps without the slightest lag. I've already figured out exactly what it's worth to report this.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2021.129.0
**Logs:**

**Comment by MikelvGP** [comment]
Oh, I forgot about the characteristics of the computer.

**Comment by peppy** [comment]
There's nothing here we can act on, but thanks for your story.
