### ISSUE TITLE
On leaderboard, if cursor in on focused scoreboard, Horizontal scrolling is not allowed.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#11621]
**Describe the bug:** On leaderboard, if cursor in on focused scoreboard, Horizontal scrolling is not allowed so you can't scroll to watch others score while mouse is on focused scoreboard. This happened to mouse wheel scrolling and mouse drag scrolling shown in video.

**Screenshots or videos showing encountered issue:** https://streamable.com/4k2ifd

**osu!lazer version:** 2021.129.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5891800/database.log), [network.log](https://github.com/ppy/osu/files/5891801/network.log), [performance.log](https://github.com/ppy/osu/files/5891802/performance.log), [runtime.log](https://github.com/ppy/osu/files/5891803/runtime.log), [updater.log](https://github.com/ppy/osu/files/5891804/updater.log)

**Comment by peppy** [comment]
This is intentional currently, as the main panel may not fit vertically (try increasing your UI scale). If you have a better suggestion our ears are open.
