### ISSUE TITLE
osu lazer stopped working

### ISSUE THREAD

**Issue by lvnry** [ppy/osu#11638]
please help
this is a screenshot from crash [https://www18.zippyshare.com/v/e5ayzdrt/file.html](url)
i've installed .net 5.0.2
no logs available
osu stable is working fine 
this is my specs [https://www18.zippyshare.com/v/geI1siFC/file.html](url)

**Comment by peppy** [comment]
Sounds like you need to read the README and install dependencies for your outdated operating system.
