### ISSUE TITLE
Hide scoreboard automatically at each beatmap start

### ISSUE THREAD

**Issue by Janaijanai** [ppy/osu#11633]
**Describe the new feature:**  
sometimes we forgot scoreboard on, after playing some solo mode or previous less important games, but when its a serious match ( tournaments for example ) we struggle to hide it espescially when the map has no intro, then the map suddenly starts and players struggle to hide it, and for some players thats so distractful and affect their performance leading them to miss more.   

**Proposal designs of the feature:** 
So the idea is as the title describe, make it hide automatically at start and then players can decide to toggle it or not.
or when its toggled on, make it hide itself after 5 secs or so ...

**Comment by bdach** [comment]
lazer currently has no scoreboard outside of multiplayer (and it's not toggleable currently). Was this issue intended for stable, or is this a proposal for when the scoreboard is eventually added back? Or do you mean the HUD?

This might be eventually resolved by skin UI options.

**Comment by Janaijanai** [comment]
Ops yeah it was intended for stable sorry about that ( i couldn't see where it says feature requests only for lazer) so i assumed its stable requests

**Comment by bdach** [comment]
The proper place for stable *bug* reports is https://github.com/ppy/osu-stable-issues/. Feature proposals are not accepted as stable is feature-locked.
