### ISSUE TITLE
osu! crashes on startup on older Android versions

### ISSUE THREAD

**Issue by MishterKirby** [ppy/osu#11643]
**Describe the crash:** 
osu! crashes on startup when  running on Android 6.
**Screenshots or videos showing encountered issue:** 
![Screenshot_20210201-103751](https://user-images.githubusercontent.com/48867925/106489821-c9d68900-647a-11eb-905b-70504f2ba0e8.png)

**osu!lazer version:** 
2021.129.0
**Logs:**

[log.txt](https://github.com/ppy/osu/files/5905235/log.txt)

**Computer Specifications:** 
Motorola Moto G3 (osprey)

**Comment by MishterKirby** [comment]
Also happens on a generic tablet running Android 5

**Comment by Blue-Beaker** [comment]
Also crashes on android-x86 9.0 rc2 even with arm library support enabled

**Comment by bdach** [comment]
@MishterKirby there is no discernible error to follow up on in the attached log.

@Blue-Beaker please open a separate issue for this, with actual details, instead of just saying that it "crashes".

closing due to a lack of actionable information all around.
