### ISSUE TITLE
[Feature request] Implement GitHub DevSecOps pipeline

### ISSUE THREAD

**Issue by AleksIvanovSinglet** [ppy/osu#11668]
#### 1. Outstanding issues

- third-party dependent pipeline
- no code quality assessment
- no third-party dependencies version management
- no security vulnerabilities discovery
- manual and error-prone deployment process

#### 2. Proposed improvements

Introduce DevSecOps pipeline utilizing free licenses for industry-standard DevSecOps tools with GitHub Actions:

1. Continuous Integration

- [CodeQL](https://securitylab.github.com/tools/codeql) - GitHub Actions' own native industry-leading static analysis engine
- [Dependabot](https://dependabot.com/) - GitHub Actions' own native dependency version and security update service

2. Continuous Deployment

- Automatic release - gathering all necessary artifacts and release information, safely tagging and publishing a complete, [GitHub release in your repository](https://docs.github.com/en/github/administering-a-repository/about-releases)
- Automatic package deployment - seamless and safe deployment to any package management system (e.g. NuGet, npm, Maven etc.)

3. General

- CI/CD Documentation - complete, step-by-step guide for every feature
- Free support included (up to 1 year)

Aleks from [Pipeline Foundation](https://pipeline.foundation/)

**Comment by bdach** [comment]
> third-party dependent pipeline

And running on github action isn't third-party dependent? Any CI that isn't on servers we fully control is "third-party dependent".

> no code quality assessment

That's incorrect and you'd know it if you looked properly.

> no third-party dependencies version management

See above. We have dependabot hooked up.

> no security vulnerabilities discovery

See above. Security critical patches will presumably bubble down via dependabot which bundles changelog notes into PR descriptions.

> manual and error-prone deployment process

Very much not the case.

---

With all due respect - I don't have the slightest clue who you are, your github profile is barren enough to warrant suspicion, and this whole issue sounds like an unwanted sales pitch. To which the polite response is "thanks, but no thanks".
