### ISSUE TITLE
Unable to turn on raw input

### ISSUE THREAD

**Issue by r00ster91** [ppy/osu#11669]
**Describe the bug:** I am unable to turn on raw input. The button is grayed out.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/35064754/106650441-32b12480-6593-11eb-8a48-cccb4df24c55.png)

**osu!lazer version:** 2021.129.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5913976/database.log)
[network.log](https://github.com/ppy/osu/files/5913978/network.log)
[performance.log](https://github.com/ppy/osu/files/5913979/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5913980/runtime.log)

**Comment by bdach** [comment]
[Please search before opening an issue.](https://github.com/ppy/osu/issues/11242
)
