### ISSUE TITLE
Changing a mod customisation value causes errors at the beginning of gameplay

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#11660]
**Describe the bug:** If you choose a mod, modifying at least one of its customization values, the game returns various exceptions.

**Screenshots or videos showing encountered issue:** 
The example shows in order: no mods, difficulty adjust mod (default values), difficulty adjust mod (with 1 modified customisation)

https://user-images.githubusercontent.com/43073074/106580257-f903fd80-6541-11eb-8e54-de799f127b18.mp4

**osu!lazer version:** 2021.129.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5910058/runtime.log)

**Comment by peppy** [comment]
This is an unfortunate one. I actually had this in the back of my mind when implementing MessagePack but forgot to fix it before we went live. This will require a custom resolve to be implemented to handle bindable types, as we probably don't want to add framework-level MessagePack attributes (would be required to fix this).

**Comment by smoogipoo** [comment]
A thought that came into my mind a few minutes ago without requiring framework changes was to try serialising the bindable directly.

Something like:
```csharp
// Serialize
foreach (var (name, bindable) in ...)
    Settings[name] = JsonConvert.SerializeObject(bindable);

// Deserialize
foreach (var (name, bindable) in ...)
    JsonConvert.PopulateObject(Settings[name], bindable);
```

**Comment by peppy** [comment]
I've already added a custom resolver for the mod dictionary as a whole, though haven't finished implementation. This involves just adding one attribute in place. An alternative would be to write a full blown bindable resolver and load it on messagepack startup. Any preference?

![20210202 195119 (JetBrains Rider)](https://user-images.githubusercontent.com/191335/106590023-05af4280-6590-11eb-89cb-e6ff9ff30320.png)

**Comment by smoogipoo** [comment]
That can probably easily be extracted into such a bindable resolver later if need be anyway, so as you have it is a good path.
