### ISSUE TITLE
The new #mapping chat channel doesn't seem to be accessible from osu!lazer

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu#11672]
**Describe the bug:** 

A few days ago a [new chat channel (#mapping) was created](http://twitter.com/ppy/status/1355719502567153666) as some kind of "replacement" for #modhelp. This new #mapping channel does not seem to be accessible yet from osu!lazer tho however, and therefore making it impossible to chat on the channel either from the osu!lazer client or from the http://osu.ppy.sh/community/chat page (right now the only way to access #mapping is through the osu!stable client or through an external IRC program).

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/36564236/106791517-987ed880-6687-11eb-94fb-007bde760cc8.png)

**osu!lazer version:** 

2021.129.0

**Logs:**

*N/A*

**Comment by bdach** [comment]
The list of joinable public channels comes from web. I'm not sure of too many details there but it might just be a question of adding an appropriate database row to represent `#mapping` (or a migration to add one - although I'm not seeing any obvious channel seeding logic over in web), at which point it'll probably automagically work both on web and in lazer. Either way there's not probably much to implement client-side.

**Comment by peppy** [comment]
This should be resolved. The channel was marked as an incorrect type in the database.
