### ISSUE TITLE
Osu! Lazer randomly crashes/freezes

### ISSUE THREAD

**Issue by CommissarHeavy** [ppy/osu#11695]
Osu! Lazer randomly crashes or freezes either  on startup or in the menu. It seems to mostly happen when I move the cursor

Osu!Lazer 2021.205.1

Can't find the logs so I'll post the event viewer logs 

Application: osu!.exe
CoreCLR Version: 5.0.220.61120
.NET Version: 5.0.2
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFC856C01BF (00007FFC854F0000) with exit code c0000005.

Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5fd43c92
Faulting module name: nvoglv64.dll, version: 27.21.14.6140, time stamp: 0x600b1a92
Exception code: 0xc0000409
Fault offset: 0x0000000001182789
Faulting process ID: 0x5494
Faulting application start time: 0x01d6fcd3ae4415a7
Faulting application path: C:\Users\dermi\AppData\Local\osulazer\app-2021.205.1\osu!.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_aba80042aca9c3c9\nvoglv64.dll
Report ID: b1e9a6bb-0d4f-469b-ae45-797e3e45209b
Faulting package full name: 
Faulting package-relative application ID: 

Intel i7-7700K
GTX 1080 RoG Asus Strix
16GB RAM
OS Windows 10

**Comment by bdach** [comment]
This is an nvidia issue (which you would know if you searched existing closed issues) and there's nothing that we can recommend other than checking for device driver updates for your graphics card.

**Comment by CommissarHeavy** [comment]
I did update my drivers but that didn't fix it sadly, everything works fine on normal osu

**Comment by smoogipoo** [comment]
Probably related to https://github.com/ppy/osu/issues/10157 then. I.e. try disabling shadowplay.
