### ISSUE TITLE
Autopilot on Android(touch) seems not working

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu#11700]
**Describe the bug:** When i enable autopilot, it seems to not working properly.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/37479424/107178128-d75db700-6a16-11eb-8371-391afc31c92d.png)
It's hard to record video on the phone itself, so here is a screenshot.

There is a strange cursortrail on the screenshot.
If i click the circle with aim correctly, It seems to work, But If isn't the circle is getting missed.

**osu!lazer version:** 2021.205.1

**Logs:**

**Comment by Gabixel** [comment]
Apparently, you have to hit the objects even if you're using Autopilot (as described in the post).
I tried to record the issue for him:

https://user-images.githubusercontent.com/43073074/107192151-8be2e300-69ed-11eb-9c6a-98fe1df06c3a.mp4

**Comment by frenzibyte** [comment]
Seems to be simply related to touch input not being handled by `RulesetInputManager` on `AllowUserCursorMovement = false`, though I'm curious to know how it would do that given that hit objects or anything inside the input manager does not handle touch events, will investigate further as something sounds weird there.
