### ISSUE TITLE
Game doesn't connect to the internet

### ISSUE THREAD

**Issue by Cholapat** [ppy/osu#11714]
**Describe the bug:** 
I can't login or use the new built in beatmap listing. I can still connect and login to the normal osu! 

**Screenshots or videos showing encountered issue:** 
![osu_2021-02-09_03-38-40](https://user-images.githubusercontent.com/29303173/107345704-7622fb80-6a89-11eb-9ce4-a8ba98611bfc.jpg)
![osu_2021-02-09_03-46-33](https://user-images.githubusercontent.com/29303173/107345869-a66a9a00-6a89-11eb-9849-bfc788797462.jpg)

**osu!lazer version:** 
2021.205.1

**Logs:**

**Comment by peppy** [comment]
Please check https://github.com/ppy/osu/issues/3507 for a temporary workaround (involves fixing your ipv6 configuration, likely by disabling it).

**Comment by Cholapat** [comment]
> Please check #3507 for a temporary workaround (involves fixing your ipv6 configuration, likely by disabling it).
Sorry about that there must have been a lot of posts like this before but that has got to be the fastest response ever

**Comment by Cholapat** [comment]
Disabling ipv6 works for me
For people who don't know how to disable ipv6, type network connection in the start menu and click the first option
![image](https://user-images.githubusercontent.com/29303173/107461942-a5387c00-6b20-11eb-91e6-be5e7d3df5c1.png)

Right click the network adapter you use (usually Wi-Fi or Ethernet) and select properties
![image](https://user-images.githubusercontent.com/29303173/107462158-1b3ce300-6b21-11eb-91be-f2f7b7c428c5.png)

Uncheck the box for Internet Protocol Version 6 and click OK
![image](https://user-images.githubusercontent.com/29303173/107462216-3e679280-6b21-11eb-920f-afc14ea9dbd9.png)
