### ISSUE TITLE
Own user is included in each multiplayer/playlists participants list

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#11715]
**Describe the bug:** For some reason, when I load any participants list of a playlist (or multiplayer), I always see my user in the list (although I have not participated in any of these).

Doesn't seem to happen on dev server.

**Screenshots or videos showing encountered issue:** The video shows the example with playlists.

https://user-images.githubusercontent.com/43073074/107350676-02551300-6aca-11eb-9a99-f9e3d35d04f9.mp4

**osu!lazer version:** `2021.205.1`

**Comment by peppy** [comment]
This looks to be an issue at osu-web's end. I've opened an issue for tracking it https://github.com/ppy/osu-web/issues/7192.

**Comment by Gabixel** [comment]
Seems fixed? Checking the recent multiplayer/playlists rooms I no longer see my user in the ones I haven't participated in.

**Comment by frenzibyte** [comment]
Yep the underlying web issue is fixed and has been deployed, so I believe this can be closed.
