### ISSUE TITLE
Osu lazer wont launch

### ISSUE THREAD

**Issue by SinixMusic** [ppy/osu#11727]
When i install osu lazer, it installs. But when i try to ruin it, it only opens as a backround app in task manager.

[network.log](https://github.com/ppy/osu/files/5960675/network.log)
[performance.log](https://github.com/ppy/osu/files/5960676/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5960677/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5960678/updater.log)

version:2021.205.1

**Comment by frenzibyte** [comment]
From the logs, this seems to be stuck in the `Loader` screen, but it's weird that no window appears for the game, perhaps it died there. Could you check the Event Viewer for any possible errors there:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

*steps ~~stolen~~ borrowed from bdach*

**Comment by SinixMusic** [comment]
i can directly upload the file so i zipped it up
[events.zip](https://github.com/ppy/osu/files/5967746/events.zip)

**Comment by peppy** [comment]
In previous cases where we've seen this, it was a database issue (unable to load the intro beatmap). Before checking anything else, can you try moving away your `client.db` file and see if it helps?

**Comment by SinixMusic** [comment]
I tried moving it out of there and the issue is still happening.

**Comment by HeyItsJinx** [comment]
> In previous cases where we've seen this, it was a database issue (unable to load the intro beatmap). Before checking anything else, can you try moving away your `client.db` file and see if it helps?

Same thing with me. here are mine. 

[lazer wont work.zip](https://github.com/ppy/osu/files/6481319/lazer.wont.work.zip)

**Comment by frenzibyte** [comment]
Please report a separate issue, following the issue template along with the [contributing guidelines](https://github.com/ppy/osu/blob/7632b8621ebcc8a1d2af7c9c6cd08cf3a7f4a456/CONTRIBUTING.md).
