### ISSUE TITLE
Focused password text boxes don't update caps warning when pressing caps lock

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#11731]
Regressed in SDL, because of [this check](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Platform/SDL2DesktopWindow.cs#L835) since https://github.com/ppy/osu-framework/commit/63a6f13c1b6fb3567cf7887d0d2b1c0a2a00d9a1 (first added). Removing that check seems to not result in any input blocking (at least on windows), but returns the ability to bind it to something (like osuTK did).

The only usage of this in osu! is:
https://github.com/ppy/osu/blob/70924319e42d79194f1a7bd12a301a0312f8f9ec/osu.Game/Graphics/UserInterface/OsuPasswordTextBox.cs#L48-L53

**Comment by frenzibyte** [comment]
The way it currently updates the caps warning looks wrong already (what if caps lock was enabled before game starts, or while game unfocused), sounds like it should be updated by `Update()` instead.

**Comment by Joehuu** [comment]
> what if caps lock was enabled before game starts, or while game unfocused

the warning should only show when it's focused right? thats what the onfocus/onfocuslost logic does.

**Comment by peppy** [comment]
No idea why that check exists in the framework. Can probably be removed?

**Comment by frenzibyte** [comment]
> > what if caps lock was enabled before game starts, or while game unfocused
> 
> the warning should only show when it's focused right? thats what the onfocus/onfocuslost logic does.

Right, but that still doesn't fix the other mentioned case: focus textbox, unfocus game, change capslock state, return back. 

> No idea why that check exists in the framework. Can probably be removed?

As per what's mentioned in the OP, "Removing that check seems to not result in any input blocking (at least on windows), but returns the ability to bind it to something (like osuTK did).".

Though honestly not sure if that's something that should be done anyways, feels like unnecessary limitation.

**Comment by peppy** [comment]
I think binding to caps lock *should* be allowed. No idea what the "input blocking" part is.

**Comment by Joehuu** [comment]
If you missed the old commit I linked in the OP, the commit title/description and [the xmldoc](https://github.com/ppy/osu-framework/commit/63a6f13c1b6fb3567cf7887d0d2b1c0a2a00d9a1#diff-1e169a9ebe1ee6d7968965f06b761bcab80d14c87af16de2ac822608e5aa2dd7R257-R261) somewhat explains it. Not sure if it still applies to the current code.

**Comment by peppy** [comment]
Ah, I see. Will required further investigation, but i guess SDL sends a down when caps lock is in the "on" state, rather than treating it as a standard keypress?

**Comment by bdach** [comment]
As I stated [in this comment](https://github.com/ppy/osu-framework/pull/4310#issuecomment-806172515), this will work on windows now, but not anywhere else. Still requires a framework fix for a truly cross-platform implementation of `CapsLockEnabled` (most likely via `SDL_GetModState()`).
