### ISSUE TITLE
Song select hover effect spammed under certain condition when dragging

### ISSUE THREAD

**Issue by kindlyfire** [ppy/osu#11745]
**Describe the bug:**
In the song select menu, upon dragging with a start position in between or just on the border of two songs and moving up or down, the new song "pop" hover effect is "spammed". The effect shouldn't be played while dragging

**osu!lazer version:** 2021.212.0

**Comment by peppy** [comment]
I'm pretty sure this is a duplicate, I know this has been a long term issue.

**Comment by Joehuu** [comment]
It was only for hover sounds: https://github.com/ppy/osu/issues/4600.

https://github.com/ppy/osu/blob/0040f141320c8128fd02cf2822eaad6675e523fa/osu.Game/Screens/Select/Carousel/CarouselHeader.cs#L100-L110

`CarouselHeader` has yet to borrow that logic.

https://github.com/ppy/osu/blob/0040f141320c8128fd02cf2822eaad6675e523fa/osu.Game/Screens/Select/Carousel/CarouselHeader.cs#L100-L110

**Comment by peppy** [comment]
I'll take a look into this one. We probably want to move the carousel header's implementation into a custom `HoverSounds` implementation.
