### ISSUE TITLE
Classic mod isn't selectable as a mod for osu! ruleset on playlists

### ISSUE THREAD

**Issue by maotovisk** [ppy/osu#11746]
As the title says, when creating a playlist room the server returns the error "invalid mod for ruleset 'CL'".

![](https://i.imgur.com/Bkc0NGa.png)

[performance.log](https://github.com/ppy/osu/files/5969013/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5969014/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5969015/updater.log)
[database.log](https://github.com/ppy/osu/files/5969016/database.log)

os: Windows 10 PRO 20H09
build: 2021.212.0

**Comment by frenzibyte** [comment]
Yeah if I'm not mistaking, the classic mod support web-side hasn't been deployed yet.

**Comment by peppy** [comment]
Is deploying now
