### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by Afif1009** [ppy/osu#11749]
**Describe the bug:** 
Notifications show pings when downloading the beatmaps but after leaving it for quite awhile, I don't get ping that the beatmaps was installed or not. When I click on Notifications, It suddenly shows a lot of ping that beatmaps was finished installed. (Sorry for my english)

**osu!lazer version:** 
2021.212.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5969743/database.log)
[network.log](https://github.com/ppy/osu/files/5969744/network.log)
[performance.log](https://github.com/ppy/osu/files/5969745/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5969746/runtime.log)

**Comment by peppy** [comment]
This will be resolved via https://github.com/ppy/osu/issues/4811.

**Comment by Afif1009** [comment]
I mean the notifications in-games at the top left. Not outside the game.

**Comment by peppy** [comment]
Yes, correct.

**Comment by Afif1009** [comment]
Top right my bad.
