### ISSUE TITLE
Preview link tooltip when hovering on text in chat

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#11751]
I think it's sometimes good to know what website you're about to click into

Is it called embedded text btw? [example.com this]

**Comment by peppy** [comment]
Weird, i thought we already had this implemented.

**Comment by peppy** [comment]
We already have a full-screen dialog that pops up when you're about to exit the client - is this not sufficient? Can you better describe your use case?

![Uploading 20210212.141253 (dotnet).png…]()

**Comment by RaiLTC** [comment]
I find it weird that you have to click a link in order to see it (and to be honest I didn't even know to preview the link until you mentioned this). But that's just my personal opinion, I think showing a tooltip with the link in it is much simpler
