### ISSUE TITLE
Allow rebind of switch chat tabs keys

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#11753]
I personally find it uncomfortable to use CTRL, SHIFT and TAB keys to switch chat tabs (hand injury), I would personally use ALT + Arrow keys

Allow the same for https://github.com/ppy/osu/issues/10148

**Comment by peppy** [comment]
Is that a standard thing on windows? If not, I'd suggest you instead use an application to rebind this on your PC. We don't intend on supporting customising "platform" binds for now.

**Comment by peppy** [comment]
This doesn't look to be a common thing. Closing for reason above.
