### ISSUE TITLE
Audio Compatibility Mode

### ISSUE THREAD

**Issue by Fvern** [ppy/osu#11763]
Feature Request:
Add an equivalent of the 'Audio Compatibility mode' present in stable.

While I haven't done rigourous testing with audio recordings, I have done feeling-based comparisons many times, and I am very sure that the hitsound/audio latency I get with the new engine (audio compatibility mode off) is about 15ms worse.
With it I hit late without -15ms universal offset, and hitsounds feel noticibly delayed. 
Due to this, I've been playing with audio compatibility mode on in stable ever since it was a feature.

I assume that lazer uses the new engine, because I get a similar amount of latency when playing it. I need around -15ms UO and the hitsounds feel laggy. 
Having an audio compatibility mode would make it infinitely more playable for me and anyone else with the issue, and would probably make me start using lazer as a practice client now that the classic mod has been added.

**Comment by huupoke12** [comment]
Are you using any 3rd party audio driver? Some drivers which provide sound effect or like that, can cause more latency. Try uninstalling those driver (the default driver is the Microsoft driver).

**Comment by Fvern** [comment]
I am using the microsoft driver, and I have tried many other drivers (old realtek HD audio, latest version, and some pieced together realtek UAD)

**Comment by peppy** [comment]
This won't be coming back, sorry. We will potentially be adding newer lower latency pathways, but "legacy" mode isn't going to return.

**Comment by Fvern** [comment]
Lower latency pathways like WASAPI (exclusive) would indeed be a great alternative. Thanks for replying.
