### ISSUE TITLE
Cannot log into lazer on PC

### ISSUE THREAD

**Issue by GiantNuker** [ppy/osu#11765]
**Describe the bug:** 
Cannot log in to lazer. Only happens on desktop, and my phone can log in fine.
I can't actually say how long this has been broken for me, but its been for at least a few months, I'm assuming its not actually related to the version.

The logs show the following
```
2021-02-12 10:59:38 [verbose]: Request to https://dev.ppy.sh/oauth/token failed with System.Net.WebException: BadRequest.
2021-02-12 10:59:38 [verbose]: Response was: {"error":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
2021-02-12 10:59:38 [verbose]: Login failed!
```
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43734540/107762053-3ce4c880-6ce1-11eb-976a-3a3511001526.mp4

**osu!lazer version:** 267869bd0baaa274e40f3c5d5b01ed6255f78767
**Logs:**
[database.log](https://github.com/ppy/osu/files/5971395/database.log)
[network.log](https://github.com/ppy/osu/files/5971396/network.log)
[performance.log](https://github.com/ppy/osu/files/5971397/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5971398/runtime.log)

Edit: I deleted (well actually renamed) the game folder under .local, there are zero beatmaps, scores, etc, forgot to mention that...

**Comment by PercyDan54** [comment]
Can you log in with latest release?

**Comment by peppy** [comment]
It sounds like you are building the game yourself. If this is the case, you are likely attempting to login to your live game account. The debug version connects to a development server so you will need to create a new account.
