### ISSUE TITLE
Prioritize newest beatmap imports

### ISSUE THREAD

**Issue by KorFeN** [ppy/osu#11768]
**Describe the new feature:** 
I noticed while importing my beatmap library of 14000 beatmaps and heading to play some multiplayer, it wouldn't import the beatmaps which I was going to play in the multiplayer lobby because the beatmaps was pushed to the last place in the queue, I would suggest pushing the newest requested imports to the front of the queue. This is would also make the maps you're trying to download from the browser not be put in the last spot of the queue.

Or another way to fix it would be to have a separate queue for library imports which would be deprioritized if there was an item in the main queue.

**Proposal designs of the feature:** 
No new design needed.

**Comment by peppy** [comment]
Let's track this one under https://github.com/ppy/osu/issues/11198 as it is the same issue, manifesting in a slightly different way.
