### ISSUE TITLE
Reduce the footprint of the leaderboard during multiplayer gameplay

### ISSUE THREAD

**Issue by SevenChords** [ppy/osu#11779]
Make an option to automatically hide the multiplayer scoreboard (top left corner) **during gameplay** and show it during brakes, like there is for the Hud in general, since the multiplayer scoreboard can take up quite a large part of the screen, even at 0.8x ui scaling. I agree with your tweet about disabling it completely taking away from the multiplayer experience, but please make it either hide during gameplay or make it smaller/relocate it to a position where it doesn't take up that much screen space, it feels like it takes away more than the entire rest of the hud once 6+ people are in the room, and it can be really distracting to have that big colorful area on an otherwise completely black screen.

**Comment by frenzibyte** [comment]
Toggling visibility of the multiplayer scoreboard *may* be fine to have, but the reason you specified sounds more like the current displaying of the scoreboard itself is not good enough to be shown alongside other gameplay elements at all (hence your first suggestion of completely disabling it).

I believe what's mostly required for improvement would be supporting legacy scoreboard elements on legacy skins.

**Comment by peppy** [comment]
The multiplayer leaderboard has a collapsed design, which is intended to display during gameplay. This has yet to be implemented, but should free up the majority of available screen space.

**Comment by frenzibyte** [comment]
Task fulfilled via https://github.com/ppy/osu/pull/11832 (triage can't edit descriptions T_T)
