### ISSUE TITLE
Option to revert to old sound effects

### ISSUE THREAD

**Issue by TheEpicRedstoner** [ppy/osu#11774]
**Describe the new feature:** 
Nothing much to say really, just a simple option to enable the old sound effects would be appreciated.
**Proposal designs of the feature:** 
A simple settings option would probably work best.

**Comment by peppy** [comment]
Thanks for your feedback. We will not be offering this for now as the previous sound effects were placeholder.

There may come a time in the future where we offer different themes for the game, at which point it may become available as an easter egg, but this is a very low priority.
