### ISSUE TITLE
Customisation window position placed too far to the right side

### ISSUE THREAD

**Issue by BlauFx** [ppy/osu#11775]
**Describe the bug:** The customisation window is placed too far to the right side, which looks cut off.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/34138240/107860098-bf829a80-6e3d-11eb-8f56-4e7b26d15b9d.mp4

**osu!lazer version:** 2021.212.0

**Comment by Joehuu** [comment]
Already fixed in https://github.com/ppy/osu/pull/11770, need to wait for next release.
