### ISSUE TITLE
change directory issue

### ISSUE THREAD

**Issue by dragondemon111311** [ppy/osu#11773]
i cant change directory for osu!lazer

![image](https://user-images.githubusercontent.com/45144330/107845482-4f105500-6e0e-11eb-8117-2129b12ac2a6.png)

osu!lazer version:2021.212.0.0
LOG: 
[database.log](https://github.com/ppy/osu/files/5975330/database.log)

**Comment by frenzibyte** [comment]
Duplicate of https://github.com/ppy/osu/issues/9746. For now keep trying until it works.

**Comment by dragondemon111311** [comment]
> Duplicate of #9746. For now keep trying until it potentially works.

wait that will actualy work?

**Comment by frenzibyte** [comment]
That's the only way for now, or wait until the underying issue is solved (by moving to a better DB system).
