### ISSUE TITLE
Spinners should not be highlighted in editor. 

### ISSUE THREAD

**Issue by c-sig** [ppy/osu#11788]
It really doesnt serve much purpose since you can see spinner count on song select (if you're looking to see if there are any) and is an eyesore.
![image](https://user-images.githubusercontent.com/61018516/107974039-f6e57880-6ff0-11eb-98f3-1bf6c8c59be2.png)

Lazer Build 2021.212.0

**Comment by Joehuu** [comment]
It probably is intentional as there is a plan to support https://github.com/ppy/osu/issues/7003.

**Comment by c-sig** [comment]
holy shit that sounds good, thanks for pointing me to the thread
