### ISSUE TITLE
Mouse input rejected momentarily at the beatmap start fade and at the end of break sections

### ISSUE THREAD

**Issue by integerrr** [ppy/osu#11813]
**Screenshots or videos showing encountered issue:** 

_**1. Beatmap start fade**_

https://user-images.githubusercontent.com/7279624/108273597-a6465a80-716b-11eb-9a2d-b0302fef37a9.mov

_Note that I was moving the mouse in circular pattern the whole time during the fade, the stopping wasn't me_

_**2. End of break sections**_

https://user-images.githubusercontent.com/7279624/108274339-ab57d980-716c-11eb-95ee-d4f90b2fbca6.mov

_Again the stopping of cursor spin is not me_

**osu!lazer version:** 2020.212.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5998918/database.log)
[performance-audio.log](https://github.com/ppy/osu/files/5998920/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5998921/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5998922/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/5998923/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5998924/runtime.log)

**Helmet:** I tried searching for this issue for about 15mins with different terms like input cursor freeze stop reject etc and nothing, if this actually is a duplicate issue please forgive me, I did try

**Comment by bdach** [comment]
I have no idea what I'm supposed to be looking at in the first video. In the second, it's clearly visible on the key overlay that there's a broken press on the spinner.

I'll give you a chance to attempt to explain, but this does not look like an actual issue to me right now.

**Comment by integerrr** [comment]
Focus on the the cursor alone and disregard all other input. 

In the first video, every time I hit retry I immediately start cursor spinning and never stopped mouse movement, this is attempting to capture the moment when the mouse input stopped registering in-game. As can be seen from the video, after the screen faded to black, in every instance of retrying there's a split second where the cursor completely stopped, however I haven't stopped moving my mouse.

In the second video, disregard everything about the spinner and look at 0:13 (my bad I didn't cut the video short), when the countdown for the break section finishes the cursor is again stopped in place whereas I haven't stopped my mouse movements.

Its not game-breaking but it is annoying as a mouse player, also apologies for not giving a better explanation of the videos, I hope you can understand what I'm trying to get at here

**Comment by peppy** [comment]
does turning off cursor confining fix this? what operating system?

**Comment by integerrr** [comment]
Turning off cursor confining did fix it, it's mac os 10.15.7.
running exclusive fullscreen also fixes it independent of cursor confining setting, which probably means this issue can be closed but you be the judge

**Comment by smoogipoo** [comment]
Tracked framework-side in https://github.com/ppy/osu-framework/issues/4086
