### ISSUE TITLE
raw input broken on windows 10

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#11815]
**Describe the bug**
Enabling Raw Input causes the mouse cursor to completely stop moving. I can only fix it by resetting raw input back to normal using control alt R.
Happens in all screen modes. One week old install of windows. 

**Screenshots or videos showing encountered issue**
https://streamable.com/qf6yi8

**osu!lazer version**
2021.212.0 (just tested latest and updated logs)
edit: if i remember correctly it was fine before 2021.205.1

**Hardware**
ASUS Strix B550-F GAMING
AMD Ryzen 5 3600
ASUS Strix GeForce RTX 3080
Sabrent Rocket 2TB NVMe
16GB DDR4
Windows 10 Pro for Workstations 20H2 (19042.804)
NVIDIA Game Ready Driver 461.40
AMD B550 Chipset Drivers 2.13.27.501
Razer Input Device Driver 10.0.15063.0

**Logs**
https://cdn.discordapp.com/attachments/303568612025696263/811739174721421312/logs.zip

**Comment by peppy** [comment]
what input device? what driver?

**Comment by ThatsNiceGuy** [comment]
razer deathadder elite on normal usb, no hub, on the mobo's ports.

**Comment by peppy** [comment]
Let's track via https://github.com/ppy/osu/issues/11815.
