### ISSUE TITLE
Cursor lag even when outside of vsync

### ISSUE THREAD

**Issue by integerrr** [ppy/osu#11814]
**Describe the bug:** 
The in-game cursor is always drawn behind the actual position of the actual cursor, even when the frame limiter is set beyond vsync

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/7279624/108278973-c5e18100-7173-11eb-8ae0-249ffdddd76b.mp4

Can clearly see the difference in position if viewed in 0.25x speed, the OS cursor is near realtime/actual cursor position

**osu!lazer version:** 2020.212.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5999064/database.log)
[network.log](https://github.com/ppy/osu/files/5999065/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/5999066/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5999067/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5999068/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/5999069/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5999070/runtime.log)

**Helmet:** Tried search terms like cursor lag input lag vsync performance etc, please forgive me if its a duplicate

**Comment by bdach** [comment]
How are you capturing this "realtime" cursor position, exactly?

**Comment by integerrr** [comment]
I was merely capturing both the in-game cursor and the OS cursor, which, the latter has a negligible input lag

**Comment by peppy** [comment]
means your game probably isn't running exclusive fullscreen

please check back in a few months and see if things are better.
