### ISSUE TITLE
Cannot change sensitivity: Turning on "Raw Input" locks mouse

### ISSUE THREAD

**Issue by Duncadoodle** [ppy/osu#11828]
Cannot change sensitivity in my Osu!Lazer. I have to turn on "Raw Input" to change the slider, but when toggling the option, it locks my cursor.

https://user-images.githubusercontent.com/79281420/108412323-590bcc80-71ef-11eb-9d48-b759a4e59498.mp4

2021.212.0
[database.log](https://github.com/ppy/osu/files/6005474/database.log)

**Comment by peppy** [comment]
duplicate search first
