### ISSUE TITLE
Performance issues on ArchLinux with Nvidia GPU: Low draw fps count on multithread

### ISSUE THREAD

**Issue by jonathannerat** [ppy/osu#11829]
Just after launching the game I get really low **draw** fps counts, about 9 fps (see screenshots), meanwhile **audio** and **input** are at 1k fps and **update** sometimes reaches 2k fps. This is with Threading Mode set to multithread. When I change this setting to single thread, all of the above get fixed at 12-13fps (that is, **draw** rises a bit) which which I found weird.

As stated in the title, I'm running ArchLinux, kernel v4.10.15, nvidia drivers v460.39

**Screenshots or videos showing encountered issue:** 
![Start screen (Multithread)](https://qu.ax/Xz2.png)
![idem (Singlethread)](https://qu.ax/xh4.png)

**osu!lazer version:** 

I have tried both [osu-lazer-git](https://aur.archlinux.org/packages/osu-lazer-git/) and [osu-lazer-bin](https://aur.archlinux.org/packages/osu-lazer-bin/) from the AUR. The former builds from master branch of this repository, the later pulls the latest AppImage, also from this repo. It happens with both of them, the logs and screenshots are from the AppImage v2021.212.0.0

**Logs:**
[logs](https://qu.ax/8CB.tar.gz)

**Comment by jai-x** [comment]
From your `runtime.log` file:

```log
2021-02-18 21:59:03 [verbose]: GL Renderer:                llvmpipe (LLVM 11.0.1, 256 bits)
```

Something in your graphics stack or system is misconfigured to be using `llvmpipe` instead of your actual graphics card renderer.
This isn't really a bug with osu!lazer so I'm not sure we can help that much.

**Comment by jonathannerat** [comment]
Thank you!

Just for some closure, turns out I had and `xorg.conf` file in `/etc/X11/` that shouldn't have been there (maybe I created it while playing with `nvidia-settings` or `nvidia-config`). I just removed that file, rebooted, and everything works perfectly now.
