### ISSUE TITLE
Some score meter types are ordered differently

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#11825]
**Describe the bug:** For some reason, the two types of score meter have some of their variants ordered differently.
(e.g. 'Colour' has `left+right` before `bottom`, but for 'Hit Error' these are reversed)

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/43073074/108338874-09210b80-71d7-11eb-8f2a-79b61aeefe5a.png)

**osu!lazer version:** 2021.212.0

**Comment by frenzibyte** [comment]
Nothing more than it just being unordered in enum definition:
https://github.com/ppy/osu/blob/46b67dd7bc05b4768f89f8569e518d34a882b64f/osu.Game/Configuration/ScoreMeterType.cs#L13-L23

https://github.com/ppy/osu/blob/46b67dd7bc05b4768f89f8569e518d34a882b64f/osu.Game/Configuration/ScoreMeterType.cs#L25-L35
