### ISSUE TITLE
Can't get out of replay

### ISSUE THREAD

**Issue by coinworld** [ppy/osu#11837]
**Describe the bug:** 
I can't get out of replay either using pause key(Esc or something else) or on-screen button

**osu!lazer version:** 
2021.219.0 on linux

**Comment by peppy** [comment]
For now, you can hit ctrl+t to bring up the toolbar, then press the "home" button.

**Comment by frenzibyte** [comment]
Resolved in https://github.com/ppy/osu/pull/11844.
