### ISSUE TITLE
Settings category bar sometimes doesn't highlight the correct section after searching

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#11835]
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43358824/108513995-9772bb80-72c3-11eb-94a2-4b04af1d907c.mp4

**osu!lazer version:** 
2021.212.0

**Comment by peppy** [comment]
This *looks* to be another case of invalidation failure, where certain pieces of the `FillFlow` don't get immediately updated to their final position. Haven't yet figured whether it is something wrong on the osu! side, but if I recall there are still a few edge case invalidation issues involving `FillFlow`?


https://user-images.githubusercontent.com/191335/112276199-d382ad00-8cc3-11eb-98c5-fc3a1c23c1e9.mp4

Note the position of the first element in the draw visualiser has an incorrect vertical position until I hover the fill flow area, after which point it recovers to its correct location.

**Comment by Theighlin** [comment]
This one can be closed as the reported problem isn't happening anymore. The animation of the highlited section changing seems to have been removed altogether.

**Comment by peppy** [comment]
This has since changed to immediately update to the target section for simplicity, yep.
