### ISSUE TITLE
Japanese kana font not rendered correctly

### ISSUE THREAD

**Issue by Contextualist** [ppy/osu#11838]
**Describe the bug:** _Some_ of the kanas do not display correctly. Kanji seems to be fine. The screenshot only shows the song selection menu, but the issue is seen everywhere. (e.g. wherever there is a song title / metadata that contains kana).

**Screenshots or videos showing encountered issue:** 
![osu-kana](https://user-images.githubusercontent.com/16000021/108564257-d22f2080-72d0-11eb-9bca-6b3c6d59c264.png)

**osu!lazer version:** 2021.219.0

**Logs:**
[logs.tar.gz](https://github.com/ppy/osu/files/6013025/logs.tar.gz)

**Comment by peppy** [comment]
Can you check if this happened on the previous version?

**Comment by Contextualist** [comment]
@peppy Can't reproduce in the previous version (2021.212.0).

**Comment by peppy** [comment]
Just to confirm, are you running the official AppImage release?

**Comment by Contextualist** [comment]
No. I'm on macOS 10.15.7.

**Comment by peppy** [comment]
Right, thanks.

I think I can see how this could potentially happen. Is it better after a restart?
