### ISSUE TITLE
Own download progress bar in realtime multi lobby starts at 50% and then goes back to 0%

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#11836]
https://user-images.githubusercontent.com/43358824/108521828-6c409a00-72cc-11eb-9742-a5401ea84b23.mp4

**osu!lazer version:** 
2021.219.0

**Comment by peppy** [comment]
This may be due to your network setup (I cannot replicate).

Please start by following the issue template and including logs etc.

**Comment by mouzedrift** [comment]
here are the logs:
[updater.log](https://github.com/ppy/osu/files/6010934/updater.log)
[database.log](https://github.com/ppy/osu/files/6010935/database.log)
[network.log](https://github.com/ppy/osu/files/6010936/network.log)
[performance.log](https://github.com/ppy/osu/files/6010937/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6010938/runtime.log)

i'm playing on windows with a wlan connection. someone else in the lobby mentioned that he had the same problem dunno what else i could add to this.

**Comment by Joehuu** [comment]
Did you only download one beatmap in your testing? The visual bug seems to happen after the first.

**Comment by mouzedrift** [comment]
i think it didn't happen the first few downloads or so. i played a few games before i noticed it. i just restarted the game and it seems to be gone even after downloading a few maps.

**Comment by mouzedrift** [comment]
i tested a bit more and it looks like it happens when you abort a download.
