### ISSUE TITLE
i cant quit from autoplay

### ISSUE THREAD

**Issue by Zsampier879** [ppy/osu#11847]
Hi, i downloaded osu lazer (and it really good) but i tryed autoplay and i cant quit from it

**Comment by Zsampier879** [comment]
and it crashed, when finished the song

**Comment by frenzibyte** [comment]
First issue is fixed in https://github.com/ppy/osu/pull/11844 and a hotfix will be released soon enough, as for your other issue please open another with following the bug template and the contributing guidelines.

**Comment by Zsampier879** [comment]
thank you so much

Salman Ahmed <notifications@github.com> ezt írta (időpont: 2021. febr. 20.,
Szo 9:04):
