### ISSUE TITLE
When starting up game, mouse movements aren't captured.

### ISSUE THREAD

**Issue by artilate** [ppy/osu#11840]
**Describe the bug:** 
When I load up into the game and on the screen showed in the screenshot, mouse movements aren't registered. I fixed it by simply restarting my game.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/45907943/108572056-4adcaf80-72c6-11eb-8310-8a4a314fb20d.png)

**osu!lazer version:** 
2021.219.0
(Has been happening for about a couple of weeks)

**Logs:**
[network.log](https://github.com/ppy/osu/files/6014336/network.log)
[performance.log](https://github.com/ppy/osu/files/6014337/performance.log)
[database.log](https://github.com/ppy/osu/files/6014340/database.log)
[runtime.log](https://github.com/ppy/osu/files/6014338/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6014339/updater.log)

**Comment by jai-x** [comment]
Please include logs files and system information, otherwise it is near impossible for use to diagnose the problem.

**Comment by peppy** [comment]
Closing for now as there's no actionable information. Hopefully the recent input changes resolved this one somehow.
