### ISSUE TITLE
Cursor confine setting option shown again in fullscreen after filtering/clearing filter

### ISSUE THREAD

**Issue by Starwort** [ppy/osu#11851]
**Describe the bug:** 
'Confine mouse cursor to window' setting is ineffective when the screen mode is set to 'fullscreen'

**Screenshots or videos showing encountered issue:** None, but the cursor simply gets stuck at the edge of the screen

**osu!lazer version:** 2021.220.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/6015989/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6015990/updater.log)
[database.log](https://github.com/ppy/osu/files/6015991/database.log)
[debug.log](https://github.com/ppy/osu/files/6015992/debug.log)
[network.log](https://github.com/ppy/osu/files/6015993/network.log)
[performance.log](https://github.com/ppy/osu/files/6015994/performance.log)

**Comment by bdach** [comment]
[This is intended](https://github.com/ppy/osu/pull/11092). The confine mode dropdown should be disabled if you're in exclusive full-screen to convey this.

**Comment by Starwort** [comment]
If by 'should be' you mean 'will be', then I agree; if you instead mean 'is supposed to be' then it isn't and that's a separate bug :P

**Comment by bdach** [comment]
[It should be hidden already](https://github.com/ppy/osu/pull/11101). Unless you're actually using borderless and not exclusive fullscreen, in which case [we're aware of that, too](https://github.com/ppy/osu-framework/issues/4134).

**Comment by Starwort** [comment]
![image](https://user-images.githubusercontent.com/16487249/108605412-dc721d00-73ab-11eb-838a-62a0e5aa61ec.png)
(mouse at edge of screen to indicate the lock)

**Comment by Starwort** [comment]
Ok screenshots are a little broken - hold on
![image](https://user-images.githubusercontent.com/16487249/108605435-f3187400-73ab-11eb-9864-3a4045271089.png)

**Comment by Starwort** [comment]
It's possible this is a bug with it showing when the user searches for it manually

**Comment by Starwort** [comment]
![image](https://user-images.githubusercontent.com/16487249/108605467-222ee580-73ac-11eb-9fb9-916219b32c24.png)
Nope - the dropdown is just always active

**Comment by bdach** [comment]
Please post everything in one go instead of peppering comments over and over. Also make sure you're posting actual screenshots.

**Comment by Starwort** [comment]
Apologies - I'll collect them in a single comment (I'm using the issues like I would Discord!)

Game is fullscreen:
![fullscreen setting](https://user-images.githubusercontent.com/16487249/108605412-dc721d00-73ab-11eb-838a-62a0e5aa61ec.png)
Setting is active even without search: ![confine setting](https://user-images.githubusercontent.com/16487249/108605495-45599500-73ac-11eb-8324-2541c0924ad0.png)

**Comment by Starwort** [comment]
Additionally I disagree with the premise of #4134 -- in borderless the confinement option actually applies correctly

**Comment by bdach** [comment]
Can reproduce being able to see the setting again after filtering/clearing the filter. Reopening for that.

**Comment by frenzibyte** [comment]
Now that dropdowns with disabled currents are improved, maybe the setting could instead be disabled, which feels better UX-wise (with a tooltip explaining that confining is always enabled in fullscreen as well maybe).
