### ISSUE TITLE
Freemod allows for invalid mod configurations

### ISSUE THREAD

**Issue by nathannino** [ppy/osu#11854]
**Describe the bug:** 
Using a combinaison of freemod and required mods, you can enable mods that aren't supposed to be enabled at the same time
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/24226538/108612817-04687d00-73ba-11eb-85c3-21469a7a71a1.mp4

**osu!lazer version:** 
2021.220.0
**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6016952/runtime.log)
[network.log](https://github.com/ppy/osu/files/6016953/network.log)

**Comment by frenzibyte** [comment]
Yeah, I was planning on fixing this one but I ran into a performance overhead from making the free mods overlay updating itself with the selected required mods to not show incompatible ones. Will see if I can reduce the overhead.
