### ISSUE TITLE
multiplayer bug

### ISSUE THREAD

**Issue by Zsampier879** [ppy/osu#11850]
hello again! i was playing osu lazer with my friend (he has it too) but he telled me his game crashed, i said "okay, a pause the game" and it dont let stop the multiplayer room. (i dont know how my friends game crashed) but i tryed to hold esc, only alt + home worked

**Comment by bdach** [comment]
The issue template is there for a reason. Do not open issues if you are going to ignore it.

**Comment by Zsampier879** [comment]
sorry
