### ISSUE TITLE
Osu!Lazer isnt launching

### ISSUE THREAD

**Issue by Flamingspark** [ppy/osu#11855]
Osu lazer doesn't launch when i open it and the cursor show its loading for less then a sec and then nothing happens. There is no notification saying anything about this issue and I am running this on laptop.

The game should be up to date with the latest version.

**Comment by PercyDan54** [comment]
Please upload game logs and follow issue template

**Comment by frenzibyte** [comment]
Please read the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)  thoroughly before opening issues, and **follow the bug issue template**, otherwise it would be impossible fixing your issue.

Closing as invalid.

**Comment by Flamingspark** [comment]
do i open the log for performance
