### ISSUE TITLE
Userpic and custom name in offline playing

### ISSUE THREAD

**Issue by Derelol999** [ppy/osu#11852]
I play only offline without account in the game and very want to change userpic and username (if possible also country) in the game settings, even without a login.
Stable version don't have userpics, but this better than standard osu userpic. And after receiving result, I can write my username. In laser I want to change username, userpic and country in the settings, when playing offline without account.
And also if offline player login game, all this information is taken from his account, these settings will affect only offline playing and local results.

**Comment by smoogipoo** [comment]
I don't think this is going to happen, sorry. We'll eventually have an invisible mode for online play.
