### ISSUE TITLE
Dropped input after break when multithreading is enabled

### ISSUE THREAD

**Issue by MishterKirby** [ppy/osu#11863]
**Describe the bug:** 
Input stops being handled after a break (also happens during an intro) when multithreading is enabled, but doesn't when it's disabled.
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/48867925/109449016-001d0f00-7a0d-11eb-9430-863a755608fa.mp4

**osu!lazer version:** 
2021.220.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6025166/database.log)
[network.log](https://github.com/ppy/osu/files/6025168/network.log)
[performance.log](https://github.com/ppy/osu/files/6025169/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6025170/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6025171/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6025172/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6025173/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6025174/updater.log)

**Comment by frenzibyte** [comment]
Have you checked whether all input is dropped? it may be caused by the cursor confinement setting set to `During Gameplay` if mouse input is what's dropped.

**Comment by MishterKirby** [comment]
Yep, both keyboard and mouse input is dropped

**Comment by MishterKirby** [comment]
This also happens in the other 3 modes, by the way

**Comment by bdach** [comment]
I'm really failing to grasp anything useful going from the video attached. There's no conceivable way to tell what the inputs to the game even were. Were you holding the key when it flickered off and on?

**Comment by MishterKirby** [comment]
No, I was spamming it to show that it worked during the break, but not directly after

**Comment by peppy** [comment]
To take any action on this, you're going to have to provide usable information. We need to be able to see the frame graphs in your video (Ctrl+f11 twice) and hopefully have a better idea of what we're actually looking at. Because even with your explanation I have no idea.

**Comment by MishterKirby** [comment]
Not too sure about this, but I feel like #11913 might be related to this, actually

**Comment by peppy** [comment]
@MishterKirby please try turning off cursor confining and see if it helps. your whole window event queue is getting stuck due to some command we are sending, which it really shouldn't (suggests that something else on your system may be at fault).

**Comment by MishterKirby** [comment]
Still happens with confining set to "Never"

**Comment by MishterKirby** [comment]
Closing due to it being a hardware issue on my end
