### ISSUE TITLE
Lazer crash on startup when ~/osu directory is an alias

### ISSUE THREAD

**Issue by Knallli** [ppy/osu#11860]
**Describe the crash:** 
App not opening with message: 6
I tried to move the ~/osu directory to an external Drive and create an alias in my home directory in order to move the contents off the internal SSD. Lazer won't start after that

**osu!lazer version:** 
Feb 20
**Logs:**
nothing gets written in logfiles

**Computer Specifications:** 
M1 MacBook Air 16gb BigSur 11.3

**Comment by MiraiSubject** [comment]
Tried to reproduce on an Intel Macbook Pro 2018, but unfortunately cannot.

I symlinked to my external drive (exFAT) using: 
```
ln -s /Volumes/MiraiT5_500/osu ~/.local/share/osu
```
and that redirects the files just fine. 

Stable seems to use ~/.osu as per https://github.com/ppy/osu/issues/3763#issuecomment-494224488 though.

**Comment by Knallli** [comment]
just a symlink works fine but the apple alias thing by right clicking -> create alias is not for some reason

**Comment by frenzibyte** [comment]
osu!lazer user data folder gets stored in `~/.local/share/osu`, I'm not sure where this `~/osu` folder you're talking about came from, and what it contains. 

Also, this whole setup is wrong, you would want to use the folder migration feature in osu!lazer (`Change folder location` button in settings) which allows you to move your data folder to a new location on an external drive or wherever you desire.

**Comment by MiraiSubject** [comment]
> just a symlink works fine but the apple alias thing by right clicking -> create alias is not for some reason

Yup, that I can reproduce. 

Leaving behind a gist with the crash log https://gist.github.com/MiraiSubject/01370f7657aa5f21caa950ec0db7f3f8 for anybody willing to look into this deeper. 

Creating an alias using the context menu on the external drive, dragging and dropping that into ~/.local/share and naming the alias osu will cause a hard crash.

**Comment by Knallli** [comment]
the built in move feature is working fine although I'd rather not have ~/osu folder in my home directory at all it's in fact that location by default and not .local/share/osu (.local) does not even exist on my system

**Comment by frenzibyte** [comment]
Based on framework code for selecting default user storage path here:
https://github.com/ppy/osu-framework/blob/46b5d3cfd37afaf6f085d2837c79b711bf718b2c/osu.Framework/Platform/MacOS/MacOSGameHost.cs#L27-L33

I guess you modified the `XDG_DATA_HOME` environment variable causing `~/osu` to be the default location for you, either way, that changes nothing. 

Again, you can migrate your data to an external drive with the "built-in move feature", unless you're encountering issues with it, please post them here.

**Comment by Knallli** [comment]
I haven't modified any variable myself. using the move feature still keeps a folder called osu with some files in my home so I'd rather have that moved completely

**Comment by frenzibyte** [comment]
You could've just stated from the beginning that you don't want the `osu` folder to still remain in your home folder.

Your only chance would be setting the `XDG_DATA_HOME` environment variable to a certain path such that osu!lazer will put its `osu` folder there, away from your home folder. Keep in mind it's not just for lazer, you can google that variable to understand more about it. Closing as not an issue with osu!lazer.
