### ISSUE TITLE
All my scores have been deleted

### ISSUE THREAD

**Issue by maramowicz** [ppy/osu#11877]
If something is not written right, I am sorry, I used a translator because I couldn't have written it better myself.

I'm not really sure when it happened, I didn't play Osu!lazer for a few days, during that time I was playing the stable release of Osu. After starting up I noticed that all my results disappeared for some reason, trying to find any deleted files with Recuva ends up with no deleted files found, so I suspect something overwrote the file with my scores.

Currently 2020.220.0, unfortunately it updated moments after starting so I don't know if it was caused by this version of Osu!lazer

**Comment by bdach** [comment]
I can't imagine a scenario in which this should be happening spontaneously as you describe it. Have you changed anything in the machine at all? Created a new user account, anything of the sort?

Additionally please attach your `client.db` file from the `%AppData%/osu/` folder for inspection.

**Comment by maramowicz** [comment]
I moved all the files from the osu folder (well almost, I didn't move the online.db, files and cache folder) to the cloud for review.

https://drive.google.com/drive/folders/18uQ5zYgx3dixzUvDsyyfVRzSt1qzks2A?usp=sharing

I also thought I might try downloading an older version of Osu!lazer, I haven't managed to do the de-update yet but I don't know if that would do anything.

**Comment by maramowicz** [comment]
Ok, I didn't know what happened but I de-updated Osu!lazer and.... I probably made the stupidest mistake I could have made. I mean, after a while, I realized that yes, my scores are there, but only the ones from Osu!taiko... I guess I don't have to explain that this "disappearance" is only my fault because after those few days I forgot that I have to switch to Osu! with Osu!taiko. If I just tried to play it once...

So I apologize for the confusion and close the topic, although I think maybe there should be a sort of "panic button" in the settings for forgetful people like me.

**Comment by bdach** [comment]
Seems like the game-global ruleset filter might be slightly confusing to users (compare https://github.com/ppy/osu/issues/11343 for another instance of this). Maybe an issue of plain discoverability, maybe something to think about at a larger level...

**Comment by maramowicz** [comment]
I have an idea how it could look like, if you don't see any scores then you panic ("what's going on, where are my scores..."). So if there was a small indicator on the left side of the beatmap bar from other modes played? (I don't know how the translator will translate it and if you know what I mean, so I made a quick visualization of how it would look like)

![osuothermodes](https://user-images.githubusercontent.com/29564602/108768560-17b14f00-7558-11eb-8eed-002433b9bd70.png)
