### ISSUE TITLE
Notification and back buttons can't be clicked from the right and bottom edges on fullscreen

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu#11874]
**Describe the bug:** 

As demonstrated in the video. Other clickable stuff at those edges work fine, like the cookie on the bottom-right or any of the song panels to the right of the edges.

Ideally you'd want to be able to flick your mouse to the corners and be able to click the buttons, like you can do with the settings button on the top-left.

This behaviour seems inconsistent with some specific UI scales as well, also shown in the video.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/36758269/108727127-81196980-7528-11eb-8ec3-307a16b30bd5.mp4

**osu!lazer version:** 

Latest release: 2021.220.0

**Logs:**

N/A

**Comment by frenzibyte** [comment]
Can you confirm you can't reproduce this when raw input is off? if so, then this would be a duplicate of https://github.com/ppy/osu/issues/4216

**Comment by Walavouchey** [comment]
Yes, can't reproduce. Couldn't find that issue.
