### ISSUE TITLE
Disable additional mouse buttons when playing

### ISSUE THREAD

**Issue by M0rica** [ppy/osu#11879]
**Describe the new feature:** 
It would be nice to turn off all mouse buttons when having the option "Disable mouse buttons during gameplay" on. Right now, only left and right click get disabled, but I got a few extra buttons on my mouse, and I sometimes accidently hit one of those keys as they are right above my thumb, causing the game to pause when I hold it just long enough. It seems like this key got automatically maped to pause gameplay in the settings, so I could maybe just delete it there, but it would be nice in general to just deactivate all mouse buttons when having this option enabled instead of just deactivating left and right click. The osu!-stable client deactivates them too.
**Proposal designs of the feature:** 
Just deactivate all mouse buttons when having the option "Disable mouse buttons during gameplay" enabled.

**Comment by bdach** [comment]
Might be as simple as dropping this `when` clause:

https://github.com/ppy/osu/blob/b8f23e4c84637bde3667f114dc622d7eb9a654e5/osu.Game/Rulesets/UI/RulesetInputManager.cs#L112-L116

**Comment by peppy** [comment]
@M0rica for your use case, do you still want the pause functionality to work outside of gameplay? as it stands, you can already unbind the pause action from your mouse button at a global level. not yet sure if we want to include these kinds of bindings in the gameplay layer disabling or not, so describing your use case better would be appreciated.

**Comment by peppy** [comment]
Turns out it doesn't really make sense *not* to disable mouse buttons globally, so I've done that. Note that they are only disabled while the ruleset/gameplay has focus.
