### ISSUE TITLE
Some issues about visual tests

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#11883]
**Describe the bug:** 
Autoplay test lag and plays random music from local beatmaps at the end (0:23)
UserDimBackgrounds has 2 NoFail mods active (0:40)
DirectDownloadButton(0:50) and SkinnableSound always fail (1:05)
**Screenshots or videos showing encountered issue:** 
https://youtu.be/JUoySzIypMw
**osu!lazer version:** 
latest master
**Logs:**
Console output: 
[test.log](https://github.com/ppy/osu/files/6028622/test.log)
Generated logs:
[runtime.log](https://github.com/ppy/osu/files/6028625/runtime.log)
[database.log](https://github.com/ppy/osu/files/6028626/database.log)
[performance.log](https://github.com/ppy/osu/files/6028624/performance.log)

**Comment by peppy** [comment]
Duplicate of https://github.com/ppy/osu/issues/11301. Don't group multiple issues in single issues. Read contribution guidelines, please.
