### ISSUE TITLE
Can't SHIFT right-click delete objects when using HitCircle or Slider (only with Select or Spinner)

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#11884]
[Video](https://puu.sh/HjpgN/9a4adf9946.mp4)

**Comment by bdach** [comment]
I actually think the current behaviour is correct. Don't think deleting should be permitted if a placement tool is active. In fact I'd probably lean the other way and disable <kbd>Shift<kbd>-right click delete while placing a spinner.

**Comment by RaiLTC** [comment]
I personally disagree. It just betrays expectations and hinders work flow. Might be because I'm used to stable editor but as long as I used the lazer editor with SHIFT right click, this was the most annoying issue to deal with (aside from not having an indicator to how any degrees I'm rotating a spider :p)

**Comment by peppy** [comment]
It's a pretty bad UX, but it is what people are used to on stable. I think supporting this only when shift is held is fine. We may add a toggle in the future if shift gets overloaded with other conflicting behaviours.
