### ISSUE TITLE
Undo or re-opening the map causes sliders with more than 3 nodes to reset all the modified nodes back to Bezier

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#11885]
[Example](https://puu.sh/HjpC3/428ad9fe68.mp4) of undo on a slider with 3 nodes and more than 3 nodes

Happens both on regular right click delete and SHIFT right click delete

**osu!lazer version:** 2021.220.0

**Comment by peppy** [comment]
This is part of the automatic logic that decides you've used the wrong curve type based on the number of points available to be consumed by the curve. It can happy when you have a "perfect curve" which doesn't have 3 points (the only number of points which will work correctly for a perfect curve), or if you have three points in a completely straight line.

https://github.com/ppy/osu/blob/2150cf1c52336cc624e7bc13fb4eb78ae18d1bd9/osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs#L312-L322

This logic is run on undo/redo/load.

I guess from a usability perspective, this may not be what we want. But the fallbacks *are* there to get the user in a good state, so they aren't trying to use an incorrect curve type and not getting any visible result.

**Comment by bdach** [comment]
Watching the video, I'm a bit confused by the state even before the undo. It doesn't really make sense to allow a perfect path type if there are four path nodes, since it is incredibly likely that a circular arc cannot be physically drawn through those points.

The way I see it, the addition of a fourth point to a circular arc should terminate the arc and begin a new path segment, with a completely different path type (linear is the obvious choice, I guess?) While it might look a bit wonky UX-wise, it sort of is a lie anyway to pretend the path is a perfect curve with 4 points, so maybe best to be explicit about that...?

**Comment by bdach** [comment]
How does something like [this video](https://drive.google.com/file/d/1zwy7SfYvGJICOnhWckeolOClDvvyISUT/view?usp=sharing) feel, UX-wise? This is the demonstration of a crude implementation of the logic I proposed above that would verify the correctness of applied curve types on path changes. This would therefore resolve the issue for new maps by making it impossible to save a map in an invalid state, as it seems like stable cannot generate a map with a broken perfect slider.

I know it's a bit wonky (and I still haven't fixed all of the edge cases - for example, the `Perfect` curve type should be disabled in the context menu if the next 2 nodes can't be used for it), but I wanted to get a feel out whether this feels acceptable. I think it's okay - it is hard to understand, but so is the magical fixup of perfect into Bezier, I feel.

**Comment by peppy** [comment]
I think it's fine. The curve guessing happening only during initial placement makes sense to me. After it is placed, the curve types should be set in stone.

**Comment by peppy** [comment]
With the recent UX changes to slider placement I believe this is no longer an issue. Note that undo/redo state handling is still a bit haphazard so if you try to reproduce this make sure to move the slider between each node change (this remaining issue is being tracked via #10314).
