### ISSUE TITLE
Global bindings don't work when hovering certain drawables

### ISSUE THREAD

**Issue by peppy** [ppy/osu#11914]
In osu! we block mouse clicks from other elements on screen in multiple places by handling the `MouseDown` events:

https://github.com/ppy/osu/blob/45e41aaeacf930ce4b5e3b62f85acbc618ce73da/osu.Game/Screens/Select/Footer.cs#L104-L108

![20210227 160026 (CleanShot)](https://user-images.githubusercontent.com/191335/109378329-eef0d700-7914-11eb-823f-23bd29255951.png)

This unfortunately blocks `GlobalAction`s from firing. An easy reproduction is to try and use the "back" binding (mouse 4 by default) while hovering the song select footer area.

I'm not immediately sure on the correct direction to fix this.

**Comment by hbnrmx** [comment]
Somewhat related: #6026

**Comment by peppy** [comment]
This is a bit of a tricky one to fix. Open to any suggestions on how we'd see this working.

Basically, we want to block "positional" mouse button input, but let "non-positional" - aka global actions - still activate.
