### ISSUE TITLE
[Bug Report] UI Overlays disappeared and some remaining objects shifted after update.

### ISSUE THREAD

**Issue by Hexality** [ppy/osu#11912]
**Describe the bug:** 
UI Overlays disappeared and some remaining objects shifted

**Screenshots or videos showing encountered issue:** 
https://i.fiery.me/9eYaO.mp4

**osu!lazer version:** 
2021.226.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/6051753/network.log)
[performance.log](https://github.com/ppy/osu/files/6051754/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6051755/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6051756/updater.log)
[database.log](https://github.com/ppy/osu/files/6051757/database.log)

**Comment by Joehuu** [comment]
The latest release had a lot of breaking api changes.

Can you remove all custom rulesets not updated for the latest version of osu! and see if it fixes itself? I see ruleset errors everywhere that can cause issues.

**Comment by Hexality** [comment]
yeah, R.I.P rulesets, that was really the problem unfortunately

**Comment by bdach** [comment]
Sorry to hear that but there is nothing we can do in this repository to fix the problem. The ruleset authors will have to release an update addressing the breaking changes.

**Comment by peppy** [comment]
Rather than "keep away" you can just run the last version. In fact, the last version is always kept available on disk, so you still have a copy.
