### ISSUE TITLE
Beatmap details preview is stuck in loading when offline

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#11910]
**Describe the bug:** 
Beatmap details preview is stuck in loading when offline
**Screenshots or videos showing encountered issue:** 
![osu_2021-02-26_19-32-58](https://user-images.githubusercontent.com/50285552/109295283-708b2b00-7869-11eb-9589-06184f9d2b97.jpg)
**osu!lazer version:** 
2021.220.0
**Logs:**
not useful here

**Comment by peppy** [comment]
Given that a good portion of this information does not need online retrieval, the loading area should be isolated to the part that does (and it should probably make use of the new `OnlineViewContainer`).

**Comment by owen-young** [comment]
I will start working on this issue.

**Comment by bdach** [comment]
@owen-young This issue thread should contain enough information already to determine what we'd be looking to achieve, but if you have follow-up questions, feel free to ask either here or on discord. Additionally, make sure you've read through [the contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md) firsthand.

**Comment by owen-young** [comment]
If it isn't too much to ask, I'd like some feedback on the revised layout based on code I've added:

https://i.imgur.com/ABVzQOX.png

Not sure if the section with the description/source/tags should be cut off like that (maps with lots of tags have that happen) and need scrolling, since that was not present previously.

**Comment by peppy** [comment]
There shouldn't be two displays. Just the bottom one is fine. The "ratings" area can just be blank instead.

**Comment by peppy** [comment]
If the cutting off is a new thing, that needs to be fixed, too.

**Comment by owen-young** [comment]
> 
> 
> There shouldn't be two displays. Just the bottom one is fine. The "ratings" area can just be blank instead.

So, instead of two `OnlineViewContainer`s, there should just be one mentioning both failure points and user ratings? And both of those areas are part of the `OnlineViewContainer` ?

**Comment by peppy** [comment]
If you can somehow arrange it in a way that that works. Else there should probably be two but one shouldn't show the message.
