### ISSUE TITLE
Modifying a beatmap does not invalidate online ranking status

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu#11922]
**Describe the bug:** 
1. Edit the beatmap for 2+ objects
2. Play the edited beatmap
3. Edit the beatmap for having 1 object
4. Play again 
5. try to play the 2 stage's replay (Flags osu.Game.Scoring.Legacy.LegacyScoreDecoder+BeatmapNotFoundException)
Plus:
- Edited beatmap have the same rank status as original beatmap status
- Leaderboard seems not to be cleared since its checksum is not same

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=6zTpyiUvtNc&feature=youtu.be
![image](https://user-images.githubusercontent.com/37479424/109413409-98f16180-79f0-11eb-908a-d22d42f50050.png)

**osu!lazer version:** 
osu!lazer 2021.226.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6056476/database.log)
[network.log](https://github.com/ppy/osu/files/6056477/network.log)
[performance.log](https://github.com/ppy/osu/files/6056478/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6056479/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6056480/updater.log)

**Comment by peppy** [comment]
Going to close this one. Client-wise a full process is now occurring on editor save. Server-side work is currently underway and being tracked at https://github.com/ppy/osu-web/issues/9115.

**Comment by AadilRn** [comment]
Sorry for replying when this is closed, but I wanted to know if changing backgrounds and mp3s will also invalidate ranked status and prevent a user's score from being submitted to the leaderboard. Currently osu!stable allows for modifying backgrounds and mp3s and I would hope osu!lazer also functions like this, but from the limited testing I have done it doesn't seem like this is the case.
