### ISSUE TITLE
Slider tail hitsounds should play even when missed with classic mod enabled

### ISSUE THREAD

**Issue by manmathew** [ppy/osu#11921]
I understand why in lazer the hitsounds don't play if you miss the sliderend. But because I've become so accustomed to it being there in stable, it makes the experience in lazer a bit odd for me. Obviously, not everyone is like me, but I'm surely not going to be the only one. And the experience becomes much more obvious when playing maps with very easy to miss sliderends like candyland by probox.

I think that there should be a tick box option in the sound section of the settings that enables the hitsound to be played on sliderends whether or not you miss it. I'm sure it won't be enabled by everyone, but it would be a nice feature to have that would also make the transition from stable to lazer a bit easier for the player, even if it's minuscule.

**Comment by peppy** [comment]
You can turn on the classic mod for this behaviour. We won't be adding this feature in because we intend to have sounds and visual 100% match your input.

**Comment by frenzibyte** [comment]
Classic mod does not seem to achieve the mentioned behaviour. Reopening for tackling that (can't edit title though).
