### ISSUE TITLE
Difficulty Adjust mod show repeated values

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#11924]
**Describe the bug:** 

When you use the difficulty adjust mod, you can see repeated "circle size" and "approach rate".
In case you move any slider from a repeated value, both sliders shown are moved.

**Screenshots or videos showing encountered issue:** 

Screenshot:

![osu_2021-02-28_13-41-55](https://user-images.githubusercontent.com/41755816/109426300-bb24b880-79cb-11eb-8d4a-127d24b8accd.jpg)

Video:

https://user-images.githubusercontent.com/41755816/109426471-941ab680-79cc-11eb-8353-f29ed897dc24.mp4

**osu!lazer version:** 

Lastest 2021.226.0

**Comment by bdach** [comment]
#11905

it's even pinned

**Comment by Gonzalo-Bruna** [comment]
I didn't expect the searchbox not to show the pinned issues. sorry about that.
