### ISSUE TITLE
Feature to refresh ranked status from beatmap

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu#11923]
**Describe the new feature:** 
Importing osz file at guest session might set the whole beatmaps from beatmapset ranked status to None
Video) https://www.youtube.com/watch?v=t_z1hNMh414&feature=youtu.be

To avoid this, I would like to ask to implement refresh beatmap ranked status when fetching beatmap lookup 
(known as fail/exittime and user rating fetch)

**Proposal designs of the feature:** 
Update ranked status when fetching beatmaps lookup at song selection (should enable checksum search at osu-web, current endpoint seems to ignores the checksum query)
ex)  https://osu.ppy.sh/api/v2/beatmaps/lookup?id=418768&checksum=2913asdasdsdadsadsaasbdc88710f08dcd8827d2e827ab65&filename=PLight%20-%20TRIGGERHAPPY%20(Hommarju%20Remix)%20(Lokovodo)%20[EXTRA%20AR10].osu

**Comment by peppy** [comment]
This can probably be tracked by the existing issue (https://github.com/ppy/osu/issues/5376). It's an obvious shortcoming which we already have plans to fix.

As an aside, the checksum should not be ignored. If you believe it is, please report that as a separate issue.

**Comment by ilsubyeega** [comment]
My bad. The parameters were validated individually instead of together. Thank you for answering this

**Comment by peppy** [comment]
Ah yep, it does a best-effort match (preferring the checksum but falling back to filename if it doesn't match, to allow for potentially matching to an update for an outdated beatmap where the ID is not available on the client).
