### ISSUE TITLE
osu!direct search bar not showing text when typing on android

### ISSUE THREAD

**Issue by xzCobra** [ppy/osu#11930]
**Describe the bug:** 
When trying to search for beatmaps on osu!direct on android, the text doesnt show up unless I tap an autocorrect option. Not sure if this happens on iOS as well, as I don't have an apple phone to test this on.

Phone: Samsung Galaxy A40 (2019)

**Screenshots or videos showing encountered issue:** 
![Screenshot_20210301-144915 2](https://user-images.githubusercontent.com/39083379/109506085-8d0fa900-7a9d-11eb-947d-f20bc508e443.jpg)

**osu!lazer version:** 
2021.212.0 (the original version I found this bug in)
2021.226.0

**Logs:**
https://pastebin.com/XaJC0Q0U (database.log)
https://pastebin.com/0QVMzYBJ (network.log)
https://pastebin.com/DHcGe1W5 (performance.log)
https://pastebin.com/XaJC0Q0U (runtime.log)

**Comment by bdach** [comment]
#8264
