### ISSUE TITLE
Difficulty sliders show 2 twice in the window

### ISSUE THREAD

**Issue by Basma1784** [ppy/osu#11932]
****Describe** the bug:** 
When i was changing the approach rate i noticed that there were 2 sliders for every option, when i adjusted one of the approach rate sliders the other changed its value as well.

**Screenshots or videos showing encountered issue:** 
![2021-03-01_19h06_30](https://user-images.githubusercontent.com/79867461/109540172-69128e80-7ac2-11eb-9601-e572f5e4a9db.png)
![2021-03-01_19h16_50](https://user-images.githubusercontent.com/79867461/109540428-b4c53800-7ac2-11eb-98ed-1b7b65a6d75a.png)

**osu!lazer version:** 
2021.226.0

**Logs:**

[performance.log](https://github.com/ppy/osu/files/6063602/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6063603/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6063604/updater.log)
[database.log](https://github.com/ppy/osu/files/6063605/database.log)

**Comment by bdach** [comment]
[check the pinned issues.](https://github.com/ppy/osu/issues/11905)
