### ISSUE TITLE
Volume wheels appear underneath the settings panel

### ISSUE THREAD

**Issue by Azzirah** [ppy/osu#11951]
**Describe the bug:** 
When changing the game's volume with either the mouse wheel or the alt+up/down arrows, if the settings panel is open the volume wheels won't be visible as they appear underneath it, while the master's volume does change.

**osu!lazer version:**  2021.302.0

**Comment by frenzibyte** [comment]
Duplicate of https://github.com/ppy/osu/issues/11077, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)
