### ISSUE TITLE
Menu slider reset (orange) click spots not displayed when value changed beyond default

### ISSUE THREAD

**Issue by integerrr** [ppy/osu#11954]
**Describe the bug:** 
When players change certain settings via in-game menus that has a slider for value adjustment, an orange bar displays on the left of those sliders indicating that the value set is non-default, and clicking it would reset the value of that particular setting back to default, this is missing through all menu items including Ctrl+O menu, mod customisation menu, replay menu etc.

**Screenshots or videos showing encountered issue:** 
Example - customisable mod menu
Normal:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/7279624/109723084-8704ef80-7ba5-11eb-89de-c802f590c0e5.png">

2020.302.0:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/7279624/109723122-94ba7500-7ba5-11eb-9932-2be44a80b83c.png">

**osu!lazer version:** 2020.302.0

**Logs:**

--

**Comment by frenzibyte** [comment]
Will be fixed by https://github.com/ppy/osu/pull/11952.
