### ISSUE TITLE
I can't run osu! In my phone

### ISSUE THREAD

**Issue by Likver** [ppy/osu#11953]
Osu! Don't work, idk why, i have a phone with Android 8.1.0 Oreo

![Screenshot_20210302-190648](https://user-images.githubusercontent.com/79934166/109694402-0e913500-7b8b-11eb-9a57-4c48bd412830.png)

*Version: 2021.302.0* 

**Logs:**
--> I dont have any folder with the name "sh.ppy.osulazer" :/

PLEASE HELP ME!!

**Comment by bdach** [comment]
We cannot help you
 with this little information. Did it ever work? What device do you have?

Closing until some actual information that can be worked with is given. Will re-open if it is provided.

**Comment by Likver** [comment]
I just Intall today, i think 10minutes ago, and it doesn't work for some reason.

I have a SelecLine S6 device... Unusual phone name i know :(

**Comment by bdach** [comment]
I can't even so much as find full hardware specifications for this device online, but from whatever little I have found, I wouldn't be surprised if it didn't meet the minimum requirements to be able to run the game.

Sorry, we cannot provide support for this device.

**Comment by Likver** [comment]
Oh okay, thank u

**Comment by Likver** [comment]
I know my phone is really bad, but i didn't expext this :'v
