### ISSUE TITLE
[Feature request] Add the feature that allows the player to toggle mods when watching a replay with the mods

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#11950]
Add the feature that allows the player to toggle mods when watching a replay with the mods. such as toggle Hidden mod when watching a replay with Hidden etc.

**Comment by frenzibyte** [comment]
Duplicate of https://github.com/ppy/osu/issues/8357, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)
