### ISSUE TITLE
Orange sidebar not appearing in the settings menu when changing any setting

### ISSUE THREAD

**Issue by Modsnotworking** [ppy/osu#11964]
**Describe the bug:** **orange** sidebar(which appears when you change the default settings) doesn't appear in the latest version(2021.302.0). Here's a screenshot to help you understand:

**Screenshots or videos showing encountered issue:**
![osu_2021-03-05_09-16-32](https://user-images.githubusercontent.com/70589304/110065014-46b79400-7d94-11eb-9ce8-13e49bf0c694.jpg)as you can see I have changed the Master volume to 60 and still there's no orange sidebar on the left of the master volume setting

**osu!lazer version:** 2021.302.0(latest)

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/6088031/logs.zip)

**Comment by bdach** [comment]
#11954
