### ISSUE TITLE
Cursor locks when raw input is enabled

### ISSUE THREAD

**Issue by makkarakka3** [ppy/osu#11960]
**Describe the bug:** 
My cursor locks when i enable raw input.
**Screenshots or videos showing encountered issue:** 
https://1drv.ms/v/s!AiDvP750cgLCiKM7RViop66wQKy2eA?e=FLBCSh
**osu!lazer version:** 
2021.302.0
**Logs:**
[network.log](https://github.com/ppy/osu/files/6084030/network.log)
[performance.log](https://github.com/ppy/osu/files/6084031/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6084032/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6084033/updater.log)
[database.log](https://github.com/ppy/osu/files/6084034/database.log)

**Comment by peppy** [comment]
We are aware of this, but this has been reported at least 10 times already. Please search first. A fix will be coming in the next release or so.
