### ISSUE TITLE
Osu Error 0x80004005

### ISSUE THREAD

**Issue by pejzaz** [ppy/osu#11967]
**Describe the crash:** Osu! installer crashes when installing, and gives me error 0x80004005, i played osu! like 3 months ago and everything was ok

**Screenshots or videos showing encountered issue:** 
![error](https://user-images.githubusercontent.com/80106075/110116126-57c5cc80-7db7-11eb-8afa-b131168206b6.png)

**osu! version:** newest

**Logs:**
No logs

**Computer Specifications:** 
Intel HD Graphics Family 1GB
Intel B950 2.1Ghz
4GB RAM

**Comment by aspriddell** [comment]
this is an osu! stable issue, and as such needs to be reported at [osu-stable-issues](https://github.com/ppy/osu-stable-issues) instead

**Comment by smoogipoo** [comment]
As above
