### ISSUE TITLE
Allow to select multiple elements that are in-between other elements via mouse-drag

### ISSUE THREAD

**Issue by Zenahr** [ppy/osu#11978]
**Describe the new feature:** 

Allow to select multiple elements that are in-between other elements.

# Similar Existing Features

Currently users can select multiple elements by simply draggin the mouse from left or right (given that the space is not occluded by elements (circles, etc.))

![input](https://user-images.githubusercontent.com/47085752/110231415-ee110400-7f17-11eb-8345-afb8ad0cb2a9.gif)

**Proposal designs of the feature:** 

Make it so that dragging off from slightly above elements creates a selection box as seen in the demo so that users can batch-select elements that are not surrounded by empty space.

**Comment by Zenahr** [comment]
Area: Editor (for the label)

**Comment by frenzibyte** [comment]
I don't understand what you're proposing here, doesn't this "drag to create a selection box for batch-selecting elements" feature already exist in osu!lazer?:

https://user-images.githubusercontent.com/22781491/110231876-6d5c0300-7f2b-11eb-80fa-8cc809caf45e.mov

**Comment by bdach** [comment]
Yeah, I'm pretty sure this is supported already. @frenzibyte's video doesn't work for me, but I checked and you can already start a drag on the top timeline even if there's an object nearby. There's a gap that allows that.

@Zenahr Please clarify your proposal. Did you try the lazer editor? What's wrong with it in the current state with regard to this issue?

**Comment by frenzibyte** [comment]
Weird, here's a streamable link instead: https://streamable.com/lxqs34

**Comment by peppy** [comment]
I think they may be asking for the gap/area to be increased in size, but it's hard to say.

**Comment by Zenahr** [comment]
oh jeez I'm terribly sorry...
Is osu!lazer the exact same as the official osu! game? If not apologies, I'll close this issur right away.

**Comment by bdach** [comment]
No, osu!lazer is the next version of the client (contrary to what we usually call "stable"). You may want to read [this blog post](https://blog.ppy.sh/a-definitive-lazer-faq/) for more information.
