### ISSUE TITLE
Osu crashes when the active ruleset is removed after a restart

### ISSUE THREAD

**Issue by jorolf** [ppy/osu#1198]
Should this happen or should it revert back to the default one?

**Comment by peppy** [comment]
crashes should never happen. further details would be useful.

**Comment by jorolf** [comment]
how to:
change "Ruleset" in game.ini to a non-existent ruleset

reason:
the mod select overlay tries to create an instance of the ruleset which throws an exception
https://github.com/ppy/osu/blob/master/osu.Game/Overlays/Mods/ModSelectOverlay.cs#L43

fix:
check if the ruleset exists and if not reset it to the default

**Comment by peppy** [comment]
Closing as duplicate of #1499
