### ISSUE TITLE
Disabling raw input with keybindings breaks the cursor sensitivity slider

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#11987]
After disabling raw input via the keyboard using `Ctrl`+`Alt`+`R`, the cursor sensitivity adjust slider will no longer function when turning raw input back on. It will instead throw unhandled exceptions, which eventually crashes the game. A restart is required to make the sensitivity slider work properly again. Info is in the runtime log (tries to modify disabled bindable).
Logs: https://www15.zippyshare.com/v/b9y4XZJq/file.html
Video: https://streamable.com/apciow
Version: 2021.302.0
I am using Windows 10.

**Comment by bdach** [comment]
I believe this will be resolved in the next release thanks to #11961.
