### ISSUE TITLE
[macOS] M1 arm64 support

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#11983]
**Describe the new feature:** 
Consider supporting arm64 compilation and distribute a Universal Binary macOS application.
This would make it so that M1 users don't have to use Rosetta and potentially lower power consumption.

**Proposal designs of the feature:** 
n/a? idk

Edit 1: actually I think this should maybe be moved into the osu!framework repo instead

**Comment by bdach** [comment]
I don't believe we should be doing anything in this direction until the runtime can actually support running without rosetta (https://github.com/dotnet/runtime/issues/43313). It should hopefully be no more complicated than adding a new runtime once upstream support lands.

This has also been asked before at #9346. I'll close this for now as this is still very much way too early to act upon on our side. Probably nothing will be happening in that regard until .NET 6.

**Comment by icanotc** [comment]
it seems like .NET 6 supports apple silicon natively now, any updates?

**Comment by bdach** [comment]
no. i recommend [searching](https://github.com/ppy/osu/discussions/15544) next time.
