### ISSUE TITLE
Osu on mac mouse acceleration

### ISSUE THREAD

**Issue by SP72s** [ppy/osu#11998]
mouse acceleration is disabled in my whole computer, however whenever i open osu!lazer mouse acceleration comes back for no reason and its completely impossible to hit anything without completely missing the circle, even if raw input was on i think it still behaves the same way altough i cant test that as it is disabled for mac os, im running the latest version of the client and im running on MacOS Mojave 1.14 (then again mouse acceleration is already disabled and my cursor works fine on my osu!stable client)

**Comment by peppy** [comment]
osu!(lazer) does nothing to "re-enable" acceleration as you are implying, but it also does nothing to disable it. on the other hand, stable may be using "raw input" for you, which may somehow be disabling the acceleration via a wine emulation layer.

For reference, how do you believe to be disabling mouse acceleration on your whole system?

**Comment by SP72s** [comment]
> osu!(lazer) does nothing to "re-enable" acceleration as you are implying, but it also does nothing to disable it. on the other hand, stable may be using "raw input" for you, which may somehow be disabling the acceleration via a wine emulation layer.
> 
> For reference, how do you believe to be disabling mouse acceleration on your whole system?

im not implying that it re-enables mouse acceleration, just to make things clear i use a tool called "SteelSeries Exact Mouse tool" reason being that attempts to disable mouse acceleration with the console didnt do anything, now that i made that clear, the feeling of the mouse did feel off but it COULD be raw input (i will test this out myself later with the stable client) thanks for replying as well

**Comment by SP72s** [comment]
Just to be sure "Exact Mouse tool" does in fact disable mouse acceleration... im not aware of wether you know about this tool (if you are, then you can ignore this reply) but you can find it by googling "Steelseries Exact Mouse Tool" click the first result, go to the bottom of the page and click on micsellaneous, you should be able to find it there

**Comment by peppy** [comment]
I'm aware of that tool, and it should also be applying the same effect inside the game (at least in the current release version). We do have some input related changes coming in in the next release or two, which will give you more configuration over how the mouse works, so please check back when that happens.

**Comment by SP72s** [comment]
> I'm aware of that tool, and it should also be applying the same effect inside the game (at least in the current release version). We do have some input related changes coming in in the next release or two, which will give you more configuration over how the mouse works, so please check back when that happens.

well thanks for that, as for the raw input issue i mentioned, i disabled raw input in the stable client, however i seemed to be able to do jumps and streams and patterns similar to those pretty fine, not sure if restart is needed to fully disable raw input but it dosent seem to be making that much of a difference. thats all
