### ISSUE TITLE
Black screen when launching osu!lazer with ShadowPlay on, but Desktop Capture off

### ISSUE THREAD

**Issue by atemerino** [ppy/osu#11997]
**Describe the bug:** 
I upgraded my GPU from a GTX 1080 Ti to RTX 3080.

When I launch lazer with Desktop Capture off, but Shadowplay Instant Replay on, the game only displays for a split second then stays as a blackscreen. This does not happen if Desktop Capture is turned on or Shadowplay Instant Replay in general is turned off.

**osu!lazer version:** 2021.302.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6118177/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6118178/updater.log)
[database.log](https://github.com/ppy/osu/files/6118179/database.log)
[network.log](https://github.com/ppy/osu/files/6118180/network.log)
[performance.log](https://github.com/ppy/osu/files/6118181/performance.log)

**Comment by frenzibyte** [comment]
Running osu!lazer with ShadowPlay seems to cause issues at the moment.

Duplicate of https://github.com/ppy/osu/issues/10157

**Comment by atemerino** [comment]
I also noticed a crashlog in event viewer:

> The description for Event ID 1 from source NVIDIA OpenGL Driver cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> Unable to recover from a kernel exception. The application must close.
> 
> 
> Error code: 3 (subcode 7)
>  (pid=2616 tid=21324 osu!.exe 64bit)
> 
> Visit http://www.nvidia.com/page/support.html for more information.
> 
> The request is not supported
