### ISSUE TITLE
Starting osu causes compositor crash

### ISSUE THREAD

**Issue by Zarcix** [ppy/osu#12001]
**Describe the bug:** 
When I start the game, the compositor crashes without any error output in terminal. After closing the game, the compositor returns to normal.

Compositor = kwin_x11
System Information: 
Arch Linux - 5.11.4-xanmod - NVIDIA GTX 770 & GT 710 - RAM 32
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/42502671/110832067-c12e5b00-824f-11eb-9860-fe802df2d10b.mp4

**osu!lazer version:** 

2021.312.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/6124972/database.log)
[network.log](https://github.com/ppy/osu/files/6124973/network.log)
[performance.log](https://github.com/ppy/osu/files/6124974/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6124975/runtime.log)

**Comment by bdach** [comment]
I'm not sure what you expect us to do with this issue report if there is "no error" from the compositor. I don't even know whether you're using x11 or wayland. From what I can tell right now it might be even the compositor's fault. I know for sure I can use another compositor (`compton`) with the game just fine.

I'm closing this until actionable information is actually provided.

**Comment by matheusfsreinert** [comment]
Are you sure it's crashing? Some fullscreen applications disable kwin when they start running and re-enable and they're closed. You can disable that on the compositor settings. I can use `kwin` and `compton` just fine with lazer
