### ISSUE TITLE
"Revert to default" tooltip appears when its button is not visible

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#12004]
**Describe the bug:** As title. I'm pretty sure that the tooltip should _not_ appear when the revert-to-default button is not visible.

**Screenshots or videos showing encountered issue:** 
![example 1](https://user-images.githubusercontent.com/43073074/110861788-eefeb880-82be-11eb-986d-7e49348966c8.png)
![example 2](https://user-images.githubusercontent.com/43073074/110861796-f2923f80-82be-11eb-9fd9-25c4b125206a.png)

**osu!lazer version:** 2021.312.0

**Comment by bdach** [comment]
side effect of `AlwaysPresent`, it looks like... should use `HasPendingTasks` I think, although at this point I don't know.
