### ISSUE TITLE
JACK support

### ISSUE THREAD

**Issue by vunyunt** [ppy/osu#1200]
JACK is a low latency audio library. With the existing audio subsystem audio latency is still sub par compared to JACK enabled applications, even after playing with the value of `Bass.DeviceBufferLength`, `Bass.PlaybackBufferLength` and `Bass.UpdatePeriod`.

From my understanding, Implementing JACK version of TrackBass and SampleBass (and other necessary classes if any), and updating the  references, presumably giving user the option to choose between default and JACK implementation (plus buffering options) under options menu or configuration file would do the trick.

I am willing to work on this. However I am new to github collaboration, and also I would like to know the audio subsystem (of Osu!) better before attempting to implement this, so any guidance would be appreciated.

Thanks in advance!

**Comment by peppy** [comment]
This looks like it requires a local server application to be installed.

i'm not sure which latency you're talking about with bass, but as can be seen with osu-stable (which also uses bass), it can be close to zero.

**Comment by vunyunt** [comment]
Yes it would require Jack to be install and started. A warning could be displayed on the option so that users who don't have Jack don't enable it (or maybe detect if jack is running).

As for the latency, I also tested with osu-stable. I always have to use some level of negative global offset to match my keyboard sound with the music, with hitsound disabled (otherwise hitsound would just sound off beat).

The value needed ranges from about 35ms (using Windows 10, all sound effects disabled) to 130ms (Wine 2.x, no tweaks).

My system specs: AMD FX 8350 w/ 4.5ghz oc, GTX 960, Asus A5M99X evo r2.0 motherboard. While not a particularly powerful system, it should be good enough for this application. (I am able to get unnoticeable audio latency with other application such as MuseScore (under JACK), and ZynAddSubFX (under WASAPI exclusive mode instead of JACK)).

I have also tested with my friend's macbook pro (with a intel core i-5 processor) under Windows it still behaves the same way.

I will make a keysound to hitsound audio recording, compared to JACK enabled application, and update this with a link to youtube. However I can only demonstrate with the AMD system right now.

**Comment by peppy** [comment]
Let's ignoring setting offsets (which isn't really related to IO path latency).

The better solution for improving latency should be to support OpenAL/WASAPI/ASIO rather than something which requires explicitly installing more software on the system to benefit from.

Either way, this is a framework level issue to tackle, as all audio interfacing is done there. [Here's an existing issue](https://github.com/ppy/osu-framework/issues/705) going in the same direction.

**Comment by vunyunt** [comment]
I agree that offset don't fix latency, that's why I have to disable the hitsound entirely, just for the music to play earlier to sync up with my keysound.

I didn't know there is an existing related issue, thanks for pointing me to the direction.

Implementations that does not require additional software sounds good. However, as far as I know Linux don't have ASIO or WASAPI (I don't know if OpenAL provides low latency audio as I am not familiar with that).

Would it be appropriate to implement, as the existing issue proposed, multiple audio backend? In that case, a default backend (bass) will be good for most users, and other backends are also an option for people who want low latency (or maybe even for compatibility). In this case, it would be a "extendable" system where backends can be added (and only shown if detected to be available as the existing issue stated).

Again, I am willing to work on this. On the JACK side, I find the JackSharp library promising. For ASIO or WASAPI with bass it looks a bit more involved (assuming that it is not just a flag under bass, as I did not find a relevant flag in device initialization). I am not very familiar with bass but I am willing to learn with documentation.

Lastly, should this issue be closed/moved to the existing issue? Sorry for my lack of familiarity of rules in this issue system.

**Comment by peppy** [comment]
Yeah I mean it does look like JACK is a feasible solution for non-windows platforms (where proprietary solutions are not available). It would probably need to be implemented in a way where it doesn't make itself known unless JACK is installed on the host - ie. extra audio devices would just show up in the settings list.

Either way, this discussion should probably be moved to the framework, as I previously mentioned. If you need any help along the way with git or implementation, make sure to jump on our discord.

**Comment by peppy** [comment]
One thing to note is to make sure all libraries you add to the project are targeting .NET standard (1.3ish or higher), since we're currently moving in that direction for better cross-platform support.
