### ISSUE TITLE
Invalid client hash while attempting to play playlists on latest release binary (2021.312.0)

### ISSUE THREAD

**Issue by maotovisk** [ppy/osu#12002]
It happens just after you press the play button at a map, my example used the latest spotlights playlist. I assume it also happens to multiplayer. Some people confirmed that it happens with them too. 

![example](https://user-images.githubusercontent.com/20617307/110844763-914f7980-8288-11eb-8a76-939ae65c2794.gif)

**osu!lazer version:** 2021.312.0

**OS:** Windows 10 Pro 2004 64bit

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6125568/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/6125569/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6125570/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6125571/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6125572/updater.log)
[database.log](https://github.com/ppy/osu/files/6125573/database.log)
[network.log](https://github.com/ppy/osu/files/6125574/network.log)

**Comment by officialrestaurant** [comment]
Same for me. [screenshot](https://i.imgur.com/vO5ALu0.png)

**Comment by frenzibyte** [comment]
Seems like client hash of latest release isn't added to database for Windows, macOS works fine. (cc @peppy)

**Comment by peppy** [comment]
For issues like this, please send an email to accounts@ppy.sh or pe@ppy.sh in the future.
