### ISSUE TITLE
Crash on toggling "Beatmap Skins" during an autoplay run

### ISSUE THREAD

**Issue by xzCobra** [ppy/osu#12007]
**Describe the crash:** 
When I try to toggle beatmap skins on *any* autoplay run, the game will crash
I managed to get this to happen on multiple songs:
Seasons - DragonForce (Dark Clouds Falling, mapped by ItsWinter)
Sky - James Portland (Master, mapped by handsome)
Black Rover - Vickeblanka (Empyrean, mapped by zhu)

**Screenshots or videos showing encountered issue:** 
[Streamable | Seasons - DragonForce](https://streamable.com/yseol9)

**osu!lazer version:** 
2021.312.0

**Logs:**
[Seasons - DragonForce](https://pastebin.com/u/xzCobra/1/mp3B2hR5)
[Sky - James Portland](https://pastebin.com/u/xzCobra/1/5uJKmJPd)
[Black Rover - Vickeblanka](https://pastebin.com/u/xzCobra/1/4XbVsK6F)

**Computer Specifications:** 
CPU: Intel Core i7-8086K
GPU: NVIDIA RTX 2080 Ti
RAM: 32GB Corsair Platinum 3200MHz

**Comment by bdach** [comment]
#5798
