### ISSUE TITLE
Unable to change lobby settings after start when user left mid game

### ISSUE THREAD

**Issue by iamkyaru** [ppy/osu#12010]
**Describe the bug:** When the host starts a game with one or more lobby participants and leaves right after that, the host is unable to change any lobby settings (the beatmap in this case) but only when one(?) or all players leave in the middle of the game. The following error occurs: "An unexpected error occurred invoking 'ChangeSettings' on the server. InvalidStateException: Attempted to change settings while game is active."

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/28540206/111037061-c98abf80-8422-11eb-82bc-4c90196c90d7.png)

**osu!lazer version:** Lazer 2021.312.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6135136/database.log)
[network.log](https://github.com/ppy/osu/files/6135137/network.log)
[performance.log](https://github.com/ppy/osu/files/6135138/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6135139/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6135140/updater.log)

**Comment by bdach** [comment]
To clarify: At the point at which you attempted to change the settings, were there any players still playing the map? If so, then I'd say this is intended; otherwise it's a bug (seems to be server-side, too).

**Comment by iamkyaru** [comment]
Maybe I didn't write that correctly but all users to were playing the map have left the room, so there were only players left that could click on "Ready". Since then I was unable to change any settings.

**Comment by bdach** [comment]
Thanks, that clarifies things, and indicates that this might require looking into.

On one side note, though, from the log it looks like you've only tried to change the map once - I'm thinking that if one of the other players hard-aborted their game (via crashing out/killing the process), it might have taken a while for the server to notice that the connection has been broken.

**Comment by iamkyaru** [comment]
Yep, that's very likely because the one who left the lobby didn't quit normally. But changing the settings didn't work either after many minutes where I wrote this issue, so osu!lazer needs some implementation to verify the lobby's state and the playing state of the users?

**Comment by bdach** [comment]
The server [already has clean-up logic if a disconnection is detected](https://github.com/ppy/osu-server-spectator/blob/effdda467a17f4b76740e321e0b62f59d131eb6f/osu.Server.Spectator/Hubs/StatefulUserHub.cs#L69-L74). The big question is why it didn't fire in this case.
