### ISSUE TITLE
No iPad Magic Keyboard input when using touch on iPad Pro

### ISSUE THREAD

**Issue by blweldon2** [ppy/osu#12019]
Keypresses are only detected when using the integrated trackpad or external mouse. When playing with touch or Apple Pencil, keypresses are ignored from the iPad Magic Keyboard. This was previously working many months ago, but has not started working again as of 2021.312.0. Device is iPad Pro 12.9 2018.

**Comment by peppy** [comment]
Looks to work fine here. Are you sure you have 'disable mouse buttons during gameplay' enabled?

**Comment by blweldon2** [comment]
I’ve tried playing with that option both enabled and disabled. I used to have mouse buttons disabled when it worked. Would a video or logs help at all?

**Comment by peppy** [comment]
- does the same thing happen at song select? ie can you use the arrow keys to change beatmap selection while dragging on the screen?
- a video may be helpful, but make sure to turn on "always show key overlay" first.

also please specify the osu! build, iOS build and hardware model you are using.

**Comment by blweldon2** [comment]
osu! build: 2021.312.0
iOS build: 14.5 beta 4 (problem has existed on every major version of iOS 14)
Hardware: iPad Pro 12.9 2018 w/ Magic Keyboard

- On song select, I can use the arrow keys to scroll through songs while my finger or pencil is on the screen, so the problem appears to exist exclusively in gameplay.
- The video was actually useful for me. The game is constantly reading a left button input when my pencil is on the screen despite mouse buttons being disabled, so only tapping with the right button works. [Test Video](https://youtu.be/HnQWDptpwgs)

**Comment by peppy** [comment]
That may be due to touch input changes we made recently. In theory, disabling mouse buttons should stop that from happening - can you confirm this is not the case? If so we may be able to fix it via that setting for now.

**Comment by blweldon2** [comment]
Mouse buttons are disabled in the video I recorded, which shows the consistent button press.

**Comment by Joehuu** [comment]
FWIW, that setting doesn't disable touch on android too.

**Comment by blweldon2** [comment]
For now, removing M1 from the left button in settings allows the game to be played normally. I can just add flip the key mapping back and forth until the issue is formally fixed.

**Comment by ThatsNiceGuy** [comment]
this has been an issue for a bit but I thought it was intended. With “ignore mouse buttons” turned OFF, touching the screen still registers as mouse button 1, so you are unable to stream using your keyboard keys when touching the display
