### ISSUE TITLE
Add the ability to access beatmap files from the editor

### ISSUE THREAD

**Issue by peppy** [ppy/osu#12029]
A (relatively) common paradigm for a mapper is to perform operations on the `.osu` or `.osb` files contained within a beatmap. This can either be copy/pasting the raw code itself, or drag-dropping the files into a third party program to perform mutation or inspection.

We should give the user a way to access the raw files on demand, likely creating a temporary folder on disk, locking the game interface, and waiting for the user to perform operations, at which point they would press a button in the game and the folder would be cleaned up.

An alternative may be to *always* follow this paradigm on entering the editor, pulling the files out when entering (as a background operation?) to allow for ongoing edits, and using a `FileSystemWatcher` to handle any external changes. This implementation is obviously a higher bar in terms of complexity.

**Comment by yyny** [comment]
We don't necessarily need `FileSystemWatcher` for synchronization (Although that would be more snappy and less intrusive), we can simply check for file changes whenever the game client regains focus. I would recommend that as a start for anyone looking to implement this.

**Comment by frenzibyte** [comment]
Whether this needs `FileSystemWatcher` or not probably depends on how the implementation goes, it's a small detail to even care about currently.

**Comment by Joehuu** [comment]
Implemented in https://github.com/ppy/osu/pull/28800.
