### ISSUE TITLE
Missing metadata fields

### ISSUE THREAD

**Issue by UndeadCapulet** [ppy/osu#12022]
Current setup panel is missing several important metadata fields:
UnicodeArtist, UnicodeTitle, Source, Tags, and also perhaps the website genre tags buttons if those are intended to be included.
https://puu.sh/HpONa/dd1dd821bf.png vs. https://puu.sh/HpONr/7965ebf8c8.png

**Comment by frenzibyte** [comment]
Closing as a duplicate of https://github.com/ppy/osu/issues/2434, which tracks implementing everything remaining for the song setup screen.
