### ISSUE TITLE
Accuracy can round up to 100%

### ISSUE THREAD

**Issue by TTTaevas** [ppy/osu#12036]
**Describe the bug:** I was playing osu!catch on osu!lazer, and almost got an SS on a map, missing only one droplet.
However, despite not SS-ing, my accuracy still showed 100.00%.
I don't think it's intended for the game to show an accuracy of 100.00% for plays that aren't SS, my play should probably show 99.99% or something like that.

**Screenshots or videos showing encountered issue:** ![osu_2021-03-17_19-59-09](https://user-images.githubusercontent.com/67872932/111523812-fceb8800-875b-11eb-9e4d-7ceb13547792.jpg)

**osu!lazer version:** 2021.312.0

**Comment by peppy** [comment]
Checking back on `osu-stable`'s code, it looks like this same scenario is not guarded there either. I guess it's just more common on lazer due to the different scoring algorithm allowing getting a lot closer to 100%?
