### ISSUE TITLE
No Audio Output with Pulse Audio and Jack audio installed

### ISSUE THREAD

**Issue by 641i130** [ppy/osu#12037]
Upon opening osu lazer for the first time, no audio is outputting to my default audio. I think this is related to me install jack audio on my system a while ago though I don't remember when I did this.

**Screenshots or videos showing encountered issue:** 
No matter what audio setting I change to, I get these errors (besides the hdmi outputs) like its trying to connect to jack audio when I think I'm currently using pulse audio.

```Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```
![image](https://user-images.githubusercontent.com/46945263/111528674-715c0200-872f-11eb-9f1c-df31c585c991.png)

**osu!lazer version:** 
2021.312.0

**Logs:**
https://clbin.com/tBP0n
(Doesn't look like there's anything useful in there)

**System:**
OS: Arch Linux x86_64 
Kernel: 5.10.17-1-lts

**Comment by bdach** [comment]
Sorry, but this does not look like the problem of the game. You will have to troubleshoot this yourself. I can't say for sure without being able to inspect your particular setup but that jack server error (`is not running or cannot be started`) is 99% likely to be the cause of this BASS error.

**Comment by jai-x** [comment]
As a more general point, we've had lot of reports of audio releated crashes on Linux and most of the time it's from poor audio confiuration on the users end. I would try and search "audio linux" in the closed issues and see if there's any related issues that can help you troubleshoot.
