### ISSUE TITLE
Add the Waveform as an overlay to the mania editor

### ISSUE THREAD

**Issue by SurfChu85** [ppy/osu#12031]
**Describe the new feature:** 
Aside from the timeline, that shows the waveform above the editor, an overlaid waveform on the editor will complement the default snap lines that are currently being used. This will make identification of the more "obscure" snappings on notecharts/beatmaps that focus more on the technical side of charting/mapping.

**Proposal designs of the feature:** 
An example of this being implemented is on the ArrowVortex chart editor for StepMania
![image](https://user-images.githubusercontent.com/29819386/111459132-41bff080-8755-11eb-9999-ce0c7e4ef123.png)

**Comment by peppy** [comment]
Not sure how useful this will be when you already have snap lines present – even if it shows you detail that you otherwise wouldn't see, you still can't snap to the waveform itself. So unless you're planning to use it as a hint and then trial-and-error switch through the snap divisor until you find the one you are looking for...?

**Comment by SurfChu85** [comment]
> So unless you're planning to use it as a hint and then trial-and-error switch through the snap divisor until you find the one you are looking for...?

Yep, that's what I meant about complementing the snap divisors.

**Comment by sr229** [comment]
I wouldn't exactly like the idea of this kind of design, probably a more greyscale kind of graphing so there's more visibility on things like the snap lines or timing points (if we're going to visualize them in-editor).

**Comment by peppy** [comment]
It's already visible in the timeline for now, so I'm not even sure it's relevant to put it in the playfield as done here. Seems more like a stylistic change than a functional one.
