### ISSUE TITLE
Playing certain patterns after Reversing Order (Ctrl +G) on Editor causes Unhandled Exceptions

### ISSUE THREAD

**Issue by maotovisk** [ppy/osu#12038]
**Describe the crash:** 
After Selecting a few circles and sliders and reversing them (using `Ctrl`+`G`) and playing the pattern (through the editor) causes a `Unhandled Exception` which leads to a eventual crash if the pattern is long enough.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/20617307/111532016-036e0580-8744-11eb-8852-c0b11e637e8e.mp4

**osu!lazer version:** 2021.312.0

**Logs:**
[performance-draw.log](https://github.com/ppy/osu/files/6159100/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6159101/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6159102/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6159103/updater.log)
[database.log](https://github.com/ppy/osu/files/6159104/database.log)
[network.log](https://github.com/ppy/osu/files/6159105/network.log)
[performance.log](https://github.com/ppy/osu/files/6159106/performance.log)

**Computer Specifications:** 
CPU: AMD FX 6300 @3.5GHz
RAM: 8GB 1866MHz DDR3
SSD: Kingston 240GB
OS: Windows 10 Pro 2004

**Comment by bdach** [comment]
Can reproduce, but not universally.

Map is https://osu.ppy.sh/beatmapsets/580215#osu/1290618, can be reproduced by reversing the 7-note pattern after 0:53:558 as shown on the video.

**Comment by maotovisk** [comment]
I didn't explore the optimal manner to reproduce it but i think any long chain is enough to cause a crash.
