### ISSUE TITLE
Z button randomly stops working

### ISSUE THREAD

**Issue by Inspraa** [ppy/osu#12033]
**Describe the bug:** At some point during a map, the Z button just stops responding to hits and the only way to fix it, is to restart the game

**Screenshots or videos showing encountered issue:** https://youtu.be/U_3jVT5cXHI

**osu!lazer version:** 2021.312.0

**Logs:** Apparently the bug isn't reported in any of the .txt files. 

![image](https://user-images.githubusercontent.com/80841939/111504569-7c735a00-8750-11eb-9959-316c40e40745.png)

P.S, at the time of this edit, the time is 6:43 PM for me.

**Comment by bdach** [comment]
You have not provided sufficient information to begin figuring out the problem. I can assure you the button works here.

* What input devices are you using? Mouse+keyboard? Tablet?
* If you're playing on a tablet, do you have mouse buttons disabled in gameplay?
* Can you show in any way what inputs are being performed?

**Comment by Inspraa** [comment]
**What input devices are you using? Mouse+keyboard? Tablet?**

Mouse: Glorious Model O Matte Black
Keyboard: HyperX Alloy FPS Brown Switches
Tablet: Wacom Intuos CTL-490

**If you're playing on a tablet, do you have mouse buttons disabled in gameplay?**

Yes, i do. 
![image](https://user-images.githubusercontent.com/80841939/111505424-45ea0f00-8751-11eb-9f9f-9ac4e9fa8075.png)

**Can you show in any way what inputs are being performed?**

Sadly i cant, i think.

**Comment by bdach** [comment]
> ![image](https://user-images.githubusercontent.com/80841939/111505424-45ea0f00-8751-11eb-9f9f-9ac4e9fa8075.png)

This screenshot is showing the setting to be *off*. Therefore, mouse inputs are *not* disabled during gameplay.

Please try enabling that option and seeing if it helps.

**Comment by peppy** [comment]
Going to close this one for now. Please report back if you're still having issues with the mouse button disable setting *checked*.
