### ISSUE TITLE
You can open a multiplayer lobby twice, causing a crash

### ISSUE THREAD

**Issue by rednir** [ppy/osu#12040]
**Describe the crash:** 
Click a multiplayer lobby, and while the loading overlay is on screen, you are still able to press enter and trigger some errors. The main menu also stops functioning.

**osu!lazer version:**  2020.312.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6159783/runtime.log)

**Video**: https://streamable.com/y3o7gv

**Comment by bdach** [comment]
The video doesn't work. Thankfully the log is likely to be enough to go off of.

Note that the multiplayer exception is not the only thing that's visible there, there's also a tripped assertion that looks similar to https://github.com/ppy/osu-framework/issues/3461.

**Comment by rednir** [comment]
Probably won't be needed, but uploaded the video to streamable just in case.
