### ISSUE TITLE
difficulty speed multiplier in the timing section rounds to one decimal place

### ISSUE THREAD

**Issue by DeviousPanda** [ppy/osu#12041]
right now if i enter a speed multiplier of 1.46 for example, it will round to 1.5, in stable the slider velocity rounds to two decimal places 

a solution to this would to actually allow alot more precise slider velocity changes than even stable has, as there are many applications for more precise slider velocity rates than 2/3 decimals

**Comment by bdach** [comment]
Yes, this is a known shortcoming. New maps (not coming from stable) have precision set to 0.1, while maps from stable have precision off to avoid mangling them, which is why there is so many decimal places visible in that case.

**Comment by peppy** [comment]
Anything using more than two decimals sounds like you are looking to do tweening between values? If that's the case, we'll be implementing that in a different way. Let's stick to 2DP for the time being.
