### ISSUE TITLE
Skin using wrong colors, instead of just blue and white 

### ISSUE THREAD

**Issue by TakuEz** [ppy/osu#12051]
**Describe the bug:** 
There's a skin I use on osu stable that normally uses a blue and white color scheme. When I imported my skins to osu lazer, the skin wouldn't use the blue and white color scheme, and would only use really vibrant red green yellow and blue colors for sliders/ hit circles. Ive tried reimporting the skins over and over to no avail. Here is the skin link: https://www.mediafire.com/folder/bxwutdn2cpr5y/-Gawr_Gura-  heres some screen shots of the skin (how its supposed to look: 
![image](https://user-images.githubusercontent.com/80863693/111556824-c9136100-8761-11eb-99c8-395178ea03d8.png)
![image](https://user-images.githubusercontent.com/80863693/111556874-f102c480-8761-11eb-98b1-486ea01cf785.png)

I have modified the cursor in the pack, but i redownloaded the original unedited version and deleted the skin from osu stable and osu lazer, and it still had the same issue. I'm back to using the modified version.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/80863693/111557065-53f45b80-8762-11eb-99b4-320f6166a721.png)
![image](https://user-images.githubusercontent.com/80863693/111557093-6373a480-8762-11eb-9e38-36c75be1cb52.png)
The screenshots look a bit weird( pixely / no aa) but its perfect ingame, besides the colors. I also am using the original skin in lazer, not the edited one i use in stable, as i haven't taken the time to import my skins again from stable, as it didn't work last time. But when i tried with the edited skin, it didn't work, like i said.
Heres how it looks in lazer: 
**osu!lazer version:** 
2021.312.0
**Logs:**
[performance.log](https://github.com/ppy/osu/files/6160573/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6160574/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6160575/updater.log)
[database.log](https://github.com/ppy/osu/files/6160576/database.log)

**Comment by Joehuu** [comment]
This is due to the `skin.ini` having a space after `[Colours]*space*`. For now, you can remove that space and it'll work.
