### ISSUE TITLE
Startup default screen mode should be exclusive full screen

### ISSUE THREAD

**Issue by peppy** [ppy/osu#12053]
Currently, a fresh install of lazer will startup in windowed mode. This is probably not a great default.

**Comment by harshavb** [comment]
The osu framework is actually what sets the default to windowed mode - should i just change it there, or do we want the framework to still default to windowed mode and osu! to default differently?

**Comment by peppy** [comment]
Should just be changed locally for now. We can reconsider framework-side at a later point in time.

**Comment by owen-young** [comment]
I am currently working on this issue.

**Comment by owen-young** [comment]
This may be a silly question (I am new to developing osu), but should it "remember" if the user changes the setting from full screen to anything else? Right now it launches in full screen, can be changed to windowed, but when launched again, it goes back to full screen.

**Comment by peppy** [comment]
It should persist, yes. You only want to change the default, not set the value each startup. I believe there is an override in `Game` for this precise purpose.

**Comment by owen-young** [comment]
To my knowledge, there is not an `OsuSetting` (if that is what you're referring to). I was searching for `WindowMode` without much success, changing the default value the dropdown is set to in `LayoutSettings` did not yield the desired effect. My apologies for the lack of familiarity with the codebase - perhaps I'm looking in the wrong places.

**Comment by peppy** [comment]
see https://github.com/ppy/osu-framework/blob/b82b13e2f802b06f3d3a9dbd20c297c95709f7b2/osu.Framework/Game.cs#L76

**Comment by owen-young** [comment]
Thank you, I was not looking at the osu-framework. Is the proper way to test this just to do a fresh clone and launch it? I implemented the method, but I'm worried that settings from previous installs are being read (if that is possible; I would like to rule this out to make sure my code is the thing causing the problem).

**Comment by peppy** [comment]
You can test by deleting your configuration file. You probably want to read and understand where that is stored.

**Comment by owen-young** [comment]
I assume you don't mean `osu!.<login name>.cfg`? I might be looking at the wrong place, but in `StorageConfigManager` it lists the file name as `storage.ini`, which does not exist in my directory. There is a mention of `.dev.ini`, but no files exist in my directory with that extension. osu-framework has `Filename` default to `game.ini`, but that does not exist either. All of the `.ini` files I found were related to skinning. I feel like I'm missing something here, I'm sorry.

**Comment by frenzibyte** [comment]
Sounds you're on the wrong directory, should be `%AppData%/osu` iirc

**Comment by owen-young** [comment]
Thank you! I deleted `framework.ini` to rebuild it using the new defaults and it appears to work properly.

**Comment by bdach** [comment]
Fixed by referencing PR.
