### ISSUE TITLE
Render at native resolution option in settings

### ISSUE THREAD

**Issue by Elabar** [ppy/osu#12068]
**Describe the new feature:** 
In the old OSU! client, we have an option to render the selected resolution in native resolution. Which is also enabled by default. Can it be added back into OSU!Lazer?

**Proposal designs of the feature:** 
Take a look at the old client's "Render at native resolution" setting.

Here's a photo showing the setting.
![image](https://user-images.githubusercontent.com/15872787/111683462-7c627f80-8860-11eb-8b2d-2be46ef2c7df.png)

**Comment by bdach** [comment]
A similar effect can be achieved using the "Screen Scaling" options:

![osu_2021-03-18_20-14-02](https://user-images.githubusercontent.com/20418176/111684096-8ebfc780-8826-11eb-9229-232094d9d201.jpg)

So unless it is absolutely necessary to have the inner content adhere to a particular resolution from the dropdown (which is the only thing that isn't possible to replicate exactly with lazer's settings), I'm not sure I see the point in bringing back that old setting.

**Comment by peppy** [comment]
Yep, this is already covered by screen scaling. We do need to make this more approachable (better settings UX) but this is definitely already implemented.

**Comment by Elabar** [comment]
Opp, sorry for missing out the scaling option. But is it possible to make it support up to two decimal points?

My current native resolution is 3440x1440, my targeted resolution is 1920x1080

if we calculate a bit
horizontal scale = 1920/3440 = 0.5581
vertical scale = 1080/1440 = 0.75 (This works just fine)

As you can see, I can't drag the scale to 55.81%.

It is small details, but it does matter imo.

**Comment by Elabar** [comment]
nvm, i just edited the ScalingSizeX and ScalingSizeY in the game.ini file
