### ISSUE TITLE
Game crash when toggling visual setting

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu#12067]
**Describe the crash:** 
- Play any map with autoplay.
- Wait until the map start.
- Try toggling the visual setting on and off.
- The game crash.

Some observation:
- Only happen when toggling beatmap skins/colours/hitsounds.
- Doesn't happen in previous release.

Probably framework issue from what I read in the log.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/5dn628

**osu!lazer version:** 2021.312.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6166502/runtime.log)

**Comment by bdach** [comment]
#5798
