### ISSUE TITLE
Game freezed when moving slider control point.

### ISSUE THREAD

**Issue by Ch4t0n** [ppy/osu#12063]
**When messing around on the editor, i was moving the last control point of a slider and it suddenly made the game freeze then shows a low res slider that is pointing out in 2 directions ? Then it went back to normal. It must be because of how the slider behaves when it suddenly leaves the screen and points at somewhere so far it makes the game's framerate really low and drains almost everything.** ***Spooky stuff.***
![raerarearearaere](https://user-images.githubusercontent.com/80898625/111629115-37ebcb00-87f1-11eb-9594-bd2d5d4ffe2f.PNG) 
But yeah it just does that and that's so weird and unexpected.

**Heres a video showing what happened :**

https://user-images.githubusercontent.com/80898625/111628241-4dacc080-87f0-11eb-8078-462e1b60ba59.mp4

**osu!lazer 2021.312.0**

**Comment by peppy** [comment]
Thanks for your report. This is already being tracked via https://github.com/ppy/osu/issues/5538.
