### ISSUE TITLE
Inconsistent opacity on fruit droplet elements

### ISSUE THREAD

**Issue by sr229** [ppy/osu#12082]
**Describe the bug:** 

During a multiplayer test-play session someone raised to me regarding inconsistent opacity in fruit droplets. I've yet to verify the behavior from stable vs Lazer, but this may be the case.

**Screenshots or videos showing encountered issue:** 

**Lazer gameplay**

https://user-images.githubusercontent.com/14976516/111787201-a0be6a80-88f9-11eb-940f-c5927189a054.mp4

**Stable Gameplay (baseline)**

https://user-images.githubusercontent.com/14976516/111788903-93a27b00-88fb-11eb-8542-9eda7491db3d.mp4

**osu!lazer version:** 2020.312.0

**Comment by peppy** [comment]
This looks like it's combo colour related (especially as it only affects every second set of droplets). Are you sure you're using the same override settings on both games?

If so, please include the skin for reference, and show your visual settings selection on stable.

**Comment by sr229** [comment]
Looks like it's not a bug, but rather an oversight from their reporter's side due to beatmap colours. Closing.
