### ISSUE TITLE
Song selection (Button "mods" and "options")

### ISSUE THREAD

**Issue by Drison64** [ppy/osu#1208]
Hi, i found a issue in osu!lazer, in Song selection menu, when tab options is opened and i will open mods, options tab should close, either on mods should close if options opens. Sorry for my english :D

**Comment by Kontorted** [comment]
Wait what?
From what I can gather, you want to talk about implementing a "Feature", namely closing the options tab when your mods tab opens. This wouldn't really be an issue, since it isn't breaking anything.
