### ISSUE TITLE
[Mode Request] osu!runners

### ISSUE THREAD

**Issue by xzCobra** [ppy/osu#12081]
**Describe the new feature:** 
This gamemode would be a mix of catch and mania/taiko, with separate lanes for hitobjects you would have to "catch" (anybody got a better term?)
**Proposal designs of the feature:** 
didn't have time to design proper extra's yet (like icons and an editor) but [here](https://blog.ppy.sh/post/148831410818/a-little-framework-test) is some gameplay of the style that I'm talking about (basically lets bring this mode back to life)

**Comment by peppy** [comment]
We don't really take ruleset requests here, sorry. This does sound like "pippidon", though, one of the template rulesets.

**Comment by xzCobra** [comment]
oh, didn't realize that was the name of the ruleset. Oopsie!
