### ISSUE TITLE
Remove the message "Deleting backgrounds makes osu! ANGGGGGGGRRRRRRRRRRYYYYYYYYYYYYYYYY!" when starting a map.

### ISSUE THREAD

**Issue by FlagFlayer** [ppy/osu#12088]
**Describe the new feature:** 
Whenever the file for a map background is missing, a message appears when starting the map stating: "Deleting backgrounds makes osu! ANGGGGGGGRRRRRRRRRRYYYYYYYYYYYYYYYY!".

Example:
[Imgur](https://i.imgur.com/lL1QdZ6.jpg)

I personally find it infuriating that the game mocks me for removing background images which make me feel uncomfortable. I won't get into the legal issues of hosting some of these sexualising backgrounds, some depicting children, because I lack the legal expertise to do so. I don't want these images on my computer, hence I delete any background image on my PC that I don't approve of. 

While that process IS bothersome to do, I don't mind doing it for my own greater good, because it makes me a lot more comfortable playing this game when there ISN'T any content that could be considered "adult" on my client. However, being actively smack-talked by the game every single time I play certain maps for wanting to feel comfortable while playing? That is truly the last straw for me. It sours A LOT of the experience of enjoying this game.

Moreover, I'll add that some backgrounds were removed after the staff themselves deemed them inappropriate, and yet this message still appears! (e.g. [DJ YOSHITAKA - A Kiss for the FLOWER](https://osu.ppy.sh/s/79702)) A game mocking its own players due to staff removing inappropriate images. Completely and utterly ridiculous.

**Proposal designs of the feature:** 
Find & remove the code that triggers the message.

I personally won't be approving of any different message notifying of a missing background file either, since seeing that message so many times would be extremely draining.

**Comment by jai-x** [comment]
This repository is for development of osu!lazer.

Issues with osu!stable can be opened here: https://github.com/ppy/osu-stable-issues/
