### ISSUE TITLE
Sliderend hitboxes on the timeline could be made easier to select

### ISSUE THREAD

**Issue by DeviousPanda** [ppy/osu#12092]
right now the hitbox for sliderend selection on the editor timeline is only a few pixels wide 
![image](https://user-images.githubusercontent.com/80785742/111854156-b93c7e00-8915-11eb-823d-6f95a794f78b.png)
compared to stable which has the same hitbox size as slider heads and circles
![image](https://user-images.githubusercontent.com/80785742/111854189-e2f5a500-8915-11eb-94d5-d6e41d06d3d6.png)

while the sliderend hitbox doesnt need to be exactly the same as the slider head (as design changes could take priority over this), some form of enlarging the sliderend size would be a good quality of life change to the editor 

(split from https://github.com/ppy/osu/issues/12020)

**Comment by peppy** [comment]
While I'm not against making this larger, t;he hitbox on stable is actually the same as on lazer (please confirm this is the case at your end).

**Comment by DeviousPanda** [comment]
yeah the drag indicator for stable is the same width as lazer, but for selecting a sliderend (which isnt implemented yet anyways) you can do this by clicking anywhere inside the sliderend hitbox 
![image](https://user-images.githubusercontent.com/80785742/111854363-cb6aec00-8916-11eb-929e-93a3f187633a.png) (so this is able to select the sliderend by itself)

sorry for not making the distinction in my original post but its more for easy of access to select the slider end hitbox (although i didnt know they had the same hitbox length, and i think in retrospect this is what made me think it was smaller)

**Comment by peppy** [comment]
Closed by https://github.com/ppy/osu/pull/12396.
