### ISSUE TITLE
osu!lazer cannot detect Huion H950P tablet

### ISSUE THREAD

**Issue by owoDeveloper** [ppy/osu#12093]
**Describe the bug:** 
osu!lazer cannot detect Huion H950P tablet
No custom drivers running, however cursor is still moving via Windows Ink. I tried re-connecting tablet, re-open osu!lazer, restart Windows.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/77315866/111858957-87accc80-8980-11eb-8d6b-74553d5fd87f.png)

**osu!lazer version:** 
2021.320.0, of course

**Logs:**
[database.log](https://github.com/ppy/osu/files/6174905/database.log)
[network.log](https://github.com/ppy/osu/files/6174906/network.log)
[performance.log](https://github.com/ppy/osu/files/6174907/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6174908/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6174909/updater.log)

**Comment by peppy** [comment]
Please report issues with tablet compatibility over at https://github.com/OpenTabletDriver/OpenTabletDriver. Make sure to follow their issue templates when you do!

**Comment by owoDeveloper** [comment]
Understood. Thanks!

**Comment by owoDeveloper** [comment]
So I found that my tablet's product id is diffrent with newer one...
![image](https://user-images.githubusercontent.com/77315866/111860158-03127c00-8989-11eb-8e5e-c3e28118ff36.png)
The newer one uses product id 109, but older one uses 110 (or whatever other than 109)
My tablet (HUION_T172_180623) is an older version of Huion H950P, and OpenTabletDriver uses configuration for newer version (product id 109). That's why osu!lazer couldn't detect my tablet.
I'm going to buy a new tablet for osu! soon, so it's not a big problem for me lol. Nice work as always, anyway.

**Comment by peppy** [comment]
Please report this to OTD so it can be fixed for other with the same tablet, even if you plan to upgrade.
