### ISSUE TITLE
Add a vertical hit lighting effect after catching a fruit

### ISSUE THREAD

**Issue by Kimitakari** [ppy/osu#12095]
Stable not only uses a short horizontal hit lighting effect in the place but also a vertical hit lighting effect making sure that you've catched a fruit while looking at the middle of the screen and not to stare into the catcher.

The reason why it's important to have a vertical hit lighting effect because you can easily play the map without looking down the monitor. The only way you can look at the fruit without looking to anything is the combo number. With this added effect the gameplay in lazer would be much more visible while playing.

Stable hit lighting in full effect (with enabled full screen and 1920x1080):
![](https://puu.sh/HqPaP/c93f6c5846.png)

**Comment by abraker95** [comment]
In stable I don't like how this effect obscures/blends with the falling fruit, and is the main reason why I do not enjoy playing the osu!catch gamemode.

**Comment by Kimitakari** [comment]
Unfortunately the majority of players I've talked with during the Season Spotlight said that the current hit lighting feels nonexistent and said that it feels like you've been playing without them.

I didn't mentioned it should be reached to the top of the window but if that's your main critique then it could be cut in half above the combo number? At least being one of the options on how this could be implemented in the first place.

**Comment by bdach** [comment]
Any implementation of this should ensure that the hit lighting can be turned off via the "Hit lighting" setting option. As it'll also be skinnable, I imagine users will also be able to provide their own texture if they want a different one.

**Comment by Kimitakari** [comment]
Agree on the skinnable part. Originally you could technically turn it off in stable by changing the hit lighting to black with the 100% background dim and it would feel like you're playing without them in lazer. Right now it wasn't implemented and there's no current answer that it'll be featured or not.

**Comment by amberkowalski** [comment]
I'm interested in implementing this, however this requires design work(?). I don't mind copying stable or working from some sort of concept image / drawing, however I understand if its just easier for someone who knows what you guys want it to look like to implement it.

**Comment by bdach** [comment]
I do not believe design work is necessary here. I believe the current hit explosion still should be used on the lazer default skin, and the stable explosion sprite should be used for the stable/legacy default skin.

**Comment by amberkowalski** [comment]
Is it already skinnable? I thought I got the lazer effect on both classic and lazer skin.

**Comment by bdach** [comment]
[It is not skinnable.](https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Catch/UI/HitExplosion.cs) It should be, the same way numerous other skin elements are. I guess for completion you would also need details of how the explosion sprite animates on stable.

Note that given that the current implementation already uses object pooling, so it may not be very easy to get this working completely correctly if you're not very familiar with what pooling is or how it is done.

**Comment by amberkowalski** [comment]
That's what I thought I saw, I just got confused for a second. I'll see what I can do, thank you for the info!

**Comment by peppy** [comment]
We do have a design in mind for the default skin, so if implementing this I would do it for classic skin only for now (or keep that in mind when implementing and use the standard separation flow, leaving the default empty or copying the effect from osu!mania as a placeholder).

**Comment by amberkowalski** [comment]
I've kept the lazer hit lighting effect the exact same as it was before, and implemented support for having the legacy version of the hit lighting effect. How should I go about actually implementing the legacy effect? Is there a sprite somewhere with animation information that I'd need?

**Comment by peppy** [comment]
Here's the relevant code from `osu-stable`:

```csharp
        private void Explode(HitObject h)
        {
            if (ModManager.CheckActive(Mods.Cinema))
                return;

            float explosionOffset = OsuMathHelper.Clamp(((HitCircleFruits)h).CatchOffset.X, -catcherWidthHalf + catchMargin * 3, catcherWidthHalf - catchMargin * 3);

            if (!(h is HitCircleFruitsTick))
            {
                float scale = OsuMathHelper.Clamp(ComboCounter.HitCombo / 200f, 0.35f, 1.125f);

                pSprite exp1 = new pSprite(TextureManager.Load(@"scoreboard-explosion-2", SkinSource.Osu),
                                           Fields.Gamefield, Origins.CentreLeft, Clocks.Game,
                                           h.Position, 0.99f,
                                           false, h.Colour);
                exp1.Additive = true;
                exp1.Rotation = (float)(-Math.PI / 2);
                exp1.FadeOut(300);
                exp1.Transformations.Add(new Transformation(TransformationType.VectorScale, new Vector2(1, 0.9f),
                                                            new Vector2(16 * scale, 1.1f), GameBase.Time, GameBase.Time + 160,
                                                            EasingTypes.Out));
                spriteManagerAdd.Add(exp1);

                exp1.IsVisible = true;
                exp1.InitialPosition = new Vector2(explosionOffset, 0);
                caughtSprites.Add(exp1);
            }
            pSprite exp2 = new pSprite(TextureManager.Load(@"scoreboard-explosion-1", SkinSource.Osu),
                                       Fields.Gamefield, Origins.CentreLeft, Clocks.Game,
                                       h.Position, 1, false,
                                       h.Colour);
            exp2.Rotation = (float)(-Math.PI / 2);
            spriteManagerAdd.Add(exp2);
            exp2.Additive = true;
            exp2.FadeOut(700);
            exp2.Transformations.Add(new Transformation(TransformationType.VectorScale, new Vector2(0.9f, 1),
                                                        new Vector2(0.9f, 1.3f), GameBase.Time, GameBase.Time + 500,
                                                        EasingTypes.Out));

            exp2.IsVisible = true;
            exp2.InitialPosition = new Vector2(explosionOffset, 0);
            caughtSprites.Add(exp2);
        }

        private void ThrowFruit(bool happy)
        {
            if (!hitObjectManager.hitObjects[hitObjectManager.currentHitObjectIndex].LastInCombo)
                return;

            if (hitObjectManager.lastHitObject is HitCircleFruitsSpin)
            {
                //Spinner end
                foreach (HitCircleFruits f in caughtFruits)
                    bounceFruit(f, true);
                ((HitCircleFruitsSpin)hitObjectManager.lastHitObject).PlayActualSound();

                pSprite exp1 = new pSprite(TextureManager.Load(@"scoreboard-explosion-1", SkinSource.Osu),
                           Fields.Gamefield, Origins.CentreLeft, Clocks.Game,
                           Vector2.Zero, 0.99f,
                           false, Color.White);
                exp1.Additive = true;
                exp1.Rotation = (float)(-Math.PI / 2);
                exp1.FadeOut(800);
                exp1.Transformations.Add(new Transformation(TransformationType.VectorScale, new Vector2(0, 1.8f),
                                                            new Vector2(4, 2.2f), GameBase.Time, GameBase.Time + 500,
                                                            EasingTypes.Out));
                exp1.IsVisible = true;

                caughtSprites.Add(exp1);
                spriteManagerAdd.Add(exp1);
            }
            else if (happy)
            {
                //Happy combo
                foreach (HitCircleFruits f in caughtFruits)
                    bounceFruit(f, false);
            }
            else
            {
                //Sad combo
                foreach (HitCircleFruits f in caughtFruits)
                {
                    foreach (pSprite p in f.SpriteCollection)
                    {
                        GameBase.PhysicsManager.Add(p);
                        p.FadeOut(1000);
                        p.AlwaysDraw = false;
                    }
                }
            }

            caughtFruits.Clear();
        }
```

The `Explode` method is most relevant here. Hopefully this should be enough to put things into context.

![scoreboard-explosion-1@2x](https://user-images.githubusercontent.com/191335/113467052-6e754700-947b-11eb-9b0d-6b840dfcc3c5.png)
![scoreboard-explosion-2@2x](https://user-images.githubusercontent.com/191335/113467055-6fa67400-947b-11eb-9ce4-228ef21fe5e0.png)

**Comment by amberkowalski** [comment]
The current implementation creates hit lighting on droplets, is this something that you'd like preserved? Additionally, is that something that would make sense to be a skin setting? AFAIK the current osu skin.ini doesn't support setting that, so for legacy skins it would probably be forced to `false`? Sorry if I'm misjudging functionality, I'm still learning how everything fits together

**Comment by peppy** [comment]
It should behave how it does in stable, so droplets would need to be excluded I think. Probably passed in as a parameter so we can potentially allow customisation in the future of skinning. Shouldn't be exposing any new user-facing settings just yet though.

**Comment by amberkowalski** [comment]
Sounds good, I think for now I can just pass the `PalpableCatchHitObject` into the explosion as a reasonable solution for now.

**Comment by amberkowalski** [comment]
I'm curious as to how transforms are applied to the explosion sprites in stable, I'm currently having an issue where the exact same math code (as far as I can tell, would be nice to have another pair of eyes make sure I didn't mess up anything up) ends up working differently. I have a feeling its: transforms are applied differently, the parameters in `pSprite()` that I ignored because I couldn't guess were important, or my math's wrong.

[Code Here](https://gist.github.com/amberkowalski/e20ff32f7029f334f663ee67c91cbe28)

Video:
https://user-images.githubusercontent.com/4877041/113493365-477f3b00-94a4-11eb-94db-2f313e02756e.mp4

**Comment by bdach** [comment]
Can you link a pushed branch to check out or something? Easier to just look at that than to guess at a gist.

**Comment by amberkowalski** [comment]
[Here you go!](https://github.com/amberkowalski/osu/tree/ctb-hitlighting). Sorry about that, when I made the comment I wasn't in a nice spot to push it, I should have updated it with a link.

**Comment by bdach** [comment]
I believe the clamping is not working as intended because of a conflation of slightly different constants. Stable defines

```csharp
catchMargin = catcherWidth * 0.1f;
```

while you have

```csharp
hitExplosion.CatcherMargin = ALLOWED_CATCH_RANGE; // is 0.8
```

You could see how those are the same constant (stable's is measured as the margin from edges, while on your branch it's the width of the catching area), but due to that difference no actual clamping is taking place. I believe you'd want something like the following:

```csharp
hitExplosion.CatcherMargin = (1 - ALLOWED_CATCH_RANGE) / 2;
```

**Comment by amberkowalski** [comment]
Just wanted to check, are we looking for an exact perfect reproduction or stable or "looks pretty much like stable". I've got it looking like stable and it accomplishes what was requested from the issue. I've also consulted some ctb players and they also think it looks okay.

https://user-images.githubusercontent.com/4877041/113507058-e3915c80-950d-11eb-86f6-578c59b5ccd2.mp4

If this looks okay, I will open a PR. If there are any obvious flaws, I will fix them beforehand.

**Comment by bdach** [comment]
Obviously the closer the better, but it looks mostly like it should it's probably fine to PR.

What I can say for sure is that the PR should come with a visual test (so that the animation can be examined better). A visual comparison against stable would also be appreciated. If you are able to put together a video of a map with a juice stream down the middle and splice it such that one side shows stable and the other shows lazer, it would definitely go a long way.

**Comment by amberkowalski** [comment]
That's a good idea, I'll get that put together, fix anything horribly wrong if I see it, and make the final preparations for a PR.

**Comment by amberkowalski** [comment]
Here's how it looks so far, going to hold off on the PR and tune the vertical scale a little more, otherwise looks okay. The platter appears to be at a different height, but that wasn't changed by me so I'm not planning on addressing it.

https://user-images.githubusercontent.com/4877041/113508240-792fea80-9514-11eb-9dd7-c47f54d4c163.mp4

**Comment by bdach** [comment]
The catcher height difference will probably be more in scope of #12079.
