### ISSUE TITLE
2 cursors teleporting when starting osu!lazer

### ISSUE THREAD

**Issue by Adminbnc** [ppy/osu#12106]
**Describe the bug:** 
Whenever I open osu lazer it basically shows 2 cursors teleporting to one another and its very hard to control.

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/54418338/111870018-749afc00-8982-11eb-95f3-24c5ce640cfe.mp4

**osu!lazer version:** 
osu!lazer 2021.320.0

**Logs:*
[runtime.log](https://github.com/ppy/osu/files/6175551/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6175552/updater.log)
[database.log](https://github.com/ppy/osu/files/6175553/database.log)
[performance.log](https://github.com/ppy/osu/files/6175554/performance.log)

**Comment by peppy** [comment]
Please either close your tablet software or disable tablet support in the game. We are working on an eventual fix for this. This is mentioned in the changelog notes.
