### ISSUE TITLE
Lock aspect ratio always turns off when game restarted

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#12107]
**Describe the bug:** lock aspect ratio option always sets itself off every time lazer starts (on linux, havent tried on windows yet). i even tried to recreate the input.json file and still happens. but the tablet works fine and the other settings are not affected by this

**Screenshots or videos showing encountered issue:** 
![osu_2021-03-21_05-32-07](https://user-images.githubusercontent.com/41866328/111871180-cd3eb900-89c3-11eb-89de-1082564bb796.png)

**osu!lazer version:** 2021.320.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6175651/database.log)
[network.log](https://github.com/ppy/osu/files/6175652/network.log)
[performance.log](https://github.com/ppy/osu/files/6175653/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6175654/runtime.log)

**input config:**
[input.json.txt](https://github.com/ppy/osu/files/6175655/input.json.txt)

**Comment by peppy** [comment]
That is because this is indeed not saved. Is there a reason you'd require it to be? Do you adjust your area that often?

**Comment by enoslayd** [comment]
Ohhhhhh. I thought its a bug cause i noticed it when i received a message "Device: failed to set tablet output 02-B0-02", tried to troubleshoot that and when i solved that, the aspect ratio thing still happen.... If thats the case then maybe we can close it......

**Comment by X9VoiD** [comment]
"Device: failed to set tablet output 02-B0-02" but input still working means that the tablet was already initialized to vendor interface mode. The tablet refused the attempt for another initialization and in such case OTD continues and just logs it.

We have no way of knowing if the tablet is already initialized so we're always logging it as an error (in case it actually caused a problem with reading raw data).

**Comment by peppy** [comment]
Going to close this for now, as it's not a super simple one and probably not required.
