### ISSUE TITLE
DeviceIOException on start-up for unsupported tablet

### ISSUE THREAD

**Issue by r00ster91** [ppy/osu#12101]
**Describe the bug:** I'm getting a `DeviceIOException: Unable to open HID class device (OK).` right on startup only when my tablet is connected. It is the XP-Pen Star 06 Wireless which is not supported by OpenTabletDriver.
By the way, I have created [an issue](https://github.com/OpenTabletDriver/OpenTabletDriver/issues/890) on the OpenTabletDriver repository to add support for this tablet and I'm being asked to export my diagnostics. Is it possible to retrieve those through osu! somehow so that I don't have to install OpenTabletDriver?
Anyhow, this should probably be a more user-friendly error.
I don't get this error if I install my tablet's drivers manually.

**Screenshots or videos showing encountered issue:** ![Screenshot from 2021-03-20 11-48-20](https://user-images.githubusercontent.com/35064754/111867148-78bf1d80-8972-11eb-832d-a85c4f06ae66.png)

**osu!lazer version:** 2021.320.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6175343/database.log)
[network.log](https://github.com/ppy/osu/files/6175344/network.log)
[performance.log](https://github.com/ppy/osu/files/6175345/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6175346/runtime.log)

**Comment by bdach** [comment]
Linux distribution do not allow userspace applications to read device streams directly, contrary to Windows. Please read [this OpenTabletDriver FAQ entry](https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#the-driver-fails-to-open-the-tablet-deviceioexception) for a resolution.
