### ISSUE TITLE
Game freezes when the scrolling the carousel

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#12108]
**Describe the bug:** Maybe it's again related to my large number of beatmap(?) But ignoring my suspicions, scrolling the carousel seems to drastically reduce the game's performance. I tried to re-use the Global Statistics by checking the top CPU consumers, as you can see from the video.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/111870942-da3db700-8987-11eb-8ef5-658dec82f3cd.mp4

**osu!lazer version:** `2021.320.0` (latest)

**Comment by peppy** [comment]
This should not be so slow. Is something using your disk? Are you running on a slow magnetic media? Does it happen with global statistics closed (having it open adds a huge overhead)?

**Comment by Gabixel** [comment]
Only the recording app was in use at the time of that recording (obviously ignoring OS reads/writes), I have lazer installed on an SSD along with the OS, and the game freezes even without ever opening the global statistics.

I can also summarize by saying that I tried to downgrade to the previous version ([`2021.312.0`](https://github.com/ppy/osu/releases/tag/2021.312.0)), and the carousel is completely smooth as expected:

### Latest version (2021.320.0):
![latest](https://user-images.githubusercontent.com/43073074/111873026-a1551080-898e-11eb-8f09-a215fc961ad4.gif)

### Previous version (2021.312.0):
![previous](https://user-images.githubusercontent.com/43073074/111873088-ed07ba00-898e-11eb-8af2-8dc38e2d560b.gif)

**Comment by peppy** [comment]
Thanks for the clarification. Wondering if this is some regression framework side with thread / locking on store lookups (can't recall if we made any major changes since the last osu! side release or now)

**Comment by l4kr** [comment]
Can confirm, same issue, worked fine in the previous version. Running on SSD.

**Comment by Walavouchey** [comment]
I traced the issue to f1302d1. The previous commit (ea9b48d) is buttery smooth as expected.

**Comment by bdach** [comment]
Another one related to the EF bump then, clearly. Still needs profiling as to what is taking so long. However, given that the commit you linked only has a package bump and a configuration change, it seems like it's not caused by the hacks we've added in place to make EF Core 5 work, but by that EF version itself, which is... worrying, to say the least.

**Comment by peppy** [comment]
let's roll back the change
