### ISSUE TITLE
Tablet driver fails and then the games ignores the tablet input

### ISSUE THREAD

**Issue by DavidHusicka** [ppy/osu#12103]
**Describe the bug:** 
Once I start osu!lazer, there will appear several notifications reporting problem with finding the tablet and if I click on "click to view log files" and then click back to the game, the tablet becomes being ignored. The mouse works fine. The tablet works as long as the button is not clicked (and stays undetected). I do not use any driver (just changed Xorg config to detect my tablet and usually change my area using `xsetwacom` utility)

Tablet is GAOMON S620, OS: Linux.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/_sckXp-byVk

**osu!lazer version:** 
2021.320.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6175518/database.log)
[network.log](https://github.com/ppy/osu/files/6175519/network.log)
[performance.log](https://github.com/ppy/osu/files/6175520/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6175514/runtime.log)

**Comment by peppy** [comment]
Linux is a mixed bag. Please disable in-game tablet support if it doesn't work for you, and go back to how you were playing before.
