### ISSUE TITLE
NCing a faded slider will create NC at incorrect position

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#12111]
In the editor, adding a `New Combo` to a partly faded slider will create the NC at the current position of the sliderhead instead of the start of the slider.

**video:** https://youtu.be/mUC2VSYAw9Y
**osu!lazer version:** 2021.320.0

**Comment by peppy** [comment]
Bit confused here. In your video it looks to be setting the new combo attribute on the correct slider. Maybe what you are seeing is combo colours being incorrect/unexpected?

**Comment by smoogipoo** [comment]
I originally thought the slider was moving positionally, but it look to just be a UI thing - the slider appears un-hit after the NC application.

**Comment by Pennek** [comment]
> the slider appears un-hit after the NC application>

Essentially this. This is more of a UX problem where I'd expect the sliderhead to already be faded out and the sliderbody to change color instead of a sliderhead appearing at the start of the visible path

**Comment by peppy** [comment]
This is going to be the general issue of autoplay discrepancies, also mentioned in https://github.com/ppy/osu/issues/10909 and https://github.com/ppy/osu/issues/10455. I am going to repurpose one of those issues to cover the more general case and close this as a duplicate.
