### ISSUE TITLE
DeviceIOException: Unable to open HID class device (OK).

### ISSUE THREAD

**Issue by danielrparks** [ppy/osu#12116]
**Describe the bug:** 
The new tablet driver fails to detect my tablet.

Additional details: this is on Arch Linux using the `osu-lazer` aur package. I am using Sway for my window manager (wayland), and applications cannot by default open input devices, so by default this error would be correct (although it should say "Permission denied" not "OK"). However, I also tried changing the permissions on the tablet input device so that any user could access it, and I still got the exact same error.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/42898924/111887791-71653780-89a5-11eb-8391-31f3c778881f.png)
![image](https://user-images.githubusercontent.com/42898924/111887809-8e016f80-89a5-11eb-80f1-5186976864be.png)

**osu!lazer version:** 
2021.320.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6176535/database.log)
[network.log](https://github.com/ppy/osu/files/6176536/network.log)
[performance.log](https://github.com/ppy/osu/files/6176537/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6176538/runtime.log)

**Comment by bdach** [comment]
Please read [this OpenTabletDriver FAQ entry](https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#the-driver-fails-to-open-the-tablet-deviceioexception) for a resolution.

**Comment by danielrparks** [comment]
Oop, sorry about that. At least people will see this now if they search issues for it.

**Comment by kisaragi-hiu** [comment]
Another note: that FAQ solution currently fails [because of a cerfificate issue causing NuGet to break completely](https://bugs.archlinux.org/task/70095). Ubuntu and Debian seem to have worked around it right now, but on Arch one would have to downgrade `ca-certificates-mozilla` to 3.62-1 or earlier, or wait for the incident to be resolved.

(Also I of course hope that this dance of building and installing an extra udev rule will not have to be done in the future.)

**Comment by bdach** [comment]
> Another note: that FAQ solution currently fails because of a cerfificate issue causing NuGet to break completely. Ubuntu and Debian seem to have worked around it right now, but on Arch one would have to downgrade `ca-certificates-mozilla` to 3.62-1 or earlier, or wait for the incident to be resolved.

That is a matter to be resolved by the distributions, and not us, or not even the dotnet team themselves.

> (Also I of course hope that this dance of building and installing an extra udev rule will not have to be done in the future.)

I'm not sure what are you expecting us to do here, given that elevated perms are required to access device streams, with the way linux defaults currently are. I'd say running a game with `sudo` is worse than manually installing an udev rule.

**Comment by danielrparks** [comment]
There is a workaround in the comments of the task you linked. The udev rule is also provided by opentabletdriver-git from the aur, although that is _also_ currently not working due to a glib2 update.

**Comment by kisaragi-hiu** [comment]
> That is a matter to be resolved by the distributions, and not us, or not even the dotnet team themselves.
> There is a workaround in the comments of the task you linked.

Exactly. That was a note for anyone who's trying to make the new version work, that they need to

> downgrade ca-certificates-mozilla to 3.62-1 or earlier, or wait for the incident to be resolved.

<hr>

> I'm not sure what you are expecting us to do here

I went off topic there, sorry. Distribution packages will make it work, so I was worrying a bit too much there.

**Comment by UlyssesZh** [comment]
More than a year passed, and I exprienced the same bug... I am using the latest (2022.605.1) AppImage version of osu!lazer on an Ubuntu 20.04 device. The game still cannot detect my tablet after I follow the instructions in [the FAQ](https://opentabletdriver.net/Wiki/FAQ/Linux). What is the workaround here for Ubuntu users?

**Comment by frenzibyte** [comment]
This is probably not the place for workarounds, you may want to either report this in OpenTabletDriver's GitHub repo or reach out their discord.
