### ISSUE TITLE
Spinner spin sound issues when scrolling in the timeline.

### ISSUE THREAD

**Issue by Momoccchi** [ppy/osu#12119]
When scrolling in the timeline while a spinner is playing, the sound of the spinner continues for longer than intended or even starts at different positions. When you click to a different spot on the timeline while the spinner sound is playing, the sound will continually play until you go back to the spinner. This issue perseveres through all trials and tribulation as seen in the video.

Video: https://streamable.com/v51u09

osu!lazer 2021.320.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6176787/database.log)
[performance.log](https://github.com/ppy/osu/files/6176788/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6176789/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6176790/updater.log)

**Comment by bdach** [comment]
Most likely something to do with #11824?

**Comment by peppy** [comment]
Looking to be related to https://github.com/ppy/osu-framework/pull/4212, which I've been meaning to look into (since it's still broken). Will see what I can manage.
