### ISSUE TITLE
[Maybe a bug] Tablet being refused by the game

### ISSUE THREAD

**Issue by Hexality** [ppy/osu#12115]
I'm on ubuntu budgie 20.04 with osu!lazer version 2021.320.0 and my tablet (CTL-472) is getting refused by the game and giving me DeviceException error, I already tried normally, blacklisting wacom, rebooting, and its still giving me this error, idk what to do:

Logs:
[database.log](https://github.com/ppy/osu/files/6176428/database.log)
[network.log](https://github.com/ppy/osu/files/6176429/network.log)
[performance.log](https://github.com/ppy/osu/files/6176430/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6176431/runtime.log)

Screenshot: 
> Disabled
>> ![image](https://user-images.githubusercontent.com/17398632/111885780-b8086100-89a8-11eb-9859-160ab21c801a.png)

> If I try to enable it:
>> ![image](https://user-images.githubusercontent.com/17398632/111885808-e0905b00-89a8-11eb-9bcd-8f0635bdf76b.png)

**Comment by bdach** [comment]
Linux distributions do not allow userspace applications to read device streams directly by default, contrary to Windows. Please read [this OpenTabletDriver FAQ entry](https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#the-driver-fails-to-open-the-tablet-deviceioexception) for a resolution.

**Comment by Hexality** [comment]
well, just to not keep spamming issues, the isn't a left-handed mode available yet right?

**Comment by peppy** [comment]
If you mean rotation support, that is planned
