### ISSUE TITLE
osu!Lazer does not detect CTL-472 on macOS Catalina

### ISSUE THREAD

**Issue by cjiwang** [ppy/osu#12113]
**Describe the bug:** osu!Lazer tablet driver does not detect my CTL-472 tablet.

**Screenshots or videos showing encountered issue:** Enabled the tablet option, simply said no tablet detected. Tried unplugging and plugging it back in, received this [error](https://i.imgur.com/l3zcbAi.png). The issue exists in OpenTabletDriver as well, so this is simply an extension of that issue. I just wanted to mention it here as well.

**osu!lazer version:** 2021.320.0 (Latest)

**Logs:**
[database.log](https://github.com/ppy/osu/files/6176170/database.log)
[network.log](https://github.com/ppy/osu/files/6176171/network.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/6176172/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/6176173/performance-gamethread.update.log)
[performance.log](https://github.com/ppy/osu/files/6176174/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6176175/runtime.log)

**My Setup:**
MacBook Pro 16 (2019)
Processor: 2.3 GHz 8-Core Intel Core i9
Memory: 32 GB 2667 MHz DDR4
Graphics: AMD Radeon Pro 5500M 8 GB
Intel UHD Graphics 630 1536 MB
OS: macOS Catalina 10.15.7

**Comment by bdach** [comment]
The error you mention is osu!-side and will be fixed next release with #12100. As for the tablet support, there is nothing we can do here. You'll have to ask the OTD team for assistance with that.
