### ISSUE TITLE
Current global leaderboard replay should use classic mod.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#12114]
**Describe the new feature:** Global leaderboard replay should use classic mod, so we don't have to confused why that FC replay miss on sliderhead, SS replay do 100 on something, **standardized score mismatch from the leaderboard one.**, etc.

**Proposal designs of the feature:** Just add classic mod to replay, may use old spinner bonus too. You may turn this off in dev build to compare the scoring.

**Comment by bdach** [comment]
This issue is close enough to #5514 that I'm going to close it as duplicate. The solution to that issue is indeed likely just using the classic mod.
