### ISSUE TITLE
Auto is late on long note releases in mania maps

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#12129]
Autoplay releases every LN exactly 20ms too late in mania maps. This is visible on the hit error bar and in the timing distribution on the result screen.

version: 2021.320.0

**Comment by bdach** [comment]
That 20ms delay has actually been [hard-coded in since 2017](https://github.com/ppy/osu/commit/a1baefe20eada145eb2ad31c2a8ded866a64f44c). @smoogipoo do you recall what that was about?

**Comment by smoogipoo** [comment]
It's supposed to look more "natural" in the key counter, though it was more intended for single notes rather than holds.

**Comment by smoogipoo** [comment]
Going to close this as the mania part of it has been fixed, and reasonable argument has been provided to not do the same for other rulesets.
