### ISSUE TITLE
Some long note tails (NoteImageT) do not get masked at the judgement line

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#12128]
Current behaviour: LN tails keep going beyond the judgement line, depending on the release timing of the player, after which they dissappear.
![1](https://user-images.githubusercontent.com/56885706/111910914-91f3c700-8a63-11eb-95ba-f971aa6d0793.gif)

Expected behaviour: LN tails get masked away when the bottom/start of the image reaches the judgement line, along with all of the other play elements. (same as stable)

This is especially visible now because of #12127. This issue will still need to be resolved though, even if that gets fixed. The tails would still peek out under the LN head if the player releases very late, which looks off.

Note that a few skins do mask tails correctly, yet most of the skins I've tested have this issue. I can't immediately think of a reason why this differs between skins.

version: 2021.320.0

**Comment by peppy** [comment]
I've removed the links to the skins you provided as they are hosted on a piece of shit service. Please attach them via github attachments so we can continue to look into this issue.

**Comment by Joppe27** [comment]
Github doesn't let me upload files that are larger than 10MB, but here's one that's less than 10MB which has this issue: [Stepmania Ultralight V1.43 - kopie - kopie (2).zip](https://github.com/ppy/osu/files/6196166/Stepmania.Ultralight.V1.43.-.kopie.-.kopie.2.zip). It might be helpful to change the NoteImageH files to transparent png's so you can see the issue more clearly.
I've uploaded the bigger skins to another site, maybe this one is better? I don't really know what the issue with the first site was to begin with so I guess you can give it a try: https://joppe27.s-ul.eu/dkf5lt0y https://joppe27.s-ul.eu/1URepw0S

**Comment by Joppe27** [comment]
I have tested this again after the recent update that fixed long note heads, and it seems like this issue dissappeared together with that. Tested all of the skins that had this issue and nothing seems to look wrong anymore. Thanks for the fix!
