### ISSUE TITLE
Built-in tablet driver doesn't work.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#12121]
**Describe the bug:** Built-in tablet driver doesn't work. It always use external driver (OpenTabletDriver) configuration. Though lazer still detect the tablet. Turn off external driver make cursor don't move at all. Turn on "High precision mouse" doesn't help and make cursor positioning from tablet broken (cursor go up a little bit).

**Screenshots or videos showing encountered issue:** 
  - The opentabletdrivers tablet area configuration is the large one.
  - The built in driver tablet area configuration is the small one.
  - Raw input position is represent at the bottom left (this is from opentabletdriver debugger)
  - There are 2 screen on this setup. Osu! is on the left.

https://user-images.githubusercontent.com/7066150/111894639-2992ee80-8a3f-11eb-973b-1f6e73d51f2f.mp4

**osu!lazer version:** 2021.320.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6176885/database.log)
[network.log](https://github.com/ppy/osu/files/6176886/network.log)
[performance.log](https://github.com/ppy/osu/files/6176887/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6176888/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6176889/updater.log)

**Comment by peppy** [comment]
Impossible to tell what you are trying to explain, but if it's to do with borderless then it's already reported and will be fixed in a future release.

**Comment by IkaWaAyuMu** [comment]
> Impossible to tell what you are trying to explain, but if it's to do with borderless then it's already reported and will be fixed in a future release.

Yes, the cursor warp do in borderless and fullscreen not windowed, but the configuration doesn't apply to all screen mode.
