### ISSUE TITLE
Long note heads (NoteImageH) disappear at the judgement line

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#12127]
Current behaviour: LN heads disappear when they reach the judgement line, making the LN body masking visible to the user.
![3](https://user-images.githubusercontent.com/56885706/111910806-2c073f80-8a63-11eb-8b0e-a2758eed20af.gif)

Expected behaviour: LN head stops at judgement line when hit correctly, covering up the body masking. (same as stable)
![2](https://user-images.githubusercontent.com/56885706/111910801-24e03180-8a63-11eb-939a-b9f0a157e95f.gif)

version: 2021.320.0
(sorry for the gigantic gifs lol)

**Comment by bdach** [comment]
Seems like a regression across all skins. I swear that this used to work properly before...
