### ISSUE TITLE
Key down images (KeyImageD) are not displayed for long enough

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#12131]
Key down images are displayed for way too little time before they go away again (KeyImageD). Stable displays them for at least 10x longer, although it's hard to measure that exactly. This isn't very important, but it's noticable enough during gameplay that I think it is worth pointing this out.

lazer (looks longer due to low gif fps):
![4](https://user-images.githubusercontent.com/56885706/111911449-ffa0f280-8a65-11eb-936e-a9bcf0c65992.gif)

stable:
![5](https://user-images.githubusercontent.com/56885706/111911516-35de7200-8a66-11eb-8bd4-25dc08b3ede2.gif)

version: 2021.320.0

**Comment by bdach** [comment]
As far as I can tell, the key down image fades out instantly exactly 80ms after release on stable.

**Comment by smoogipoo** [comment]
Indeed. It's supposed to match the fadeout start time from the hitlight:
https://github.com/ppy/osu/blob/70342897637e9dd630d778daab062e7a7022d240/osu.Game.Rulesets.Mania/Skinning/Legacy/LegacyHitExplosion.cs#L75-L76
