### ISSUE TITLE
No sound playing with error messages

### ISSUE THREAD

**Issue by LordBurtz** [ppy/osu#12140]
When I open osu!lazer I cant hear any sound, but I get the error messages:
`BASS faulted with error code 3: Driver` and
`DeviceIOException: Unable to open HID class device (OK)` 
I have recently reinstalled arch linux and before my reinstall it worked fine but now it doesnt.
I think im missing a library or something
I am using 2021.320.0

[osu!lazer image with error message](https://imgur.com/a/OciwfC9)

**Logs:**
[logs](https://filebin.net/eya5vghltcn8ekx3)

**Comment by peppy** [comment]
This repository is for reporting issues with osu!. This is clearly a misconfiguration with your system.

**Comment by LordBurtz** [comment]
@peppy  ok so where can I ask for some support?

**Comment by peppy** [comment]
Try googling for each error message separately. There are many solutions listed.
