### ISSUE TITLE
InvalidThreadForMutationException on MIDI device disconnect

### ISSUE THREAD

**Issue by adryzz** [ppy/osu#12146]
**Describe the crash:** 
When disconnecting a MIDI device, the game gets an unhandled exception (trying to update the UI from a worker thread i suppose), hangs a bit and then crashes
Related to #12102
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/46694241/112066224-4249f400-8b66-11eb-980f-43bb878e6ab6.mp4

(After the exception the cursor isn't moving too)
**osu!lazer version:** 
Local debug and local release updated to commit https://github.com/ppy/osu/commit/779d2ed5d9156d3d76b85d7e3bfa283d6fcf4150 on .NET 5.0.2
Windows (Microsoft Windows NT 10.0.19042.0)
**Logs:**
[database.log](https://github.com/ppy/osu/files/6185632/database.log)
[updater.log](https://github.com/ppy/osu/files/6185633/updater.log)
[runtime.log](https://github.com/ppy/osu/files/6185634/runtime.log)
[performance.log](https://github.com/ppy/osu/files/6185635/performance.log)
[network.log](https://github.com/ppy/osu/files/6185636/network.log)

here is where it's being thrown
https://github.com/ppy/osu/blob/779d2ed5d9156d3d76b85d7e3bfa283d6fcf4150/osu.Game/Graphics/UserInterface/Nub.cs#L45
**Computer Specifications:** 
CPU: AMD Ryzen 5 3600
GPU: Radeon RX 580 Series
RAM: 32GB
Android MIDI Device

**Comment by bdach** [comment]
Will be fixed next release with https://github.com/ppy/osu-framework/pull/4293.

**Comment by adryzz** [comment]
my bad, i forgot that i wasn't using the latest commit of osu!framework but only the latest commit of lazer
