### ISSUE TITLE
Incorrect tablet mapping when running in fullscreen mode

### ISSUE THREAD

**Issue by Moxanthia** [ppy/osu#12156]
Whether or not I use the new tablet options available in lazer with my regular tablet drivers disabled or vice versa, the screenshot below shows the furthest point on both axes that my cursor will go within lazer. My entire screen is accessible outside of lazer using my tablet. Within lazer I can reach my entire screen using my mouse though, just not my tablet. When I Print Screen, the screenshot shows a black box around the window. This does not happen if I use Print Screen on any other window. I'm using fullscreen at my default resolution as I always have been, and screenshots worked before as normal.

![lazer_mouse_area](https://user-images.githubusercontent.com/17536688/112180737-6dadfc80-8bc1-11eb-83c8-7678ceaa1801.png)

**osu!lazer version:** 2021.323.0 on Windows 10

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6191238/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6191239/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6191240/updater.log)
[database.log](https://github.com/ppy/osu/files/6191241/database.log)
[network.log](https://github.com/ppy/osu/files/6191242/network.log)

**Comment by frenzibyte** [comment]
- Can you clarify by "vice versa" you meant that you turned off the in-game tablet driver, from input settings? 
- Can you post a screenshot of the tablet configuration you have set?
- Were you running on borderless mode from start? that was an issue that was supposed to be fixed.

**Comment by Moxanthia** [comment]
Yes, I tried disabling the in-game driver and just using the XP-PEN drivers as I normally do, but the issue still occurred. I have always been using fullscreen, but borderless has the same issue for me. I have nothing changed, like so:
![lazer_tablet_settings](https://user-images.githubusercontent.com/17536688/112185310-b8ca0e80-8bc5-11eb-90a6-efb5513d6962.png)
Oddly, the screenshot turned out normal this time. Might be because I was messing around with resolution and needed to restart the game for some reason.

**Comment by frenzibyte** [comment]
Can you confirm it's happening because of running in fullscreen mode from start, as it's likely to be the case here.

**Comment by Moxanthia** [comment]
Okay yeah, the issue is fixed if I launch the game in borderless from the start.

**Comment by peppy** [comment]
Do you have DPI scaling enabled? Multiple monitors?

**Comment by Moxanthia** [comment]
No DPI scaling, single monitor

**Comment by peppy** [comment]
And can you confirm it was working correctly before today's build? This looks like an issue related to your fullscreen resolution being set incorrectly, not anything specific to input or tablets.

You can find thee previous builds from the release page if you need to check the last release (320).

**Comment by Moxanthia** [comment]
The issue still occurs in 320 but not in 312.

**Comment by NafeeJ** [comment]
I have same kind of issue with tablet not mapping to full screen area on Monoprice 10 x 6.25-inch. This tablet isn't detected by the new drivers and whether enabled/disabled in osu it doesnt work. Borderless works, Fullscreen doesn't. 

I'm on 323.

**Comment by peppy** [comment]
This all sounds like we aren't correctly updating one of the internal values SDL is using to resize the backbuffer or window. May actually be a performance concern as well.

@Moxanthia can you confirm that you are using the windows vanilla print screen functionality (ie. your screen is copied to clipboard)?

**Comment by Moxanthia** [comment]
Yes, I am.

**Comment by peppy** [comment]
@Moxanthia Are you able to reproduce any of these weird issues with mouse input, or only tablet?

**Comment by Moxanthia** [comment]
It's only my tablet.

**Comment by minasminas** [comment]
I have this issue, or a very similar one too. It kinda works if you start in Borderless or Windowed mode and you can fix it ingame by switching to any of these modes as well. But by starting any Map or going back to Fullscreen, the issue starts again. This only happens when I use external drivers (Wacom ones in my case) and not the new internal drivers for me. Not entirely sure if this is 100% the same issue, but it sounds very similar. I have a small clip showing the problem: https://youtu.be/OnVdN46_D8M

**Comment by Moxanthia** [comment]
Release 331 creates this same issue even in borderless mode but only when playing a map. Everything works on the main menu and song select screens.

**Comment by TurtleJud** [comment]
Same thing happening to me. happens in fullscreen when i use wacom tablet drivers in everything I do. only happens when playing a map when I have it in borderless. using in-game table driver has no problem.

**Comment by peppy** [comment]
@TurtleJud are you running multiple monitors? do you have any scaling applied in windows? does it still happen if you turn off `confine mouse mode` or `high precision cursor` (try each of these separately)?

**Comment by TurtleJud** [comment]
I cannot seem to be able to recreate the issue. I havn't played lazer since I made the report of me also having this problem and just now spent ~15m trying to recreate the problem. Everything runs fine now. I have two monitors but I disable the 2nd one in windows settings when I play lazer because when the tablet implement first came out, it would figure both monitors as one. It doesn't now. When the problem occurred I thought that might fix it. I had my 2nd monitor disabled When I had the problem.

**Comment by minasminas** [comment]
@peppy I can confirm after reading your message, that disabling High precision mouse fixes the problem completely for me.

**Comment by peppy** [comment]
@minasminas hmm, do you happen to have the in-game tablet support *disabled* then? it sounds like osu! is using the output from your system wacom drivers and something is going wrong in that process, *but* with our recent changes osu! should override this output and handle your tablet itself.

**Comment by minasminas** [comment]
@peppy Yes, I have the in-game tablet support disabled, because I have a very weird Tablet Area which is hard to recreate. It was just that having high precision mouse enabled, the above described problem began. After turning that setting off, everything works fine and I can switch between the integrated and the Wacom drivers with no problem.

**Comment by LemonJuicer** [comment]
Problem is resolved for me, build: 2021.410.0

**Comment by peppy** [comment]
@LemonJuicer you never reported having the problem, so could you please confirm your environment and confirm you could previously reproduce it?

**Comment by LemonJuicer** [comment]
I did report it in #12156.

**Comment by peppy** [comment]
Did you mean to link a different issue, or am I missing something?

**Comment by LemonJuicer** [comment]
Sorry, its #12167

**Comment by peppy** [comment]
@minasminas can you check on the latest release and see if this is also resolved for you?

**Comment by minasminas** [comment]
@peppy It is the same as in the last release. It is fixed if I turn "High Precision Mouse" off, but is still there if the setting is on.

**Comment by NafeeJ** [comment]
turning off high precision mouse also fixes the problem for me regardless of if in-game tablet drivers are enabled, latest build.

**Comment by LemonJuicer** [comment]
High precision mouse does nothing for me
