### ISSUE TITLE
Add button to restore recently deleted beatmaps

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1215]
Just a QOL improvement.

**Comment by FreezyLemon** [comment]
I started implementing this but encountered some bugs that also happen with the (already existing) "restore all hidden map difficulties" button in the options:
When you undelete/unhide a map while having the song select open, it doesn't update song select, so you have to re-enter from the main menus to see the map again. Also, if you undelete/unhide a map, you can't delete/hide it again until restarting (or at least waiting a while, not sure).

**Comment by peppy** [comment]
That sounds like a serious regression. Please report in a separate issue in cases like this.
