### ISSUE TITLE
Alt-Tabbing into osu! in specific circumstances half-breaks High precision mouse

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#12169]
**Describe the bug:** 

Alt-Tabbing into osu in a specific way breaks the in-game cursor.

How the cursor is broken:
- While the cursor is directly over the osu window, everything is normal
- If it's not: the cursor position won't update
- Focusing (Alt-Tab, or using the taskbar button) osu will move the cursor

**Repro steps:**
1. Enable `High precision mouse`
2. Move another window (Notepad, in my example) so that it overlaps the osu window
3. Focus the other window
4. Move your cursor into the overlap area
5. Alt-Tab into osu
6. Your in-game cursor should be broken as explained above

**Remarks:**

The bug applies to Windowed and Borderless mode

To return the cursor to normal:
1. disable `High precision mouse`
2. minimize the osu window
3. restore it again
4. enable `High precision mouse`

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/16479013/112361058-49424500-8cd3-11eb-8301-e59c70fb3623.mp4

**osu!lazer version:** 2021.323.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/6199470/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6199471/updater.log)
[database.log](https://github.com/ppy/osu/files/6199472/database.log)
[network.log](https://github.com/ppy/osu/files/6199473/network.log)
[performance.log](https://github.com/ppy/osu/files/6199474/performance.log)

**Comment by bdach** [comment]
I'm a bit confused by how this report is worded. Does the "breakage" only occur when the window does not have focus? Is everything OK after performing the steps above after focus is regained?

If so then this is a bit wonky, but still probably low priority. If it actually breaks input after tabbing back in then that changes things.

**Comment by Susko3** [comment]
Once the cursor is "broken" it won't return to normal.

The breakage occurs when osu! is not in focus, and you Alt-Tab into it.

Everything about input is fine. Only thing that is broken is that the in-game cursor doesn't follow the real cursor when it's not directly on the game window.

This is problematic because it unexpectedly moves the cursor if you Alt-Tab into the game.

Red is real cursor location:
![image](https://user-images.githubusercontent.com/16479013/112365850-69283780-8cd8-11eb-88e8-aa435a2df09c.png)

When it cursor is not broken, it'll follow the real cursor even if the real cursor is not over the game widow:
![normal](https://user-images.githubusercontent.com/16479013/112366195-cf14bf00-8cd8-11eb-8c5b-f71a2be180d3.gif)

**Comment by bdach** [comment]
Ok, thanks for clarifying.

**Comment by peppy** [comment]
Thanks so much for this reproduction! This is something we were tracking via a different reproduction method, but that one has largely been worked around.

If anyone else ends up investigating this: the issue is that SDL stops sending the focus events (at a message pump level):

![20210326 133050 (JetBrains Rider-EAP)](https://user-images.githubusercontent.com/191335/112577343-7d367b00-8e37-11eb-922d-cab16eab1f10.png)

It likely needs to be reported to SDL, I'm pretty sure it's not an issue at our end. We may be able to work around it by using `wndproc` events instead on the windows platform.

**Comment by Susko3** [comment]
I've done some testing and noticed that when the cursor is broken, the Cursor sensitivity setting doesn't apply. So this does have a game-breaking effect.

If `Confine mouse cursor to Window` is set to `During Gameplay`, then the cursor is back to normal when gameplay starts.

**Comment by slouken** [comment]
Please retest using the latest SDL snapshot at commit https://github.com/libsdl-org/SDL/commit/a1fabca162091b50d6f7dd71879d028319e09d80:
http://www.libsdl.org/tmp/SDL-2.0.zip

Thanks!
