### ISSUE TITLE
Still able to click circles after failing beatmap

### ISSUE THREAD

**Issue by iamkyaru** [ppy/osu#12166]
**Describe the bug:** 
After failing a beatmap in-game you are still able to click circles that appear in slow motion. It's not a big bug, but this doesn't look right to me I guess?

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2021.323.0

**Logs:**

**Comment by peppy** [comment]
This is actually intended. Does it feel bad to you?

**Comment by iamkyaru** [comment]
So I actually thought that when you fail you can not click any circles anymore. Like: "you have failed this map so you have to stop right here."

**Comment by peppy** [comment]
The intention was to have a bit of fun while failing, since we can.

**Comment by Antholony** [comment]
It's a nice thing to have but it doesn't feel intended in my opinion, more like someone forgot to turn off whatever mechanism is responsible for clicking circles when failing. If made more clear it would definitely be pretty cool but I feel that's a bit hard to implement.

**Comment by iamkyaru** [comment]
But this does not seem right to me because when you fail, where "fail" means your HP dropping to zero, you shouldn't be able to continue playing?

**Comment by peppy** [comment]
Okay we'll consider this in the future, but this is by design and not hurting anyone for now. Will reconsider if it gets reported again as a "bug".

**Comment by szmarczak** [comment]
I very much agree with @Anthony1x Perhaps this could be customizable via an option? I mean it's funny but annoying :joy:

**Comment by szmarczak** [comment]
Why my comment was marked as spam? I explicitly asked if this could be customizable via an option. A simple yes/no would do. Please reconsider your behavior, this is very inappropriate.

**Comment by bdach** [comment]
@szmarczak:

![2021-09-30-202539_1373x177_scrot](https://user-images.githubusercontent.com/20418176/135510511-1c5750b7-6875-4f46-b0ce-f9cab474d5ee.png)

[taken from CONTRIBUTING.md](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md)
