### ISSUE TITLE
Allow "caps lock" key to be rebound

### ISSUE THREAD

**Issue by TheFartLord** [ppy/osu#12165]
In osu!stable it is possible to bind caps lock to a function (e.g. K1), but osu!lazer doesn't allow it. There might also be other keys that have the same issue and should be allowed to be rebound.

**Comment by peppy** [comment]
does this mean in stable you toggle your caps lock state every time you hit the key?

**Comment by Joehuu** [comment]
Related to https://github.com/ppy/osu/issues/11731 as it needs the same fix.

**Comment by TheFartLord** [comment]
Yes, it toggles with every press
