### ISSUE TITLE
No text appearing

### ISSUE THREAD

**Issue by bkGamingYT** [ppy/osu#12174]
**Describe the bug:**  No text shows up even after reinstalling the game or restarting the computer.

**Screenshots or videos showing encountered issue:** 
![osu!lazer no text](https://user-images.githubusercontent.com/33919755/112406137-962d1800-8ce1-11eb-9050-9b2e3cd95f67.PNG)
![osu!lazer no text 2](https://user-images.githubusercontent.com/33919755/112406417-1fdce580-8ce2-11eb-90f8-e47827d0daab.PNG)

**osu!lazer version:** 2021.323.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6201465/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6201466/updater.log)
[database.log](https://github.com/ppy/osu/files/6201467/database.log)
[performance.log](https://github.com/ppy/osu/files/6201468/performance.log)

**Comment by peppy** [comment]
- Do you have any graphical overlays loaded (like MSI Afterburner or similar) that could be interfering with the game?
- Do you get any similar issues with stable?
- Does this happen if you run windowed (you can switch using alt-anter)?
- Can you press Ctrl+F3 and take a screenshot of what you see there?

**Comment by smoogipoo** [comment]
Firstly, go into the `%APPDATA%\osu` folder and back up:
1. The `cache` folder.
2. `online.db`
3. `client.db`

Then, does it fix it by deleting any of these? Try them in the order above.

**Comment by bkGamingYT** [comment]
Deleting the cache folder worked, thank you! :)

**Comment by smoogipoo** [comment]
Can you upload the backed up folder? If you still have it.

**Comment by peppy** [comment]
@bkGamingYT i don't suppose you have a copy of the cache folder that was causing issues still?

also, can you let us know how you took the second screenshot? it looks to be capturing more of the game than should be on screen, which is something we'd want to look into.

**Comment by bkGamingYT** [comment]
> Can you upload the backed up folder? If you still have it.


[BACKUP.zip](https://github.com/ppy/osu/files/6202072/BACKUP.zip)

**Comment by bkGamingYT** [comment]
> @bkGamingYT i don't suppose you have a copy of the cache folder that was causing issues still?
> 
> also, can you let us know how you took the second screenshot? it looks to be capturing more of the game than should be on screen, which is something we'd want to look into.

I used Windows snipping tool but it acts really weird around full screen apps. It does this with the stable version of osu! too, so it doesn't seem to be a problem specific to osu!lazer :)

**Comment by smoogipoo** [comment]
Thanks, can reproduce.

**Comment by smoogipoo** [comment]
Not sure how this is possible. One of the files (osuFont) is completely empty:
```
[smgi@smgi fonts]$ hexdump 57302b981c4deb011671c82fe789d7a9#dd9f54baf84b45edcd4cbf944cb107b3#1018#612
0000000 0000 0000 0000 0000 0000 0000 0000 0000
*
00981a0 0000 0000 0000 0000
00981a8
```
Indicating that it isn't a result of partial writes, but a complete failure having occurred. I suspect that it's related to the issue fixed via https://github.com/ppy/osu-framework/pull/4205 as I can't see anything else.

@bkGamingYT did you previously have osu!lazer installed?

**Comment by bkGamingYT** [comment]
Lmao I did get a blue screen crash while installing osu!lazer for the first time today
