### ISSUE TITLE
Osu lazer hitsound problem

### ISSUE THREAD

**Issue by PastaSoosi** [ppy/osu#12170]
Sometimes when I hit notes, they come out very loud. It doesn't happen everytime, but when it does, it makes my ears bleed. How do I fix this?

I have the latest version.

**Comment by Joehuu** [comment]
Can you confirm you are hearing the same thing from the video in https://github.com/ppy/osu/issues/11845?

**Comment by bdach** [comment]
Closing as duplicate.

**Comment by peppy** [comment]
@PastaSoosi for reference, could you please include your logs so we can determine your operating system? Also can you let us know if you had your game set to "single threaded" mode?

The other report for this was specific to macOS, so it would be handy knowing if this is platform dependent or not.
