### ISSUE TITLE
Imported map metadata cuts off after two slashes ( // )

### ISSUE THREAD

**Issue by facespkz** [ppy/osu#12172]
**Describe the bug:** When importing a map from osz, two forward slashes are interpreted as a comment delimiter, even when they're in front of metadata fields.

This has been tested and confirmed with Title, Artist, Version, and Source values. Creating a map within the editor doesn't seem to cause this.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/22137884/112369615-9dc8ce80-8c99-11eb-8abc-91de5f355f1c.png)

(title is supposed to say "PLANET//SHAPER")

![image](https://user-images.githubusercontent.com/22137884/112370607-d74e0980-8c9a-11eb-91df-e6a72cf3f275.png)

![image](https://user-images.githubusercontent.com/22137884/112370650-e03edb00-8c9a-11eb-9214-013682a5fdbe.png)

(fields are supposed to include "//comment" after them)

**osu!lazer version:** 2021.323.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6199926/database.log)
[network.log](https://github.com/ppy/osu/files/6199927/network.log)
[performance.log](https://github.com/ppy/osu/files/6199928/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6199929/runtime.log)

**Comment by bdach** [comment]
Yep, this will happen...

https://github.com/ppy/osu/blob/6a37fb41cc02a6e33f0a0fdf23df6cdf4b60f9de/osu.Game/Beatmaps/Formats/LegacyDecoder.cs#L84-L91

Can't find how stable does this. It looks a bit like it doesn't explicitly trim comments, just ignores them...?

**Comment by Walavouchey** [comment]
> Can't find how stable does this. It looks a bit like it doesn't explicitly trim comments, just ignores them...?

Only lines with double-slashes at the beginning of the line are ignored as comments.

This is (sort of) mentioned at the bottom of https://osu.ppy.sh/wiki/en/Storyboard_Scripting/General_Rules

![image](https://user-images.githubusercontent.com/36758269/112373674-81e91b00-8ce1-11eb-9e6c-e4ef7d39f034.png)

**Comment by smoogipoo** [comment]
Hmm.... I remember this was done this way specifically because some beatmaps have properties with `//` placed inside a line. See the skin mentioned in https://github.com/ppy/osu/pull/3023:
```
[Colours]
Combo1: 255,240,141 //yellow
Combo2: 255,128,64  //orange
Combo3: 255,128,128 //red
Combo4: 154,255,141 //green
```
Will need to test whether this is broken on stable first, and see why if it isn't. Other than that, it does seem that stable uses `StartsWith`.

**Comment by peppy** [comment]
I think https://github.com/ppy/osu/pull/3023#issuecomment-405067123 sums it up best - it's probably safe to do what we are doing everywhere but metadata, so I'm going to go with that.
