### ISSUE TITLE
Cursor gets stuck after moving the game window to a second display

### ISSUE THREAD

**Issue by K4ktus123** [ppy/osu#12188]
**Describe the bug:** 
I'm running a dual display setup. Everything works fine on the first display, however when I move the game window to the second display, as soon as I try to move my cursor outside the window it gets stuck in the middle of it. I can free it by switching to another program with Alt+Tab.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/55000815/112541946-49664180-8db4-11eb-9057-e6c16a1c29cd.mp4

**osu!lazer version:** 
2021.323.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6207799/database.log)
[network.log](https://github.com/ppy/osu/files/6207801/network.log)
[performance.log](https://github.com/ppy/osu/files/6207802/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6207804/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6207806/updater.log)

**Comment by peppy** [comment]
I could've sworn I found this reported against SDL, but can't seem to find the bug report. Does it happen to resolve if you switch to another window and back (after already moving osu! to your second display)?

**Comment by K4ktus123** [comment]
When I switch to another window and back, the same thing happens. I can move the cursor inside the window, but as soon as it tries to leave it gets stuck again.

**Comment by K4ktus123** [comment]
After the 2021.407.1 update, the cursor is no longer stuck in the middle of the window. I can move it freely around, but it's permanently confined to the window and doesn't care about "Confine mouse cursor to window" setting.

https://user-images.githubusercontent.com/55000815/113931788-2ba4cd80-97f3-11eb-9419-3c5549af3362.mp4

**Comment by peppy** [comment]
@K4ktus123 thanks for the update. if possible, could you also test with just one monitor/desktop enabled and confirm that it resolved the issue? just want to be sure that the root cause here is actually having two displays connected.

**Comment by K4ktus123** [comment]
Yes, with only one monitor everything works fine. But just to clarify, the cursor behaves correctly as long as the window is on the first display, regardless whether I have the second one connected or not. Only after moving the window to the second screen it gets confined as soon as it enters the window, like shown in the video.

**Comment by Susko3** [comment]
@K4ktus123 what happens when the window is in-between the displays?

Move your window so it's still on the main display (but some portion of it is on the second) and then move your mouse so you exit the window on the second display. Also do the opposite (window mostly on seconds display, try leaving the window on the primary).

**Comment by K4ktus123** [comment]
@Susko3 With a small portion of the window on the second screen, it behaves as if it was entirely on the first one (the cursor can be freely moved outside). Similarly, with most of it on the second screen and only a small part on the first, it behaves as if it was entirely on the second screen (the cursor is confined and can not leave the window).

**Comment by peppy** [comment]
If someone beats me to investigating this, it's likely due to both `Size` and `ClientSize` currently reporting the same value (and also may be related to windows only handling scaling in very specific scenarios in the first place).

**Comment by peppy** [comment]
@K4ktus123 does this still apply to you? We've made some changes which I believe fixed confinement mode area updating and may have indirectly fixed your issue.

**Comment by Susko3** [comment]
Still the same with my repro steps on 2021.523.0

**Comment by K4ktus123** [comment]
@peppy Yes, the issue is still present in 2021.523.0.
