### ISSUE TITLE
Toggle to opt-out from using OpenTabletDriver

### ISSUE THREAD

**Issue by ab123321** [ppy/osu#12189]
**Describe the new feature:** As noted in #12159, #12116, #12101 and numerous other fresh issues, OTD and its integration into osu! is frankly speaking far from delivering "a better out-of-the-box experience", on different kinds of system configurations.

For instance, to run latest versions of osu! on Linux, you need to add extra udev rules and unload wacom driver from kernel. Since both actions require root privileges, recent changes render unpossible any in-game interaction using tablet (if user lacks such rights). Given that blindly following https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ also simply breaks any system-wide tablet detection, I think it would be justified to (temporarily) add an option for opting out of using OTD, until major issues with it are sorted out

**Proposal designs of the feature:** an entry in settings menu with a user-friendly message

**Comment by bdach** [comment]
Sych an option is already available.

![2021-03-25-232709_557x163_scrot](https://user-images.githubusercontent.com/20418176/112551654-a3b9cf00-8dc1-11eb-883a-45d4fc2be490.png)

**Comment by ab123321** [comment]
@bdach No success, option is toggled off
[network.log](https://github.com/ppy/osu/files/6208242/network.log)
[performance.log](https://github.com/ppy/osu/files/6208243/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6208244/runtime.log)

**Comment by ab123321** [comment]
Ok, after disabling of both options and restarting the game, everything works fine...
Seems like "high precision mouse" does not trigger device re-enumeration
