### ISSUE TITLE
Osu!lazer doesn't detect my Tablet

### ISSUE THREAD

**Issue by RinOkumurra** [ppy/osu#12185]
I downloaded Lazer
Started lazer but it doesnt detect my Gaomon S620.

here are my logs if you need them idk
[runtime.log](https://github.com/ppy/osu/files/6206478/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6206479/updater.log)
[database.log](https://github.com/ppy/osu/files/6206480/database.log)
[network.log](https://github.com/ppy/osu/files/6206482/network.log)
[performance.log](https://github.com/ppy/osu/files/6206484/performance.log)

**Comment by frenzibyte** [comment]
Please report at https://github.com/OpenTabletDriver/OpenTabletDriver/issues/new?assignees=&labels=bug&template=bug_report.md&title=
