### ISSUE TITLE
Ability to add additional "Songs" directories from the options menu

### ISSUE THREAD

**Issue by Sylurial** [ppy/osu#12195]
**Describe the new feature:**
An addition to the Lazer client allowing for more than one `Songs` directory. Shouldn't be *too* (?) complicated to add.

**Proposal designs of the feature:**
- Add a button underneath `Change folder location` labeled `Add extra song folder(s)` or something similar
- When clicked, this button brings up a menu similar to the one seen when changing osu!'s main folder location on disk
- When the user selects the folder of their choosing and confirms said choice, it is then shown in it's own list below the aforementioned button, so that it can be kept track of (when there's multiple of these additional folders added)
- Next to each of the extra song folders mentioned, there will be a red clickable "X" allowing the user to delete these additional folders if need be

**Sidenote(s):**
I mentioned at the beginning of this feature request that in terms of the work put in to make this idea functional, it *shouldn't* be too complicated. This is an educated guess. Since Lazer does not explicitly require extra directories to be created inside of it (a user can create a new one outside of the game and select it from *within* the client), the amount of new code needed drops by a fair bit.

My concern lies not so much in the implementation, but in whether or not performance would be hindered if a user adds enough extra song directories. The simpler solution to something of this manner is to add a cap on how many extra song directories there can be at any one given time, though I'm open to alternate solutions as well.

**Comment by frenzibyte** [comment]
This will likely be complicated as osu!lazer reads the beatmaps from the database, adding the ability to read from (and write to?) a certain beatmaps folder doesn't sound simple.

Is there a fair reason why you would want this feature?

**Comment by peppy** [comment]
This won't happen, sorry.
