### ISSUE TITLE
osu!lazer behaving as if it's in foreground when opened in background

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#12199]
**Describe the bug:** 

When osu! is opened in background, it'll behave as if it's in foreground:

- The game will render at it's normal Frame limiter rate (120 Hz), instead of at 60 Hz
- Moving mouse into osu! window makes the cursor stuck at the center of the window
  - Provided high precision mouse is enabled
  - To break out of this, just Alt-Tab into osu

**Repro steps:**
1. Open osu!lazer
2. Focus another window before osu!lazer opens
3. When osu!lazer opens, it should not be focused and it should be the last entry in Alt-Tab
4. Observe the aforementioned problems

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/16479013/112703877-d1be1280-8e98-11eb-8b5b-2597f79ba096.mp4

**osu!lazer version:** 2021.323.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6214847/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6214848/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6214849/updater.log)
[database.log](https://github.com/ppy/osu/files/6214850/database.log)
[network.log](https://github.com/ppy/osu/files/6214851/network.log)

**Comment by peppy** [comment]
Focus issues never end on windows (due to a very bad underlying API). We've had similar problems on stable with weird workarounds, and it's clear that SDL also does not handle this correctly.

We may want to work around this ourselves by polling focus state locally.

**Comment by peppy** [comment]
Have addressed this SDL side (https://github.com/libsdl-org/SDL/pull/4293).

**Comment by peppy** [comment]
This has been deployed via our SDL/SDL2-CS fork and seems to be working well.
