### ISSUE TITLE
Keyboard input lags happen randomly

### ISSUE THREAD

**Issue by hmoon630** [ppy/osu#12197]
**Describe the bug:** 
While playing the game, my keyboard input gets stuck (remains being pressed). And my keyboard input counts increases at once. It didn't happened while I'm playing stable. Maybe there's a input lag in osu! lazer.

I'm playing with Wacom CTL-472 Tablet, and using keypad 1, keypad 2 as left button and right button. Also, I'm playing on Windows 10.

**Screenshots or videos showing encountered issue:**

https://user-images.githubusercontent.com/48788794/112632337-5732ca00-8e7b-11eb-99f8-4ad614a2134b.mp4

**osu!lazer version:** 
2021.323.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6211810/database.log)
[network.log](https://github.com/ppy/osu/files/6211811/network.log)
[performance.log](https://github.com/ppy/osu/files/6211812/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6211813/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6211814/updater.log)

**Comment by frenzibyte** [comment]
Can you attach another video record of the issue, but with the extended FPS counter on (press `Ctrl+F11` twice to display it)

**Comment by hmoon630** [comment]
Of course. Here's another one.

https://user-images.githubusercontent.com/48788794/112634302-c7dae600-8e7d-11eb-8d0c-3183208a4cf3.mp4

**Comment by bdach** [comment]
> using keypad 1, keypad 2 as left button and right button

Those are keys on the *keyboard* keypad, right?

Do you have mouse buttons disabled during gameplay? I'm thinking you might be causing the press input by physically pressing the tablet stylus into the tablet surface.

**Comment by hmoon630** [comment]
Well, I already turned on "Disable mouse buttons during gameplay" option. And I drag on a tablet while playing osu.

I tried pressing the tablet stylus into surface, and pressing the buttons on pen(it works as right button and wheel button).
But, it didn't work on play generally.

**Comment by hmoon630** [comment]
I had some time to play osu! lazer today. And I could get live play with FPS Counter. 
https://www.youtube.com/watch?v=nYnAWpfccEw&ab_channel=%EC%83%88%EC%9A%B0

As you can see, I definitely clicked circles, but game didn't recognize. B1, B2 counts sometimes increased 2 or more when input lags happened.

If it doesn't have enough informations, how can I provide you more informative one??

**Comment by bdach** [comment]
It looks like the input thread had some kind of hitch at the point of miss (see fps counter, went from sub-1000 fps before to 1500-1600 after). This might mean that another application might be open in the background and hooking input, or that your device drivers are faulty.

Either way I'm not sure this is the game's fault.

**Comment by hmoon630** [comment]
Oh, I found why input lag happens now. When USB Device get unplugged or plugged, input thread stops for a really short time.
In some reason, one of my device gets unplugged and this would cause that.

Thanks for your help. I think it's not lazer's fault. Then can I close this issue?

**Comment by bdach** [comment]
Yep, closing as resolved.
