### ISSUE TITLE
No user scores on the new site's beatmap pages. 

### ISSUE THREAD

**Issue by AkashaOsu** [ppy/osu#122]
When looking at the new site I noticed something that might have just been forgotten when making it. There is a tab you can click that will show your friends scores on the beatmap, but no matter how hard you look your personal score won't be among them. I know in game it shows personal scores among friends scores. I've checked on multiple songs that I have scores on and they are all the same. I know this isn't only me because I had my friend check as well. (Keep in mind, to view this you need to be supporter)

**Comment by peppy** [comment]
wrong repo. you're looking for https://github.com/ppy/osu-web/
