### ISSUE TITLE
song audio is drowned out by hitsounds, no matter the volume

### ISSUE THREAD

**Issue by firinael** [ppy/osu#12203]
Since the osu!lazer `release 2021.219.0` the song audio has been *_massively drowned_* by the effects' audio, no matter what skin I use.

Before this update, I could play with general audio at 30%, and both effects/music at the same level (usually 70%), and the worst that would happen would be one or other map with hitsounds that were a bit too loud, but because the mapper chose that for some reason.

Now, it's kind of fucked. I have to keep my song audio at 100% at all times, with the effects at around 30% - and even then sometimes I'll have to throw the general audio up and the effects audio down so that I can actually hear the song properly. Before it's asked: no, **I did not update any drivers or the OS during the period I've been experiencing this issue**.

**osu!lazer version:** 
`2021.323.0` (but it's been happening since `2021.219.0`)

**audio driver details:**
Name: Realtek HD Audio
Driver Vesion: 10.0.19041.1

**OS Specifications:**
Edition - Windows 10 Pro
Version - 20H2
Installed on - ‎09/‎09/‎2020
OS build - 019042.867
Experience - Windows Feature Experience Pack 120.2212.551.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6215293/database.log)
[network.log](https://github.com/ppy/osu/files/6215294/network.log)
[performance.log](https://github.com/ppy/osu/files/6215295/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6215296/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6215297/updater.log)

**Comment by peppy** [comment]
To get your previous behaviour, please reduce effect volume by 20%. This is an intentional change and we have further upcoming work scheduled for the audio subsystem to better balance game-wide volume (including replaygain support).

**Comment by firinael** [comment]
I currently play with around 35% effects and 100% music. The imbalance is insane, and I have to switch around audio values all the time from map to map. If you say it's gonna be addressed, that's fine. I just don't want the issue to be understated, it's something that hinders gameplay quite a bit.

**Comment by peppy** [comment]
The change we made was precisely 20%, nothing else. You can adjust accordingly if it doesn't suit.

**Comment by peppy** [comment]
Actually the change was from 80% to 50% (see https://github.com/ppy/osu/blob/49d6bf066a70e465f56b5593067514a3b3e0f72b/osu.Game/OsuGameBase.cs#L162). So you would need to adjust accordingly to please your ears.
