### ISSUE TITLE
Online features don't work with Osu!Lazer

### ISSUE THREAD

**Issue by FDAkira** [ppy/osu#12206]
Recently downloaded Osu!Lazer and when I tried logging in the game would just show connecting for a second and then go back to log in screen and it looks like no internet feature works with lazer. I looked through all the other issue reports of the same problem but none of the fixes worked for me

I also get 2 unobserved errors on start and the game telling me I have to be online to multi when trying to go to multiplayer
![Screenshot_187](https://user-images.githubusercontent.com/81518086/112754133-72204e00-8fe3-11eb-9db4-12a4ecf7c152.png)

I have osu lazer version 2021.323.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6217374/database.log)
[network.log](https://github.com/ppy/osu/files/6217375/network.log)
[performance.log](https://github.com/ppy/osu/files/6217376/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6217377/runtime.log)

**Comment by sr229** [comment]
According to `runtime.log` the error was a 403. Have you attempted to log in using your credentials before jumping in to Multi?

**Comment by Susko3** [comment]
Can you open https://osu.ppy.sh/ in your web browser?

Also try in an Incognito window

`network.log` says it's a Clodflare Captcha verification failure

**Comment by FDAkira** [comment]
> Can you open https://osu.ppy.sh/ in your web browser?
> 
> Also try in an Incognito window
> 
> `network.log` says it's a Clodflare Captcha verification failure

I can open the link in my browser. Incognito asked to solve a capcha tho

**Comment by FDAkira** [comment]
> According to `runtime.log` the error was a 403. Have you attempted to log in again using your credentials before jumping in to Multi?

I tried, but the game still wouldn't let me log in.

**Comment by Susko3** [comment]
Solve the Captcha in incognito, and try opening osu!lazer again

**Comment by sr229** [comment]
From experience this is because your IP is flagged by CloudFlare as bad reputation, so you may try @Susko3's recommendations first, otherwise, you may need to contact your ISP due to your IP being flagged.

**Comment by FDAkira** [comment]
> Solve the Captcha in incognito, and try opening osu!lazer again

Didn't work

**Comment by sr229** [comment]
> > Solve the Captcha in incognito, and try opening osu!lazer again
> 
> Didn't work

Looks like you need to either use a VPN for now as a workaround. I don't think this is something we can fix at Lazer's side since this is a ISP-related issue.

**Comment by Susko3** [comment]
> > Solve the Captcha in incognito, and try opening osu!lazer again
> 
> Didn't work

If you restart your PC, and open an incognito window again, do you still get the Captcha?
