### ISSUE TITLE
Wacom 2021.323.0 Auxilarity Problem

### ISSUE THREAD

**Issue by emmersemmie** [ppy/osu#12216]
hey so whenever I plug in my Wacom tablet to play it says "Detect: Failure to Find Auxilarity Device, Express Keys may be unavailable." and my mouse glitches and jitters every time I am on the osu! screen. It works everywhere else on my computer except osu! :( . sorry if I sound kind of stupid lol, I'm new to the community so I'm unaware if this problem is common.

osu! version: 2021.323.0

thank u <3

image: 
![image](https://user-images.githubusercontent.com/81598568/112917692-34015800-90d1-11eb-94eb-97dc798f53c0.png)

**Comment by smoogipoo** [comment]
Please make an issue at OTD's respository: https://github.com/OpenTabletDriver/OpenTabletDriver/issues/new?assignees=&labels=bug&template=bug_report.md&title=
