### ISSUE TITLE
Accuracy in profiles are displayed incorrectly

### ISSUE THREAD

**Issue by LavaDesu** [ppy/osu#12221]
**Describe the bug:** 
Hit accuracy in profile details and rankings are two decimal places off to the right.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/56823419/112945518-9bb1b480-915e-11eb-85d2-a5e211a95a50.png)
![image](https://user-images.githubusercontent.com/56823419/112946699-09121500-9160-11eb-927e-81c461fc15a6.png)

**osu!lazer version: b9b0623c831e11d63347a28de7c3aacdb7ca0652**

**Comment by bdach** [comment]
Will have regressed with #12181. @peppy I glossed over this, but was there some particular reason to change `UserStatistics.Accuracy` away from `decimal` to `double` and nuke the overload?

**Comment by peppy** [comment]
Seemed unnecessary. Still unsure why necessary.

**Comment by peppy** [comment]
Okay I can see why it was necessary and, well, that's one of the worst code smells I've seen in a while. Let's not do that the same way.

**Comment by peppy** [comment]
Local fix is best for now.
