### ISSUE TITLE
Key bindings don't differentiate from left and right modifier keys

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#12233]
intended:
![screenshot014](https://user-images.githubusercontent.com/44514667/113068628-438da900-9184-11eb-986d-4adb015682e3.png)

actual:
![osu_2021-03-30_18-16-19](https://user-images.githubusercontent.com/44514667/113068662-5b652d00-9184-11eb-9186-7189d1233718.jpg)

additionally, osu!lazer should also differentiate between the numberpad keys and the non-numberpad keys as keys like the right arrow key and the numberpad 6 key(numlock off) give the same input 
keys like 7 and numberpad 7(numlock on) also give the same input

**Comment by frenzibyte** [comment]
Duplicate of https://github.com/ppy/osu-framework/issues/2136

**Comment by peppy** [comment]
Fine to leave this open to track the framework-side issue. We can't expect users to also search on the framework.

**Comment by FamousPig** [comment]
I think this can be closed since the framework-side counterpart https://github.com/ppy/osu-framework/issues/2136 is resolved

**Comment by peppy** [comment]
No, please open a new issue covering that.
