### ISSUE TITLE
new osu!lazer update (2021-331.0) crashes on my macbook air 2016 (macOS Mojave 10.14.6)

### ISSUE THREAD

**Issue by infinite-pi** [ppy/osu#12243]
since I downloaded the update about 12 hours ago, the game would crash before opening fully, it would show its icon bouncing on the dock and then it would disappear. this only occurs on the new update and I've already tried restarting my laptop and reinstalling the update

https://user-images.githubusercontent.com/81694640/113154194-57abd600-926a-11eb-9970-0933a17fdb3b.mov

the osu! open on the left is the 2021-323.0 update, and even closing that doesn't change anything

**Comment by bdach** [comment]
Please re-read the issue template and follow it instead of entirely deleting it.

**Comment by smoogipoo** [comment]
> I can't find the logs folder anywhere so I don't know what I can do to provide those logs

The logs should be found in your `~/.local/share/osu/logs` folder.
