### ISSUE TITLE
Using rate on osu!mania seems to break accuracy timing window

### ISSUE THREAD

**Issue by AlexHgC** [ppy/osu#12242]
**Describe the bug:** 

If you put a rate lower than 1.0 on OD10 ( or lower ) maps like 0.7 for example, the accuracy ( timing windows ) will be a lot more easier, and it's really easy to have MAXs with high OD maps, which is not supposed to be the case.

It's hard to proof what i mean with only screenshot, but when you play OD10 base map 4*, and other OD10 harder map with like 0.5 rate for down into 4*, you can feel the timing window is a lot more easy, with the same OD/difficulty

**First, the score with base map OD8, no modifier :**
![image](https://user-images.githubusercontent.com/31996023/113147837-7e99e600-9231-11eb-8cae-61620a53fae5.png)

**The same map OD8 with 0.8 rate :**
![image](https://user-images.githubusercontent.com/31996023/113147895-8d809880-9231-11eb-8dc5-7a650c449cdd.png)

**And now, the same map with 0.7 rate and OD11 modifier :**
![image](https://user-images.githubusercontent.com/31996023/113148021-ac7f2a80-9231-11eb-87c9-9df782eaeb6d.png)

**Comment by vernonlim** [comment]
lazer mania might be using the same rate algorithm as other modes, which simply changes the game clock, making timing windows tighter/looser for higher/lower rates respectively. in stable, the timing windows are adjusted to keep them the same.

**Comment by bdach** [comment]
For the record, please avoid statements such as "players will be outraged", because nobody wants that. Stating that it's already the case in stable would have been enough.

**Comment by AlexHgC** [comment]
So this is not intended ? Because i think this feature doesn't really fit with osu!mania, accuracy is the most important part of this gamemode. Having some different timing windows for the same OD is too weird

**Comment by smoogipoo** [comment]
This is the case on all timing-based rulesets (i.e. all except catch). If this behaviour changes for mania, it must change for all rulesets.

**Comment by smoogipoo** [comment]
Closing this to be tracked under https://github.com/ppy/osu/issues/12248
