### ISSUE TITLE
Input settings on Android

### ISSUE THREAD

**Issue by TheDarkDnKTv** [ppy/osu#12252]
We need settings of input on Android platform more than any other. 
Since I seen deep input settings on desktop version of osu!lazer, even integrated tablet drivers, i was hoping we have same on Android. Using an OTG-capabale smartphone and connecting mouse/tablet i haven't seen an any input settings except a key mapping. In last release even raw input/sensetivity settings was removed.

Please add it if possible, I want to play osu when out home as well :)

**Comment by peppy** [comment]
Most settings on mobile are done at the system level, not application.

For instanced, mouse speed: http://efigureout.com/change-mouse-speed-in-android/

**Comment by TheDarkDnKTv** [comment]
I glad you answer so fast. May be some phones can handle this. But not any. For desktop there is more ability to change input settings even through system or third party software. But on most of phones I had and my current one (Meizu 16th) I have no ability to disable mouse acceleration, change it sensitivity. Also as big issue I cant use external graphical tablet since Wacom not providing android drivers anymore. (On my old 4 android phone tablet were working)

So I please add some tweak from ingame for android, otherwise there is no clue to play on that platform for me :-(

**Comment by bdach** [comment]
Android is not a priority. Completing the game for desktop comes first.

**Comment by peppy** [comment]
If my answer wasn't clear, android doesn't *expose an interface* to change these settings. It can not be done from our end. You will need to ask google for this functionality, not us.
