### ISSUE TITLE
Star rating number doesn't show

### ISSUE THREAD

**Issue by NotGumballer91** [ppy/osu#12257]
**Describe the bug:** 
The star rating text doesn't show for some reason. I can see it from the draw visualiser though.
It just happened randomly. I didn't tweak much with my windows. Also, note that this started happening to me before even the tablet support was even added.

**Screenshots or videos showing encountered issue:** 
![osu_2021-04-02_02-35-53](https://user-images.githubusercontent.com/64581009/113338978-6e325a00-935c-11eb-9741-14a31360c81f.png)

**osu!lazer version:** 2021.331.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/6245782/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6245783/updater.log)
[performance.log](https://github.com/ppy/osu/files/6245786/performance.log)
[network.log](https://github.com/ppy/osu/files/6245787/network.log)

**Comment by bdach** [comment]
Next thing to check would be the texture atlas window (Ctrl+F3), to make sure the font even got loaded, I guess.

**Comment by peppy** [comment]
Also please try *renaming* the `caches` folder in your lazer folder. Please don't delete it, as we will ask for a copy if this fixes the issue. See https://github.com/ppy/osu/issues/12174#issuecomment-806304053 for further instructions.

**Comment by NotGumballer91** [comment]
> Also please try _renaming_ the `caches` folder in your lazer folder. Please don't delete it, as we will ask for a copy if this fixes the issue. See [#12174 (comment)](https://github.com/ppy/osu/issues/12174#issuecomment-806304053) for further instructions.

Works now. For some reason, it didn't load. Thanks!

**Comment by frenzibyte** [comment]
Please attach your broken `caches` folder here, as mentioned above.

**Comment by NotGumballer91** [comment]
> Please attach your broken `caches` folder here, as mentioned above.

done!
