### ISSUE TITLE
Scores and information does not sync to account.

### ISSUE THREAD

**Issue by AriDaBirb** [ppy/osu#12267]
Hello,
When I play a level the scores and information I got from when playing it doesn't actually sync to the actual account. I think it is because I have both osu and osu!lazer installed using the same account, but I'm not quite sure. I keep checking my accounts details after I play a few levels, but it hasn't seemed to have synced since I got osu!lazer. Another person i know also has the same issue.

2021.331.0
encountered on both Linux and Windows 
**Logs:**
https://pastebin.com/znS5bpE3

**Comment by jai-x** [comment]
Score submission has not been enabled on osu!lazer yet.
This is intentional.
