### ISSUE TITLE
Can't CMD Tab out of osu! when it's fullscreened.

### ISSUE THREAD

**Issue by mmattbtw** [ppy/osu#12260]
[macOS 11.2.3 \\ MacBook Air M1]

When launching osu!, I can no longer CMD Tab out of the game. I have to put it in Windowed mode. Is this a bug or a limitation with macOS?

<details>
<summary>Appreciation</summary>
Good job on the work with the macOS release, works really well on M1 Rosetta 2 emulation <3
</details>

**Comment by peppy** [comment]
Have you tried turning off "high precision mouse"? Does that help?

**Comment by mmattbtw** [comment]
@peppy Yeah, with the Window Mode as "Fullscreen", and high precision mouse off, Cmd+Tab still doesn't work :/

**Comment by H7perus** [comment]
I have a similar issue on Windows10, where I am unable to tab out in the latest version of lazer properly.
It is still in the foreground and as soon as I click once I am back in the application.

**Comment by johnny-prencipe** [comment]
same issue on my machine. works fine in windowed mode though

**Comment by peppy** [comment]
Please don't comment unless you have new information. We are aware that this happens for more than one person.

**Comment by peppy** [comment]
@mmattbtw please test this again on the latest release.

**Comment by Joehuu** [comment]
Still doesn't work with same hardware, maybe a rosetta bug if it's working with intel macs?

FWIW there are other games I downloaded with the same behavior: StepMania (also using SDL), Stardew Valley, and Don't Starve Together.

**Comment by mmattbtw** [comment]
@peppy Just did, still can't CMD Tab

**Comment by Joehuu** [comment]
Seems like this cannot be fixed, see https://github.com/ppy/osu/discussions/13351.
