### ISSUE TITLE
Use decimal value type for tablet input area settings

### ISSUE THREAD

**Issue by Methos-** [ppy/osu#12263]
**Describe the bug:** Messed around with the new update, had a lot of fun using the built in tablet support. I had no ability to use decimals so I decided to pass them through the configuration file (input.json) instead. Worked perfectly in-game, just that it seems it cause the tablet input options screen to bug out a bit. 

**Content of the input.json file:**
`{"InputHandlers":[{"$type":"osu.Framework.Input.Handlers.Keyboard.KeyboardHandler, osu.Framework","Description":"Keyboard","IsActive":true,"Enabled":true},{"$type":"osu.Framework.Input.Handlers.Tablet.OpenTabletDriverHandler, osu.Framework","IsActive":true,"AreaOffset":{"x":58.21,"y":43.55},"AreaSize":{"x":75.3,"y":42.36},"Rotation":352.5,"Tablet":{"Name":"Wacom CTH-480","Size":{"x":152.0,"y":95.0}},"Description":"OpenTabletDriver","Enabled":true},{"$type":"osu.Framework.Input.Handlers.Joystick.JoystickHandler, osu.Framework","Description":"Joystick / Gamepad","IsActive":true,"Enabled":true},{"$type":"osu.Framework.Input.Handlers.Midi.MidiHandler, osu.Framework","Description":"MIDI","IsActive":true,"Enabled":true},{"$type":"osu.Framework.Platform.Windows.WindowsMouseHandler, osu.Framework","IsActive":true,"UseRelativeMode":true,"Sensitivity":1.0,"Description":"Mouse","Enabled":true}]}`

**Screenshots or videos showing encountered issue:** 
![osu_2021-04-02_00-39-56](https://user-images.githubusercontent.com/6557053/113394024-65398c80-934c-11eb-9aff-8d477af2b2ce.jpg)

**osu!lazer version:** 2021.331.0

**Logs:** 
[network.log](https://github.com/ppy/osu/files/6248387/network.log)
[performance.log](https://github.com/ppy/osu/files/6248388/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6248389/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6248390/updater.log)
[database.log](https://github.com/ppy/osu/files/6248391/database.log)

**Comment by peppy** [comment]
This issue should probably be reworded to request decimal input support at the settings. We don't support manually editing configuration files.
