### ISSUE TITLE
Multi touch (Note 20 Ultra)

### ISSUE THREAD

**Issue by BsRebornPhoenix** [ppy/osu#12277]
Ok so for reference I am using a Galaxy Note 20 Ultra with the S Pen.

**Problem:** When im play osu lazer on mobile it only lets me use one of my fingers or the s pen and other taps on the screen will not be recognized. I hover play using the s pen ( it tracks the s pen perfectly when hovering) but when hovering it doesn't let me touch the screen with my fingers. This also happens when not using using only fingers it only recognizes one at a time so no dragging play either so what's left is tapping but that is super inefficient.

 **Describe the new feature:** I believe this is due to Samsung's built in accidental touch function. I have also noticed that in Minecraft, Terraria, LoL Wild Rift and some other games they allow more then one touch at a time so it is possible to fix the future on the note 20 but when introducing the s-pen into those games it brings it back down to one touch. So i think you can at least fix drag play with fingers. As for the s pen i not sure if there is a way to fix it but i hope there is because it would be a perfect game for the note 20 ultra and it would be inconvenient to have to use a different stylus instead then the one provided with the phone.

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/4201
