### ISSUE TITLE
IPC Source set to "Not found" after every restart

### ISSUE THREAD

**Issue by akuponcture** [ppy/osu#12289]
**Describe the bug:** The client seem to forget about the stable path after every restart even tho my stable.json file is correctly set, this issue only appeared recently.

**Screenshots or videos showing encountered issue:** https://youtu.be/bbRnzlpp3OI

**osu!lazer version:** 2021.331.0

**Comment by MiraiSubject** [comment]
I found the solution. Am on mobile right now I'll fire a PR when I'm back at my desk. Was pretty sloppy of me.


I called the ctor parameter for storage instead of `this.storage` in subsequent calls in ctor causing the attempts to read to fall in the incorrect place.
