### ISSUE TITLE
Red slider tail anchor only emulates one anchor

### ISSUE THREAD

**Issue by facespkz** [ppy/osu#12286]
**Describe the bug:** When importing maps made in stable editor, a red slider tail anchor is interpreted as only one anchor instead of two. This doesn't seem to affect gameplay, but it makes some sliders look weird without it.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/22137884/113496827-6ab0e700-94b2-11eb-8a5b-93425bac31e6.png)

![image](https://user-images.githubusercontent.com/22137884/113496482-d1340600-94ae-11eb-8e97-0297f01e8ff6.png)

**osu!lazer version:** 2021.331.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6253915/runtime.log)
[database.log](https://github.com/ppy/osu/files/6253916/database.log)
[performance.log](https://github.com/ppy/osu/files/6253917/performance.log)
[network.log](https://github.com/ppy/osu/files/6253918/network.log)

**Comment by peppy** [comment]
- Please include the beatmap.
- Please show your expectation of what it should look like.

**Comment by facespkz** [comment]
[Within Temptation - The Unforgiving [In The Middle Of The Night]](https://osu.ppy.sh/beatmapsets/29157#osu/172611) (05:47:893)

The slider is meant to have an appearance similar to that of perfect-circle sliders, which seemed to be implemented a couple months after the mapset's approval.
![2021-04-03_23-17-13-519645541](https://user-images.githubusercontent.com/22137884/113500454-ed499e80-94d2-11eb-9ea3-505c924d92d0.png)

Changing the red anchor to white mirrors the shape in Lazer.
![2021-04-03_23-18-11-744048765](https://user-images.githubusercontent.com/22137884/113500531-91334a00-94d3-11eb-8f1d-310c69ac46c1.png)

**Comment by peppy** [comment]
Wow. I actually have no idea how this works, so will require further investigation.

**Comment by facespkz** [comment]
Adding two anchors really close to each other seems to produce the same shape on both versions.


![2021-04-04_00-01-36-288254539](https://user-images.githubusercontent.com/22137884/113501340-1c630e80-94d9-11eb-9566-523c603a3695.png)
![2021-04-04_00-03-50-286843968](https://user-images.githubusercontent.com/22137884/113501360-44eb0880-94d9-11eb-8df0-62fb8f2a5cbf.png)

**Comment by smoogipoo** [comment]
I'm prioritising this one since it's a game-breaking change that also affects diffcalc.
