### ISSUE TITLE
Osu!Mania don't finish after a song finished.

### ISSUE THREAD

**Issue by Zetz512** [ppy/osu#1229]
hey! i'm new here and i can't speak correctly this language but anyways...

I always play on osu!mania and previous version i can't play that... but that newer version i'ts working fine, ty...

The issue now is when i play a song and finish that, the game "don't finish" stay in-game as if you had not finished it ...

Image: https://gyazo.com/c02f4a82a67d7fa3da2666e36effe47f

sry for my bad english and ty a lot for this.
cheers

**Comment by peppy** [comment]
This game and mania are both very much a WIP. You are reporting a valid issue but there are so many issues apart from this that we aren't really in need of such reports. Stay tuned and your experience should rapidly improve, as mania is one of our primary focuses at the moment :)
