### ISSUE TITLE
Custom gamemode/ruleset fails to load

### ISSUE THREAD

**Issue by Kookie167** [ppy/osu#12307]
Hi.

**Describe the bug:** 

I'm trying to import custom rulesets into osu!lazer without any success. I first tried the sample working freeform game via
`dotnet new ruleset-example -n MyCoolWorkingRuleset`. I first opened the osu folder from inside the osu!lazer client and put the dll from `C:\...\MyCoolWorkingRuleset\osu.Game.Rulesets.MyCoolWorkingRuleset\bin\Debug\netstandard2.1` into the rulesets folder. I then restarted the game and I get the following error shown in first the screenshot below.

I then tried a different gamemode from `https://github.com/karaoke-dev/karaoke`. Here I downloaded the latest release of the DLL (2021.0116.0), put it into the same rulesets folder and restarted the game. Unfortunately I got the error shown in the second screenshot. May I please know what I am doing wrong and how I can get these rulesets to work?

**Screenshots or videos showing encountered issue:** 

![errorproblem](https://user-images.githubusercontent.com/50559893/113648642-4599bf80-96d0-11eb-84ea-c9a689b746cb.png)
![errorproblem1](https://user-images.githubusercontent.com/50559893/113649055-1b94cd00-96d1-11eb-876b-be4509dbedd0.png)

**osu!lazer version:** 
2021.331.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6261553/database.log)
[network.log](https://github.com/ppy/osu/files/6261556/network.log)
[performance.log](https://github.com/ppy/osu/files/6261557/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6261559/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6261560/updater.log)

**Comment by peppy** [comment]
You are using an outdated version of the templates. They were updated yesterday so recreate your project or bring it up-to-date.

Again, you are doing this wrong and should be using the provided test projects in the templates, not moving it into a release build of osu!. If you did this, it would at least have run.

**Comment by Kookie167** [comment]
Hi Peppy, thanks for the quick response. I admit to being on a new level of stupid, but for the sake of others (and myself too), could you explain how to use the test projects in the templates?

**Comment by peppy** [comment]
Press the debug or run button in your IDE. The template projects are setup to be usable like any other c# project in existence.

If you are unfamiliar with this I recommend doing some tutorials on visual studio (or whatever IDE you are using) to get familiar with the project build controls.

**Comment by Kookie167** [comment]
Okay, it's good you explained that. However, I've done that before and I got the error below.

![Screenshot 2021-04-06 122331](https://user-images.githubusercontent.com/50559893/113650082-fc973a80-96d2-11eb-9b72-597f5a7d6612.png)

Could it be something else that's the problem?

**Comment by smoogipoo** [comment]
You need to run the `MyRuleset.Test` project, not the `MyRuleset` project

**Comment by Kookie167** [comment]
Got it. Thank you so much! I thought the Tests project just had unit tests in them. Just to clarify, should I run the other gamemodes via their `.Tests` project?

**Comment by smoogipoo** [comment]
If you're developing - yes.
