### ISSUE TITLE
Allow users to exclude scores with certain mods in beatmap leaderboards

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#12317]
**Describe the new feature:** 
As for now, users can 'create' leaderboards that consist of one particular mod/mod combination. The proposal is that for users to be able to 'create' leaderboards that consist of all mod combinations with the mod that user wants doesn't want

**Proposal designs of the feature:** 
Example: User doesn't want to see HD plays in the leaderboards, so he unchecks HD mod in a new selection menu and checks all other mods. If user wants to see all scores that consist of HR mod, he can uncheck 'No Mod' and check the HR mod and all other mods that he's interested in.

**Comment by smoogipoo** [comment]
I don't think this is going to happen for the during-gameplay/songselect leaderboard. But you can use the beatmap listing to filter how you want:
![image](https://user-images.githubusercontent.com/1329837/113862844-e4631080-97e3-11eb-8d79-368304971900.png)

**Comment by smoogipoo** [comment]
Going to close as this is not going to be on our priorities for a very long time.
