### ISSUE TITLE
Music bindings conflict with song select bindings

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#12312]
**Describe the bug:** Regressed in https://github.com/ppy/osu/pull/12225 due to onpressed actions being handled first before onkeydown actions.

This problem was seen before in https://github.com/ppy/osu/pull/9194#discussion_r436855778, albeit in a different scenario (both being onpressed but music bindings happening first).

**Comment by peppy** [comment]
can you explain which bindings specifically?

**Comment by Joehuu** [comment]
F1 (restart/previous) and F3 (play/pause) is blocking the mod select and beatmap options toggle respectively.

**Comment by peppy** [comment]
Aha, that's not such a bad one at least. I think we may want to convert those to also use global actions, will take a look.

**Comment by Joehuu** [comment]
There's a PR doing that as said on my OP (https://github.com/ppy/osu/pull/9194).
