### ISSUE TITLE
Accuracy Graphs do not send in Multiplayer games

### ISSUE THREAD

**Issue by kirbykirby56** [ppy/osu#1232]
Hello! I'm not a great programmer, but I would like to work on sending accuracy graphs in multiplayer games. When you click on someone else's name, their accuracy graph doesn't show. Is there a reason for this?

**Comment by jorolf** [comment]
this is osu!lazer and not stable

**Comment by kirbykirby56** [comment]
I believe I might have put this in the wrong place. Thanks!
