### ISSUE TITLE
"sliderslide" hitsamples do not seem to be playing

### ISSUE THREAD

**Issue by peppy** [ppy/osu#12325]
As per title. Using class skin.

**Comment by smoogipoo** [comment]
Can't repro https://drive.google.com/file/d/1y1iJOe-naQDT9Lo9kaaZd47jkACh2ZDm/view?usp=sharing

Are you sure the beatmap didn't set the volume set to 0%?

**Comment by peppy** [comment]
I was testing using disco prince (where there should be whistles during the sliders). Based off a user report, see https://twitter.com/CPrinsje/status/1379821300156358659.
