### ISSUE TITLE
Alt entering in song select also starts game

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#12327]
**Describe the bug:** Can reproduce on Windows and macOS with M1.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/35318437/113912415-f1561480-978f-11eb-9f8d-619a0615824b.mov

**osu!lazer version:** since 2021.407.1

**Comment by peppy** [comment]
As it turns out, this is fixed by #12334!
