### ISSUE TITLE
Alt-scroll on editor timeline no longer zooms

### ISSUE THREAD

**Issue by peppy** [ppy/osu#12328]
I believe this may be a regression from input handling order, but the volume control now gets the scroll events too soon.

**Comment by peppy** [comment]
This actually looks to be working correctly now. Not sure if it was something my end, but closing for the time being.

**Comment by peppy** [comment]
Going to reopen this as I think it may still be an issue. For me it seems like ctrl+alt are both required, where it should only actually require `alt`. Confirmation that others can reproduce this on `master` would be appreciated.

**Comment by Joehuu** [comment]
Can confirm. The volume global actions are blocking the zoom, and as global actions are `KeyCombinationMatchingMode.Modifiers`, pressing another modifier will prevent them from working.

**Comment by peppy** [comment]
Right, didn't realise the default bindings for volume adjust is actually alt-mousewheel.

In that case we may want to consider changing the modifier for the editor timeline zoom change.

**Comment by LittleEndu** [comment]
Was this reverted at some point? <kbd>Alt</kbd>+scroll doesn't zoom anymore while <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+scroll does.

**Comment by bdach** [comment]
@LittleEndu cannot reproduce. works fine here. are you hovering over the timeline?

**Comment by LittleEndu** [comment]
I indeed am hovering over the timeline.

https://user-images.githubusercontent.com/11320483/133321710-8ad2d228-3b4e-4198-92d5-00f367b95ffc.mp4

**Comment by bdach** [comment]
i do hope the on-screen keyboard is just for demonstration purposes to show that alt is being pressed and not what you're actually using to claim that? as in this also happens when using an actual physical keyboard?

either way this may be windows-specific or even specific to your system because i can assure you it works locally here. need more info to act or someone else to check windows.
