### ISSUE TITLE
Video not playing on linux without external libraries

### ISSUE THREAD

**Issue by ghost** [ppy/osu#12332]
( Offtopic: I have been referred to here via this thread I posted https://osu.ppy.sh/community/forums/topics/1292220 )

**Describe the bug:** 

I am facing issues playing video when playing osu!lazer on Void Linux.

I am playing the game via Lutris through the AppImage.

I have all vulkan drivers required & the proprietary Nvidia drivers.

https://cdn.discordapp.com/attachments/816329962435903509/829463527223459840/unknown.png - The Nvidia Packages I installed via XBPS for the proprietary driver.

https://imgur.com/VboPewe - The Packages I installed via XBPS for vulkan.

**Screenshots or videos showing encountered issue:** 

https://streamable.com/tgk2v9

**osu!lazer version:** 

2021.407.1

**Logs:**

database.log : https://gist.github.com/0ae/8e4fbd18899b1e346582b8848e618f45

network log: https://gist.github.com/0ae/9f78cb5427ad3c7c44e607bb0bc50aa5

performance log: https://gist.github.com/0ae/0ef1479439b662bd120bc28d653da2a1

runtime log: https://gist.github.com/0ae/3714882a89dac8182f868f96b5d38131

**Comment by xFadedxShadow** [comment]
Audio for some reason is also not working for me last update it was not sure why it just decided to stop. Basically osu can't spawn a ALSAlib slave.

**Comment by peppy** [comment]
i don't believe there have been any changes our end which would cause this. so it is more than likely a system configuration issue on your end.

**Comment by smoogipoo** [comment]
We don't currently include ffmpeg libs with our linux builds. Not entirely sure on the reason - maybe we just didn't have the binaries, maybe people argued that system libs should be used instead, maybe it was to do with licensing.

The issue should fix by installing ffmpeg system-wide.

**Comment by smoogipoo** [comment]
Tracking at https://github.com/ppy/osu-framework/issues/4349

**Comment by xFadedxShadow** [comment]
> i don't believe there have been any changes our end which would cause this. so it is more than likely a system configuration issue on your end.

Thank you for letting me know ill give you an update as soon as possible.

**Comment by yellowsink** [comment]
I am having video playback issues just like this (arch linux), but i do have a systemwide ffmpeg available: 4.4 as `ffmpeg` and 3.4.8 as `ffmpeg3.4`

**Comment by Theighlin** [comment]
I think this has been fixed.
