### ISSUE TITLE
Blacklisting hid_uclogic on startup

### ISSUE THREAD

**Issue by osufan11** [ppy/osu#12335]
I would like to see lazer in startup blacklisting hid_uclogic on linux.
Ofcourse this is just a request.

**Comment by peppy** [comment]
Context? Logs? Anything?

We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

**Comment by enoslayd** [comment]
iirc blacklisting is a root action

**Comment by osufan11** [comment]
> iirc blacklisting is a root action

But its possible to give lazer root permissions.

**Comment by smoogipoo** [comment]
osu! will not be given root permissions.

**Comment by osufan11** [comment]
> osu! will not be given root permissions.

Hmm. Alright.
