### ISSUE TITLE
Expand TimeSignatures from Enumerator to customisable object.

### ISSUE THREAD

**Issue by Coppertine** [ppy/osu#12333]
**Describe the new feature:** 
Expands from #12020 

Currently, the TimeSignature is displayed as an enum. This can cause issues for songs of more complex timing and would require additional enum values.
A better solution to this would be to convert the Enum into a class of two values (numerator and denominator), simular to that of a Vector2. Which these can also have static values similar to the current Enum (i.e. ```TimeSignature.SimpleTriple = new TimeSigature(3,4)```).
With this, we can include new additions to the time signatures without having to break the legacy parsing or having to resort for timing the bpm for 5/8 or any other abitrary time signatures.
This eliminates time signatures issues with 7/8 for example. With the legacy editor, you are forced to use x/4 on uninherited timing points. Enforcing mappers to place a new timing point every 3 and a half beats in the editor. (Great example for this is [onumi - CONFUSION PART ONE](https://osu.ppy.sh/beatmapsets/1037665#osu/2197286) or Camellia - Qyoh (Nine Stars) (written in 7/8, but mappers noted to only use 1 7/4 timing point and call it a day))

**Comment by peppy** [comment]
Let's track this here https://github.com/ppy/osu/issues/2316 (this new issue is basically a duplicate, or a proposed solution to the problem and does not need to exist as its own isssue).
