### ISSUE TITLE
Sound stays at inactive volume when clicking back with a tablet

### ISSUE THREAD

**Issue by matheusfsreinert** [ppy/osu#12345]
**Describe the bug:**  Click outside the game and click back with a tablet the volume will stay at inactive. If you use the mouse it has the expected behavior. I'm using osu's built-in tablet driver on Arch Linux with Xorg

**Screenshots or videos showing encountered issue:** Inactive volume is at 0 for a better demonstration 
https://streamable.com/b23f1j

**osu!lazer version:** 2021.407.1

**Logs:**
[database.log](https://github.com/ppy/osu/files/6281990/database.log)
[network.log](https://github.com/ppy/osu/files/6281991/network.log)
[performance.log](https://github.com/ppy/osu/files/6281992/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6281993/runtime.log)

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu/pull/12334
