### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by emperorsolar** [ppy/osu#12341]
**Describe the new feature:** 
On the iOS beta there is no way to stream so could u please make it so u can drag your finger to follow the stream and use 2 other fingers to spam 
**Proposal designs of the feature:**

**Comment by smoogipoo** [comment]
Duplicate of https://github.com/ppy/osu/issues/4201

**Comment by emperorsolar** [comment]
Oh I just noticed I was asking the same thing as that guy
