### ISSUE TITLE
You can only edit the same beatmap once.

### ISSUE THREAD

**Issue by abassboostedraphater** [ppy/osu#12346]
I know editor is in progress but in the next update can you fix this or is this just not a feature lazer has yet? You can only edit the same beatmap once and never again. I spent 6 hours making one and decided to take a break from it. I came back opening the editor again and there was no option to edit saved beatmaps. I just have an unfinished beatmap sitting there now. I really want to get back to editing it again so if this could be fixed that would be great.

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

- You haven't shown or provided logs as to why you can edit your beatmaps.
- You haven't provided a screenshot showing the flow you're taking.

**Comment by peppy** [comment]
Are you missing the method of entering the editor?

![20210409 111916 (dotnet)](https://user-images.githubusercontent.com/191335/114119364-76266700-9925-11eb-9829-6728e177598a.gif)

or

![20210409 111958 (dotnet)](https://user-images.githubusercontent.com/191335/114119402-89d1cd80-9925-11eb-8b61-c40c9925edef.gif)

**Comment by Joehuu** [comment]
Closing as there hasn't been a response since.
