### ISSUE TITLE
Importing a collection will also import maps in it

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#12359]
**Describe the new feature:** 
Is it possible to create a method that only imports maps from collections and not all maps in general? I don't want to import all 10,000 maps, those 1,500 from the collections are enough for me.

**Comment by peppy** [comment]
Collection support is planned to be improved, but if you're asking about import from stable specifically, no that will not be an option.

Please leave it running overnight, or first create a new copy of your stable install, delete all maps you don't want, then import from that.
