### ISSUE TITLE
Menu/UI Hover sounds audible when moving cursor while tabbed out.

### ISSUE THREAD

**Issue by ShiiTsuin** [ppy/osu#12351]
**Describe the bug:** 
When tabbed out (client is open in the background) in Borderless, Fullscreen or Windowed mode, moving the cursor over where a button is in the client results in the related hover sound being audible at full volume.

**Screenshots or videos showing encountered issue:** 
Unlisted video - https://youtu.be/DFb7oseoOhQ

**osu!lazer version:** 
2021.407.1

**Logs:**
https://shii.s-ul.eu/eLOtwEIX

Can't see this reported anywhere, but sincere apologies if it is and I've missed it.

**Comment by peppy** [comment]
Duplicate of https://github.com/ppy/osu/issues/12345
Duplicate of https://github.com/ppy/osu-framework/issues/4347
Fixed via https://github.com/ppy/osu/pull/12334
