### ISSUE TITLE
Skin's cursormiddle carries over to beatmap skins without one

### ISSUE THREAD

**Issue by facespkz** [ppy/osu#12363]
**Describe the bug:** Skins that have cursormiddle.png, such as osu!classic, carry it over to a beatmap that doesn't use one. This also makes the cursor use the wrong kind of trail.

The map in these screenshots can be found here:
[Feint - Times Like These (Fracture Design Remix) [Happy Times]](https://osu.ppy.sh/beatmapsets/82635#osu/228607)

**Screenshots or videos showing encountered issue:** 

### Lazer

2008 skin
![osu_2021-04-10_10-04-44](https://user-images.githubusercontent.com/22137884/114278393-733e7b80-99e4-11eb-8f4e-53cdaf76e683.jpg)

osu!classic
![osu_2021-04-10_10-04-53](https://user-images.githubusercontent.com/22137884/114278395-75a0d580-99e4-11eb-8ba9-cc002f739991.jpg)

osu!lazer
![osu_2021-04-10_10-05-01](https://user-images.githubusercontent.com/22137884/114278398-7afe2000-99e4-11eb-901d-9244a359d457.jpg)

### Stable

Default
![screenshot041](https://user-images.githubusercontent.com/22137884/114279969-fb744f00-99eb-11eb-9a6f-7b7cf86e325a.png)

**osu!lazer version:** 2021.410.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6290354/database.log)
[network.log](https://github.com/ppy/osu/files/6290353/network.log)
[performance.log](https://github.com/ppy/osu/files/6290352/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6290351/runtime.log)

**Comment by peppy** [comment]
If possible can you also include a screenshot from osu!(stable) showing what you expect to see? Thanks.

**Comment by facespkz** [comment]
Taken with default skin selected.
![screenshot041](https://user-images.githubusercontent.com/22137884/114279969-fb744f00-99eb-11eb-9a6f-7b7cf86e325a.png)

**Comment by facespkz** [comment]
No longer an issue as of 2021.608.0
