### ISSUE TITLE
Add position options for the "Show FPS" setting

### ISSUE THREAD

**Issue by ZedME** [ppy/osu#12368]
The "Show FPS" setting shows the FPS counter with its position fixed towards the bottom-right side of the screen.

![osu_2021-04-11_14-49-27](https://user-images.githubusercontent.com/77842743/114317279-44ec9900-9ad5-11eb-81b2-2eb57eb01f13.jpg)

Add different position options for the FPS counter (top/bottom-left/right of the screen).

**Comment by peppy** [comment]
We probably won't allow moving it, but it will better position itself in the future. Let's track via https://github.com/ppy/osu/issues/4141.
