### ISSUE TITLE
Video causes osu! to crash

### ISSUE THREAD

**Issue by ClemensU42** [ppy/osu#12364]
So I wanted to make a beatmap for a friend of mine and the whole song is about 16 minutes long and so is the video I wanted to use as a background. Everything's working fine until I add the video as a background. Once I play the beatmap with the video, osu loads for about 3 - 5 seconds and then crashes. The mp4 file for the video is ~190mb in size.

**Comment by jai-x** [comment]
Please attach logs and system information as stated in the issue template.

**Comment by ClemensU42** [comment]
my system: 
cpu: Intel Core i7 CPU    920 @ 2.67GHz  (4 cores)
gpu: Nvidia GeForce GTX 1050ti
os: Windows 10

[runtime.log](https://github.com/ppy/osu/files/6290705/runtime.log)
[session.log](https://github.com/ppy/osu/files/6290706/session.log)

**Comment by jai-x** [comment]
This repository is for development for osu!lazer only.

Your issue appears to be for osu!stable.

Please open issue for osu!stable here: https://github.com/ppy/osu-stable-issues/
