### ISSUE TITLE
Add a 'Clear' drop-down button in 'Participated' and 'Owned' rooms in multiplayer

### ISSUE THREAD

**Issue by Modsnotworking** [ppy/osu#12365]
**Describe the new feature:** 
Right-Clicking any room in 'Participated' and 'Owned' drop-downs a 'create copy' button, it would be great if you'll add one more option in drop-down list, a 'Clear' Button. It will be great for those players who play Multiplayer a lot in osu!lazer  

**Here's a screenshot of the Drop-Down list which currently only has a 'Create Copy' button:** 
![osu_2021-04-11_10-04-37](https://user-images.githubusercontent.com/70589304/114292657-9a14b480-9aad-11eb-9870-e1b14777e401.jpg)

**Proposal designs of the feature:** 

1. Add an option in the drop-down list(when you right-click any room in 'Participated' and 'Owned' in Multiplayer) of 'Participated' and 'Owned' room in multiplayer
2. The option will/can be named like 'Clear' or anything that developers think preferable 
3. Clicking on the "Clear" button will clear the selected room

**Comment by peppy** [comment]
I don't think this will happen. These screens act as a history. Generally we don't allow selective deletion from history. I don't thing many people would use this.
