### ISSUE TITLE
Bug when importing beatmaps and skin at a same time

### ISSUE THREAD

**Issue by HelloYeew** [ppy/osu#12379]
**Describe the bug:** 

I downloaded a beatmap file from osu! and skin from r/osuskin subreddit and I import it at a same time and then this bug happen so I reproduce it 2 more time with a different file to record it (but forget to copy a log file) and this is a reproduce result.

_First reproduce_

This is first file list to import. (2 beatmaps and 1 skin and file order is beatmap come first)
![Screen Shot 2564-04-12 at 18 23 04](https://user-images.githubusercontent.com/68165621/114386997-23b2a800-9bbc-11eb-9ccc-df9c8036354d.png)
Then I imported it into osu!lazer at a same time.
Import result : 2 beatmaps is in a beatmap list and file deleted but 1 skin is not imported.
![Screen Shot 2564-04-12 at 18 27 03](https://user-images.githubusercontent.com/68165621/114387485-b05d6600-9bbc-11eb-86cb-3c0bffdcf6b1.png)

_Second reproduce_

This is second file list to import. (1 beatmaps and 2 skin and file order is skin come first)
![Screen Shot 2564-04-12 at 18 28 43](https://user-images.githubusercontent.com/68165621/114387678-ee5a8a00-9bbc-11eb-9d71-eb2278f01930.png)
Then I imported it into osu!lazer at a same time.
Import result : Both 3 file imported as a skin. Wait! 1 file is a beatmap. But it appear in a skin selection and you can select it as a skin. (I try to select and play it and it's osu!lazer default skin.)
<img width="460" alt="Screen Shot 2564-04-12 at 18 30 15" src="https://user-images.githubusercontent.com/68165621/114387844-23ff7300-9bbd-11eb-91eb-7ae1d7e27eb5.png">
That beatmap is still in folder and not appear in beatmap list and 2 skin files deleted.
![Screen Shot 2564-04-12 at 18 35 18](https://user-images.githubusercontent.com/68165621/114388410-d7686780-9bbd-11eb-9851-acbe01d30cb2.png)

**Screenshots or videos showing encountered issue:** 
- _First reproduce_: https://drive.google.com/file/d/1NVfCJwlKuGfBIrG_Jvl9TSM1RtvL9nnU/view?usp=sharing
- _Second reproduce_: https://drive.google.com/file/d/1NYypO4aygj-J3eEAjudgtrzuLXFAfvUW/view?usp=sharing

**osu!lazer version:** 
2021.410.0

**Logs:**
I forget to copy file lof after reproduce. I can reproduce a bug again and copy a log file if you want.

**Computer Specifications:**
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
Processor: 2 GHz Quad-Core Intel Core i5
Memory: 16 GB 3733 MHz LPDDR4X
Graphics: Intel Iris Plus Graphics 1536 MB
OS: macOS Big Sur 11.3 Developer Beta 5

**Comment by smoogipoo** [comment]
Yes, please provide logs.

**Comment by Game4all** [comment]
That one stems from the fact that  the string-based override of `Import()` is used,  which will assume that all the passed paths have the same extension as the first path of the list.

https://github.com/ppy/osu/blob/32868d0d459a1245dbebc22f4e35f3e18031ddfa/osu.Game/OsuGameBase.cs#L431-L443

**Comment by peppy** [comment]
@Game4all are you planning to make a fix for this?

**Comment by peppy** [comment]
I'll get this one, since it's a pretty bad failure.
