### ISSUE TITLE
Deselecting hitobjects in selection shouldn't allow moving the selection within the same button press

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu#12373]
**Describe the bug:** 

I think this is best described by the videos below. Ctrl+click-dragging hitobjects in a selection deselects that hitobject but allows moving the selection.

When ctrl+clicking, you'd expect to be selecting or deselecting objects. It's fine to be able to immediately move the selection when *selecting* something, but this causes jank if you can do the same while *deselecting* something.

Idk how to word the title, feel free to change if you have a better way to describe it.

**Screenshots or videos showing encountered issue:** 

Lazer:

https://user-images.githubusercontent.com/36758269/114325405-46977a80-9b30-11eb-9f3c-0cc646fcd211.mp4

Stable:

https://user-images.githubusercontent.com/36758269/114325409-4b5c2e80-9b30-11eb-87c2-7736a88aa178.mp4

**osu!lazer version:** 

Latest release: 2021.410.0

**Logs:**

N/A

**Comment by peppy** [comment]
Going by both windows and macOS logic here, I'm going to make it work as following:

- `Ctrl` drag from a non-selected object should add to the selection and begin a drag
- `Ctrl` drag from an existing selected object should maintain the selection and begin a drag

Deselection will be moved to `OnReleased` to achieve this.
