### ISSUE TITLE
Score submitting error, even with unranked , auto mods and custom ruleset.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#12372]
**Describe the bug:** After played some maps, score submitting notification error appear (Which didn't happened yesterday.) So I tried something (not) fun by enable auto mods, error still occour. Although the log was send(?) but I still want tracking issue (It's fine if not).

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/7066150/114324422-1235b580-9b54-11eb-8595-5eb17182f3a1.png)

**osu!lazer version:** 2021.410.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6292936/database.log),[network.log](https://github.com/ppy/osu/files/6292937/network.log),[performance.log](https://github.com/ppy/osu/files/6292938/performance.log),[performance-audio.log](https://github.com/ppy/osu/files/6292939/performance-audio.log),[performance-draw.log](https://github.com/ppy/osu/files/6292940/performance-draw.log),[performance-update.log](https://github.com/ppy/osu/files/6292941/performance-update.log),[runtime.log](https://github.com/ppy/osu/files/6292942/runtime.log),[updater.log](https://github.com/ppy/osu/files/6292943/updater.log)

**Comment by peppy** [comment]
The only error I can see is the autoplay one, which is the server complaining that you had autoplay enabled. We'll probably silence this one server-side eventually.

**Comment by IkaWaAyuMu** [comment]
I thought the normal one it's just server side (I think 404 doesn't do pop up notification since the score submitting update doesn't have this issue.) So the log is just autoplay one (which shouldn't submit the score.)
![image](https://user-images.githubusercontent.com/7066150/114334281-723c5400-9b74-11eb-9a26-da9e4b9237a8.png)
[database.log](https://github.com/ppy/osu/files/6293534/database.log)
[network.log](https://github.com/ppy/osu/files/6293536/network.log)
[performance.log](https://github.com/ppy/osu/files/6293537/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6293538/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6293539/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6293540/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6293541/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6293542/updater.log)

This may help too. :)
