### ISSUE TITLE
Hitting ctrl+z to undo deselects hitobjects when editing them

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu#12371]
**Describe the bug:** 

To be clear:
- In lazer, slider nodes display only when selecting the slider, while on stable they are also visible while just hovering the slider. (separate issue, not sure if intended)
- In lazer, selections disappear after undoing. (this is what this issue is about)

I thought this was reported already, but apparently not.

**Screenshots or videos showing encountered issue:** 

Lazer:

https://user-images.githubusercontent.com/36758269/114323920-bfde9f80-9b27-11eb-9b6e-3f7e16da7506.mp4

With multible selections, the last slider edited gets deselected:

https://user-images.githubusercontent.com/36758269/114323958-f5838880-9b27-11eb-874b-7a2468acebb2.mp4

Expected:

https://user-images.githubusercontent.com/36758269/114323921-c1a86300-9b27-11eb-8a8d-14408df6be77.mp4

**osu!lazer version:** 

Latest release: 2021.410.0

**Logs:**

N/A

**Comment by Walavouchey** [comment]
Right, and while I was pointing out the implications for sliders, this should also cover selection for all hitobjects.

I'll just add one more edge case with circles for completeness' sake:

https://user-images.githubusercontent.com/36758269/114324866-ff5bba80-9b2c-11eb-8264-46afe3fec50d.mp4

**Comment by peppy** [comment]
not related, 100% duplicate 😌
