### ISSUE TITLE
Skin misaligned

### ISSUE THREAD

**Issue by LemonJuicer** [ppy/osu#12385]
Skin misaligned

![image](https://user-images.githubusercontent.com/64481039/114462683-adc23700-9be3-11eb-9972-631632189f6d.png)
![image](https://user-images.githubusercontent.com/64481039/114462780-cc283280-9be3-11eb-8a94-ab03558e5a2d.png)
with opened HUD

build 2021.410.0

**Comment by LemonJuicer** [comment]
probably wasn't noticed because most skins dont have this "frame"

**Comment by frenzibyte** [comment]
I believe you're talking about the `scorebar-bg` element, that will not be fixed as the element is intended for the background of the health, not extend all over the screen to other parts of the HUD: https://github.com/ppy/osu/issues/12123#issuecomment-803541303.

As for the other highlighted part here:
<img width="552" alt="CleanShot 2021-04-13 at 00 31 03@2x" src="https://user-images.githubusercontent.com/22781491/114465247-896c5780-9bef-11eb-8683-659994960fb4.png">

I'm not sure what it's about, please elaborate more and I'll reopen if it needs. Closing.

**Comment by LemonJuicer** [comment]
Entire scorebar-bg is moved vertically so I highlighted the difference between top and bottom gap

**Comment by frenzibyte** [comment]
Then there's no need to keep this discussion further. As long as the related component doesn't desync places from its background piece, it's working correctly.
