### ISSUE TITLE
Get recommended song genre on random song select

### ISSUE THREAD

**Issue by Nebula3310** [ppy/osu#12387]
osu! will track the genre of music and possibly the length of the song that you play (a score that is counted as 1 playcount) so when you pick a random map with f2, you can get one that's tailored right to your likings. This can be toggled in the settings. This could also pair this with the recommended star rating, beatmap language, or any of the beatmaps' tags. 

Example: you play lots of metal songs in one osu! session, the random song select will give you songs that are similar in genre, length, and possibly star rating to give you a better experience playing osu!. 

The recommended maps reset after you close the game, so if you decide to play another genre the next day, you won't get cluttered with the genre you played last session.

**Comment by frenzibyte** [comment]
This will be implemented with the osu!web-side feature https://github.com/ppy/osu-web/issues/6879, which would probably be then ported to osu!lazer, something like the current `DifficultyRecommender` component.

Closing as already tracked osu!web-side, where the tracking goes.
