### ISSUE TITLE
In-game tablet - keep the area inside tablet

### ISSUE THREAD

**Issue by taep96** [ppy/osu#12398]
![114455434-0b528580-9bdc-11eb-9da5-eaf4dbb8ff3f](https://user-images.githubusercontent.com/64481039/114548879-a3924e00-9c60-11eb-9872-118350571041.png)
Count offset from edge of the area, not the center

**Comment by smoogipoo** [comment]
This needs to be an option. Both Hawku and OpenTabletDriver position from the centre, so it's easier for users of those drivers to migrate to osu!lazer using the current settings.

**Comment by LemonJuicer** [comment]
I was pretty sure it was counting offset from edge but it turns out you are right.
A better solution would be to not allow area move out the border.

**Comment by peppy** [comment]
What is the use case for this? Are you looking to transfer settings from an existing driver or something? Would be good to know where the requirement comes from.

**Comment by LemonJuicer** [comment]
I thought external driver works the way it actually doesn't.
Sorry for that, I edited my issue
