### ISSUE TITLE
Add precise volume settings from using the scroll wheel

### ISSUE THREAD

**Issue by ZedME** [ppy/osu#12403]
If you scroll the scroll wheel on an empty space in the screen, the volume settings for EFFECTS, MASTER and MUSIC pop up at the left side of the screen, but if you scroll by one increment, the volume setting changes by 5 increments.

Add a way to make precise volume settings from using the scroll wheel by using keyboard combinations, such as holding Shift with scrolling to set the volume options by a change in 1 increment.

**Comment by peppy** [comment]
Rather than add a key for precise adjustments, I've been looking at adding a basic acceleration implementation which allows for adjusting by 1 when scrolling slowly, but increases back to 5 if you scroll fast enough (allowing for quick large changes to still occur).
