### ISSUE TITLE
Make multiplayer chat visible during gameplay / results

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#12402]
**Describe the new feature:** 

In osu!stable, when you are in a multiplayer room, the chat overlay is always opened and the multiplayer chat tab is fixed at the beggining of all the tabs.
In osu!lazer, the multiplayer chat is separate from the overlay which contain all the chat tabs, so it looks like there is no need to make the room's chat tab be fixed in the chat overlay, but when the game starts, it's common for players to use the room's tab in the chat overlay to communicate something to the players while you are in a rest section of the map or when the gameplay is loading at the beggining.
Currently, it's hard to find the current room's tab in osu!lazer because it is always at the end and can be confusing because the name is always "lazermp_" along with some numbers, the idea is to make the current room chat tab be fixed at the beggining of the tab list in the chat overlay and maybe rename it to "multiplayer" as stable does.

**Comment by peppy** [comment]
we'll probably show a separate control for multiplayer chat, rather than use the global one.
