### ISSUE TITLE
Linux / X11 : Tablet not detected by in-game support and no longer works in-game using standard XWacom drivers

### ISSUE THREAD

**Issue by andrewathalye** [ppy/osu#12413]
**Describe the bug:** 
When using the latest builds of osu!lazer containing a built-in tablet recognition system on Linux, my Wacom Tablet, which otherwise is detected by GIMP and recognised by the builtin XWacom driver, is not recognised and additionally does not function as a mouse, although it does function outside of osu!.

As a test I reverted to using 2021.302.0, which had not yet added the built-in tablet functionality, and this worked as expected, allowing me to play using a tablet and keyboard.

**osu!lazer version:** 
2021.410.0 (regression from 2021.302.0)

**Logs:**

No errors were reported in the logs as I was unable to navigate past the main screen. If desired, I can attach them anyway, however there is no relevant information contained within database.log, network.log, performance.log, or runtime.log.

**Comment by peppy** [comment]
If you're using external tablet drivers, try toggling high precision mouse in game. Nothing else has changed. We haven't disabled or "broken" any external tablet support.

**Comment by andrewathalye** [comment]
High precision mode is actually still enabled, it seems that something changed between 2021.407.1 and 2021.410.0. Just to check I redownloaded both but 2021.410.0 consistenly does not accept tablet input, whereas 2021.407.1 always works as expected.

**Comment by andrewathalye** [comment]
If nothing has changed it is possible that there could be some other issue, but I'm not sure what else could cause the difference.

**Comment by andrewathalye** [comment]
diff -r osu-2021.407.1/osu.Game/OsuGameBase.cs osu-2021.410.0/osu.Game/OsuGameBase.cs
311c311,313
<             var globalInput = new GlobalInputManager(this)
---
>             GlobalActionContainer globalBindings;
> ^M
>             var mainContent = new Drawable[
313,314c315,317
<                 RelativeSizeAxes = Axes.Both,
<                 Child = MenuCursorContainer = new MenuCursorContainer { RelativeSizeAxes = Axes.Both }
---
>                 MenuCursorContainer = new MenuCursorContainer { RelativeSizeAxes = Axes.Both },
>                 // to avoid positional input being blocked by children, ensure the GlobalActionContainer is above everything.
>                 globalBindings = new GlobalActionContainer(this)
319c322
<             base.Content.Add(CreateScalingContainer().WithChild(globalInput));
---
>             base.Content.Add(CreateScalingContainer().WithChildren(mainContent));
321,322c324,325
<             KeyBindingStore.Register(globalInput.GlobalBindings);
<             dependencies.Cache(globalInput.GlobalBindings);
---
>             KeyBindingStore.Register(globalBindings);
>             dependencies.Cache(globalBindings);

This is the closest I could find by diff'ing the source code trees. I also found that by _disabling_ high precision mouse mode in 2021.410.0 the tablet functionality could be restored, whereas the opposite seems to be the case in 2021.407.1. Since there is now a workaround to make the tablet functionality work, this issue shouldn't prove to be a problem, however it is a noticeable change in behaviour between the two. Relative area may have something to do with the strange mouse mapping observed.

**Comment by bdach** [comment]
The diff above is terminally broken, and I'd be surprised if the linked changes had anything to do with this. Please run a proper bisection if you wish to pinpoint the issue.

**Comment by andrewathalye** [comment]
Sorry about that, I'll try to get a bisection done within an hour or so. To note, disabling high precision mouse in the latest build seems to bypass whatever the issue is, whereas in earlier builds that actually made the tablet not work.

**Comment by andrewathalye** [comment]
[dfe3240b45557c4229a0e41e854dc9ce3cfa5f6a] Merge pull request #12353 from nekodex/songselect-hoversamples

According to my bisection, this is the commit which causes the change in behavior. I repeated it twice since this commit doesn't seem to change anything that would influence tablet behavior, but in both cases it was the first known bad commit. The change in ppy.osu.Game.Resources version might be related.

**Comment by bdach** [comment]
That also makes zero sense and looks to be an invalid bisection. If it was a framework bump that did it, I might understand. But in no way should a resource bump influence input behaviour.

**Comment by peppy** [comment]
Either way the user got the issue fixed, so this does not require further discussion for now (given it's linux).
