### ISSUE TITLE
Flashlight feels unnatural (size not matching?)

### ISSUE THREAD

**Issue by takoz53** [ppy/osu#12417]
**Describe the bug:** 
Unlike stable osu!, the flashlight mod feels very unnatural as it feels like it is some ms behind the actual cursor movement, making it much harder to see next notes.

**osu!lazer version:** 2021.410.0

**Comment by frenzibyte** [comment]
There's an intentional smoothing applied, but I don't see how it is ms behind? maybe a video comparing between osu!stable and osu!lazer on a certain beatmap so it's notable how it's harder to see next notes?

**Comment by peppy** [comment]
Asking about the user's perception is not really useful here. Either it matches stable or doesn't.

In this case it looks to numerically match but the way interpolation is invoked is slightly different, so required a double-check.

**Comment by takoz53** [comment]
I could make a 1:1 video. I'll be posting it by tomorrow on slow speed so it might be visible. Might be just my feeling, but I play FL often and it is just different (?)

**Comment by peppy** [comment]
A video would be helpful. Note that there's still some other issues which still need addressing apart from the movement speed (see https://github.com/ppy/osu/issues/3740)

**Comment by takoz53** [comment]
Sorry for being a bit too late on this topic. I have a 1:1 clip from stable & lazer.

At timing point 00:10 you can see that I'm moving my cursor on lazer but it won't move for a bit and then move afterwards, which is the slight delay I'm talking about. In stable though, the area moves 1:1 with the cursor as if it was a cursor overlay.

I understand that ofc the flashlight effective area etc. is subject of change, but the slight delay should be still visible! If not, I can still point some arrows and whatever to make it a bit more visible.

If this is helpful: https://puu.sh/Hz90q/8c51ed50e9.png Radius between cursor and flashlight is not always the same R.

**Comment by peppy** [comment]
Did you forget to link the video?

**Comment by takoz53** [comment]
Sorry! https://www.youtube.com/watch?v=E-N7GpTrL_0&ab_channel=takoz53

**Comment by peppy** [comment]
Thanks, but it honestly looks correct from that video. I think this issue will only proceed further if frame comparisons are done (or comparing the underlying alrogorithm for accuracy).

**Comment by takoz53** [comment]
Alright. Sorry for not being helpful on this. It's just feeling very odd.

**Comment by DomiZone1** [comment]
osu!stable also lags behind the cursor as seen here:

![stable_cursor_lag](https://user-images.githubusercontent.com/74203314/115965389-5a2be380-a529-11eb-97bc-c6d05861de58.png)
Which was already pointed out [here](https://github.com/ppy/osu/issues/3740#issuecomment-485349391) so that is not the problem.

but the visible area on osu!stable is a good bit larger which may be the problem as seen here:

![size_clearer](https://user-images.githubusercontent.com/74203314/115966059-459d1a80-a52c-11eb-9c03-ff0358a4a725.png)
Here we can clearly see that the circle with the 4 in it is somewhat hidden in lazer while it is not in stable! With the smaller visible area on lazer its easier to notice that the visible area lags behind, which may make it feel 'unnatural'.

I hope i could help out.

**Comment by dailac-boiii** [comment]
Apart from the size issue, it’s seems Fl in Lazer lacks the blurring effect from Stable as well. Should this be tracked in a separate issue?

**Comment by frenzibyte** [comment]
Yeah probably worth tracking it separately, it's not clear enough what this issue is even about, seems to be along the lines of size not matching, unrelated from blur effect.

**Comment by peppy** [comment]
What is the "blur effect"? If you mean the "size of the gradient" then this issue is already ample to track that.

**Comment by chipscaper** [comment]
i want it to be more blurred in lazer since it looks kinda bad rn imo

**Comment by Joehuu** [comment]
Mostly fixed via https://github.com/ppy/osu/pull/20566.
