### ISSUE TITLE
Add star rating to be visible in player loader screen

### ISSUE THREAD

**Issue by ZedME** [ppy/osu#12414]
There is a star rating for every beatmap in the game, and it is only visible in the beatmap-selecting screen.

Add a way to see the star rating of a specific beatmap in the beatmap-loading screen as well.

The screen I am talking about (beatmap-loading screen):
![osu_2021-04-14_14-03-10](https://user-images.githubusercontent.com/77842743/114766525-7dd67900-9d34-11eb-90ce-f005c39ad21b.jpg)

**Comment by frenzibyte** [comment]
I recall there being an issue requesting adding further beatmap info on player loader screen, but I can't find it, perhaps it was for another section in the game.

**Comment by peppy** [comment]
@arflyte do you have a design update for the player loading / metadata screen? (not a priority, just wondering before we add more information to the existing one as a temporary measure).

**Comment by arflyte** [comment]
So far major changes to the loader screen, Can easily add more info to it.

**Comment by peppy** [comment]
If someone wants to look at adding this in the mean time, it could just be displayed in the current listing either as text or using the existing `StarRatingDisplay` component.

**Comment by frenzibyte** [comment]
Been fiddling around with this, and wondering what sounds best:
 1. following the carousel style and show it as it was there (not 100% sure about it though, feels weird/out of its place)
  ![CleanShot 2021-05-06 at 00 24 09](https://user-images.githubusercontent.com/22781491/117211294-7bca7c00-ae01-11eb-8e89-07e52ec1d7a2.png)

 2. or add a simple star rating display down the difficulty and call it a day.
  ![CleanShot 2021-05-06 at 00 30 30](https://user-images.githubusercontent.com/22781491/117211922-4d996c00-ae02-11eb-9373-ac09be657627.png)

**Comment by bdach** [comment]
The former two make very little sense to me. Last one all the way as far as I'm concerned.
