### ISSUE TITLE
New editor timeline hit objects don't display selections

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#12425]
**Describe the bug:** 

It's very difficult to tell which hitobjects are selected with the new blueprints in the editor timeline.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/1329837/114863684-020b2800-9e2b-11eb-98a4-32402acb8878.png)

**Comment by peppy** [comment]
Yeah, I'm aware of this. Will add back tomorrow in some form I guess. Luckily selections are generally consecutive so it's not a common issue
