### ISSUE TITLE
Osu Lazer no open 

### ISSUE THREAD

**Issue by omarxd332** [ppy/osu#12434]
Hi im from chile my english is bad 
My osu does not open when I click on the icon and I wanted to know if there is any way to solve it I was seeing other posts on this subject but I did not find a solution because my English is a bit bad and it is difficult for me to understand

I do not know if it will have to do with having the normal osu installed but I leave this post in case someone can help me

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

**Comment by omarxd332** [comment]
I can not give more information because I do not know the root of the problem I just installed the game and when trying to enter the game it loads and remains in the task manager for 2 seconds and closes suddenly without any message, I do not know how else I can provide information since I do not know why the game does not want to open

**Comment by smoogipoo** [comment]
Please re-read the issue template...

```
**Logs:**

<!--
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*
- `Android/Data/sh.ppy.osulazer/logs` *(on Android)*,
- on iOS they can be obtained by connecting your device to your desktop and copying the `logs` directory from the app's own document storage using iTunes. (https://support.apple.com/en-us/HT201301#copy-to-computer)
-->
```

**Comment by omarxd332** [comment]
[runtime.log](https://github.com/ppy/osu/files/6322187/runtime.log)
[SquirrelSetup.log](https://github.com/ppy/osu/files/6322189/SquirrelSetup.log)
[updater.log](https://github.com/ppy/osu/files/6322190/updater.log)
[database.log](https://github.com/ppy/osu/files/6322191/database.log)
[performance.log](https://github.com/ppy/osu/files/6322192/performance.log)

**Comment by smoogipoo** [comment]
Can you upload the `%AppData%/osu/client.db` file? You will need to .zip it.

**Comment by omarxd332** [comment]
[client db osu.zip](https://github.com/ppy/osu/files/6322210/client.db.osu.zip)

**Comment by peppy** [comment]
@smoogipoo As it's malformed there's probably no recovering it (that's an sqlite level issue). I'd recommend just deleting the file and starting from scratch here.

**Comment by omarxd332** [comment]
what should i do

**Comment by peppy** [comment]
Delete `client.db` and run the game again.

**Comment by omarxd332** [comment]
I was finally able to come in, thank you very much for taking the time to help me: D
