### ISSUE TITLE
osu!lazer Arch Linux X Error

### ISSUE THREAD

**Issue by xero-lib** [ppy/osu#12435]
After installing ose!lazer (osu-lazer) from the AUR for Arch Linux, upon trying to run, I get this error: 
![image](https://user-images.githubusercontent.com/54485853/114967038-574e3600-9e39-11eb-9c2e-df0d9fd5f26d.png)

**osu!lazer version:**  

**Logs:**

 
The specified logs folder is empty: 
![image](https://user-images.githubusercontent.com/54485853/114969077-41db0b00-9e3d-11eb-9e58-904af280d558.png)

**Comment by smoogipoo** [comment]
Looks like you don't have graphics drivers installed.

Can you run other OpenGL applications? Try `glxgears`. And post the output of `glxinfo -B`.

**Comment by xero-lib** [comment]
> glxinfo -B

Interesting, both also return th error. Let me reinstall graphics drivers and renoot, I'll post status here after.

**Comment by smoogipoo** [comment]
In any case, there's nothing more that we can do here, so I'm closing this issue. Feel free to post back if you have more information.

There's very few cases where SDL fails to initialize a GL context, but they'll appear as an error output by the game and not by X itself.

**Comment by xero-lib** [comment]
Any advice of what to do if it isn't fixed by reinstalling drivers?

**Comment by smoogipoo** [comment]
I don't, it's specific to your installation/system. I use Arch Linux + X, so the default configuration works fine on my end.

Googling around has several results:
- https://bbs.archlinux.org/viewtopic.php?id=195435 Suggests kernel/driver/dependencies mismatch.
- https://forums.developer.nvidia.com/t/quadro-k600-x-glxcreatecontext-issue/40088/5 Suggests some issues with/without indirect GLX.
- Check journalctl, check `ldd /usr/bin/glxinfo` and see if any dependencies are missing, etc.

Beyond that, it's up to you, sorry.

**Comment by DavidHusicka** [comment]
Maybe you need to install OpenGL libraries. If you have Nvidia GPU, these are not installed by installing the `nvidia` package. You need additional `nvidia-utils` package. `pacman -S libgl` should install the GL libraries no matter what GPU you use but it is recommended to read the Wiki first and choose the correct package. 

https://wiki.archlinux.org/index.php/OpenGL
