### ISSUE TITLE
Have slider rotation dongle overlap the timeline

### ISSUE THREAD

**Issue by Momoccchi** [ppy/osu#12433]
It is somewhat annoying having to move to the middle of the screen just to rotate it.

Screenshots or videos showing encountered issue: https://twitter.com/Momochi85/status/1382761208722432001?s=20

osu!lazer version: 2021.410.0

**Comment by frenzibyte** [comment]
Willing to take this one, but, is displaying the selection box in front of the timeline the desired direction here? was thinking about moving the rotation button to the opposite side of the box instead, rather than blocking display from the timeline.

**Comment by peppy** [comment]
You mean dynamically moving it depending on whether it is able to be displayed without being covered?

**Comment by frenzibyte** [comment]
Yep.

**Comment by peppy** [comment]
Just above or below sounds fine, but "all sides or centre" sounds like a really bad user experience.

I'm not sure making it dynamically switch sides is a final step, but if you think you can make it happen with minimal implementation then it sounds like a good starting point, at least to see how it feels.

The primary issue here is that there's not enough breathing space for the playfield (it should have padding equivalent to half a hitcircle size, at least).
The secondary issue is the rotation control is too far away from the edge. Other applications generally bundle the rotation control into the selection box's corners:

![20210416 114023 (Figma)](https://user-images.githubusercontent.com/191335/114963960-ca42c580-9ea8-11eb-8f77-eb47cc8426d4.gif)

**Comment by Theighlin** [comment]
I noticed this also happens on the bottom of the editor, so even if you implement the rotation on the corners, the other options should shift to the top of the selection box
![osu_2021-04-16_13-27-58](https://user-images.githubusercontent.com/53081750/115018001-9c18b200-9eb7-11eb-9a49-5d61b91cb15a.png)

**Comment by peppy** [comment]
@frenzibyte are you still planning to look at this one?

**Comment by frenzibyte** [comment]
Yeah is my focus now. Adding the ability to rotate from the corners of the selection box sounds better, will give it a try first and see how it goes.
