### ISSUE TITLE
Numpad keys are not differentiated from non-Numpad keys

### ISSUE THREAD

**Issue by vernonlim** [ppy/osu#12430]
When setting keybinds, Numpad keys with NumLock On/Off are not differentiated from their counterparts on the rest of the keyboard.
Some examples:
NumpadRight (Numpad6 with NumLock off) is the same as Right
Numpad6 is the same as 6
Numpad5 is the same as 5

In settings menu:
![image](https://user-images.githubusercontent.com/25032854/114882872-f9b8ea00-9e36-11eb-9a83-78925ab1dc2a.png)
(Special 1 is RightArrow and Key 6 is NumpadRight, both are triggered at the same time when pressing either)

**Comment by smoogipoo** [comment]
I don't think this is something that can be supported. Numlock is a very hacky thing in Windows, as we've discovered many times with stable.

But I'll leave it open, just low priority/never getting fixed.

**Comment by vernonlim** [comment]
I think I might be misunderstood? This is a feature in stable already and isn't about ignoring the NumLock state (that's another issue), it's differentiating between for example Numpad1 and regular 1, or NumpadRight and the RightArrow key.

![image](https://user-images.githubusercontent.com/25032854/114886060-cfb4f700-9e39-11eb-8195-12d6e7d2f378.png)
(this is impossible in lazer, since it binds to 1 3 1 3 and pressing either will trigger both keys)

I apologize if that's what you meant.

**Comment by frenzibyte** [comment]
Yes we understood that, and as been mentioned above, the underlying issue may not be easily solvable, but this is left open for now as low priority.

**Comment by vernonlim** [comment]
Very sorry if this is unwanted input — A possible solution is to somehow use keyboard key positions instead of what they output in the OS (reading keyboard scancodes?) which would make this issue invalid and fix ppy/osu-stable-issues#589 (present in lazer atm), which is a much bigger inconvenience for players using the numberpad. If that is being considered this could be closed.

**Comment by bdach** [comment]
SDL does return scancodes ([and we're using them right now](https://github.com/ppy/osu-framework/blob/99786238a02e0d6b69da86dd52e5506ee8ec0566/osu.Framework/Platform/SDL2/SDL2Extensions.cs#L310-L341)). To fix this we would have to introduce `KeypadRight` et al., the same way `KeypadN` exists already.

Bringing up stable is irrelevant as it goes through a wholly different input backend.

**Comment by frenzibyte** [comment]
I was gonna bring this up but I'm a bit confused on something, @vernonlim already stated that there is no difference between regular number key and numpad number key, but I think that should not be the case?

**Comment by bdach** [comment]
That would need investigation on behalf of the reporter. If the keyboard is question is already sending out `SDL_SCANCODE_N` for the numpad keys (which it may well do) there is nothing that we can do to fix this.

As far as I can tell on linux number keys get distinguished correctly with numpad on.

**Comment by vernonlim** [comment]
I tested it again, I might have been running an old version of lazer or have an interfering program running because it works fine now.

**Comment by vernonlim** [comment]
Sorry for turning things into such a mess, I've tested things with the latest version of lazer without other programs running and have found these remaining issues (mostly unrelated to title).

- Numeric Numpad keys (the output with NumLock on) aren't displayed properly in the settings menu, displaying as just "1" instead of "Numpad 1" despite registering differently in gameplay. 

- Holding L/RShift causing Numeric Numpad keys to not register is not an issue, but holding a Numpad key causes the Shift key to stop registering until the Numpad key is released, making it impossible to use them simultaneously (problem when using Shift to dash and Numpad to move in catch)


The rest are minor/debatable. 

- Numpad function keys (NumLock off) like NumpadRight aren't distinguished from ordinary keys like Right.

- NumLock state is taken into account when setting gameplay keybinds, which might cause confusion as the same key might suddenly not register in gameplay if NumLock is accidentally pressed.

**Comment by bdach** [comment]
> NumLock state is taken into account when setting gameplay keybinds, which might cause confusion as the same key might suddenly not register in gameplay if NumLock is accidentally pressed.

But that changes the keybind text, no? For instance, if you press <kbd>Num1</kbd> with numlock off, <kbd>End</kbd> will appear instead. Numlock state ought to work exactly as it does anywhere else on the system.

**Comment by vernonlim** [comment]
Yeah, exactly, hence why it's in the "minor/not problems" section. They are more observations than issues. I will just remove that from the comment.
