### ISSUE TITLE
DeviceIOException: Unable to open HID class device (OK)

### ISSUE THREAD

**Issue by kerostampcrab** [ppy/osu#12449]
osu!lazer says "DeviceIOException: Unable to open HID class device (OK)." and doesn't detect my Wacom CTL-490. I'm using input-wacom drivers on Manjaro.

https://i.imgur.com/vMiaP8x.png

I'm on osu!lazer 2021.410.0

[database.log](https://github.com/ppy/osu/files/6325920/database.log)
[network.log](https://github.com/ppy/osu/files/6325921/network.log)
[performance.log](https://github.com/ppy/osu/files/6325922/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6325923/runtime.log)

**Comment by smoogipoo** [comment]
Consult the OpenTabletDriver FAQ: https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ

**Comment by kerostampcrab** [comment]
it didn't work

**Comment by smoogipoo** [comment]
You will need to make an issue in the OpenTabletDriver repository, we can't help here.
