### ISSUE TITLE
Memory Leak affecting both linux and windows.

### ISSUE THREAD

**Issue by ILOVEPIE** [ppy/osu#12451]
**Describe the bug:** 
A couple of people including myself have encountered a issue where playing lazer for more than a few hours with multiple restarts of the game client results in large amounts of ram getting used up however closing lazer does not fix it. It did not seem to have this problem before 2021.410.0.
Unknown if it occurs on 2021.416.0.
**Screenshots or videos showing encountered issue:** 
Not helpful for this issue.
**osu!lazer version:** 
2021.410.0
**Logs:**
https://mega.nz/file/UQRSAJAZ#z2Nhn81q5sBmUed0Tn8Fnev7zSHFtCCZb3QZjcSTAGA

**Comment by peppy** [comment]
"closing lazer does not fix it" then this is an issue with your operating system.

you are going to have to provide a process dump (from task manager. on windows. on the latest release).

**Comment by peppy** [comment]
Closing this until further details are provided from the latest release. The attached logs show nothing and there's nothing to work with here.

**Comment by ILOVEPIE** [comment]
I suspect lazer might be triggering a memory leak in the Nvidia driver or something, because the only commonality between the hardware/software of both of us who experienced this is that we both run Nvidia GPUs. I'll try reproducing the issue on my windows partition.
