### ISSUE TITLE
Make approach rate work similar to Scroll Speed in osu!mania.

### ISSUE THREAD

**Issue by Striikerr** [ppy/osu#12452]
**Describe the new feature:** 
The majority of people who play osu! likely prefer a certain approach rate on maps over others, similar to most players in osu!mania 
with scroll speed. I personally don't see why osu! players are forced to use an approach rate set by a map set while osu!mania can freely change their scroll speed to whatever they're comfortable with.
**Proposal designs of the feature:** 
Like osu!mania, players would be able to change their approach rate either through keybinds in the song select screen or through a menu, similar to the current difficulty adjust modification or in the settings menu like scroll speed in osu!lazer

**Comment by peppy** [comment]
There's a mod to allow this, called "difficulty adjust". Please use it.

**Comment by Striikerr** [comment]
I was more talking about making this feature rankable

**Comment by peppy** [comment]
So was I. Difficulty adjust will likely be usable as you want to. Thanks for understanding.
