### ISSUE TITLE
Alt+Scroll in editor timeline to Zoom in/out Timeline

### ISSUE THREAD

**Issue by Eeveelution** [ppy/osu#12455]
**Describe the new feature:** 
Alt+Scroll should ideally like in stable allow for Timeline Zoom

**Proposal designs of the feature:** 
In osu!stable's editor, there's a handy shortcut that can Zoom In or Zoom out the timeline which is Alt+Scroll when hovering the cursor above the timeline, This is very handy as it removes the need to spam the + and - keys for Timeline Zoom, and makes the process much more convinient and easy to do.

**Comment by frenzibyte** [comment]
https://user-images.githubusercontent.com/22781491/115082368-7d91d580-9f0e-11eb-920a-1c7e07defffb.mp4

That was already a feature that got regressed in the last release (2021.410.0), but is now working correctly? can you confirm you're running latest release (2021.416.0)?

**Comment by Eeveelution** [comment]
ok what, i swear this didnt used to work. now it works for some reason, aaaaaaaaaaa this is embarassing

**Comment by frenzibyte** [comment]
Happens 🤷🏼‍♂️
