### ISSUE TITLE
Add "Reset keybind" button for all individual keybinds

### ISSUE THREAD

**Issue by ZedME** [ppy/osu#12457]
Add a reset button for all the keybinds that have been configured. This makes it simpler for single keybind resets, instead of resetting a whole section of keybinds.

**Comment by peppy** [comment]
You're asking for a button to reset every single key bind?

**Comment by ZedME** [comment]
Just a reset button for every keybind so we can reset it to its normal keybind
Ex: If I change the screenshot keybind, then I can reset only the screenshot keybind to its regular keybind by pressing the reset button it individually has.

**Comment by peppy** [comment]
Right, thanks.
