### ISSUE TITLE
Use of Classic mod

### ISSUE THREAD

**Issue by DESLiZADORES** [ppy/osu#12469]
Will this be implemented?
Before ScoreV2 replaces ScoreV1 in all scores and Lazer has the ability to update profiles (in coming weeks yes?) , The use of classic mod (scoreV1) will allow you to play on Lazer as if it were Stable client and submit _ranked_ scores

**Comment by frenzibyte** [comment]
I think both classic mod and non-classic mod scores will be submitted, not sure what you're proposing here?

**Comment by DESLiZADORES** [comment]
> I _think_ both classic mod and non-classic mod scores will be submitted, not sure what you're proposing here?

Well, I mean (gain ranks from it) since ScoreV2 isnt ranked, right?

**Comment by peppy** [comment]
You can follow development process and timeline, but please don't use github issues to ask questions about it. If you're just curious how things will work, either check existing talks, interviews, blogs, tweets, or wait until the feature you're interested in is actually implemented.
