### ISSUE TITLE
Add changes to score multipliers for using osu!mania mods

### ISSUE THREAD

**Issue by ZedME** [ppy/osu#12463]
Since the mods in osu!, osu!taiko and osu!catch have mods that affect the score, it should make sense that osu!mania should also have this. It makes the osu!mania mods far more useful because we can play more with a purpose like to increase our score.

**Comment by peppy** [comment]
Score multipliers are, for the moment, not considered to be something we will be using going forward. They made be removed or reconsidered in a multiplayer or legacy way.

If anything, osu!mania is closer to the direction we are intending to go.
