### ISSUE TITLE
Copy pasted objects are selected but do not show rotation box

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#12471]
[Video](https://puu.sh/HzjmU/28b9bd0097.mp4)

Latest version
2021.416.0

Sorry if duplicate, could not find related issue

**Comment by peppy** [comment]
This is due to `SelectionBlueprint.LoadComplete` getting run after `SelectionHandler.updateVisibility`, causing it to miss the fact that any blueprints are selected. I'll look into this one.
