### ISSUE TITLE
Catcher should not fade during hyper-dash state

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#12472]
[Video](https://puu.sh/HzkFS/68d1c8036e.mp4)
It matches the opacity of the afterimage when dashing from a hyperfruit instead of glowing like in stable

Latest version as of 4/18/2021, 2021,416.0

**Comment by frenzibyte** [comment]
Can you attach the skin you tested this with, it doesn't look to lose opacity with osu!classic skin to me?

**Comment by RaiLTC** [comment]
[Here you go](https://puu.sh/HzkHm/4821f5f60c.osk)

**Comment by RaiLTC** [comment]
It does happen with every skin. It happens when dashing from a hyperfruit
[osu!classic skin](https://puu.sh/HzkPF/838dd95b48.png)
[osu!lazer skin](https://puu.sh/HzkRp/5d9615284b.png)

**Comment by frenzibyte** [comment]
Aha, yes that's what's happening right here:
https://github.com/ppy/osu/blob/89bea2868a9ca68a8c09a9c93db6f504e9022a96/osu.Game.Rulesets.Catch/UI/Catcher.cs#L387-L391

With catcher fade:

https://user-images.githubusercontent.com/22781491/115139090-b8902800-a038-11eb-9bd9-425186199fa9.mp4

Without catcher fade:

https://user-images.githubusercontent.com/22781491/115139088-b6c66480-a038-11eb-8bcb-682aba3b96f8.mp4

I feel without fade is better than fade, but would probably need further opinion and why the fade was added in the first place.

**Comment by RaiLTC** [comment]
Fading is a bad idea, makes it hard to judge your location especially on higher difficulties where you usually look around the center of the screen and not around the catcher

**Comment by peppy** [comment]
Not sure why this is here as it isn't in stable. Let's remove it for now.
