### ISSUE TITLE
Crash when stacking zero-length hold note and normal note in osu!mania editor

### ISSUE THREAD

**Issue by linearaccelerator** [ppy/osu#12477]
**Describe the bug:** 
When opening the osu!mania editor and creating a hold note with 0 length (without dragging it so the hold area is visible) and then stacking a normal note on top of it, the game crashes with a System.ArgumentException.
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/64271566/115154325-8c959680-a07a-11eb-8e5a-5b5dcf2c9f89.mp4

**osu!lazer version:** 
2020.410.0
**Logs:**
(The logs got overwritten because I reopened the game so I don't have them anymore, but the full stack trace is shown at the end of the video)

**Comment by bdach** [comment]
Zero length hold notes even being able to exist at all here is the bug.
