### ISSUE TITLE
Game and audio doesn't load when using monitor audio

### ISSUE THREAD

**Issue by titus-ong** [ppy/osu#12482]
I use my monitor audio for osu! specifically, so I've set the audio device in osu!'s settings as such (Dell S2421HN (Intel(R) Display Audio)). It has been working for the previous lazer versions, up to 2021.410.0. 

This morning, when I installed 2021.416.0, the game window opened but it stopped loading when the "2021.416.0" appears at the bottom of the screen (so just before "welcome to osu!" appears), and no audio was playing. After fiddling a little with .410 and .416, I realise that if I set my audio device in osu! to be my laptop speakers (Realtek High Definition Audio), the game loads fine, so the issue seems to be with the monitor audio device (I managed to do this by setting it in .410, and the settings were carried over to .416 so I could open it).

Now that I could open .416 in a roundabout way, I tried setting the audio device back to my monitor audio. It worked and I could hear audio through my monitor's audiojack, but after I alt-tabbed out and in, the audio was gone and I couldn't click play in the "now playing" box. 

I've attached the [logs](https://github.com/ppy/osu/files/6333336/logs.zip) here. I am playing on Windows 10 version 2004.

**Comment by peppy** [comment]
Before we check further, have you tried restarting? Sounds like your audio device might be in a bad state.

**Comment by smoogipoo** [comment]
Can you explain what's going on in the logs/how you've taken the logs? It seems like the audio device is being changed multiple times - are you causing this to happen?

Can you also provide a log when starting with the bad audio device selected on startup, when it gets stuck?

**Comment by titus-ong** [comment]
@peppy yes I've restarted my computer. I'm able to use my monitor audio to listen to other things.

@smoogipoo sorry yeah I realise the logs were quite messy. I took a new set of [logs](https://github.com/ppy/osu/files/6333683/logs.zip), hope this helps.

**Comment by smoogipoo** [comment]
Just to confirm - you're not changing any devices throughout that?

**Comment by titus-ong** [comment]
For the recent set of logs, nope. I don't know if this is related or not, but there is an issue where the audio device changes from my monitor audio to my laptop speakers (even when monitor audio is default) whenever I alt-tab in and out of osu! for a few seconds, and this has always been the case for lazer (I think I saw an issue here on it before? not sure).

**Comment by smoogipoo** [comment]
I think this is probably going to be resolved by https://github.com/ppy/osu-framework/pull/4469. @peppy confirm this is one of the issues you looked at?

**Comment by peppy** [comment]
Should be, yes.

**Comment by smoogipoo** [comment]
@titus-ong Please wait for and check on the next release, and report back if it still isn't resolved.
