### ISSUE TITLE
Barrel roll extended limits

### ISSUE THREAD

**Issue by Moxanthia** [ppy/osu#12489]
I'd like to see the ability to play the barrel roll mod at a much higher rpm. It's quite fun and I can see myself playing with it from this point forward, but in its current state it doesn't pose much of an extra challenge. I'm not sure what ceiling would be reasonable, but maybe 11 like the other extended limits settings.

**Comment by peppy** [comment]
Increasing to 11 will offer almost no difference. Also if it is to be changed, we would not use the "extended limits" term; the allowable range would just be increase. "extended limits" is only there because it's outside the normal editor range.

**Comment by Moxanthia** [comment]
I believe it would be much more difficult at a higher rpm especially with low AR hidden. I've used an rpm visualizer tool online to try and guess what speed would be most fun, but it really is hard to say without being able to play it.

**Comment by peppy** [comment]
Ah, my mistake. The old value used to be 10, but after converting to RPM it is now 4. I'd say either changing to 10 or 12 is a safe number, although it may make selecting lower values hard.

**Comment by Moxanthia** [comment]
Oh okay, great!
