### ISSUE TITLE
Confine TABLET cursor to osu window using tablet driver.

### ISSUE THREAD

**Issue by Rubydesic** [ppy/osu#12494]
**Describe the new feature:**  With the new tablet driver option, if the tablet area is reduced and the "confine mouse cursor to window" option is set to "never", the tablet cursor will go off the osu screen if your pen goes outside of the area you set. 

Setting "confine mouse cursor to window" is undesirable because you may wish to move your cursor outside of the window using the mouse but not using the tablet.

**Proposal designs of the feature:**:

Add a "Confine tablet cursor to window" option under the tablet input device settings that does the same thing as the mouse one but when you are using the tablet pen.

**Comment by peppy** [comment]
I believe this is already fixed in the next release via https://github.com/ppy/osu-framework/pull/4379.

**Comment by peppy** [comment]
@Rubydesic Going to close this for now as "likely-fixed". If you still have issues after the next release, please leave a comment here and we'll investigate further.
