### ISSUE TITLE
"Invalid client hash" web exception causes the game to freeze entirely

### ISSUE THREAD

**Issue by Samega7Cattac** [ppy/osu#12491]
When I join a multiplayer room and we start the match the beatmap starts to load for 1-2 secs and then just freezes the client there.
After waiting a bit it says that `dotnet stopped working`.
Checking the network logs it shows the following issue:
```
2021-04-19 22:31:48 [verbose]: Performing request osu.Game.Online.Rooms.CreateRoomScoreRequest
2021-04-19 22:31:49 [verbose]: Request to https://osu.ppy.sh/api/v2/rooms/66853/playlist/148088/scores failed with System.Net.WebException: UnprocessableEntity.
2021-04-19 22:31:49 [verbose]: Response was: {"error":"invalid client hash"}
2021-04-19 22:31:49 [verbose]: Failing request osu.Game.Online.Rooms.CreateRoomScoreRequest (osu.Game.Online.API.APIException: invalid client hash
2021-04-19 22:31:49 [verbose]: ---> System.Net.WebException: UnprocessableEntity
2021-04-19 22:31:49 [verbose]: --- End of inner exception stack trace ---)
```
It doesn't happen on solo.
I also have osu!stable installed.
Environment:
```
Archlinux 5.12.0-rc7-146-tkg-cfs
dotnet 5.0.5.sdk202-1
osu!lazer (git) 2021.416.0.r8.1832f624e2-1
```

**Comment by jai-x** [comment]
I believe only official released versions of osu!lazer are currently permitted to connect to multiplayer servers as identified through hash of the release. Since you are using the git version pulled from the AUR, this is not whitelisted as an official release.

Please use an official Linux AppImage made available from the releases page to connect to multiplayer: https://github.com/ppy/osu/releases

**Comment by Samega7Cattac** [comment]
Just wanted to avoid using an appimage.
btw
any plans for dealing with it gracefully instead of a freeze and crash?

**Comment by jai-x** [comment]
You're right, probably worth keeping this issue open to track gracefully handling this.

**Comment by peppy** [comment]
@Samega7Cattac Could you please include all logs, not just an excerpt of `network.log`? The information regarding the actual crash will be elsewhere to what you provided.

**Comment by huupoke12** [comment]
I'm able to reproduce the bug by playing in a playlist room (`2021.416.0.r73.e227c076e5-1` on `dotnet-runtime 5.0.5.sdk202`)
Logs:
[database.log](https://github.com/ppy/osu/files/6343092/database.log)
[network.log](https://github.com/ppy/osu/files/6343093/network.log)
[performance.log](https://github.com/ppy/osu/files/6343094/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6343095/runtime.log)

**Comment by RefriZaddo** [comment]
AHEM, I also have this problem but I have the official windows version
