### ISSUE TITLE
Slider Tails get detached when playing Wiggle Mod

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu#12505]
**Describe the bug:** Only applicable to legacy skins that have visible slider tails. When playing with Wiggle Mod, slider tails get detached from the slider and end up somewhere else.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/20495991/115414988-1daa7000-a229-11eb-95c9-a7ad823fc6e4.mp4

**osu!lazer version:** 2021.426.0

**Comment by peppy** [comment]
Have you tested on the latest master release?

**Comment by peppy** [comment]
This looks to occur *without* barrel roll mod enabled. Please test properly before reporting an issue to reduce wasted effort.

**Comment by LeNitrous** [comment]
Affects master. I'll edit the description and title as you only need wiggle mod to trigger this effect.
