### ISSUE TITLE
Osu doesnt open a window but shows in task manager

### ISSUE THREAD

**Issue by EgirlLani** [ppy/osu#12508]
I try to open up osu!Lazer because I enjoy playing on it a lot more than standard, because of the new features, and once, I was doing something to it, while playing mania, so I closed it and started it twice, (Idk why it was a while ago), then the 3rd time when I tried to open it, it wouldn't. I checked task manager and saw it showed up on task manager, I just uninstalled Lazer then reinstalled it, assuming that would fix the problem, and nope, every time I open it, it stays on task manager, but the window doesnt open

**Comment by bdach** [comment]
You need to attach the logs, as requested in the issue template. Closing until those are provided.
