### ISSUE TITLE
Beat blocks gamemode (keyboard arrows + spacebar)

### ISSUE THREAD

**Issue by Bryceed** [ppy/osu#12517]
**Describe the new feature:** Gamemode to play with arrows and space, for those who likes rhythm games like `LoveBeat`, `Audition`, `Touch Online` and similar. _Beat blocks looks a more self-descriptive name but in the format of osu gamemodes, "osu!beats", "osu!bubbles" or another will sounds good too._

1. Coube be autogenerated using the main offset or creating a specific for this mode.
2. _Rounds_ will be with single or double row of 4 _beat blocks_ (or more with mod).
3. Each _beat block_ can have a space block OR arrows to be pressed in the sequence, while that beat is being played.
4. How much faster the BPM was in that _round_, more tolerance the player need to start/end each block before consider that input as a fail.
5. Only spacebars needs to have a precision judgement. _I don't know in practice, but I suggest for the single arrow in a beat block to have the same judgement too, to improve the gameplay and more data to judge_.
6. Between rounds, it's necessary a time to player rest and be focused again. A beat countdown to warning the player, or another visual rhythmed alert, is necessary to prepare the player to the next round. *8 or 4 beats earlier maybe?*

https://user-images.githubusercontent.com/42657376/115516997-1309ce00-a25d-11eb-9d8f-56e54103eeb5.mp4

https://user-images.githubusercontent.com/42657376/115521626-b52bb500-a261-11eb-8a6d-8739240e2d7b.mp4

*_game concept being created in HTML/CSS with a more "toy style" and separed video panel to test, but obviously need to be recreated with a futuristic style_

**Proposal designs of the feature:** 
Similar visual to the osu! gamemode but with different color for each key in keyboard. Need to support more than a 4-arrows set (like `WASD`, `IJKL` or numerical pad 2469 arrows) to players be able to play fast songs with a lot of notes to press. A virtual keyboard (single or double arrows in the side down of the screen) and a spacebar at center bottom is important to be touch-friendly.

**Comment by peppy** [comment]
Thanks for the suggestion, but we don't really accept proposals for rulesets here, especially when they are not original ideas but copying other games.
