### ISSUE TITLE
Warn users to not run lazer as admin/root

### ISSUE THREAD

**Issue by adryzz** [ppy/osu#12520]
**Describe the new feature:** 
There are a LOT of users who run stable as admin thinking it improves performance/latency.
This is false, and it's just a big security risk.
Proposal: adding a warning notification if running as admin/root.
**Proposal designs of the feature:** 
Startup notification warning to not run lazer as admin/root

**Comment by peppy** [comment]
I can agree with this one. It's a very bad practice, and dialogs like UAC are largely ignored by users that think they know best.
