### ISSUE TITLE
osu! classic mod is inaccurate on some replays

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#12532]
Several replays provided in https://github.com/ppy/osu/pull/12515 and the linked issue.

**Comment by integerrr** [comment]
possibly related to #8747? classic scoring still doesn't give the correct value for hits without a backing combo from what I can see in the game

**Comment by bdach** [comment]
@integerrr That should be impossible. The PR fixing the issue you mentioned (that I wrote) has tests attached. If it broke, we'd be seeing very loud CI failures.

The "classic" scoring algorithm is not exactly 1:1 with stable. That is to be expected for now. I believe the inaccuracies mentioned are more about the actual replay playback rather than the end score itself.

**Comment by integerrr** [comment]
I did read the PR as well and saw the mentioned test, I'm not very well versed in reading/writing code so I don't really understand it all but maybe the value tested for is different to the value visible to players? 

I whipped up a quick video, I have no idea whether this is relevant at all but you can see the replay playback scores are different
https://user-images.githubusercontent.com/7279624/115971380-024ca700-a540-11eb-9b4e-4ed356558df1.mp4

**Comment by frenzibyte** [comment]
I've took a look on this [one](https://github.com/ppy/osu/pull/12515#issuecomment-823855326) and checked on combo, and found this discrepancy between "classic" mod and stable on slider input:

https://user-images.githubusercontent.com/22781491/116025640-ac6c2200-a659-11eb-8176-7ec5328e96ff.mp4

behaviour on stable:

https://user-images.githubusercontent.com/22781491/116025791-0240ca00-a65a-11eb-85b6-997584378850.mp4

It seems that slider ball can potentially be untracked when one key gets released out of two held, and I can reproduce it in `TestSceneSlider`, will look at fixing that.

**Comment by peppy** [comment]
Are you intending to fix the specifically when the classic mod is enabled, or as a core mechanic? If core mechanic, it may need some further consideration.

**Comment by frenzibyte** [comment]
Hmm yeah, I've looked through the code and it seems there's some logic for making slider ball only tracked using the key that hit the slider head circle, until there's no other keys held along:
![CleanShot 2021-04-26 at 07 08 32](https://user-images.githubusercontent.com/22781491/116027693-38804880-a65e-11eb-81d6-201d8c11db89.png)

So better to start as a classic mod thing, does osu!stable just allow any actions for tracking ball, or does it have its own logic as well?

**Comment by peppy** [comment]
Please test against a stable install to figure the logic. It will be faster than sharing or reading the code. There are only a few finite scenarios to test.

**Comment by integerrr** [comment]
https://osu.ppy.sh/scores/osu/3618817334
lazer replay at around 1:13 and 1:59 double clicked on circles, not sliders in this case

**Comment by smoogipoo** [comment]
I'm going to close this because I believe all issues have been fixed. A few things to note:

- Stable doesn't consider ticks (slider ticks or repeats) into acc% which is why the difference in https://github.com/ppy/osu/pull/12515#issuecomment-823853664 exists. Lazer's value is the more accurate one.
- Lazer doesn't have (and probably won't ever have) "slider drops" where the tail doesn't provide a combo but is also not counted as a miss.

We can open another issue if more issues are found, but at the moment this is just a zombie issue serving no purpose at a high priority.
