### ISSUE TITLE
Windows borderless position hack does not play well with some monitor layouts

### ISSUE THREAD

**Issue by Rubydesic** [ppy/osu#12535]
**Describe the bug:** When running in **Borderless** mode, the osu client appears to be running at 60fps, although the fps counter says 500+fps (and so does fraps). When running in **Fullscreen** or **Windowed** mode, the game appears to be as smooth as it should be.

Furthermore, disabling my other monitors (which are 60hz) also fixes **Borderless** mode and makes it appear as smooth as it should be. Note that the monitors weren't being used for osu, just by being enabled in Windows they cause this strange performance degradation.

This issue does not exist on the stable client.

**Screenshots or videos showing encountered issue:** n/a

**osu!lazer version:** 2021.416.0

**Logs:**

[network.log](https://github.com/ppy/osu/files/6358364/network.log)
[performance.log](https://github.com/ppy/osu/files/6358365/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6358366/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6358367/updater.log)
[database.log](https://github.com/ppy/osu/files/6358368/database.log)

**Comment by peppy** [comment]
Probably going to be graphics driver related. Please include your hardware and driver specifications.

**Comment by Rubydesic** [comment]
I'm aware of the second point and it is not applicable this case: my other monitors were empty and this issue is not present on stable osu.

I have an NVIDIA GTX 1060 3GB, and my driver version is 460.79.

**Comment by peppy** [comment]
Also do not that if _fraps_ is reporting a frame rate, that's definitely what lazer is rendering at. No questions asked.

**Comment by peppy** [comment]
Could you also attach a screenshot showing your monitor/desktop arrangement?

**Comment by Rubydesic** [comment]
I realize. This is probably the fault of Windows but I felt it was worth opening an issue for as it *is* a regression. 

My hypothesis is that the issue exists because the osu client bleeds one pixel onto my other monitor in Borderless mode, which I just realized.

Not sure what you mean by monitor/desktop arrangement but here, they are all 1080p: 
![image](https://user-images.githubusercontent.com/26909616/115722466-05cc0c80-a34d-11eb-8a9d-e78bf58e8c5b.png)

1: 60hz
2: 144hz
3: 75hz

**Comment by peppy** [comment]
Could you try moving monitor 3 to above monitor 2 and see if it helps?

**Comment by Rubydesic** [comment]
Yep, that solves the problem.

**Comment by Rubydesic** [comment]
It does not, osu stable does not have this issue.

**Comment by peppy** [comment]
@Susko3 is this still an issue? i think it has been resolved?

**Comment by Susko3** [comment]
This is still an issue. The game doesn't render on the other display with https://github.com/ppy/osu-framework/pull/5068, but the window still extends and DWM forces it to the lowest common framerate. (I don't have a way to test this, but I presume this is what happens.)

Veldrid / "compatibility mode" (https://github.com/ppy/osu-framework/issues/4909) should fix this, as it uses native DirectX fullscreen/borderless.

Another fix may be improving the borderless hack so the 1px extension avoids other displays (for this specific configuration, extending 1px to the top or bottom is amicable). This is easier said than done as explained in https://github.com/ppy/osu-framework/pull/5068.

**Comment by peppy** [comment]
I'm going to remove the priority flag on this for now as I don't believe we will be solving it before adding some implementation of directx.

For any users landing at this issue, please consider using fullscreen or windowed mode instead for the time being.

**Comment by peppy** [comment]
Closing as should-be-resolved.

Please feel free to reply in this thread if you can still reproduce an issue.
