### ISSUE TITLE
Creating a new osu! beatmap does not automatically add drum and soft samplesets

### ISSUE THREAD

**Issue by ICanNoot** [ppy/osu#12533]
I am on the stable release stream on the latest version of osu!.

I was creating a beatmap and was trying to add the drum sampleset to a few circles, only to find that when changing the sampleset from "normal" to "drum", it still played the standard normal hitsound regardless of what it said on the left. Going into the audio tab of the timing panel and trying it there did not work, either. I went into the beatmap file and saw that the hitsounds were not even inside of the beatmap folder. As far as I know, it should have been added automatically when creating a new beatmap.

The only way that I have managed to "fix" this is by copying the standard hitsounds from a different beatmap that I have downloaded off of the osu! website and placing it into my beatmap folder, and then going into the audio tab of the timing panel and adding it as a custom hitsound.

**Comment by peppy** [comment]
They come with the game. Also this is the wrong place to report stable issue. Also this is not an issue, please seek help on the help forum or wiki.
