### ISSUE TITLE
Unable to change folder location 

### ISSUE THREAD

**Issue by gregest** [ppy/osu#12540]
**Describe the bug:** 
When trying to move the folder with the ingame Change Folder Location button, it moves the folder to the selected location just fine but upon restarting the game the original osu!lazer folder regenerates itself and wipes everything I had imported

**Screenshots or videos showing encountered issue:** 
currently unable since it would take extremely long 

**osu!lazer version:** 
2021.416.0

**Comment by bdach** [comment]
Please attach logs as requested, as well as contents of `%AppData%/osu/storage.ini` (assuming this is windows, since you didn't actually even state your platform.)

**Comment by gregest** [comment]
there doesn't seem to be a storage.ini anywhere I'm looking and I looked through all my osu folders 
[database.log](https://github.com/ppy/osu/files/6361032/database.log)
[network.log](https://github.com/ppy/osu/files/6361033/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/6361034/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6361035/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6361036/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6361037/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6361038/updater.log)
[performance.log](https://github.com/ppy/osu/files/6361039/performance.log)

**Comment by bdach** [comment]
The lack of a `storage.ini` would definitely explain the issue, but to fix this an explanation why it's not there is needed.

I might have been unclear: I was asking for logs captured from a lazer run in which you attempted to change the folder location. I see no clear attempt of a migration in the attached logs.

**Comment by gregest** [comment]
alright I'm back now, took a little long because horrible HDD, now there is a storage.ini there, here is every log AFTER I did the change folder location and closed the game 
[performance-draw.log](https://github.com/ppy/osu/files/6361282/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6361283/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6361285/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6361286/updater.log)
[database.log](https://github.com/ppy/osu/files/6361287/database.log)
[network.log](https://github.com/ppy/osu/files/6361288/network.log)
[performance.log](https://github.com/ppy/osu/files/6361289/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6361290/performance-audio.log)
can't upload storage.ini since github doesn't wanna upload it but it just says 

FullPath = D:\lazer

**Comment by bdach** [comment]
That sounds like everything worked correctly. Are the files where you expect them to be and is the game reading them correctly now?

**Comment by gregest** [comment]
okay well yeah it seems like it worked perfectly this time, I don't know what else I did differently this time because I tried it like 5 times before and it always reset hence why I came here, thanks for the help

**Comment by bdach** [comment]
Closing as (mostly) resolved - not much else to do here.
