### ISSUE TITLE
Gameplay clock container does not reset correctly in single thread mode

### ISSUE THREAD

**Issue by bdach** [ppy/osu#12541]
Regressed in #12448. Opening as an issue as I am not going to make sense of this in time and it feels like a big one to fix before the next release (we'll definitely be getting lots of android reports about this otherwise).

# Reproduction steps

1. Change execution mode to single-threaded. This does *not* reproduce in multi-threaded mode.
2. Choose any beatmap from song select. For better observability of the bug, ensure that it is not seeked to the start (so any preview point in the middle of the song will do fine).
3. Enter gameplay.
4. The audio will seek back to the start correctly, but gameplay will be frozen and unresponsive. Pausing and unpausing, or waiting until the audio catches up to the progress bar at the bottom will unfreeze gameplay.

https://user-images.githubusercontent.com/20418176/115779342-28dfd600-a3b8-11eb-947c-2a148e03d64a.mp4

# Initial investigation

This seems at least tangentially relevant to the removal of the schedule in the reset procedure [as mentioned here](https://github.com/ppy/osu/pull/12448#discussion_r618634665). The following patch seems to help, although I am not PRing it as I don't entirely understand why it does so:

```diff
diff --git a/osu.Game/Screens/Play/GameplayClockContainer.cs b/osu.Game/Screens/Play/GameplayClockContainer.cs
index 5cd17d92c4..8ba3ea54b8 100644
--- a/osu.Game/Screens/Play/GameplayClockContainer.cs
+++ b/osu.Game/Screens/Play/GameplayClockContainer.cs
@@ -100,13 +100,17 @@ public virtual void Seek(double time)
         /// </summary>
         public virtual void Reset()
         {
+            ChangeSource(SourceClock);
             Seek(0);
 
             // Manually stop the source in order to not affect the IsPaused state.
             AdjustableSource.Stop();
 
-            if (!IsPaused.Value)
-                Start();
+            Schedule(() =>
+            {
+                if (!IsPaused.Value)
+                    Start();
+            });
         }
 
         /// <summary>
```

The source change is defensible, as before the seek to zero, the decoupled clock's source is not set, and therefore the seek happens in decoupled mode without it. But I cannot explain why the schedule is required. It's been there for ages before its removal in the aforementioned PR, and nothing in blame points as to why it was needed. The fact that this does not reproduce in multi-threaded mode suggests a race against the audio thread, but I have no concrete proof that this is the case.

Here's a dirty log snippet I captured while trying to make sense of all this:

```
2021-04-22 19:42:08 [verbose]: coupled = False; current @ 0.028956000000000006, proposed @ 0.028956000000000006, stopwatch @ 0.40985900000000003
2021-04-22 19:42:08 [verbose]: after a seek: gameplay clock @ 0.028956000000000006, underlying @ 0.028956000000000006, source @ 7114.852607709751
2021-04-22 19:42:08 [verbose]: trackbass updated time to 0.022675736961451247
2021-04-22 19:42:08 [verbose]: trackbass updated time to 0.022675736961451247
2021-04-22 19:42:08 [verbose]: trackbass updated time to 0.022675736961451247
(...)
2021-04-22 19:42:09 [verbose]: trackbass updated time to 212.99319727891157
2021-04-22 19:42:09 [verbose]: trackbass updated time to 222.85714285714286
2021-04-22 19:42:09 [verbose]: trackbass updated time to 226.43990929705217
2021-04-22 19:42:09 [verbose]: coupled = False; current @ 7114.852607709751, proposed @ 7114.852607709751, stopwatch @ 255.06591
2021-04-22 19:42:09 [verbose]: normal update: gameplay clock @ 7114.852607709751, underlying @ 7114.852607709751, source @ 226.43990929705217
2021-04-22 19:42:09 [verbose]: trackbass updated time to 338.09523809523813
2021-04-22 19:42:09 [verbose]: coupled = False; current @ 7114.852607709751, proposed @ 7114.852607709751, stopwatch @ 369.628973
```

My working theory is that the reset completes correctly, but then the decoupled clock is reading out the source's time too early when determining proposed time and therefore begins to operate in decoupled mode. It would make some sense that a schedule in single-threaded mode would fix that, as it would basically allow the audio thread to run the next frame before the proposed time readout happens. Then again I have no concrete proof of that, and the "fix" feels like a bad one.

**Comment by peppy** [comment]
When we switch to github actions (and can more easily run concurrent jobs) we should definitely consider running CI in both execution modes.

**Comment by bdach** [comment]
Ironically I'm not sure even that would save us here, since tests for the gameplay clock container don't seem to fail even single threaded when I tried that, unless I messed up. Likely because of use of a virtual track. There may be other real tests that would catch this - not sure, haven't checked.

**Comment by peppy** [comment]
Sounds like a missing test case we'd want to add framework side
