### ISSUE TITLE
Adding "Streamer Mode"

### ISSUE THREAD

**Issue by hxotic** [ppy/osu#12547]
Preface: an old thread from [here](https://www.reddit.com/r/osugame/comments/jk51ba/osu_and_vtubers_identities/) brings up people who would like to stream but do not want their username visible due to either privacy or identity issues (in the vtuber threads case)

**Describe the new feature:** A "Streamer Mode" where username and rank in the menu screen & local scores names get anonymized

**Proposal designs of the feature:** 
BEFORE:
![osu_2021-04-23_13-31-27](https://user-images.githubusercontent.com/26120552/115871781-e6aaa900-a438-11eb-905c-76f47f6fc8f9.jpg)
AFTER:
![osu_2021-04-23_13-31-267](https://user-images.githubusercontent.com/26120552/115871797-ead6c680-a438-11eb-82e8-68774393f404.png)

(don't mind the shit photo editing its just there so you can visualise what I'm trying to say)

**Comment by peppy** [comment]
I don't foresee this happening. We will offer privacy options to hide location etc., but not username as that is one of the core elements of osu!.

Logging out is the best solution if you do not want to share your username with an audience.
