### ISSUE TITLE
`Bind` mod doesn't submit with other mod

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#12549]
**Describe the bug:** After completed ranked map with NF,Bind mods only NF is submitted. Didn't test with single bind because I can't solo bind.

**Screenshots or videos showing encountered issue:** 
Score on profile page.
![image](https://user-images.githubusercontent.com/7066150/115878360-a831e000-a472-11eb-9f0b-0c37d7cbe269.png)
Local result screen.
![image](https://user-images.githubusercontent.com/7066150/115878328-a1a36880-a472-11eb-910e-2859dc06326f.png)

**osu!lazer version:** 2021.416.0

**Logs:**
[performance-audio.log](https://github.com/ppy/osu/files/6365634/performance-audio.log),[performance-draw.log](https://github.com/ppy/osu/files/6365635/performance-draw.log),[performance-update.log](https://github.com/ppy/osu/files/6365637/performance-update.log),[runtime.log](https://github.com/ppy/osu/files/6365638/runtime.log),[updater.log](https://github.com/ppy/osu/files/6365640/updater.log),[database.log](https://github.com/ppy/osu/files/6365631/database.log),[network.log](https://github.com/ppy/osu/files/6365632/network.log),[performance.log](https://github.com/ppy/osu/files/6365633/performance.log)

**Comment by peppy** [comment]
The score is sent correctly. Server-side support for the new mods is not quite there yet.

**Comment by Contextualist** [comment]
Not sure if this is related, but `Relax` mod is also not displayed in Recent Plays (while `AutoPilot` is):

![截屏2021-04-24 20 46 55](https://user-images.githubusercontent.com/16000021/115976776-720e6200-a53f-11eb-8efa-a3f1de06071b.png)

osu!lazer version: 2021.424.0
