### ISSUE TITLE
Sliderends don't expand after 2021.424.0 release

### ISSUE THREAD

**Issue by maotovisk** [ppy/osu#12556]
**Describe the bug:** As title says, sliderends don't reproduce the expand animation after the 2021.0424.1 release. It is probably due to the new editor-hitanimation implementation as it refactors some parts of the `DrawableHitCircle` class.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/20617307/115952338-b5bf8800-a4bb-11eb-9641-db21531940c8.mp4

**osu!lazer version:** 2021.424.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6369219/database.log)
[network.log](https://github.com/ppy/osu/files/6369220/network.log)
[performance.log](https://github.com/ppy/osu/files/6369221/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6369222/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6369223/updater.log)

**Comment by frenzibyte** [comment]
Was a bit unsure from the video you linked so I double-checked myself on visual tests, and seems it does actually not expand on both modern (osu!lazer default skin) and legacy skins, after the hit animations PR:

before #12519:

https://user-images.githubusercontent.com/22781491/116012357-b169ab00-a632-11eb-9d73-a52ab7999cc6.mp4

after #12519:

https://user-images.githubusercontent.com/22781491/116012355-af9fe780-a632-11eb-9fc4-70c138ed6fae.mp4
