### ISSUE TITLE
Not being able to lauch in Ubuntu 21.04

### ISSUE THREAD

**Issue by ItzJaum** [ppy/osu#12550]
Can't launch the AppImage on Ubuntu 21.04, I only get this when running from the terminal:
```
$ ./osu.AppImage 
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  98
  Current serial number in output stream:  99

```
I'm using Xorg since Wayland doesn't work well with nvidia, but I don't think that's the issue since it used to work well with Xorg on Ubuntu 18.04

**Comment by smoogipoo** [comment]
This is an issue with your system. Perhaps you don’t have the correct drivers installed. The same should occur if you try to run glxgears or glxinfo.

**Comment by ItzJaum** [comment]
Thank you so much for this insight.
I've found out that the Nvidia drivers on Linux don't play nicely with my discrete gpu.
For anyone else having this issue: go to Nvidia X Server settings and change it to adaptive performance mode
Sorry for any inconveniece
