### ISSUE TITLE
Showing log overlay even during a gameplay

### ISSUE THREAD

**Issue by Nekomosh004** [ppy/osu#12567]
**Describe the bug:** 
What happened here is, I tried importing all scores that I have from stable to lazer. However, since I don't have all my beatmaps imported this happened. I'm not sure if this is intentional and I'm aware I can disable this in the settings. Just a suggestion, to have these messages auto-disabled or limit the messages to one (like how "Chat Ticker" works in stable) or two lines during a gameplay.

Thank you for reading!

**Screenshots or videos showing encountered issue:** 
![osu_2021-04-25_05-26-20](https://user-images.githubusercontent.com/82471957/115973462-bf162680-a587-11eb-836c-3c9e590a171e.jpg)

**osu!lazer version:** 
2021.424.0

**Comment by smoogipoo** [comment]
This is intentional.
