### ISSUE TITLE
ingame tablet input overrides global tablet input

### ISSUE THREAD

**Issue by ethannij** [ppy/osu#12561]
With the integration of OTD into lazer I can no longer use my preferred tablet driver. When in the menus and stable, any tablet driver I use (libwacom, OTD) register perfectly. In lazer enabling the tablet setting overrides my global tablet input (i have to disable libwacom and it takes priority over OTD). If the setting is disabled, I am unable to move the cursor with the tablet ingame (though it works in the menus).
A video of the described bug can be found [here](https://streamable.com/5d2qe0)

osu!lazer version: 2021.424.0
OS: Gentoo Linux (5.10.26 custom kernel)
OTD version: 0.5.2.3

[database.log](https://github.com/ppy/osu/files/6369378/database.log)
[network.log](https://github.com/ppy/osu/files/6369379/network.log)
[performance.log](https://github.com/ppy/osu/files/6369380/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6369381/runtime.log)

**Comment by peppy** [comment]
osu! already lets you use external tablet drivers if you want. you may need to turn off  "high precision cursor" to make your wacom software work for now.

**Comment by bdach** [comment]
Also note that because of the extremely niche setup (linux with custom kernel and custom drivers) we are not able to debug why this is not the case without much hassle, and we cannot easily support such configurations. You would need to do some investigation yourself if disabling high precision does not help.

**Comment by ethannij** [comment]
Thanks for the reply. As you suggested disabling high percision mouse solved the issue.

**Comment by tuxutku** [comment]
disabling high precision mouse solved my problem too. But I think it should be disabled by default on linux for now. Also osu still complains even after setting is disabled
