### ISSUE TITLE
Song select crash with tilde key

### ISSUE THREAD

**Issue by xzCobra** [ppy/osu#12566]
**Describe the crash:** 
Entering song select and hitting the tilde (`/~) key and escape at the same time causes errors on click, eventually crashing.
(sorry if dupe btw, didnt find any other issues related to this)

**Screenshots or videos showing encountered issue:** 
[Streamable](https://streamable.com/kem7mj)

**osu!lazer version:** 
2021.424.0

**Logs:**
[runtime.log](https://pastebin.com/sRvdEmub)

**Comment by bdach** [comment]
This is actually a duplicate of #11511 - the same assertion is being tripped. I couldn't find the issue myself for a good five minutes, though, so I'll rename it for better tracking.

**Comment by frenzibyte** [comment]
Technically duplicate of https://github.com/ppy/osu/issues/11511
