### ISSUE TITLE
Remake rotate buttons

### ISSUE THREAD

**Issue by LemonJuicer** [ppy/osu#12563]
![image](https://user-images.githubusercontent.com/64481039/115960648-f0a0da80-a512-11eb-9c14-47c8cd8b8524.png)
Make them smaller and add offset. Maybe add borders.

**Comment by bdach** [comment]
What is "offset" supposed to mean? What's the point of "borders"?

If you are going to be suggesting such changes at least to provide reasoning.

**Comment by peppy** [comment]
Settings UI is all temporary until it gets a design pass. This kind of issue is unnecessary.
