### ISSUE TITLE
on iPad enables stop the game or retry the game by double tapping the side of the apple pencil

### ISSUE THREAD

**Issue by marsman233** [ppy/osu#12575]
**Describe the new feature:** 
on iPad enables stop the game or retry the game by double tapping the side of the apple pencil
**Proposal designs of the feature:** 
to make it easier to restart or pause the game

**Comment by frenzibyte** [comment]
Actually was going to close this as a duplicate of https://github.com/ppy/osu-framework/issues/2918, but it seems that framework-side issue is requesting the double-tap for right-clicking, while this is requesting double-tap for binding to certain game actions. 

Not sure what to do with these issues, but reboundable better than fixed to right-clicking imo?

**Comment by frenzibyte** [comment]
Don't close this yet.

**Comment by peppy** [comment]
the solution is adding binding support, yes.
