### ISSUE TITLE
on ipad multithread mode will cause lag and frame lost in background video and playing

### ISSUE THREAD

**Issue by marsman233** [ppy/osu#12576]
**Describe the bug:** 
on ipad multithread mode will cause lag and frame lost in background video and playing
**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/25430781/116015674-b0ee0600-a66c-11eb-8c7c-9168e7eb5d1f.mp4
this is just about the problem of background video
**osu!lazer version:** 
2020.312.0
**Logs:**
not recorded

**Comment by peppy** [comment]
then don't turn it in please. single threaded execution is a default on mobile for a reason (it will provide the best performance/.
