### ISSUE TITLE
Lazer click latency is consistently 6ms greater than stable

### ISSUE THREAD

**Issue by tomvernon** [ppy/osu#12597]
When trying out Lazer yesterday, I felt like the click latency was a bit more than stable. So I decided to test using audacity and measuring difference in keyboard sounds and hitsounds.

I found stable was 35ms, and Lazer was 41ms. 

I'm running on realtek drivers from the motherboard with REAL running and nvidia low latency on "ultra" in control panel.

Apologies if it's a bit insignificant, but any extra latency is undesired latency :)

Lazer version is 2021.424.0

**Comment by peppy** [comment]
Please attach all your testing methodology, without external programs like REAL running and we will reconsider this issue. Also please follow the template.

**Comment by tomvernon** [comment]
realised with further testing that there is a bit of variance in the latency too. I'll do as you guys said and get some more data together while I'm at it

**Comment by tomvernon** [comment]
I was right with the variance. Did some more tests with more data and although one could conclude that lazer has a few ms less click latency than stable, it's too close to be certain. Looks like it was just me being silly. Sorry for wasting your time. Keep up the good work :) 

Testing method:
1) start recording in audacity, place microphone next to headphones and mouse
2) play offset calculator map with music set to 0%
3) measure difference in mouse click and hit sound in audacity for 10 clicks

These are the results:
<img width="728" alt="osu latency tests" src="https://user-images.githubusercontent.com/33759811/116252562-98aee180-a767-11eb-9784-80cea96bc6f5.png">
