### ISSUE TITLE
Multiplayer scores are not forced to one scoring mode

### ISSUE THREAD

**Issue by takoz53** [ppy/osu#12591]
**Describe the bug:** 
As described in title, endresult scores are different to each player. Problem occurs with any mod combination. Recreatable by opening a multi lobby and playing.
**Screenshots or videos showing encountered issue:** 
[Img1](https://cdn.discordapp.com/attachments/834203507916800041/836458436526997544/osu_Screenshot_2021.04.27_-_00.26.51.30.png) 500k and 300k
[Img2](https://cdn.discordapp.com/attachments/834203507916800041/836458342846562314/osu_2021-04-27_06-26-31.jpg) 1mil and 500k

Those images are both the same map.
**osu!lazer version:** 2021.424.0

**Comment by frenzibyte** [comment]
Sounds like different scoring modes selected? can you confirm both you and the other user use the same scoring mode? haven't checked yet if osu!lazer forces to one on multiplayer results.

**Comment by takoz53** [comment]
> Sounds like different scoring modes selected? can you confirm both you and the other user use the same scoring mode? haven't checked yet if osu!lazer forces to one on multiplayer results.

That's what I thought too, but only the host selects the mods, so it should be the same I believe.

**Comment by frenzibyte** [comment]
no check the game settings, there's a setting for switching scoring modes between "standardised" and "classic" (*roughly* matches stable).

**Comment by takoz53** [comment]
Oh! I guess that's it.

**Comment by smoogipoo** [comment]
Multiplayer shouldn't be forced to one scoring mode. Please make a separate issue for scores being displayed twice.
