### ISSUE TITLE
Importing from stable not working on linux

### ISSUE THREAD

**Issue by LinuxOsuGamer** [ppy/osu#12599]
**Describe the bug:** 
On my linux installation of osu!lazer going into settings and trying to import beatmaps, scores, skins or collections from stable opens a prompt stating "No osu!stable installation available!" I have previously used osu!stable on linux using wine and would love to be able to import my beatmaps into osu!lazer. I'm running Manjaro KDE Plasma 21.0.2 .
**Screenshots or videos showing encountered issue:** 
![Screenshot_20210427_171702](https://user-images.githubusercontent.com/83295589/116267442-f1807900-a76b-11eb-8a98-32e0cd66bbb0.png)

**osu!lazer version:** 
2021.424.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6385685/database.log)
[runtime.log](https://github.com/ppy/osu/files/6385687/runtime.log)
[network.log](https://github.com/ppy/osu/files/6385688/network.log)
[performance.log](https://github.com/ppy/osu/files/6385690/performance.log)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues?q=is%3Aissue+stable+import+linux+is%3Aclosed+
