### ISSUE TITLE
Pull in all the colors into some class

### ISSUE THREAD

**Issue by SirCmpwn** [ppy/osu#126]
Eventually we'll probably let the user override them with skins

**Comment by SirCmpwn** [comment]
Bump

**Comment by Tom94** [comment]
We want more than just the colours to be customizable via skins. It's probably worth it to consider everything that may be customizable, and settle on a solution that is not specific to colours.

What I had in mind was that every class implementing a UI component (e.g. the wedged beatmap info) could get passed in skinned information (e.g. via reflection similar to DI, potentially even using the DI machinery itself) and handle applying the parameters (including colours, position, shape) itself. This would also nicely extend to hit objects.
