### ISSUE TITLE
Confined cursor glitches on dwm

### ISSUE THREAD

**Issue by orangixx** [ppy/osu#12607]
**Describe the bug:** 
dwm with "Confine mouse cursor to window" can cause the cursor to teleport/flicker.

**Screenshots or videos showing encountered issue:**
I'm too lazy to take a video so this looks like #12593 ([included video](https://streamable.com/bxkjh7)) but (when in windowed mode) on the dwm bar as well as borders between 2 monitors.

**osu!lazer version:** 
2021.424.0 (AUR osu-lazer-bin)

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.
