### ISSUE TITLE
Gameplay feels rough when in fullscreen mode, but runs smoothly when switching from windowed to fullscreen

### ISSUE THREAD

**Issue by Modsnotworking** [ppy/osu#12600]
**Describe the bug:** The gameplay feels rough when playing in fullscreen mode, but feels much better/smooth when switching from widowed to fullscreen. 

**Screenshots or videos showing encountered issue:** My pc has 4gb RAM and recording osu!lazer increases the amount of load thus recording slows down the game by a lot. that's why I don't have any video recorded for this issue.

**osu!lazer version:** 2021.424.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6385745/performance.log)
[database.log](https://github.com/ppy/osu/files/6385755/database.log)

**Comment by Modsnotworking** [comment]
sorry for not giving video/screenshot. and I know that screenshot or video is necessary as it's explains the issue more easily

**Comment by peppy** [comment]
If it feels better in windowed mode the please play windowed!

**Comment by Modsnotworking** [comment]
But I want to play in fullscreen mode

**Comment by peppy** [comment]
You're going to need to play with your graphic driver settings for now. We have a few bug fixes ongoing for multiple monitors, but if that doesn't apply to you then it's likely something your end.

This is a forum for development and not technical support. Your request does not look like a bug report and is not actionable from our end.
