### ISSUE TITLE
Canceling import after beatmap is finished downloading makes the button stuck

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#12606]
**Describe the bug:** I need this to be fixed before fixing https://github.com/ppy/osu/pull/12564. I'm not well-versed in the downloading state code so I'm making an issue.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/35318437/116330460-71194280-a782-11eb-8afe-d09006ef8f2a.mp4

**osu!lazer version:** 2021.424.0

**Comment by frenzibyte** [comment]
I was thinking https://github.com/ppy/osu/pull/12564 just need adding a download button if it isn't already, unless it's something else that depends on this?

**Comment by Joehuu** [comment]
This is for the edge case mentioned in that PR, can't do anything if the internal state is wrong/stuck in the first place.
