### ISSUE TITLE
Unused old version resources are not removed after updating from in-game updater

### ISSUE THREAD

**Issue by Rian8337** [ppy/osu#12601]
**Describe the bug:** 
After updating the game via in-game updater, the game doesn't delete old version resources, which takes a moderate amount of storage space. While this doesn't seem to matter for the majority of users, it is a problem for users with low storage space.

I don't see any option to rollback to previous version both in client and game directory, therefore I don't see any point of keeping these files.

I have tried to run the game after moving those old resources into recycle bin. It worked normally.

**Screenshots or videos showing encountered issue:** 
(this is under `AppData\Local` directory)
![image](https://user-images.githubusercontent.com/52914632/116278368-a0df3f00-a7b0-11eb-93f8-abb9dd551ecc.png)

**osu!lazer version:** 
2020.424.0

**System specifications**:
OS: Windows 10 Home OS Build 19042.928
Device: Surface Pro 6 (complete specifications can be found [here](https://www.microsoft.com/en-us/surface/devices/surface-pro-6)

**Logs:**
(I don't think this will give any information since I updated the game 3 days prior to this issue, but here)
[network.log](https://github.com/ppy/osu/files/6386165/network.log)
[performance.log](https://github.com/ppy/osu/files/6386166/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6386167/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6386168/updater.log)
[database.log](https://github.com/ppy/osu/files/6386170/database.log)

**Comment by Game4all** [comment]
This is an issue with the the Squirrel framework (which lazer uses for updating the game) which as far as I'm aware will always keep around two copies of the software: the current version and the last previous version. I'm not sure something this is actionnable on osu! side unfortunately ...

**Comment by smoogipoo** [comment]
We'll probably move away from squirrel at some point anyway. Safe to close for the time being.

**Comment by Rian8337** [comment]
Good to know, thank you.

**Comment by peppy** [comment]
Even if moving away we will likely keep two copies. This is to allow for recovery if there's any issue.
