### ISSUE TITLE
Dynamic Collection

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#12616]
**Describe the new feature:** 

> Allow collection to have "tags" that will add beatmaps with the correct tag into the collection automatically. This should make collection organization much easier

**Proposal designs of the feature:** 

> Allow player to add tags for a collection, check and add beatmaps into the collection when a new beatmap detected

**Comment by peppy** [comment]
Duplicate of https://github.com/ppy/osu/issues/4071. Please search first.
