### ISSUE TITLE
Unhandled error when spam opening/closing beatmap set overlay

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#12631]
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/35318437/116621802-992ab200-a8f8-11eb-9389-4ef5437c0f74.mp4

**osu!lazer version:** 2021.424.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6401765/runtime.log)

**Comment by frenzibyte** [comment]
This will be resolved by https://github.com/ppy/osu/pull/11582, was a bug with the way `BeatmapSetCover` was written and refactoring it to use `ModelBackedDrawable` cleaned things up and fixed it.

**Comment by peppy** [comment]
;
