### ISSUE TITLE
Unplugging headphones and plugging them back in breaks audio

### ISSUE THREAD

**Issue by K4ktus123** [ppy/osu#12638]
**Describe the bug:** 
If I start the game with headphones plugged in and then unplug them, the sound output, as expected, switches to built-in speakers (I'm on a laptop). But when I plug the headphones back in, I get no sound through them until I close the game and re-open it. This seems to only occur on Windows, I couldn't reproduce this on Linux.

**osu!lazer version:** 
2021.424.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6407405/runtime.log)
[performance.log](https://github.com/ppy/osu/files/6407407/performance.log)
[database.log](https://github.com/ppy/osu/files/6407408/database.log)
[updater.log](https://github.com/ppy/osu/files/6407409/updater.log)

**Comment by K4ktus123** [comment]
When I do this, the other program (Chrome tab) switches back to headphones as expected, and the game behaves just like I described above.

**Comment by bdach** [comment]
Okay, thanks. Mind showing a video of this (I guess without audio is fine as it's already been described what happens)? I'd especially be interested in how the "Audio device" dropdown in settings behaves when the switch happens. A `dxdiag` report to list your audio devices might be handy, too?

The log shows multiple instances of the BASS initialisation header, so it looks like the device switch was detected somehow, but I'm not sure as to why sound output wouldn't get switched onto it.

**Comment by K4ktus123** [comment]
Here's the video. I started the game with headphones connected, I unplug them at 0:12 and re-connect them at 0:23.

https://user-images.githubusercontent.com/55000815/116777071-8c2ecf80-aa6c-11eb-95bc-aba382678ed2.mp4

And a DxDiag report regarding sound devices:
[DxDiag_sound.txt](https://github.com/ppy/osu/files/6409264/DxDiag_sound.txt)

**Comment by peppy** [comment]
@K4ktus123 if you manually select the reconnected device from the dropdown does it recover? You may need to select an alternative device first to make sure it actually toggles to a different device.

**Comment by K4ktus123** [comment]
No, it does not recover. If I select speakers, the sound plays through speakers as expected, but when I select headphones there is no sound coming through them.
