### ISSUE TITLE
Dynamic area demo size depending on angle

### ISSUE THREAD

**Issue by LemonJuicer** [ppy/osu#12647]
![image](https://user-images.githubusercontent.com/64481039/116792867-a942bd00-aac3-11eb-8738-03261cbd86d0.png)
As you can see tablet demo can be bigger here.

![image](https://user-images.githubusercontent.com/64481039/116792896-c8d9e580-aac3-11eb-8f3d-3dc0eca5ea9b.png)
Here it needs to be smaller to fit, but not as small as it is now.

Can you make it so it changes size dynamically depending on angle so there will be certain margin left from the edges?

**Comment by bdach** [comment]
I have no idea what this is asking for.

**Comment by smoogipoo** [comment]
From the looks of it, they’re saying the display can fit closer to the edges of the settings area, with the large paddings removed.

But no, this will happen with a design refresh.
