### ISSUE TITLE
Colour shifting approach circle mod 

### ISSUE THREAD

**Issue by mk56-spn** [ppy/osu#12645]
(I'm rather new to this sorry if I mess up the request format slightly)

The idea is rather simple  but id say rather intruiging aswell (may have come up before but  i googled and checked git as best as i could to no avail) .

So basically the approach circles (only the actual circle part there would be no circumference closing  in in this concept since it would serve no purpose)  would (or a designated part of them depending on the skin )  start off as a color A ( lets say red  as an example ) the second the circle becomes visible (would depend on the AR obviously and in this sense be no different to traditional approach circles) and end  on another colour B at  the exact moment at which you are meant to click the circle (the transition between these two colours would be the color gradient ) here is an illustration to clarify what I mean :
![heatwave](https://user-images.githubusercontent.com/74463310/116791448-b313f280-aaba-11eb-8f94-734810538250.png)

As to why I think this would be of interest: 
It would offer a different approach to reading without being inherently easier or harder than normal reading (atleast not objectively speaking ) except with hidden which it would nerf as it gives additional info on when to hit which isnt the case for no mod since its simply replacing the circumferences  (and therefore this could be allowed on ranked scores which I dont see why it wouldn't be but thats not relevant to the scope of this proposal) .

As for a proposed name : "Heatwave", simple and I feel it gets the point across pretty well once you see what it does.

Unfortunately I dont know how easy or difficult this would be to implement since my only coding experience is with web programming. that said it doesn't seem like a monumental task.

**Comment by FrameMuse** [comment]
I think it shouldn't be in game by default, but could be possiblly added by a skin change, like customizable skin or just a setting.

**Comment by frenzibyte** [comment]
I would disagree with that, especially since this is changing the way you play the ruleset and is *potentially* increasing the difficulty.

I don't see the problem with having it as a fun mod? or even a difficulty increase mod if decided.
