### ISSUE TITLE
Raw Input support needed for Mac

### ISSUE THREAD

**Issue by ReNForce72** [ppy/osu#12642]
**Describe the new feature:** 
1:1 movement between the mouse and the cursor. From what I understand, the High Precision Cursor feature was added because there were some issues with the Raw Input mechanic, but the high precision cursor just doesn't cut it once you reach 5-star maps and beyond. 
If I go and play the browser-based version of this game (https://osugame.online/index.html), there's no issue with the raw input feature, so I'm sure there's a way to make it work. The game just feels really sluggish and unresponsive right now.
**Proposal designs of the feature:**

**Comment by sr229** [comment]
High Precision exists on all platforms, even in macOS. This is just a renaming of "Raw Input" from stable. This is more of a bug report regarding performance rather than a feature request, and you have not provided logs as well as to why the game feels sluggish on your device so it's not possible to help you with this issue.

**Comment by peppy** [comment]
Yep, this sounds like nothing to do with input, and more to do with performance.

Also a couple of misconceptions: "high precision" mode on macOS does *not* remove system acceleration. That's something we haven't added back due to supporting it on macOS being hard/not possible. There's no way a browser game is managing this, either.

**Comment by ReNForce72** [comment]
> Yep, this sounds like nothing to do with input, and more to do with performance.
> 
> Also a couple of misconceptions: "high precision" mode on macOS does _not_ remove system acceleration. That's something we haven't added back due to supporting it on macOS being hard/not possible. There's no way a browser game is managing this, either.

Correct, I'm using another program called SteerMouse to bypass mouse accel. Could that possibly be part of the issue? I would imagine that since it's a third-party app, there may be some compatibility issues.

**Comment by frenzibyte** [comment]
Can't you check that out yourself?

**Comment by ReNForce72** [comment]
I mean, I tried running the app with SteerMouse disabled, and the mouse acceleration was definitely back, but that made it difficult to tell whether there was any latency. My thought is that because it's the macOS communicating with a third party program designed for Mac, but not for Osu Lazer, there could be a delay between Steermouse and the game; a delay that isn't present with Mac, since SteerMouse was made specifically for Mac.

**Comment by ReNForce72** [comment]
I'm going to try and bypass mouse accel on Mac through the terminal. I won't have my optimal sensitivity, but it should give me enough info to figure out whether the latency is entirely performance-based, or if it's from the 3rd party software.

**Comment by ReNForce72** [comment]
Alright, I'm pretty sure now it's performance. Though I just don't see how an unofficial browser version is able to outperform an official game client.
For that reason though, if you ever were thinking about eventually, in the future, building a browser version of Lazer to extend your user base, that's something to consider.

**Comment by ReNForce72** [comment]
> High Precision exists on all platforms, even in macOS. This is just a renaming of "Raw Input" from stable. This is more of a bug report regarding performance rather than a feature request, and you have not provided logs as well as to why the game feels sluggish on your device so it's not possible to help you with this issue.
> 
> And no, there is no "Raw Input" in browsers, as providing such access would defeat the security of these browsers.
http://osugame.online/settings.html
You sure about that?
![Screen Shot 2021-05-02 at 5 39 48 PM](https://user-images.githubusercontent.com/83483901/116830094-705f2280-ab6d-11eb-9e6c-38c4856c7e02.png)

**Comment by frenzibyte** [comment]
> Alright, I'm pretty sure now it's performance. Though I just don't see how an unofficial browser version is able to outperform an official game client.
> For that reason though, if you ever were thinking about eventually, in the future, building a browser version of Lazer to extend your user base, that's something to consider.

Depends on how much the "browser" version you're playing on uses GPU, sure osu!lazer still needs a bit of optimization in terms of drawing to perform better, but you don't just arbitrarily compare and question why that performs better than osu!lazer, and even suggest building a browser version of the game (which I'm pretty sure will just be a way too worse experience to even consider). 

Closing as not an input issue.
