### ISSUE TITLE
osu lazer error occurs when launching

### ISSUE THREAD

**Issue by slenshortman** [ppy/osu#12643]
**Describe the bug:** 
When I want to launch osu!lazer, it will occur an error to stop the application itself. I was using a windows 10 in 64 bit so I am pretty sure is not about 32 bits. It seems that the application has appeared on task manager but it just doesn't launch.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/_TDlO-j9XGM

**osu!lazer version:**
 2021.424.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6408983/runtime.log)

**Comment by frenzibyte** [comment]
Your database file has been corrupted, please delete it from your game data folder (should be `%appdata%/osu/client.db` or wherever you set your game data folder to) for now and reimport all your data from osu!stable, it'll be resolved by switching to a better database backend.
