### ISSUE TITLE
osu opening then crashing the second its launched

### ISSUE THREAD

**Issue by wilylosu** [ppy/osu#12640]
so basically i installed 'install.exe' and ran it and it immediately crashed the second i launched it.
something i did discover was it crashes when i interact or am on tab of osu!lazer, i i were to open osu!lazer then click on the chrome window osulazer would start correctly and not crash, but the second i interact/go on the osu!lazer tab it crashes. Any help with this?

**Comment by integerrr** [comment]
Please follow the bug report template and include all the relevant information that is required by the team.
What version is this? Any logs? Steps to reproduce the crash?

**Comment by frenzibyte** [comment]
As above, please fill the [bug report issue template](https://github.com/ppy/osu/issues/new?assignees=&labels=&template=01-bug-issues.md) rather than completely deleting it and think your issue will be acted upon.

**Comment by wilylosu** [comment]
latest version

**Comment by bdach** [comment]
Likely duplicate of #6391. Try updating graphics card drivers.

And please, if you're going to be opening issues, put in some effort. Your latest comment is unhelpful - you've provided just one piece of information from however many requested above.
