### ISSUE TITLE
Sample Points randomly disappearing

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu#12648]
**Describe the bug:** 
Sometimes, after exiting the editor, sample points will just... vanish. (Sometimes, sample points also have no effect). 

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/25379179/116793405-96fd5a80-aa94-11eb-81f6-78e18cdbf501.mp4

**osu!lazer version:** 
2021.424.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6410193/database.log)
[network.log](https://github.com/ppy/osu/files/6410194/network.log)
[performance.log](https://github.com/ppy/osu/files/6410195/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6410196/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6410197/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6410198/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6410199/runtime.log)

**Comment by peppy** [comment]
Can you confirm you manually saved before exiting? Currently, not all changes to the beatmap trigger a "dirty" state so the editor may not prompt to save (tracking at #10314)

**Comment by AndyThePie** [comment]
I've tried doing this a few times, and I'm pretty sure I've manually saved (clicked "Save", pressed `Ctrl` + `S`) and the same outcome - some random sample points go missing. 
This also sometimes includes points that I didn't interact with.

**Comment by peppy** [comment]
@AndyThePie when you said "sometimes sample points have no effect": are you implying that existing sample points are not adjusting the volume after loading a beatmap into the editor? Or is it more like new points that you are adding have no effect?

**Comment by AndyThePie** [comment]
> @AndyThePie when you said "sometimes sample points have no effect": are you implying that existing sample points are not adjusting the volume after loading a beatmap into the editor? Or is it more like new points that you are adding have no effect?

Sorry for the vagueness — I'm referring to new points I'm adding that don't have effect. I'll try and attach a video that shows this when I get time.

**Comment by nolife99** [comment]
I looked into this issue a bit and it seems like adding a sample timing point with a large amount of samples already existing will delete the newly added ones along with some or even all of the existing ones. I tried this with https://osu.ppy.sh/s/1054045 and it deleted all of them except for very few. 
This seems to only affect samples; it will disable the sample but leave other options such as difficulty and the BPM the same.

**Comment by peppy** [comment]
Going to bump up the priority of this as it seems from the outside like a pretty critical issue. Hopefully will get to it this week if no one beats me.

**Comment by peppy** [comment]
As mentioned in #14211, the difficulty point you are adding in the video is redundant. It is therefore removed.

One could argue that these "redundant" control points should still be displayed in the editor as they may have been added for future use. But given the direction we are going with control points (ie. they will be attached to hit objects), I don't foresee this changing.

Phrased another way: if you want the new sample points you add to stick, make sure they are actually changing something relative to the one before them. If they aren't, they will be removed.
