### ISSUE TITLE
Logging in/Tapping Profile will freeze my phone

### ISSUE THREAD

**Issue by kurokoro** [ppy/osu#12655]
after logging in my account on lazer the game eventually freeze. And if I reopen it again, my account successfully logged in but, if I tap the Profile (at the upper right) it freeze again.

logs:

[database.log](https://github.com/ppy/osu/files/6410958/database.log)
[network.log](https://github.com/ppy/osu/files/6410959/network.log)
[performance.log](https://github.com/ppy/osu/files/6410961/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6410962/runtime.log)

**Comment by frenzibyte** [comment]
Looks to be an issue at Humanizer-level (https://github.com/Humanizr/Humanizer/issues/1059), with a workaround specifiying to use an older Humanizer version `2.8.26`.
