### ISSUE TITLE
Multiplayer - Game Freeze

### ISSUE THREAD

**Issue by Styxrich** [ppy/osu#12654]
**Describe the bug:** 
When I press on the multiplayer for Andriod, the game just freeze,no way to go back to the home page,only can exit the app and enter back but multiplayer still freeze.
**Screenshots or videos showing encountered issue:** 
![Screenshot_2021-05-02-15-12-06-78_25a1a32208bbcdc1d450b7aa854bb161](https://user-images.githubusercontent.com/75202959/116805375-d1303000-ab58-11eb-9edd-bceb568cebac.jpg)

**osu!lazer version:** 
2021.502.0
**Logs:**

**Comment by frenzibyte** [comment]
Logs.

**Comment by Styxrich** [comment]
Idk how get logs, theres no logs in my file

**Comment by frenzibyte** [comment]
Are you sure? have you checked the attached path `Android/data/sh.ppy.osulazer/files/logs`? 

This is not actionable in any way possible without another one reproducing this issue and providing the logs.

**Comment by Styxrich** [comment]
Every mobile users are experiencing this issue, not only me after this
update so if it's possible, you should have the log file.

**Comment by frenzibyte** [comment]
I can't test myself so I would appreciate if anyone could confirm this and pass the logs. Can you confirm whether tapping on your profile and going to the user profile overlay works fine for you?

**Comment by Styxrich** [comment]
It also freeze my game

**Comment by peppy** [comment]
Please use the previous build or wait for a reupload with fix applied.
