### ISSUE TITLE
Replay frames should use stable sort algorithm

### ISSUE THREAD

**Issue by integerrr** [ppy/osu#12651]
**Describe the bug:** 
Not sure if this should be opened seeing as #12532 is already tracking inaccuracy involved with classic mod, but I did find that the replays are still inaccurate even when classic mod wasn't applied/used.

The issue that I've came across was that the replay was "double tapping" at seemingly random places, there doesn't seem to be a pattern to this "double tapping" but the issue is consistent and repeatable on isolated replays. 

-----

**Screenshots or videos showing encountered issue:** 

1. https://youtu.be/2hcOwZDtfoQ 

This is one of the better examples I can put on tape as all my other replays are mostly littered with inaccurate play by myself to begin with which will probably make it very difficult for you to pick out the actual issue, but unfortunately **there's only 1 "double tap" in the entire replay which happens on the stream after _1:27_ in the video.** As you can see the older game version which this score was set on (2021.331.0) can accurately replay the score.

I am also attaching the replay in question so you can investigate it deeper if desired
[Integer playing Feint - Tower Of Heaven (You Are Slaves) (eLy) [Extra].osr.zip](https://github.com/ppy/osu/files/6410583/Integer.playing.Feint.-.Tower.Of.Heaven.You.Are.Slaves.eLy.Extra.osr.zip)

-----

2. https://youtu.be/sPdfN7SpVds 

This I already mentioned in #12532 but I'll leave the clip here as I don't really want to ping everyone again with another comment. Look for 1:20 and 2:05 in the video, note that this score is SS

**osu!lazer version:** 2021.424.0

**Logs:**
I deleted the logs folder, played the 1st replay mentioned, then quitted the game 
[network.log](https://github.com/ppy/osu/files/6410591/network.log)
[performance.log](https://github.com/ppy/osu/files/6410592/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6410593/runtime.log)

**Comment by frenzibyte** [comment]
I don't understand, is this reporting issues of discrepancies between scores with classic mod and without classic mod?

**Comment by integerrr** [comment]
No I'm reporting how replaying scores that don't have classic mod are still inaccurate

**Comment by frenzibyte** [comment]
Huh? The point of classic mod is to simulate osu!stable's behaviour so that playing a replay of legacy scores will give mostly the same results as in osu!stable, without classic mod, there's no surprise you'll see inaccuracies.

**Comment by integerrr** [comment]
No the first replay was actually set on lazer, that wasn't a "legacy" score

**Comment by frenzibyte** [comment]
OK let me reiterate, this has nothing to do with classic mod or osu!stable scores, and it's all about an inaccuracy on a score that was set on osu!lazer of an old version (2021.416.0), is that right?

**Comment by integerrr** [comment]
I have
- 1 lazer score that was set on an older version of lazer without classic mod (replay 1)
- 1 osu!stable score (replay 2)
- 1 lazer score that was set on 2021.424.0 that has classic mod turned on, didn't mention this in post I didn't see a need to

All 3 are inaccurate (has double tapping)

I hope this makes more sense

**Comment by frenzibyte** [comment]
I still don't fully understand this, to be honest, and why "classic mod" is even mentioned at all, but I'll look on the first replay and figure it out myself.

**Comment by integerrr** [comment]
I didn't want to say "all replays with all mod combinations are affected by double tapping" because I didn't test for it, the list I gave in my last comment were the ones  I happened to came across. If it makes this more understandable then I think all replays are affected by this

**Comment by frenzibyte** [comment]
I understand the issue now, simply both keys are pressed at once when only one should be pressed in the original play, is that right? and is that the same for the other score you attached?

**Comment by frenzibyte** [comment]
The "double tapping" bug, or rather, the bug regarding both keys getting pressed when one was pressed in the original play only, appears to be a regression from https://github.com/ppy/osu/pull/12376 (cc @ekrctb).

Before #12376 (hidden mod diasbled programmatically):

https://user-images.githubusercontent.com/22781491/116801788-8ccf7080-ab15-11eb-8039-c559994b94fd.mp4

After #12376:

https://user-images.githubusercontent.com/22781491/116801790-8f31ca80-ab15-11eb-8610-4377684d871d.mp4

As you can see at the point of hitting circle 15, for some reason both keys got pressed, unlike in the above video before the regressing PR, causing the next circle to be hit prematurely.

**Comment by frenzibyte** [comment]
If it's any useful, here are the frames of the replay, along with a video showing them with a counter in the bottom giving the current gameplay time.

https://user-images.githubusercontent.com/22781491/116802450-8643f780-ab1b-11eb-9551-0304aa617825.mp4

**Comment by ekrctb** [comment]
My guess is this sort <https://github.com/ppy/osu/pull/12376/files#diff-c0f671905f32642378459e01ebe6de218af576fabf4b519a0b8ebf8a3f628f61R89> is unstable and the two replay frames at the same time got swapped.

**Comment by frenzibyte** [comment]
Right that may be the case, should use `OrderBy` instead for stability. But I'm wondering whether the frames list could use `SortedList` instead, not sure about the performance.

**Comment by bdach** [comment]
I don't believe `SortedList` will fix this, because I don't believe its `Add()` method is stable wrt insertion order (as in, it does not guarantee that if the list already has items with the same sorting key, the item will be added after all of them). This is because [it internally uses `BinarySearch()` to find the insertion index](https://github.com/ppy/osu-framework/blob/7e88bc0c19f490cddfcb733539690a7143ba95c1/osu.Framework/Lists/SortedList.cs#L64-L83), which does not have this property and can return the index of any of the existing items as long as the sorting key is equal ([see sharplab](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcAMACOSAsA3OunAMy4LYDC2A3utk5VQ2sx9gG4CGY2AGwCWAZ2DYAvNigBTAO7YAMqOAAeIVGAA+etiQAabAkPGjhsoYCs2AL7F2nJngCcACmFiAdACENfAJ4AyjJ8AMYAFq5kAJTR9hw26DZAA===)).
