### ISSUE TITLE
In in-game player info, lazer scores are shown as classic scores

### ISSUE THREAD

**Issue by hmoon630** [ppy/osu#12674]
**Describe the bug:** 

I just played on Osu! lazer, but "Recent plays" of **in-game player info** says my record is a classic score. 
Also accuracy on "Recent plays"(maybe it's calculated as a classic mod) and the one on local score is different

Is it intended or a bug??

**Screenshots or videos showing encountered issue:** 
![lazer score but classic mod](https://user-images.githubusercontent.com/48788794/116968897-56018200-acf0-11eb-98ac-652d96e51187.png)

It's the most recent play. I didn't played with a classic mod. But screenshot above says it's played with a calssic mod.
![yes, it's only with HD](https://user-images.githubusercontent.com/48788794/116968908-5a2d9f80-acf0-11eb-9828-a8e512c973ad.png)

**osu!lazer version:** 
2021.502.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6419405/database.log)
[network.log](https://github.com/ppy/osu/files/6419406/network.log)
[performance.log](https://github.com/ppy/osu/files/6419408/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6419409/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6419410/updater.log)

**Comment by peppy** [comment]
This is going to be how things are until server-side support is updated.

**Comment by Theighlin** [comment]
This is no longer the case, can be closed

**Comment by bdach** [comment]
I've just double-checked and no, it can't. While lazer scores no longer show the classic mod icon on user profile, stable scores don't seem to show it either. So if anything that looks closer to a regression than to being fixed.

**Comment by peppy** [comment]
Bumping to p1 so it doesn't get forgotten. We'll need to deal with this soon as we are switching across to the new score storage within the next month or few.

**Comment by Theighlin** [comment]
> I've just double-checked and as far as I can see, no, it can't. While lazer scores no longer show the classic mod icon on user profile, stable scores don't seem to show it either. So if anything that looks closer to a regression than to being fixed.

I think I can say that this issue can be closed now (fingers crossed). In the profile overlay,stable scores show the classic mod while lazer scores don't. Scores set with the classic mod from lazer are also shown correctly.

**Comment by Joehuu** [comment]
Can confirm, closing.
