### ISSUE TITLE
Leaderboard on playlists room screen too small

### ISSUE THREAD

**Issue by aphelionosu** [ppy/osu#12679]
![osu_2021-05-05_00-37-46](https://user-images.githubusercontent.com/41836319/117047130-b5d14a80-ad3b-11eb-996d-685278732c28.jpg)

Actually I just want to rather report that Leaderboard on playlist/time-shifted multiplayer is too small and feels uncomfortable. Would be better if the leaderboard at least able to shows 2 player at one time in leaderboard

**Comment by Joehuu** [comment]
I would move the extra mods to the bottom of the playlist as it doesn't need the width and add a collapsing feature to the chat that saves state.

**Comment by smoogipoo** [comment]
Sounds like a fine idea for the time being.

**Comment by peppy** [comment]
I'm not sure about putting it on the left as that column was meant to be the playlist-level options. I'd sooner consider moving the chat. Or just waiting for a full design to be ready.

**Comment by venix12** [comment]
should probably be closed (as of #16945)
