### ISSUE TITLE
(Slider) Paths are reporting incorrect `ReceivePositionalInputAt` in some cases

### ISSUE THREAD

**Issue by peppy** [ppy/osu#12671]
When entering the editor with a slider already on screen, clicking the blueprint doesn't work. This is due to the animation that plays when entering (not sure we want this animation but let's ignore that), which shifts the composer and its children downwards. The path is still reporting as if it is at the pre-transform location.

I've traced this down to framework's `Path`. It resolves after clicking the blueprint.

![20210503 184403 (JetBrains Rider)](https://user-images.githubusercontent.com/191335/116862319-89380880-ac3f-11eb-88cf-b7e4f1512484.png)

https://user-images.githubusercontent.com/191335/116862388-9fde5f80-ac3f-11eb-8a67-46ce399a3cc7.mp4

This can also be reproduced by toggling the timeline "Control Points" display mode, causing a resize of the playfield.

**Comment by ekrctb** [comment]
The cause of this issue is different.
Because `SliderBodyPiece` is always transparent, `IsPresent` is `false` and the body piece is not updated (not sure what exactly the mechanism of this is).
Setting `AlwaysPresent = true` will resolve the issue.

**Comment by bdach** [comment]
Setting `AlwaysPresent` unconditionally should be an absolute last resort.

**Comment by peppy** [comment]
Right, this is making a whole lot more sense now. I was sure that the `BodyPiece` reference was one inside the `DrawableSlider`, but as it turns out it's part of the blueprint.

I think we should be checking against the `DrawableSlider` instead.

**Comment by peppy** [comment]
> Setting `AlwaysPresent` unconditionally should be an absolute last resort.

I think it actually makes sense here, as it's a tightly coupled component with its direct parent relying on it for input handling.
