### ISSUE TITLE
Frame drops on linux when using slow hard drive

### ISSUE THREAD

**Issue by Kyuunex** [ppy/osu#12687]
**Describe the bug:** The game stutters if it's data is on a slow hard drive. The stuttering manifests itself in a form of the last rendered frame being shown far longer than it's supposed to. Stuttering happens in the beatmap listing, when scrolling, when clicking on the beatmap, when searching for a beatmap, when downloading/importing a beatmap from the online thing and even during gameplay (for what I assume the game trying to load something while gameplay). Additionally, the game takes a good 20 seconds to launch.

To troubleshoot this, I temporarily copied the whole game data folder to my SSD (in the very limited space I had) and everything was smooth, no stuttering happened, the game launched instantly. Maybe a little stutter while searching.

osu-stable does not stutter during gameplay or at all even on this slow disk drive. I have not enabled "reduce dropped frames on it".

The reason, I prefer to keep the game data on a Hard Drive is because I have 100+ GB worth of beatmaps, and am very limited with SSD storage.

Also, I did not use the game's in game move functionality, I just symlink folders.

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/5400432/117138383-04262e00-adbc-11eb-981c-f25e5706534d.mp4
CPU is Ryzen 7 2700, so the stuttering is not happening as a result of me recording this

**osu!lazer version:** 
2021.502.0 but this has been a thing a long before this specific version
linux btw

**Logs:** 
[logs.tar.gz](https://github.com/ppy/osu/files/6426915/logs.tar.gz)

**Other:**
Arch Linux, KDE. 
The hard drive is a 4 TB drive from WD. It is formatted in btrfs. I used to have it on ext4 but recently moved it to btrfs. it stutters on both of them, but I would say a little more so on btrfs. Maybe this time around game files are in the slower sectors of the drive? or btrfs sucks idk

**Comment by peppy** [comment]
Please keep the game files on your hard drive and use the in-game support for moving the beatmap storage to your slow media.

Can't really act on these kinds of reports when they come from linux, unfortunately, as anything could be at play. Will leave it open until I get a chance to confirm whether this is an issue on windows.

**Comment by Kyuunex** [comment]
I moved to using the in-game support. It seems to not stutter anymore during gameplay, still stutters while searching tho but overall seems more responsive. 

(this symlink was reminiscent from the old days when in-game support was not there)

feel free to close this if you think not much can be done about it stuttering while searching. 
(maybe you can make it not stutter and show a wait animation while it's searching like what it shows when searching online for maps?)

**Comment by peppy** [comment]
Great to hear. We are already aware of song select performance issues (these are generally not IO related, but more that we are not doing searching asynchronously quite yet). It will be addressed when we get around to migrating the database format we're using for lookups there.

Will close this for now as the main issue seems to be resolved.
