### ISSUE TITLE
Optimisation for Galaxy A42 5G

### ISSUE THREAD

**Issue by FlorinBoghian** [ppy/osu#12684]
Better optimisation of the main menu with teardrop, notch and hole punch camera

**Proposal designs of the feature:**

**Comment by smoogipoo** [comment]
Performance is a constant WIP. This is unactionable.

**Comment by peppy** [comment]
We are already tracking this via https://github.com/ppy/osu/issues/4330.

For the time being you can adjust the "Screen Scaling" setting to make sure the game doesn't cover the holes your manufacturer made in your screen.

![20210505 183539 (dotnet)](https://user-images.githubusercontent.com/191335/117122315-bcf66800-add0-11eb-9bc7-a32a7ceb5094.png)

**Comment by FlorinBoghian** [comment]
Thanks :)
