### ISSUE TITLE
Osu does not open

### ISSUE THREAD

**Issue by stefanobarbon** [ppy/osu#12689]
updated the drivers but now it does not open
tried re-installing the game but that does not fix it
[runtime.log](https://github.com/ppy/osu/files/6428989/runtime.log)

**Comment by bdach** [comment]
This is another case of the GDI generic OpenGL driver being used for whatever reason (see #12521, #10174, #9072, etc.)

If updating the driver doesn't help then there's nothing we can do for now. Please stay tuned for compatibility improvements in the future via DirectX support (direct or indirect).
