### ISSUE TITLE
Input offset

### ISSUE THREAD

**Issue by Pechu317** [ppy/osu#12680]
**Describe the new feature:** 
It offsets input by a customizable amount of time.
**Proposal designs of the feature:** 
Not exactly sure what this section means, but I guess you could have a slider called "Input Offset" in the controls tab in the settings menu.

**Comment by frenzibyte** [comment]
Check https://github.com/ppy/osu/issues/9811, it'll not happen. Please search next time.

**Comment by samurai-ops** [comment]
could you make a dear maria count me in osu beat map
