### ISSUE TITLE
osu!mania accuracy display

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu#12681]
**Describe the new feature:** 
Like "Quaver" and "ett" 
![456](https://user-images.githubusercontent.com/52590027/117099212-31b2ad80-ada3-11eb-9c39-f807e609dd7d.jpg)
Players can check the accuracy in real time.
that's cool, and it's going to be a lot more convenient for people who are streaming.
Players can also check their accuracy (perfect, great, etc.) in real time during breaks.

**Comment by peppy** [comment]
Duplicate of https://github.com/ppy/osu/issues/6492. Please search first.
