### ISSUE TITLE
Skin editor crashes if element is being dragged during player exit

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#12692]
this can be easily reproduced if you select and hold a skin element and quit to the main menu by using esc

**Screenshots or videos showing encountered issue:** 
https://youtu.be/t8BHNSJLRdU

**osu!lazer version:** 
commit bb496d05f72bbe917ce0c9180da671e41fd2086f

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6429810/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6429811/runtime.log)

**Comment by bdach** [comment]
Closing in favour of #18716
