### ISSUE TITLE
Can't import beatmaps for mac os

### ISSUE THREAD

**Issue by Ys0505** [ppy/osu#12699]
**Describe the bug:** 
Can't import beatmaps with mac and the import beatmaps from osu Stable doesn't work as it says that it is not detected 
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:**

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.
