### ISSUE TITLE
Osu!Lazer bug causes system to crash 

### ISSUE THREAD

**Issue by aewastaken** [ppy/osu#12691]
**Describe the bug:** 
Osu!Lazer beatmap + system crash (for some weird reason)
MacBook Pro intel i7 16gb ram with _MacOS 11.3.1_
**Screenshots or videos showing encountered issue:** 
will upload them soon from phone
**osu!lazer version:** 
2021.502.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6429417/database.log)
[network.log](https://github.com/ppy/osu/files/6429418/network.log)
[performance.log](https://github.com/ppy/osu/files/6429419/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6429420/runtime.log)

**Comment by peppy** [comment]
In order for us to action on this you are going to need to include the full crash log. Whether that is coming from an error popup or Console.app.

Nothing you have provided gives any details of what is happening.

**Comment by aewastaken** [comment]
ok i found i think i found it.

![Zrzut ekranu 2021-05-5 o 8 58 54 PM](https://user-images.githubusercontent.com/80064625/117194721-b7a31880-ade4-11eb-9281-5d5d454ded08.png)
both crashed at same time, here are logs
[WindowServer crash.odt](https://github.com/ppy/osu/files/6429607/WindowServer.crash.odt)
[Osu crash.odt](https://github.com/ppy/osu/files/6429608/Osu.crash.odt)

**Comment by aewastaken** [comment]
it didnt happened only once, all that today
![Zrzut ekranu 2021-05-5 o 9 00 43 PM](https://user-images.githubusercontent.com/80064625/117194914-f5a03c80-ade4-11eb-81da-46e7aa6af32a.png)

**Comment by peppy** [comment]
What is an ODT file? Please attach the raw text from the crash report. Including the WindowServer one.

**Comment by aewastaken** [comment]
ODT is shortcut of OpenDocumentText file

**Comment by bdach** [comment]
`.odt` is opendocument (open-source alternative to word).

[Here's a gist with the raw text](https://gist.github.com/bdach/71e351a7ec8e36629cc93fd17f3a3251). Seems very much like a not-our-problem type of issue? Entire windowserver looks to have been kicked by watchdog there.

**Comment by aewastaken** [comment]
What do you mean by that?

**Comment by aewastaken** [comment]
so, what else do you need?

**Comment by peppy** [comment]
This is an issue with the OpenGL drivers on your system, and something likely out of our control. We hope to eventually solve these kinds of problems by supporting Metal, but there is no timeline on this.
