### ISSUE TITLE
Map music suddenly started to play earlier than expected

### ISSUE THREAD

**Issue by szmarczak** [ppy/osu#12702]
**Describe the bug:** 

I was tinkering with the modifications. When I was done, I disabled them all and played a beatmap and noticed that the map music started playing much earlier. It got playable again when I set `audio offset` to ~~`160ms`~~ right now it is ~`200ms`.

~~It could be that other software running in background is causing this.~~

**Screenshots or videos showing encountered issue:** 

https://www.youtube.com/watch?v=bwH2KP8XoXc

The video was recorded using OBS. For some reason the clicks are delayed too in the video. In reality the clicks are being played right on time, so I don't know what's happend. Just the music is played too early. But the recording plays audio like `0ms` would be correct, but in reality it isn't correct.

**osu!lazer version:** 

https://github.com/ppy/osu/releases/tag/2021.502.0

**Logs:** [logs.zip](https://drive.google.com/file/d/1wQKMIy9S36WUc_0rza8rsYwuPw7Vq4lX/view?usp=sharing)

**LatencyMon result**:

![image](https://user-images.githubusercontent.com/36894700/117341032-eb904380-aea1-11eb-8b2a-c129a52a89f8.png)

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/117343934-1d56d980-aea5-11eb-929e-9602d85ccf82.png)

**Comment by szmarczak** [comment]
Restarted osu and the issue is gone. Definitely an issue with osu.

**Comment by bdach** [comment]
There *are* some errors in the logs attached, but I haven't seen anything like this before, am not even entirely sure how they could happen, and they do not look audio-related either:

```
2021-05-06 17:14:02 [error]: An unhandled error has occurred.
2021-05-06 17:14:02 [error]: osu.Framework.Screens.ScreenStack+ScreenNotInStackException: Cannot perform MakeCurrent on a screen not in a ScreenStack.
2021-05-06 17:14:02 [error]: at osu.Framework.Screens.ScreenStack.MakeCurrent(IScreen target)
2021-05-06 17:14:02 [error]: at osu.Framework.Screens.ScreenExtensions.MakeCurrent(IScreen screen)
2021-05-06 17:14:02 [error]: at osu.Game.Screens.Play.Player.PerformExit(Boolean showDialogFirst)
2021-05-06 17:14:02 [error]: at osu.Game.Screens.Play.Player.<createOverlayComponents>b__86_0()
2021-05-06 17:14:02 [error]: at osu.Game.Graphics.Containers.HoldToConfirmContainer.Confirm()
2021-05-06 17:14:02 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.Button.Confirm()
2021-05-06 17:14:02 [error]: at osu.Game.Graphics.Containers.HoldToConfirmContainer.<BeginConfirm>b__12_0(HoldToConfirmContainer _)
2021-05-06 17:14:02 [error]: at osu.Framework.Graphics.Transforms.TargetGroupingTransformTracker.invokePendingRemovalActions()
2021-05-06 17:14:02 [error]: at osu.Framework.Graphics.Transforms.Transformable.updateTransforms(Double time, Boolean forceRewindReprocess)
2021-05-06 17:14:02 [error]: at osu.Framework.Graphics.Transforms.Transformable.UpdateTransforms()
2021-05-06 17:14:02 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
```

**Comment by szmarczak** [comment]
It is definitely an issue with the audio.

**Comment by bdach** [comment]
I am not negating whether you have an audio issue. I'm saying that the error shown in logs may or may not be a separate issue. Because it doesn't *look* audio-related to me.

**Comment by szmarczak** [comment]
Agreed. I'll definitely let you know if I can reproduce the issue.

**Comment by szmarczak** [comment]
I tried to reproduce this but no luck. I remember the graphics were lagging a bit as well. It could also be that the circles started appearing later. IDK what has really happened.

**Comment by firinael** [comment]
This is happening to me right now, in version 2021.524.0.

I'm not sure what exactly is causing it, but I've noticed that the audio offset is just going completely haywire and going from way too early to way too late, to on time, it seems completely random.

I *think* it happens after I alt-tab, but I can't be sure because, as I said, it's extremely random. Messing with the actual audio offset option can make it realign with the clicks, but the next time it changes randomly I have to try and adjust the offset again.

It does reset after restarting the game, too, and the audio offset bar in the options isn't what's changing, what changes is only the offset itself.

**Comment by smoogipoo** [comment]
That sounds more like an issue with your system, though it's possible that https://github.com/ppy/osu-framework/pull/4463 may have fixed this by not re-initting the default device in one edge case (audio devices constantly changing, which could happen with a dodgy joystick that intermittently connects, for example)... Hard to say other to wait for and try the next update.

Do you have any other "latency reduction" apps in the background, like REAL?

**Comment by szmarczak** [comment]
> Do you have any other "latency reduction" apps in the background, like REAL?

No.

**Comment by firinael** [comment]
I don't have any latency reduction apps at all either, and even disabled the Discord overlay to make sure that wasn't it somehow.

Also didn't have my joystick connected.
And as I've mentioned before, it seemed to be something that pops up after having the game open for an hour or so, and that seems to change randomly with alt-tabs.

**Comment by peppy** [comment]
I'm just wondering if this is something which happens to all users over a long period of time (something to do with timekeeping / top level clock that is being used for gameplay timing).

Can either of you confirm whether it gets even worse if you leave osu! open for longer? Also is it a sudden thing, or does it gradually become worse the longer you have osu! running?

**Comment by bdach** [comment]
#9995 could be related.

**Comment by peppy** [comment]
Nice find, that does look oddly relevant...

**Comment by peppy** [comment]
@szmarczak and @firinael can you please confirm that this happens to you when alt-tabbing, and that you are both running full screen? If so, we'll continue tracking the issue over at #9995 just to keep all further conversation in one place.

**Comment by peppy** [comment]
We found a potential cause for this. Please test again in the next release to see if it feels better.

**Comment by peppy** [comment]
Tentatively closing this as I'm 99% sure it should be resolved.

Still appreciate a response from @szmarczak / @firinael confirming or otherwise.
