### ISSUE TITLE
Game not finding my tablet (xp-pen g640 on linux)

### ISSUE THREAD

**Issue by qween0w0** [ppy/osu#12700]
Tablet works fine outside of the game, but when I open the game and go to input the game says no tablet is connected, although it clearly is. 
When I plug out the tablet and plug it back in it finds it for a second, but then stops finding it right after. 
I'm using the latest version, both of the game and of the drivers, this used to sometimes happen with older versions too, but I'd just need to reboot my pc and all would work fine.

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

**Comment by Razuuu** [comment]
having the "same" issue, using pentablet software for my XP Pen G640, works for my desktop, but in osu!lazor stop working.
![osu_error](https://user-images.githubusercontent.com/40471551/117538098-d41d9b80-b004-11eb-8e07-5da603cb29c6.png)

Kind regards
Razuuu
