### ISSUE TITLE
Clicking on "Show More" button in News Overlay will show the same posts.

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#12716]
Previously we were relying on `Cursor` included in the `GetNewsRequest`'s response. However now it's (returned cursor) null, which is causing such behavior.
Not sure whether it is web-side issue or not, leaving here for now.

**Comment by frenzibyte** [comment]
As per the [documentation](https://osu.ppy.sh/docs/index.html?bash#currentuserattributes):

![CleanShot 2021-05-08 at 05 33 50](https://user-images.githubusercontent.com/22781491/117522985-f987b680-afbe-11eb-8978-166a70b8ecac.png)

And with double-checking on the news request response, all the news are included as of 2021, it's a client-side issue for displaying the "Show More" button even though there's nothing to show next (`cursor` = null).

**Comment by EVAST9919** [comment]
> And with double-checking on the news request response, all the news are included as of 2021.

`GetNewsRequest` returns only latest 12 posts with null cursor (even if on the website there are many more), the rest as of 2021 included in the `news_sidebar` (which is not implemented, but it shouldn't matter), but they don't have full post info.

**Comment by frenzibyte** [comment]
I see, that does sound like an API issue / incomplete then, should report at their end for the fact that `cursor` is not behaving properly and showing further posts, doesn't sound related to the client other than it not handling null `cursor`s properly, which is to be fixed in #12727.

**Comment by peppy** [comment]
Tracking remaining issue at https://github.com/ppy/osu-web/issues/7571.
