### ISSUE TITLE
Temporary files from beatmap downloads via beatmap listing overlay are not cleaned up properly

### ISSUE THREAD

**Issue by Lefafel** [ppy/osu#12718]
This might be intended behavior for all I know, but as it stands, it makes osu!lazer an unviable version of the game for me due to my system's hard drive space allocation.

**Describe the bug:**
As the title says, even after successfully changing osu!lazer's folder location to a different hard drive, all the data from exporting maps/skins still goes to the original .\appdata folder.

**Screenshots or videos showing encountered issue:** 
![01freshinstall](https://user-images.githubusercontent.com/41944069/117536798-e0eebf00-b005-11eb-9704-671eb7e2c693.jpg)
Step 1: Made a fresh install of osu!lazer
![02storagechange](https://user-images.githubusercontent.com/41944069/117536842-1a272f00-b006-11eb-84d9-838a27c32fb9.jpg)
Step 2: used the folder location changer to successfully point to a different hard drive
![03alldatagoestoC](https://user-images.githubusercontent.com/41944069/117536849-201d1000-b006-11eb-8b54-90be1d690db4.jpg)
Step 3: Imported a bunch of maps and skins, all data goes to the old .\appdata folder instead of the new appointed folder on the K:\ drive.

**osu!lazer version:** 
Latest as of the time of posting, 2021.502.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6445725/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6445726/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6445727/updater.log)
[database.log](https://github.com/ppy/osu/files/6445728/database.log)
[network.log](https://github.com/ppy/osu/files/6445729/network.log)

**Comment by Lefafel** [comment]
This is what's in the designated folder on K:\
![04whatsinK](https://user-images.githubusercontent.com/41944069/117537330-d5e95e00-b008-11eb-9e9d-beb3e6d177e8.jpg)

Appdata no longer has a storage.ini, don't know if it was there to begin with. you can see above that there is also no storage.ini in the K:\ folder.
![05whatsinappdata](https://user-images.githubusercontent.com/41944069/117537373-22cd3480-b009-11eb-96a1-cacba3afc56a.jpg)

**Comment by bdach** [comment]
The lack of a `storage.ini` file would definitely explain it as the file is needed for the game to know where to look for beatmap files, etc.

This looks a bit like the migration didn't complete successfully somehow (some of the old files are also in the new location, old location wasn't purged, missing `storage.ini`).

* Please compare the size of the old and new folders.
* Did you interrupt the migration in any way? If not, please try performing it again and check for any error messages.

**Comment by Lefafel** [comment]
Trying to change the folder location to something it already was just gave an error about that fact so I deleted the folder in K:\ and then ran the folder location changer again, no errors came up. Folder contents on the new K:\...\osu-lazer seem identical to before.

This time there is a storage.ini that correctly says `FullPath = K:\Media\Games\osu-lazer` in the .\appdata\roaming\osu folder, and the duplicate file structure from K: is gone.
![07newappdata](https://user-images.githubusercontent.com/41944069/117538264-0e3f6b00-b00e-11eb-9cf2-9da1c28a5923.jpg)


So I imported a bunch more maps to see what would happen, and it is still storing something onto C:\
![06tryingagain](https://user-images.githubusercontent.com/41944069/117538176-a6892000-b00d-11eb-8434-8e895c6d7712.jpg)

However, now there's data being stored on BOTH the old and the new file locations.
![08sizesbeforemapimport](https://user-images.githubusercontent.com/41944069/117538685-01bc1200-b010-11eb-810c-45438efceef6.jpg)
imported 10 or so beatmaps
![09sizeaftermapimport](https://user-images.githubusercontent.com/41944069/117538690-054f9900-b010-11eb-8757-ee09af8e28fe.jpg)

**Comment by Lefafel** [comment]
Also notable that only ~1% of the new data that's being stored on C:\ is going into the \appdata\roaming\osu folder, the rest seems to be going somewhere else? Where would it even be going, I checked the appdata\local\osulazer folder but that has not seen any changes at all.

**Comment by bdach** [comment]
If it's not in either roaming or local then that might as well be something else on your system entirely. You need to check this yourself, with a tool that shows precise disk usage per directory.

**Comment by Lefafel** [comment]
Many diagnostics and reboots later...

Looks like osu!lazer is creating a sizable temp file (into .appdata\local\Temp) for every beatmap import I do, and those temp files are also not getting cleared on lazer client restart or even PC restart. Do I need to manually go clear the temp files every time I import new maps, or is this somehting lazer should be doing by itself but is failing to do for some reason?
![11tempfiles](https://user-images.githubusercontent.com/41944069/117541986-3daaa380-b01f-11eb-939a-f2b7416ae62b.jpg)

**Comment by Lefafel** [comment]
yeah I was using the in-game beatmap listing to download a bunch of random mapsets for testing purposes. Glad to know there's a fix on the way!
