### ISSUE TITLE
Osu slutters while playing beatmaps or using menu

### ISSUE THREAD

**Issue by aewastaken** [ppy/osu#12713]
**Describe the bug:** 
Osu slutters few times while playing beatmaps
**Screenshots or videos showing encountered issue:** 

here is a **very** short video showing that issue (pro tip: look at fps counter)
as you can see it drops all fps for some reason. i mean, i can live with that small lag but its better to report it anyway

https://user-images.githubusercontent.com/80064625/117488748-10052200-af6d-11eb-9935-6baaffd4bf3d.mov

https://user-images.githubusercontent.com/80064625/117489172-99b4ef80-af6d-11eb-8234-c6ea11c5cf01.mov

https://user-images.githubusercontent.com/80064625/117489647-2790da80-af6e-11eb-836d-893a1236af53.mov

**osu!lazer version:** 
2021.502.0 (mac version)
**Logs:**
[database.log](https://github.com/ppy/osu/files/6443428/database.log)
[network.log](https://github.com/ppy/osu/files/6443429/network.log)
[performance.log](https://github.com/ppy/osu/files/6443430/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6443431/runtime.log)

**Comment by peppy** [comment]
- Please test with the default skin
- Please link the beatmap in question
- Please attach logs from the actual session (the attached logs don't even enter gameplay)
- List system specs

We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.
