### ISSUE TITLE
Crash when exiting the map at the end

### ISSUE THREAD

**Issue by Kremator1007** [ppy/osu#12710]
**Describe the bug:** 
If you try to exit the map (by holding ESC) when the map has just ended (or is about to end, I am not sure), the game crashes.

**osu!lazer version:** 
Latest stable (2021.502.0), compiled from the source on linux mint 20.1

**Logs:**
[database.log](https://github.com/ppy/osu/files/6442043/database.log)
[network.log](https://github.com/ppy/osu/files/6442044/network.log)
[performance.log](https://github.com/ppy/osu/files/6442045/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6442046/runtime.log)

**Comment by peppy** [comment]
Can you confirm you are not compiling from `master` but from the release tag?

**Comment by Kremator1007** [comment]
Actually, I have compiled it from the master branch. This doesn't reproduce in the tagged version. I guess I'll close it then

**Comment by peppy** [comment]
It's fine to keep it open, just needed that clarification. It's a likely regression of the recent outro skip logic.

**Comment by Cublibre** [comment]
I was able to reproduce this by disabling the storyboard/playing any map without a storyboard, then attempting to exit after the last judgement is processed and before the score is displayed. The exception occurs from `updateCompletionState()` being called from `PerformExit()` while it is already in the delayed sequence from the score processor calling it.

A possible fix is cancelling and nullifying `completionProgressDelegate` in `PerformExit`.
This makes the score show immediately unlike in the latest release, where the game exits to song selection.

**Comment by frenzibyte** [comment]
Thanks for the reproduction, are you willing to fix it yourself? it sounds like the completion logic in `PerformExit` has an oversight of performing the exit regardless of whether `scheduleCompletion` has been already called, and should guard against that.

Also if you will do, write a test case for it in the existing test scene (check `TestSceneCompletionCancellation` as an example of how to test that)
