### ISSUE TITLE
crashed every time i try to load skins from stable

### ISSUE THREAD

**Issue by NeekoVN** [ppy/osu#12711]
**Describe the bug:** 
it crash everytime i try to load skins from stable
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
latest (2021.502.0)
**Logs:**

[database.log](https://github.com/ppy/osu/files/6442792/database.log)
[network.log](https://github.com/ppy/osu/files/6442794/network.log)
[performance.log](https://github.com/ppy/osu/files/6442795/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6442796/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6442797/updater.log)

**Comment by peppy** [comment]
There are no crashes in the attached logs.

**Comment by jai-x** [comment]
Your included logs do not included the error reported. 
Please try to reproduce the issue and then post the log files without opening the game again.

**Comment by NeekoVN** [comment]
am i just having a very bad luck or this time lazer didn't crashed
