### ISSUE TITLE
Add auto skip

### ISSUE THREAD

**Issue by gamerturtlepoggers** [ppy/osu#12729]
**Describe the new feature:** 
There is an option to automatically skip intros
**Proposal designs of the feature:** 
For example if you click f10 is disables mouse buttons maybe there could be something like that to disable intros

**Comment by peppy** [comment]
I don't think this is something we want, but will leave it open as a proposal.

**Comment by szmarczak** [comment]
I approve this feature. It's really annoying to have skip intros.

**Comment by bdach** [comment]
@szmarczak please stop adding "i agree" comments. they are noise. use reactions on the first post instead.

**Comment by szmarczak** [comment]
I don't consider `It's really annoying to have to skip intros.` as noise.

> use reactions on the first post instead.

Already did that.
