### ISSUE TITLE
XP-Pen G640 / Tablets on Linux

### ISSUE THREAD

**Issue by Razuuu** [ppy/osu#12726]
**Describe the bug:** 
In the last issue I mentioned that my tablet doesn't work with osu!lazor. I fixed that bug, but I'm getting the next one.
The question is, why do you program a tablet menu when you have to fix it manually? (I know osu!lazor is only a developer version ..)
I know a lot about Linux myself, but don't know how to fix it myself.

I also decided to use Linux to escape from Microsoft packages (spyware), so it doesn't make sense to install dotnet packages.

This issue should not sound aggressive in anyway, sorry for that.

**Screenshots or videos showing encountered issue:** 
![osu_error](https://user-images.githubusercontent.com/40471551/117552989-22578c80-b04f-11eb-87e9-86c8825507b7.png)
![osu_error_2](https://user-images.githubusercontent.com/40471551/117553021-52069480-b04f-11eb-8c34-860c69f96832.png)

**osu!lazer version:** 
2021.502.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6446561/database.log)
[network.log](https://github.com/ppy/osu/files/6446562/network.log)
[performance.log](https://github.com/ppy/osu/files/6446563/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6446564/runtime.log)

Kind regards
Razuuu

**Comment by frenzibyte** [comment]
> The question is, why do you program a tablet menu when you have to fix it manually? (I know osu!lazor is only a developer version ..)

I don't understand what this means, how does having in-game tablet menu relate to fixing tablet issues?

Either way, the logs literally instruct you to go to this link https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#argumentoutofrangeexception-value-0-15 and fix the issue yourself (you can open the `runtime.log` to get the full link).

**Comment by frenzibyte** [comment]
Closing this as not an issue to handle on this side.

**Comment by bdach** [comment]
> The question is, why do you program a tablet menu when you have to fix it manually?

You should direct that question to whoever decided that on Linux distributions tablet device streams are not user-readable by default without udev rules. There's no such person here as far as I know.

> I also decided to use Linux to escape from Microsoft packages (spyware)

You do realise that lazer is *running* on dotnet, right, just bundled in an appimage? If you have an issue with that, then you shouldn't play or install the game. Or post github issues either, probably, since github is *also* owned by microsoft.
