### ISSUE TITLE
Maps converted to osu!mania should display key count in details

### ISSUE THREAD

**Issue by Silver-Volt4** [ppy/osu#12720]
**Describe the new feature:** 
This is the details tab of an osu!mania map:
![image](https://user-images.githubusercontent.com/35656715/117538603-3e374000-b007-11eb-8848-4c0f5d304ef2.png)
This is the details tab of an osu! map converted to osu!mania:
![image](https://user-images.githubusercontent.com/35656715/117538624-5909b480-b007-11eb-84d4-c5145403f7c6.png)
Currently, there is no way of finding out the key count of a converted map (as far as I know) without playing it. Not that of a big deal, but having it somewhere could improve UX.
**Proposal designs of the feature:** 
Replace circle size with key count for converted maps.
#9453 had discussion about displaying key count elsewhere. Hasn't been active since November 2020, except for duplicate issues being linked to it.

**Comment by bdach** [comment]
Fixing this is sort of implied by the linked issue, so this borders on a duplicate, but sure, I guess it can be a separate one.

As an aside, the fact that the issue "hasn't been active" doesn't mean anything. There are almost a thousand issues open. We know that this needs fixing.
