### ISSUE TITLE
Add Inter font

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu#12739]
Mentioned in https://github.com/ppy/osu/pull/12688#issuecomment-832874635

**Proposal** : Add Inter font as secondary font.

osu!web itself is using it as [main content font](https://github.com/ppy/osu-web/blob/95310a72ab9eb9dccbfc3ebd5b4031f0c4147540/resources/assets/less/variables.less#L10).

**Comment by VINXIS** [comment]
is it possible at all if we could just select our own font choice somehow instead of restricting it to only a select few? That could be better than only adding this/monospaced font by giving people the option to choose their font.

(Also mainly asking for lazer tournament client purposes as well since many tournaments would usually want to use fonts that fit within the general aesthetic choices they made for the design of their own tournament which can conflict with the default font choice(s) of lazer)

**Comment by peppy** [comment]
This is an issue about the content font for wiki display purposes. If you want tournament customisation please open a separate issue specifically about that.

**Comment by TicClick** [comment]
passing by to say this will also significantly improve cyrillic characters ([current font](https://cdn.discordapp.com/attachments/188630652340404224/854121843829243944/osu_2021-06-15_00-12-54.png) vs [Inter](https://fonts.google.com/specimen/Inter?preview.text_type=custom&preview.text=%D0%A1%D1%8A%D0%B5%D1%88%D1%8C-%D0%BA%D0%B0%20%D0%B5%D1%89%D1%91%20%D1%8D%D1%82%D0%B8%D1%85%20%D0%BC%D1%8F%D0%B3%D0%BA%D0%B8%D1%85%20%D1%84%D1%80%D0%B0%D0%BD%D1%86%D1%83%D0%B7%D1%81%D0%BA%D0%B8%D1%85%20%D0%B1%D1%83%D0%BB%D0%BE%D1%87%D0%B5%D0%BA,%20%D0%B4%D0%B0%20%D0%B2%D1%8B%D0%BF%D0%B5%D0%B9%20%D0%B6%D0%B5%20%D1%87%D0%B0%D1%8E))

**Comment by gagahpangeran** [comment]
Because localisation is currently happening, looks like I'll work on this today or tomorrow so the cyrillic characters will fallback into Inter font instead of current Noto font.

**Comment by gagahpangeran** [comment]
Here are some comparisons for cyrillic character. Before is font in current master, after is Inter font.

---

**Before**

![Screenshot from 2021-06-16 20-54-29](https://user-images.githubusercontent.com/4964985/122233214-141a4d00-cee6-11eb-9e47-241f985f6ed0.png)

**After**

![Screenshot from 2021-06-16 20-48-57](https://user-images.githubusercontent.com/4964985/122233256-1bd9f180-cee6-11eb-958c-7481c9122ccc.png)

---

**Before**

![Screenshot from 2021-06-16 20-57-06](https://user-images.githubusercontent.com/4964985/122233373-344a0c00-cee6-11eb-9f70-3a7dde93f11b.png)

**After**

![Screenshot from 2021-06-16 20-45-07](https://user-images.githubusercontent.com/4964985/122233418-3dd37400-cee6-11eb-92e0-a929943effed.png)

---

**Before**

![Screenshot from 2021-06-16 20-58-09](https://user-images.githubusercontent.com/4964985/122233457-475cdc00-cee6-11eb-8d75-4c642429be25.png)

**After**

![Screenshot from 2021-06-16 20-48-24](https://user-images.githubusercontent.com/4964985/122233482-4d52bd00-cee6-11eb-87fd-d9071ee4549f.png)

---

Will PR soon after do some more check.

**Comment by TicClick** [comment]
bliss to my eyes. thanks for reconfirming
