### ISSUE TITLE
Autopilot on touch platforms doesn't count clicks unless they are correctly positioned

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#12731]
**Describe the new feature:** 
Now, to interact with objects, I need to hover over the object itself, which is contrary to the essence of the mod.

**Proposal designs of the feature:** 
Is it possible to register clicks from the entire screen? I just want to follow the rhythm.

**Comment by frenzibyte** [comment]
Are you sure you're using the latest version of the game? there was an issue related to this that was solved already long ago. (https://github.com/ppy/osu/issues/11700)

**Comment by Moltanicaa** [comment]
No, clicks are registered on hover. But I need to hover over the object itself.

**Comment by frenzibyte** [comment]
I know that already, I'm asking you whether you're sure you're using the latest version of the game to ensure this is an actual issue.

**Comment by Moltanicaa** [comment]
I apologize for the orientation of the video, the recording program cannot be launched when the wasp is open. The latest version (otherwise there would be a message about the need to update).
https://youtube.com/shorts/F-U4Q9Ga6gY?feature=share

**Comment by peppy** [comment]
I believe this must be something to do with the touch->mouse conversion, potentially taking precedence over the local logic in autopilot. Needs further investigation.
