### ISSUE TITLE
Investigate beatmap import performance when beatmap is already loaded into client

### ISSUE THREAD

**Issue by ribbanya** [ppy/osu#12746]
While this is marked as a feature request, I'm really just looking for a quick hack because I'm not sure how applicable this issue is to the userbase at large. So it's more of just a question. Please feel free to close it immediately.

# Background

I have a very large (27,300) collection of beatmaps that I'm trying to import from stable. As you can imagine, not all of these are well-formed beatmaps that lazer will accept. It's also not the most stable process in the world; my game crashed last time I tried to load the selection screen, forcing me to start the import over even though about 20k beatmaps are now successfully imported.

# Speculative implementation

Without any familiarity with the codebase, I was thinking of just adding a new table to the database that contains a unique index of directory names within `osu!\Songs`. Then all the import process has to do is look at the directory name before determining whether to skip, so it can get back to where it left off last time as quickly as possible. Once a beatmap is successfully (or unsuccessfully, I suppose) added to the collection, it adds the stable directory name.

# Questions

Is my approach too naive? Do you have any suggestions? Would this feature actually be desirable for a pull request?

Thank you!

**Comment by peppy** [comment]
We already do skip already-imported beatmaps, but it's done via a relatively intensive hash check. There are plans to improve this in the future, but I don't think there will be a local implementation/hack in the mean time. You could consider importing in smaller batches by splitting your `Songs` directory into multiple pieces and running the import multiple times for each piece for the time being.

**Comment by ribbanya** [comment]
I wrote a [PowerShell script](https://gist.github.com/ribbanya/d60bfac56c312850992ef2cdf7c58aeb) to take care of the batching. Just leaving it here in case anyone else finds it useful.

**Comment by smoogipoo** [comment]
Resolved by https://github.com/ppy/osu/pull/13673
