### ISSUE TITLE
Second level context menus can go off-screen

### ISSUE THREAD

**Issue by peppy** [ppy/osu#12749]
Self-explanatory

![20210511 180559 (dotnet)](https://user-images.githubusercontent.com/191335/117789692-8f536800-b283-11eb-9a96-a0fc64d02ae2.png)

**Comment by smoogipoo** [comment]
Tracked framework-side at https://github.com/ppy/osu-framework/issues/3861

**Comment by peppy** [comment]
Has been resolved
