### ISSUE TITLE
Freezing bug

### ISSUE THREAD

**Issue by ITWolfHypixel** [ppy/osu#12756]
**Describe the bug:When i play this map https://osu.ppy.sh/beatmapsets/715915#osu/1513044 [Another] difficult with using this skin https://mega.nz/file/5WZ1TCDb#kGvBLznI9aH-KxbBQsIkOl5Lumaeere0Jn9rj7qaP4Q and enable EZ and Score V2 modes and doing many misses my game freezes by one second. ** 

**Screenshots or videos showing encountered issue:*https://i.imgur.com/Ytlt7Rc.mp4* 

**osu!lazer version:*stable b20210423.2* 

**Logs:**

**Comment by jai-x** [comment]
This repository is for development of osu!lazer only.

Please open bug reports for osu!stable here: https://github.com/ppy/osu-stable-issues
