### ISSUE TITLE
Deleting skin elements isn't being saved

### ISSUE THREAD

**Issue by GopoBoi** [ppy/osu#12786]
**Describe the bug:** 
Deleting skin elements using the skin editor isn't saved
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=P-hGCExyWfA
**osu!lazer version:** 
2021.514.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6473884/database.log)
[network.log](https://github.com/ppy/osu/files/6473885/network.log)
[performance.log](https://github.com/ppy/osu/files/6473886/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6473887/runtime.log)

**Comment by peppy** [comment]
Can you show what skin is selected in your settings? It should be "osu! default (modified)".

**Comment by peppy** [comment]
Please also test with a different skin, and test doing something that isn't deleting. My hypothesis is that *nothing* is saving for your specific case, not just deletion.

**Comment by GopoBoi** [comment]
The modified skin is selected:
![2021-05-13_18-57](https://user-images.githubusercontent.com/69014805/118159410-46371b80-b41d-11eb-8f6e-eda301bdc617.png)
Also happens with legacy skins, moving elements is being saved.

**Comment by bdach** [comment]
A dirty fix for this is:

```csharp
diff --git a/osu.Game/Skinning/ISkinnableTarget.cs b/osu.Game/Skinning/ISkinnableTarget.cs
index 65b8ba7b17..9f0f9d671a 100644
--- a/osu.Game/Skinning/ISkinnableTarget.cs
+++ b/osu.Game/Skinning/ISkinnableTarget.cs
@@ -29,7 +29,10 @@ public interface ISkinnableTarget : IDrawable
         /// Serialise all children as <see cref="SkinnableInfo"/>.
         /// </summary>
         /// <returns>The serialised content.</returns>
-        IEnumerable<SkinnableInfo> CreateSkinnableInfo() => Components.Select(d => ((Drawable)d).CreateSkinnableInfo());
+        IEnumerable<SkinnableInfo> CreateSkinnableInfo()
+            => Components.Cast<Drawable>()
+                         .Where(d => d.Parent != null)
+                         .Select(d => d.CreateSkinnableInfo());
 
         /// <summary>
         /// Reload this target from the current skin.
```

Basically, even though the component was correctly deleted and expired, `ISkinnableTarget.Components` still holds a reference to it regardless.

**Comment by peppy** [comment]
I'd hope we can actually remove the components from the bindable list via the editor flow. It's not intended that they stay around in there.
