### ISSUE TITLE
Skin editor: opening options may reset custom current skin

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#12789]
**Describe the bug:** 
When you opened the skin editor with Ctrl+Maj+S, when you open the options with Ctrl+O, the skin is replaced by the default. Imagine having this when you didn't saved your settings ;_;

Also, this happens only if the "Save changes" button is pressed at least 1 time, even without modification.

**Screenshots or videos showing encountered issue:** 
(I'm using the skin show in the 1st picture before pressing Ctrl+O)
I didn't pressed "Save changes" and I pressed Ctrl+O...
![osu_2021-05-13_22-31-09](https://user-images.githubusercontent.com/57914482/118184556-ca000080-b43b-11eb-87ce-0151fdce2d36.png)

I pressed "Save changes" before and I pressed Ctrl+O...
![osu_2021-05-13_22-31-17](https://user-images.githubusercontent.com/57914482/118184561-cb312d80-b43b-11eb-8a0b-61de215fbbe6.png)

**osu!lazer version:** 
2021.514.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6474943/database.log)
[network.log](https://github.com/ppy/osu/files/6474944/network.log)
[performance.log](https://github.com/ppy/osu/files/6474945/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6474946/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6474947/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6474948/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6474949/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6474950/updater.log)

**Comment by Corne2Plum3** [comment]
Also, the bug even happens on gameplay, once you closed the skinning editor (if you pressed "Save changes")

**Comment by peppy** [comment]
This is due to a forgotten framework bump (already fixed). Will be resolved next release.
