### ISSUE TITLE
Dragging sliders in the editor causes weird movements

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#12787]
I couldn't find for an open issue tracking this one

**Describe the bug:** 

The video describes it better

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/41755816/118173628-d2d0e200-b3fb-11eb-8ab4-b3d1c57b7661.mp4

**osu!lazer version:** 

2021.514.0

**Logs:**

[performance-update.log](https://github.com/ppy/osu/files/6474501/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6474502/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6474503/updater.log)
[database.log](https://github.com/ppy/osu/files/6474504/database.log)
[network.log](https://github.com/ppy/osu/files/6474505/network.log)
[performance.log](https://github.com/ppy/osu/files/6474507/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6474508/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6474509/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/6474510/performance-input.log)

**Comment by bdach** [comment]
I can reproduce, but *only* in single-threaded mode and only for a while after switching (seems to calm down after dragging for a second or two). Very scary...

**Comment by peppy** [comment]
I can't seem to repro this one. @bdach able to take a bit of a dive whenever you get a chance?

**Comment by smoogipoo** [comment]
@peppy have you tried single threaded? I can reproduce immediately.

**Comment by peppy** [comment]
Yes, followed above instructions. I think it may be related to frame rate (in single threaded mode I am vsynced due to macOS).
