### ISSUE TITLE
Starting gameplay in multiplayer/playlists pushes player screen without a loader

### ISSUE THREAD

**Issue by Szago** [ppy/osu#12797]
**Describe the bug:** Whenever I'm pressing the start button in playlist lobby, there is an empty Lazer background screen appearing for ~1 second instead of a loading screen.

**Screenshots or videos showing encountered issue:**  https://www.youtube.com/watch?v=srZG_8TDi0o

**osu!lazer version:**  2021.514.0

**Logs:** 

[runtime.log](https://github.com/ppy/osu/files/6475773/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6475774/updater.log)
[database.log](https://github.com/ppy/osu/files/6475775/database.log)
[network.log](https://github.com/ppy/osu/files/6475776/network.log)
[performance.log](https://github.com/ppy/osu/files/6475777/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6475778/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6475779/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6475780/performance-update.log)

**Comment by frenzibyte** [comment]
Looks to be an oversight from #12538, `CreateGameplayScreen()` should return a player loader with the player inside rather than just the player directly, will get this one.
