### ISSUE TITLE
Double results after completing map in playlists

### ISSUE THREAD

**Issue by Szago** [ppy/osu#12798]
**Describe the bug:**  Each time I finish a map in playlists, two results of my single play appear, most of the time there is a difference of 1-100 score between them, and one of them shows one less or more dropped sliderends, also the second result always doesn't have pp value displayed. 

**Screenshots or videos showing encountered issue:**  
![osu_2021-05-14_02-34-59](https://user-images.githubusercontent.com/43099280/118204715-26c0e280-b45f-11eb-93ef-5914616fd1fb.jpg)

**osu!lazer version:** 2021.514.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/6475824/database.log)
[network.log](https://github.com/ppy/osu/files/6475834/network.log)
[performance.log](https://github.com/ppy/osu/files/6475826/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6475827/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6475828/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6475829/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6475830/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6475831/updater.log)

**Comment by peppy** [comment]
Sounds like a potential regression with the player progression logic.
