### ISSUE TITLE
Retry button in playlists exits to lobby

### ISSUE THREAD

**Issue by ch4tie** [ppy/osu#12790]
**Describe the bug:** 
Pressing the quick retry ingame or the retry button in the pause menu while in a multiplayer lobby sents user back to the lobby.

**osu!lazer version:** 
2021.514.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6474935/database.log)
[debug.log](https://github.com/ppy/osu/files/6474936/debug.log)
[network.log](https://github.com/ppy/osu/files/6474937/network.log)
[performance.log](https://github.com/ppy/osu/files/6474938/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6474939/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6474940/updater.log)

**Comment by bdach** [comment]
The bug here is the retry hotkey doing anything in real-time multiplayer at all.

(Note that I said multiplayer and not playlists.)

**Comment by bdach** [comment]
Actually I re-checked logs and am now confused.

@ch4tie do you mean "multiplayer" or do you mean "playlists"? because it seems that you meant the latter from the logs. the distinction is quite important.

**Comment by ch4tie** [comment]
oh my god sorry, I meant playlists!! The bug happens in playlists

**Comment by peppy** [comment]
This is also due to the missing `PlayerLoader` screen, and should be resolved by #12800.
