### ISSUE TITLE
add score meter type editor

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu#12809]
**Describe the new feature:** 
in mania mode.the "hit error"is too small.It's hard to identify him.
If you put it on the left and right, you can't see it at all for the "Mania" model.
If in the bottom, to tell the truth, the size is very small, and a bit to block the normal play process
maybe can make it freely reorient/resize(add in skin editor).
![1131](https://user-images.githubusercontent.com/52590027/118261951-cd9c9180-b4e6-11eb-8ff5-9dcf326f93ec.png)

**Comment by mas-alone** [comment]
It is not like the stable version, which can be resized freely.

And since the Stable version is actually displayed below the hit position, it doesn't have any effect on normal gameplay.

But in Lazer, at the bottom is the progress bar
![1141](https://user-images.githubusercontent.com/52590027/118262607-b0b48e00-b4e7-11eb-8ae0-998112f534d2.png)

**Comment by peppy** [comment]
Please search first there's countless issues surrounding this, including potential solutions available to you already
