### ISSUE TITLE
Add "Flip" mod for osu!taiko

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu#12812]
this mod would flip dons and kats, as simple as that.

it can be a really nice (and hopefully easy) addition that can keep gameplay fresh and reduce mindblock. Plus it can be good for practicing certain patterns too or for balancing out maps that put more strain on a non-dominant hand for example.

**Comment by Henry-YSLin** [comment]
I would like to try implementing this. Sounds like it's just a slight modification from the random mod, might as well group flip and random into a multi-mod.
