### ISSUE TITLE
Geforce Experience Issue

### ISSUE THREAD

**Issue by XxJimmy122xX** [ppy/osu#12819]
**Describe the new feature:** 
As the game update, it will keep the last two version. Maybe they should get zip up so those game detecting software don't see a lot of osu lol
**Proposal designs of the feature:** 
It make me feel better. 

![螢幕擷取畫面 (118)](https://user-images.githubusercontent.com/25565500/118349181-ba8acf80-b581-11eb-90aa-5389bdb2d147.png)
*A lot of osussss

**Comment by frenzibyte** [comment]
This may be solved once osu!lazer switches to an own update manager instead, but until then, I don't think this will be solved using squirrel.
