### ISSUE TITLE
Game crash when using caps lock in multiplayer screens

### ISSUE THREAD

**Issue by BojayB** [ppy/osu#12818]
I tried looking for this already, so please close asap if this is a clone.

Osu!Lazer version 2021.514.0
OS: Manjaro Linux x86      5.10.34-1-MAN
CPU: Intel Core 2 quad Q8200 2.33GHz
GPU: AMD ATI Radeon R7 240
6 GB Memory

After downloading the latest update, lots of things have been going wrong. When I was looking for my friends lobby, it wasn't there (probably due to him not making it yet) so I decided to make my own lobby. I then exited by accident and created another lobby, then either left again or played a map in said lobby. While playing the map there were some funky glitches, like the audio skipping and teleporting me throughout the song (only forward). The game then crashed. I reopened it hoping everything would be fixed, so I joined my friends lobby and the music that was playing of the selected beatmap was double-time. Pretty sure he had double-time *on*, but while loading into the map the speed changed a few times, then going back into double-time. That map worked fine. The next map my friend put on was laggy for me. Laggy as in it felt like I had accidentally turned up or down my audio offset without realizing. This isn't the case and the map felt mapped properly, but was lagging behind a little bit. We then tried another map I KNEW was mapped properly, it also lagged. My offset settings are at their defaults and this problem hasn't happened before. The game had crashed upwards of three times. The second time the game crashed was because I turned on caps lock (at least that's what happened directly before my game crashed), and the third time multiple "an error has occurred"-like messages appeared saying they were auto sent to the devs. I only caught a photo of the last crash. 

Here are my logs:
[database.log](https://github.com/ppy/osu/files/6482148/database.log)
[network.log](https://github.com/ppy/osu/files/6482149/network.log)
[performance.log](https://github.com/ppy/osu/files/6482150/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6482151/runtime.log)

And this is the screenshot:
![image](https://user-images.githubusercontent.com/41974762/118348591-69df8c00-b519-11eb-942f-aef8abc0c455.png)

I have no *real* idea as to what is actually going on, but I thought it would be important to share, it can't be good and I CAN'T be the ONLY one who's going through this.
Sorry for the vulgarity and if this was long/difficult to read. Trying to be as reproducible as possible.

**Comment by frenzibyte** [comment]
Your logs look to be clean, did you restart the game prior to attaching the logs? if so, please reproduce again and attach the logs before starting the game again.

**Comment by BojayB** [comment]
Nope, I haven't started the game since I took that screenshot.

**Comment by frenzibyte** [comment]
The logs show you've only been at the main menu then exited ~2 minutes later:
```
2021-05-15 04:53:30 [verbose]: Screen changed → Loader
2021-05-15 04:53:31 [verbose]: Screen changed → Disclaimer
2021-05-15 04:53:37 [verbose]: Screen changed → IntroTriangles
2021-05-15 04:53:38 [verbose]: decoupled ruleset transferred ("" -> "osu!")
2021-05-15 04:53:41 [verbose]: Screen changed → MainMenu
2021-05-15 04:55:23 [verbose]: ButtonSystem's state changed from Initial to Exit
2021-05-15 04:55:23 [verbose]: Screen changed ← IntroTriangles
2021-05-15 04:55:26 [verbose]: Screen changed ← Disclaimer
2021-05-15 04:55:26 [verbose]: Screen changed ← Loader
2021-05-15 04:55:26 [verbose]: Screen changed ←
```

It's working completely fine for me and many others (excluding the known bugs https://github.com/ppy/osu/issues/12790 & https://github.com/ppy/osu/issues/12797), so it's gonna be something specific to your device, therefore we need the logs at the time you get the issue in order to investigate further.

**Comment by BojayB** [comment]
Well, I got bored snd started playing again. Useless comment but if it crashes again will post.

**Comment by BojayB** [comment]
There was another update today I downloaded. What seems to happen is every time I use caps lock in multi lobbies my game crashes. Same thing in the first image where notifcations pop up saying there was an error. I haven't opened the game since it crashed

[database.log](https://github.com/ppy/osu/files/6498614/database.log)
[network.log](https://github.com/ppy/osu/files/6498615/network.log)
[performance.log](https://github.com/ppy/osu/files/6498616/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6498617/runtime.log)

**Comment by peppy** [comment]
@smoogipoo i think this may have been resolved via https://github.com/ppy/osu-framework/pull/4471?

**Comment by smoogipoo** [comment]
Should be resolved, yes.
