### ISSUE TITLE
Retrying/quick retrying in a playlist does not work

### ISSUE THREAD

**Issue by bluereflega** [ppy/osu#12815]
**Describe the bug:** Trying to retry or quick retry while playing a beatmap in a playlist does not restart the beatmap and instead takes you back to the playlist screen. The sound effect still plays though.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43960495/118305266-4a952e80-b51a-11eb-96d5-7821ae4444f1.mp4

**osu!lazer version:** 2021.514.0

**Logs:**

[network.log](https://github.com/ppy/osu/files/6480194/network.log)
[runtime.log](https://github.com/ppy/osu/files/6480195/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6480196/updater.log)
[database.log](https://github.com/ppy/osu/files/6480197/database.log)
[performance.log](https://github.com/ppy/osu/files/6480198/performance.log)

**Comment by bdach** [comment]
#12790
