### ISSUE TITLE
Unable to play a single map in playlist mode

### ISSUE THREAD

**Issue by aphelionosu** [ppy/osu#12827]
This is occurred on recent version of osu! (2021.515.0) when the game loads the map that I about to play, the game says "unable to submit score: invalid client hash", and then back to playlist room menu. This happens in every playlist room including the spotlight

Logs:

[performance.log](https://github.com/ppy/osu/files/6487759/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6487760/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6487761/updater.log)
[database.log](https://github.com/ppy/osu/files/6487762/database.log)

**Comment by peppy** [comment]
Could you please try once more?

**Comment by peppy** [comment]
Going to close this as it should be resolved.
