### ISSUE TITLE
Default element location is wrong on skin with both legacy and default elements

### ISSUE THREAD

**Issue by Cryolien** [ppy/osu#12820]
**Describe the bug:**  As title says; the skin I use for osu!mania has legacy and default elements
The default positioning for both DefaultAccuracyCounter and DefaultComboCounter are at the very top left of the screen while DefaultScoreCounter is at the very top, being cut off by DefaultHealthDisplay

**Screenshots or videos showing encountered issue:**  
![Inkedosu_2021-05-15_14-35-39_LI](https://user-images.githubusercontent.com/84220673/118351514-0d1eb880-b58f-11eb-8d42-22c3a8b9d0d1.jpg)
Skin in question: 

[Pray.zip](https://github.com/ppy/osu/files/6483613/Pray.zip)

(I understand I can just move the position anywhere but I just only found out that skinning in game exists; and if someone doesn't know it exists, the position will stay at that position)

**osu!lazer version:** 2021.514.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/6483536/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6483537/updater.log)
[database.log](https://github.com/ppy/osu/files/6483538/database.log)
[network.log](https://github.com/ppy/osu/files/6483539/network.log)
[performance.log](https://github.com/ppy/osu/files/6483540/performance.log)

**Comment by frenzibyte** [comment]
Not really sure if this needs to be fixed here, the fact that legacy skins are using default skin elements is not correct to begin with, they're supposed to fall back to the legacy default instead, which is tracked in https://github.com/ppy/osu/issues/8019.

**Comment by peppy** [comment]
Yep, can be tracked via the existing issue.
