### ISSUE TITLE
Mouse wheel adjusts the volume even if the corresponding binding is removed

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#12822]
**Describe the bug:** 
Setting seems to be ignored
**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/59089206/118354003-a048f580-b571-11eb-956b-9f9424d118e3.mp4
**osu!lazer version:** 
2021.514.0

**Comment by frenzibyte** [comment]
If you're scrolling in an area that doesn't react to a scroll, then the volume will be adjusted instead, that's a natural behaviour regardless of the key binding, not sure if it'll keep existing though, maybe on main menu only.

**Comment by Moltanicaa** [comment]
But removing the key binding is my own initiative. Why not turn it off completely?

**Comment by frenzibyte** [comment]
I'll close this as already tracked in this comment https://github.com/ppy/osu/issues/2238#issuecomment-657848160, which I would agree to and would solve your problem of "scroll shouldn't adjust volume".
