### ISSUE TITLE
`applause` skin sound stops playing after switching to another score in beatmap leaderboard

### ISSUE THREAD

**Issue by Rian8337** [ppy/osu#12823]
**Describe the bug:** 
After finishing a beatmap, viewing another score stops the playback of `applause` skin sound.

This starts happening on `2021.514.0` and it is reproducible with default osu!lazer skin.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/52914632/118357072-67754480-b5a2-11eb-9606-268115c6e6ff.mp4

**osu!lazer version:** 
`2021.515.0`

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6485689/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6485691/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6485693/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6485695/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6485697/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6485698/updater.log)
[database.log](https://github.com/ppy/osu/files/6485699/database.log)
[network.log](https://github.com/ppy/osu/files/6485700/network.log)

**Comment by smoogipoo** [comment]
The sample should probably not be a part of the accuracy circle, but part of the results screen instead. I believe it was only done this way for quick testability during sound design.

**Comment by peppy** [comment]
@smoogipoo are you 100% sure about this direction? the sound effect is one to one coupled with what is happening in the `AccuracyCircle` itself. moving it to the results screen feels like a bad code smell (and breaks testing of this to the point i was confused why no sound effects were playing on `TestScenAccuracyCircle`, where I would expect the applause to be).

**Comment by smoogipoo** [comment]
I'm not tied to my proposal and against doing something different, but do you have a different solution?

**Comment by peppy** [comment]
Note that this has been reverted via #13330. The applause now plays in-line with the accuracy circle's new sound effects. I'm not sure how this will work going forward (depends on how users respond to this change and how much of a "classic" implementation we end up giving the results screen), so I don't think we need to reopen this issue for now; just leaving a paper trail.
