### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by S1n1st3rn3ss** [ppy/osu#12824]
**Describe the bug:** Game is freezing at random after the UI editor update. Can't find any possible cause for it so I assume it is related to the recent update. Had no issues a week ago

**osu!lazer version:** 2021.515.0 and 2021.514.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/6486363/database.log)
[network.log](https://github.com/ppy/osu/files/6486364/network.log)
[performance.log](https://github.com/ppy/osu/files/6486365/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6486366/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6486367/updater.log)

**Comment by peppy** [comment]
We can't work with this information. Nothing has changed which affects performance in recent releases. Please confirm by installing an old build and checking your performance, and come back with actual details (where is performance bad, what is bad, frame logs, who knows)
