### ISSUE TITLE
can I level up on !lazer?

### ISSUE THREAD

**Issue by Al3sKa** [ppy/osu#12838]
**Describe the bug:** 
I checked my rank and played ranked levels and I still can't level up. I played like 12 beat maps and some of them are ranked and stuff but I don't see any progress in my profile. (forgot my old account and stared a new one) I may be wrong or something...
**Screenshots or videos showing encountered issue:** 
![osu_2021-05-16_21-10-55](https://user-images.githubusercontent.com/68668508/118423706-36247380-b68b-11eb-8cf1-f75222c63093.jpg)
**osu!lazer version:** 
2021.515.0

**Logs:**

**Comment by peppy** [comment]
Not yet. This will come in the very near future though.
