### ISSUE TITLE
Google play protect thinks it's a virus

### ISSUE THREAD

**Issue by MattiDeP** [ppy/osu#12835]
Google play protect on my android phone thinks that the OSU APK is a virus
![Screenshot_2021-05-16-11-01-06-503_com android vending](https://user-images.githubusercontent.com/79059837/118391736-2f1f4600-b636-11eb-9570-2ffca1d6fddc.jpg)

**Comment by frenzibyte** [comment]
As long as you downloaded it officially from [here](https://github.com/ppy/osu#running-osu) then it's not a "virus", that's a false positive.
