### ISSUE TITLE
Game goes weird when maps stops

### ISSUE THREAD

**Issue by gabixdev** [ppy/osu#1284]
I don't know what's causing that, but when music ends and there is only one beatmap osu goes crazy, triangles in logo are moving rapidly, game is buggy and other weird things happen...

That only map I have is Soleily - Renatus from ppy/osu-resources

**Comment by peppy** [comment]
- Explain what "game is buggy" means
- Explain what "other weird things happen"
- Please ensure and confirm you're on the latest master, and this was fixed once already (https://github.com/ppy/osu/pull/1243)

**Comment by gabixdev** [comment]
I'm using latest master built with Mono 5.2.0.215 from Ubuntu 17.04
```
Mono JIT compiler version 5.2.0.215 (tarball Mon Aug 14 15:46:23 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

- Triangles in osu! logo are moving rapidly (i don't have screen recorder to record it)
- Player can't play/rewind music
- When starting gameplay it stays black (http://i.imgur.com/zZyYBbA.png)
- No stacktraces etc. are printed

**Comment by swoolcock** [comment]
You sure it's not related to this?
https://github.com/ppy/osu/pull/1243
If so, I have another change stashed that might help.  It ignores channel levels while the track is paused.

**Comment by Kontorted** [comment]
I can affirm that the rapid triangles is an issue, though it seems related to when audio devices are not found. @swoolcock has referenced an issue, which will hopefully address the issue correctly.
