### ISSUE TITLE
Add skin layout customisation per ruleset

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#12871]
**Describe the new feature:** 

Not sure if this is the same approach as #6124, since that opened issue wants to select a different skin for each ruleset, but this one aims to customize just one skin (with the skin editor) for each ruleset separately.

The idea is to save the skin editor configs in a per-ruleset way, since every ruleset is different and every ruleset uses different space in the gameplay field.

For example: (images taken from a guy on twitter)

![E0JRSgAUcAAfLl3](https://user-images.githubusercontent.com/41755816/118831418-c3371a80-b88d-11eb-9989-f373c80d5f59.jpg)
![E0JRSgAUcAEG0en](https://user-images.githubusercontent.com/41755816/118831421-c3cfb100-b88d-11eb-898a-305223714d73.jpg)

**Comment by frenzibyte** [comment]
Pretty similar scope and that issue already mentions "skin settings", but I guess this can stay open since it's focusing on the "saving" part.

**Comment by peppy** [comment]
Converting this to an epic to track the increasingly important requirement of having per-ruleset layouts.

This could be used to solve issues like:
- https://github.com/ppy/osu/issues/21949
- https://github.com/ppy/osu/issues/20422
- https://github.com/ppy/osu/issues/22362

It would both allow for applying per-ruleset defaults, and give users the option to further customise from those defaults. There should also likely be facilities in the editor to copy full layouts between rulesets (maybe not required if we have clipboard support).

**Comment by peppy** [comment]
Scratch that, I'll open a new issue to keep things tidy.
