### ISSUE TITLE
Mods not working

### ISSUE THREAD

**Issue by ymmit64** [ppy/osu#1287]
When testing mods I noticed that flashlight, suddendeath, perfect, hidden, relax (sometimes misses when shouldn't), auto-pilot, and target practice dont't work. I was testing these mods on Everything will freeze - undead corporation. I am using the latest version - 2017.915.1

**Comment by jai-sharma** [comment]
The osu! lazer client is still under heavy development, and while good progress is being made, it is still not fully feature complete. In the future please refer to the main client to-do list to see what has been implemmented and what hasn't.

https://github.com/ppy/osu/issues/988
