### ISSUE TITLE
Increase beatmap difficulty limits up to 11

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#12873]
**Describe the new feature:** 
AR9 + DT = AR10.3
Playing with this AR is almost a separate skill, which is why simply AR 10 seems insufficient. Is it possible to give an opportunity to set for a map at the time of creation (not difficalty adjust) above 10?

**Comment by frenzibyte** [comment]
Not sure this will really happen given that any difficulty value beyond 10 is considered "extreme mode" here, but I guess this can stay as a proposal.

**Comment by smoogipoo** [comment]
From my experience, mappers don't jack up the AR for the sole purpose of increasing the skill requirement, and I really doubt they would if this was implemented. It's more commonly used to reduce density as a result of higher BPM to acceptable levels.

As I've mentioned in the past, AR>10 is really not a special skill by itself.
