### ISSUE TITLE
Ability to remove/add combo numbers in catch above the plate

### ISSUE THREAD

**Issue by Kimitakari** [ppy/osu#12887]
Because of the new implemented skin editor no longer needed to use combo numbers on taiko inside the drums or in mania above the judgement line, in catch for some reason it uses 2 combos. One on the bottom left of the screen and another above the plate.

However instead of removing both it only removes the bottom left only and not the one above the plate as shown in this video.

https://user-images.githubusercontent.com/36848514/118972370-29e53280-b979-11eb-9472-2d1ad1b5775b.mp4

**Comment by bdach** [comment]
#12791
