### ISSUE TITLE
[Bug report] Database map import error for specific maps only

### ISSUE THREAD

**Issue by Hexality** [ppy/osu#12899]
**Describe the bug:** 
osu!lazer refuses to import some specific maps and ends up throwing me FOREIGN Key error. But besides this, osu!lazer imports every single other map except some maps like [ダダダダ天使 (dadada tenshi)](https://osu.ppy.sh/beatmapsets/1394839#osu/2879115) from [_Miiyuki](https://osu.ppy.sh/users/11707999)
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/17398632/119211925-95b7c000-ba8b-11eb-9f23-4a5cb04668fa.mp4

**osu!lazer version:** 
2021.515.0
**Logs:**
[network.log](https://github.com/ppy/osu/files/6525684/network.log)
[performance.log](https://github.com/ppy/osu/files/6525686/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6525687/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6525688/updater.log)
[database.log](https://github.com/ppy/osu/files/6525689/database.log)

**Comment by peppy** [comment]
Could you please attach your database file (`client.db`)? Thanks in advance.

**Comment by Hexality** [comment]
[client.db](https://a.cockfile.com/koWrkt.db)

**Comment by peppy** [comment]
The provided download link does not work.

**Comment by Hexality** [comment]
File expired, its only 1 day limit, but the last update of the game fixed it ao thx anyways. If you still want the db file let me know.
