### ISSUE TITLE
Discord rich presence should show current game mode rank

### ISSUE THREAD

**Issue by adryzz** [ppy/osu#12898]
As of now, the discord rich presence shows current game mode, what the user is doing, and his rank
![image](https://user-images.githubusercontent.com/46694241/119197369-e9280f00-ba87-11eb-868f-9eb2158371f8.png)

The rank shown however, does not reflect the current game mode that is being played, but it shows only osu!std
https://github.com/ppy/osu/blob/51e52fffd86347dbdb16c1420d1b3df13debfb1b/osu.Desktop/DiscordRichPresence.cs#L108

Lazer version: 2021.515.0

**Comment by frenzibyte** [comment]
Was taking a quick look at getting this one, but seems currently there's no way to get the local user statistics based on the current ruleset. 

One quick way I can think of is making an `IAPIProvider.LocalUserStatistics` and update it based on ruleset changes by refetching via `GetUserRequest()` (with caching and debouncing), but would like to hear if that's fine to do, not sure myself.

**Comment by LittleEndu** [comment]
If such caching is implemented, note that there are other components (well, looks like just `DifficultyRecommender`) that would benefit from it as well.

**Comment by smoogipoo** [comment]
Is this the way such a thing is done? I thought we had another way to do it that was implemented recently via `User.RulesetsStatistics`.

**Comment by frenzibyte** [comment]
The `User.RulesetStatistics` thing is only on `User`s from `UserCompact` responses (i.e. `GetUsersRequest`), if osu!web can also make it exist in regular `User` responses (`GetUserRequest`/`GetFriendRequest`), that would be another good way to support this.
