### ISSUE TITLE
Pressing the reset buttons on dropdown settings causes weird behaviours.

### ISSUE THREAD

**Issue by SleepySwords** [ppy/osu#12896]
**Describe the bug:** Pressing the reset button of a dropdown setting, then opening it results in scrolling without any input. 
Also pressing the reset button while the dropdown setting is also opened doesn't fade the change.

**Screenshots or videos showing encountered issue:** https://youtu.be/HFGuBu6UZsk

**osu!lazer version:** 2021.515.0

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/6522212/performance.log)
[network.log](https://github.com/ppy/osu/files/6522213/network.log)
[database.log](https://github.com/ppy/osu/files/6522214/database.log)
[runtime.log](https://github.com/ppy/osu/files/6522215/runtime.log)

**Comment by MyDogsEd** [comment]
This must've been fixed at some point, no longer an issue on 2022.217.0-lazer.
