### ISSUE TITLE
Replays incorrectly show mistimed taps

### ISSUE THREAD

**Issue by IsaacElenbaas** [ppy/osu#12891]
**Describe the bug:**
Multiple replays occasionally show notes being tapped much earlier or later than they actually were. No noticeable game stutters occurred during play or recording of replay. Accuracy displayed before the results screen does not match the result screen accuracy.

**Screenshots or videos showing encountered issue:**
From what I remember, ~the first half was very clean, and many of the errors occur there. They are extremely obvious, especially if one watches the hit error meter. The stream around 0:39, just after one of the errors, also feels mistimed.
[Video](https://youtu.be/3UVHGumzAfs)
[Replay file](https://github.com/ppy/osu/files/6519752/Kerotoric.playing.Umeboshi.Chazuke.%2B.Chroma.-.Omoide.Note.Azzedd.Extra.zip) (renamed to `.zip` from `.osr`, *not* actually zipped)

**osu!lazer version:** `2021.502.0-1`

**Logs:** 
[database.log](https://github.com/ppy/osu/files/6519740/database.log)
[network.log](https://github.com/ppy/osu/files/6519741/network.log)
[performance.log](https://github.com/ppy/osu/files/6519742/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6519744/runtime.log)

**Comment by peppy** [comment]
Is there any reason you're on such an old release?

**Comment by IsaacElenbaas** [comment]
Duplicate of #12760, I checked open issues but not closed ones :man_facepalming:

**Comment by IsaacElenbaas** [comment]
Updating did fix it. I thought I had updated two days ago, as I was setting up a laptop and reworking my current system as I did it, and didn't think to try after checking for duplicate issues.
