### ISSUE TITLE
`DrawableSliderTail` unnecessarily implements `ITrackSnaking`

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#12902]
**Describe the bug:** 
Because the slider tail is always at the end of the slider and is drawn after the slider has already snaked in, it has no reason to track snaking. Some other method to set its position should be more appropriate.

Not to be confused with `OsuSkinComponents.SliderTailHitCircle` that is drawn for both `DrawableSliderTail` and `DrawableSliderRepeat` where the repeat already correctly follows snaking in all cases.

(I was looking over my previous PRs and remembered [this comment](https://github.com/ppy/osu/pull/8486#issuecomment-605551650) that slider tails need to consider their hit status when snaking, but after looking into it I discovered this issue instead)

**osu!lazer version:** 
2021.515.0
master is at a8acbbe69cbc31cb6e39c3fad4b5dbdbb460117e

**Comment by smoogipoo** [comment]
I'm deprioritising this since it's just a code quality improvement.
