### ISSUE TITLE
osu!lazer the exception unknown software exception application error 

### ISSUE THREAD

**Issue by avendurree23** [ppy/osu#12905]
I've been playing osu!lazer over the years on different hardware. Couple of months ago, I bought a new CPU Intel Xeon E5 2620 v3, x99 motherboard and also 16GB RAM and SSD. My GPU remained GTX 750TI, until recently I got GTX 960, but I still cant even launch the game ever since I got the CPU.

Everytime I launch the game, this appears:

![Capture](https://user-images.githubusercontent.com/29961163/119230108-79fff880-bb23-11eb-8039-3ef86c9be1e2.PNG)

What I tried:
-running with admin and win7 compatibility
-running almost each osu!lazer versions since march
-installing various drivers
-installing net runtime, vredist stuff 

osu! stable works fine, but I've gotten used to osu!lazer and I dont know how to fix this...

[performance.log](https://github.com/ppy/osu/files/6526590/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6526591/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6526592/updater.log)
[database.log](https://github.com/ppy/osu/files/6526593/database.log)

**Comment by frenzibyte** [comment]
Looks to be your database file failing, rename it / move it away (`%appdata%/osu/client.db`), and attach it here so we can investigate further on it.

**Comment by peppy** [comment]
The database is malformed. Please delete it and it will fix your issue.
