### ISSUE TITLE
Legacy Skinning Elements Being Placed Ontop Lazer Skinning Elements by Default

### ISSUE THREAD

**Issue by MLisDreaming** [ppy/osu#12907]
**Describe the bug:** 
By default, the skinning element **LegacyComboCounter** is placed directly ontop of the skinning element **SongProgress** in Legacy Skins (including osu!classic). This makes it hard to read both and makes it near impossible to see the time progressed through the current map.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/43427333/119234665-b405d600-baf4-11eb-8a35-2de569aaa026.png)

**osu!lazer version:**
osu!lazer 2021.523.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6526829/database.log)
[network.log](https://github.com/ppy/osu/files/6526830/network.log)
[performance.log](https://github.com/ppy/osu/files/6526831/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6526832/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6526833/updater.log)

**Comment by frenzibyte** [comment]
The legacy combo counter is placed perfectly fine, the issue here is that the `SongProgress` does not have the legacy variant supported yet, which is tracked under #10945.

**Comment by peppy** [comment]
Are you sure? This sounds like a major regression.

**Comment by MLisDreaming** [comment]
Then should I be concern about this stacking I just noticed? (am I the only one seeing this)
![image](https://user-images.githubusercontent.com/43427333/119235065-45c21300-baf6-11eb-80b5-683b902d35e1.png)

**Comment by frenzibyte** [comment]
> Are you sure? This sounds like a major regression.

Right, I responded based on the attached image only, haven't actually checked the game...

**Comment by peppy** [comment]
The attached image shows the precise issue.

**Comment by MLisDreaming** [comment]
After further testing, I don't think legacy skins are at fault. This also happens to osu!lazer's default skin. (unless you uses some legacy skin stuff. I don't know C# so I can't help directly unfortunately, this is the best I can do)

**Before 2021.523.0**
![image](https://user-images.githubusercontent.com/43427333/119236226-e109b700-bafb-11eb-8415-c8a61f2ff012.png)
**2021.523.0**
![image](https://user-images.githubusercontent.com/43427333/119236201-c59eac00-bafb-11eb-990f-239424fdccf5.png)
