### ISSUE TITLE
news sidebar doesn't let you scroll to the bottom when multiple dropdowns are expanded

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#12906]
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43358824/119233184-03192e80-bb28-11eb-9eeb-76c10f909d4c.mp4

**osu!lazer version:** 
2021.523.0

**Comment by frenzibyte** [comment]
Probably should be done like in osu!web:

https://user-images.githubusercontent.com/22781491/119233244-c69e0080-bb30-11eb-872a-dd8b1d4c2d2d.mp4

Would imagine it being that the news sidebar scroll container stops blocking scrolls when it reaches it's limits, and the scroll will be propagated to a parent main controller that scrolls the entire overlay content (both sidebar and the page itself).

**Comment by peppy** [comment]
The scroll control transfer to the main container is not required. That's just an implementation quirk.

**Comment by EVAST9919** [comment]
Or we can probably make sidebar height match free area instead of it being full height (?)

**Comment by peppy** [comment]
Please don't, that looks *really* broken.

**Comment by EVAST9919** [comment]
This is how it looks with web-like behavior:
https://streamable.com/k9kyyh

**Comment by smoogipoo** [comment]
That looks fine
