### ISSUE TITLE
Continue Glitch With Mouse Buttons Off

### ISSUE THREAD

**Issue by gamerturtlepoggers** [ppy/osu#12901]
**Describe the bug:** 
When you click retry in the pause menu, if you have mouse buttons disabled (as I do) you can't click the orange circle to continue the map. A lot of players have mouse button disabled so pausing the game and continuing can be really annoying.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:**

**Comment by frenzibyte** [comment]
- What type of platform are you encoutering this on?
- What type of input device are you using? (mouse? tablet? touchscreen?)

**Comment by gamerturtlepoggers** [comment]
Tablet

**Comment by gamerturtlepoggers** [comment]
osu lazer

**Comment by frenzibyte** [comment]
To clarify, are you trying to resume gameplay by tapping the orange circle with your tablet stylus? you should do it by pressing the game key bindings (Z/X or how you have it)?

And if that's the case, then this is not an issue, but an intended behaviour given you intended to disable mouse buttons from interrupting your gameplay.

**Comment by gamerturtlepoggers** [comment]
oh sorry I was being stupid my instict was just clicking it with my tablet
