### ISSUE TITLE
Select key count of a mania map in the lazer editor

### ISSUE THREAD

**Issue by myl7** [ppy/osu#12904]
Option to configure key count (to set 4k, 5k, 7k, for example) in the setup page for mania mode of osu!lazer edtior. Currently the lazer editor only support 5k mapping for mania mode (correct me if I am wrong).

Just in my opinion this is truely an important feature, to let mappers get the key count they want. I have searched the web to find if there is already a option doing this, ending up only found [the Reddit answer](https://www.reddit.com/r/osugame/comments/kagjoy/how_to_change_amount_of_keys_used_for_an_osumania/gfdurcw/) .

**Comment by frenzibyte** [comment]
You *can* change the key count of a mania map by changing the "object size" setting then saving the beatmap and opening editor again.

However, the drawable ruleset should probably update on changes to that setting (which would later properly display as "key count").

**Comment by XahnmX50** [comment]
thanks it worked

**Comment by bdach** [comment]
The "circle size" slider in mania editor has been renamed to match purpose. Mind you, the changes still will not apply until a full editor reload, but let's track that as part of #17127.

**Comment by ViRiXDreamcore** [comment]
> The "circle size" slider in mania editor has been renamed to match purpose. Mind you, the changes still will not apply until a full editor reload, but let's track that as part of #17127.

I'm on the August 03 build and it still says "circle size". I'm using the Mac build though, so maybe it just wasn't changed there?

**Comment by bdach** [comment]
@ViRiXDreamcore change hasn't been deployed yet, please wait for next release. 2023.803.0 was a hotfix that did not include this.
