### ISSUE TITLE
Hold-for-menu button may crash when pressing exit key if it's masked away

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#12919]
**Describe the bug:** Moving bottom anchor progress bar cause key stroke and back button move. If back button go out of screen, press back is not possible (quick retry then back still work.)

If trying to move item back after failed attempt to back. The game crash.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/7066150/119265770-0daff280-bc12-11eb-8f35-5801699821ba.mp4

**osu!lazer version:** 2021.523.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6528294/database.log)
[network.log](https://github.com/ppy/osu/files/6528295/network.log)
[performance.log](https://github.com/ppy/osu/files/6528296/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6528297/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6528298/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6528299/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6528300/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6528301/updater.log)

**Comment by frenzibyte** [comment]
You should not move bottom-anchored elements to the top, but instead, change their anchor according to where you want to place it.

Closing as not an issue.

**Comment by frenzibyte** [comment]
Nevermind, I misunderstood your intention behind this issue, which is that the HUD hold-to-exit button doesn't behave properly when out of screen, while rename the title to indicate that properly.
