### ISSUE TITLE
Game wont even lauch.

### ISSUE THREAD

**Issue by TosteRowe** [ppy/osu#1291]
Hello there.I have problem with osu!lazer.It keeps crashing when trying to startup.No log is being created.When i startup the game its black screen then it crashes.

I'm waiting for quick answer from you guys. :)

**Comment by Kontorted** [comment]
Did you even build properly? Are you running the EXE straight from explorer, or are you trying it from within the VS environment? Alternatively, are you using the latest release?
These are debug builds, and pre-releases. They are NOT meant to work properly, as Lazer is still in-development. If you can't run it, try building the latest code updates, cross your fingers, and pray to peppy (or just wait for the full release :/)
