### ISSUE TITLE
Pipewire - Triangles intro is broken

### ISSUE THREAD

**Issue by yellowsink** [ppy/osu#12913]
**Describe the bug:** 
When the game is started, it will reach the disclaimer, but then stop at a black screen. It does not freeze nor crash.

This does not affect the Circles intro, though due to either pipewire or alsa exclusive mode (not 100% sure), sound does not play on default. I would assume this sound configuration is also the cause of Triangles breaking, as after fixing it Triangles works fine.

**Screenshots or videos showing encountered issue:** 
Video showing issue with Triangles + fix using Circles.
https://youtu.be/-mN3s1aKOs4

**osu!lazer version:** 
2021.515.0 - tested issue occurring on latest but not the "fix"

**Logs:**

[logs.zip](https://github.com/ppy/osu/files/6527835/logs.zip)

**Comment by Game4all** [comment]
From the looks of this, this looks like to be another instance of ppy/osu-framework#3297.

**Comment by yellowsink** [comment]
oh maybe. I probably should have checked osu!framework issues too actually :\
