### ISSUE TITLE
Game hiding Progress Bar in edited skins, ignoring the enabled option to display it 

### ISSUE THREAD

**Issue by Bryceed** [ppy/osu#12911]
**Describe the bug:**
The game are not showing the progress bar on in-game edited skins (with merge #12845), ignoring config., but it still displaying in legacy (with gliches, as reported on the #12907)

![12d89b1b-2c7b-45a4-a1f4-685f2ea5514e](https://user-images.githubusercontent.com/42657376/119248314-b6087d00-bb66-11eb-8ea2-67dcbf5f503a.png)
So, this option don't makes sense (no more), if the **game will not respect the player's choice** to display it

> 💡 **Suggestion:** Change this checkbox option to a dropdown with "_Always display_", "_Display with supported skins (default)_", "_Don't display on legacy skins_" and "_Never display_" options, or something like.

**Screenshots or videos showing encountered issue:** (_mod x legacy_)
![image](https://user-images.githubusercontent.com/42657376/119249332-164eed00-bb6e-11eb-8fca-190a7a94492a.png)
![image](https://user-images.githubusercontent.com/42657376/119249500-5fec0780-bb6f-11eb-8196-73e90468b7f3.png)

**osu!lazer version:** 2021.523.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6527594/database.log)
[network.log](https://github.com/ppy/osu/files/6527595/network.log)
[performance.log](https://github.com/ppy/osu/files/6527596/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6527597/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6527598/updater.log)

**Comment by peppy** [comment]
I think you may be misunderstanding that option. It's not intending to hide it. It just changes the height of it.

**Comment by peppy** [comment]
I've tried to find any weirdness that could be relevant to the issue but can't seem to. Waiting for further information.

**Comment by LittleEndu** [comment]
I think this happens when upgrading from 2021.515.0 to 2021.523.0:



https://user-images.githubusercontent.com/11320483/119267201-30341280-bbf6-11eb-970c-e1699e843a10.mp4

**Comment by peppy** [comment]
This is intended behaviour, as you customised the skin. Revert to defaults.

**Comment by LittleEndu** [comment]
The skin that got saved in 515 had progress bar and one in 523 doesn't. How can this be intended?

**Comment by peppy** [comment]
As per the changelog notes, the progress bar is now a customisable element.

Because this is a new system we are not offering migrations for each change so it is up to you to revert to get newer changes.
