### ISSUE TITLE
Scale the rotated items in single axis cause it to scale diagonally.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#12920]
**Describe the bug:** Scale the rotated items in single axis cause it to scale diagonally.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/7066150/119266548-6e8cfa00-bc15-11eb-8b56-cdc97d660181.mp4

**osu!lazer version:** 2021.523.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6528350/database.log)
[network.log](https://github.com/ppy/osu/files/6528351/network.log)
[performance.log](https://github.com/ppy/osu/files/6528352/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6528353/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6528354/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6528355/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6528356/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6528357/updater.log)

**Comment by bdach** [comment]
[Was explicitly intended](https://github.com/ppy/osu/pull/12866#issuecomment-845681018), at least for now. For it to work how you want, the selection box would have to rotate with the element and not always stay upright.
