### ISSUE TITLE
Clicking while a chat message is being sent breaks input

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#12936]
**Describe the bug:** 

Clicking any mouse button right after sending a chat message breaks input.
Breaks with any message, even with `/help`

When input is broken in this way, every input event (keyboard press, mouse click, scrollwheel...) causes an unhandled error to occur.

**Repro steps:**

1. Open chat
2. Type a message and press enter
3. Click as soon as you can (doesn't matter where you click, nor which button is pressed)
4. Input is now broken

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/16479013/119358168-a98c3d80-bca8-11eb-8b47-7d538d99a3e7.mp4

**osu!lazer version:** 2021.523.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/6532808/network.log)
[performance.log](https://github.com/ppy/osu/files/6532809/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6532810/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6532811/updater.log)

**Comment by ekrctb** [comment]
The crash is same as #11511.

**Comment by smoogipoo** [comment]
Closing as duplicate.
