### ISSUE TITLE
separate hitsounds from skins

### ISSUE THREAD

**Issue by firinael** [ppy/osu#12937]
**Describe the new feature:** the idea is separating hitsounds from skins entirely -- instead allowing for the creation of hitsound sets, which would be swappable as skins are right now.

Skins at the moment include hitsounds as well as elements. This means that, if you want to switch hitsounds, you have to create a copy of your skin *specifically* so that it has another set of hitsounds (and this means that it's very likely that some unintended hitsounds will slip unnoticed). That, in turn, means that you might end up having up to 4 or 5 variants of the same skin, and the only difference between them all is the hitsounds they use (which means lots of clutter in the skins list).

Not only that, but the biggest issue that comes from hitsounds and skin elements being merged is: you have multiple skins for different hitsound sets, and want to edit something related to the visuals of the skin -- _now you have to go to each one and edit the same thing several times._

This feature would allow for a much better experience for people that like editing their skins, and would make switching hitsounds _so much simpler_.

Anyway, thank you for the good work!

**Comment by peppy** [comment]
We already have plans to allow copying / customising subsets of skin elements you want to use. It's part of a larger skin customisation system which will be coming. Will close this issue as I don't believe we need another one tracking that task (which is already on our roadmap / tracked via skinning issues).

**Comment by firinael** [comment]
alright, thank you for taking the time to explain!

**Comment by leg7** [comment]
@peppy Could you reconsider adding this feature? I just thought about it today when I changed to a skin I liked visually but one where I didn't like the hitsounds.
