### ISSUE TITLE
Consistent game crash by repeatedly selecting broken game mode

### ISSUE THREAD

**Issue by CenTdemeern1** [ppy/osu#12932]
**Describe the bug:** 
You can consistently crash the game by repeatedly clicking a ruleset that isn't selectable due to it failing (see screenshot)

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/24682280/119343081-409bca00-bc96-11eb-95be-9911d5c64b4f.png)

https://www.youtube.com/watch?v=M7NEA3JdTyw

**osu!lazer version:** 
osu!lazer 2021.523.0

**Logs:**

[network.log](https://github.com/ppy/osu/files/6532091/network.log)
[performance.log](https://github.com/ppy/osu/files/6532092/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6532093/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6532094/updater.log)
[database.log](https://github.com/ppy/osu/files/6532095/database.log)

**Comment by PercyDan54** [comment]
Update the ruleset to follow #12811

**Comment by CenTdemeern1** [comment]
> Update the ruleset to follow #12811

Right, I'll check if there is an update.
My problem still stands though, since this suddenly crashes the game.
The error isn't being caught.

**Comment by CenTdemeern1** [comment]
I'll be a bit more clear about what I mean:
I get that I need to update my rulesets, which I'm doing right now
But I feel like errors like this need to be caught

**Comment by PercyDan54** [comment]
Maybe needs further discussions on if we should add back the implementions in `ModHidden`

**Comment by frenzibyte** [comment]
This does not need any further discussion, ruleset loading errors should be handled properly instead of potentially crashing the game as shown in the OP.

**Comment by peppy** [comment]
This is intentional behaviour for now. If you trigger unhandled exceptions too fast (by clicking repeatedly) the game *will* crash.

Eventually we will have a more graceful system in place for hard denying rulesets which aren't built for the correct version, but for now the onus is on you.
