### ISSUE TITLE
Mod display padding is missing

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#12931]
**Describe the bug:** 
Mod display is overlapping with score/health display. Accuracy display is misplaced
Broken in the recent build

**Screenshots or videos showing encountered issue:** 
![osu_2021-05-24_19-16-28](https://user-images.githubusercontent.com/50285552/119340138-b028ae00-bcc4-11eb-88c6-49291cbec0f0.jpg)

**osu!lazer version:** 
2021.523.0

**Logs:**
Not needed

**Comment by Game4all** [comment]
This should be fixed in the next release after the merge of #12917.

**Comment by frenzibyte** [comment]
The accuracy part sounds wrong, what do you mean by it misplaced, can you attach the skin please?

**Comment by PercyDan54** [comment]
> The accuracy part sounds wrong, what do you mean by it misplaced, can you attach the skin please?
Rename to osk

[PercyDan Mix.zip](https://github.com/ppy/osu/files/6532004/PercyDan.Mix.zip)

**Comment by PercyDan54** [comment]
> The accuracy part sounds wrong, what do you mean by it misplaced, can you attach the skin please?

The accuracy seems displayed a bit below stable's position
![screenshot001](https://user-images.githubusercontent.com/50285552/119342214-4eb60e80-bcc7-11eb-975b-7073893edf5d.jpg)

**Comment by peppy** [comment]
Looks close enough to me. If you want you can reposition it yourself using the layout editor.

You're not going to get it matching perfectly because your skin is using dodgy hacks to get it centered, which don't work in lazer.
