### ISSUE TITLE
osu!lazer tablet driver problem

### ISSUE THREAD

**Issue by z0rfix** [ppy/osu#12935]
I cant play osu!lazer with my tablet. When I try to slide the pen across the tablet, the cursor turns pink and hangs in one place.
( I tried to turn off / on some settings but it's doesn't help )
Tablet XP-PEN Deco Mini 4
Tablet driver version [1.6.4]

Video link: https://www.youtube.com/watch?v=DY9pAqlD0jc

**Comment by peppy** [comment]
Check opentabletdriver issues or search here.

It's likely related to windows ink or an upstream issue.

If you don't understand this then just wait and it will probably eventually be fixed.

**Comment by itrTie** [comment]
On my CTL-472, I went into my tablet properties and un-checked "Use Windows Ink".  I've never had an XP-PEN, but there should be an option to do this somewhere.
