### ISSUE TITLE
Some sort of Shape Palette for the Editor

### ISSUE THREAD

**Issue by Ezius** [ppy/osu#12941]
**This feature is not a high priority just a small quality of life feature that was probably already proposed**

**Describe the new feature:** 
After pressing a shortcut, a window or something similar _(your palette)_ should appear where you can copy several map sections _(like complex sllider shapes with some circles afterwards, or 4 circles in a square and 1 in the middle)_ that you have saved previously into your palette, so that you dont have to wind back to something you previously mapped and copy the section and then wind forward again.
It would also be cool if you could choose that some patterns in your palette are usable between different beatmaps.

The saving of the section into your palette should also work with a shortcut to make it quick.

I hope you understand what I was trying to say, it was just a simple thought I had in my mind while watching some of Pishifats videos

**Comment by frenzibyte** [comment]
Sounds relevant to https://github.com/ppy/osu/issues/8773, if not a duplicate.

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/8773
