### ISSUE TITLE
Disabling "Show difficulty graph on progress bar" still shows the difficulty graph underneath regular bar

### ISSUE THREAD

**Issue by Azzirah** [ppy/osu#12940]
**Describe the bug:** While testing out the skin editor, i noticed that disabling "Show difficulty graph on progress bar" only hides it below the simple progress bar, making it visible again when moved elsewhere.

**Screenshots or videos showing encountered issue:** 
![osu_2021-05-24_18-10-47](https://user-images.githubusercontent.com/65025784/119376300-13faa900-bcbc-11eb-8996-9d128c047dc3.jpg)

**osu!lazer version:** 2021.524.0

**Comment by peppy** [comment]
This is because the hiding is done in a simple/high performance way. You can temporarily avoid this by not moving it upwards, or not toggling it.

**Comment by Hexality** [comment]
here the same thing is happening

https://user-images.githubusercontent.com/17398632/127361635-46fb2a5a-c8a6-4654-b6d3-6227faeab4ab.mp4

**Comment by Hexality** [comment]
btw, just to not open another issue for now, I would ask here if will there be support for moving elements precisely using the arrow keys in the future

**Comment by smoogipoo** [comment]
Please make another issue, it can be done.
