### ISSUE TITLE
Cannot make a new account OsuLazer

### ISSUE THREAD

**Issue by CharlesAce2000** [ppy/osu#12955]
**Describe the bug:** 
When making new account gaves me an error, also a friend of mine tried to log in but nothing.

I really want to play but this error won't let me
**Screenshots or videos showing encountered issue:** 
![WhatsApp Image 2021-05-25 at 4 55 29 PM](https://user-images.githubusercontent.com/84813670/119567229-102d5c00-bd7a-11eb-8df6-305e89a2aabc.jpeg)

![WhatsApp Image 2021-05-25 at 8 45 48 PM](https://user-images.githubusercontent.com/84813670/119586268-5a263a00-bd9a-11eb-8faa-cbec6579b29d.jpeg)

**osu!lazer version:** 

**Logs:**
[database.log](https://github.com/ppy/osu/files/6542372/database.log)
[network.log](https://github.com/ppy/osu/files/6542373/network.log)
[performance.log](https://github.com/ppy/osu/files/6542374/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6542375/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6542376/updater.log)

**Comment by frenzibyte** [comment]
Logs please, as stated in the issue template:
![image](https://user-images.githubusercontent.com/22781491/119567484-0e34be80-bdb5-11eb-9923-93c305f517ef.png)

**Comment by peppy** [comment]
You are being blocked by cloudflare likely due to your OC being compromised.

Visit the osu! site and complete the captcha.

**Comment by CharlesAce2000** [comment]
How can I do this?
