### ISSUE TITLE
Osu Lazer Just doesnt wanna Open

### ISSUE THREAD

**Issue by Palxz** [ppy/osu#12956]
Ok probably someone alredy had this issue but when i touch the osu! lazer direct acces it doesnt open just as if i didnt click it i also tried opening the exe directly and still nothing.
Some times it open tho i dont know why its only somethimes.
it sayed that i should upload logs and idk wich one is it so just gonna upload everything
[network.log](https://github.com/ppy/osu/files/6543267/network.log)
[performance.log](https://github.com/ppy/osu/files/6543268/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6543269/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6543270/updater.log)
[database.log](https://github.com/ppy/osu/files/6543271/database.log)
Ok also idk my osu lazer version but i think it should be the last.
i can also give my pc specs if needed
https://prnt.sc/13f4ned
srry for the inconvinience
also sorry for bad english im actually spanish native.

**Comment by frenzibyte** [comment]
I'm not sure *when* was the last time you successfully started the game, but the logs you attached are from May 15th, almost 2 weeks old from now.

**Comment by Palxz** [comment]
ye that is right its been almost like 2 weeks since my last start

**Comment by Palxz** [comment]
what details u need exactly?

**Comment by peppy** [comment]
You'll need to look into event viewer for osu!-related errors.

**Comment by frenzibyte** [comment]
Here are the steps in case you need, you can then attach the saved file here:

https://user-images.githubusercontent.com/22781491/119592849-eb6ccf00-bde1-11eb-9378-ad2e23597c86.mp4

**Comment by Palxz** [comment]
also aparently i tried reading it and this is the error?

A .NET application failed.
Application: osu!.exe
Path: C:\Users\faceb\AppData\Local\osulazer\app-2021.514.0\osu!.exe
Message: Cannot use file stream for [C:\Users\faceb\AppData\Local\osulazer\app-2021.514.0\osu!.deps.json]: No such file or directory
Failed to create CoreCLR, HRESULT: 0x80004005

**Comment by Palxz** [comment]
also i tried using another version that was in the local/osulazer/ and aparently it does work so the error is in the app-2021.514.0 folder?

**Comment by peppy** [comment]
Relevant portion of event viewer log:

```csharp
Description: A .NET application failed.
Application: osu!.exe
Path: C:\Users\faceb\AppData\Local\osulazer\app-2021.514.0\osu!.exe
Message: Cannot use file stream for [C:\Users\faceb\AppData\Local\osulazer\app-2021.514.0\osu!.deps.json]: No such file or directory
Failed to create CoreCLR, HRESULT: 0x80004005
```

This looks like your install was missing a file. Could you try reinstalling lazer (without uninstalling first) and see if it resolves your issue?

**Comment by zekroman** [comment]
I think i have a similar issue, i did check in the Event Viewer, and it says that KERNELBASE.dll is missing, which is apparently requires to run, and yes, i have already installed the latest build thinking it was a small bug from version 612, so i have no idea why is it giving me this error.

**Comment by bdach** [comment]
If "`KERNELBASE.dll` is missing" then your system

**Comment by zekroman** [comment]
i may be misquoting then, because it's hard to translate the event viewer for me, but it says that the module failed

**Comment by zekroman** [comment]
> - <System>
> 
>   <Provider Name="Application Error" /> 
>   <EventID Qualifiers="0">1000</EventID> 
>   <Version>0</Version> 
>   <Level>2</Level> 
>   <Task>100</Task> 
>   <Opcode>0</Opcode> 
>   <Keywords>0x80000000000000</Keywords> 
>   <TimeCreated SystemTime="2021-06-18T18:24:04.3461863Z" /> 
>   <EventRecordID>3378</EventRecordID> 
>   <Correlation /> 
>   <Execution ProcessID="0" ThreadID="0" /> 
>   <Channel>Application</Channel> 
>   <Computer>ZAK-PC</Computer> 
>   <Security /> 
>   </System>
> - <EventData>
>   <Data>osu!.exe</Data> 
>   <Data>0.0.0.0</Data> 
>   <Data>5fd43c92</Data> 
>   <Data>KERNELBASE.dll</Data> 
>   <Data>10.0.19041.1023</Data> 
>   <Data>924f9cdb</Data> 
>   <Data>e0434352</Data> 
>   <Data>0000000000034b89</Data> 
>   <Data>1eb0</Data> 
>   <Data>01d7646f1bfedcec</Data> 
>   <Data>C:\Users\hugo_\AppData\Local\osulazer\app-2021.619.0\osu!.exe</Data> 
>   <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
>   <Data>fd8b03a8-1651-4d8b-8666-df41d6035912</Data> 
>   <Data /> 
>   <Data /> 
>   </EventData>
>   </Event>

Here's the log

**Comment by bdach** [comment]
The way attaching the log is typically done is as follows:

1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue. You may need to rename it or archive it in a zip for github to allow uploading it here.

**Comment by zekroman** [comment]
[EventlogforGitHub.zip](https://github.com/ppy/osu/files/6678780/EventlogforGitHub.zip)

Is this alright?

**Comment by bdach** [comment]
That works but there's nothing specific to go on. Please open a new Q&A discussion about this and attach game logs (if any are present) and a dxdiag report.
