### ISSUE TITLE
Ability for hardrock to increase the values ​​of OD, CS, AR up to 11

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#12960]
**Describe the new feature:** 
Not the default. I think it is worth introducing the "Extendet Limit" button

The factor that Difficulty Adjust does not have a multiplier still plays here. And hardrock has a multiplier of 1.06.

**Comment by smoogipoo** [comment]
I think the issue here is just that DA and HR can't used together?

**Comment by Moltanicaa** [comment]
No, just a suggestion to expand the existing mod.

**Comment by peppy** [comment]
Unless this issue is suggesting deleting difficulty adjust and merging it into HardRock, this should be closed.

**Comment by Moltanicaa** [comment]
No, it's just that if I want to play with an inverted map, but AR 11, then I can't do it.  Maybe you should give them the opportunity to combine? Or something like that?

**Comment by peppy** [comment]
I think if anything we'd add a flip mod which allows vertical/horizontal flipping to be applied anywhere.

**Comment by smoogipoo** [comment]
I'm going to close this based on the above comments.
