### ISSUE TITLE
Move `Overlays/KeyBinding` namespace to within `Settings`

### ISSUE THREAD

**Issue by peppy** [ppy/osu#12961]
It's not an overlay. Should also be renamed to `KeyBindings` or similar to avoid a namespace/class conflict with the framework class sharing the same name.

I'm leaving this open as a task which should probably be done after the realm key binding store updates have been merged, to avoid ugly conflicts due to file renames.

- [x] Depends on #11461

**Comment by zachary-thomas-115** [comment]
Hello all, I am willing to help with this, if you would be able to assign this to me then please do!

**Comment by peppy** [comment]
See the line directly above your reply. It has already been completed.
