### ISSUE TITLE
osu! hit object lifetime is not updated when AR is changed in editor

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu#12972]
1. In editor, make sure no hit objects are selected.
2. Go to setup, change AR to a lower value.
3. Back to compose, and scroll timeline backwards. Notice hit objects disappear at wrong time.

`OsuHitObjectLifetimeEntry` overrides `InitialLifetimeOffset`.
<https://github.com/ppy/osu/blob/3e5de9e5a8396e3d0a2ace6a5cf57d6ad1226bd3/osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs#L196>

However, there is no logic to update `LifetimeStart` when `TimePreempt` is somehow changed.
It is issue only for pooled DHOs because for non-pooled DHOs `LifetimeStart` is applied at `OnApply`:
<https://github.com/ppy/osu/blob/3e5de9e5a8396e3d0a2ace6a5cf57d6ad1226bd3/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs#L217-L222>

Perhaps `HitObjectLifetimeEntry` should react to `OnDefaultsApplied`, not only `StartTime` changes.

**Comment by smoogipoo** [comment]
I would agree with reacting to `OnDefaultsApplied`.

**Comment by ekrctb** [comment]
Or move `InitialLifetimeOffset` usage to `DrawableOsuHitObject.OnApply`. (This comment of `InitialLifetimeOffset` mentions `LoadComplete`, but this is wrong for pooled DHOs)

https://github.com/ppy/osu/blob/8dce147b8a5cb27ec72d02859fe52ec43d4a45e0/osu.Game/Rulesets/Objects/HitObjectLifetimeEntry.cs#L87

A DHO will be immediately removed after first load (so `OnApply` is called twice per hit object for a gameplay). But this is the current default behavior for scrolling hit objects.

**Comment by ekrctb** [comment]
https://github.com/ppy/osu/blob/8dce147b8a5cb27ec72d02859fe52ec43d4a45e0/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs#L629-L633

This comment is also not correct because `InitialLifetimeOffset` is also used as "transform start time".

https://github.com/ppy/osu/blob/8dce147b8a5cb27ec72d02859fe52ec43d4a45e0/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs#L403

I think `InitialLifetimeOffset` shouldn't be used for this purpose. But existing rulesets are relying on this behavior.
