### ISSUE TITLE
Need can be set to disable the mouse side button

### ISSUE THREAD

**Issue by SmallLuma** [ppy/osu#1310]
Some game player may easily according to the mouse side button, side key is corresponding to exit in OSU or the pause button, very easily lead to unexpected exit game player, hope can be set to disable the mouse side button.

**Comment by DaPrimeAtce** [comment]
I can't understand anything about how you worded the issue. Do you not speak English as a first language? Just curious. :/

**Comment by peppy** [comment]
They are asking for an option to disable the peripheral mouse buttons.

**Comment by peppy** [comment]
All bindings are now removable, so this is no longer an issue.
