### ISSUE TITLE
Auto, Replay bug

### ISSUE THREAD

**Issue by Szenoen** [ppy/osu#1311]
I think it is a bug, but it can be a Secret Feature :)
https://streamable.com/25kox
Let's Watch a video :)

**Comment by FuhKu** [comment]
hmm

**Comment by peppy** [comment]
This is expected behaviour

**Comment by Nightfirecat** [comment]
I think @Szenoen is referring to the last 1/3 of the video or so; the video before that looks normal

**Comment by peppy** [comment]
It's all expected. The functionality is not yet complete. This issue is useless.
