### ISSUE TITLE
osu!lazer exclusive skinning

### ISSUE THREAD

**Issue by painfulspring** [ppy/osu#13207]
_First, I apologize if this has been answered before, even though, I couldn't find much information related to this question._

If I recall correctly, the only way to add a skin to osu!lazer is by importing it from the stable build. However, stable skin seem to have a lot of elements that aren't and can't be used in osu!lazer at all.

My question:
If it's possible, how to create an optimized osu!lazer skin? Does the skin import feature handle these unused elements automatically, or it has to be done manually?

**Comment by peppy** [comment]
You can't yet. It's not implemented yet. Please wait for future developments.
