### ISSUE TITLE
Unhandled error after rewinding taiko beatmap at the end before the result screen transition starts

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#13223]
**Describe the bug:** 
i'm not really sure how to reproduce this but sometimes when i use autoplay on a beatmap and change the skin a few times and then rewind at 100% map completion before the result screen transition starts i get the error sometimes.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43358824/119904316-749f1580-bf4a-11eb-81e7-f029a018d807.mp4

error happens at around 38 seconds.

**osu!lazer version:** 
2021.524.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6557062/database.log)
[network.log](https://github.com/ppy/osu/files/6557063/network.log)
[performance.log](https://github.com/ppy/osu/files/6557064/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6557065/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6557066/updater.log)

**Comment by bdach** [comment]
Cause looks pretty obvious:

```
2021-05-27 21:47:28 [error]: System.ObjectDisposedException: Can not get a channel from a disposed sample.
2021-05-27 21:47:28 [error]: Object name: 'osu.Framework.Audio.Sample.SampleBass'.
2021-05-27 21:47:28 [error]: at osu.Framework.Audio.Sample.Sample.GetChannel()
2021-05-27 21:47:28 [error]: at osu.Game.Skinning.PoolableSkinnableSample.Play()
2021-05-27 21:47:28 [error]: at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
2021-05-27 21:47:28 [error]: at osu.Game.Rulesets.Taiko.Skinning.Legacy.LegacyInputDrum.LegacyHalfDrum.OnPressed(TaikoAction action)
```

Not sure about the resolution, though. May need to unset `DisposeOnDeathRemoval` on `DrumSample` or something of that sort. Unless the sample was disposed through the player hierarchy, which would be way worse to recover from.

**Comment by smoogipoo** [comment]
> Unless the sample was disposed through the player hierarchy

I'm almost certain this is exactly what's going on.

**Comment by peppy** [comment]
Same issue as https://github.com/ppy/osu/issues/5798, different location. Going to take a look into this with no promise of fixing.

**Comment by smoogipoo** [comment]
I don't have any direction planned, no. But scheduling `Play()` sounds wrong imo.

If we keep having to tackle these issues, maybe it's better to relax the disposal checks framework-side, though... Curious if there's a simpler solution before going down this path though.

**Comment by peppy** [comment]
Another option would be to handle it locally in `PoolableSkinnableSound`, by exposing a skin change scheduled delegate and only scheduling the playback if that exists. But feels a bit weird to have to do that there.

**Comment by smoogipoo** [comment]
I don't think that's all that bad. There's a reasonable argument to be made that `PoolableSkinnableSample` needs to run some of its code outside of the scheduler to ensure a correct internal state.
