### ISSUE TITLE
osu!lazer can't log in

### ISSUE THREAD

**Issue by Flippette** [ppy/osu#13239]
**Describe the bug:** 
When I hit fill the username and password fields and hit "Log in", after 2-5 seconds it puts me back at the login menu.
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43138244/120074179-d6d05580-c0c5-11eb-9888-00ca08cd2f1a.mp4

**osu!lazer version:** 
master (f144fcf)
**Logs:**
[network.log](https://github.com/ppy/osu/files/6564800/network.log)
[performance.log](https://github.com/ppy/osu/files/6564801/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6564802/runtime.log)
[database.log](https://github.com/ppy/osu/files/6564803/database.log)

**Comment by enoslayd** [comment]
If your running on debug, tou need to create an account first since it connects to the dev server

**Comment by Flippette** [comment]
> If your running on debug, you need to create an account first since it connects to the dev server

I'm running on release.

**Comment by peppy** [comment]
Please visit the osu! site and fill in the cloudflare captcha. Your IP address is blacklisted.

**Comment by Flippette** [comment]
After filling the captcha, it still can't log in.
