### ISSUE TITLE
"Perfect" is displayed on non-full combo scores

### ISSUE THREAD

**Issue by Ecpii** [ppy/osu#13238]
**Describe the bug:** 
Importing a score from stable with a sliderbreak can show the full combo indicator, even if the score may not be a full combo.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/28408948/120031069-452dee80-bfc6-11eb-9299-58c2b8ac2551.png)
(Full combo is 1252x, as seen on the global leaderboard, this play with 1041x is wrongly marked as "PERFECT")

[the osr file](https://cdn.discordapp.com/attachments/751898645628190843/847915841232437258/Ecpi_playing_Jin_ft._Takumi_Yoshida_phatmans_after_school_-_Kuusou_Forest_Trust_Insane.osr)

**osu!lazer version:** 2021.524.0 

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/6562884/logs.zip)

**Comment by ekrctb** [comment]
This is not specific to imported score.
"Perfect" is shown as long as miss count is zero (slider breaks don't count).
According to #8336, it is planned to take slider breaks into account, but it is not implemented yet.

**Comment by peppy** [comment]
safe to close as a duplicate

**Comment by Joehuu** [comment]
That's a merged PR, reopening.
