### ISSUE TITLE
UI Scaling causes changes in the Skin Editor not to scale properly

### ISSUE THREAD

**Issue by Nekomosh004** [ppy/osu#13234]
**Describe the bug:** 
I tried moving some game elements in the Skin Editor, however, adjusting the UI Scaling in the settings causes the moved elements not to scale properly.

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/82471957/119972142-71f0fe80-bfe4-11eb-8fae-f8e955b77f47.mp4

**osu!lazer version:** 
2021.524.0

**Logs:**

**Comment by smoogipoo** [comment]
This is intended based on the way elements are anchored. Closeable, @peppy?

**Comment by peppy** [comment]
Yes, the user is misusing anchors.

**Comment by smoogipoo** [comment]
I think the other way would be to use relative positioning, right? Maybe that can be considered at some point?

**Comment by peppy** [comment]
I think that will add too much complexity. It's best we give hints to the user they are using the wrong anchor (or automatically update it to the closest edge/corner with a default "choose best" settings) than add more variables to the equation.

Reasoning being is that we wouldn't want relative positioning to be the only choice (would be harder to align elements to other elements) which would make it a fringe case, and one which would usually be served just as well with an anchor spec.
