### ISSUE TITLE
large droplet and small droplet aren't using caps as "Large droplet" and "Small droplet"

### ISSUE THREAD

**Issue by Kimitakari** [ppy/osu#13236]
Just a small thing that could be quickly fixed if the letters L and S we're capitalized. Also shouldn't "Large droplet" should be named as "Ticks" and "Small Droplet" as "Droplets"? It doesn't really follow the osu! website names.

![](https://puu.sh/HKqcw/f5b55008ee.png)

**Comment by peppy** [comment]
The naming should not be changed as we are sticking with the new naming for now.
