### ISSUE TITLE
Beatmaps not showing up in osu!lazer

### ISSUE THREAD

**Issue by trumtex65** [ppy/osu#13246]
**Describe the bug:** when i add skin to osu lazer and then restarting game to see if skin was applied, then beatmaps are not there and even restore buttons dont work or clear cashe memory. Thanks

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** the latest osu lazer on Ipad 

**Logs:**

**Comment by bdach** [comment]
Do you mean to say that beatmaps are getting reset every time the game is launched, or something of the sort? It's not exactly clear from your opening post.

As a sanity check, please make sure you don't have any star rating filters set in the game settings.

**Comment by peppy** [comment]
Please read the issue template and fill it out properly.
