### ISSUE TITLE
Skin editor should automatically update origin/anchor to closest anchor point unless manually overridden

### ISSUE THREAD

**Issue by peppy** [ppy/osu#13252]
In 99% of cases, the correct anchor is the closest one to the dragged selection (see cases like https://github.com/ppy/osu/issues/13234, where the user has moved elements across the screen and left the incorrect anchor specification).

To reduce the manual overhead, the anchor/origin selections should default to an "Automatic" or "Closest" menu item, which will update the anchor/origin to the closest as the user drags elements around.

**Comment by ribbanya** [comment]
I see two mutually exclusive ways to do this.

1. Add `Closest = 1 << 7` to [`Anchor`](https://github.com/ppy/osu-framework/blob/404d4afc303ba2592f00d69e3c3fbf5e358ae335/osu.Framework/Graphics/Drawable.cs#L2836).
In [`RelativeAnchorPosition`](https://github.com/ppy/osu-framework/blob/404d4afc303ba2592f00d69e3c3fbf5e358ae335/osu.Framework/Graphics/Drawable.cs#L1201), if that flag is present, give back a position (x and y = 0, 0.5, or 1) calculated from `Position / Parent.ChildSize`. 
Then we can either set the `Closest` flag and keep the positional flags along with it (like `Anchor.Closest | Anchor.BottomRight`), so as not to confuse existing framework functions, or we can simply set `Anchor` to `1 << 7` and zero out the positional data, as is done with `Anchor.Custom` (which has different behaviour, so we don't necessarily want to mirror it).
2. In [`createAnchorItems`](https://github.com/ppy/osu/blob/7b88ba8c63a3e53be8786146baae8736fcae9df7/osu.Game/Skinning/Editor/SkinSelectionHandler.cs#L201), map the `Anchor[]` to strings, but before passing them to `TernaryStateRadioMenuItem`, prepend the string `"Closest"` and have the `SkinSelectionHandler` keep some additional state (maybe a dictionary or something) to remember what menu item is used for each drawable. This wouldn't require any framework modifications, but keeping duplicate state like that is always messy.

What do you think?

**Comment by bdach** [comment]
Option 1 is out of the question. `Anchor` is used in more contexts than just this one and specifying a "closest" anchor does not really make sense for anything than this specific use case.

**Comment by ribbanya** [comment]
Okay. I know it's used pretty much everywhere, I just wasn't sure if an extra flag was doable or not. I'll look into some options along the lines of (2), then.
