### ISSUE TITLE
i cannot create a prive room

### ISSUE THREAD

**Issue by Ochinchin-san** [ppy/osu#13268]
I cannot set my multiplayer room to only invite or set a password. The options for this are grayed out. Why?

**Comment by bdach** [comment]
Because those functions are not available yet. Please stay tuned for their return.

**Comment by plusls** [comment]
Although it's a bit presumptuous, I still want to ask when it will be ready, because when playing with friends, I often want to have a private room.

**Comment by peppy** [comment]
It is an upcoming imminent focus. Please be patient.
