### ISSUE TITLE
Scroll wheel doesn't scroll beatmaps in song select

### ISSUE THREAD

**Issue by SilverRoll** [ppy/osu#13267]
**Describe the bug:**
Using the wheel in song select adjusts the volume instead of scrolling the view.
**Screenshots or videos showing encountered issue:**
I recorded two videos to demonstrate this; this first one is an osu! build from 2018. It was the first old release that I had on my disk, the date doesn't really matter.
This is what it did before:
https://user-images.githubusercontent.com/35656715/120231842-8df9d780-c252-11eb-89c8-7f764c8e8e70.mp4
This is what it does now:
https://user-images.githubusercontent.com/35656715/120232058-0bbde300-c253-11eb-8a07-f2828e620786.mp4
**osu!lazer version:**
https://github.com/ppy/osu/releases/tag/2021.524.0

**Comment by peppy** [comment]
Please reset your key bindings. You must have scroll wheel bound to volume adjust as a global binding.

**Comment by SilverRoll** [comment]
@peppy This worked, alhough I don't know why it was set to that. Thanks.
