### ISSUE TITLE
Now playing song list goes off-screen at higher UI scaling values

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#13275]
**Describe the bug:** 

Now playing song list has a fixed height, so it can easily go off-screen if higher UI scaling values are used.

**Screenshots or videos showing encountered issue:** 

![osu_2021-06-01_14-12-08](https://user-images.githubusercontent.com/16479013/120322384-a4507380-c2e4-11eb-9ce2-d6b08f8af2f1.jpg)

**osu!lazer version:** 2021.524.0

**Logs:**
Not needed

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/9239
