### ISSUE TITLE
Going to wiki sitemap leads to a blank page with no way of going back

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#13305]
**Describe the bug:** The sitemap is a special autogenerated page and 404s on the api.

**Screenshots or videos showing encountered issue:** 
![osu_2021-06-02_09-17-14](https://user-images.githubusercontent.com/35318437/120515632-56d71380-c383-11eb-9b2e-83d591f8d05e.png)

**osu!lazer version:** 2021.602.0

**Comment by gagahpangeran** [comment]
The blank page is expected.

But the 'index' text in breadcrumb should be clickable so it can go back to main page. I'll look into it.
