### ISSUE TITLE
Invalid client hash

### ISSUE THREAD

**Issue by BojayB** [ppy/osu#13306]
When trying to play a map in multiplayer by myself, it says
"**You are not able to submit a score: Invalid Client Hash**"
and then returns me to the lobby, I'm not sure why. Yesterday when I tried to play a map by myself in multi it worked just fine. I'm not sure if this happens when other players are in the lobby with you or not because nobody joined me. I left the lobby and played the map on my own and it worked fine. I shut down the game so I could get the logs without them changing, hopefully they're useful. If not, I'll recreate the bug and try again.

![image](https://user-images.githubusercontent.com/41974762/120517795-cf979900-c39e-11eb-876b-b4b7b7d1b4bf.png)

**osu!lazer version 2021.602.0** 

**Logs:**
[database.log](https://github.com/ppy/osu/files/6586159/database.log)
[network.log](https://github.com/ppy/osu/files/6586160/network.log)
[performance.log](https://github.com/ppy/osu/files/6586161/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6586162/runtime.log)

**Comment by peppy** [comment]
Please try once more, you may have been too close to the new update being released.

**Comment by BojayB** [comment]
Yep, it works now. My bad!
