### ISSUE TITLE
Links in wiki overlay open in system web browser on Android

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#13309]
**Describe the bug:** 

Tapping on wiki links will try to open them in the system web browser, not in the in-game wiki overlay. This only happens on Android (haven't tested iOS) and is fine on PC.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/16479013/120523411-240a3b00-c3d6-11eb-82a3-f4d0e15bb0db.png)

This is what I get when tapping on a link. If I tap 'yes', it'll open the link in the system web browser (Firefox for me).

**osu!lazer version:** 2021.602.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6586346/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6586347/runtime.log)
[network.log](https://github.com/ppy/osu/files/6586348/network.log)

**Comment by gagahpangeran** [comment]
This is weird, perhaps there's something different happen with `HandleLink` in android.

Unfortunately, I don't have android setup for debugging this right now. Maybe will setup it this weekend.

If someone with android setup want to help debugging this, click the first "Welcome" in main page and take a look at these code.

https://github.com/ppy/osu/blob/7b88ba8c63a3e53be8786146baae8736fcae9df7/osu.Game/Graphics/Containers/Markdown/OsuMarkdownLinkText.cs#L46

The `Url` above should be `https://dev.ppy.sh/wiki/Welcome`. (I assume this will be using dev server in debug mode)

https://github.com/ppy/osu/blob/7b88ba8c63a3e53be8786146baae8736fcae9df7/osu.Game/OsuGame.cs#L276

The `link.Action` above should be `OpenWiki`.

**Comment by peppy** [comment]
I also had a quick look and couldn't see anything off. The URL being loaded shows in the external load dialog and it looks correct to match the `GetLinkDetails` pattern. Very weird.

**Comment by Joehuu** [comment]
`Url` is `/wiki/Welcome`. The tooltip shown when hovering also shows that.

`link.Action` is `External`.

Putting the link in chat works though.

**Comment by peppy** [comment]
so the relative URL isn't being converted to absolute. could this be a race condition between when the absolute URL is being set on a wiki container?

**Comment by peppy** [comment]
I'll look into this one, I can see a potential cause.

**Comment by peppy** [comment]
Actually everything at our end is looking like it should be working correctly. I believe this is going to likely be a `System.Runtime` implementation difference in `Uri` between mono and .net...
