### ISSUE TITLE
Move random mod seed into the base class

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#13319]
Currently only OsuModRandom has a seed, but seeds can and should be used by all random mods.

This would also allow combining the random mods in osu-web, which currently has separate entries for mania, taiko, and (soon) osu!.

**Comment by enoslayd** [comment]
> separate entries for mania, catch, and (soon) osu!.
Isn't it taiko not catch?

**Comment by smoogipoo** [comment]
Yes, fixed.
