### ISSUE TITLE
Star Rating not updating properly when using custom speed

### ISSUE THREAD

**Issue by Lyti4n** [ppy/osu#13312]
**Describe the bug:** 
After you change the custom speed the star rating will only update when you add another mod. If you then change the speed again and change back to that mod combination it will be the same star rating as before.
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=oqkfsBMcrtA
**osu!lazer version:** 
2021.602.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6588786/database.log)
[network.log](https://github.com/ppy/osu/files/6588787/network.log)
[performance.log](https://github.com/ppy/osu/files/6588788/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/6588789/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6588790/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6588791/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6588793/updater.log)

**Comment by smoogipoo** [comment]
https://github.com/ppy/osu/issues/10580

**Comment by Lyti4n** [comment]
this isn't at all the same issue.

**Comment by smoogipoo** [comment]
I've updated my post, https://github.com/ppy/osu/issues/9669 is the original.
