### ISSUE TITLE
Cursor is a little bit invisible

### ISSUE THREAD

**Issue by YOSHIIIII3** [ppy/osu#13321]
**Describe the bug:** 
The cursor is hard to see so i cant really know if my cursor is lined up in the hitcircle or not and that's basically one of the points of the game.... Pls fix this
**Screenshots or videos showing encountered issue:** 
![IMG_20210603_233605](https://user-images.githubusercontent.com/85303351/120672831-3c0cb800-c4c5-11eb-8dde-fac26fd44a6f.jpg)

**osu!lazer version:** 
2021.524.0
**Logs:**
(Sorry i don't know how to put my logs in here for i dont know how to move or copy the files and paste it in this comment cus I'm using a phone at the moment)

**Comment by wowcake** [comment]
I believe the cursor is intended to be invisible in the mobile version.

**Comment by YOSHIIIII3** [comment]
> I believe the cursor is intended to be invisible in the mobile version.

But why tho? Is there any reason for cursors in mobile to be intended as invisible?

**Comment by wowcake** [comment]
Probably the fact that you are supposed to *tap* the circle (until you can actually drag and click?) in mobile, instead of actually moving the cursor in the PC version, making it kinda unnecessary and kinda off.
