### ISSUE TITLE
lazer doesn't show up maps but it loaded

### ISSUE THREAD

**Issue by FLYEMOJ1** [ppy/osu#13327]
**Describe the bug:**  On database.log I saw Import and Cache created, but on UI it doesn't show up.
mp is downloaded by built in beatmap listing. and my macOS version is 11.2.3.

**Screenshots or videos showing encountered issue:** 
<img width="1367" alt="CleanShot 2021-06-04 at 09 49 27@2x" src="https://user-images.githubusercontent.com/53422421/120729465-2bd2f800-c51a-11eb-8b29-5a370d0123d2.png">

**osu!lazer version:** 2021.602.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/6595063/database.log)
[runtime.log](https://github.com/ppy/osu/files/6595064/runtime.log)
[network.log](https://github.com/ppy/osu/files/6595065/network.log)
[performance.log](https://github.com/ppy/osu/files/6595066/performance.log)

**Comment by peppy** [comment]
Do you happen to have a star difficulty filter active in settings?

Do the maps show up in the music control's playlist view? (access from the toolbar)

**Comment by FLYEMOJ1** [comment]
star diff filter is set on: 0 to infi
and maps shows up in the music control 
<img width="1363" alt="CleanShot 2021-06-04 at 10 11 50@2x" src="https://user-images.githubusercontent.com/53422421/120730830-53778f80-c51d-11eb-8512-22628d6041d6.png">

**Comment by peppy** [comment]
What "sort by" mode do you have set? Does typing a search in song select for a map show it?

**Comment by Joehuu** [comment]
Those look to be mania-only maps. Switch to the 4th mode on the top left.

**Comment by FLYEMOJ1** [comment]
> Those look to be mania-only maps. Switch to the 4th mode on the top left.

OMG SRY MY BAD BRO UR GENIUS ._.
