### ISSUE TITLE
Loading too many rulesets causes UI overflow in various locations

### ISSUE THREAD

**Issue by NekomusuMae** [ppy/osu#13339]
**Describe the bug:** 
I cannot reach a bunch of my rulesets as I have too many. Lowering UI Scaling to it's lowest has helped so far but now I have so many rulesets that I can't reach my newest one, Sandbox by Evast. Having this many rulesets is realistically possible (as I've just proven) and causes several other problems. While I'm the most advanced case of this (28 rulesets), as even more rulesets are made, more people can deal with this, especially alot sooner as I am running the game fullscreen and UI Scaling 0.8. People at UI Scaling 1, Fullscreen on a 1080p monitor can only have 14 custom rulesets before they start having problems switching rulesets which is a easy number to reach by just... downloading them all like all do.
Edit: Just now remembering that this is a bigger problem on mobile too do to their small screen sizes.

**Screenshots or videos showing encountered issue:** 
- Ruleset Picker (Rulesets past the intersection are inaccessible through this menu)
![image](https://user-images.githubusercontent.com/43427333/120894552-a6fde200-c5de-11eb-9c0a-eb29565a4c0d.png)
- Ranking Menu
![image](https://user-images.githubusercontent.com/43427333/120894589-cf85dc00-c5de-11eb-9f38-94ea473326e5.png)
- Beatmap Listing (You'd think drop down would've fixed it but the drop down cuts off the last 5 rulesets behind the "Sort by" section)
![image](https://user-images.githubusercontent.com/43427333/120894631-11168700-c5df-11eb-8400-f47a890f2e12.png)
- "Triangles" Intro (Can't show them all)
![image](https://user-images.githubusercontent.com/43427333/120894743-a1ed6280-c5df-11eb-84f5-4ac4a0b18e55.png)
- Bottom of the Settings
![image](https://user-images.githubusercontent.com/43427333/120894760-bc274080-c5df-11eb-8475-aaebceaf5621.png)
- Key Config (After scrolling down, the last ruleset's icon will be hidden behind the back button, but still fully functional)
![image](https://user-images.githubusercontent.com/43427333/120894786-e8db5800-c5df-11eb-9062-2449a66aaab2.png)
**osu!lazer version:** 
2021.602.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6602679/database.log)
[network.log](https://github.com/ppy/osu/files/6602680/network.log)
[performance.log](https://github.com/ppy/osu/files/6602681/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6602682/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6602683/updater.log)

**Comment by bdach** [comment]
A fix was attempted but rejected due to design shortcomings at #9896. That control has been redesigned since then, I think.

**Comment by bdach** [comment]
This was resolved by #18691.
