### ISSUE TITLE
Manual input for sliders in Settings

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#1333]
Precisely setting a slider can be very difficult. For example, I tried fiddling with the Audio Offset, but can't get it back to 0ms. I only move my mouse by a pixel, and I can only pick either 1ms or -4ms now.
Having a small textbox-rectangle next to sliders like these for manual input would be nice.

**Comment by huoyaoyuan** [comment]
Seems "Reset to default" planned.
I remember that left and right key have been implemented?

**Comment by smileyhead** [comment]
When controlled with the arrow keys, the slider jumps 50ms per keypress. It's even less precise than the mouse.

By the way, I found I can edit the config file (%appdata%/osu/game.ini) to reset the Offset, so that's a good thing.

**Comment by huoyaoyuan** [comment]
You'll get used to edit config file manually when the game is in develop 😃

**Comment by peppy** [comment]
Rather than having manual input, the amounts by which sliders moves needs to be tweaked (on a per-slider basis) to make sense.

Also added #1358.

**Comment by smileyhead** [comment]
Dear God, this is a necrobump.

…Anyway, a friend of mine has reminded me of this issue from a couple years back and now I actually have some proposal designs to share.

The first one is likely easier to implement. When the user double clicks a scrollbar head, have a text box pop up that lets you input a value manually. Preferably, it should also tell you what the default, minimum and maximum are.

The more exciting version is the following: When the user double clicks and holds the slider head (or just holds down the Ctrl key where applicable), have a little overlay pop up above the slider that has little pill-shaped ticks representing the minimum adjustable values, then require the mouse to be moved by several pixels to scroll between them. If the user enters the bounding 1/3 area of ticks, have them start scrolling slowly, and quickly on the very edges.

![image](https://user-images.githubusercontent.com/15932372/166436854-ef65f25b-3a34-40f9-aa96-ce7d890be704.png)

I'll add these to the OP, too.

**Comment by peppy** [comment]
I have no idea what your diagram means. But do note that slider bars are getting a new design soon which may change how this is implemented.

**Comment by Theighlin** [comment]
> I have no idea what your diagram means.

I can't record properly now but the closest thing that comes to mind by seeing that diagram is how the youtube website handles searching in a long video. If you want to go to a specific second you drag the slider upwards and it lets you move with much more precision.

![Screenshot_2022-05-03-14-51-07-67_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/53081750/166456451-98bd026c-69a4-4295-b160-d8539580eb9b.jpg)

**Comment by SonoSooS** [comment]
I just realized that peppy has already said the solution to the problem.

For PC, the obvious solution is to adjust the slider by the Bindable's Step value on left/right press instead of some proportional value based on the slider's size.
As for mobile, I guess we'll just have to wait for the slider redesign.
