### ISSUE TITLE
osu!lazer dosen't launch and gives an error after launch

### ISSUE THREAD

**Issue by JadenJSJ** [ppy/osu#13348]
**Describe the bug:** 
osu!.exe - System Error Exception Processing Message 0xc0000005 - Unexpected parameters

**Simmilar Issues:** (More on the bottom)
~~https://github.com/ppy/osu/issues/4502~~
^The issue was closed

System Specs:
Sorry my bad I should have added the specs
Device name	JadenJSJ-Laptop
Processor	Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.70 GHz
Installed RAM	8.00 GB (7.85 GB usable)
System type	64-bit operating system, x64-based processor
AMD Radeon (TM) R7 M360 & Intel (R) HD 620 Graphics

**Screenshots or videos showing encountered issue:**
![image](https://user-images.githubusercontent.com/44781632/120913088-a3da2300-c6be-11eb-8225-be67d621278f.png)

**osu!lazer version:** 
Happens on 2021.602.0 & 2021.524.0
**Logs:**

```
2021-06-06 04:49:17 [verbose]: ----------------------------------------------------------
2021-06-06 04:49:17 [verbose]: runtime Log for jaden (LogLevel: Verbose)
2021-06-06 04:49:17 [verbose]: Running osu 2021.524.0.0 on .NET 5.0.2
2021-06-06 04:49:17 [verbose]: Environment: Windows (Microsoft Windows NT 10.0.19042.0), 4 cores
2021-06-06 04:49:17 [verbose]: ----------------------------------------------------------
2021-06-06 04:49:17 [verbose]: GL Initialized
2021-06-06 04:49:17 [verbose]: GL Version:                 1.1.0
2021-06-06 04:49:17 [verbose]: GL Renderer:                GDI Generic
2021-06-06 04:49:17 [verbose]: GL Shader Language version:
2021-06-06 04:49:17 [verbose]: GL Vendor:                  Microsoft Corporation
2021-06-06 04:49:17 [verbose]: GL Extensions:              GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
2021-06-06 04:49:17 [verbose]: Execution mode changed to MultiThreaded

```

Event Viewer:
![image](https://user-images.githubusercontent.com/44781632/120913148-fa476180-c6be-11eb-8b4b-78e999ce629b.png)
The process was terminated due to an internal error in the .NET Runtime at IP 00007FFB5AC301BF (00007FFB5AA60000) with exit code c0000005.

Visual Studio Debug Log:
Exception thrown at 0x0000000000000000 in osu!.exe: 0xC0000005: Access violation executing location 0x0000000000000000.

Things I have tried:
Whitelist osu!lazer on Windows Defender
Installing it with admin privilages
Scower Google for similar issues in osu!lazer and other games

**What this may be related to**
~~Exception code c0000005 is the code for an access violation. That means that your program is accessing (either reading or writing) a memory address to which it does not have rights. Most commonly this is caused by: ... Only if the memory manager has returned the memory to the system do you get an access violation.
Because of the above I tried to look for osu!lazer memory issue and found this
https://github.com/ppy/osu/issues/5179~~
^if that was rolled out like 1 year ago this issue should have been fixed so im still unsure what how to fix this any help?

**Comment by frenzibyte** [comment]
This is not related to any "memory issues" here, osu!lazer is being ran with GDI generic for some reason. Can you specify your PC specifications please? especially GPU.

**Comment by JadenJSJ** [comment]
Device name	JadenJSJ-Laptop
Processor	Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.70 GHz
Installed RAM	8.00 GB (7.85 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by JadenJSJ** [comment]
> This is not related to any "memory issues" here, osu!lazer is being ran with GDI generic for some reason.

![image](https://user-images.githubusercontent.com/44781632/120913582-3d570400-c6c2-11eb-974c-9a53032be365.png)
![image](https://user-images.githubusercontent.com/44781632/120913597-58c20f00-c6c2-11eb-91cd-d2dd6f6d1e72.png)
I tried changing the graphics to Intel and AMD and the game still didn't launch

**Comment by frenzibyte** [comment]
Rather than that, a `dxdiag` information file would help instead:
 1. Search for `dxdiag` in the Windows Search bar and open it up,
 2. If you get prompted with a dialog regarding checking drivers being digitally signed, you can safely click on `Yes`:
 
![image](https://user-images.githubusercontent.com/22781491/120913634-248a2680-c6a1-11eb-8b5d-6f6d9c01f7a3.png)

 3. Click on the `Save All Information...` button at the bottom, save it somewhere, and attach it here.

**Comment by JadenJSJ** [comment]
Ok
[DxDiag.txt](https://github.com/ppy/osu/files/6604205/DxDiag.txt)

**Comment by bdach** [comment]
From what I can tell by googling around both the cards should - in theory - support at least OpenGL 4.3, which I believe should be enough to run the game. It definitely should not be the case that GDI generic drivers are used, and that may indicate a misconfiguration on your machine.

Please try to reinstall your graphics card drivers and see if it helps at all.

**Comment by enoslayd** [comment]
I think i might have experienced something similar ro that before albeit with only an intel integrated gpu. What i did was to downgrade the driver to 27.20.100.9168 (or lower if possible)

**Comment by smoogipoo** [comment]
I believe that this may be an issue coming as a result of osu! using a compatibility GL context rather than a core one, which has different fallbacks (for picking the most configuration) at an SDL level.

Hard to say without being able to reproduce locally though. @JadenJSJ are you able to compile locally at all? If not I'll make two builds for you to test this theory out with.

**Comment by JadenJSJ** [comment]
@smoogipoo 
Ill try to compile it myself ive compiled some programs but with instructions and in linux not windows but i cant try

**Comment by JadenJSJ** [comment]
I made osu!lazer's update.exe and C:\Users\jaden\AppData\Local\osulazer\app-2021.524.0\osu!.exe
High Performace on Windows Settings and after a restart it fixed itself
![image](https://user-images.githubusercontent.com/44781632/122032868-3b93eb80-cdfa-11eb-91b0-8725690010e9.png)
