### ISSUE TITLE
Editor's Beatmap Setup UI Leaks a Bit

### ISSUE THREAD

**Issue by MLisDreaming** [ppy/osu#13340]
**Describe the bug:** 
A small amount of the UI can leak over the header if scrolled down at all. It's just one row of pixels but it's still noticeable.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/43427333/120895399-6607cc80-c5e2-11eb-8132-94b74af5f186.png)
![image](https://user-images.githubusercontent.com/43427333/120895465-9b141f00-c5e2-11eb-8d3b-2f5eab4fcd60.png)

**osu!lazer version:** 
2021.602.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6602702/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6602703/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6602704/updater.log)
[database.log](https://github.com/ppy/osu/files/6602705/database.log)
[network.log](https://github.com/ppy/osu/files/6602706/network.log)

**Comment by peppy** [comment]
This happens in many places, and is being tracked by https://github.com/ppy/osu-framework/issues/1675. I don't think it's worthwhile to keep this issue open.
