### ISSUE TITLE
osu! lags horribly when I hold a key in beatmap selection search box

### ISSUE THREAD

**Issue by s0m3guy2004** [ppy/osu#13343]
**Describe the bug:** I try holding a key for it to spam out characters and osu! lags horribly unlike stable. I have around 2000+ beatmaps imported and I assume it's constantly searching for a beatmap each time a character is inputted.

**Screenshots or videos showing encountered issue:** https://streamable.com/dv5x72

**osu!lazer version:** 2021.602.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6603063/database.log)
[network.log](https://github.com/ppy/osu/files/6603059/network.log)
[performance.log](https://github.com/ppy/osu/files/6603060/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6603061/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6603062/updater.log)

**Comment by bdach** [comment]
Close enough to https://github.com/ppy/osu/issues/11571 that I'll close as duplicate.

**Comment by peppy** [comment]
Also holding a key should not trigger any searches unless you have your key repeat set to something very slow. Please provide a video showing what you're seeing as it may be unrelated.
