### ISSUE TITLE
Slide Bugs

### ISSUE THREAD

**Issue by IdkMyNameAgain** [ppy/osu#13355]
sometimes, at the beginning of the slides, it gives a score of 100 points and we lose accuracy

**Comment by mk56-spn** [comment]
I assume you're aware but I'm going to check eitherway  . You do know sliders in Lazer have accuracy right ? 

As in you have to hit them on time

**Comment by bdach** [comment]
See above comment, slider head accuracy has been introduced in lazer. Please try the classic mod if you want to play with the old mechanics.
