### ISSUE TITLE
Add filtering by date ranked in the beatmap listing

### ISSUE THREAD

**Issue by boooooooop** [ppy/osu#13353]
this way, you can for example find the top rated/most played/most difficult maps from the past month

![osu_2021-06-06_19-15-10](https://user-images.githubusercontent.com/59298999/120933788-f84fc380-c6fb-11eb-8538-f43114590007.png)

**Comment by frenzibyte** [comment]
Requires support web-side first.

**Comment by peppy** [comment]
it's already supported on web via text searching. if you want UI added then please open an issue against osu-web as we track its design in lazer
