### ISSUE TITLE
Skin editor corner anchors are too sensitive

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#13366]
**Describe the bug:** 

Seems to only occur with vertically-rotated elements, regardless of which element it is.

**Screenshots or videos showing encountered issue:** 

https://drive.google.com/file/d/1QxRbPo483okJxlw1x7aJGt3HmvJdBdNz/view?usp=sharing

**Comment by peppy** [comment]
that's as-implemented, since scale is done based on absolute horizontal mouse movement. i believe this is also how most image editors work but will check on them. maybe the direction used for accepting input should be the longest side.

**Comment by smoogipoo** [comment]
I would expect it to be relative to whatever corner it was dragged from, not horizontal or vertical or the longest edge.

**Comment by peppy** [comment]
ah, diagonally outwards?

**Comment by smoogipoo** [comment]
Exactly

**Comment by bdach** [comment]
Not sure how that would resolve the problem... When the mouse position during a drag isn't on the exact diagonal (as shown on the video there), some choice has to be made as to how to fit the object in it. It can be shorter or longer dimension, but that choice has to be made if aspect ratio is to be preserved.

**Comment by peppy** [comment]
i think it would be more like "scale to the closest point on the diagonal line" or something.

anyways i'll do some research into other apps because i agree we can do better.

**Comment by peppy** [comment]
That's doing precisely what @smoogipoo suggested.

**Comment by peppy** [comment]
For reference photoshop works in the same way, so that looks to be the correct direction for implementation:

![20210608 174116 (Adobe Photoshop 2021)](https://user-images.githubusercontent.com/191335/121153203-d2076080-c880-11eb-9078-39e4d271494f.gif)

**Comment by ribbanya** [comment]
@peppy Do you want this behaviour to stay?
https://github.com/ppy/osu/blob/4b3165084d72b4fefb2fe81ec9fb401da2c5fdc5/osu.Game/Skinning/Editor/SkinSelectionHandler.cs#L74-L75

**Comment by peppy** [comment]
Yes, as per the photoshop animation above.
