### ISSUE TITLE
Clicking the gamemode icon while on the menu page does not take you to the gamemode

### ISSUE THREAD

**Issue by mk56-spn** [ppy/osu#13368]
Pretty self explanatory but when I click on the osu! symbol in the top bar in the menu i am not taken to the osu! gamemode 
![osu! Screenshot 2021 06 07 - 16 15 32 20](https://user-images.githubusercontent.com/74463310/121033272-563be400-c7ac-11eb-816a-11fe19e73e4c.png)

**Comment by mk56-spn** [comment]
*applies to all gamemodes and custom ones too if that is of any importance*

**Comment by peppy** [comment]
It is changing the ruleset you have selected. It shouldn't take you anywhere. It's a global control.

**Comment by mk56-spn** [comment]
Ah. sorry
