### ISSUE TITLE
Custom seed input field for random mod is completely invisible when not highlighted

### ISSUE THREAD

**Issue by integerrr** [ppy/osu#13389]
**Describe the bug:** 
When not clicked, the input field is completely invisible and might be confusing to players as only the word "seed" is seen under the customisation window

**Screenshots or videos showing encountered issue:** 
![osu_2021-06-08_20-27-50](https://user-images.githubusercontent.com/7279624/121245891-71841d80-c898-11eb-9be7-469fbfe09fcd.jpg)
![osu_2021-06-08_20-31-52](https://user-images.githubusercontent.com/7279624/121246014-937da000-c898-11eb-8672-429c4b5ea502.jpg)

**osu!lazer version:** 2021.608.0

**Comment by aitani9** [comment]
This issue has been reintroduced.

**osu!lazer version:** 2021.623.0

**Comment by ekrctb** [comment]
Regressed by #13626:
https://github.com/ppy/osu/pull/13626/files#diff-d9b9b066bb822d8fae7e68e947713c7b4047116167c7c17a07066e6d8b9732f2L78
https://github.com/ppy/osu/pull/13626/files#diff-9838c10c4c9df0fe5c50069b5d37f9e7f31bfc0691bbf63f0a261760b4ecc1c6R64
