### ISSUE TITLE
Background not change to a skin background when using a skin

### ISSUE THREAD

**Issue by HelloYeew** [ppy/osu#13388]
**Describe the bug:** 
After update to latest version (2021.608.0) I normally set a background source to a skin but after I update it's not use a background from skin. It always an osu!lazer default background. I change to other skin and it's still not change.

Before Update (I capture this on 2021.602.0 yesterday) :
<img width="1680" alt="CleanShot 2564-06-08 at 04 21 24@2x" src="https://user-images.githubusercontent.com/68165621/121245451-3ef31880-c8ca-11eb-96e6-6e70665f25c1.png">

After Update :
![CleanShot 2564-06-09 at 02 24 35](https://user-images.githubusercontent.com/68165621/121245184-ed4a8e00-c8c9-11eb-978f-26074d551f25.png)

**Screenshots or videos showing encountered issue:** 
https://youtu.be/xAXOnzFTd2Y

**osu!lazer version:** 
2021.608.0

**Skin that I test in a video:**
https://drive.google.com/drive/folders/1qC-sqQg9TY3VRlru_-NvvBwiJ-xzOcap?usp=sharing

**Logs:**
[database.log](https://github.com/ppy/osu/files/6618985/database.log)
[network.log](https://github.com/ppy/osu/files/6618986/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/6618987/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6618988/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6618989/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/6618990/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6618991/runtime.log)

**Comment by bdach** [comment]
Regressed at https://github.com/ppy/osu/commit/f677f9b5f44a36fd4dc880c55bd7c998fb5b98db. Note in particular the removal of `SkinnedBackground`.
