### ISSUE TITLE
Screen resolution overlay no longer updates during resize

### ISSUE THREAD

**Issue by peppy** [ppy/osu#13385]
It should show the window size during resize operations, not only after letting go.

https://user-images.githubusercontent.com/191335/121227436-82e41e80-c8c6-11eb-823d-c6a504cf1904.mp4

**Comment by maotovisk** [comment]
With further investigation it seems that it only happens on singlethreaded mode.

https://user-images.githubusercontent.com/20617307/121463229-0a459680-c988-11eb-8a63-1113bc1ed782.mp4

https://user-images.githubusercontent.com/20617307/121463231-0c0f5a00-c988-11eb-9c72-26aee83e6098.mp4

running on 2021.608.0

**Comment by peppy** [comment]
The issue is less referring to the flickering, but the "Screen Resolution" popup. It should show you in real-time the dimensions of the window as you're adjusting (I used to use it to get my window to a specific size for recording purposes).

But also interesting to know regarding the threading mode. I'm not sure that's something we can really resolve, just a quirk.

**Comment by peppy** [comment]
Will give this a quick look today, hopefully a quick fix.
