### ISSUE TITLE
Rewinding a replay/autoplay sometimes shows stray hitobjects

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#13395]
**Describe the bug:** 

Rewinding a replay/autoplay will sometimes show hitobjects that shouldn't be there. Those hitobjects are from earlier in the map.

This bug is very common when rewinding; finding a time (that rewinding to shows stray hitobjects) is just trial and error, and can easily be done in all replays.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/16479013/121267256-35fb4a80-c8bc-11eb-86bd-5a0045c2b8c3.mp4

What would have appeared if I had rewound to an earlier time:
![osu_2021-06-09_00-50-06](https://user-images.githubusercontent.com/16479013/121267698-e2d5c780-c8bc-11eb-8b55-5b463c95b7fb.jpg)

**osu!lazer version:** 2021.608.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6619985/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6619986/updater.log)
[network.log](https://github.com/ppy/osu/files/6619987/network.log)
[performance.log](https://github.com/ppy/osu/files/6619988/performance.log)

**Comment by ekrctb** [comment]
It seems like this issue is not completely fixed.
