### ISSUE TITLE
Beatmap skin doesn't get completely deactivated when having it set to off

### ISSUE THREAD

**Issue by M0rica** [ppy/osu#13394]
**Describe the bug:** 
When playing a beatmap that has it's own skin and having beatmap skins disabled, the cursor, moving object on sliders as well as the "connection lines" between hit objects still appear in the beatmaps skin.
**Screenshots or videos showing encountered issue:** 
https://drive.google.com/file/d/1DLuTEWBd2O9X_KZ6PMK_LqN3uaB7jQo8/view?usp=sharing
First map doesn't has it's own skin (and that's how the skin usually looks), second map has a skin which results in these visual glichtes.
**osu!lazer version:** 
2021.608.0
**Logs:**

**Comment by frenzibyte** [comment]
Would be easier if you attached a link to the beatmap, but it's https://osu.ppy.sh/beatmapsets/64525#osu/200670.

Can you please attach the skin you're seeing this issue on as well? if it's not present on all skins.

**Comment by bdach** [comment]
Well this is likely to be the case on all skins. `FindProvider` is not taking `Allow{Drawable,Texture,Sample}Lookup` into account it seems.

**Comment by frenzibyte** [comment]
Ah right, that was actually a noticed issue but got forgotten with all the reconsiderations that went inside #13264.
