### ISSUE TITLE
Resizing a selection should not move it

### ISSUE THREAD

**Issue by ribbanya** [ppy/osu#13398]
**Describe the bug:** 
In both the skin editor and the beatmap editor, resizing a selection below the minimum bounds will instead move the selection. This also results in the cursor being offset from the original drag point in a way that is not intuitive.

In the case of the beatmap editor, this only occurs when scaling from a left-side drag handle.

Two ways of fixing this come to mind.

The first is to simply cap the scaling and freeze the object in place. When the cursor moves back into scalable bounds, it will still be in sync with the original drag point.

The second is to allow inverse scaling, as suggested by https://github.com/ppy/osu/pull/13382#issuecomment-857294928, but this could not be used for the beatmap editor.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/5190964/121293817-427ea380-c8ba-11eb-9519-75de53e81a33.mp4

https://user-images.githubusercontent.com/5190964/121294057-c0db4580-c8ba-11eb-824a-1af05b64aba7.mp4

**osu!lazer version:** 
2021.608.0

**Comment by peppy** [comment]
I think inverse scaling feels the best, where it can be supported. In the beatmap editor the movement should just be inhibited.

**Comment by aitani9** [comment]
I am reserving this issue for myself to work on.

For the inverse scaling, I'd like a second opinion on what should be done about the buttons at the bottom of the selection box and the item count at the top left of the box. Should the buttons always stay at the bottom of the box and the item count always at the top left of the box, or should they move with the box as shown in the clip below?

https://user-images.githubusercontent.com/55509723/126229345-c8d969fe-06c7-475d-b843-764415e68e26.mp4

**Comment by bdach** [comment]
The video above looks weird to me. In favour of fixed position of both the buttons and the count text myself.

**Comment by bdach** [comment]
This appears to be fixed in the beatmap editor (by inhibiting movement as per https://github.com/ppy/osu/issues/13398#issuecomment-857369308). Rescoping to cover skin editor only.
