### ISSUE TITLE
`SelectionBox` doesn't show border when scale is negative

### ISSUE THREAD

**Issue by ribbanya** [ppy/osu#13406]
**Describe the bug:**

When attempting to scale a `SelectionBox` below zero on either axis, its border is invisible.

This seems simple to fix, but I lack familiarity with the framework.

Prerequisite to https://github.com/ppy/osu/issues/13398#issuecomment-857369308.

**Screenshots or videos showing encountered issue:**

![2021-06-09_04-13-55](https://user-images.githubusercontent.com/5190964/121318304-1e7e8a80-c8d9-11eb-8aa0-fb83ba8456a3.gif)

**osu!lazer version:** 
2021.608.0

**Comment by peppy** [comment]
I'm not sure where the concept of "back face culled" comes from, but that's 99% not what's happening here.

Please try using the draw visualiser (Ctrl+F1) to diagnose this yourself. It's likely something local to the drawable implementation of the selection box.

**Comment by bdach** [comment]
To elaborate, the borders are internally drawn using [a shader](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Resources/Shaders/sh_Masking.h), which seems to somehow fail when one of the dimensions of the `CompositeDrawable` it is applied to is negative. Did not investigate any further than confirming that this is actually an issue.
