### ISSUE TITLE
Custom rulesets not working

### ISSUE THREAD

**Issue by CloudyWhale** [ppy/osu#13415]
**Describe the bug:** 
Custom rulesets no longer working

**Screenshots or videos showing encountered issue:** 
<img width="191" alt="2021-06-09 13_50_38-Settings" src="https://user-images.githubusercontent.com/83542885/121404241-c328b880-c929-11eb-998f-c3e8c17e9d69.png">

**osu!lazer version:** 
2021.608.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6625845/database.log)
[performance.log](https://github.com/ppy/osu/files/6625846/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6625847/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6625848/updater.log)

**Comment by frenzibyte** [comment]
The rulesets are outdated, please look for / wait for their new releases. Nothing to do on our side.

**Comment by CloudyWhale** [comment]
ill check them for updates

**Comment by CloudyWhale** [comment]
a way to fix this problem is to add a custom ruleset library where you can post and download rulesets in game so they can auto update

**Comment by EVAST9919** [comment]
https://rulesets.info/pages/status/

**Comment by CloudyWhale** [comment]
when osu lazer updates and there is custom rulesets you can tell the user to update the rulesets

**Comment by bdach** [comment]
This is out of scope for now. It will be coming eventually but likely not before the game reaches feature parity with stable.
