### ISSUE TITLE
Wiki overlay images overflow at higher UI scale

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#13418]
**Describe the bug:** 
an image on the Game client > osu! program files page doesn't scale correctly at higher ui scale and overflows.

**Screenshots or videos showing encountered issue:** 
UI Scale: 1.30x
![image](https://user-images.githubusercontent.com/43358824/121408548-d0ad6500-c960-11eb-9dcf-4b50f0e61cec.png)

**osu!lazer version:** 
commit aed490803fd6d9da10db184bc14c1fd382588266

**Comment by gagahpangeran** [comment]
Looks like need access to the sprite itself after some initial investigation, or maybe there's another way(?)

**Comment by peppy** [comment]
A first step would be to make the content at least mask inside the content are, so it's not overlapping other elements.

UI scaling will (quite correctly) apply to anything not using relative scale. I'm not sure how often wiki images are featured on the same line as other images or content, but the expected result here would be that increasing UI scale would increase the image's size until it fills the full width of the content container, at which point it stops getting larger.

A potential direction/solution may be to nest them inside a relative X container and set a fill mode. Not sure how well this will work but it's somewhere to start looking for a potential solution.

**Comment by gagahpangeran** [comment]
> A potential direction/solution may be to nest them inside a relative X container and set a fill mode. Not sure how well this will work but it's somewhere to start looking for a potential solution.

Fortunately, for now image block (like in the OP) and inline image is already in separate container. The image block itself is inside `WikiMarkdownImageBlock` with relative X. So this could be a potential solution.

I'll look into it again.
