### ISSUE TITLE
Results screen doesn't show up when the spectated user finishes the beatmap

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#13424]
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43358824/121437542-d025c600-c982-11eb-93c2-bb6aa60c0af1.mp4

**osu!lazer version:** 
2021.608.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6627231/database.log)
[network.log](https://github.com/ppy/osu/files/6627233/network.log)
[performance.log](https://github.com/ppy/osu/files/6627235/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6627236/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6627237/updater.log)

**Comment by smoogipoo** [comment]
I'm aware of this one, it's one of the many things I plan to fix with spectator.
