### ISSUE TITLE
Tablet shifted to part of screen

### ISSUE THREAD

**Issue by Sleepdealr** [ppy/osu#13433]
**Describe the bug:** 
Cursor is moved down and to the right in lazer. This wasn't an issue last time I used lazer and isn't an issue in stable.
I have tried changing resolution, scaling, windowed/fullscreen.
My tablet is not detected by laser as well (Huion 430p), have tried with and without OTD.

**Screenshots or videos showing encountered issue:** 
Video:
https://user-images.githubusercontent.com/35879391/121560913-ffb9ea00-c9e5-11eb-9070-4d78ba2b3d40.mp4
In the beginning I moved my cursor around on the desktop, as this issue is only in osu!lazer

**osu!lazer version:** 
2021.608.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6632992/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6632993/updater.log)
[database.log](https://github.com/ppy/osu/files/6632994/database.log)
[network.log](https://github.com/ppy/osu/files/6632995/network.log)
[performance.log](https://github.com/ppy/osu/files/6632996/performance.log)

Edited IRL name out of log header

**Comment by peppy** [comment]
Missing any kind of actionable information. Please open a discussion instead.
