### ISSUE TITLE
Song select takes more time than it should to load panels

### ISSUE THREAD

**Issue by ModuleLFS** [ppy/osu#1344]
I have imported my maps via settings a week or so. Now almost every time I go to song select, I get 2-3 seconds freeze, then I see no maps available. After another 2-3 seconds they appear. Performance log:
~~~
9.10.2017 15:46:36: Drawable [PlaySongSelect (0,0) 1x1] load was blocked for 2210.64ms!
9.10.2017 15:47:53: Drawable [PlaySongSelect (0,0) 1x1] load was blocked for 2283.88ms!
~~~
[Video preview](https://www.youtube.com/watch?v=GkjZo5QbLsQl)

**Comment by peppy** [comment]
This is expected behaviour. Optimisations will come in the future.

**Comment by peppy** [comment]
This has since been vastly improved. Please test again and report back.

There's still plenty of room for further optimisation, for what that's worth.

**Comment by ModuleLFS** [comment]
Pretty smooth now! No freezes or map reloading whatsoever. Nothing in the performance log either.

**Comment by peppy** [comment]
We're getting there! Still huge improvements to be had down the line. Going to close for now.
