### ISSUE TITLE
Distinguish the types of notes in the osu!taiko editor timeline

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#13442]
Currently, stable shows the color of a note in the timeline, and most taiko mappers rely on that to map and mod.

The issue with lazer is that the notes share the same white color in the timeline, which makes mapping feel extremely offputting and weird. We also rely on that in order to look at the map from a wider perspective using the zoom function.

I propose to show note colors on the timeline, which would make the taiko mapping experience much more intuitive and familiar.

### what stable looks like:
![stable](https://user-images.githubusercontent.com/62819481/121578697-da979c80-ca22-11eb-8465-cf7e9d75b8a9.png)

### what lazer looks like:
![lazer](https://user-images.githubusercontent.com/62819481/121578705-dd928d00-ca22-11eb-992a-78a37d9237b1.png)

### proposed change:
![example](https://user-images.githubusercontent.com/62819481/121578716-e08d7d80-ca22-11eb-9e60-943d85ba4844.png)

Oh also I don't know how possible is this but in addition to this, showing finishers on the timeline would be a direct upgrade from the stable editor, instead of just aiming for feature parity with this proposal.

_Originally posted by @Hiviexd in https://github.com/ppy/osu/discussions/13435_

**Comment by peppy** [comment]
Closed via #13444.
