### ISSUE TITLE
Searching for Pending/WIP or Graveyard beatmaps should update default sort mode

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu#13456]
**Describe the bug:** 

In the in-game Beatmap Listing page, when you're searching for maps that are currently in Pending/WIP or in Graveyard, the "Sort by Ranked" option doesn't change into "Sort by Updated" by default :

![image](https://user-images.githubusercontent.com/36564236/121691094-ce7a1080-caf0-11eb-91db-e2774c76385a.png)

This is contrary to the website's behaviour, in which when you're switching the search category from Ranked to Pending/WIP or Graveyard the "Sort by Ranked" option automatically flips over to "Sort by Updated" :

![image](https://user-images.githubusercontent.com/36564236/121690817-8529c100-caf0-11eb-82fd-75c06a303e94.png)

**osu!lazer version:** 

Latest (Lazer 2021.608.0)

**Logs:**

N/A

**Comment by smoogipoo** [comment]
This should only be fixed by consuming the osu!web localisation.

**Comment by smoogipoo** [comment]
I misunderstood this issue as a localisation one. This will need additional support to change that tab's value when the pending search option is selected.
