### ISSUE TITLE
`Export skin` button isn't disabled for modified built-in skins

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#13457]
**Describe the bug:** 
If you edit the skin with skin editor with any of the built-in skins, `Export skin` button isn't disabled.
Clicking it outputs a archive only contains HUD component positions

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/50285552/121692343-9aa3e880-cafa-11eb-8fc7-064adc90da96.png)
![image](https://user-images.githubusercontent.com/50285552/121692565-c8892d00-cafa-11eb-95f9-2005f846a8a3.png)

**osu!lazer version:** 
2021.602.0

**Comment by peppy** [comment]
This is intended and correct.

**Comment by PercyDan54** [comment]
> This is intended and correct.

But when re-importing the exported skin it shows as legacy skin instead of lazer skin.
I know it's because it's falling back to legacy skin because the skin is empty, but could this be a issue?

**Comment by peppy** [comment]
Please either reword or open an issue to cover that, then. Your current issue is imposing new subjective behaviour which as it turns out is not what we intend or want.
