### ISSUE TITLE
Local leaderboard in song select does not refresh automatically in various cases

### ISSUE THREAD

**Issue by Henry-YSLin** [ppy/osu#13465]
**Describe the bug:** 

The local leaderboard sometimes does not respond to changes immediately and requires user interaction to refresh.

Case 1: Clear all local scores of a difficulty when there is only 1 score
Before clearing:
![image](https://user-images.githubusercontent.com/25472513/121765644-ffa12200-cb7e-11eb-9909-bf5ccc083801.png)

After clearing:
![image](https://user-images.githubusercontent.com/25472513/121765664-1f384a80-cb7f-11eb-9534-630cdf076fd7.png)

The deleted score still shows up in the leaderboard after deletion. The leaderboard is only properly cleared if two or more scores are deleted.

Case 2: Quitting to song select after finishing a map, but before the results screen shows
Pressing <kbd>Esc</kbd> at this stage...
![image](https://user-images.githubusercontent.com/25472513/121765862-8efb0500-cb80-11eb-8864-8ee652e70b42.png)

Causes the game to quit to song select without the score showing in the local leaderboard.
![image](https://user-images.githubusercontent.com/25472513/121765871-a0441180-cb80-11eb-9bc4-e8128071cfdb.png)

**osu!lazer version:** 2021.612.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6641707/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6641708/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6641709/updater.log)
[database.log](https://github.com/ppy/osu/files/6641710/database.log)
[network.log](https://github.com/ppy/osu/files/6641711/network.log)

**Comment by peppy** [comment]
I believe this is going to be a duplicate (or at least the same cause) as https://github.com/ppy/osu/issues/13376.

**Comment by peppy** [comment]
I was able to reproduce the item not correctly being removed once out of many tries. Seems like it may be something weird with the underlying EF implementation (something being cached that we don't expect to be), so I'm hesitant to look further into a fix.

I will be addressing the "new scores don't show up", though.

Just to confirm, @Henry-YSLin when you reproduced the first case (clearing local scores not actually removing the scores), does the leaderboard look to refresh? ie. do the panels regenerate themselves?

**Comment by Henry-YSLin** [comment]
Yes, they do. Looks like the score got deleted and then immediately added back.
