### ISSUE TITLE
Hit circles still have animations on editor even with hit animations disabled after 2021.612.0

### ISSUE THREAD

**Issue by maotovisk** [ppy/osu#13466]
https://user-images.githubusercontent.com/20617307/121765896-9ee4fb80-cb24-11eb-83db-351a72ece7e8.mp4

It might be caused by the new DHO changes introduced by https://github.com/ppy/osu/pull/13405 (or https://github.com/ppy/osu/pull/13447, not that much tbh) but i'm not sure.

**version**: 2021.612.0

**logs**:
[performance.log](https://github.com/ppy/osu/files/6641697/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6641698/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6641699/updater.log)
[database.log](https://github.com/ppy/osu/files/6641700/database.log)
[network.log](https://github.com/ppy/osu/files/6641701/network.log)

**Comment by ekrctb** [comment]
The hit custom hit animation logic in the editor uses `ApplyCustomUpdateState` event:

https://github.com/ppy/osu/blob/8795c5f0824e1f1cd9b1aae00d429ac2968713f8/osu.Game.Rulesets.Osu/Edit/DrawableOsuEditorRuleset.cs#L46

But `MainCirclePiece` transformation is also registering the event, and the result is dependent on the invocation order of the event:

https://github.com/ppy/osu/blob/610cdaea98bb1fb9720035cfdbdaa113c542bed8/osu.Game.Rulesets.Osu/Skinning/Default/MainCirclePiece.cs#L71

The editor's custom transformation is overwritten when that is invoked first.

I guess an intention is separating the editor-specific logic from the main game components, but not sure how much of that is feasible.

**Comment by peppy** [comment]
Defintely need regression tests for this stuff.

**Comment by bdach** [comment]
I would much rather somehow enforce that the editor `ApplyCustomUpdateState` callback is invoked at the correct time than add editor-specific logic to the circle piece, as far as I'm concerned. That said, both ways aren't great.

Maybe the skinning system can be roped into this somehow...

**Comment by bluereflega** [comment]
Slider head circles also have hit animations upon initially entering the editor, but goes back to expected behavior (no hit animations) after a few seconds of playing the song.

https://user-images.githubusercontent.com/43960495/121782286-66ecbf80-cbdb-11eb-9996-50783be53f43.mp4

[database.log](https://github.com/ppy/osu/files/6642513/database.log)
[network.log](https://github.com/ppy/osu/files/6642514/network.log)
[performance.log](https://github.com/ppy/osu/files/6642515/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6642516/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6642517/updater.log)

**Comment by ekrctb** [comment]
I think #10909 is the same issue?

**Comment by peppy** [comment]
That one's slightly different (and has been the case for a while now), which has something to do with rewind or autoplay logic I believe.

The one in this issue covers not just slider head circles but standard hitcircles too, which should get a different approach circle and fade animation applied.

**Comment by bdach** [comment]
For what it's worth we can attempt to "enforce" the event ordering by putting these in a `ScheduleAfterChildren()` (and it seems to work on a quick check):

https://github.com/ppy/osu/blob/8795c5f0824e1f1cd9b1aae00d429ac2968713f8/osu.Game.Rulesets.Osu/Edit/DrawableOsuEditorRuleset.cs#L71-L73

I think I'd be fine with such a local solution but not sure I'll get agreement on that...

**Comment by peppy** [comment]
Sounds better than leaving it indefinitely broken, as long as there's an inline comment explaining why and a test covering the resultant behaviour.
