### ISSUE TITLE
Failure finding non-existent express keys

### ISSUE THREAD

**Issue by Tudi20** [ppy/osu#13461]
**Describe the bug:** The only thing this bug does -as far as I noticed - is for my tablet with no express keys (Wacom CTL-472) every start-up you get an annoying error notification. I don't know, if this is a bug on OTD's side though, nor have I seen this reported in this fashion.

(The "Failed to set tablet feature: 02-02" has been reported multiple times so I'm not going to bother with that)

**Screenshots or videos showing encountered issue:** 
![kép](https://user-images.githubusercontent.com/13798839/121742928-d04bd000-cb00-11eb-8150-c577ac6a64a5.png)

**osu!lazer version:** 
2021.621.0

**Logs:**
```
2021-06-11 19:49:52 [verbose]: Detect: Searching for tablet 'Wacom CTL-472'
2021-06-11 19:49:52 [important]: Device: Failed to set tablet feature: 02-02
2021-06-11 19:49:52 [verbose]: Detect: Found tablet 'Wacom CTL-472'
2021-06-11 19:49:52 [important]: Detect: Failed to find auxiliary device, express keys may be unavailable.
```
[runtime.log](https://github.com/ppy/osu/files/6640749/runtime.log)

**Comment by bdach** [comment]
This should indeed be reported to OTD, as that's where the entirety of the detection code lives. We can't do anything about this error in this repository.
