### ISSUE TITLE
failed to process line when switching random skin

### ISSUE THREAD

**Issue by GDcheeriosYT** [ppy/osu#13476]
failed to process line
"BarlineHeight: 0" into
"osu.Game.Skinning.LegactSkingConfigurationColor specified in incorrect format (should be R,G,B or R,G,B,A): 0

![image](https://user-images.githubusercontent.com/54640414/121792384-a60a1900-cbb9-11eb-9e3f-515149872d86.png)

I think this is probably something with the skin itself

I am on windows 10
gpu: Nvidia rtx 2070 super
cpu: Ryzen 7 3800x
mem: 32gb

**Comment by peppy** [comment]
Eventually we will silence these errors, but for now you will need to fix your skin.ini, removing the line in question or changing it to contain `0,0,0` instead if you're expecting black as the colour.
