### ISSUE TITLE
Use "Command" key rather than "Control" for global keybinds on macOS

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#13482]
- [ ] Depends on #12776

---

macOS users are used to using the Command key (superkey/windows key) for shortcuts normally activated with control, i suggest that osu! should check what platform its running on and switch the keys on macOS

_Originally posted by @TMinusBlastedRocket in https://github.com/ppy/osu/discussions/13481_

**Comment by bdach** [comment]
This is already the case to a degree, is it not? At least framework [seems to define platform actions](https://github.com/ppy/osu-framework/blob/99786238a02e0d6b69da86dd52e5506ee8ec0566/osu.Framework/Platform/MacOS/MacOSGameHost.cs#L76-L111) in such a way.

**Comment by frenzibyte** [comment]
Yep I have specifically mentioned "global keybinds" in the title as that's the place where this hasn't been done yet.

**Comment by peppy** [comment]
Can a list be provided here of which keys are currently an issue? I'm not sure if we should be changing all of them, so we should at least document which should be changed so someone attempting this gets it right.

**Comment by frenzibyte** [comment]
Reading on the [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/), it states the following in the "Defining Keyboard Shortcuts" section:

> As much as possible, avoid using the Control key as a modifier. The Control key is already used extensively throughout the system. To avoid possible conflicts, use it only when necessary.

So we may actually have to replace all of them with the `Command` key, as the `Control` key should remain for system-level keybinds only. That includes all of the global keybinds using that modifier:

https://github.com/ppy/osu/blob/385d10eeae407dce35275676df66a16aa99fcb14/osu.Game/Input/Bindings/GlobalActionContainer.cs#L46-L51

https://github.com/ppy/osu/blob/385d10eeae407dce35275676df66a16aa99fcb14/osu.Game/Input/Bindings/GlobalActionContainer.cs#L65

https://github.com/ppy/osu/blob/385d10eeae407dce35275676df66a16aa99fcb14/osu.Game/Input/Bindings/GlobalActionContainer.cs#L74

https://github.com/ppy/osu/blob/385d10eeae407dce35275676df66a16aa99fcb14/osu.Game/Input/Bindings/GlobalActionContainer.cs#L84-L86

https://github.com/ppy/osu/blob/385d10eeae407dce35275676df66a16aa99fcb14/osu.Game/Input/Bindings/GlobalActionContainer.cs#L106

While it currently doesn't make much sense to change some of them, the current combinations used for the global keybinds are [known to be over the place](https://github.com/ppy/osu/issues/12776), and it may be better to mark that as a dependency for this, so nothing feels weird/incorrect when applying this guideline to the combinations.

But also while thinking about this, the key combination for switching rulesets (`Control+Num`) would have to change as well, to completely follow the guidelines there. `Command+Num` may not be right... `Alt+Num`? `Alt+Shift+Num`? not completely sure.

**Comment by peppy** [comment]
I think you're missing the point. All those global bindings *are* system keys.

**Comment by peppy** [comment]
Going to close this until the user actually says which keys they are finding troubling. Kinda pointless in this state.
