### ISSUE TITLE
Update user profile overlay everytime you open it

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#13493]
When I open my profile and go to the "Recent Plays (24h)" to see my last played beatmap, at first everything works fine. My submitted play is shown there. But when I play another map, reopen my profile and look for my most recent play, it doesn't update. The only "fix" at the moment is to open a different profile from another user and then switch back to my profile to force the page to update.

Another very similar issure is in the "dashboard" within the "friends" section. This also doesn't seem to update. It checks once you start the game and then never again. So my friends are still shown as online/offline, even though they are not online/offline anymore.

**Comment by EVAST9919** [comment]
Dashboard overlay already [does](https://github.com/ppy/osu/blob/b6e07ff59c105e0537f7d85fbcd4d01acfc216a0/osu.Game/Overlays/TabbableOnlineOverlay.cs#L44) that.
The thing is that friends' online/offline statuses aren't synched with lazer yet (although I'm not completely sure about that)

**Comment by Joehuu** [comment]
Resolved via https://github.com/ppy/osu/pull/22006 (as a side effect).
