### ISSUE TITLE
ScrollingPlayfield considerations

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1349]
- [ ] Time axis position should automatically be set in base `DrawableScrollingHitObject` rather than individual implementations.
- [ ] Investigate floating point errors for long beatmaps.
- [ ] Consider allowing hitobjects to exist in a custom RelativeChildSize on the non-scrolling axis.

**Comment by peppy** [comment]
Is this still relevant?

**Comment by smoogipoo** [comment]
Nope.
