### ISSUE TITLE
**question and problem**

### ISSUE THREAD

**Issue by GoddessGirl** [ppy/osu#1351]
Question: PC requirements for osu! lazer?

Problem: I've tried downloading osu! lazer multiple times, and every time I open it, it seems to crash.
Help would be greatly appreciated.

PC specs:
Windows 10 Pro 64bit
Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
4GB RAM
.NET Framework installed

Regular osu! works well as usual

Thank you.

Update: It sometimes says ''Program cannot be run in DOS mode''

**Comment by DaPrimeAtce** [comment]
Have you tried troubleshooting compatibility yet? Also, I have an intel i9 processor and 8 gb of ram, and it runs perfectly for me. Which version are you trying to install? 2017.928.0 or 2017.1008.0?

**Comment by peppy** [comment]
Did you try googling the error message? Might be helpful.

**Comment by GoddessGirl** [comment]
I did. Nothing useful

**Comment by GoddessGirl** [comment]
@peppy I tried. Nothing useful.

@DaPrimeAtce Tried troubleshooting compatibility, didnt work. Looks like I'm running 2017.524.0

**Comment by ArtBlnd** [comment]
"Program cannot be run in DOS mode" in normal program means. that program has broken PE structure.
did you tried re downloading it?

**Comment by DaPrimeAtce** [comment]
@GodessGirl try re installing it you're way behind on stability updates

**Comment by GoddessGirl** [comment]
Yes, I've tried reinstalling multiple times @DaPrimeAtce  @ArtBlnd

**Comment by DaPrimeAtce** [comment]
have you tried running any form of virus scan to see if a virus might be
preventing you from installing it?

**Comment by lanodan** [comment]
> Program cannot be run in DOS mode

Are you sure your Windows isn’t trying to run osu! in DOS compatibility mode or whatever bizarre setting/default value? (2 cents of a linux user)

**Comment by LumpBloom7** [comment]
@lanodan Irrelevant, normally CMD or powershell should still run modern applications the way it was meant to be run properly. So that possibility is out of the question.
