### ISSUE TITLE
Avatar tooltip shows username instead of "view profile" when you hover at the bottom/right last pixel of the avatar in fullscreen mode

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#13522]
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43358824/122201066-ed372900-ce9b-11eb-9021-adb4ee06f057.mp4

**osu!lazer version:** 
2021.612.0

**Comment by peppy** [comment]
Honestly feel like we should always be showing the username, not "view profile" here right?

**Comment by peppy** [comment]
The issue here of the edges providing a different tooltip looks to be due to the avatar in question not being a square (therefore two tooltips being provided depending on the hovering location). I'll take a look into improving this.
