### ISSUE TITLE
Can't access some easing values for Approach Different mod

### ISSUE THREAD

**Issue by i3ym** [ppy/osu#13542]
**Describe the bug:** 
Can't access bottom easing values for Approach Different mod

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/20320769/122456808-296fa400-cfd8-11eb-925f-369e4f6ea04b.mp4

**osu!lazer version:** 
Commit 880a008e01cb78b623e7bea355d29999fbe601a3

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/6672593/logs.zip)

**Comment by smoogipoo** [comment]
You need to scroll on the sides of the settings panel too. I agree it's bad UX but I don't think core team members are going to be working on this in the next little while so I'm demoting its priority.

**Comment by peppy** [comment]
A temporary fix of limiting the height of dropdowns in the mod settings area would be the best path forward for now, I believe. This is already done in the settings panel for similar cases.

**Comment by peppy** [comment]
Tracking underlying issue in https://github.com/ppy/osu-framework/issues/4536.
