### ISSUE TITLE
Mod "Approach Different" can be used with mods that hide the approach circle

### ISSUE THREAD

**Issue by i3ym** [ppy/osu#13543]
**Describe the bug:** 
Approach Different mod could be used with the Hidden mod, which doesn't make much sense

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/20320769/122463471-d699ea80-cfdf-11eb-9b06-31c689e7e567.png)

**osu!lazer version:** 
Commit 880a008e01cb78b623e7bea355d29999fbe601a3

**Comment by frenzibyte** [comment]
Seems pretty straightforward, `OsuModApproachDifferent` should be incompatible with mods that hide the approach circle, such as `ModHidden` as mentioned above, and also `ModSpinIn` and `OsuModObjectScaleTween`.
