### ISSUE TITLE
Click sound on changelog overlay doesn't play when clicking on the edge of a category

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#13557]
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43358824/122593663-4a7ed600-d066-11eb-8cc6-16b552dd782a.mp4

**osu!lazer version:** 
2021.612.0

**Comment by aitani9** [comment]
Just to double-check, should the gaps between the items always highlight one of the adjacent items as it does so on the website, or is it okay if none of the items adjacent to the cursor are highlighted when the cursor is in the gap?

**Comment by peppy** [comment]
I'd say the empty space should not highlight anything.
