### ISSUE TITLE
Huge lag spike when starting a beatmap for the first time

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#13558]
**Describe the bug:** 
everytime i start a beatmap for the first time i get a huge lag spike at the beginning. this started happening with version 2021.619.0. the previous version doesn't have this problem.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43358824/122600841-afd7c480-d070-11eb-9047-0f8f5e45c207.mp4

**osu!lazer version:** 
2021.619.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6678677/database.log)
[network.log](https://github.com/ppy/osu/files/6678678/network.log)
[performance.log](https://github.com/ppy/osu/files/6678679/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/6678680/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6678681/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6678683/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6678684/updater.log)

**Comment by bdach** [comment]
This will presumably be somehow related to #13525 if it got worse, but it's likely something that was an issue previously and just got exposed by the GC mode change...

**Comment by mouzedrift** [comment]
> Do you have a spinning disk drive and not an SSD by any chance? 

yep i do have a spinning disk drive.

**Comment by smoogipoo** [comment]
This is definitely related to that PR, but it’s more likely related to just too many allocations in general. From first time sample loads DHO loads…

**Comment by minasminas** [comment]
I also have this issue and I play on an M.2 SSD. The bigger problem tho: it also happens in-game from time to time which is reeaaly annoying.

**Comment by bdach** [comment]
Ok, so I guess that kills my theory and it is just general allocs that need reducing before `LowLatency` can be kicked on...

**Comment by minasminas** [comment]
Another thing I found out (not sure if it helps) is that is does NOT lag at the beginning of the beatmap when you get the option to skip.

**Comment by minasminas** [comment]
Okay, just realised that in the video above it also happens when getting the option to skip for him. Hmm, weird.

**Comment by kindlyfire** [comment]
I get regular lag spikes as well now, after the last update (2021.619.0), every ~1-2 minutes. It also happens when playing a new map. Previous build worked fine.

Since disk set up came up: I have an NVMe SSD.

**Comment by bdach** [comment]
No need to provide more hard disk info at this point, thanks.

**Comment by HerrBreuler** [comment]
> everytime i start a beatmap for the first time i get a huge lag spike at the beginning
> 
Maybe worth to mention, i always get a lag spike at the beginning, not just when starting a map for the first time (after launching the game). The spike happens on every map retry.

**Comment by PLAYERUNKNOWNHatsune01** [comment]
The Issue I guess gotten worse specially when you choice 4 stars up and it will lag in middle of the song when you firs time load it and right now when you play a map first time and played many times then move to other maps and back to it the first lag play will be present again.

**Comment by peppy** [comment]
Please wait for the next release where this change is reverted. We don't need any further feedback, thanks!

**Comment by frenzibyte** [comment]
Unpinning as a [hotfix release](https://osu.ppy.sh/home/changelog/lazer/2021.623.0) has been published for this.
