### ISSUE TITLE
A way to cheese spinners (650 RPM)

### ISSUE THREAD

**Issue by Hammerhead042** [ppy/osu#13563]
Similar: https://github.com/ppy/osu/issues/8224
(Technically the same problem but the blame was on playing with touch)

By just rapidly going back and forth in a straight line over the middle of the spinner you can spin up to 650 RPM without actually going in circles.

video: https://youtu.be/N5ZtL_Uoyls

version: 2021.619.0

**Comment by frenzibyte** [comment]
It's all going to be resolved by properly handling spinning input anyway, regardless of whether it's mouse/touch/tablet. There's no point in opening a duplicate like this.
