### ISSUE TITLE
Osu!Lazer opens, but crashes when the game loads

### ISSUE THREAD

**Issue by Pneu666** [ppy/osu#13570]
**Describe the bug:** i updated osu!lazer right now, when i opened it, it loaded to the black screen where the message "this game is a work in progress" but it crashes before the message appears

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/81386229/122623166-72276b80-d071-11eb-8143-fc8d17e99daf.mp4

**osu!lazer version:** 2021.619.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/6679598/database.log)
[network.log](https://github.com/ppy/osu/files/6679599/network.log)
[performance.log](https://github.com/ppy/osu/files/6679600/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6679601/runtime.log)

**Comment by LumpBloom7** [comment]
Try removing custom rulesets if you have any.

**Comment by jai-x** [comment]
One of the errors in your `runtime.log` file is very weird:

```
2021-06-18 23:04:21 [error]: An unhandled error has occurred.
2021-06-18 23:04:21 [error]: System.Globalization.CultureNotFoundException: Culture name tl is not supported.
```

`tl` does not appear to be a valid two letter country code to have an associated language culture.
Is your system running using a non-standard language setting?

**Comment by bdach** [comment]
No. `tl` was added in the recent localisation settings. Seems like mono doesn't like it.

Thinking of just removing as it has no existing translations anyway yet.

**Comment by Pneu666** [comment]
> One of the errors in your `runtime.log` file is very weird:
> 
> ```
> 2021-06-18 23:04:21 [error]: An unhandled error has occurred.
> 2021-06-18 23:04:21 [error]: System.Globalization.CultureNotFoundException: Culture name tl is not supported.
> ```
> 
> `tl` does not appear to be a valid two letter country code to have an associated Culture class.
> Is your system using a non-standard language configuration?

well, i don't know about that, it only happened in 2021.619.0 
before that it runned normally

**Comment by bdach** [comment]
We've rode this rodeo once before when humanizer added support for Kurdish and mobile users started reporting that the game no longer launched, but this time it's our fault. See https://github.com/ppy/osu/pull/12656 for paper trail.

**Comment by Pneu666** [comment]
so i wont be able to load the game until its fixed or is there any way to solve this bug?

**Comment by bdach** [comment]
Correct. This requires a fix and a new release.

**Comment by peppy** [comment]
> so i wont be able to load the game until its fixed or is there any way to solve this bug?

You can download and reinstall the previous release. I'll pull the android build for now.
