### ISSUE TITLE
After the last osu!lazer update game doesn't open

### ISSUE THREAD

**Issue by z0rfix** [ppy/osu#13573]
osu!lazer 2021.619.0. After update game crashes when I trying open it.
https://www.youtube.com/watch?v=OI2H_iFKP-0&ab_channel=z0rfix

Logs https://disk.yandex.by/d/JzIM756YUlwUqg

Laptop specs
Intel pentium 3558u with intel HD graphics
4 GB RAM

**Comment by peppy** [comment]
Please check the last few reported issues and please read the requirements before posting an issue, which involve searching for existing issues.
