### ISSUE TITLE
The game will crash if you spectate someone and drag a skin component while a transition happens

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#13578]
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43358824/122642252-b8c8a480-d109-11eb-9a7f-a9d8a84cf165.mp4

**osu!lazer version:** 
2021.619.1

**Logs:**
[network.log](https://github.com/ppy/osu/files/6680633/network.log)
[performance.log](https://github.com/ppy/osu/files/6680634/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/6680635/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6680636/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6680637/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6680638/updater.log)
[database.log](https://github.com/ppy/osu/files/6680639/database.log)

**Comment by bdach** [comment]
This is pretty much just https://github.com/ppy/osu/issues/12692. Which you have reported already.

**Comment by mouzedrift** [comment]
woops didnt even notice 🤦
