### ISSUE TITLE
Linux: small stutter when going from song select screen to playing a map

### ISSUE THREAD

**Issue by MierenManz** [ppy/osu#13576]
**Describe the bug:** 
the most recent version `2021.619.0` seems to freeze half a second on linux
idk why this is but it didn't happen before.
This might be because of https://github.com/ppy/osu/pull/13525

**Screenshots or videos showing encountered issue:** 
https://youtu.be/yXvwexqmKWo

**osu!lazer version:** 
`2021.619.0`

**Logs:**
[database.log](https://github.com/ppy/osu/files/6680390/database.log)
[network.log](https://github.com/ppy/osu/files/6680391/network.log)
[performance.log](https://github.com/ppy/osu/files/6680392/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6680393/runtime.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/13558
