### ISSUE TITLE
osu!lazer stutters with some of the fun mods

### ISSUE THREAD

**Issue by amareloPvP** [ppy/osu#13585]
**Describe the bug:**
Constant stuttering when using the mods spin in, grow/deflate and barrel roll, also have a friend having the same issue.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=-jf5razOG8c

**osu!lazer version:** 
2021.619.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6681221/database.log)
[network.log](https://github.com/ppy/osu/files/6681222/network.log)
[performance.log](https://github.com/ppy/osu/files/6681223/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6681224/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6681225/updater.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/13584

**Comment by amareloPvP** [comment]
I saw that but i only have stutter while using those specific mods

**Comment by bdach** [comment]
The frame graph is pretty unambiguously showing that the the issue is the same. A gen2 garbage collection on the update thread is visible right at the time of the stutter.
