### ISSUE TITLE
Sliders Don't "Snake Out" with Classic Mod Enabled

### ISSUE THREAD

**Issue by MLisDreaming** [ppy/osu#13589]
**Describe the bug:** 
When using the "Classic" mod on osu!standard, the sliders no longer "Snake out", even when "Snaking out sliders" is enabled in the settings.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/43427333/122656125-7f9a2f80-d11d-11eb-96b8-3df5838eecb7.png)

**osu!lazer version:** 
2021.619.1

**Logs:**
[database.log](https://github.com/ppy/osu/files/6681372/database.log)
[network.log](https://github.com/ppy/osu/files/6681373/network.log)
[performance.log](https://github.com/ppy/osu/files/6681374/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6681375/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6681376/updater.log)

**Comment by mouzedrift** [comment]
thats intended you can disable/enable it in the classic mod customisations:
![image](https://user-images.githubusercontent.com/43358824/122656376-49c76c00-d15a-11eb-9c41-99b519cb38e5.png)

**Comment by MLisDreaming** [comment]
Asking this to be made into a discussion as I think that's pointlessly redundant and just adds unnecessary confusion. Especially since the mod customization and the options menu use two different things for the same option. This just feel unnecessary and just forces an arbitrary UX choice on legacy replays if I'm right.
If the reasoning is to "do what classic did" then I'd disagree. The classic mod should enforce the mechanics of osu!stable, not the graphics. If they want the graphics of osu!stable, use the skin.

**Comment by peppy** [comment]
This is 100% a *behavioural change*. There is no discussion to be had.

The snaking in lazer changes where you can hit the objects. This setting changes that behaviour.
