### ISSUE TITLE
Osu Lazer again slutters

### ISSUE THREAD

**Issue by aewastaken** [ppy/osu#13584]
**Describe the bug:** 
Again low performance (this time restarting didnt worked at all)
it works mostly with ranked maps, or video ones or even both
Also i noticed that somehow beatmap selection is locked to 60fps, even with 8x refresh rate

**Screenshots or videos showing encountered issue:** 
i forgot to add sound to video, but music is working fine
Google Photos just like always: https://photos.app.goo.gl/rY32odS929XuQRPF6
(for some reason it uploaded in 360p, sorry)

**osu!lazer version:** 
2021.619.1 (mac version)

**Logs:**
[database.log](https://github.com/ppy/osu/files/6681167/database.log)
[network.log](https://github.com/ppy/osu/files/6681168/network.log)
[performance.log](https://github.com/ppy/osu/files/6681169/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6681170/runtime.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/13558

**Comment by aewastaken** [comment]
yeah i just noticed it
