### ISSUE TITLE
Hidden compatibility with Grow/Deflate

### ISSUE THREAD

**Issue by Moxanthia** [ppy/osu#13581]
As of releases 2021.619.0 and 2021.619.1, the Hidden mod can no longer be selected alongside Grow/Deflate. My primary way of playing has been with these mods together as their combined effects make gameplay look much smoother to me. Maybe this is a bug, but if it was on purpose then I'd hope this change can be reverted as there's no apparent conflict between the two.

**Comment by bdach** [comment]
It was semi-intentionally done in https://github.com/ppy/osu/pull/13546, because both mods change approach circles. Although it may have been a bit far-reaching in this case as both of the mentioned mods hide the approach circle in more or less the exact same manner.

**Comment by peppy** [comment]
I'm not against fixing this one, but will need a bit of thought as to how/where the interface should be added to make this work as expected.

**Comment by enoslayd** [comment]
i also wanna suggest that traceable should be compatible with approach different cause technically, traceable only changes the hit circles and slider itself not the approach circles directly

**Comment by frenzibyte** [comment]
Traceable completely hides the approach circle, rendering Approach Different useless.

**Comment by gagahpangeran** [comment]
Tracable doesn't hide approach circle, it hides the circle only.

**Comment by frenzibyte** [comment]
Okay, I confused it with `SpinIn`. Traceable should probably not have `IMutateApproachCircle` assigned to it or be incompatible with them, but be specifically incompatible with mods that hide the approach circle. Will investigate through this.
