### ISSUE TITLE
Spinner approach circlce doesnt appear of default legacy skin

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#13600]
**Describe the bug:** title. it does work on custom skins both old and new spinner style

**Screenshots or videos showing encountered issue:** 
Classic:
![osu_2021-06-21_20-47-56](https://user-images.githubusercontent.com/41866328/122766169-ce89c580-d2d3-11eb-90e7-6f53173d5937.png)

Custom (the grey with white element is the approach circle)
![osu_2021-06-21_20-48-16](https://user-images.githubusercontent.com/41866328/122766230-df3a3b80-d2d3-11eb-864c-7b64e386691d.png)

**osu!lazer version:** master

**Comment by peppy** [comment]
The default legacy skin does not have an approach circle.

**Comment by enoslayd** [comment]
![image](https://user-images.githubusercontent.com/41866328/122767066-d433db00-d2d4-11eb-86b3-66914ab8bb68.png)
it does and stable also have

**Comment by peppy** [comment]
You must be using a skin for this expectation to stand true.

I coded the game and made the spinner. I think I would know.

**Comment by enoslayd** [comment]
oh wait im dum dum yes it doesnt have
