### ISSUE TITLE
Clicking on breadcrumb exits the multiplayer room without confirmation 

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#13609]
**Describe the bug:** 

Clicking the `Lounge` breadcrumb will exit the multiplayer room without the usual confirmation popup.

**Screenshots or videos showing encountered issue:** 

The breadcrumb in question:

![image](https://user-images.githubusercontent.com/16479013/122842844-71573980-d2fe-11eb-8527-9d8e1409b00b.png)

What I **expected** to see when I clicked on the breadcrumb:

![osu_2021-06-22_02-06-36](https://user-images.githubusercontent.com/16479013/122842883-7ddb9200-d2fe-11eb-84f2-695f539d1387.png)

**osu!lazer version:** 2021.619.1

**Logs:** N/A

**Comment by Gonzalo-Bruna** [comment]
The same happens when pressing the home button in the top toolbar
