### ISSUE TITLE
(osu!stable) selection-mode@2x strange visual bug

### ISSUE THREAD

**Issue by iceflarexd** [ppy/osu#13603]
**Describe the bug:** 
I don't know how this affects lazer if at all, but in osu!stable, I was customizing a skin when I noticed a strange bug. The selection-mode@2x picture that covers the menu is gone when the version is set to anything equal to or lower than 1.0. I made a short video detailing this bug so you can understand it better than what I can describe here.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/5dbIlc4cgdI

**osu!stable version:** 
b20210520.2
**Logs:**

**Comment by bdach** [comment]
![2021-06-21-175645_1686x469_scrot](https://user-images.githubusercontent.com/20418176/122792196-392e0780-d2ba-11eb-8113-50874499e276.png)

stable issues are not accepted in this repository. Please follow the link highlighted above and open this issue at https://github.com/ppy/osu-stable-issues/.
