### ISSUE TITLE
Pressing escape key when finishing a map skips results screen

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#13644]
**Describe the bug:** 

When finishing a map, I always click the escape key to try to "acelerate" the process of going to the results screen (I got used to it), but when I do this on lazer it skips the results screen directly and goes to song select, unlike stable.

**Screenshots or videos showing encountered issue:** 

Lazer when pressing escape after finishing a map:

https://user-images.githubusercontent.com/41755816/123186965-3e7c8500-d467-11eb-9b12-c70c7463a3f9.mp4

Stable when pressing escape after finishing the map (expected behavior):

https://user-images.githubusercontent.com/41755816/123187102-800d3000-d467-11eb-9fa0-39f9a7472a1c.mp4

**osu!lazer version:** 

2021.623.0

**Comment by peppy** [comment]
This is an intentional change. Hitting escape should exit, not progress.

You could consider changing your key bindings to avoid inadvertently hitting escape.
