### ISSUE TITLE
Beatmap import hard-locks the game

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#1364]
Seems to be dependent on the length of the beatmap as far as my testing concludes - https://osu.ppy.sh/s/29157 hard-locks for about 4 seconds on my PC.

**Comment by peppy** [comment]
Can reproduce, but only via the osu!direct panels. Drag&drop correctly runs async.

Not going to address the performance issues (it really shouldn't take that long) but will fix async-ness.
