### ISSUE TITLE
Change language to Traditional Chinese (Hong Kong) results in simplified Chinese instead

### ISSUE THREAD

**Issue by JimmyC7834** [ppy/osu#13650]
**Describe the bug:** 
The translated text turns out to be simplified Chinese instead of Traditional Chinese when changing the language to Traditional Chinese (Hong Kong)

**Screenshots or videos showing encountered issue:**
![image](https://user-images.githubusercontent.com/42904673/123293295-727aa780-d546-11eb-8054-511dc546a2aa.png)

**osu!lazer version:** 
2021.263.0

**Comment by bdach** [comment]
Upon double-checking in `osu-resources`, there are actually no `zh-HK` translations there, and [web crowdin](https://crowdin.com/project/osu-web) only lists `zh` and `zh-TW`, so it makes *some* sense that it reverts to simplified in a way. Probably best to remove/comment out for now to avoid confusion...

**Comment by peppy** [comment]
After osu!'s history to date we've had zero demand or requests for whatever dialect that is, so it's safe to say we don't need it for now. Should be removed for sure.
