### ISSUE TITLE
Gaomon S620 not working with lazer drivers

### ISSUE THREAD

**Issue by itsnobii** [ppy/osu#13653]
### Discussed in https://github.com/ppy/osu/discussions/13652

<div type='discussions-op-text'>

<sup>Originally posted by **itsnobii** June 24, 2021</sup>
Hey peeps, I've seen the Gaomon S620 work for others on lazer with the new built-in drivers, but for me, the game just says "No tablet detected." No other tablet drivers are running on my computer atm.

![{D6E497C1-A14C-4B52-98A2-B562FC54BB36}](https://user-images.githubusercontent.com/57056220/123351326-dbecbd00-d52a-11eb-9792-47590f23c616.png)

Maybe I'm missing something incredibly obvious but I can't seem to figure it out.
Any help would be appreciated!</div>

**Comment by frenzibyte** [comment]
That's not an actual bug with osu!lazer, a GitHub discussion is the right place for such issues.
