### ISSUE TITLE
osu!lazer drivers and wacom drivers fighting?

### ISSUE THREAD

**Issue by emrldlol** [ppy/osu#13656]
**Describe the bug:
I have this weird issue with lazer where
if i put the built in tablet drivers on it makes my tablet (Wacom Intuos S (4100S)) run its default settings in wacom drivers and tablet area is glitchy too. Anyone know why??
[](url)

**Screenshots or videos showing encountered issue:
[New folder.zip](https://github.com/ppy/osu/files/6713628/New.folder.zip)
** 

**osu!lazer version: 2021.623.0** 

**Logs:
[network.log](https://github.com/ppy/osu/files/6713636/network.log)
[performance.log](https://github.com/ppy/osu/files/6713637/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6713638/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6713639/updater.log)
[database.log](https://github.com/ppy/osu/files/6713640/database.log)
**

**Comment by peppy** [comment]
Everything in your video looks behaving as expected. Also this is not a bug. Please re-read the issue creation screen properly.
