### ISSUE TITLE
Song select menu freezes during song import

### ISSUE THREAD

**Issue by kiwec** [ppy/osu#13662]
**Describe the bug:** After finishing a song and clicking the button to go to the song select menu, the client freezes for seconds to minutes. I'm currently importing a ton of songs (classic client says ~80k, lazer says ~20k) and both the classic and lazer clients are on HDD.

**Screenshots or videos showing encountered issue:** [Part 1 (playing to song select)](https://www.youtube.com/watch?v=6O8tgJLRI9g) - [Part 2 (song select to usable state)](https://www.youtube.com/watch?v=OYzUcyEn3O8)

Audio isn't recorded, but there are no audio freezes. The currently selected song keeps playing in a loop.

**osu!lazer version:** 2021.623.0 (linux AppImage) - previous versions also affected

**Logs:** [logs.zip](https://github.com/ppy/osu/files/6717772/logs.zip) - also visible live in video :)

Might be related to https://github.com/ppy/osu/issues/3878.

**Comment by peppy** [comment]
How are you triggering the import? It sounds like a thread pool exhaustion case, which we've seen in the past when imports are triggered in non-standard ways. We may still be missing coverage of the fix for this.

**Comment by bdach** [comment]
As an aside logs show foreign key constraint failures as well which may be resolved with #13633, but I'm not convinced they're related to the performance issue.

**Comment by kiwec** [comment]
> How are you triggering the import? It sounds like a thread pool exhaustion case, which we've seen in the past when imports are triggered in non-standard ways. We may still be missing coverage of the fix for this.

I started it from the settings menu, using the button in the debug section. I don't know any other way to import the beatmaps?

**Comment by Cometblazer** [comment]
I have some kind of nagging in myself that there's no limit to the number of maps that can be imported async at any one given time. If this is true, then perhaps (?) the read/write speeds of kiwec's hard drive can't keep up with the demand of the game itself during importing?

The same can be assumed for skins and replays under this hypothetical, though I wouldn't doubt that somewhere in there, there's also some Linux stuff getting in the way potentially. You'd also have to have a pretty well-used or beaten up HDD for this to be an issue.

@kiwec have you tried leaving a terminal with bashtop running while you import your maps, and seeing if your hardware is strained?

**Comment by peppy** [comment]
Please don't comment unless you have actually done research and have evidence. We don't need this.

**Comment by peppy** [comment]
@kiwec we've made some changes to database foreign key constraints, which may somehow help your issue. Could you please try again on the latest release (`2021.707.0`) and see if anything has improved?

**Comment by kiwec** [comment]
Still happens on `2021.707.0`, although it's much, much shorter.

I deleted ~/.local/share/osu and restarted the import from scratch (because the freeze doesn't happen when no new beatmaps are imported).

It looks like the freeze gets longer the more beatmaps are loaded : at first, there's nothing, but after ~5000 beatmaps are imported, the freeze lasts about 10 seconds. After ~10000, it lasts around 45 seconds.

Sitting in the main menu while the import is going on and opening the song list after a few minutes doesn't trigger the freeze.

**Comment by peppy** [comment]
Once it starts happening, if you stop the import then start it again, does it help at all?

**Comment by peppy** [comment]
Closing as stale (should be resolved or at least present differently with realm).
