### ISSUE TITLE
Spectator mode is broken

### ISSUE THREAD

**Issue by kiwec** [ppy/osu#13667]
**Describe the bug:** When spectating a multiplayer lobby, the song starts at the beginning and the spectating window is stuck. UI still works just fine.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=s1TGtnEOtU8

**osu!lazer version:** 2021.623.0 (linux AppImage)

**Logs:** [runtime.log](https://github.com/ppy/osu/files/6719997/runtime.log)

**Comment by peppy** [comment]
Can you confirm if this happens if you are spectating from before the match starts?

**Comment by kiwec** [comment]
It still happens if I start spectating before the match starts. (2/3 people I asked had the same bug)

**Comment by peppy** [comment]
It does seem to play correctly after catching up in time. This should be covered by https://github.com/ppy/osu/pull/13450. I'm not sure if there's already an issue open tracking this to maybe safe to leave this open until the PR gets merged.

**Comment by peppy** [comment]
This should be fixed in the latest release - please give it another try!
