### ISSUE TITLE
Game crashes when enabling multithreading 

### ISSUE THREAD

**Issue by denis34343** [ppy/osu#13670]
**Describe the bug:** 
Game crashes immideatly when enabling multithreading

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/73022874/123527919-c5d62c80-d6e3-11eb-9d48-b257d9addf47.mp4

**osu!lazer version:** 
2021.623.9

**Logs:**

**Comment by peppy** [comment]
This is a known issue with the current release. It will be fixed in the next release. You can change the value in your config file for now, if required.
