### ISSUE TITLE
pp values of plays on website not updated, even if they're top plays of active players

### ISSUE THREAD

**Issue by Sorgair** [ppy/osu#13677]
right now most of the community knows that inactive players do not have their scores' pp updated, such as cookiezi

however, it turns out that this is the case for everyone who was inactive during about a month before and after the rebalance

reddit link with better examples/budget explanation: https://www.reddit.com/r/osugame/comments/o94tvs/bug_top_scores_maybe_all_of_active_players_who/

so if cookiezi came back, his famous freedom dive hdhr would stay under 900 pp on the website, even though I assume the actual value of like 908 or something is stored on the server

**Comment by bdach** [comment]
See [this discussion](https://discord.com/channels/188630481301012481/380598781432823815/853180041194242068) from osu!dev discord, then continued [here](https://discord.com/channels/188630481301012481/380598781432823815/854967115034787841). TL;DR: this is known.

This issue isn't really related to osu!lazer the client, so I'm going to go ahead and close it. https://github.com/ppy/osu-web/ would be a better fit although still not quite as the website does not actually process scores.
