### ISSUE TITLE
the game closes or it just does not open.

### ISSUE THREAD

**Issue by LinuxGamer** [ppy/osu#1368]
several times I tried to compile and recompile, however, the game does not open at all, even though no error occurred during construction. I tried to install the executable file, it opened, however, the game stopped responding and closed.

I want to help with development, but I'm not able to fix this bug.
What is the minimum RAM needed to run the game?

**Comment by huoyaoyuan** [comment]
For Win64 Debug, it's about 1GB, and Release build needs less.
You may check if it saves any log.

**Comment by LinuxGamer** [comment]
@huoyaoyuan 
I didn't do this in windows, but in linux. 
the executable I tested on windows (I also tried to compile it, but it gave the same problem)

**Comment by VPeruS** [comment]
It may be sick question but how did you run .exe file?

**Comment by LinuxGamer** [comment]
I executed it as administrator

**Comment by VPeruS** [comment]
General method for linux user should be something like `$ mono /your/path/to/osu /path/to/your/beatmaps`. Console output of previous command will be also appreciated.

**Comment by LinuxGamer** [comment]
I believe you have not understood very well.

**Comment by LinuxGamer** [comment]
The game simply doesn't even open

**Comment by VPeruS** [comment]
As huoyaoyuan said you should provide logs(path user home/.local/share/osu!/).
