### ISSUE TITLE
Osu grabbing the cursor

### ISSUE THREAD

**Issue by yyny** [ppy/osu#13684]
On Linux, when the `High precision mouse` setting (`UseRelativeMode`) is enabled, Osu is grabbing the mouse cursor, causing X11 mouse events to no longer propogate. This is acceptable for a game like osu, but under certain window manager configurations, it may cause other windows (as well as the Osu window itself) to become unmovable/unresizable/unselectable/unclosable/uninteractable. A common fix for this problem used by other X11 games and applications is to provide the user with a shortcut to manually remove focus like Escape or Alt, although I would recommend Super ("windows key"). The application can then just wait for the window manager to give back focus (through alt-tab, or by the user clicking on the window).

**Comment by gagahpangeran** [comment]
What do you mean by "grabbing"? Is it "confine" or something?

Please provide a video about the issue.

**Comment by peppy** [comment]
You should use an existing window manager binding to avoid this. Like alt-tab.

**Comment by yyny** [comment]
> What do you mean by "grabbing"? 

I guess I should have been more clear. Osu is calling XGrabPointer, or an equivalent. I'm pretty sure this is tied directly to the `High precision mouse` setting, although cursor confining might also affect this.

> You should use an existing window manager binding to avoid this. Like alt-tab.

I *can't*, that's the problem. The default configuration of several window managers including dwm/i3/Xmonad (as well as my own) uses mouse gestures rather than window decoration for most of their actions. These actions are simply nonfunctional while the cursor is grabbed, since the window manager will never receive mouse events in this case. This is usually fine, I don't want to accidentally close the window while playing a game, and this is the intended use case for grabbing the pointer, but it gets annoying when Osu is just idle on the main menu and I want to dismiss a notification.

For my particular configuration, I cannot:

 * Give focus to a specific window (Alt + Click or Hover)
 * Move a window (Alt + Hold LMB)
 * Move the osu window
 * Resize a window (Alt + Hold RMB)
 * Resize the osu window
 * Maximize a window (Alt + Double Click)
 * Maximize the osu window
 * Minimize a window (Alt + Double Right Click)
 * Minimize the osu window
 * Close a window (Alt + Middle Click)
 * Close the osu window without using the ingame  keybind.
 * Interact with a window (Click/Press Key while over the window)

...when Osu is below the cursor. This is because whenever I move my cursor over the Osu window to perform an action, Osu will then immediately grab the pointer.

With my configuration, the best I can do is move osu to a new workspace, but that is annoying and overkill for what is clearly a bug in Osu, since none of the other applications I use that grab the pointer are greedy for pointer grab like this.

I can make a video if that would make the issue more obvious.

Because of the nature of the X11 protocol, there is no way for the window manager to take back cursor control from uncooperative applications in case of a mouse gesture short of preventing applications from grabbing the pointer *completely* (or by hacking the kernel to receive raw mouse events). Few window managers take this extreme, as it is consensus that pointer grabbing can be better handled by cooperative applications.

That is also why many applications and games like the Source Engine, Minecraft, LibreOffice, FireFox and most slideshow/image viewers I have used provide an explicit escape key to give back pointer control to the window manager.

**Comment by peppy** [comment]
Did you check your confine setting in osu! as proposed? If that's not enough to fix your issue, and you can't work around it with your window manager then I'd suggest trying a different window manager or not using "high precision" mode.

**Comment by gagahpangeran** [comment]
I believe this is something in your end with your configuration.

I use i3wm and never experienced that kind of issue.

Like peppy said, if you'd like further help with using linux, please open a discussion instead.

**Comment by yyny** [comment]
The issue occurs on i3, dwm, Xmonad, and my hand-written window manager on both a default install of Ubuntu in both a VM and on a bootable USB as well as on my personal install of Void Linux. This is not a configuration issue.

On further investigation, it appears the issue occurs both when "High precision mouse" is enabled, and when "Confine mouse cursor to window" is set to "Always".

**Comment by bdach** [comment]
This is explicitly intended. Grabbing the mouse is what confining mouse to window *does*, period. They are one and the same.
