### ISSUE TITLE
osu.desktop build login issue

### ISSUE THREAD

**Issue by CertifiedRice** [ppy/osu#13686]
on Jetbrains Rider(C#/.net ide) when I build and run osu.desktop and I try to login to my osu account it won't let me in.

I don't have a video showing it since I don't want to leak passwords and stuff. Let me know if you have the same issue.

It doesn't log anything.

**Comment by smoogipoo** [comment]
In the debug configuration, osu! connects to `https://dev.ppy.sh`. You need to create an account, which is done through the game.

**Comment by CertifiedRice** [comment]
ahh ok ty
