### ISSUE TITLE
Chat commands in multiplayer get sent to the first open channel, which is not always the correct channel

### ISSUE THREAD

**Issue by Muffyn** [ppy/osu#13689]
**Describe the bug:** 
The output of chat commands sent in the multiplayer and playlists chat box are being sent to the first channel on the list. This can cause you to send a message to a player you did not mean to message. 
The chat box in the F8 menu works as expected.
(I found this on accident when an actual player responded to my /me - this isn't just client side)

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/33764011/123750491-40d24b00-d87c-11eb-9a13-e81191296dd2.mp4

**osu!lazer version:** 
2021.623.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6731272/database.log)
[network.log](https://github.com/ppy/osu/files/6731273/network.log)
[performance.log](https://github.com/ppy/osu/files/6731274/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6731276/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6731277/updater.log)

**Comment by peppy** [comment]
To confirm, while in the broken state (without changing the selected channel) can you send normal messages?

**Comment by Muffyn** [comment]
Yes, normal messages send just fine.
