### ISSUE TITLE
Aspire beatmap video is not aligned correctly with gameplay

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#13696]
**Describe the bug:** 
This map is an aspire type of map that emphasizes the video in the background. But here, for some strange reason, the video is in a hurry for about 1.5-2 seconds.
**Screenshots or videos showing encountered issue:** 
lazer gameplay:
https://youtu.be/cJvUl7EoxAs

original:
https://youtu.be/0ZXNxdxWZmo

map - https://osu.ppy.sh/beatmapsets/1503327#osu/3079907
**osu!lazer version:** 
2021.623.0

**Comment by Moltanicaa** [comment]
@bdach
I have information about another problematic aspire map, where there is a problem with music playback (assuming the map starts with negative time values), a storyboard problem, where storyboard objects are displayed much earlier than they should. I'm not sure if you know about this map now. Is it possible to create issue? 
This map - https://osu.ppy.sh/beatmapsets/1237363#osu/2571858

I will remove this comment after answering

**Comment by bdach** [comment]
@Moltanicaa separate issue for that please.

**Comment by peppy** [comment]
Can you confirm this only occurs for you on this one beatmap, not others with video offsets?

**Comment by Moltanicaa** [comment]
https://youtu.be/VlE4B8N2NUs

**Comment by bdach** [comment]
The map used for the comparison above (https://osu.ppy.sh/beatmapsets/1376486#osu/2869013) has video offset 0, but I've taken it and manually edited one of the beatmap `.osu` files to set offset to -1 and there seems to be no discernible difference. So likely it's somehow specific to this one broken beatmap from the OP.

**Comment by Wieku** [comment]
I experienced the same problem in danser.

After digging into it, it turns out MP4/MOV container contains metadata called "edit list" which instructs parsers how to cut the video. Most players except QuickTime/VLC/FFPlay ignore it.

It looks like osu!stable ignores it as well, so videos with that data becomes misaligned in lazer. For now I'm unaware if are there other videos with similar problem.

ffmpeg CLI/ffplay have `-ignore_editlist` argument but I don't know how to apply it with ffmpeg API.

**Comment by bdach** [comment]
Poking in ffmpeg source & [docs](https://www.ffmpeg.org/doxygen/4.3/group__opt__set__funcs.html#ga5fd4b92bdf4f392a2847f711676a7537) it looks like the desired incantation *should* be something along the lines of `av_opt_set_int(formatContext, "ignore_editlist", 1, 0)` or similar? Have not tested, though.

**Comment by peppy** [comment]
Hardcoding sounds fine until it becomes an issue, I think.

**Comment by Wieku** [comment]
IIRC almost everyone re-encodes the video with ffmpeg, even cutting without re-encode actually removes frames, so the only source of editlist would be if someone used QuickTime to trim the video (which seems to be the case here as the video still has audio attached).

**Comment by bdach** [comment]
I can't see the issue on beatmaps which @TechniKris mentioned locally. The beatmap in the OP looks clearly broken but not the purportedly "affected" mapset.

**Comment by TechniKris** [comment]
> I can't see the issue on beatmaps which @TechniKris mentioned locally. The beatmap in the OP looks clearly broken but not the purportedly "affected" mapset.

Ah, I should've made a video showcasing the issue.
Here, I made one now. I synced up gameplay, but the video on lazer is 8 frames (of this 60fps recording) ahead of stable

https://github.com/ppy/osu/assets/30842158/25a110eb-f6e2-4c49-aab8-f2814283ee52
