### ISSUE TITLE
Conflict with Breevy causes quick retry key to go awry

### ISSUE THREAD

**Issue by Berstarke** [ppy/osu#137]
Osu version: b20161101.2

**Breevy** is a windows application that mimics Textexpander, in which the user types snippets which are automatically replaced with some predefined text, launches applications and stuff like that. It has been recently featured in a Humble Bundle, so it may be possible other people may stumble on this problem too.

Steps to reproduce:

1. With Breevy running, start Osu. (starting Breevy while Osu is running has the same effect)
2. Start any song, no matter the mode.
3. Anytime during play, hit the tilde key (quick retry default button). It is not necessary to hold it for the bug to trigger.
4. Try hitting any key in the keyboard. Doesn't matter if it is mapped to anything in Osu or not.

Expected behavior: Song restart and keyboard function as usual.

Actual behavior:

- Quick retry button doesn't work, even if held;
- From now on, any key you hit causes the song to enter a retry loop, as if the retry button was held, even if nothing is being pressed. Hitting the retry button once again breaks the loop. Hitting it twice causes the keyboard to return to normal (But hitting the retry button again will start everything all over).
- Mouse buttons still work as intended

Confirmed workarounds:

- Remapping the retry button to F13 solved the issue.
- Closing Breevy solved the issue.

------

Not sure if this is something on Breevy's side or Osu's. Might be on Osu since I didn't see any problems with other applications, including some pretty keyboard-heavy (like Blender), but I thought I could let you guys know. It seems that Breevy is causing the input to get stuck, and hitting it twice resets the behavior. I've recorded a reproduction. If anyone wants to see it, just let me know.

**Comment by peppy** [comment]
this version of osu! doesn't even have quick retry implement. i think you're posting this in the wrong place, sorry :(

**Comment by Berstarke** [comment]
Huh? It does. It's the latest stable release, post Halloween update. I thought I goofed the version, but it's correct. I just checked.
