### ISSUE TITLE
screenshot bug that slows down the game

### ISSUE THREAD

**Issue by zackysena** [ppy/osu#13707]
**Describe the bug: if you make the screenshot bindings to your tapping it lags and SLOWS osu down for example you tap with z x and you use the z button for screenshotting, the game will lag a little bit and MAKE THE GAME SLOWER so everything is easier** 

**Screenshots or videos showing encountered issue: you can try it out for yourself** 

**osu!lazer version: osu stable** 

**Logs: i dont think this is logs**

**Comment by smoogipoo** [comment]
come on...
