### ISSUE TITLE
Mod compatibility (Approach Different with Traceable)

### ISSUE THREAD

**Issue by BlauFx** [ppy/osu#13700]
**Describe the bug:** Since #13546 it is no longer possible to combine Approach Different with Traceable. In my opinion these two mods should be compatible with each other.

**Screenshots or videos showing encountered issue:** 

How it is as of 2021.619.0:

https://user-images.githubusercontent.com/34138240/123861923-01613880-d928-11eb-88cc-e4f5f2865008.mp4

What no longer is possible to do:

https://user-images.githubusercontent.com/34138240/123861937-0625ec80-d928-11eb-9cd8-fbdbcefc833b.mp4

**Comment by frenzibyte** [comment]
Falls within the scope of #13581, will all be resolved by #13682.
