### ISSUE TITLE
Can't look at global ranking and can't submit scores

### ISSUE THREAD

**Issue by Skylineok1** [ppy/osu#13708]
I've tried restarting my pc and reconnected my wifi but it's still not showing global rankings
And it also says "An error occured during the last update attempt."

Screenshots:
![screenshot142](https://user-images.githubusercontent.com/66750044/123911373-ecc38580-d9a5-11eb-9045-6244128af74b.png)
![screenshot143](https://user-images.githubusercontent.com/66750044/123911572-272d2280-d9a6-11eb-85b9-81bfe5cc05af.png)

**Comment by bdach** [comment]
This repository does not accept issues from stable. Please re-read what's written on the issue creation screen and follow the appropriate link, if you're sure this is an actual game issue and not something about your network connection.
