### ISSUE TITLE
Multiplayer spectator view broken when someone uses a mod with a random seed

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#13751]
When spectating in a multiplayer lobby (have not tested with normal spectating) and someone uses the "random" mod without any specific seed selected, then the spectating playfied doesn't match the one who is playing. I only have a very short clip, but it looks like this (look at the player at the bottom): 

https://user-images.githubusercontent.com/81645139/124313697-84290400-db71-11eb-8fb4-644d45129ed4.mp4

**Comment by minasminas** [comment]
Just updated the title, as I found out that this issue seems to happen with all mods that accept seeds (target practice as a second example here).

**Comment by bdach** [comment]
That's correct. The spectator server will have to handle such mods and authoritatively set a seed for the entire room rather than leaving it up to the clients as done currently.

**Comment by Theighlin** [comment]
This issue doesn't seem to be fixed, played now with someone using random and we were both on 2021.916.0

**Comment by smoogipoo** [comment]
I've tested this multiple times and can no longer repro. I can only assume you weren't actually on 2021.916.0, otherwise please provide logs.

**Comment by Theighlin** [comment]
Ok, it seems it actually was fixed. I saw it not working yesterday and i'm sure i was on the 916.0, you can also see a bit of it in the #14768 video. The only thing i can think of is that he was not on the latest version even though i asked him to check in settings. All good!
