### ISSUE TITLE
Crash when changing Screen mode from Borderless to Fullscreen

### ISSUE THREAD

**Issue by sim1222** [ppy/osu#13758]
**Describe the bug:** 
Crash when changing Screen mode from Borderless to Fullscreen.
However, it does not occur when changing from Windowed to Fullscreen.
Occurs only when Nvidia Geforce Experience Instant Replay is enabled and Desktop Capture is disabled.
It did not occur in osu!Stable.

**System specifications**
Windows 10 21H1 (19043.1052)
GTX 1050 Ti x2
Driver version 471.11

**Screenshots or videos showing encountered issue:** 
https://sim1222.com/assets/osubug2021-07-03-23-57-54.mp4

**osu!lazer version:** 
2021.703.0 (WIndows)

**Logs:**
[network.log](https://github.com/ppy/osu/files/6758590/network.log)
[performance.log](https://github.com/ppy/osu/files/6758591/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6758592/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6758593/updater.log)

**Comment by peppy** [comment]
This is a driver level crash. Please check windows error logs for the driver failure (and also try updating your drivers). We can't really fix this but would appreciate the error log contents being posted here.

**Comment by sim1222** [comment]
This is the error log.
[error.txt](https://github.com/ppy/osu/files/6758615/error.txt)

**Comment by bdach** [comment]
This is indeed caused by the nvidia opengl driver. Other users have had success with disabling shadowplay if it was enabled on their system ([see other similar issues](https://github.com/ppy/osu/search?q=shadowplay&type=issues)).
