### ISSUE TITLE
Can no longer run on windows 7/8 due to realm dependency

### ISSUE THREAD

**Issue by MeguMario** [ppy/osu#13769]
**Describe the bug:** 
The game crashes upon launching the game, 2021.623.0 works fine

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2021.703.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6759799/runtime.log)

**Specs:**
![image](https://user-images.githubusercontent.com/44724359/124383608-92089180-dcf7-11eb-8993-2314ddbccc46.png)

**Note:** I opened this report for a friend who is having this issue. I'm sorry if i can't response right away

**Comment by bdach** [comment]
Error is:

```
2021-07-04 11:04:15 [error]: An unhandled error has occurred.
2021-07-04 11:04:15 [error]: System.TypeInitializationException: The type initializer for 'Realms.SharedRealmHandle' threw an exception.
2021-07-04 11:04:15 [error]: ---> System.DllNotFoundException: Unable to load DLL 'realm-wrappers' or one of its dependencies: The specified module could not be found. (0x8007007E)
2021-07-04 11:04:15 [error]: at Realms.SynchronizationContextScheduler.install_scheduler_callbacks(get_context get, post_on_context post, release_context release, is_on_context is_on)
```

No idea why it's happening on windows 7 while apparently every other OS is fine. Fix might consist of something like #13575 but for the `osu.Desktop` project. I can't test this easily myself because I don't have a win7 machine up anywhere.

**Comment by peppy** [comment]
I doubt a direct reference will do anything. It may be that realm just doesn't have windows 7 support. I'll give it a run in my VM tomorrow.

**Comment by peppy** [comment]
Realm is apparently not supported on windows 7, nor intends to ever be (https://github.com/realm/realm-dotnet/issues/1385).

We'll need to make a decision on wether to use realm or drop windows 7 support.

**Comment by enoslayd** [comment]
[runtime.log](https://github.com/ppy/osu/files/6764598/runtime.log)
for some reason this also happens on 8.1???? (albeight newly installed but alread has the drivers)

**Comment by peppy** [comment]
> [runtime.log](https://github.com/ppy/osu/files/6764598/runtime.log)
> for some reason this also happens on 8.1???? (albeight newly installed but alread has the drivers)

Thanks for the report. This is apparently a regression at realm's end which they are looking to resolve.

**Comment by theklensi** [comment]
8.1 every lazer build launching badly (crash/crash without error/launch only 1 time after pc launch)
