### ISSUE TITLE
osu!lazer won't start after I've imported my beatmaps from stable

### ISSUE THREAD

**Issue by v1kramb** [ppy/osu#13773]
I imported all my beatmaps, scores, and skins from stable in order to switch to lazer, but after I closed it, the app won't open again. Some skins/beatmaps didn't show up, so that may have to do with the issue.

[database.log](https://github.com/ppy/osu/files/6760453/database.log)
[performance.log](https://github.com/ppy/osu/files/6760454/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6760455/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6760456/updater.log)

**Comment by peppy** [comment]
Please attach your `client.db`.

**Comment by v1kramb** [comment]
Here's a link: [https://drive.google.com/file/d/1-abMtca2Blemt3HCYVtN_wN3fu8V8wwg/view?usp=sharing](url)
