### ISSUE TITLE
A score is submitted regardless whether I finished the map.

### ISSUE THREAD

**Issue by K4ktus123** [ppy/osu#13775]
**Describe the bug:** 
When I start a map and then exit it before its end, the game still submits a score to the server.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/55000815/124400314-bf6a3500-dd21-11eb-94b2-6659de3fccea.mp4

**osu!lazer version:** 
2021.703.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6760638/database.log)
[network.log](https://github.com/ppy/osu/files/6760639/network.log)
[performance.log](https://github.com/ppy/osu/files/6760640/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6760641/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6760642/updater.log)

**Comment by peppy** [comment]
That is how osu! works.
