### ISSUE TITLE
Bass cannot be initialize if there is no device available.

### ISSUE THREAD

**Issue by ArtBlnd** [ppy/osu#1379]
Note that this is related to https://github.com/ppy/osu/issues/1302

initializing Bass with `private bool setAudioDevice(string preferredDevice = null)` function doesn't initialize if prefeeredDevice is null.
it should be `Bass.NoSoundDevice` if it isn't exists.

**Comment by peppy** [comment]
This is the same issue and not a new one.

**Comment by ArtBlnd** [comment]
It isn't a same issue. it causes more serious problem.
osu still doesn't work correctly with `const int bass_nodevice = 0x20000;` variable. even fixing it to `Bass.NoSoundDevice`.

**Comment by peppy** [comment]
it's the same issue
