### ISSUE TITLE
osu!lazer is not working anymore since last update, I am using windows 10

### ISSUE THREAD

**Issue by sosobibi** [ppy/osu#13805]
Describe the bug: So, I tried to play osu! lazer but since I installed update 2021.703.0.0, the game wont start anymore. I get no error messages or anything. I do see an error message in the log file but I don't know what it means. Nothing happens when I try to launch the game. 

I am using windows 10 64-bit and have a nvidia graphic card. What should I do to fix the problem ?

Logs:

[database.log](https://github.com/ppy/osu/files/6773451/database.log)
[network.log](https://github.com/ppy/osu/files/6773452/network.log)
[performance.log](https://github.com/ppy/osu/files/6773453/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/6773454/performance-gamethread.audio.log)
[runtime.log](https://github.com/ppy/osu/files/6773456/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6773457/updater.log)

**Comment by Joehuu** [comment]
Should be fixed next release, see https://github.com/ppy/osu/pull/13780.
