### ISSUE TITLE
Show number of beatmaps when searching in song select

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#13837]
### Discussed in https://github.com/ppy/osu/discussions/13833

<div type='discussions-op-text'>

<sup>Originally posted by **IHaveAStrongPassword** July  8, 2021</sup>
I think it would be cool if players can see amount of beatmaps there are whenever a filter is being applied. This was a feature in osu stable as well

example: 
star>3 star<4 
results: 3405 available beatmaps</div>

**Comment by bdach** [comment]
I'm not honestly sure of the usefulness of such information. Does it really matter that much how many maps are matching a filter? How would the user use such information? I'm not necessarily sure that it should happen just because it was in stable.

**Comment by peppy** [comment]
It's useful to know how many results are matching when searching in general. It's something I like to see and I'm pretty sure I already requested this in the new song select design (so it should be there already).

**Comment by OsoCoco** [comment]
@bdach im interested in resolving this issue.
What direction does the team have in mind for this issue?
I already got a solution but it is not the best, so ill like some advice and guide to do better.

Sorry for the bad english!

**Comment by bdach** [comment]
@OsoCoco as mentioned above this will be added as part of a larger song select redesign. however the [latest draft](https://www.figma.com/file/DXKwqZhD5yyb1igc3mKo1P/Song-Select-Draft-2?node-id=0%3A1) doesn't seem to have the count visible anywhere, so that probably needs to be added to design somewhere first and foremost.
