### ISSUE TITLE
Intermittent gameplay stutter

### ISSUE THREAD

**Issue by cxr6548** [ppy/osu#13850]
This is an _irregularly_ occurring stutter during gameplay. It is not regular, and I am not running osu! on a slow hard drive. It's actually fairly hard to catch on recording because it doesn't occur regularly.

The music doesn't skip or anything, which makes me wonder if this is an intentional frame skip to keep timing?

https://user-images.githubusercontent.com/84841289/125152982-464e5180-e116-11eb-9ec0-52ea1e9c0c49.mp4

Sorry I'm not good at video editing. Between the 12th and 13th frame you can see the blue approach circle jump.

[runtime.log](https://github.com/ppy/osu/files/6794721/runtime.log)
[database.log](https://github.com/ppy/osu/files/6794722/database.log)
[network.log](https://github.com/ppy/osu/files/6794723/network.log)
[performance.log](https://github.com/ppy/osu/files/6794724/performance.log)

I'm on the latest version: 2021.707.0-lazer, using the AppImage on Fedora 34. Nvidia proprietary driver and X11

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/11800
