### ISSUE TITLE
osu!lazer randomly tabs out

### ISSUE THREAD

**Issue by bakabakabakabakabaka** [ppy/osu#13854]
**Describe the bug:** When playing osu in fullscreen it randomly tabs out. Pausing the game, and ruining the play. This *may* be a windows 11 specific issue. (I am running the 22000 build of said OS) I cannot test whether this happens in Windows 10. <br/> In further detail, the game will randomly exit fullscreen / tab out. You can tell it isn't in fullscreen because when the bug occurs the taskbar overlaps the window of the game. Sometimes it pauses the game, or stops taking input in the middle of play.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/65756037/125184293-5119ec80-e1d1-11eb-9e6b-29c0ff7c0881.png)
(Can't record this issue since my computer isn't very good at recording with OBS)

**osu!lazer version:** 2021.707.0 (Latest as of 7/10)

**Logs:**

[performance-audio.log](https://github.com/ppy/osu/files/6796384/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6796385/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6796386/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6796387/runtime.log)
[session.log](https://github.com/ppy/osu/files/6796388/session.log)
[update.log](https://github.com/ppy/osu/files/6796389/update.log)
[update_success.log](https://github.com/ppy/osu/files/6796390/update_success.log)
[updater.log](https://github.com/ppy/osu/files/6796391/updater.log)
[database.log](https://github.com/ppy/osu/files/6796392/database.log)
[network.log](https://github.com/ppy/osu/files/6796393/network.log)
[performance.log](https://github.com/ppy/osu/files/6796394/performance.log)

**Comment by enoslayd** [comment]
are you running the leak build? if so update to the latest insider build. I have that problem before on every app and it was gone after updating

**Comment by peppy** [comment]
We can't handle reports from preview operating systems, sorry.

**Comment by bakabakabakabakabaka** [comment]
Windows 11 is going to release later this year, this will most likely only just create duplicates :(
