### ISSUE TITLE
EF considerations

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1386]
While EF has been implemented via #1350, there are several shortcomings or issues I came across along the way. I will be listing these issues here for future references, rather than attempting to address everything in that single PR.

# Overall

- [ ] Streamline `DbContext` retrieval and lifetimes ([good reading](http://mehdi.me/ambient-dbcontext-in-ef6/))
- [x] Investigate osu!direct performance regression.
- [x] Remove `DbContext.Update` calls when not needed
- [ ] Make transactions more elegant (`using` would be nice, explicit failure handling)
- [ ] Handle `DbContext` disposals and restore [TestCase cleanup](6074b205d5d69ca1e4fbfcddfa096e726f79109d).
- [ ] Too many instances of OnlineBeatmapSetID.

# BeatmapManager

- [ ] Do something about the `BeatmapStore`/`FileStore` pair
- [ ] Handle import failures with rollback logic

**Comment by UselessToucan** [comment]
> Do something about the BeatmapStore/FileStore pair

@peppy 
Could you please explain how do you see this? I reread the whole class code and it is not obvious.
By the way, I suggest to extract online operations(`DownloadBeatmapSetRequest` related things) to separate class.

**Comment by kmoore43** [comment]
You could make use of a simple repository pattern with a unit of work, that way you can keep all the queries centralised and easier to maintain. It also makes things a bit more testable.
