### ISSUE TITLE
Enabling Difficulty Adjust crashes the game

### ISSUE THREAD

**Issue by leonekmi** [ppy/osu#13869]
**Describe the bug:** When enabling the DA mod in the beatmap selector, the game freezes and stops.

**Screenshots or videos showing encountered issue:** *(sometimes I noticed that the tray for the options would come up but without rendering the sliders)*

https://user-images.githubusercontent.com/20224422/125333013-040d5600-e34a-11eb-8d55-56225f976582.mp4

**osu!lazer version:** compiled from git sources, commit d85fc08d122d8425d37cbe038a95c6ba389aebc2

With bisect from the DA refactor (#13824, merged in 0c52b26d2312bd090896bf7c65f790ca83ba0cb2), I was able to find the first bad commit is d5d7dd0e74cab0504b8f9c195b1b41aa91398839 (#13701).

**Logs:** [logs_difficulty_adjust_crash.zip](https://github.com/ppy/osu/files/6803409/logs_difficulty_adjust_crash.zip)

There is `Unhandled exception. System.MissingMethodException: Constructor on type 'osu.Game.Rulesets.Mods.DifficultyBindable' not found.` in the console where I ran `dotnet run --project osu.Desktop -c Release` along with the stacktrace that's the same as in `runtime.log`.

**Comment by bdach** [comment]
This is known and will be fixed by #13860.

**Comment by leonekmi** [comment]
Oh, neat! Thanks for the quick answer, keep up the good work. :+1:
