### ISSUE TITLE
Windows switches to 256 colours after second launch

### ISSUE THREAD

**Issue by CircularJoel** [ppy/osu#1388]
I had some problems with osu!lazer. At the first launch everything went normal, but on the second launch, it "turned" to 256 colours, and the game was a black screen. Please help me with this!
#1332 @peppy

**Comment by ZenitH-AT** [comment]
Seems to only happen on Windows 7 from my experience (are you using Windows 7?). Recompiling the code also seems to fix the problem. Is there something that a second run would actually do?

**Comment by CircularJoel** [comment]
I am using Windows 7. Maybe data corrupted while launching it the second time, I'm not an IT expert.

**Comment by peppy** [comment]
Sounds like a driver-specific issue. Please reproduce and provide your `runtime.log` if you want further help.

**Comment by CircularJoel** [comment]
under which directory is runtime.log listed?

**Comment by CircularJoel** [comment]
[runtime (2).log](https://github.com/ppy/osu/files/1405175/runtime.2.log)

**Comment by ZenitH-AT** [comment]
Here's mine. This is a university PC using HD Graphics 2000
[runtime.log](https://github.com/ppy/osu/files/1406994/runtime.log)

**Comment by CircularJoel** [comment]
Here are some lines which are missing in my log:

2017/09/20 11:21:07 AM: Focus contention triggered by LoginOverlay (0,40) 360x0.
2017/09/20 11:21:32 AM: Focus contention triggered by MainSettings (0,0) 0x768.
2017/09/20 11:21:38 AM: Menu item Fullscreen is Selected
2017/09/20 11:21:39 AM: Menu item Windowed is Selected
2017/09/20 11:21:39 AM: Menu item Fullscreen is NotSelected
2017/09/20 11:21:39 AM: Menu item Borderless is Selected
2017/09/20 11:21:39 AM: Menu item Windowed is NotSelected
2017/09/20 11:21:40 AM: Menu item Fullscreen is Selected
2017/09/20 11:21:40 AM: Menu item Borderless is NotSelected

**Comment by ZenitH-AT** [comment]
I'm pretty sure that's a log of the user toggling between fullscreen and windowed (I was trying to get the game to work again).

It does work fine in windowed, although obviously with the usual added latency.

**Comment by CircularJoel** [comment]
It seems that it was launched the first time in Windowed, i changed it to Fullscreen. At the second launch it glitched as previously described. I think it was because i left it in Fullscreen mode.

**Comment by farkasma** [comment]
I have the same problem. Where can I find my runtime.log?

**Comment by farkasma** [comment]
Nvm, I found it! :D
[runtime.log](https://github.com/ppy/osu/files/1408251/runtime.log)

**Comment by CircularJoel** [comment]
farkasma, mine runtime.log is exactly the same as yours.

**Comment by farkasma** [comment]
Yeah, I don't have those lines either.

**Comment by NITPRUDO** [comment]
Try looking at the compatibility settings of the main exe. There is a checkbox in the properties window that says "run in 256 color mode" It might be checked, but I don't know why it would be.

**Comment by CircularJoel** [comment]
I did not touch the properties, I did not even touch the right click menu.

**Comment by farkasma** [comment]
In my .exe it wasn't checked, and checking - unchecking didn't solve it. Running with the admin rights box checked was no good either.

**Comment by ZenitH-AT** [comment]
I thought that it was already established that this is a problem that occurs on the second run of the game on windows 7 machines using integrated HD graphics. Can you guys confirm?

**Comment by NITPRUDO** [comment]
Only the second run? No problems first time? What happens when reinstalling?

**Comment by farkasma** [comment]
Only the second run, reinstall doesn't fiy it, and yes, I'm using Windows 7 64-bit with Intel HD 3000.

**Comment by farkasma** [comment]
So @ZenitH-AT is absolutely correct.

**Comment by MattiaPette** [comment]
That's not true for me. I can open osu! (latest release, also on local develop) and i don't have any issues.

> 14/11/2017 13:13:37: ----------------------------------------------------------
14/11/2017 13:13:37: Runtime Log for pettemat
14/11/2017 13:13:37: osu version unknown
14/11/2017 13:13:37: Running on Microsoft Windows NT 6.1.7601 Service Pack 1, 8 cores
14/11/2017 13:13:37: ----------------------------------------------------------
14/11/2017 13:13:37: GL Initialized
14/11/2017 13:13:37: GL Version:                 4.4.0 - Build 20.19.15.4531
14/11/2017 13:13:37: GL Renderer:                Intel(R) HD Graphics P530
14/11/2017 13:13:37: GL Shader Language version: 4.40 - Build 20.19.15.4531
14/11/2017 13:13:37: GL Vendor:                  Intel
14/11/2017 13:13:37: GL Extensions:              GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_texture_edge_clamp GL_EXT_separate_specular_color GL_ARB_multitexture GL_ARB_map_buffer_alignment GL_ARB_conservative_depth GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_ARB_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_SUN_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_EXT_texture_rectangle GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ATI_separate_stencil GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_ARB_occlusion_query GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_texture_non_power_of_two GL_ARB_vertex_shader GL_NV_texgen_reflection GL_ARB_point_sprite GL_ARB_fragment_program_shadow GL_EXT_blend_equation_separate GL_ARB_depth_texture GL_ARB_texture_rectangle GL_ARB_draw_buffers GL_ARB_color_buffer_float GL_ARB_half_float_pixel GL_ARB_texture_float GL_ARB_pixel_buffer_object GL_ARB_texture_barrier GL_EXT_framebuffer_object GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_occlusion_query2 GL_EXT_draw_buffers2 GL_WIN_swap_hint GL_EXT_texture_sRGB GL_ARB_multisample GL_EXT_packed_float GL_EXT_texture_shared_exponent GL_ARB_texture_rg GL_ARB_texture_compression_rgtc GL_NV_conditional_render GL_ARB_texture_swizzle GL_EXT_texture_swizzle GL_ARB_texture_gather GL_ARB_sync GL_ARB_cl_event GL_ARB_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_ARB_depth_buffer_float GL_EXT_transform_feedback GL_ARB_transform_feedback2 GL_ARB_draw_indirect GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_ARB_framebuffer_object GL_ARB_framebuffer_no_attachments GL_EXT_texture_array GL_EXT_texture_integer GL_ARB_map_buffer_range GL_ARB_texture_buffer_range GL_EXT_texture_snorm GL_ARB_blend_func_extended GL_INTEL_performance_query GL_ARB_copy_buffer GL_ARB_sampler_objects GL_NV_primitive_restart GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_uniform_buffer_object GL_ARB_depth_clamp GL_ARB_vertex_array_bgra GL_ARB_shader_bit_encoding GL_ARB_draw_buffers_blend GL_ARB_geometry_shader4 GL_EXT_geometry_shader4 GL_ARB_texture_query_lod GL_ARB_explicit_attrib_location GL_ARB_draw_elements_base_vertex GL_EXT_shader_integer_mix GL_ARB_instanced_arrays GL_ARB_base_instance GL_ARB_fragment_coord_conventions GL_EXT_gpu_program_parameters GL_ARB_texture_buffer_object_rgb32 GL_ARB_compatibility GL_ARB_texture_rgb10_a2ui GL_ARB_texture_multisample GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_timer_query GL_EXT_timer_query GL_ARB_tessellation_shader GL_ARB_vertex_array_object GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_texture_cube_map_array GL_EXT_gpu_shader4 GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_INTEL_fragment_shader_ordering GL_ARB_fragment_shader_interlock GL_ARB_clip_control GL_EXT_shader_framebuffer_fetch GL_ARB_shader_subroutine GL_ARB_transform_feedback3 GL_ARB_get_program_binary GL_ARB_separate_shader_objects GL_ARB_shader_precision GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_ARB_transform_feedback_instanced GL_ARB_compressed_texture_pixel_storage GL_ARB_shader_atomic_counters GL_ARB_shading_language_packing GL_ARB_shader_image_load_store GL_EXT_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_texture_storage GL_EXT_texture_storage GL_ARB_compute_shader GL_ARB_vertex_attrib_binding GL_ARB_texture_view GL_ARB_fragment_layer_viewport GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_texture_storage_multisample GL_ARB_buffer_storage GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_query_buffer_object GL_EXT_polygon_offset_clamp GL_ARB_clear_texture GL_ARB_texture_mirror_clamp_to_edge GL_ARB_debug_output GL_ARB_enhanced_layouts GL_KHR_debug GL_ARB_arrays_of_arrays GL_ARB_texture_query_levels GL_ARB_invalidate_subdata GL_ARB_clear_buffer_object GL_AMD_depth_clamp_separate GL_ARB_shader_stencil_export GL_INTEL_map_texture GL_ARB_texture_compression_bptc GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_robustness GL_ARB_robust_buffer_access_behavior GL_EXT_texture_sRGB_decode GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_ARB_copy_image GL_KHR_blend_equation_advanced GL_EXT_direct_state_access GL_ARB_stencil_texturing GL_ARB_texture_stencil8 GL_ARB_explicit_uniform_location GL_INTEL_multi_rate_fragment_shader GL_ARB_multi_bind GL_ARB_indirect_parameters

Currently trying on a xeon e3-1505M 4 cores 8 thread mobile CPU with Intel HD P530 graphics or a Nvidia quadro 1000M (can switch between the two renderer options)

**Comment by farkasma** [comment]
@MattiaPette Are you talking about the latest osu! release? Because this thread is about osu!lazer.

**Comment by MattiaPette** [comment]
The latest osu!lazer release 2017.1113.0

**Comment by farkasma** [comment]
Just realized I didn't have the latest release, but after updating it still doesn't work. :(

**Comment by MattiaPette** [comment]
It's probably the GL Version you got.
The openGL version is determined by the graphics card driver (usually). Please make sure that you have the latest version of your graphics driver.

By the file you attached the graphics adapter is the Intel HD 3000. Here's the support page:
https://downloadcenter.intel.com/product/81500/Intel-HD-Graphics-3000

**Comment by farkasma** [comment]
I have installed that, restarded, reinstalled, but it still doesn't work.

**Comment by MattiaPette** [comment]
Can you please post the latest runtime.log file? Just to verify that the
opengl has changed.

Il 14 nov 2017 17:06, "farkasma" <notifications@github.com> ha scritto:

**Comment by farkasma** [comment]
It's the same version and build. :D

**Comment by MattiaPette** [comment]
Ok so your driver was updated... Definetively something to keep in mind
@peppy

Il 14 nov 2017 17:12, "farkasma" <notifications@github.com> ha scritto:

**Comment by jorolf** [comment]
Intel HD Graphics 2000 and 3000 only support up to OpenGL version 3.1
https://en.wikipedia.org/wiki/Intel_HD_and_Iris_Graphics#Capabilities

**Comment by jorolf** [comment]
And I can also confirm that Intel HD Graphics 4000 works fine for lazer (that one supporting up to 4.0)

**Comment by MattiaPette** [comment]
Good to know, thanks for sharing. Maybe there os something wrong with the
opengl version. I think it needs further investigations

Il 14 nov 2017 18:09, "jorolf" <notifications@github.com> ha scritto:

**Comment by farkasma** [comment]
I have tried it on another laptop, it has an Intel HD Grapics 620. I'll upload the runtime.log.
[runtime.log](https://github.com/ppy/osu/files/1475981/runtime.log)

**Comment by MattiaPette** [comment]
This time it worked or not? This has an higher pixel shader version so it
should be fine. If this didn't worked there might be some other issues not
related to the driver version

Il 15 nov 2017 20:02, "farkasma" <notifications@github.com> ha scritto:

I have tried it on another laptop, it has an Intel HD Grapics 620. I'll
upload the runtime.log.
runtime.log <https://github.com/ppy/osu/files/1475981/runtime.log>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ppy/osu/issues/1388#issuecomment-344694133>, or mute
the thread

**Comment by farkasma** [comment]
I only forgot the important thing. :D Yes, it was fine this time (aside from the usual instability).

**Comment by MattiaPette** [comment]
So it still might be a openGL version issue.
@peppy what do you think?

**Comment by peppy** [comment]
This is not related to opengl. Please provide a video (use a phone to take it) so we can see what is actually going on.

**Comment by farkasma** [comment]
Sorry for the late answer, here's the video.
[video](https://drive.google.com/file/d/1DpHLiGYtafQUggcDJQC1RIbPxv2LP9hQ/view?usp=sharing)

**Comment by peppy** [comment]
video as streamable link: https://streamable.com/zpzfr

**Comment by peppy** [comment]
Second reproduction case: https://streamable.com/j9mkw (from #1587)

**Comment by bezbashn** [comment]
Hey, I wrote @peppy on twitter yesterday; https://twitter.com/abyss_party/status/942777786162466816
He sent me here. And here I'm.
I made a small video of my own for this issue. Maybe it will clear something out...

(this is the latest lazer build if you are wondering)
https://streamable.com/ot9lq
