### ISSUE TITLE
Incorrect frame limits set on game startup

### ISSUE THREAD

**Issue by PandaDriver156** [ppy/osu#13888]
**Describe the bug:** 
I have a 165Hz monitor, however frame limit values are always set assuming the refresh rate is 60Hz *at startup* (2x frame limit limits to 120fps, 4x to 240fps etc.). Manually changing to a different frame limit option fixes the issue, but will be wrong again on next launch.
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=djYaE5WrhiE
**osu!lazer version:** 
2021.707.0
**Logs:**
[network.log](https://github.com/ppy/osu/files/6817992/network.log)
[performance.log](https://github.com/ppy/osu/files/6817993/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6817994/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6817995/updater.log)
[database.log](https://github.com/ppy/osu/files/6817996/database.log)

**Comment by bdach** [comment]
Potentially related: https://github.com/ppy/osu-framework/issues/4081

**Comment by mk56-spn** [comment]
I also have a 165hz monitor and had this issue of it locking, a windows reinstall solved it for me, short of that id recommend  reinstalling the nvidia drivers you probably have

**Comment by frenzibyte** [comment]
Would that actually be related if the values are corrected once switching the setting? the closest thing I can think of is `CurrentDisplay`/`CurrentDisplayMode` not being correct initially, needs investigation.

**Comment by peppy** [comment]
I believe both responses above are not correct.

This is either going to be operating system or graphic driver related, so could those reporting seeing this please list your specs? Also whether you use multiple monitors or not (and if so, the refresh rate of each).

**Comment by PandaDriver156** [comment]
> could those reporting seeing this please list your specs? Also whether you use multiple monitors or not (and if so, the refresh rate of each).

OS: Windows 10, 2004
CPU: Intel I5-4570
GPU: NVidia GTX 1650 Super (Driver 471.11)
1 Monitor, 165Hz

**Comment by peppy** [comment]
Correction, after checking the video I think @frenzibyte's thinking is correct. Something sounds weird with the bindable / initial display mode setting timings.

**Comment by PandaDriver156** [comment]
> @PandaDriver156 does this happen 100% of the time? does it also happen if you set your game to single-threaded execution?

Yes, on every launch. Happens in single-threaded mode too.

**Comment by peppy** [comment]
Does making the window inactive (alt-tab) then coming back fix the issue? Please try in both windowed and fullscreen modes.

**Comment by PandaDriver156** [comment]
No, doesn't fix with any of the screen modes. Only way to correct them is to change frame limiter (as far as i've noticed).
