### ISSUE TITLE
Support of Windows 7 broke

### ISSUE THREAD

**Issue by Dadoum** [ppy/osu#13883]
**Describe the bug:** 25 days ago the PR #11461 has been merged. Since then, osu!lazer no longer works on Windows 7. Realm does not support Windows 7.

**osu!lazer version:** 2021.623.0 and above

**Logs:** Could not load 'realm-wrappers' or one of its dependencies.

**Comment by smoogipoo** [comment]
https://github.com/ppy/osu/discussions/13750 / https://github.com/ppy/osu/issues/13769
