### ISSUE TITLE
Mania scroll speed does not match the numbers in stable

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#13895]
**Describe the bug:** 
I noticed that the displayed scroll speed number (1 - 40) does not match the scroll speed of stable. I have no idea what the "correct" math is but I don't think I'm able to find out easily.

Example:
Scroll speed of 13720ms (1, the lowest you can go) in lazer results in ~10000 milliseconds time between seeing the note for the first time and being able to hit it, whereas a scroll speed of 1 in stable gives ~11500 milliseconds. None of these numbers make any sense to me given that it says 13720ms.

Another example for the opposite case, aka 340ms (40):
Lazer time between seeing the note and hitting it: about 20 frames on my 60fps recording, aka ~333ms.
Stable time: 17 frames on a 60fps recording, so around 283ms.

I was timing from the first frame any part of the note was visible to the frame in which autoplay hits the note, in the standard skin.

**osu!lazer version:** 
2021.707.0

**Comment by peppy** [comment]
Moving to discussion, as this was done mostly intentionally (ie. it matches closely but I believe is done in a more sane way here, vs stable). We'll probably want to migrate people's values across to give a starting point, but this requires further discussion.
