### ISSUE TITLE
Osu! Game state API

### ISSUE THREAD

**Issue by Disinterpreter** [ppy/osu#139]
Hello everyone! I have a mouse Steelseries Rival 100, It's mouse can change color, and i want change color in depending game event (f.e if i can miss, mouse change color on RED). 

So that I could change the color I need a Game state API.

How it work in CS:GO https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration

It's need for many device (mice, keyboards, headset) from SteelSeries and Razer

P.S Sorry for my bad English ;)

**Comment by huoyaoyuan** [comment]
Sounds an useful idea.
I used to write an tool getting osu's state, but it's using window title, and can only get very little information.

**Comment by SirCmpwn** [comment]
Could do this quite easily with the existing IPC code, or with minor changes to it.

**Comment by Disinterpreter** [comment]
I think IPC it's too difficult

**Comment by FayneAldan** [comment]
I think this is a good idea, but not for your idea of the mouse color changing to red if you can miss a note. Something like that might make it way too easy to create cheating tools and possibly give some players an unfair advantage. Instead, maybe external tools could be able to request info such as score, combo, accuracy, song progress, key counts, hp, current song, and game mode; and they could listen in on events such as start, finish, fail, pause, resume, retry, quit, hit note (with info on the timing and score), and maybe the other activities shown in Bancho (like editing, modding, listening)

**Comment by peppy** [comment]
Definitely should be a thing, but closing the issue to clean things up for now (only keeping active problems rather than potential features).

**Comment by C0D3-M4513R** [comment]
Can this be taken into consideration again?
It would help build bots, that display "Now Playing" information in OBS or Twitch.
Other bots might appear too.
Otherwise we would have to resort to reading from raw memory addresses, or patch the osu!laser code and risk not being able to submit scores.

Btw: gosumemory currently [reads from raw memory addresses](https://github.com/l3lackShark/gosumemory/blob/master/memory/read.go) in regular osu.

**Comment by frenzibyte** [comment]
This is still tracked under https://github.com/ppy/osu/discussions/13011 and attempted at https://github.com/ppy/osu/pull/12274.
