### ISSUE TITLE
Osu Lazer freezes input at random intervals

### ISSUE THREAD

**Issue by Piotr88e** [ppy/osu#13907]
osu lazer freezes input from the mouse, keyboard and tablet for 1-5 seconds randomly, it only happens with osu lazer running, and it happens no matter if i'm idle, playing a beatmap, or with the game completely out of focus.

version: 2021.707.0-lazer

**Comment by bdach** [comment]
This report has nowhere near enough information to be actionable (no video - preferably with extended fps counter, no logs, no hardware specs). Closing until those are provided.
