### ISSUE TITLE
Osu has two versions for 707.0 on the releases tab

### ISSUE THREAD

**Issue by NoraTheGamer** [ppy/osu#13913]
This is really breaking the scoop package for osulazer. Is there any chance you can put the binaries under their proper location at 707.0 not 707.0-lazer or remove the newer tag if -lazer will be amended to future packages. Thank you :)

**Comment by NoraTheGamer** [comment]
Essentially scoop is a package manager for windows and is checking for updates at your releases repo using the newest tag and compares it to the existing tag. It sees a newer tag which is supposed to have the binaries but are under a previous tag using the -lazer amended to it. This is breaking the updater.

**Comment by bdach** [comment]
The suffixed tag is the proper tag going forward. They point at the same ref. The ordering is enforced by github, I'm pretty sure.

Also note that the "lazer" moniker is being slowly phased out and this suffix is a part of that effort.

Also *also*, the game has an auto-updater bundled for windows. So I'm not sure how worth it is to add it to a "package manager".
