### ISSUE TITLE
Tournament client crashes when seeding added with no mod name

### ISSUE THREAD

**Issue by bdach** [ppy/osu#13912]
### Discussed in https://github.com/ppy/osu/discussions/13910

Steps to reproduce:

1. From a blank tourney client, create a team.
2. Add a seeding result for that team, but leave the `Mods` field blank as it initially is.
3. Navigate to seeding screen and see it crash.

<div type='discussions-op-text'>

<sup>Originally posted by **Sheepposu** July 17, 2021</sup>
The osu!lazer tournament client was working fine the other day, but it suddenly stopped opening when I clicked the shortcut. I made sure the shortcut is still pointing to the osu!lazer executable plus the "--tournament" appended at the end. So I tried opening up the actual lazer client for it to update and now the tournament client opens but just loads forever. I also tried uninstalling and reinstalling osu!lazer. Screenshot below of what it looks like:
![image](https://user-images.githubusercontent.com/49356627/126024249-1ff5a8b1-5349-4088-92f2-2d9303620a8d.png)
Thanks in advance for any help with this.</div>

**Comment by bdach** [comment]
Not entirely sure whether to permit adding seedings with no mod name, or to make the textbox initially not-blank. That stuff is all a bit "you have to know how it works to use it properly".

**Comment by peppy** [comment]
It should work when empty I believe. Seems like an oversight which has always been avoided because the seeding screen was made to the requirements of the world cup tournaments.
