### ISSUE TITLE
Mouse jumps randomly from one point on the screen to other

### ISSUE THREAD

**Issue by Feetroid** [ppy/osu#13923]
**Describe the bug:** 

The mouse flicks when i use it to play, use the song list or anything else, the mouse jumps from a local on the screen to some extremity on the monitor, this happens randomly, first i thinked it could be the inputs or the app's cache, but the problem still happen.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/49126087/126084309-c7203943-cd4a-4bd5-8da7-6b26a453f730.mp4

**osu!lazer version:**  2021.707.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/6837066/runtime.log)
[network.log](https://github.com/ppy/osu/files/6837067/network.log)

OS: KDE Neon User Edition 5.22
Kernel: 5.8.0
RAM: 16gb
CPU: FX-8150
Video Card: GTX 1050 2gb

**Comment by mk56-spn** [comment]
Are you sure you have no other input devices plugged in?

**Comment by Feetroid** [comment]
> Are you sure you have no other input devices plugged in?

I have a tablet and a xbox controller, but they aren't connected on the pc, only keyboard and mouse.

**Comment by frenzibyte** [comment]
Have you tried disabling "high precision mouse" and/or changing "confine mouse mode" state?

**Comment by Feetroid** [comment]
> Have you tried disabling "high precision mouse" and/or changing "confine mouse mode" state?

it works, i disabled the option "high precision mouse" and is working normally, the most strange is that i enabled again the option and the error don't appeared again (for the time i've tested, an equivalent to 1h30m).

Thank you so much.

**Comment by peppy** [comment]
Closing for now. Please let us know if it comes back.
