### ISSUE TITLE
osu!lazer for Android and Linux.

### ISSUE THREAD

**Issue by LinuxGamer** [ppy/osu#1394]
I know this is not a place to ask questions but, do you guys have any predictions of launching the osu!lazer for Android and Linux? (without the need of any extra coding)

**Comment by VPeruS** [comment]
As linux user, it work nice, no extra code required for linux user to launch it. There are even package for arch linux https://aur.archlinux.org/packages/osu-lazer-git.

**Comment by LinuxGamer** [comment]
i don't use arch bro

**Comment by LinuxGamer** [comment]
I already tried to open the game here, but the game doesn't open

**Comment by peppy** [comment]
one we are on core we will likely release per-architecture packages. i'd say within a month.
