### ISSUE TITLE
Autoplay and Cinema mod show "1 January 0001" as the play date

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#13940]
**Describe the bug:** As title. Without those mods, score panels show the correct date and time.

**Screenshots or videos showing encountered issue:** 

- Normal score
![1](https://user-images.githubusercontent.com/43073074/126246715-2ca12f7e-afe1-43f2-8bd5-11f1fe297c62.png)

- With Cinema
![2](https://user-images.githubusercontent.com/43073074/126246535-39e7b1e0-f45c-4c7e-9da0-6cdc11c9a3df.png)

- With Autoplay
![3](https://user-images.githubusercontent.com/43073074/126246549-b4dde587-9005-49b5-86ef-ad68b3bf780c.png)

**osu!lazer version:** `2021.720.0-lazer`

**Comment by peppy** [comment]
I'm thinking the correct direction for such scores is to not show the "played on" date at all. @smoogipoo thoughts on this one?

**Comment by smoogipoo** [comment]
I can get behind that.
