### ISSUE TITLE
Osu causes Xorg coredump when kwin compositing is suspended.

### ISSUE THREAD

**Issue by iliekprogrammar** [ppy/osu#13950]
**System information**:
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.22.3
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.12.16-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-4310M CPU @ 2.70GHz
Graphics Processor: Mesa DRI Intel® HD Graphics 4600
```

**Describe the bug:** Osu causes Xorg coredump under the condition that kwin's compositing is suspended. There's 2 ways of suspending kwin's compositing features:
1. Check ``Allow applications to block compositing`` checkbox in ``System Settings > Display and Monitor > Compositing``.
2. Execute ``qdbus org.kde.KWin /Compositor suspend``.

The workaround seems to be to just avoid blocking kwin compositing features while Osu is running. Let me know if other info is needed.

**osu!lazer version:** Running osu 2021.707.0.0 on .NET 5.0.6, Environment: Linux (Unix 5.12.16.1), 4 cores

**Logs:** (Relevant(?) logs):
- [osu/runtime.log](https://github.com/ppy/osu/files/6848471/runtime.log)
- [osu/performance.log](https://github.com/ppy/osu/files/6848470/performance.log)
- captured through ``osu-lazer >xserver-kill.log 2>&1``: ``X connection to :0 broken (explicit kill or server shutdown)``.
- [journalctl.log](https://github.com/ppy/osu/files/6849547/journalctl.log).
- dmesg and other osu logs provide nothing of relevance or surmounted by other logs. It seems that osu doesn't log anything about this issue though, since ``runtime.log`` and ``performance.log`` are unchanged when i replicate the bug.

**Similar issues:** #12001. however, that issue merely involves kwin compositing bugs while this one involves Xorg.

**Comment by iliekprogrammar** [comment]
i just realized there's a new release. i'll update to 2021.720 and see if anything changes.

**Comment by bdach** [comment]
As in the issue linked, I'm not sure what you're expecting us to do here if there's absolutely no error information to go off of. I continue to develop the game on a machine with another compositor (compton) on it and it runs without crashing.

**Comment by iliekprogrammar** [comment]
even as small as to document the workaround somewhere, that's enough for me. i'll leave it to you to close it or not.

**Comment by bdach** [comment]
Going to go ahead and close indeed as non-actionable / low priority. Will reopen if conclusive actionable information is provided that this is indeed caused by something the game does (rather than however many other pieces could be causing this failure, including but not limited to: SDL, kwin, xorg, the distro itself...)
