### ISSUE TITLE
User mods don't update correctly when freemods list changes

### ISSUE THREAD

**Issue by Muffyn** [ppy/osu#13956]
**Describe the bug:** 
I found a way to get players to have disallowed freemods in multiplayer. They can play the map as normal with these glitched mods enabled but their score does not submit.
forcemod = "mods" menu, freemod= "freemods" menu

**Screenshots or videos showing encountered issue:** 
First video shows how to reproduce.
1. Flashlight freemod is toggled off through "freemods" menu - works correctly.
2. Hidden forcemod is toggled on in "mods" menu, then immediately toggled back off. This disables Hidden in the "freemods" menu and updates both players - works correctly (though maybe Hidden freemod should automatically be reenabled to be intuitive to the player?).
3. Hard Rock forcemod is toggled on in "mods" menu and map is selected. Player1 correctly loses Hard Rock, but Player2 keeps Hard Rock. The map correctly shows Hard Rock forcemod. Next, Hard Rock forcemod is toggled off and map is selected again. Player2 incorrectly still has Hard Rock enabled, even though it is no longer an allowed freemod.
https://www.youtube.com/watch?v=iSzgPY8NhXw

Player2 gets to play the map with the mods they visibly have selected, but their score does not show up in results:

https://user-images.githubusercontent.com/33764011/126403999-13c6b7a7-8d6e-4b02-b3b7-44f52e8c8c97.mp4

Also, when player2 attempts to change their mods, any glitched mods will automatically be removed.

**osu!lazer version:** 
2021.720.0

**Logs:**
accidentally overwrote by relaunching, but any errors should probably only show for Player2

---

Kind of a convoluted method, but players could definitely stumble upon this accidentally, especially when the lobby host is shifting a lot, and it's not intuitive for the players to fix.

The main bug here might just be forcemod only removing freemod from Player1, not any other players (0:30 in video 1, Hard Rock is visible twice).

**Comment by frenzibyte** [comment]
The linked youtube video https://www.youtube.com/watch?v=iSzgPY8NhXw is private.

**Comment by Muffyn** [comment]
Sorry, changed it to unlisted now

**Comment by frenzibyte** [comment]
I think this is basically what this issue thread is pointing to:

https://user-images.githubusercontent.com/22781491/126414845-6ee61631-ced6-475d-b1b6-0d418542debc.mp4

Basically that whenever the host sets a previously freemod as a "required" mod, other users who have that freemod in their `UserMods` list will not be correctly updated to have that removed.

This should also be validated server-side, I'll look into doing that as well.

**Comment by smoogipoo** [comment]
Rather than just validating server-side, it should be the server being authoritative in changing user mods in the first place for this case.

**Comment by peppy** [comment]
Without checking I'm *pretty sure* the server side logic is already correct, but the client is just not aware that it needs to update its mods.

**Comment by frenzibyte** [comment]
The issue has now been resolved with the [server-side fix](https://github.com/ppy/osu-server-spectator/pull/68). Client still has its own `UserMods` validation logic to cover playlists rooms as well, so I think that can remain as-is for now.
