### ISSUE TITLE
Client is unable to join multiplayer room when password is a space character

### ISSUE THREAD

**Issue by DavidHusicka** [ppy/osu#13966]
**Describe the bug:** 

When room password is set to the space character (https://en.wikipedia.org/wiki/Space_(punctuation)), any client trying to connect will get error stating that the password is wrong despite being correct.

**Screenshots or videos showing encountered issue:** 
![osu_2021-07-21_13-57-20](https://user-images.githubusercontent.com/25853767/126485954-64815ab5-ad19-499e-aeba-2c8a5dd91518.png)

**osu!lazer version:** 

2021.720.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6855504/database.log)
[network.log](https://github.com/ppy/osu/files/6855505/network.log)
[performance.log](https://github.com/ppy/osu/files/6855506/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6855507/runtime.log)

**Comment by peppy** [comment]
This is due to the web request not escaping correctly.
