### ISSUE TITLE
Incorrect icons in beatmap details window

### ISSUE THREAD

**Issue by jkl2k2** [ppy/osu#13968]
**Describe the bug:** When viewing beatmap details (hitting the "Details..." button on a map after right clicking it), the icons representing BPM, circle count, and slider count have incorrect icons next to their values. They just show a blank circle icon.

**Screenshots or videos showing encountered issue:**
![osu_2021-07-21_12-28-38](https://user-images.githubusercontent.com/24350667/126549234-3c2a7ba0-8dcc-44c8-8c2f-660ce2952869.jpg)

**osu!lazer version:** 2021.720.0-lazer

**Logs:**
[database.log](https://github.com/ppy/osu/files/6858367/database.log)
[performance.log](https://github.com/ppy/osu/files/6858369/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6858370/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6858371/updater.log)

**Comment by bdach** [comment]
Considering the impending redesign at #13712, this is probably pretty low priority as these icons look to be gone from the new design. But I suppose if someone wants to get their feet wet in lazer development then this is about as good a task as any. The proper icons are defined [here](https://github.com/ppy/osu/blob/master/osu.Game/Beatmaps/BeatmapStatisticIcon.cs).

**Comment by MishterKirby** [comment]
I would like to attempt correcting this

**Comment by peppy** [comment]
The reason they are "wrong" is because the correct icons are not in the font. You're welcome to update it, but make sure you create a reproducible flow for doing so in the future. You'll need to see how this is done in osu-web (which I think may have since moved to svg).

**Comment by Theighlin** [comment]
This issue can be closed.
