### ISSUE TITLE
Sound when osu! is in background and Pause/Death Menu

### ISSUE THREAD

**Issue by chikahide** [ppy/osu#1397]
When you put osu! in background, we can always hear the sound of buttons

Video: 
https://streamable.com/ywuuz

Also, once you lose a map, the game displays the death menu, except that if you press the pause key, the pause menu will superimpose the death menu.

https://i.imgur.com/3Yhv85P.png

**Comment by swoolcock** [comment]
These should be raised as two separate issues, but I would say the background sounds are working as intended.

**Comment by peppy** [comment]
Please file separate issues as separate issues.

Also one is a duplicate of #1369
