### ISSUE TITLE
Beatmap background not showing in playlist/mulitplayer song select

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#13974]
**Screenshots or videos showing encountered issue:** 
![osu_2021-07-21_21-31-22](https://user-images.githubusercontent.com/35318437/126590148-f3dd17a5-53c1-465e-a7ac-aff2b7188cff.jpg)

**osu!lazer version:** Since https://github.com/ppy/osu/pull/13946

**Comment by peppy** [comment]
I'm guessing this has to do with the change of where the component is loaded (against the current screen rather than the screen stack, see https://github.com/ppy/osu/pull/13946/files#diff-26417f10ac2c232c62e2413df2f3639f6d1448de497988eadab3237d4411342fR168).
