### ISSUE TITLE
Text overflow in playlist item

### ISSUE THREAD

**Issue by Henry-YSLin** [ppy/osu#13973]
**Describe the bug:** 
When the beatmap title is too long, the text simply goes under the "view results" button and gets clipped at the edge of the playlist item, which looks weird.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/25472513/126583225-8e07d423-4b30-4fb4-9bde-ded696fcfbcd.png)

**osu!lazer version:** 2021.720.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6859715/database.log)
[network.log](https://github.com/ppy/osu/files/6859717/network.log)
[performance.log](https://github.com/ppy/osu/files/6859718/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6859719/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6859720/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/6859722/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/6859723/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6859724/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6859725/updater.log)

**Comment by frenzibyte** [comment]
A redesign is upcoming for the multiplayer/playlists screen, but I guess there's no harm in truncating text there.
