### ISSUE TITLE
Beatmap listing in-game repeats if content is scrollable

### ISSUE THREAD

**Issue by Tudi20** [ppy/osu#13985]
**Describe the bug:** 
If you search for beatmaps in in-game on beatmap listing and the results are plentiful enough for it to warrant a scrollbar the beatmaps will start to repeat/loop (while on the other-hand the web one just stops).

**Screenshots or videos showing encountered issue:** 
(Downloaded beatmap to highlight repeating)
![osu_2021-07-22_13-40-22](https://user-images.githubusercontent.com/13798839/126633651-527d9172-c67d-4ed0-b4cf-9210b5375bd1.jpg)
![osu_2021-07-22_13-40-46](https://user-images.githubusercontent.com/13798839/126633654-ec1db56e-6b09-4cc4-80c7-600d7408e8b9.jpg)

**osu!lazer version:** 
2021.720.0-lazer (Arch-based)

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/6861903/logs.zip)

**Comment by gagahpangeran** [comment]
Should be fixed in next release. See https://github.com/ppy/osu/pull/13959
