### ISSUE TITLE
Custom Rulesets Error (Ubuntu 18.04)

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#13995]
IMPORTANT: Your issue may already be reported.

**Describe the bug:** When attempting to load a custom ruleset in Lazer, the game gave me a notification that it couldn't import it on startup (If it's important, I'm using Ubuntu Bionic Beaver 18.04)

**Screenshots or videos showing encountered issue:** Unable to get a screenshot

**osu!lazer version:** 2021.720.0

**Logs:**
(All log files attached, idk which one the error would be under)
[logs.zip](https://github.com/ppy/osu/files/6871401/logs.zip)

**Comment by bdach** [comment]
The ruleset DLL in question is outdated and has to be updated to be compatible with the latest release. Either check for newer releases of the ruleset or wait for the author to update it.

**Comment by LumpBloom7** [comment]
According to the logs, mvis seems to be the culprit of your problems, and should be reported over there. The project has been consolidated into [lazer-sandbox](https://github.com/EVAST9919/lazer-sandbox), please refer to that repo to obtain the new ruleset file. You'd need to remove mvis from your ruleset folder as well.

**Comment by frenzibyte** [comment]
Also next time please open a discussions thread, this is not an immediate bug with osu!lazer you should open an issue thread for.
