### ISSUE TITLE
Beatmap listing is not fully translated into Belarusian language

### ISSUE THREAD

**Issue by z0rfix** [ppy/osu#13997]
Lazer 2021.724.0
https://i.imgur.com/JwyK3fg.jpg

**Comment by Game4all** [comment]
The translations of the in-game overlays are sourced from their web counterparts. As such, this indicates that the Belarus translation may either be missing non translated strings or that the translations aren't up to date. Upon looking on web it seems that the strings simply aren't translated at all.

**Comment by z0rfix** [comment]
There is a translation on the osu website and on the crowdin (100% translated on Belarusian)
