### ISSUE TITLE
Crash while viewing changelogs on the "lazer" stream

### ISSUE THREAD

**Issue by MineCommanderCN** [ppy/osu#13993]
**Describe the bug:** 

1. Open osu!, click Changelog on the top bar;

2. Go to the "Lazer" version;

3. Wait a few seconds and game crashes.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/59791306/126767466-021c7825-9bf2-445e-b9c4-a82776cb5609.mp4

Sorry that I can't record audio due to the device limitation.

**osu!lazer version:** 

2021.720.0-lazer, running on MagicUI 3.1.1 (based on Android 10) using Honor ViewPad 6.

**Logs:**

[Logs.zip](https://github.com/ppy/osu/files/6868008/Logs.zip)

**Comment by peppy** [comment]
Broken by the following comment content:

```
My tablet doesn't work :(
It's a Huion 420 and it's apparently incompatible with OpenTablet Driver. The warning I get is: "DeviceInUseException: Device is currently in use by another kernel module. To fix this issue, please follow the instructions from https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#arg    umentoutofrangeexception-value-0-15" and it repeats 4 times on the notification before logging subsequent warnings. 
Checking the logs, it looks for other Huion tablets before sending the notification (e.g.
 "2021-07-23 03:52:33 [verbose]: Detect: Searching for tablet 'Huion WH1409 V2'
 20 2021-07-23 03:52:33 [error]: DeviceInUseException: Device is currently in use by another kernel module. To fix this     issue, please follow the instructions from https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#arg    umentoutofrangeexception-value-0-15") 
I use an Arch based installation of Linux and the tablet runs perfectly with Digimend kernel driver, with area configuration, pen pressure, etc. On osu!lazer the cursor disappears until I set it to "Borderless" instead of "Fullscreen" and even after it shows up, it goes to the bottom left corner as soon as a map starts. 
I have honestly 0 idea of whats going on at this point.
```

Fault is either in `MessageFormatter.FormatText` or `LinkFlowContainer.AddLinks`. Will require a framework side fix.

I've hidden the comment for now to alleviate the crashes.

**Comment by bdach** [comment]
The issue is caused by the pasted log lines. In particular, the log timestamps (`03:52:33`) are being parsed as editor timestamps. And the timestamp regex is quite greedy - it'll consume the rest of the line as long as there's no dash in it:

https://github.com/ppy/osu/blob/8eb42614060bee5e0ec217bf24485b516b8f96f1/osu.Game/Online/Chat/MessageFormatter.cs#L45-L46

The crash happens because that line has a nested link in it and `LinkFlowContainer` obviously fails to deal with links nested in links (but I don't fault it for not being able to).

I'd say this is a blatant misuse of `MessageFormatter` - it was intended for chat and should not be used to parse comments for links. The way forward is probably actually using the markdown representation of comments from web?

**Comment by CloudyWhale** [comment]
I've done the same thing on fireos (based on android) and windows 10 and it did not crash for me

**Comment by bdach** [comment]
That's because the comment in question was hidden. Please read this thread.

**Comment by smoogipoo** [comment]
Using markdown sounds like the way to go.

**Comment by gagahpangeran** [comment]
There's slightly different behaviour for image rendering in wiki page and comment markdown. The image in comment has this minimum and maximum height value in web.

https://github.com/ppy/osu-web/blob/6dc5188ef1a15ca90b53500aa883c01cfe2956a2/resources/assets/less/bem/osu-md.less#L31-L35

Maybe I can work on this and hide the image for the meantime.

**Comment by smoogipoo** [comment]
The bigger issue is that the API doesn't yet provide the message in markdown format. I mentioned in #osu-web but also https://github.com/ppy/osu-web/issues/7922.

**Comment by bdach** [comment]
I'm slightly confused. The string that caused the crash was in a user comment, and not a changelog entry...?

**Comment by smoogipoo** [comment]
You're right, I misread.

**Comment by gagahpangeran** [comment]
@smoogipoo are you working on this?

If not, I can work on this and open the PR tonight.

**Comment by smoogipoo** [comment]
Go for it.
