### ISSUE TITLE
Broken accuracy and combo on results screen

### ISSUE THREAD

**Issue by z0rfix** [ppy/osu#13994]
https://i.imgur.com/JcGDJJ5.jpg
Logs https://disk.yandex.by/d/34RWSB5BplpfFg

Lazer 2021.720.0

Windows 8.1 (x64)

**Comment by bdach** [comment]
This looks a lot like #1488. Going to close this as duplicate and reopen that one.

**Comment by smoogipoo** [comment]
It could also be something broken with the Russian locale? Are you using the Russian language in-game @z0rfix?

**Comment by z0rfix** [comment]
I'm using belarussian language. For some reason its fixed by itself in next session

**Comment by smoogipoo** [comment]
Sounds like it probably is related to the above issue then.
