### ISSUE TITLE
Scroll wheel can change volume where it shouldn't

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14000]
**Describe the bug:** I started the game unfocused (as in #12644 ) and in the main menu i alt-tabbed out and back in to fix the focus, but i also adjusted the volume at the same time. While the threads did start running as expected, i could no longer scroll the song select. To fix it without restarting the game, i had to change the volume with alt-arrows, and then it started scrolling the beatmaps.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/53081750/126871407-e8a69a3a-5b0a-4eba-8566-84a0a8e91ed7.mp4

**osu!lazer version:** 2021.724.1-lazer

Logs and video show different beatmaps but same behaviour.
**Logs:** [logs.zip](https://github.com/ppy/osu/files/6872566/logs.zip)

**Comment by peppy** [comment]
Your alt key is stuck. Pressing alt again will fix the issue.

This is a common thing on windows, hard to say whether it's out fault but we are tracking a similar issue at https://github.com/ppy/osu/issues/11489.
