### ISSUE TITLE
osu!direct completely ignores limiting search terms

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#14008]
expected(osu!web):
![searcherror1](https://user-images.githubusercontent.com/44514667/126886531-cec838d8-25af-4172-91a6-b962a01f75c4.PNG)
results bring up mania maps that have at least one 10 key mania beatmap, as normal

actual(osu!lazer):
![osu_2021-07-24_22-16-37](https://user-images.githubusercontent.com/44514667/126886563-88c25b9f-3b18-48bc-a018-50d3b4a74eb2.jpg)
results bring up maps that contain "key", abnormal result

the search ignores the limiter part and uses the initial word as the keyword, bringing up results with the keyword instead of results within the bounds of the limiter

version: 2021.724.1

**Comment by smoogipoo** [comment]
This probably needs osu!web support? cc @nanaya / @notbakaneko

**Comment by nanaya** [comment]
It's just part of query string. It looks like lazer double escapes query string so it sends `=` as `%253D` instead of `%3D` (also causes other weirdness like `&hello` yielding nothing).

**Comment by bdach** [comment]
This unintentionally regressed after https://github.com/ppy/osu-framework/pull/4628 because the game had locally percent-encoded query string values for the beatmap search request, which I was not aware of (but probably should have checked for).
