### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by DiiMeX** [ppy/osu#14011]
when i try to launch update 2021.724.1 the process freezes
![1](https://user-images.githubusercontent.com/87930646/126894767-2ab70217-5268-4e2e-9629-253005749680.png)

**Comment by frenzibyte** [comment]
Fill the issue template please:
![CleanShot 2021-07-25 at 12 43 02](https://user-images.githubusercontent.com/22781491/126894801-e3c662b6-d58b-4d6c-a606-42cd1234016a.png)

**Comment by bdach** [comment]
Closing until information requested above is provided.
