### ISSUE TITLE
Playfield vanishes in multiplayer

### ISSUE THREAD

**Issue by takoz53** [ppy/osu#14049]
**Describe the bug:** When spectating in multiplayer, the playfield of the players vanish, but the circles etc. remain with the default multiplayer background.

**How it happened (Maybe replicatable?):** 
1. Leave mid-song
2. Start spectating
3. Have someone leave the game while playing
4. Continue watching, it should happen

Happened in RLC version of [The Pretender](https://osu.ppy.sh/beatmapsets/79498#osu/221777).

**Screenshots or videos showing encountered issue:** 
[Bug Screenshot](https://puu.sh/HZRWu/23933cf129.jpg)
**osu!lazer version:** 2021.724.1

[**Logs**](https://puu.sh/HZRXl/6ecb204b60.zip)

**Comment by peppy** [comment]
If possible could you please take a video showing this happening? Also, what is your background dim set to?

**Comment by Theighlin** [comment]
I think i remember seeing something like this, but can't confirm due to linked screenshot not being available.
That said, multiplayer spectator has seen some work so maybe this can be closed as stale?
