### ISSUE TITLE
Osu!lazer Tournament loading screen

### ISSUE THREAD

**Issue by Becanda** [ppy/osu#14055]
Describe the bug: 
i'm currently doing some testing to osu!lazer tournament, yesterday its doing fine but today when i want to open it again it keeps loading like screenshot down below. I already wait the loading for almost 10 minutes and its keep spinning.

am i doing something wrong?

**Screenshots or videos showing encountered issue:** 
![a](https://user-images.githubusercontent.com/88150487/127510488-50e306b3-153f-4475-ac92-39c18f0b7d2d.PNG)

**osu!lazer version:** 2021.724.1.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6901283/performance.log)

**Comment by peppy** [comment]
Please re-read the issue template. You are not attaching your logs correctly.

**Comment by Becanda** [comment]
ahh sorry!
**Logs:**
[logs.zip](https://github.com/ppy/osu/files/6901358/logs.zip)

is it correct?

**Comment by peppy** [comment]
It looks like your `drawings.txt` file is not in a good state. Could you please attach that, and also try moving it out of the folder to see if it resolves the issue?

**Comment by Becanda** [comment]
where is drawing.txt file? i cant find it
![image](https://user-images.githubusercontent.com/88150487/127514103-9e56e80a-5d3c-4da1-ad61-01a0afdb14f2.png)

**Comment by peppy** [comment]
Easiest if probably just to zip and attach the whole `tournaments` folder.

**Comment by Becanda** [comment]
[tournaments](https://drive.google.com/file/d/1FoRbrMqHwBL9M-X0wFslVgBygD739RNm/view?usp=sharing)

i cant upload it in here so i attached in google drive, is it okay?

**Comment by peppy** [comment]
Yes that's fine, thanks.

I'm looking into it and have identified a couple of issues, but if possible, could you please try running a previous release of lazer and see if this helps? You can just run `install.exe` from a [previous release](https://github.com/ppy/osu/releases/tag/2021.707.0-lazer) and it will downgrade you until the next time you start the game (without the `--tournament` specification).

**Comment by Becanda** [comment]
Hi peppy, 

I already downgrade my osu lazer version to 2021.707.0-lazer but still have the same issue

**Comment by peppy** [comment]
Please provide logs. Also please try the latest release.

**Comment by peppy** [comment]
@Becanda did you ever figure this out? we've made some huge progress in terms of the reliability of the tournament client startup, so please let me know how things are looking now. i'm going to close the issue as it's a bit outdated now.
