### ISSUE TITLE
osu!lazer crashing

### ISSUE THREAD

**Issue by nubbyy** [ppy/osu#1405]
![image](https://user-images.githubusercontent.com/33008137/31865582-cd9f8952-b725-11e7-9eae-c371f0204615.png)
can someone tell me why osu!lazer s crashing?

**Comment by peppy** [comment]
Please provide crash logs from Event Log at very least.

**Comment by NITPRUDO** [comment]
As peppy said, please provide crash logs and some additional information. This isn't enough information to let us help you with the issue. With that said, did you try reinstalling the game? When does the game crash?

**Comment by peppy** [comment]
Closing due to lack of detail

**Comment by FirstSintax** [comment]
Hello I have the same problem, how can I provide crash logs?

**Comment by Aergwyn** [comment]
Look into `%APPDATA%/osu/logs` and see if you have logfiles in it. If they exist and the latest content timestamps match your last crash then you can try uploading them so it's possible to have a look at them.
The most interesting would be the `runtime.log` first.

**Comment by FirstSintax** [comment]
I am late but here:

[runtime.log](https://github.com/ppy/osu/files/1624772/runtime.log)
[performance.log](https://github.com/ppy/osu/files/1624773/performance.log)

**Comment by peppy** [comment]
Looks like your GPU doesn't support 4096x4096 textures. What graphics card are you running?

**Comment by FirstSintax** [comment]
I have Intel(R) HD Graphics

**Comment by NITPRUDO** [comment]
That won't help. What model specifically?

**Comment by FirstSintax** [comment]
How do I check the model?

**Comment by Aergwyn** [comment]
😕 A bit of googling is no problem in our time where everything is accessible online. But still here is a shortcut.

1) Rightclick empty space on your desktop and choose `display settings`.
2) On the opening window scroll down and click on the bottom most option that says `advanced display settings`. It may happen that you can straight skip to 3).
3) Then again the bottom most option called "adapter properties".

On the newly opened window you can see some things about your graphic card. I see this for example:
![qq](https://user-images.githubusercontent.com/27222621/35198619-a26fb0cc-fef1-11e7-81d8-c33a1fc4bf0b.png)

**Comment by aQaTL** [comment]
You can also type in cmd `wmic path win32_VideoController get name`, which will list names of all detected cards.

**Comment by FirstSintax** [comment]
![model](https://user-images.githubusercontent.com/9309739/35198774-e2222770-fec1-11e7-8751-ed6b6f931312.PNG)

**Comment by jacksonisiah** [comment]
Maximum resolution supported by that is 2560 x 1600

**Comment by FirstSintax** [comment]
Oh ok thanks

**Comment by jacksonisiah** [comment]
try running at a lower resolution, that should help

**Comment by jorolf** [comment]
shouldn't it be possible to detect the maximum size and override the standard 4096x4096?

**Comment by jorolf** [comment]
@jacksonisiah I think you're talking about screen resolution, right? the exception comes from too large textures

**Comment by jacksonisiah** [comment]
oh yeah. sorry for the lack of information. 

and yes, it should be able to.

**Comment by jorolf** [comment]
nevermind, the framework already does that
