### ISSUE TITLE
Maps longer than 1 hour do not display the correct map length

### ISSUE THREAD

**Issue by broken-egg** [ppy/osu#14073]
This appears to happen in all maps that are longer than one hour, but hear is a preview with this map: https://osu.ppy.sh/beatmapsets/1236584#osu/2570401

Here is a video displaying what happens when the time reaches 1 hour: 
https://user-images.githubusercontent.com/38958632/127721497-9a0b274f-5934-40d2-87df-2c7e179fa406.mp4

and also a screenshot of the incorrect time being displayed: 
![Screenshot (4)](https://user-images.githubusercontent.com/38958632/127721531-5b03466a-f555-431b-99d0-a9ffeb9cf964.png)

It also displays incorrectly in the in-game beatmap page
![image](https://user-images.githubusercontent.com/38958632/127721628-727d52f3-a0ab-4967-b09b-06cbdec1f676.png)

Here is the map time correctly displayed on the osu! website
![image](https://user-images.githubusercontent.com/38958632/127721672-18d5e196-0692-48af-af9d-3eebad8bb0ab.png)
(the time also shows correctly on the stable client)

**Comment by iSimpFor** [comment]
what i think is happening is that the hour part of the length display is getting cut off, search still works normally but it may seem off with the hour part of the length display missing
