### ISSUE TITLE
Accidentally hitting a gameplay key cancels pause

### ISSUE THREAD

**Issue by SonoSooS** [ppy/osu#14075]
**Describe the bug:** 
If you bind pause to NUMPAD_PLUS and bind standard buttons to arrow LEFT and arrow RIGHT respectively, it becomes impossible to pause if you accidentally hit NUMPAD_6 with NumLock off during the pause timer.

Is this a bug, or a feature?
Is it possible to add a toggle for this, or would it break the "pausing is cheating" feature?

**osu!lazer version:** 
2021.724.1-lazer

**Comment by peppy** [comment]
Please open a discussion instead, and provide video showing what you mean, along with logs etc.

**Comment by SonoSooS** [comment]
#14077

**Comment by SonoSooS** [comment]
It turns out that keybindings have nothing to do with this issue.

Pressing any of these keys during the pause is enough to cancel the pause:
- UP/DOWN/LEFT/RIGHT
- F1 to F12
- CTRL, ALT, SHIFT
- RETURN, ENTER
