### ISSUE TITLE
osu!lazer will not open

### ISSUE THREAD

**Issue by kermitthefroggo** [ppy/osu#14087]
I have gotten a lot of help, but nothing worked. my device is windows 10. 
event log
[osu lazer not loading.zip](https://github.com/ppy/osu/files/6911839/osu.lazer.not.loading.zip)
i really wish to try out lazer as i only have ever experienced it on an android phone at 10fps. i hope i could get help ASAP.

**Comment by frenzibyte** [comment]
Please begin by filling the bug issue template so we can help you pretty quickly. The logs at `%appdata%/osu/logs` are what's mostly required in this case.

**Comment by kermitthefroggo** [comment]
> Please begin by filling the bug issue template so we can help you pretty quickly. The logs at `%appdata%/osu/logs` are what's mostly required in this case.

i have given the event log, now i will give the logs =
[runtime.log](https://github.com/ppy/osu/files/6911848/runtime.log)
[session.log](https://github.com/ppy/osu/files/6911849/session.log)
[update_success.log](https://github.com/ppy/osu/files/6911850/update_success.log)
And also, how would the osu!lazer logs be located in the osu! folder and not the osulazer folder

**Comment by frenzibyte** [comment]
That's the logs for osu!stable, osu!lazer's logs folder resides in `%appdata%/osu` (`AppData/Roaming/osu`).

Does that folder not exist for you?

**Comment by kermitthefroggo** [comment]
oh i didnt know sorry! you didnt say if it was in local or any of the other folders so my bad, the logs for lazer are here 
[runtime.log](https://github.com/ppy/osu/files/6911858/runtime.log)

also please bare with me as i run aon a slow laptop

**Comment by frenzibyte** [comment]
```
2021-07-31 20:52:51 [verbose]: GL Initialized
2021-07-31 20:52:51 [verbose]: GL Version:                 1.1.0
2021-07-31 20:52:51 [verbose]: GL Renderer:                GDI Generic
2021-07-31 20:52:51 [verbose]: GL Shader Language version:
2021-07-31 20:52:51 [verbose]: GL Vendor:                  Microsoft Corporation
2021-07-31 20:52:51 [verbose]: GL Extensions:              GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
```
Your issue is one another case of the GDI generic OpenGL driver (see [here](https://github.com/ppy/osu/issues?q=is%3Aissue+GDI+generic+is%3Aclosed)). Try updating your drivers to latest version in hopes it helps, otherwise please stay tuned for DirectX support, which may come soon within the next 2 months.

**Comment by kermitthefroggo** [comment]
thank you.
