### ISSUE TITLE
Inconsistent ordering of adjacent hitresults

### ISSUE THREAD

**Issue by facespkz** [ppy/osu#14089]
**Describe the bug:** Lazer sometimes shows hitresults behind previous ones. This can make it difficult to read them, especially with skins that obscure the playfield with an opaque hit###.png.

**Screenshots or videos showing encountered issue:** 

### Stable

https://user-images.githubusercontent.com/22137884/127753376-a471a8e5-56da-4030-aa6a-ad51d13eaf9c.mp4

### Lazer

https://user-images.githubusercontent.com/22137884/127753379-6261c633-0b11-4894-9c5f-e57f95d282b2.mp4

**osu!lazer version:** 2021.731.0.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/6911887/database.log)
[network.log](https://github.com/ppy/osu/files/6911888/network.log)
[performance.log](https://github.com/ppy/osu/files/6911889/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6911890/runtime.log)

**Comment by bdach** [comment]
To clarify, do you mean that the Z ordering of the hitresults themselves (among each other, not in relation to the hitobjects) is incorrect?

I can see how this could happen as a side effect of judgement pooling. May want to set depth to something derived from `Time.Current` on applying.

**Comment by facespkz** [comment]
Yeah, that's what I meant. I guess the title was a bit too simplistic.
