### ISSUE TITLE
Joining a playlist potentially shows settings screen instead of room

### ISSUE THREAD

**Issue by peppy** [ppy/osu#14091]
This looks like it happens for a playlist with difficulties from different rulesets, where the current game's ruleset doesn't match the first playlist item.

When it does match, the room opens correctly:

https://user-images.githubusercontent.com/191335/127768011-46ae3d87-cfba-4121-be62-afe3b9f78082.mp4

When it doesn't match, the settings are shown and it's not possible to get into the actual room:

https://user-images.githubusercontent.com/191335/127768038-40f6e8f3-22ff-40cc-8671-596a167d0de3.mp4

**Comment by bdach** [comment]
On a quick check the sequence of events here is as follows:

* The playlist is joined, switching ruleset from (current user ruleset) to (ruleset of the first playlist item)
* This changes filter criteria in the (still-visible) playlists screen
* Therefore a re-poll of the playlist rooms is triggered
* This re-poll clears all rooms in the room manager
* If all of this occurs *after* the actual room is joined and set, the settings overlay will display (ie. this is a race - if the actual room set loses the race and executes after all of that, everything will work "as expected").

Feels like the lounge screen should take exclusive control over the current room, I think?
