### ISSUE TITLE
"Mute" metronome audio mutes on miss

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#14090]
**Describe the bug:** "Mute" metronome audio disappear on miss then reappear on unknown reason (Known reason is when track end or fail. but during map is still unknown.). This also effect replay as well.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/7066150/127756042-3d667fff-8deb-4328-9419-30ab561bbf73.mp4

Replay : https://drive.google.com/file/d/1cNpRRfkkudA2krPujn10XUCTfLJIo4NR/view?usp=sharing

Mod : HD + Mute (Final volume at combo 0)
Map : https://osu.ppy.sh/beatmapsets/1311371#osu/2868033

**osu!lazer version:** 2021.731.0-lazer

**Comment by peppy** [comment]
it’s supposed to silence on miss. that’s part of the mod?

**Comment by frenzibyte** [comment]
If I understand this issue correctly, it's showing that the metronome silences when the player misses on "muted" with zero final combo. I believe on this case, it is expected for the metronome to play forever and the track to be silenced forever.
