### ISSUE TITLE
Star ratings colour doesn't match new osu-web spectrum

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14118]
**Screenshots or videos showing encountered issue:** 
osu-web
![image](https://user-images.githubusercontent.com/53081750/128001470-a2027526-09ed-46e7-a484-3614c483b840.png)
osu!lazer
![image](https://user-images.githubusercontent.com/53081750/128001575-57ec63b8-f2ca-4307-9eac-fd931a49ab2e.png)
![image](https://user-images.githubusercontent.com/53081750/128001615-8946bff3-b70f-42bb-8129-01ec07971ee4.png)

**osu!lazer version:** 2021.731.0-lazer

**Comment by frenzibyte** [comment]
Keep in mind that due to osu!lazer having white difficulty icons over the difficulty colour itself, light colours do not look well:

![CleanShot 2021-08-03 at 13 55 37](https://user-images.githubusercontent.com/22781491/128004199-1d3df85e-0064-4838-bc3a-2e9a7fa9c252.png)

On my beatmap info redesign work, I've added support for the difficulty colour spectrum but as a `New` method and used it only for the redesign, and expecting it to be used for the other designs once they get implemented. 

Would like to hear the other's opinions on this.

**Comment by smoogipoo** [comment]
How does the above look with the following change?
```diff
diff --git a/osu.Game/Beatmaps/Drawables/DifficultyIcon.cs b/osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
index c62b803d1a..419b5d0ced 100644
--- a/osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
+++ b/osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
@@ -52,7 +52,7 @@ public new Vector2 Size
 
         private readonly Bindable<StarDifficulty> difficultyBindable = new Bindable<StarDifficulty>();
 
-        private Drawable background;
+        private Drawable icon;
 
         /// <summary>
         /// Creates a new <see cref="DifficultyIcon"/> with a given <see cref="RulesetInfo"/> and <see cref="Mod"/> combination.
@@ -90,32 +90,32 @@ private void load(OsuColour colours)
         {
             iconContainer.Children = new Drawable[]
             {
-                new CircularContainer
-                {
-                    RelativeSizeAxes = Axes.Both,
-                    Scale = new Vector2(0.84f),
-                    Anchor = Anchor.Centre,
-                    Origin = Anchor.Centre,
-                    Masking = true,
-                    EdgeEffect = new EdgeEffectParameters
-                    {
-                        Colour = Color4.Black.Opacity(0.08f),
-                        Type = EdgeEffectType.Shadow,
-                        Radius = 5,
-                    },
-                    Child = background = new Box
-                    {
-                        RelativeSizeAxes = Axes.Both,
-                        Colour = colours.ForDifficultyRating(beatmap.DifficultyRating) // Default value that will be re-populated once difficulty calculation completes
-                    },
-                },
-                new ConstrainedIconContainer
+                // new CircularContainer
+                // {
+                //     RelativeSizeAxes = Axes.Both,
+                //     Scale = new Vector2(0.84f),
+                //     Anchor = Anchor.Centre,
+                //     Origin = Anchor.Centre,
+                //     Masking = true,
+                //     EdgeEffect = new EdgeEffectParameters
+                //     {
+                //         Colour = Color4.Black.Opacity(0.08f),
+                //         Type = EdgeEffectType.Shadow,
+                //         Radius = 5,
+                //     },
+                //     Child = background = new Box
+                //     {
+                //         RelativeSizeAxes = Axes.Both,
+                //     },
+                // },
+                icon = new ConstrainedIconContainer
                 {
                     Anchor = Anchor.Centre,
                     Origin = Anchor.Centre,
                     RelativeSizeAxes = Axes.Both,
                     // the null coalesce here is only present to make unit tests work (ruleset dlls aren't copied correctly for testing at the moment)
-                    Icon = (ruleset ?? beatmap.Ruleset)?.CreateInstance()?.CreateIcon() ?? new SpriteIcon { Icon = FontAwesome.Regular.QuestionCircle }
+                    Icon = (ruleset ?? beatmap.Ruleset)?.CreateInstance()?.CreateIcon() ?? new SpriteIcon { Icon = FontAwesome.Regular.QuestionCircle },
+                    Colour = colours.ForDifficultyRating(beatmap.DifficultyRating) // Default value that will be re-populated once difficulty calculation completes
                 },
             };
 
@@ -124,7 +124,7 @@ private void load(OsuColour colours)
             else
                 difficultyBindable.Value = new StarDifficulty(beatmap.StarDifficulty, 0);
 
-            difficultyBindable.BindValueChanged(difficulty => background.Colour = colours.ForDifficultyRating(difficulty.NewValue.DifficultyRating));
+            difficultyBindable.BindValueChanged(difficulty => icon.Colour = colours.ForDifficultyRating(difficulty.NewValue.DifficultyRating));
         }
 
         public ITooltip GetCustomTooltip() => new DifficultyIconTooltip();
```

**Comment by smoogipoo** [comment]
For reference, I believe this is the newest design:
![image](https://user-images.githubusercontent.com/1329837/128006144-d3f4b9df-55f3-4a21-8ed5-2cdec045f02f.png)
https://www.figma.com/file/DXKwqZhD5yyb1igc3mKo1P/Song-Select-Draft-2?node-id=0%3A1

**Comment by frenzibyte** [comment]
Yeah, I haven't thought about changing the icon display, but here's how it would look:

![CleanShot 2021-08-03 at 14 13 31](https://user-images.githubusercontent.com/22781491/128006293-0be6e429-f506-4a14-bd9a-84464df33fab.png)

While this looks somewhat tolerable, the bad part is here:

![CleanShot 2021-08-03 at 14 14 29](https://user-images.githubusercontent.com/22781491/128006324-f623f891-8268-4b2c-b4d4-cc352819f542.png)

I think the colour update can happen after the beatmap listing and beatmap cards get redesigned, and maybe even after the song select gets redesigned as well. I'll define it and use it for the redesigned beatmap info overlay as a beginning.

**Comment by smoogipoo** [comment]
Tbh, I think that's _tolerable_ until the components get redesigned.

**Comment by peppy** [comment]
I prefer the version @frenzibyte had.

**Comment by smoogipoo** [comment]
Are you fine getting that in as-is then?

**Comment by peppy** [comment]
It’s fine to open a PR. I might make some slight changes to the card to make it bearable but i think it’s fine to push the colour update through.

**Comment by bdach** [comment]
Could do what web did before the new card design came in, which is make the background dark rather than pure white.

**Comment by peppy** [comment]
That was my thinking, yep.
