### ISSUE TITLE
Wacom driver tablet settings reset on start/window focus since 2021.731.0

### ISSUE THREAD

**Issue by kindlyfire** [ppy/osu#14141]
**Describe the bug:** I use the Linux wacom driver to set up my tablet area (using `xsetwacom`) before starting osu!. Since 2021.731.0, osu! seems to reset my area settings on start and every time I focus the window. Tablet support and high precision mouse are disabled in the settings.

This setup worked fine before 2021.731.0 (reverted to 2021.724.1 and it does not interfere with my tablet settings)

**osu!lazer version:** 2021.731.0

**Logs:** [runtime.log](https://github.com/ppy/osu/files/6944726/runtime.log)

**Comment by mk56-spn** [comment]
Make sure you have the in-game tablet drivers off if you want to use your external wacom drivers otherwise it my override them . Do this by searching tablet in settings and disabling the setting that appears
