### ISSUE TITLE
Fix and re-enable ruleset-local tests

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1415]
Currently failing with missing project references (unable to find local DLLs for everything). Need to figure why transitive dependencies aren't locatable, hopefully without including every dependency with `<Private>`.

![unknown](https://user-images.githubusercontent.com/191335/31921430-57b3be9e-b8aa-11e7-8cf0-f3df4aa9ca4b.png)

**Comment by peppy** [comment]
This should be attempted post merging of https://github.com/ppy/osu/issues/1398

**Comment by smoogipoo** [comment]
This has since been fixed.
