### ISSUE TITLE
Incorrect legacy slider body transparency fade out

### ISSUE THREAD

**Issue by TheOmyNomy** [ppy/osu#14165]
**Describe the bug:** The latest update changed the legacy slider body incorrectly.

**Screenshots or videos showing encountered issue:**

Previously (2021.731.0):

![2021-731-0](https://user-images.githubusercontent.com/10572146/128617521-8da2bb5b-5225-4ebe-8df9-b943ca096952.png)

Currently (2021.808.0):

![2021-808-0](https://user-images.githubusercontent.com/10572146/128617528-67084e24-9206-4eb8-9fe3-3ccb293f04a9.png)

**osu!lazer version:** 2021.808.0

**Comment by frenzibyte** [comment]
Can you point out exactly where the difference is, I'm struggling to notice any.

**Comment by TheOmyNomy** [comment]
This is more noticeable near the edge of the body, but I believe the transparency fade out is incorrect, hence the stronger body colour.

Previously:

![2021-731-0_zoom](https://user-images.githubusercontent.com/10572146/128618040-e4e40601-8730-435f-b543-2881e12ee563.png)

Currently:

![2021-808-0_zoom](https://user-images.githubusercontent.com/10572146/128618046-951957d0-f75a-42e0-ab49-fef112ebfe29.png)

It's easier to see if you open both images in separate tabs and switch between them.

**Comment by frenzibyte** [comment]
Well, it's pretty hard to understand what was the issue at first, along with the chosen title which almost feels like it's stating the body itself to be shaped incorrectly.

I guess I can understand the issue now.

**Comment by TheOmyNomy** [comment]
My bad, sorry. Hopefully the new title is a better fit.

**Comment by peppy** [comment]
Is this reproducible with the `osu!classic` skin? If not, please provide your skin.

**Comment by TheOmyNomy** [comment]
It's harder to notice with the osu!classic skin, but it's still there. You can see it more easily with darker colours like the red sliders (beatmap colours were enabled).

Previously:

![2021-731-0-classic-1_zoom](https://user-images.githubusercontent.com/10572146/128624827-0f068714-8f48-47ee-9768-1723d752cdb7.png)

![2021-731-0-classic_zoom](https://user-images.githubusercontent.com/10572146/128624865-9c97281c-b07f-433a-8adb-6825805323cc.png)


Currently:

![2021-808-0-classic-1_zoom](https://user-images.githubusercontent.com/10572146/128624834-95bfba8e-7714-4e3b-8fb3-4b68393d2acf.png)

![2021-808-0-classic_zoom](https://user-images.githubusercontent.com/10572146/128624866-663d2067-1f5d-43f0-8974-d960ba807c24.png)

**Comment by bdach** [comment]
Looks like this will be a side effect of https://github.com/ppy/osu-framework/pull/4657 (the gamma-correct interpolation change), unfortunately.

Unsure how to proceed, as I *think* the old version was *technically* incorrect, but stable behaviour preservation and all that...
