### ISSUE TITLE
Changing match type does not update the online room in server database

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14163]
**Describe the bug:** After a couple of maps in peppy's team vs room were played, teams colour were no longer visible even though the room was still in the team vs mode. I tried replicating but couldn't.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/53081750/128615752-f6c4d1c1-f7f9-44d5-b3bb-e357f6dbd206.png)
![image](https://user-images.githubusercontent.com/53081750/128615757-9277f352-3804-4f4e-a0a3-f6cd616bebed.png)

**osu!lazer version:** 2021.808.0-lazer

**Comment by minasminas** [comment]
I think the issure here is **not** that the Team VS UI doesn't show, it is that the room type was changed after the room was created. So the real issue is that the icon in the multiplayer list doesn't update if you change the room type.

**Comment by frenzibyte** [comment]
This was stated to be an issue with the server, I'll dig further.
