### ISSUE TITLE
osu!lazer crashes/freezes up when playing a preview of a song after letting another preview of a song finish in osu!direct

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#14171]
after letting the first preview fully play in osu!direct, all sounds stop

trying to preview another song after that causes osu!lazer to freeze/crash(downloads will still be saved if you let them finished downloading and processing)

logs:
[performance-draw.log](https://github.com/ppy/osu/files/6950338/performance-draw.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/6950339/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/6950340/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/6950341/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/6950342/performance-gamethread.update.log)
[performance-update.log](https://github.com/ppy/osu/files/6950343/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6950344/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6950345/updater.log)
[database.log](https://github.com/ppy/osu/files/6950346/database.log)
[network.log](https://github.com/ppy/osu/files/6950347/network.log)
[performance.log](https://github.com/ppy/osu/files/6950348/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6950349/performance-audio.log)

version: 2021.808.0

**Comment by peppy** [comment]
Likely the same as https://github.com/ppy/osu-framework/issues/4671.

**Comment by bdach** [comment]
Yeah, confirmed to be the same thing.

**Comment by peppy** [comment]
A hotfix release has been pushed out to resolve this.
