### ISSUE TITLE
Solo game start game stuck on random position

### ISSUE THREAD

**Issue by AriosJentu** [ppy/osu#14184]
**Describe the bug:** When open solo game, a lot of times game shows me random moment in middle of the map as frozen. Never seen this before, and also bugreports like this one (this bug appeared after previous update, expecting as SDL bug). All steps and bug you can see on video below.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/6349084/128715314-21976d16-0e8e-4d4b-89e1-406f18f87e96.mp4

**osu!lazer version:** 
2021.809.0-lazer
OS: Manjaro Gnome
DE: IceWM
Kernel: 5.13.8-1-MANJARO
SDL Versions:
_SDL:_ 1.2.15-14
_SLD2:_ 2.0.14-1

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6954881/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6954882/runtime.log)

**Comment by frenzibyte** [comment]
What do you have threading mode set to? for reference.

**Comment by AriosJentu** [comment]
Threading - single mode. This bug appears on every map in solo mode, but at least at 50% of plays

**Comment by peppy** [comment]
This looks like an audio regression for sure (and may be a similar cause to the current spectator mode failures), going to bump up in priority for visibility.
