### ISSUE TITLE
InvalidStateChangeException: Cant change from Idle to Loaded

### ISSUE THREAD

**Issue by ackhack** [ppy/osu#14181]
**Describe the bug:** 
Got this error message while starting to play in mp. I got reverted to back to the Lobbymenu while the others started playing.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/43985368/128694556-15b7e989-f314-42e6-9595-4771211be3e5.png)
**osu!lazer version:** 
2021.809.0
**Logs:**
[network.log](https://github.com/ppy/osu/files/6953815/network.log)
[performance.log](https://github.com/ppy/osu/files/6953816/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6953817/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6953818/updater.log)
[database.log](https://github.com/ppy/osu/files/6953819/database.log)

**Comment by peppy** [comment]
Did you happen to be mashing the ready button when this happened? Just trying to figure out the order of events.

**Comment by ackhack** [comment]
was on my phone at the time, so no button smashing

**Comment by peppy** [comment]
How many others were in the room when you were playing?

**Comment by peppy** [comment]
Your log file shows that you never changed beatmaps in the play session, but it does look like you downloaded the beatmap for the lobby. Do you recall whether your game started playing the beatmap in the background before the match started?

One hypothesis is that the beatmap did not completely load, causing an issue in the ordering of events, but it would be useful to get any further details you remember from the flow that caused the failure.

**Comment by peppy** [comment]
The only way I can see this happening is the following flow, which is not protected client-side:

- User2 hits ready
- User1 starts match
- User2 hits not-ready before receiving the "begin loading" request
- User2's client received the "begin loading" and started loading (even though their last sent state change was `Idle`)
- User2's `Player` sends the `Loaded` state from `Idle`

There are two paths to fix this:
- The client should differentiate from a "not ready" request and an "abort load" request. This would allow the server to ignore the "not ready" incoming changes if the "begin load" request has been sent (the assumption is that the user still wants to play in the current match if they were ready a split second before it started)
- The local client should keep the last-sent `MultiplayerRoomUser` state and check it before performing a subsequent incoming request. This would allow the client to avoid attempting to load if the last send request was to not load.

I think the first solution is likely what we want.

**Comment by ackhack** [comment]
It happend on your stream yesterday when you tried to record a clip for the changelog, there you can maybe see what happen if you still have that recording.

**Comment by peppy** [comment]
Revisiting this one to try and get it off the open issue list. To summarise:

- a user is spamming the toggle ready button
- while they are spamming the match started, and they are put in a `WaitingLoad` state and their client starts loading, expecting to be able to play
- the server receives one of their ready button spam which puts them back in `Idle`, which from the server's perspective is them "cancelling" load.

As I mentioned in my comment above, there's no way to discern a load abort from a toggle ready operation. Thoughts on adding a new method to the hub (ie `hub.CancelLoad()` being the only way to exit the `WaitingLoad` state) or an intermediary state to the `MultiplayerUserState` enum (ie `CancelLoad`, which would be handled by the server and return the user to `Idle` when received and acknowledged).

@smoogipoo @bdach thoughts on how this one should be handled?

**Comment by bdach** [comment]
Adding something like you proposed (either a new state or a new operation) seems inevitable, I can't see much of an alternative. I think I'd *slightly* prefer a new operation but no strong feelings.

I would however probably make it an `AbortGameplay` thing rather than a `CancelLoad` thing. The latter feels too specific imo, as there's seemingly no need to discern that the exit happened during load specifically, just that it's happening after the game was started by the host...?

**Comment by peppy** [comment]
Sounds good.

Remaining question is whether to use the existing `ChangeState` flow or create a new one. I'm not sure which feels better.

**Comment by smoogipoo** [comment]
So would the server drop the incoming message then? Supposing the user's already in a `WaitingForLoad` state, would an incoming `set to idle` message from the client then just be dropped, expecting the client to only go through via the `AbortGameplay()` path?

**Comment by peppy** [comment]
Yep, that'd be the assumption.
