### ISSUE TITLE
Exception thrown of not finding a MIDI device (Arch-based) Linux with ALSA

### ISSUE THREAD

**Issue by Tudi20** [ppy/osu#14185]
**Describe the bug:** 
Exception thrown of not finding a MIDI device on (Arch-based) Linux with ALSA.
Also, I do have sound.
> "Couldn't list input devices. Is libasound2-dev installed?"

**osu!lazer version:** 
2021.809.0.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6955233/database.log)
[network.log](https://github.com/ppy/osu/files/6955234/network.log)
[performance.log](https://github.com/ppy/osu/files/6955235/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6955236/runtime.log)

**Comment by peppy** [comment]
You can ignore it.
