### ISSUE TITLE
Not able to create multiplayer room in a different ruleset if already joined a room on the current one

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#14189]
After joining a room (for example in the osu! ruleset), you can't create rooms in other rulesets anymore. Joining should still work (I believe).

Example:

https://user-images.githubusercontent.com/81645139/128756017-c5427af8-2ccb-4018-9cc3-630cba8a78c1.mp4

And yes, before I joined the room shown in the Video I was able to create a room in other rulesets.

**Comment by frenzibyte** [comment]
Logs please

**Comment by minasminas** [comment]
Not sure which one of these logs is correct, so I just post all of them.

Logs:
[database.log](https://github.com/ppy/osu/files/6956698/database.log)
[network.log](https://github.com/ppy/osu/files/6956699/network.log)
[performance.log](https://github.com/ppy/osu/files/6956700/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6956701/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6956702/updater.log)
