### ISSUE TITLE
Add support for animated note images

### ISSUE THREAD

**Issue by arceuss** [ppy/osu#14198]
the skin in question is https://osu.ppy.sh/community/forums/topics/1368278

**Describe the bug:** im playing any 4k song with this specific skin and all of the notes are invisible

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/28229451/128817314-864fd4b7-4f1c-4abe-bb3d-61b94c571338.png)

**osu!lazer version:** 2021.809.0

**Logs:** 
[logs.zip](https://github.com/ppy/osu/files/6959370/logs.zip)

**Comment by bdach** [comment]
The skin is using animations for notes, which is not currently supported.
