### ISSUE TITLE
The mod icon jumps along the lines when opening the mod menu

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu#14196]
**Screenshots or videos showing encountered issue:** 
https://drive.google.com/uc?id=1YeMnFtD1bGjCHYlf86OB7I92Ze-rCAMS

**osu!lazer version:** 
2021.809.0-lazer

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/6959289/logs.zip)

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/9155
