### ISSUE TITLE
Screen breadcrumb show "New room" even while inside rooms

### ISSUE THREAD

**Issue by Flutterish** [ppy/osu#14192]
**Describe the bug:** The lobby name does not update everywhere after changing it.
Lobby name was updated from `Flutterish's awesome room` to `This is the new lobby name` but it did not change in the `Longue` path. In fact it is `New room` instead of the first given name. The lobby name in the `Longue` path is always what it was originally when joining the lobby.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/40297338/128798737-4bcd3da6-658b-4d7a-a60a-27e4f5034a84.png)

**osu!lazer version:** 2021.809.0-lazer

**Logs:** Not needed, this is easily reproducible.

**Comment by smoogipoo** [comment]
This one's known. That breadcrumb is going away in the redesign so I'm deprioritising.

**Comment by peppy** [comment]
Might as well close given that? This will likely get forgotten about anyways.
