### ISSUE TITLE
Update beatmapset panels in beatmap listing to match web

### ISSUE THREAD

**Issue by Tudi20** [ppy/osu#14216]
**Describe the bug:**
Beatmapset panels haven't been updated to match the web yet.

**Screenshots or videos showing encountered issue:** 
Old panels in-game:
![osu_2021-08-10_22-45-11](https://user-images.githubusercontent.com/13798839/128932738-317c4014-37ab-4aca-9bb5-f44c4d414c52.jpg)
New panels on the web:
![Screenshot_20210810_224604](https://user-images.githubusercontent.com/13798839/128932777-0b538956-b0c0-46c9-aeed-e12c423764ec.png)

**osu!lazer version:** 
2021.809.0-lazer

**Comment by frenzibyte** [comment]
Figma designs for reference:
 - Beatmap card design: https://www.figma.com/file/oYJ9WkzXGvbPWBz6NxeyGr/UI%2FBeatmap-Card?node-id=0%3A1
 - Beatmap listing page: https://www.figma.com/file/bONtBvDRWNfOuiYpueD2ms/Web-Search-Result-with-Beatmap-Listing?node-id=1%3A160 with all different view modes placed next to each other.

**Comment by bdach** [comment]
Assigning to myself as I have made significant headway in this regard.

![2021-10-17-213319_1144x417_scrot](https://user-images.githubusercontent.com/20418176/137642274-f45e707b-bc4b-48d2-87f5-cbc2dac748a9.png)

Still need to clean up some shortcuts, finish some loose threads and split into digestible chunks, but there you go.

**Comment by bdach** [comment]
Old cards and listing heavily use `BeatmapOnlineInfo`. There are also fields there that aren't in client yet but the cards are using them and which I'd be looking to add, such as hype/ranked status. So my thinking is that it may be better to get that into at least a semi-stable state first.

**Comment by peppy** [comment]
I think I should be done work on the online portions today (or yesterday), so take that for whatever it's worth.

**Comment by EVAST9919** [comment]
Resolved by https://github.com/ppy/osu/pull/15807

**Comment by bdach** [comment]
It is not. There is still work to be done here for parity with web.

**Comment by andreymal** [comment]
Old panels looked better and were more useful :(

**Comment by bdach** [comment]
@andreymal care to elaborate on this rather than give vague complaints? looked better how, were more useful how?

**Comment by andreymal** [comment]
@bastoo0
1) I have to hover the mouse cursor to view favs/plays, and this additional action doesn't make sense because the panel has a free space that can display this info without hovering
2) I can't view starrate without clicking (but hovering works in web, ok)
3) The download button is smaller (~32x32 in lazer, 20x21 in web) while it has a lot of free space to be bigger
4) As seen in screenshots attached to this issue, the title "Harumachi Clover" is cropped (and it's even more cropped in latest lazer), which may indicate that the new layout is not as good than old

**Comment by bdach** [comment]
i hope the following screenshots of ongoing work ease most of your concerns. aside from number 3, maybe.

![osu_2021-11-29_01-03-17](https://user-images.githubusercontent.com/20418176/143792029-dae68d59-0211-4996-b472-2ef9f9ec0e74.jpg)
![osu_2021-11-29_01-11-22](https://user-images.githubusercontent.com/20418176/143792031-e4008b8d-8432-444e-a4c4-170fa8449bb2.jpg)

these pieces being missing is also why this issue isn't closed yet.

**Comment by peppy** [comment]
Are we done here?

**Comment by bdach** [comment]
The extra size isn't used in the overlay yet. I have pending changes for this.

**Comment by bdach** [comment]
Tentatively going to close this one given the latest merged changes which more or less bring the cards to parity with web.
