### ISSUE TITLE
Editor has no way to set preview points

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#14213]
There should be a way to set preview points in the editor to reach feature parity with stable.
This is what it looks like in stable:

![](https://pennek.s-ul.eu/JwbaHfQX.png)

**osu!lazer version:** 2021.809.0-lazer

**Comment by jai-x** [comment]
Also related to this:
- https://github.com/ppy/osu/issues/12091
- https://github.com/ppy/osu/issues/4717
