### ISSUE TITLE
osu!lazer stops working automatically after opening it

### ISSUE THREAD

**Issue by Joshynhu** [ppy/osu#14230]
**Describe the bug:** 
osu!lazer shows "osu! has stopped working" after opening it

**Screenshots or videos showing encountered issue:** 
![Capturar](https://user-images.githubusercontent.com/88790353/129066569-03099e55-64eb-4a7f-92fb-8f01efa061d4.PNG)
my windows it's in portuguese, but it basically says "osu! has stopped working"

**osu!lazer version:** 
2021.809.0

**system specifications**
windows 7 sp1 64 bits
2 GB ram
Pentium dual core 3 GHz 2.99 GHz

**Comment by bdach** [comment]
We cannot support Windows 7 for now. See #13769 for details.

Support may return at a later date.
