### ISSUE TITLE
Convert sliders to streams in the editor

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#14246]
### Discussed in https://github.com/ppy/osu/discussions/14245

<div type='discussions-op-text'>

<sup>Originally posted by **localcake** August 12, 2021</sup>
In stable the hotkey was Ctrl+Shift+F but now that does nothing.</div>

**Comment by peppy** [comment]
For backward compatibility this might be nice, but I also think we would benefit from a “stream” placement mode (maybe its own tool?) that is more accessible.

**Comment by minetoblend** [comment]
One way that would combine converting sliders into streams, as well as having a a dedicated tool for streams would be to have streams be a type of hit object.
It would essentially work like a slider, but instead of a slider body a bunch of circles get placed on its path and their position gets updated when the control points are moved. This would also allow for easily making adjustments to the shape after a stream has been created. Sliders could simply be converted to a stream object and vice versa.

**Comment by Lyti4n** [comment]
Adding a way to make accelerating streams would be nice as well.

**Comment by Auriga05** [comment]
Doing this kinda works but I don't know how to do it properly. Undo doesn't work correctly too because I didn't edit EditorBeatmap to do all the changes in one go.
```
private void convertSliderToStream()
{
    int objects = (int) Math.Round(HitObject.Duration / editorBeatmap.GetBeatLengthAtTime(HitObject.StartTime));
    for (int i = 0; i <= objects; i++)
    {
        HitCircle streamHitCircle = new HitCircle
        {
            Position = HitObject.Position + HitObject.Path.PositionAt((float) i / objects),
            StartTime = HitObject.StartTime + editorBeatmap.GetBeatLengthAtTime(HitObject.StartTime) * i
        };
        streamHitCircle.Samples.Add(new HitSampleInfo(HitSampleInfo.HIT_NORMAL));
        editorBeatmap.Add(streamHitCircle);
    }
    editorBeatmap.Remove(HitObject);
}

public override MenuItem[] ContextMenuItems => new MenuItem[]
{
    new OsuMenuItem("Add control point", MenuItemType.Standard, () => addControlPoint(rightClickPosition)),
    new OsuMenuItem("Convert slider to stream", MenuItemType.Standard, convertSliderToStream),
};
```

**Comment by bdach** [comment]
@Auriga05 that looks like a decent start, but the tool should probably also support different beat divisors like stable did (but maybe without a dialog, just use the current divisor setting from the upper right). As for undo, you want to call `EditorBeatmap.{Begin,End}Change` for the stream conversion to register as one entire operation that is undone/redone atomically.

**Comment by bdach** [comment]
This has been added now. Tentatively closing - the stream-as-hitobject idea can be implemented at a later time.
