### ISSUE TITLE
osu! tries to set invalid xdg-surface geometry on Wayland

### ISSUE THREAD

**Issue by 2secslater** [ppy/osu#14259]
**Describe the bug:** 
When trying to launch the game under Wayland (currently only tested on Sway), it tries to "set invalid xdg-surface geometry" (see [output with WAYLAND_DEBUG](https://github.com/ppy/osu/files/6977800/output.log)), preventing the game from properly starting. Setting the SDL videodriver to x11 works.

This issue has been happening since 2021.808.0 in my testing - the last version to work Wayland-native is 2021.731.0.

I am running:
Sway 1.6.1 / wlroots 0.14.0
libsdl2 2.0.16
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/30773181/129252244-b9154992-0eed-479a-a77d-aeebf29678ea.mp4

**osu!lazer version:** 
2021.809.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6977772/database.log)
[network.log](https://github.com/ppy/osu/files/6977773/network.log)
[performance.log](https://github.com/ppy/osu/files/6977774/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6977775/runtime.log)

**Comment by bdach** [comment]
This will be 99% an issue with SDL, so we cannot do anything about it here. It needs reporting upstream.

In general we cannot afford to support wayland yet. There have been several issues with it before and we do not have the bandwidth required to make it work properly. External pull requests to fix are welcome, but it's not a priority, so I'll go ahead and close this.

**Comment by bdach** [comment]
In fact it is extremely likely that this has already been fixed upstream in https://github.com/libsdl-org/SDL/pull/4629 ([see paper trail](https://github.com/libsdl-org/SDL/pull/4575#issuecomment-896600664)).

So this will be resolved the next time SDL binaries are bumped.
