### ISSUE TITLE
Unable to search some beatmap names that include special characters

### ISSUE THREAD

**Issue by 1uws** [ppy/osu#14254]
**Describe the bug:** 
Unable to search beatmap named "me!me!me!".
Map: [https://osu.ppy.sh/beatmapsets/236697](https://osu.ppy.sh/beatmapsets/236697)

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/37792683/129182204-284bc7c0-45a8-4a2e-b021-2ccb937f287e.mp4

**osu!lazer version:** 
2021.809.0-lazer
**Logs:**
[update_success.log](https://github.com/ppy/osu/files/6974702/update_success.log)
[runtime.log](https://github.com/ppy/osu/files/6974704/runtime.log)
[session.log](https://github.com/ppy/osu/files/6974705/session.log)

**Comment by smoogipoo** [comment]
@frenzibyte where's that delimiter defined, for reference?

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/blob/00ca066c39a66a31ade67b8ad33be8f57d377b7b/osu.Game/Screens/Select/FilterCriteria.cs#L53-L66

which are then consumed by `CarouselBeatmap` in:
https://github.com/ppy/osu/blob/00ca066c39a66a31ade67b8ad33be8f57d377b7b/osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs#L60-L63

**Comment by peppy** [comment]
I think we can remove both the comma and exclamation from this list without much issue? Feels weird having either of them in the first place (and blaming back, there doesn't look to be any reasoning for it being this way).
