### ISSUE TITLE
`OsuPopoverContainer` doesn't get the correct local `OverlayColourProvider`

### ISSUE THREAD

**Issue by peppy** [ppy/osu#14255]
As it is global. This is probably not good..

**Comment by bdach** [comment]
I'd probably take this a step further and say that the popover should receive all dependencies from its target...?

As to how that would be done, it'd have to be either via a manual `InjectDependencies` call, or by async loading under the target drawable itself?

**Comment by peppy** [comment]
Did we figure whether we could potentially move it back to a more local context with all the fixes that have been applied?

**Comment by bdach** [comment]
I don't think so, since the current structure still allows to do things that would be impossible normally and I'd call expected behaviour of the component, such as being able to display "in front of" scroll containers rather than "inside" (see usage in editor colour picker).

**Comment by peppy** [comment]
And being directly outside the scroll container would cause positional tracking to fail?

**Comment by bdach** [comment]
Oh, you meant moving the container itself locally. I understood it as getting rid of it entirely and displaying popovers locally next to their targets in the hierarchy.

In theory I believe that should work just fine.
