### ISSUE TITLE
Clock-related microstutters when judgements occur

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#14262]
**Describe the bug:** 

By pure chance, I've discovered what looks like clock-related microstutters occurring alongside judgements.

In the analysis video below, notice how time jumps forward after the green slider, then doesn't progress for 4 frames, and the same occurs for the blue 1. The rest of hitobjects are fine.  
The cursor continues moving throughout all of this, so it's not draw/GC-related microstutters.

This could be a `FrameStabilityContainer` issue.

**Screenshots or videos showing encountered issue:**

Full video: https://drive.google.com/file/d/1QhKg7EtsRpGPdUAkcOsercMgZZYJ1xAj
Analysis video: https://drive.google.com/file/d/19e-I2_P-ZEub61qLAq28mL6qci_e5M8x

Captured at 120FPS with user (not replay) gameplay.

Map used: https://osu.ppy.sh/beatmapsets/1034179#osu/2257469

**osu!lazer version:** 00ca066c39a66a31ade67b8ad33be8f57d377b7b

**Logs:** Irrelevant. It's going to be a deeper issue than what's shown in logs.

**Comment by peppy** [comment]
This looks like frame stability doing what it is meant to, but the source click not having a correct / updated time value. You can confirm this by adding logging to the cannot-interpolate case.

**Comment by smoogipoo** [comment]
It's definitely doing a lot more catchup:

Pre-bassmix: [runtime-old.log](https://github.com/ppy/osu/files/6979490/runtime-old.log)
Post-bassmix: [runtime-new.log](https://github.com/ppy/osu/files/6979491/runtime-new.log)

Note that when pre-bassmix did catchups, it's always on a GC spike.

Will keep investigating...
