### ISSUE TITLE
Add skip intro in multiplayer

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14260]
**Describe the bug:**
Can't skip in multi.
Like in stable, make players be able to ask for skipping, and if all agree, do it.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/53081750/129283820-bd0828e8-6670-49ae-902f-133a26e811ba.png)

**osu!lazer version:** 2021.809.0-lazer

**Comment by JonLit** [comment]
another idea would be to make it a room setting to choose if all players have to ask for skipping or if the majoritiy is enough for the intro to be skipped
