### ISSUE TITLE
Don't show "playback" and "Visual settings" while spectating

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14261]
**Describe the bug:** Don't show these options since they're not actionable and only take up space making things less clear.
Maybe put only one section for the user where one of the arrows is pointing

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/53081750/129284950-52ac2b36-b777-4380-8718-3c52c214be9d.png)

**osu!lazer version:** 

**Logs:**

**Comment by peppy** [comment]
The spectator interface is still very raw, but if this can be done with minimal effort then it's probably a good quick improvement.
