### ISSUE TITLE
Low fps on the new lounge design screen

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#14276]
**Describe the bug:** 
currently i get around 40-50 fps (sometimes even less) on the new lounge design screen which feels a bit weird since i get around 150 fps on the beatmap selection screen. i know that performance is a constant WIP but it feels weird having so low fps on a simple screen like that while the beatmap selection screen works just fine.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/43358824/129385445-4734f9c6-3cb0-4f0a-9c5d-2871c344badd.png)

**osu!lazer version:** 
7725336008939d115c27060ae652e46171d0a59e

**Logs:**
[database.log](https://github.com/ppy/osu/files/6983707/database.log)
[network.log](https://github.com/ppy/osu/files/6983708/network.log)
[performance.log](https://github.com/ppy/osu/files/6983710/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6983711/runtime.log)

OS: windows 10
CPU: i5-4440
iGPU: intel hd graphics 4600
RAM: 8 gb

**Comment by peppy** [comment]
Thanks for the report. Can you confirm whether it is also low with no rooms available? (try viewing in non-osu! ruleset).

**Comment by mouzedrift** [comment]
i've checked it with no rooms available and i got a little fps boost up to 70 fps

**Comment by peppy** [comment]
Going to look into this. I think it must be related to the background layer.

**Comment by mouzedrift** [comment]
i've tested the linked PR and i'm now getting solid 180 fps 👍
