### ISSUE TITLE
Linux | Xorg: Main monitor gets disabled when lazer enters full screen

### ISSUE THREAD

**Issue by Fynises** [ppy/osu#14279]
**Describe the bug:** 
When the game enters full screen mode in any context. my primary monitor gets disabled. which is fixable by manually re-enabling the monitor with nvidia-settings.

This includes re-entering fullscreen mode after re-enabling the disabled monitor.

Trying to recreate this issue is very awkward. so it could also be that any monitor that isn't offset at 0,0 gets disabled.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2021.809.0
**Logs:**

**Comment by Fynises** [comment]
I forgot to include some extra details:

- I'm running a dual monitor setup
- the DE I'm using is KDE Plasma

**Comment by bdach** [comment]
This will be 99% an issue with SDL and not something we can fix here in any capacity.

If your screens have different/incompatible resolutions then this may be another manifestation of https://github.com/libsdl-org/SDL/issues/4561 which was hotfixed on the SDL side recently, but not fully fixed yet. It may be that you will need the proper upstream fix to have this issue resolved.

Either way I'll close this issue as not something that we can deal with in this repository.
