### ISSUE TITLE
Small lag spikes during gameplay.

### ISSUE THREAD

**Issue by Mysidian** [ppy/osu#14288]
That's it, small lag spikes during short and long gaming session, idk why but I tried everything and doesn't work, no third-party apps, 0 apps open, etc...

https://user-images.githubusercontent.com/82321696/129450116-2994d6df-8298-42da-8d1f-9bfc5b778f55.mp4

 can you take a look pls? thx!

**Comment by frenzibyte** [comment]
Can you please record a video with the performance overlay opened in extended mode (Ctrl+F11 twice).

**Comment by bdach** [comment]
The video attached is from stable. This repository is for lazer.

Please read https://osu.ppy.sh/wiki/en/Performance_Troubleshooting.

**Comment by Mysidian** [comment]
I will post it on osu stable issues sorry
