### ISSUE TITLE
Hit circle overlay animations are not supported

### ISSUE THREAD

**Issue by Tyfaspo** [ppy/osu#14285]
Using particular skin makes circles invisible.

Link to the video showing issue:
https://lowkey.gg/v/ba83b29e-2257-402f-a3cb-64545f4e0bee

Lazer version 2021.809.0-lazer

Here's a link to the skin:
https://drive.google.com/file/d/1IWXiSo1nnG-tiliLJTwwScZrQvY8EwE0/view

**Comment by bdach** [comment]
The skin is implicitly using animated `hitcircleoverlay`, which is not supported yet (but should be).

(Worse yet, the "animation" has only one frame - `hitcircleoverlay-0` - and also has a transparent *non*-animated `hitcircleoverlay`.)

For now a workaround would be to rename `hitcircleoverlay-0` to `hitcircleoverlay`.
