### ISSUE TITLE
Game detects physical keys, not actual keys

### ISSUE THREAD

**Issue by ammongit** [ppy/osu#143]
I have swapped my caps lock and escape keys use `xmodmap`. However when osu! is open, I must press my physical escape key (labelled "esc") rather than my actual escape key (labelled "caps lock") in order to invoke the functions of the escape key. This appears to happen with other bindings as well.

System details:
```
OS: Arch Linux 64-bit
uname: Linux 4.8.6-1-ARCH #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016 x86_64 GNU/Linux
Xorg: 1.18.4
Mono: 4.6.1.3
Graphics driver: NVIDIA v375.10
OpenGL: NVIDIA libgl v375.10
```

**Comment by RemieRichards** [comment]
See: https://github.com/ppy/osu-framework/issues/252

**Comment by ammongit** [comment]
Closing as duplicate.
