### ISSUE TITLE
Not submitted maps are marked as pending on beatmap info card

### ISSUE THREAD

**Issue by AlexHgC** [ppy/osu#14309]
**Describe the bug:** 

Not submitted maps are marked as pending on beatmap info card, that is not useful for choosing maps on multiplayer

**Screenshots or videos showing encountered issue:** 

![Inkedosu_2021-08-15_14-16-13_LI](https://user-images.githubusercontent.com/31996023/129478312-c5c1ee28-0976-4242-a7e2-6d589133e3f4.jpg)

**Comment by bdach** [comment]
I can't reproduce this. I've tried exporting a map I created and re-importing it back again, and it has the "none" status correctly.

Can you perhaps link the beatmap in question?

**Comment by AlexHgC** [comment]
These maps were imported via osu! Stable, when I export them from stable and put them manually in lazer, the maps do not have any labels, so i can't reprduce it too, i've tried to create a map on osu!stable and use the import from osu stable option on lazer, but the map is not marked as pending. Here is the map folder if you want to look : 
[Camellia - Shun no Shifudo o Ikashita Kare Fumi Paeria.zip](https://github.com/ppy/osu/files/6988155/Camellia.-.Shun.no.Shifudo.o.Ikashita.Kare.Fumi.Paeria.zip)

**Comment by bdach** [comment]
This may be a vestige of some old bug which has since been fixed, then. Without a reliable reproduction scenario we can't really do much here, so I'm going to tentatively close this. If you manage to find a case where this happens reliably then please comment and we'll reopen.
