### ISSUE TITLE
The supporter promo section on the changelog page doesn't have glow around the heart image

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#14303]
**Screenshots or videos showing encountered issue:** 
| web | lazer |
| ----- | ----- |
| ![image](https://user-images.githubusercontent.com/43358824/129458069-04611c17-5721-4f62-ab0a-293759221e8b.png) | ![image](https://user-images.githubusercontent.com/43358824/129458063-12a000a4-e0a1-4fc1-9f45-f1cd70774f21.png) |

![image](https://user-images.githubusercontent.com/43358824/129458164-a20864dd-cf83-43dc-8005-73d42a77fcdf.png)

**osu!lazer version:** 
2021.815.0

**Comment by camellirite** [comment]
would this be a good first issue?
