### ISSUE TITLE
Remove left player instances from the multi-spectator view

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14322]
**Describe the bug:** Remove the box of the players that quit the match

**Screenshots or videos showing encountered issue:** 
![lazerspectator](https://user-images.githubusercontent.com/53081750/129493311-4e392ad1-a460-4f07-8e9a-95ee518905dc.png)

**Comment by peppy** [comment]
Weird, I actually had one screen disappear and thought it was due to a player leaving... but must have been some other issue.

**Comment by smoogipoo** [comment]
It'll disappear if the player leaves and starts playing again.

**Comment by frenzibyte** [comment]
While I was looking at implementing this, I got concerned about how the grid should behave when a player exits, should it get removed, or should it fade out?

Here are videoes showing the two different effects applied, for reference:

https://user-images.githubusercontent.com/22781491/130745799-fc05d3f2-c58c-440e-8fd6-19fc36153041.mp4

https://user-images.githubusercontent.com/22781491/130745437-f35a4b3e-1ade-46a3-91b9-adcc97bdaae9.mp4

Graying out might be good to still preserve the left player's areas (not as if they haven't even joined), but removing completely would be good if there were more than 16 players playing at once, not sure.

**Comment by peppy** [comment]
It should remain in place. Colour to gray sounds good, don't use alpha please.
