### ISSUE TITLE
Break time needs to be added when editing a beatmap

### ISSUE THREAD

**Issue by peppy** [ppy/osu#14330]
A good start would be to automate this in a similar way to stable (without allowing user modification) to cover the 99% case.

If anyone is interested and needs the automation rules, please ask and I will pull it out.

**Comment by bdach** [comment]
I'd looked at this a tiny bit today. The very basic rules for autogeneration seem to be relatively simple:

1. A break will be automatically inserted if a gap between two objects exceeds 5000ms
2. Breaks begin 200ms after the last object before the break
3. Breaks end at the time of the first object after the break, minus the pre-empt time for this object (for osu!, that's 1200ms at default AR=5)

The slight problem here is point (3). As things stand in lazer code, "pre-empt time" is only defined for osu! and catch; mania and taiko don't currently have it defined (let alone custom rulesets). Unsure how to proceed.

**Comment by peppy** [comment]
For mania and taiko it sounds like preempt should come from the time when the object first appears on screen. The edge case is mania i guess, since the user can change the scroll speed (maybe the time with default scroll speed?).

Maybe best to not overthink this one and use a constant value to start with, unsure.

**Comment by Zyumane** [comment]
I am interested in how to take this issue, but it seems that we do not have any leads to where to start the changes, let alone to I am unaware of the format of the code and to who manages it.

I am willing to tackle this issue in particular and gain experience throughout the process. Can you assist me with how is the process?

**Comment by bdach** [comment]
@Zyumane please make sure you are familiar with [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#i-would-like-to-submit-a-pull-request) first and foremost.

I will however note that I am not sure that this is a good first issue to start with for you - while the break generation algorithm has been mostly outlined in the comments above, it uses a fair amount of jargon, and there's still a decent number of things to figure out structurally with regard to how this should fit into the rest of editor and I fear all that may become overwhelming to juggle for a first time contribution. I'd recommend starting with something much simpler to learn the basics of framework and our general development procedure.

**Comment by Zyumane** [comment]
Understandable, thou although I am not that beginner at coding in C# but thank you for pointing out where to start experiencing the contribution, and the jargon is not an issue for me with time and reading with ease, I can follow the thread of the structure of the program.

Thanks once more.
