### ISSUE TITLE
Multiplayer Infinitely Loads

### ISSUE THREAD

**Issue by zachmanthethird** [ppy/osu#14335]
The title is pretty self-explanatory; nothing loads no matter how long I wait upon entering the multiplayer screen. This problem used to occur on the playlists screen until the newest update (2021.815.0)
While the game doesn't throw any errors, I was able to find some and isolated them in this [network.log](https://github.com/ppy/osu-web/files/6989338/network.log). Not an urgent issue (and tbh I'm probably just missing something obvious); I'm mainly putting this here for anyone else that might have the same problem.
PS This is my first time submitting an issue, so apologies if I did anything wrong.

**Comment by peppy** [comment]
You are getting a 404 error. Please try loading https://spectator.ppy.sh in your browser. It will likely give you a solution.
