### ISSUE TITLE
Colour picker gradients are rendered as a solid colour on android

### ISSUE THREAD

**Issue by minetoblend** [ppy/osu#14383]
**Describe the bug:** 
The saturation/value square of the colour picker in the editor setup page is displayed as completely white on my phone, and the hue picker shows up as completely red.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/20pj51

**osu!lazer version:** 
2021.815.0

**device / android version**
Xiaomi Redmi Note 8 Pro / 10 QP1A.190711.020

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/7008499/logs.zip)

**Comment by bdach** [comment]
Am seeing the same. The shader must not be ES-compliant in some weird way. It didn't even occur to me to check...

**Comment by ibrab000** [comment]
Has this issue been fixed yet? Because it is the same on my device.

**Comment by peppy** [comment]
I think you answered your own question.
