### ISSUE TITLE
System.DllNotFoundException: e_sqlite3 on linux

### ISSUE THREAD

**Issue by DerpyCrabs** [ppy/osu#1438]
Osu doesn't run after compilation on arch linux, but if i manually copy "packages/SQLitePCLRaw.lib.e_sqlite3.linux.1.1.8/runtimes/linux-x64/native/libe_sqlite3.so" to "/usr/lib/osu-lazer/" it fixes the problem. 
I don't know how to fix this, can someone fix this for me so i don't need to manually copy this library?

**Comment by peppy** [comment]
Are you building post this merge? https://github.com/ppy/osu/pull/1403

**Comment by DerpyCrabs** [comment]
I've tried on latest commit (post #1403 merge) - problem still exist.

**Comment by Nabile-Rahmani** [comment]
Works for me. Are you compiling from a dev environment or using some sort of package manager ?
Files should be copied to `osu.Desktop/bin/Debug|Release`, not `/usr/lib`.
