### ISSUE TITLE
Login process does not abort correctly in some cases

### ISSUE THREAD

**Issue by bdach** [ppy/osu#14386]
### Discussed in https://github.com/ppy/osu/discussions/14382

<div type='discussions-op-text'>

<sup>Originally posted by **Gabixel** August 18, 2021</sup>
Not sure how it happened, but I got this 525 `WebException` (I guess that's the HTTP status code?).
Everything looked ok (e.g. the carousel leaderboard was asking me to log in), except for the user panel, which showed me as a registered user:

![osu_2021-08-18_17-18-48](https://user-images.githubusercontent.com/43073074/129926595-836f0786-33d5-4b11-a966-8b44084cf3e3.png)

I didn't check if there were any other problems. I "logged out" and re-logged in, and everything was back to normal.

Logs:
- [`network.log`](https://github.com/ppy/osu/files/7008377/network.log)
- The [`runtime.log`](https://github.com/ppy/osu/files/7008398/runtime.log) looks clean

Version: `2021.815.0`</div>

---

525 is a non-standard HTTP error code, I'm pretty sure (seems to be cloudflare-specific), but the timeout is the root cause, I believe. The user request failure handling looks flaky in such a case:

https://github.com/ppy/osu/blob/d76ad0e5e0b896bf0062c07c471b2be4e6c8f178/osu.Game/Online/API/APIAccess.cs#L153-L159

but 17168b8 says it wasn't supposed to be robust in the first place.

**Comment by peppy** [comment]
The issue here is that it shouldn't be actually producing a valid login. The previous code (before the PR/commit you mention) would just have the loading spinner continue and a further retry scheduled. Very weird, will take a look today.
