### ISSUE TITLE
Settings' recommendations don't appear on not recommended options until you update them

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#14396]
**Describe the bug:** As title. Not sure if this was intended.

**Screenshots or videos showing encountered issue:** 

- After startup:
![image 1](https://user-images.githubusercontent.com/43073074/130104889-9c921f6a-f8ae-45aa-a8a1-5e8ff6fb7b2e.png)
![image 2](https://user-images.githubusercontent.com/43073074/130105490-2b11c4b4-5241-4473-9ff0-0f2d5d00e03e.png)

- After changing these options:
![image 3](https://user-images.githubusercontent.com/43073074/130104955-cebd332b-b4ea-43ef-b666-203c04b08445.png)
![image 4](https://user-images.githubusercontent.com/43073074/130105520-b93595e4-586b-4722-9b33-5a75e6c21515.png)

**osu!lazer version:** 2021.815.0

**Comment by bdach** [comment]
Regressed at https://github.com/ppy/osu/commit/af9f910a127da8d7763279f1d4494ce2e83f5e4d. `hasValue` is backwards (it should be negated), and the alpha set later on "covers up" that fact in all cases but when this logic fires the first time on startup.
