### ISSUE TITLE
View Profile broken for beatmap creators

### ISSUE THREAD

**Issue by Igbooo** [ppy/osu#14411]
**Describe the bug:** 
The "View Profile" button is returning no profile in some places, specifically the beatmap select screen and the multiplayer screen. If a profile has been viewed beforehand, it will display that one (e.g. if I look at my profile and then a beatmap creators it will show mine.) It works in the Beatmap Listing screen, the ranking screen and the personal profile in the top right. 

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/49489897/130268711-3315016a-9ac3-46e8-b5e0-dc81e163afe3.mp4
https://www.youtube.com/watch?v=pJhlA4JXD6M (i think the above video doesn't play, so its on youtube here)

**osu!lazer version:** 
osu 2021.820.0-lazer

**Logs:**
[database.log](https://github.com/ppy/osu/files/7023069/database.log)
[network.log](https://github.com/ppy/osu/files/7023070/network.log)
[performance.log](https://github.com/ppy/osu/files/7023071/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7023072/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7023073/updater.log)

**Comment by bdach** [comment]
Was reported before in #9730 but that was apparently fixed already. Did you import the map fresh, or did it live there on disk for a longer period of time? Does deleting the map, then restarting the game and reimporting the map again help?

**Comment by Igbooo** [comment]
The map has been there for a while. Redownloading (via beatmap  listing) and then opening it does make it work but for other maps that are already there the profile doesn't load. It does then work for that specific map across restarts though.

**Comment by bdach** [comment]
The solution is to reimport for now, then - the required database fields must be populated for the field to work correctly, which they won't be in case of imports from before the aforementioned change.
