### ISSUE TITLE
Incorrect display of the starrate when setting the circle size to 0

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#14415]
CS 0.1
![image](https://user-images.githubusercontent.com/59089206/130280652-27f7c84f-18fb-4e53-9b8a-14ffddcaddc6.png)

CS 0 
![image](https://user-images.githubusercontent.com/59089206/130280670-48a9979f-4c20-4375-bc69-78e014ca65e3.png)

Normal CS (4.8)
![image](https://user-images.githubusercontent.com/59089206/130280693-3ffddfa8-d3dc-445c-8975-6d517dbee453.png)
**osu!lazer version:** 
2021.820.0

**Comment by bdach** [comment]
This was technically before #14416, but that one is a better report, so closing this one.
