### ISSUE TITLE
Osu Lazer crashes when switching to windowed 

### ISSUE THREAD

**Issue by matotomato1** [ppy/osu#14424]
Hey I'm completely new to osu lazer, downloaded it an hour ago or so. And I saw fullscreen was on so I went for borderless windowed since I tab a lot but launcher crashed. And now it crashes every time I open it. 

I tried launching as admin, uninstalling and reinstalling and adding a route exception to my antivirus, but nothing worked.

I guess I could mayba look for the options file in the game folder but haven't tried that yet.

Also hope I'm not uploading an already discussed issue (I didnt see my problem anywhere), if so, I'm sorry.

**Comment by bdach** [comment]
We cannot work with such a vague report, sorry. There are no logs or video in the opening post, no details about your platform of choice, etc.

Closing due to not enough info, will reopen again if relevant information is provided.
