### ISSUE TITLE
Messages being written in lounge arent transferred to in-game textbox

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#14423]
They are saved/displayed once we get back out of the lobby. But when interrupted in stable/tourney play it's almost always possible to finish typing before the map starts

**video:** https://youtu.be/lKyCN7iaIK8
**osu!lazer version:** 2021.820.0-lazer

**Comment by bdach** [comment]
To make sure I understand correctly: the point is that the pending message being written in the lounge screen isn't transferred to the in-game textbox?

**Comment by Pennek** [comment]
Yes

**Comment by peppy** [comment]
Messages should be stored against each channel and restored on switching in the main chat overlay too. A bindable would work well to keep all displays in sync.
