### ISSUE TITLE
Crashing + display issues switching from wondowed/fullscreen to borderless windowed

### ISSUE THREAD

**Issue by camellirite** [ppy/osu#14426]
**Describe the bug:** Swapping to borderless windowed from fullscreen or windowed causes crashes or black screens (with functioning audio)

**Screenshots or videos showing encountered issue:** https://youtu.be/kHiysgC6Vck

**osu!lazer version:** 2021.820.0

**Logs:** At each crash/closing the game I saved the logs
[1.zip](https://github.com/ppy/osu/files/7024853/1.zip)
[2.zip](https://github.com/ppy/osu/files/7024854/2.zip)
[3.zip](https://github.com/ppy/osu/files/7024855/3.zip)
[4.zip](https://github.com/ppy/osu/files/7024856/4.zip)

**Comment by bdach** [comment]
These logs look clean. On the video I see that you have geforce experience enabled; do you by any chance also have shadowplay enabled? If so please try disabling it and seeing if it helps anything.

Windows Event Viewer info may also be helpful. You can attach it by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by camellirite** [comment]
Disabling instant replay solves it!
