### ISSUE TITLE
Entering wrong password when joining private multi lobby gives error

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#14421]
**video:** https://youtu.be/BZ8h93JxH-g
**osu!lazer version:** 2021.820.0-lazer

**Comment by bdach** [comment]
The error isn't *incorrect*, per se - it's correct operating behaviour, but it could be definitely handled better / not look as scary.

**Comment by sh0ckR6** [comment]
I can attempt fixing this issue if nobody else has

**Comment by peppy** [comment]
The issue is still open which suggests that is the case. You're more than welcome to give it a try.
