### ISSUE TITLE
Gameplay cursor still appears in a faded state while touch input is received

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#14434]
Cursors are supposed to be completely hidden as per this logic in `MenuCursorContainer`:

https://github.com/ppy/osu/blob/d3dba296d672afa4d5c4d7c97154fe68117935a1/osu.Game/Graphics/Cursor/MenuCursorContainer.cs#L51-L59

But gameplay cursors take advantage of being hidden by instead fading slightly out rather than hiding completely, for the case of hovering a non-gameplay component for example.

Opening an issue as that causes touch users to always see faded gameplay cursors rather than not displaying any cursor.

`IProvideCursor`s should instead define a separate path to hide the cursor with the intention that "they shouldn't appear", rather than using `Hide()`.

### Discussed in https://github.com/ppy/osu/discussions/14427

<div type='discussions-op-text'>

<sup>Originally posted by **Ryoko-Chann** August 21, 2021</sup>
Idea: Add an option to Show Cursor during Gameplay for Android users.

It's really hard to play lazer on android with drag or a stylus when playing because i can't see the cursor on screen, practicing to click (key z, x) makes it harder too because i can't see the cursor's timing going to the hit circle. Adding an option to Show/Hide Cursor During Gameplay makes things easier for some of us android users. :)</div>

**Comment by bdach** [comment]
I would rather just hide completely than add some separate path. Is there really a reason why the gameplay cursor should show behind the UI one? That already looks sort of dicey in some scenarios (i.e. chat box which is semi-transparent, and shows two cursors, one behind the other).

**Comment by peppy** [comment]
The faded cursor was intentionally done as it looked better, but I'm open to trying hiding if someone wants to make the change *and* after doing so agrees that it feels good.

**Comment by ProudFoxx42069** [comment]
Yeah, gameplay is hard when the cursor is in low opacity. Even with muscle memory its really difficult.  Tho you guys are the developers I don't really mind. Good job bringing osu! to mobile👍.

**Comment by TUPSI-art** [comment]
I would love for the cursor to be seen like in opsu, if I capture the screen it is not seen and I do not like it
