### ISSUE TITLE
Beatmap count and star range display on multiplayer selection screen not always correctly shown

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#14439]
After joining a lobby and leaving it again, the star rating display at the multiplayer selection screen and beatmap count on the rooms aren't shown correctly anymore.

Video:

https://user-images.githubusercontent.com/81645139/130331117-178a9b37-8555-4cfd-9d37-32dc8f3a217f.mp4

**Comment by peppy** [comment]
This is quite weird. I thought it was cross-talk from you entering a room, but it actually looks like incorrect data is being displayed for *other* rooms in the lounge. Probably worth some investigation..
