### ISSUE TITLE
Requesting the beatmap fails (multiplayer)

### ISSUE THREAD

**Issue by elweojus** [ppy/osu#14440]
**Describe the bug:** 
sometimes I don't get the beatmap when the host changes it, I think its due my bad internet although I never experienced this issue before

**Screenshots or videos showing encountered issue:** 
![Capture](https://user-images.githubusercontent.com/50848502/130334468-d0a92104-3100-40a7-9291-c06112ba889f.PNG)

**osu!lazer version:** 
2021.820.0
**Logs:**
[runtime .log](https://github.com/ppy/osu/files/7026126/runtime.log)

**Comment by peppy** [comment]
can you also include your `network.log` file?

**Comment by elweojus** [comment]
[network.log](https://github.com/ppy/osu/files/7028088/network.log)
[runtime.log](https://github.com/ppy/osu/files/7028090/runtime.log)
Here an update

**Comment by smoogipoo** [comment]
Looks like your network was dying at the time. Not much more we can do here - perhaps add a loading spinner or a message that the beatmap request is failing...?

And perhaps we could stop clearing the beatmap, which may be easier to do these days following the recent refactorings.
