### ISSUE TITLE
Turning off Difficulty Adjust should reset other mods parameters

### ISSUE THREAD

**Issue by 1uws** [ppy/osu#14447]
**Describe the bug:** 
Each mod needs to be turned off then on to reset after DA mod is turned off.
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/37792683/130361738-4c71b970-b653-4b76-abee-e1ed9bbfbb97.mp4

**osu!lazer version:** 
2021.820.0-lazer
**Logs:**
[session.log](https://github.com/ppy/osu/files/7027677/session.log)
[runtime.log](https://github.com/ppy/osu/files/7027678/runtime.log)

**Comment by bdach** [comment]
I'm not sure why this would have to be the case, or why difficulty adjust is mentioned here specifically? All mods have their settings stay as they are until they are deselected, and on re-selecting the settings are reset. Can you elaborate on this?

**Comment by 1uws** [comment]
Oh sorry, but it's a bit weird as some include me sees DA as a mod to open a customizing sub-window for other mods. Then again Customisation button doesn't reset parameters but closes the sub-window. It would be convenient to have a feature to reset them but not really important. I'll close this issue.

**Comment by bdach** [comment]
There is a button available to reset each setting:

![obraz](https://user-images.githubusercontent.com/20418176/130362906-3b9cebd8-b276-4169-8306-d680cd75691d.png)

but I do realise doing this one-by-one with all of them may get tedious. Feel free to start a discussion about adding one, I'm reasonably certain this is something that could very well happen.
