### ISSUE TITLE
Missing skins when importing from stable

### ISSUE THREAD

**Issue by TheBrunoRM** [ppy/osu#14451]
**Describe the bug:** when importing skins from stable, it doesn't import all the skins, there are missing ones.

**Screenshots or videos showing encountered issue:** 

My osu! skins folder:
![image](https://user-images.githubusercontent.com/38665405/130366679-377252ae-c40b-44e1-9820-399ffcea5b8e.png)

osu!lazer skins: (no scrollbar)
![image](https://user-images.githubusercontent.com/38665405/130366703-14cd3f57-1f09-4a84-9d36-b26b7e5e1b26.png)

**osu!lazer version:** 2021.820.0

**Logs:** 
[logs.zip](https://github.com/ppy/osu/files/7027962/logs.zip)

**Comment by TheBrunoRM** [comment]
I've discovered something: the skins "White Circles" and "White Circles XD" had the same skin.ini file.
I changed the skin.ini file for one of them, and now it imported both.

**Comment by bdach** [comment]
The log contains the following:

```
2021-08-22 18:40:03 [verbose]: [405c4] Found existing but failed re-use check.
2021-08-22 18:40:03 [verbose]: [405c4] Import successfully completed!
```

Which means that indeed, the `skin.ini` files must have been completely identical, so the skins were deemed to be the same one skin. This was an optimisation applied to speed up skin import times.

I guess for now the solution is to make the skins distinct from each other by making `skin.ini` changes. This could also be communicated to the user more clearly.

**Comment by peppy** [comment]
This isn't the first time this has come up. We may want to reconsider how we're doing the duplicate detection (when migrating from stable) to also include the directory. It's kind of implied that the user expects each of the skins to be their own non-duplicate instances when performing a migration.
