### ISSUE TITLE
UR bar tick marks do not update after seeking in replay

### ISSUE THREAD

**Issue by memesnightmares** [ppy/osu#14470]
**Describe the bug:** 

When I seek while watching a reply, the UR bar ticks do not update to match the section proceeding the new location. It seems like updating the ticks fully could be an expensive operation (as it would require a lookbehind of sorts), so at least it would be nice to clear the UR bar after seeking.

**Screenshots or videos showing encountered issue:** 

Here's an example in which the issue occurs several times. First, the replay plays and then I seek back to the start, and yet the ticks on the UR bar remain. Second, I repeatedly seek to an empty area of the map, and you see that the ticks fade out with real time rather than game time.

https://user-images.githubusercontent.com/55752957/130532358-bc2d2d0e-454f-48d6-86a7-d5b3c5dad452.mp4

> I'm unsure why this isn't loading in my browser, but downloading the file with `wget` and opening it in a video player locally works, so here's the bare link: [`https://user-images.githubusercontent.com/55752957/130532358-bc2d2d0e-454f-48d6-86a7-d5b3c5dad452.mp4`](https://user-images.githubusercontent.com/55752957/130532358-bc2d2d0e-454f-48d6-86a7-d5b3c5dad452.mp4)

**osu!lazer version:** 2021.820.0

**Logs:** I don't think they're relevant but I can provide them if necessary

**Comment by peppy** [comment]
Clearing the display is probably a good quick solution.
