### ISSUE TITLE
Random black screen on Android

### ISSUE THREAD

**Issue by BalazsSzeles** [ppy/osu#14498]
**Describe the bug:** On Android I get this black screen randomly, and I don't know what causes it. It usally happens when I'm doing something like downloading a map, or browsing the web features. When I'm in this black screen, I usally hear the background music, and when I touch somewhere, I usally hear the sound of the buttons.

**Screenshots or videos showing encountered issue:** I don't have any

**osu!lazer version:** 2021.820.0 but it happened before this version too

**Logs:** 
[database.log](https://github.com/ppy/osu/files/7048818/database.log)
[network.log](https://github.com/ppy/osu/files/7048819/network.log)
[performance.log](https://github.com/ppy/osu/files/7048820/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7048821/runtime.log)

**Comment by theklensi** [comment]
dude, maybe u should try ask parents for new phone with 3-4 gb ram? black screen or squares = your phone - potato from 2014

**Comment by Elabar** [comment]
I got this black screen too bug too.
Not sure how to trigger it exactly.

But what you can try is,
Play solo -> Select beatmap -> Open beatmap listing -> download a song -> randomly clicking around

Here is a video showing how to trigger it.
https://streamable.com/pszri3
When the screen goes black, it seems like it just stops drawing, it still accepts all the input and sound is being output as well.

Running on [2022.306.0](https://github.com/ppy/osu/releases/tag/2022.306.0), but I got this on [2022.226.0](https://github.com/ppy/osu/releases/tag/2022.226.0) as well. Not sure it started from what version. LMK if you need any other info.

Logs:
[database.log](https://github.com/ppy/osu/files/8192023/database.log)
[network.log](https://github.com/ppy/osu/files/8192024/network.log)
[performance.log](https://github.com/ppy/osu/files/8192025/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8192026/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8192027/updater.log)

**Comment by bdach** [comment]
@elabar please try updating your graphics drivers and disabling any overlays first, to ensure your problem is not related to any of those things.

**Comment by Elabar** [comment]
> @Elabar please try updating your graphics drivers and disabling any overlays first, to ensure your problem is not related to any of those things.

Seems like an overlay issue. Can't replicate it after disabling overlay in Discord.

**Comment by Teages** [comment]
> @Elabar please try updating your graphics drivers and disabling any overlays first, to ensure your problem is not related to any of those things.

https://github.com/ppy/osu/discussions/17108 is not related to graphics drivers or low memory. But it is also related to Discord Game Overlay

**Comment by Joehuu** [comment]
Closing as OP never gave more information to the initial Android report and the off-topic Windows discussion is resolved.
