### ISSUE TITLE
error after opening the beatmap info overlay on a specific beatmap

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#14541]
**Describe the bug:** 
if i open the beatmap info overlay on [this beatmap](https://osu.ppy.sh/beatmapsets/580821#osu/1237234) i get an error.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43358824/131215901-329f5890-5388-43ee-81c3-4d32976cc0d6.mp4

**osu!lazer version:** 
2021.828.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/7070593/database.log)
[network.log](https://github.com/ppy/osu/files/7070594/network.log)
[performance.log](https://github.com/ppy/osu/files/7070595/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7070596/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7070597/updater.log)

**Comment by bdach** [comment]
I cannot reproduce this failure, and don't understand how a null reference could feasibly be present in the place indicated by the stack trace (which is somewhere [here](https://github.com/ppy/osu-framework/blob/758ec3418239d143c491ae92bfa7664ef6a650c1/osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs#L28-L51)).

**Comment by Theighlin** [comment]
I tried it and it actually crashed my game after showing the error
[runtime.log](https://github.com/ppy/osu/files/7071049/runtime.log)

**Comment by Game4all** [comment]
Managed to reproduce while debugging on the aforementionned maps. After a bit of digging aroundl, found out that the error was originating from there: https://github.com/ppy/osu/blob/56b5d2a6e96fe95e9dbfee4b724e0340640b10a1/osu.Game/Overlays/BeatmapSet/Scores/TopScoreStatisticsSection.cs#L119

And the reason is somewhat obvious: both mentionned maps are loved, and as such the API return null values for the PP field.

**Comment by frenzibyte** [comment]
The logs show that the nullref happened in `LocalisedBindableString.updateValue`? shouldn't it show up in `LocalisableFormattableString.GetLocalised` in that case? if the exception is somehow skipping the first method in the stack trace, then that needs to be fixed as well.
