### ISSUE TITLE
problem on importing beatmaps from stable

### ISSUE THREAD

**Issue by Iodid** [ppy/osu#1454]
An issue occurs while using the 'import beatmaps from stable' option.

The problem occurs while importing the 100th beatmap (specific beatmap: 102071 Yoomii - Ryth Of Love_1) causing database and runtime messages to rapidly appear and the RAM usage of lazer to spike drastically.

Video example of the issue: https://streamable.com/vl3xl

An example of the repetetive debug messages (can post the entire database.log if required, though it's essentially a repetition of this set of messages):

02.11.2017 17:42:52: Failed executing DbCommand (4ms) [Parameters=[@p10='?', @p11='?', @p12='?', @p13='?', @p14='?'], CommandType='Text', CommandTimeout='10']
02.11.2017 17:42:52: INSERT INTO "BeatmapSetInfo" ("DeletePending", "Hash", "MetadataID", "OnlineBeatmapSetID", "Protected")
02.11.2017 17:42:52: VALUES (@p10, @p11, @p12, @p13, @p14);
02.11.2017 17:42:52: SELECT "ID"
02.11.2017 17:42:52: FROM "BeatmapSetInfo"
02.11.2017 17:42:52: WHERE changes() = 1 AND "ID" = last_insert_rowid();
02.11.2017 17:42:52: An exception occurred in the database while saving changes for context type 'osu.Game.Database.OsuDbContext'.
02.11.2017 17:42:52: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: BeatmapSetInfo.OnlineBeatmapSetID'.
02.11.2017 17:42:52: bei Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
02.11.2017 17:42:52: bei Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
02.11.2017 17:42:52: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
02.11.2017 17:42:52: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
02.11.2017 17:42:52: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
02.11.2017 17:42:52: --- Ende der internen Ausnahmestapelüberwachung ---
02.11.2017 17:42:52: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
02.11.2017 17:42:52: bei Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
02.11.2017 17:42:52: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
02.11.2017 17:42:52: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
02.11.2017 17:42:52: bei Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

Runtime debug message (transscript from the recorded footage since I can't seem to find it in any of the logs):

ERROR: Could not import beatmap set
Microsoft.Data.SqliteException (0x80004005): SQlite Error 19: 'UNIQUE constraint failed: BeatmapSetinfo.OnlineBeatmapSetID'.
bei Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
bei Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection DbCommandMethod executeMethod, IReadOnlyDictionary'2 parameterValues)
bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary'2 parameterValues)
bei Microsoft.Entity.FrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

The runtime debug messages would occur inbetween each repetition of the afore mentioned set of database debug messages.

version 2017.1030.0

**Comment by peppy** [comment]
Yep, aware of this one. There's another which can trigger too:

`SqliteException: SQLite Error 19: 'UNIQUE constraint failed: FileInfo.Hash'.`

These are caused by the same beatmap being imported twice (or two maps with incorrect/missing metadata being imported)

**Comment by peppy** [comment]
@lodid could you please test this after first deleting your `client.db`? I believe this is an issue with migration from old databases specifically (cannot reproduce on a fresh database).

**Comment by Iodid** [comment]
After deleting the client.db in AppData/Roaming/Osu the error is still reproduceable.

**Comment by Iodid** [comment]
A peculiar thing happened:

After importing the 'faulty' beatmap (and a few before and after it) on a fresh client.db and trying to "import beatmaps from stable" again, lazer tripped on the same beatmap even though it should have skipped importing that beatmaap due to it already being in the database.

**Comment by peppy** [comment]
It'd be great if you could share the problematic .osz files!

**Comment by Iodid** [comment]
The beatmap in question would be https://osu.ppy.sh/s/102071
Importing the .osz on it's own works fine.

**Comment by MattiaPette** [comment]
I have a video about this error.
I don't know if it will be useful at all but I'll post it anyway, who knows 😆 

[Osu lazer import stable beatmaps error](https://youtu.be/mHe3qKJFDQQ)

**Comment by Iodid** [comment]
The issue happened to me again in version 2017.11.20.0

While this time the beatmap that caused it originally was imported witout problems, the exact same issue happened on a later beatmap with the same error messages as before.
