### ISSUE TITLE
problem with the game during installation

### ISSUE THREAD

**Issue by anymelovgames** [ppy/osu#14543]
Describe the error:
during installation this bug comes out

Screenshots or videos demonstrating the problem:

osu! lazer version: 2021 828.0
windows 7 64x system
![131216502-7827e64d-e2bf-4573-b321-63e676c4dc11](https://user-images.githubusercontent.com/72560856/131218051-24f6c52a-7e21-464a-8ae9-a9bfd99c7b88.png)

**Comment by bdach** [comment]
see [my comment](https://github.com/ppy/osu/issues/14542#issuecomment-907620496) on your original non-english report. windows 7 is not supported for now.
