### ISSUE TITLE
проблема с игрои при установке вылезает эта ошыбка

### ISSUE THREAD

**Issue by anymelovgames** [ppy/osu#14542]
![image](https://user-images.githubusercontent.com/72560856/131216502-7827e64d-e2bf-4573-b321-63e676c4dc11.png)

**Describe the bug:** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2021 828,0

**Logs:**

**Comment by frenzibyte** [comment]
Please re-write your report in english, along with your OS specifications (mainly whether you're running in 32-bit Windows).

**Comment by bdach** [comment]
Bitness is not even relevant right now. The support for running lazer on windows 7 (which is what the screenshot shows) has been dropped, at least temporarily.

Closing as such
