### ISSUE TITLE
Beatmap video flickering on low powered devices (decode performance)

### ISSUE THREAD

**Issue by BalazsSzeles** [ppy/osu#14544]
**Describe the bug:** Weird storyboard effect on some beatmaps. I attached videos that show the problem. I suspect the problem is that the video's and the screen's aspect ratio is not matching
_(sorry for the laggy video on Android and the low quality video on my potato PC (and also all 3 videos have been a little bit compressed))_

**Screenshots or videos showing encountered issue:** 
[Map A on PC](https://user-images.githubusercontent.com/71432767/131219368-e1063e72-5d88-44e8-abba-994565ba4952.mp4)
[Map B on PC](https://user-images.githubusercontent.com/71432767/131219377-ffe596c9-670e-4ed8-8a0e-1f24d43b88e6.mp4)
[Map A on Android](https://user-images.githubusercontent.com/71432767/131219382-565c1f36-b6c6-4f91-9df1-064e456b2321.mp4)
(Map B also have this issue on Android, but I don't have that video)

**osu!lazer version:** 
Android: 2021.820.0
PC:  2021.828.0

**Logs:** _I'll attach it if needed_

**Comment by bdach** [comment]
This may be just due to the decoding being done in software right now. https://github.com/ppy/osu-framework/issues/4079 may improve this.

**Comment by peppy** [comment]
@BalazsSzeles can you explain what you're pointing out here? Apart from the lag, both videos seem to look like the aspect ratio is the same.

**Comment by BalazsSzeles** [comment]
On mobile (Android) the aspect ratio (of the device) is a little bit wider than 16:9 (1520x720)
On PC, the aspect ratio (of the device) is 16:9 (1920x1080)
The thing that I pointing out, is that there is a little bit of flickering effect on the storyboard, and I suspected, that the non-matching aspect ratio is the problem (the device's and the storyboard's aspect ratio is not a 1:1 fit).

**Comment by turbedi** [comment]
Can this issue be closed since hardware decoding has been implemented in ppy/osu-framework#4839 ?

**Comment by bdach** [comment]
Difficult to say for sure unless the original reporter re-tests.

**Comment by peppy** [comment]
Let's close for now and wait for someone else to report an issue. The hardware decode should have fixed this in theory.
