### ISSUE TITLE
FPS Limiter getting incorrect screen refresh rate, unable to set specific frame limit.

### ISSUE THREAD

**Issue by AverytheFurry** [ppy/osu#14557]
**Describe the bug:** 
The fps limiter is getting the incorrect screen refresh rate. Also, I'm unable to set a specific frame limit.
Running on an intel celeron chromebook (running arch linux), if relevant.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/47131867/131235120-2a88784e-31ec-46ed-b733-d4255ec9a072.png)

**osu!lazer version:** 
2021.828.0-1
**Logs:**
[performance.log](https://github.com/ppy/osu/files/7071742/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7071743/runtime.log)
[database.log](https://github.com/ppy/osu/files/7071744/database.log)
[network.log](https://github.com/ppy/osu/files/7071745/network.log)

**Comment by Susko3** [comment]
Input and audio threads always run at 1000 Hz in multithreaded mode. Set to single threaded and it'll mathc the update thread. The frame limit is being set to 120 Hz, as written on the fps overlay, 2x your refresh rate.
