### ISSUE TITLE
Default lazer hit judgements look different/"wrong"

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#14555]
**Describe the bug:** The changelog doesn't seem to mention anything about this, so I guess it's unintended? (I'm using the official "triangles" skin.)

**Screenshots or videos showing encountered issue:** 

- Before latest version:
![image](https://user-images.githubusercontent.com/43073074/131228514-706996f6-a5fe-4065-90cb-d31036ebc604.png)

- After:
![image](https://user-images.githubusercontent.com/43073074/131228520-43d15d7a-77d2-44fe-a159-eb99a6a238ba.png)

**osu!lazer version:** Latest (`2021.828.0`)

**Comment by frenzibyte** [comment]
That is intended yes, it's done for performance reasons (no longer tweening text spacing, see https://github.com/ppy/osu-framework/issues/4712) and feels better than before in general anyways.
