### ISSUE TITLE
Rotating fit tablet area 180° degress appear as outside bounds

### ISSUE THREAD

**Issue by Smorty100** [ppy/osu#14570]
When rotating the tablet play area 180° it should appear in a blue color, indicating, that no part of the playarea is cut off. But in this case it appears in red, indicating that some part is cut off. This isn't a issue, once I resize the playarea smaller, then it returns to blue.

**Comment by peppy** [comment]
Has this been reproduced by anyone? This issue has no logs or video showing this happening.

**Comment by Walavouchey** [comment]
this is slightly different from what i've seen a while ago (went red in the flipped orientation), but pretty much the same issue

https://user-images.githubusercontent.com/36758269/131541383-0b6e9435-4383-49de-92af-f8e9e22b8dfe.mp4

[logs.zip](https://github.com/ppy/osu/files/7085454/logs.zip)

latest release

**Comment by Smorty100** [comment]
This is what happens:
https://youtu.be/M9Ju0Ov4brs
Ill add the runtime file to the post, if that helps
I am running debian 11 as seen in the video.
[runtime.log](https://github.com/ppy/osu/files/7085500/runtime.log)
