### ISSUE TITLE
In main menu on osu! logo some little triangle(s) moves too slow

### ISSUE THREAD

**Issue by GetterSetterAndDot** [ppy/osu#14584]
So, the problem is already described in title. I tried to restart the client but this triangle (sometimes one, sometimes two) spawns anyway at different places.
Video:

https://user-images.githubusercontent.com/47123924/131412211-9d979618-015b-474a-829c-84ab39a65693.mp4

**Comment by peppy** [comment]
This is actually "correct" by implementation, but I agree it looks a bit weird. We probably should be limiting how small the triangles that spawn should be, or limiting the minimum velocity. Likely the first?

**Comment by frenzibyte** [comment]
Any reason for closing? the corresponding PR is still not merged.

**Comment by GetterSetterAndDot** [comment]
> Any reason for closing? the corresponding PR is still not merged.

Oh, sorry, I am a newbie on GitHub. I thought if peppy wrote a fix, the issue should be closed.
