### ISSUE TITLE
Running as administrator notification shows when not running as administrator.

### ISSUE THREAD

**Issue by xDololow** [ppy/osu#14588]
**Describe the bug:** 
So basically I use Windows 10 LTSC version 1809 17763.1577 and when I start lazer it shows that it runs as admin but actually not. 

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/26763912/131479088-119c6b93-77df-4661-a03c-cf736df51c78.png)
![image](https://user-images.githubusercontent.com/26763912/131479246-ec5dd216-9731-4ea0-a13e-f83dc4894747.png)

**osu!lazer version:** 
2021.828.0-lazer (it was on previous versions as well as it was added)

**Logs:**
[performance-draw.log](https://github.com/ppy/osu/files/7082869/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/7082870/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/7082871/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7082872/updater.log)
[database.log](https://github.com/ppy/osu/files/7082873/database.log)
[debug.log](https://github.com/ppy/osu/files/7082874/debug.log)
[network.log](https://github.com/ppy/osu/files/7082875/network.log)
[performance.log](https://github.com/ppy/osu/files/7082877/performance.log)

**Comment by peppy** [comment]
Have you setup your user account in a weird way? This should only appear if you have the system administrator elevated credential (which even with "LTSC" should not be a default). If so, I'd recommend changing your account settings.

**Comment by xDololow** [comment]
Here's a list of all users in my Windows.
```
Name               FullName Disabled.
----               -------- ---------
DefaultAccount
WDAGUtilityAccount
xDololow           xD
Администратор(Administrator)
Гость(Guest)
```
My main account is xDololow. It's local and it is shown as administrator here: 
![image](https://user-images.githubusercontent.com/26763912/131526629-48da8dc2-b6a0-4717-8949-1623bb2a419d.png)

But the weird thing that if I run a program that requires being started as an administrator it won't work until I explicitly run it as administrator. 🤔

**Comment by peppy** [comment]
Can you check the "elevated" column in task manager to 100% confirm that osu! isn't somehow elevating?

https://user-images.githubusercontent.com/191335/131527253-5f7cdb4e-a725-48b6-a5c5-6c5fa78bcb43.mp4

**Comment by xDololow** [comment]
![image](https://user-images.githubusercontent.com/26763912/131531306-031cc4c1-b460-46bb-86a6-043f753372c4.png)
it is elevated

**Comment by peppy** [comment]
You're going to have to figure out why that's the case. It should not be elevated.

**Comment by AggressiveCombo** [comment]
@peppy Do you have any idea why that could cause that to happen?
I know there is no defenitive answer but maybe a reccomendation? 
I have that problem as well, and it's annoying, elevation is on "yes" and admin off

**Comment by peppy** [comment]
See https://github.com/ppy/osu/issues/14588#issuecomment-909348322

**Comment by Espionage724** [comment]
I propose a way for osu! to ignore elevated/admin or to not warn about it; like some checkbox at the bottom of settings that would only be enabled intentionally. I run with EnableLua=0 which is system-wide, and afaik can't run osu! as a normal user.

I'm confident enough in my OS set-up and don't need osu! giving a warning every start-up.

**Comment by bdach** [comment]
@Espionage724 With respect, you may be confident about your setup, but (1) you are the only one to request turning this off in literal years, and (2) the principle of least privilege is a firmly established security practice and we're as confident that ignoring it should result in notifications as you seem to be about disabling UAC (is there even a valid use case for doing this?)

**Comment by Espionage724** [comment]
osu! is the only software I've ran in years to ever mention anything about it. Steam, various games on it, WoW, Firefox, Chrome, Edge, Windows itself, and other random apps don't notify or act differently.

I understand it's not best-practice, but I'm also not going to change it because of a warning from a single game, so the notification being shown is just an annoyance, instead of being a warning. It feels like lazy UX to always have it showing without a condition check (anyone with EnableLua=0 intentionally isn't undoing it for osu!) or a way to not show it.

Perhaps after a one-time start as admin the notification should be shown; maybe someone ran it as admin by accident or thought they could get that performance improvement. After 6+ times in a row of starting the game as admin however, it should be clear I'm running osu! as admin on purpose, not heeding the notification, and it should be hidden out of user-respect.

I think checking for EnableLua=0 and not showing the notification would be the most simple approach; I'm thinking it stays at 1 even with the control panel setting at the lowest and it keeps the UAC sandbox stuff, so it being at 0 wouldn't be an accident.

I'm aware of how trivial this is, but osu! is the only software I've seen this with in years and it felt odd enough for me to come write about it :p

**Comment by bdach** [comment]
> maybe someone ran it as admin by accident or thought they could get that performance improvement

"performance improvement"?

> I'm aware of how trivial this is, but osu! is the only software I've seen this with in years and it felt odd enough for me to come write about it

Well the "fix" would not be trivial. To even test out your configuration we would have to disable UAC ourselves. It's non-trivial development time spent on just you.

**Comment by Espionage724** [comment]
> "performance improvement"?

The notification implies that someone may run osu! as admin to try to improve performance. I don't know how that would work, but the message is worded like someone tried before; I'm sure whoever wrote the message for osu!, committed it, and maybe translators for that string would know more details.

> To even test out your configuration and ensure the "fix" works we would have to disable UAC ourselves. 

It takes less than a minute to disable UAC temporarily and isn't some huge endeavor. This was a popular key back during Vista and early 7 days and still usable today on 10 and 11 for similar behavior.

> It's non-trivial development time spent on just you.

I'm not asking major developers to stop whatever they're doing today just to code up some logic for this :p Just as I stumbled upon an over year-old ticket about this, maybe someone else with the free time and care will find this, understand what I'm talking about, and pull request something. osu! is already doing a check for admin rights; surely it wouldn't be that much more effort to have the condition check go a little further to not needlessly annoy EnableLua=0? Assuming the detection logic isn't a pile of spaghetti, this seems like something that could be tossed together in an hour for a public contribution to a popular open-source project ;p

osu! is still the only exception to this compared to other more popular software over years, and I figure there's interest in having it more consistent.
