### ISSUE TITLE
"Left button" and "Right button" can have multiple keyboard keys bound to them

### ISSUE THREAD

**Issue by anexistantperson** [ppy/osu#14596]
**Describe the bug:** 
Due to Mouse inputs being unbindable from "Left button" and "Right button", You can somewhat bind more buttons to them. Causing a method of legitimately-cheating in comparison to stable. Although the buttons tend to override each other when doing this, they can still be used to stream at a normally-unrealistic speed.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/55331139/131603112-8b74be99-aba9-44ed-ae8f-758e65092b17.png)

**osu!lazer version:** 
2021.828.0

**Comment by peppy** [comment]
This is intended behaviour.
