### ISSUE TITLE
Placing new control points have no effect on some beatmaps

### ISSUE THREAD

**Issue by nolife99** [ppy/osu#14595]
**Describe the bug:** 
In the lazer editor, (note this is in specific maps such as galaxy collapse) timing points are displaying 2 values, along with having no effect. This forces the user to move 1 tick back, which causes timing points to have no effect and be deleted. (#12648)
To go into more detail, when timing points are placed with certain maps, it displays 2 different values 1 tick apart, along with having no effect due to not being on the same tick as the hitobject.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/89430659/131591629-d4565fb2-b842-475a-b148-bdba47999aef.png)
(The object next to the first object is clearly affected, but not the first one.)
![image](https://user-images.githubusercontent.com/89430659/131592161-9e20174a-b61c-4412-80cc-e7de19b9dc5a.png)
Look on the left for the control point offsets, and on the right side, it displays a different value for the offset.
**osu!lazer version:** 
2021.828.0-lazer
**Logs:**
I compiled the logs into a zip
[logs.zip](https://github.com/ppy/osu/files/7087372/logs.zip)

**Comment by nolife99** [comment]
I'm also going to note that I think this may be caused by the BPM of some maps

**Comment by peppy** [comment]
i have no idea what you are trying to say. please link the beatmap and specify exactly which control points you believe to be displaying wrong (with their exact offsets.

**Comment by nolife99** [comment]
Sorry for not responding, I was busy
The beatmap is https://osu.ppy.sh/s/396221
The control point that are displaying wrong is 00:52:901 (on the left side of the timing panel) and the displayed offset is 52,902 on the right hand side
As in the screenshot, the slider that is supposed to be attached to the timing point isn't affected at all, however the object next to it is affected. This is basically saying that the point is being placed too late while also being displayed wrong in the timing panel.

**Comment by peppy** [comment]
Thanks. Definitely looks like an issue. Possible with the `control_point_lenience` we are adding at decode time.

**Comment by peppy** [comment]
Going to refrain from looking further into this one until I'm done with the `DifficultyControlPoint` refactor, as things are in a bit of a state of flux right now. I don't believe my changes will fix this issue (and I have a good idea of what is going wrong here) but it's best fixed after the rest.

**Comment by nolife99** [comment]
Some hitobjects seem to be unsnapped by ~1 ms on some maps, but I have no idea why. This seems to also indirectly be the cause of this issue, but this occurs with some maps that don't have unsnapped objects.
(just saying)

**Comment by nolife99** [comment]
Just providing more screenshots:
![image](https://user-images.githubusercontent.com/89430659/132111722-ecda9284-f6ee-4126-8bdf-691295a01d49.png)
It seems to be placing hitobjects like this too it's really weird

**Comment by peppy** [comment]
Please stop posting screenshots of text files. It's unnecessary.

**Comment by peppy** [comment]
The control point mentioned in your opening post doesn't exist in the linked beatmap. Can you better explain what you're doing here? Are you attempting to edit the beatmap in the osu!(lazer) editor and add new control points?

**Comment by nolife99** [comment]
Yes, I'm trying to add more control points in the editor (the 10x one)

**Comment by peppy** [comment]
@nolife99 The way SV is adjusted (what used to be difficulty control points) has completely changed now, to the point I don't believe this issue still exists. I'm going to close the issue, but please leave a comment if you're still hitting any snags with what you're attempting to do.
