### ISSUE TITLE
Notification sound stacks when downloading multiple maps

### ISSUE THREAD

**Issue by Zalmez** [ppy/osu#14621]
**Describe the bug:** 
By downloading many maps at the same time, notification sound stacks. The issue with this it is extermly uncomfortable opening the notifcation tab and could possibly do "harm" if one downloads enough at the same
It is almost as if the sound gets played at x voulme * the amount of notifications. 

**Screenshots or videos showing encountered issue:** 
How it is when downloading multiple maps at the sametime:

https://user-images.githubusercontent.com/8438702/132077153-2d1833c4-603f-467f-af08-9d7605aa8b98.mp4

With 1 map:

https://user-images.githubusercontent.com/8438702/132077167-4a757ae5-6dbc-4d92-a7a7-df27d6ec7f6f.mp4

**osu!lazer version:** 
2021.828.0-lazer

**Comment by peppy** [comment]
It can't do harm because volume is limited by your OS volume settings. But it is annoying, for sure.
