### ISSUE TITLE
Playlist panel display is not asynchronous enough

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#14638]
https://user-images.githubusercontent.com/86934170/132138577-f250b465-3a5e-43ec-aa34-b92f643cbc20.mp4

The example of other sections (solo, multi) shows how much it stutters with playlists. Need to solve.
--

**Comment by peppy** [comment]
This is a known issue, due to no pagination and suboptimal asynchronous load of panels.

**Comment by peppy** [comment]
I've started looking into this. The largest portion of overhead is... reflection of mod settings. Each playlist item gets all its mods `ToMod`ded, which causes two reflection iterations over `SettingsSource` in *all cases* via the `GetModsFor` path instantiated `ModDifficultyAdjust` regardless of the query:

https://github.com/ppy/osu/blob/25420af078151b68146f8786911562869b39e7fd/osu.Game/Rulesets/Ruleset.cs#L43

https://github.com/ppy/osu/blob/90326f8864723bc4427512705da4295a9f316300/osu.Game/Rulesets/Mods/ModDifficultyAdjust.cs#L60-L64

![20210907 193308 (JetBrains Rider)](https://user-images.githubusercontent.com/191335/132330537-7414e9b2-e243-4836-bbde-211366b0a053.png)


Solving this is relatively simple (see https://github.com/ppy/osu/compare/master...peppy:fix-playlist-listing-performance?expand=1) and I believe we want a solution like this to avoid any overhead in a mod's `ctor`. On this branch, the performance overhead is reduced to:

![20210907 193338 (JetBrains Rider)](https://user-images.githubusercontent.com/191335/132330588-43bdbaaf-739b-4312-a204-ce42b7185f99.png)

The second is happening in `MapObjects` and more involved to replace:

https://github.com/ppy/osu/blob/fb0e9d6760c2877ae97b40ad62d601b9e6774369/osu.Game/Online/Rooms/PlaylistItem.cs#L78-L92

Looking for input on correct direction to resolve this. We could potentially cache the reflection methods, but I really don't know if that's the right direction. If possible I'd like to avoid the calls in the first place.

**Comment by smoogipoo** [comment]
Test

**Comment by smoogipoo** [comment]
Test (sorry for spam)

**Comment by bdach** [comment]
A trick that messagepack uses for this sort of thing is leveraging the fact that fully-constructed generic types are really "separate" types with their own set of static fields, and using that to cache stuff in a `private static readonly` field, something like so:

```csharp
public class ModSettingsCache<TMod>
    where TMod : Mod
{
    private static readonly IEnumerable<(SettingSourceAttribute, PropertyInfo)> settings_source_properties
        = typeof(TMod).GetProperties(BindingFlags.GetProperty | BindingFlags.Public | BindingFlags.Instance)
                      .Select(property => (property.GetCustomAttribute<SettingSourceAttribute>(), property))
                      .Where(pair => pair.Item1 != null);

    public static IEnumerable<(SettingSourceAttribute, PropertyInfo)> SettingsSourceProperties => settings_source_properties;
}
```

essentially relying on the static initialiser to do the lazy one-time initialisation logic. (The same could be achieved with a `Lazy<T>`, obviously). That sounds like about the best middle-ground between performance and "automatic" extensibility, but at the cost of adding a `static`... The types returned there *seem* mostly immutable, aside from `SettingSourceAttribute.SettingControlType`, so it may be alright to throw an interface on that and call it a day?

Aside from that, I can't see any performant way out of this other than hand-rolling `ToMod()` implementations for each mod type, or source generators (which from I recall have several shortcomings still)...

**Comment by peppy** [comment]
Hmm, that's actually quite a cheap way (implementation wise) to handle caching like this, kinda like it.
