### ISSUE TITLE
`SectionsContainer` initially does not properly scroll to autosized sections that are masked away

### ISSUE THREAD

**Issue by bdach** [ppy/osu#14631]
Foreshadowed by my pre-emptive disclaimer at #14630. I'm opening this as an issue partially because I don't know how to tackle this best. The following video will probably explain the repro case better than I can:

https://user-images.githubusercontent.com/20418176/132109022-194e3564-0d3f-4b9a-b571-a6bd8e137ae4.mp4

Notice how it takes three clicks of the kudosu! section tab to navigate to it, and in the editor setup screen it takes two clicks on the design tab to properly scroll to the end (that one is more subtle, but becomes less subtle with the aforementioned pull).

The cause of this is that, as stated in the title, `SectionsContainer` does not play well with autosized content that is initially masked away. Because said content is masked away and its initial bounding box/draw size is not necessarily correct or final, the scroll positions for each section are not calculated properly, unless the *initial* size is already correct. This catches things like:

* Content that is loaded dynamically based on a web request in the background
* Content that is not yet fully sized because some children are created in BDL or similar
* Content that has transforms on it which play out off-screen

In the case of the setup screen at least the "culprit" is the colours section and its child `LabelledColourPallette` which does not get its full size computed correctly until it is unmasked.

I am not sure what the proper solution here is. Maybe it is sync-loading the sections before adding them to the `SectionsContainer` to ensure they're in a good initial state. Maybe it is only enabling masking on `LoadComplete()` (I tested this and it kinda works). It is most likely *not* just turning off masking because that's just inefficient.

**Comment by peppy** [comment]
Sounds like we're wanting to do a forced compute either on load or before the `scrollTo` operation, for sure.
