### ISSUE TITLE
Games becomes unplayable after saving edited skin and restarting beatmap.

### ISSUE THREAD

**Issue by willmexe** [ppy/osu#14639]
**Describe the bug:** 
If you open the ingame skin editor while playing a beatmap and edit something then save and then press escape and restart the game only shows the beatmap background and escape crashes the game (in the video the game crashes after i pressed escape).

**Screenshots or videos showing encountered issue:** 
https://youtu.be/zvRxbuJXUyI

**osu!lazer version:** 
2021.828.0-lazer

**Logs:**
[database.log](https://github.com/ppy/osu/files/7112223/database.log)
[network.log](https://github.com/ppy/osu/files/7112224/network.log)
[performance.log](https://github.com/ppy/osu/files/7112225/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7112226/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7112227/updater.log)

**Comment by peppy** [comment]
The only errors in your logs are due to custom rulesets. Please unload them and try again.

If you are actually getting an error, please attach the logs with the error and we'll reconsider the issue.
