### ISSUE TITLE
Errors returned from API use language chosen on web rather than client's

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#14662]
**Describe the bug:** The "_You have too many favourited beatmaps_" notification seems to ignore the selected in-game language.
I guess the message is retrieved from the request to favourite a beatmap, which uses the website language for the response (edit: confirmed after checking the `network.log` file).
It's not really an issue, but seeing two different languages at the same time might seem wrong.

In the example below, both notifications were triggered while the language in-game was `English`.

- In the first notification (from top to bottom), the language of the website was set to `English`.
- In the second notification, the website language was set to `Italian`.

At the moment I don't remember if there are other similar requests/notifications, so I'll just keep the scope of this issue on this specific case.

**Screenshots or videos showing encountered issue:**

![image](https://user-images.githubusercontent.com/43073074/132344431-679bcaae-c31c-4ec3-b2ee-827222eaa064.png)

**osu!lazer version:** `2021.907.0`

**Comment by bdach** [comment]
The error message does indeed come from web and will indeed use the language chosen web-side. Not sure how to proceed here, maybe the client language and the website language should sync up at some point.

This won't be specific to this one case either, I imagine this will happen every time that user-readable errors from web are displayed on the client UI.

**Comment by frenzibyte** [comment]
Or, alternatively, let osu!web provide the key to the localisable string for the client to identify. Might be easier if feasible.

**Comment by bdach** [comment]
Actually I forgot that a somewhat typical method to do something like this is sending an `Accept-Language` header from the client and letting web handle it to return the proper translated message.

**Comment by peppy** [comment]
Agree that is the easiest / best direction initially.
