### ISSUE TITLE
Multiplayer password popover not properly handling Escape key

### ISSUE THREAD

**Issue by sh0ckR6** [ppy/osu#14669]
**Describe the bug:** 
The popover that prompts for a password on a locked multi room does nothing when the Escape key is pressed. 

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/68568464/132412970-b6b29530-0c6e-4915-be04-1ff8c62f3005.mp4

**osu!lazer version:** 
2021.907.0

**Logs:**
I'm pretty sure these aren't necessary but I can add them if needed

**Comment by sh0ckR6** [comment]
I've narrowed it down to only when using the escape key. **Clicking** away from the popover will close it and return keyboard focus to the search bar. Using the escape key shows the behaviour above.

**Comment by peppy** [comment]
The issue isn't that "focus isn't being lost", rather that popovers are not handling the escape key at all.

**Comment by Theighlin** [comment]
Don't know if it's a separate issue but seems related, I had this problem with the betamap listing overlay, but only when i searched for something and scrolled down. It didn't get captured, but everything was done via mouse and on screen keyboard, pressing the escape key  too.

https://user-images.githubusercontent.com/53081750/132542696-2d04888f-c5fe-4277-a888-a74eaae869aa.mp4

**Comment by sh0ckR6** [comment]
Are you talking about the beatmap listing not closing with the escape key when there's something in the search box? If so, I'm 99% sure this is intended behaviour.

**Comment by bdach** [comment]
@Theighlin separate issue thread, please.
