### ISSUE TITLE
Typo in the supporter promo section

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#14663]
(I guess you can also vary this section with the language in the future)

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/43073074/132366910-f4d8a06a-56c2-4c53-8c56-b0350620c7af.png)

**osu!lazer version:** `2021.907.0`

**Comment by bdach** [comment]
In the end of the day it will probably be best to fix it by replacing current hard-coded English with web strings once `TextFlowContainer` is localisable, but it's a simple enough fix if anyone wants to get their feet wet.
