### ISSUE TITLE
osu(lazer) installer issue

### ISSUE THREAD

**Issue by Yoel-Yisuru** [ppy/osu#14689]
Hi, i cannot open the last versión of osu lazer.
When i open the Osu(lazer) installer after a few seconds it stop working.
Here i leave a event log windows information.

- System

- Provider

[ Name] .NET Runtime

- EventID 1026

[ Qualifiers] 0

Level 2

Task 0

Keywords 0x80000000000000

- TimeCreated

[ SystemTime] 2021-09-08T12:38:37.000000000Z

EventRecordID 241384

Channel Application

Computer Yoel

Security

- EventData

Application: osu!.exe CoreCLR Version: 5.0.220.61120 .NET Version: 5.0.2 Description: The process was terminated due to an unhandled exception. Exception Info: System.TypeInitializationException: The type initializer for 'Realms.SharedRealmHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'realm-wrappers' or one of its dependencies: No se encontró el proceso especificado. (0x8007007F) at Realms.SynchronizationContextScheduler.install_scheduler_callbacks(get_context get, post_on_context post, release_context release, is_on_context is_on) at Realms.SynchronizationContextScheduler.Install() at Realms.NativeCommon.Initialize() at Realms.SharedRealmHandle..cctor() --- End of inner exception stack trace --- at Realms.SharedRealmHandle.Open(Configuration configuration, RealmSchema schema, Byte[] encryptionKey) at Realms.RealmConfiguration.CreateRealm(RealmSchema schema) at Realms.Realm.GetInstance(RealmConfigurationBase config, RealmSchema schema) at Realms.Realm.GetInstance(RealmConfigurationBase config) at osu.Game.Database.RealmContextFactory.createContext() at osu.Game.Database.RealmContextFactory.GetForWrite() at osu.Game.OsuGameBase.migrateDataToRealm() at osu.Game.OsuGameBase.load() --- End of stack trace from previous location --- at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance) at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext) at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child) at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation) --- End of stack trace from previous location --- at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance) at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext) at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child) at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation) --- End of stack trace from previous location --- at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance) at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext) at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child) at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation) --- End of stack trace from previous location --- at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance) at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext) at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child) at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation) --- End of stack trace from previous location --- at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies) at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance) at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies) at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext) at osu.Framework.Platform.GameHost.bootstrapSceneGraph(Game game) at osu.Framework.Platform.GameHost.Run(Game game) at osu.Desktop.Program.Main(String[] args)

This problem doesn't happen with a old version from a few months ago (like 2 months), but when i update osu in that same version the problem get out again.

Some solution?

**Comment by bdach** [comment]
Please state your operating version system.

**Comment by Yoel-Yisuru** [comment]
> Please state your operating system version.

I have Windows 7 Ultimate

**Comment by bdach** [comment]
Windows 7 support has been dropped for now as we're moving forward with realm for database storage. This may change at a future date but this is how things stand right now, sorry.
