### ISSUE TITLE
"Reset all bindings in section" text can go out of the button in different languages

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14685]
**Describe the bug:** It should probably asdjust its size based on containing text.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/53081750/132557728-a03456a4-8d91-4754-a121-28b688509aa1.png)
![image](https://user-images.githubusercontent.com/53081750/132557762-0fc88221-2bd7-4a48-8b4a-9fe349f1da65.png)

**Comment by bdach** [comment]
this will be relatively simple to fix if all languages' button text can fit in the width of the settings panel, and not simple (and require localisable text flow) if there _are_ languages with button text that would cause the width of the settings panel to be exceeded. all languages need to be checked before PRing any solution.

**Comment by Emil8250** [comment]
Is this in the desktop application?

**Comment by bdach** [comment]
@Emil8250 i'm not sure what you mean by that. please elaborate.

**Comment by Emil8250** [comment]
@bdach I was just wondering if it was bindings on the app or the desktop application. 
But I now notice which keys are bound, so it's clear to me now. Sorry.

**Comment by Emil8250** [comment]
Do you want the button to always use max width (which is compatible with all languages), or do you want the button to fit to the text length?
