### ISSUE TITLE
Crash on launch starting at version 2021.703.0

### ISSUE THREAD

**Issue by Maoman1** [ppy/osu#14693]
**Describe the bug:** 
Disclaimer: I am on Windows 7. _Yeah_ I know, but I'm forced to use it for work (don't ask...), I can't afford a second computer, and last time I tried to set up a dual boot I fucked something up and had to start over from scratch so like hell I'm trying that again if I don't have to. 

Anywho. My tablet died almost a year ago so I was unable to play osu for a while. I was finally able to get a new tablet and I immediately played for a couple of hours. The game obviously downloaded a bunch of updates but I just ignored it and let it actually install the update next time I started the game.

Well next time I started the game it crashed instantly on launch. 
I uninstalled and clean reinstalled the latest version to confirm, no change.
I uninstalled again and tried older versions until I found the last working release: version 2021.623.0 runs with no problem - uninstalling again and installing version 2021.703.0 (the very next stable release) causes it to crash on launch. 

I would be _extremely_ appreciative if this issue were actually addressed, but I was met with a lot of attitude last time I mentioned I'm still stuck on windows 7 here so I'm honestly expecting y'all to just shrug me off. 

If you consider this issue a waste of your time, please at least tell me whether there is any way to prevent Lazer from automatically updating so I can just stay on version 623 instead of being stuck with osu!stable. I couldn't find anything about it in the options menu but I'm hoping there's a line buried in a config file or something.

**Logs:**
[network.log](https://github.com/ppy/osu/files/7133258/network.log)
[runtime.log](https://github.com/ppy/osu/files/7133259/runtime.log)

**Comment by peppy** [comment]
We don't support windows 7 any more. Sorry.

**Comment by Maoman1** [comment]
-sigh- please read the last paragraph.

**Comment by Maoman1** [comment]
Better than nothing I guess. Thanks.

**Comment by peppy** [comment]
Reading is a two way street. Please read the screen before opening an issue, which mentions that you should be opening a discussion, not an issue.
