### ISSUE TITLE
Leaderboard ordering inconsistencies can still exist when comparing scores with/without Classic Mod

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#14697]
### Discussed in https://github.com/ppy/osu/discussions/14664

<div type='discussions-op-text'>

<sup>Originally posted by **MrWither83** September  8, 2021</sup>
With the way the scaling is done with the new Classic scoring algorithm (based on maximum combo), there can still be inconsistencies in leaderboards when comparing scores with and without classic mod, as not using classic mod doesn't make sliderends count towards combo.

Here's an example :
![image](https://user-images.githubusercontent.com/52672543/132379680-2eaee19c-09d1-4668-afcc-44bb7dd31032.png)

I'm not sure if scores with/without classic mod should be compared, as the Classic mod impacts several elements of core gameplay.

If the decision is taken that classic/non classic scores should be compared, maximum combo should stay constant whatsoever to ensure leaderboard stability with Classic scoring.</div>

**Comment by peppy** [comment]
@smoogipoo do you have any initial thoughts about how to solve this one? We've previously discussed potentially deflating classic scores to allow these kinds of cases to coexist, but I don't know how feasible that is from a user-acceptance perspective.

**Comment by smoogipoo** [comment]
I don't know how to solve this one yet. I thought we wanted to remove mod multipliers...?

**Comment by peppy** [comment]
I didn't mean a multiplier - more some change to how the max combo is introduced to allow lazer to have higher headroom for scores (based on slider heads being accuracy based). The unfortunate part is that classic *increases* the available combo, not vice versa.

**Comment by smoogipoo** [comment]
More generally, any mod that changes combo needs the same thing applied to it, somehow.
