### ISSUE TITLE
Deploy cross compatibility for Unix. Paths and Files.

### ISSUE THREAD

**Issue by Zylviij** [ppy/osu#1470]
In file: `./osu/osu.Desktop.Deploy/Program.cs`
In the function `private static void findSolutionPath()`

This method of getting the current directory and incrementally finding parent folders is not Unix (macOS Sierra) safe. 
```
string path = Path.GetDirectoryName(Environment.CommandLine.Replace("\"", "").Trim());

while (!File.Exists(Path.Combine(path, $"{SolutionName}.sln")))
    path = path.Remove(path.LastIndexOf('\\'));
path += "\\";
```

I suggest using `System.IO.Directory`:
```
string path = Directory.GetCurrentDirectory();

while (!File.Exists(Path.Combine(path, $"{SolutionName}.sln")))
{
    path = Directory.GetParent(path).FullName;
}
```

I am not yet very well acquainted with the "Deploy" module, so I apologize if I'm missing the point or if my code doesn't solve the problem. 

**I do not know if this code works correctly** as I have yet been able to compile it due to errors with the Github fetch call.

**Comment by Nabile-Rahmani** [comment]
More or less yes, but there's some more things that need to be taken into account, such as the [hard-coded](https://github.com/ppy/osu/blob/master/osu.Desktop.Deploy/Program.cs#L19-L21) tools' paths and ensuring all dependencies are cross-platform.
What's sure is that, for instance, Linux has both msbuild and nuget in its PATH when installing the Mono packages; only Squirrel would have to be located in a similar fashion.

**Comment by peppy** [comment]
Closing as zero-priority. Feel free to test and PR a fix for this, but that deploy script it basically windows-only at the moment.
