### ISSUE TITLE
Editing a ranked beatmap don't make it unranked

### ISSUE THREAD

**Issue by Joao-Tome** [ppy/osu#14715]
**Describe the bug:** 
When you editing a ranked beatmap, and save, the map continue Ranked, and I can't update the map again, and thing like this happen.

**Screenshots or videos showing encountered issue:** 

The map I tested
![osu_2021-09-11_13-22-03](https://user-images.githubusercontent.com/73352040/132954546-5daf459a-7b13-4545-a170-8d7633225d0c.jpg)

How i edit it.
![osu_2021-09-11_13-22-16](https://user-images.githubusercontent.com/73352040/132954548-b6233d15-6a61-4939-8006-b8b37deffbfa.jpg)

My ranks for testing the bug
![osu_2021-09-11_13-22-58](https://user-images.githubusercontent.com/73352040/132954556-8ac3cd93-cfbe-4b94-bb35-efdaf0efd866.jpg)

My Profile page of Recent plays 
![image](https://user-images.githubusercontent.com/73352040/132954533-030be94a-54db-4c4f-8a30-6c3bd135cdb9.png)

The SS on the profile is too from this, I just delete from my game to see if it's delete from my profile too, but did not work.

**osu!lazer version:** 
2021.907.0

**Logs:**
Logs
[logs.zip](https://github.com/ppy/osu/files/7148169/logs.zip)

My profile in osu: https://osu.ppy.sh/users/5337493

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/11922
