### ISSUE TITLE
Loved storyboard beatmaps cause huge drops of fps and freezes

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#14719]
https://youtu.be/ptqwVI7pcMA
https://youtu.be/ih7T7ZUdcZU

https://osu.ppy.sh/beatmapsets/1236927
https://osu.ppy.sh/beatmapsets/982020

**Comment by peppy** [comment]
See https://github.com/ppy/osu/issues/12401

**Comment by Loreos7** [comment]
We will assume that I recorded a video that shows the issue

**Comment by Coppertine** [comment]
Gonna say this issue should be reopened as this is related to SliderNode allocation and NOT storyboard loops on sprites.

**Comment by peppy** [comment]
Please open a new issue with full details explaining that.
