### ISSUE TITLE
Score meter moves to the right in spectator mode

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#14711]
**single mode**

![ScreenShot_20210910184056](https://user-images.githubusercontent.com/86934170/132882141-49c8eae9-9cc3-4e0a-9d37-8cd646e2570c.png)
**multi**

![ScreenShot_20210910183948](https://user-images.githubusercontent.com/86934170/132882145-546e5a56-c6ac-4870-b8c8-3b34f96e11dd.png)
![ScreenShot_20210910183934](https://user-images.githubusercontent.com/86934170/132882148-2c3935cc-5ab2-4fa5-8305-6079130b437c.png)

**Comment by bdach** [comment]
I can't reproduce this. Are you sure you've anchored the element correctly to make this happen the way you want it to? It should look like this.

![2021-09-10-205756_363x228_scrot](https://user-images.githubusercontent.com/20418176/132903788-6d79f8c2-b224-454c-9430-2c4f62a56406.png)

That is with Anchor set to BottomCentre and Origin set to CentreLeft.

**Comment by Loreos7** [comment]
I had wrong Anchor bind. Now it works
