### ISSUE TITLE
Error meter ticks are not centered

### ISSUE THREAD

**Issue by developomp** [ppy/osu#14714]
**Describe the bug:** The ticks in the Error bar are not perfectly centered.

**Screenshots or videos showing encountered issue:**
![not centered](https://user-images.githubusercontent.com/40858122/132934762-d889897f-9000-4ebe-92e3-9c22622cc394.png)

**osu!lazer version:** 2021.907.0

**Logs:** None

**Comment by peppy** [comment]
If you’re talking about autoplay I believe this is a duplicate and also intended (auto hits slightly early IIRC).

**Comment by developomp** [comment]
ah, I thought this was a bug because the right edge of the mark is exactly at the center. This must be a coincidence then. Shall I close the issue?

**Comment by frenzibyte** [comment]
There's nothing to take action on in this issue thread then, so there's no point in keeping it open anymore.
