### ISSUE TITLE
Editor: displayed bonus points of the spinners are stacked

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#14722]
**Describe the bug:** 
In the editor, you can now se the bonus points of the spinner when you spinned enough to get the bonus. The problem is in the editor... The displayed value is invalid if you check the part when you get bonus points not for the 1st time.

It seems like the value isn't calculated according to the time like it should be, but it just increase the bonus value, without reset it if needed.

This bug affects all spinners of the map, where each spinner have its own value with this bug. Looking for another spinner doesn't reset the bonus value of the other ones.

**Screenshots or videos showing encountered issue:** 
In this short video, there're only 2 spinners in the map.

https://user-images.githubusercontent.com/57914482/132989168-f6633ff9-1ffd-44a5-a169-be9c2bdde0cb.mp4

**osu!lazer version:**  2021.907.0

**Logs:**
[performance-audio.log](https://github.com/ppy/osu/files/7149623/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/7149624/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/7149625/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/7149626/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/7149627/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7149628/updater.log)
[database.log](https://github.com/ppy/osu/files/7149629/database.log)
[performance.log](https://github.com/ppy/osu/files/7149631/performance.log)

**Comment by peppy** [comment]
Likely just another issue related to editor not using stable frame playback.

**Comment by frenzibyte** [comment]
Sounds to be part of https://github.com/ppy/osu/issues/10455.
