### ISSUE TITLE
Same beatmap present twice in song select

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14738]
**Describe the bug:** This beatmap appears twice in song select, but only one shows detail when right clicking on the difficulties

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/53081750/133206176-ce9e2c90-2355-4c6c-ab38-2f6824f05315.png)
![image](https://user-images.githubusercontent.com/53081750/133206200-0cf7ca7a-ea06-405e-8778-af57272eaca2.png)

**osu!lazer version:** 2021.907.0-lazer

**Logs:** [runtime.log](https://github.com/ppy/osu/files/7159328/runtime.log)

**Comment by peppy** [comment]
Can you delete one? What is your expectation here? We can't really action on this unless you are asking about "why was it imported twice?". If that's the case, we would need import logs to actually figure anything out (ie `database.log` from when the second instance was imported).

**Comment by Theighlin** [comment]
I've tried 2 things:
1: deleting the details clickable one and reimorting beatmaps from stable. Only 1 showed up with the details in the dropdown menu, but i still had 2 beatmaps after clicking restore deleted beatmaps in settings
2: same thing but deleting the other beatmap

This is the log from case 2 (but looks the same as case 1, i don't think there's anything useful)
[database.log](https://github.com/ppy/osu/files/7160184/database.log)

I don't have the original database.log because i only noticed this now, you can close this issue if that's all the information you needed, unless you want to keep it open for tracking.

**Comment by peppy** [comment]
If you can reproduce this again, please comment on this issue with reproduction steps. Can't really do anything until then, just delete one.
