### ISSUE TITLE
osu!lazer has stopped working when clicked on

### ISSUE THREAD

**Issue by TomPatelGaming** [ppy/osu#14736]
Every time I open osu!lazer it keeps coming up with this error shown here
![image](https://user-images.githubusercontent.com/90646489/133138477-c73a06e8-15d7-4c35-89e9-632176254bbb.png)

I just downloaded osu!lazer yesterday and it still doesn't work. The version is 2021.907.0 and I use Windows 7. Why is this error popping up?

**Comment by bdach** [comment]
Because windows 7 is not supported. Read the readme page, the windows release is tagged as 8.1+.
