### ISSUE TITLE
osu!taiko mods (HD and FL) not behaving as intended

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu#14734]
HD and FL are not working as intended, or at least, does not match behaviour on osu!stable

1. HD viewfield is way too small.
Lazer:
![osu_2021-09-13_13-41-43](https://user-images.githubusercontent.com/30021847/133085457-f3d1e12d-3c1a-44f0-b53e-4a41184a4d94.jpg)

Stable:
![screenshot043](https://user-images.githubusercontent.com/30021847/133085807-cc9948d9-606d-4a4b-9639-047b625e9b17.jpg)

Now, a consensus has not yet been reached by the community regarding the behaviour of HD in widescreen on lazer (because notes take longer to travel across the screen on 16:9, but in the lazer screenshot, not only do the notes take longer, the amount of notes you can see at a time is reduced as well. This makes this exponentially harder. 

HDHR as a consequence is also completely unreadable - notes fadeout offscreen before they even reach the viewable playfield.

Will do a poll on widescreen HD behaviour eventually (it would be greatly helpful if the amount HD covers could be adjustable, we can really figure out where we want "official" HD to be placed)

2. FL is not centred around the middle.
Lazer: 
![image](https://user-images.githubusercontent.com/30021847/133086714-700b3ab1-f10f-4413-bcc9-dd402068156f.png)

Stable:
![image](https://user-images.githubusercontent.com/30021847/133086813-a5ce0071-6b0c-41dc-b9e5-64ae8559096b.png)

This one should be a simple one to fix, the flashlight should be level with the playfield at all times. This problem is exacerbated on when reducing the vertical scale:

Lazer (100% Horizontal/50% Vertical):
![osu_2021-09-13_13-55-13](https://user-images.githubusercontent.com/30021847/133087446-2fdc0a36-8858-4b35-88a9-77d9d8770fdd.jpg)

**osu!lazer version: 2021.907.0 (Latest), though I have noticed this issue since the Classic mod was implemented in taiko.**

**Comment by peppy** [comment]
Just going to link https://github.com/ppy/osu/discussions/13047, which has similar discussion points.

**Comment by mangomizer** [comment]
Just realised the same issue was reported in #14252 
Just want to reiterate that the aforementioned issues make HD nigh unplayable and HDHR actually unplayable.

I would suggest for all resolutions, HD should have notes fade out completely when reaching the middle of the screen. Yes this means that wider resolutions operate at an inherent disadvantage because notes would be invisible for longer before being hit, but this should be offset by the fact that they appear on the screen for longer as well.

Similar behaviour should be seen for HDHR.

Would appreciate if these could be fixed at a high priority - I reiterate that certain aspects of the game are unplayable in its current state. My intention is to host a mini-tournament / showmatch soon, which will allow a large number of players to properly test out features in osu!lazer and get feedback, but this won't be possible if parts of the game aren't functioning.
