### ISSUE TITLE
Incorrect leaderboard shown at song select when beatmap takes considerable time to load

### ISSUE THREAD

**Issue by xDololow** [ppy/osu#14762]
**Describe the bug:** 
Title + It happened only when beatmap is long and big because there's a slight fps drop when switching.

**Screenshots or videos showing encountered issue:** 
This map is graveyarded.
![image](https://user-images.githubusercontent.com/26763912/133561738-3dcdcb76-b755-48b0-9d73-b9daf2e4f12b.png)
Happened on the first try.
https://user-images.githubusercontent.com/26763912/133562264-286adfd4-686f-4206-9766-71a84c3da96c.mp4

**osu!lazer version:** 
2021.907.0

**Logs:**

[updater.log](https://github.com/ppy/osu/files/7175399/updater.log)
[database.log](https://github.com/ppy/osu/files/7175400/database.log)
[network.log](https://github.com/ppy/osu/files/7175401/network.log)
[performance.log](https://github.com/ppy/osu/files/7175402/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7175403/runtime.log)

**Comment by peppy** [comment]
@xDololow at the start of your video, it shows there is a leaderboard for that graveyard beatmap, but that doesn't seem possible (have confirmed just to make sure). was it already in the bugged state at the start of the video?

**Comment by peppy** [comment]
Never mind, that is definitely the case (the first leaderboard is from the beatmap above).
