### ISSUE TITLE
Typing after entering wrong password via keyboard in multi starts searching for a room instead

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14779]
**Describe the bug:** This does not happen when manually pressing on the join button

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/53081750/133756197-33ab96b1-2891-40af-96bd-4d6acc47f168.mp4

**osu!lazer version:** 2021.916.0-lazer

**Comment by Theighlin** [comment]
I understand that it's a very unlikely scenario, but this can still happen when doing it very fast, just poiting this out

https://user-images.githubusercontent.com/53081750/134967803-0fad825f-5390-403e-b47a-36bb84fb7736.mp4

**Comment by peppy** [comment]
Please provide logs

**Comment by Theighlin** [comment]
[network.log](https://github.com/ppy/osu/files/7245043/network.log)
[performance.log](https://github.com/ppy/osu/files/7245044/performance.log)
[database.log](https://github.com/ppy/osu/files/7245046/database.log)
[runtime.log](https://github.com/ppy/osu/files/7245047/runtime.log)
