### ISSUE TITLE
You can rewind a map while in the middle of playing (caused by offset being applied every time a map is paused)

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu#14773]
Extension of discovery from #14770, though not strictly related. Credit to zachmanthethird

**When playing with an Audio offset, upon resuming from pause, the offset is stacked again onto the map again (though the mp3 offset remains consistent).** 

If I play with +500 offset, when I pause, upon resuming all objects appear to reset back to their position at 0 offset, effectively "turning back time" by 500ms. This can be done multiple times throughout the map.

Best to watch the videos below to understand.

**Example with osu!catch:** 
beatmap used: https://osu.ppy.sh/beatmapsets/393995#fruits/857602
https://user-images.githubusercontent.com/30021847/133720702-9205ec00-c0e0-41b4-9531-9d384c99adc6.mp4

**Further example with osu!taiko:**
beatmap used: https://osu.ppy.sh/beatmapsets/958476#taiko/2006816
https://user-images.githubusercontent.com/30021847/133720736-8ff6b034-e89a-4030-b300-1e9a7f37bec9.mp4

**Interesting behaviour with finishers having their combo counted twice when reverted. This ONLY happens to finishers when hit with both sides of the drum:**
beatmap used: https://osu.ppy.sh/beatmapsets/566725#taiko/1200449
https://user-images.githubusercontent.com/30021847/133720768-1d6fcc5f-8251-4147-b120-c0911de7d51b.mp4

This bug works in reverse too. So playing with -500 offset will skip the map forward in time by 500ms each time you pause (considerably less abuseable since it only leads to misses).

In additon, the bugged scores also submit for osu!
![image](https://user-images.githubusercontent.com/30021847/133719983-cb76e8a7-06d5-4b08-b2e6-382539826f8b.png)

Using the osu!plus extension also shows that the score submitted with 47/40x combo which obviously is not intended.
![image](https://user-images.githubusercontent.com/30021847/133720081-3ff6d718-e475-4a63-81a6-00b7c610ef0b.png)

**osu!lazer version: 2021.916.0** 

Full Quality videos of the above if needed:
1. https://cdn.discordapp.com/attachments/315319764354596865/888262518324207716/2021-09-17_04-12-01.mp4 
2. https://cdn.discordapp.com/attachments/315319764354596865/888264144770457610/2021-09-17_04-23-19.mp4
3. https://cdn.discordapp.com/attachments/315319764354596865/888265475769909248/2021-09-17_04-27-48.mp4

and replays:
1. https://cdn.discordapp.com/attachments/614431704064589824/888272181371498566/mangomizer_playing_toby_fox_-_Quiet_Water_Intelli_Still.osr
2. https://cdn.discordapp.com/attachments/614431704064589824/888272175730143232/mangomizer_playing_toby_fox_-_Quiet_Water_Axer_Kantan.osr
3. https://cdn.discordapp.com/attachments/614431704064589824/888272182587842610/mangomizer_playing_Hanasaka_YuiCV__M.A.O_-_Harumachi_Clover_Xinely_Kantan.osr

**Comment by peppy** [comment]
Sounds like the wrong clock is being seeked in the forced-seek we perform on resuming gameplay.
