### ISSUE TITLE
Beatmap star rating display on lobby banner only updating after you play the map

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#14786]
Inside of the lobby, when you choose a new map, the star rating display at the top doesn't update. It only updates after you played the chosen map.

Video:

https://user-images.githubusercontent.com/81645139/133835428-0e20b60a-e5dd-429b-9c33-316a6ad81f47.mp4

Logs (not sure if helpful in this case):
[database.log](https://github.com/ppy/osu/files/7187792/database.log)
[network.log](https://github.com/ppy/osu/files/7187793/network.log)
[performance.log](https://github.com/ppy/osu/files/7187794/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7187795/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7187796/updater.log)

**Comment by bdach** [comment]
Will likely be fixed together with https://github.com/ppy/osu/issues/14788.

**Comment by peppy** [comment]
Has since been resolved.
