### ISSUE TITLE
Participant count on multiplayer room screen doesn't update on user changes

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#14788]
The participant count on the banner at the top **never** shows youself and (I think) it doesn't update too. So if a new player joins the lobby, the participant count on the banner stays the same (this last one I couldn't test again tho, as there was no public open lobby a few minutes after I recorded this video).

Video showing that the banner doesn't show yourself:

https://user-images.githubusercontent.com/81645139/133837380-5d7b295d-f312-4fd1-ac3b-36184e527d11.mp4

Logs (as I said, I could only test the case where the banner doesn't show yourself):
[database.log](https://github.com/ppy/osu/files/7187809/database.log)
[network.log](https://github.com/ppy/osu/files/7187810/network.log)
[performance.log](https://github.com/ppy/osu/files/7187811/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7187812/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7187813/updater.log)

**Comment by peppy** [comment]
I think this has been resolved with the design refresh?
