### ISSUE TITLE
Can`t install

### ISSUE THREAD

**Issue by Fab4key** [ppy/osu#14795]
Writting in cmd Update.exe --install=app-2021.916.0 (because lazer didnt install first time) and happened error

![image](https://user-images.githubusercontent.com/87313205/133893482-59dc8c1d-9a58-4962-a17c-457c77336ec3.png)

Logs:
[SquirrelSetup.log](https://github.com/ppy/osu/files/7190147/SquirrelSetup.log)

Using Windows 7 64 bit
DirectX9

**Comment by bdach** [comment]
please read the README, windows 7 is not supported.
