### ISSUE TITLE
Huion Tablet Driver software does not work on osu!lazer

### ISSUE THREAD

**Issue by Urzylol** [ppy/osu#14803]
**Describe the bug:** 
Huion Tablet Driver software does not work on osu!lazer
_(I would like to switch to OpenTabletSoftware but I do not know how to calculate the area between the two)_
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/34139161/133931485-f6d88b1d-ef6e-4d25-9395-0660edf82ee9.png)

![image](https://user-images.githubusercontent.com/34139161/133931606-32ffa242-dfd6-4ae1-8e83-938f2310bccc.png)

**osu!lazer version:** 
2021.916.0
**Logs:**

<!--
[database.log](https://github.com/ppy/osu/files/7192275/database.log)
[network.log](https://github.com/ppy/osu/files/7192276/network.log)
[performance.log](https://github.com/ppy/osu/files/7192277/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7192278/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7192279/updater.log)
*

**Comment by URSELLLIN** [comment]
The first screenshot is supposed to show that I do not have a cursor.

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues?q=is%3Aissue+huion+is%3Aclosed
