### ISSUE TITLE
Time Since Score not Being Shown

### ISSUE THREAD

**Issue by M0RGaming** [ppy/osu#14810]
I am unsure if this expected behaviour is correct since I've never seen it as anything other than a question mark. I am also unsure if this is known or not, as after a quick search of the issues, I've been unable to find any issue regarding this. 

**Describe the bug:** 
In the local scores tab, there is a question mark below the scorer's username. I believe that this is where the time since the score was submitted was shown, however, I'm not entirely sure, as it has always been a question mark for me.

**Screenshots or videos showing the encountered issue:** 
![Screen Shot showing the bug](https://user-images.githubusercontent.com/13577339/133954446-6f3217a9-d237-44e5-bda0-eec279d028a2.png)

**osu!lazer version:** 
I am currently running osu 2021.916.0.0 on .NET 5.0.1, however, I have experienced this bug for a couple of months atleast.

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/7193503/runtime.log)

**Comment by peppy** [comment]
That's the flag. It will eventually be populated when we handle local users better. Please open discussions, not issues.
