### ISSUE TITLE
Settings overlay do not handle mouse wheel up properly

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu#14818]
Describe the bug: 
1. Open Settings
2. Scroll mouse wheel **down** while cursor **inside** of the settings.
3. Settings scroll down. (expected result)
4. Scroll mouse wheel **up** while cursor **inside** of the settings.
5. -> Settings do not scroll up, but Master Volume go up. (**unexpected result**) <-
6. Scroll mouse wheel **down** while cursor **outside** of the settings.
7. Master Volume go down. (expected result)
8. Scroll mouse wheel **up** while cursor **outside** of the settings.
9. Master Volume go up. (expected result)

video of me following the steps above that showing the issue: (please pay a bit attention to the volume of the video)

https://user-images.githubusercontent.com/18349191/134086380-bcec107c-fc79-4eca-bd2e-2a3984a2df3b.mp4

osu!lazer version: 2021.916.0, also confirmed on local debug release@master(46a39a4188892fc56eaadd9bcd7d0ba081993f13)

**Comment by integerrr** [comment]
I can reproduce if i only bind wheelup to `increase volume` secondary but leave `decrease volume` secondary binding empty
> <img width="445" alt="image" src="https://user-images.githubusercontent.com/7279624/134092915-b2728f68-2a10-40f3-835f-59a2ec3aba52.png">

But I cannot repro when I unbind all secondaries
> <img width="444" alt="image" src="https://user-images.githubusercontent.com/7279624/134092586-3a49e8ea-a06a-4801-9d31-663952ce3456.png">

Are you able to check your bindings?

**Comment by kj415j45** [comment]
![image](https://user-images.githubusercontent.com/18349191/134095512-45867681-f768-4b50-888a-5a1df695fc42.png)
yep, `wheel up` was bind to increase volume, it was set by Test :thinking:. and I don't have a secondary binding, strange.

**Comment by integerrr** [comment]
`wheel up`, `alt-down`, `alt-left`, `alt-right`, `ctrl-F4` are all secondary bindings, try rebinding `wheel up` to something like `alt-up` (or just unbinding `wheel up`) and try again?
