### ISSUE TITLE
Music controller pause button does not pause gameplay

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#14816]
The `Now Playing`-tab can be brought up in replays by pressing `F6`. Interacting with it doesn't seem to do anything except make the gameplay stutter. Might be worthwhile to hide the `Now Playing`-tab in replays, EDIT: Also seems to happen while spectating and inside the editor.

**video:** https://www.youtube.com/watch?v=u7hUjr70XLI
**osu!lazer version:** 2021.916.0-lazer

**Comment by peppy** [comment]
you are smashing the pause button, of course it's going to stutter?

**Comment by smoogipoo** [comment]
The point is that it should pause gameplay rather than doing nothing. Super low priority.
