### ISSUE TITLE
Empty beatmap is created when pressing edit and backing out of it quickly

### ISSUE THREAD

**Issue by fuwaa** [ppy/osu#14878]
Related to #10628
> Exiting empty beatmap setup should not prompt "save changes" 

**Expected behavior:** 
- Empty beatmap shouldn't exist. 
- Setup prompt must be shown, preventing Reproduction Step 3.

**What actually happened:**
- No setup prompt was shown but an empty beatmap was created.

**Reproducibility:** Very Reproducible

**Reproduction steps:**
1. Click on play (doesn't have to be in the song select screen)
2. Back out and click on edit
3. Press ESC repeatedly as soon as edit is clicked on
4. Go on song select and scroll to the very top

**osu!lazer version & specifics**
- 2021.927.0-lazer
- Arch Linux, Kernel 5.13.19-xanmod1-1

**Logs**
[runtime.log](https://github.com/ppy/osu/files/7244395/runtime.log) [database.log](https://github.com/ppy/osu/files/7244401/database.log) 

**Video showing the bug**

https://user-images.githubusercontent.com/53419401/135097475-3b2601a9-b75e-466e-8807-224a33de1559.mp4

**Comment by Rattles69** [comment]
couldn't this be fixed by adding some code that says something along the lines of (when item placed in beatmap, add beatmap to "mappool") instead of doing it the moment the edit tab is opened? I'm too busy rn, just throwing out an idea

**Comment by peppy** [comment]
I'm too busy rn to tell you why, but your comment is pointless noise.
