### ISSUE TITLE
My osu keeps crashing

### ISSUE THREAD

**Issue by djenson2000** [ppy/osu#14930]
Looked in osu log files nothing useful there, windows event viewer does have some things though. Happens during gameplay randomly, every 10 or so beatmaps. Just disappears. no error message. Latest lazer version 
![image](https://user-images.githubusercontent.com/86269857/135677412-057d4f10-99a8-4ee0-a354-2e4d602164ef.png)
![image](https://user-images.githubusercontent.com/86269857/135677469-55a4d9ed-6a84-4980-be22-7c191754528c.png)

Fault bucket 1374782777815330792, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: osu!.exe
P2: 0.0.0.0
P3: 5fd43c92
P4: coreclr.dll
P5: 5.0.220.61120
P6: 5fd42cad
P7: c0000005
P8: 00000000000c25b9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER57C2.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER591A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER592B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5929.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5949.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_osu!.exe_abc3388d141141a6b23ba5ee56a203f9bac021_0d8b75ca_8f465bb8-be42-4c34-89ca-5cde94419208

Analysis symbol: 
Rechecking for solution: 0
Report Id: ee3982a8-a96a-4be3-92ef-171ed0df0991
Report Status: 268435456
Hashed bucket: c3e58dcfb25a78f0531435a70b01efe8
Cab Guid: 0

Things I've tried so far are running CHKDSK, reinstalling Osu!lazer running all windows updates

osu logs files are below, i dont think there anything bad about sharing them publicly??
If you want the windows dump files i can but id prefer to send those privately

[logs.zip](https://github.com/ppy/osu/files/7269774/logs.zip)

**Comment by bdach** [comment]
`0xc0000005` is an access violation exception, suggesting a driver level issue. [we've seen plenty of these](https://github.com/ppy/osu/search?q=c0000005&type=issues). about the best thing i can recommend is checking for graphics driver updates.

**Comment by djenson2000** [comment]
> `0xc0000005` is an access violation exception, suggesting a driver level issue. [we've seen plenty of these](https://github.com/ppy/osu/search?q=c0000005&type=issues). about the best thing i can recommend is checking for graphics driver updates.

Thanks for your help. Its a new laptop with freshly installed drivers so suspiring that its having driver issues already. It definably supports all the open GL things (i7-10875H + GTX 1660TI  MaxQ). will try a driver reinstall with DDU, and report back if that fixes.

**Comment by djenson2000** [comment]
> `0xc0000005` is an access violation exception, suggesting a driver level issue. [we've seen plenty of these](https://github.com/ppy/osu/search?q=c0000005&type=issues). about the best thing i can recommend is checking for graphics driver updates.

Yep, after that was playing with headphones in with the dark and system bluescreen making a right racket in my ears. Sorry for opening this for my issue.

**Comment by djenson2000** [comment]
> `0xc0000005` is an access violation exception, suggesting a driver level issue. [we've seen plenty of these](https://github.com/ppy/osu/search?q=c0000005&type=issues). about the best thing i can recommend is checking for graphics driver updates.



Hi there, sorry to send you another ping on this but i found the issue and thought it could be useful for future reference. The issue was the "memory integrity" function of windows security. I suspect that was blocking certain drivers needed during osu gameplay. Once ive turned that off ive had no issues atall.

**Comment by bdach** [comment]
Turning off memory integrity checks to fix this sounds dodgy. I'm not sure whether that's the OS detection being wrong or there is an actual invalid memory access, but if it's the latter then disabling the check is not an actual fix.

**Comment by djenson2000** [comment]
> Turning off memory integrity checks to fix this sounds dodgy. I'm not sure whether that's the OS detection being wrong or there is an actual invalid memory access, but if it's the latter then disabling the check is not an actual fix.

Memory integrity can make systems so unopenable microsoft released a bulletin saying to turn it off in some cases. Its not even on by default, don't know why i even turned it on when i got the laptop. Memory integrity stops certain drivers from loading correctly, so the errors and crash's in osu as well as the general bluescreens with the device all to do with driver issues make sense.
