### ISSUE TITLE
Can't download replays from song select leaderboard

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14960]
I tried downloading the first 2 score replays from the big black, it downloaded them fine in 2021.927.0 (tested but didn't get video) while it didn't on 2021.1005.0 (can't download replays from any map)

https://user-images.githubusercontent.com/53081750/136047209-b587f43a-09f5-4782-b5c7-6e70b3e1e27a.mp4

[runtime.log](https://github.com/ppy/osu/files/7286850/runtime.log)

**Comment by gagahpangeran** [comment]
The `ScoreModelDownloader` is null in

https://github.com/ppy/osu/blob/3e3b9bc963583fa5f6ad3b822ad3e6e3818aa06c/osu.Game/Screens/Ranking/ReplayDownloadButton.cs#L42-L43

Looks like it is not cached anywhere when split up in https://github.com/ppy/osu/pull/14900

**Comment by bdach** [comment]
I don't see any other places that download scores so the above looks to be theoretically sufficient.

I am however unsure whether it was the intention to continue using `ScoreManager` rather than to cache its downloader because #14900 switched away from it explicitly.

**Comment by peppy** [comment]
The eventual intention would be to cache and consume the interface, but I didn't do that for now to keep compatibility. This should be restored to `BeatmapManger` for the moment.
