### ISSUE TITLE
Beatmap editor doesn't save changes

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#14972]
https://user-images.githubusercontent.com/43358824/136114448-5cedb12c-36a2-45ae-b7b9-2ce9fcc3358d.mp4

**osu lazer version:** 2021.1006.0

**Comment by peppy** [comment]
@mouzedrift if you are going to blatantly bypass the issue creation page, then please **attach logs**.

**Comment by mouzedrift** [comment]
i haven't attached any logs because there were no logs related to this issue but if you want the logs regardless i can attach them in the future. (looks like you already fixed the issue on stream so didn't attach the logs in this reply)
