### ISSUE TITLE
Thousands separator character not displayed correctly in some locales

### ISSUE THREAD

**Issue by bdach** [ppy/osu#15135]
Unicode code point in question is `'NARROW NO-BREAK SPACE' (U+202F)`

I'm not even sure bmfont allows for exporting code points from that range. May require a framework-side bypass to make that alias with the space character.

### Discussed in https://github.com/ppy/osu/discussions/15133

<div type='discussions-op-text'>

<sup>Originally posted by **MicrophoneJunkie** October 16, 2021</sup>
I've had this problem for quite some time now, and I can't figure it out. Moreover, I didn't see anyone talking about it on Internet, so I'm posting it here.
![image](https://user-images.githubusercontent.com/88437729/137589419-950b5799-ad80-4cc3-9c85-0aa703731553.png)
(note that it's the same on the end screen of any map.) </div>

**Comment by peppy** [comment]
Aliasing to a more normal space sounds like a good solution.

**Comment by Corne2Plum3** [comment]
Still have this issue w/ the latest client at 2023/03/18

**Comment by MeuhMeuh62** [comment]
His ? is only on french language.
FR :
![image](https://github.com/ppy/osu/assets/86471514/d2515f4b-5fe2-420a-bc0e-0a8207ee5b04)
EN :
![image](https://github.com/ppy/osu/assets/86471514/3be0abc0-9e53-4ad1-b295-fea953009510)
And other in different languages.
It's probably a french font issue

**Comment by peppy** [comment]
Going to bump this up to p0. I've seen this often enough that we should just fix it in any hacky way possible to avoid the `?`s displaying.

**Comment by MeuhMeuh62** [comment]
Thank tou! Do your best!

**Comment by Susko3** [comment]
On a quick check with framework tests and Roboto font, `'NARROW NO-BREAK SPACE' (U+202F)` is supported by `bmfont1.14a` (if the font supports it). Notice the different spacing in between the `| |`.

![image](https://github.com/ppy/osu/assets/16479013/8d67c17b-ca35-49e7-9a67-2b61bc1193f0)

If Venera supports that character, it should be as simple as regenerating the font files with it selected. I couldn't find a TrueType version online, so I'm leaving that to someone else.

If that's not possible, then just overriding [`SpriteText.FallbackCharacter`](https://github.com/ppy/osu-framework/blob/1c67b75f805846e96959887e865f5db25c3ca044/osu.Framework/Graphics/Sprites/SpriteText.cs#L584) to be a space seems amicable.

**Comment by bdach** [comment]
This will be fixed with new framework & resources bumps.
