### ISSUE TITLE
Mouse input is handled incorrectly if extended desktop is used

### ISSUE THREAD

**Issue by UselessToucan** [ppy/osu#1515]
BRIEF:
If the game is launched in fullscreen mode on multidisplay PC configuration with extended desktop enabled, it does not handle mouse input correctly.

STEPS TO REPRODUCE:
1. Launch the game using single display and configure it to run in Fullscreen mode.
2. Configure your GPU output to something like "Extend"/"Extended desktop".
3. Launch the game again.
4. Perform mouse click.

EXPECTED RESULT:
Mouse input is handled as usual.

ACTUAL RESULT:
Mouse click is handled by different program. For example, by the windows explorer which is opened on your desktop. Mouse move and keyboard events looks ok.

ADDITIONAL INFO:
I used [this](https://github.com/ppy/osu/commit/f6bdfa987669067576a0154fc0303357cc468a0f) revision compiled in Release mode.
If you did not understand text explanation, [this video](https://youtu.be/mpDzWH0Sa6o) might help.

**Comment by bdach** [comment]
I can't seem to be able to reproduce this on 2019.1021.0; mind having a look if at all possible?

**Comment by UselessToucan** [comment]
Tried to reproduce on https://github.com/ppy/osu/commit/e93e9067a17962d3f03700fe2ae93b5087264ea8. The problem is gone.
Video: https://youtu.be/8RJTQN8XJfk
