### ISSUE TITLE
Reselecting finished song plays same map but with different soundtrack

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#1522]
If you successfully complete a map and come back to the song select you get greeted by silence.
Though if you select the same map again and play it you get the same beatmap but it plays a different sound track.
After somehow completing that song it shows the map details of the soundtrack and not of the one you just played.

Here is a [video](https://youtu.be/T9E3YaShC_I). I marked the times of the important things happening.
[1:36](https://youtu.be/T9E3YaShC_I?t=1m36s) song completed first time
[1:44](https://youtu.be/T9E3YaShC_I?t=1m44s) song selected again but different soundtrack appears
[3:08](https://youtu.be/T9E3YaShC_I?t=3m08s) song completed second time

This happened in version 2017.1116.0.

**Comment by Aergwyn** [comment]
I'm slowly digging into this.
So far I found that songs don't loop in the song select menu. They play once and then everything stays silent.
If you press play without manually changing the song (or the map in the selected set) after the current one ended `PlaylistOverlay.PlayNext()` triggers. This just selects the next song from the playlist which is of course a different one from what you actually wanted to play.

**Comment by Aergwyn** [comment]
I think I found a fix for this. Songs not looping actually caused the `PlaylistOverlay` to trigger `PlayNext()` when you want to play a map and the current track was at its end. Thus it loaded a different track while you were going into play.
With working looping I didn't encounter this anymore. 🤔
A PR will be coming Soon™.

**Comment by peppy** [comment]
Should be resolved by https://github.com/ppy/osu-framework/pull/1204
