### ISSUE TITLE
Is it possible to run osu on an ARM processor?

### ISSUE THREAD

**Issue by LinuxGamer** [ppy/osu#1528]
I know that here is no place for questions but is it possible to run the osu on an ARM processor? https://i.imgur.com/ofLKcpO.jpg

**Comment by jorolf** [comment]
If you're trying to get osu to work on a smartphone then wait until android is supported

**Comment by LinuxGamer** [comment]
I'm trying to run osu-stablr on Android with Wine, but it's not working

**Comment by jorolf** [comment]
oh.
This repository is for osu!lazer and not stable.

**Comment by LinuxGamer** [comment]
ik, but i tried osu!lazer too
and doesn't work

**Comment by peppy** [comment]
this isn't going to work unless you know what you're doing.

**Comment by LovelyA72** [comment]
have you ever heard about mono on raspberry pi?

**Comment by peppy** [comment]
If you're actually interested in helping getting this running, please check the `netstandard` branches using a target runtime of Xamarin.iOS
