### ISSUE TITLE
Checkboxes in settings menu

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#153]
![test](https://cloud.githubusercontent.com/assets/22874522/20128008/da6f1490-a655-11e6-949d-16ca8271bba8.gif)
Checkboxes are moving after checking.

**Comment by RemieRichards** [comment]
It's an issue I've actually did myself when initially creating the textboxes.
@SirCmpwn has put ```base.OnChecked()``` in both ```OnChecked()``` AND ```OnUnchecked()```
https://github.com/ppy/osu/blob/d6dafd6b7039065c1bcb21593e25578dfc62e9b7/osu.Game/Overlays/Options/CheckBoxOption.cs#L51

Easy fix.

**Comment by peppy** [comment]
Thanks for finding such an easy issue 👍 .

Consider PRing it next time.
