### ISSUE TITLE
notice bug

### ISSUE THREAD

**Issue by Kinzvier** [ppy/osu#1536]
after a song is finish or a map is played, then same map is played the song won't play but the map start up.
Also I notice the approach circle is hard to see(Cannot make the right timing to hit the circle).
- that's all i notice! hope Osu! Lazer soon to be publish :)

**Comment by Kinzvier** [comment]
Addition, the setting menu is not auto hiding when clicked outside of it like when click on the map or click the logo(osu), it stay there until i press "esc" or click back, also it stay on screen even when map is already loading.

**Comment by peppy** [comment]
You bring up valid points, but:

- Please file issues with appropriate titles.
- Please file one issue per issue.
