### ISSUE TITLE
Currently downloading beatmap notification doesn't show the beatmap set info

### ISSUE THREAD

**Issue by bdach** [ppy/osu#15421]
### Discussed in https://github.com/ppy/osu/discussions/15419

<div type='discussions-op-text'>

<sup>Originally posted by **Sinamer** November  2, 2021</sup>
As in the title:
![image](https://user-images.githubusercontent.com/53346335/139915133-d3905e39-28ca-4b9a-963c-f58da3c8d342.png)
</div>

**Comment by Sinamer** [comment]
This has surfaced again in 2021.1108.0-lazer osu! release:
![image](https://user-images.githubusercontent.com/53346335/140769062-67f07fdd-9ad8-40d4-af68-086b2ae0051d.png)
