### ISSUE TITLE
Taiko scroll speed increases after saving the beatmap in editor without any changes made

### ISSUE THREAD

**Issue by bdach** [ppy/osu#15435]
The taiko-local 1.4x multiplier to scroll speed strikes again! Somehow stacks by 1.4x time on every save & reenter of editor. `TaikoMultiplierAppliedDifficulty.CopyTo()` is never called but `CopyFrom()` is, meaning that the 1.4x adjustments stack every time the beatmap is read back from the legacy format.

### Discussed in https://github.com/ppy/osu/discussions/15424

<div type='discussions-op-text'>

<sup>Originally posted by **gagahpangeran** November  2, 2021</sup>
Reproduce in latest release:

**Original**

https://user-images.githubusercontent.com/4964985/139917396-30e3ebd4-5e2b-4880-8439-f25eed96b068.mp4

**After edit several times**

https://user-images.githubusercontent.com/4964985/139917425-028657bc-7f24-4116-bebe-a5a0c769410b.mp4

**Full repro step**

https://user-images.githubusercontent.com/4964985/139917495-a308f227-020e-4a64-a4b5-877a7f0e29f9.mp4
</div>

**Comment by peppy** [comment]
Going to mark as priority zero, but I'm also planning to do a hotfix release today which this may not make it into. Not sure how simple this is going to be to fix (and also not sure how this regressed when we tested this multiple times).
