### ISSUE TITLE
Multiplayer currently playing map name breaks line too soon

### ISSUE THREAD

**Issue by peppy** [ppy/osu#15451]
### Discussed in https://github.com/ppy/osu/discussions/15449

<div type='discussions-op-text'>

<sup>Originally posted by **Gabixel** November  3, 2021</sup>
This is not intended, isn't it?

![image](https://user-images.githubusercontent.com/43073074/140057416-4535ace5-f74b-4d96-ba5a-931b2a93f90e.png)

![image](https://user-images.githubusercontent.com/43073074/140057548-ca7218dc-c36b-4434-86bc-78806dcea6ac.png)
</div>

**Comment by bdach** [comment]
so, as stated on discord, with a quick fix i can offer either working truncation with ellipsis but wrong clickable area:

| drawable room | drawable playlist item |
| :-: | :-: |
| ![2021-11-03-174647_1913x727_scrot](https://user-images.githubusercontent.com/20418176/140105365-0b72fa2e-76f1-4b1d-9a0c-68044535c9c8.png) | ![2021-11-03-174634_686x431_scrot](https://user-images.githubusercontent.com/20418176/140105378-3d570e2b-6731-4ea1-8e48-00c5ac119627.png) |

or truncation with no ellipsis but correct clickable area:

| drawable room | drawable playlist item |
| :-: | :-: |
| ![2021-11-03-173951_1906x730_scrot](https://user-images.githubusercontent.com/20418176/140105501-c8269da8-ce43-4d4a-89a6-b86a504a51f7.png) | ![2021-11-03-174006_711x467_scrot](https://user-images.githubusercontent.com/20418176/140105523-85691628-3e1c-4f82-8047-cfb203e9da79.png) |

any preferences as to which one it should be?

**Comment by peppy** [comment]
I think I'd have to go with the one that's less anti-user (correct clickable area). But there needs to be an inline TODO mentioning ellipsis is eventually required.
