### ISSUE TITLE
Multiple visual regressions after enabling buffered container framebuffer clipping by default

### ISSUE THREAD

**Issue by bdach** [ppy/osu#15475]
Opening as issue as I'm unsure on how to proceed.

Found at least three:

| multiplayer lounge | now playing overlay | mania default skin (doesn't look too broken, but is too flat) |
| :-: | :-: | :-: |
| ![osu_2021-11-04_20-22-57](https://user-images.githubusercontent.com/20418176/140406652-753abff8-7ff9-4f8f-b058-5d07972665f3.jpg) | ![osu_2021-11-04_20-23-05](https://user-images.githubusercontent.com/20418176/140406659-fc32a3fb-71aa-465d-9d75-1010ec61ab48.jpg) | ![osu_2021-11-04_20-23-34](https://user-images.githubusercontent.com/20418176/140406661-2db36b46-2c19-48f2-84ea-6adc0a1c3381.jpg) |

Root case in all three usages is the same: it is combining the clipping option with `CacheDrawnFrameBuffer`. Using both in conjunction makes it so that the framebuffer is only ever clipped once, so if i.e. the buffered container is only partially visible when entering the screen, the cached framebuffer will have that initial too-small clipped size forevermore. In all above usages the buffered container sweeps/moves into the screen bounds and the framebuffer is clipped and cached too early.

Two fixes seem obvious - either reverting the clipping on-by-default and then adding clipping back to slider paths to fix the aspire breakage, or applying game-local `clipToRootNode: false` specs to all places that specify `CacheDrawnFrameBuffer` and look broken.

**Comment by khang06** [comment]
personally i think it should be disabled by default. it's an optimization that only really impacts one niche use case and i don't think performing that optimization by default would be what someone would expect from using the affected classes

**Comment by bdach** [comment]
The bigger issue is that the combination of `clipToRootNode = true` and `CacheDrawnFrameBuffer = true` is a footgun and maybe the two should be mutually exclusive at a framework level.

**Comment by peppy** [comment]
Starting to think the setting should not be exposed, but hard-coupled with `CacheDrawnFrameBuffer` instead. I can't immediately think of a case where clipping when not caching would be visible in any way, and the chance of someone using caching but also wanting to clip to the screen bounds seems quite low.

Will wait for further opinions on the matter.

**Comment by smoogipoo** [comment]
The consideration for mania is that it's possible to have one gigantic hold note exceeding GPU texture size limits. That being said, perhaps there is a better way to do mania such as wrapping textures.

In general I think I 80% agree with making them exclusive.

**Comment by peppy** [comment]
Yeah I get that. Saying that the solution there is likely to turn off caching and use the new clipping bounds.

**Comment by smoogipoo** [comment]
Depends on how bad the performance is. As you've mentioned, it's two nested buffered containers.
