### ISSUE TITLE
Broken sound at the start of songs

### ISSUE THREAD

**Issue by Gunnest663** [ppy/osu#1550]
The sound on any beatmap at the start is always broken and fixes after 10 seconds which already i have lost my beat and missed some circles. Is that an issue with my computer or the game?

**Comment by peppy** [comment]
you have to provide details

video? audio? anything really?

**Comment by Gunnest663** [comment]
https://www.youtube.com/watch?v=ub_3V_Hh3W4

Do you mean a recorded video like that? that sound just bothers me and happens whenever it wants

**Comment by peppy** [comment]
I can reproduce this on one of my testing setups. Thanks for the video, we'll look into it.

Looks like the audio is getting started/stopped very rapidly.

**Comment by peppy** [comment]
@Gunnest663 if you are able to build from source, could you please try against the latest osu/framework master? I can't seem to reproduce any more.

**Comment by Gunnest663** [comment]
Didn't see this before but i have tried the newest version but it does the same issue sometimes

**Comment by peppy** [comment]
just to confirm, you built from source?

**Comment by peppy** [comment]
Has been resolved by https://github.com/ppy/osu/pull/1717 and https://github.com/ppy/osu-framework/pull/1275.
