### ISSUE TITLE
UserRatings Metrics assumes beatmap has both positive and negative ratings

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#1552]
<img width="807" alt="screen shot 2017-11-21 at 7 03 21 pm" src="https://user-images.githubusercontent.com/1329837/33066496-c7d53f90-ceee-11e7-80e0-3df98423c15a.png">

Throws out of range exception for positive ratings.

**Comment by FreezyLemon** [comment]
I think this is just a general error in this usage of the `GetRange` method.
If you use an even number in the line starting with `positiveRatings.Text = ...` you will always try to access an array element that is out of bounds. Take for example ratings.Count == 100 and ratings.Count == 101.

`GetRange(ratings.Count / 2 + 1, ratings.Count / 2)` will evaluate to 
`GetRange(51, 50)` in both cases (int casting on the left side will make 101 / 2 = 50, 50 + 1 = 51).

This will start at array index 51 and take 50 elements, ending at array index 100. There you go, out of bounds error for all even numbers. Fixing this just on the numbers side of things isn't too hard. but I'd rather have someone do this that knows what is supposed to happen here.
