### ISSUE TITLE
UR Counter isn't updated until HUD is shown

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#15568]
### Discussed in https://github.com/ppy/osu/discussions/15560

<div type='discussions-op-text'>

<sup>Originally posted by **Sinamer** November 11, 2021</sup>
UR Counter will not update its value if HUD was hidden from the beginning of a beatmap, and once the HUD is shown, it displays `0ur` until the next hitobject is hit:
![osu_2021-11-10_20-43-13](https://user-images.githubusercontent.com/53346335/141175353-ae70f539-b93b-4875-bd18-460a03f859a5.png)

</div>

**Comment by bdach** [comment]
Fixed by #15576 (linked discussion instead of issue by accident).
