### ISSUE TITLE
Display a breakdown of the user's PP in the results screen

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#15570]
### Discussed in https://github.com/ppy/osu/discussions/15566

<div type='discussions-op-text'>

<sup>Originally posted by **developomp** November 11, 2021</sup>
Show breakdown of pp (aim, speed, accuracy, etc.) in the result screen.
</div>

**Comment by Henry-YSLin** [comment]
I would like to try implementing this. How about a tooltip on the "PP" statistic item?

**Comment by mk56-spn** [comment]
> I would like to try implementing this. How about a tooltip on the "PP" statistic item?

do you have sort of like an idea of what the visuals will be like for such a feature?

i think a spider web chart or bar chart would be the ideal presentation for this, text alone would lack the quick digestibility

**Comment by Henry-YSLin** [comment]
Spider web charts won't work for taiko and mania because they only have 2 pp attributes (accuracy and difficulty)

Bar charts might work, but we need to figure out a maximum value to scale the attributes to. Using total pp as maximum won't work because it is affected by multipliers and may be smaller than attribute values.

**Comment by mk56-spn** [comment]
> Spider web charts won't work for taiko and mania because they only have 2 pp attributes (accuracy and difficulty)
> 
> Bar charts might work, but we need to figure out a maximum value to scale the attributes to. Using total pp as maximum won't work because it is affected by multipliers and may be smaller than attribute values.

yeah  good point about mania and taiko,

why wouldnt the sum of the bars being the total pp not work? 

simply scale the pp bar size down to a fixed size so they dont change in total size among different total pp values no?

**Comment by Henry-YSLin** [comment]
By "total pp" I meant the final value you see in the results screen.

But yeah a simple sum should work. Lemme work on it a bit and see
