### ISSUE TITLE
osu! Crashing after goint to Online Profiles (Build In)

### ISSUE THREAD

**Issue by WhiteRedWolf** [ppy/osu#1558]
osu!lazer Crashes after i log In and want to see My Profile Details in the Game By Clicking on My Profile (Which is Banned for the Time Being) And it just Crashes.

Log:
Aplikacja: osu!.exe
Wersja architektury: v4.0.30319
Opis: proces został przerwany z powodu nieobsłużonego wyjątku.
Informacje o wyjątku: System.NullReferenceException
   w osu.Game.Overlays.Profile.Sections.Ranks.PaginatedScoreContainer.<ShowMore>b__3_0(System.Collections.Generic.List`1<osu.Game.Online.API.Requests.OnlineScore>)
   w osu.Framework.Threading.Scheduler.Update()
   w osu.Game.OsuGameBase.Update()
   w osu.Framework.Graphics.Drawable.UpdateSubTree()
   w osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   w osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   w osu.Framework.Platform.GameHost.UpdateFrame()
   w osu.Framework.Threading.GameThread.ProcessFrame()
   w osu.Framework.Threading.GameThread.runWork()
   w System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   w System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   w System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   w System.Threading.ThreadHelper.ThreadStart()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w osu.Framework.Threading.Scheduler.Update()
   w osu.Framework.Threading.GameThread.ProcessFrame()
   w osu.Framework.Platform.GameHost.<Run>b__90_1(System.Object, OpenTK.FrameEventArgs)
   w System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   w OpenTK.GameWindow.RaiseUpdateFrame(Double, Double ByRef)
   w OpenTK.GameWindow.DispatchUpdateAndRenderFrame(System.Object, System.EventArgs)
   w OpenTK.GameWindow.Run(Double, Double)
   w osu.Framework.Platform.GameHost.Run(osu.Framework.Game)
   w osu.Desktop.Program.Main(System.String[])

Log 2:

Nazwa aplikacji powodującej błąd: osu!.exe, wersja: 2017.1120.0.0, sygnatura czasowa: 0x5a12e59c
Nazwa modułu powodującego błąd: KERNELBASE.dll, wersja: 10.0.15063.726, sygnatura czasowa: 0x1a9bbe0b
Kod wyjątku: 0xe0434352
Przesunięcie błędu: 0x0000000000069d98
Identyfikator procesu powodującego błąd: 0x21e8
Godzina uruchomienia aplikacji powodującej błąd: 0x01d362e80ef8cd3d
Ścieżka aplikacji powodującej błąd: C:\Users\arkad\AppData\Local\osulazer\app-2017.1120.0\osu!.exe
Ścieżka modułu powodującego błąd: C:\WINDOWS\System32\KERNELBASE.dll
Identyfikator raportu: 21f87288-1387-4abd-b085-15ffc1f3f2c8
Pełna nazwa pakietu powodującego błąd: 
Identyfikator aplikacji względem pakietu powodującego błąd: 

Sorry for Providing only Polish Logs... owo

Log 3:
Nazwa aplikacji powodującej błąd: osu!.exe, wersja: 2017.1120.0.0, sygnatura czasowa: 0x5a12e59c
Nazwa modułu powodującego błąd: unknown, wersja: 0.0.0.0, sygnatura czasowa: 0x00000000
Kod wyjątku: 0xc0000005
Przesunięcie błędu: 0x00007ffbe43e0d4d
Identyfikator procesu powodującego błąd: 0x21e8
Godzina uruchomienia aplikacji powodującej błąd: 0x01d362e80ef8cd3d
Ścieżka aplikacji powodującej błąd: C:\Users\arkad\AppData\Local\osulazer\app-2017.1120.0\osu!.exe
Ścieżka modułu powodującego błąd: unknown
Identyfikator raportu: ea8a370c-f8d7-490b-a4cc-028300a71a21
Pełna nazwa pakietu powodującego błąd: 
Identyfikator aplikacji względem pakietu powodującego błąd:

**Comment by peppy** [comment]
This has already been fixed via framework PR https://github.com/ppy/osu-framework/pull/1175 . Please make sure you are running the latest master before reporting issues.
