### ISSUE TITLE
UI sounds while lazer is in background

### ISSUE THREAD

**Issue by Iodid** [ppy/osu#1560]
While interacting with other windows infront of lazer still plays the sounds of hovering over/highlighting menu options.

Although it's not a pressing issue, it would be nice if you had the option to disable UI interaction sounds or even all sounds if lazer is in the background.

**Comment by jorolf** [comment]
this has already been fixed by https://github.com/ppy/osu-framework/pull/1174

**Comment by jorolf** [comment]
as in: drawables aren't hovered anymore when a window is in front of them which result in them not playing their sound
