### ISSUE TITLE
Hitokori Problem

### ISSUE THREAD

**Issue by Subjecter** [ppy/osu#15656]
I have recently downloaded Hitokori, But as of now having it downloaded,
Any and all maps that I have newly downloaded are all 0 star and apparently have no BM information

~ Whilst
Other mods are working 100% fine as they're made to

I'm very sad as this game mode is very fun

+ I had already deleted lazer and all the custom modes from the osu! folder ( Located in roaming ) not appdata
Reinstalled it
And the same thing happend... Idk what to do...

**Comment by peppy** [comment]
You will need to open this issue on the relevant ruleset's repository, not here.

**Comment by Coppertine** [comment]
I think he knows of this issue, but will get Bloom to make it set to std rating.

Currently, it's hard to create ruleset spesific difficulties with correct calculations....
also, wrong repo.. try LumpBloom7 / sentakki

**Comment by Subjecter** [comment]
> You will need to open this issue on the relevant ruleset's repository, not here.


sorry this is my first time here I'm not sure where to open this at

**Comment by TheRealStevie** [comment]
https://github.com/Flutterish/Hitokori/issues

**Comment by Coppertine** [comment]
already fixed in latest release
