### ISSUE TITLE
Beatmap sometimes shows 0* temporarily after being selected

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#15699]
Sometimes, when a beatmap is selected (i.e. during the transition to entering gameplay) the SR is temporarily modified to 0*. The beatmap wedge pill will animate towards 0, and the `PlayerLoader` pill will likewise show 0*.

I'm not sure what triggers this - it doesn't seem to always happen (even on the same beatmaps). I've had it come and go after reselection / mod selection / mod customisation.

Another report found here: https://github.com/ppy/osu/discussions/15694

**Comment by smoogipoo** [comment]
I've managed to get it stuck at 0 for a particular DT rate (and it's not diffcalc's problem).

**Comment by bdach** [comment]
This is a regression from the cancellation token changes, additionally exacerbated by a few `BeatmapDifficultyCache` errors.
