### ISSUE TITLE
Scores not saving if hitting "back" binding during transition to results screen

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#15726]
I've had this one happen to me also. It's pretty minor for the time being (hence P3) but I think it'll become a bigger issue as people care/start to care more about their scores on lazer.

### Discussed in https://github.com/ppy/osu/discussions/15706

<div type='discussions-op-text'>

<sup>Originally posted by **RadekMojzis** November 21, 2021</sup>
Right now a lot of people in standard instantly press escape after finishing the map to instantly jump to score screen immediately. 

If you do this in laser it takes you straigth to song select (so the game forgets things like UR and hit distribution) which is quite frustrating because of my muscle memory from stable
</div>

**Comment by peppy** [comment]
I’ve checked the code for this and it definitely was a conscious decision to implement with the current behaviour.

The correct fix should be to ensure the score saves (if not happening already as the discussion claims, have not confirmed), not that the results screen is displayed, I think. A “back” binding probably shouldn’t go forwards.

Users will break the habit eventually.

**Comment by peppy** [comment]
Changed the scope of this slightly to cover the more serious part of the issue described. The remaining portion requires a bit more discussion around how the flow should work, at a later date.

**Comment by bdach** [comment]
Not sure whether I messed something up, but I wrote a test and I think that scores will already import already even if the player is exited between gameplay completion and results screen being displayed. I wrote the following:

```diff
diff --git a/osu.Game.Tests/Visual/Gameplay/TestScenePlayerScoreSubmission.cs b/osu.Game.Tests/Visual/Gameplay/TestScenePlayerScoreSubmission.cs
index 324a132120..617a0fd045 100644
--- a/osu.Game.Tests/Visual/Gameplay/TestScenePlayerScoreSubmission.cs
+++ b/osu.Game.Tests/Visual/Gameplay/TestScenePlayerScoreSubmission.cs
@@ -3,6 +3,7 @@
 
 using System;
 using System.Linq;
+using System.Threading;
 using System.Threading.Tasks;
 using NUnit.Framework;
 using osu.Framework.Screens;
@@ -38,6 +39,8 @@ public class TestScenePlayerScoreSubmission : PlayerTestScene
 
         protected override TestPlayer CreatePlayer(Ruleset ruleset) => new NonImportingPlayer(false);
 
+        protected new NonImportingPlayer Player => (NonImportingPlayer)base.Player;
+
         protected override Ruleset CreatePlayerRuleset() => createCustomRuleset?.Invoke() ?? new OsuRuleset();
 
         protected override IBeatmap CreateBeatmap(RulesetInfo ruleset) => createCustomBeatmap?.Invoke(ruleset) ?? createTestBeatmap(ruleset);
@@ -207,6 +210,25 @@ public void TestSubmissionOnExit()
             AddAssert("ensure failing submission", () => Player.SubmittedScore?.ScoreInfo.Passed == false);
         }
 
+        [Test]
+        public void TestSubmissionOnExitDuringImport()
+        {
+            prepareTokenResponse(true);
+
+            createPlayerTest();
+            AddStep("block imports", () => Player.AllowImportCompletion.Wait());
+
+            AddUntilStep("wait for token request", () => Player.TokenCreationRequested);
+
+            addFakeHit();
+
+            AddUntilStep("wait for import to start", () => Player.ScorePreparationStarted);
+
+            AddStep("exit", () => Player.Exit());
+            AddStep("allow import to proceed", () => Player.AllowImportCompletion.Release(1));
+            AddAssert("ensure submission", () => Player.SubmittedScore != null && Player.ImportedScore != null);
+        }
+
         [Test]
         public void TestNoSubmissionOnLocalBeatmap()
         {
@@ -288,15 +310,28 @@ private void addFakeHit()
             });
         }
 
-        private class NonImportingPlayer : TestPlayer
+        protected class NonImportingPlayer : TestPlayer
         {
+            public bool ScorePreparationStarted { get; set; }
+            public SemaphoreSlim AllowImportCompletion { get; }
+            public Score ImportedScore { get; private set; }
+
             public NonImportingPlayer(bool allowPause = true, bool showResults = true, bool pauseOnFocusLost = false)
                 : base(allowPause, showResults, pauseOnFocusLost)
             {
+                AllowImportCompletion = new SemaphoreSlim(1);
+            }
+
+            protected override async Task PrepareScoreForResultsAsync(Score score)
+            {
+                ScorePreparationStarted = true;
+                await AllowImportCompletion.WaitAsync();
             }
 
             protected override Task ImportScore(Score score)
             {
+                ImportedScore = score;
+
                 // It was discovered that Score members could sometimes be half-populated.
                 // In particular, the RulesetID property could be set to 0 even on non-osu! maps.
                 // We want to test that the state of that property is consistent in this test.
```

and it seems to pass just fine.

**Comment by peppy** [comment]
Want to PR that test? I think it'd be good to have regardless of the outcome of this issue.

@smoogipoo can you try and reproduce this again and see if there's anything specific that's being overlooked in the test above?

**Comment by smoogipoo** [comment]
I hadn't reproduced the "score not saving" issue. The scope of this issue was changed, but it was initially only relating to the score not being shown if escape was pressed too soon after completion.

**Comment by peppy** [comment]
Bit of a mess. Let's close this issue and open another tracking the remaining UX change if you feel strongly about it (probably a P2 or P3).``
