### ISSUE TITLE
Get iOS testflight builds happening again

### ISSUE THREAD

**Issue by peppy** [ppy/osu#15742]
All the pieces should roughly be in place for this to happen. Needs updating to the build server's toolchain, certificates and whatever else is broken.

**Comment by DaRealGitHubDoriitos** [comment]
is it released yet?

**Comment by bdach** [comment]
no. and it will not be until this issue is closed.

**Comment by peppy** [comment]
Figured out all the remaining issues, so going to close this. The next release should see a new iOS build alongside it.
