### ISSUE TITLE
Beatmap broken after download

### ISSUE THREAD

**Issue by memesnightmares** [ppy/osu#15750]
I'm on the latest version of lazer, and I just downloaded [this map](https://osu.ppy.sh/beatmapsets/1519259#/3163675) via in game osu direct. As shown in the screenshot, one diff has no star rating. It is playable and plays normally. Initially after the download, it showed as light grey, and then transitioned to purple after I played it (and then quit out). All the hitobjects inside are normal. There is nothing notable in the logs.

![2021-11-22_17-27](https://user-images.githubusercontent.com/55752957/142950252-288699cc-ddd1-4f9b-9a88-9b75263812dc.png)

**Comment by mk56-spn** [comment]
I'll add that I don't think this has anything to do with newly imported beatmaps I've had it happen to me today on beatmaps I've had quite a while

**Comment by memesnightmares** [comment]
I'm dumb #15699
