### ISSUE TITLE
Cannot choose more than 1 Map per Multiplayer lobby

### ISSUE THREAD

**Issue by Ekital** [ppy/osu#15809]
Not sure if it's a client related issue however since today (It was working yesterday on the newest patch without any problems) players on Lazer are no longer able to play more than 1 map per lobby without receiving a "Attempted to select an expired playlist item." Error message. It seems to treat every multiplayer lobby as a playlist instead of a regular lobby.

**Comment by peppy** [comment]
Sounds like a regression from osu-web deployment, very unfortunate.

**Comment by peppy** [comment]
Has been resolved via a temporary rollback of osu-web.
