### ISSUE TITLE
Audio previews potentially crashing game

### ISSUE THREAD

**Issue by peppy** [ppy/osu#15818]
May require framework attention.

Probably also need to look into the missing `IPreviewTrackOwner`, unless there's actual intentional cases where that is not supposed to be found.

### Discussed in https://github.com/ppy/osu/discussions/15816

<div type='discussions-op-text'>

<sup>Originally posted by **mouzedrift** November 26, 2021</sup>
when running the game in single thread mode and you preview multiple audios in quick succession the game can crash.

possibly the same or similar issue to #14313?

https://user-images.githubusercontent.com/43358824/143555792-6f840cfc-762a-4493-a53b-ffad17c6c9b7.mp4

version: c7f905f8dac24d19fb9e2b190ca6ea1600daa4a2

logs:
[performance.log](https://github.com/ppy/osu/files/7607527/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/7607528/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/7607530/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/7607531/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/7607532/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/7607533/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7607534/updater.log)
[database.log](https://github.com/ppy/osu/files/7607535/database.log)
[network.log](https://github.com/ppy/osu/files/7607536/network.log)
 </div>

**Comment by bdach** [comment]
upon comparing both implementations of preview buttons looks like i dropped a schedule of `onPreviewLoaded` when copying across.

not sure about the missing track owner, though. that should be cached at overlay level.

**Comment by peppy** [comment]
Going to drop this here:

![20211126 215013 (JetBrains Rider-EAP)](https://user-images.githubusercontent.com/191335/143583686-443e2678-d7fc-43bc-adb8-456e801f6d79.png)

Still not 100% on the correct fix, but that should show all that is required to understand the context.

**Comment by bdach** [comment]
from the paper trail at #14313 it appears to be the exact same issue and the fix should amount to scheduling the body of `onPreviewLoaded` as mentioned above. i'll handle this at the nearest available opportunity.
