### ISSUE TITLE
Joining multiplayer rooms with multiple queue items is slow

### ISSUE THREAD

**Issue by peppy** [ppy/osu#15829]
Looks to not join until sequential calls to `beatmapsets/lookup` complete for every item in the room.

**Comment by bdach** [comment]
Definitely sounds bad, but I'm not super sure what the fix is there either. Should the items be allowed to load one by one, starting from the current item backwards? Or should there be a web endpoint for multiple lookups at once?

**Comment by peppy** [comment]
They should load as they come on screen, I think.

**Comment by bdach** [comment]
So I've spend a bit on trying to make async load work and I'm not sure it's viable. The thing is that the playlist item fetch is wedged quite deep in the multiplayer client and many things look to depend on it being synchronously populated.

I had limited "success" with the following branch: https://github.com/ppy/osu/compare/master...bdach:multiplayer-delayed-playlist-load-broken?expand=1 - while the happy path seems to mostly behave, it quickly broke down under me trying to stress the robustness of that solution against delayed loads/races:

![2021-11-27-141406_2556x1034_scrot](https://user-images.githubusercontent.com/20418176/143683019-430b700f-5efd-4b31-9c0d-73c51e01b698.png)

(note the completely different: current map display on the top, difficulty rating spread display, and the playlist itself).

**Comment by peppy** [comment]
Temporarily assigning this one as I'm going to give it a shot (building off @bdach's existing work towards it).

**Comment by peppy** [comment]
> So I've spent a bit on trying to make async load work and I'm not sure it's viable. The thing is that the playlist item fetch is wedged quite deep in the multiplayer client and many things look to depend on it being synchronously populated.

While your approach here might alleviate the immediate delay, it's still potentially going to result in thousands of API requests being queued up on joining a room, which are hanging and never cancelled even after leaving the room, and will hold up all other game-wide operations. Maybe one step better than what we have, but also not really solving the full problem.

I still think that population should only happen when the drawable panels come on screen. Will see if I can make that happen. I can understand how this is a struggle with the way multiplayer is structured client-side. It's very very very complex. And these items are used anywhere and everywhere.
