### ISSUE TITLE
Music playback doesn't pause while playing beatmap preview with osu!direct

### ISSUE THREAD

**Issue by Iodid** [ppy/osu#1585]
When you preview a beatmap with osu!direct the currently playing music doesn't pause and both tracks play simultaniously.

**Comment by FreezyLemon** [comment]
For anyone wanting to do this:
The previewed song is started from `osu.Game\Overlays\Direct\PlayButton.cs` and the `Start()` method is called on a`TrackBass` instance. Currently, every `TrackBass` instance creates its own audio stream and can't access any other instance's audio stream (as in pause/stop/resume the audio).

Might need a way to pause all current audio from the global `TrackManager`, which contains the song that is currently played from the toolbar at the top, or at least _only_ the song from the toolbar.

**Comment by Aergwyn** [comment]
Shouldn't it be enough to stop the MusicController for a bit? All other sounds from moving over buttons etc shouldn't be affected. Or did I interpret "all" tracks wrong?

**Comment by FreezyLemon** [comment]
Uhm yes, I meant all tracks as in all Songs, not hover samples or anything like that.

**Comment by peppy** [comment]
sounds fine, but the interaction needs to be done in a solid way. ie. if we are in play mode it should still work as expected.

**Comment by Aergwyn** [comment]
I'm going to look into this if no one stops me.
