### ISSUE TITLE
taiko-slider should be hidden when using cinema mod

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#15869]
### Discussed in https://github.com/ppy/osu/discussions/15866

<div type='discussions-op-text'>

<sup>Originally posted by **Joppe27** November 30, 2021</sup>
The goal of the cinema mod is being able to watch the video that comes with a beatmap. The taiko-slider and taiko-slider-fail elements should probably be hidden (stable behavior) as they cover up the video which defeats the point of the cinema mod: 
![osu_2021-11-29_22-07-56](https://user-images.githubusercontent.com/56885706/143953354-55b904f0-e489-45d9-ba06-8e0f276e873a.jpg)
This was probably overlooked/forgotten because the osu!lazer default skin doesn't use this element anymore.</div>

Prio-3 because I don't think cinema mod is used enough that this needs a timely fix.

**Comment by Joppe27** [comment]
Sorry, I forgot to say that the taiko-slider element should also be hidden when a storyboard is playing in taiko mode, because half of it is cut off now. Maybe this can be done in the same fix?

**Comment by peppy** [comment]
Please do that separately
