### ISSUE TITLE
Borderless Mode issue

### ISSUE THREAD

**Issue by Kinzvier** [ppy/osu#1586]
when playing using borderless it makes the response of the cursor delay...

**Comment by peppy** [comment]
This is intended behaviour. It should be the same on osu-stable. Borderless runs as a window, which is not exclusive fullscreen and doesn't bypass the window buffer frame latency.

**Comment by Kinzvier** [comment]
but in the current Osu!... i play with window mode or sometimes borederless so that i can increase the input latency, also i can get a better view when window mode.
