### ISSUE TITLE
Fullscreen mode when alt tab

### ISSUE THREAD

**Issue by Kinzvier** [ppy/osu#1587]
when fullscreen then alt tab, the display color change or it makes all the color random.

**Comment by peppy** [comment]
Possibly related to #1388

**Comment by peppy** [comment]
Please provide a screenshot or video of what you are seeing.

**Comment by Kinzvier** [comment]
yes, it seems to be related to #1338 
here's the video file.
[http://www.mediafire.com/file/dazh03vimmoifq0/WP_20171126_00_44_29_Pro.mp4](url)

**Comment by peppy** [comment]
Merging with #1388
