### ISSUE TITLE
Playing in multiplayer doesn't submit scores

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#15888]
### Discussed in https://github.com/ppy/osu/discussions/15887

<div type='discussions-op-text'>

<sup>Originally posted by **respektive** December  1, 2021</sup>
When in a multi room, after playing a map the stats on your profile, like playcount, don't update, like they do on solo play.

logs:
[performance.log](https://github.com/ppy/osu/files/7632733/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/7632735/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/7632736/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/7632737/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/7632738/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/7632739/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7632740/updater.log)
[database.log](https://github.com/ppy/osu/files/7632741/database.log)
[network.log](https://github.com/ppy/osu/files/7632748/network.log)

</div>

**Comment by smoogipoo** [comment]
This is going to be an osu-web + osu-queue-score-statistics issue. We don't currently have a multiplayer score redis queue for the former to push to, and the latter only handles solo scores for now.

**Comment by peppy** [comment]
I think the path forward is sending solo scores in the multiplayer case too, not creating a new flow for it.

**Comment by smoogipoo** [comment]
True. I would think that should be handled server-side?

**Comment by respektive** [comment]
I noticed that the same applies to playlists. Should that be tracked in separate issue?

**Comment by smoogipoo** [comment]
No, it's the same issue.

**Comment by bdach** [comment]
Believe this one is fixed now.
