### ISSUE TITLE
Fail to get map data in tournament mode

### ISSUE THREAD

**Issue by itsmehoaq** [ppy/osu#15912]
In tournament mode, map cards are empty (shown in the screenshot linked below). Upon checking the `bracket.json` file, it appeared that the request to get map data all failed.
[Screenshot](https://cdn.discordapp.com/attachments/899952602077347881/916216350320521256/unknown.png)

Log files:
[database.log](https://github.com/ppy/osu/files/7647272/database.log)
[updater.log](https://github.com/ppy/osu/files/7647273/updater.log)
[network.log](https://github.com/ppy/osu/files/7647274/network.log)
[performance.log](https://github.com/ppy/osu/files/7647276/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7647277/runtime.log)

**Comment by peppy** [comment]
Please open a discussion instead of an issue in the future.

**Comment by zachmanthethird** [comment]
Forcefully removed "BeatmapInfo" from each map in one round of my bracket.json, and this is what it built in its stead: [bracket.json.txt](https://github.com/ppy/osu/files/7647371/bracket.json.txt)

**Comment by itsmehoaq** [comment]
It doesn't look to different from the normal file anyway, if I'm not wrong, as all the map data are still missing. 
This is what I currently have: [bracket.json.txt](https://github.com/ppy/osu/files/7647488/bracket.json.txt)

**Comment by peppy** [comment]
This is looking to be an osu-web end issue, @nanaya is handling it.
