### ISSUE TITLE
User profile covers aren't masked/resized correctly at wide aspect ratios

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1592]
![image](https://user-images.githubusercontent.com/191335/33237021-7d1ad5ea-d2aa-11e7-996f-d7a4fc3286b1.png)

**Comment by PoULkY** [comment]
I found that by changing `width` to 1 in `UserProfileOverlay()` solve the problem

![image](https://user-images.githubusercontent.com/15938103/33239928-7d7cbc9e-d2df-11e7-9033-1ef227177a13.png)

But for profile background cover, i'm still not found why it out from dim sections

![3](https://user-images.githubusercontent.com/15938103/33239938-b8a03a3a-d2df-11e7-84ed-e02e70128575.png)

Or is it should be like that ?

**Comment by peppy** [comment]
The width is correct at 0.85.
