### ISSUE TITLE
Multiplayer gameplay starts for beatmap selected on multi song select rather than the current playlist item

### ISSUE THREAD

**Issue by bdach** [ppy/osu#15946]
Basically #15764 again, but with the distinction that you have to be at the song select screen and have a different song selected when the host decides to start gameplay.

### Discussed in https://github.com/ppy/osu/discussions/15945

<div type='discussions-op-text'>

<sup>Originally posted by **Veldora2k** December  5, 2021</sup>
Hi. Easy to reproduce bug, 100% of time.
-> Press ready as player then press "add map" (to poll)
-> Browse maps, don't add, stay at this list at different than picked to play song
-> Host is starting match
-> You are playing last saw song on list, not this one that others are playing.

It's easy to reproduce, tried this couple times and it works every time.</div>

**Comment by Veldora2k** [comment]
Thank you Bartek, you are doing awesome job :) Fast as f answers :D
