### ISSUE TITLE
Fullscreen and Borderless are broken on Wayland

### ISSUE THREAD

**Issue by puyoxyz** [ppy/osu#16021]
On Wayland, using Fullscreen or Borderless makes the game not appear visually but still run, appear in the alt+tab menu, and play sound. It works fine in Windowed, and if you switch from Windowed to Fullscreen or Borderless, the game will freeze visually (leaving a ghost window), but still run and play sound.

Logs (Wayland, started in Windowed, then switched to Fullscreen, it "froze" and left a ghost window I could still see in the GNOME overview and close) -> [runtime](https://paste.puyo.xyz/wefiqokofi) [performance](https://paste.puyo.xyz/yenonofosi) [network](https://paste.puyo.xyz/digajituvi)

Logs (Wayland, started in Fullscreen, no window appeared, had to Ctrl-C in terminal to close it) -> [runtime](https://paste.puyo.xyz/sicayolebi) [performance](https://paste.puyo.xyz/egexotepug) [network](https://paste.puyo.xyz/aruwagimew)

Artix Linux (OpenRC), GNOME 41.2, Nvidia GTX 1060 6GB (proprietary drivers), Intel i7-8700, 16GB RAM

### Discussed in https://github.com/ppy/osu/discussions/15625

<div type='discussions-op-text'>

<sup>Originally posted by **puyoxyz** November 14, 2021</sup>
Running Artix Linux, GNOME on Wayland. I can hear the game, but it doesn't open (there's no osu window). I'm using the AppImage.

- network.log https://paste.puyo.xyz/aveyasaxiw
- performance.log https://paste.puyo.xyz/eqesorujuv
- runtime.log https://paste.puyo.xyz/eyefeyuram</div>

**Comment by bdach** [comment]
wayland is known to be broken in several ways, and is not really actively supported. 99% confidence that most of the issues are upstream sdl issues rather than ours.

see the many search results at:
https://github.com/ppy/osu/search?q=wayland&type=issues
https://github.com/ppy/osu/search?q=wayland&type=discussions

closing, because there was never really any need to escalate this to an issue.

**Comment by puyoxyz** [comment]
> never really any need to escalate this to an issue

i escalated to an issue because i figured out what's causing the problem (fullscreen)

**Comment by bdach** [comment]
you could have just said that in the discussion. and please spare the snippy remarks.

**Comment by peppy** [comment]
Please don't escalate to issues. We will do that if/when appropriate.
