### ISSUE TITLE
Virtual keyboard not function on android

### ISSUE THREAD

**Issue by Picobyte-sudo** [ppy/osu#16033]
### Discussed in https://github.com/ppy/osu/discussions/16032

<div type='discussions-op-text'>

<sup>Originally posted by **Picobyte-sudo** December 10, 2021</sup>
So Basically for recent versions of osu!lazer the virtual keyboard is unfunctional which is kinda annoying  because I can't  look up any beatmaps on osu!direct I used to play one of the older versions this was a non issue however with newer ver it just doesn't work. Just requesting the devs if they could fix this bug in an update or does anyone know a fix? My current virtual  eyboard  is the default  Samsung keyboard.</div>

**Comment by bdach** [comment]
please do not escalate discussions to issues yourself, we will do this if it is appropriate
