### ISSUE TITLE
Switching to Classic score display while playing/watching causes DefaultScoreCounter to overlap other UI elements

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16067]
The per-skin layout code likely needs to be performed again after the current skin is changed while already in gameplay.

### Discussed in https://github.com/ppy/osu/discussions/15806

<div type='discussions-op-text'>

<sup>Originally posted by **zachmanthethird** November 26, 2021</sup>
I initially mentioned in #14770.
As the title suggests, the DefaultScoreCounter overlaps the DefaultAccuracyCounter and DefaultComboCounter when switching from Standardised to Classic score display when playing/watching using the "osu! (triangles)" skin. While I cannot show this in the skin editor (when entering, it creates a new modified skin, therefore reloading the skin and solving the problem), by creating a modified skin in Standardised score display, this behavior can be replicated, as modified skins do not change based on the score display mode.
Version 2021.1120.0-lazer
![osu_2021-11-25_14-04-20](https://user-images.githubusercontent.com/74262407/143504081-b3e8c7c6-4814-4939-b7f6-c3a563ded6a1.png)
![osu_2021-11-25_14-05-09](https://user-images.githubusercontent.com/74262407/143504087-1a730209-8af0-4d48-b3e8-6a66c7f64eb8.png)</div>

**Comment by bdach** [comment]
Thing is that all of the other elements (accuracy/combo meter) are freely movable, so after saving a modified default skin there is really no reliable way to tell if an element has been moved or not, because the skin json only persists global position.

The one reliable method I can come up with to make this work is to implement anchoring of elements relative to other elements. Either that, or to make the score display mode setting part of the skin...?

**Comment by peppy** [comment]
Hmm, my proposal was specifically for the default skins, where this is handled via the custom layout code:

https://github.com/ppy/osu/blob/f6a3709060b3ba4d81ce4f9d01df52aba7fa18dd/osu.Game/Skinning/DefaultSkin.cs#L81-L130

But I guess this is quite engrained in the skin implementation.

Here's a diff showing how this could be fixed for the default implementations, tested to work as expected. Not sure whether it's the correct path, though. Can imagine that once people start distributing custom layouts for lazer skins we may need something similar to what you mention (anchoring to other objects or adding some kind of flow support, the latter which was kinda planned from the start)

```diff
diff --git a/osu.Game/Screens/Play/HUDOverlay.cs b/osu.Game/Screens/Play/HUDOverlay.cs
index fdb5d418f3..ad688dd38b 100644
--- a/osu.Game/Screens/Play/HUDOverlay.cs
+++ b/osu.Game/Screens/Play/HUDOverlay.cs
@@ -17,6 +17,7 @@
 using osu.Game.Overlays;
 using osu.Game.Overlays.Notifications;
 using osu.Game.Rulesets.Mods;
+using osu.Game.Rulesets.Scoring;
 using osu.Game.Rulesets.UI;
 using osu.Game.Screens.Play.HUD;
 using osu.Game.Skinning;
@@ -83,10 +84,7 @@ public HUDOverlay(DrawableRuleset drawableRuleset, IReadOnlyList<Mod> mods)
             Children = new Drawable[]
             {
                 CreateFailingLayer(),
-                mainComponents = new SkinnableTargetContainer(SkinnableTarget.MainHUDComponents)
-                {
-                    RelativeSizeAxes = Axes.Both,
-                },
+                mainComponents = new MainComponentsContainer(),
                 topRightElements = new FillFlowContainer
                 {
                     Anchor = Anchor.TopRight,
@@ -120,6 +118,28 @@ public HUDOverlay(DrawableRuleset drawableRuleset, IReadOnlyList<Mod> mods)
             };
         }
 
+        public class MainComponentsContainer : SkinnableTargetContainer
+        {
+            private Bindable<ScoringMode> scoringMode;
+
+            [Resolved]
+            private OsuConfigManager config { get; set; }
+
+            public MainComponentsContainer()
+                : base(SkinnableTarget.MainHUDComponents)
+            {
+                RelativeSizeAxes = Axes.Both;
+            }
+
+            protected override void LoadComplete()
+            {
+                base.LoadComplete();
+
+                scoringMode = config.GetBindable<ScoringMode>(OsuSetting.ScoreDisplayMode);
+                scoringMode.BindValueChanged(val => Reload());
+            }
+        }
+
         [BackgroundDependencyLoader(true)]
         private void load(OsuConfigManager config, NotificationOverlay notificationOverlay)
         {
```

**Comment by bdach** [comment]
Hmm, I checked the above and it does appear to be functioning fine for the default skin, although if you modify anything in the default skin and save that, it will not function correctly (because all of the element positionings get written to json and become absolute, I imagine). Maybe fine to fix at least for the default skin for now, though...
