### ISSUE TITLE
Selecting a map with storyboard in SongSelect lags the game

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu#1606]
Exactly what the title says. If you load up the game, enter the song selection screen and open up a difficulty with a storyboard, the game basically hangs for a second or two and then resumes (audio usually resumes without problems, though I've had it stutter too in rare occasions).

**Comment by Aergwyn** [comment]
So far I found that `BeatmapManagerWorkingBeatmap.GetBeatmap()` is called every time the selection changes.

![qq](https://user-images.githubusercontent.com/27222621/33394879-0fd249c2-d544-11e7-93d4-1b567604ee70.png)

`GetBeatmap()` parses the files again every time though which includes the storyboard. Shouldn't the storyboard only load at the loading screen leading to the playfield though?

If I remove the two lines that are responsible for parsing the Storyboard the carousel behaves just fine without any lag at all.
Proposal: Can the storyboard loading be moved somewhere else where it's called when it's actually needed?

**Comment by peppy** [comment]
Yes, we probably need to make storyboard loading completely separate from Beatmap (ie. Beatmap shouldn't contain Storyboard; it should be at a WorkingBeatmap level if possible).

**Comment by Aergwyn** [comment]
Working on it. Will take a bit.

**Comment by Aergwyn** [comment]
Am I understanding correctly that `Storyboard` should be completely removed from `Beatmap`?
That would require changes to `BeatmapDecoder` though because it always expects a `Beatmap` no matter what to parse. Currently it's not able to function without a `Storyboard` in `Beatmap`.

**Comment by peppy** [comment]
That's the reason it hasn't been done yet (it's a non-trivial change).

**Comment by Aergwyn** [comment]
Alright. I'm going to try my luck then. Only that part remains.
