### ISSUE TITLE
Can't run debug build

### ISSUE THREAD

**Issue by zerox029** [ppy/osu#161]
I'm trying to help with some issues. 
I downloaded the zip file, unziped it and opened osu.sln with visual studio.
However, it's telling me that the osu frameworks are unexistent and when i try to run debug it's telling me the following : Visual Studio cannot start debugging because the debug target 'c:\target' is missing. Please build the project and retry, or set the OutputPath and AssemblyName properties appropriately to point at the correct location for the target assembly.  

Anyone knows how to fix?

**Comment by peppy** [comment]
Please learn how to git before trying to help. You won't be able to help by downloading a zip file.

https://desktop.github.com/ this may be a good place to start.
