### ISSUE TITLE
Beatmap card difficulty dropdown isn't visible when at the bottom of beatmap listing

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#16120]
### Discussed in https://github.com/ppy/osu/discussions/16119

<div type='discussions-op-text'>

<sup>Originally posted by **Sinamer** December 16, 2021</sup>
When you search for specific beatmaps and the amount of items is limited, difficulty dropdown of a beatmap card is covered by the end of page.

https://user-images.githubusercontent.com/53346335/146408971-8b1987e4-5794-4a89-b95a-da133a1b364e.mp4

</div>

**Comment by bdach** [comment]
this requires general design consideration because web has a similar problem wherein the dropdown extends past the footer.

![2021-12-16-185507_728x270_scrot](https://user-images.githubusercontent.com/20418176/146423860-482867fd-6903-429f-bf32-46f54f999bae.png)

**Comment by smoogipoo** [comment]
@arflyte

Though, maybe padding it will look fine in both cases?

**Comment by bdach** [comment]
I guess that's the obvious way out, yeah, but I'd probably want to pad by just enough for the last row dropdowns to fit rather than by a constant value...? Although that's pretty difficult to achieve and could look pretty wonky.
