### ISSUE TITLE
Can't use game-wide shortcuts at pause/fail screen

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1615]
Ctrl-O / F8 / other shortcuts are getting eaten somewhere.

**Comment by PoULkY** [comment]
I found that function `handleNewPressed()` is not executed properly.
So i split it in return code

![image](https://user-images.githubusercontent.com/15938103/33369291-a81c5b28-d526-11e7-9982-9177574558fe.png)

It worked (Ctrl-O & F8 shortcut button) but when i pressed shortcut button again to close it, it don't. I can close it with Escape button but using shortcut button to show it again is not wotking. Finally, it leading to crash

![image](https://user-images.githubusercontent.com/15938103/33369528-6a15068a-d527-11e7-82f9-b718d5ef8148.png)

I know showing a solution that leads to another error maybe is not a solution at all. But i hope this info will helps.

**Comment by Aergwyn** [comment]
This may be related to #1700?
