### ISSUE TITLE
Global audio offset is wrong for existing beatmaps

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1616]
- osu-stable applies a magic 24ms offset to maps older than version 5
- osu-stable uses an older version of bass. in newer versions the overall sync changed, which means that in lazer a UO of +35-40ms must be set for the game to feel good (samples too late by default).

**Comment by MattiaPette** [comment]
I think there is a mixerLatency channel attribute that can be applied, I'll PR asap

**Comment by chudooder** [comment]
Was there any progress made on this issue since last year? I'm trying to solve a similar issue in a standalone application using existing osu! beatmaps, so if I figure something out it might be applicable here.

**Comment by smoogipoo** [comment]
We've applied the 24ms offset and a global UO. I'm not sure if this issue should still be open.

**Comment by peppy** [comment]
Let's close this for now. It's feeling pretty good in general to me.
