### ISSUE TITLE
Playback slider tooltip and text show values of different precision

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#1618]
Playback speed slider in replays/autoplay have a tooltip and a text for their value with different precision. These should be the same or the tooltip may be entirely unnecessary here.

![qq](https://user-images.githubusercontent.com/27222621/33328746-14e82cb8-d45b-11e7-9a00-b72a7bcf080f.png)

**Comment by PoULkY** [comment]
When i change the precision to N2 (line 39), it show the same precision in text (previously is N1)

![image](https://user-images.githubusercontent.com/15938103/33355830-c04f4740-d4eb-11e7-8ee9-cb47b60f0317.png)

For anyone who wants more info about precision : https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings
