### ISSUE TITLE
Changing language should probably update `CurrentCulture`

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16320]
I believe stable does this, and lazer probably should too. This would allow formatting of numbers etc. to follow the user's language choice which makes sense in the majority of cases.

**Comment by bdach** [comment]
Pretty sure that should [already be happening...?](https://github.com/ppy/osu-framework/blob/0f2655a861c61c02340a1aae76bdb711e394d283/osu.Framework/Platform/GameHost.cs#L987) If it isn't then that logic must be somehow failing.

If it didn't work then locale specific number formatting wouldn't work, and I know for a fact that it does wherever supported.

**Comment by peppy** [comment]
Oh weird.. While testing https://github.com/ppy/osu/pull/16321 it didn't seem to. Silly me only searched osu-side for the setting of `CurrentCulture` - forget we had this implemented at a framework level.

**Comment by bdach** [comment]
It may be that some background threads (e.g. task pool ones?) won't receive the culture adjustment as the framework logic looks to be operating on a best effort basis (as in the main threads are the ones that directly and instantly apply the change, while background task threads may not necessarily do so as the game host cannot directly access them).
