### ISSUE TITLE
KeyboardStep in SensitivitySlider doesn't change anything

### ISSUE THREAD

**Issue by awesomecuber** [ppy/osu#1634]
In the MouseSettings class, the KeyboardStep of the SensitivitySlider is set to 0.01f. However, using the keyboard adjusts the sensitivity by 0.2 in game, which would be expected if the KeyboardStep was 0 (OnKeyDown in SliderBar). This is the only SliderBar which works in this way.

My suspicion is that this has something to do with SensitivitySlider not being a SettingsSlider like every other slider in the settings.

edit: I missed that there is indeed a SettingsSlider in MouseSettings, but it's not attached to the SensitivitySlider.

**Comment by peppy** [comment]
(Resolved by #1635)
