### ISSUE TITLE
Map skipping forward mid-song

### ISSUE THREAD

**Issue by Felixnightshade** [ppy/osu#16358]
### Discussed in https://github.com/ppy/osu/discussions/16357

<div type='discussions-op-text'>

<sup>Originally posted by **Felixnightshade** January  7, 2022</sup>
What I know:
Sometimes while playing a map it will 'skip' forward instantly. Sometimes it fasts forwards less than a second, and sometimes multiple seconds, though I haven't been keeping track on exact times. It doesn't appear to be map specific, as I can replay a map and have no skipping. When the skip occurs, nothing else happens. The map continues seamlessly, apart from me immediately losing combo from missing after the skip.
I'm on Linux now, but I've also had this issue in Windows 10 since at least a year ago (since my first time installing lazer).
If it would be useful, I could try to record an instance of this happening, but sometimes I can go entire days without it occurring, and other times it happens multiple times in a single play.

System Info:
OS: EndeavourOS rolling rolling (but this also happened in Windows 10)
Kernel: x86_64 Linux 5.15.12-arch1-1
Resolution: 1920x1080 (one of two 1080p monitors)
WM: i3
Disk: 842G / 5.6T (lazer is on a 3TB hardrive while my core system is on a separate 256GB NVMe drive. Lazer is run from the appimage release.)
CPU: AMD Ryzen 5 3600X 6-Core @ 12x 3.8GHz
GPU: AMD Radeon RX 5700 (NAVI10, DRM 3.42.0, 5.15.12-arch1-1, LLVM 13.0.0)
RAM: 32GB (I've never noticed my ram usage go above 6GB unless I manually do something that requires more ram, which never coincides with me playing osu)

Logs from the most recent time this happened:
[database.log](https://github.com/ppy/osu/files/7832071/database.log)
[network.log](https://github.com/ppy/osu/files/7832072/network.log)
[performance.log](https://github.com/ppy/osu/files/7832073/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7832074/runtime.log)

</div>

**Comment by frenzibyte** [comment]
Please don't consider self-escalating discussion threads next time.

**Comment by Felixnightshade** [comment]
Ah, thanks for letting me know. 

The map I was playing this time was [this yomi yori](https://osu.ppy.sh/beatmapsets/1047958#osu/2190486). I cannot reproduce the issue though, and it happens on very standard ranked maps that shouldn't have any issues whatsoever with them.

**Comment by peppy** [comment]
Continue discussion in discussion.
