### ISSUE TITLE
Searching for "Sparks" in "Any" category in beatmap listing overlay fails

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16364]
### Discussed in https://github.com/ppy/osu/discussions/16363

Going to be related to bpm being null in a graveyarded map, I'll check on why this is happening (was supposed to already be solved).

<div type='discussions-op-text'>

<sup>Originally posted by **Sinamer** January  8, 2022</sup>
If the chosen category is `Any`, typing "Sparks" into the search will fail to complete. `Has leaderboard` category completes the search just fine.

https://user-images.githubusercontent.com/53346335/148647448-b49ed47c-b34f-4de9-a2a9-05fea496f77c.mp4

[network.log](https://github.com/ppy/osu/files/7833352/network.log) (error is on line 183)
[runtime.log](https://github.com/ppy/osu/files/7833353/runtime.log)

</div>

**Comment by bdach** [comment]
Map is https://osu.ppy.sh/beatmapsets/1605094#osu/3277648.

Difference in this case is that the `.osz` *does* actually contains the `.osu` file for the difficulty with the null bpm, it just doesn't have any timing points. Which explains the null bpm, but not sure such maps should be submittable via BSS in the first place...?

**Comment by peppy** [comment]
I've fixed this case and also fixed this at a database level (better default value).
