### ISSUE TITLE
APIAccess.Perform() is sometimes called inside TPL tasks

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#16396]
I'm not entirely sure how to fix this / want more opinions so I'm making an issue for the time being.

The "currently playing" dashboard display is an example of a component that doesn't work anymore, failing with:
```
[network] 2022-01-10 08:19:33 [verbose]: Failing request osu.Game.Online.API.Requests.GetUsersRequest (System.InvalidOperationException: Can't use WaitSafely from inside an async operation.
[network] 2022-01-10 08:19:33 [verbose]: at osu.Framework.Extensions.TaskExtensions.WaitSafely(Task task)
[network] 2022-01-10 08:19:33 [verbose]: at osu.Framework.IO.Network.WebRequest.Perform()
[network] 2022-01-10 08:19:33 [verbose]: at osu.Game.Online.API.APIRequest.Perform(IAPIProvider api) in /home/smgi/Repos/osu/osu.Game/Online/API/APIRequest.cs:line 121
[network] 2022-01-10 08:19:33 [verbose]: at osu.Game.Online.API.APIAccess.Perform(APIRequest request) in /home/smgi/Repos/osu/osu.Game/Online/API/APIAccess.cs:line 249)
```
The source of this is:
https://github.com/ppy/osu/blob/9756c0ab5cf5ed1752a189880f87da31b8c3fd4e/osu.Game/Database/OnlineLookupCache.cs#L128-L130
Given the source above, there may be other components such as spectator which also no longer work as a result.

It seems like tournament should fail with the same issue, e.g.:
https://github.com/ppy/osu/blob/9756c0ab5cf5ed1752a189880f87da31b8c3fd4e/osu.Game.Tournament/TournamentGameBase.cs#L193-L214
Called from:
https://github.com/ppy/osu/blob/9756c0ab5cf5ed1752a189880f87da31b8c3fd4e/osu.Game.Tournament/TournamentGameBase.cs#L68

**Comment by peppy** [comment]
This looks like a framework side oversight. The second `WaitSafely` should be a standard `Wait` in [WebRequest](https://github.com/ppy/osu-framework/blob/master/osu.Framework/IO/Network/WebRequest.cs#L415).
