### ISSUE TITLE
Add support for nonstandard time signatures

### ISSUE THREAD

**Issue by bdach** [ppy/osu#16419]
Splitting from https://github.com/ppy/osu/issues/12020.

The goal is to support custom time signatures like stable did:

![](https://user-images.githubusercontent.com/80785742/111513293-8f822c00-8748-11eb-84aa-3c0c65e95480.png)

Moreover, currently when a map with a custom timing signature is opened, clicking on a row on the timing screen that has a custom signature crashes with

```
[runtime] 2022-01-11 21:22:40 [error]: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
[runtime] 2022-01-11 21:22:40 [error]: at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
[runtime] 2022-01-11 21:22:40 [error]: at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
[runtime] 2022-01-11 21:22:40 [error]: at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
[runtime] 2022-01-11 21:22:40 [error]: at osu.Framework.Extensions.ExtensionMethods.GetLocalisableDescription[T](T value)
[runtime] 2022-01-11 21:22:40 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.GenerateItemText(T item)
[runtime] 2022-01-11 21:22:40 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.selectionChanged(ValueChangedEvent`1 args)
[runtime] 2022-01-11 21:22:40 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
[runtime] 2022-01-11 21:22:40 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
[runtime] 2022-01-11 21:22:40 [error]: at osu.Framework.Bindables.Bindable`1.BindTo(Bindable`1 them)
[runtime] 2022-01-11 21:22:40 [error]: at osu.Framework.Bindables.BindableWithCurrent`1.set_Current(Bindable`1 value)
[runtime] 2022-01-11 21:22:40 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.set_Current(Bindable`1 value)
[runtime] 2022-01-11 21:22:40 [error]: at osu.Game.Overlays.Settings.SettingsItem`1.set_Current(Bindable`1 value) in /home/dachb/Dokumenty/opensource/osu/osu.Game/Overlays/Settings/SettingsItem.cs:line 90
[runtime] 2022-01-11 21:22:40 [error]: at osu.Game.Screens.Edit.Timing.TimingSection.OnControlPointChanged(ValueChangedEvent`1 point) in /home/dachb/Dokumenty/opensource/osu/osu.Game/Screens/Edit/Timing/TimingSection.cs:line 45
```

Example map to reproduce the above on is https://osu.ppy.sh/beatmapsets/545484#mania/1155651.

**Comment by frenzibyte** [comment]
For reference, there is already an issue thread open tracking the addition of nonstandard time signatures (https://github.com/ppy/osu/issues/2316).

**Comment by peppy** [comment]
And a PR which is stuck in limbo https://github.com/ppy/osu/pull/2403

**Comment by bdach** [comment]
That issue and that PR are talking about beat divisors and not the meter of the song though, aren't they? Like the beat snap and the timing signature on the timing point aren't the game thing?

**Comment by peppy** [comment]
Right. Considering this causes a crash it'd be best to get things working again as a starting point. Keep in mind that going forward, people are going to ask for changing the denominator as well. But that adds quite a bit of complexity (and requires new storage in the beatmap format) so would be a follow-up effort.
