### ISSUE TITLE
lazer crash after starting

### ISSUE THREAD

**Issue by Tylooo** [ppy/osu#1642]
Hi today i installed osu!lazer and updated framenetwork .NET to 4.7.1 to get it to work then i have a problem like this while turning it on:
![image](https://user-images.githubusercontent.com/34162455/33484500-cbea04ec-d6a2-11e7-922d-d243b1fa3d0f.png)
I don't know from where i can get crash logs

**Comment by peppy** [comment]
Please check other similar issues for more information on how to get crash logs. Right now issue reporting is focused on other developers who can help us get things done efficiently. Worst case scenario your crash will be accounted for once we get proper error reporting in.
