### ISSUE TITLE
Messages in multiplayer are only polled once per minute

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#16438]
### Discussed in https://github.com/ppy/osu/discussions/16437

<div type='discussions-op-text'>

<sup>Originally posted by **PandaDriver156** January 13, 2022</sup>
Messages sent in a lobby chat can take up to a minute to show up to other players.
Happens since the latest 2022.108.0 release.

Steps to reproduce:
  1. Enter a lobby with 2 clients
  2. Send a message on a client
  3. Message will not show up on the other client for around a minute, except if chat overlay is opened.

This very much seems to be caused by #16253, as opening the chat overlay does make messages sent in the lobby appear immediately.</div>

**Comment by peppy** [comment]
will investigate this one

**Comment by zachmanthethird** [comment]
This has not been fixed in tournament client. Version 2022.118.0
[runtime.log.txt](https://github.com/ppy/osu/files/7918245/runtime.log.txt)
[runtime.log.txt](https://github.com/ppy/osu/files/7918244/runtime.log.txt)
