### ISSUE TITLE
Add recovery support when realm cannot be opened

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16441]
Currently if a realm file can't be opened (usually due to backwards migration), the game will not start.

Instead, the game should create a fresh realm file and allow itself to start, along with letting the user know what happened so they can report the issue if it was unexpected.

Marking as p0 since I'd want to get this ready before a release happens with #16428.

**Comment by bdach** [comment]
I'll suggest it here as to not pollute the already-way-too-huge migration PR thread, but I'd also consider backing up users' databases before the beatmap/score migration is performed itself to avoid irrecoverable data loss and allow people to rollback if post-migration realm doesn't work in some respect.

**Comment by smoogipoo** [comment]
> I'll suggest it here as to not pollute the already-way-too-huge migration PR thread, but I'd also consider backing up users' databases before the beatmap/score migration is performed itself to avoid irrecoverable data loss and allow people to rollback if post-migration realm doesn't work in some respect.

Perhaps rather than nuking the old content, we can add a table + flag to the database to indicate migration completed? I have bad experiences with backing up user data from stable as there's always some way it goes wrong.
Definitely think this is required though.

**Comment by peppy** [comment]
If migration fails, it will throw before the old rows are deleted. Is there a scenario where that is not enough? Or are you trolling to allow users to roll back to an old version without manual backup?

**Comment by bdach** [comment]
I'm also worried about cases where the migration may be aborted
