### ISSUE TITLE
Represent sound frequencies in the editor by colors

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu#1650]
With waveforms being introduced into the editor, I and a bunch of other people thought it would be useful to make frequencies colored, like in programs such as Traktor DJ and Serato DJ, where you can see kicks and low frequency sounds as red and high frequency sounds as blue/white. This would greatly help in recognizing kicks / whistles / whatever and widen the usefulness of waveforms in a really good way. I can't even describe how much it improves working with audio in any way really.

Image of an example:
![example image](https://i.imgur.com/MuC5GOI.png)

**Comment by peppy** [comment]
This was in the original design, and I agree it would be a nice feature to see. If you're interested in working on it then go ahead.

Marking it as backlog because it's low priority in the scheme of things.

**Comment by hbnrmx** [comment]
Is this considered implemented with the current white <-> blue gradient 
or are we still considering the rainbow version?
![master](https://user-images.githubusercontent.com/46070579/50450338-8a4d2280-092d-11e9-87b1-fd61374d4153.PNG)
![color](https://user-images.githubusercontent.com/46070579/50450463-88379380-092e-11e9-96d1-49a5d457c0ec.PNG)

**Comment by smoogipoo** [comment]
Implemented.
