### ISSUE TITLE
Legacy scores import without classic mod

### ISSUE THREAD

**Issue by bdach** [ppy/osu#16513]
Unfortunately I missed this in my testing of the realm branch. Reproduction steps:

1. Download any stable score
2. Import to lazer
3. Classic mod isn't present on imported score

Failure is due to the convoluted `ScoreInfo` logic. Legacy decoder sets mods once:

https://github.com/ppy/osu/blob/b3983db69d5a5646cae2c3bdd9db326ea472fbfd/osu.Game/Scoring/Legacy/LegacyScoreDecoder.cs#L66

`ScoreInfo` ferries that across to `ModsJson` via `Mods.set`:

https://github.com/ppy/osu/blob/b3983db69d5a5646cae2c3bdd9db326ea472fbfd/osu.Game/Scoring/ScoreInfo.cs#L191-L197

Up to now everything is OK, but then `LegacyScoreDecoder` sets mods again:

https://github.com/ppy/osu/blob/b3983db69d5a5646cae2c3bdd9db326ea472fbfd/osu.Game/Scoring/Legacy/LegacyScoreDecoder.cs#L68-L70

`ScoreInfo` is supposed to ferry that across to `ModsJson` (which is the column that gets persisted to DB) via `Mods.set`, but `updateModsJson()` reads from `APIMods`:

https://github.com/ppy/osu/blob/b3983db69d5a5646cae2c3bdd9db326ea472fbfd/osu.Game/Scoring/ScoreInfo.cs#L230-L233
https://github.com/ppy/osu/blob/b3983db69d5a5646cae2c3bdd9db326ea472fbfd/osu.Game/Scoring/ScoreInfo.cs#L206-L219

At that stage, `apiMods` is null, but `ModsJson` has been populated with the first set of `Mods`, so the second update is essentially dropped in that `ModsJson` is never actually set the second time. The naive fix would be to only set `Mods` from the decoder once, but this feels really way too brittle.

**Comment by peppy** [comment]
Thanks for the detailed explanation. Quick fix would be emptying the `ModJson` string before repopulating, but that's pretty ugly. Will see if I can structure this better..
