### ISSUE TITLE
Per-object slider velocity isn't always saved correctly

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16540]
Looks to be something regressed in the latest release

### Discussed in https://github.com/ppy/osu/discussions/16537

<div type='discussions-op-text'>

<sup>Originally posted by **Axilotl17** January 21, 2022</sup>
[I've recorded a video of the bug here](https://youtu.be/Nj7DUF_gI_k)
(sorry for low quality idk why that happened)

I've tried restarting my game, I've tried reinstalling, different maps too; the only solution seems to be to use stable.

text version of bug:
the slider velocity sometimes gets reset to 1, or to the slider velocity of preceding sliders, and when you try to fix it it doesn't save, and even sometimes spreads to other nearby sliders. and when i change the position and velocity of a slider, only the position get saved, not the velocity. 

I'm using arch Linux, nvidia gpu and drivers. running lazer 2022.118.0 (although this happens across versions)</div>

**Comment by peppy** [comment]
To document, this is due to the nested lookup:

https://github.com/ppy/osu/blob/213d89b479e83bcc03bdeb38c5dee944f8ee68a7/osu.Game/Beatmaps/Formats/LegacyBeatmapEncoder.cs#L248-L249

Sliders have nested objects which don't have the velocity applied. I believe this was due to a recent (unrelated) change. I guess we want to copy the velocity down to nested control points? Wondering if there's a reason for this to be a nested lookup in the first place, though.

**Comment by peppy** [comment]
Point of regression is https://github.com/ppy/osu/pull/14619/commits/76ccdd1340b3480036207b94c6d688fdddef27ef. Specifically citing that this logic is required for `JuiceStream`s, although commenting out the nested lookup also does not make any tests fail..

Need opinions on the last sentence in the above comment as it changes how a fix should be applied here. Setting the velocity of all ticks in a slider from the editor UI is the easiest fix (and also what is done by the legacy decoder indirectly via `ApplyDefaults`), but feels a bit weird? Not sure.

**Comment by bdach** [comment]
If I remember correctly the reason the above commit was written was to continue correctly supporting sample points from legacy maps which were placed in the middle of an object with nested object, not just juice streams, I believe.

Because sample points implicitly happen at the end of the object, you would otherwise get a not-correctly-ordered list of sample points, leading the subsequent encoder logic to wrongly calculate which points are redundant and therefore safe to not encode.
