### ISSUE TITLE
Multiplayer gameplay leaderboard does not consider different user mod combinations

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#16562]
https://github.com/ppy/osu/blob/00177a3ae195130dcabe9657c76c78a4b809f481/osu.Game/Screens/Play/HUD/MultiplayerGameplayLeaderboard.cs#L52-L63

Back then users could not choose different mod combinations, but 4 months later support for that was added, but apparently to this day `MultiplayerGameplayLeaderboard` has not been updated to handle that yet.

### Discussed in https://github.com/ppy/osu/discussions/16557

<div type='discussions-op-text'>

<sup>Originally posted by **zachmanthethird** January 22, 2022</sup>
Using Standardised scoring, the scores from my player results screen give a total of 5,132,728. However, the score bar at the top seems to indicate a total of 6,438,041. Viewing the spectator screen, this appears to be resulting from No Fail not properly using the maximum of 500k. It doesn't matter whether NF is debuffed or not, the scores should corroborate. (Source: https://youtu.be/DDVeIYY3pYw?t=1675)
Version 2022.108.0
~~Last mp report from me today~~
![image](https://user-images.githubusercontent.com/74262407/150626254-032d8db9-f433-4408-8c3d-621d5cbad5a5.png)</div>

**Comment by peppy** [comment]
@smoogipoo is this still on your short-term list?

**Comment by smoogipoo** [comment]
Not immediately anymore, no, maybe as my next work item.
