### ISSUE TITLE
Cursor ignores mouse input when clicked for a small amount of time

### ISSUE THREAD

**Issue by ninjaprawn** [ppy/osu#1659]
Platforms tested: macOS (10.12.6)

The issue occurs when the user clicks (left or right). While the animation from the black cursor to the pink one is occurring, the user cannot move the cursor. This issue does NOT occur while Raw Input is enabled.

Steps to reproduce: Disable Raw Input (if enabled), spam click while physically moving your mouse

Expected result: the cursor will move (this can be confirmed with Raw Input enabled)

Actual result: the curse remains in the same position 

A video of this issue can be produced if required.

**Comment by peppy** [comment]
This is a framework level issue.

**Comment by Joehuu** [comment]
Closing as stale.
