### ISSUE TITLE
Changes to beatmap info made in editor not undone until next restart

### ISSUE THREAD

**Issue by bdach** [ppy/osu#16616]
Reproduction steps:

1. Enter editor
2. Change tags on setup screen
3. Exit without saving
4. Changed metadata will persist on song select until a game restart

Probably goes for a few other metadata items, can be also spotted with #16610 and #16613.

Likely cause is beatmap working cache pollution due to reusing same `BeatmapInfo` and likely easiest solution is purging said cache upon editor exit. Or cloning, but that's more finicky.

**Comment by bdach** [comment]
Turns out it is not enough to purge the cached working beatmap, the model also has to be refetched (because `BeatmapManagerWorkingBeatmap` uses the `BeatmapInfo` it is provided without question, so it has to be a refetched fresh instance from DB rather than a potentially-polluted editor one).

Proposed fix can be previewed at https://github.com/ppy/osu/compare/master...bdach:editor-changes-not-resetting?expand=1 but it's a touch ugly. Not sure how to package it better (and also have done essentially 0 further testing of it other than to ensure that the test I wrote for this scenario passes).

**Comment by frenzibyte** [comment]
Since the `BeatmapInfo` is a direct reference to the one from the working beatmap cache, I think only re-querying the beatmap from the database on `refetchBeatmap` makes sense here (similar to what you have in that branch):
```csharp
var refetchedBeatmapInfo = beatmapManager.QueryBeatmap(b => b.ID == Beatmap.Value.BeatmapInfo.ID);
var refetchedBeatmap = beatmapManager.GetWorkingBeatmap(refetchedBeatmapInfo);
```

 If `Editor` is the one which directly modified it, it should be responsible for refreshing it back on suspend/exit.

**Comment by peppy** [comment]
I think the proposed solution is fine for now.

I still have a picture of how we can better handle this once we begin to yank the detaching logic, but I don't believe that is an imminent effort.

**Comment by bdach** [comment]
@frenzibyte if you're trying to suggest that purging the working beatmap cache for the edited map isn't required then that's not correct. pretty sure i checked and without it, the previous instance with the same modified `BeatmapInfo` is used even despite the `BeatmapInfo` refetch.

**Comment by frenzibyte** [comment]
Right, invalidating the cache also makes sense now that I think about it.
