### ISSUE TITLE
Centralise Screen state management (for Screen.Push calls)

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu#1662]
This is needed so that screen-independent elements (e.g. chat overlay) can push screens or otherwise influence the screen states.
This should probably be done in `OsuGame`, as it contains the screenStack and currentScreen properties needed to do this.

**Comment by peppy** [comment]
Note that this already exists to some extent (see `LoadScore` in `OsuGame`). Also note that nothing should be pushing screens except the method that handles these incoming events.

**Comment by peppy** [comment]
You may want to actually mention what actions you need to be handled. This issue is way too general otherwise.

**Comment by FreezyLemon** [comment]
Oh, um, yes.
This would currently be needed for the actions that fire on clicking chat links (see #806), so:
- Open a spectator screen and spectate a certain player **if possible** (spectate link) 
- Open a multiplayer lobby screen and join a lobby **if possible** (invite link)
- Jump to a specific timestamp in the editor, if open (modding/editor timestamps)

What I mean by "if possible" is that not every screen can/should be pushed on top of any other screen. For example, pushing pretty much any screen while in the Player would be a bad idea.

**Comment by peppy** [comment]
None of these features exist yet, though. If anything, they should just be placeholder functions which we make work later (that show a notification or something for now).

**Comment by FreezyLemon** [comment]
Then this was a misunderstanding on my side.
I thought there should be some kind of general method or class that handles these requests from screen-independent elements on an `OsuGame` level instead of just single methods for every special case.

I guess it works, but couldn't this become an issue once there is too many special cases?

**Comment by peppy** [comment]
how would you even make one method to handle every case?

**Comment by FreezyLemon** [comment]
There would be multiple ways.. maybe a method that decides based on types of currentScreen and the new screen and then redirects to private methods? Of course it wouldn't just be one incredibly long and complex method, it would have to split workloads into smaller, private function calls.

On second thought though, if there is only one method to handle all of this, then the actual functionality behind it is mostly "hidden away" for the actual calls (as in naming doesn't make much sense anymore).. Might not be such a great idea afterall.

But maybe these still have to be moved to a dedicated class once it becomes too many.. or else it would be too cluttered. Not sure

**Comment by FreezyLemon** [comment]
Alright. So, I wrote the methods necessary for my intended changes (without actual implementation so far, just notifications showing up) and the way it is right now really doesn't justify its own issue, especially since I thought something else was supposed to be implemented when I opened this.
