### ISSUE TITLE
Importing BeatmapSets without BeatmapSetID in metadata "fails" silently

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#1666]
The map [Love Is War](https://osu.ppy.sh/s/8163) can't be imported because the files don't contain a `BeatmapSetID`. Thus it's assumed as "nekodex - circles" (which is already present) and reports completion.

EDIT: peppy reported [Baby Cruising Love](https://osu.ppy.sh/s/8023) with the same problem

**Comment by peppy** [comment]
I'm attacking this one, as it's pretty detrimental to importing.
