### ISSUE TITLE
Assert hit when pausing or failing a map

### ISSUE THREAD

**Issue by WhiteRedWolf** [ppy/osu#1668]
![screenshot_18](https://user-images.githubusercontent.com/33634370/33725128-89ab3488-db71-11e7-895a-a2f12591984e.png)

it happens randomly it is on the lastest version.

**Comment by peppy** [comment]
Does this happen when pausing during gameplay or replay? Do you have to be holding keys down for it to happen?

**Comment by WhiteRedWolf** [comment]
I happened to me whilke gameplay, Lazer did not crash tho, it just did randomly accur during pause/fail

**Comment by WhiteRedWolf** [comment]
and no i dont need to hold keys.

**Comment by peppy** [comment]
Does it happen at the point of pausing or by pressing keys *after* pausing? I'm yet to be able to reproduce :(

**Comment by WhiteRedWolf** [comment]
sometimes i do need to press keys to do it and sometimes not

**Comment by LovelyA72** [comment]
it happends to me when i tried to drag the beatmap list with my tablet/mouse to select a song...

**Comment by peppy** [comment]
@LovelyA72 that's a different error

@WhiteRedWolf what controls are you using to make this happen? Keys or mouse? If keys, which keys?
