### ISSUE TITLE
Beatmap carousel panels do not show correctly after changing ruleset

### ISSUE THREAD

**Issue by bdach** [ppy/osu#16752]
See following video:

https://user-images.githubusercontent.com/20418176/152240679-c92d4afa-d3c7-40dd-8900-f5607aedafd2.mp4

Regressed in #16716.

**Comment by peppy** [comment]
Regressed due to the state event fire dedupe at https://github.com/ppy/osu/pull/16716/files#diff-5c1acf993805bef85672afa52a88567a5b009fb98b346db743d8ebc2a501a4f7R124

Turns out `DrawableCarouselBeatmapSet` was relying on `Selected` arriving more than once..

**Comment by bdach** [comment]
This has been fixed for now by a revert of the regressing PR in #16782.
