### ISSUE TITLE
Hitobjects don't follow the cursor with "Aim Assist" when "No Scope" is enabled

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#16792]
This happens essentially when `Playfield.Cursor.Alpha = 0`, because the `CursorContainer` no longer receives positional input to update the `ActiveCursor.Position`.

However, I've found the following line in `CursorContainer` which made me wonder if that's how it should've behaved:
https://github.com/ppy/osu-framework/blob/1a5b2b275d7061e41578b015db1ea39d78b41840/osu.Framework/Graphics/Cursor/CursorContainer.cs#L37

![CleanShot 2022-02-06 at 00 12 18](https://user-images.githubusercontent.com/22781491/152659205-238be930-7fc6-4ebf-9c38-6586a60562fb.png)

It states that the override is for making sure `CursorContainer` updates position while it's hidden, but in reality, it's overriding `PropagatePositionalInputSubTree` to still depend on the `IsPresent` state, which will be false when the `CursorContainer` actually gets hidden?

Not sure if that's an outdated override or otherwise, but I think what's meant there is overriding it to always true instead? Opening an issue thread to keep track and get opinions first.

### Discussed in https://github.com/ppy/osu/discussions/16791

<div type='discussions-op-text'>

<sup>Originally posted by **Snake-GGJJWP** February  5, 2022</sup>
#### **Problem**
When playing a map with `No Scope` (`always hidden` customisation) and `Aim Assist` mode objects don't follow the cursor. Instead they gravitate to the place where the cursor was last time it was visible. As far as I get it if `No Scope` with `always hidden` customisation is enabled the game remembers the cursor's last position when it was still visible. It can clearly be seen when paused: orange cursor where you need to click to continue doesn't match the cursor's real position before pausing. Also, this bug appears only if `No Scope` is enabled with `always hidden` cutomisation.
#### **Video**
https://youtu.be/E-NlLufS9Ck
#### **Version and logs**
osu!lazer 2022.205.0
[database.log](https://github.com/ppy/osu/files/8008677/database.log)
[performance.log](https://github.com/ppy/osu/files/8008678/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8008679/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8008681/updater.log)

</div>

**Comment by frenzibyte** [comment]
Haven't bothered to test without hearing the intent of the current override, but I tested now and nothing falls to my eyes from what I've seen. 

I'm curious what you're thinking about specifically, I would think it not to break anything given that the only change in behaviour it has would be that `ActiveCursor.Position` will now update regardless of whether the `CursorContainer` is visible, which sounds like an improvement if anything?

**Comment by peppy** [comment]
Might be okay then. I was thinking more on the intertwining logic which ensures the menu cursor is hidden during gameplay, but that seems to be a separate path.
