### ISSUE TITLE
osu!lazer crashing at startup

### ISSUE THREAD

**Issue by rodreyperseus** [ppy/osu#1680]
Application Error:
Faulting application name: osu!.exe, version: 2017.1208.0.0, time stamp: 0x5a2968f9
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x48c
Faulting application start time: 0x01d370a8bb81a04b
Faulting application path: C:\Users\Rodrey\AppData\Local\osulazer\app-2017.1208.0\osu!.exe
Faulting module path: unknown
Report Id: 0c926922-6615-4cf4-8afb-d69684828472
Faulting package full name: 
Faulting package-relative application ID: 

.NET Runtime:
Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.ES30.GL.BlendEquationSeparate(OpenTK.Graphics.ES30.BlendEquationMode, OpenTK.Graphics.ES30.BlendEquationMode)
   at osu.Framework.Graphics.OpenGL.GLWrapper.SetBlend(osu.Framework.Graphics.BlendingInfo)
   at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(System.Action`1<osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D>)
   at osu.Framework.Platform.GameHost.DrawFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by TemTemmie** [comment]
known bug

**Comment by smoogipoo** [comment]
What GPU do you have?

**Comment by smoogipoo** [comment]
Have you installed the graphics drivers?

**Comment by rodreyperseus** [comment]
yup

**Comment by peppy** [comment]
This is far enough into execution that runtime.log should be present.

**Comment by rodreyperseus** [comment]
runtime.log
21/12/2017 9:55:15 AM: ----------------------------------------------------------
21/12/2017 9:55:15 AM: Runtime Log for Rodrey
21/12/2017 9:55:15 AM: osu version unknown
21/12/2017 9:55:15 AM: Running on Microsoft Windows NT 10.0.16299.0, 4 cores
21/12/2017 9:55:15 AM: ----------------------------------------------------------
21/12/2017 9:55:15 AM: GL Initialized
21/12/2017 9:55:15 AM: GL Version:                 1.1.0
21/12/2017 9:55:15 AM: GL Renderer:                GDI Generic
21/12/2017 9:55:15 AM: GL Shader Language version:
21/12/2017 9:55:15 AM: GL Vendor:                  Microsoft Corporation
21/12/2017 9:55:15 AM: GL Extensions:              GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture

**Comment by rodreyperseus** [comment]
[database.log](https://github.com/ppy/osu/files/1578733/database.log)
[performance.log](https://github.com/ppy/osu/files/1578734/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/1578736/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/1578737/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/1578738/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/1578739/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/1578740/runtime.log)

**Comment by MillhioreF** [comment]
OpenGL version 1.1 may not be adequate to run lazer at all... Are you able to use the latest stable build of osu!?

**Comment by rodreyperseus** [comment]
yes

**Comment by Poliwrath** [comment]
Might be an OpenTK issue? https://stackoverflow.com/questions/41857427/creating-a-graphic-context-using-opentk-returns-a-1-1-opengl-context-since-nvidi

**Comment by peppy** [comment]
We really need these issues to be created on `osu-framwork`, not `osu` :|.

**Comment by roza02** [comment]
My osu!lazer crashes too. (I am on win 10 and on intel graphics)

**Comment by roza02** [comment]
why do you delete my comment?

**Comment by peppy** [comment]
We don't need "me too" posts.

**Comment by roza02** [comment]
ok sorry

**Comment by TemTemmie** [comment]
probably something  with your graphics card or the framework. try updating your video card

**Comment by rodreyperseus** [comment]
It works now with ver. 2018.406.0. Thanks!
