### ISSUE TITLE
Android back button is not handled when at main menu

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16899]
It should return to the home screen as per standard android expectations. The behaviour should be the same as pressing the "home" button.

@Susko3 reckon you could look into this? would like to put an end to the attached discussion.

### Discussed in https://github.com/ppy/osu/discussions/16546

<div type='discussions-op-text'>

<sup>Originally posted by **TojikCZ** January 21, 2022</sup>
Hi, yes, Android apps don't have exit buttons. But I can't hold my back button, because I don't have that button. I only got gestures and the only way to quit osu is using the app switcher. Please let me quit it with the "see you next time". I miss it :pleading_face:</div>

**Comment by Susko3** [comment]
I'll look into it, I reckon we would do something similar to how [Android 12 (version code S) does it](https://developer.android.com/reference/android/app/Activity#onBackPressed()).

**Comment by Stedoss** [comment]
> I'll look into it, I reckon we would do something similar to how [Android 12 (version code S) does it](https://developer.android.com/reference/android/app/Activity#onBackPressed()).

That event is already handled framework side, but currently voided to prevent default behavior, if that helps.
https://github.com/ppy/osu-framework/blob/5a6dadf75d5a03fc2455ad61bd647792a9292332/osu.Framework.Android/AndroidGameActivity.cs#L121-L125
