### ISSUE TITLE
Difficulty calculation for stable not working

### ISSUE THREAD

**Issue by Pasi4K5** [ppy/osu#16900]
When osu!lazer 2022.216.0 (latest release) is open in the background, the difficulty calculation in stable shows 0 stars when recalculating a beatmap's difficulty. This issue is new to 2022.216.0.

Here's a video of me showing the calculated difficulty of a beatmap in stable with osu!lazer closed, osu!lazer 2022.205.0 open in the background and osu!lazer 2022.216.0 open in the background, respectively: https://youtu.be/oM0KD3Kd9hA

Logs (2022.216.0):
[network.log](https://github.com/ppy/osu/files/8085865/network.log)
[performance.log](https://github.com/ppy/osu/files/8085866/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8085868/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8085869/updater.log)

**Comment by peppy** [comment]
oh..
