### ISSUE TITLE
Click failling

### ISSUE THREAD

**Issue by anaboth** [ppy/osu#1691]
Everytime you have two circles in the same position, you will miss this two notes.

Compiling on Linux.

**Comment by peppy** [comment]
Need more detail.

**Comment by anaboth** [comment]
Basically it will miss if this two notes are on top of each other.
Here is a video of the bug: https://youtu.be/aeTtxlYgVHU
You can see it in: 0:53, 0:56, 0:59

**Comment by peppy** [comment]
Sounds like you may not be on latest head checkout (especially framework-side)?

**Comment by anaboth** [comment]
Actually I'm, I pulled everything 2~3 hours ago. Double checked to be sure.

**Comment by peppy** [comment]
Just to make 100% sure can you state the commit hashes you are on (especially for `osu-framework`)?

Also are you using custom key bindings, or default z/x?

**Comment by anaboth** [comment]
I just figured out, that for some reason mono was launching an old binary. Deleting everything, cloning and compiling again fixed it.

Yes, i'm using z/x.

osu - ce37688cd3be2b684aa454a406fd7f49e0034b96
osu-framework - 4c10fbf937804195f562b98a19c70768634d28d9
