### ISSUE TITLE
Right-click collections dropdown sometimes doesn't show

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#16953]
Can reproduce.

![image](https://user-images.githubusercontent.com/1329837/155061350-add0ff8b-1996-4e6e-9276-e1eee09b745a.png)

### Discussed in https://github.com/ppy/osu/discussions/16952

<div type='discussions-op-text'>

<sup>Originally posted by **TheFantasticLoki** February 22, 2022</sup>
I was going through adding all my custom maps for the ruleset Yoso to a collection and in order to filter for these maps I type adofai since all maps for yoso have the dif name adofai converted and after adding 6ish maps the collections tab on right click wouldn't show any of my collections untill after scrolling up a fair ways and scrolling back down. then it would show my collections for 1 map then be bugged again. still doing more testing to find out the scope of the problem</div>

**Comment by TheFantasticLoki** [comment]
Thanks for taking a look into this I honestly thought it was going to get swept under or just closed for wrong section
