### ISSUE TITLE
Non-current screens receive keyboard inputs.

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu#1700]
Steps to reproduce: Go into `SongSelect` and hit Ctrl-Shift-D. This will crash because `MainMenu` (which is not the current screen) runs its `OnKeyDown` method and tries to push a Screen.

This is because when the keyboard input queues are built, it only checks for `CanReceiveInput` which at the moment does not correlate with `IsCurrentScreen` and incorrectly adds `MainMenu` as an element that handles keyboard presses.

If `HandleInput` is modified to include `IsCurrentScreen` however, this will break all input (mouse too). Not sure why it does this.

**Comment by peppy** [comment]
This is a framework-level issue.
