### ISSUE TITLE
Implement Chat Overlay redesign

### ISSUE THREAD

**Issue by jai-x** [ppy/osu#17001]
Reference design: https://www.figma.com/file/f8b2dHp9LJCMOqYP4mdrPZ/Client%2FChat?node-id=0%3A1

**Comment by jai-x** [comment]
Some current questions I have regarding the implementation:

* The current reference design shows the overlay with the green theme. It is intended that the chat overlay can use all the overlay colour themes or just green?
* For the channel name text, does white text or green text indicate that there are unread messages in that channel? It's a bit unclear from the design :/
* What is the intended behaviour of clicking the "Channels" and "Direct Messages" text in the top bar? I assume filtering of showing already joined channels in the sidebar but there may be some other behaviour.
* Is there buttons or a context menu that should appear over channel names to be able to close/leave them?

That's all the immediate questions I have now. If this isn't the correct place to ask please let me know.

**Comment by peppy** [comment]
I'm not sure these designs are to be considered final / ready for implementation yet. I haven't seen them or given feedback yet. Probably best to hold off implementation before that happens, if you were planning on giving it a shot.

**Comment by bdach** [comment]
They look to [be marked as ready](https://www.figma.com/file/6m10GiGEncVFWmgOoSyakH/osu!-Figma-Library?node-id=0%3A1) on the index figma library page. Might have been a miscommmunication then? Possibly that's not a "ready" for implementation, but more of a "ready" from the standpoint of "design complete"...

**Comment by jai-x** [comment]
I assumed the design was ready based on the status displayed on that page. If it's not ready I'm fine doing something else

**Comment by peppy** [comment]
I'll take a look at it today, and confirm with @arflyte on intentions.

**Comment by peppy** [comment]
@jai-x I think it should be fine to implement and see how we go. My only thought is that we may want to keep the current overlay around as a setting the user can choose (ie. "horizontal" or "vertical" layout), but the design language likely isn't going to match going forward. Probably fine to nuke and revisit later.

**Comment by jai-x** [comment]
I think I may have enough of an implementation to start PR'ing individual components. Here's a short video of what I have so far running on a local release build: 

https://user-images.githubusercontent.com/8362491/156933658-ac49504b-7f61-4268-9742-46c7b3c86779.mp4

Here is also the WIP branch of my changes so far with visual test for each component. Note that I'm not going to PR from this branch since it's all over the place and will instead PR individual component on their own branch:

https://github.com/jai-x/osu/tree/new-chat

Some additional implementation specific things that have come up:
- The top of the overlay doesn't show it's corner radius as specified in the design due to a bug with nested masking containers. I tried using the workaround using a nested buffered container but it ends up making the text look really fuzzy. May need a local workaround for that.
- The channel control sidebar doesn't show mentions in a channel yet. This is because the `MessageNotifier` is setup to post new mentions to the `NotificationsOverlay` and the `Channel` class doesn't have an attribute for it. May need to refactor this class for it when integrating the new overlay into the game proper.
- The channel control sidebar doesn't have a way to show unread messages since their doesn't seem to be a way to bind to that in sensible way. May need it's own component to manage this and can be address at the same time as the `MessageNotifier` changes.
- The `A-` and `A+` buttons have not been added. I assume they are responsible for changing the text size of the channel but I'm not sure of a sensible way to implement that.
- The search icon button has not been implemented. I assume it is used to search previous messages in a channel. May be added later
- The collapsed behaviour of the overlay has not been implemented and seems quite complex. I don't think any other overlay class does anything similar so would maybe require a new overlay base class to encapsulate having three states (Visbile/Hidden/Collapsed but still updating).

**Comment by bdach** [comment]
Yeah piece by piece is best. I have some small reservations about what is shown on the video but it's probably best that it's addressed along the way rather than here.

I'll say one thing that looks missing and wasn't mentioned above is the "new day" line visible at around 0:19 - doesn't seem to have been touched at all and that one is [actually on design](https://www.figma.com/file/f8b2dHp9LJCMOqYP4mdrPZ/Client%2FChat?node-id=2%3A16).

**Comment by jai-x** [comment]
The new day line is in internal component of `DrawableChannel`. At the moment I've just dropped in the `DrawableChannel` component with no changes aside from making that line white in colour. Given it is also used in other places like lobby chat I was hesitant to change it further.

**Comment by bdach** [comment]
@jai-x just to confirm, are you planning on cleaning up the old design classes at some point?

**Comment by jai-x** [comment]
Yes will do.
