### ISSUE TITLE
Bug de dificultad en osu!mania

### ISSUE THREAD

**Issue by Phantom047** [ppy/osu#1703]
Se me presento un error, en donde las dificultades de los mapas tipo mania, no mostraban sus estrellas (osea, dificultad) Una ss del problema
![image](https://user-images.githubusercontent.com/34610880/34074941-4e8dd95e-e298-11e7-9b58-f7e1ceba9905.png)

**Comment by ColdVolcano** [comment]
Creo que se prefiere (o se necesita) que todos los problemas se muestren en inglés. Haz tu mejor esfuerzo de traducción de ahora en adelante.
Lo que describes no ha sido implementado, vuelve en un tiempo.
English: NAB

**Comment by peppy** [comment]
Please post issues in english in the future (even using google automatic translation is better than nothing!)
