### ISSUE TITLE
malloc(): unsorted double linked list corrupted

### ISSUE THREAD

**Issue by heredos** [ppy/osu#17109]
while playing a few online games with my sister, the game often crashed during the beatmap loading process.
i tried to run the game from command line and here is what i got as an error message:
![image](https://user-images.githubusercontent.com/75367977/156886586-736f7f72-bc84-4cde-9794-48aa38cd093f.png)
note that i tried to play a beatmap on solo mode, and it still crashes 3/4 of the time.
i am running the game from a 64-bit computer running manjaro.
here are the logs, but from what i can see, there isn't anything interesting in there.
[logs.zip](https://github.com/ppy/osu/files/8190808/logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/discussions/16959

also please open discussions rather than issues next time. discussions will be escalated to issues as we see fit.
