### ISSUE TITLE
Sliders don't give RepeatPoints samples

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#1712]
Slider's RepeatPoint construction doesn't pass samples down to the repeat points.

**Comment by Aergwyn** [comment]
SliderTicks do something like this:
```
Samples = new SampleInfoList(Samples.Select(s => new SampleInfo
{
    Bank = s.Bank,
    Name = @"slidertick",
    Volume = s.Volume
}))
```
Is it the same for RepeatPoints? Just with a different (not known) name? Or is it a deeper problem?

**Comment by smoogipoo** [comment]
Pretty much, except they should look up the samples relating to their repeat index from `IHasRepeats.RepeatSamples`. Leave this until after https://github.com/ppy/osu/pull/1665 is merged because it contains some important structural changes to that stuff.
