### ISSUE TITLE
Scrolling ruleset playfields are not reloaded in editor after significant configuration changes

### ISSUE THREAD

**Issue by bdach** [ppy/osu#17127]
Hoped this was going to be rather easy to handle but it isn't. There are two main problems:

* how to subscribe to appropriate timing changes in order to know that bar lines need to be regenerated
* timing points are wedged in rather deep - `DrawableScrollingRuleset` uses them in BDL, for instance, to generate multiplier points. So it may be easier to just regenerate the whole drawable editor ruleset to avoid things being half-broken...?

### Discussed in https://github.com/ppy/osu/discussions/17094

<div type='discussions-op-text'>

<sup>Originally posted by **zachmanthethird** March  4, 2022</sup>
Version 2022.226.0 | taiko and mania gamemodes
This one is hard to put into words. If you enter the editor and change a timing point, the ticks in the timeline at the top do update while the "barlines" (at least that's what they're called in taiko) on the playfield do not, leading to misleading behavior. In both screenshots, I've aligned myself to a new "barline" tick, but that's not visually represented in the playfield.
![osu_2022-03-03_23-55-08](https://user-images.githubusercontent.com/74262407/156723778-23bee53a-aaac-4b52-a89e-f4bb96c9ab86.png)
![osu_2022-03-03_23-59-47](https://user-images.githubusercontent.com/74262407/156723774-e3e73c0c-460b-4a17-a092-8d4d8c2eaf7e.png)
When saving and reloading, everything displays visually how it should.
It should also be noted that small changed to the Scroll Speed (less than 0.5) are also not represented properly on the playfield until saving and reloading the beatmap. This makes mapping in these gamemodes especially difficult.</div>
```[tasklist]
### Tasks
- [ ] https://github.com/ppy/osu/pull/28444
- [ ] https://github.com/ppy/osu/pull/28445
```

**Comment by peppy** [comment]
This has come up a few times. Wondering if a single event at `ControlPointInfo` that is fired on *any and every* change may be a good starting point? Feels we should get these flows working robustly before attempting to subscribe locally to events.

**Comment by 2minwia** [comment]
Changing the SV of a roll in taiko using the velocity setting on the compose page also doesn't update until you reload the editor.

**Comment by peppy** [comment]
Going to bump this up to p0 due to the taiko scroll speed issue also occurring due to the same root failure.

As above, I think a single event we can subscribe to to watch for changes would be a starting point to get things into a sane state.

**Comment by peppy** [comment]
Dropping back to p1 as our focuses are elsewhere and I don't think this can be called "critical to next release".
