### ISSUE TITLE
We need a better way to handle nested HitObjects

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#1713]
At the moment pretty much every gamemode instantiates nested HitObjects in one way or another. Osu instantiates ticks and repeats in Slider, Mania instantiates head/tail/ticks in HoldNote, Taiko instantiates ticks in DrumRoll, and Catch will probably follow the same.

We want `ApplyDefaults` to be called on these nested hit objects, and potentially even have them reconstructed if any properties inside the containing `HitObject` are changed.

**Comment by peppy** [comment]
I think this may be resolved @smoogipoo

**Comment by smoogipoo** [comment]
Yup.
