### ISSUE TITLE
Signify "not enough disk space" IO exceptions to users

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#17133]
We may want to explicitly show up a warning notification in such cases, rather than returning misleading "Beatmapset download failed" errors.

### Discussed in https://github.com/ppy/osu/discussions/17132

<div type='discussions-op-text'>

<sup>Originally posted by **sponnify** March  6, 2022</sup>
attempting to download any beatmaps from "browse" cancels after a second, and "playlists" results in "beatmapset download failed!". at random times, i will be able to download from browse only, but after a minute i will no longer be able to.

running windows 11 and latest version of lazer. please @ me and mention the files which will be helpful for troubleshooting.</div>

**Comment by jai-x** [comment]
Related: https://github.com/ppy/osu/issues/5997

**Comment by frenzibyte** [comment]
Right, closing as duplicate of the aforementioned issue thread.
