### ISSUE TITLE
Hovering a button on pause container causes it to become selected

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1714]
If the mouse is hovering one of the three pause menu (or two fail menu) items when the menu appears, it immediately gets focus. This causes keyboard selection to have an incorrect starting point.

Behaviour should be changed to only trigger a hover after the mouse is moved.

**Comment by Aergwyn** [comment]
While it's true that the hovered button immediately becomes selected (which isn't really bad I think) it does not seem to cause an incorrect starting point for keyboard selection.
But moving the mouse again (but not leaving the button you hovered) does not reselect it if the selection changed through keyboard.
What do?
