### ISSUE TITLE
Allow attaching descriptions to the playlist lobbies

### ISSUE THREAD

**Issue by peppy** [ppy/osu#17224]
I think this is something we want sooner rather than later.

### Discussed in https://github.com/ppy/osu/discussions/17221

<div type='discussions-op-text'>

<sup>Originally posted by **venix12** March 12, 2022</sup>
Would be a nice addition for spotlights lobbies since such kind of description could contain a brief information on how spotlights system work along with a link to wiki or newspost for more of an in-depth explaination of those stuffs (mostly for people randomly finding out spotlighted lobbies while playing around with lazer). 

Would also likely be useful for regular lobbies to explain the gimmick or purpose of a playlist.</div>

**Comment by pastequeninja** [comment]
Hi, 

I'm new on the project, and I would like to contribute. Is this this section that you are talkin about ?
![image](https://user-images.githubusercontent.com/36705698/159451088-c9797d75-0f07-4f60-be00-b8b86f678b46.png)
 
And the aim is it to understand how create a playlist that's it ? I'm not sure about the definition of "spotlights lobbies"

**Comment by peppy** [comment]
No, this is talking about online playlists.

**Comment by peppy** [comment]
This is being tracked via https://github.com/ppy/osu-web/issues/8736
