### ISSUE TITLE
Spectating mid-gameplay no longer seeks to first received frame time

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#17267]
Regressed in https://github.com/ppy/osu/pull/17026/commits/bb8caabb8be3e0391fee7adede8f0bed09948737 due to `MasterGameplayClockContainer` resetting current time on `LoadComplete` rather than BDL. 

`SpectatorPlayer` can receive the first frame and seek to it before `MasterGameplayClockContainer` reaches `LoadComplete` state, therefore, after https://github.com/ppy/osu/pull/17026/commits/bb8caabb8be3e0391fee7adede8f0bed09948737, `MasterGameplayClockContainer` would overwrite any seeks done before `LoadComplete`, and regress spectating mid-gameplay.

I'm unsure about a solution to this, perhaps the sanest would be to schedule the first frame seek in `SpectatorPlayer` to run after `Player` updates children (i.e. `ScheduleAfterChildren`)

### Discussed in https://github.com/ppy/osu/discussions/17266

<div type='discussions-op-text'>

<sup>Originally posted by **minasminas** March 16, 2022</sup>
The singleplayer spectate doesn't seem to work anymore. It did work a few weeks ago (don't know which update broke it). Multiplayer spectate is working good as usual by the way.

While testing this issue I also made sure that the user is really playing the map and isn't in the menus or pausing.

Here is a short video of the issue:

https://user-images.githubusercontent.com/81645139/158482669-6692fe95-93f8-4b8b-a445-d02811147468.mp4

Logs:
[performance.log](https://github.com/ppy/osu/files/8257473/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8257475/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8257476/updater.log)
[database.log](https://github.com/ppy/osu/files/8257477/database.log)
[network.log](https://github.com/ppy/osu/files/8257478/network.log)

</div>

**Comment by smoogipoo** [comment]
Guessing this is probably also causing all the recent test failures...?

**Comment by frenzibyte** [comment]
Indeed now that I look at [this one](https://github.com/ppy/osu/runs/5561977171?check_suite_focus=true)... never thought that to be relevant. The interesting part is that it's intermittent, would've thought that to always fail on all platforms.

**Comment by peppy** [comment]
One thing I'm unsure about here is how does the flow that @frenzibyte proposed actually occur? The `OnNewFrames` call is `Scheduled` at a `SpectatorClient` level:

https://github.com/ppy/osu/blob/67082b8c5de9d97d353ea973f34bc6773af4029f/osu.Game/Online/Spectator/SpectatorClient.cs#L155

Which while being at the wrong component, this would guarantee the gameplay screen to have loaded along with all children at this point, no?

`Player.OnEntering` -> `StartGameplay` -> `OnNewFrames +=` -> `Player.LoadComplete` / `Player.UpdateSubTree.loadChild` -> `SpectatorClient.Scheduler.Update` is what I'm seeing.

**Comment by frenzibyte** [comment]
The reason behind that is actually interesting: [`Player` sets its alpha to 0 at `OnEntering` to fade in](https://github.com/ppy/osu/blob/2eb3365f463618a8679a2ba4a06418bc44b1e4c8/osu.Game/Screens/Play/Player.cs#L926), but that causes it to have `IsPresent = false` on the first (current) frame, therefore delaying updating its children until next frame (see [`CompositeDrawable.UpdateSubTree`](https://github.com/ppy/osu-framework/blob/108c36ef5e23e6842d49fd03c603d34d63972bac/osu.Framework/Graphics/Containers/CompositeDrawable.cs#L906-L908)). 

And in that single frame window, `SpectatorClient` updates its scheduler and executes the scheduled `OnNewFrames`, therefore causing `userSentFrames` to be executed before `MasterGameplayClockContainer` gets loaded and receives the `LoadComplete` callback.

**Comment by peppy** [comment]
Jesus. I saw that `Alpha` set and was definitely suspicious of it.

Solving this isolated failure is easy enough, but this level of critical failure makes it feel like we need to reexamine things at another level.
