### ISSUE TITLE
Multiplayer host should be pinned to the top of the participants list

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#17297]

**Comment by frenzibyte** [comment]
I've spent some time on this and I've stumbled across 3 different ways to pin the host in a good UX manner.

The first way is to keep it simple and only change the order so that the new host gets moved to the top but is still in the same participants list:

https://user-images.githubusercontent.com/22781491/158780577-bc6c60b2-96fe-4b68-ba46-a03325cc8d68.mp4

The second way (additional to the first) is to add a spacing between the host and the participant (potentially with a separator line in the middle):

![CleanShot 2022-03-17 at 12 24 28](https://user-images.githubusercontent.com/22781491/158780840-70d954de-c32a-49bc-b2a7-3d8379822779.png)

The third way is to move the host to its own section away from the participants list:

![CleanShot 2022-03-17 at 12 21 09](https://user-images.githubusercontent.com/22781491/158781057-d0183171-cb0b-4357-bb42-468bf5150472.png)

Would like feedback on which sounds best and make more sense.

**Comment by peppy** [comment]
I prefer the third, but I'm not sure how this will work when we (probably) group players on the same teams in the future. We could potentially show the host but also duplicate them into the "Participants" list (renaming it to "Teams" or something).

I'd say for now, keep things simple and go with the first option (showing them first in the list but not separating out), but am interested to hear other's opinions.

**Comment by AadilRn** [comment]
I prefer the second one tbh. I feel as if it is cleaner than the third option, showing clearly who the host is much better than the first and the spacing looks much nicer than the two lines above and below. The difference in spacing caused by the "host" subtitle also doesn't help the aesthetic.

**Comment by bdach** [comment]
I think first is ok. Second also looks fine but will get awkward with multiple teams as stated above. Option 3 makes little sense to me given there is already a crown icon on the room user panel, so both the header and the crown being there is just duplicated information and wasting space on the actual user panels. Could be fine with having that separated if the crown icon is removed.

**Comment by frenzibyte** [comment]
I'll go with the first option for now then, we can revise on this once the room gets redesigned and more displays of the participants list (i.e. teams list) get added.
