### ISSUE TITLE
Non-user-playable mods can be selected in multi if previously selected in solo

### ISSUE THREAD

**Issue by bdach** [ppy/osu#17306]
had to pull out the repro scenario from the reporter but it does appear to be legitimate:

1. Open the game
2. Go to song select
3. Activate Auto
4. Go to playlists
5. Create playlist

also works with multiplayer. note that web-side validation will prevent the room from actually being created like this, so the impact of this is not major, but still feels pretty bad.

### Discussed in https://github.com/ppy/osu/discussions/17304

<div type='discussions-op-text'>

<sup>Originally posted by **Moltanicaa** March 17, 2022</sup>
I think this is wrong
![image](https://user-images.githubusercontent.com/59089206/158872560-77438a8a-c3e4-42e0-8ca9-96de808b3c2e.png)
</div>

**Comment by nagilson** [comment]
I could work on this. What is the preferred behavior? 
1. Just disable/toggle off the Automation mod from the enabled mods list when entering playlists? 
2. Keep it on but display an error message when trying to edit playlists? 
3. Keep it on and allow adding songs to playlists but ignore the automation mod?

**Comment by bdach** [comment]
1 makes most sense to me - 2 is too much noise for what isn't really a huge deal, and 3 is just outright weird. In fact I'm not entirely convinced that mods from solo song select should carry over to multiplayer at all ever but I may need backup opinions on that.

**Comment by frenzibyte** [comment]
Would agree mods shouldn't carry across screens like that. In fact, I think it's likely to be an oversight:
https://github.com/ppy/osu/blob/bdc3b76df0b58406796e2b08db13be7f2140fa7e/osu.Game/Screens/OnlinePlay/OnlinePlaySongSelect.cs#L85-L93

`rulesetInstance` will be null if there is no item in the playlist (i.e. when creating a new room, which I believe to be the only case where this issue can occur).

**Comment by nagilson** [comment]
Thanks @bdach and @frenzibyte. I think I have enough context now to fix this issue. I can do that, then investigate how to add a regression test.
