### ISSUE TITLE
"Hold for menu" button fading area can conflict with the osu! playfield

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#17313]
Currently, the fading area is decided by the distance between the mouse position and the center of the button with a constant divisor applied to reduce the area, that causes the button to potentially start fading when a hitobject is near the edges of the playfield, which can distract the player.

![CleanShot 2022-03-18 at 06 14 17](https://user-images.githubusercontent.com/22781491/158930805-3f47cb11-76a7-47a8-9ae5-229ab5362e53.gif)

I'm currently stuck between increasing the divisor value for the fading area to not conflict with the playfield, and just removing the entire logic behind fading it and only do so when the cursor is exactly on the button.

---

As an aside, I've noticed during `TestSceneAutoplay` that the hitobjects could actually end up conflicting with the button itself when the window is in square aspect ratios:

![CleanShot 2022-03-18 at 06 00 48](https://user-images.githubusercontent.com/22781491/158931068-d13e7ea2-e320-439c-9e0f-0a49321cafeb.png)

But I think it's safe to say that's out of scope, for the time being at least.

### Discussed in https://github.com/ppy/osu/discussions/17308

<div type='discussions-op-text'>

<sup>Originally posted by **DeadEyed-5** March 18, 2022</sup>
i cant play a single beatmap without having the hold for menu X pop up and its the most distracting thing in the world. is there a way to disable the auto pop up whenever your cursor goes near it. 
edit: my screen is monitor is square because its all i have so the play area takes up the whole monitor basically. So every time i go near the bottom right it the hold for menu button shows up.</div>

**Comment by peppy** [comment]
Unsure about opening issues when we haven't finished discussing a solution, but ok let's go with it.

As a first step the button should probably be moved to where the key counter is to reduce the likelihood of it getting in the way. I'm also okay with reducing the radius for visibility.
