### ISSUE TITLE
Spelling error.

### ISSUE THREAD

**Issue by HydroZenon** [ppy/osu#17310]
### Discussed in https://github.com/ppy/osu/discussions/17309

<div type='discussions-op-text'>

<sup>Originally posted by **HydroZenon** March 17, 2022</sup>
License is spelled wrong. Just wanted to make a quick correction
![Screenshot (147)](https://user-images.githubusercontent.com/101785393/158926572-5e07365b-fe04-447f-aaee-f8b377d2f301.png)
.</div>

**Comment by frenzibyte** [comment]
Please don't create issues from discussions, we'll do that ourselves.
