### ISSUE TITLE
api-ms-win-core-winrt-l1-1-0.dll file is missing

### ISSUE THREAD

**Issue by Virajphoenix** [ppy/osu#17330]
i downloaded the osu Lazer setup like some hours ago so when I opened the setup and this error popped up I tried restarting my laptop still the same error do let me know if I did anything wrong
![osu Lazer error](https://user-images.githubusercontent.com/93857948/159060494-85b343fe-0a9c-44f4-98dc-e25463ee094d.png)
 this second error comes after i click 'ok' on the first error
![osu lazer error(2)](https://user-images.githubusercontent.com/93857948/159060683-09fc2d3a-a9b2-495f-b3ae-ee90de083896.png)

**Comment by bdach** [comment]
From screenshots I'm guessing you're running on windows 7 which is not supported [as per readme](https://github.com/ppy/osu#running-osu).

**Comment by Virajphoenix** [comment]
thank you it helped me a lot :)
