### ISSUE TITLE
Skin editor doesn't properly take keyboard input focus when watching a replay

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#17346]
### Type

Game behaviour

### Bug description

Skin editor's element settings sliders don't properly take keyboard left and right arrow input when editing gameplay. When the left or right arrow keys are pressed, the replay is seeked instead of adjusting the slider bar.

When editing song select, the left and right arrow keys properly move the slider, same thing when editing a skin during live gameplay (since arrow keys don't do anything then).

### Screenshots or videos

The slider in question:

![image](https://user-images.githubusercontent.com/16479013/159125068-50eb15bd-8f3a-49fa-aff1-79a07dcafbac.png)

### Version

2022.391.0

### Logs

[network.log](https://github.com/ppy/osu/files/8309424/network.log)
[performance.log](https://github.com/ppy/osu/files/8309425/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8309426/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8309427/updater.log)

**Comment by bdach** [comment]
this is because replay seeking is using `KeyBindingContainer` and sliders are using `OnKeyDown()`. making https://github.com/ppy/osu-framework/issues/3992 the actual underlying issue here.

**Comment by peppy** [comment]
Probably okay to keep this tracking the issue?

**Comment by Susko3** [comment]
It's doing the opposite of the linked framework issue. Probably because of:

https://github.com/ppy/osu/blob/866ae3472bb654af5bde50f79ecb0ae2cbd884e5/osu.Game/Input/Bindings/GlobalActionContainer.cs#L131-L138

**Comment by peppy** [comment]
A high level solution to this is likely to stop input from reaching the target screens when the skin editor is active. I'll take a look at how simple this is to acheive.
