### ISSUE TITLE
Paused the Game & i couldn't unpause

### ISSUE THREAD

**Issue by PotatoGod937** [ppy/osu#17344]
### Type

Game behaviour

### Bug description

ok so I was playing a 27 minute long map right and my hand was getting tired so I paused the game when I tried to un-pause I was unable to click the orange circle to un-pause (I paused like 5 or 6 times through the map fine it broke around the 16 minute mark)

### Version

2022.314.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8309354/runtime.log)

**Comment by bdach** [comment]
sorry but this is not nearly enough information to go on to even begin looking for the issue.

do you have a video of this? what map was it? how were you pausing? how do you know it "broke around the 16 minute mark"?

**Comment by PotatoGod937** [comment]
ok so you know when you unpause and there is an orange circle you have to press i couldn't press it and it says how long you have played in the bottom right also no i do not have video of this i do have shadowplay but i forgot to turn it on

**Comment by frenzibyte** [comment]
You mention "clicking", but have you actually toggled off "Disable mouse buttons during gameplay? I'm not sure that'll work if you have it toggled on.

**Comment by tybug** [comment]
Thanks for the report, but I'm going to close as we can't reproduce this issue without more information. If you can provide more information or a reliable reproduction, we'll look at reopening this issue!
