### ISSUE TITLE
Scores made with third party rulesets can't be saved

### ISSUE THREAD

**Issue by LumpBloom7** [ppy/osu#17350]
### Type

Game behaviour

### Bug description

Users are greeted with a "Score failed to import" notification after completing a play with a third party ruleset, and scores don't show in local leaderboards, and replays can't be viewed. 

This regression seems to be introduced in #17017, when the check in `LegacyScoreEncoder` have switched from checking `score.ScoreInfo.BeatmapInfo.Ruleset.OnlineID` which is always 0, to checking `score.ScoreInfo.Ruleset.OnlineID` which is always -1 for third party rulesets.

### Screenshots or videos

https://user-images.githubusercontent.com/12001167/159126084-eabe3e95-f459-4619-a656-92ef41b31176.mp4

### Version

2022.319.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/8309611/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8309612/updater.log)
[database.log](https://github.com/ppy/osu/files/8309613/database.log)
[network.log](https://github.com/ppy/osu/files/8309614/network.log)
[performance.log](https://github.com/ppy/osu/files/8309615/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8309616/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8309617/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8309618/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8309619/performance-update.log)

**Comment by bdach** [comment]
Not sure what the solution is here. While the end result is unacceptable at best, the ruleset ID check was there from the very first revision of `LegacyScoreEncoder` and hasn't been failing until now by pure chance.

Best thing I can think of is just removing the check.

**Comment by EVAST9919** [comment]
First time this issue was introduced after lazer transferred to realm (2022.127.0)

**Comment by smoogipoo** [comment]
Moving this out of p0 since the PR above aiming to fix this has been left in a blocked state for 1+ months.

**Comment by peppy** [comment]
I still consider this p0 as it shows an error message after every score. I'll revisit today and hopefully find a simpler solution to just disable saving for now.
