### ISSUE TITLE
Now playing overlay are still usable in new gameplay skin editor

### ISSUE THREAD

**Issue by HelloYeew** [ppy/osu#17351]
### Type

Crash to desktop

### Bug description

Normally in playfield with or without autoplay I cannot using some global shortcut or can toggle but cannot use like in playfield with auto mod I can still toggle but cannot skip or pause the track since it's make the game crash. But when I toggle now playing overlay and I can do anything like in normal menu like next track, previous track or select a track from dropdown to make the game crash. (But cannot pause the track)

Note that using next track (F5) or previous track (F1) shortcut can reproduce too.

### Screenshots or videos

https://user-images.githubusercontent.com/68165621/159131668-4dd68534-0581-4b6b-8396-63339ad8658e.mp4

### Version

2022.319.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/8309763/runtime.log)

**Comment by peppy** [comment]
This is due to an oversight I noticed during testing but forgot to address: the button doesn't load `PlayerLoader` in the chain of loading (which is what restricts the ability to change tracks).

**Comment by frenzibyte** [comment]
Alternatively we can add the `DisallowExternalBeatmapRulesetChanges` override to `Player` as well, rather than forcing `PlayerLoader` in the middle.
