### ISSUE TITLE
Add setting to blur background during gameplay

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#1736]
For people who think 100% background dim is too dark, but still don't want to get distracted by the background. It could be listed in the settings under background dim.
I've seen this used in a couple of places already (like the song select screen), so it would just be a matter of reusing that code and adding a toggle to settings.

**Comment by peppy** [comment]
I don't see any harm in adding this alongside background dim.

**Comment by EriiYenn** [comment]
**Hello,**
Shall I continue with unfinished **Blur System**, as it is still opened, or you are about to close it with some statement for the future developement.

*Thanks for answer in advance,*
**EriiYenn**

**Comment by jorolf** [comment]
https://github.com/ppy/osu/pull/1754

**Comment by EriiYenn** [comment]
Let's see how it ends :)
