### ISSUE TITLE
Score submission doesn't submit mods(?)

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#17383]
### Type

Other

### Bug description

I played some maps with mods apply, result screen seems normal. but when I check the profile page for submitted score, it's become no mod.

### Screenshots or videos

[Replay file, consider change .txt to .osr](https://github.com/ppy/osu/files/8313447/IkaWaAyuMu.playing.Shimotsuki.Haruka.-.Rengoku.Dored.Cartagra.txt)
![image](https://user-images.githubusercontent.com/7066150/159213282-37599120-2736-4002-9d7e-4eddf9cbc673.png)

Recent plays from [Me](https://osu.ppy.sh/users/1978491)
![image](https://user-images.githubusercontent.com/7066150/159213311-8d236daf-db0f-44df-9858-8f7f5a9cd59a.png)

### Version

2022.319.0-lazer

### Logs

[update.log](https://github.com/ppy/osu/files/8313469/update.log)
[update_success.log](https://github.com/ppy/osu/files/8313470/update_success.log)
[runtime.log](https://github.com/ppy/osu/files/8313471/runtime.log)
[session.log](https://github.com/ppy/osu/files/8313472/session.log)

**Comment by peppy** [comment]
Thanks for reporting this. Fixed via ppy/osu-web#8738. Not sure what to do about scores from the last 5 days, but unless anything too bad comes up we'll probably let this one slide.
