### ISSUE TITLE
Editor Test Play never exits when starting from a different time

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu#17395]
### Type

Game behaviour

### Bug description

- Reproduction Steps:
  - Open any beatmap in editor
  - Advance the time to any time greater than the first hit object
  - Open test play and complete the beatmap
  
- Cause:
  - This is because `EditorPlayer` relies on `ScoreProcessor.HasCompleted` to check whether a map has been completed or not. However, the check works if all hit objects have been judged and this is never true for the case when the beatmap starts at a different time.
  
```csharp
hasCompleted.Value =
    JudgedHits == MaxHits
    && (JudgedHits == 0
        // Last applied result is guaranteed to be non-null when JudgedHits > 0.
        || lastAppliedResult.AsNonNull().TimeAbsolute < Clock.CurrentTime);
```

### Screenshots or videos

https://user-images.githubusercontent.com/20495991/159376139-98ef4101-c4af-4dfa-aa63-11f3bbcd55e3.mp4

### Version

2022.319.0

### Logs

N/A

**Comment by peppy** [comment]
This is a weird one, because somehow `SpectatorPlayer` manages to avoid the issue, but I can't immediately find the logic making it work there..

**Comment by bdach** [comment]
I'm guessing that spectator player exit is driven by `EndPlaying()` calls rather than beatmap completion.

**Comment by smoogipoo** [comment]
In spectator, `ScoreProcessor` gets replay frames applied to it which updates `JudgedHits`:
https://github.com/ppy/osu/blob/cda46ec8a3dbc1b0ef9bad53971ade094ee4bff8/osu.Game/Rulesets/UI/RulesetInputManager.cs#L87-L89
