### ISSUE TITLE
Hit sound not playing on certain notes

### ISSUE THREAD

**Issue by SimsimhanChobo** [ppy/osu#17405]
### Type

Other

### Bug description

Hitsounds for some notes do not play on lazer
At least in Mania 4K...

I checked issue #8375 but still I get the same problem

I am using Windows 10 21H2 (19044.1586)

### Screenshots or videos

osu! : [https://youtu.be/HdvQNbAOEo8](https://youtu.be/HdvQNbAOEo8)
osu!lazer : [https://youtu.be/w-GVtTtcMJI](https://youtu.be/w-GVtTtcMJI)
(Other bitmaps have the same problem.)

### Version

2022.319.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8322790/database.log)
[network.log](https://github.com/ppy/osu/files/8322791/network.log)
[performance.log](https://github.com/ppy/osu/files/8322792/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8322793/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8322794/updater.log)

**Comment by peppy** [comment]
Could you please link the beatmap you're seeing this in, and the rough timestamp where you expect to hear the hitsounds?

**Comment by SimsimhanChobo** [comment]
> Could you please link the beatmap you're seeing this in, and the rough timestamp where you expect to hear the hitsounds?

It is the most different in Quaver (1854032) 0:52
I'm not sure if I understood correctly.

**Comment by SimsimhanChobo** [comment]
I think this video is better at explaining the bug than the video above.

osu! : [https://youtu.be/baSe1UIGkus](https://youtu.be/baSe1UIGkus)
osu!lazer : [https://youtu.be/Q0dyNCwk8ew](https://youtu.be/Q0dyNCwk8ew)

**Comment by peppy** [comment]
Can reproduce this, isolated to the following test case:

```csharp
osu file format v13

[General]
AudioFilename: Freedom Dive.mp3
AudioLeadIn: 0
PreviewTime: 108027
Countdown: 0
SampleSet: Normal
StackLeniency: 0.7
Mode: 3
LetterboxInBreaks: 0
SpecialStyle: 0
WidescreenStoryboard: 1

[Editor]
DistanceSpacing: 0.8
BeatDivisor: 12
GridSize: 8
TimelineZoom: 2

[Metadata]
Title:FREEDOM DiVE
TitleUnicode:FREEDOM DiVE
Artist:xi
ArtistUnicode:xi
Creator:razlteh
Version:4K Hyper
Source:Cytus
Tags:bms blocko fullerene- tear dainesl
BeatmapID:420005
BeatmapSetID:173612

[Difficulty]
HPDrainRate:7
CircleSize:4
OverallDifficulty:8
ApproachRate:5
SliderMultiplier:1.4
SliderTickRate:1

[Events]
//Background and Video events
0,0,"background desuuu.jpg",0,0
//Break Periods
//Storyboard Layer 0 (Background)
//Storyboard Layer 1 (Fail)
//Storyboard Layer 2 (Pass)
//Storyboard Layer 3 (Foreground)
//Storyboard Sound Samples
//Background Colour Transformations
3,100,163,162,255

[TimingPoints]
2133,270.002700027,4,1,0,30,1,0
10772,-100,4,1,0,30,0,0

[HitObjects]
320,192,18603,1,12,0:0:0:0: // removing this hitobject fixes the hitsounds in the subsequent hitobjects
64,192,18873,1,12,0:0:0:0:
192,192,18940,1,0,0:0:0:0:
320,192,19008,1,0,0:0:0:0:
448,192,19075,1,0,0:0:0:0:
64,192,19143,1,12,0:0:0:0:
192,192,19210,1,0,0:0:0:0:
320,192,19278,1,0,0:0:0:0:
448,192,19345,1,0,0:0:0:0:
```

Still looking into the underlying issue.

**Comment by peppy** [comment]
45233932089ea26d9e329c47f1893137d2d4bcaf + pooling = 😢
