### ISSUE TITLE
Legacy beatmap version offset is applied incorrectly

### ISSUE THREAD

**Issue by peppy** [ppy/osu#17404]
Currently, we apply a legacy adjustment offset in `LegacyBeatmapDecoder` at decode time, at the hitobjects directly:

https://github.com/ppy/osu/blob/a029e418cfef55371f956f3b4e39be6126596e99/osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs#L496-L500

In contrast, stable applies these offsets at what we currently call a "clock" level, unless loading for editing. ie. alongside the following other offsets:

https://github.com/ppy/osu/blob/edd361d256a2428f9ce0f5a16aa2dc1ceaa2ba96/osu.Game/Screens/Play/MasterGameplayClockContainer.cs#L173-L184

To explain *why* stable only applies the offsets where it does, and why it makes sense that way:
- The offsets are inherently required to apply to fix sync between hitobjects and audio.
- Any replays set before and after the change happened should work correctly.

Considering only these two preconditions, it is obvious that the offset should be applied at a point of `GameplayClock`. The extra complexity comes from the fact that:
- When saving a beatmap (upgrading it from <v5 to >v5), the offset needs to be baked into the hitobjects and timing points, as we can no longer use the version specification to apply the offset.

So in stable, the offset is "baked into" the beatmap timings like we are doing on lazer, but only when entering edit mode:

![JetBrains Rider-EAP 2022-03-22 at 07 29 20](https://user-images.githubusercontent.com/191335/159429498-bcbbd98d-5dfc-4105-832d-0ad7bd32d6ae.png)

In all other cases, they are applied in the `AudioEngine` offset calculation:

![JetBrains Rider-EAP 2022-03-22 at 07 29 56](https://user-images.githubusercontent.com/191335/159429588-33f2293a-ea5e-4f91-9e4d-bcd19d1cf972.png)

This means that what we are currently doing is incorrect, and any replays created with lazer have incorrect timing values for these beatmaps. It's also the reason that (all) replays set on stable for these beatmaps will be incorrectly timed (see linked issue for examples).

Proposals:

- Remove the baking logic from `LegacyBeatmapDecoder` completely. Apply on entering the editor or in `LegacyBeatmapEncoder` (if the latter, would need to figure out what to do about non-legacy encoding).
    - This would require adding a new offset component to `GameplayClock` to account for the offset. It would also mean the editor wouldn't be applying this offset (although this is part of a [larger](https://github.com/ppy/osu/issues/12064) [issue](https://github.com/ppy/osu/issues/11400) which really needs attention).
- Apply the same offset logic to replays, both during encoding and decoding
    - Has the advantage of keeping this legacy offset out of `GameplayClock`, at the cost of making legacy replay serialisation more complex.

### Discussed in https://github.com/ppy/osu/discussions/17362

<div type='discussions-op-text'>

<sup>Originally posted by **MrWither83** March 20, 2022</sup>
_I mentioned in the meeting that there might be some gameplay differences in how stacked sliders are handled with classic mod, but I found out another issue while looking for the slider one. Will continue to investigate on that._

I observed this phenomenon on a few maps, mostly old maps so the issue might be linked to some kind of offset specific to older formats not being applied in lazer.

1st map : https://osu.ppy.sh/beatmapsets/243#osu/1147
| stable | lazer after watching replay |
| :---: | :---: |
| ![screenshot502](https://user-images.githubusercontent.com/52672543/159153401-f27ff5d0-2713-46ff-aa50-875084f3f91e.jpg) | ![image](https://user-images.githubusercontent.com/52672543/159153314-988caaca-b49f-4fc0-86c1-b763a00c17e8.png) |

Replay : https://drive.google.com/file/d/1SeHl50mi_wQon-qKX_WbzOStRN6dC5dE/view?usp=sharing

2nd map : https://osu.ppy.sh/beatmapsets/131#osu/292
| stable | lazer after watching replay |
| :---: | :---: |
| ![screenshot503](https://user-images.githubusercontent.com/52672543/159153764-c6a07304-cdb3-492b-b4dd-ada76881d6b6.jpg) | ![image](https://user-images.githubusercontent.com/52672543/159153700-543fc0a2-45be-4fba-9190-fd4077bb2d01.png) |

Replay : https://drive.google.com/file/d/1zNIcabn259aHzJTnCu1oZYFUOU4VBr-_/view?usp=sharing

</div>

**Comment by frenzibyte** [comment]
To state my opinion on this one, I think it is better to go with the second option here if feasible, to keep legacy code in their place rather than moving them to `GameplayClockContainer` (and still bake it into objects on decoding during edit mode, which makes it more complicated).
