### ISSUE TITLE
BPM Value as shown in the timing section of the editor sometimes shows incorrect bpm.

### ISSUE THREAD

**Issue by AggressiveCombo** [ppy/osu#17446]
### Type

Game behaviour

### Bug description

If you go into the timing section in the editor, make a new timing point, and open the timing window, then move your mouse to your bpm, it may be less bpm than it shows in the little window.

### Screenshots or videos

https://user-images.githubusercontent.com/80444661/160087258-43c0e2f6-8fcf-45e2-9bc2-2ce03769f92c.mp4

SCREENSHOT: https://prnt.sc/E1IrO69zefpO

### Version

2022.319.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/8348882/network.log)
[performance.log](https://github.com/ppy/osu/files/8348883/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8348885/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8348886/updater.log)
[database.log](https://github.com/ppy/osu/files/8348887/database.log)

**Comment by bdach** [comment]
This is mostly a rounding discrepancy. This particular slider needs work anyhow as the precision/step on it is rather nonsensical right now.

**Comment by AggressiveCombo** [comment]
yep i think it should round up to an integer for example: 146.98 - 147 
songs dont have decimal bpms so that is a good idea

**Comment by Cesan** [comment]
> yep i think it should round up to an integer for example: 146.98 - 147 songs dont have decimal bpms so that is a good idea

Some maps have, for example [Freedom Dive](https://osu.ppy.sh/beatmapsets/39804#osu) has 222.22 bpm, so removing the precision would break things maybe. I would go with a slider snapping to full integers and being able to adjust the precision afterwards in the textbox or so

**Comment by AggressiveCombo** [comment]
cesan yeah that's what i meant

**Comment by frenzibyte** [comment]
The best I can see happening is to set `0.01` precision to the BPM bindable, and have `KeyboardStep` set to `1f`:

https://user-images.githubusercontent.com/22781491/160255513-7b249ca0-ab67-4432-96dd-27cab30fa4ad.mp4

There has been a long-standing issue thread for improving steps to make the UX of this much better (https://github.com/ppy/osu-framework/issues/1109), but I'm unsure if it can be improved further currently.

**Comment by SensouShin** [comment]
Or just remove slider input for numbers. Slider is one of the worst input for numbers. Also It just wasting space(duplicate input for the same thing) and if you have to adjust bpm in textbox already there is no point to keep them.

**Comment by peppy** [comment]
I wouldn't be against removing it for now.

**Comment by CenTdemeern1** [comment]
I agree with removing the slider.
Plus I'd like to add that using the slider gives you a minimum/maximum cap for bpm, which is also quite nonsensical.
For example, more than enough songs exist with a bpm greater than 240.
The first example I thought of was WYSI by Camellia, which is (quite appropriately) 727 bpm.

**Comment by peppy** [comment]
Removed via #17581.
