### ISSUE TITLE
Beatmaps with videos sometimes crashes the game

### ISSUE THREAD

**Issue by yellowsink** [ppy/osu#17457]
### Type

Crash to desktop

### Bug description

Playing beatmaps with videos sometimes freezes the game, crashing roughly 30 seconds later, with what appears to be a memory error from some called C code printed to stdout:
```
malloc(): unsorted double linked list corrupted
zsh: IOT instruction (core dumped)  osu-lazer
```

On some other attempts at reproducing the bug, I also encountered this message:
```
free(): invalid next size (fast)
```

### Screenshots or videos

https://youtu.be/vZO6JfvC5oQ

### Version

2022.319.0

### Logs

[database.log](https://github.com/ppy/osu/files/8352778/database.log)
[network.log](https://github.com/ppy/osu/files/8352779/network.log)
[performance.log](https://github.com/ppy/osu/files/8352780/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8352781/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8352783/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8352784/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8352785/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8352786/runtime.log)

**Comment by bdach** [comment]
Please post output of `ffmpeg -version`.

**Comment by yellowsink** [comment]
```
λ ffmpeg -version
ffmpeg version n5.0 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
libavutil      57. 17.100 / 57. 17.100
libavcodec     59. 18.100 / 59. 18.100
libavformat    59. 16.100 / 59. 16.100
libavdevice    59.  4.100 / 59.  4.100
libavfilter     8. 24.100 /  8. 24.100
libswscale      6.  4.100 /  6.  4.100
libswresample   4.  3.100 /  4.  3.100
libpostproc    56.  3.100 / 56.  3.100
```

**Comment by bdach** [comment]
The game uses the system-wide FFmpeg and this particular set of versions seems to have a bug upstream that causes this. See also: https://github.com/ppy/osu/discussions/17035#discussioncomment-2276489.

Please upgrade to a newer FFmpeg version if one is available or downgrade to 4.x.

**Comment by yellowsink** [comment]
ok then, thanks!
