### ISSUE TITLE
"Import skins from stable" button doesn't import skins correctly.

### ISSUE THREAD

**Issue by zachmanthethird** [ppy/osu#17456]
### Type

Cosmetic

### Bug description

Someone new to lazer informed me that they were annoyed that legacy skins weren't yet implemented. Upon following up, it appears as though skins imported using the button are imported as lazer skins instead of legacy skins. Skins imported as `.osk`s import correctly.

### Screenshots or videos

![osu_2022-03-25_10-11-19](https://user-images.githubusercontent.com/74262407/160168835-a5666bc4-7c72-4327-a47b-c1422ada1969.png)

### Version

2022.319.0

### Logs

[database.log](https://github.com/ppy/osu/files/8352563/database.log)
[runtime.log](https://github.com/ppy/osu/files/8352565/runtime.log)

**Comment by peppy** [comment]
It works fine here. Please attach the skin.

**Comment by zachmanthethird** [comment]
[skin.zip](https://github.com/ppy/osu/files/8352604/skin.zip) is what I was using. I'll ask what skin my friend was using. Just rename from `.zip` to `.osk`

**Comment by peppy** [comment]
That skin has basically no files. The skin.ini is also malformed, missing a version which is a requirement to have elements understood correctly.

 In addition, it has a blank sprite for pippidon, and pippidon is hidden on your screnshot. What is your expectation here?

**Comment by peppy** [comment]
That is an existing issue (https://github.com/ppy/osu/issues/13448) which actually should be resolved as of the next release, in theory. If you want classic elements to be used you will need to have a score font in the skin.

Will close this as a duplicate. You can test in the next release to confirm it works better.

But there is no different between loading via .osk or not. You are just loading a very weird skin here.
