### ISSUE TITLE
Using high precision mouse make bug on laptop's tactile screen

### ISSUE THREAD

**Issue by orkeilius** [ppy/osu#17467]
### Type

Game behaviour

### Bug description

When high precision mouse is enable (by default in windows), using a tactile screen make your mouse teleport to the top left corner of your screen
that, a similar issue that #14021
>edit: randomly that seem to work correctly until I disable/re-enable the setting

A temporary fix should be:
- enable the warning on Windows too (see #14023)
- disable this setting by defeat (idk how to do that)

### Screenshots or videos

i can't video on my potato's laptop

I can make a video with my phone if that really needed

### Version

2022-319-0 (lazer)

### Logs

[network.log](https://github.com/ppy/osu/files/8356107/network.log)
[performance.log](https://github.com/ppy/osu/files/8356108/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8356109/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8356110/updater.log)
[database.log](https://github.com/ppy/osu/files/8356111/database.log)

**Comment by bdach** [comment]
Was previously reported in https://github.com/ppy/osu/discussions/16840, is already being tracked as https://github.com/ppy/osu-framework/issues/5033
