### ISSUE TITLE
Opening the Autoplay mod's profile shows a real user with the same name

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#17479]
### Type

Game behaviour

### Bug description

After watching a replay with the Autoplay mod (in the osu! ruleset), the game shows the leaderboard as usual.
The weird thing is when I click the Autoplay user icon, which leads to [a "random" user named AutoPlay](https://osu.ppy.sh/users/27721499) (presumably inactive).

### Screenshots or videos

![image](https://user-images.githubusercontent.com/43073074/160277713-6572ca9f-f97f-4d21-9aa2-fa183c054ee2.png)

### Version

2022.327.0-lazer

### Logs

The only portion of the logs showing the issue seems to be in the `network` file:

```
2022-03-27 10:30:31 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2022-03-27 10:30:32 [verbose]: Request to https://osu.ppy.sh/api/v2/users/Autoplay/?key=username successfully completed!
```

**Comment by frenzibyte** [comment]
Seems like it regressed after the addition of looking up users via usernames in https://github.com/ppy/osu/pull/15487. Should probably be disabled on cases like autoplay users (by potentially assigning "system" user ID or otherwise).
