### ISSUE TITLE
"Disable mouse buttons during gameplay" also disables touch

### ISSUE THREAD

**Issue by Ruubke** [ppy/osu#17470]
### Type

Game behaviour

### Bug description

It's a while ago that I played osu on my phone,
So after updating the app
Tapping a hitbox while playing a map doesn work anymore
Tapping trough the menus en scrolling works.
But when I play a map it doesn't tap anymore and I lose the game
Is this normal or is it a bug?
My phone is a Samsung galaxy fold 3 with Android 12

### Screenshots or videos

https://youtu.be/EPWXjxnfmzo

### Version

2022.319.0

### Logs

Nope

**Comment by frenzibyte** [comment]
This is due to having mouse buttons disabled:

![CleanShot 2022-03-27 at 01 25 20](https://user-images.githubusercontent.com/22781491/160258981-04d63583-8359-4b93-91c3-f49b9bfca67b.png)

The setting should be reworded to include "touch" and "tablet" as well, as mentioned in https://github.com/ppy/osu/pull/16330#issue-1094206356.

**Comment by bdach** [comment]
Or touch input could be exempt from that toggle after all. Tablet stylus presses could still be covered by it, just not touch.

**Comment by Ruubke** [comment]
Thank u guys!
I did not notice that button!
It does work now!!
Or maybe not enable that botten on default would fix it?

**Comment by bdach** [comment]
It is not on by default.

https://github.com/ppy/osu/blob/4de66bb1c6e053a948b968d85905c0dda95f8a2b/osu.Game/Configuration/OsuConfigManager.cs#L84

**Comment by Ruubke** [comment]
Odd, I'm sure I never pressed on it.

**Comment by peppy** [comment]
This is a hard one to address, as once we have proper touch support in it will no longer be an issue (the only reason for the failure is because of the touch-to-mouse implicit mapping).

Maybe best to close this issue for now with that in mind?

**Comment by bdach** [comment]
I mean,.. do you think that eventually every single clickable component in the game is going to explicitly handle touch via separate touch handlers? Because I find that... unlikely. The touch-to-mouse mapping covers 99% of normal UI cases, and it seems like a good idea to keep that going just to spare us the boilerplate.

**Comment by peppy** [comment]
The disable setting here only disables mouse buttons during gameplay. I think I'd expect all gameplay to be implemented to use touch, right?

**Comment by bdach** [comment]
Fair, I'd tend to agree with that position.

**Comment by frenzibyte** [comment]
You might potentially still want this when hitting objects via virtual controls on one hand but still controlling the cursor across the screen with another, which is a regular mobile play-style as far as I'm aware.

**Comment by bdach** [comment]
> This will be required for when hitting objects via virtual controls on one hand but still controlling the cursor across the screen with another

I... don't think so? What does that have to do with anything? The virtual controls should be handling... mouse and touch events, no? So it'd be weird to have a toggle that "turns off mouse and touch" but only on the playfield?

**Comment by frenzibyte** [comment]
> What does that have to do with anything?

This has to do with whether the option should never disable touch input.

> So it'd be weird to have a toggle that "turns off mouse and touch" but only on the playfield?

That's exactly how it behaves currently, player overlays are exempted from those checkboxes. Although the scenario I brought is a little bit at the extremes of this, the options will definitely never affect the virtual controls (which will be an overlay at a `Player` level).

**Comment by bdach** [comment]
I don't know, this sounds like really confusing behaviour that could be done much simpler, e.g. by forcing the user to choose one of:

* click the objects by touching with one finger without use of virtual controls (one finger playstyle),
* or point at the objects with one finger and click them with the virtual controls (two finger playstyle).

At least that has semi-expected consequences in comparison to an obscurely named toggle with weird edge cases.

**Comment by frenzibyte** [comment]
> point at the objects with one finger and click them with the virtual controls (two+ finger playstyle).

Well, that's the type of playstyle I'm referring to, and it has the potential of the pointing finger potentially triggering hit actions if the user releases and holds again the same finger, but I suppose it's not that much of an issue until someone reports it.

**Comment by bdach** [comment]
i don't think you understood my point above there. i was trying to make a point that the presence of the virtual controls should *force* pointing finger to not trigger hit actions.

**Comment by peppy** [comment]
To summarise:

The setting currently affects touch because touch is mapped to mouse input, not because it's explicitly disabling touch. Going forward, as we add proper touch support, this setting will no longer affect touch (because touch will not be mapped to mouse buttons).

I'm going to close this issue.
