### ISSUE TITLE
Nightcore Pitch

### ISSUE THREAD

**Issue by SimonDiamond** [ppy/osu#17478]
### Type

Game behaviour

### Bug description

With the addition to changing the tempo of both Double Time and Nightcore, I thought that it would make sense to have the pitch change with the according tempo with the nightcore mod, but, for whatever reason, it's not.

### Screenshots or videos

https://streamable.com/w5xkl8

### Version

2022.327.0-lazer

### Logs

Not really needed, but sure

[network.log](https://github.com/ppy/osu/files/8357335/network.log)
[performance.log](https://github.com/ppy/osu/files/8357336/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8357337/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8357338/updater.log)
[database.log](https://github.com/ppy/osu/files/8357339/database.log)

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/discussions/13125

<img width="920" alt="CleanShot 2022-03-27 at 13 20 50@2x" src="https://user-images.githubusercontent.com/22781491/160277002-28bedee6-8011-4216-a83d-203a6719abf0.png">
