### ISSUE TITLE
Click `Exit` in skin editor seem like the editor is not completely exit

### ISSUE THREAD

**Issue by HelloYeew** [ppy/osu#17489]
### Type

Game behaviour

### Bug description

When exit the skin editor using `Exit` on toolbar instead of using `Esc` or `Ctrl + Shift + S` (skin editor shortcut) make everything unclickable except toolbar.

**Step to reproduce :**
1. Get in skin editor
2. Click `Exit` on skin editor toolbar
3. Everything unclickable except in toolbar. (You can make everything back by using `Ctrl + Shift + S` or skin editor shortcut like you normally exit skin editor)

### Screenshots or videos

https://user-images.githubusercontent.com/68165621/160294696-0c0b3dc6-da8d-4585-929e-195b263b1154.mp4

### Version

2022.327.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8358198/runtime.log)

**Comment by bdach** [comment]
The menu item is calling `Hide()` one level too low:

https://github.com/ppy/osu/blob/8c5594b3eadd8afb6db153d0726eaa0b48359f02/osu.Game/Skinning/Editor/SkinEditor.cs#L110

Is calling `SkinEditor.Hide()`, should be calling `SkinEditorOverlay.Hide()`. Not sure why the two are allowed to be disparate `VisibilityContainer`s with uncoupled `State` to begin with.
