### ISSUE TITLE
Game crashing every time I click on singleplayer after I ticked this box

### ISSUE THREAD

**Issue by hairez** [ppy/osu#17493]
### Type

Crash to desktop

### Bug description

![image](https://user-images.githubusercontent.com/75111093/160298884-711fea3d-db30-48de-8d6b-bb04162ab124.png)

Ever since I clicked "show converted", the game crashes every time I click on "single player". 

I've tried to clear the caches, and uninstall + reinstalling the game, but the bug is still there. I can't find where I can untick the box, because I only that the only place where the box exists, is inside "single player".

### Screenshots or videos

![image](https://user-images.githubusercontent.com/75111093/160299109-b5af162b-4dab-4586-9a36-5e689785a0b1.png)

### Version

2022.327.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8358391/database.log)
[network.log](https://github.com/ppy/osu/files/8358392/network.log)
[performance.log](https://github.com/ppy/osu/files/8358393/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8358394/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8358395/updater.log)

**Comment by bdach** [comment]
i can see that you seem to have a custom ruleset installed:

```
2022-03-27 20:05:33 [verbose]: updating selection with beatmap:null ruleset:bosu!
```

can you try removing it and seeing if it fixes anything?

**Comment by EVAST9919** [comment]
Can confirm it's my ruleset's fault.

**Comment by bdach** [comment]
out of curiosity, what in particular broke it?

**Comment by EVAST9919** [comment]
Star rating was handled poorly, so there was a possibility of division by 0

**Comment by bdach** [comment]
thanks. not sure we should be guarding against NaN star rating, so i'm going to go ahead and close this.
