### ISSUE TITLE
Applying autoplay with shortcut while cinema mod applied cause both mods to apply.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#17508]
### Type

Game behaviour

### Bug description

Applying Autoplay with shortcut while Cinema mod applied cause both mods to apply and only(?) Cinema mod apply throughout the gameplay.

I think it should have priority on Autoplay mod instead.

*btw. Should applying Autoplay with shortcut also override any mods that incompatible with Autoplay?*

### Screenshots or videos

https://user-images.githubusercontent.com/7066150/160416379-7461688e-b0d0-49c1-b42d-9d706bd88e61.mp4

### Version

2022.327.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8363461/database.log)
[network.log](https://github.com/ppy/osu/files/8363462/network.log)
[performance.log](https://github.com/ppy/osu/files/8363463/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8363464/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8363465/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8363466/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8363467/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8363468/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8363469/updater.log)

**Comment by bdach** [comment]
As an aside, because in the new mod select design multi mods are no more, then unless they get brought back I'm likely going to be looking to adding incompatibility specs to all mods that are currently part of multi mods (because that's actually the only thing that makes them exclusive as things stand), which would encompass this case too.

**Comment by peppy** [comment]
> As an aside, because in the new mod select design multi mods are no more, then unless they get brought back I'm likely going to be looking to add incompatibility specs to all mods that are currently part of multi mods (because that's actually the only thing that makes them exclusive as things stand), which would encompass this case too.

I think that regardless of the future of "multi mod", the incompatibility spec should also include them as incompatible combinations.
