### ISSUE TITLE
Filtering in game settings does not respect localised labels

### ISSUE THREAD

**Issue by IsGris** [ppy/osu#17535]
### Type

Other

### Bug description

if you try to find something in the settings filter in English, it will work, but if you try to find the same thing in the language that is enabled in the settings, the filter will not work

### Screenshots or videos

![image](https://user-images.githubusercontent.com/83012795/160671727-d61367b1-c9f7-4743-ab32-3b33e1b19c3e.png)
![image](https://user-images.githubusercontent.com/83012795/160671737-a6bd6c96-2cec-44c8-9d3e-bace3ac9c740.png)

### Version

2022.327.0

### Logs

[network.log](https://github.com/ppy/osu/files/8373778/network.log)
[performance.log](https://github.com/ppy/osu/files/8373779/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8373780/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8373781/updater.log)
[database.log](https://github.com/ppy/osu/files/8373783/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8373784/legacy-ipc.log)

**Comment by Theighlin** [comment]
#14802?

**Comment by frenzibyte** [comment]
Indeed, closing as duplicate.
