### ISSUE TITLE
osu! crashes on startup on macOS (MacBook Air M1 (2020))

### ISSUE THREAD

**Issue by stanrunge** [ppy/osu#17548]
### Type

Crash to desktop

### Bug description

When opening osu!, the game immediately crashes to desktop.

### Version

2022.327.0

### Logs

[database.log](https://github.com/ppy/osu/files/8375964/database.log)
[network.log](https://github.com/ppy/osu/files/8375965/network.log)
[performance.log](https://github.com/ppy/osu/files/8375966/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8375967/runtime.log)

**Comment by stanrunge** [comment]
The Intel version runs fine

**Comment by peppy** [comment]
does the apple version still crash after running the intel version once? if so can you check Console.app for any errors when the crash occurs?

**Comment by stanrunge** [comment]
Ah it appears that running the Intel version made the Apple silicon version run fine

**Comment by peppy** [comment]
Good to hear. Probably will be fixed by https://github.com/ppy/osu/pull/17502.
