### ISSUE TITLE
"Classic" mod not implemented for catch and mania modes

### ISSUE THREAD

**Issue by Sans3108** [ppy/osu#17541]
### Type

Game behaviour

### Bug description

I used the Classic mod while playing in standard mode, and when I switched to mania, my main mode, I noticed the mod was greyed out/disabled.

I checked each of the game modes and it seems that for standard and taiko the mod appears ok, but for catch and mania the mod is un-usable.

### Screenshots or videos

Standard (Classic mod appears fine)
![osu_2022-03-29_23-40-36](https://user-images.githubusercontent.com/39863198/160703891-b41575be-1e47-4dac-998f-68ba84e6589d.jpg)

Taiko (Classic mod appears fine)
![osu_2022-03-29_23-40-45](https://user-images.githubusercontent.com/39863198/160703894-18a20a75-b05e-4456-80df-ede1faa7c8bc.jpg)

Catch (Classic mod is greyed out/disabled)
![osu_2022-03-29_23-40-50](https://user-images.githubusercontent.com/39863198/160703895-dedf8209-6244-473c-9774-3926f1e6e2da.jpg)

Mania (Classic mod is greyed out/disabled)
![osu_2022-03-29_23-40-54](https://user-images.githubusercontent.com/39863198/160703898-f90fba79-21aa-4625-9518-5dc7b386b951.jpg)

### Version

osu! 2022.327.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8374963/database.log)
[network.log](https://github.com/ppy/osu/files/8374964/network.log)
[performance.log](https://github.com/ppy/osu/files/8374965/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8374966/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8374967/updater.log)

**Comment by bdach** [comment]
they're greyed out because they're not implemented yet. i suppose there is no other open issue tracking that, so i'll leave open.

**Comment by Sans3108** [comment]
> all stable replays automatically receive the classic mod at import time for future compatibility.

Oh I see, but it's kind of confusing to see a mod applied when it doesn't exist yet.

**Comment by frenzibyte** [comment]
It is specifically applied to distinguish between legacy and lazer scores. A better UX might be to hide the mod from the mod select overlay entirely, until a purpose for it comes.

**Comment by peppy** [comment]
I think it's fine for now. Maybe we can just hide it in @bdach's new overlay if that makes more sense. Probably no need for a tracking issue.
