### ISSUE TITLE
Unable to click some menu buttons after exiting skin editor

### ISSUE THREAD

**Issue by daviskyLV** [ppy/osu#17542]
### Type

Other

### Bug description

After launching the skin layout editor from the settings menu, then going to edit song select and exiting the editor via file menu I'm unable to press any song select buttons or buttons in the main menu.

Note that I have a fresh install of osu!Lazer and I only changed some settings and haven't imported any beatmaps yet.

Steps to reproduce:
1. Open skin layout editor from settings menu
2. Go to song select
3. Exit via the file option at the top
4. Buttons don't work 
5. Press home button at the top
6. Buttons in main menu don't work either

Hardware & OS information:
Linux EndeavourOS, kernel: 5.16.16-arch1-1
KDE Plasma Desktop version 5.24.3
Intel i5-7500 CPU
NVIDIA RTX 2060 SUPER GPU
24GB RAM

### Screenshots or videos

https://user-images.githubusercontent.com/51496244/160707638-d9327585-37e7-4a74-8d17-e454bc027bec.mp4

### Version

2022.327.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8374938/runtime.log)
[performance.log](https://github.com/ppy/osu/files/8374940/performance.log)
[network.log](https://github.com/ppy/osu/files/8374941/network.log)
[database.log](https://github.com/ppy/osu/files/8374942/database.log)

**Comment by bdach** [comment]
#17489
