### ISSUE TITLE
Case sensitivity of file lookups

### ISSUE THREAD

**Issue by peppy** [ppy/osu#17595]
Right now, we are storing filenames to realm in a case sensitive way, but all lookups are done (for skins, beatmap etc.) ignoring case sensitivity.

As I work on the skin editor, where users are going to be importing more files into the game than before, I wonder how we should be handling this going forwards. For instance, right now the same file can be imported twice with different case, but only one is addressable by the user.

I believe the ignoring case part is there for compatibility with stable skins/resources. Should we ignore it for all "new" lookups?

Will self-assign this one so I don't lose track of it, but interested in thoughts on this.

**Comment by CenTdemeern1** [comment]
> Should we ignore it for all "new" lookups?

I am having trouble processing what this means
Does this mean ignoring case, or ignoring the standard set by stable?

**Comment by peppy** [comment]
Can be read either way, I think it's still the same question. My initial proposal would be to allow for case sensitive lookups going forward, if that is how we are going to store imported files. If not, we should probably be standardising at the point of import.

**Comment by CenTdemeern1** [comment]
Let's say someone started working on a skin in stable, and then moved to lazer.
How would the case-sensitive and case-insensitive items mix?
Would it be confusing to the user at all why some things are ignoring case and some things aren't?

**Comment by peppy** [comment]
Legacy skins are always legacy skins, and would never change in behaviour.

**Comment by CenTdemeern1** [comment]
Makes sense.
But maybe it should be noted in an info box somewhere or something if you are currently working with a legacy skin.

**Comment by bdach** [comment]
I would say that filename lookups should be case-insensitive, and my reason is very simple - things may start falling over on export otherwise depending on OS. Windows and macOS by default do not do in filename case sensitivity, as far as I'm aware, contrary to unix/linux. So being case-insensitive would be safer by catering to the lowest common denominator.

**Comment by peppy** [comment]
I'm okay with that direction, makes things a lot simpler. Would you agree with a migration to convert all existing realm filenames to lower-case and then applying that on import going forward?

**Comment by bdach** [comment]
I can agree with applying lowercase on import, but not too sure about backward migration. May cause issues if users already happened to have filenames that differ only in casing in their databases - although maybe that is fine to break...?

**Comment by peppy** [comment]
Any such files would already be failing in lookups, so I'm not sure that's a huge issue..

**Comment by bdach** [comment]
I suppose most legacy skins will be following the windows lower-case convention already, so maybe worth a shot adding a migration for it too in the end. Tough to say what the actual impact of potential breakage would be but it seems like it would be slim.

**Comment by peppy** [comment]
@smoogipoo can I get your confirmation on this before I attempt to tackle it?

To summarise: Currently we store case-sensitive filenames in realm but perform lookups with `IgnoreCase`. Can cause issues with the skin editor if a user imports two files with same name but different case.

Proposal: Migrate all filenames to lower case in realm and normalise on import for future imports. Importing a file in the skin editor with the same `filename.ToLower()` as an existing would overwrite it.

**Comment by smoogipoo** [comment]
I agree with migration + case-insensitivity.

**Comment by peppy** [comment]
One thing of note is that by normalising to lower-case, exporting beatmaps or skins would lose all capitalisation. This may actually be an issue for beatmaps if other systems expect the case to match. Not so sure anymore..

![MongoDB Realm Studio 2022-04-04 at 05 57 04](https://user-images.githubusercontent.com/191335/161482511-48c7f9ec-fffb-44f0-b176-1efb086cd163.png)

**Comment by smoogipoo** [comment]
Along the same lines - `.osu` files themselves can reference files (storyboard, video, background)...

**Comment by peppy** [comment]
Could you explain what you mean? I'm not sure I understand, are you agreeing with the previous comment that this is an issue?

**Comment by smoogipoo** [comment]
Yes I'm agreeing with the above.

**Comment by peppy** [comment]
Will close this and change the way I'm handling imports in #17596

**Comment by peppy** [comment]
Turns out this is already handled for adding files:

https://github.com/ppy/osu/blob/3e5c9e843606647561eb35541459386ecf54da20/osu.Game/Stores/RealmArchiveModelManager.cs#L79
