### ISSUE TITLE
In-game profile error

### ISSUE THREAD

**Issue by ChikoShidori** [ppy/osu#17612]
### Type

Other

### Bug description

My profile on osu lazer says I have 2k ranks and on the website it doesn't say anything (which is fine).

### Screenshots or videos

https://user-images.githubusercontent.com/53100578/161384917-d0f5d2ce-8e04-4450-91e8-c73b9c1e74ae.mp4

![](https://i.imgur.com/2uc2Kql.png)

### Version

2022.327.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8402575/database.log)
[network.log](https://github.com/ppy/osu/files/8402576/network.log)
[performance.log](https://github.com/ppy/osu/files/8402577/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8402578/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8402579/updater.log)

**Comment by bdach** [comment]
please link your profile.

**Comment by ChikoShidori** [comment]
https://osu.ppy.sh/u/chikoshidori

**Comment by bdach** [comment]
it appears that the website is - for some reason - intentionally changing the last value in the rank graph to the current global rank: https://github.com/ppy/osu-web/blob/77a53a2dd67720483c555505fe6b511f4ddc6d87/resources/assets/lib/profile-page/rank-chart.tsx#L56-L60

the 64.9k rank gain is even visible in the page source if you go look for it (search for `rank_history` and scroll to the end):

![2022-04-02-152812_157x50_scrot](https://user-images.githubusercontent.com/20418176/161385482-34f824b4-870b-48b4-82c2-d65dfe1c446e.png)

it's a bit weird that this data is apparently returned by API but sanitised post-facto on the front end, but alas. should be somewhat easily fixable in client too, if this is deemed the right approach.

**Comment by jai-x** [comment]
Related:
https://github.com/ppy/osu-web/issues/3966
https://github.com/ppy/osu-web/issues/3966

**Comment by bdach** [comment]
Yeah, just dug that up via blame too.

@nanaya since you fixed the original web-side instance, are you able to perhaps comment why this data in `rank_history` is returned from API at all if it's not supposed to be displayed? I can't see anything about it in the docs.

**Comment by nanaya** [comment]
It's replaced on osu-web because the current rank is also displayed somewhere (and the data is available). The data returned is technically correct as that number is what will be shown once the day changes.

As for the docs, the whole user object has been underdocumented 🤷

**Comment by peppy** [comment]
@nanaya how much would be involved in fixing this data at the api level? wondering if we should apply the same fix here or just fix it in osu-web. feels like even api consumers would expect the data to match what is shown on profile pages.

**Comment by nanaya** [comment]
Doable although that means the number may change during the day.

**Comment by peppy** [comment]
Yeah, I think that's what people would expect since that's how we've always exposed it.

**Comment by peppy** [comment]
https://github.com/ppy/osu-web/pull/8766
