### ISSUE TITLE
Spectating mid-gameplay calculates acc as if it's the start of the map

### ISSUE THREAD

**Issue by clxxiii** [ppy/osu#17610]
### Type

Game behaviour

### Bug description

If you join a multi and spectate while the lobby is already going, accuracy on the top right of each client will be calculated based on  the accuracy since you joined, contrary to the player list which displays the correct acc

### Screenshots or videos

![image](https://user-images.githubusercontent.com/46410314/161358069-ab3e887e-0098-4ac6-9723-f4a64e2de2f0.png)

![image](https://user-images.githubusercontent.com/46410314/161358197-eb08b5e7-19ca-4a01-b534-32dcb55bfeaf.png)

### Version

2022.128.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8401474/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8401475/updater.log)
[database.log](https://github.com/ppy/osu/files/8401476/database.log)
[network.log](https://github.com/ppy/osu/files/8401477/network.log)
[performance.log](https://github.com/ppy/osu/files/8401478/performance.log)

**Comment by Theighlin** [comment]
I think this is a duplicate of #14157 as in, hud elements act as if they were at the start of the map (score starts from 0 and acc from 100%)

**Comment by bdach** [comment]
> 2022.128.0-lazer

is this correct? are you really on a lazer build from _january_?

if yes then please upgrade. this has since been fixed in https://github.com/ppy/osu/pull/16722 (2022.205.0 release or higher).

**Comment by clxxiii** [comment]
My apologies, I was on the wrong build, this has been fixed since then
