### ISSUE TITLE
Skin name repeats when deleting and re-adding skin

### ISSUE THREAD

**Issue by JamieWright99** [ppy/osu#17614]
### Type

Game behaviour

### Bug description

I found this bug while I was importing some skins. I made a mistake when making a skin so I deleted them from lazer, and the naming format for the skin seemed to duplicate itself as I kept deleting and re-adding. 

Here's a video: https://streamable.com/f9q5rz

I checked the skin.ini file from the exported skin and it seems that the skin was making another Name and Author line for each time I exported the skin.

### Screenshots or videos

![osu! Skin Name Duplicate](https://user-images.githubusercontent.com/102170503/161390293-5d6ba23c-de18-44ed-bb60-dd76cfc9c519.png)

### Version

2022.327.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8402830/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8402831/updater.log)
[database.log](https://github.com/ppy/osu/files/8402832/database.log)
[network.log](https://github.com/ppy/osu/files/8402833/network.log)
[performance.log](https://github.com/ppy/osu/files/8402834/performance.log)

**Comment by bdach** [comment]
Can you attach any of these skin copies to this report?

This is hitting an intentional code path (intended to address people importing skins where the `.osk` has a different name than the skin name inside of `skin.ini` in the actual archive), but it should probably not be happening over and over again after the first time.

**Comment by JamieWright99** [comment]
Here's a download link to one of the skins: https://www.mediafire.com/file/7j25v3b89bmjadi/Cookiezi_Red_%2528Seouless%2529.osk/file

I'll ad that removing the author '(Seouless)' from the skin file name seems to fix this issue, but it will occur again if you don't remove the author name from the exported skin.
