### ISSUE TITLE
hitsounds not working anymore

### ISSUE THREAD

**Issue by crumpledmint** [ppy/osu#17626]
### Type

Game behaviour

### Bug description

Today skins that contain .ogg files for hitsounds are not working properly. All .ogg sounds are replaced with ones from standard skin
Yesterday all worked fine and I tried restarting my pc but it didn't changed anything

### Version

Stable 20220323

### Logs

[runtime.log](https://github.com/ppy/osu/files/8404329/runtime.log)
[session.log](https://github.com/ppy/osu/files/8404330/session.log)
[update_success.log](https://github.com/ppy/osu/files/8404331/update_success.log)

**Comment by crumpledmint** [comment]
It's not only .ogg
After I restarted my pc .wav sounds were also replaced with the standard ones

**Comment by bdach** [comment]
> Stable 20220323

did you perhaps miss this?

![2022-04-03-132108_1578x439_scrot](https://user-images.githubusercontent.com/20418176/161425397-d8a76df2-95f3-4b20-a3bc-0da9d6e8acaf.png)

closing as this repository is specific to lazer and stable reports are not allowed here.

**Comment by crumpledmint** [comment]
Yep, sorry, I'm dumb
