### ISSUE TITLE
Osu android

### ISSUE THREAD

**Issue by Rystars** [ppy/osu#17639]
### Type

Game behaviour

### Bug description

The osu circle cannot be pressed/slipped without the Relax mode

### Screenshots or videos

![Uploading Screenshot_2022-04-04-05-59-24-207_sh.ppy.osulazer.jpg…]()

### Version

2022.327.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8405884/database.log)
[network.log](https://github.com/ppy/osu/files/8405885/network.log)
[performance.log](https://github.com/ppy/osu/files/8405886/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8405887/runtime.log)

**Comment by peppy** [comment]
Check your key bindings and make sure you do t have mouse buttons disabled.

**Comment by Rystars** [comment]
![Screenshot_2022-04-04-09-49-00-894_sh ppy osulazer](https://user-images.githubusercontent.com/96302690/161466017-dd921aab-74e7-475f-843d-e94d26ecafdc.jpg)

is this one?
