### ISSUE TITLE
A lot of strings are not localizable 

### ISSUE THREAD

**Issue by CenTdemeern1** [ppy/osu#17637]
### Type

Other

### Bug description

A lot of strings are unavailable for localization on Crowdin, and are not going through the localization system.

### Version

2022.327.0-lazer

### Logs

N/A

**Comment by CenTdemeern1** [comment]
I know this is a very dumb issue to report but I’d still like some kind of progress to be tracked somewhere and would like to have some place to discuss this.
I akso didn’t put this in the GH discussions tab because this is neither an idea or a question, this is a problem.

**Comment by peppy** [comment]
You are welcome to add more. This doesn’t require an issue tracking it.
