### ISSUE TITLE
Lag spikes when you're playing beatmap for first time in session

### ISSUE THREAD

**Issue by pscr00ge** [ppy/osu#17633]
### Type

Performance

### Bug description

literally lag spikes
i think that video will explain everything

### Screenshots or videos

https://vimeo.com/695479099

### Version

2022.327.0

### Logs

[database.log](https://github.com/ppy/osu/files/8405415/database.log)
[network.log](https://github.com/ppy/osu/files/8405416/network.log)
[performance.log](https://github.com/ppy/osu/files/8405417/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8405418/runtime.log)

**Comment by peppy** [comment]
Does this happen with the default skin? Often when we see this kind of lag, it's due to having a weird skin loaded.

**Comment by pscr00ge** [comment]
any skin, triangles just giving me smaller amount fps due poor gpu

**Comment by peppy** [comment]
Right, you're on android.

We're still working on optimising things over there. You should see performance get better over time.
