### ISSUE TITLE
When I start playing with TABLET ONLY my cursor locks to the right side of the screen

### ISSUE THREAD

**Issue by Danniel2527** [ppy/osu#17655]
### Type

Game behaviour

### Bug description

Started when I updated it, before my tablet worked perfectly fine, but recently started acting up. Osu! Lazer doesn't detect my tablet. It works in the main menu and just before I play a map, but as soon as the first hit circles appears my cursor locks to the right. But for some reason my tablet stars working after I turn off High Precision Mouse. I use a Gaomon s620 btw 

### Version

osu! 2022.327.O-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8414149/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8414150/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8414151/network.log)
[performance.log](https://github.com/ppy/osu/files/8414152/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8414153/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8414154/updater.log)

**Comment by peppy** [comment]
Please leave high precision mouse off. Or use the in-game tablet controls.
