### ISSUE TITLE
Closing game does not close all processes

### ISSUE THREAD

**Issue by WoahdangJr142** [ppy/osu#17654]
### Type

Game behaviour

### Bug description

When closing osu!(lazer) it does not close all processes, leading to things such as using ~10% of my CPU and making things like discord think I'm playing the game until I end the process in task manager or restart PC.

### Version

Latest osu!(lazer) (as of 4/4/2022)

### Logs

[performance.log](https://github.com/ppy/osu/files/8413560/performance.log)
[updater.log](https://github.com/ppy/osu/files/8413561/updater.log)
[database.log](https://github.com/ppy/osu/files/8413562/database.log)
[network.log](https://github.com/ppy/osu/files/8413563/network.log)
[runtime.log](https://github.com/ppy/osu/files/8413564/runtime.log)

**Comment by peppy** [comment]
Last time this came up it was overwolf causing the issue. Can you confirm you don’t use that app? Also can you give a brief list of other apps on your system to hat may be interacting with osu!?

**Comment by WoahdangJr142** [comment]
I do have overwolf, but osu! is disabled in settings, and I don't see an osu!(lazer).

Other than that I have Razer Cortex and MSI Center that I can think of off the top of my head.

**Comment by peppy** [comment]
Can you try killing overwolf and see if it still happens? ie. end the process completely.

**Comment by WoahdangJr142** [comment]
I did, and it is still showing up in discord. Here is an image of my taskbar.
![image](https://user-images.githubusercontent.com/68622581/161659062-5cba254e-a481-424f-a107-88ed29f844dd.png)

**Comment by peppy** [comment]
Did you also end the osu! process once? To clarify, closing overwolf won't fix the stuck process, but it shouldn't get stuck next time you run osu! fresh.

**Comment by WoahdangJr142** [comment]
Yes. I closed osu! process, overwolf processes, and launched osu!(lazer). I then ended osu!(lazer) process and started and closed again. same issue.

**Comment by peppy** [comment]
Are you able to email me a memory dump when osu! is in the stuck state?

You can create it from the task manager process list by right clicking on the stuck osu! process and choosing "Create memory dump". As it may contain confidential information, I recommend you email it to me (pe@ppy.sh).

**Comment by WoahdangJr142** [comment]
Done.

**Comment by peppy** [comment]
```csharp
Not Flagged	>	33544	1	Main Thread	Main Thread	combase.dll!CCliModalLoop::BlockFn
 	 	 	 	 	 	[External Code]
```

On a quick [google search](https://www.google.com/search?q=+combase.dll%21CCliModalLoop%3A%3ABlockFn&client=safari&rls=en&ei=qLRLYq2CGLHdmAXYvbjoBw&ved=0ahUKEwit9vnq-vv2AhWxLqYKHdgeDn0Q4dUDCA0&uact=5&oq=+combase.dll%21CCliModalLoop%3A%3ABlockFn&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGAFKBAhGGABQ3hBY6jRgrTdoAXAAeACAAUaIAYsEkgEBOZgBAKABAcABAQ&sclient=gws-wiz) there are other applications hitting a similar issue. One looks addon related, but others mention the clipboard directly.

Can you confirm that this happens regardless of whether you use the clipboard in the game? We don't look to be directly interacting with the clipboard unless explicitly requested by the user (although SDL may be?)

**Comment by peppy** [comment]
Also not sure if related, but analysing the dump in VS gives the following warnings:

![Parallels Desktop 2022-04-05 at 03 21 24](https://user-images.githubusercontent.com/191335/161672515-ef9b9882-4ae2-4883-a345-3dde8553cf0b.png)

**Comment by smoogipoo** [comment]
Re: Finalizer: Are you able to load the dump into dotMemory and see what objects are in the finalizer queue? It usually shows this type of info in the main page:
![image](https://user-images.githubusercontent.com/1329837/161684052-94b05c70-f920-4d43-a714-8928dda9846e.png)

**Comment by peppy** [comment]
![Parallels Desktop 2022-04-05 at 05 24 06](https://user-images.githubusercontent.com/191335/161684494-3a92208b-a651-4e21-8100-94261509ad62.png)

**Comment by peppy** [comment]
Types:

![Parallels Desktop 2022-04-05 at 05 28 27](https://user-images.githubusercontent.com/191335/161684937-96a762ae-5521-4c5d-a382-b0982dbf8841.png)

**Comment by NotGumballer91** [comment]
This also happens to me as well. CPU usage wasn't the problem except for discord. It shows that I'm that playing osu as well.

![image](https://user-images.githubusercontent.com/64581009/161779260-f73a9532-fd88-4378-9ac4-57fbc438d0ad.png)

@WoahdangJr142 I've found a workaround for discord. You don't have to completely restart it. All you need to do is just change your status to Invisible and back to Online.

**Comment by WoahdangJr142** [comment]
> ```cs
> Not Flagged	>	33544	1	Main Thread	Main Thread	combase.dll!CCliModalLoop::BlockFn
>  	 	 	 	 	 	[External Code]
> ```
> 
> On a quick [google search](https://www.google.com/search?q=+combase.dll%21CCliModalLoop%3A%3ABlockFn&client=safari&rls=en&ei=qLRLYq2CGLHdmAXYvbjoBw&ved=0ahUKEwit9vnq-vv2AhWxLqYKHdgeDn0Q4dUDCA0&uact=5&oq=+combase.dll%21CCliModalLoop%3A%3ABlockFn&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGAFKBAhGGABQ3hBY6jRgrTdoAXAAeACAAUaIAYsEkgEBOZgBAKABAcABAQ&sclient=gws-wiz) there are other applications hitting a similar issue. One looks addon related, but others mention the clipboard directly.
> 
> Can you confirm that this happens regardless of whether you use the clipboard in the game? We don't look to be directly interacting with the clipboard unless explicitly requested by the user (although SDL may be?)

I have not used clipboard in the game.

**Comment by WoahdangJr142** [comment]
> This also happens to me as well. CPU usage wasn't the problem except for discord. It shows that I'm that playing osu as well.
> 
> ![image](https://user-images.githubusercontent.com/64581009/161779260-f73a9532-fd88-4378-9ac4-57fbc438d0ad.png)
> 
> @WoahdangJr142 I've found a workaround for discord. You don't have to completely restart it. All you need to do is just change your status to Invisible and back to Online.

Well, CPU is a problem for me haha it uses ~12% of my r5 5600g

**Comment by WoahdangJr142** [comment]
I just opened and closed the stable release of the game as well, and it did the same thing.

**Comment by peppy** [comment]
If it's also happening in stable there has to be something more to this. Please try shutting down any other apps on your pc (including system tray apps) and see if it still happens.

**Comment by WoahdangJr142** [comment]
I believe it could have been Medal.tv

**Comment by WoahdangJr142** [comment]
I believe after the last update, (not the one I just got today), it fixed the issue.
