### ISSUE TITLE
Beatmap import  from osu! stable installation failing with SQLite Error 19

### ISSUE THREAD

**Issue by Cynplytholowazy** [ppy/osu#1766]
Updating from 2017.1208.0

![capture](https://user-images.githubusercontent.com/31384149/34362070-37fbcabe-eaab-11e7-8402-0ff5e5ce4d13.JPG)

![capture](https://user-images.githubusercontent.com/31384149/34362128-d64b7afc-eaab-11e7-864f-dc02fc624ca8.JPG)

![capture](https://user-images.githubusercontent.com/31384149/34362124-bb5101a4-eaab-11e7-848d-c059620b9f54.JPG)

The above message pops up whenever osu!lazer try to import beatmaps from the osu! stable installation.

My osu! installation lies on D:\osu! while osu!lazer are in C:\Users\user\Appdata\local\osulazer. I wonder if this would mater.

**Comment by Aergwyn** [comment]
Already known as seen in https://github.com/ppy/osu/issues/1566

**Comment by Cynplytholowazy** [comment]
The new feature tho...

**Comment by Aergwyn** [comment]
It's just a dialog in front of regular import. The shown error points to the issue as already mentioned.

**Comment by peppy** [comment]
Duplicate of #1566.
