### ISSUE TITLE
Osu not running

### ISSUE THREAD

**Issue by JankoDB** [ppy/osu#17672]
### Type

Crash to desktop

### Bug description

I have this issue that i've played osu!lazer like 6 months ago it was running then and when i downloaded it again like 2 days ago i tried installing it, but whenever i tried playing it. It would like the program is on loading cursor but again nothing happens. And if open the update application in appdata>local>osulazer. A cmd window flashes very fast and i cannot see what's written in it.
Can someone help me somehow, please?

### Screenshots or videos

-

### Version

-

### Logs

[runtime.log](https://github.com/ppy/osu/files/8422140/runtime.log)

**Comment by smoogipoo** [comment]
Lazer requires Windows 8.1 at minimum.
