### ISSUE TITLE
Stacked Sliders behave differently with classic mod than how they do in stable

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#17675]
This appears to be a difference in how notelock is implemented, but needs more investigation to confirm. Also refer to https://github.com/ppy/osu/discussions/17362#discussioncomment-2433499 for a replay where this occurs.

### Discussed in https://github.com/ppy/osu/discussions/17667

<div type='discussions-op-text'>

<sup>Originally posted by **MrWither83** April  6, 2022</sup>
I noticed while playing on lazer (with classic mod) that something was off with sliders during gameplay.

Essentially, on stable, the second slider doesn't accept input until the first one is finished, while in lazer the second slider accepts input as soon as the sliderhead of the first slider has been clicked.

I managed to isolate the issue on a short beatmap with only two sliders. In both clips, I click both keys on the first slider then click one key on the second slider. Notice how stable ignores one of the first two hits, while lazer registers a sliderbreak on the second slider.

**Stable :** 

https://user-images.githubusercontent.com/52672543/161821612-e120670b-20e9-4026-8600-80afe1e9d134.mp4

**Lazer :**

https://user-images.githubusercontent.com/52672543/161821617-f0a03c09-c555-4da0-92e0-7990450ebc2a.mp4

I think this is the issue behind the "strange slider miss" mentioned here : https://github.com/ppy/osu/discussions/17362#discussioncomment-2433499</div>

**Comment by ackhack** [comment]
Just came across this issue, wanted to add that the second object can be a circle aswell. So it is not restricted to stacked silders, but to any stack that contains a slider before another object.

**Comment by WitherFlower** [comment]
Just bumping this for the sake of visibility, as this needs to me considered before locking in scoring and gameplay mechanics.
