### ISSUE TITLE
Editing and playing can still be used when osu!lazer has no beatmap, which results in crash.

### ISSUE THREAD

**Issue by Cynplytholowazy** [ppy/osu#1767]
osu!lazer 2017.1226.0

Starting osu!lazer, default it has no beatmap, and the osu! main theme song will be played.
Enter solo mode, and no beatmaps available will show up.
If you press the play button osu!lazer will crash.
If you enter editor, clicking on the timeline will result in a crash as well.
May need to disable play and edit mode when no beatmaps are present.

**Comment by Aergwyn** [comment]
Regarding play: Known as in https://github.com/ppy/osu/issues/1719
Editor is still WIP

**Comment by peppy** [comment]
This seems to be a new regression separate to #1719.
