### ISSUE TITLE
Boardless Mode Bug 

### ISSUE THREAD

**Issue by Ne0W0r1d** [ppy/osu#17680]
### Type

Crash to desktop

### Bug description

Just so titles
I accidentally pressed F11
It is changed display mode to Windows
I pressed again F11
It is changed display mode to Boardless
And then it is crash again and again

### Screenshots or videos

![image](https://user-images.githubusercontent.com/93416867/161928869-8fafcd0b-9753-49bf-8a97-0ecf3a069149.png)

### Version

2022.405.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/8424965/logs.zip)

**Comment by bdach** [comment]
not sure what "boardless mode" is supposed to be but you should try updating your graphics card drivers as they are the thing that's crashing here
