### ISSUE TITLE
Skin-sourced image files are inaccessible in storyboard if suffixed with extension in .osu file

### ISSUE THREAD

**Issue by CenTdemeern1** [ppy/osu#17690]
### Type

Cosmetic

### Bug description

I tried playing [Time Traveler](https://osu.ppy.sh/beatmapsets/1236988#osu/2573493) and it seems that skin-sourced image files seem to have broken on lazer recently. (It worked the last time I viewed the map, which was quite a bit ago)

### Screenshots or videos

![image_133](https://user-images.githubusercontent.com/24682280/162051445-9e2aea02-a163-48e7-a80e-2b74de024e0c.png)

Video: https://youtu.be/Q7aIi8dHwGY
For some reason, the visual "missing sprite" indicators (shown in the screenshot) stopped appearing after a restart, and there was no trace of the sprites left anymore. (shown in the video)

### Version

2022.405.0-lazer, local debug on 2c8fcadb9738df7dbaa42b5c2c58e5e6d80b68cc

### Logs

[database.log](https://github.com/ppy/osu/files/8429965/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8429966/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8429967/network.log)
[performance.log](https://github.com/ppy/osu/files/8429968/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8429969/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8429970/updater.log)

**Comment by bdach** [comment]
already reported and root-caused in https://github.com/ppy/osu/discussions/17062

**Comment by CenTdemeern1** [comment]
Man and I looked so hard for dupes too

**Comment by bdach** [comment]
going to reopen as it's an actual issue that needs fixing, but the cause is described in detail in https://github.com/ppy/osu/discussions/17062#discussioncomment-2301700 and https://github.com/ppy/osu/discussions/17062#discussioncomment-2301890

**Comment by CenTdemeern1** [comment]
Oh wait the other thing is a discussion not an issue

**Comment by CenTdemeern1** [comment]
I showed off in the video that this problem exists on *any* skin, not just the default one. Renaming issue.

**Comment by peppy** [comment]
To clarify here, this has always been broken but is more visible now due to the not found sprite (which I think is better than having these issues hidden). I'm going to look at applying a fix as proposed in #17062.
