### ISSUE TITLE
Positional hitsounds don't update with mods that change the position of hit objects

### ISSUE THREAD

**Issue by not-so-smart** [ppy/osu#17719]
### Type

Game behaviour

### Bug description

When using mods like Barrel Roll or Magnetised, stereo hitsounds are played from their original position rather than their adjusted position.

**Repro steps:** _(set "hitsound stereo separation" to 100% for best results)_
1. turn on barrel roll mod
2. play any map, wait for the screen to turn upside down and listen to where the hitsounds are coming from

or
1. turn on magnetised mod, set attraction strength to 100%
2. play any map, put your cursor all the way to one side of the screen and tap along, leaving your cursor in place

**Expected:**
positional hitsounds play from the position they appear at on the playfield

**Actual:**
all hitsounds are played as if the notes were in their original positions without taking into account the rotation of the playfield / movement of notes / etc.

### Version

2022.405.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/8448777/network.log)
[performance.log](https://github.com/ppy/osu/files/8448778/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8448779/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8448780/updater.log)
[database.log](https://github.com/ppy/osu/files/8448781/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8448782/legacy-ipc.log)

**Comment by peppy** [comment]
The best probable fix for this is using screen-space coordinates at the point of sample playback.

**Comment by frenzibyte** [comment]
One way I can think of without directly accessing the parenting hit object container is:
```diff
diff --git a/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs b/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
index a1c8879105..5a2a1967df 100644
--- a/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
+++ b/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
@@ -9,7 +9,6 @@
 using osu.Game.Rulesets.Judgements;
 using osu.Game.Rulesets.Osu.Judgements;
 using osu.Game.Graphics.Containers;
-using osu.Game.Rulesets.Osu.UI;
 using osuTK;

 namespace osu.Game.Rulesets.Osu.Objects.Drawables
@@ -24,7 +23,9 @@ public class DrawableOsuHitObject : DrawableHitObject<OsuHitObject>
         // Must be set to update IsHovered as it's used in relax mod to detect osu hit objects.
         public override bool HandlePositionalInput => true;

-        protected override float SamplePlaybackPosition => HitObject.X / OsuPlayfield.BASE_SIZE.X;
+        protected override float SamplePlaybackPosition => ScreenSpaceDrawQuad.Centre.X / parentScreenSpaceWidth;
+
+        private float parentScreenSpaceWidth => ((DrawableOsuHitObject)ParentHitObject)?.parentScreenSpaceWidth ?? Parent.ScreenSpaceDrawQuad.Width;

         /// <summary>
         /// Whether this <see cref="DrawableOsuHitObject"/> can be hit, given a time value.
```

Would that look tolerable at a first glance? feels fine, but might only be me.

**Comment by peppy** [comment]
Does this work with something like barrel roll? It seems like it may not be pinned high enough in the hierarchy (should be comparing to a fixed container that is not affected by any mods.

**Comment by frenzibyte** [comment]
> Does this work with something like barrel roll? It seems like it may not be pinned high enough in the hierarchy (should be comparing to a fixed container that is not affected by any mods.

I would expect it to work given that this is all computed at a screen-space level, but I haven't precisely checked that yet.

**Comment by peppy** [comment]
Right, I guess as long as it's using `.Width` it may work okay (cancels out any rotation applied, at least).
