### ISSUE TITLE
Relax plays update profile max combo statistic (and probably shouldn't)

### ISSUE THREAD

**Issue by ChaBoiNeil** [ppy/osu#17718]
### Type

Game behaviour

### Bug description

https://osu.ppy.sh/users/21251392
https://osu.ppy.sh/beatmapsets/930865#osu/1943817

I played with relax on "Forget Not - Ne Oblivisaris" and managed to get a combo of x2356 my previous maximum combo was x1017 set on Stable on "Sound Chimera - Laur." I have played ranked maps with relax on stable with combos around 1300-1500 , but none of them would transfer to my profile. I set this play on Lazer and it wasn't till minutes later that I checked my profile to see that my max combo had updated to this. I don't know if this is a Lazer issue that shouldn't be, or if this is working as intended.

Either way I didn't receive the achievement for 2000 combo. I hope this didn't bug out my profile and I'll never be able to get it now. I thought to try playing an unranked "cheese map" to get a high combo by doing basically nothing, but I didn't want to fudge my profile up even more lol.

### Version

2022.405.0

### Logs

N/A

**Comment by peppy** [comment]
We had previous discussion whether automation mods should be excluded from such stats (in https://github.com/ppy/osu/discussions/17319). I think there's a general agreement that that should be the case.

I'll look at applying a change to exclude automation mods in the stats processor unless there are any differing opinions.

**Comment by peppy** [comment]
I'm looking to apply this as above, but not 100% about whether "spun out" should also not count. Blanket disabling max combo statistics for automation seems like the best move, which would include that mod too. @smoogipoo thoughts?
