### ISSUE TITLE
Customisation UI goes in front of mods

### ISSUE THREAD

**Issue by soopax** [ppy/osu#17710]
### Type

Cosmetic

### Bug description

The customisation UI can obscure certain mod options, which makes them hard to select.
Easy workaround is to close the customisation menu. Alternatively click slightly above/below the menu.
Screen resolution: 2560 × 1440

### Screenshots or videos

![osu_2022-04-07_16-03-32](https://user-images.githubusercontent.com/101510334/162209919-cef249b3-40db-4fa7-a4e6-c6c057fa3b15.png)

### Version

2022.405.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8443253/database.log)
[network.log](https://github.com/ppy/osu/files/8443254/network.log)
[performance.log](https://github.com/ppy/osu/files/8443255/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8443256/runtime.log)

**Comment by frenzibyte** [comment]
A redesign is ongoing for the mods select overlay, in which the mods customization overlay is on a separate panel from the mod buttons (see https://github.com/ppy/osu/issues/16917).
