### ISSUE TITLE
Osu android doesn't register any clicks

### ISSUE THREAD

**Issue by chicco-carone** [ppy/osu#17758]
### Type

Game behaviour

### Bug description

If i try playing any maps the game doesn't recognize clicks. I tried changing the keys in the settings and there it recognize the key but in game no. I tried relax and the aim works but autopilot doesn't work. Since i found this bug there were 5 updates but none of them fixed this.
My phone: Oppo find x3 lite

### Screenshots or videos

[https://drive.google.com/file/d/1j6fG47Nk0kzLxKiU3OPAXNq301u3yHsk/view?usp=sharing](url)
[https://drive.google.com/file/d/1j1UNWTGVNAM9h5tONz32L0Xzs8CZVJF2/view?usp=sharing](url)
The videos were too bis so i uploaded them into google drive

### Version

Osu! 2022.409.0-lazer

### Logs

There weren't any folder in Android/data/

**Comment by Susko3** [comment]
Reset your keys to default (so it's `M1` and `M2`) and then disable "disable mouse buttons" (make sure mouse buttons are enabled).
That setting also disables touch input.

**Comment by chicco-carone** [comment]
> Reset your keys to default (so it's `M1` and `M2`) and then disable "disable mouse buttons" (make sure mouse buttons are enabled). That setting also disables touch input.

I searched and there isn't an option called "disable mouse buttons" and in the pc version there is

**Comment by Susko3** [comment]
That option is coming with #16464 to regular settings.

For now, you can toggle it while starting a beatmap.
![image](https://user-images.githubusercontent.com/16479013/162614406-215f4dca-56ca-4f5f-a3ab-d189bd3565c0.png)

**Comment by chicco-carone** [comment]
> That option is coming with #16464 to regular settings.
> 
> For now, you can toggle it while starting a beatmap. ![image](https://user-images.githubusercontent.com/16479013/162614406-215f4dca-56ca-4f5f-a3ab-d189bd3565c0.png)
Thanks for the help
