### ISSUE TITLE
Lazer crashing when I'm changing my In-game keybinds.

### ISSUE THREAD

**Issue by Soetch** [ppy/osu#17768]
### Type

Crash to desktop

### Bug description

I was looking for the bindings in the options and when I found it and clicked on it, osu! stopped functionning and has closed. I was using a graphic tablet to click on the UI Element in the options.

The application lost performance and crashed afterwards.

### Version

2022.409.0

### Logs

[database.log](https://github.com/ppy/osu/files/8463259/database.log)
[network.log](https://github.com/ppy/osu/files/8463260/network.log)
[performance.log](https://github.com/ppy/osu/files/8463261/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8463262/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8463263/updater.log)

**Comment by jai-x** [comment]
Your log files do not contain the crash info.
Please make sure after you've reproduced the crash to not re-open osu! since the log files are cleared on startup.

**Comment by Soetch** [comment]
![Screenshot_20220411_144622.jpg](https://user-images.githubusercontent.com/70801309/162742270-75891bd3-e5ab-440f-aa18-2c6e067ae574.jpg)

I did put it in actually

**Comment by peppy** [comment]
Please read the last message once more, carefully.

**Comment by Soetch** [comment]
> Please read the last message once more, carefully. Your logs contain no crash.

In facts it was a freeze then it closed

**Comment by Soetch** [comment]
Nevermind, it maybe has to do with the first boot of the game. 
Thanks for your replies.
