### ISSUE TITLE
Unknown mod shown in some mods

### ISSUE THREAD

**Issue by tacozyt** [ppy/osu#17777]
### Type

Other

### Bug description

**CONTEXT**: I was looking at the mods list, until I saw an unknown mod in the incompatible mods list.

I started to see which mods had this unknown mod on the incompatible list.

I searched for the unknown mod but saw that it is not in the list of mods.
It was a mod with a yellow like icon (color of difficulty increase)

### Screenshots or videos

Here is the list of mods with this mod icon

![mods affected](https://user-images.githubusercontent.com/84425557/162807924-6dc41d18-3b89-42c7-90b8-05e9d4aec736.png)

Here the unknown mod unavailable in osu!
![incompatible list](https://user-images.githubusercontent.com/84425557/162807925-de79c6d0-443b-455a-bde3-e5acd42be5d3.png)

### Version

2022.409.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8466920/database.log)
[network.log](https://github.com/ppy/osu/files/8466921/network.log)
[performance.log](https://github.com/ppy/osu/files/8466922/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8466923/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8466924/updater.log)

**Comment by Susko3** [comment]
That's the perfect mod. (hint: click sudden death twice)

![image](https://user-images.githubusercontent.com/16479013/162810382-7c1bf658-7769-4582-b808-193c7459abe3.png)

**Comment by frenzibyte** [comment]
As per above, that's not an unknown mod, that's the "Perfect" mod, stacked with the "Sudden Death" mod. This may be improved in the redesigned variant, where mod stacks may not be a thing and all mods will be shown separately (see https://github.com/ppy/osu/issues/16917).

**Comment by tacozyt** [comment]
xddddddddddddddddddddddddd

**Comment by tacozyt** [comment]
im a little dumb

**Comment by tacozyt** [comment]
> That's the perfect mod. (hint: click sudden death twice)
> 
> ![image](https://user-images.githubusercontent.com/16479013/162810382-7c1bf658-7769-4582-b808-193c7459abe3.png)

![osu_2022-04-11_14-06-46](https://user-images.githubusercontent.com/84425557/162811993-dafee080-c186-4da4-b22c-1cd458c1fbea.png)

Yes

**Comment by bdach** [comment]
@tacozyt please stop spamming comments, thanks
