### ISSUE TITLE
Delete buttons don't behave as dangerous buttons when clicking on the edge

### ISSUE THREAD

**Issue by aplefull** [ppy/osu#17774]
### Type

Game behaviour

### Bug description

Delete buttons perform action instantly instead of asking to hold when clicked like in a video. Works on deleting beatmaps and local scores. Haven't tested mass delete, but I assume it's the same. 

### Screenshots or videos

https://user-images.githubusercontent.com/10453915/162784777-6a34e70a-c556-482d-9f5e-50fbe4c4dd85.mp4

### Version

2022.409.0

### Logs

[performance-audio.log](https://github.com/ppy/osu/files/8465992/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8465993/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/8465994/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8465995/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8465996/updater.log)
[database.log](https://github.com/ppy/osu/files/8465997/database.log)
[network.log](https://github.com/ppy/osu/files/8465998/network.log)
[performance.log](https://github.com/ppy/osu/files/8465999/performance.log)

**Comment by tacozyt** [comment]
You need to hold the button to delete a song in osu!lazer
