### ISSUE TITLE
`ScoreProcessor` returns `double` scores, but scores are always displayed as integer

### ISSUE THREAD

**Issue by peppy** [ppy/osu#17783]
Returns of methods such as `ComputeScore` are `double` right now:

https://github.com/ppy/osu/blob/5ec2d86c094e26f1c2663047ba895c47271b9d6c/osu.Game/Rulesets/Scoring/ScoreProcessor.cs#L347

Meanwhile, we apply rounding in local usages like `MultiplayerGameplayLeaderboard`, potentially leading to discrepancies in calculation and display. Consider that for tournaments, a one point difference can be quite important. If osu-web is getting floored results but the leaderboard is rounding, that would cause an issue.

https://github.com/ppy/osu/blob/9c19ae1df8061373e8a2f9481d17885def75d691/osu.Game/Screens/Play/HUD/MultiplayerGameplayLeaderboard.cs#L195

It seems on initial investigation that scores should always be returned as integer by the `ScoreProcessor`, not double.

**Comment by bdach** [comment]
As far as I can tell, resolved by #21140.
