### ISSUE TITLE
the score doesn't submit

### ISSUE THREAD

**Issue by GabubuAvailable** [ppy/osu#17795]
### Type

Other

### Bug description

well... that's not a bug (ig) but everytime when i finish playing a beatmap, the score doesn't submit.

### Screenshots or videos

the score when i was on classic: 
![image](https://user-images.githubusercontent.com/88589756/163030964-746cdc64-8696-4463-9c71-994a45f40d61.png)

------------------------------------------------------------------
the score when i made on osu!lazer:
![image](https://user-images.githubusercontent.com/88589756/163031074-1d51c4ec-0eac-444a-88e1-1694904e3caa.png)

### Version

2022.409.0

### Logs

[database.log](https://github.com/ppy/osu/files/8475678/database.log)
[network.log](https://github.com/ppy/osu/files/8475679/network.log)
[performance.log](https://github.com/ppy/osu/files/8475680/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8475681/runtime.log)

**Comment by bdach** [comment]
it submitted. check your profile: https://osu.ppy.sh/users/17971421

what you mean is that it doesn't overwrite the play from stable on the leaderboards. this is known, and there is ongoing background work that will make this happen eventually.

please read: https://osu.ppy.sh/home/news/2022-03-07-community-meetings-recap
