### ISSUE TITLE
importing skins from stable in multiplayer doesn't work and disables button

### ISSUE THREAD

**Issue by respektive** [ppy/osu#17793]
### Type

Game behaviour

### Bug description

The same is true for the other `import from stable` buttons.

This might not be an issue on Windows where lazer can find the current stable install, but I can't test this rn.

### Screenshots or videos

https://user-images.githubusercontent.com/22381687/162985265-0bee0e80-d221-4603-bd73-94c0910f88b3.mp4

### Version

2022.409.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8473816/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8473817/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8473818/network.log)
[performance.log](https://github.com/ppy/osu/files/8473819/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8473820/runtime.log)

**Comment by peppy** [comment]
When you click that button from the menu, does it open a prompt for you to find your stable install or something similar?
