### ISSUE TITLE
Cursor locking up before/after breaks and occasionally as beatmap starts

### ISSUE THREAD

**Issue by Lunaero1** [ppy/osu#17798]
### Type

Game behaviour

### Bug description

As I am playing certain maps when a break starts or ends the cursor will stop moving and mouse inputs will stop being detected for a few moments, but the beatmap continues in the background as normal, sometimes causing me to miss several notes. Oddly enough as well, once the cursor starts moving again it feels heavier and slower than it did before until map restart or exit.
I don't know if its just my computer or if its a bug thats known or anything but its really frustrating. 

### Version

2022.409.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/8477085/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8477086/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8477087/updater.log)
[database.log](https://github.com/ppy/osu/files/8477088/database.log)
[network.log](https://github.com/ppy/osu/files/8477089/network.log)

**Comment by frenzibyte** [comment]
Does changing the state of `Confine mouse mode` in game settings to `Always`/`None` help? if so, then you're facing https://github.com/ppy/osu-framework/issues/4086, which is interesting as we believed it to be macOS-only.

**Comment by Lunaero1** [comment]
> Does changing the state of `Confine mouse mode` in game settings to `Always`/`None` help? if so, then you're facing [ppy/osu-framework#4086](https://github.com/ppy/osu-framework/issues/4086), which is interesting as we believed it to be macOS-only.

Yes, it stopped from what i am seeing but ill give it time, ill continue to play around for a bit and check back up if it gets to as bad as it was before again. Also i changed it to never confine cursor and latency seems to have gone down a bit during gameplay, confusingly enough

**Comment by Lunaero1** [comment]
Ok. Update:
I changed confine mouse cursor to Never and it seems to have somehow fixed the issue, other than an occasional frame studder during gameplay. Still gonne give it a bit longer to see if that changes any over time.

**Comment by Lunaero1** [comment]
@frenzibyte I've p[layed around for a bit and yeah, changing the cursor confinement to never fixed the issue, but i also checked on my laptop on both of its OSs and it doesnt seem to happen at all on both win10 and linux, my main PC is on windows 11. Could this be a case of the newer OS having the same bug that causes the other osu framework bug in macOS?? I'm literally so confused

**Comment by frenzibyte** [comment]
Can be grouped under https://github.com/ppy/osu-framework/issues/4086 anyways.
