### ISSUE TITLE
Backspace not working on external keyboard android

### ISSUE THREAD

**Issue by mrbeaten** [ppy/osu#17803]
### Type

Game behaviour

### Bug description

Backspace doesn't work for some reason, it works when i pressed it the first time but when I pressed it, it delete the whole text then i went on to press the second time.... it brokey  clip below

### Screenshots or videos

https://user-images.githubusercontent.com/85782540/163193998-fb3ae673-5a20-41a2-ac4c-0c8a0b5d10ca.mp4

### Version

The latest one, I think?

### Logs

[runtime.log](https://github.com/ppy/osu/files/8481949/runtime.log)
[network.log](https://github.com/ppy/osu/files/8481950/network.log)
[performance.log](https://github.com/ppy/osu/files/8481951/performance.log)
[database.log](https://github.com/ppy/osu/files/8481952/database.log)

**Comment by mrbeaten** [comment]
Os is android btw

**Comment by AuCrossover** [comment]
I have the same problem. Typing any other letter on the keyboard works, but not backspace on external keyboard. It doesn't delete text though.
