### ISSUE TITLE
Starting osu! in windowed sets the refresh rate to 60

### ISSUE THREAD

**Issue by respektive** [ppy/osu#17804]
### Type

Performance

### Bug description

My monitor refresh rate is set to 240hz and I am using 2x refresh rate in osu!
When i start osu! in borderless mode like i usually do, the Draw refresh rate gets correctly set to 480hz.
However if i start the game in windowed mode it is set to 120hz, which would be 2x 60hz. This also carries over to fullscreen mode and only after switching back and forth between the screen modes, it will set it to 480hz and also keep it at that when switching again.

I can repro the game starting at 120hz in windowed, but I am not entirely sure what makes it set the correct 480hz at one point then.

### Screenshots or videos

https://user-images.githubusercontent.com/22381687/163212452-19a3d8f8-f108-471f-b78d-fa4db5de2c8c.mp4

### Version

2022.409.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8482593/database.log)
[network.log](https://github.com/ppy/osu/files/8482594/network.log)
[performance.log](https://github.com/ppy/osu/files/8482595/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8482596/runtime.log)

**Comment by Theighlin** [comment]
I can reproduce on windows fwiw
