### ISSUE TITLE
Unable to discard a new empty map, and that same empty map couldn't be deleted

### ISSUE THREAD

**Issue by MeguMario** [ppy/osu#17806]
### Type

Game behaviour

### Bug description

I accidentally opened the editor only to find that i was unable to discard the map, the only option is to save the change which created an undeletable map, to make sure that it was not some platform specific bug (I was on my android phone), I tested on both my Linux and Windows machines, to which both also exhibit the same issue

### Screenshots or videos

Android:  https://files.catbox.moe/hi7fut.mp4
Linux: https://files.catbox.moe/d93vg7.mp4
Windows: https://files.catbox.moe/fyz7h0.mp4

### Version

2022.409.0

### Logs

Android:
[database.log](https://github.com/ppy/osu/files/8483981/database.log)
[network.log](https://github.com/ppy/osu/files/8483982/network.log)
[performance.log](https://github.com/ppy/osu/files/8483983/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8483984/runtime.log)

Linux:
[database.log](https://github.com/ppy/osu/files/8484006/database.log)
[network.log](https://github.com/ppy/osu/files/8484007/network.log)
[performance.log](https://github.com/ppy/osu/files/8484008/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8484010/runtime.log)

Windows:
[network.log](https://github.com/ppy/osu/files/8484001/network.log)
[performance.log](https://github.com/ppy/osu/files/8484002/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8484003/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8483999/updater.log)
[database.log](https://github.com/ppy/osu/files/8484000/database.log)

**Comment by respektive** [comment]
You have to hold down on those buttons. It's recently been changed to prevent accidental deletion.

**Comment by frenzibyte** [comment]
I find it interesting that you could not notice that from the fact that the button starts progressing until you release that click. The dialog showing up even though the beatmap is completely empty is tracked in https://github.com/ppy/osu/issues/10628.

**Comment by peppy** [comment]
I'm curious if this animation/behaviour change helps. @MeguMario does this hint at the hold requirement any better to you?

https://user-images.githubusercontent.com/191335/163304781-0759bfe6-c4c4-42a2-b4fe-2a14203f64f9.mp4

**Comment by MeguMario** [comment]
> I'm curious if this animation/behaviour change helps. @MeguMario does this hint at the hold requirement any better to you?
> 
>  osu.Game.Tests.2022-04-14.at.02.56.02.mp4
I think it's better then the last one actually, the way the animation slowly fill up (and not instantly retract itself) with each click should make it more obvious now.
