### ISSUE TITLE
Resolution switching is broken on macOS build

### ISSUE THREAD

**Issue by wtfcxt** [ppy/osu#17812]
### Type

Other

### Bug description

I tried to change the resolution because osu!lazer was running a bit laggy but it doesn't work.

### Version

2022.409.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8485277/database.log)
[network.log](https://github.com/ppy/osu/files/8485279/network.log)
[performance.log](https://github.com/ppy/osu/files/8485281/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8485282/runtime.log)

**Comment by frenzibyte** [comment]
Please attach a video showing how you're changing the resolution. Also make sure you're running in "Fullscreen" mode to actually be able to change the resolution, otherwise you'll hit https://github.com/ppy/osu/issues/14397.

**Comment by wtfcxt** [comment]
I feel really stupid right now, I don't know if it's actually changing the resolution because I can't really see a difference with my bare eye. I can only see it when using something that's lower than 1280x800, and otherwise it literally looks the exact same. Also, I recorded it but the recording crashed while changing the resolution - good job!
Looks like it's actually changing it tho.
