### ISSUE TITLE
Playing Osu! will cause my taskbar dislocation

### ISSUE THREAD

**Issue by zhongzi26** [ppy/osu#17827]
### Type

Other

### Bug description

Playing Osu! will cause my taskbar dislocation

In Windows11 22000.613

“I'm very sure is a bug with Osu!, I did not meet this bug again in any other games or tools, but everytimes i open Osu! and play for above 10min, I use Alt+Tab togo to my desktop, my taskbar will give me a little flash to white and it will dislocation. As a side effect, when I maximize any application, it will directly cover a small part of the taskbar, so that I can't see the taskbar icon. It will be fixed automatically after restart, but every time you play osu! will recur again.”

I have reinstalled the system, but the same bug still exists. only in osu!

So far, the temporary solution I have found is: turn on and off the "auto-hide windows taskbar" in the settings, and the taskbar will return to normal, but this is a bug that affects the use, looking forward to your fix!

(It seems that the bug has something to do with my having a secondary screen.)

### Version

20220406.3

### Logs

There is no log. because this bug will not make osu! crash.

**Comment by peppy** [comment]
Please provide video or screenshots. You can use your phone if display capture doesn't capture the issue.

**Comment by zhongzi26** [comment]
![fd844e7537a7aae7adc78790ab49095](https://user-images.githubusercontent.com/77111407/163543439-188da65a-eb9f-4a4c-be17-992ab6090e3c.png)
when the bug happending


![567ab273c5214700e2d91355eb7b266](https://user-images.githubusercontent.com/77111407/163543463-1be91d65-997a-43f7-8008-972a9d7423ae.png)
normal status

this is the status before the bug happended and when the bug happended

**Comment by zhongzi26** [comment]
> ![fd844e7537a7aae7adc78790ab49095](https://user-images.githubusercontent.com/77111407/163543439-188da65a-eb9f-4a4c-be17-992ab6090e3c.png) when the bug happending
> 
> ![567ab273c5214700e2d91355eb7b266](https://user-images.githubusercontent.com/77111407/163543463-1be91d65-997a-43f7-8008-972a9d7423ae.png) normal status
> 
> this is the status before the bug happended and when the bug happended

Pay attention to the spacing between the windows pop-up window and the taskbar

**Comment by zhongzi26** [comment]
my screen is 2560x1440

**Comment by peppy** [comment]
This looks like a windows bug if anything. Please report to microsoft.
