### ISSUE TITLE
Skin editor returns to broken song select

### ISSUE THREAD

**Issue by adryzz** [ppy/osu#17836]
### Type

Crash to desktop

### Bug description

Go on the skin editor in song select and add a few sprites. then without saving click on "gameplay", and after you're there click ESC. 

from the gameplay screen you're into, click esc again to get into a broken song select screen. clicking ESC again will get you to the broken main menu.

from this main menu, get into the skin editor again, and by clicking on "Gameplay" it should crash (after this long chain of errors.

this happened randomly and my db is now corrupted somehow.
 EDIT: using the corrupted db works (?)

### Screenshots or videos

Video from broken main menu onwards:

https://user-images.githubusercontent.com/46694241/163599686-671ac840-f9ba-42b0-b88d-488c60d29990.mp4

### Version

2022.405.0.0

### Logs

[database.log](https://github.com/ppy/osu/files/8497048/database.log)
[network.log](https://github.com/ppy/osu/files/8497049/network.log)
[performance.log](https://github.com/ppy/osu/files/8497050/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8497051/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8497052/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8497053/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8497054/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8497055/runtime.log)

**Comment by peppy** [comment]
Probably fine to close this and track as part of https://github.com/ppy/osu/issues/17391. The solution is likely going to be the same.
