### ISSUE TITLE
Occasional lag spikes and low fps on my phone.

### ISSUE THREAD

**Issue by kajxqeirscl** [ppy/osu#17832]
### Type

Performance

### Bug description

osu lazer is running poorly on my Samsung Galaxy A52. Could there be compatibility issues?

### Screenshots or videos

![Screenshot_20220415-161420](https://user-images.githubusercontent.com/75833519/163584559-b55771b5-eeab-47df-a8ad-7a0bafca965b.jpg)

### Version

2022.409.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8496502/database.log)
[network.log](https://github.com/ppy/osu/files/8496503/network.log)
[performance.log](https://github.com/ppy/osu/files/8496504/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8496505/runtime.log)

**Comment by jamesbt365** [comment]
Lazer isn't that well optimized for mobile at the moment? I think more are stability stuff is coming along in the future? The main focus is desktop i think. Don't quote me on this if i'm wrong.

**Comment by frenzibyte** [comment]
Desktop and parity with osu!(stable) comes first, correct. Performance is an ongoing effort, and mobile optimizations are not a focus yet.
