### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by Xandaros** [ppy/osu#17842]
### Type

Crash to desktop

### Bug description

The game sometimes just crashes, usually when opening a beatmap.
I've had playing one particular map crash on me, restarted the game and tried the same beatmap, immediate crash again. It worked on the 3rd try, but then crashed after a couple retries.

```
xandaros@MELON lazer> ./osu.AppImage
malloc(): unsorted double linked list corrupted
fish: Job 1, './osu.AppImage' terminated by signal SIGABRT (Abort)
xandaros@MELON lazer [134]> ./osu.AppImage
malloc(): invalid next size (unsorted)
fish: Job 1, './osu.AppImage' terminated by signal SIGABRT (Abort)
xandaros@MELON lazer [134]> ./osu.AppImage
malloc(): invalid next size (unsorted)
fish: Job 1, './osu.AppImage' terminated by signal SIGABRT (Abort)
```

There was at least one more crash that isn't in the above log, but should be in the log file.

### Version

2022.409.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8499950/database.log)
[network.log](https://github.com/ppy/osu/files/8499951/network.log)
[performance.log](https://github.com/ppy/osu/files/8499952/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8499953/runtime.log)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/17457

**Comment by Xandaros** [comment]
Ah, good to know - thank you.

For what it's worth, I did search first - I just didn't think to check closed issues.
