### ISSUE TITLE
Axis "bounce" using gamepad/joystick, CTB

### ISSUE THREAD

**Issue by maromalo** [ppy/osu#17846]
### Type

Game behaviour

### Bug description

I'm playing CTB on a gamepad, using the L stick to move the catcher left and right. On stable it works flawlessly (I've played on stable for quite a while now), but on lazer the catcher occasionally bounces back. I've tried calibrating my gamepad but that didn't do it. I played on borderless to make it easy to record (which is also why my FPS are all over the place), however issue still persists on full-screen.

### Screenshots or videos

On osu!lazer: https://imgur.com/vhNtDay

On regular osu!: https://imgur.com/NRIJm83

### Version

2022.409.0

### Logs

[network.log](https://github.com/ppy/osu/files/8500522/network.log)
[performance.log](https://github.com/ppy/osu/files/8500523/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8500524/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8500525/updater.log)
[database.log](https://github.com/ppy/osu/files/8500526/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8500527/legacy-ipc.log)

**Comment by peppy** [comment]
Deadzone on stable is `0.25f`(absolutely huge...), osu-framework is `0.075f`. I've mentioned in the past that this likely needs to be configurable by the user for cases where the controller misbehaves.

**Comment by frenzibyte** [comment]
To keep track, adding support for configuring joystick axis deadzones is tracked in https://github.com/ppy/osu-framework/issues/3639.

**Comment by maromalo** [comment]
Closed by https://github.com/ppy/osu/pull/17942
