### ISSUE TITLE
Many lag spikes during Gameplay on Android

### ISSUE THREAD

**Issue by FlynxUwu** [ppy/osu#17852]
### Type

Performance

### Bug description

My Samsung Galaxy Tab S7 gets a lot of lag spikes during Gameplay ( example in the video)
Its really hard playing like this and it has been like that since october when i started playing Osu lazer
My Tablet has a Snapdragon 865+ and 6gb RAM running Android 12 OneUI 4.1 so it shouldnt lack the performance to run Osu.

### Screenshots or videos

https://user-images.githubusercontent.com/66845810/163731949-999af283-4864-43de-8c56-07dbcbeac58a.mp4

### Version

Osu! 2022.418.0 - Lazer

### Logs

[network.log](https://github.com/ppy/osu/files/8502439/network.log)
[performance.log](https://github.com/ppy/osu/files/8502440/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8502441/runtime.log)
[database.log](https://github.com/ppy/osu/files/8502442/database.log)

**Comment by bdach** [comment]
Mobile performance is a constant work in progress but not a priority currently. Desktop performance comes first and foremost for now.
