### ISSUE TITLE
Cursortrail shows white pixel

### ISSUE THREAD

**Issue by respektive** [ppy/osu#17871]
### Type

Cosmetic

### Bug description

Lazer shows a white dot for the trail while on stable it's not showing any trail. On lazer we now have the option to disable the cursor trail in the settings but that was not the case on stable so people put a 1x1 transparent png as the trail, which would basically "disable" it then. 
I remember other legacy skins working fine in that regard on lazer so it's probably something specific to this one.
[Varv.osk.zip](https://github.com/ppy/osu/files/8506271/Varv.osk.zip) (.osk file is inside the zip)

### Screenshots or videos

Stable:
![output](https://user-images.githubusercontent.com/22381687/163824018-ab67af39-de2c-4521-ba8e-50339e4a6f52.gif)
Lazer:
![output2](https://user-images.githubusercontent.com/22381687/163824035-1c7ce111-1da3-4886-9fa8-6daa496375b3.gif)

### Version

2022.418.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8506280/database.log)
[network.log](https://github.com/ppy/osu/files/8506281/network.log)
[performance.log](https://github.com/ppy/osu/files/8506283/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8506284/runtime.log)

**Comment by bdach** [comment]
a gif helps less than a freeze frame here. i presume you mean this:

![2022-04-18-173213_1213x559_scrot](https://user-images.githubusercontent.com/20418176/163832330-a0784a58-1049-440c-94c3-da2e67a1b940.png)

**Comment by respektive** [comment]
Yeah, sorry the gif made it kinda hard to see but that's what i mean.

**Comment by bdach** [comment]
So I checked the files of the skin in question... and `cursortrail.png` is firmly *not* transparent on it. It is a 1x1 white pixel.

![image](https://user-images.githubusercontent.com/20418176/163841060-a9494556-cc1f-4c28-81df-406317d551d0.png)

Closing as a "broken skin" issue.

**Comment by respektive** [comment]
Interesting, I assumed it was transparent as stable doesn't actually show it, but that actually makes sense then. Sorry for that, I should have checked beforehand if it was actually transparent.
