### ISSUE TITLE
Aspect ratio is stuck at 16:9 when playing on phone's with different aspect ratio

### ISSUE THREAD

**Issue by Vortex100K** [ppy/osu#17908]
### Type

Game behaviour

### Bug description

I use a iPhone 11 which has a 19.5:9 aspect ratio so when I installed osu on it I instantly noticed the black bars on the sides 

I also have an older version of lazer sideloaded onto my phone and that is using my phones aspect ratio without a problem,
Was this maybe intentional because of apple devices having a notch on the screen?

### Screenshots or videos

![IMG_2462](https://user-images.githubusercontent.com/79509710/164414288-ff2742ad-e309-4bbf-97e6-0996973bfeff.PNG)
![IMG_2463](https://user-images.githubusercontent.com/79509710/164414296-e7da64ce-03a4-430b-be04-d259ccb789fa.PNG)

### Version

2022.418.0

### Logs

I am unable to supply logs since my pc doesn't have a USB-C connection

**Comment by peppy** [comment]
The black bars are there to ensure the game doesn't overlap the notches or rounded edges of your device. This is the best-effort implementation we have now. Internally we already have support for better handling these, but it requires consideration at every screen of the game, which is quite a large effort.

Tracking at https://github.com/ppy/osu/issues/4330.

**Comment by Vortex100K** [comment]
Ok thanks for the input
ill be sure to subscribe to that issue for updates
