### ISSUE TITLE
Crashing on heavy beatmaps.

### ISSUE THREAD

**Issue by artflowfx** [ppy/osu#1792]
Later today, I've imported maps from my original osu! And, I tried experimenting with the play bot on a map called "Centipede".
The game had no problem at start for 5 seconds. Eventually, it started lagging and so on, it crashed.
Plus, the map doesn't crash or lag on the original game.

(I know lazer is a early access game and don't expect anything to work, just pointing it out!)

**Comment by peppy** [comment]
Known but not really worth making issues over for now. At a previous point in time it worked; now it doesn't; one day it will work again.
