### ISSUE TITLE
Searching in settings does not show/hide sections correctly

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#17929]
### Type

Game behaviour

### Bug description

I was trying the local version of master for various things (e.g. the new setup screen) when I noticed that the search in the settings seems to behave weirdly and doesn't hide some sections at times.

### Screenshots or videos

https://user-images.githubusercontent.com/43073074/164707375-27931985-6cdb-4127-9c68-be881b813b7c.mp4

### Version

master

### Logs

N/A

**Comment by bdach** [comment]
This is not fully fixed on master for me:

https://user-images.githubusercontent.com/20418176/164936465-13bdd0f0-4b20-4aec-abb5-b2f045e3adfc.mp4

#17937 fixes this for me. @frenzibyte please confirm that that pull was supposed to address this? not sure why this issue wasn't reopened if so.

**Comment by frenzibyte** [comment]
Ah right, noticed the issue was still persisting in master after I had submitted the PR already, but forgot to mention it here.
