### ISSUE TITLE
"Get Started" message never appears on the first-run guide

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#17948]
### Type

Game behaviour

### Bug description

Yesterday while looking at the Crowdin's translations, I noticed that there's a "Get Started" message for the first-run guide overlay, but for some reason, it never shows up in the actual game. (I guess it should be on the first page where it says "Welcome to the first-run setup")

With some debugging, the issue seems to be in the following logic:

![image1](https://user-images.githubusercontent.com/43073074/164891536-33dc92be-e637-4b83-9a4e-23d5faf85aae.png)
1. The button is initialized with the `GetStarted` message
 ![image](https://user-images.githubusercontent.com/43073074/164892938-5d05d2d0-1b56-4b20-84f0-5f64c0ef80bc.png)
2. The pop-in animation calls the `showFirstStep()` method, followed by `showFirstStep()` and `showNextStep()`
3. Inside this last method there's a call to the `updateButtons()` method, which checks for the `NextButton`'s text and discards the possibility of being exactly at step 0. This causes the "Get Started" message to never appear:
```c#
private void updateButtons()
 {
    BackButton.Enabled.Value = currentStepIndex > 0;
    NextButton.Enabled.Value = currentStepIndex != null;

    if (currentStepIndex != null)
    {
        NextButton.Text = currentStepIndex + 1 < steps.Length
            ? FirstRunSetupOverlayStrings.Next(steps[currentStepIndex.Value + 1].Description)
            : CommonStrings.Finish;
    }
}
```

I'm not sure about the correct code style here, but I can imagine the logic to be something like this 
(the `if` flow can probably be changed to something better):

```c#
private void updateButtons()
{
    BackButton.Enabled.Value = currentStepIndex > 0;
    NextButton.Enabled.Value = currentStepIndex != null;

    if (currentStepIndex == null) return;

    if (currentStepIndex == 0)
        NextButton.Text = FirstRunSetupOverlayStrings.GetStarted;
    else if (currentStepIndex + 1 < steps.Length)
        NextButton.Text = FirstRunSetupOverlayStrings.Next(steps[currentStepIndex.Value + 1].Description);
    else
        NextButton.Text = CommonStrings.Finish;
}
```

### Screenshots or videos

N/A

### Version

master

### Logs

N/A

**Comment by peppy** [comment]
Hmm, nice find. I'm not sure if we need this, but probably makes sense to fix it.

**Comment by peppy** [comment]
Resolved via https://github.com/ppy/osu/pull/17979
