### ISSUE TITLE
The videos in beatmaps wont play on Osu!Lazer for Linux

### ISSUE THREAD

**Issue by patgamer351** [ppy/osu#17947]
### Type

Cosmetic

### Bug description

I have downloaded beatmaps with videos on them but they wont play in the background, but Storymaps work 100% fine. 

### Version

2022.418.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8546700/database.log)
[network.log](https://github.com/ppy/osu/files/8546701/network.log)
[performance.log](https://github.com/ppy/osu/files/8546702/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8546703/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8546704/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8546705/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8546706/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8546707/runtime.log)

**Comment by peppy** [comment]
Please install ffmpeg 4.x or wait until we are bundling it in the future.

Please search in the future, there's tens of issues related to this.
