### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by yuracoff18** [ppy/osu#1794]
Hi, I want to report an error that happened to me in osu lazer, when I'm going to run the program, I miss an error saying that osu lazer stopped working for a problem with Windows, if you can tell me how to fix it I'll be very grateful, I'll try again to install the program but nothing, also try executing it in task manager and neither.

The requirements of my pc are:
Processor: Corei 5
RAM: 4 gb
video card: it does not have
operating system: windows 10 with 64 bits

**Comment by kj415j45** [comment]
A report without any logs is helpless. And no one could give you any help either.

**Comment by TemTemmie** [comment]
reinstall. probably a bug with the framework
