### ISSUE TITLE
Game crashed when opening beatmap details while downloading it

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#17953]
### Type

Crash to desktop

### Bug description

I was browsing the beatmap listing with "blood moon" and i clicked the download button of the [first result](https://osu.ppy.sh/beatmapsets/1395456#osu/2880284). While it was downloading i clicked on the beatmap card to go to its page, the overlay opening animation froze midway and then it crashed.

### Version

2022.418.0

### Logs

[network.log](https://github.com/ppy/osu/files/8548552/network.log)
[performance.log](https://github.com/ppy/osu/files/8548553/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8548554/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8548555/updater.log)
[database.log](https://github.com/ppy/osu/files/8548556/database.log)

**Comment by bdach** [comment]
From log:

```
2022-04-23 20:24:39 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2022-04-23 20:24:39 [error]: at osu.Framework.Localisation.LocalisableFormattableString.GetLocalised(LocalisationParameters parameters)
2022-04-23 20:24:39 [error]: at osu.Framework.Localisation.LocalisationManager.GetLocalisedString(LocalisableString text)
2022-04-23 20:24:39 [error]: at osu.Framework.Localisation.LocalisationManager.LocalisedBindableString.updateValue()
2022-04-23 20:24:39 [error]: at osu.Framework.Graphics.Sprites.SpriteText.load(ShaderManager shaders)
```

I think this is just going to be a case of `.ToLocalisableString()` not being able to handle being called on a null `IFormattable`...?

**Comment by frenzibyte** [comment]
Hmm, upon checking, there doesn't seem to be any `IFormattable` input of a nullable/reference type. 

But with the changes in https://github.com/ppy/osu-framework/pull/5130, that'll be implicitly handled as `string.Format` handles null arguments properly:

<img width="1052" alt="CleanShot 2022-04-26 at 04 06 40@2x" src="https://user-images.githubusercontent.com/22781491/165198711-5d45dc53-5a83-4eae-a5a1-c7c6a7d40ee1.png">

**Comment by peppy** [comment]
You can probably link that PR to close this one. Do we know where the null came from in this instance?

**Comment by frenzibyte** [comment]
Nope, that's why I'm unsure if the PR will really close this issue, since I can't find any use case which *can* pass a null input to cause a nullref in the first place.

Upon looking at the current code of `LocalisableFormattableString.GetLocalised`, one other potential culprit is the `parameters` parameter, which can potentially be null since it's a class type, but can't find any usage where that can be the case... 

Maybe best to just link the PR and see if it comes up later.
