### ISSUE TITLE
Context menus cannot be interacted with

### ISSUE THREAD

**Issue by Silent-string** [ppy/osu#17961]
### Type

Game behaviour

### Bug description

no issue with mouse buttons, but these menu bars stopped working in the 2022.424.0 AppImage

### Screenshots or videos

![menu1](https://user-images.githubusercontent.com/52829727/164976278-88eca9a9-a140-45a0-ab4c-f26b1a0a4040.jpg)
![menu2](https://user-images.githubusercontent.com/52829727/164976282-a2893555-7c4e-48f7-8ba4-5d0e93b76e15.jpg)

### Version

2022.424.0-lazer AppImage

### Logs

[database.log](https://github.com/ppy/osu/files/8549666/database.log)
[network.log](https://github.com/ppy/osu/files/8549667/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/8549668/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8549669/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8549670/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8549671/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/8549672/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8549673/runtime.log)

**Comment by Silent-string** [comment]
Upon clicking, menu disappears, nothing happening

**Comment by Isuewo** [comment]
Can confirm. Same thing here. Also occurs on the beatmap selection screen. I can sometimes interact with the first item in the submenu, otherwise my click just goes through and selects the element behind it. Also 2022.424.0-lazer with the AppImage version

**Comment by peppy** [comment]
going to be a regression of the framework `ScrollContainer` change, no doubt (https://github.com/ppy/osu-framework/pull/5118).

**Comment by Isuewo** [comment]
I've also made a recording of the issue:

https://user-images.githubusercontent.com/53264315/164978138-f196c751-766e-44f8-8233-86941008d79c.mp4
