### ISSUE TITLE
Right clicking osu! icon on Windows taskbar doesn't open context menu

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#17965]
### Type

Other

### Bug description

Noticed when trying to reproduce https://github.com/ppy/osu/issues/10588.

This is only reproducible in release builds, and seems like Windows 8.1 is unaffected (only 10/11).

Note that this can sometimes break right clicking on any other icon, and the only fix is restarting windows explorer.

### Screenshots or videos

![2022-04-24_11-25-36](https://user-images.githubusercontent.com/35318437/164990881-13425949-fc06-4401-8488-0688f0bb8ed2.gif)

### Version

Since 2022.314.0 (Clowd.Squirrel)

### Logs

N/A

**Comment by Joehuu** [comment]
Didn't notice I duplicated https://github.com/ppy/osu/issues/17963 (because it specifies tournament, but can be reproduced anywhere), closing.

**Comment by bdach** [comment]
I dunno about that, that other issue mentions something about resolution? Is that just misguided/wrong? Too far from a windows box to check myself right now.

**Comment by Joehuu** [comment]
Yeah, seems wrong, but I wanted to keep the older issue. Can reopen this if the description is better.

Can be even reproduced with lazer closed and just pinned on the taskbar.
