### ISSUE TITLE
mod buttons unreachable on andriod (or any small screen)

### ISSUE THREAD

**Issue by RewardedIvan** [ppy/osu#17960]
### Type

Cosmetic

### Bug description

"mods  random  options" buttons are infront of the mods buttons, making them unreachable

### Screenshots or videos

![Screenshot_20220424-134700](https://user-images.githubusercontent.com/67065165/164972770-a94e352f-62f1-45b1-8b7e-0497fac7a75b.jpg)

### Version

2022.418.0 (android)

### Logs

It is a cosmetic issue thus it does not need any logs.

**Comment by peppy** [comment]
Please drag to scroll the dialog.

**Comment by RewardedIvan** [comment]
is there something i am missing?
![Screenshot_20220424-145908](https://user-images.githubusercontent.com/67065165/164975355-6866a73b-e348-4366-ab82-3c45fedc6253.jpg)
For now changing the ui scale makes it reachable

**Comment by peppy** [comment]
Changing UI scale works, yes.
