### ISSUE TITLE
Tournament Overlay breaks taskbar context menu if StreamAreaResolution = Monitor Resolution

### ISSUE THREAD

**Issue by MaxKruse** [ppy/osu#17963]
### Type

Other

### Bug description

Following the setup on [this guide](https://mirai.blog/osu-lazer-tournament-streaming-guide/), i encounter the problem that lazer forces itself over the taskbar (as per the resolution setting), but then breaks the taskbar into not being able to rightclick it at all. This issue persists even after restarting explorer.exe and is only fixed by a reboot.

Additionally, the overlay is only closable through the taskmanager in cases where the streamarea is set to 1080p on a 1080p monitor.

My setup: 

Win10 21h1 (Build 19043.1645)
2x 1080p Monitors

How to replicate:

1. Start osu!lazer with a shortcut and the --tournament flag
2. Set the streaming-area to 1080p and click apply
3. Try to rightclick any open window's program (e.g. lazer itself) on the taskbar
4. Nothing happens, except a small highlight that something has been pressed, but no actual context menu appears (for pinning, closing the application etc)

I am not quite sure why this happens, or how to fix the resulting problems except rebooting my PC everytime.

### Version

2022.424.1

### Logs

[network.log](https://github.com/ppy/osu/files/8550195/network.log)
[performance.log](https://github.com/ppy/osu/files/8550196/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8550197/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8550198/updater.log)
[database.log](https://github.com/ppy/osu/files/8550199/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8550200/legacy-ipc.log)

**Comment by frenzibyte** [comment]
From what I'm reading in #17965, I think this can be shortened to that context menu never appears on lazer, and has the chance to break all other icons surrounding it until the task bar is reloaded.

![](https://user-images.githubusercontent.com/35318437/164990881-13425949-fc06-4401-8488-0688f0bb8ed2.gif)

Does this line up with what you're referring to? and if so, can you confirm whether the part about "tournament overlay" and resolution is unnecessary, and it's just lazer not showing context menu at all?

**Comment by MaxKruse** [comment]
I can confirm this is the exact issue.

Having the tournament overlay span across the taskbar breaks the other icons semi-permanently (as described, reboots fix this).

It appears lazer's missing context menu is somehow being replicated by all taskbar elements that were covered by the tournament overlay. This did not occur when i ran lazer as the regular client.

**Comment by peppy** [comment]
Tracking via #17965
