### ISSUE TITLE
osu!catch game breaking bug

### ISSUE THREAD

**Issue by AkaiiKitsune** [ppy/osu#1799]
Hi, this just occured while i was trying to play some osu!catch
![image](https://user-images.githubusercontent.com/33877610/34449013-f7ccffe4-ecf3-11e7-8c5e-eb1f23dec195.png)
I don't know if this bug is known but i feel like it's a bit broken x)

My game resolution is 3962\*1080 pixels... i think the problem is coming from here : i'm playing on two 1920\*1080 screens with Nvidia Surround enabled...

**Comment by peppy** [comment]
This happens even at non-wide resolutions and a fix is in progress. Closing for now as it'll be fixed as part of a larger rework on catch hitobject positioning.
