### ISSUE TITLE
Search container is flawed in multiple ways

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18003]
### Type

Game behaviour

### Bug description

`SearchContainer` relies on a very manual specification of filterable items. This falls over regularly with the amount of hierarchical structure we use.

Example 1: Search for "Resolution" while running windowed
Result: Section is shown even though the resolution dropdown is hidden via other means

Example 2: Search for "Horizontal" while not applying any UI scaling
Result: Section is shown even though the scaling options are hidden via other means

Example 3: Search for "Rotation" while tablet support is disabled
Result: Tablet settings are shown with no content, as content is hidden via the main toggle checkbox

I'm not sure if `SearchContainer` is able to be used properly in a case like this. It's the classic case of a parent container being hidden but children still being `IsPresent` (we don't currently check this, but this or any other means of checking also reporting that it's "visible" makes a path forward hard to envisage).

### Screenshots or videos

![osu! 2022-04-28 at 04 56 19](https://user-images.githubusercontent.com/191335/165679352-e3000d92-895e-4dd2-8c56-a29da4029684.png)

### Version

master

### Logs

-

**Comment by frenzibyte** [comment]
Have took a look through this issue and how `SearchContainer` works currently, and can see one of the main things which can make it break is the necessity of an `IHasFilterableChildren` interface, for the fact that some filterables may be layered inside containers, hiding it from the usual `Children.OfType<IFilterable>()` query.

Started things off by refactoring `SearchContainer` to instead do a proper tree traversal and look for any drawable which implements from `IFilterable` and take its filter terms into account, all with flexibility and legibility in mind (since I had a hard time trying to understand how it makes sense):
```csharp
        /// <summary>
        /// Performs a tree traversal from the given node to filter out drawables which do not match the specified search terms.
        /// </summary>
        /// <param name="drawable">The root drawable of this subtree.</param>
        /// <param name="searchTerms">The search terms to filter drawables against.</param>
        /// <param name="searchActive">Whether there are search terms usable for filtering drawables.</param>
        /// <param name="nonContiguousMatching">Whether the matching algorithm should be non-contiguous, allowing for potentially non-matching characters to exist between matches.</param>
        private static bool matchSubTree(Drawable drawable, IReadOnlyList<string> searchTerms, bool searchActive, bool nonContiguousMatching)
        {
            bool matching = match(drawable, searchTerms, nonContiguousMatching, out var nonMatchingTerms);

            if (drawable is IContainerEnumerable<Drawable> container)
            {
                foreach (var child in container.Children)
                    matching |= matchSubTree(child, nonMatchingTerms, searchActive, nonContiguousMatching);
            }

            if (drawable is IFilterable filterable)
            {
                filterable.FilteringActive = searchActive;
                filterable.MatchingFilter = matching;
            }

            return matching;
        }

        /// <summary>
        /// Whether the specified drawable matches the specified search terms.
        /// </summary>
        /// <param name="drawable">The drawable to check for match.</param>
        /// <param name="searchTerms">The search terms to check against.</param>
        /// <param name="nonContiguousMatching">Whether the matching algorithm should be non-contiguous, allowing for potentially non-matching characters to exist between matches.</param>
        /// <param name="nonMatchingTerms">The search terms which do not match the specified drawable.</param>
        private static bool match(Drawable drawable, IReadOnlyList<string> searchTerms, bool nonContiguousMatching, out IReadOnlyList<string> nonMatchingTerms)
        {
            nonMatchingTerms = searchTerms;

            if (drawable is IFilterable filterable)
                nonMatchingTerms = nonMatchingTerms.Where(term => !checkTerms(filterable.FilterTerms, term, nonContiguousMatching)).ToArray();

            return nonMatchingTerms.Count == 0;
        }

        private static bool checkTerms(IEnumerable<string> filterTerms, string searchTerm, bool nonContiguous) => filterTerms.Any(term => checkTerm(term, searchTerm, nonContiguous));
```

And then, in order to resolve the issues mentioned in OP, `SearchContainer` would take into account whether the filterable or its parent is not present, and exclude it during filtering:
```diff
diff --git a/osu.Framework/Graphics/Containers/SearchContainer.cs b/osu.Framework/Graphics/Containers/SearchContainer.cs
index 9c56a1acc..6e0b33e04 100644
--- a/osu.Framework/Graphics/Containers/SearchContainer.cs
+++ b/osu.Framework/Graphics/Containers/SearchContainer.cs
@@ -100,7 +100,7 @@ private static bool matchSubTree(Drawable drawable, IReadOnlyList<string> search
         {
             bool matching = match(drawable, searchTerms, nonContiguousMatching, out var nonMatchingTerms);

-            if (drawable is IContainerEnumerable<Drawable> container)
+            if (drawable.IsPresent && drawable is IContainerEnumerable<Drawable> container)
             {
                 foreach (var child in container.Children)
                     matching |= matchSubTree(child, nonMatchingTerms, searchActive, nonContiguousMatching);
@@ -127,8 +127,16 @@ private static bool match(Drawable drawable, IReadOnlyList<string> searchTerms,
             nonMatchingTerms = searchTerms;

             if (drawable is IFilterable filterable)
+            {
                 nonMatchingTerms = nonMatchingTerms.Where(term => !checkTerms(filterable.FilterTerms, term, nonContiguousMatching)).ToArray();

+                // reset filter to ensure presence is not influenced by previous filter state when checking.
+                filterable.MatchingFilter = true;
+            }
+
+            if (!drawable.IsPresent)
+                return false;
+
             return nonMatchingTerms.Count == 0;
         }
```

(in addition, the issue about the screen scaling options will also require a local change that hides the container of the options, since currently it hides by [having its height reset to zero](https://github.com/ppy/osu/blob/faeefc5e18860dc69337235b973037cfa378bed1/osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs#L208-L209))

Before I go off with PR'ing this, does this look like a good path forward for `SearchContainer`, or is there a different idea envisioned which could simplify this?

**Comment by peppy** [comment]
I think it could work. My only concern is relying on `IsPresent`, which means we cannot fade content unless that content if also manually implementing `IFilterable`. But maybe that's okay?

On the perspective of doing full traversal, I think this is fine. If performance ever becomes a concern we can async the search/filter process (will likely need to be done regardless).
