### ISSUE TITLE
Sort by "Rank Achieved" doesn't work, it simply sorts by the Artist.

### ISSUE THREAD

**Issue by osulover9000** [ppy/osu#18015]
### Type

Game behaviour

### Bug description

Trying to sort by Rank Achieved simply sorts by Artist instead.

### Screenshots or videos

https://user-images.githubusercontent.com/104596572/165878112-539f95c6-b1d7-4b08-bfa2-a42638385a96.mp4

### Version

2022.424.1-lazer

### Logs

N/A

**Comment by frenzibyte** [comment]
Because it's not implemented. See https://github.com/ppy/osu/issues/4917.
