### ISSUE TITLE
Path option in the AppImage's XDG desktop file is incorrect

### ISSUE THREAD

**Issue by agausmann** [ppy/osu#18023]
### Type

Other

### Bug description

The desktop file that is packaged in the AppImage looks like this:

```
[Desktop Entry]
Type=Application
Name=osu!
Comment=A free-to-win rhythm game. Rhythm is just a *click* away!
Icon=osu!
Exec=osu!
Path=~
Terminal=false
Categories=Game;
```

The problem here is the `Path` field. It seems that it was set to `~` to try to set the working directory to the home directory, but `~` will not work for that. This is alluded to by `desktop-file-validate`:
```
$ ./osu.AppImage --appimage-mount &
/tmp/.mount_osu.ApJLA0Wd

$ desktop-file-validate '/tmp/.mount_osu.ApJLA0Wd/osu!.desktop'
/tmp/.mount_osu.ApJLA0Wd/osu!.desktop: warning: value "~" for key "Path" in group "Desktop Entry" does not look like an absolute path
```

In any case, removing the `Path` line entirely works fine for me.
I would have submitted a PR fixing it if I knew where the desktop file is located or wherever that value is being set, but I cannot find it.

### Version

2022.424.1-lazer

### Logs

N/A

**Comment by jai-x** [comment]
The repo containing packaging scripts is https://github.com/ppy/osu-deploy/ so you can open a PR there.

**Comment by agausmann** [comment]
Fixed in osu-deploy, thanks!
