### ISSUE TITLE
links in Multi lobby titles

### ISSUE THREAD

**Issue by Ocklepod** [ppy/osu#18044]
### Type

Game behaviour

### Bug description

When inviting to a multiplayer lobby, and the title includes a link, clicking it will open the link instead of joining the lobby. For example "[Tournament name]: (link) vs Team B", when clicking somewhere else, e.g. "Team B", it will let you join, but if the lobby is just "(link)", it's not possible to join. I suggest making external links unclickable if inside an internal link.

### Version

b20220424

### Logs

[runtime.log](https://github.com/ppy/osu/files/8599782/runtime.log)
[session.log](https://github.com/ppy/osu/files/8599783/session.log)
[update_success.log](https://github.com/ppy/osu/files/8599784/update_success.log)

**Comment by bdach** [comment]
As far as I can tell (from the version number and the logs), this issue pertains to stable. This repository only accepts reports for lazer.

Reports for stable go over at https://github.com/ppy/osu-stable-issues, but only major game-breaking bugs have a good chance of being fixed, and this doesn't seem to be one.
