### ISSUE TITLE
Window glitching between monitors and crashing KWin (Wayland)

### ISSUE THREAD

**Issue by JonLit** [ppy/osu#18068]
### Type

Other

### Bug description

Hi, I have a weird problem:I have 4 Monitors, 3 connected to my rx 6700xt, and 1 connected to the intel iGPU (770, the new 12th gen one) and use Garuda Linux (Arch-based) with kwin_wayland (5.24.4, same problem also on older version of both osu and kwin)

So I wanted to play osu!lazer. I like to launch it from lutris, so I started lutris (with `ENABLE_VKBASALT=0 lutris &; disown` because else it just instantly crahes with a segmentation fault... but nevermind I got past this step).Next I started osu, and it is displayed on my iGPU-connected-monitor, so I drag it with `Win + mouse drag` to my main monitor (connected to amd gpu)Next I wanted to tab out, so I did this, already was a bit suspicious that the minimize animation glitched from left to right, so (as I experienced this before) I toggle the windows overview or whatever it's called (`Ctrl + F9`) and the osu!lazer window glitches from one of my dGPU-connected-monitors to another dGPU-connected-monitor. From prior experience I can say this: If i then tab back into osu, or click on the osu window in the overview, kwin crashes with a segmentation fault and I get a Black Screen on all monitors, with working cursor, if I press `Ctrl + F8` I can see the buttons to add/remove workspaces, they also "work" as in if I create one, the delete button isn't greyed out anymore and the other way round, but that's it about the working GUI stuff. I can still switch to a tty, and terminate the session with loginctl / restarting sddm, or reboot from the tty.

Imagine the window from osu (with the wayland logo) going from the middle right to the middle left monitor MANY times / second
![grafik](https://user-images.githubusercontent.com/55829273/166412142-b3a1f34c-99f9-488a-bad1-28566c3bfe2c.png) 
Picture of the osu window glitching between the main monitor and the 2nd monitor from the left (edited for privacy)

P.S. Sometimes, if I tab out, the osu window goes to the rightmost monitor, and doesn't glitch around there, I can drag it just back to my main monitor, also doesn't nuke kwin if I tab in if that happens (I have no idea how/why the one or the other happens)

### Version

2021* to newer version, probably also older versions

### Logs

Currently on my laptop, so I only have a pic of terminal output, I'll send the logs later (probably ~8pm UTC)
![grafik](https://user-images.githubusercontent.com/55829273/166412537-69ca4dba-0bb3-48c5-863e-43730211fd19.png)

**Comment by peppy** [comment]
Please use X11 and track wayland issues against SDL (which are improving support gradually). We can't provide direct support for linux environment, sorry. Every user is different.
