### ISSUE TITLE
Player should not be able to exit gameplay after progression to results has begun

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18089]
Currently, if you hit the exit key (after setting hold delay to zero) directly after passing a beatmap, the player will not reach the results screen. This feels like pretty bad UX.

Optimally, during this previous, invoking the pause menu should still be feasible. I did look into doing this but it's a bit involved due to the `Task` which is used to progress to the next screen.

Failing that, a better-than-nothing option would be to have it immediately switch to the results screen (similar to stable), or outright block the exit sequence during this period (least preferable).

### Discussed in https://github.com/ppy/osu/discussions/17955

<div type='discussions-op-text'>

<sup>Originally posted by **respektive** April 24, 2022</sup>
As has been reported before: https://github.com/ppy/osu/issues/3060 https://github.com/ppy/osu/issues/13644

I believe the behaviour from stable should come back for this as I see a lot of players do this all the time and I don't think we can expect people to break this habit that easily. Even after playing more and more lazer over the last months, it is very hard for me to get rid of this habit and I still find myself hitting the escape key after almost every play. 

Maybe this isn't affecting as many players as I think though, as it's not that much of a problem with the "hold to confirm" option, which i personally have disabled. I'm interested to hear more opinions on this.</div>

**Comment by kanakisaki** [comment]
> The alternative would be to block the escape press completely for that very short period of time. Or make it show the pause screen.

Just to mention, personally, I feel like this alternative is not actually fixing the problem, just making it less annoying. Even if nothing happens when you press Esc button, you still need to wait about 1 sec for the results screen to appear, but after playing osu stable a lot, you get used to the immediate switching to the screen after pressing the Esc button, so if it differs, the player would think that "something is wrong" anyway. Showing the pause screen is even worse, because the part of the actual gameplay has gone, and there's nothing for you to pause, so it would confuse the player even more, in my opinion.

**Comment by Fivoka** [comment]
Assuming the intended behavior of this change is to show the score screen early when pressing `escape` (which I use very often), I want to bring up the fact that it's not very effective on longer beatmaps (or beatmaps with larger object counts, I don't actually know which).

I tested it with a single object map and it works fine, then tried it on a longer map with more objects and the video below is what it looks like when I spam `escape` as it ends.

https://github.com/user-attachments/assets/a11fdc11-3dc8-4843-bfac-9d3001e50dda

_Map length: 04:04
Object count: 1152
[map link](https://osu.ppy.sh/beatmapsets/2112194#osu/4500445)_

The ideal behavior, speaking from a player's perspective, is one where `escape` can be pressed right after the last object, and the score screen appears on that keypress without delay. This also allows them to go back to the song select by hitting `escape` twice. 

Whether the score data is calculated in time to be displayed or not is a different issue, but it really shouldn't be holding back the skip-to-score-screen behavior like it currently is.
