### ISSUE TITLE
Editor test play inherits current ruleset instead of beatmap's ruleset

### ISSUE THREAD

**Issue by naoei** [ppy/osu#18084]
### Type

Game behaviour

### Bug description

When entering the editor, everything seems to be fine with the correct ruleset being fetched and applied. however, upon playtesting the beatmap, instead of the player using the correct ruleset for the beatmap, it chooses the current ruleset you have selected in the toolbar. 

### Screenshots or videos

https://user-images.githubusercontent.com/35349837/166618184-be238772-3a5c-4ca1-a571-305f94756995.mp4

### Version

2022.501.0

### Logs

Not entirely sure this is needed for this scenario.

[runtime.log](https://github.com/ppy/osu/files/8617678/runtime.log)

**Comment by peppy** [comment]
This does look like an issue which should be fixed, but I do wonder if it's going to be seen as a regression from users that use the editor to "practice" a beatmap. Probably out of scope for now (said mode should be introduced in the standard play flow, not the editor flow) but worth noting.
