### ISSUE TITLE
Strict tracking mod cannot exist in its current form

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18087]
### Type

Game behaviour

### Bug description

I didn't realise it was *removing slider ticks*.

It should not do this. It's changing the hitsounding and playability of a beatmap in a way that should not be done (for a mod that claims to only be making tracking stricter).

### Version

master

### Logs

-

**Comment by bdach** [comment]
There was a reason why this was done but I don't remember. @apollo-dw do you recall perhaps? One reason I can think of is that the ticks would become a purely-visual element (as in, hitting them only plays a sound, and doesn't have any actual gameplay implications). It might have had something to do with how classic judges sliders proportionally, but the mod is now incompatible with classic anyway, so it maybe doesn't matter anymore?

I guess they could be brought back but have an `Ignore{Hit,Miss}` judgement on them, just to play the sounds.

**Comment by apollo-dw** [comment]
Yeah, the decision was more-or-less cosmetic since the sliderticks didn't offer any gameplay: adding them back in should be straightforward if `Ignore{Hit,Miss}` works
