### ISSUE TITLE
Clicking on a guest profile brings you to some random guy

### ISSUE THREAD

**Issue by VladutzNVT** [ppy/osu#18105]
### Type

Other

### Bug description

clicking on a guest in the local scores brings you to some random guy with the name guest
need i say more

### Screenshots or videos

https://user-images.githubusercontent.com/103924738/166930352-1318ee1c-98df-4479-b6c8-e423188741fa.mp4

### Version

2022.501.0-lazer

### Logs

i found the bug this morning and my pc has been off for like 6 hours so logs are probably not important but here you go anyway
[performance.log](https://github.com/ppy/osu/files/8631536/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8631537/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8631538/updater.log)
[database.log](https://github.com/ppy/osu/files/8631539/database.log)
[network.log](https://github.com/ppy/osu/files/8631540/network.log)

**Comment by bdach** [comment]
#17509 didn't catch this I guess. `GuestUser` shouldn't be getting an id of 1:

https://github.com/ppy/osu/blob/b9d8d1b4f6cfb41857bb2e85086766273791d278/osu.Game/Online/API/APIAccess.cs#L456-L463

Fix is obvious - it should be getting `APIUser.SYSTEM_USER_ID` instead - but not sure whether past scores should be migrated over as well...?

**Comment by VladutzNVT** [comment]
cant you just disable clicking on the profile of guests?

**Comment by peppy** [comment]
Interestingly, `1` is the *correct* user id for guest. I think this is the result of falling back to username on an ID lookup failure (and the API doesn't expose `1` as guest itself).

Probably fine to mark as `SYSTEM_USER_ID` and call it a day though.

**Comment by VladutzNVT** [comment]
its still happening for me..

https://user-images.githubusercontent.com/103924738/167808470-5002a8be-118e-40f1-b99b-f6640d21bce0.mp4

also its a guest because my internet went out, i was offline

**Comment by bdach** [comment]
It's happening because past scores weren't migrated. It shouldn't happen anymore on new replays.

**Comment by VladutzNVT** [comment]
ohhhhhhhh ok
