### ISSUE TITLE
Collections disappear on exit

### ISSUE THREAD

**Issue by osulover9000** [ppy/osu#18113]
### Type

Other

### Bug description

I have to manually import my collections from stable every time I open the game as they disappear in lazer after exiting.

### Screenshots or videos

https://user-images.githubusercontent.com/104596572/167032550-b568aca4-8d26-4b53-a100-bf432ea8c2a7.mp4

### Version

Latest AppImage

### Logs

[database.log](https://github.com/ppy/osu/files/8636305/database.log)
[network.log](https://github.com/ppy/osu/files/8636302/network.log)
[performance.log](https://github.com/ppy/osu/files/8636303/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8636304/runtime.log)

**Comment by bdach** [comment]
Are you sure that the maps in the collections are present on lazer? As in, did you import all maps from stable before importing collections, and are the collections actually functioning properly before you exit?

Please attach the `collections.db` file also, so we can try reproducing ourselves.

**Comment by osulover9000** [comment]
Yes, the maps are all present in the collections and they do function properly. 
I didn't select all of the collections as some of them have thousands of maps in them which takes a while to load.

https://user-images.githubusercontent.com/104596572/167042959-9a05dcb7-d8c5-4d73-973f-1965528e0480.mp4

[collection.zip](https://github.com/ppy/osu/files/8636591/collection.zip)

**Comment by peppy** [comment]
Something is definitely wrong here. The loading and display should not be this slow...

**Comment by peppy** [comment]
@osulover9000 could you please also attach your `client.realm` file? thanks

**Comment by osulover9000** [comment]
Didn't see this my bad.
https://www.mediafire.com/file/5ufne7vm7rk5i0h/client.realm/file

**Comment by peppy** [comment]
@osulover9000 sorry for the delayed response. The `collections.db` file doesn't seem to actually contain your migrated collections.

Can you also attach the `collections.db` file from your *osu!stable* install so I can attempt to migrate them myself?
