### ISSUE TITLE
osu!lazer often freezes completely on song select

### ISSUE THREAD

**Issue by pratham-tharwani** [ppy/osu#18123]
### Type

Crash to desktop

### Bug description

Game freezes very often for me during regular play especially in the song select menu. Interestingly, the screen freezes but responses to mouse clicks and other inputs can be heard, sometimes to the point that the map seems to start playing even though the screen remains frozen on the song select menu. At this point repeatedly pressing 'esc' will usually close the game.

Windows Event Viewer shows the same error message after every crash:
```
Log Name:      Application
Source:        .NET Runtime
Date:          06-05-2022 22:03:44
Event ID:      1023
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-ERSK6KJ
Description:
Description: A .NET application failed.
Application: osu!.exe
Path: C:\Users\Pratham\AppData\Local\osulazer\app-2022.501.0\osu!.exe
Message: Cannot use file stream for [C:\Users\Pratham\AppData\Local\osulazer\app-2022.501.0\osu!.deps.json]: No such file or directory


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-05-06T16:33:44.6792236Z" />
    <EventRecordID>1981</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-ERSK6KJ</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Description: A .NET application failed.
Application: osu!.exe
Path: C:\Users\Pratham\AppData\Local\osulazer\app-2022.501.0\osu!.exe
Message: Cannot use file stream for [C:\Users\Pratham\AppData\Local\osulazer\app-2022.501.0\osu!.deps.json]: No such file or directory

</Data>
  </EventData>
</Event>
```

### Version

2022.501.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/8642223/network.log)
[performance.log](https://github.com/ppy/osu/files/8642224/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8642225/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8642226/updater.log)
[database.log](https://github.com/ppy/osu/files/8642227/database.log)

**Comment by frenzibyte** [comment]
Going by the advice in https://github.com/ppy/osu/discussions/15876#discussioncomment-1871333, have you tried updating your graphics drivers? if that doesn't help, please state your hardware specification.

**Comment by SonoSooS** [comment]
Considering that it's an Intel UHD, you have most likely hit the well known driver bug for Intel UHD 620/630, which causes the rendered frame to be not properly (or never) updated inside the window.

Try putting the game into windowed mode (Left ALT+ENTER), and unfocus the game to see what happens. When you click away from the game, it should start rendering the image normally, but as soon as you click into the game window again, it will stop displaying the game image.

Is this also what's happening to you?

**Comment by navidmafi** [comment]
Related (almost duplicate) with the exact behaviors said : https://github.com/ppy/osu/discussions/17098

**Comment by pratham-tharwani** [comment]
Updating driver did not help.

Tried what @SonoSooS said but on entering windowed mode the osu! windows just goes black with same mouse and keyboard input behaviour.

This behaviour does indeed seem to be consistent with https://github.com/ppy/osu/discussions/17098 as @navidmafi suggested.

System info as follows:
```
Processor	Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
Installed RAM	8.00 GB (7.81 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

```
Graphics processor is the integrated graphics (I do not have any discrete GPU).

**Comment by frenzibyte** [comment]
Probably best to track this at https://github.com/ppy/osu/discussions/17098 and remove answer until a definite solution is provided, given that the OP of that thread can no longer reproduce the issue here.

In general, driver-level bugs are not something which we can take action on, therefore should reside in a Q&A discussion thread at best.

**Comment by frenzibyte** [comment]
Closing, further discussion on potential solution can continue in https://github.com/ppy/osu/discussions/17098
