### ISSUE TITLE
color picker osu

### ISSUE THREAD

**Issue by Rystars** [ppy/osu#18136]
### Type

Cosmetic

### Bug description

The color picker osu is only black but the color that has been taken is not black

### Screenshots or videos

![Screenshot_2022-05-07-20-53-40-299_sh ppy osulazer](https://user-images.githubusercontent.com/96302690/167257727-00c055ce-3da1-4ab3-b73e-b0d01465467b.jpg)
![Screenshot_2022-05-07-20-53-21-098_sh ppy osulazer](https://user-images.githubusercontent.com/96302690/167257733-f378a0e1-1869-4e69-81f3-71d1a9d953ea.jpg)

### Version

2022.501.0

### Logs

[database.log](https://github.com/ppy/osu/files/8645320/database.log)
[network.log](https://github.com/ppy/osu/files/8645321/network.log)
[performance.log](https://github.com/ppy/osu/files/8645322/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8645323/runtime.log)

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/issues/14383
