### ISSUE TITLE
hitboxes on the mods/random/options buttons are a bit wacky

### ISSUE THREAD

**Issue by VladutzNVT** [ppy/osu#18159]
### Type

Other

### Bug description

this happens if you go below them at the bottom of the screen and move left/right

maybe its because the buttons are a bit diagonal?

### Screenshots or videos

https://user-images.githubusercontent.com/103924738/167303663-de8cfff6-e6ab-4788-8567-a85136e82664.mp4

### Version

2022.501.0-lazer

### Logs

this bug probably doesnt need the logs

**Comment by Susko3** [comment]
What are your settings for
- mouse confine mode
- window mode (fullscreen etc.)
- relative mouse mode?

What's your OS? (this question would have been answered by the logs)

**Comment by VladutzNVT** [comment]
i am on windows, i use raw input and i have 0.8 - 0.9 ui scale, i dont know what the rest mean

**Comment by Susko3** [comment]
Can repro with:
- borderless
- relative mode on
- cursor not confined

Caused by the cursor exiting the window on the edge, and then the OS warping the cursor back in the window (since it's past the bounds of the desktop/monitor). Not really a way to fix this, mouse confine works as advertised.

@VladutzNVT if you don't want to have this problem anymore, set `Screen mode` to `Fullscreen` or `Confine mouse cursor to window` to `Always` in settings.

**Comment by peppy** [comment]
Even in this state, I'd expect the framework to correctly handle things. Looks like a potential floating point / rounding issue. Would be interested to see the raw values being reported in this state.

**Comment by Susko3** [comment]
With sensitivity set to 1.02 to make the relative mouse events easily visible. The position can go far below `1079` pixels (the usual boundary when confined).

```cs
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (408; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (412; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (415; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (417; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (420.27; 1094.26)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (421.36; 1110.61)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (420; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (423; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (425; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (427; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (428.09; 1099.71)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (428; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (430; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (433; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (437; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (441; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (442.09; 1099.71)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (444.27; 1120.4199)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (442; 1079)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (442; 1093.17)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (442; 1107.3401)
[runtime] 2022-05-10 11:01:59 [verbose]: mouse position: (442; 1079)
```

One possible way to fix this is to selectively confine the cursor based on adjacent monitors. And only allow escaping the fullscreen borderless window when there is a monitor to go to. Seems overly complicated, maybe there's a better way.

![image](https://user-images.githubusercontent.com/16479013/167620386-dec3b797-b57c-4571-af9d-f0375cf1d78c.png)

**Comment by peppy** [comment]
Feels like in relative mode the cursor position sent by the handler should be confined. Is this only happening when there are multiple displays?

**Comment by Susko3** [comment]
This issue is specifically when the cursor is _not_ confined.

Multiple monitors were given as an example where not confining makes sense in borderless, as you want to be able to escape to the second monitor.

**Comment by peppy** [comment]
In the case of multiple monitors where the other monitor is not at the bottom edge (in the example case) I'd still expect things to work as expected, regardless of confining mode. Which is why I'm curious if the original poster has more than one monitor in the first place.

**Comment by VladutzNVT** [comment]
i have 1 monitor
