### ISSUE TITLE
Settings dropdown menu items flash gray on initial hover

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#18163]
### Type

Cosmetic

### Bug description

Noticed when scrolling through the languages dropdown.

### Screenshots or videos

![osu!_2022-05-08_13-20-02](https://user-images.githubusercontent.com/35318437/167314336-0c9c3b2f-9232-490e-8773-b1bbf7bc9c6c.gif)

### Version

Since 2022.418.0 / https://github.com/ppy/osu-framework/pull/5105

### Logs

N/A

**Comment by peppy** [comment]
Figured this might happen. I think the most correct fix is to make a framework change to ensure the colour is applied immediately (probably with a `FinishTransforms` or applied in `load()` instead). See https://github.com/ppy/osu-framework/blob/c2577ddaca1ccf5831d3d5af124ad54a06acdf73/osu.Framework/Graphics/UserInterface/Menu.cs#L838-L839.
