### ISSUE TITLE
Inconsistent behavior of dropdowns on playlists/multiplayer creation screens

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#18162]
### Type

Cosmetic

### Bug description

When creating a multiplayer room, dropdowns don't push the content that's below while playlists do.

### Screenshots or videos

| Multiplayer | Playlists |
| --- | --- |
| ![osu!_2022-05-08_12-38-38](https://user-images.githubusercontent.com/35318437/167312863-005cf9df-b6fa-44a4-a56e-e1d008ce6b4b.gif) | ![osu!_2022-05-08_12-39-11](https://user-images.githubusercontent.com/35318437/167312876-62976955-c052-43b4-b333-ddc7a067c29b.gif) |

### Version

2022.501.0

### Logs

N/A

**Comment by peppy** [comment]
I believe this was done intentionally for some reason in the past (to keep elements on the screen) but if that's not an issue then the right-hand behaviour is the preferred one.

**Comment by smoogipoo** [comment]
That's exactly it, yes. The video isn't really doing it justice, but at 16:9 opening at least the auto-start dropdown would send the "select beatmap" button off-screen.

I actually highly prefer the left-hand behaviour to be used in all cases. One reason is because it makes it easier to hit target when things aren't moving around.

**Comment by peppy** [comment]
> I actually highly prefer the left-hand behaviour to be used in all cases. One reason is because it makes it easier to hit target when things aren't moving around.

Is a valid consideration, but I really like the feel of them opening and pushing down content. At least in the global settings I think it's going to stay that way (generally you're interacting with only one setting when you go to do something there, so less of an issue with "aim").

For a screen like this where you're generally interacting with more elements the aim issue is more important. I can sway either way.

**Comment by smoogipoo** [comment]
Resolved via https://github.com/ppy/osu/pull/19065
