### ISSUE TITLE
Fail- and PauseOverlay can be open at the same time

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#1821]
I somehow managed to pause the second I failed a song and both overlays opened at the same time.
![qq](https://user-images.githubusercontent.com/27222621/34460853-607f5a64-ee1b-11e7-9d1c-0eab97079e0f.png)

**Comment by peppy** [comment]
Please no :(.

This should have been 100% rectified with the synchronous `TrackBass` logic.

**Comment by peppy** [comment]
Self assigning as I am a touch too familiar with this issue.

**Comment by FreezyLemon** [comment]
I can reproduce:

When the PlayerLoader switches to the player, some maps lag (especially if they have a lot of objects).
If I hit Esc (and wait for the lag to be over), the pause overlay opens, then the map clock seems to catch up, notice that I failed, and the fail overlay opens aswell. (I guess this only happens on slower machines)

**Comment by fangerm** [comment]
Same thing happend to me on today's build: https://i.imgur.com/0J2Zklp.png
FOr me, it happens when pressing esc just before time as
