### ISSUE TITLE
Beatmap search filter header strings don't got to new line when they are too long

### ISSUE THREAD

**Issue by LukynkaCZE** [ppy/osu#18223]
### Type

Cosmetic

### Bug description

beatmap search filter header strings don't got to new line when they are too long thus cause overlap with beatmap search filter items

This doesn't happen in English but its problem in some other translations.
On website this isn't a problem.

### Screenshots or videos

osu!lazer
![image](https://user-images.githubusercontent.com/48604271/167812571-3df2e33a-0fa4-43aa-9245-16189baf8bf6.png)
![image](https://user-images.githubusercontent.com/48604271/167812642-b1c5087f-e388-4bfe-85d8-41efb82cb597.png)

osu!website
![image](https://user-images.githubusercontent.com/48604271/167812703-f821a6c2-f11e-4c19-9eca-334b30d09000.png)

### Version

2022.509.0

### Logs

[network.log](https://github.com/ppy/osu/files/8668411/network.log)
[performance.log](https://github.com/ppy/osu/files/8668412/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8668413/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8668415/updater.log)
[database.log](https://github.com/ppy/osu/files/8668416/database.log)

**Comment by frenzibyte** [comment]
Going to note that there's already a discussion thread in https://github.com/ppy/osu/discussions/15452 which covers a list of places in which translation doesn't fit. Think it may be best just listing all of the different places there to potentially solve it one go, or at least not have many leading to the same goal.

**Comment by smoogipoo** [comment]
Cool, I've posted the above screenshots in there and will close this.
