### ISSUE TITLE
Not getting PP and globally scored on maps after playing them with higher score of for the first time

### ISSUE THREAD

**Issue by MCHuskins** [ppy/osu#18232]
### Type

Other

### Bug description

What is happing is when I beat a map that I have **not** beaten or gotten a higher score than I did before I don't get the PP and it does not update on the website or the global list thing. I checked the version, restarted my computer, and uninstall and reinstalled also I checked on normal osu and it worked as it should so it is just lazer. Lazer has worked for me in the past, I think. I also tried with classic on and no modes. 

also why no smoke? 

thanks for the help! love the game

how I check to see if it was working and it was not. 

### Screenshots or videos

![IMG-3506](https://user-images.githubusercontent.com/38637043/167976497-10796d45-fdf1-4dfd-a8f0-059a000ec7d4.JPG)
![IMG-3504](https://user-images.githubusercontent.com/38637043/167976504-a26ee670-0ef9-42a4-99de-b46c5eb88d19.JPG)
![IMG-3508](https://user-images.githubusercontent.com/38637043/167976723-b5e4c8ac-61bd-4890-b4a1-2584e6b6403d.JPG)
![IMG-3510](https://user-images.githubusercontent.com/38637043/167976749-384fff91-a3c1-42ac-a849-01fed6822f73.JPG)
the one that has pp is from normal the some of the others should but don't 
![IMG-3512](https://user-images.githubusercontent.com/38637043/167976743-05d33d8b-d227-4be0-a011-dd56e376e433.JPG)

### Version

2022.509.0-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/8674465/updater.log)
[database.log](https://github.com/ppy/osu/files/8674466/database.log)
[network.log](https://github.com/ppy/osu/files/8674467/network.log)
[performance.log](https://github.com/ppy/osu/files/8674468/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8674469/runtime.log)

**Comment by smoogipoo** [comment]
> I don't get the PP

Lazer scores currently don't contribute to PP.

> also why no smoke?

Not implemented yet https://github.com/ppy/osu/issues/5721.

**Comment by MCHuskins** [comment]
oh sorry did not know 
(think that should be easier to find out and should be added)

**Comment by MCHuskins** [comment]
also what about smoke
