### ISSUE TITLE
New mod select menu in playlists glitched

### ISSUE THREAD

**Issue by NagaseIori** [ppy/osu#18243]
### Type

Game behaviour

### Bug description

The mod select menu in playlists is wiggling.

### Screenshots or videos

https://user-images.githubusercontent.com/31349569/168103461-9c0561d5-71d7-4e4d-be4e-2caaec7d0da6.mov

### Version

2022.509.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8680126/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8680127/updater.log)
[database.log](https://github.com/ppy/osu/files/8680128/database.log)
[network.log](https://github.com/ppy/osu/files/8680129/network.log)
[performance.log](https://github.com/ppy/osu/files/8680130/performance.log)

**Comment by frenzibyte** [comment]
Confirmed #18161 resolved this.
