### ISSUE TITLE
Rewinding when Auto Mod is playing a map can sometimes cause it to fail.

### ISSUE THREAD

**Issue by LiveLM** [ppy/osu#1825]
When Auto Mod is playing a map, rewinding can cause it to fail.
This may be a beatmap specific issue, since it's easy to reproduce the issue [on this map](https://osu.ppy.sh/b/678444&m=0), but not so easy on others.
[Video demonstrating issue](https://streamable.com/efnnb)
If a log file is needed, what log should I provide?

**Comment by peppy** [comment]
I believe this is a known issue. You were playing on osu! mode, yeah?

**Comment by LiveLM** [comment]
Yes, but I just tested, and the issue is also present on Mania. Taiko doesn't seem affected.

**Comment by TemTemmie** [comment]
the map may have elements at the same  time causing auto to miss

**Comment by ticotaco72** [comment]
![inkedosu_2018-06-25_22-43-18-2_li](https://user-images.githubusercontent.com/32620809/41875083-1dc20124-78ca-11e8-9c92-61ad61fe90ab.jpg)

It makes number of clicks increase unnormally too.
If you rewind play the number should go lower too.

**Comment by smoogipoo** [comment]
Seems like this has been fixed (auto can't fail during playback + replay playback has had a number of improvements). It's not perfect but some random misses are present during fast forward too.
