### ISSUE TITLE
osu fps drop

### ISSUE THREAD

**Issue by kli75962** [ppy/osu#18258]
### Type

Performance

### Bug description

osu fps drop to 10-30fps sometimes when gaming. I need to stop and alt+tab to go out and come back
It happen a long time ago. But I play osu lazer this day and I realize that only osu! will drop fps but laser don't.

### Version

b20220424

### Logs

[update_success.log](https://github.com/ppy/osu/files/8692693/update_success.log)
[runtime.log](https://github.com/ppy/osu/files/8692694/runtime.log)
[session.log](https://github.com/ppy/osu/files/8692695/session.log)

**Comment by bdach** [comment]
* This repository doesn't accept issue reports about stable.
* Please read https://osu.ppy.sh/wiki/en/Performance_troubleshooting
