### ISSUE TITLE
Free mods don't appear correctly in playlists with multiple gamemodes

### ISSUE THREAD

**Issue by spdragon0** [ppy/osu#18253]
### Type

Game behaviour

### Bug description

In playlists, players can't see free/extra mods for gamemodes other than the one already selected. This bug appears in playlists with multiple gamemodes.
The screenshot shows an empty mod select screen for osu!catch after opening the playlist with osu!standard selected.

### Screenshots or videos

![osu_2022-05-13_16-27-58](https://user-images.githubusercontent.com/105521937/168392092-b2008138-c785-470e-a7ee-c06f6a6442cb.png)

### Version

2022.509.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8691446/database.log)
[network.log](https://github.com/ppy/osu/files/8691447/network.log)
[performance.log](https://github.com/ppy/osu/files/8691448/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/8691449/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/8691450/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8691451/runtime.log)

**Comment by bdach** [comment]
I checked latest master and this is already resolved by #18230. Will be fixed in next release.
