### ISSUE TITLE
MSbuild fails on Linux, missing SharpCompress

### ISSUE THREAD

**Issue by IceHusky** [ppy/osu#1826]
Running nuget restore and then msbuild on an unchanged git clone creates the following error:

"/home/b/osu/osu.sln" (default target) (1) ->
"/home/b/osu/osu.Game/osu.Game.csproj" (default target) (2) ->
(CoreCompile target) -> 
  Rulesets/Scoring/ScoreStore.cs(13,7): error CS0246: The type or namespace name 'SharpCompress' could not be found (are you missing a using directive or an assembly reference?) [/home/b/osu/osu.Game/osu.Game.csproj]

Manually installing SharpCompress using nuget does not help.
Running Mono Alpha 3.8.0, also tried 3.4.1 and having the same issue. Nuget 4.4.1.

**Comment by IceHusky** [comment]
A workaround to the issue is entering the packages directory and installing SharpCompress version 0.18.1 specifically.

**Comment by VPeruS** [comment]
Didn't have such issue with mono 5.4 + nuget 4.3. Check that you have SharpCompress in packages/ dir after "nuget restore"

**Comment by IceHusky** [comment]
Odd hiccup I guess, recloned and went through the process again and build was successful without workaround. Closing.
