### ISSUE TITLE
Issues with Hiddenmod

### ISSUE THREAD

**Issue by AliceOnAcid** [ppy/osu#1827]
Hello Peppy, It is me again. C: 

Been hyped when I saw that Hidden was implemented so I tried it and it does have a better feel than the hidden from stable, tho sometimes the sliders start circles and follow ball isn't showing at all, and the slider itselft having troubles to show up. 

https://streamable.com/h4gfg

**Comment by peppy** [comment]
This is known. Hidden is still a WIP and will see improvements over the coming days/weeks. The build which I made live has temporary changes which actually cause this breakage to some extent, so I'm just going to close this issue for now.
