### ISSUE TITLE
osu!lazer does not open

### ISSUE THREAD

**Issue by Facuisawp** [ppy/osu#18282]
### Type

Crash to desktop

### Bug description

I installed the latest version of osu!lazer 2022.515.0. I install the .exe, everything is fine until when I want to open it, it gives me an error saying that it stopped working.

pc specs: 
processor: AMD A4-3300 APU with Radeon(tm) HD Graphics 2.50 Ghz
ram: 4gb
type of system: 64 bits
graphic card: don't have
windows: 7

### Screenshots or videos

![image](https://user-images.githubusercontent.com/102629282/168483158-5a0888cd-d94d-49e8-bbbd-4ee7b1aae14c.png)

### Version

2022.515.0.

### Logs

[update_success.log](https://github.com/ppy/osu/files/8695398/update_success.log)
[database.log](https://github.com/ppy/osu/files/8695399/database.log)
[runtime.log](https://github.com/ppy/osu/files/8695400/runtime.log)
[session.log](https://github.com/ppy/osu/files/8695401/session.log)

**Comment by jai-x** [comment]
osu!lazer does not currently support Windows 7 due to dependency on RealmDB: https://github.com/ppy/osu/issues/13769
This is noted in the readme document.

![image](https://user-images.githubusercontent.com/8362491/168483552-343e3218-e52b-4a37-a4f7-e0f102bab838.png)
