### ISSUE TITLE
A rather destructive spinner behavior

### ISSUE THREAD

**Issue by Hexality** [ppy/osu#18316]
### Type

Game behaviour

### Bug description

barely shaking the cursor when centered to the middle of the spinner makes it go brr.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/17398632/168898475-969b7216-a375-4d71-888f-0963c797e891.png)

https://user-images.githubusercontent.com/17398632/168899056-fc1b4f56-9dcc-43ab-8b53-8ea9b82f7536.mp4

### Version

2022.512.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8711184/database.log)
[network.log](https://github.com/ppy/osu/files/8711185/network.log)
[performance.log](https://github.com/ppy/osu/files/8711186/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8711187/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8711188/updater.log)

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/issues/8224

**Comment by Hexality** [comment]
has nothing to do with tapping 2 buttons

**Comment by Hexality** [comment]
you literally just need to center the cursor and goes up to ~1700RPM
issues looks a bit different here.
