### ISSUE TITLE
Inconsistent behaviour between "Back" button as escape-key and other buttons in song-select

### ISSUE THREAD

**Issue by Sr3qt** [ppy/osu#18349]
### Type

Game behaviour

### Bug description

The bug occurs when I have written something in the search bar and I open the collections menu. If I use the back button, which is escape by default, it will first close the collections pop-out and when I press it again it will clear the text. However, if I bind any other button for back it I will immediatly put me back to the main menu. In the video I show first what happens with when pressing Mouse 4, the other default button for "back", and then what happens when pressing escape twice.

I have also noticed that when I unbind "escape" from the "back" button, it will still close the collections window, but will not clear text. I have no other binds for "escape".

The problem I have with this bug is that, when I try to clear text and have the collections menu open I get sent to the main menu, which is not what I want and it happens a surprising number of times. I would rather that all keys bound to the "back" button closes the collections menu, just like the "escape" key, or alternatively that the "back" button ignores whether the collections menu is open and clears the text regardless if the menu is open or not.

I don't know if I need to mention this but I play on Windows 1440p and I tested with both Fullscreen and Borderless Windowed. 

I would like to by end by saying I appreciate everything you devs do to make the game!

### Screenshots or videos

https://user-images.githubusercontent.com/105977398/169652958-c73ebae9-388e-4cbe-945a-dc3583677867.mp4

### Version

osu! 2022.515.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/8747702/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8747703/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8747704/updater.log)
[database.log](https://github.com/ppy/osu/files/8747705/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8747706/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8747707/network.log)

**Comment by bdach** [comment]
The following diff fixes this, but I'm not 100% sure we want this behaviour on every single dropdown in the game:

```diff
diff --git a/osu.Game/Graphics/UserInterface/OsuDropdown.cs b/osu.Game/Graphics/UserInterface/OsuDropdown.cs
index 4e391c8221..23e05c7ccc 100644
--- a/osu.Game/Graphics/UserInterface/OsuDropdown.cs
+++ b/osu.Game/Graphics/UserInterface/OsuDropdown.cs
@@ -12,9 +12,12 @@
 using osu.Framework.Graphics.Containers;
 using osu.Framework.Graphics.Sprites;
 using osu.Framework.Graphics.UserInterface;
+using osu.Framework.Input.Bindings;
+using osu.Framework.Input.Events;
 using osu.Framework.Localisation;
 using osu.Game.Graphics.Containers;
 using osu.Game.Graphics.Sprites;
+using osu.Game.Input.Bindings;
 using osu.Game.Overlays;
 using osuTK;
 using osuTK.Graphics;
@@ -31,7 +34,7 @@ public class OsuDropdown<T> : Dropdown<T>
 
         #region OsuDropdownMenu
 
-        protected class OsuDropdownMenu : DropdownMenu
+        protected class OsuDropdownMenu : DropdownMenu, IKeyBindingHandler<GlobalAction>
         {
             public override bool HandleNonPositionalInput => State == MenuState.Open;
 
@@ -275,6 +278,23 @@ public bool Hovering
             }
 
             #endregion
+
+            public bool OnPressed(KeyBindingPressEvent<GlobalAction> e)
+            {
+                if (e.Repeat) return false;
+
+                if (e.Action == GlobalAction.Back)
+                {
+                    State = MenuState.Closed;
+                    return true;
+                }
+
+                return false;
+            }
+
+            public void OnReleased(KeyBindingReleaseEvent<GlobalAction> e)
+            {
+            }
         }
 
         #endregion
```

**Comment by Sr3qt** [comment]
I should start by saying I don't know what that code means, but I assume from your response that this fix will make any key bound to "back" also close drop down menus.
Would it not makes sense that since the escape-key closes drop down menus and is by default bound to "back" that the second option for binding "back" should be functionally the same as the escape-key? What i mean is, that since escape works fine bound to "back" and being able to close drop down menus, that any other button would work just as well for the job?

**Comment by peppy** [comment]
Applying to all `OsuDropdown`s sounds sensible.
