### ISSUE TITLE
`TestMostInSyncUserIsAudioSource` fails whenever one more test is added before it

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#18352]
I have absolutely no idea what's going on, but opening this issue to at least track it.

https://user-images.githubusercontent.com/22781491/169660049-14cc9604-89ed-499d-a3da-d116c8cf9191.mp4

**Comment by peppy** [comment]
Have you run through visual tests? It might reveal what's going on better. Probably some left over state.

**Comment by frenzibyte** [comment]
Tried going through visual tests in the same exact order as the headless ones and couldn't reproduce. Perhaps the headless game clock is involved here.

**Comment by bdach** [comment]
I couldn't reproduce this on my machine at all period, for what it's worth.

**Comment by peppy** [comment]
Maybe a local rider / project issue. I've seen something like this before and a rider restart usually fixes.

**Comment by frenzibyte** [comment]
Indeed, I can't reproduce this anymore. Closing as invalid for now.
