### ISSUE TITLE
Imported beatmap offset is very big

### ISSUE THREAD

**Issue by SonoSooS** [ppy/osu#18358]
### Type

Game behaviour

### Bug description

There is a single beatmap I encountered which seems to have an enormous delay in notes compared to the audio. The delay in fact is so big, that it's out of range for the "local beatmap offset" slider.

I deleted it and re-imported it just in case it was a problem of the importers of older osu!lazer versions, but no, this issue still happens in the current version.

The beatmap works "as intended" on osu!stable.

I can't link the original beatmap because I'm still having issues getting myself unbanned, so hopefully this issue is not caused by a local copy corruption: [39085 Tony Harnell - City Escape (Classic Remix).zip](https://github.com/ppy/osu/files/8748467/39085.Tony.Harnell.-.City.Escape.Classic.Remix.zip)

### Version

2022.515.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/8748476/runtime.log)
[performance.log](https://github.com/ppy/osu/files/8748477/performance.log)
[database.log](https://github.com/ppy/osu/files/8748478/database.log)
[updater.log](https://github.com/ppy/osu/files/8748479/updater.log)
[performance-draw.log](https://github.com/ppy/osu/files/8748480/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/8748481/performance-update.log)

**Comment by Sublimelime** [comment]
I'm able to reproduce this using the [version downloaded from the site](https://osu.ppy.sh/beatmapsets/39085#osu/125018). Offset is certainly way off.

**Comment by frenzibyte** [comment]
I would say given that this is the first time this type of issue comes and the beatmap in question is a graveyard one, there's the possibility for this to be an issue with the beatmap itself and osu!(stable) hasn't been affected by it for one reason or another.

Therefore I think it's best moving it to a discussion thread until the underlying issue is figured out, at which point it can be moved to an issue thread for tracking as a solvable issue and discussing the right solution here. 

Right now I'm unsure if this issue thread deserves remaining as-is with only a graveyard beatmap atatched.

**Comment by peppy** [comment]
The beatmap file looks pretty sane, so may be audio related. Requires further investigation. Fine to leave as issue.

**Comment by SonoSooS** [comment]
I re-encoded the mp3 with ffmpeg, and now it works correctly in lazer.

It seems like osu!stable handled it properly, as it works the same there, and ffmpeg fixed the offset, so this must be something weird in lazer.

**Comment by peppy** [comment]
One thing to try would be disabling the `OLDGAPS` workaround and see what happens (https://github.com/ppy/osu-framework/blob/11cc0d0400792b84f5cdca3e044125a0160f49a1/osu.Framework/Audio/AudioManager.cs#L378-L379).

**Comment by bdach** [comment]
Disabling `OLDGAPS` does nothing useful here. This appears to actually be another case of #10671:

```
$ mediainfo Escape\ from\ the\ City\ -\ Classic\ Remix.mp3 
General
Complete name                            : Escape from the City - Classic Remix.mp3
Format                                   : MPEG Audio
File size                                : 2.31 MiB
Duration                                 : 2 min 31 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 128 kb/s
Album                                    : Sonic Generations
Track name                               : Escape from the City - Classic Remix
Performer                                : Summer of Sonic
Genre                                    : Game
Released date                            : 2011
Encoded date                             : UTC 2011-11-08 22:12:35
Writing library                          : Lavf53.18.0

Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Duration                                 : 2 min 31 s
Bit rate mode                            : Variable
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Frame rate                               : 38.281 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 2.31 MiB (100%)
```

Note the "variable bit rate" parts. Closing as duplicate.

**Comment by peppy** [comment]
The weird thing is, as mentioned in the other thread, the `PRESCAN` bass flag should already be handling this correctly. In the previous case, it was an ogg file, but this time it's an mp3...

We're definitely going to have to report this upstream if it becomes a more common issue.
