### ISSUE TITLE
Tournament client does not fetch player information based on the current gamemode

### ISSUE THREAD

**Issue by LeoFLT** [ppy/osu#18363]
### Type

Other

### Bug description

The tournament client uses each player's preferred game mode (as set on the user's profile) when querying user information instead of the applied ruleset. This is obviously not expected and can lead to very weird results on the Seeding tab (such as 2 players having the same rank at the same time, or being rank 100k when in reality they are top 100 on the game mode).

### Version

2022.306.0.0

### Logs

[network.log](https://github.com/ppy/osu/files/8750325/network.log)

**Comment by peppy** [comment]
Could you please provide the `bracket.json` file used to repro this?

**Comment by LeoFLT** [comment]
[bracket.zip](https://github.com/ppy/osu/files/8750864/bracket.zip)
bracket.json contains the ruleset info and user IDs, bracket.json (populated) is the resulting file after importing
