### ISSUE TITLE
Catmull sliders have a wrong shape around their stating point

### ISSUE THREAD

**Issue by MrWither83** [ppy/osu#18366]
### Type

Game behaviour

### Bug description

Likely because of #18321, some catmull sliders have an additional path at the start of the slider.

Maps where the issue can be encountered : 
https://osu.ppy.sh/beatmapsets/25#osu/165
https://osu.ppy.sh/beatmapsets/31#osu/100

### Screenshots or videos

![image](https://user-images.githubusercontent.com/52672543/169790547-b6f4e045-89a1-4312-b50c-b146541d93a0.png)
![image](https://user-images.githubusercontent.com/52672543/169790727-d51b1b7b-0d3f-446f-9d5d-2c814c168911.png)
![image](https://user-images.githubusercontent.com/52672543/169791243-1d5e62ff-944d-4da5-ac3f-3cbd18199ad5.png)

### Version

2022.523.0-lazer

### Logs

[performance-draw.log](https://github.com/ppy/osu/files/8753437/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/8753438/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8753439/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8753440/updater.log)
[database.log](https://github.com/ppy/osu/files/8753441/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8753442/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8753443/network.log)
[performance.log](https://github.com/ppy/osu/files/8753444/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8753445/performance-audio.log)

**Comment by bdach** [comment]
Not sure how this is happening yet but it looks like the first control point may be duplicating itself somehow and causing this...

https://user-images.githubusercontent.com/20418176/169905454-fc1501b8-b9da-473f-ad39-4d6e11aa3367.mp4

Slider depicted above is given by:

```
416,288,38708,6,0,C|416:288|352:160|256:352|192:160,1,560
```

so not sure how a fifth control point has spawned there.

**Comment by smoogipoo** [comment]
Yeah, I was aware of this but forgot to test it. Basically this logic shouldn't be applied to the first control point.
