### ISSUE TITLE
Metronome's movement is not smooth when the track is slowed down.

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#18365]
### Type

Cosmetic

### Bug description

/

### Screenshots or videos

https://user-images.githubusercontent.com/53081750/169790360-3c8444ab-a855-49a4-97da-256d64446ef4.mov

### Version

2022.523.0

### Logs

[database.log](https://github.com/ppy/osu/files/8753422/database.log)
[network.log](https://github.com/ppy/osu/files/8753423/network.log)
[performance.log](https://github.com/ppy/osu/files/8753424/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8753425/runtime.log)

**Comment by frenzibyte** [comment]
This can be fixed by passing the `EditorClock` to the metronome to be affected by it, but unsure if that solution sounds good (cc @peppy):
```diff
diff --git a/osu.Game/Screens/Edit/Timing/MetronomeDisplay.cs b/osu.Game/Screens/Edit/Timing/MetronomeDisplay.cs
index 7b0b8440e6..ff130e798b 100644
--- a/osu.Game/Screens/Edit/Timing/MetronomeDisplay.cs
+++ b/osu.Game/Screens/Edit/Timing/MetronomeDisplay.cs
@@ -32,7 +32,7 @@ public class MetronomeDisplay : BeatSyncedContainer
         private OverlayColourProvider overlayColourProvider { get; set; }
 
         [BackgroundDependencyLoader]
-        private void load()
+        private void load(EditorClock editorClock)
         {
             const float taper = 25;
             const float swing_vertical_offset = -23;
@@ -43,6 +43,7 @@ private void load()
             Margin = new MarginPadding(10);
 
             AutoSizeAxes = Axes.Both;
+            Clock = editorClock;
 
             InternalChildren = new Drawable[]
             {
```

I would assume it makes sense because normally we don't want the editor clock to affect the UI of the editor, but metronomes are an exception because they animate based on the track/clock.

**Comment by peppy** [comment]
That won't work. Resetting will break, and so will changing BPM etc.

The metronome is supposed to keep its own time, not use the track time. Consuming only the rate is the correct path forward.

**Comment by frenzibyte** [comment]
Right, I see. Consuming only the rate (and fall back to 1 if paused) should do for now.
