### ISSUE TITLE
osu interperts one joystick button as multiple

### ISSUE THREAD

**Issue by ciulinuwu** [ppy/osu#18361]
### Type

Game behaviour

### Bug description

When I bind a key for my Xbox One Wireless Controller, it thinks I smashed all the buttons.

### Screenshots or videos

https://user-images.githubusercontent.com/79811506/169696709-772ebdbe-6cb4-412f-a01e-0d3d658e6060.mp4

### Version

2022.515.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/8749465/network.log)
[performance.log](https://github.com/ppy/osu/files/8749466/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8749467/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8749468/updater.log)
[database.log](https://github.com/ppy/osu/files/8749469/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8749470/legacy-ipc.log)

**Comment by frenzibyte** [comment]
As you can see in the key binding buttons, it's the axes which are shown as pressed (i.e. left/right stick or triggers). You may want to consider increasing the dead-zone.

**Comment by ciulinuwu** [comment]
> As you can see in the key binding buttons, it's the axes which are shown as pressed (i.e. left/right stick or triggers). You may want to consider increasing the dead-zone.

Oh. Increasing it helped, thank you!
