### ISSUE TITLE
Display exception on Android12

### ISSUE THREAD

**Issue by zjw666nwn** [ppy/osu#18387]
### Type

Performance

### Bug description

open Android osu!

### Screenshots or videos

https://user-images.githubusercontent.com/64683635/169956227-23248737-6195-4221-a57a-73015df6ef85.mp4

### Version

new download(cannot get version)

### Logs

[database.log](https://github.com/ppy/osu/files/8759789/database.log)
[network.log](https://github.com/ppy/osu/files/8759790/network.log)
[performance.log](https://github.com/ppy/osu/files/8759791/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8759792/runtime.log)

**Comment by zjw666nwn** [comment]
use Dimensity 820

**Comment by zjw666nwn** [comment]
Maybe the device doesn't support it

**Comment by bdach** [comment]
The video looks so broken that I think this can only realistically be due to broken graphics drivers or a lack of proper opengl support. I don't know that we can do anything about this, I'd say this issue should be closed.
