### ISSUE TITLE
Advanced Skin Menu for Specific Mod Combinations

### ISSUE THREAD

**Issue by takoz53** [ppy/osu#1838]
- Allows users to pre-set Skins for specific Mod combinations
- No more skin changing everytime you want to try other mods
- **Turn on/off hitlight** for each combination since this might be annoying in some skins
- **A search function** implemented to **find skins faster and easier**
- Lazy people can be even lazier!
- **Example:** 
Selected Combination: **HDDT**
Selected Skin for combination: **HDDTSkin2018**

I've come up with a template design of how everything should look like on the old client.
The template design should probably be able to explain what I've just been trying to explain here.
![finalproduct 1680x1050 ratio](https://user-images.githubusercontent.com/16865864/34509653-d6e58592-f04c-11e7-8e12-3e14147ca358.png)

**Comment by smoogipoo** [comment]
While we may consider having more skin customisation in the future, I'm backlogging + marking this as low prio since the rest of the game should come first.

**Comment by peppy** [comment]
Different skins for different mods isn't something I can get behind, personally. Making switching skins easy is as far as we should be going.
