### ISSUE TITLE
1 Key no longer deselects all mods when in mod menu

### ISSUE THREAD

**Issue by quantified-null** [ppy/osu#18389]
### Type

Game behaviour

### Bug description

I'm unsure if this is a bug, or an intended removal of a feature, but in previous versions of osu!stable and osu!lazer, you could press the "1" key in the mod menu to deselect all mods, but this seems to have been removed with the introduction of the new mods user interface. 

### Version

2022.523.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8761047/database.log)
[network.log](https://github.com/ppy/osu/files/8761048/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/8761049/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8761050/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8761051/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8761052/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/8761053/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8761054/runtime.log)

**Comment by peppy** [comment]
You can rebind this in settings. The default is backspace.
