### ISSUE TITLE
osu! will freeze if you alt tab on startup with a laptop using Optimus 

### ISSUE THREAD

**Issue by Makishanuto** [ppy/osu#1839]
- A laptop using Optimus technology (Intel + NVIDIA) will result in a freeze. No error is detected.
- This only occurs if a third party overlay (i.e Discord is enabled).

- Turning off Optimus/Overlay will fix this issue.

**Comment by smoogipoo** [comment]
@peppy why did you label this as "missing details"? Please explain along with labelling.

**Comment by peppy** [comment]
missing any kind of logs/debug info

**Comment by Makishanuto** [comment]
Fair enough. Not really sure how to provide any sort of logs, as no error is reproduced.  The only thing I have is an image attached below, showing that the drawFrames takes up most of the threads.
![unknown](https://user-images.githubusercontent.com/16981265/34550615-9de092e0-f0cf-11e7-81dd-51feb2daa697.png)

This probably should go in low priority, since I'm not sure specifically what about drawFrame() is being affected.

**Comment by peppy** [comment]
It could be the combination of any number of factors, including OS or other overlays also present on your system. Need more reports or more low-level debug. Likely not something at our end, though.

**Comment by smoogipoo** [comment]
Pause the execution and post the callstacks for all threads. https://msdn.microsoft.com/en-us/library/a3694ts5.aspx

**Comment by TemTemmie** [comment]
third party overlays make the game run in top of the overlay which can make osu consume more ram. try reporting the bug to the overlay's author

**Comment by Makishanuto** [comment]
Nope, I don't think it's present anymore. Anyways, the issue was so minor
that I don't really think it really would have been worth that much
development time on it.

**Comment by peppy** [comment]
Closing this for now.
