### ISSUE TITLE
"Bug on Mobile Version"

### ISSUE THREAD

**Issue by BaNaN4Ik-STOP** [ppy/osu#18416]
### Type

Other

### Bug description

On the mobile version, it normally does not look for ways to download and create maps.

**Please correct!!!**

### Screenshots or videos

https://drive.google.com/file/d/15CBozmMfbsTtBNkRKIgJCsshfgXPyLUI/view?usp=drivesdk

### Version

0.1

### Logs

"Nothing"

**Comment by bdach** [comment]
#11911
