### ISSUE TITLE
Leaderboard loads results multiple times

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#1841]
The leaderboard is having a seizure if you click different tabs quickly before the previous result is shown.
Video: https://streamable.com/iho9j

**Comment by peppy** [comment]
https://github.com/ppy/osu/pull/1829/commits/4f8a830fbf341d0bc9a57376b4f518b6a106dfe4#diff-480104f4dc249aec7e7aec4d2b8b389dR112 this should probably be moved before the equality check

**Comment by Aergwyn** [comment]
Ok, then I'm on it right now.

**Comment by Aergwyn** [comment]
Or not. Doing so fixes the mutliple loads but causes recognizable lag instead. I'll have to go deeper.

**Comment by Aergwyn** [comment]
Nvm, got rekt by debug. PR coming.
