### ISSUE TITLE
osu!Lazer Multiplayer random user kick

### ISSUE THREAD

**Issue by Pandxyz** [ppy/osu#18425]
### Type

Game behaviour

### Bug description

Players are getting randomly kicked while being in a osu!Lazer Multiplayer lobby or match. This can happen also to the Host of the match. We found the bug yesterday, when players we've played with randomly got kicked, and thought, that the Host wanted them to be out of the lobby. That issue happens randomly. Most players that I've played with had it often, I had it only 3 times. The issue happens **more often** when the lobby has **more** than 4 players in it.  

### Screenshots or videos

My POV of the issue:
https://youtu.be/jEnQ1C5uNoM
Error Message:
![Screenshot 2022-05-26 163537 PNG](https://user-images.githubusercontent.com/104238285/170534029-6ec90c7d-3678-4e10-a669-8e5f640d5b37.jpg)

### Version

osu! 2022.523.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8780572/database.log)
[network.log](https://github.com/ppy/osu/files/8780573/network.log)
[performance.log](https://github.com/ppy/osu/files/8780577/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8780578/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8780579/updater.log)

**Comment by peppy** [comment]
This is known and due to cloudflare dropping websocket connections. We have a solution in the works which should be deployed in a week or so.

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/14365
