### ISSUE TITLE
Sensitivity

### ISSUE THREAD

**Issue by EzPzLemonSquez** [ppy/osu#1843]
I tried to play with my tablet but the sensitivity was way too high, in normal osu I have it I think at 3.26x and when i put it to 0.1x in Lazer it was almost the same. Major issue ... please fix!

**Comment by fangerm** [comment]
It's a known issue that absolute positioning devices don't work with raw input. See #1301

**Comment by peppy** [comment]
Closing as duplicate of #1301.
