### ISSUE TITLE
Chatting with <username> overflows on the new chat overlay when the username is too long

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#18430]
### Type

Cosmetic

### Bug description

On the new chat overlay "Chatting with <username>" overflows when the username is too long.

### Screenshots or videos

![osu!_gLyg1RZfE0](https://user-images.githubusercontent.com/43358824/170610046-82b21de4-aed9-460b-bf66-b474cd22b224.png)

### Version

commit 0d760e707e605616e8dd6b918c3a0283b680559d

### Logs

[database.log](https://github.com/ppy/osu/files/8783215/database.log)
[network.log](https://github.com/ppy/osu/files/8783217/network.log)
[performance.log](https://github.com/ppy/osu/files/8783218/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8783220/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8783221/updater.log)

**Comment by peppy** [comment]
Was known from the outset and requires design reconsideration.

@arflyte
