### ISSUE TITLE
Opening Notification overlay closes First run setup wizard

### ISSUE THREAD

**Issue by LukynkaCZE** [ppy/osu#18449]
### Type

Game behaviour

### Bug description

Opening Notification overlay closes first run setup wizard
This is problem after the game updates. First, the first run setup wizard opens and then you get the changelog notification which opens notification overlay thus closes the first run setup wizard

Its also problem when importing content from stable version using the first setup wizard. Importing from stable opens the notification overlay with progress bar and closes the first run setup wizard

### Screenshots or videos

https://user-images.githubusercontent.com/48604271/170805380-29501031-e766-4b56-9d32-348473341ead.mp4

https://user-images.githubusercontent.com/48604271/170805384-3fc5730d-452b-46c3-bbbd-51751d5a180e.mp4

https://user-images.githubusercontent.com/48604271/170805385-ed25f0cd-3e27-4144-a453-74bb29b9db66.mp4

### Version

2022.523.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8790294/runtime.log)
[performance.log](https://github.com/ppy/osu/files/8790295/performance.log)
[network.log](https://github.com/ppy/osu/files/8790296/network.log)

**Comment by frenzibyte** [comment]
Importing from stable probably shouldn't open notifications, similar to how it's done in the "beatmaps" screen.

**Comment by LukynkaCZE** [comment]
After bit more of playing around with it, i found that it closes whenever almost any other overlay is open so it probably has something to do with focus changing to different overlay, not just notification overlay

https://user-images.githubusercontent.com/48604271/170805660-1eada397-19a2-4533-8dbe-402879334b5e.mp4

**Comment by frenzibyte** [comment]
That is intentional and solving the issue would be by making the first-run overlay never open another overlay during setup.

**Comment by LukynkaCZE** [comment]
yeah that would make sense

**Comment by peppy** [comment]
I’m not so sure though. I do want the stable import notification to still appear, so blocking to notification overlay from popping out during setup might be best.

**Comment by LukynkaCZE** [comment]
That is also true because you can run the stable import from button in setting and removing the notifications for it would basically remove any progress display if you are not in the first run wizard
