### ISSUE TITLE
Wacom tablet not working

### ISSUE THREAD

**Issue by notsniped** [ppy/osu#18463]
### Type

Game behaviour

### Bug description

When using a Wacom Intuos (Wacom CTL-4100) tablet with my osu!lazer install (not sure if this is only on my install or in general), when I plug in the tablet to my Linux machine it returns errors and decides to lock the cursor to the bottom-right corner of my screen

### Screenshots or videos

![osu_2022-05-27_15-52-31](https://user-images.githubusercontent.com/72265661/170830916-583f0208-4108-4c1d-acbc-adab87b3c156.jpg)

### Version

2022.501.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/8791354/runtime.log)
[network.log](https://github.com/ppy/osu/files/8791355/network.log)
[performance.log](https://github.com/ppy/osu/files/8791356/performance.log)
[database.log](https://github.com/ppy/osu/files/8791357/database.log)

**Comment by frenzibyte** [comment]
Please investigate this yourself and check the [linux FAQ](http://opentabletdriver.net/Wiki/FAQ/Linux#fail-device-streams) for ideas to fix this, or report this against [OpenTabletDriver](https://github.com/OpenTabletDriver/OpenTabletDriver/issues) for further help. This is not the right place.

**Comment by bdach** [comment]
* the errors displayed are likely to be caused by a permissions issue. please read https://opentabletdriver.net/Wiki/FAQ/Linux#fail-device-streams
* as for the teleporting, please state whether you have "high precision mouse" on or off.
