### ISSUE TITLE
Timings of slider components are incorrect

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#1846]
Compared to stable the timings of slider ticks and repeat arrows seem to be off.

Ticks appear way too late compared to stable.
![qq](https://user-images.githubusercontent.com/27222621/34519263-562c8572-f083-11e7-985a-7de3cac2bf54.png)
Blue is stable vs Purple as osu!lazer. The red arrow points to the last tick that has just fully appeared given the respective circle positions.

~~Repeat arrows can appear before the slider snaked out to them.~~
![qq](https://user-images.githubusercontent.com/27222621/34519319-accaf152-f083-11e7-8ba6-04768f3c112d.png)

**Comment by LittleEndu** [comment]
Repeat arrows should be rendered with the snake-in not with slider ticks.
Also, is two repeat arrows rendered on that image? I don't think that's something that's supposed to happen

**Comment by Aergwyn** [comment]
It's a short repeat slider with fast speed. You can see the repeats before the slider even started. You can look and slow down personally in osu ruleset tests.

**Comment by LittleEndu** [comment]
I meant compared to osu-stable. But I'm wrong again. Checked in editor where I have default skin, two repeat arrows are supposed to appear 👍

**Comment by Aergwyn** [comment]
To update on this: Repeats should be fixed really soon so only Ticks remain incorrect. I'll try my luck with them.
