### ISSUE TITLE
In the first run setup, pressing the "Get the osu! tutorial" button when you already have it generates infinite load.

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#18468]
### Type

Game behaviour

### Bug description

I launched the first run setup and clicked on the "Get the osu! tutorial" button, while I already have it in lazer (I have the old and the new one, so I'm sure that I have it). And the result is the game seems to try to get the map, but there's just a long load time, probably infinite (I waited 30 seconds, I usually download beatmaps in less than 15 seconds)... I just see that loading circle on the button, as shown in the screenshot.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/57914482/170846039-f8ac5922-5b95-4fad-b22b-10ac5fe387f8.png)

### Version

2022.528.0

### Logs
[performance.log](https://github.com/ppy/osu/files/8792351/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8792352/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8792353/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8792354/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8792355/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8792356/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8792357/updater.log)
[database.log](https://github.com/ppy/osu/files/8792358/database.log)
[network.log](https://github.com/ppy/osu/files/8792359/network.log)

**Comment by bdach** [comment]
I couldn't reproduce this one despite multiple tries and multiple restarts. Must be something else going on.

**Comment by peppy** [comment]
I've had this happen a couple of times. Can currently repro on one of my iOS devices. Going to be something like existing but in bad state, so no event arrives.

**Comment by Corne2Plum3** [comment]
I reproduced the bug with my Linux (Debian 11) using the AppImage file from the Release section (2022.528.0). I got exactly the same result.

[performance.log](https://github.com/ppy/osu/files/8793647/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8793648/runtime.log)
[database.log](https://github.com/ppy/osu/files/8793645/database.log)
[network.log](https://github.com/ppy/osu/files/8793646/network.log)

I forgot to say that in both Windows and Linux, I have the tutorial installed BEFORE launching the game (if it would help).
