### ISSUE TITLE
`LegacyExporter.Export()` blocks calling thread causing freezes when exporting large archives

### ISSUE THREAD

**Issue by bdach** [ppy/osu#18476]
Original discussion mentions skin export from settings menu, but this is also the case for the "Export package" menu option in editor.

### Discussed in https://github.com/ppy/osu/discussions/18475

<div type='discussions-op-text'>

<sup>Originally posted by **cdwcgt** May 29, 2022</sup>
On some computers with slow hard drives, `Export selected skin` will make main thread blocked(osu! not response)
We can make it as a task so it will not dragging down the main thread</div>

**Comment by Speykious** [comment]
This problem also applies to saving a beatmap.
I'm willing to give this a shot as a first contribution.

Reporting what I've said in #18557 below.
After some examination of the problem, it got me all the way down to Realm, where the bottleneck is this method:
https://github.com/ppy/osu/blob/45451178dfd08174071ac38d382cc5d490842dc0/osu.Game/Stores/RealmFileStore.cs#L64-L72
It would need to support some kind of way to report progress (if possible) on the action of copying. Maybe a Bindable.

**Comment by peppy** [comment]
Please start by profiling and understanding why that operation is taking so long, if it is. Because it shouldn't be (`.osu` files aren't that big).

Also I'm not sure what the point is of reporting progress unless we have a means of displaying it.

**Comment by Speykious** [comment]
> Please start by profiling and understanding why that operation is taking so long, if it is. Because it shouldn't be (`.osu` files aren't that big).
> 
> Also I'm not sure what the point is of reporting progress unless we have a means of displaying it. Progress of ongoing operations is hard to do and will add a lot of noise to the code.

For the means of display, I was thinking of posting a `ProgressNotification`. Though indeed if it's not meant to take long at all then I'll probably start looking into profiling - I haven't ever done that extensively in any of my personal projects, so I'll have to learn.
I'm sure exporting a package on the other hand should take a longer, given that it's zipping the whole thing?

**Comment by cdwcgt** [comment]
https://user-images.githubusercontent.com/34775378/202493609-59f5a2b0-fe42-4f6b-b3e7-62663bd128cf.mp4

An implementation using async
Change the whole `LegacyExporter` basically
So some test problems have not been solved
But it's enough for me
[branch](https://github.com/cdwcgt/osu/tree/export)

**Comment by peppy** [comment]
Are you planning on PRing your branch?

**Comment by cdwcgt** [comment]
> Are you planning on PRing your branch?

Yes, but my code implementation doesn't look good, especially testing.
I will pr after I finish what I should do.
