### ISSUE TITLE
Repeat steps don't reset their count when trying to run the test again

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#1850]
While making new test cases for TestCaseBeatmapCarousel I noticed that it always gets stuck at ``select next diff 4/4``

**Comment by Aergwyn** [comment]
That is just a repeat step that is called 4 times. 4/4 means it has executed successfully the amount of times it was told to.

**Comment by LittleEndu** [comment]
Yeah, but it doesn't do anything if you run the test again without recompiling it or switching to another test first

**Comment by LittleEndu** [comment]
It wouldn't be a problem but can be if you miss the thing that you are testing for and want to run the test again.

**Comment by peppy** [comment]
it's a bit weird you can't manually increment further, I agree. you're welcome to add a bypass to go over the max runs when clicked
