### ISSUE TITLE
the preview of the skin editor is covered

### ISSUE THREAD

**Issue by nanashi-1** [ppy/osu#18534]
### Type

Other

### Bug description

the preview is covered making it hard to line up elements

### Screenshots or videos

![Screenshot from 2022-06-02 18-35-25](https://user-images.githubusercontent.com/54083498/171612197-07aea9d0-9ccb-4a6a-907f-37bd4fa44a4d.png)
as you can see the combo counter and health bar is covered by the components menu

### Version

2022.528.0

### Logs

[database.log](https://github.com/ppy/osu/files/8823048/database.log)
[network.log](https://github.com/ppy/osu/files/8823049/network.log)
[performance.log](https://github.com/ppy/osu/files/8823050/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8823051/runtime.log)

**Comment by smoogipoo** [comment]
I don't think this overlay was tested at different resolutions :sweat_smile:
