### ISSUE TITLE
Scroll handling is broken

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18550]
Anywhere there is single directional scroll is broken since recent changes. Consider the case of song select: vertical scroll should still be handled if nothing else handled horizontal first.

Needs reconsideration at framework level. Scroll containers should likely be checking constantly until a minimum threshold is hit, rather than only once (`OnDragStart`).

https://user-images.githubusercontent.com/191335/171878208-3ed5ec34-9871-48c7-aa23-37db38c5ae3b.mp4

**Comment by peppy** [comment]
I noticed this in about 5 places in the UI, where my drags would randomly not scroll where I expected them to, until I realised the cause of this. Especially noticeable on smaller elements like dropdown menus.

**Comment by frenzibyte** [comment]
> Needs reconsideration at framework level. Scroll containers should likely be checking constantly until a minimum threshold is hit, rather than only once (OnDragStart).

That's not quite feasible as there can only be one drawable receiving drag events at once, determined by returning true on `OnDragStart`.

One solution I can offer in the interim is to only have the new dragging behaviour when a `ScrollContainer` is nested inside of another one with opposite direction. Can give that a try if it sounds good enough.

**Comment by peppy** [comment]
> One solution I can offer in the interim is to only have the new dragging behaviour when a `ScrollContainer` is nested inside of another one with opposite direction. Can give that a try if it sounds good enough.

Sounds like a good immediate fix. I think this is crippling to the point I'll be doing another framework release with a fix before the next osu! release.
