### ISSUE TITLE
Opening song select after switching threading mode becomes unresponsive 

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#18569]
### Type

Game behaviour

### Bug description

(title)

### Screenshots or videos

https://user-images.githubusercontent.com/86934170/172020105-75314cde-1e2d-4179-8314-1d2e8d4a1384.mp4

### Version

605

### Logs

[performance.log](https://github.com/ppy/osu/files/8838379/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8838380/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8838381/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8838382/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8838383/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8838384/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8838385/updater.log)
[database.log](https://github.com/ppy/osu/files/8838386/database.log)
[network.log](https://github.com/ppy/osu/files/8838387/network.log)

**Comment by frenzibyte** [comment]
Can reproduce, very spooky...
