### ISSUE TITLE
Allow showing hidden folders in file/directory selector

### ISSUE THREAD

**Issue by r0xANDt0l** [ppy/osu#18573]
### Type

Game behaviour

### Bug description

When you want to import stuff from osu!stable to lazer, and you have the installation in a hidden folder (For example, if you're using  osu! in linux with wine, it installs it in `~/.local/share/osu-wine/OSU`, and by default, `.local` is a hidden folder). So therefore,  you can't import it without having to copy the contents to a folder in ~/ or in an accesible place.

### Screenshots or videos

![imagen](https://user-images.githubusercontent.com/41841903/172027063-541c22f2-8ea0-4457-af12-89bc949282d2.png)

### Version

2022.528.0-lazer 

### Logs

[database.log](https://github.com/ppy/osu/files/8839005/database.log)
[network.log](https://github.com/ppy/osu/files/8839006/network.log)
[performance.log](https://github.com/ppy/osu/files/8839007/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8839008/runtime.log)

**Comment by ggliv** [comment]
https://github.com/ppy/osu-framework/commit/c1ea24e654c0e89e17f5f8216962a454d7ed1b5d made hiding hidden items the default behavior, this issue should probably be reopened until a toggle is implemented osu-side.

**Comment by frenzibyte** [comment]
@ggliv Do you plan on PR'ing an implementation for this? A simple nub at the top right with a colour scheme similar to the selector should do.

**Comment by ggliv** [comment]
> @ggliv Do you plan on PR'ing an implementation for this? A simple nub at the top right with a colour scheme similar to the selector should do.

Yes I do, thanks for the design cue.

**Comment by ThePooN** [comment]
This is also an issue for lazer's tournament mode which requires you to select the osu! stable path which is by default installed in %localappdata%, a hidden directory.

**Comment by peppy** [comment]
I've merged the PR as-is because it's in a pretty usable state.
