### ISSUE TITLE
Editor export function mangles Unicode file names

### ISSUE THREAD

**Issue by STCapricorn** [ppy/osu#18585]
### Type

Game behaviour

### Bug description

I imported an audio file with a Unicode file name to try timing with the new timing screen, then I exported it after timing to try it in stable. 

the file name went from:
`01. 愛言葉Ⅳ feat. 初音ミク.ogg`
to:
`01. µä¢Φ¿ÇΦæëΓàú feat. σê¥Θƒ│πâƒπé».ogg`

### Screenshots or videos

![image](https://user-images.githubusercontent.com/7162510/172132509-9596d175-dafe-4619-b615-0b263b519038.png)
![image](https://user-images.githubusercontent.com/7162510/172132574-b87ba442-0764-4a1e-9a51-0fe41e8869c4.png)

### Version

2022.605.1

### Logs

[performance.log](https://github.com/ppy/osu/files/8843272/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8843273/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8843274/updater.log)
[database.log](https://github.com/ppy/osu/files/8843275/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8843276/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8843277/network.log)

**Comment by peppy** [comment]
`osz`/`zip` doesn't support unicode great. And we don't support it at all at a BSS level.

- Audio tracks should generally be automatically renamed to `audio.mp3`
- Unicode should be stripped from filenames on editor import

**Comment by frenzibyte** [comment]
> Audio tracks should generally be automatically renamed to `audio.mp3`

Should the same not apply to beatmap backgrounds? (i.e. having them `background.png` instead). And if it were to be applied on both background and track, would that make stripping unicode no longer necessary since they're automatically renamed to english?

**Comment by peppy** [comment]
Stable already does the renaming part, at least for audio filenames, and I think this makes sense to retain in lazer. The sanitisation will likely still be required for storyboard resources going forward regardless.

Updating the UI controls as you propose sounds fine.
