### ISSUE TITLE
Leaderboard shows Placeholder and Scores together (or neither)

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#1859]
With certain timing I am able to get the leaderboard to show both scores and placeholder...
![qq](https://user-images.githubusercontent.com/27222621/34622293-e5e41e3a-f24c-11e7-9ebf-d68f862349f8.png)

... or nothing at all.
![qq](https://user-images.githubusercontent.com/27222621/34622331-0d6b47f8-f24d-11e7-90f6-ebc2a183c68a.png)

This is independent of #1841 and most likely a problem in the structure and timings how Scores and PlaceholderState are assigned and checked.

It's hard to explain and understand because Scores and PlaceholderState are used and set all over the place and setting PlaceholderState resets Scores too and so on.

**Comment by FreezyLemon** [comment]
Something that might be related:
With a lot of random tab changes (just spamming clicks), I was able to hard crash.
The scheduled `LoadComponentAsync` call [here](https://github.com/ppy/osu/blob/master/osu.Game/Screens/Select/Leaderboards/Leaderboard.cs#L65) can sometimes be called with `scores == null`
