### ISSUE TITLE
Issues with menu sound samples

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu#1860]
When moving my mouse around the lazer build, there was so many sound effects going on that I was getting a headache. There's a couple fixes that could be done to make it easier to tolerate

- The samples used on lazer are too long and have too much echo. All of them need to be shorter, as sounds frequently overlap and play at the same time.
- button-hover.wav shouldn't have a high pitch sound, only the low pitch one should be used. This file can play dozens of times per second, having a high pitch sound with it is really annoying.
- osu-logo-heartbeat should sound more like a kick and less like a clap/finish. When hovering over it with high bpm maps, it gets really annoying.

These are technically separate issues, but it would be best to fix in one batch.

**Comment by peppy** [comment]
sound design is still a wip and its too early to accept feedback here. also it's a matter of balancing levels which hasn't been considered

**Comment by peppy** [comment]
Closing for now
