### ISSUE TITLE
Incoming sliders are different than stable with snaking enabled

### ISSUE THREAD

**Issue by Wuteva** [ppy/osu#18613]
### Type

Game behaviour

### Bug description

In lazer, the incoming sliders show all at once regardless of the snake settings, see video. Notice how in stable (when snaking enabled), the incoming slider appear slowly, unlike lazer which always appear all at once. 
Does not seems to be skin / classic mod related.

### Screenshots or videos

https://user-images.githubusercontent.com/1039595/172513367-b46d607b-7521-4b92-904d-9c31d3acf7b5.mp4

### Version

2022.605.1-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8857617/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8857618/updater.log)
[database.log](https://github.com/ppy/osu/files/8857619/database.log)
[network.log](https://github.com/ppy/osu/files/8857620/network.log)
[performance.log](https://github.com/ppy/osu/files/8857621/performance.log)

**Comment by peppy** [comment]
This looks like you have snaking turned off. Are you seeing this on a specific beatmap?

**Comment by Wuteva** [comment]
Mm, I've restarted the game and it indeed seems to work now. I didn't even change the settings. Could it be because I updated from an old version the last time I opened it ( a few months old?). Either way it seems to works fine now so I'm gonna close.
