### ISSUE TITLE
lazer mobile crashes whenever you tab out of the game then tab in again

### ISSUE THREAD

**Issue by recognitionmark** [ppy/osu#18616]
### Type

Crash to desktop

### Bug description

Lazer on mobile crashes whenever you tab out of the game (e.g. using the Recents button) and go back into the game with recents as well. This also happens when you:
- Use the home button and go back in again by tapping the app icon.
- Press the home button and go back in using the recents feature.
Basically, this bug occurs with any feature that puts osu! in the background.
Device Model: OPPO A92 (CPH2059)

### Screenshots or videos

https://user-images.githubusercontent.com/55909718/172548118-f7009fb9-99dc-4e46-b972-6e4a2f94061f.mp4

### Version

2022.605.1-lazer (Android)

### Logs

[network.log](https://github.com/ppy/osu/files/8858900/network.log)
[database.log](https://github.com/ppy/osu/files/8858901/database.log)
[performance.log](https://github.com/ppy/osu/files/8858902/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8858903/runtime.log)

**Comment by peppy** [comment]
Thanks for your report. We're well aware of this issue and tracking at https://github.com/ppy/osu-framework/issues/4994.
