### ISSUE TITLE
Editor mode selector font is incorrect after selection and deselection

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#18637]
### Type

Cosmetic

### Bug description

This bug happens in the editor, with the tabs at the top right ("setup", "compose", ...). These tabs uses (ugly) font's alternate glyphs or something, making some letters differents from normal text (the dot in the "o", different letter "g", ...) and unreadable. But the problem is, when you click another tab, the alternates glyphs diseappears or are disabled, making the text (finally) normal. Note that the current tab (the one we selected) always have these alterate glyphs, even if they got disabled before.

The buttons at the top left ("File", "View", ...) aren't affected.

The bug is fixed when you close then open the editor again.

### Screenshots or videos

https://user-images.githubusercontent.com/57914482/173158654-8236a031-273c-4030-aacd-723e8e2b6198.mp4

### Version

2022.605.1

### Logs

[performance-audio.log](https://github.com/ppy/osu/files/8882556/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8882557/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8882558/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8882559/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8882560/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8882561/updater.log)
[database.log](https://github.com/ppy/osu/files/8882562/database.log)
[network.log](https://github.com/ppy/osu/files/8882563/network.log)
[performance.log](https://github.com/ppy/osu/files/8882564/performance.log)

**IMPORTANT** This isn't the logs from the video, but in these logs, I opened the game, quickly recreated the bugs by selecting all tabs, closed the editor and opening it again (on the same map).

**Comment by Corne2Plum3** [comment]
While having fun with the Draw Visualizer tool I noticed the font somehow changed (it don't use the right font when it change from the state "selected" to "unselected")

_The "design" tab was not selected:_
![osu_2022-06-11_01-05-08](https://user-images.githubusercontent.com/57914482/173161077-94ff67dc-9f50-4a8c-ad55-eb84d9fa0361.png)

_The "design" was previously selected, then I clicked on another tab:_
![osu_2022-06-11_01-06-30](https://user-images.githubusercontent.com/57914482/173161080-d4f6428f-ab29-4083-ab30-e49d23704113.png)

**Comment by peppy** [comment]
This is due to `Torus-Alternative-Medium` not being bundled in resources. We may want to consider adding it, or checking whether another weight is intended to be used in tab controls.

**Comment by frenzibyte** [comment]
"Medium" weight isn't supported for torus fonts, they are mapped to "Regular":
https://github.com/ppy/osu/blob/86240cc8ecf570e9c9eba1760db1d651d67c2c9d/osu.Game/Graphics/OsuFont.cs#L80-L82

But the logic isn't applied to "Torus Alternate" font currently.
