### ISSUE TITLE
Text on the bottom button in the setup wizard is cropped if the text is too long

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#18638]
### Type

Cosmetic

### Bug description

Self-explanatory. 

If the text is too long, the text is cropped (the beginning and the end isn't visible). 

The bug is the same regardless the UI scaling and can't be recreated with the game set in english because the text always fit in the button with 1 line.

This bug may affects all buttons with this style. I think these buttons should be able to display text in several lines if possible, and not cutting the text.

### Screenshots or videos

Look at the pink button at the bottom left of the screen

_UI scaling = 0.90x or 1.00x I forgor 💀_
![osu_2022-06-11_00-51-07](https://user-images.githubusercontent.com/57914482/173160332-b93fd8b4-4ab3-4438-b59d-2ff4ebf1b158.png)

_UI scaling = 0.80x (min)_
![osu_2022-06-11_00-51-32](https://user-images.githubusercontent.com/57914482/173160348-8d1f92d5-2625-4486-83fa-55566b68055b.png)

_UI scaling = 1.60x (max)_
![osu_2022-06-11_00-51-50](https://user-images.githubusercontent.com/57914482/173160379-58d7a851-ec7e-400d-af7e-41d9dcf4eb04.png)

### Version

2022.605.1

### Logs

[performance-draw.log](https://github.com/ppy/osu/files/8882631/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8882632/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8882633/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8882634/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8882635/updater.log)
[database.log](https://github.com/ppy/osu/files/8882636/database.log)
[network.log](https://github.com/ppy/osu/files/8882637/network.log)
[performance.log](https://github.com/ppy/osu/files/8882638/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8882639/performance-audio.log)

**Comment by peppy** [comment]
This is an issue with the localisation string being too long. It should be shortened.

**Comment by frenzibyte** [comment]
There is a discussion thread for this (https://github.com/ppy/osu/discussions/15452), probably better placing this issue there instead.

**Comment by peppy** [comment]
Let's keep things in that thread.
