### ISSUE TITLE
Stuttering when using beatmap offset slider

### ISSUE THREAD

**Issue by notohh** [ppy/osu#18656]
### Type

Performance

### Bug description

When using the beatmap offset slider, the game starts to stutter immensely.

### Screenshots or videos

https://user-images.githubusercontent.com/31116143/173236194-e10b458f-2b6c-45bc-8dad-fa676094393d.mp4

### Version

2022.612.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/8885951/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8885952/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8885953/updater.log)
[database.log](https://github.com/ppy/osu/files/8885954/database.log)
[network.log](https://github.com/ppy/osu/files/8885955/network.log)

**Comment by peppy** [comment]
Do you have an import running?

**Comment by notohh** [comment]
> Do you have an import running?

I do not.

**Comment by peppy** [comment]
@notohh to help with reproducing this one, could you please zip and attach your `client.realm` file? It should be in your osu! user data folder.

**Comment by peppy** [comment]
Thanks, can reproduce using your database.
