### ISSUE TITLE
Reverse arrows not showing up when they should on small sliders

### ISSUE THREAD

**Issue by Lunaero1** [ppy/osu#18655]
### Type

Other

### Bug description

I played a map and on the default skin reverse arrows arent showing up on small sliders that have reverse points (im posting this as idk if its a bug or intentional)

### Screenshots or videos

![osu_2022-06-12_08-10-41](https://user-images.githubusercontent.com/102831916/173234851-f2003f6b-885b-4ec0-8273-27891a97145d.png)
![osu_2022-06-12_08-09-44](https://user-images.githubusercontent.com/102831916/173234856-204f75ab-71a1-4f28-a110-262dd24645bc.png)

### Version

2022.612.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8885885/database.log)
[network.log](https://github.com/ppy/osu/files/8885886/network.log)
[performance.log](https://github.com/ppy/osu/files/8885887/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8885888/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8885889/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8885890/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8885891/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8885892/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8885893/updater.log)

**Comment by VeilStar** [comment]
Looks like this is https://github.com/ppy/osu/issues/2147?

**Comment by Lunaero1** [comment]
> Looks like this is #2147?

I assume, I didnt know an issue like this already existed.

**Comment by bdach** [comment]
Closing as duplicate.
