### ISSUE TITLE
Not all scores are visible at playlists leaderboard

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18657]
### Type

Game behaviour

### Bug description

Noticed when spectating a multiplayer game today. Needs further investigation.

### Version

latest

### Logs

-

**Comment by peppy** [comment]
Safe to close this one as working-as-intended?

**Comment by smoogipoo** [comment]
Turns out that this wasn't an issue. Some players just hadn't played to completion.

**Comment by peppy** [comment]
Tracking at https://github.com/ppy/osu-web/issues/9026
