### ISSUE TITLE
Basically Unlimited FPS warning text overflow

### ISSUE THREAD

**Issue by SiderealArt** [ppy/osu#18666]
### Type

Cosmetic

### Bug description

When the language is set to Chinese (both Traditional and Simplified) or Japanese, the warning text for the Basically unlimited fps option will overflow.

And I don't think this is related to #15452, because in Korean, the word wraps normally (as shown in the third screenshot).

### Screenshots or videos

![image](https://user-images.githubusercontent.com/30827929/173291848-27ab7977-86b2-4d9a-a05a-c19b3c00f68a.png)
![image](https://user-images.githubusercontent.com/30827929/173291891-19996383-cc88-4195-894b-8eb6c0c9d36a.png)
![image](https://user-images.githubusercontent.com/30827929/173292144-618b10e0-9677-4124-8eb4-afddbf0bc85b.png)

### Version

2022.612.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/8888420/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8888422/updater.log)
[database.log](https://github.com/ppy/osu/files/8888423/database.log)
[network.log](https://github.com/ppy/osu/files/8888424/network.log)
[performance.log](https://github.com/ppy/osu/files/8888425/performance.log)

**Comment by peppy** [comment]
Nope, just another case of https://github.com/ppy/osu/issues/14837.
