### ISSUE TITLE
Click not registering 

### ISSUE THREAD

**Issue by LanguidCookie61** [ppy/osu#18662]
### Type

Game behaviour

### Bug description

I’ve been playing osu lazer recently and notice a bug. Digital Hypno said you could use 4 keys as your binds for osu, so I've been trying to do 3 keys. When I click the left button fast sometimes it won't register the second click. I don’t know if this makes sense, but the picture might help.

### Screenshots or videos

![bug](https://user-images.githubusercontent.com/58916265/173256439-ba6aaf45-a0ae-4631-adba-c042e4cda91b.png)

### Version

Osu Lazer 

### Logs

[performance.log](https://github.com/ppy/osu/files/8886932/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8886933/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8886934/updater.log)
[database.log](https://github.com/ppy/osu/files/8886935/database.log)
[network.log](https://github.com/ppy/osu/files/8886936/network.log)

**Comment by frenzibyte** [comment]
> When I click the left button fast sometimes it won't register the second click.

That should be correct according to the [simultaneous binding mode](https://github.com/ppy/osu/blob/abb617a3df76c0ed685f9b84ae4abd4b3ea8be79/osu.Game.Rulesets.Osu/OsuInputManager.cs#L32-L33), to be more clear, at the point of holding one key from the "left button", pressing another will only register after the first one is released. So you can't really use 4 keys at once as the beatmap gets faster.

The point of different keys for one "button" is to allow playing the game using different input devices, such as mouse, as in the default key bindings set (M1/Z, M2/X).

**Comment by peppy** [comment]
To phrase things another way for future visitors: While you can bind four keys, you can only have two actual inputs to the game. For the keys you bind to the same "game" button, you will need to release one before you press the other, or they will not be accounted for.
