### ISSUE TITLE
Cursor in the run latency certifier is behind the background of the unselected half

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#18675]
### Type

Cosmetic

### Bug description

The cursor in the new brand mini-game "run latency certifier" is behind the background of the half where your cursor isn't, which is darker than the other half.  This bugs applies with both sides (left or right).

Also can you make the cursor a bit brighter plase?

### Screenshots or videos

![osu_2022-06-13_14-41-37](https://user-images.githubusercontent.com/57914482/173356634-273a00af-c3bf-4997-9523-5ab4555cc1b8.png)
![osu_2022-06-13_14-41-51](https://user-images.githubusercontent.com/57914482/173356639-d1071e0d-439b-4276-b832-a9d927bf1693.png)
![osu_2022-06-13_14-41-43](https://user-images.githubusercontent.com/57914482/173356644-0a240687-80b8-4564-985f-6250e5384ed9.png)

### Version

2022.612.0

### Logs

[performance-draw.log](https://github.com/ppy/osu/files/8891117/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8891118/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8891119/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8891120/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8891121/updater.log)
[database.log](https://github.com/ppy/osu/files/8891122/database.log)
[network.log](https://github.com/ppy/osu/files/8891123/network.log)
[performance.log](https://github.com/ppy/osu/files/8891124/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8891125/performance-audio.log)

This isn't the log of the session where I made the screenshot, but I basically opened the game, go to "run latency certifier" and took a screenshot.

**Comment by peppy** [comment]
This is 100% intentional, so you can't see the seam (which would make an unfair comparison).
