### ISSUE TITLE
Osu!Lazer dosen't like Windows 10

### ISSUE THREAD

**Issue by lauthaiming** [ppy/osu#1867]
The oldest version of Lazer can run on Windows 7.

But the newest version of Lazer needed 4.6.1 of .net framework. So, updated the computer to windows 10,
which is update the .net framework also ( 4.7.1 ).

For some reason, the Osu!Lazer doesn't like Windows 10. Even with the oldest version of Osu!Lazer.

**Comment by Aergwyn** [comment]
What do you mean with "it doesn't like it"? Can you describe what happens if you try to start osu!lazer? For me it runs perfectly fine on Windows 10.

**Comment by NITPRUDO** [comment]
It crashes, i assume? Give us crash logs, please.

**Comment by peppy** [comment]
Please reopen with more detail.
