### ISSUE TITLE
Object bug of using the editor(The version that can read beatmap object on osu!editor)

### ISSUE THREAD

**Issue by DynamicMiner** [ppy/osu#1868]
Recently,I found that when I open a beatmap file,the issue will happen.
Object overlapping will happen at the first load or click the process bar randomly everytime.
But it will disappear after scrolling or click randomly on the process bar.
Down here is a screenshot.
![error_1](https://user-images.githubusercontent.com/35213403/34660940-1dde4a32-f481-11e7-87be-7ac5c8314825.png)
Or even you just import the song and use the editor immediately on that song,nothing show up at the editor.(After select a beatmap)
![error_2](https://user-images.githubusercontent.com/35213403/34661217-25849258-f483-11e7-95d7-e4ff985bac8b.png)
This beatmap called [/emotional] mapped by Girl
Difficulty:Serendipity
https://osu.ppy.sh/s/554758
You can check the song length and compare with the screenshot to shows that it isn't fake.

Another one,lazer cannot read 0 bpm beatmap,when you want to open it,lazer will crush.

**Comment by DynamicMiner** [comment]
I cant type <> inside,so the beatmap name called </emotional>.

**Comment by peppy** [comment]
The editor is still in very early stages of implementation and no great effort has been spent yet to address bugs like this.  Will leave open for now.

**Comment by TemTemmie** [comment]
the osu!laser editor is still in early stages of implementation and very buggy.

**Comment by AlFasGD** [comment]
Cannot reproduce the first issue after the version where [this](https://github.com/ppy/osu-framework/pull/1542) change was added into the game (around a month ago). This fix might have fixed all the issues related to this.

**Comment by smoogipoo** [comment]
Afaik this can still be repro'd if you scroll in the editor prior to the composer loading.

**Comment by peppy** [comment]
This does indeed seem fixed.

**Comment by DynamicMiner** [comment]
First I need to sorry about reply it late because I really get busy
recently and secondly,may I ask how to delete the issue?

**Comment by ticotaco72** [comment]
@dynamicminer it's already deleted. When you issue is closed it becomes inactive and stays on repo for reference
