### ISSUE TITLE
MP3 Rushes Over Time (?) In Editor

### ISSUE THREAD

**Issue by rcfox2** [ppy/osu#18700]
### Type

Game behaviour

### Bug description

When in the editor, it feels like the song plays faster than it should, as, over time, the song's snapping is later than the map's snapping. This makes it impossible to make good maps in the lazer editor. This does not happen in gameplay.

### Screenshots or videos

Early in the map, it sounds fine:
https://user-images.githubusercontent.com/68173946/173740646-4d8e5e00-2fd0-441c-ac94-fcdbb878357a.mp4

Later on, it is massively delayed:
https://user-images.githubusercontent.com/68173946/173740318-4dfc77f2-a562-46c4-aa01-a2544ddcf876.mp4

### Version

2022.612.0

### Logs

[performance.log](https://github.com/ppy/osu/files/8905830/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8905831/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8905833/updater.log)
[database.log](https://github.com/ppy/osu/files/8905834/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8905835/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8905836/network.log)

**Comment by peppy** [comment]
Could you please check whether this is only the case in the latest release, by trying to install the last release (see instructions [here](https://github.com/ppy/osu/issues/18652#issuecomment-1153398699)?

If so it is likely a duplicate of #18652.

**Comment by rcfox2** [comment]
> Could you please check whether this is only the case in the latest release, by trying to install the last release (see instructions [here](https://github.com/ppy/osu/issues/18652#issuecomment-1153398699)?
> 
> If so it is likely a duplicate of #18652.

Sorry, I just saw that, and was about to close this. Playing the map from the beginning to the end without pausing seems to remove the delay.
