### ISSUE TITLE
First time entering song select plays a "seek" sound

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18705]
Not sure what or why.

**Comment by LittleEndu** [comment]
What sound are we talking about? Does next random function play the seek sound? It's called when entering song select.

**Comment by peppy** [comment]
This is probably fine after all. It only plays when first entering song select if song select decides to change the current beatmap:

https://github.com/ppy/osu/blob/0815b01b75e2de9364118fc05c6e9410899c8d2a/osu.Game/Screens/Select/SongSelect.cs#L485-L488

Doesn't sound too bad.
