### ISSUE TITLE
Timeline waveform does not update on beatmap track changes

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#18713]
### Type

Cosmetic

### Bug description

As per the video, when the beatmap track is changed in editor, going into compose screen doesn't show the waveform in the timeline updated inline with the new track.

### Screenshots or videos

https://user-images.githubusercontent.com/22781491/173854533-46d636fb-6f1c-4624-a075-2bfff34efa7e.mp4

### Version

2022.612.0

### Logs

-

**Comment by KantoChampion** [comment]
No logs?
