### ISSUE TITLE
Menu cursor is invisible when external link popup is shown during latency certifier

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#18718]
### Type

Game behaviour

### Bug description

The menu cursor does not appear for menus when the latency certifier is open, I've tested this on both Windows 10 and Linux and both have the same error

### Screenshots or videos

https://user-images.githubusercontent.com/58333920/173891005-3c8da4d2-b7a6-40b6-9997-c014aa56a30c.mp4

### Version

2022.615.0-lazer

### Logs

[logs.zip](https://github.com/ppy/osu/files/8911870/logs.zip)

**Comment by peppy** [comment]
It’s intentionally hidden, correct.

**Comment by bdach** [comment]
Probably shouldn't be while an "external link" popup is being shown, though?

**Comment by Stoppedpuma** [comment]
Is there a reason why the latency certifier hides the menu cursor for everything instead of just the latency certifier? I don't see a reason that it's hidden for menus
