### ISSUE TITLE
Osu!Lazer crashes after starting

### ISSUE THREAD

**Issue by lauthaiming** [ppy/osu#1872]
I'm using Windows 10 ( Just updated from Windows 7 ) to launch Osu!Lazer latest version ( 2017.1231.0 update ).

For the crash log ... I go to %appdata%/osu/logs 
And here is the crash log ( i'm not sure this is osu!lazer or osu! crashlog. )

[database.log](https://github.com/ppy/osu/files/1617282/database.log)
[performance.log](https://github.com/ppy/osu/files/1617283/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/1617284/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/1617285/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/1617286/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/1617287/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/1617288/runtime.log)

The osu!lazer just crashed after I just starting it.
( Blackscreen and Give me a error message , the [Close Program] one. )

**Comment by peppy** [comment]
You'll need to check event log or run in a debug environment to get something that is useful to diagnosing your issue.

**Comment by lauthaiming** [comment]
What is event viewer ?
And ... how can I run in a debug environment ?

**Comment by peppy** [comment]
If neither of these ring a bell, please come back in a month or two and we may have things working for you.
