### ISSUE TITLE
Osu on mac os won't open.

### ISSUE THREAD

**Issue by Rawwwwr** [ppy/osu#18722]
### Type

Other

### Bug description

Hello dear devs. I ran into a problem that the osu client does not open! lazer on my Macbook air m1. Before everything worked fine, but then, it began to give an error (I'll attach the screen below), I tried to reinstall, but nothing helped.

### Screenshots or videos

https://imgur.com/gallery/9Xsx33f

### Version

osu! lazer 2022.615.0 (apple silicon)

### Logs

[eror osu!lazer.pdf](https://github.com/ppy/osu/files/8915457/eror.osu.lazer.pdf)

**Comment by peppy** [comment]
Do you have external monitors connected? If so, can you try without them connected?

**Comment by Rawwwwr** [comment]
omg, it worked! But before I played with an external monitor and everything was fine :(

**Comment by peppy** [comment]
We're tracking this at https://github.com/ppy/osu-framework/issues/5190.

You can fix it by running this command in terminal:

`rm ~/.local/share/osu/framework.ini`

Note that it may begin to crash again if you change screen arrangements again, but this should temporarily fix it.
