### ISSUE TITLE
Volume adjust and gameplay input conflict (up/down arrows) 

### ISSUE THREAD

**Issue by dolkilu** [ppy/osu#18738]
### Type

Game behaviour

### Bug description

Issue:
Using **arrow keys** as gameplay input will result in unwanted UI (volume panel) and volume change.

This is a new issue as of version 612 or 615, not sure, maybe due to [osu#18554](https://github.com/ppy/osu/pull/18554).

Suggestion:
Add an option similar to the existing "mouse wheel" one, "Disable arrow keys adjusting volume during gameplay".

### Version

2022.615.0

### Logs

***

**Comment by bdach** [comment]
https://github.com/ppy/osu/pull/18737 will presumably fix this
