### ISSUE TITLE
"Gameplay" and "Song Select" buttons in skin editor no longer function

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#18758]
Can reproduce, haven't yet investigated.

### Discussed in https://github.com/ppy/osu/discussions/18755

<div type='discussions-op-text'>

<sup>Originally posted by **Gabixel** June 18, 2022</sup>
The buttons to switch between the gameplay and song select screens don't work. The game doesn't seem to give any errors, so I'm not sure if I missed something in the changelogs or if it's a real problem.

For reference: 
![buttons](https://user-images.githubusercontent.com/43073074/174439238-cee53d3c-323f-4474-9c9d-6887b4317366.gif)

</div>

**Comment by peppy** [comment]
`BlueprintContainer` is eating the clicks.
