### ISSUE TITLE
Small Userpage Improvements and Suggestions

### ISSUE THREAD

**Issue by mynasu** [ppy/osu#1876]
- Full avatar transparency on userpage (instead of [this](https://i.imgur.com/iTP0Q7J.png), something like [this](http://puu.sh/yYNPe.png)) or at least making the grey box around the avatar something of a similar transparancy to the level/userstats boxes.

- Profile badges!!! I'm not entirely sure the best way to display them with the new site's layout, but they absolutely should be a thing. Contributer badges, tournament and mapping contest victories, etc. are all awesome things that should be celebrated and shown off, so they certainly need a space on player's userpages.

- Small suggestion, but being able to rearrange favorite beatmaps efficiently would be very nice, considering they now have a little preview image alongside them, and it would be neat to be able to sort of rank your favorites in order, or showcase a group of your absolute favorite maps. 

- Another very minor suggestion, but being able to remove the header over each panel, or at least the "me!" tab would be appreciated. It's a super small thing, but it bothers me for some reason and I'm not entirely certain why.

-  Change [these](https://i.imgur.com/jljOLVj.png) details into the little symbols on the old site. The symbols are used for the location/interest/occupation trio but not for from/joined at/last online. Oh also, an alt tag should probably be added for the symbols because it probably isn't entirely clear for a new user what each of them mean.

- This is probably a bit of a more extreme suggestion, but would color-customizing your profile be a possible feature? Similar to the way twitter profile customization works? Would be neat, and add more personalization which is always pretty nice.

I think that's about everything I've noticed or thought of. Keep up the great work you all are doing, can't wait to be able to fully switch to lazer in the near future :)

**Comment by peppy** [comment]
The design of the profile page is tracking the osu-web designs. These are already in a moving state and tehre are several issues open for improvements on the osu-web repo.

If you choose to re-submit these issues against osu-web, please split them out into individual issues, rather than making long lists like this.
