### ISSUE TITLE
Using down-arrow for dashing in osu!catch will decrease volume and not allow dashing. 

### ISSUE THREAD

**Issue by Blooshing** [ppy/osu#18767]
### Type

Game behaviour

### Bug description

Hello, this was brought up by https://osu.ppy.sh/community/forums/topics/1596290?n=1 with the issue of not being able to unbind the decrease volume (in-game) keybind to something else. I was unable to reproduce the issue when I was running 05.28.2022's version of lazer, but when I updated this issue was immediately reproducible. I believe this to be unintentional as it wasn't in the prior updates. 

My catch keybinds are Tab - Dash, Left - Delete, and Right - PgDwn, with the other 3 "optional" keybinds not including down arrow, but I think it should be rebindable to something else to help players be comfortable. 

Main issue is that anyone that uses down-arrow for dashing can no longer dash AND the music is consistently lowering. 

### Screenshots or videos

[Video of my computer doing it](https://puu.sh/J6Mwm.mp4)

https://user-images.githubusercontent.com/90729492/174466999-b704d58e-2386-449e-9473-7bf57024353f.mp4

### Version

Lazer 2022.615.0 was not reproducible on Lazer 2022.528.0

### Logs

[database.log](https://github.com/ppy/osu/files/8934790/database.log)
[network.log](https://github.com/ppy/osu/files/8934791/network.log)
[performance.log](https://github.com/ppy/osu/files/8934792/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8934793/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8934794/updater.log)

**Comment by bdach** [comment]
Already fixed in #18738. Please wait for next release.
