### ISSUE TITLE
Does not see an additional keyboard with ctrl+C and ctrcl+V binds

### ISSUE THREAD

**Issue by EvgenyD9** [ppy/osu#18763]
### Type

Game behaviour

### Bug description

Hello!
I have a keyboard with two buttons. With ctrl+C and ctrl+V binds, i can see these two buttons in the settings (screenshot down below), but the game does not see them (during gameplay). They are simply doesnt press.
It would be cool if youd fix this problem!
Thx!

### Screenshots or videos

![image](https://user-images.githubusercontent.com/89486149/174460296-91949bd1-9a2b-47df-83d3-be6ba664c100.png)

### Version

2022.615.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/8934532/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8934533/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8934534/updater.log)
[database.log](https://github.com/ppy/osu/files/8934535/database.log)
[network.log](https://github.com/ppy/osu/files/8934536/network.log)

**Comment by frenzibyte** [comment]
Ctrl+C and Ctrl+V are reserved for general copy/paste actions in the game, you will have to use a different letter instead (although I don't really think you should be using that combination in the first place).

**Comment by smoogipoo** [comment]
Don't do this.
