### ISSUE TITLE
Down and up keys change master volume in game, even when they are bound to controls

### ISSUE THREAD

**Issue by farkasma** [ppy/osu#18772]
### Type

Game behaviour

### Bug description

As mentioned in the title, up and down keys change master volume during gameplay, even if they are bound to controls.
I play CtB with the left and down keys as direction control, but due to this I am slowly bringing the master audio lower by movin the catcher right.

### Version

2022.615.0

### Logs

[database.log](https://github.com/ppy/osu/files/8936507/database.log)
[network.log](https://github.com/ppy/osu/files/8936508/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/8936509/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8936510/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8936511/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8936512/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/8936513/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8936514/runtime.log)

**Comment by frenzibyte** [comment]
Has already been fixed (https://github.com/ppy/osu/issues/18738), please wait until next release.
