### ISSUE TITLE
osu!lazer fullscreen wrong refresh rate issue

### ISSUE THREAD

**Issue by Mrturtlenugget** [ppy/osu#18773]
### Type

Performance

### Bug description

The game thinks my monitor is 60hz because it is displaying the renderers of multiple of 60

This only happens in fullscreen 
also my monitor is overclocked to 74hz it was originally 60hz 

Windows 10
Nvidia 1660 super 
Ryzen 5 3600 6 core 

### Screenshots or videos

![osu_2022-06-19_18-09-24](https://user-images.githubusercontent.com/65026721/174503713-65b83445-d790-4bd9-83c0-ea1f5396483d.jpg)
![image](https://user-images.githubusercontent.com/65026721/174503730-a81f25aa-0ff2-48ff-858f-7ba05028714e.png)

### Version

2022.615.0

### Logs

[database.log](https://github.com/ppy/osu/files/8936558/database.log)
[network.log](https://github.com/ppy/osu/files/8936559/network.log)
[performance.log](https://github.com/ppy/osu/files/8936560/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8936561/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8936562/updater.log)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/18653#issuecomment-1153125690

Please search first.
