### ISSUE TITLE
Score can't be submit if non-stable mod is enabled.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#18784]
### Type

Game behaviour

### Bug description

Score can't be submit if non-stable mod is enabled. 
In the screenshot is tried with Strict Tracking mod. In the logs also have tried history of some of other mods (Bind, Classic, Barrel roll).

### Screenshots or videos

![image](https://user-images.githubusercontent.com/7066150/174644719-35fe0ca9-cff0-4cc5-8017-43724e11c876.png)

### Version

2022.615.0

### Logs

[performance-draw.log](https://github.com/ppy/osu/files/8942272/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8942273/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8942274/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8942275/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8942276/updater.log)
[database.log](https://github.com/ppy/osu/files/8942277/database.log)
[network.log](https://github.com/ppy/osu/files/8942278/network.log)
[performance.log](https://github.com/ppy/osu/files/8942279/performance.log)
[Uploading performance-audio.log…]()

**Comment by peppy** [comment]
Thanks for the report. Someone fucked something bad osu-web side, performing an immediately rollback. Should work again in a few minutes.

**Comment by peppy** [comment]
Tracking via ppy/osu-web#9040.
