### ISSUE TITLE
Api error on Multiplayer

### ISSUE THREAD

**Issue by MakS1mKa228** [ppy/osu#18799]
### Type

Other

### Bug description

An error occurs when creating a room in multiplayer

### Screenshots or videos

![image](https://user-images.githubusercontent.com/49811239/174857651-97533eb2-0e9a-4a9c-8159-5a1f9cc17d46.png)

### Version

2022.621.0

### Logs

[database.log](https://github.com/ppy/osu/files/8950989/database.log)
[network.log](https://github.com/ppy/osu/files/8950991/network.log)
[performance.log](https://github.com/ppy/osu/files/8950992/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8950993/runtime.log)

**Comment by bdach** [comment]
I see the error web-side, but I'm not sure how to reproduce it. Did you select any mods when creating the room?

**Comment by bdach** [comment]
Never mind, I can reproduce. Seems to have something to do with setting free mods.

Investigating further.

**Comment by bdach** [comment]
Web has been rolled back to last good known version. I've verified with the latest release that this cannot be hit anymore.

Underlying web issue is being fixed in https://github.com/ppy/osu-web/pull/9044.
