### ISSUE TITLE
Score table on beatmap overlay shows 0 score on mania maps

### ISSUE THREAD

**Issue by bdach** [ppy/osu#18824]
No idea what causes yet, just confirmed that this is an issue. No other rulesets are affected.

### Discussed in https://github.com/ppy/osu/discussions/18823

<div type='discussions-op-text'>

<sup>Originally posted by **Flamiii** June 23, 2022</sup>
This occurs with every osu!mania beatmap that has a leaderboard. The actual in-game leaderboard that isn't tied to the website functions as normal.

![osu_2022-06-23_12-53-05](https://user-images.githubusercontent.com/74088315/175363237-7e3d0141-da7f-499d-b8fb-d9f51a94928d.png)
</div>

**Comment by bdach** [comment]
Appears that this is caused by the fact that the in the following web request:

https://github.com/ppy/osu/blob/730228ec2a7fb991e1738d953e9eb95138ea4c92/osu.Game/Overlays/BeatmapSetOverlay.cs#L87-L96

mania beatmaps arrive with `APIBeatmap.MaxCombo` set to `null`:

https://github.com/ppy/osu/blob/730228ec2a7fb991e1738d953e9eb95138ea4c92/osu.Game/Online/API/Requests/Responses/APIBeatmap.cs#L78-L79

Normally `ScoresContainer` only works because of some rather rickety logic:

https://github.com/ppy/osu/blob/730228ec2a7fb991e1738d953e9eb95138ea4c92/osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs#L80-L88

https://github.com/ppy/osu/blob/730228ec2a7fb991e1738d953e9eb95138ea4c92/osu.Game/Scoring/ScoreManager.cs#L160-L167

but if it's not present, then a max combo of 0 is returned and everything else follows.

The flow around `ScoresContainer` is criminal but we know that already, it was duct-taped to work during the realm effort. Not sure why max combo has disappeared on the web side, though.

**Comment by peppy** [comment]
This has already been fixed upstream but requires reprocessing of beatmaps. I can make this happen at any point, just need to be sure I don't accidentally apply new star rating adjustments.

**Comment by smoogipoo** [comment]
For clarity, this was fixed by https://github.com/ppy/osu/issues/18493, but is awaiting deploy.

**Comment by peppy** [comment]
@smoogipoo just so I don't ask every time I visit this issue: this is pending on a server-side diffcalc update, correct? And we haven't yet decided whether to hotfix on the live branch or wait for other upcoming changes?

**Comment by smoogipoo** [comment]
We've already hotfixed the "live" branch:
- https://github.com/ppy/osu-difficulty-calculator/pull/211
- https://github.com/ppy/osu/pull/18533

Please make sure that when/if you deploy, you deploy using the branches:
- https://github.com/ppy/osu-difficulty-calculator/tree/release-diffcalc
- https://github.com/ppy/osu/tree/release-diffcalc

**Including** local-osu on the `osu-difficulty-calculator` repo (`./UseLocalOsu.sh`).

**Comment by smoogipoo** [comment]
This should no longer be an issue since the change to using ScoreV2 (`ScoreInfo.TotalScore` directly).
