### ISSUE TITLE
osu!lazer Android - Inputs not working correctly

### ISSUE THREAD

**Issue by lemocha7** [ppy/osu#18847]
### Type

Game behaviour

### Bug description

In the attached video, I was trying to press the letter keys (A, B, C, etc.) for input, but it wasn't working. After I opened the search box and typed things, it was recognizing a combination of the first key entered in the search box and either the Mouse Buttons, Ctrl, Alt, Enter, Backspace, or Escape. These inputs worked during gameplay, but only after I typed things in the search box (and once again, only the first entered letter).

I've been having issues with this since on the Android version since versions dated ~December 2021.

I'm also playing the Android version on a Chromebook by the way.

### Screenshots or videos

[https://drive.google.com/file/d/1V_3XlAj_els1T4v3wZttuVKLGjcjs6CO/view?usp=sharing](https://drive.google.com/file/d/1V_3XlAj_els1T4v3wZttuVKLGjcjs6CO/view?usp=sharing) 

### Version

2022.621.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/8985892/network.log)
[performance.log](https://github.com/ppy/osu/files/8985893/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8985894/runtime.log)
[database.log](https://github.com/ppy/osu/files/8985895/database.log)

**Comment by lemocha7** [comment]
After testing some old versions, I found out that this issue happens on 2021.1225.0.

The version directly before it, 2021.1218.0, works completely fine and has no input issues.

**Comment by Susko3** [comment]
Keyboard handling should have improved in the latest release (2022.630.0). Give it a try report back!

**Comment by lemocha7** [comment]
Yep, it works now. Thanks :)
