### ISSUE TITLE
Add touch support for all rulesets

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18882]
Per-ruleset (non-customisable) implementations as a first step.

## osu!

- Tapping anywhere on the screen while a finger is already pressed should count as a tap
- Up to two fingers should be usable in such a way (three contact points in total)
- Should gracefully switch to this mode after the first tap, ie. a user should be able to play by tapping hitcircles directly if they choose to

## osu!taiko

- A drum should appear at the bottom of the screen
- Follow up would see three separate buttons as draggable elements which can be rearranged to a user's liking

## osu!catch

- Screen areas should be used to signal direction and dash keys. Needs more thought as to where these should be
- Follow up would see three separate buttons as draggable elements which can be rearranged to a user's liking

## osu!mania

- Screen areas should be used to interact with columns. These should be larger than the columns themselves, potentially signalled by a visual element which connects them back to the columns
- Follow up would see the ability to change the perspective of the playfield to make the columns approach the full width of the screen at the location the user is tapping

**Comment by frenzibyte** [comment]
Related: https://github.com/ppy/osu/issues/4201

**Comment by zachmanthethird** [comment]
#17200 will implement the first bullet point for osu!taiko.

**Comment by StarsDream00** [comment]
maybe adding full-wide keys to osu!mania is a solution?

**Comment by killer78887** [comment]
just to be sure i wanna ask that osu! points still need to be implemented right?

**Comment by Joehuu** [comment]
Has since been completed.
