### ISSUE TITLE
Change notifications to be toasts

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18885]
When a new notification arrives, it should show up momentarily (like stable) before ending up in the notification overlay. The transition of when it displays to when it enters the overlay should be seamless.

This will improve the very awkward user experience of having the notification overlay suddenly appear while you're trying to do something else.

**Comment by LittleEndu** [comment]
* see also: https://github.com/ppy/osu/issues/10222

**Comment by bdach** [comment]
I'm guessing this is going to require design before proceeding? Or is there one available?

**Comment by peppy** [comment]
One more note to add here is that once this is done, a lot of tests should be checked and updated to not wait on potential notifications forcefully opening the notification overlay.
