### ISSUE TITLE
Change all online displays to prefer featured artist beatmaps by default

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18881]
As the number of licensed tracks we have on osu! increases, it only makes sense to display them as the primary game content, with user uploaded content (that may be licensed incorrectly) taking a back seat.

While not *required* for mobile releases, personally this would make me feel a lot better about releasing the game to a larger audience that comes with them. It will also hopefully avoid (rightfully) pissing off other mobile rhythm game developers from users uploading paid content from their games to osu!.

Online views should default to featured artist beatmaps, requiring the filter to be changed by the end user (and showing a disclaimer when changed) in order to see other beatmaps.

We may want to also consider applying this to multiplayer / playlists as a future step.

**Comment by frenzibyte** [comment]
This has been fulfilled by https://github.com/ppy/osu/pull/21646.
