### ISSUE TITLE
Add client-server loop for awarding medals

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18880]
We already have a (very dated) medal award implementation, so the first step should be to get the communication working so the server can let us know when new medals are achieved. Should likely use SignalR, potentially as part of the new `BeatmapHub` i'm working on.

This time around, we hope to make medals awarded outside of the results screen, so we can award them for things that aren't necessarily related to a score being submitted.

**Comment by Walavouchey** [comment]
a consideration for medals is the difficulty to pass maps. with the current hp and notelock implementation, many medals would become much easier

**Comment by peppy** [comment]
It doesn't matter if not all medals are online when lazer goes live. The goal would be getting the basic and important ones.

**Comment by peppy** [comment]
Not going to happen this year, moving out of project for now.

As an update, we already support pack medals, but others are not implemented yet.
