### ISSUE TITLE
Create a list of all gameplay changes

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18894]
We have made quite a few changes to gameplay across all rulesets in lazer. Some of these can be reverted with "classic" mods.

A document needs to be created covering each and every change, along with rationale and technical details, so they can be digested by users (and be used as a reference for things like making osu!wiki pages in the future).

We should also use this as an opportunity to make sure all the gameplay changes we've made still make sense and that we're all happy with them. A recent example of this would be #18795 / https://github.com/ppy/osu/discussions/18870#discussioncomment-3030791.

### Changes yet to be considered

- https://github.com/ppy/osu/discussions/13187
- https://github.com/ppy/osu/discussions/18905
- https://github.com/ppy/osu/issues/18968
- https://github.com/ppy/osu/issues/19590

**Comment by ggliv** [comment]
related: https://github.com/ppy/osu/wiki/Gameplay-differences-from-osu!stable

**Comment by peppy** [comment]
Of note, the wiki page above is a bit out of date now. There's a more comprehensive list of gameplay changes being maintained over at osu-wiki: https://osu.ppy.sh/wiki/en/Client/Release_stream/Lazer/Feature_comparison

**Comment by Walavouchey** [comment]
what is this issue tracking?

**Comment by peppy** [comment]
I'm going to close this as @Walavouchey has said he's pretty confident the [wiki](https://osu.ppy.sh/wiki/en/Client/Release_stream/Lazer/Gameplay_differences_in_osu%21%28lazer%29) is up-to-date with all gameplay changes.
