### ISSUE TITLE
Playlists and multiplayer scores should also be counted for solo leaderboards

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18900]
Currently multiplayer and playlists use their own score submission endpoints. This should be combined at the osu-web side, using the single new storage (`solo_scores`) and linking to multiplayer or playlist rooms as required.

**Comment by respektive** [comment]
Related: https://github.com/ppy/osu/issues/15888

**Comment by peppy** [comment]
This should be resolved via https://github.com/ppy/osu-web/pull/10437.
