### ISSUE TITLE
OpenTK exception on startup: entry point in SDL2.dll not found

### ISSUE THREAD

**Issue by jorolf** [ppy/osu#1896]
```
12.01.18 20:15:58: fatal error:
12.01.18 20:15:58: System.EntryPointNotFoundException: Der Einstiegspunkt "SDL_GetGlobalMouseState" wurde nicht in der DLL "SDL2.dll" gefunden.
12.01.18 20:15:58: bei OpenTK.Platform.SDL2.SDL.GetGlobalMouseState(Int32& hx, Int32& hy)
12.01.18 20:15:58: bei OpenTK.Platform.SDL2.Sdl2Mouse.GetCursorState()
12.01.18 20:15:58: bei OpenTK.Input.Mouse.GetCursorState()
12.01.18 20:15:58: bei osu.Framework.Input.Handlers.Mouse.OpenTKRawMouseHandler.<>c__DisplayClass9_0.<Initialize>b__1()
12.01.18 20:15:58: bei osu.Framework.Threading.ScheduledDelegate.RunTask()
12.01.18 20:15:58: bei osu.Framework.Threading.Scheduler.Update()
12.01.18 20:15:58: bei osu.Framework.Threading.GameThread.ProcessFrame()
12.01.18 20:15:58: bei osu.Framework.Platform.GameHost.<Run>b__90_1(Object <p0>, FrameEventArgs <p1>)
12.01.18 20:15:58: bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
12.01.18 20:15:58: bei OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
12.01.18 20:15:58: bei OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
12.01.18 20:15:58: bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
12.01.18 20:15:58: bei osu.Framework.Platform.GameHost.Run(Game game)
12.01.18 20:15:58: bei osu.Desktop.Program.Main(String[] args)
```

not really sure what causes or fixes it but visual tests work and after compiling them debug works too

**Comment by VPeruS** [comment]
Where you put SDL and what version it is?

**Comment by jorolf** [comment]
idk, I've never put it anywhere

**Comment by VPeruS** [comment]
Try to search. One possible reason that your version of SDL is outdated and function is not avaliable.

**Comment by jorolf** [comment]
why does it work then when I'm running visual tests?
And has no one else encountered this problem if it's an outdated version? I'm running win10 and not win98

**Comment by VPeruS** [comment]
https://wiki.libsdl.org/SDL_GetGlobalMouseState look at version. last sdl 2.0.7. Visual tests use raw input?

**Comment by peppy** [comment]
Please do as vperus asked and find where your SDL dll is. providing a path where it exists and it’s version would be a great start.

**Comment by jorolf** [comment]
I don't have a SDL file, I even searched my whole drive and it only found sdl files related to other games

**Comment by peppy** [comment]
Can you run in debug and find the path of the SDL which is being loaded by osu!?

It should be under Debug > Windows > Modules, hopefuly

**Comment by jorolf** [comment]
it doesn't load even load it

**Comment by peppy** [comment]
Dude, the exception you're getting can only be thrown is an sdl2 is found and being used. opentk won't even use sdl unless it loads the dll. You're gonna have to search harder.

**Comment by jorolf** [comment]
Do you think I didn't? I would guess this is an opentk bug

**Comment by jorolf** [comment]
Okay..... for some reason it's loading SDL 2.0.1.0 from qemu

**Comment by jorolf** [comment]
Probably because i put the qemu folder in my Path variable. great 😐

**Comment by jorolf** [comment]
Updated the dll from qemu manually and now everything works
