### ISSUE TITLE
M1 doesn't refresh input after pressing K1 in game and vise-versa 

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#1897]
In osu-stable while holding M1 you can press K1 and when you release K1, M1 would refresh. Same for K2 and M2.

**Comment by peppy** [comment]
what does refresh mean?

**Comment by LittleEndu** [comment]
It would get pressed again but if you were holding a slider (or spinning a spinner) it wouldn't break. So somewhere in-between pressing again and having never released in the first place. Don't know how to describe that but the gist is that you can press both, at the same time, in osu-stable without having to worry about breaking combo or stopping the spinner.

**Comment by peppy** [comment]
So what you are reporting is that sliders get broken if you press and release K1 while holding M1 the whole time?

**Comment by peppy** [comment]
I can see what you mean; that definitely looks to be a regression.

**Comment by LittleEndu** [comment]
Yes, You start slider with M1, press and release K1, and slider breaks (same with spinner), and vice-versa (start K1, press M1...)
