### ISSUE TITLE
Multiplayer map edit button always jumps to the first map in the map selection carousel

### ISSUE THREAD

**Issue by leryss** [ppy/osu#18987]
### Type

Game behaviour

### Bug description

When you have multiple songs selected in the queue and you click the edit button of any song it always jumps (in the carousel map select) to the first song from the queue. That is very annoying when you just want to edit real quick and change the difficulty of the map.

Also when you click "Add Item" to add a new song to the queue it also selects the first map from the queue in the carousel. Can be annoying if you want to add a bunch of maps to the queue because it keeps backtracking to the first song, my opinion is that it should default to the last song in the queue.

### Screenshots or videos

![Animation](https://user-images.githubusercontent.com/8768822/176994533-87a9e66c-5c86-4043-b9c9-36f5a85cd536.gif)

### Version

2022.630.0

### Logs

[updater.log](https://github.com/ppy/osu/files/9032719/updater.log)
[database.log](https://github.com/ppy/osu/files/9032720/database.log)
[network.log](https://github.com/ppy/osu/files/9032721/network.log)
[performance.log](https://github.com/ppy/osu/files/9032722/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9032723/runtime.log)

**Comment by peppy** [comment]
Encountered this yesterday
