### ISSUE TITLE
Mania's keysounded maps don't load the background music

### ISSUE THREAD

**Issue by just7nz** [ppy/osu#18999]
### Type

Game behaviour

### Bug description

In stable, keysounded maps use keysounds + background music to represent the full song, however, in lazer the background music seems to be missing. There aren't many fully keysounded maps as far as I know, but these are some ranked ones that are definitely affected (e. g. https://osu.ppy.sh/beatmapsets/92190, https://osu.ppy.sh/beatmapsets/152065)

### Screenshots or videos

https://user-images.githubusercontent.com/61681644/177179779-5e834b14-aac6-405e-a1c6-249067a07ad4.mp4

https://user-images.githubusercontent.com/61681644/177179796-389b7716-08a3-40d6-934b-d7b7588d81bd.mp4

### Version

2022.074.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/9040435/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9040436/updater.log)
[database.log](https://github.com/ppy/osu/files/9040437/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9040438/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9040439/network.log)
[performance.log](https://github.com/ppy/osu/files/9040440/performance.log)

**Comment by smoogipoo** [comment]
Not sure if the above is a guess at what's going on, but this is caused by storyboards being disabled which consequently also disables all storyboard samples.

**Comment by peppy** [comment]
Was indeed a guess. But also to my recollection stable handles the same way?

**Comment by smoogipoo** [comment]
I think storyboard samples are a separate thing that always play in stable. Also related: https://github.com/ppy/osu/issues/9315

**Comment by peppy** [comment]
Based on the other thread, it seems there's not a consensus for how the storyboard toggle should behave. Maybe the best way going forward is to show a notification to the user if they are playing a storyboard with storyboarded samples and have the storyboard disabled? Or split the storyboard toggle into two pieces?

**Comment by frenzibyte** [comment]
> show a notification to the user if they are playing a storyboard with storyboarded samples and have the storyboard disabled

Feels noisy for people who would prefer not to play with storyboard though (due to performance concerns or otherwise).

> Or split the storyboard toggle into two pieces?

Not sure if a second toggle is warranted, I would think it's enough for the storyboard samples to be controlled by the same "Storyboard / video" toggle but have them still play at 100% dim (which is what #9315 tracks).

**Comment by frenzibyte** [comment]
I see... feels somewhat off that the music track is included within the beatmap's "storyboard", but for now I think I'm on board with a second "storyboard audio" toggle then? Will wait for further opinions.

**Comment by smoogipoo** [comment]
Either a separate toggle or no toggle at all as stable does.

**Comment by ikzune** [comment]
I am seeing a lot of songs with .ogg files that have this issue but there are some maps where the .ogg has been put inside the .osu which seems to prevent it from importing correctly
![Capture](https://user-images.githubusercontent.com/31851536/193227681-306d4eb4-acec-4031-9865-1982ad618027.PNG)

**Comment by peppy** [comment]
@ok have you confirmed that turning storyboards ON does not fix the issue?

**Comment by ikzune** [comment]
Turning on the storyboards does deal with the issue

I managed to get the other maps to import properly by turning them into a .osz and dragging the file into osulazer so i'm probably wrong about the issue being related

**Comment by Vad1mCSO2** [comment]
This issue can be resolved

**Comment by Vad1mCSO2** [comment]
https://user-images.githubusercontent.com/76803825/233815459-59aa0810-90f6-4150-b86d-60e57596bb87.mp4

@peppy Keysound is working
