### ISSUE TITLE
Profile Picture of the user is not displayed when opening a replay.

### ISSUE THREAD

**Issue by Coppertine** [ppy/osu#19012]
### Type

Cosmetic

### Bug description

Below is replicated by downloading any replay and opening said replay into lazer.

### Screenshots or videos

![osu_2022-07-06_13-19-22](https://user-images.githubusercontent.com/37494321/177460786-9d7eabc1-c967-49eb-9bbe-2a2bab78e965.png)
https://osu.ppy.sh/scores/osu/4209619408 (Link to play)

### Version

2022.704.0-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/9051212/updater.log)
[network.log](https://github.com/ppy/osu/files/9051213/network.log)
[runtime.log](https://github.com/ppy/osu/files/9051214/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9051215/performance.log)
[database.log](https://github.com/ppy/osu/files/9051216/database.log)

**Comment by peppy** [comment]
This is because right now user IDs are not populated when importing a replay (as that data is not contained in the replay format).

**Comment by novialriptide** [comment]
Hi @peppy, can I work on this issue?

**Comment by novialriptide** [comment]
While trying to test my new code, I can't seem to view the scoreboards for osu!lazer to export a replay. Is there a way to fix this? (I'm using the development version)

![image](https://user-images.githubusercontent.com/35881688/177700898-682524ae-7dc2-4d1c-b7b2-c2e3ac2d1b54.png)

**Comment by Coppertine** [comment]
> While trying to test my new code, I can't seem to view the scoreboards for osu!lazer to export a replay. Is there a way to fix this? (I'm using the development version)
> 
> ![image](https://user-images.githubusercontent.com/35881688/177700898-682524ae-7dc2-4d1c-b7b2-c2e3ac2d1b54.png)

It's best to use an already made replay on stable

**Comment by novialriptide** [comment]
> 

Got it! Thanks!

**Comment by frenzibyte** [comment]
> While trying to test my new code, I can't seem to view the scoreboards for osu!lazer to export a replay. Is there a way to fix this? (I'm using the development version)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/35881688/177700898-682524ae-7dc2-4d1c-b7b2-c2e3ac2d1b54.png)
> 
> 

Would also like to note that you're getting this due to running in development server. Switching to "release" configuration or manually changing `UseDevelopmentServer` should allow you to connect to production.

**Comment by novialriptide** [comment]
I'm slightly confused on how `API.PerformAsync()` and `GetUserRequest` works, how would I retrieve the user id value after sending an API request?

**Comment by novialriptide** [comment]
> A simple solution would be to resolve the user ID from the player's username via API requests after score import, likely at `ScoreImporter.PostImport`

Are you talking about the `PostImport` here? https://github.com/ppy/osu/blob/master/osu.Game/Database/RealmArchiveModelImporter.cs#L342

I can't find any `ScoreImporter.PostImport`, but I found a way to get the user's ID from their username. I just don't know where to put it.

**Comment by frenzibyte** [comment]
I mean overriding `PostImport` and doing the user ID population process there.

**Comment by novialriptide** [comment]
Sorry for asking so many questions, so the correct way to implement this would be to
1. Override `PostImport` in `ScoreImporter`
2. Send a `GetUserRequest` to the `API`
3. Then use the `Populate()` function

If so, I'm not sure how to reference the `API` since that doesn't exist in `ScoreImporter`.

**Comment by frenzibyte** [comment]
It's best to search for similar usages across similar components and generally try figuring things yourself rather than have me give an answer to every detail. Try looking at how `ScoreImporter` already has access to some of the main game components, it's done by providing them from `OsuGameBase` via constructor.

Also would recommend asking such questions on [discord](https://discord.gg/ppy) rather than on GitHub threads, to lower the noise.

**Comment by novialriptide** [comment]
> It's best to search for similar usages across similar components and generally try figuring things yourself rather than have me give an answer to every detail. Try looking at how `ScoreImporter` already has access to some of the main game components, it's done by providing them from `OsuGameBase` via constructor.
> 
> Also would recommend asking such questions on [discord](https://discord.gg/ppy) rather than on GitHub threads, to lower the noise.

Thanks! I didn't know this existed.
