### ISSUE TITLE
Slider hitcircle doesn't disappear correctly on hidden.

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#1903]
It's supposed to be 0% visible when I need to hit it but it seems to disappear along with sliderbody.

**Comment by Aergwyn** [comment]
Ah, yes now I see what you mean. Seems to be a side effect of moving code from `DrawableHitObject<T>` into `DrawableHitObject`.

**Comment by LittleEndu** [comment]
Now, looking at osu-stable behaviour, sliderbody is supposed to start fading after hitcircle is hit. So right now, lazer seems to put both of them togather. Both circle and body fade from appearance to finish.

**Comment by Aergwyn** [comment]
No it's just that the HitCircle doesn't fade out early at all. The mentioned change from my previous post broke the animation. Go back a few commits and you'll see it working properly.

**Comment by LittleEndu** [comment]
Yeah, I didn't look at the code and the new slider design confused me there. Sliderbodies fade just fine, so never mind that

**Comment by LittleEndu** [comment]
Just noticed, but I think slider heads still don't fade soon enough. Hard to measure when there's no hit meter but it seems regular hitcircles fade to 0% a bit before you need to hit them while slider heads finish fading to 0% right before you need to hit them.

Should this be reopened or should new issue be created?

**Comment by LittleEndu** [comment]
Yeah it's definitely not fading correctly. Tried on https://osu.ppy.sh/b/741477 with +EZ,HT - The first slider head is already 0% when the music starts on osu-stable while it's about 25% on lazer.

**Comment by LittleEndu** [comment]
@peppy Can you reopen this? or should I make new issue?
