### ISSUE TITLE
crash at osu!lazer 2022.709.0

### ISSUE THREAD

**Issue by toadsworth-jr** [ppy/osu#19049]
### Type

Crash to desktop

### Bug description

Upgrade of installation from osu!lazer 2022.704.0 via an apk file downloaded from GitHub caused osu to no longer function as intended.
System specifications are shown below, courtesy of Inware:
![Screenshot_20220709_035422_com evo inware](https://user-images.githubusercontent.com/75596775/178062409-11624391-9406-4596-883a-12785c69ae3e.jpg)
![Screenshot_20220709_035542_com evo inware](https://user-images.githubusercontent.com/75596775/178062419-c15bcbbb-10f6-462d-af3b-01c2496fbedb.jpg)

### Screenshots or videos

https://user-images.githubusercontent.com/75596775/178063000-c2b3f1ca-cbb1-4105-9680-82531ac540cc.mp4

For additional context, the problematic version is already installed, which leaves downgrading to the last release (shown in the video as "sh.ppy.osulazer 2022-704-0.apk") as a prohibited option.

### Version

2022.709.0

### Logs

[database.log](https://github.com/ppy/osu/files/9074793/database.log)
[network.log](https://github.com/ppy/osu/files/9074794/network.log)
[runtime.log](https://github.com/ppy/osu/files/9074795/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9074796/performance.log)

**Comment by peppy** [comment]
Should be fixed in 2022.709.1.

**Comment by toadsworth-jr** [comment]
Seems to be regressed in 2022.1008.0
I've tried everything: reinstalling from scratch, redownloading the APK in case it was corrupt, freed up storage, even rebooted several times.
This was the only log that it could generate until the game crashed.
[runtime.log](https://github.com/ppy/osu/files/9739057/runtime.log)
