### ISSUE TITLE
Ruleset API breaking changes / announcements

### ISSUE THREAD

**Issue by peppy** [ppy/osu#19068]
This issue is intended to be a place custom ruleset developers can subscribe to so we can forward critical information on incoming breaking changes (or convey error reports we are seeing) to avoid breakage.

While this thread will be locked to keep traffic low, if you have any concerns about changes in this thread, or need further help, please don't hesitate to open a new issue or discussion!

cc/ @LumpBloom7 @Beamographic @taulazer @EVAST9919 @andy840119 @swoolcock

**Comment by peppy** [comment]
Please check in on https://github.com/ppy/osu/pull/19066 (NRT nullable support being added to the `Ruleset` class). While not finalised yet, it would be good to cross-check and bring any concerns to light before it is merged. It may also be a good opportunity to make other breaking changes, if there are any outstanding requests.

**Comment by peppy** [comment]
A few updates here:

- For any rulesets which are using shaders or other lower level graphics APIs, please check the recent [osu!framework breaking changes](https://github.com/ppy/osu-framework/wiki/Breaking-changes) to ensure compatibility. One example we found was a ruleset using the slider path renderer by copy-pasting the code, but not updating to track the new implementation (https://sentry.ppy.sh/share/issue/0499e9ae8f284ec7b56a04e87b0388a5/)
- Update string to `LocalisableString`s in line with localisation support additions (see https://github.com/ppy/osu/pull/19695)

I am in the process of adding ruleset versioning, which will initially be opt in, but may become a requirement at some point. Will leave another message here when that is ready. It should avoid all game crashes surrounding breaking changes (by not loading the ruleset in the first place unless it's up-to-date).

**Comment by Joehuu** [comment]
Unpinning for now because of no new updates since 2022. Can be converted to an "announcement" discussion instead as it's a better fit there.
