### ISSUE TITLE
Crash when trying to spectate in multiplayer

### ISSUE THREAD

**Issue by leryss** [ppy/osu#19061]
### Type

Crash to desktop

### Bug description

Sometimes the game crashes when you try to spectate in a multiplayer lobby, this time I grabbed the logs to share.
How it happened: host started the game and I wasnt on ready state. I waited a bit, pressed spectate and then the game froze  and crashed.

### Version

2022.709.1

### Logs

[performance.log](https://github.com/ppy/osu/files/9077412/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9077413/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9077415/updater.log)
[database.log](https://github.com/ppy/osu/files/9077416/database.log)
[network.log](https://github.com/ppy/osu/files/9077417/network.log)

**Comment by peppy** [comment]
As seen in recent 15th anniversary lobby, bumping up in priority.
