### ISSUE TITLE
Issue Merged to osu-web

### ISSUE THREAD

**Issue by DolphiiineRe** [ppy/osu#1906]
Hello i've found some mistakes on the translations on the latest [website](https://osu.ppy.sh/home).
I'm understand that website is not complete, and that issue will be a "low priority" for the development, But I wanted to say it so that it does not stay that way. 

So i've found theses on the French Translations.

When you are on your profile and you want to change some things in your profile, you go to the settings, except that I saw that the title "Account Settings" is correct for the English translation but not for the French translation that marks "Paramètres de compte Compte" which means in English "Account Account Settings".

For now I just noticed that this error except for the modding watchlist page that does not seem to be finished which is totally in English for the French translation.

Im gonna search all mistakes about French translations.

**Comment by jorolf** [comment]
Wrong repository, the correct one is https://github.com/ppy/osu-web
