### ISSUE TITLE
⚠️ ArgumentOutOfRangeException: Value range is [0, 15]. (Parameter 'value')

### ISSUE THREAD

**Issue by EnderDremurr** [ppy/osu#19085]
### Type

Game behaviour

### Bug description

Game throws out a three " ⚠️ ArgumentOutOfRangeException: Value range is [0, 15]. (Parameter 'value') " errors from start, and graphical tablet (Ugee M708) dont working

i`m using Manjaro Gnome (x11) with OpenTabletDriver
kernel 5.15.50

### Screenshots or videos

![image](https://user-images.githubusercontent.com/83834601/178503329-3d77297c-ab18-4cdd-8102-026e4a470f9a.png)

### Version

2022.709.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9093438/database.log)
[network.log](https://github.com/ppy/osu/files/9093439/network.log)
[performance.log](https://github.com/ppy/osu/files/9093440/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9093441/runtime.log)

**Comment by peppy** [comment]
I have no idea what this means. Please report over at https://github.com/OpenTabletDriver/OpenTabletDriver

**Comment by jamesbt365** [comment]
OpenTabletDriver team here. This means the Kernel driver is still loaded. (his_uclogic) and therefore your tablet can't be used within the game. Read the wiki on https://opentabletdriver.net/Wiki/FAQ/Linux for more info.
