### ISSUE TITLE
Importing skins with large assets gets very slow on macOS

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#19116]
### Type

Performance

### Bug description

Happening due to the file IO overhead from `RealmFileStore`'s use of file streams which flush on disposal, as the flush performed also flushes intermediate data buffers (i.e. `Flush(flushToDisk: true)`).

Opening issue to keep track of this as it's quite a bad one for macOS users and me personally (resorted to deleting all large skins I had).

See [previous discussion](https://discord.com/channels/188630481301012481/188630652340404224/996998527064473610).

### Version

b511c9cc3fd253926a0f4f79abb2e50e74476e0c

### Logs

-

**Comment by peppy** [comment]
By "Realm's use" you mean the model importer class right? When you say "realm's use" it sounds like it's something their end, which I am not sure it is? Would help if you show a basic snapshot of profiling during the import.

**Comment by frenzibyte** [comment]
Yeah I meant the model importer class, took the term from reading the class name (`RealmFileStore`).

<img width="1628" alt="CleanShot 2022-07-14 at 08 23 54@2x" src="https://user-images.githubusercontent.com/22781491/178905759-f3640c7f-9a1b-4957-ba59-ef9e53f5b48e.png">

**Comment by frenzibyte** [comment]
Upon further investigation, the flushing overhead only started occurring since switching to .NET 6

| .NET 5 | .NET 6 |
|--------|--------|
| <img src="https://user-images.githubusercontent.com/22781491/179130113-8fd09890-1bb2-46da-a53b-962014c1887c.png"/> | <img src="https://user-images.githubusercontent.com/22781491/179130085-81fc3770-61c1-4c47-8b57-d31ce6a2e0f4.png" /> |

Noticed this as I was looking through existing issue threads about file flushing on .NET, and finding https://github.com/dotnet/runtime/issues/28444 which was addressed on .NET 6 ([specifically the `F_FULLSYNC` flag](https://github.com/dotnet/runtime/issues/28444#issuecomment-475058760)).
