### ISSUE TITLE
osu!mania hit lighting doesn't rewind correctly

### ISSUE THREAD

**Issue by peppy** [ppy/osu#19119]
### Discussed in https://github.com/ppy/osu/discussions/19118

<div type='discussions-op-text'>

<sup>Originally posted by **Loreos7** July 14, 2022</sup>
I dont think this is intentional

https://user-images.githubusercontent.com/86934170/178926551-e88374d3-f062-4cd9-963b-ae6476e1f246.mp4

</div>

**Comment by Loreos7** [comment]
Alright, I found initial issue. https://github.com/ppy/osu/issues/9117
