### ISSUE TITLE
Online leaderboards scores have some different values

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#19144]
### Type

Other

### Bug description

For now, I can only verify this with my replays. There seems to be some inconsistency here (as you can see in the screenshots below, the values for "barrel roll," "difficulty adjust," and spinners' spins/bonus are different along with the final score as well, but I don't know if it's related to the mods and stuff).
In case you need it, this is the map: https://osu.ppy.sh/beatmapsets/1749750#osu/3579611
And [here's the replay (change the extension from `zip` to `osr`)](https://github.com/ppy/osu/files/9125739/Gabixel.playing.Gabry.Ponte.LUM.X.Prezioso.-.Thunder.Nightcore.Mix.P.A.N.Thunder.zip).

### Screenshots or videos

Local score:

![image](https://user-images.githubusercontent.com/43073074/179354421-26db3ad2-5af6-4234-a343-22a12384e789.png)

Online score:

![image](https://user-images.githubusercontent.com/43073074/179354429-ac6a6168-f48e-4baf-a428-694436ecdb6f.png)

### Version

2022.716.1-lazer

### Logs

n/a

**Comment by memesnightmares** [comment]
I also see some scores lower on the global leaderboard than they are locally when they are in fact the same play. I believe this is because on the global leaderboard the "Spinner Bonus" and "Spinner Spin" values are 0 whereas locally they are positive.

**Comment by frenzibyte** [comment]
> I also see some scores lower on the global leaderboard than they are locally when they are in fact the same play. I believe this is because on the global leaderboard the "Spinner Bonus" and "Spinner Spin" values are 0 whereas locally they are positive.
> 
> 
> 
> For other peoples scores they seem positive, and on some of my plays they seem positive, but not all. Seems like more recent scores *do* have the spinner stats but older plays don't. I haven't been able to isolate when the changed happened yet though. And, regardless of age, the spinner stats are positive on other peoples plays.

That is correct, it was an oversight which has been fixed about 4 months ago.

**Comment by frenzibyte** [comment]
As for OP, the web returns the correct mod settings values, this is likely an issue with serialisation, will investigate further. The spinner bonus/spin issue has been fixed a month ago as per above.
