### ISSUE TITLE
Score's dates in browser has been reset to 1 January of 0001 year

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#19146]
### Type

Game behaviour

### Bug description

2022 years ago

### Screenshots or videos

![image](https://user-images.githubusercontent.com/86934170/179354935-41906c32-3b68-42d5-b04b-0aa233135a27.png)

### Version

716.1

### Logs

[network.log](https://github.com/ppy/osu/files/9125726/network.log)
[runtime.log](https://github.com/ppy/osu/files/9125727/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9125728/performance.log)
[database.log](https://github.com/ppy/osu/files/9125729/database.log)
[updater.log](https://github.com/ppy/osu/files/9125730/updater.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9125731/legacy-ipc.log)

**Comment by peppy** [comment]
Are you reporting an osu-web issue? if so please report on the correct repository.

**Comment by Theighlin** [comment]
> Are you reporting an osu-web issue? if so please report on the correct repository.

I thought too it wasat first, but by the cursor it looks to be the in-game browser.

**Comment by Loreos7** [comment]
> Are you reporting an osu-web issue? if so please report on the correct repository.

No, of course not. Its in the in-game embedded browser (user profile)
