### ISSUE TITLE
Audio waveforms are invisible

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#19149]
### Type

Cosmetic

### Bug description

As title. Tested on a new beatmap and one already ranked

### Screenshots or videos

![image](https://user-images.githubusercontent.com/43073074/179355842-1e106beb-e8b0-418f-a8dc-5ba0fa5acc91.png)

![image](https://user-images.githubusercontent.com/43073074/179355759-28c773c4-0f62-4ca8-b7b1-4d41ac0251f1.png)

### Version

2022.716.1-lazer

### Logs

n/a

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/18479
