### ISSUE TITLE
when trying to play different songs in a compilation only the first song plays 

### ISSUE THREAD

**Issue by SirMrpanda** [ppy/osu#19153]
### Type

Game behaviour

### Bug description

it's hard to describe, let's say you go on a song with a bunch of different songs in it, for example aim practice maps, only the first song plays so if you try to play another song in the same map you get the map but the song stays the same as the first song.

### Screenshots or videos

https://user-images.githubusercontent.com/103606646/179357261-77ed1389-0dfb-4c3f-9d2e-251ab60a63f5.mp4

https://user-images.githubusercontent.com/103606646/179357274-be717190-198d-412b-b501-15e0de5a558f.mp4

### Version

Lazer 2022.716.1

### Logs

[database.log](https://github.com/ppy/osu/files/9125850/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9125851/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9125852/network.log)
[performance.log](https://github.com/ppy/osu/files/9125853/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9125854/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9125855/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9125856/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9125857/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9125858/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9125859/updater.log)

**Comment by peppy** [comment]
Link the beatmap.

**Comment by SirMrpanda** [comment]
https://osu.ppy.sh/beatmapsets/825086#osu/3082727
https://osu.ppy.sh/beatmapsets/968216#osu/2026026
but all beatmaps like these have the same issue i can link more if you want

**Comment by SirMrpanda** [comment]
> Link the beatmap.
https://osu.ppy.sh/beatmapsets/825086#osu/3082727
https://osu.ppy.sh/beatmapsets/968216#osu/2026026
but all beatmaps like these have the same issue i can link more if you want

**Comment by XeZey** [comment]
this also happens on mapsets which use rates (1.1x, 1.2x etc) in case thats useful information

**Comment by Skylake-dev** [comment]
Same issue here, happens on all beatmaps where there are different songs, for example
https://osu.ppy.sh/beatmapsets/1292572#osu/3098881
https://osu.ppy.sh/beatmapsets/825086#osu/3082727
Also when trying to play, the notes are correct but the song is wrong, it plays always the first

**Comment by bdach** [comment]
closing in favour of #19161 as the two issues overlap, but that one has a wider scope (also includes backgrounds) and a better title
