### ISSUE TITLE
Capitalisation for result breakdown screen are not consistent.

### ISSUE THREAD

**Issue by 3stantedja** [ppy/osu#19155]
### Type

Cosmetic

### Bug description

With lazer score submission being shown for the time being, score panels that are being minimised shows that capitalisations for statistics that are currently specific for lazer (eg. in osu!std: slider ticks and ends, spinner bonus and spinner spin, which are not shown when minimised) aren't capitalised as expected.

### Screenshots or videos

Shown below are the rulesets where the capitalisation discrepancy is visible:

## osu!
![osu_2022-07-16_06-56-01](https://user-images.githubusercontent.com/3055647/179358198-c1d1f1c9-6c85-4952-8ee1-e606bccec221.jpg)

## Mania
![osu_2022-07-16_06-58-55](https://user-images.githubusercontent.com/3055647/179358206-da167dea-78c4-46d3-96ae-d8bd18d131c6.png)

## Catch
Not too sure about Catch though because I'm not sure if it's meant to be sentence-case or title-case.
![osu_2022-07-16_07-01-31](https://user-images.githubusercontent.com/3055647/179358619-decdff2c-1caa-43b1-8a2e-7697e7f8c05d.png)

### Version

2022.716.1

### Logs

[updater.log](https://github.com/ppy/osu/files/9125970/updater.log)
[performance.log](https://github.com/ppy/osu/files/9125971/performance.log)
[database.log](https://github.com/ppy/osu/files/9125972/database.log)
[runtime.log](https://github.com/ppy/osu/files/9125973/runtime.log)
[network.log](https://github.com/ppy/osu/files/9125974/network.log)

**Comment by frenzibyte** [comment]
All statistics should be in uppercase, so `pp` should be `PP` as well.

**Comment by 3stantedja** [comment]
Would it be better for the statistics be localisable, or would just changing the strings in the code be fine for now? Because while filing this bug report I found the strings where some of the statistics were named for each ruleset.

**Comment by 3stantedja** [comment]
Can I have a go at it? Like my previous comment, I went through the codebase and saw that the ones that aren't using titlecase are being named in the code instead of being localised elsewhere. So I thought that for now it would be simple to do a simple pass over the ruleset and give "correct-looking" capitalisations (read: titlecase), since it's within my skillset. I don't know if it would be ok for me to submit a really simple pull request for now.

**Comment by frenzibyte** [comment]
I was confused into thinking the expanded panel middle content is the one at fault (thinking `PP` is not capitalised). I believe fixing this should be a one-liner by enforcing title casing to all statistic labels in the contracted variant. I'll leave you to figure that out.
