### ISSUE TITLE
Cannot add single tap and repel mods to map in multiplayer

### ISSUE THREAD

**Issue by Kudostoy0u** [ppy/osu#19162]
### Type

Game behaviour

### Bug description

Found the bug by using the "select all" option under mod select. 

Narrowed the issue down to the single tap and repel mods

### Screenshots or videos

![image](https://user-images.githubusercontent.com/69732000/179366193-52b5ba5d-cc87-4e22-a227-cd2679a2d7cd.png)

### Version

2022.716.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9126296/database.log)
[network.log](https://github.com/ppy/osu/files/9126301/network.log)
[runtime.log](https://github.com/ppy/osu/files/9126303/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9126302/performance.log)

**Comment by frenzibyte** [comment]
Probably missing osu-web support for those mods.

**Comment by peppy** [comment]
It's a spectator server issue. I'll deploy an updated version within the next 24 hours.

**Comment by peppy** [comment]
New server is spinning up. Any new multiplayer rooms should work correctly.
