### ISSUE TITLE
Ability to mute the game

### ISSUE THREAD

**Issue by aQaTL** [ppy/osu#1918]
While there is a "Boss" key that hides Osu from taskbar and mutes it, I don't find this really convenient. I have an idea for 2 different options to mute Osu. So how about a key binding for toggling mute/unmute and a switch in settings to automatically mute Osu when losing focus (on alt+tab for example)?

**Comment by peppy** [comment]
Should probably be implemented in the form of a toggle in global options "mute when inactive".
