### ISSUE TITLE
Perfect mod incompatibility tooltip does not include auto pilot

### ISSUE THREAD

**Issue by hburn7** [ppy/osu#19199]
### Type

Cosmetic

### Bug description

A simple visual bug. The perfect mod tooltip does not show that the auto pilot mod is also incompatible.

### Screenshots or videos

![osu!_2QXc3axK4s](https://user-images.githubusercontent.com/38370573/179421932-9bc6b01e-5cbb-4e0b-8cec-e056864becd1.png)
![osu!_tm0T1HBXl7](https://user-images.githubusercontent.com/38370573/179421935-1858f52f-52e8-4d85-9bcb-50f78637c2ee.png)

### Version

2022.716.1-lazer

### Logs

N/A

**Comment by Dragon77mathbye** [comment]
Cinema also doesn't show it is incompatible with repel

![image](https://user-images.githubusercontent.com/74103504/179422170-dc741262-770e-4566-a93f-d0a13a980dea.png)

![image](https://user-images.githubusercontent.com/74103504/179422160-544bc2e1-704f-452a-be5b-4467ea3685cd.png)
