### ISSUE TITLE
No hit register (android)

### ISSUE THREAD

**Issue by W4nds** [ppy/osu#19224]
### Type

Game behaviour

### Bug description

So, I decided to play with only SS mode just for fun. Everything is normal until my 3 try the game never registered any "clicks" anymore. I disabled the mod but the bug continues, not only in the beatmap I was current playing on but all other too. I can't play the game anymore because there is no way to hit. My phone hat its own digital pen and I used that. But  none of then is working(finger or pen) now.

Obs.: I updated the game and the bug continues

OS: Android 12

Device: Samsung Galaxy Note 10 lite

### Version

2022.709.1

### Logs

[database.log](https://github.com/ppy/osu/files/9136573/database.log)
[network.log](https://github.com/ppy/osu/files/9136574/network.log)
[performance.log](https://github.com/ppy/osu/files/9136575/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9136577/runtime.log)

**Comment by peppy** [comment]
Could you explain what "only SS mode" is?

**Comment by W4nds** [comment]
I reinstalando the game and now tanto works

**Comment by W4nds** [comment]
> Could you explain what "only SS mode" is?

Hi the Perfect mode
