### ISSUE TITLE
Osu not detecting tablet but OpenTabletDriver does.

### ISSUE THREAD

**Issue by IgnisFlamme** [ppy/osu#19231]
### Type

Other

### Bug description

In Settings > Input > Tablet it says No Tablet Detected despite Open Tablet Driver detecting my tablet and working properly.
Note: I had to add a custom tablet configuration to /usr/share/OpenTabletDriver/Configurations for it to detect my tablet. Perhaps this is why osu isn't detecting it?

If this is the cause, how do I go about fixing it?

### Version

20220424 - latest

### Logs

[runtime.log](https://github.com/ppy/osu/files/9139896/runtime.log)

**Comment by peppy** [comment]
I doubt we can support custom configurations like that. Is there a reason you can't have your tablet supported directly by OTD?

**Comment by Susko3** [comment]
> If this is the cause, how do I go about fixing it?

You can get your configuration merged upstream by following their guide at https://github.com/OpenTabletDriver/OpenTabletDriver#supporting-a-new-tablet.

Once your configuration is merged, osu! will pick up support when a new OpenTabletDriver release is available.

**Comment by jamesbt365** [comment]
OpenTabletDriver/OpenTabletDriver/pull/2315 added this configuration, wait until next release if you want it in lazer.
