### ISSUE TITLE
inconsistency and incomplete selection of object in editor while quickly dragging through timeline

### ISSUE THREAD

**Issue by Frfri1** [ppy/osu#19255]
### Type

Game behaviour

### Bug description

When I tried to select all objects in my beatmap by dragging in the timeline fastly, I noticed that not all objects in the map were getting picked. It seems very inconstitent, and sometimes I get most of the objects, and other times, I barely get a third of the total object count.
It only does that in the backwards way, and doesn't happen when going slowly. zooming in or out doesn't change that from happening.
Here's a quick video showing this. (the map has 167 total objects)

### Screenshots or videos

https://user-images.githubusercontent.com/104506631/180071083-51133a5a-b211-42b6-8919-7788a088bdf0.mp4

### Version

2022.719.0-lazer

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/9154135/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9154136/network.log)
[performance.log](https://github.com/ppy/osu/files/9154137/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9154138/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9154139/updater.log)
[database.log](https://github.com/ppy/osu/files/9154140/database.log)

**Comment by bdach** [comment]
#16410
