### ISSUE TITLE
Failed scores display incorrect total score and max combo

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#19259]
### Discussed in https://github.com/ppy/osu/discussions/19251

<div type='discussions-op-text'>

<sup>Originally posted by **mk56-spn** July 20, 2022</sup>
as stated in the title currently F scores calculate their 1 mill score seemingly based on the objects played uptil failure, which  gives nonsense scores like this 
![osu_2022-07-20_18-52-26](https://user-images.githubusercontent.com/74463310/180040786-6d59549c-89d8-44f0-8740-46dbe00bad3e.jpg)
combo is also broken for the same reasons</div>

**Comment by smoogipoo** [comment]
Yeah, I didn't envision this scenario. We can't just the hit statistics to compute scores like this - it necessitates running through the entire `ScoreProcessor`.

**Comment by frenzibyte** [comment]
I don't quite follow, the total score should already be computed using a `ScoreProcessor`? The issue is that the current statistics aren't filled up to the beatmap's end, causing the maximum scoring values extracted in `ScoreProcessor` to be incorrect.

**Comment by smoogipoo** [comment]
`ScoreProcessor.ComputeFinalScore()` uses the hit statistics. The `ScoreProcessor` is actually only used to access that function, but a beatmap isn't applied via `ApplyBeatmap` otherwise.

Hence why I said "running through the _entire_ `ScoreProcessor`".
