### ISSUE TITLE
User status indicator icon does not update when not in main menu

### ISSUE THREAD

**Issue by 0x84f** [ppy/osu#19283]
### Type

Cosmetic

### Bug description

If you update your status (online/DND/offline) while you are in any screen except the main menu, the visual indicator does not update.
My assumption is that it should be coloured red if I am set to DND?

### Screenshots or videos

https://user-images.githubusercontent.com/24534022/180278615-752668d6-a3ab-4cb2-9b6c-90c4bda3556a.mp4

### Version

2022.719.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9161579/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9161581/updater.log)
[database.log](https://github.com/ppy/osu/files/9161582/database.log)
[network.log](https://github.com/ppy/osu/files/9161583/network.log)
[performance.log](https://github.com/ppy/osu/files/9161584/performance.log)

**Comment by frenzibyte** [comment]
Before that even gets attempted, wait until the feature actually gets supported (https://github.com/ppy/osu/issues/12635)
