### ISSUE TITLE
Inconsistency of "Rotate cursor when dragging" setting

### ISSUE THREAD

**Issue by SneakY-NickY** [ppy/osu#19347]
### Type

Cosmetic

### Bug description

The setting "Rotate cursor when dragging" seems to work only if I click and drag at high velocity.

### Screenshots or videos

https://user-images.githubusercontent.com/92948020/180650315-f3e182b4-4ec9-49f7-9060-6b536591476a.mp4

### Version

2022.723.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/9175914/logs.zip)

**Comment by toadsworth-jr** [comment]
I can't help but think that this is an intentional effect.
But I could be wrong.

**Comment by peppy** [comment]
That is intentional
