### ISSUE TITLE
Updating beatmaps removes them from collections

### ISSUE THREAD

**Issue by camellirite** [ppy/osu#19346]
### Type

Game behaviour

### Bug description

How to replicate:
1. Include a beatmap that needs updating in a collection
2. Update the beatmap

### Screenshots or videos

https://user-images.githubusercontent.com/23125409/180634101-edb611d0-7f23-4d07-9171-94c50f1d91e3.mp4

### Version

2022.723.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/9175204/logs.zip)

**Comment by peppy** [comment]
Collections are based on hash, so this makes sense. I guess we may need special logic to handle this flow for updates.

**Comment by peppy** [comment]
Optimally, this would be fixed by first moving collections to realm to save having a second flow to manage the updates. @smoogipoo thoughts on this? Do we want to keep the current collection database model to maintain compatibility, or is that a good direction to implement immediately?

**Comment by smoogipoo** [comment]
We could always still provide the option to import/export collections, just not store them as `collections.db`. The reader/writer would be super simple, probably 1/10th the amount of lines in that class already. I do believe it's a good direction.
