### ISSUE TITLE
Multiplayer loads infinitely

### ISSUE THREAD

**Issue by TheAirBlow** [ppy/osu#19358]
### Type
Game behaviour

### Bug description
The game infinitely loads multiplayer, nothing relevant was output to the `network.log` after a few minutes of waiting. Monitored the file in live with `tail -F` (logs updated, there is some stuff) (actually still no relevant info, the error was because my wifi connection randomly getting disrupted)

#### Websocket connection test https://github.com/ppy/osu/issues/18721#issuecomment-1172137083
URL: `https://www.piesocket.com/websocket-tester`
![image](https://user-images.githubusercontent.com/68467762/180666297-46183e45-a110-44c0-839e-0bfec541ada7.png)
For some unknown reason I was often getting timeouts instead of 404s without VPN or Tor.
#### Availability test (Cause why not)
URL: `https://2ip.io/site-availability/`
![image](https://user-images.githubusercontent.com/68467762/180665940-499f0c42-42a5-4fc3-acf9-51e4fc4314c2.png)
~~According to #14336, that should not happen~~ It is normal according to https://github.com/ppy/osu/issues/18721#issuecomment-1172137083
#### Trace routing https://github.com/ppy/osu/issues/18721#issuecomment-1164931765
Used `traceroute` for this purpose.
```
traceroute to spectator.ppy.sh (167.172.8.103), 30 hops max, 60 byte packets
 1  _gateway (192.168.0.1)  2.866 ms  3.225 ms  3.914 ms
 2  100.92.160.1 (100.92.160.1)  15.662 ms  15.978 ms  16.323 ms
 3  10.1.132.2 (10.1.132.2)  16.911 ms  17.287 ms  17.681 ms
 4  10.1.132.17 (10.1.132.17)  18.416 ms  18.635 ms  18.992 ms
 5  10.1.132.57 (10.1.132.57)  21.354 ms  21.687 ms  22.015 ms
 6  10.0.19.153 (10.0.19.153)  19.708 ms  17.437 ms  17.475 ms
 7  79.140.16.179 (79.140.16.179)  17.294 ms 79.140.16.195 (79.140.16.195)  7.469 ms 79.140.16.179 (79.140.16.179)  12.148 ms
 8  79.140.16.193 (79.140.16.193)  12.966 ms  14.235 ms  14.192 ms
 9  10.2.168.1 (10.2.168.1)  15.518 ms  16.085 ms  16.963 ms
10  10.1.245.8 (10.1.245.8)  14.148 ms  14.444 ms  14.816 ms
11  10.1.245.130 (10.1.245.130)  16.358 ms  17.318 ms  17.723 ms
12  212.46.219.109 (212.46.219.109)  18.555 ms  18.650 ms  6.648 ms
13  * * *
14  * * *
15  ae1.3505.edge9.SanJose1.level3.net (4.69.219.61)  289.538 ms  289.109 ms  289.009 ms
16  DIGITAL-OCE.edge9.SanJose1.Level3.net (4.71.117.218)  289.340 ms * 4.7.18.10 (4.7.18.10)  289.814 ms
```

### ~~Useless~~ extra information
I use `osu-lazer-bin` from AUR, linux kernel version `5.18.6-arch1-1`.
My provider is [OJSC Ufanet](https://2ip.io/isp/OJSC+Ufanet/), sometimes I can visit some blocked websites.

### Screenshots or videos
![image](https://user-images.githubusercontent.com/68467762/180665521-d4c02add-309a-413e-a0ad-0c06e04c9d2d.png)

### Version
2022.723.0-lazer

### Logs
[database.log](https://github.com/ppy/osu/files/9176714/database.log)
[network.log](https://github.com/ppy/osu/files/9176715/network.log)
[performance.log](https://github.com/ppy/osu/files/9176716/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9176717/runtime.log)

**Comment by TheAirBlow** [comment]
~~Maybe something would've been shown in the logs if I waited longer, idk...~~
![image](https://user-images.githubusercontent.com/68467762/180665940-499f0c42-42a5-4fc3-acf9-51e4fc4314c2.png)
`https://2ip.io/site-availability/` tells me that it always 404's in multiple locations.
According to #14336, that should not happen. Reopening.

**Comment by TheAirBlow** [comment]
![image](https://user-images.githubusercontent.com/68467762/180666003-efa27867-3ec0-4fcc-9212-fa270cc17429.png)
Updated the log files in the issue

**Comment by TheAirBlow** [comment]
Tried `https://www.piesocket.com/websocket-tester` tested, here's the result:
![image](https://user-images.githubusercontent.com/68467762/180666143-8e6a2d36-6840-4c78-b18e-5871aa0c0fa1.png)

**Comment by TheAirBlow** [comment]
I use `osu-lazer-bin` from AUR, linux kernel version `5.18.6-arch1-1`

**Comment by frenzibyte** [comment]
Please include all your findings in the main issue thread (#18721), there's absolutely no need to open another one. It only makes it hard for us to keep track of issues properly.
