### ISSUE TITLE
Scores are sometimes displayed as 0

### ISSUE THREAD

**Issue by isuewo** [ppy/osu#19356]
### Type

Other

### Bug description

This is the second time I've encountered this bug and I honestly don't know how to consistently reproduce it, but sometimes it just happens

### Screenshots or videos

![image](https://user-images.githubusercontent.com/53264315/180664121-d611bf96-9d36-4067-ae81-685f1e338a3d.png)

I don't know why the video is corrupted, but downloading and then opening it should work:

https://user-images.githubusercontent.com/53264315/180664680-200003dc-5a17-46d3-ab73-03ea952a19d0.mp4

### Version

2022.723.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9176627/database.log)
[performance.log](https://github.com/ppy/osu/files/9176628/performance.log)
[network.log](https://github.com/ppy/osu/files/9176629/network.log)
[runtime.log](https://github.com/ppy/osu/files/9176630/runtime.log)

**Comment by smoogipoo** [comment]
I thought there was another similar issue duplicating this (_not_ https://github.com/ppy/osu/issues/18824).

The working theory is that difficulty calculation is being cancelled, which caches null values to the cache. Still investigating...

**Comment by peppy** [comment]
This will also be resolved with the direction we're taking (adding extra statistical data as per #19380 to avoid requiring beatmap difficulty calculation for score computation).

**Comment by peppy** [comment]
Will track via https://github.com/ppy/osu/issues/19519.
