### ISSUE TITLE
mania 8K+ displays the left most column hold notes wrong

### ISSUE THREAD

**Issue by Ludio235** [ppy/osu#19360]
### Type

Cosmetic

### Bug description

Mania mode displays a regular note at the end of every hold note in the left most column. The note is purely graphical and does not affect the score or handling of input in any way. This applies to mania mode with 8, 9 and 10 keys only.

### Screenshots or videos

https://user-images.githubusercontent.com/94078268/180666969-8f511d3f-fd05-4aec-bd7a-288fa8a74b47.mp4

### Version

2022.723.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9176778/database.log)
[network.log](https://github.com/ppy/osu/files/9176779/network.log)
[performance.log](https://github.com/ppy/osu/files/9176780/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9176781/runtime.log)

**Comment by frenzibyte** [comment]
Please attach your skin.

**Comment by Ludio235** [comment]
Okay, I'm an idiot - tested on stable and it is indeed a problem with my skin... No idea how to fix it. I wanted to attach it anyway if someone would want to look into it, but the file size limit is 25 MB. -_-

**Comment by peppy** [comment]
Please attach your skin.ini or upload it elsewhere

**Comment by Ludio235** [comment]
Here:
[skin.ini.txt](https://github.com/ppy/osu/files/9194905/skin.ini.txt)

**Comment by enoslayd** [comment]
replace 
> NoteImage0T: mania-note2H 

with
> NoteImage0T: mania-note2T 

on your skin.ini in section
>  [Mania]
> Keys: 8
