### ISSUE TITLE
Support deleting beatmap difficulties within editor

### ISSUE THREAD

**Issue by Ludio235** [ppy/osu#19361]
### Type

Other

### Bug description

There is no way to delete a beatmap difficulty in the editor screen.

### Screenshots or videos

![no delete difficulty option](https://user-images.githubusercontent.com/94078268/180667237-5830dfa9-aa76-4eed-866e-19404477ce2b.png)

### Version

2022.723.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9176787/database.log)
[network.log](https://github.com/ppy/osu/files/9176788/network.log)
[performance.log](https://github.com/ppy/osu/files/9176789/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9176790/runtime.log)

**Comment by bdach** [comment]
Resolved with #19413
