### ISSUE TITLE
Performance statistic may not match value shown on breakdown

### ISSUE THREAD

**Issue by Dragon77mathbye** [ppy/osu#19386]
### Type

Cosmetic

### Bug description

The performance points display on the quick score page does not match the value when viewing extra details about the play.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/74103504/180907412-c00c4a1c-6511-4cd9-8e7c-7916dec60ded.png)

### Version

2022.723.0

### Logs

[performance.log](https://github.com/ppy/osu/files/9186003/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9186004/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9186005/updater.log)
[database.log](https://github.com/ppy/osu/files/9186006/database.log)
[network.log](https://github.com/ppy/osu/files/9186007/network.log)

**Comment by peppy** [comment]
If that is for an online score, one is probably being calculated locally while the other isn't. Lazer uses a newer version of diffcalc which would cause a potential difference.

**Comment by Dragon77mathbye** [comment]
it is for an online score

**Comment by arielcostas** [comment]
Something similar happens to me on `2023.326.1-lazer`, however, in my case they are the same in the performance breakdown. I was tempted to open a new issue, but I'm guessing it's the same bug.

The following is my in-game performance breakdown, even after restarting the game.

![image](https://user-images.githubusercontent.com/94913521/228852670-873345e0-f576-4d3f-9966-c969b7505413.png)

The following is my in-game profile, under the "History" section. Which is the same as the score on the web: [2260350103](https://lazer.ppy.sh/scores/2260350103).

![image](https://user-images.githubusercontent.com/94913521/228853025-3eebfbe3-87f4-4e78-b13e-acc5bc0e25a0.png)
