### ISSUE TITLE
New FPS display sometimes just disappears

### ISSUE THREAD

**Issue by isuewo** [ppy/osu#19384]
### Type

Cosmetic

### Bug description

As you can see in the video, sometimes the new FPS display just disappears

### Screenshots or videos

https://user-images.githubusercontent.com/53264315/180863291-0dc3f14a-3ff9-4b0a-979f-181115f713f6.mp4

### Version

2022.723.0

### Logs

[database.log](https://github.com/ppy/osu/files/9184403/database.log)
[performance.log](https://github.com/ppy/osu/files/9184404/performance.log)
[network.log](https://github.com/ppy/osu/files/9184405/network.log)
[runtime.log](https://github.com/ppy/osu/files/9184406/runtime.log)

**Comment by frenzibyte** [comment]
That's intentional, when the FPS disappears it means that the game is operating smoothly, and it's done as such to not interrupt the user while doing something else.

For the record, this also matches osu!(stable).
