### ISSUE TITLE
Top local score is shown duplicated on results screen

### ISSUE THREAD

**Issue by Sublimelime** [ppy/osu#19406]
### Type

Cosmetic

### Bug description

After playing a beatmap where you improve your top local score, your top local score will be shown twice in the horizontal list of scores shown after playing a beatmap. 

As far as I can tell, this is only happening to scores made with this/a recent build - old top local scores don't seem to be duplicated.

 

### Screenshots or videos

![osu_2022-07-26_10-06-13](https://user-images.githubusercontent.com/10090332/181041982-23aff173-1042-471a-a06d-ff04b31f5b6b.jpg)

### Version

2022.723.0

### Logs

[database.log](https://github.com/ppy/osu/files/9190966/database.log)
[network.log](https://github.com/ppy/osu/files/9190967/network.log)
[performance.log](https://github.com/ppy/osu/files/9190968/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9190969/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9190971/updater.log)

**Comment by frenzibyte** [comment]
Upon looking at the results screen code, it should be guarding against displaying two scores with matching online IDs:
https://github.com/ppy/osu/blob/f956955d4d66a6955cafdf066d1c4034b46c64ec/osu.Game/Screens/Ranking/SoloResultsScreen.cs#L35-L37

(notice `r.Scores.Where(s.OnlineID != Score.OnlineID)`).

Thought `Score.OnlineID` wasn't being populated on time, so I fired up a client on dev server and checked on the values after submitting score, but it's getting populated correctly from [`SubmittingPlayer.submitScore`](https://github.com/ppy/osu/blob/937692604edbc919e6a55d6499ca6a0e72bc69c5/osu.Game/Screens/Play/SubmittingPlayer.cs#L182) which `Player` waits for before pushing results screen.

I'm not sure anymore on what could be the issue, and I can't debug this myself as dev server doesn't support real-time updating leaderboards like prod server does right now.

**Comment by peppy** [comment]
Have you checked that the returned `OnlineID` is also populated correctly? The only recent thing that changed is the model mapping, to my recollection..

**Comment by frenzibyte** [comment]
The `OnlineID` returned from the score submission request? it looks to return a correct ID:
<img width="585" alt="CleanShot 2022-07-27 at 11 45 18@2x" src="https://user-images.githubusercontent.com/22781491/181203632-dee28387-8cad-4c86-9cb8-fa7007fe3633.png">

Otherwise not sure what other place that returns `OnlineID` you're referring to.

**Comment by peppy** [comment]
> I'm not sure anymore on what could be the issue, and I can't debug this myself as dev server doesn't support real-time updating leaderboards like prod server does right now.

This should be coming online within a day or two (cc/ @ThePooN) if it helps with testing.

**Comment by frenzibyte** [comment]
I've tried reproducing this on production server itself to no avail, unassigning myself for now.

**Comment by smoogipoo** [comment]
Dropping out of P1 since we can't repro.

**Comment by Sublimelime** [comment]
Closing as I can't repro this now either. Seems to be fixed collaterally by some other change.

**Comment by nutel65** [comment]
![image](https://user-images.githubusercontent.com/44318430/213823216-d4ef39fe-3d53-4697-bb87-8ded477cfc00.png)
![image](https://user-images.githubusercontent.com/44318430/213823234-740a5f60-8f33-4af0-af71-10e15bedd9fc.png)
