### ISSUE TITLE
Quit confirmation at menu screen

### ISSUE THREAD

**Issue by thomastanck** [ppy/osu#1940]
Right now, pressing Esc at the menu screen causes lazer to quit immediately instead of showing a quit confirmation overlay.

Are there designs from @arflyte ? I assume it should look similar to the pause and fail overlays?

Pause overlay:
![maxresdefault](https://user-images.githubusercontent.com/829070/35195370-7cc635a6-fefd-11e7-8e46-7da5c9a94ae7.jpg)

**Comment by peppy** [comment]
I believe we are planning on making "hold to action" for things like this, rather than adding confirmations. That still requires some degree of design-work, but a basic implementation should already be possible.

**Comment by Express76** [comment]
Hows these concepts on how this could work/ look if it was a pop up menu or drop down and not a hold to exit.

Drop down:
![drop down](https://user-images.githubusercontent.com/36247859/37944694-62173072-31c8-11e8-9692-c30c97200a02.jpg)

 
Pop up:
![pop up](https://user-images.githubusercontent.com/36247859/37945244-f84b4144-31ca-11e8-88ee-fe6cd51e893a.jpg)

If hold to exit was to be used the exit button filling up to the top like a cup of water would work imo.
