### ISSUE TITLE
Newly added kiai sections don't appear in the bottom timeline

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#19412]
Fairly certain there are more issues with this timeline around undo/redo, probably related.

### Discussed in https://github.com/ppy/osu/discussions/19404

<div type='discussions-op-text'>

<sup>Originally posted by **cdwcgt** July 26, 2022</sup>
kiai section have two timing line, one of its start and another of its end
when set a timing line to end kiai sction, time bar don't refresh like 
![image](https://user-images.githubusercontent.com/34775378/180997490-38e9947d-5acf-46ee-82c4-a036ee83b6c1.png)
I think it's a problem with the refresh timing of the time bar, it should refresh all kiai section after the second line(or any) is placed

https://user-images.githubusercontent.com/34775378/180997912-a12053f7-4254-4ee7-bb8b-6d33ba3d5c32.mp4

version: 2022.723.0</div>

**Comment by cdwcgt** [comment]
https://user-images.githubusercontent.com/34775378/190179561-c11d5c82-d870-420b-ba89-bdf42dc670e4.mp4

![image](https://user-images.githubusercontent.com/34775378/190179622-9c396764-5a0f-4587-9531-c0c9269c592e.png)
this doesn't seem to be fully resolved

**Comment by Joehuu** [comment]
The bug above was probably the same as https://github.com/ppy/osu/issues/20122, which was fixed in https://github.com/ppy/osu/pull/29667.
