### ISSUE TITLE
Massive stutter in lazer, if NVIDIA Threaded Optimization is turned on

### ISSUE THREAD

**Issue by Jungspylie** [ppy/osu#19421]
### Type

Performance

### Bug description

If in the NVIDIA Control Panel the option "Threaded optimization" is enabled, it results in the game lagging /stuttering really bad.
For a temporary fix and clear visuals with a video as proof of this happening and the setting being the cause, I'll link the reddit post I made: https://www.reddit.com/r/osugame/comments/w8n85v/osulazer_lag_spikes_fixed/
Also, I'm completely new to GitHub, so I'm sorry in advance if I butchered something.

### Version

2022.723.0-lazer

### Logs

[performance-audio.log](https://github.com/ppy/osu/files/9201283/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9201284/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9201285/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9201286/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9201287/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9201289/updater.log)
[database.log](https://github.com/ppy/osu/files/9201290/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9201291/legacy-ipc.log)

**Comment by peppy** [comment]
We already force this off in stable, and may want to do the same here. I believe this was previously discussed but can't find the relevant issue.

**Comment by n-buna404** [comment]
similar performance issue was found in Linux Mint 21 laptop with nvidia discrete GPU
However, I could not find the switch to turn it off in Linus Mint.
Would prefer if the dev turn it of by default for Nvdia GPU user

**Comment by smoogipoo** [comment]
@n-buna404 From what I'm reading, it seems like you should be able to set the environment variable `__GL_THREADED_OPTIMIZATIONS=1`. It may or may not work for you depending on the driver/etc.

**Comment by n-buna404** [comment]
> @n-buna404 From what I'm reading, it seems like you should be able to set the environment variable `__GL_THREADED_OPTIMIZATIONS=1`. It may or may not work for you depending on the driver/etc.

As far as I knows from googling `__GL_THREADED_OPTIMIZATIONS=1` is to enable threaded optimization that caused the stutter
I tried `__GL_THREADED_OPTIMIZATIONS=0` to disable it but it does not seems to work.
Would prefer if osu lazer disable this by default on all nvidia gpu system or added a toggle in settings for this

**Comment by smoogipoo** [comment]
Yeah, `0` would make sense. I'm not sure it's possible for us to disable it because NVAPI doesn't exist for Linux. If you don't have a driver control interface / that interface doesn't allow you to disable threaded optimisations, then it's likely nothing can be done from our side.

**Comment by n-buna404** [comment]
> Yeah, `0` would make sense. I'm not sure it's possible for us to disable it because NVAPI doesn't exist for Linux. If you don't have a driver control interface / that interface doesn't allow you to disable threaded optimisations, then it's likely nothing can be done from our side.

Guess I had to go back to the old Osu stable+ wine which disabled this by default.

**Comment by smoogipoo** [comment]
How are you ensuring it disabled it?

**Comment by n-buna404** [comment]
> We already force this off in stable, and may want to do the same here. I believe this was previously discussed but can't find the relevant issue.

It was mentioned the comment above.

**Comment by smoogipoo** [comment]
That doesn't mean it works under Wine, and I've never tested it under Wine - only that the game won't fatally crash if NVAPI can't be loaded for any reason.

**Comment by peppy** [comment]
Keep in mind the user here is only *guessing* that this is the issue. It may just be GC or something else as they are on linux.

My advice specifically for the threaded optimisations (*assuming that is the issue*) would be to wait until we get the new render pipelines online as it will almost definitely be fixed on Direct X / vulkan.

**Comment by smoogipoo** [comment]
Also, doing some further reading on https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/openglenvvariables.html, they say setting it to `0` should work. So I'm confused at how you're testing this? If it's just that you're seeing stutters, it could be for any reason and not necessarily threaded optimisations.

**Comment by n-buna404** [comment]
Okay, I am not a developer and merely juggling through this as casual user. Apologies if I had offended u in anyway
At first I would like open a separate issue which is due to the observation below:
1. open osu.appimage ( fps steady at 120fps as I had set to 2x renderer)
2. select solo playing and go to song selection ( the stuttering started and it ranges from 80-90 fps some worse scenario it causes song playing at background to stutter)
3. start playing a beatmap ( the fps steadily at around 120fps)

So I infers this would be something related to song selection menu. But before opening a new issue I found this old one and the video from the reddit discussion looks similar to my experience. Furthermore, I am also using nvidia discrete GPU
so I tried open terminal in the directory I saved the appimage  and run the command below
`__GL_THREADED_OPTIMIZATIONS=0 ./osu.AppImage`
which gives:
`touch: cannot touch '/home/user1/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory`
and osu open with similar performance issue. 

So u may be correct one that it could be for any reason and not necessarily threaded optimizations.

**Comment by natan5388** [comment]
> We already force this off in stable, and may want to do the same here. I believe this was previously discussed but can't find the relevant issue.

Actually i haven't seen any problem in using it on stable RN. because fps seems to be fixed on 2x render when it was off [75hz / 150fps] -> 600fps. 
1660 Super + Ryzen 5 3500 [6/6]

**Comment by peppy** [comment]
Please wait for new renderer.

**Comment by peppy** [comment]
Closing as should-be-resolved.
