### ISSUE TITLE
Wrong taiko hitsound samples loaded when using legacy skins

### ISSUE THREAD

**Issue by its5Q** [ppy/osu#19436]
### Type

Game behaviour

### Bug description

When using legacy skins in osu!taiko, if the skin doesn't have taiko hitsounds, instead of defaulting to classic taiko hitsounds, it uses skin's osu!std samples, so rim hits have no sound, and centre hits have circle hit samples from the current skin.

### Screenshots or videos

https://user-images.githubusercontent.com/12975646/181447319-3d37d92d-2f18-4601-bce7-d362fcbd8ae5.mp4

### Version

2022.723.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/9206644/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9206646/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9206647/updater.log)
[database.log](https://github.com/ppy/osu/files/9206649/database.log)
[network.log](https://github.com/ppy/osu/files/9206650/network.log)

**Comment by frenzibyte** [comment]
That matches with what the code currently does:
https://github.com/ppy/osu/blob/f8830c6850128456266c82de83273204f8b74ac0/osu.Game.Rulesets.Taiko/Skinning/Legacy/TaikoLegacySkinTransformer.cs#L170-L180

If the classic legacy skin provides samples for all taiko hit sounds then we probably don't even want to fall back to the regular hit sounds names.
