### ISSUE TITLE
Map fails to update, instead it copies itself endlessly

### ISSUE THREAD

**Issue by MkGuh** [ppy/osu#19448]
### Type

Game behaviour

### Bug description

clicking on ''update'' atnewly downloaded map does not update it, but creates a copy of itself instead that's also ''not updated''

### Screenshots or videos

![osu_2022-07-28_22-07-52](https://user-images.githubusercontent.com/45127556/181662116-946a1c9a-3e22-42f5-aaed-848dff0b3de7.jpg)

### Version

2022.723.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9215200/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9215201/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9215202/network.log)
[performance.log](https://github.com/ppy/osu/files/9215203/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9215204/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9215205/updater.log)

**Comment by peppy** [comment]
Will be fixed in the next release. Multiple reports already exist for this and have been resolved.
