### ISSUE TITLE
"update beatmap" feature does not work on maps that cannot be downloaded

### ISSUE THREAD

**Issue by Proxima36** [ppy/osu#19475]
### Type

Game behaviour

### Bug description

"update beatmap" feature does not work on maps that cannot be downloaded due to DMCA. Updating such maps causes an error.
[Beatmap example](https://osu.ppy.sh/beatmapsets/97932#osu/262062)

### Screenshots or videos

Lazer:
![2022-07-30_17-25-27](https://user-images.githubusercontent.com/65703743/181918861-d985a526-8031-48c0-8862-a4897e69a0d9.gif)
Stable:
![2022-07-30_17-27-52](https://user-images.githubusercontent.com/65703743/181918875-2fc2a045-9b42-4855-b885-b4e3de721dc6.gif)

### Version

2022.723.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/9226625/runtime.log)
[network.log](https://github.com/ppy/osu/files/9226626/network.log)

**Comment by peppy** [comment]
This is correct behaviour. It will only apply to a few legacy cases where the full beatmap is not available, rather than only the relevant files.

**Comment by LittleEndu** [comment]
Is it possible to not show the update button for such beatmaps?

**Comment by peppy** [comment]
Dunno, maybe it can be hidden after the first failure. Not important priority wise.
