### ISSUE TITLE
Adding additions to the sliders in the compose menu doesn't change the sound

### ISSUE THREAD

**Issue by NagBoard** [ppy/osu#19470]
### Type

Game behaviour

### Bug description

Been trying to search for a similar issue reported already, but I haven't found one. Sorry for cloning other report, if anything.

Anyways, the issue is pretty much self explanatory, and additions doesn't quite work not only with whistles, but with claps and finishes too. The bug takes place only when applying additions to the sliders, circles work just fine. 

### Screenshots or videos

Video demo: https://youtu.be/Dwu2Pti7MNk.

### Version

2022.723.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/9226437/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9226438/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9226439/updater.log)
[database.log](https://github.com/ppy/osu/files/9226440/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9226441/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9226442/network.log)

**Comment by naipofo** [comment]
I tried doing exactly what you are doing in the video and everything works fine. Can you please check if it works with the built-in osu!classic skin?

**Comment by NagBoard** [comment]
> I tried doing exactly what you are doing in the video and everything works fine. Can you please check if it works with the built-in osu!classic skin?

Oh, so that's was the case. Yep, everything works fine with standard skin, thanks for clarifying that. Not sure if it is a right place to ask, but any ideas on how to fix this? I guess something is messed up with mp3 files, but whatever. 
Thanks for the answer anyways!

**Comment by naipofo** [comment]
`normal-hitwhistle.wav` and `normal-sliderwhistle.wav` are separate files for both circles and sliders. I'm guessing the second one is missing.
