### ISSUE TITLE
Volume doesn't save on note overlapping with a hold note

### ISSUE THREAD

**Issue by Redd56** [ppy/osu#19483]
### Type

Game behaviour

### Bug description

when in editor editing hitsounds sometimes the volume does not save
added context: before i hit save and exit set both single hits to 33% volume and the hold to 0, save and come back and it just doesnt save it
this has been happening alot in random spots on the map, some areas will save the volume and some will not

### Screenshots or videos

https://user-images.githubusercontent.com/12189828/181995119-9188b9a2-d1ac-4a6f-9cda-792a765de1c3.mp4

### Version

2022.731.1 lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9227532/database.log)
[network.log](https://github.com/ppy/osu/files/9227533/network.log)
[performance.log](https://github.com/ppy/osu/files/9227534/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9227535/runtime.log)

**Comment by Redd56** [comment]
update: video file that works on githu

https://user-images.githubusercontent.com/12189828/181995119-9188b9a2-d1ac-4a6f-9cda-792a765de1c3.mp4

**Comment by Redd56** [comment]
may be related to https://github.com/ppy/osu/issues/15618

**Comment by frenzibyte** [comment]
Different volume specifications for objects on a specific time can't work because they'll all be encoded back to the stable format (which is a control point per time). May need to indicate that somehow, potentially by only showing one bubble rather than multiple at a time. That's not quite possible with the way editor timeline is structured (where each hitobject provides its own volume bubble).

**Comment by peppy** [comment]
The format should be fixed instead.

**Comment by frenzibyte** [comment]
Not sure how feasible that'll be though, unless it's fine changing the legacy beatmap encoder to include additional properties in control points? (I suppose that's the reason why we have lazer beatmaps set to v128)

**Comment by Redd56** [comment]
there has also been some wierdness ive noticed with some notes just not saving volume informantion at all, some will randomly revert to 100/0 volume. ill try to figure more out here tomorrow

**Comment by peppy** [comment]
This issue should be resolved via #23308.
