### ISSUE TITLE
Sort by Date Ranked hides supposedly ranked beatmaps

### ISSUE THREAD

**Issue by FriendsNone** [ppy/osu#19488]
### Type

Other

### Bug description

Correct me if I'm wrong. Sort by Date Ranked should sort beatmaps by when it was ranked. But in this case, it just hides all the supposedly ranked maps.

I'm not sure if this is due to most of my beatmaps are imported from stable.

### Screenshots or videos

Windows:

https://user-images.githubusercontent.com/4056272/182009795-be4f7387-adf8-43d6-8adc-9955703edbd2.mp4

Android:

https://user-images.githubusercontent.com/4056272/182010155-6fb49391-e0e3-4e30-b4a7-0e3d446906ae.mp4

### Version

2022.731.1 on Windows 11 and 2022.723.0 on Android 12

### Logs

Windows
[network.log](https://github.com/ppy/osu/files/9228036/network.log)
[performance.log](https://github.com/ppy/osu/files/9228037/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9228038/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9228039/updater.log)
[database.log](https://github.com/ppy/osu/files/9228040/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9228041/legacy-ipc.log)

Android
[runtime.log](https://github.com/ppy/osu/files/9228056/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9228057/performance.log)
[network.log](https://github.com/ppy/osu/files/9228058/network.log)
[database.log](https://github.com/ppy/osu/files/9228059/database.log)

**Comment by peppy** [comment]
Can you please attach your `client.db`

**Comment by naipofo** [comment]
[client.realm.gz](https://github.com/ppy/osu/files/9228642/client.realm.gz)
Here, I'm having the same problem. Those beatmaps where just downloaded on a new client save. Most `BeatmapSet`s don't have both `DateSubmitted` and `DateRanked`. Those are also different from my other save: _Willi wills wissen_ had both dates on my main save but when i just downloaded it, it didn't have any.

**Comment by peppy** [comment]
Have you always been logged into the game and have a network connection available?

**Comment by naipofo** [comment]
Yeah

**Comment by FriendsNone** [comment]
> Can you please attach your `client.db`

Got back from somewhere.
I'd assume you mean `client.realm`? This is from the Windows machine. I can send the one on Android if needed.
[client.zip](https://github.com/ppy/osu/files/9228654/client.zip)

If that's not it, Then I couldn't find `client.db` within the osu folder

**Comment by naipofo** [comment]
It seems like downloading qualified maps always fetches them with `DateRanked` and the few ranked maps i had working where downloaded before as qualified.

**Comment by peppy** [comment]
Currently there is no trigger causing a metadata update when a qualified beatmap becomes ranked. This will be added soon, which will resolve this issue.

**Comment by naipofo** [comment]
Well, everything else seems to be caused but the metadata not updating, like `DateRanked` being actually the qualified date despite the map being ranked already.

**Comment by FriendsNone** [comment]
Tried adding in some beatmaps through the listing in osu, through drag-and-drop, and through import from stable. They all seem to appear and sort as expected.

It's possible that the existing beatmaps didn't get updated to support the feature? I'm just guessing a possible reason.

**Comment by peppy** [comment]
All beatmaps were supposed to be updated once after the feature was brought online, but I'll confirm this by checking your databases over the coming days. There may be an oversight with the state of certain beatmaps.

**Comment by peppy** [comment]
The issue here is that the local cache actually doesn't *contain* the metadata required to populate beatmaps. So any batch imports (ie. from stable) are going to be populated with missing ranked date. Also, the background processing task is using the local cache where available, so it won't fill the data either.

I've got a working branch (https://github.com/ppy/osu/compare/master...peppy:osu:fill-missing-ranked-dates?expand=1) which will resolve this issue, but requires some extra data to be added to `online.db` to make it efficient (tracking https://github.com/ppy/osu-onlinedb-generator/issues/4).

**Comment by FriendsNone** [comment]
I might as well bump this issue since the "Date Submitted" sort as been added to 2022.902.0

I've just read (and seen) the changelog updates. I can redo the steps and send in the required files whenever I get some spare time.

**Comment by frenzibyte** [comment]
There's no need to bump this issue, it is already open and seemingly pending osu!-side changes to reprocess existing beatmaps and fill missing ranked dates.

**Comment by peppy** [comment]
As an update, the cache generator now includes this metadata, so this task can proceed.

**Comment by frenzibyte** [comment]
@peppy I believe this is still under your radar seeing that you're assigned? or was it only for the server-side changes.

**Comment by peppy** [comment]
You're welcome to take it on if you want, won't be looking at it immediately.

**Comment by Biokax** [comment]
The problem still here, i wanted to play some old maps but when i enabled the filter, all the maps that was ranked more than one year ago disapear, even if they are selected

![ranked_date_bug](https://user-images.githubusercontent.com/50368878/209963324-df6aa2e7-3602-43ba-beda-98cb89f2e247.gif)

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu/pull/22775, remaining issue is tracked in https://github.com/ppy/osu/issues/22416.
