### ISSUE TITLE
Newly imported maps are still not in the right place when the sort mode is set to "Last Played"

### ISSUE THREAD

**Issue by isuewo** [ppy/osu#19499]
### Type

Game behaviour

### Bug description

This issue is related to #19382 and was supposedly fixed by #19399.

I can confirm that the second part of said issue has been fixed, but if you import an unplayed map while the sort mode is set to "Last Played" it will still be somewhere, but not at the end where it should be. Changing the sort mode to something else and back again fixes this though.

### Screenshots or videos

Once again, I have no idea why GitHub thinks this file is corrupted, but downloading and playing it locally should work just fine.

https://user-images.githubusercontent.com/53264315/182027173-53c95d7d-5f06-4700-92d3-f79853203d54.mp4

### Version

2022.731.1

### Logs

[performance.log](https://github.com/ppy/osu/files/9228853/performance.log)
[database.log](https://github.com/ppy/osu/files/9228854/database.log)
[network.log](https://github.com/ppy/osu/files/9228855/network.log)
[runtime.log](https://github.com/ppy/osu/files/9228856/runtime.log)

**Comment by peppy** [comment]
I'm guessing what you're looking for is that maps are sorted in "import order" when never played?

**Comment by peppy** [comment]
Currently order is undefined for all unplayed beatmaps. Some kind of stable ordering would need to be added.

**Comment by frenzibyte** [comment]
This looks to be specific to newly imported maps, as closing the song select and opening it again or changing sort mode fixes it. Will give this a short bit of investigation.
