### ISSUE TITLE
Improve messaging when download fails due to error

### ISSUE THREAD

**Issue by peppy** [ppy/osu#19518]
### Discussed in https://github.com/ppy/osu/discussions/19309

<div type='discussions-op-text'>

<sup>Originally posted by **iSimpFor** July 23, 2022</sup>
if you download/update enough beatmaps to hit the limit, it just tells you that the download failed as if it was a error

instead, the player should be told that they hit the download limit and to do something else in the meantime</div>

**Comment by peterpan06** [comment]
invidninvfjivndibvhrbfkbidbdihddjidhgeihfihrih hehfinrifhrighirjgirjitfjje hfihrif brkeufuhfuhunfinfi hfirhfirhhvifhnfidni nvindinvndnnfrgdinviexnfueujfurndurnuendugmvienxufmvifnuxnfuvjsncudhfuncudhfunfurnunrufbrunfurnfn grhehdydhejkalwmdkdogkxurk,j.jfididkdjdkcjrhfjejsj!d.dudkeidbixjdjfhfhvhvhchvnninckjginuebninuenutniwnfuxenvurnuxdnnufnrchfdfhdhcrnvkdnvfjn chcdxrncdbuvfbcurgirhcirhvidncthvirhftigfiehtihdoejxorhviehifhditjf7hvurhfut uhcurndurnjenufebcubu burnduntufnrungunfurnfunuvnu nuthfuntufntuf
