### ISSUE TITLE
Slider Repeats not fading correctly in osu!

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#1951]
While they don't appear outside of the slider anymore they now instead move with the beginning / end of it.

Video: https://streamable.com/g15h4

**Comment by peppy** [comment]
This is intended behaviour (see ppy/osu#1934).

**Comment by peppy** [comment]
(The only issue in this video is that they aren't being faded correctly as part of hidden)

**Comment by Aergwyn** [comment]
Oh. I'll change the title then.
