### ISSUE TITLE
Bug Pen Tablet Cursor when using 2 driver tablet at same time

### ISSUE THREAD

**Issue by yarndinasti** [ppy/osu#19511]
### Type

Game behaviour

### Bug description

my pen tablet behaves strangely when using the default driver (Huion Driver) and the driver in the osu game is activated at the same time

### Screenshots or videos

![osu_2022-08-01_06-58-02](https://user-images.githubusercontent.com/21020026/182050784-205d69a0-78f1-431e-9c86-5f973327f906.jpg)

![image](https://user-images.githubusercontent.com/21020026/182050792-f3b95a6b-eab2-4eb4-a398-2a9fd67c630a.png)

https://user-images.githubusercontent.com/21020026/182053157-900fad8c-28e5-438b-81cc-5a27ca6151cf.mp4

### Version

2022.731.1-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/9229963/network.log)
[performance.log](https://github.com/ppy/osu/files/9229964/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9229965/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9229966/updater.log)
[database.log](https://github.com/ppy/osu/files/9229967/database.log)

**Comment by smoogipoo** [comment]
Then... Disable one of them?
