### ISSUE TITLE
There are unbeatable Relax + Magnetized scores in the osu!lazer leaderboards

### ISSUE THREAD

**Issue by Paladynee** [ppy/osu#19539]
### Type

Other

### Bug description

Following the update which made relax and magnetized modes incompatible, I don't think there was a score purge consisting them. There currently are unbeatable scores in the leaderboard and it bugs me out every time I see a 13 star SS.

### Screenshots or videos

![osu_2022-08-01_23-52-10](https://user-images.githubusercontent.com/62181440/182245806-ac840733-b18a-4a51-b3cc-0b170404f8cb.png)

### Version

2022.731.1-lazer

### Logs

no logs

**Comment by peppy** [comment]
There’s a lot of processsing, purging and redistributing to be done. It will happen over time.
