### ISSUE TITLE
mods icons are floating incorrectly on player score in leaderboard

### ISSUE THREAD

**Issue by Kenshelent** [ppy/osu#19569]
### Type

Cosmetic

### Bug description

If a player has used too many mods, their icons are superimposed on other information in leaderboard

### Screenshots or videos

![image](https://user-images.githubusercontent.com/38864337/182589264-1439079f-cd12-4e11-ae6e-818ad0f131d2.png)

### Version

2022.731.1

### Logs

[performance.log](https://github.com/ppy/osu/files/9250627/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9250628/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9250629/updater.log)
[database.log](https://github.com/ppy/osu/files/9250630/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9250631/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9250632/network.log)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/7923
