### ISSUE TITLE
Unranked maps contribute to 'Maximum Combo' on profile

### ISSUE THREAD

**Issue by SimonDiamond** [ppy/osu#19576]
### Type

Game behaviour

### Bug description

While searching the osugame subreddit, I came across a post that was talking about how a user had more max combo than originally achievable using ranked maps. I originally suspected lazer and unranked maps to be a part of the bug, so I grabbed a map that had more max combo than that ranked map, played it in lazer, and, it actually added that max combo to my max combo stat on my profile. 

Reddit Post: https://www.reddit.com/r/osugame/comments/wfbc50/so_i_was_just_wandered_around_and_then_i_saw_the/

Map used: https://osu.ppy.sh/beatmapsets/1233758#osu/2567229

### Screenshots or videos

![2022_08_04_13_41_50_Window](https://user-images.githubusercontent.com/60475100/182838771-4288d9eb-88da-47d9-ad6f-fbffb587ae5c.png)

### Version

2022.731.1-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9259323/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9259324/updater.log)
[database.log](https://github.com/ppy/osu/files/9259325/database.log)
[network.log](https://github.com/ppy/osu/files/9259326/network.log)
[performance.log](https://github.com/ppy/osu/files/9259327/performance.log)

**Comment by Doksha** [comment]
should probably be retitled to something like "unranked maps contribute to 'Maximum Combo' on profile"

**Comment by SimonDiamond** [comment]
Yeah, thanks!

**Comment by peppy** [comment]
Thanks, will fix and reset the stat any users affected.
