### ISSUE TITLE
Spectating multiplayer match until finish sometimes doesn't transition to results screen

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#19593]
### Type

Game behaviour

### Bug description

As per the title, there are chances where this happens, and chances where this doesn't, and chances where the results screen is transitioned to but is actually greyed (may be a different issue).

### Screenshots or videos

https://user-images.githubusercontent.com/22781491/183147803-e31186d0-19be-40de-8625-766cba9d2819.mp4

### Version

9ac322d337e348f63d824e5995942c2ee367dc2a

### Logs

-

**Comment by peppy** [comment]
This was supposed to be fixed, but the fix didn't work and a proper fix was unfortunately forgotten about.

This needs to be hot fixed within 12 hours, so if anyone is able to look into this it would be appreciated.
