### ISSUE TITLE
osu!catch fruit catcher is offset from where it should be when importing legacy skins

### ISSUE THREAD

**Issue by Akariow** [ppy/osu#19590]
### Type

Game behaviour

### Bug description

In Osu!Catch there should be 16-17 pixels of free space at the top of the fruit-ryuuta so it lines up with where fruits are catched thats how it works in stable,
in lazer however it lines up with the top of the fruit-ryuuta element which makes it offset compared to where fruits are actually being collected, this can be adjusted by manually editing the catcher element to not have the 16-17 pixels of free space

This may or may not be related to https://github.com/ppy/osu/discussions/18870

### Screenshots or videos

![image](https://user-images.githubusercontent.com/109684187/183082208-0df0d884-8db4-4ce7-924b-6febee23ec64.png)
Comparing the same skin on the same map
the size problem has already been addressed before, but the height is also wrong

![image](https://user-images.githubusercontent.com/109684187/183080481-26e3e68b-ad4f-42ce-86cc-2c24d649f9cc.png)
Here I already adjusted the catcher element to not have 16 empty pixels at the top and it then lines up with the catchline which has been marked with red, now it does line up with where fruits are collected

### Version

2022.731.1-lazer

### Logs

[performance-audio.log](https://github.com/ppy/osu/files/9268779/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9268780/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9268781/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9268782/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9268783/updater.log)
[database.log](https://github.com/ppy/osu/files/9268784/database.log)
[network.log](https://github.com/ppy/osu/files/9268785/network.log)
[performance.log](https://github.com/ppy/osu/files/9268786/performance.log)

**Comment by Akariow** [comment]
on a side note i noticed that if i vary just the hight of the fruit catcher image it also affects how the entire catcher is scaled,
so that 348x381 was overall scaled down compared to 348x300
I didnt resize them, i just cut off some of the lower part of the catcher
![image](https://user-images.githubusercontent.com/109684187/183108796-fd9358d7-9c5e-40c5-ab12-59cf57865a93.png)

**Comment by Akariow** [comment]
After a little more investigation I noticed that it might not just be something with skin porting (or more specifically resizing of catcher) but that fundamentally the whole hitline and fruit-catcher has been offset

Here I compared both of the Default skins
![image](https://user-images.githubusercontent.com/109684187/221347009-32ff642d-3dca-4497-8427-499fbd18b89f.png)

This does affect the feel of the gameplay, or rather muscle memory as players get used to the exact height on the screen where the objects are hit, having either hitline or skin deviate from it can be off putting when switching between stable and lazer

Version: 2023.207.0

**Comment by bdach** [comment]
I think this should be sorted by #25070 now. cc @frenzibyte
