### ISSUE TITLE
"Show leaderboard during gameplay" option is affected by ALT + TAB

### ISSUE THREAD

**Issue by Naworm** [ppy/osu#19603]
### Type

Game behaviour

### Bug description

"Show leaderboard during gameplay" option seems te be affected by ALT + TAB.
Since TAB is the default bind, it result to hazardous and unwanted change of the parameter.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/48997616/183246240-8c8e4603-5fbf-4008-b506-52ae7c65fa04.png)

### Version

https://osu.ppy.sh/home/changelog/stable40/20220424

### Logs

[runtime.log](https://github.com/ppy/osu/files/9274885/runtime.log)
[session.log](https://github.com/ppy/osu/files/9274886/session.log)
[update_success.log](https://github.com/ppy/osu/files/9274887/update_success.log)
[osu!auth.log](https://github.com/ppy/osu/files/9274888/osu.auth.log)

**Comment by frenzibyte** [comment]
This repository is for osu!(lazer) issues. Open an issue against [ppy/osu-stable-issues](http://github.com/ppy/osu-stable-issues) instead.
