### ISSUE TITLE
macOS Window Scaling crashes 

### ISSUE THREAD

**Issue by tomm13** [ppy/osu#19609]
### Type

Crash to desktop

### Bug description

When osu is windowed and is scaled, the crash occurs (but not always).

This was run on an M1 MacBook Pro 2020 (16GB), on macOS Ventura (13.0).

### Screenshots or videos

https://user-images.githubusercontent.com/42684333/183261359-75d5a243-6fb6-4911-ad56-a2fdaa09d4c0.mov

### Version

2022.731.1

### Logs

[database.log](https://github.com/ppy/osu/files/9275560/database.log)
[network.log](https://github.com/ppy/osu/files/9275561/network.log)
[performance.log](https://github.com/ppy/osu/files/9275562/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9275563/runtime.log)

**Comment by peppy** [comment]
Please switch to single thread mode for now.
