### ISSUE TITLE
Multiplayer lobby shows as ended for the host upon finishing queue

### ISSUE THREAD

**Issue by NiceAesth** [ppy/osu#19602]
### Type

Cosmetic

### Bug description

The multiplayer lobby will show up as "Ended" for the host. When spectating the lobby from a second client, the status remains "Open". Leaving the lobby from the host client will show the lobby as "Open" in the listing.

### Screenshots or videos

https://user-images.githubusercontent.com/8437201/183244894-a06de6b8-823f-4340-b573-3adf5e3f07e6.mp4

### Version

2022.731.1

### Logs

[network.log](https://github.com/ppy/osu/files/9274826/network.log)
[performance.log](https://github.com/ppy/osu/files/9274827/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9274828/runtime.log)
[database.log](https://github.com/ppy/osu/files/9274829/database.log)

**Comment by peppy** [comment]
Going to mark this p0 since it's a very weird state issue we should probably figure out.
