### ISSUE TITLE
osu!mania barlines are too present (and no classic skin support yet)

### ISSUE THREAD

**Issue by peppy** [ppy/osu#19611]
### Discussed in https://github.com/ppy/osu/discussions/19608

<div type='discussions-op-text'>

<sup>Originally posted by **coiledmocha** August  7, 2022</sup>
What are these weird lines and how do I turn them off. Very distracting, and doens't seem normal. Thanks in advance.

![osumaniaweirdlines](https://user-images.githubusercontent.com/68021563/183261153-063349bf-ca91-4531-9df3-ca4da1c64776.jpg)
</div>

**Comment by bdach** [comment]
The triangles are only present if the bar line is major, so whatever this map is, it must be using a 1/4 timing or something. It's not generally this bad.

**Comment by peppy** [comment]
For sure, but even the lines are too bright. It's quite distracting when playing and we've discussed (potentially IRL conversation only) revamping them.

**Comment by Redageddon** [comment]
Imo, there should at least be a way to disable them.

**Comment by peppy** [comment]
We generally try and fix things before adding more toggles.

**Comment by Redageddon** [comment]
The existence of these in lazer is 1 of 3 only reasons why I haven't moved to lazer yet.

**Comment by abraker95** [comment]
You don't need these lines most of the time. Notes in patterns are read relative to each other and by the rate they scroll. The only case where they might help is scroll speed changes.

**Comment by peppy** [comment]
Can people reporting issues with the design in this thread please check the screenshots in #19642 and see if that feels better to you? I'm starting with the new base design, but we can potentially scale visibility back if it still feels like too much.

**Comment by abraker95** [comment]
> Can people reporting issues with the design in this thread please check the screenshots in #19642 and see if that feels better to you? I'm starting with the new base design, but we can potentially scale visibility back if it still feels like too much.

It is better but still would love the option to hide them altogether. They might look nice on paper but functionally serve as slight visual clutter.

**Comment by peppy** [comment]
You're talking specifically about the "major" bar lines right? The ones on the bar, not the beat.

Out of curiosity, would you still hide them if they only appeared at timing changes?

**Comment by abraker95** [comment]
> You're talking specifically about the "major" bar lines right? The ones on the bar, not the beat.
> 
> Out of curiosity, would you still hide them if they only appeared at timing changes?

Yes, I am talking about the "major" bar lines. If they appeared only at timing changes I see no reason to hide them for most maps. This wouldn't solve this issue for maps which attempt to time live performances however. Here is a sample map demonstrating such case: https://osu.ppy.sh/beatmapsets/1432082

**Comment by peppy** [comment]
I'm not sure if such beatmaps need to be "solved". As a player I'd want to be informed of timing changes regardless of their nature.

**Comment by Redageddon** [comment]
As a player who mainly plays only mania, any of these barlines on the screen is really distracting. Timing change reading is just considered a skillset, and I don'e need a crutch that actually distracts me when it is really not needed.

**Comment by abraker95** [comment]
> As a player I'd want to be informed of timing changes regardless of their nature.

Is this speaking from theory or experience? I assure you that this method of displaying timing changes does more to distract the player from reading patterns properly than inform the player of timing changes.

**Comment by peppy** [comment]
I’m not sure what you mean.

The idea is that timing changes should always be displayed as… timing has changed. If it’s constantly changing I want to be informed. That is the end goal. It should not be distracting but helpful. If the new design is still too distracting (I believe it is) we will continue to iterate until it is not.

**Comment by Redageddon** [comment]
Something that could be interesting to explore is an off-playarea indicator.

It would solve what makes the barline terrible: it wouldn't distract you while you are trying to focus on the notes, or be in the way, or just look terrible and not match your skin theme to start with.

An example of what you could do: arrows to the right and/or left of the play area (not in the playarea like barlines) and they could show up pointing up or down whenever there is a speed change (up being speed up, down being speed down)

**Comment by peppy** [comment]
For sure, this has been touched on at https://github.com/ppy/osu/discussions/13072 and other discussions and is something we'll investigate.

**Comment by abraker95** [comment]
> I’m not sure what you mean.
> 
> The idea is that timing changes should always be displayed as… timing has changed. If it’s constantly changing I want to be informed. That is the end goal. It should not be distracting but helpful. If the new design is still too distracting (I believe it is) we will continue to iterate until it is not.

In terms of experience, timing changes are not something that I need to be informed about to be able to hit notes on time. In stable the bar lines are so barely visible my mind filters them out while playing, and I take that as a good thing. Making them more noticeable is distracting me from reading the patterns. As you can see I am not the only one in this issue that shares this sentiment.

In terms of technicality, I can explain why. The core visual elements that players use to read note timing are:
1. The speed at which the note is scrolling 
2. The vertical spacing of the note relative to surrounding notes

If any indicators are to be added it should be in aid of those two elements. As an example of a feature that does work, [note snap color](https://github.com/ppy/osu/issues/8583) helps with the second element as it allows the player to better read the vertical spacing between notes. So the strong push for this feature really confuses me. How are timing change indicators supposed to help the player read note timings better?

**Comment by peppy** [comment]
I guess that depends on the person and is very subjective. As someone with a good knowledge of music theory, I definitely like to be informed of bpm changes as they occur, and it helps my play more enjoyable.

**Comment by Redageddon** [comment]
I made a poll on r/osugame: https://www.reddit.com/r/osugame/comments/wkor9h/osumania_barline_poll/

**Comment by peppy** [comment]
Great, but please open a new discussion thread with any further discussion. This issue has outstayed itself at this point.
