### ISSUE TITLE
Mod preset selection "click" sound still persists after deleting the presets

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#19625]
### Type

Game behaviour

### Bug description

When you create a personal mod preset, delete it and choose the mod combination for the preset you've just deleted you'll still hear the "click" selection sound from the personal mod. I've attached a video which will hopefully make it easier to understand the problem. I added multiple mod presets with the same mod combinations which should make it easier to hear the volume difference. 

### Screenshots or videos

https://user-images.githubusercontent.com/43358824/183304826-a7e75c1d-a066-4b0b-bff9-d9f558e2f9eb.mp4

### Version

commit 21f6fefcde5244cf61488c06ec0fb00dff57b5f8

### Logs

[runtime.log](https://github.com/ppy/osu/files/9277254/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9277255/updater.log)
[database.log](https://github.com/ppy/osu/files/9277256/database.log)
[network.log](https://github.com/ppy/osu/files/9277257/network.log)
[performance.log](https://github.com/ppy/osu/files/9277258/performance.log)

**Comment by peppy** [comment]
Of note, the click also plays when deleting a collection due to the full list being regenerated each time. Probably not as big of a deal if we disallow duplicates of the same mod preset (#19633) but we may want to handle the realm `ChangeSet` in a better way in the future to avoid this.

**Comment by peppy** [comment]
Yeah, I know what the root cause is. Interestingly I tried fixing using `RemoveAndDisposeImmediately` but this doesn't work for an undetermined reason (some panels gets left over, maybe parent isn't set yet?). Probably worth investigating why that extension method doesn't work, as that is its intended usage.

I didn't investigate further as you already have this assigned.

**Comment by bdach** [comment]
I just tried using `RemoveAndDisposeImmediately()` but I can't seem to get it to break? Works perfectly fine here, although the code is a bit funny (I'm removing items while walking the list, so I have a manual index iterator and a while loop.)

I guess I'll just PR what I have and we'll compare notes.
