### ISSUE TITLE
Collection import from stable doesn't work

### ISSUE THREAD

**Issue by PandaDriver156** [ppy/osu#19631]
### Type

Game behaviour

### Bug description

Clicking "Import collections from stable" in settings doesn't import collections. There is no notification about the import process happening but no error about it either.

Just an idea, could this be related to collections being recently migrated to realm?

### Screenshots or videos

https://user-images.githubusercontent.com/46034537/183310349-f1adb97b-7b00-4407-b392-0d3b5830d2a0.mp4

### Version

2022.731.1

### Logs

[network.log](https://github.com/ppy/osu/files/9277481/network.log)
[performance.log](https://github.com/ppy/osu/files/9277482/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9277483/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9277484/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9277485/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9277487/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9277488/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9277489/updater.log)
[database.log](https://github.com/ppy/osu/files/9277490/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9277491/legacy-ipc.log)

**Comment by peppy** [comment]
I did test this with the recent realm changes and everything worked correctly for my test imports. There's no messaging that it works, though.

If possible, could you please attach the collection database you're attempting to import?

**Comment by PandaDriver156** [comment]
> If possible, could you please attach the collection database you're attempting to import?

Sure, [here it is](https://drive.google.com/file/d/1PbreFJoRT3cgdFHSR9Gr_Z1hUzEXle-a/view?usp=sharing)

**Comment by peppy** [comment]
It looks to have imported correctly for me:

![JetBrains Rider 2022-08-08 at 07 22 09](https://user-images.githubusercontent.com/191335/183362332-a4b83743-274f-48e6-9777-148ca7094ed5.png)

![osu! 2022-08-08 at 07 22 42](https://user-images.githubusercontent.com/191335/183362347-4d34d692-8f2f-4132-aa31-e71fc450dc1a.png)

Can you not see this?

**Comment by PandaDriver156** [comment]
I'm not at my pc right now. Hopefully can test at the weekend, sorry about that.

**Comment by PandaDriver156** [comment]
Tested this with a clean `client.realm` and a new `collection.db` with 2 collections. First import imported everything correctly, but any beatmaps added later in stable didn't add to lazer when importing again. Notifications says it did import 2 collections, though.

[Here](https://drive.google.com/drive/folders/1wEysq8bNVNuhKNtYIIcp7mHW1ToD3DNv?usp=sharing) are both 2 files.

The 2 collections had 11 beatmaps at first import. `modified` had 16 after adding more maps to stable, but lazer still has 11.

**Comment by peppy** [comment]
Thanks a lot for the reproduction instructions. I found the issue with no trouble as a result.
