### ISSUE TITLE
Video background support not implemented

### ISSUE THREAD

**Issue by ILOVEPIE** [ppy/osu#1963]
I'm creating this issue so we can discuss the best way to do this so I can implement it.

**Comment by Aergwyn** [comment]
What do you mean? Storyboard videos or something else? Storyboards are already there and working (mostly).

**Comment by ILOVEPIE** [comment]
I mean the background videos for maps, not storyboards. The storyboards are implemented.

**Comment by smoogipoo** [comment]
We'll need to implement video decoding at some point in the future, probably accounting for whatever license FFMPEG or similar solutions have.

**Comment by ILOVEPIE** [comment]
Well, FFMPEG's licence varies based on what features it's built with. I know we can definitely test support without having to worry about licensing using VP8/VP9 and FLAC or OGG or VORBIS in webm files.

**Comment by ticotaco72** [comment]
osu-framework/#1744

**Comment by nyquillerium** [comment]
Can now be implemented, further optimizations can be done at a framework level.

**Comment by ILOVEPIE** [comment]
Sorry I've been really busy so i haven't had a chance to do any work on this. IRL stuff has been getting in the way.

**Comment by iiSaLMaN** [comment]
@ILOVEPIE I'm planning on implementing it, is that fine for you?

**Comment by iiSaLMaN** [comment]
Can be closed as already implemented by PR #5908.
