### ISSUE TITLE
Older .osu format’s sliders are not handled correctly

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#1967]
Instead of using catmull algorithm, slider is converted to use bezier algorithm. 

Here's an example from this map: https://osu.ppy.sh/b/1354806
Line 303 in .osu file: (edit: had wrong line in here, the next slider is also catmull)
``222,302,53210,6,0,C|174:293|89:342|14:324,1,200``

Looks like this in osu-stable:
![](https://i.imgur.com/RXSNWdi.png)

Looks like this in lazer:
![](https://i.imgur.com/CTxiV1b.png)
(Images are from editor but look the same ingame)

Nomega_gaming on discord was supposed to report it but I think he got lazy.

**Comment by ColdVolcano** [comment]
they are not converted, rather catmull has not been implemented yet
