### ISSUE TITLE
Images not showing in lazer client

### ISSUE THREAD

**Issue by Dia1006** [ppy/osu#19688]
### Type

Game behaviour

### Bug description

Lazer doesnt show images on the Beatmap download page when clicking on the preferred map and scrolling to the comments while somebody posted an image
osu!lazer

### Screenshots or videos

osu!lazer
![image](https://user-images.githubusercontent.com/110993151/183933609-dec52945-1750-49f4-a502-aeb9170591cf.png)

Website
![image](https://user-images.githubusercontent.com/110993151/183933965-7374201c-4ffc-4a1d-b291-8c38d869dbd5.png)

### Version

2022.810.2-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9301061/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9301062/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9301063/network.log)
[performance.log](https://github.com/ppy/osu/files/9301064/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9301065/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9301066/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9301067/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9301068/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9301069/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9301072/updater.log)

**Comment by bastianpedersen** [comment]
This is the intended behavior according to the current implementation. For reference:
````csharp
public class CommentMarkdownContainer : OsuMarkdownContainer
    {
        public override MarkdownTextFlowContainer CreateTextFlow() => new CommentMarkdownTextFlowContainer();

        protected override MarkdownHeading CreateHeading(HeadingBlock headingBlock) => new CommentMarkdownHeading(headingBlock);

        private class CommentMarkdownTextFlowContainer : OsuMarkdownTextFlowContainer
        {
            // Don't render image in comment for now
            protected override void AddImage(LinkInline linkInline) { }
        }

        private class CommentMarkdownHeading : OsuMarkdownHeading
        {
            public CommentMarkdownHeading(HeadingBlock headingBlock)
                : base(headingBlock)
            {
            }

            protected override float GetFontSizeByLevel(int level)
            {
                float defaultFontSize = base.GetFontSizeByLevel(6);

                switch (level)
                {
                    case 1:
                        return 1.2f * defaultFontSize;

                    case 2:
                        return 1.1f * defaultFontSize;

                    default:
                        return defaultFontSize;
                }
            }
        }
    }
```` 
specifically this:
````csharp
private class CommentMarkdownTextFlowContainer : OsuMarkdownTextFlowContainer
        {
            // Don't render image in comment for now
            protected override void AddImage(LinkInline linkInline) { }
        }
