### ISSUE TITLE
osu! crashing on re-login in beatmap selection

### ISSUE THREAD

**Issue by Calemy** [ppy/osu#19705]
### Type

Crash to desktop

### Bug description

Each time i was in beatmap selection performing a re-login when this occured. It doesn't happen always but frequently.

### Version

2022.810.2

### Logs

No Logs due to crash

**Comment by peppy** [comment]
In the case of a crash, logs are vital. There are logs, so please provide them next time.

Already fixed via https://github.com/ppy/osu/pull/19702.

**Comment by Calemy** [comment]
I understand, the issue is that i already re-opened osu to try to replicate the bug again and therefore lost the logs from the crash. Sorry for the inconvinience
