### ISSUE TITLE
DrawableHitObject performs miss updates on nested hitobjects twice

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#1970]
`DrawableHitObject` performs `UpdateJudgement` in `UpdateAfterChildren`. This, in-turn, prior to checking for judgements on itself, performs `UpdateJudgement` on all `NestedHitObjects`.

So in the example:
```
HitObject: A
    -> HitObject: B
        -> HitObject: C
```

C will perform `UpdateJudgement` three times, B twice, and A once, all in the same frame. Beyond potential performance issues, this may be very problematic if judgements are added that are not marked as `Final` for the current time.

**Comment by smoogipoo** [comment]
To add to this, we probably don't need to call `UpdateJudgement` on `NestedHitObjects`, since that's already done to us by the draw hierarchy. Instead we need something like `if (NestedHitObjects.Any(h => h.HasJudgementOccurredThisFrame))`...

**Comment by iiSaLMaN** [comment]
> To add to this, we probably don't need to call `UpdateJudgement` on `NestedHitObjects`, since that's already done to us by the draw hierarchy. Instead we need something like `if (NestedHitObjects.Any(h => h.HasJudgementOccurredThisFrame))`

Although doing that would not allow updating nested hit objects judgement results (`UpdateResult`) if triggered by user, is that intended?
