### ISSUE TITLE
Issues in Full Screen and Windowed mode on a legacy iGPU

### ISSUE THREAD

**Issue by cheeezie** [ppy/osu#19710]
### Type

Game behaviour

### Bug description

Hello there gents.
I recently have gotten a frustrating problem that was already a thing back then from the May releases of lazer up to now but in the latest update, it has become more frequent.
I use a pretty old system, the specs are mentioned in the bottom of the description but I'll give a quick rundown on this problem.

The issue is mostly related to the old sub par 2020 gpu drivers that Intel has released at the time and hasn't updated for the past ~2 years or so.
The graphical artifacts were a thing but it was less of an issue and could be solved by changing it to borderless then changing it back to full screen as the graphical glitches only happen in Full Screen mode, but now every time I run the game on full screen, the graphical artifacts appear, while back then it only did when I tabbed out of the game. the issue still can be solved by switching to borderless then full screen, running the game in either borderless or windowed won't cause any of seen graphical glitches. (note: the game can't run in Exclusive Fullscreen as well)

Update: At launch on Windowed mode, the graphical artifacts aren't there but tabbing out creates the same artifacts as Fullscreen. so only borderless is the only mode that isn't affected by such issue.

Important Specs:
CPU: Intel i5-4590
iGPU: Intel® HD Graphics 4600
iGPU Driver Version: 20.19.15.5126

### Screenshots or videos

![osu_2022-08-11_16-10-45](https://user-images.githubusercontent.com/102518950/184142973-464e8889-9743-49fb-b481-2c3edd3d4f74.png)
![osu_2022-08-11_16-12-09](https://user-images.githubusercontent.com/102518950/184142982-c08462ed-02ed-47b1-b2a1-0228e9069685.png)
![osu_2022-08-11_16-11-08](https://user-images.githubusercontent.com/102518950/184142984-864178d6-9e15-4c65-99e2-913b93bd0ec7.png)

### Version

osu! 2022.810.2-lazer

### Logs

[logs.zip](https://github.com/ppy/osu/files/9309196/logs.zip)

**Comment by peppy** [comment]
This isn't going to be something we can fix because as you say it's likely driver level, but once we add DirectX support you will likely see it go away. This will come in the next few months, probably.
