### ISSUE TITLE
Personal Preset with Difficulty Adjust should not automatically open Mod Customisation

### ISSUE THREAD

**Issue by peppy** [ppy/osu#19720]
### Discussed in https://github.com/ppy/osu/discussions/19719

<div type='discussions-op-text'>

<sup>Originally posted by **NotGumballer91** August 12, 2022</sup>

https://user-images.githubusercontent.com/64581009/184314391-9a92fe48-1fee-4b11-8425-2497bd3ff95e.mp4

Any mods that are customised, should not open mod customisation anyway because they are intending it keep it that way as a preset.</div>

**Comment by bdach** [comment]
Hmm. This definitely feels bad, but with the way everything is written, it's actually not very easy to detect this.

A quick hack would entail not opening the customisation panels if incoming mods that require customisation have non-default settings already. Aside from that, I can't think of anything else other than a pretty huge refactor of data flow.

**Comment by peppy** [comment]
Could also probably handle the case where more than one mod is applied in the same event, in addition to non-default value.

That should give the correct user experience for the majority of cases, I think.

**Comment by bdach** [comment]
Coming at this from another direction, people have been requesting to be able to open the customisation panel even on mods that don't automatically open it with a right click. So maybe the way forward is to invert the flow and make the mod panels themselves responsible for these behaviours.

I'll have a think and see where I end up.
