### ISSUE TITLE
Vector scale commands applied at the start of a storyboard object's lifetime

### ISSUE THREAD

**Issue by blueberrymuffin3** [ppy/osu#19732]
### Type

Cosmetic

### Bug description

When a storyboard object has both vector scale (`V`) and scale (`S`) commands osu!lazer doesn't apply them in the same way as osu! stable. stable does not "pre-apply" the vector scale command at the beginning of a storyboard objects lifetime, while lazer will "pre-apply" the vector scale command. I'm not sure if this is actually used by any real-world storyboards, so this should be pretty low priority.

### Screenshots or videos

# Example storyboard code:
```ini
[Events]
Sprite,Foreground,Centre,"square.png",320,240
 F,0,2000,3000,0,1
 S,0,4000,,5
 V,0,5000,,2,0.5
 S,0,6000,,10

 F,0,10000,,0
//  Fade in
//  Make small (squished on lazer, but not on stable)
//  Make squished
//  Make large (still squished)
//  End time
```

[Full test map download](https://github.com/ppy/osu/files/9330568/cYsmix.-.triangles.osz.zip)

# osu! stable:
![screenshot006](https://user-images.githubusercontent.com/12852902/184463763-8eea5b20-2f5e-4544-a30f-4b5a6c40c3de.png)
![screenshot007](https://user-images.githubusercontent.com/12852902/184463765-8bac8952-ca04-4f5f-9bda-ec35a0c6da3f.png)
![screenshot008](https://user-images.githubusercontent.com/12852902/184463766-d7b11fe5-d17b-4773-a78b-a6957c9837e2.png)

# osu! lazer (only two different "states" are displayed, so there's two screenshots):
![osu_2022-08-12_20-48-48](https://user-images.githubusercontent.com/12852902/184464017-37cbfb17-41c5-4872-bddb-825482110772.jpg)
![osu_2022-08-12_20-48-51](https://user-images.githubusercontent.com/12852902/184464019-e74f97a2-7e1f-418c-9099-51bb3c0f0bb4.jpg)

### Version

2022.810.2-lazer

### Logs

.

**Comment by blueberrymuffin3** [comment]
I forgot to include the sprite in the previous osz:

[cYsmix - triangles.osz.zip](https://github.com/ppy/osu/files/9330573/cYsmix.-.triangles.osz.zip)

**Comment by Coppertine** [comment]
Just as clarification, it's expected that lazer would take prioity of one of the commands.
Vector Scale and Scales are not ment to be run on the exact same sprite. Just as you won't for Move X/Y and the regular Move Command.

**Comment by blueberrymuffin3** [comment]
That makes sense, I wasn't aware that these weren't supposed to be used together.
