### ISSUE TITLE
One of my physical keyboards doesn't work on one of my Android devices

### ISSUE THREAD

**Issue by laurinneff** [ppy/osu#19762]
### Type

Game behaviour

### Bug description

On one of my Android devices, one of my keyboards doesn't want to work in osu gameplay. Other apps and text fields in osu work, and the same keyboard on other devices (tried Android and desktop Linux) or another keyboard on the same device also works.

Reading the logs it looks like the game receives the key events, but for some reason they're ignored (I'm not familiar enough with the code to know why though). Specifically, I'm referring to these lines:

```
2022-08-14 16:31:17 [verbose]: Unknown AndroidJoystickHandler.OnKeyDown event: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_A, scanCode=30, metaState=META_NUM_LOCK_ON, flags=0x8, repeatCount=0, eventTime=53291685, downTime=53291685, deviceId=13, source=0x301, displayId=-1 }
2022-08-14 16:31:18 [verbose]: Unknown AndroidJoystickHandler.OnKeyUp event: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_A, scanCode=30, metaState=META_NUM_LOCK_ON, flags=0x8, repeatCount=0, eventTime=53291724, downTime=53291685, deviceId=13, source=0x301, displayId=-1 }
```

Since it's probably relevant, my phone is a OnePlus 7T running [Pixel Experience](https://pixelexperience.org), the problematic keyboard is a [Lotus 58](https://github.com/TweetyDaBird/Lotus58) running [ZMK](https://zmk.dev), and the working one is some generic Dell model.

### Version

2022.810.2-lazer

### Logs

Logs of me launching the game and then pressing A a bunch of times on the title screen:

[runtime.log](https://github.com/ppy/osu/files/9333721/runtime.log)  
[performance.log](https://github.com/ppy/osu/files/9333722/performance.log)  
[network.log](https://github.com/ppy/osu/files/9333723/network.log)

**Comment by bdach** [comment]
The logged source of the event is `0x301` which - if I'm looking correctly [at the docs](https://developer.android.com/reference/android/view/InputDevice#SOURCE_KEYBOARD) - would be `SOURCE_DPAD | SOURCE_KEYBOARD`. It's a really strange combination, I'm not sure what this particular keyboard is doing that it presents as a dpad. It's _also_ really strange that the joystick handler is attempting to process this event - [although it seems intended](https://github.com/ppy/osu-framework/blob/859cbd420fad84af8a502fbf6776746c7b01a2a4/osu.Framework.Android/Input/AndroidJoystickHandler.cs#L35-L36)?

Also I'm very confused by [these comments](https://github.com/ppy/osu-framework/blob/859cbd420fad84af8a502fbf6776746c7b01a2a4/osu.Framework.Android/Input/AndroidJoystickHandler.cs#L76-L77) in source. They seem to infer that keyboard-only events should not be handled by the joystick handler, but the condition actually seems to be stating the opposite? @Susko3 what's going on there?

**Comment by laurinneff** [comment]
I'm not familiar with the source code of my keyboard's firmware so I can't say why it presents as dpad, but I've asked on the Discord server for the firmware so maybe someone from there will be able to answer that.

**Comment by Susko3** [comment]
> It's also really strange that the joystick handler is attempting to process this event - although it seems intended?
>
> Also I'm very confused by these comments in source. They seem to infer that keyboard-only events should not be handled by the joystick handler, but the condition actually seems to be stating the opposite?

It's intended that the joystick handler is handling `SOURCE_DPAD | SOURCE_KEYBOARD`. The joystick handler also handles `SOURCE_KEYBOARD` events, but will never log them (and that's why it returns `true` for those). The return value here is only really used for logging unhandled events.

The keyboard firmware is the problem here, but it's also Android's fault, as really similar devices report as different `SOURCE`s (and those can vary by event type for the _same_ device).

We should be able to support `SOURCE_DPAD | SOURCE_KEYBOARD` in `AndroidKeyboardHandler` but arrow keys might not work properly / will behave as Joystick dpad buttons. (Android uses the same keycodes for arrow keys and joystick buttons).

@laurinneff can you confirm that arrow keys on the offending keyboard behave as a joystick D-Pad.

**Comment by laurinneff** [comment]
osu recognizes the arrow keys as dpad buttons, but I also tried a few random keyboard/gamepad test apps from the play store and all of them correctly recognized the arrow keys as arrow keys

**Comment by V3rald** [comment]
I think i have a similar problem where search fields are working BUT backspace isnt. Also cant bind keys at all and gameplay doesnt recognise any keys as stated in this issue.

I am using a Samsung Tab S8 ultra with its stock keyboard, running on 2022.911.0-lazer
I created a issue (was converted into discussion) for this but it is probably a duplicate then (#20278 )

**Comment by laurinneff** [comment]
@bdach @Susko3  
I just installed Switchroot Android TV on my Nintendo Switch and tried out on there, and I get the exact same issue (including the logged source being 0x301). Maybe this is an issue with AOSP?

also, @V3rald, in your logs it also has source 0x301, so this looks like the same issue to me

**Comment by V3rald** [comment]
Yes its the same, i was just providing a bit more information that might or might not help
