### ISSUE TITLE
Lazer locks cursor to top of screen on secondary monitor (win11)

### ISSUE THREAD

**Issue by Doksha** [ppy/osu#19786]
### Type

Game behaviour

### Bug description

When moving lazer to portrait monitor (secondary) the cursor is locked to the top. If you alt F4 and try again, lazer will not start until you update the monitor configuration (either by unplugging a monitor or setting the portrait monitor to the main monitor, but this only works one way, so if you want to try to go back to having your landscape monitor as main, you will have to unplug your other monitors)
Also, lazer seems unable to detect the correct refresh rate of the monitor.
I have not tested this with a secondary landscape monitor, so whether this happens on landscape needs to be verified.

Sometimes you can get lucky and the cursor will unlock long enough to select a map, but then it goes back to being locked at the top

### Version

2022.810.2-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/9340945/network.log)
[performance.log](https://github.com/ppy/osu/files/9340949/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/9340953/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9340956/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9340959/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9340962/updater.log)
[database.log](https://github.com/ppy/osu/files/9340965/database.log)

**Comment by peppy** [comment]
Try turning off high precision mouse

**Comment by smoogipoo** [comment]
Closing as this is a stale issue.
