### ISSUE TITLE
Window does not get properly offset by the title bar using Intel integrated graphics

### ISSUE THREAD

**Issue by DevSDK** [ppy/osu#1978]
Noticed on Optimus devices, the window contents don't get properly offset by the application title bar.

PC Specifications (XPS 15 9560):
Windows 10 Pro
GTX1050 (Laptop)

![capture](https://user-images.githubusercontent.com/18409763/35386045-db0180b8-020d-11e8-9d0c-5688e429b1f8.PNG)

Works on Linux (Ubuntu 16.04 LTS).

**Comment by peppy** [comment]
Does it work correctly if you make the window smaller?

**Comment by DevSDK** [comment]
I'll try change many resolution and I can see sometime half-hidden sometime all-hidden.
But, I cannot see all top and bottom UI on Windowed mode.

**Comment by smoogipoo** [comment]
Can you make sure you're not actually running on the Intel GPU? Right click -> run with graphics processor -> nvidia gtx 1050

**Comment by DevSDK** [comment]
Oh I see. It is worked completely work on 1050. 
But it is make another issue...  Isn't it?
"Weird work osu! on laptop that inside intel optimous...."

**Comment by smoogipoo** [comment]
I've updated the issue description for this issue, don't need to make another one.

**Comment by ticotaco72** [comment]
can't reproduce on intel graphics - win 10
![2018-09-09](https://user-images.githubusercontent.com/32620809/45268411-15d49d80-b47c-11e8-8e7c-91ed3734d61e.png)
[database.log](https://github.com/ppy/osu/files/2364601/database.log)
[debug.log](https://github.com/ppy/osu/files/2364602/debug.log)
[network.log](https://github.com/ppy/osu/files/2364603/network.log)
[performance.log](https://github.com/ppy/osu/files/2364604/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2364605/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2364606/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2364607/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2364608/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2364609/runtime.log)

**Comment by Joehuu** [comment]
Can you still reproduce this on latest build @DevSDK ?

**Comment by DevSDK** [comment]
@Joehuu 
It looks fixed!
I've tested not only build & publish to exe, but also debug, release build setup on visual studio. 
Same laptop(XPS15 9560, GTX1050), same setups. 
![image](https://user-images.githubusercontent.com/18409763/66279504-cc5bb980-e8ec-11e9-8a7f-18d88cb702f6.png)

Above Image contains my test information. For the testing, I made executive file for launching with intel graphics.

And also test on binary build executive file. It work!

Thanks.

PS) Could you please let me know what is the problem and how to fix it?

**Comment by Joehuu** [comment]
I'm just going through stale issues that I can't reproduce.

I didn't fix the issue, and can't track what change fixed this as I never had this problem and only specific setups had this.

This issue is safe to close. Closing.
