### ISSUE TITLE
Changing/adding the mp3 or background of a beatmap disturbs ranked status

### ISSUE THREAD

**Issue by AadilRn** [ppy/osu#19797]
### Type

Game behaviour

### Bug description

Changing/adding the mp3 or background of a beatmap will change it to local status and not display leaderboards or allow you to submit a score to the global leaderboards. This does not replicate stable behaviour where changing the mp3 or background will not disturb the ranked status.

### Version

2022.810.2-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9347993/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9347994/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9347995/network.log)
[performance.log](https://github.com/ppy/osu/files/9347996/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9347997/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9347998/updater.log)

**Comment by toadsworth-jr** [comment]
That is intentional, because modifying files disqualifies the beatmap from submitting scores.

**Comment by AadilRn** [comment]
Yes, but modifying the mp3 or background in stable does not disqualify the map. I don't know if the devs never intended to allow players to change mp3s or backgrounds but this will be a pretty large complaint if devs decide that this was always the intended result.

**Comment by peppy** [comment]
If you have a reason for doing this, open a discussion stating the reasoning and we will provide an alternative path to resolution if it's seen as feasible. You should not be changing any files in the files directory. It will break the game.
