### ISSUE TITLE
Volume Controls

### ISSUE THREAD

**Issue by arflyte** [ppy/osu#1982]
![volume-settings](https://user-images.githubusercontent.com/3632750/35432960-20bf36ec-02c5-11e8-90c4-5dafec0c7442.jpg)

This is how the volume control looks like for osu!lazer. Almost similar to stable's, but it's on the left side.  Subtle dark gradient from the left for visibility purposes when the controls are active.

Hover each circle to modify the values. Mute/Unmute button. Bright orange outline on hover. Changes to Mute icon when muted.

Ignore the button with the artistically red cross drawn on it.

**Comment by jorolf** [comment]
Is there a way to display the volume circles? `CircularProgress` is filled, which means that there needs to be some kinf of new drawable. _Or we do some `Border` magic / change the texture of `CircularProgress`_

**Comment by jorolf** [comment]
The problem would be, that you can't create your own Texture in osu.Game. One of `TextureUpload`s ctors needs a Bitmap which has to included in the csproj

**Comment by thomastanck** [comment]
You should look at the VisualTests...

**Comment by jorolf** [comment]
`osu.Game`

**Comment by thomastanck** [comment]
![maim](https://user-images.githubusercontent.com/829070/35476527-68ec4540-03ec-11e8-9464-a1b0dfd50754.png)
Just add a reference to System.Drawing as the error message suggests. System.Drawing is already referenced in osu.Desktop anyway.

**Comment by jorolf** [comment]
I think this should be supported in the framework anyway

**Comment by jorolf** [comment]
![grafik](https://user-images.githubusercontent.com/12570757/35476814-d04ad778-03b6-11e8-9d54-c1c59a023c2a.png)
this works 🤔

**Comment by peppy** [comment]
In stable we made a custom shader to get the glow right. I can extract that code if you'd like something to work from.

**Comment by jorolf** [comment]
@arflyte MAX = 100, right? _(Because in your mockup 60 = ⅔ of the meter)_

**Comment by peppy** [comment]
yes

**Comment by jorolf** [comment]
Should VolumeControl and etc. be moved from UserInterface to Overlays?

**Comment by peppy** [comment]
Yeah, I think overlays suits it better.
