### ISSUE TITLE
Flipping a slider can change curve type of PerfectCurve control points to Bezier

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#19824]
### Type

Game behaviour

### Bug description

When editing a beatmap, flipping a PerfectCurve slider may change the curve type of that slider to Bezier. It's not just flipping a slider that can produce this behaviour, rotating, reversing, and possibly more operations can do this. I've done some investigation as to why this happens. 

The code which flips the position of the slider control points moves the control points one by one.
https://github.com/ppy/osu/blob/4627e4f53b96a6571c63ab5cf08accede4877537/osu.Game.Rulesets.Osu/Edit/OsuSelectionHandler.cs#L130-L136

Each time an anchor is moved, the path is invalidated and the `PathControlPointPiece` gets notified and calls `updatePathType`
https://github.com/ppy/osu/blob/4627e4f53b96a6571c63ab5cf08accede4877537/osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointPiece.cs#L224-L226

If not all control points have been moved yet and they happen to be in an unfortunate position, then we can get an invalid perfect curve which gets corrected to a bezier.

### Screenshots or videos

https://user-images.githubusercontent.com/17460441/185263241-f3303ae3-a4cd-404d-96da-2776b2d1f6b6.mp4

### Version

latest master branch 18/8/2022

### Logs

[runtime.log](https://github.com/ppy/osu/files/9366682/runtime.log)

**Comment by peppy** [comment]
Thanks for the detailed report. Definitely seems like either we want to be invalidating less often (ie. not watching the collection and triggering a higher level event) or updating all points in one go somehow.

**Comment by smoogipoo** [comment]
Other places (`OsuModHardRock`) update all points in one go. Can/should do that here also.

**Comment by peppy** [comment]
For reference:

https://github.com/ppy/osu/blob/f8830c6850128456266c82de83273204f8b74ac0/osu.Game.Rulesets.Osu/Utils/OsuHitObjectGenerationUtils.cs#L147-L151

**Comment by OliBomby** [comment]
I think it will be beneficial to add some feature to SliderPath which can temporarily prevent it from invalidating. Perhaps a `beginChange()` and `endChange()` method which disables invalidating until `endChange()` is called and only then invalidates once. This would allow you to make changes to slider paths like moving points one by one without triggering invalidation while the edit is not yet complete. Performance would be better because you won't have to create multiple temporary arrays to edit all control points at once. It might also be easier to understand for the reader because seeing `beginChange()` and `endChange()` explains to the reader why it is being done in that way.

**Comment by bdach** [comment]
I don't really agree with this "prevent invalidation" flow. To me the fact that the state of the slider is always consistent with the currently-set path is a _feature_ which decreases complexity (because you can't forget to call `endChange()` and leave the slider in a broken state). I don't see any real reason to add *more* `{begin,end}Change()` stuff if setting the flipped path in one go is a viable alternative.

> This would allow you to make changes to slider paths like moving points one by one without triggering invalidation while the edit is not yet complete

I'm not sure where this would be wanted. At least when editing interactively, again, having the state of the path update as modifications are applied is the desirable outcome.
