### ISSUE TITLE
i can't install osu lazer on my windows 8 laptop it keeps on saying "installation failed" can someone help 

### ISSUE THREAD

**Issue by otaku82** [ppy/osu#1985]

**Comment by jacksonisiah** [comment]
can you provide a screenshot or something we can use to help us fix your issue?

**Comment by Frontear** [comment]
Try to build the latest available build through some c# compatible IDE (visual studio works). If the issue still occurs, something in your hardware may not be correctly working for lazer. Alternatively, provide some sort of logs, or some more information, such as specs. It really is hard to find out your issue with such a vague title, and 0 information.

**Comment by peppy** [comment]
Closing until further information is provided.
