### ISSUE TITLE
Weird behaviour of stable skins and the skin editor

### ISSUE THREAD

**Issue by cheeezie** [ppy/osu#19872]
### Type

Game behaviour

## There are some inconsistencies and problems that I have found with stable skins and the skin editor while having a stable skin on, those were my findings:

<details><summary>Point 1:</summary>

1. Azure Snowfall is the first skin that I tested for my theory, the first screenshot is from the stable track while the second is from lazer. It seems like the other UI elements (that is a part of the health bar UI (explained in screenshot 7, point 2)), anchors to the left side of the legacy pie progress bar. To further validate it, I tried 2 other skins as well, Chocolate 105° (by Tkieen) (screenshots 3 and 4) and Chocolate and Vanilla - Nekopara (by Suminoze) (screenshots 5 and 6) and my theory was correct from my testings.

</details>
<details><summary>Point 2:</summary>

2. As it stands both the health bar and other UI elements are in one group which can be a cause of another issue that is seen in screenshot 7, where the health bar and other UI take up a big space in the editor, making editing a little bit of a hassle.

</details>
<details><summary>Point 3:</summary>

3. For the last screenshot (number 8), there is an issue with how the scaling of the bar and the other UI elements stand. In Stable it is bigger (how it should look like). While in lazer it looks smaller, especially noticable in the health bar.
P.S, in screenshot 9. The other UI elements wasn't visible in the skin editor for the Azure Snowfall skin.
(I tested it on Android as well but I got unusual results from my device with a non-16:9 aspect ratio display (screenshot 10).

</details>
<details><summary>Some specs:</summary>

Some specs and stuff:
Resolution of the computer: 1366x768 (still have been tested in 1280x720 in the driver and display level)
Resolution of the phone (OnePlus 8T running the latest updates): 2400x1080 (the game isn't rendered in native resolution because the game wasn't run in immersive fullscreen mode).

</details>

### Screenshots or videos
<details><summary>Screenshots:</summary>

![1](https://user-images.githubusercontent.com/102518950/185755480-42ee7438-a26d-45a3-b628-2fdd6809fb1f.jpg)
Screenshot 1

![2](https://user-images.githubusercontent.com/102518950/185755482-009153f4-c86c-4d42-b539-af5b4a964fb5.png)
Screenshot 2

![3](https://user-images.githubusercontent.com/102518950/185755484-6b999304-0595-457c-856a-56f3d087bdb3.jpg)
Screenshot 3

![4](https://user-images.githubusercontent.com/102518950/185755486-4ded3f47-76af-406c-bac7-54d94862d606.png)
Screenshot 4

![5](https://user-images.githubusercontent.com/102518950/185755487-ffa6b971-ef39-47bd-9aae-79e146254cec.jpg)
Screenshot 5

![6](https://user-images.githubusercontent.com/102518950/185755488-17628f1d-cff8-4999-9137-33b841b86d24.png)
Screenshot 6

![7](https://user-images.githubusercontent.com/102518950/185755489-0dd5a4bc-1773-4859-bd8b-8e6e6ffbf448.png)
Screenshot 7

![8](https://user-images.githubusercontent.com/102518950/185755490-2538bad3-2723-441d-a069-5484e5e1537c.png)
Screenshot 8

![9](https://user-images.githubusercontent.com/102518950/185755491-7e6e39bc-43d0-44d0-87c3-d72fd20cd5a0.png)
Screenshot 9

![10](https://user-images.githubusercontent.com/102518950/185755493-59224018-dc63-4ede-8311-cadc91486e0e.jpg)
Screenshot 10
</details>

### Version

osu!lazer 2022.816.0

### Logs

<details><summary>Logs:</summary>

[runtime.log](https://github.com/ppy/osu/files/9387610/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9387611/updater.log)
[database.log](https://github.com/ppy/osu/files/9387612/database.log)
[network.log](https://github.com/ppy/osu/files/9387613/network.log)
[performance.log](https://github.com/ppy/osu/files/9387614/performance.log)

</details>

**Comment by bdach** [comment]
You haven't actually linked any of the skins, but I'm relatively certain they were all "aligning" the elements you mention (i.e. the bells and whistles near the score display, or the playfield border) by abusing stable's element alignment logic. This was never portable, relied on the game's aspect ratio, and will not be supported going forward.

See also: https://github.com/ppy/osu/discussions/18684
