### ISSUE TITLE
Installation on Win7 Error - squBD3.tmp.exe with error at (0xc000007b) - Fails to install

### ISSUE THREAD

**Issue by ag111112** [ppy/osu#19878]
### Type

Crash to desktop

### Bug description

Trying to use the Osu! Lazer installer does not get further than this error. I have tried various fixes I could find associated with an (0xc000007b) error, including installing different .NET dependencies, replacing xinput1_3.dll (read in one persons fix guide to replace with most up to date version), checking my dx to make sure its not outdated itself (using 11), ... I stopped there, because I started to worry about installing something that might do more damage than good.

Attached is screenshots of the errors (it shows the first window, then clicking OK shows the second window), the location I had to use to find the squirreltemp log (the error's listed location didn't exist), and the .NET stuff I currently have installed.

I tried to make sure this is not a repeat issue, I'm very sorry if it is!

### Screenshots or videos

![1_first error](https://user-images.githubusercontent.com/111667997/185771503-8fd45228-8dda-42ff-a7b3-90188e74cc08.png)
![2_second error](https://user-images.githubusercontent.com/111667997/185771507-e5d9bcf8-6973-430d-a1cc-ac1c6b905fb4.png)
![other_location](https://user-images.githubusercontent.com/111667997/185771632-39263fa2-735b-4206-bf30-bbce454ec1b9.png)
![other_dotnet list](https://user-images.githubusercontent.com/111667997/185771633-63bf26a7-53a5-4661-ad9d-29333f50e1fd.png)

### Version

2022.816.0

### Logs

[SquirrelSetup.log](https://github.com/ppy/osu/files/9388266/SquirrelSetup.log)

**Comment by jai-x** [comment]
As per the [readme](https://github.com/ppy/osu/blob/master/README.md), osu!lazer requires a minimum of Windows 8.1 to run.

Please read the documentation carefully.
