### ISSUE TITLE
osu!lazer never boot up

### ISSUE THREAD

**Issue by Kuina-chan** [ppy/osu#19880]
### Type

Crash to desktop

### Bug description

I was playing the game normally when one day, I miss-clicked the wrong version I want to play, which is lazer. Before the game show the intro, I instantly Alt+F4, and then the game no longer can be boot up again. The game just display a black screen then quit

### Screenshots or videos

https://user-images.githubusercontent.com/75318520/185786364-5995b9c3-8b36-4132-a0f6-bea203a2d947.mp4

### Version

Release 2022.821.0

### Logs

Sadly, I can't find any logs file inside the osu!lazer. Despite no log inside osu!, I mananged to find a log related to osu!lazer in the event viewer

[Event Viewer Log.txt](https://github.com/ppy/osu/files/9388869/Event.Viewer.Log.txt)

**Comment by bdach** [comment]
Attached event viewer log error shows exception code `0xc0000409` which is `STATUS_STACK_BUFFER_OVERRUN`. [Has been seen before](https://github.com/ppy/osu/issues/8686) but the cause is unclear. I'm not even super sure it's related unless it shows up every time without fail when trying to launch.

**Comment by Kuina-chan** [comment]
I saw this same error twice in the event viewer, so I kinda suspect it may related to the game itself

**Comment by Kuina-chan** [comment]
@bdach I found the way to open it by the command in the powershell: 
$env:COMPlus_DefaultStackSize = 10000000; .\osu!.exe

**Comment by peppy** [comment]
@Kuina-chan if that fixes your issue, there's a few things that we need to follow up with:

- What's your operating system / environment? Anything uncommon hardware or software wise?
- If that makes osu! run, could you please provide your logs from a session after it's running?

**Comment by smoogipoo** [comment]
It would be really helpful if you can get a crash dump. Unfortunately, I don't believe this is turned on by defaults, so instructions to turn it on are here: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps (just the default values are fine)

Also, please don't post the dump publicly. Send it to pe@ppy.sh instead.

**Comment by Kuina-chan** [comment]
@peppy I'm using Windows 10 Pro, 21H2 version. Also I don't think there is any uncommon hardware. Software however, I do install StreamCompanion from Pioketrol and Sentakki ruleset. StreamCompanion is out of suspect because before I found the bug fix, I tried to close StreamCompanion and run, but it still no work like the video presented. Also here is the log
[updater.log](https://github.com/ppy/osu/files/9391994/updater.log)
[database.log](https://github.com/ppy/osu/files/9391995/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9391996/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9391997/network.log)
[performance.log](https://github.com/ppy/osu/files/9391998/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9391999/runtime.log)

**Comment by Kuina-chan** [comment]
@smoogipoo I got the game to run so that crash dump I think no longer have anything inside?

**Comment by smoogipoo** [comment]
Crash dumps are a different thing that's done by Windows itself. It's when that message box shows up after a crash. But you'd need to set it up as above.

**Comment by Kuina-chan** [comment]
Back when the bug happen, there is no message box, but the game works now so I don't know if that still need or not

**Comment by bdach** [comment]
@Kuina-chan to confirm: are you saying that after you ran the game with `COMPlus_DefaultStackSize = 10000000` once, it works fine and you don't have to pass that parameter again? or are you still running with that parameter every time?

**Comment by JustKirill1** [comment]
Ok i have a few comments about it
1. OpenTablet is not an issue
2. If start with administration rights the game will run but eventually freeze when game modes appear
3. If after that start the game without administration rights the game will run but freeze instantly
4. Even though it's running it doesn't create a log file
UPD: the game freezes/crashes only after you open a window if it's running withought opening it it won't freeze/crash

**Comment by bdach** [comment]
@JustKirill1 that doesn't even sound like remotely the same issue. please open a separate discussion thread about your problem

**Comment by Kuina-chan** [comment]
@bdach yes, I don't have to pass that parameter, I just need to execute it once in the PowerShell and everything back to normal

@JustKirill1 I tried all the method you said, and I confirm that OpenTablet and Wacom Driver is not an issue

**Comment by bdach** [comment]
@Kuina-chan if you're not having to pass the argument anymore and the game just works now then there's nothing to debug here anymore.

I'm going to tentatively close. If this happens again, i.e. you have to specify the parameter again to be able to launch the game, or I'm misunderstanding and you *do* still have to pass the parameter, then please reply here and I'll reopen the issue.

**Comment by Kuina-chan** [comment]
@bdach idk if recently osu!lazer has update or not (prob yes), I can't open the game and passing the parameter in PowerShell never work. On the day that I update, the game still work fine. I compared this event log with the previous, found out that it's the same bug cause by the same module: ntdll.dll
