### ISSUE TITLE
Scoring Bug

### ISSUE THREAD

**Issue by Elkan10** [ppy/osu#19886]
### Type

Game behaviour

### Bug description

Personal Best Score is not accurate after the latest update. Scores with Relax or Autopilot is shown as Personal Best even though those mods were nerfed.

### Version

2022.821.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9389040/database.log)
[network.log](https://github.com/ppy/osu/files/9389041/network.log)
[performance.log](https://github.com/ppy/osu/files/9389042/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9389043/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9389044/updater.log)

**Comment by peppy** [comment]
read changelog.
