### ISSUE TITLE
Importing certain beatmaps never finishes and is unabortable

### ISSUE THREAD

**Issue by MrTheMake** [ppy/osu#1988]
When you try to import certain beatmaps (e.g. https://osu.ppy.sh/s/594828), the process never finishes and trying to cancel it doesn't work either (Just stays in the canceling state).

**Comment by fangerm** [comment]
It's probably an issue with 0/Infinity BPM. See #750

**Comment by ZapTech43** [comment]
But when i tried to import beatmaps from my osu! It Did Worked well
