### ISSUE TITLE
Cheat Engine completely working

### ISSUE THREAD

**Issue by Tulip-0333** [ppy/osu#19888]
### Type

Game behaviour

### Bug description

While testing, I opened Cheat Engine. Neither Cheat Engine or osu! closed. I checked if speedhack worked, and it did (just unplayable). I didn't submit any scores so I didn't actually cheat. I'm just pointing out that hacking is basically completely possible.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/93089383/185796548-d0dd5f21-1b9a-488e-a055-f022ad9de447.png)

### Version

2022.821.0

### Logs

[network.log](https://github.com/ppy/osu/files/9389340/network.log)
[performance.log](https://github.com/ppy/osu/files/9389341/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9389342/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9389343/updater.log)
[database.log](https://github.com/ppy/osu/files/9389344/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9389345/legacy-ipc.log)

I don't know why I need these, but okay!

**Comment by jai-x** [comment]
Anti cheat has not been added to osu!lazer yet.
See https://github.com/ppy/osu/issues/18876
Currently, scores submitted by osu!lazer go to a separate leaderboard which has the ability to be wiped in cases of undesired scores being submitted, so there's less risk at the moment.

**Comment by Tulip-0333** [comment]
Oh, alright! Thanks.
