### ISSUE TITLE
Changelog date disappears before being off screen

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#19891]
### Type

Game behaviour

### Bug description

As title. 

### Screenshots or videos

![changelog](https://user-images.githubusercontent.com/43073074/185798581-35672362-f8af-4a06-9af4-b061e597a566.gif)

It seems that its container only accounts for the text above for some reason, I don't know if this is the reason:
![image](https://user-images.githubusercontent.com/43073074/185798535-8a2d45f4-15a5-4052-afdf-98276820a3c7.png)

### Version

2022.821.0-lazer

### Logs

.

**Comment by smoogipoo** [comment]
Yes, it's because the parent container is being masked away and children are placed outside of it.
