### ISSUE TITLE
Draw Visualiser can block hover events even after selecting a target

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#19890]
### Type

Game behaviour

### Bug description

As title. The problem is solved:
- By hovering at least once inside the draw visualiser
- By taking the cursor outside the game window

### Screenshots or videos

https://user-images.githubusercontent.com/43073074/185798120-34c39a81-0d0a-4525-9d62-4adb39f2f20c.mp4

### Version

2022.821.0-lazer

### Logs

.

**Comment by peppy** [comment]
Yes, it does.

**Comment by peppy** [comment]
If you have an issue, please open against osu-framework with an explanation of why it's an issue.
