### ISSUE TITLE
Game crash when merging Hit Objects

### ISSUE THREAD

**Issue by Dia1006** [ppy/osu#19894]
### Type

Crash to desktop

### Bug description

When putting 2 Hit Circles on top of eachother and merging them into a slider nothing happens, but when you try to extend said slider via the beatmap timeline the game freezes and crashes shortly after.
The game will immediately crash when the Beat Divisor is below 1/4

### Screenshots or videos

Dragging the Black Bot in the middle of the Slider(Timeline) to the right will result in a crash
![osucrash](https://user-images.githubusercontent.com/110993151/185801796-269c5b20-1ca8-42aa-80d5-b4a89161c75c.png)

### Version

2022.821.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9389610/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9389611/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9389612/network.log)
[performance.log](https://github.com/ppy/osu/files/9389613/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9389614/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9389615/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9389616/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9389617/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9389618/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9389619/updater.log)

**Comment by bdach** [comment]
The merge operation shouldn't be available in this situation.
