### ISSUE TITLE
Hold note duration can't be modified in the playfield of the editor

### ISSUE THREAD

**Issue by Bruno5430** [ppy/osu#19900]
### Type

Game behaviour

### Bug description

After placing a longnote in the editor I can't drag the longnote end to modify the duration like in stable

### Screenshots or videos

https://user-images.githubusercontent.com/111712756/185818414-8274a6d4-f0e2-4c88-b54a-b24fdf219b4c.mp4

https://user-images.githubusercontent.com/111712756/185818424-6cc85c86-69da-48fd-b856-06f4342a151b.mp4

### Version

2022.821.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9390244/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9390245/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9390246/network.log)
[performance.log](https://github.com/ppy/osu/files/9390247/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9390248/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9390249/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9390250/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9390251/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9390252/runtime.log)

**Comment by peppy** [comment]
Hvaen't confirmed this yet, but as a temporary workaround you can drag in the timeline.
