### ISSUE TITLE
Leaderboards show wrong placements

### ISSUE THREAD

**Issue by Sr3qt** [ppy/osu#19916]
### Type

Game behaviour

### Bug description

The leaderboard shows wrong placements in few different ways and there seems to be some score issues too.

### Screenshots or videos

Here I am placed correctly, but my personal best shows the wrong leaderboard rank:

![image](https://user-images.githubusercontent.com/105977398/186009308-c1411c2e-538d-4940-83e9-ef7e35d4ec39.png)

Don't know if it is related but I also tried to submit a score that didn't overwrite my previous score on the global leaderboard. Additionally, I tried rerunning the old score and got 141 748, which, with the images included give three different scores

![osu_2022-08-22_22-10-38-copy](https://user-images.githubusercontent.com/105977398/186010155-4fa45dd2-aa76-4373-8591-4332a8c3e601.jpg)

Set a new score and got correctly placed, but again personal best has the wrong number wrong. After rerunning the score i got 727 990

![image](https://user-images.githubusercontent.com/105977398/186010385-103fee42-0d3d-4122-a4d0-0dfb1fea1f66.png)

Score seems to have been submitted, but this time the placement is completely wrong. According to the scores it should be a number 1 play. Also rerunning the score gives 69 752

![osu_2022-08-22_22-19-31-copy](https://user-images.githubusercontent.com/105977398/186013288-aa7c4cd6-0c37-4b46-ac66-cd437d47f15d.jpg)

### Version

2022.821.0 - lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/9397367/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9397368/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9397369/updater.log)
[database.log](https://github.com/ppy/osu/files/9397370/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9397371/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9397372/network.log)

**Comment by peppy** [comment]
Scores server-side need to be recalculated, as mentioned on the changelog, this will happen over the coming week.
