### ISSUE TITLE
New scores dont post when previous relax scores were higher

### ISSUE THREAD

**Issue by JustToasty** [ppy/osu#19921]
### Type

Game behaviour

### Bug description

I had a score made with the relax mod before the recent update, After the update my score was nerfed (as expected). But now when I make a higher score than what the relax score is now set as, it doesn't show up on global leaderboards.

How to reproduce: Get a high relax score on the previous release, update, get a score lower than the previous score without the mod

Also worth noting I have this issue on both Android and Windows

### Screenshots or videos

![osu_2022-08-23_00-49-52](https://user-images.githubusercontent.com/50493368/186072756-74a76d4f-755d-4400-b76d-b0a60054c116.png)
![osu_2022-08-23_00-38-13](https://user-images.githubusercontent.com/50493368/186072759-fee3d10c-1ebc-4c23-beac-4396253c4a94.png)

### Version

2022.821.0

### Logs

[performance.log](https://github.com/ppy/osu/files/9399458/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9399459/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9399460/updater.log)
[database.log](https://github.com/ppy/osu/files/9399461/database.log)
[network.log](https://github.com/ppy/osu/files/9399462/network.log)

**Comment by peppy** [comment]
This is because we're still waiting on sever reprocessing of old scores. This will happen sometime in the next week most likely.
