### ISSUE TITLE
macOS: Game data corrupt immediately if moved to an exFAT partition

### ISSUE THREAD

**Issue by i0ntempest** [ppy/osu#19948]
### Type

Crash to desktop

### Bug description

If I move the game folder to a exFAT partition within the game and quit it, the game will crash and no longer open (crash on startup).

### Version

2022.821.0

### Logs

[database.log](https://github.com/ppy/osu/files/9419346/database.log)
[network.log](https://github.com/ppy/osu/files/9419347/network.log)
[performance.log](https://github.com/ppy/osu/files/9419348/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9419350/runtime.log)
macOS crash log
[crash.log](https://github.com/ppy/osu/files/9419362/crash.log)

**Comment by peppy** [comment]
This is a limitation of realm. Please avoid doing this.

We’ll need to add better messaging to avoid this happening in the first place.

**Comment by i0ntempest** [comment]
Well the size of my beatmap library doesn't allow me to put it on the system partition. It worked for a period of time before, so this limitation must be new?

**Comment by peppy** [comment]
Unless you mean a year or more ago, nothing should have changed.

Out of curiosity, is there a reason you use an ExFAT partition as opposed to APFS or HFS+?

**Comment by i0ntempest** [comment]
Can't remember the exact time but it definately worked in late 2021/early 2022.
I have a dual boot setup and afaik only exFAT allows r/w access for both macOS and Windows (officially anyways). I have thought about making lazer on both OSes use the same directory, not sure if that's a good idea so haven't tried yet.

**Comment by peppy** [comment]
Hmm... so realm has this fallback logic which should handle these cases (as discussed at https://github.com/realm/realm-dotnet/issues/2751). Could something have regressed with that? Or maybe it never worked? We'll need to test this against an ExFAT drive and report back to realm.

**Comment by i0ntempest** [comment]
Just found the screenshot I took in lazer on macOS, it was taken on April 24. So the newest version at that time definately worked.

**Comment by peppy** [comment]
I can reproduce the issue, so I will report it upstream.

**Comment by peppy** [comment]
Tracking at https://github.com/realm/realm-dotnet/issues/3007.

**Comment by peppy** [comment]
This has been fixed upstream. We should be able to close out this issue after the next realm release.
