### ISSUE TITLE
I cant compile

### ISSUE THREAD

**Issue by StartForKillerMC** [ppy/osu#1995]
When compiling says this: osu-master\osu.Game\Database\OsuDbContext.cs(15,47,15,55): error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

I dont iclude all the roors but this is the first error

**Comment by Aergwyn** [comment]
Restore NuGet packages.

**Comment by VPeruS** [comment]
https://github.com/ppy/osu/pull/1406 last comment

**Comment by ZLima12** [comment]
While there is a workaround, it would be optimal to reference the library instead of using a symlink.
