### ISSUE TITLE
Clicking and dragging, then hitting z or v will only select objects that are on the timeline at either point

### ISSUE THREAD

**Issue by Doksha** [ppy/osu#19954]
### Type

Game behaviour

### Bug description

Badly articulated title, but when you hit z or v while drag clicking on the timeline in the editor, only the objects that are visible on the timeline after you hit either of the keys will be selected, (if you hold shift while doing this, this will be extended to include the objects that were visible before you hit z or v, but none of the objects inbetween.)
The expected behavior (from stable) is to select all notes in between where you started dragging, and where you end up after hitting z or v.

### Version

2022.821.0-lazer

### Logs

[performance-update.log](https://github.com/ppy/osu/files/9421027/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9421028/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9421029/updater.log)
[database.log](https://github.com/ppy/osu/files/9421030/database.log)
[network.log](https://github.com/ppy/osu/files/9421031/network.log)
[performance.log](https://github.com/ppy/osu/files/9421032/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/9421033/performance-draw.log)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/16410
