### ISSUE TITLE
Displayed mania difficulty not correct after latest update

### ISSUE THREAD

**Issue by Dangonizer** [ppy/osu#19968]
### Type

Game behaviour

### Bug description

After the latest update adjusted the difficulty rating for many mania maps, the wrong difficulty is shown at map select. Sorting by difficulty sorts the maps in order of the new difficulty which is correctly displayed when looking at the web view of the map.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/88250185/186686961-b1a473fb-244e-44be-bad6-006a2f0b857e.png)
![image](https://user-images.githubusercontent.com/88250185/186687073-a06610be-d536-4c79-8517-473bdae380fe.png)

### Version

2022.821.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9425423/database.log)
[network.log](https://github.com/ppy/osu/files/9425424/network.log)
[performance.log](https://github.com/ppy/osu/files/9425425/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9425426/runtime.log)

**Comment by frenzibyte** [comment]
I don't understand what the screenshots are meant to indicate, can you explain what's wrong in both of them?

**Comment by Dangonizer** [comment]
On map selection the difficulty is shown as 3.37 while on the website it is shown as 3.27. This is true for most of my maps.

**Comment by smoogipoo** [comment]
Yeah this is intentional for the time being since mania's SR/PP algorithms have been updated but hasn't been deployed to osu!web.
