### ISSUE TITLE
Exclusive fullscreen not working warning is incorrectly showing for intel GPUs

### ISSUE THREAD

**Issue by peppy** [ppy/osu#19961]
I think we want to at least disable this warning for intel GPUs for now, as it is a touch misleading and already caused confusion amongst users that believe things aren't working when they usually are.

---

### Discussed in https://github.com/ppy/osu/discussions/19785

<div type='discussions-op-text'>

<sup>Originally posted by **InsertX2k** August 16, 2022</sup>
Hello, 
So after I got the new osu!lazer update, it seems like I got an issue with the new "exclusive full screen" mode.
The issue is that whenever i switch to the exclusive full screen mode there appears a red word that says "Unable to enter exclusive full screen mode"

My PC Specifications are:
CPU: Intel Core i5 3470
RAM: 12 GB RAM
GPU: Intel HD Graphics 2500 w/ latest GPU Drivers
the issue doesn't seem to be a hardware related, i think it is a bug in osu!lazer as my PC is able to run it at 120fps</div>

**Comment by InsertX2k** [comment]
Hello ppy,
Thank you for disabling this warning for Intel iGPUs as it leads us into thinking that there is a bug in your osu!lazer game.
I would like to be as helpful as possible to help you solve this issue, so if there is anything I can do to help you solve this issue, don't hesitate to tell me what is it.
Thanks,
Ziad Ahmed (Mr.X)
