### ISSUE TITLE
Unpausing gameplay skips forwards a little bit

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#19975]
### Type

Game behaviour

### Bug description

Regressed in https://github.com/ppy/osu/pull/19828

### Screenshots or videos

https://user-images.githubusercontent.com/1329837/186894216-31a0257c-da24-4c97-ac6b-313059ef16bd.mp4

### Version

91e044542d5af54454282aa883727e24e6ee1baa

### Logs

-

**Comment by peppy** [comment]
Hmm interesting. I did notice this but thought it was only jumping by the freq ramp (which has beeen something that historically was the case). Either way, needs to be fixed, was on my list for the clock rewrite.
