### ISSUE TITLE
Leaderboard top 50 did not update after some mod multipliers were changed

### ISSUE THREAD

**Issue by Doksha** [ppy/osu#19979]
### Type

Game behaviour

### Bug description

The set of players in the top 50 is the same as before the change (ie, if you were in the top 50 with a relax score, that score is still in the top 50 even if there are more than 50 scores better than the new score) the scores are re-ordered *within* the top 50, but scores that shouldnt be in the top 50 are still there

### Screenshots or videos

![osu_2022-08-26_21-29-55](https://user-images.githubusercontent.com/72625258/187009016-1ffc2f38-70f0-40a4-b5df-18aef848caf7.jpg)

### Version

2022.821.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9437083/database.log)
[network.log](https://github.com/ppy/osu/files/9437084/network.log)
[performance.log](https://github.com/ppy/osu/files/9437085/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/9437086/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9437087/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9437088/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9437089/updater.log)

**Comment by apollo-dw** [comment]
This is already known - please refer to the changelog and search before posting issues to avoid duplicate posts.
