### ISSUE TITLE
Best scores are not submited because of relax scores.

### ISSUE THREAD

**Issue by okolenmi** [ppy/osu#19972]
### Type

Game behaviour

### Bug description

My nomode scores was not submited but only on maps where I have "better" old Relax score. 
(Now relax scores is like I'm playing maps on 40% accuracy with NF. Before it was a full score up to million) 
It's all.

### Screenshots or videos

![osu_2022-08-26_09-41-28](https://user-images.githubusercontent.com/55319814/186839029-f15c1ef7-5365-4a16-875e-9bb869f5450d.jpg)
![osu_2022-08-26_09-41-48](https://user-images.githubusercontent.com/55319814/186839064-6f657ec7-74dd-4f0e-b9c1-772ffdeab535.jpg)

### Version

osu! 2022-821.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/9430486/network.log)
[performance.log](https://github.com/ppy/osu/files/9430487/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9430488/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9430489/updater.log)
[database.log](https://github.com/ppy/osu/files/9430490/database.log)

**Comment by peppy** [comment]
Please read the changelog. Server side reprocessing has not happened yet.

Please also search before opening an issue. This has been reported countless times.
