### ISSUE TITLE
Osu Score bug after Pc restart 

### ISSUE THREAD

**Issue by OsuGerman** [ppy/osu#19986]
### Type

Game behaviour

### Bug description

Finished the map successfully and then had to restart my PC. Now the score has been halved and suddenly it is 0 pp. DAvor there were 202 see picture also the ranking is wrong.

Score is not correct after PC restart 

### Screenshots or videos

![osu_2022-08-27_22-33-03](https://user-images.githubusercontent.com/89344482/187047921-3b138239-f423-4df1-89b9-00349d533f9b.jpg)

1-Picture before PC restart
![osu_2022-08-27_22-52-20](https://user-images.githubusercontent.com/89344482/187047928-2ca4f1da-6aa5-4408-8c51-b1223e7dc72b.jpg)

2-Picture after restart  

### Version

2022.821.0

### Logs

[performance.log](https://github.com/ppy/osu/files/9438678/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9438679/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9438680/updater.log)
[database.log](https://github.com/ppy/osu/files/9438681/database.log)
[network.log](https://github.com/ppy/osu/files/9438682/network.log)

**Comment by Flamiii** [comment]
It's not a bug; your game updated to the latest version of lazer which gives Difficulty Adjust a 0.5x multiplier so your score was halved. Leaderboard positions will be reprocessed at a later date

**Comment by OsuGerman** [comment]
ok thanks
