### ISSUE TITLE
Cursor disappear when pressing down with tablet

### ISSUE THREAD

**Issue by BurningFlames2314** [ppy/osu#19983]
### Type

Game behaviour

### Bug description

For some reason my cursor disappears when i press down with my pen... it is very distracting since i play a hybrid of hover and drag (especially for spinners) and it gets really distracting when sometimes the cursors opacity drops down to like 10% and becomes barely visible. its like FL mod but instead of the entire screen dimming when a button is pressed, its just cursor dimming when i hold down my pen. 

I use a CTL-6100WL - Wacom Intuos M BT

### Screenshots or videos

Menu:
https://user-images.githubusercontent.com/104247330/187030631-d202782c-cf8a-4c5c-9d84-0ca3fa068bf1.mp4

Gameplay:
https://user-images.githubusercontent.com/104247330/187030639-85efd353-336d-4734-b197-ee5bdea8324d.mp4

### Version

2022.821.0

### Logs

[network.log](https://github.com/ppy/osu/files/9437967/network.log)
[performance.log](https://github.com/ppy/osu/files/9437968/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9437969/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9437970/updater.log)
[database.log](https://github.com/ppy/osu/files/9437971/database.log)

**Comment by jai-x** [comment]
Your tablet input is being detected as a Windows touchscreen event.

Either enable this option in the settings or use the built-in tablet driver:
![image](https://user-images.githubusercontent.com/8362491/187030994-b70b0ee2-3bd4-4b10-b277-018cbf1fb8fc.png)

See also: https://github.com/ppy/osu/pull/19389 and it's linked issues.
