### ISSUE TITLE
Inability to override relax score

### ISSUE THREAD

**Issue by 19peytonsmith** [ppy/osu#19993]
### Type

Game behaviour

### Bug description

I tried playing two maps, both of which I already had relax scores on the leaderboard, I tried to play without relax to overwrite and was unable to, even though the score was clearly higher, surely unintended.

### Screenshots or videos

![osu_2022-08-27_21-04-17](https://user-images.githubusercontent.com/54728307/187053432-d586f223-e9ae-4963-af10-be517934b2b5.jpg)
![osu_2022-08-27_21-04-23](https://user-images.githubusercontent.com/54728307/187053433-97cfd899-9497-4a29-9c44-ff05129a68fe.jpg)
![osu_2022-08-27_21-09-08](https://user-images.githubusercontent.com/54728307/187053434-3453bad5-b658-4f73-9c36-589863eac8bd.jpg)
![osu_2022-08-27_21-09-12](https://user-images.githubusercontent.com/54728307/187053436-e309d69b-e470-4b91-8340-b71b0b47da78.jpg)

### Version

2022.821.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/9438901/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9438902/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9438903/updater.log)
[database.log](https://github.com/ppy/osu/files/9438904/database.log)
[network.log](https://github.com/ppy/osu/files/9438905/network.log)

**Comment by 19peytonsmith** [comment]
The leaderboard ranking also seems to be incorrect, which is another issue in of itself.

**Comment by peppy** [comment]
Please check the last changelog. Don't worry, your scores are being saved.
