### ISSUE TITLE
Pressing pen buttons freezes keyboard input

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu#20007]
### Type

Game behaviour

### Bug description

During gameplay in osu!lazer, if any button on a tablet pen is pressed or the pen is touched to the tablet, it 'freezes' input for a second or two. Basically, it ignores any new key presses and will keep holding any pressed keys.

I'm on a 2021 14-inch MacBook Pro with Apple M1 Pro and 16 GB memory. My tablet is a Wacom Intuos BT S. My osu!lazer tablet input settings are: 
* tablet: enabled
* X offset: 40
* Y offset: 22
* Rotation: 0
* Aspect ratio: 1.78
* Lock aspect ratio: disabled
* Width: 80
* Height: 45

My Wacom tablet settings are:
* Tap: Click
* Button 1: Click
* Button 2: Right Click
* Mode: Pen
* Screen Area: full
* Force Proportions: disabled
* Tablet Coordinates: Top: 0, Left: 0, Bottom: 4500, Right: 8000
* Pen Button Mode: Hover Click (Reproduced with both)

My Wacom drivers are version 6.3.46-1.

### Screenshots or videos

https://user-images.githubusercontent.com/100527514/187096944-10a4bf9c-b4a2-4d60-8f9a-78fa6e55e565.mp4

During this clip, I'm spamming buttons 1 and 2 for the entire time. At 0:01, I press down the first button on my mouse.

### Version

2022.821.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9440557/database.log)
[network.log](https://github.com/ppy/osu/files/9440558/network.log)
[performance.log](https://github.com/ppy/osu/files/9440559/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9440560/runtime.log)

**Comment by peppy** [comment]
This sounds like it could be a conflict with any external tablet software you have installed (ie. wacom's or other).

As an initial test, can you try turning *off* tablet support in lazer and then try to reproduce the issue?

**Comment by Non-Binary-Programmer** [comment]
It's fixed after restarting my device so it's probably a driver issue.
