### ISSUE TITLE
creating and editing beatmaps on lazer's editor causes an error on mobile platforms

### ISSUE THREAD

**Issue by toadsworth-jr** [ppy/osu#20000]
### Type

Game behaviour

### Bug description

Editing any beatmap on lazer's editor causes the editor to lock up and display an error for mobile platforms. Said mobile platform was seen on an Android 10 device, and the error wouldn't go away even after a fresh reinstall, even after restarting the device.

### Screenshots or videos

![Screenshot_20220828_203328_sh ppy osulazer](https://user-images.githubusercontent.com/75596775/187074518-648936c6-868e-4b8e-bc91-ca9e41ced080.jpg)

### Version

2022.821.0

### Logs

[database.log](https://github.com/ppy/osu/files/9439675/database.log)
[network.log](https://github.com/ppy/osu/files/9439677/network.log)
[performance.log](https://github.com/ppy/osu/files/9439678/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9439679/runtime.log)

**Comment by bdach** [comment]
Already fixed in #19906. Next release will be fine.
