### ISSUE TITLE
Nomode scores is still not submiting (Relax scores are not overwriten). Peppy, don't close this while this issue is still active (It's obviously is not "score processing" all these days...)

### ISSUE THREAD

**Issue by okolenmi** [ppy/osu#20018]
### Type

Game behaviour

### Bug description

For example, I have an old relax score ~1 180 000 (now it's displayed like 59 000). All my nomode scores that have score less than it will be NOT submited. Example on screens. 

### Screenshots or videos

![osu_2022-08-29_17-17-59](https://user-images.githubusercontent.com/55319814/187224598-de50475a-7505-477b-9195-06c5346ffb82.jpg)
![osu_2022-08-29_17-18-28](https://user-images.githubusercontent.com/55319814/187224639-845ad090-a529-480a-af1d-5a1c6d12d177.jpg)

### Version

osu! 2022-821.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9445360/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9445361/updater.log)
[database.log](https://github.com/ppy/osu/files/9445363/database.log)
[network.log](https://github.com/ppy/osu/files/9445364/network.log)
[performance.log](https://github.com/ppy/osu/files/9445365/performance.log)

**Comment by peppy** [comment]
Please do not do this. We are working on the issue and it will be resolved in time.
