### ISSUE TITLE
Random loud audio crackle upon clicking "View Results" in playlists

### ISSUE THREAD

**Issue by TomG16** [ppy/osu#20017]
### Type

Game behaviour

### Bug description

A varying in loudness click/crackle can be heard upon clicking the "View Results" button of a song in playlists.

-It varies between to a loud click to sometimes not even noticeable. Also happens with music/effects _ON_

### Screenshots or videos

https://user-images.githubusercontent.com/90901143/187214855-6b5c3267-c827-40af-a2f3-f63d6d924c01.mp4

### Version

2022.821.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/9445033/runtime.log)
[network.log](https://github.com/ppy/osu/files/9445034/network.log)
[updater.log](https://github.com/ppy/osu/files/9445036/updater.log)
[performance.log](https://github.com/ppy/osu/files/9445037/performance.log)
[database.log](https://github.com/ppy/osu/files/9445038/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9445039/legacy-ipc.log)

**Comment by smoogipoo** [comment]
Sounds like the sample is potentially played with 100% volume for one frame or something.

**Comment by peppy** [comment]
Looks to be related to `DrawableAudioMixer` (https://github.com/ppy/osu/blob/475679ca66da4f34051d14c52b0f01b9e5704920/osu.Game/Screens/Ranking/ScorePanel.cs#L102). Changing this to an `AudioContainer` fixes the issue.

I'll take a brief journey to see if I can figure the underlying cause, but I don't actually think a mixer is appropriate or required here.

**Comment by peppy** [comment]
This happens without any sample playback. Just having the `CreateMixer` calls is enough.
