### ISSUE TITLE
Beatmap editor error

### ISSUE THREAD

**Issue by SadBoy0055** [ppy/osu#20046]
### Type

Game behaviour

### Bug description

it gave this error when trying to create beatmap

### Screenshots or videos

![Screenshot_2022-08-31-11-58-18-918_sh ppy osulazer](https://user-images.githubusercontent.com/87833130/187653525-d1c1bc14-80e1-4048-a134-242106f50887.jpg)

### Version

2022.821.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/fil
[network.log](https://github.com/ppy/osu/files/9460564/network.log)
es/9460561/runtime.log)
[performance.log](https://github.com/ppy/
[Uploading database.log…]()
osu/files/9460563/performance.log)

**Comment by toadsworth-jr** [comment]
https://github.com/ppy/osu/pull/19906
