### ISSUE TITLE
Main menu icons don't bounce after certain track changes

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#20059]
### Type

Game behaviour

### Bug description

As title. They seem to work only at startup (with the intro) and when the track is paused.

### Screenshots or videos

https://user-images.githubusercontent.com/43073074/187868553-b5ee0842-4303-466c-8b12-b7a2a1333781.mp4

### Version

2022.901.0-lazer

### Logs

.

**Comment by novialriptide** [comment]
<img width="866" alt="image" src="https://user-images.githubusercontent.com/35881688/187870308-9848a095-507d-40a7-bcab-af7f02c7149e.png">
Looking through the code of `osu.Game\Screens\Menu\MainMenuButton.cs`, it looks like this is an intended feature as the function's name is `OnNewBeat()`

**Comment by Gabixel** [comment]
The same problem also seems to occur with caret in textboxes, since they should follow the bpm of the track

**Comment by novialriptide** [comment]
Hi, I'll be taking a look into this issue.

**Comment by FongFong1231** [comment]
Hello I've also found out issue from the video also related with this issue.
there no sound when hovering on the big big circle, my ear feel nothing
Uploading bug1.mp4…

**Comment by Gabixel** [comment]
I meant exactly that in my previous comment. Thank you for showing it on video.
It's interesting to know that if you select the basic empty beatmap (the one with the title "no beatmaps available!"), for example by doing an empty search, the problem fixes itself.

**Comment by Gabixel** [comment]
It seems to be happening again, so far I could only test on Android though:

https://user-images.githubusercontent.com/43073074/202845583-a8da795c-2ee3-4f47-a54f-616cd1d641b1.mp4

It seems to happen only with certain beatmaps by interacting with the carousel, not by simply changing maps from the player in the toolbar.

**Comment by Gabixel** [comment]
I'm beginning to think that this thread may not notify any developer (since it has been closed, and they are no longer participants).
Instead of deciding who to ping, there already seems to be an active thread about the same problem, but on a larger scale (https://github.com/ppy/osu/issues/21069).
