### ISSUE TITLE
Special key in mania shows as the first key in key overlay

### ISSUE THREAD

**Issue by Doksha** [ppy/osu#20055]
### Type

Cosmetic

### Bug description

When playing an odd width mania map (3k, 5k, 7k, and 9k) the middle key is a "special" key. In the key overlay the special key is designated to "B2" while all non special keys are dedicated to B11-B20 causing B2 to always be sorted to the first spot.

### Version

2022.821.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9466163/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9466164/updater.log)
[database.log](https://github.com/ppy/osu/files/9466165/database.log)
[network.log](https://github.com/ppy/osu/files/9466166/network.log)
[performance.log](https://github.com/ppy/osu/files/9466167/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/9466168/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9466169/performance-update.log)

**Comment by smoogipoo** [comment]
Yes, it isn't supported yet https://github.com/ppy/osu/issues/2203
