### ISSUE TITLE
Scrolling through beatmaps within song select menu breaks the song select carousel

### ISSUE THREAD

**Issue by 0x84f** [ppy/osu#20062]
### Type

Game behaviour

### Bug description

Noticed the issue while writing about #20060 
Scrolling through song select with the right-left arrows (beatmap select) causes the carousel to stop scrolling in the direction it was scrolling towards already. You also cannot move in that direction anymore until you randomly select a song with F2

### Screenshots or videos

https://user-images.githubusercontent.com/24534022/187872726-7ece2d25-5615-4884-b306-f8c5c968f7e7.mp4

### Version

2022.901.0

### Logs

[client.zip](https://github.com/ppy/osu/files/9468414/client.zip)
[database.log](https://github.com/ppy/osu/files/9468415/database.log)
[network.log](https://github.com/ppy/osu/files/9468416/network.log)
[performance.log](https://github.com/ppy/osu/files/9468417/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9468419/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9468420/updater.log)

**Comment by 0x84f** [comment]
Seems like this might be related to the "Date Ranked" sorting as I can only reproduce the issue while sorting like that:

https://user-images.githubusercontent.com/24534022/187877044-625c138f-74d8-4bba-90c1-007b0f55979c.mp4

I tested all sorting types and I could only reproduce with date ranked selected

**Comment by peppy** [comment]
Tracking via https://github.com/ppy/osu/issues/20064.

You can avoid this by changing your sort mode for now.
