### ISSUE TITLE
I can't launch osu!lazer. Game crashed

### ISSUE THREAD

**Issue by NG-Kurayoru** [ppy/osu#2006]
Hello ! I have a little problem with osu!lazer.

The first time i lauched osu!lazer (the ver 2018.127.0), he works fine. But, after, i wanted to relaunch  osu!lazer... and he crashed ! My PC tells me : "osu!lazer stopped working" or something like that... I am sorry if my english is weird, i am french.

And the 1st Frebrary, i seen that a new wersion of osu!lazer was avalaible ! i redownloaded it, retry and... Same error. he crashed. I don't know what to do to fix this little error.

Can you help me ?

**Comment by peppy** [comment]
Not without you telling us why it crashed (error logs etc)
