### ISSUE TITLE
Game crashes when scrolling through difficulties

### ISSUE THREAD

**Issue by 0x84f** [ppy/osu#20060]
### Type

Crash to desktop

### Bug description

Just decided to play the game and experienced a crash

### Screenshots or videos

https://user-images.githubusercontent.com/24534022/187871209-a8c36385-ed92-4439-93a1-22afbf89bf25.mp4

### Version

2022.901.0

### Logs

[performance.log](https://github.com/ppy/osu/files/9468222/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9468223/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9468224/updater.log)
[database.log](https://github.com/ppy/osu/files/9468225/database.log)
[network.log](https://github.com/ppy/osu/files/9468226/network.log)

**Comment by peppy** [comment]
Please attach your `client.realm` file.

**Comment by 0x84f** [comment]
https://2127.s-ul.eu/WWCCsIoQ.realm
sorry, Github "doesn't support that file type"

**Comment by peppy** [comment]
Thanks. For future reference you can zip the file first.

**Comment by 0x84f** [comment]
Also, when scrolling with the left-right arrows (beatmap select), this happens: 
![image](https://user-images.githubusercontent.com/24534022/187872154-51197b4c-49be-432a-baa2-f867d74f055c.png)
Does this constitute for another issue raised or can it be left here?

**Comment by 0x84f** [comment]
Figured a video might explain better what's happening
https://user-images.githubusercontent.com/24534022/187872726-7ece2d25-5615-4884-b306-f8c5c968f7e7.mp4

**Comment by 0x84f** [comment]
Got event viewer logs, might be helpful 
[osu crash.zip](https://github.com/ppy/osu/files/9468565/osu.crash.zip)

**Comment by peppy** [comment]
Tracking via https://github.com/ppy/osu/issues/20064.

You can avoid this by changing your sort mode for now.
