### ISSUE TITLE
Some scores are incorrectly indicated as 1,000,000.

### ISSUE THREAD

**Issue by isuewo** [ppy/osu#20068]
### Type

Other

### Bug description

Multiple scores on this map are incorrectly indicated as 1,000,000 (see the screenshots for reference).

### Screenshots or videos

![osu_2022-09-01_13-36-40](https://user-images.githubusercontent.com/53264315/187905467-796afb21-515a-4a86-9ccc-9ac97b836891.jpg)
![osu_2022-09-01_13-40-13](https://user-images.githubusercontent.com/53264315/187905472-233db519-123c-4166-b718-9435b59f3c13.jpg)

### Version

2022.901.0

### Logs

[database.log](https://github.com/ppy/osu/files/9469457/database.log)
[performance.log](https://github.com/ppy/osu/files/9469458/performance.log)
[network.log](https://github.com/ppy/osu/files/9469459/network.log)
[runtime.log](https://github.com/ppy/osu/files/9469460/runtime.log)

**Comment by integerrr** [comment]
#20058
