### ISSUE TITLE
Searching for beatmaps within song selection menu breaks song selection carousel

### ISSUE THREAD

**Issue by 0x84f** [ppy/osu#20061]
### Type

Game behaviour

### Bug description
When searching anything within song selection the carousel breaks and doesn't let you move
Wanted to see game behaviour after posting #20060

### Screenshots or videos

https://user-images.githubusercontent.com/24534022/187874912-6fc02f44-67f2-4170-9464-a71c57afcee3.mp4

### Version

2022.901.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/9468353/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9468354/updater.log)
[database.log](https://github.com/ppy/osu/files/9468355/database.log)
[network.log](https://github.com/ppy/osu/files/9468356/network.log)
[performance.log](https://github.com/ppy/osu/files/9468357/performance.log)
[client.zip](https://github.com/ppy/osu/files/9468363/client.zip)

**Comment by peppy** [comment]
Tracking via https://github.com/ppy/osu/issues/20064.

You can avoid this by changing your sort mode for now.
