### ISSUE TITLE
Can't run osu! on Huawei P40 Lite

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#20078]
### Type

Crash to desktop

### Bug description

.

### Screenshots or videos

https://user-images.githubusercontent.com/86934170/187963595-1deeea97-c370-4700-b9d8-a1a3abad6bc9.mp4

### Version

901

### Logs

There are no any log records

**Comment by toadsworth-jr** [comment]
Yeah, the android release was recalled because of that same issue.
Read the release post.
