### ISSUE TITLE
No record line in internal browser

### ISSUE THREAD

**Issue by ZanyJester** [ppy/osu#20112]
### Type

Cosmetic

### Bug description

There is no line of my record in the map where it was set in the internal browser in the Laser.

### Screenshots or videos

![изображение](https://user-images.githubusercontent.com/40006523/188274796-5641cced-a2a9-4bea-be76-88d51873edfe.png)
![изображение](https://user-images.githubusercontent.com/40006523/188274814-e0029906-d32d-428d-bde7-ef6988d30e87.png)

### Version

2022.902.1

### Logs

[database.log](https://github.com/ppy/osu/files/9482822/database.log)
[network.log](https://github.com/ppy/osu/files/9482823/network.log)
[performance.log](https://github.com/ppy/osu/files/9482824/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9482825/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9482826/updater.log)

**Comment by peppy** [comment]
Please set a score via osu!(lazer). For now, leaderboards are split apart. This is as intended.
