### ISSUE TITLE
Storyboard can display incorrectly on maps with 4:3 background

### ISSUE THREAD

**Issue by uku3lig** [ppy/osu#20110]
### Type

Game behaviour

### Bug description

On certain maps (ex. [Scarlet Rose (131564)](https://osu.ppy.sh/b/131564)) with a 4:3 background, the background will be adapted to fit on 16:9 displays, potentially causing discrepancies with osu!stable.

### Screenshots or videos

osu!stable behavior:

![stable](https://user-images.githubusercontent.com/61147779/188273299-0da4367f-d420-4c0f-a4eb-b793aba00b95.png)

osu!lazer behavior:

![lazer](https://user-images.githubusercontent.com/61147779/188273374-73454f24-d77b-47c7-b34c-f695de4207d1.png)

### Version

2022.902.1-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/9482710/network.log)
[performance.log](https://github.com/ppy/osu/files/9482711/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9482712/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9482713/updater.log)
[database.log](https://github.com/ppy/osu/files/9482714/database.log)

**Comment by Walavouchey** [comment]
https://github.com/ppy/osu/issues/2086
