### ISSUE TITLE
Cursor behaves weirdly when cmd-tabbing on MacOS

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu#20118]
### Type

Game behaviour

### Bug description

This only occurs when using a tablet, and the effect is much more extreme when your osu tablet mapping is different from your driver tablet mapping. This also occurs when when opening the screenshot app.

### Screenshots or videos

https://user-images.githubusercontent.com/100527514/188289641-8b1ee200-492c-4db9-9ed3-d0db24545a75.mov

### Version

2022.902.1

### Logs

[database.log](https://github.com/ppy/osu/files/9483480/database.log)
[network.log](https://github.com/ppy/osu/files/9483481/network.log)
[performance.log](https://github.com/ppy/osu/files/9483482/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9483483/runtime.log)

**Comment by Non-Binary-Programmer** [comment]
Note this only occurs when using tablet.

**Comment by peppy** [comment]
Please use borderless or windowed mode.

Fullscreen on macOS is using a super legacy call and will probably be removed in the future (especially as we move to metal).

**Comment by Non-Binary-Programmer** [comment]
I am using borderless mode.

**Comment by Non-Binary-Programmer** [comment]
https://user-images.githubusercontent.com/100527514/188295495-5446d6ae-21e9-47b0-8ae4-506177915f61.mov

**Comment by peppy** [comment]
Then what you are seeing is the OS tablet driver outputting mouse movement. I don't think we can't do anything about this.

If you're not using your tablet at an OS level, you can uninstall the driver to potentially avoid this. Or you might be able to use karabiner elements to disable it as a cursor device.

**Comment by Non-Binary-Programmer** [comment]
I am using my tablet for other things, so I won't install my OS level drivers. Unfortunate you can't fix this.

**Comment by peppy** [comment]
To confirm, you can still `cmd-tab-tab-tab` to get to the app you want to using keyboard only yeah? It shouldn't impede your ability to get away from osu!.

**Comment by Non-Binary-Programmer** [comment]
Correct. The only problem is that the cursor is visually buggy.
