### ISSUE TITLE
Hovering cursor above fullscreen window causes problems on MacOS

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu#20117]
### Type

Game behaviour

### Bug description

If using mouse, the game cursor suddenly snaps lower and then follows the os cursor. If using tablet, the game cursor fights the os cursor.

### Screenshots or videos

Mouse: 

https://user-images.githubusercontent.com/100527514/188288995-f939410e-4e6a-4cf8-9ee9-c5050f33a090.mov

Tablet: 

https://user-images.githubusercontent.com/100527514/188289031-276ff742-9903-4111-bd48-d811e37d7937.mov

### Version

2022.902.1

### Logs

[database.log](https://github.com/ppy/osu/files/9483463/database.log)
[network.log](https://github.com/ppy/osu/files/9483464/network.log)
[performance.log](https://github.com/ppy/osu/files/9483465/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9483466/runtime.log)

**Comment by peppy** [comment]
Please use borderless or windowed mode.

Fullscreen on macOS is using a super legacy call and will probably be removed in the future (especially as we move to metal).

**Comment by Non-Binary-Programmer** [comment]
I'm sorry for using the word fullscreen, I was using borderless mode and just said fullscreen because I forgot there was a difference.

Regardless, this is probably the same underlying issue as #20118
