### ISSUE TITLE
Storyboard sprites that display in stable not working in lazer

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu#20125]
### Type

Other

### Bug description

On the storyboard for this map for the triangles contest: https://osu.ppy.sh/beatmapsets/1841845#osu/3783132

Starting at 00:24:765 - , multiple triangles are supposed to appear with a rotation command, then scale up in unison to fill the screen. On stable, this works fine. On lazer, only the first triangle of the 15 triangles appears.

I am not entirely sure what is causing this issue only on lazer after reviewing it.

The triangle sprites affected are called "innie.png" and start on line 1277 of the .osb on the linked mapset.

### Screenshots or videos

https://user-images.githubusercontent.com/33286824/188314971-b6d27509-6b65-417c-9aee-b16ec7bc1c7a.mp4

### Version

2022.902.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/9484764/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9484765/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9484766/updater.log)
[database.log](https://github.com/ppy/osu/files/9484767/database.log)
[debug.log](https://github.com/ppy/osu/files/9484768/debug.log)
[network.log](https://github.com/ppy/osu/files/9484769/network.log)

**Comment by Apiichu** [comment]
Looking at these sprites in osb code I noticed that some commands have extra spaces before the command. 
![image](https://user-images.githubusercontent.com/25745108/188516129-ff953ce4-0220-49fa-b892-03b0e07a8fb8.png)
^sprite of moving triangle in 三角形.tar.gz's map
![image](https://user-images.githubusercontent.com/25745108/188516247-2d13a545-3a87-443f-b737-a77ad1aee2cf.png)
^triangle sprites in Crush the Candy Boys' map. (the bottom sprite is the middle triangle which seem to not disappear which doesn't have additional spaces)

I haven't tested this but I think that these extra spaces are likely causing this.

**Comment by NoffyNoffeh** [comment]
"extra" spaces are the required formatting for using Loop commands, they indicate they are nested in the loop in the script.

If the problems are from loop commands being broken on Lazer that sounds pretty concerning.

Also as mentioned the problem sprites start at 1277 in my osb, the ones you highlighted are working just fine and also use loops. It's the ones below that don't appear.

**Comment by Apiichu** [comment]
Oh my bad didn't know that they were loops lol.

**Comment by Fisky1** [comment]
we managed to fix our issue

the triggers & loops had higher priority than regular commands, is the info i got
so they made a workaround with that in mind

i dont know sb stuff but hope this makes sense

**Comment by peppy** [comment]
@NoffyNoffeh as a workaround (if you want to make your storyboard work before the next release), you can add this line:

<img width="564" alt="iTerm2 2022-09-06 at 15 30 07@2x" src="https://user-images.githubusercontent.com/191335/188675664-0699a82f-80f7-41e0-8e2f-b5d43e983882.png">

to anywhere that is affected. basically you need a fade at the top level (outside the loop) giving the initial time for display.

**Comment by peppy** [comment]
> the triggers & loops had higher priority than regular commands, is the info i got so they made a workaround with that in mind
> 
> i dont know sb stuff but hope this makes sense

Yes, this has been fixed but will take a week or so to be released. You have the right gist. The issue is along the same lines as explained above. You can resolve by adding alpha=0 lines to the top level (non-loop).
