### ISSUE TITLE
performance drops dramatically temporarily after cancelled beatmap import operation

### ISSUE THREAD

**Issue by approachcircle** [ppy/osu#20120]
### Type

Performance

### Bug description

if the beatmap import task is stopped before it has completed, performance will drop severely, and only returns to normal after the beatmap task resolves as completed by just importing the beatmaps that it could before it was interrupted. (performance improves again at ~0:28). this only occurs when running an unedited local build, and not on a release build.

### Screenshots or videos

https://user-images.githubusercontent.com/58401347/188293372-4d2412e2-edc8-4921-bd46-2e2bcf1cc66f.mp4

### Version

local development build

### Logs

[performance.log](https://github.com/ppy/osu/files/9483660/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9483661/runtime.log)
[database.log](https://github.com/ppy/osu/files/9483662/database.log)
[network.log](https://github.com/ppy/osu/files/9483663/network.log)

**Comment by smoogipoo** [comment]
Yes, because you're running with debugger attached. This will be alleviated by https://github.com/ppy/osu/pull/20136 but please don't report performance issues with dev builds unless.
