### ISSUE TITLE
Max combo is sometimes shown as 0

### ISSUE THREAD

**Issue by Dragon77mathbye** [ppy/osu#20138]
### Type

Cosmetic

### Bug description

The max combo on the score display is sometimes displayed as 0.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/74103504/188358085-a30ce121-6aff-406e-b3dc-2c2dd3703d44.png)

### Version

2022.902.1

### Logs

[performance.log](https://github.com/ppy/osu/files/9486586/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9486587/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9486588/updater.log)
[database.log](https://github.com/ppy/osu/files/9486589/database.log)
[network.log](https://github.com/ppy/osu/files/9486590/network.log)

**Comment by Dragon77mathbye** [comment]
This only appears to happen for local scores

**Comment by smoogipoo** [comment]
https://github.com/ppy/osu/discussions/20088
