### ISSUE TITLE
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue

### ISSUE THREAD

**Issue by DecoyIV** [ppy/osu#2014]
Played a beatmap and failed, hit the retry button and this happend

![e59ed15f92ab0b778f26ee070aef36a2](https://user-images.githubusercontent.com/36089309/35757663-35bf4914-083e-11e8-966a-aae1cf6f4449.png)

**Comment by LittleEndu** [comment]
Close in favour of #2158 ?

**Comment by peppy** [comment]
Duplicate of #2158
