### ISSUE TITLE
Spectate not working (gameplay frozen at spectator mode)

### ISSUE THREAD

**Issue by BurningFlames2314** [ppy/osu#20151]
### Type

Game behaviour

### Bug description

Ive tried restarting osu! but the bug still persist. replay works just fine tho

### Screenshots or videos

https://user-images.githubusercontent.com/104247330/188515367-03362de0-8e67-4d0d-8e69-3353e9d7af28.mp4

### Version

2022.902.1

### Logs

[database.log](https://github.com/ppy/osu/files/9492111/database.log)
[network.log](https://github.com/ppy/osu/files/9492114/network.log)
[performance.log](https://github.com/ppy/osu/files/9492115/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9492116/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9492117/updater.log)

**Comment by BurningFlames2314** [comment]
nvm, turns out its just a really long delay before starting? it takes like 10 seconds for of frozen gameplay for it to finally load, not like before where it automatically starts

**Comment by peppy** [comment]
Please provide another video showing the gameplay eventually starting.

Also please try spectating an already running gameplay session and see if it behaves differently.

**Comment by BurningFlames2314** [comment]
https://youtu.be/tt66CqMViDc

heres the link to the video :/ the 10mb file size really sucks lol also sorry for the late reply, been quite busy

**Comment by taep96** [comment]
I think this can be closed

**Comment by Joehuu** [comment]
Fixed by https://github.com/ppy/osu/pull/24451.
