### ISSUE TITLE
Sprites using vector scale with width 0 are visible in lazer

### ISSUE THREAD

**Issue by Apiichu** [ppy/osu#20155]
### Type

Other

### Bug description

Sprites having a width of 0 but a height of some value are invisible in stable, but in lazer they are visible. 

### Screenshots or videos

stable
![image](https://user-images.githubusercontent.com/25745108/188573237-cd1f4623-2e3e-4ca3-8a7b-cb442caff895.png)
lazer
![image](https://user-images.githubusercontent.com/25745108/188573343-7bbe2229-a937-4411-860d-46a0a7c41a1a.png)
osb code
![image](https://user-images.githubusercontent.com/25745108/188573494-dd9e1dfa-8ea6-481f-8579-e55b0318899d.png)

### Version

2022.902.1

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/9494264/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9494265/network.log)
[performance.log](https://github.com/ppy/osu/files/9494266/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9494268/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9494269/updater.log)
[database.log](https://github.com/ppy/osu/files/9494270/database.log)

**Comment by peppy** [comment]
What's the use case here? Does the width eventually get animated from zero to a higher value?

If possible can you provide the actual `osb` file as an attachment (you can zip it if it won't attach) or link to a beatmap / timestamp where this occurs?

**Comment by peppy** [comment]
Also can you confirm that you were able to work around this in your beatmap (I think that's what I heard), and if so, what the workaround was (so I don't break it accidentally).

**Comment by Apiichu** [comment]
> What's the use case here? Does the width eventually get animated from zero to a higher value?
> 
> If possible can you provide the actual `osb` file as an attachment (you can zip it if it won't attach) or link to a beatmap / timestamp where this occurs?
> 
> Please also provide the `png` file which is causing this issue. I can't immediately reproduce what you're seeing.

1. Yes it eventually is animated.
2. this is the beatmap of the screenshots
[beatmap-637980146129304734-1-minute-of-silence.zip](https://github.com/ppy/osu/files/9495163/beatmap-637980146129304734-1-minute-of-silence.zip)
3. I don't really understand what you mean?

> Also can you confirm that you were able to work around this in your beatmap (I think that's what I heard), and if so, what the workaround was (so I don't break it accidentally).

The workaround was to just have the sprite have scale 0 by 0 before the scale animation starts. The issue was affecting a triangle text animation but I thought it was fixed cuz the letter "G" was fixed. But now when the osb is uploaded with it applied to all letters it seems the letter "R" is not fixed hmm. I can send screenshots and the beatmap, should I sent here or create a new issue?
