### ISSUE TITLE
Leaderboard scorecards have inconsistent pp values

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu#20167]
### Type

Game behaviour

### Bug description

When viewing leaderboard cards at the end of a play or after clicking on the leaderboard in game, the pp value shown on the card is different from the pp value shown in the performance breakdown to the right of the card. However, this does not occur if the card you are viewing is for a local replay (generated by clicking on a replay in the local leaderboard or for a play you just completed).

### Screenshots or videos

<img width="1512" alt="Screen Shot 2022-09-06 at 3 55 59 PM" src="https://user-images.githubusercontent.com/100527514/188754873-6c030728-6572-4214-9241-89bc1afde612.png">

### Version

2022.902.1

### Logs

[database.log](https://github.com/ppy/osu/files/9501395/database.log)
[network.log](https://github.com/ppy/osu/files/9501396/network.log)
[performance.log](https://github.com/ppy/osu/files/9501397/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9501398/runtime.log)

**Comment by peppy** [comment]
The pp algorithm is constantly changing. Currently lazer tracks these changes directly, while the server does not.

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/issues/19386
