### ISSUE TITLE
Score Multiplier & Spinner Bonus Score Problem

### ISSUE THREAD

**Issue by ZapTech43** [ppy/osu#2016]
So i tried to play But i see something strange like "why did i get a lot of score?" Not like in original osu! the score on osu!lazer is too much 
Here's A Sample of it : 

![too many scores](https://user-images.githubusercontent.com/30797591/35764085-483c2824-08ec-11e8-936e-b8ed9f6df1ba.png)

And one more problem the spinner after i pass it i should get a bonus but i didn't get the bonus 
Here's A Sample of it :

![spinner bonus score unavailable](https://user-images.githubusercontent.com/30797591/35764084-47deedbc-08ec-11e8-8ee5-8726fbfa64bd.png)

![after spinner score](https://user-images.githubusercontent.com/30797591/35764083-47246816-08ec-11e8-8a45-dbb6cafb3c43.png)

(I Did played it on windowed so it will be easy to get out the problem still exists in fullscreen)
Beatmap I Played for this : 
 - https://osu.ppy.sh/beatmapsets/401790 (For The Score Problem)
 - https://osu.ppy.sh/beatmapsets/440997 (For The Spinner Problem)

**Comment by peppy** [comment]
Scoring is different on lazer compared to stable. Also lazer is a work in progress, with things like spinner bonuses yet to be implemented.
