### ISSUE TITLE
Beatmap listing rarely shows same song twice

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#20170]
Not sure on the cause of this one. Maybe our side, maybe osu-web.

### Discussed in https://github.com/ppy/osu/discussions/20169

<div type='discussions-op-text'>

<sup>Originally posted by **Non-Binary-Programmer** September  7, 2022</sup>
### Type

Game behaviour

### Bug description

Rarely, the beatmap listing will show two copies of the same song. Additionally, when you begin to download one the other also shows the download progress.

This has only happened for me with the beatmap of [CORE](https://osu.ppy.sh/beatmapsets/481511#osu/1271279), and it is inconsistent.

### Screenshots or videos

<img width="1128" alt="Screen Shot 2022-09-06 at 2 50 27 PM" src="https://user-images.githubusercontent.com/100527514/188748019-83a75648-5be4-4b1e-aa85-4e9aa49080f2.png">
(When hovered or clicked on, the beatmaps are exactly identical)

### Version

2022.902.1

### Logs

[database.log](https://github.com/ppy/osu/files/9501118/database.log)
[network.log](https://github.com/ppy/osu/files/9501119/network.log)
[performance.log](https://github.com/ppy/osu/files/9501120/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9501121/runtime.log)
</div>

**Comment by Non-Binary-Programmer** [comment]
<img width="1089" alt="Screen Shot 2022-10-27 at 8 42 13 PM" src="https://user-images.githubusercontent.com/100527514/198497378-a6be6e51-956e-4242-b05e-c7b4fc1d5b85.png">
The issue has returned (ver. 2022.1022.0-lazer)

[database.log](https://github.com/ppy/osu/files/9885065/database.log)
[input.log](https://github.com/ppy/osu/files/9885066/input.log)
[network.log](https://github.com/ppy/osu/files/9885067/network.log)
[performance.log](https://github.com/ppy/osu/files/9885068/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9885069/runtime.log)

**Comment by peppy** [comment]
This is still open and tracked at osu-web (ppy/osu-web#9270) for what that's worth.

**Comment by frenzibyte** [comment]
That's weird, if the beatmaps are equivalent and failed the LINQ distinct operation, then the game would've crashed the moment both of them are added to the listing...
