### ISSUE TITLE
Selecting time changing mods after leaving to main menu also selects unselected mods

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2018]
Sorry, don't know how to word it better.

I selected EZ, HT, HD then left to main menu. When I went back to mod select, selecting HT would also reselect EZ and HD even if they were unselected.

Happens with most mods when selecting HT or DT. Sometimes selecting EZ or HR will also reselect DT. 

Doesn't happen all the time. After restarting I had to close to menu 3 times before this weird behavior started again.

**Comment by Frontear** [comment]
Does this error occurred with any other mods? (Attempt to toggle, say hidden. Does the error reselect all other mods?)

**Comment by LittleEndu** [comment]
Upon further checking it, it seems to happen with all mods that have secondary mod (so SD, HT and DT and mania keys, but not Auto as it doesn't have Cinema in lazer)
It only reselects mods that were selected before. (So if before I only selected HD it will only reselect HD)
With EZ and HR it seems to only reselect HT or DT.

It thought it was a regression due to recent changes made with time changing mods, but it doesn't seem to be the case.

**Comment by peppy** [comment]
See #2046 for screen capture reproduction if needed.
