### ISSUE TITLE
Crash upon deleting notes on same timestamp in editor

### ISSUE THREAD

**Issue by Axilotl17** [ppy/osu#20185]
### Type

Crash to desktop

### Bug description

sometimes when you delete notes stacked in the editor timeline, your game crashes.

### Screenshots or videos

stacked notes
deleting these sometimes crashes game. 
![image](https://user-images.githubusercontent.com/78441708/189000785-8159dd91-ca37-444a-8b20-4eb258fa7189.png)

### Version

2022.902.1-lazer

### Logs

[logs.zip](https://github.com/ppy/osu/files/9522162/logs.zip)

**Comment by Axilotl17** [comment]
i thought this was fixed but apparently it wasn't.

**Comment by MegamiKato** [comment]
Issue can be reproduced on my end

Crash to desktop, on 2022.902.1

On 165 BPM and 4/4

**Comment by peppy** [comment]
Duplicate of https://github.com/ppy/osu/issues/20019
