### ISSUE TITLE
Main menu icons no longer animate after failing a song

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#20193]
Can repro on 9aab502adcc6e61bb675eafcfaf5368f828e1ab8

### Discussed in https://github.com/ppy/osu/discussions/20192

<div type='discussions-op-text'>

<sup>Originally posted by **TheEggo** September  8, 2022</sup>
When exiting a song, objects that would usually pulse to the bpm seem to just be stuck (e.g osu! logo, menu icons etc)

https://user-images.githubusercontent.com/64386789/189114176-a47717d8-0842-4fef-8c7a-b51095cd5b5a.mp4

</div>

**Comment by sw1tchbl4d3r** [comment]
This also happens when simply exiting the song via the pause menu without failing, and gets fixed by selecting another song, to avoid looking in the wrong places.
