### ISSUE TITLE
Notifications stay visible during gameplay

### ISSUE THREAD

**Issue by Cyliann** [ppy/osu#20197]
### Type

Cosmetic

### Bug description

If notification pops up and imidiately after this you start a beatmap, the notification stays on for quite a while and limits visibility.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/33868960/189191980-b72273b7-a5a0-4641-a6df-47ff422664c3.png)

### Version

2022.902.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9529501/database.log)
[network.log](https://github.com/ppy/osu/files/9529502/network.log)
[performance.log](https://github.com/ppy/osu/files/9529503/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9529504/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9529505/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9529506/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9529507/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9529508/updater.log)

**Comment by peppy** [comment]
You can click them to close them.

**Comment by Cyliann** [comment]
I know that, but I think they should close automatically as soon as you start a beatmap.

**Comment by Drison64** [comment]
Hi, I would like some input on this.

Do you think it would be better to:

- just hide the notifications when you play, and show them again as soon as you pause
- make an indicator in the top right corner of the screen that there is an unread notification when you play. As soon as you pause, the notifications, that did not get to stay on the screen for their intended time, will pop up.

**Comment by Cyliann** [comment]
I think the first one is less intrusive

**Comment by peppy** [comment]
There is already logic to not post new notifications during gameplay.

If we are doing *anything* here, it should be forwarding all toasts to the notification tray on entering gameplay. Nothing else.
