### ISSUE TITLE
Old local scores are sometimes higher than possible

### ISSUE THREAD

**Issue by Dragon77mathbye** [ppy/osu#20201]
### Type

Cosmetic

### Bug description

Scores made in stable are sometimes shown with a much higher score than they should be shown as.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/74103504/189251577-bffbf0a3-97d2-4664-afd9-561297f4fa30.png)
![image](https://user-images.githubusercontent.com/74103504/189251704-800887aa-5f5c-4239-964f-8194675635dd.png)
![image](https://user-images.githubusercontent.com/74103504/189251775-92165628-808b-4099-9af0-523b499f9a9c.png)

### Version

2022.902.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/9531555/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9531556/updater.log)
[database.log](https://github.com/ppy/osu/files/9531557/database.log)
[network.log](https://github.com/ppy/osu/files/9531558/network.log)
[performance.log](https://github.com/ppy/osu/files/9531559/performance.log)

**Comment by peppy** [comment]
Probably covered by #20200 etc?

**Comment by smoogipoo** [comment]
@Dragon77mathbye can you check if these scores display correctly now?

**Comment by Dragon77mathbye** [comment]
They seem fine now
