### ISSUE TITLE
Shift input being handled incorrectly after both shift keys are held down at the same time

### ISSUE THREAD

**Issue by nbvdkamp** [ppy/osu#2022]
After having held down both shift keys at the same time the shift input will continually be given. If you for example press and then release both shift keys and then start a catch map dash will be on immediately and stay on. This input stays on until the shift key that was pressed second is pressed and released again. 

The issue seems to be exclusive to the shift keys and doesn't occur with control or alt. It also doesn't affect textboxes, just dash and changing keybinds. (e.g. when you try to change a bind to x after triggering the bug it changes it to shift+x)

I am running windows 10 and on the latest commit of master.

**Comment by pdrapoport** [comment]
If you insert lines

```
Debug.WriteLine("!!! KEYS STATE !!!");
foreach (var k in Keys) { Debug.WriteLine(k.ToString()); }
```

After 
`Keys = all_keys.Where(tkState.IsKeyDown)` 
in file OpenTKKeyboardHandler.cs you will have this as [result](https://pastebin.com/GgD5tCbg)

Modifier keys are reported twice, but I saw this handled in InputHandler. 
And incorrect state of pressed keys is coming from Keys = all_keys.Where(tkState.IsKeyDown).

I suggest that this issue should be moved to osu-framework and labeled with openTk label.

**Comment by ticotaco72** [comment]
still reproducible

**Comment by Joehuu** [comment]
Just noting that this will be fixed after moving to SDL. Will leave open until the transition is complete.

**Comment by Joehuu** [comment]
Fixed in SDL.
