### ISSUE TITLE
Song Progress hides and appears in gameplay

### ISSUE THREAD

**Issue by agatemosu** [ppy/osu#20235]
### Type

Game behaviour

### Bug description

Sometimes the Difficulty Graph / Song Progress disappears and appears when playing

### Screenshots or videos

https://user-images.githubusercontent.com/58957468/189520955-762ac8fa-2ec7-4622-b5ed-f0a278c0dada.mp4

### Version

2022.910.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9542159/database.log)
[updater.log](https://github.com/ppy/osu/files/9542160/updater.log)
[runtime.log](https://github.com/ppy/osu/files/9542161/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9542162/performance.log)
[network.log](https://github.com/ppy/osu/files/9542163/network.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9542164/legacy-ipc.log)

**Comment by smoogipoo** [comment]
Looks like it's caused by this code changing the height of the graph ever so slightly and causing an invalidation:
https://github.com/ppy/osu/blob/aa823161f18b957d65e4bab024d10bce92e6885e/osu.Game/Screens/Play/HUD/DefaultSongProgress.cs#L176-L180
