### ISSUE TITLE
Clicking this link in the changelog make an error, and a double click crashes the game

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#20240]
### Type

Crash to desktop

### Bug description

It happens with the link of the 2022.911.0 changelog, where there's a GitHub link without number (see screenshot below). Once clicked, I got a notification "An unhandeled error has occured". Even worse, if I double click fast enough, the game crashes.

### Screenshots or videos

The only link with this issue.
![osu_2022-09-11_14-24-25](https://user-images.githubusercontent.com/57914482/189527423-29d63660-89de-4977-956c-0dc6753a737a.png)

### Version

2022.911.0

### Logs

[database.log](https://github.com/ppy/osu/files/9542503/database.log)
[network.log](https://github.com/ppy/osu/files/9542504/network.log)
[performance.log](https://github.com/ppy/osu/files/9542505/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9542506/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9542507/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9542508/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9542509/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9542510/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9542511/updater.log)

**Comment by Corne2Plum3** [comment]
On the web changelog, there isn't any link. Maybe the issue is caused by the game excepting a link but there is none, idk?

**Comment by Gabixel** [comment]
The bugfix does not appear to include a pull request ID (it should be `osu-framework#<number>`).
The interesting thing to note is that there is no trace of the parenthesized text/link on web:
![image](https://user-images.githubusercontent.com/43073074/189527856-78d9da79-555d-4b81-8abc-93e5deb95218.png)

**Comment by peppy** [comment]
I've fixed this server-side but we should guard against a crash here. PR ID *can* be null.

**Comment by agatemosu** [comment]
osu-framework#20236 does not exist
