### ISSUE TITLE
OSU! Unexpected OSU! performance drop

### ISSUE THREAD

**Issue by DeadlyFury** [ppy/osu#20251]
### Type

Performance

### Bug description

Since the past 2-3 OSU stable updates my game has started to run worst and worst the more i play, i can get a stable 3ms when i freshly boot up my laptop but after around a hour i get up to a unplayable 30ms-60ms or even worst.

laptop specs:
I7 9750h
RTX 2060 (6GB)
16 GB ram

### Screenshots or videos

![screenshot009](https://user-images.githubusercontent.com/112054099/189566635-5b16933e-4e25-4151-90cf-1ac2d17ab647.jpg)

### Version

B20220829

### Logs

[session.log](https://github.com/ppy/osu/files/9544330/session.log)
[osu!auth.log](https://github.com/ppy/osu/files/9544331/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/9544332/runtime.log)

**Comment by Coppertine** [comment]
This looks like osu stable, please report at ppy/osu-stable-issues instead

**Comment by DeadlyFury** [comment]
> This looks like osu stable, please report at ppy/osu-stable-issues instead

This is already categorised as ppy/osu-stable-issues, i just checked and it is the second newest one

**Comment by peppy** [comment]
Please check https://osu.ppy.sh/help/wiki/Performance_Troubleshooting

Nothing has changed which can affect performance on our end, so try and recall anything you hanged recently.
