### ISSUE TITLE
[lazer] Game crashes while changing into the Borderless Window Type. 

### ISSUE THREAD

**Issue by PolskiKapsel** [ppy/osu#20276]
Problem details:
Osu!lazer instantly crashes while changing from any other Window Type into Borderless. I managed to fix the game by quickly using Alt+Enter key combination, however the Error is still easily reproduceable, at least on my PC.

Video showing the problem: https://youtu.be/oY8Aniz92dg

osu! version: 2022.911.0-lazer

[logs.zip](https://github.com/ppy/osu/files/9552402/logs.zip)

**Comment by peppy** [comment]
https://github.com/ppy/osu/discussions/20275
