### ISSUE TITLE
Followpoints appear way earlier than they're supposed to

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#20335]
No doubt this is going to be animations not being reset. More examples can be found down in the discussion thread.

### Discussed in https://github.com/ppy/osu/discussions/19807

<div type='discussions-op-text'>

<sup>Originally posted by **Flamiii** August 17, 2022</sup>
This has been something that has been very noticeable for me and I'm fairly certain that this came from the 2022.810.0 update of lazer. If I had to guess I would say that this might be an unintended side effect of https://github.com/ppy/osu/pull/19587, but I'm not sure. This shouldn't be skin specific as I've tested with multiple skins and it happens with all of them.

Skin 1: https://skins.osuck.net/index.php?newsid=863
Skin 2: https://skins.osuck.net/index.php?newsid=166
Map: https://osu.ppy.sh/beatmapsets/408820#osu/887621

Some examples of them appearing way too early:

![osu_2022-08-16_19-25-39](https://user-images.githubusercontent.com/74088315/185008574-267916df-64a8-4741-bacc-76b8d563d4b3.png)
![osu_2022-08-16_19-29-38](https://user-images.githubusercontent.com/74088315/185008615-394a4386-3175-4545-aba9-565732e357e0.png)
![osu_2022-08-16_19-29-49](https://user-images.githubusercontent.com/74088315/185008946-1a06473a-0652-410f-aace-a2cef0762ab1.png)

The bottom followpoint seems bugged to me as it appears and then disappears without being visibly connected to any notes:

![osu_2022-08-16_19-33-48](https://user-images.githubusercontent.com/74088315/185008668-2c8bbfc0-1dac-4400-ba87-7bc509e968f8.png)
</div>

**Comment by peppy** [comment]
I'll look into this, it's been on my list.
