### ISSUE TITLE
Notes spawn outside of the play area

### ISSUE THREAD

**Issue by FuZ38** [ppy/osu#20341]
### Type

Game behaviour

### Bug description

Notes can spawn outside of the play area in osu!catch, making the note impossible to catch

Only happen on lazer, stable is fine

### Screenshots or videos

https://streamable.com/3jdnet

### Version

2022.911.0-lazer

### Logs

Can't find the logs folder in my osu folder

**Comment by smoogipoo** [comment]
Looks like osu!stable clamps it to the edge of the playfield but lazer doesn't. Here's how that pattern looks in both, for comparison.

Stable:
![image](https://user-images.githubusercontent.com/1329837/190610570-b26d9dbc-0c40-441e-9b80-39100a1a0f69.png)

Lazer:
![image](https://user-images.githubusercontent.com/1329837/190611094-28f6c93e-d530-454c-aa38-6849508152e1.png)
