### ISSUE TITLE
maps bugging and randomly selecting different songs

### ISSUE THREAD

**Issue by boiledcabbages** [ppy/osu#2040]
so my issue at the moment is that some maps downloaded from osu direct are bugged and simply do not work, however they don't crash the game instead they just select a random song, example of the issue can be found here https://www.youtube.com/watch?v=uMQTPHdtiNc

**Comment by Aergwyn** [comment]
I suspect the tracks loading as 0 length which causes the MusicController to select the next song when going into loading screen. Many components have unpredictable behaviour if track length is below 1.

**Comment by peppy** [comment]
Could you please provide beatmap links rather than videos?

**Comment by boiledcabbages** [comment]
thing is i was talking to someone in lazer chat and they said those maps worked fine for them so i'm thinking it might be clashes with other beatmaps and beatmap link is https://osu.ppy.sh/s/616378

**Comment by boiledcabbages** [comment]
(that's the link to the bugged map) i decided to not put up the map it defaults to because if i delete it then it either crashes osu or picks a different map.
