### ISSUE TITLE
Corrupted ranked beatmaps

### ISSUE THREAD

**Issue by sunghwan2789** [ppy/osu#2041]
I found that osu!lazer throws IOException("Unknown file format") when it decodes some ranked beatmaps.

1. https://osu.ppy.sh/b/157249
![157249th beatmap data](https://user-images.githubusercontent.com/4927894/35973475-eaddf820-0d18-11e8-9779-4f16e7318adb.png)

2. https://osu.ppy.sh/b/294291
![294291st beatmap data](https://user-images.githubusercontent.com/4927894/35973481-efbc790c-0d18-11e8-8453-be87eda2941b.png)

3. https://osu.ppy.sh/b/363416
![363416th beatmap data](https://user-images.githubusercontent.com/4927894/35973484-f3c838ec-0d18-11e8-99f5-1d9d3ef5483d.png)

They seem to be explicitly saved with notepad or somthings...

**Comment by Aergwyn** [comment]
I was on that a while ago but it was decided that these files will be fixed on the serverside for now.

**Comment by sunghwan2789** [comment]
Ah, then, damaged beatmap treated damaged is normal in osu!lazer !

**Comment by sunghwan2789** [comment]
see #1537

**Comment by sunghwan2789** [comment]
These beatmaps have not been fixed.. So I will reopen this issue..

**Comment by peppy** [comment]
Not really the correct place to report these kinds of fixes, but I will self-assign until they are fixed server-side.

**Comment by peppy** [comment]
These three maps have been fixed. I've also added safety against future uploads.

Please let me know if you track down any other broken beatmaps.
