### ISSUE TITLE
Excessive stuttering during gameplay

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#20421]
### Type

Performance

### Bug description

Stutters start only during gameplay. Happens regardless if the frame graph is shown. Occurs both in gameplay and while watching replays. No other applications besides osu!lazer are open. The previous version (2022.911.0) shows no such issue if installed.

Here are the specifications of the laptop (note that the game is running using the Intel iGPU rather than nVidia dGPU):
[DxDiag.txt](https://github.com/ppy/osu/files/9633217/DxDiag.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/53346335/191952245-ca793c78-2b04-45d5-aaaa-98d4e57abf98.mp4

### Version

2022.923.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/9633204/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9633205/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/9633207/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9633209/performance-update.log)
[performance-audio.log](https://github.com/ppy/osu/files/9633210/performance-audio.log)
[performance-input.log](https://github.com/ppy/osu/files/9633211/performance-input.log)

**Comment by peppy** [comment]
Initial guess is song progress invalidation gone wrong.

Could you try removing the song progress display using the skin editor (`ctrl`+`shift`+`s`) and see if it fixes the issue?

**Comment by Sinamer** [comment]
Can confirm removing song progress display helps resolve the stutters.

**Comment by peppy** [comment]
Great.

Also can you set your skin to the default skin (without your custom layout) and confirm that the stutters are still there?

**Comment by PercyDan54** [comment]
Can reproduce using the argon skin, removing song progress helps

**Comment by Sinamer** [comment]
Can confirm stutters happen with default skin.
![osu_2022-09-23_14-49-56](https://user-images.githubusercontent.com/53346335/191954320-318e1901-7250-42bd-a0f2-882be146ae35.png)

**Comment by NotGumballer91** [comment]
I've noticed that you don't have to remove song progress entirely. Just disabling the graph helps

![osu_2022-09-23_20-00-26](https://user-images.githubusercontent.com/64581009/191955835-b66d1873-7b97-4b7e-86a5-f44b6556cfdd.png)
![osu_2022-09-23_20-00-42](https://user-images.githubusercontent.com/64581009/191955841-577d80ff-8713-4152-8392-117e6f7811c7.png)

**Comment by peppy** [comment]
Initial investigation shows increased overhead in `Bind` / `Add` (left is newer/regressed framework):

![Parallels Desktop 2022-09-26 at 07 58 14](https://user-images.githubusercontent.com/191335/192223967-b2b1f9a8-fb49-4707-85b5-6bb9dfbe1324.png)
