### ISSUE TITLE
Notification getting stuck when flicking left 

### ISSUE THREAD

**Issue by FriendsNone** [ppy/osu#20420]
### Type

Cosmetic

### Bug description

Specifically when downloading a beatmap. When flicking it to the left, it cancels the download (which is expected) but doesn't play the animation of it getting flicked.

Somewhat hard to describe. The first video attached should explain for itself.

### Screenshots or videos

https://user-images.githubusercontent.com/4056272/191951952-1b962d68-01ec-478c-a68f-1bf19387b514.mp4

### Version

2022.923.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/9633223/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9633224/updater.log)
[database.log](https://github.com/ppy/osu/files/9633226/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9633227/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9633228/network.log)
[performance.log](https://github.com/ppy/osu/files/9633229/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/9633230/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9633231/performance-update.log)

**Comment by peppy** [comment]
It should not cancel the download, nor allow flicking to the left.

**Comment by FriendsNone** [comment]
Oh. If that's the case. Importing from stable should also not cancel the process when flicked (see video attached)? Flicking to the left is an equivalent of clicking on the "x" of a notification, which dismisses it, but also cancels if said notification is a task.

https://user-images.githubusercontent.com/4056272/192007976-159dff5e-004f-484e-9726-4cd5ec5734c8.mp4

I think separating notifications as "notifications" and "tasks" can fix it? Notifications (like any messages, warnings, errors) can be dismissed (flicking left or clicking on the "x") and set aside (flicking right), while Tasks (like updates, downloads, imports) can't be dismissed but can be set aside, and can only be canceled by clicking on the "x".

That's just my suggestion. I haven't really paid much attention to the notification system of lazer.
