### ISSUE TITLE
Text is cut off in certain places

### ISSUE THREAD

**Issue by yuzupon1133** [ppy/osu#20449]
### Type

Other

### Bug description

As the title says, the text cut off, so I think it should be a line break.
I found a related issue on #3504, but slightly different.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/65931718/192091405-4922b94a-4de2-470e-8624-2fb5ae7a5b90.png)
![image](https://user-images.githubusercontent.com/65931718/192091410-190abe11-4274-48c9-9700-e516fa07b7f6.png)
![image](https://user-images.githubusercontent.com/65931718/192091485-a1486efd-d182-48f5-a44f-fe43fd8328c9.png)

### Version

2022.923.1

### Logs

[database.log](https://github.com/ppy/osu/files/9638432/database.log)
[performance.log](https://github.com/ppy/osu/files/9638433/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9638434/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9638435/updater.log)

**Comment by peppy** [comment]
serach pleasf

**Comment by yuzupon1133** [comment]
> serach pleasf

Of course I searched.
However, that issue is 4 years old and I didn't think it was still being advanced, so I assumed it was practically the same as being closed.
Should I have commented on that issue?

**Comment by peppy** [comment]
The base issue is here for reference https://github.com/ppy/osu-framework/issues/5007
