### ISSUE TITLE
Game freezes when changing the keys i use to play.

### ISSUE THREAD

**Issue by Stogdy** [ppy/osu#20456]
### Type

Performance

### Bug description

I tried to change my keys for gameplay and it gave me a big freeze but its inconsistent because one time it can be shorter freezes and other times longer freezes.

I tried this on my desktop and my laptop.

### Screenshots or videos

https://user-images.githubusercontent.com/67536549/192104392-f8bdaa5c-642c-4e05-8c31-590057761884.mp4

### Version

osu! 2022.923.1-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9638929/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9638930/updater.log)
[database.log](https://github.com/ppy/osu/files/9638931/database.log)
[network.log](https://github.com/ppy/osu/files/9638932/network.log)
[performance.log](https://github.com/ppy/osu/files/9638933/performance.log)

**Comment by peppy** [comment]
Are you importing beatmaps in the background?

**Comment by Stogdy** [comment]
i was not importing beatmaps at the time

**Comment by peppy** [comment]
@Stogdy are you running the game from a slower IO device (hard drive or otherwise)? Do you also find beatmap imports to be quite slow?

**Comment by peppy** [comment]
Fixed via #20707 (and will be further improved #20712).
