### ISSUE TITLE
Non-default skin selected by default when installing osu! for the first time

### ISSUE THREAD

**Issue by agatemosu** [ppy/osu#20459]
### Type

Game behaviour

### Bug description

When installing osu! for the first time the "triangles" skin is selected, but the default skin is "argon".

### Version

2022.923.1-lazer

### Logs

I think it's irrelevant

**Comment by peppy** [comment]
This was intentional to an extent, because I wasn't sure whether it would be ready for the new release to be objectively a better initial choice. But I think it can be switched over for the next release.
