### ISSUE TITLE
Suspiciously low scores in leaderboards

### ISSUE THREAD

**Issue by WiseDragoon5374** [ppy/osu#20469]
### Type

Game behaviour

### Bug description

Recently I was running Autoplay on Acid Rain (https://osu.ppy.sh/beatmapsets/982020#osu/2055234) to see if it worked similarly to stable (it didn't, espescially the tree part), and then I saw an SS score with 1/1 combo and DTHDFLDO (DO modified AR to 7.8 and OD to 0.0) as the first score. (see first screenshot).

Looking around, there were some more low scores, such as a Blue Zenith SS worth 428pp with 1/1 combo, with DTHRHDFL (all unmodified) (see 2nd screenshot), another one for Bwa ! (https://osu.ppy.sh/beatmapsets/1014936#osu/2124067) with no mods and 6/6 combo (3rd screenshot), and a final one for Fata Morgana (https://osu.ppy.sh/beatmapsets/751782#osu/1582612), no mods, 1/1 combo SS. (4th screenshot)

Not sure what caused these, but it's very clear that 1/1 combos on these maps are impossible.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/93832641/192158611-f6d72fae-a359-4bb0-95a8-3434acebd4e4.png)
![image](https://user-images.githubusercontent.com/93832641/192158740-545e78a3-53bd-4afb-84ac-29c77df7e955.png)
![image](https://user-images.githubusercontent.com/93832641/192158939-a018ae90-cd13-4267-9194-f75db483f234.png)
![image](https://user-images.githubusercontent.com/93832641/192158944-1e32458e-ae4e-41bf-b5d1-69cb03118c8c.png)

### Version

2022.923.1

### Logs

[database.log](https://github.com/ppy/osu/files/9641477/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9641478/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9641479/network.log)
[performance.log](https://github.com/ppy/osu/files/9641480/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9641481/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9641482/updater.log)

**Comment by toadsworth-jr** [comment]
As far as I remember, peppy is working on it to make sure that scores like that will be removed and local changes to the beatmaps will invalidate the beatmap for score submission.
But that's just my complete guess.

**Comment by WiseDragoon5374** [comment]
Good, we don't want more of these. Thanks!
