### ISSUE TITLE
song speed up after exiting the result screen

### ISSUE THREAD

**Issue by kafibu** [ppy/osu#20475]
### Type

Game behaviour

### Bug description

1.play or use autoplay on any map

2.play until result screen.

3.exit out immediately 

4.song will speed up

*more noticeable with DT

### Screenshots or videos

https://user-images.githubusercontent.com/111474179/192192322-7f0c916e-e047-40e0-8b70-c3a571e6eefb.mp4

### Version

2022.923.1

### Logs

[performance.log](https://github.com/ppy/osu/files/9642872/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9642873/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9642874/updater.log)
[database.log](https://github.com/ppy/osu/files/9642875/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9642876/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9642877/network.log)

**Comment by peppy** [comment]
In your log file, it shows the gameplay clock seeking many times, but I can't see this happening in your video, nor can I reproduce locally. I think these seek operations may be the issue, and the bass/audio thread may be running behind or something like that.

Are you able to repro the issue from a clean startup and provide logs once more?

**Comment by kafibu** [comment]
ok this only happen with DT.
You can notice at the end in song select menu the song speed up and slow back down


https://user-images.githubusercontent.com/111474179/192461358-7b0ddc1f-123d-4f00-9dcf-e2202ea70b6d.mp4

[performance.log](https://github.com/ppy/osu/files/9652816/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9652818/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9652821/updater.log)
[database.log](https://github.com/ppy/osu/files/9652822/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9652823/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9652824/network.log)
