### ISSUE TITLE
Screen scaling "gameplay" partially cuts off approach and follow circles

### ISSUE THREAD

**Issue by edward-shen** [ppy/osu#20517]
### Type

Cosmetic

### Bug description

Repro steps:
 - Set screen scaling is set to "Gameplay".
 - Set vertical and horizontal scaling values to 75.
 - Play any osu!standard song with sliders or hit circles near the top or bottom of the scaled screen.
   - Screenshots are from https://osu.ppy.sh/beatmapsets/1593057#osu/3253646 
 - Approach circles and follow circles are cut off at the scaling boundary.

Expected behavior: These elements should be scaled, but also rendered beyond the scaled area.

This doesn't repro on other scaling modes as this is the only mode scales game play elements while preserving UI elements at their original positions.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/6173958/192692981-f7009f0a-0adc-41e2-8616-6fe4da5db140.png)
![image](https://user-images.githubusercontent.com/6173958/192692892-8a48a0ec-b1e7-4736-8e59-278a215c890d.png)
Full screen example of the previous image:
![osu_2022-09-27_22-24-49](https://user-images.githubusercontent.com/6173958/192694644-ac071253-a65f-4df8-a06f-e2a981759138.png)

### Version

2022-923.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9661765/database.log)
[network.log](https://github.com/ppy/osu/files/9661766/network.log)
[performance.log](https://github.com/ppy/osu/files/9661767/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9661768/runtime.log)

**Comment by peppy** [comment]
This is intended as if we didn't mask the edges, some rulesets would show off-screen elements and look broken. We may add a border to make this look nicer in the future.

Tracking at https://github.com/ppy/osu/discussions/19985 already.
