### ISSUE TITLE
Mania LegacyComboCounter get a shadow backdrop when counter increases

### ISSUE THREAD

**Issue by Endroma1** [ppy/osu#20541]
### Type

Cosmetic

### Bug description

LegacyComboCounter  gets a shadow behind itself when the counter increases like the stable counter. This is very distracing when using the combo counter as a reference point. 

Skin: https://mega.nz/file/C2QVjKZC#OxGzqLXNNp7rtmc51E-xMYtdwpcZ7LAQ8m2XzDAwteI

also tested with this skin: https://osu.ppy.sh/community/forums/topics/203238?n=1

### Screenshots or videos

Lazer behaviour:
![Screenshot 2022-10-01 211429](https://user-images.githubusercontent.com/102969718/193424796-91dd8f97-6fba-4b0c-9433-bccb2fe7e277.png)

Stable behaviour:
![Screenshot 2022-10-01 211714](https://user-images.githubusercontent.com/102969718/193424905-c314e8b9-e2a5-42b9-80a7-8abd14778861.png)

### Version

2022.923.1

### Logs

[updater.log](https://github.com/ppy/osu/files/9691048/updater.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9691050/legacy-ipc.log)
[performance.log](https://github.com/ppy/osu/files/9691053/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9691054/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9691055/updater.log)
[updater.log](https://github.com/ppy/osu/files/9691058/updater.log)

**Comment by smoogipoo** [comment]
We cannot fix this, the shadow is baked into the texture.

**Comment by enoslayd** [comment]
Its more of a different animation as the mania and taiko animations aren't added yet

**Comment by loma-baldsson** [comment]
perhaps a side-by-side comparison via stable and lazer may help?

as mentioned, it seems to be because the mania combo counter is not implemented (at least, was not implemented the last time i checked) and just uses the one for standard

**Comment by peppy** [comment]
I think this is valid to keep open. osu!stable uses a different animation in mania, so we probably want to support that to some degree (similar to how it's handled in osu!catch).

https://user-images.githubusercontent.com/191335/193524943-0aa1a863-6ef0-42e1-8955-ac89ffe6532b.mp4
