### ISSUE TITLE
Hit circle overlap inconsistent on stable and lazer for this skin.

### ISSUE THREAD

**Issue by DanWlker** [ppy/osu#20546]
### Type

Cosmetic

### Bug description

The "2" in the hit circle.has a slightly larger spacing in Lazer when compared to stable for this skin 
 https://drive.google.com/file/d/1XnMjkNgGpVWpj9FoJpfQJhflgQfx7itQ/view?usp=sharing

### Screenshots or videos

![photo_2022-10-02_18-26-13](https://user-images.githubusercontent.com/60170554/193449505-214354ac-a9c3-40d1-837d-980380c0bde2.jpg)
![photo_2022-10-02_18-27-34](https://user-images.githubusercontent.com/60170554/193449510-f9e9cf9e-0655-4492-bacb-250a9f4001b6.jpg)

### Version

2022.923.1

### Logs

[network.log](https://github.com/ppy/osu/files/9692254/network.log)
[performance.log](https://github.com/ppy/osu/files/9692256/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9692257/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9692258/updater.log)
[database.log](https://github.com/ppy/osu/files/9692259/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9692260/legacy-ipc.log)

**Comment by peppy** [comment]
This is an issue with your skin. The `1` sprite has empty transparent space in the `@2x` version.


https://user-images.githubusercontent.com/191335/193528642-af6a6343-2980-423c-9eeb-efc20d6b8f96.mp4

**Comment by smoogipoo** [comment]
Well, presumably that's why they mentioned "hit circle overlap" in the title, because skins have a `HitCircleOverlap` parameter which we're not using in lazer. Though their skin's been deleted from their drive so I can't access it to verify.

I believe that this is a valid issue just because we're not using `HitCircleOverlap`.

**Comment by peppy** [comment]
That's the thing. Their stable was using the 1x version which has a different alignment. It looks like they edited only the 1x version in their skin and the rest of the files were unedited, including the 2x version without the padding.

**Comment by smoogipoo** [comment]
How do you know that their stable was using the 1x version? I understand how you've conjectured that based on the files in their skin, but have you also verified they don't have a massive `HitCircleOverlap` in their skin to make up for it? Can you check, if you still have the skin?

**Comment by peppy** [comment]
Just to confirm, you understand that `HitCircleOverlap` applies the same amount of overlap change at both 1x and 2x, right?

Here are the files for reference (I don't have the full skin anymore):

![default-1@2x](https://user-images.githubusercontent.com/191335/193774697-361b632b-7dde-4796-8b17-d656e1b20bd4.png)
![default-1](https://user-images.githubusercontent.com/191335/193774700-b6b07a94-0411-48df-a638-2bb0a44cd35e.png)

**Comment by smoogipoo** [comment]
Yes, I understand that. It's not unreasonable to expect a user's skin to not match at 1x and 2x resolutions if they only use 2x and only update those particular files.

**Comment by peppy** [comment]
2x are only used above 768 pixels height on stable, if that helps your understanding.

**Comment by smoogipoo** [comment]
TIL. Obviously unless `HighResolution` is true but I expect that to be false in this case.

Anyway I found a skin with the same name in their profile and it looks different yet so /shrug, also contains only 2x textures:
![osu_2022-10-04_17-58-52](https://user-images.githubusercontent.com/1329837/193778694-1afb2e34-0c11-4f20-be83-3c289053f813.jpg)
