### ISSUE TITLE
Song Exist But Beatmap Doesn't Exist

### ISSUE THREAD

**Issue by ZapTech43** [ppy/osu#2055]
So The Issue that happens is the **music & beatmap exist & i can play it** but it **doesn't exist on the beatmap list** when you wanna play it 
Here's A Example for it : 

![song exists beatmap doesn t](https://user-images.githubusercontent.com/30797591/36068650-a0310c86-0f0c-11e8-9a32-b51319f5baeb.png)

If It Exist in the music list & beatmap list : 

![it should be like this](https://user-images.githubusercontent.com/30797591/36068659-c6263830-0f0c-11e8-826c-36a295408589.png)

**Comment by peppy** [comment]
Wrong ruleset?

**Comment by ZapTech43** [comment]
Yes i think like the music & beatmap exist but on the beatmap list it doesn't **Showed**

**Comment by LovelyA72** [comment]
Can you also make sure that map is not under taiko, catch, and mania? Because some map does not have the osu version, they may only contain mania or taiko or catch. And we don't(maybe not yet) have a catch to osu converter etc.

**Comment by jacksonisiah** [comment]
can someone confirm this is a beatmap as well? (link possibly?)

**Comment by ZapTech43** [comment]
Oh Yeah Sorry just Noticed 😄 Yes It's An CTB But after i go to CTB Mode The Beatmap Exist Problem Fixed 😆 But it's kind a messy for me to play a CTB Map that i have to go to CTB Mode Fist Though

**Comment by ticotaco72** [comment]
@ppy i think this issue isn't needed anymore if you don't want to implement convereters from ruleset x to standard ruleset

**Comment by Joehuu** [comment]
Fixed in #2159.
