### ISSUE TITLE
Slider's Tick Circles gets out from the Slider

### ISSUE THREAD

**Issue by ZapTech43** [ppy/osu#2056]
This Bug Is Exist When You Activated **Hard Rock** Mod in osu!lazer
Here's A Example Of It : 

![slider s mini circles get s out from the sliders](https://user-images.githubusercontent.com/30797591/36069065-11cd441a-0f15-11e8-9976-175d3337c45a.png)

The Black Circles Indicates Are The Bug, But When You Deactivated Hard Rock The Bug Will Disappear

**Comment by smoogipoo** [comment]
Was fixed with #2146
