### ISSUE TITLE
Hitsound sample changes aren't being applied to slider heads in the editor using osu! classic (2013) skin

### ISSUE THREAD

**Issue by MkGuh** [ppy/osu#20595]
### Type

Game behaviour

### Bug description

On the editor, when trying to switch the sample from normal to soft, it is only applied to hitcircles and slider ends - the slider head is left unchanged.

### Version

2022.923.1-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/9727317/updater.log)
[database.log](https://github.com/ppy/osu/files/9727318/database.log)
[performance.log](https://github.com/ppy/osu/files/9727319/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9727320/runtime.log)

**Comment by peppy** [comment]
I don't believe this is only relevant to the classic skin, but an actual oversight in sample update logic.
