### ISSUE TITLE
Smoke not working with Relax mod on version 2022.1088.0

### ISSUE THREAD

**Issue by Erasings** [ppy/osu#20619]
### Type

Game behaviour

### Bug description

It's found when using relax mod, and the newly added smoke feature doesn't work due to the clicking system or something.

### Screenshots or videos

couldn't find any

### Version

2022.1088.0

### Logs

[performance.log](https://github.com/ppy/osu/files/9739167/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9739168/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9739169/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9739170/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9739171/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9739172/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9739173/updater.log)
[database.log](https://github.com/ppy/osu/files/9739174/database.log)
[input.log](https://github.com/ppy/osu/files/9739175/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9739176/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9739177/network.log)

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/issues/20663
