### ISSUE TITLE
Random frame stutters when using argon! skin

### ISSUE THREAD

**Issue by Domtastick** [ppy/osu#20613]
### Type

Performance

### Bug description

I first encountered the issue when trying out the argon skin right after updating. 
It doesn't seem like the issue applies to any other skin.

### Screenshots or videos

https://streamable.com/xp3vfw

### Version

2022.1008.0

### Logs

[network.log](https://github.com/ppy/osu/files/9739060/network.log)
[performance.log](https://github.com/ppy/osu/files/9739061/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9739063/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9739064/updater.log)
[database.log](https://github.com/ppy/osu/files/9739065/database.log)

**Comment by NotGumballer91** [comment]
I believe the same issue #20421 has happened again.
If you disable song progress, The stutter should go away.

As for the explanation for your other skins, It doesn't have a song progress difficulty graph.

**Comment by Erasings** [comment]
Your computer is a toaster

**Comment by peppy** [comment]
This will be fixed in an upcoming hotfix release.
