### ISSUE TITLE
osu!Mania crash on flashlight mod enable.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#20620]
### Type

Crash to desktop

### Bug description

osu!Mania crash on flashlight enable. 
You can still back to song selection if you don't want to trigger the bomb though.

### Screenshots or videos

https://streamable.com/mnb5iz

### Version

2022.1008.0

### Logs

[performance-audio.log](https://github.com/ppy/osu/files/9739189/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9739190/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9739191/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9739192/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9739193/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9739194/updater.log)
[database.log](https://github.com/ppy/osu/files/9739195/database.log)
[network.log](https://github.com/ppy/osu/files/9739196/network.log)
[performance.log](https://github.com/ppy/osu/files/9739197/performance.log)

**Comment by peppy** [comment]
Will be fixed in the next release.
