### ISSUE TITLE
Osu!lazer Keeps Crashing upon Start on Mobile

### ISSUE THREAD

**Issue by xAstroDev** [ppy/osu#20627]
### Type

Game behaviour

### Bug description

I Updated OsuLazer Android Version To The **[Latest Version(2022.1008.0)](https://github.com/ppy/osu/releases/tag/2022.1008.0) By Downloading The Apk** Which Existed In The New Release But Now I Can't Find It.. So I Downloaded It And Started it But **it Keeps Crashing.** I Also Discovered Something Weird The Version In The App Info Page Says _**v0.1??..**_

### Screenshots or videos

![Screenshot_2022-10-08-14-09-03-980_com miui securitycenter](https://user-images.githubusercontent.com/100206062/194707718-e1d303b8-25c6-4f87-8db0-eab78fa8148f.png)

### Version

2022.1008.0

### Logs

[database.log](https://github.com/ppy/osu/files/9739224/database.log)
[performance.log](https://github.com/ppy/osu/files/9739226/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9739227/runtime.log)
[network.log](https://github.com/ppy/osu/files/9739229/network.log)

**Comment by peppy** [comment]
Will be fixed in the next release (hotfix).

Note that this only applied to android, not iOS.

**Comment by xAstroDev** [comment]
> Will be fixed in the next release (hotfix).
> 
> Note that this only applied to android, not iOS.

I Hope So, Thanks For Helping Me ☺️
