### ISSUE TITLE
osu!direct doesn't list played beatmaps

### ISSUE THREAD

**Issue by IsoaSFlus** [ppy/osu#2062]
I found that there is no option to list played beatmaps in osu!direct.

**Comment by peppy** [comment]
You mean this button?

![Pasted Image 1.png](https://shipusercontent.com/03c534c4c43eb4531370632df52d6db4/Pasted%20Image%201.png)

**Comment by IsoaSFlus** [comment]
@peppy 
I mean this
![screenshot_20180213_134218](https://user-images.githubusercontent.com/5125031/36135131-206c6f5e-10c4-11e8-974b-ece0554f801f.png)

**Comment by peppy** [comment]
Right. osu!direct is still missing a lot of functionality.

**Comment by Joehuu** [comment]
Added in https://github.com/ppy/osu/pull/10607.
