### ISSUE TITLE
Misaligned storyboard elements with backwards commands

### ISSUE THREAD

**Issue by nolife99** [ppy/osu#20632]
### Type

Game behaviour

### Bug description

Storyboard elements of reverse, or going backwards commands, are displayed differently in lazer.
![image](https://user-images.githubusercontent.com/89430659/194710917-6acbc4a8-85ae-43ea-91f4-402def8ea701.png)
Investigating in the .osb file of this storyboard shows the lyrics in the screenshots having Move-X commands that have a greater start time than end time.

map: http://osu.ppy.sh/s/768768

### Screenshots or videos

This screenshot is of the storyboard in lazer
![image](https://user-images.githubusercontent.com/89430659/194710792-22704aef-861d-4d9e-8e16-95f0b49c99d3.png)

this screenshot is in design editor in stable
![image](https://user-images.githubusercontent.com/89430659/194710819-3d3ac1f5-584e-426f-b50c-da572fe65e80.png)

### Version

2022.1008.2

### Logs

[database.log](https://github.com/ppy/osu/files/9739387/database.log)
[input.log](https://github.com/ppy/osu/files/9739388/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9739389/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9739390/network.log)
[performance.log](https://github.com/ppy/osu/files/9739391/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9739392/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9739393/updater.log)

**Comment by peppy** [comment]
Honestly I'm tempted to say that the storyboard is broken and needs to be fixed. This is super dodgy.

**Comment by smoogipoo** [comment]
According to https://github.com/ppy/osu/discussions/20865#discussioncomment-3941477, this is still not fixed.

**Comment by peppy** [comment]
@Walavouchey can you describe specifically what wasn't fixed by this? From the screenshots you posted in the linked discussion I'm not immediately sure what's the issue (text in a different place maybe?).

**Comment by Walavouchey** [comment]
> text in a different place maybe?

yes, that is exactly the issue. it's "better" now in that storyboard (cf. first image in op), but still wrong (images i posted).

i haven't tested all cases so i don't know the exact logic involved with backwards commands. as i said, that needs to be tested.

**Comment by peppy** [comment]
I'll keep this assigned for now, but I'm not intending on looking into it as a priority (as this likely only affects a handful of beatmaps and can be fixed in the future). If anyone beats me feel free to investigate further.

**Comment by Wieku** [comment]
The real issue here was that transforms with endTime<startTime were discarded, so proper starting position could not be established. Changing endTime to startTime for sanity and letting the transform through fixes the issue:

https://user-images.githubusercontent.com/5307179/199632212-abaef9e2-d7b9-41c5-99e2-6b841f2dd13a.mp4

Stable doesn't have any weird logic, it just treats endTime<startTime as instant command at startTime. Move is instantaneous at 112244, endTime and startTime are after the object fade-out is complete:

https://user-images.githubusercontent.com/5307179/199632471-89702759-e751-4a35-80de-f6502364b374.mp4

Will create a PR shortly.

**Comment by peppy** [comment]
@Wieku I made PR because you didn't. Please check it matches expectations (looks to work in the beatmap in question).
