### ISSUE TITLE
Contrast of some combo colours does not work well with "argon" skin

### ISSUE THREAD

**Issue by NullifiedJosh** [ppy/osu#20642]
### Type

Game behaviour

### Bug description

Argon skin on the beatmap named ["Everything black"](https://osu.ppy.sh/beatmapsets/589603#osu/1486195) has invisible sliders and is hard to read.

### Screenshots or videos

https://user-images.githubusercontent.com/86538544/194719418-c2c7a414-6b1c-4bfb-810e-72fe86b20caa.mp4

### Version

2022.1008.2-lazer

### Logs

Unnessary but:

[runtime.log](https://github.com/ppy/osu/files/9739866/runtime.log)

**Comment by loma-baldsson** [comment]
#19682

**Comment by NullifiedJosh** [comment]
Yeah, I think it’s simular but has to changed on per-skin basses

> #19682

**Comment by peppy** [comment]
Let's keep this issue open to track the discussion.
