### ISSUE TITLE
Game freezing when changing input binds.

### ISSUE THREAD

**Issue by qtchaos** [ppy/osu#20643]
### Type

Performance

### Bug description

Game freezes for ~5-20 seconds when changing input bindings. The problem has been persisting through multiple versions and I haven't found a solution.

### Version

2022.1008.2

### Logs

[database.log](https://github.com/ppy/osu/files/9739879/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9739880/legacy-ipc.log)
[performance.log](https://github.com/ppy/osu/files/9739882/performance.log)
[updater.log](https://github.com/ppy/osu/files/9739884/updater.log)
[runtime.log](https://github.com/ppy/osu/files/9739885/runtime.log)
[network.log](https://github.com/ppy/osu/files/9739903/network.log)

**Comment by RizonFTW** [comment]
Unable to replicate. Can you tell me if you are at the menu or inside a game? And which blind you are changing?

**Comment by qtchaos** [comment]
I've had this issue both while inside the game and in the menu, but this time I believe I was paused in the few starting seconds of a mania map.

**Comment by peppy** [comment]
There was another similar issue opened recently which I can't locate.

I'm still not 100% sure of the cause here. It's clearly a database write taking too long, but the cause is undetermined.

@qtchaos could you please attach your `client.realm` database so we can test further using your game data?

**Comment by qtchaos** [comment]
I think I've narrowed the issue down somewhat. It seems to only freeze when importing something from stable (skins, beatmaps, scores).

I don't know how much my `client.realm` database will help due to the aforementioned reasons, but I've attached it anyways.

You can't upload `.realm` files to GitHub so I've put it inside a zip file: [client.zip](https://github.com/ppy/osu/files/9747569/client.zip)

**Comment by peppy** [comment]
That helps a lot actually! I was suspecting that would be a potential cause, but as it wasn't mentioned I presumed it was from a fresh and idle game.
