### ISSUE TITLE
Slider ball points in incorrect directions in editor with Argon skin

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#20648]
### Type

Game behaviour

### Bug description

It looks like the arrow on the slider ball on a slider with the Argon skin always points in the direction it last moved towards, so when time goes backwards or you edit a slider, the slider ball points in nonsensical directions.

### Screenshots or videos

https://user-images.githubusercontent.com/17460441/194727615-d4985fcf-0b06-41a5-b7e0-1ca8d8a937fa.mp4

### Version

c169127f6ea31a8dd3f55168443f92c0da95badc

### Logs

[runtime.log](https://github.com/ppy/osu/files/9740246/runtime.log)

**Comment by peppy** [comment]
Interestingly, the logic is the same in the legacy and argon implementation, so this should actually be broken in legacy skins as well. I guess it's saved by most being symmetrical (or otherwise indiscernible)?
