### ISSUE TITLE
Phantom notes when copying and flipping in the editor

### ISSUE THREAD

**Issue by Axilotl17** [ppy/osu#20644]
### Type

Game behaviour

### Bug description

when editing a beatmap, sometimes flipping pasted notes will create phantom hitcircles that disappear 

### Screenshots or videos

https://user-images.githubusercontent.com/78441708/194720577-ded8e34c-492b-4aac-ae37-a0b1ea8853b6.mp4

### Version

2022.923.1-lazer

### Logs

[logs.zip](https://github.com/ppy/osu/files/9739942/logs.zip)

**Comment by peppy** [comment]
This has to be a regression from something changed recently, very weird.

**Comment by Trung0246** [comment]
I think I'm able to reliably replicate this bug.

For some reason it only occur when snapping into center and not other place.

https://user-images.githubusercontent.com/11626920/197924593-9b620b49-7c29-4d6d-bd08-361956723cbe.mp4

No copy-pasting involved. Only note stacking enabled.
