### ISSUE TITLE
Smoke key is displayed in the key overlay

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#20640]
### Type

Game behaviour

### Bug description

As in title, the key for Smoke is currently being displayed during gameplay in the key overlay as `B3`.

### Screenshots or videos

https://user-images.githubusercontent.com/19843905/194716163-b99c2c65-96f8-4a4b-8244-b01e82b39f7f.mp4

### Version

2022.1008.2-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/9739690/network.log)
[input.log](https://github.com/ppy/osu/files/9739691/input.log)
[runtime.log](https://github.com/ppy/osu/files/9739692/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9739693/performance.log)

**Comment by peppy** [comment]
This is intended
