### ISSUE TITLE
Starting a score replay causes the game to go back to the main menu

### ISSUE THREAD

**Issue by ndygo** [ppy/osu#20651]
### Type

Game behaviour

### Bug description

When trying to replay a score, the game briefly goes back to the main menu before the loading screen for the selected beatmap appears. This does not happen when trying to play a map, or with autoplay.

### Screenshots or videos

[lazer-replay-bug.webm](https://user-images.githubusercontent.com/93353099/194729750-0645ccaf-355b-48bf-9922-7317d0a1f2a9.webm)

### Version

2022.1008.2-lazer and master (a1f96ad5f8a2853892b43c7b58c94cb0756b6ea2)

### Logs

[database.log](https://github.com/ppy/osu/files/9740355/database.log)
[input.log](https://github.com/ppy/osu/files/9740356/input.log)
[network.log](https://github.com/ppy/osu/files/9740357/network.log)
[performance.log](https://github.com/ppy/osu/files/9740358/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9740359/runtime.log)

**Comment by peppy** [comment]
This was a hotfix to fix crashing in certain scenarios, but I agree that it feels pretty weird. Will see if we can bypass the fix in the case where it is guaranteed to not crash..
