### ISSUE TITLE
"Installing update..." notification lingers after update is ready to be applied

### ISSUE THREAD

**Issue by WiseDragoon5374** [ppy/osu#20668]
### Type

Game behaviour

### Bug description

Just logged into lazer today, got the update prompt, and then when I was about to restart to finish the update, I found the "Installing update..." notification still in the running tasks section of the notification bar. The "Update ready!" notification still displayed in the notifications section, but even if I close that, the bugged update notification stays in the tasks. Even attempting to cancel it doesn't work.

### Screenshots or videos

https://user-images.githubusercontent.com/93832641/194770395-e3bd0ede-e117-425a-834c-32a6c3961129.mp4

### Version

2022.923.1 (updating to 2022.1008.2)

### Logs

[database.log](https://github.com/ppy/osu/files/9742168/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9742169/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9742170/network.log)
[performance.log](https://github.com/ppy/osu/files/9742171/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9742172/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9742173/updater.log)

**Comment by PandaDriver156** [comment]
This has been fixed in the version you are updating to. (https://github.com/ppy/osu/pull/20428)
