### ISSUE TITLE
Locally editing a map causes an update button to show that can delete work

### ISSUE THREAD

**Issue by pfgithub** [ppy/osu#20674]
### Type

Game behaviour

### Bug description

If you locally edit a difficulty in a map, an update button shows up. Pressing this button resets the map and deletes all of your work, without warning.

It would be nice if it displayed a warning that local changes will be deleted, or made a backup of the maps with local changes or something rather than deleting them

### Version

2022.1008.2

### Logs

Doesn't apply here

**Comment by peppy** [comment]
If you do this by accident, you can restore changes from the settings menu ("Restore recently deleted beatmaps"), but I agree there should be a confirmation before running the update process.

**Comment by Doksha** [comment]
I think a very easy remedy would be to pop up a notification that says "you just deleted a beatmap, undo?"
would also happen if you delete a beatmap normally
