### ISSUE TITLE
Rewind replay to countdown after play cause skin pp display to go far negative.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#20690]
### Type

Game behaviour

### Bug description

Rewind replay to countdown (< 0:00 min) using arrow key after current pp is >= 1 cause skin's pp display to go far negative (-2147483648) and back to normal after first note hit in replay.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/7066150/194895131-ec11c1b9-bea2-4ebb-8e18-f15fe07135b5.png)

### Version

2022.1008.2

### Logs

[network.log](https://github.com/ppy/osu/files/9746986/network.log)
[performance.log](https://github.com/ppy/osu/files/9746987/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9746988/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9746989/updater.log)

**Comment by Natelytle** [comment]
This is due to the accuracy PP formula dividing by 0 at 0 objects hit, see #20691
