### ISSUE TITLE
Smoke shakes when gameplay is paused

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#20705]
### Discussed in https://github.com/ppy/osu/discussions/20686

<div type='discussions-op-text'>

<sup>Originally posted by **Gabixel** October 10, 2022</sup>
As title. Also, if an overlay temporarily shifts the playfield, the smoke stops wobbling for that moment:

![osu! 2022 10 10 - 12 06 45 01_Trim](https://user-images.githubusercontent.com/43073074/194843639-06db8027-5b8b-49da-a54c-9e8a7bb5d682.gif)
</div>

**Comment by peppy** [comment]
Cursor trail is also a weird one while paused, likely for similar reasons.
