### ISSUE TITLE
Beatmap background blur does nothing if storyboard is enabled

### ISSUE THREAD

**Issue by UselessToucan** [ppy/osu#2072]
STEPS_TO_REPRODUCE:
1. Play beatmap which has storyboard with auto mod enabled(auto mod allows us to tweak settings on the Player screen itself).
2. Drag "Background blur" sliderbar whenever Storyboard is enabled(check the checkbox below).
3. Drag "Background blur" sliderbar whenever Storyboard is disabled(uncheck checkbox below).

EXPECTED_RESULT:
Whenever I drag "Background blur" sliderbar the image becomes blurry no matter is storyboard enabled or not.

ACTUAL_RESULT:
It works ok when storyboard is disabled, but nothing happens with the background image when storyboard is on.

ADDITIONAL_INFO:
Tested on [this revision](https://github.com/ppy/osu/commit/e1f81488cd653eeae83a7162bacdfa168be82791)
Tested on [this beatmap](https://osu.ppy.sh/s/46969)
Background dim works ok.

Screenshots:
![blurstoryboardoff](https://user-images.githubusercontent.com/22450664/36281597-41c18c6a-12af-11e8-80bc-151f874463dc.jpg)
![blurstoryboardoff2](https://user-images.githubusercontent.com/22450664/36281598-41eb63fa-12af-11e8-9676-3c80f02560f1.jpg)
![blurstoryboardon](https://user-images.githubusercontent.com/22450664/36281599-420b3d92-12af-11e8-933e-95212f560212.jpg)

**Comment by thatprogrammer1** [comment]
I believe this was intended during implementation for performance.

**Comment by peppy** [comment]
for the time being, yes. to make it work in a way we could support, storyboards will need to be buffered. the current buffered implementation may not be good enough for this to happen yet.
