### ISSUE TITLE
Long usernames overlap score on playlist leaderboards

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu#20760]
### Type

Cosmetic

### Bug description

This is referring to the central leaderboard that appears immediately after opening a playlist.

### Screenshots or videos

<img width="460" alt="Screen Shot 2022-10-13 at 7 07 59 PM" src="https://user-images.githubusercontent.com/100527514/195745962-8429d520-1a60-4557-95c7-907283c65b2f.png">

### Version

2022.1008.2-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9781879/database.log)
[network.log](https://github.com/ppy/osu/files/9781880/network.log)
[performance.log](https://github.com/ppy/osu/files/9781881/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9781882/runtime.log)

**Comment by frenzibyte** [comment]
Might as well include this in https://github.com/ppy/osu/issues/3504 rather than having a separate thread for it.

**Comment by Non-Binary-Programmer** [comment]
If we're including this in #3504, should this be closed as completed or not planned, or is there some other github technique that I'm not familiar with?
