### ISSUE TITLE
osu! Cookie ticks delay when game lags.

### ISSUE THREAD

**Issue by Mou-Ikkai** [ppy/osu#20769]
### Type

Game behaviour

### Bug description

Haha, I know, niche case, but, just something I thought was a bit weird when listening to some songs on Main Menu. Specifically, when the cursor is on the osu! Cookie to make it play ticks and claps to the BPM. That just seems to lag behind when the game is, graphically, being lagged.

### Screenshots or videos

Surprised this Storyboard still kills modern GPUs so much .w.
https://user-images.githubusercontent.com/45863583/195964216-cb9d3328-963c-4378-acb6-e460a9ed8105.mp4

### Version

2022.1008.2-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9790943/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9790944/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9790945/network.log)
[performance.log](https://github.com/ppy/osu/files/9790946/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9790947/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9790948/updater.log)

**Comment by Coppertine** [comment]
> Surprised this Storyboard still kills modern GPUs so much .w.
For context, MouIkkai was talking about world.execute(me);
(Although a majority of storyboards on lazer are CPU, GPU and RAM bound. any of those can be a major bottleneck.)
And I feel the major issue would be the CPU.
Can you provide your current specs of your computer?

**Comment by peppy** [comment]
This is how games work.

Storyboard issues are not GPU related and already being tracked in other issue threads.

**Comment by Mou-Ikkai** [comment]
> > Surprised this Storyboard still kills modern GPUs so much .w.
> 
> For context, MouIkkai was talking about world.execute(me); (Although a majority of storyboards on lazer are CPU, GPU and RAM bound. any of those can be a major bottleneck.) And I feel the major issue would be the CPU. Can you provide your current specs of your computer?

Ryzen 9 3900X, 5700XT, DDR4-2733MHz (I just am a tech nerd .w.)
