### ISSUE TITLE
Osu can't detect my keyboard input randomly during the middle of the map

### ISSUE THREAD

**Issue by YuJJun0918** [ppy/osu#20772]
### Type

Performance

### Bug description

Problem details:

This is a problem that occurred with my recently bought keyboard. The keyboards works just fine, except when I play Osu mania. I would be playing fine until the keyboard just seemingly stops working and none of my inputs would register, causing me to fail the map. This is happening on almost every single play attempt at this point, making it impossible for me to play.

I have tried using compatibility mode. I tried using all versions of Osu (stable, experimental, etc). I've tried not using fullscreen. I've tried everything that was suggested in previous posts regarding this issue. Nothing worked, and nothing worked.

Does anyone else have the same issue?

### Version

osu! version: Stable 20221011.3 (latest)

### Logs

[database.log](https://github.com/ppy/osu/files/9791555/database.log)
[network.log](https://github.com/ppy/osu/files/9791556/network.log)
[performance.log](https://github.com/ppy/osu/files/9791557/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9791558/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9791559/updater.log)

**Comment by papertek** [comment]
this is the wrong repository

you're looking for [this](https://github.com/ppy/osu-stable-issues/issues)

**Comment by peppy** [comment]
If it's only with a new keyboard I'd say the keyboard is at fault. Likely being overloaded when you are inputting too many keys (ie. doesn't support NKRO). Please test in another application to confirm it's not just osu! (it can't be just osu!) then follow up with the manufacturer or wahtever is required.
