### ISSUE TITLE
Smoke point maximum doesn't work

### ISSUE THREAD

**Issue by goodtrailer** [ppy/osu#20805]
### Type

Game behaviour

### Bug description

This slipped by when the code was simplified to rely on function calls instead of event subscription (https://github.com/ppy/osu/pull/20376/commits/6628ab5190409e93dd4fb46f57ac0877c1d27905). Before, `SmokeSegment` stopped adding points by unsubscribing, but when that was replaced with function calls, there was no more unsubscription. So even though `FinishDrawing` is called when the max point count is hit, that function doesn't actually do anything to stop `SmokeSegment` from adding more points.

---

I was gonna open PR a fix, but I saw two ways about it and wasn't sure which was better:
1. Add an `isActive` variable which is set to `false` in `FinishDrawing`, and early return if `isActive` is `false`
2. Move all of the max point count logic to `SmokeContainer` and use the pre-existing `currentSegmentSkinnable` variable

Method 1 is easier/simpler, but I was leaning towards Method 2 since it separates responsibility more clearly, where `SmokeContainer` sorta "manages" `SmokeSegment` (spawning + input handling, and now capping too).

### Version

2022.1008.2

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/9805009/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9805010/network.log)
[performance.log](https://github.com/ppy/osu/files/9805011/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/9805012/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9805013/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9805014/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9805015/updater.log)
[database.log](https://github.com/ppy/osu/files/9805016/database.log)
[input.log](https://github.com/ppy/osu/files/9805017/input.log)

**Comment by peppy** [comment]
Hard to say which will work better without attempting both, I'd give the one you think seems better a try and see how it looks.

**Comment by smoogipoo** [comment]
Fyi I don't know how I feel about the capping in general. From my recollection (I could be wrong here), but osu! classic fast forwards the transforms to hide earlier points, which I think feels better in the context of perhaps users playing entire maps with one finger held down (rare occurrence but I've seen it a few times).

**Comment by peppy** [comment]
It should work similarly. I think that's the goal unless i'm mistaken
