### ISSUE TITLE
Changing combo in the editor doesn't update correctly with the Argon skin

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#20807]
### Discussed in https://github.com/ppy/osu/discussions/20804

<div type='discussions-op-text'>

<sup>Originally posted by **Gabixel** October 18, 2022</sup>
With the Argon skin, when you toggle the "new combo" option in an object that's in the past of the timeline, this happens:

![image](https://user-images.githubusercontent.com/43073074/196264150-83a28759-c388-4c6e-a21f-108d8ed7ef96.png)

Here's a video:

https://user-images.githubusercontent.com/43073074/196263661-7c891a02-e9bb-4e7b-9a32-cabe078ed8c0.mp4

</div>

**Comment by peppy** [comment]
Due to use of `accentColour` baked into transforms:

https://github.com/ppy/osu/blob/3811ea113d993b9e2705cc3ed93a22b6d2d5cd01/osu.Game.Rulesets.Osu/Skinning/Argon/ArgonMainCirclePiece.cs#L153-L180
