### ISSUE TITLE
Scores not submitting 

### ISSUE THREAD

**Issue by Crozh** [ppy/osu#20802]
### Type

Other

### Bug description

I recently installed osu!lazer again, 'cause my friends literally told me the leader-boards were always there, despite me seeing that none of my scores did submit before. 
Later on I found out the scores that I did 6 months ago were submitted. I even submitted scores myself yesterday. But today I played again and none of my scores are on the leader-boards.
I don't know if this is normal or not, but I wanted to report it in case it is not.  
They appear in the last played section, tho (https://osu.ppy.sh/users/4125190) but leader-boards take time to update here it seems? 

### Screenshots or videos

![image](https://user-images.githubusercontent.com/44332979/196252485-0abc0812-0b84-45af-a1df-4dcea658633f.png)
![image](https://user-images.githubusercontent.com/44332979/196252515-6cb20106-f014-4279-9921-b3ab8d21f473.png)

### Version

2022.1008.2

### Logs

[database.log](https://github.com/ppy/osu/files/9803346/database.log)
[network.log](https://github.com/ppy/osu/files/9803347/network.log)
[performance.log](https://github.com/ppy/osu/files/9803348/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9803349/runtime.log)

**Comment by peppy** [comment]
This is due to a forgotten change in envvar case. It's fixed for new scores, but existing scores were lost for good.

I'll perform a full reindex today because there's no other recovery path. Should be resolved within 24 hours.
