### ISSUE TITLE
a message comes up

### ISSUE THREAD

**Issue by joowonXD** [ppy/osu#2081]
osu!lazer is currently in early stages of development and is not yet ready for end users. Please avoid creating issues or bugs if you do not personally intend to fix them. Some acceptable topics include:

- Discussions about technical design decisions
- Bugs that you have found and are personally willing and able to fix
- TODO lists of smaller tasks around larger features

Basically, issues are not a place for you to get help. They are a place for developers to collaborate on the game.

If your issue qualifies, replace this text with a detailed description of your issue with as much relevant information as you can provide.

**Comment by joowonXD** [comment]
I play some maps and this came up
<img width="667" alt="capture" src="https://user-images.githubusercontent.com/36570638/36347442-5258a640-1425-11e8-9c51-5ca14bb7935b.PNG">

**Comment by peppy** [comment]
Has been reported already in a different issue. Will be fixed.
