### ISSUE TITLE
Featurerequest: Disable Nightcore Beats & Disable Scoreboard Flash

### ISSUE THREAD

**Issue by takoz53** [ppy/osu#2082]
As the topic describes, an option to disable both Nightcore beats playing in the background and the Scoreboard Flash when entering top 50 would be great. Nightcore beats can be annoying when and not always a good beat at some point. For Scoreboard Flash I can just say, that there are plenty maps, that where you enter top50 and the scoreboard flashes and a note is next to the scoreboard, it can be very frustrating to see notes, so I'd add in an Option in the Menu to disable both. An example is to be seen in this picture.

![screenshot006](https://user-images.githubusercontent.com/16865864/36348782-b06ca93c-1477-11e8-9432-07c38d8da8f6.jpg)

**Comment by peppy** [comment]
Please only file issues related to the lazer client.

Also you seem to be using a modified game client. This is considered cheating, you should avoid doing this.
