### ISSUE TITLE
Exiting a replay exits all the way to main menu

### ISSUE THREAD

**Issue by Sublimelime** [ppy/osu#20833]
### Type

Game behaviour

### Bug description

As per title, pressing escape or clicking the back button after/while watching a replay will cause the game to exit out to main menu, **instead of back to beatmap carousel like I'd expect**. This seems to be a regression since it didn't happen a few updates ago. 

To reproduce:

- Watch a replay
- Press escape or click back button
- See main menu

### Version

2022.1008.2

### Logs

[runtime.log](https://github.com/ppy/osu/files/9825232/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9825233/updater.log)
[database.log](https://github.com/ppy/osu/files/9825234/database.log)
[network.log](https://github.com/ppy/osu/files/9825235/network.log)
[performance.log](https://github.com/ppy/osu/files/9825236/performance.log)

**Comment by smoogipoo** [comment]
This is intentional for the time being. https://github.com/ppy/osu/blob/6b26547d03432668ffa4d762aea00ab8c6ced46e/osu.Game/OsuGame.cs#L568-L577

**Comment by Sublimelime** [comment]
I just clicked on the play from the left side of the beatmap carousel (from the local scores display), then clicked the green view replay button at the bottom. Maybe I copied the wrong logs. 

Why is this behavior intentional? The code smoogi linked doesn't really indicate why to me. Some kind of temporary fix to a crash?

**Comment by peppy** [comment]
Aha, that's the specific case I fixed. The fix wasn't in the last release, so you'll probably see things fixed in the next release in that case! (see https://github.com/ppy/osu/pull/20682)
