### ISSUE TITLE
Not able to drag mp3 file into editor

### ISSUE THREAD

**Issue by Drazzens** [ppy/osu#20843]
### Type

Game behaviour

### Bug description

I tried to put an mp3 file into the editor to make a new map and it brings up a circle with a line through it and when I let go it goes away and nothing happens not sure how to fix this.

### Screenshots or videos

https://user-images.githubusercontent.com/111329172/197094611-823b401a-ee4c-42d2-a182-b77940b9bc22.mp4

### Version

b20221016.2

### Logs

[runtime.log](https://github.com/ppy/osu/files/9835119/runtime.log)
[session.log](https://github.com/ppy/osu/files/9835120/session.log)
[update_success.log](https://github.com/ppy/osu/files/9835121/update_success.log)
[osu!auth.log](https://github.com/ppy/osu/files/9835122/osu.auth.log)

**Comment by jai-x** [comment]
This repository is for osu!lazer.

Please report osu!stable issues to https://github.com/ppy/osu-stable-issues/

**Comment by peppy** [comment]
Also the cause of this is that something on your system is running as administrator when it shouldn't be. So please confirm and fix that.
