### ISSUE TITLE
Tournament Ladder deserialisation test fails on MacOS

### ISSUE THREAD

**Issue by its5Q** [ppy/osu#20844]
### Type

Other

### Bug description

I've cloned the repo and decided to run all tests to make sure everything works fine, and there was a test that's failing in the tournament client - LadderInfoSerialisationTest -> TestDeserialise.
Reading through the stacktrace, it fails to parse the Position field of TournamentMatch class, haven't dug depper as to why. 

I'm running MacOS 12.6 on M1 Air.

### Version

HEAD (703a8afb)

### Logs

[Test Output for TestDeserialise.Ragiwar.txt](https://github.com/ppy/osu/files/9837213/Test.Output.for.TestDeserialise.Ragiwar.txt)

**Comment by peppy** [comment]
What region/culture do you have set? Does the issue go away if you change to something standard like US english / US region?

**Comment by its5Q** [comment]
My display language was set to Russian, and region to Russia. Changing those to English US made the test complete successfully.

**Comment by peppy** [comment]
Seems like we need to pass invariant culture to 

https://github.com/ppy/osu/blob/f8830c6850128456266c82de83273204f8b74ac0/osu.Game.Tournament/JsonPointConverter.cs#L34

But I can't figure out what the context argument is

![JetBrains Rider-EAP 2022-10-21 at 11 44 56](https://user-images.githubusercontent.com/191335/197188518-82fe9a86-8cba-4496-9d3d-d3446918bbf7.png)

Apparently the context can be `null` in .NET 6 but not .NET standard...

@smoogipoo any ideas?

**Comment by smoogipoo** [comment]
Have you tried it? If it works then just bypass it - I have no idea what to pass there.

**Comment by peppy** [comment]
It does just seem to work, albeit I've only tested against desktop. Probably fine to go with it?
