### ISSUE TITLE
Linux build can export files with names containing invalid characters for other platforms

### ISSUE THREAD

**Issue by ChoquePumper** [ppy/osu#20858]
### Type

Other

### Bug description

Whenever I export files (such as scores) from the Linux native build, it replaces only the `/` character for filenames and not other invalid characters such as `*`, `"`, `<` and `>` that metadata might contain. (e.g. `Guest playing Artist*Name - Song_"name" <something ver.> (Not me) [Easy].osr`).
If I export the same thing but from Windows, it replaces all the invalid characters as expected.

I run both Linux and Windows operating systems on the same PC and use a shared location for the game data. The location happens to be in a NTFS filesystem and Windows doesn't like those invalid characters mentioned earlier in the filenames. In a FAT32 filesystem, the exporting fails with an "Invalid argument" error since the vfat Linux kernel module enforces to not have those invalid characters.

Looking at the code, it relies on `Path.GetInvalidFileNameChars()` for getting the invalid characters. It seems that on Linux it returns only two characters, the NULL character and `/`.

### Screenshots or videos

On the NTFS filesystem the exports directory looks like this. The first 4 items are generated from the Linux native build and the other 3 are from the Windows build.

![Captura de pantalla de 2022-10-22 01-48-17](https://user-images.githubusercontent.com/58898942/197323961-0bb3129f-a0a7-4c1c-9fdc-06a7b299a393.png)

I also recorded a video reproducing this bug but on a clean installation with a few beatmaps installed on a FAT32 filesystem.

https://user-images.githubusercontent.com/58898942/197324631-e80bf0bc-fdc1-4ed9-bcca-74dbb2ab2dac.mp4

### Version

2022.1008.2-lazer

### Logs

Generated while recording the video (FAT32 filesystem):
[database.log](https://github.com/ppy/osu/files/9843746/database.log)
[network.log](https://github.com/ppy/osu/files/9843747/network.log)
[performance.log](https://github.com/ppy/osu/files/9843748/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9843749/runtime.log)

**Comment by peppy** [comment]
Relevant links:

https://github.com/dotnet/runtime/issues/25011 (potential proposal for a better API)
https://github.com/dotnet/runtime/blob/25ea6c44cf3140cc9bfbaaff7f01ad2a27414f8e/src/libraries/System.Private.CoreLib/src/System/IO/Path.Unix.cs (code showing the `GetInvalidFileNameChars` is... not useful on linux)

Most importantly:

https://github.com/dotnet/runtime/issues/24223

Which says that we basically shouldn't be using this method, and instead handling exceptions from the actual IO operations.. I guess? Then identifying the characters that need replacing ourselves?

At this point I think we should probably just maintain our own method which has all the common not-supported characters blocked across all OSes. Thoughts?

**Comment by frenzibyte** [comment]
Seems this is resolved now?

**Comment by ChoquePumper** [comment]
Yes, it's resolved. I just wanted to do some testing with the new version before closing the issue but i was 'busy' and kind of forgot about that.

I added more beatmaps to the installation in the FAT32 filesystem and the exporting just worked, no errors. These are the results:

![Captura de pantalla de 2022-11-04 01-38-42](https://user-images.githubusercontent.com/58898942/199890117-f727d9cc-4499-4bcb-9186-33b06236f60d.png)

Not sure if allowing `'` would be safe but for now it seems to work. So I'm closing this.
