### ISSUE TITLE
Unable to install osu! lazer

### ISSUE THREAD

**Issue by sarkolsss** [ppy/osu#20859]
### Type

Other

### Bug description

Hello, I have a problem. When installing osu! lazer I get the error **" The program cannot be started because api-ms-win-core-winrt-l1-1-0.dll is missing on the computer"**. And another error on picture. And folder "SquirellClowdTemp" does not exist. Please help.

### Screenshots or videos

![picture](https://user-images.githubusercontent.com/116424610/197325809-f422a1d4-6696-4a47-ba85-6e76ce05c67e.png)
![picture](https://user-images.githubusercontent.com/116424610/197325868-33bb2aae-529f-4e2d-b3c7-7d21e3386427.png)

### Version

osu! lazer (2022.1008.2.0)

### Logs

I dont have logs.

**Comment by enoslayd** [comment]
It looks like you are using windows 7 which is unsupported by lazer (8.1 is the minimum Windows version supported)

**Comment by sarkolsss** [comment]
> It looks like you are using windows 7 which is unsupported by lazer (8.1 is the minimum Windows version supported)

okay, thanks
