### ISSUE TITLE
Text information in beatmap details overlay may overflow in certain languages

### ISSUE THREAD

**Issue by DavidHusicka** [ppy/osu#20863]
### Type

Cosmetic

### Bug description

In beatmap details, the "approach rate" text overflows the label and goes behind the visualization in the Czech language.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/25853767/197353759-fa4c7035-fcfa-4810-86fc-5024ececcf0c.png)

### Version

2022.1022.0

### Logs

[database.log](https://github.com/ppy/osu/files/9844930/database.log)
[input.log](https://github.com/ppy/osu/files/9844931/input.log)
[network.log](https://github.com/ppy/osu/files/9844932/network.log)
[performance.log](https://github.com/ppy/osu/files/9844933/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9844934/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9844935/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9844936/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9844937/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9844938/runtime.log)

**Comment by bdach** [comment]
Let's track in #15452.
