### ISSUE TITLE
Non-mania judgement animations display on mania ruleset with converted beatmaps

### ISSUE THREAD

**Issue by JanluOfficial** [ppy/osu#20867]
### Type

Game behaviour

### Bug description

While I was trying to play the Beatmap "Hatsune Miku - Lovely Day" on osu!mania instead of osu!, I noticed that lazer couldn't decide between the Classic ("300", "100", "50", "X") Indicators and the modern/argon ("Perfect", "Good", "Meh", "Bad") Indicators. I have not tested if this also happens in the other skins, but I could imagine it does.

The Map has custom skin data included, which lazer doesnt fully read, opting to use a mix of argon and the custom one.

### Screenshots or videos

osu!mania gameplay of a normal beatmap (Birdsong) and one with custom Skin Data (Lovely Day)
https://user-images.githubusercontent.com/95766563/197356856-632d74ba-9f68-4050-b415-ea6f1864dfad.mp4

Normal osu! Gameplay of Lovely Day to show the custom skin data:
https://user-images.githubusercontent.com/95766563/197356856-632d74ba-9f68-4050-b415-ea6f1864dfad.mp4

### Version

osu! 2022.1022.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9845072/database.log)
[input.log](https://github.com/ppy/osu/files/9845073/input.log)
[network.log](https://github.com/ppy/osu/files/9845074/network.log)
[performance.log](https://github.com/ppy/osu/files/9845075/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9845077/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9845078/updater.log)

I don't know how these will help but they are requirements...

**Comment by Walavouchey** [comment]
beatmap is https://osu.ppy.sh/beatmapsets/22534, and you accidentally linked the same video twice (mania video missing)

The beatmap wasn't designed for mania, so when playing the convert, it doesn't have a custom sprite for the Perfect (MAX) and Good (200) judgements (which are exclusive to mania), so it will display the default skin variant.

This is expected behaviour.

**Comment by JanluOfficial** [comment]
Oh... My bad, I originally added the videos in the main section before attempting to copy the link into the screenshot section.

https://user-images.githubusercontent.com/95766563/197361519-5742f545-0863-41e8-b489-e1401bf682f0.mp4

Here is the actual Mania Video

**Comment by JanluOfficial** [comment]
> This is expected behaviour.

With the Mania Video now, I think seeing the context of what I mean is way easier, and I don't think that the actual behavior is intended. If it is... Idk.

**Comment by Walavouchey** [comment]
yes, i did test the map in mania myself too, and yes it is expected, just like i described. this is exactly how stable behaves.

you can select a skin with judgement sprites that resemble the ones in the beatmap if you want them to match better, or just play maps designed for mania

**Comment by frenzibyte** [comment]
That looks wrong. Mania uses its own set of judgement textures prefixed with `mania-hitX`, while that beatmap doesn't have such ones. Looks to be working fine on previous release so seems this likely regressed in https://github.com/ppy/osu/pull/20725, will investigate further.
