### ISSUE TITLE
Duplicate "installation update ready" notification

### ISSUE THREAD

**Issue by Julian-Heidenreich** [ppy/osu#20875]
### Type

Game behaviour

### Bug description

I just tried to update from Version 2022.923.1-lazer to 2022.1022.0-lazer.
The download took way to long and checked why and saw Steam was Updating a Game, stopped it and tabbed back in.
Download resumed and finished 2 seconds after like normal. After that I got 2 duplicate ready to install notification.

After that I took a 2 Screenshots to test if any other notifications duplicate themselves but they worked fine.

The Changelog notification in the new version worked as expected as well

Additionally:
I just realized that the "Downloading update" notification did not disappeared as well but I am not sure if that is intended

### Screenshots or videos

![osu_2022-10-23_01-26-29](https://user-images.githubusercontent.com/52206546/197366363-a276e697-f23b-488c-9212-b927b3136a43.jpg)
![osu_2022-10-23_01-26-30](https://user-images.githubusercontent.com/52206546/197366364-cb70f4a1-6209-4a62-a578-54039ad85c61.jpg)

### Version

2022.923.1-lazer

### Logs

I unfortunately only have the log files from the updated version next time I will remember that so save them in advance. I still provide the one from 2022.1022.1-lazer
[performance.log](https://github.com/ppy/osu/files/9845464/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9845465/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9845466/updater.log)
[database.log](https://github.com/ppy/osu/files/9845467/database.log)
[network.log](https://github.com/ppy/osu/files/9845468/network.log)

**Comment by peppy** [comment]
We applied some fixes over the recent releases to the update notifications, so this may already be resolved. I've checked your logs and the code and can't immediately see how this could happen.

**Comment by Julian-Heidenreich** [comment]
If this happens again I leave a comment and the logs on the issue.

**Comment by Julian-Heidenreich** [comment]
Hey again,

I got the same bug again.

![osu_2022-11-17_23-22-57](https://user-images.githubusercontent.com/52206546/202573469-d9974958-3d00-45ac-9527-939893faab9a.jpg)

This time from 2022.1022.0 to 2022.1117.0
This time I got logs too

[performance.log](https://github.com/ppy/osu/files/10036179/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10036180/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10036181/updater.log)
[database.log](https://github.com/ppy/osu/files/10036182/database.log)
[network.log](https://github.com/ppy/osu/files/10036183/network.log)

I wasn't sure if I should open a new one but decided against it hope that's ok

**Comment by Joehuu** [comment]
> This time from 2022.1022.0 to 2022.1117.0

Yes, the fix was applied to the latest version (2022.1117.0). Future updates won't have this bug.
