### ISSUE TITLE
Lazer weirdly Jumping around when moved between monitors in Windowed Mode (At least on Windows 10)

### ISSUE THREAD

**Issue by JanluOfficial** [ppy/osu#20871]
### Type

Game behaviour

## How did you find the bug?
I was doing some development with a pulled repo of osu!lazer. While having Lazer in Windowed, I moved it between my screens. thats when I found this issue.

I tested to see if this was also an issue in the official lazer build (as I wasn't sure if it had to do with my branch) and sure enough, It was there. The Footage you're seeing is from the official lazer build and not from my branch.

## Any additional details that might help?

- My Left Monitor is 1920x1080 and my right (primary) monitor is 1920x1200
- My system is running on a GTX 560 SE from Nvidia with Video-BIOS-Version 70.24.45.00.80 and PCI-E x16 Gen2
- My Nvidia Driver Version is 391.35 

### Screenshots or videos

https://user-images.githubusercontent.com/95766563/197362082-eac3c234-e0a3-4ed4-8e35-f12ac1e3692b.mp4

Sorry for the weird OBS Scene
(VS 2022 is in a Ruleset Project)

### Version

osu! 2022.1022.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9845245/database.log)
[input.log](https://github.com/ppy/osu/files/9845246/input.log)
[network.log](https://github.com/ppy/osu/files/9845247/network.log)
[performance.log](https://github.com/ppy/osu/files/9845248/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9845249/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9845250/updater.log)

And I don't know how they are going to help this time.

**Comment by Susko3** [comment]
Tracked framework-side in https://github.com/ppy/osu-framework/issues/5449.
