### ISSUE TITLE
Multiple UI Elements do not translate to Romanian

### ISSUE THREAD

**Issue by ilie-alessandro** [ppy/osu#20888]
### Type

Game behaviour

### Bug description

By testing out the game in Romanian language you can notice a ton of inconsistencies in UI translations which generally speaking makes the experience unpleasant for the romanians who know very few english and just doesn't feel polished at all!

### Screenshots or videos

![image](https://user-images.githubusercontent.com/114367743/197396947-58e34222-a39a-4595-bf07-ad249a4a179d.png)
![image](https://user-images.githubusercontent.com/114367743/197396953-dbb20b5c-2fec-4f86-aa70-ed18924ead48.png)
![image](https://user-images.githubusercontent.com/114367743/197396968-9a57c0cd-7b06-4cfe-b597-ea9d192ed10e.png)

### Version

latest

### Logs

None

**Comment by peppy** [comment]
Localisation is an ongoing effort.

**Comment by ilie-alessandro** [comment]
No doubts. Thanks! <3
