### ISSUE TITLE
Some storyboard videos play too early

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#20898]
### Discussed in https://github.com/ppy/osu/discussions/20865

<div type='discussions-op-text'>

<sup>Originally posted by **RBQcat** October 23, 2022</sup>
This storyboard is black from 1:54 to 2:09
Storyboard seems to play early
This problem is not encountered in Stable
[Beatmap](https://osu.ppy.sh/beatmapsets/1503327#osu/3079907)</div>

**Comment by Moltanicaa** [comment]
This is was created 1 year ago - https://github.com/ppy/osu/issues/13696
