### ISSUE TITLE
Left Mouse Button assigned to keyboard key not working properly

### ISSUE THREAD

**Issue by Graphicscore** [ppy/osu#2089]
Hi,
I am trying to play the development build and it looks spectecular so far!
I've encountered an issue where I am unable to use the key that is assigned to the Left Mouse Button.
It doesn't matter which key I assign to, Right Mouse Button works fine for me. When I re-assign the Left Mouse Key while being in a beatmeat it works for 10 seconds but then no more.

**Comment by peppy** [comment]
Do you mean this setting here?

![Pasted Image 1.png](https://shipusercontent.com/92068c5a191c95f02d18a9a91ea5eef0/Pasted%20Image%201.png)

Could you please tell us:

- Which key you are trying to bind?
- Do the defaults of z and x work?
- Does something coincide with the 10 second mark? Is the window losing focus or something?
- What operating system are you on?

**Comment by Graphicscore** [comment]
Yes I mean that setting.
It doesn't work with the default settings either. I'm using a german QWERTZ Keyboard Layout so the 'Z' and the 'Y' key are swapped (Y key is displayed as Z key in the settings). But I can assign it to whatever key in the alphabet it wont work.

10 seconds was an estimate amount of time, the window is still focused and the Right Button Key still works as expected, only the Left Button Key loses functionality. 

I am running Windows 10 with the latest updates. Can I provide gamelogs or something like that to help locating this issue ?
