### ISSUE TITLE
Slider sliding sample remains playing when skipping in editor timeline

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#20900]
This was supposed to be handled by `DrawableSlider.StopAllSamples()` :/

### Discussed in https://github.com/ppy/osu/discussions/20814

<div type='discussions-op-text'>

<sup>Originally posted by **Gabixel** October 19, 2022</sup>
It's still unknown to me the exact scenario of why this happens, but as you can see from the videos below, for some reason sometimes the slider sound remains audible until there's a break / the end of the map / a time shift from the user.

https://user-images.githubusercontent.com/43073074/196527345-ac06e197-e2a0-4728-94d4-720291dc21d0.mp4

https://user-images.githubusercontent.com/43073074/196527368-ccfa53ee-8a57-480f-8b16-cf83bbba3271.mp4
</div>

**Comment by peppy** [comment]
I've tried but cannot reproduce this at all.

@Gabixel can you try with a minimum repro case (ie. a single slider) and see if you can find any case where you can/can't reproduce to isolate this further?

**Comment by Gabixel** [comment]
I think I found a way to reproduce it. Here is a video showing in detail (it happens 50% of the time):

https://user-images.githubusercontent.com/43073074/197856833-9d48f77a-1d3c-4357-9f02-54e8eeb7a62e.mp4

In the original post, I managed to reproduce it randomly, but the optimal way seems to be as follows:
- Select the slider
- Put the timeline toward the very end of the slider
- Play the music and skip the slider with the mouse wheel (or directional arrows)

I also managed to perform the opposite, which was that the slider did not play any sound (but I have no idea how):

https://user-images.githubusercontent.com/43073074/197858619-477a0efa-0478-402a-a62e-0662ca385e1e.mp4

**Comment by Gabixel** [comment]
It doesn't seem to happen with spinners.

However, one way to reproduce it 100% of the time with sliders is by skipping using the timeline instead of using the scroll wheel or keyboard (following the steps above):

https://user-images.githubusercontent.com/43073074/197860281-7e51142d-171a-4f37-80ee-b0755e6d2d75.mp4

**Comment by Gabixel** [comment]
It seems that something has changed since then and I can't reproduce it anymore on the latest version (2023.513.0) 👍🏻
