### ISSUE TITLE
Taiko drum roll lengths don't always match stable

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#20902]
### Type

Game behaviour

### Bug description

As brought up in https://github.com/ppy/osu/pull/20658, some sliders don't match stable.

Sample .osu:
```
osu file format v14

[General]
Mode: 0

[Difficulty]
HPDrainRate:6
CircleSize:7
OverallDifficulty:7
ApproachRate:10
SliderMultiplier:1.7
SliderTickRate:1

[TimingPoints]
29,333.333333333333,4,1,0,100,1,0
29,-10000,4,1,0,100,0,0

[HitObjects]
256,192,29,6,0,P|384:192|384:192,1,159.375
```

In this, the length of the slider is `128`px, the "expected length" as present in the file is `159.375`px. Stable expects the latter, lazer returns the former.

I'm making this issue now because I'm not sure how deep the rabbit hole goes...:

`ExpectedDistance` is documented as matching `Distance` if non-null: https://github.com/ppy/osu/blob/83dd295b223dbd21640c26e751074273360b41b6/osu.Game/Rulesets/Objects/SliderPath.cs#L29-L33

But this is clearly not the case in some situations (the one important here):
https://github.com/ppy/osu/blob/83dd295b223dbd21640c26e751074273360b41b6/osu.Game/Rulesets/Objects/SliderPath.cs#L283-L290

Needs more investigation.

### Version

83dd295b223dbd21640c26e751074273360b41b6

### Logs

-

**Comment by peppy** [comment]
No doubt there's going to be some special case for non-osu! rulesets..................

**Comment by peppy** [comment]
This should be re-checked with the latest release, as there were multiple fixes around taiko timing.

**Comment by smoogipoo** [comment]
I'd confirmed this issue separately from the latest changes. As mentioned in the description, it's due to `ExpectedLength` not being used for some calculations.

I'll be looking at this as a priority over the coming days.
