### ISSUE TITLE
Distance snapping shows snap grid incorrectly when swapping between common and triplets time signature

### ISSUE THREAD

**Issue by Trung0246** [ppy/osu#20938]
### Type

Game behaviour

### Bug description

1) First put some notes with snapping mode on with common time signature
2) Switch to triplets
3) Observe the weird snap behavior

### Screenshots or videos

https://user-images.githubusercontent.com/11626920/197915921-97a01b43-7481-441f-9b25-d6b9edb80a59.mp4

### Version

2022.1022.0

### Logs

[database.log](https://github.com/ppy/osu/files/9865277/database.log)
[input.log](https://github.com/ppy/osu/files/9865278/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9865279/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9865287/network.log)
[performance.log](https://github.com/ppy/osu/files/9865288/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9865289/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9865290/updater.log)

**Comment by peppy** [comment]
On a quick glance, it would seem that this is happening because your "point of reference" here is a circle placed on a 1/2 tick, which isn't valid in 1/3 timing so the distance snap alignments are off.

Still needs to be fixed, but there's the reasoning.
