### ISSUE TITLE
Distance snapping with stack leniency enabled will cause weird snap and stack behavior

### ISSUE THREAD

**Issue by Trung0246** [ppy/osu#20940]
### Type

Game behaviour

### Bug description

Stack Leniency settings: 0.7

Sometimes when placing distance snapped notes on top of each others, it will stuck in stacking mode and no way to place notes anywhere else until switch back to select mode and note place mode.

### Screenshots or videos

https://user-images.githubusercontent.com/11626920/197927650-ebed54d0-e0ca-4eb3-be45-03476c47cf0e.mp4

Possible to occur on different locations as long as notes are placed on top of each others.

https://user-images.githubusercontent.com/11626920/197928251-1d1b1cc3-9f8c-4521-857c-2cbdce4ab1f9.mp4

### Version

2022.1022.0

### Logs

[database.log](https://github.com/ppy/osu/files/9865755/database.log)
[input.log](https://github.com/ppy/osu/files/9865756/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9865757/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9865758/network.log)
[performance.log](https://github.com/ppy/osu/files/9865759/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9865760/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9865761/updater.log)

**Comment by peppy** [comment]
The main thing going on here is that while the distance spacing should (logically) be able to place back and forth between the two hitobjects, because you're overlapping the previous object, the object-to-object snap is kicking in. When this occurs, it doesn't provide a "distance snap" time value, so because you aren't manually forwarding time in the editor it places the object at the current time location.

To help me ascertain the best direction forward, can you confirm that you'd expect this scenario to snap to the existing object but also assign a future time value similar to how distance snap works (because the two positions match almost perfectly)?

**Comment by peppy** [comment]
Also can you confirm that things behave better if you always click somewhere *not* on the circle when placing subsequent circles? The object-object snap will only trigger if your cursor is close enough to another hitobject on the screen.

**Comment by peppy** [comment]
If you're able to build from source, I'd appreciate you checking out #2043 and seeing if you can still break things in a similar scenario.

**Comment by Trung0246** [comment]
> To help me ascertain the best direction forward, can you confirm that you'd expect this scenario to snap to the existing object but also assign a future time value similar to how distance snap works (because the two positions match almost perfectly)?

Yeah that's correct. The expected behavior should be like the second video in the pull request you just demonstrated.

> Also can you confirm that things behave better if you always click somewhere not on the circle when placing subsequent circles? The object-object snap will only trigger if your cursor is close enough to another hitobject on the screen.

Still stuck when not clicking onto the subsequent circle.

https://user-images.githubusercontent.com/11626920/197958189-9fe63ade-4d56-409c-b0aa-88f193d80119.mp4

> If you're able to build from source, I'd appreciate you checking out https://github.com/ppy/osu/issues/2043 and seeing if you can still break things in a similar scenario.

I guess I could setup C# envi to build and test it (already have VS2022 installed for other dev stuff).

**Comment by peppy** [comment]
You shouldn't even need visual studio, the hardest part will be the git branch checking out.

You can run with just the `dotnet` sdk using `dotnet run --project osu.Desktop` from the checkout directory.

**Comment by Trung0246** [comment]
Hmm looks like the branch fixed the initial bug of not getting stuck but when clicking outside the circle it does not snap.

https://user-images.githubusercontent.com/11626920/197967513-26941bbc-548f-49f4-a8ac-84b747a4c91f.mp4

Also looks like #2043 is kinda old (2018). Does the bug still relevant?
