### ISSUE TITLE
Extra (BMS) note sounds not played in osu!lazer with mania

### ISSUE THREAD

**Issue by Vad1mCSO2** [ppy/osu#20969]
### Type

Game behaviour

### Bug description

I downloaded Piano beatmap sets and viewing autoplay but all note are not played (in editor is soft 100), inside note are played only gameplay (in editor not working).
Beatmaps: https://osu.ppy.sh/beatmapsets/332673#mania/1317194 https://osu.ppy.sh/beatmapsets/1786993#mania/3660909

### Screenshots or videos

https://user-images.githubusercontent.com/76803825/198255313-059f0c8e-2737-41df-8b00-2909d9721809.mp4

![osu_2022-10-27_17-06-35](https://user-images.githubusercontent.com/76803825/198256592-aedde8fa-110f-4e44-beb7-bc3352dc8ead.png)

### Version

2022.1022.0

### Logs

[database.log](https://github.com/ppy/osu/files/9878265/database.log)
[input.log](https://github.com/ppy/osu/files/9878266/input.log)
[network.log](https://github.com/ppy/osu/files/9878267/network.log)
[performance.log](https://github.com/ppy/osu/files/9878269/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9878270/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9878271/updater.log)

**Comment by peppy** [comment]
Do you happen to have storyboard toggled off?

**Comment by JeromTWinL** [comment]
And also turn on `storyboard/video` option.

**Comment by Vad1mCSO2** [comment]
> And also turn on `storyboard/video` option.

Storyboard and video is on

**Comment by Vad1mCSO2** [comment]
if dimmer is 100% cannot get storyboard sounds

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/18999
https://github.com/ppy/osu/issues/9315
