### ISSUE TITLE
Fatal Error when phone auto-locks.

### ISSUE THREAD

**Issue by Mou-Ikkai** [ppy/osu#20972]
### Type

Crash to desktop

### Bug description

Sometimes, I like to have osu! play in the background so I can listen to music using all the beatmaps I have downloaded! However, I've noticed that sometimes, when I manually lock my phone, or my phone autolocks, I'll hear a quick noise from the game before it seems to have closed when I unlock my phone. (Sounds like the Bomb/Fatal Error sound?) Requiring me to reopen the game.

### Version

2022.1022.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9881732/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9881733/performance.log)
[network.log](https://github.com/ppy/osu/files/9881734/network.log)
[database.log](https://github.com/ppy/osu/files/9881735/database.log)

**Comment by bdach** [comment]
Tracking at https://github.com/ppy/osu-framework/issues/4994.
