### ISSUE TITLE
Storyboards with looping transforms can extend the outro time excessively

### ISSUE THREAD

**Issue by pablo5425** [ppy/osu#21008]
### Type

Game behaviour

### Bug description

if a song includes an ending section (i.e the video continues but there are no more notes) result screen wont appear when it should (once video ends). i think these sections try to extend a song length to around 7 minutes

this can be tested with the "new beginnings" beatmap included with lazer. in this map there are 4 minutes 50 seconds from the momend the last note is hit until result screen appears, when it should appear the exact moment it fades to black

### Screenshots or videos

![image](https://user-images.githubusercontent.com/34631489/198830738-d59f1204-8dc4-4e8a-a901-f90c3baf46d8.png)

### Version

2022.1022.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9893610/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9893611/updater.log)
[input.log](https://github.com/ppy/osu/files/9893612/input.log)
[network.log](https://github.com/ppy/osu/files/9893613/network.log)
[performance.log](https://github.com/ppy/osu/files/9893614/performance.log)

**Comment by peppy** [comment]
This looks to happen when a storyboard loops an element for a long time past the end of the beatmap. This works on stable because loops are not normalised out, but on lazer the storyboard engine is unaware of when the beatmap ends and will realise all loops from the outset.

```
Sprite,Foreground,BottomCentre,"SB\hit.png",70,460
 L,17972,40
  R,0,0,2000,0,-0.03
  R,0,2000,6000,-0.03,0.03
  R,0,6000,10000,0.03,0
```

![JetBrains Rider 2023-01-11 at 08 50 13](https://user-images.githubusercontent.com/191335/211760457-1b4398e5-67fe-4d12-bb3d-b4a6096420ce.png)

**Comment by peppy** [comment]
Bumping priority as this affects the tutorial, amongst other beatmaps.

**Comment by bdach** [comment]
If I'm reading stable source correctly, then loop commands (including anything nested within them) do not affect the map's end time at all (or at least not in ways you'd expect to), but other commands do. So if my understanding is correct, it seemingly _would_ be sufficient to just disregard `loops` here:

https://github.com/ppy/osu/blob/9bcc6bf6dae08504f18755d50ec0240fff4563a9/osu.Game/Storyboards/StoryboardSprite.cs#L74-L85

It's a bit weird that stable doesn't count loops into end time though (and some of stable code surrounding that seems 100% bugged to me), so I'm not super sure I'd want to be PRing something like that raw without further comment, or a way to access the _correct_ end time...?

**Comment by peppy** [comment]
Nice find. Maybe it's enough to reproduce that behaviour until someone needs otherwise (with an inline comment yelling that it's not 100% correct).

**Comment by Walavouchey** [comment]
i've tested against stable as well and would like to point out a minor detail as [discussed on the osb discord server](https://discord.com/channels/203050773645492224/483948766332846090/1072099377277054976):

for e.g. a 100,000 ms long map, 

```
 L,120000,10
  R,0,-120000,120000,0,1000
```

has the same effect as

```
 R,0,-120000,120000,0,1000
```

resulting in an intro at -120,000 ms and outro stretching to 120,000 ms. the first loop iteration's start and end times are taken as is (regardless of where the loop starts or how many iterations it has)

this also means that the solution in https://github.com/ppy/osu/pull/11990 wasn't in line with stable, as sprite visibility does not matter for intros or outros on stable (although i agree with the direction taken in lazer).

**Comment by bdach** [comment]
I'm aware of what @Walavouchey points out above (and it's actually the "buggedness" of stable code I [alluded to](https://github.com/ppy/osu/issues/21008#issuecomment-1418010390) above, as I found this yesterday when peering over at stable source). I just didn't want to go into detail describing it as it's just a 100% bug that isn't worth reproducing in lazer unless it causes actual issues with actual storyboards. So in the context of this particular issue I'll be looking away from that part of it.

**Comment by Walavouchey** [comment]
right, and i'd argue that having similar logic as what's currently in [`StoryboardSprite.StartTime`](https://github.com/peppy/osu/blob/master/osu.Game/Storyboards/StoryboardSprite.cs#L29-L59) in [`StoryboardSprite.EndTime`](https://github.com/peppy/osu/blob/master/osu.Game/Storyboards/StoryboardSprite.cs#L74-L85) would be more correct than however stable handled it.
