### ISSUE TITLE
Selected Mods leaderboard usually times out without processing request

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu#21024]
### Type

Performance

### Bug description

Attempting to view a beatmap leaderboard filtering for selected mods results in the request timing out after about 10 seconds and displaying a notice saying "Couldn't fetch scores!" the vast majority of the time. I do not believe this is a problem with my network as I used this feature extensively previously without any such issue occurring, and several different internet speed tests run directly after the issue occurred reported latency of no more than 100 ms and download well over 150 Mbps.

### Version

2022.1008.2-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9896890/database.log)
[input.log](https://github.com/ppy/osu/files/9896891/input.log)
[network.log](https://github.com/ppy/osu/files/9896892/network.log)
[performance.log](https://github.com/ppy/osu/files/9896893/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9896896/runtime.log)

(Only has a few requests since I tried restarting after the issue occurred)

**Comment by peppy** [comment]
Can confirm this.

Looks to be a regression after adding all scores to the new index. This was benchmarked on production in the past, so will require a bit of investigation to figure out what has changed.

**Comment by peppy** [comment]
This should now be resolved.
