### ISSUE TITLE
Custom rulesets crash every time game is opened

### ISSUE THREAD

**Issue by walkerb273** [ppy/osu#21043]
### Type

Game behaviour

### Bug description

I have many custom rulesets, some crash every time osu!lazer is opened.

### Screenshots or videos

![Screenshot_20221031_054704](https://user-images.githubusercontent.com/67877746/199130686-aae27930-ae50-4eb4-8b7d-b5dea6049a80.png)

### Version

2022.1022.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9905654/runtime.log)

**Comment by smoogipoo** [comment]
Read the error description / report to the ruleset authors / remove the rulesets. It's unfortunate but the ruleset API is still in a bit of a flux.

**Comment by EVAST9919** [comment]
Also make sure to check ruleset updates. For example, latest sanbox version works just fine, which means you haven't checked if you are using latest ruleset version.
