### ISSUE TITLE
Skin "custom ingame guis" not behaving the same way as in stable.

### ISSUE THREAD

**Issue by deok420** [ppy/osu#21048]
### Type

Cosmetic

### Bug description

This issue occurs on skins with some custom ingame gui elements like WhiteCat 2.0. The issue is that some elements overlay others not how they're supposed to. On the screenshot below it's shown that the element LegacySongProgress is overlaying the little box. It's supposed to be under the box so it gives it that cool effect of filling up the box as the song carries on. I could think of a few more skins that might have an issue with this, but I mention specifically LegacySongProgress, because a lot of skins have this little detail.

Skin link: https://mega.nz/folder/cMtEVALC#3t0G9_TbvPIC0awP5-78XQ/file/IVUXEYKB

### Screenshots or videos

![image](https://user-images.githubusercontent.com/90860478/199177573-978b24fd-70eb-4dbd-8a8f-a659fbe292fb.png)

### Version

2022.1031.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/9907675/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9907676/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9907677/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9907678/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9907679/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9907680/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9907681/updater.log)
[database.log](https://github.com/ppy/osu/files/9907682/database.log)
[input.log](https://github.com/ppy/osu/files/9907683/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9907684/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9907685/network.log)

**Comment by peppy** [comment]
Could you please provide a screenshot showing how it should actually look?

**Comment by deok420** [comment]
![image](https://user-images.githubusercontent.com/90860478/199187246-b908266b-a0ad-4e8d-a537-70123ad00e31.png)

**Comment by peppy** [comment]
No guarantees we'll be able to support this perfectly, but I think it's worth attempting. The main issue being incorrect depth ordering (in theory a simple one?), but it also looks to be misaligned slightly.

**Comment by NatureHog** [comment]
I've also experienced this, with multiple skins. (Mainly the reason I've been holding off on switching to lazer...)

Judging by the skin editor, it looks as if the "LegacyHealthDisplay" in osu!lazer is not only in the wrong "layer", but also off-center.

Here a few examples, including links to the forum pages:
_Every screenshot below was taken on a 16:9 screen with 1080p resolution, with the same beatmap in the background._

**[WhiteCat (same as OP)](https://osu.ppy.sh/community/forums/topics/1279815?n=1)**
Stable:
![screenshot004](https://user-images.githubusercontent.com/55314658/199252022-d23c1f74-1673-487b-9aae-ebc4e17fbe7e.jpg)
Lazer:
![osu_2022-11-01_14-56-14](https://user-images.githubusercontent.com/55314658/199252232-e4b3fd75-ef44-4b86-a394-42f35d040086.jpg)

**[BlooMoon ReDone (only edited the scorebar photo on the left, nothing else was changed)](https://osu.ppy.sh/community/forums/topics/1488743)**
Stable:
![screenshot005](https://user-images.githubusercontent.com/55314658/199252749-bc9a1fbc-22a3-401b-8824-e73b9d708242.jpg)
Lazer:
![osu_2022-11-01_14-56-37](https://user-images.githubusercontent.com/55314658/199253071-5d1237af-4261-4636-9939-8437f1cfa310.jpg)

**[〉 DknsK ┐ (the skin defaults the accuracy to the middle of the screen)](https://osu.ppy.sh/community/forums/topics/1627924?n=1)**
Stable:
![screenshot006](https://user-images.githubusercontent.com/55314658/199253674-3ac9c204-2264-49e7-80d4-5d27704480e6.jpg)
Lazer:
![osu_2022-11-01_14-56-58](https://user-images.githubusercontent.com/55314658/199253832-d809c11c-b685-4564-9d61-5c3172f8602f.jpg)

[Ralsei Dark](https://osu.ppy.sh/community/forums/topics/1629393?n=1)
Stable:
![screenshot007](https://user-images.githubusercontent.com/55314658/199254200-023451e8-b82c-41f3-a274-f6ba61f8972d.jpg)
Lazer:
![osu_2022-11-01_14-57-17](https://user-images.githubusercontent.com/55314658/199254320-9d0db474-be90-4510-870e-74022520400c.jpg)

**Comment by NatureHog** [comment]
I think I found out why this is happening.

It seems to be the different positioning of the score and accuracy.
Stable "pushes" the score number more to the top right than lazer.

Here is an onion-skin of both versions, using the "default" skin from both versions:
_"Default" for stable, "Classic" for lazer_
![onionskin-score](https://user-images.githubusercontent.com/55314658/200957607-efb15259-9cf1-4b7d-abd4-d0ee1be791d2.png)

Here are a few other images, all using the same "default" skins as above, including a "non-cropped" screenshot:
https://1drv.ms/u/s!AqwZ15G5dYM5h6gyXSWZ7G1zGq295Q?e=2y5jBI

**Comment by peppy** [comment]
Yep, it's going to be a matter of trying to match the alignments perfectly if that's what we're going for.

**Comment by NatureHog** [comment]
I don't know how this is implemented in stable, but wouldn't it be possible to look up how stable is programmed to align the score + accuracy, and replicate it more accurately for every legacy skin by default?
(I don't know if that statement made sense logically...)

**Comment by 0xallie** [comment]
> Also if my assumptions are correct without checking the skin files, we would only be able to get this to work as a single aspect ratio.

Yes, even in stable separate versions of these skins are needed for different aspect ratios.
