### ISSUE TITLE
Lazer accessing wrong directory on android

### ISSUE THREAD

**Issue by xStormyy** [ppy/osu#21058]
### Type

Game behaviour

### Bug description

I'm not sure if this just affects android 8 and below, but lazer tends to access some random directory instead of storage/emulated/0 (150 in my case). I am also not able to access storage/emulated/0 for some odd reason.

### Screenshots or videos

![storage_issue_lazer](https://user-images.githubusercontent.com/90779060/199210191-071f59c0-9214-4f19-bdb4-a8797ef88974.jpg)

### Version

2022.1031.0

### Logs

[database.log](https://github.com/ppy/osu/files/9908911/database.log)
[network.log](https://github.com/ppy/osu/files/9908912/network.log)
[performance.log](https://github.com/ppy/osu/files/9908913/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9908914/runtime.log)

**Comment by bdach** [comment]
#11911
