### ISSUE TITLE
low fps on samsung a6 tablet

### ISSUE THREAD

**Issue by Faresgmr** [ppy/osu#21063]
### Type

Performance

### Bug description

Running on Samsung Galaxy Tab A6 (2016)

The game runs on 10-17 fps and keeps stuttering (the stutter is mostly in maps)

I'm not sure if this has something to do with my device having an Exynos processor

### Version

2022.1101.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9912855/database.log)
[network.log](https://github.com/ppy/osu/files/9912856/network.log)
[performance.log](https://github.com/ppy/osu/files/9912857/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9912859/runtime.log)

**Comment by bdach** [comment]
Mobile performance is a constant work-in-progress and this issue is not specific enough to be actionable. Unless the performance has noticeably regressed in the recent releases then there's not much point in having this issue open.
