### ISSUE TITLE
Light does not cover notch area

### ISSUE THREAD

**Issue by KittyLikeme** [ppy/osu#21061]
### Type

Cosmetic

### Bug description

Upon launching the game, there is a light that flashes on the screen. But if the notch area is enabled in the settings, the light does not reach it.

### Screenshots or videos

https://user-images.githubusercontent.com/117192303/199272442-a1ba0066-c696-424e-9015-e2e137824eee.mp4

### Version

2022.1031.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/9911718/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9911719/performance.log)
[network.log](https://github.com/ppy/osu/files/9911720/network.log)
[database.log](https://github.com/ppy/osu/files/9911721/database.log)

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/21050.
