### ISSUE TITLE
Snaking in sliders + Freeze Frame mod cause slider ticks to appear before slider bodies

### ISSUE THREAD

**Issue by Kaerulans** [ppy/osu#21075]
### Type

Game behaviour

### Bug description

Title. 
First video shows the bug, second video is nomod for reference.
Map link: https://osu.ppy.sh/beatmapsets/421061#osu/910815

### Screenshots or videos

https://user-images.githubusercontent.com/55179197/199478009-0c9e3594-3699-40ce-954d-5b02bf9e553d.mp4

https://user-images.githubusercontent.com/55179197/199478063-223d3920-127a-41a5-b2bc-3e254ee3b73e.mp4

### Version

2022.1101.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9919856/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9919857/performance.log)
[network.log](https://github.com/ppy/osu/files/9919858/network.log)
[input.log](https://github.com/ppy/osu/files/9919859/input.log)
[database.log](https://github.com/ppy/osu/files/9919860/database.log)

**Comment by mk56-spn** [comment]
did a quick fix and exempted the slideticks from the freeze, like was done for the sliderrepeats. doesnt feel ideal but works

https://user-images.githubusercontent.com/74463310/199502056-364cf18a-7d56-46cc-99bc-1ba21480a353.mov
