### ISSUE TITLE
Hit objects may disappear in editor when using argon skin

### ISSUE THREAD

**Issue by JoppyLoppy** [ppy/osu#21089]
### Type

Cosmetic

### Bug description

I was mapping in the editor and suddenly noticed that hitobjects were disappearing

Hitobjects disappear if a few seconds of the timeline is scrubbed "quickly"

- Can be fixed by exiting and reentering map editor (can come back though)
- Broken hitobjects do not effect gameplay. Testing the map proves that all hitobjects are visible and functional
- Objects can reappear if the timeline is scrubbed multiple times (but can disappear again)

- _Not sure how to reproduce other than scrubbing 5 or more seconds of the timeline "quickly"_
- _Not sure if it depends on time, or a % of the timeline._

### Screenshots or videos

![image](https://user-images.githubusercontent.com/59589451/199642323-63dc776e-7e54-4378-91d7-37e49906e9e8.png)
![image](https://user-images.githubusercontent.com/59589451/199642481-8486c8ed-23ab-4c31-9d1c-f9bd9c723672.png)
![image](https://user-images.githubusercontent.com/59589451/199642539-2dd7ed45-c4d8-4b0b-9e35-6eb257b02abb.png)

https://user-images.githubusercontent.com/59589451/199642596-342b66d8-7715-46ae-9887-44ac3a9165bc.mp4

### Version

2022.1101.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/9925494/network.log)
[performance.log](https://github.com/ppy/osu/files/9925495/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9925496/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9925497/updater.log)
[database.log](https://github.com/ppy/osu/files/9925498/database.log)
[input.log](https://github.com/ppy/osu/files/9925499/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9925500/legacy-ipc.log)

**Comment by peppy** [comment]
@JoppyLoppy Could you test with triangles or classic skin and see if you can reproduce the same issue?

**Comment by JoppyLoppy** [comment]
> ia

will check now

**Comment by JoppyLoppy** [comment]
> @JoppyLoppy Could you test with triangles or classic skin and see if you can reproduce the same issue?

I wasn't able to reproduce the issue with the triangles or classic skin, or a separate skin that I downloaded previously.
Seems like it's specific to Argon.

**Comment by peppy** [comment]
Weirdly, I'm unable to reproduce this on both the latest release nor `master`...

**Comment by JoppyLoppy** [comment]
![image](https://user-images.githubusercontent.com/59589451/199841475-9f7d0537-f4a4-41b9-88c8-9907630081f9.png)
That's strange...
Let me know if you need more information or testing on my end

**Comment by peppy** [comment]
This is quite unsettling, as it points to something inherently wrong with transform rewinding logic. The weird part is, I can't see any reason why this same issues *shouldn't* also be occurring in the triangles skin.

![osu! 2023-01-24 at 08 27 02](https://user-images.githubusercontent.com/191335/214244024-1df13bf3-854f-44cc-9756-6734babf4a04.png)
![osu! 2023-01-24 at 08 27 06](https://user-images.githubusercontent.com/191335/214244039-8f12f033-9df6-4814-92a4-72c9bb75f98c.png)

**Comment by peppy** [comment]
Actually I guess since this is not a `DrawableHitObject` (which has specific `ClearTransformsAfter` and also initial transforms specs), there's really nothing protecting this class from getting incorrect transforms applied. Especially with the `Scheduler.AddOnce` call, it's very possible for transforms to be applied out of band.

**Comment by peppy** [comment]
Right, and `DrawableHitObject`'s safeties are applied to the full hierarchy, which protected the non-scheduled case correctly.
