### ISSUE TITLE
Star bursts are missing in gameplay

### ISSUE THREAD

**Issue by peppy** [ppy/osu#21091]
### Discussed in https://github.com/ppy/osu/discussions/20081

<div type='discussions-op-text'>

<sup>Originally posted by **smileyhead** September  2, 2022</sup>
osu!stable has a star burst effect for when kiai time starts, which, in my opinion, really improves the experience while playing a song. Lazer is currently missing this effect. Would it be possible to add it back?

https://user-images.githubusercontent.com/15932372/188006472-3ca74766-9d6b-4f59-9e45-11eacaf1b61d.mp4

</div>

**Comment by NullifiedJosh** [comment]
I think it would be helpful to provide the code from stable to get an idea of the animations.
