### ISSUE TITLE
Disable or improve parallax to be less distracting during play

### ISSUE THREAD

**Issue by Stekeblad** [ppy/osu#2109]
While I played my first map in lazer for a long time I noticed that the background was slightly moving in the opposite direction of the cursor. This behaviour is in stable as well but I do not think it happens during gameplay there. The background "wiggling" was a bit confusing to play with so I want to start a discussion about if this should happen during gameplay or if the wiggling should be excluded from it.

It felt a little like if moving the cursor also moves the background, the background would drag the circles and sliders with it, but I know it don't and that was confusing.

Lazer version: 2018.213.0

**Comment by VPeruS** [comment]
It's parallax backgroud effect, you can disable it in settings

**Comment by Stekeblad** [comment]
Thanks for the tip about the setting.I like the effect but I think it should not happen during gameplay

**Comment by peppy** [comment]
It will likely be dialled back or disabled before release. I think everyone agrees that it is very distracting with its current implementation.

**Comment by Frontear** [comment]
This should potentially be controlled from a *temporary toggle*, where it gets disabled at https://github.com/ppy/osu/blob/c701b8eae506fe8d50caacfa22806df0ccbcbdd2/osu.Game/Screens/Play/PlayerLoader.cs#L61, and re enabled from the config.

**Comment by TheCuhphen** [comment]
Are there still any plans to make parallax during gameplay toggleable or just outright remove it? 

I play often without full background dim -usually never less than 90%-  and while playing maps that require circular aim like [Can't Defeat Airman] (https://osu.ppy.sh/beatmapsets/24313#osu/104229) it is still incredibly noticeable and distracting to the point of giving me motion sickness. 

I do like the effect it has on menus and such, and understandably it seems that the map background seems to be tied together between the menu and gameplay. 

If there is a way for this to be toggleable as an option, it would allow whatever subset of people who have the same issue as I do, to enjoy the game the way they'd like to and would be immensely appreciated.

The obvious solution of just playing with 100% background dim is not acceptable for me as I don't always play that way, and this issue isn't present in stable as parallax isn't applied to the background during gameplay. If it is possible I am sure I and a good amount of other players would be grateful for it.

**Comment by peppy** [comment]
There's already a setting to disable it.

If you mean splitting the setting between menus and gameplay, then maybe we'll add that one day, but no promises.

**Comment by NSilviaS15** [comment]
Just returned to osu for a while and accidentally downloaded lazer instead of stable, and stuck with it.
The gameplay parallax is just subtle enough to make me consistently doubt if it's static, which is disorienting.
Worse with more vibrant backgrounds, as well as big jumps across the whole play area.
The UI feels flat and less interactive without parallax, but in gameplay the ease in reading gives ~2% more accuracy in my experience.
Gameplay parallax isn't applied to maps with storyboard or video anyway, so why does it exclusively apply to static BGs?
Playing with parallax off now, but if it could be a menu-only thing or a separate toggle for gameplay that'd be nice.
