### ISSUE TITLE
Backspace key does not register for TextBox

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2110]
I noticed that the backspace key does not register for either the SettingsSearchBar or the BeatmapSearchBar. The backspace key does work on the login section.

**Comment by peppy** [comment]
I believe this has already been fixed. Are you sure your framework is up-to-date?

**Comment by Frontear** [comment]
Running the latest *release*. Will attempt building from source, and update the status.

**Comment by peppy** [comment]
A new release is now live with a fix for this. Please update and close after testing.

**Comment by Frontear** [comment]
Not currently at an accessible PC. Will update this issue ASAP..

**Comment by Frontear** [comment]
Issue has been resolved!
