### ISSUE TITLE
Unable to Send Chat messages after opening chrome

### ISSUE THREAD

**Issue by Vunistic** [ppy/osu#21128]
### Type

Other

### Bug description

After clicking on a song to download it and downloading it through chrome i am unable to hit enter in chat. Everything else works like typing in chat, and pressing escape but i send my messages with enter.

### Version

b20221104.1beta

### Logs

[osu!auth.log](https://github.com/ppy/osu/files/9942114/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/9942115/runtime.log)
[session.log](https://github.com/ppy/osu/files/9942116/session.log)
[update_success.log](https://github.com/ppy/osu/files/9942117/update_success.log)

**Comment by bdach** [comment]
This repository is for lazer issues only. Stable issues are not accepted here.
