### ISSUE TITLE
it says that the website is unsecure?!?!?!

### ISSUE THREAD

**Issue by BoydoesgamingOfficial** [ppy/osu#2113]
ok so. i was just going to look for map contests and it says that this website is dangerous?
![2018-02-24](https://user-images.githubusercontent.com/36111611/36632134-4ec8809a-197a-11e8-9159-405de124f717.png)

**Comment by Shawdooow** [comment]
shouldn't this be on the osu-web repo if anything?

**Comment by peppy** [comment]
Wrong repository.

This means you are likely on an insecure network. Something is intercepting your traffic.
