### ISSUE TITLE
`EffectControlPoint`s don't save correctly when scroll speed is adjusted on a ruleset that doesn't support it

### ISSUE THREAD

**Issue by NovaliX-Dev** [ppy/osu#21139]
### Type

Cosmetic

### Bug description

When effects are set in the timing panel, the editor saves them weirdly.
- Only the first kiai effect is saved
- The "Skip Bar Line" option is copied at different time points in the map, it even create ones. In rare cases some of the time points are also not accessible (the editor switch to the one above it).
- Both effects are saved with a value of 1 (which i assume is the default value)

#### Steps to reproduce
Kiai bug:
1. Open the editor and go to the timing section
2. Add a first time point with the kiai effect turned on. Set a random value.
3. Add a second time point with the same effect and another value.
4. Save the map, close it and reopen it.

Skip Bar Line bug:
1. Open the editor and go to the timing section
2. Add a time point with the "Skip Bar Line" option turned on. Set a random value.
4. Save the map, close it and reopen it.

#### Kiai bug

https://user-images.githubusercontent.com/79244938/200195769-b59568bd-10be-4415-9d45-b56dd940d048.mp4

#### Skip Bar Line bug

https://user-images.githubusercontent.com/79244938/200195851-678abdb2-1f5c-44a5-bec6-164c9634e345.mp4

### Version

2022.1101.0-lazer

#### Platform informations
Os : Windows 11

### Logs

[database.log](https://github.com/ppy/osu/files/9946860/database.log)
[input.log](https://github.com/ppy/osu/files/9946861/input.log)
[network.log](https://github.com/ppy/osu/files/9946862/network.log)
[performance.log](https://github.com/ppy/osu/files/9946863/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9946865/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9946866/updater.log)

**Comment by peppy** [comment]
This is a touch awkward. The decoding of scroll speed is only done for rulesets which support it:

https://github.com/ppy/osu/blob/6177df2a2486dfbbb98cbd57fb408c61b8c4e534/osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs#L453-L454

This would be fixed if we moved to a new serialisation format (at which point we wouldn't be transferring scroll speed values from current SV). I'm not sure how to better handle it until then. Maybe the setting should just be disabled on rulesets like osu!?

**Comment by NovaliX-Dev** [comment]
So Scroll Speed are not supposed to be used in osu! mode. What are their primary use ?

I found them useful for the kiai effect for changing the intensity.
