### ISSUE TITLE
Can't import a map

### ISSUE THREAD

**Issue by deok420** [ppy/osu#21137]
### Type

Game behaviour

### Bug description

 I tried importing Save me to lazer, but the map just doesn't show up. I tried to import it from osu direct too, but it didn't work. There is an example video.

Beatmap: https://osu.ppy.sh/beatmapsets/594170#osu/1256809

[client.zip](https://github.com/ppy/osu/files/9945508/client.zip)

### Screenshots or videos

https://youtu.be/hwmZN0FH8-8

### Version

2022.1101.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9945494/database.log)
[input.log](https://github.com/ppy/osu/files/9945495/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9945496/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9945497/network.log)
[performance.log](https://github.com/ppy/osu/files/9945498/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9945499/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9945500/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9945501/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9945502/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9945503/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9945504/updater.log)

**Comment by peppy** [comment]
- You've included the wrong log files (they are from stable, not lazer)
- Please link the beatmap
- Please attach your `client.realm` after zipping it.

**Comment by deok420** [comment]
Done, sorry for the issues.

**Comment by deok420** [comment]
Update: https://youtu.be/KTqyVKw4R00

I don't know why it does that. I used a software called "Everything", that basically allows you to search for folders and filenames on your entire computer very fast, but I don't find any folder that has anything to do with the map.

It plays the actual map and the actual song, but it doesn't appear anywhere on the song select list.

**Comment by deok420** [comment]
I cannot believe how dumb I am.

Turns out I hid the map and that's why I couldn't find it. Took me a good while to realize. Don't make the same mistake as me.
