### ISSUE TITLE
Combo and Score on website aren't the same from actual gameplay shows (replay)

### ISSUE THREAD

**Issue by rodrigoelicer** [ppy/osu#2114]
Hi,

I hope this issue isn't some sort of duplicate, but I felt the need to report this.

Basically I was looking at a random replay of mine (not in lazer) and realized that the score shown on the website and ingame scoreboard weren't the same from what there was on the replay. Screenshots:

579 combo + less score
![10335998](https://user-images.githubusercontent.com/16049165/36633332-82b47fec-1972-11e8-81e4-4df2bc3a554c.jpg)
![ss 2018-02-24 at 02 51 34](https://user-images.githubusercontent.com/16049165/36633335-8c8f37d2-1972-11e8-8776-e77de9f622b0.png)

580 combo + more score (that means to be part of top50)
![10336035](https://user-images.githubusercontent.com/16049165/36633334-899fc172-1972-11e8-9edf-c8e7cd5c2653.jpg)

the map in question is https://osu.ppy.sh/b/1291657

I think it's somehow related to the last note being a spinner, but can't really tell more.

**Comment by peppy** [comment]
this is a repo for lazer development
