### ISSUE TITLE
Storyboards with variables not working

### ISSUE THREAD

**Issue by Proxima36** [ppy/osu#21159]
### Type

Game behaviour

### Bug description

osb file in this [beatmap set](https://osu.ppy.sh/beatmapsets/774573#osu/1627968) has a "variables" block that is ignored by the Laser or processed incorrectly. Maybe the problem is that for some reason non-printable unicode characters are used as names for variables.

### Screenshots or videos

| Stable | Lazer |
| ------------- | ------------- |
|  ![osu!_2022-11-07_19-50-54](https://user-images.githubusercontent.com/65703743/200367722-61adc5aa-0185-4c22-bdc0-cf9690d9c762.png)|![osu!_2022-11-07_19-55-05](https://user-images.githubusercontent.com/65703743/200368756-79ed21e5-f270-44d6-b958-2827e3842bed.png)|

### Version

2022.1101.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/9954493/runtime.log)

**Comment by peppy** [comment]
Why the fuck would anyone do something that stupid.

**Comment by Coppertine** [comment]
It's mostly processed incorrectly as the variables itself range from U+0000 to U+001F (Null and Unit Seperator respectively).
As well, osu! stable adds `.png` if the path to the sprite doesn't have any extension to it..

**Comment by Coppertine** [comment]
> Why the fuck would anyone do something that stupid.

One word, optimisation. The osb file itself is 32mb due to the rotoscoped "animation".
