### ISSUE TITLE
Tournament Client does not populate Beatmap Seeding Results on Startup

### ISSUE THREAD

**Issue by DerHamm3r** [ppy/osu#21152]
### Type

Game behaviour

### Bug description

I imported a generated bracket.json (AppScript by Coppertine that relies on lazer to populate the non-important values) and noticed that the seeding page for each team did not immediately show the team's placement on a map, then went into the Team Editor and checked the seeding results there and all scores were properly filled in. The scores were only properly displayed in the Seeding tab after entering every team's seeding results and hitting Save Changes twice (If i do it once it only populates the NM and HD pool?) 

Step by Step recreation:
- Open Lazer Tourney Client with the attached bracket.json
- Go to Seeding page and see that Seeding Beatmap Data is missing
- Go to Team Editor
- Click Edit seeding results for a team
- Confirm that the scores are filled in properly
- Hit Save Changes in the seeding results editor
- Go back to Seeding
- Change the shown team to any other team and then switch back to the original team
- Half the scores should be shown now
- Go back to the seeding results editor for that team
- Scroll down to see HR and DT scores
- Hit save changes again
- Go back to the Seeding tab and switch to a different team again, then back to the original
- All scores are shown now

^ all of the above should not be necesary and the populating should happen on startup

### Screenshots or videos

Empty results:
![](https://media.discordapp.net/attachments/1039080818921971744/1039101738621341718/image.png)

Seeding Results:
![](https://media.discordapp.net/attachments/1039080818921971744/1039101809572184094/image.png)

After saving once:
![](https://media.discordapp.net/attachments/1039080818921971744/1039102103529988166/image.png)

Confirmed that the scores for HR and DT were there:
![](https://media.discordapp.net/attachments/1039080818921971744/1039102178775810120/image.png)

After saving again:
![](https://media.discordapp.net/attachments/1039080818921971744/1039106592467079178/image.png)

bracket.json that I extracted with some populated and some unpopulated beatmaps:
https://cdn.discordapp.com/attachments/1039080818921971744/1039102477770948618/bracket.json

### Version

2022.1101.0-lazer

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/9949980/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9949981/network.log)
[performance.log](https://github.com/ppy/osu/files/9949982/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9949983/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9949984/updater.log)
[database.log](https://github.com/ppy/osu/files/9949985/database.log)
[input.log](https://github.com/ppy/osu/files/9949986/input.log)

**Comment by peppy** [comment]
Are you able to make a video showing the process? I'm not super familiar with the seeding screens so it would be helpful to see in motion.

**Comment by peppy** [comment]
Can you check whether this bracket file looks more correct?

[bracket.json.zip](https://github.com/ppy/osu/files/9950308/bracket.json.zip)

It looks like a lot of data wasn't populated (and wasn't being attempted to be due to half the entries having already populated data), so I've adjusted the population checks accordingly.

**Comment by DerHamm3r** [comment]
> Can you check whether this bracket file looks more correct?
> 
> [bracket.json.zip](https://github.com/ppy/osu/files/9950308/bracket.json.zip)
> 
> It looks like a lot of data wasn't populated (and wasn't being attempted to be due to half the entries having already populated data), so I've adjusted the population checks accordingly.

Yeah this one is displaying all scores correctly for me.
