### ISSUE TITLE
Display `-` symbol when tracked in-game leaderboard score is below 50

### ISSUE THREAD

**Issue by Piggey** [ppy/osu#21176]
### Type

Cosmetic

### Bug description

When there are more than 50 scores already set, gameplay leaderboard shows at the beggining that the player is 51st

![image](https://user-images.githubusercontent.com/49120531/200559534-53cf3529-f764-471d-8e01-8f76de880393.png)

This would imply that with the score that player has currently, they would end up with 51st place on the map's leaderboard, which is not always true.

What I would suggest is to change the current `#51` position to `?` or something, untill player beats the 50th score.

### Version

2022.1101.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9960974/database.log)
[input.log](https://github.com/ppy/osu/files/9960975/input.log)
[network.log](https://github.com/ppy/osu/files/9960976/network.log)
[performance.log](https://github.com/ppy/osu/files/9960977/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9960978/runtime.log)

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/discussions/20538

**Comment by peppy** [comment]
it's probably fine to just change it to "??" or "-" as a temporary thing.
