### ISSUE TITLE
Maps sometimes got deleted, marked as downloaded in browser. 

### ISSUE THREAD

**Issue by dZarkX** [ppy/osu#21187]
### Type

Game behaviour

### Bug description

After playing Osu!Lazer everyday, my map number keeps decreasing, being potentially deleted, or marked as corrupted(don't know how to check this). Noticed it while checking collections, with maps i usually play everyday, now gone. 

While trying to download them again they are marked as already downloaded in in-game browser. Pressing "Go to beatmap" forwards me to it but its not shown in the map selector, I can still play it by pressing enter.

Using RESTORE options don't work.

I think it happened before, few weeks ago I tried to copy Osu! folder from SSD to HDD for more space and in the process some maps were lost. I fixed it by copying new folder back to the old one but this seems like totally different problem. 

I don't think its purely disk issue, don't have any problems playing different games and doing other stuff.

### Screenshots or videos

![osu_2022-11-09_13-16-05](https://user-images.githubusercontent.com/51414016/200828198-63e0370c-af4e-44f3-b3d3-f7a90f76e3ad.jpg)
![osu_2022-11-09_13-16-15](https://user-images.githubusercontent.com/51414016/200828201-5592006a-d880-4987-96d4-fb3cbd868a4a.jpg)
![osu_2022-11-09_13-16-19](https://user-images.githubusercontent.com/51414016/200828205-b46a84e2-5643-4c58-a15b-2f9e921ff112.jpg)
![osu_2022-11-09_13-21-38](https://user-images.githubusercontent.com/51414016/200829215-b63e8e78-5ef3-451d-8eed-b0f41251264c.jpg)

### Version

2022.1101.0-Lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9970910/database.log)
[input.log](https://github.com/ppy/osu/files/9970911/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9970912/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9970913/network.log)
[performance.log](https://github.com/ppy/osu/files/9970914/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9970915/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9970916/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9970917/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9970918/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9970919/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9970920/updater.log)

**Comment by peppy** [comment]
Are you potentially hiding them?

**Comment by dZarkX** [comment]
I don't think so, using restore hidden difficulties does nothing

**Comment by ItsJustSomeDude** [comment]
Please zip and attach client.realm.

**Comment by dZarkX** [comment]
[client.realm.zip](https://github.com/ppy/osu/files/9971796/client.realm.zip)

**Comment by peppy** [comment]
I can't seem to open that database file. Could you please try attaching it once more (while the game isn't running to make sure nothing weird happens)?

**Comment by dZarkX** [comment]
Sorry for not providing updates on this, but i fixed it, and found totally new bug. The game was sorting by "Date Ranked" and for some reason, it hides random maps(?) even if they are ranked, like Blue Zenith in screenshot. 


[client.realm.zip](https://github.com/ppy/osu/files/10056092/client.realm.zip)

Client realm files, packed while the game is closed

**Comment by peppy** [comment]
Thanks. We'll track this in #21332 as part of ranked-status-not-being-updated-correctly.
