### ISSUE TITLE
After dragging the replay seek back and forth, replay is still acting like the seek is getting dragged despite the song playing normally after releasing the mouse

### ISSUE THREAD

**Issue by CrushyGreenRen** [ppy/osu#2119]
I've decided to watch an Autoplay replay, and dragged the seek back and fourth. I've noticed this weird issue. (Yes, I am updated to the latest version.)

To reproduce the problem:

1. Have Autoplay enabled.
2. Drag the seek back and fourth 
3. You will notice that once you release your mouse, the song plays normally, but the replay thinks you're still dragging the seek back and fourth. (This lasts for a few seconds)

video preview: https://www.youtube.com/watch?v=507FOPm9L8c

**Comment by peppy** [comment]
This is intentional behaviour for now. It needs to reprocess all frames to return to the current seek point, which can take some time. It will improve as we optimise.
