### ISSUE TITLE
Scores updated then revert to previous score set. (Lazer)

### ISSUE THREAD

**Issue by ChaBoiNeil** [ppy/osu#21194]
### Type

Other

### Bug description

I set some scores yesterday and they updated on the live leaderboards after I set them. But not even a full day later the scores have been removed and reverted to the previous score that I had set before hand. Don't know if there is stuff being updated in the backend that may have caused this, but I thought I would bring this up none the less. Thanks.

### Screenshots or videos

![Score Issue](https://user-images.githubusercontent.com/103234709/200981524-0fdbf7cf-8a64-42e7-8017-987986c309f1.png)

### Version

Lazer 2022.1101.0

### Logs

N/A

**Comment by smoogipoo** [comment]
There were some indexing shenanigans that happened over the past day, @peppy ?

**Comment by peppy** [comment]
We are currently re-running indexing, scores will be outdated for some days.
