### ISSUE TITLE
Dummy beatmap card rendered after beatmap update

### ISSUE THREAD

**Issue by TwoQuantumBits** [ppy/osu#21213]
### Type

Game behaviour

### Bug description

After hitting "update" on the beatmap card and the beatmap had been updated, the client rendered another (yet non-interactive) beatmap card with the "Update" button shown. This card actually scrolled with the beatmap list as well and also persisted across switching playlists, only disappearing when the beatmap list was actually emptied.

### Screenshots or videos

From master build (commit 8154eaa):

![image](https://user-images.githubusercontent.com/37262651/201481103-03efb373-8b3d-42b9-9788-2e5044be33b0.png)

https://user-images.githubusercontent.com/37262651/201481854-fb81eb51-680d-4eef-9939-7e179070dbf2.mp4

From master build (commit f52540c):

https://user-images.githubusercontent.com/37262651/201518611-d4c0d302-3325-4b15-a77a-3c5a77019870.mp4

### Version

master build (commit 8154eaa, commit f52540c)
_(note: this bug is **not** observed in release 2022.1101.0)_

### Logs
From master build (commit 8154eaa):
[database.log](https://github.com/ppy/osu/files/9995276/database.log)
[input.log](https://github.com/ppy/osu/files/9995270/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9995271/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9995272/network.log)
[performance.log](https://github.com/ppy/osu/files/9995273/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9995274/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9995275/updater.log)

From master build (commit f52540c):
[database.log](https://github.com/ppy/osu/files/9997024/database.log)
[input.log](https://github.com/ppy/osu/files/9997025/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9997026/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9997027/network.log)
[performance.log](https://github.com/ppy/osu/files/9997028/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9997029/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9997030/updater.log)

### Other attachments
[client.realm.zip](https://github.com/ppy/osu/files/9997034/client.realm.zip) (for f52540c)

**Comment by bdach** [comment]
Does this persist after a restart? If yes, please attach `client.realm`.

**Comment by TwoQuantumBits** [comment]
It appears that this behavior still persists after several restarts, and even across updates (for context, earlier when I opened the client, a notification popped up saying my database was "too new" to use with 8154eaa, so I had to update to f52540c).

I've updated the original post to add another video, and (as requested) the `client.realm` file for this instance.

**Comment by liesened** [comment]
Probably related, using version 2022.1117.0 something very similar happens after deleting all difficulties of the beatmap, although the dummy card disappears after re-entering song select.
![image](https://user-images.githubusercontent.com/101940285/202441919-89585de4-dd35-4049-b1af-a43ffdd8c869.png)
![image](https://user-images.githubusercontent.com/101940285/202442002-3199f815-de76-4e20-9588-8a7806f49bac.png)

**Comment by frenzibyte** [comment]
Tracking in https://github.com/ppy/osu/issues/21272

**Comment by peppy** [comment]
You forgot to transfer the p0 tag 😅
