### ISSUE TITLE
Updating very old beatmaps doesn't work properly

### ISSUE THREAD

**Issue by mandelbrotse** [ppy/osu#21219]
### Type

Game behaviour

### Bug description

I have just imported a lot of beatmaps from stable onto lazer, and there is one glaring issue. Some very old beatmaps (examples were ranked in 2008) don't update properly. When they update, they seem to "duplicate." They cannot be deleted manually, but seem to not actually exist as they disappear after relaunch. However, even after relaunch, the beatmaps still seem to have an update available. This does not happen on newer beatmaps. Clicking "update" on the duplicates does not do anything.

Even when downloading a beatmap from in-game after deleting the original, it still wants to update.

### Screenshots or videos

![osu_2022-11-13_14-06-35](https://user-images.githubusercontent.com/118090364/201504224-56b2e011-cc84-4edd-8ffa-f8050921657a.png)
![osu_2022-11-13_16-26-59](https://user-images.githubusercontent.com/118090364/201504226-a8d2e081-0e78-4681-8c22-253c217b5728.png)

### Version

2022.1101.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9996437/database.log)
[input.log](https://github.com/ppy/osu/files/9996438/input.log)
[network.log](https://github.com/ppy/osu/files/9996439/network.log)
[performance.log](https://github.com/ppy/osu/files/9996440/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9996441/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9996442/updater.log)

**Comment by peppy** [comment]
Please link the beatmap in question. It's likely going to be another case of server-side version/hash being incorrect.

**Comment by reo-the-enby** [comment]
Not the same map but it happens with this map too for me: https://osu.ppy.sh/beatmapsets/16#osu/119

**Comment by mandelbrotse** [comment]
https://osu.ppy.sh/beatmapsets/940#osu/6903 

https://osu.ppy.sh/beatmapsets/1373#osu/15463 

the beatmap sets in question. I'll come back if I find any others.

**Comment by frenzibyte** [comment]
Please include any beatmap you find in https://github.com/ppy/osu/discussions/19551. Closing this as duplicate.
