### ISSUE TITLE
Spanish, polish and french strings in first-run are in lowercase

### ISSUE THREAD

**Issue by r0xANDt0l** [ppy/osu#21234]
### Type

Cosmetic

### Bug description

When you run the first run setup, the strings for Spanish, Polish and French ("español", "polski", "français") are in all lowercase

### Screenshots or videos

![image](https://user-images.githubusercontent.com/41841903/201687665-57c1fd4f-15d9-4f5d-b029-2b3ac45b7088.png)

### Version

2022.1101

### Logs

[runtime.log](https://github.com/ppy/osu/files/10003960/runtime.log)
[performance.log](https://github.com/ppy/osu/files/10003961/performance.log)
[network.log](https://github.com/ppy/osu/files/10003962/network.log)
[input.log](https://github.com/ppy/osu/files/10003963/input.log)
[database.log](https://github.com/ppy/osu/files/10003964/database.log)

**Comment by Susko3** [comment]
This is intended. Language names are lowercase in those languages.
