### ISSUE TITLE
DeviceIOException: Failed to open USB device: 0xE00002C5 (Huion KAMVAS 13)

### ISSUE THREAD

**Issue by joshuah345** [ppy/osu#21237]
### Type

Other

### Bug description

Whenever my Huion KAMVAS 13 is connected to my MacBook (running macOS 12.4 Monterey) lazer displays `Encountered tablet error: "DeviceIOException: Failed to open USB device: 0xE00002C5"` as a notification.

This behavior occurs after toggling the `Tablet` option once. The message continues to appear even after disabling it (after 30 seconds or so it attempts to open the usb device again for some reason) and i have to relaunch osu! for it to end. I have no other tablet drivers running. 

Occasionally a different error appears: `Exception: "Failed retrieving USB Device"`

The latest version of OpenTabletDriver supports this tablet as well, but i've noticed that it runs into the same errors yet it does work after a few attempts at detecting while osu!'s version always seems to fail.

At the end of input.log, it's reported that the tablet was detected yet osu! doesn't display any options for configuring it.

I have opened a similar issue upstream in case it isn't specific to osu!

### Screenshots or videos

![image](https://user-images.githubusercontent.com/29195927/201744999-0519cc52-c325-49e4-9eab-c2b4c94b2be6.png)
<img width="1242" alt="Screen Shot 2022-11-14 at 2 18 10 PM" src="https://user-images.githubusercontent.com/29195927/201746664-c664f50a-b0cf-4cf8-a335-22428cc961e0.png">
(command lists running processes and returns whatever matches the pattern. nothing for huion, opentabletdriver, or wacom (other than the upgrader) is running)

### Version

2022.1101.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10006343/database.log)
[input.log](https://github.com/ppy/osu/files/10006344/input.log)
[network.log](https://github.com/ppy/osu/files/10006345/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/10006346/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10006347/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10006348/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/10006349/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10006434/runtime.log)

**Comment by bdach** [comment]
Tracked upstream as https://github.com/OpenTabletDriver/OpenTabletDriver/issues/2497. Closing as duplicate.
