### ISSUE TITLE
Release shift while dragging velocity slider change node sometimes will cause timeline move left and right by just moving mouse.

### ISSUE THREAD

**Issue by Trung0246** [ppy/osu#21260]
### Type

Game behaviour

### Bug description

Place a slider. Then try to release shift button while mouse is **moving and dragging** the slider node. This would cause timeline to move with the mouse for some reason even when the mouse did not click and grab anything and just moving.

Temporary fix is grabbing the velocity change node and drag it again.

### Screenshots or videos

https://user-images.githubusercontent.com/11626920/202318712-a56d78e3-999e-436d-a520-df89b9c824f3.mp4

### Version

2022.1101.0

### Logs

[database.log](https://github.com/ppy/osu/files/10026482/database.log)
[input.log](https://github.com/ppy/osu/files/10026483/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10026484/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10026485/network.log)
[performance.log](https://github.com/ppy/osu/files/10026486/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10026487/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10026488/updater.log)

**Comment by peppy** [comment]
I'm having trouble even finding the code which handles scrolling-near-extents, but it's probably going to be related to that specifically.

**Comment by frenzibyte** [comment]
This is the logic responsible for scrolling near timeline extents:

https://github.com/ppy/osu/blob/fcb9e2cc00894cf686a9fb73cbe27fd8af6dc766/osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineBlueprintContainer.cs#L187

That said, I'm not entirely sure what needs to be done here. In your scenario, that feature is supposed to allow you to scroll through the timeline while increasing the durartion/velocity of the slider.

**Comment by peppy** [comment]
@frenzibyte the issue is that the user is not holding the mouse down when it gets into the bad state. somehow the "drag" event is sticking.

**Comment by frenzibyte** [comment]
Right, I've just managed to reproduce this...
