### ISSUE TITLE
Deleting/updating beatmapset causes weird visual bug in the song select screen

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#21272]
### Type

Cosmetic

### Bug description

Deleted beatmapset remains in the background overlapping the other ones.

### Screenshots or videos

https://user-images.githubusercontent.com/86934170/202422540-f253a8cb-6c61-4c07-81ea-e8dfe74411f0.mp4

### Version

1117

### Logs

nothing

**Comment by Nepp0** [comment]
similar thing happens after updating a beatmap

**Comment by kajxqeirscl** [comment]
I was gonna report this too
![image](https://user-images.githubusercontent.com/75833519/202904719-c49e74b5-0be9-439c-8d5f-90ace1f71dc1.png)
