### ISSUE TITLE
Import from stable not detecting all beatmaps

### ISSUE THREAD

**Issue by vsod99** [ppy/osu#21282]
### Type

Game behaviour

### Bug description

I have >66000 beatmaps in stable. Import shows 16300 beatmaps.

### Version

2022.1117.0-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/10036716/input.log)
[performance.log](https://github.com/ppy/osu/files/10036717/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10036718/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10036719/updater.log)
[database.log](https://github.com/ppy/osu/files/10036720/database.log)

**Comment by peppy** [comment]
66,000 beatmap difficulties (what stable shows at the main menu), 16,300 beatmap sets (what import cares about).
