### ISSUE TITLE
Cursor spins when the user makes a circle with their mouse while scrolling

### ISSUE THREAD

**Issue by KreconyMakaron** [ppy/osu#21301]
### Type

Cosmetic

### Bug description

Steps to reproduce:
1. Go to any panel that can be scrolled through using your cursor (e.g. settings, profile)
2. Hold LMB and start dragging in either direction until the cursor assumes a vertical orientation
3. Make a circle around the point that flips the cursor
4. Release LMB and watch as the cursor starts erratically spinning

I'm pretty sure it makes as many spins as you have spun yourself

### Screenshots or videos

https://user-images.githubusercontent.com/55319736/202784484-c28eacf3-94cf-46cb-a259-b2a7ba8e7440.mp4

### Version

2022.1117.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/10044099/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10044100/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10044101/updater.log)
[database.log](https://github.com/ppy/osu/files/10044102/database.log)
[input.log](https://github.com/ppy/osu/files/10044104/input.log)
[network.log](https://github.com/ppy/osu/files/10044105/network.log)

**Comment by bdach** [comment]
Video doesn't work.

**Comment by KreconyMakaron** [comment]
> Video doesn't work.

Fixed it

**Comment by bdach** [comment]
I'm pretty sure this is intentional behaviour.

Related: https://github.com/ppy/osu/pull/18841

**Comment by toadsworth-jr** [comment]
You can also turn it off if you don't like it, though.
Just disable the option that says `Rotate cursor when dragging`
