### ISSUE TITLE
osu!laser does not turn on

### ISSUE THREAD

**Issue by uurcan7** [ppy/osu#21314]
### Type

Crash to desktop

### Bug description

Doesn't open, doesn't even respond. I tried to set it to windows 8 in compatibility mode, but this time it gave an error because my windows version is old.

I have the latest Windows 10 Pro version. Also, I'm not an Insider.

### Versions

2022.1117.0

### logs

[runtime.log](https://github.com/ppy/osu/files/10047197/runtime.log)
[input.log](https://github.com/ppy/osu/files/10047198/input.log)

**Comment by bdach** [comment]
Please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by uurcan7** [comment]
Günlük Adı:    Application
Kaynak:        Application Error
Tarih:         19.11.2022 18:28:44
Olay Kimliği:  1000
Görev Kategorisi:(100)
Düzey:         Hata
Anahtar sözcükler:Klasik
Kullanıcı:     Yok
Bilgisayar:    uurca
Açıklama:
Hatalı uygulama adı: osu!.exe, sürüm: 0.0.0.0, zaman damgası: 0x61e1d8d9
Hatalı modül adı: atio6axx.dll, sürüm: 31.0.12029.4013, zaman damgası: 0x63580452
Özel durum kodu: 0xc0000005
Hata uzaklığı 0x00000000003391bc
Hatalı işlem kimliği: 0x3620
Uygulama başlangıç zamanı: 0x01d8fc2b98b2cdf0
Hatalı uygulama yolu: C:\Users\uurca\AppData\Local\osulazer\app-2022.1117.0\osu!.exe
Hatalı modül yolu: C:\Windows\System32\DriverStore\FileRepository\u0384991.inf_amd64_ec94cf5fef2223e7\B384893\atio6axx.dll
Rapor kimliği: d52144f1-fdec-4857-bd4c-3bced3d9ee43
Hatalı paket tam adı: 
Hatalı paketle ilgili uygulama kimliği: 
Olay Xml'si:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-11-19T15:28:44.5442542Z" />
    <EventRecordID>7139</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>uurca</Computer>
    <Security />
  </System>
  <EventData>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>61e1d8d9</Data>
    <Data>atio6axx.dll</Data>
    <Data>31.0.12029.4013</Data>
    <Data>63580452</Data>
    <Data>c0000005</Data>
    <Data>00000000003391bc</Data>
    <Data>3620</Data>
    <Data>01d8fc2b98b2cdf0</Data>
    <Data>C:\Users\uurca\AppData\Local\osulazer\app-2022.1117.0\osu!.exe</Data>
    <Data>C:\Windows\System32\DriverStore\FileRepository\u0384991.inf_amd64_ec94cf5fef2223e7\B384893\atio6axx.dll</Data>
    <Data>d52144f1-fdec-4857-bd4c-3bced3d9ee43</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Günlük Adı:    Application
Kaynak:        .NET Runtime
Tarih:         19.11.2022 18:28:43
Olay Kimliği:  1026
Görev Kategorisi:Yok
Düzey:         Hata
Anahtar sözcükler:Klasik
Kullanıcı:     Yok
Bilgisayar:    uurca
Açıklama:
Application: osu!.exe
CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFEFBF891BC

Olay Xml'si:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-11-19T15:28:43.7851011Z" />
    <EventRecordID>7138</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>uurca</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFEFBF891BC
</Data>
  </EventData>
</Event>

**Comment by uurcan7** [comment]
First of all, I'm sorry it's Turkish. Event Viewer stops responding when I extract a file in the .eptx format you specified. For this reason, I decided to publish it as a detailed text.

**Comment by bdach** [comment]
This is an unspecified "access violation" driver error that we cannot easily assist with. Please try updating your GPU drivers to a newer version.

Failing that, it may be that we cannot support your device for now until the equivalent of "compatibility mode" (i.e. a directx or vulkan renderer) is added to lazer - this is planned work which is already in progress.

**Comment by uurcan7** [comment]
I updated my video card driver but..

Günlük Adı:    Application
Kaynak:        Application Error
Tarih:         19.11.2022 23:10:45
Olay Kimliği:  1000
Görev Kategorisi:(100)
Düzey:         Hata
Anahtar sözcükler:Klasik
Kullanıcı:     Yok
Bilgisayar:    uurca
Açıklama:
Hatalı uygulama adı: osu!.exe, sürüm: 0.0.0.0, zaman damgası: 0x61e1d8d9
Hatalı modül adı: atio6axx.dll, sürüm: 31.0.12029.7019, zaman damgası: 0x636c8e7a
Özel durum kodu: 0xc0000005
Hata uzaklığı 0x000000000034ba7c
Hatalı işlem kimliği: 0x1fa0
Uygulama başlangıç zamanı: 0x01d8fc52fe57dd76
Hatalı uygulama yolu: C:\Users\uurca\AppData\Local\osulazer\app-2022.1117.0\osu!.exe
Hatalı modül yolu: C:\Windows\System32\DriverStore\FileRepository\u0385557.inf_amd64_ec9d8bb56fc39c0b\B385520\atio6axx.dll
Rapor kimliği: 5a831765-aed7-49ec-9ed6-d13de55826a8
Hatalı paket tam adı: 
Hatalı paketle ilgili uygulama kimliği: 
Olay Xml'si:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-11-19T20:10:45.8714784Z" />
    <EventRecordID>7379</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>uurca</Computer>
    <Security />
  </System>
  <EventData>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>61e1d8d9</Data>
    <Data>atio6axx.dll</Data>
    <Data>31.0.12029.7019</Data>
    <Data>636c8e7a</Data>
    <Data>c0000005</Data>
    <Data>000000000034ba7c</Data>
    <Data>1fa0</Data>
    <Data>01d8fc52fe57dd76</Data>
    <Data>C:\Users\uurca\AppData\Local\osulazer\app-2022.1117.0\osu!.exe</Data>
    <Data>C:\Windows\System32\DriverStore\FileRepository\u0385557.inf_amd64_ec9d8bb56fc39c0b\B385520\atio6axx.dll</Data>
    <Data>5a831765-aed7-49ec-9ed6-d13de55826a8</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Günlük Adı:    Application
Kaynak:        .NET Runtime
Tarih:         19.11.2022 23:10:45
Olay Kimliği:  1026
Görev Kategorisi:Yok
Düzey:         Hata
Anahtar sözcükler:Klasik
Kullanıcı:     Yok
Bilgisayar:    uurca
Açıklama:
Application: osu!.exe
CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFF9C25BA7C

Olay Xml'si:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-11-19T20:10:45.0169022Z" />
    <EventRecordID>7378</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>uurca</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFF9C25BA7C
</Data>
  </EventData>
</Event>

**Comment by uurcan7** [comment]
I sent them a report, I hope they will take care of it.
![2022-11-19](https://user-images.githubusercontent.com/79050542/202869981-603cec72-cfdf-4efd-aad0-4cffd3ce22d4.png)

**Comment by uurcan7** [comment]
There is a bug in the current version. When I reverted to the WHQL Verified recommended driver, the problem was resolved
