### ISSUE TITLE
Day separator not added correctly when message is sent to user during channel load

### ISSUE THREAD

**Issue by Terochi** [ppy/osu#21316]
### Type

Cosmetic

### Bug description

When sending a message to a chat room, which is in a loading state, will not update the "message sent date" after loading and sending said message. This is (of course) only client sided, as the room is shown correctly after closing.

### Version

2022.1117.0

### Logs

[updater.log](https://github.com/ppy/osu/files/10047294/updater.log)
[database.log](https://github.com/ppy/osu/files/10047295/database.log)
[network.log](https://github.com/ppy/osu/files/10047296/network.log)
[performance.log](https://github.com/ppy/osu/files/10047297/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10047298/runtime.log)

**Comment by bdach** [comment]
I don't understand what is being claimed here. Can you explain better? A screenshot or video would help.

**Comment by Terochi** [comment]
https://user-images.githubusercontent.com/100224757/202858502-5afd5cff-2a17-4752-98de-66ec710b44da.mp4
