### ISSUE TITLE
sometimes particles from a hold note do not go away after release/end of hold

### ISSUE THREAD

**Issue by Doksha** [ppy/osu#21311]
### Type

Cosmetic

### Bug description

when playing mania often times the effect for the hold note will be activated, then not deactivated until much later. I do not know what causes it to happen, nor what causes it to end, they both seem somewhat random.
This happens pretty often, although it seems to be more consistent if you play the same section of a beatmap

I've tried searching for this issue but cannot find a pre-existing one, although I am tired as shit so I may have skimmed over it.

### Screenshots or videos

https://user-images.githubusercontent.com/72625258/202837663-0c0b3182-af0a-4c0d-9c3e-4ac1da8871da.mp4

(ignore my garbage gameplay, i am playing one handed with reverse controls)
note the left lane turns on, stays on for a bit, then turns off

the beatmap played: https://osu.ppy.sh/beatmapsets/1255057#mania/2693916
around 2:37 in

### Version

2022.1117.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/10046233/performance.log)
[input.log](https://github.com/ppy/osu/files/10046234/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10046235/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10046236/network.log)
[runtime.log](https://github.com/ppy/osu/files/10046237/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10046238/updater.log)
[database.log](https://github.com/ppy/osu/files/10046239/database.log)

**Comment by frenzibyte** [comment]
Please attach the skin.

**Comment by Doksha** [comment]
[R Skin v3.0 (Bars) [R Skin v3.0 (Jakads Edit)] (Retsukiya).zip](https://github.com/ppy/osu/files/10047466/R.Skin.v3.0.Bars.R.Skin.v3.0.Jakads.Edit.Retsukiya.zip)
(rename to .osk)

**Comment by peppy** [comment]
@Doksha are you able to reproduce this during autoplay, or only with manual inputs? If the latter, could you please attach a replay from that gameplay above?

**Comment by Doksha** [comment]
> are you able to reproduce this during autoplay, or only with manual inputs? If the latter, could you please attach a replay from that gameplay above?

I have not noticed this in autoplay (although I basically never use it) here is a replay where it happens (about midway through the map; right before I fail) 
[NoHaxNoSkill playing KOTOKO - Sociometry (TV Size) (Pengdoll) [Hard].zip](https://github.com/ppy/osu/files/10062555/NoHaxNoSkill.playing.KOTOKO.-.Sociometry.TV.Size.Pengdoll.Hard.zip)
