### ISSUE TITLE
Cursor smoke isn't rectangular or scalable compared to stable

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [ppy/osu#21331]
### Type

Cosmetic

### Bug description

in lazer, Cursor smoke isn't rectangular or scalable, when applied to custom skins that override cursor-smoke.
in stable, Cursor smoke is rectangular and scalable, when applied to custom skins that override cursor-smoke.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/40109698/202902874-32fdf4e0-3af2-4746-a70f-ebe1ff5b0c54.png)
![image](https://user-images.githubusercontent.com/40109698/202903039-c42c7d56-dfc3-4477-9fac-a334903244a5.png)

### Version

2022.1117.0-lazer

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/10049716/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10049717/network.log)
[performance.log](https://github.com/ppy/osu/files/10049718/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10049719/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10049720/updater.log)
[database.log](https://github.com/ppy/osu/files/10049721/database.log)

**Comment by bdach** [comment]
I'm not sure whether this should be supported given it's a pretty... unorthodox use of smoke. But please attach the skin at the least.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
at least... the skin is at github so there you have it! TRRESTGHGYTCFTGBCXSZD/osuloop2
