### ISSUE TITLE
Add length limit to chat text box

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#21330]
Currently there is no length limit applied client-side, and any message that exceed the server-side limit will get thrown away. Ideally such errors would be elegantly handled and the message would be returned back to the user, but I've attempted at least adding a client-side length limit of 100 characters (which is the default value from web source), and I wasn't if that's what the web currently has (it's envvar-based, and it seems to exceed 100 characters).

### Discussed in https://github.com/ppy/osu/discussions/21245

<div type='discussions-op-text'>

<sup>Originally posted by **developomp** November 15, 2022</sup>
When I try to send a lengthy message in the osu!lazer client, it clears the text input regardless of whether the message was successfully delivered or not, forcing me to retype the whole thing. Adding a character length limit feature and doing the following for message input area would feel like a much better user experience in my opinion:

1. When a user sends a message, lock the text input.
2. If the message is successfully delivered, clear the text input. Notify user otherwise (give the text input a little shake maybe).</div>

**Comment by novialriptide** [comment]
Hi, I've made some progress on this issue. I'll be making a pull request in a couple of hours.
