### ISSUE TITLE
Game crashes while running an overkill map

### ISSUE THREAD

**Issue by l4rryc0n5014** [ppy/osu#2133]
I'd like to elaborate more. The map I played is [198002] Knife Party - Centipede (THE Centipede map, 46-ish star difficulty) on Autoplay mod in osu!standard. I was actually planning to test the map on lazer in mania mode to see whether osu!lazer's mania Autoplay has any improvement comparing to osu-stable's, but that's not the point.

The map started out normally, no hiccups with a big long spinner. Then comes the main fun of the map. At this point, FPS dropped to 0 and the game only updates the field every few seconds. After the "mayhem" starts for about 10-15secs, the game freezes and crashes, "osu!lazer has stopped working". The weird part is the music behind keeps playing normally before the crash. I thought it was due to lack of memory so I killed Firefox and everything else at that point, returning me to 1.6/3.9GB, and re-ran the steps for the 4th time. Despite that, the game still crashed, and I noticed the game was using roughly 500-600MB of memory when viewed in Task Manage's Performance tab, and 1,107,000 K under the Details tab.

The build from which I get the bug is 2018.224.0 Dev Build. System is Dell Inspiron 13 3443 with Intel Core i5 5200U at 2.49GHz at time of crash, running Windows 10 Enterprise 64-bit under DX9 and DX11 in parallel, with 4GB of RAM and a lot of C++ redist. Graphics is Intel HD Graphic 5000. The game was at resolution 1366x768. I shouldn't be sending this per Peppy's order (I don't know how to fix it) but I think I should send this for the development of the game. Thank you, and end of issue report.

**Comment by peppy** [comment]
Please provide crash logs.

**Comment by l4rryc0n5014** [comment]
I'm at school right now so I can't upload the crash report. I'll upload it ASAP, the earliest I can do is in 6 hours 30 minutes to 7 hours.

**Comment by l4rryc0n5014** [comment]
Crash logs are here. Thank you Aergwyn on #1405 for the location of the logs (Sorry, I'm new here)
Crash logs on 27 Feb 2018 are 04 files below
[performance-audio.log](https://github.com/ppy/osu/files/1767435/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/1767436/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/1767437/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/1767438/performance-update.
Crash logs on 28 Feb 2018 re-running the steps of the issue are 06 files below:
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/1767446/performance-gamethread.draw.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/1767447/performance-gamethread.update.log)
[performance.log](https://github.com/ppy/osu/files/1767448/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/1767449/performance-gamethread.audio.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/1767450/performance-gamethread.input.log)
[runtime.log](https://github.com/ppy/osu/files/1767451/runtime.log)

**Comment by Frontear** [comment]
Ran the beatmap centipede, at around 0:25 Exception is thrown in Scheduler: https://hastebin.com/ogukuxobab.tex

This exception is consistently thrown, sometimes in Drawable, and sometimes in Schedular. The point is that the beatmap will *always* crash the game at around 0:25.

**Comment by peppy** [comment]
I have since reproduced this.
