### ISSUE TITLE
Aspect ratio is limited to 2.32 after the update

### ISSUE THREAD

**Issue by Cailus** [ppy/osu#21342]
### Type

Game behaviour

### Bug description

I have an ultrawide monitor. On stable I used to play with 1:2.39, when I migrated to lzer, because of the lack of decimal points, I used to play with ~1:2.4 (100x42mm). After the update my area reseted to 1:1, and I literally cannot rever to 100x42, it doesn't allow me even if I unlock aspect ratio.

### Screenshots or videos

https://user-images.githubusercontent.com/63445917/202937263-3bc4b735-6942-4163-a50a-ed2ed94d8923.mov

### OS
MacOS Ventura m1 pro

### Version

latest (lazer)

### Logs

...

**Comment by Cailus** [comment]
@Samaoo your change did that.

**Comment by peppy** [comment]
We have always limited the maximum aspect ratio to 2.33 (based on 21:9 numbers, which is supposed to be ultrawide). Can you give specs or a model for your monitor so we can consider increasing this as a result?

Of note, until now this was probably not being enforced correctly which is why you were managing to get higher aspect ratios. I made a recent fix to this.

**Comment by Cailus** [comment]
I was able to choose 100x42 In the previous lazer version. I'll post a video as proof.

https://user-images.githubusercontent.com/63445917/202960330-4ad3be87-b33e-4138-8b45-8ccd36ae925f.mov

my monitor: LG 34WP65C-B 34-Inch 21:9 Curved UltraWide QHD (3440x1440)

"Of note, until now this was probably not being enforced correctly which is why you were managing to get higher aspect ratios. I made a recent fix to this."

I play with 1:2.389. that is ~2.5% more than 2.33, might not look like much difference, but it is a big difference in this game. I appreciate if you increase the limit to accomodate my needs, especially if you add more decimal points to width and height.

Best Regards.

**Comment by peppy** [comment]
Just to confirm, you are wanting to intentionally making it so your horizontal positioning is different to your vertical? 2.38 on a 2.33 screen means that horizontal movements on the tablet will move further on screen than vertical.

**Comment by Cailus** [comment]
> Just to confirm, you are wanting to intentionally making it so your horizontal positioning is different to your vertical? 2.38 on a 2.33 screen means that horizontal movements on the tablet will move further on screen than vertical.

short answer:
yes.

Long answer:
1. if you watch the first video you will notice that the aspect doesn't even go to 2.33 anymore, it goes up to 2.32
2. there are ultrawide monitors that go beyond 21:9.
3. it's better to let the user decide to avoid these kinds of issues

**Comment by peppy** [comment]
> 1. if you watch the first video you will notice that the aspect doesn't even go to 2.33 anymore, it goes up to 2.32

That's just a precision / rounding issue. Not relevant here.

> 3. it's better to let the user decide to avoid these kinds of issues

We believe in sane limits for these values. Having a user choose with no limits is bad UX in my opinion. But thanks for your advice.

I've increase the maximum to 23:9 for now, see #21346.

**Comment by Cailus** [comment]
Thank you.
