### ISSUE TITLE
Song is placed in the wrong spot in the menu

### ISSUE THREAD

**Issue by thiccyoshi4568** [ppy/osu#21370]
### Type

Game behaviour

### Bug description

Not sure of any details that'll help but I was just browsing the menu after being AFK and found this weird visual glitch. I can't seem to click on the song.

### Screenshots or videos

![Screenshot (15)](https://user-images.githubusercontent.com/94721605/203248949-36a974e8-518b-4127-900f-ea492bef8eef.png)

### Version

2022.1117.0-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/10064810/input.log)
[network.log](https://github.com/ppy/osu/files/10064811/network.log)
[performance.log](https://github.com/ppy/osu/files/10064812/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10064813/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10064814/updater.log)
[database.log](https://github.com/ppy/osu/files/10064815/database.log)

**Comment by smoogipoo** [comment]
I've seen this reported on Twitter I think, but I can't remember the specifics. I believe it has to do with hiding beatmaps, if I remember correctly.

Does that sound about right for what you were doing at the time?

**Comment by smoogipoo** [comment]
Oh, it looks like this is fixed by https://github.com/ppy/osu/pull/21326
