### ISSUE TITLE
[Bug] Texts and mouse cursor missing after computer suspend (sleep)

### ISSUE THREAD

**Issue by UlyssesZh** [ppy/osu#21398]
### Type

Game behaviour

### Bug description

How I find the bug (I don't know whether all steps are required):
1. Use windowed mode.
2. Suspend the computer.
3. Wake up the computer.
4. Texts and mouse cursor are missing.

Linux, Ubuntu 20.04.5 LTS. osu!lazer AppImage version 2022.1117.0.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/26196187/203621060-bf1bbe7b-6612-4188-ac74-fa94be8c4186.png)
![image](https://user-images.githubusercontent.com/26196187/203621150-cc6cd12d-c9e4-4825-8885-0995ed6f5041.png)

### Version

2022.1117.0

### Logs

[database.log](https://github.com/ppy/osu/files/10078216/database.log)
[input.log](https://github.com/ppy/osu/files/10078217/input.log)
[network.log](https://github.com/ppy/osu/files/10078218/network.log)
[performance.log](https://github.com/ppy/osu/files/10078219/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/10078220/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10078221/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10078222/runtime.log)

**Comment by peppy** [comment]
This is going to be a driver level issue.
