### ISSUE TITLE
Updated map displaying over other maps

### ISSUE THREAD

**Issue by Gamereily** [ppy/osu#21392]
### Type

Game behaviour

### Bug description

After updating to the most recent version I played a random map for not even 5 seconds, then proceeded to see that the map "Be your light" needed an update. I updated it and then clicked on "Beastmode" and then it was visually covered (overlapping) by "Be your light". I could still interact with "Beastmode" as normal but "Be your light" remained, even after continuing to play a beatmap. It also persists if I change the song selected. I planned to take screenshots of this but went back to the main menu first to get the version and when I returned the bug was gone... Sorry for how unhelpful that is! I couldn't find any mention of this in any other issues by searching keywords. If there's any clarification needed just ask!

Beatmaps Mentioned:
Beastmode: https://osu.ppy.sh/beatmapsets/494225#osu/1052353
Be your Light: https://osu.ppy.sh/beatmapsets/590152#osu/1253222

### Version

2022.1117.0-lazer

### Logs

[performance-draw.log](https://github.com/ppy/osu/files/10074098/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10074100/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10074101/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10074102/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10074105/updater.log)
[database.log](https://github.com/ppy/osu/files/10074106/database.log)
[network.log](https://github.com/ppy/osu/files/10074107/network.log)
[performance.log](https://github.com/ppy/osu/files/10074108/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/10074109/performance-audio.log)

**Comment by peppy** [comment]
This will be fixed in the next release.
