### ISSUE TITLE
Deleted song stays until leaving song select

### ISSUE THREAD

**Issue by lemocha7** [ppy/osu#21391]
### Type

Cosmetic

### Bug description

When I delete any song in the song select, it stays on screen, completely unselectable, not even going away when switching game modes. Clears when going in and then out of song select.

### Screenshots or videos

https://drive.google.com/file/d/1t2PPJAg7Il7DvTj-56h3BvqPJ-wl_0WX/view

### Version

2022.1117.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10074023/database.log)
[input.log](https://github.com/ppy/osu/files/10074024/input.log)
[network.log](https://github.com/ppy/osu/files/10074026/network.log)
[performance.log](https://github.com/ppy/osu/files/10074027/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10074028/runtime.log)

**Comment by peppy** [comment]
Already fixed in the next release.
