### ISSUE TITLE
Editing "nothing" will cause error on song select screen.

### ISSUE THREAD

**Issue by Trung0246** [ppy/osu#21402]
### Type

Game behaviour

### Bug description

1) Type random thing into search bar for showing nothing
2) Attempt to "edit" nothing
3) Quit the edit screen
4) Error occured

Optional steps:
5) Attempt to edit again will cause the game to stuck in a weird state until pressing close button while in windowed mode will fix it I guess.

### Screenshots or videos

https://user-images.githubusercontent.com/11626920/203734717-1fa13f7f-7b8d-4158-adfb-da760e124dfd.mp4

### Version

2022.1123.0

### Logs

[database.log](https://github.com/ppy/osu/files/10082240/database.log)
[input.log](https://github.com/ppy/osu/files/10082241/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10082242/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10082243/network.log)
[performance.log](https://github.com/ppy/osu/files/10082245/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10082246/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10082247/updater.log)

**Comment by nanashi-1** [comment]
#21244

**Comment by Trung0246** [comment]
Oh looks like dupe then. I was remembering I saw this somewhere but cannot find it.
