### ISSUE TITLE
Ruleset should not automatically switch when jumping to an osu! ruleset beatmap

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#21415]
Going to preemptively assume this is pretty annoying for players of alternate rulesets, and mark as relatively high priority.

As mentioned in the discussion, having this depend on the state of the "Show converted" checkbox sounds like a solid idea.

### Discussed in https://github.com/ppy/osu/discussions/21404

<div type='discussions-op-text'>

<sup>Originally posted by **smileyhead** November 24, 2022</sup>
When playing in an alternate game mode, it can be pretty jarring if the game switches back to standard, even though the beatmap is playable in the current game mode. I would suggest setting an exception to auto-switching in this case.

https://user-images.githubusercontent.com/15932372/203771961-254f3a26-cc0f-4100-9372-672a96fa2a98.mp4</div>

**Comment by LittleEndu** [comment]
Does lazer have a function that determines whether beatmap from one ruleset can be converted to another or should this just apply to osu! ruleset for now?
