### ISSUE TITLE
Universal offset Osu! Lazer

### ISSUE THREAD

**Issue by Megumiiiiii** [ppy/osu#21411]
### Type

Game behaviour

### Bug description

I set the offset in default to +25 and while ingame it always returns to 0 from having to set again right before starting

### Screenshots or videos

![329_1](https://user-images.githubusercontent.com/98658943/203878776-26a44910-49ee-4698-8f8e-a746537b54f3.png)
![offset](https://user-images.githubusercontent.com/98658943/203878790-44716b65-1da3-43d5-b007-354f3b17252b.png)

### Version

2022.1101.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10087816/database.log)
[input.log](https://github.com/ppy/osu/files/10087817/input.log)
[network.log](https://github.com/ppy/osu/files/10087818/network.log)
[performance.log](https://github.com/ppy/osu/files/10087819/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10087820/runtime.log)

**Comment by Megumiiiiii** [comment]
Also please add this score metter to Osu!Lazer
![scoremetter](https://user-images.githubusercontent.com/98658943/203879441-db112811-3c88-496e-a8a2-7c011d00ffff.png)

**Comment by peppy** [comment]
Universal offset and beatmap offset are separate controls. Beatmap offset (the first screenshot) only applies to the current beatmap.

The score meter you're looking for is already added to the game, please use the skin layout editor to customise your HUD (ctrl+shift+s).

**Comment by Megumiiiiii** [comment]
There is no option to change score metter

**Comment by peppy** [comment]
You will need to add a new one from the list on the left (you want a "Colour" version).
