### ISSUE TITLE
icon error when windowed

### ISSUE THREAD

**Issue by EatKFCinMc** [ppy/osu#21436]
### Type

Performance

### Bug description

After osu is windowing and narrowed down, random song's icon will be painted strangely, and no notes will appear after entering the pavement, but the normal decision is made. I thought it would always be there but it was restored after an unintentional random song, but there were no notes on the pavement(sorry I didn't record this part).
And sorry I open the game again and play once when the bug occured before.

### Screenshots or videos

https://user-images.githubusercontent.com/69470365/204138624-4c6e99e4-3ab8-41b7-a4c2-38f31b86c6b5.mp4

### Version

2022.1123.0

### Logs

[performance-update.log](https://github.com/ppy/osu/files/10098442/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10098443/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10098444/updater.log)
[database.log](https://github.com/ppy/osu/files/10098445/database.log)
[input.log](https://github.com/ppy/osu/files/10098446/input.log)
[network.log](https://github.com/ppy/osu/files/10098447/network.log)
[performance.log](https://github.com/ppy/osu/files/10098448/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/10098449/performance-draw.log)

**Comment by smoogipoo** [comment]
This is going to be a GPU issue, and should be resolved after the move to DirectX for your platform.
