### ISSUE TITLE
osu!lazer will play all sound at once (randomly) if you lag in edit mode

### ISSUE THREAD

**Issue by timelessnesses** [ppy/osu#21431]
### Type

Game behaviour

### Bug description

if you have very bad (like seriously bad) you might lag in beatmap editor and when it lags it is going to stack sound up and when its back to normal it just throw those sound at your ear

### Screenshots or videos

https://user-images.githubusercontent.com/59832159/204096975-67766d72-ce65-4071-a401-8741a097ecdb.mp4  

(audio warning and yes my laptop is very bad also blame obs for barely captured any frames)

### Version

2022.1123.0-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/10096548/updater.log)
[database.log](https://github.com/ppy/osu/files/10096549/database.log)
[network.log](https://github.com/ppy/osu/files/10096550/network.log)
[performance.log](https://github.com/ppy/osu/files/10096551/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10096552/runtime.log)

**Comment by bdach** [comment]
Performance is a constant work-in-progress, and the beatmap being edited on this video (https://osu.ppy.sh/beatmapsets/1360713#mania/2815667) is a "meme" map that is doing note spam to the point of triggering this assertion in debug builds:

https://github.com/ppy/osu/blob/a841d35ebd4ecab69ef268273038c04c0432b895/osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineTickDisplay.cs#L152-L164

I think that this is an outlier case that does not warrant further action at this time.
