### ISSUE TITLE
Special Sliders using a lot of anchors lagging when selected

### ISSUE THREAD

**Issue by TimperNL** [ppy/osu#21452]
### Type

Performance

### Bug description

When in the editor, if you select a slider that has a lot of set anchors, it causes the game to lag a lot.
When standing still with the cursor after selecting the slider, it puts me at around 30 fps (as seen in the video attached below), but when I start moving my cursor, the game starts to stutter a ton. The fps drops and the latency spikes to insane levels.
When you deselect the slider, the game takes a second before it's fine again. So it only lags that much when I have the slider selected.

I couldn't find any other report with this problem, so I don't know if it was an already known bug.

### Screenshots or videos

https://user-images.githubusercontent.com/100241406/204516642-84cb2b13-d1d3-4b7f-ac4c-5e1d6f2b8220.mp4

This is the map that the bug is appearing in, but I do think it will be the same for other maps with the same slider tech.
https://osu.ppy.sh/beatmapsets/1746664#osu/3640375
Kotoha - God-ish [lean's Extra]

### Version

2022.1123.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/10112535/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10112536/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10112537/updater.log)
[database.log](https://github.com/ppy/osu/files/10112538/database.log)
[input.log](https://github.com/ppy/osu/files/10112539/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10112540/legacy-ipc.log)
network.log is not working and GitHub can't process the file.

**Comment by smoogipoo** [comment]
Performance and optimisation considerations are an ongoing effort. Please be patient and wait for future optimisations.
