### ISSUE TITLE
Default skin reverse arrows need a design making them more visible

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2147]
This is how it looks on stable:
![Stable](https://i.imgur.com/nN8hzA0.png)

This is how it looks on lazer:
![Lazer](https://i.imgur.com/4hCai1A.png)

Lazer renders the reverse arrow behind the entire hitcircle while on stable it's rendered only behind the hitcircleoverlay. Also lazer's reverse arrows are way smaller.

**Comment by AntonPetrochenko** [comment]
Still an issue 2 years later

**Comment by bdach** [comment]
Yes, it's still open for a reason. Such comments are not helpful or needed.

**Comment by peppy** [comment]
@arflyte i think we already discussed this and it's included in the latest default skin design logic, can you confirm that?

**Comment by arflyte** [comment]
Yeah, it's in the latest design.

**Comment by LittleEndu** [comment]
Was going to open its own issue for the legacy portion of this, but I don't think anyone has actually complained about legacy reverse arrows being hard to see. Opened a discussion (#14594) instead.

**Comment by LittleEndu** [comment]
Can this be considered addressed by https://github.com/ppy/osu/pull/24990 or does the triangles skin also need to be changed?

**Comment by peppy** [comment]
Should be good.
