### ISSUE TITLE
Game keeps throwing errors everytime the beatmaps are refreshed.

### ISSUE THREAD

**Issue by kajxqeirscl** [ppy/osu#21472]
### Type

Other

### Bug description

Almost everytime I restart a map or refresh beatmaps in some way the game throws these errors. It's probably cause by some beatmap but I can't find which one (I don't understand the logs)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/75833519/204872180-60c6caef-7244-4551-bec2-002ee275ab13.png)

### Version

2022.1123.0

### Logs

[database.log](https://github.com/ppy/osu/files/10125928/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10125929/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10125930/network.log)
[performance.log](https://github.com/ppy/osu/files/10125931/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10125932/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10125933/updater.log)

**Comment by kajxqeirscl** [comment]
This didn't happen before I imported a lot of beatmaps from stable.

**Comment by kajxqeirscl** [comment]
> I have no idea how this is possible. It can't really have anything to do with imports from stable, that's for sure.
> 
> ```
> 2022-11-30 17:27:07 [error]: An unobserved error has occurred.
> 2022-11-30 17:27:07 [error]: MessagePack.MessagePackSerializationException: Failed to serialize osu.Game.Online.Spectator.SpectatorState value.
> 2022-11-30 17:27:07 [error]: ---> System.MissingMethodException: Method not found: 'System.get_Mods.IEnumerable`1<osu.Game.Online.API.APIMod> osu.Game.Online.Spectator.SpectatorState.get_Mods()'.
> 2022-11-30 17:27:07 [error]: at MessagePack.Formatters.osu_Game_Online_Spectator_SpectatorStateFormatter1.Serialize(MessagePackWriter& writer, SpectatorState value, MessagePackSerializerOptions options)
> 2022-11-30 17:27:07 [error]: at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
> 2022-11-30 17:27:07 [error]: --- End of inner exception stack trace ---
> 2022-11-30 17:27:07 [error]: at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
> 2022-11-30 17:27:07 [error]: at Microsoft.AspNetCore.SignalR.Protocol.DefaultMessagePackHubProtocolWorker.Serialize(MessagePackWriter& writer, Type type, Object value)
> 2022-11-30 17:27:07 [error]: at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.WriteInvocationMessage(InvocationMessage message, MessagePackWriter& writer)
> 2022-11-30 17:27:07 [error]: at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.WriteMessageCore(HubMessage message, MessagePackWriter& writer)
> 2022-11-30 17:27:07 [error]: at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.WriteMessage(HubMessage message, IBufferWriter`1 output)
> 2022-11-30 17:27:07 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.SendHubMessage(ConnectionState connectionState, HubMessage hubMessage, CancellationToken cancellationToken)
> 2022-11-30 17:27:07 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCore(ConnectionState connectionState, String methodName, InvocationRequest irq, Object[] args, String[] streams, CancellationToken cancellationToken)
> 2022-11-30 17:27:07 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
> 2022-11-30 17:27:07 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
> 2022-11-30 17:27:07 [error]: An unobserved error has occurred. (inner)
> 2022-11-30 17:27:07 [error]: System.MissingMethodException: Method not found: 'System.get_Mods.IEnumerable`1<osu.Game.Online.API.APIMod> osu.Game.Online.Spectator.SpectatorState.get_Mods()'.
> 2022-11-30 17:27:07 [error]: at MessagePack.Formatters.osu_Game_Online_Spectator_SpectatorStateFormatter1.Serialize(MessagePackWriter& writer, SpectatorState value, MessagePackSerializerOptions options)
> 2022-11-30 17:27:07 [error]: at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
> ```
> 
> This looks more like a terminally corrupted install somehow. @kajxqeirscl can you explain how you installed the game? you're not running a dev build or something, right? is it possible that something corrupted during a game update or something?

No, completely normal game install and updates.

**Comment by kajxqeirscl** [comment]
> Any custom rulesets installed or something?

Nope. None.

**Comment by peppy** [comment]
@kajxqeirscl Are you able to zip and send your full osu installation directory? ie. everything at `%localappdata\osulazer` (you can paste this location into the `Run...` dialog on windows.

It might be a bit big so you are welcome to use an external file sharing service and/or email to me (pe@ppy.sh).

**Comment by kajxqeirscl** [comment]
here it is https://drive.google.com/file/d/1Fyq_yBEFFJcji0LEGg8l2jBGVdxPL6dh/view?usp=sharing

**Comment by peppy** [comment]
@kajxqeirscl I'm finally getting around to investigating this. Have you updated your install since this occurred? If so, has the situation improved at all?

**Comment by kajxqeirscl** [comment]
> @kajxqeirscl I'm finally getting around to investigating this. Have you updated your install since this occurred? If so, has the situation improved at all?
The issue never happened again literally the next day iirc. I can no longer replicate it. iirc the game wasn't updated the issue just somehow disappeared and fixed itself...

**Comment by peppy** [comment]
Great to hear. Let's close for now 😅 .
