### ISSUE TITLE
Statistics of a score changing after watching the replay

### ISSUE THREAD

**Issue by kajxqeirscl** [ppy/osu#21485]
### Type

Cosmetic

### Bug description

[This score](https://osu.ppy.sh/scores/osu/4264818247)'s statistics are displayed incorrectly after watching the replay of it (I imported the replay using "import files" in settings after downloading it from the website).
The replay itself plays exactly how it is supposed to be. 

### Screenshots or videos

before watching the replay (stats are correct):
![Screenshot 2022-12-01 194432](https://user-images.githubusercontent.com/75833519/205111232-f1915b87-3dfd-453c-b963-388635f8feb4.png)
after watching the replay (stats are incorrect):
![Screenshot 2022-12-01 194758](https://user-images.githubusercontent.com/75833519/205111238-b9c4c895-66ad-4322-b7bc-8f9294b10102.png)

### Version

2022.1123.0

### Logs

[database.log](https://github.com/ppy/osu/files/10134385/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10134386/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10134387/network.log)
[performance.log](https://github.com/ppy/osu/files/10134388/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10134389/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10134390/updater.log)

**Comment by bdach** [comment]
#19766

**Comment by kajxqeirscl** [comment]
I think the issues are not the same. in this case the replay plays correctly...

**Comment by bdach** [comment]
Original post of linked issue mentions judgement counts changing along with accuracy. Which is the same as this report.

There is no reason to have 30 different issues pointing out different playback inaccuracies.
