### ISSUE TITLE
osu!lazer login

### ISSUE THREAD

**Issue by GiereczeqYTT** [ppy/osu#2148]
Hello i typed wrong password i cant change it because i have everytime Connecting. and it never wanna connect

**Comment by peppy** [comment]
May be a regression, but also seems like it could be a network issue at your end.

Could you please include your `network.log` contents?

**Comment by WolfgangAxel** [comment]
I'm experiencing the same issue- a successful login will cause the game to just say `Connecting...` forever. If the "Remember username/password" options are checked, then the sign in gets locked up on game startup. Interestingly enough, this only happens when the login is successful; putting in random credentials will return a failure and re-display the login box. `network.log` is not terribly helpful, but here's mine anyway, with commentary:

    3/10/2018 4:52:46 AM: ----------------------------------------------------------
    3/10/2018 4:52:46 AM: Network Log for WolfgangAxel
    3/10/2018 4:52:46 AM: osu version unknown (Built direct from GitHub ~5 hours before this comment)
    3/10/2018 4:52:46 AM: Running on Unix 4.14.0.3, 8 cores (Debian Testing, Mono 5.10.0.160)
    3/10/2018 4:52:46 AM: ----------------------------------------------------------
        (Tried connecting using random keypresses as username/password)
    3/10/2018 4:52:46 AM: We just went Connecting!
    3/10/2018 4:52:46 AM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Unauthorized (FAILED).
    3/10/2018 4:52:46 AM: Login failed!
    3/10/2018 4:52:46 AM: We just went Offline!
        (Tried connecting using proper email/password credentials)
    3/10/2018 4:53:08 AM: We just went Connecting!
    3/10/2018 4:53:09 AM: Request to https://osu.ppy.sh/oauth/token successfully completed!
    3/10/2018 4:53:09 AM: Performing request osu.Game.Online.API.Requests.GetUserRequest
    3/10/2018 4:53:10 AM: Request to https://osu.ppy.sh/api/v2/me successfully completed!

That's all the further it gets. I've let it try to sign in while playing for over 1 hour and it still never connected nor gave me the ability to try signing in again. My internet connection did work during that timespan. If there's any further information I can give, please let me know.

**Comment by VPeruS** [comment]
What is your rank in osu on this profile and how long profile exists?

**Comment by peppy** [comment]
At this point, we're going to need further debug information by actually debugging the application during login. Logs are not showing the issue.

**Comment by WolfgangAxel** [comment]
@VPeruS I've been holding off playing osu until I got it running on Linux natively (thank you all **so** much for that, BTW). I had to run it through WINE to get my account created, but past that I haven't been able to get a rank since I can't log in. FWIW [here's](https://osu.ppy.sh/u/11854087) my profile.

@peppy I'm willing to help out any way I can. What should I do to get more debug information?

**Comment by WolfgangAxel** [comment]
I've built the most recent commit (3e313a1), and this behavior is still present. As before, login failures return immediately, but after a successful request to `https://osu.ppy.sh/api/v2/me`, the login gets stuck. There is no new information in my `network.log`.

I don't have any experience with C#, but I was able to add a few extra log entries to see where things are going awry. It seems like my login is getting stuck in the loop [starting here](https://github.com/peppy/osu/blob/1ecd0513831c98e3c3b97197cd53033283312070/osu.Game/Online/API/APIAccess.cs#L144). My `GetUserRequest` is completing, however [this line](https://github.com/peppy/osu/blob/1ecd0513831c98e3c3b97197cd53033283312070/osu.Game/Online/API/APIAccess.cs#L125) is not successfully doing anything.

I apologize for my inexperience with C# and for not being able to provide a pull request. I hope this is somewhat helpful and not annoying or useless information. Again, if there's anything else you'd like me to try, if it's within my abilities I will.

**Comment by peppy** [comment]
There's a web-side fix that isn't pushed out yet which may still solve this for you. What's your osu! username?

**Comment by WolfgangAxel** [comment]
My username is [kuroneko-love](https://osu.ppy.sh/u/11854087). Sorry, I guess I didn't consider this might be a server-side issue.

**Comment by peppy** [comment]
Yeah, this is a server-side issue which should be resolved soon.

**Comment by peppy** [comment]
Please try again now, it should theoretically be fixed.

**Comment by WolfgangAxel** [comment]
Sorry for the delay, I was at work. 

I recompiled from your latest commit and tried logging in, with no luck. The behavior is the same as before on this end.

**Comment by peppy** [comment]
Anything in `network.log`? If you're on the lastest master there should be logging of the response failures now.

**Comment by VPeruS** [comment]
https://github.com/ppy/osu-framework/blob/d29c8365ba3cf7924b57cf22341f4af55658764c/osu.Framework/IO/Network/WebRequest.cs#L351 go here, right after "{" place `System.Console.WriteLine(e.ToString());`

**Comment by WolfgangAxel** [comment]
@peppy There was nothing new in the log, same as above.

@VPeruS Looks like there's a rouge `null` trying to be converted into an integer somewhere in `WebRequests.cs`.

    Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'statistics.rank.global', line 1, position 1512. ---> System.InvalidCastException: Null object cannot be converted to a value type.
      at System.Convert.ChangeType (System.Object value, System.Type conversionType, System.IFormatProvider provider) [0x00029] in <f56c876907e742b0aa586f051fcce845>:0 
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (Newtonsoft.Json.JsonReader reader, System.Object value, System.Globalization.CultureInfo culture, Newtonsoft.Json.Serialization.JsonContract contract, System.Type targetType) [0x000aa] in <dc86da7fc46c487ba6c7ab826da479cc>:0 
       --- End of inner exception stack trace ---
      at osu.Framework.IO.Network.WebRequest.Complete (System.Exception e) [0x00201] in <4b5899890c8f455781306ff4640f5b0f>:0 
      at osu.Framework.IO.Network.WebRequest.beginResponse (System.Threading.CancellationToken cancellationToken) [0x000ef] in <4b5899890c8f455781306ff4640f5b0f>:0 
      at osu.Framework.IO.Network.WebRequest.internalPerform () [0x00468] in <4b5899890c8f455781306ff4640f5b0f>:0

**Comment by VPeruS** [comment]
That was already covered, try fresh checkout

**Comment by WolfgangAxel** [comment]
A fresh clone seems to have done the trick. My guess is that I wasn't getting the submodule updates with `git remote update`, so that's been added to my update/compile script. My bad... Many, many apologies for continuing this issue. Thank you for all of your help!

**Comment by peppy** [comment]
👍
