### ISSUE TITLE
Sudden crash while playing a beatmap

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#21490]
### Type

Crash to desktop

### Bug description

I just played a beatmap and suddenly the game kept freezing and then crashed. i tried looking for similar issues but im not sure if this is a duplicate of #21200. I decided to open a separate issue because im on windows and the linked issue had the android label.

### Version

2022.1123

### Logs

[database.log](https://github.com/ppy/osu/files/10135472/database.log)
[network.log](https://github.com/ppy/osu/files/10135473/network.log)
[performance.log](https://github.com/ppy/osu/files/10135474/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10135475/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10135476/updater.log)

**Comment by bdach** [comment]
Going to expand scope of original issue to cover non-mobile and close this one as duplicate.
