### ISSUE TITLE
Can't spectate in development build

### ISSUE THREAD

**Issue by JetMouseWasTaken** [ppy/osu#21507]
### Type

Game behaviour

### Bug description

I was playing osu with my new hacked client, but I noticed that while I was in a multiplayer game, peoples' scores wouldn't update until the end of the match. Also I noticed I was unable to spectate other players, as it would continuously show the loading animation.

In [the video](https://youtu.be/an6pwdc1v7M) (sorry it's so choppy and flickery, idk why it's like that), the first osu project was completely unmodified. The second one was my hacked client, which I used to show what it's like in-game. I'm not planning on releasing the code for it because I don't want to be responsible for a ton of hacked client score submissions XD

For the log files, I opened my hacked client, tried to spectate a lobby, then played a match. If there's any weird lines in there, it's because I added a lot of log lines to the code and might have forgotten to comment them all out.

There wasn't anything notable in the log, so I did some digging in the code.
In SpectatorScoreProcessor, in onSpectatorStatesChanged, It keeps setting everything to null because the length of spectatorClient.WatchedUserStates is always 0. I couldn't figure out where things get added to WatchedUserStates, but I think it has something to do with the stuff in OnlineSpectatorClient. In OnlineSpectatorClient, in load, the line
connection.On<int, SpectatorState>(nameof(ISpectatorClient.UserBeganPlaying), ((ISpectatorClient)this).UserBeganPlaying);
get called, and BeginPlayingInternal was never run, but SendFramesInternal did get run.

Anyway, the problem should be really easy to replicate. All you have to do is do a git clone of the repository, and then run the code and try to spectate some people. Let me know if you can figure it out!

### Version

2022.1123.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/10147877/runtime.log)
[performance.log](https://github.com/ppy/osu/files/10147878/performance.log)
[network.log](https://github.com/ppy/osu/files/10147879/network.log)
[input.log](https://github.com/ppy/osu/files/10147880/input.log)
[database.log](https://github.com/ppy/osu/files/10147881/database.log)

**Comment by peppy** [comment]
Please don't connect to production servers using a local build. You will experience issues like this on an ongoing basis.
