### ISSUE TITLE
Android and iOS shows "0.1"

### ISSUE THREAD

**Issue by stevenkiethanete** [ppy/osu#21508]
The Latest Version has a Incorrect Version if you go to app info or check the app package i think the version was not editied or forgotten

Not Correct Version:0.1
Version:Any version or later
![Screenshot_20221201-205926-1-1-1](https://user-images.githubusercontent.com/111575685/205285792-d3483fb1-1218-496d-8893-0e8b5fb98c89.jpg)

_Originally posted by @stevenkiethanete in https://github.com/ppy/osu/discussions/21498_

**Comment by frenzibyte** [comment]
Please refrain from self-escalating discussion threads. We will take action ourselves.
