### ISSUE TITLE
osu!lazer crashing on Android since version 2022.1101.0

### ISSUE THREAD

**Issue by SK-Fast** [ppy/osu#21516]
### Type

Crash to desktop

### Bug description

The game client with version >2022.1101.0 crashed upon start on Android.

Additional details
- I'm using Samsung Galaxy Tab S6 Lite.
- I had Samsung's Game Booster enabled on osu!, at though disabling it still crash the game.
- I'm using Thai Buddhist Calendar. Telling this because from the error, I think it might be related to the calendar.

### Screenshots or videos

simply crashing upon start there
https://user-images.githubusercontent.com/60780448/205585016-777438de-b98c-4463-b9fa-681ed9bbfe3a.mp4

### Version

above 2022.1101.0

### Logs

[database.log](https://github.com/ppy/osu/files/10151865/database.log)
[network.log](https://github.com/ppy/osu/files/10151866/network.log)
[performance.log](https://github.com/ppy/osu/files/10151867/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10151868/runtime.log)

(Couldn't get input.log and other as the file are not there)
![image](https://user-images.githubusercontent.com/60780448/205583468-982b6530-b498-435c-b982-268e2969f3ff.png)

**Comment by smoogipoo** [comment]
Probably cc @Susko3

**Comment by Susko3** [comment]
Can you confirm that there is no crash when using osu! version [2022.1031.0](https://github.com/ppy/osu/releases/tag/2022.1031.0)?

**Comment by SK-Fast** [comment]
> Can you confirm that there is no crash when using osu! version [2022.1031.0](https://github.com/ppy/osu/releases/tag/2022.1031.0)? (If you get a crash, post the log.)
> 
> Also could you show where you've set the calendar to the Thai Buddhist Calendar in your tablet settings. (Screenshots and/or steps you take to change/set the calendar would be beneficial.)

Version 2022.1031.0 doesn't crash, work as expected.

About the calendar settings. The calendar settings does not exist, instead the calendar format is taken from the language settings. so If I set my language to English instead of Thai. It'll work.

![Screenshot_20221205_184040_Settings](https://user-images.githubusercontent.com/60780448/205628672-63d01be6-42cd-4878-9686-2fdb3ca4bdeb.jpg)
*Language settings, normally I use Thai(second one) by default*

![Screenshot_20221205_183902](https://user-images.githubusercontent.com/60780448/205628753-13731813-6423-474e-a105-d1ba7c5b1d48.jpg)
*Latest version works with English as default language*
