### ISSUE TITLE
`Triangles` should have masking enabled by default

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#21515]
### Type

Cosmetic

### Bug description

Creating the issue because I personally think that their scope always should be limited to the drawable, but would like to hear a feedback. Goes both for old and new ones.

### Screenshots or videos

![Снимок экрана (206)](https://user-images.githubusercontent.com/22874522/205551996-acb78d21-90c3-4372-b44b-7d9c721fa4e4.png)
![Снимок экрана (207)](https://user-images.githubusercontent.com/22874522/205551998-711506bc-71ce-4c42-a0ab-0faa0c5cf31d.png)

### Version

master

### Logs

n/a

**Comment by frenzibyte** [comment]
Is this suggesting for the triangle particles to always be clipped to the specified dimensions of the `Triangles` drawable? If so, I would expect that to be the case by default.

**Comment by EVAST9919** [comment]
Yep, that's what I suggest.

**Comment by peppy** [comment]
I agree it should be the default bhaviour.

**Comment by EVAST9919** [comment]
Found a case in which Triangles are expected to be drawn outside of the drawable: explosions in "Triangles" skin.
![img](https://user-images.githubusercontent.com/22874522/214516062-2ceed4db-c4dd-4aef-b0b9-87133941fc94.png)

Not sure what to do about it. May be adding `Masking` property will be the right move? It will have the same meaning, so no confusion with naming or anything.

**Comment by peppy** [comment]
That's indeed a very weird case. `Masking` property is the path of least resistance I guess, if it's simple to implement that way.
