### ISSUE TITLE
osu! Resetting the settings on every launch

### ISSUE THREAD

**Issue by KittyLikeme** [ppy/osu#21530]
### Type

Game behaviour

### Bug description

Relaunching the game causes it to forget all of the settings and it behaves as it was just installed.

### Version

2022.1205.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/10167572/runtime.log)
[performance.log](https://github.com/ppy/osu/files/10167574/performance.log)
[network.log](https://github.com/ppy/osu/files/10167575/network.log)
[database.log](https://github.com/ppy/osu/files/10167576/database.log)

**Comment by JeromTWinL** [comment]
Same Issue for me also after an update.

**Comment by smoogipoo** [comment]
Will be fixed via https://github.com/ppy/osu-framework/pull/5571

**Comment by peppy** [comment]
Will be fixed in a release today.

**Comment by JeromTWinL** [comment]
Now, user settings are kept saved after re-opening osu!
