### ISSUE TITLE
My osu!lazer crashes

### ISSUE THREAD

**Issue by faox50** [ppy/osu#21562]
### Type

Crash to desktop

### Bug description

My osu!lazer crashes randomly, I mean, I'm calm configuring my osu! and just good it doesn't crash it self, an error dialog appears that say what is in the first screenshot.
![a](https://user-images.githubusercontent.com/113381143/206175730-a2c3d293-6440-4185-b397-b41317363790.png)

And osu stays open and when I try to go back to it in the second screenshot you will see the problem.
![s](https://user-images.githubusercontent.com/113381143/206175886-4c5b6b65-d77d-42c0-b851-f11d408eed82.png)

so just in case I will give the specifications of my laptop
![as](https://user-images.githubusercontent.com/113381143/206176045-68c62495-fdde-44af-96fd-0861eef5f16c.png)

and the graphics card is an Intel HD Graphics
and i am not sure if this type of issue is crashing or performance

### Version

2022.1205.0

### Logs

[database.log](https://github.com/ppy/osu/files/10175965/database.log)

[input.log](https://github.com/ppy/osu/files/10175970/input.log)

[performance.log](https://github.com/ppy/osu/files/10175971/performance.log)

[runtime.log](https://github.com/ppy/osu/files/10175972/runtime.log)

[updater.log](https://github.com/ppy/osu/files/10175976/updater.log)

**Comment by WindowsMeosu** [comment]
check `Event Viewer`?

**Comment by bdach** [comment]
This is an unspecified "access violation" driver error that we cannot easily assist with. Please try updating your GPU drivers to a newer version.

Failing that, it may be that we cannot support your device for now until the equivalent of "compatibility mode" (i.e. a directx or vulkan renderer) is added to lazer - this is planned work which is already in progress.
