### ISSUE TITLE
Slider ticks are broken when putting Hard Rock and Mirror in osu! ruleset

### ISSUE THREAD

**Issue by LightningBlueDevs** [ppy/osu#21561]
### Type

Game Behavior

### Bug description

Encountered this a while ago when I was testing some maps with HR and I noticed that slider ticks are way off the sliderbody. No mod seems fine just adding HR makes slidertick broken.

### Screenshots or videos

https://user-images.githubusercontent.com/85861916/206177310-b2430819-ad61-4d86-baef-6083827d32c8.mp4

https://user-images.githubusercontent.com/85861916/206179852-d71f9fa9-0ce0-47f9-81ce-a145c42de817.mp4

### Version

2022.1207.0

### Logs

[database.log](https://github.com/ppy/osu/files/10175952/database.log)
[performance.log](https://github.com/ppy/osu/files/10175953/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10175954/runtime.log)

**Comment by WhetBoi** [comment]
It also seems to do the same thing when mirror is used, and mirror is also increasing the star rating for some reason? It also changes differently based on which mirror specifications you use.

**Comment by bdach** [comment]
Please link the maps involved.

**Comment by bdach** [comment]
Never mind, PR was likely fixed moments ago.

**Comment by bdach** [comment]
Also affects mirror. See [my comment](https://github.com/ppy/osu/pull/21567#issuecomment-1341578553) with elaboration.

**Comment by IdkeMint** [comment]
MR HAVE PP AND STARRATING PROBLEM BUT YOU READ ONLY ABOUT TICKS

**Comment by loma-baldsson** [comment]
> MR HAVE PP AND STARRATING PROBLEM BUT YOU READ ONLY ABOUT TICKS

Please see https://github.com/ppy/osu/issues/21561#issuecomment-1341410762. PP is affected by the same problems as star rating as far as I know

**Comment by IdkeMint** [comment]
im so sorry i didn't noticed it
