### ISSUE TITLE
Login box incorrectly remembers username instead of email

### ISSUE THREAD

**Issue by jai-sharma** [ppy/osu#2156]
When going to login:
![image](https://user-images.githubusercontent.com/8362491/36920856-06c85c7c-1e5a-11e8-9c76-6a9424d21c86.png)

After restart of lazer:
![image](https://user-images.githubusercontent.com/8362491/36920923-3d015f64-1e5a-11e8-809f-a40e7effd06c.png)

The problem seems to be here:
https://github.com/ppy/osu/blob/master/osu.Game/Overlays/Settings/Sections/General/LoginSettings.cs#L213

The textbox is populated with the username, if the APIAccess class is not null.
The APIAccess class does not seem to have the user email as a field.
Also I don't think the password field should be public.

**Comment by UselessToucan** [comment]
Do I understand the problem correctly?

EXPECTED_RESULTS:
1. Whenever I sign in using email, the textbox is populated with the email adress.
2. Whenever I sign in using username, the textbox is populated with the username.

ACTUAL_RESULT:
The textbox is populated with the username in both cases.

Or should the textbox be populated with the email adress in both cases?

**Comment by peppy** [comment]
It should keep the exact value you originally filled in.

**Comment by VPeruS** [comment]
https://github.com/ppy/osu/blob/master/osu.Game/Online/API/APIAccess.cs#L128 this may be a problem

**Comment by Frontear** [comment]
[This Code](https://github.com/ppy/osu/blob/c11f6efab51e3dc57791564525e2879a9ef7952b/osu.Game/OsuGameBase.cs#L219) is the culprit. It saves the username value, which then populates the username field with the username, not the value you typed in. This really isn't a priority, since it causes no real issues, other than minor differences. Lowprio?

**Comment by peppy** [comment]
You can see the priority of an issue by looking at the active milestone.
