### ISSUE TITLE
MR BUGGED

### ISSUE THREAD

**Issue by IdkeMint** [ppy/osu#21568]
### Type

Performance

### Bug description

Mirror mod breaking starrateing and pp also sliderticks are broken ![osu_2022-12-07_22-37-29](https://user-images.githubusercontent.com/100031245/206292090-51b7b18f-99f8-4ec1-a289-735538ba374b.png)
when you turning on mirror firstly you can see how strongly starrateing ![osu_2022-12-07_22-34-22](https://user-images.githubusercontent.com/100031245/206292202-849bc221-2545-4026-b156-da5e3094506f.png)
![osu_2022-12-07_22-34-15](https://user-images.githubusercontent.com/100031245/206292207-908e1174-66b1-45aa-8249-212f935c5e3e.png) got up than after playing map you can see how pp are broken 

![osu_2022-12-07_22-34-36](https://user-images.githubusercontent.com/100031245/206292379-93e8aaf0-bffa-4933-a4af-966f0aea8495.png)
![osu_2022-12-07_22-34-44](https://user-images.githubusercontent.com/100031245/206292385-b5d7f45d-b80b-451e-ac8e-91c9205c0435.png)

### Version

2022.1207.0-laser

### Logs

[database.log](https://github.com/ppy/osu/files/10179896/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10179902/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10179903/network.log)
[performance.log](https://github.com/ppy/osu/files/10179905/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10179906/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10179907/updater.log)

**Comment by bdach** [comment]
Same root cause as #21561.

**Comment by IdkeMint** [comment]
it's not the same 
learn to fucking read then say your opinion

**Comment by IdkeMint** [comment]
sorry if so toxic

**Comment by bdach** [comment]
This was actually found on the performance points discord in parallel to this, which is why I said it's the same root cause. But sure, please do insult my comprehension skills.
