### ISSUE TITLE
Limit URL schemes that osu! can run.

### ISSUE THREAD

**Issue by DHCPCD9** [ppy/osu#21576]
### Type

Game behaviour

### Bug description

Currently osu!(lazer) can run any URL scheme, like `file://`, `stream://`, `calculator://`, etc. I think osu! should able to recognize **only** following URL schemes: `https://`, `http://`, `osu://`.

### Screenshots or videos

https://user-images.githubusercontent.com/92095401/206415789-78442d8c-3b91-41ea-93db-428437a61b8d.mp4

### Version

2022.1208.0

### Logs

[network.log](https://github.com/ppy/osu/files/10184214/network.log)
[performance.log](https://github.com/ppy/osu/files/10184215/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10184216/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10184217/updater.log)
[database.log](https://github.com/ppy/osu/files/10184218/database.log)
[input.log](https://github.com/ppy/osu/files/10184220/input.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu-framework/pull/5574
