### ISSUE TITLE
Can not import replay

### ISSUE THREAD

**Issue by LovelyA72** [ppy/osu#2157]
When i drag and drop replay to lazer's window nothing will happen.
When i tried to open it with osu.exe an error will popup and game will hard crash.

Please tell me if I need to provide any log from lazer.

From my VS2015 debugger:
```
未处理System.NullReferenceException
Message: “System.NullReferenceException”类型的未经处理的异常在 mscorlib.dll 中发生 
其他信息: 未将对象引用设置到对象的实例。
```

**Comment by peppy** [comment]
That alone doesn't help much. Anything in your `runtime.log`?

For what it's worth, I can import replays using both methods on the live build.

Does it help if you ensure the beatmap is present in lazer before loading the replay?

**Comment by LovelyA72** [comment]
Here is my runtime.log:
[runtime.log](https://github.com/ppy/osu/files/1777051/runtime.log)

And an useless screen shoot
![image](https://user-images.githubusercontent.com/29054052/36929926-b858457e-1ed2-11e8-8da0-0a1fb87e4c0b.png)

**Comment by peppy** [comment]
Could you also attach the replay you were trying to load?

**Comment by LovelyA72** [comment]
Here is the file, from this page
[replay-0_404237_1767792072.osr.gz](https://github.com/ppy/osu/files/1777053/replay-0_404237_1767792072.osr.gz)
I added a gzip on it so I can upload. Please ungzip to read the file.
https://osu.ppy.sh/s/166277

**Comment by peppy** [comment]
This issue seems to already be fixed in the next build. It will show a notification about the beatmap not being present instead of crashing.

Please try loading the beatmap first.

**Comment by LovelyA72** [comment]
And yes... My drag and drop function is not working...
lazer will not respond my drag and drop on either osz osr and osk. I have to drag and drop to lazer's executable in order to import...

**Comment by peppy** [comment]
Are you running as administrator? If so, don't.

**Comment by LovelyA72** [comment]
I tried on my other laptop and it works fine...
So there must be sth wrong with my laptop. Thank you so much!
