### ISSUE TITLE
Error popup when scrolling mouse wheel while playing

### ISSUE THREAD

**Issue by PancakeGD** [ppy/osu#2158]
![obrazek](https://user-images.githubusercontent.com/35656715/36935584-e087cc5a-1ef9-11e8-974b-d2a55d07eaad.png)
This appeared when i tried to scroll mouse wheel (to turn down the sounds) while playing osu standard
I'm not a skilled developer and I don't understand this thing but I hope you will.

**Comment by Frontear** [comment]
This error can be reproduced very easily. Enter any beatmap, spam your left and right keys (X and Z by default) and scroll the mouse wheel. This error occurs.

**Comment by FreezyLemon** [comment]
More specifically, press and hold X or Z, scroll up or down, and then release the first key again to produce this crash.

**Comment by Frontear** [comment]
`Trace.Assert` is a boolean, which expects `newlyReleased.All` to return true, given that you scrolled. `newlyReleased.All` expects the `b.KeyCombination.Keys.Contains(scrollwheelkey)`, however recieves `player X or Z input`. This forces `Trace.Assert` to display a message box of the error. It doesn't really do anything for the game, so removing it is safe, however, this isn't the way to deal with this.

**Comment by Frontear** [comment]
@JouzaLoL incorrect. It removes the message box, however it does not fix the underlying problem.

**Comment by smoogipoo** [comment]
Can this still be reproduced? I haven't been able to reproduce it with the aforementioned instructions...

**Comment by peppy** [comment]
Yes, reproducible 100% on latest master and release.
