### ISSUE TITLE
usr/share/icons/hicolor missing from appimage filesystem

### ISSUE THREAD

**Issue by TDCMC** [ppy/osu#21597]
### Type

Cosmetic

### Bug description

The app image file structure seems to have the osu icon, but doesn't have
usr/share/icons/hicolor/1024x1024
usr/share/icons/hicolor/512x512
usr/share/icons/hicolor/256x256
...
This makes it so that when it's installed using AppImageLauncher, the icon shows up in the file manager; but not the application menu.

### Screenshots or videos

![Screenshot from 2022-12-10 12-35-56](https://user-images.githubusercontent.com/69730881/206842488-de0dd5a0-3321-4a40-a3e3-a003cf009e6d.png)

### Version

2022.1208.0-lazer

### Logs

N/A

**Comment by bdach** [comment]
> This is why AppImage is not available currently

this is WILDLY incorrect

**Comment by bdach** [comment]
duplicate / tracking in https://github.com/ppy/osu-deploy/issues/158, also, by the way
