### ISSUE TITLE
osu!mania scroll speed changes when launchung the game

### ISSUE THREAD

**Issue by Bruno5430** [ppy/osu#21611]
### Type

Game behaviour

### Bug description

Each time I launch the game it adds an extra 0 at the scroll speed ms value
Re-launching the game with the extra 0 will not stack more digits if the resulting value exceeds 11485ms (max ms value of the slider) and will remain the same value as before

### Screenshots or videos

| Value before closing the game | Value after re-launching the game |
| --- | --- |
| ![1010ms](https://user-images.githubusercontent.com/111712756/206914824-b72425d3-4b26-4050-adba-fda49da3ffd0.png) | ![10100ms](https://user-images.githubusercontent.com/111712756/206914827-f0868c0d-e09a-44a5-920b-73b363dfe6fb.png) |
| ![290ms](https://user-images.githubusercontent.com/111712756/206914797-7084c75c-be0e-4b9b-867f-8dd0a915bd55.png) | ![2900ms](https://user-images.githubusercontent.com/111712756/206914810-a10795cb-89ae-4e57-856e-a723d9807514.png) |

### Version

2022.1208.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/10202616/runtime.log)
[performance-update.log](https://github.com/ppy/osu/files/10202617/performance-update.log)
[performance-input.log](https://github.com/ppy/osu/files/10202618/performance-input.log)
[performance-draw.log](https://github.com/ppy/osu/files/10202619/performance-draw.log)
[performance-audio.log](https://github.com/ppy/osu/files/10202620/performance-audio.log)
[performance.log](https://github.com/ppy/osu/files/10202621/performance.log)
[network.log](https://github.com/ppy/osu/files/10202622/network.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10202623/legacy-ipc.log)
[input.log](https://github.com/ppy/osu/files/10202624/input.log)
[database.log](https://github.com/ppy/osu/files/10202625/database.log)

**Comment by peppy** [comment]
What locale is your system set to?

**Comment by Bruno5430** [comment]
es_AR
