### ISSUE TITLE
Cursor Flicking

### ISSUE THREAD

**Issue by Ertersilva** [ppy/osu#21613]
### Type

Game behaviour

### Bug description

When the cursor goes all the way to the right, the cursor starts flickering insanely

### Screenshots or videos

https://user-images.githubusercontent.com/100218407/206919143-e5ba7713-e54d-45d2-b9ad-e3a807dc06bc.mp4

### Version

Stable - b20221208.5

### Logs

[performance.log](https://github.com/ppy/osu/files/10202791/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10202792/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10202793/updater.log)
[database.log](https://github.com/ppy/osu/files/10202794/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10202795/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10202796/network.log)

**Comment by bdach** [comment]
Stable issues don't go here. This repository is for lazer only.

**Comment by Ertersilva** [comment]
> Stable issues don't go here. This repository is for lazer only.

sorry :/
