### ISSUE TITLE
Mods settings restore to default after changing ruleset

### ISSUE THREAD

**Issue by BlestLace** [ppy/osu#21634]
### Type

Game behaviour

### Bug description

I just wanted to play a specific map with mods, and I tried osu!mania... I had dt at 0.10x and quickly changed over to mania, the song started playing much faster. Turns out, dt's setting had been changed over from 0.10x to 0.50x (default setting).

(in case you didn't know, dt stands for "double time".)

### Screenshots or videos

I would greatly have posted a video here, but it's too big.
I will post photos here, and you'll need to open them in order.

![first](https://user-images.githubusercontent.com/96539694/207403672-dfaa7041-65ab-448b-88b4-8699125ffd96.png)
![second](https://user-images.githubusercontent.com/96539694/207403684-e57b70ea-ee03-4d42-9699-f03f087bcbcb.png)
![third](https://user-images.githubusercontent.com/96539694/207403687-cca16a35-3cf5-4ea9-87b4-2bca3a64ac03.png)
![fourth](https://user-images.githubusercontent.com/96539694/207403680-3b9b2171-86d3-4c4a-a999-65200333dc4a.png)

### Version

osu! 2022.1208.2-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10220628/database.log)
[input.log](https://github.com/ppy/osu/files/10220629/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10220630/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10220631/network.log)
[performance.log](https://github.com/ppy/osu/files/10220632/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/10220633/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10220634/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10220635/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10220636/updater.log)

**Comment by bdach** [comment]
I guess wanting mod settings to persist when changing rulesets is reasonable if we're keeping them enabled since #20758. It's a little tricky though because sometimes mods that have the same acronym don't exactly have the same set of settings in all rulesets.

**Comment by peppy** [comment]
Best effort sounds like a good path... just try-catch any failures to copy.
