### ISSUE TITLE
Refreshing skin makes game elements go away along with skin elements

### ISSUE THREAD

**Issue by ParaliyzedEvo** [ppy/osu#21656]
### Type

Other

### Bug description

Pretty much I do is ctrl+alt+shift+s which makes the skin refresh and yea I get missing elements for skin and elements part of the game. So yeah, the only solution is to keep refreshing it until it comes back so it's kinda an annoying bug (personally) in my opinion. Just saying logs might not helped since this was a day ago so it might be outdated. MB

### Screenshots or videos

![68747470733a2f2f692e6962622e636f2f387a505358324d2f53637265656e73686f742d32303232313231302d3130303830362e706e67](https://user-images.githubusercontent.com/107338855/208018218-cd780fc6-7e76-411c-8e4c-c829e7aa9b01.png)

### Version

Cutting Edge 20221208.3

### Logs

[network.log](https://github.com/ppy/osu/files/10242546/network.log)
[osu!auth.log](https://github.com/ppy/osu/files/10242547/osu.auth.log)
[performance.log](https://github.com/ppy/osu/files/10242548/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10242549/runtime.log)
[session.log](https://github.com/ppy/osu/files/10242550/session.log)
[update.log](https://github.com/ppy/osu/files/10242551/update.log)
[update_success.log](https://github.com/ppy/osu/files/10242552/update_success.log)

**Comment by peppy** [comment]
This is a stable issue (you posted against the lazer github), and also going to be 100% a driver issue. Please upgrade or downgrade your GPU drivers or switch the game to compatibility mode.
