### ISSUE TITLE
`LeaderboardScore` and some other `OsuClickableContainer`s do not have hover (click) sounds

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#21676]
### Type

Game behaviour

### Bug description

Regressed in https://github.com/ppy/osu/pull/21619.

That PR made hover sounds possible to be removed when using `Child`/`Children` in `load()`/`LoadComplete()`. Not sure of a good solution other than:
- Replacing those with `Add()`/`AddRange()` and restricting `Child`/`Children` somehow
- Moving `CreateHoverSounds()` to `LoadComplete()` and hope there's no `Child`/`Children` calls after

### Screenshots or videos

https://user-images.githubusercontent.com/35318437/208231081-eb73a1ff-6662-4bb9-bcfe-a510ade9db3e.mp4

### Version

master

### Logs

N/A

**Comment by bdach** [comment]
I was wondering about that yesterday but didn't get to looking into it more.......

Both solutions proposed seem suboptimal but I can't think of anything better on the spot.

@EVAST9919 thoughts?

**Comment by EVAST9919** [comment]
May be make a private class in `OsuClickableContainer` which will hold hover sounds as an internal drawable and make that a content instead? Should repair this case and leave everything working in mentioned pr, but that'd be too many containers probably: this new container having sounds and another container for content and it's everything in `OsuClickableContainer`

**Comment by bdach** [comment]
Yeah I was thinking something along those lines too but that does seem to be getting close to too much overhead.

**Comment by peppy** [comment]
I'd fix the cases and throw on `AddInternal` / `AddRangeInternal` if that's ample to solve this. More containers sounds bad

**Comment by EVAST9919** [comment]
It's not an `Internal` problem. Since we are adding `HoverSounds` to the content container - any setting/clearing children in sub-classes will remove the sounds. So I guess throwing on `Clear()` and `Children.set` then?

**Comment by peppy** [comment]
pretty sure those call `AddInternal` themselves, but yeah, that's the direction I was thinking.

**Comment by wiskerz76** [comment]
Is it alright if @RaafatSalib and I look into fixing this issue? Do you have any further suggestions before we get started?

**Comment by Joehuu** [comment]
Yep, that is what the `good-first-issue` label is for. I recommend reading the [Submitting pull requests](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#submitting-pull-requests) section of the contributing guidelines first, and don't hesitate to ask questions in the [Discord server](https://discord.gg/ppy) (or here until you are verified).

**Comment by wiskerz76** [comment]
I might be overlooking something obvious with this, but why can't the `HoverSounds` be added as an `Internal` component of `OsuClickableContainer` rather than as a direct child? From what I can tell, this prevents the sounds from being removed in any sub-classes.

**Comment by peppy** [comment]
Everything is in a hierarchy. That's how osu!framework works.

**Comment by bdach** [comment]
> why can't the `HoverSounds` be added as an `Internal` component of `OsuClickableContainer` rather than as a direct child?

That would be a partial revert of the PR mentioned in the OP. Does that not regress the issue that PR was fixing?

**Comment by wiskerz76** [comment]
It doesn't appear to bring back the original issue of buttons receiving input outside the content. Although, I don't know the details of exactly how to reproduce the original issue, keeping the `HoverSounds` as `Internal` still passes the test created in the PR mentioned.

**Comment by bdach** [comment]
The test doesn't test audio playback because testing that is pretty much not feasible as we have things structured.

Also I've checked, and changing back to `AddInternal()` would regress the fix. See following video:

https://user-images.githubusercontent.com/20418176/214396008-b4d65d19-08e8-4ccc-a546-0e2035393f80.mp4

Notice how I can get the hover sound to play even though the mouse is not inside the bounds of the actual button part of the pink sheared "back" button yet.

**Comment by wiskerz76** [comment]
From your previous discussion about this issue, it seems that the best solution at the moment is to throw on `Clear()` in the `OsuClickableContainer` component, and then in all `OsuClickableContainer` subclasses, we change all instances of `Child = ...`  or `Children = new Drawable[] {...} `to Add(...)  and `AddRange(new Drawable[] {...}` in order to  not overwrite the component responsible for the hover sound.
Do you think I should go ahead with implementing this solution?

**Comment by bdach** [comment]
That solution is already described in this issue thread, yes.

**Comment by Joehuu** [comment]
I found a more amicable solution. How about adding:
```csharp
public override bool ReceivePositionalInputAt(Vector2 screenSpacePos) => Parent?.ReceivePositionalInputAt(screenSpacePos) ?? false;
```
to `HoverSampleDebounceComponent` (the base class of `Hover{Click}Sounds`)? There is one precedent with using `Parent` here:
https://github.com/ppy/osu/blob/7bc8908ca9c026fed1d831eb6e58df7624a8d614/osu.Game/Rulesets/Edit/PlacementBlueprint.cs#L124

I could also refactor the base class to inherit `Component` instead of `CompositeDrawable` and effectively make it a `0x0` drawable (if that improves anything).

---

Removing `good-first-issue` and assigning myself for now.

**Comment by peppy** [comment]
Given what the component is doing, that may be a good solution.

Not so sure about making them `0x0` size though.
