### ISSUE TITLE
The end of the slider gets a combo counter when shifted

### ISSUE THREAD

**Issue by Maks1mio** [ppy/osu#21677]
### Type

Game behaviour

### Bug description

The video shows the bug.

### Screenshots or videos

https://user-images.githubusercontent.com/44835662/208235403-ec402f13-6aef-453e-b78f-5aa8e643e8f7.mp4

https://user-images.githubusercontent.com/44835662/208235406-b078f9b8-4b20-4f69-8cf7-cac89e78997a.mp4

### Version

2022.1208.0

### Logs

[performance.log](https://github.com/ppy/osu/files/10251403/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10251404/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10251405/updater.log)
[database.log](https://github.com/ppy/osu/files/10251406/database.log)
[network.log](https://github.com/ppy/osu/files/10251407/network.log)

**Comment by bdach** [comment]
Also falls under scope of #10455
