### ISSUE TITLE
When scrolling a map in mania, the sliders are not drawn correctly

### ISSUE THREAD

**Issue by Maks1mio** [ppy/osu#21680]
### Type

Game behaviour

### Bug description

If you use SHIFT + scroll mouse back, the map behaves very strangely.

I don't know if there was such a bug report, but I'll just leave it here.

### Screenshots or videos

https://user-images.githubusercontent.com/44835662/208245411-c4d49ec7-64f7-4bbc-b6f7-eed7cd001737.mp4

### Version

2022.1208.0

### Logs

[database.log](https://github.com/ppy/osu/files/10251841/database.log)
[network.log](https://github.com/ppy/osu/files/10251842/network.log)
[performance.log](https://github.com/ppy/osu/files/10251843/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10251844/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10251845/updater.log)

**Comment by bdach** [comment]
Let's track under #10455

**Comment by loma-baldsson** [comment]
#21090 may be relevant
