### ISSUE TITLE
Insane performance Issue on this map during gameplay and while editing

### ISSUE THREAD

**Issue by Inconsist** [ppy/osu#21706]
### Type

Performance

### Bug description

When the map shown in the recording reaches a certain slider, you can see that my performance drops immensely (Ryzen 12 core and 3060 minus overhead for recording). So I went to the editor, where the performance is also terrible. But once I clicked on that silder (01:36) the game just froze, at (01:49) I tabbed out which reset me from editior view to songselect. At some point I heard sounds again(02:11) after spamming escape in the meantime, but the screen never updates, so much even that when I move other windows over the lazer one on my main screen these freeze as well. That effect might be unrelated though. I assume that at (02:26) I quit the game after inputting escape 2 times and then holding 1, but as you can see its still visible. Anyways I have to close the game via Taskmanager nothing else works. Windows also does not show the "application not responding" error, and from what I heard at the end of the video something is responding, but as said, visuals are never updated.

I hope im not reporting 2 issues at once here(gameplay and editor), if so just tell me what to do to make it fit your report structure.

### Screenshots or videos

[https://www.youtube.com/watch?v=U-ww4YB_suU](url)

The video was too long and therefor larger then 10 MB. I uploaded it to youtube unlisted, hope that works for you.

### Version

2022.1208.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/10255317/runtime.log)
[session.log](https://github.com/ppy/osu/files/10255318/session.log)
[update_success.log](https://github.com/ppy/osu/files/10255319/update_success.log)
[osu!auth.log](https://github.com/ppy/osu/files/10255320/osu.auth.log)

(from my understanding these are osu standard logs, but the guide says to use these so... It's a lazer issue though.)

**Comment by loma-baldsson** [comment]
Related: #21495

**Comment by Inconsist** [comment]
> Related: #21495

I knew about the other issue you linked and completely agree, but this is so severe that the game literally crashes. And btw I could not reopen lazer until I did a full system restart. At least in the other issue it was possible to edit the slider or at least inspect it without a crash like this. Just let the moderators for this project decide wether to add the details of my report to the existing one or if its worth its own. Idk.

**Comment by peppy** [comment]
Please link the beatmap.

**Comment by Inconsist** [comment]
https://osu.ppy.sh/beatmapsets/1125563#osu/2359830

Its the correct diff. Slider at around 01:03

**Comment by peppy** [comment]
Let's track at https://github.com/ppy/osu/issues/21495. It's the same issue. Also I'm not sure we can support such edge cases in loved beatmaps, but we'll do our best to do something about it.
