### ISSUE TITLE
Kiai flashes in osu! ruleset are way too strong

### ISSUE THREAD

**Issue by stanriders** [ppy/osu#21747]
### Type

Cosmetic

### Bug description

Same as #21569 but in osu! ruleset.

It gets really distracting when using skins with colorful hitcircles. Stable has the flashing too, but its way more subtle.

### Version

2022.1208.0

### Logs

-

**Comment by peppy** [comment]
I've compared with stable and the implementation is seemingly very wrong. Will work on fixing this.
