### ISSUE TITLE
osu! lazer crashes on mania mode, if quick-retry and 'release' judge occur simultaneously

### ISSUE THREAD

**Issue by Clpsplug** [ppy/osu#21748]
### Type

Crash to desktop

### Bug description

I quick-retried while holding the 'hold notes' in osu!mania. The end of the said notes was about to occur (and thus the judgment,) then osu! reported an internal error then promptly crashed to the desktop.

## Repro steps

1. Launch osu!lazer as usual.
2. Start an osu!mania beatmap. To save time, choose one that starts with reasonably long 'hold notes.'
3. Perform a hold. Do *not* let the keys go.
4. Wait until the end of the said hold notes approaches.
5. Just as the hold notes are about to pass the judgment line, perform a quick retry.
6. For a split second, you can observe the game's notification system logging an internal error.
7. At the next instant, osu!lazer straight-up dies.

## Repro frequency

So far, I can repro this crash 100% of the time. 

## Additional context

The hold note doesn't need to be the one at the start to cause a crash, i.e., the crash-causing condition is just that quick-retry and 'hold end' judge occur simultaneously.  
Checked for keywords like "mania," "hold," and "crash" (including closed issues!), but none of the issues or Q&As seem to be about this crash.

## Environment
* macOS Monterey 12.6 (21G115)
* osu!lazer 2022.1208.0-lazer

### Screenshots or videos

I have the footage where I perform the repro steps above on Gyazo; **visit https://gyazo.com/7df89bd00dd0404c87530a844f6135a4 for full FPS footage.**

[![Image from Gyazo](https://i.gyazo.com/7df89bd00dd0404c87530a844f6135a4.gif)](https://gyazo.com/7df89bd00dd0404c87530a844f6135a4)

### Version

2022.1208.0-lazer

### Logs

Note that all these logs were uploaded right after I repro'd the crash.

[database.log](https://github.com/ppy/osu/files/10278476/database.log)  
[input.log](https://github.com/ppy/osu/files/10278478/input.log)  
[network.log](https://github.com/ppy/osu/files/10278480/network.log)  
[performance.log](https://github.com/ppy/osu/files/10278482/performance.log)  
[runtime.log](https://github.com/ppy/osu/files/10278484/runtime.log)

**Comment by bdach** [comment]
Can reproduce. Weirdly enough this doesn't seem happen on the argon skin in my testing, though?

**Comment by Clpsplug** [comment]
> Weirdly enough this doesn't seem happen on the argon skin in my testing

Can repro on my side regardless of the skin used (official, edited, doesn't matter,) although it was a bit hard to hit the right spot when using the Argon skin.

Something I realized later is that the crash seems to occur *after I release the quick-retry key.* Depending on when it is released, the internal crash handler notification fails to spawn before osu!lazer calls it quits.

**Comment by bdach** [comment]
Yeah the fix I submitted for this is skin-agnostic.
