### ISSUE TITLE
Game won't start shortly because of the player opened his notification pannel in multi

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#21758]
### Type

Game behaviour

### Bug description

Game starts right after ONE minute but should after everyone is loaded no matter they opened his notifications or not.

### Screenshots or videos

https://user-images.githubusercontent.com/86934170/209138105-c5cc471b-0092-402e-a60b-376664f306b7.mp4

https://user-images.githubusercontent.com/86934170/209139012-2fb1f3d2-6f41-4a62-9883-ef05d65eb11d.mp4

### Version

1208

### Logs

-

**Comment by bdach** [comment]
I don't know. What if you want to adjust settings? Change skin? Adjust literally anything quickly in the loading screen?

Maybe the timeout is excessive but I don't know about force-closing all overlays in sight immediately.

**Comment by Loreos7** [comment]
> 
I don't think players should wait for others that long. Maybe like 10-15 seconds but not a whole minute.

**Comment by peppy** [comment]
We originally decided on one minute to cover slow load times, but I have previously mentioned reducing to 30s. I think that would be a good first step.

**Comment by Loreos7** [comment]
> We originally decided on one minute to cover slow load times, but I have previously mentioned reducing to 30s. I think that would be a good first step.

Yeah, I can agree.
