### ISSUE TITLE
Score replays do not get saved online

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu#21773]
### Type

Game behaviour

### Bug description

when setting a score in the top 50 of a beatmap, its replay is not saved. idk how long this issues has been a thing for, but i haven't found a score that is available for download when looking for older (even year-old) ones

they are however available locally when you set them as you'd expect

### Screenshots or videos

![image](https://user-images.githubusercontent.com/36758269/209355352-1836d009-a4e7-4083-aab6-ae11b46917aa.png)

example 1:

https://osu.ppy.sh/beatmapsets/232518#osu/539811

![image](https://user-images.githubusercontent.com/36758269/209355847-4614f4aa-4ed7-4f71-9d00-2ee54106db8a.png)

example 2: 

https://osu.ppy.sh/beatmapsets/1126845#osu/2354363

![image](https://user-images.githubusercontent.com/36758269/209355912-952a8212-7d4f-4bfb-b3b5-fe7ab64b2539.png)

### Version

2022.1208.0-lazer

### Logs

not necessary i believe

**Comment by bdach** [comment]
As stated on discord they are intercepted by the spectator server and a recent change [added upload to S3](https://github.com/ppy/osu-server-spectator/pull/155). So I guess this can remain open for tracking but I don't imagine that anything needs to specifically happen client-side for this to be fixed?

**Comment by peppy** [comment]
This is now resolved, but not deployed. I'll close the issue as we will be deploying / tracking this internally as we continue with the leaderboard improvements on lazer.
