### ISSUE TITLE
Fully-faded hitobjects in editor can still be selected

### ISSUE THREAD

**Issue by OninDynamics** [ppy/osu#21793]
### Type

Game behaviour

### Bug description

When a mapper opts to disable white hitmarkers in the editor, hitobjects in the past becomes invisible. These hitobjects should no longer be selectable.

As of writing, completely invisible hitobjects can be accidentally interacted with.

### Screenshots or videos

https://user-images.githubusercontent.com/71348981/209471487-0a73a617-758b-4fcb-950d-348ab5bd810f.mp4

### Version

2022.1208.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10301371/database.log)
[input.log](https://github.com/ppy/osu/files/10301372/input.log)
[network.log](https://github.com/ppy/osu/files/10301373/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/10301374/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10301375/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10301376/performance-input.log)
[performance.log](https://github.com/ppy/osu/files/10301377/performance.log)
[performance-update.log](https://github.com/ppy/osu/files/10301378/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10301379/runtime.log)

**Comment by peppy** [comment]
Is that how it works on stable?

**Comment by OninDynamics** [comment]
Yep, in Stable, turning `View>Hit Animations` = `enable` makes objects fade much faster, in turn making them no longer selectable.

**Comment by OliBomby** [comment]
this issue appears to have since been fixed

**Comment by peppy** [comment]
Yep!
