### ISSUE TITLE
lost beatmas/skin/score/collections after delete and re-install

### ISSUE THREAD

**Issue by cakestheking** [ppy/osu#21808]
### Type

Game behaviour

### Bug description

So before doing anything I copied the ''files'' folder that contains all of the beatmas/skin/score/collections to another drive not to lose anything. I then proceeded to uninstall anything osu!lazer related in C:\Users\Asus\AppData\Roaming\osu and C:\Users\Asus\AppData\Local\osulazer because I thought that I could fresh/clean install it on a different drive. (turns out I can't select the install location) So now taking the initially copied ''files'' folder and placing it in C:\Users\Asus\AppData\Roaming\osu, the game doesn't recognize any contents inside of it. why? how can I fix this?

### Version

2022.1208.0

### Logs

[database.log](https://github.com/ppy/osu/files/10306169/database.log)
[input.log](https://github.com/ppy/osu/files/10306170/input.log)
[network.log](https://github.com/ppy/osu/files/10306171/network.log)
[performance.log](https://github.com/ppy/osu/files/10306172/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10306173/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10306174/updater.log)

**Comment by enoslayd** [comment]
you also need to have the old client.realm file placed on Roaming\osu folder

**Comment by bdach** [comment]
See above. You probably didn't copy the realm database. This makes the installation no longer recoverable.

Please don't touch the files manually. If you must, then the way to do this is to back up the entire `osu` directory rather than just the `files` subdir.

**Comment by cakestheking** [comment]
is there anything i can do to salvage my beatmaps?

**Comment by bdach** [comment]
Not really. We don't provide any way to recover from this sort of scenario. It isn't completely impossible but the amount of effort required is likely too high to be worth it.

When in doubt just please don't modify game files manually unless you actually know what you're doing/
