### ISSUE TITLE
PP values displayed in lazer client and on website aren't the same

### ISSUE THREAD

**Issue by DutchEllie** [ppy/osu#21815]
### Type

Game behaviour

### Bug description

I set a score on Lazer. The client showed me I got 89pp. But the [score page on the website](https://lazer.ppy.sh/scores/2165163328) shows 71pp.
Another more different [play on the website shows 68pp](https://lazer.ppy.sh/scores/2165314696), but in the client was 81pp. (Second screenshot)

### Screenshots or videos

![osu_2022-12-27_19-02-12](https://user-images.githubusercontent.com/6501187/209705163-9c5ce05b-8562-493d-9363-5071a45540c9.jpg)
![osu_2022-12-27_18-59-12](https://user-images.githubusercontent.com/6501187/209705541-a3e6d906-193c-402b-a52d-89c269f47207.jpg)

### Version

2022.1227.0

### Logs

[database.log](https://github.com/ppy/osu/files/10310005/database.log)
[input.log](https://github.com/ppy/osu/files/10310006/input.log)
[network.log](https://github.com/ppy/osu/files/10310007/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/10310008/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10310009/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10310010/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10310011/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/10310012/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10310013/runtime.log)

**Comment by Non-Binary-Programmer** [comment]
This appears to be #19386 combined with the website showing lazer scores.

**Comment by bdach** [comment]
Likely explanation provided here https://github.com/ppy/osu/issues/12542#issuecomment-1366192979

**Comment by bdach** [comment]
Also reported externally (https://twitter.com/GreyMatterMr/status/1608580668120010753)

**Comment by peppy** [comment]
@smoogipoo going to leave this one to you

**Comment by peppy** [comment]
@smoogipoo any idea on the state of this? is it fine to close as something which we'll ensure is correct when resetting the leaderboards? or worth investigating imminently?

**Comment by smoogipoo** [comment]
I'm not really sure on the state of this, and I personally don't think it's too important for the time being. I want to see how things are after the leaderboard reset and reassess at that time. The linked issue is quite full of data that is hard to look through.

**Comment by developomp** [comment]
The problem very much still is a thing if that's what you want to know @peppy.

**Comment by peppy** [comment]
Thanks, we'll mak sure to check after redeploying all components more close to score reset. Please re-check from your end at a later date.

**Comment by CdrSonan** [comment]
I'm still getting this issue in the latest version (2023.914.0).
PP scores on the website are consistently lower than the ones reported after a game by about 20-30%.
This also happened on the previous version, although I don't have the exact version number for it.

(Apologies in case the mentioned redeploy hasn't happened yet)

**Comment by SevenChords** [comment]
Issue is still present in 2023.1026.0-lazer.
just got a score displaying as 64pp in game and 48pp when checking my profile.

**Comment by peppy** [comment]
> Issue is still present in 2023.1026.0-lazer.
> 
> just got a score displaying as 64pp in game and 48pp when checking my profile.

Please provide links and screenshots showing what you are seeing.

**Comment by SevenChords** [comment]
Here is a fresh example (the difference is present consistently on every single play and it was easier to get screenshots on a fresh play)
The Result screen in game directly after finishing the beatmap (27pp):
![image](https://github.com/ppy/osu/assets/31819497/48c0b802-be79-4931-a1ee-0ff00df38d4c)
The Performance Breakdown (also directly after finishing the beatmap, same 27pp):
![image](https://github.com/ppy/osu/assets/31819497/f45139ff-a1e7-42ec-81d5-d7583ea8c2b3)
Viewing Recent Plays in my Profile in game (22pp):
![image](https://github.com/ppy/osu/assets/31819497/b812dddd-0bc9-4e90-a780-83b6a75bbd28)
Viewing Recent play in my profile on lazer.ppy.sh (osu.ppy.sh shows pp as `-` since it was a score set in lazer) (22pp):
![image](https://github.com/ppy/osu/assets/31819497/56a18a34-ae96-4230-9f9e-a964d66bfca1)

**Comment by CdrSonan** [comment]
I still have the issue as well.
PP displayed in my profile are lower than the ones displayed after a play, or in the score list of the beatmap in the beatmap selection screen.

Using the Classic mod fixes this and makes PP counts consistent. Other mods don't seem to have any effect.

Viewing a nomod score after setting it (20PP):
<img width="1920" alt="postgame" src="https://github.com/ppy/osu/assets/64283097/a2739cc8-a32c-4a8a-9fa2-8842fcba26ab">
Viewing a classic mod score after setting it (39PP):
<img width="1920" alt="postgameClassic" src="https://github.com/ppy/osu/assets/64283097/80027baa-1cf0-48ca-a4f6-36ee791028aa">
Viewing both scores in my profile (15 and 39PP respectively):
<img width="1920" alt="profile" src="https://github.com/ppy/osu/assets/64283097/135a8718-57fd-4720-bbd2-98e010f09375">
Viewing both scores on lazer.ppy.sh (also 15 and 39PP):
<img width="727" alt="website" src="https://github.com/ppy/osu/assets/64283097/3ce2a73c-514a-46bd-a959-5f11de2d8f27">

**Comment by peppy** [comment]
I'm guessing this is going to be due to diffcalc changes which haven't been deployed yet? And if so, we should probably try and get a new `score-statistic-processor` out in some form..

**Comment by bdach** [comment]
> And if so, we should probably try and get a new `score-statistic-processor` out in some form..

Currently blocked by https://github.com/ppy/osu-infrastructure/issues/15, unless you want to try the new processors live without the indices and see if they handle the load well enough.

**Comment by smoogipoo** [comment]
A new score statistics processor is not going to fix this. The issue in the above few posters appears to be the use of non-classic mod, whereas we only store and use classic-mod difficulty attributes to the table.

**Comment by bdach** [comment]
Or I guess we just agree that mods should not change max combo of a map?

**Comment by smoogipoo** [comment]
Can that be enforced even with the current mod selection? For example, doesn't mania's no holds mod change combo? In that particular case, the mod itself is "pp-unranked", but what about when it starts to give pp?

**Comment by bdach** [comment]
Yeah okay I forgot about that one. Target probably too, etc.

**Comment by peppy** [comment]
For the majority case, it seems like matching osu! ruleset no mod combo would resolve this (already on my list).
