### ISSUE TITLE
Missing .apk file in latest realese.

### ISSUE THREAD

**Issue by justinweichTV** [ppy/osu#21817]
### Type

Crash to desktop

### Bug description

Missing .apk file in latest realese.

### Screenshots or videos

https://1drv.ms/u/s!AubUEEgXFkKvgV2e2PGcP1arA_u-

### Version

2022.1227.0

### Logs

None

**Comment by peppy** [comment]
read

**Comment by bdach** [comment]
https://osu.ppy.sh/comments/2557698 is what you should be reading, to be more precise
