### ISSUE TITLE
Hit Accuracy seems to be broken

### ISSUE THREAD

**Issue by JonLit** [ppy/osu#21849]
### Type

Game behaviour

### Bug description

it's displaying I have 9607.02% Hit Accuracy...
see screenshot

### Screenshots or videos

![Uploading image.png…]()

### Version

2022.1227.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10310884/database.log)
[input.log](https://github.com/ppy/osu/files/10310885/input.log)
[network.log](https://github.com/ppy/osu/files/10310886/network.log)
[performance.log](https://github.com/ppy/osu/files/10310887/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10310888/runtime.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21843
