### ISSUE TITLE
Alltime Accuracy display is bugged (multiplied by 100 twice) 

### ISSUE THREAD

**Issue by snowynguyen** [ppy/osu#21843]
### Type

Cosmetic

### Bug description

Have a look at the image below, where my accuracy is displayed as 9630.85%. This is most likely a display error and can be patched easily. 
![image](https://user-images.githubusercontent.com/30857393/209720328-144542eb-325a-4587-9e74-876adeda2daf.png)

### Version

2022.1227.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/10310643/network.log)
[performance.log](https://github.com/ppy/osu/files/10310644/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10310645/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10310647/updater.log)
[database.log](https://github.com/ppy/osu/files/10310648/database.log)
[input.log](https://github.com/ppy/osu/files/10310649/input.log)

**Comment by peppy** [comment]
https://github.com/ppy/osu/pull/21819
