### ISSUE TITLE
Overall Ranking loads forever

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu#21847]
### Type

Performance

### Bug description

The Overall Ranking section of the scorecard display, which shows up after finishing a solo play has not stopped loading for me, ever. I have left it loading for several minutes previously. I have experienced no other problems with loading or connectivity on my network.

This happens with 100% consistency, in osu!standard, osu!taiko, and osu!mania, although it does not occur in osu!catch. This may be because I have far fewer osu!catch plays or because I wasn't ranked for osu!catch on the [lazer website](lazer.ppy.sh) before this play, or some other reason.

I'm sorry if this is a duplicate of one of those sentry issues, I don't understand them well enough to tell.

### Screenshots or videos

Loading screen:
<img width="1512" alt="Screen Shot 2022-12-27 at 2 54 03 PM" src="https://user-images.githubusercontent.com/100527514/209721291-06a7d0f7-767f-47fe-ae55-4268219008c4.png">
Properly displaying on osu!catch:
<img width="1512" alt="Screen Shot 2022-12-27 at 3 07 47 PM" src="https://user-images.githubusercontent.com/100527514/209722418-937fc16e-ffca-40c3-9ed9-2bd28bcf4bd4.png">

### Version

2022.1227.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10310723/database.log)
[input.log](https://github.com/ppy/osu/files/10310724/input.log)
[network.log](https://github.com/ppy/osu/files/10310725/network.log)
[performance-draw.log](https://github.com/ppy/osu/files/10310726/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10310727/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/10310728/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10310729/runtime.log)

**Comment by bdach** [comment]
Yes I've observed this happening myself. It is not entirely clear to me why this is happening, it seems non-deterministic in nature. The likeliest explanation I can provide is that the stats updates are calculated asynchronously, and delivery of those updates times out after 30 seconds server-side. So if there is congestion on the server that leads those updates to be dropped due to scores taking too long to process, that would explain update delivery failure - that said I would need @peppy to take a look at the datadog metrics from osu-server-spectator to rule this out.

**Comment by bdach** [comment]
In empirical testing this seems better on my end today. @Non-Binary-Programmer please confirm whether you can see any improvement on your end too.

**Comment by Non-Binary-Programmer** [comment]
Can confirm, loads practically instantly on all rulesets now.

**Comment by bdach** [comment]
Let's just chalk this up to first-day teething issues and close for now. If it gets worse again we'll reopen and investigate.

**Comment by SevenChords** [comment]
i have just re-encountered this issue while playing mania or the first time in a while, never had that happen when playing standard, so maybe it's something that happens if you haven't played a gamemode in a while and the server's need to reprocess a lot of data
