### ISSUE TITLE
Hit Accuracy displays improperly for osu!catch scores

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu#21848]
### Type

Cosmetic

### Bug description

In the Overall Ranking section of the osu!catch scorecard, hit accuracy is displayed incorrectly. It appears that the decimal point is being placed incorrectly, two places to the right of where it should be (my actual hit accuracy is 98.15%). I have no idea if this affects other rulesets due to #21847 .

### Screenshots or videos

Example score:
<img width="1512" alt="Screen Shot 2022-12-27 at 3 07 47 PM" src="https://user-images.githubusercontent.com/100527514/209722418-937fc16e-ffca-40c3-9ed9-2bd28bcf4bd4.png">

### Version

2022.1227.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10310783/database.log)
[input.log](https://github.com/ppy/osu/files/10310784/input.log)
[network.log](https://github.com/ppy/osu/files/10310785/network.log)
[performance-draw.log](https://github.com/ppy/osu/files/10310786/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10310787/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/10310788/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10310789/runtime.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21843

please please _please_ use the search button!!
