### ISSUE TITLE
Built in tablet driver size detection

### ISSUE THREAD

**Issue by Hunnus** [ppy/osu#21888]
### Type

Runtime error

### Bug description

The built in driver can't detect the correct size of some XP pen tablets like Deco 1 v2.

### Version

2022.1227.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10314452/database.log)
[input.log](https://github.com/ppy/osu/files/10314453/input.log)
[network.log](https://github.com/ppy/osu/files/10314457/network.log)
[performance.log](https://github.com/ppy/osu/files/10314458/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10314459/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10314460/updater.log)

**Comment by bdach** [comment]
Please report this over at https://github.com/OpenTabletDriver/OpenTabletDriver. We don't do any custom detection on our side other than what OTD provides.

**Comment by tujh2** [comment]
fixed by https://github.com/OpenTabletDriver/OpenTabletDriver/pull/4293

so the version needs to be upgraded (when it will be released)
