### ISSUE TITLE
Judgement animation mismatch between osu!(stable) and osu!(lazer)

### ISSUE THREAD

**Issue by 0x84f** [ppy/osu#21892]
### Type

Cosmetic

### Bug description

When playing maps it felt really jarring whenever I didn't hit a note perfectly, when looking at it frame by frame in Sony Vegas I realized the judgement in lazer (left side) "bounces" one more time than in stable (right side), making gameplay feel really jarring.
I only tested this for the osu! game mode, but I assume it's the same for other modes as well

### Screenshots or videos

https://user-images.githubusercontent.com/24534022/209846819-c5bb9863-cc3c-466a-9871-3dfe91a3d312.mp4

### Version

2022.1228.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10315398/database.log)
[input.log](https://github.com/ppy/osu/files/10315399/input.log)
[network.log](https://github.com/ppy/osu/files/10315400/network.log)
[performance.log](https://github.com/ppy/osu/files/10315401/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10315402/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10315403/updater.log)

**Comment by bdach** [comment]
This logic probably needs crosschecking / re-evaluating against stable again.

https://github.com/ppy/osu/blob/b35e796d75153b53c1e450f407a48032aef1eddf/osu.Game/Skinning/LegacyJudgementPieceOld.cs#L67-L72

**Comment by peppy** [comment]
@0x84f could you please attach your skin for reference? There may be animation frames or a version discrepancy causing the issue.

**Comment by 0x84f** [comment]
[skin.zip](https://github.com/ppy/osu/files/10395812/skin.zip)

**Comment by peppy** [comment]
Congratulations on being the first person to share a skin where the skin isn't stupid and 150mb and contains 1023958 animation frames.
