### ISSUE TITLE
System cursor shows up when moving cursor to top of game

### ISSUE THREAD

**Issue by JacksonChen666** [ppy/osu#21890]
### Type

Cosmetic

### Bug description

When the cursor is moved to the toolbar (or the top of the game), the system cursor (macOS's cursor) shows up with also osu!'s cursor.

Screen mode: borderless
OS: macOS 13.1
Screen resolution (major factor, somehow): 1920x1080 (with HIDPI, so actual resolution is 3840x2160. also known as "Default" resolution in macOS settings using a 4k monitor, see video for further details)

### Screenshots or videos

![](https://user-images.githubusercontent.com/50755746/209824785-494f7321-9c13-41cc-8d66-1a5134548cea.jpeg)

https://user-images.githubusercontent.com/50755746/209826002-88a619ef-7494-4bb9-87cd-304fb0a194f1.mp4

### Version

2022.1227.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10314568/database.log)
[input.log](https://github.com/ppy/osu/files/10314569/input.log)
[network.log](https://github.com/ppy/osu/files/10314570/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/10314571/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10314572/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10314574/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10314575/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/10314576/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10314577/runtime.log)

**Comment by JacksonChen666** [comment]
can't reproduce on 2022.1228.0-lazer

**Comment by frenzibyte** [comment]
There's nothing notable in 2022.1228.0 to confirm that this issue has been fixed. Are you sure you can't reproduce this? If so, it might be best closing this for now as I can't reproduce at all anyway.

**Comment by JacksonChen666** [comment]
still can't reproduce on 2022.1228.0-lazer, though it happened once again with no obvious cause (during osu!catch gameplay, not exactly sure).
