### ISSUE TITLE
Osu! windows volume resets after every update

### ISSUE THREAD

**Issue by Awesomerp** [ppy/osu#21893]
### Type

Crash to desktop

### Bug description

After every update the windows volume is reset to the maximum value. For example, my overall windows volume is 20 but I use Osu! at only 2. After every lazer update this is reset back to the maximum value and I need to change it again. Small bug but as a casual user it's little things like this that I enjoy being fixed. 

### Screenshots or videos

![](https://gyazo.com/fdc8f12a86465f44867c332f474afff9.png)

^ Resets to the maximum value after each update.

### Version

2022.1228.0-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/10315471/updater.log)
[database.log](https://github.com/ppy/osu/files/10315472/database.log)
[network.log](https://github.com/ppy/osu/files/10315473/network.log)
[performance.log](https://github.com/ppy/osu/files/10315474/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10315475/runtime.log)

**Comment by bdach** [comment]
Not sure we can do anything about this... Can you not use in-game volume instead? That should persist between updates.

**Comment by frenzibyte** [comment]
As mentioned above, there's nothing to do on our side, and you can pretty much just set the in-game volume to 2%.

**Comment by peppy** [comment]
This is due to the way squirrel currently works. It will be resolved when we switch to the new version which doesn't change the folder name each time.
