### ISSUE TITLE
Beatmap links in chat don't open

### ISSUE THREAD

**Issue by r0xANDt0l** [ppy/osu#21900]
### Type

Game behaviour

### Bug description

When you click a link for an osu! beatmap on chat, it prompts to open a link, but when you do /np, it goes to the page in osu!direct

### Screenshots or videos

[Screencast from 2022-12-28 20-10-06.webm](https://user-images.githubusercontent.com/41841903/209861005-fc5b1e3e-85c8-4bef-a491-bd942ee5691f.webm)

### Version

2022.1227.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10316000/database.log)
[input.log](https://github.com/ppy/osu/files/10316001/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10316002/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10316003/network.log)
[performance.log](https://github.com/ppy/osu/files/10316004/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10316005/runtime.log)

**Comment by LittleEndu** [comment]
This is already fixed in 2022.1228.0. See https://github.com/ppy/osu/pull/21854
