### ISSUE TITLE
Hard link creation flow does not consider users changing `BeatmapDirectory` in stable

### ISSUE THREAD

**Issue by bdach** [ppy/osu#21904]
This check is not completely correct for beatmaps:

https://github.com/ppy/osu/blob/ea8beffa612016460a7df64736c7d9dbe61fd4f8/osu.Game/Database/LegacyImportManager.cs#L64-L67

For beatmaps, I believe it should be checking via `stableStorage.GetSongStorage()` specifically, as that is not the same and can in particular lead to a different drive.

### Discussed in https://github.com/ppy/osu/discussions/21902

<div type='discussions-op-text'>

<sup>Originally posted by **hrfarmer** December 28, 2022</sup>
So I have my stable installation on my C drive, but in the .ini file I changed my songs folder to be on my D drive. Whenever I tried to import my maps in the setup wizard (with lazer being on my C drive as well), it still started duplicating all my beatmaps, which I cannot do because I will run out of storage. For now I'm just moving stable over to my D drive so I can do the hard link there, but I'm wondering if there is a fix for this.</div>

**Comment by peppy** [comment]
@LittleEndu can you confirm that you're taking this one on? else i'll add it to my list.

**Comment by LittleEndu** [comment]
I can try again taking into account what bdach and frenzy discussed with me, but your final comment in the PR left me confused. 

Lazer will already try to make hard links when possible, and would do so even if stable uses custom Songs directory. The issue here is that it's not made clear to the user during first-run setup, the message is flat out wrong most of the time.

**Comment by peppy** [comment]
The change that needs to be made is that the display on the first run setup should take into account the final location of the `Songs` folder, which it doesn't right now seemingly.

Scores / replays / skins can be ignored as they are relatively a small amount of data compared to beatmaps.

Does that make things clearer?
