### ISSUE TITLE
PP scores between website and the game

### ISSUE THREAD

**Issue by victorvaz2** [ppy/osu#21923]
### Type

Game behaviour

### Bug description

The website says it was a 89pp play, while the game itself says its 107.

### Screenshots or videos

Game:
![image](https://user-images.githubusercontent.com/15064122/209953636-35c037c1-1141-4c9e-8862-5e263d27f2b2.png)

lazer.ppy.sh:
![image](https://user-images.githubusercontent.com/15064122/209953657-9f51e486-90ec-4b33-9d77-50f4d598fa63.png)

### Version

2022.1228.0

### Logs

[database.log](https://github.com/ppy/osu/files/10319540/database.log)
[input.log](https://github.com/ppy/osu/files/10319541/input.log)
[network.log](https://github.com/ppy/osu/files/10319542/network.log)
[performance.log](https://github.com/ppy/osu/files/10319543/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10319544/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10319545/updater.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21815
