### ISSUE TITLE
Osu!mania. Sliders aren't displayed in some skins

### ISSUE THREAD

**Issue by spl3g** [ppy/osu#21936]
### Type

Game behaviour

### Bug description

in some skins, for example in One diamond, sliders are not shown

### Screenshots or videos

![image](https://user-images.githubusercontent.com/58591608/210014110-270743c2-21b1-4ddf-9cef-e553242915f7.png)
![image](https://user-images.githubusercontent.com/58591608/210014213-f760e64e-0167-4c8e-9d12-ad2ec860e864.png)

### Version

2022.1228.0

### Logs

[database.log](https://github.com/ppy/osu/files/10322264/database.log)
[input.log](https://github.com/ppy/osu/files/10322265/input.log)
[network.log](https://github.com/ppy/osu/files/10322266/network.log)
[performance.log](https://github.com/ppy/osu/files/10322267/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10322268/runtime.log)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/12057
