### ISSUE TITLE
Notes dissapear upon SV change in mania with Wind Up mode

### ISSUE THREAD

**Issue by Kwolium** [ppy/osu#21930]
### Type

Game behaviour

### Bug description

When playing 4k mania with Wind Up mode, some notes may dissappear and reappear in the leftmost column upon hitting SV change. This doesn't happen on other keys or Wind Down. It also appears on other skins.

### Screenshots or videos

https://user-images.githubusercontent.com/72566596/209992395-2e3de6ef-d46d-45c7-8f65-b61f479cf63d.mp4

https://user-images.githubusercontent.com/72566596/209992419-f5d7e825-9d61-4de3-8c23-fc7c3c47b705.mp4

### Version

2022.1227.0

### Logs

No need

**Comment by bdach** [comment]
Can you link an example of a map that this happens on?

**Comment by Kwolium** [comment]
> Can you link an example of a map that this happens on?

https://osu.ppy.sh/beatmapsets/555076#mania/1174927
https://osu.ppy.sh/beatmapsets/1878528#mania/3895702

these two from the videos
