### ISSUE TITLE
Possible to place notes out of bound in taiko, catch and mania editor.

### ISSUE THREAD

**Issue by Trung0246** [ppy/osu#21944]
### Type

Game behaviour

### Bug description

Probably doesn't need explaination.

### Screenshots or videos

https://user-images.githubusercontent.com/11626920/210063744-34449712-e4f0-4bf4-b3fb-2b7a8e5df6db.mp4

### Version

2022.1228.0

### Logs

[database.log](https://github.com/ppy/osu/files/10324379/database.log)
[input.log](https://github.com/ppy/osu/files/10324380/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10324381/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10324382/network.log)
[performance.log](https://github.com/ppy/osu/files/10324383/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/10324384/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10324385/performance-draw.log)
[runtime.log](https://github.com/ppy/osu/files/10324402/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10324403/updater.log)
[performance-input.log](https://github.com/ppy/osu/files/10324386/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10324388/performance-update.log)

**Comment by Trung0246** [comment]
Looks like it goes the same for taiko.

https://user-images.githubusercontent.com/11626920/210065744-20c44c18-255f-4b30-97d6-063254262391.mp4

And catch. Absolutely weird bug.

https://user-images.githubusercontent.com/11626920/210065887-fc85ec1d-15e1-4adc-a52a-186a226ec163.mp4

**Comment by ekrctb** [comment]
It is half-intended for catch because why not (bigger useful area).
