### ISSUE TITLE
`BeatmapAttributeText` are not affected by mods

### ISSUE THREAD

**Issue by Sclafus** [ppy/osu#21946]
### Type

Cosmetic

### Bug description

As you can see from the screenshot below, `BeatmapAttributeText`s display missmatched information when adding a difficulty increasing mod. In the screenshot you can see the missmatch with AR, CS and OD.
It may be intended. 
I'm not giving attaching logs since I am importing beatmaps and they are ~20MB.

### Screenshots or videos

![osu_2022-12-30_14-52-00](https://user-images.githubusercontent.com/31241607/210077550-f69aa33f-c02c-4d6c-8266-a2b8ed690c72.jpg)

### Version

2022.1228.0-lazer

### Logs

-

**Comment by peppy** [comment]
This can't be as hard to fix as it has been made to look in the last attempted PR.

**Comment by Toasterly** [comment]
Still experiencing this after a year. Any fix coming soon?

This is not only for difficulty increasing mods btw, the star rating value is only showing the original star rating.

**Comment by Joehuu** [comment]
Implemented in https://github.com/ppy/osu/pull/30321.
