### ISSUE TITLE
Combo colors are forced on legacy skins that don't support them

### ISSUE THREAD

**Issue by kiwec** [ppy/osu#21956]
### Type

Cosmetic

### Bug description

Stable skins that have the following in skin.ini:
```
[Colours]
Combo1: 255,255,255
Combo2: 255,255,255
Combo3: 255,255,255
Combo4: 255,255,255
```

Should not get colored based on the map, but still are. Also affects approach circles.

Expected: skins imported from stable should look the same in lazer

### Version

2022.1228.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/10326216/runtime.log)
[performance.log](https://github.com/ppy/osu/files/10326217/performance.log)
[network.log](https://github.com/ppy/osu/files/10326218/network.log)
[input.log](https://github.com/ppy/osu/files/10326219/input.log)
[database.log](https://github.com/ppy/osu/files/10326220/database.log)

**Comment by bdach** [comment]
Are you sure you're not confused and you don't just have beatmap skins off in stable? I just checked on a user skin with what you pasted in `skin.ini` and as long as beatmap skins are on the beatmap combo colours are not ignored.

**Comment by kiwec** [comment]
> Are you sure you're not confused and you don't just have beatmap skins off in stable? I just checked on a user skin with what you pasted in `skin.ini` and as long as beatmap skins are on the beatmap combo colours are not ignored.

Right, that was it. I just didn't find the setting in lazer's settings menu when searching for it the first 3 times.

**Comment by peppy** [comment]
To help us improve usability, what did you search for the first three times? We can potentially add more keywords or changes things around to improve discoverability.

**Comment by kiwec** [comment]
`combo color` / `beatmap skin` (that second one showed up, but in a grayed out area I misinterpreted as "not relevant")

Another thing that tripped me up was that the setting wasn't in the "Skin" category but in "Gameplay".

The relevant setting was "beatmap colours", I already had beatmap skins disabled.
