### ISSUE TITLE
Mouse cursor displayed during multiplayer loading screen

### ISSUE THREAD

**Issue by kiwec** [ppy/osu#21957]
### Type

Cosmetic

### Bug description

The "UI" mouse cursor is displayed during the loading screen, while the gameplay area is visible.

That small period before the song is useful to "calibrate" your aim by moving your cursor around, but since it's the "UI" mouse it doesn't feel right (no trail, it's spinning around after you stopped moving, etc)

Expected: see the gameplay cursor ball instead (with trail)

### Version

2022.1228.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/10326229/runtime.log)
[performance.log](https://github.com/ppy/osu/files/10326230/performance.log)
[network.log](https://github.com/ppy/osu/files/10326231/network.log)
[input.log](https://github.com/ppy/osu/files/10326232/input.log)
[database.log](https://github.com/ppy/osu/files/10326233/database.log)

**Comment by bdach** [comment]
Opening a bug report rather than a discussion about this is a stretch but alright.

**Comment by peppy** [comment]
This is as-expected for now as all players have the same time to start the match.
