### ISSUE TITLE
Android Download issue

### ISSUE THREAD

**Issue by Yoru-Kitsune** [ppy/osu#21969]
### Type

Other

### Bug description

When I try to update the existing app there is a package conflict

### Screenshots or videos

![Screenshot_20221231_092132_Package installer](https://user-images.githubusercontent.com/108625654/210130524-b754fedf-47c7-46dc-89ba-b1790f0941c7.png)

### Version

2022.1228.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/10327082/logs.zip)

**Comment by peppy** [comment]
We're working on fixing the certificate of the download. Please try again in a day or two.

**Comment by peppy** [comment]
As an update this should now be resolved.
