### ISSUE TITLE
Beatmap listing difficulty dropdown is hoverable for too long after cursor exit

### ISSUE THREAD

**Issue by yamplum** [ppy/osu#21962]
### Type

Cosmetic

### Bug description

The difficulty dropdown list in the beatmap listing stays hoverable for a little too long after moving the cursor out, keeping it active after it visually disappears and preventing interaction with the card below.

Priority: annoyance
Keywords searched: beatmap listing, difficulty, hover

### Screenshots or videos

https://user-images.githubusercontent.com/118788705/210121159-248e584f-7184-4374-b456-f009699c5be4.mp4

### Version

2022.1228.0

### Logs

[input.log](https://github.com/ppy/osu/files/10326687/input.log)
[network.log](https://github.com/ppy/osu/files/10326688/network.log)
[performance.log](https://github.com/ppy/osu/files/10326689/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10326690/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10326691/updater.log)
[database.log](https://github.com/ppy/osu/files/10326692/database.log)

**Comment by bdach** [comment]
The timings should be the exact same as on the website. Is this not a problem there too for you? The delay is only 100ms.

**Comment by frenzibyte** [comment]
Web doesn't seem to have the same behaviour:

https://user-images.githubusercontent.com/22781491/210127440-b61e0dda-176d-47b4-ba23-7c465fa9cfc4.mp4

Whereas in lazer:

https://user-images.githubusercontent.com/22781491/210127408-6d214ea8-3471-45bd-9f99-6aecc8e4ddc3.mp4
