### ISSUE TITLE
osu!mania maps with a lot of timing points take way too long to load

### ISSUE THREAD

**Issue by Kori3** [ppy/osu#21960]
### Type

Game behaviour

### Bug description

Idk if this only applies to mania maps, but I don't know about any other mode beatmaps that have a lot of timing points to test this. I tried with multigenre smackdown in taiko and i didn't have any issues while loading
Also, when several of these timing points are present at the same time, the framerate drops by a lot.
Its probably not just my device where this issue is present.
And this doesn't apply for effect points, probably because the game doesn't have to render extra barlines during gameplay
Some beatmaps that share the same issue:
https://osu.ppy.sh/beatmapsets/1869945#mania/3847430 (sv difficulty)
https://osu.ppy.sh/beatmapsets/1134062#mania/2658817 (evil difficulty)
https://osu.ppy.sh/beatmapsets/596105#mania/1274057 (A lie's asgard difficulty)
https://osu.ppy.sh/beatmapsets/1160847#mania/2591542

### Screenshots or videos

Lazer video:

https://user-images.githubusercontent.com/70714793/210117833-0e694c36-4492-4902-9fdf-40d76c41fe59.mp4

Stable video (for comparison):

https://user-images.githubusercontent.com/70714793/210117848-c7ba8822-2fc7-433b-9c2f-0d7cf0a73267.mp4

### Version

2022.1828.0

### Logs

[performance.log](https://github.com/ppy/osu/files/10326519/performance.log)
[updater.log](https://github.com/ppy/osu/files/10326520/updater.log)
[input.log](https://github.com/ppy/osu/files/10326521/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10326522/legacy-ipc.log)
[runtime.log](https://github.com/ppy/osu/files/10326523/runtime.log)
[network.log](https://github.com/ppy/osu/files/10326524/network.log)
[database.log](https://github.com/ppy/osu/files/10326525/database.log)
Probably not necessary, but still

**Comment by bdach** [comment]
Let's track at #20918 since it's pretty much the same thing.
