### ISSUE TITLE
Beatmap listing is broken

### ISSUE THREAD

**Issue by swrast** [ppy/osu#21982]
### Type

Game behaviour

### Bug description

Results of searching maps in osu!lazer and website with equal tags are not the same.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/115649270/210166352-b7d5fa71-6f81-49c8-9362-e2b9979273ac.png)
![osu_2022-12-31_18-20-36](https://user-images.githubusercontent.com/115649270/210166377-1f5d3887-094d-41d3-bc72-8acd2a16ac8a.jpg)

### Version

2022.1228.0

### Logs

[database.log](https://github.com/ppy/osu/files/10328560/database.log)
[input.log](https://github.com/ppy/osu/files/10328561/input.log)
[network.log](https://github.com/ppy/osu/files/10328562/network.log)
[performance.log](https://github.com/ppy/osu/files/10328563/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10328564/runtime.log)

**Comment by peppy** [comment]
You need to disable the featured artist filter if you want to see potentially unlicensed content.
