### ISSUE TITLE
Metronome skips new timing point if it longs less than a 1/1 beat 

### ISSUE THREAD

**Issue by Dopaminos** [ppy/osu#21988]
### Type

Game behaviour

### Bug description

Map tested: https://osu.ppy.sh/beatmaps/795140
In combo with https://github.com/ppy/osu/discussions/21494 and https://github.com/ppy/osu/issues/21947, claiming lazer is "unusable for timing" is pretty valid imo

### Screenshots or videos

[_No response_
](https://user-images.githubusercontent.com/42616718/210182384-2aa9043d-d882-423d-9725-e79ffe0d36d3.mp4)
### Version

20221228

### Logs

no need in logs

**Comment by bdach** [comment]
we'll address this but

> claiming lazer is "unusable for timing" is pretty valid imo

can we leave out these sorts of statements? they're not productive. this isn't twitter, there's no need for this sort of language. sticking to the facts of the matter is best.

**Comment by snalgae** [comment]
doesn't look like it's an issue anymore, should be closed
https://github.com/ppy/osu/assets/104220939/b861182b-6a1a-4be1-b9bd-d03b6828638a

**Comment by Joehuu** [comment]
Yep, confirmed fixed by https://github.com/ppy/osu/pull/25316.
