### ISSUE TITLE
"Argon" cursor colour conflicts with slider ball

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#21986]
That feels quite bad. I feel at the very least the cursor should change its colour to white (and border to black) when interacting with a slider.

### Discussed in https://github.com/ppy/osu/discussions/21880

<div type='discussions-op-text'>

<sup>Originally posted by **Kaerulans** December 28, 2022</sup>
I constantly lose track of my cursor during sliders when using argon because both the slider ball and the cursor are red. I feel like one of them should have its color changed to avoid this.

![Screenshot from 2022-12-28 13-25-11](https://user-images.githubusercontent.com/55179197/209797771-2c10fc8d-5365-44e0-a3f1-07b6530095c8.png)</div>

**Comment by peppy** [comment]
The better solution is to make the ball match the slider

**Comment by frenzibyte** [comment]
As in tint the ball to the slider's combo colour? I've thought about that but felt someone may then propose a setting for it given that one already existed for it in stable at a skin level and a game level. Probably a better solution for the time being anyway.

**Comment by peppy** [comment]
Yeah. I think based on feedback it may be fine to make it the default for now. I'm not sure I want to introduce another highlight colour to the skin apart from the pink.
