### ISSUE TITLE
Appearance of featured artist filter in beatmap listing overlay is too subtle when enabled

### ISSUE THREAD

**Issue by bdach** [ppy/osu#22009]
### Type

Cosmetic

### Bug description

Leading to [several](https://github.com/ppy/osu/issues/21982) [issue](https://github.com/ppy/osu/issues/21990) [reports](https://github.com/ppy/osu/issues/22008) that the overlay is returning incorrect results. Which it isn't, but we probably can do a better job at conveying it than it is done currently. The difference between the filter being enabled and disabled is just font weight.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/20418176/210278613-1f607b49-6491-4905-948d-e49046860701.png)

Top 2 lines: featured artist filter on/off. Bottom 2 lines: any other filter on/off. Side by side this appears to be more obvious, but in isolation it can be difficult to tell the difference.

### Version

current master

### Logs

-

**Comment by peppy** [comment]
I've been meaning to open an issue for this. It's very bad design as it exists right now, because it uses a different colour to the normal highlight colour it doesn't even look like it's selected, but just highlighted.

@arflyte please advise

**Comment by bdach** [comment]
For whatever it's worth [this is a design that exists](https://www.figma.com/file/bONtBvDRWNfOuiYpueD2ms/Web%2FSearch-Result-(with-Beatmap-Listing)?node-id=1%3A160&t=d6B0kD4IXfCYfR9D-4). No idea at what stage of usability it is, but it's there.

It predates the featured artist filter but it has the green dots next to things to signal enabled state. Probably not a very good short-term solution if we want to avoid redesigning the entire search control though.

**Comment by CX13BVA** [comment]
> Leading to [several](https://github.com/ppy/osu/issues/21982) [issue](https://github.com/ppy/osu/issues/21990) [reports](https://github.com/ppy/osu/issues/22008) that the overlay is returning incorrect results. Which it isn't,

I was literally about to open an issue regarding ["returning incorrect results"](http://puu.sh/JvTwZ/801e5ce3ae.jpg), good thing I checked with Death first to confirm it's not just on my end.
The "Featured artist" filter has almost zero visual difference between being enabled/disabled on my screen :/

**Comment by peppy** [comment]
That design doesn't make much sense based on how the tabs are arranged. "Featured artist" should be a filter on beatmap rather than a top level tab, unless that's intended for browsing the featured artist pages themselves (not implmented in game yet)?

**Comment by bdach** [comment]
Yeah I did not pay too much attention to the header on that design there. The filter control was more the point.

**Comment by janneslessmann** [comment]
Maybe it would help, to display a little "X" button besides the "Featured artists" filter?

**Comment by mcendu** [comment]
Probably make the text white when selected as with other text.

**Comment by gutyina70** [comment]
I'd love to see a "Don't show again" button when turning off featured artist filter.

**Comment by frenzibyte** [comment]
Turns out I had opened a duplicate issue thread for this. I'll just copy what I wrote in the other thread:
> This happened to me a handful of times after not launching osu!(lazer) for a short period of time, and has also just been [encountered by a user](https://discord.com/channels/188630481301012481/1097318920991559880/1157753736513474691) recently. Opening this issue thread to raise a bit of discussion before osu!(lazer) becomes ranked and many stable players switch to lazer (not sure if it deserves being included in the project though).
>
> Part of this confusion likely rises from the fact that the osu! website does not enable the "featured artists" filter in beatmap listing by default. But I'm not sure if the website will have it enabled by default any time soon.
>
> I'm not sure how much of noting is acceptable, but would maybe adding a line strip at the top of the search results stating that this is searching for beatmaps with the "featured artist" filter enabled? Or at the very least, maybe bring the filter to the right side of the search bar in some shape or form, e.g.:
> 
> <img width="1005" alt="CleanShot 2023-09-30 at 22 21 22@2x" src="https://github.com/ppy/osu/assets/22781491/36da2269-d8a8-46f5-adb8-8a87b5510006">

@peppy thoughts on whether this should be addressed before lazer becomes "ranked"? since I believe by then many people would switch to lazer and would likely be confused when they can't search for their beatmaps due to being filtered out by the "Featured Artists" filter.

**Comment by Tanza3D** [comment]
Might be worth considering adding something underneath search results warning about it when none of the results match the query directly? Like so:
![image](https://github.com/ppy/osu/assets/33783503/e63e83d2-47fe-4e6e-a0be-443bdceb8dea)
Would allow for there to be no warning when the user's searching for featured artist maps, and for it not to get too in the way when their search isn't successful. Would need some experimentation to figure out when best to display it though, I'd say when the song name, artist name, or mapper name don't match on *any* of the maps returned.

**Comment by bdach** [comment]
That looks potentially okay, but I'm not sure that particular design will work when there are zero results displayed. It'd probably have to replace the "... nope, nothing found" placeholder entirely. Or supplement it somehow.

**Comment by Tanza3D** [comment]
![image](https://github.com/ppy/osu/assets/33783503/4c44795d-139f-451f-b5f7-64fe282b5514)
Could possibly just append the message to the text like this? I personally feel like the no results found ui could do with a redesign in general, doesn't fit in too well with the UI in my opinion, but for now this would probably work.

**Comment by peppy** [comment]
While you're there maybe you could check out the song select placeholder we have (design done by me, nothing special) and update it to be in line with what we display here ;).

**Comment by Tanza3D** [comment]
Hmm which one, when there's no search results in song select? or something else?

**Comment by peppy** [comment]
Yep, it has a few different modes of display:


https://github.com/ppy/osu/assets/191335/5231ac76-cfde-4000-9a5f-4481dd7ccfe6

**Comment by Tanza3D** [comment]
Would it be viable to redesign the beatmap one completely to be reusable across multiple areas (including song select)? I feel that might be a good way forward. The image on the beatmap one doesn't fit too well in lazer's design language in my opinion, and especially would look out of place in song select.

**Comment by Tanza3D** [comment]
Something like this:
![image](https://github.com/ppy/osu/assets/33783503/e482e277-4744-47b7-8f3f-d0bc8a577530)
Unsure about the icon though

**Comment by bdach** [comment]
Looks somewhat okay to me, although some of the text alignment here looks off (I'd argue the bullet list needs to be indented more).

One other question I'd have is what to do when there's no actual results and no real good hint to give, I guess then you'd just keep the heading and skip the bullet list?

**Comment by peppy** [comment]
I'm not a huge fan on the proposed design. I'm hoping it can be something that feels nice, like the blank-expression-pippi, and meld a bit better than a mundane corner radius box.

**Comment by Tanza3D** [comment]
> One other question I'd have is what to do when there's no actual results and no real good hint to give, I guess then you'd just keep the heading and skip the bullet list?

Yep, can just have the text



> I'm not a huge fan on the proposed design. I'm hoping it can be something that feels nice, like the blank-expression-pippi, and meld a bit better than a mundane corner radius box.

I really feel the pippi is out of place and kind of jarring compared to the rest of the UI, though I'll try think up some other concepts. I think it'll be best to come up with something which can be used continually into the future in other UIs, including the multiplayer screen (which at the moment just shows a blank screen when there's no results)

**Comment by Joehuu** [comment]
Can we reuse the existing outdated country filter UI for this?

![Screenshot 2024-03-22 at 11 42 28 PM](https://github.com/ppy/osu/assets/35318437/6457c1a5-ed1f-49bf-bfd8-376cff609999)

and show `filtered by: ( Featured Artist X ) ( Ranked X ) ( ETC X )`

This UI is similar to https://github.com/ppy/osu-web/issues/7372#issuecomment-1047485245 (just found this out while writing this).

Note that web uses a dropdown for the country now, but the above is better suited for the beatmap listing as there are multiple filters.

**Comment by bdach** [comment]
"Putting this out of limbo" is going to require someone to make a shotcall on the design part. I don't even know who at this point.

**Comment by frenzibyte** [comment]
@arflyte able to advise on design for https://github.com/ppy/osu/issues/22009#issuecomment-2016380074? we want to add a "filtered by" row in the beatmap listing page to make it clear to the user what filters they have active (see also https://github.com/ppy/osu-web/issues/7372#issuecomment-1047485245)

**Comment by peppy** [comment]
> Saw a reddit post about this again so trying to put this out of limbo.
> 
> Can we reuse the existing outdated country filter UI for this?
> 
> ![Screenshot 2024-03-22 at 11 42 28 PM](https://private-user-images.githubusercontent.com/35318437/316222805-6457c1a5-ed1f-49bf-bfd8-376cff609999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTE4MTMsIm5iZiI6MTcxNjgxMTUxMywicGF0aCI6Ii8zNTMxODQzNy8zMTYyMjI4MDUtNjQ1N2MxYTUtZWQxZi00OWJmLWJmZDgtMzc2Y2ZmNjA5OTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEyMDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZmQ2OGFiZGIzZjc4N2M0ZWNjOWRiNWM5ZTIzNzhhNTI3NzNiNGRhODc2YzUxYWNhNTJkMDQxNDgwYjdiOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.180vRbtgMYZVRrZQrBsL5yCpaCwCtceT4SW7ky_52JE)
> 
> and show `filtered by: ( Featured Artist X ) ( Ranked X ) ( ETC X )`
> 
> This UI is similar to [ppy/osu-web#7372 (comment)](https://github.com/ppy/osu-web/issues/7372#issuecomment-1047485245) (just found this out while writing this).
> 
> Note that web uses a dropdown for the country now, so the above can be made abstract / repurposed for the beatmap listing as there are multiple filters.
> 
> Edit: And probably make pippi say "... nope, nothing found. maybe try removing the filter(s) above?" when there's no results. Otherwise the "filtered by" row should be obvious to the eye.

both of these sound fine. we don't need a non-responsive designer to move forward with this IMO.

**Comment by frenzibyte** [comment]
Taking out of `waiting-on-design` label in compliance with the above (i.e. this is ready to be tackled).
