### ISSUE TITLE
[Bug?] Weird timestamp 

### ISSUE THREAD

**Issue by Hexality** [ppy/osu#22021]
### Type

Cosmetic

### Bug description

score timestamps on the playlist ranking appears with weird date/time.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/17398632/210424508-79d14cd9-45f3-4f3c-89ca-1a4a4d8b4a17.png)

### Version

2022.1228.0

### Logs

[database.log](https://github.com/ppy/osu/files/10339142/database.log)
[input.log](https://github.com/ppy/osu/files/10339143/input.log)
[network.log](https://github.com/ppy/osu/files/10339144/network.log)
[performance.log](https://github.com/ppy/osu/files/10339145/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10339146/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10339147/updater.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/19292

**Comment by Hexality** [comment]
mb, search didn't show anything
