### ISSUE TITLE
Changing SS in osu!mania scorev2 to be all 300s or above

### ISSUE THREAD

**Issue by zkldi** [ppy/osu#2202]
rather than all 300gs

This was how it was in scorev1 and it is generally much better for players as getting all 300gs is near-impossible even for the best of acc players on anything beyond 3*. SS as being all 300s/300gs is significantly more useful as a player metric (at a quick glance) to tell whether a player has got an amazing acc score on a chart.

Also, in tournaments it's still widely referred as an SS (or, v1SS) as it is simply a more useful metric.

Apologies, I originally posted this in osu-web by accident; it should have been in here.

**Comment by AlFasGD** [comment]
SS is already quite hard to achieve and it originally refers to having 100% accuracy (which is achieved through getting only 300s and above). As for only 300gs (or MAXs as originally referred to in osu!stable) there could be another rank like SSS or something.

**Comment by peppy** [comment]
This is how it is now. for now.
