### ISSUE TITLE
File type assosiation and importing issues

### ISSUE THREAD

**Issue by cheeezie** [ppy/osu#22039]
### Type

Game behaviour

### Bug description

After installing osu!lazer for the first time on a Windows 11 machine, the file type didn't associate with osu! at all, but even after trying to open the file using the "Open With" context menu option in Windows Explorer, selecting the osu executable as well. The file didn't import. The only way to import said file is it is to drag and drop it into the osu! window (shown in the screen recording).

### Screenshots or videos

Screen Recording:
https://user-images.githubusercontent.com/102518950/210865978-c6736820-10e3-433e-87cc-af4ace8438a8.mp4

### Version

2022.1228.0-lazer

### Logs

Taken after trying to open using Explorer and the drag and drop of the file.
[database.log](https://github.com/ppy/osu/files/10355210/database.log)
[input.log](https://github.com/ppy/osu/files/10355211/input.log)
[network.log](https://github.com/ppy/osu/files/10355212/network.log)
[performance.log](https://github.com/ppy/osu/files/10355213/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10355214/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10355215/updater.log)

**Comment by cheeezie** [comment]
This issue hasn't affected me in older versions of Windows, nor any other Linux distro. Only Windows 11.

**Comment by peppy** [comment]
File associations are not implemented yet. See https://github.com/ppy/osu/issues/14824
