### ISSUE TITLE
Dashboard show same friends multiple times

### ISSUE THREAD

**Issue by kelinimo** [ppy/osu#22036]
### Type

Other

### Bug description

Dashboard shows every friend three times and as shown in the video the time active can be different for all of them

### Screenshots or videos

https://user-images.githubusercontent.com/98035959/210809553-31cf6a5c-92cd-4ba0-ab16-aa618da0c08b.mp4

### Version

2022.1228.0

### Logs

[performance.log](https://github.com/ppy/osu/files/10353033/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/10353034/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10353035/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10353036/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10353037/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10353038/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10353040/updater.log)
[database.log](https://github.com/ppy/osu/files/10353041/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10353042/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10353044/network.log)

**Comment by frenzibyte** [comment]
Can you reliably reproduce this bug? Does osu!web display the friends list correctly?

**Comment by kelinimo** [comment]
i'm not sure about a reliable way, but it happens consistently after running for more than 1 day. This can be related to the time cuz in the video lazer ran for 2 days and it showed every friend three times, today it ran for 1 day and shows them 2 times

**Comment by frenzibyte** [comment]
Right, I can reproduce this by disconnecting from internet until the game reaches a `Failing` state, then connect back again.
