### ISSUE TITLE
PC suddenly crash due to lazer lack of memory(4GB RAM)

### ISSUE THREAD

**Issue by stevenkiethanete** [ppy/osu#22071]
when i open lazer i runs normal but i click osu! logo the pc crashed
### because csrss.exe triggered to terminate

memory cache might be the problem

i dont have photo or video because my phone is blurry

i have second one on #22070

**Comment by peppy** [comment]
One thread is enough.

**Comment by stevenkiethanete** [comment]
ah ok

> One thread is enough.

so this is it
you hate 1k lol
