### ISSUE TITLE
Random Mod replaying scores older than a month incorrectly

### ISSUE THREAD

**Issue by Sunglas** [ppy/osu#22074]
### Type

Game behaviour

### Bug description

While watching a replay that is older than a month with the Random Mod, lazer will not play the map correctly.

It seems as if the circles aren't placed where they were originally. This seems to line up with the update that was released on december 7th. (specifically with this change #21544 involving the Random Mod) Additionally, when the HP reaches 0 the map keeps playing, which isn't a behavior I was expecting to happen.

### Screenshots or videos

https://user-images.githubusercontent.com/65361987/211203758-44538622-ed57-4968-82f6-c97921ad8ea0.mp4

### Version

2022.1228.0-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/10368727/input.log)
[database.log](https://github.com/ppy/osu/files/10368729/database.log)
[performance.log](https://github.com/ppy/osu/files/10368730/performance.log)
[network.log](https://github.com/ppy/osu/files/10368731/network.log)
[runtime.log](https://github.com/ppy/osu/files/10368734/runtime.log)

**Comment by bdach** [comment]
That is correct, we do not currently offer guarantees that historical random mod replays will work correctly. At some cutoff point we will probably start guaranteeing this once the mod has somewhat stabilised, but for now this is intentional until we introduce some sort of versioning scheme.
