### ISSUE TITLE
Score on the profile uses different mods compared to the one on the in-game leaderboard

### ISSUE THREAD

**Issue by MVPuccino** [ppy/osu#22075]
### Type

Game behaviour

### Bug description

osu! has submitted a score that on the in-game leader board uses the Relax and Difficulty Adjust mods (correct) while my profile's top plays show the same score as my using no mods (incorrect).

### Screenshots or videos

![Screenshot_20230108_185307](https://user-images.githubusercontent.com/85420241/211211347-e03a4841-35ec-48a7-b5ce-1e30f27eb8ed.png)
![Screenshot_20230108_185400](https://user-images.githubusercontent.com/85420241/211211349-2c2a83c7-6869-4a4e-87b7-10cc09bd0924.png)

### Version

2022.1228.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/10369109/network.log)
[runtime.log](https://github.com/ppy/osu/files/10369111/runtime.log)
[performance-audio.log](https://github.com/ppy/osu/files/10369112/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10369113/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10369114/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10369115/performance-update.log)
[database.log](https://github.com/ppy/osu/files/10369116/database.log)
[input.log](https://github.com/ppy/osu/files/10369117/input.log)
[performance.log](https://github.com/ppy/osu/files/10369118/performance.log)

**Comment by bdach** [comment]
> uses the Relax and Classic mods (correct)

Screenshot is showing Relax and Difficulty Adjust, though?

Also notably this score is 10 months old so whatever was causing this may well have already been fixed.

**Comment by MVPuccino** [comment]
Sorry, I thought it was Classic mod, my bad.

**Comment by peppy** [comment]
Scores will be purged at some point. Non-issue.
