### ISSUE TITLE
Change multiplayer to not require "ready" state to join match start

### ISSUE THREAD

**Issue by peppy** [ppy/osu#22090]
Originally we decided to make it a requirement to hit "ready" to join a match, but these days I feel this is very anti-user and can cause users to miss a match they intended to play in. It's also different to how stable works which can add to the confusion.

Users which don't wish to join gameplay can now hit the "spectate" button which covers that case quite well.

### Discussed in https://github.com/ppy/osu/discussions/21966

<div type='discussions-op-text'>

<sup>Originally posted by **yamplum** December 31, 2022</sup>
In multiplayer, if the host starts the game and a player did not click the "Ready" button, that player will be dropped into the spectator pool and will not get to play.

This seems unnecessarily punishing on new and old players alike as it's quite easy to forget to ready up. Personally, I often tab out of the game while waiting on the lobby and tab back in when I hear the song starting; if I didn't ready up, I will likely not notice until it's too late.

For hosts, an additional trip-up point is being able to start a game without readying up yourself via countdown.

The only benefit of the ready state seems to be indicating to the host that the player is not AFK. Since players do not interact with each other, there is no harm to the rest of the lobby in an AFK player joining the game.

Perhaps it would be more intuitive to let all players in the lobby join the game by default and only move them to spectators if explicitly requested?</div>

**Comment by smoogipoo** [comment]
Resolved in https://github.com/ppy/osu-server-spectator/pull/170
