### ISSUE TITLE
WheelDelta handling is probably wrong game-wide

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2210]
We make assumptions about `> 0` being just one wheel action, where we should probably be considering the magnitude of the number. Have to check across platforms what the number means (is `1` equal to one wheel tick?).

**Comment by FreezyLemon** [comment]
On windows, the wheel delta is exactly the amount of wheel "ticks".
See [OpenTK's implementation](https://github.com/opentk/opentk/blob/b08acb758a940319c664de2799b0d7509e528efa/src/OpenTK/Platform/Windows/WinRawMouse.cs#L234) (take the raw data and divide by 120).

From the [windows API docs](https://msdn.microsoft.com/de-de/library/windows/desktop/ms645617(v=vs.85).aspx)
```
The high-order word indicates the distance the wheel is rotated, expressed in multiples or divisions of WHEEL_DELTA, which is 120.
A positive value indicates that the wheel was rotated forward, away from the user; a negative value indicates that the wheel was rotated backward, toward the user.
```

**Comment by bdach** [comment]
Pretty sure this is no longer relevant since merge of ppy/osu-framework#1658 (see ppy/osu-framework@3d6aad9 in particular); closing.
