### ISSUE TITLE
The behavior of the hitcircle is strange with sliders

### ISSUE THREAD

**Issue by dwarf17342** [ppy/osu#22121]
### Type

Cosmetic

### Bug description

If a slider is hit late or missed entirely the hitcircle, both hitcircle.png and hitcircleoverlay.png, only fade out once it's hit or missed. Since the sliderball is rendered on top of the hitcircle it can be hard to see. But, with many skins the sliderball is either smaller than the hitcircle or has transparency and you can see the hitcircle below and it makes the skin look very different from stable. The larger the judgment window the more obvious this is, with smaller judgment windows looking like a transition animation that only shows up when you're late. The behavior also changes depending on the mod combinations.
No mod the hitcircle moves with the sliderball at the same rate until the miss.
Classic mod the hitcircle starts to fade out once the sliderball shows up.
And in stable the hitcircle disappears instantly at the same time the sliderball shows up.

The triangles skin, and to a lesser extent argon, seem to actually make use of this to show when the hitcircle is still good to hit but I think this is part of why "sliders feel janky in lazer"

### Screenshots or videos

![durring judgment window](https://user-images.githubusercontent.com/105325426/211675392-157d02e5-a145-436e-a9e1-10156b5af63c.jpg)
![after missing](https://user-images.githubusercontent.com/105325426/211675396-0cda5cff-29db-4b7d-81a3-149ecdfd49f8.jpg)
![the white circle around the sliderball](https://user-images.githubusercontent.com/105325426/211678195-bbd13d61-ddd5-4da1-a0fa-34976bfe2d56.jpg)

https://user-images.githubusercontent.com/105325426/211677823-4f0b2b41-318f-4f9b-92cb-b6658674d368.mov

### Version

2022.1228.0

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/10387352/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10387353/network.log)
[performance.log](https://github.com/ppy/osu/files/10387354/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10387355/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10387356/updater.log)
[database.log](https://github.com/ppy/osu/files/10387357/database.log)
[input.log](https://github.com/ppy/osu/files/10387358/input.log)

**Comment by Cwazywierdo** [comment]
Classic mod doesn't seem to effect how the hit circle fades. The fact that the hit circle follows the slider ball is an intentional change, if that's what you're talking about. The fading is different between stable and lazer though.

https://user-images.githubusercontent.com/42323315/217135640-27170d76-23c2-4207-892e-257712e6c6d2.mp4
