### ISSUE TITLE
Automatic SV

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#2213]
This is the idea pretty much: 
![photoshop_2018-03-13_09-49-40](https://user-images.githubusercontent.com/35473621/37329230-95e2d808-26a5-11e8-9de7-e4dd8e9d87f7.png)

Quick slider velocity changes:
A small panel will be shown just like in the picture. It will allow for a quick manual SV changes.

Open lock:
User is able to change the size of the slider to what they want and SV would be automatically applied to that slider based on its size in the timeline and length in the editor.

Closed lock:
For consistent sliders, the mapper is able to close the lock to make the sliders the same size (Basically the same as you create sliders in the current version)

Every time the mapper creates a slider while the lock is open, a new inherited point would be created.

Once the mapper changed the SV in the panel, **on a new slider** an inherited point would be created.

I hope you understand. I'm not that good with explaining. (And English, sorry if I made any mistakes!)

**Comment by peppy** [comment]
The UI would not be as you proposed, but this will definitely be possible.

**Comment by RaiLTC** [comment]
Yeah I'm not a designer. But you get what I meant which is good.

Everytime I tried to map changing SV was really tiring, especially when I wanted custom SV (0,2x, 4x etc)

**Comment by peppy** [comment]
Going to close this in favour of https://github.com/ppy/osu/issues/7882, which is covering this flow.
