### ISSUE TITLE
Beatmap keeps asking to update even after updating/re-downloading

### ISSUE THREAD

**Issue by sigmadroid** [ppy/osu#22148]
### Type

Game behaviour

### Bug description

A ran into this beatmap that keeps showing the `Update` button even after you click on it and the map is supposedly updated.
I tried deleting the map (right click and delete) and download it again but is the same behavior.
I also tried restarting the game after updating the map but still showing the update button.

### Screenshots or videos

![osu_2023-01-11_19-39-51](https://user-images.githubusercontent.com/94931827/211955885-0f97a396-d3c8-4030-910f-c1fda2f14c08.jpg)

### Version

2022.1228.0

### Logs

[database.log](https://github.com/ppy/osu/files/10397391/database.log)
[input.log](https://github.com/ppy/osu/files/10397392/input.log)
[network.log](https://github.com/ppy/osu/files/10397393/network.log)
[performance.log](https://github.com/ppy/osu/files/10397394/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10397395/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10397396/updater.log)

**Comment by sigmadroid** [comment]
Is there a tool to compare different versions of a map? because unfortunately I think I didn't even play the map or maybe just once before trying to update it.

This happened also by deleting the map and downloading it again so if none else can reproduce I agree it is probably some visual bug (cached or something).

**Comment by Cootz** [comment]
![image](https://user-images.githubusercontent.com/50776304/234162430-d471b7ea-8af7-41e1-a83c-8bb97a53f45e.png)
I have the same issue. It's probably visual or server side bug (the beatmap is 14yo :/).

**Comment by Gyoshi** [comment]
I have the same issue with 2 maps (duplicate issue #23498 )
- https://osu.ppy.sh/beatmapsets/370819#osu/831724
- https://osu.ppy.sh/beatmapsets/5213#osu/26179

One of them is from 2015, so I doubt it has to do with the age of the map

**Comment by Non-Binary-Programmer** [comment]
I have the same issue with [this map](https://osu.ppy.sh/beatmapsets/3862#osu/23023).
[network.log](https://github.com/ppy/osu/files/11669649/network.log)
[performance.log](https://github.com/ppy/osu/files/11669650/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11669651/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11669652/updater.log)
[database.log](https://github.com/ppy/osu/files/11669653/database.log)
[input.log](https://github.com/ppy/osu/files/11669654/input.log)

**Comment by peppy** [comment]
Another case to track: https://github.com/ppy/osu/discussions/24310

**Comment by Joehuu** [comment]
> Another case to track: #24310

Seems to be a different issue, and can't seem to reproduce.

This is also related to https://github.com/ppy/osu-web/issues/4335.

**Comment by GamingWithJanko** [comment]
Video:
> https://youtu.be/3QfT2ZPiVm8

Maps:
> https://osu.ppy.sh/beatmapsets/364282
> https://osu.ppy.sh/beatmapsets/3862
> https://osu.ppy.sh/beatmapsets/552002
> https://osu.ppy.sh/beatmapsets/153455
> https://osu.ppy.sh/beatmapsets/362460
> https://osu.ppy.sh/beatmapsets/135358
> https://osu.ppy.sh/beatmapsets/590152

Version:
> Lazer 2023.924.1

**Comment by Joehuu** [comment]
Fixed, see https://github.com/ppy/osu/issues/25078#issuecomment-1790107365.
