### ISSUE TITLE
Mod badges don't take vertically flipped UI components' occupied space into consideration

### ISSUE THREAD

**Issue by PillTime** [ppy/osu#22165]
### Type

Cosmetic

### Bug description

When using a UI component at the top of the screen flipped vertically (like in the screenshot), the mod badges cover the component.
In the screenshot, the song progress element has the Origin set to BottomCenter and the Anchor to TopCenter ([link to full MainHUDComponents.json](https://gist.github.com/PillTime/09464fb7df6447fb15a9b1ce782927f6)).
The badge disappears when the drain time starts as expected, but it still feels wrong for the badge to display over UI elements at the start of a song.

### Screenshots or videos

![osu_2023-01-12_20-55-00](https://user-images.githubusercontent.com/2399664/212180780-b6044fe2-7a4c-414b-857e-5fb863ebbf95.png)

### Version

2022.1228.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10405963/database.log)
[input.log](https://github.com/ppy/osu/files/10405964/input.log)
[network.log](https://github.com/ppy/osu/files/10405965/network.log)
[performance.log](https://github.com/ppy/osu/files/10405966/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10405967/runtime.log)

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/30535.
