### ISSUE TITLE
Taiko leaderboard display needs to be moved somewhere else

### ISSUE THREAD

**Issue by OpenSauce04** [ppy/osu#22166]
I think this screenshot kind of speaks for itself

![image](https://user-images.githubusercontent.com/48618519/212185590-957a72c6-1d65-4e40-b20b-4b303dabe3dd.png)

**Comment by OpenSauce04** [comment]
I'd propose the bottom right of the screen

**Comment by mk56-spn** [comment]
https://github.com/ppy/osu/issues/20422

**Comment by OpenSauce04** [comment]
Oh, I did but that didn't come up for whatever reason, sorry
