### ISSUE TITLE
Custom backspace buttons on windows language don't work.

### ISSUE THREAD

**Issue by columna1** [ppy/osu#2216]
I use a keyboard layout called [Colemak](https://colemak.com) which maps the caps lock button to backspace. This backspace doesn't work for me using the windows language feature to switch layouts.
I assume that this is either a weird side effect with how you are handling windows languages, something to do with the way the button processed in the game, or how this "hack"/trick works to get caps lock into a backspace.
this is a major inconvenience to me but that probably doesn't matter much, my worry is why it isn't working in the first place.
I haven't tried with other buttons mapped to backspace, just the caps lock button
To reproduce:
either create a new layout with msklc
https://forum.colemak.com/topic/870-hacked-msklc-to-enable-remapping-capslock/
or download and install the layout and switch to it from the language menu
https://forum.colemak.com/topic/1621-colemak-for-windows-with-capslock-to-backspace/
and then try to use the backspace.

**Comment by peppy** [comment]
Could you please file this issue against [osu-framework](https://github.com/ppy/osu-framework)? It's at a lower level than osu!.
