### ISSUE TITLE
Volume in editor doesn't affect slider heads or ticks

### ISSUE THREAD

**Issue by iamt0bie** [ppy/osu#22187]
### Type

Game behaviour

### Bug description

Changing the volume of notes in the editor doesn't affect the slider head's or any sliderticks. It does correctly affect the slider's tail, the sliderslide, and sliderwhistles

Also, this might be a separate issue, and it's very strange, but the editor cannot add/remove hitwhistles (sliderwhistles on the sliderbody work correctly), finishes, or claps on sliders that already existed when the editor loads a beatmap, and it removes those samples, but only from slider heads, when the editor closes (it doesn't play the sample on slider heads when you test the beatmap, but when you go back to the editor the samples continue to play on the sliderheads until you exit the editor)

These issues aren't just aesthetic in the editor, any hitsounding done in the lazer editor will be messed up in this manner, even when the map is played normally (in the lazer client) or when exported to stable (in fact, all the hitsounds done in the editor disappear when exported except for those on slider bodies or tails)

### Screenshots or videos

https://user-images.githubusercontent.com/96793708/212401730-b8ece861-54e5-4514-a6fa-d8734cffa3c5.mp4

### Version

2022.1228.0

### Logs

[network.log](https://github.com/ppy/osu/files/10414779/network.log)
[performance.log](https://github.com/ppy/osu/files/10414780/performance.log)
[input.log](https://github.com/ppy/osu/files/10414783/input.log)
[database.log](https://github.com/ppy/osu/files/10414785/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10414786/legacy-ipc.log)
[runtime.log](https://github.com/ppy/osu/files/10414790/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10414791/updater.log)

**Comment by OliBomby** [comment]
We need some way to edit the hitsounds on the individual `NodeSamples`
