### ISSUE TITLE
taiko slider velocity very diference of stable

### ISSUE THREAD

**Issue by ChervyachokMigo** [ppy/osu#22189]
### Type

Game behaviour

### Bug description

All notes speed not correct compared stable. i think it's something wrong with slider velocity 

### Screenshots or videos

sample video: https://www.youtube.com/watch?v=jxbFxElOCc0

### Version

from oct 2022 finded to latest, now

### Logs

not exists

**Comment by bdach** [comment]
1. Please link the beatmap.
2. What resolution/aspect ratio was this recorded on?

**Comment by ChervyachokMigo** [comment]
> 1. Please link the beatmap.
> 2. What resolution/aspect ratio was this recorded on?

it's [my map](https://osu.ppy.sh/beatmapsets/1860039) but it repeats on every map 
default resolution full hd, 1.777

**Comment by OpenSauce04** [comment]
Yeah create a new issue for that

**Comment by ChervyachokMigo** [comment]
ok i think this ticket not acctually
