### ISSUE TITLE
osu!taiko notes which placed on timing point show incorrectly

### ISSUE THREAD

**Issue by ChervyachokMigo** [ppy/osu#22205]
### Type

Game behaviour

### Bug description

i found new bug: some notes, which stands on timing points appears with previous timing point speed in osu laser taiko.

samples from [my map ](https://osu.ppy.sh/beatmapsets/1860039) but i think this repeat in other maps too.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/74270643/212491952-58f5d728-3aaf-4880-ad67-3ba26b75e49f.png)
![image](https://user-images.githubusercontent.com/74270643/212492002-9e00cff7-ef7b-4ec6-b76b-494192210329.png)
![image](https://user-images.githubusercontent.com/74270643/212492104-3c147ad9-4dd2-468a-bd25-e6d3128b896b.png)
![image](https://user-images.githubusercontent.com/74270643/212492117-9f6208f6-af64-40ab-9b5c-92fd6884915c.png)

### Version

29 12 2022

### Logs

 -

**Comment by ChervyachokMigo** [comment]
[map]( https://osu.ppy.sh/beatmapsets/1860039#taiko/3823564)
00:23:634 (87) - 
![image](https://user-images.githubusercontent.com/74270643/212660762-aeaf25f1-b409-4cec-883c-9416dee6626c.png)
00:31:503 (157) - 
![image](https://user-images.githubusercontent.com/74270643/212660888-e0a95f0e-ed0f-4fb7-b465-e0d00802bd71.png)
00:39:372 (227) - 
![image](https://user-images.githubusercontent.com/74270643/212661022-7e7ded73-2a63-4925-8082-d557ca9edd14.png)
00:46:257 (289) - 
![image](https://user-images.githubusercontent.com/74270643/212661647-bd9a633b-0eea-4472-b107-25d85256fd42.png)
00:46:749 (295) - 
![image](https://user-images.githubusercontent.com/74270643/212662012-9fa54794-f01b-496d-aeaf-08c4771e31f0.png)
and other simmilar as that

**Comment by peppy** [comment]
Your timing points have floating point data in them. This was likely not generated by osu!. You can fix this by fixing your timing point's offset values to be whole numbers.

Please let us know if you find such an issue with a ranked beatmap.
