### ISSUE TITLE
Beatmap links in "Recent" section do nothing

### ISSUE THREAD

**Issue by toadsworth-jr** [ppy/osu#22217]
### Type

Game behaviour

### Bug description

When going into the ``Recent`` section of the profile, links to beatmaps do not function.
This can happen with every other profile.

### Screenshots or videos

Initially discovered when looking at my own profile (clods5XG)

https://user-images.githubusercontent.com/75596775/212529434-98f4f491-2e4a-4459-b374-6c963a11efc9.mp4

To make sure that it's not just me, I checked out another person's profile (Amamya)

https://user-images.githubusercontent.com/75596775/212529607-289fa7a7-de48-4f7f-81b7-00d6f3f25612.mp4

### Version

2022.1228.0

### Logs

[database.log](https://github.com/ppy/osu/files/10419709/database.log)
[input.log](https://github.com/ppy/osu/files/10419710/input.log)
[network.log](https://github.com/ppy/osu/files/10419711/network.log)
[performance.log](https://github.com/ppy/osu/files/10419712/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10419718/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10419719/updater.log)

**Comment by Joehuu** [comment]
This has already been fixed in https://github.com/ppy/osu/pull/21983, please wait for the next release.
