### ISSUE TITLE
osu!mania argon note pieces don't account for scrolling direction

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#22216]
### Type

Cosmetic

### Bug description

Noticed when wanting to play in the opposite direction.

### Screenshots or videos

![osu!_LN73pTyMWi](https://user-images.githubusercontent.com/35318437/212523694-bcacc1ef-0502-4390-8998-f0e3480792c8.gif)

### Version

2022.1228.0

### Logs

N/A

**Comment by zoey-on-github** [comment]
maybe we could flip the skin's elements vertically when upscroll is selected?
