### ISSUE TITLE
Starting test in lazer catch editor creates deafening audio

### ISSUE THREAD

**Issue by Baron9876** [ppy/osu#22242]
### Type

Game behaviour

### Bug description

When going to test a beat map in the osu!catch editor it plays audio for every note that has been prior to that point in the map you're testing. When early on the map/on a not very dense map this causes little to no problem. However, when you test on a very dense map/late into a map this causes a very loud audio spike, and a spike in lag. 

My only assumption is this is due to the auto "catching" every note in the map in the split second you start testing. Happens on any map

### Screenshots or videos

**Warning for potentially very loud audio**

https://user-images.githubusercontent.com/39878874/212759572-859a5670-71da-4cfa-b11b-6985ffc47a92.mp4

https://user-images.githubusercontent.com/39878874/212759578-548407d9-04ed-4630-b8dd-e7382e9d10c5.mp4

https://user-images.githubusercontent.com/39878874/212759580-e34402a8-673f-4b10-80eb-167af362be5d.mp4

### Version

2022.1228.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/10429270/network.log)
[performance.log](https://github.com/ppy/osu/files/10429271/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10429272/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10429274/updater.log)
[database.log](https://github.com/ppy/osu/files/10429276/database.log)
[input.log](https://github.com/ppy/osu/files/10429279/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10429281/legacy-ipc.log)

**Comment by bdach** [comment]
#20221
