### ISSUE TITLE
Turn Volume Up or Down while in settings

### ISSUE THREAD

**Issue by Nattale** [ppy/osu#22250]
### Type

Game behaviour

### Bug description

While in "settings menu" you can put the cursor in the middle and turn up or down the game volume, i dont know if its intended but thats it.

### Version

2022.1228.0

### Logs

[network.log](https://github.com/ppy/osu/files/10432797/network.log)
[performance.log](https://github.com/ppy/osu/files/10432799/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10432800/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10432801/updater.log)
[database.log](https://github.com/ppy/osu/files/10432802/database.log)

**Comment by peppy** [comment]
Yes. It's intended.
