### ISSUE TITLE
Draw frame stutters resulting in low performance

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu#2227]
Game built on Release configuration, with the [osu-lazer-git package from AUR](https://aur.archlinux.org/packages/osu-lazer-git).  
System configuration: AMD Ryzen Threadripper 1950X overclocked at 3.8GHz, NVIDIA GTX 980.  

The game is basically unplayable during gameplay, and it's even worse while recording, while osu!stable (under Wine) works like a charm in both cases.  
[This recording](https://streamable.com/n0zqx) shows an osu!stable gameplay, as smooth as it can be, followed by a very stuttery osu!lazer one, despite using very similar configuration.  
Both games were running on threads 0-7 while OBS was using threads 8-31.

Logs:
[network.log](https://github.com/ppy/osu/files/1815401/network.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/1815402/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/1815403/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/1815404/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/1815405/performance-gamethread.update.log)
[performance.log](https://github.com/ppy/osu/files/1815406/performance.log)
[runtime.log](https://github.com/ppy/osu/files/1815407/runtime.log)

**Comment by peppy** [comment]
Thanks for the report. There are people getting perfect performance on linux, so it must be something specific to your setup.

Please try debugging further and provide any details you may find. It is quite possibly driver or X11 system specific (linux has unlimited variables so we can’t really help out unless you find the cause).

**Comment by peppy** [comment]
Further debugging on discord shows that this is likely the result of a dated mono install.

**Comment by ThePooN** [comment]
I'm giving up getting a recent version of Mono to run on Arch Linux.  
There's no working recent package in both repos and on AUR. Only managed to get their master branch to build and even then it couldn't install properly and I couldn't even build osu!.

Giving up on getting osu!lazer to decently work on my system for now.
