### ISSUE TITLE
Changing display mode of `JudgementCounterDisplay` causes max judgement to be rendered regardless of "Show max judgement" setting until next (re)play or enabling and re-disabling the setting

### ISSUE THREAD

**Issue by TwoQuantumBits** [ppy/osu#22286]
### Type

Cosmetic

### Bug description

When changing the display mode of `JudgementCounterDisplay` with "Show max judgement" disabled, the max judgement is still rendered. The max judgement only goes away either on a new (re)play, or by enabling and re-disabling the "Show max judgement" setting on the current play.

This happens every time the display mode is changed.

### Screenshots or videos

https://user-images.githubusercontent.com/37262651/213346369-f05117eb-9ebe-4a5e-9adb-91a80ce2a954.mp4

### Version

master build (commit e58abf7)

### Logs

[database.log](https://github.com/ppy/osu/files/10453121/database.log)
[input.log](https://github.com/ppy/osu/files/10453122/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10453123/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10453124/network.log)
[performance.log](https://github.com/ppy/osu/files/10453125/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10453126/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10453127/updater.log)

**Comment by bdach** [comment]
cc/ @mk56-spn

**Comment by mk56-spn** [comment]
Will look into this in a couple of hours if no one does first
