### ISSUE TITLE
Autoplay misses when you wiggle playback speed.

### ISSUE THREAD

**Issue by Zozimoto** [ppy/osu#2228]
As the title says, Auto misses when you wiggle around the playback speed.

Here's a video showing it because github doesn't support video files: https://drive.google.com/uc?id=1KAbGqjkhHPZ3D_PRgA0r7rySUvDrPlON

**Comment by jacksonisiah** [comment]
Duplicate of #1825

**Comment by Zozimoto** [comment]
not exactly what i wrote, that thread is talking about how you skip around in the replay, auto misses. what i'm talking about, is that auto misses, when you change the playback speed fast.

**Comment by peppy** [comment]
This should be resolved (via `FrameStabilityContainer` and other replay handling  improvements).
