### ISSUE TITLE
Add icons to beatmap info wedge

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#2229]
Web already has these icons. Spinner icon is not implemented yet tho.
![](https://puu.sh/zIApb/5a7022f824.png)
![](https://puu.sh/zIA7z/7dc97f83f9.png)

**Comment by peppy** [comment]
Are you planning on doing this yourself?

**Comment by Joehuu** [comment]
Yeah, can't find the code for the last three icons.

**Comment by Joehuu** [comment]
Nvm got it, just need the icons.

**Comment by Aergwyn** [comment]
Same goes for osu!direct iirc.

**Comment by Joehuu** [comment]
Ik, and noticed that the the other modes don’t have these counts. Just copying code from osuruleset works and acts like stable, and wanted to change the tooltip name from the selected mod(ie. slider count should be named drumroll count in taiko, etc.)

**Comment by Joehuu** [comment]
How do I get these web icons? They seem to be custom icons (excluding length icon, it is the clock icon on fontawesome)

**Comment by peppy** [comment]
![Pasted Image 1.png](https://shipusercontent.com/fca10c4ee4d424172ae281c5d0e3ea0b/Pasted%20Image%201.png)

We will likely need to convert them from their svg format to be usable.

**Comment by Joehuu** [comment]
Sorry but idk how to add icons. I can only do the easy part of the code. Don't know anything about fonts.  I thought it was supposed to be added years ago from what you said on ppy/osu-resources#10.

**Comment by Joehuu** [comment]
With all the font changes and updates, can this be added to the osu font?

**Comment by peppy** [comment]
Will need to check with @arflyte as to how our workflow is for custom icons.

**Comment by arflyte** [comment]
We have the icon designs but it's not exported to usable form yet.

**Comment by peppy** [comment]
@arflyte could you at least provide them as some kind of format in this thread so we can look at making them display?

**Comment by arflyte** [comment]
The icons were super dated, and we discussed that it needs to be designed because it wasn't good enough... I haven't designed the new icons yet ._.
