### ISSUE TITLE
Slider velocity inconsistency between stable and lazer

### ISSUE THREAD

**Issue by MishterKirby** [ppy/osu#22299]
### Type

Game behaviour

### Bug description

Slider velocity is wrong on some maps causing sliders to overlap, which does not happen in stable in my testing

I noticed while playing [this map](https://osu.ppy.sh/beatmapsets/847498#osu/1772399), and I recorded a video attached below displaying the issue and comparing it to stable

I looked for issues related to this and couldn't find any, so I opened one since it does to affect gameplay

### Screenshots or videos

https://user-images.githubusercontent.com/48867925/213633122-c94bee5d-afa0-4b9f-8a10-1cc87eefbc1f.mp4

### Version

Originally found in 2021.623.0, still present in 2022.1228.0

### Logs

[database.log](https://github.com/ppy/osu/files/10463786/database.log)
[input.log](https://github.com/ppy/osu/files/10463787/input.log)
[network.log](https://github.com/ppy/osu/files/10463788/network.log)
[performance.log](https://github.com/ppy/osu/files/10463789/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/10463790/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10463791/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10463792/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10463793/updater.log)

**Comment by peppy** [comment]
Yeah I dunno. This beatmap has two timing points at the same point in time, which is completely invalid spec.

If you find this issue in a *ranked* beatmap, please let us know.
