### ISSUE TITLE
Selecting root folder of drive for importing maps from stable not working as expected

### ISSUE THREAD

**Issue by navidmafi** [ppy/osu#22305]
### Type

Game behaviour

### Bug description

Selecting the root folder of a drive when choosing a folder to symlink stable maps from, fails with the following error:

![image](https://user-images.githubusercontent.com/46371349/213792166-9fdab07a-cfe7-47dc-991f-5783ddd3689a.png)

#### Steps to reproduce:

1 - Run first time setup wizard
2 - Choose change folder location
![image](https://user-images.githubusercontent.com/46371349/213792372-4fc10a9e-30ce-4590-a9c5-acbf90909dcc.png)
3 - select a NTFS partition that has an osu stable installation in the root

#### Already tried:

Not changing the folder location in setup wizards, copies and converts all of the stable beatmaps to osu-lazer directory and format although the target partition is NTFS formatted.

Skipping the setup entirely and using the "Import from stable" button does the same.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/46371349/213793619-c6a7e8c0-8333-4735-b6e2-1be8c7903596.png)

Partition root containing a valid(?) stable installation

### Version

2022.1228.0-lazer

worth noting: The target partition is a Microsoft VHDX image, should that matter.

### Logs

[runtime.log](https://github.com/ppy/osu/files/10469745/runtime.log)
[database.log](https://github.com/ppy/osu/files/10469748/database.log)

**Comment by bdach** [comment]
Let me get this straight because what I'm looking at here looks really confusing: you have your stable songs directory mapped to `E:\` is what this looks like? And you're trying to set up lazer *also* on `E:\`?

**Comment by navidmafi** [comment]
Not the songs directory specifically, but a full stable installation on E:\
So my stable songs folder would be `E:\songs` (please take a look at the E:\ folder screenshot)

 I'm  trying to use that for lazer as well.

**Comment by bdach** [comment]
Ok, well, so first of all, this is kind of a weird setup to want to have but I do suppose there is no reason for _not_ supporting it.

Secondly, there's this:

> 2023-01-20 19:37:06 [error]: Error during migration: The directory specified, 'osu-lazer', is not a subdirectory of 'E:\'. (Parameter 'path')
> 2023-01-20 19:37:06 [verbose]: ⚠️ Error during migration: The directory specified, 'osu-lazer', is not a subdirectory of 'E:\'. (Parameter 'path')

When you select a directory to migrate lazer to that already has files, lazer automatically will attempt to create a `osu-lazer` subdir and use *that* instead, to avoid intermingling itself with other surrounding files. This error above looks like the problem is somewhere around that, but there are no actual stacks, so I can't really tell *what* is failing here exactly.

Probably gonna need one of us to recreate this strange setup and see what the actual error is...

**Comment by navidmafi** [comment]
I think I misunderstood and mixed things up really badly and also confused everyone

I'm trying to set lazer data folder to `E:\` (which doesn't work) 

On the other hand I'm trying to import stable songs from `E:\` 


This issue is misleading at best and invalid at worst, I will edit and re open this or create a new one, whatever you think is a better idea.

**Comment by navidmafi** [comment]
So yes, this is an invalid issue

I'm not selecting root folder of a drive to import stable maps from, I'm selecting it for new lazer data location, lazer tries to create a new directory to avoid conflicts which fails for some reason. (what @bdach said)

I will open a new issue with proper reproducing steps

**Comment by navidmafi** [comment]
Check #22345 please
