### ISSUE TITLE
2 key set on the same keybind cannot be used properly in std

### ISSUE THREAD

**Issue by wanderingkittenn** [ppy/osu#22301]
### Type

Game behaviour

### Bug description

tdlr: if z and x is set to one keybind and you tried to stream with z and x, it get throttled and lags or something and doesn’t work u can try it

weird “issue” right? i play tapping with the pen and hovering to aim and use too zx so for example for jumps and sliders ill use my pen and for streams, bursts and triples ill use z and x so what’s my issue? or anybodys because everyone uses zx only? for me on extremely fast streams or bursts ill alternate between x (index finger) and my mouse button which can easily be set to b1 and b2 so yee ill get straight to the point

mainly this is a input processing problem (yes i don’t know anything you can tell, you know what i mean though) but its annoying because as i mention before how i alternate, sometimes if it’s a slower stream slower ill use my finger i want to give to peppy on z which… oh, it’s mapped to the same button as my pen so i cant properly because its bugged and dropping all my inputs 

(stuff i would say but you get the idea by now goes here) it’s frustrating that m1 and m2 is gone especially from replays because im going to be looking like im single tapping at goddamn 300bpm and get banned

i have troubles with english and anything mildly social i hope this post is atleast ok it wont matter in a month im kinda dumb oh man how do i make test smaller and strikethrough.. ask me anything before criticising any of this post idek if im making sense

### Version

2022.1228.0-lazer

### Logs

domt need also i cant be bothered my pooper is updating

**Comment by frenzibyte** [comment]
If you're trying to map two keys to either "Left button" or "Right button" as per the following (e.g. <kbd>Z</kbd> and <kbd>X</kbd> to "Left button"):
![CleanShot 2023-01-21 at 15 50 59](https://user-images.githubusercontent.com/22781491/213867597-351afcaa-c7af-48a6-b6bb-1d8e6a634153.png)

Then do not expect that to work as you desire. The point of having more than one key per binding is to allow using different input sources for playing the game, not use all of them at once. If you want to stream, simply map <kbd>Z</kbd> to "Left button" and <kbd>X</kbd> to "Right button".
