### ISSUE TITLE
Catch needs to correctly use FastRandom to offset droplets

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2232]
Requires some more foundation around random seeding per hitobject.

**Comment by ekrctb** [comment]
I request FastRandom and catch beatmap convert codes from osu!stable.

**Comment by peppy** [comment]
`FastRandom` is already present in the `Mania` namespace. As it's a legacy component rather than moving it a common location, just copy that class into the respective location in `Catch`.

Here's the relevant conversion code:
https://gist.github.com/peppy/6a1dc3dfcd80d84464e3475d239f43c5

**Comment by ekrctb** [comment]
The droplet disposition process is not in that code.

**Comment by peppy** [comment]
droplets are adding an X offset of `hitFactoryFruits.random.Next(-20, 20)` per droplet. do note that the `FastRandom` needs to be at the correct seed value for this to match stable, which may need some further iteration to get right.

**Comment by smoogipoo** [comment]
@peppy What's the ordering on randomisation calls? Are droplets randomised after all hitobjects are constructed, or are they randomised at the construction time of the juice stream?

**Comment by peppy** [comment]
After, I think. It's in `UpdateCalculations`
