### ISSUE TITLE
Multiple bugs noticed, (a) Textbox caps warning bug, and (b) cursor teleportation bug

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2233]
Currently running latest release.

First bug:
- Open the login sub menu
- Press caps key while on username
- Caps warning appears only in password

Second bug:
- Place mouse in a certain place
- Hover tablet elsewhere
- Click with mouse
- Cursor teleports to old mouse position

Video evidence:
https://streamable.com/f9z11

**Comment by jai-sharma** [comment]
Having the caps lock warning show for only the password field seems intentional.

**Comment by Frontear** [comment]
That wouldn't seem like a very good design choice, even if it makes sense..

**Comment by jorolf** [comment]
The reason password field has this warning is because you can't see if it's activated. 
The ~username~ email field however shows what you typed in so you're going to notice pretty fast that caps lock is activated

**Comment by Frontear** [comment]
If that is the case, then the warning should only appear if password textbox is focused on.

**Comment by Joehuu** [comment]
I think he wants the warning to only appear when on the password field.

**Comment by jorolf** [comment]
That would be a simple fix.

**Comment by peppy** [comment]
Please report one bug per issue.

1. warning should only appear when typing password
2. each input device remembers its position.

**Comment by peppy** [comment]
Going to close this; please re-file as separate issues.
