### ISSUE TITLE
Selecting root of a drive for changing lazer data locations fails

### ISSUE THREAD

**Issue by navidmafi** [ppy/osu#22345]
### Type

Game behaviour

## Steps to recreate:

1 - From settings select "Change folder location"
2 - Select a partition root for new data location

https://user-images.githubusercontent.com/46371349/213909066-fd5397bf-3a23-44f8-b891-57224a59500f.mp4

## What was expected 

a new directory called "osu-lazer" would be created in the "E:\" folder and be used as the new location

## Alternative solutions 

Create an empty directory yourself and choose that.

![image](https://user-images.githubusercontent.com/46371349/213908296-7a956673-8764-4a3c-912c-a485011f6f22.png)

https://user-images.githubusercontent.com/46371349/213908913-b784d647-b263-4902-8674-c1b22507a46b.mp4

### Version

2023.121.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/10474075/runtime.log)

**Comment by Cootz** [comment]
I'm not sure if it's a bug or a feature. Some source code from System.Runtime:
```csharp
            // We want to make sure the requested directory is actually under the subdirectory.
            if (trimmedNewPath.StartsWith(trimmedCurrentPath, PathInternal.StringComparison)
                // Allow the exact same path, but prevent allowing "..\FooBar" through when the directory is "Foo"
                && ((trimmedNewPath.Length == trimmedCurrentPath.Length) || PathInternal.IsDirectorySeparator(newPath[trimmedCurrentPath.Length])))
            {
                FileSystem.CreateDirectory(newPath);
                return new DirectoryInfo(newPath);
            }

            // We weren't nested
            throw new ArgumentException(SR.Format(SR.Argument_InvalidSubPath, path, FullPath), nameof(path));
```
