### ISSUE TITLE
Drag/drop skin import lead to render freeze

### ISSUE THREAD

**Issue by mty22** [ppy/osu#22342]
### Type

Game behaviour

### Bug description

Actions taken which lead to render freeze:

osu!lazer (build `2023.121.0-lazer`) was in Windowed mode [958x826] via F11 toggle, drag/drop skin from Windows environment into the game in order to load the skin.

After the skin had imported, game rendering had ceased/completely frozen. Music/actions within game were still playing/working, and I could alt F4 without any problems (I could hear things when pressing keys and nothing was rendering).

Event viewer indicates an OpenGL error and also a .NET Runtime unhandled excepion (log is attached).

This is the first time I've run into this issue and I've imported skins many times in the past using this method. I could not locate similar issues.

Thanks!

Matt / frzn

### Screenshots or videos

Image of my game after render freeze:
![image](https://user-images.githubusercontent.com/2951231/213901216-4a794a6b-4030-4b7a-ac27-934b50285d4a.png)

### Version

2023.121.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10473781/database.log)
[network.log](https://github.com/ppy/osu/files/10473782/network.log)
[performance.log](https://github.com/ppy/osu/files/10473784/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/10473785/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10473786/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10473787/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10473788/updater.log)
[eventviewer_errors.zip](https://github.com/ppy/osu/files/10473789/eventviewer_errors.zip)

**Comment by mty22** [comment]
Skin used: https://www.dropbox.com/s/scowbfp3q4wud6p/MonkoEdit%20RHS.osk?dl=0

**Comment by bdach** [comment]
Most of the time this indicates a driver fault which there is not much more we can do about for now other than wait for new renderer backends to arrive.

Driver updates may also fix this, but your mileage may vary.

**Comment by peppy** [comment]
Closing as should-be-resolved.

Please feel free to reply in this thread if you can still reproduce an issue.
