### ISSUE TITLE
failsound.ogg keeps playing indefinitely

### ISSUE THREAD

**Issue by mikkreb** [ppy/osu#22350]
### Type

Game behaviour

### Bug description

When you fail a beatmap with a legacy skin, which has a failsound.ogg, it starts playing and does not stop, even if you leave to the song selection screen and it continues in gameplay.

### Screenshots or videos

https://user-images.githubusercontent.com/23295886/213917311-339f0f43-0cf6-484b-a866-ca1806191014.mp4

An example of the reported behaviour.

### Version

2023.121.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/10474483/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10474484/updater.log)
[database.log](https://github.com/ppy/osu/files/10474485/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10474486/legacy-ipc.log)
[performance.log](https://github.com/ppy/osu/files/10474490/performance.log)
[network.log](https://github.com/ppy/osu/files/10474492/network.log)

**Comment by stanriders** [comment]
Already fixed by #22339
