### ISSUE TITLE
Each input device remembers its position

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2235]
To reproduce:
- Move mouse to one position, remember that position
- Hover with a tablet pen (may also work with touchscreen?) and move the cursor elsewhere
- Click with your mouse, the cursor should teleport back to the old mouse position you remember.

**Comment by peppy** [comment]
This is actually intentional for the time being. We may consider changing the behaviour if it feels non-intuitive, though.

**Comment by LittleEndu** [comment]
I complained about it before because I play without pen nib and use my touchpad's left click. This behavior makes clicking like that impossible because where I hover with my pen isn't where my touchpad will click.

**Comment by LittleEndu** [comment]
Would people using this behaviour to bypass the difficulty executing cross screen jumps be considered cheating?
