### ISSUE TITLE
Importing beatmaps from stable doesn't work for unsubmitted, and long map names

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2236]
The `Import Beatmaps From Stable Task` doesn't correctly handle unsubmitted beatmaps and long named maps.

When attempting to import unsubmitted (and some normal) maps, this is present in the logs
`Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: FileInfo.Hash'.`

When attempting to import a map with a longer name, this is present in the logs
`System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

The log in question can be found [here](https://hastebin.com/umadevisen.vbs).

**Comment by peppy** [comment]
Could you please include a link to the beatmap/osz file?

**Comment by Frontear** [comment]
I will leave a list of all the beatmaps that I can link here (these maps are referenced in the logs):

(as a side note, I have not tried dragging and dropping the beatmaps osz files, only importing from stable)

- https://osu.ppy.sh/s/419600
- https://osu.ppy.sh/s/431455
- https://osu.ppy.sh/s/449200
- https://osu.ppy.sh/s/461744
- https://osu.ppy.sh/s/462386
- https://osu.ppy.sh/s/476695
- https://osu.ppy.sh/s/480765
- https://osu.ppy.sh/s/489996
- https://osu.ppy.sh/s/499959
- https://osu.ppy.sh/s/501106
- https://osu.ppy.sh/s/514858
- https://osu.ppy.sh/s/519256
- https://osu.ppy.sh/s/521653
- https://osu.ppy.sh/s/542433
- https://osu.ppy.sh/s/549468
- https://osu.ppy.sh/s/555030
- https://osu.ppy.sh/s/564538
- https://osu.ppy.sh/s/581970
- https://osu.ppy.sh/s/582089
- https://osu.ppy.sh/s/582625
- https://osu.ppy.sh/s/583277
- https://osu.ppy.sh/s/583487
- https://osu.ppy.sh/s/584770
- https://osu.ppy.sh/s/585435
- https://osu.ppy.sh/s/585631
- https://osu.ppy.sh/s/58604
- https://osu.ppy.sh/s/586121
- https://osu.ppy.sh/s/586889
- https://osu.ppy.sh/s/587024

**Comment by Zyfarok** [comment]
I don't know if it's related or not, but my beatmap importation went well until some map where I got:
```
08/04/2018 00:40:52: Could not import (113192 Lifetheory - Angel)
08/04/2018 00:40:52: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: BeatmapSetInfo.OnlineBeatmapSetID'.
08/04/2018 00:40:52: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
08/04/2018 00:40:52: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
08/04/2018 00:40:52: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
08/04/2018 00:40:52: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
08/04/2018 00:40:52: at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

And then, all the following maps that should have been imported crashed with this "FileInfo.Hash" error :
```
08/04/2018 00:40:52: Could not import (113219 Kato Emiri - happy bite (TV Size))
08/04/2018 00:40:52: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: FileInfo.Hash'.
08/04/2018 00:40:52: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
08/04/2018 00:40:52: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
08/04/2018 00:40:52: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
08/04/2018 00:40:52: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
08/04/2018 00:40:52: at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)```

**Comment by peppy** [comment]
Tested all maps in https://github.com/ppy/osu/issues/2236#issuecomment-374002912 with no failures. I can see how the path too long may be occuring, so will look at fixing that. The format exception seem to definitely be fixed now, though.

**Comment by peppy** [comment]
This issue should be resolved by the above four PRs.

**Comment by Frontear** [comment]
I'll retry to import these beatmaps, and hopefully they do work.

**Comment by peppy** [comment]
Should now be resolved.

**Comment by Morilli** [comment]
I had beatmap importing issues before, so assuming every importing issue was fixed, went back and reinstalled osu!lazer as well as deleting any previously done import. What happened on import was that A TON of maps that could get imported previously now failed to do. They seem to all throw the same error, which looks similar to this:

```01.06.2018
 20:37:53: Import of 347556 Camellia - flying in the flow of deep-sea failed and has been rolled back.
01.06.2018 20:37:53: System.IO.IOException: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
01.06.2018 20:37:53: 
01.06.2018 20:37:53: bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
01.06.2018 20:37:53: bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
01.06.2018 20:37:53: bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
01.06.2018 20:37:53: bei osu.Game.IO.Archives.LegacyFilesystemReader.GetStream(String name)
01.06.2018 20:37:53: bei osu.Game.Database.ArchiveModelManager`2.createFileInfos(ArchiveReader reader, FileStore files)
01.06.2018 20:37:53: bei osu.Game.Database.ArchiveModelManager`2.Import(ArchiveReader archive)
```

The error translates to "`The syntax for filename, directory name, or volume label is incorrect.`".
Sorry but I do not know how to get the log files in english.

Here is a zip file of all log files from that session: 
[Import-failure.zip](https://github.com/ppy/osu/files/2064164/Import-failure.zip)

**Comment by peppy** [comment]
What windows version are you running on?

**Comment by Morilli** [comment]
Current version of Windows 10 Pro; 17134.81 64-bit.

**Comment by peppy** [comment]
Closing in favour of #2718, which focuses on the new issue.
