### ISSUE TITLE
Argon skin hit circles may not display correctly after quick rewind in editor

### ISSUE THREAD

**Issue by peppy** [ppy/osu#22372]
Need to investigate. Looks like an oversight in rewind logic?

### Discussed in https://github.com/ppy/osu/discussions/22314

<div type='discussions-op-text'>

<sup>Originally posted by **RBQcat** January 21, 2023</sup>

https://user-images.githubusercontent.com/74862110/213864090-80a88b98-4b40-45fd-8c0c-5901e2751ebf.mp4

</div>

**Comment by ekrctb** [comment]
Duplicate of #21089? Also #22353 is potentially the same issue.

**Comment by peppy** [comment]
Seems so. Will close in favour of #21089.
