### ISSUE TITLE
Add per-ruleset skin layout customisation

### ISSUE THREAD

**Issue by peppy** [ppy/osu#22388]
Right now, a skin layout is saved globally for a skin. This doesn't work great for multiple rulesets, where the playfield may be attached to an edge of the screen and cause overlap. Also, in the new "argon" designs, UI elements have already been customised to often be attached to the playfield – this is also the case with classic skins like the osu!mania default.

This epic replaces existing requests for this:
- https://github.com/ppy/osu/issues/12871
- https://github.com/ppy/osu/issues/6124

This could be used to solve issues like:
- https://github.com/ppy/osu/issues/21949
- https://github.com/ppy/osu/issues/20422
- https://github.com/ppy/osu/issues/22362

It would both allow for applying per-ruleset defaults, and give users the option to further customise from those defaults. There should also likely be facilities in the editor to copy full layouts between rulesets (maybe not required if we have clipboard support).

**Comment by frenzibyte** [comment]
Related: https://github.com/ppy/osu/discussions/20694

**Comment by peppy** [comment]
Pulling out of my recent skin structural write-up for visibility:

Currently we store configuration in individual `json` files, per target container. This likely won't scale well once we add ruleset rules in (and it also makes migrating over version changes harder).

My initial thoughts is that we should move the full skin configuration into a single json structured file, with "layer" objects that container local information as to how/when they should be used. We could then have four of the same layers specified, each with a different ruleset tag to define when they should be used.

This could also allow for the case where multiple rulesets share a layout (ie. there are no ruleset tags), or at very least allow for migration from global to per-ruleset with less fuss.

**Comment by peppy** [comment]
@frenzibyte looking again at https://github.com/ppy/osu/discussions/20694, I think your first approach is closest to what I had in mind. Did you want to revisit that and see how things play out? I think if you revisit it, also keep in mind what I mentioned in my last comment here. It'll probably be enough to make sure you can easily hook the new structure up to the undo/redo system (#22506).

**Comment by peppy** [comment]
As an update, frenzi mentioned elsewhere that he's a bit busy at the moment so I'm continuing to work through this.

I've rebased approach 1 at https://github.com/ppy/osu/compare/master...peppy:osu:ruleset-skinning-frenzi-approach-1-rebase?expand=1 and it seems to be working well.

**Comment by peppy** [comment]
The base work for this has been completed and merged. Remaining tasks are to use this implementation in skin transformers to update the default layouts to match expectations for legacy skins.
