### ISSUE TITLE
Beatmap carousel can't be scrolled with right click

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2239]
In stable client right click acts like scrollbar acts in internet browser, instantly jumping to that position in the scrollable.

**Comment by peppy** [comment]
This could be added back as an option but should be disabled by default.

**Comment by LittleEndu** [comment]
Added back? Why was it removed?

**Comment by peppy** [comment]
it is not yet implemented.

**Comment by jorolf** [comment]
It is implemented in OsuScrollContainer but not enabled BeatmapCarousel
https://github.com/ppy/osu-framework/pull/857
https://github.com/ppy/osu-framework/issues/897
https://github.com/ppy/osu/pull/1013
https://github.com/ppy/osu/blob/master/osu.Game/Graphics/Containers/OsuScrollContainer.cs
https://github.com/ppy/osu/blob/master/osu.Game/Screens/Select/BeatmapCarousel.cs

**Comment by jorolf** [comment]
And I disagree with it being disabled by default. While it is "non-standard" it's quite useful. Many people would likely enable it back when switching from osu!stable, new players however would probably ignore/not find the toggle in the settings.

**Comment by peppy** [comment]
There’s already a draggable scroll bar that you can intuitively drag. No other app ever uses right click for this purpose. We use right click for context menus now.

It is imperative that this functionality is off by default.

**Comment by jorolf** [comment]
Doesn't osu!stable use right click for context menus, too?

**Comment by jorolf** [comment]
And why would I prefer dragging a small dot on the right window edge instead of clicking/dragging the right mouse button anywhere

**Comment by peppy** [comment]
We can consider making it bigger if once grouping options etc. are implemented people complain about the size.

Right click drag is not going to be default on, though.

**Comment by LittleEndu** [comment]
Is there a context menu planned for the carousel itself? If not then why should it not act like it does in stable where right clicking the area in the middle scrolls the carousel?

**Comment by peppy** [comment]
It will not work on tablets. It will not work on touchscreens. It makes zero sense to anyone who has used any other UI in their lives.

**Comment by peppy** [comment]
Accidentally miss a panel and click 2px away from it SUDDENLY WHOLE LIST JUMPS TO NEW POINT

"wtf"

Just because you're used to something and/or I implemented it a certain way many years ago doesn't mean we should stick to it. We're looking to bring things in line with standard UX guidelines and this is one of the changes that is going to happen.

Don't worry. We will make sure it is still easy to navigate long lists via the scroll bar or similar.

**Comment by jorolf** [comment]
So a proper scrollbar including clicking on the side to jump is going to be a thing? The current design doesn't include that, does it?
