### ISSUE TITLE
Mod icons are cut off on osu!mania minimized result cards for lazer plays with hold ticks

### ISSUE THREAD

**Issue by TwoQuantumBits** [ppy/osu#22408]
### Type

Cosmetic

### Bug description

On osu!mania, with the introduction with the "Hold Tick" statistic in the result card for maps with hold ticks, the minimized result card is no longer able to contain everything, thus cutting out the mod icons on lazer (non-classic) plays with mods enabled.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/37262651/214521093-75fe710a-1015-4f4b-a000-aca2dadb2589.png)

### Version

master build (commit efe57f2), release 2023.123.0

### Logs

N/A

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21622
