### ISSUE TITLE
Limit scroll bar height on song select

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#2241]
The scroll bar can't be clicked or dragged on the search area.
![](https://puu.sh/zKEAV/e7d03f139f.png)
~Edit: Can't title stuff rn.~

Should *start below* the search area and *end above* the osu! logo.

**Comment by Joehuu** [comment]
Same here.
![](https://puu.sh/zKELk/b39eabe947.png)

**Comment by ticotaco72** [comment]
still a thing

**Comment by Joehuu** [comment]
Fixed in #5468.
