### ISSUE TITLE
Triangles animation doesn't show in various places until you open the settings

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#22427]
### Type

Cosmetic

### Bug description

some places are:
- song select
- pause menu (ingame)

the triangles skin never shows any triangles even after opening the settings but i'm not sure if they were removed or not since i never check that skin. 

### Screenshots or videos

https://user-images.githubusercontent.com/43358824/214760760-fc06733e-1f64-4955-ae76-0a500dc750e2.mp4

### Version

commit 9ed0b8ccfaeec972f9bf2a0f2d64ccb407100d71

### Logs

[network.log](https://github.com/ppy/osu/files/10506397/network.log)
[performance.log](https://github.com/ppy/osu/files/10506398/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10506399/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10506400/updater.log)
[database.log](https://github.com/ppy/osu/files/10506401/database.log)
[input.log](https://github.com/ppy/osu/files/10506402/input.log)

**Comment by peppy** [comment]
Very weird, I can't replicate. Can you test on latest master just to make sure (there was a change to triangles masking since the commit you were testing on).

cc/ @EVAST9919

**Comment by EVAST9919** [comment]
Yeah, I was about to ask are you sure this was happening before https://github.com/ppy/osu/pull/22409 was merged?

**Comment by mouzedrift** [comment]
i tested this again on latest master (commit 9677a8e3b374ccf46802764c0da21bd3ab392d2e) and it still appears to be bugged for me

**Comment by EVAST9919** [comment]
Fair enough. In that case your proposal will be easier to use later with merging these classes together.

**Comment by bdach** [comment]
All of the above notwithstanding fixing the shader so it *doesn't* div-by-zero is also something that could (should?) be done. Just need confirmation that this issue is what that is.

**Comment by mouzedrift** [comment]
> Can't reproduce either on my machine, but on comparing `Triangles` and `TrianglesV2` I notice a difference:
> 
> https://github.com/ppy/osu/blob/c4dce30de510e96accb824f2acc37d26d76f8368/osu.Game/Graphics/Backgrounds/Triangles.cs#L297-L298
> 
> 
> https://github.com/ppy/osu/blob/c4dce30de510e96accb824f2acc37d26d76f8368/osu.Game/Graphics/Backgrounds/TrianglesV2.cs#L235-L237
> 
> Thinking is that the `texelSize` uniform starts off with an undefined initial value, breaking `Triangles` usages until the first `TrianglesV2` is shown on screen, which sets the uniform and therefore restores operation to `Triangles` too?
> 
> @mouzedrift would you be able to pull and test [this branch](https://github.com/ppy/osu/compare/master...bdach:osu:test-triangles-fix?expand=1) and see if it helps any?

this seems to work and fixed the issue for me

**Comment by bdach** [comment]
@mouzedrift thanks for confirming.

Not sure where to take this now. The game-side branch linked above is a guaranteed fix, but it may come at a bit of a performance cost (I'm not super sure how I'd go about measuring this; in crude measurements I didn't see one - FPS looks roughly the same, seemingly no extra batch flushes). But maybe fixing the shader is preferable?

@ppy/team-client would appreciate an opinion or two here on how to proceed.

**Comment by EVAST9919** [comment]
As long as we are not setting `texelSize` for every triangle - performance should be around the same, yes. And I prefer your approach since as I mentioned this part most likely will be included in the base class later on. Shader should be adjusted anyway though to handle 0 value separately.

**Comment by EVAST9919** [comment]
@bdach revisited your branch and I would argue that using just 0 `texelSize` looks way better. I assume the code you used was taken from `TrianglesV2`, and `texelSize` calculations there were made with constant triangles size in mind. Applying it here results in bigger triangles having too much smoothing which makes them look very blurry.
![Снимок экрана (319)](https://user-images.githubusercontent.com/22874522/215264938-7608d2aa-87d0-4077-b4be-0d3ed571c7ef.png)

**Comment by bdach** [comment]
I wrote my branch in five minutes to confirm the issue. I don't claim it to be a proper fix which is why it's not PRed and why I was asking for further opinions here.
