### ISSUE TITLE
Crash when attempting to load certain profiles

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#2242]
[runtime.log](https://github.com/ppy/osu/files/1824110/runtime.log)

https://www.youtube.com/watch?v=OKwUTmpVUYs

**Comment by peppy** [comment]
Which profile were you attempting to access?

**Comment by ToIGLAK** [comment]
It appears on any profile i choose.

**Comment by VPeruS** [comment]
Version on program?

**Comment by ToIGLAK** [comment]
I updated lazer today

**Comment by smoogipoo** [comment]
This is an issue with our deploy script not outputting any localisation files for some reason. I've tested msbuild locally and it seems to copy the folders to the output paths, so it needs more investigation.

**Comment by peppy** [comment]
Both on windows and mac, I only get the following folders in output:

![untitled](https://user-images.githubusercontent.com/191335/37635438-eb8c3daa-2c3e-11e8-8833-6044084d38b1.png)

Definitely a build-time issue, not deploy.

**Comment by smoogipoo** [comment]
Weird, and that's compiling with rider? Is it the same output in osu.Desktop/bin/Debug/ too?

I get all the folders on my mac o_o

**Comment by peppy** [comment]
Yeah. On a fresh clone and windows build I did get more folders, weirdly enough. But a full project clean doesn't fix the output. I think there's something more to it.

**Comment by peppy** [comment]
For anyone seeing this, it seems to be solved by

```
rm -r packages
nuget restore
```

I believe an older version of nuget was incorrectly handling the humanizer dependency chain.

Will push out a new build tonight with this fixed.
