### ISSUE TITLE
Pause background sound effect continues to play after quitting

### ISSUE THREAD

**Issue by Stehsaer** [ppy/osu#22446]
### Type

Game behaviour

### Bug description

Pausing background sound continues to play after pressing the quit button, and it also causes a rather long pause, which shouldn't exist, at the beginning of next play. Heavily ffects gameplay experience. See screen recording below. 

### Screenshots or videos

https://user-images.githubusercontent.com/54050160/215262612-b11735ad-9959-4b89-9a1d-e21d181d65b8.mp4

notice that little *whoooooooooooo* sfx after pausing, it continues after quitting and disappears when osu!lazer is switched to background.

### Version

2023.123.0 (Windows 11, x86 arch)

### Logs

[updater.log](https://github.com/ppy/osu/files/10527026/updater.log)
[database.log](https://github.com/ppy/osu/files/10527028/database.log)
[input.log](https://github.com/ppy/osu/files/10527029/input.log)
[network.log](https://github.com/ppy/osu/files/10527030/network.log)
[performance.log](https://github.com/ppy/osu/files/10527032/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10527033/runtime.log)

**Comment by Stehsaer** [comment]
After restarting both lazer and computer, the bug is still reproduce-able. It happens to every skin, built-in ones(argon, argon pro, triangles, classic) and custom ones. what's more, switching the skin can make the bug disappear, but only once. Quitting the second time after switching the skin, the bug appears again.

**Comment by Stehsaer** [comment]
it also occasionally triggers an "unobserved error, reported to dev" warning

**Comment by Stehsaer** [comment]
More info about my sys:

**Comment by peppy** [comment]
@Stehsaer after you get the "unobserved error", could you please save and upload your `runtime.log`? Note that the file will reset each time you start the game, so I specifically request it immediately after you reproduce the issue.

I'm not sure if it will be relevant, but it may help in understanding what is going on here.

**Comment by Joppe27** [comment]
It looks like the original poster had an unreliable internet connection in the video they attached. I can indeed reproduce this when artificially crippling my connection to a whopping ~56 kbps. 

I think what's happening here is the thread which handles the disposal queue on gameplay exit is getting blocked by user avatar downloads for the in-game leaderboard (in hindsight you can also see this in the video):

https://github.com/ppy/osu/blob/02c74f5fb4b893b3881aafe2eb2feebe67b68f88/osu.Game/Screens/Play/HUD/GameplayLeaderboardScore.cs#L287

In normal situations, these avatars are loaded before any reasonable person would exit gameplay (or very quickly after) but in this case the connection is so slow and unstable that the late disposal does become a noticable issue:

<details>
  <summary>Thread view (large image)</summary>

![afbeelding](https://user-images.githubusercontent.com/56885706/216741442-41eb8b80-9e7e-4ea1-92b5-783ba68dd76e.png)
</details>

**Comment by Stehsaer** [comment]
> It looks like the original poster had an unreliable internet connection in the video they attached. I can indeed reproduce this when artificially crippling my connection to a whopping ~56 kbps. 
> 
> I think what's happening here is the thread which handles the disposal queue on gameplay exit is getting blocked by user avatar downloads for the in-game leaderboard (in hindsight you can also see this in the video):
> 
> https://github.com/ppy/osu/blob/02c74f5fb4b893b3881aafe2eb2feebe67b68f88/osu.Game/Screens/Play/HUD/GameplayLeaderboardScore.cs#L287
> 
> In normal situations, these avatars are loaded before any reasonable person would exit gameplay (or very quickly after) but in this case the connection is so slow and unstable that the late disposal does become a noticable issue:
> 
> <details>
>   <summary>Thread view (large image)</summary>
> 
> ![afbeelding](https://user-images.githubusercontent.com/56885706/216741442-41eb8b80-9e7e-4ea1-92b5-783ba68dd76e.png)
> </details>
> 
> 

That may be the cause. I'm living in China. The internet connection to bancho server is relatively slow and it generally takes a long time to load my avatar (5~10secs, avg~7secs), regardless of stable or lazer.

**Comment by peppy** [comment]
Thanks for reproducing this. It definitely looks like your hypothesis is correct.

To elaborate more on what is happening:

- Many avatars are being queued for load at song select, loading via `TextureStore` -> `OnlineStore`
- Gameplay is started and also begins to load textures for the current skin via `TextureStore` but is put in the queue behind the online texture loads. The point of lock contention is:

https://github.com/ppy/osu-framework/blob/16d1c2d3356b0f59271fb49cff5fe8373ae9cdf3/osu.Framework/Graphics/Textures/TextureStore.cs#L212

- The user exits gameplay (after gameplay probably not loading, or somehow loading but delayed by the texture loads?)
- Individual pieces of the gameplay system queue for disposal, but disposal waits for load to finish before it can continue, causing a bottleneck on the original avatar loads.
- Things aren't disposed as fast as expected

There's a few things we can do to improve this in order of simplicity:

- Introduce a `PauseOverlay.Stop` call in `Player.OnExiting`, similar to `failAnimationLayer.Stop` which already exists. This will remove dependence on disposal for the sound stopping
- Reduce the locking on `TextureStore`, or isolate in a way that it doesn't lock on online lookups at very least

**Comment by peppy** [comment]
To elaborate further, this is highly likely happening because the same avatar is being loaded in the gameplay stack (the leaderboard) as well as at song select. We already guard against online fetches blocking non-online fetches (or rather *per lookup*), and this is [tested to work](https://github.com/ppy/osu-framework/blob/9bbc6a81a2b8f035e2b043d3718d2db6e4f1d868/osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs#L75-L96).

**Comment by peppy** [comment]
The weird part and remaining question then is: why is this happening in the first place? Every usage of `DrawableAvatar` is being loaded using `LoadComponentAsync`, which in general means the drawable should not be part of the `RulesetSkinProvidingContainer` disposal path (contrary to what is shown in the screenshot above).

**Comment by peppy** [comment]
So it's that happening all over again: https://github.com/ppy/osu-framework/pull/5004

This time rather than the TPL thread blocking, the async disposal (single thread) is now the cause of concern.
