### ISSUE TITLE
editor still plays taiko hitsounds on pause screen

### ISSUE THREAD

**Issue by lilaccutie** [ppy/osu#22471]
### Type

Game behaviour

### Bug description

Was going to save a map and noticed that while pausing the game to save changes, it still plays the notes at full volume as the song itself in the background gets muffled. I'm not entirely sure if this is a bug, or a feature so I'm reporting it just to be sure. 

### Screenshots or videos

https://user-images.githubusercontent.com/122637294/215887113-3b78c41d-39d5-4987-b747-b09e1988e2b9.mp4

### Version

2023.123.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/10551179/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10551180/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10551181/updater.log)
[database.log](https://github.com/ppy/osu/files/10551182/database.log)
[input.log](https://github.com/ppy/osu/files/10551183/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10551184/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10551185/network.log)

**Comment by peppy** [comment]
Thanks for your report.

This is basically the best we can do right now without nested mixer support. Also that's not a pause screen but save screen.

Probably not worth tracking this as an issue as it will be resolved along the way with other changes.
