### ISSUE TITLE
Dragging in song select menu causes Debug.Assert to fail

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2249]
This is what Debug.Assert displays to my screen:
![](https://puu.sh/zLdtT/313d28ccf9.png)

This specifically is the line at which the Debug.Assert failed:
![](https://puu.sh/zLdAH/e88e1a7a20.png)

Steps to reproduce: (is kind of troublesome, doesn't always fail for some reason)
- Run lazer
- On the beatmap organization/sorter tool (green options above songs) select any one (I selected author)
- Close and re-run lazer
- Try to drag while holding down in song select quickly

**Comment by Aergwyn** [comment]
Possible duplicate to #1637

**Comment by Frontear** [comment]
@Aergwyn Seems to be, closing.
