### ISSUE TITLE
Default skin needs colour differentiation in judgements

### ISSUE THREAD

**Issue by Express76** [ppy/osu#2251]
After a few months of playing Osu!Lazer one thing that instantly stood out to me was That **300 ,100 and 50** were changed to **Great, Good and meh**. While i prefer this change. The part were all the results were the same color of white and became harder to tell what i was hitting in faster beatmaps .

![lazor now](https://user-images.githubusercontent.com/36247859/37638751-888d0044-2c62-11e8-90bd-276f1b22c1fc.PNG)

From this, changing the colors for each result not only gives a clearer indication of your timing but i feel can also been linked to look good with Lazer's Glowy Bright Colors if done better than my quick 2 min job for stable.

![lazor later maybe](https://user-images.githubusercontent.com/36247859/37638804-d2796814-2c62-11e8-8074-e4db58b67cec.PNG)

I'm sure this has been thought of before but if not, Thoughts?

**Comment by peppy** [comment]
Yep, I agree that colour coding is necessary. Have already brought this up with @arflyte several times over the last year.

**Comment by Frontear** [comment]
I am assuming we don't want to add numerous conditions to [Colour = Judgement.Result == HitResult.Miss ? colours.Red : Color4.White](https://github.com/ppy/osu/blob/3151940435ed216875efe241d875e6c470e969be/osu.Game/Rulesets/Judgements/DrawableJudgement.cs#L51). Perhaps we can introduce a custom attribute [here](https://github.com/ppy/osu/blob/master/osu.Game/Rulesets/Scoring/HitResult.cs,)?
