### ISSUE TITLE
Roll back wrong localisation for "Edit" string 

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#22517]
### Type

Cosmetic

### Bug description

Current localisation for "Edit" string in Russian is right, but the master's isn't.

### Screenshots or videos

Release (right):
![image](https://user-images.githubusercontent.com/86934170/216729450-0ec72b86-7954-45cf-b2c3-02dcb65bd6fc.png)
From this:
![image](https://user-images.githubusercontent.com/86934170/216730064-71c6e9f6-868b-4fc1-94ee-191028148284.png)

Master (wrong):
![image](https://user-images.githubusercontent.com/86934170/216729406-0d2cb102-edf1-43a8-a7f6-148559e98368.png)
From this:
![image](https://user-images.githubusercontent.com/86934170/216730012-ffb60ea2-3fce-4ae2-acb5-c03d8c866f3c.png)

This commit made it wrong https://github.com/ppy/osu/pull/22227/commits/91fbf388da5cfdd6071c5f6f99330634aaa74934

### Version

master

### Logs

-

**Comment by bdach** [comment]
"создать карту" - which google tells me translates to "create a map" - is a questionable translation of "edit" in the first place if you ask me.

**Comment by Loreos7** [comment]
Current translations fits the context. Once https://github.com/ppy/osu/issues/18903 will be implemented translation will be changed.

Even with that I believe this string shouldn't be grabbed from button system because they aren't the same.

**Comment by bdach** [comment]
Looking at crowdin the only languages that seem to have taken the creative liberty of changing the meaning from "edit" to "create beatmap" are Belarusian, Bulgarian, and Russian. All other languages seem to have preserved the meaning of "edit", although whether it is with the correct grammatical form, I cannot say.

I'm not feeling particularly convinced that this should be reverted right now. To me it feels like the aforementioned language translations are taking too many liberties.
