### ISSUE TITLE
Unable to select song on osu!lazer

### ISSUE THREAD

**Issue by foxtail286** [ppy/osu#22522]
### Type

Game behaviour

### Bug description

I was trying to map on mobile, but I was unable to select a song or background image because Lazer did not detect files on Android. I am not sure if this counts as a bug, but it is quite inconvenient.

### Screenshots or videos

`
![Screenshot_20230204-134925](https://user-images.githubusercontent.com/79239522/216784720-90059002-86f2-4374-afc7-738ee0e8d5cd.jpg)
`

### Version

2023.123.0

### Logs

`
[database.log](https://github.com/ppy/osu/files/10609429/database.log)
[network.log](https://github.com/ppy/osu/files/10609430/network.log)
[runtime.log](https://github.com/ppy/osu/files/10609431/runtime.log)
[performance.log](https://github.com/ppy/osu/files/10609432/performance.log)
`

**Comment by bdach** [comment]
#11911
