### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by JakeOpsu2** [ppy/osu#22523]
### Type

Other

### Bug description

Its Me, RJRickJunior, I HAve A Issue When My BEatmap Are Gone, I Installed It, Add Lazer beatmaps To Stable, Ok

### Version

2023.123.0

### Logs

I Take A Break Of Make My Osu Lazer Beatmaps Back,

**Comment by bdach** [comment]
This bug report is not understandable and is missing details. Closing until a clear description of the issue is provided, with logs included.

**Comment by JakeOpsu2** [comment]
ok
