### ISSUE TITLE
osu!lazer is not working normally 

### ISSUE THREAD

**Issue by Exorix56** [ppy/osu#22520]
### Type

Game behaviour

### Bug description

When I run osu!lazer instead of letters, some strange stripes 
Run on Macbook Pro 13 2009 macOS Mojave

### Screenshots or videos

![image](https://user-images.githubusercontent.com/124453299/216777561-f0ef722a-81f7-4432-97c8-1394795a5d92.jpg)

### Version

2023.123.0

### Logs

I don’t have logs

**Comment by Blahajmoder** [comment]
Did you try reinstalling it?

**Comment by Exorix56** [comment]
> Did you try reinstalling it?

so many times

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/9314
