### ISSUE TITLE
lazer only opens if I run it as administrator

### ISSUE THREAD

**Issue by AkiraAkiraxD** [ppy/osu#22530]
### Type

Game behaviour

### Bug description

Hi, I've been playing in osu! lazer for almost a year now but this is the first time I encountered this problem. for some reason it doesn't open unless I run it in administrator mode. Not only that, I can't import new skins and songs but I'm not sure if it has something to do with the administrator mode thing. I'm planning on deleting and reinstalling lazer. Would I be losing every local score and maps or is there a way for me to fix it without reinstalling? Additionally, whenever I right click it and go to properties, this error shows up. (see attached image) I would also encounter errors 

### Screenshots or videos

![image](https://user-images.githubusercontent.com/124269519/216876949-b3f9bdfa-e646-4f15-8a21-72f16c5b7264.png)

### Version

2023.123.0

### Logs

[database.log](https://github.com/ppy/osu/files/10643157/database.log)
[input.log](https://github.com/ppy/osu/files/10643171/input.log)
[network.log](https://github.com/ppy/osu/files/10643178/network.log)
[performance.log](https://github.com/ppy/osu/files/10643185/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10643192/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10643198/updater.log)

**Comment by NotGumballer91** [comment]
Why is the shortcut pointing towards an old version 2022.1008.2?
Did you create a shortcut directly from the folder?

**Comment by Bruno5430** [comment]
Did you also run the installer as administrator? Why is it then in the Admin user directory?

Try to locate the `C:\Users\Admin\AppData\Local\osulazer\` folder (It requires admin privileges) and move it to your user directory at `C:\Users\<your user>\AppData\Local\osulazer\` and fix the shortcut to point at the new location

**Comment by AkiraAkiraxD** [comment]
> 

no the shortcut was made upon downloading lazer

"Try running osu!.exe from C:\Users\Admin\AppData\Local\osulazer\" - I tried it but it still wont open, I opened task manager hoping that maybe it did open but not showing on screen but to no avail.

**Comment by AkiraAkiraxD** [comment]
no I didnt run the installer as an administrator. I am the admin of this pc and there are no other users logged in here so there is only one user folder here. If this problem still persists then maybe reinstalling is my only option.

**Comment by Bruno5430** [comment]
Try checking for the permissions of the osulazer folder in the Security tab on the properties of the folder
![2023-02-07_10-27](https://user-images.githubusercontent.com/111712756/217258010-3e01a70d-ea79-4466-ac56-6ff3748b9f95.png)

**Comment by AkiraAkiraxD** [comment]
![image](https://user-images.githubusercontent.com/124269519/217283497-b01b422e-8757-4e9e-b4c9-a9ad624b0b83.png)

**Comment by AkiraAkiraxD** [comment]
1.

**Comment by Bruno5430** [comment]
Try backing up the `osulazer` folder and reinstall it to see if the issue persist

**Comment by AkiraAkiraxD** [comment]
Are local scores included in the osu lazer folder or is there a separate folder for it. Local scores set in lazer, not local scores imported from standard

**Comment by AkiraAkiraxD** [comment]
uhh ok so I deleted it but now it doesn't want to install
![image](https://user-images.githubusercontent.com/124269519/217419955-3141e93f-b29e-40c6-8d0f-1d36d8567ed7.png)

**Comment by AkiraAkiraxD** [comment]
.

**Comment by Bruno5430** [comment]
pls provide the log mentioned at the end of the dialog

**Comment by AkiraAkiraxD** [comment]
the squirrel log?

**Comment by AkiraAkiraxD** [comment]
[Squirrel.log](https://github.com/ppy/osu/files/10681362/Squirrel.log)

**Comment by Bruno5430** [comment]
It seems like the installation folder has very messed up permissions or something, as the logs mention
`2023-02-08 11:09:12.1930 [ERROR] - ApplyReleasesImpl: Failed to run cleanup hook, continuing: C:\Users\Admin\AppData\Local\osulazer\app-2023.123.0\osu!.exe: System.ComponentModel.Win32Exception (740): An error occurred trying to start process 'C:\Users\Admin\AppData\Local\osulazer\app-2023.123.0\osu!.exe' with working directory 'C:\Windows\system32'. The requested operation requires elevation.`

Try uninstalling lazer AND check if the `osulazer` folder actually gets removed (local scores and other user data is not located there, it's located at `%appdata%/osu/files`, see [File storage in osu!(lazer)](https://osu.ppy.sh/wiki/en/Client/Release_stream/Lazer/File_storage) )
If not, remove it manually and try again

**Comment by Bruno5430** [comment]
Also, this issue is very likely a duplicate of other issues like #20973 but i can't really do too much about it, I just wanted to help

**Comment by AkiraAkiraxD** [comment]
![image](https://user-images.githubusercontent.com/124269519/217432052-e9846cb7-22ac-4a79-bed2-4f0e1ab884b1.png)

nope the issue is still here
[Squirrel.log](https://github.com/ppy/osu/files/10681593/Squirrel.log)

I attached the log again, but if there really is nothing for me to do, then so be it. I just have one last question, can I view lazer local scores on standard or no?

**Comment by AkiraAkiraxD** [comment]
Just to follow up, I did it again today and it worked, somehow. Thank you for your guidance my lazer is now fixed xD

**Comment by DavidElwood** [comment]
I had the same problem, but I found a solution:

I copy-pasted folder that's from C:\Users\Hello\AppData\Local\**osulazer** to C:\Users\Hello\AppData\**Roaming**.

Plus if you're using start menu and typed in osu!(lazer) ;open it's file location and make a shortcut of the exe you copy-pasted previously with in the folder, replace shortcut with the exe that's in C:\Users\Hello\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\**ppy Pty Ltd** and just rename it same and everything is good to go! 

(hopefully you'll understand what I typed as english isn't my first language)
