### ISSUE TITLE
Error when fail or win with accuracy challenge enabled

### ISSUE THREAD

**Issue by Niterux** [ppy/osu#22548]
### Type

Game behaviour

### Bug description

When you enable the accuracy challenge mod and then fail or win a map you will get an error notification.,

It says "Failed to submit score (unknown setting for AC (minimum_accuracy)) This error has been automatically reported to the devs", in the video it says "Failed to submit score (invalid mod for ruleset: AC) This error has been automatically reported to the devs." So I guess it varies.

### Screenshots or videos

https://user-images.githubusercontent.com/110568869/217489413-4554c120-7e18-4a27-9ab3-e929c084ee35.mp4

![Screenshot_20230208_040855](https://user-images.githubusercontent.com/110568869/217489490-e4d3b81b-62db-454b-bd99-9ac0868b8e4e.png)

### Version

2023.207.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/10683840/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10683841/updater.log)
[database.log](https://github.com/ppy/osu/files/10683842/database.log)
[input.log](https://github.com/ppy/osu/files/10683843/input.log)
[network.log](https://github.com/ppy/osu/files/10683844/network.log)
[performance.log](https://github.com/ppy/osu/files/10683845/performance.log)

**Comment by bdach** [comment]
Fix has been merged, but I'll keep this open until deploy happens as I still see these on sentry.

**Comment by Niterux** [comment]
Was this fixed? I do not get errors anymore, also I do not know what sentry is because I am new to this.

**Comment by bdach** [comment]
The web-side fix has been deployed. Closing.
