### ISSUE TITLE
Skin editor overwrites gameplay layout after being opened during map with a legacy beatmap skin

### ISSUE THREAD

**Issue by bdach** [ppy/osu#22561]
### Type

Game behaviour

### Bug description

1. Have a triangles / argon skin that you applied customisations to
2. Enter gameplay in a map that has a legacy beatmap skin
3. Open skin editor and close it
4. Exit gameplay
5. "Skin saved" toast will show
6. Re-enter gameplay on map without beatmap skin
7. Original skin layout will be mangled

### Screenshots or videos

https://user-images.githubusercontent.com/20418176/217614365-855c6fd8-e4cd-44ab-90c7-ff44d71b7239.mp4

### Version

current master

### Logs

\-

**Comment by peppy** [comment]
This seems pretty bad. Although I'm wondering what the expectation here is – should a beatmap level skin ever be allowed to change the *layout* of the HUD? That seems wrong no?
