### ISSUE TITLE
Mania skin broke after "basic support for stupidly long hold note skin textures"

### ISSUE THREAD

**Issue by Bruno5430** [ppy/osu#22572]
### Type

Cosmetic

### Bug description

from #22389 
> I **am** interested if anyone finds a skin which doesn't use stupid-long textures and gets broken/affected by this change.

My personal skin uses hold note textures of 158x32 (which isn't "stupidly large") that has a color gradient, but it doesn't show anymore after the update, it's just one solid color now

Skin: [' Night05 [minimal] (Bruno543's FNF edit).zip](https://github.com/ppy/osu/files/10698566/Night05.minimal.Bruno543.s.FNF.edit.zip)

### Screenshots or videos

Version:  2023.123.0
![osu_2023-02-09_00-20-08](https://user-images.githubusercontent.com/111712756/217715117-242cdb2c-7732-4472-9984-878a0f005f5c.png)

Version: 2023.207.0
![osu_2023-02-09_00-24-20](https://user-images.githubusercontent.com/111712756/217715304-e009280c-0fb4-47fa-a21f-3a2dd08ff695.png)

### Version

2023.207.0

### Logs

-

**Comment by peppy** [comment]
An aside, but how do you use this skin?

![Parallels Desktop 2023-02-09 at 10 16 46](https://user-images.githubusercontent.com/191335/217784367-8defe510-875b-4422-96c9-fe0d1c97227e.png)

**Comment by peppy** [comment]
No worries. I've identified the issue with the version you attached so it worked fine.

**Comment by yuuiko** [comment]
Plus one for this issue and gradients too.

Before:
![Screenshot_2023-02-05_at_3 51 44_pm](https://user-images.githubusercontent.com/50823728/218213733-1ea37f7a-6911-4b53-b79a-9c3574e86e3b.png)
![Screenshot_2023-02-05_at_3 58 45_pm](https://user-images.githubusercontent.com/50823728/218213747-485becea-d1e6-4eaf-a8e3-7bc1a95c1c73.png)

After:
<img width="1897" alt="Screenshot 2023-02-11 at 9 31 39 am" src="https://user-images.githubusercontent.com/50823728/218213766-2b3a8d52-46ca-4285-ae09-4e2e3db529ba.png">


Sprite:
![mania-note1L@2x](https://user-images.githubusercontent.com/50823728/218214065-1d19f26b-df4f-4edc-99dc-28df22c083cc.png)

Skin:
https://drive.google.com/file/d/15AENfcJFCwq7jlOb1wlgB65tY8nMMHuO/view?usp=share_link

**Comment by peppy** [comment]
I've tested the skin above on the new PR and it does look correct now.
