### ISSUE TITLE
Updating beatmap to online version duplicates both `Beatmap` and `BeatmapSet`

### ISSUE THREAD

**Issue by Cootz** [ppy/osu#22579]
### Type

Game behaviour

### Bug description

Game duplicates both `Beatmap` and `BeatmapSet` while updating to online version. New `BeatmapSet` is available to user, old one is not, but both of them are storing into realm.

Steps to reproduce:
1. Edit `Beatmap` and save it
1. Update `BeatmapSet`
1. (Optional) look up `Beatmap` and `BeatmapSet` in the realm database

### Screenshots or videos

`Beatmap`:
![image](https://user-images.githubusercontent.com/50776304/217849237-76ba2078-f9fb-48b4-bee4-55c06378c3d6.png)
`BeatmapSet`:
![image](https://user-images.githubusercontent.com/50776304/217851734-312f1252-4f8c-4c9e-999f-e4e8bcc9c106.png)
`Score`:
![image](https://user-images.githubusercontent.com/50776304/217848625-a0b13195-c0e1-44d9-a773-f6db2d94be41.png)

### Version

master (up to merge #22566 )

### Logs

Not needed

**Comment by peppy** [comment]
This is intended. Check the `DeletePending` column.

It is done this way to keep things simple, and to allow restoring the edited version (or potentially having it exist alongside the original).

https://github.com/ppy/osu/blob/de079e08dcbe845e4e8b944a5beabeb875033755/osu.Game/Beatmaps/BeatmapImporter.cs#L73-L77
