### ISSUE TITLE
Skin behavior discrepancy between Lazer and stable.

### ISSUE THREAD

**Issue by blockmakerpedi** [ppy/osu#22585]
### Type

Game behaviour

### Bug description

There are a lot of differences when playing the skin on lazer vs playing the skin on stable. 
the main issue here is that the circles look different,  sliders should not have slider end circles, 300s should not be visible, and the cursor should not have a trail.

Mania also has some problems, namely little bars between notes, hit lighting even when it is turned off in settings, and rainbow 300s showing up as judgments even though they should not appear.

here is the skin in question:
[Redageddonss_Circle_Skin_v5_Achromatic.zip](https://github.com/ppy/osu/files/10700619/Redageddonss_Circle_Skin_v5_Achromatic.zip)

### Screenshots or videos

Lazer view:

https://user-images.githubusercontent.com/43874888/217905090-991af221-5282-49ae-8cef-cb79d25933e3.mp4

Stable view:

https://user-images.githubusercontent.com/43874888/217905385-d419c807-d1d5-4700-a4ba-cfd62574c105.mp4

Lazer mania view:

https://user-images.githubusercontent.com/43874888/217909900-ef814d09-97b6-4e50-ba95-e9bd261771a1.mp4

Stable maina view:

https://user-images.githubusercontent.com/43874888/217912601-8f5c2f1e-f3d2-4029-bf13-9c177ed2637e.mp4

### Version

2023.207.0

### Logs

[database.log](https://github.com/ppy/osu/files/10700641/database.log)
[input.log](https://github.com/ppy/osu/files/10700642/input.log)
[network.log](https://github.com/ppy/osu/files/10700643/network.log)
[performance.log](https://github.com/ppy/osu/files/10700644/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10700645/runtime.log)

**Comment by Redageddon** [comment]
There isnt a skin problem here thats is the fault of lazers. I used a broken transparent png in stabe that just happened to not work in lazer as well, and blockmaker posted in my behalf without asking. The probelm here is resolved.

**Comment by blockmakerpedi** [comment]
I still do noth think it is resolved as the feature discrepency is still there. I think we should leave it up to the devs to see wether or not this is a missing lazer parity or user error.

**Comment by peppy** [comment]
- Don't use "latest" as a skin version. It won't work. This should never be used in distributed skins.
- The PNG being used for `sliderendcircle` is corrupt and not able to be read by either of our PNG libraries. If it was just one out of two failing, I'd consider making an exception, but nope. Use valid PNG please.

![JetBrains Rider-EAP 2023-02-10 at 09 25 32](https://user-images.githubusercontent.com/191335/218054313-d27f6311-5b79-4583-bb48-fec59e7063fc.png)

![JetBrains Rider-EAP 2023-02-10 at 09 24 18](https://user-images.githubusercontent.com/191335/218054008-f9c02da4-dca4-4d02-9982-e27cbf2cba21.png)


As for mania issues, I don't know. Open a new issue with better defined scope.
