### ISSUE TITLE
Song select screen black - 'play' button crashes game

### ISSUE THREAD

**Issue by BagelGamerz** [ppy/osu#226]
![image](https://cloud.githubusercontent.com/assets/12241556/20947188/fcafa28e-bc05-11e6-8082-28ae1cdbbbef.png)
![image](https://cloud.githubusercontent.com/assets/12241556/20947191/02aa98ba-bc06-11e6-9c62-1e0f9241a82c.png)

**Comment by FayneAldan** [comment]
Lazer doesn't use the same folder as release, so it doesn't load the beatmaps you have for release. You have to give it beatmaps by dragging a beatmap file onto osu!.exe (it may also work to drag it onto the game window, but I haven't tried it).
