### ISSUE TITLE
Reduce glow amount slider and triangle animation toggle

### ISSUE THREAD

**Issue by lanes100** [ppy/osu#2260]
I've noticed that lazer has a very "glowy" style to it, and while it does look nice, it is sometimes hard to discern between notes, which is not an issue on stable. I just think the glow effect should have a slider so you can turn it down and so that the circles are a bit easier to see. They are really an eye burner right now to say the least and I just think it would be a nice addition. 
On the same note, I also think there should be an option to remove the triangles/animations from the circles and sliders, for people with lower end machines (assuming this feature uses a decent amount of processing power), and for people who would just prefer without.

**Comment by peppy** [comment]
I'd rather fine-tune it to be a good default than provide toggles.

**Comment by lanes100** [comment]
Fair enough

**Comment by smoogipoo** [comment]
Closing as this is a very out of date issue and gameplay will be iterated on in the future, once we get more into a release-able state.
