### ISSUE TITLE
Background Blur not working on storyboards

### ISSUE THREAD

**Issue by BuySharp** [ppy/osu#22612]
### Type

Cosmetic

### Bug description

When messing with background blur, I found that it doesn't work if there is a storyboard/video backgrounds. The blur is always at 0% no matter what the blur setting is set to.

### Version

2023.207.0-lazer

### Logs

N/A

**Comment by ColdVolcano** [comment]
Intended. Currently not possible due to performance concerns.

See #13001

**Comment by BuySharp** [comment]
> Intended. Currently not possible due to performance concerns.
> 
> See #13001

My mistake, didn't know it was intentional. Thanks for letting me know
