### ISSUE TITLE
Setup wizard cutting off text in Japanese

### ISSUE THREAD

**Issue by IcedDog** [ppy/osu#22625]
### Type

Cosmetic

### Bug description

The setup wizard will cut off text in Japanese. I don't think this is a duplicate of #15452, since this doesn't happen in any other language.

### Screenshots or videos

![06cf3051229654f9ecf73596d0a4b26](https://user-images.githubusercontent.com/34804287/218350541-058e2332-bbd8-49c3-bd22-8386db9d721d.png)
![2d4a478dee2dbbfbeba208d265e11ce](https://user-images.githubusercontent.com/34804287/218350545-fc2f240e-02e5-4691-a15a-9fed7baa84ba.png)
![b7678d76bd503b196f60872090a44ba](https://user-images.githubusercontent.com/34804287/218350547-9874433d-b706-42c5-a8a8-11c6ced42232.png)

### Version

2023.207.0

### Logs

Not applicable

**Comment by Joehuu** [comment]
Your comment about settings in https://github.com/ppy/osu/discussions/15452#discussioncomment-4952361 is the same problem, so both places will be fixed with the same code changes, closing.
