### ISSUE TITLE
Importing a skin doesn't select it automatically

### ISSUE THREAD

**Issue by Bruno5430** [ppy/osu#22623]
### Type

Game behaviour

### Bug description

As title says, not even when clicking on the import notification will select the skin automatically like stable does

### Screenshots or videos

Lazer behaviour:

https://user-images.githubusercontent.com/111712756/218330271-478854a3-770e-4b4c-b97b-bb4411a78ed8.mp4

Stable behaviour:

https://user-images.githubusercontent.com/111712756/218330311-cd30b75b-fd22-4b40-9233-31d9a340a25b.mp4

### Version

2023.207.0

### Logs

-

**Comment by Cootz** [comment]
I don't think it needs to be selected automatically tbh. It's not fitting well with the multiple import feature. Adding `click on import notification to select the skin` is a good idea tho

**Comment by Theighlin** [comment]
> It's not fitting well with the multiple import feature.

We could just not do it on when multiple skins are imported?
(Though iirc when importing multiple maps in both stable and lazer you are brought to the last added one?)

When importing a single skin, i am probably gonna play with it, or now in lazer edit it, either way i would like for it to be selected.

**Comment by Cootz** [comment]
Should be ok now

https://user-images.githubusercontent.com/50776304/218452093-91439a80-8383-4826-b6cc-596d5e2cac27.mp4

**Comment by Bruno5430** [comment]
> We could just not do it on when multiple skins are imported?
(Though iirc when importing multiple maps in both stable and lazer you are brought to the last added one?)

Well, in stable It doesn't seem to be able to import multiple skins at once (see video in op).
But yeah, importing multiple beatmaps in both clients will redirect you to the last imported one (lazer will when clicking on the "Imported X beatmaps! Click to view.")
![2023-02-13_11-26](https://user-images.githubusercontent.com/111712756/218485843-a3f24a74-4bed-477f-9e39-0e5f24a835ca.png)

> Should I PR this?

I think It should follow the behaviour of importing beatmaps, because if you import multiple skins then this notification would be misleading if the skin doesn't change (or at least bring the skin selection menu)
![2023-02-13_11-36](https://user-images.githubusercontent.com/111712756/218486885-d2e91326-db9c-4301-a1dc-babda842de27.png)
