### ISSUE TITLE
Is this a glitch or a game breaking bug?

### ISSUE THREAD

**Issue by ParaliyzedEvo** [ppy/osu#22626]
### Type

Other

### Bug description

I was scrolling through my maps and saw that. Idk how or what they did, but they only had to hit one circle on the map. That was a enough to get number 1 and number 2 spots. Since osu!lazer doesn't really have a pp system yet I don't this should a priority. But if this bug can be done on other maps I think it should be fixed ASAP. 
Map: https://osu.ppy.sh/beatmapsets/742961#osu/1816113

### Screenshots or videos

![image](https://user-images.githubusercontent.com/107338855/218362937-d64f2b22-5c2b-40d3-8233-7ff830e756b8.png)

### Version

2023.207.0

### Logs

[performance.log](https://github.com/ppy/osu/files/10718318/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10718319/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10718320/updater.log)
[database.log](https://github.com/ppy/osu/files/10718321/database.log)
[input.log](https://github.com/ppy/osu/files/10718322/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10718323/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10718324/network.log)

**Comment by Axilotl17** [comment]
Right now leaderboards for lazer are still being worked out, and many leaderboard resets will probably come.

**Comment by Theighlin** [comment]
This issue is already fixed, players can't do it anymore.
Lazer leaderboards are likely to be reset soon anyway.

**Comment by Joehuu** [comment]
As said here, [the download page](https://osu.ppy.sh/home/download), and [the wiki page](https://osu.ppy.sh/wiki/Help_centre/Upgrading_to_lazer), leaderboard resets are expected for users who play lazer for now.
