### ISSUE TITLE
Сannot determine the refresh rate of the monitor.

### ISSUE THREAD

**Issue by MikelvGP** [ppy/osu#22665]
### Type

Performance

### Bug description

The game runs at a stable frequency of 60 Hz in full-screen mode, when my monitor was overclocked to 70 Hz using the Nvidia driver. Twitching occurs. It is solved when the mode is "in the window", but there is a delay.

### Screenshots or videos

FullScreen.
![image](https://user-images.githubusercontent.com/74131227/219362660-05236cbb-0e70-4c4d-b1fb-da535bf39db3.png)
Windowed.
![image](https://user-images.githubusercontent.com/74131227/219362765-aa8dcb8b-703d-43aa-8520-021ac16fe231.png)

### Version

2023.207.0

### Logs

[input.log](https://github.com/ppy/osu/files/10755860/input.log)
[network.log](https://github.com/ppy/osu/files/10755861/network.log)
[performance.log](https://github.com/ppy/osu/files/10755862/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10755863/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10755864/updater.log)
[database.log](https://github.com/ppy/osu/files/10755865/database.log)

**Comment by bdach** [comment]
> It is solved when the mode is "in the window", but there is a delay.

The game throttles all threads to 60 Hz when the window is inactive (is not focused, the mouse is not inside it). This is intentional.

**Comment by MikelvGP** [comment]
> The game throttles all threads to 60 Hz when the window is inactive (is not focused, the mouse is not inside it). This is intentional.

But the window is in an active state. That's the whole problem. The whole game runs at 60Hz, regardless of any other factors other than the fact whether the game is in "Fullscreen mode" or in "windowed" mode, or "Borderless".

**Comment by bdach** [comment]
Then I don't understand what you're trying to report, sorry. Please attach an actual video of this or something.

**Comment by MikelvGP** [comment]
> Then I don't understand what you're trying to report, sorry. Please attach an actual video of this or something.

https://www.youtube.com/watch?v=jqfF2w9fiPg

**Comment by bdach** [comment]
That is a duplicate of https://github.com/ppy/osu-framework/issues/4081, then.
