### ISSUE TITLE
Lag And Auto Reset Settings

### ISSUE THREAD

**Issue by JakeOpsu2** [ppy/osu#22661]
### Type

Other

### Bug description

The Bug Means If You Play Osu! On A Old Or Legacy Laptop, It Will Lag, If You Know When The Settings Gonna Reset Automatically In It...

### Version

b20230206

### Logs

...

**Comment by bdach** [comment]
Performance is a constant work in progress. And I don't know what "auto reset settings" is supposed to mean.
