### ISSUE TITLE
Skin import adds redundant information to skin.ini

### ISSUE THREAD

**Issue by rozukke** [ppy/osu#22681]
### Type

Game behaviour

### Bug description

During skin import, `SkinImporter` writes Name and Author fields to `skin.ini` regardless of them already existing, leading to strange cases like the linked image. In these cases, instead of grabbing the actual skin name that is specified at the top of the file, exports, deletions and sequential re-imports lead to the name being nested within itself and written to the end of `skin.ini` again leading to mangled names.

This should be a very short fix where a check for existing metadata occurs before calling `updateSkinIniMetadata`, and I can PR it myself if that is necessary.
https://github.com/ppy/osu/blob/6b1c8195bcba6eb3af2e1836d0799ff9e061f8c2/osu.Game/Skinning/SkinImporter.cs#L111-L112

### Screenshots or videos

![image](https://user-images.githubusercontent.com/73006620/219867734-e8882c0d-5d9e-4dee-92c3-68479af8a6b1.png)

### Version

2023.207.0

### Logs

[updater.log](https://github.com/ppy/osu/files/10774326/updater.log)
[database.log](https://github.com/ppy/osu/files/10774327/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10774328/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10774329/network.log)
[performance.log](https://github.com/ppy/osu/files/10774330/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/10774331/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10774332/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10774333/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10774334/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10774335/runtime.log)

**Comment by bdach** [comment]
The thing that is directly triggering this behaviour is the weird characters in the filename being stripped by [`GetValidFilename()`](https://github.com/ppy/osu/blob/ff5de04fb1587e9d1cf59fba150b8ffdb8f692e1/osu.Game/Extensions/ModelExtensions.cs#L142-L150) on export, which on re-import will never allow [this check](https://github.com/ppy/osu/blob/ff5de04fb1587e9d1cf59fba150b8ffdb8f692e1/osu.Game/Skinning/SkinImporter.cs#L111) to succeed. But the linked PR is clearly not the right way to go about it either as it fails several existing tests.

**Comment by Cootz** [comment]
>After switching to realm it can be moved into another place.

Guess [it's](https://github.com/ppy/osu/blob/ff5de04fb1587e9d1cf59fba150b8ffdb8f692e1/osu.Game/Skinning/SkinImporter.cs#L108-L112) legacy code now.  What does this check even prevent?

**Comment by bdach** [comment]
It is not "legacy code". It *may* need to be structured better, but it's there for a clear, specific, and continuing purpose. As I said in the PR thread, please read https://github.com/ppy/osu/pull/14465 / https://github.com/ppy/osu/pull/15406 for context

**Comment by Cootz** [comment]
Still not sure about it. If import metadata name [depends](https://github.com/ppy/osu/blob/ff5de04fb1587e9d1cf59fba150b8ffdb8f692e1/osu.Game/Skinning/SkinImporter.cs#L108-L112) on filename and export filename [depends](https://github.com/ppy/osu/blob/ff5de04fb1587e9d1cf59fba150b8ffdb8f692e1/osu.Game/Database/LegacyExporter.cs#L37) on metadata name, why metadata name can be any length? Filenames have some [limitations](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits), but metadata name doesn't. In addition to this we overwrite some symbols that prohibited in file naming, which is duplicating skins by default.

**Comment by bdach** [comment]
I'm not sure what name length has to do with it, and I'm not sure what "duplicating skins by default" means. Prohibited symbols (which is also done due to *filename limitations*) is done on export only.

**Comment by rozukke** [comment]
This seems to be a lot more annoying of an issue than anticipated and I can't think of any way to determine whether or not a skin has been previously imported without using regex (which I assume is pretty undesirable to use in this situation) or breaking the very specific set of tests. For now I'm going to leave the issue unless I magically think of something.
