### ISSUE TITLE
Scroll containers get into a weird scroll state

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2269]
Usually happens after startup and eventually resolves itself.

https://streamable.com/zomot

I'm not doing anything but dragging and releasing in that video.

**Comment by bdach** [comment]
Do you remember any more context to this at all? I can't see this happening anywhere and I don't recall ever seeing anything like that either. Tortured a few scrolling containers to no avail, too.

**Comment by peppy** [comment]
I've actually triggered this quite recently. It has to be something related to clocks or frame rate, and I believe it's a framework-level fix that is required to fix it.

**Comment by peppy** [comment]
I haven't seen this happen in recent times. It used to be *very* common, so it's probably safe to say it has been fixed.
