### ISSUE TITLE
Username not showing correctly

### ISSUE THREAD

**Issue by Abchrisabc** [ppy/osu#227]
When logging in on the newest release the username doesn't show correctly on the top right side.

https://puu.sh/sH3Z0/6919056b19.png

**Comment by peppy** [comment]
would appreciate if you can debug as to why it isn't

**Comment by Abchrisabc** [comment]
Upon restarting it correctly showed, I am trying to reproduce it another time but so far no luck.

**Comment by Abchrisabc** [comment]
The Username part only happens when the game.ini file doesn't exist.

Also the debug messages are sometimes not showing correctly:
https://puu.sh/sH5nK/06d6e11b41.png

**Comment by peppy** [comment]
is it permanent? ie. if you logout then log back in does it fix itself?

**Comment by Abchrisabc** [comment]
Is the game.ini file exists and you logout and back in (even with restarts) it shows correctly.

**Comment by Abchrisabc** [comment]
So I just imported the first beatmap and Noticed that also on the beatmaps there are problems. https://youtu.be/bkwfJWpk9Bc Also in this play there were no accuracy numbers (50, 100, 300) which do show some times but still random.

**Comment by peppy** [comment]
Unless you're willing to figure out why and fix, this is not worth reporting yet sorry.
