### ISSUE TITLE
It's possible to cheat using modified ruleset dll's

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#22707]
### Type

Game behaviour

### Bug description

As per title. You can modify ruleset dll's and replace original ones in the game without being noticed.
Examples: transparent FL, auto hitobjects, etc.
I'm pretty sure team is aware of that, just couldn't find any related issues.

### Version

master

### Logs

N/A

**Comment by peppy** [comment]
Yes, anti-cheat has not yet been implemented. It will arrive soon.
