### ISSUE TITLE
Notes appearing with wind-up mod

### ISSUE THREAD

**Issue by TheRealSuper678** [ppy/osu#22733]
### Type

Game behaviour

### Bug description

When trying out the wind up mod (1.0x - 1.3x) on [scrap syndrome](https://osu.ppy.sh/beatmapsets/1715644#mania/3505666), there were 2 occurances of this issue, same pattern.

This issue did not happen without the wind up mod.

### Screenshots or videos

https://user-images.githubusercontent.com/84391906/221287723-2a027242-d3c2-430e-90f3-916c2aa7f606.mp4

### Version

2023.207.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10828643/database.log)
[input.log](https://github.com/ppy/osu/files/10828644/input.log)
[network.log](https://github.com/ppy/osu/files/10828645/network.log)
[updater.log](https://github.com/ppy/osu/files/10828648/updater.log)
[runtime.log](https://github.com/ppy/osu/files/10828647/runtime.log)
[performance.log](https://github.com/ppy/osu/files/10828646/performance.log)

**Comment by Axilotl17** [comment]
for those who don't understand the issue, in the leftmost column? (i dont know the name) a note appears right before you were supposed to click it instead of falling from offscreen like the other notes.
