### ISSUE TITLE
Input events don't propagate to SettingsOverlay when the NotificationsOverlay is open

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu#2273]
https://streamable.com/skds4

Doesn't seem like it is intended.

**Comment by Frontear** [comment]
I think this has something to do with the layers. The latest added drawable is given input priority. Wonder if that can be fixed

**Comment by FreezyLemon** [comment]
Found the issue:
Since `NotificationOverlay` and `SettingsOverlay` are both `OverlayContainer`s, they both try to remove all drawables behind them from the mouse input queue. This means that just because the `NotificationOverlay` is added later, it removes the `SettingsOverlay` and makes it not receive input.

But this also opens up another question: How to handle multiple `OverlayContainer`s like this?
We can't change `BlockScreenWideMouse` or `BlockPassThroughMouse` since that will make the overlays not close when clicking outside of them (and we also want to block the drawables behind both overlays to not get input while having both overlays receive it).

**Comment by peppy** [comment]
I'm not sure of the "correct" way to solve this (`IHandleGlobalInput` plus some limiting of `ReceiveMouseInputAt`, most likely).

It was decided a while back that only one should be visible at a time, so we're going with that for now.
