### ISSUE TITLE
Creating a new difficulty, renaming, then deleting it and continuing the editing process causes errors

### ISSUE THREAD

**Issue by hburn7** [ppy/osu#22783]
### Type

Game behaviour

### Bug description

After creating a new difficulty, renaming it, then deleting it, selecting a certain set of menu items can lead to strange behavior. The editor also tries to delete a different difficulty after going back and trying to delete again.

### Screenshots or videos

https://user-images.githubusercontent.com/38370573/222838183-f1b81237-7445-4801-9c38-cfd84df2e22b.mp4

### Version

2023.301.0

### Logs

[input.log](https://github.com/ppy/osu/files/10886437/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10886438/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10886439/network.log)
[performance.log](https://github.com/ppy/osu/files/10886440/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10886441/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10886442/updater.log)
[database.log](https://github.com/ppy/osu/files/10886443/database.log)

**Comment by Halo-nm** [comment]
@hburn7 Could you expand a bit on what the resulting "strange behavior" is beyond the unhandled error pop-up? Is the re-deleted attempt the only noticeable breakage? Does restarting the application clear the issue up?

**Comment by hburn7** [comment]
> @hburn7 Could you expand a bit on what the resulting "strange behavior" is beyond the unhandled error pop-up? Is the re-deleted attempt the only noticeable breakage? Does restarting the application clear the issue up?

Sure. The main issue is that deleting a difficulty should probably take you back to the song select screen (or some other behavior) rather than do what it does now. It seems to me like the game tries to keep the user in the editor but on a different difficulty if there is one. It isn't obvious to the user that the difficulty was deleted. And then of course errors arise if an attempt is made at deleting the difficulty the game says you can delete as shown in the video.

There shouldn't be an option to discard changes after deleting a difficulty because that implies you can undo the deletion.
