### ISSUE TITLE
"Esc" button doesn't work after login

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#228]
If I press "log in" button with empty fields - It's okay, But even with wrong login/pass after login fail it becames non-working.

**Comment by peppy** [comment]
this is due to focus not being removed from the textbox when it is disposed. needs to be fixed at a framework level.

**Comment by EVAST9919** [comment]
How about just call .TriggerFocusLost() for username and password textboxes in performLogin()?

**Comment by EVAST9919** [comment]
Oh, or right in Dispose function? It worked
