### ISSUE TITLE
Pause loop isn't updated if skin is changed during loading screen

### ISSUE THREAD

**Issue by PillTime** [ppy/osu#22817]
### Type

Cosmetic

### Bug description

As the title says: if a skin is changed during the loading screen of a beatmap, the pause loop sample doesn't update and the previous skin's pause loop is used instead. There might be more elements that don't get updated, but the pause loop is the only one I noticed.

### Screenshots or videos

https://user-images.githubusercontent.com/2399664/223893501-f61afa91-a77b-4986-a3ab-41229192e4e3.mp4

### Version

2023.305.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10926845/database.log)
[input.log](https://github.com/ppy/osu/files/10926846/input.log)
[network.log](https://github.com/ppy/osu/files/10926847/network.log)
[performance.log](https://github.com/ppy/osu/files/10926848/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/10926849/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10926850/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10926851/runtime.log)

**Comment by peppy** [comment]
If this is true, it's quite worrying (means there's something wrong at a `SkinnableSound` level).

**Comment by PillTime** [comment]
Can confirm that the fail sound sample has the same issue.
Also, pausing, unpausing, and pausing for a second time fixes the issue for the pause loop (the fail sound sample only gets fixed after retrying the map).

**Comment by Terochi** [comment]
Turns out this happens even when changing the skin directly in game while not having the pause screen shown. The skin sample update happens only when the pause screen is opened, which is too late because the previous sample starts playing by then.
