### ISSUE TITLE
2018.322.0 Won´t Start at all.

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#2281]
Since the new update osu! lazer refuses to start at all and there are no logs what so ever 
Windows 10 x64
I3 6100
GTX 1050 Ti 
8GB Ram

**Comment by peppy** [comment]
Did you try the new update? This was released a second time with fixes for the previous crashes.

**Comment by Lolihunter1337** [comment]
yea

**Comment by peppy** [comment]
Going to require runtime.log or equivalent debug output.

**Comment by Lolihunter1337** [comment]
i cannot get a runtime.log since there is none. i can try to get an equivalent debug output however im not sure what exactly how / with what

**Comment by Lolihunter1337** [comment]
im installing Visual Studio Right now. all i can see is that its showing up in the Task Manager for arround 1-2 seconds and then its closing / vanishing

**Comment by peppy** [comment]
Rather than installing visual studio, you can probably check your "event viewer" log under Applications. There should be a logged error (or two) related to osu! crashing.

**Comment by Lolihunter1337** [comment]
[NET Runtime.txt](https://github.com/ppy/osu/files/1837862/NET.Runtime.txt)

i might as well include the Application error 
[Application.txt](https://github.com/ppy/osu/files/1837864/Application.txt)

**Comment by MosheBarkan** [comment]
for me its not starting since (I think,..) a month ago 
[OsuError.txt](https://github.com/ppy/osu/files/1838772/OsuError.txt)

**Comment by Lolihunter1337** [comment]
Downloaded newest Update and got the 
[runtime.log](https://github.com/ppy/osu/files/1844145/runtime.log)
 now

**Comment by peppy** [comment]
Which skin are you using?

**Comment by Lolihunter1337** [comment]
I have no idea which were it. is there are a way i can look which skin is selected?

**Comment by peppy** [comment]
That's fine, the runtime.log gives enough information for us to resolve this one. Thanks!

**Comment by Lolihunter1337** [comment]
No Problem :)

**Comment by peppy** [comment]
Closing in favour of #2306.

**Comment by IIILanceIII** [comment]
on the update 2018.910.0. when i open the osu!lazer  Application. it does nothing. what should i do?
