### ISSUE TITLE
Sliders confused about their speed

### ISSUE THREAD

**Issue by ZWORX52** [ppy/osu#22813]
### Type

Game behaviour

### Bug description

I was mapping/mostly messing around in the editor, and I noticed that after changing a slider speed multiplier from 4.0x to 2.0x, the slider seemed to

1. disappear when it would have if it were 4.0x speed
2. reappear just before finishing as if it remembered that it should exist
3. disappear again, this time when it should have

I should note that the slider "ball" moved at 2.0x speed, and the slider appeared as I would expect it to in the editor timeline.

It's a bit difficult to see in the video because it also seems to cause lag, but it doesn't lag like that to me when editing (perhaps it's just a recording error, if a better recording is necessary I will try)

### Screenshots or videos

https://user-images.githubusercontent.com/66217856/223586744-2c78e6d2-798b-4057-807b-a0eb1a59c732.mp4

### Version

2023.305.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10915169/database.log)
[input.log](https://github.com/ppy/osu/files/10915170/input.log)
[network.log](https://github.com/ppy/osu/files/10915171/network.log)
[performance.log](https://github.com/ppy/osu/files/10915172/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10915173/runtime.log)

**Comment by Axilotl17** [comment]
#22698

**Comment by ZWORX52** [comment]
Related or duplicate?

**Comment by bdach** [comment]
99% will have the same cause. Closing as duplicate.
