### ISSUE TITLE
Quickly changing menu screens causes unintended disappearances of osu logo

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2282]
Best method to reproduce:

- Spam the following two keys while on main menu: `E` and `Esc`. (Quick-toggles editor and returns on main menu)
- Osu logo should disappear and not recreate itself.

Video: https://streamable.com/smh0k

**Comment by peppy** [comment]
Yeah, there's still some race conditions / mis-schedules with logo animations. Can happen on startup too, where the logo animated in an unexpected way.
