### ISSUE TITLE
Recent Plays in Profile show far early play result.

### ISSUE THREAD

**Issue by DeadBushSanpai** [ppy/osu#22826]
### Type

Game behaviour

### Bug description

Not sure cause by I haven't play for a long time (Detail: osu!web `Play History` graph show latest play on 2023-01, so I should get at most 2 months ago result on top of `Recent Plays` but 7 months ago show instead)
But in osu!lazer profile It show 100 Recent Play(number 100 not change between I click `SHOW MORE`)
These result between 2022-08-13 and 2022-01-20.
osu!web not show these result.(of couse)
https://osu.ppy.sh/api/v1/get_user_recent?k=**************&u=10215545&m=0 also return `[]`
This bug found on Linux and verified on Windows.

### Screenshots or videos

![Screenshot_20230310_092409](https://user-images.githubusercontent.com/46657591/224277189-c3d89df9-d5b9-4fa4-8f40-982f91501362.png)

### Version

osu! 2023.305.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/10940829/network.log)

**Comment by peppy** [comment]
This is because scores are currently not being purged after any period of time. The eventual plan is to purge non-high scores, but for now you can enjoy seeing more history than you may expect.
