### ISSUE TITLE
pp still being calculated after 3 or so days 

### ISSUE THREAD

**Issue by Shudhanshu-Raj** [ppy/osu#22823]
### Type

Game behaviour

### Bug description

It started mostly after playing with difficulty adjust mod

### Screenshots or videos

![Screenshot_20230309-203512](https://user-images.githubusercontent.com/76690780/224066907-07c7ec49-ae11-46b8-a84f-635b1ca77a3c.png)

### Version

2023.301.2

### Logs

[logs.zip](https://github.com/ppy/osu/files/10933021/logs.zip)

**Comment by peppy** [comment]
Do plays without difficulty adjust work okay? If so, I think you can probably extrapolate what's going on here.

https://github.com/ppy/osu-queue-score-statistics/blob/51fcf88918d60bc3af4a08109df23607c2a11039/osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs#L191-L193
