### ISSUE TITLE
Entering song select menu without any beatmaps, then exiting causes System.NotImplementedException

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2283]
Best method to reproduce:

- Remove all beatmaps, and enter song select menu
- Ignore prompt from importing, and return to main menu
- Notification and/or Debug log should appear.

Video: https://streamable.com/ytmtm

**Comment by peppy** [comment]
I'm not sure #2288 completely resolves this. Seems to be something going wrong in `SongSelect`'s async load (while at the main menu).

**Comment by FreezyLemon** [comment]
Exiting `PlaySongSelect` calls the `FinalizeSelection` method, which always tries to load a player with the currently selected map. Is that what you meant? If so, we should probably add a way to just not load a player instance at the end of `FinalizeSelection`
