### ISSUE TITLE
Clicking update notification on iOS causes an unobserved exception

### ISSUE THREAD

**Issue by gadielisawesome** [ppy/osu#22832]
### Type

Other

### Bug description

I discovered a bug on `iOS`.
When there is a new update, clicking the update notification results in an exception.

### Version

2023.305.0

### Logs

[database.log](https://github.com/ppy/osu/files/10947710/database.log)
[input.log](https://github.com/ppy/osu/files/10947711/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10947712/legacy-ipc.log)
[performance.log](https://github.com/ppy/osu/files/10947713/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/10947714/performance-draw.log)
[runtime.log](https://github.com/ppy/osu/files/10947715/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10947716/updater.log)

**Comment by gadielisawesome** [comment]
Found another! If you click the "View subsequent logs" notification, it crashes the game entirely and sends you to the home screen.

**Comment by peppy** [comment]
Your log files look to be in a weird non-text format.

**Comment by gadielisawesome** [comment]
Oh. I don't know what's going on there.

**Comment by peppy** [comment]
I can replicate the crash so will keep this open while investigating.
