### ISSUE TITLE
osu:// links do not work as intended in macOS

### ISSUE THREAD

**Issue by aceticke** [ppy/osu#22841]
### Type

Game behaviour

### Bug description

Using the osu!direct button on beatmap pages does not open the beatmap in lazer, macOS will ask for permission to open osu!, but all it does it swap to osu! if it's currently open without navigating to the beatmap's page or queuing a download. If it matters, I have an active osu! supporter tag.

### Screenshots or videos

https://user-images.githubusercontent.com/83513254/224512668-53c51b9a-ac9d-4966-aff1-ae229685e3e7.mov

### Version

2023.305.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10949511/database.log)
[input.log](https://github.com/ppy/osu/files/10949512/input.log)
[network.log](https://github.com/ppy/osu/files/10949513/network.log)
[performance.log](https://github.com/ppy/osu/files/10949514/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10949515/runtime.log)

**Comment by peppy** [comment]
I can reproduce this.

It looks like the IPC event here is arriving as a file drag-drop for whatever reason (via `SDL2DesktopWindow.DragDrop`). Will need to investigate further as to why this is the case (and how we're supposed to handle it), but safe to say this is going to be a macOS quirk.

As seen by the log output:

```csharp
2023-03-15 08:30:47 [verbose]: Adding 1 files for import
2023-03-15 08:30:47 [verbose]: Handling batch import of 1 files
```

**Comment by aceticke** [comment]
This seems to be a general issue for how macOS is handling osu:// links, as mentioned by zoey. Similar things such as timestamps in beatmap discussions also do not work, so I will be editing the title to reflect this.

**Comment by Susko3** [comment]
SDL [sends URLs as file drop events](https://github.com/libsdl-org/SDL/blob/f360965db64e1f90b578c9e9d28f73d0266fd4aa/src/video/cocoa/SDL_cocoaevents.m#L315-L320), so having it handled trough `SDL2DesktopWindow.DragDrop` is expected.

So I think having a special case for when the dropped "file" starts with `osu://` would make sense (with a notice about this!).
