### ISSUE TITLE
Visual Settings checkbox toggle plays audio sample more than once, leading to extremely distorted audio sample

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2284]
Best method to reproduce:

- Go to visual settings
- Press storyboard toggle

Video: https://streamable.com/h3ugh

**Comment by nbvdkamp** [comment]
Seems to be related to how many times you've gone to the starting screen before actually playing a beatmap:
https://streamable.com/3v5fd
Doing that somehow causes the ShowStoryboard  bindable to raise multiple ValueChanged events which is what makes the sound play.
