### ISSUE TITLE
Volume meter glow is pixelated

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2285]
Best method to reproduce:

- Scroll mouse wheel to show audio meter(s)
- Take a look at the ring, very pixelated + The glow effect gets cut off at certain areas, most commonly above and to the sides at perfect 90 degrees

Video: https://streamable.com/1gecy

**Comment by jorolf** [comment]
The meter being pixelated is due to the way they're drawn (CircularProgress)

**Comment by jorolf** [comment]
So this should probably be moved to framework

**Comment by Frontear** [comment]
Moved to framework; New issue: https://github.com/ppy/osu-framework/issues/1478
