### ISSUE TITLE
Screen scaling breaks judgement sizing in taiko

### ISSUE THREAD

**Issue by 2minwia** [ppy/osu#22853]
### Type

Cosmetic

### Bug description

In taiko, if you set the playfield scaling to something like:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/2979581/224569992-22ce6376-afed-4218-b35b-17a378a2123f.png">
your judgements become way smaller than the actual judgement-circle-thing, which breaks several skins (osu!classic, basically all custom skins), or just makes things really hard to see (osu!triangles/argon).

### Screenshots or videos

https://user-images.githubusercontent.com/2979581/224570119-79435384-b87c-4089-9784-743eb2494f86.mp4

### Version

2023.305.0

### Logs

[database.log](https://github.com/ppy/osu/files/10951909/database.log)
[input.log](https://github.com/ppy/osu/files/10951910/input.log)
[network.log](https://github.com/ppy/osu/files/10951911/network.log)
[performance-update.log](https://github.com/ppy/osu/files/10951912/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/10951913/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10951914/runtime.log)

**Comment by peppy** [comment]
Probably already covered / fixed / broken in https://github.com/ppy/osu/pull/22581
