### ISSUE TITLE
Overall Ranking showing the results of previous map

### ISSUE THREAD

**Issue by Terochi** [ppy/osu#22876]
### Type

Cosmetic

### Bug description

This is not confirmed, but just by observation I have noticed that the overall ranking shown at the end of a map doesn't seem to match with the play. When comparing the previous play with the current ranking however, they seem to match up pretty well.
This was played in osu!mania by [me](https://lazer.ppy.sh/users/14033233), but probably doesn't work either in other rulesets (didn't test those).

Probably related to https://github.com/ppy/osu/issues/22289

### Screenshots or videos

Last 3 result screens in order from oldest (don't mind the quality change please):
![image](https://user-images.githubusercontent.com/100224757/225383413-18034020-c465-423b-b936-518158a8b8fe.png)
![image](https://user-images.githubusercontent.com/100224757/225383836-e4767d06-4d68-4d4c-bad2-3ab95d866049.png)
worth noting that I didn't get any rank update because 95pp less than my 100th play
![image](https://user-images.githubusercontent.com/100224757/225384130-52308b0a-13b1-4340-a5ae-4cc3971164b0.png)
With recent plays for reference:
![image](https://user-images.githubusercontent.com/100224757/225384311-688f8cee-66e9-4811-be6e-3367b9df509c.png)

### Version

2023.305.0

### Logs

[database.log](https://github.com/ppy/osu/files/10982747/database.log)
[input.log](https://github.com/ppy/osu/files/10982748/input.log)
[network.log](https://github.com/ppy/osu/files/10982749/network.log)
[performance.log](https://github.com/ppy/osu/files/10982750/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/10982751/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10982752/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10982753/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10982754/updater.log)

**Comment by peppy** [comment]
What am I supposed to be looking at? I don't see it.

**Comment by Terochi** [comment]
Mainly look at the hit accuracy change. In the first screenshot, it doesn't make sense to be giving me positive hit accuracy with 90.23%, however in the play before that, I had 130pp with 94.58% accuracy, that seems to line up better. On the second screenshot I have pp with lower value than my 100th play, so it would make sense to only add total score and nothing else, but we see that happening in the third screenshot instead.

**Comment by peppy** [comment]
Hit accuracy is calculated weighted by PP. This means if you get a new score with higher PP, it weights in more to your accuracy. This is probably what happened here.
