### ISSUE TITLE
Score importing fails with System.NotSupportedException: The member 'DeletePending' is not supported

### ISSUE THREAD

**Issue by Cootz** [ppy/osu#22879]
### Type

Game behaviour

### Bug description

In previous versions of osu lazer you could import all scores, If score doesn't have a `beatmap` it was set on it was skipped.
Now osu fails to import scores from stable with lot of exceptions and notifications.

### Steps to reproduce
1. Import a map from stable you have score on
1. Import all scores from stable (you should have more than one)

### Screenshots or videos

https://user-images.githubusercontent.com/50776304/225583424-d1c77644-e343-4443-9491-d71126f64b0e.mp4

### Version

master (debug build)

### Logs

[database.log](https://github.com/ppy/osu/files/10989260/database.log)
[input.log](https://github.com/ppy/osu/files/10989262/input.log)
[network.log](https://github.com/ppy/osu/files/10989263/network.log)
[performance.log](https://github.com/ppy/osu/files/10989264/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10989265/runtime.log)

**Comment by bdach** [comment]
Seems like a regression from #22741. @peppy? @cdwcgt?

**Comment by peppy** [comment]
I've reverted on `master`. Scary for confidence in test coverage.

**Comment by Cootz** [comment]
Tested it. Now its working as expected
