### ISSUE TITLE
osu! sometimes displays an empty window when alt+tabbing

### ISSUE THREAD

**Issue by tuszmak** [ppy/osu#22909]
### Type

Game behaviour

### Bug description

I play on exclusive fullscreen and when I press alt+tab twice in quick succession (mainly when loading a map, but I encountered it in the starting screen as well), the game freezes. I use process explorer, and when I experience this, a werfault.exe also appears.

I can still play with the game, and it accepts inputs. The game's display is dead though.
The first video is the error in practice (which I can't replicate somehow when streamlabs OBS is recording), the second video is the programs currently running. (The werfault.exe stops after like 2-3 seconds after the error appears)

### Screenshots or videos

https://user-images.githubusercontent.com/81630417/226176925-c491b36c-1d9f-4c5b-b5f4-9740d78a6279.mp4

https://user-images.githubusercontent.com/81630417/226176936-e32865e0-1760-425d-9557-98f48cf561c9.mp4

### Version

2023.305.0-lazer

### Logs

[performance-draw.log](https://github.com/ppy/osu/files/11011037/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11011038/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11011039/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11011040/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11011041/updater.log)
[database.log](https://github.com/ppy/osu/files/11011042/database.log)
[debug.log](https://github.com/ppy/osu/files/11011043/debug.log)
[input.log](https://github.com/ppy/osu/files/11011044/input.log)
[network.log](https://github.com/ppy/osu/files/11011045/network.log)
[performance.log](https://github.com/ppy/osu/files/11011046/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11011047/performance-audio.log)

**Comment by peppy** [comment]
Will probably be resolved after we move away from open gl.

**Comment by peppy** [comment]
Closing as should-be-resolved.

Please feel free to reply in this thread if you can still reproduce an issue.
