### ISSUE TITLE
Custom skin objects cause Lazer to crash upon down- and reupgrading

### ISSUE THREAD

**Issue by GamingWithJanko** [ppy/osu#22925]
### Type

Crash to desktop

### Bug description

I have set a custom sprite in Osu!Lazer and it seems, that if you downgrade (Which happened on accident), then upgrade back to the latest build, it can't get the information of the said sprite in the skin editor. The button "Gameplay" was pressed.

Osu!Lazer will crash upon leaving the editor and back to the menu.

I'll post the sprite in question as well, if it's needed in any way, just in case.

![Black info panel](https://user-images.githubusercontent.com/48768314/226741662-d4d601cf-bdbc-4d95-8b83-30b37014e68b.png)

### Version

lazer/2023.305.0

### Logs

[database.log](https://github.com/ppy/osu/files/11033688/database.log)
[input.log](https://github.com/ppy/osu/files/11033689/input.log)
[network.log](https://github.com/ppy/osu/files/11033690/network.log)
[performance.log](https://github.com/ppy/osu/files/11033691/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11033692/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11033693/updater.log)

**Comment by GamingWithJanko** [comment]
The skin was ONLY for mania and looked as follows:
![osu_2023-03-11_13-42-44](https://user-images.githubusercontent.com/48768314/226742504-5e943b1d-2a2b-4f49-948c-8f20ed6e8326.png)

**Comment by peppy** [comment]
Could you please attach your `client.realm`?

**Comment by GamingWithJanko** [comment]
Here's the files you requested, Dean!

Named "(before) client.realm" and "(after) client.realm", just so you know, what file was before opening Lazer and which after crashing it.

Due to the file sizes being over 25 MB, I'll have to use Google-Drive.
Sorry for the inconvinience.

https://drive.google.com/drive/folders/1zRud3WKStEJayot93Y3yPPa_-2ogB3mZ

**Comment by GamingWithJanko** [comment]
Any updates yet? I kinda wanna remove the folder again.

**Comment by peppy** [comment]
I unfortunately haven't had time to look into this sorry. Will try to take a look this week.

**Comment by GamingWithJanko** [comment]
Ill reupload them soon then. Hang tight.

**Comment by GamingWithJanko** [comment]
Link is active again.

**Comment by GamingWithJanko** [comment]
Uhh...

**Comment by peppy** [comment]
I've checked the two files and I can't find a skin that looks like the one you have in the screenshot. What was it named?

**Comment by GamingWithJanko** [comment]
It's a heavily modified version of argon pro

**Comment by peppy** [comment]
That didn't seem to have any custom layout in either realm versions I tested. But I guess that makes sense because I don't have your full file system.

I'd probably require you to export the skin from an old release in the good state to figure out anything at this point.

**Comment by GamingWithJanko** [comment]
There's one problem tho...

The exports I'd do now wouldn't match the image, since I update the layout every time new things are added.

And last time I exported a skin, the ZIP compressed file was empty.

**Comment by peppy** [comment]
Going to close this issue for now as there's nothing to work with, sorry.
