### ISSUE TITLE
Save Button in Bracket Editor in tournament client does not trigger after editing match round

### ISSUE THREAD

**Issue by zSmoxKe** [ppy/osu#22937]
### Type

Game behaviour

### Bug description

Match round does not trigger Save button in Bracket Editor

### Screenshots or videos

https://user-images.githubusercontent.com/84255608/226967859-7fd55642-dae6-4d70-b3d4-b092ebb8af01.mp4

### Version

2023.305.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11042227/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11042229/updater.log)
[database.log](https://github.com/ppy/osu/files/11042230/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11042231/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11042232/network.log)
[performance.log](https://github.com/ppy/osu/files/11042233/performance.log)

**Comment by peppy** [comment]
Nice find, this is a pretty big oversight.
