### ISSUE TITLE
Osu crash

### ISSUE THREAD

**Issue by denwii** [ppy/osu#22945]
### Type

Crash to desktop

### Bug description

While I was playing, the song increased dramatically in speed, and then crashed osu

### Screenshots or videos

I don't have them

### Version

b20230206

### Logs

[osu!auth.log](https://github.com/ppy/osu/files/11061698/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/11061699/runtime.log)
[session.log](https://github.com/ppy/osu/files/11061700/session.log)
[update_success.log](https://github.com/ppy/osu/files/11061701/update_success.log)

**Comment by bdach** [comment]
Issue reports from osu!stable are not accepted in this repository.
