### ISSUE TITLE
Placing object in taiko with whistle or clap doesn't turn them into Katus

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu#22944]
### Type

Game behaviour

### Bug description

Having whistle or clap selected while placing a hit note doesn't turn them into Ks but having finisher selected turns them into big notes. Selecting placed objects and then selecting whistle or clap works tho which is quite non-consistent. The fact that they turn blue in the timeline also supports the case that they should place down Ks.
I think this should be changed to be like stable but still have right click make Ks too.

Also marking objects and then dragging to the edges should scroll the playfield back or forward and also mark objects.

### Screenshots or videos

https://user-images.githubusercontent.com/81715029/227506235-d492f4d9-83db-4561-8a66-d0e294b5d39b.mov

### Version

2023.305.0

### Logs

[database.log](https://github.com/ppy/osu/files/11061406/database.log)
[input.log](https://github.com/ppy/osu/files/11061407/input.log)
[network.log](https://github.com/ppy/osu/files/11061408/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/11061409/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11061410/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11061411/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11061412/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/11061413/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11061414/runtime.log)

**Comment by bdach** [comment]
> Also marking objects and then dragging to the edges should scroll the playfield back or forward and also mark objects.

Please open a separate discussion for this (if one doesn't already exist).

**Comment by aceticke** [comment]
I would like to add that this is likely because of how the editor handles left and right clicks in the taiko editor, right clicks are set to kats and left for dons, however this is quite impractical so I would like to see a fix for this.

**Comment by peppy** [comment]
I'm not 100% sure I agree with removing left/right click (it is quite fast to create hitobjects, but it's definitely non-standard), but it would likely make little sense to keep it around if we enforce the sample based placement logic.
