### ISSUE TITLE
Legacy skins will prioritise textures in folders over textures in the root folder

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#2295]
It's very common for skins to have folders within them for "extra styles".

For example, the following is a common folder structure:
```
Skin/
  -> cursor.png
  -> Extra/
      -> cursor.png
```

In the above scenario, `LegacySkin`, due to the ordering of filenames, will prioritise the `Extra/cursor.png` texture over `Skin/cursor.png`.

**Comment by peppy** [comment]
We probably want to keep that part of the path in lookups rather than dropping the whole thing.
