### ISSUE TITLE
Issues when using editor of o!m

### ISSUE THREAD

**Issue by Nick2357111** [ppy/osu#22953]
### Type

Game behaviour

### Bug description

There are some issues i found when using the editor:
1. There is a chance to highlight the previous one when scrolling to a timeline in the timeline table.
2. There is some image gliches which make LNs head seems to be at a wrong place and some notes disappeared when scrolling by mousewheel.
3. It seems that you can't change the keys that the map used.
4. There is some bug dealing with sv changing, which makes part of map's sv behavior being ignored in editor.
5. Some hitsound glitches happened in LN. (Newly placed LN has tail hitsound but older hasn't)
6. Hoping that the uploading window will add soon in future update.

### Version

2023.305.0

### Logs

[input.log](https://github.com/ppy/osu/files/11071844/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11071845/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11071847/network.log)
[performance.log](https://github.com/ppy/osu/files/11071848/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11071849/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11071851/updater.log)
[database.log](https://github.com/ppy/osu/files/11071852/database.log)

**Comment by bdach** [comment]
Most of this is already reported in other issues (https://github.com/ppy/osu/issues/10455, https://github.com/ppy/osu/issues/12904).

Closing because the scope is too wide and there is not enough details in some of the points raised. Please search first, and reopen everything that hasn't been reported yet with proper details.
