### ISSUE TITLE
Screenshots don't work with veldrid renderer

### ISSUE THREAD

**Issue by TheEggo** [ppy/osu#22959]
### Type

Game behaviour

### Bug description

Screenshots taken by hitting f12 save completely transparent, regardless of the renderer selected.
This has not happened prior to todays update

### Screenshots or videos

![image](https://user-images.githubusercontent.com/64386789/227790750-918027af-c555-4218-9901-aeaffb0664f5.png)

https://user-images.githubusercontent.com/64386789/227791136-9841dafc-cb13-48df-b816-6ae3510e3fe8.mp4

### Version

2023.326.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/11072305/runtime.log)

**Comment by RUvlad1** [comment]
I have the same issue, however in my case choosing "OpenGL (Legacy)" renders the screenshot perfectly fine

![osu_2023-03-26_21-55-54](https://user-images.githubusercontent.com/60317461/227797770-38247fb0-068a-4c5d-9148-78d13f405af8.png)

**Comment by Eeveelution** [comment]
Same issue on Metal, running on my M1 Mac

**Comment by 3stantedja** [comment]
ppy/osu-framework#5678 might be the relevant framework-side issue for this.
