### ISSUE TITLE
Freezes and memory leaks when using the new vulkan renderer

### ISSUE THREAD

**Issue by bytenekos** [ppy/osu#22960]
### Type

Performance

### Bug description

Changed the vulkan renderer to vulkan and it now freezes and memory leaks in the background when I check task manager
System details are:
Windows 11 Pro build 22621.1413 experience pack 1000.22639.1000.0
Ryzen 7 3700x
Rtx 3080 running nvidia drivers 531.29

### Screenshots or videos

https://user-images.githubusercontent.com/66184829/227791626-18be26f7-0857-40b0-9ed8-40b0cf6d3861.mp4

### Version

2023.326.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11072338/database.log)
[input.log](https://github.com/ppy/osu/files/11072339/input.log)
[network.log](https://github.com/ppy/osu/files/11072340/network.log)
[performance.log](https://github.com/ppy/osu/files/11072341/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11072342/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11072343/updater.log)

**Comment by Hexality** [comment]
same here, however here it is freezing as soon as the osu logo appears when opening the game, only audio continues.

https://user-images.githubusercontent.com/17398632/227791922-8e819bf8-3bc4-471b-86b5-0031baeac401.mp4

**Comment by bdach** [comment]
Vulkan is going to be pulled as a choice on all platforms for now until it is stabilised (#22961).

**Comment by Hexality** [comment]
how do I revert to default renderer?

**Comment by embedvr** [comment]
I am getting this too after symlinking `libdl.so.2` to `libdl.so` on linux.

Arch Linux (6.2.7-arch1-1) using X server,
Ryzen 5 3600x
NVIDIA RTX 2060 Super (using the Arch [Nvidia drivers](https://archlinux.org/packages/extra/x86_64/nvidia/)

**Comment by bdach** [comment]
@Hexality you can either delete `framework.ini` from the game files, or if feeling particularly attached to your settings, remove the `Renderer = Vulkan` line from that file.

**Comment by Hexality** [comment]
ok thanks.

**Comment by Hitsounds** [comment]
The vulkan render seems to not freeze when the threading mode is set to single threaded.

**Comment by Sukuratchi** [comment]
> The vulkan render seems to not freeze when the threading mode is set to single threaded.

Still freezes rendering and starts memory leaking for me, but most of the time it at least lets me "get into the map" (it gets past the loading screen and loads into the map). Seems like it starts to break when it starts showing objects on screen maybe?

Also another thing I noticed is that the frame limiters don't work except for vsync. I set the frame limiter to 2x and it still rendered over 500fps (Monitor is 144hz)

**Comment by Hitsounds** [comment]
![image](https://user-images.githubusercontent.com/17516655/228741691-7ea33ce6-2b15-4c6c-98a9-cba96c8e6f07.png)
This is the stack whenever it freezes. It looks like it gets stuck waiting for a fence.

**Comment by efojug** [comment]
On my computer, it will appear that after entering the map, it will not respond directly, and the game will automatically exit after waiting for a while(osu version 816)

**Comment by smoogipoo** [comment]
Don't use the vulkan renderer. It's known to be unstable, see the many (ongoing) reports in https://github.com/ppy/osu/discussions/27659

This issue is stale so I'm closing it.
