### ISSUE TITLE
[2023.326.0/Bug Report] osu! vulkan renderer graphically stuck.

### ISSUE THREAD

**Issue by Hexality** [ppy/osu#22964]
### Type

Game behaviour

### Bug description

Using vulkan renderer while in window mode makes the game get stuck (graphically only, audio and input still working) as soon as the game logo appears on the screen. When using fullscreen, the game displays nothing but a black screen with audio (input still works).

### Screenshots or videos

https://user-images.githubusercontent.com/17398632/227792299-d954f241-c731-4655-890d-aa0131ec502f.mp4

### Version

2023.326.0

### Operating system
Windows 11 Pro (22621.1413)

### Logs

[database.log](https://github.com/ppy/osu/files/11072386/database.log)
[input.log](https://github.com/ppy/osu/files/11072387/input.log)
[network.log](https://github.com/ppy/osu/files/11072388/network.log)
[performance.log](https://github.com/ppy/osu/files/11072389/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11072390/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11072391/updater.log)

**Comment by bdach** [comment]
Let's just track all of these under #22960 for now.

**Comment by Hexality** [comment]
may I post this there?

**Comment by bdach** [comment]
the issues are linked to each other already literally what is the point
