### ISSUE TITLE
Caught fruits in osu!catch not scaling down to sane size on the catcher at low CS values

### ISSUE THREAD

**Issue by rrex971** [ppy/osu#22968]
### Type

Cosmetic

### Bug description

The fruits that have already been caught on stable scale down to the catcher's size. In lazer, they remain the same size as the map's circle size, causing visibility issues. This is especially prominent when the maps have low circle size. The videos below show the difference in behavior:

Edit: Upon further testing it appears the fruits are indeed scaled down but it is by such a small amount that it becomes insignificant for low CS maps. It works fine for higher CS maps (>3) but impedes readability on any lower
### Screenshots or videos

Behavior on stable:

https://user-images.githubusercontent.com/75212090/227794437-cbfc928c-ccd3-499d-a2f8-a6ab97c6d0a6.mp4

Behavior on lazer:

https://user-images.githubusercontent.com/75212090/227794445-a22b5b94-e503-408f-839f-5253f269356c.mp4

### Version

2023.326.0-lazer

### Logs

Logs don't seem that relevant for this cosmetic issue, but I can provide them if required

**Comment by peppy** [comment]
This is likely an issue with your skin. Scaling is applied correctly on all defaults including classic.

Please attach the skin.

**Comment by peppy** [comment]
The skin you gave me doesn't match your video.

Also it looks correct here:

https://user-images.githubusercontent.com/191335/228443926-c87d0e63-71d8-421b-8328-472ddd49a06a.mp4

**Comment by rrex971** [comment]
Hmm, it's definitely scaling in a weird way for me. Here's the exact skin I used in that original video: 
https://drive.google.com/file/d/1uAwAUITsMWpD23hb5zP-0rKQeSQ3nyUk/view?usp=sharing

**Comment by peppy** [comment]
It does look like the scaling effect is reduced too much at low CS values. I'll investigate further with this knowledge, thanks.
