### ISSUE TITLE
Beatmaps with video have considerable stutter on new OpenGL renderer

### ISSUE THREAD

**Issue by STCapricorn** [ppy/osu#22970]
### Type

Performance

### Bug description

as written on the title, the frame rate drops from the max set frame rate to about 30-40 fps on Windows.
it doesn't happen on D3D or legacy OpenGL, and turning off hardware decoding makes it even worse.
issue will be exacerbated by flipping video on and off.
the GPU is an Nvidia GTX 1660 Ti, fwiw. Running on Windows 11 22H2.

### Screenshots or videos

https://user-images.githubusercontent.com/7162510/227793388-a0cbe6aa-23f9-4388-8587-ff343cbfe279.mp4

### Version

2023.326.0

### Logs

[performance.log](https://github.com/ppy/osu/files/11072507/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11072508/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11072509/updater.log)
[network.log](https://github.com/ppy/osu/files/11072510/network.log)

**Comment by TheComputerGuy96** [comment]
I should add that this also affects Linux (and possibly any platform that supports the OpenGL Veldrid renderer)

I also have discovered another more severe video issue that affects Veldrid OpenGL in multi-threaded mode and Vulkan in any mode, but I will make another issue for that 🐸

**Comment by smoogipoo** [comment]
Yeah, likely the performance problems are coming from FFmpeg giving us packed data and Veldrid not supporting this exact case. So we're doing one upload per row of the image.

https://github.com/ppy/osu-framework/blob/9ff4eaaabc2eddc0e218b0cabea439e03df11d3f/osu.Framework/Graphics/Veldrid/VeldridRenderer.cs#L299-L307

**Comment by peppy** [comment]
Bumping this to p0 as it reduces FPS on iOS to <1fps. Worse on OpenGL than metal.
