### ISSUE TITLE
Password is not correct.  (fact checked)

### ISSUE THREAD

**Issue by SatoTsukasaCode** [ppy/osu#22986]
### Type

Crash to desktop

### Bug description

Trying to log in. saying that my password is wrong. (I did check it.)

I use the development build.
Bug started after I used `git pull`

Currently looking into it.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/78177853/227800134-aff08850-3eda-4dbb-89ed-78af804ee6d7.png)

### Version

2023.326.1

### Logs

I can't find them.

**Comment by mouzedrift** [comment]
When you build in debug mode, you connect to the development server, so I'm assuming you tried to login with your actual osu! account, which does not exist on the development server.

**Comment by SatoTsukasaCode** [comment]
i see, thanks for the info. how can i open an account on the development server?

**Comment by mouzedrift** [comment]
I believe you can create an account on the development server by registering a new osu! account on osu!lazer while you're running it in debug mode.
