### ISSUE TITLE
Accuracy Heatmap only shows 1 horizontal row when using OpenGL

### ISSUE THREAD

**Issue by Kori3** [ppy/osu#22982]
### Type

Game behaviour

### Bug description

Pretty self explanatory.
This happens with both OpenGL and OpenGL Legacy.

### Screenshots or videos

pc
![pc](https://user-images.githubusercontent.com/70714793/227798632-6008a9a3-cb6b-4422-8f53-24ae19b9a7d0.png)

mobile (android)
![mobile](https://user-images.githubusercontent.com/70714793/227798642-5c7cf52a-bbc7-4d23-aa68-5568bc87e89c.jpg)

### Version

2023.326.1

### Logs

probably not necessary but whatever
[logs.zip](https://github.com/ppy/osu/files/11072765/logs.zip)

**Comment by bdach** [comment]
Looks to be a regression from #5706. Something clearly must not be flipped on opengl that should be, but I'm failing to find what it is right now.
