### ISSUE TITLE
Taiko spinners stutter when using classic or imported skins

### ISSUE THREAD

**Issue by nobbele** [ppy/osu#22985]
### Type

Performance

### Bug description

1. Select "classic" or an imported skin
2. Play a taiko map containing a spinner

Right before the spinner comes on-screen the game with freeze for a split second.

### Screenshots or videos

https://user-images.githubusercontent.com/17962514/227799859-1bd80879-2531-42b7-9198-0f06f7fcf5c5.mp4

### Version

2023.326.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11072825/database.log)
[input.log](https://github.com/ppy/osu/files/11072826/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11072827/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11072828/network.log)
[performance.log](https://github.com/ppy/osu/files/11072829/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11072830/runtime.log)

**Comment by scyencee** [comment]
for me, the stutter is more intense, freezing sometimes up to an entire second

**Comment by peppy** [comment]
From what I can tell this only applies to the first spinner/swell in a beatmap.

**Comment by peppy** [comment]
Regression from veldrid:

![Parallels Desktop 2023-03-28 at 04 47 26](https://user-images.githubusercontent.com/191335/228131015-8acc6675-6aeb-4ddb-8bd1-d7a419a5cbcb.png)
