### ISSUE TITLE
Clicking the update notification in Android does nothing

### ISSUE THREAD

**Issue by agatemosu** [ppy/osu#22993]
### Type

Other

### Bug description

Same as #22777. The version with the bug fixed doesn't work. But the chat links do work.

### Version

2023.326.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11073140/runtime.log)

**Comment by Joehuu** [comment]
This happens when the GitHub app is installed and `github.com` links are redirecting there. Haven't investigated yet what the solution is.
