### ISSUE TITLE
Skin Layout Editor doesn't account for resolution resizing after adding items on Song Select

### ISSUE THREAD

**Issue by Arisamiga** [ppy/osu#22992]
### Type

Cosmetic

### Bug description

When trying to add something on Song Select using the Skin layout editor the editor makes the song select menu smaller but when exiting from the Skin layout editor it expands again but the items don't follow that expansion.

### Screenshots or videos

https://user-images.githubusercontent.com/64918822/227803986-58f1d161-fdc8-43fe-87c6-d7e16feff434.mp4

### Version

2023.326.1

### Logs

[performance.log](https://github.com/ppy/osu/files/11073067/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11073069/runtime.log)

**Comment by bdach** [comment]
This is not the correct way to align this element like you want it to. Please try the anchor and origin options from the context menu, see what they do, and then try this again but by setting a different anchor and origin point of the drawable you're trying to add.

Tangentially related: https://github.com/ppy/osu/discussions/22210

**Comment by Arisamiga** [comment]
> 

Oh, I wasn't aware of that. Thanks so much for your help 🙂
