### ISSUE TITLE
HIdden in mania is broken

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu#23009]
### Type

Game behaviour

### Bug description

You can't see any notes

### Screenshots or videos

https://user-images.githubusercontent.com/81715029/227890231-e7a72a7f-f550-4388-b193-692b4276884f.mov

### Version

2023.326.1

### Logs

[database.log](https://github.com/ppy/osu/files/11076577/database.log)
[input.log](https://github.com/ppy/osu/files/11076579/input.log)
[network.log](https://github.com/ppy/osu/files/11076581/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/11076582/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11076583/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11076584/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11076585/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/11076586/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11076587/runtime.log)

**Comment by SatoTsukasaCode** [comment]
what renderer are you using?

**Comment by reo-the-enby** [comment]
openGL

**Comment by SatoTsukasaCode** [comment]
You are on MacOS right?

**Comment by reo-the-enby** [comment]
Yes

**Comment by SatoTsukasaCode** [comment]
try using the default.

**Comment by Sarisan** [comment]
That new-renderer change is completely broken imo. OpenGL (legacy) makes my game run in 30 fps. If i use just OpenGL I get to the end of my local scores list. Accuracy is too low, many of missclicks, I don't believe that my skills got so bad.
