### ISSUE TITLE
Difficulty Adjust mod in osu!catch doesn't allow CS and AR values below 1.0

### ISSUE THREAD

**Issue by rrex971** [ppy/osu#23015]
### Type

Game behaviour

### Bug description

The Difficulty Adjust mod in osu!catch doesn't allow the slider to be set to values below 1.0 for Circle Size and Approach Rate. The HP and OD sliders are fine, allowing 0.0-0.9 as values. This is not the case with the mod in osu!standard.

### Screenshots or videos

![Q7nZ8UT](https://user-images.githubusercontent.com/75212090/227957856-5c852527-9f88-44a8-ae16-d42ad7d3e631.png)

![NoUJoTc](https://user-images.githubusercontent.com/75212090/227957863-af7512ae-8437-4a5c-a3ff-0f6da9cc178d.png)

### Version

2023.326.1-lazer

### Logs

N/A, issue with game behavior

**Comment by rrex971** [comment]
I have an open issue related to stuff being broken specifically at around CS0, #22968 
But there are ranked catch CS0 maps and CS0 has been a thing forever on stable with catch

**Comment by rrex971** [comment]
Oh I was about to open a PR for this since it was just two lines that had to be changed, should I not? Apologies for my ignorance as it's my first time contributing to osu!

**Comment by bdach** [comment]
That sounds about right.
