### ISSUE TITLE
Screen and audio error popups after newest Lazer update (iOS 15.4.1, iPhone SE 2020)

### ISSUE THREAD

**Issue by HyperLemons** [ppy/osu#23013]
### Type

Other

### Bug description

Opening the game for the first time after the latest TestFlight release (2023.326.1) displays the popups shown in the first screenshot.

I closed and reopened the game to see if it was just a one time thing and then I got another error for audio as shown in the second screenshot. Weirdly doesn’t seem to effect any actual audio or performance (can’t comment too much on if this actually effects performance because I still can’t stably hit 60fps in menus even after the metal update :/)

### Screenshots or videos

![0017B69A-C3A3-4F07-A447-011D9A868DC6](https://user-images.githubusercontent.com/36387099/227930899-1c84e4d0-39f8-4436-93c1-2f2aa27799c9.png)

![AFBD6A39-3FC0-4228-9ECB-0BDE954E3E41](https://user-images.githubusercontent.com/36387099/227931677-59b489ec-8ac6-4afe-9170-accc01967834.png)

### Version

2023.326.1 (iOS)

### Logs

https://mega.nz/file/dzgkmQgI#2bTG_wB4bCT_A66j70C3js1QEUMMqLJMZgT2C4DL-TE

Link to zip containing logs folder after I took second screenshot and closed the game

**Comment by HyperLemons** [comment]
Should probably mention I just tried to switch to renderer back to OpenGL (regular not legacy) to see if those errors would still show up and the game won't reopen now.

**Comment by frenzibyte** [comment]
All of your issues are known / tracked elsewhere:

- The first error is tracked in https://github.com/ppy/osu/issues/22997.
- The second error is mostly happening as a result of the intro performing poorly, leading to the game think it's not playing at all and skipping it.
- The third error you mentioned in your comment above is tracked in https://github.com/ppy/osu/issues/22978.
