### ISSUE TITLE
Attempting to submit a score with Taiko Single Tap throws an error

### ISSUE THREAD

**Issue by OpenSauce04** [ppy/osu#23014]
### Type

Other

### Bug description

As the title says. Something may have been forgotten to make this mod work with online score submission, as this did not happen on a local debug build

### Screenshots or videos

![Screenshot_20230327_135637](https://user-images.githubusercontent.com/48618519/227946808-f05aa76e-0c25-4f74-ab8b-bf854752edfe.jpg)

### Version

2023.326.1

### Logs

N/A

**Comment by peppy** [comment]
Should be resolved now via the other project updates.
