### ISSUE TITLE
osu!lazer crashes on launch on M1 Mac

### ISSUE THREAD

**Issue by SeazeIsCool** [ppy/osu#23021]
### Type

Crash to desktop

### Bug description

i downloaded the latest version of osu for apple silicon from releases, and when i open the app, it just stays in the dock bouncing for a bit and then exits with an error (i sent the log below (both the one in the logs folder and the one which appears when you press "Report..." because im unsure on if both are needed))

this happens for both 2023.326.1 and 2023.326.0 but any version before that is fine

im on an m1 mac on big sur 11.6

### Screenshots or videos

https://user-images.githubusercontent.com/129086431/227986181-4fd7c67b-4b4a-4d2e-90b9-3758fc84e88e.mov

### Version

2023.326.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/11080428/runtime.log)
[message.txt](https://github.com/ppy/osu/files/11080495/message.txt)

**Comment by Minorsonek** [comment]
maybe update your os, on 13.2.1 ventura all mentioned versions work flawlessly

**Comment by frenzibyte** [comment]
As mentioned above, please consider updating your operating system first as it's quite dated now (almost 3 years old).
