### ISSUE TITLE
Slider working after auto-close popup window in map

### ISSUE THREAD

**Issue by senhorstd** [ppy/osu#23023]
### Type

Cosmetic

### Bug description

when i star map and need change slider value, after close popup slider has changing value (mouse button is held down)

### Screenshots or videos

https://www.veed.io/view/335afaef-8cd8-44af-b524-90615bcf3043?sharingWidget=true&panel=share

### Version

2023.326.1

### Logs

logs dont have

**Comment by peppy** [comment]
This issue needs to be rewritten to make sense to an average human.

**Comment by longnguyen2004** [comment]
When you use the slider to change the value of whatever, if the cursor leaves the container's bounds while you're still holding left click, you can still drag the slider inside that container, even when it's already hidden.

**Comment by peppy** [comment]
Please provide an example of where this happens. Sorry but I'm not willing to click a "veed.io" link to watch your video (please drag it into github instead).

**Comment by Gabixel** [comment]
> you can still drag the slider inside that container, even when it's already hidden.

I think he probably means something like https://github.com/ppy/osu/issues/6121 and https://github.com/ppy/osu/discussions/23347

**Comment by peppy** [comment]
Let's track via those issues then.
