### ISSUE TITLE
New renderers stuttered when playing video

### ISSUE THREAD

**Issue by a0193143** [ppy/osu#23026]
### Type

Performance

### Bug description

New renderers would cause stutter when beatmap playing video, OpenGL (legacy) performs normally.
Tried turn on/off use hardware acceleration but no difference.

### Screenshots or videos

![osu!_2023_03_28_03_25_07_296](https://user-images.githubusercontent.com/32773311/228047935-6986dc99-4159-40c6-933b-e4648407113c.png)
![osu!_2023_03_28_03_26_13_831](https://user-images.githubusercontent.com/32773311/228047944-e9b48933-0f76-4810-8ea7-b1f52cb3b47f.png)
![osu!_2023_03_28_03_22_55_104](https://user-images.githubusercontent.com/32773311/228047950-a277a074-71c9-49f0-8747-b202620dfca4.png)

### Version

2023.326.1-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11082324/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11082325/updater.log)
[database.log](https://github.com/ppy/osu/files/11082326/database.log)
[input.log](https://github.com/ppy/osu/files/11082327/input.log)
[network.log](https://github.com/ppy/osu/files/11082328/network.log)
[performance.log](https://github.com/ppy/osu/files/11082329/performance.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/22970
