### ISSUE TITLE
Playtesting in the editor should start from 100% accuracy regardless of start position to match stable

### ISSUE THREAD

**Issue by aceticke** [ppy/osu#23029]
### Type

Game behaviour

### Bug description

Starting from any position other than the beginning of the beatmap will treat any mapping prior as misses, starting from 0% and the maximum accuracy will depend on how many notes the remainder of the map contains.

### Screenshots or videos

https://user-images.githubusercontent.com/83513254/228094904-1d2f64de-0c69-4400-822c-cb67504b7d90.mp4

### Version

2023.326.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11083919/database.log)
[input.log](https://github.com/ppy/osu/files/11083920/input.log)
[network.log](https://github.com/ppy/osu/files/11083921/network.log)
[performance.log](https://github.com/ppy/osu/files/11083922/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11083923/runtime.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/17395 is sorta related.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/26465.
