### ISSUE TITLE
Skinning for hit judgements regression

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#2303]
I thought this was already implemented earlier before. Went back to the default when a skin is selected.
![](https://puu.sh/zOfN7/5db624053e.png)

**Comment by peppy** [comment]
It works here.

**Comment by Joehuu** [comment]
I checked it out and seems that only the 2x pngs are only shown on the recent release. The skin I used didn't have 2x 300, so it didn't display. Renamed it 2x to the file, and it showed. The old release did show the non 2x ones.

**Comment by peppy** [comment]
Thanks. That does sound like a regression.
