### ISSUE TITLE
F score on 80.66% accuracy

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#23032]
### Type

Game behaviour

### Bug description

Hi, there is no F score in the game, and also my accuracy is B.
(its Guest cuz I was playing offline)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/89677246/228123929-0337d186-1722-4f38-8d19-9982504f8855.png)
![image](https://user-images.githubusercontent.com/89677246/228123999-d06d715c-3af1-42a1-807a-e6673a1aa133.png)
![image](https://user-images.githubusercontent.com/89677246/228124021-fda0ff50-95df-40ac-9fc5-1883a1349630.png)

### Version

2023.305

### Logs

I realized it after some sessions, so there is no logs about that.

**Comment by aL1NaZ4R** [comment]
Edit: I didn't failed that beatmap

**Comment by peppy** [comment]
Could you please attach the replay and also your `client.realm` if possible?

**Comment by bdach** [comment]
@aL1NaZ4R did you have storyboards enabled? If so, then this could plausibly be the same thing as https://github.com/ppy/osu/issues/23016#issuecomment-1485831756

**Comment by aL1NaZ4R** [comment]
Video is disabled, but I still get epilepsy smh

**Comment by aL1NaZ4R** [comment]
+ I'm sorry, I cleared all beatmaps replay cache.
