### ISSUE TITLE
New OpenGL renderer causes weird visual glitches with sliders on maps with storyboards when dim is 100%

### ISSUE THREAD

**Issue by PillTime** [ppy/osu#23046]
### Type

Game behaviour

### Bug description

Sliders get glitchy visuals using the new OpenGL renderer (legacy one works fine).
Video attached.

My graphics card is an AMD Radeon RX 5600 XT, using the Mesa driver, version 23.0.1-1, on Arch Linux.

**EDIT**: After seeing that the logs complained about storyboards, I verified that this bug doesn't happen if the storyboard/video option is disabled.

Beatmap is https://osu.ppy.sh/beatmapsets/705788#osu/1492654

**EDIT 2**: This just gets weirder. This bug only happens when dim is 100%. Even 99% dim is enough for the bug to disappear.

Happens with any skin, even the built-in skins like argon.

### Screenshots or videos

https://user-images.githubusercontent.com/2399664/228394070-29469062-8099-4617-b130-2bba33537575.mp4

### Version

2023.326.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11095322/database.log)
[input.log](https://github.com/ppy/osu/files/11095324/input.log)
[network.log](https://github.com/ppy/osu/files/11095325/network.log)
[performance.log](https://github.com/ppy/osu/files/11095326/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/11095327/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/11095328/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11095329/runtime.log)

**Comment by MkGuh** [comment]
doesn't seem to happen in Windows 11 with AMD GPU

**Comment by peppy** [comment]
Could you please try again on the latest release and see if the problem still reproduces?

**Comment by PillTime** [comment]
Yep, still looks the same as before.

**Comment by bdach** [comment]
Can't seem to reproduce on my hardware, neither on windows nor on linux (ubuntu 22.04, nvidia graphics card, proprietary driver). Unfortunately appears this may be driver-specific.

**Comment by rxfrxctxd** [comment]
Can agree about this being a driver-specific issue, I use a RX 6600XT on Arch with the same `mesa` version, but while I do not have any graphical glitches, the performance is very subpar relative to the "Legacy" renderer.

Would not be an issue if it didn't constantly drop below my 144hz refresh rate, where the Legacy has >300fps at all times.
This happens on the same maps as on OP's, but I get 10fps...

Default dim settings, to be clear.

**Comment by OninDynamics** [comment]
Also happens on this map: https://osu.ppy.sh/beatmapsets/703957#osu/1489207 On the last slider before drop, and the last slider of the map.

![image](https://user-images.githubusercontent.com/71348981/233557215-b454d828-fa83-4160-a76b-e9ccf7c95748.png)![image](https://user-images.githubusercontent.com/71348981/233557262-06ccef74-f797-422b-bccf-ce9d3c1660a0.png)

I use the [NVIDIA proprietary drivers](https://archlinux.org/packages/extra/x86_64/nvidia-dkms/), and happens both on Windows and (Arch) Linux. Will edit and attach logs.

**Comment by OninDynamics** [comment]
I noticed just now, the artifacts do not appear when "Bypass front-to-back render pass" is enabled.

**Comment by OninDynamics** [comment]
Doesn't seem to happen anymore. Tested on the previous maps I mentioned, both `OpenGL` and `OpenGL (Experimental)`, with `bypass front-to-back render pass` disabled and enabled.

i don't know what fixed this, but it seems fixed now

**Comment by PillTime** [comment]
Can confirm that the experimental OpenGL renderer is working fine on Linux for me too.
