### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by howozz** [ppy/osu#23045]
### Type

Crash to desktop

### Bug description

The game crashes as there is no usable renderer, please see the logs.
There was no issue before this new renderer stuff.

My system info:
Intel Core 2 Duo T7600
3.3 GB RAM
AMD Mobility Radeon X1600 256MB

### Version

2023.326.1

### Logs

[runtime.log.txt](https://github.com/ppy/osu/files/11093355/runtime.log.txt)

**Comment by peppy** [comment]
Out of curiosity, are you able to easily test on windows with the same hardware?

**Comment by howozz** [comment]
I'll test it when I get home.

**Comment by howozz** [comment]
@peppy /

**Comment by howozz** [comment]
@peppy 
[windows-runtime.log.txt](https://github.com/ppy/osu/files/11101794/windows-runtime.log.txt)

**Comment by TheComputerGuy96** [comment]
@howozz Your GPU doesn't even support Direct3D 11, so that's expected

**Comment by peppy** [comment]
The case here is that your GPU doesn't support any semi-modern OpenGL version, and we had to bump the version to implement the new renderer changes.

@smoogipoo can confirm, but I'm 99% sure this is the end of the line for you and your 2006 GPU.

**Comment by smoogipoo** [comment]
Yeah, unfortunately it looks like that's going to be the case.

In the future we may consider adding D3D9 support to Veldrid, but I'm not sure if that's even feasible at this point.
