### ISSUE TITLE
Replays don't record properly on beatmaps with video

### ISSUE THREAD

**Issue by doomed151** [ppy/osu#23055]
### Type

Game behaviour

### Bug description

It started breaking after the game got updated to the latest version.

1. Play a map until the end.
2. Click watch replay at the bottom of the end screen.
3. See replay being broken.

Watching the replay via local scoreboard also produces the same result. I have the exported .osr but I can't seem to attach it here.

### Screenshots or videos

https://streamable.com/wt3cgi

### Version

2023.326.1-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/11100832/input.log)
[network.log](https://github.com/ppy/osu/files/11100833/network.log)
[performance.log](https://github.com/ppy/osu/files/11100834/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11100835/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11100836/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/11100837/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11100838/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11100839/updater.log)
[database.log](https://github.com/ppy/osu/files/11100840/database.log)

**Comment by bdach** [comment]
This will have the same root cause as https://github.com/ppy/osu/issues/23016 and (likely) https://github.com/ppy/osu/issues/23032.
