### ISSUE TITLE
Glitched graphics with DirectX renderer in fullscreen mode

### ISSUE THREAD

**Issue by khanhmuy** [ppy/osu#23067]
### Type

Performance

### Bug description

On the new DirectX renderer in fullscreen mode, the game's graphics stutters and glitches, with FPS and input still being relatively normal (although there are somewhat frequent stutters) Happens on both single-threaded and multi-threaded mode.

Laptop specs: Intel Core i3-4005U, 8GB RAM, Intel HD Graphics 4400 on Windows 10 21H1 build 19043.1021

### Screenshots or videos

https://photos.app.goo.gl/oXqh7y4B299WitU46

### Version

2023.326.1

### Logs

[input.log](https://github.com/ppy/osu/files/11119734/input.log)
[network.log](https://github.com/ppy/osu/files/11119736/network.log)
[performance.log](https://github.com/ppy/osu/files/11119738/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11119739/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11119743/updater.log)
[database.log](https://github.com/ppy/osu/files/11119745/database.log)

**Comment by Susko3** [comment]
It seems you're using a non-native fullscreen resolution. If you set the native resolution, do you still get the visual glitches?

```cs
2023-03-31 08:10:54 [verbose]: Updated display mode to desktop resolution: 1366x768@60, SDL_PIXELFORMAT_RGB888
2023-03-31 08:11:00 [verbose]: Updated display mode to fullscreen resolution: 1280x720@60, SDL_PIXELFORMAT_RGB888
```

**Comment by khanhmuy** [comment]
Yeah I was testing different resolutions to see if the glitches still happen, but yes they do happen on native resolution

**Comment by longnguyen2004** [comment]
Does it happen on OpenGL? (not OpenGL Legacy, that's the old renderer)

**Comment by khanhmuy** [comment]
No, this only happens with DX11

**Comment by 1qqri** [comment]
same issue, all ui/gameplay elements are flickering.
specs: Intel Celeron 2957U, Intel HD Graphics, Windows 10 Build 19045, 1366x768@60.
glitches don't show up in screenshots.

**Comment by smoogipoo** [comment]
I think the simplest path here is to replace the D3D renderer. I have very little faith in the Veldrid implementations as they are which is why I'm working on implementing WebGPU (which should have a stabilised D3D implementation).

I haven't been able to reproduce this so I don't think it's worth addressing/keeping this issue around. I recommend using OpenGL.
