### ISSUE TITLE
Parent OnRevertResult is not invoked by nested HitObjects

### ISSUE THREAD

**Issue by LumpBloom7** [ppy/osu#23069]
### Type

Game behaviour

### Bug description

Previously, when a nested `DrawableHitObject` had their results reverted, they would invoke `OnRevertResult` of their parent. 

This behaviour is removed in #22291, but the comments above `DrawableHitObject.OnRevertResult` remain unchanged, leading to difference in expected behaviour.

### Version

2023.326.1

### Logs

N/A

**Comment by peppy** [comment]
Going to drop this in p0 for now since it was a regression in ruleset API.
