### ISSUE TITLE
Color is screwed up in my client.

### ISSUE THREAD

**Issue by Zozimoto** [ppy/osu#2307]
As the title says, some colors are screwed up. my pfp is yellow, not blue.
![image](https://user-images.githubusercontent.com/24670913/37861766-bb2df96e-2f40-11e8-968b-7856393fc297.png)

**Comment by Zozimoto** [comment]
It happened with the new update.

**Comment by smoogipoo** [comment]
Are there any colours in the game that are inverted like this? I can't replicate this prior/post netstandard.

**Comment by iiSaLMaN** [comment]
Missing details? Can you provide us with your hardware info, does this issue happen only for your avatar or does it happen to all components provided in the screen?

**Comment by peppy** [comment]
This is over a year old and has no details. Please reopen with system specs and an update as to whether it is still reproducible.
