### ISSUE TITLE
Game studders on DirectX 11

### ISSUE THREAD

**Issue by distrair** [ppy/osu#23075]
### Type

Performance

### Bug description

Game render starts to studder when in game (probably only on osu!standart)

### Screenshots or videos

https://send.vis.ee/download/bbdf3d2b3d5331bf/#L9MQRLLnHjodIKm285eVFw
(my recording is 40 mb big for some reason, had to zip it)

### Version

2023.326.1

### Logs

[updater.log](https://github.com/ppy/osu/files/11130034/updater.log)
[runtime.log](https://github.com/ppy/osu/files/11130035/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11130036/performance.log)
[database.log](https://github.com/ppy/osu/files/11130037/database.log)
[input.log](https://github.com/ppy/osu/files/11130038/input.log)
[network.log](https://github.com/ppy/osu/files/11130041/network.log)

**Comment by peppy** [comment]
Use the original issue.
