### ISSUE TITLE
[Android] Music keeps playing when using ALT+F4

### ISSUE THREAD

**Issue by FabiSahne** [ppy/osu#23072]
### Type

Game behaviour

### Bug description

When using the shortcut ALT+F4 to close the game the music keeps playing, even though the app is closed (not in the resent App menu anymore).
After opening the App again (to close it properly) it is stuck on a black screen with the App logo (see screenshot).
Closing this on the other hand does close it properly.

Might just be Android being Android, but you never know.

### Screenshots or videos

![photo_2023-04-01_15-34-09](https://user-images.githubusercontent.com/65239050/229292162-640fec16-2e99-4e12-b9e9-8bb65d17c42c.jpg)

### Version

2023.326.1

#### After using ALT+F4

[network.log](https://github.com/ppy/osu/files/11129675/network.log)
[performance.log](https://github.com/ppy/osu/files/11129676/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11129677/runtime.log)
[database.log](https://github.com/ppy/osu/files/11129678/database.log)

#### After closing the game properly

[performance.log](https://github.com/ppy/osu/files/11129652/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11129653/runtime.log)
[database.log](https://github.com/ppy/osu/files/11129654/database.log)
[network.log](https://github.com/ppy/osu/files/11129655/network.log)

**Comment by peppy** [comment]
Alt-F4 should not work on android, so the first thing should be to fix that.

**Comment by FabiSahne** [comment]
I should also mention that i'm using a Samsung Tablet with their Keyboard cover. Just saying because Samsung really likes to make custom stuff. Might actually not be easily solvable.

**Comment by peppy** [comment]
The point is Alt+F4 should not trigger anything on a mobile platform in the first place.

**Comment by bdach** [comment]
Testing with latest master of game + framework post-SDL3 migration, via an USB OTG adapter, I can't get alt-f4 to do anything. So tentatively closing as resolved/maybe-never-an-actual-issue until proven otherwise.

**Comment by FabiSahne** [comment]
I guess this was never an osu related bug, but a Samsung one. I've tried to recreate the issue again today, but Alt+F4 just closed the app like when closing it through the 'recent apps' list would. My best guess is Samsung tried to implement an Alt+F4 feature for their tablets, but (at least a year ago) this was not functioning as expected and so I mistook this issue as a osu issue, as that was the only app where Alt+F4 did weird things.
