### ISSUE TITLE
Veldrid OpenGL flickering and visual breakage

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#23088]
### Type

Other

### Bug description

When going to song select the game starts flickering and there is a lot of random green/white lines going through the screen. It recovers upon going back to main menu. Scrolling to change game volume produces a similar behaviour but also makes the visuals completely unresponsive.

### Screenshots or videos

https://user-images.githubusercontent.com/53346335/229367651-8698a38f-4c49-4382-8a11-433249dfdce0.mp4

### Version

2023.403.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/11132787/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11132788/performance.log)
[updater.log](https://github.com/ppy/osu/files/11132789/updater.log)
[network.log](https://github.com/ppy/osu/files/11132790/network.log)

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I'm experiencing issues with tabbing in and out. The stuff that's being rendered just freezes, the game is responsive, but I can't see.
I've tested the version before and then this version, and it's only on the new version. (its repeatable)
Here's a video of it freezing and flickering (!!!Epilepsy warning!!!):

https://user-images.githubusercontent.com/88291316/229382245-23650241-3f2e-4b77-b145-8cfff7c0e1d6.mp4
