### ISSUE TITLE
OpenGL (non-legacy) Flickers/Blinks/Unplayable

### ISSUE THREAD

**Issue by covelloz** [ppy/osu#23097]
### Type

Crash to desktop

### Bug description

When using openGL (non-legacy) on a linux workstation, game becomes unplayable due to screen flickering.

### Screenshots or videos

https://user-images.githubusercontent.com/20232054/229391281-7c00fc63-e041-4ce8-b966-1dae5dba7d3b.mp4

### Version

2023.403.0

### Logs

[logs.tar.gz](https://github.com/ppy/osu/files/11133896/logs.tar.gz)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/23093
https://github.com/ppy/osu/issues/23088
