### ISSUE TITLE
Storyboard not accounting for when loop events end

### ISSUE THREAD

**Issue by nolife99** [ppy/osu#23092]
### Type

Game behaviour

### Bug description

In http://osu.ppy.sh/s/1388590, at around 1:54, the scene mimics a concert with lights on the sides. In stable this plays correctly, but in lazer, the highlights end too early (they just disappear)
This behavior is fixed when the sprite has an explicit end time, and not a loop event with just a start time

Lazer:
![Screenshot 2023-04-02 143124](https://user-images.githubusercontent.com/89430659/229372060-6c2ff9b5-6d86-423c-af96-5a14f81349f4.png)

Stable:
![image](https://user-images.githubusercontent.com/89430659/229372233-570f4b6f-1aeb-4773-b5d0-37877bd99796.png)

Here's the .osb code for one of the disappearings
```Sprite,Background,Centre,"sb\hl.png",0,420
 L,99206,8
  F,12,0,176,1,0
  F,12,176,352,1,0
  F,12,352,529,1,0
  F,12,529,882,1,0
  F,12,882,1058,1,0
  F,12,1058,1235,1,0
  F,12,1235,1411,1,0
  F,12,1411,1764,1,0
  F,12,1764,1941,1,0
  F,12,1941,2117,1,0
  F,12,2117,2294,1,0
  F,12,2294,2824,1,0
 S,0,99206,,0.8931186
 C,0,99206,,220,57,38
```
As in the .osb code, there is no explicit end time, it needs to be calculated based on the given syntax in the loop.
If a command with the explicit end time of the sprite was added, this issue disappears.

### Version

2023.403.0

### Logs

Logs aren't needed for this (I think?)

**Comment by peppy** [comment]
The code you provided isn't even in the `.osb` file.

Could you please provide the line number or something?

**Comment by nolife99** [comment]
Sorry, the code was in an edited version
Here's the specific line number (24397) and code:
```Sprite,Background,Centre,"sb\circle2.png",-70,480
 L,99211,8
  F,18,0,176,1,0
  F,18,176,352,1,0
  F,18,352,529,1,0
  F,18,529,882,1,0
  F,18,882,1058,1,0
  F,18,1058,1235,1,0
  F,18,1235,1411,1,0
  F,18,1411,1764,1,0
  F,18,1764,1941,1,0
  F,18,1941,2117,1,0
  F,18,2117,2294,1,0
  F,18,2294,2823,1,0
 S,0,99211,,15
 C,0,99211,,220,57,38
 ```

**Comment by Coppertine** [comment]
Same issue arrises with an OWC custom tiebreaker map ([escape (the looking-glass, and what alice found there)](https://osu.ppy.sh/beatmapsets/1880652#osu/3871800) where the sprites `sb\bg2.jpg`, `sb\bg1.png`, `sb\frobj3.png`, `sb\frobj2.png`, `sb\frobj1.png`, `sb\color.png` (2 sprites) and the 1 animation all use Loops (either 64 or 321 loops depending on the sprite) without any explicit Fade out times.
This leads to every sprite excluding animation (due to the LoopForever tag, however still does not change scaling) to disapear after the first loop.

Here is essentailly the entire storyboard (background sprite and p.png sprites)
```
Sprite,Background,Centre,"sb\bg2.jpg",320,240
 L,0,64
  S,17,0,2645,0.1777778,0.1888889
  S,17,2645,5290,0.1888889,0.1777778
Sprite,Background,Centre,"sb\bg1.png",320,240
 L,0,64
  S,17,0,2645,1.008,1.056
  S,17,2645,5290,1.056,1.008
Animation,Background,Centre,"sb\chara_ani\chara morphing.png",320,240,56,100,LoopForever
 L,0,64
  S,17,0,2645,1.008,1.056
  R,17,0,2645,0,0.03490658
  S,17,2645,5290,1.056,1.008
  R,17,2645,5290,0.03490658,0
 F,0,0,340076,1
Sprite,Background,Centre,"sb\frobj3.png",320,240
 L,0,64
  S,17,0,2645,0.1777778,0.1888889
  S,17,2645,5290,0.1888889,0.1777778
Sprite,Background,Centre,"sb\frobj2.png",320,240
 L,0,64
  S,17,0,2545,0.1777778,0.2
  R,17,0,2745,0,0.06283186
  S,17,2545,5290,0.2,0.1777778
  R,17,2745,5290,0.06283186,0
Sprite,Background,Centre,"sb\frobj1.png",320,240
 L,0,64
  S,17,0,2645,0.1777778,0.2111111
  R,17,0,2645,0,-0.06981317
  S,17,2645,5290,0.2111111,0.1777778
  R,17,2645,5290,-0.06981317,0
Sprite,Background,Centre,"sb\color.png",320,240
 L,0,321
  F,0,0,529,0.4,0
  F,0,529,1058,0,0.4
 S,0,0,,0.96
Sprite,Background,Centre,"sb\color.png",320,240
 L,0,321
  F,0,0,529,0,0.4
  F,0,529,1058,0.4,0
 S,0,0,,0.96
```
