### ISSUE TITLE
Ensure all gameplay elements have maximum dimensions

### ISSUE THREAD

**Issue by peppy** [ppy/osu#23099]
### Type

Game behaviour

### Bug description

Currently users are quite free to make gameplay elements (taiko hit circles, osu! hit circles, catch fruit) as large as they wish. This can be used to make certain types of gameplay easier for the player.

We should enforce sane maximum sizes to avoid this kind of usage.

Relevant discussions:

https://github.com/ppy/osu/discussions/23025#discussioncomment-5504068

**Comment by toadsworth-jr** [comment]
This should probably resolve https://github.com/ppy/osu/issues/23870 too, although that case is for making the game more visually distracting rather than helping...

**Comment by bdach** [comment]
@toadsworth-jr we broke the sizing of that particular element on purpose because the stable sizing logic for it was pants-on-head dumb. nowhere near the same thing. this issue is about curtailing gaining gameplay advantages via the skinning system.
