### ISSUE TITLE
Game Wont Start

### ISSUE THREAD

**Issue by MosheBarkan** [ppy/osu#2310]
^ title ^

[runtime.log](https://github.com/ppy/osu/files/1844398/runtime.log)

**Comment by escolasticokid** [comment]
I think that was the build that everyone had issues opening
Open the previous build and update to the newest or just redownload the newest version

**Comment by MosheBarkan** [comment]
same runtime error

**Comment by xKyoma** [comment]
For me it didn't work at first too. I deleted the osulazer folder in Local (C:\Users\xxx\AppData\Local\osulazer)
and the osu folder in Roaming (C:\Users\xxx\AppData\Roaming\osu). After I installed the newest version again it worked.
