### ISSUE TITLE
Memory leak when scrolling through beatmap carousel

### ISSUE THREAD

**Issue by liesened** [ppy/osu#23121]
### Type

Performance

### Bug description

So when I was playing for a while, I noticed increased memory usage, osu took up to 2 gb in the task manager or so. Didn't find anything similar, so I'm creating a new issue.

See the attached video, the memory leak happens when scrolling through the beatmap carousel. The way you scroll it pretty much doesn't matter, it leaks if scrolling with mouse wheel, as well as if scrolling with arrow keys. It also leaks if scrolling the same beatmaps. Except it only doesn't if you scroll with the right mouse button.

It happens on both new and legacy OpenGL renderers and on Direct3D11, too, both in Fullscreen and Windowed modes.

Besides ArrayPool numbers in the global statistic menu, it seems that "Total constructed" value under the Drawables also grows very quickly when scrolling.

### Screenshots or videos

Sorry for the poor quality, that's the best I could fit into github's limits.

https://user-images.githubusercontent.com/101940285/229611539-3c065325-7b10-42cf-9599-06e4071ab399.mp4

00:22 - scrolling with mouse wheel
00:47 - RMB and then mouse wheel again
01:17 - scrolling with arrow keys
03:05 - scrolling same beatmaps

### Version

2023.403.1-lazer

### Logs

(106 mb zip bomb beware, performance.log blows up for some reason)
[logs.zip](https://github.com/ppy/osu/files/11141144/logs.zip)

**Comment by bdach** [comment]
The "total constructed" count rising is normal *and natural*. It is the total count of *constructed* drawables, but that doesn't mean that all of them are *still active*. Some of them may well have been disposed of already. `ArrayPool` numbers rising are also normal. The memory is *pooled*. Most of it is being *returned*, since both numbers shown are roughly equal. A leak could happen if the memory wasn't being returned.

If you have proof of a memory leak then please demonstrate it properly because there is no real evidence of one in this report. Demonstrating it properly would entail:

- stopping the scroll and seeing if the memory reclaims properly (if it doesn't, then that may be something to follow up)
- showing the memory usage while you're reproducing (it's not visible anywhere)
- (preferable) attaching a proper profile from dotmemory or similar

**Comment by peppy** [comment]
To confirm, are you testing this with global statistics open or closed? Keeping it open can actually add to memory issues which would otherwise be avoided (it turns on extra analysis).

**Comment by i44p** [comment]
Can reproduce on my laptop with Ryzen 5500U APU on 2023.326.1-lazer with much smaller beatmap database (155 shown).

Having global statistics not opened appears to have little to no effect, as this happens in both cases. The "Clear all caches" button doesn't affect Gen2, unless you exit the carousel back to the main menu. Once you exit the carousel (to the main menu!) though, GC clears most of Gen2 just fine. But it doesn't if you open a beatmap editor instead, for example.

Looks like something (related to CarouselBeatmapSet?) is being stored in memory (but not necessarily _used_) until the carousel object instance or something gets destroyed.

To sum this up, following these steps results in Gen2 not being recovered at all even if triggering GC, while constantly allocating new memory (until there's no more memory to allocate?):

1. open osu!
2. go to the carousel
3. _scroll intensely_
4. play beatmap
6. _scroll intensely_
7. play beatmap
8. etc...

If you do this however, Gen2 gets cleaned or actually already allocated memory gets reused, depending on the mood of the GC:

1. open osu
2. go tho the carousel
3. _scroll intensely_
4. play beatmap
5. exit to the main menu <-- the critical step
6. go to the carousel
7. _scroll intensely_
8. play beamap
9. exit to the main menu <-- the critical step
10. etc...

I could share dotmemory workspace with memory snapshots if required, but that's probably easier to reproduce this yourself.

**Comment by liesened** [comment]
Can reproduce on my laptop with Ryzen 5500U APU on 2023.326.1-lazer with much smaller beatmap database (155 shown).

Having global statistics not opened appears to have little to no effect, as this happens in both cases. The "Clear all caches" button doesn't affect Gen2, unless you exit the carousel back to the main menu. Once you exit the carousel (to the main menu!) though, GC clears most of Gen2 just fine. But it doesn't if you open a beatmap editor instead, for example.

Looks like something (related to CarouselBeatmapSet?) is being stored in memory (but not necessarily _used_) until the carousel object instance or something gets destroyed.

To sum this up, following these steps results in Gen2 not being recovered at all even if triggering GC, while constantly allocating new memory (until there's no more memory to allocate?):

1. open osu!
2. go to the carousel
3. _scroll intensely_
4. play beatmap
6. _scroll intensely_
7. play beatmap
8. etc...

If you do this however, Gen2 gets cleaned or actually already allocated memory gets reused, depending on the mood of the GC:

1. open osu
2. go tho the carousel
3. _scroll intensely_
4. play beatmap
5. exit to the main menu <-- the critical step
6. go to the carousel
7. _scroll intensely_
8. play beamap
9. exit to the main menu <-- the critical step
10. etc...

I could share dotmemory workspace with memory snapshots if required, but that's probably easier to reproduce this yourself.

**Comment by peppy** [comment]
Sharing dotmemory snapshot (or even just a dump from task manager) would be appreciated.

Before doing so, can you return to the main menu and smash the "clear caches" button about 10 times then wait 10 seconds?

**Comment by liesened** [comment]
Just found out that using even smaller database (128 matches shown in the carousel, 22 beatmapsets) doesn't start memory growth. Hovewer, after adding only one more beatmapset (131 matches, 23 beatmapsets, as in the video) it starts "leaking".

https://user-images.githubusercontent.com/101940285/235842720-14ff4954-96d4-47c9-91f0-3d08884325fd.mp4

If allocating with another application, Gen2 usage doesn't drop and osu! memory likely goes to the page file. (I used `f = list(range(10**8))` in python shell)
Sending you memory dumps.

**Comment by peppy** [comment]
@liesened i don't suppose you could attach your database?

**Comment by peppy** [comment]
Also to confirm, returning to the main menu then clearing caches *always fixes this issue* correct?

**Comment by liesened** [comment]
>returning to the main menu then clearing caches always fixes this issue correct?

From what I can tell, yes.

>I'm seeing 2424 CarouselBeatmapSet objects, which would imply that you have that many loaded.

This is an older dump I did in April, not sure how many beatmaps were there because I deleted the osu!lazer database since then and I obviously can't check the number, but 2424 looks about right.

>i don't suppose you could attach your database?

How would I do that? Is there any standard way to do this or could I just have sent you the zipped `%appdata%/osu` folder?
