### ISSUE TITLE
Flipping skinning components causes them to be unmovable

### ISSUE THREAD

**Issue by probablyy** [ppy/osu#23124]
### Type

Game behaviour

### Bug description

I wanted to flip the hit error bar so it would be like it is on stable, but after doing that it was stuck in place. This is fixed by flipping it again, but it is highly inconvenient.

### Screenshots or videos

https://www.youtube.com/watch?v=GRhYk4aCDGU

### Version

osu! 2023.326.1-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/11145175/network.log)
[performance.log](https://github.com/ppy/osu/files/11145176/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11145177/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11145178/updater.log)
[database.log](https://github.com/ppy/osu/files/11145179/database.log)
[input.log](https://github.com/ppy/osu/files/11145181/input.log)

**Comment by probablyy** [comment]
Not sure why it says crash to desktop, because I didn't put that

**Comment by uzervlad** [comment]
Probably #23042 ?

**Comment by peppy** [comment]
yep. updated your game and this should be fixed.
