### ISSUE TITLE
[Question] The future of osulazer skinning

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2312]
From what I can see, skins don't seem to get saved in a readable format (inside client.db), which prevents users from modifying their skins in any way. Is this intentional, or will this be changed in the future? It personally is very tedious for a skinner if they cannot test their newly created elements inside of osu, and have to re-import again and again. It also won't allow to modify and fix up elements that we won't know correctly work.

**Comment by smoogipoo** [comment]
Skinning will be completely integrated within osu! You will be able to select + drag in textures for skinnable components and alter the skin settings, all from within osu!.

So yes, this is intended.

**Comment by smoogipoo** [comment]
And also combine elements from multiple skins together if desired.
