### ISSUE TITLE
Unranked mods should have a score multiplier of 1x and another color

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#2313]
Will do this. I want to know the multiplier when I have an unranked mod on. I just can't decide on a color.
![](https://puu.sh/zOE86/902eae79ab.png)

**Comment by jorolf** [comment]
What do you mean by color? I don't think the mod icons should have another color

**Comment by Joehuu** [comment]
I meant the score multiplier.

**Comment by Aergwyn** [comment]
Shouldn't the multiplier itself stay green/red depending on change? Maybe you want the `(Unranked)` to have a different colour to be more noticeable?

**Comment by Joehuu** [comment]
Yeah, unranked should have a color of its own and be separated from the multiplier's color.

**Comment by Aergwyn** [comment]
Imo you could play around with the multiplier having a different colour than red for anything below 1x. Red `(Unranked)` is already super fitting.

**Comment by Express76** [comment]
I mean like you can change to blue like the color of the unranked icons. But imo its fine how it is atm.
