### ISSUE TITLE
Linux sound system is broken with pipewire and another process that creates sound. No sound.

### ISSUE THREAD

**Issue by hashelq** [ppy/osu#23139]
### Type

Game behaviour

### Bug description

```
OS: NixOS 22.11
Sound system: ALSA / pipewire
Worked before?: Yes, I played old version of osu (don't remember version) and it worked fine!
```
When I start the game with another process that creates sound (like mpv), the game has no sound at all (no matter what sound option I select in the settings).

If I start the game without any other process like this, it might either have or not have sound. But if there is no sound, I go to the settings and select another sound output, it works.

Stderr/stdout:
```
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
```

### Version

2023.403.1

### Logs

[input.txt](https://github.com/ppy/osu/files/11166038/input.txt)
[network.log](https://github.com/ppy/osu/files/11166039/network.log)
[performance.log](https://github.com/ppy/osu/files/11166040/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11166041/runtime.log)

Other logs seem outdated

**Comment by peppy** [comment]
As per previous, you're setting an envvar that is breaking this. Don't do that.

**Comment by hashelq** [comment]
```
firejail --private=. --noprofile --env=LD_LIBRARY_PATH=/nix/store/yjk16nkvp9i6qq2mqm498g1h0i3lfcd6-icu4c-72.1/lib /nix/store/09xjy19wf9lf4h3ink6bnfpd1sra940l-user-environment/bin/appimage-run osu.AppImage.6
```

Needs to be reopened, this problem is not fixed even after installing libicu.

**Comment by hashelq** [comment]
[input.log](https://github.com/ppy/osu/files/11166171/input.log)
[network.log](https://github.com/ppy/osu/files/11166172/network.log)
[performance.log](https://github.com/ppy/osu/files/11166173/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11166174/runtime.log)

**Comment by hashelq** [comment]
https://github.com/ppy/osu/issues/23142

**Comment by nferhat** [comment]
> As per previous, you're setting an envvar that is breaking this. Don't do that.

Even without the environment variable, this can also happen.
Willing to provide more information for this!

**Comment by hashelq** [comment]
> > As per previous, you're setting an envvar that is breaking this. Don't do that.
> 
> Even without the environment variable, this can also happen. Willing to provide more information for this!

ig that's some wired pipewire/media-server bug, afaik lazer uses either pulseaudio or alsa if available, so make sure the pipewire can handle it properly.
