### ISSUE TITLE
Cannot open beatmap page: game crashes.

### ISSUE THREAD

**Issue by hashelq** [ppy/osu#23140]
### Type

Crash to desktop

### Bug description

When I open any beatmap's page, the game freezes and crashes.

### Version

2023.403.1

### Logs

[input.log](https://github.com/ppy/osu/files/11166072/input.log)
[input.txt](https://github.com/ppy/osu/files/11166075/input.txt)
[network.log](https://github.com/ppy/osu/files/11166076/network.log)
[performance.log](https://github.com/ppy/osu/files/11166077/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11166078/runtime.log)

**Comment by hashelq** [comment]
Ah, I have take a look on the logs. Inb4, my run command is:
```
firejail --private=. --noprofile --env=DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 /nix/store/09xjy19wf9lf4h3ink6bnfpd1sra940l-user-environment/bin/appimage-run osu.AppImage.6
```

**Comment by peppy** [comment]
Your invariant envvar is probably breaking this. Check the error.

We can't support per-configuration issues like this, so please investigate this further via google.
