### ISSUE TITLE
osu!lazer shows exit dialogue but not exiting

### ISSUE THREAD

**Issue by JeromTWinL** [ppy/osu#23148]
### Type

Game behaviour

### Bug description

I'm not sure how do I mention the title, but when i change the renderer from "OpenGL (Legacy)" to "Automatic" (when it doesn't include "(OpenGL (Legacy))"), It shows the "you should restart osu!lazer to use the new renderer" dialogue, and "you want to exit osu!lazer?" dialogue, when I click "let me out", it says "see you next time" (not that point) and it doesn't close, I expect it to close or show "new renderer will be used at next startup"

### Screenshots or videos

https://user-images.githubusercontent.com/84004577/230434370-4561f58f-e44c-4efa-838a-89d643aaf715.mp4

And i can only see the black screen, I exited manually.

### Version

2023.403.1 (Android)

### Logs

[logs.zip](https://github.com/ppy/osu/files/11172391/logs.zip)

**Comment by bdach** [comment]
We're aware of this, but for now we won't be fixing it as there is 0 reason to switch renderer on android (as automatic and legacy opengl are one and the same thing).

This will be fixed properly once android can actually support other renderers.

**Comment by JeromTWinL** [comment]
Thanks for the information!
