### ISSUE TITLE
When I click on my avatar, nothing appears, but an yellow line.

### ISSUE THREAD

**Issue by hashelq** [ppy/osu#23141]
### Type

Game behaviour

### Bug description

ENV changes:
```
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/105644136/230264368-44aadc86-6579-40eb-b2af-8622974a9d5b.png)

### Version

2023.403.1

### Logs

[input.log](https://github.com/ppy/osu/files/11166100/input.log)
[network.log](https://github.com/ppy/osu/files/11166101/network.log)
[performance.log](https://github.com/ppy/osu/files/11166102/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11166104/runtime.log)

**Comment by peppy** [comment]
As per previous, you're setting an envvar that is breaking this. Don't do that.
