### ISSUE TITLE
Timing: Bugged audio drivers / hardware can cause gameplay to run too slowly

### ISSUE THREAD

**Issue by joshuk** [ppy/osu#23149]
### Type

Game behaviour

### Bug description

Day to day I currently use an external bluetooth speaker (a Sony SRS-XB01, to be specific) while doing general browsing and computer use, including watching replays on osu!

While changing my audio output device on stable, I noticed a device called 'Headset Earphone (SRS-XB01 Hands-Free AG Audio)':
![lazer-output-device](https://user-images.githubusercontent.com/25204957/230433947-8acd537a-6860-4e9f-a72e-5cd54bc6d9de.PNG)
Note that the screenshot from lazer, however the same audio device is also available on stable.

When switching to this audio device, all audio in the game noticably slows down (to around 50% speed I reckon). When starting a map, the gameplay also slows down accordingly. Stable seems to detect this, giving this error when submitting a score:
![stable-submission-error](https://user-images.githubusercontent.com/25204957/230435002-6101c6f7-11ed-4fea-8f54-1c40dbdd3e09.PNG)

However, when doing this same thing in lazer, the error isn't present and the score submits. As an example, see my score on [Silvia - Vertex Delta [GAMMA]](https://lazer.ppy.sh/scores/2268017156). This score is 'cheated' in this way, which allowed me to play much faster than I am actually able to.

Happy to provide any further information/recordings if needed. Thanks.

### Version

2023.403.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/11172316/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11172318/updater.log)
[database.log](https://github.com/ppy/osu/files/11172319/database.log)
[input.log](https://github.com/ppy/osu/files/11172321/input.log)
[network.log](https://github.com/ppy/osu/files/11172322/network.log)
[performance.log](https://github.com/ppy/osu/files/11172323/performance.log)

**Comment by peppy** [comment]
I have no idea what "timewarp" means but the fact you do is likely incriminating. Could you please update the issue description to make it less obvious that you are a cheater and know the cheater terminology.

**Comment by joshuk** [comment]
I don't think that knowing the name of a cheating technique that's been used by several top players in the past therefore means that I'm a cheater, but appreciate the baseless accusation. Really encourages people to help point out potential integrity issues with your game.

Either way, I've updated the title to try and explain it a bit better. Feel free to ask again if you still don't understand 🙂

**Comment by peppy** [comment]
As for how we should handle this (whether it should be strictly moved to the anticheat module or also implemented in the game in a way that the user can be made aware that their hardware is borked), will require further discussion.

**Comment by joshuk** [comment]
My two cents: I feel like stable's implementation works fine here, where it shows an error message and prevents score submission.

Since this is only triggered by the user changing their audio device I could certainly see it being triggered innocently by someone who's maybe unsure on what they're doing. Don't think it necessarily indicates cheating.

**Comment by peppy** [comment]
That's not what I was implying. It just depends where we place the duty of checking this kind of thing in the game structure.

**Comment by beltzawoo** [comment]
I accidentally found another way to replicate (on Debian Linux with Pipewire, but distro-agnostic without a doubt), while messing with my settings for latency:
1. launch osu!
2. set the clock quantum to a very high value, such as with the command `pw-metadata -n settings 0 clock.force-quantum 4096`
3. the game slows down while allowing scores to be submitted

**Comment by rszyma** [comment]
My DAC sometimes encounters a bug where it's running at 48khz but when a program on my pc (linux) wants to run audio @ 44.1khz and it results in the sped up audio. I got this a few times in osu too, so it's kind of opposite than what this issues is about, but either way, I don't think it should be even possible to for osu gameplay to run faster/slower because mismatch in sample rate.

**Comment by YourSandwich** [comment]
> I accidentally found another way to replicate (on Debian Linux with Pipewire, but distro-agnostic without a doubt), while messing with my settings for latency:
> 
> 1. launch osu!
> 2. set the clock quantum to a very high value, such as with the command `pw-metadata -n settings 0 clock.force-quantum 4096`
> 3. the game slows down while allowing scores to be submitted

I can confirm this, it also happens randomly since Pipewire is setting the quantum clock dynamically. Which results in a slowed down and distorted audio in some cases, changing the outputs fixes it.
