### ISSUE TITLE
Shift-delete no longer works to delete beatmaps at song select

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2315]

**Comment by leonkouz** [comment]
I haven't been able to pinpoint the exact cause of the bug but if I comment out 
`newlyPressed = newlyPressed.OrderByDescending(b => b.KeyCombination.Keys.Count()).ToList();` from the method below in KeyBindingContainer.cs, I find this works correctly.


    private bool handleNewPressed(InputState state, InputKey newKey, bool repeat)
        {
            var pressedCombination = KeyCombination.FromInputState(state);

            bool handled = false;
            var bindings = repeat ? KeyBindings : KeyBindings.Except(pressedBindings);
            var newlyPressed = bindings.Where(m =>
                m.KeyCombination.Keys.Contains(newKey) // only handle bindings matching current key (not required for correct logic)
                && m.KeyCombination.IsPressed(pressedCombination));

            if (isModifier(newKey))
                // if the current key pressed was a modifier, only handle modifier-only bindings.
                newlyPressed = newlyPressed.Where(b => b.KeyCombination.Keys.All(isModifier));

            // we want to always handle bindings with more keys before bindings with less.
            //newlyPressed = newlyPressed.OrderByDescending(b => b.KeyCombination.Keys.Count()).ToList();

            if (!repeat)
                pressedBindings.AddRange(newlyPressed);

            foreach (var newBinding in newlyPressed)
            {
                handled |= PropagatePressed(KeyBindingInputQueue, newBinding.GetAction<T>());

                // we only want to handle the first valid binding (the one with the most keys) in non-simultaneous mode.
                if (simultaneousMode == SimultaneousBindingMode.None && handled)
                    break;
            }

            return handled;
        }

**Comment by Aergwyn** [comment]
It's because the Textbox in SongSelect forces focus and eats the KeyDown. You're way too far there. :3
