### ISSUE TITLE
Spinners show incorrect score in editor

### ISSUE THREAD

**Issue by UnknownRedFoxDev** [ppy/osu#23160]
### Type

Game behaviour

### Bug description

When you put a spinner in the editor, at first it works, but if you rewind back to the start of it, while the song is played, the spinner point value gets add to the previous time that it was used, else than just resetting to zero.

### Screenshots or videos

https://user-images.githubusercontent.com/114443299/230719499-17ee19ff-78de-4f9c-a374-10bcc8d34917.mp4

### Version

Lazer 2023.403.1

### Logs

[performance.log](https://github.com/ppy/osu/files/11183138/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11183139/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11183140/updater.log)
[database.log](https://github.com/ppy/osu/files/11183141/database.log)
[input.log](https://github.com/ppy/osu/files/11183142/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11183143/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11183144/network.log)

**Comment by peppy** [comment]
Fortunately, this doesn't make it "broken" and is only a visual concern. Please title your issues better in the future!

**Comment by Gabixel** [comment]
This is also already covered in #10455 I think

**Comment by UnknownRedFoxDev** [comment]
Right, thanks for informing that it was already covered, even though I search before sending, I did not find something that was covering the bonus point accumulation.

**Comment by bdach** [comment]
Going to close as duplicate as mentioned above.
