### ISSUE TITLE
Argon song progress placed by the player unfolds in the wrong direction

### ISSUE THREAD

**Issue by RBQcat** [ppy/osu#23163]
### Type

Cosmetic

### Bug description

1. Open Skin Editor
2. Place Argon song progress
3. Exit Skin Editor
4. Put the cursor on Argon song progress

### Screenshots or videos

https://user-images.githubusercontent.com/74862110/230723650-81554d55-48e7-41ae-b724-0e60a54e724c.mp4

### Version

2023.403.1

### Logs

[network.log](https://github.com/ppy/osu/files/11183363/network.log)
[performance.log](https://github.com/ppy/osu/files/11183364/performance.log)
[database.log](https://github.com/ppy/osu/files/11183365/database.log)
[runtime.log](https://github.com/ppy/osu/files/11183366/runtime.log)

**Comment by Gabixel** [comment]
This is intended. It depends on the "origin" of the `SongProgress` component. Try setting it to "BottomCentre":
![image](https://user-images.githubusercontent.com/43073074/230741180-6a754b22-48de-4660-9946-7622790af676.png)
