### ISSUE TITLE
Osu not launching on Appimage (it worked but I changed the renderer to see the difference in performance but it bricked the game)

### ISSUE THREAD

**Issue by Samir2zk** [ppy/osu#23170]
### Type

Crash to desktop

### Bug description

I changed the game renderer to something else and in the logs itself it says that "no usable renderer was found" apart of the OTD thing. I am pretty noob at linux but I reinstalled the appimage and deleted the config folders nothing fixed it yet.

### Screenshots or videos

![Screenshot from 2023-04-08 22-41-00](https://user-images.githubusercontent.com/88938482/230743784-7ebc347a-ee62-4007-ae23-a84a29dc8ad3.png)

### Version

2023.403.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/11184287/runtime.log)

**Comment by Samir2zk** [comment]
I hope I wrote this in the right place.

**Comment by OninDynamics** [comment]
Refer to https://github.com/ppy/osu/issues/22960#issuecomment-1484165825 (Issue #22960).

tl/dr; go to `~/.local/share/osu/` then open up `framework.ini`.

On line 16: `Renderer = Vulkan`

Change `Vulkan` to `OpenGL (Legacy)`.

**Comment by bdach** [comment]
Please perform the steps described above for now. The vulkan renderer is not yet ready for use.

**Comment by Samir2zk** [comment]
hmhmh I changed it to OpenGL (Legacy) within the framework.ini with gedit. But, everytime I launch the game it goes into automatic and goes into Vulkan, doesn't stay with OpenGL. Is there some way to enforce the use of OpenGL? btw I am using a 2010 x201t thinkpad. there a way to make the game run better or should I just stick with stable (better performance)
