### ISSUE TITLE
mania note animation clocks differ from stable

### ISSUE THREAD

**Issue by Jolomann** [ppy/osu#23187]
### Type

Game behaviour

### Bug description

I'm no programmer so just a disclaimer - technical terms I'm using are purely guesses from what I can see in-game

In stable, when a note enters the screen space, its animation starts at frame 0 and then loops the animation. This happens separately for every single note so they all have local animation clocks

In lazer, it seems that instead of each note having their own clock, now it's each column that has a separate clock, and every note in a specific column follows the same clock. A column's clock starts when the first note in the column appears in a map. So if the map starts with, say, a 4-note chord in 4k, they sync up. If each column's first note starts at separate times, the clocks desync.

My skin has a gradient as the animation and the effect is very trippy when each column is at a different time in the animation. This is where I want to ask which behaviour is intended because stable is a bit non-traditional for VSRG note animations. Other games like StepMania use a global clock for note animations where the animation runs continuously regardless of notes spawning, and each column follows it so all notes sync up.

I strongly prefer the stable behaviour but obviously that's biased because my skin depends on it(that aside I also think it looks better for animations in general). Which behaviour is generally the one sought after? Right now the implementation falls somewhere in-between stable and the example from StepMania. Kinda global but still localised to each column so they can end up desynced. I'd say it makes more sense to have it be one or the other, so either a single global clock or a clock for each and every note(with strong preference to the latter).

Apologies if this is confusing to read.. It's not the easiest thing to explain through text

To summarise:
stable note enters screen -> animation starts at frame 0 for each note
lazer note enters screen -> follows clock for specific column which starts with the first note in that column during the map

### Screenshots or videos

For clarity this is the animation sequence
![notes](https://user-images.githubusercontent.com/33073129/231256557-e92b25b9-a78e-4122-a276-d8e594fe8fdb.png)

Screenshot of difference (Video shows it better)
![vlcsnap-2023-04-11-20h38m18s123](https://user-images.githubusercontent.com/33073129/231258213-a59f3ba6-55af-4ff4-b7df-92ed632c7bb8.png)

Stable vs lazer video
https://streamable.com/05860x

### Version

2023.403.1-lazer

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/11203759/legacy-ipc.log)
[performance.log](https://github.com/ppy/osu/files/11203760/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11203761/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11203762/updater.log)
[database.log](https://github.com/ppy/osu/files/11203763/database.log)
[input.log](https://github.com/ppy/osu/files/11203764/input.log)

**Comment by peppy** [comment]
Would have been nice if you included your full skin so there as no guesswork.

I've got this working but cannot guarantee the timing is the same as stable. And i'm not sure we need / want to. But it's a starting point I guess.
