### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [ppy/osu#23180]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by bdach** [comment]
cc @peppy (not sure if we want to be enabling this, or if you prefer to receive disclosure reports to email directly)

**Comment by peppy** [comment]
I'll cautiously enable this. The original poster looks to be automatically(?) spamming this on all our repos. We'll see what gets reported I guess.
