### ISSUE TITLE
Music keeps playing on map selection

### ISSUE THREAD

**Issue by Sarisan** [ppy/osu#23183]
### Type

Game behaviour

### Bug description

While selecting maps if I suddenly stop currently selected beatmap music I can hear music of beatmaps previously selected, I don't really know how to reproduce the bug, but its second time I get it.

### Version

2023.403.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/11200770/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11200773/performance.log)
[network.log](https://github.com/ppy/osu/files/11200774/network.log)
[input.log](https://github.com/ppy/osu/files/11200776/input.log)
[database.log](https://github.com/ppy/osu/files/11200777/database.log)

**Comment by bdach** [comment]
Please upload a video of this or describe the issue better at least because I have no idea what this issue is trying to report.

**Comment by Sarisan** [comment]
> Please upload a video of this or describe the issue better at least because I have no idea what this issue is trying to report.

When I select maps/quitting maps their music keeps playing at background at very low volume . If I try to play map which music starts with silence I can clearly hear music porridge. I'm closing this issue since I couldn't catch this bug again.
