### ISSUE TITLE
Can't change scroll speed for taiko

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu#23188]
### Type

Game behaviour

### Bug description

Adding a timing point and changing the SV doesn't work

### Screenshots or videos

https://user-images.githubusercontent.com/81715029/231268945-9af4e461-a9ee-4be5-b22a-5c9722a2191a.mov

### Version

2023.403.1

### Logs

[database.log](https://github.com/ppy/osu/files/11204223/database.log)
[input.log](https://github.com/ppy/osu/files/11204225/input.log)
[network.log](https://github.com/ppy/osu/files/11204226/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/11204227/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11204228/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11204229/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11204230/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/11204231/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11204232/runtime.log)

**Comment by bdach** [comment]
Mostly the same thing as #17127, but it can be its own issue I guess

**Comment by reo-the-enby** [comment]
Weird, it only affected the note that was on the timing point. All other notes after were still the same SV when I opened it before.
