### ISSUE TITLE
weird cut-off on the black glow on the arrows during a break section

### ISSUE THREAD

**Issue by OIAGYT** [ppy/osu#23210]
### Type

Cosmetic

### Bug description

I was playing and i randomly noticed this little detail.

### Screenshots or videos

![osu_2023-04-15_20-46-55](https://user-images.githubusercontent.com/120472586/232250414-50147363-9259-4864-960f-8ae56a4b2226.jpg)

### Version

2023.403.1-lazer

### Logs

this is a cosmetic bug, so i can't find any logs for this

**Comment by peppy** [comment]
no idea what look at

**Comment by OIAGYT** [comment]
look at the arrow, there is black glow and on the top you can see the glow
cut out. It's not a perfect glow circle.

**Comment by peppy** [comment]
Weirdly, I can't repro this one. Will need to figure out what causes it to happen.

![osu! 2023-05-02 at 08 14 48](https://user-images.githubusercontent.com/191335/235614688-d8e4448a-eb68-41ac-a29e-37a9f53fa578.png)

**Comment by OIAGYT** [comment]
Could it be cause i play on 800x600 screen resolution?

**Comment by peppy** [comment]
Thanks, I think I can reproduce at a lower resolution.
