### ISSUE TITLE
Game no longer launches on IOS after the render update

### ISSUE THREAD

**Issue by CastanaEddd** [ppy/osu#23218]
### Type

Crash to desktop

### Bug description

After updating the game to 2023.326.0 the game crashes instantly upon opening, unfortunately leaving no logs behind afterwards. The issue still persists after updating to 2023.403.1

Runs perfectly fine after downgrading to 2023.305.0
Tested on a iPhone 6s running IOS 14.3 (18C66)

### Screenshots or videos

https://user-images.githubusercontent.com/128545778/232326389-be48299b-914a-4b6a-9b27-43bf1e38a522.MOV

### Version

2023.403.1-lazer (Sideloaded) 

### Logs

Logs unavailable

**Comment by peppy** [comment]
We can't support "side loaded" installs sorry.

**Comment by CastanaEddd** [comment]
Ah sorry, wasn't aware of that being a thing. I've looked through both the readme and contributing guidelines but i don't recall anything like that being mentioned. Could be worth posting some sort of disclaimer to avoid further cases of possible confusion in the future. 

Once again sorry for taking away from your time. Thank you.

**Comment by peppy** [comment]
The fact IPAs are provided is a bit of an easter egg right now. Will probably stop once we have things live on the app store.
