### ISSUE TITLE
Huge lag spike after long new combo in osu catch

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu#23220]
### Type

Crash to desktop

### Bug description

When exiting a long combo (50-100+), there's a huge lag spike.
I'm on a 3070ti 32gb ram etc computer, this issue is much worse for those with weaker setups
Should probably also add that general performance drops rapidly during long combos.

example ranked maps:
https://osu.ppy.sh/beatmapsets/1668029#fruits/3852338 
https://osu.ppy.sh/beatmapsets/1521219#fruits/3337690 (ending)
https://osu.ppy.sh/beatmapsets/725171#fruits/1541573 (somewhere 3/4 through)

### Screenshots or videos

https://user-images.githubusercontent.com/30382015/232461345-de9a35f2-7128-480d-83e0-5dc12300b9c7.mp4

### Version

2023.401.1-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11249107/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11249108/updater.log)
[database.log](https://github.com/ppy/osu/files/11249109/database.log)
[input.log](https://github.com/ppy/osu/files/11249110/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11249111/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11249112/network.log)
[performance.log](https://github.com/ppy/osu/files/11249113/performance.log)

**Comment by peppy** [comment]
Should be improved vastly with #23275.
