### ISSUE TITLE
Previous track playback shows filtered difficulties 

### ISSUE THREAD

**Issue by tomm13** [ppy/osu#23225]
### Type

Game behaviour

### Bug description

Steps to reproduce:
1. Select a beatmap set with multiple beatmaps (for example, a 2* and a 3*)
2. Adjust the difficulty range to 0-2*, and the 3* difficulty hides as expected
3. Select a different beatmap set
4. Use the previous track keybind twice (F9 by default)
5. All beatmaps expand

Done on M1 Macbook Pro.

### Screenshots or videos

https://user-images.githubusercontent.com/42684333/232602600-65d8be05-eccc-4a2b-ae74-796c0ee7ffaf.mov

### Version

2023.403.1

### Logs

[database.log](https://github.com/ppy/osu/files/11255542/database.log)
[input.log](https://github.com/ppy/osu/files/11255543/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11255544/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11255545/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/11255546/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11255547/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11255548/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11255549/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/11255550/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11255551/runtime.log)

**Comment by peppy** [comment]
This is intended. You're using the global music controller. This has the priority to select filtered beatmaps.
