### ISSUE TITLE
Large parts of long song titles getting cut off in info wedge and results screen

### ISSUE THREAD

**Issue by nbvdkamp** [ppy/osu#2322]
As you can see in the screenshots below long song titles can get cut off in multiple cases.
It's worse in the info wedge because there the title is prefixed with the source of the song.
I don't know if there is/could be a good general solution for this type of problem or if it needs to be addressed on a case by case basis.
![carousel_text_wrap](https://user-images.githubusercontent.com/15140758/38033730-f799d4e6-32a0-11e8-9e80-5f983c91179c.png)
![score_screen_text_wrap](https://user-images.githubusercontent.com/15140758/38033731-f7b858d0-32a0-11e8-86e2-2e50cebd6a58.png)
Example map: https://osu.ppy.sh/beatmapsets/122111

**Comment by Frontear** [comment]
Potentially intentional, since this would be preferred over allowing overflow. Perhaps line break when it reaches its width limit?

**Comment by ticotaco72** [comment]
same with total score
![osu_2018-06-25_22-53-22](https://user-images.githubusercontent.com/32620809/41875601-a9f12926-78cb-11e8-830e-ed48b5a55a76.jpg)

**Comment by peppy** [comment]
See #3504.
