### ISSUE TITLE
`Difficulty Multiplier` show wrong value when adjust mod and preset was selected

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#23234]
### Type

Game behaviour

### Bug description

First select a mod preset, then adjust mod customization (e.g. adjust HT speed from 0.75x to 0.9x), then `Difficulty Multiplier` will not update

### Screenshots or videos

https://user-images.githubusercontent.com/34775378/233113614-8848e411-b607-411f-865d-b674f7de2fa5.mp4

### Version

2023.419.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/11274430/runtime.log)
right

**Comment by Hy0tic** [comment]
is this issue fixed? I can't replicate it

**Comment by Joehuu** [comment]
Still reproducable.

![Kapture 2023-04-21 at 19 50 26](https://user-images.githubusercontent.com/35318437/233758150-fca51dcf-ef9e-498b-8590-139c338e3d65.gif)

**Comment by peppy** [comment]
Fixed via #23824.
