### ISSUE TITLE
Extremly high ram usage on the new renderer.

### ISSUE THREAD

**Issue by qwert0p** [ppy/osu#23253]
### Type

Performance

### Bug description

When using new OpenGL renderer, ram usage is absurdly high and after closing the game ram usage somehow won't go down(i wasn't been able to track down where excatly is it held in the system but it only goes away after reboot).

This started happening on the latest release and legacy render works just fine.
I've tried downgrading mesa to 22.3, using old "radeon" kernel driver and running on x11, nothing changed. I've also tried running on the "zink" mesa OpenGL driver, it has the same high memory usage, but memory gets release after closing the game unlike RadeonSI driver.
Running Arch Linux 6.1.0-tkg-pds w/ Mesa 23.0.2 on Radeon HD 7750.

Looks like some obscure driver issue to me, but i wasn't been unable to reproduce it anywhere else but the latest version of lazer with the new renderer.

### Screenshots or videos

https://user-images.githubusercontent.com/73023925/233338431-407be85f-f41c-4477-bb2d-84f75984da7e.mp4

### Version

2023.419.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/11285096/runtime.log)
[network.log](https://github.com/ppy/osu/files/11285097/network.log)
[performance.log](https://github.com/ppy/osu/files/11285098/performance.log)
[input.log](https://github.com/ppy/osu/files/11285099/input.log)
[database.log](https://github.com/ppy/osu/files/11285100/database.log)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/23252
