### ISSUE TITLE
Osu lazer's text and icons broken

### ISSUE THREAD

**Issue by Xeox771** [ppy/osu#23267]
### Type

Cosmetic

### Bug description

I dont know how this bug occured I wanted to play some osu mania but this happened 
Edit: I'll try to reinstall the client 
Edit: 2 it didn't work
Edit: 3 I'll try to play on my laptop

### Screenshots or videos

![Screenshot_20230421_114829](https://user-images.githubusercontent.com/131448701/233606396-c334ac02-272e-4880-9935-cee12826a937.jpg)
![Screenshot_20230421_114823](https://user-images.githubusercontent.com/131448701/233606402-314a9827-6441-47bb-acec-65c421d954a4.jpg)

### Version

2023.419.0

### Logs

How do I paste logs on android?

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/issues/23249
