### ISSUE TITLE
Enabling barrel roll and magnetised or repel causes a memory leak

### ISSUE THREAD

**Issue by Niterux** [ppy/osu#23263]
### Type

Performance

### Bug description

when I enable repel/magnetised and barrel roll together with maximum speed the amount of memory the game uses increases significantly over time and my fps decreases and stutters a lot
at the end my fps is in the 20-30 range when usually it is around 1000
if it helps any i use the opengl render

### Screenshots or videos

![Screenshot 2023-04-20 224421](https://user-images.githubusercontent.com/110568869/233528690-e0c7b73f-850a-41b2-9c10-a48935b47341.png)
https://drive.google.com/file/d/1yjf8o2UCQNDl5N_o9BiOwFAKQd5j_QJr/view?usp=sharing

### Version

2023.419.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11291843/database.log)
[input.log](https://github.com/ppy/osu/files/11291844/input.log)
[network.log](https://github.com/ppy/osu/files/11291845/network.log)
[performance.log](https://github.com/ppy/osu/files/11291846/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11291847/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11291848/updater.log)

**Comment by frenzibyte** [comment]
With magnetised and barrel roll, there seem to be so much framebuffer texture computation going on in gameplay, and using the new (non-legacy) `OpenGL` renderer has memory leaks in latest release, so this is making sense. Have you tried using `OpenGL (Legacy)` or `Direct3D 11`? They should help.

**Comment by frenzibyte** [comment]
Closing as duplicate.

**Comment by peppy** [comment]
Tracking via https://github.com/ppy/osu/issues/23252
