### ISSUE TITLE
When playing song with speed (x2.0) it glitches back even when it was supposed to finish

### ISSUE THREAD

**Issue by Arisamiga** [ppy/osu#23281]
### Type

Game behaviour

### Bug description

When playing a song for example https://osu.ppy.sh/beatmapsets/8561#osu/35057

+ Using DT with (x2.0)
 At the end of the song, it would glitch back even when it was the end of the song

+ On the video I used classic mod, HDFL, and DT with x2.0 but it works with only DT x2.0 as well.

### Screenshots or videos

https://user-images.githubusercontent.com/64918822/233784275-1a8c8a01-e66a-4639-a3db-0a86f0ec50f4.mp4

### Version

2023.419.0

### Logs

[updater.log](https://github.com/ppy/osu/files/11301276/updater.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11301277/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11301278/network.log)
[runtime.log](https://github.com/ppy/osu/files/11301280/runtime.log)

**Comment by frenzibyte** [comment]
I can't reproduce this. It doesn't seem like it's going back to the preview point either, nor are logs showing any sign of explicit GCC seek, so potentially driver-level audio issue. Make sure you don't have any other application running that affects audio output.

**Comment by Arisamiga** [comment]
I tried to open several of the apps I normally use to try to reproduce the issue again but it doesn't seem to be happening. If I find any information about why this is happening I will let you know!

Thanks so much for your help :D
