### ISSUE TITLE
White lines around some sprites

### ISSUE THREAD

**Issue by ndb000** [ppy/osu#23285]
### Type

Cosmetic

### Bug description

These white lines appear on legacy sprites (especially noticeable on numbers.)  I recall this not being an issue about 2 updates ago.

Here is my skin: 
[catpro (nadadb).zip](https://github.com/ppy/osu/files/11302012/catpro.nadadb.zip)

### Screenshots or videos

![osu_2023-04-22_14-55-48](https://user-images.githubusercontent.com/131550296/233799957-a7ce7d8d-c472-4147-a70e-270cf74ae980.jpg)
![osu_2023-04-22_14-56-09](https://user-images.githubusercontent.com/131550296/233799979-f45a6df7-1d1b-4a31-9725-ac25a2ba2aba.jpg)
![osu_2023-04-22_14-55-54](https://user-images.githubusercontent.com/131550296/233800041-e1ac922f-9ba5-4047-af57-a63401048186.jpg)
![osu_2023-04-22_14-41-38](https://user-images.githubusercontent.com/131550296/233800057-a02647a2-3f74-46e0-b755-17d577640bbf.jpg)

### Version

2023.419.0-lazer

### Logs

[logs.zip](https://github.com/ppy/osu/files/11302011/logs.zip)

**Comment by NekoToo** [comment]
I have the same problem on Linux Flatpak and AppImage running on OpenGL Legacy, the problem disappears with OpenGL selected as the renderer for me.

**Comment by peppy** [comment]
99% sure this will be resolved via ppy/osu-framework#5765 so let's close for now.
