### ISSUE TITLE
OpenGL (Legacy) flickering during gameplay

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#23294]
### Type

Other

### Bug description

Cursor and UI text seem to dissapear for a frame. Setting the Frame Limiter to Vsync alleviates the issue. This issue does not affect UI on the other game screens.

### Screenshots or videos

https://user-images.githubusercontent.com/53346335/233840474-6a2abe7f-bcee-4d27-b905-431da0d014be.mp4

### Version

2023.326.0 and above

### Logs

[runtime.log](https://github.com/ppy/osu/files/11303749/runtime.log)

**Comment by frenzibyte** [comment]
I cannot reproduce this one myself so I can't investigate it. cc @peppy / @smoogipoo.

**Comment by Shirou27** [comment]
I also experience that flickering in my android phone(Redmi Note 9) sometimes.

**Comment by peppy** [comment]
Can't see this in the video, but it's likely just the user experiencing screen tearing, which was previously not happening.

**Comment by Sinamer** [comment]
That can't be right. Screen tearing was always there. If you go through the video frame by frame, the cursor and UI text are there at first, then dissapear completely on the next frame, there is no in-between.

![mpv-shot0002](https://user-images.githubusercontent.com/53346335/234486892-51e97fb7-87ab-4898-bb49-66c2875425ea.jpg)
![mpv-shot0001](https://user-images.githubusercontent.com/53346335/234486864-8b1e99b6-efd2-453f-af88-360892047c9d.jpg)
![mpv-shot0003](https://user-images.githubusercontent.com/53346335/234486900-b0b96de5-6af7-4c5a-aa75-8baff85a142b.jpg)

**Comment by peppy** [comment]
@smoogipoo any ideas on this one?

**Comment by Sinamer** [comment]
I noticed just now that the issue is not visible when using argon and triangle default skins. It only shows when using classic or my legacy skin

**Comment by smoogipoo** [comment]
Unfortunately I haven't yet repro'd this, but I'll keep trying. Since it's skin related, you could try disabling certain elements and seeing which one causes it. In particular, the progress circle isn't shared between those skins.

Though I don't think it has any chance of fixing the issue, you could try testing with https://github.com/ppy/osu-framework/pull/5758.

**Comment by Sinamer** [comment]
I went as far as removing all the skin elements possible in the skin editor and cursor was still flickering, so that didn't help.

I ran the game with a local osu-framework and the PR applied and it had no effect on the issue either.

**Comment by Shirou27** [comment]
I want to add more information about this.

When I'm playing osu! Lazer with account log out and without using internet or simply OFFLINE, flickering is much less frequent than playing online.

Approaching circle is much stable when playing offline rather than playing online.

**Comment by smoogipoo** [comment]
@Sinamer can you check to make sure you're on the latest drivers, and can still reproduce this? Alternatively:

Please provide your [dxdiag output](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe).

**Comment by Sinamer** [comment]
Here's the dxdiag:
[DxDiag.txt](https://github.com/ppy/osu/files/11421487/DxDiag.txt)

As for the drivers, unfortunately I'm stuck with the default Windows provides for this iGPU, as this laptop seems to have firmware issues which cause blue screens when using the driver package Intel provide on their website. ASUS also took down the page for this specific model of the laptop and their support page with their drivers for it

**Comment by Sinamer** [comment]
I have updated my install to a newer version of Win10 which comes with better default graphics drivers for this Intel iGPU, and the issue does not show up anymore. The Update thread fps is lower by 70 fps on average with these drivers, but I'm glad I'm not affected by this issue now
