### ISSUE TITLE
Direct3D 11 performance degraded on latest release

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#23295]
### Type

Performance

### Bug description

In 2023.403.1
Veldrid Direct3D 11 results in a quarter of the fps OpenGL (Legacy) was getting
Veldrid OpenGL was mostly on par
Both of the Veldrid options had heavy stuttering though which was not present with OpenGL (Legacy)

And then in 2023.419.0
Clicking on anything makes the entire game experience a lag spike (on both Veldrid renderers)
Gameplay doesn't even reach 60 fps on the Draw Thread, Song Select goes down to single digits
Please note that on the release before Veldrid, Gameplay ran at 240, and Song Select was at 40
Before Veldrid, when things were loading the game kept being smooth and did not experience the lag spikes seen in the video here

### Screenshots or videos

https://user-images.githubusercontent.com/53346335/233840641-5b286f18-4883-4a4f-a74c-ba41aca93dfc.mp4

### Version

2023.419.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/11303759/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11303760/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/11303763/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/11303754/performance-update.log)
[performance-audio.log](https://github.com/ppy/osu/files/11303761/performance-audio.log)
[performance-input.log](https://github.com/ppy/osu/files/11303762/performance-input.log)
[updater.log](https://github.com/ppy/osu/files/11303755/updater.log)
[database.log](https://github.com/ppy/osu/files/11303757/database.log)
[network.log](https://github.com/ppy/osu/files/11303758/network.log)

**Comment by frenzibyte** [comment]
I'm not entirely sure whether you're experiencing this on D3D11 specifically or on OpenGL as well, but for D3D11, this will likely be a combination of two things:
 1. Generating texture mipmaps, which creates a new texture every time for sampling (may be improved with a compute shader).
 2. Mapping VBOs every time they're updated, which has turned out to be an expensive operation on D3D11 (cc @smoogipoo).

**Comment by Sinamer** [comment]
This is both Veldrid OpenGL and D3D11

**Comment by Lunaero1** [comment]
> I experience this issue on both Veldrid OpenGL and D3D11. The video was taken with Veldrid OpenGL

actually same here, same issues.. Exept Legacy barely works anymore for me too

**Comment by Sinamer** [comment]
The recent release has improved performance quite substantially, aside from more frequent GC-s on Veldrid renderers during gameplay, the framerate is on par with LegacyGL and it works really well. I'm not seeing long pauses like the video in OP shows anymore so I consider this issue closed.
