### ISSUE TITLE
Slider rendering broken at the end of a beatmap on new OpenGL renderer when Storyboards on

### ISSUE THREAD

**Issue by Retiu** [ppy/osu#23314]
### Type

Game behaviour

### Bug description

I found the bug at the end when playing this beatmap: https://osu.ppy.sh/beatmapsets/703957#osu/1511864
I mainly play on the new OpenGL renderer and this bug only showed when storyboards were turned on. Also at the beginning of the beatmap when I load it up with storyboards turned on, I get an unexpected error.

I have attached screenshots and a screen recording below showcasing what it looks like

### Screenshots or videos

![osu!_wVS43bWzE5](https://user-images.githubusercontent.com/72349963/234375121-7513a290-db39-4edf-9634-f785d4b2db59.png)
![osu!_fOwFCQM4IP](https://user-images.githubusercontent.com/72349963/234375127-077996c0-331a-49d1-9ed5-7f157ad9e770.png)

Gameplay screenrecording: https://www.youtube.com/watch?v=f0sDftY8Wh4
The video showing the unexpected error: https://user-images.githubusercontent.com/72349963/234375202-195f0508-e588-49ca-8c3b-65203bca224a.mp4

### Version

osu! 2023.419.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/11325910/network.log)
[runtime.log](https://github.com/ppy/osu/files/11325911/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11325912/updater.log)
[performance.log](https://github.com/ppy/osu/files/11325913/performance.log)
[input.log](https://github.com/ppy/osu/files/11325914/input.log)
[database.log](https://github.com/ppy/osu/files/11325915/database.log)

**Comment by peppy** [comment]
Please use legacy GL renderer instead.

**Comment by bdach** [comment]
Looks extremely similar to #23046?

@Retiu can you confirm that you had storyboards fully dimmed (100%) and that this bug only occurs if storyboards are fully dimmed?

**Comment by Retiu** [comment]
yeah, it was fully dimmed. seems this only happens when the storyboard is not 100% dimmed. can provide a video if necessary

**Comment by bdach** [comment]
I don't think we need one. What you're saying confirms that this bug is a duplicate.
