### ISSUE TITLE
(android) Mania notes invisible on certain mobile devices 

### ISSUE THREAD

**Issue by megadrive7** [ppy/osu#23318]
### Type

Game Behavior

### Bug description

While attempting to play osu! mania on my phone, I found that the notes were not displayed at all. All other elements are displayed but all notes are completely invisible. They are still hittable, though. This also occurred while attempting to watch the replay of this issue I made, and when importing replays made by other people onto my device and attempting to play them back. All judgements are still visable, and the field still displays a scrolling effect.

Tldr, mania notes in both gameplay and replay are not being displayed

I have no other mobile device to test with. Observed on a Samsung A14 5g (notably a rather low end device)
This issue has persisted through both app and phone reboots

Edit sorry for the spam open/close my finger unironically slipped twice
### Screenshots or videos

https://user-images.githubusercontent.com/112918046/234651463-38e7597e-773f-49a0-92d7-be2c04a11c12.mp4

### Version

2023.419.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11335550/database.log)
[performance.log](https://github.com/ppy/osu/files/11335555/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11335560/runtime.log)
[network.log](https://github.com/ppy/osu/files/11335562/network.log)

**Comment by megadrive7** [comment]
My bad for not labeling, forgot to and don't know how to do retrospectively

**Comment by peppy** [comment]
Probably related to the osu! logo text also being invisible. Looks like a mishap with the new renderer, potentially.
