### ISSUE TITLE
Argon's sliderball with hidden doesn't disappear as fast as other skins

### ISSUE THREAD

**Issue by auroraongithub** [ppy/osu#23316]
### Type

Game behaviour

### Bug description

I tried lazer and I play hidden a lot. I actually like argon (pro especially), but one huge issue is this sliderball that doesn't disappear quick enough, which causes a lot of possible misreads. This doesn't happen to other skins which is a bit weird.

### Screenshots or videos

https://streamable.com/clq3da

### Version

2023.419.0

### Logs

[performance.log](https://github.com/ppy/osu/files/11328871/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11328872/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11328873/updater.log)
[database.log](https://github.com/ppy/osu/files/11328874/database.log)
[input.log](https://github.com/ppy/osu/files/11328875/input.log)
[network.log](https://github.com/ppy/osu/files/11328876/network.log)

**Comment by peppy** [comment]
Turns out the implementation was adding a double fade, but other implementations add a 4x faster fade so I'll match that for now.

It's still not as fast as legacy skins (no transition) but it should be enough.
