### ISSUE TITLE
User profile flag label is not clickable unlike web

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#23324]
### Type

Other

### Bug description

Just nitpicking the differences between lazer and web behavior.

<sub>Mostly fulfilling my "Make osu! repo more friendly for new contributors" goal.</sub>

### Screenshots or videos

| Lazer | Web |
| --- | --- |
| ![osu!_YgKZ07CKI5](https://user-images.githubusercontent.com/35318437/234764017-0512827e-a725-41c7-b07b-31e4633529db.gif) | ![firefox_lHcm0y79GM](https://user-images.githubusercontent.com/35318437/234764065-34e109c5-add2-4f83-8011-5a6c97d4c2e5.gif) |

### Version

Since 2023.207.0 / https://github.com/ppy/osu/commit/ef7812412b5eadf301de7aa2d7e090f450d76d65

### Logs

N/A

**Comment by anirudh-pandey** [comment]
Hey @Joehuu, Can I pick this task? If yes, I have to make the functionality similar to web right?

**Comment by Joehuu** [comment]
Yes you can! You have to match the web functionality.

But first, I recommend reading the Submitting pull requests and Resources section of the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md) if you haven't done so already.

https://github.com/ppy/osu-framework/wiki/Debug-Overlays:-Draw-Visualizer is also a useful tool when dealing with UI like this.

**Comment by rltn** [comment]
> Hey @Joehuu, Can I pick this task? If yes, I have to make the functionality similar to web right?

Sorry, didnt noticed you had to make this issue. However, i am not sure about my realization, so i am pretty sure you can do better job.

**Comment by Joehuu** [comment]
For future reference (in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md)):

> In the case of simple issues, a direct PR is okay. However, if you decide to work on an existing issue which doesn't seem trivial, please ask us first. This way we can try to estimate if it is a good fit for you and provide the correct direction on how to address it. In addition, note that while we do not rule out external contributors from working on roadmapped issues, we will generally prefer to handle them ourselves unless they're not very time sensitive.

This is a trivial issue, so it can be on a first come first served basis which doesn't need asking.
