### ISSUE TITLE
freezes on openGL

### ISSUE THREAD

**Issue by Axilotl17** [ppy/osu#23330]
### Type

Performance

### Bug description

It happens randomly in game sometimes, generally in the first few games. after a few maps it stops happening.

in the logs, it happened about ~3m into the latest song

### Version

2023.419.0-lazer

### Logs

[logs (1).zip](https://github.com/ppy/osu/files/11350247/logs.1.zip)

**Comment by frenzibyte** [comment]
OpenGL was deemed quite unstable this release, please switch to OpenGL (Legacy) or Direct3D 11 for now.
