### ISSUE TITLE
Screen stuck if open the skin editor in the gameplay with new skin.

### ISSUE THREAD

**Issue by andy840119** [ppy/osu#23338]
### Type

Crash to desktop

### Bug description

The screen will stuck at gameplay if open the skin in the editor with new skin.
Might not got the stuck always and might have the same issue with official ruleset.

Not really sure is caused by realm because seems it will save the skin and read immediately in the skin editor.
And seems got the crash if add some breakpoints in the `EnsureMutableSkin()`

### Screenshots or videos

https://user-images.githubusercontent.com/9100368/235296814-4690f8ec-e803-4b6f-9d22-a8d965b92619.mp4

### Version

2023.419.0

### Logs

[database.log](https://github.com/ppy/osu/files/11358859/database.log)
[input.log](https://github.com/ppy/osu/files/11358860/input.log)
[network.log](https://github.com/ppy/osu/files/11358861/network.log)
[performance.log](https://github.com/ppy/osu/files/11358862/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11358863/runtime.log)

Not the same log as video but it's similar:
- There's no callstack in the log.
- Have the `2023-04-29 09:46:36 [verbose]: SkinImporter is being paused.` at the end of the line in the `runtime.log`.

**Comment by bdach** [comment]
#22486
