### ISSUE TITLE
osu! lazer in the website the osu! direct button doesn't work with the lazer client

### ISSUE THREAD

**Issue by Thomas-Harit** [ppy/osu#23364]
### Type

Game behaviour

### Bug description

When downloading a beatmaps on the osu website, the osu!direct button will do nothing.

### Version

2023.419.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/11369040/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11369041/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11369042/updater.log)
[database.log](https://github.com/ppy/osu/files/11369043/database.log)
[input.log](https://github.com/ppy/osu/files/11369046/input.log)
[network.log](https://github.com/ppy/osu/files/11369048/network.log)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/14824
