### ISSUE TITLE
Improve playability of osu!mania on small touch screen devices

### ISSUE THREAD

**Issue by mariopvz** [ppy/osu#23377]
### Type

Crash to desktop

### Bug description

awfully small hitbox placement which is really hard to use on mobile

### Screenshots or videos

![Screenshot_2023-05-02-23-07-21-710_sh ppy osulazer](https://user-images.githubusercontent.com/101997040/235777548-040c51d9-48c4-4db7-a55b-c2b47a03498a.jpg)

### Version

2023.419.0

### Logs

> 
[database.log](https://github.com/ppy/osu/files/11377400/database.log)
[runtime.log](https://github.com/ppy/osu/files/11377401/runtime.log)
[network.log](https://github.com/ppy/osu/files/11377402/network.log)
[performance.log](https://github.com/ppy/osu/files/11377403/performance.log)

**Comment by stanriders** [comment]
Rotate the phone

**Comment by peppy** [comment]
> Rotate the phone

Unfortunately rotation is locked due to majority consensus a while ago. We still need to provide a solution to this (but this issue is likely a duplicate as this has been brought up quite a few times).

**Comment by christopher317** [comment]
i think this is what they mean

https://github.com/ppy/osu/assets/86526198/d792b1c4-6b6b-4300-bbb2-6b324bb75a63

( srry for the bad video quality, i wanted to capture how i was *trying* to play as well )
something like tiles or dedicated buttons would work much better for this than just rotating the phone.

**Comment by toadsworth-jr** [comment]
I'm pretty sure this has been discussed many, many times over with no definite answer yet...

**Comment by YoJames2019** [comment]
Soooo any update on this? Mania is currently unplayable on phones

**Comment by 502y** [comment]
Same issue on iPad Pro, Mi 10s and Surface 7 pro with touch mode, too small to play.

**Comment by peppy** [comment]
Yes, we understand this issue is on all touch screens. Further comments like this is not going to help.

If you want to show your support, please add a reaction to the opening post, rather than posting a comment.

**Comment by 502y** [comment]
> Yes, we understand this issue is on all touch screens. Further comments like this is not going to help.
> 
> If you want to show your support, please add a reaction to the opening post, rather than posting a comment.
Sure, i will delete it

**Comment by dooooooodd** [comment]
![IMG_20231101_122509](https://github.com/ppy/osu/assets/149602558/a206deb0-39aa-40c1-82cc-6e309b1ff822)
I wouldn't be able to explain it so I made this, please make it a thing, it's so simple and it works really well!

**Comment by bdach** [comment]
I'm locking this because clearly polite pleas to not comment fluff aren't working.

We know this is an issue, and we know what needs to be done to fix it. Mobile is not currently a priority full stop.
