### ISSUE TITLE
can't save a replay 

### ISSUE THREAD

**Issue by mariopvz** [ppy/osu#23376]
### Type

Game behaviour

### Bug description

can't save a replay because touch is binded on left mouse button,and to save it you need to click on right mouse button(on mobile)

### Version

2023.419.0

### Logs

> 
[database.log](https://github.com/ppy/osu/files/11377400/database.log)
[runtime.log](https://github.com/ppy/osu/files/11377401/runtime.log)
[network.log](https://github.com/ppy/osu/files/11377402/network.log)
[Uploading performance.log…]()

**Comment by peppy** [comment]
https://github.com/ppy/osu-framework/pull/5255
