### ISSUE TITLE
Lazer editor have multiple errors in spinner

### ISSUE THREAD

**Issue by MineTurtlee** [ppy/osu#23373]
### Type

Game behaviour

### Bug description

I got this after trying several spinners, there are like [MULTIPLE] bugs at the spinner in the editor. Look at these screenshot!

### Screenshots or videos

![image](https://user-images.githubusercontent.com/97010924/235619135-fd1785ce-21ca-4252-9770-2c8c671a820c.png)
![image](https://user-images.githubusercontent.com/97010924/235620223-f0164f9f-e8a3-4146-b4b8-e9c4af03522f.png)

### Version

2023.419.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/11371312/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11371313/updater.log)
[database.log](https://github.com/ppy/osu/files/11371314/database.log)
[input.log](https://github.com/ppy/osu/files/11371303/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11371304/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11371306/network.log)
[performance.log](https://github.com/ppy/osu/files/11371307/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11371308/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11371309/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/11371310/performance-update.log)
(Forgive me, I don't know what type is this bug so I uploaded all)

**Comment by bdach** [comment]
Already covered by #10455
