### ISSUE TITLE
Editor metronome plays late

### ISSUE THREAD

**Issue by noneistaken** [ppy/osu#23393]
### Type

Game behavior

### Bug description

With this beatmap 
[ARForest _ nayuta - Imaginary Arcadia (noneistaken).zip](https://github.com/ppy/osu/files/11390203/ARForest._.nayuta.-.Imaginary.Arcadia.noneistaken.zip) (please rename to .osz extension!) in the editor, the metronome ticks around 20ms to 30ms late.

Some notes:

- **The audio file in the beatmap has ZERO milliseconds of offset.**
I verified this with REAPER (a DAW) both visually with a spectrogram and its built-in metronome. This is set accordingly for the one and only timing point in the beatmap. There is no ~negative 20ms offset like on beatmaps timed with osu!stable.
- **The latency in osu!lazer's metronome ticking is found visually through REAPER.**
Top two channels are of the original mp3 file, bottom two are from a recording of the game's audio. Green line marks a downbeat in the song, and the grey overlay rectangle is the gap between the downbeat and when osu!lazer actually played the downbeat tick sample. I specifically picked a downbeat, as the tick sample that plays in other beats has 5ms of effective silence at the beginning.
- The attached video has the beatmap BPM set to 2x to make the latency more obvious.

![2023-05-04_02-21](https://user-images.githubusercontent.com/90960821/236024165-105fe1a4-793d-4542-b3b2-0bd2fc37fe32.png)

System info: I am on Artix Linux, using JACK audio output at 48000Hz, two channels, 256 samples/period. I explicitly set the audio output in osu!lazer to "JACK Audio Connection Kit" and verified that game audio was actually going through JACK.

### Screenshots or videos

https://files.catbox.moe/8445uc.mp4 (around 65.2MiB, GitHub does not allow files over 10MB)

### Version

2023.419.0.0

### Logs

[database.log](https://github.com/ppy/osu/files/11390452/database.log)
[input.log](https://github.com/ppy/osu/files/11390453/input.log)
[network.log](https://github.com/ppy/osu/files/11390454/network.log)
[performance.log](https://github.com/ppy/osu/files/11390455/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11390456/runtime.log)

**Comment by peppy** [comment]
You can adjust your universal offset in settings to fix this, game-wide.

**Comment by peppy** [comment]
Period doesn't affect sample playback latency.
