### ISSUE TITLE
Black Screen on Intel

### ISSUE THREAD

**Issue by gabixdev** [ppy/osu#234]
When trying to run osu preview v6 build a black non-responding window appears.
I also have tried running from osu folder - nothing.
Hardware: Cheap Windows tablet with Intel Atom Z3735 (7-gen Intel HD Graphics).

No logs are created, nothing, just black screen...

**Comment by peppy** [comment]
this is not helpful. please try to fix or avoid running for now.

**Comment by riley11992** [comment]
Also having this issue... i don't know c# that well but I'm learning. Once i finish learning c# i will try to resolve the issue myself and get back to you guys once i do (unless it's fixed before).
