### ISSUE TITLE
Metronome tick sample has silence at the beginning

### ISSUE THREAD

**Issue by noneistaken** [ppy/osu#23409]
### Type

Other

### Bug description

In the editor, this sound is supposed to play on non-downbeats: https://github.com/ppy/osu-resources/blob/master/osu.Game.Resources/Samples/UI/metronome-tick.wav 
It has around 5 milliseconds of silence at the beginning, which isn't too noticeable but definitely trouble when timing high-BPM maps just by hearing. IMO if you measure from the start to the actual impact, it's actually more like 9-10ms. The soft impact of the whole sound doesn't help either.
For starters, it's possible to just replace metronome tick samples with a sharp-attack sine pluck.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/90960821/236540764-266238e1-0dbc-419b-aa85-fc51d01b9fa8.png)
![image](https://user-images.githubusercontent.com/90960821/236540878-106e44cc-30b4-4f8a-a920-948481d13ad1.png)

### Version

2023.419.0.0

### Logs

(not relevant)

**Comment by peppy** [comment]
It's all part of the process. A reminder is not required.
