### ISSUE TITLE
Progress pie of legacy skin is not being displayed correctly

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu#23417]
### Type

Cosmetic

### Bug description

- Skin: https://osu.ppy.sh/community/forums/topics/1672096

There are two circle overlapping on the progress pie (see screenshots). The problem doesn't happen on stable.

### Screenshots or videos

Stable
![screenshot037](https://user-images.githubusercontent.com/16283764/236629843-2a6f52cd-be6c-488f-9623-b2e60926a60d.png)

Lazer
![osu_2023-05-06_20-06-22](https://user-images.githubusercontent.com/16283764/236629783-4dc22c3e-470a-4fe7-8774-82de0bba1c2d.png)

### Version

2023.419.0

### Logs

[database.log](https://github.com/ppy/osu/files/11412550/database.log)
[input.log](https://github.com/ppy/osu/files/11412551/input.log)
[network.log](https://github.com/ppy/osu/files/11412552/network.log)
[performance.log](https://github.com/ppy/osu/files/11412553/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11412554/runtime.log)

**Comment by bdach** [comment]
This is a case of "hacky skin". The linked skin is attempting to use `scorebar-bg` to change the shape of the circular progress via crude use of opaque pixels, and relying on z-order of the skinning elements:

![1683384240](https://user-images.githubusercontent.com/20418176/236631120-6707a5a0-c0d2-4755-9645-1cba4f1e05d5.png)

This will not be supported forward, in the same way that players' "playfield area" indicators crudely implemented via `scorebar-bg` are not.

**Comment by Joehuu** [comment]
> This will not be supported forward

This is a duplicate of https://github.com/ppy/osu/issues/21048 and it seems like we may want to fix this (at least for a single aspect ratio): https://github.com/ppy/osu/issues/21048#issuecomment-1298199407
