### ISSUE TITLE
Note will not be visible if there are too many barlines

### ISSUE THREAD

**Issue by RBQcat** [ppy/osu#23412]
### Type

Cosmetic

### Bug description

https://osu.ppy.sh/beatmapsets/1134062#mania/2658817
At 00:57:429 in this beatmaps, too many bar lines completely cover the note

### Screenshots or videos

Lazer:
![image](https://user-images.githubusercontent.com/74862110/236594087-a5977d7f-3562-4e7c-9458-f99637b280dc.png)
stable (for comparison):
![image](https://user-images.githubusercontent.com/74862110/236594075-8392a88f-3796-4b54-b55b-7fa754aade9a.png)

### Version

2023.419

### Logs

N/A

**Comment by bdach** [comment]
What on god's green earth is that...

I was hoping this was going to be a graved map but it's loved so we're probably going to end up having to hack past this somehow... sigh

**Comment by peppy** [comment]
Jesus fuck.

**Comment by longnguyen2004** [comment]
There are more hack maps out there...
https://osu.ppy.sh/beatmapsets/697153#mania/1484721
https://osu.ppy.sh/beatmapsets/501530#mania/1073953
https://osu.ppy.sh/beatmapsets/424218#mania/916468

Those are what I have, there might be more out there. All of them are BPM abuse, so yea...gonna be a pain.
