### ISSUE TITLE
Osu!catch plays are inconsistent when replayed

### ISSUE THREAD

**Issue by Timkador** [ppy/osu#23447]
### Type

Game behaviour

### Bug description

I decided to watch my replay of acid burst that I made 2 days ago and it was different. I remember FCing in the Spring Beatmap Spotlight, but the replay showed that I didn't (I also used Sudden Death and the replay just didn't care)

something very similar happened to me earlier when there was the winter 2023 Beatmap Spotlight when my play of Villain virus was bugged too but i didn't think too much about it

### Screenshots or videos

The files are too big so I uploaded them on youtube
https://youtu.be/NYc4eActkkE i forgot to change the bitrate on obs that's why I made two videos
https://youtu.be/Ki-zIDzd11w
and that's why I'm saying it's inconsistent

### Version

2023.419.0-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/11429560/updater.log)
[database.log](https://github.com/ppy/osu/files/11429561/database.log)
[input.log](https://github.com/ppy/osu/files/11429562/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11429563/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11429564/network.log)
[performance.log](https://github.com/ppy/osu/files/11429565/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11429566/runtime.log)

**Comment by bdach** [comment]
Please upload the replay of this play.

**Comment by Timkador** [comment]
uh I made the youtube videos with the replays

**Comment by Timkador** [comment]
https://youtu.be/41RwazXMob4 
https://drive.google.com/file/d/1Olmc9rR5_JtB1ZdK869Ges99xkW-vJm8/view?usp=sharing
i guess it's more broader

**Comment by Timkador** [comment]
I think it's a duplicate of #19766

**Comment by Timkador** [comment]
it should probably be closed like this
