### ISSUE TITLE
Cursor trail detaches in skin layout editor

### ISSUE THREAD

**Issue by soopax** [ppy/osu#23441]
### Type

Cosmetic

### Bug description

This always happens.
# Steps to reproduce
1. Import this replay https://osu.ppy.sh/scores/osu/4428381232
2. Start watching the replay
3. Pause the playback of the replay
4. Open the skin layout editor (`Ctrl-Shift-S`)

## Expected result
The cursor trail stays attached to the cursor.
## Actual result
The cursor trail detaches from the cursor.

### Screenshots or videos

![Screenshot from 2023-05-08 15-53-24](https://user-images.githubusercontent.com/101510334/236834811-e83e4a1d-c31d-463a-a6f8-8cd20fd220a1.png)
![Screenshot from 2023-05-08 15-53-45](https://user-images.githubusercontent.com/101510334/236834819-079354b7-e238-412f-8aee-84967a3feab3.png)

### Version

2023.419.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/11421565/logs.zip)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/23814
