### ISSUE TITLE
Extremely low or high BPM timing points do not function as intended in osu!taiko

### ISSUE THREAD

**Issue by aceticke** [ppy/osu#23456]
### Type

Game behaviour

### Bug description

A map that is due for Loved voting within the next couple of days does not function as intended in Lazer (https://osu.ppy.sh/beatmapsets/1213082#taiko/2524777), 0bpm timing points (in the .osu they are 6E+17) are used so that notes are permanently on the hitcircle on the left, however in Lazer they play as normal, appearing like any other hit object, extremely high bpm timing points are used to achieve barlines that visually do not move as they are so fast, however in Lazer it caps at a certain point and displays multiple barlines as "normal" (could be a rendering thing?). 

### Screenshots or videos

https://github.com/ppy/osu/assets/83513254/897be887-8a8b-440e-862b-6c201e3e9a4b

Comparison between Lazer and Stable

### Version

2023.419.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11441451/database.log)
[input.log](https://github.com/ppy/osu/files/11441452/input.log)
[network.log](https://github.com/ppy/osu/files/11441454/network.log)
[performance.log](https://github.com/ppy/osu/files/11441455/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11441456/runtime.log)

**Comment by bdach** [comment]
Timing point with such BPM specifications were never really meant to be supported properly and constitute "aspire-like" behaviour, which is not guaranteed to be preserved in lazer, unless they break an existing ranked map.

See also: https://github.com/ppy/osu/issues/750, https://github.com/ppy/osu/discussions/17426, https://github.com/ppy/osu/discussions/14835#discussioncomment-1372698.
