### ISSUE TITLE
osu! leaks memory when open for long enough

### ISSUE THREAD

**Issue by Ferdi265** [ppy/osu#2345]
Encountered this yesterday when I had to interrupt playing osu! and left it open for a few hours.

## Version

Yesterday's master (25524bf24fa79e0e1c5aec8ebbb35cceca3f1d59)

## What?

osu! consumes the entire available RAM if open long enough.

## How to reproduce?

Open osu!, play an "osu!"-mode beatmap, pause somewhere in between, leave open for hours.

## Symptoms

- laggy triangle animation on the continue, retry, exit buttons
- very unresponsive system

## Debug info

None (yet).

I'm new to working on this project. I'm used to building my own osu!lazer with msbuild (regularly from git), but I don't have much experience profiling or debugging C# (I do have with other languages, such as C, Rust, JS, ...).

If you have tips on how I can capture allocation traces (like from valgrind) I can do that and post the info here.

~yrlf

**Comment by jai-sharma** [comment]
Can you glean any extra information from the log files found in `~/.local/share/osu`?

**Comment by FreezyLemon** [comment]
I'll try and see if this happens on windows too.. 
I tested it a fair while back, and it definitely had a memory leak somewhere.

By the way, if you want to capture memory information, you could use Jetbrains' dotMemory. They have a trial version that you can use, and the UI is pretty self-explanatory. Maybe a memory snapshot will help with understanding this^^

**Comment by peppy** [comment]
dotmemory won't work on linux, unfortunately

**Comment by FreezyLemon** [comment]
Can't repro on Win10 x64, on latest master. Might be something related to Linux or to your system specifically..

**Comment by Ferdi265** [comment]
[logs folder](https://mega.nz/#!BhlzzR6S!neGIjwa5drya73k0O7tIZJdUsabMxMQtyJnNiLmIN8g)

**Comment by Ferdi265** [comment]
I can try using the mono profiler (regular and HeapShot).

I'm currently testing that. I'll see if it leaks memory again. Testing on the same SHA as in the first post.
Once I've reproduced it during profiling, I'll try again with latest master.

**Comment by peppy** [comment]
Please ensure you're on the latest mono builds (at *least* 5.10) as they basically rewrote the GC recently. It can make a huge difference.

Also please test under netcore2.0 if possible.

**Comment by peppy** [comment]
Yeah, I believe this is no longer an issue.
