### ISSUE TITLE
Right-click action in touch devices shouldn't work on gameplay

### ISSUE THREAD

**Issue by JeromTWinL** [ppy/osu#23465]
### Type

Game Behaviour

### Bug description

I just saw the video of the new update, and I tried the "right click" action occurs when holding the touch screen, but I expect it to not work (not to show hold animation) on the gameplay. We don't even need right click on the gameplay (except keyboard players)

### Screenshots or videos

https://github.com/ppy/osu/assets/84004577/58b033f1-4128-4d7a-8fe6-184d4f9f31d6

Video that I played without purposely holding in a same place:

https://github.com/ppy/osu/assets/84004577/c458a568-7bdf-4205-b050-913a1241c429

### Version

2023.511.0 (Android)

### Logs

(Not necessary)

**Comment by Joehuu** [comment]
Has since been fixed in https://github.com/ppy/osu/pull/23529.
