### ISSUE TITLE
Replays lag 

### ISSUE THREAD

**Issue by RevertedClock** [ppy/osu#2347]
Whenever i drag a replay into lazer it starts heavily to lag and you die. 
 
https://streamable.com/b5ohu

**Comment by smoogipoo** [comment]
Can't replicate. Can you try again on the latest build and see if it still happens?

Can't see any reason why this wouldn't happen during gameplay/autoplay either - does it work with those?

**Comment by Lolihunter1337** [comment]
I can confirm this issue with build 2018.618.0

**Comment by Lolihunter1337** [comment]
@smoogipoo is there a way i can provide more that could help?

**Comment by smoogipoo** [comment]
I believe I've been able to replicate this since last time, just haven't had the time to look into it.

**Comment by MrTheMake** [comment]
Happens to me when using the replay file [MrTheMake - FLOWxGRANRODEO - 7 -seven- -TV SIZE - [Expert] (2016-06-18) Osu.zip](https://github.com/ppy/osu/files/2453959/MrTheMake.-.FLOWxGRANRODEO.-.7.-seven-.-TV.SIZE.-.Expert.2016-06-18.Osu.zip). The map is 
https://osu.ppy.sh/beatmapsets/282345/#osu/638493.

**Comment by Lolihunter1337** [comment]
Just as update on 2018.1228.0 still occurring

**Comment by peppy** [comment]
This should now be resolved. Could reporters please confirm?

**Comment by Lolihunter1337** [comment]
Yup. Works fine for me now
