### ISSUE TITLE
Spinners in editor don't reset their spin amounts when replayed

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [ppy/osu#23480]
### Type

Game behaviour

### Bug description

When previewing a spinner in the compose tab in the editor, it is automatically spun, like in stable.
However, the spin amount/bonus (I'm not sure which one) continues to increase from the same amount after rewinding to a previous point in the timeline. 

The only consistent way I can find to reproduce this is to rewind to another point within the spinner without pausing the preview, but other methods (including rewinding while paused, rewinding back to before the spinner starts, restarting the preview from the start) have also shown this behavior.

This does not affect the playtesting of beatmaps, nor does playtesting seem to affect the bug in any way.
The behavior resets when the editor is reopened.

### Screenshots or videos

https://github.com/ppy/osu/assets/84215197/4bb9e2fb-7839-43f1-a143-35c63a4cd119

### Version

2023.511.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/11453591/network.log)
[performance.log](https://github.com/ppy/osu/files/11453593/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11453594/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11453595/updater.log)
[database.log](https://github.com/ppy/osu/files/11453596/database.log)
[input.log](https://github.com/ppy/osu/files/11453597/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11453598/legacy-ipc.log)

**Comment by bdach** [comment]
#10455
