### ISSUE TITLE
Text overlaps in notifications sidebar

### ISSUE THREAD

**Issue by soopax** [ppy/osu#23482]
### Type

Cosmetic

### Bug description

# Steps to reproduce
1. Set the game's language to Finnish (suomi)
2. Open the notifications sidebar (`Ctrl-N`)
## Expected result
No text overlaps.
## Actual result
The "käynnissä olevat tehtävät" text overlaps with the "peruuta kaikki" text.

### Screenshots or videos

![Screenshot from 2023-05-11 18-09-27](https://github.com/ppy/osu/assets/101510334/e4f224b6-ef04-44ef-b2d3-c5a5879c17f2)

### Version

2023.511.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/11454407/logs.zip)

**Comment by bdach** [comment]
We're tracking these cases in https://github.com/ppy/osu/discussions/15452.
