### ISSUE TITLE
BPM dependent animations stops after selecting a few songs

### ISSUE THREAD

**Issue by Fasher99** [ppy/osu#23486]
### Type

Game behaviour

### Bug description

So it's been apparently mentionned and adressed in issue #20059 but i've been able to reproduce it and here's my diagnosis :

- This affects the main menu icons and the osu! cookie
- This is not map dependent, meaning it can produce on any song selected
- It ONLY happens on single-threaded (multithreaded works fine)
- Scrubbing in the Now Playing section can fix the problem
- Going in the editor also fixes the issue

Those 2 last workarounds work until selecting songs again, either through the Solo Play ot the Now Playing menus.

Config:
- Windows 10 22H2
- Ryzen 7 5800x
- Geforce RTX 3060
- 32 Gb RAM

### Screenshots or videos

https://github.com/ppy/osu/assets/133251163/3f61a8ce-a616-4d1f-a39b-378b1dccb4cf

### Version

2023.511.0

### Logs

[database.log](https://github.com/ppy/osu/files/11454635/database.log)
[input.log](https://github.com/ppy/osu/files/11454636/input.log)
[performance.log](https://github.com/ppy/osu/files/11454637/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11454638/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11454639/updater.log)

**Comment by soopax** [comment]
This happens to me too and it happens on both multithreaded and singlethreaded.

**Comment by bdach** [comment]
Can reproduce with single-threaded.

**Comment by peppy** [comment]
This is looking to be a deep bug within `DecoupleableInterpolatingFramedClock` (great).

I'll look into it.
