### ISSUE TITLE
[Proposal] Beatmap Sync

### ISSUE THREAD

**Issue by Numailia** [ppy/osu#2351]
will the new osu! system allow for a feature like saving and syncing beatmaps per user between platforms? I know currently supporters are able to search ranked maps by played status, but I'd sort of like to see this feature built in to the client ... especially when you have multiple devices and have to keep re-downloading maps on different platforms, or if you want to play on the go without manually installing all your maps from pc. (supporter-only, ofcourse)

**Comment by jpsouzasilva** [comment]
@Numailia I really like this feature. Losing all beatmaps is a pain.

If syncing can't be made available, I think at least exporting your current beatmap list to a file locally would be a good option.

1. Export your beatmap list to a file (each entry could have the title + serial ID, exactly how the map's folder is named).
2. Backup that file to somewhere you personally want (cloud, usb stick, whatever).
3. When playing on a new computer, load that file into Lazer. Maps you don't currently own will be greyed out in the song selection menu.
4. Supporters could double click missing maps to download with Direct.

Exporting the maps' titles means we don't need to query the API to know which missing map is the one we are searching.

**Comment by peppy** [comment]
If anything, I'm going in a different direction to this, which is making it easier to access the online catalog via osu!direct (to the point a user doesn't feel the need to download their whole collection every time).

I do not foresee a "download all played maps" ever being a thing. If you wish to do this please use a sync solution like dropbox, which will already provide this ability.

**Comment by Frontear** [comment]
Additionally, if you would like a feature which already does this, please see [osu!sync](https://github.com/naseweis520/osu-Sync/tree/1.0.1.1) (this potentially won't support lazer, however, if you are interested...)
