### ISSUE TITLE
Skinned cursor blending looks wrong on non-black background

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#23521]
### Type

Cosmetic

### Bug description

When the background is completely black, the cursor in my skin looks as intended, but on a background that is not dark, it looks like it's cut off on the edges

### Screenshots or videos

Dark background:
![image](https://github.com/ppy/osu/assets/53346335/8249687a-dd1b-452e-af26-8b8a9efe5e27)
Lighter background:
![image](https://github.com/ppy/osu/assets/53346335/63d310fc-ed8b-4727-a2af-d150d7f10b70)

### Version

master framework and osu! branches

### Logs

Not applicable

Here's my skin file:
https://drive.google.com/file/d/1UaHVIZfeeyGluVA38eC01idCrz2zlnC5/view?usp=share_link

**Comment by Gyoshi** [comment]
On my screen it also looks cut-off on the black background.

I looked at the files, and I'm sorry but the cursor image just is like that. Problem of the skin

**Comment by Sinamer** [comment]
Ah, my bad, it is a perception issue (or low colour accuracy on my screen) that leads to this. Indeed an issue with the skin image
