### ISSUE TITLE
Strict Tracking messing with slider velocity, map time, combo and score

### ISSUE THREAD

**Issue by Acrued** [ppy/osu#23535]
### Type

Game behaviour

### Bug description

By putting on strict tracking, it somehow changes the Slider Velocity (and as a result map time), Maximum Combo, Score per Slider, and total 300 count

It's pretty noticeable if you have a slider at the beginning of a map, I just got a single-slider map to test it out.

### Screenshots or videos

![ST Bug 1](https://github.com/ppy/osu/assets/85308781/68bd1aa9-f799-4685-a6eb-698977687654)
![ST Bug 2](https://github.com/ppy/osu/assets/85308781/3e1c0415-dc5a-47e7-9092-c9260c2cc404)

### Version

2023.51.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11470089/database.log)
[input.log](https://github.com/ppy/osu/files/11470090/input.log)
[network.log](https://github.com/ppy/osu/files/11470091/network.log)
[performance.log](https://github.com/ppy/osu/files/11470092/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11470093/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11470094/updater.log)

**Comment by peppy** [comment]
Please update your game. This was already fixed.
