### ISSUE TITLE
Intel Arc A770 artifacts

### ISSUE THREAD

**Issue by AuracleTech** [ppy/osu#23538]
### Type

Crash to desktop

### Bug description

I don't think I had this issue before the update even with the Intel Arc
As seen on the video the textures seems to bind left and right and the performance destroyed

### Screenshots or videos

https://github.com/ppy/osu/assets/40531871/c4e37026-17b4-4e3d-98d2-f6d5f6612c98

### Version

2023.513.0

### Logs

[performance-audio.log](https://github.com/ppy/osu/files/11470566/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11470567/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11470568/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11470569/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11470570/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11470571/updater.log)
[database.log](https://github.com/ppy/osu/files/11470572/database.log)
[input.log](https://github.com/ppy/osu/files/11470573/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11470574/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11470575/network.log)
[performance.log](https://github.com/ppy/osu/files/11470576/performance.log)

**Comment by AuracleTech** [comment]
![image](https://github.com/ppy/osu/assets/40531871/9cbc0673-cdfe-495e-b262-dc0b233c13cf)
It seems to be an issue with the font atlas

**Comment by AuracleTech** [comment]
I tested 3-4 of versions back they all had this issue then scrolled way down at `2023.403.0` and this one doesn't have the issue
Hope that helps, sadly I have to reinstall it every time I play because the game auto updates 🥹

**Comment by peppy** [comment]
cc/ @smoogipoo (d3d, latest release, a770)

**Comment by smoogipoo** [comment]
@AuracleTech Can you double confirm that this issue started with `2023.417.0`?

**Comment by AuracleTech** [comment]
Ok now I am really confused
I just installed these versions in this order :
2023.403.1 Ok
2023.419.0 Ok
2023.511.0 Ok
2023.513.0 ( latest ) Glitching
2023.511.0 Ok

I am not sure why earlier I had to go so far back to get it working again... Something's up

**Comment by smoogipoo** [comment]
Are you able to debug with a local osu!framework?

**Comment by AuracleTech** [comment]
I test with master?

**Comment by smoogipoo** [comment]
If you can test first on master to ensure you can reproduce, and then by removing this line: https://github.com/ppy/osu-framework/blob/9bd821bf70dd42a27c0b1b83d0cc85e8f355c8e8/osu.Framework/Graphics/Veldrid/VeldridRenderer.cs#L609, that would be perfect.

**Comment by AuracleTech** [comment]
Confirmed 👍 tested 5 more times off camera

https://github.com/ppy/osu/assets/40531871/daf1f93b-1d6b-48c6-a7c7-a6fde98aac63

**Comment by smoogipoo** [comment]
Ok, can you then test if applying this patch fixes the issue (revert the change from above):

```diff
diff --git a/osu.Framework/Graphics/Veldrid/Buffers/Staging/PersistentStagingBuffer.cs b/osu.Framework/Graphics/Veldrid/Buffers/Staging/PersistentStagingBuffer.cs
index ba2044dda4..7fcaabb66c 100644
--- a/osu.Framework/Graphics/Veldrid/Buffers/Staging/PersistentStagingBuffer.cs
+++ b/osu.Framework/Graphics/Veldrid/Buffers/Staging/PersistentStagingBuffer.cs
@@ -15,7 +15,7 @@ internal class PersistentStagingBuffer<T> : IStagingBuffer<T>
     {
         private readonly VeldridRenderer renderer;
         private readonly DeviceBuffer stagingBuffer;
-        private readonly MappedResource stagingBufferMap;
+        private MappedResource stagingBufferMap;
 
         public PersistentStagingBuffer(VeldridRenderer renderer, uint count)
         {
@@ -49,12 +49,16 @@ public Span<T> Data
 
         public void CopyTo(DeviceBuffer buffer, uint srcOffset, uint dstOffset, uint size)
         {
+            renderer.Device.Unmap(stagingBuffer);
+
             renderer.BufferUpdateCommands.CopyBuffer(
                 stagingBuffer,
                 (uint)(srcOffset * Unsafe.SizeOf<T>()),
                 buffer,
                 (uint)(dstOffset * Unsafe.SizeOf<T>()),
                 (uint)(size * Unsafe.SizeOf<T>()));
+
+            stagingBufferMap = renderer.Device.Map(stagingBuffer, MapMode.ReadWrite);
         }
 
         public void Dispose()

```

**Comment by AuracleTech** [comment]
Fixed the issue, you can merge!
