### ISSUE TITLE
Display/Monitor dropdown hidden by default in the settings 

### ISSUE THREAD

**Issue by Xarib** [ppy/osu#23537]
### Type

Cosmetic

### Bug description

**Context**
The game launched on the wrong monitor. I could not find the display/monitor dropdown intiallly in the settings. You cannot find in in the search bar when it is hidden. After the "Display" dropdown appears, you can find it with the searach.

**How to reproduce**
1. Open up osu!
2. Goto settings
3. Goto the section "Graphics"
4. There shoud be no dropdown called "Display"
5. Select "Borderless" in the "Screen Mode" dropdown
6. Select "Fullscreen" in the "Screen Mode" dropdown
7. The "Display" dropdown appears

Or

1. Open up osu!
2. Goto settings
3. Goto the section "Graphics"
4. There shoud be no dropdown called "Display"
5. Tab out of the game
6. Tab back in
7. The "Display" dropdown appears

**Screenshots**

Hidden
![osu_2023-05-13_21-29-43](https://github.com/ppy/osu/assets/67692366/93daf570-52fa-4b8c-afa6-d6a1371ef60b)

Visible
![osu_2023-05-13_21-29-56](https://github.com/ppy/osu/assets/67692366/7286be2e-28e2-4868-b418-1011bc40f235)

**Other**
OS: arch linux

### Version

2023.511.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11470483/database.log)
[input.log](https://github.com/ppy/osu/files/11470485/input.log)
[network.log](https://github.com/ppy/osu/files/11470486/network.log)
[performance.log](https://github.com/ppy/osu/files/11470487/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11470488/runtime.log)

**Comment by bdach** [comment]
Pretty sure this is going to be another regression from https://github.com/ppy/osu-framework/pull/5516 (`Dropdown.Items` set being scheduled).
