### ISSUE TITLE
Flashlight mod doesnt work on Metal renderer

### ISSUE THREAD

**Issue by SeazeIsCool** [ppy/osu#23550]
### Type

Game Behaviour

### Bug description

flashlight just makes everything invisible when using the Metal renderer, works fine on OpenGL tho, noticed this months ago but never reported it

also im on an M1 Macbook Air

https://www.youtube.com/watch?v=afKo5KkIZIs video showcasing the issue

### Screenshots or videos

https://www.youtube.com/watch?v=afKo5KkIZIs

### Version

2023.513.0

### Logs

[database.log](https://github.com/ppy/osu/files/11471640/database.log)
[input.log](https://github.com/ppy/osu/files/11471641/input.log)
[network.log](https://github.com/ppy/osu/files/11471642/network.log)
[performance.log](https://github.com/ppy/osu/files/11471643/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11471644/runtime.log)

**Comment by monochrome22** [comment]
This is known https://github.com/ppy/osu/issues/23368
