### ISSUE TITLE
Hard linked beatmaps become empty if updated from osu!stable

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#23553]
### Type

Game behaviour

### Bug description

After hard linking beatmaps from osu!stable to lazer, launching stable and updating the beatmap, it will not properly show up in lazer anymore

### Screenshots or videos

![osu_2023-05-15_09-37-11](https://github.com/ppy/osu/assets/53346335/cbfdb062-5c95-4939-8a25-d64d27fd9271)

### Version

2023.513.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/11474780/runtime.log)

**Comment by peppy** [comment]
This sounds like a failure at a non-osu! level. Deleting a hard linked file elsewhere should not remove it from disk at all locations, which is what looks like has happened here.

Cannot repro.

![Parallels Desktop 2023-05-16 at 04 27 41](https://github.com/ppy/osu/assets/191335/cb2affcd-7c74-4969-93cb-57701a908298)



https://github.com/ppy/osu/assets/191335/0134a7d0-96c1-455b-877c-0f8381286240

**Comment by Sinamer** [comment]
On a double check, following the process in OP indeed is not the cause as deleting or updating the map from stable works just fine. This is quite odd, a bunch of maps on lazer became empty, the only common denominator being that they were hard linked from stable, and all of those show either pending an update or got a "not submitted" status on stable:
![osu_2023-05-16_08-47-22](https://github.com/ppy/osu/assets/53346335/d418c32a-51c1-4afc-9d68-b3c62e17fe73)
![screenshot136](https://github.com/ppy/osu/assets/53346335/9518e8aa-2cf7-4b9f-9dcc-fb9984096e06)
![osu_2023-05-16_08-51-37](https://github.com/ppy/osu/assets/53346335/1062ff23-588e-43df-ac0a-3580db30f2ec)
![screenshot137](https://github.com/ppy/osu/assets/53346335/e6a45b45-181d-4f1c-aa11-cbc8050d2b2d)
Closing as there are no details on how that happened. I have ran the import from stable process again which resolved those maps being empty, and will report back later if this shows up and I know what lead to it.

**Comment by peppy** [comment]
Did you happen to have a power / system failure at any point in the recent past? We've seen issues with zeroed files which can be attributed to such cases, and the use of unsafe file API. We've already fixed this in common save scenarios but there may be an edge case where it's not applied.

**Comment by Sinamer** [comment]
Yes, I have had to hard power off my laptop multiple times recently due to another game causing my system to freeze. I didn't have osu! open at those moments though, not sure if it would affect osu! folders
