### ISSUE TITLE
"Back to top"/"Previous position" button hides behind the user profile header

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#23566]
### Type

Cosmetic

### Bug description

As title.

### Screenshots or videos

https://github.com/ppy/osu/assets/43073074/e57efae5-32b5-4148-8215-37a9dedf4bd9

Hard to show in a screenshot, but you can see the little shadow in the bottom-right corner here:
![image](https://github.com/ppy/osu/assets/43073074/e47af9ba-29c2-4d01-a89f-4d91f2458c61)

Also, here's a screenshot from the draw visualiser, if it helps to better understand the problem:
![visualiser](https://github.com/ppy/osu/assets/43073074/b413e963-b4b2-440d-8a94-a5f0eb8bbaec)

### Version

2023.513.0-lazer

### Logs

n/a

**Comment by peppy** [comment]
What kind of weird resolution or profile are you visiting to make this happen? It gets nowhere near it for me.

**Comment by cdwcgt** [comment]
https://github.com/ppy/osu/assets/34775378/34879074-279e-4bd2-bccf-091428fe3426

still broken with 00bf79d51f

**Comment by cdwcgt** [comment]
I think the problem is that the button can't be used in profile overlay, so I'm sending it here. If it needs to be start a new issues separately, I will do it

For reproduce, try show my profile in production server but not dev server. Some player pages will trigger this problem. For me, it always happened on my page

**Comment by Gabixel** [comment]
Hmm, I have managed to reproduce something in the master branch. You can't press that button in a specific area. And I think it's what @cdwcgt is trying to explain(?). Judging by the hitbox, it feels like `ProfileSectionTabControl` "is absorbing/cancelling the click on the button (hover included)" (I'm not exactly sure if that's what's happening, but that's the best I can explain it with):
![image](https://github.com/ppy/osu/assets/43073074/dbf7519b-15ae-40ec-928b-b35b7c9bc34d)
The button in question works if I click it outside the marked rectangle.

It probably needs to be opened as a new issue. Let me know.

**Comment by bdach** [comment]
That is indeed a separate issue caused by completely different code. Please open separately.
