### ISSUE TITLE
osu!mania: Hold endnotes are offset incorrectly

### ISSUE THREAD

**Issue by Kosyne** [ppy/osu#2357]
The ends of holds seem to be offset somewhat. Not sure if it has to do with the bit about them being too vertically thin (found here #1377) so I figured I'd make this issue. (That said, I quite like thin notes)

Screenshots:
<details>
<summary>osu!lazer</summary>
<br> 

![osu!lazer](https://i.imgur.com/aKLWaXf.png)
</details>

<details>
<summary>osu! stable</summary>
<br>

![osu!stable](https://i.imgur.com/uqQ9MCd.png)
</details>

**Comment by smoogipoo** [comment]
Are you using `Visualise speed changes as` `overlapping` by any chance (in settings)? Can't replicate with sequential speed changes, which is why I asked.

**Comment by Kosyne** [comment]
Sorry about the late reply here, didn't get the notification.

The map in question can be found here: https://osu.ppy.sh/beatmapsets/110637#mania/298815

This was with no mods or anything like that. Just fresh install, select map, play.

**Comment by LastExceed** [comment]
I did some testing for this bug:
- this bug occurs on ALL mania maps, [including auto-converts](http://puu.sh/AcLcA/b67596aa38.png)
- not just its graphic, but the entire hitobject is being mispositioned. if you release the LN where its supposed to end, lazer will judge it as early-release.
- the offset is constant, but based on time, not visual (changing scrollspeed will change the size of the gap between where its supposed to end and where it actually ends, while changing the bpm will not). the offset is somewhere around 22,5ms (measured with MS paint*).
- this has nothng to do with the way speed changes are visualized, as it also occurs on maps that only have a single timing point (the initial one setting the bpm). to make sure i checked with both the sequential and the overlapping setting, and there was no difference

*I mapped [this pattern](http://puu.sh/AcKeW/f1b6334883.png) (the left singlenote and the LNend are on-beat, while the right singlenote is 1/16 later) in the osu!stable client at various BPM rates and took screenshots from the result in osu!lazer to calculate the offset based on the relative distances between the notes. here are 2 examples showing that the offset is constant: [120bpm](http://puu.sh/AcLIR/f343ca80b0.png) | [200bpm](http://puu.sh/AcLJC/3c210a7d5d.png)

**Comment by AlFasGD** [comment]
Does it work if you remove the leftmost note in the example you provided? In this case, the end of the hold note is at the same time with the hit time of the note on the left. It would be good to know if the bug only occurs when having simultaneous actions or generally.

**Comment by LastExceed** [comment]
As you can see in the example for auto-converts it also happens when there are no other notes

**Comment by AlFasGD** [comment]
I did not check it, my bad. I now came up with another idea, where the universal offset may affect the end note.
