### ISSUE TITLE
The leaderboard rank place is displayed incorrectly

### ISSUE THREAD

**Issue by Takami-Ch** [ppy/osu#23585]
### Type

Game behaviour

### Bug description

![osu! 5_17_2023 7_20_13 PM](https://github.com/ppy/osu/assets/73393168/783124cd-b019-4ef0-88fc-58da7fbfe16a)

### Version

2023.513.0

### Logs

[performance.log](https://github.com/ppy/osu/files/11497487/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11497489/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11497490/updater.log)
[database.log](https://github.com/ppy/osu/files/11497491/database.log)
[input.log](https://github.com/ppy/osu/files/11497492/input.log)
[network.log](https://github.com/ppy/osu/files/11497493/network.log)

**Comment by Theighlin** [comment]
I think there is already an issue open for this, but this boils down to local score recomputation.
Ukty's score (the guy in your place) in the screenshot was submitted with DT at 1,20x speed, which now has a score multiplier of 1,04x, but the server is still treating non 1,50x speeds as if they have a 1x multiplier, so according to the website, you have a higher score than him.
<img width="921" alt="Screenshot 2023-05-17 alle 14 26 19" src="https://github.com/ppy/osu/assets/53081750/66eb74c2-989c-4b05-ba58-0ba5b000bda9">
