### ISSUE TITLE
Undo doesn't work for editor slider velocity & sample changes

### ISSUE THREAD

**Issue by Dimmitsaras** [ppy/osu#23598]
### Type

Game behaviour

### Bug description

Go to the map editor and perform any actions (make sure a slider exists). Change a single slider's velocity and then try to undo that action by pressing ctrl + z

Expected result: the slider velocity changes back
Actual result: Undoing seems to do nothing. Pressing undo again undoes the action before the slider velocity change

By testing with changing the slider velocity more than once, and noting the amount of ctrl+z inputs before any change, it is evident that while the event is written in undo history, its not correctly undone

### Screenshots or videos

https://github.com/ppy/osu/assets/35996393/5d0c20b6-2b0f-44ff-b758-13ea799b1640

### Version

Release 2023.513.0-lazer

### Logs

[performance-input.log](https://github.com/ppy/osu/files/11519588/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11519589/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11519590/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11519591/updater.log)
[database.log](https://github.com/ppy/osu/files/11519592/database.log)
[input.log](https://github.com/ppy/osu/files/11519593/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11519594/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11519595/network.log)
[performance.log](https://github.com/ppy/osu/files/11519596/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11519597/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11519598/performance-draw.log)

**Comment by bdach** [comment]
Applies to samples too. Another victim of https://github.com/ppy/osu/pull/23308.

I may have a proposal for a fix but I need to run it past tests first. Also not sure it's going to be to everyone's liking.
