### ISSUE TITLE
Main audio track is muted forever if direct/profile/beatmap overlay is closed while preview is playing

### ISSUE THREAD

**Issue by UselessToucan** [ppy/osu#2361]
Reproduced on [this commit](https://github.com/ppy/osu/commit/81981acc6850010910d43278d807ea69b7c879d0)

Steps to reproduce:
1. Start some song in the music controller.
2. Open user profile overlay with direct panels.
3. Start preview playback.
4. Close overlay before preview is finished.

Video:
https://streamable.com/li6do

**Comment by StartForKillerMC** [comment]
I will try to solve it

**Comment by UselessToucan** [comment]
Investigating the problem.
`DirectOverlay` works ok since it explicitly stops active preview inside of it's `PopOut` method.
`UserProfileOverlay` doesn't do anything with the active preview during `PopOut`. Shit happens here.

**Comment by peppy** [comment]
Reverted due to fix breaking transitions.
