### ISSUE TITLE
Editor Scripting

### ISSUE THREAD

**Issue by HornyAlpaca** [ppy/osu#2362]
This is a quick overview of an alternative way to implement most of the editor functionality.

The basic idea is to have all but the most basic functions implemented in extern scripts instead of actual code. This would not only make it possible to add custom editor shortcuts, but the creation of the editor might actually prove to be simpler than if we implement all required features directly.

## THE CORE IDEA:

Only have a few things in C#, circle, slider and spinner placement, a simple change log, beat snap change etc.

Implement all other functionality of the editor with scripts, such as undo and redo, actually placing a slider circle or spinner, rotating an object, changing a slider to a stream and so on.

All scripts are saved in a separate folder, similar to the way beatmaps and skins are stored, and loaded once the editor is stored, all scripts are run by a simple JIT-compiler. We can also reuse the notification bar for error and help messages.

In case I did not forget a crucial problem and the people who are currently working on the editor like this idea I would love to both help with building the compiler and with implementing the rest of the editor.

## Example

Editor Layout:

![example1](https://user-images.githubusercontent.com/32333665/38454658-7fde7d44-3a6b-11e8-9eeb-babd9377aba0.png)

Script example, syntax can obviously still be changed/ improved.

```

# comment
# !# is a global
![name = "undo"]  # compiler directive, name in the editor script panel
![defaultShortcut = {"strg", "z"] # default shortcut, editor might ask the user if it wants to use it when the script is imported for the first time
!# reverts the last change made in the editor 
func revert_last_change() # function declaration
    var lastEdit = core.changeStack.pop() # function calls
    lastEdit.revert() # member function support
end func
````

```
func a()
    if mouse.position.x > 4 then
         core.place_circle(0, 10)
    else
         core.error("invalid mouse position")
    end if
end func
```

**Comment by smoogipoo** [comment]
Firstly: This won't result in the creation of the editor being any simpler than it currently is. In-fact on the contrary - the client will need a lot of implementation to begin to even JIT the code (JITting isn't easy 'yo!), never mind the standard library and everything. The exact same complexity of coding the editor will be added on top of that. This is not feasible for us.

Secondly, we're coding the editor in a way that it's usable for all current and future rulesets without much re-implementation at all. The only functionality the scripting language can reasonably add on top of that is shortcuts, however there's no reason we can't implement those in neater ways (macros) without having to resort to implementing a whole language. Now, you can propose that scripting support be added on top of that in the future, but we won't be looking into it until lazer's complete at the very least.

Anyone will be able to request additions if they find functionality that is not possible in the editor. It's super not hard to use C# for core functionality.

Closing this based on the above reasoning.

**Comment by peppy** [comment]
Completely agree with @smoogipoo here. This is not the direction we are going. But don’t worry, we will be exposing much of the necessary modular functionality to rulesets.
