### ISSUE TITLE
Osu lazer freeze bug

### ISSUE THREAD

**Issue by Adameczu** [ppy/osu#23629]
### Type

Other

### Bug description

so yea, when you are on lazer and you are spinning the spinner don't use ctrl+shift+r to change skin cuz it freezes, like there is still audio, but u can't do anything. 

btw I hope you will fix that pretty quick and I will be able to see that bug fix on ur channel on youtube "osu!"

### Version

lazer latest / 2023.513.0

### Logs

[database.log](https://github.com/ppy/osu/files/11534641/database.log)
[input.log](https://github.com/ppy/osu/files/11534642/input.log)
[network.log](https://github.com/ppy/osu/files/11534643/network.log)
[performance.log](https://github.com/ppy/osu/files/11534644/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11534645/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11534646/updater.log)

**Comment by bdach** [comment]
I can't reproduce this bug. Please attach a video of this.

**Comment by Adameczu** [comment]
now i also cant recreate it so i think there is sth with my tablet driver or my laptop so im closing.
