### ISSUE TITLE
Impossible to map Del key to anything

### ISSUE THREAD

**Issue by Zyfarok** [ppy/osu#2363]
![image](https://user-images.githubusercontent.com/10669609/38461434-09dfda06-3ad0-11e8-9bb7-cae610ad8cbf.png)
Because of this, it's impossible to map Del key to anything.
(I usually use the del key with my right hand in mania cause I like how the key is placed on the keyboard)

Not sure if it can be called "a bug" but it looks like a design flaw.
Allowing the user to use a combination like Shift/Ctrl/Alt+Del to map the Del key (or at the opposite, to use a combination to delete the shortcut) would actually fix it.

**Comment by Joehuu** [comment]
Already resolved.
