### ISSUE TITLE
Weird Graphical Issues on DX11 with new update

### ISSUE THREAD

**Issue by Tellilum** [ppy/osu#23645]
### Type

Game behaviour

### Bug description

I was playing through a song and noticed odd graphical issues that happened multiple times throughout the map, i managed to capture it through autoplay so i could be sure i wasn't just seeing things

sure enough some graphics and icons are bugged, often not being fully transparent, items being replaced with other icons, etc. 

my GPU is an RTX 3060 if that could be of importance.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/59491721/93f6d27f-e70b-41b2-9d78-a3e37e44670e)
![image](https://github.com/ppy/osu/assets/59491721/3bc2372b-9250-43b2-ab9c-203506693321)
![image](https://github.com/ppy/osu/assets/59491721/82e5608b-0579-4e25-8cf4-ff036af94a40)
![image](https://github.com/ppy/osu/assets/59491721/f9e4c026-d4b7-4939-aed9-34370180767c)

### Version

2023.513.0

### Logs

[database.log](https://github.com/ppy/osu/files/11552548/database.log)
[performance.log](https://github.com/ppy/osu/files/11552556/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11552557/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11552558/updater.log)
[input.log](https://github.com/ppy/osu/files/11552559/input.log)
[network.log](https://github.com/ppy/osu/files/11552560/network.log)

**Comment by FWone** [comment]
The only thing you can do for now is to Downgrade from osu!lazer 2023.513.0 to osu!lazer 2023.511.0
It worked well for me

**Comment by bdach** [comment]
@Tellilum Can you check today's release and see if this got any better (or worse)?

**Comment by Tellilum** [comment]
@bdach Looks like it's better! i haven't seen any visual glitches at all.

**Comment by peppy** [comment]
Tentatively closing for now then, thanks.
