### ISSUE TITLE
Can't quite map before the first timing point like in stable

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu#23666]
### Type

Game behaviour

### Bug description

In stable the timeline has snap-lines(?) at the top timeline before the first timing point that follows the same bpm and you're able to map there. 

I can map before the first timing point in lazer but only to the point where the hitcircle is in the image while there is a sound before the hitcircle that I can't reach.
This should be like in stable and would be good for when a song has sounds before the song starts. In this case 3 piano notes before the song.

### Screenshots or videos

<img width="1440" alt="Skärmavbild 2023-05-26 kl  08 58 16" src="https://github.com/ppy/osu/assets/81715029/7e31d3de-7063-4450-a353-c909485d6338">

### Version

2023.513.0

### Logs

[database.log](https://github.com/ppy/osu/files/11572432/database.log)
[input.log](https://github.com/ppy/osu/files/11572434/input.log)
[network.log](https://github.com/ppy/osu/files/11572435/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/11572436/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11572437/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11572438/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11572439/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/11572440/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11572441/runtime.log)

**Comment by peppy** [comment]
This looks to be specific to the taiko editor.
