### ISSUE TITLE
Accuracy heatmap is empty after ScoreV2 merge.

### ISSUE THREAD

**Issue by Charlese2** [ppy/osu#23712]
### Type

Game behaviour

### Bug description

Commit 3c3c812e removed an override for [CreateHitEvent](https://github.com/ppy/osu/commit/3c3c812ed6dfca27d7ffa2db07703c93d57d52b9#diff-08cebd43769e2045a09e504d29a395bdbdf0dd784dee0b21d6810f533b4721ceL23-L24) that includes the cursor position at the time of the hit event that the Accuracy Heatmap relies on. https://github.com/ppy/osu/blob/812def124f28fa7320789c59fa2525ad07def194/osu.Game.Rulesets.Osu/Statistics/AccuracyHeatmap.cs#L209-L215
e.Position always ends up `null` so the heatmap ends up empty.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/1207515/ebe9d94b-5ee1-4f05-ae88-ec24d82100ed)

### Version

Local Debug Build (812def12)

### Logs

[database.log](https://github.com/ppy/osu/files/11617610/database.log)
[input.log](https://github.com/ppy/osu/files/11617611/input.log)
[network.log](https://github.com/ppy/osu/files/11617613/network.log)
[performance.log](https://github.com/ppy/osu/files/11617614/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11617615/runtime.log)

**Comment by bdach** [comment]
I haven't reviewed the PR in question, but I see basically zero reason for the removal of the override in question. @smoogipoo?

**Comment by smoogipoo** [comment]
Whoops, that was not intentional. Good catch.
