### ISSUE TITLE
Tablet option spamming notifications with errors when activated.

### ISSUE THREAD

**Issue by Alawapr** [ppy/osu#23710]
### Type

Game behaviour

### Bug description

I was trying to get osu! lazer running on my freshly installed Linux (EndeavourOS) when I just couldn't figure out why OpenTabletDriver just won't work, it just doesn't detect my tablet (Gaomon S620).
I resorted to trying to play with Lazer's built-in tablet drivers, but when I tried to enable them, a whole wall of notifications would spam the screen as seen in the video below.

### Screenshots or videos

https://github.com/ppy/osu/assets/93432929/0dc86d3f-23ca-4506-ad07-65163a8a0b97

### Version

2023.513.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11616059/database.log)
[input.log](https://github.com/ppy/osu/files/11616060/input.log)
[network.log](https://github.com/ppy/osu/files/11616061/network.log)
[performance.log](https://github.com/ppy/osu/files/11616062/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11616063/runtime.log)

**Comment by bdach** [comment]
Looking at [opentabletdriver source](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/94b0c2d8d13ed689f0c284af45823c23eda647f0/OpenTabletDriver/Driver.cs#L147-L156) it seems that this indicates that the tablet is being occupied by another kernel module. Please try following instructions from https://opentabletdriver.net/Wiki/FAQ/Linux#argumentoutofrangeexception to resolve.

That said, we probably don't want this to spam notifications that much. Not sure on which side this should be handled though.

**Comment by peppy** [comment]
The other thing is we have debounce logic to avoid such error spam from occurring:

https://github.com/ppy/osu/blob/8c542c6c51134a7357a631f15a2d5fca0bfc5edc/osu.Game/OsuGame.cs#L1084-L1123

But because we're manually handling these tablet errors it's bypassed:

https://github.com/ppy/osu/blob/8c542c6c51134a7357a631f15a2d5fca0bfc5edc/osu.Game/OsuGame.cs#L1125-L1145

I'll try to see if I can fix that part.
