### ISSUE TITLE
Fullscreen mode sets 75hz monitor to 60hz

### ISSUE THREAD

**Issue by Jaec0b** [ppy/osu#23728]
### Type

Performance

### Bug description

windows 10 22h2 latest update

description of bug:

Whenever I set osu! lazer to fullscreen, it goes to 60hz even though I have my monitor set to 75hz in Nvidia control panel.
it works at 75hz when set to borderless.
this does not happen in osu! stable.

I set my frame limit to 2x refresh rate, and you can see how it goes from 120fps (60hz) in fullscreen to 150fps (75hz) in borderless in the bottom right fps display thing.
(sorry if I'm doing this wrong, I don't really use GitHub)

### Screenshots or videos

https://youtu.be/QIeLZcKwTv4

### Version

2023-513.0 lazer

### Logs

[network.log](https://github.com/ppy/osu/files/11631632/network.log)
[performance.log](https://github.com/ppy/osu/files/11631634/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11631635/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11631636/updater.log)
[database.log](https://github.com/ppy/osu/files/11631637/database.log)
[input.log](https://github.com/ppy/osu/files/11631638/input.log)

**Comment by Jaec0b** [comment]
This still happens in the latest 2023.605.0 version

**Comment by Mineplayerminer** [comment]
Omg I was just about to cover this issue, but thanks for posting it. I'm so angry over the 60hz lock. I can't run it in the borderless as it just adds latency.

**Comment by peppy** [comment]
Tracking at https://github.com/ppy/osu-framework/issues/4081.
