### ISSUE TITLE
As of 2023.605.0 combo and accuracy are not shown in multiplayer ingame

### ISSUE THREAD

**Issue by r00ster91** [ppy/osu#23758]
### Type

Game behaviour

### Bug description

In a regular multiplayer room with all freemods enabled, Team VS game type, All Players queue mode, auto start off, and no password, in all games so far I haven't been able to see the combo or accuracy of my friend (and other people) ingame either during a break in the beatmap or at the end of the beatmap.

My friend is reporting the exact same thing about me. 

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/35064754/405131de-847a-4439-9e70-5b30cdb4d67d)
Another one:
![image](https://github.com/ppy/osu/assets/35064754/92028a77-7e55-42b5-ac22-1747b25d99d0)

Top one is me in both.

And here's one where I could actually see combo and accuracy for one person:
![image](https://github.com/ppy/osu/assets/35064754/ddb40ee0-47ca-4ddb-b965-5506091e61ad)

New one:
![image](https://github.com/ppy/osu/assets/35064754/ca65d400-5ec0-4071-a929-ba31d7490d56)
Theory: only the accuracy & combo of the ppl above are shown

### Version

2023.605.0

### Logs

Sorry, no logs. I could provide them if this issue is harder to reproduce. Feel free to close if that makes this issue unacceptable.

Maybe when I finished playing.

**Comment by bdach** [comment]
I couldn't reproduce this on dev environment, so I went to check on production (the same room that the OP reported this on, in fact), and could see that some of the users didn't have their acc/combo update at all - but then, seemingly only after a reboot of one of the users, everything went back to normal.

No idea what is going on here.

**Comment by r00ster91** [comment]
Updating to 2023.605.0 seems to fix this.

**Comment by r00ster91** [comment]
Seems fine.

**Comment by bdach** [comment]
I guess *something* we did must have broke old clients, but I'm not even really sure what it was, and I'm not super sure it's worth putting time into investigating.

Thanks for the help though.

**Comment by peppy** [comment]
The changes were supposed to completely break old clients (changes to replay header). We really need server versioning (https://github.com/ppy/osu-server-spectator/issues/52).
