### ISSUE TITLE
Triangles song progress bar indeterministically blinking in gameplay

### ISSUE THREAD

**Issue by bdach** [ppy/osu#23760]
"Regressed" in https://github.com/ppy/osu/pull/23451.

The root cause of this is:

https://github.com/ppy/osu/blob/25d0f0f3da506aa0af19edf58c8fe4222a3f6532/osu.Game/Screens/Play/HUD/DefaultSongProgress.cs#L104

`info.Height` seems to fluctuate throughout the beatmap, causing needless invalidations of the graph because its height is changing ever so slightly. I would probably just round that but maybe there are other opinions?

For anyone wanting to reproduce - this may be resolution-dependent, since I couldn't get this to happen windowed, but did pretty much immediately when fullscreen.

### Discussed in https://github.com/ppy/osu/discussions/23757

<div type='discussions-op-text'>

<sup>Originally posted by **Firmatorenio** June  5, 2023</sup>
The bar in question seems to be randomly reinitializing during gameplay, as seen on the [video](https://www.youtube.com/watch?v=KFsc1ulWV2Y).

Some things I've tested around:
- happens across all gamemodes and on any map
- doesn't seem to be tied to specific spots in the maps (so, seems completely random and doesn't happen on the same spots across different plays)
- happens with auto too
- isn't specific to my custom skin and happens with the default triangles (2017) skin too
- happens on both ogl and dx11

For reference, I don't like the new argon progress bar and would rather not switch to it because it makes it difficult to judge the density of the parts of the map that are already completed.

[runtime.log](https://github.com/ppy/osu/files/11656051/runtime.log)</div>

**Comment by peppy** [comment]
Rounding sounds best.
