### ISSUE TITLE
Multiplayer leaderboard not updating

### ISSUE THREAD

**Issue by megadrive7** [ppy/osu#23764]
### Bug description

Played a lobby with my friends, noticed that the leaderboard throughout the entire song stayed at zero score and zero accuracy, and the rankings did not update. My friends in the lobby saw this as well. In this same lobby there was another bug involving the spectating system (seems very similar to issue https://github.com/ppy/osu/issues/20151, but it seems that on mine the spectating never starts. it stays on the screen of the map's background, and stays there even after they have finished playing the song and until they start a new one).

### Screenshots or videos

https://github.com/ppy/osu/assets/112918046/9105ee73-00d6-4be1-b31c-eaca34c897d7

### Version

2023.605.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11659808/database.log)
[input.log](https://github.com/ppy/osu/files/11659809/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11659810/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11659811/network.log)
[performance.log](https://github.com/ppy/osu/files/11659813/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11659814/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11659815/updater.log)

**Comment by peppy** [comment]
Please make sure your friends update to the latest release.

**Comment by megadrive7** [comment]
> Please make sure your friends update to the latest release.

all three of us are on the latest update

**Comment by peppy** [comment]
I've tested and all looks good from my end. We had other reports of this and it was always due to outdated clients, so please triple-check.

**Comment by megadrive7** [comment]
i asked them both over call and confirmed that they were both on 2023.605. its possible it auto updated one of them after the bug occurred, although it seems to be unlikely. haven't been able to reproduce it though so maybe that was the answer after all
