### ISSUE TITLE
Switching between beat snap groups always resets to 1/1 snap

### ISSUE THREAD

**Issue by seritools** [ppy/osu#23786]
### Type

Game behaviour

### Bug description

Mapping something that switches between 1/4 and 1/4 beat snap frequently gets frustrating quickly because switching between "common" and "triples" always resets back to 1/1. In combination with #23785 this makes switching take a *lot* of extra clicks, whereas in stable you just drag the beat snap slider a couple of pixels.

I'm not sure what the solution would be for this new beat snap UI, but maybe remembering the last value per group could work? And then, thinking even further, maybe a shortcut to switch the beat snap group could be helpful as well?

### Screenshots or videos

![osu!_22FKaxTCJy](https://github.com/ppy/osu/assets/5844066/8c23be22-edf7-47d6-a8c0-7f89c86b2dda)

### Version

2023.605.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11669624/database.log)
[input.log](https://github.com/ppy/osu/files/11669625/input.log)
[network.log](https://github.com/ppy/osu/files/11669626/network.log)
[performance.log](https://github.com/ppy/osu/files/11669627/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/11669628/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/11669629/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11669630/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11669631/updater.log)

**Comment by peppy** [comment]
See #23463 and #23772 which cover this behaviour
