### ISSUE TITLE
Problem with points

### ISSUE THREAD

**Issue by Maxplay141** [ppy/osu#23780]
### Type

Performance

### Bug description

So I just played some batman and noticed that I pass it better than last time but got smaller number of points. (same mods, same diff everything same, no spinners)

### Screenshots or videos

https://github.com/ppy/osu/assets/130863605/046329bf-85df-47cf-a081-f89c3b99cdbb

### Version

2023.605.0

### Logs

[database.log](https://github.com/ppy/osu/files/11666914/database.log)
[input.log](https://github.com/ppy/osu/files/11666916/input.log)
[network.log](https://github.com/ppy/osu/files/11666917/network.log)
[performance-update.log](https://github.com/ppy/osu/files/11666918/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/11666919/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11666920/runtime.log)

**Comment by monochrome22** [comment]
That's because lazer uses ScoreV2 now. Your old score was made with the old scoring system.
Some more information regarding the new scoring system can be found in the [lazer update video](https://m.youtube.com/watch?v=iV6IdUcwHLY&pp=ygUMbGF6ZXIgdXBkYXRl) .

**Comment by bdach** [comment]
As above, see https://github.com/ppy/osu/discussions/23761
