### ISSUE TITLE
Scores from previous lazer releases are incomparable to new ones after ScoreV2 introduction

### ISSUE THREAD

**Issue by Xen0Xys** [ppy/osu#23782]
### Type

Game behaviour

### Bug description

As on my screenshot, when playing on the new update (2023.605.0-lazer), the new score created (one of the bottom) is really lower than previous.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/47594493/d230cc99-d003-4072-9f67-1d18c045e67e)

### Version

2023.605.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/11668492/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11668493/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11668494/updater.log)
[database.log](https://github.com/ppy/osu/files/11668495/database.log)
[input.log](https://github.com/ppy/osu/files/11668496/input.log)
[network.log](https://github.com/ppy/osu/files/11668497/network.log)

**Comment by monochrome22** [comment]
This is because lazer is now using a new scoring system, ScoreV2. Your old scores were set using a different scoring system.
You can find more information about the new scoring sytem at the [lazer update video](https://www.youtube.com/watch?v=iV6IdUcwHLY).

**Comment by Xen0Xys** [comment]
So is there a way to migrate my old scores to the new scoring system in the objective to see a personal progression ?
And if it's not possible (which would be a real shame), how to delete my local scores ?

**Comment by GDcheeriosYT** [comment]
I also found this

https://github.com/ppy/osu/assets/54640414/bde9a1e8-de57-4d94-8c88-5e8bd51f429c

**Comment by monochrome22** [comment]
That's https://github.com/ppy/osu/issues/23756.

**Comment by GDcheeriosYT** [comment]
ah, ok. 👍

**Comment by bdach** [comment]
Let's keep this issue for tracking the "old lazer score algorithm" problem, and use https://github.com/ppy/osu/issues/23756 for the "scores imported from stable" problem.

**Comment by peppy** [comment]
> how to delete my local scores ?

You can delete all scores using the maintenance button at the bottom of settings.

![osu! 2023-06-09 at 05 14 55](https://github.com/ppy/osu/assets/191335/b7f9a3c0-ad36-41d3-8c67-c06275caa803)


You can also delete per-beatmap:

![osu! 2023-06-09 at 05 17 10](https://github.com/ppy/osu/assets/191335/caf427b0-6296-4e1d-a73b-990ad7e4d050)

Or per-score (right click):

![osu! 2023-06-09 at 05 17 34](https://github.com/ppy/osu/assets/191335/a1347985-898d-40d3-b388-70f2aa988f84)

**Comment by peppy** [comment]
The general consensus on the lazer (old) vs lazer (new) scoring seems to be that we should just let it be. It's going to be very hard to make any sense of trying to cross-compare the scores.

So I'd recommend deleting any scores that feel out of place to you.

Of note, we're going to hotfix osu!mania, where the difference in the two scoring algorithms was massive (#23816).
