### ISSUE TITLE
Flashlight slider dim slower than stable

### ISSUE THREAD

**Issue by nightaaas** [ppy/osu#23797]
### Type

Game behaviour

### Bug description

When pressing slider head in o!stable, the dark overlay immediately appears, while compared to o!lazer, the dark overlay gradually fades up in the span of (roughly) 6 frames.

### Screenshots or videos

Replay Video : https://youtu.be/UNYVScORSuQ

Frame by frame breakdown : https://youtu.be/8mLH7WCko9M

### Version

2023.605.0

### Logs

[osu!auth.log](https://github.com/ppy/osu/files/11672743/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/11672744/runtime.log)
[session.log](https://github.com/ppy/osu/files/11672745/session.log)
[update_success.log](https://github.com/ppy/osu/files/11672746/update_success.log)

**Comment by peppy** [comment]
It's applied over 50ms. I believe I did this intentionally to make it less abrupt. Whether that's seen as breaking a gameplay mechanics will need to be discussed.

**Comment by nightaaas** [comment]
In my experience playing with HDFL, I feel like it helps quite a bit, but that can just be a placebo effect, plus I just realized that the combo gained were less than stable, meaning the flashlight area stays bigger for longer, therefore making the map I played easier.

**Comment by bdach** [comment]
This also looks like another "make like stable" issue? What are the sticking points on this one?
