### ISSUE TITLE
Editing skins / resizing window after pausing results in gameplay display issues

### ISSUE THREAD

**Issue by Jan-Arbus** [ppy/osu#23814]
### Type

Cosmetic

### Bug description

Open the skin editor after pausing playback
Seems to only appear in Mania

### Screenshots or videos

https://github.com/ppy/osu/assets/74862110/921b9393-fdf5-4ed2-bdc8-f6cb1c3ca1a2

### Version

2023.605

### Logs

N/A

**Comment by peppy** [comment]
This is due to `FrameStabilityContainer` basically ensuring that `Update` doesn't run when paused. It has similar weird layout effects in taiko, at very least.

At some point we need to change things around to allow `Update` to run, at least for some part of the hierarchy.

**Comment by bdach** [comment]
Has since been fixed (most likely by https://github.com/ppy/osu/pull/26606)
