### ISSUE TITLE
Ctrl+o not working with ctrl and caps swapped

### ISSUE THREAD

**Issue by lfpraca** [ppy/osu#23895]
### Type

Other

### Bug description

In one of these 3 commits: https://github.com/ppy/osu/commit/298989ffd20899d18a6c4004d08c827e710dcbcc, https://github.com/ppy/osu/commit/e68ba6366c88554db3bee4332be5f1563e4257c1, https://github.com/ppy/osu/commit/a9ba16a2be5d8355248d658ddb90867799dc86ba a change was made that made Ctrl+o stop working if the Ctrl and Caps Lock keys are swapped. Before these 3 commits, the behaviour was as expected, the physical Caps Lock key mapped to the Ctrl key registered as the Ctrl key in osu!, but it seems to not be registered in the game at all after these commits, neither as Ctrl or Caps Lock.

Additional information: In the logs there is an additional tablet error that is just due to the wacom kernel module being active. This is not an issue at all and has no relation to this issue I am filing.

### Version

a9ba16a2be5d8355248d658ddb90867799dc86ba

### Logs

[database.log](https://github.com/ppy/osu/files/11728021/database.log)
[input.log](https://github.com/ppy/osu/files/11728022/input.log)
[network.log](https://github.com/ppy/osu/files/11728023/network.log)
[performance.log](https://github.com/ppy/osu/files/11728024/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11728026/runtime.log)

**Comment by peppy** [comment]
Please add any more information to the discussion thread.

**Comment by lfpraca** [comment]
I understand if this issue is too niche to be looked at at this point, but it is definitely an issue. I built the game commit by commit to try to figure out the problem, due to the build failing on some commits, I could only narrow it down to 3, not one in particular. But this allowed me to confirm that this problem is somewhere within the game itself. The game files, the system configuration, everything else is exactly the same both when it did and when it did not work.

If it is indeed the case that this is not important enough right now, I would appreciate if you could point me in some direction in the codebase where something like this could be handled so that I can try to fix it myself and submit a PR

**Comment by lfpraca** [comment]
Yes, this is correct.

I've been doing some more digging and it is indeed something that came from osu.Framework.

I don't really understand how this can be possible but locally, the change from version 2023.513.0 to 2023.521.0 happened in commit https://github.com/ppy/osu/commit/298989ffd20899d18a6c4004d08c827e710dcbcc , even though there is no change at all in osu.Game.csproj on this commit when inspecting in GitHub.

If I understand your last point correctly, I think you mean that it would be more correct for the keys to be unswitched. I do understand that but the behaviour, as of now, is that Caps Lock works normally while Ctrl doesn't work at all.

Anyway, I will wait for a new version to be released with the changes in this pull request. In the event that it is something else, now I have better idea of where to look. Thank you for the response.

**Comment by bdach** [comment]
> If I understand your last point correctly, I think you mean that it would be more correct for the keys to be unswitched

That is not quite what I said. It is more correct _for SDL_ to not switch scan codes of modifiers around, since the _point_ of scan codes is to identify this one concrete physical key that is being pressed. For what you want to achieve, we're using scan codes incorrectly in the game, which is supposed to get resolved with the pull request that I linked.
