### ISSUE TITLE
FPS drop on a slider

### ISSUE THREAD

**Issue by silvestron** [ppy/osu#23894]
### Type

Performance

### Bug description

Dramatic fps drop playing https://osu.ppy.sh/beatmapsets/1746664#osu/3598398 during a slider at 2:22. It goes down to 20fps according to the fps counter, but it feels lower than that.

### Version

2023.610.0-lazer

### Logs

The game didn't crash.

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/21495
