### ISSUE TITLE
Audacity and osu! waveform in editor disagree on the timeline for particular songs

### ISSUE THREAD

**Issue by Trung0246** [ppy/osu#23897]
### Type

Game behaviour

### Bug description

Is something wrong with the waveform of this song in lazer? I want to double check why osu! waveform showing wrong waveform at wrong time point.

https://osu.ppy.sh/beatmapsets/1676482#osu/3902488

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/11626920/b4c11ea6-68c9-4dbc-a693-0205f9a85f5a)

### Version

2023.610.0

### Logs

No logs necessary I hope.

**Comment by peppy** [comment]
Tracking in https://github.com/ppy/osu/issues/21947

**Comment by peppy** [comment]
That said, if it's a particular track, it may be an issue with mp3 headers or similar. Might be worth further investigation.
