### ISSUE TITLE
Realm unable to load database

### ISSUE THREAD

**Issue by Terochi** [ppy/osu#23909]
### Type

Crash to desktop

### Bug description

Occurs only in the latest version. Tried to switch back to 2023.610 with the backup and works fine.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/100224757/57d31d71-3327-4cdc-b829-2e6981a6cbcb)

### Version

2023.614

### Logs

[performance.log](https://github.com/ppy/osu/files/11743311/performance.log)
[database.log](https://github.com/ppy/osu/files/11743312/database.log)
[updater.log](https://github.com/ppy/osu/files/11743313/updater.log)
[input.log](https://github.com/ppy/osu/files/11743314/input.log)
[network.log](https://github.com/ppy/osu/files/11743315/network.log)
[runtime.log](https://github.com/ppy/osu/files/11743316/runtime.log)

**Comment by peppy** [comment]
Should be fixed in the hotfix release. You can recover your database by renaming it back from `_corrupt`.

**Comment by peppy** [comment]
@Terochi can you confirm you were able to recover your database and close this issue if so?

If you're having troubles please attach your database.

**Comment by Terochi** [comment]
Yes, db recovered and converted correctly.
