### ISSUE TITLE
Scores imported into osu!lazer from osu!stable are broken in Lazer 2023.614.1

### ISSUE THREAD

**Issue by UltimateCactus** [ppy/osu#23912]
### Type

Game behaviour

### Bug description

After updating to osu!lazer 2023.614.1 my imported scores from osu!stable have been completely broken. A large majority of scores have been increased substantially (from ~1,000,000 to upwards of 7,000,000), whilst a few (seemingly beatmap and/or difficulty specific, I'm not sure) have been greatly reduced (over 1,000,000 to around 200,000). I'm also not convinced that the old osu!lazer scores have been re-scored correctly, as they seem off.
The images attached shows various imported scores.
I have a video of me going through them but it is way to big to upload and almost 5 minutes long.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/89234997/35ac935b-152a-4d20-a141-e7e1e651e93d)

### Version

2023.614.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11745041/database.log)
[input.log](https://github.com/ppy/osu/files/11745042/input.log)
[network.log](https://github.com/ppy/osu/files/11745043/network.log)
[performance.log](https://github.com/ppy/osu/files/11745045/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11745046/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11745047/updater.log)

client.realm (zipped because I can't upload it otherwise)
[client.realm.zip](https://github.com/ppy/osu/files/11745051/client.realm.zip)

**Comment by peppy** [comment]
- Please remove all but one screenshot.
- Please include lazer logs, not stable logs
- Please include client.realm

**Comment by UltimateCactus** [comment]
> Please remove all but one screenshot.

I have updated it with the most inflated imported score. Should I also include a screenshot of the most deflated imported score (Silver SS down to ~240,000)?

**Comment by UltimateCactus** [comment]
There are also some serious discrepancies between different plays (both from v1 and v2 lazer scoring) that have arisen with this update. I'm not entirely sure how the scoring works but I have some plays that are clearly better than others and yet are scoring significantly lower than these "adjusted" scores.

**Comment by cdwcgt** [comment]
[cdwcgt playing Hello_ Happy World_ - Shin Takara Jima (TT Mouse) [Insane] (2020-11-24_21-38).zip](https://github.com/ppy/osu/files/11745878/cdwcgt.playing.Hello_.Happy.World_.-.Shin.Takara.Jima.TT.Mouse.Insane.2020-11-24_21-38.zip)
It should not be a problem of database migration
This replay file has a score of 287,650 on replay

![image](https://github.com/ppy/osu/assets/34775378/e8dffd50-6bde-427b-84d0-c9da5de92d38)

when reimported as 1,157,358
![image](https://github.com/ppy/osu/assets/34775378/a732b86c-737c-4c8f-91c2-9b2c781b0f17)

Apparently lazer completely ignores the original score when importing and re-calculate with **only statistics** 

https://github.com/ppy/osu/assets/34775378/0f3257f4-0b44-4515-9a40-b786c0e722da

**Comment by bdach** [comment]
@cdwcgt i'm not even sure you're reporting the same issue that the OP is. can you move your thing to a separate issue thread thanks

**Comment by cdwcgt** [comment]
this is issues is about `Scores imported into osu!lazer from osu!stable`
So I think they are the same problem.

reimport also can be import other's lazer score.
I do re-import just let you see the score calculation error more intuitively.

That is, the difference between the normal score and the imported score

**Comment by bdach** [comment]
@UltimateCactus just to clarify: you did *not* import the scores that you show in your screenshot *after* updating to the latest release? you only updated to the latest release and saw the scores change, correct?

i'm asking because that's how i understand the report. @cdwcgt seems to understand otherwise but i'm pretty sure they're wrong.

**Comment by UltimateCactus** [comment]
> just to clarify: you did not import the scores that you show in your screenshot after updating to the latest release, right? you only updated to the latest release and saw the scores change, correct?
Correct. The scores were imported around 3 months ago when I started playing lazer. I cannot 100% confirm that the scores changed in the latest release as I do not have any photo evidence, however I believe that they did change as of this latest release.

> are you using standardised or classic score display? which were you using on previous release?
I am using the standardised display. I have not changed this setting and to be honest I didn't even know it was a thing until now.

> can you replay the "broken" scores at all?
Yes I can, and upon finishing watching the replay it gives an accurate v2 score as if I had just played it (which I believe is how the replay system is meant to work).

> are you able to attach an exported replay that you consider "broken" so that we may try to retrace what happened to it?
This .zip file contains two replays. The first file ("Ultimate_Cactus playing Hinkik - Time Leaper") is the replay that is shown as number 1 in the screenshot of the bug report. The second file ("Ultimate_Cactus playing MDK - Fingerbang") is a replay of a silver SS that has had its score reduced to ~240,000.
[imported replays.zip](https://github.com/ppy/osu/files/11751933/imported.replays.zip)

In my opinion considering that viewing a replay calculates the score based on the current scoring system a good fix for this issue would be an option to recalibrate scores of all replays (or just imported replays) in order to correct their scores and place them more in line with the current scores. I am not sure if reimporting old scores would do this anyway, but I don't think that would fix the discrepancies between old v1 and new v2 lazer scores.

**Comment by bdach** [comment]
Thanks for the details supplied.

I've looked into the replays you attached. The score values you mention being "inflated" and "reduced" match the ones stored in the replay files exactly. lazer never touched the actual replay values, which means those must be the score v1 values as written by stable.

What likely happened - and I'm extrapolating a bit here - is that you upgraded to 2023.614.1 from a version _earlier_ than 2023.605.0, which is the release that reintroduced score v2 to lazer. The results are still not as you expect, but if my supposition is correct, then this bug report is a duplicate of https://github.com/ppy/osu/issues/23756, and we have work pending to address it.

Please confirm whether my thinking is correct before I proceed further (either by continuing investigation, or by closing this as duplicate).

**Comment by UltimateCactus** [comment]
My bad. I just checked osu!stable and yes those are the actual scores. My mistake I just got confused when they changed back to the old stable scoring, in combination with the conversion of old lazer scores. I believe that the old lazer scores conversion to v2 is still incorrect, however this issue is just a mistake on my behalf so I will close this issue.
