### ISSUE TITLE
Submitting score with higher accuracy but equal PP to a previous one doesn't mark it as "high score"

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#23914]
### Type

Game behaviour

### Bug description

Previously reported in [discord](https://discord.com/channels/188630481301012481/1097318920991559880/1118170559713398854).

Seems like the server responsible for processing scores doesn't properly handle a score with higher accuracy but equal PP to a previous score. It ignores the new score with higher accuracy and keeps the previous one as "high score".

As an aside, the fact that two scores with different stats have equal PP may be a sign of precision loss, but I haven't checked whether that's the case, as I'm only reporting this just so it doesn't get lost behind other discord messages.

### Screenshots or videos

Taking the [reporter's account](https://lazer.ppy.sh/users/31521396) as an example,

Current high score:

![CleanShot 2023-06-14 at 15 18 12](https://github.com/ppy/osu/assets/22781491/4aeafb94-0ace-478d-831f-74c183e06e63)

Recent play:

![CleanShot 2023-06-14 at 15 18 25](https://github.com/ppy/osu/assets/22781491/d97c0b3a-d4a2-4349-bcc2-cea3a513bd8a)

### Version

-

### Logs

-

**Comment by bdach** [comment]
I made a [loose inquiry on the pp development server](https://discord.com/channels/546120878908506119/619282780563570688/1143469326213599262) and it seems that there are several opinions on this and not many seem to be strong. So we're probably fine with taking score as the tiebreaker and running with it?

I also floated the idea of increasing precision for pp values but I'm not really sure we need to do that for this.

**Comment by bdach** [comment]
Increasing precision was generally the most favourably looked upon conclusion, so from a user acceptance angle that's a good way out. Unsure about fp errors, and unsure how we'd even check, probably something we'd learn N months down the line after applying the change...

**Comment by peppy** [comment]
On investigating further, it looks like the `DOUBLE(8,2)` we were using is both deprecated, and not reducing the storage size. So the path forward is to migrate to using either `DOUBLE` (8 bytes) or `FLOAT` (4 bytes) without a precision specification. I'd propose `FLOAT` as I don't think we need double precision for pp.

@smoogipoo can you envision any issues with this? For the range of pp values (generally 0~30,000 let's say), it should always give us better results than what we had.

**Comment by smoogipoo** [comment]
I don't foresee any problems with that.

**Comment by peppy** [comment]
I've started a migration for this on production. Will update relevant osu-web migrations once it's done and working okay.

**Comment by peppy** [comment]
This has been applied:

```sql
root@db-master:osu> select * from solo_scores_performance order by score_id desc limit 20;
+------------+---------------+
| score_id   | pp            |
+------------+---------------+
| 2403657002 |   0.0         |
| 2403657001 |   0.0         |
| 2403657000 |   0.0         |
| 2403656999 |   9.5913      |
| 2403656998 |   0.0         |
| 2403656997 |  15.5648      |
| 2403656996 |   1.18757     |
| 2403656994 |   0.785629    |
| 2403656993 |  11.0441      |
| 2403656992 |  19.8077      |
| 2403656991 |  13.2695      |
| 2403656990 |  33.9375      |
| 2403656989 |  42.7277      |
| 2403656988 |  20.9787      |
| 2403656987 |   8.05131     |
| 2403656986 |   2.17417e-09 |
| 2403656985 |   3.04858     |
| 2403656984 |   0.0         |
| 2403656983 | 227.255       |
| 2403656982 |  41.5243      |
+------------+---------------+
```

**Comment by smoogipoo** [comment]
How has this one been resolved? All I see above is that the table structure was altered, but how does that fix the original issue of the OP?

**Comment by bdach** [comment]
The thought process was that the added precision would tie-break the scores.

I'm not sure if it's feasible for two scores with different accuracy to return the same numerical pp value to the float precision in any of the rulesets, but if there is I guess this isn't quite fixed yet.

**Comment by peppy** [comment]
Based on discussion (see https://github.com/ppy/osu/issues/23914#issuecomment-1687823276), the requirement for action here was weak in the first place.

Best performance is literally a list of PP-sorted scores. I disagree with adding any fallback to this as from an infrastructure perspective it's hard to do. Adding extra precision is as far as I'm willing to go to fix this for now.
