### ISSUE TITLE
Mania hold notes are shortened when seeking back on editor timeline

### ISSUE THREAD

**Issue by CandyCrush14** [ppy/osu#23923]
### Type

Game behaviour

### Bug description

While editing hold notes start may get misaligned and shortened while seeking back through a song. This isn't as noticeable if you seeking while the song is paused only leading to it being misaligned by a few pixels, but if you seek back while the song is playing the notes may invisible or start way later.

### Screenshots or videos

https://github.com/ppy/osu/assets/103076033/6eb207b8-ab30-4c70-8d4b-0dd397f09ce0

### Version

2023.614.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11756962/database.log)
[input.log](https://github.com/ppy/osu/files/11756963/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11756964/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11756965/network.log)
[performance.log](https://github.com/ppy/osu/files/11756966/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11756967/runtime.log)

**Comment by CandyCrush14** [comment]
What I'm doing in the clip is scrolling back in the timeline. Also this happens in any mania map no just in this map.


[METAROOM - TRASH CLAN (CandyCrush14).zip](https://github.com/ppy/osu/files/11757346/METAROOM.-.TRASH.CLAN.CandyCrush14.zip)

**Comment by peppy** [comment]
Thanks, understood.
