### ISSUE TITLE
Local score not converted after 2023.614.1

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu#23931]
### Type

Game behaviour

### Bug description

After setting a local score on a map, I noticed it was ~200,000 points worse than my old best local (from before 2023.614.1) despite having a significantly better combo and accuracy. This seemed a bit extreme, so I checked the online leaderboard and it turned out that the local score was the exact same as the score of my best online play, meaning that the score had not been recalculated for the new scoring system.

### Screenshots or videos

Local leaderboard:
![image](https://github.com/ppy/osu/assets/100527514/e25dce88-ce07-4cbf-9ab1-3cd67b9c8180)

My online score (on global leaderboard):
![image](https://github.com/ppy/osu/assets/100527514/d45b93c5-8560-43b0-9511-65938d257729)

### Version

2023.614.1-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/11764351/updater.log)
[database.log](https://github.com/ppy/osu/files/11764352/database.log)
[input.log](https://github.com/ppy/osu/files/11764353/input.log)
[network.log](https://github.com/ppy/osu/files/11764354/network.log)
[performance.log](https://github.com/ppy/osu/files/11764355/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11764356/runtime.log)

Note: These are not the logs from my first run of this version, as I tried restarting osu to see if it would recalculate the scores.

**Comment by Non-Binary-Programmer** [comment]
To be clear: this is not a duplicate of #23929 or #23912. Neither of these plays are imported in any capacity.

**Comment by peppy** [comment]
Please upload your client.realm (zip if you need to)

**Comment by Non-Binary-Programmer** [comment]
[client.zip](https://github.com/ppy/osu/files/11765258/client.zip)

**Comment by peppy** [comment]
The score here is being round down to 399696 in the old standardised calculation and therefore not migrated:

![JetBrains Rider 2023-06-16 at 04 53 09](https://github.com/ppy/osu/assets/191335/7680caaf-c916-4cc1-b3fb-302afff06921)

![Safari 2023-06-16 at 04 55 53](https://github.com/ppy/osu/assets/191335/40ac4aa8-e896-45ab-b0ba-33fbbcaa8b8c)

This is probably affecting a good portion of scores, so I'll apply the migration a second time to catch any of these.
