### ISSUE TITLE
Wrong localization on countdown buttons in multiplayer room

### ISSUE THREAD

**Issue by SchiavoAnto** [ppy/osu#23941]
### Type

Other

### Bug description

The buttons used to start a match after some time are wrongly localized.
I attached a screenshot from my friend, as this bug happens only to him. He has both Windows and osu! in English.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/63348037/82d1bd24-b472-4de0-84f6-e84783b91230)

### Version

2023.614.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11771161/database.log)
[input.log](https://github.com/ppy/osu/files/11771162/input.log)
[network.log](https://github.com/ppy/osu/files/11771163/network.log)
[performance.log](https://github.com/ppy/osu/files/11771164/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11771165/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11771166/updater.log)

**Comment by bdach** [comment]
Button in question is not really properly localised yet. It only appears to be because of use of humanizer.

https://github.com/ppy/osu/blob/0ee9bcfea1ca3c4a39d221944c606abfb7b0779f/osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerCountdownButton.cs#L115
