### ISSUE TITLE
Score with lower accuracy gets more points

### ISSUE THREAD

**Issue by KevinLetsPlay** [ppy/osu#23944]
### Type

Other

### Bug description

The score with a lower accuracy has more points than the other score with higher accuracy.

### Screenshots or videos

![Screenshot (66)](https://github.com/ppy/osu/assets/136841895/42d0dbb7-a4ac-4385-8846-a220f080479e)
![Screenshot (68)](https://github.com/ppy/osu/assets/136841895/42d6619b-6f47-4e5c-9076-e1ef11982749)

### Version

2023.605.0

### Logs

Can you help why is it like this. I really can't explain it to myself

**Comment by peppy** [comment]
We just released a hotfix which may solve this. Please update and see if it looks better.

**Comment by peppy** [comment]
Going to close for now. Please let us know if this is still an issue.
