### ISSUE TITLE
Incorrect display of grade evaluations

### ISSUE THREAD

**Issue by wawdili** [ppy/osu#23955]
### Type

Game behaviour

### Bug description

![U$6LGD2R_8DR7DWB JU 2_D](https://github.com/ppy/osu/assets/87159802/9ffb2626-aba1-4c86-abbc-be689f5b44f6)
The score that did not have "Hidden" or "FlashLight" mod enabled is still displayed as a silver SS in the figure, and it should be a yellow SS. (Global second in the figure)
He is still on the leaderboard, maybe you can take a look.

### Version

2023.617.0-lazer

### Logs

[1.log](https://github.com/ppy/osu/files/11780788/1.log)

**Comment by peppy** [comment]
Leaderboards will be reset soon, which will fix this glitch.
