### ISSUE TITLE
Auto cannot keep up with extreme hit-object density

### ISSUE THREAD

**Issue by Poyo-SSB** [ppy/osu#2395]
The best way to see this in action is with [KAEDE - Ocelot [EX EX]](https://osu.ppy.sh/beatmapsets/660630/#osu/1398809), mapped by Hollow Wings. The map has extremely high-velocity sliders with numerous repeats. lazer misses several sliders, while stable always gets an SS.

One such slider is at 01:18:843 in the map (per stable's editor).

![a swift lad](https://user-images.githubusercontent.com/1782081/38701150-01f48d48-3e52-11e8-86f6-bb38cd65190a.png)

This is the (relevant) data of the slider in question:

```javascript
{
    "type": 2,
    "velocity": 5.1624998593330353,
    // ...
    "curve_type": 1,
    "distance": 109.374997019768,
    // ...
    "repeat_count": 11,
    "end_time": 79075.2372881356,
    "duration": 254.23728813559865,
    "start_time": 78821.0,
    // ...
}
```

11 segments across ~254ms is approximately 23 milliseconds to complete each segment. Auto is designed to follow sliders exactly even when impractical for humans, and lazer's specific method for this yields the misses observed; when following sliders, it creates a frame in temporal increments of the frame delay value.

https://github.com/ppy/osu/blob/ea24006a6618664baac89abb469f947cf23101ce/osu.Game.Rulesets.Osu/Replays/OsuAutoGeneratorBase.cs#L47-L48

Without mods, this code makes the frame delay ~16.66, which is is not enough to accurately follow the slider. Slowing down the auto replay to 0.05x speed reveals this clearly, with the cursor discretely jumping between positions on the slider.

**Comment by peppy** [comment]
Low priority compatibility-with-intensive-maps issue.

**Comment by Poyo-SSB** [comment]
This appears to be resolved on latest master. Auto successfully hits everything it should reasonably be able to, matching stable.

**Comment by peppy** [comment]
Thanks!
