### ISSUE TITLE
Taiko hitsound volume behavior in lazer is inconsistent with stable

### ISSUE THREAD

**Issue by hongaaronc** [ppy/osu#23963]
### Type

Game behaviour

### Bug description

The way that hitsound volumes are applied in taiko for Lazer is different from the behavior in Stable.

In Lazer, hitsound volume is determined by the volume of the most nearby HitObject, similar to how it works in other game modes.
* [Source code reference](https://github.com/ppy/osu/blob/f8b94ed033f639a77ad1d9757cc987c8819d1ad1/osu.Game.Rulesets.Taiko/UI/DrumSampleTriggerSource.cs#L21)

However, in Stable, hitsound volume is completely agnostic to HitObjects, and is purely based the currently active timing point's volume.

This is relevant particularly for spinners and sliders in Taiko, since often Taiko maps will use multiple timing points throughout the duration of a spinner or slider to create a crescendo/decrescendo effect.

This also results in a tendency for any stray inputs after mashing a quiet spinner in Taiko to be very noticibly louder (shown in the videos below).

And finally, this effects the usecase where the player is noodling around during inactive play, like a break section, and the expected hit volumes are not properly applied.

### Screenshots or videos
* [Behavior for a spinner section on Lazer](https://github.com/ppy/osu/assets/5133530/ca7fa440-e5c5-4641-aae8-39d8cf923598)

* [Behavior for the same spinner section on Stable](https://github.com/ppy/osu/assets/5133530/b220b00c-b874-46c3-a467-79fb5c927789)

The first video shows the behavior when mashing a spinner in Lazer, and the second video shows the same section in Stable. 

Note the hitsound volume as soon as the spinner is completed and becomes inactive.

[Link to beatmap shown in video for reference](https://osu.ppy.sh/beatmapsets/1718727)

### Version

2023.605.0-lazer

### Logs

N/A - code is running as expected, but behavior is fundamentally flawed.

**Comment by peppy** [comment]
Not sure how this could be fixed. I guess we'd need special behaviour in swells to handle it.

**Comment by peppy** [comment]
Actually, assuming volume is already being applied to nested objects (you'd hope so) this may be enough to work. Haven't tested:

```diff
diff --git a/osu.Game.Rulesets.Taiko/UI/DrumSampleTriggerSource.cs b/osu.Game.Rulesets.Taiko/UI/DrumSampleTriggerSource.cs
index 92f2b74568..8d611fd2df 100644
--- a/osu.Game.Rulesets.Taiko/UI/DrumSampleTriggerSource.cs
+++ b/osu.Game.Rulesets.Taiko/UI/DrumSampleTriggerSource.cs
@@ -18,7 +18,14 @@ public DrumSampleTriggerSource(HitObjectContainer hitObjectContainer)
 
         public void Play(HitType hitType)
         {
-            var hitSample = GetMostValidObject()?.Samples?.FirstOrDefault(o => o.Name == HitSampleInfo.HIT_NORMAL);
+            var mostValidObject = GetMostValidObject();
+
+            if (mostValidObject == null)
+                return;
+
+            var hitSample =
+                mostValidObject.NestedHitObjects.LastOrDefault(o => o.StartTime > Time.Current)?.Samples.FirstOrDefault(o => o.Name == HitSampleInfo.HIT_NORMAL)
+                ?? mostValidObject.Samples?.FirstOrDefault(o => o.Name == HitSampleInfo.HIT_NORMAL);
 
             if (hitSample == null)
                 return;

```

**Comment by hongaaronc** [comment]
> Actually, assuming volume is already being applied to nested objects (you'd hope so) this may be enough to work. Haven't tested:
> 
> ```diff
> diff --git a/osu.Game.Rulesets.Taiko/UI/DrumSampleTriggerSource.cs b/osu.Game.Rulesets.Taiko/UI/DrumSampleTriggerSource.cs
> index 92f2b74568..8d611fd2df 100644
> --- a/osu.Game.Rulesets.Taiko/UI/DrumSampleTriggerSource.cs
> +++ b/osu.Game.Rulesets.Taiko/UI/DrumSampleTriggerSource.cs
> @@ -18,7 +18,14 @@ public DrumSampleTriggerSource(HitObjectContainer hitObjectContainer)
>  
>          public void Play(HitType hitType)
>          {
> -            var hitSample = GetMostValidObject()?.Samples?.FirstOrDefault(o => o.Name == HitSampleInfo.HIT_NORMAL);
> +            var mostValidObject = GetMostValidObject();
> +
> +            if (mostValidObject == null)
> +                return;
> +
> +            var hitSample =
> +                mostValidObject.NestedHitObjects.LastOrDefault(o => o.StartTime > Time.Current)?.Samples.FirstOrDefault(o => o.Name == HitSampleInfo.HIT_NORMAL)
> +                ?? mostValidObject.Samples?.FirstOrDefault(o => o.Name == HitSampleInfo.HIT_NORMAL);
>  
>              if (hitSample == null)
>                  return;
> ```

So there's multiple behaviors that are missing in Lazer, in this issue:
1. Not being able to handle multiple volume levels for a single object - which your suggestion might address
2. When a spinner is completed early, it becomes inactive - which I believe would still be an issue even with your suggestion, since [GetMostValidObject() only checks AliveObjects](https://github.com/ppy/osu/blob/f8b94ed033f639a77ad1d9757cc987c8819d1ad1/osu.Game/Rulesets/UI/GameplaySampleTriggerSource.cs#L71), in which case it will hit that `null` case

I think fixing this might be a bit more involved. Here's what I'm thinking:
* HitObjects shouldn't be used in the implementation for volume in Taiko at all, only timing points
* Whenever a drum sound is played we just want to play it at the volume of the most recently active timing point
* Since there can be a lot of inputs in a short time frame, I think it wouldn't be performant enough to look it up at the timing of playing the sound. The volume should be already known beforehand

So I'd go for an approach something like this (I'll be making a bunch of assumptions since I'm not familiar the codebase):
1. Create a singleton "current hit volume" variable
2. After the map is loaded, when first starting it (at the `00:00:000` mark):
  a. For each timing point, start a coroutine with a delay correspondent to it's timestamp which updates the "current hit volume" singleton
3. When `DrumSampleTriggerSource.Play(..)` is called, just get the volume from that "current hit volume" singleton

Not sure how realistic that sounds. What do you think?

**Comment by hongaaronc** [comment]
> We've gone through great pains to move timing points to hit objects across all rulesets. I'm not sure we're going to double back on all that now.

I see, do you have any links to some of the discussion about that, or was that internal? I'm curious to understand what the main benefits are, to see if I can think of any solution that retains them.

Like would it be reasonable to just make a new subclass of `HitObject` for these volume changes?

> Something that _may_ fill the gap in functionality is allowing some sort of volume curve to be placed on objects, combined with altering the behaviour of not considering finished objects for determining most valid object.

That could get closer to the Stable behavior. However there still will be edge cases (but they might be too niche to really care about).

For example in [this map](https://osu.ppy.sh/beatmapsets/1956955) at [`02:46:660`-`02:50:122`](osu://edit/02:46:660): the expected hitsound volume in Stable during this break should be `30%`, since there are 2 volume changes between consecutive hit objects. But this solution would not be able to handle that case.

**Comment by bdach** [comment]
> I see, do you have any links to some of the discussion about that, or was that internal?

See: https://github.com/ppy/osu/pull/10416, https://github.com/ppy/osu/pull/14578, https://github.com/ppy/osu/pull/23308.

**Comment by peppy** [comment]
Okay, so nested objects are already handled. The linked beatmap didn't even have a "crescendo" applied soo.

The remaining issues can easily be fixed with a change to what is considered `GetMostValidObject`. We should probably handle similar to how I recall BMS simulators doing this: only taking on the sample of a hitobject if it is within a good range. Right now we're simply taking the next immediately, which makes little sense.

I'll look to make this change as it should be pretty straightforward.

**Comment by hongaaronc** [comment]
> Okay, so nested objects are already handled. The linked beatmap didn't even have a "crescendo" applied soo.

Ah ok, that's good. And sorry for the confusion with the video - meant to show the issue with the HitObject switching to inactive.

> The remaining issues can easily be fixed with a change to what is considered `GetMostValidObject`

That still won't solve the [second case I mentioned](https://github.com/ppy/osu/issues/23963#issuecomment-1597883137), because no hitobjects are affected by the volume change during the break. However the player can still make sounds during it.
> @hongaaronc: For example in [this ranked beatmap](https://osu.ppy.sh/beatmapsets/1956955) at `02:46:660`-`02:50:122`: the expected hitsound volume in Stable during this break should be 30%.

It is a very niche case. But it does seem like a deliberate choice by the mapper to make the hitsounds during the break work that way.

> I'll look to make this change as it should be pretty straightforward.

In any case, this change you suggested would be an improvement even if it doesn't solve _everything_. So might as well do it, if it's not too much trouble.

**Comment by peppy** [comment]
> That still won't solve the https://github.com/ppy/osu/issues/23963#issuecomment-1597883137, because no hitobjects are affected by the volume change during the break. However the player can still make sounds during it.

This is unsupported and will not be supported going forward. Sorry.

**Comment by hongaaronc** [comment]
> This is unsupported and will not be supported going forward. Sorry.

No worries - that seems perfectly reasonable to me. Just wanted to make sure we were clear that we were settling on it as the new behavior. 👍
