### ISSUE TITLE
Number format/notation conversion error

### ISSUE THREAD

**Issue by skitou** [ppy/osu#23988]
### Type

Other

### Bug description

Scores and numbers in general have format problems when the language of the game isn't English.

For example, the number "123,456,789" is represented as "123?456?789" instead of "123 456 789".

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/38993289/b3e620b4-3c10-4708-81ac-56d081eca796)
![image](https://github.com/ppy/osu/assets/38993289/46d07b53-7413-43fb-8ee3-00f2f7433bad)

### Version

2023.621.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11818135/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11818136/updater.log)
[database.log](https://github.com/ppy/osu/files/11818137/database.log)
[input.log](https://github.com/ppy/osu/files/11818139/input.log)
[network.log](https://github.com/ppy/osu/files/11818140/network.log)
[performance.log](https://github.com/ppy/osu/files/11818142/performance.log)

**Comment by bdach** [comment]
#15135
