### ISSUE TITLE
Nupkg file blocking updates

### ISSUE THREAD

**Issue by wawdili** [ppy/osu#23997]
### Type

Other

### Bug description

If the update was not completed last time, the nupkg file left in C:\Users\xxx\AppData\Local\osulazer\packages may cause the next update to fail, as mentioned in the video.

### Screenshots or videos

https://github.com/ppy/osu/assets/87159802/8cef922f-8d1d-41b3-b594-2170dbe86b49

### Version

2023.617.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11828705/runtime.log)

**Comment by peppy** [comment]
Please upload all logs after reproducing again.

**Comment by wawdili** [comment]
> Please upload all logs after reproducing again.

Sometimes it can't be replicated, I think it may not be the problem, but sometimes it can be replicated, which is strange. Additionally, my osulazer got stuck during installation and was unable to complete the update, which is why I have been able to try updating multiple times.
[runtime.log](https://github.com/ppy/osu/files/11849116/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11849118/updater.log)
[database.log](https://github.com/ppy/osu/files/11849119/database.log)
[network.log](https://github.com/ppy/osu/files/11849120/network.log)
[performance.log](https://github.com/ppy/osu/files/11849121/performance.log)

**Comment by wawdili** [comment]
![L4X_$C8C{4}$(}~}(IF8_F1](https://github.com/ppy/osu/assets/87159802/3c0a493b-d144-4b6d-a56c-5c66d867803c)
What?

**Comment by peppy** [comment]
When it gets in a bad state, could you zip and upload a copy of the files in that folder?

**Comment by wawdili** [comment]
> When it gets in a bad state, could you zip and upload a copy of the files in that folder?

Ah? I think I need to reinstall the lazer, it seems to have too many problems. As for the file, osulazer is currently occupying it and cannot read it, but updates to osulazer are stagnant.


well, I closed the game, here are its files. (Note that packages(2). zip is the second sub volume of packages.zip)
[packages(2).zip](https://github.com/ppy/osu/files/11881588/packages.2.zip)
[packages.zip](https://github.com/ppy/osu/files/11881590/packages.zip)
![9H0B({KJIHZ3R$AR5S 201H](https://github.com/ppy/osu/assets/87159802/8ccfa987-f8c9-4f95-987c-d8d7e65399ee)
