### ISSUE TITLE
Using metal API makes the image torn, OpenGL does not

### ISSUE THREAD

**Issue by Dreamail** [ppy/osu#23995]
### Type

Game behaviour

### Bug description

Im play in macOS 14 with Apple Silicon M1
When I using Metal API without VSync enabled, the  bottom part of image will be torn, but OpenGL with any fps limit doesn't
I have try VSync and problem disappear, but latency show in right-bottom was higher.

### Version

2023.621.0

### Logs

[performance.log](https://github.com/ppy/osu/files/11827445/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11827447/runtime.log)

**Comment by peppy** [comment]
That's not latency, but frame time.

This is expected behaviour. Your best option is vsync on metal for now.
