### ISSUE TITLE
Osu!Catch cursor showing up for players dashing with the mouse when the cursor mouve outside of the fruits "spawn zone"

### ISSUE THREAD

**Issue by kitsumed** [ppy/osu#23996]
### Type

Cosmetic

### Bug description

Hi, in the current and old releases of osu!lazer, one problem mainly prevented me from playing a lot on the new client. From my current understanding of the game, when you play on osu!catch your cursor hide itself as long as you don't move it. However, the cursor only do so when inside of the "spawn zone" of the fruits. If, while playing, you accidentally move your cursor outside of this famous zone, he will start to appear when the player clicks to dash, then becomes invisible again. To put it simply, show>hidden>show>hidden. It's not a game-breaking bug, however, it's personally something that distracts me when I play and the current version of osu! doesn't behave like that.

During my searches, I came across similar topics, although they where not exactly the same as me from my understanding : https://github.com/ppy/osu/issues/21644
https://github.com/ppy/osu/discussions/21645

### Screenshots or videos

In this video, the cursor, in the redbox, is outside of the "spawn zone" and show>hide itself each time I dash with my mouse button.

https://github.com/ppy/osu/assets/45147847/3bebd4e1-1055-42a7-807c-9e91c13b943f

Yes, I dash with the mouse 👌

*Here's an additional video in which I deliberately reproduced the "bug" at the start of the game by moving my cursor on the side. This one also less feel like im moving my cursor. Because yes, I know that moving the cursor will cause it to show up, however I am not in the current case.

https://github.com/ppy/osu/assets/45147847/300dbd2b-464b-4973-9905-308c2ae99d9f

### Version

Lazer 2023.621.0

### Logs

N/A
```[tasklist]
### Tasks
```

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/20877
