### ISSUE TITLE
Unable to open maps

### ISSUE THREAD

**Issue by r0xANDt0l** [ppy/osu#23990]
### Type

Game behaviour

### Bug description

I can't open any maps in any gamemode, Only thing I can imagine that could help is that it's stored on an hdd, and the amount of maps I have 

### Screenshots or videos

https://github.com/ppy/osu/assets/41841903/f2d60433-0008-47b6-83e0-ba17b2798290

### Version

2023.0621

### Logs

[network.log](https://github.com/ppy/osu/files/11819827/network.log)
[performance.log](https://github.com/ppy/osu/files/11819828/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11819829/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11819830/updater.log)
[database.log](https://github.com/ppy/osu/files/11819831/database.log)
[input.log](https://github.com/ppy/osu/files/11819832/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11819833/legacy-ipc.log)

**Comment by r0xANDt0l** [comment]
wait, restarting the game fixed it lol, not sure if I should close it so I'll just comment

**Comment by peppy** [comment]
Hard to say what happened here, the logs don't seem to match with the session in your video so I can't attain much from them.

My best guess would be something the custom ruleset you've loaded did, but very hard to say.
