### ISSUE TITLE
How to Build the Source code?

### ISSUE THREAD

**Issue by cscp** [ppy/osu#240]
i cannot build because there are 1266 Errors caused of osu.Framework it says it does not exist. how to build it??

**Comment by Aerath** [comment]
You probably forgot to init/update git submodules. If there is no files in osu-framework, you must run `git submodule init` and `git submodule update`.

**Comment by cscp** [comment]
and how to do this on windows 7??

**Comment by FayneAldan** [comment]
If you don't know how to do this, you probably shouldn't try to do this.
