### ISSUE TITLE
Catch editor - Moving an object with the mouse creates additional hitlighting

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu#24008]
### Type

Cosmetic

### Bug description

Moving an object with the mouse (either position or on the timeline) will increase the number of hitlightings in the editor.
Moving the object with the keyboard (eg nudge forward/backward, ctrl-left/right) will not cause this bug
Low priority since it's just visual, goes away pretty quickly and doesn't bother much.

### Screenshots or videos

https://github.com/ppy/osu/assets/30382015/6d5c4447-1187-41d0-9105-8683cc17bed6

### Version

2023.621.0

### Logs

[performance.log](https://github.com/ppy/osu/files/11844224/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11844225/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11844226/updater.log)
[database.log](https://github.com/ppy/osu/files/11844227/database.log)
[input.log](https://github.com/ppy/osu/files/11844228/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11844229/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11844230/network.log)

**Comment by Xinnoh** [comment]
Moving slider nodes also causes this issue but at a significantly faster rate
There must be a hitlighting on the catcher for this bug to occur
(both showcased below)

https://github.com/ppy/osu/assets/30382015/d507f5bc-7c85-43f1-82ad-d1a1e9b8a3f5

**Comment by peppy** [comment]
Please just include this in https://github.com/ppy/osu/issues/24007, it's basically the same thing.

**Comment by Xinnoh** [comment]
sure, thought they were different but will bundle
