### ISSUE TITLE
osu!catch Floating Fruits mod flips touch controls

### ISSUE THREAD

**Issue by Kori3** [ppy/osu#24000]
### Type

Game behaviour

### Bug description

very small thing and pretty self explanatory
idk if this is intended or not but its annoying

### Screenshots or videos

https://github.com/ppy/osu/assets/70714793/e05cd2aa-3203-4112-a832-91b31fad7e43

https://github.com/ppy/osu/assets/70714793/0b5945ad-8666-456c-8d43-a7727eac9c8e

### Version

2023.621.0

### Logs

no

**Comment by soopax** [comment]
Yes, I think that's wrong. (Issue number 24000 🤔)
