### ISSUE TITLE
Toggling beatmap hit sounds can cause a deadlock in bindable logic

### ISSUE THREAD

**Issue by RBQcat** [ppy/osu#24013]
### Type

Crash to desktop

### Bug description

Adjusting the beatmap hitsound while playing this [beatmaps](https://osu.ppy.sh/beatmapsets/332673#mania/736490) will cause the game to freeze

### Version

2023.621

### Logs

[runtime.log](https://github.com/ppy/osu/files/11849126/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11849128/performance.log)
[database.log](https://github.com/ppy/osu/files/11849129/database.log)
[network.log](https://github.com/ppy/osu/files/11849130/network.log)

**Comment by peppy** [comment]
Should be pretty obvious why. Can you confirm it does recover after freezing (aka reloading the hitsounds)?

**Comment by RBQcat** [comment]
I waited about a minute and the game didn't continue.  The game uses almost no CPU.  But I created a dump file, do you need it?

**Comment by peppy** [comment]
Thanks for the extra information. I have a very strong feeling I know how this can happen. As in it's definitely [this](https://discord.com/channels/188630481301012481/188630652340404224/1116330022190456884). I was only able to repro under very rare circumstances, but the beatmap you linked definitely makes this easier to warrant escalating.

![JetBrains_Rider_2023-06-08_at_11 37 13](https://github.com/ppy/osu/assets/191335/ed139e21-8444-4a5c-9cce-80494b058f36)
![JetBrains_Rider_2023-06-08_at_11 38 18](https://github.com/ppy/osu/assets/191335/6370f20f-ba2e-408f-b044-e4a0aa744573)
![JetBrains_Rider_2023-06-08_at_11 38 47](https://github.com/ppy/osu/assets/191335/4e498d45-837b-4729-b0f1-307a10a08aab)


I'll bump this in priority and put it on my own high prio list if no one beats me.
