### ISSUE TITLE
Metal 60FPS Cap

### ISSUE THREAD

**Issue by SherlockWh0** [ppy/osu#24024]
### Type

Performance

### Bug description

Basically, when I use the metal renderer, osu! is capped at 60fps, and occasionally goes to 55. (even if my in-game cap is set higher.) The game still runs smooth, just at a low fps.
But when I tried OpenGL, osu! runs at ~500fps in the menus and ~300 in osu!taiko at basically unlimited. This is weird, as usually macOS OpenGL support is not great, but it's somehow better than metal.

### Screenshots or videos

<img width="1440" alt="hifpsogl" src="https://github.com/ppy/osu/assets/107404453/f6d919d8-9f25-4d10-893f-62dbd2d084a2">
<img width="1440" alt="lofpsmetal" src="https://github.com/ppy/osu/assets/107404453/31874fbe-76d9-455d-a6db-059165ee089f">

### Version

2023.621.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11855541/database.log)
[input.log](https://github.com/ppy/osu/files/11855542/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11855543/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11855544/network.log)
[performance-draw.log](https://github.com/ppy/osu/files/11855545/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/11855546/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/11855547/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11855548/runtime.log)

**Comment by integerrr** [comment]
Because of [this](https://github.com/ppy/osu-framework/pull/5821)
From changelog:
> This pulls in veldrid changes by smoogipoo which allow near-perfect frame timings on macOS. Basically, the game can now run at refresh-rate-draw-fps and have hardware-cursor-like latency. Even when running windowed.
>
> It's the new lowest-latency osu! experience by far. We hope to bring similar behaviour to windows (using things like GSync) in the near future.
>
> **Note that as a result, the draw thread will always be locked to your refresh rate, regardless of your chosen frame limiter setting.**

You even said it yourself how the game still runs smoothly

**Comment by SherlockWh0** [comment]
Will this be changed later, or is it permanent?

**Comment by peppy** [comment]
Welcome to the real world neo. Where more frames does not equal better (in any way).

**Comment by Eeveelution** [comment]
i know this has been closed but something i'd like to add is that on metal no matter what you set the frame limiter to it always remains at vsync, which seems to lead to consistent stuttering most noticable for me in taiko. using the veldrid opengl renderer where the frame limiter works as expected yields a way smoother gameplay experience. setting opengl to vsync shows similar stuttering as experienced in metal which leads me to believe that implementing these frame limiters that go beyond vsync would be a nice addition.

**Comment by peppy** [comment]
To make taiko smooth, please set vsync to *on*. In the future this will be automatic (right now the frame limiters don't really mean what they say on macOS because we're using newer APIs for lower latency).

Vsync on macOS with metal displaylink sync is already as low as 1 frame of latency. And especially in taiko this should be very very playable.

If you still get stutters on metal when vsync is on, also try setting threading to single thread.

**Comment by Eeveelution** [comment]
I tried all of the above and it notes still weren't moving smoothly...

**Comment by Eeveelution** [comment]
https://streamable.com/qax9sj
https://streamable.com/mi7ni7
https://streamable.com/1dblhi

**Comment by peppy** [comment]
It might be something else running on your PC. macOS is very sensitive in this way. For instance, if I run ubersicht it will cause system-wide frame drops every 1 second.

**Comment by Eeveelution** [comment]
Then why would it disappear on OpenGL, the OpenGL test was even worse off since it had Discord running in the background, whereas when I tested Metal under your perfect conditions I closed everything and it still ran poorly

**Comment by peppy** [comment]
not sure sorry. if gl works better then please use it for now.

**Comment by Minorsonek** [comment]
I second this, I agree new changes feels great on something like a built-in macbook screen, promotion makes it 120fps and it feels quite excelent. But as soon as you change to your external 60hz monitor, 60fps for this game is simply not enough and it stutters so much that OpenGL really feels like a better option now. Can we have "old" Metal setting back?
