### ISSUE TITLE
Windows key don't wor as an input

### ISSUE THREAD

**Issue by TopGonGit** [ppy/osu#24029]
### Type

Game behaviour

### Bug description

So I have the "windows" and "alt" key remapped with Microsoft Power Toys. "windows"="x" and "alt"="c".
The alt key works perfectly fine in game, but the windows key doesn't, even though that in keyboard blinding it takes me the "windows" key input as an "x", but for some reason in while playing it seems that the input never exists.

### Version

Lazer 2023.621.0

### Logs

[performance.log](https://github.com/ppy/osu/files/11858030/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11858031/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11858032/updater.log)
[database.log](https://github.com/ppy/osu/files/11858033/database.log)
[input.log](https://github.com/ppy/osu/files/11858034/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11858035/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11858036/network.log)

**Comment by monochrome22** [comment]
Untick "Disable windows key during gameplay" in settings.

**Comment by TopGonGit** [comment]
> Untoggle "Disable windows key during gameplay" in settings.

Oh, I see! Thank you so much.
