### ISSUE TITLE
Error in editor while attempting to save

### ISSUE THREAD

**Issue by wawdili** [ppy/osu#24034]
### Type

Game behaviour

### Bug description

An error occurred while saving the beatmap, and the saved items were subsequently cleared.
Can it still recover?

If there is no guarantee that player's files will be lost due to bugs, please always backup player's files.

### Screenshots or videos

![S}RC}GQQR716{X)SX_73L 6](https://github.com/ppy/osu/assets/87159802/01f4d359-1b28-427f-800d-107cd5474e4d)
:(

### Version

2023.617.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11859659/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11859660/updater.log)
[database.log](https://github.com/ppy/osu/files/11859661/database.log)
[network.log](https://github.com/ppy/osu/files/11859662/network.log)
[performance.log](https://github.com/ppy/osu/files/11859663/performance.log)

**Comment by peppy** [comment]
The file should actually still be on disk in this case, if you want to recover it (you will have to search in the `files` subfolder by date modified to find it though).

**Comment by whatwillweget** [comment]
Does **TUYU - Under Kids [Insane]** initially have objects?

**Comment by wawdili** [comment]
> Does **TUYU - Under Kids [Insane]** initially have objects?

yes

**Comment by wawdili** [comment]
> The file should actually still be on disk in this case, if you want to recover it (you will have to search in the subfolder by date modified to find it though).`files`

Um, I have remade it.

**Comment by peppy** [comment]
@wawdili in your screenshot, I can see multiple errors. is this because you triggered a save multiple times manually?

**Comment by wawdili** [comment]
> @wawdili in your screenshot, I can see multiple errors. is this because you triggered a save multiple times manually?

yes

**Comment by bdach** [comment]
@wawdili prior to the errors shown in these screenshot, did you delete any difficulties from the set being edited through the "Delete difficulty" option in editor?

**Comment by wawdili** [comment]
> @wawdili prior to the errors shown in these screenshot, did you delete any difficulties from the set being edited through the "Delete difficulty" option in editor?

I don't think I did that.
