### ISSUE TITLE
Animated taikocircleoverlays don't animate to the beat

### ISSUE THREAD

**Issue by toadsworth-jr** [ppy/osu#24049]
### Type

Cosmetic

### Bug description

Animating both `taikohitcircleoverlay` and `taikobigcircleoverlay` will cause them to animate at the beat on stable. This BPM-dependent animation doesn't seem to line up on lazer, sometimes being offset by a 100ms.

### Screenshots or videos

https://github.com/ppy/osu/assets/75596775/b24df633-2298-45da-a5b6-8566ec86353b

https://github.com/ppy/osu/assets/75596775/36af8c43-ee46-4358-be3c-cd0a94992789

### Version

2023.621.0

### Logs

[database.log](https://github.com/ppy/osu/files/11871067/database.log)
[network.log](https://github.com/ppy/osu/files/11871068/network.log)
[performance.log](https://github.com/ppy/osu/files/11871069/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11871070/runtime.log)

**Comment by peppy** [comment]
When testing this on stable, it seems the animation starts arbitrarily at some point in the beatmap. Do you know anything about this?

**Comment by peppy** [comment]
Okay apparently it's based on combo. No idea where that logic lives in stable.
