### ISSUE TITLE
Storyboards loaded at the main menu persist through song select

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#24044]
### Type

Performance

### Bug description

If the in-game background source is set to `Beatmap (with storyboard / video)`, the loaded storyboard will remain loaded regardless of if another screen is entered (songselect, gameplay, etc), until the main menu is resumed.

If the loaded storyboard happens to be particularly huge, such as https://osu.ppy.sh/beatmapsets/470977#osu/1006822, then this could mean an extra 1+GB of gen2 pressure that does not need to exist.

### Screenshots or videos

https://github.com/ppy/osu/assets/1329837/b0901821-a912-4942-af34-383d91edb73b

### Version

2023.621.0

### Logs

-

**Comment by peppy** [comment]
Yep, ran into this a few times.
