### ISSUE TITLE
Osu crashes.

### ISSUE THREAD

**Issue by dominik567765** [ppy/osu#2404]
Hello! 

The game crashes during startup.
Here are the logs:

14.04.2018 18:22:56: fatal error:
14.04.2018 18:22:56: osu.Game.Database.MigrationFailedException: sqlite-net migration failed
14.04.2018 18:22:56: в osu.Game.Database.OsuDbContext.Migrate()
14.04.2018 18:22:56: в osu.Game.OsuGameBase.runMigrations()
14.04.2018 18:22:56: в osu.Game.OsuGameBase.load()
14.04.2018 18:22:56: 
14.04.2018 18:22:56:

**Comment by peppy** [comment]
Can you include database.log?

**Comment by dominik567765** [comment]
16.04.2018 17:45:17: ----------------------------------------------------------
16.04.2018 17:45:17: Database Log for User
16.04.2018 17:45:17: osu version unknown
16.04.2018 17:45:17: Running on Microsoft Windows NT 6.2.9200.0, 4 cores
16.04.2018 17:45:17: ----------------------------------------------------------
16.04.2018 17:45:17: Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='10']
16.04.2018 17:45:17: CREATE TABLE "BeatmapDifficulty" (
16.04.2018 17:45:17: "ID" INTEGER NOT NULL CONSTRAINT "PK_BeatmapDifficulty" PRIMARY KEY AUTOINCREMENT,
16.04.2018 17:45:17: "ApproachRate" REAL NOT NULL,
16.04.2018 17:45:17: "CircleSize" REAL NOT NULL,
16.04.2018 17:45:17: "DrainRate" REAL NOT NULL,
16.04.2018 17:45:17: "OverallDifficulty" REAL NOT NULL,
16.04.2018 17:45:17: "SliderMultiplier" REAL NOT NULL,
16.04.2018 17:45:17: "SliderTickRate" REAL NOT NULL
16.04.2018 17:45:17: );
16.04.2018 17:45:17: Migration failed! We'll be starting with a fresh database.
16.04.2018 17:45:17: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "BeatmapDifficulty" already exists'.
16.04.2018 17:45:17: в Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
16.04.2018 17:45:17: в Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
16.04.2018 17:45:17: в Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
16.04.2018 17:45:17: в Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
16.04.2018 17:45:17: в Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
16.04.2018 17:45:17: в Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
16.04.2018 17:45:17: в Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
16.04.2018 17:45:17: в osu.Game.Database.OsuDbContext.Migrate()
16.04.2018 17:45:17: Database purged successfully.
16.04.2018 17:45:17: Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='10']
16.04.2018 17:45:17: CREATE TABLE "BeatmapDifficulty" (
16.04.2018 17:45:17: "ID" INTEGER NOT NULL CONSTRAINT "PK_BeatmapDifficulty" PRIMARY KEY AUTOINCREMENT,
16.04.2018 17:45:17: "ApproachRate" REAL NOT NULL,
16.04.2018 17:45:17: "CircleSize" REAL NOT NULL,
16.04.2018 17:45:17: "DrainRate" REAL NOT NULL,
16.04.2018 17:45:17: "OverallDifficulty" REAL NOT NULL,
16.04.2018 17:45:17: "SliderMultiplier" REAL NOT NULL,
16.04.2018 17:45:17: "SliderTickRate" REAL NOT NULL
16.04.2018 17:45:17: );

**Comment by peppy** [comment]
Is that the end of the log?

**Comment by peppy** [comment]
Also if possible could you please attach your `client.db` in the lazer data directory?

**Comment by dominik567765** [comment]
Yes, that was the end of the log.
The forum doesn't let me attach the client.db file. It says that it is not supported.
