### ISSUE TITLE
Song select carousel doesn't recognize dragging when too far away

### ISSUE THREAD

**Issue by ZWORX52** [ppy/osu#24055]
### Type

Cosmetic

### Bug description

I found this by trying to right-click drag the song select menu. I noticed that by trying to avoid right-clicking the currently selected song, my mouse click just wouldn't register. After poking around, I found that if your click is horizontally correctly positioned, but vertically is between the left edge of the search bar and the info on the left of the screen (a location where you'd expect dragging to work), then the carousel doesn't recognize dragging inputs.

### Screenshots or videos

![affected_area](https://github.com/ppy/osu/assets/66217856/3f525b18-0fa5-4f1f-8633-9710348ebd7c)

### Version

2023.621.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11875349/database.log)
[input.log](https://github.com/ppy/osu/files/11875350/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11875351/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11875352/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/11875353/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11875354/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11875355/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11875356/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/11875357/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11875358/runtime.log)

**Comment by peppy** [comment]
Drag closer to the carousel?
