### ISSUE TITLE
Random crash to desktop when selecting song

### ISSUE THREAD

**Issue by Trung0246** [ppy/osu#24054]
### Type

Crash to desktop

### Bug description

I played the game normally when suddenly the game crashed. Have no idea what caused this or why does this crash exist. For now I seemingly cannot replicate this since the crash is random. The only thing I have is the log as the crash happened. Deadlock issue?

Windows 11

### Version

2023.621.0

### Logs

[database.log](https://github.com/ppy/osu/files/11874925/database.log)
[input.log](https://github.com/ppy/osu/files/11874926/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11874927/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11874928/network.log)
[performance.log](https://github.com/ppy/osu/files/11874929/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11874930/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11874931/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11874932/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11874933/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11874934/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11874935/updater.log)

**Comment by peppy** [comment]
No xm rash in logs, so likely driver related. You can check windows event log for confirmation.
