### ISSUE TITLE
Reverse arrows on legacy skins with no sliderend circle still turn black

### ISSUE THREAD

**Issue by rozukke** [ppy/osu#24074]
### Type

Cosmetic

### Bug description

This seems to be specifically a problem with legacy skins that do not replace the default reverse arrow. Results in something quite difficult to read. 

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/73006620/1e39b26e-c605-4951-a92f-26db7721b11c)

### Version

2023.621.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11898081/runtime.log)

**Comment by peppy** [comment]
Please attach the skin.

**Comment by rozukke** [comment]
[Uploading problemskin.zip…]()
This is an example of a problem skin, though any skin with a transparent sliderend and default reversearrow will do the trick.

**Comment by rozukke** [comment]
[problemskintiny.zip](https://github.com/ppy/osu/files/11903785/problemskintiny.zip)
Here's an example of a skin that exhibits the behaviour, thought it is very stripped down so that the github upload wouldn't take forever.

**Comment by peppy** [comment]
The same thing happens on stable:

![Parallels Desktop 2023-06-30 at 05 41 34](https://github.com/ppy/osu/assets/191335/97ded4f3-bae6-416d-b139-4afd92830f1a)

Closing as "behaves as expected". Fix your skin instead, please. This could be as simple as copying the default skin's reverse arrow sprite into your skin.
