### ISSUE TITLE
OTD sends a very large amount of errors before lazer can disable OTD

### ISSUE THREAD

**Issue by hrfarmer** [ppy/osu#24086]
### Type

Game behaviour

### Bug description

OpenTabletDriver was giving an error for the tablet, but between the time OTD sent the error and Lazer disabled the driver (#23719), OTD would flood my in-game notifications with literally thousands of errors.

### Screenshots or videos

https://github.com/ppy/osu/assets/58487401/c8e4ea3d-644c-48e4-9b44-f254b13bee7e

### Version

2023.621.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/11910929/network.log)
[runtime.log](https://github.com/ppy/osu/files/11910930/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11910931/performance.log)
[input.log](https://github.com/ppy/osu/files/11910932/input.log)
[database.log](https://github.com/ppy/osu/files/11910933/database.log)

**Comment by peppy** [comment]
I think this might be resolved with the next framework bump (as we updated OTD itself), but maybe we can also handle this better from our end.
