### ISSUE TITLE
Black screen on launch, followed by crash

### ISSUE THREAD

**Issue by Disreality** [ppy/osu#241]
Hello there.
It seems there's an issue when opening the app, it just shows a black screen for a couple of seconds, followed by a crash.
I've also tried running in Admin Mode, same problem. The versions I've tried are v6 and v5.

Have a nice day!
EDIT: Yes, .NET 4.5 is installed

**Comment by aerouk** [comment]
Files are blocked by default. Try building from source if you don't know how to unblock them.

**Comment by peppy** [comment]
Resolved via framework DI fix (if that's what this was referring to).
