### ISSUE TITLE
Spectator bug in multiplayer

### ISSUE THREAD

**Issue by TheSloPro** [ppy/osu#24108]
### Type

Game behaviour

### Bug description

When playing multiplayer, if the map that is currently being played is removed, the spectator will see the next map. Look at the screen recording for more details my english is bad...

**How to replicate**

0. Create a room
1. Have 2 maps in queue
2. Let others play
3. Remove the map that they're playing
4. Click spectate

### Screenshots or videos

https://github.com/ppy/osu/assets/37777261/a1e56707-5049-494e-9baa-76fb99e812a4

### Version

app-2023.621.0

### Logs

not necesarry

**Comment by bdach** [comment]
Probably shouldn't be possible to remove items that are currently being played in the first place.
