### ISSUE TITLE
Odd score calculation

### ISSUE THREAD

**Issue by Aerastus** [ppy/osu#24113]
### Type

Game behaviour

### Bug description

Had a brief look through the other issues with the score tag, but nothing seemed to exactly fit. I've been messing around with Lazer as a mania player recently and noticed that plays with better accuracy and higher ratio result in scoring that is far lower than it seems it should be when compared to the other scores around it. This consistently happens for me.

If its as simple as the way score is calculated has changed between these plays, then my bad, but I couldn't see anything specifically about it. 

### Screenshots or videos

![Untitled](https://github.com/ppy/osu/assets/138389483/57b9a371-d921-4d01-84db-91d548f316fc)
![score1](https://github.com/ppy/osu/assets/138389483/ea1094ac-fbcb-4c73-89ba-cd617beeab62)
![score 2](https://github.com/ppy/osu/assets/138389483/388db135-e474-4dfc-8e48-1fa470c30bc4)

### Version

2023.621.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11944348/database.log)
[input.log](https://github.com/ppy/osu/files/11944349/input.log)
[network.log](https://github.com/ppy/osu/files/11944350/network.log)
[performance.log](https://github.com/ppy/osu/files/11944351/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11944352/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11944353/updater.log)

**Comment by peppy** [comment]
Comparing against old online scores is not a great thing to do right now. We'll reset the leaderboards soon.

**Comment by Aerastus** [comment]
Roger that. o/
