### ISSUE TITLE
Song options have no hovering animation.

### ISSUE THREAD

**Issue by DentsHub** [ppy/osu#2413]
Title and video show it all.

https://youtu.be/hEHAW-8z4xo

**Comment by peppy** [comment]
Correct

**Comment by StartForKillerMC** [comment]
Trying to add the animation

**Comment by StartForKillerMC** [comment]
https://github.com/ppy/osu/pull/2436

**Comment by StartForKillerMC** [comment]
https://github.com/ppy/osu/pull/2437

**Comment by peppy** [comment]
Don't think this needs a tracking issue. Will change with designs as they evolve.
