### ISSUE TITLE
Player loader metadata is not centered

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#2414]
Is this design intentional? The center is the space between the keyword and the title. If you were to center it, the keyword would be on the very left of long source titles, and keywords won't be in the same place.
The diff name is for middle reference.
![](https://puu.sh/A3Suq/ad96070462.png)

Idk if this would work out. Any thoughts? The spacing is not finalised.
![](https://puu.sh/A3SqZ/f081a05d67.png)

**Comment by peppy** [comment]
The whole metadata section container should be centered, not individual lines (ie. the first image you have, but everything is mvoed far left).

**Comment by peppy** [comment]
I believe this is behaving correctly as of now. Closing this issue to avoid confusion.
