### ISSUE TITLE
"mapped by" info in Song Select shows only the Creator, not the GD mapper as like on web

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#24143]
### Type

Other

### Bug description

Not much to say, basically "mapped by" should probably show the actual creator of the diff instead of the mapset host.
Screenshot from in-game:
![image](https://github.com/ppy/osu/assets/82095491/72a927e4-247d-4c59-86d9-9e2827ca0ddd)
Screenshot from in-game web browser:
![image](https://github.com/ppy/osu/assets/82095491/8d343a85-292e-4eb0-bb25-e1fe08b6f39f)

### Version

2023.621.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11968006/database.log)
[input.log](https://github.com/ppy/osu/files/11968007/input.log)
[network.log](https://github.com/ppy/osu/files/11968008/network.log)
[performance.log](https://github.com/ppy/osu/files/11968009/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11968010/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11968012/updater.log)

**Comment by soopax** [comment]
Similar to https://github.com/ppy/osu/issues/12965.

**Comment by Joehuu** [comment]
I'd say it's a duplicate as it requires the same fix (having both `hosted|mapped by` present in the UI and fixing the wrong linking).
