### ISSUE TITLE
The prompt to leave the Editor muffles the music, but not the hitsounds if the song is not paused

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#24162]
### Type

Game behaviour

### Bug description

1. Go to the editor for any map
2. Start the playback
3. Click Esc to get to the prompt
4. Notice that hitsounds are not muffled with the music

### Screenshots or videos

https://skubi.s-ul.eu/JQswBUoV

### Version

2023.621.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11990814/database.log)
[input.log](https://github.com/ppy/osu/files/11990815/input.log)
[network.log](https://github.com/ppy/osu/files/11990816/network.log)
[performance.log](https://github.com/ppy/osu/files/11990817/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11990818/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11990819/updater.log)

**Comment by bdach** [comment]
#23043
