### ISSUE TITLE
Crash after Starting a CTB Map with Pressing Shift

### ISSUE THREAD

**Issue by WhiteRedWolf** [ppy/osu#2418]
![screenshot_37](https://user-images.githubusercontent.com/33634370/38947651-bd2d404c-433d-11e8-8d3d-0398c5c6197c.png)

That Happened to me While Starting a CTB Converted Map in osu!lazer i was Pressing Shift and right and left arrow key and that happened

**Comment by alexpado** [comment]
You can just Ignore this error and keep playing. It's happening when you're pressing a key between the load screen and the game screen

**Comment by smoogipoo** [comment]
Will be looking into this issue next. Closing as it is a duplicate.
