### ISSUE TITLE
Incorrect stacking on older maps?

### ISSUE THREAD

**Issue by daymxn** [ppy/osu#24185]
### Type

Game behaviour

### Bug description

Beatmap: [#1146](https://osu.ppy.sh/beatmapsets/243#osu/1146)

The stacking is different between Stable and Lazer; if you look at the screenshots below, you'll notice that Lazer applies a stack to the second slider, while Stable does not.

The Beatmap is an old map (V3), so it may be an issue with [how older maps are parsed](https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapProcessor.cs#L193).

_Note that while the screenshot is from the editor, this behavior is identical to the gameplay_

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/17409137/e93a154b-c711-4b81-8c2b-b08b7cca2ab8)
![image](https://github.com/ppy/osu/assets/17409137/8aa97918-62fb-4c20-bad4-29970618b3f0)

### Version

2023.621.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12017260/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12017261/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12017262/updater.log)
[database.log](https://github.com/ppy/osu/files/12017263/database.log)
[input.log](https://github.com/ppy/osu/files/12017264/input.log)

**Comment by peppy** [comment]
In the future, please include a timestamp of where the issue occurs in the beatmap.
