### ISSUE TITLE
Mania score cannot be import

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#24217]
### Type

Game behaviour

### Bug description

Database import or population failed and has been rolled back.
System.InvalidCastException: Unable to cast object of type 'FakeHit' to type 'osu.Game.Rulesets.Mania.Objects.ManiaHitObject'.

Reproducibility method:
play mania once and you will get error message in result screen, fail the game and import score by button also can cause fail

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/34775378/2b2624cd-4d63-4bb1-a1f2-ea0a33c18d01)

### Version

commit cdbb6f90be

### Logs

[database.log](https://github.com/ppy/osu/files/12047867/database.log)
[runtime.log](https://github.com/ppy/osu/files/12047870/runtime.log)

**Comment by peppy** [comment]
Thank you for your testing. This definitely saved us from a hotfix release.
