### ISSUE TITLE
Missing localizable elements

### ISSUE THREAD

**Issue by Sclafus** [ppy/osu#24231]
### Type

Cosmetic

### Bug description

I was looking at the crowdin and I realized that there are some missing localizable items. 
In-game language is Italian, which is (almost) fully translated. 
This is *not* a case of missing translations.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/31241607/787db164-2672-48d7-8ab8-826a6a348945)

Partial `ModSelectOverlay` (only `Personal Presets` -> `Preset Personali` & `Difficulty Multiplier` -> `Moltiplicatore Difficoltà`)
![image](https://github.com/ppy/osu/assets/31241607/304161e9-b7b7-4ed7-a9f7-0f34dedf0f72)

Only `Edit Beatmap` -> `Modifica Beatmap`
![image](https://github.com/ppy/osu/assets/31241607/0622bc58-993e-419e-8d4c-6fe5674ac263)

### Version

2023.621.0-lazer

### Logs

N/A

**Comment by bdach** [comment]
We know. There is so much stuff left to localise it's not worth opening an issue for.

**Comment by Sclafus** [comment]
@bdach is there already an issue/milestone tracking this issue?

**Comment by bdach** [comment]
No, because there's no point. Every single user-facing string in the game code that is not a `LocalisableString` needs to be fixed. We have tooling that points this out too.
