### ISSUE TITLE
Components of BeatmapSetOverlay need tests

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#2423]
The following types are defined as required by `TestCaseBeatmapSetOverlay`:
```
typeof(Header),
typeof(ClickableUsername),
typeof(DrawableScore),
typeof(DrawableTopScore),
typeof(ScoresContainer),
typeof(AuthorInfo),
typeof(BasicStats),
typeof(BeatmapPicker),
typeof(Details),
typeof(DownloadButton),
typeof(FavouriteButton),
typeof(Header),
typeof(HeaderButton),
typeof(Info),
typeof(PreviewButton),
typeof(SuccessRate),
```

Almost all, if not all of these, change their display or behaviour depending on the presence of `Beatmap` or `BeatmapSet` or `Metrics` or `User` or similar objects.

`TestCaseBeatmapSetOverlay` is used as the catch-all test for all of these components. This cannot stand going forward. Each of these components needs an individual testcase.

**Comment by peppy** [comment]
Safe to say the majority of these now have tests.
