### ISSUE TITLE
osu! doesn't want to be fullscreen

### ISSUE THREAD

**Issue by MeuhMeuh62** [ppy/osu#24247]
### Type

Performance

### Bug description

When i press F11 or alt+enter osu! normally does fullscreen but not for me.
Borderless or fullscreen normally hide task-bar but not now.
A youtube video for explain my problem is available down.
OS : Windows 11 Dev. insider preview, Version : 10.0.23493 Build 23493

### Screenshots or videos

https://youtu.be/LfF4X5i-N80

### Version

2023.716.0

### Logs

[performance-input.log](https://github.com/ppy/osu/files/12064377/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12064379/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12064380/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12064381/updater.log)
[database.log](https://github.com/ppy/osu/files/12064382/database.log)
[input.log](https://github.com/ppy/osu/files/12064383/input.log)
[network.log](https://github.com/ppy/osu/files/12064384/network.log)
[performance.log](https://github.com/ppy/osu/files/12064385/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/12064386/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12064387/performance-draw.log)

**Comment by agatemosu** [comment]
If you restart the computer does it work?

**Comment by longnguyen2004** [comment]
Restart explorer.exe/your computer. Sometimes Windows like to do it, and there's no way to fix it afaik

**Comment by RizonFTW** [comment]
This is an known windows issue which has been around for awhile. It sometimes happens sometimes doesn't. 

Normally, you would just click on the OSU! icon on the taskbar and it will disappear.

**Comment by MeuhMeuh62** [comment]
I restart m'y laptop and yeah it's works ty. I see Windows Explorer logs,
task bar dosen't hide yeah ty.
