### ISSUE TITLE
iOS crash on song carousel

### ISSUE THREAD

**Issue by hburn7** [ppy/osu#24251]
### Type

Crash to desktop

### Bug description

On the latest TestFlight version (2023.716.0) the app crashes completely and produces errors through normal use.

### Screenshots or videos

https://github.com/ppy/osu/assets/38370573/1a36c753-e9c8-480c-986d-0e23e4c9234f

### Version

2023.716.0

### Logs

[network.log](https://github.com/ppy/osu/files/12064556/network.log)
[database.log](https://github.com/ppy/osu/files/12064557/database.log)
[runtime.log](https://github.com/ppy/osu/files/12064558/runtime.log)
[performance.log](https://github.com/ppy/osu/files/12064559/performance.log)
[input.log](https://github.com/ppy/osu/files/12064560/input.log)

**Comment by agatemosu** [comment]
#24242
