### ISSUE TITLE
Changing skin while paused doesn't immediately update gameplay elements

### ISSUE THREAD

**Issue by DarkbitNetwork** [ppy/osu#24269]
### Type

Cosmetic

### Bug description

The hit objects (circle, slider, spinner), follow points, judgements (300s, 100s, etc.), and the cursor doesn't immediately update when the skin is changed until the gameplay is unpaused. Notice how other UI elements (health bar, accuracy, combo counter, etc.) are updated immediately even when the game is paused.

This can occur during autoplay and during actual gameplay.

### Steps to reproduce:
1. Play any beatmap
2. Pause while the gameplay is active
3. Change skin to any other skin (where hit objects or cursor are different)
4. Observe the change.
5. Then unpause the gameplay.

### Screenshots or videos
Doesn't include follow points because the video is made before I found out this issue also affect follow points

https://github.com/ppy/osu/assets/43719333/ccb1edec-88fb-4e8e-b74e-165ebdf95048

### Version

osu! 2023.717.0-lazer

### Logs

Unnecessary but I'll put it here anyway.
[performance.log](https://github.com/ppy/osu/files/12068380/performance.log)
[updater.log](https://github.com/ppy/osu/files/12068381/updater.log)
[database.log](https://github.com/ppy/osu/files/12068382/database.log)
[network.log](https://github.com/ppy/osu/files/12068383/network.log)
[runtime.log](https://github.com/ppy/osu/files/12068384/runtime.log)

**Comment by monochrome22** [comment]
Should be same as https://github.com/ppy/osu/issues/7285.
