### ISSUE TITLE
the game force close when trying to play rulesets rush and can't icon

### ISSUE THREAD

**Issue by Megumiiiiii** [ppy/osu#24268]
### Type

Crash to desktop

### Bug description

2023-07-17 06:28:34 [verbose]: Unhandled exception has been denied .
2023-07-17 06:28:36 [verbose]: ⚠️ Subsequent messages have been logged. Click to view log files.
2023-07-17 06:28:36 [verbose]: Host execution state changed to Stopping
2023-07-17 06:28:36 [verbose]: Host execution state changed to Stopped

### Screenshots or videos

![osu_2023-07-17_13-27-56](https://github.com/ppy/osu/assets/98658943/1ee43823-a870-40f4-b2b4-0f066b77e176)

### Version

2023.717.0

### Logs

[database.log](https://github.com/ppy/osu/files/12066566/database.log)
[input.log](https://github.com/ppy/osu/files/12066567/input.log)
[network.log](https://github.com/ppy/osu/files/12066568/network.log)
[performance.log](https://github.com/ppy/osu/files/12066569/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12066570/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12066571/updater.log)

**Comment by peppy** [comment]
You'll have to contact the ruleset developer. We constantly make changes and unfortunately this means that rulesets need to be updated in some releases.

**Comment by peppy** [comment]
You'll have to contact the ruleset developer. We constantly make changes and unfortunately this means that rulesets need to be updated in some releases.
