### ISSUE TITLE
Overall ranking total score not matching actual lazer score

### ISSUE THREAD

**Issue by Ladwick** [ppy/osu#24261]
### Type

Game behaviour

### Bug description

The title is pretty self explanatory, but basically when I set a score, sometimes the overall ranking total score won't match the lazer score neither in standardised or classic display, sadly I'm not able to decipher a pattern in the bug because it will happen sometimes and other times both scores will match, I tried using mods, playing a map that had a score set already, not finishing sliderends, failing sliderticks or spinners and even losing score after failing many times in a row but after trying every one of those methods at least twice the only thing I could understand is that this disparity will happen sometimes and other times it won't.

The first two images show two different scores I settled on the same map and diff (I tried using the same method of replaying a map with a score settled in other maps but then the disparity wouldn't occur in all of the cases) and the third image is a first time score I settled, getting the disparity.

### Screenshots or videos

![osu_2023-07-16_16-06-05](https://github.com/ppy/osu/assets/37979533/9b1a1659-b4f4-4442-992d-7104a05470ab)
![osu_2023-07-16_16-09-47](https://github.com/ppy/osu/assets/37979533/f0e21c94-9bc2-4071-bebe-244497ce2a90)
![osu_2023-07-16_15-14-08](https://github.com/ppy/osu/assets/37979533/0087e760-ed51-4433-a807-97c567b4f17b)

### Version

2023.716.0

### Logs

[performance.log](https://github.com/ppy/osu/files/12064964/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/12064965/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/12064966/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12064967/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12064970/updater.log)
[database.log](https://github.com/ppy/osu/files/12064971/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12064972/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12064973/network.log)

**Comment by peppy** [comment]
Checking the process for this, I can't see how this could occur (there's no special processing server-side for this currently). Going to need more diagnostics of when it happens.

I also attempting to repro but things look fine my end.

**Comment by Ladwick** [comment]
This stopped happening eventually, maybe it was due to a score discrepancy between server and client thanks to the score system modifications that were happening by that time? Or maybe something weird happening on my side, I dunno.
