### ISSUE TITLE
Timing distribution graph shows slider head hits in an unintuitive way on classic scores

### ISSUE THREAD

**Issue by bdach** [ppy/osu#24274]
### Type

Game behaviour

### Bug description

Originally reported [on discord](https://discord.com/channels/188630481301012481/188630652340404224/1128931248442720287). Opening as issue because I'm not sure what to do with this one.

The slider head circle is judged either as a full circle (with classic mod off), or as a large slider tick (with classic mod on):

https://github.com/ppy/osu/blob/551c24394516517dd33c81ac4be75c24b52d4197/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderHead.cs#L83-L93

Notably, when classic mod is on, the head circle is judged as a large slider tick, but contrary to normal slider ticks, it still has non-empty hit windows due to inheriting from `HitCircle : OsuHitObject`:

https://github.com/ppy/osu/blob/551c24394516517dd33c81ac4be75c24b52d4197/osu.Game.Rulesets.Osu/Objects/SliderHeadCircle.cs#L9
https://github.com/ppy/osu/blob/551c24394516517dd33c81ac4be75c24b52d4197/osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs#L156

The hit event distribution graph discards hit events for objects with empty hit windows:

https://github.com/ppy/osu/blob/551c24394516517dd33c81ac4be75c24b52d4197/osu.Game/Screens/Ranking/Statistics/HitEventTimingDistributionGraph.cs#L62

However, with classic active, slider heads are objects that are judged as ticks but have non-empty hit windows, leading them to be included on the stacked bar graph (in the topmost position on each bar). What compounds the confusion is the fact that they will always be painted on the graph using blue:

https://github.com/ppy/osu/blob/551c24394516517dd33c81ac4be75c24b52d4197/osu.Game/Graphics/OsuColour.cs#L92-L95

With classic off, this just isn't an issue because the slider heads are judged as standard circles.

### Screenshots or videos

![osu_2023-07-17_20-25-28](https://github.com/ppy/osu/assets/20418176/82e3baf5-8d5b-4b72-8f19-7a891040df7d)

### Version

current master

### Logs

n/a

**Comment by peppy** [comment]
Is the fix here as simple as returning empty windows when classic mod is enabled (probably via a flag set somewhere on the `OsuHitObject`, or applied by the mod – `HitWindows` is publicly settable)?

**Comment by bdach** [comment]
> Is the fix here as simple as returning empty windows when classic mod is enabled (probably via a flag set somewhere on the `OsuHitObject`, or applied by the mod – `HitWindows` is publicly settable)?

I'm 99% sure it is not. Doing this would essentially mean that with classic mod active the slider head would need to be hit with zero offset. As in precise to the millisecond.

This isn't an issue for normal slider ticks as they are generally not timed objects and judgements on them are set on their parent objects.
