### ISSUE TITLE
`BeatmapOptionsOverlay` is missing new design

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#24273]
Nowhere to be seen in https://www.figma.com/file/DXKwqZhD5yyb1igc3mKo1P/Song-Select-Draft-2?type=design&node-id=0-1&mode=design&t=OgFGHnbe4rJH7Vlt-0 as of now.

Tracking as it was ignored multiple times during the implementation of the new footer and it's not in the client yet mostly because of this.

Ref:

> @arflyte still missing design
> 
> ![osu! 2022-12-01 at 06 44 46](https://user-images.githubusercontent.com/191335/204984135-6b5db31d-4ff5-4649-bb9d-60ced7500b0a.png)
> 
> what do

_Originally posted by @peppy in https://github.com/ppy/osu/issues/20148#issuecomment-1333285223_

**Comment by peppy** [comment]
@arflyte

**Comment by peppy** [comment]
@arflyte

**Comment by Tanza3D** [comment]
was asked by peppy to try a design on this;
![image](https://github.com/ppy/osu/assets/33783503/c273ec37-bcfb-41d4-894b-3b9b949a4a8d)

there's probably some existing components and such which look a bit different than this, but this is a general idea of how i feel it should look. - uses the same dropdown ui than in editor, just with an error (arrow is not too important if it's too complex to add)

![image](https://github.com/ppy/osu/assets/33783503/2c4f086e-f741-4d8f-97a4-25a929f59a4b)

background in that ui is `B/B4 - Card`, and the buttons are `B/B3 - Brighter Card`, though again if existing components differ from that i feel it's fine

https://www.figma.com/file/2PxrcTbYoFXzHj4ctD9tde/Lazer-%7C-Song-Select-Options-Dropdown?type=design&node-id=0%3A1&mode=design&t=kh046WQrmfkPnQS7-1

**Comment by peppy** [comment]
I think this looks pretty decent 👍 .
