### ISSUE TITLE
Hitcircles fade out too fast with classic mod active

### ISSUE THREAD

**Issue by bdach** [ppy/osu#24276]
### Type

Cosmetic

### Bug description

See video below for visual explanation.

I think https://github.com/ppy/osu/pull/22543 is partially wrong. In particular, when debugging stable, the code linked [in this review comment](https://github.com/ppy/osu/pull/22543#discussion_r1105282453) which comes from [`Disarm()`](https://github.com/peppy/osu-stable-reference/blob/1531237b63392e82c003c712faa028406073aa8f/osu!/GameplayElements/HitObjects/Osu/HitCircleOsu.cs#L220-L222) does not fire when the hit circle is hit or even missed. What fires on hit/miss is [`Arm()`](https://github.com/peppy/osu-stable-reference/blob/1531237b63392e82c003c712faa028406073aa8f/osu!/GameplayElements/HitObjects/Osu/HitCircleOsu.cs#L235-L277) instead which is:

```csharp
        internal override void Arm(bool isHit)
        {
            base.Arm(isHit);


            int armTime = GameBase.Mode != OsuModes.Edit ? AudioEngine.Time : StartTime;


            if (isHit)
            {
                //Fade out the actual hit circle
                Transformation circleScaleOut = new Transformation(TransformationType.Scale, 1.0F, 1.4F, armTime, (int)(armTime + (HitObjectManager.FadeOut)), EasingTypes.Out) { TagNumeric = ARMED };


                SpriteHitCircle1.Transformations.Add(circleScaleOut);
                SpriteHitCircle1.Transformations.Add(new Transformation(TransformationType.Fade, 1, 0, armTime, armTime + HitObjectManager.FadeOut) { TagNumeric = ARMED });


                SpriteHitCircle2.Transformations.Add(circleScaleOut.Clone());
                SpriteHitCircle2.Transformations.Add(new Transformation(TransformationType.Fade, 1, 0, armTime, armTime + HitObjectManager.FadeOut) { TagNumeric = ARMED });


                SpriteApproachCircle.Transformations.Add(new Transformation(TransformationType.Fade, SpriteApproachCircle.Alpha, 0, armTime, armTime) { TagNumeric = ARMED });


                if (SkinManager.UseNewLayout)
                {
                    SpriteHitCircleText.Transformations.Add(new Transformation(TransformationType.Fade, 1, 0, armTime, armTime + 60) { TagNumeric = ARMED });
                }
                else
                {
                    SpriteHitCircleText.Transformations.Add(new Transformation(TransformationType.Scale, 1.0F * TEXT_SIZE, 1.4F * TEXT_SIZE, armTime, (int)(armTime + (HitObjectManager.FadeOut)), EasingTypes.Out) { TagNumeric = ARMED });
                    SpriteHitCircleText.Transformations.Add(new Transformation(TransformationType.Fade, SpriteHitCircleText.Alpha, 0, armTime, armTime + HitObjectManager.FadeOut) { TagNumeric = ARMED });
                }
            }
            else
            {
                bool hidden = ModManager.CheckActive(hitObjectManager.ActiveMods, Mods.Hidden);


                SpriteHitCircle1.Transformations.Add(new Transformation(TransformationType.Fade, !hidden ? SpriteHitCircle1.Alpha : 0, 0, armTime, armTime + 60) { TagNumeric = ARMED });
                SpriteHitCircle2.Transformations.Add(new Transformation(TransformationType.Fade, !hidden ? SpriteHitCircle2.Alpha : 0, 0, armTime, armTime + 60) { TagNumeric = ARMED });
                SpriteHitCircleText.Transformations.Add(new Transformation(TransformationType.Fade, !hidden ? SpriteHitCircleText.Alpha : 0, 0, armTime, armTime + 60) { TagNumeric = ARMED });
                SpriteApproachCircle.Transformations.Add(new Transformation(TransformationType.Fade, !hidden ? SpriteApproachCircle.Alpha : 0, 0, armTime, armTime + 60) { TagNumeric = ARMED });


                SpriteHitCircle1.Scale = DefaultScale;
                SpriteHitCircle2.Scale = DefaultScale;
                SpriteHitCircleText.Scale = TEXT_SIZE;
            }
        }
```

and in particular features differing fadeout durations depending on whether the hitcircle was hit or missed.

### Screenshots or videos

https://github.com/ppy/osu/assets/20418176/7fc859ed-fb78-4aac-a647-870fd17a7ba7

Left is stable. Right is lazer master with classic active.

Map used: [Caravan Palace feat. Charles X - About You.osz.zip](https://github.com/ppy/osu/files/12074000/Caravan.Palace.feat.Charles.X.-.About.You.osz.zip) (remove zip extension)

### Version

current master

### Logs

n/a

**Comment by frenzibyte** [comment]
Something is not adding up here. In the stable code, if the hit circle has been missed, then the difference between `AudioEngine.Time` and `StartTime` must be at least greater than the hit window of the lowest result type (i.e. 400ms). But according to the video attached in #22543, the hit circle is fading out before the miss judgement is raised? (cc @peppy).

For now, the hit circle must definitely not apply the "early fade out" transition if it has changed to a hit state, so I'll fix that quickly.
