### ISSUE TITLE
Color-hexed beatmaps don't translate correctly into Lazer

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#24270]
### Type

Game behaviour

### Bug description

Taking my ranked mapset as an example: https://osu.ppy.sh/beatmapsets/1724593#osu/3524570

I've color-hexed the map, so that my parts are: blue, light blue, blue, light blue
and Sonnyc's parts are: pink, light pink, pink, light pink

As you can see in the second kiai, the colors are mixed.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/82095491/b38b6c07-f948-4d38-9880-e6cdcef39de3)
![image](https://github.com/ppy/osu/assets/82095491/5d852456-e42b-422f-ad80-47e56093caf2)

### Version

2023.717.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/12069827/network.log)
[performance.log](https://github.com/ppy/osu/files/12069828/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12069829/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12069830/updater.log)
[database.log](https://github.com/ppy/osu/files/12069831/database.log)
[input.log](https://github.com/ppy/osu/files/12069832/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12069833/legacy-ipc.log)

**Comment by bdach** [comment]
As far as I can tell this is caused by the spinner at the start of the map. It appears that on stable spinners [_never_ increment combo index](https://github.com/peppy/osu-stable-reference/blob/master/osu!/GameplayElements/HitObjectManager.cs#L1273-L1294):

```csharp
                if (currHitObject.IsType(HitObjectType.Spinner))
                {
                    if (Beatmap.BeatmapVersion <= 8)
                        forceNew = true;
                    else if (currHitObject.NewCombo)
                    {
                        // make colourhax possible when the spinner has a new combo but the object after does not:
                        // the player may set colourhax on the spinner itself in this case and get carried over.
                        combo += offset;
                        forceNew = true;
                    }
                }
                else if (forceNew || (currHitObject.Type & HitObjectType.NewCombo) > 0 || //Keep bit flag intact here as it is necessary for CTB to alternate fruit color while still keeping track of combo.
                         (i == 0 && !(currHitObject is HitCircleFruits)))
                {
                    comboNumber = 1;
                    currHitObject.ComboNumber = comboNumber;
                    combo += offset + 1;
                    forceNew = false;
                }
                else
                    currHitObject.ComboNumber = ++comboNumber;
```

while lazer is using the much more naive

https://github.com/ppy/osu/blob/88ac53557a328b3e149b6392752fb5884107f374/osu.Game/Rulesets/Objects/Types/IHasComboInformation.cs#L67-L86
