### ISSUE TITLE
Game hardlocks when losing connection / signing out while creating a online room with a beatmap added

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#24275]
### Type

Crash to desktop

### Bug description

Noticed when addressing the duration supporter todo and wanted to sign out:
https://github.com/ppy/osu/blob/27c497145f87449ac17c08796fc57026d3129f2e/osu.Game/Screens/OnlinePlay/Playlists/PlaylistsRoomSettingsOverlay.cs#L331

The while loop never ends because of the blocking discard changes dialog:
https://github.com/ppy/osu/blob/62d177440730e507ff3b080dd8c1c1eca66ea6bc/osu.Game/Screens/OnlinePlay/OnlinePlayScreen.cs#L98-L114

https://github.com/ppy/osu/blob/894ef15e79168b985eced57741c9cd1428eb2d2b/osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs#L354-L374

### Screenshots or videos

https://github.com/ppy/osu/assets/35318437/733adc62-2d75-412c-9720-d5dda6ef66f6

### Version

Since 2022.731.1 / https://github.com/ppy/osu/pull/19455

### Logs

N/A

**Comment by bdach** [comment]
Maybe we want to pull out this logic from `MultiplayerMatchSubScreen` to base...

https://github.com/ppy/osu/blob/88ac53557a328b3e149b6392752fb5884107f374/osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs#L257-L263
