### ISSUE TITLE
Osu!lazer scores broken

### ISSUE THREAD

**Issue by itskhero** [ppy/osu#24281]
### Type

Game Behaviour

### Bug description

Started the game, game throws a unhandled error, when i got to "choosing beatmap" section, the scores are just like that, the scores of my beatmaps is just impossible and the others are so low (as on the screenshots attached)

### Screenshots or videos

![Screenshot_2023-07-18-17-42-40-59_25a1a32208bbcdc1d450b7aa854bb161](https://github.com/ppy/osu/assets/116128416/3021d437-922b-43db-9660-a9c70405379e)
![Screenshot_2023-07-18-17-40-43-06_25a1a32208bbcdc1d450b7aa854bb161](https://github.com/ppy/osu/assets/116128416/01fd01ac-7086-4d06-b80d-5867de6bce64)

### Version

osu!lazer 2023.717.0

### Logs

[database.log](https://github.com/ppy/osu/files/12079128/database.log)
[network.log](https://github.com/ppy/osu/files/12079129/network.log)
[performance.log](https://github.com/ppy/osu/files/12079130/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12079131/runtime.log)

**Comment by peppy** [comment]
Could you please attach your `client.realm`?

**Comment by itskhero** [comment]
> Could you please attach your `client.realm`?

[client.realm.zip](https://github.com/ppy/osu/files/12080039/client.realm.zip)

**Comment by itskhero** [comment]
my dumbass accidentally clicked close issue sorry

**Comment by itskhero** [comment]
> Could you please attach your `client.realm`?

does sending a freshly launched osu!lazer's whole FILES directory with no logins is still going to carry sensitive information in it?

**Comment by peppy** [comment]
The scores in your first screenshot are correct. You have the game set to classic score display mode, maybe you didn't mean to set that?

![osu! 2023-07-19 at 05 16 53](https://github.com/ppy/osu/assets/191335/27feccab-e5ee-4f6a-af91-715856b6cafd)

**Comment by itskhero** [comment]
> 

oh. i do didn't meant that to be set on classic. 
well i'm really sorry that i bothered you and i hope i didn't made your day/night worse 'my stupidity got me again (-_-)'
