### ISSUE TITLE
Editor's functionality concept

### ISSUE THREAD

**Issue by AlFasGD** [ppy/osu#2428]
Right now the editor works in a very "impulsive" way. Simply opening it will start editing a beatmap with the song that is currently playing on the background. Notably, even "Circles" (the song that plays upon opening the game) is "editable".

Allowing the user to select a song from the beatmap carousel just like in the normal play screen needs to be implemented, since this is the way it's constructed in osu!stable.

**Comment by peppy** [comment]
Yes, this is one task which needs to be completed.

**Comment by peppy** [comment]
This has since been resolved. We still need an "open" menu in the editor but at very least, going into the editor no longer starts editing the randomly playing track.
