### ISSUE TITLE
Score upgrade may fail for beatmaps missing files on disk (and cause performance degradation on startup)

### ISSUE THREAD

**Issue by shrublet** [ppy/osu#24301]
### Type

Game behaviour

### Bug description

[As per this message on the osu! discord](https://discord.com/channels/188630481301012481/1097318920991559880/1131412159881019492), the game fails to upgrade some scores on startup which causes brief performance degradation.

### Version

2023.717.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/12101906/runtime.log)
[client.zip](https://drive.google.com/file/d/1vuEvMc2PHD0yqz9oIdBMRcM1I8ePbSKw/view?usp=sharing) (uploaded on drive since it's over 25MB)

**Comment by peppy** [comment]
It looks like files are missing for a lot of your beatmaps. Did you happen to do anything weird to your lazer install in the past? ie. did you copy your database across to a new install without the `files` folder or something like that?

**Comment by peppy** [comment]
@ppy/team-client thoughts on what to do for cases like this? For failed upgrades, we may want to either mark them as if they succeeded, or mark them with a failed state in some way so they aren't reprocessed on each startup.

Alternatively, we could add a delay between processes to avoid the overhead that a user may see from this.

**Comment by bdach** [comment]
I'd probably mark as failed as a baseline rather than pretend it succeeded. Maybe not show such scores, or show them with an exclamation point or tooltip indicating the score is potentially bogus; maybe add a button for manual reprocessing. Not sure about the gory details.

**Comment by frenzibyte** [comment]
> I'd probably mark as failed as a baseline rather than pretend it succeeded. Maybe not show such scores, or show them with an exclamation point or tooltip indicating the score is potentially bogus; maybe add a button for manual reprocessing. Not sure about the gory details.

Agree with keeping the score displayed with an indicator beside it if feasible, not showing the score or ignore processing them feels too aggressive to the user if there's a way to salvage it.

**Comment by peppy** [comment]
So this is likely going to require another database flag, unless we're going to overload the score version with another special case...

**Comment by smoogipoo** [comment]
I'd also agree with a database flag.

**Comment by peppy** [comment]
@smoogipoo how does this look naming wise?

![image](https://github.com/ppy/osu/assets/191335/d57e150b-d2ec-48d2-9ef9-25309f913d51)

**Comment by smoogipoo** [comment]
I'd have gone with something more generic, but I think that's fine for the time being and we can adjust in the future if there's need for it.
