### ISSUE TITLE
Alt-A and Alt-Y doens't work well on lazer

### ISSUE THREAD

**Issue by hashgulso** [ppy/osu#24307]
### Type

Game behaviour

### Bug description

Kinda new on github so sorry if i did something wrong.

I tried osulazer with my keypad which uses Alt-A (left), Alt-Y (middle) and Alt-V(right), they work pretty well on stable but when i tried on lazer they aren't working very well when i play stream maps.

Note: I'm not that good on stream but i think the videos are good enough to point the problem.

### Screenshots or videos

I tried my best to replicate this on both lazer and stable:

Lazer:

https://github.com/ppy/osu/assets/140101905/a783d5e5-6e6c-4f96-bc2e-f1fddf322253

Stable:

https://github.com/ppy/osu/assets/140101905/40db6a74-1ad4-47d3-99c0-d7cf2bcc4628

Besides my overstream, i managed to maintain the stream well enough on stable but on lazer is all mess up.

### Version

2023.717.0-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/12112563/input.log)
[performance.log](https://github.com/ppy/osu/files/12112564/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12112565/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12112566/updater.log)
[database.log](https://github.com/ppy/osu/files/12112567/database.log)

**Comment by peppy** [comment]
Can't you change your keypad to not use alt? This is super weird and I'm not sure I'm even willing to investigate itt.

**Comment by hashgulso** [comment]
the seller didn't say anything about changing the keys but he suggested to use just "A" normally instead of "Alt-A" since the Alt command doesn't last too long and it works, sorry if i caused any trouble for a stupid way to fix this.
