### ISSUE TITLE
Game crash on mania mode

### ISSUE THREAD

**Issue by Litttlefish** [ppy/osu#24319]
### Type

Crash to desktop

### Bug description

The game will randomly crash when playing mania mode on any song.
Before crash, the game will freeze, not responsive to input, and after that throw 2 to 3 errors then crash.

### Version

2023.717.0

### Logs

[performance.log](https://github.com/ppy/osu/files/12126227/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12126244/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12126255/updater.log)
[database.log](https://github.com/ppy/osu/files/12126261/database.log)
[network.log](https://github.com/ppy/osu/files/12126266/network.log)

**Comment by bdach** [comment]
Duplicate of https://github.com/ppy/osu/issues/24248
