### ISSUE TITLE
No option to set a preview point in editor

### ISSUE THREAD

**Issue by Free544** [ppy/osu#24326]
### Type

Crash to desktop

### Bug description

I cannot find any option to set a preview point in the timing menu!!

### Screenshots or videos

![000](https://github.com/ppy/osu/assets/136237456/deaf4472-8fe5-4956-8770-dc0fc34b286e)

### Version

2023.717.0

### Logs

help

**Comment by integerrr** [comment]
??? You literally circled the option to set the preview time in the menus

**Comment by bdach** [comment]
The above is correct. *Timing* -> *Set preview point to current time* is what you're looking for.

**Comment by Free544** [comment]
Thanks guys I'm dumb
