### ISSUE TITLE
Auto hangs on the end of intensive maps in osu!catch

### ISSUE THREAD

**Issue by ghost** [ppy/osu#2433]
Auto seems to hang on the end of intensive osu!catch maps. This has happened both times I've tried it with [Woey's Soulless 4 map](https://osu.ppy.sh/beatmapsets/757945). I assume this is because of how intensive the map is since it also causes auto to miss notes (I've brought it up w/ this map in another existing issue) though it might also be because it's a standard map. Stable doesn't have any issues with this map.

Here's a screenshot of auto hanging at the end (even though I'm not sure if it's all that helpful in this case):
![image](https://user-images.githubusercontent.com/13991844/39068966-605bd2b6-449b-11e8-9115-efe54c7b0173.png)

osu!lazer also doesn't freeze entirely, I can exit out like you would any other time, by pressing escape, and I can also do things like open and play around with the visual settings just fine while it's like that.

EDIT: A map where this seems to only occasionally be a problem is [Maakkeli's Tetrastructural Minds map](https://osu.ppy.sh/beatmapsets/361035).

**Comment by peppy** [comment]
I believe this has been resolved?

**Comment by peppy** [comment]
Can confirm this is resolved.
