### ISSUE TITLE
Health drain should match expectations better

### ISSUE THREAD

**Issue by akiya-nagatsuka** [ppy/osu#24365]
### Type

Game behaviour

### Bug description

The HP system doesn't change when switching to classic mode, therefore I can pass some beatmap in laser and when I run the replay in classic osu! I see the fail because of the different HP system.

### Version

2023.717.0

### Logs

[performance.log](https://github.com/ppy/osu/files/12167032/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/12167033/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12167034/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/12167036/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12167037/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12167038/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12167039/updater.log)
[database.log](https://github.com/ppy/osu/files/12167040/database.log)
[input.log](https://github.com/ppy/osu/files/12167041/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12167042/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12167043/network.log)

**Comment by peppy** [comment]
We are still considering what to do with health drain, and may try to match stable 1:1.

**Comment by bdach** [comment]
@peppy what's the goal here? are we matching stable? always or only in classic mod?

**Comment by peppy** [comment]
I'd say always. At least as close as we can get.

**Comment by smoogipoo** [comment]
osu: https://github.com/ppy/osu/pull/25418
catch: https://github.com/ppy/osu/pull/25563
mania: https://github.com/ppy/osu/pull/25587
