### ISSUE TITLE
Snap grid in tournament bracket editor only covers a small static area

### ISSUE THREAD

**Issue by ILW8** [ppy/osu#24378]
### Type

Cosmetic

### Bug description

The RectangularPositionSnapGrid that was added to the tournament client's bracket editor only covers a relatively small static area. When creating any bracket with more than 8 matches per round, one will end up outside of the area covered by the snap grid.

The grid should cover the whole editor regardless of zoom level and how much the dragcontainer has been dragged

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/1176059/b70b0638-9269-4375-ace6-5f6f6fb98ba8)

### Version

on master branch, SHA 0b5be51ee00565f8e42668c3c8c0ec05c383f619

### Logs

[runtime.log](https://github.com/ppy/osu/files/12178324/runtime.log)
[network.log](https://github.com/ppy/osu/files/12178325/network.log)
[performance.log](https://github.com/ppy/osu/files/12178326/performance.log)
[database.log](https://github.com/ppy/osu/files/12178327/database.log)

**Comment by peppy** [comment]
It actually covers the while intended usable area. Could you please attach your `bracket.json`?

**Comment by ILW8** [comment]
Still in the middle of making it, but enough to illustrate the issue. The bracket is expected to look like this https://challonge.com/USC_2023

[bracket.json.zip](https://github.com/ppy/osu/files/12178502/bracket.json.zip)

zip file because github refuses to take .json files

**Comment by peppy** [comment]
My first question is that in your case, would you want the ability to zoom out far enough to see everything on one screen?

**Comment by ILW8** [comment]
It's more about having a grid while placing and aligning the matches in the lower part of the early rounds and in the losers' bracket. I've attached a bracket.json with the start of a losers bracket, hopefully it should help illustrate my point better:
[bracket.zip](https://github.com/ppy/osu/files/12191313/bracket.zip)

**Comment by peppy** [comment]
Please test against my PR if you can.

**Comment by ILW8** [comment]
Works great.
