### ISSUE TITLE
Osu Taiko! editor not able to place rims as right click

### ISSUE THREAD

**Issue by AstronomyLoot** [ppy/osu#24373]
### Type

Game behaviour

### Bug description

in the osu taiko editor, unlike the past versions of osu where you could place rim notes just by right clicking on the map, now it looks like you cant place rims by right clicking but rather pressing r or right clicking after you place the normal note and changing that note to rim
(details)
running on macos ventura 13.4

### Screenshots or videos

https://github.com/ppy/osu/assets/92839855/be598b3b-3610-4758-8b6b-192f83aac391

thats me trying left clicking(which worked)and right clicking(which didnt work)

### Version

2023.717.0

### Logs

[database.log](https://github.com/ppy/osu/files/12175266/database.log)
[input.log](https://github.com/ppy/osu/files/12175268/input.log)
[network.log](https://github.com/ppy/osu/files/12175269/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/12175270/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12175271/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/12175272/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/12175273/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12175274/runtime.log)

**Comment by bdach** [comment]
This was intentionally removed in https://github.com/ppy/osu/pull/23112.
