### ISSUE TITLE
Enabling autoplay via Ctrl-Enter and then exiting gameplay leaves the autoplay mod active

### ISSUE THREAD

**Issue by bdach** [ppy/osu#24383]
### Type

Game behaviour

### Bug description

Found during review of #24316.

1. Enter any map with autoplay momentarily enabled via <kbd>Ctrl</kbd>-<kbd>Enter</kbd>
2. Attempt to exit game
3. Abort exit
4. Re-enter song select
5. Momentarily-enabled autoplay mod will still be active

Looks to be caused by the fact that the unapplication of autoplay happens in `OnResuming()`:

https://github.com/ppy/osu/blob/22163020c348c8ad1545b95d33665277425f4a1f/osu.Game/Screens/Select/PlaySongSelect.cs#L146-L155

which doesn't fire on a screen stack unwind during exit process.

### Screenshots or videos

https://github.com/ppy/osu/assets/20418176/6b20a636-5da1-4782-93bd-71b121e4c588

### Version

current master

### Logs

n/a

**Comment by peppy** [comment]
Looks like a potential resolution would be to also call this logic in `OnExiting`, which is gauranteed to be called.
