### ISSUE TITLE
Beatmap has an additional slidertick in Stable comparing to lazer

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#24401]
### Type

Game behaviour

### Bug description

(Credits to Shmiklak for finding the issue)

[Troye Sivan - Rush (M a r v o l l o) (2).zip](https://github.com/ppy/osu/files/12196621/Troye.Sivan.-.Rush.M.a.r.v.o.l.l.o.2.zip)
Here's the beatmap

Diff: Skubi's thing
Timestamp: 01:19:918 (1) -

This slider doesn't have a slidertick on 01:20:246 - in lazer but does in stable
The diff was created in lazer

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/82095491/cf76bc19-dbf4-408e-b809-6c2cb65ecf99)
![image](https://github.com/ppy/osu/assets/82095491/a3fbc1be-390c-413f-95a3-c7575bf8753f)

### Version

2023.717.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12196636/database.log)
[input.log](https://github.com/ppy/osu/files/12196637/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12196638/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12196639/network.log)
[performance.log](https://github.com/ppy/osu/files/12196640/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12196641/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12196642/updater.log)

**Comment by Shmiklak** [comment]
As an addition to what Skubi mentioned, it isn’t just about sliderticks being inconsistent between lazer and stable, but rather how the whole sliderticks algorithm breaks with maps exported from lazer when they are imported in stable. Slidertick rate that has been set for this beatmap doesn’t actually cause sliderticks on 3/4 sliders and in fact it has never caused them throughout the map with this one slider being an only exception.

**Comment by peppy** [comment]
This is due to floating point precision (the timing point which has the 1.5x SV multiplier is not being taken on by the slider). I feel like we have a tracking issue for this already...

@OliBomby I don't suppose you've looked into the FP osz conversion? Until now we've output floating point as-is for round-trip compatibility, but maybe we need to floor or round everything now that we have a separate stable export path.

**Comment by OliBomby** [comment]
> This is due to floating point precision (the timing point which has the 1.5x SV multiplier is not being taken on by the slider). I feel like we have a tracking issue for this already...
> 
> @OliBomby I don't suppose you've looked into the FP osz conversion? Until now we've output floating point as-is for round-trip compatibility, but maybe we need to floor or round everything now that we have a separate stable export path.

The new compatibility conversion does truncate all floating point time values of the timing points and the hit objects, so this issue is gone if you use the compatibility export. I've checked and the slidertick is gone in stable if you use the compatibility export.

**Comment by peppy** [comment]
@OliBomby Is it safe to close this in that case? I think so?

**Comment by OliBomby** [comment]
Yes, it should be fixed now with compatibility export.
