### ISSUE TITLE
Crashing on loading any beatmap

### ISSUE THREAD

**Issue by Chisk** [ppy/osu#2440]
Everytime I try to load any beatmap, it being ranked, unranked, osu! standard, or osu!catch it crashes lazer. I'm running Windows 10. I'm not logged in as lazer is crashing when typing, only the last 5-6 updates to lazer has this happening.
[runtime.log](https://github.com/ppy/osu/files/1934958/runtime.log)

**Comment by peppy** [comment]
This will be fixed in the next release.

**Comment by peppy** [comment]
Could you please try this version and see if it helps? https://github.com/ppy/osu/releases/tag/v2018.421.0 It should automatically prompt you to install a newer framework, so please let me know if it doesn't.

**Comment by Chisk** [comment]
Peppy, it straight up won't load anymore. No log, nothing. It opens for a second, that closes.
