### ISSUE TITLE
Sliders with Perfect Curve anchors in the middle, don't translate correctly into stable

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#24426]
### Type

Crash to desktop

### Bug description

As in title and in screenshots

![image](https://github.com/ppy/osu/assets/82095491/c9fb4ab7-8c1f-4a9d-bd44-b0a343eb952a)

![image](https://github.com/ppy/osu/assets/82095491/639b1dc0-7720-43a0-8a2d-be3350765b8c)

### Version

2023.717.0-lazer

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/12210100/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12210101/network.log)
[performance.log](https://github.com/ppy/osu/files/12210102/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12210103/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12210104/updater.log)
[database.log](https://github.com/ppy/osu/files/12210105/database.log)
[input.log](https://github.com/ppy/osu/files/12210106/input.log)

**Comment by bdach** [comment]
This will be at least temporarily remedied by the legacy export option added in https://github.com/ppy/osu/pull/24186. Please stay tuned for the next release which will include it.
