### ISSUE TITLE
Spectator gameplay appearing behind focused gameplay

### ISSUE THREAD

**Issue by GDcheeriosYT** [ppy/osu#24432]
### Type

Game behaviour

### Bug description

I was spectating on lazer and was focusing to a player and saw that gameplay appeared behind. I'm pretty sure it has something to do with the storyboard layering.

### Screenshots or videos

https://github.com/ppy/osu/assets/54640414/90fe4322-fda2-41e5-92ec-7aea6397d383

### Version

2023.717.0-lazer

### Logs

[performance-draw.log](https://github.com/ppy/osu/files/12225151/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/12225152/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12225153/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12225154/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12225155/updater.log)
[database.log](https://github.com/ppy/osu/files/12225156/database.log)
[network.log](https://github.com/ppy/osu/files/12225157/network.log)
[performance.log](https://github.com/ppy/osu/files/12225158/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/12225159/performance-audio.log)

**Comment by toadsworth-jr** [comment]
Can you fix the video first? It won't load.

**Comment by GDcheeriosYT** [comment]
> Can you fix the video first? It won't load.

I don't know what you want me to do... It loads fine for me on other devices.

**Comment by peppy** [comment]
Could you turn off main menu storyboard mode and record again? It's a bit hard to tell what's going on with that active.

**Comment by GDcheeriosYT** [comment]
Yeah, 

https://github.com/ppy/osu/assets/54640414/e6e73552-26f9-48ab-a945-667f8feea2f4

**Comment by peppy** [comment]
The fix for his is simple, but I'm not too sure whether we need to consider the performance implications.

Also, it affect not just multiplayer / spectator but also solo gameplay.

**Comment by peppy** [comment]
Also this was attempted to be fixed in https://github.com/ppy/osu/pull/22035.
