### ISSUE TITLE
ProfileHeader needs a rewrite

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2445]
Half of user setting is done in ctor, half is done in `User_Set` with no logical separation.

Should be updated to work in the same way at `BeatmapSetOverlay`.

**Comment by swoolcock** [comment]
I'll pick this one up; it's on this month's milestone and seems pretty straightforward.

**Comment by swoolcock** [comment]
Going forward, do you think it might be useful to use a `Bindable<User>` for the profile overlay?  Possibly out of scope for this issue.

**Comment by peppy** [comment]
Nah, leave as property for now.

**Comment by swoolcock** [comment]
It's currently not a property at all (in the overlay), it's an overloaded method `ShowUser`.

**Comment by peppy** [comment]
That's fine too (at the top-most level). The main part is having it propagate down in a similar way to how it's done elsewhere, so everything is on the same page.

**Comment by peppy** [comment]
I believe it's a method there because it also triggers the display of the overlay as well.
