### ISSUE TITLE
Hard Link feature not working

### ISSUE THREAD

**Issue by Sebaex** [ppy/osu#24460]
### Type

Game behaviour

### Bug description

On First-run setup, lazer tells me that hard link will be used to copy my stable stuff, but it ends up making a whole copy of everything anyways

### Screenshots or videos

osu! telling me that hard link feature is available

![osu_2023-08-04_00-25-32](https://github.com/ppy/osu/assets/22472487/771ce2c2-8845-4b69-8b97-365882480bef)

ends up making a copy of everything rather than hard linking the stuff and filling my drive anyways

![osu!_EJDL243dN5](https://github.com/ppy/osu/assets/22472487/f4b247e8-c3e7-46b2-a7eb-dcbd14c5b203)

- Left folder: Stable
- Right folder: Lazer

### Version

2023.803.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12257068/database.log)
[input.log](https://github.com/ppy/osu/files/12257070/input.log)
[network.log](https://github.com/ppy/osu/files/12257071/network.log)
[performance.log](https://github.com/ppy/osu/files/12257072/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12257073/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12257074/updater.log)

**Comment by Joehuu** [comment]
The size in properties is misleading, please read the last paragraph from the link (https://osu.ppy.sh/wiki/en/Client/Release_stream/Lazer/File_storage#via-hard-links).

**Comment by Sebaex** [comment]
> The size in properties is misleading, please read the last paragraph from the link (https://osu.ppy.sh/wiki/en/Client/Release_stream/Lazer/File_storage#via-hard-links).

I stopped the file copy, lemme update with corresponding file sizes

**Comment by Sebaex** [comment]
Pictures updated

Regarding the link info
>On other operating systems and filesystems where hard links are not available (or the functionality to create them has not been implemented yet)

Isn't implemented yet for Windows?
Also, drive formatted as NTFS as shown here

![explorer_yE5T28zgEI](https://github.com/ppy/osu/assets/22472487/25f8daf6-e3c7-4a3e-bfc1-ed607c2b8c98)

**Comment by agatemosu** [comment]
<https://osu.ppy.sh/wiki/en/Client/Release_stream/Lazer/File_storage#:~:text=Note%20that%20if,after%20the%20migration.> this paragraph

**Comment by agatemosu** [comment]
<https://osu.ppy.sh/wiki/en/Client/Release_stream/Lazer/File_storage#:~:text=Note%20that%20if,after%20the%20migration.> this paragraph
