### ISSUE TITLE
Game crash after tap the tablet with the pen outside the osu window

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#24463]
### Type

Crash to desktop

### Bug description

When I tap the tablet with the pen outside from osu!lazer windows, lazer will pop a notification that `An unhandled error has occurred.` then crash.

maybe because `ButtonDownInputQueue` is null?

https://github.com/ppy/osu-framework/blob/master/osu.Framework/Input/ButtonEventManager.cs#L98

### Version

commit 270c03235d

### Logs

Release build
[runtime.log](https://github.com/ppy/osu/files/12260239/runtime.log)

Debug build which has Assertion Exception
[runtime.log](https://github.com/ppy/osu/files/12260241/runtime.log)

**Comment by bdach** [comment]
> maybe because `ButtonDownInputQueue` is null?

you're literally posting a debug log that trips the assertion that confirms that, so i don't know why this is a question

**Comment by cdwcgt** [comment]
because I don't know why this will be null.😟
