### ISSUE TITLE
Osu! Tablet Raw Input problem

### ISSUE THREAD

**Issue by MathhyOsu** [ppy/osu#2448]
I have a problem with my Wacom Tablet in Osu!

When I change my projektion in the tablet Options, the pen projektion in Osu also get smaller, but only for the pen. I don't know how to fix the problem. 
I using windows 7.

![screenshot104](https://user-images.githubusercontent.com/38697326/39197140-13921714-47e4-11e8-9072-2cbbf6bbdbc2.jpg)
![screenshot_6](https://user-images.githubusercontent.com/38697326/39197189-34b55294-47e4-11e8-933b-325f010799d4.png)

**Comment by LittleEndu** [comment]
This a repository is for osu!lazer development. If you need help setting up your tablet for osu!stable, you need to ask that in the osu! forums.
