### ISSUE TITLE
Storyboard way too bright compared to stable on specific map

### ISSUE THREAD

**Issue by bdach** [ppy/osu#24480]
### Discussed in https://github.com/ppy/osu/discussions/24471

<div type='discussions-op-text'>

<sup>Originally posted by **hachuyenden** August  6, 2023</sup>
This is beatmap: https://osu.ppy.sh/beatmapsets/234935#osu/545304
The problem of the effect being pinned continuously in Lazer leads to glare like the video below, compared to the stable version

https://github.com/ppy/osu/assets/128424762/9d80db37-4c03-440a-985d-0a354143a846

The dimming here is set to 65% but it's still quite blinding, I don't know if other beatmaps with a similar effect suffer.

</div>

**Comment by Coppertine** [comment]
Going to chime in after checking the osb.
It seems that it's a case of Triggers not being implemented and therefore all additive `bright.jpg` are kept on screen. (otherwise known as #2084 )
Here are all of the `bright.jpg` sprites that affect this bug.
```
Sprite,Foreground,Centre,"SB\bright.jpg",320,240
 P,0,0,138958,A
 S,0,15,,1
 T,HitSoundFinish,0,137700
  F,1,0,1200,1,0
  S,1,0,1200,1,1.05
Sprite,Foreground,Centre,"SB\bright.jpg",320,240
 P,0,0,57139,A
 S,0,15,,1
 T,HitSoundWhistle,17070,23783
  F,1,0,1200,0.3,0
Sprite,Foreground,Centre,"SB\bright.jpg",320,240
 P,0,0,138958,A
 S,0,15,,1
 T,HitSoundClap,23783,43503
  F,1,0,1000,0.4,0
 T,HitSoundClap,90077,97209
  F,1,0,1000,0.4,0
 T,HitSoundClap,110636,138958
  F,1,0,1000,0.5,0
Sprite,Foreground,Centre,"SB\bright.jpg",320,240
 P,0,0,138958,A
 S,0,15,,1
 T,HitSoundWhistle,43503,58818
  F,1,0,1200,0.3,0
 T,HitSoundWhistle,83993,90077
  F,1,0,1200,0.3,0
  ```

**Comment by bdach** [comment]
Thanks, closing as duplicate.
