### ISSUE TITLE
Scores are not submitting

### ISSUE THREAD

**Issue by kajxqeirscl** [ppy/osu#24502]
### Type

Game behaviour

### Bug description

None of my scores today are submitting. I don't know what is causing this. Is there some maintenance going on?

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/75833519/7f01d9f3-91f2-4dd9-9251-19e911270cea)
![image](https://github.com/ppy/osu/assets/75833519/b2ce16f2-8fcf-4f3f-a64d-5dc2c9dd4e52)
![image](https://github.com/ppy/osu/assets/75833519/a19f687f-5dbd-4335-a685-6bfbc9171402)

### Version

2023.803.0

### Logs

[database.log](https://github.com/ppy/osu/files/12324254/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12324255/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12324256/network.log)
[performance.log](https://github.com/ppy/osu/files/12324257/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12324258/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12324259/updater.log)

**Comment by kajxqeirscl** [comment]
I was connected to the internet the whole time. No issues regarding that.

**Comment by bdach** [comment]
We've identified an issue with score processing, The relevant server component was restarted, new scores should be hopefully processing fine. As for past scores that are stuck, please give us 24-48 hours to catch up.

We'll keep this open until the issue is fully mitigated.

**Comment by bdach** [comment]
Update: Background reprocessing is currently being run on scores from the past 3 months or so, and it should conclude within the next 12 hours.

**Comment by peppy** [comment]
Should have finished. @kajxqeirscl please report back if any of your scores are still in a weird state. They should have all been reprocessed now.
