### ISSUE TITLE
Stable replays do not snake sliders out

### ISSUE THREAD

**Issue by SherlockWh0** [ppy/osu#24512]
### Type

Cosmetic

### Bug description

I was watching a replay of [this map](https://osu.ppy.sh/beatmapsets/1071189#osu/2242173) when I noticed "snaking out sliders wasn't working. I checked a lazer auto replay, and it snaked out fine. Either I am an idiot and this is intentional, or this is an oversight.

### Screenshots or videos

Stable replay:
<img width="1440" alt="Screenshot 2023-08-12 at 11 13 03" src="https://github.com/ppy/osu/assets/107404453/9b539c49-050b-4c14-82ee-24c13e43e245">
Lazer replay:
![Screenshot 2023-08-12 at 11 15 24](https://github.com/ppy/osu/assets/107404453/04120b2b-19f3-4e88-ab2e-5f655bc03e03)

### Version

2023.811.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12326119/database.log)
[input.log](https://github.com/ppy/osu/files/12326120/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12326121/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12326122/network.log)
[performance-draw.log](https://github.com/ppy/osu/files/12326123/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/12326124/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/12326125/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12326126/runtime.log)

**Comment by peppy** [comment]
classic mod is applied, expected
