### ISSUE TITLE
Mixed sound playback in the song menu

### ISSUE THREAD

**Issue by eynu** [ppy/osu#24525]
### Type

Other

### Bug description

This is the text written with a translator. If you have any reading difficulties, please understand.

As long as I repeatedly switch songs while selecting them, the songs will mix and play.

### Screenshots or videos

https://github.com/ppy/osu/assets/142105290/ab06fb9d-70f5-4ac4-b7f8-8c0f7599fb10

### Version

2023.812.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12327664/database.log)
[input.log](https://github.com/ppy/osu/files/12327665/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12327666/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12327667/network.log)
[performance.log](https://github.com/ppy/osu/files/12327668/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12327669/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12327670/updater.log)

**Comment by bdach** [comment]
#24519
