### ISSUE TITLE
Every tick of the metronome will cause the game to freeze briefly

### ISSUE THREAD

**Issue by RBQcat** [ppy/osu#24521]
### Type

Performance

### Bug description

It can be seen in the video that each tick of the metronome will cause the game to freeze briefly
It seems that the longer the beatmap, the more serious the problem
Beatmaps used in the video: https://osu.ppy.sh/beatmapsets/972#osu/9007 | https://osu.ppy.sh/beatmapsets/2459#osu/19753

### Screenshots or videos

https://github.com/ppy/osu/assets/74862110/0c8f67e0-cacb-492a-a31c-4d081ffdd189

https://github.com/ppy/osu/assets/74862110/8e35e12e-8ed2-4909-a7b0-12473f427e39

### Version

2023.812.0

### Logs

[database.log](https://github.com/ppy/osu/files/12327472/database.log)
[runtime.log](https://github.com/ppy/osu/files/12327473/runtime.log)
[performance.log](https://github.com/ppy/osu/files/12327475/performance.log)
[network.log](https://github.com/ppy/osu/files/12327476/network.log)

**Comment by longnguyen2004** [comment]
Taken to the extreme, Hello (BPM) 2022 is extremely laggy

![image](https://github.com/ppy/osu/assets/15729831/d924562f-a326-462d-affc-6b371eb3cad5)

**Comment by bdach** [comment]
#20918

**Comment by RBQcat** [comment]
> #20918

I don't think this issue is related to #20918, if beatmaps have only one time point it will also cause stuttering

**Comment by bdach** [comment]
@RBQcat then please attach a video of this showing with one time point rather than the tens or hundreds the maps in OP have. preferably also with frame graph enabled (ctrl-f11 twice).

**Comment by RBQcat** [comment]
https://github.com/ppy/osu/assets/74862110/f2070cdf-7dea-4eea-a93c-d4d69abb2c73

In addition, I found that Caton appears after the waveform image is loaded

**Comment by Lunarien** [comment]
The metronome causes that UI component to update, which results in an assumption that the metronome might be the cause, but the cause is probably what the metronome affects.

**Comment by RBQcat** [comment]
Fixed by https://github.com/ppy/osu-framework/pull/6009
