### ISSUE TITLE
Mania HoldOff mod generates very unnatural gameplay

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#24551]
### Type

Game behaviour

### Bug description

The hold off mod generates a note for both the start _and_ end of a hold note, which ends up as difficult-to-hit jacks. One map this can be seen on is https://osu.ppy.sh/beatmapsets/1252675#mania/2603455.

The solution is simple, but I want to make sure people agree with this before I change it, and to note that I don't know how we can preserve old scores (probably irrelevant since we're going to have a score reset?).

### Version

latest

### Logs

-

**Comment by Kominaru** [comment]
Just to help confirm, simply leaving the *start* of the note (not converting the *end* into a note) is what virtually everyone that plays the o!m will expect from this mod. 

Currently, no-holdnote edits of existing maps (e.g. as en edited map version for tournament usage) are done precisely that way
