### ISSUE TITLE
Changing beat snap divisor or slider control point types can produce a zero-length slider

### ISSUE THREAD

**Issue by Pasi4K5** [ppy/osu#24559]
### Type

Game behaviour

### Bug description

Messing around with the beat snap divisor and slider control points can produce a slider with 0 length/duration.

![image](https://github.com/ppy/osu/assets/47356629/04642f3f-31ee-403b-a977-713c71a1eb08)

## Steps to reproduce
There are 2 methods for reproducing this (both are shown in the video):
### 1. Using the beat snap divisor
1.1. Set a high beat snap divisor (like 1/16).
1.2. Place a *very short* slider.
1.3. Set a low beat snap divisor (like 1/1).
1.4. "Wiggle" any of the control points.
### 2. Using slider control point types
2.1. Set a low beat snap divisor (like 1/1).
2.2. Place a "Perfect curve" slider with the smallest possible radius
2.3. Change the first or second control point type ("Linear" probably works best).
2.4. "Wiggle" any of the control points.

### Screenshots or videos

https://github.com/ppy/osu/assets/47356629/032b0859-8d3e-4110-9c55-da05b23b8d7a

### Version

2023.815.0-lazer (latest release)

### Logs

[performance.log](https://github.com/ppy/osu/files/12353548/performance.log)
[updater.log](https://github.com/ppy/osu/files/12353549/updater.log)
[database.log](https://github.com/ppy/osu/files/12353550/database.log)
[runtime.log](https://github.com/ppy/osu/files/12353551/runtime.log)
[input.log](https://github.com/ppy/osu/files/12353552/input.log)
[network.log](https://github.com/ppy/osu/files/12353553/network.log)

**Comment by OliBomby** [comment]
related #10959

**Comment by peppy** [comment]
I think this could almost be closed as a duplicate.
