### ISSUE TITLE
Image not scaled down in beatmap comment section

### ISSUE THREAD

**Issue by Aksumxd** [ppy/osu#24569]
### Type

Cosmetic

### Bug description

Comment in osu lazer browser

![Qlufwkr](https://github.com/ppy/osu/assets/63202855/8e3b2b23-9272-4f5b-a09f-7389ac8dfb8a)
Comment on the website

![nXMaJy1](https://github.com/ppy/osu/assets/63202855/41859c77-f179-490e-9d68-8ab302b93006)

Comment section: **https://osu.ppy.sh/beatmapsets/1512813#osu/3103322**

### Version

osu! 2023.815.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12359197/database.log)
[input.log](https://github.com/ppy/osu/files/12359198/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12359199/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12359200/network.log)
[performance.log](https://github.com/ppy/osu/files/12359201/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12359202/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12359203/updater.log)

**Comment by Fabiano1337** [comment]
This is probably due to the ParagraphBlock not having a max image size in CommentMarkdownContainer.
I haven't really worked with Markdig yet so i'll let someone else handle this
