### ISSUE TITLE
Accuracy Calculation Discrepancy

### ISSUE THREAD

**Issue by XinthePanda** [ppy/osu#24579]
### Type

Game behaviour

### Bug description

On this map: https://osu.ppy.sh/beatmapsets/1263883#osu/4243843

Set a FC with DT 2.00x (116 Great, 3 OK, 0 Meh, 0 Miss, all slider tick & ends) and received an accuracy of 98.38%.
Another player set an FC with HR + DT + Classic (116 Great, 3 OK, 0 Meh, 0 Miss, all slider tick & ends) and received an accuracy of 98.47%.

Wouldn't the 2 plays have the exact same accuracy?

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/85714155/b348b225-5c0e-4be1-a06b-309846e484ed)
![image](https://github.com/ppy/osu/assets/85714155/503651a6-6719-4c13-9693-f223a714982e)

### Version

2023.815.0

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/12373202/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12373203/network.log)
[performance.log](https://github.com/ppy/osu/files/12373204/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12373205/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12373206/updater.log)
[database.log](https://github.com/ppy/osu/files/12373207/database.log)
[input.log](https://github.com/ppy/osu/files/12373208/input.log)

**Comment by plaguemask** [comment]
> Wouldn't the 2 plays have the exact same accuracy?

No. Classic mod fundamentally changes the nature of sliders, including with how accuracy is calculated. Comparing the statistics of a play with classic mod to the statistics of one without classic mod is comparing apples to oranges.

**Comment by XinthePanda** [comment]
That sounds quite abusable with the current scoring algorithm...

**Comment by peppy** [comment]
Classic mod is not comparable to plays without it.
