### ISSUE TITLE
osu! freezes within a beatmap

### ISSUE THREAD

**Issue by MinecraftPlaye** [ppy/osu#2457]
Hi there,

I just tested out osu lazer for a bit and came across some freezes in which
the whole screen freezes for a second or more in the normal osu mode. 

I don't know what's causing the issue, maybe something with the
database (?) as I had a few errors importing my beatmaps.

Windows 10 (1709, x64)
Intel Core i7 6800k
Readon RX Vega 64 (driver: 18.3.4)
osu version: 2018.423.0 using a guest account

I hope those [logs](https://github.com/ppy/osu/files/1949392/logs.zip) help to fix the
bug and get one step closer to a stable osu lazer release. ;)
(I just put in all logs from the whole session... Performance logging features got enabled after I first noticed the problem)

**Comment by MinecraftPlaye** [comment]
I tested it again with the new version of osu!lazer and the problem occured again.

Version: 2018.502.0
[log files](https://github.com/ppy/osu/files/1969229/logs_2.zip)

**Comment by MinecraftPlaye** [comment]
Tested again with version 2018.606.0 and the problem still persits while only testing 2 beatmaps with my mouse and keyboard instead of some intense test with my graphics tablet (Wacom Intuos Pro) and my osu keyboard.

Version: 2018.606.0
Readon RX Vega 64 (driver: 18.5.1)

[log files](https://github.com/ppy/osu/files/2078529/logs3.zip)

**Comment by peppy** [comment]
Could you please turn on performance logging in settings, make it happen again and attach all performance logs once more?

![image](https://user-images.githubusercontent.com/191335/41095503-8aaa54fe-6a8c-11e8-95ae-0043ab6c0370.png)

**Comment by MinecraftPlaye** [comment]
@peppy I just tested it again and the problem persists:

Version: 2018.611.0
Readon RX Vega 64 (driver: 18.5.1)

[log files and settings](https://github.com/ppy/osu/files/2091371/osu_2.zip)

**Comment by MinecraftPlaye** [comment]
@peppy Applies still to osu!lazer 2018.712.0 after I've did a test with 3 shorter beatmaps:

[log and setting files](https://github.com/ppy/osu/files/2190623/logs3.zip)

**Comment by MinecraftPlaye** [comment]
@peppy I tested it again, but with another graphics card to make sure it's not my graphics card and
this problem also applies to osu!lazer build 2018.722.0.

Version: 2018.712.0
Readon RX 480 (driver: 18.6.1)

Thus it happens with the same driver and a different graphics card and a newer game version again.
Debug features like the performance logging have been turned on!

[log and setting files](https://github.com/ppy/osu/files/2217417/logs.zip)

**Comment by MinecraftPlaye** [comment]
@peppy What do you mean by hard lock?
Well, I'm just testing once in a while osu! lazer builds. While playing I notice these freezes of the screen (music still playing). After such a freeze happens I still play on a bit (and often notice a few more freezes) before I close the game manually via the exit button.
Some of these freezes are also smaller while other's seem to take longer for some reason or another.
Well, I suppose capturing this on video will be easier than taking a screenshot, but I'll give it a try.

**Comment by MinecraftPlaye** [comment]
@peppy I would like to capture the problem, but AMD ReLive isn't able to capture the osu!lazer client. Enabling desktop capture (to ensure it's not a problem with ReLive doens't recognize osu as a Game) does also not resolve the problem. As of this I am currently not able to capture the problem.

**Comment by ThatFreakGameTV** [comment]
Hi everyone I have a massive problem with my osu! while loading in to play a beatmap it just froze and i cant quit it this is what i see right now 
![Screen Shot 2019-06-22 at 9 26 20 am](https://user-images.githubusercontent.com/52089282/59955971-a0006680-94d0-11e9-8415-88b1cc7a64e8.png) and it's been happening the past 2 days, i want to play the game can someone plz help me? :(

**Comment by iiSaLMaN** [comment]
@ThatFreakGameTV 
first of all, everything here is directly related to osu!lazer
second, you can email that to peppy (pe@ppy.sh) if you want help on stable (osu!)

**Comment by HoLLy-HaCKeR** [comment]
I'm pretty sure bugs like that should be reported on the forum instead. @ThatFreakGameTV try reinstalling the game and then properly file a bug report.

**Comment by peppy** [comment]
Closing as most-likely-fixed. Performance has been improved several magnitudes since this report.
