### ISSUE TITLE
mania playfield skin elements scale with field width

### ISSUE THREAD

**Issue by dwRchyngqxs** [ppy/osu#24597]
### Type

Cosmetic

### Bug description

Elements attached to the mania playfield scale with key count. This makes the element really big on 8k or really small on 4k.

### Screenshots or videos

![osu_2023-08-20_16-38-56](https://github.com/ppy/osu/assets/12198691/649c4f25-467e-4e8d-91b4-abceeb399947)
![osu_2023-08-20_16-39-16](https://github.com/ppy/osu/assets/12198691/d83ec0fe-1824-4fe2-996a-b4cfa4fc2c6e)

### Version

2023.815.0-lazer

### Logs

Irrelevant but here they are 
[database.log](https://github.com/ppy/osu/files/12388548/database.log)
[input.log](https://github.com/ppy/osu/files/12388549/input.log)
[network.log](https://github.com/ppy/osu/files/12388550/network.log)
[performance.log](https://github.com/ppy/osu/files/12388551/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12388553/runtime.log)

**Comment by bdach** [comment]
#24388

**Comment by peppy** [comment]
Trust that it's related. Because you have a 90 degree rotated health bar, it is getting the incorrect scaling axis applied to it (usually it would make sense if not rotated).
