### ISSUE TITLE
Beatmap card on Tournament Client disappears when osu!tourney is on the main menu and a song ends

### ISSUE THREAD

**Issue by Trosk** [ppy/osu#24598]
### Type

Game behaviour

### Bug description

The beatmap card on the bottom right corner sometimes disappears when a song ends. This doesn't always happen, but I'm 100% sure this wasn't a thing in older versions.

Sometimes it just changes the beatmap card to a different one for half a second when osu!tourney is reloading the beatmap and then goes back to the one it's supposed to be showing. 

The beatmap card reappears when a different beatmap is selected on the MP room you are spectating on osu!tourney.

### Screenshots or videos

https://clips.twitch.tv/PatientMistyKleeSpicyBoy-7RQKpEPpHTauYo4T

### Version

2023.815.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/12389030/runtime.log)
[performance.log](https://github.com/ppy/osu/files/12389031/performance.log)

**Comment by peppy** [comment]
@Trosk is this something new since a recent update, or something that has happened for months+?

**Comment by Trosk** [comment]
@peppy I've never seen it disappear like that before, and it's happened twice this weekend, so it probably only started happening recently

**Comment by peppy** [comment]
@Trosk i don't suppose you happen to have `network.log` saved from one of these occurrences? It's looking to me like a request may have failed somehow..

**Comment by peppy** [comment]
Closing this one for now as I think it might be fixed by the linked PR.
