### ISSUE TITLE
Settings text box should clear (or select) previous search when opening

### ISSUE THREAD

**Issue by peppy** [ppy/osu#24606]
Probably the latter, probably depending on https://github.com/ppy/osu-framework/pull/5823.

### Discussed in https://github.com/ppy/osu/discussions/24470

<div type='discussions-op-text'>

<sup>Originally posted by **rszyma** August  6, 2023</sup>
It's annoying that literally *every time* I press Ctrl+O I have clear the previous search! If you don't want to make this behavior default at least make it optional. Or at the *very least* clear it after user have not entered settings for a minute or so. Please!</div>

**Comment by frenzibyte** [comment]
There are many other places where `SearchTextBox` is used, and probably should have a behaviour similar to this.
