### ISSUE TITLE
Clicking on the reset to default button located next to a slider will not properly call functions from other components

### ISSUE THREAD

**Issue by AlFasGD** [ppy/osu#2460]
Specifically, in the playback settings dialog while watching a replay, after changing the slider's value to a non-default one, the small button that appears will reset the value to the default one, without changing the label's text to the new value, even if any value adjustments will make it change normally.

This happens with every other component that extends `Bindable` and calls the `SetDefault()` function. I don't know why this is caused, even calling `TriggerValueChanged()` in the `SetDefault()` function itself doesn't fix it (not that there would be any reason for it to work).

**Comment by peppy** [comment]
This must be a regression as it used to work correctly.
