### ISSUE TITLE
Local scores shows other person profile picture and flags

### ISSUE THREAD

**Issue by floccini** [ppy/osu#24624]
### Type

Cosmetic

### Bug description

After importing a offline score from stable that has, let's say, "mrekk" as its player name, when logging into Lazer and seeing the local leaderboard, the game shows mrekk profile picture and flag as he was the one that originally set the score, even tho it was a offline score.

I noticed that after importing my scores using the setup wizard, that's when I noticed the local score confused a local score of mine in this same map with the name "gigi", with the player GIGI. The same happened when I imported this single "mrekk" replay into lazer.

![image](https://github.com/ppy/osu/assets/55555174/da98239a-7203-486a-8bf1-fa115a34128a)

### Version

2023.815.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12413101/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12413102/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12413103/updater.log)
[database.log](https://github.com/ppy/osu/files/12413104/database.log)
[input.log](https://github.com/ppy/osu/files/12413105/input.log)
[network.log](https://github.com/ppy/osu/files/12413106/network.log)

**Comment by peppy** [comment]
Not sure what you're hoping for. Are you saying you set a local score and used the username "mrekk" and expect it to show no avatar because it was your local score?

**Comment by floccini** [comment]
Yes, it is something that i am used to since I came from stable, and I really don't know if that is supposed to be like that.
It can be quite misleading seeing another's player pfp/flag in your local score, at least that's a opinion I heard from a few people  after showing this, since in stable you can't see that and it is normal for people to use a random username while playing offline. I noticed that on lazer you can't change your username while offline so it might be a way to fix it, but the problem here is only the imported scores, and since a lot of people will certainly use the import tool, I do think it will be confusing for a lot of them.

**Comment by Pants** [comment]
To add to this:
If you've changed your username in the past and someone else took your old username, your older scores will show the other person's profile picture and country flag.

**Comment by bdach** [comment]
Yes. There is nothing we can do about that. Old replays have no other means of identifying the player than the username.

**Comment by peppy** [comment]
Going to bump this in priority. The longer we wait on this the more people are going to have issues due to username changes etc.
