### ISSUE TITLE
Possible difference between lazer and stable in input handling with overlapping sliders

### ISSUE THREAD

**Issue by bdach** [ppy/osu#24626]
### Type

Game behaviour

### Bug description

Discovered during investigation into https://github.com/ppy/osu/pull/24280.

[TestOverlappingSliders2.zip](https://github.com/ppy/osu/files/12416268/TestOverlappingSliders2.zip) contains a beatmap and a replay on that beatmap. When said replay is played back on said beatmap on stable, different results ensue than when it is played back on lazer.

### Screenshots or videos

lazer does this:

https://github.com/ppy/osu/assets/20418176/9c3cf738-9c02-4124-b6f5-bea1cd6cedf6

stable does this:

https://github.com/ppy/osu/assets/20418176/5ece1faa-e7b7-4513-8b1b-b616c0dd592b

https://github.com/ppy/osu/pull/24280 does not fix this and this particular issue does not appear to be notelock-related, going by the below log excerpt extracted from stable:

```
2023-08-23T07:05:01: Player.onGamePress: on object osu.GameplayElements.HitObjects.Osu.SliderOsu (start time = 1000), at time 1000, note lock decided to Hit
2023-08-23T07:05:01: Player.onGamePress: on object osu.GameplayElements.HitObjects.Osu.SliderOsu (start time = 1000), at time 1025, note lock decided to Hit
2023-08-23T07:05:01: Player.onGamePress: on object osu.GameplayElements.HitObjects.Osu.SliderOsu (start time = 1000), at time 1200, note lock decided to Hit
2023-08-23T07:05:01: HitObjectManager.Hit: osu.GameplayElements.HitObjects.Osu.SliderOsu judged as Hit300 @ 1251 (offset 251)
2023-08-23T07:05:01: HitObjectManager.Hit: osu.GameplayElements.HitObjects.Osu.HitCircleSliderStart judged as MissHpOnly @ 1401 (offset 201)
2023-08-23T07:05:01: HitObjectManager.Hit: osu.GameplayElements.HitObjects.Osu.SliderOsu judged as Hit100k @ 1451 (offset 251)
```

Seems like the first slider is possiblky blocking input for the second slider despite undergoing judgement?

### Version

master

### Logs

n/a

**Comment by bdach** [comment]
Yeah, the same thing happens with just B1. Here's a variant of that replay that only does the single click: 
[TestOverlappingSliders2a.zip](https://github.com/ppy/osu/files/12416400/TestOverlappingSliders2a.zip)

And the playback result:

https://github.com/ppy/osu/assets/20418176/1d75f3a5-943c-4a26-8c6f-52585f09d175

**Comment by peppy** [comment]
Probably best to test with single button in that case, just to keep things simple.

**Comment by peppy** [comment]
@smoogipoo also curious on your thoughts here. do we match the stable anti-user behaviour for now just to keep things in parity?

**Comment by peppy** [comment]
Unless I'm misunderstanding something, in stable the second click is not activating the slider head of the second (underlapping) slider while it is in lazer. In which case, the lazer implementation looks more correct?

That said, I haven't noticed stable behaving in the way shown in the video in maps like marisa, so may need further clarification..

**Comment by bdach** [comment]
> Isn't it an issue if the sliders are more offset than shown in the video, such that pressing one slider will miss the head of the one underneath it?

So spacing them further gets... weird...

Here's a test case: [TestOverlappingSliders3.zip](https://github.com/ppy/osu/files/12417628/TestOverlappingSliders3.zip)

```csharp
        [Test]
        public void TestOverlappingSliders3()
        {
            const double time_first_slider = 1000;
            const double time_second_slider = 1300;
            Vector2 positionFirstSlider = new Vector2(100, 50);
            Vector2 positionSecondSlider = new Vector2(100, 80);
            var midpoint = (positionFirstSlider + positionSecondSlider) / 2;

            var hitObjects = new List<OsuHitObject>
            {
                new Slider
                {
                    StartTime = time_first_slider,
                    Position = positionFirstSlider,
                    Path = new SliderPath(PathType.Linear, new[]
                    {
                        Vector2.Zero,
                        new Vector2(25, 0),
                    })
                },
                new Slider
                {
                    StartTime = time_second_slider,
                    Position = positionSecondSlider,
                    Path = new SliderPath(PathType.Linear, new[]
                    {
                        Vector2.Zero,
                        new Vector2(25, 0),
                    })
                }
            };

            performTest(hitObjects, new List<ReplayFrame>
            {
                new OsuReplayFrame { Time = time_first_slider, Position = midpoint, Actions = { OsuAction.RightButton } },
                new OsuReplayFrame { Time = time_first_slider + 25, Position = midpoint, Actions = { OsuAction.LeftButton } },
                new OsuReplayFrame { Time = time_first_slider + 50, Position = midpoint },
            });

            addJudgementAssert(hitObjects[0], HitResult.Ok);
            addJudgementAssert(hitObjects[1], HitResult.Miss);
            addClickActionAssert(0, ClickAction.Hit);
            addClickActionAssert(1, ClickAction.Hit);
        }
```

On lazer master, this happens:

https://github.com/ppy/osu/assets/20418176/cff32bb5-384c-4359-9f54-ddd04cf4e024

i.e. the second slider head does head eagerly missed due to being clicked under the first slider.

With fixes from https://github.com/ppy/osu/pull/24280, note lock gets involved:

https://github.com/ppy/osu/assets/20418176/0bb4c7ce-9f60-48aa-9e1e-75d254c6960f

The second slider head is not activated by the second click because note lock prevents it from happening. See: shake.

On stable this happens:

https://github.com/ppy/osu/assets/20418176/e2fb4255-d4d4-4d6a-95b0-011c5338d79c

There's no shake here, and log output indicates that the second slider is missed, but only _after it's been fully ignored_:

```
2023-08-23T09:27:34: Player.onGamePress: on object osu.GameplayElements.HitObjects.Osu.SliderOsu (start time = 1000), at time 1000, note lock decided to Hit
2023-08-23T09:27:34: Player.onGamePress: on object osu.GameplayElements.HitObjects.Osu.SliderOsu (start time = 1000), at time 1025, note lock decided to Hit
2023-08-23T09:27:34: HitObjectManager.Hit: osu.GameplayElements.HitObjects.Osu.SliderOsu judged as Hit100 @ 1250 (offset 250)
2023-08-23T09:27:34: HitObjectManager.Hit: osu.GameplayElements.HitObjects.Osu.HitCircleSliderStart judged as MissHpOnly @ 1501 (offset 201)
2023-08-23T09:27:34: HitObjectManager.Hit: osu.GameplayElements.HitObjects.Osu.SliderOsu judged as Miss @ 1550 (offset 250)
```

Note that note lock was handled by _the first slider on both clicks_, which would confirm the hypothesis that clicked slider heads will handle clicks over objects underneath them.

**Comment by peppy** [comment]
I'd like to see this objectively broken behaviour fixed in lazer. ie. all these situations should get 100% and activate the second slider.

As for how we make that work for backwards compatibility (re-break it in classic mod? just decide it's not worth implementing such a broken thing) needs discussion.

**Comment by bdach** [comment]
> As for how we make that work for backwards compatibility (re-break it in classic mod? just decide it's not worth implementing such a broken thing) needs discussion.

With my pending changes for stable-like notelock in classic (https://github.com/ppy/osu/pull/24280), it would kinda "break again" in classic mod, just with a shake rather than completely no response like stable does, as per videos above. If you're ok with that then we could leave that at that and be done with it until someone complains.

Failing that I could try to invent some new condition to make classic notelock somehow ignore such clicks but I'm generally quite reluctant to that if I'm honest.

**Comment by peppy** [comment]
I think that's fine. Is it safe to assume that without classic mod applied it works fine with 100% as per the earlier videos in this thread?

**Comment by smoogipoo** [comment]
Just so we're on the same page... When two sliders are stacked and you're pressing squarely on the top one, you expect input from the second keypress to fall through to the one below it? But if circles are stacked underneath that top slider, you don't expect input to fall through?

**Comment by peppy** [comment]
> Just so we're on the same page... When two sliders are stacked and you're pressing squarely on the top one, you expect input from the second keypress to fall through to the one below it? But if circles are stacked underneath that top slider, you don't expect input to fall through?

If the slider head is hit already, I'd expect input to fall through in all cases (circle or slider).

**Comment by bdach** [comment]
> I think that's fine. Is it safe to assume that without classic mod applied it works fine with 100% as per the earlier videos in this thread?

Yes, with "new note lock" active (`StartTimeOrderedHitPolicy`) a slider head under an earlier slider can be triggered if the prior slider's head was hit. Video:

https://github.com/ppy/osu/assets/20418176/b1c0b6b2-3f63-4243-959d-f34a5c7417f9

If there's agreement that that is correct behaviour (which, it might not be judging from the comment above), I can PR that as extra test coverage.

**Comment by smoogipoo** [comment]
> If the slider head is hit already, I'd expect input to fall through in all cases (circle or slider).

Hmmm... Might be okay. I can't think of a map to bring up as an example right now that could be tested, as circle-slider stacks are usually circle-slider and not slider-circle.

**Comment by GuineaGuy99** [comment]
I know I'm a little late but I think I have a year old clip demonstrating this issue, maybe a good time to share?

I missed because I tapped with two fingers, but stable never punished doing this. I still have a lot of stable muscle memory and missing the slider I was not aiming for was quite frustrating at the time (and I was playing with classic mod).

https://www.youtube.com/watch?v=YZlteNz8URk

**Comment by bdach** [comment]
@GuineaGuy99 if you are able, you can playtest the linked PR, or check that it fixes replay playback on this particular replay to confirm this is fixed for you.

**Comment by GuineaGuy99** [comment]
I managed to [find the replay](https://cdn.discordapp.com/attachments/773067328283082755/1149991424381685851/GuineaGuy99_playing_Yousei_Teikoku_-_Paradiso_Inferno_IsomirDiAngelo_Insane_2022-08-27_01-43.osr), unfortunately it seems I misremembered a key-detail. The map was part of a playlist so I did not pick the mods, and the classic mod actually had `(No slider head accuracy requirement: off, Apply classic note lock: off, Always play a slider's tail sample: off)` applied. This was over a year ago so sorry for misremembering. It may not be as relevant to the PR however I still think the clip is a good example of a scenario where the overlapping slider behavior in lazer differs from stable.

Weirdly when importing the replay into my main lazer install or the linked PR, the classic mod disappears entirely leaving it as only a HR play. The part where I tap with both fingers and miss is still in the replay so I think if you could somehow force classic to always be on in the dev build or modify the replay file to re-include classic, then it might be useful for testing? I'm not familiar enough with lazer to try these things myself so if you're interested I linked the replay file. The map was [Paradiso=Inferno](https://osu.ppy.sh/beatmapsets/1296273#osu/2689510).

Not really related to the issue but to my amusement the original play had two misses (0:15 and 0:17 in the youtube video) but after watching the HR only replay the 2nd miss actually counted as a "Great", I assume it's because I overshot and without classic mod the slider head actually moved under my cursor? So the replay says 2 misses on the map select screen but after watching the replay the results screen says 1 miss. Interesting.

**Comment by bdach** [comment]
@GuineaGuy99 I'm really only interested in accurately representing classic note lock, so sorry but the replay you're linking is out of scope for now.

The remaining issues you mention are either caused by the replay being too old or are out of scope of this issue.
