### ISSUE TITLE
Lazer replays downloaded from lazer.ppy.sh show score as 0 inside lazer

### ISSUE THREAD

**Issue by bdach** [ppy/osu#24643]
### Discussed in https://github.com/ppy/osu/discussions/24638

<div type='discussions-op-text'>

<sup>Originally posted by **Theighlin** August 24, 2023</sup>
Tried on 2 different beatmaps, one is 
https://lazer.ppy.sh/beatmapsets/1856043#osu/3814127
![image](https://github.com/ppy/osu/assets/53081750/e0522a39-cfee-4a0f-936b-e789ec57c2ce)
with this score (https://lazer.ppy.sh/scores/2399877639)
![image](https://github.com/ppy/osu/assets/53081750/dcaea82a-4e98-42ba-8537-29273afa4c60)
Shows like this in game (Acc also changes upon importing?)
![image](https://github.com/ppy/osu/assets/53081750/378e36a7-f9e4-4e7b-982a-cda64a966ec7)

[database.log](https://github.com/ppy/osu/files/12425914/database.log)
[runtime.log](https://github.com/ppy/osu/files/12425915/runtime.log)

</div>

**Comment by peppy** [comment]
The comment was from before total score was simple and included, and had to be locally calculated. The fix you propose seems correct to my eyes.

**Comment by Theighlin** [comment]
Not sure it's up to me, but if this is still open because there are scores still with 0, it's fine to close, I don't think it's important to act on those.

**Comment by bdach** [comment]
Yeah I think this is closeable.

**Comment by Lemmmy** [comment]
Not sure if it's related to this or a separate issue (I can make one if needed), but seeing a lot of 0-point scores on leaderboards. I did originally see three or four plays with nonzero scores but after reloading they're all zero now. 
![image](https://github.com/ppy/osu/assets/858456/2f627604-13a0-495b-bbb0-a1abd436533d)
![image](https://github.com/ppy/osu/assets/858456/f4461cbc-9365-4bc7-8677-59dcc6a0f885)
![image](https://github.com/ppy/osu/assets/858456/965c38f3-a0ca-48f4-aea8-6cdaea7ad995)

**Comment by peppy** [comment]
Please open a new issue
