### ISSUE TITLE
Able to play 2 songs simultaneously on osu!direct

### ISSUE THREAD

**Issue by Glasses-are-90-me** [ppy/osu#2465]
You can click on the play button on one of the main view and quickly click into another song description and play another song over the other.

First playing
![image](https://user-images.githubusercontent.com/17042136/39364817-8a2805ec-4a72-11e8-8e75-b495b4a279d5.png)
Second Playing
![image](https://user-images.githubusercontent.com/17042136/39364840-a6b1b7b2-4a72-11e8-80f0-91cbcf223050.png)

**Comment by UselessToucan** [comment]
Looks similar to #2344 . I guess it's time to find a global solution for this kind of problems since we can't do ad-hoc bugfixes forever.
