### ISSUE TITLE
osu! ruleset ScoreV1 simulation underestimates total score

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#24653]
### Type

Other

### Bug description

With `[ HD HR DT FL ]`, the [SV1 simulator](https://github.com/ppy/osu/blob/d70df88fa007c7a3f5b4e3e2d600e7fa634ee2f5/osu.Game.Rulesets.Osu/Difficulty/OsuLegacyScoreSimulator.cs) estimates https://osu.ppy.sh/beatmapsets/1#osu/75 at `2052734`.

```
AccuracyScore = 61200
ComboScore = 1960834
legacyBonusScore = 30700
```

There are several scores on the leaderboard above this value, even non-FCs.

We should probably investigate this and try to match it better, because this is used for SV1 -> SV2 conversion of legacy scores.

### Version

d70df88fa007c7a3f5b4e3e2d600e7fa634ee2f5

### Logs

-

**Comment by Magnus-Cosmos** [comment]
DT score multiplier for 1.5x speed was changed to 1.1 in #23177, which would cause the score discrepancy described (when set back to 1.12 the simulator returns this:
```
AccuracyScore = 61200
ComboScore = 1996487
legacyBonusScore = 30700
```
Which would total to 2088387, the correct max score of the map.

**Comment by smoogipoo** [comment]
Good catch. Definitely needs fixing then. Probably by hardcoding the osu!stable multipliers.
