### ISSUE TITLE
Short music mute while game retry

### ISSUE THREAD

**Issue by xXN1ckWa1k3rXx** [ppy/osu#24652]
### Type

Game behaviour

### Bug description

Same as [#22164](https://github.com/ppy/osu/issues/22164)

Step:
1. Playing beatmap and press Esc+ ` (retry key)
2. Playing beatmap and press ` (retry key) , return song select when loading beatmap
3. Paused and click the Retry button , return song select when loading beatmap
4. Just retry game.. and somehow it will mute short time

*This problem also occurred in the previous version

**Due to personal reasons I can't provide more information later, I can only provide information in the ASAP of August 25th for GTM+8**

### Screenshots or videos

https://github.com/ppy/osu/assets/85390877/6734332b-36f8-4625-aa00-d2892bb8e12d

https://github.com/ppy/osu/assets/85390877/e2c34f97-4663-439b-9781-45d4fdc6822d

### Version

2023.815.0-Lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/12436159/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12436160/updater.log)
[database.log](https://github.com/ppy/osu/files/12436161/database.log)
[input.log](https://github.com/ppy/osu/files/12436162/input.log)
[network.log](https://github.com/ppy/osu/files/12436164/network.log)
[performance.log](https://github.com/ppy/osu/files/12436165/performance.log)

**Comment by peppy** [comment]
You've claimed that this is the same issue as https://github.com/ppy/osu/issues/22164, so please post in that thread rather than making a new issue, thanks!
