### ISSUE TITLE
[Android] osu!lazer's editor doesn't see mp3's in editor's file browser

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#24656]
### Type

Game behaviour

### Bug description

I've moved my mp3 to Music folder in sdcard, and it's not there in lazer's file browser in editor

I'm using Google Pixel 6

### Screenshots or videos

![Screenshot_20230825-194517](https://github.com/ppy/osu/assets/82095491/9ec7ec68-9ef2-497b-b8c8-d8a516fef12b)
![Screenshot_20230825-194828](https://github.com/ppy/osu/assets/82095491/e0ea7231-8d7a-404c-a146-dcfcede9c1a8)

### Version

2023.717.0-lazer

### Logs

[logs.zip](https://github.com/ppy/osu/files/12442422/logs.zip)

**Comment by bdach** [comment]
#11911
