### ISSUE TITLE
Classic plays in leaderboards showing as 0 score

### ISSUE THREAD

**Issue by Lemmmy** [ppy/osu#24663]
### Type

Game behaviour

### Bug description

Global leaderboards are showing plays made on stable since a certain time as having 0 score. For example, on [this map](https://osu.ppy.sh/beatmapsets/2015722#osu/4196159):
![image](https://github.com/ppy/osu/assets/858456/87f79ed9-ddf4-4bf1-98fd-2427e9cfbb80)

I can't say for sure that it's all plays since a certain time, but if it is, then I believe it happened some time between 2023-08-24 10:12:36 UTC+1 and 2023-08-24 11:38:08 UTC+1. Non-stable plays (including plays made with classic, but on lazer) don't seem to be affected.

### Screenshots or videos

![osu_2023-08-27_02-57-39](https://github.com/ppy/osu/assets/858456/97d1cdb3-d85e-4fa4-a09a-d539cea74d51)
![osu_2023-08-27_02-57-20](https://github.com/ppy/osu/assets/858456/41aaf509-4f43-474f-b3ec-e7fabb1ff158)

### Version

2023.815.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12447074/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12447075/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12447076/updater.log)
[database.log](https://github.com/ppy/osu/files/12447077/database.log)
[input.log](https://github.com/ppy/osu/files/12447078/input.log)
[network.log](https://github.com/ppy/osu/files/12447079/network.log)

**Comment by peppy** [comment]
This is due to the new legacy attributes required for score conversion not being populated at a database level

![2023-08-27 13 04 25@2x](https://github.com/ppy/osu/assets/191335/b0fdef5b-a49c-4840-a3c7-931909529895)

https://github.com/ppy/osu-queue-score-statistics/blob/0d231a420859dab2e16b48affe465500a0c4cd59/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs#L517-L521

**Comment by peppy** [comment]
This has been fixed by pinning the importer to the previous version of v1 score conversion (which still doesn't match v2 expectations).

We will need to revisit this after everything is set in stone with v2 mechanics.
