### ISSUE TITLE
Time remaining wraps back around to zero when a map is an hour long or longer

### ISSUE THREAD

**Issue by headache-booth** [ppy/osu#2466]
This can be seen happening with the map [Hatsune Miku Remembers 10,000 Digits of Pi](https://osu.ppy.sh/beatmapsets/355637). osu!lazer starts off saying there's only 8 minutes left in the song, but after those 8 minutes are up, will say there's 59 minutes left. Similarly, after 59 minutes have passed, lazer will say no time has passed.
![osu _2018-04-28_00-21-13](https://user-images.githubusercontent.com/13991844/39392831-49b5226c-4a7a-11e8-9401-e0a217b360f6.png)
![osu _2018-04-28_00-25-30](https://user-images.githubusercontent.com/13991844/39392855-d717e6a8-4a7a-11e8-98da-927e75a1e3bf.png)

**Comment by UselessToucan** [comment]
@tomatohentai There are only mania screenshots in the issue. What about other game mods?

**Comment by tomatohentai** [comment]
Oops, sorry, I somehow completely forgot to try and grab screenshots of this happening in other modes.

Testing all the other modes with [this map,](https://osu.ppy.sh/beatmapsets/752308), which is an hour and fifteen minutes long, the same thing happens.

![osu _2018-04-28_05-37-08](https://user-images.githubusercontent.com/13991844/39396183-d76a1726-4aa6-11e8-8c80-2a40cf399300.png)
![osu _2018-04-28_05-38-46](https://user-images.githubusercontent.com/13991844/39396188-f147fc6c-4aa6-11e8-9f87-7df23bca345e.png)
![osu _2018-04-28_05-39-34](https://user-images.githubusercontent.com/13991844/39396193-061f4726-4aa7-11e8-8412-57ac1ab8b7ed.png)
