### ISSUE TITLE
Alt + F4 behaviour

### ISSUE THREAD

**Issue by pixlmars** [ppy/osu#24660]
### Type

Game behaviour

### Bug description

In stable, when you press alt + f4 it closes playing song redirecting you based on where you are. If you are playing a song, then to song select menu and then closing osu!. However, lazer does behave slightly differently showing "Are you sure you want to exit osu!?" without any hesitation

### Screenshots or videos

https://github.com/ppy/osu/assets/124377327/40c0787e-6b72-47af-973c-9b39a25eed44

https://github.com/ppy/osu/assets/124377327/46538174-f1a3-4580-9ecb-3438e652a083

### Version

2023.815.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12444595/database.log)
[input.log](https://github.com/ppy/osu/files/12444596/input.log)
[network.log](https://github.com/ppy/osu/files/12444597/network.log)
[performance.log](https://github.com/ppy/osu/files/12444598/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12444599/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12444600/updater.log)

```[tasklist]
### Tasks
```

**Comment by peppy** [comment]
This is an intended usability change. You can hit alt-f4 one more time to exit.
