### ISSUE TITLE
Lack of proper analog inputs

### ISSUE THREAD

**Issue by Sebaex** [ppy/osu#24673]
### Type

Game behaviour

### Bug description

Game in general, both stable and lazer, has no support for analog inputs, for devices like iidx/ez2dj or sdvx controllers to be used in gamemodes like mania, standard or ctb

Specially in mania, since the RC [wants to expand](https://osu.ppy.sh/community/forums/topics/1787329) to keycounts above 10 keys, people might go on more arcade oriented mapping, but the lack of this input mode limits the capabilities of the maps that can be doable to rank since they're based on arcade counterparts rather than some freeform mapping

### Version

2023.815.0

### Logs

n/a

**Comment by peppy** [comment]
https://github.com/ppy/osu/discussions/24446
