### ISSUE TITLE
'now playing' tab will cut of song titles/artists if they are too long

### ISSUE THREAD

**Issue by tovc** [ppy/osu#24681]
### Type

Cosmetic

### Bug description

song titles are cut off in the 'now playing' tab if the song name is too long
![image](https://github.com/ppy/osu/assets/49025619/65cd790a-a5e4-417b-a68b-ec9a5dc72fcf)
the text should scroll or wrap to show the full song name

also happens with artist names, so they should be given the same treatment, just in case
![image](https://github.com/ppy/osu/assets/49025619/55abf7e7-0d90-4064-9092-1161e1ad3e73)

### Version

2023.815.0-lazer

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/12472884/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12472885/network.log)
[performance.log](https://github.com/ppy/osu/files/12472886/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12472887/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12472889/updater.log)
[database.log](https://github.com/ppy/osu/files/12472890/database.log)
[input.log](https://github.com/ppy/osu/files/12472891/input.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/3504#issuecomment-425615159

**Comment by tovc** [comment]
most of the text areas in that issue have been given proper truncation; this just looks messy by comparison

I don't understand why this would be marked as 'not planned', despite nearly every other instance having already been fixed

**Comment by bdach** [comment]
![image](https://github.com/ppy/osu/assets/20418176/476e28e7-aa99-4b14-991e-bf943b1d8e81)

ask github why it is this way i guess

**Comment by tovc** [comment]
alright, fair enough; that's a bit silly on github's part
