### ISSUE TITLE
osu!lazer 2018.423.0 crashes on startup

### ISSUE THREAD

**Issue by Herobrine59** [ppy/osu#2468]
I installed it, and when i started it up it shows me an error that osu! has stopped.

**Comment by LovelyA72** [comment]
can you provide the screenshot of the error?

**Comment by peppy** [comment]
Likely due to net471 prerequisite.

**Comment by peppy** [comment]
Please try reinstalling using the [latest release](https://github.com/ppy/osu/releases) and report back.

**Comment by frank89722** [comment]
Still same in 2018.502.0 :(

**Comment by peppy** [comment]
Closing for now.
