### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by MrKiwiBirb** [ppy/osu#24695]
### Type

Game behaviour

### Bug description

Out of nowhere, the screen cuts to black on the welcome splash. I have tried every single solution I found online to no avail. I've tried repairing it, launching it windowed, launching it in compatibility mode, launching it in both, restarted my computer, did a complete reinstall and every single one has been met with the same lack of results. I have zero idea what is causing the issue or how to fix it and I have come across zero helpful results online.

### Version

20230814.2

### Logs

[osu!auth.log](https://github.com/ppy/osu/files/12489076/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/12489077/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/12489078/update_success.log)

**Comment by bdach** [comment]
This repository is for lazer issues only. Issues with stable go in https://github.com/ppy/osu-stable-issues.
