### ISSUE TITLE
Ranked beatmap has 1 less slidertick/combo in Lazer compared to Stable

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu#24708]
### Type

Game behaviour

### Bug description

[`4182386`](https://osu.ppy.sh/beatmapsets/2007300#osu/4182386) shows `293` max combo in Stable (and as can be seen on the score leaderboards), but in Lazer the map only has `292` max combo. This is likely related to #24401.

### Screenshots or videos

For Stable, the editor shows that the 7th object has 1 slidertick right before the sliderend (actually after if you consider the -36ms):
![screenshot4474](https://github.com/ppy/osu/assets/39173355/b62c3efb-1feb-4950-8cca-f7439484fc92)
While for Lazer, the tick does not exist:
![osu_2023-09-03_02-20-04](https://github.com/ppy/osu/assets/39173355/55f987fa-4184-42f7-b0ce-7b33d95dc812)

---

Further inspection shows that the `tickDistance`, `Velocity`, and `length` values in Lazer are slightly inconsistent with Stable.
> Notes:
> `minDistanceFromEnd` is a multiple of `Velocity`
> `distanceToEnd = length - tickDistance`
> `scoringLengthTotal` is `length`
> `minTickDistanceFromEnd` is `minDistanceFromEnd`
> `skipTick` is `true` when `distanceToEnd <= minDistanceFromEnd`

Lazer's values from debugging:
![lazer slider inconsistency](https://github.com/ppy/osu/assets/39173355/49b0a1fd-372d-44f5-875f-205d319bd92c)

Stable's values from debugging:
![image](https://github.com/ppy/osu/assets/39173355/d9757929-ebe1-4095-83f9-db10ddaefeeb)
![image](https://github.com/ppy/osu/assets/39173355/d3a95919-abe4-47f6-a3a1-4215bda05949)
![image](https://github.com/ppy/osu/assets/39173355/b869dfca-1ac5-4818-a3f3-f026036e7493)

The slight differences causes Lazer to have a smaller `distanceToEnd` value and a larger `minDistanceFromEnd` value, which causes `skipTick` to be `true`, thus no slidertick is created for the slider.

---

Since I assume the server also uses the same logic as Lazer to process beatmaps, the database ends up having the wrong max combo in respect to Stable, as shown in the API response for the beatmap:
![image](https://github.com/ppy/osu/assets/39173355/cfef0bd4-5baa-4b43-88e6-9004d11edb9d)

### Versions

2023.815.0-lazer
b20230814cuttingedge

### Logs

[network.log](https://github.com/ppy/osu/files/12505265/network.log)
[performance.log](https://github.com/ppy/osu/files/12505266/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12505267/runtime.log)
[database.log](https://github.com/ppy/osu/files/12505268/database.log)
[input.log](https://github.com/ppy/osu/files/12505269/input.log)

**Comment by honguyenminh** [comment]
Maybe it has something to do with multiple redlines and redlines in the middle of the slider?

**Comment by Magnus-Cosmos** [comment]
> Maybe it has something to do with multiple redlines and the red line in the middle of the slider?

Are you referring to the red lines in the Lazer editor? If so, those are just the ticks for 1/2 beats. If you're referring to the timing points, there is a bpm and slider velocity change in the middle of the slider, but Stable and Lazer should have the same behavior regarding this.

**Comment by peppy** [comment]
Initial investigation shows that this is indeed a floating point issue.

This fixes the issue, by matching how stable is doing calculations (and introducing the floating point imprecision in the same place):

```diff
diff --git a/osu.Game.Rulesets.Osu/Objects/Slider.cs b/osu.Game.Rulesets.Osu/Objects/Slider.cs
index 4189f8ba1e..21a5c17ff8 100644
--- a/osu.Game.Rulesets.Osu/Objects/Slider.cs
+++ b/osu.Game.Rulesets.Osu/Objects/Slider.cs
@@ -167,7 +167,7 @@ protected override void ApplyDefaultsToSelf(ControlPointInfo controlPointInfo, I
 
             TimingControlPoint timingPoint = controlPointInfo.TimingPointAt(StartTime);
 
-            double scoringDistance = BASE_SCORING_DISTANCE * difficulty.SliderMultiplier * SliderVelocity;
+            double scoringDistance = BASE_SCORING_DISTANCE * difficulty.SliderMultiplier * (float)1/SliderVelocity;
 
             Velocity = scoringDistance / timingPoint.BeatLength;
             TickDistance = GenerateTicks ? (scoringDistance / difficulty.SliderTickRate * TickDistanceMultiplier) : double.PositiveInfinity;

```

This begs the question of whether `LegacyBpmMultiplier` is not being used in a place it should be. This requires further investigation.

**Comment by Magnus-Cosmos** [comment]
Not sure if this will help, but I compiled a list of all approved beatmaps (excluding qualified) that have incorrect `max_combo` compared to Stable: https://docs.google.com/spreadsheets/d/19TFgR_ZlKEWeqCnKoXJlf48Scql0QDl3YAA5ppw9MNg

As expected, a majority of them are loved/aspire beatmaps, which can be ignored for now (unless there are plans to support those types of beatmaps in the future). There are also 3 ranked beatmaps, [`1855`](https://osu.ppy.sh/beatmapsets/268#osu/1855), [`42196`](https://osu.ppy.sh/beatmapsets/10804#osu/42196), and [`4182386`](https://osu.ppy.sh/beatmapsets/2007300#osu/4182386). I believe `1855` and `4182386` are due to floating point issues, which #24739 should fix.

But for `42196`, the slider length is off by a huge amount. This is because the length specified in the [.osu file](https://osu.ppy.sh/osu/42196) is different than the length calculated using the path points. For Stable, the calculated length is `222.004464186728` while the length in the beatmap file is `330`. Stable attempts to resolve this by removing the "excess", which happens to add the missing amount back when the "excess" is negative. After doing this, the calculated length becomes `330.00000862032175`.

For Lazer, the recalculation for the last path is skipped when the last two control points are equal and when the expected length is greater than the calculated length. Relevant Lazer code: https://github.com/ppy/osu/blob/f90f2491c349c58f5a038ab83e9934ca4b483787/osu.Game/Rulesets/Objects/SliderPath.cs#L331-L336
Meanwhile in Stable, the only scenario where recalculation is skipped is when the last two control points are equal and when the length of the final path is greater than the "excess" (calculated length - expected length). Applying this logic to Lazer results in the same slider length, although I'm unsure if this will have any unintended consequences (also not sure if the `0.0001` is needed):
```diff
diff --git a/osu.Game/Rulesets/Objects/SliderPath.cs b/osu.Game/Rulesets/Objects/SliderPath.cs
index 34113285a4..b4507f8d6f 100644
--- a/osu.Game/Rulesets/Objects/SliderPath.cs
+++ b/osu.Game/Rulesets/Objects/SliderPath.cs
@@ -328,16 +328,16 @@ private void calculateLength()

             if (ExpectedDistance.Value is double expectedDistance && calculatedLength != expectedDistance)
             {
+                int pathEndIndex = calculatedPath.Count - 1;
+
                 // In osu-stable, if the last two control points of a slider are equal,  extension is not performed.
-                if (ControlPoints.Count >= 2 && ControlPoints[^1].Position == ControlPoints[^2].Position && expectedDistance > calculatedLength)
+                if (ControlPoints.Count >= 2 && ControlPoints[^1].Position == ControlPoints[^2].Position && calculatedPath[pathEndIndex].Length > calculatedLength - expectedDistance + 0.0001)
                 {
                     cumulativeLength.Add(calculatedLength);
                     return;
                 }
 
                 // The last length is always incorrect
                 cumulativeLength.RemoveAt(cumulativeLength.Count - 1);
 
-                int pathEndIndex = calculatedPath.Count - 1;
-
                 if (calculatedLength > expectedDistance)
```
***
## Stable
![screenshot4476](https://github.com/ppy/osu/assets/39173355/e2a83eec-e035-440c-8127-a6ad35c36c8e)
## Lazer
![osu_2023-09-13_03-06-20](https://github.com/ppy/osu/assets/39173355/d64ccd1b-36d2-4e62-9c33-8103e36ae407)
## Lazer with diff applied
![osu_2023-09-13_03-33-00](https://github.com/ppy/osu/assets/39173355/b5e7b5ae-cb40-4c40-b632-7ec5f98e9d00)

**Comment by Magnus-Cosmos** [comment]
Okay, was thinking I should've done that, was originally going to comment just the list, so that it provides more test cases, but ended up looking into it and finding another issue.
