### ISSUE TITLE
Lazer not opening in the previously pinned shortcut

### ISSUE THREAD

**Issue by Kuina-chan** [ppy/osu#24746]
### Type

Game behaviour

### Bug description

Newer lazer client do not open in the same place as the pinned icon on the taskbar.

Re-creating the bug:
Open older lazer client -> Pin to the taskbar -> update -> re-launch

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/75318520/ac46838f-d229-4cb5-b2eb-ce11d95c3466)

### Version

2023.908.0

### Logs

[performance.log](https://github.com/ppy/osu/files/12557326/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12557327/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12557328/updater.log)
[database.log](https://github.com/ppy/osu/files/12557329/database.log)
[input.log](https://github.com/ppy/osu/files/12557330/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12557331/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12557332/network.log)

**Comment by peppy** [comment]
Please make sure your shortcut is to the `osu!.exe` not the dated release folder.

This will be fixed when we get to updating squirrel to v3.

**Comment by Kuina-chan** [comment]
@peppy I can't unpin the old icon as well :L

**Comment by peppy** [comment]
That sounds like a windows bug. Maybe try restarting.
