### ISSUE TITLE
Performance regressions reported since SSBO implementation

### ISSUE THREAD

**Issue by peppy** [ppy/osu#24751]
I've experienced corruption and performance regressions on macOS (M2 / Metal) when opening the wiki to the "BanchoBot" article.

Graphical corruption:

<img width="1694" alt="2023-09-08_01 07 502x" src="https://github.com/ppy/osu/assets/191335/99cd957f-0959-4519-807d-76e3e788c18a">

Weird performance including system wide degradataion:

https://github.com/ppy/osu/assets/191335/4df1b682-4c9b-4ca0-a31f-2049bcdee3d3

**Comment by peppy** [comment]
Also android users have reported [performance issues](https://osu.ppy.sh/comments/2868385).

**Comment by peppy** [comment]
Some more reports of performance degradation we should follow up on in the future:

https://osu.ppy.sh/comments/2868545
https://osu.ppy.sh/comments/2868506
https://osu.ppy.sh/comments/2868385

all OpenGL, it would seem

**Comment by netfri25** [comment]
I have the same issue, using Ubuntu linux.
after the update everything became laggy and even scrolling stutters
