### ISSUE TITLE
Sliders flicker and then disappears while spectating on multiplayer

### ISSUE THREAD

**Issue by DarkbitNetwork** [ppy/osu#24766]
### Type

Game behaviour

### Bug description

While I was spectating other players in a multiplayer lobby, I noticed that the slider body would flicker and then disappear. The reverse arrow, slider ticks, and slider head aren't affected by this bug.

### Screenshots or videos

https://github.com/ppy/osu/assets/43719333/64f3576f-d874-4a85-b3a6-dde14ba3eabe

### Version

osu! 2023.908.2-lazer

### Logs

Doesn't seem to be relevant but I'll put it here just in case
[runtime.log](https://github.com/ppy/osu/files/12564617/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12564618/updater.log)
[database.log](https://github.com/ppy/osu/files/12564619/database.log)
[input.log](https://github.com/ppy/osu/files/12564620/input.log)
[network.log](https://github.com/ppy/osu/files/12564621/network.log)
[performance.log](https://github.com/ppy/osu/files/12564622/performance.log)

**Comment by GuineaGuy99** [comment]
It seemed like everybody in the lobby who tried spectating was having rendering issues.

There were no issues while actually playing, and I also noticed on my end that about 95% of the time the top-left spectator box rendered properly while the others all had flashing and other rendering issues. Some people also noticed that the line on profile rank-graphs was not rendering properly either.

Complete guess but I suspect this is related to the recent SSBO changes?

https://github.com/ppy/osu/assets/12271508/9a43af1b-cb06-427a-874f-0bb6d3399bb5
