### ISSUE TITLE
You are able to download the same replay several times if you switch to another result on the map

### ISSUE THREAD

**Issue by r0xANDt0l** [ppy/osu#24760]
### Type

Game behaviour

### Bug description

If you download a replay from the leaderboard, and then switch to another player on the leaderboard, when you come back, instead of having the option to check the replay, it prompts you to download it again

### Screenshots or videos

https://github.com/ppy/osu/assets/41841903/69e4eb1e-5485-4deb-a570-34abebee40e3

### Version

2023.0908.2-lazer

### Logs

[performance-input.log](https://github.com/ppy/osu/files/12562644/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12562645/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12562646/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12562647/updater.log)
[database.log](https://github.com/ppy/osu/files/12562648/database.log)
[input.log](https://github.com/ppy/osu/files/12562649/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12562650/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12562651/network.log)
[performance.log](https://github.com/ppy/osu/files/12562652/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/12562653/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12562654/performance-draw.log)

**Comment by bdach** [comment]
This is known and will not be fixed before the checklist in https://github.com/ppy/osu/issues/24229 is completed. To that end, closing as duplicate.
