### ISSUE TITLE
osu! laser always stop working

### ISSUE THREAD

**Issue by dragonGod97677** [ppy/osu#2476]
![untitled](https://user-images.githubusercontent.com/38875906/39462719-0171cfb8-4d46-11e8-8a9f-f030127725c3.png)

**Comment by AlFasGD** [comment]
What version of Windows is that? If it's prior to 7, I doubt osu!lazer is intended to support that.

**Comment by swoolcock** [comment]
According to this, it’s Windows 7. https://www.msigeek.com/442/windows-os-version-numbers

**Comment by jai-sharma** [comment]
osu! laser should be able to support any platform that can run .NET Framework 4.7 (which Windows 7 supports) or dotnetcore 2.0

@dragonGod97677 Make sure you have the latest .NET Framwork installed: https://www.microsoft.com/net/download/dotnet-framework-runtime

**Comment by peppy** [comment]
Please try reinstalling using the [latest release](https://github.com/ppy/osu/releases) and report back.

**Comment by Op4ic** [comment]
I know another solution: First uninstall the latest release then install older release (Feb 2018 works).
After you installed the game, launch it. And it will autoupdate the game. And yes, after update latest release works. Op4ic

**Comment by dragonGod97677** [comment]
Sorry for the late reply.. I used win 7 and i will report back when i can.. And as far as i know latest .net framework is installed.. If not it will least give me a notice window that i need to install/update .net framework after installation. Right?

**Comment by peppy** [comment]
It will now. This was only fixed very recently, so please download the latest installer and try again.

**Comment by dragonGod97677** [comment]
ok thanks.. back to normal
