### ISSUE TITLE
Score shows as 0 for downloaded replays

### ISSUE THREAD

**Issue by Sukuratchi** [ppy/osu#24771]
### Type

Game behaviour

### Bug description

When downloading replays it shows the score as 0 except when after watching the replay. But even after you finish watching the replay, the score in the song select is still 0

### Screenshots or videos

https://github.com/ppy/osu/assets/66184829/c674dbca-6a9a-4db3-a0a7-2494337badeb

https://github.com/ppy/osu/assets/66184829/95bb89c9-18f2-4faf-bac2-7279adca3669

### Version

2023.908.2-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12566136/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12566137/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12566138/updater.log)
[database.log](https://github.com/ppy/osu/files/12566139/database.log)
[network.log](https://github.com/ppy/osu/files/12566140/network.log)

**Comment by Sukuratchi** [comment]
Not sure if #24643 is supposed to be fixed in the current version of the game

**Comment by bdach** [comment]
Known, fix requires deployment of https://github.com/ppy/osu-server-spectator/pull/181, only replays recorded after deployment of fix will have the score populated in the replay.
