### ISSUE TITLE
Sorting beatmaps by difficulty only shows one beatmap that fits criterion, not all of them

### ISSUE THREAD

**Issue by matthewcn56** [ppy/osu#24774]
### Type

Game behaviour

### Bug description

When sorting beatmaps by difficulty, I saw that  if a beatmap had multiple difficulties which fit the criteria, only one gets displayed and there's not even an option to expand to see all difficulties unlike when I sort by other criteria.

### Screenshots or videos

Quaver when sorted by difficulty, only the first one that fits the criterion shows up.
<img width="864" alt="Screenshot 2023-09-09 at 7 13 09 PM" src="https://github.com/ppy/osu/assets/65370631/8b8bff5a-45d7-4812-b7ef-7eb846ce4ccf">

When sorting by artist, I get to see all beatmaps within the given difficulty range and it shows the option to expand and show all difficulties, even those outside the difficulty range.
<img width="855" alt="Screenshot 2023-09-09 at 7 13 38 PM" src="https://github.com/ppy/osu/assets/65370631/d89e5cdf-0ac9-41c9-908a-1a4ad8c3c457">

### Version

2023.908.2-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12567024/database.log)
[input.log](https://github.com/ppy/osu/files/12567025/input.log)
[network.log](https://github.com/ppy/osu/files/12567026/network.log)
[performance.log](https://github.com/ppy/osu/files/12567027/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12567028/runtime.log)

**Comment by peppy** [comment]
This is intended behaviour.
