### ISSUE TITLE
Replay download button doesn't get changed when replay is downloaded

### ISSUE THREAD

**Issue by Sukuratchi** [ppy/osu#24772]
### Type

Cosmetic

### Bug description

When downloading a replay the replay download button doesn't get updated if the replay is downloaded, forcing you to exit out and enter the score listing to then watch

### Screenshots or videos

https://github.com/ppy/osu/assets/66184829/276682cd-3098-4e7c-8152-f0888057f2d6

### Version

2023.908.2-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12566153/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12566154/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12566155/updater.log)
[database.log](https://github.com/ppy/osu/files/12566156/database.log)
[network.log](https://github.com/ppy/osu/files/12566157/network.log)

**Comment by bdach** [comment]
Known, will be fixed once checklist in https://github.com/ppy/osu/issues/24229 is completed.
