### ISSUE TITLE
Even if Mania is rated SS, Accuracy Circle will not show the SS rating

### ISSUE THREAD

**Issue by RBQcat** [ppy/osu#24788]
### Type

Cosmetic

### Bug description

View detailed scores in the leaderboard, Accuracy Circle does not display SS level
Beatmaps: https://osu.ppy.sh/beatmapsets/2037054#mania/4248392

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/74862110/62b36e0c-c638-47ef-bede-428330aeeafd)

### Version

2023.908.2

### Logs

N/A

**Comment by bdach** [comment]
basically boils down to https://github.com/ppy/osu/issues/24238
