### ISSUE TITLE
Spinners hides sliders body while shown

### ISSUE THREAD

**Issue by NovaliX-Dev** [ppy/osu#24784]
### Type

Game behaviour

### Bug description

When a slider appear while a spinner is active, we only see the start of the slider. It's body is hidden, until it magically pops of out of nowhere.

### Screenshots or videos

During a replay (From a real map) :

https://github.com/ppy/osu/assets/79244938/8bbda5c2-5c02-4b1a-8fdb-9c22f8179d4f

During play (From a custom map, easy to reproduce) : 

https://github.com/ppy/osu/assets/79244938/22358cc4-636c-49b3-93fe-c0c81518d67b

### Version

2023.908.2

### Logs

[database.log](https://github.com/ppy/osu/files/12577333/database.log)
[input.log](https://github.com/ppy/osu/files/12577334/input.log)
[network.log](https://github.com/ppy/osu/files/12577335/network.log)
[performance.log](https://github.com/ppy/osu/files/12577336/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12577337/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12577339/updater.log)

**Comment by HyperSlayer72** [comment]
Can confirm this is happening to me also.

**Comment by peppy** [comment]
Duplicate https://github.com/ppy/osu/issues/24766, https://github.com/ppy/osu/issues/24769, https://github.com/ppy/osu/issues/24767.

Will be resolved in the next release.
