### ISSUE TITLE
osu! on nixos

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [ppy/osu#24797]
### Type

Game behaviour

### Bug description

first of all nixos handle appimage diffrently ,
lets install **appimage-run**

`nix-env -iA nixos.appimage-run`

now lets try to play 
```

appimage-run osu.AppImage 

Uncompress osu.AppImage of type 02 @ offset 193728
[===========================================================================================================================================================================|] 2782/2782 100%
osu.AppImage is now installed in /home/krafi/.cache/appimage-run/6b5917cd293ce53526016c2768d5f36fe0dee064ba0b090ba230656f572e1632
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.

```

after doing some online research i added this line on terminal 

`export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1`

now i can play osu , but some reason there are still some bugs kind of thing like i cant see anyone profile  
where i can find the log file ? 

```
An unhandled exception occurred at $00007F45858CD9E9:
EAccessViolation: Access violation
  $00007F45858CD9E9 in /nix/store/clggkpvdqizmynyr4xc19178b2gbxpfx-qtbase-5.15.10/lib/libQt5Core.so.5

An unhandled exception occurred at $00007F458580BDDE:
EAccessViolation: 
  $00007F458580BDDE in /nix/store/clggkpvdqizmynyr4xc19178b2gbxpfx-qtbase-5.15.10/lib/libQt5Core.so.5

An unhandled exception occurred at $00007F458580BDDE:
EAccessViolation: 
  $00007F458580BDDE in /nix/store/clggkpvdqizmynyr4xc19178b2gbxpfx-qtbase-5.15.10/lib/libQt5Core.so.5

An unhandled exception occurred at $00007F458580BDDE:
EAccessViolation: 
  $00007F458580BDDE in /nix/store/clggkpvdqizmynyr4xc19178b2gbxpfx-qtbase-5.15.10/lib/libQt5Core.so.5

An unhandled exception occurred at $00007F458580BDDE:
EAccessViolation: 
  $00007F458580BDDE in /nix/store/clggkpvdqizmynyr4xc19178b2gbxpfx-qtbase-5.15.10/lib/libQt5Core.so.5

An unhandled exception occurred at $00007F458580BDDE:
EAccessViolation: 
  $00007F458580BDDE in /nix/store/clggkpvdqizmynyr4xc19178b2gbxpfx-qtbase-5.15.10/lib/libQt5Core.so.5

/usr/bin/xdg-open: line 896: x-www-browser: command not found
SystemLocale en_US
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
Starting GuiMessageQueue
Starting Double Commander
Double Commander 1.1.1 beta
Revision: Unknown
Commit: Unknown
Build: 2023/09/02
Lazarus: 2.2.2.0
Free Pascal: 3.2.2
Platform: x86_64-Linux-qt5
System: NixOS 23.11 (Tapir)
Error loading configuration file /home/krafi/.config/doublecmd/favoritetabs.xml


```

### Version

latest

### Logs

cat ~/.local/share/osu/logs/database.log | paste
https://paste.rs/nXxrM                                                                                      

cat ~/.local/share/osu/logs/input.log | paste 
https://paste.rs/9Kv4q   

 cat ~/.local/share/osu/logs/network.log | paste 
https://paste.rs/yyLz3

cat ~/.local/share/osu/logs/performance.log | paste 
https://paste.rs/5ZRBf

cat ~/.local/share/osu/logs/runtime.log | paste 
https://paste.rs/Ew5KJ

**Comment by View-my-Git-Lab-krafi** [comment]
forgot to meantion there is an osu lazer package on the nixos package manager, not too much up to date .  it work perfectly , can i build osu ?? to play ?

https://search.nixos.org/packages?channel=23.05&show=osu-lazer&from=0&size=50&sort=relevance&type=packages&query=osu

**Comment by View-my-Git-Lab-krafi** [comment]
![osubug12023-09-13_14-57](https://github.com/ppy/osu/assets/121858831/c1011846-1f6a-4fa9-8c0f-79bac60ca923)

![osubug22023-09-13_14-58](https://github.com/ppy/osu/assets/121858831/b19b7dd1-35d6-4297-9410-b945cbc94356)

![osubug32023-09-13_14-58](https://github.com/ppy/osu/assets/121858831/7f3c2190-1102-47d6-a404-80abc0b1d939)

**Comment by bdach** [comment]
The only supported installation mediums on linux are the appimage and the flatpak. Anything else is not supported. In particular, due to compatibility and anticheat concerns, local builds will not be able to connect to online servers and participate on leaderobards. I hope you can understand that we cannot provide further advice here.

**Comment by View-my-Git-Lab-krafi** [comment]
i wish i should know it before osu!lazer support flatpak. anyway which one should i use  ?

```
flatpak install osu
Looking for matches…
Similar refs found for ‘osu’ in remote ‘flathub’ (system):

   1) app/sh.ppy.osulazer/x86_64/stable
   2) app/sh.ppy.osu/x86_64/stable
   3) app/org.mobsya.ThymioSuite/x86_64/stable

Which do you want to use (0 to abort)? [0-3]: 2
Required runtime for sh.ppy.osu/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/22.08) found in remote flathub
Do you want to install it? [Y/n]: y

```

**Comment by bdach** [comment]
https://github.com/flathub/sh.ppy.osu
