### ISSUE TITLE
Crashing to desktop while initializing beatmaps.

### ISSUE THREAD

**Issue by Inconsist** [ppy/osu#24793]
### Type

Crash to desktop

### Bug description

Downloaded new beatmaps, had about 60 waiting to initialize, tabbed out to Taskmanager, tabbed back in, crashed to desktop. No idea what caused it. I reopened the game and then uploaded the log files to this bug report.

### Version

2023.908.2

### Logs

[performance.log](https://github.com/ppy/osu/files/12592787/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/12592788/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12592789/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/12592790/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12592791/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12592792/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12592793/updater.log)
[database.log](https://github.com/ppy/osu/files/12592794/database.log)
[input.log](https://github.com/ppy/osu/files/12592795/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12592796/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12592797/network.log)

**Comment by peppy** [comment]
Reopening the game resets log files, so there's not too much to see here. Rest assured, all crashed (except GPU/driver issues) are logged at our end so yours likely has been accounted for. Please let us know if it happens again (and if possible, upload the log files before restarting).
