### ISSUE TITLE
Can't import beatmap via IPC

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu#248]
After quick investigation, it seems the IPC message isn't received by the primary host at all. I may investigate further, but not assigning myself yet.

I believe it is OS-related (Arch Linux user here).

EDIT: Actually works with absolute, non-unicode paths.

**Comment by autismpp** [comment]
Works on Arch here with the latest mono package from the official repositories.

Run as `mono osu\!.exe <full path to .osz file>` - make sure you don't specify a relative path.

**Comment by ThePooN** [comment]
AH. That might be it...

**Comment by ThePooN** [comment]
So after using absolute paths + non-unicode path it works. Thanks for the tip.

**Comment by peppy** [comment]
relative paths now work too. this has been completely resolved.
