### ISSUE TITLE
Can't login to osu!lazer

### ISSUE THREAD

**Issue by WubWoobWub** [ppy/osu#24804]
### Type

Other

### Bug description

tried logging in for the first time on osu!lazer but couldn't, game tells me "An error occured while sending the request."

### Screenshots or videos

![osu_2023-09-13_16-02-54](https://github.com/ppy/osu/assets/54578359/1bdbd29d-a2d6-4d17-acb5-35cc67ac23a3)

### Version

2023.913.0

### Logs

[database.log](https://github.com/ppy/osu/files/12598467/database.log)
[input.log](https://github.com/ppy/osu/files/12598468/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12598469/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12598470/network.log)
[performance.log](https://github.com/ppy/osu/files/12598471/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12598472/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12598473/updater.log)

**Comment by peppy** [comment]
Your system SSL is misconfigured. This may mean your system is compromised, you applied custom tweaks and broke something, or your data is corrupt. Google for `0x80090326` for potential solutions.

**Comment by WubWoobWub** [comment]
Thanks for the quick response but I don't think I ever tweaked anything related to SSL, tbf I don't even know what it really is. Anyway I'll try and find a solution with that error code then
