### ISSUE TITLE
Not able to import files because Osu! Lazer on Android doesn't have access to files.

### ISSUE THREAD

**Issue by AkiraKusanagi** [ppy/osu#24830]
### Type

Other

### Bug description

I was checking out some import file stuff and edit mode. I noticed that Osu! Lazer wasn't detecting ANY files. So I checked the permissions on the apps and it said, "App has not requested any permissions." This is probably why. It could also be better if you could use the built-in file manager for the device as

1. It would be much easier to navigate than using the Osu! File viewer-thingy.
2. It's faster
3. You can view files from an SD Card.

### Screenshots or videos

Checking for permissions:
![Screenshot_20230915-210629](https://github.com/ppy/osu/assets/137284132/818b2807-c9d8-462d-a609-614c5373844f)

Checking in my Idk folder with beatmaps:
![Screenshot_20230915-210830](https://github.com/ppy/osu/assets/137284132/a166029b-5488-4857-a503-b2d0e89664b8)

Checking out the add music feature in edit mode:
![Screenshot_20230915-211007](https://github.com/ppy/osu/assets/137284132/76f175fe-b799-4b94-b556-95391bbc3f3c)

### Version

2023.914.0

### Logs

No sure how this'll help because this is not an issue with performance, crashing, or something related to that, but, ok!
[runtime.log](https://github.com/ppy/osu/files/12639808/runtime.log)
[database.log](https://github.com/ppy/osu/files/12639809/database.log)
[network.log](https://github.com/ppy/osu/files/12639810/network.log)
[performance.log](https://github.com/ppy/osu/files/12639812/performance.log)

**Comment by bdach** [comment]
#11911
