### ISSUE TITLE
[ Osu!catch ]  fruit inconsistent in stable and lazer 

### ISSUE THREAD

**Issue by juices95** [ppy/osu#24836]
### Type

Game behaviour

### Bug description

Compared to Lazer, Stable's fruit is a hyperfruit rather than a normal fruit.
In [this map ](https://osu.ppy.sh/beatmapsets/1280183#fruits/2659330)the ending section. ( 02:07:531 )

*Please take a look at  [this. ](https://osu.ppy.sh/beatmapsets/1280183/discussion/2659330/timeline#/1958048)

### Screenshots or videos

Stable :
![screenshot195](https://github.com/ppy/osu/assets/122288984/95662a8a-44c3-48d6-8485-90dc9caa71e0)
Lazer :
![osu_2023-09-17_11-19-41](https://github.com/ppy/osu/assets/122288984/593fc0bc-1c62-4a90-aca5-2ec1347771e9)

----------------------------------------------------------------------------------------------------
Stable :

https://github.com/ppy/osu/assets/122288984/0aa7bff1-a31f-4f77-8a24-2355dea17ae1

Lazer :

https://github.com/ppy/osu/assets/122288984/f6a57b6f-a78d-43b8-9571-d037771f071b

### Version

2023.914.0

### Logs

[performance.log](https://github.com/ppy/osu/files/12642041/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/12642042/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/12642043/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12642044/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12642045/updater.log)
[database.log](https://github.com/ppy/osu/files/12642046/database.log)
[input.log](https://github.com/ppy/osu/files/12642047/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12642048/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12642049/network.log)

**Comment by bdach** [comment]
We already have #15305 for a similar sort of issue, so let's track this there. Closing as duplicate.
