### ISSUE TITLE
"No idea sorry. Your game may be corrupt. Try downloading again."

### ISSUE THREAD

**Issue by Maoman1** [ppy/osu#24851]
No idea sorry. Your game may be corrupt. Try downloading again.

_Originally posted by @peppy in https://github.com/ppy/osu/issues/24838#issuecomment-1723899685_

Come the fuck on man, you knew full well your reply was completely useless. Locking the thread? Jesus.

"Try downloading again"
...I have downloaded install.exe _nine separate times_, some of them older versions, some of them just repeats of the latest release in case the download was corrupted. None of them work. I already said as much in my first post. 

I repeat, this is a fresh install of windows. This isn't an OEM pre-built with all the extras and bloatware pre-installed, this is a custom build with as little extra bullshit as humanly possible because I fucking hate microsoft. It is like two weeks old and literally all I've done so far is browse social media and play Rimworld.

I'm guessing the problem is some dependency I'm missing or it would at the very least _try_ to run, but it doesn't even get that far--so, a basic runtime or library or something. But I'm not gonna just go downloading random shit and hope I stumble onto what I'm missing, I was hoping one of _you_ could tell me what is needed. What basic-ass fundamental _something_ does osu!lazer require that might be missing in a fresh install? If you don't see it on ninite.com, I probably don't have it. Like, I don't think this thing even has a C++ redistributable installed yet. Does it need that? What about Java? I don't fuckin know, it's your code. What is _absolutely vital_ for Lazer to even try to exist on a system?

**Comment by Maoman1** [comment]
Original post https://github.com/ppy/osu/issues/24838

**Comment by peppy** [comment]
The thread is not locked, it's moved to discussions for further discussion. Please follow the link and post there.

This is standard practice to keep issues limited to those we have confirmed. Sorry if this has upset you.
