### ISSUE TITLE
Can't shift-delete to delete beatmap in song select anymore

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#24867]
### Type

Game behaviour

### Bug description

Regressed because of https://github.com/ppy/osu-framework/pull/5870.

Relevant song select code:
https://github.com/ppy/osu/blob/aea7f81f1c1751858e457645c7d541ec5ee39fac/osu.Game/Screens/Select/SongSelect.cs#L973-L991

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/35318437/1a0832c4-a19e-42dc-afcf-c6158d1d0c03)

### Version

Since 2023.716.0

### Logs

N/A

**Comment by peppy** [comment]
Probably needs another textbox exception. Or at this point, probably need to re-think how song select textbox focus works. Maybe it should only get focus on pressing the tab key similar to other places (would fix other issues like keyboard navigation of the textbox.

**Comment by bdach** [comment]
this is actually and properly closed by https://github.com/ppy/osu/pull/24878 now.
