### ISSUE TITLE
In multiplayer team VS mode the opponent's lower score's bar is not displayed correctly

### ISSUE THREAD

**Issue by wooster0** [ppy/osu#24886]
### Type

Cosmetic

### Bug description

In all multiplayer Team VS games I've played today there was this graphical bug where the score bar of the opposing team wasn't displayed correctly. It rendered text with a negative number. I don't think this is supposed to be like that. And I'm sure it's a very recent regression.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/35064754/75f3cbc1-bfbe-4ef1-90a2-6a3c13f12cc9)
Another game:
![image](https://github.com/ppy/osu/assets/35064754/cdb7c56e-3889-47df-9bca-9bff86ad3afa)
(My team was in the lead here, I was in red team in both screenshots)
Instead of -255,172 it should probably draw a blue rectangle similar to red.

### Version

2023.914.0

### Logs

This should be easy to reproduce? I had this bug happen every single time. I was in a multiplayer room with 1 other person in team VS mode, had all freemods on, beatmap intro skip enabled, auto start off, and host mode set to all players, and no password. I hope that's enough info to reproduce. And I was in red team and in the lead whenever this happened.

**Comment by peppy** [comment]
This is 100% intentional, and how we show scores on tournaments too.

The negative number is the different between the scores. It shows how much you're winning by.
