### ISSUE TITLE
Login Not Working?

### ISSUE THREAD

**Issue by TheCandiedHat** [ppy/osu#2488]
I created an osu account (with major difficulty) using a windows VM. The account is verified and everything, but when I try to sign in to it using osu!lazer it doesn't work. The message is "Login failed!"

**Comment by peppy** [comment]
Could you please attempt to debug and see what error is occurring? `network.log` may be a good place to start.

**Comment by LovelyA72** [comment]
I remember that if you created an account, you have to login to osu!stable once in order to activate your account. I think this related to bancho connection. Since lazer don't support bancho, i suggest you login into osu!stable once, then see if you can login into lazer.

**Comment by MoriokaMario** [comment]
Where Can i find network.log file?
I found it once.Cant find it now.

**Comment by peppy** [comment]
@MoriokaMario Could you please try again and see if login is working now? If not could you please provide the log I asked for?

**Comment by MoriokaMario** [comment]
/2018 1:03:12 PM: ----------------------------------------------------------
12/1/2018 1:03:12 PM: Network Log for JHAKUNIPARA GPS (LogLevel: Verbose)
12/1/2018 1:03:12 PM: osu 2018.1123.1.0
12/1/2018 1:03:12 PM: Running on Microsoft Windows NT 6.2.9200.0, 4 cores
12/1/2018 1:03:12 PM: ----------------------------------------------------------
12/1/2018 1:03:12 PM: We just went Connecting!
12/1/2018 1:03:22 PM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
12/1/2018 1:03:32 PM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
12/1/2018 1:03:33 PM: Processing response from https://osu.ppy.sh/oauth/token failed with System.ArgumentNullException: Value cannot be null.
12/1/2018 1:03:33 PM: Parameter name: value
12/1/2018 1:03:33 PM: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
12/1/2018 1:03:33 PM: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
12/1/2018 1:03:33 PM: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse()
12/1/2018 1:03:33 PM: at osu.Framework.IO.Network.WebRequest.Complete(Exception e).
12/1/2018 1:03:33 PM: Login failed!
12/1/2018 1:03:33 PM: We just went Offline!

**Comment by MoriokaMario** [comment]
Is it a problem in my internet connection,or my Password or Email?

**Comment by peppy** [comment]
Just to confirm, you are able to access https://osu.ppy.sh/oauth/token? (should show "Page Missing")

**Comment by MoriokaMario** [comment]
> Just to confirm, you are able to access https://osu.ppy.sh/oauth/token? (should show "Page Missing")

Yes...I can.It shows page missing.

**Comment by Joehuu** [comment]
@MoriokaMario try reproducing again. comment if it still occurs and we'll reopen.
