### ISSUE TITLE
Score seems buggy

### ISSUE THREAD

**Issue by patin-osu** [ppy/osu#24904]
### Type

Game behaviour

### Bug description

Some player score shows incorrectly, Making some player FC big black with only 57 points and 1/1 combo for example and it seems to affect the lazer version of osu! website as well (I'm so sorry if it was a dupe, it's hard to find an identical bug that people encountered and report earlier)

### Screenshots or videos

![Screenshot (1)](https://github.com/ppy/osu/assets/75104667/3ad016f5-b457-475f-998e-387bab52490d)
![Screenshot (2)](https://github.com/ppy/osu/assets/75104667/a85d6785-01c6-40ac-bcf1-8bdce3ae3f7f)
![Screenshot (3)](https://github.com/ppy/osu/assets/75104667/0f17923e-741d-4d47-8658-7dd02330c956)
![Screenshot (4)](https://github.com/ppy/osu/assets/75104667/d4939388-800a-4106-90fc-33fd2fae0b60)
![image](https://github.com/ppy/osu/assets/75104667/bc1fb0e6-bc09-4cbc-962f-6743412e030b)
![image](https://github.com/ppy/osu/assets/75104667/3e01d028-7276-4d90-b281-5f4ec7e5e447)

### Version

2023.904.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12708170/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12708171/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12708172/updater.log)
[database.log](https://github.com/ppy/osu/files/12708173/database.log)
[input.log](https://github.com/ppy/osu/files/12708174/input.log)
[network.log](https://github.com/ppy/osu/files/12708175/network.log)

**Comment by peppy** [comment]
We're planning on doing a scrore reset to wipe all these broken scores in the near future. They are broken from the many scoring changes we've applied over the last year. Stay tuned for that!
