### ISSUE TITLE
SR/BPM display in mod menu doesn't work in multiplayer and playlists room.

### ISSUE THREAD

**Issue by ChiNoel-osu** [ppy/osu#24907]
### Type

Cosmetic

### Bug description

This thing https://github.com/ppy/osu/pull/24705 is a cool addition but rn it doesn't work in multiplayer and playlists room, it all shows zero. Does work in song selection (where you add maps to the map pool).

### Screenshots or videos

<img width="1286" alt="Screenshot 2023-09-24 221341" src="https://github.com/ppy/osu/assets/39649720/77bf7172-1cba-46f1-9e58-acf98d05a540">
The above screenshot shows a playlist room. But same thing in multiplayer room.

### Version

2023.924.0

### Logs

_c'mon you don't need logs for this_

**Comment by bdach** [comment]
Resolved by https://github.com/ppy/osu/pull/24922
