### ISSUE TITLE
Notification spam when importing scores linked to deleted beatmaps from stable

### ISSUE THREAD

**Issue by SupDos** [ppy/osu#24926]
### Type

Game behaviour

### Bug description

This might not apply to everyone, but many players probably have a lot of scores/replays in their stable database built up over the years which are linked to maps they deleted (they played once and deleted after, etc)

With the new missing beatmap fetcher #24450, while importing you now get a notification for every missing beatmap, and if you have the "auto download missing beatmaps" setting enabled it will download every map which is probably not what the person importing wants.

Maybe the fetcher should be disabled when importing from stable?

I also noticed that the nano cards stop loading after a few notifications until you hover over them, but that is probably a different issue.

### Screenshots or videos

https://github.com/ppy/osu/assets/6813986/0bbec373-6475-4ff0-817f-02774536a01b

### Version

2023.924.1

### Logs
[database.log](https://github.com/ppy/osu/files/12726304/database.log)
[input.log](https://github.com/ppy/osu/files/12726305/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12726306/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12726307/network.log)
[performance.log](https://github.com/ppy/osu/files/12726308/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12726309/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12726310/updater.log)

**Comment by peppy** [comment]
Note that logs are not N/A. Please include them.

**Comment by SupDos** [comment]
Edited and added logs

**Comment by cdwcgt** [comment]
> which is probably not what the person importing wants.

At least that's not the case for me.

In fact, I tried to re-implement this function in order to import the stable score and download the missing beatmap at the same time. So I can open automatic download and just AFK.

**Comment by SupDos** [comment]
The issue isn't with the missing beatmap fetcher itself, it's that stable keeps replays (Data/r) even if the beatmap is deleted, and when importing lazer triggers the missing beatmap notification on each one.

I think that someone importing their content from stable wouldn't expect to be notified about scores from maps they deleted (and probably don't even remember about), they'd only expect the maps/scores that are in their song select to be imported. It's great when dragging in an individual replay, but I don't think it's needed when importing from stable.
