### ISSUE TITLE
Skin without skin.ini does not default to latest skin.ini verison

### ISSUE THREAD

**Issue by loma-baldsson** [ppy/osu#24939]
### Type

Cosmetic

### Bug description

**Description:**
In stable, a skin without a `skin.ini` file will default to the latest version, as [documented on the wiki](https://osu.ppy.sh/wiki/en/Skinning/skin.ini#latest). However, in lazer, a skin without a skin.ini file does not show this behaviour.

**Reproduction steps:**
1. Download [this skin](https://github.com/ppy/osu/files/12733048/ryuuta.zip) and open it in both stable and lazer. The skin only has one file, named `fruit-ryuuta.png`.
2. Play any osu!catch map.

**Expected behaviour**
Since the `fruit-ryuuta.png` should only work with skin version 2.3 and lower [as documented here], this sprite should not be used if the skin defaults to the latest version (which is version 2.7 as of posting this issue). As shown in the screenshots below, stable demonstrates this behaviour by ignoring the `fruit-ryuuta.png` file completely and replacing it with the default catcher.

**Actual behaviour**
It uses the `fruit-ryuuta.png` file as the catcher, also shown in the screenshots below

### Screenshots or videos

![The skin as seen in lazer.](https://github.com/ppy/osu/assets/102317848/f7d2f094-33da-4a1b-bfd3-5c621f80f70c)
The skin as seen in lazer.

![The skin as seen in stable.](https://github.com/ppy/osu/assets/102317848/b92f5d37-4384-440b-a0d0-09c5e8d85f80)
The skin as seen in stable.

### Version

osu! 2023.924.1-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/12733054/updater.log)
[runtime.log](https://github.com/ppy/osu/files/12733055/runtime.log)
[performance.log](https://github.com/ppy/osu/files/12733056/performance.log)
[input.log](https://github.com/ppy/osu/files/12733057/input.log)
[database.log](https://github.com/ppy/osu/files/12733058/database.log)

**Comment by peppy** [comment]
Thanks for pointing this out. How did you notice this though? Surely you didn't have a skin which had a `fruit-ryuuta` laying around that suddenly started showing even though it wasn't supposed to?

**Comment by loma-baldsson** [comment]
> Thanks for pointing this out. How did you notice this though? Surely you didn't have a skin which had a `fruit-ryuuta` laying around that suddenly started showing even though it wasn't supposed to?

I had a default skin edit which only changed hitsounds, but it seemed to have a different animation than the built-in "osu! 'classic'" skin so I looked around for a culprit. Skinning info on the wiki pointed to wrong `skin.ini` version, and `fruit-ryuuta.png` seemed like the easiest way to showcase that
