### ISSUE TITLE
Second pass on element sizing (specifically `followpoint`)

### ISSUE THREAD

**Issue by peppy** [ppy/osu#24940]
https://github.com/ppy/osu/pull/24706 was merged, but due to an issue with hot reload I may have missed multiple cases where maximum dimensions need to be applied but are not yet. One is `followpoint`, which needs a maximum size in order to avoid cheesing flashlight by providing visibility outside of the expected region.

For `followpoint`, testing will be required with some skins that create solid lines using follow points (ie. the `maxWidth` should still allow for these skins to work).

Other elements should also be re-checked using the test scene.

**Comment by peppy** [comment]
@RockRoller01 could I bug you for some stats here on `followpoint` usage to guide adding some kind of lenient restrictions to it?

**Comment by bdach** [comment]
@peppy I actually asked for `followpoint` data already last time around in advance. See https://gist.github.com/RockRoller01/0a25249c86fda4c5a0c3d8fb97c28041#followpoint, https://gist.github.com/RockRoller01/0a25249c86fda4c5a0c3d8fb97c28041#followpoint-0.

Plotted:

![image](https://github.com/ppy/osu/assets/20418176/fe8a675e-7a8a-433e-969d-5f804bebb357)

![image](https://github.com/ppy/osu/assets/20418176/537b8191-84f5-4ed7-b84b-350a99e7b7d9)

Most skins actually seem to turn off followpoints via 1px sprites so...

Width pretty much has to be no lower than 128; height is debatable. One possible threshold is 50px (128x50 will break 0.53% of skins). Another is 128x128 (breaks 0.15% of skins).

**Comment by peppy** [comment]
Let's go with 128x50 for now.
