### ISSUE TITLE
Waveform display in editor with long songs causes lag spikes

### ISSUE THREAD

**Issue by verarr** [ppy/osu#24951]
### Type

Performance

### Bug description

The waveform display thingy _(or at least I suspect that's what's causing this)_ when setting up a timing point for a longer song slows down the _update_ thread and does way too much memory allocation _(IMO, I don't know how much is bad on .NET)_.

This causes the **metronome to skip and/or delay the ticks** significantly, sometimes making the task of timing such a beatmap correctly impossible. _Probably_ reproducible with any kind of audio that's longer than ~15 minutes. Mainly affects mapping song compilations.

I've also managed to make the game crash twice because of this, with the audio output outright freezing and the whole process just exiting (exit code still `0` which is weird) a couple of seconds after. I can't reproduce it now, but I did reproduce a case where it halted my computer in its entirety _(never happened to me with osu!lazer before, but this one might be on me)_.

I don't think this is a duplicate of #20918, because the issue there is probably caused by the unconventional amount of timing points. **#23905 seems very similar**, but that one impacts the _draw_ thread _(and it was closed already...)_, and this issue is present **even at the start** of a long beatmap.

Originally discovered on Arch Linux, but reproduced with Linux Mint 21.2 + Flatpak osu!lazer _(just so that I clear myself of having problems just because of Arch)_. _I don't know about Windows._

### Screenshots or videos

Here's a demonstration with a 30 minute 200BPM metronome audio that I generated with Audacity: https://youtu.be/HXiu70Sx8Eo

Another one with a 40-minute actual playlist (stolen from YouTube) with a more dramatic performance impact: https://youtu.be/wsn-_NJjQhQ

Finally, the video I recovered from the computer halting incident: https://youtu.be/YKNLQEgYP3g

_(Had to murder video quality so that osu! can run in peace while recording...)_

### Version

2023.924.1

### Logs

_Only attaching logs I think are relevant._

#### First video (mild performance issues) _(also empty for about half an hour, I'm sorry...)_

[runtime.log](https://github.com/ppy/osu/files/12742756/runtime.log)

_Notable: The message `Waveform resampled with ... points (original ...)` occurred over 23,000 times (for about a sum of ~30 minutes (??) of experimenting with this)._

[performance.log](https://github.com/ppy/osu/files/12742757/performance.log)

_Notable: Doesn't contain any messages from the timeframe in which the previously mentioned `Waveform resampled with ...` messages occurred. Less notable: it seems to complain a LOT about some Roboto fonts being made into a texture atlas (??) on a non-background thread._

[performance-input.log](https://github.com/ppy/osu/files/12742758/performance-input.log)
[performance-audio.log](https://github.com/ppy/osu/files/12742759/performance-audio.log)

_Actual audio output was not an issue, and the frame times are nothing outrageous._

[performance-update.log](https://github.com/ppy/osu/files/12742760/performance-update.log)

_No call stacks were recorded in this, only contains frame lengths in ms, so probably useless._

[performance-draw.log](https://github.com/ppy/osu/files/12742761/performance-draw.log)

_I don't know much about the multithreading in lazer, but the timestamps in this one match up pretty closely with the ones in `performance-update.log` making me think it is somewhat dependent on the update thread._

#### Second video (stronger performance impact)

[runtime.log](https://github.com/ppy/osu/files/12743367/runtime.log)

_This one also contains the messages about resampling a waveform._

[performance.log](https://github.com/ppy/osu/files/12743371/performance.log)

_Same goes for this one with the Roboto fonts._

[performance-input.log](https://github.com/ppy/osu/files/12743369/performance-input.log)
[performance-audio.log](https://github.com/ppy/osu/files/12743370/performance-audio.log)
[performance-update.log](https://github.com/ppy/osu/files/12743368/performance-update.log)
[performance-draw.log](https://github.com/ppy/osu/files/12743372/performance-draw.log)

#### When my computer went kaboom

[runtime.log](https://github.com/ppy/osu/files/12743420/runtime.log)
[performance.log](https://github.com/ppy/osu/files/12743423/performance.log)
[performance-input.log](https://github.com/ppy/osu/files/12743418/performance-input.log)
[performance-audio.log](https://github.com/ppy/osu/files/12743419/performance-audio.log)
[performance-update.log](https://github.com/ppy/osu/files/12743421/performance-update.log)
[performance-draw.log](https://github.com/ppy/osu/files/12743422/performance-draw.log)

_Notice how these don't include the messages usually sent when the game is shutting down._

**Comment by peppy** [comment]
Can you reproduce using https://dev.ppy.sh/beatmapsets/972#osu/9007?

and if so, does the performance issue still appear when hovering the waveform display?

![osu! 2023-09-28 at 05 42 18](https://github.com/ppy/osu/assets/191335/4187fc6f-4d3f-4549-910f-b0484f189bc0)

and if so, does the performance issue still appear when in compose mode?

**Comment by verarr** [comment]
> Can you reproduce using https://dev.ppy.sh/beatmapsets/972#osu/9007?

**Yes** (sometimes). There were only a few delayed ticks, but still had a lot of skips.

> and if so, does the performance issue still appear when hovering the waveform display?

**Yes.**

> and if so, does the performance issue still appear when in compose mode?

**No.** _Compose_ mode is fine.

### Logs and videos

#### At the start of the beatmap and starting from the middle

https://youtu.be/WNcXtkyhEUg
https://youtu.be/wGaEA2QMhSs

[runtime.log](https://github.com/ppy/osu/files/12752916/runtime.log)
[performance.log](https://github.com/ppy/osu/files/12752918/performance.log)
[performance-input.log](https://github.com/ppy/osu/files/12752920/performance-input.log)
[performance-audio.log](https://github.com/ppy/osu/files/12752922/performance-audio.log)
[performance-update.log](https://github.com/ppy/osu/files/12752919/performance-update.log)
[performance-draw.log](https://github.com/ppy/osu/files/12752921/performance-draw.log)

#### Comparison to compose mode

https://youtu.be/fvmkMKY0ylI

[runtime.log](https://github.com/ppy/osu/files/12752991/runtime.log)
[performance.log](https://github.com/ppy/osu/files/12752996/performance.log)
[performance-input.log](https://github.com/ppy/osu/files/12752993/performance-input.log)
[performance-audio.log](https://github.com/ppy/osu/files/12752995/performance-audio.log)
[performance-update.log](https://github.com/ppy/osu/files/12752992/performance-update.log)
[performance-draw.log](https://github.com/ppy/osu/files/12752994/performance-draw.log)

**Comment by peppy** [comment]
That's quite surprising. I can get a few small glitches, but nothing on the level you are. Will require further investigation. Potentially something specific to linux/GC (@bdach can you see if you can repro anything as bad as shown in this issue?)

**Comment by bdach** [comment]
I don't get such large freezes but the update thread does spike significantly on every beat and my box does turn the jets on when playing the track so there does seem to be something going on there. A lot of GCs, too.

**Comment by bdach** [comment]
In profiling:

![1695974943](https://github.com/ppy/osu/assets/20418176/25cf65a2-d507-4bf1-af50-357ae9893ad6)

99% this will be due to [this code](https://github.com/ppy/osu-framework/blob/7f20b43bf182f7028d20844deca43b2735f381ae/osu.Framework/Graphics/Audio/WaveformGraph.cs#L161-L173). The comment gives off an impression that `RequiredParentSizeToFit` is used insted of `MiscGeometry` to avoid invalidations happening due to position changing. But in this particular case `RequiredParentSizeToFit` is _also_ getting invalidated.

**Comment by peppy** [comment]
I did notice minor spikes, but I'm just trying to figure out how that becomes game crippling performance as shown in the videos. Maybe running as debug or something similar?

**Comment by bdach** [comment]
Yeah not sure about that part. I only get spikes on update thread, rather than draw thread tanking shown on the videos above.
