### ISSUE TITLE
Changing HT/DT speed with hold Shift doesn't change the value with 0.1 snapping

### ISSUE THREAD

**Issue by akiya-nagatsuka** [ppy/osu#24958]
### Type

Game behaviour

### Bug description

I am not sure It's intended or regression, but after recent update I cannot change the speed multiplier value snapping by 0.1x

### Version

2023.924.1

### Logs

[network.log](https://github.com/ppy/osu/files/12751541/network.log)
[osu!auth.log](https://github.com/ppy/osu/files/12751542/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/12751544/runtime.log)
[session.log](https://github.com/ppy/osu/files/12751545/session.log)
[update_success.log](https://github.com/ppy/osu/files/12751546/update_success.log)

**Comment by bdach** [comment]
- Logs are from wrong version of game
- Change was intentional (https://github.com/ppy/osu/pull/24795)

**Comment by akiya-nagatsuka** [comment]
@bdach 
1. Where can I find logs for the current version?
2. I don't see anything about my issue in the PR. Even if It's intentional can I ask the objectives? I remember @peppy said that mostly users don't want to change the speed multiplier with 0.01x precision and It's ok to trim it to 0.1x so the user can easily adjust to 1.1x. 1.2x, 1.3x, 1.4x, 1.5x and so on. Also I find it convenient to use Shift + drag to easily adjust the value. Since It was removed I need to drug multiple times to set it 1.2x, not 1.21x or 1.19x

**Comment by akiya-nagatsuka** [comment]
@bdach Can you check is it proper logs now? Used `%AppData%/Roaming/osu/logs` instead of `%AppData%/Local/osu/logs`

[updater.log](https://github.com/ppy/osu/files/12773571/updater.log)
[performance.log](https://github.com/ppy/osu/files/12773565/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/12773566/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12773567/performance-draw.log)
[runtime.log](https://github.com/ppy/osu/files/12773570/runtime.log)
[performance-input.log](https://github.com/ppy/osu/files/12773568/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12773569/performance-update.log)
[database.log](https://github.com/ppy/osu/files/12773561/database.log)
[input.log](https://github.com/ppy/osu/files/12773562/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12773563/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12773564/network.log)

**Comment by bdach** [comment]
1. The change that causes this behavior is https://github.com/ppy/osu/pull/24795/files#diff-64e18c7cd25acae4988c88bd09b4c788b8dad44c1767d2757ab5f86fefcf697fR13. I'm not entirely sure why it was done, @peppy might know better, but I assume it was 100% intentional.
2. Those are correct lazer logs yes. They aren't really needed for this particular issue though.

**Comment by akiya-nagatsuka** [comment]
@bdach Thank you for confirming the logs
I understand you devs made it intentionally so I believe in your vision, but since I still don't see any reasons to remove this feature from user perspective I stay with the same opinion on this as user experience regression.
Maybe @peppy can clarify the vision on this

**Comment by peppy** [comment]
Yes the change was intentional. Changing by 0.1 should be done by holding a modifier, but this implementation should be across all slider bars everywhere.

Probably will be addressed via https://github.com/ppy/osu/discussions/24900 or similar framework changes.
