### ISSUE TITLE
Blurred backgrounds do not render correctly on an M1 iPad Pro

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#24960]
### Type

Game behaviour

### Bug description

Likely shader related. Opening this up for tracking.

### Screenshots or videos

![](https://media.discordapp.net/attachments/589331078574112768/1156927177892319303/IMG_0026.png?ex=6516bfe5&is=65156e65&hm=9353b0783b16dcd86065645ea32a52ab325d94c9cfa7ec6f0d930790007c24a3&=&width=1972&height=1377)

### Version

2023.924.1-lazer

### Logs

-

**Comment by GSculerlor** [comment]
also broke on M2 fwiw ![image](https://github.com/ppy/osu/assets/6506864/db5e947d-b447-42d1-9682-c91f03e2f10d)

**Comment by bdach** [comment]
If it is related to blur then likely suspect is https://github.com/ppy/osu-framework/pull/5979.
