### ISSUE TITLE
Audio files and image files dont show up when creating a map

### ISSUE THREAD

**Issue by GreenWeegeeCantCode** [ppy/osu#24971]
### Type

Other

### Bug description

Hi.

So i wanted to try to make a map (an osu!taiko one) on mobile using osu!lazer, however i cant pick a song or background image since it doesnt show anything, only the folders.

### Screenshots or videos

https://github.com/ppy/osu/assets/145769578/8db2b5fb-4722-4431-846a-ffe4c6a975c0

### Version

2023.924.1-lazer

### Logs

[My Logs.zip](https://github.com/ppy/osu/files/12765616/My.Logs.zip)

**Comment by toadsworth-jr** [comment]
https://github.com/ppy/osu/issues/11911

**Comment by GreenWeegeeCantCode** [comment]
The audio file im trying to use is an mp3, and i have like 15 png images in my downloads but none of the files show up.

**Comment by bdach** [comment]
Duplicate of aforementioned issue.

As a workaround you can enable image/audio file access to the app via android settings.
