### ISSUE TITLE
Skin inconsistency between release and master

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#24973]
### Type

Game behaviour

### Bug description

These screenshot were used using the same folder (i renamed osu-development to osu and ran release, not logged in)

### Screenshots or videos

| 2023.924.1 | master |
|--------|--------|
| ![image](https://github.com/ppy/osu/assets/53081750/5ef6c49e-78aa-49d1-95bf-36e9d73b0953) | ![image](https://github.com/ppy/osu/assets/53081750/ab70dcfa-03e8-4f2d-8c03-5c308df0953c) | 
| ![image](https://github.com/ppy/osu/assets/53081750/bc6a4276-6bce-41ba-8135-6cea9030947f) | ![image](https://github.com/ppy/osu/assets/53081750/e238b366-b4af-4c4f-8283-3711c3c0f0ad) |
| ![image](https://github.com/ppy/osu/assets/53081750/4140f1f4-d4b1-4db0-bc21-da4abf499872) | ![image](https://github.com/ppy/osu/assets/53081750/e2b3e207-b851-408a-a7c1-f34ca150a175) |

Skins: https://osu.ppy.sh/community/forums/topics/1792308?n=1
https://drive.google.com/file/d/1t6-Hfz5mG4IxATLjLcAGmyEEshZob_kp/view?usp=sharing
(i imagine any beatmap will do, but here we go) Beatmap: https://osu.ppy.sh/beatmapsets/1760668#osu/4036420

### Version

https://github.com/ppy/osu/commit/09c9baadec535bed2869d897764d340902868932

### Logs

[performance.log](https://github.com/ppy/osu/files/12769027/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12769028/runtime.log)
[database.log](https://github.com/ppy/osu/files/12769029/database.log)
[input.log](https://github.com/ppy/osu/files/12769030/input.log)

**Comment by frenzibyte** [comment]
This is one of the after-effects of https://github.com/ppy/osu/pull/24706, will investigate further.

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/pull/24975 should fix the incorrect rendering of the glyphs in the first screenshots row. For the hit circles, they look to be over the size of the hit circle's dimensions for the drop-shadow effect:

<img width="652" alt="CleanShot 2023-09-30 at 01 44 26@2x" src="https://github.com/ppy/osu/assets/22781491/9d8f4140-a439-459e-81bd-7a39a839cb15">

With #24975, it will render as follows:

<img width="652" alt="CleanShot 2023-09-30 at 01 44 26@2x" src="https://github.com/ppy/osu/assets/22781491/0b21d48b-5916-41b0-a34a-ffec4eaf0ef5">

We could add bit more leniency to the hit circle's maximum dimensions to allow for such effects, maybe an absolute number applied within `WithMaximumSize` itself. @peppy thoughts?

**Comment by frenzibyte** [comment]
To keep this thread updated, @RockRoller01 has [mentioned](https://discord.com/channels/188630481301012481/188630652340404224/1157626126550700122) bringing up some numbers of gameplay elements' dimensions across countless skins in a couple of days, which we can use to alter the current specifications we had set.

**Comment by Loreos7** [comment]
| Release  | Master |
| ------------- | ------------- |
| ![image](https://github.com/ppy/osu/assets/86934170/a12bdb5c-13c2-4294-81d9-56e5afe53e42) | ![image](https://github.com/ppy/osu/assets/86934170/b0612861-d883-4e99-9040-84d55c04e440) |
| ![image](https://github.com/ppy/osu/assets/86934170/757497c4-5194-49c8-ac12-ebd739c37d19) | ![image](https://github.com/ppy/osu/assets/86934170/5584ed95-96ce-4065-b92b-c039f251cd1a) |
| ![image](https://github.com/ppy/osu/assets/86934170/6fcc6996-22a4-431b-a64c-e6432f8bcaa9) | ![image](https://github.com/ppy/osu/assets/86934170/cb5d07ad-c92d-4f7b-87b0-90873fa9afec) |

Skins: BTMC Freedom Dive, Bacon boi 1.0 blue

**Comment by peppy** [comment]
Of note, this needs to be resolved before the next release. Increasing by the amount required to support the skin above would be a good start if we don't hear back from rockroller or find the time to investigate further ourselves.

**Comment by RockRoller01** [comment]
I've gone and grabbed stats for all the files that @bdach listed on [discord](https://discord.com/channels/188630481301012481/188630652340404224/1159236590367952956). For animated files I checked for their base version and the first frame, checking all frames didnt really feel worth it. Overall this goes over ~4200 skins.

https://gist.github.com/RockRoller01/0a25249c86fda4c5a0c3d8fb97c28041

If stats for any other files are needed just let me know, now that I have working code it takes no time to get them.

**Comment by Loreos7** [comment]
I can still see the small difference. There are harsh shadows appear near a note.
| Release  | Master with https://github.com/ppy/osu/pull/24975 |
| ------------- | ------------- |
| ![image](https://github.com/ppy/osu/assets/86934170/641abed7-fe0b-4467-b9bc-1dc4d5900217) | ![image](https://github.com/ppy/osu/assets/86934170/18e257e1-dc7a-46e2-b274-1dcc50561205) |
| ![image](https://github.com/ppy/osu/assets/86934170/9f2b5f85-48fc-4bb1-884a-62b4093342e4) | ![image](https://github.com/ppy/osu/assets/86934170/4b3f4dcf-142a-405b-834d-d44c003235f8) |
