### ISSUE TITLE
Top play score is calculated not properly

### ISSUE THREAD

**Issue by akiya-nagatsuka** [ppy/osu#24981]
### Type

Game behaviour

### Bug description

The play with full combo and better accuracy is considered as much worse play in the leaderboard than 1 miss play with significantly worse accuracy.

### Screenshots or videos

In-game screenshots
![osu_2023-10-01_15-03-21](https://github.com/ppy/osu/assets/38129679/d36185d9-7f61-469b-9778-dcf7087d0d2f)
![osu_2023-10-01_15-03-38](https://github.com/ppy/osu/assets/38129679/d9aa1056-bdfa-493e-b50b-d9401c8c5339)

Replays:
https://drive.google.com/file/d/1yUon5huT9wm9kiCI5NhsxcYsfOVSPz9k/view?usp=drive_link
https://drive.google.com/file/d/1usstUACKWnldHUFhlbsfXe6lNhgngZyt/view?usp=drive_link

### Version

2023.924.1

### Logs

[database.log](https://github.com/ppy/osu/files/12776521/database.log)
[input.log](https://github.com/ppy/osu/files/12776522/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12776523/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12776524/network.log)
[performance.log](https://github.com/ppy/osu/files/12776525/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/12776526/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12776527/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/12776528/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12776529/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12776530/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12776531/updater.log)

**Comment by bdach** [comment]
These scores were set on two lazer versions with completely different scoring algorithms. The scoring algorithms itself 100% changed since ("score V2" went live in May), the mod multipliers likely did so too.

This will be resolved by an online leaderboard wipe, when we're ready for one. Other than that I see no reason to track this as an issue as we know very well this can happen.
