### ISSUE TITLE
Colour picker glitches out during appear animation

### ISSUE THREAD

**Issue by Kuina-chan** [ppy/osu#24987]
### Type

Game behaviour

### Bug description

When choosing a new combo colour, sometime it will flickering and display the incorrect color for the set, as like in the video

### Screenshots or videos

https://github.com/ppy/osu/assets/75318520/3d15f79c-541f-47d8-b8cc-9f3118a5dd2a

### Version

2023.924.1-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/12780785/updater.log)

[runtime.log](https://github.com/ppy/osu/files/12780783/runtime.log)

[database.log](https://github.com/ppy/osu/files/12780777/database.log)
[input.log](https://github.com/ppy/osu/files/12780778/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12780779/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12780780/network.log)
[performance.log](https://github.com/ppy/osu/files/12780781/performance.log)

**Comment by peppy** [comment]
Windows / Direct X / NVIDIA GeForce GTX 1650

**Comment by bdach** [comment]
Cannot reproduce on my hardware, for whatever that's worth (windows, d3d11, RTX 3060M).

**Comment by EVAST9919** [comment]
Can't reproduce, but in the video it looks like it's only flickering at `hue = 0`? So probably something precision-wise in the hsv to rgb function would be my guess.
