### ISSUE TITLE
Tournament client doesn't always fetch beatmap backgrounds

### ISSUE THREAD

**Issue by DRCallaghan** [ppy/osu#24993]
### Type

Crash to desktop

### Bug description

The showcase function is largely broken, with map backgrounds not being fetched properly and neither showcase.mp4 nor main.mp4 showing up as intended on the bottom bar. The attached video shows the issue being replicated. 

Note that during the attached video, my showcase video is labeled as main.mp4 in my tournament folder, though the same issue occurs with it labled as showcase.mp4. Other parts of the client seem to work for me as intended, just showcase seems to be bugged.

See video here: https://youtu.be/FhQqpYjpsEM

### Version

2023.924.1

### Logs

[network.log](https://github.com/ppy/osu/files/12784080/network.log)
[performance.log](https://github.com/ppy/osu/files/12784082/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12784083/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12784084/updater.log)
[database.log](https://github.com/ppy/osu/files/12784085/database.log)
[input.log](https://github.com/ppy/osu/files/12784086/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12784087/legacy-ipc.log)

**Comment by bdach** [comment]
Logs look clean, so that's a dead end.

- Are you able to determine the last working version?
- Long shot but let's try: please locate `framework.ini` in `%AppData%/osu/logs`. Locate the line starting with `HardwareVideoDecoder` and change it to `HardwareVideoDecoder = DXVA2`. Restart tournament client. Does that do anything?

**Comment by DRCallaghan** [comment]
Still the same after that change. Unfortunately the last working version I have currently is 2023.513.0. I can try downloading old versions and using those until I find the last working version, though.

**Comment by bdach** [comment]
If you can nail down which release broke this more specifically it would be a huge help. Alternatively you can try supplying the video files you're using so I may try and reproduce on my hardware, if that is an option.

> though I'm not sure where I can find downloads of old builds.

They'll be under "Assets" on the [releases page](https://github.com/ppy/osu/releases).

**Comment by DRCallaghan** [comment]
Nailed down the latest working version: [2023.815.0](https://github.com/ppy/osu/releases/tag/2023.815.0). So the version that caused the issue is [2023.908.0](https://github.com/ppy/osu/releases/tag/2023.908.0).

**Comment by bdach** [comment]
Hmm. The SSBO changes from that release have since been reverted. But that release also contains the D3D11VA decoder addition, which I can tell _for sure_ your tournament client wants to use from the logs in the OP. But I would expect forcing it back to DXVA2 [as I attempted to above](https://github.com/ppy/osu/issues/24993#issuecomment-1743251592) to fix it.

Can you attach logs again after setting the hardware decoder to DXVA2? Also, another nuclear option to try would be to disable hardware video decoding entirely by setting

```
HardwareVideoDecoder = None
```

@FreezyLemon able to assist here perhaps?

**Comment by DRCallaghan** [comment]
Here's what the logs look like having swapped to DXVA2. This change didn't work on the latest build and also doesn't work for 2023.908.0.

[performance.log](https://github.com/ppy/osu/files/12785684/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12785685/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12785686/updater.log)
[database.log](https://github.com/ppy/osu/files/12785687/database.log)
[input.log](https://github.com/ppy/osu/files/12785688/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12785689/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12785690/network.log)

For convenience, here are the logs on the latest working build 2023.815.0 with DXVA2.
[runtime.log](https://github.com/ppy/osu/files/12785715/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12785716/updater.log)
[database.log](https://github.com/ppy/osu/files/12785717/database.log)
[input.log](https://github.com/ppy/osu/files/12785718/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12785719/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12785720/network.log)
[performance.log](https://github.com/ppy/osu/files/12785721/performance.log)

Lastly, on the earliest broken build 2023.908.0, here are the logs and a short video of what happens when I set `HardwareVideoDecoder = None`. The showcase video file flashes briefly before disappearing again on each map change.
[runtime.log](https://github.com/ppy/osu/files/12785742/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12785743/updater.log)
[database.log](https://github.com/ppy/osu/files/12785744/database.log)
[input.log](https://github.com/ppy/osu/files/12785745/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12785746/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12785747/network.log)
[performance.log](https://github.com/ppy/osu/files/12785748/performance.log)

https://github.com/ppy/osu/assets/106406900/d315c974-e966-46bd-a62b-d322bf0bebb1

**Comment by DRCallaghan** [comment]
Here's my bracket.json: 
[bracket.zip](https://github.com/ppy/osu/files/12785949/bracket.zip)
I put it in a zip file since apparently github doesn't support uploads of .json files. All the qualifier data is preloaded in my client.

**Comment by peppy** [comment]
@DRCallaghan are you the person that previously reported the beatmap backgrounds not display? If not, I believe there was one other report of this.

**Comment by peppy** [comment]
@DRCallaghan the logs you provided don't match the video. Could you possible make a very short video and attach `runtime.log` and `network.log` from the same run as in the video? You don't need to show any of the setup process, just the issue happening a few times then quit.

**Comment by DRCallaghan** [comment]
@peppy I reported it in the discord dev server 2 days ago as well, but this is the first issue I've put on github about it. Here are the log files and video requested.
[network.log](https://github.com/ppy/osu/files/12804489/network.log)
[runtime.log](https://github.com/ppy/osu/files/12804490/runtime.log)

https://github.com/ppy/osu/assets/106406900/8ec5cd04-5fba-4fd8-9da3-4d43e0e05cc1

**Comment by DRCallaghan** [comment]
Seems like the map fetching issue has been fixed, but the gray bar across the map stats persists. Is that being worked on? Should I open a separate issue?

**Comment by peppy** [comment]
> Seems like the map fetching issue has been fixed

Very weird, we haven't made any fixes yet.

> but the gray bar across the map stats persists

This was an intentional design change. I'll see if we can restore the previous behaviour or improve things somehow.
