### ISSUE TITLE
lazer auto mod doesnt work 

### ISSUE THREAD

**Issue by maothebest** [ppy/osu#24994]
### Type

Game behaviour

### Bug description

Only shows the beatmap song and the effect with 0% dim background (preset 100%)

it happened after I edit the beatmap and replace it to local. I'm not sure if this happened before the edit or not. Since this is my first time to use cinema mod after i switched into lazer.

### Screenshots or videos

https://github.com/ppy/osu/assets/146758549/a56cdb7e-f4bf-462e-a623-461926d72770

### Version

2023.924.1-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/12784699/network.log)
[performance.log](https://github.com/ppy/osu/files/12784700/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12784701/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12784702/updater.log)
[database.log](https://github.com/ppy/osu/files/12784703/database.log)
[input.log](https://github.com/ppy/osu/files/12784704/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12784705/legacy-ipc.log)

**Comment by bdach** [comment]
I don't understand this issue report. What were you expecting to see, specifically?


> it happened after I edit the beatmap and replace it to local.

What does this mean? Which beatmap?

**Comment by maothebest** [comment]
oh shit, my bad
i just got confused the auto mod with the cinema mod
i thought they are the same thing
just ignore this post
