### ISSUE TITLE
Beatmap editor's combo color selection blinking when hue slider at the beginning

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#25017]
### Type

Cosmetic

### Bug description

I was just about to pick the combo colors and when I added the 4th combo the color displayed started blinking through all the hues (see video: <https://www.youtube.com/watch?v=Fb4bckFZPcE>).

### Screenshots or videos

<img width="1280" alt="osu! Screenshot 2023 10 05 - 09 05 00 21" src="https://github.com/ppy/osu/assets/67008763/421d32b0-1e8f-4972-a8fc-91d23913e574">
<img width="1280" alt="osu! Screenshot 2023 10 05 - 09 04 53 49" src="https://github.com/ppy/osu/assets/67008763/74252dbb-3dfc-40f6-806f-b0fcbf1f60fe">

### Version

2023.924.1-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/12813396/network.log)
[performance.log](https://github.com/ppy/osu/files/12813397/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12813398/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12813399/updater.log)
[database.log](https://github.com/ppy/osu/files/12813400/database.log)
[input.log](https://github.com/ppy/osu/files/12813401/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12813402/legacy-ipc.log)

**Comment by bdach** [comment]
There's no video here?

**Comment by yesseruser** [comment]
Sorry, I'm having problems uploading it.

**Comment by yesseruser** [comment]
Here: [Video on YouTube](https://www.youtube.com/watch?v=Fb4bckFZPcE)

**Comment by yesseruser** [comment]
The "Screenshots or videos field" seems to be unable to display links.

**Comment by bdach** [comment]
Seems like potentially duplicate / same issue as https://github.com/ppy/osu/issues/24987. Should be fixed next release. If it isn't please report back and we'll reopen.

**Comment by yesseruser** [comment]
Hello, the issue #24987 is a DirectX issue, however, I was using OpenGL as my renderer.

**Comment by yesseruser** [comment]
Okay. Thank you.
