### ISSUE TITLE
osu! doesn't open on Android 14 (Realm issue)

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#25020]
### Type

Crash to desktop

### Bug description

Whenever I try starting osu! after installing Android 14 (that just released) on my phone it crashes.

### Screenshots or videos

This is all that appears when starting the app (the app icon):
![Screenshot_20231005-135924](https://github.com/ppy/osu/assets/67008763/22ff55b4-e6fc-4eb1-9cf5-0bcb6cf14138)
It also said the app crashed.

### Version

2023.924.1-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/12818021/runtime.log)
[performance.log](https://github.com/ppy/osu/files/12818022/performance.log)
[network.log](https://github.com/ppy/osu/files/12818024/network.log)
[database.log](https://github.com/ppy/osu/files/12818026/database.log)

**Comment by peppy** [comment]
I've reported this one to realm: https://github.com/realm/realm-dotnet/issues/3458

**Comment by kiburtse** [comment]
Hi, @peppy! Could you provide a bit more details under relevant issue in [realm core](https://github.com/realm/realm-core/issues/7037)?

**Comment by peppy** [comment]
@yesseruser can you confirm things were working before upgrading to android 14? And could you give more details on how you upgraded (was this an official release from your manufacturer? is it beta?)

**Comment by bdach** [comment]
I guess for general information I won't get android 14 updates on my only test device until apparently November so I cannot test this at this time.

**Comment by yesseruser** [comment]
@peppy yes, before upgrading everything was working just fine.

**Comment by matthew-5pl** [comment]
Same experience with my Pixel 7a running Android 14 (build `UP1A.231005.007`, stable, installed through OTA). 
Lazer version `2023.1008.1`.

**Comment by peppy** [comment]
Thanks for confirming. It looks like another developer has run into the same issues, so it's safe to say it's not specific to our project. Let's wait for word from the realm team.

**Comment by peppy** [comment]
Looks like this is going to require changes from our end (see https://github.com/realm/realm-core/issues/7037#issuecomment-1760840766).

I'm not really aware of the current situation with android storage, but are we not already storing internally? Is the user in this thread choosing to move their game storage elsewhere? If so, with this knowledge, we're going to have to either disable that functionality, or selectively only store user data files externally while having the database internal.

Which sounds completely fucked and destroys any portability of installation, but is what it is I guess.

**Comment by bdach** [comment]
> are we not already storing internally?

Apparently not: https://github.com/ppy/osu-framework/blob/cb21c4efc4b6aa4143fb4b746fc5e25292432c49/osu.Framework.Android/AndroidGameHost.cs#L72-L73

The screwed part is going to be figuring out how to migrate users. [Android docs on this](https://developer.android.com/training/data-storage/use-cases#write-files-secondary-storage-volumes) are terrible, I can't understand any of it. So I can't personally act on this until I get OS upgrades on my test device.

**Comment by peppy** [comment]
Just waiting for the next release of android to ban the same file operations on the root filesystem, and destroy realm completely...

**Comment by Joehuu** [comment]
FWIW, osu! opens on Android 14 QPR1 beta on my Pixel 6a and [someone on Pixel 7](https://discord.com/channels/188630481301012481/188630652340404224/1155915263418572880) with the graphics being weird:
![Screenshot_20231013-140930](https://github.com/ppy/osu/assets/35318437/f6105ce0-2675-4184-8a32-8ef3a69d3135)

The thing is the changes in QPR1 won't be in stable until December (or approximately 3 months)...

**Comment by AAGaming00** [comment]
> until I get OS upgrades on my test device.

Does your device support DSU?

**Comment by AAGaming00** [comment]
> > are we not already storing internally?
> 
> Apparently not: https://github.com/ppy/osu-framework/blob/cb21c4efc4b6aa4143fb4b746fc5e25292432c49/osu.Framework.Android/AndroidGameHost.cs#L72-L73
> 
> The screwed part is going to be figuring out how to migrate users. [Android docs on this](https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage) are terrible, I can't understand any of it. There's like a flag to keep previous behaviour, but it doesn't work on android 11, unless you set _another_ flag, or something??? So I can't personally act on this until I get OS upgrades on my test device.

Seems like the actual issue was [linked](https://issuetracker.google.com/issues/304123373?pli=1) there

**Comment by qwertyuiii-code** [comment]
and how to fix its issue?

**Comment by peppy** [comment]
There's no fix, please wait patiently.

**Comment by OnlyCS** [comment]
A fix was proposed in the realm-core issue

[Link to that comment](https://github.com/realm/realm-core/issues/7037#issuecomment-1784855359)

**Comment by yesseruser** [comment]
How long could you estimate this will take for Google to fix?

**Comment by FileOfName** [comment]
osu! opens on my pixel after the [November update](https://support.google.com/pixelphone/thread/242705137/google-pixel-update-november-2023?hl=en). 
However, the graphical glitches are still present.

**Comment by Joehuu** [comment]
Closing as resolved and tracking the graphical glitches in https://github.com/ppy/osu/issues/25189.
