### ISSUE TITLE
Background stays dimmed during break times

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2502]
This feature was just changed (on 100% dim) on stable to match lazer's current behaviour, which is to keep the background dim the same during gameplay and break time. I would argue that one of the few times you actually see the background is during break times and thus there should be an option to show the background during them.

I don't know what the general consensus around this issue is as I have not heard any player mention that the background should stay dimmed (even if it's set to 100% or something)

**Comment by Frontear** [comment]
This most likely lies on personal preference. Personally, I don't like the backgrounds, and keeping dim just helps out with that. Perhaps this can be an option?

**Comment by peppy** [comment]
Break dim changes have not been implemented yet, and should be done so to match stable behaviour.

**Comment by peppy** [comment]
Moving this out of milestone. Existing implementation isn't really ready, plus this is a lower priority feature.
