### ISSUE TITLE
No support for filtering favourites beatmaps in song select list

### ISSUE THREAD

**Issue by akiya-nagatsuka** [ppy/osu#25038]
### Type

Game behaviour

### Bug description

Please refer to the [discussion](https://github.com/ppy/osu/discussions/22798)

### Version

2023.924.1

### Logs

N/A

**Comment by peppy** [comment]
Would be appreciated if you could post in the issue thread rather than making a duplicate.

**Comment by akiya-nagatsuka** [comment]
Hello @peppy
I checked through all [issues](https://github.com/ppy/osu/issues) and didn't find this issue, so is was objective to open a new one. If there is another open or closed "issue" I would be appreciated If you can share it so we can use it for tracking ^^

**Comment by akiya-nagatsuka** [comment]
Sorry, I guess I got your point now. Did you mean I should have to write something in the discussion or what? For me personally It's an issue and there is nothing to discuss, so I pressed "Convert the discussion to issue", but I guess something got wrong XD 
<img width="235" alt="Screenshot 2023-10-14 at 1 46 40" src="https://github.com/ppy/osu/assets/38129679/dc06fb4f-ec1b-483c-bb01-6b973e793e8d">

**Comment by peppy** [comment]
Leave that to us.
