### ISSUE TITLE
Exiting and then quickly entering songselect will just display menu background for few seconds

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2503]
Even had it throw an error once: ``Disposed Drawables may never get a parent and return to the scene graph.`` Line 1303 of ``Drawable.cs``. Wasn't able to get stacktrace because only had it happen once. 

Easy to reproduce by just pressing ``Esc`` + ``P`` + ``P`` while in songselect.

**Comment by Aergwyn** [comment]
Maybe kinda related (not necessarily with SongSelect):
Try `E` -> `ESC` and repeat to switch between main menu and editor. Eventually I managed to get the error that an inactive screen isn't allowed to push or something (recalling from memory).
I once actually managed to get in a state where no menu was displayed at all and I was stuck there on the empty background of the main menu. I couldn't reproduce and try to debug that one though. :(

**Comment by LittleEndu** [comment]
Transitioning to song selection still hangs for a good second.
