### ISSUE TITLE
Clamped resolution on approach circles breaks skins with a "glow" effect

### ISSUE THREAD

**Issue by EriDere** [ppy/osu#25044]
### Type

Cosmetic

### Bug description

The recently imposed limits on the size on hitobjects cause approach circles with a "glow" effect to appear cut-off and broken. Many skins use such an effect, so the size limit on approach circles should be increased to account for this.

From limited testing within my own library of skins, approach circles are the only element I have found in the standard game mode that has this issue on a significant number of skins. Glow effects on hitcircles and followcircles seem far more forgiving.

Attached are screenshots of 3 examples I encountered of this issue. If specific skins/assets are needed, I'm happy to oblige. 

### Screenshots or videos

![osu_2023-10-07_23-44-44](https://github.com/ppy/osu/assets/75809251/ba0cdd34-20d0-4c45-a116-baa6de4fbf9c)
![osu_2023-10-08_00-19-36](https://github.com/ppy/osu/assets/75809251/82b0d285-1756-4472-a471-9762d2695ac0)
![osu_2023-10-08_00-21-07](https://github.com/ppy/osu/assets/75809251/40deec2c-8c1c-445d-96a4-44a11562bba9)

### Version

2023.1008.0

### Logs

[updater.log](https://github.com/ppy/osu/files/12839777/updater.log)
[database.log](https://github.com/ppy/osu/files/12839778/database.log)
[input.log](https://github.com/ppy/osu/files/12839779/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12839780/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12839781/network.log)
[performance.log](https://github.com/ppy/osu/files/12839782/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12839783/runtime.log)

**Comment by bdach** [comment]
I missed this element in https://github.com/ppy/osu/pull/25023. If / when I can get sizing data about this element from @RockRoller01, I'll tweak the dimensions.

**Comment by RockRoller01** [comment]
Approachcircle data: https://gist.github.com/RockRoller01/8aa13d217a3e5b6175409a31dd97f635
