### ISSUE TITLE
Health bar visually fills at start of map when it shouldn't (osu!taiko)

### ISSUE THREAD

**Issue by peppy** [ppy/osu#25046]
### Discussed in https://github.com/ppy/osu/discussions/25043

<div type='discussions-op-text'>

<sup>Originally posted by **12beesinatrenchcoat** October  8, 2023</sup>
The health bar starts at 0 in osu!taiko, but at the start of the beatmap, it still animates to full (this seems to be visual; it immediately drops once a note is hit).

https://github.com/ppy/osu/assets/25379179/a119bb57-b97c-41ba-afcc-980bbd8885cc

(The health bar also animates when paused, but that's less important.)

https://github.com/ppy/osu/assets/25379179/fbad2588-e3f9-436e-8542-a9ddbb900aa9

</div>

**Comment by yesseruser** [comment]
The health bar animates when paused on all gamemodes.

**Comment by bdach** [comment]
this is known.

https://github.com/ppy/osu/blob/54722bf251078fbc97e919a09da1fd7fa30d1ce8/osu.Game/Screens/Play/HUD/HealthDisplay.cs#L86-L88

see "should run in gameplay time" part.
