### ISSUE TITLE
Visual bounding box doesn't match outline of scaled elements in skin editor

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [ppy/osu#25049]
### Type

Game behaviour

### Bug description

Scaling a skin element in the skin editor produces inaccuracies between the pink bounding box and the yellow outline on selected elements (I'm not sure what the technical terms for them are).

It happens on every element that I've tested so far, but is most noticeable when stretching somewhat wide elements vertically.

### Screenshots or videos

https://github.com/ppy/osu/assets/84215197/11a28861-3201-46a8-93a5-1af79fad77ed

### Version

2023.1008.0

### Logs

[network.log](https://github.com/ppy/osu/files/12840531/network.log)
[performance.log](https://github.com/ppy/osu/files/12840533/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12840534/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12840535/updater.log)
[database.log](https://github.com/ppy/osu/files/12840536/database.log)
[input.log](https://github.com/ppy/osu/files/12840537/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12840538/legacy-ipc.log)

**Comment by peppy** [comment]
It's intended to be a small amount larger than the element, but it definitely shouldn't be getting relatively larger when scaled.

**Comment by madebylydia** [comment]
Hello, I'd like to work on this issue and make a PR to resolve this problem.
Can I just get a directive about what file I must edit? I started having a look for myself, so I'll see if I can find it by my own.
I'll send a PR once fixed. 👍

**Comment by peppy** [comment]
You can use the draw visualiser (see framework key bindings) to find classes based on visuals. That should give you a pointer.

**Comment by kennytram** [comment]
Can you describe the intended behavior more specifically? Do you expect the area inside the bounding box to be entirely covered in pink, or do you want the pink area to scale slightly beyond the bounding box?

**Comment by bdach** [comment]
The pink box should be slightly larger than the element but the amount of inflation should be constant and not depend on the scale of the element.

**Comment by travis-g-reid** [comment]
As a newcomer, it is unclear how to replicate this issue.
