### ISSUE TITLE
Individual beatmap results are missing in recently ended playlist

### ISSUE THREAD

**Issue by DarkbitNetwork** [ppy/osu#25058]
### Type

Game behaviour

### Bug description

The results won't appear when you take a look inside the individual beatmap results of a playlist that has ended. Pretty sure this previously wasn't the case as far as I know. And yes, I tried downloading the beatmap and then viewing the result and it's still missing.

Might be an issue on my end due to recent network issues I have (however I think this issue shouldn't occur 100% of the time if this is the case and also that open playlist isn't missing any results) but just to be sure
### Screenshots or videos
There's one player on the leaderboard who have a score on every beatmaps in the playlist so it shouldn't be possible for a beatmap to not have anyone submitted a score on it

https://github.com/ppy/osu/assets/43719333/da200f93-bedc-449c-b25e-82be17c1b1c4

### Version

osu! 2023.1008.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12841318/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12841320/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12841321/updater.log)
[database.log](https://github.com/ppy/osu/files/12841322/database.log)
[input.log](https://github.com/ppy/osu/files/12841323/input.log)
[network.log](https://github.com/ppy/osu/files/12841329/network.log)

**Comment by Stoppedpuma** [comment]
Having the same issue on my end. osu!web also no longer shows playlist and multiplayer history which may or may not be related to this.

**Comment by peppy** [comment]
This is due to not all scores being migrated to the new storage schema. I didn't think people would care that much, but obviously I was wrong. I'll migrate the rest.

**Comment by peppy** [comment]
Migration has completed. I've confirmed on the above rooms that scores are displaying again.
