### ISSUE TITLE
Freezes when editing skins

### ISSUE THREAD

**Issue by Sukuratchi** [ppy/osu#25050]
### Type

Performance

### Bug description

Got a really long freeze when editing a skin and scrolling through the selectable skin components

Seems like this happens when sitting and watching auto play a beatmap in the skin editor, then scrolling between the components?

### Screenshots or videos

https://github.com/ppy/osu/assets/66184829/e5b5de70-38f1-4dad-b61e-97d334bfcf8b

Replicated with performance graph:

https://github.com/ppy/osu/assets/66184829/e79c47d6-79de-4e18-8ace-34aa4828195b

### Version

2023.1008.0

### Logs

[database.log](https://github.com/ppy/osu/files/12840676/database.log)
[input.log](https://github.com/ppy/osu/files/12840677/input.log)
[network.log](https://github.com/ppy/osu/files/12840678/network.log)
[performance.log](https://github.com/ppy/osu/files/12840679/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/12840681/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/12840682/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12840683/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12840684/updater.log)

**Comment by Sukuratchi** [comment]
I've recorded a replay thing of the last 10 minutes of what I was doing
First video (9:37)
https://youtu.be/jqpqTrdVPeI

Second video (5:08)
https://youtu.be/mh5RPeK4wuY

**Comment by peppy** [comment]
It looks to be occurring when the new health bar comes on screen in the components list. Weirdly, I can't reproduce this.

**Comment by Sukuratchi** [comment]
Seems to be fixed for me with that pr

**Comment by Sukuratchi** [comment]
A thing I noticed is that when scrolling up, fps drops for a bit until I guess it "loads" or "catches up". After which it gets fixed. No idea if that's something you'll fix but thought I should mention this

https://github.com/ppy/osu/assets/66184829/bba2ae29-73c9-4373-aebc-51d62ffc14ba
