### ISSUE TITLE
OsuCheckbox : the LabelText may be overlapped by the nub

### ISSUE THREAD

**Issue by UselessToucan** [ppy/osu#2505]
If the label is long, it may be overlapped. I think it should be handled somehow(replace text with "..." at some point, perform word wrapping and so on).
![label_overlap](https://user-images.githubusercontent.com/22450664/39821160-44cc26ee-53b0-11e8-9f79-c4183f9d877e.jpg)

**Comment by Aergwyn** [comment]
Whoever does this may have my upvote because more areas could benefit from this (e. g. #1701 ).

**Comment by peppy** [comment]
Should be wrapped.

**Comment by Joehuu** [comment]
Fixed in #4970.

![](https://puu.sh/DItSU/400d8aba6f.png)
