### ISSUE TITLE
Incorrect followcircle animation

### ISSUE THREAD

**Issue by Natelytle** [ppy/osu#25061]
### Type

Game behaviour

### Bug description

The animation starts late, and when the slider ball hits a slider tick, the follow circle seems to jump to full size instantly.

### Screenshots or videos

https://github.com/ppy/osu/assets/92956514/8570547d-0878-4515-8e69-bcc3a50cd118

### Version

2023.1008.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12842273/database.log)
[input.log](https://github.com/ppy/osu/files/12842274/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12842275/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12842276/network.log)
[performance.log](https://github.com/ppy/osu/files/12842277/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12842280/runtime.log)

**Comment by Natelytle** [comment]
https://github.com/ppy/osu/pull/14832#discussion_r713562240 whoops intentional

**Comment by Zyfarok** [comment]
@Natelytle are you sure this is still "intentional" ?
It seems that this PR (which followed the issue you linked above) has changed follow-circle behavior such that the delay on the lazer animation might not make sense anymore : https://github.com/ppy/osu/pull/18795

**Comment by peppy** [comment]
The only difference I can see in that video is that the tick animation plays more correctly on lazer.

If there's an issue here, I'd recommend opening a new issue better explaining what doesn't match and we'll work from there.
