### ISSUE TITLE
Touchscreen "Click/Tap Streaming" No Longer Working

### ISSUE THREAD

**Issue by Va1orance** [ppy/osu#25065]
### Type

Game behaviour

### Bug description

Touchscreen functions including: cursor, scrolling, etc. all are recorded. However, "click" inputs such as tapping on notes no longer work. Osu! Mania/other key rhythm games function fine. Just standard osu! does not recognize tap/click inputs.

Updated to latest version of osu!lazer via automatic updates on Testflight on IOS 16.3.1

Says there is a newer version (2023.1008.0 -> 2023.1008.1)

iPhone SE (2020), both fingers and stylus do not function for input. Both, however, work for movement.

### Screenshots or videos

https://github.com/ppy/osu/assets/69877475/70aa9e1b-7f0c-40b5-af7c-ea38ca2c924b

### Version

2023.1008.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12843017/database.log)
[input.log](https://github.com/ppy/osu/files/12843018/input.log)
[network.log](https://github.com/ppy/osu/files/12843019/network.log)
[performance.log](https://github.com/ppy/osu/files/12843020/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12843021/runtime.log)

**Comment by Va1orance** [comment]
Update:
Ported the same version osu! IPA onto device. The touchscreen features now function perfectly fine. May be a TestFlight issue?

**Comment by Va1orance** [comment]
I found the issue, "disable mouse button input" must be disabled. The touchscreen inputs count as mouse clicks.

**Comment by peppy** [comment]
100% sure this has come up before, but can't find the issue.

Probably worth tracking as high priority as it's pretty weird.

**Comment by frenzibyte** [comment]
I was looking at this the other, and I've been wondering between two options:
 1. Redefine the original "disable mouse buttons" setting to state that it also disables touch taps (only taps, pointing will still work).
 2. Add a separate setting for disabling touch taps, as something like "Disable touch taps during gameplay" with a tooltip mentioning that pointing is still enabled, for anyone who plays with a keyboard and a stylus pen.

The former would prevent from showing more settings to the user, while the latter provides more flexibility to the user's play style (e.g. allowing them to play with keyboard+mouse, keyboard+tablet, and touch-only without toggling settings every time, by disabling mouse buttons while keeping touch enabled...but that may be a weak point to support that option).

A third option will be to have the setting not affect touch at all, and ignore the idea of a keyboard+touch play style, if anyone can play with that at all.

cc @ppy/team-client

**Comment by peppy** [comment]
What would be your proposed display text for solution 1? That's the hardest part here.

**Comment by frenzibyte** [comment]
The only name I had was something clunky like "Disable mouse buttons / touch taps". If we can't figure out a good name for it, then that might as well be a hint to not group it into one setting.

**Comment by peppy** [comment]
"touch taps" makes no sense to a user. It would need to be something like "Disable gameplay actions triggered by mouse buttons or touch input"

**Comment by frenzibyte** [comment]
The term "action" feels slightly too technical to be shown to the user, but you know this better than I do...If we agree on option 1, then I'll go with that and we can discuss it further in the PR.

**Comment by Susko3** [comment]
Touch works for input even if mouse buttons are unbound.

Since the setting lives under the `Mouse` section, there's no sense in renaming it to accommodate touch as well. I think duplicating the setting to appear under `Touch` (with a different name) could work.

"Gameplay actions" does seem too technical and broad. I think calling it "clicks" makes more sense ("click the circles", "rhythm is just a click away").

Something like this (the popup saying mouse buttons is out of place for touch):

![image](https://github.com/ppy/osu/assets/16479013/2e9f8e40-d95f-4a61-a9ac-ba3b1b82615a)

**Comment by frenzibyte** [comment]
> Since the setting lives under the Mouse section, there's no sense in renaming it to accommodate touch as well. I think duplicating the setting to appear under Touch (with a different name) could work.

That sounds like a weird approach to me. There should either be two settings or one setting placed at a general place like "Gameplay".

> "Gameplay actions" does seem too technical and broad. I think calling it "clicks" makes more sense ("click the circles", "rhythm is just a click away").

Not sure, it's definitely going to be odd when thinking about catch and the side buttons it has. How about just "press"? Like, "Ignore presses from mouse / touch input during gameplay".

**Comment by peppy** [comment]
I think the two settings under input works quite well.

"Disable taps during gameplay"
"Disable clicks during gameplay"

are probably best terminology I've seen so far.

**Comment by frenzibyte** [comment]
@peppy should I consider this to be out of discussion given https://github.com/ppy/osu/issues/25065#issuecomment-1786360644 and work on it? otherwise, maybe the issue thread's priority should be downgraded to `priority:2`?

**Comment by peppy** [comment]
Implementing as proposed is fine, yes.
