### ISSUE TITLE
Old beatmaps have different MD5 hash from online database

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#25078]
Tracking issue so this can be added to the project. See discussion for more info.

### Discussed in https://github.com/ppy/osu/discussions/19551

<div type='discussions-op-text'>

<sup>Originally posted by **Loreos7** August  2, 2022</sup>
https://user-images.githubusercontent.com/86934170/182387273-f4a9a3cf-d1aa-4ae4-8649-1017190a81c5.mp4

https://user-images.githubusercontent.com/86934170/182388323-a3413ab9-19af-4a3f-a330-945359c213a4.mp4

Trying to update:

https://user-images.githubusercontent.com/86934170/182388361-5539aa1d-1c2b-4c39-a335-66dab3487355.mp4

[runtime.log](https://github.com/ppy/osu/files/9242688/runtime.log)
[network.log](https://github.com/ppy/osu/files/9242689/network.log)
[database.log](https://github.com/ppy/osu/files/9242690/database.log)
[performance.log](https://github.com/ppy/osu/files/9242691/performance.log)
[updater.log](https://github.com/ppy/osu/files/9242692/updater.log)

https://osu.ppy.sh/beatmapsets/215#osu/712
https://osu.ppy.sh/beatmapsets/212#osu/2029
https://osu.ppy.sh/beatmapsets/304#osu/1304
https://osu.ppy.sh/beatmapsets/167#osu/398
https://osu.ppy.sh/beatmapsets/157#osu/352</div>

**Comment by bdach** [comment]
Judging from https://github.com/ppy/osu/discussions/19551#discussioncomment-3902132 this is probably something only @peppy can fix?

**Comment by peppy** [comment]
I'll do a full pass of this, but note that most of the ones in that thread were already fixed.

**Comment by peppy** [comment]
I'm running a first pass across all ranked beatmaps to ensure that `.osu` files match database hashes. I believe as discussed in the thread, this should result in zero mismatches.

A second pass will update `.osz` files with the more correct `.osu` files, after the above is confirmed.

**Comment by peppy** [comment]
I've created a batch process to repair all known issues in `osz` files. It has run up to `beatmapset_id=316000` and will continue on all ranked/approved/loved beatmaps (should complete within 48 hours).

So far it has repaired around 60 beatmaps with various issues, including filename and checksum mismatches, but also beatmaps which were incorrectly cached on one or more mirrors.

I'm going to close this issue. Please feel free to post / reopen if something looks to have been missed.

**Comment by peppy** [comment]
A full run has completed. A total of ~120 beatmaps were fixed.
