### ISSUE TITLE
Toolbar toggle-able during gameplay

### ISSUE THREAD

**Issue by tomdenty1** [ppy/osu#2507]
Opening the toolbar using Ctrl+T during gameplay allows you to skip throughout the song, open options, the social browser, chat and osu!direct

https://youtu.be/2AFc67lD7RY

Edit: The Toolbar is pretty much toggle-able everywhere which could present problems in things like the editor.

**Comment by peppy** [comment]
This is actually intended. Could you explain how it could present problems in the editor?

**Comment by tomdenty1** [comment]
While in the editor, changing the song while previewing the beatmap causes the game to crash.

**Comment by odgaard** [comment]
I can't seem to re-produce the crash in the editor, could you show it in a video?

**Comment by tomdenty1** [comment]
Here
https://youtu.be/MdritfTw3Xw

**Comment by odgaard** [comment]
The buttons you used to cause the crash have been disabled in the editor in the most recent builds. I have a PR up to disable all MusicController functionality (seek, pause/resume prev/next) during gameplay, in the editor and in a replay. All of the necessary functionality to control the music are already present in those screens, so the MusicController in the Toolbar is redundant.
