### ISSUE TITLE
Player rank not displayed in menu

### ISSUE THREAD

**Issue by Dents6679** [ppy/osu#2510]
![image](https://user-images.githubusercontent.com/36710174/39835211-5efe4314-53c7-11e8-95bd-892b7d0d043a.png)

There is no 'easy' way to view your rank in the menu, it requires going into the social browser.
Rank progress is also not displayed anywhere like rank.

**Comment by peppy** [comment]
Obviously planned but not implemented yet.

**Comment by Leostayner** [comment]
I don't know if this issue is still wanted, I can work on it?

**Comment by bdach** [comment]
Obviously wanted, but needs a design first.

**Comment by peppy** [comment]
@arflyte general direction here would be useful. is rank etc. going to be inside the user card, or below/above it?

**Comment by SleepySwords** [comment]
Random idea. In addition to adding the ranks to the user card, we could also add the rank as a tab in the top bar. 
Like: 

![Screen Shot 2021-05-29 at 10 26 54 pm](https://user-images.githubusercontent.com/33922797/120070266-fa4ace80-c0cc-11eb-8dbc-2c495d99ca2b.png)
or
![Screen Shot 2021-05-29 at 10 27 08 pm](https://user-images.githubusercontent.com/33922797/120070276-02a30980-c0cd-11eb-9fe0-6387e55ad166.png)

**Comment by peppy** [comment]
Thanks but we aren't accepting design submissions right now. We already have a path forward for the look of this.
