### ISSUE TITLE
Deleted beatmap still accessible in MusicController

### ISSUE THREAD

**Issue by tomdenty1** [ppy/osu#2511]
Here, don't exactly know how to explain this...

https://youtu.be/9V-J4-9mPCU

**Comment by peppy** [comment]
Explanation: After deleting a beatmap, it is still accessible using the "next" button in the music controller.

**Comment by DudeMartin** [comment]
I'm looking into this right now, but I'm having a hard time reliably replicating this. I've been able to witness the bug a few times, but it does not always happen. @tomdenty1 Could you provide steps to replicate this issue?
