### ISSUE TITLE
The score is shown twice on the result screen

### ISSUE THREAD

**Issue by akiya-nagatsuka** [ppy/osu#25117]
### Type

Cosmetic

### Bug description

When I click the score in a local leaderboard It's shown twice on the result screen.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/38129679/12ccbaae-85ef-45b3-8be1-065ebc597e66)

### Version

2023.1008.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/12896466/runtime.log)
[performance-audio.log](https://github.com/ppy/osu/files/12896467/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12896468/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/12896469/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12896470/performance-update.log)
[database.log](https://github.com/ppy/osu/files/12896472/database.log)
[input.log](https://github.com/ppy/osu/files/12896474/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12896475/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12896476/network.log)
[performance.log](https://github.com/ppy/osu/files/12896477/performance.log)
[updater.log](https://github.com/ppy/osu/files/12896478/updater.log)

**Comment by akiya-nagatsuka** [comment]
Maybe the first one is a top50 global ranking play and the second play is the local play. So osu just doesn't understand this play is already added in a result screen scores list. Because I don't observe this issue when I click on the same play but in global ranking.

**Comment by yesseruser** [comment]
Happens to me, as well.
Here's a screenshot, I don't know if it helps:
![image](https://github.com/ppy/osu/assets/67008763/b30bfeb2-b141-4dfc-b04e-132ea6f41b77)

**Comment by yesseruser** [comment]
Are scores identified somehow (e.g. with a hash)?
