### ISSUE TITLE
Tablet with pressure detection glitching out

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#25128]
### Type

Game behaviour

### Bug description

When playing with a tablet that supports pressure detection (One by Wacom - CTL-472) that and pressing firmly the cursor just glitches out. (See video)
This tablet works normally in stable using system drivers and it would be great if the same worked on Lazer.

(Original discussion: #24778)

### Screenshots or videos

https://1drv.ms/v/s!Ag98u2Nn2vf2mv1yJrm0JdsJ8GOPmA?e=6Pj5EN
(Github didn't let me upload the video because it's too large so I uploaded it to OneDrive)

### Version

2023.1008.1-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12568638/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12568639/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12568640/updater.log)
[database.log](https://github.com/ppy/osu/files/12568641/database.log)
[input.log](https://github.com/ppy/osu/files/12568642/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12568643/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12568644/network.log)

**Comment by peppy** [comment]
Please report to OpenTabletDriver
