### ISSUE TITLE
Installation doesn't have French start with a capital letter

### ISSUE THREAD

**Issue by baikil** [ppy/osu#25125]
### Type

Cosmetic

### Bug description

Installation doesn't have French start with a capital letter (should be "Français" instead of "français")

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/78218286/3b62b09d-3729-4d43-a98f-5b933dcf8bfe)

### Version

2023.1008.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12907087/database.log)
[input.log](https://github.com/ppy/osu/files/12907088/input.log)
[network.log](https://github.com/ppy/osu/files/12907089/network.log)
[performance.log](https://github.com/ppy/osu/files/12907090/performance.log)
[updater.log](https://github.com/ppy/osu/files/12907093/updater.log)
[runtime.log](https://github.com/ppy/osu/files/12907095/runtime.log)

**Comment by Joehuu** [comment]
That's intentional, see https://github.com/ppy/osu-web/issues/6840 for reasoning.
