### ISSUE TITLE
Edge hit note becomes a miss when watching back replay

### ISSUE THREAD

**Issue by Natelytle** [ppy/osu#25162]
### Type

Game behaviour

### Bug description

I was watching back Akolibed's play on Reign of Fear (https://osu.ppy.sh/scores/osu/4518727921) when I discovered that he misses at 1270 combo in lazer, but not in stable. I dug a little deeper using 2 replay parsing apps, and osu! rewind displays the lazer behaviour (a miss), and circleguard displays the stable behaviour (a hit).

### Screenshots or videos

osu! rewind:
![image](https://github.com/ppy/osu/assets/92956514/bef1c703-76b3-48fe-9ca8-ffd219d1f265)

circleguard:
![image](https://github.com/ppy/osu/assets/92956514/e45f3e96-96ab-4b77-808e-49be4df7c584)

Lazer:
https://github.com/ppy/osu/assets/92956514/8e83a596-f646-458f-8a94-dea115ff9eb8

Stable:
https://github.com/ppy/osu/assets/92956514/b28ac5aa-868a-4536-873a-fb22ffc6f80e

### Version

2023.1008.1-lazer

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/12974109/legacy-ipc.log)
[database.log](https://github.com/ppy/osu/files/12974110/database.log)
[input.log](https://github.com/ppy/osu/files/12974111/input.log)
[performance.log](https://github.com/ppy/osu/files/12974112/performance.log)
[network.log](https://github.com/ppy/osu/files/12974113/network.log)
[runtime.log](https://github.com/ppy/osu/files/12974114/runtime.log)

**Comment by tybug** [comment]
My immediate guess would be floating point differences in the hitradius calculation.

[circleguard](https://github.com/circleguard/circlecore/blob/659f099c5653a15a90a749379cd0bca63376ab61/circleguard/utils.py#L220)

```python
def hitradius(CS):
    # attempting to match stable hitradius
    return np.float32(64 * ((1.0 - np.float32(0.7) * (float(np.float32(CS)) - 5) / 5)) / 2) * np.float32(1.00041)
```


[rewind](https://github.com/abstrakt8/rewind/blob/a815a67f75c28a995b5251f34071c044abaa8faa/libs/osu/math/src/difficulty.ts#L7)

```javascript
export function circleSizeToScale(CS: number) {
  return float32((1.0 - (0.7 * (CS - 5)) / 5) / 2);
}
```

[lazer](https://github.com/ppy/osu/blob/e927267c4d66e29ea0eaa894eda1b5da4adb98b1/osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs#L158)

```csharp
            Scale = (1.0f - 0.7f * (difficulty.CircleSize - 5) / 5) / 2;
```

[stable](https://github.com/peppy/osu-stable-reference/blob/1531237b63392e82c003c712faa028406073aa8f/osu!/GameplayElements/Beatmaps/BeatmapDifficultyCalculatorOsu.cs#L52) (I think?)

```csharp
            float circleRadius = (PLAYFIELD_WIDTH / 16.0f) * (1.0f - 0.7f * (float)HitObjectManager.AdjustDifficulty(Beatmap.DifficultyCircleSize));
```

I'll be honest with you...I have no idea anymore where some of the casts or constants in the circleguard code came from (what is `np.float32(1.00041)` doing there??). But maybe it will be useful for anyone looking into this.

**Comment by peppy** [comment]
Path forward would be to reimplement to match stable calculation-wise, I believe. Should try and simplify things down as much as possible.

**Comment by peppy** [comment]
I'll look into this one.
