### ISSUE TITLE
No hitsound when hit objects' volume is on 5% on lazer

### ISSUE THREAD

**Issue by SedjamTan** [ppy/osu#25165]
### Type

Game behaviour

### Bug description

I noticed while playing [this map](https://osu.ppy.sh/beatmapsets/1859679#osu/3823636) that certain hit objects don't have a hitsound on lazer compared to stable. Upon checking the beatmap in the editor, those hitobjects have a volume of 5%.

Some of the hit objects with volume of 5%:
0:39:260
0:39:450
0:49:969
0:44:007
0:46:476

### Screenshots or videos

Stable

https://github.com/ppy/osu/assets/62494738/de0c5a6d-f7cc-4c74-9785-de4abfbf3591

Lazer

https://github.com/ppy/osu/assets/62494738/bf5c5161-0b49-438b-a2a5-8218e2da6724

### Version

2023.1008.1

### Logs

[performance.log](https://github.com/ppy/osu/files/13004264/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13004269/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13004275/updater.log)
[database.log](https://github.com/ppy/osu/files/13004278/database.log)
[network.log](https://github.com/ppy/osu/files/13004282/network.log)

**Comment by peppy** [comment]
Stable enforces a 5% minimum. It's probably not yet implemented.

**Comment by bdach** [comment]
> Stable enforces a 5% minimum. It's probably not yet implemented.

Are you referring to this thing?

https://github.com/peppy/osu-stable-reference/blob/3ea48705eb67172c430371dcfc8a16a002ed0d3d/osu!/Audio/AudioEngine.cs#L1070
https://github.com/peppy/osu-stable-reference/blob/3ea48705eb67172c430371dcfc8a16a002ed0d3d/osu!/Audio/AudioEngine.cs#L1404-L1405

If yes, then that's 8%, but that still doesn't explain the massive volume difference. Whatever this thing is probably would though.

![image](https://github.com/ppy/osu/assets/20418176/8d037f3e-90e5-44bc-b78a-f40d44e9a3bf)

We already apply leniency here:

https://github.com/ppy/osu/blob/f36a671eb41dce6dd08169891e8992962930aa9f/osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs#L115

Not yet sure why it isn't enough in this case.
