### ISSUE TITLE
Osu! lazer slider bug

### ISSUE THREAD

**Issue by PixelLV** [ppy/osu#25161]
### Type

Game behaviour

### Bug description

When multiple slider starts are stacked on top of each other and you double tap the first slider, the second slider "disappears" and you're unable to click on it and if you even enable and disable the classic mod it doesn't fix the issue. I even double checked in osu stable and this issue didn't occur there. 

### Screenshots or videos

https://github.com/ppy/osu/assets/89537859/3412c2e5-c559-49c9-b385-38fd9c524b8a

### Version

2023.1008.1

### Logs

[session.log](https://github.com/ppy/osu/files/12955135/session.log)
[update_success.log](https://github.com/ppy/osu/files/12955139/update_success.log)
[osu!auth.log](https://github.com/ppy/osu/files/12955141/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/12955143/runtime.log)

**Comment by peppy** [comment]
Wrong log files. No link to beatmap. Unclear video.

**Comment by RatinFX** [comment]
Their issue seems to be the different handling of notelock when you use multiple keys at once / double tap on overlapping slider heads - however, this behaves like in Stable if you use the Classic mod.

Beatmap: https://osu.ppy.sh/beatmapsets/702892#osu/1487213
Extreme difficulty from 00:25:916 - 

### Stable

> https://github.com/ppy/osu/assets/38523955/b207ec92-b775-4f79-9470-e5bc1c4e95f8

### Lazer + Classic mod

> https://github.com/ppy/osu/assets/38523955/9e5ce60d-6333-42fe-b4c1-d4bc8ecb8a60

### Lazer default

> https://github.com/ppy/osu/assets/38523955/915fc20b-5662-4d93-ad02-f679201fdc66

**Comment by peppy** [comment]
So this is "as intended"? Or needs further discussion?

**Comment by bdach** [comment]
I think this is basically https://github.com/ppy/osu/issues/24626? So yes that would be "intended" given the discussion that took place in that thread.

**Comment by RatinFX** [comment]
Sounds like it is intended then
