### ISSUE TITLE
小米平板5Pro，freedom dive有音乐问题

### ISSUE THREAD

**Issue by laoqijun1** [ppy/osu#25196]
### Type

Game behaviour

### Bug description

设备:小米平板5pro
soc:高通骁龙870
在用自动游玩的模组播放freedom dive的谱面时，音乐会偶有卡顿，画面也卡了一下。

Device: Mi Tablet 5pro soc: Qualcomm Snapdragon 870 When playing freedom dive's side of the music on the autoplay module, the music occasionally stutters and the picture gets stuck.

### Version

2023.1008.1

### Logs

NO!

**Comment by toadsworth-jr** [comment]
- Please give us logs. The devs can't fix your issue if you say NO!
- Send us a video of what you're experiencing. I'm having trouble visualizing the problem in my head.

**Comment by MiddleRed** [comment]
It is very likely because of the lack of optimizing for mobile platform rather than the game bug, given that playing lazer on a strong device like iPad Pro with M2 chip will still occasionally stall and lagging, especially when playing chart with many LN in mania.

**Comment by laoqijun1** [comment]
> * Please give us logs. The devs can't fix your issue if you say NO!
> * Send us a video of what you're experiencing. I'm having trouble visualizing the problem in my head.

试了一下，可能是我那时候设备电量低导致系统限制了性能，现在除了掉帧就没什么问题了。

I tried it. It was probably the low battery of my device at the time that limited the system's performance, but now it's fine except for dropping frames.

[https://alist.xn--vzyr4p.top/d/teambition/Screenrecorder-2023-10-22-09-34-41-627.mp4?sign=l5SvOjYfFKkv3u5_rHuRkHa2MsEgRxW_M5eFfBq36Bw=:0](url)
