### ISSUE TITLE
Keybinds for numpad keys are dependent on NumLock state

### ISSUE THREAD

**Issue by longnguyen2004** [ppy/osu#25195]
### Type

Game behaviour

### Bug description

Noticed this while trying to set up keybinds for 10k and accidentally turned off NumLock. Pressing NumPad4 will result in Right being registered. Although this behavior matches stable, it can affect people who use an external numpad and don't want to turn on NumLock, because it affects the internal keyboard. 

### Version

2023.1008.1

### Logs

Probably not needed

**Comment by bdach** [comment]
This works this way to begin with because someone reported the inverse of this issue - https://github.com/ppy/osu-framework/issues/2728. And I'd argue that respecting num lock state is the _more_ correct behaviour here.
