### ISSUE TITLE
osu!stable std - Unlimited FPS - Audio Latency Issue

### ISSUE THREAD

**Issue by Arizoka** [ppy/osu#25224]
### Type

Performance

### Bug description

Hello there,

I have been struggling with audio latency in osu!stable std for a couple of months now. The experience during gameplay is as follows: When I click on an object on time, whether it is a high sr map or a low sr map I hear the hit sound coming with delay (most frequently after my actual keypress). osu! is the only game where I'm experiencing this issue.

Please find below some specs and settings:

**PC Specs:**

CPU : Intel I5 12th gen 6 cores 4.5Ghz
GPU : NVIDIA MSI RTX 3060 12GB
RAM : Corsair 16GB 3200 Mhz
SSD : 1TB Samsung 980Pro PCIE Gen 4

**External Soundcard:**

Model: Focusrite Solo Gen 2
Driver version: 4.116.9
Sample Rate : 48000
Buffer Size : 32
Round-Trip Latency: 5.5ms (262 Samples)
Windows Exclusive mode: Disabled
Nvidia GPU Audio: Disabled

**osu! Settings:**

All visual FX: Disabled
Ratio: Full Screen
HeightFullscreen = 1080
WidthFullscreen = 1920
MyPCSucks = 0
Skin Samples = 1
Audio Compatibility mode = 0
Frame sync = Unlimited

**osu! Output:**

Gameplay latency/fps counter: 0.2 to 0.3ms

Is there anything i can do to fix this?

So far I have tried : 

- Enabling and Disabling Windows Exlusive mode
- Activating and deactivating audio compatibility mode (which results in screen tearing)
- Updating all audio and GPU drivers
- Updating Windows 10
- Updating all .Net and C++ Visual drivers

Thank you in advance for your help

### Version

b20231023.1cuttingedge

### Logs

[performance.log](https://github.com/ppy/osu/files/13165368/performance.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu-stable-issues/issues is the correct place for this
