### ISSUE TITLE
Implementing Flow PP - First pass

### ISSUE THREAD

**Issue by suddenly-eva** [ppy/osu#2523]
As described in this reddit post:

https://www.reddit.com/r/osugame/comments/8ildvl/first_pass_introducing_flow_pp/

Code is still messy/undocumented, I wanted to get the post out there first.

Any ideas for things that might be broken? And can anyone help with getting better datasets?

**Comment by peppy** [comment]
Please either post this as an issue or code, rather than linking off-site.
