### ISSUE TITLE
Chinese Characters Render Issue

### ISSUE THREAD

**Issue by LmanTW** [ppy/osu#25231]
### Type

Other

### Bug description

It seems a bit random, some times it won't appear.

### Screenshots or videos

<img width="522" alt="截圖 2023-10-26 下午6 22 20" src="https://github.com/ppy/osu/assets/82919705/846d1a07-0e96-4bf8-9296-0baf8a46cbe3">
<img width="381" alt="截圖 2023-10-26 下午6 21 23" src="https://github.com/ppy/osu/assets/82919705/aed90199-eb27-48b5-8b97-fbe72d74c6fd">
<img width="100" alt="截圖 2023-10-26 下午6 21 10" src="https://github.com/ppy/osu/assets/82919705/627a6f05-6463-43b6-a117-2c195f4af452">

### Version

2023.1026.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/13176105/runtime.log)
[network.log](https://github.com/ppy/osu/files/13176106/network.log)
[performance.log](https://github.com/ppy/osu/files/13176107/performance.log)
[database.log](https://github.com/ppy/osu/files/13176109/database.log)
[input.log](https://github.com/ppy/osu/files/13176110/input.log)

**Comment by bdach** [comment]
Can you elaborate as to what "won't appear"? I'm not familiar with the language so I'm not sure what I'm looking at.

**Comment by peppy** [comment]
I think the issue here may be that some characters are drawn smaller than others. Likely https://github.com/ppy/osu/issues/13843.

**Comment by RBQcat** [comment]
The OP is refers to text rendering being truncated. In the OP photo, ![image](https://github.com/ppy/osu/assets/74862110/f7eaabbf-9e6a-4899-85ce-cc3f1f5c4d7f) are rendered incorrectly. If the text is rendered correctly it should look like this ![image](https://github.com/ppy/osu/assets/74862110/f35883b9-909d-4747-b345-56b2cb1646b5). 
Among them, the most serious one is Rank Achieved's D. The complete error is displayed as ![image](https://github.com/ppy/osu/assets/74862110/8b3cf139-6e3f-43df-aa1d-aa725957879c) ,
 and the correct one should be displayed as D.

**Comment by bdach** [comment]
That looks like either driver error or an atlassing failure. Not sure how we're going to meaningfully debug if it's the second though. The atlas view exists but it will be too tiny to tell if the CJK characters are drawn to the atlas correctly.

Maybe a renderdoc capture would help here. Not sure if that's something we can request the user to take though...

**Comment by LmanTW** [comment]
> Can you elaborate as to what "won't appear"? I'm not familiar with the language so I'm not sure what I'm looking at.

Sorry for I didn't keep up with this issue, I'm expecting some kind of notifications, but I didn't get any, sorry about that.

**Comment by peppy** [comment]
Closing in favour of #25393, as this seems to be a larger scoped issue which is better covered by that issue.
