### ISSUE TITLE
Distance snap on catch editor not work properly

### ISSUE THREAD

**Issue by Sololiquy** [ppy/osu#25238]
### Type

Game behaviour

### Bug description

Distance snap always stuck on corner bottom left, won't move.
and not disappear even it turn off

### Screenshots or videos

![Screenshot 2023-10-26 201052](https://github.com/ppy/osu/assets/77843814/c1e3c0b4-d542-4058-9cdf-1adb757487bf)

### Version

2023.1026.0-lazer

### Logs

.

**Comment by CornDoggyyy** [comment]
Also, moving the distance spacing slider ends up in an instant error. Do this too much and lazer will crash. 

![image](https://github.com/ppy/osu/assets/113111923/fcbb4b40-81b7-472e-85d3-cacbb3f2d139)
