### ISSUE TITLE
Followpoints exceeding max dimensions look strange

### ISSUE THREAD

**Issue by osu-funkyfeelin** [ppy/osu#25273]
### Type

Cosmetic

### Bug description

I have a skin using 137x5 (274x10@2x) followpoints which are supposed to look like lines.
As of 2023.1026, they look strange. One line seems to be repeated beside itself a few times, giving me "claw marks".
If I unpack the skin and scale 137x5 to 128x5 (https://github.com/ppy/osu/issues/24940#issuecomment-1760983359), the followpoints look how I think they should again.

### Screenshots or videos

![followpoint-weird-fs8](https://github.com/ppy/osu/assets/71528455/b3506dce-40e3-4861-b62d-bab6ed3cf606)

### Version

2023.1026.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13194396/database.log)
[performance.log](https://github.com/ppy/osu/files/13194397/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13194398/runtime.log)

**Comment by frenzibyte** [comment]
Please attach your skin for further investigation.

**Comment by peppy** [comment]
Sounds like texture repeat mode set wrong on one axis. Should be easy to repro without the skin.

**Comment by peppy** [comment]
Safe to say texture dimension limiting is completely broken for cases where the aspect ratio is different. It's pulling in stuff from the atlas, completely corrupting display:

![CleanShot 2023-10-31 at 08 01 43](https://github.com/ppy/osu/assets/191335/8d89e1a4-c23e-4958-8763-319db755ff0c)

Test using the following `followpoint`:

![followpoint@2x](https://github.com/ppy/osu/assets/191335/e2ad81db-a486-428c-b215-c644805926d9)
