### ISSUE TITLE
No "Add Friend" button on social browser

### ISSUE THREAD

**Issue by Dents6679** [ppy/osu#2528]
![image](https://user-images.githubusercontent.com/36710174/39931884-984b1546-5536-11e8-8dc1-4ccc728ea90a.png)

Probably planned for implementation but just gonna point it out,

**Comment by tomdenty1** [comment]
Things like follower count aren't here either

**Comment by peppy** [comment]
Correct

**Comment by tomdenty1** [comment]
I have no coding experience and am here to just help report bugs, I won't bother with reporting missing features since it just seems to inconvenience you and the team.

**Comment by HoutarouOreki** [comment]
I'm currently working on implementing buttons like Messaging, Add friend. Already added Follower Count text. I most probably will not know how to make calls to server to actually add someone as a friend etc.

**Comment by peppy** [comment]
#30386
