### ISSUE TITLE
Alt+tab moves lazer window to end of alt+tab queue

### ISSUE THREAD

**Issue by distilledx** [ppy/osu#25292]
### Type

Game behaviour

### Bug description

Using alt+tab to switch windows moves osu!lazer to the end of alt+tab queue. I'm on Ubuntu 22.04 using Gnome as my desktop environment and the default mutter as window manager, running a wayland session

### Screenshots or videos

[Screencast from 10-29-2023 02:58:26 PM.webm](https://github.com/ppy/osu/assets/108227905/8b7d4a7c-6a28-49d5-97f8-b00a2cf5f696)

### Version

osu! 2023.1026.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/13197697/runtime.log)
[performance.log](https://github.com/ppy/osu/files/13197698/performance.log)
[network.log](https://github.com/ppy/osu/files/13197699/network.log)
[input.log](https://github.com/ppy/osu/files/13197700/input.log)
[database.log](https://github.com/ppy/osu/files/13197701/database.log)

**Comment by bdach** [comment]
I don't know why this is but I'm pretty sure it has nothing to do with the game. It's likely some random linux breakage.

Closing until there's actual evidence we're on the hook for fixing this.
