### ISSUE TITLE
osu! crashes when sliding greyed out sliders in settings

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [ppy/osu#25319]
### Type

Crash to desktop

### Bug description

osu! crashes when sliding greyed out sliders in settings.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/88291316/6e2ea3fa-368a-4f13-a774-a40dcc6113f2)

### Version

newest 31 october 2023

### Logs

[database.log](https://github.com/ppy/osu/files/13214136/database.log)
[input.log](https://github.com/ppy/osu/files/13214137/input.log)
[network.log](https://github.com/ppy/osu/files/13214138/network.log)
[performance.log](https://github.com/ppy/osu/files/13214139/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13214140/runtime.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25228
