### ISSUE TITLE
when watching auto (possibly replays) and fast forward, it breaks in a very *fun* way

### ISSUE THREAD

**Issue by thatgurkangurk** [ppy/osu#25312]
### Type

Game behaviour

### Bug description

i was trying to watch an auto replay and just out of curiosity, i dragged the progress bar and the playfield exploded with all hit objects appearing very fast, even though the audio had ended

### Screenshots or videos

https://github.com/ppy/osu/assets/82083756/15f390d4-321a-4cb6-9c6a-17a1fb61118c

### Version

2023-1026.0

### Logs

[database.log](https://github.com/ppy/osu/files/13209636/database.log)
[input.log](https://github.com/ppy/osu/files/13209637/input.log)
[network.log](https://github.com/ppy/osu/files/13209638/network.log)
[performance.log](https://github.com/ppy/osu/files/13209639/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13209640/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13209641/updater.log)

**Comment by DarkbitNetwork** [comment]
Works as intended?

**Comment by peppy** [comment]
This is how the game currently works, yes.
