### ISSUE TITLE
Beatmap details page "Rating Spread" have some weird rendering

### ISSUE THREAD

**Issue by zvyap** [ppy/osu#25324]
### Type

Other

### Bug description

Sometime the `Rating Spread` graph will cause some rendering error

This happened on most beatmap that contains "low rating spread area",
lots of the beatmap affect by this issue

btw what is `Rating Spread` for, is it really a need?

### Screenshots or videos

https://github.com/ppy/osu/assets/52874570/6f50215f-3e0d-4a24-b030-45162e4632e0

### Version

2023.1026.0

### Logs

[performance.log](https://github.com/ppy/osu/files/13216273/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13216275/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13216276/updater.log)
[database.log](https://github.com/ppy/osu/files/13216277/database.log)
[network.log](https://github.com/ppy/osu/files/13216278/network.log)

**Comment by peppy** [comment]
> btw what is Rating Spread for, is it really a need?

"Rating spread" shows what people rated a beatmap from 1-10.

I dunno how useful it is to take up this much space.

**Comment by EVAST9919** [comment]
>The graphic issue can probably be fixed with either a minimum height or adjusting EdgeSmoothness, but as always, I do wonder if we should be fixing this at a Box level, since it affects all boxes anywhere.

This component using drawnodes since https://github.com/ppy/osu/pull/21304 but without inflation used, should be easy to fix.
