### ISSUE TITLE
Playing a very long spinner map makes osu very lag

### ISSUE THREAD

**Issue by wdnmd23333fdhsuidus** [ppy/osu#25326]
### Type

Game behaviour

### Bug description

editing long spinner map is also very laggy

### Screenshots or videos

https://github.com/ppy/osu/assets/81455657/f8ba6c4d-4f8c-407a-a1ca-c531e09b2e3a

### Version

2023.1026.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/13218565/network.log)
[performance.log](https://github.com/ppy/osu/files/13218569/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13218571/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13218572/updater.log)
[database.log](https://github.com/ppy/osu/files/13218573/database.log)

**Comment by bdach** [comment]
Mostly addressed by #25333
