### ISSUE TITLE
Error caused by starting a new map from scratch with different gamemode

### ISSUE THREAD

**Issue by Vadeblade** [ppy/osu#25337]
### Type

Game behaviour

### Bug description

1)Create a beatmap through the main menu.
2) Selected gamemode besides standard. 
3) Start from scratch, confirm deletion. 
Error

Error isn't triggered when you don't start from scratch

### Screenshots or videos

https://github.com/ppy/osu/assets/20312791/df455865-882f-4472-b1a9-fe72d0ca176a

### Version

2023.1026.0-Lazer

### Logs

[input.log](https://github.com/ppy/osu/files/13235108/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13235109/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13235110/network.log)
[performance.log](https://github.com/ppy/osu/files/13235111/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13235112/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13235113/updater.log)
[database.log](https://github.com/ppy/osu/files/13235114/database.log)

**Comment by bdach** [comment]
This feels like a UX failure as well as a code failure. It should not be possible to enter this flow in such a way in the first place (i.e. trying to create a new difficulty on an unsaved beatmap set).

Dunno what should happen here. Either it shouldn't be possible to create a new difficulty until the first save, or I don't know what else...?

**Comment by Vadeblade** [comment]
To be honest, If it was be id create a beatmap and then "save" it, and it should continue working normally if going by what you say. If the user decides to Close the map it prompts a save menu like normal and if they decline it, the map gets deleted.

Thats if A) you get what im trying to explain and B) its something that can be done.

**Comment by bdach** [comment]
I'm not sure I understand, but the editor currently works on a difficulty basis. You can't switch to another difficulty without saving (or discarding unsaved changes), and I'm not sure we'd be willing to change that.

**Comment by frenzibyte** [comment]
cc @peppy for feedback on an ideal UX to solve this issue.

**Comment by peppy** [comment]
Forcing a save in this scenario with the standard "save required" popup sounds like the easiest solution for now. Is that feasible?
