### ISSUE TITLE
Editor does not update "break" sections

### ISSUE THREAD

**Issue by alanyongy** [ppy/osu#25332]
### Type

Game behaviour

### Bug description

In the editor, the red bar indicating break sections (extended periods without hit objects) on the bottom timeline does not update to reflect new hitobjects being placed in the map. 

It does correctly reflect break sections based on hitobjects placed in the stable editor, but does not update based on changes made to the map from within the lazer editor.

### Screenshots or videos

New hitobjects placed in a break section in the lazer editor:
(The objects placed on either sides of this break section were placed in the stable editor)
https://github.com/ppy/osu/assets/27821892/7dbd76c2-225a-49dd-9812-c199b919e93c

### Version

2023.1026.0-lazer

### Logs

[performance-update.log](https://github.com/ppy/osu/files/13225145/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/13225146/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13225147/updater.log)
[database.log](https://github.com/ppy/osu/files/13225148/database.log)
[input.log](https://github.com/ppy/osu/files/13225149/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13225150/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13225151/network.log)
[performance.log](https://github.com/ppy/osu/files/13225152/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/13225153/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/13225154/performance-draw.log)

**Comment by bdach** [comment]
#14330
