### ISSUE TITLE
Displaying beatmaps within a star rating range

### ISSUE THREAD

**Issue by DudeMartin** [ppy/osu#2536]
The settings for displaying beatmaps from a certain star rating range do not work.

![Photo](https://user-images.githubusercontent.com/1411294/39972036-cd7d47bc-56d4-11e8-981e-076c6b9d303d.png)

Notice how the entire beatmap set is displayed on the carousel, regardless of the settings.

I am interested in implementing this feature myself.

**Comment by peppy** [comment]
The setting does not looked to be hooked up at all. Go ahead – let us know if you need any help!

**Comment by SevenChords** [comment]
newest version this is still not hooked up, any guess on which update this setting will work?

**Comment by Game4all** [comment]
The Pull request addressing this issue hasn't been merged yet. Please be patient.
