### ISSUE TITLE
Sprite display issues on some Metal hardware

### ISSUE THREAD

**Issue by LmanTW** [ppy/osu#25393]
### Type

Other

### Bug description

I also noticed that when this happens, my [text rendering](https://github.com/ppy/osu/issues/25231) is more likely to have problems.

### Screenshots or videos

<img width="1280" alt="截圖 2023-11-08 下午8 23 55" src="https://github.com/ppy/osu/assets/82919705/05afd7a8-8c3d-4d1b-a17d-3b0e3e2f4060">
<img width="340" alt="截圖 2023-11-08 下午8 26 46" src="https://github.com/ppy/osu/assets/82919705/3dba7191-7d88-4821-93aa-ed7193979f1e">
<img width="96" alt="截圖 2023-11-08 下午8 31 02" src="https://github.com/ppy/osu/assets/82919705/f7269076-16f0-4170-9210-8258ed67cfde">

### Version

2023.1026.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/13296603/network.log)
[runtime.log](https://github.com/ppy/osu/files/13296604/runtime.log)
[performance.log](https://github.com/ppy/osu/files/13296606/performance.log)
[input.log](https://github.com/ppy/osu/files/13296607/input.log)
[database.log](https://github.com/ppy/osu/files/13296608/database.log)

**Comment by peppy** [comment]
Relevant hardware info:

```
2023-11-08 12:23:23 [verbose]: 🖼️ Initialising "Veldrid" renderer with "Metal" surface
2023-11-08 12:23:23 [verbose]: Updated display mode to desktop resolution: 1280x800@60, SDL_PIXELFORMAT_ARGB8888
2023-11-08 12:23:23 [verbose]: Metal Initialized
2023-11-08 12:23:23 [verbose]: Metal Feature Set: macOS GPU family 1 (v4)
2023-11-08 12:23:23 [verbose]: UseStructuredBuffers: True
```

@LmanTW what model mac are you running here?

**Comment by LmanTW** [comment]
I'm using Retina, Mid 2012, And seems like Apple don't let me upgrade anymore, so I don't really have other options lol.
