### ISSUE TITLE
Black screen on launch

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu#254]
I try to build osu!(branch:master) on Raspberry Pi use
`xbuild osu\!.sln`
It build success,but when I run it with
 `mono osu\!.exe`
It just show me a black screen.
What should I do?I really want to play osu! on Pi,Thanks!

Environment:Raspberry Pi 2 with monodevelop

**Comment by DevSyphon** [comment]
On Windows the issue was that the files were Locked, so perhaps there is a similar issue in the Linux build, too. Try searching for an equivalent.
