### ISSUE TITLE
Pressing multiple commands may cause the game to crash.

### ISSUE THREAD

**Issue by kli75962** [ppy/osu#25410]
### Type

Crash to desktop

### Bug description

Pressing multiple commands (including tablet clicks) at a same time on the song selection screen may cause the game to crash.

### Version

osu! 2023.1026.0-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/13326013/updater.log)
[runtime.log](https://github.com/ppy/osu/files/13326014/runtime.log)
[database.log](https://github.com/ppy/osu/files/13326015/database.log)
[input.log](https://github.com/ppy/osu/files/13326016/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13326017/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13326018/network.log)
[performance.log](https://github.com/ppy/osu/files/13326019/performance.log)

**Comment by peppy** [comment]
The logs you attached don't show a crash. Could you attach a video showing this happening, and possibly check your system event viewer logs for any crash there?

**Comment by lkm36** [comment]
I don't have video showing this happen now. I will try to record my game from now on to catch the crash, and there is crash record in my system event viewer logs. The top 6 errors shown in the picture are from osu.
![osucrash](https://github.com/ppy/osu/assets/145571865/3d55259d-a6a3-41b4-ae02-518de4cbe5a9)

**Comment by kli75962** [comment]
I don't have video showing this happen now. I will try to record my game from now on to catch the crash, and there is crash record in my system event viewer logs. The top 6 errors shown in the picture are from osu.
![osucrash](https://github.com/ppy/osu/assets/102646902/14af3759-870c-43f1-96a6-8297f578837a)

**Comment by kli75962** [comment]
sorry, I misclicked the completed button

**Comment by bdach** [comment]
Can you export these error logs? Or at least show one of the ".NET Runtime" log entries?

**Comment by kli75962** [comment]
[123.zip](https://github.com/ppy/osu/files/13364555/123.zip)

**Comment by peppy** [comment]
```
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x65305eaf
Faulting module name: coreclr.dll, version: 6.0.2423.51814, time stamp: 0x653058bd
Exception code: 0xc0000005
Fault offset: 0x00000000001d25b9
Faulting process id: 0x402c
Faulting application start time: 0x01da14b3eea67c4d
Faulting application path: C:\Users\kli92\AppData\Local\osulazer\app-2023.1026.0\osu!.exe
Faulting module path: C:\Users\kli92\AppData\Local\osulazer\app-2023.1026.0\coreclr.dll
Report Id: 296f82dc-9141-42a1-ac61-6d1b2da32f93
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by bdach** [comment]
Until proven otherwise, this is a driver issue. Please try updating your graphics card drivers.

See also: https://github.com/search?q=repo%3Appy%2Fosu+access+violation&type=discussions

**Comment by kli75962** [comment]
I update my graphics card drivers to newest version yesterday but it still crash few times today.
https://github.com/ppy/osu/assets/102646902/94eaf9b4-cffe-44e6-9c49-15636a07e36b

https://github.com/ppy/osu/assets/102646902/379d8653-22fb-429f-9f93-5cd06d56488b
