### ISSUE TITLE
Max achievable accuracy display is incorrect

### ISSUE THREAD

**Issue by yoyyoy** [ppy/osu#25428]
### Type

Cosmetic

### Bug description

max achievable accuracy is higher than what is achievable.

### Screenshots or videos

https://github.com/ppy/osu/assets/43836438/c91224fe-b444-4a6d-bbab-837ec4abb5b5

### Version

2023.1114.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/13344699/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/13344700/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/13344701/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/13344702/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/13344703/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/13344704/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13344705/updater.log)
[database.log](https://github.com/ppy/osu/files/13344706/database.log)
[input.log](https://github.com/ppy/osu/files/13344707/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13344708/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13344709/network.log)

**Comment by bdach** [comment]
Can you attach the replay you used to reproduce this?

**Comment by yoyyoy** [comment]
github says it doesn't support the file type so i changed the extension to .txt
[yoyyoyyoy playing dj TAKA - True Blue (Monstrata) [Halcyon] (2023-11-13_22-49).txt](https://github.com/ppy/osu/files/13349874/yoyyoyyoy.playing.dj.TAKA.-.True.Blue.Monstrata.Halcyon.2023-11-13_22-49.txt)

**Comment by peppy** [comment]
Investigating this one, can reproduce with the replay.

**Comment by DanielPower** [comment]
This appears to have been resolved in #25740.
I've tested the attached replay on latest master. Maximum achievable and actual accuracy match at the end of the replay.
