### ISSUE TITLE
Changing skin via keyboard arrows for the first time will always default to argon

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#25433]
### Type

Game behaviour

### Bug description

The first time you change your skin after launching the game it will always default to argon instead of the next / previous option.

### Screenshots or videos

https://github.com/ppy/osu/assets/58333920/3409b591-a88c-4ac6-8cfd-a49543b9ebe2

### Version

2023.1114.0

### Logs

.

**Comment by peppy** [comment]
Keyboard... arrows...?

**Comment by bdach** [comment]
It's a dropdown thing. https://github.com/ppy/osu-framework/blob/1962cf6c24897066385937519dd0f319c278134f/osu.Framework/Graphics/UserInterface/Dropdown.cs#L241-L269

**Comment by zihadmahiuddin** [comment]
It looks like it's working as expected now. I'm able to reproduce it on 2023.1026.0 but not on master. Some other change in between must've fixed it.
