### ISSUE TITLE
Custom argon skins doesn't load

### ISSUE THREAD

**Issue by JacksonChen666** [ppy/osu#25437]
### Type

Game behaviour

### Bug description

If you try to load an argon based skin (even the one you just modified), the skin will always be the default. No amount of changes in the skin editor will matter.

(I discovered this bug when trying my own osu!lazer build for 2023.1114.0 at 2023-11-12, but it seems like it got into production anyways so here's the bug report!)

### Screenshots or videos

https://github.com/ppy/osu/assets/50755746/c97c5639-a333-4862-b2a0-2292714031f4

### Version

2023.1114.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13346874/database.log)
[input.log](https://github.com/ppy/osu/files/13346875/input.log)
[network.log](https://github.com/ppy/osu/files/13346876/network.log)
[performance.log](https://github.com/ppy/osu/files/13346877/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13346878/runtime.log)

**Comment by peppy** [comment]
Please attach an affected skin.

**Comment by peppy** [comment]
Thanks, I've identified the point of failure and we'll look to get a hotfix out soon. Your skin is intact, even in the new release, so you can rest assured that data has not just been lost.
