### ISSUE TITLE
Score calculation does not have slider end

### ISSUE THREAD

**Issue by Contextualist** [ppy/osu#25435]
### Type

Game behaviour

### Bug description

After the update of version 2023.1114.0, osu! standard score calculation seem to no longer consider slider end. I noticed the behavior change by looking at the scores produced by the previous lazer version (the one I used yesterday) vs scores produced by the current lazer version.

Maybe related to #25342

### Screenshots or videos

![se-score](https://github.com/ppy/osu/assets/16000021/0d10b5d2-6c98-4863-ae67-b474a7d071a1)
> A replay from today (left) vs a replay from yesterday (right). Notice the missing slider end section, and the larger slider tick count (expected?)

![se-leaderboard](https://github.com/ppy/osu/assets/16000021/2bcc3b8a-b36f-4c3f-a3ed-9dd58d568b3d)
> The recent replays are submitted to the leaderboard with no slider end information.

### Version

2023.1114.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/13346299/logs.zip)

[Also attaching the replay from today and the replay from yeterday](https://github.com/ppy/osu/files/13346301/replay-1112%2B1113.zip)

**Comment by bdach** [comment]
This is intentional. Read the [changelog](https://osu.ppy.sh/home/changelog/lazer/2023.1114.0), please.

**Comment by Contextualist** [comment]
If I understand correctly, this update is trying to match the way stable counts slider ticks and combos, but are we also dropping the slider end information all together?

Also, the way it counts slider ends towards combo make sense (in this case, 373+773=1146), 
but what does the new slider ticks represent (in this case, 373+26≠387)?

**Comment by bdach** [comment]
For now this is intended yes. We may revisit this further when matching slider mechanics even closer to stable (see https://github.com/ppy/osu/issues/11769).
