### ISSUE TITLE
New argon combo/accuracy/score counter not displaying values on skins that aren't (customised) argon

### ISSUE THREAD

**Issue by dolkilu** [ppy/osu#25430]
### Type

Skinning

### Bug description

For me and some other users from the change log comment, the new argon counter is not displaying numerical values.
Only displaying the text COMBO, ACCURACY, and score counter has 0 or 1 pixel.

### Screenshots or videos

![2023-11-14 01-12-16](https://github.com/ppy/osu/assets/16611027/43b63b8f-2519-45b3-ad5d-9426554c5447)

### Version

2023.1114.0

### Logs

[performance.log](https://github.com/ppy/osu/files/13344841/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13344842/runtime.log)

**Comment by Stoppedpuma** [comment]
They seem to only work on argon, I'm able to reproduce with custom skins.

**Comment by bdach** [comment]
Placement of the digit assets is [pretty clearly wrong](https://github.com/ppy/osu-resources/tree/master/osu.Game.Resources/Skins/Argon) if this was intended as a component that any skin should be able to use.
