### ISSUE TITLE
osu!mania 7K playfield goes off on mobile screens

### ISSUE THREAD

**Issue by alixdotsh** [ppy/osu#25440]
### Type

Game behaviour

### Bug description

The best way to explain it is the note scaling is too big and not adjusted properly for more than just 4k gameplay. I haven’t tested 5k/6k/8k/etc… but I did test 7k and it went off of my screen

edit: I want to clarify that I did keep UI scaling untouched at default. even downsizing, it didn't fix the issue

### Screenshots or videos

![IMG_2020D10120D7-1](https://github.com/ppy/osu/assets/58949994/833b7cf4-dad8-401e-a9dc-dc7e50569d3b)

### Version

2023.1114.0

### Logs

Cannot get logs from ios

**Comment by peppy** [comment]
ipad i guess

**Comment by bdach** [comment]
Yeah. Turns out the absolute minimum size of the playfield is not 1366x768, it's 1024x768, because that's the default in `DrawSizePreservingFillContainer`. This will manifest on devices whose aspect ratio is 4:3-ish rather than 16:9-ish, so generally tablets.

**Comment by alixdotsh** [comment]
to answer peppy, yes, I use an iPad Pro. 
> easiest way i can think is to either make lazer shrink the skin when it detects it going outside the screen or shrink the mania keys a little bit so its within the borders of the screen

when "shrinking" the skin, I think it should be shrunk based on the borders of the UI scaling. so for default, the border of the screen I guess, but if someone has special UI scaling, it should shrink respectively to that instead

**Comment by The-Grace-God** [comment]
@alixdotsh 
> to answer peppy, yes, I use an iPad Pro.
> 
> > easiest way i can think is to either make lazer shrink the skin when it detects it going outside the screen or shrink the mania keys a little bit so its within the borders of the screen
> 
> when "shrinking" the skin, I think it should be shrunk based on the borders of the UI scaling. so for default, the border of the screen I guess, but if someone has special UI scaling, it should shrink respectively to that instead
> 
> ill test later on an iPhone (15 pro to be specific) to see if I can reproduce the issue to determine if this is just a tablet specific issue or in general

this isn't just a issue with mobile its a resolution and tall display issue as most things were tested with 16:9 in mind and lazer is only scaling the skin based off the Y resolution no matter if its 100px or 1920px so when using a smaller or taller display the skin will get cut off as a result of this the real simple fix is just to check the X res and see if the play-field is beyond that
and for scaling based off of ui can be a issue if you have ui going over the track like i do for some of my skins for stuff like healthbars and hit error meters
best way i can think of is check the X res with a percentage of the screen reserved for the ui and if the play-field goes beyond that shrink the play-field by either stretching it or just straight squishing it

**Comment by The-Grace-God** [comment]
i actually have a perfect screenshot to show this let me find it real quick

**Comment by alixdotsh** [comment]
I wanted to share this before I forgot about it again but, may I suggest there is a new setting added to where players can change the keys scaling themselves? obviously the playfield issue would be in mind, but maybe people can choose to make the zoom/scale "maximum" or they can make it less scaled, hopefully this makes sense.

**Comment by bdach** [comment]
I do not want it to be a setting unless it can somehow be applied in the skin editor. I don't think we're in a place wherein that can be easily done yet.

**Comment by RubberDuckShobe** [comment]
> I wanted to share this before I forgot about it again but, may I suggest there is a new setting added to where players can change the keys scaling themselves? obviously the playfield issue would be in mind, but maybe people can choose to make the zoom/scale "maximum" or they can make it less scaled, hopefully this makes sense.

An option to get the old scale back would be pretty great (at least for my purposes, since I play on an iPad with a keyboard).
Maybe there could be a way to change the scale automatically depending on whether or not a keyboard is connected?
