### ISSUE TITLE
weird healthbar behavior in mania

### ISSUE THREAD

**Issue by The-Grace-God** [ppy/osu#25459]
### Type

Cosmetic

### Bug description

South Park appears to bend in on itself not much to explain here as I don't know what's causing it

### Screenshots or videos

![IMG20231114164542](https://github.com/ppy/osu/assets/66783188/e53ee16f-e47d-426e-ab0f-aa40daeda6b4)

### Version

2023.1114.1-lazer

### Logs

Submitting on phone have to attach separately

**Comment by The-Grace-God** [comment]
[database.log](https://github.com/ppy/osu/files/13358074/database.log)
[input.log](https://github.com/ppy/osu/files/13358075/input.log)
[network.log](https://github.com/ppy/osu/files/13358076/network.log)
[performance.log](https://github.com/ppy/osu/files/13358077/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13358079/runtime.log)

**Comment by bdach** [comment]
Please attach the skin.

**Comment by The-Grace-God** [comment]
> Please attach the skin.

https://github.com/The-Grace-God/Delta-4-mania/releases/tag/V1

No edits have been made since then as I started working on a new theme for a different machine

**Comment by peppy** [comment]
Tracking in https://github.com/ppy/osu/issues/25460.

**Comment by The-Grace-God** [comment]
I can note that even with themes that did use it before the update the health bar is still broken on those themes it's only the stock one that works properly

**Comment by bdach** [comment]
@The-Grace-God are you sure you did not (accidentally or purposefully) save your skin on the latest release?

**Comment by The-Grace-God** [comment]
> @The-Grace-God are you sure you did not (accidentally or purposefully) save your skin on the latest release?

It was last saved on the last release so I doubt it
Could try reimporting from the upload though

**Comment by The-Grace-God** [comment]
No the same issue

**Comment by The-Grace-God** [comment]
The only way I can get the health bar system to work is if I copy it from the argon skin and paste it into my thing

**Comment by CyndaWott** [comment]
HB is bugged only when adding it. Doesn't matter if they are legacy skins or argon pro skin. this was the only way I got it to go to normal. 
https://github.com/ppy/osu/assets/132945252/e470faa2-7e71-4560-98f7-fa371dc9f516
