### ISSUE TITLE
The new osu!Lazer update falsely flags me as a touchscreen player

### ISSUE THREAD

**Issue by kuka012** [ppy/osu#25455]
### Type

Game behaviour

### Bug description

I have been using my samsung galaxy s6 lite (since this July) connected to my pc via spacedesk and have always been using the S pen to play. Also spacedesk has an inbuilt "enable touchscreen control" which I turned off and stayed off from the very beggining of my time playing (there is also an "enable stylus screen control" which is obviously turned on so i can play with the S pen). I was never sure whether it detected me as playing with a touch screen or not but because I turned off the setting I figured it probably didn't. But apperantly from this update I count as a touchscreen user.

### Screenshots or videos

![SmartSelect_20231114_203250_spacedesk](https://github.com/ppy/osu/assets/150837841/0c0d9345-5669-4478-a562-10654565bf9c)
![SmartSelect_20231114_203230_spacedesk](https://github.com/ppy/osu/assets/150837841/58230c06-3d63-47a3-bc45-29d81a0271f4)

### Version

2023.1114.1-lazer

### Logs

[osu!auth.log](https://github.com/ppy/osu/files/13355597/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/13355598/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/13355599/update_success.log)

**Comment by bdach** [comment]
#25446
