### ISSUE TITLE
Distorted audio during some sliders

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#2546]
When playing the map https://osu.ppy.sh/s/347556 I noticed that from 1:08 on audio sounds a little distorted, there is some kind of deep sound in the background which only exist during play mode and only in osu!lazer. That also happens later on from 3:29 onwards. The issue is consistent; it happens every single time. Log files don't seem to show any unusual behavious. I've included a video file where the issue can be seen.
[a.zip](https://github.com/ppy/osu/files/2000897/a.zip)

**Comment by peppy** [comment]
Looks like a slider slide sound gone wrong

**Comment by Morilli** [comment]
This seems to have mostly been fixed in 2018.1105.0 via https://github.com/ppy/osu/pull/3600, yet some sliders near the end of the map still play a slightly distorted sound.

**Comment by peppy** [comment]
@Morilli can't seem to repro any more. can you confirm this is better now?

**Comment by Morilli** [comment]
@peppy I can reproduce this issue, but having looked into it a bit more, this seems to be an issue with how samples are tied to hitobjects, and I'm honestly not sure whether this is an issue on osu!lazer's side or osu!stable's.

The map I originally linked (https://osu.ppy.sh/s/347556) seems to have done very weird things in regards to hitsounds, and all the "distorted" sounds are actually hitsamples that are included in the map, but aren't actually supposed to play at any point in the map (as far as I noticed), but they do in lazer.

Take for example the sliders starting from 1:04:172. They don't play any unusual samples in stable, but they do play the ``drum-sliderslide.wav`` sample in lazer, even though the map should only use only soft samples.

**Comment by peppy** [comment]
Will milestone this for further investigation.

**Comment by Morilli** [comment]
Here is a more of less minimal reproduction beatmap: [Camellia - flying in the flow of deep-sea.zip](https://github.com/ppy/osu/files/5395403/Camellia.-.flying.in.the.flow.of.deep-sea.zip) (it's a .osz)

Apparently, as far as I understand, lazer tries to apply the slider's hitsample (which is set to be of the "drum" bank in this ^ case)  to the slider body / slider slide, which is incorrect or at least not what stable does.

Here is a "fix" that resolves this issue but might add ten more; I don't know enough about the entire sample-flow to know for sure: 
```diff
diff --git a/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs b/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
index b00d12983..906263734 100644
--- a/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
+++ b/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
@@ -2,7 +2,6 @@
 // See the LICENCE file in the repository root for full licence text.
 
 using System;
-using System.Linq;
 using osuTK;
 using osu.Framework.Graphics;
 using osu.Game.Rulesets.Objects.Drawables;
@@ -95,14 +94,11 @@ protected override void LoadSamples()
             slidingSample?.Expire();
             slidingSample = null;
 
-            var firstSample = HitObject.Samples.FirstOrDefault();
+            var controlPointSample = slider.SampleControlPoint?.GetSampleInfo("sliderslide");
 
-            if (firstSample != null)
+            if (controlPointSample != null)
             {
-                var clone = HitObject.SampleControlPoint.ApplyTo(firstSample);
-                clone.Name = "sliderslide";
-
-                AddInternal(slidingSample = new PausableSkinnableSound(clone)
+                AddInternal(slidingSample = new PausableSkinnableSound(controlPointSample)
                 {
                     Looping = true
                 });

```

**Comment by bdach** [comment]
I've had a tiny peek at this and while current `master` is incorrect in using `HitObject.Samples` the way it does (which ends up using the slider's last node samples), the above proposed patch is not correct, either. In fact, stable can be made to play `drum-sliderslide` if, for instance, the following change is applied to the `.osu` file:

```diff
-122,49,64172,6,0,L|51:45,3,57.7499982376099,8|0|0|0,3:2|3:0|3:0|3:0,0:0:0:0:
+122,49,64172,6,0,L|51:45,3,57.7499982376099,8|0|0|0,3:2|3:0|3:0|3:0,3:0:0:0:
```

Looking at `Legacy.ConvertHitObjectParser` the slider-global sample info (i.e. the part changed above, or `split[10]` in code), is discarded (overwritten) entirely if the slider has node samples, which is probably the key oversight here.

Any changes in this area will have to be made with extra care as to ensure that other ruleset conversions aren't broken.

**Comment by smoogipoo** [comment]
Before anything is changed around these parts of code, I'd really like to see the whole "replace with last node samples" thing removed. As I mentioned before, I believe it's incorrect since it's used for determining the tick samples:
https://github.com/ppy/osu/blob/daa0a05d9e95ffd0a9994e5da027cbd502a84793/osu.Game.Rulesets.Osu/Objects/Slider.cs#L217-L231

Perhaps block `base.PlaySamples()` in `DrawableSliderTail` and have a public delegating method for `DrawableSlider` to call at the correct point in time...

**Comment by peppy** [comment]
@Morilli Are you able to test this on the latest release? The underlying code has been refactored in multiple ways and it'd be appreciated if you can check again.

**Comment by bdach** [comment]
I've tested and I'm pretty sure this is still an issue. Mainly because it's not so much a skinning issue as a decoding one as described above.

**Comment by Morilli** [comment]
I've tested with both my modified short version and the original version of the map, and I can actually not reproduce this anymore. 
Unless you @bdach have a concrete example of this issue still occuring somewhere I'm calling this fixed.

**Comment by bdach** [comment]
I read

> all the "distorted" sounds are actually hitsamples that are included in the map, but aren't actually supposed to play at any point in the map (as far as I noticed)

above and once I heard the buzzing samples that are included in the map, concluded that this isn't fixed. But I just cross-checked stable and the sounds do seem to be correct, and that original assertion was never true in the first place. Let's just close this for now then.
