### ISSUE TITLE
Slider tick counter doesn't show the max correctly on the results screen

### ISSUE THREAD

**Issue by peppy** [ppy/osu#25464]
### Discussed in https://github.com/ppy/osu/discussions/25463

<div type='discussions-op-text'>

<sup>Originally posted by **felipemarins** November 15, 2023</sup>
I don't know if it's intended to work this way for now, but after the last update the slider tick max on results screen is always equal to the achieved slider ticks number. Here is two results that I achieved on the same beatmap difficulty:
![image](https://github.com/ppy/osu/assets/53406701/58f73ee6-d00f-49a7-935e-6d066e117b87) ![image](https://github.com/ppy/osu/assets/53406701/2e0e4fa7-9961-4389-91b2-c3066c99f647)</div>

**Comment by felipemarins** [comment]
Just a small update on this issue. I was testing here and the affirmation about the slider tick max being always equal to the achieved slider ticks number is incorrect. It may be different in cases where you miss a tick that counts as a miss. I don't know it's a useful information, but I just wanted to correct myself.

**Comment by bdach** [comment]
Yes we know why this is happening thanks.

**Comment by DarkbitNetwork** [comment]
I believe this issue hasn't been fixed with 2023.1130.0-lazer from my testing.

1 slider end is missed and it seems like slider tick counter's max is still reduced

https://github.com/ppy/osu/assets/43719333/d363c28f-67f9-4ac2-bf36-232475d88974
