### ISSUE TITLE
Argon Health Bar still broken in an oddly specific way

### ISSUE THREAD

**Issue by WalmartWhiteCat** [ppy/osu#25460]
### Type

Cosmetic

### Bug description

The healthbar that comes loaded with the skin is fine, but the graphic on the tile and trying to add one yourself are broken. And yes, I tried to resize it. Nothing happened. It's like the healthbar is stuck like this for some reason. This can't just be me, right?

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/149839359/5ea34d2e-355f-43ac-9ffd-ce5a953ba557)

### Version

2023.1114.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13358744/database.log)
[input.log](https://github.com/ppy/osu/files/13358745/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13358746/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13358747/network.log)
[performance.log](https://github.com/ppy/osu/files/13358748/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13358749/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13358750/updater.log)

**Comment by The-Grace-God** [comment]
The temporary fix until it gets uploaded is that you can just copy and paste the health bar from the actual argon skin and it should work fine
