### ISSUE TITLE
Difficulty sort groups beatmaps by set, making it mostly useless

### ISSUE THREAD

**Issue by jorolf** [ppy/osu#2547]
The current design for beatmapsets with only one beatmap is this:
![old](https://user-images.githubusercontent.com/12570757/40009868-773e3a08-57a3-11e8-98e8-92c8e3c688a0.png)

This is different from what stable does where it only uses one panel:
![stable](https://user-images.githubusercontent.com/12570757/40009935-a4c092d2-57a3-11e8-8c31-d75899015545.png)

perhaps the design could be adjusted to be similar to stable:
![new](https://user-images.githubusercontent.com/12570757/40010272-83c69206-57a4-11e8-972d-9cc4575fbe82.png)

**Comment by DudeMartin** [comment]
What about just displaying the version of the beatmap and its star rating?

![singlemapsetmock](https://user-images.githubusercontent.com/1411294/40276286-15901a4e-5bd4-11e8-8fc2-b55fe788adf1.png)

**Comment by lukis101** [comment]
Longer diff names would push star ratings further to the right thus giving visual inconsistency. (Not a designer, just my 2¢)

**Comment by peppy** [comment]
Moving this out of milestone. It's clear we do not have the bandwidth to implement this just yet.

**Comment by LittleEndu** [comment]
Is there a design for this? I'm looking to rework how the carousel draws its panels so a design would be nice to have.

**Comment by peppy** [comment]
We haven't finalised the UX or design for this just yet. Needs further discussion, so stick with what we have for now.

**Comment by LittleEndu** [comment]
I want to try implement carousel grouping. Can I make up a design that fits what we have right now or should we wait for the new design to be final before implementing the logic necessary for carousel grouping?

**Comment by peppy** [comment]
You're most welcome to try, as long as you're prepared to get shot down. I still don't have anything yet (and would need to experiment myself to give any kind of direction).

**Comment by smoogipoo** [comment]
Groupings were added to the designs https://www.figma.com/file/DXKwqZhD5yyb1igc3mKo1P/Song-Select-Draft-2?node-id=0%3A1
@arflyte Can you confirm whether the design showing carousel groupings (as seen in the second from bottom-right) is the latest design or not? Because the panels in the top-most design are significantly different. Are there two different panel designs for grouped vs non-grouped displays?

**Comment by LittleEndu** [comment]
Another question is what this issue originally was: Should beatmap sets with single difficulty be displayed as if they would in the non-consecutive case or should header and difficulties version be preferred when not grouping?

**Comment by halbGefressen** [comment]
To be honest, I think the behaviour should just mimic the old osu! client. E.g. sorting by difficulty should yield the separate difficulties in the exact difficulty ordering.

**Comment by peppy** [comment]
That is the plan. We have a design ready to go for this, and you will probably see it appear within the next few months.
