### ISSUE TITLE
Undo changes to sliders in editor will also change and lock their sampleset to normal set

### ISSUE THREAD

**Issue by FukutoTojido** [ppy/osu#25488]
### Type

Game behaviour

### Bug description

Upon undoing any changes to a slider in Lazer editor, its sample set is locked to `normal` although the sample set shown on screen is still the initial value which is `soft`. Even if you are trying to change the sample set by hand, the sample set is still locked to `normal`. A copy of the slider still gets affected by this bug. Therefore, the only solution is to create a completely new slider.

### Screenshots or videos

https://github.com/ppy/osu/assets/39629922/6eaa06f4-3c6c-4858-8c72-f20047f1ae67

For comparison, this is what my skin's sample set sound like:

https://github.com/ppy/osu/assets/39629922/a0135471-5f5a-4efe-aa44-274d851e97ed

Upon further inspection into the `.osu` file, it seems that the `edgeSets` parameter of the object has been set from `0` (No custom sample set) to `1` (Normal set). Since osu!lazer has not been implemented the ability to change individual slider part sample set and addition set yet, there is no way to change them back by hand.

![notepad_4dOedpGiuE](https://github.com/ppy/osu/assets/39629922/6dd1ad58-2236-4499-a11b-72476a72b642)

### Version

2023.1114.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13387053/database.log)
[input.log](https://github.com/ppy/osu/files/13387054/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13387055/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13387057/network.log)
[performance.log](https://github.com/ppy/osu/files/13387058/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13387059/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13387060/updater.log)

**Comment by peppy** [comment]
Is there a reason the red box highlight is a different slider in your screenshots? Nothing from the two matches.

**Comment by FukutoTojido** [comment]
My apology. I selected the wrong object. This should be the corrected one.

![notepad_zqDt1mqi0B](https://github.com/ppy/osu/assets/39629922/a9457269-2123-4564-823f-baba04e8636d)

**Comment by peppy** [comment]
Are you editing a beatmap where you've already adjusted samples in stable? Or is this a lazer-first beatmap? I can't seem to reproduce after testing the same adjustment on two different ranked beatmaps.

Could you try on a different beatmap and confirm that you can reproduce it>?

**Comment by FukutoTojido** [comment]
I was editing a beatmap imported from stable and from further testing on both local maps and ranked maps, I have found out that only sliders created in Lazer will have this bug.

### Local map imported from stable

| Editing and unoding on stable-created object   | Editing and undoing on lazer-created object  |
|---|---|
| <video src="https://github.com/ppy/osu/assets/39629922/8f79ed86-3bb3-4c30-9aad-bfe287ec2144"/> | <video src="https://github.com/ppy/osu/assets/39629922/c03716f6-8fac-45a9-8e43-50647076997b" /> |

### Ranked map

Beatmap in the videos: **[Walkuere - Kuchibiru no Toushou](https://osu.ppy.sh/beatmapsets/1714629#osu/3503514)**

| Editing and unoding on stable-created object   | Editing and undoing on lazer-created object  |
|---|---|
| <video src="https://github.com/ppy/osu/assets/39629922/8abdf9be-c5ca-4288-80b0-4f8f916281c5"/> | <video src="https://github.com/ppy/osu/assets/39629922/5d6f2906-819d-450a-9dd3-3625bd5b15b7" /> |

**Comment by OliBomby** [comment]
This should be fixed by https://github.com/ppy/osu/pull/23443 which adds the ability to change the edge hitsounds of sliders.
