### ISSUE TITLE
Score not seeming to calculate correctly

### ISSUE THREAD

**Issue by JeroenvanBeckhoven** [ppy/osu#25484]
### Type

Game behaviour

### Bug description

For some reason my scores seem very low even tough I am peforming okay. The score multiplier is 1.00x or in the screenshots provided below even higher. This seems to happen no matter what mods I use. My score compared to other scores who did worse does not seem possible. As seen in the screenshots I (Jeroonie_XD) did somewhat better than the other person but had only half his score. 

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/142342673/30a50ab5-51c3-41ea-9318-c731c944c95f)
![image2](https://github.com/ppy/osu/assets/142342673/f3769f66-4f94-4dc8-83b8-30f719785010)

### Version

Lazer 2023.1114.1

### Logs

[database.log](https://github.com/ppy/osu/files/13379938/database.log)
[input.log](https://github.com/ppy/osu/files/13379939/input.log)
[network.log](https://github.com/ppy/osu/files/13379940/network.log)
[performance.log](https://github.com/ppy/osu/files/13379942/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13379943/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13379945/updater.log)

**Comment by peppy** [comment]
Many scoring changes have happened recently, meaning that scores may not match against older scores. We will be resetting the leaderboards in the near future.
