### ISSUE TITLE
Mania track moves while in skin edit mode

### ISSUE THREAD

**Issue by The-Grace-God** [ppy/osu#25482]
### Type

Cosmetic

### Bug description

when entering the skin editor mode during gameplay on a vertical display the mania track instead of stretching it will move to the top and the bottom will move to the center of the screen

### Screenshots or videos

![IMG20231115195742](https://github.com/ppy/osu/assets/66783188/19b30d39-e144-4917-9921-0ebf81cd1c99)

### Version

2023.1114.1-lazer

### Logs

i cant grab them as I'm writing this from school and this issue was discovered on my main machine that's at home

**Comment by The-Grace-God** [comment]
and yes the vertical display is something i actually use as i use it mainly for SDVX which is intended for vertical play

**Comment by bdach** [comment]
please attach skin

**Comment by The-Grace-God** [comment]
@bdach 
> please attach skin

ill have to do that when i get home as i don't have this one saved online yet due to it being unfinished

**Comment by Kori3** [comment]
its not a skin issue, the gameplay playfield layer-thing doesn't scale properly in the skin editor only if a replay is paused
this only happens in mania

https://github.com/ppy/osu/assets/70714793/2a78f7e4-ebeb-4d17-a589-b81ae2ade037

the playfield moves to the right if a horizontal screen is being used

https://github.com/ppy/osu/assets/70714793/4135289c-bef8-4616-baf9-4c2b418d399f

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/23814
