### ISSUE TITLE
Wait at least one  second before restarting issue

### ISSUE THREAD

**Issue by NympheSorchest** [ppy/osu#25495]
### Type

Game behaviour

### Bug description

Even im not playing i will get notification says "Wait at least one  second before pausing again" everytime if i dont close the game.

### Screenshots or videos

https://github.com/ppy/osu/assets/151243376/9d59bc88-ba68-48cf-80cd-2eff6901c504

### Version

20231102.5

### Logs

[session.log](https://github.com/ppy/osu/files/13397340/session.log)
[update_success.log](https://github.com/ppy/osu/files/13397341/update_success.log)
[osu!auth.log](https://github.com/ppy/osu/files/13397342/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/13397343/runtime.log)

**Comment by bdach** [comment]
Issues with stable go [here](https://github.com/ppy/osu-stable-issues/issues).
