### ISSUE TITLE
Beatmap Import Crash

### ISSUE THREAD

**Issue by cscp** [ppy/osu#255]
I am importing beatmaps to osu!lazer and i have 1 map and i try to import a second one and it dont works

OS:Windows 7
Architecture:x86 / x32

**Comment by KogasakaYou** [comment]
Try to unblock the "release.zip" by right click and go to properties you should be see unblock check box under the tab, extract it and drag song file to "osu.exe"

If it's show blank screen and crash try to open osu first and drag the file to "osu.exe" (remember to not drag to osu window) restart osu and check the song if it's available if stil not work try to drag and restart it again until work

note: only new song from november 2016 can be added i cannot guarantee all song can be added under that date

**Comment by cscp** [comment]
Ok everthing works now. Thanks :)
