### ISSUE TITLE
User profile loads indefinitely if logged out

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#25503]
### Type

Cosmetic

### Bug description

I've checked with other overlays (such as chat, beatmap listing, etc.) and they all just show the clickable "login to view" message with no loading in front of it.

For some reason, the user overlay has a constant loading spinner that prevents the user from clicking on the "please log in" message. Nothing special, but it looks wrong.

You can easily achieve this with the following steps:
- download a beatmap (while logged in)
- log out (which happened in my case after an update for some reason, on mobile)
- restart the game (probably not necessary, but just to have the fresh, non-logged-in experience in case you need to log out)
- go to the carousel and click on a mapper name from the wedge

### Screenshots or videos

![Screenshot_20231119-014837](https://github.com/ppy/osu/assets/43073074/fe897b76-be2a-46ed-99f2-3707ebb15a4d)

### Version

2023.1114.1-lazer

### Logs

(It doesn't permit me to access the logs from the phone for some reason, I will be able to do it from the computer but in a while. Please ask if needed.)

**Comment by Stedoss** [comment]
I believe the loading state regressed in https://github.com/ppy/osu/pull/22006/commits/a124c967dfd96a671640b24734f9e9c10d574f56, the loading overlay only gets hidden on request success.

Worth noting that logging in whilst on this screen does not load the user profile, it probably needs something like this https://github.com/ppy/osu/blob/166518db7a84ce5619b7ee74a014651dd9256f22/osu.Game/Overlays/BeatmapSetOverlay.cs#L85-L90

I've had a look at this today, but I'm sure someone will beat me to a decent fix!
