### ISSUE TITLE
Trackpads not reverting controls in-game with left handed controls turned on with raw input

### ISSUE THREAD

**Issue by BashhScriptKid** [ppy/osu#25527]
### Type

Game behaviour

### Bug description

I use my laptop with mouse on my left hand with the controls inverted (right click as left click and left click as right click)

When I use trackpad on other apps, it works like usual, you tap with one finger, it's mapped to a normal left click and vice versa. But on osu!, It takes the inverted control settings too seriously, I have to tap with 2 finger to register a normal left click to it and vice versa.

### Version

2023.1114.1-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/13425677/input.log)
[updater.log](https://github.com/ppy/osu/files/13425759/updater.log)
[performance.log](https://github.com/ppy/osu/files/13425762/performance.log)
[network.log](https://github.com/ppy/osu/files/13425768/network.log)
[runtime.log](https://github.com/ppy/osu/files/13425766/runtime.log)

**Comment by Susko3** [comment]
- This is a problem in SDL, so I've reported it upstream: https://github.com/libsdl-org/SDL/issues/8597

There's not much we can do. So, until it's fixed, you'll have to find a workaround, sorry.

**Comment by Susko3** [comment]
Fixed upstream in https://github.com/libsdl-org/SDL/commit/eae81ec80e3448fe4bcde60719e916f35cb42df6. The fix will trickle down to osu! at some point in the future (when the dependencies are updated).
