### ISSUE TITLE
Directly pasting copied images from the clipboard is not allowed

### ISSUE THREAD

**Issue by toadsworth-jr** [ppy/osu#25543]
### Type

Game behaviour

### Bug description

Directly copying images doesn't allow osu to paste it as a Sprite.
Do it too often, and it is grounds for a crash.

### Screenshots or videos

https://github.com/ppy/osu/assets/75596775/bdcb21f1-81e7-4abf-92d5-e6b42d31d35b

### Version

2023.1114.1

### Logs

[network.log](https://github.com/ppy/osu/files/13441163/network.log)
[runtime.log](https://github.com/ppy/osu/files/13441165/runtime.log)
[performance.log](https://github.com/ppy/osu/files/13441166/performance.log)
[updater.log](https://github.com/ppy/osu/files/13441167/updater.log)
[database.log](https://github.com/ppy/osu/files/13441168/database.log)

**Comment by bdach** [comment]
I don't know about allowing arbitrary content like that. But it definitely should not be crashing.

**Comment by bdach** [comment]
I'm gonna close this as the crash is resolved; pasting images into the game should be a separate feature request.
