### ISSUE TITLE
image is not animating

### ISSUE THREAD

**Issue by The-Grace-God** [ppy/osu#25623]
### Type

Cosmetic

### Bug description

when adding a gif to the skin it will only show the first frame and when i select it in the skin-editor it changes it to a different asset without being able to change it back

### Screenshots or videos

https://github.com/ppy/osu/assets/66783188/ddd5fad9-b963-4551-8a4e-2829084b5271

### Version

2023.1130.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/13518400/network.log)
[performance.log](https://github.com/ppy/osu/files/13518402/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13518403/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13518404/updater.log)
[database.log](https://github.com/ppy/osu/files/13518405/database.log)
[input.log](https://github.com/ppy/osu/files/13518406/input.log)

**Comment by bdach** [comment]
I'm not sure gifs will ever be supported, for whatever it's worth. Very low priority anyhow.

**Comment by The-Grace-God** [comment]
@bdach 
> I'm not sure animated gifs will ever be supported, for whatever it's worth. Very low priority anyhow.

Main reason for trying this was i wanted to add a fading effect on top of some assets (like a black background with the player or song name on top) but as far to my knowledge there is no way to do this other than with the notes or the keys themselves

**Comment by bdach** [comment]
> i wanted to add a fading effect on top of some assets (like a black background with the player or song name on top)

I'm not sure what that has to do with animation. You can use pngs with transparency, but they will be static.

**Comment by The-Grace-God** [comment]
@bdach 
> > i wanted to add a fading effect on top of some assets (like a black background with the player or song name on top)
> 
> I'm not sure what that has to do with animation. You can use pngs with transparency, but they will be static.

i meant by fading in and out kinda like a slow flash

**Comment by peppy** [comment]
This is not supported and would need to be a feature request.
