### ISSUE TITLE
osu! lazer make my pc dead

### ISSUE THREAD

**Issue by NamGitHub2002** [ppy/osu#25638]
### Type

Other

### Bug description

likely the "LegacyScoreCounter" is missing details and make my pc bsod

### Screenshots or videos

![20231201_192023](https://github.com/ppy/osu/assets/120299835/cf0d700e-7267-4424-b22f-eb7e97aa0aa2)

https://github.com/ppy/osu/assets/120299835/b336e363-2602-4954-9f65-c09a3188ab94

### Version

2023.1130.0

### Logs

[performance.log](https://github.com/ppy/osu/files/13526877/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/13526878/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/13526879/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/13526881/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/13526882/performance-update.log)
[updater.log](https://github.com/ppy/osu/files/13526884/updater.log)
[database.log](https://github.com/ppy/osu/files/13526887/database.log)
[input.log](https://github.com/ppy/osu/files/13526888/input.log)
[network.log](https://github.com/ppy/osu/files/13526889/network.log)
[runtime.log](https://github.com/ppy/osu/files/13527031/runtime.log)

**Comment by bdach** [comment]
What is this?

```
2023-12-01 12:25:12 [verbose]: Found a critical process died
2023-12-01 12:25:12 [verbose]: Host execution state changed to Freezing
2023-12-01 12:25:12 [verbose]: Host execution state changed to Critical
2023-12-01 12:25:12 [verbose]: Host execution state changed to Stopping
2023-12-01 12:25:12 [verbose]: Host execution state changed to Stopped
2023-12-01 12:25:12 [verbose]: Can't find the name of Intel ICD OpenGL driver
```

It should not be possible for the game to produce all but two of these lines in the log. `Stopping` and `Stopped` are [the only two valid execution states](https://github.com/ppy/osu-framework/blob/567f608d7a529de664a69bf653e21997bb2669b2/osu.Framework/Platform/GameHost.cs#L1487-L1513).

Where did you download the game from?

**Comment by NamGitHub2002** [comment]
> What is this?
> 
> ```
> 2023-12-01 12:25:12 [verbose]: Found a critical process died
> 2023-12-01 12:25:12 [verbose]: Host execution state changed to Freezing
> 2023-12-01 12:25:12 [verbose]: Host execution state changed to Critical
> 2023-12-01 12:25:12 [verbose]: Host execution state changed to Stopping
> 2023-12-01 12:25:12 [verbose]: Host execution state changed to Stopped
> 2023-12-01 12:25:12 [verbose]: Can't find the name of Intel ICD OpenGL driver
> ```
> 
> It should not be possible for the game to produce all but two of these lines in the log. `Stopping` and `Stopped` are [the only two valid execution states](https://github.com/ppy/osu-framework/blob/567f608d7a529de664a69bf653e21997bb2669b2/osu.Framework/Platform/GameHost.cs#L1487-L1513).
> 
> Where did you download the game from?

i download in osu.ppy.sh

**Comment by bdach** [comment]
> can I take a screenshot lol?

If you must, as long as the screenshot is in english... I'm not sure why this is a problem at all.

**Comment by NamGitHub2002** [comment]
thank everyone, problem solved with reinstall windows.
