### ISSUE TITLE
Multiple skip sections before beatmap starts

### ISSUE THREAD

**Issue by brandondong** [ppy/osu#25633]
### Type

Game behaviour

### Bug description

Similar issue to https://github.com/ppy/osu/issues/25263. Can be reproduced for https://osu.ppy.sh/beatmapsets/132824#osu/344643.

On stable, clicking Skip starts the beatmap. On lazer, pressing Skip twice is required if the first Skip is pressed relatively quickly.

### Version

2023.1130.0, happened on previous version too

### Logs

N/A

**Comment by rushiiMachine** [comment]
Found the issue behind this, this seems to be an intentional feature for storyboards (the linked map has a long intro before the first hitobject):
https://github.com/ppy/osu/blob/668ce937a8d879ebf982ca4bdf1a8ccb1c6cfe36/osu.Game/Screens/Play/MasterGameplayClockContainer.cs#L187-L189
(from 4 years ago, https://github.com/ppy/osu/commit/8369be90f20842c6b9a6aaf4eba5a4671c0c2915#, "Allow skip button to actuate more than once")

Should it match stable instead?

**Comment by bdach** [comment]
> Should it match stable instead?

well stable source says

```csharp
        protected bool AllowDoubleSkip
        {
            get
            {
                int leadIn = leadInTime < 10000 ? -leadInTime : 0;
                return !(this is PlayerVs)
                       && AudioEngine.Time < leadIn - (InputManager.ReplayMode ? 50 : 0)
                       && SkipBoundary > 6000;
            }
        }
```

so i'm not sure i can immediately tell why this isn't "matching stable".

**Comment by rushiiMachine** [comment]
Maybe it would be better to not allow double skipping entirely if storyboards are disabled, as there's no point.

**Comment by rushiiMachine** [comment]
For this specific map, it seems like the leadin time is around ~1900ms, which stable requires a lead-in time of >=10s
Lazer however seems to completely ignore this and instead only checks if there is any lead in at all and then that the skip target is over 6000ms. (for this map it's 8058ms)

I think lazer has correct behavior in this case, no?
Either way double skipping shouldn't even exist with storyboard off.

**Comment by bdach** [comment]
i will fix this myself because whatever you PR i will have to cross check against stable anyway so might as well cut out the middleman.
