### ISSUE TITLE
Pausing gameplay can cause phantom misses

### ISSUE THREAD

**Issue by wawdili** [ppy/osu#25655]
### Type

Game behaviour

### Bug description

Move the mouse over the slider head and pause the game (at this point, the slider still has a long time to hit), then continue the game. When you click the yellow cursor, you will receive a miss, but the slider head does not disappear. Then, when the hit time of the slider head is reached (the big circle coincides with the small circle), it will disappear and receive an additional miss, both of which are missed slider tick.

However, this problem does not occur during replays, and the score of the completed replay is higher than the score after the game, and the score of the replay is the normal expectation.

### Screenshots or videos

This video illustrates everything:
https://github.com/ppy/osu/assets/87159802/68353edf-e459-4c61-b834-560e4160930d

### Version

2023.1130.0

### Logs

；

**Comment by peppy** [comment]
Tracking via https://github.com/ppy/osu/issues/26442.
