### ISSUE TITLE
Game crashes after changing resolution [Hyprland, Arch]

### ISSUE THREAD

**Issue by iceeburr** [ppy/osu#25657]
### Type

Crash to desktop

### Bug description

I tried installing osu like I always do, I open the game, I know the resolution would be messed up so I instantly go to the settings, change from Default to my resolution which is 2560x1440 and then the osu window just vanishes from view like it just closed itself. The game's music is still present and the process still runs. You can stop the game completely by forcefully killing the process with `pkill osu` or `pkill osu-lazer` (whatever works for you), then I hear a nice beep sound because the game's audio glitched, it continues for a few seconds then stops, so I recommend lowering your volume just in case.. After launching the game again it won't start. I tried starting it from the CLI command `osu-lazer`. It outputs this:
```
~
❯ osu-lazer
touch: cannot touch '/home/iceeburr/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
wp_viewport@35: error 2: source rectangle out of buffer bounds

~ took 2s
```
I get the 'touch' thing every time I try to start it, so that's not the issue. What we are looking at is the wp_viewport. Whenever changing the resolution to some specific numbers osu just crashes. It does not happen for all resolutions, but most will break. Sometimes it doesn't crash when relaunching and that resolution works even though it crashed the first time. Look at the video, I showcase everything and how it happens. I can't even properly explain it, it's this bizarre.

### Screenshots or videos

*audio warning, might have a loud beep crash sound so lower your volume please
the video is really compressed, that's why the quality is so bad, it's only to show you what happens visually and you can clearly see it happening. there is no specific timestamp since I show multiple ways that it crashes from the same error*

https://github.com/ppy/osu/assets/85520957/d62050d0-8469-4ad6-97b0-6f1da702c314

### Version

2023.1130.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13540116/database.log)
[input.log](https://github.com/ppy/osu/files/13540117/input.log)
[performance.log](https://github.com/ppy/osu/files/13540118/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13540119/runtime.log)

**Comment by bdach** [comment]
This is either a wayland issue, a hyprland issue, or an sdl issue. Nothing that can be done about it in this repository, and we cannot debug it without reproducing your exact setup.
