### ISSUE TITLE
Submitting better score on a beatmap in a playlist doesn't overwrite the old score

### ISSUE THREAD

**Issue by DarkbitNetwork** [ppy/osu#25654]
### Type

Game behaviour

### Bug description

I was grinding for better score on beatmap spotlights but then I noticed that the completed beatmaps counter is higher than the number of beatmaps in a playlist and also the fact that my playlist placement is higher than usual.

So I decided to do a little test by making my playlist and submitting a play then overwriting it (see screenshot 1). For some reason, the old score isn't replaced by the better score meaning it's possible to get more total score than it's possible in a playlist. And in some cases (see screenshot 2), allows you to go above 100% total accuracy. 

I'm pretty sure this doesn't happen before 2023.1130.0-laser so I'm gonna guess something broke in the new update.
### Screenshots or videos

The first score is 994,880 and the second score is 1,000,000
![thats NOT supposed to happen AT ALL](https://github.com/ppy/osu/assets/43719333/15930f04-719f-4a55-82d8-af6594c22579)

Somebody's PB having more accuracy than 100%. This is done on [osu! Beatmap Spotlights (Autumn 2023) Playlist C](https://osu.ppy.sh/multiplayer/rooms/475123) by the way.
![even worse](https://github.com/ppy/osu/assets/43719333/d90844a1-ed65-467f-aa01-1d0afc719dcf)

### Version

2023.1130.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/13538188/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13538189/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13538190/updater.log)
[database.log](https://github.com/ppy/osu/files/13538191/database.log)
[input.log](https://github.com/ppy/osu/files/13538192/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13538193/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13538194/network.log)

**Comment by peppy** [comment]
We're working through a fix for this, stay seated please.

**Comment by bdach** [comment]
As per https://discord.com/channels/188630481301012481/188630616286167041/1181571441544663121, this should be theoretically resolved now.
