### ISSUE TITLE
Late hits on short sliders can cause incorrect combo breaks

### ISSUE THREAD

**Issue by Natelytle** [ppy/osu#25651]
### Type

Game behaviour

### Bug description

This issue can happen with buzz sliders or with slider streams, the latter being much more apparent.

In [this replay](https://osu.ppy.sh/scores/osu/4331397217), there is a sliderbreak at 1348 combo on a buzz slider which was clicked after the first repeat. In [this other replay](https://osu.ppy.sh/scores/osu/3806985799), there is a sliderstream at 1826 combo where most of the sliders broke combo, despite being an FC in stable. 

 This issue is caused by 550340790759db6f29c2a18613922503770239fa.

### Screenshots or videos

https://github.com/ppy/osu/assets/92956514/bccae9ab-303f-4246-be7f-c1d99b93d31a

https://github.com/ppy/osu/assets/92956514/dc8fc926-28fe-4327-8b96-06f307d4da1e

### Version

2023.1130.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13537657/database.log)
[input.log](https://github.com/ppy/osu/files/13537658/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13537659/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13537660/network.log)
[performance.log](https://github.com/ppy/osu/files/13537661/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13537662/runtime.log)

**Comment by smoogipoo** [comment]
Resolving this is going to be loosely related to https://github.com/ppy/osu/pull/25594, as well as the ongoing discussion in https://github.com/ppy/osu/discussions/25129

**Comment by peppy** [comment]
@smoogipoo tentatively assigning this one to you. not sure this needs to be in the project if it only affects legacy replay playback, but definitely worth looking into to see what exactly is going on stable's end, and you are the deepest in slider knowledge right now.

**Comment by smoogipoo** [comment]
This issue would also be resolved by the recent changes in https://github.com/ppy/osu/pull/25776

**Comment by peppy** [comment]
For reference, can you explain how that PR fixes a stable compatibility issue?

**Comment by smoogipoo** [comment]
The miss here is a case we've discussed recently - a key is being held from a previous object while cursor enters the next slider. The next slider is a buzz slider, so the repeat gets judged before the head is pressed with the intended key for this slider.

This condition kicks in, which forces a miss on the head:

https://github.com/ppy/osu/blob/deef7dae1db7c91dab275e5cfafce7fefe3cad52/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderRepeat.cs#L97-L98

The PR above doesn't allow the repeat to get judged until the head is judged.
