### ISSUE TITLE
Inconsistency between score when set and score when replayed

### ISSUE THREAD

**Issue by BoTheBanana** [ppy/osu#25661]
### Type

Game behaviour

### Bug description

I set a 1 100 play on [this](https://osu.ppy.sh/beatmapsets/1495669#osu/3066107) map and when watched through replay it show it as an SS.

replay uploaded as a txt because github would not let me upload the osr: [BoTheBanana playing Various Artists - Jump _ Stream Practice (Kailler) [Cellina_s Bravely You [Memorial]] (2023-12-03_18-41).txt](https://github.com/ppy/osu/files/13541188/BoTheBanana.playing.Various.Artists.-.Jump._.Stream.Practice.Kailler.Cellina_s.Bravely.You.Memorial.2023-12-03_18-41.txt)

### Screenshots or videos

# Pressing on the score
![osu_2023-12-03_18-53-26](https://github.com/ppy/osu/assets/76603534/c4c36394-4158-4122-adcd-d8974813c58b)
# After watching replay
![osu_2023-12-03_18-53-37](https://github.com/ppy/osu/assets/76603534/e26dcb35-1b72-4866-88d2-5b98de760b98)

### Version

2023.1130.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13541140/database.log)
[input.log](https://github.com/ppy/osu/files/13541141/input.log)
[network.log](https://github.com/ppy/osu/files/13541142/network.log)
[performance.log](https://github.com/ppy/osu/files/13541143/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/13541146/performance-draw.log)
[performance-audio.log](https://github.com/ppy/osu/files/13541149/performance-audio.log)
[performance-input.log](https://github.com/ppy/osu/files/13541150/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/13541151/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/13541153/runtime.log)

**Comment by camelius** [comment]
I can confirm the same issue seen in multiple instances. I managed to FC a few beatmaps, but the end screen and leaderboard results show the max combo as one less than a full combo. The end result screen for the replay shows a full combo and even a different score.

// Result screen on the leaderboard
![image](https://github.com/ppy/osu/assets/10532980/d486dcd0-e5a1-4014-bfb7-89f78965e314)

// Result screen after the replay
![image](https://github.com/ppy/osu/assets/10532980/5128630b-9453-4af7-8d00-b2de7785eaed)

[Zetamyte playing Reol - No title (VINXIS) [Light Insane] (2023-12-03_18-28).osr.txt](https://github.com/ppy/osu/files/13541462/Zetamyte.playing.Reol.-.No.title.VINXIS.Light.Insane.2023-12-03_18-28.osr.txt)
