### ISSUE TITLE
by default, Taiko base SV is not 1.40

### ISSUE THREAD

**Issue by SherlockWh0** [ppy/osu#25674]
### Type

Game behaviour

### Bug description

When I make maps in osu!(lazer), I often notice the SV is very slow. When I open the .osu file in TextEdit, it shows either 0.7142857264499277 or 0.510204099010101. This is an issue when you add SV effects in lazer and have to adjust them on export.

### Screenshots or videos

Here is a .zip with 2 files with this issue:
[Archive.zip](https://github.com/ppy/osu/files/13551601/Archive.zip)

### Version

2023.1130.0

### Logs

[database.log](https://github.com/ppy/osu/files/13551550/database.log)
[input.log](https://github.com/ppy/osu/files/13551551/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13551552/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13551553/network.log)
[performance-draw.log](https://github.com/ppy/osu/files/13551555/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/13551556/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/13551557/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13551559/runtime.log)

**Comment by peppy** [comment]
Are you talking about the default being wrong when creating a new beatmap, compared to stable? Does setting the scroll speed in the timing panel to 1.4x fix this?

**Comment by peppy** [comment]
The weird thing is, we only apply this 1.4 thing to taiko, while in osu!stable it's the default for all rulesets in the editor, seemingly?

**Comment by SherlockWh0** [comment]
I don't really know, to be honest. I mainly use osu!lazer due to using MacOS.
