### ISSUE TITLE
slider break on repeat slider, but no judgement

### ISSUE THREAD

**Issue by ZythePDX** [ppy/osu#25690]
### Type

Game behaviour

### Bug description

you slider break on a repeat slider but it gives no judgement(100, 50, miss).
**this has only happened when I use the mod Strict Tracking**.
usually you would get a miss because ST but no.
check the video below for a example
I have no way to purposefully repeat this consistently or at all.
this is uncommon to occur but has happened to me multiple times before
sorry in advance for the bad footage.

### Screenshots or videos

https://github.com/ppy/osu/assets/50603224/b8f9aa7c-cac6-4011-be5c-734f916c20e0

### Version

Lazer 2023.1130.0

### Logs

[database.log](https://github.com/ppy/osu/files/13577741/database.log)
[input.log](https://github.com/ppy/osu/files/13577742/input.log)
[network.log](https://github.com/ppy/osu/files/13577743/network.log)
[performance.log](https://github.com/ppy/osu/files/13577745/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13577746/runtime.log)

**Comment by bdach** [comment]
I'm not even sure what I'm supposed to be looking for in the video.

Please provide a timestamp or something. Or a replay. Anything at all.

**Comment by ZythePDX** [comment]
https://github.com/ppy/osu/assets/50603224/40b1741e-69d4-44af-b9ed-95316f2c368b

sorry for the late response but what you are looking for is the repeat slider and how even when I slider broke it gave me no miss when ST will always give you a miss if you slider break.
sorry for the slow response and the sliderbreak is at 30 seconds of the replay
link to the replay 
https://mega.nz/file/1ehVWLDK#aoaAV-8bfBXcAWdQ6F0wK_Qqe3WhV44N5kkmyqLJ3wE

**Comment by mysteGH** [comment]
OP is talking about the hit results at the top of the screen, His gameplay screen had displayed a "miss" due to the sliderbreak, but the miss was not counted. 

this isn't technically a bug since sliderbreaks don't show up on the end screen either (the same in stable), but for some players maybe an optional "sb" counter could help clear confusion.
