### ISSUE TITLE
Current ruleset selection underline is not masked away when scrolled

### ISSUE THREAD

**Issue by Guanran928** [ppy/osu#25696]
### Type

Other

### Bug description

1. Scroll on game mode selection buttons
(I have no idea how to name it, just see the video below)

### Screenshots or videos

https://github.com/ppy/osu/assets/68757440/4d24b0ed-442d-4a7d-8bcb-5daf2af7e88f

### Version

2023.1130.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13596718/database.log)
[input.log](https://github.com/ppy/osu/files/13596719/input.log)
[network.log](https://github.com/ppy/osu/files/13596720/network.log)
[performance.log](https://github.com/ppy/osu/files/13596721/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13596723/runtime.log)

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu/pull/26168.
