### ISSUE TITLE
Total Hits do not increase with Play Count if play is retried on Lazer client

### ISSUE THREAD

**Issue by cyreu** [ppy/osu#25701]
### Type

Game behaviour

### Bug description

Noticed this issue when I spotted an unexplained drop in my average hits per play (see screenshot of table).

All other stats on profile behave as expected - play time, play count and total score responds to plays that are retried but total hits remain unchanged unless the play submits and goes to the results screen.

### Screenshots or videos

Original play count and total hits:
![Before Play](https://github.com/ppy/osu/assets/153249437/99406e8e-a650-4f1e-ab36-4ffca6e77dee)

Play count and total hits after retrying:
![After Retry](https://github.com/ppy/osu/assets/153249437/e6c9ebb5-8c73-46a0-8b69-20043c42331e)

Play count and total hits after then submitting a score:
![After Submission](https://github.com/ppy/osu/assets/153249437/049b8d3d-03fe-4f6b-bab0-23fbc3607e35)

Table tracking personal hits per play every 250 plays, suggesting issue arose when [Lazer 2023.1114.0] was released:
![Hits Per Play Table](https://github.com/ppy/osu/assets/153249437/1fa6b292-8d33-444e-8797-66c6421e3dc0)

### Version

Lazer 2023.1130.0

### Logs

[database.log](https://github.com/ppy/osu/files/13608258/database.log)
[input.log](https://github.com/ppy/osu/files/13608259/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13608260/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13608261/network.log)
[performance.log](https://github.com/ppy/osu/files/13608262/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/13608263/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/13608264/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/13608265/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/13608266/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/13608267/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13608268/updater.log)

**Comment by peppy** [comment]
From your screenshots, it looks like total score also didn't increase?

**Comment by peppy** [comment]
Fixed both via https://github.com/peppy/osu-queue-score-statistics/commit/90c4e832381986bd045ce50bc6e2a978d56d6b9e.
