### ISSUE TITLE
The game is crashing, when importing the beatmap that already exists 

### ISSUE THREAD

**Issue by thenotsosh** [ppy/osu#25718]
### Type

Crash to desktop

### Bug description

As the title stands, when importing the map that you have second time, or imagine the scenario : someone helped you with mapping, and you import the beatmap: the game just starts crashing almost immediately when entering the song select.

### Screenshots or videos

https://github.com/ppy/osu/assets/70341224/aa70e04b-d36e-461a-9357-ea1097e98b5d

### Version

2023.1130.0

### Logs

i can’t get logs, because i can’t connect my iPad to my PC, maybe try recreate the bug on Windows and send logs there or in Discord

**Comment by bdach** [comment]
Cannot reproduce. Downloaded same map twice, imported it once and then once again, no crash.

Please upload the logs or provide a better reproduction scenario.

**Comment by tybug** [comment]
Thanks for the report, but I'm going to close as we can't reproduce this issue without more information. If you can provide more information or a reliable reproduction, we'll look at reopening this issue!
