### ISSUE TITLE
Black screen crash

### ISSUE THREAD

**Issue by madser123** [ppy/osu#2571]
Hi.

So i've been able to start the osu!lazer before (i tried about 3 months back). But now it crashes instantly. I can't really tell you anything about why it happens. It also happened to me a couple of releases back, but i didn't bother to state the issue. I'm thinking its some hardware incapability but i'm not sure.

**My system:**
_(I'm running this on a laptop. And the program is running from my SSD):_

OS: Windows 10 Home 64-Bit
CPU: Intel Core i7-6700HQ 2.60GHz (Skylake 14nm)
RAM: 8GB DDR4 (No model specified)
MB: ASUSTeK COMPUTER INC. G752VT
GPU: 3071MB NVIDIA GeForce GTX 970M (ASUSTeK Computer Inc.)
HDD: 931GB Hitachi HGST HTS721010A9E630 (SATA)
SSD: 119 NVMe SAMSUNG MZVLV128 (RAID)
SOUND: Realtek High Definition Audio (Can't seem to find any model or version)

Hope you can help (Or that i'm helping by posting this). I love to see the cutting edge of OSU!

Picture of the issue is attached.
**The error-box translates to:** "osu! has stopped working. A problem caused the program to stop working correctly. Windows will shut down the program and notify you if a solution is found. **Button:** Shut down program."
![udklip](https://user-images.githubusercontent.com/36743573/40164958-2ed62504-59bb-11e8-8baa-7a098f6a52a8.PNG)

EDIT: Attatched the runtime.log
[runtime.log](https://github.com/ppy/osu/files/2012718/runtime.log)

Keep up the awesome work 👍 
- Mads

**Comment by madser123** [comment]
@Aergwyn I attatched the log in the main post

**Comment by madser123** [comment]
@Aergwyn How/where do i delete the database?

**Comment by Aergwyn** [comment]
It should be in the `%appdata%/osu` iirc. I think it's even called lazer.db or something?

**Comment by Az3220** [comment]
how i can fix the same issue?
i already did everything you guys said but no one works.
pls help

**Comment by Aergwyn** [comment]
@madser123 any news on this?

**Comment by madser123** [comment]
@Aergwyn Sorry. Haven't had any time to check up on this. Deleting every ".db" file worked. it starts up and runs as its supposed to. Thank you for the help.
