### ISSUE TITLE
Lazer autoplay misses where stable autoplay does not.

### ISSUE THREAD

**Issue by AkiraMorilas** [ppy/osu#25724]
### Type

Game behaviour

### Bug description

As per title.
The mania beatmap I randomly noticed this in is the top diff of https://osu.ppy.sh/beatmapsets/2092660#mania/4386977 and it happens 7 minutes 42 seconds in, on lane 6(blue in the screnshot)

### Screenshots or videos

The note being dropped
![osu_2023-12-11_10-55-51](https://github.com/ppy/osu/assets/134231050/fb1843b6-bc6b-4e88-a6b4-51952fcfce02)
![osu_2023-12-11_10-57-10](https://github.com/ppy/osu/assets/134231050/9b559906-8c50-47f5-8402-36ff362064bd)
proof that it's not dropped in stable
![image](https://github.com/ppy/osu/assets/134231050/71c5bc78-c53f-47f3-bb40-5b400ec41a78)

### Version

2023.1130.0.lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/13633802/runtime.log)
[performance.log](https://github.com/ppy/osu/files/13633804/performance.log)
[network.log](https://github.com/ppy/osu/files/13633807/network.log)
[input.log](https://github.com/ppy/osu/files/13633811/input.log)
[database.log](https://github.com/ppy/osu/files/13633813/database.log)

**Comment by PercyDan54** [comment]
The note being missed is a super short hold note
`281,192,466175,128,0,466175:0:0:0:0:`

And that causes a instant release due to calculateReleaseTime() using the note's end time without any delay

**Comment by bdach** [comment]
@PercyDan54 are you going to attempt to fix this?

**Comment by PercyDan54** [comment]
> @PercyDan54 are you going to attempt to fix this?

This is my proposed fix
```diff
@@ -87,15 +87,22 @@ private IEnumerable<IActionPoint> generateActionPoints()
         private double calculateReleaseTime(HitObject currentObject, HitObject? nextObject)
         {
             double endTime = currentObject.GetEndTime();
+            double releaseDelay = RELEASE_DELAY;
 
-            if (currentObject is HoldNote)
-                // hold note releases must be timed exactly.
-                return endTime;
+            if (currentObject is HoldNote hold)
+            {
+                if (hold.Duration > 0)
+                    // hold note releases must be timed exactly.
+                    return endTime;
+
+                // Special case for super short hold notes
+                releaseDelay = 1;
+            }
 
             bool canDelayKeyUpFully = nextObject == null ||
-                                      nextObject.StartTime > endTime + RELEASE_DELAY;
+                                      nextObject.StartTime > endTime + releaseDelay;
 
-            return endTime + (canDelayKeyUpFully ? RELEASE_DELAY : (nextObject.AsNonNull().StartTime - endTime) * 0.9);
+            return endTime + (canDelayKeyUpFully ? releaseDelay : (nextObject.AsNonNull().StartTime - endTime) * 0.9);
         }
```

**Comment by bdach** [comment]
I'm not sure what's with the insistence of falling out of the `if` condition for releases. I'd just put the special case entirely there, i.e.

```csharp
return hold.Duration > 0 ? endTime : endTime + 1;
```

If you're gonna PR, then with tests, please.

**Comment by PercyDan54** [comment]
> I'm not sure what's with the insistence of falling out of the `if` condition for releases. I'd just put the special case entirely there, i.e.
> 
> ```cs
> return hold.Duration > 0 ? endTime : endTime + 1;
> ```
> 
> If you're gonna PR, then with tests, please.

I was going with the mind that if there is a next note before 1ms (very unlike but who knows).

**Comment by bdach** [comment]
Sure. I guess I can live with what you have.
