### ISSUE TITLE
Possible to have a duplicate song entry when clicking "Update" then click "Restore all recently deleted beatmap".

### ISSUE THREAD

**Issue by Trung0246** [ppy/osu#25731]
### Type

Game behaviour

### Bug description

This requires the song have a local only difficulty. By creating this local only difficulty beforehand then perform the actions in the title, the duplicate will occur.

### Screenshots or videos

Probably not needed.

### Version

2023.1130.0

### Logs

Probably not needed.

**Comment by peppy** [comment]
Correct. You can avoid this by not doing that.

**Comment by Trung0246** [comment]
Interesting. Was not thinking this was intended behavior. I guess maybe have disclaimer about this somewhere.

**Comment by peppy** [comment]
There's no need for a disclaimer? When you update, it will duplicate and delete the old version. You might want this version back. You can restore it with the restore deleted.
