### ISSUE TITLE
Selecting another mod with HR enabled causes the mod to stack twice

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu#2575]
https://streamable.com/pufk7 - Slow video due to loading times.
The HR (and probably EZ) mod is stacked twice when selecting other mods

Steps to Replicate:
Load either a Standard or Catch map with HR enabled, this will increase CS to around 6-7.
Exit the map and enable another mod (eg NF or DT)
Load the same map again, the CS will now be 10

This was tested both with and without Exam's suggested changes

**Comment by peppy** [comment]
Regression due to changes to cloning behaviour of BeatmapInfo.
