### ISSUE TITLE
Slow performance in song selection menu and mod menu

### ISSUE THREAD

**Issue by P1zzaDaddy** [ppy/osu#25755]
### Type

Performance

### Bug description

Performance issues while scrolling in song selection menu or mod selection menu.
For mod selection menu, the FPS goes low when its popping up and when I scroll or select some mod.
I stumbled upon this issue what I assume few updates or several updates ago as before there was no performance losses.

### Screenshots or videos

https://github.com/ppy/osu/assets/153810028/6d6b37b7-5c24-4460-ad69-7a11907221d7

### Version

2023.1130.0

### Logs

[database.log](https://github.com/ppy/osu/files/13670723/database.log)
[input.log](https://github.com/ppy/osu/files/13670725/input.log)
[network.log](https://github.com/ppy/osu/files/13670726/network.log)
[performance.log](https://github.com/ppy/osu/files/13670727/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13670728/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13670729/updater.log)

**Comment by peppy** [comment]
If possible could you try older releases and see which build causes the issue for you?

You can download previous releases from https://github.com/ppy/osu/releases (note that after you install, it will auto-update to the latest release, so you'll have to test without restarting).

**Comment by P1zzaDaddy** [comment]
[2023.326.0](https://github.com/ppy/osu/releases/tag/2023.326.0)
Is the build where the issues start. Previous builds from that version works flawlessly

**Comment by bdach** [comment]
If you switch renderer in settings to `OpenGL (legacy)`, do you get better performance?

**Comment by P1zzaDaddy** [comment]
Switch renderer to `OpenGL (legacy)` fixes the performance issues.

**Comment by peppy** [comment]
@smoogipoo might be one for you to investigate further when we have bandwidth..

**Comment by longnguyen2004** [comment]
Quick question: What's your driver version?

**Comment by P1zzaDaddy** [comment]
> Quick question: What's your driver version?
23.11.1

**Comment by smoogipoo** [comment]
Sounds super weird - this GPU should handle perfectly fine - we regularly test on a RX 5500XT.

If there are no driver updates available, can you make sure the GPU's running in PCI-E x16 mode? You could check this either by using GPU-Z, or by running the following powershell (`.ps1`) script:

```pwsh
# Get all devices related to PCI BUS
$pciStats = (Get-WMIObject Win32_Bus -Filter 'DeviceID like "PCI%"').GetRelated('Win32_PnPEntity') |
  foreach {
    # request connection properties from wmi
    [pscustomobject][ordered]@{
      Name = $_.Name
      ExpressSpecVersion=$_.GetDeviceProperties('DEVPKEY_PciDevice_ExpressSpecVersion').deviceProperties.data
      MaxLinkSpeed      =$_.GetDeviceProperties('DEVPKEY_PciDevice_MaxLinkSpeed'      ).deviceProperties.data
      MaxLinkWidth      =$_.GetDeviceProperties('DEVPKEY_PciDevice_MaxLinkWidth'      ).deviceProperties.data
      CurrentLinkSpeed  =$_.GetDeviceProperties('DEVPKEY_PciDevice_CurrentLinkSpeed'  ).deviceProperties.data
      CurrentLinkWidth  =$_.GetDeviceProperties('DEVPKEY_PciDevice_CurrentLinkWidth'  ).deviceProperties.data
    } |
    # only keep devices with PCI connections
    Where MaxLinkSpeed
  }
$pciStats | Format-Table -AutoSize

[System.Console]::WriteLine("Press any key to exit.");
[System.Console]::ReadKey();
```

**Comment by P1zzaDaddy** [comment]
GPU is running in PCI-E 4.0 x16 mode.
There was driver update available, which caused me issues related to other things (mainly issues in Vulkan based applications) so I had to rollback.
![Screenshot_9](https://github.com/ppy/osu/assets/153810028/9f731e96-23cc-49e3-83e9-89d9a4b05f8e)

I've been on RX 6700 XT for quite some time and I did not notice any major performance drops in menus.
I don't know if it's any use but I did go through "major" change for my PC in general (CPU and motherboard upgrade) which after I noticed this performance loss but I dunno if I could pin the issue on that.

**Comment by P1zzaDaddy** [comment]
Did a bit of testing on my own: 
I swapped my RX 6700 XT back to RX 5600 XT and I have no issues there, swapped it back to RX 6700 XT and issue is there.
I reinstalled drivers between swappings.

**Comment by smoogipoo** [comment]
You shouldn't need to reinstall drivers - did you install the same driver for both?

**Comment by P1zzaDaddy** [comment]
Yes, both of the times were 23.11.1 version drivers.

**Comment by bdach** [comment]
would rather spend that time into making vulkan work via veldrid than adding another translation layer

**Comment by peppy** [comment]
This is all very concerning. The amount of users switching to opengl / other because of "isolated" performance issues means we must be doing something very wrong. But fixing this is going to be hard for as long as we can't reproduce.

**Comment by P1zzaDaddy** [comment]
I dunno if its worth giving an update to this issue or not but after upgrading my GPU, the issue has vanished.
