### ISSUE TITLE
Insane stuttering in song select on master

### ISSUE THREAD

**Issue by Flamiii** [ppy/osu#25767]
### Type

Performance

### Bug description

I wanted to test out the recent changes made to osu!(lazer) on master, but when I got to song select, there was an insane level of stuttering and cursor skipping happening for some reason, and it's very clearly a problem. This kind of stuttering does not occur on the latest release (2023.1130.0).

### Screenshots or videos

2023.1130.0 version of osu!(lazer):

https://github.com/ppy/osu/assets/74088315/6251cb95-8012-4968-8a3a-04801d8b5872

master:

https://github.com/ppy/osu/assets/74088315/f180a4a6-04e8-43f7-a351-759d15538eaf

### Version

master

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13679363/compressed-logs.zip)

**Comment by Flamiii** [comment]
Okay, it went away so it seems like it was some sort of initial processing of scores because of the new scoring system or something along those lines. Gonna close this, although maybe a prompt signifying that is happening would be nice.

**Comment by GerritPlehn** [comment]
Had the same issue in the newest release, I noticed my install disk was under a relatively heavy write load for a few minutes when in song select. That would support your hypothesis of some initial processing of scores or maps.
Agree that a notification would have been appreciated.

**Comment by peppy** [comment]
A fix has been deployed for this.
