### ISSUE TITLE
Dropdowns aren't correctly isolating / blocking key bindings

### ISSUE THREAD

**Issue by peppy** [ppy/osu#25769]
### Discussed in https://github.com/ppy/osu/discussions/25766

<div type='discussions-op-text'>

<sup>Originally posted by **Loreos7** December 15, 2023</sup>

https://github.com/ppy/osu/assets/86934170/efb2c290-d733-46e6-bc33-9ebce52413f4

Even default `Space` binding.</div>

**Comment by Joehuu** [comment]
Another case: https://github.com/ppy/osu/discussions/27914
