### ISSUE TITLE
Object dimming not correctly applied to sliders

### ISSUE THREAD

**Issue by isakvik** [ppy/osu#25761]
### Type

Cosmetic

### Bug description

Not an extension of #25745, but related to some idiosyncratic behavior noted by me [here](https://github.com/ppy/osu/discussions/25745#discussioncomment-7839229).

Three things of note:
- For the first few seconds of a map, sliderend hitcircles + overlay are not dimmed. 
- After playing a few seconds of a map, sliderheads appear darker than other game objects for the duration from fadein to object dimming is removed. The excessive dim is at ~56% of full color, about the level of what you'd see if you applied a 25% dim twice. In the video, visible on sliderheads from 0:05.400 onwards.
- Sliderticks are not dimmed along with the rest of the slider. This does, however, match stable behavior and might be intended.

The dimming can be forced to apply selectively in the first seconds of the map the editor, but not sure about the mechanics of it there. Scrolling past the objects from early to late and then scrolling back would usually make sliderheads appear correct, but then moving an object would make them incorrect again.

Screenshot depicts an undimmed circle, a dimmed circle, a correctly dimmed slider and an incorrectly dimmed sliderhead. Video depicts the first section of Lily - Scarlet Rose [0108 style] with kiai removed.

Video and screenshot should be viewed at low gamma settings as the discrepancies are pretty subtle.

Reproducible on all skins I've tried, including defaults.

### Screenshots or videos

![osu_2023-12-14_17-54-00](https://github.com/ppy/osu/assets/11044829/fc0d0358-1dc2-4e22-a4f7-a872c5775647)

https://github.com/ppy/osu/assets/11044829/56c38970-7770-456a-83d7-d982b16f3eac

### Version

2023.1130.0

### Logs

[input.log](https://github.com/ppy/osu/files/13676640/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13676641/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13676642/network.log)
[performance.log](https://github.com/ppy/osu/files/13676643/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13676644/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13676645/updater.log)
[database.log](https://github.com/ppy/osu/files/13676647/database.log)

**Comment by peppy** [comment]
I'm having trouble understanding why the editor is involved here. Editor should match gameplay 1:1 (it runs the same code), so if possible could you please keep this focused on gameplay and not involve the editor?

**Comment by isakvik** [comment]
The editor was just my testbed for figuring out why it doesn't apply during the first few seconds of a map. Like you said, the editor runs the same code for objects, so it's not important to look specifically at it here, but there's some weird temporal behavior to this issue which I can't seem to nail down without diving into the code (my best guess is that there's some handling for the intro of a map where dimming is applied, and there's a bug in that).
