### ISSUE TITLE
When holding esc to quit the game, pressing 1 should skip the fade and quit the game

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu#2576]
Old habits die hard, Pressing 1 while holding escape should skip the fading to black before exiting the game.
Just a quality of life thing everyone would appreciate

**Comment by peppy** [comment]
Disagree

**Comment by DudeMartin** [comment]
I just spam Escape and the game closes instantly for me.

**Comment by HoutarouOreki** [comment]
You can also press 'alt''F4' twice.
