### ISSUE TITLE
Osu sometimes reports itself as "My SDL application" on Linux

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#25783]
### Type

Cosmetic

### Bug description

In some places osu! is named "My SDL application" for example in Multiple Screens applet in KDE when showing that osu! enforces presentation mode. Also default Wayland icon is being used in such places

### Screenshots or videos

![obraz](https://github.com/ppy/osu/assets/32620809/d1296087-02ef-4c40-919b-0f68e00a0338)
![obraz](https://github.com/ppy/osu/assets/32620809/61fdb196-fe1e-4f70-87dd-5f617ff4bcf4)

### Version

2023.113.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/13691231/runtime.log)
[performance.log](https://github.com/ppy/osu/files/13691233/performance.log)
[network.log](https://github.com/ppy/osu/files/13691234/network.log)
[input.log](https://github.com/ppy/osu/files/13691235/input.log)
[database.log](https://github.com/ppy/osu/files/13691236/database.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu-framework/pull/5650 would fix it if it worked correctly.
