### ISSUE TITLE
Mismatch of max slider tick amount in multiplayer between players

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#25786]
### Type

Game behaviour

### Bug description

Max slider ticks were different between players in multiplayer

### Screenshots or videos

![osu_2023-12-16_07-15-12](https://github.com/ppy/osu/assets/58333920/9f604881-96db-433f-b834-9cf7114a5f6e)
![osu_2023-12-16_07-15-09](https://github.com/ppy/osu/assets/58333920/f51e8b0c-02b9-490d-beff-adeec5dfbce2)

### Version

2023.1130.0

### Logs

[shorter_runtime.log](https://github.com/ppy/osu/files/13691587/shorter_runtime.log)
[network.log](https://github.com/ppy/osu/files/13691588/network.log)

**Comment by bdach** [comment]
Will be fixed next release.
