### ISSUE TITLE
Fade music out on failing

### ISSUE THREAD

**Issue by carmonben** [ppy/osu#2579]
When you fail a map in release osu, the music fades out and slows down, in Lazer it does not
I would like to help implement this, but have hit a roadblock.

**Comment by carmonben** [comment]
my current code is 
`        private bool onFail()
        {
            if (Beatmap.Value.Mods.Value.OfType<IApplicableFailOverride>().Any(m => !m.AllowFail))
                return false;

            //var pitchAdjust = clock as IHasPitchAdjust;
            int i = 10;
            do
            {
                AdjustableAudioComponent.Frequency.value = 1 / i ;
                //adjustableClock.Rate = 1 / i ;
                System.Threading.Thread.Sleep(100 * i);
                i -- ;
            } while (i > 1);
           
            adjustableClock.Stop();

            HasFailed = true;
            failOverlay.Retries = RestartCount;
            failOverlay.Show();
            return true;
        }`

**Comment by Aergwyn** [comment]
You can get inspiration for that in mods that change the speed.
E.g. [DT mod](https://github.com/ppy/osu/blob/master/osu.Game/Rulesets/Mods/ModDoubleTime.cs)

**Comment by LovelyA72** [comment]
suggestion: check codes for night/daycore mod. It might help.

**Comment by peppy** [comment]
This should probably be left alone until we restructure the audio subsystems. The path forward is to make all audio components exist in the scene hierarchy, and use `Transform`s to handle these scenarios.

**Comment by carmonben** [comment]
as in Clock.Rate.Equals (1/i); ?

**Comment by carmonben** [comment]
Ok I'll look for something else to do in the meantime
