### ISSUE TITLE
In spectator mode, when the player fails (?) you can't leave with the Esc key

### ISSUE THREAD

**Issue by Zyfarok** [ppy/osu#25804]
### Type

Menu navigation behaviour

### Bug description

I was spectating a friend, and as he failed and stopped playing, I noticed that I was stuck on the fail screen.
Pressing Escape was not doing anything, and the only way to get unstuck was to press Alt+F4 (which brought me back to the main menu after saying no to the exit confirmation menu).

### Screenshots or videos

![osu_2023-12-17_22-02-36](https://github.com/ppy/osu/assets/10669609/ef7b3bb9-e4de-4c67-801f-d96318aee1f4)

### Version

2023.1130.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13697783/database.log)
[network.log](https://github.com/ppy/osu/files/13697784/network.log)
[performance.log](https://github.com/ppy/osu/files/13697785/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13697786/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13697787/updater.log)

**Comment by toadsworth-jr** [comment]
https://github.com/ppy/osu/issues/25763

**Comment by Zyfarok** [comment]
good catch, I only searched open issues, mybad.
