### ISSUE TITLE
After changing the "Random" keybind from default, 'Rewind' remains Shift-F2

### ISSUE THREAD

**Issue by dumbuz** [ppy/osu#25803]
### Type

Game behaviour

### Bug description

If you change your keybinds so that Song Select Random isn't `F2`, the keybind for rewinding remains to be `Shift` + `F2`
Because the rewind button is shown in place of random when shift is held, the rewind keybind should update to match the random keybind. Alternatively, a bindable keybind would be acceptable (and make this 'hidden' feature more accessible to players who don't know about it)

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/44739965/43b7f208-6ab9-49d5-98dd-9dcec50c24c8)

### Version

2023.1130.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/13697297/network.log)
[runtime.log](https://github.com/ppy/osu/files/13697298/runtime.log)
[performance.log](https://github.com/ppy/osu/files/13697299/performance.log)
[updater.log](https://github.com/ppy/osu/files/13697300/updater.log)
[input.log](https://github.com/ppy/osu/files/13697301/input.log)

**Comment by bdach** [comment]
> Alternatively, a bindable keybind would be acceptable (and make this 'hidden' feature more accessible to players who don't know about it)

![image](https://github.com/ppy/osu/assets/20418176/0ce07c5f-9638-4210-8102-e2ff6b73201a)
