### ISSUE TITLE
Cursor trail is made up of 12k polygons?

### ISSUE THREAD

**Issue by carmonben** [ppy/osu#2580]
Im not sure this is normal, but when i pull up RenderDoc it tells me that the cursor trail is made up of 12k triangles. is this expected and fine?
sliders are only made up of 200 triangles per curve (about)
![image](https://user-images.githubusercontent.com/26778421/40223512-29430468-5a38-11e8-9d5b-6b23b7f343ab.png)

**Comment by peppy** [comment]
Sounds about right.

**Comment by carmonben** [comment]
wont that be a pretty big drag on frametimes?

**Comment by peppy** [comment]
You could test this yourself.

**Comment by smoogipoo** [comment]
It's only 2048 small sprites all batched together, not really.

**Comment by Tom94** [comment]
12k triangles are a relatively small number compared to any remotely recent 3D game. osu! is mostly bound by the number of pixels to be filled in, and those are only a small number for the cursor trail.

**Comment by carmonben** [comment]
yes, but in standard im looking for sub .5ms frametimes, in lazer im lucky to get 5ms

**Comment by peppy** [comment]
Please test with and without to ensure this is an issue affecting your performance, and open an issue if you find an issue.
