### ISSUE TITLE
Music stops at the end of a multiplayer game, before reaching results

### ISSUE THREAD

**Issue by peppy** [ppy/osu#25807]
I don't recall if this is only the case in spectator or also for players, but it's very abrupt and feels super bad.

**Comment by bdach** [comment]
@peppy Do you recall the circumstances of this happening? I attempted to reproduce with a beatmap with a long outro and it seems to be playing fine as far as I can tell...

**Comment by peppy** [comment]
Here's an example:

https://github.com/ppy/osu/assets/191335/6809ab2a-bfc0-45f8-963d-ad19a947f9e3

- Spectate a multiplayer room
- Wait for results screen
- Music stops
