### ISSUE TITLE
Difficulty sort breaks when switching rulesets

### ISSUE THREAD

**Issue by DarnTwine** [ppy/osu#25820]
### Type

Game behaviour

### Bug description

The difficulty sort in the beatmap carousel breaks when switching rulesets; i.e. from osu!standard to osu!mania. It groups all difficulties of a particular mapset—and within a mapset, the difficulties seem to be sorted by difficulty name rather than star rating. Switching back to the original ruleset will display the original correctly sorted beatmap list.

Converted beatmaps retain their difficulty sort when switching rulesets—however it remains sorted according to the original ruleset and does not correctly sort by converted star rating.

### Screenshots or videos

Sorting without switching rulesets (correctly sorted):

![osu_2023-12-18_17-51-14](https://github.com/ppy/osu/assets/149099574/5c64a29d-be71-4068-baa4-1074123e26ff)

Sorting after switching rulesets (incorrectly sorted):

![osu_2023-12-18_17-51-30](https://github.com/ppy/osu/assets/149099574/cd79303d-1bf4-44a2-ba24-40bd2a479ad2)

Sorting after switching rulesets with converted beatmaps (incorrectly sorted according to the new ruleset's star rating):

![osu_2023-12-18_18-17-24](https://github.com/ppy/osu/assets/149099574/d26ded13-8e86-4698-a372-316664ed1071)

### Version

2023.1218.0-lazer

### Logs

N/A

**Comment by NiceAesth** [comment]
Can reproduce without switching rulesets as well:

1. Search for a beatmap
2. Start playing the beatmap and exit
3. Clear the filter

The entire set will now be grouped and at the end of the carousel even if the current sort mode would place it elsewhere.

Video showcasing this issue: https://streamable.com/c1bfx0

**Comment by peppy** [comment]
>The issue is caused by:
https://github.com/peppy/osu/blob/8704dc3505a934f42f2259ec734bb072aa940282/osu.Game/Screens/Select/Carousel/CarouselGroup.cs#L90
> This check does not account for other cases where re-sorting would be necessary.
(e.g. SearchText being different, Ruleset being different)

I'm not sure if you were intending to be helpful here, but this explanation brings nothing to the table at all.

Changing the text being searched for should not affect sort order, as it only toggles the visible state of some items.
