### ISSUE TITLE
secondary key stops function in standard gameplay while importing from classic osu!

### ISSUE THREAD

**Issue by falsestatement** [ppy/osu#25844]
### Type

Game behaviour

### Bug description

I was trying to create the hard link talked about on the song import steps, however while playing osu! standard while the songs are importing, midway through the song, the secondary key stops working. The primary is still able to click the notes but the second key is completely unresponsive. After exiting out and picking a new song, it seems to work again, but later on in the song the same thing happens. It seems like the key is being detected as held down continuously when its not?

### Screenshots or videos

https://github.com/ppy/osu/assets/119913228/ca8477e9-a966-4da2-a012-ccac22b50b76

### Version

2023.1218.0

### Logs

[1702904198.performance.log](https://github.com/ppy/osu/files/13703996/1702904198.performance.log)
[1702904198.runtime.log](https://github.com/ppy/osu/files/13703997/1702904198.runtime.log)
[1702904198.updater.log](https://github.com/ppy/osu/files/13703998/1702904198.updater.log)
[1702904198.input.log](https://github.com/ppy/osu/files/13703999/1702904198.input.log)
[1702904198.network.log](https://github.com/ppy/osu/files/13704000/1702904198.network.log)

**Comment by Theighlin** [comment]
Are you playing on tablet? If so, you might have "disable mouse buttons during gameplay" off, if your pen is touching the tablet that is the same as holding down B1.

**Comment by falsestatement** [comment]
I am, but I drag the entire time the gameplay was shown, mouse buttons are disabled

**Comment by bdach** [comment]
> mouse buttons are disabled

are they though? from the video you attached in the OP:

![image](https://github.com/ppy/osu/assets/20418176/195f5c7b-6296-4275-affb-46ebe81d8bf6)

**Comment by Theighlin** [comment]
> I am, but I drag the entire time the gameplay was shown, mouse buttons are disabled

I can see for a split frane that you drag with your pen during loading, that will not trigger b1 to be pressed, but if you lift the pen and start dragging again during the map, it will block your b1 input.

**Comment by falsestatement** [comment]
oh i guess they're not... i could've sworn they were sry for being a dumbass haha.
