### ISSUE TITLE
osu!mania on mobile is very stretched when playing 

### ISSUE THREAD

**Issue by icohbad1** [ppy/osu#25852]
### Type

Crash to desktop

### Bug description

simply after the update the screen was stretched making it impossible for me to play without feeling strange with the skin, I even uninstalled the new version and reinstalled the old version to see if there was anything wrong with the settings but everything was normal.  My phone is galaxy a23

### Screenshots or videos

![Screenshot_20231218_112154](https://github.com/ppy/osu/assets/135658895/30fb7950-743b-4630-9fd7-cc04ad3232fe)
![Screenshot_20231218_112202](https://github.com/ppy/osu/assets/135658895/51cf2df9-9aa7-4882-8322-e792a3d3a92e)

### Version

2023.1130.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/13704942/logs.zip)

**Comment by bdach** [comment]
This was an intentional change to make mania playable on mobile devices. So if anything I'd like to think this would be a positive change.

Are you playing with an external keyboard?

**Comment by icohbad1** [comment]
Yes, I play with an external keyboard, but as the resolution is high I can't read the notes correctly, and decreasing the osu settings makes it extremely weird to play
