### ISSUE TITLE
osu!taiko slider velocities are rounded to 2 decimal points, causing patterns to look staggered and unnatural

### ISSUE THREAD

**Issue by mtz404** [ppy/osu#25862]
### Type

Game behaviour

### Bug description

In stable, you can input sv's up to 16 decimal places. Lazer has rounded all of these sv's to 2 decimal places, causing patterns that use continuous sv's for speed ups and slow downs to look staggered at times, making it uncomfortable to read.

Many taiko mappers have become accustomed to using external programs that will generate sv slow downs and speed ups, so a sizeable number of ranked taiko maps and world cup tournament maps have these 16 decimal point sv values. Because of this I believe this is a urgent issue.

**EDIT: After further investigation, I've found that this issue is most noticeable on maps with lower slider velocity, and maps with very gradual increase/decrease in slider velocity. This is because in both scenarios, you will be changing slider velocities every note by a small, but equal amount. When rounding these values to 2 decimal places, the changes in between slider velocities are no longer equal, causing the staggered effect seen below.**

### Screenshots or videos

The video provided shows a taiko world cup map which has this issue. It is hard to see the issue in real time so I recommend pausing to have a closer look. I have also provided a diagram of one pattern which hopefully better showcases this problem. Top players expect the smooth sv's seen in stable, so reading the disjointed one in lazer at the moment is very uncomfortable.

https://github.com/ppy/osu/assets/106291852/15ae7bce-abc3-4f9d-b513-d14a27ef3e87

![imageardtda3452345](https://github.com/ppy/osu/assets/106291852/107f202b-2c4d-4515-a81d-26e607da022b)

**EDIT: Adding more examples.**

Map 2: https://osu.ppy.sh/beatmapsets/1888593#taiko/3889528 at 01:07:401

https://github.com/ppy/osu/assets/106291852/ffbe3497-39f3-4897-93c2-036fc18d653c

Map 3: https://osu.ppy.sh/beatmapsets/1182264#taiko/2464974 at 02:32:385

https://github.com/ppy/osu/assets/106291852/670f8873-4138-4b73-a1a4-2bd864794b57

Map 4: https://osu.ppy.sh/beatmapsets/1311567#taiko/2718349 at 02:43:830

https://github.com/ppy/osu/assets/106291852/2a58a13d-5cdc-4b9f-a48c-89e46613b860

Map 5: https://osu.ppy.sh/beatmapsets/1684883#taiko/3442563 at 01:08:582 

This one is very hard to notice when not in gameplay so I recommend pausing. You should be able to notice very slight staggered notes, where 2 notes are closer together than one another. 

https://github.com/ppy/osu/assets/106291852/5960b563-2794-4b9a-9a51-1ea737605d59

### Version

2023.1218.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13706706/database.log)
[input.log](https://github.com/ppy/osu/files/13706707/input.log)
[performance.log](https://github.com/ppy/osu/files/13706708/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13706709/runtime.log)
[network.log](https://github.com/ppy/osu/files/13706710/network.log)
[1702919148.input.log](https://github.com/ppy/osu/files/13706711/1702919148.input.log)
[1702919148.performance.log](https://github.com/ppy/osu/files/13706712/1702919148.performance.log)
[1702919148.runtime.log](https://github.com/ppy/osu/files/13706713/1702919148.runtime.log)
[1702919148.network.log](https://github.com/ppy/osu/files/13706714/1702919148.network.log)

**Comment by bdach** [comment]
please link the beatmap

**Comment by mtz404** [comment]
https://osu.ppy.sh/beatmapsets/1734235#taiko/3544679

**Comment by peppy** [comment]
This probably needs to be addressed before scoring comes online if we're going to, as it will break replays and scores set.

**Comment by bdach** [comment]
> as it will break replays and scores set

I don't... think so? Slider velocity is purely visual. It does not impact timing of hits.

Mind you, I don't disagree that this is an *important* issue (in fact it keeps lingering on my todo list), but it's not _that_ critical.

**Comment by peppy** [comment]
Right, i'm used to SV affecting sliders.
