### ISSUE TITLE
Plays from stable showing as a large negative number score in local leaderboards

### ISSUE THREAD

**Issue by azu173** [ppy/osu#25860]
### Type

Game behaviour

### Bug description

Some plays that I have recently imported from the stable version appear at the bottom of the local leaderboard with a score of -9223372036854775808.

It happens on some maps, both old and recent plays. I have not been able to find a pattern whereby the scores show broken.

Score replays work fine and show the correct score on the results screen after the replay is finished.

### Screenshots or videos

![osu_2023-12-18_18-12-03](https://github.com/ppy/osu/assets/75030224/2c6ff4c3-adf9-48ae-9d9c-884a38afa369)

### Version

2023.1218.0-lazer

### Logs

[1702919495.performance.log](https://github.com/ppy/osu/files/13706586/1702919495.performance.log)
[1702919495.updater.log](https://github.com/ppy/osu/files/13706587/1702919495.updater.log)
[1702919495.input.log](https://github.com/ppy/osu/files/13706588/1702919495.input.log)
[1702919495.network.log](https://github.com/ppy/osu/files/13706589/1702919495.network.log)
[1702919495.runtime.log](https://github.com/ppy/osu/files/13706590/1702919495.runtime.log)
[1702919495.database.log](https://github.com/ppy/osu/files/13706591/1702919495.database.log)

**Comment by peppy** [comment]
Please attach the .osr files for the scores.

Also any reason you're attaching logs one by one rather than using the new zip feature?

**Comment by azu173** [comment]
[exports](https://drive.google.com/file/d/1MdVUZSFsMGj8iLc_j_AHEIugytA_B5ZY/view?usp=sharing)

I just dropped the log files in the box as the instructions said. Didn't know it was recommended to zip them before

**Comment by ImAPotatoDude** [comment]
Having the same issue
this screenshot file is just exemple (the osr file is harder to attach in git but when viewing the replay the score at the end is correct)

![image](https://github.com/ppy/osu/assets/62946407/9968cf6b-2788-4b78-8500-3073cf2abe6a)
[compressed-logs.zip](https://github.com/ppy/osu/files/13708540/compressed-logs.zip)

**Comment by bdach** [comment]
@ImAPotatoDude can you zip and attach the `.osr`? I have a prospective fix, just wanna make sure it covers your case too.

**Comment by ImAPotatoDude** [comment]
no worries the new update fixed it
![image](https://github.com/ppy/osu/assets/62946407/5702f6b5-f21e-4fa9-bff7-a22db6f4e97f)

**Comment by bdach** [comment]
Thanks for confirming.

**Comment by azu173** [comment]
New hotfix release fixed my scores as well 👍. Thank you
