### ISSUE TITLE
Sorting breaks after switching selected sort while searching

### ISSUE THREAD

**Issue by EthereaI** [ppy/osu#25866]
### Type

Crash to desktop

### Bug description

The selected sorting does not get applied after removing the search keyword(s).
Say, someone has artist sorting selected, searches something and then switches to the BPM sorting, and then removes their search keyword(s), the found beatmaps do not get sorted and all of the other beatmaps that re-appear do not get sorted either.

### Screenshots or videos

video too big for github, but it shows what is written above.
https://youtu.be/dcdY5jVwDXA

### Version

2023.1218.0-lazer

### Logs

N/A

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25820
