### ISSUE TITLE
Mod selection does not honor mod search box autofocus option

### ISSUE THREAD

**Issue by rodovia** [ppy/osu#25880]
### Type

Game behaviour

### Bug description

Despite the "Automatically focus search text in mod select" option being turned off, the mod selection screen will still open with its search box focused by default, breaking keyboard mod shortcuts

### Screenshots or videos

https://github.com/ppy/osu/assets/64744799/b73d009c-ccd0-4fd0-bd71-8cedae794c0c

### Version

2023.1218.1

### Logs

[database.log](https://github.com/ppy/osu/files/13709461/database.log)
[input.log](https://github.com/ppy/osu/files/13709462/input.log)
[performance.log](https://github.com/ppy/osu/files/13709463/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13709464/runtime.log)
[network.log](https://github.com/ppy/osu/files/13709466/network.log)

**Comment by peppy** [comment]
Will close this and track in #25857.
