### ISSUE TITLE
Song selection not consistent with "now playing" song on startup

### ISSUE THREAD

**Issue by ImJustAFish** [ppy/osu#25892]
### Type

Crash to desktop

### Bug description

Upon entering the song selection screen, one of three things happens: 
song selection matches "now playing" 
song selection defaults to lowest difficulty map
song selection plays random map

not a big priority but it is a small annoyance to be had. 

### Screenshots or videos

https://github.com/ppy/osu/assets/66386095/38547cb8-4e52-433a-8b2c-f1137c486bf0

### Version

2023.1218.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13712667/compressed-logs.zip)

**Comment by bdach** [comment]
This is by design.

Main menu doesn't filter beatmaps by ruleset when looking for something to play, but song select does. You have catch ruleset active and converts off, so if the beatmap chosen by the game at the start does not have a catch difficulty, song select will arbitrarily switch to something that fits the active filters.

**Comment by ImJustAFish** [comment]
> This is by design.
> 
> Main menu doesn't filter beatmaps by ruleset when looking for something to play, but song select does. You have catch ruleset active and converts off, so if the beatmap chosen by the game at the start does not have a catch difficulty, song select will arbitrarily switch to something that fits the active filters.

ah that makes sense, thanks!

**Comment by sourajit02** [comment]
> This is by design.

Is there a valid design reason to not have the user-set difficulty/ruleset filters apply for the main menu playlist? It is a bit disappointing to find a nice song on game startup, only to find that it is way outside the star range you have set.

**Comment by peppy** [comment]
If you see value in this, open a discussion. Depends how many others would like the behaviour to change.
