### ISSUE TITLE
Miss falls through stacked sliders

### ISSUE THREAD

**Issue by EdmundDong** [ppy/osu#25891]
### Type

Game behaviour

### Bug description

I missed a slider in the following replay and the miss seems to have fell through to the next slider even though there was only one keypress.

Keypress overlay shows 1 keypress, 2 misses judged.

Play was with no mod on lazer.

The closest issue I could find was #17675, but that seems to be with Classic mod so unsure if related.

### Screenshots or videos

Video (occurs at 0:03):
https://github.com/ppy/osu/assets/12579441/82c87bf8-8f74-476d-b14d-b4910729e328

[https://github-production-user-asset-6210df.s3.amazonaws.com/12579441/291508580-82c87bf8-8f74-476d-b14d-b4910729e328.mp4](https://github-production-user-asset-6210df.s3.amazonaws.com/12579441/291508580-82c87bf8-8f74-476d-b14d-b4910729e328.mp4)

Replay (occurs at 2:08, after break around 2/3):
[EDong playing C-Show - AImee feat. Aitsuki Nakuru (SMOKELIND) [gazimal_s x] (2023-12-18_23-42).zip](https://github.com/ppy/osu/files/13712276/EDong.playing.C-Show.-.AImee.feat.Aitsuki.Nakuru.SMOKELIND.gazimal_s.x.2023-12-18_23-42.zip)

### Version

2023.1218.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13712252/compressed-logs.zip)

**Comment by smoogipoo** [comment]
This is actually intended by the new notelock policy.

If the current time has passed object N's start time, then object N+1 can be hit instead which will cause object N to be missed immediately.
