### ISSUE TITLE
HP system is overly punishing in some cases

### ISSUE THREAD

**Issue by Givikap120** [ppy/osu#25897]
### Type

Game behaviour

### Bug description

Map have HP drain rate 3, and after getting few 100s HP don't recover even after getting many 300s in a row
Map link:
https://osu.ppy.sh/beatmapsets/1685879#osu/3445484
Replay link:
https://drive.google.com/file/d/1pHnlk8swz0wxvZ0Dgge-e0uNzYejc06_/view?usp=sharing

### Screenshots or videos

https://www.youtube.com/watch?v=mMIisiBOeKw

### Version

2023.1218.1

### Logs

Not needed

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25935
