### ISSUE TITLE
"For reference" feature in Taiko editor

### ISSUE THREAD

**Issue by Pachiru** [ppy/osu#2589]
In order to avoid issues about spread density, I suggest an idea of adding "For reference" feature in the Taiko editor as it's already existing in Mania. 

Since in Taiko, we don't mind about placement on the grid but just the hitsounds, I think we can still allow some space to this feature by reducing a bit the grid size for Taiko editor.

**Comment by peppy** [comment]
All editor features will be implemented for all rulesets.
