### ISSUE TITLE
Why do I need to search for mods..?

### ISSUE THREAD

**Issue by Dan4ik2021** [ppy/osu#25908]
### Type

Other

### Bug description

I want to use the hotkeys to select mods, but when I open the mods panel and press the selection key, I start searching and not selecting a mod.. I need to start by pressing tab, and then select the mod with a hotkey. Who needs to search?

> Congratulation for 500 release

### Version

2023.1218.1 | 2023.1218.0

### Logs

Logs are not needed here

**Comment by peppy** [comment]
Open settings, search for "mods", uncheck search by default.

![2023-12-20 00 46 48@2x](https://github.com/ppy/osu/assets/191335/70d0de8a-68c4-4697-bce9-21e1a9345892)

Also please don't make issues without reading what you should make issues for. You completely ignored everything.
