### ISSUE TITLE
Dropdowns change color unexpectedly when disabled (or vice-versa)

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#25909]
### Type

Cosmetic

### Bug description

The best example is with the cursor confinement option, which is disabled in fullscreen, as you can see from the video below. Notice how it also changes after hovering it.

### Screenshots or videos

https://github.com/ppy/osu/assets/43073074/07321979-68e6-486a-b411-3749bf14e394

### Version

2023.1218.1-lazer

### Logs

N/A

**Comment by bdach** [comment]
cc @frenzibyte
