### ISSUE TITLE
Weird sound plays the first time a beatmap is opened from song select

### ISSUE THREAD

**Issue by ikkue** [ppy/osu#25902]
### Type

Game behaviour

### Bug description

When opening a beatmap for the first time from the song select, as in it wasn't a retry, a weird sound effect plays as shown and can be heard in the video attached. The sound effect, as far as I can tell, is the same one as when a beatmap finishes updating and imported. I did update 3 beatmaps before this started to happen, so that might be related.

### Screenshots or videos

https://drive.google.com/file/d/1NM9r7h3oePuu3SNLRBzVdXFQ8a2zIbQL/view?usp=sharing

### Version

2023.1218.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13715181/compressed-logs.zip)

**Comment by ikkue** [comment]
> Duplicate of #25875?

Maybe! I recognise it as the "beatmap imported after updating" sound though, and this did happen after updating three maps in a row.

**Comment by bdach** [comment]
Presentation sounds pretty much the same, so closing as duplicate.
