### ISSUE TITLE
All channels in "Add more channels" submenu show 0 current users chatting

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#25901]
### Type

Game behaviour

### Bug description

In Lazer, Just navigate to Chat and Add more channels

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/82095491/85415070-1ada-41f0-99bf-30ecdce3aef7)

### Version

2023.1218.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13714993/compressed-logs.zip)

**Comment by RBQcat** [comment]
https://github.com/ppy/osu/issues/5327
