### ISSUE TITLE
Restarting maps with Hard Rock on keeps making circle size smaller.

### ISSUE THREAD

**Issue by DudeMartin** [ppy/osu#2591]
When retrying maps with Hard Rock on, the circle size gets smaller after every retry. Turning off Hard Rock and replaying the *same map* with no mods still retains the small circle size.

It looks like the mod is being reapplied to the beatmap every time it is replayed, because the drain, approach rate, and accuracy also keep increasing.

**Comment by Xinnoh** [comment]
There was a fix for this yesterday with #2582 , just double check your client is up to date

**Comment by DudeMartin** [comment]
I'm using the latest release. I'll just have to wait until that fix is worked into the next release.
