### ISSUE TITLE
strict tracking, causes misses on sliders that, if i had to guess, are thinking the wrong inputs are theirs, not even auto can avoid these

### ISSUE THREAD

**Issue by gamefalor** [ppy/osu#25915]
### Type

Game behaviour

### Bug description

Problem details: strict tracking, causes misses on sliders that, if i had to guess, are thinking the wrong inputs are theirs, not even auto can avoid these

Video or screenshot showing the problem:
https://cdn.discordapp.com/attachments/1078376655170580562/1186744097852104785/TONDEMO_WONDERZ.mp4?ex=65945c91&is=6581e791&hm=64f0dca9578db8b550aab3d09705765d8880f06defafb5bb6cfb7b37d9cc484d&
https://osu.ppy.sh/beatmapsets/1547596#osu/3216926

https://cdn.discordapp.com/attachments/1078376655170580562/1186744108404969562/aiueoon.mp4?ex=65945c94&is=6581e794&hm=81ab922f811f7485a9f11db904d7899a06128a397fbabbf83a68fbf9fe51642e&
https://osu.ppy.sh/beatmapsets/1029473#osu/2935284

osu! version: 2023.1220-lazer

### Screenshots or videos

doesnt let me paste them, theyre in the bug description

### Version

2023.1220-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13719512/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25816
