### ISSUE TITLE
osu!taiko slider velocity doesn't match stable

### ISSUE THREAD

**Issue by Arityle** [ppy/osu#25919]
### Type

Gameplay Issue

### Bug description

When playing lazer I noticed that the general sv of notes is faster than stable at the same sv rate, this can become extremely noticeable on mods like HR, which significantly increase sv to begin with. The reason this is a big issue is because this allows maps to become a lot more harder or easier on lazer depending on the type of player. 

### Screenshots or videos

For the gameplay I used the same resolution (1440x900) and used the same mod combination. (HR,A) map link: https://osu.ppy.sh/beatmapsets/2010165#taiko/4182585 Sorry if the video isn't edited the best.

https://github.com/ppy/osu/assets/154377322/1cefe09c-8a87-44c7-910d-220b96925b13

### Version

2023.1220.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13720324/compressed-logs.zip)

**Comment by bdach** [comment]
Can you re-test with classic mod enabled?

**Comment by Arityle** [comment]
sure!

**Comment by Arityle** [comment]
The classic mod appears to have changed nothing 

https://github.com/ppy/osu/assets/154377322/6d80574a-e998-4cf7-aa96-129ceb5bf602

**Comment by Ratchet0203** [comment]
I think it's worth pointing out that Vunyunt already made a pull request about this last year which solves the inaccuracies: https://github.com/ppy/osu/pull/19604.

**Comment by bdach** [comment]
@Ratchet0203 that pull is touching SV on HR, so unless you want to tell me that nomod matches correctly and this is a HR-only concern, i don't think so

**Comment by Ratchet0203** [comment]
@bdach https://github.com/ppy/osu/pull/19604 mentions NM/HD/HR/HDHR, not just HR. It also has videos at various resolutions demonstrating that lazer and stable match in all of those mod combos.

**Comment by bdach** [comment]
> Classic + NM now fades the note in when gameplay aspect ratio is wider than 2:1

i do not see SV mentioned here?

**Comment by Ratchet0203** [comment]
SV isn't mentioned, no, but in those videos, the notes all move at the correct speed, while currently in lazer they don't. Whatever Vunyunt did in his code made the SV correct as well. Maybe that PR wouldn't work now because of other changes since that I don't know about, but I wanted to bring it up in the hopes that it would save people work. Apologies if I'm mistaken.

**Comment by bdach** [comment]
yeah well the link to the PR is appreciated but unless you've gone and tested please don't make claims about whether it fixes or doesn't fix the issue until it's properly investigated.
