### ISSUE TITLE
Skin Editor glitch with live play

### ISSUE THREAD

**Issue by Bokcho** [ppy/osu#25926]
### Type

Game behaviour

### Bug description

In lazer's skin editor there's a replay playing in the background to show you how your skin will look in real time.
However, if you let this replay finish, it will consistently play in reverse at an insane rate to return to the songs preview time.
You can re-create this issue by going into the skin editor and watching a replay, as soon as it finishes you will get the result as below. Not game breaking, but very immersion breaking. Also note that the Components on the left will flash rapidly as well. It is also not exclusive to the standard gamemode either, appears to work with any gamemode

### Screenshots or videos

https://medal.tv/games/osu/clips/1K7RBRVWAVR6z8/d1337JHxkGbf?invite=cr-MSwxS3MsNzczMjU4NDMs
https://medal.tv/games/osu/clips/1K860Mfnjrzo1e/d1337ItScVGR?invite=cr-MSw1bkosNzczMjU4NDMs
https://medal.tv/games/osu/clips/1K8d3bLeXmtmxv/d1337osPaSQm?invite=cr-MSwyUXksNzczMjU4NDMs

### Version

2023.1220.0-lazer

### Logs

[Exported log](https://github.com/ppy/osu/files/13721855/compressed-logs.zip)

**Comment by Bokcho** [comment]
Sorry for using medal to do this, didn't think I could submit raw .mp4 files to GitHub lol

**Comment by bdach** [comment]
This is intentional for now, as if this didn't happen, you'd be moved to results screen while in the middle of editing the skin.
