### ISSUE TITLE
score recalculation does not affect new mod's score multiplier

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu#25925]
### Type

Game behaviour

### Bug description

This score has more than >800k, since synesthesia(0.8x) has affected in new. I'm guessing re-calculating score does not affect new mod rating changes.
autoplay with mod:
![Screenshot from 2023-12-20 10-01-36](https://github.com/ppy/osu/assets/37479424/408b75bd-b087-4efb-a94d-0a644cd135ac)
my score:
![Screenshot from 2023-12-20 10-01-41](https://github.com/ppy/osu/assets/37479424/65a617d5-d215-40b4-98f6-d67c3874cd3b)
my score with replay-reviewed:
![Screenshot from 2023-12-20 10-02-45](https://github.com/ppy/osu/assets/37479424/c19268be-850e-46d7-816d-d26739adefcc)

### Version

2023.1220.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/13721745/runtime.log)
[network.log](https://github.com/ppy/osu/files/13721746/network.log)
[performance.log](https://github.com/ppy/osu/files/13721747/performance.log)
[input.log](https://github.com/ppy/osu/files/13721748/input.log)
[database.log](https://github.com/ppy/osu/files/13721749/database.log)

**Comment by bdach** [comment]
> I'm guessing re-calculating score does not affect new mod rating changes

It currently does not, correct. The recalculation from latest release was more targeted at imported stable scores.

We're not likely to be changing this state of things before going live with ranked play, based on [a conversation I had](https://discord.com/channels/188630481301012481/188630652340404224/1186705332542644236) with @peppy on scoring yesterday in discord. Unless I misunderstood.

**Comment by peppy** [comment]
I don't thing we have the manpower to support migration of older scores, at least not short-term.
