### ISSUE TITLE
A sound that shouldn't be there is audible only when selecting a song from song select

### ISSUE THREAD

**Issue by Polyva** [ppy/osu#25920]
### Type

Other

### Bug description

As the title reads there is, what i assume to be, a menu sound effect audible whenever i select a song from song select. This sound does not occur when i restart the same song. This happens with every song across all game modes. This also happened on version 2023.1218.1-lazer (most likely on version 2023.1218.0-lazer too) and i know it did not happen on version 2023.1130.0-lazer.

### Screenshots or videos

https://github.com/ppy/osu/assets/115677736/aa1d88ba-ec5f-43f2-9872-9fdcd54e207a

### Version

2023.1220.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13720652/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25875
