### ISSUE TITLE
MIss without any reason

### ISSUE THREAD

**Issue by Yserille** [ppy/osu#25942]
### Type

Bug

### Bug description

So I'm tapping and aiming right but missing here is some exemple

(the red part on the trail is where i tapped)

![image](https://github.com/ppy/osu/assets/154394536/3f8c3dea-63cf-4c69-a460-dfec849ee8a0)
![image](https://github.com/ppy/osu/assets/154394536/25c0eeba-76f2-4718-b17d-66256a578f62)

https://github.com/ppy/osu/assets/154394536/5486ddf2-40a4-416f-bac7-0544be5d6b71

### Version

2023.1220.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13724756/compressed-logs.zip)

replay 
[Toblerone playing Alustrium - Hunted (ItsWinter) [A Monument to Silence] (2023-12-20_03-27).zip](https://github.com/ppy/osu/files/13724804/Toblerone.playing.Alustrium.-.Hunted.ItsWinter.A.Monument.to.Silence.2023-12-20_03-27.zip)

**Comment by bdach** [comment]
What is this even? Why are the screenshots from some external tool (which I'm not even sure if it's replicating lazer mechanics)?
