### ISSUE TITLE
Changing slider velocity will cause juicestream visually broken in osu!catch editor 

### ISSUE THREAD

**Issue by Sololiquy** [ppy/osu#25957]
### Type

Game behaviour

### Bug description

the juicestream will visually produce much big droplet when the slider velocity goes high.
Exit and reenter editor will visually turning back juicestream normal again.

### Screenshots or videos

https://github.com/ppy/osu/assets/77843814/58ba3553-84c9-4cf6-bb4f-4d0a77fe1e5f

### Version

2023.12.20.0-lazer

### Logs

-

**Comment by snalgae** [comment]
Ooh i just discovered that this is an earlier version of #28534 that I made and I didn't notice this one. This should be closed.
