### ISSUE TITLE
Mania key count in editor does not update after changing in Setup

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#25969]
### Type

Game behaviour

### Bug description

In a osu!Mania beatmap editor, after changing the key count slider in Setup, the key count in Compose still stays the same.

### Screenshots or videos

<img width="1280" alt="osu! Screenshot 2023 12 20 - 20 21 48 65" src="https://github.com/ppy/osu/assets/67008763/4f2841ab-2262-4948-a6db-b4f7df014023">
<img width="1280" alt="osu! Screenshot 2023 12 20 - 20 22 20 76" src="https://github.com/ppy/osu/assets/67008763/97705ba7-7121-4387-8051-84db992b74a6">

### Version

2023.1221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13731430/compressed-logs.zip)

**Comment by bdach** [comment]
tracked as https://github.com/ppy/osu/issues/17127

this will work if you save and re-enter editor.
