### ISSUE TITLE
Little osu! logo flashing in intro sequence

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#2597]
![qq](https://user-images.githubusercontent.com/27222621/40306190-0bb4038e-5cfe-11e8-83c2-489966e4fd59.png)
It's only for a frame or two but when starting up the game parts of the osu! logo that usually sits in the bottom right corner flash up before disappearing again.

**Comment by Aergwyn** [comment]
This is still happening in `Disclaimer`.

**Comment by peppy** [comment]
Not sure why this was reopened, @smoogipoo can you confirm?

**Comment by peppy** [comment]
Closing; opened #2814 as a follow-up for the cited remaining case.
