### ISSUE TITLE
Beatmap status displays incorrectly

### ISSUE THREAD

**Issue by EWReinE** [ppy/osu#25975]
### Type

Other

### Bug description

I found the bug purely coincidentally. I was just surfing through maps when I spotted a certain map had an incorrect ranked status. I don't know what caused it or if this has occurred to other maps. I checked a few of the other maps that are not under ranked status that I have downloaded and they displayed normally. I am aware that a similar issue opened by smoogipoo occurred in 2020 with regards to loved ranked maps and this issue could be similar to that issue. 

An additional detail about the map is that I downloaded the map when it was under the qualified status onto osu stable and ported it to osu lazer.

### Screenshots or videos

![osu_2023-12-20_20-18-53](https://github.com/ppy/osu/assets/106027517/c22736ac-9bc7-41dd-a717-35d345a6abb0)
![osu_2023-12-20_20-19-42](https://github.com/ppy/osu/assets/106027517/efc23b4f-28e3-4ce4-aebb-929aee69577f)

### Version

2023.1221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13732207/compressed-logs.zip)

**Comment by bdach** [comment]
Similar issue has been reported in https://github.com/ppy/osu/issues/23804, but this one is about qualified -> ranked.

**Comment by EWReinE** [comment]
Ah I'll close this issue then
