### ISSUE TITLE
Perfect mod permits dropped slider ends

### ISSUE THREAD

**Issue by DarnTwine** [ppy/osu#25978]
### Type

Game behaviour

### Bug description

The Perfect mod does not fail the player if they miss the tail of a slider. I discovered this while playing with the Relax mod, but it applies even when playing without it.

### Screenshots or videos

Linked replay: [replay.zip](https://github.com/ppy/osu/files/13732496/replay.zip)

![osu_2023-12-21_06-49-12](https://github.com/ppy/osu/assets/149099574/4de77e69-d0da-415d-91af-f93ae11c488c)

### Version

2023.1221.0-lazer

### Logs

N/A

**Comment by bdach** [comment]
Dropped slider ends do not cause accuracy to decrease, so this is currently by design.

https://github.com/ppy/osu/blob/b7cca788b5cc4da29e02627fdac2c69e45ac77c6/osu.Game/Rulesets/Mods/ModPerfect.cs#L30-L32

**Comment by bdach** [comment]
Actually now that I look at this again I'm not sure why this does what it does and I got lost after changing slider mechanics 5000 times. Requires more thorough investigation.
