### ISSUE TITLE
osu!mania replay yields a different score and judgements than gameplay

### ISSUE THREAD

**Issue by Paturages** [ppy/osu#25973]
### Type

Game behaviour

### Bug description

So I was having an osu!mania session and I forgot to take a screenshot of the detailed graphs at the end of my play. The play was the following 978K run:

![osu_2023-12-20_21-05-54](https://github.com/ppy/osu/assets/9801350/4e15922b-5c20-4039-9326-3f75d7884937)

I replayed the entire map to get the graph again, and was met with a different score with different judgements

![osu_2023-12-20_21-08-06](https://github.com/ppy/osu/assets/9801350/c9ec7c21-d63a-4734-b8d5-7ba5346b52cc)

Original score gotten through gameplay was: `978,857 | 1413/427/11/1/0/0`  
Score after replay is: `980,677 | 1433/409/9/1/0/0`

I suspect timing windows may be different between gameplay and replay, but I may be wrong and have no way of checking that myself.

[Beatmap in question](https://osu.ppy.sh/beatmapsets/701056#mania/2933919)  
[Replay file](https://github.com/ppy/osu/files/13732143/Guest.playing.Michael.Gray.-.The.Weekend.Jole.friday.feeling.2023-12-20_21-01.zip)

### Version

2023.1221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13732162/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/11311#issuecomment-1084933364
