### ISSUE TITLE
Slider tick/end misses shows full size Judegement on stable skins

### ISSUE THREAD

**Issue by Tunnelbliick** [ppy/osu#25987]
### Type

Cosmetic

### Bug description

Stable skins show a full sized miss for missed slider tick / slider end.

This leads to very distracting gameplay, aswell as thinking that you missed eventho you just missed a slider tick / end.
Especially on tech heavy maps or maps with very fast reverse sliders where you frequently can drop slider ends / ticks this is very confusing.

Id recommend making this a toggelable option aswell as it may not be wanted by everyone.

[Skin i used](https://osu.ppy.sh/community/forums/topics/1498493?n=1)

### Screenshots or videos

https://streamable.com/x4l1t9

### Version

2023.1221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13734466/compressed-logs.zip)

**Comment by NiceAesth** [comment]
This happens on skins which have miss sprites with very tall textures.

Left: skin that does not scale correctly
Right: skin that does
![](https://up.aesth.dev/A8g4EBWX.png)

**Comment by bdach** [comment]
nope the tallness of the sprite has no impact.

spot the actual issue:

https://github.com/ppy/osu/blob/7e9d12e1d2f928b8cd46b6d26c319d4b2991cb0a/osu.Game/Skinning/LegacyJudgementPieceOld.cs#L51-L63
