### ISSUE TITLE
The autopilot does not work as described in the latest update 2023.1221.0-Lazer

### ISSUE THREAD

**Issue by Misty-Owl** [ppy/osu#25988]
### Type

Game behaviour

### Bug description

Autopilot mode is incompatible with modes No Fail, Sudden Death, Perfect. But at the same time it can be failed.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/154484088/01a29db4-4404-4bb7-88ca-c948a9205516)
![image](https://github.com/ppy/osu/assets/154484088/617bf5e3-4dd2-4b52-bbc2-6d8469a789f8)
![image](https://github.com/ppy/osu/assets/154484088/af25ce3b-02f7-4419-b261-1b8fa6fac351)

### Version

2023.1221.0-Lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13734519/compressed-logs.zip)

**Comment by peppy** [comment]
already fixed, search first please.
