### ISSUE TITLE
Audio bug when headphones are getting plugged out and in again

### ISSUE THREAD

**Issue by grizzly0304** [ppy/osu#2598]
https://youtu.be/kleFc9o7q-s

sorry for the water mark and fairly low recording quality but the bug went down as followed:
I began porting my stable maps into lazer and while doing so I accidently pulled my headphones out. Then the music stopped playing but the sounds were still playing. I have no idea how this is a thing but I hope it helps.

**Comment by peppy** [comment]
We still have quite a bit of work to do on audio device changing (ppy/osu#1302 loosely related)
