### ISSUE TITLE
The result shown on leaderboard does not match with the gameplay after the new algorithm is set

### ISSUE THREAD

**Issue by akivn** [ppy/osu#25982]
### Type

Game Behaviour

### Bug description

The final result shown in the replay does not match with the leaderboard score.
Two sets of scores are shown for reference. Pic 1/2 as Example 1, and Pic 3/4 as Example 2.

### Screenshots or videos

![osu_2023-12-20_22-35-49](https://github.com/ppy/osu/assets/97215472/31a70433-072e-46cd-b6a7-816bfd894b53)
![osu_2023-12-20_22-35-55](https://github.com/ppy/osu/assets/97215472/423f0f43-10d2-47b9-9696-e9f769fdf392)
![osu_2023-12-20_22-39-36](https://github.com/ppy/osu/assets/97215472/28b97b20-23f5-4889-b95d-277ca1c7d20b)
![osu_2023-12-20_22-39-39](https://github.com/ppy/osu/assets/97215472/5df013f6-6af1-49be-8989-0ddf49e30d19)

### Version

2023.1221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13733168/compressed-logs.zip)

**Comment by peppy** [comment]
Please be patient.
