### ISSUE TITLE
Skin-Editor: incorrect StarRating attribute during gameplay, if mods that change difficulty are active

### ISSUE THREAD

**Issue by lexcelent** [ppy/osu#25980]
### Type

Cosmetic

### Bug description

**Expected**
StarRating attribute shows real Star Rating, even if you use Difficulty changing mods like HardRock, DoubleTime, HalfTime, Easy

**Actual**
StarRating attribute doesn't show real Star Rating, if you use Difficulty changing mods like HardRock, DoubleTime, HalfTime, Easy

**Steps to reproduce:**
1. In skin editor add a StarRating attribute in Gameplay section
2. Save
3. Add DoubleTime mod, look at StarRating in the Song Select section
4. Start the game, look at the StarRating attribute

### Screenshots or videos

![изображение](https://github.com/ppy/osu/assets/114250713/719af0f5-03a1-42aa-9833-0dbc3b7b004d)
![изображение](https://github.com/ppy/osu/assets/114250713/8cc00b75-d8df-4388-950f-8a70655d891c)

### Version

2023.1221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13732471/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21946
