### ISSUE TITLE
FPS locked to VSync while using Metal renderer on MacOS.

### ISSUE THREAD

**Issue by RealistikDash** [ppy/osu#25985]
### Type

Performance

### Bug description

When using the Metal renderer, the FPS of osu does not exceed the refresh rate (120fps) while specifically using the Metal renderer even with the unlimited FPS option. This is not the case on any of the OpenGL renderers, which are able to exceed 120fps with the same settings.

### Version

2023.1221

### Logs

[1703118437.runtime.log](https://github.com/ppy/osu/files/13733774/1703118437.runtime.log)
[1703118437.performance.log](https://github.com/ppy/osu/files/13733776/1703118437.performance.log)

All of the relevant log files from simply starting up the game using the Metal renderer.

**Comment by peppy** [comment]
This is intentional as we are using hardware locked frame sync.
