### ISSUE TITLE
Unpredictable behavior of orange cursor after pause when hovering a circle

### ISSUE THREAD

**Issue by aryu-ki** [ppy/osu#25984]
### Type

Game behaviour

### Bug description

I can't tell exactly what happens if you unpause game by clicking orange circle when hovering some note. It sometimes produces miss sound while NOT breaking combo, which is very, very distracting. Also, you can't tell if clicking orange dot will click the underlying note or not (do I have to press twice?). It ruined a lot of my plays, since I have to adjust my mouse from mouse drift using pause 

### Screenshots or videos

https://vimeo.com/896722590 - Using 0.5 playback speed, notice how I only click orange circle and it immediately misses as if I hit it too early 
https://vimeo.com/896723143 - Here, watch carefully. When I click orange circle, it registers an **early hit** on the UR bar at the right, and then I hit the same note perfectly and we don't even get to see a 100.
And there is also a behavior when it produces miss sound and probably even miss picture when hit like in first example, but I couldn't reproduce it

### Version

Lazer 2023.1221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13733658/compressed-logs.zip)

**Comment by iminlikewithyou** [comment]
it seems like a bug, maybe

in this clip i clicked on the orange cursor and held - and got a full combo
https://github.com/ppy/osu/assets/20297536/96881b42-13c4-4080-85a0-64d976bee2f9

in this one, i did the exact same thing - yet i got a "great" at the beginning, an instant miss, and then it continued to let me finish the slider
https://github.com/ppy/osu/assets/20297536/863e76e4-34e6-4435-ad64-e2477a6d2957

i will also say that i tried it around 10 times, and in 9/10 of them, the second outcome occured.

**Comment by iminlikewithyou** [comment]
this is related
https://github.com/ppy/osu/issues/25655

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/9658
