### ISSUE TITLE
Pausing the music using hotkey during the intro sequence makes the song play right after the intro sequence but from the middle of the song

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#25999]
### Type

Game behaviour

### Bug description

Sometimes I just want the game to start silently, so I click Pause Music hotkey during the intro sequence, but that pauses it only until the intro sequence is finished. Right after that, it will start playing again, from the middle of the song.

1. Have a hotkey for pausing music
2. Close Lazer
3. Open Lazer
4. Click the Pause Music hotkey during the intro sequence
5. Observe the issue

### Screenshots or videos

https://github.com/ppy/osu/assets/82095491/e27e296f-15e2-4cf1-a2a0-68ce1e9f8b4c

### Version

2023.1221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13739648/compressed-logs.zip)

**Comment by bdach** [comment]
If you wanna do that, use the mute shortcut (ctrl+f4).

We will likely be "fixing" this by disabling the pause hotkey during intro anyhow.
