### ISSUE TITLE
slider thickness, sliderfollow and circle difference from stable

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu#26000]
### Type

Game behaviour

### Bug description

I had feeling that lazer feels different from stable in terms of gameplay, so i decided to record side by side comparison.

_I used same skin and beatmap to see difference._

## Slider thickness
Here is video shows difference between stable and lazer
p.s. **Left** is lazer, **right** is stable

https://github.com/ppy/osu/assets/21735205/d6318638-07ac-4465-b58b-4d9faab3e8ed

## Sliderfollow expand
In stable scaling of the sliderfollow is smoother
p.s. **Left** is lazer, **right** is stable

https://github.com/ppy/osu/assets/21735205/a23ed191-e127-4730-99cd-b85d63ca1b1d

## Sliderfollow still holded
After you move your cursor away from slider, while still having key pressed, it wont expand slider like in stable
p.s. **Left** is lazer, **right** is stable

https://github.com/ppy/osu/assets/21735205/b8f1fe60-e07f-4c9e-8d37-b429496d286a

## Missing note
Missed note stay longer than in stable
p.s. **Left** is lazer, **right** is stable

https://github.com/ppy/osu/assets/21735205/17a165b6-dc22-46f9-b9f4-bea68a72a5be

## Sliderfollow dissappear on miss
If you getting miss on the slider, it'll expand sliderfollow, unlike stable where it will downscale. Which is less distracting
p.s. **Left** is lazer, **right** is stable

https://github.com/ppy/osu/assets/21735205/c0e6de82-53b3-4b91-8ae7-220b9e72348d

### Version

2023.1221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13739674/compressed-logs.zip)

**Comment by peppy** [comment]
> Missed note stay longer than in stable

intentional. you can use classic mod to restore this.

**Comment by Detze** [comment]
'Sliderfollow expand' has been fixed in #27288.

**Comment by Detze** [comment]
After #27382 the scenario in 'Sliderfollow dissappear on miss' should result in either TailBreak or End, and not Break, so the issue should be resolved.
