### ISSUE TITLE
Mod search blocking Hotkeys for selecting mods

### ISSUE THREAD

**Issue by Fabiano1337** [ppy/osu#26005]
### Type

Game behaviour

### Bug description

**Description**:
When opening the mod selection search bar is auto selected blocking hotkeys for mods

**Example**: 
1. Select a map
2. Press F1
3. Press F

**Expected behaviour**: DoubleTime should be selected but osu just searched for mods containing "F"

### Version

2023.1221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13742587/compressed-logs.zip)

**Comment by bdach** [comment]
Please disable "Automatically focus search text box in mod select" in settings to disable this behaviour.
