### ISSUE TITLE
Profile picture is expanded outside it's area.

### ISSUE THREAD

**Issue by ly-nld** [ppy/osu#26019]
### Type

Cosmetic

### Bug description

![afbeelding](https://github.com/ppy/osu/assets/38471793/9a3aced5-23c4-48c5-b137-3b8e60486340)
I tried recording a video to reproduce it, but this is the best way I can explain it:
1. Try logging into osu while completely logged out
2. The crucial step here I think; get prompted to verify your location/identity to Bancho
3. visit the URL to Bancho
4. if your profile picture is high resolution, you will get it larger than the intended size

I apologize for not having clear instructions, I currently do not know how to trigger a Bancho verification message myself. But if there is a way to trigger that, I can record it and hopefully reproduce the bug. I also apologize if this is the wrong repository, I saw different repos fro osu!stable so I thought this one was the right one. If not, please transfer this issue ^^

### Screenshots or videos

![スクリーンショット 2023-12-21 203347](https://github.com/ppy/osu/assets/38471793/09aca994-4501-4e5e-8eae-0ebb4a77cdba)

### Version

https://osu.ppy.sh/home/changelog/stable40/20231219.2

### Logs

[osu!auth.log](https://github.com/ppy/osu/files/13745807/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/13745808/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/13745809/update_success.log)

**Comment by bdach** [comment]
This is one for https://github.com/ppy/osu-stable-issues
