### ISSUE TITLE
Shows misses eventhough I didn't miss nor lose combo

### ISSUE THREAD

**Issue by RosenbergGG** [ppy/osu#26014]
### Type

Game behaviour

### Bug description

I was just playing and notice at the end of the map that It showed I missed every last slider but didn't lose any combo so I decided to look at the replay and I was right.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/127504909/5c5c560e-0acb-4696-8ab1-f4c07786ec19)
![image](https://github.com/ppy/osu/assets/127504909/ed48b4f0-7c42-41f3-a4bd-a2a06c10e9f9)

### Version

1222.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13744851/compressed-logs.zip)

**Comment by bdach** [comment]
Please upload the replay.

**Comment by TruestGecko** [comment]
[Guest playing Yuyoyuppe - AiAe (Fort) [Another] (2023-12-21_13-15).zip](https://github.com/ppy/osu/files/13745567/Guest.playing.Yuyoyuppe.-.AiAe.Fort.Another.2023-12-21_13-15.zip)
Here is a replay where it happened for me. It seems to mostly (or only) happen on slider ends.

**Comment by rszyma** [comment]
Also happens on some maps with RX mod enabled.

**Comment by peppy** [comment]
Yes. You did lose combo. This is now showing you that you did.
