### ISSUE TITLE
osu!taiko in-game leaderboards placed incorrectly

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu#26011]
### Type

Game behaviour

### Bug description

should be lower

### Screenshots or videos

![osu!_2023-12-21_18-15-52](https://github.com/ppy/osu/assets/32525896/4181a614-8ceb-4d2c-aeb4-9023c80631c5)

### Version

2023.1222.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13744571/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/20422
