### ISSUE TITLE
Cannot input spaces when filtering beatmap collections if 'Select' key is mapped to 'Space'

### ISSUE THREAD

**Issue by 3047256** [ppy/osu#26025]
### Type

Game behaviour

### Bug description

`Space` is one of the default key bindings for `GlobalAction.Select`:  
https://github.com/ppy/osu/blob/master/osu.Game/Input/Bindings/GlobalActionContainer.cs#L91

If a beatmap is selected, even when the beatmap collection filter is focused, any spaces entered will be overriden by the the select action in song select.

### Screenshots or videos

https://github.com/ppy/osu/assets/154562391/513418da-913b-40c5-98e9-3912e10924ae

### Version

2023.1222.0-lazer

### Logs

-

**Comment by smoogipoo** [comment]
That is shocking.

**Comment by peppy** [comment]
@frenzibyte another case of nested input manager going wrong

**Comment by frenzibyte** [comment]
Duplicate of https://github.com/ppy/osu/issues/25769
