### ISSUE TITLE
Its really hard to find song without anime girl or vtuber

### ISSUE THREAD

**Issue by TV-Toshikawa** [ppy/osu#26033]
### Type

Other

### Bug description

i looked at beatmap list but most of song are full of anime girl or vtubers.
can you fix this? i want to play game without anime girl but i cant

### Version

Any

### Logs

I dont think log does anything
also on android14, "android/data/" cant be accessed so need better method

**Comment by NamGitHub2002** [comment]
it... doesn't look like any issue at all.
This is not possible with beatmaps.
Everyone can create an anime beatmap and post it on bancho, and anyone can do it.
