### ISSUE TITLE
Incorrect score multiplier when DT/NC and Hidden are both selected

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#26065]
### Type

Game behaviour

### Bug description

Value is supposed to be 1.16 but it shows as 1.17 instead.

### Screenshots or videos

![multiplier_issue](https://github.com/ppy/osu/assets/58333920/61ec5fc2-ab8c-4977-a721-1e89be0e07c9)

### Version

2023.1223.0

### Logs

.

**Comment by bdach** [comment]
Double Time is 1.11x. Hidden is 1.06x. Multiplied together, they are 1.166x, which rounded to 2 decimal places is 1.17.

**Comment by Stoppedpuma** [comment]
haha my bad I was adding .10 and .06 and didn't even think about multiplying 1.xx, math is definitely not my strong point when I'm half asleep.
