### ISSUE TITLE
When buttons are stacked on top of each other, the button below should not trigger

### ISSUE THREAD

**Issue by Jan-Arbus** [ppy/osu#26079]
### Type

Game behaviour

### Bug description

Pay attention to the favorites bar, the favorites bar should not enter the search state when I click on the next song
The problem seems to be unique to Android.

### Screenshots or videos

https://github.com/ppy/osu/assets/74862110/46169dd9-09e3-486d-a860-c66ca7da51f3

### Version

2023.1223

### Logs

N/A

**Comment by peppy** [comment]
@frenzibyte another one, probably duplicate?

**Comment by Jan-Arbus** [comment]
The problem can still be reproduced, reopened

**Comment by bdach** [comment]
I can confirm the above. This will be fixed with a framework bump.
