### ISSUE TITLE
Opening the player for multi while Circles is playing will reserve all memory

### ISSUE THREAD

**Issue by AlFasGD** [ppy/osu#2608]
Steps to reproduce:
- Open osu!lazer
- Change mode to osu!mania
- Do NOT change the beatmap, let Circles play in the background
- Navigate to Play > Multi > Match > Player

Version: 2018.522.0

The reserved memory will start stacking up with a rate of ~300 MB/s, leading to severe lag once too much memory is reserved in an attempt to free it.

Despite the fact that:
- This has to do with the fact that any attempt to load an osu!mania beatmap not containing any objects won't throw an exception
- Circles is not meant to be usable in any form when opening any screen

I think it's useful to at least get rid of that bug.

**Comment by DrabWeb** [comment]
Did this happen when opening a proper beatmap? If not, then this can be closed as you can no longer enter the player from multi, and when you can it will not be able to be opened while Circles is playing.
