### ISSUE TITLE
spinner-top and spinner-middle2 spinning at the same speed

### ISSUE THREAD

**Issue by Wrongwayscout** [ppy/osu#26094]
### Type

Cosmetic

### Bug description

The way spinners are animated is quite different from stable, I understand. 
But, in stable, spinner-top and spinner-middle2 spin at different speeds, but now spinner-top and spinner-middle2 spin at the same speed. The skin I use and made uses spinner-top and spinner-middle-2 as the parts of the spinner and now the entire spinner spins at the same speed, when it was not meant to. (I didn't use spinner-bottom because it was too slow for what I had wanted)
I checked and this all happens on osu! "classic" (2013) as well, it just isn't very noticeable since spinner-middle2 is just in the very center of that skin's spinner.
I noticed this because spinners spin much faster overall in lazer, which I personally found distracting, and so while trying to inspect why that was, I noticed that the elements on my skin's spinner were permanently aligned, which isn't how I had designed it. Spinners spinning faster is fine, though perhaps legacy skins should act as they used to, but the relative speeds of each spinner element should really stay the same.

### Screenshots or videos

stable video:
https://github.com/ppy/osu/assets/84840821/05fc99a8-c16e-4afe-a7b8-abdc9008c30f

lazer video:
https://github.com/ppy/osu/assets/84840821/94459316-40f8-47ba-89a7-c05b1f80bae7

skin:
[- _ PINKOUT _ - (Rozemyne).zip](https://github.com/ppy/osu/files/13760701/-._.PINKOUT._.-.Rozemyne.zip)

the specific skin elements in question:
[spinner-top@2x](https://github.com/ppy/osu/assets/84840821/5114d001-e346-4ccb-b026-d5ee1ea283ae)

[spinner-middle2@2x](https://github.com/ppy/osu/assets/84840821/37abf038-7d54-4097-b7cd-69cd4cd308d5)

### Version

2023.1224.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13760677/compressed-logs.zip)

**Comment by peppy** [comment]
Here's the relevant stable code if someone wants to give this a shot. It should be pretty simple:

```csharp
                float rotationAddition = (float)(velocityCurrent * InputManager.ElapsedAudioTime);
                float turnRatio = spriteMiddleBottom != null && spriteMiddleBottom.Texture != null ? 0.5f : 1;

                // We don't want the spinner sprite to spin faster / slower when DT / HT are active. It should always spin proportionally to the cursor spinning rate.
                SpriteCircleTop.Rotation += (float)HitObjectManager.ApplyModsToTime(rotationAddition * turnRatio, hitObjectManager.ActiveMods);
                if (spriteMiddleBottom != null)
                {
                    spriteMiddleBottom.Rotation += (float)HitObjectManager.ApplyModsToTime(rotationAddition, hitObjectManager.ActiveMods);
                    spriteCircleBottom.Rotation = SpriteCircleTop.Rotation / 3f;
                }
```
