### ISSUE TITLE
Skin elements not correctly aplied

### ISSUE THREAD

**Issue by Neon095** [ppy/osu#26103]
### Type

Game behaviour

### Bug description

I found the bug when importing a new skin. It happens whit other skins also.

### Screenshots or videos

![imagen](https://github.com/ppy/osu/assets/97938542/945ec895-6ab2-47c8-9463-9fc40c448efb)

![imagen](https://github.com/ppy/osu/assets/97938542/021d0f5e-85ff-4f7c-8e99-52d97d46a09f)

### Version

2023.1224.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13761790/compressed-logs.zip)

**Comment by Flamiii** [comment]
This is happening because your UI scaling seems to be below 1.0x, causing your scorebar-bg.png to not fit the entire screen. You can either change your UI scaling back to 1.0x or manually resize the skin element to fit the entire screen using the built-in skin editor.

**Comment by bdach** [comment]
The `scorebar-bg` hack is and always has been a hack reliant on screen aspect ratio and other such things. It will not be supported going forward.

If you want a playfield border, there's now a built-in one in settings.

**Comment by Neon095** [comment]
Ok thx.

**Comment by Methosss** [comment]
it would be ok if there was button "don't scale scorebar-bg" under UI scalling

**Comment by bdach** [comment]
there will be no such button.
