### ISSUE TITLE
osu!lazer has trouble rendering the really big stacked sliders in aspire maps

### ISSUE THREAD

**Issue by Xnightslayer99** [ppy/osu#26111]
### Type

Performance

### Bug description

While playing osu!lazer i decided to play an aspire map specifically [this one](https://osu.ppy.sh/beatmapsets/982020#osu/2055234)
While playing the map, as i approached the first set of "tree" sliders, the game slowed down to ~3fps from 100+

### Version

2023.1224.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13763705/compressed-logs.zip)

**Comment by peppy** [comment]
Please search first, there's around 10 issues covering aspire beatmaps, including slider issues.
