### ISSUE TITLE
Skin Editor doesn't position the object as expected

### ISSUE THREAD

**Issue by fakeaireuonboard** [ppy/osu#26123]
### Type

Game behaviour

### Bug description

When I tried to customize the Skin Editor, I thought it'll automatically position the object as I intended to happen. This may be the Skin's issue or just the resolution of the Skin editor.

### Screenshots or videos

https://github.com/ppy/osu/assets/124829162/ad0d0961-f89f-480d-bbf0-c43ec64fa309

### Version

2023.1224.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13766426/compressed-logs.zip)

**Comment by bdach** [comment]
Change the anchor of both elements to top left via the context menu.

**Comment by fakeaireuonboard** [comment]
Alright it worked! I feel dumbfounded right now.
