### ISSUE TITLE
Text clipping

### ISSUE THREAD

**Issue by OmegaFloweyAdmin** [ppy/osu#26151]
### Type

Game behaviour

### Bug description

I was looking at song listings and the leaderboard text was clipping into more text.

### Screenshots or videos

![Screenshot 2023-12-26 at 5 24 25 PM](https://github.com/ppy/osu/assets/141077905/b65a5fb9-7df2-49b6-89fb-4cea95a186b7)

### Version

2023.1224.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13773942/compressed-logs.zip)

**Comment by peppy** [comment]
Duplicate
