### ISSUE TITLE
PP and rank on my profile "reset"

### ISSUE THREAD

**Issue by CipherGamer** [ppy/osu#26173]
### Type

Game behaviour

### Bug description

https://osu.ppy.sh/users/11388672

I've just been playing osu!mania, when suddenly my pp and rank, as well as ranked accuracy entirely reset.

This happened without warning, and despite using a fix for a similar problem from another bug report ( https://github.com/ppy/osu/discussions/21831 ), it did not put me back on my previous rank. Did I miss some sort of update to the ranking system that reset everyone's scores, or is this just me?

I unfortunately didn't manage to make a screenshot of the exact map that this bug happened on, but I have screenshots before and after using the fix from the aforementioned bug report.

For some background, I had moved onto osu!laser around 6-ish months ago? There has not been any problem with the game, aside from a few expected performance issues/already-fixed bugs.

### Screenshots or videos

![osu_2023-12-27_22-57-02](https://github.com/ppy/osu/assets/155024831/15fdc676-11de-4bff-9237-8566265be2e9)
![osu_2023-12-27_23-27-25](https://github.com/ppy/osu/assets/155024831/603169dd-42ff-4776-bf14-07384d3731c8)

### Version

Laser 2023.1224.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13781918/compressed-logs.zip)

**Comment by bdach** [comment]
We are currently doing some work in preparation for common leaderboards and pp granting with stable. Please bear with us for now, all will be explained in due time.

**Comment by CipherGamer** [comment]
> We are currently doing some work in preparation for common leaderboards and pp granting with stable. Please bear with us for now, all will be explained in due time.

Could I ask how long this will take? My rank is still worryingly low...

**Comment by frenzibyte** [comment]
It's not finished yet, please wait patiently.
