### ISSUE TITLE
Autoplay ignored leaderboard toggle

### ISSUE THREAD

**Issue by zvyap** [ppy/osu#26185]
### Type

Cosmetic

### Bug description

Autoplay mod ignore in-game leaderboard toggle

Tested in lastest commit build and official version

Actually I'm not sure this is designed it behave like that or what, but it already said `Toggle In-Game Leaderboard - Disabled`, it should be disabled right?

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/52874570/b71b2ceb-71ae-48ca-8e29-59fbeba51d43)

### Version

2023.1224.0 / Lastest Dev Build

### Logs

2023.1224.0
[compressed-logs.zip](https://github.com/ppy/osu/files/13784769/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25512
