### ISSUE TITLE
Multiplayer: Invalid combination of required and allowed mods: RX,NF

### ISSUE THREAD

**Issue by Airkek** [ppy/osu#26180]
### Type

Other

### Bug description

Sometimes when switching mods with [freemod: all] osu! says that you set invalid combination of mods - RX/NF which is legal combination now

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/45855057/a4b8c2cb-a99b-4984-81d6-d2126f33cff6)

### Version

2023.1224.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13783892/compressed-logs.zip)

**Comment by Airkek** [comment]
On dev build also cannot set [Freeemod: all]:
![image](https://github.com/ppy/osu/assets/45855057/9d84e912-c748-4dd8-98ac-2ffd7cac4a9a)

**Comment by peppy** [comment]
I think we need a spectator server update for this.

**Comment by peppy** [comment]
Update has been deployed!

**Comment by Airkek** [comment]
> Update has been deployed!

both dev and release
![image](https://github.com/ppy/osu/assets/45855057/15ff71fd-a4a8-44d8-9263-64b042a6210e)
![image](https://github.com/ppy/osu/assets/45855057/2aa300e2-3757-47b6-800b-a0a512724fba)
