### ISSUE TITLE
[Memory leak] Caused by opening the video background

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu#26192]
### Bug description

It's not a big problem. After running for an hour, the memory slightly increased. Not as obvious as stable.
There is currently no impact on normal operation, but it may become a safety hazard.

Used the same testing method as stable.
stable issue: https://github.com/ppy/osu-stable-issues/issues/1197

### Screenshots or videos

![QQ截图20231229005151](https://github.com/ppy/osu/assets/26690346/d5063de8-704e-4c0a-8069-1419627935ce)

### Version

osu! 2023.1224.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13788162/compressed-logs.zip)

**Comment by peppy** [comment]
When you run an app, it uses memory. This is expected.

**Comment by wanjiaXG** [comment]
> When you run an app, it uses memory. This is expected. You are welcome to investigate this if you think it is a leak, but what you show here is well within normal operation parameters.

At present, I have only been running for 1 hour. Compared to the first time I played, I have increased the memory by 200-300m. Of course, this value was observed in dot memory, and there is no significant difference in taskmgr. If there is time, I will do a long-term test.
