### ISSUE TITLE
Triangles in gamemode background on the new toolbar spill out

### ISSUE THREAD

**Issue by PillTime** [ppy/osu#26197]
### Type

Cosmetic

### Bug description

As it says in the title, the triangles from the gamemodes background from the new toolbar design spill out by a pixel. It's a very minor issue, but still very visible, especially it being animated.

### Screenshots or videos

![osu_2023-12-28_20-13-00](https://github.com/ppy/osu/assets/2399664/cefbdfde-f7aa-41cd-9af1-44294865da57)

### Version

2023.1229.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13789259/compressed-logs.zip)

**Comment by bdach** [comment]
#4591
