### ISSUE TITLE
Autopilot cursor now choppy on large movements.

### ISSUE THREAD

**Issue by mysteGH** [ppy/osu#26206]
### Type

Game behaviour

### Bug description

was giving the new offset wizard a little try and didn't have my tablet so i decided to try autopilot when i noticed that the cursor is now choppy almost like it's inputting inconsistently at 30hz or something.

this is only made clear in large jumps / movements, i wanted to make sure it was actually choppy movement so i've created a little comparison between how stable and lazer autopilot behaves.

gameplay wise, it does make tapping somewhat more difficult, maybe because there's a little bit less time where your cursor is actually on the note? but that could definitely be placebo.

### Screenshots or videos

https://github.com/ppy/osu/assets/96603029/88a28ec1-a99c-4627-bbc9-f38159fc3620

### Version

2023.1229.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13790528/compressed-logs.zip)

**Comment by bdach** [comment]
#19930
