### ISSUE TITLE
settings cannot use arrow keys to control the value

### ISSUE THREAD

**Issue by chchee3300** [ppy/osu#26211]
### Type

Game behaviour

### Bug description

It's on the title, previously can work on standard version but not on lazer

### Screenshots or videos

https://github.com/ppy/osu/assets/84435341/daa1fa47-6204-4d26-b3a6-89f590e21a4d

### Version

2023.1229.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13791089/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/discussions/26175#discussioncomment-7968770 likely root cause / reproduction scenario
