### ISSUE TITLE
300s not showing with Depth mod

### ISSUE THREAD

**Issue by BashhScriptKid** [ppy/osu#26229]
### Type

Game behaviour

### Bug description

I tried the new depth modifier and was tinkering around with it, which then I tried using it with the osu!'argon' which has the 300s drawn (as GREATs) then notices it wasn't drawn with the modifier applied. To make sure it wasn't an osu!'argon' specific issue, I tried it again with the classic skin, which also didn't get the 300s drawn. Tried both without the modifier, it gets drawn like normal.

### Screenshots or videos

osu!'argon' (without Depth modifier)

https://github.com/ppy/osu/assets/63024549/c9eb19ea-ef3d-46d8-8721-89be2addc5da

osu!'argon' (with Depth modifier)

https://github.com/ppy/osu/assets/63024549/d2854e6f-1f40-4a55-a260-10e98b54a7ca

osu! classic (with Depth modifier)

https://github.com/ppy/osu/assets/63024549/db52e399-2696-4589-a93f-82b287d91ce4

osu! classic (without Depth modifier)

https://github.com/ppy/osu/assets/63024549/914a5bcc-2d7d-4a96-b207-b5e7b32a6f7c

### Version

2023.1229.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13794345/compressed-logs.zip)

**Comment by EVAST9919** [comment]
These are deliberately disabled for now due to some technical limitations. Same as in `OsuModMagnetised' and `OsuModRepel`.

**Comment by frenzibyte** [comment]
Tracking in https://github.com/ppy/osu/issues/20139
