### ISSUE TITLE
Tablet raw input broken on Linux

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu#2623]
_Are we reporting Linux+input issues? :thinking:_

[YouTube video](https://www.youtube.com/watch?v=DTVCAtufaP4)

It seems as if the tablet is mapped to a much bigger rectangle than the screen, what is visible when the cursor is `never` confined. The parallax gets so much offset the screen goes black.

Mouse works perfectly fine.

osu!Tablet (first one, white), Lubuntu 18.04

Later I can try testing at my family's Ubuntu laptop and see if this also happens on it.

**Edit**: Apparently no, won't test it there, because I can't install msbuild and mono because of random broken packages, that I couldn't fix with trying every available solution on the internet for 4 hours, including clean install.

**Comment by peppy** [comment]
I don't think raw input with tablets was ever tested on linux. Keep in mind that this will be a framework level issue if you attempt to fix it.

**Comment by peppy** [comment]
Raw input has since been disabled on linux. We are introducing a tablet-specific handler in the near future which will resolve your issues.

Closing this for now.

**Comment by Clown-On-Github** [comment]
hehe
