### ISSUE TITLE
Editor rotation popover incorrectly disabled when selecting a single hit circle

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#26247]
### Type

Game behaviour

### Bug description

If you select a single hit circle in the editor, the rotation tool will be disabled, but this is incorrect behaviour because you can still rotate the hit circle around the center of the playfield. 

`OsuSelectionRotationHandler.updateState` assumes that the rotation is always around the selection center, but this is not true. The editor rotation popover should use a different definition of `CanRotate` because it is more powerful than the rotation handles on the selection box.

### Version

2023.1229.1

### Logs

[1703898149.runtime.log](https://github.com/ppy/osu/files/13796723/1703898149.runtime.log)
[1703898149.performance.log](https://github.com/ppy/osu/files/13796724/1703898149.performance.log)
[1703898149.network.log](https://github.com/ppy/osu/files/13796725/1703898149.network.log)

**Comment by bdach** [comment]
Notably the rotation operation *should* arguably continue to be inaccessible via the rotation handlers in the composer, but the popover *should* become accessible.
