### ISSUE TITLE
.osz and .osk files do not seem to be associated with osu!lazer

### ISSUE THREAD

**Issue by wsxdrfvyhn** [ppy/osu#26245]
### Type

Other

### Bug description

as the title says, .osz and .osk files aren't associated with osu!lazer even after starting up the game a few times. osu!lazer is the only version of osu i have ever had on this installation of windows, i have not yet installed the stable version of osu! as well.
i have also tried importing both filetypes into the game and restarting my computer afterwards to no avail.

### Screenshots or videos

![explorer_1z6ByIEXrZ](https://github.com/ppy/osu/assets/66824635/528b73b2-0a91-487e-b417-d0da4ab013b3)
![explorer_7NGyQPyxKk](https://github.com/ppy/osu/assets/66824635/e7eb75f7-5cb3-47e6-bfdd-22452560fc08)

### Version

2023.1229.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13796548/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/14824
