### ISSUE TITLE
Settings section text gets cut off on certain languages

### ISSUE THREAD

**Issue by respektive** [ppy/osu#26264]
### Type

Cosmetic

### Bug description

It looks fine on English, but on some other languages like German it gets cut off.

### Screenshots or videos

![osu_2023-12-30_16-21-25](https://github.com/ppy/osu/assets/22381687/118fec50-137c-4109-bd51-e2fe1763e57b)
![osu_2023-12-30_16-26-40](https://github.com/ppy/osu/assets/22381687/e86957a6-6f59-4d09-9ff1-67174983f0df)

### Version

2023.1229.1

### Logs

N/A

**Comment by bdach** [comment]
#21617
