### ISSUE TITLE
Edited (on Stable) then imported Ranked map has no "update" button

### ISSUE THREAD

**Issue by RatinFX** [ppy/osu#26277]
### Type

Game behaviour

### Bug description

~~I edited a map's AR on Stable and imported it to lazer (alongside other beatmaps) via the setup wizard.~~

~~This resulted in the map still having the edited AR and the user not being able to submit a score on it because it cannot be "updated" unless it's deleted and downloaded again.~~

Nvm, the update button was on the set item and my eyes totally missed it, I was searching for it on the difficulty instead. 

A way to forcefully re-download the map would be great though, especially for locally (in lazer) edited beatmaps.

### Screenshots or videos

![osu!_2023-12-31_01-15-20](https://github.com/ppy/osu/assets/38523955/02e770b5-e513-4f7d-a702-fa132488bf5a)

![osu!_2023-12-31_01-15-44](https://github.com/ppy/osu/assets/38523955/45a81426-2205-4b13-934b-7675d070088b)

### Version

2023.1229.1

**Comment by frenzibyte** [comment]
@RatinFX What is the issue here? The beatmap shows the "Update" button as expected. If you think it should have the "local" status, that is only given when the beatmap is modified **in lazer**. Closing.
