### ISSUE TITLE
PP not adding up properly

### ISSUE THREAD

**Issue by rtran138** [ppy/osu#26280]
### Type

Crash to desktop

### Bug description

https://lazer.ppy.sh/users/4155721

I'm currently experiencing an issue on Lazer where my PP is fluctuating/resetting on an almost daily basis. 

I was at 1812 PP earlier this week but then dropped all the way down to 0 pp. 

A few days afterwards I would play on Lazer again and my pp would go back up to 1700 for some unknown reason. 

Yesterday my pp was lowered down to about 800-900 and I am currently at 954 and is not consistent with the sum of my top plays. The weighted sum of my 10 highest pp plays is around 1251 which is much higher than my profile's current 954 pp. Is there something that can be done about this?

### Screenshots or videos

![d9d92e80a8a501b411149031a99b4ebf](https://github.com/ppy/osu/assets/44415919/78cf948c-7c5d-4b56-a759-349c0098ffc7)

### Version

2023.1229.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13800277/compressed-logs.zip)

**Comment by peppy** [comment]
Have you tried playing again recently? I fixed pp not calculating last night.

Keep in mind we're looking to reset the leaderboards soon so this will likely change again.

**Comment by rtran138** [comment]
Yes, I have been playing basically all day today. I calculated the first
10-15 of my top plays and the amount was 1152 (currently at 1060).

Thank you for the heads up, I'll be ready for that whenever it comes! Lazer
has been an amazing experience so far so I'm really looking forward to when
the leaderboards between stable and lazer are merged!

Best,

Raymond Tran
