### ISSUE TITLE
Resume cursor limits minimum size, disrespecting small "Gameplay cursor size" values

### ISSUE THREAD

**Issue by JacksonChen666** [ppy/osu#26289]
### Type

Cosmetic

### Bug description

If the "Gameplay cursor size" option was set to something less than 0.87x (e.g. 0.5x), the **resume cursor** will stay the same size (at 0.87x or 0.88x). Anything higher than 0.87x for Gameplay cursor size isn't a problem.

### Screenshots or videos

0.5x gameplay cursor size:

![osu!lazer asks to click the cursor to resume. The gameplay cursor is on the resume cursor, which is noticeably bigger.](https://github.com/ppy/osu/assets/50755746/86d09d94-d93d-41c3-9814-04d6610900b0)
![The gameplay cursor away from the resume cursor. The resume cursor is obviously bigger.](https://github.com/ppy/osu/assets/50755746/88462a74-56b0-4ec4-9bc0-ec777bb7ffcf)

1x gameplay cursor size:

![osu!lazer asks to click the cursor to resume. The gameplay cursor is on the resume cursor, and looks like the same size.](https://github.com/ppy/osu/assets/50755746/463ec7c1-9a6a-4925-9a7c-6c36fb331720)
![The gameplay cursor away from the resume cursor. Both look like the same size/](https://github.com/ppy/osu/assets/50755746/c0276767-cd1b-46e2-8ebb-5d735c665b7d)

### Version

2023.1231.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13801427/compressed-logs.zip)

**Comment by bdach** [comment]
intentional (#26148)
