### ISSUE TITLE
Song select grouping issue 

### ISSUE THREAD

**Issue by AstronomyLoot** [ppy/osu#26302]
### Type

Game behaviour

### Bug description

I think this kind of grouping system were implemented somewhere mid 2023 but even after all the updates it still seems like the beatmap grouping is separate

### Screenshots or videos

<img width="1680" alt="Screenshot 2024-01-01 at 12 36 29" src="https://github.com/ppy/osu/assets/92839855/e40ab294-8178-4dd0-835a-91c6bd3cb06e">
you can see here all the difficulties are like separated individually and not as a whole beatmap set

### Version

Lazer 2023.1231.0

### Logs

the log is here
[compressed-logs.zip](https://github.com/ppy/osu/files/13802666/compressed-logs.zip)

**Comment by Flamiii** [comment]
This was changed in https://github.com/ppy/osu/pull/24614 and is not a bug. Most people seem to prefer this way of difficulty sort in song select as opposed to way it worked before (where it grouped entire mapsets together and sorted them based on the star rating of the hardest difficulty). This also matches the behavior of osu!stable.

**Comment by AstronomyLoot** [comment]
is there any way to change the beatmap grouping from this one to the one that groups beatmaps without separating the different difficulties within each mapset??

**Comment by peppy** [comment]
It's coming later.
