### ISSUE TITLE
Rewrite the input section on settings

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#2630]
Most of these settings can apply to tablets or other [pointing devices](https://en.wikipedia.org/wiki/Pointing_device) too. Thinking about changing the subsection name to [pointing devices](https://en.wikipedia.org/wiki/Pointing_device), and removing the word `mouse`.

Also the ones that say `during gameplay` should be on the actual `Gameplay` section?
![](https://puu.sh/AsvVJ/0506582d22.png)

Or should all input options be in the `Input` section? (i.e. this setting is an input setting for song select.)
![](https://puu.sh/Aswrl/371e0f21be.png)

**Comment by peppy** [comment]
Eventually we should be grouping options per device.

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu/pull/12006.
