### ISSUE TITLE
Slider shorter than chosen beat snap can be created 

### ISSUE THREAD

**Issue by Dopaminos** [ppy/osu#26318]
Game behaviour

### Bug description

Basically... You can create sliders that is shorter than beat snap you chose!
![image](https://github.com/ppy/osu/assets/42616718/31a6952e-1159-4f95-b6e7-134a7f56d47c)
It creates a weird visual bug and if you will export map containing such slider in stable - it will be invisible.
![image](https://github.com/ppy/osu/assets/42616718/a737f1fb-dd8d-42e7-903f-f98fdb454519)

[map in .olz format](https://dopaminos.s-ul.eu/DQVPumXx)
[map in .osz format](https://dopaminos.s-ul.eu/6hlZ0AcK) 

Difficulty to look on: easy
This behaviour doesn't match stable, because it's impossible to create such sliders, and also it's unsnapped because of ridicuously short length
###  Version

2023.1231.0

**Comment by cihe13375** [comment]
How did you create that slider?

**Comment by bdach** [comment]
#10959
