### ISSUE TITLE
beatmap sound samples don't account for pitch shifting when being sped up or slowed down

### ISSUE THREAD

**Issue by Squaduck** [ppy/osu#26320]
### Type

Game behaviour

### Bug description

beatmaps that play audio samples on top of the music don't account for pitch shifting when playing back at a different speed. The audio sample gets pitch-shifted.

### Screenshots or videos

https://github.com/ppy/osu/assets/55469508/6002c71c-085e-48be-8957-e4c24e06162e

### Version

2023.1231.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13806343/compressed-logs.zip)

**Comment by bdach** [comment]
#10069

please search
