### ISSUE TITLE
Undoing an operation done to a selected group of objects deselects the group of objects

### ISSUE THREAD

**Issue by Mrgglock** [ppy/osu#26327]
### Type

Other

### Bug description

Reproduce:
1. Open any map in the editor
2. Select any group of objects
3. Do some operation, say, move it somewhere else on the screen
4. Press Ctrl+Z
Current: The objects should remain selected
Expected: The objects are deselected

This is unintuitive behaviour and does not mimic what is seen on stable as well as popular software such as Photoshop, where the group of objects is expected to stay selected. In a normal use case, the mapper would have done a wrong operation, undo that operation, and then proceed to do the correct operation on the selected group of objects

### Screenshots or videos

https://github.com/ppy/osu/assets/9843579/b2f200c3-c0c2-4be7-9ff0-ce5130d3e443

### Version

Lazer 2023.1231.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13807259/compressed-logs.zip)

**Comment by bdach** [comment]
#10627

please search x2
