### ISSUE TITLE
Spinner starting from max after seeing it max out in the editor

### ISSUE THREAD

**Issue by Mrgglock** [ppy/osu#26326]
### Type

Other

### Bug description

Reproduce:
1. Open any map in the editor
2. Make a spinner
3. Watch the spinner max out
4. Go back and watch the spinner again
Current behaviour: The spinner starts from max
Expected behaviour: It should start from 0 again

### Screenshots or videos

https://github.com/ppy/osu/assets/9843579/77531755-1f24-4c1c-940a-ec013d59d43a

### Version

Lazer 2023.1231.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13807247/compressed-logs.zip)

**Comment by bdach** [comment]
#10455

please search
