### ISSUE TITLE
Saving any metadata field requires clicking off the box

### ISSUE THREAD

**Issue by Mrgglock** [ppy/osu#26324]
### Type

Other

### Bug description

Reproduce:
1. Open a beatmap
2. Click the setup tab
3. Click the Difficulty Name field
4. Append something, like "x"
Let's say the above is our setup, then...

1. Setup with above.
2. Press "Esc"
Current Behaviour: Exits without any prompt to save
Expected Behaviour: Prompt the user to save

 1. Setup with above.
 2. Press Ctrl+S
 3. Press "Esc"
 Current Behaviour: Exits without saving
Expected Behaviour: The field should be saved

### Version

Lazer 2023.1231.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13807172/compressed-logs.zip)

**Comment by ntransw** [comment]
caused by updates being invoked only on commit:

```Csharp       
private void onCommit(TextBox sender, bool newText)
        {
            if (!newText) return;

            // for now, update on commit rather than making BeatmapMetadata bindables.
            // after switching database engines we can reconsider if switching to bindables is a good direction.
            Scheduler.AddOnce(updateMetadata);
        }
```

would now be a good time to switch to bindables?
