### ISSUE TITLE
High PP reward while using daycore

### ISSUE THREAD

**Issue by AaronTherapy** [ppy/osu#26335]
### Type

Game behaviour

### Bug description

While playing osu, I selected the daycore mod, I got a weirdly high best play.
I got a 120~ pp in game but on [my profile](https://lazer.ppy.sh/users/34471194) it says that I got 207pp which is a lot for me. The score was set using daycore but the pp reward isnt changed at all, should be fixed before the pp update.. 

### Screenshots or videos

https://youtu.be/uaEAHq-hhD4

### Version

2023.1231.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13809267/compressed-logs.zip)

**Comment by bdach** [comment]
This was reported already (https://github.com/ppy/osu/issues/25719) and fixed (https://github.com/ppy/osu-queue-score-statistics/pull/177). The fix has not been deployed yet, but will be before pp goes live.

Thanks for reporting, please wait for things to resolve on their own.
