### ISSUE TITLE
Background dim slider doesn't always work correctly

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#26344]
### Type

Cosmetic

### Bug description

Dragging the dim slider doesn't always show the correct dim level.

### Screenshots or videos

[bgdimissue.webm](https://github.com/ppy/osu/assets/58333920/4298d22a-e873-44a3-8868-28484f0fa9a7)

### Version

2023.1231.0

### Logs

[shorter_runtime.log](https://github.com/ppy/osu/files/13812987/shorter_runtime.log)

**Comment by bdach** [comment]
I don't understand this report? When are you claiming that the dim level is "incorrect"?
