### ISSUE TITLE
[Memory leak] Long time running of the lazer will result in an increasing amount of memory that will not be released

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu#26368]
### Type

Performance

### Bug description

After running the lazer for a long time, the memory will increase at a speed of approximately 600-700m/h and will not be released,

test method：

Lazer only has two mapset.

Turn on NF+DT+AUTO, then play the complete map with the video, and keep repeating this process

After running continuously for 2 hours, the trend of memory changes is shown in the figure.

![QQ图片20240104010954](https://github.com/ppy/osu/assets/26690346/1294c7a1-b408-4c1f-a205-b51d2b069bc6)

![QQ截图20240104011816](https://github.com/ppy/osu/assets/26690346/7b715be3-581e-4ce3-95f3-cd7b1bb3fd6e)

I am testing under the windowed setting, and if using fullscreen, there will be slightly more memory, and the peak after 2 hours will be to 3G.

The same issue https://github.com/ppy/osu/issues/26192
Because I am unable to reopen old issue,  so I am opening a new issue.

Memory dump file(2.35G) has been sent to pe@ppy.sh.

Stable also has similar issues, but the Lazer has not experienced any crashes so far, it may cause other problems in the future.

### Version

osu! 2023.1224.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13821738/compressed-logs.zip)

**Comment by peppy** [comment]
Please test without video, since you seem to be implying that it is video related but not directly stating that.

**Comment by wanjiaXG** [comment]
> Please test without video, since you seem to be implying that it is video related but not directly stating that.

Yes, the cause may be similar to that stable, enabled video background will result in memory leak.

![QQ截图20240104025548](https://github.com/ppy/osu/assets/26690346/e580d239-5280-41a9-8383-c10081b04ae0)

**Comment by EVAST9919** [comment]
Since you are on D3D renderer, probably a duplicate/extension of https://github.com/ppy/osu/issues/23258?
If this can't be reproduced with LegacyGL then most likely it is.

**Comment by peppy** [comment]
It would make more sense to be honest, if the issue you reported is also specifically *video* not storyboards in general.

@EVAST9919 want to confirm with a beatmap that doesn't have video vs one that does and close your issue in favour of this one if that's the case?

**Comment by EVAST9919** [comment]
Unfortunately I was talking about storyboards (any textures, to be exact), and the issue can still be replicated.
It looks like I musunderstood this one. In my case on D3D allocated VRAM is never freed even when using "Clear all caches" and when it overflows and goes to RAM, it can't be cleared as well (which is not the case on LegacyGL).

Regarding this one, I can replicate ram usage increase by playing maps with a video, however purging cache immediately helps.

**Comment by smoogipoo** [comment]
Will likely be fixed in the next release by https://github.com/ppy/veldrid/pull/54

**Comment by Wilker-uwu** [comment]
i'm writing here if it's relevant:

reading this as memory accumulating in background, i got a similar problem leaving the game minimized. [Toby Fox - Finale +HDHR](https://osu.ppy.sh/beatmapsets/667713#osu/1566387 "Link to beatmap"), with the autoplay triggered by the skin editor, and left with the screen open in the background for a similar period (shorter period because my pc isn't that strong)

[compressed-logs.zip](https://github.com/user-attachments/files/29183535/compressed-logs.zip)
