### ISSUE TITLE
taiko maps which consist only of drum rolls and swells cannot be passed

### ISSUE THREAD

**Issue by bdach** [ppy/osu#26370]
### Type

Game behaviour

### Bug description

- https://osu.ppy.sh/beatmapsets/371675#taiko/814198 is all drum rolls
- https://osu.ppy.sh/beatmapsets/614615#taiko/1371517 is all drum rolls & swells
- https://osu.ppy.sh/beatmapsets/675779#taiko/1431549 is all drum rolls

Because health in taiko can only be gained from hits:

https://github.com/ppy/osu/blob/8b8f7953ec2736c28e0aaedecf5da6863071afde/osu.Game.Rulesets.Taiko/Judgements/TaikoJudgement.cs#L13-L29

if a beatmap consists entirely of drum rolls & swells, it is impossible to gain any health on it, implying it is impossible to go above 50% health, implying it is impossible to pass.

I haven't checked if stable behaves the same but this seems like a potential problem unless confirmed that stable also does this (but I doubt it, since these maps have scores on leaderboards).

### Version

current master

### Logs

n/a

**Comment by JohnnyJ808** [comment]
> I haven't checked if stable behaves the same but this seems like a potential problem unless confirmed that stable also does this (but I doubt it, since these maps have scores on leaderboards).

On stable all those maps have scores on the leaderboards because all of them use NF to get around not being able to get enough health.
