### ISSUE TITLE
osu!catch editor very loud first hitsound when playtesting a map

### ISSUE THREAD

**Issue by Ttobas** [ppy/osu#26387]
### Type

Game behaviour

### Bug description

In the editor, if you playtest an osu!catch map after the beginning of the map, you'll get a very loud stack of hitsounds playing at once.

Video linked shows normal volume when playtesting from the beginning of the map, but a very loud sample when playtesting from the middle of the same map. **LOUD AUDIO WARNING**

_My guess is, since osu!catch doesn't need any user input, the game "skips" to the playtesting sample and catches dozens of notes at the same moment?_

Note: issue #20597 is similar but different from this issue.

### Screenshots or videos

https://github.com/ppy/osu/assets/18629016/f3bce691-6bbc-42c9-b48c-0503ecc015ba

### Version

2023.1231.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13830374/compressed-logs.zip)

**Comment by Ttobas** [comment]
My apologies, this is actually a duplicate of #22242 which as been closed referencing #20221.

You can close this if you think it's appropriate, but I think this issue should be prioritized over solving general "extreme lag" which doesn't prevent mapping, which this hitsound problem is actually very annoying.

**Comment by bdach** [comment]
Closing as duplicate
