### ISSUE TITLE
Editor doesn't change Break Periods when mapping

### ISSUE THREAD

**Issue by xDololow** [ppy/osu#26386]
### Type

Crash to desktop

### Bug description

When editing beatmap in lazer, break periods doesn't change at all. As you can see, the mapped section being shown as a break period at the bottom.

![image](https://github.com/ppy/osu/assets/26763912/fc8c0c67-fcfe-4215-9ca3-5599d79e3293)

And how it looks in stable editor.

![image](https://github.com/ppy/osu/assets/26763912/d6cdf214-58ca-4b84-8e98-a27ad30562bf)

Also, because of it, this happens:
![image](https://github.com/ppy/osu/assets/26763912/66b06590-72d0-418e-b019-43b4ad101feb)

Map was imported from stable to lazer once.

### Version

2023.1231.0

### Logs

Logs:
[compressed-logs.zip](https://github.com/ppy/osu/files/13829326/compressed-logs.zip)

**Comment by bdach** [comment]
#14330
