### ISSUE TITLE
Filtering beatmaps after null selection

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2638]
While fixing #2264 I never looked at what stable does. In stable the selection never goes to null, as in there's always some beatmap playing/displayed in the background, which is good in one situation.

A user might mistype while trying to further filter their selection, which in lazer would result in you losing your index (for a lack of better word) after being placed to random spot after your now correct filter. In stable the selection would just go back to the previous beatmap that was playing before the filter matched no beatmaps.

Example:
* You first search ``touhou``
* Go through half your library and then want to further refine the search term
* You now search for ``touhou imperishable`` but mistype imperishable
* In stable you are greeted with ``No matches found. Hit ESC to reset.`` and after correcting your mistake you can continue browsing your library from where you left off.
* In lazer you are greeted with ``no beatmaps avalibe! please load a beatmap!`` and after correcting your mistake are sent to random spot in your library and you have to find the spot you were at before. 

I propose that instead of random selection, last valid beatmap is used, unless that beatmap is now filtered in which case keep the current behaviour. Last valid beatmap could be just the last one, could be last 50 ones and the algorithm chooses the latest.

**Comment by peppy** [comment]
Yeah, this is something we may want to add back in the future. The current behaviour is there to keep things simple for the initial implementation.
