### ISSUE TITLE
Perfect scores/Sudden Death scores still upload when playing in multiplayer lobbies.

### ISSUE THREAD

**Issue by Kuina-chan** [ppy/osu#26396]
### Type

Behavior

### Bug description

Credit to @telkomo2 on discord, he was the person to find this.

Quote: "This defeat the purpose of PF"

### Screenshots or videos

https://cdn.discordapp.com/attachments/1122921187874455686/1192720122331271258/output3.mp4?ex=65aa1a2c&is=6597a52c&hm=28ec3b2e7b6a1b85c1a9dfa6cf277cfa36abc61e02d4b60d016dfe3a33b0183e&

Or

https://cdn.discordapp.com/attachments/1122921187874455686/1192723373936087060/output4.mp4?ex=65aa1d34&is=6597a834&hm=62e2b6c156a3436cc148f34cf021717a983e8775dea28dc168286008f2eb87cf&

### Version

2023.1231.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13839088/compressed-logs.zip)

**Comment by Kuina-chan** [comment]
Tho if I remember correctly, peppy once said something about all players in a multiplayer lobby should be play together at the same time till the end of the map. But the score should not upload to the server like that for display.

**Comment by bdach** [comment]
Should be fixed by the same change as https://github.com/ppy/osu/issues/26369
