### ISSUE TITLE
Replay music disappears when the song loops back to beginning while tabbed out

### ISSUE THREAD

**Issue by lunauii** [ppy/osu#26391]
### Type

Game behaviour

### Bug description

Was afking on skin editor gameplay replay when this happened. The music doesn't fix itself when tabbing back to osu!, but _does_ when seeking forwards or backwards. Could affect other areas that loop back to the beginning but not sure.
Tested on all base rulesets

Likely related to #25613.

### Replication Steps

1.  After navigating to the skin edtior, click the Gameplay scene.
2.  Seek song close to the end or wait until it is close to the end of the song.
3.  Tab out to a different application until the song starts to loop back (it does not have to finish going back to the start).
4.  Observe that the music has disappeared until seeking forwards or backwards.

### Screenshots or videos

https://youtu.be/4wGORWA8uqQ (Standard)
https://youtu.be/_cNiujj-UsQ (Mania)
https://youtu.be/Gpol4-oZ5a4 (Taiko)
https://youtu.be/_k6OIOZt6Yw (Catch the Beat)

### Version

2023.1231.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13834867/compressed-logs.zip)

**Comment by bdach** [comment]
#26022
