### ISSUE TITLE
Notification problem with beatmaps

### ISSUE THREAD

**Issue by sanswitch1** [ppy/osu#2640]
So when I was playing osu!lazer for the first time, it asks to import my beatmaps. I said yes and started playing some beatmaps while waiting. While in the middle of one of my beatmaps, the notification side popped out and told me all of the beatmaps were done importing, but the beatmap I was playing was still going, and I missed a few hits thanks to the problem. I couldn't get the notif side away until I clicked my mouse (annoyingly). This seems like a problem that can cause some issues when getting message notifs or other types. I suggest adding a notification symbol in the top right of the screen, telling you you have a notif depending on the type of notif (message, beatmap, etc.). 

This also works when getting messages from players and screenshotting the game while in a map.

![osu_2018-05-25_17-40-14](https://user-images.githubusercontent.com/20387223/40567309-c8891df4-6042-11e8-9a6e-05e54d4fcc60.jpg)

**Comment by Aergwyn** [comment]
In addition what about all the other overlays?
Right now it's not clear what should be allowed in play / pause / etc. ...
