### ISSUE TITLE
Resuming gameplay above a HitObject behaves like it was clicked

### ISSUE THREAD

**Issue by RatinFX** [ppy/osu#26413]
### Type

Game behaviour

### Bug description

Upon resuming via a key press, it plays the object's **Hitsound**, shows up on the **HitErrorMeter**, and increases the correct key in the **KeyCounter** - it should probably not do either.

Other than that it works like Stable and it's not registered as an actual _new_ click - which is the expected behavior.

### Screenshots or videos

eg. Slider
> https://github.com/ppy/osu/assets/38523955/5c36c6c8-4b5d-46ca-a955-d6a33f3dbb9f

- eg. HitCircle
> https://github.com/ppy/osu/assets/38523955/eac6688b-95de-4f5d-8b5d-5b8478d684f6

### Version

2023.1231.0

**Comment by bdach** [comment]
#9658
