### ISSUE TITLE
I sent a score with Perfect mode but it's not an SS

### ISSUE THREAD

**Issue by Jupunnn** [ppy/osu#26417]
### Type

Game behaviour

### Bug description

When we go into multiplayer with the obligatory "Perfect" mode, we don't die despite 100s and 50s, and our score is still sent.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/155381042/4fb4afbf-e65a-45dd-adab-850c20db277b)
![image](https://github.com/ppy/osu/assets/155381042/0b0a762a-b75e-4c6a-acfe-9d6ec5acea6d)
![image](https://github.com/ppy/osu/assets/155381042/1183075d-84b0-4399-9e3a-5b94b423ef02)
![osu_2024-01-06_22-42-21](https://github.com/ppy/osu/assets/155381042/9b36c643-2e49-4265-8b85-f336a2de53cf)
![osu_2024-01-06_22-42-46](https://github.com/ppy/osu/assets/155381042/4719ff8e-4b73-45ef-a952-87347e4fd198)

### Version

Lazer 2023.1231.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13851452/compressed-logs.zip)

**Comment by bdach** [comment]
#26396
