### ISSUE TITLE
Toolbar Ruleset Selector's ascending triangles are misaligned

### ISSUE THREAD

**Issue by RatinFX** [ppy/osu#26412]
### Type

Cosmetic

### Bug description

Off by ~1px at the bottom, this is more visible in the Main Menu with a bright background

### Screenshots or videos

https://github.com/ppy/osu/assets/38523955/9e3f38f0-1690-4c4d-9137-180c4bda34d0

### Version

2023.1231.0

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/4591
