### ISSUE TITLE
osu!mania scores not properly awarding pp

### ISSUE THREAD

**Issue by Gavator234** [ppy/osu#26425]
### Type

Game behaviour

### Bug description

Made a new PB on a map, https://osu.ppy.sh/beatmapsets/2040918#mania/4257769, and went to the website for a moment to review my ranking when I saw down there on the recent plays list that I had been awarded no pp for it. I hover with the mouse, it says 'only personal best scores award pp'. In osu!lazer, it shows the rewarded pp fine, and the resulting ranking is vastly different as a result, as I would suspect if this is an issue across the whole account.

I am aware that this may be deliberate (as in osu!web scores are exclusive to stable) but I couldn't find anything documenting this so I opened the issue to be sure.

Playing on Gentoo Linux, with the AppImage release

### Screenshots or videos

osu!lazer
![osu_2024-01-07_13-27-16](https://github.com/ppy/osu/assets/37884919/c61794e2-c4e6-4f3c-bbc6-edb84438027a)
![osu_2024-01-07_13-28-19](https://github.com/ppy/osu/assets/37884919/ca344860-7466-4e2f-a508-32ed7f8bb825)

osu!web
![Screenshot_20240107_133141](https://github.com/ppy/osu/assets/37884919/ca98e77d-e0a5-493e-9ab0-2d692bdf3b50)
![Screenshot_20240107_133226](https://github.com/ppy/osu/assets/37884919/cfd12f5a-4668-420c-be94-67d24817fddc)

### Version

2023.1231

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13854671/compressed-logs.zip)

**Comment by bdach** [comment]
You're checking the wrong instance of the website. Check `lazer.ppy.sh`. lazer plays will by design not show on `osu.ppy.sh`.

This confusion will hopefully go away sooner than later.

**Comment by Gavator234** [comment]
Ah, thanks for kindly clearing this up.
