### ISSUE TITLE
Back button in spectator screen overlapping with bottom-left side of progress bar 

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#26426]
### Type

Cosmetic

### Bug description

The hold-to-exit button on the bottom right is already there, so I wouldn't imagine the back button to be visible in the first place.

### Screenshots or videos

![CleanShot 2024-01-07 at 20 49 31](https://github.com/ppy/osu/assets/22781491/9d81b426-7a1b-4970-8e77-7554b5ce2db7)

### Version

2023.1231.0-lazer

### Logs

-

**Comment by bdach** [comment]
See for https://github.com/ppy/osu/pull/25770 for reason why button is there.

As a frequent contributor, I would expect you to generally know to look into the reason behind things by checking blame.

**Comment by frenzibyte** [comment]
> As a frequent contributor, I would expect you to generally know to look into the reason behind things by checking blame.

What purpose does the PR you linked serve for this issue thread? What does blame have anything to do with opening an issue thread about a blatant cosmetic issue here? I'm failing to see your point here sorry.

**Comment by bdach** [comment]
From OP:

> I wouldn't imagine the back button to be visible in the first place

It was made visible by https://github.com/ppy/osu/pull/25770 to fix https://github.com/ppy/osu/issues/25763. Which explains why the button is visible and would show in history/blame.

**Comment by Joehuu** [comment]
Is showing just the quit button on fail overlay a solution?

```diff
diff --git a/osu.Game/Screens/Play/FailOverlay.cs b/osu.Game/Screens/Play/FailOverlay.cs
index 210ae5ceb6..00dd072c4e 100644
--- a/osu.Game/Screens/Play/FailOverlay.cs
+++ b/osu.Game/Screens/Play/FailOverlay.cs
@@ -26,21 +26,20 @@ public partial class FailOverlay : GameplayMenuOverlay
 
         public override LocalisableString Header => GameplayMenuOverlayStrings.FailedHeader;
 
-        private readonly bool showButtons;
+        private readonly bool showRetryButton;
 
-        public FailOverlay(bool showButtons = true)
+        public FailOverlay(bool showRetryButton = true)
         {
-            this.showButtons = showButtons;
+            this.showRetryButton = showRetryButton;
         }
 
         [BackgroundDependencyLoader]
         private void load(OsuColour colours)
         {
-            if (showButtons)
-            {
+            if (showRetryButton)
                 AddButton(GameplayMenuOverlayStrings.Retry, colours.YellowDark, () => OnRetry?.Invoke());
-                AddButton(GameplayMenuOverlayStrings.Quit, new Color4(170, 27, 39, 255), () => OnQuit?.Invoke());
-            }
+
+            AddButton(GameplayMenuOverlayStrings.Quit, new Color4(170, 27, 39, 255), () => OnQuit?.Invoke());
 
             // from #10339 maybe this is a better visual effect
             Add(new Container
diff --git a/osu.Game/Screens/Play/SpectatorPlayer.cs b/osu.Game/Screens/Play/SpectatorPlayer.cs
index 2faead0ee1..d1404ac184 100644
--- a/osu.Game/Screens/Play/SpectatorPlayer.cs
+++ b/osu.Game/Screens/Play/SpectatorPlayer.cs
@@ -25,8 +25,6 @@ public abstract partial class SpectatorPlayer : Player
 
         private readonly Score score;
 
-        public override bool AllowBackButton => true;
-
         protected override bool CheckModsAllowFailure()
         {
             if (!allowFail)

```
https://github.com/ppy/osu/assets/35318437/590df6a8-d5e6-4379-b1b0-f47707230310

**Comment by bdach** [comment]
In principle I'm not opposed to the appearance. The code is a bit eh but probably passable.

That said does it actually work correctly? That's not shown on video and I'm a bit skeptical that it will.

**Comment by Joehuu** [comment]
Yes it does after testing. Comment here should be updated though, probably just removing the text inside the parenthesis:

https://github.com/ppy/osu/blob/e1a376c0a742d958399734683c8eb79631f37add/osu.Game/Screens/Play/GameplayMenuOverlay.cs#L47-L55

**Comment by bdach** [comment]
I'd keep the comment and guard as a safety, and probably allow setting the visibility of all three buttons via an `init` property or something? Not sure.
