### ISSUE TITLE
Graphic artifacts on Android 14

### ISSUE THREAD

**Issue by kilyabin** [ppy/osu#26431]
### Type

Game behaviour

### Bug description

**My Device: Google Pixel 6a**
**Android version: 14**
**Osu!lazer version: 2023.1231.0-lazer**

I have a graphic artifacts in game that prevent me from playing. I tried to use ANGLE, but this is crashing the game.
[Video with problem](https://www.youtube.com/watch?v=7r8zLs_S9LQ)

### Version

2023.1231.0-lazer

### Logs

Can't access android/data

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25189

**Comment by kilyabin** [comment]
> #25189

sorry. did't found this in search
