### ISSUE TITLE
Sliderend hitsounds sometimes not playing

### ISSUE THREAD

**Issue by Mrgglock** [ppy/osu#26430]
### Type

Game behaviour

### Bug description

This is related to random hitsounds playing / not playing after some time of use in the editor.

It seems tangentially related to #22693 and #24211, but this I think this is a new issue thread as the other issues talk about hitsounds appearing where they shouldn't be. This issue is for hitsounds not appearing where they should be. Reproducing any of these issues seem challenging - but we can reproduce the following issue:

Sliderend hitsounds not playing when they should be.

To reproduce this:
1) Open the editor
2) Make a very long slider
3) Set the SV to 0.1 so the slider can be very long and still on screen (probably not necessary)
4) Extend the slider by around 4 beats or so by clicking the last yellow node and bringing it further
5) Listen to the sliderend
Expected: Sliderend plays
Current: Sliderend doesn't play
((6)) Like all hitsound bugs, it is fixed by either leaving and restarting the editor, or moving far enough back to listen to the whole slider, of which the slider end will play again.

Note: This does not work if step 2 is not long enough. 140 beats of slider length seems enough, but ~2 beats is not enough to reproduce this bug.

### Screenshots or videos

https://github.com/ppy/osu/assets/9843579/da2e08ad-2d06-462e-8fa1-7988ee20d87a

### Version

Lazer 2023.1231.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13858137/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/10455 probably
