### ISSUE TITLE
Small artifacts shows up w/ missed slider ticks

### ISSUE THREAD

**Issue by kvietcong** [ppy/osu#26448]
### Type

Cosmetic

### Bug description

This issue showed up a few weeks ago, but these weird red lines started showing up on what seems to be missed slider ticks. It seems to be half of an x (slated red line). I thought it was my skin but it happens in the official skin too (albeit much less noticeable b/c it's a smaller line that appears).

The video is me triggering the behavior by failing on a slider heavy map as that seems to be the only reliable way for it to show up. It pops up in gameplay intermittently though.

This also happens w/ both OpenGL and Direct backends.

### Screenshots or videos

https://github.com/ppy/osu/assets/32186663/64061c94-40a5-49be-a743-eccfeeaaa341

### Version

2023.1231.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13869192/compressed-logs.zip)

**Comment by peppy** [comment]
Yes, we show misses of ticks and ends now. It's not an artifact. You can skin it to suit your skin. Please see the changelog.
