### ISSUE TITLE
Optimizing the osu!lazer's Performance

### ISSUE THREAD

**Issue by ZeroSanDew** [ppy/osu#2645]
Hello Devs, I've got a problem about the performance of the game, osu!lazer. Since my PC is kinda bad, the game lags always. So can you at least optimize the graphics for the people who had a bad PC like me?

**Comment by AlFasGD** [comment]
The game is still at its early development stages; this is surely planned to be a thing, yet you have to wait until other core functionality is implemented and provided.

**Comment by peppy** [comment]
we are making ongoing improvements to performance, and are well aware it is below requirements currently
