### ISSUE TITLE
Sliders can be moved outside playfield

### ISSUE THREAD

**Issue by WhiteRedWolf** [ppy/osu#2646]
The Sliders can be Placed whereever you really want, and it should not behave like that to avoid breaking the rule of thew sliders being onscreen in 4:3 Aspect Ratios, i think you guys are aware of this but its something to fix anyway.
![screenshot_120](https://user-images.githubusercontent.com/33634370/40575470-d313453a-60e5-11e8-87c5-3f158386e5d0.png)
![screenshot_121](https://user-images.githubusercontent.com/33634370/40575474-e44c9702-60e5-11e8-9b65-b1a9867b8aa2.png)

**Comment by peppy** [comment]
Editor is still in a very raw state.
