### ISSUE TITLE
I can't login on osu!lazer

### ISSUE THREAD

**Issue by Akeeru** [ppy/osu#2648]
osu!lazer 2018.522.0

`26.05.2018 17:16:04: We just went Connecting!
26.05.2018 17:16:15: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 11 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
26.05.2018 17:16:25: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
26.05.2018 17:16:26: Processing response from https://osu.ppy.sh/oauth/token failed with System.ArgumentNullException: The value can not be zero.
26.05.2018 17:16:26: The name of the parameter: value
26.05.2018 17:16:26: w Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
26.05.2018 17:16:26: w Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
26.05.2018 17:16:26: w osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse()
26.05.2018 17:16:26: w osu.Framework.IO.Network.WebRequest.Complete(Exception e).
26.05.2018 17:16:26: Login failed!
26.05.2018 17:16:26: We just went Offline!
`

**Comment by AlFasGD** [comment]
Unless more context is provided, this may mainly happen due to poor internet connection, or server maintenance.

**Comment by Akeeru** [comment]
But on normal osu i can login.

**Comment by peppy** [comment]
Could you please provide your osu! username?

**Comment by Joehuu** [comment]
Closing as stale and probably your end. @Akeeru can you please try again on latest version and reopen if it persists?

**Comment by peppy** [comment]
Would be interested in seeing what the actual response is in this case. Likely an ISP or proxy intercept or similar.
