### ISSUE TITLE
osu!mania editor "flashes" when adding a note

### ISSUE THREAD

**Issue by xdi1** [ppy/osu#26493]
### Type

Game behaviour

### Bug description

In mania editor, screen flashes when adding a note. It seems this action also triggers multiple random key presses. Not sure if two things are related.

### Screenshots or videos

https://github.com/ppy/osu/assets/47128831/f00bdb3d-805d-43d7-8352-0872b0389a77

### Version

latest development build

### Logs

[runtime] 2024-01-13 07:18:29 [debug]: MouseDownEvent(Left) handled by NotePlacementBlueprint.
[runtime] 2024-01-13 07:18:29 [debug]: Pressed (Key10) handled by Column.
[runtime] 2024-01-13 07:18:29 [debug]: Pressed (Key1) handled by Column.
[runtime] 2024-01-13 07:18:29 [debug]: Pressed (Key8) handled by Column.
[runtime] 2024-01-13 07:18:29 [debug]: Pressed (Key6) handled by Column.
[runtime] 2024-01-13 07:18:29 [debug]: Pressed (Key5) handled by Column.
[runtime] 2024-01-13 07:18:30 [debug]: MouseDownEvent(Left) handled by NotePlacementBlueprint.
[runtime] 2024-01-13 07:18:30 [debug]: Pressed (Key10) handled by Column.
[runtime] 2024-01-13 07:18:30 [debug]: Pressed (Key1) handled by Column.
[runtime] 2024-01-13 07:18:30 [debug]: Pressed (Key8) handled by Column.
[runtime] 2024-01-13 07:18:30 [debug]: Pressed (Key6) handled by Column.
[runtime] 2024-01-13 07:18:30 [debug]: Pressed (Key5) handled by Column.

**Comment by frenzibyte** [comment]
This is a side effect of the editor becoming frame-stable now (see https://github.com/ppy/osu/pull/26382). cc @peppy for input on this one (if required).

**Comment by bdach** [comment]
explain why

**Comment by frenzibyte** [comment]
Never mind, I misunderstood the original issue.
