### ISSUE TITLE
osu! can submit a score with a mod belonging to a different ruleset

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#26498]
### Type

Game behaviour

### Bug description

Noticed while looking at https://github.com/ppy/osu/issues/26463.

This is quite bad, as it could lead to users finding ways to get the game into a bugged state and submit scores with difficulty-increasing mods that are not taking effect in game (due to being of the wrong ruleset).

In the linked issue thread, when applying the steps shown in the [video](https://youtu.be/vVa_nXOoZqo), the player is able to start a gameplay session on osu! ruleset with flashlight and hidden being mod instances of taiko ruleset, leading to them becoming ineffective in gameplay.

There should be checks inside `SubmittingPlayer` to not even create a score token when there are mods of an incorrect ruleset selected, but the hard part is defining each mod with the ruleset it belongs to.

cc @ppy/team-client for opinions on how this can be approached.

### Screenshots or videos

-

### Version

-

### Logs

-

**Comment by bdach** [comment]
> the hard part is defining each mod with the ruleset it belongs to

https://github.com/ppy/osu/blob/3d3f58c2523f519504d9156a684538e2aa0c094c/osu.Game/Rulesets/Ruleset.cs#L60-L77

am i missing something?

**Comment by frenzibyte** [comment]
I failed to notice the existence of this property. So you are proposing that it should be used to check whether the mod belongs to the current ruleset? Sounds good.
