### ISSUE TITLE
Direct3D 11 causes serious performance issues

### ISSUE THREAD

**Issue by wawdili** [ppy/osu#26494]
### Type

Performance

### Bug description

OSU defaults to Direct3D 11. (On PC)
But it will lead to a significant decrease in game frame rate.

If it were OpenGL, there wouldn't be such a problem, and if it were in the past, there wouldn't have been this problem either.
Restarting the game will not improve the situation. Both CPU and GPU are in an underloaded state.

The 'OSU' running on my computer sometimes reports unknown errors, but I ignore them.

**have more detailed content?** I don't know what information to collect because I don't know what is related to it. This problem happened suddenly.

### Screenshots or videos

Game interface
[2024-01-13 16-06-04_Sav1.zip](https://github.com/ppy/osu/files/13927397/2024-01-13.16-06-04_Sav1.zip)

Playing
[2024-01-13 16-31-38_Sav1.zip](https://github.com/ppy/osu/files/13927443/2024-01-13.16-31-38_Sav1.zip)

### Version

2023.1231.0

### Logs

[log.zip](https://github.com/ppy/osu/files/13927323/log.zip)
The issue still exists after updating to '2023.1231.0'.

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25755

opengl is not going away in the near future, if it helps you, then please switch to it for now

**Comment by wawdili** [comment]
> #25755
> 
> OpenGL 在不久的将来不会消失，如果它对您有帮助，那么请暂时切换到它

I don't think this issue has much to do with #25755, as I saw that my OSU has a **15ms ResetDraw** (in playing), while the Work time is only about 13ms.

And it always maintains 38fps, not dynamically changing like #25755. It's like the game's target is running at 38fps (which happens to be rounding off half of my monitor's refresh rate).

**Comment by bdach** [comment]
try fullscreen in that case (*not* windowed, *not* borderless).

**Comment by wawdili** [comment]
> try fullscreen in that case (_not_ windowed, _not_ borderless).

That has no effect, and sometimes full screen situations can be even worse. That video has specific content.

**Comment by peppy** [comment]
15ms "resetdraw" is from attempted frame sync. lower frame rates are not actually a bad thing if frames are delivered timely. are you actually seeing issues, or just looking at the numbers?

**Comment by wawdili** [comment]
> 15ms "resetdraw" is from attempted frame sync. lower frame rates are not actually a bad thing if frames are delivered timely. lower cpu and gpu usage is also expected and one of our goals.
> 
> are you actually seeing issues, or just looking at the numbers?

I'm not very sure, because that happened while playing Beatmap. Usually, in full screen mode, it's a 15ms SwapBuffer, and the window mode is a 15ms Sleep (Update is 0.4ms work). Occasionally, it suddenly changes to 15ms Work. (These '15ms' are not accurate as they may sometimes be higher or lower)

The content of 'advanced frame/thread statistics' is like this.

I see the number, Draw only has 26fps, unless using OpenGL.

**Comment by peppy** [comment]
Again, the 15ms is from frame sync to 60hz.
