### ISSUE TITLE
Black Screen at song select

### ISSUE THREAD

**Issue by Chara-Reborn** [ppy/osu#265]
Not really sure what to add on but this is exactly what's happening on my end.
https://my.mixtape.moe/gyhdal.mp4 for the video of what's happening

**Comment by MeepMu** [comment]
If anyone encounters this in the future, here is how to fix it:
osu! doesnt really have any beatmaps from default, so you have to drag a beatmap file onto the exe file (located in osu.Desktop/bin/debug or release) when you do that, osu! may crash, but next time you start it, the select screen should have the beatmap that you loaded.
