### ISSUE TITLE
Game cannot start

### ISSUE THREAD

**Issue by RBQcat** [ppy/osu#26506]
### Type

Crash to desktop

### Bug description

After I updated my game on Android pad to 2024.113, the game showed a black screen when opened.

### Version

2024.113

### Logs

[1705165128.runtime.log](https://github.com/ppy/osu/files/13928925/1705165128.runtime.log)

**Comment by WhatDamon** [comment]
same as me
all **three renderers** in total, OpenGL and Vulkan, **failed to initialize**
