### ISSUE TITLE
Add a cap to the amount of characters you can type in any textbox

### ISSUE THREAD

**Issue by xRasea** [ppy/osu#2651]
On my journey to find minimal details or ways to crash the new client by doing stupid stuff I found it extremely easy to make lazer freeze and crash by just copy-pasting large (1000 characters) amounts of text. This and many other issues of the same caliber may be solved by adding a cap. 

![osu _2018-05-27_14-10-57](https://user-images.githubusercontent.com/35492066/40585763-3b8afff4-61b8-11e8-8d47-7ce34b30dac5.png)
![osu _2018-05-27_14-12-25](https://user-images.githubusercontent.com/35492066/40585764-3dc0c5ba-61b8-11e8-8cde-45151cae85ab.png)

**Comment by Frontear** [comment]
Mind if I ask, could this just be a processing error, as copy-pasting vs typing. Is this kind of thing reproducible by just holding down 1 key, rather than copy pasting?

**Comment by xRasea** [comment]
In 100 seconds of letting one keycap pressed my update frames got down from 2200 to 160, and this being in the title screen, which performs way better

**Comment by EVAST9919** [comment]
Fixed, I suppose
