### ISSUE TITLE
current release has no apk package

### ISSUE THREAD

**Issue by junejsjsjdjjdjdjdjdj** [ppy/osu#26529]
### Type

Crash to desktop

### Bug description

can a package be built for apk as there is currently no apk package for the latest version of osu

### Version

latest

### Logs

no logs 
```[tasklist]
### Tasks
```

**Comment by Gabixel** [comment]
Some issues are going on with the Android build, so no APK for now since it's not the highest priority for the upcoming hotfix. Be patient!

**Comment by bdach** [comment]
hotfix is coming shortly, it should include an android release.
