### ISSUE TITLE
Some textures are loaded during `SoloPlayer` instead of `PlayerLoader`, creating big stutters on slow disks

### ISSUE THREAD

**Issue by adryzz** [ppy/osu#26535]
### Type

Performance

### Bug description

Some textures and skin elements get loaded during `SoloPlayer` instead of `PlayerLoader`, creating big stutters on slow disks.

for example, in mania, the `mania-key*`,  `mania-hit*`, `mania-note*` and a few more get loaded in the player loader, while for example `score-*`, a few `mania-hit*` and a few font textures get loaded during the actual gameplay, adding stutters in the first play of the session when for example running on a spinning drive

as per [discord](https://discord.com/channels/188630481301012481/188630652340404224/1196249283649867858), it appears to be known, but searching both the issue tracker and Q&A discussion listing, i couldn't find anything matching.

adding a quick log line at https://github.com/ppy/osu-framework/blob/92db55a52742047b42c0b4b25327ce28bd991b44/osu.Framework/Graphics/Textures/TextureStore.cs#L223 shows texture loading to be the culprit.

[runtime.log](https://github.com/ppy/osu/files/13933779/1705277270.runtime.log)
```
[...]
2024-01-15 00:08:17 [verbose]: 📺 OsuScreenStack#168(depth:5) suspended PlayerLoader#387 (waiting on SoloPlayer#154)
2024-01-15 00:08:17 [verbose]: 📺 OsuScreenStack#168(depth:6) entered SoloPlayer#154
2024-01-15 00:08:17 [verbose]: GameplayClockContainer seeking to 0
2024-01-15 00:08:18 [verbose]: Loading texture score-0@2x from disk.
2024-01-15 00:08:18 [verbose]: Loading texture score-x@2x from disk.
2024-01-15 00:08:18 [verbose]: Loading texture score-5@2x from disk.
2024-01-15 00:08:18 [verbose]: Loading texture score-1@2x from disk.
[...]
```

### Screenshots or videos

https://github.com/ppy/osu/assets/46694241/73e47e49-7cca-424a-aeb3-4ade06f46ec7

### Version

latest master branch

### Logs

[1705279607.network.log](https://github.com/ppy/osu/files/13933718/1705279607.network.log)
[1705279607.runtime.log](https://github.com/ppy/osu/files/13933719/1705279607.runtime.log)
[1705279607.performance.log](https://github.com/ppy/osu/files/13933720/1705279607.performance.log)
[1705279607.input.log](https://github.com/ppy/osu/files/13933721/1705279607.input.log)

**Comment by peppy** [comment]
Please attach your skin.

**Comment by KoleckOLP** [comment]
This also happens for me in osu standard.

Here is my skin:
[Oduby-pon_unfollowed.osk.zip](https://github.com/ppy/osu/files/13936221/Oduby-pon_unfollowed.osk.zip)

**Comment by peppy** [comment]
@KoleckOLP if you mean the counters, then that is fixed in #26536.

I'm more interested in the osu!mania skin to fix the other reported cases, which are specific to that ruleset.

**Comment by adryzz** [comment]
this is not skin specific, but here it is

(had to upload it on my server as GitHub's max file size is 32MB
https://paste.nihil.gay/paste/0faed21a-6893-476b-95a3-558f9559b203.osk

**Comment by bdach** [comment]
Not sure this is all:

```
[performance] 2024-01-15 12:04:53 [verbose]: Resource KeyCounter/key-up:wrap-0-0 was retrieved from a TextureStore on a non-background thread.
[performance] 2024-01-15 12:04:53 [verbose]: Resource Resources/Textures/KeyCounter/key-up was retrieved from a DllResourceStore on a non-background thread.
[performance] 2024-01-15 12:04:53 [verbose]: Resource Textures/KeyCounter/key-up was retrieved from a DllResourceStore on a non-background thread.
[performance] 2024-01-15 12:04:53 [verbose]: Resource Resources/Textures/KeyCounter/key-up.png was retrieved from a DllResourceStore on a non-background thread.
[performance] 2024-01-15 12:04:53 [verbose]: Resource Textures/KeyCounter/key-up.png was retrieved from a DllResourceStore on a non-background thread.
[performance] 2024-01-15 12:04:53 [verbose]: Resource KeyCounter/key-glow:wrap-0-0 was retrieved from a TextureStore on a non-background thread.
[performance] 2024-01-15 12:04:53 [verbose]: Resource Resources/Textures/KeyCounter/key-glow was retrieved from a DllResourceStore on a non-background thread.
[performance] 2024-01-15 12:04:53 [verbose]: Resource Textures/KeyCounter/key-glow was retrieved from a DllResourceStore on a non-background thread.
[performance] 2024-01-15 12:04:53 [verbose]: Resource Resources/Textures/KeyCounter/key-glow.png was retrieved from a DllResourceStore on a non-background thread.
[performance] 2024-01-15 12:04:53 [verbose]: Resource Textures/KeyCounter/key-glow.png was retrieved from a DllResourceStore on a non-background thread.
```

```
[performance] 2024-01-15 12:04:56 [verbose]: Resource cursor-ripple@2x:wrap-0-0 was retrieved from a TextureStore on a non-background thread.
[performance] 2024-01-15 12:04:56 [verbose]: Resource Resources/Skins/Legacy/cursor-ripple@2x was retrieved from a DllResourceStore on a non-background thread.
```
