### ISSUE TITLE
Replays, stable site, and lazer site, showing different results than whats shown on local score

### ISSUE THREAD

**Issue by chandler14362** [ppy/osu#26534]
### Type

Game behaviour

### Bug description

Watching a replay shows different results than what is on my local leaderboard. Max combo, great, ok, meh, miss, slider tick, and slider end are all different than the saved local score. I have watched the replays on 1x speed and 2x speed, both have the issue. The replay is consistently showing higher accuracy. I have tested this with replays from today running on the latest lazer version and with replays from almost a month ago. Both have the issue. The scores under recent performances on the lazer site are also slightly different than whats shown on my local leaderboard, the reported scores have slightly higher acc. Looking at the recent performances on the stable site is also showing different accuracy, however, this accuracy is lower. The scores I have looked in to only have dt mod on. I am not using classic scoring. 

### Screenshots or videos

Score viewed from my local leaderboard:
![osu_2024-01-14_14-53-29](https://github.com/ppy/osu/assets/5816171/c7363001-502e-4dff-9183-33f5c9598893)

Score after watching a 2x speed replay:
![osu_2024-01-14_16-48-21](https://github.com/ppy/osu/assets/5816171/e0b756d0-8a51-493d-b1c8-ef73f254b743)

Score after watching a 1x speed replay:
![osu_2024-01-14_16-54-16](https://github.com/ppy/osu/assets/5816171/7e784305-b00e-4382-9353-d6f15bc667f8)

Score under recent performances on lazer site:
![firefox_2024-01-14_17-20-28](https://github.com/ppy/osu/assets/5816171/85779858-0609-402d-89ac-959579b5be37)

Score under recent performances on stable site:
![firefox_2024-01-14_17-20-47](https://github.com/ppy/osu/assets/5816171/44ce477d-6ea5-4be1-82d8-cbc55afa382b)

Score replay:
[chandler14362 playing Fleshgod Apocalypse - The Violation (Mazzerin) [pishi_s Extra] (2024-01-14_14-53).zip](https://github.com/ppy/osu/files/13933309/chandler14362.playing.Fleshgod.Apocalypse.-.The.Violation.Mazzerin.pishi_s.Extra.2024-01-14_14-53.zip)

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13933293/compressed-logs.zip)

**Comment by bdach** [comment]
stable site accuracy is mostly irrelevant (stable site calculates accuracy locally, in a way that is incorrect for lazer scores, this will be fixed once leaderboards go live).

Replay playback accuracy has like fifteen issues opened about it already.
