### ISSUE TITLE
Ingame song explorer showing totally different result than Web, sometimes none

### ISSUE THREAD

**Issue by TomBerriot** [ppy/osu#26533]
### Type

Explorer Feature - Not expected results (0 results)

### Bug description

When searching in Explorer, results are not at all same than on web, even get 0 results for very popular licences such as Idolmaster, Stray Kids...

### Screenshots or videos

![osu!_2024-01-14_22-59-02](https://github.com/ppy/osu/assets/11588007/0c7a2915-4247-4ff0-bb01-51c24c08f6b5)
![firefox_2024-01-14_23-03-12](https://github.com/ppy/osu/assets/11588007/4509a8ce-b9fd-4b77-b9c5-e7a270817d47)

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13933248/compressed-logs.zip)

**Comment by Ladwick** [comment]
Disable the Featured Artist filter.

**Comment by TomBerriot** [comment]
Ah, i'll try that, the UI seemed more like a link unlike other filters 🤔
Thank you 👋

**Comment by TomBerriot** [comment]
On the site, it's the yellow as well though ? 🤔🤔

**Comment by bdach** [comment]
It's always yellow. Filter is active if underlined.

See also: https://github.com/ppy/osu/issues/22009.
