### ISSUE TITLE
Tournament client doesn't always fetch beatmap backgrounds

### ISSUE THREAD

**Issue by JuanM4T** [ppy/osu#26550]
### Type

Cosmetic

### Bug description

Referencing #24993 because it was never actually fixed, or so it seems.

Basically, maps' backgrounds seem not to be fetched correctly in tourney client, leading to a plain dark image instead of the actual map background. Every stat on the map seems to be picked up and being correctly shown except for backgrounds. 

For me it worked until reinstalling windows and reinstalling lazer (having copied and pasted lazer data folder) but it generally _seems_ to happen on every new install of lazer.

I tried deleting cache, as some people previously suggested in a discord server dedicated to tournaments, to no avail.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/52723130/2d663a53-1bd9-4b1e-a174-dec4fd3f8cb1)
![image](https://github.com/ppy/osu/assets/52723130/f1f60a34-be34-4833-ae73-a9fb39edc0c9)

### Version

2024.114.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13943025/compressed-logs.zip)

**Comment by peppy** [comment]
The weird part is, this has never happened to us on world cup streams, and I can't repro locally.

---

Your log files are full of initialisation errors from rulesets that can't load. I'm not sure this is related, but I'd ask that you remove those as a starting point (Karaoke / Gamebosu / Yoso).

Also I'm not really seeing any tournament usage in the log files. Did you export the logs just after reproducing the issue, or should I be looking further back in log history?

**Comment by JuanM4T** [comment]
I do believe rulesets error don't interfere with this as I already had those rulesets erroring out in startup a few months ago, however I'll try and remove them momentarily and send logs once again.

Adressing that, as I could not find any way to export logs from the tournament client I closed it and open regular lazer then export. I think it should be there tho I'll remove all extra rulesets and try to reproduce the bug again.

After removing the rulesets (no more error notifications when opening normal lazer) the same still occurs. As mentioned in #24993, mappool tab loads just fine but it's both gameplay and showcase which show this anomaly. I guess it's the same fetch method for the last two and different for mappool tab?
![image](https://github.com/ppy/osu/assets/52723130/3b5c851b-b581-4c80-9e41-1d65de922550)
![image](https://github.com/ppy/osu/assets/52723130/421c49b4-359b-4860-a20e-7e42607fde01)
[compressed-logs.zip](https://github.com/ppy/osu/files/13948124/compressed-logs.zip)

**Comment by peppy** [comment]
Does resizing the window randomly help at all?

**Comment by JuanM4T** [comment]
That's weird... It just worked on gameplay, then showcase still showed dark bg, changed beatmap, then dark again on both, went on showcase resized like crazy a few times and it now seems to pick up every map in both tabs

**Comment by peppy** [comment]
So resizing does fix? There's a potential issue with things not loading due to floating point precision and masking if so.

It would be helpful to confirm that in a broken state, if doing nothing but resizing the window (not changing screens) fixes the issue or not.

**Comment by JuanM4T** [comment]
It seems to do the trick, and it also seems like some resolutions cause this more often, for example, setting height to 800 seems to break the bg consistently as shown in this video:

https://github.com/ppy/osu/assets/52723130/e58c22d8-8e1f-4775-b53c-bc48b01cd97d
