### ISSUE TITLE
Traceable mod doesn't honour the SliderBorder setting in skin.ini

### ISSUE THREAD

**Issue by koopafou** [ppy/osu#26556]
### Type

Cosmetic

### Bug description

I'm using a legacy skin for NoMod that attempts to replicate Traceable but in classic osu!.
My skin.ini contained the following before export :
```[General]
Author: Lesbea
Version: latest
AllowSliderBallTint: 1
SliderStyle: 1
[Colours]
Combo1: 255,255,255
SliderTrackOverride: 16,0,0
SliderBorder: 120,0,0
[Fonts]
HitCircleOverlap: 170
```
My approach circle is half-size and cyan tinted, this is how it looks with EZ if I make the hitcircles invisible (except slider heads which are greenish but ignore that) :
![20240116-020825](https://github.com/ppy/osu/assets/1556504/80491c82-fca0-4c8c-8f8f-4096122d134a)

And this is how it looks with EZTC :
![20240116-020807](https://github.com/ppy/osu/assets/1556504/041287a1-23f8-431c-80e4-f6b7f33133d8)

Sometimes the mod will display the first slider with the correct colour, but after that it's always using the combo colour, which is white in my example.

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13944810/compressed-logs.zip)

**Comment by peppy** [comment]
that's how the mod works. the first one will use the correct colour if you have the "make first object more visible" setting on.

**Comment by koopafou** [comment]
The mod says "put your faith in the approach circles", why is preventing me from toning down the slider visibility supposed to be the correct behaviour ?
