### ISSUE TITLE
Mouse wheel deltas are wrong at borders / alt-tab with raw input enabled

### ISSUE THREAD

**Issue by LovelyA72** [ppy/osu#2658]
move cursor out the upper border then move back will display the volume control for a second.
Version:2018.526.0

**Comment by peppy** [comment]
Could you please share your OS, whether you have raw input on or off and which input device you're using?

**Comment by LovelyA72** [comment]
quick update: I just updated my osu! to 2018.526.0 and it does not have this issue. I'll need to verify with him tonight. Maybe it's just an issue with his OS?

**Comment by peppy** [comment]
If they are on the latest release and still reproducing this, it is likely due to the specific input setup they have. That said, the build you mention did attempt to fix this once and for all, so not sure.

**Comment by LovelyA72** [comment]
I tried to reproduce on his device. But i failed:( The volume control are now showing correctly. I think we can close this issue for now.

**Comment by peppy** [comment]
I've since been able to reproduced this and we are tracking it for imminent fixing.
