### ISSUE TITLE
ColourHitErrorMeter resets after a pause

### ISSUE THREAD

**Issue by immorrtalz** [ppy/osu#26596]
### Type

Cosmetic

### Bug description

Taiko mode
ColourHitErrorMeter instantly becomes empty right after I press and release the "continue" button in the pause menu
It seems to be just a visual thing

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/61843974/2f926b9a-f629-4f1d-8d72-8fb53612dc7d)

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13962327/compressed-logs.zip)

**Comment by bdach** [comment]
This is happening because `MasterGameplayClockContainer` apparently seeks when resuming:

https://github.com/ppy/osu/blob/6a8a45bb1364ec42308daf01f38a1e1b1578d826/osu.Game/Screens/Play/MasterGameplayClockContainer.cs#L153-L157

which causes the clear.

**Comment by peppy** [comment]
I have some in-progress changes which remove that block of code, so stay tuned.
