### ISSUE TITLE
Mac: Not able to scroll in results screen

### ISSUE THREAD

**Issue by LikiaBili** [ppy/osu#26592]
### Type

Game behaviour

### Bug description

Not able to scroll down using trackpad (two fingers swipe down) in the results screen in mac, only able to scroll horizontally
like my mac book air's screen is small, so it can't display the full game result in my screen, so i need to scroll it down

### Screenshots or videos

https://github.com/ppy/osu/assets/103659676/d8ad41aa-d87b-4712-b2f3-ef97867fdb70

### Version

Apple Silicon 2024.114.0

### Logs

No logs.

**Comment by peppy** [comment]
Thanks for reporting this.

The results screen will be getting a redesign which will probably resolve this. Until then, you can adjust your UI scale downwards so everything fits on the screen, or you can drag to scroll upwards.
