### ISSUE TITLE
Mod selection screen sometimes doesn't show up

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#2662]
Somehow, it's possible to get song select into a state where pressing the mods button does nothing. Focus contention is triggered but the overlay doesn't show.

Not entirely sure on the replication case yet.

**Comment by Joehuu** [comment]
Does this still happen? Never noticed this problem.

**Comment by peppy** [comment]
I haven't ever seen this happen

**Comment by smoogipoo** [comment]
Fair to assume this is probably an old issue and has since been fixed.
