### ISSUE TITLE
Flashlight Dim Flickers On Sliders

### ISSUE THREAD

**Issue by SevenEnd7** [ppy/osu#26624]
### Type

Game behaviour

### Bug description

Not related to #26525 (don't know if #26576 would affect this issue). It's hard to find what maps trigger this issue, but if you can a map it's consistent through playing and auto every time. I found the issue while playing [this](https://osu.ppy.sh/beatmapsets/236292#osu/553247) map with HRFL. Interestingly, using random mod does change where the sliders have these issues (I used 1193067784 as the seed). 

Note: playing the easy diff without hardrock or flipping the map as if you were playing hardrock doesn't cause this issue. [this map with just FL triggers the same issue 40 seconds in for example.](https://osu.ppy.sh/beatmapsets/53923#osu/164183)

### Screenshots or videos

[link if the video bitrate is too low](https://cdn.discordapp.com/attachments/423268473838370816/1197651083447779480/2024-01-18_13-05-45.mp4?ex=65bc0a7d&is=65a9957d&hm=ff3de26f22b434bfb895eb8d7d1e1ff11fdf52f4a7ce92f8b11813c33a401980&)

https://github.com/ppy/osu/assets/69742831/368ad092-7f76-4a9f-b82c-2b909f9441a6

at 0:32, notice how the slider dim does trigger, but immediately undims for the rest of the slider. Happens again at 0:43 and 0:48. Watching with auto has the same issues and does this on the same sliders. 

### Version

2024.114.0-lazer

### Logs

[compressed-logs (1).zip](https://github.com/ppy/osu/files/13981793/compressed-logs.1.zip)

**Comment by bdach** [comment]
Both maps are fixed by https://github.com/ppy/osu/pull/26576 (I checked).
