### ISSUE TITLE
Pressing space while searching for collection starts gameplay

### ISSUE THREAD

**Issue by JacksonChen666** [ppy/osu#26654]
### Type

Game behaviour

### Bug description

1. Open the collections selector drop down
2. Press space
3. Accidentally start gameplay

In a real scenario where you have a collection with a space character in the collection name, typing the full collection name will start the gameplay. Definitely not what the user wanted.

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14001401/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25769
