### ISSUE TITLE
DT multiplier shows incorrectly in the UI

### ISSUE THREAD

**Issue by Orlandinum04** [ppy/osu#26651]
### Type

UI issue

### Bug description

if i change the value it shows the correct value, but everytime i select it it shows x1.10 instead of x1.50.

### Screenshots or videos

![bpng](https://github.com/ppy/osu/assets/57011310/8983c41c-f3b6-49f0-8992-b0c6fa7550d6)
![apng](https://github.com/ppy/osu/assets/57011310/030e2e0e-6011-4e72-a2ec-acf3cb32fb9f)

### Version

2024.114.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14001081/compressed-logs.zip)

**Comment by bdach** [comment]
Nothing is incorrect here. "Score multiplier" is not the same thing as the rate of speedup of the audio track.
