### ISSUE TITLE
OSU Lazer DT/NC 1.01 -- 1.49 calculate forever / never gives pp

### ISSUE THREAD

**Issue by Mr1celand** [ppy/osu#26650]
### Type

Game behaviour

### Bug description

When you use DT/NC  on lazer and pick between 1.01x to 1.49 the score will calculate forever and never give you the pp. Is this a feature or a bug. because im not sure if Different Dt selections are meant to give pp. 

### Screenshots or videos

![osu_2024-01-20_23-37-12](https://github.com/ppy/osu/assets/157278290/ecb89212-5253-40da-90db-ba511fbbd8e5) 
![osu_2024-01-20_23-37-12](https://github.com/ppy/osu/assets/157278290/075ef038-94b2-4413-b5b7-cc059a103878)
![osu_2024-01-20_11-02-55](https://github.com/ppy/osu/assets/157278290/7cba13e1-49d9-4057-983b-e306a82ce63c)
 

### Version

The newest

### Logs

no logs just screenshot

**Comment by bdach** [comment]
Non-default speeds will not be giving pp. This is intentional for now.
