### ISSUE TITLE
Sliders causing game to stutter

### ISSUE THREAD

**Issue by SomeoneSomewher** [ppy/osu#26675]
### Type

Performance

### Bug description

Game stutters / drops in frames when displaying a slider with many control points in game and in replays. 
When trying to open in editor it becomes unusable.
beatmap: 
https://osu.ppy.sh/beatmapsets/1746664#osu/3598398

### Screenshots or videos

https://github.com/ppy/osu/assets/66387749/80dc8c35-df40-4930-bedd-e7aa7f1adda5

https://github.com/ppy/osu/assets/66387749/28bff7d0-b1fe-4bed-a3a1-58fb8f18dda1

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14016017/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21495
