### ISSUE TITLE
Osu Lazer Dosent Shows Up

### ISSUE THREAD

**Issue by XronaldCpX** [ppy/osu#2668]
Hello, My Username Is ronaldCp

The Problem I have is , I downloaded Osu lazer Update,

so , i click osu lazer icon and nothing happens.

i dont know what is this error but i need to fix it.

please whit love an entire process of writtin ,

- ronaldCp

**Comment by XronaldCpX** [comment]
how i get it ?

**Comment by LovelyA72** [comment]
For me, the path of log file is
`C:\Users\think\AppData\Roaming\osu\logs`
You can find your logs at 
`C:\Users\<user name here>\AppData\Roaming\osu\logs`
if you are using a ppy official release.

**Comment by XronaldCpX** [comment]
i found it , so what i gonna do now?

**Comment by alexpado** [comment]
Drag and drop file on the text area, post it and voilà

**Comment by XronaldCpX** [comment]
text area?

**Comment by XronaldCpX** [comment]
what is that?

**Comment by XronaldCpX** [comment]
[runtime.log](https://github.com/ppy/osu/files/2050185/runtime.log)

**Comment by LittleEndu** [comment]
duplicate of #2675
Solution is to delete ``client.db`` as mentioned in that issue

**Comment by XronaldCpX** [comment]
OMGGG THX SO SO MUCH I TESTED OSU LAZER THX YOOUUUU -hugs-
