### ISSUE TITLE
Buggy Graphics

### ISSUE THREAD

**Issue by Marioplays18** [ppy/osu#26708]
### Type

Game behaviour

### Bug description

So I Decided To Try And Play Osu Again On Android 14 When Osu Decided To Not Render Properly.
Transparency Decided Off Today And There Is Flickering.

### Screenshots or videos

https://github.com/ppy/osu/assets/152031793/c343402c-c967-4f8b-a198-95f10f77a549

### Version

2024.114.0

### Logs

Im On Android 14 So I Can't Access Logs...

**Comment by bdach** [comment]
#25189
