### ISSUE TITLE
sliders with a lot of anchor points imploding fps

### ISSUE THREAD

**Issue by Wonderis701** [ppy/osu#26712]
### Type

Performance

### Bug description

Playing the top difficulty of God-ish (https://osu.ppy.sh/beatmapsets/1746664#osu/3572698) I was surprised by my game falling down to double digit framerates upon getting to this slider ( 02:22:887 (1) - ), the same slider plays perfectly fine on stable. I suppose with how awfully this slider is made it's probably not a big concern (no one would realistically map this way, except for some reason here they did), but the same slider not being an issue fps wise on stable seems like a valid issue.

### Screenshots or videos

https://github.com/ppy/osu/assets/157759463/12906cbf-66d0-4b2b-801b-fc34bc6133ad

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14058256/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21495
