### ISSUE TITLE
Mouse statter on macOS (lazer native)

### ISSUE THREAD

**Issue by diabloproject** [ppy/osu#26714]
### Type

Game behaviour

### Bug description

Mouse not working properly (see attachements)
Because i play in borderless mode, i can see my macos mouse and, as you can see, problem is not in the mouse or OS.

### Screenshots or videos

https://drive.google.com/file/d/1yit73iLgBzLWBebZHqeOC1ZrDT0RKViE/view?usp=sharing

### Version

Lazer 2024.114.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14060083/compressed-logs.zip)

**Comment by peppy** [comment]
For now, please set your game to "single thread" mode and set "vsync" to on. This should make things easier to cope with.

Tracking rest at https://github.com/ppy/osu/issues/24620.
