### ISSUE TITLE
Beatmap import supposedly succeeds (but does not appear in listing)

### ISSUE THREAD

**Issue by rtiosfu** [ppy/osu#26739]
### Type

Game behaviour

### Bug description

On Lazer, I was attempting to download [this mapset](https://osu.ppy.sh/beatmapsets/1833716#osu/3764512) via the browse tab. Despite the fact that it apparently succeeded, the 'go to beatmap' button on the page takes me to a seemingly random beatmap instead, and it does not appear when searching nor when manually scrolling through the list.
The issue persists when using the manual import option with a manually downloaded .osz in settings - and the beatmap seemingly cannot be deleted.

### Screenshots or videos

![osu_2024-01-26_19-06-33](https://github.com/ppy/osu/assets/70916694/bfa70733-03b5-4161-9fe8-40a163890498)
![osu_2024-01-26_19-06-50](https://github.com/ppy/osu/assets/70916694/e32d3a72-d9ce-4414-a349-dd77130ebded)

### Version

2014.144.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14070777/compressed-logs.zip)

**Comment by rtiosfu** [comment]
After some further testing, it seems like it isn't working with _any_ beatmap import.

**Comment by ssz7-ch2** [comment]
The map's star rating is below the difficulty range, which is why it's not showing
related discussion: https://github.com/ppy/osu/discussions/25894

**Comment by rtiosfu** [comment]
Oh. I feel foolish.

**Comment by rtiosfu** [comment]
Oh. I feel foolish.
