### ISSUE TITLE
Rapidly switching between skin editor tabs deletes all elements and saves

### ISSUE THREAD

**Issue by Qunas101** [ppy/osu#26735]
### Type

Other

### Bug description

I guess it doesn't have time to load everything and just saves an empty scene. Would suck if it were to happen to a skin you put effort in

### Screenshots or videos

https://github.com/ppy/osu/assets/40661883/a1bdd9a2-6089-4b29-ba31-cad34063e728

### Version

2024.114.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14070136/compressed-logs.zip)

**Comment by Joehuu** [comment]
I believe this has already been fixed by https://github.com/ppy/osu/pull/26560. Please comment if it still happens again in the next release.
