### ISSUE TITLE
Relax clicked too early

### ISSUE THREAD

**Issue by wawdili** [ppy/osu#26746]
### Type

Game behaviour

### Bug description

Relax erroneously clicked too early, and each time it clicked, two ripples appeared instead of one.

At 1 minute and 17 seconds:  (or watch the video directly)
[replay](https://github.com/ppy/osu/assets/87159802/3d070de4-2c58-4551-a372-6523abff4a2a)
(Please change the suffix to '. osr' after downloading)

### Screenshots or videos

video:

https://github.com/ppy/osu/assets/87159802/ad481eb4-d141-4fc6-918e-8a8b9eaadf75

### Version

2024.114.0

### Logs

-

**Comment by frenzibyte** [comment]
I cannot download the replay attached. Can you please provide a link to the beatmap you're noticing the issue on?

**Comment by Drison64** [comment]
@frenzibyte
The beatmap: https://osu.ppy.sh/beatmapsets/1956534
[replay-26746.zip](https://github.com/ppy/osu/files/14073053/replay-26746.zip)
Failed to replicate the issue on stable, but was able to reproduce on lazer.

**Comment by wawdili** [comment]
It also triggered note lock.

https://github.com/ppy/osu/assets/87159802/beb2cc22-b236-4dbd-93c0-2496be0b10eb
