### ISSUE TITLE
triangles is a bit off on rulesets select

### ISSUE THREAD

**Issue by SussyGuy35** [ppy/osu#26754]
### Type

Cosmetic

### Bug description

triangles is a bit off to the panel, see the screenshot 

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/107260269/9bc9186a-ecde-43a0-92d0-aa24d8f21c33)

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14074894/compressed-logs.zip)

**Comment by nagi-desuuu** [comment]
https://github.com/ppy/osu/issues/4591
