### ISSUE TITLE
Links go off screen in chat

### ISSUE THREAD

**Issue by Sukuratchi** [ppy/osu#26795]
### Type

Cosmetic

### Bug description

When clicking on an "embeded link" (link that's "hidden" in text), the warning pops up asking if you want to leave and the link that it shows goes off screen if it's a very long link

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/66184829/f323dc6b-451a-486b-bb93-957064dab726)

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14094634/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/10085
