### ISSUE TITLE
Ruleset icon in Discord's Rich Presence is cut off at the bottom

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#26796]
### Type

Cosmetic

### Bug description

Just run lazer and look at your ruleset selection in Discord Rich Presence

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/82095491/ae2f33d2-8e4c-4b3b-93f1-5c9cefbbddf4)

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14095141/compressed-logs.zip)

**Comment by peppy** [comment]
Did you mean to report this to discord?

**Comment by Skubers** [comment]
> Did you mean to report this to discord?

I assumed that osu! decides what icons to put in there.
I can send a ticket to discord then

**Comment by peppy** [comment]
we do, but our icons aren't cut off

**Comment by Skubers** [comment]
No worries, already submitted :)
