### ISSUE TITLE
Hit Judgements disappear unexpectedly

### ISSUE THREAD

**Issue by tomm13** [ppy/osu#26801]
### Type

Game behaviour

### Bug description

Judgements only last one frame

### Screenshots or videos

https://github.com/ppy/osu/assets/42684333/d565ec9d-4949-4845-a5c1-5f9202bb7d98

### Version

2024.130.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14097772/compressed-logs.zip)

**Comment by bdach** [comment]
Please attach/link skin.

**Comment by tomm13** [comment]
https://drive.google.com/file/d/1EELdPTJ7yJOFwWm2sNWL1m8woPMq5nDP/view?usp=drive_link

**Comment by jwh926** [comment]
Same issue here. I think it's a problem with the animation processing, because some skins with no judgement animations have no issues.

skin that have no issues
- https://skins.osuck.net/api/skins/2398/download?v=0&t=2

skin that has some issues
https://skins.osuck.net/api/skins/2023/download?v=0&t=2

**Comment by vatei** [comment]
Same issue here
Skin: https://drive.google.com/file/d/1HouZ-zgopRlzIP8d6K5MAn-anWIsvJJS/view?usp=sharing

I played lazer before and it's an issue with the new update

**Comment by Sprinter05** [comment]
Same issue here with all judgements using the reOwO Tuna - Selyu skin

**Comment by innocentDE** [comment]
I've been trying with different skins and it seems to be more often with animated hit judgements

**Comment by bdach** [comment]
Thanks everyone, no further input necessary, I can reproduce. I'm investigating why this is happening.

**Comment by suicidalravioli** [comment]
I will comment, to some degree it is nice to have a shorter judgement period, gives less "nerves" when playing high intensity patterns, perhaps in future allow users to adjust period the judgements show up?

**Comment by NoelleTGS** [comment]
> I will comment, to some degree it is nice to have a shorter judgement period, gives less "nerves" when playing high intensity patterns, perhaps in future allow users to adjust period the judgements show up?

Can't this just be adjusted by having less frames in the animation?
