### ISSUE TITLE
Android version is unplayable

### ISSUE THREAD

**Issue by fekked** [ppy/osu#26809]
### Type

Performance

### Bug description

New version can't be played on Android. Also massive lag can appear on map selection and playing any crashes the game.

### Screenshots or videos

https://github.com/ppy/osu/assets/118572740/0fc6fa38-770d-4554-9e2d-2490fb08a676

### Version

2024.130.2

### Logs

[Logs.zip](https://github.com/ppy/osu/files/14098426/Logs.zip)

**Comment by fekked** [comment]
https://github.com/ppy/osu/assets/118572740/5688f159-e174-4017-8c87-0c522a4ebce5

**Comment by Focron** [comment]
I have a similar issue, but in my case there are graphical issues too. See below:

https://github.com/ppy/osu/assets/106925315/6aec92cc-bd2b-433c-abc3-5256d00e3180

**Comment by frenzibyte** [comment]
Android build will be pulled for the time being.

**Comment by frenzibyte** [comment]
> I have a similar issue, but in my case there are graphical issues too. See below:
> 
>  screen-20240130-141742.mp42.mp4

video isn't loading but you're likely looking at https://github.com/ppy/osu/issues/25189.

**Comment by Focron** [comment]
> > I have a similar issue, but in my case there are graphical issues too. See below:
> > screen-20240130-141742.mp42.mp4
> 
> video isn't loading but you're likely looking at #25189.

Thanks for point that out. You are probably right as I am also an a Pixel device and on Android 14.

**Comment by yesseruser** [comment]
> I have a similar issue, but in my case there are graphical issues too. See below:
> 
> https://github.com/ppy/osu/assets/106925315/6aec92cc-bd2b-433c-abc3-5256d00e3180
> 
> 

The graphical issues were already in a release a while ago. You can fix them by enabling ANGLE for osu! in developer options.
