### ISSUE TITLE
Can't play multi: Expired token

### ISSUE THREAD

**Issue by Zissue** [ppy/osu#26808]
### Type

Game behaviour

### Bug description

Joining a multiplayer lobby on osu!lazer. When the map starts, at the loading screen, it kicks you back to the lobby, while everyone else is playing. 

The notification error says: "You are not able to submit a score: expired token"

I tried restarting the game or submitting a score on single-player, but it doesn't solve it. 

### Screenshots or videos

https://github.com/ppy/osu/assets/52385367/0463a189-7e65-4942-b189-f6aa44085221

![image](https://github.com/ppy/osu/assets/52385367/8710ca0a-5852-4d30-9211-260a4237ccec)

### Version

2024.130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14098369/compressed-logs.zip)

**Comment by Zissue** [comment]
Somehow it got solved 👍🏼

**Comment by StrangeEggs** [comment]
experiencing this issue as well in latest version (2024.130.2-lazer)
[compressed-logs.zip](https://github.com/ppy/osu/files/14103545/compressed-logs.zip)

**Comment by ssz7-ch2** [comment]
Came across another player with this issue, and signing out then singing in again supposedly fixes the issue.

**Comment by StrangeEggs** [comment]
The issue for me was because my clock was an hour behind. I fixed it by setting my system clock to the correct time.

**Comment by Walavouchey** [comment]
maybe the error message should instead warn about incorrect system clock time?

**Comment by peppy** [comment]
For sure, it should provide better detail.

**Comment by ExeHead** [comment]
I have the same error , but nothing fix it , literally everything done , restart pc , game , log again , some ip changes with my internet and the error still there . _ .

**Comment by peppy** [comment]
It means your date, time or time zone are wrong. Please check them at a system level.
