### ISSUE TITLE
Rank on player card don't show the other rulesets 

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu#26802]
### Type

Game behaviour

### Bug description

The rank on the player card only show the players standard rank and not the other rulesets when switched to them.

### Screenshots or videos

<img width="1440" alt="Skärmavbild 2024-01-30 kl  13 35 01" src="https://github.com/ppy/osu/assets/81715029/067ade35-eeae-486d-89a7-36fc78444874">
<img width="1440" alt="Skärmavbild 2024-01-30 kl  13 34 51" src="https://github.com/ppy/osu/assets/81715029/61589c8d-220e-4e9b-bf28-29f6bbc96967">

### Version

2023.130.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14097821/compressed-logs.zip)

**Comment by EVAST9919** [comment]
To be more specific: it shows the rank of the default mode selected on the website. This selection isn't implemented in the game, so here we are.
