### ISSUE TITLE
Performance issues on some Aspire beatmaps

### ISSUE THREAD

**Issue by flowi07** [ppy/osu#26805]
### Type

Performance

### Bug description

I am encountering performance issues on some Aspire beatmaps. For example on the video I watch https://osu.ppy.sh/beatmapsets/982020 with mods AutoPlay, NoFail. Also this problem occurs on all skins.

### Screenshots or videos

https://github.com/ppy/osu/assets/53127770/df8e0e90-335f-44ee-8523-418465154b3e

### Version

2024.130.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14098271/compressed-logs.zip)

**Comment by bdach** [comment]
ostensibly duplicate of https://github.com/ppy/osu/issues/21495
