### ISSUE TITLE
Pinned stable scores don't display with Classic mod on profile in-game

### ISSUE THREAD

**Issue by MikeGaming** [ppy/osu#26804]
### Type

Cosmetic

### Bug description

Classic mod icon shows up on best performance scores but not on pinned scores when viewing profile in-game.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/31964010/927cd5ee-56ed-4a52-9059-31739df1bca6)

### Version

2024.130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14097989/compressed-logs.zip)

**Comment by bdach** [comment]
Tracked at https://github.com/orgs/ppy/projects/19?pane=issue&itemId=51580056
