### ISSUE TITLE
Discord uses the old osu logo in the RPC

### ISSUE THREAD

**Issue by chicco-carone** [ppy/osu#26811]
### Type

Cosmetic

### Bug description

After updating to the latest version just relased today i noticed that discord is still using the old osu logo.

### Screenshots or videos

![Screenshot_20240130_150201](https://github.com/ppy/osu/assets/66080458/ffb98fa3-5ef2-4ca0-a9c9-f5e5a7f8ba5d)

### Version

2024.130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14099266/compressed-logs.zip)

**Comment by bdach** [comment]
The logo is probably somewhere inside discord developer tooling innards so fixing requires _access_.

**Comment by VEERT00X** [comment]
> The logo is probably somewhere inside discord developer tooling innards so fixing requires _access_.

That is correct Discord's RPC can be managed in the [Discord DeveloperPortal](https://discord.com/developers/applications/) inside the *Rich Presence* tab. 

![image](https://github.com/ppy/osu/assets/72668825/379f7ce1-f5d6-45cf-a098-a6320cc8354f)

Meaning that only the people with the access to the _account / team_ that manages the bot can change it.

**Comment by peppy** [comment]
We're using the same app for both osu! and lazer. Unless this changes, the icon won't be updated for the time being, as the new logo is only used on lazer for now.

**Comment by frenzibyte** [comment]
It appears it's updated now. Closing.
