### ISSUE TITLE
Mod Select is focusing on search bar while entering

### ISSUE THREAD

**Issue by Batosoba** [ppy/osu#26830]
### Type

Game behaviour

### Bug description

Mod Select shouldn't put focus on search bar, because players are used to shortcuts (D for Double Time etc.) for mods, which can be upsetting while they're selecting desired mod. It's a small change but useful.

### Screenshots or videos

https://github.com/ppy/osu/assets/158211542/6111b1a7-4f33-4192-a816-bd75f8e89ce1

### Version

2024.130.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14102974/compressed-logs.zip)

**Comment by bdach** [comment]
There is a setting for this.
