### ISSUE TITLE
Ingame time display in bottom left corner works incorrectly

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#2684]
While playing a beatmap there is a timer in the bottom left corner that shows how long you've been playing the beatmap. But I've noticed that in the current release every time a 30 second mark is passed, the minute counter increases by 1 (incorrectly) and doesn't when 1 full minute has passed, which results in the following behaviour:
First 29 seconds the timer counts normal.
Once the timer hits 30, "1:30" gets displayed and the timer continues to count to "1:59".
After that the second counter gets reset, so now "1:00" gets displayed and the whole process continues.

The issue is consistent; occurs on all beatmaps (I've played).
This probably is a simple mistake, I just don't know how and where to fix it myself :/

**Comment by peppy** [comment]
Can you make a video of this behaviour? Also, what regional settings do you have set for your windows?

**Comment by Poyo-SSB** [comment]
Times (and other measurement metrics) are displayed differently in different locales.

**Comment by Morilli** [comment]
Alright, so just in case I'm living in Germany with UTC +2.

**Comment by FreezyLemon** [comment]
I have this happening as well (never noticed).
Also in Germany, using `en-DE` locale.

I think I'll take this one
