### ISSUE TITLE
Possible regression with animated 300s, 100s, 50s, and misses

### ISSUE THREAD

**Issue by nobully-osu** [ppy/osu#26858]
### Type

Cosmetic

### Bug description

During gameplay while using my skin that has animated 100s and 50s will act more like an instafade for 100s and 50s instead of playing out the full animation. Skin link [here](https://mega.nz/file/xwVSCR4R#IKMINbEDspePhys_daonwRIf6AmLIZ7EkwF2ih9gYGI) for others to test.

I don't remember this being an issue before hence the title for possible regression. 

### Version

2024.130.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14106553/compressed-logs.zip)

**Comment by bdach** [comment]
#26801
