### ISSUE TITLE
Grade does not display on song select after name change

### ISSUE THREAD

**Issue by Slim-3** [ppy/osu#26851]
### Type

Cosmetic

### Bug description

Scores imported from stable do not show achieved grade on lazer song select when name has been changed. I'm pretty sure this is because this name isn't in my name history since I reverted. These are both scores uploaded to the leaderboards.

### Screenshots or videos

![osu_2024-01-30_19-35-07](https://github.com/ppy/osu/assets/31319486/db3d73c5-0f2a-4ee7-b8a8-f2f70aa35e45)
![osu_2024-01-30_19-35-53](https://github.com/ppy/osu/assets/31319486/063261dc-6b51-4bfe-bbb8-4b93e29bbc71)

### Version

2024.130.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14105782/compressed-logs.zip)

**Comment by bdach** [comment]
> I'm pretty sure this is because this name isn't in my name history since I reverted

I'm not sure there is any way this can be fixed even then for legacy scores? There is no way for the lazer client to find out that the username in question was ever yours if nothing has recorded that fact. And the replay only has username to go off of.

As per https://github.com/ppy/osu/issues/24624#issuecomment-1918401500 we'll probably fixing that for new lazer replays going forward but I'm not sure anything can be done in this particular circumstance.
