### ISSUE TITLE
Account info/profile hide when closing social browser

### ISSUE THREAD

**Issue by Arasfon** [ppy/osu#2686]
When i close social browser, account info/profile remains open. Can profile hide when i close social browser?

-> opened social browser:

![image](https://user-images.githubusercontent.com/29773434/40730486-d15b98ac-643f-11e8-8f1f-634cca7ce6af.png)

-> closed social browser:

![image](https://user-images.githubusercontent.com/29773434/40730519-e87b5fcc-643f-11e8-9194-3afe906c2e65.png)

**Comment by Aergwyn** [comment]
This should also happen for beatmapset and osu!direct then. Maybe I'd even go so far to say that opening/closing either osu!social or osu!direct closes an open profile/beatmapset?

**Comment by HoutarouOreki** [comment]
This doesn't happen anymore.
