### ISSUE TITLE
Idea: Share your recent score

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#2687]
A small idea I've thought of randomly.

/ss (/ShareScore) to send your recent set score on a listening song with //information box in chat

Once you share a score it will link the name of the map, with a yellow color (your choice) background, and once you hover on the link it will show an information box with the score details (AR, OD, CS etc, score itself and mods if used)

If possible if the user clicks the link it will redirect to the score on the leaderboard

https://puu.sh/AvTCw/cb2483d8ed.png - Similar to this

**Comment by Arasfon** [comment]
May be in discord too?

**Comment by RaiLTC** [comment]
Since almost everything is now inside osu why not keep score sharing inside osu too?

**Comment by peppy** [comment]
This is already planned, on the *web* side.
