### ISSUE TITLE
Hit Judgements on many skins disappear instantly rather than fading out

### ISSUE THREAD

**Issue by Zeno-ZX** [ppy/osu#26881]
### Type

Crash to desktop

### Bug description

I decided to hop on Lazer to set a few scores when I noticed that I was dropping acc left and right, and I couldn't even tell where. It turned out my skin, along with most of Cyperdark's, are now broken, and the hit judgements disappear basically instantly instead of the expected fade out.

I have attached 2 videos, one with broken judgement lighting, and one with them working properly.

### Screenshots or videos

https://github.com/ppy/osu/assets/53851182/f2092d2c-7702-479f-9430-455b4fcdc961

https://github.com/ppy/osu/assets/53851182/da014838-da2d-471b-a10e-7c85fefae25b

### Version

2024.130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14110955/compressed-logs.zip)

**Comment by bdach** [comment]
#26801 

hotfix to arrive shortly
