### ISSUE TITLE
Hit points only showing for a split second / not showing at all

### ISSUE THREAD

**Issue by Crylia** [ppy/osu#26897]
### Type

Cosmetic

### Bug description

When playing and missing or having bad timing the 50, 100 etc points will only show for a split seconds so they are basically not visible

### Screenshots or videos

I don't have a video atm but could make one if needed

### Version

2024.131.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14113923/compressed-logs.zip)

**Comment by bdach** [comment]
> ### Version
> 
> 2024.131.0

No it's not:

```
----------------------------------------------------------
runtime Log for crylia (LogLevel: Verbose)
Running osu 2024.130.2.0 on .NET 6.0.26
Environment: Linux (Unix 6.7.2.1), 6 cores 
----------------------------------------------------------
```

Anyways please download 2024.131.0 because it's fixed there. If you're on windows then please do so manually from [here](https://github.com/ppy/osu/releases/tag/2024.131.0) as there's an issue with the autoupdated.
