### ISSUE TITLE
Lazer is not checking for updates on version 2024.130.2

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#26908]
### Type

Game behaviour

### Bug description

Game isn't checking for updates on launch and the check for updates button is now missing from settings since 2024.130.2.
I don't know if this is an issue on other platforms but it seems to be on linux.

### Version

 2024.130.2

### Logs

.

**Comment by Stoppedpuma** [comment]
Seems to only be an issue on 2024.130.2

**Comment by bdach** [comment]
Yes we know please see https://osu.ppy.sh/comments/3029371. Still looking into possibility of restoring auto update functionality but for now please update manually.

**Comment by Qunas101** [comment]
Linux doesn't have auto updates, but now it doesn't have a notification about available update either

**Comment by peppy** [comment]
We've pushed a fix for this. The game should automatically update after a restart (you will need the game to have started twice).

Note that this only applies to windows.
