### ISSUE TITLE
Ranked beatmap sets get marked as "Local" forever after modifying

### ISSUE THREAD

**Issue by Qunas101** [ppy/osu#26917]
### Type

Game behaviour

### Bug description

After modifying a ranked beatmap set, there is no way to "update" it so it displays as Ranked again. You can delete it or re-import when there is a local diff present, but those result in "Date added" getting lost pretty much.

A way to revert all beatmap modifications without resetting date added would be nice

### After creating a local diff
![osu!bug1](https://github.com/ppy/osu/assets/40661883/8710e8a0-fdfb-436d-a783-cf6b2c51c810)
### After deleting it
![osu!bug2](https://github.com/ppy/osu/assets/40661883/6ee54bd9-d988-415b-a7c6-b0d10e5fdfb7)

### Version

2024.131.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14121923/compressed-logs.zip)

**Comment by bdach** [comment]
#23524

**Comment by Qunas101** [comment]
why am I so bad at searching issues
