### ISSUE TITLE
Star rating sourced from local database may become outdated due to diffcalc changes

### ISSUE THREAD

**Issue by developedby** [ppy/osu#26929]
### Type

Cosmetic

### Bug description

I have a BeatmapAttributeText in the song select to always show the star rating no matter what tab of the song info is open.
I noticed that the normal star rating display is different from the values given by the BeatmapAttributeText skin element as shown in the images below.

I imagine this is related to #10242 or #16251 , the rating shown by BeatmapAttributeText is the same as on web. No mods are enabled, so not a case of #21946 . 

It's slightly confusing and for consistency it would be better to sample the information from the same source, but since this is used also during plays that might not be possible right now?

### Screenshots or videos

![Screenshot_20240201_183405](https://github.com/ppy/osu/assets/4893601/82e39d13-e48c-48a7-8144-41b530c9c5b1)
![Screenshot_20240201_183441](https://github.com/ppy/osu/assets/4893601/d50a8fc2-9ffc-46c9-9a4e-36e2f4eef901)

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14129138/compressed-logs.zip)

**Comment by bdach** [comment]
This I believe will be caused by diffcalc changing between the beatmap was imported and now. The `BeatmapAttributeText` is using the star rating persisted to the local database, but the actual SR has changed since, and the database was not updated.

For a proper solution to this we need something like https://github.com/ppy/osu/discussions/13356.

**Comment by smoogipoo** [comment]
I believe we have this now? https://github.com/ppy/osu/blob/c64d414d1b229c5dc508eadcfea1d8a9425cbcbd/osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs#L37-L40

Or is there something insufficient with it?

**Comment by bdach** [comment]
I guess the most insufficient thing about it is that we seem to have collectively forgotten that it exists and as such failed to increment it once over the last year and a half.
