### ISSUE TITLE
osu!mania loved state text stays for too long for certain maps thus blocking the screen

### ISSUE THREAD

**Issue by Atuii** [ppy/osu#2693]
In osu!mania the loved state text for some maps doesn't disappear fast enough and it blocks the view.
Here's some maps that you can easily replicate it with:
https://osu.ppy.sh/b/776884 [SMITH RMX]
https://osu.ppy.sh/b/1245284 [TSLove <3] for example has this but [ManiaLove <3] difficulty doesn't include this problem
https://osu.ppy.sh/b/448729 [7k Normal] and [4k Normal] have this problem but other difficulties don't have it

![screenshot243](https://user-images.githubusercontent.com/35481565/40776965-0390237a-64d5-11e8-8611-00ab7c959d17.jpg)

![screenshot246](https://user-images.githubusercontent.com/35481565/40776814-8a31b0e8-64d4-11e8-80d1-3d9813c8b455.jpg)
 
Also I apologize if this is posted in the wrong place but I couldn't find a better place to post this issue, it has been bugging me for quite a while since i have to restart the map in order to see the first notes. This doesn't affect easier maps that much in my opinion but maps with a lot of notes at the start it's pretty bad.

**Comment by peppy** [comment]
Thanks for the report but this is indeed the wrong place. https://osu.ppy.sh/forum/5 is probably the best place to report stable issues.
