### ISSUE TITLE
Non-SS scores submit with Perfect mod in osu!mania

### ISSUE THREAD

**Issue by 2thwiki** [ppy/osu#26944]
### Type

Game behaviour

### Bug description

https://osu.ppy.sh/scores/2275078243

### Version

2024.131.0-lazer

### Logs

N/A

**Comment by 2thwiki** [comment]
@bdach Might I suggest changing the mod description from "SS or quit" for being misleading.

**Comment by bdach** [comment]
We'll see what the general mania's reaction is to the changes to grading. Chances are we might have to fix the _grades_ to match instead.
