### ISSUE TITLE
Links can spill out of the DialogOveray Box

### ISSUE THREAD

**Issue by LunarSynapse** [ppy/osu#26941]
### Type

Cosmetic

### Bug description

System: Mac Studio (2022) Apple M1 Max
os version: macOS 14.2.1 (23C71)
osu! version: 2024.131.0

When navigating to the "News" tab of the top icon bar and clicking on some news articles within the news section, a user may find that links can spill out of the DialogOveray Box.

### Screenshots or videos

<img width="2560" alt="Screenshot 2023-12-28 at 9 31 30 PM" src="https://github.com/ppy/osu/assets/16374252/53822197-174e-49c8-ae46-245c0695c3f4">

https://github.com/ppy/osu/assets/16374252/1e33ea3b-2a90-4229-8327-6695bf7f87c2

### Version

2024.131.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14133438/compressed-logs.zip)

**Comment by Stedoss** [comment]
https://github.com/ppy/osu/issues/10085
