### ISSUE TITLE
Gameplay cursor can get in an incorrect clicked state

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2694]
Something about overlays appearing in front of it while in a "pressed" state will get it stuck in said state.

https://puu.sh/Awsq5/0bf52f429e.mp4

**Comment by peppy** [comment]
This is now fixed (via #2948)

**Comment by Joehuu** [comment]
Doesn't seem fixed. Also my issue might be linked after all.

https://puu.sh/AVXY2/6d689e6d05.mp4

**Comment by peppy** [comment]
There is a portion of this fix which is not yet merged.
