### ISSUE TITLE
Relax replays from stable act like relax isn't turned on

### ISSUE THREAD

**Issue by Dreams005** [ppy/osu#26945]
### Type

Game behaviour

### Bug description

Was going through some old relax replays of mine and found out that they don't behave like they should. Tried it out with a new relax replay I just set on stable and the bug was still there.

Relax replays set on the lazer client seem to be completely fine however.

### Screenshots or videos

https://streamable.com/eanzev

(Video is over 10mb so I had to upload it to a 3rd party app)

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14134697/compressed-logs.zip)

**Comment by bdach** [comment]
#9560
