### ISSUE TITLE
Add unpause buffer for non-standard modes

### ISSUE THREAD

**Issue by rcfox2** [ppy/osu#26954]
### Type

Game behaviour

### Bug description

osu!standard benefits from a box that requires you to click in order to fully unpause. This is not a feature or really possible in other modes, and it seems like there is no buffer implemented. This makes it literally impossible to unpause without missing or having a reduction in accuracy, in any mode other than standard. 
The first video I linked is of unpausing in stable, the 2nd is in lazer.

### Screenshots or videos

https://github.com/ppy/osu/assets/68173946/f2eabbdd-232f-4c3e-a756-4914a7b85685

https://github.com/ppy/osu/assets/68173946/31a12c3c-904b-4c1d-8c53-7a141f32ac9f

### Version

2024.130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14137317/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/10202
