### ISSUE TITLE
Reverse arrow is displayed at an incorrect angle for some sliders

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2696]
Incorrect as in it doesn't match stable at all. 

This slider ``395,261,8942,2,0,B|358:243|358:243|268:273,2,136.500005207062,2|2|2,0:0|0:0|0:0,0:0:0:0:`` at 8:942 on [Re:TrymenT [Lecana's Another]](https://osu.ppy.sh/beatmapsets/519521/#osu/1415575) displays its reverse arrow angled down while it's angled correctly in stable.

![example.png](https://i.imgur.com/iiskl3x.png)

**Comment by peppy** [comment]
We have `Precision.AlmostEquals()` which may be useful in this scenario
