### ISSUE TITLE
Playlist total accuracy showing lower than expected

### ISSUE THREAD

**Issue by ssz7-ch2** [ppy/osu#26981]
### Type

Cosmetic

### Bug description

shows 99.99% instead of 100%

### Screenshots or videos

![osu_2024-02-02_18-16-36](https://github.com/ppy/osu/assets/76718358/0ad8492a-d905-4a52-8dc8-e5e71151dded)
![osu_2024-02-02_18-16-28](https://github.com/ppy/osu/assets/76718358/2e276fcd-f7fb-46dd-abd1-33d7a31061b6)

### Version

2024.131.0.0

### Logs

[1706914065.runtime.log](https://github.com/ppy/osu/files/14146418/1706914065.runtime.log)
[1706914065.network.log](https://github.com/ppy/osu/files/14146419/1706914065.network.log)
[1706914065.database.log](https://github.com/ppy/osu/files/14146420/1706914065.database.log)
[1706914065.performance.log](https://github.com/ppy/osu/files/14146421/1706914065.performance.log)
[1706914065.updater.log](https://github.com/ppy/osu/files/14146422/1706914065.updater.log)

**Comment by frenzibyte** [comment]
The score in the playlist of the attached screenshot seems to have since been changed so I couldn't attempt to investigate this further, but it seems like this is mostly an issue from the API.

**Comment by ssz7-ch2** [comment]
> The score in the playlist of the attached screenshot seems to have since been changed

Sorry about that. The scores were set when the map was qualified so they got removed after the map was ranked.

Replicated it again here: https://osu.ppy.sh/multiplayer/rooms/566124
![osu_2024-02-14_02-32-49](https://github.com/ppy/osu/assets/76718358/dccc46a6-a696-4eeb-abf5-6c9f55c7303c)


Steps to replicate:
1. Set a score that is < 100%
2. Set a score that is 100%

**Comment by peppy** [comment]
```sql
root@db-master.osu.io:osu> select * from scores where id in (select score_id from multiplayer_score_links where playlist_item_id in (select id from multiplayer_playlist
                        -> _items where room_id = 566124)) order by total_score desc limit 1\G;
***************************[ 1. row ]***************************
id                 | 2342883669
user_id            | 10685932
ruleset_id         | 0
beatmap_id         | 4148305
has_replay         | 1
preserve           | 1
ranked             | 0
rank               | XH
passed             | 1
accuracy           | 1.0
max_combo          | 376
total_score        | 1119606
data               | {"mods": [{"acronym": "DT"}, {"acronym": "HD"}, {"acronym": "CL"}], "statistics": {"great": 221, "ignore_miss": 2, "large_bonus": 3, "small_bonus": 7, "large_tick_hit": 155, "small_tick_hit": 128}, "maximum_statistics": {"great": 221, "large_bonus": 5, "small_bonus": 7, "large_tick_hit": 155, "small_tick_hit": 128}}
pp                 | <null>
legacy_score_id    | <null>
legacy_total_score | 0
started_at         | 2024-02-14 07:26:21
ended_at           | 2024-02-14 07:27:22
unix_updated_at    | 1707895642
build_id           | 7415
```

@ppy/team-web can you check on this? things look roughly right from the database end.
