### ISSUE TITLE
Next media bug when searching for a map

### ISSUE THREAD

**Issue by owoPeef** [ppy/osu#26986]
### Type

Game behaviour

### Bug description

When I was looking for a beatmap by name, I pressed F5 (Next Media) and I saw this bug. Next Media is added to the current list of beatmaps found in the search.

### Screenshots or videos

https://github.com/ppy/osu/assets/77969185/29c431c7-7f54-4417-960b-a6aa9eb9f028

### Version

2024.131.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14149346/compressed-logs.zip)

**Comment by bdach** [comment]
I'm torn between calling this "expected behaviour" (because this is what happens when you forcibly present a beatmap from an import notification, for example) and not doing that. Will keep open for now, but I think this could just as well be closed as working as intended.

**Comment by frenzibyte** [comment]
This looks to be a duplicate of https://github.com/ppy/osu/discussions/19438. And even if anything should be done about it because it has been mentioned more than once, let's track that under https://github.com/ppy/osu/issues/11325.
