### ISSUE TITLE
osu! requests verification code each time I log in

### ISSUE THREAD

**Issue by PANCHO7532** [ppy/osu#26985]
### Type

Other

### Bug description

Since the last update, osu! seems to request an verification code each time I log-in to my account, isn't supposed to request it only once and never again as long as you're on the same network/computer?

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14148732/compressed-logs.zip)

**Comment by bdach** [comment]
This is intended. Use the "stay signed in' toggle if you don't want it to do that.

**Comment by Nickdev7** [comment]
> This is intended. Use the "stay signed in' toggle if you don't want it to do that.

it doesn't work for me. it signs me out every day

**Comment by peppy** [comment]
Could you provide logs after the sign out occurs?

**Comment by Nickdev7** [comment]
what do u mean logs?

**Comment by nagi-desuuu** [comment]
settings>export logs>click the notification that comes after it>drag `compressed-logs.zip` here

**Comment by Nickdev7** [comment]
[compressed-logs.zip](https://github.com/user-attachments/files/16228897/compressed-logs.zip)
