### ISSUE TITLE
Gameplays with customised mods are not recorded by leaderboard server.

### ISSUE THREAD

**Issue by SysError99** [ppy/osu#26993]
### Type

Game behaviour

### Bug description

Any gameplays with customised mods (for example, double speed with 2.00x configuration) are not recorded by the osu! main server leaderboard.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/17522480/47e86c29-4a79-4817-ab99-69e038dd70d5)

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14151523/compressed-logs.zip)

**Comment by bdach** [comment]
This is intended for now.

https://github.com/ppy/osu/pull/26934 will convey this better.
