### ISSUE TITLE
Countries are not localisable

### ISSUE THREAD

**Issue by soopax** [ppy/osu#27000]
### Type

Other

### Bug description

Steps to reproduce:
1. Select *any* language other than English
2. Go to country rankings

Expected result
The country names should be in the selected language instead of English.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/101510334/3d048b27-9a94-4011-907f-764bd50fa673)
In this screenshot, notice that the language of the game is set to Finnish, but the country names are still in English. For example:
* "United States" should be "Amerikan yhdysvallat" or "Yhdysvallat"
* "Russian Federation" should be "Venäjä" or "Venäjän federaatio"
* etc.

### Version

2024.131.0-lazer

### Logs

*

**Comment by bdach** [comment]
This does not need a specific issue open for it. It's the same as every other place in client that currently doesn't support localisation.

The website also doesn't localise these by the way.
