### ISSUE TITLE
Osu freezes completely when starting up on Arm (M1) macOS Sonoma (14.1)

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#27003]
### Type

Crash to desktop

### Bug description

Not really crash to desktop but forces me to force quit the app. Every time I start the game up, it gets stuck at the initial screen.

Since it may be helpful (my graphics settings etc.), here's my game.ini file with a removed username and token: 
[game.ini](https://github.com/ppy/osu/files/14152530/game.txt)

### Version

2024.131.0

### Logs

Since I couldn't get to the export buttons, here's the noramlly zipped up logs:
[logs.zip](https://github.com/ppy/osu/files/14152518/logs.zip)

**Comment by smoogipoo** [comment]
I can't reproduce this. Can you try deleting `~/Library/Application Support/osu/AuthNative.so` as a test?
