### ISSUE TITLE
Lazer Social/Multiplayer chat just saying "disabled" when attempting forward chatting

### ISSUE THREAD

**Issue by jazzomega** [ppy/osu#27023]
### Type

Game behavior

### Bug description

Apologies for a bad bug report or categorized wrong or anything as this is my first one trying to report to Github. Anyhow, attempting to chat in osu!lazer yields an error. Chat updates everything fine and up-to-date, however attempting to chat in any channels, including dms, is disabled with no error code or anything. Screenshots are there for reference; have attempted troubleshooting and looking up the issue online and haven't seen this reported or something not exactly my issue without any help as to how to fix. Hoping to get this fixed before the complete transition to lazer has completed if it's unique to me. Also sorry if this is a known issue and has been there for some people just trying to get some info.

### Screenshots or videos

![osu_2024-02-04_11-42-37](https://github.com/ppy/osu/assets/35309074/44912821-4e73-4d43-98dc-8c1fb5ec6a38)
![osu_2024-02-04_11-42-45](https://github.com/ppy/osu/assets/35309074/a44ab711-28ce-45ee-955a-3531544a1115)

### Version

2024.131.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14157735/compressed-logs.zip)

**Comment by bdach** [comment]
> ### Version
> 
> 2024.131.0

You're not running this version. I unfortunately can't tell which version you're running because for a while we broke logs such that the version was not getting correctly to logs, but it is most definitely not 2024.131.0.

Please upgrade.

**Comment by jazzomega** [comment]
> > ### Version
> > 2024.131.0
> 
> You're not running this version. I unfortunately can't tell which version you're running because for a while we broke logs such that the version was not getting correctly to logs, but it is most definitely not 2024.131.0.
> 
> Please upgrade.

Thank you for the info, it was not my knowledge I didn't upgrade, thought I did cause I remember downloading the current version and running it but when it finished it made a seperate osu shortcut on my taskbar and I think I unpinned it thinking it was a weird visual bug. Don't know how that works where I somehow downgraded unless the versions are two seperate files but definitely user error on my part.
