### ISSUE TITLE
Osu lazer on IOS is still on an old version (1.14) 

### ISSUE THREAD

**Issue by fadechilln** [ppy/osu#27034]
### Type

Game behaviour

### Bug description

The latest version of lazer is (1.31) while on iOS it's stuck on ver 1.14. Whenever I try to click the update button in lazer, it takes me to testflight and it states "latest version 1.14." Due to this version difference, scores set on lazer iOS don't submit. If you could update the iOS version of lazer to the latest, I believe this would fix the issues I am experiencing. https://www.reddit.com/r/osugame/comments/1aixj0n/osulazer_on_ios_be_like/ I don't believe this is only happening to me so I believe this issue to be due to the version difference. In the screenshots below you can see how the text and everything is glitched, this didn't happen yesterday but it's broken due to the old version. Sorry for repeating words a lot but just trying to emphasize the issue as much as possible. Thank you whoever is reads and fixes this, have a great day!

### Screenshots or videos

![IMG_1111](https://github.com/ppy/osu/assets/118009242/be53a1ca-b789-4bc4-b5ff-30db3d7b2692)
![IMG_1112](https://github.com/ppy/osu/assets/118009242/c1ba9de8-4db0-4f78-bedb-2e624e661331)
![IMG_1113](https://github.com/ppy/osu/assets/118009242/80d487ab-f0b9-44fc-a1fc-2ca18fbc464a)

### Version

1.14

### Logs

Unfortunately, I can't connect my iOS device to my computer at this moment so I can't get the logs. However for this issue, I think you don't need logs either way since it's obvious that the issues are caused by (version mismatch.)

**Comment by frenzibyte** [comment]
Tracking in https://github.com/ppy/osu/issues/27017

**Comment by fadechilln** [comment]
that was not the issue, it didn’t get addressed. I reinstalled the game and it still says there’s a new update, but I can’t update because it isn’t pushed to TestFlight. 
![IMG_1116](https://github.com/ppy/osu/assets/118009242/e17d65c7-3807-4119-a953-b95a45772dcc)

**Comment by frenzibyte** [comment]
Again, that's because iOS builds have not been published for the releases you're receiving the notification for. This scenario of the notification showing up when no release is available will be resolved in a future release after https://github.com/ppy/osu/pull/26930/files is merged.
