### ISSUE TITLE
Inaccurate beatmap stat values in playlists/multiplayer when using rate change

### ISSUE THREAD

**Issue by snoresx3** [ppy/osu#27030]
### Type

Game behaviour

### Bug description

When using rate changed maps in playlists, it shows the stats of the map at base speed rather than the rate changed speed. This also occurs when applying stat modifying mods (Difficulty Adjust, Hard Rock and Easy).

### Screenshots or videos

https://youtu.be/33mWwZmPqB0

https://youtu.be/gP37UWh5NnY (EZ)

https://youtu.be/yc9N6fT-yT8 (HR)

https://youtu.be/uKgJOXvbDJw (DA)

### Version

2024.131.0-Lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14158086/compressed-logs.zip)

**Comment by bdach** [comment]
This is also an issue in multiplayer.

**Comment by Givikap120** [comment]
Fixed?
https://github.com/ppy/osu/pull/27214
