### ISSUE TITLE
Slider ball renders incorrectly in editor if you move the slider endpoint during its playing animation

### ISSUE THREAD

**Issue by OwenCMYK** [ppy/osu#27037]
### Type

Cosmetic

### Bug description

I found the bug while I was using the editor. I paused during a slider and decided to adjust it, but when I did, I noticed the slider ball pointed in weird random directions. So I thought I'd post a bug report.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/42657486/e6d51437-8c3d-4c8f-8395-b880bf45fe76)
![image](https://github.com/ppy/osu/assets/42657486/ffe1a484-b0c2-4798-87d2-e13b92083299)

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14159207/compressed-logs.zip)
I don't think the logs will be needed but here they are just in case

**Comment by owengaming001** [comment]
This also happens with the start point. I forgot to test that before submitting.
![image](https://github.com/ppy/osu/assets/42657486/6edb58d2-7aeb-4430-841a-fba06252d6c4)
