### ISSUE TITLE
Trying to deselect a slider creates control points instead of deselecting

### ISSUE THREAD

**Issue by kongehund** [ppy/osu#27055]
### Type

Game behaviour

### Bug description

You can Ctrl+Click on two objects in the editor to select both of them. If one of them is a slider, Ctrl+Clicking it once it is a part of a selection of two or more objects will add a control point to it instead of deselecting it.

### Screenshots or videos

No video needed, very easy to replicate.

### Version

master/cc5e1e0a

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14172535/compressed-logs.zip)

**Comment by kongehund** [comment]
I'd like to give a go at this issue

**Comment by OliBomby** [comment]
I guess a reasonable direction is to disallow adding/removing control points if more than one object is selected.

**Comment by bdach** [comment]
i don't know that i agree with the above. the fact that the ctrl-click to add anchor functionality thus becomes context sensitive feels pretty wrong.

**Comment by bdach** [comment]
that's fine and all but the fact that the control points hide when more than one objects is selected is primarily described as a means to "reduce overhead":

https://github.com/ppy/osu/blob/c18cd650811ea147219b051c3ed916ea92c12a27/osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs#L144-L145

it also apparently "matches stable" as per description of https://github.com/ppy/osu/pull/20965 but i'm not really sure that's something that holds up if we can improve performance there. i dunno.

**Comment by OliBomby** [comment]
I can't imagine a reason why you would want to edit slider control points while having multiple objects selected, so I think the stable behaviour makes more sense. 

Sure you could fix the performance and have all selected sliders show their control points and allow editing, but the mapper probably intends to do some multi-selection operations when multiple objects are selected, so having ctrl+click for toggling selection is more useful in that case.

I've never had issues with the behaviour in stable and neither have I heard any mappers complain about not being able to edit sliders while multi-selecting. If it aint broke dont fix it.
