### ISSUE TITLE
Can’t choose custom fullscreen resolution

### ISSUE THREAD

**Issue by InSovietCS** [ppy/osu#2706]
Currently, you can not use any other resolution other than native (no resolution select in the settings menu). Reason of issue: low performance due to peoples PC's not being able to handle everything ofc.

**Comment by UselessToucan** [comment]
Workaround: you can set lower resolution using OS or GPU settings.
It works:
![osu_2018-06-02_00-05-55](https://user-images.githubusercontent.com/22450664/40863617-3137830c-65f9-11e8-83e2-55944e181af5.jpg)
![osu_2018-06-02_00-06-34](https://user-images.githubusercontent.com/22450664/40863618-315bc8c0-65f9-11e8-80d7-bf6fbee9204d.jpg)

**Comment by InSovietCS** [comment]
I don't know what exactly you mean by workaround. The application overrides the chosen resolution in this method. Device: laptop. Active GPUs 2, 920MX+IntelHD

**Comment by UselessToucan** [comment]
> I don't know what exactly you mean by workaround. The application overrides the chosen resolution in this method.

On my Surface Pro 2 changing the resolution via "Intel HD Graphics Control Panel" makes the trick(see second screenshot which is 1280x720).

**Comment by peppy** [comment]
Please stay focused on addressing the issue, not providing workarounds.

**Comment by peppy** [comment]
Letterboxing options will not be resolution based, but instead have crop parameters local to the setting.
