### ISSUE TITLE
Key presses during break times count up towards total

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2707]
They do not on stable

**Comment by turbedi** [comment]
Duplicate of issue #3032 , fixed by PR #3035

**Comment by HoutarouOreki** [comment]
@peppy This is neither a duplicate nor is it fixed by that PR. This one is about break times, that issue and PR are about pauses.

**Comment by galister** [comment]
This is also the case during song intro:
https://i.imgur.com/efxWVtO.jpg
