### ISSUE TITLE
Flechas estiradas

### ISSUE THREAD

**Issue by Dante20218** [ppy/osu#27073]
### Type

Game behaviour

### Bug description

E estado jugando Osu! Lazer en mi android pero cuando juego Osu! Mania me aparece las flechas estiradas ademas de que el fondo casi ni se ve por las flechas y por culpa de las flechas gigantes me da mucho lag porfavor me pueden ayudar a sacarlo o arreglarlo en una proxima actualizacion

### Screenshots or videos

![Screenshot_20240207_051338](https://github.com/ppy/osu/assets/87088191/d54bcee6-b82b-4f95-ab64-c37e40d376ed)

### Version

2024.131.0-Lazer

### Logs

No hay

**Comment by bdach** [comment]
inglés por favor

https://github.com/ppy/osu/discussions/25449
https://github.com/ppy/osu/discussions/25753
https://github.com/ppy/osu/discussions/26380
