### ISSUE TITLE
replay bug and a little suggestion

### ISSUE THREAD

**Issue by crystvl6mik** [ppy/osu#27082]
/del

**Comment by cdwcgt** [comment]
replays are allowed to fail, but the premise is that the rank is F
if a failed replay export from stable, it's rank will not be F

https://github.com/ppy/osu/blob/7bc571dd517bdcc5493eac8e28b2ea5309726591/osu.Game/Screens/Play/ReplayPlayer.cs#L49

[replay.zip](https://github.com/ppy/osu/files/14249666/replay.zip)

**Comment by frenzibyte** [comment]
Let's not combine two things in one issue thread please.
