### ISSUE TITLE
Game skipping backwards and then failing for no reason

### ISSUE THREAD

**Issue by Packsolite** [ppy/osu#27088]
### Type

Game behaviour

### Bug description

So i had this happen twice now where it would skip to a different part of the song for one frame. Also in this case even the combo counter decreased from 85 to 79 and then 77 in two frames. I have no clue why this happens.

Frame
![image](https://github.com/ppy/osu/assets/102829507/48bf60d6-268a-4e3c-ba44-ef6864e5312e)
Next frame:
![image](https://github.com/ppy/osu/assets/102829507/aaac36d9-7a16-4512-9f0c-a462551e5d82)
Frame after that:
![image](https://github.com/ppy/osu/assets/102829507/24af25cd-0ac4-4e9f-b52e-8ddaca5e9b13)

This just makes no sense to me at all.

### Screenshots or videos

https://youtu.be/RC5nnESASrI

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14202905/compressed-logs.zip)

**Comment by ssz7-ch2** [comment]
probably related to https://github.com/ppy/osu/issues/26843
https://github.com/ppy/osu/issues/26879

**Comment by bdach** [comment]
Probably the second because of

```
$ grep discrepancy . -R
./1707349538.runtime.log:2024-02-08 00:05:08 [verbose]: Playback discrepancy detected (1 of allowed 5): 47,256.8 vs 59,119.8
```

**Comment by Packsolite** [comment]
> Probably the second because of

So this is not being fixed? Makes lazer unplayable lol. Never happened on stable.

**Comment by bdach** [comment]
This was closed as a duplicate of another issue.
