### ISSUE TITLE
Key conversion mods don't change key count prefix on carousel beatmap panels

### ISSUE THREAD

**Issue by Kebababik** [ppy/osu#27086]
### Type

Game behaviour

### Bug description

there is a problem in osu! the selected map difficulty is shown and in osu!lazer it doesn't work in the video it is shown (I noticed it on this map and I apologize for the map name)

### Screenshots or videos

https://github.com/ppy/osu/assets/139135202/867a283c-ee1d-4285-b335-2b9b57b8b059

### Version

2024.131.0-lazer 

### Logs

idk

**Comment by bdach** [comment]
Key conversion mods don't change key count prefix on carousel beatmap panels

**Comment by AfonsoOrmonde** [comment]
I am interested in this bug and will try to solve it
