### ISSUE TITLE
Scores occasionally don't show up on new leaderboards

### ISSUE THREAD

**Issue by Ting0887** [ppy/osu#27097]
### Type

Performance

### Bug description

My NM score didn't show on the leaderboard, but it actually showed in the game.
beatmap : https://osu.ppy.sh/beatmapsets/2124277#fruits/4464551
score : https://osu.ppy.sh/scores/2309890432

### Screenshots or videos

website leaderboard : 
![image](https://github.com/ppy/osu/assets/57065036/24c63f62-8388-4606-bab8-5edaeabd0d94)

in game : ![screenshot369](https://github.com/ppy/osu/assets/57065036/d632b19d-c86b-4df6-b311-f4d3f68a3f63)

### Version

2024.131.0

### Logs

[osu!auth.log](https://github.com/ppy/osu/files/14217374/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/14217375/runtime.log)
[session.log](https://github.com/ppy/osu/files/14217376/session.log)
[update_success.log](https://github.com/ppy/osu/files/14217377/update_success.log)

**Comment by peppy** [comment]
I've done a full reindexing pass, which successfully fixed the reported score here.

I'm also doing ongoing investigation into the indexing process to hopefully find how this happened.

If anyone else find a similar case, please do report it here as it will help with investigations.

**Comment by peppy** [comment]
Closing this for now.
