### ISSUE TITLE
Osu.iOS Crashes on Launch

### ISSUE THREAD

**Issue by Drayy-Is-Kalina** [ppy/osu#27098]
### Type

Crash to desktop

### Bug description

Hardware+Software Details:
- iPhone 12 Mini, iOS 16.0.3 (non-jailbroken)
- TrollStore 2.0.12
- Latest Osu.iOS.ipa
Bug Details:
Immediately crashes upon opening the app; easily replicable by simply using TrollStore to load the ipa and opening the app afterwards.

### Screenshots or videos

Uncut footage, current video speed at bottom.
https://github.com/ppy/osu/assets/131895215/8032e369-9abe-4fef-b00f-4106c8bbff4f

### Version

1.0

### Logs

Unable to find logs

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/27017
