### ISSUE TITLE
MusicController can be dragged from anywhere

### ISSUE THREAD

**Issue by UselessToucan** [ppy/osu#2709]
Version: v2018.601.0
Steps to reproduce:
1. Launch the game.
2. Open music controller overlay.
3. Perform drag from any point of the screen.

Video: https://youtu.be/3cOCQwZd8yw

**Comment by UselessToucan** [comment]
Expected result: overlay is closed

**Comment by UselessToucan** [comment]
I guess this thing is the culprit
![scr](https://user-images.githubusercontent.com/22450664/40864680-752a307e-65fd-11e8-8016-5e825d179d7e.PNG)

**Comment by peppy** [comment]
Should be a simple fix by moving drag handling one container level lower in the heirarchy.
