### ISSUE TITLE
Inconsistent recent plays section between web (non pp-processed scores such like lack of mod support or loved maps)

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu#27109]
### Type

Cosmetic

### Bug description

In Recent Plays, web and client have different handling of PP unprocessable scores due to unsupported mod additions or when playing a Loved map.

### Screenshots or videos

Web:
![image](https://github.com/ppy/osu/assets/37479424/d3402e76-5625-4640-bac5-ad13a7227765)

^ it is from osu.ppy.sh lazer mode, profile: https://osu.ppy.sh/users/13063545

Client:
![image](https://github.com/ppy/osu/assets/37479424/db01ff95-4d61-4788-9715-7536b2fb8999)

### Version

2024-131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14227616/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/27027
