### ISSUE TITLE
PP counter is allocating too much

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#27104]
### Type

Performance

### Bug description

It's not directly pp counter's fault though. The source lies in [`BeatmapExtensions.GetMaxCombo()`](https://github.com/ppy/osu/blob/0ebea77392fbca045611e8478494861b0919ef04/osu.Game/Beatmaps/IBeatmap.cs#L97) which creates `Judgement`s to determine the max combo of a beatmap portion, which is called a lot.
One approach would be caching already created judgement as we already do for [`HitWindows`](https://github.com/ppy/osu/blob/0ebea77392fbca045611e8478494861b0919ef04/osu.Game/Rulesets/Objects/HitObject.cs#L155).
Also worth noting that this is an extreme case (centipede), for "normal" maps it's not as severe.

### Screenshots or videos

![2024-02-09_222039](https://github.com/ppy/osu/assets/22874522/572634e1-390c-4c98-84fa-6859dc0e3091)

### Version

master

### Logs

N/A

**Comment by EVAST9919** [comment]
This is my proposal:
![Снимок экрана 2024-02-09 231049](https://github.com/ppy/osu/assets/22874522/ada97bdc-a8af-44ea-a96f-02a261aaec15)

**Comment by EVAST9919** [comment]
Closing for now as I can't reproduce this anymore (??)

**Comment by peppy** [comment]
I don't suppose you have a call stack showing the allocations source?

**Comment by EVAST9919** [comment]
There's a chance that I profiled while star rating was recalculating in the background which may explain this.
