### ISSUE TITLE
Searching "NS" in the mod search box and pressing enter selects Cinema instead of No Scope.

### ISSUE THREAD

**Issue by Nella52** [ppy/osu#27111]
### Type

Game behaviour

### Bug description

Searching "NS" and hitting enter selects Cinema (CN) instead of No Scope (NS). If a user is typing NS its more likely they want to select No Scope, and not a mod that doesn't even have an s in its name.

### Screenshots or videos

https://github.com/ppy/osu/assets/62504841/e418629f-4a93-492f-b443-69820d9d2e70

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14227764/compressed-logs.zip)

**Comment by Gabixel** [comment]
This seems related to the discussion https://github.com/ppy/osu/discussions/25979 (so I guess the intent here is to have what https://github.com/ppy/osu/discussions/26293 is also suggesting. There is currently no way to search by acronyms)
