### ISSUE TITLE
Database not correctly getting deleted on migration failure

### ISSUE THREAD

**Issue by KurayamiZ6** [ppy/osu#2711]
When i start the game some second after i get a crash message even with the last version of osu!lazer (2018.601.0) i also have try to uninstall and reinstall it or to install older version of osu!lazer. I have also check many post about crash issue but it doesn't correspond to me, so please can you fix that problem.
my (bad) config:
- OS:windows 7 64 bits
- CPU: 2 (intel core 2 duo (2.53 GHz))
- RAM: 4go (3.45go usable)
- GPU: Mobil Intel 4 Series Express Chipset Family
- HDD: 232 GB
- MB: Dell Latitude E6500
- SOUND: Intel High Definition Audio HDMI
i also play osu at 120 fps

Log:

02/06/2018 06:29:30: GL Initialized
02/06/2018 06:29:30: GL Version:                 2.1.0 - Build 8.15.10.2869
02/06/2018 06:29:30: GL Renderer:                Mobile Intel(R) 4 Series Express Chipset Family
02/06/2018 06:29:30: GL Shader Language version: 1.20  - Intel Build 8.15.10.2869
02/06/2018 06:29:30: GL Vendor:                  Intel
02/06/2018 06:29:30: GL Extensions:              GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_texture_edge_clamp GL_EXT_separate_specular_color GL_ARB_multitexture GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_EXT_texture_rectangle GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ATI_separate_stencil GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_ARB_occlusion_query GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_texture_non_power_of_two GL_ARB_vertex_shader GL_NV_texgen_reflection GL_ARB_point_sprite GL_EXT_blend_equation_separate GL_ARB_depth_texture GL_ARB_texture_rectangle GL_ARB_draw_buffers GL_ARB_color_buffer_float GL_ARB_half_float_pixel GL_ARB_texture_float GL_ARB_pixel_buffer_object GL_EXT_framebuffer_object GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_EXT_draw_buffers2 GL_WIN_swap_hint GL_EXT_texture_sRGB GL_EXT_packed_float GL_EXT_texture_shared_exponent GL_ARB_texture_rg GL_ARB_texture_compression_rgtc GL_NV_conditional_render GL_EXT_texture_swizzle GL_ARB_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_ARB_depth_buffer_float GL_EXT_transform_feedback GL_EXT_framebuffer_blit GL_ARB_vertex_array_object
02/06/2018 06:29:30: GL Context:                 Index: 6, Color: 32 (8888), Depth: 16, Stencil: 0, Samples: 0, Accum: 64 (16161616), Buffers: 2, Stereo: False

ps: i'm french so sorry for my bad english
![image](https://user-images.githubusercontent.com/39850053/40871598-bd382cea-663e-11e8-815c-b69dd5cacb49.png)
Signature du problème :
  Nom d’événement de problème:	CLR20r3
  Signature du problème 01:	osu!.exe
  Signature du problème 02:	2018.601.0.0
  Signature du problème 03:	99cc4bbc
  Signature du problème 04:	mscorlib
  Signature du problème 05:	4.7.2650.0
  Signature du problème 06:	5ab1c3d4
  Signature du problème 07:	5386
  Signature du problème 08:	c
  Signature du problème 09:	3IMYJMNB0CI5KNMQRXWWCTDSQS5GCWQA
  Version du système:	6.1.7601.2.1.0.256.48
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	c3ca
  Information supplémentaire n° 2:	c3ca5ec72ba14a522e34f5e88e027b5e
  Information supplémentaire n° 3:	d52f
  Information supplémentaire n° 4:	d52f987f4187ace8fe888d24a19f6c77

**Comment by KurayamiZ6** [comment]
the new version 2018.608.0 doesn't work too like all other version if you need more information from me ask me for.

**Comment by peppy** [comment]
Please see the last response, asking for more information.

**Comment by KurayamiZ6** [comment]
i already have update my post with the log files but FreezyLemon didn't answer.

**Comment by LittleEndu** [comment]
If that's the entire log file then there's not enough info to go off of, the crash happens before anything meaningful is logged. You should ***upload*** the entire log file just to be sure tho.

Also people don't get notifications for updates. You need to post a new comment.

**Comment by KurayamiZ6** [comment]
Well i dont have my osu file just in %appdata% but in %appdata%/local/osu and when i check the log folder i just have a runtime and update_success file.

Picture of what i see in %appdata%/local/osu/logs

![screen](https://user-images.githubusercontent.com/39850053/41424461-65f57298-6ffe-11e8-9f2c-a485dc869a52.PNG)

**Comment by KurayamiZ6** [comment]
If you want the file who are in the Logs Folder here they are.

[runtime.log](https://github.com/ppy/osu/files/2103157/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/2103158/update_success.log)

**Comment by LittleEndu** [comment]
``%localappdata%\osu!\Logs`` is for stable client. You need to go to ``%appdata%\osu\logs``. Local app data is stable, roaming app data is lazer.

**Comment by KurayamiZ6** [comment]
ok thx for answer

**Comment by KurayamiZ6** [comment]
[performance.log](https://github.com/ppy/osu/files/2103163/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2103164/runtime.log)
[database.log](https://github.com/ppy/osu/files/2103165/database.log)

**Comment by KurayamiZ6** [comment]
its the file who are in roaming logs osu folder

**Comment by KurayamiZ6** [comment]
btw, i have install the last 2018.614.0 osu!lazer version

**Comment by FreezyLemon** [comment]
Please only post one comment and then edit it instead of posting 3 or more single comments right after another.

Anyways, this is from the DB log
```
14/06/2018 16:06:39: Failed executing DbCommand (58ms) [Parameters=[], CommandType='Text', CommandTimeout='10']
14/06/2018 16:06:39: DROP INDEX "IX_BeatmapInfo_Hash";
14/06/2018 16:06:39: Migration failed! We'll be starting with a fresh database.
14/06/2018 16:06:39: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such index: IX_BeatmapInfo_Hash'.
14/06/2018 16:06:39: à Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
14/06/2018 16:06:39: à Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__62.MoveNext()
14/06/2018 16:06:39: à Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
14/06/2018 16:06:39: à Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
14/06/2018 16:06:39: à Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
14/06/2018 16:06:39: à Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
14/06/2018 16:06:39: à Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
14/06/2018 16:06:39: à Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
14/06/2018 16:06:39: à osu.Game.Database.OsuDbContext.Migrate()
14/06/2018 16:06:39: Database purged successfully.
14/06/2018 16:06:39: Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='10']
14/06/2018 16:06:39: DROP INDEX "IX_BeatmapInfo_Hash";
```

Looks like something completely different than the other DB migration fails.

**Comment by peppy** [comment]
The latest version may have now fixed this. Please try updating to it.

**Comment by KurayamiZ6** [comment]
But i have already install the last 2018.614.0 osu!lazer version and it doesn't work for me.

**Comment by peppy** [comment]
Please try again on the next version (`2018.615.0` or later) and post logs. They will help us better understand the error.

**Comment by KurayamiZ6** [comment]
nothing change with osu!lazer 2018.616.0 i always have the same crash problem. logs file:

[performance.log](https://github.com/ppy/osu/files/2108327/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2108328/runtime.log)
[database.log](https://github.com/ppy/osu/files/2108329/database.log)
