### ISSUE TITLE
Storyboard hitsounds do not play when background dim is at 100%

### ISSUE THREAD

**Issue by tailsdk** [ppy/osu#27124]
### Type

Game behaviour

### Bug description

In mania there are a quite a few maps that are fully keysounded in ranked and many that use storyboard hitsounds in general. These hitsounds do not play unless the storyboard is enabled and visible. As an example https://osu.ppy.sh/beatmapsets/92190#mania/249346 playing this with 100% dim and storyboard hitsounds turned on will not play the storyboard hitsounds. The storyboard it self and the hitsounds should be split for mania at least

### Version

2024.131.0

### Logs

No logs

**Comment by bdach** [comment]
#9315
