### ISSUE TITLE
Crash to desktop when playing mania map with non argon skin

### ISSUE THREAD

**Issue by RubiksImplosion** [ppy/osu#27134]
### Type

Crash to desktop

### Bug description

Started the following map in lazer and the game crashed to desktop. Doesn't happen when using argon skin.
https://osu.ppy.sh/beatmapsets/2103069#mania/4412529 ([7K] Don't use Color 300)

skin:
[R Skin v1.2 (Bars) (Retsukiya).osk.zip](https://github.com/ppy/osu/files/14234333/R.Skin.v1.2.Bars.Retsukiya.osk.zip)

### Version

2024.131.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14234327/compressed-logs.zip)

**Comment by bdach** [comment]
It's not the skin, it's the ~~dumb~~ map. It features zero-length hold notes.
