### ISSUE TITLE
Local leaderboards show a global leaderboard score

### ISSUE THREAD

**Issue by u3o** [ppy/osu#27169]
### Type

Cosmetic

### Bug description

The best global score is shown in my local leaderboard for some reason, it didnt happen in any other map, only this one. Restarting the game didnt fix it.

### Screenshots or videos

https://github.com/ppy/osu/assets/64749081/cb1b1101-9259-4451-876a-23e52e16a494

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14278232/compressed-logs.zip)

**Comment by bdach** [comment]
You must have imported this score to your local database.

Please attach `client.realm` to confirm this.

**Comment by u3o** [comment]
> You must have imported this score to your local database.
> 
> Please attach `client.realm` to confirm this.

[client.realm.zip](https://github.com/ppy/osu/files/14278489/client.realm.zip)

**Comment by bdach** [comment]
Confirmed, you imported this score last year.

![1707908820](https://github.com/ppy/osu/assets/20418176/279e0607-b9a1-4e01-a0c3-aa4191d84cbf)

https://osu.ppy.sh/scores/osu/3911622489

**Comment by u3o** [comment]
> Ok the "last year" part was a mistake on my behalf (what's shown on the screenshot is the date when the no. 1 user in question set the score). But the explanation is that you imported this score locally, most likely by watching it. If it bothers you you can remove it from the leaderboard by right-clicking it and selecting "delete".

oh alirght then!!!
