### ISSUE TITLE
CS12+ maps will crash the game

### ISSUE THREAD

**Issue by ssz7-ch2** [ppy/osu#27172]
### Type

Crash to desktop

### Bug description

map: https://osu.ppy.sh/beatmapsets/1357863#osu/2810068

Should probably prevent users from loading such maps or cap the CS in some way, as CS12 maps aren't playable (unless you're using a gigantic touchscreen or something)

Aso tried some other CS values and the game starts to crash at around CS11.9 to be more precise

### Version

2024.131.0.0

### Logs

[1707931266.runtime.log](https://github.com/ppy/osu/files/14285383/1707931266.runtime.log)

**Comment by Rekunan** [comment]
> or cap the CS in some way, as CS12 maps aren't playable

I'd prefer not capping, as there has been a CS11.9 FC: https://twitter.com/moonpointless/status/1565742945336180736
