### ISSUE TITLE
PP fluctuates when switching between stable and lazer

### ISSUE THREAD

**Issue by Miyuki-10** [ppy/osu#27174]
### Type

Other

### Bug description

whenever i play osu! stable / beta, i submit a score on a new beatmap i never played before that are rank, i get like -4000 to -5000 ranks in stable / beta, and whenever i go back and submit a new rank map in lazer, i get my ranks back i just lost. is there a fix to that, or am i forced to play lazer at long the score i submit are not close to top play, but just a score for practice maps.

As you can see in the graph this looks so weird, should not keep go up and down, tested on osu normal website and also with lazer enable on website

![image](https://github.com/ppy/osu/assets/93956624/51c8afeb-788b-417c-92a9-678710e45fa4)

I use the lastest version of all the osu! versions:

![image](https://github.com/ppy/osu/assets/93956624/c2cbded4-6b46-4b12-811f-e43ab930b4c8)
![image](https://github.com/ppy/osu/assets/93956624/39aba4f1-e015-4964-ad94-56fc7133ea61)

### Screenshots or videos

![Screenshot 2024-02-15 002053](https://github.com/ppy/osu/assets/93956624/ff7ac06d-0649-42b6-b23f-62131a418a3f)
![Screenshot 2024-02-15 002102](https://github.com/ppy/osu/assets/93956624/ebcbf912-4bdd-4324-be7e-1b270d689204)
![Screenshot 2024-02-15 002111](https://github.com/ppy/osu/assets/93956624/03d16af6-746c-4672-a131-2e8be615c8af)
![Screenshot 2024-02-15 002118](https://github.com/ppy/osu/assets/93956624/95c054cc-aa63-408f-b76b-7c4962ef37f0)

### Version

stable: 20240123, beta: 202401211, lazer: 2024.131.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14289578/compressed-logs.zip)

**Comment by peppy** [comment]
This is how things work right now. We're aware of this but since there's no tracking issue yet, I'll use this one.

**Comment by peppy** [comment]
For tracking purposes, https://github.com/ppy/osu-performance/issues/118 is also related.
