### ISSUE TITLE
Extra cursor ripples appearing in replay

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#27171]
### Type

Game behaviour

### Bug description

Hi. I was playing [this beatmap](https://osu.ppy.sh/b/3783074) and performed a score, but I was wondering about my misses. So I watched it's replay precisely to find out why I missed some objects.
Then I saw something strange that I attached it's video.

### Screenshots or videos

https://github.com/ppy/osu/assets/89677246/48f8bea3-3a6b-4ef2-9fce-9bdfb2a61c9f

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14284544/compressed-logs.zip)

**Comment by aL1NaZ4R** [comment]
It's the replay: https://osu.ppy.sh/scores/2345346908

**Comment by ssz7-ch2** [comment]
Can you clarify which part is acting strange?

If you're talking about the misses on the circles, then there's nothing wrong since you pressed in between the circles. (The cursor ripples are a bit misleading here)

The slider before the circles is acting a bit strange though. It's showing missed slidertick and sliderend even though they are clearly hit.

**Comment by aL1NaZ4R** [comment]
> Can you clarify which part is acting strange?
> 
> If you're talking about the misses on the circles, then there's nothing wrong since you pressed in between the circles. (The cursor ripples are a bit misleading here)
> 
> The slider before the circles is acting a bit strange though. It's showing missed slidertick and sliderend even though they are clearly hit.

I turned on cursor ripples to see exactly when I clicked.
I clicked on both 2 & 3 circles in the time. The ripple in between is another click, because I didn't heard the hitsound, So I clicked again.

**Comment by ssz7-ch2** [comment]
Cursor ripples also show when you release the key/mouse button fyi
Try looking at the keypress overlay on the bottom right instead, as that better shows when you clicked.

**Comment by aL1NaZ4R** [comment]
> Cursor ripples also show when you release the key/mouse button fyi Try looking at the keypress overlay on the bottom right instead, as that better shows when you clicked.
Really?😢 Thx

**Comment by ssz7-ch2** [comment]
> > Cursor ripples also show when you release the key/mouse button fyi Try looking at the keypress overlay on the bottom right instead, as that better shows when you clicked.
> 
> Really?😢 Thx

Nvm, I am completely wrong about that. It's not supposed to show for key releases.

This seems like a bug with extra cursor ripples appearing when scrolling through a map. So keep this issue open.

**Comment by peppy** [comment]
If the issue is to be reopened tracking a different thing completely, please update the title to match.
