### ISSUE TITLE
Osu!Lazer wont open

### ISSUE THREAD

**Issue by MLGSquidz** [ppy/osu#2717]
I was downloading Osu!Lazer and it will only have the loading cursor then close immediately. I tried from another page to delete the database and try run the game because we had the same logs from what i noticed but it still doesn't open. If it helps I can give my logs. 
[database.log](https://github.com/ppy/osu/files/2065365/database.log)
[network.log](https://github.com/ppy/osu/files/2065367/network.log)
[performance.log](https://github.com/ppy/osu/files/2065368/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2065369/runtime.log)

**Comment by LittleEndu** [comment]
The logs are still the same. Are you sure you deleted lazer database and not stable database?? Or maybe you uploaded old log files by mistake?

For reference, lazer files are stored at ``%appdata%\osu`` while *all* stable files are stored at ``%localappdata%\osu!``

**Comment by MLGSquidz** [comment]
Oh, I understand now when they say Lazer database. I was deleting my log not the actual file. Thank you very much for the explanation! Have a good day ^_^
