### ISSUE TITLE
Replay doesn't "end" at the end if storyboards are enabled and background dim isn't at 100%

### ISSUE THREAD

**Issue by Sukuratchi** [ppy/osu#27188]
### Type

Crash to desktop

### Bug description

Watch a replay or auto play a map to the end with storyboards on and background dim set to anything that's lower than 100%
I would expect it to show the results screen after the map finishes but it (I'm assuming) lets the storyboard finish playing. There's also a skip button at the end

### Screenshots or videos

https://github.com/ppy/osu/assets/66184829/0183c134-6e1d-4dc8-b726-f4418f0efdfa

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14305611/compressed-logs.zip)

**Comment by bdach** [comment]
Not sure this is a bug? It's the same as normal gameplay, storyboarded outros are played out after gameplay but can be skipped if desired?

**Comment by Sukuratchi** [comment]
I'm sorry, didn't know this
