### ISSUE TITLE
Slider ends and repeats get unsnapped (probably after importing map to stable)

### ISSUE THREAD

**Issue by StalkyBoi43815** [ppy/osu#27181]
### Type

Game behaviour

### Bug description

Most slider ends and repeats ended up unsnapped by a few milliseconds. I don't know the cause of this, but I think it might be because I imported this map to stable (to upload).

### Screenshots or videos

![timeline](https://github.com/ppy/osu/assets/148560144/67e495d5-3122-422a-a0c0-6616cef67042)
![timeline 2](https://github.com/ppy/osu/assets/148560144/8020f886-a621-490d-b0ef-50a531c01bb5)
![Screenshot_20240215_143456](https://github.com/ppy/osu/assets/148560144/212f3579-df43-4aeb-ab69-7e3cb10fb5ac)

### Version

2024.130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14297660/compressed-logs.zip)

**Comment by bdach** [comment]
Can you describe _what_ was done here exactly, start to end? What was exported and imported where? Are you saying you mapped in lazer, then exported to stable, submitted map via stable, and then redownloaded via lazer?

**Comment by peppy** [comment]
Also need a copy of the beatmap, after lazer export and after stable export (if that is indeed what you're doing).

**Comment by StalkyBoi43815** [comment]
> Can you describe _what_ was done here exactly, start to end? What was exported and imported where? Are you saying you mapped in lazer, then exported to stable, submitted map via stable, and then redownloaded via lazer?

I mapped on Lazer, exported the (unfinished) map as an .osz file, imported the map to stable, and uploaded the map using the stable client. I never redownloaded the map. The local map on Lazer stayed unchanged. I don't know why I even mentioned stable. As you can see, the sliderends and repeats were all unsnapped by 3 or 4 different amounts of milliseconds. Like, a fourth of sliderends were unsnapped by 2.4ms. For so many sliderends to be unsnapped by such a specific amount is weird. I sometimes used 1/8 beat for specific parts of the song, as it was fitting. Also, I run both clients on ArcoLinux and I run stable using Wine. I even opened the map in stable editor. I mentioned stable because stable and Lazer sliders seem to conflict.

**Comment by StalkyBoi43815** [comment]
> Also need a copy of the beatmap, after lazer export and after stable export (if that is indeed what you're doing).

Lazer export:
[Foreground Eclipse - Koiyomi (StalkyBoi) Lazer.zip](https://github.com/ppy/osu/files/14308838/Foreground.Eclipse.-.Koiyomi.StalkyBoi.Lazer.zip)

Stable export:
[Foreground Eclipse - Koiyomi Stable.zip](https://github.com/ppy/osu/files/14308845/Foreground.Eclipse.-.Koiyomi.Stable.zip)

Website: https://osu.ppy.sh/beatmapsets/2134190

**Comment by ssz7-ch2** [comment]
I think what most likely happened here is the base velocity was changed, whether accidentally by the user or some other cause.

The version on the website is 1.75 base velocity, while the lazer and stable exports are 1.95 base velocity.
Changing the base velocity from 1.75 to 1.95 in the website version will also match the unsnapped sliders shown in the images.

**Comment by StalkyBoi43815** [comment]
> I think what most likely happened here is the base velocity was changed, whether accidentally by the user or some other cause.
> 
> The version on the website is 1.75 base velocity, while the lazer and stable exports are 1.95 base velocity.
> Changing the base velocity from 1.75 to 1.95 in the website version will also match the unsnapped sliders shown in the images.
> 
> 

That is true. So this is a skill issue and not a game issue. Thanks for telling me.
