### ISSUE TITLE
Some maps keep failing to import

### ISSUE THREAD

**Issue by MLGSquidz** [ppy/osu#2718]
I try to import maps but it doesn't work but when I delete the map it goes along the queue until another map turns out to be "faulty" too. I was wondering if there was a way to fix this. I'll throw my logs just in case that helps. 
[database.log](https://github.com/ppy/osu/files/2065471/database.log)
[network.log](https://github.com/ppy/osu/files/2065472/network.log)
[performance.log](https://github.com/ppy/osu/files/2065473/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2065474/runtime.log)
Please help! I just got through to finally getting my client to open and I'm desperate to play my favourite map which is, unfortunately, "Faulty".

**Comment by Morilli** [comment]
Seems like the same issue I've reported in #2236.

**Comment by MLGSquidz** [comment]
Yes, it does

**Comment by MLGSquidz** [comment]
full path? Like the song files? I don't quite understand what you meant by that.

**Comment by Morilli** [comment]
I'm having the same problem, so I'm just gonna help out here. The beatmaps (at least for me) are located in %localappdata%\osu!\Songs and I can assure the beatmaps are in no way faulty, as deleting and redownloading a beatmap gives the same error.
[3756 Peter Lambert - osu! tutorial.zip](https://github.com/ppy/osu/files/2070297/3756.Peter.Lambert.-.osu.tutorial.zip)

**Comment by Wieku** [comment]
I'm having the same problem. Maps are not corrupted, they work fine in osu!beta and in my cursordance visualizer i'm writing recently.

OS: Windows 10 Pro 17134.48 64-bit
Absolute path to map: C:\Users\Wieku\AppData\Local\osu!\Songs\125553 Krewella - Come & Get It (Nightcore Mix)
Packed map: [125553 Krewella - Come & Get It (Nightcore Mix).zip](https://github.com/ppy/osu/files/2070369/125553.Krewella.-.Come.Get.It.Nightcore.Mix.zip)
Logs (53 maps have failed to load): [database.log](https://github.com/ppy/osu/files/2070370/database.log)

**Comment by Wieku** [comment]
It's working now: https://img.wieku.me/18/2018-06-05_10-40-47.png

**Comment by peppy** [comment]
Great to hear, thanks for testing.
