### ISSUE TITLE
IPad 6gen | IOS 16.1 | Osu! crashes when trying to launch app. [Log file included]

### ISSUE THREAD

**Issue by Su4o** [ppy/osu#27213]
### Type

Other

### Bug description

When trying to launch the Osu! app on my iOS device, it kicks me out, instead of sideloading on a windows/macOS.

Don’t know why it crashes/kicks me out at all.

### Version

2024.131.0

### Logs

[osu LOG.txt](https://github.com/ppy/osu/files/14320215/osu.LOG.txt)

**Comment by frenzibyte** [comment]
Please do not mention what you're using to sideload the app. iOS has been broken for a while now and will hopefully be fixed starting from next release. See https://github.com/ppy/osu/issues/27017.

**Comment by Su4o** [comment]
Do you know the most recent release that would work? Thanks.a
