### ISSUE TITLE
Pinned Scores : Classic Mode Not Appended

### ISSUE THREAD

**Issue by 19peytonsmith** [ppy/osu#27222]
### Type

Game behaviour

### Bug description

Pinned Scores don't have the classic mode appended to the mods despite them being set on stable client.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/54728307/bcd9d3ab-12ed-4545-af20-514905ccf01c)

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14321390/compressed-logs.zip)

**Comment by 19peytonsmith** [comment]
Did some more investigation and it only adds it to scores pinned after a certain threshold? Within the month it looks like, surely not intended behaviour.

**Comment by peppy** [comment]
https://github.com/orgs/ppy/projects/19/views/1?pane=issue&itemId=51580056
