### ISSUE TITLE
Game crashes when external controller/joystick is plugged in

### ISSUE THREAD

**Issue by Nebula-Developer** [ppy/osu#27221]
### Type

Crash to desktop

### Bug description

On macOS 13.6.4, the game will crash when a Taiko no Tatsujin joystick is plugged in (potentially other controllers also)
This may relate to https://github.com/ppy/osu/issues/24458
The crashing is not consistent - the game will rarely work fine (the controller working in taiko), but other times it will either crash before the window opens, or after the launch animation finishes.

Sometimes (inconsistently) it logs this before crashing:
`osu!(1478,0x700002f14000) malloc: Heap corruption detected, free list is damaged at 0x6000028d4a50`

### Screenshots or videos

<img width="807" alt="Screenshot 2024-02-18 at 1 20 31 PM" src="https://github.com/ppy/osu/assets/96085977/8ab88449-b957-4c16-8271-7f36395f2ca5">

### Version

2024.131.0-lazer

### Logs

2024-02-18 13:18:16.166 osu![1478:59696] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
2024-02-18 13:18:16.166 osu![1478:59696] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
2024-02-18 13:18:16.166 osu![1478:59696] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
2024-02-18 13:18:25.920 osu![1478:59696] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
osu!(1478,0x700002f14000) malloc: Heap corruption detected, free list is damaged at 0x6000028d4a50

**Comment by peppy** [comment]
Please export and attach your logs.

**Comment by frenzibyte** [comment]
I tested on my DualSense controller both in wired and wireless mode in case this turns out to be an easy repro, but couldn't get anywhere. @Nebula-Developer For added info, you can export logs by running the game (without your controller so it doesn't crash), then go to settings and locate & press the "Export Logs" button, the attach the outputted archive.

**Comment by Nebula-Developer** [comment]
Hiya, sorry for the delay.
I haven't had any access to the controller I used when encountering the bug, as it was not my own (I was at another persons house). I will see if I can find some time to reproduce the bug and export the logs. Sorry about that.

**Comment by Nebula-Developer** [comment]
Failed to replicate this issue on the latest version of osu!.
