### ISSUE TITLE
Sideloaded osu! IPA doesent work on IPadOS 17.2

### ISSUE THREAD

**Issue by Pogzhsd2** [ppy/osu#27236]
### Type

Game behaviour

### Bug description

When i try to sideload osu! on every type
(Sideloadly, Scarlet, etc)
it doesent work, it just crashes

### Version

2024.131.0

### Logs

Just crashes and it doesent give me logs for some reason

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/27017
