### ISSUE TITLE
Multiplayer match screen

### ISSUE THREAD

**Issue by DrabWeb** [ppy/osu#2723]
![multiplayer_settings_c](https://user-images.githubusercontent.com/6215387/40883031-fa9b390c-66c9-11e8-8d3e-c4334c76bc6d.png)

![multiplayer_settings_b](https://user-images.githubusercontent.com/6215387/40883061-0843f976-66cb-11e8-9e44-179152bb89f4.png)

Should implement the match screen interface and it's individual components.

**Comment by LastExceed** [comment]
with the `invite only` option password protection seems to become redundant, or at least I can't think of a scenario where that would be useful. but in case there's such a scenario `password protected` should be an option next to `public`, `friends only` and `invite only` as a combionation (e.g. `invite` + password) makes no sense.

Further more, the structure of the UI needs work, its not intuitive at all. Even as an experienced player (i.e. someone who already knows how osu!multiplayer works) I had to look at these drafts for a solid full minute to understand whats and wheres. Also the beatmap selection area seems very small. Idk how to fit all the necessary information (name, diff name, difficulty, ect) in there.

Design is top notch though, great job with that.

**Comment by peppy** [comment]
Unfortunately the designs you see here are low effort in terms of understanding the system. Think of it as a work in progress.

**Comment by peppy** [comment]
Main screen has been added via #2708. Settings portion is a WIP, I believe. Moving to July.

**Comment by peppy** [comment]
@DrabWeb can you give us an update on whether you're still actively working on the setup screen?

**Comment by DrabWeb** [comment]
Have it mostly done just haven't finished it up yet, it'll probably be done this week.
