### ISSUE TITLE
Reverse slider arrow is reversed

### ISSUE THREAD

**Issue by Wildthing0** [ppy/osu#27241]
### Type

Game behaviour

### Bug description

I am making a map and when i went out and playtested it the slider arrow was facing the wrong way. its kind funny tbh.
the error persisted after editing the map, playing other maps, and after restarting the game
removing and replacing the slider fixed it though

editing the slider was also pretty funky

### Screenshots or videos

https://github.com/ppy/osu/assets/90672169/3e2a0480-9ef7-4a29-b57c-bf2852ce09f5

After restarting

https://github.com/ppy/osu/assets/90672169/97c53014-f273-4a3e-8fc4-f2656129f788

### Version

2024.131.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14329467/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Please attach your beatmap or any steps you have to get the reverse arrow reversed.

**Comment by Stoppedpuma** [comment]
Reproduced by adding a 3rd control point in odd positions:

![1708393506](https://github.com/ppy/osu/assets/58333920/014413db-2c5d-4150-86d8-17311cf5efa4)
![1708393873](https://github.com/ppy/osu/assets/58333920/98b6372c-ac5f-4161-8898-1cd8d3092112)

Kind of hard to see but OP seems to have done the same thing:
![1708393923](https://github.com/ppy/osu/assets/58333920/ff0b6f89-e40a-4660-bc5d-48941fa79995)

**Comment by Wildthing0** [comment]
@Stoppedpuma that seems to be the issue i am encountering, thanks
