### ISSUE TITLE
Bug: Hold notes in osu!lazer Mania displaying as normal notes with custom skin

### ISSUE THREAD

**Issue by Disc0nnect0r** [ppy/osu#27250]
### Type

Cosmetic

### Bug description

While playing osu!lazer Mania mode, I encountered a bug where hold notes are displayed as normal notes instead of their proper hold note visuals with a custom skin. This resulted in misjudgment during gameplay, where I started missing notes that appeared to be regular notes but were actually hold notes. This behavior is inconsistent with the behavior observed in stable osu! where hold notes are properly displayed with the same custom skin.

### Screenshots or videos

Skin : https://drive.google.com/file/d/1i1I6VflXC4bIBjPoqin1cANcQs28Ae6h/view?usp=sharing
video : https://drive.google.com/file/d/1grGwI8GHDEQukjakDe3WLbq90QCi1q2o/view?usp=sharing

### Version

2024.219.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14335679/compressed-logs.zip)

**Comment by longnguyen2004** [comment]
A quick look through your skin.ini shows
```
NoteImage0L: LNTail7
NoteImage0L: LNTail7
