### ISSUE TITLE
Invalid client hash on 2024.219.0 release

### ISSUE THREAD

**Issue by Kiciuk** [ppy/osu#27268]
### Type

Other

### Bug description

After updating client there is msg regarding not being able to submit score,
exported logs mention following error:
`Response was: {"error":"invalid client hash"}`

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/6343178/66f3004e-9af6-4248-a7f9-134a411f000e)

### Version

2024.219.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14342595/compressed-logs.zip)

**Comment by smoogipoo** [comment]
- Does it still happen after restarting the game?
- Do you have any antivirus installed other than the Windows default?

**Comment by Kiciuk** [comment]
> * Does it still happen after restarting the game?
> * Do you have any antivirus installed other than the Windows default?

1) Just restarted and seems to be resolved -no longer popup when starting map and score got submitted
2) Only default defender.
