### ISSUE TITLE
taiko and mania difficulties appear as grey on song select

### ISSUE THREAD

**Issue by pablo5425** [ppy/osu#27269]
### Type

Cosmetic

### Bug description

any song that has taiko and/or mania maps will display their difficulties without any color
however colors are displayed correctly when the song is clicked to view difficulty select

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/34631489/ade1da98-0e45-45ca-bb07-a995ff9589c2)
![image](https://github.com/ppy/osu/assets/34631489/8a07f6ac-e187-4dcc-93f0-ae3a786166c0)
![image](https://github.com/ppy/osu/assets/34631489/9e717652-d561-4d49-9134-19252676cd18)

### Version

2024.219.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14342760/compressed-logs.zip)

**Comment by longnguyen2004** [comment]
Does a game restart fix the issue?

**Comment by pablo5425** [comment]
> Does a game restart fix the issue?

it did. i guess there was some weird cache thing going on and didnt load those colors
