### ISSUE TITLE
Remember username still remembers your username when disabled.

### ISSUE THREAD

**Issue by Toasterly** [ppy/osu#27272]
### Type

Cosmetic

### Bug description

Logging out of Lazer and disabling the "Remember Username" option after it was previously on will cause your username to still appear in the text field on start-up.

### Screenshots or videos

https://github.com/ppy/osu/assets/37195727/58f805bb-7c8f-4e61-8751-fca0d6f9685f

### Version

2024.219.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14346929/compressed-logs.zip)

**Comment by bdach** [comment]
The config setting is pretty much only written to after a successful login. It should really be getting cleared after this checkbox is deselected.
