### ISSUE TITLE
Game freezes during start of gameplay 

### ISSUE THREAD

**Issue by AIOM786** [ppy/osu#27273]
### Type

game behaviour 

### Bug description

Upon starting a map in the Osu!Catch ruleset the game freezes for a moment. 

### Screenshots or videos

In Lazer

https://github.com/ppy/osu/assets/149255845/37e15baf-dabd-438d-9ce8-95667d9ff474

In Stable

https://github.com/ppy/osu/assets/149255845/e3d8d05e-a047-4aa9-ac7f-727f97b8c18a

### Version

2023.1026.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14349340/compressed-logs.zip)

**Comment by Shavixinio** [comment]
FYI This bug appears on all gamemodes. The game freezers like this only when the song starts during the in this case - fruits falling down. If a song starts before the first mania note, ctb fruit or click circle appears, you won't be able to notice the bug.
