### ISSUE TITLE
Approach circle doesnt hit the hitcircle on the perfect tap moment on imported skins

### ISSUE THREAD

**Issue by Raregendary** [ppy/osu#27283]
### Type

Game behaviour

### Bug description

In osu lazer with imported skins i have an issue where the perfect timing hit would be when the approach circle is few pixels away from the hitcircle. The issue isn't present in the default skins that are coming with lazer. Also i played the game before in 2021 and it didn't have this issue.

You can literally open a map and when you switch skins live you can see how the hit circle on the classic skin and my imported skins is smaller than the hit circle on the lazer default skins.

### Screenshots or videos
The issue was recorded using replay and auto pilot mod not live gameplay.
In the bottom of the screenshot there is a frame indicator.
My imported skin:
![1](https://github.com/ppy/osu/assets/71941668/f87ee1cc-467e-47d8-87e0-575cc9279d1d)
![2](https://github.com/ppy/osu/assets/71941668/14d0569d-34be-4c9a-af53-eee1157cc34d)

Default osu lazer skin:
![3](https://github.com/ppy/osu/assets/71941668/23b96d48-7985-4adc-8b5c-e1615b9efe2d)
![4](https://github.com/ppy/osu/assets/71941668/b1bacc2c-392f-4fd3-b72f-98d2d3e1d203)

The timing altho not important for this seems to be between + 10-20 ms from playing the game 30 mins and looking at suggested offset, altho its still unreadable.

The following 2 pairs are on 0.5 slowdown instead of 0.05 so if there is a slightly bigger gap it should be ignored due to recording in 60 fps and approach circle is fast :)

The same skin in osu stable doesn't have this issue and its perfectly snapped:
![5](https://github.com/ppy/osu/assets/71941668/e55ae40d-8612-43ba-87bf-cf37597b054d)
![6](https://github.com/ppy/osu/assets/71941668/5963556b-5e78-4bb9-97be-855526d1b653)

Older 2021 lazer version around the time i last played it doesn't have said issue:
![5](https://github.com/ppy/osu/assets/71941668/9a4aff58-ce2d-415c-bf12-713673b9cd8e)
![6](https://github.com/ppy/osu/assets/71941668/54d3289b-45d2-4134-979c-301fa6fddb09)

First observed issue when lazer pp got released and downloaded the game then.

### Version

2024.219.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14352349/compressed-logs.zip)

**Comment by Raregendary** [comment]
After losing my hearing installing few versions and testing i found that the issue first appeared in 2024.130.2. From 2024.114.0 and before it wasn't.
![image](https://github.com/ppy/osu/assets/71941668/19a041ba-7b7f-41bc-8c14-32d98837518d)

**Comment by peppy** [comment]
@Raregendary attach skin please.

**Comment by Raregendary** [comment]
> @Raregendary attach skin please.

It happens with all my skins and even the osu classic default skin but i used this skin for all the screenshots:
[-        # WhiteCat (1.0) 『CK』 #-.zip](https://github.com/ppy/osu/files/14353620/-.WhiteCat.1.0.CK.-.zip)
