### ISSUE TITLE
Expanded local user card from toolbar overflows at 7 digits and/or language-based wide spaces

### ISSUE THREAD

**Issue by HastagGuigui** [ppy/osu#27296]
### Type

Cosmetic

### Bug description

If you look at your player card while playing in french, the spaces may overflow the rank text.
It is to note that this only happen in french, as every other language that uses spaces (screenshot 2, Česky) seem to use a different kind of space.
Overall, if you're a 7-digit (rank 1 000 000 and higher), the space for the rank on your profile card seems a bit small.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/47950669/6a46d152-75de-4ab9-9b31-40158230274b)
![image](https://github.com/ppy/osu/assets/47950669/f0050a18-0737-4a84-a853-3467c8b7beb6)
![image](https://github.com/ppy/osu/assets/47950669/646d0f5f-d622-4d93-bff5-037a6eb5a1fc)

### Version

2024.219.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14362900/compressed-logs.zip)

**Comment by frenzibyte** [comment]
It's already looking bad on English with 7 digits. Needs reconsideration.

**Comment by bdach** [comment]
See also: https://github.com/ppy/osu/pull/27147#issuecomment-1943920629

**Comment by Joehuu** [comment]
I think truncating the rank (i.e. 1.03M) and showing the exact one with a tooltip would be another solution if we don't want to increase the width.

We have results screen doing that for no reason (there's a lot of width here):
![osu!_4uAaOxg7BP](https://github.com/ppy/osu/assets/35318437/64075e5f-5d31-43d1-8bc3-f4cdb57a8190)
