### ISSUE TITLE
Crash on exit, attempting to swap buffers when window is rip

### ISSUE THREAD

**Issue by nashiora** [ppy/osu#273]
Just because I was impatient, I decided to press the Windows X button after clicking Exit in game.

Turns out that crashes everything, and it looks like the game continues to try to swap the backbuffer after the window is closed. Just to say I tried to fix it, I used the ?. operator at the call site and the crash still happens, so it's internal to the window (since the issue isn't a null reference) and I haven't dug any farther.

I'm using Rider right now and don't know how to access useful info, but it's reproducible 100% of the time on my machine and it's really easy to do, so I'll just assume you can press two buttons one after the other (it's not like you're bad at osu!, right? you got this.)

If you can't make it happen, I'll pull it up in VS and get info out of it if I can.

Crash on BasicGameHost.cs line 253, calling SwapBuffers on Window

**Comment by peppy** [comment]
thanks for the report, but we don't really need these kinds of reports at the moment unless you are willing to actually provide a solution.

we are already aware of this and other bugs, but they are low priority currently.

**Comment by nashiora** [comment]
Had to be ready for work not long after this, so I didn't bother looking too deep into it. I can dig deeper soon and try to find a solution, thanks for making me aware.
