### ISSUE TITLE
Repeatable and consistent microstutters

### ISSUE THREAD

**Issue by arturino009** [ppy/osu#27306]
### Type

Performance

### Bug description

This is a very strange issue. I've disabled everything I could and reinstalled a bunch of drivers, but I still get these weird and regular microstutters which bring an insanely annoying latency spike. These are the things that I managed to deduce:
1.) During gameplay, this stutter always happens in ~14 second intervals. Regardless of beatmap. I can also sometimes see the same graph spike when I restart a beatmap, although sometimes it doesnt appear. But it will always appear in the first ~9 seconds of a beatmap. After that its 14 seconds again.
2.) If im just idling in the song selection screen, I also get a consistent bump in the metrics every ~19 seconds. Its barely noticable in the graph, but it does have a bump in the Invalidations, Refreshes and DrawNodeAppl columns for Update and UniformUpl for Draw (there is absolutely no impact in Input and Audio).

Im seriously lost with this one. Tried using procmon to and task manager to see any CPU usage spikes, but there was nothing. Looking for any suggestions.

### Screenshots or videos

![Spike](https://github.com/ppy/osu/assets/51629394/39bb6c46-2575-4c60-a9de-f324b14a188e)

### Version

2024.221.0-lazer

### Logs

[1708561920.network.log](https://github.com/ppy/osu/files/14367193/1708561920.network.log)
[1708561920.runtime.log](https://github.com/ppy/osu/files/14367194/1708561920.runtime.log)
[1708561920.updater.log](https://github.com/ppy/osu/files/14367195/1708561920.updater.log)
[1708561920.performance.log](https://github.com/ppy/osu/files/14367196/1708561920.performance.log)

**Comment by peppy** [comment]
Looks like GC, even though things are in a better place than ever in terms of memory allocations (maybe it's hardware / CPU specific).

Does reducing your frame limiter make them occur less frequently?

**Comment by arturino009** [comment]
![2](https://github.com/ppy/osu/assets/51629394/11ddd278-ebaa-4a09-b719-5ee8ac6361f6)
I reduced it to 2x refresh rate and vsync and now it does occur less often: i would say about every ~19-20 seconds during gameplay. Also I dont know if this is intended but when I use vsync limiter the Draw graph is at 1000hz instead of 180hz (might be VRR though).

**Comment by arturino009** [comment]
I also changed my monitor to 60hz and tried vsync limiter. The spike happens after every ~30 seconds now

**Comment by acha666** [comment]
![image](https://github.com/ppy/osu/assets/37405625/0b60398f-448b-4eed-87b6-f85ba70037ad)
same problem after updated to 2024.221.0
for me, it happens about every 6-7 seconds
In older version I always keep refresh rate unlimited, and it was able to keep 1000 fps and it was very stable

**Comment by peppy** [comment]
> Also I dont know if this is intended but when I use vsync limiter the Draw graph still shows 1000hz instead of 180hz (its clearly not refreshing at 1000hz).

This will happen if you've forced vsync off in your drivers, as you'd expect.

**Comment by peppy** [comment]
> same problem after updated to 2024.221.0

no this is not the same problem. you're seeing gpu hitching for some other reason.

**Comment by arturino009** [comment]
Is there anything I can do to investigate this further? Is there a way to get more specific metrics or deduce the issue with a profiler?

**Comment by WyuerKa** [comment]
Same problem on MacOS too after updating to 2024.219.0, very annoying to play now. It always stutters once in the first 15 secs of every beatmap, no matter what renderer, frame limiter or skin I use. Had 0 stutters on the previous version.

[compressed-logs.zip](https://github.com/ppy/osu/files/14394299/compressed-logs.zip)
