### ISSUE TITLE
Add linking from import notifications to select beatmap

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2731]
Clicking "import complete" notifications should switch the current beatmap to the imported one (if possible in current game state).

High priority in terms of usability. Covers manual import and osu!direct downloads.

**Comment by DrabWeb** [comment]
I think when #2735 is merged, the download buttons should change to open buttons when a beatmap set is downloaded.

**Comment by peppy** [comment]
Yep, definitely. Not sure on the design for this yet, but feel free to choose an arbitrary FA icon for the time being and we can iterate from there.
