### ISSUE TITLE
Incorrect Redirect on Map made by another user

### ISSUE THREAD

**Issue by 19peytonsmith** [ppy/osu#27313]
### Type

Game behaviour

### Bug description

I like the idea of the redirect to whoever mapped a difficulty in a set to go to the difficult creator rather than the person hosting the set. However as it currently stands it's a bit inconsistent with the UX. It says it was mapped by the creator of the set but redirects to the difficult creator. To make it consistent, I suggest making it say Mapped by <Difficult creator> instead of the creator of the set.

Or better yet have both info present, like Mapped by <Difficult creator> and below that have set made by <Set creator>

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/54728307/981a4ff4-c904-4516-a254-33f291f2ac65)

In this example saying

> mapped by LosPedros
> set by Moko

makes a lot more sense

### Version

2024.221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14373103/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/12965
