### ISSUE TITLE
Map will not exit / terminate on completion

### ISSUE THREAD

**Issue by itsfprime** [ppy/osu#27327]
### Type

Crash to desktop

### Bug description

Any play I set on lazer will not terminate the "game phase" and switch to the results screen. Please note the "Difficulty Adjust" and "Classic" mods were enabled during this issue. Pressing "Alt + F4" would reset the game to the start screen as a way to get around this issue, but otherwise I could not find a fix.

### Screenshots or videos

https://github.com/ppy/osu/assets/80008010/fe3c9162-2746-4ea3-9ffc-0e6d45f3eb1c

### Version

2024.130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14377958/compressed-logs.zip)

**Comment by bdach** [comment]
I have no idea how you entered this state but apparently you're not logged in.

```
2024-02-22 18:12:33 [verbose]: Score submission token retrieval failed (API is not online.)
```

First and foremost I would try updating the game, 2024.130.2 is a bit outdated now. If that doesn't help then please attach a full video of what the game does boot to a play finish.

**Comment by itsfprime** [comment]
> I have no idea how you entered this state but apparently you're not logged in.
> 
> ```
> 2024-02-22 18:12:33 [verbose]: Score submission token retrieval failed (API is not online.)
> ```
> 
> First and foremost I would try updating the game, 2024.130.2 is a bit outdated now. If that doesn't help then please attach a full video of what the game does boot to a play finish.

I really thought my game was updated haha. I will try updating, and maybe the up-to-date client will allow me to sign in.

**Comment by itsfprime** [comment]
A few things to note

1.) My computer seemed to bug out a little bit, I had 2 instances of Osu! running in the background after closing them previously for some reason, which may have caused the initial issues.
2.) Upon closing the background instances, Lazer client decided to download the update on startup
3.) Upon opening the new version of Lazer, I was immediately signed in, and play submission worked as expected.

Sorry for the confusion! I think my computer may have bugged a bit, or perhaps I met some weird parameter in the closing of Osu! Stable and Lazer. Thank you!

**Comment by bdach** [comment]
> I had 2 instances of Osu! running in the background after closing them previously for some reason, which may have caused the initial issues

I'm reopening this for myself just to make sure to double-check this because this sounds not good. Might mean that entering the broken state involves opening two instances of the game and playing on the one that got logged out or something.

**Comment by bdach** [comment]
Upon a quick check in 2 different scenarios involving a logout mid-gameplay I've been unable to reproduce a full-on refusal to complete gameplay so I'm just going to look the other way and hope whatever happened above was just a freak accident and will not happen again.
