### ISSUE TITLE
Ranked sorting not working properly (After game update note "Fix beatmap carousel ordering not matching expectations")

### ISSUE THREAD

**Issue by Hendshues2** [ppy/osu#27335]
### Type

Game behaviour

### Bug description

Date Ranked sorting option isn't working properly, it's all over the place, there's no way Xeroa was ranked before rog-unlimitation because rog-unlimitation was ranked in 2012 while Xeroa was ranked in 2022. In case the sorting is top to bottom (oldest at the top) it also isn't accurate because MIIRO vs. Ai no Scenario was ranked in 2015 which is after rog-unlimitation. i've uploaded different screenshots through imgur in "screenshots or videos" for better explanation (i'm making a new Issue because the most recent update said "Fix beatmap carousel ordering not matching expectations" and assumed this was meant to fix it however i'm still seing the issue, i'm aware that there's Issue 22416 open however that 1 is from a while ago and i'm assuming this is a brand new issue now)

### Screenshots or videos

What i read on the ingame update notes: https://i.imgur.com/gllyRxQ.png

osu!lazer sorting image: https://i.imgur.com/gjLi0zw.png

MIIRO vs. Ai no Scenario: https://i.imgur.com/VBWsi7w.png
rog-unlimitation: https://i.imgur.com/PUaY9oG.png
Xeroa: https://i.imgur.com/VXpdxQz.png

further examples:
https://i.imgur.com/WSHuHcw.png
(same map just in details https://i.imgur.com/Iq26bu4.jpeg )

https://i.imgur.com/v4bad1Q.png
(same map just in details https://i.imgur.com/B1uvGi6.jpeg )

https://i.imgur.com/nMmUrJF.png
(same map just in details https://i.imgur.com/ZOvEiqs.jpeg )

no matter how i see it, a map ranked in 2012 shouldn't be in between a map ranked in 2015 and a map ranked in 2022.

### Version

2024.221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14380717/compressed-logs.zip)

**Comment by bdach** [comment]
The change you mention only affected textual sorting and not sorting by ranked date.

The actual issue here is probably https://github.com/ppy/osu/issues/22416. Please attach `client.realm` from game directory to confirm.

**Comment by peppy** [comment]
Definitely going to be a duplicate. Let's track in #22416.
