### ISSUE TITLE
In the playlist menu box, dragging down or up on a point in the song lags the game and distorts the audio

### ISSUE THREAD

**Issue by escolasticokid** [ppy/osu#2733]
On the song select box in the top right, obviously the current part of the song can be dragged ahead or behind, but when you drag this yellow bar down, it lags terribly, distorting the audio as well
https://youtu.be/4_OLOe1XrAY

**Comment by Aergwyn** [comment]
I assume the dragging down causes rapid seeking at nearly the same point.

**Comment by escolasticokid** [comment]
That sounds right, it just taxes my hardware when I do it so much that the game lags and the audio also freaks out

**Comment by smoogipoo** [comment]
Has since been fixed.
