### ISSUE TITLE
Osu! crashes when adding a video to the beatmap [Osu!Stable]

### ISSUE THREAD

**Issue by GamingWithJanko** [ppy/osu#27349]
### Type

Crash to desktop

### Bug description

Title pretty much says it all.

### Screenshots or videos

[2024-02-23 22-45-52.webm](https://github.com/ppy/osu/assets/48768314/d871c120-0ec2-4617-b7f9-e969218cd961)

### Version

b20240123

### Logs

[Logs.zip](https://github.com/ppy/osu/files/14390411/Logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu-stable-issues is where these are supposed to go.
