### ISSUE TITLE
Import notifications for single beatmaps interrupt while in direct

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu#2734]
Scenario:
Enter osu!direct from the main menu.
Start browsing for beatmaps. Find a map you like, hit download. Scroll to look for other maps.
What happens: The notification overlay opens and turns your scrolls into changing volume. I think that's unexpected.
![](https://i.imgur.com/eumF7Zb.png)

Same when a map finishes importing/downloading.

Somewhat related to #2640 (although that one is about the 'import from stable' notification)

**Comment by peppy** [comment]
Will be fixed once we have a toast notification implementation.

**Comment by Joehuu** [comment]
Can be closed (original issue is resolved and #4811 specifies toast notifications).
