### ISSUE TITLE
Scores not submitting to stable servers through Lazer

### ISSUE THREAD

**Issue by akitorunsyou** [ppy/osu#27363]
### Type

Other

### Bug description

I got a score that would have been my #2 play, but it wasn't submitted to the main servers after around 15 minutes.
Screenshots (first set of 3) are of the result screen/local score list 15 minutes after it was set in Lazer, and my top play section of my profile. The play was 195pp, so it should have been visible there. This also happened to be before on mania when I set another #2 play on galaxy collapse +ht, its still not there. screenshots also provided. (second set of 3)

### Screenshots or videos

<img width="450" alt="Screenshot 2024-02-24 at 11 35 35 AM" src="https://github.com/ppy/osu/assets/153377905/c35879e2-65f3-4cbc-8870-25c46513835a">
<img width="646" alt="Screenshot 2024-02-24 at 11 35 51 AM" src="https://github.com/ppy/osu/assets/153377905/3b63085f-d441-4a60-93c0-96c360dc39e4">
<img width="1151" alt="Screenshot 2024-02-24 at 11 36 10 AM" src="https://github.com/ppy/osu/assets/153377905/24f79e37-5aac-420c-b27b-4cec427dd829">
<img width="451" alt="Screenshot 2024-02-24 at 11 40 45 AM" src="https://github.com/ppy/osu/assets/153377905/30bd2f48-1054-4dcd-aa53-22f9a2072b94">
<img width="659" alt="Screenshot 2024-02-24 at 11 41 02 AM" src="https://github.com/ppy/osu/assets/153377905/f71a3632-94f2-4761-a82f-6b811d8a785a">
<img width="1139" alt="Screenshot 2024-02-24 at 11 41 23 AM" src="https://github.com/ppy/osu/assets/153377905/984120ab-30ca-419a-b868-ee636cb9227b">

### Version

2024.130.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14393643/compressed-logs.zip)

**Comment by bdach** [comment]
Also if you're on 2024.130.2 then update because you won't be able to submit any scores at all on that build anymore.

**Comment by akitorunsyou** [comment]
> Also if you're on 2024.130.2 then update because you won't be able to submit any scores at all on that build anymore.

oh, i never got a notification in game telling me i needed to update. my bad then, thanks for the help.
