### ISSUE TITLE
PP is subtly different from web on a certain score

### ISSUE THREAD

**Issue by generalh104** [ppy/osu#27368]
### Type

Behavioural

### Bug description

When viewing a score, the "Achieved PP" value on the "Performance Breakdown" screen (right side) is truncated instead of rounded. The PP value on the smaller results screen (left side) is correct and matches the website.
![osu_2024-02-24_15-30-05](https://github.com/ppy/osu/assets/63620677/048319ad-e3d1-4dbc-aa3e-e5ea2860060e)

The exact PP value on the website is 244.516.
![Screenshot from 2024-02-24 15-42-36](https://github.com/ppy/osu/assets/63620677/c798446c-fc7a-4ce8-b41f-9f62323f568d)

After watching the replay, the PP value shown on the smaller results screen is also displayed incorrectly as 244.
![osu_2024-02-25_15-50-28](https://github.com/ppy/osu/assets/63620677/db6bec04-7c9a-47ec-92b6-43668f6ba0a7)

Here is another example of the same issue. Exact PP value on the website is 634.63
![osu_2024-02-24_15-52-48](https://github.com/ppy/osu/assets/63620677/c28b6f81-3bd8-4735-a007-35e54b1169b9)

### Version

2024.221.0-lazer (linux)

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14394414/compressed-logs.zip)

**Comment by frenzibyte** [comment]
The score in question shows a slightly different PP with the `PerformanceCalculator` compared to web:

![CleanShot 2024-02-27 at 00 56 06](https://github.com/ppy/osu/assets/22781491/77562e25-cfcc-4bc2-9689-515b529d6199)

(notice it's ~244.442 instead of ~244.516, therefore getting rounded down to 244).

**Comment by bdach** [comment]
Live pp (even on lazer) is a few changes behind local in-client pp. So this is likely completely normal and expected.

**Comment by generalh104** [comment]
:+1: closing, thank you :D
