### ISSUE TITLE
Seeking over and over the beginning of spinner SPM exponentially freezes the game

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#27362]
### Type

Performance

### Bug description

Happens on both editor and autoplay/replay.

Important points (a little bit long to digest, but I'll try to be brief):
1. [Video is 2 minutes long](https://youtu.be/2WVfCH53SvE), and definitely exceeds the limit imposed by GitHub. I kept it in 1080p so that I could clearly show you the values of statistics. (You can also skip to 44 seconds to see the lag.)
  The video shows a short version of the issue, but I can swear I even got as far as waiting about 20 seconds before the game started working again (and I guess the lag only continues to increase).
2. Could be related to https://github.com/ppy/osu/issues/10455 (since spinners have been known to be a bit.. erratic in the editor), however maybe point 3 contradicts that?
3. Autoplay seems to be affected by this as well, here's [a video example](https://github.com/ppy/osu/assets/43073074/f5ad82c2-494c-4953-813b-2d8359493e74) (skipping straight to the issue, since you would have to seek a bunch of times, and it seems that it can only be done with a very short time frame before the spinner).
  ~~Not sure about replays, I haven't tested yet.~~
  Can also be reproduced with user-made replays.
4. I don't know much about what statistics I could focus on. The only one I learned was to look at the "Top CPU consumers," and indeed at the top comes `ArgonSpinner`, and you can also see the frame graph "freezing".
5. Skin used is the default argon one (non-pro).
6. I tested the issue on a very random local map, and I'll avoid sending it for track reasons, but can be tested on any map.
  (See also the next point for a map where to try this.)
7. With further testing, I think this narrows down the issue to the SPM counter:
  I tried to reproduce it on another random map, [this one](https://osu.ppy.sh/beatmapsets/819112#osu/1720675).
  Re-opening the editor (by exiting about halfway through the spinner at the beginning of the map) causes the spinner's SPM to appear later (another bug?) for some reason, and you can see/reproduce the issue exactly at that moment (and not at the beginning of the spinner).
  Here's [a low-res video](https://github.com/ppy/osu/assets/43073074/9b99f35e-e6fe-4019-8d3b-6f835e583bb8) explaining this.
8. In both the local map and the one linked above, the spinner is the first object; but this doesn't seem to be required to reproduce.
9. If you pass the end of the spinner (or go far enough back), the issue resets

### Version

2024.221.0

### Logs

n/a?

**Comment by Gabixel** [comment]
As a side note: the video on point 2 shows `Container` as the top CPU consumer. (It probably had something to do with the fact that I clicked the button to forward the track for one frame.)

![image](https://github.com/ppy/osu/assets/43073074/67fd3e54-c4ac-4484-94f0-a652c47bff66)

If I let the replay go on its own, `ArgonSpinner` appears:

![image](https://github.com/ppy/osu/assets/43073074/a51ac56c-402c-4f26-a982-ebe0b47ecdb3)

**Comment by peppy** [comment]
@Gabixel can you test on https://github.com/ppy/osu/pull/27359 to see if it's any better?

**Comment by Gabixel** [comment]
What a coincidence! Didn't notice that PR before reporting this, and it seems to solve this issue!
I've done various tests that should come to these lag spikes, but I can't notice a single one of them. Definitely feels smooth.

**Comment by Gabixel** [comment]
Closing as fixed by https://github.com/ppy/osu/pull/27359
