### ISSUE TITLE
Beatmap status doesn't match website

### ISSUE THREAD

**Issue by Ladwick** [ppy/osu#27402]
### Type

Cosmetic

### Bug description

Aside from the map status on the beatmap wedge, it seems to be a solely 'Cosmetic' bug, I tried deleting and redownloading the map, playing it, closing and re-starting the game and nothing seemed to fix the issue, and the fact that the score submitted correctly makes me think it's just cosmetic too. Haven't experienced it with any other beatmapmap.

Hope it's not a duplicate.

### Screenshots or videos

![osu_2024-02-27_10-31-26](https://github.com/ppy/osu/assets/37979533/18acb310-6817-4e6a-91f3-93bfc94837c6)
![osu_2024-02-27_10-31-38](https://github.com/ppy/osu/assets/37979533/4c81105d-2a61-456e-8565-28afe77c4202)

### Version

2024.221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14421305/compressed-logs.zip)

**Comment by bdach** [comment]
Can't reproduce.

- When did you import the map?
- Please try deleting the map, restarting the game, and then re-importing it, in that order specifically.

**Comment by Ladwick** [comment]
I imported the map the day they released the pp update.

Doing it in the order you said solved it, probably re-importing the map was not fixing it for me because I didn't restarted after deleting and the game was caching the beatmap status due to the soft deletion feature or smth like that? Anyway, sorry for the inconveniences and thanks for your help!

**Comment by bdach** [comment]
> because I didn't restarted after deleting and the game was caching the beatmap status due to the soft deletion feature or smth like that?

Correct.

This is probably going to be the same thing as https://github.com/ppy/osu/issues/27332.

**Comment by Ladwick** [comment]
Oh, I saw that issue while trying to avoid duplicates but since that issue was behaving differently and mostly oriented to an issue with scores not submitting I thought it may be a different thing.
