### ISSUE TITLE
No audatory feedback when switching editor modes using keybinds

### ISSUE THREAD

**Issue by developomp** [ppy/osu#27400]
### Type

Game behaviour

### Bug description

When in editor, players can switch between modes either by clicking the buttons on the top right corner of the screen or using keybinds (<kbd>F1</kbd>, <kbd>F2</kbd>, <kbd>F3</kbd>, and <kbd>F4</kbd>). Here, audatory feedback is implemented for the buttons, but not for keybinds. This is inconsistent between other parts of the game where the same audio feedback is played regardless of whether they are using mouse or keybinds (in song select, for example).

### Screenshots or videos

[untitled.webm](https://github.com/ppy/osu/assets/40858122/dcf9de1e-f97a-4555-b08c-aa04eea13bff)

### Version

2024.221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14418404/compressed-logs.zip)

**Comment by peppy** [comment]
Not an easy one to fix due to the behaviour being provided by `HoverClickSounds` at an `OsuTabItem` level:

https://github.com/ppy/osu/blob/02bb506cce02df332ff4f884462bc5e24dfac949/osu.Game/Graphics/UserInterface/OsuTabControl.cs#L199


Probably needs the click part to be moved to `OsuTabControl` and handle `Current` changes.

**Comment by frenzibyte** [comment]
Playing a sound on every change to every `OsuTabControl` is a bit of an overkill and hard to control. Here's one place that gets affected negatively when doing so, for example:

https://github.com/ppy/osu/assets/22781491/1d56b51a-4ce0-4924-acce-6cb59aeb0192

(notice the "Sort by" tab switching and causing a click sample to trigger)

I think it's best to handle this case-by-case instead, similar to how we generally trigger button clicks from key bindings to play the button click samples.
