### ISSUE TITLE
Stable PP increase after play one lazer map

### ISSUE THREAD

**Issue by ABCDF0804** [ppy/osu#27409]
### Type

Other

### Bug description

first time here, not sure should I ask it as Issue, but anyway.
Date is 2024/2/28, for test the diff from stable and lazer, I open lazer and play a single map, after that my total pp suddenly increased about 200, my rank from 72679 up to 66,464.
the map is https://osu.ppy.sh/beatmapsets/1012262#osu/2266773

I read the recent changelog, and seems there is no pp rework in recent day, so I don't think it just another pp rework help me,
how does lazer affect my pp? and does that mean lazer now can make effect to pp system? or there just some log I miss. 

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/56595474/028819c6-91c6-4c41-a346-2fe4f8e44b67)

Even the my rank rises, but the Recent didn't show any score about the map I played and how much pp I get.
![image](https://github.com/ppy/osu/assets/56595474/5d4d5fc9-a9a4-4bb7-a280-386c2db1b872)

### Version

stable: b20240123 lazer: 2024.221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14424929/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/27174
