### ISSUE TITLE
Volume bar won't fade in osu!catch if enabled during gameplay

### ISSUE THREAD

**Issue by MkGuh** [ppy/osu#27423]
### Type

Performance

### Bug description

This is caused if player is using arrow keys to move the catcher, this action will keep selecting the volume options and it won't disappear as it should.

### Version

2024.221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14440302/compressed-logs.zip)

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/19362
