### ISSUE TITLE
Difficulty filter doesn't work for convert beatmaps

### ISSUE THREAD

**Issue by MkGuh** [ppy/osu#27422]
### Type

Game behaviour

### Bug description

Sorting by difficulty for convert beatmaps while playing other game modes won't work, as it will still filter by standard's star rating.

### Version

2024.221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14440291/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Duplicate of https://github.com/ppy/osu/issues/12628
