### ISSUE TITLE
osu!mania key images leave tiny gaps between columns

### ISSUE THREAD

**Issue by Saerdna123** [ppy/osu#27431]
### Type

Cosmetic

### Bug description

In mania on certain ColumnWidth values the KeyImage element leaves gaps. Screenshot uses ColumnWidth: 45,45,45,45,45 and KeyImage dimensions: 100 x 412 using mania-key@2x.

### Screenshots or videos

![osu_2024-02-29_08-23-50](https://github.com/ppy/osu/assets/33616260/3e79a71d-8901-448b-a07f-c2388d2f31b0)
![enhance](https://github.com/ppy/osu/assets/33616260/6b0ff20c-768c-4417-a97d-b41f2fe5a4f6)

### Version

2024.221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14451209/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Please attach your skin.

**Comment by Saerdna123** [comment]
[o2def2 (Saerdna).zip](https://github.com/ppy/osu/files/14463074/o2def2.Saerdna.zip)
here is my skin

**Comment by frenzibyte** [comment]
Isolated to a framework-level issue:

![CleanShot 2024-03-01 at 22 04 04](https://github.com/ppy/osu/assets/22781491/67b2347e-3cc8-4719-b54c-ab58e5b11cac)

([white-texture.png](https://github.com/ppy/osu/assets/22781491/9f073d59-d069-4ed6-b45d-71f537e5afa3) is literally just a 512x512 block of white pixels).

**Comment by frenzibyte** [comment]
After a period of investigation, it appears that the gaps are caused by the texture shader sampling beyond the texture's bounds, leaving a black/gray pixel between keys. Using `WrapMode.ClampToEdge` works around the issue.
