### ISSUE TITLE
Score submission fails on Loved and Qualified maps

### ISSUE THREAD

**Issue by Slim-3** [ppy/osu#27458]
### Type

Game behaviour

### Bug description

Within the past 2 days scores on Loved and Qualified maps do not submit to leaderboards, you can also still pull them from the api.

My last submitted loved score was on Feb 27th 8:55 EST on https://osu.ppy.sh/beatmapsets/643448#osu/2627239
The first failed submission was Feb 29th 7:57 EST on https://osu.ppy.sh/beatmapsets/755844#osu/1590814

### Version

2024.221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14467871/compressed-logs.zip)

**Comment by peppy** [comment]
Oversight from `Ranked` flag change, will require an osu-web side fix [around this code](https://github.com/ppy/osu-web/blob/master/app/Models/Solo/Score.php#L123-L126).

This will be retroactively fixed with an ES reindex, which is planned regardless.

**Comment by RBQcat** [comment]
Should have been fixed by https://github.com/ppy/osu-web/pull/11056 ?

**Comment by peppy** [comment]
Correct.
