### ISSUE TITLE
osu!lazer believes it is running an out-of-date version after crashing on the 2024.302.0 version

### ISSUE THREAD

**Issue by AppleRank** [ppy/osu#27466]
### Type

Crash to desktop

### Bug description

The game worked perfectly fine for about 15 minutes upon automatically updating and restarting to the latest version, but I opened a random song on catch (that had always worked perfectly fine before) which suddenly crashed the game, and reopening lazer causes it to believe it is no longer running the latest version despite the settings contradicting it.

### Screenshots or videos

![Screenshot (97)](https://github.com/ppy/osu/assets/80185907/27612694-df15-4145-8f59-0035f904d46b)
![Screenshot (98)](https://github.com/ppy/osu/assets/80185907/f983a47d-fcbf-4d26-8cb8-e985f95b9244)

### Version

2024.302.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14469635/compressed-logs.zip)

**Comment by Crumpetfiddler** [comment]
Same issue except I never had the crash

**Comment by tovc** [comment]
https://github.com/ppy/osu/assets/49025619/4a35a4ab-112e-4e99-bb6d-f123c1f8d9e3

![image](https://github.com/ppy/osu/assets/49025619/4a9ff7ec-a288-4456-9aa3-4dc40878fd7c)

**Comment by DenisHIK522** [comment]
same
![image](https://github.com/ppy/osu/assets/56361522/e45e1c79-518f-4381-bce2-8543f9eaa025)

**Comment by AppleRank** [comment]
Event Viewer Logs related to osu! crash:
**First Log:**
Log Name:      Application
Source:        .NET Runtime
Date:          3/2/2024 9:56:42 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-3GH0UJ7
Description:
Application: osu!.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at ManagedBass.Bass.FXSetPriority(Int32, Int32)
   at ManagedBass.Bass.FXSetPriority(Int32, Int32)
   at osu.Framework.Audio.Mixing.Bass.BassAudioMixer+<>c__DisplayClass29_0.<onEffectsChanged>g__applyEffects|2(Int32, Int32)
   at osu.Framework.Audio.Mixing.Bass.BassAudioMixer+<>c__DisplayClass29_0.<onEffectsChanged>b__0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean)
   at osu.Framework.Audio.AudioComponent.Update()
   at osu.Framework.Audio.AudioCollectionManager`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].UpdateChildren()
   at osu.Framework.Audio.AudioComponent.Update()
   at osu.Framework.Threading.AudioThread.onNewFrame()
   at osu.Framework.Threading.GameThread.processFrame()
   at osu.Framework.Threading.GameThread.<createThread>g__runWork|66_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-03-02T13:56:42.4888733Z" />
    <EventRecordID>147346</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-3GH0UJ7</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at ManagedBass.Bass.FXSetPriority(Int32, Int32)
   at ManagedBass.Bass.FXSetPriority(Int32, Int32)
   at osu.Framework.Audio.Mixing.Bass.BassAudioMixer+&lt;&gt;c__DisplayClass29_0.&lt;onEffectsChanged&gt;g__applyEffects|2(Int32, Int32)
   at osu.Framework.Audio.Mixing.Bass.BassAudioMixer+&lt;&gt;c__DisplayClass29_0.&lt;onEffectsChanged&gt;b__0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean)
   at osu.Framework.Audio.AudioComponent.Update()
   at osu.Framework.Audio.AudioCollectionManager`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].UpdateChildren()
   at osu.Framework.Audio.AudioComponent.Update()
   at osu.Framework.Threading.AudioThread.onNewFrame()
   at osu.Framework.Threading.GameThread.processFrame()
   at osu.Framework.Threading.GameThread.&lt;createThread&gt;g__runWork|66_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
</Data>
  </EventData>
</Event>

**Second Log:**
Log Name:      Application
Source:        Application Error
Date:          3/2/2024 9:56:43 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-3GH0UJ7
Description:
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x65a80000
Faulting module name: coreclr.dll, version: 8.0.224.6711, time stamp: 0x65a895d5
Exception code: 0xc0000005
Fault offset: 0x00000000001d1f48
Faulting process id: 0x3ac0
Faulting application start time: 0x01da6ca7577a726a
Faulting application path: C:\Users\Roy\AppData\Local\osulazer\app-2024.302.0\osu!.exe
Faulting module path: C:\Users\Roy\AppData\Local\osulazer\app-2024.302.0\coreclr.dll
Report Id: 56e58167-ead6-43fa-b634-65884949184d
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-03-02T13:56:43.3179216Z" />
    <EventRecordID>147347</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-3GH0UJ7</Computer>
    <Security />
  </System>
  <EventData>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>65a80000</Data>
    <Data>coreclr.dll</Data>
    <Data>8.0.224.6711</Data>
    <Data>65a895d5</Data>
    <Data>c0000005</Data>
    <Data>00000000001d1f48</Data>
    <Data>3ac0</Data>
    <Data>01da6ca7577a726a</Data>
    <Data>C:\Users\Roy\AppData\Local\osulazer\app-2024.302.0\osu!.exe</Data>
    <Data>C:\Users\Roy\AppData\Local\osulazer\app-2024.302.0\coreclr.dll</Data>
    <Data>56e58167-ead6-43fa-b634-65884949184d</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Last log (doubt this is helpful but just incase, its windows information):**
Log Name:      Application
Source:        Windows Error Reporting
Date:          3/2/2024 9:56:45 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-3GH0UJ7
Description:
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: osu!.exe
P2: 0.0.0.0
P3: 65a80000
P4: coreclr.dll
P5: 8.0.224.6711
P6: 65a895d5
P7: c0000005
P8: 00000000001d1f48
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2621.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A29.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A68.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A66.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A96.tmp.txt
\\?\C:\Users\Roy\AppData\Local\Temp\WER2B16.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_osu!.exe_6413c270bb96968d3b4ceed36c14e6bac8e719_afb755cf_cab_7917cd44-7206-4074-a582-7f3433d1e0f2

Analysis symbol: 
Rechecking for solution: 0
Report Id: 56e58167-ead6-43fa-b634-65884949184d
Report Status: 4
Hashed bucket: 
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-03-02T13:56:45.0577231Z" />
    <EventRecordID>147348</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-3GH0UJ7</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>65a80000</Data>
    <Data>coreclr.dll</Data>
    <Data>8.0.224.6711</Data>
    <Data>65a895d5</Data>
    <Data>c0000005</Data>
    <Data>00000000001d1f48</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2621.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A29.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A68.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A66.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A96.tmp.txt
\\?\C:\Users\Roy\AppData\Local\Temp\WER2B16.tmp.appcompat.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_osu!.exe_6413c270bb96968d3b4ceed36c14e6bac8e719_afb755cf_cab_7917cd44-7206-4074-a582-7f3433d1e0f2</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>56e58167-ead6-43fa-b634-65884949184d</Data>
    <Data>4</Data>
    <Data>
    </Data>
    <Data>0</Data>
  </EventData>
</Event>

**Comment by peppy** [comment]
Thanks for the reports. People/process fucked up. The build has been pulled and we're pushing a new build out imminently.

**Comment by Nevrdid** [comment]
Hi, I use https://aur.archlinux.org/packages/osu-lazer-bin and version is well show as 3.12.1 but same notification message and scorese not beeing submited at all.

**Comment by smoogipoo** [comment]
@Nevrdid does it work after restarting the game?

**Comment by Nevrdid** [comment]
No, i tried multiple times.

**Comment by smoogipoo** [comment]
Please upload all logs from ~/.local/share/osu/logs

**Comment by Nevrdid** [comment]
[logs.zip](https://github.com/ppy/osu/files/14667388/logs.zip)
Here it is.

**Comment by smoogipoo** [comment]
It doesn't look like you're using a release build.

You may be using https://aur.archlinux.org/packages/osu-lazer, which is not supported. Please make sure you are using https://aur.archlinux.org/packages/osu-lazer-bin .

**Comment by Nevrdid** [comment]
Mmm, correct. But it was working previously. I guess it was previously using the appimage and chanced to build solution. x/
Thanks for the help.
