### ISSUE TITLE
EZ mode places objects outside of the screen

### ISSUE THREAD

**Issue by MaximTarenkov** [ppy/osu#27476]
### Type

Game behaviour

### Bug description

The problem is described in the title and shown in the video

### Screenshots or videos

https://youtu.be/42FulXI6l9c?si=SiXvAo71yheT746p

### Version

2024.302.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14472356/compressed-logs.zip)

**Comment by bdach** [comment]
Please link beatmap.

Judging from the video alone it looks like this will be https://github.com/ppy/osu/issues/14811, i.e. a stacking concern. It's likely that this is also an issue on stable and will require something like a classic mod setting to resolve.

**Comment by MaximTarenkov** [comment]
[Equilibrium - Waldschrein (Maakkeli).zip](https://github.com/ppy/osu/files/14473211/Equilibrium.-.Waldschrein.Maakkeli.zip)


> Please link beatmap.

**Comment by frenzibyte** [comment]
This is apparently an issue on stable as well:

https://github.com/ppy/osu/assets/22781491/d344897e-56ff-4d7e-91ab-fff4499009af

And it does look indeed relevant to stack leniency, as decreasing leniency completely (i.e. less stack) resolves the issue.

Tracking in https://github.com/ppy/osu/issues/14811
