### ISSUE TITLE
Mouse Stutter during Gameplay

### ISSUE THREAD

**Issue by Sewlell** [ppy/osu#27488]
### Type

Game behaviour

### Bug description

Ever since I updated the osu!lazer to the February 19 version ( February 21? ), I have constantly realize my mouse keep stuttering during gameplay and thx to it, I keep losing my FC.

I never had a mouse stutter issues before in **ANY** application unlike the #23448. Roblox, Chrome, Discord, everything is working just fine.

osu!stable also working without stopping the mouse from moving.

Changing renderer from DirectX to OpenGL won't worked.

I have throw my mouse ( Logitech B175 ) because tiring of keep playing like this ( actually also button insesitivity issue ). The point is I have change my mouse to Logitech M275. The issue is still there standing.

Drivers installed, tried different USB port, still the same.

I have closed all running application running in the background and still the same.

Borderless and Windowless of osu!lazer doesn't have the same issue somehow.

Did not have dynamic wallpaper going on as someone who had similar issue in Q&A having that.

One of thing I haven't do yet is reinstall osu!lazer, which well, because of lazy to backup 6GB of map file?

Here my laptop spec :
Windows 11 Home 22H2
Core i5-10210U with integrated graphic
Nvidia MX130 (2GB VRAM)
12GB RAM
512GB SSD
60Hz display

Two were provided, one with direct record with RTTS and other stuff actually opening in the background. another one with fullscreen record with RTTS showed.

### Screenshots or videos

https://github.com/ppy/osu/assets/93970226/ffb02d3c-3d5b-4431-922f-8f784402bfbb

https://github.com/ppy/osu/assets/93970226/320c0717-d4a9-4a2e-9546-30e553e6b637

### Version

Since February 19

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14480478/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu-framework/issues/6181 probably
