### ISSUE TITLE
osu!lazer passed scores do not account to beatmap success rate properly

### ISSUE THREAD

**Issue by JamieWright99** [ppy/osu#27485]
### Type

Game behaviour

### Bug description

I noticed when I played my beatmap that the success rate for it was getting lower and lower, I was confused since most plays were from myself. I found some quick uploaded maps with small play counts and found that playing them on lazer lowered that value regardless of if you passed or not.

In the video I played a map I found that had no plays at all, but I have seen the value lower on maps that already have plays.

### Screenshots or videos

https://github.com/ppy/osu/assets/102170503/8ecd0599-cf20-4bec-943b-4ede5b10a6f5

### Version

2024.302.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14475005/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Seems passing a beatmap in lazer does not increment the `beatmap.passcount` field returned by the API (tested on both a pending beatmap and a ranked beatmap, same issue). cc @peppy / @ppy/team-web
