### ISSUE TITLE
Replay score mishandling

### ISSUE THREAD

**Issue by Zockerboy468** [ppy/osu#27503]
### Type

Game behaviour

### Bug description

If a score is getting replayed, the score gets better apparently. This was for me the case and it's a bit sad because it could've been my first 300pp play :( (for the video,no its not because i fast forwarded, i also tried it without)

### Screenshots or videos

https://github.com/ppy/osu/assets/85823953/6f80129d-d350-4d41-ae97-49b92bbeac65
https://osu.ppy.sh/scores/2389652615

### Version

2024.132.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14497448/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues?q=is%3Aissue+is%3Aopen+replay+accuracy
