### ISSUE TITLE
clicking the orange cursor when unpausing counts as input

### ISSUE THREAD

**Issue by sawawas** [ppy/osu#27505]
### Type

Game behaviour

### Bug description

the orange cursor you click when trying to unpause counts as a click ingame, and if it's ontop of a circle that just appeared, you will miss for clicking too early

i dunno
im on apple silicon if that helps

### Version

2024.302.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14503461/compressed-logs.zip)

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/9658
