### ISSUE TITLE
Beatmap testing mode doesn't end automatically when audio ends

### ISSUE THREAD

**Issue by Kyorie** [ppy/osu#27512]
### Type

Game behaviour

### Bug description

1. Open any beatmap in the editor
2. Run into testing mode from any timestamp
3. Wait till the audio ends. You'll still remain in the gameplay testing mode despite the end of an audio.

Expected behaviour: Automatic redirect back to the editor (to the point before you started testing) when map/audio ends.

### Screenshots or videos

https://github.com/ppy/osu/assets/47324490/fd3a6df4-c584-443f-9954-122767fed541

### Version

2024.302.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14513122/compressed-logs.zip)

**Comment by bdach** [comment]
#17395
