### ISSUE TITLE
osu!mania beatmaps play with incorrect key count

### ISSUE THREAD

**Issue by AlFasGD** [ppy/osu#2751]
In that update somehow in osu!mania all beatmaps are read with 7 keys regardless of the actual key count, and only the hold notes are read, ignoring all the other notes. The break overlay also only appears for half a second and then disappears only in the start, even if it's actually skippable.

**Comment by peppy** [comment]
Please open a separate issue for the space key.

**Comment by AlFasGD** [comment]
https://youtu.be/f344OfgEHbY
