### ISSUE TITLE
Skin Editor deselects Automation mods

### ISSUE THREAD

**Issue by Urantij** [ppy/osu#27519]
### Type

Game behaviour

### Bug description

If you have selected Automation mods (autoplay, autopilot, spunout), entering "Gameplay" tab of skin editor will deselect these mods.
It doesnt deselect other mods like Double Time or Classic.
I didnt test it for all the mods, just for Difficulty increase, Automation and "Classic" from Conversion.

### Version

2024.302.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14523049/compressed-logs.zip)

**Comment by bdach** [comment]
This is intentional because the skin editor forces autoplay when launched through the scene library such that you can edit skin while representative gameplay is taking place in the background.
