### ISSUE TITLE
Minor stutters at regular intervals

### ISSUE THREAD

**Issue by theyareonit** [ppy/osu#27525]
### Type

Performance

### Bug description

The game has frametime spikes roughly every 4 seconds, at consistent intervals. Tested with both DX11 and OpenGL, as well as with both 480fps and 960fps. These spikes are not present whatsoever in osu!stable, or any other games. Using an RTX 3060 and an i5 12500 on Windows Server 2022, with nothing besides PresentMon running in the background. Threaded optimization disabled.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/82268986/ea1eee95-a2c1-4f89-b017-c72cdf2059a4)

### Version

2024.302.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14532412/compressed-logs.zip)

**Comment by peppy** [comment]
Please wait for the next release where we have tuned the GC to hopefully reduce these stutters.

Also please search issues before opening a new one, there's at least 10.

**Comment by theyareonit** [comment]
I did try searching for related issues, but none of them had stutters at the same interval as the ones I am experiencing. For example, this user is getting stutters every 20 seconds, and doesn't seem to be experiencing the kind I'm getting at all: https://github.com/ppy/osu/issues/27306. So, this made me unsure if the stutters I was getting were truly GC related or not (I don't have much knowledge of how the garbage collector works, or if these inconsistencies across systems are normal, apologies).
