### ISSUE TITLE
Can't scroll through drop-down lists in osu!direct

### ISSUE THREAD

**Issue by BlockHead007** [ppy/osu#27532]
### Type

Cosmetic

### Bug description

Not every category is visible on some non-english languages (for example russian), so there is a drop-down list to show them all. The thing is that you can't scroll that list to see the rest of the options. I believe that is because they are hidden behind beatmap results section and it is hard to select them. Also while on english lang there are some missing options at the end of both lists.

### Screenshots or videos

https://www.youtube.com/watch?v=tRbU-jK8Dik

### Version

2024.302.1

### Logs

I don't think they are needed, but here they are:
[compressed-logs.zip](https://github.com/ppy/osu/files/14535878/compressed-logs.zip)

**Comment by bdach** [comment]
There should be no dropdown to begin with, this should just wrap.
