### ISSUE TITLE
First language switch removes bold design on Personal (Mod) Presets column title

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#27549]
### Type

Cosmetic

### Bug description

Images should be self-explanatory: the first time you change language, after loading the mod select overlay, the title of the mod presets column (which is the only one translated for now) loses the _**bold** design_.
Changing language again fixes the issue.
Doesn't seem language-specific.

### Screenshots or videos

**(Images show two language scenarios, they are not run consecutively.)**

- Changing language, for the first time, after loading the overlay (stays like this until you change language):
  English → Italian
  ![image](https://github.com/ppy/osu/assets/43073074/1c4fb6bb-3c10-4e4e-aa49-28080adacc24)
  Italian → English
  ![image](https://github.com/ppy/osu/assets/43073074/22588270-8610-44a7-ad91-ee68789dd599)

- After changing language again (even if the overlay is closed):
  Italian → English
  ![image](https://github.com/ppy/osu/assets/43073074/a080dca4-76cb-47cb-aa63-17b373108bd7)
  English → Italian
  ![image](https://github.com/ppy/osu/assets/43073074/2e8ef7c1-1745-45e7-b225-36437d560601)

### Version

2024.302.1

### Logs

n/a

**Comment by Gabixel** [comment]
Actually, it looks like you can also change the language on the main menu (without first loading the mod overlay), and the issue appears anyway

**Comment by peppy** [comment]
I believe this is going to be a framework side issue (`creationParameters` not being reapplied when localised text changes).
