### ISSUE TITLE
Support for Vulkan

### ISSUE THREAD

**Issue by lunafreya** [ppy/osu#2756]
Basically, Vulkan serves as a spiritual successor to OpenGL (the API the game is currently using) as well as AMD's Mantle API. What can it do (unlike OpenGL) is that it allows low-level hardware overhead, not to mention some performance improvement over OpenGL.

Do you think this will be used in the game, pending overall compatibility concerns?

[en.wikipedia.org/wiki/Vulkan_(API)](url)

**Comment by peppy** [comment]
While no one is against adding vulkan support, there is currently no ETA or reason to do so.

You're welcome to look into it, although as we are currently using OpenTK you may wish to look into their plans for implementation of it as a prerequisite to discussing here.

**Comment by peppy** [comment]
Also this is not an osu!-side issue. It deals 100% with osu-framework.
