### ISSUE TITLE
Input thread freeze/stutters

### ISSUE THREAD

**Issue by Givikap120** [ppy/osu#27576]
### Type

Performance

### Bug description

During the gameplay there's a chance that cursor will freeze in one place (the rest of the game is still rendered)
The play with big amount of occurrences of this bug ended in 22:17 (marked as 20:17 in logs because UTC+2) 
Video contains part of this play
It's not a tablet lag because all of the actions (key presses) are being registered as soon as thread is unfreezing

### Screenshots or videos

https://github.com/ppy/osu/assets/89256026/270392af-f271-478d-8c1c-abbceb7f37bc

### Version

2024.312.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/14564642/logs.zip)

**Comment by Gabixel** [comment]
Could this be related to https://github.com/ppy/osu/issues/27227 (so a known issue)?

**Comment by Givikap120** [comment]
> Could this be related to #27227 (so a known issue)?

yes, sorry haven't found this issue cuz i was filtering by performance

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/27227
