### ISSUE TITLE
Remnants of the old osu! logo are still present in lazer

### ISSUE THREAD

**Issue by Auruhausu** [ppy/osu#27572]
### Type

Cosmetic

### Bug description

Surprised that no one had found this since the implementation of the redesigned logo.

### Screenshots or videos

![ouch](https://github.com/ppy/osu/assets/152286401/8bc4016c-6ba8-4b41-820a-760e486d467d)

### Version

2024.312.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14563589/compressed-logs.zip)

**Comment by bdach** [comment]
[People did, actually.](https://discord.com/channels/188630481301012481/188630652340404224/1201919022669778985) It's intentional for now.
