### ISSUE TITLE
Highest rank is wrong

### ISSUE THREAD

**Issue by Wildthing0** [ppy/osu#27575]
### Type

Cosmetic

### Bug description

Went to check peak rank and it was off by 200k
Android btw

### Screenshots or videos

![Screenshot_20240312_073152](https://github.com/ppy/osu/assets/90672169/321ace67-2a50-4332-a165-bc42f1d2cf49)

### Version

2024.312.0

### Logs

Could not access the data folder

**Comment by Gabixel** [comment]
I think this is a duplicate of https://github.com/ppy/osu-web/issues/10937

**Comment by Joehuu** [comment]
Yes, but leaving this open for visibility.

**Comment by snalgae** [comment]
i also have this problem

**Comment by frenzibyte** [comment]
> i also have this problem

Thank you but the underlying issue is known, there's no need for +1 comments like yours.

**Comment by Wildthing0** [comment]
> I think this is a duplicate of [ppy/osu-web#10937](https://github.com/ppy/osu-web/issues/10937)

yeah but thats for osu web and this if for osu lazer

**Comment by frenzibyte** [comment]
osu! sources the highest rank from web API, so no, they lead to the same thing, but this is still open for a different reason (visibility).

**Comment by peppy** [comment]
https://github.com/ppy/osu-web/issues/10937
