### ISSUE TITLE
Hitsound de-sync with bluetooth headphones

### ISSUE THREAD

**Issue by Shiner001** [ppy/osu#27573]
### Type

Game behaviour

### Bug description

Okay so I know bluetooth has high latency and I don't play the game that way, but sometimes I watch replays using it. Never been an issue before, but with the newest release, using bluetooth desyncs the hitsounds with the music. I've recorded a sample wired and with bluetooth.

### Screenshots or videos

-wired video https://youtu.be/TzoyswS-dFc

-bluetooth video https://youtu.be/IRMsbQkmn9g

### Version

2024.312.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14563875/compressed-logs.zip)

**Comment by peppy** [comment]
Please adjust universal offset.

**Comment by No-Biggie805** [comment]
idk what is too though. I have this issue too.
I use Linux, though. I found out that built-in speakers is desync free whereas BT it desyncs. Even with gaming mode which I have for some earbuds.
Now what's weird is that, and maybe I'm crazy it wasn't desyncing b4, or didn't feel that way.
The stable version seems to work (with wine) well with BT devices. 
Edit: will see on liveCD to see what happens, apologies for reviving a "not planned" thread.
