### ISSUE TITLE
Login fails with "Invalid url or incorrect request method."

### ISSUE THREAD

**Issue by Ben-Brady** [ppy/osu#27579]
### Type

Game behaviour

### Bug description

Using the built-in Osu Lazer login menu, I get an error message when trying to login with correct credentials. It displays the error message "Invalid url or incorrect request method.". This may be due to ratelimitting as I attempted to sign-in multiple times, however I'm unsure wether or not the original error message was the same.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/64110708/01ee6754-eab2-4b79-9c35-5ab2d1e35af9)

### Version

2024.114.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14565406/compressed-logs.zip)

**Comment by Joehuu** [comment]
You are running a really old version, please update.
