### ISSUE TITLE
Importing beatmaps sometimes does not store OnlineBeatmapID

### ISSUE THREAD

**Issue by ringosham** [ppy/osu#2758]
I noticed that some ranked maps have no leaderboards. I cannot get to the details page by right-clicking the beatmap.
I took a look at the database and found that the OnlineBeatmapID is not stored.

![capture](https://user-images.githubusercontent.com/7325740/41132796-ed9d6e4c-6aba-11e8-9db9-fadc86530cdf.PNG)

Both values in beatmapsetinfo and beatmapinfo are null on that map (There are cases where one has the ID, but the other doesn't). Keep in mind that beatmap is ranked as well.
I've checked the logs as well. I only see success messages. Nothing going wrong.

Since this bug is inconsistent, try importing around 50-100 maps all at once.

**Comment by peppy** [comment]
Older beatmaps do not have these values stored in .osu files. We need to add a lookup step to the import process.

**Comment by jai-sharma** [comment]
The beatmaps stored in the Songs directory of stable, each seem contain the BeatmapSetID in the directory name. Maybe the importer could use that value.
![image](https://user-images.githubusercontent.com/8362491/41133971-f2857088-6ac1-11e8-83a6-0c09b4b28a00.png)

**Comment by peppy** [comment]
Sometimes, but that is not always the case. There needs to be an online confirmation/fallback step which queries the API.
