### ISSUE TITLE
Graphical glitches on Osu 

### ISSUE THREAD

**Issue by FartDezz** [ppy/osu#27598]
### Type

Game behaviour

### Bug description

Glitching UI elements and frequent crashing on Osu Android client on first start-up.

### Screenshots or videos

https://github.com/ppy/osu/assets/131302964/bd946ef6-bb3a-4d01-a9a7-d8b2b8644d23

### Version

2024.312.1

### Logs

Not able to find "sh.ppy.osulazer" folder. But here's some useful information that could help track down this bug; I am using a Pixel 7a on Android 14 (Crdroid).

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25189
