### ISSUE TITLE
Lazer osu!catch slider inconsistencies

### ISSUE THREAD

**Issue by NinakoMaid** [ppy/osu#27593]
On a map XNOR XNOR XNOR [Earth difficulty]
https://osu.ppy.sh/beatmapsets/1236927#osu/2619200
some sliders either gone or highly misplased.

Stable:
![StableXnor](https://github.com/ppy/osu-web/assets/49080544/34a215e0-24d2-4509-ad38-d40d109cbf15)
Lazer:
![LazerXnor](https://github.com/ppy/osu-web/assets/49080544/66f070d8-84fa-4462-b021-b44cb370be50)

**Comment by bdach** [comment]
Map is aspire. We don't guarantee that these are going to match stable because these maps abuse undefined behaviour that is difficult or impossible to reimplement in a sane way.
