### ISSUE TITLE
Loved maps does not show pp disclaimer screen things

### ISSUE THREAD

**Issue by SussyGuy35** [ppy/osu#27603]
### Type

Cosmetic

### Bug description

on stable, when open a Loved map, a disclaimer screen will be show to tell player that no pp will be awarded.
on lazer that thing does not exist

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/107260269/0ef9b661-2bbf-45cb-82b1-7fefb2fd5af4)

### Version

2024.312.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14590847/compressed-logs.zip)

**Comment by bdach** [comment]
#6480
