### ISSUE TITLE
Frame behind rendering on macOS

### ISSUE THREAD

**Issue by DBeitniz** [ppy/osu#27621]
### Type

Performance

### Bug description

So I play on an M2 MacBook Air, have no background apps open or anything. I recently started playing osu!lazer and have always seen this one issue in all gamemodes I play. In osu!std the approach circle is a frame behind if it's near a counter (accuracy, score, health etc.), as example at the bottom in the middle there's the accuracy thing, if there's a circle near that counter the approach circle at the bottom is a frame behind, but the upper part of the approach circle is at it usually should, the same for the upper part, just that the upper part of the approach circle is a frame behind and the under part is the way it should. This issue happens with or without a skin and with and without a storyboard/video. About osu!taiko if there's a storyboard/video the circles may sometimes go a frame back for 2-4 frames and then back, which is sometimes unplayable. In osu!mania same thing just the notes are going up for 2-4 frames and then back to their positions if there's a storyboard/video.

Also one thing to consider with skins and storyboards and videos, my max Cpu usage was 60-70% and GPU 60-80%, so it's not using all the power of the laptop.

To consider, I haven't changed ANY graphics setting and have the latest version of osu. Also this issue has been around for me for around a month already. English isn't my main language so it may be confusing or bad at times, sowwy :(

### Screenshots or videos

In videos/screenshots the frames are normal, I don't know what's happening, but visually on the screen they are off and its VERY bad I tried to record my Screen with my Phone, the file size was to big (28MB) so I uploaded it to YouTube https://youtube.com/shorts/xVLarbFefGo?feature=share it made it a short for some reason >:

### Version

2024.312.1-lazer (The newest version right now)

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14620452/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Change your frame limiter mode in settings to "VSync".
