### ISSUE TITLE
Better handling of storyboard object lifetime

### ISSUE THREAD

**Issue by nolife99** [ppy/osu#27627]
### Type

Crash to desktop

### Bug description

Take a long-lived sprite that fills the screen with a flash (this is used in the following screenshots)
```Sprite,Background,TopRight,"sb\p.png",747,0
 V,0,54035,,854,480
 P,0,54035,,A
 F,0,54035,55447,0.8,0
 F,0,76623,78035,1,0
 F,0,99211,100623,1,0
 F,0,110505,111917,1,0
 F,0,121800,123211,0.9,0
 F,0,135917,137329,0.8,0
 F,0,147211,148623,0.8,0
 F,0,158505,159917,1,0
 F,0,169800,171211,0.8,0
 F,0,181094,182505,1,0
 F,0,192388,193800,0.8,0
 F,0,203682,205094,0.7,0
 F,0,214976,216388,1,0
 F,0,226270,227682,0.8,0
 F,0,238976,240388,0.8,0
 F,0,261564,262976,0.8,0
 F,0,284152,285564,1,0
``` 

This flash does not show at all in lazer, but work fine in stable

Here is the map if you need to test further
https://cdn.discordapp.com/attachments/703242491163312178/1218049120032395335/Kuba_Oms_-_My_Love_XenjeS_remix.osz?ex=66063fa4&is=65f3caa4&hm=677609d6d5c66e09cced7f993287f6abb7c55a0cdf0106a1536bcb92c2cb87df&

### Screenshots or videos

Screenshot of in lazer
![image](https://github.com/ppy/osu/assets/89430659/9f133b2e-49fc-49f6-816d-7efdc2ff39f2)

Screenshot of in stable (at the same time)
![image](https://github.com/ppy/osu/assets/89430659/5a83e781-8efa-428d-852e-7265bd78f374)

### Version

2024.312.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14622469/compressed-logs.zip)

**Comment by EVAST9919** [comment]
Can confirm this regresed with [my pr](https://github.com/ppy/osu/pull/27454) since I mislooked the fact that sprites can be become visible again even with `EndValue = 0` command (we need to account for `StartValue != 0` as well). Will pr a fix.
