### ISSUE TITLE
Storyboard commands are ignored for videos

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu#27634]
### Type

Game behaviour

### Bug description

surprising as it sounds, storyboard commands work on video events and there are ranked maps that take advantage of this

example 1: https://osu.ppy.sh/beatmapsets/1049855

```
[Events]
0,0,"OptionsBG.jpg",0,0
Video,0,"Options.avi"
 S,0,0,,1
```

example 2: https://osu.ppy.sh/beatmapsets/1629388#osu/3326292

```
[Events]
0,0,"silence.jpg",0,0
Video,0,"silence.avi"
 S,0,0,,1
```

### Screenshots or videos

example 1:

stable
![screenshot763](https://github.com/ppy/osu/assets/36758269/1f8c10dc-4365-4bb0-95f6-ee93b214369a)

lazer
![osu_2024-03-16_15-41-08](https://github.com/ppy/osu/assets/36758269/167e4a27-4dc6-4c83-bff4-152b2976d2a5)

example 2:

stable
![screenshot765](https://github.com/ppy/osu/assets/36758269/a86979f4-601d-4087-8b71-78f6a40150aa)

lazer
![osu_2024-03-16_15-48-13](https://github.com/ppy/osu/assets/36758269/eafeed68-70ec-4638-a26e-c0e2b719eeac)

### Version

2024.312.1-lozer

### Logs

n/a

**Comment by Coppertine** [comment]
To be more technical, Videos are storyboard sprites and can be interacted with as regular sprites. However with special properties. You can't have 2 different video sprites at the same time, but can have 2 of the same video sprite at the same time and move / scale / rotate them around.
