### ISSUE TITLE
A new type of in gameplay stutters that is visible within logs

### ISSUE THREAD

**Issue by Clasher078** [ppy/osu#27642]
### Type

Performance

### Bug description

Normally when there are small stutters in the Gameplay those stutters are not visible within the logs but this seems like a new type of stutter, being preceded by a playback discrepancy and lasting a lot longer. This occurs simultaneously with a lot of frames arriving at spectatorclient outside of the Gameplays scope. 

### Screenshots or videos

![logs](https://github.com/ppy/osu/assets/70033359/131896c0-a188-4c18-8893-66930da3e033)
.
.
.
.
.
![logs2](https://github.com/ppy/osu/assets/70033359/3c9d9856-9fc1-47a0-abbb-fed5a81a0de9)

### Version

2024.312.1-lazer

### Logs

These are the relevant logs, the section around where the error occurs has been screenshot above.
 
[compressed-logs.zip](https://github.com/ppy/osu/files/14627083/compressed-logs.zip)

**Comment by peppy** [comment]
Please share a video of this happening with fframe graphs visible (ctrl+f11 twice).

**Comment by Clasher078** [comment]
This is apparently fixed by reloading the beatmap as i am unable to reproduce this after deleting and reinstalling the map

**Comment by Clasher078** [comment]
closing this as this appears to be unreproducable after reloading the map through deleting and reinstalling it.
