### ISSUE TITLE
Only master volume can be changed while something else (e.g. notifications) has focus

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2765]
While using the scroll wheel Master volume will change. When you hover over Effects or Music then that volume can be changed. But only when something else isn't opened, like notifications or music player.

**Comment by Aergwyn** [comment]
#2744 may adress that actually.

**Comment by LittleEndu** [comment]
Checked it out. It doesn't. And the hover animation introduced doesn't work either.

**Comment by peppy** [comment]
I believe this can be fixed by making the volume controls overlay higher than all other overlays (except for settings, maybe).
