### ISSUE TITLE
Map with subfolders have incompatibility issues.

### ISSUE THREAD

**Issue by Ladwick** [ppy/osu#27653]
### Type

Game behaviour

### Bug description

I'm talking about [this](https://osu.ppy.sh/beatmapsets/73#osu/167) map. The thing is that the beatmap folder has a subfolder that contains the .mp3 file and lazer apparently can't understand this, so the map is still playable but it won't find the .mp3.

In stable you can take the .mp3 out of the subfolder into the main folder, then update the map and the ranked status will stay along with the song, however, I tried to export the map already in this modified state to lazer but it won't detect it as a ranked map and will ask you to update (sometimes, other times it won't even ask for update and will stay without ranked status). Once you update the map the ranked status will be back but unlike stable, the song will be gone, I presume stable keeps the .mp3 in the main folder after updating while lazer puts it back in the subfolder for the beatmap to be in a ranked status. I dunno if this issue occurs with any other maps but this is the only one I came across with this specific problem, so probably is easier to just modify the osz file in the server to avoid this?

### Screenshots or videos

![osu_2024-03-17_12-34-11](https://github.com/ppy/osu/assets/37979533/523d23bf-3437-4f23-8787-d8af6fb72367)
![image](https://github.com/ppy/osu/assets/37979533/fcbb592f-ab9f-4043-b660-2cb315a83072)

### Version

2024.312.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14628139/compressed-logs.zip)

**Comment by peppy** [comment]
Fixed the osz
