### ISSUE TITLE
Crash after opening settings

### ISSUE THREAD

**Issue by ItzIcoza** [ppy/osu#27665]
### Type

Crash to desktop

### Bug description

Not really sure what to put in here except that opening the settings make the game crash...
Anyways, here's some info about my system + operating system in case you need it.

OS: Windows 11 Home Build 23612
System Type: x64
Processor/CPU: 12th gen Core i5-12400F, 2500Mhz, 6 cores
RAM: 16 GB

### Screenshots or videos

https://github.com/ppy/osu/assets/105557160/2011d76a-5ce7-481d-acbc-744bfe2b9aed

### Version

Latest (Can't see version number as opening the settings crash the game)

### Logs

Again, I CANNOT open the settings inside the game as opening them make the game crash.
Sorry I couldn't attach any logs.

**Comment by bdach** [comment]
It's 99% a custom ruleset. Probably hitokori.
