### ISSUE TITLE
Double Inputs Cause a Crash to Desktop

### ISSUE THREAD

**Issue by witkodn** [ppy/osu#27660]
### Type

Crash to desktop

### Bug description

I am playing on a custom ruleset, osu!Rush. There is a type of hitobject in the game, that requires the player to input two keys at once. Recently, when inputted it causes a crash to desktop. Though, I believe they need to be exactly simultaneous, because it will not always occur immediately when trying to recreate the issue. As so, this also only occurs when trying to hit an object, and does not occur when there are no objects present. Another interesting point to note is that this happens when there is a slider object and a hitobject at the same time. It does not occur when there are two hitobjects and neither of them are slider types.

### Screenshots or videos

https://github.com/ppy/osu/assets/158174283/1c00ae45-90bb-4ca5-bd37-c023c8dc3c3d

### Version

2024.312.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14631109/compressed-logs.zip)

**Comment by LumpBloom7** [comment]
This issue is specific to the rush ruleset, and not osu. This should be fixed by the ruleset specifically.
