### ISSUE TITLE
does not work lazer multi chat commands

### ISSUE THREAD

**Issue by SokTV** [ppy/osu#27671]
### Type

Game behaviour

### Bug description

Multi room chat commands like !mp does not work!

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/34370220/d45e52ae-72d4-4da4-a5ad-a9571d910e85)
![image](https://github.com/ppy/osu/assets/34370220/f8ca445e-2a11-47e7-8a1b-9c40d9decef7)

### Version

2024.312.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14653548/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/18897
