### ISSUE TITLE
Cursor gets updated while beatmap is paused

### ISSUE THREAD

**Issue by xRasea** [ppy/osu#2767]
This made me get >500 spins per minute, I find it quite amusing to be honest.

Video of the issue: (Sorry for the jumpcuts, I didn't want to show more than what was necessary, from 5 mins of raw footage to 1:30 I think it's an improvement)
https://www.youtube.com/watch?v=PM2HmlrOeho

edit2: i'm dumb and don't know how to post in github, period.

Important edit: This happened almost randomly when pressing one or both triggers, but I highly believe it has something to do with Mouse buttons being disabled and me tapping on the tablet (mouse1) when in the pause menu.

**Comment by peppy** [comment]
Is this on the latest build (608)?

**Comment by xRasea** [comment]
yup, just saw your comment on #lazer and updated

**Comment by peppy** [comment]
Has since been fixed.
