### ISSUE TITLE
Combo colour changes are not automatically updated to the verify/aimod tab

### ISSUE THREAD

**Issue by 64ArthurAraujo** [ppy/osu#27670]
### Type

Game behaviour

### Bug description

While working in adding the luminosity check to the editor, i found this issue, if you update the colors and go to the verify tab it will not update to the latest changes you've made (like it works with the AR, CS) you need to reload the editor to actually update the colors for the verify tab. This will probably need to be addressed before adding the luminosity check to the editor.

[luminosity check branch](https://github.com/64ArthurAraujo/osu/tree/verify-colours-luminosity)

### Screenshots or videos

https://github.com/ppy/osu/assets/90941580/00b34889-3c18-485c-ad98-8f24484a472d

### Version

development

### Logs

None (probably not a bug)

**Comment by bdach** [comment]
Somewhat tangential but I'm not sure how valid the check is now that we have combo colour normalisation in the game.
