### ISSUE TITLE
Share menu images between lazer and stable

### ISSUE THREAD

**Issue by peppy** [ppy/osu#27680]
I'm looking to standardise this across both clients, while also adding rotation to the mix to avoid this being done manually by some script (leave it up to the client to rotate the banners).

Proposed model:

```csharp
   public class APIMenuContent
    {
        /// <summary>
        /// Images which should be displayed in rotation.
        /// </summary>
        [JsonProperty(@"images")]
        public APIMenuImage[] Images { get; set; } = Array.Empty<APIMenuImage>();
    }

    public class APIMenuImage
    {
        /// <summary>
        /// A URL pointing to the image which should be displayed. Generally should be an @2x image filename.
        /// </summary>
        [JsonProperty(@"image")]
        public string Image { get; set; } = string.Empty;

        /// <summary>
        /// A URL that should be opened on clicking the image.
        /// </summary>
        [JsonProperty(@"url")]
        public string Url { get; set; } = string.Empty;

        /// <summary>
        /// The time at which this item should begin displaying. If <c>null</c>, will display immediately.
        /// </summary>
        [JsonProperty(@"begins")]
        public DateTimeOffset? Begins { get; set; }

        /// <summary>
        /// The time at which this item should stop displaying. If <c>null</c>, will display indefinitely.
        /// </summary>
        [JsonProperty(@"expires")]
        public DateTimeOffset? Expires { get; set; }
    }
```

example json

```json
{
  "images": [
    {
      "image": "https://assets.ppy.sh/main-menu/image1@2x.jpg",
      "url": "https://osu.ppy.sh/",
      "begins": "2024-03-20T10:00:00+00:00",
      "expires": "2024-03-20T11:00:00+00:00"
    },
    {
      "image": "https://assets.ppy.sh/main-menu/image2@2x.jpg",
      "url": "https://osu.ppy.sh/",
      "begins": null,
      "expires": "2024-03-20T13:00:00+00:00"
    },
    {
      "image": "https://assets.ppy.sh/main-menu/image3@2x.jpg",
      "url": "https://osu.ppy.sh/",
      "begins": "2024-03-20T13:00:00+00:00",
      "expires": null
    }
  ]
}
```

Interested in feedback before going ahead with updating the lazer implementation, refactoring stable to read from this, and adding ASS commands to manage the file.

cc @bdach for a quick review of the above.

**Comment by bdach** [comment]
Model looks fine in itself I guess.

I am slightly curious what is gonna happen when there is more than one banner image "active" at the time as per `begins` / `expires` but I'm not sure that's a model question moreso than a management / implementation model. Although the desired behaviour may influence the model so...

**Comment by peppy** [comment]
The basic goal of `begins`/`expires` is to allow scheduling for when the images should show (or not).

For the case of more than one image, they may be displayed at the same time, at which point they will automatically rotate between the images (with equal time slots). Whether we want to try and achieve syncronised rotation across clients, I'm not yet sure. I was thinking of trying for this, based on the current minute in the hour, but we'll see.

**Comment by bdach** [comment]
Sounds fine.

**Comment by cl8n** [comment]
can this be the same data as in this website design? https://github.com/ppy/osu-web/issues/9614

for reference this is my WIP table for it. seems very similar so far <https://github.com/ppy/osu-web/pull/9617/files#diff-c207ed2efa496cc1e5377ce72c1643fac21fb2cf0c47c20773eee43cf79fba4e>

**Comment by bdach** [comment]
Why should there be system / structure overlap between these to begin with? For stuff like a world cup banner sharing would make sense yes, but in-client banners also sometimes advertise newsposts or polls, which would have presumably hit the website front page on their own?

**Comment by cl8n** [comment]
hmm ya good point, nvm for now then :100:
