### ISSUE TITLE
chat still receive input when pressing enter key while playing multiplayer

### ISSUE THREAD

**Issue by PGRjoystick** [ppy/osu#27693]
### Type

Other

### Bug description

my keybind for mania is ' which is near the enter key on a laptop. when i accidently press the enter key while playing mania. all my key input will also registered in a chatbox and sometimes thats make the game stutter. is there any way to disable chat input or enter key when playing multiplayer ?

### Screenshots or videos

https://github.com/ppy/osu/assets/30430815/b382fce5-9709-4e2e-9ed9-f7dbc792a597

### Version

2024.312.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14720300/compressed-logs.zip)

**Comment by bdach** [comment]
You can rebind or fully unbind that key.

![Uploading osu_2024-03-22_10-17-53.jpg…]()

**Comment by PGRjoystick** [comment]
oops sorry. i didn't find that settings until i dig more into configure input. 

thank you
