### ISSUE TITLE
Timing Distribution +RX is slightly off

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#27695]
### Type

Game behaviour

### Bug description

Relax mod clicks exactly on hitobject timing points, but it's slightly off in the results screen, and also in the HitErrorMeter.

I thougt it can be because of Audio Offset, but I tested with 0 offset on both global's and beatmap's and the same thing happened.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/89677246/32cceb0d-77be-48b7-aa99-8ea9907ecc73)
![image](https://github.com/ppy/osu/assets/89677246/f428e728-6d49-46c1-81b4-ab648e0f1381)
![image](https://github.com/ppy/osu/assets/89677246/02af48e1-84e1-4326-95ad-37d2e3c0bc8b)

### Version

2024.312.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14722752/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Because it doesn't hit objects at their exact start time:

https://github.com/ppy/osu/blob/77660e57ea3d675b92d4c6c0c5eb8e68562d9135/osu.Game.Rulesets.Osu/Mods/OsuModRelax.cs#L28-L31

**Comment by aL1NaZ4R** [comment]
> Because it doesn't hit objects at their exact start time:
> 
> https://github.com/ppy/osu/blob/77660e57ea3d675b92d4c6c0c5eb8e68562d9135/osu.Game.Rulesets.Osu/Mods/OsuModRelax.cs#L28-L31
Can I ask why?

**Comment by smoogipoo** [comment]
I'm not entirely sure why it's that specific value, but it's because players generally aim in advance and waiting until the exact start time would feel slow - they may have already moved off the circle towards the next one.
