### ISSUE TITLE
In-game leaderboard show when no leaderboard selected before gameplay.

### ISSUE THREAD

**Issue by Silica163** [ppy/osu#27694]
### Type

Game behaviour

### Bug description

This bug was found in osu lazer on linux.
# How to reproduce this bug
1. go to osu! song select menu and select a song
2. click on Local or Global label below song name and difficulty info
3. click on Details then click on selected level of that song

when gameplay interface is on screen, it show in-game leaderboard below health bar with the last leaderboard selected before click at Details

in-game leaderboard can be removed by select another level or another song.

### Screenshots or videos

# select "Local" before "Details"
https://github.com/ppy/osu/assets/96188282/7ee3f4a2-359d-4d1e-ab24-48ac1892bdf1

# select "Global" before "Details"
https://github.com/ppy/osu/assets/96188282/1def1ab1-ae2d-455c-b5f2-770f2330fe3d

### Version

2014.312.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14720325/compressed-logs.zip)

**Comment by bdach** [comment]
That's not just how any of this is supposed to work. Selecting details is not meant to turn the leaderboard off.
