### ISSUE TITLE
osu!taiko mascot looks smaller compared to stable

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#27701]
### Type

Crash to desktop

### Bug description

-

### Screenshots or videos

Stable:

![CleanShot 2024-03-23 at 05 52 39](https://github.com/ppy/osu/assets/22781491/d882f064-82b9-4d4c-b4b1-8adc14767415)

Lazer:

![CleanShot 2024-03-23 at 05 52 11](https://github.com/ppy/osu/assets/22781491/279cfd3b-33a9-4a64-8a30-94e8de0e9ce7)

### Version

2024.302.1-lazer

### Logs

-

**Comment by ominoussage** [comment]
I've always noticed this for years but thought it was intentional. Oops.
