### ISSUE TITLE
Beatmaps without Mp3 causing a crash

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#2770]
Beatmaps with no Mp3 causing lazer to crash when you try to change the state in the music controller 
[runtime.log](https://github.com/ppy/osu/files/2087555/runtime.log)

**Comment by UselessToucan** [comment]
Could you please provide concrete steps to reproduce the problem? I also would like you to provide a beatmap.

**Comment by peppy** [comment]
For what it's worth I did test this and could not reproduce the issue.

Also the crash in the provided `runtime.log` is unrelated (but still a valid concern)

**Comment by Lolihunter1337** [comment]
https://streamable.com/a8fvx

The Map: https://osu.ppy.sh/beatmapsets/665562#osu/1408519

last runtime.log which got logged 
[runtime.log](https://github.com/ppy/osu/files/2106267/runtime.log)

**Comment by Lolihunter1337** [comment]
Sorry. my bad! i got another runtime log on editor 
[runtime.log](https://github.com/ppy/osu/files/2108229/runtime.log)

**Comment by Lolihunter1337** [comment]
Yes. 


The other runtime.log only appears when changing the time on the music controller
