### ISSUE TITLE
Score inconsistency before & after a replay due to mishandling slider ends

### ISSUE THREAD

**Issue by WiIIiamWei** [ppy/osu#27704]
### Type

Game behaviour

### Bug description

I've been watching a lot of replays recently and found a lot of score inconsistencies between leaderboard scores and replay scores. I tried a lot of different replays trying to grasp what is going on, and I found nearly all of them is caused by slider ends. So I assume there is something wrong in slider end judgements with Classic mod (i.e. stable scores in lazer).

*Note: There seem to be similar issues, but I failed to find somthing that fully describes my situation imo. Sorry for the disturbance if you think I made a duplicate.*

### Screenshots or videos

Here are some examples.
| # | Link | Leaderboard score | Replay score |
| - | - | - | - |
| 1 | https://osu.ppy.sh/scores/393079484 | <img width="1280" alt="score-2c" src="https://github.com/ppy/osu/assets/37211959/9dabb455-b890-4bd4-9e27-3a5ee46488c9"> | <img width="1280" alt="score-2i" src="https://github.com/ppy/osu/assets/37211959/533047b7-0dc0-4bf7-9c7a-a0ec8a701aef"> |
| 2 | https://osu.ppy.sh/scores/1627966762 | <img width="1280" alt="score-3c" src="https://github.com/ppy/osu/assets/37211959/9f067b73-3f50-449c-9cf4-3ced4e8dd6e6"> | <img width="1280" alt="score-3i" src="https://github.com/ppy/osu/assets/37211959/44055efc-fc12-4c3b-85f1-e1abdbef0d39"> |
| 3 | https://osu.ppy.sh/scores/1637024169 | <img width="1280" alt="score-1c" src="https://github.com/ppy/osu/assets/37211959/13edf4ef-5ff5-4750-9234-63208fb0b9e5"> | <img width="1280" alt="score-1i" src="https://github.com/ppy/osu/assets/37211959/a39b9cc5-ea62-4a25-85a5-dd77a97cc5b3"> |

I intentionally watched a 2B slider map replay (example 3) to confirm whether it's because of slider ends. All the slider ends are considered a Miss in lazer replay rather than a 100/OK as it should be in stable.

Additionally, something interesting happened when I was exploring this situation:

https://github.com/ppy/osu/assets/37211959/c6dcb1d4-e81a-4fe6-a768-bce133d56432

The replay score shown in the beginning is after the first time I watched the replay **without speeding up or navigating the progress bar to skip** and it is correct with 5 100/OKs. After watching it for a second time and **navigated the progress bar to skip**, an extra slider end 100/OK appeared in the score, causing inconsistency.

I put it here because it is also slider end related. However this could be another issue. Feel free to open another one to discuss this.

All the example replays mentioned in the table is not speeded up or skipped by navigating the progress bar, however in the video the first replay score is correct, meaning it does not reproduce every time and could vary from machines to machines.

### Version

2024.312.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14731733/compressed-logs.zip)

**Comment by ssz7-ch2** [comment]
2nd example is combination of https://github.com/ppy/osu/issues/11311 + https://github.com/ppy/osu/issues/11769
3rd example is a 2b/aspire map so ignore those for now as support for these kinds of maps hasn't been added

For the 1st example, it appears that speeding up/skipping through the replay can cause the judgement times for sliderends & sliderticks to be inconsistent. The sliderend at `37435.50202502025` in this replay changes from a Great to an Ok when skipping through replay.

| playback at normal speed | skipping to end of replay |
| ---- | ---- |
| <pre>result.Type: Great<br/>result.RawTime: 37436.085754347216</pre> | <pre>result.Type: Ok<br/>result.RawTime: 37444</pre> |

The times here are retrieved from the result in ScoreProcessor.ApplyResultInternal

**Comment by WiIIiamWei** [comment]
> For the 1st example, it appears that speeding up/skipping through the replay can cause the judgement times for sliderends & sliderticks to be inconsistent.

Sometimes without speeding up/skipping through could also cause inconsistency. This happened last week on the very same replay file but I didn't pay much attention. As I said:

> it does not reproduce every time and could vary from machines to machines.

I'll watch the replay thoroughly for a few more times when I have time to see if it could be reproduced.

**Comment by WiIIiamWei** [comment]
<img width="1280" alt="image" src="https://github.com/ppy/osu/assets/37211959/ebb182bf-172a-4642-969c-215a26a6ca9a">

Reproduced after changing fps limiter from 2x to VSync. No skipping or speeding up. Does it have something to do with frame rate?

Logs here for diagnose.

[compressed-logs.zip](https://github.com/ppy/osu/files/14734911/compressed-logs.zip)

**Comment by ssz7-ch2** [comment]
Sorry I was looking at the wrong place. The actual problem seems to be how lazer differs from stable with handling decimal numbers.

The slider small tick is at `37399.50202502025` in lazer whereas stable truncates it to `37399` afaik
And the replay has a frame with key pressed at `37399` and a frame with key released at `37402`
So at `37399` stable counts it as a hit while lazer doesn't
<br/>

The reason why the sliderend behavior is inconsistent in lazer is because, in order for the sliderend to be hit, the game has to check between `37399.50202502025` and `37402` (not inclusive). And low framerate/skipping through the replay will skip past that timeframe, causing the sliderend to be missed.

**Comment by tybug** [comment]
Replay playback when seeking is known to be a bit buggy; it could be any combination of these:

#22267 
https://github.com/ppy/osu/issues/19738
https://github.com/ppy/osu/issues/19766
https://github.com/ppy/osu/issues/21659
https://github.com/ppy/osu/issues/23709

I'm going to cc @ppy/team-client only because @ssz7-ch2's theory on the third replay sounds promising and isn't one I've heard before (slider ticks having fractional times could cause discrepancies in scoring).

**Comment by tybug** [comment]
Thanks for the report @WiIIiamWei. Since all of these cases are covered by existing issues, I'm going to close this in favor of #21659 and the issues linked here https://github.com/ppy/osu/issues/27704#issuecomment-2016572450.
