### ISSUE TITLE
Drifting offset upon poor performance

### ISSUE THREAD

**Issue by BlockHead007** [ppy/osu#27710]
### Type

Performance

### Bug description

May be related to #27567 and #26237
It looks like that background tasks may inflict on games offset if they are taking some cpu resources. Lazer works fine at launch, but as time goes sound offset starts to drift to abnormal values. I finally managed to reproduce it and here is what I did:
1. (optional, it drifts even without this step) Limited cpu frequency, so cpu works slower than it should (base 3.27ghz, worked at ~2.2ghz);
2. Launched the game in borderless mode and started autoplay;
3. Moved mouse to another screen without losing games focus where i had task manager opened and started scrolling it continuously, so games performance became worse.

As a result audios offset started to drift. Here are my specs:
AMD Ryzen 5600H,
32GB Ram,
RTX 3060 Mobile.

### Screenshots or videos

https://www.youtube.com/watch?v=rJPoLKxYn6w

### Version

2024.312.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14735211/compressed-logs.zip)
Latest session

**Comment by peppy** [comment]
Please post in one of those threads, rather than opening a new one. Thank you.
