### ISSUE TITLE
Catmull sliders with anchored points look incorrect compared to stable

### ISSUE THREAD

**Issue by Digitalfear117** [ppy/osu#27712]
### Type

Cosmetic

### Bug description

Nearly all Catmull sliders with anchors do not look the same as they do in osu! stable. Although this doesn't affect gameplay, they are quite ugly. Catmull sliders with either red or white anchors seem to always have this curved ball shape around their points in lazer. In stable this typically only happens when you create a red anchor point with very large angle changes and little to no additional anchors nearby. Here is a comparison of the current version of lazer, stable, and a late 2010 version of osu! 
![image showing this same catmull object in different versions of osu! In lazer the slider has a noticeable bump where it doesn't have this in stable](https://github.com/ppy/osu/assets/28713262/49426cd1-7aa7-4b40-8ead-2ad4f8bbc843)
[This is the beatmap in question](https://osu.ppy.sh/beatmapsets/11219#osu/45282), the object is at 00:40:768, and here is the .osu snippet for this slider 
`320,352,44078,6,0,C|352:328|352:328|360:248,2,90,8|0|0`

Here is another example, [from my recently ranked map.](https://osu.ppy.sh/beatmapsets/1800845#osu/3692015) This object is at 04:29:955
![a second example with multiple red anchors where lazer makes these bumps where they should be straight](https://github.com/ppy/osu/assets/28713262/b565bfee-cd44-4e6f-a961-188b4fcdc730)
Here is the .osu snippet for this slider
`416,128,270255,2,0,C|416:160|416:176|416:176|400:176|352:176|336:176|336:176|336:160|336:128|336:112|336:112|320:112|272:112|256:112|256:112|256:128|256:176,1,350,10|0`

Other beatmaps with Catmull sliders will also have this issue too, depending on how the mapper used anchors.

### Version

2024.312.1 and (all?) versions before this

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14735537/compressed-logs.zip)

**Comment by tybug** [comment]
cc @ppy/team-client
