### ISSUE TITLE
Application does not start on Android smartphone

### ISSUE THREAD

**Issue by shiumano** [ppy/osu#27737]
### Type

Other

### Bug description

Since version 2024.312.0, osu does not start on my Xperia 1 V.
It plays fine on my Xperia 5 II.
Also, although not logged, 2024.312.1 did not start on my AQUOS R8 pro.

I was able to play until 2024.302.0, but the moment I upgraded to 2024.312.0 it stopped starting.
I tried deleting data and reinstalling to no avail.

### Screenshots or videos

[2024年3月27日 [xqBeQD7O-84].webm](https://github.com/ppy/osu/assets/75152752/a7e1f18a-d25b-45af-ae3a-90e6c95e7598)

### Version

2024.312.1

### Logs

[logs.zip](https://github.com/ppy/osu/files/14775337/logs.zip)

**Comment by shiumano** [comment]
sentakki built with the latest version of the source can work
[2024年3月28日 [rYp__-noke4].webm](https://github.com/ppy/osu/assets/75152752/a4847a4c-9913-4884-86ab-4a8356e69a64)

**Comment by bdach** [comment]
I don't know why you're bringing up "sentakki"? If you're implying that it's the ruleset's fault then please report this to the authors of the ruleset.

**Comment by shiumano** [comment]
It was my fault for complicating the conversation. I am truly sorry.......
My point was that official releases do not boot, but those built from source do. The APK I built myself could not be installed due to signature issues, so I installed sentakki's build instead.
The problem is with the official release.
