### ISSUE TITLE
Export bans on mobile devices are inconsistent

### ISSUE THREAD

**Issue by shiumano** [ppy/osu#27741]
### Type

Cosmetic

### Bug description

related issues: #22676 
related pr: #7977 

Export settings were previously disabled on mobile platforms, but enabled for recently added features. (You probably haven't touched it since you disabled it, but it seems to work on Android.)
Even though it works within the application, the file location is still crazy. Once you enable it, there will be no end to people crying, "Where's my replay file!? Help me, Peppy!!!"
Is it possible to disable all of them, or basically disable them and enable them by setting "Enable export" in the settings?
Also, on other platforms, clicking the export completion notification opens the destination folder, but is it possible to launch a file picker activity on Android as well?

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/75152752/2e631424-ec93-40f4-8bf2-042ced33ea25)
![image](https://github.com/ppy/osu/assets/75152752/58760edd-ea0e-4518-9f61-2fcad9dd684d)
![image](https://github.com/ppy/osu/assets/75152752/092eb7e7-9435-489f-900a-4e5fa49493a2)
![image](https://github.com/ppy/osu/assets/75152752/5f508c8d-b565-4d29-84de-9cd250e5def4)

### Version

2024.312.1

### Logs

[1711595789.runtime.log](https://github.com/ppy/osu/files/14783679/1711595789.runtime.log)
[1711595789.performance.log](https://github.com/ppy/osu/files/14783680/1711595789.performance.log)
[1711595789.network.log](https://github.com/ppy/osu/files/14783681/1711595789.network.log)
[1711595789.auth.log](https://github.com/ppy/osu/files/14783682/1711595789.auth.log)
[1711595789.input.log](https://github.com/ppy/osu/files/14783683/1711595789.input.log)

**Comment by Walavouchey** [comment]
you're describing 3 separate things in this issue:

1. you can export beatmaps/skins from the settings, even though you can't export directly from the editors
2. the exact same thing as https://github.com/ppy/osu/issues/22676 (you even linked the issue)
3. clicking on an "export completed" notification doesn't open a file picker on android

report one thing at a time, with no duplicates, please. this is just confusing

**Comment by tybug** [comment]
I think we can close this in favor of #11911.
