### ISSUE TITLE
Playlists can show an incorrect number of completed beatmaps

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#27759]
### Type

Game behaviour

### Bug description

I don't know how to recreate this bug as of now so this is my best guess: I'm 90% sure the reason this happened was because I quit in the middle of a beatmap, it caused my accuracy to lower and read as if I completed the beatmap on the leaderboard of the playlist. This issue did not solve itself until I completed the beatmap I quit. It continued to exist after completing maps before I completed the quit map.

### Screenshots or videos

Video showing right before I completed the map I quit in the middle of:

https://github.com/ppy/osu/assets/58333920/39d6f5a0-238b-484c-9a90-83fc0d0865df

### Version

2024.312.1

### Logs

[shortened_1711771111.network.log](https://github.com/ppy/osu/files/14810524/shortened_1711771111.network.log)
[shortened_1711771111.runtime.log](https://github.com/ppy/osu/files/14810525/shortened_1711771111.runtime.log)

**Comment by Walavouchey** [comment]
very easy to reproduce with the steps described in op

1. play a map in a playlist, exit before completion. this one somehow increments the "completed beatmaps" count
2. play and complete another map in the playlist (to make sure you have a score that puts you on the playlist leaderboard)

room: https://osu.ppy.sh/multiplayer/rooms/620870
scores:
  1. a prematurely exited score that i can't get the id of, but it was achieved right before the below one
  2. https://osu.ppy.sh/scores/2593265337

@ppy/team-client

**Comment by peppy** [comment]
Playlist aggregate scoring is currently handled by osu-web, so this is gonna require @ppy/team-web to take a look at (probably @nanaya due to familiarity with the system).
