### ISSUE TITLE
api v2 query result does not match the expectations

### ISSUE THREAD

**Issue by HollisMeynell** [ppy/osu#27764]
### Type

Other

### Bug description

I'm not sure where to report the issue with the API. If it shouldn't be here, I'll remove it.

description:

The response from the API  `beatmaps/{beatmap}/scores`  is incorrect.
this score [2558700199](https://osu.ppy.sh/scores/2558700199) 
api v2 query response returns `404 Not Found` without `legacy_only=1` when i get
 `https://osu.ppy.sh/api/v2/beatmaps/4162586/scores/users/33295812&mode=osu`

I can only get the correct response when specifying 'legacy_only=1'

The documentation describes it as 'Whether or not to exclude lazer scores. Defaults to 0.' According to the description, it should return any existing scores rather than 'Not Found'.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/56613764/676ae183-fb38-440c-89ed-b53da731298b)

### Version

now?

### Logs

no logs

**Comment by Joehuu** [comment]
As mentioned in https://osu.ppy.sh/docs/index.html#introduction, API issues should be in https://github.com/ppy/osu-web/issues.
