### ISSUE TITLE
Playing pending beatmap with an update available throws `invalid beatmap_hash` to user

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#27781]
### Type

Game behaviour

### Bug description

This type of notification should be hidden from user.
Maybe reword to "Your score will not be submitted. Please, update the beatmapset."

### Screenshots or videos

https://github.com/ppy/osu/assets/86934170/c810d6f6-6a31-45b2-a976-e51dd0f1cecf

### Version

2024.312.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14852945/compressed-logs.zip)

**Comment by 64ArthurAraujo** [comment]
it appears it should have a custom message but they did not create for that case yet
![image](https://github.com/ppy/osu/assets/90941580/d54c1e91-2023-4164-b0ce-813832b35224)
