### ISSUE TITLE
Cursor shows after using smoke on Mac OS

### ISSUE THREAD

**Issue by SC7RED** [ppy/osu#27796]
### Type

Game behaviour

### Bug description

This bug has been going on for a little bit now and happens after I use smoke. Only way to fix it is to tab out and tab back in but during gameplay you can't really do that and the cursor becomes very distracting.

### Version

2024.312.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14879639/compressed-logs.zip)

**Comment by Rekunan** [comment]
Can you provide a video of this? Having trouble parsing the logs properly.

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/24620
