### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Sukuratchi** [ppy/osu#27817]
### Type

Crash to desktop

### Bug description

Just finished playing a map and went to check my rank by clicking on the profile thing on the top right from song select, then just crashed

### Version

2024.312.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14922902/compressed-logs.zip)

**Comment by Joehuu** [comment]
This was already fixed by https://github.com/ppy/osu/pull/27754. Just need to wait for the next release that may come this week.
