### ISSUE TITLE
Can not launch on Windows ARM64

### ISSUE THREAD

**Issue by louist103** [ppy/osu#27813]
### Type

Other

### Bug description

This only occurs when targeting ARM64. I built this on an x86_64 machine cross compiling for ARM64. I set the architecture to ARM64 in the build menu. After building I took the release folder from `osu.Desktop\bin\ARM64\Release\net8.0` and moved it to the ARM laptop and got the crash. When targeting `Any CPU` it launches fine on the x86 machine. I can not launch the x86_64 build on the ARM machine since it is running Windows 10 and can not emulate 64 bit apps.
Even though the logs suggest a missing veldrid DLL I do see `ppy.Veldrid.dll` and a few other similar files in the build folder. 
I also have the OpenGL Compatibility layer installed on the ARM machine. 
I did see #12210 but it doesn't look like they tried building in that thread.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/35883445/83e010a3-dcef-44ca-9172-fa19cccbe584)

### Version

b226a056377d3cc5ab537c2f9fd98fa851923c2c

### Logs

I can't launch the game so I can't get the logs from that but I can get the event viewer back trace and build logs from Visual Studio.
[event viewer.txt](https://github.com/ppy/osu/files/14911664/event.viewer.txt)
[files.txt](https://github.com/ppy/osu/files/14911686/files.txt)

[build.txt](https://github.com/ppy/osu/files/14911665/build.txt)

**Comment by bdach** [comment]
https://github.com/veldrid/veldrid-spirv/issues/29
