### ISSUE TITLE
Incorrect slider stacking on specific beatmap

### ISSUE THREAD

**Issue by bdach** [ppy/osu#27822]
### Type

Game behaviour

### Bug description

Was looking at https://github.com/ppy/osu/issues/27712 / https://github.com/ppy/osu/pull/27734 and found this instead...

1. Download https://osu.ppy.sh/beatmapsets/215#osu/713
2. Look at 00:02:610 (1,2)

stable has the two sliders perfectly stacked:

![image](https://github.com/ppy/osu/assets/20418176/e20675f3-0301-4a49-bf53-c60157380a98)

and lazer does not:

![image](https://github.com/ppy/osu/assets/20418176/74997741-7aa1-45e8-82ea-9be66879eb39)

### Screenshots or videos

above

### Version

current master

### Logs

n/a

**Comment by bdach** [comment]
Never mind, I got played. It's fine in gameplay. Apparently stable editor just doesn't apply stacking.

![screenshot116](https://github.com/ppy/osu/assets/20418176/6960e4c9-d6b6-47c1-b29e-2b46728ed040)

**Comment by smoogipoo** [comment]
It does but it's broken in some cases. May also be https://github.com/ppy/osu-stable-issues/issues/388

**Comment by peppy** [comment]
> It does but it's broken in some cases.

Also depends on the setting under the view menu.

**Comment by bdach** [comment]
I checked the setting because I saw that in code search but it was not due to the setting.
