### ISSUE TITLE
Vulkan renderer fails to initialise on Linux

### ISSUE THREAD

**Issue by Kaktus14** [ppy/osu#27844]
### Type

Other

### Bug description

Arch Linux

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/108426150/9568c5be-bbbf-4c98-aa59-47567d7b589a)

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14965714/compressed-logs.zip)

**Comment by smoogipoo** [comment]
https://github.com/ppy/osu/discussions/27659
