### ISSUE TITLE
System.DllNotFoundException: e_sqlite3

### ISSUE THREAD

**Issue by Dhs92** [ppy/osu#2785]
Intsalled osu-lazer-git from the AUR and received this error on startup. Here are my logs:
https://media.dhs92.me/database.log
https://media.dhs92.me/runtime.log

**Comment by jai-sharma** [comment]
The AUR package is not officially supported.

We recommend not using the AUR package and instead compiling the game yourself.

**Comment by Dhs92** [comment]
Interesting, works fine when I compile on my own :). The AUR version pulls directly from  the github page, so I didn't think it'd make much of a difference.
