### ISSUE TITLE
In tablet mode Left mouse button releasing upon getting input from tablet.

### ISSUE THREAD

**Issue by RadekMojzis** [ppy/osu#27862]
### Type

Game behaviour

### Bug description

When the tablet input option is enabled, the left mouse buttons input immediately releases (key-up) when the tablet changes cursor position (It is impossible to drag with left mouse button while moving the cursor with tablet).

Steps to reproduce: 

1. Turn on osu
2. enable tablet input in the menu
3. Hord left mouse button
4. move the cursor ussing the tablet

I normally play with a keypad and i bind mouse buttons to keys that I use to click in game - so that i don't have to click with stylus/mouse in the menu or in windows.

This issue is not in any way related to the keypad - mouse clicks work exactly the same.

Works the same way on windows 10 and 11 on multiple computers  - my tablet is One by Wacom S

### Screenshots or videos

https://youtu.be/aujE6S3tEUQ?t=94

### Version

All versions with the tablet drivers (right now that would be 2024-412.1)

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14971548/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/discussions/27310 probably
