### ISSUE TITLE
osu!lazer consumes huge amounts of ram

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#2787]
Each time osu!lazer starts a map, its ram usage rises, probably due to some map data getting cached. Though after the map is finished, this ram space isn't cleared, which means that if enough maps are played (or the right ones) osu!lazer will eventually use up all the ram it can get, which in my case equals 80% of my 16gb RAM.

A very good map to check this out: https://osu.ppy.sh/s/631235
Each time the map gets loaded, osu!lazer uses huge amounts of ram, even reloading the same map over and over increases said ram usage. Forcing garbage collection usually clears out some ram, although not nearly as much as I believe would be possible.
Made a quick and low quality video here: https://streamable.com/nh5tl

**Comment by Lolihunter1337** [comment]
and extreme example is this map: https://osu.ppy.sh/s/121591 trying to load this map in the editor is not ending good at all

**Comment by peppy** [comment]
The remaining issue is due to a parsing issue where hundreds of thousands of slider ticks are generated.

**Comment by Morilli** [comment]
This has... somewhat been fixed by simply ignoring the problematic cases. Probably better to make a new issue if it occurs later anyway.

**Comment by peppy** [comment]
Just to confirm, is the mentioned map better now?

**Comment by Morilli** [comment]
Well, in terms of playability and ram usage, the map is now fine, yes. The hitobjects that were responsible for that are just no longer in the map, as per https://github.com/ppy/osu/pull/4462.
