### ISSUE TITLE
Osu Classic Replay Shows Slider Hit Inaccurately

### ISSUE THREAD

**Issue by mojobojo** [ppy/osu#27911]
### Type

Game behaviour

### Bug description

The original score is an FC as can be seen here
![image](https://github.com/ppy/osu/assets/513778/74caaee5-3231-4a89-8eeb-f87e64bef5b1)

When I watched the replay back it ended up with a miss at combo 1142. If I drop the cursor size and check, its a very very close edge hit so I suspect this has something to do with slider leniency differences.
![image](https://github.com/ppy/osu/assets/513778/d892e3ce-71b9-46db-a6db-02de61627a4c)

Here is the results screen from the score
![image](https://github.com/ppy/osu/assets/513778/186e3bf4-d88e-49eb-9a3c-d48e8abc28b7)

Here is the replay:
[mojobojo playing OISHII - ONIGIRI FREEWAY (Hazu-) [TATAN_S EXPERT] (2022-01-20_00-58).zip](https://github.com/ppy/osu/files/15008952/mojobojo.playing.OISHII.-.ONIGIRI.FREEWAY.Hazu-.TATAN_S.EXPERT.2022-01-20_00-58.zip)

### Version

Lazer 2024.412.1

### Logs

[logs.zip](https://github.com/ppy/osu/files/15009056/logs.zip)

**Comment by Walavouchey** [comment]
this is likely due to the score being old and slider mechanics having changed since

@ppy/team-client

**Comment by smoogipoo** [comment]
I dunno. Could be any number of issues.

- Could be float positioning related.
- Could be integer timing related.
- Could be replay playback related as we've seen many times in recent past.

I don't believe it's a change to slider mechanics.
