### ISSUE TITLE
Add ability to adjust already-placed objects when changing timing offsets

### ISSUE THREAD

**Issue by rust2** [ppy/osu#27915]
### Type

Other

### Description

There must be an ability to tweak already existing circles, sliders, etc. when timing section's offset is changed by buttons near metronome

### Screenshots or videos

![osu_2024-04-17_19-07-21](https://github.com/ppy/osu/assets/43823272/14dc43fd-0362-4766-9e20-d087ab3b0a3d)

### Version

2024.412.1

### Logs

not needed?

**Comment by Joehuu** [comment]
Stable has this feature already so not converting to discussion.

![Screenshot 2024-04-17 at 12 45 04 PM](https://github.com/ppy/osu/assets/35318437/9145bcee-52aa-4b12-aa63-5b4140383675)

**Comment by rust2** [comment]
> Stable has this feature already so not converting to discussion.

Yes, I know about stable's one but this is lazer's repo and I miss this feature here, in "the next major update of osu"
