### ISSUE TITLE
Beatmaps are stuck at "Qualified" and don't update to "Ranked"

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#27936]
### Type

Game behaviour

### Bug description

As the title says, Qualified Beatmaps don't update their status to Ranked, once they get ranked. I'm not sure if this always happens or only with some beatmaps. Maybe this problem isn't only restricted to Qualified maps, but to all Beatmap status updates, but I couldn't test that yet.

I think now that pp is a thing in Lazer and a lot more people switch over to Lazer, this might be pretty important to a lot of people. Here are some screenshots of the problem:

Beatmap gets shown as Qualified in Song Select:
![osu_2024-04-19_15-12-02](https://github.com/ppy/osu/assets/81645139/b684ab12-24c1-43a7-8409-70c8c4c39ef0)

Beatmap is Ranked in reality:
![osu_2024-04-19_15-12-36](https://github.com/ppy/osu/assets/81645139/5448cf07-47a7-46a9-a382-97898aaf01aa)

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15040925/compressed-logs.zip)

**Comment by bdach** [comment]
Presumably the same thing as https://github.com/ppy/osu/issues/23804#issuecomment-1586620316
