### ISSUE TITLE
The main menu occasionally doesn't restore correctly

### ISSUE THREAD

**Issue by LovelyA72** [ppy/osu#2793]
Version: 2018.612.0
When you use esc to exit the song selection menu, the main menu will randomly disappear. When you hit esc again, osu! logo will appear with "see you next time" and exit the game.

Here is the screen shoot:
![missing menu](https://user-images.githubusercontent.com/29054052/41352844-1ad9ef02-6f4d-11e8-9d1d-04fd6dd01d80.JPG)

**Comment by Lolihunter1337** [comment]
can reproduce

**Comment by peppy** [comment]
I can also reproduce this once in hundreds of tries. Has anyone found a way to increase the predictability of this bugging out>

**Comment by peppy** [comment]
I haven't been able to reproduce this for a while now. Can anyone still repro on the latest master?

**Comment by peppy** [comment]
Reproduced.

**Comment by peppy** [comment]
After many tries I cannot reproduce this on my main dev setup. It may be dependent on very high frame rates.

Based on manually tracing through the logic, it seems `OnExiting` must be getting called with an incorrect screen, rather than `MainMenu`. `SongSelect`'s `OnExiting` is definitely getting called (logo outward animation plays via [onExitingLogo](https://github.com/ppy/osu/blob/master/osu.Game/Screens/OsuScreen.cs#L192)) but the background is not switching to the `MainMenu` background (as seen in the OP screenshot). It is either stuck at the song select background or another screen's background.

**Comment by LovelyA72** [comment]
That's the main menu background. I applied a custom skin to my lazer.

**Comment by peppy** [comment]
Could you please not do this in the future? It completely breaks our ability to debug issues.

**Comment by LovelyA72** [comment]
Sorry:( this is my fault. I will use default data for further. I really apologize.

**Comment by peppy** [comment]
Can you still reproduce this one? I've tried hundreds of times to no avail.

**Comment by Joehuu** [comment]
Can reproduce easily with only the osu! logo showing. Doesn't require switching screens.

Steps:
Left click mouse and esc simultaneously at the starting menu screen.

https://puu.sh/APa8q/e8bce21122.gif

**Comment by peppy** [comment]
I think that may be a different issue, but definitely an issue nonetheless.

**Comment by LovelyA72** [comment]
I just tried, and also I can not reproduce it on the version 629.

**Comment by LovelyA72** [comment]
![image](https://user-images.githubusercontent.com/29054052/42424163-349714e2-82bc-11e8-9b6f-7a99486f7666.png)
This is 2018.705 pure origional version. reproduced by using esc to go back to menu after quit from a song(not finish)

**Comment by peppy** [comment]
I believe I've already fixed this in #2945.

**Comment by peppy** [comment]
Could you show a screenshot or video?

**Comment by Nyanekoy** [comment]
Well like before. the problem is it happens very rarely and really randomly. :( its pretty hard to reproduce

**Comment by Lolihunter1337** [comment]
so i tried to reproduce it for about an hour now and in all that time it happend once. no idea how or why but i can say it happend

**Comment by Morilli** [comment]
I can attempt to reproduce it and make a video of it.
