### ISSUE TITLE
DefaultHealthDisplay change it's scale when attached to mania playfield

### ISSUE THREAD

**Issue by DaiterGG** [ppy/osu#27938]
### Type

Game behaviour

### Bug description

I think it scales with mania stage sprite because It's getting bigger with more keys
There is also 8 scale points on this specific health bar, 4 of them does not change the scale

### Screenshots or videos

![Screenshot_4](https://github.com/ppy/osu/assets/64665908/26095f04-4b63-4e87-979a-72a57fab87b9)
![Screenshot_6](https://github.com/ppy/osu/assets/64665908/94084314-2030-49e9-a93e-62641c8fc83d)
![Screenshot_7](https://github.com/ppy/osu/assets/64665908/3b5520d1-1a3e-48e3-a897-058e5c654988)

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15042556/compressed-logs.zip)

**Comment by smoogipoo** [comment]
This is because `DefaultHealthDisplay` uses `Axes.X`, and even though it's rotated vertically it's still relevant to the parent container's width, which is the playfield's width.

One way to resolve would be to use `Width = 1366` instead. This would be a breaking change for skins.

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/24388
