### ISSUE TITLE
Fade-out transparency clipping during app quit

### ISSUE THREAD

**Issue by tractorbeam0** [ppy/osu#27959]
### Type

Cosmetic

### Bug description

Absolutely doesn't really matter that much, probably doesn't affect anybody with a 1080p or lower monitor, but still worth putting a report up about it.

During the "Cya next time" fade-out, around the osu! logo, I noticed that the little bars would clip through the fading logo because it's transparency is being changed independently to the logo. It's a really easy fix, honestly.

It can't be seen faintly in the attached screenshot

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/37884919/9ba5e1af-23f6-482d-82eb-5b397eec6ac8)

### Version

2024.412.1

### Logs

eh whatever
[compressed-logs.zip](https://github.com/ppy/osu/files/15053097/compressed-logs.zip)

**Comment by PLGGitHub1** [comment]
osu!lazer Is not a .exe. Its a Shortcut.
Try Moving the bars that dosent clip.

**Comment by smoogipoo** [comment]
I don't think this needs an issue. It could even be considered intentinonal.

**Comment by peppy** [comment]
It's a side effect from trying to best align quads to a circle, not such a simple fix as alluded to

**Comment by tractorbeam0** [comment]
I wasn't implying to align them, I suppose I should've been more clear. If I'm not mistaken, moving the changing transparency to a parent layer would apply it to the whole logo and bars equally, since it would be working with the buffer containing both of them rendered as apposed to the bars and the logo individually.

Its also worth considering just making a black texture fade over everything, although you guys might consider that a lazy fix.

**Comment by tractorbeam0** [comment]
It is to my understanding that a common good practice in rendering is for effects to be applied on a buffer-by-buffer process (as in, each layer is given a dedicated buffer and rendered like a texture to other layers, effects like transparency are applied then and there), so problems like this can be avoided by way of what I described. I guess I should look at the bit smoogipoo wrote involving the new deferred renderer to get a better understanding of how it works, because this implies its very unconventional and interesting.

#this has performance implications and is not a great solution.

It is not, that would be correct. That was written at about 8ish am in my local time.

Side note: I honestly would've just put in a pull request after making a fix myself (assuming it was as simple as changing what got the alpha change), but I'm not good with C#. Something about the design choice to automatically manage when a variable should be a reference and when it should be a copy really irks me.
