### ISSUE TITLE
mismatched checksum between downloaded .osz and online checksum

### ISSUE THREAD

**Issue by ILW8** [ppy/osu#27961]
### Type

Game behaviour

### Bug description
Problem mapset: https://osu.ppy.sh/beatmapsets/731259

Probably related to #25078. Distinction being that this map is graveyarded

After downloading the mapset, the update button for this mapset is always visible even after updating. Upon further inspection, the md5sum of the `.osu` files don't match the checksum returned by the API for all difficulties besides `ALEXA's NIGHTMARE`

### Screenshots or videos

https://github.com/ppy/osu/assets/1176059/7488e57f-b3fd-4825-ab5c-c49055ba7d26

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15055283/compressed-logs.zip)

**Comment by peppy** [comment]
Not too interested in fixing graveyarded beatmaps that have this kind of mismatch for now.
