### ISSUE TITLE
Bug with selection of Daycore Mod

### ISSUE THREAD

**Issue by Hickacou** [ppy/osu#2796]
When we select Nightcore or Daycore mod, this mod is impossible to disable. And, when the nightcore is supposed to be selected, the Daycore is still selected. 
I think a video is the best way to explain you the issue : 
https://www.youtube.com/watch?v=4IJZoOSHweE
(I apologize for the bugged audio ^^)
_The record was made on 2018.611.0 but the bug is still here on 2018.612.0_
The audio become normal on the main menu but the daycore comes back in the song select menu.

**Comment by Joehuu** [comment]
Fixed in #2789. You need to wait for the next release to come out.
