### ISSUE TITLE
Left or Right click Inputs gets stuck randomly

### ISSUE THREAD

**Issue by Jitro124** [ppy/osu#27980]
### Type

Game behaviour

### Bug description

I'm kinda new to this but I found this weird bug where on an specific beatmap at least (Minor Piece on Insane https://osu.ppy.sh/beatmapsets/2147857#osu/4524267) my Inputs freeze or just stopped working, I thought it was my keyboard until I tested outside the game and nothing seemed wrong, it also seems to not happen in other maps that I tested and also it looks that doesn't happen on Stable as far as I played for now.

It happened very often that I recorded 2 examples, one of the replays I saved when it happened and one with the frame graph while playing just in case it helps, on a last note, I played very little to test it but I think this only happens when running the game on Direct3D 11 (Experimental)

### Screenshots or videos

https://github.com/ppy/osu/assets/167953762/aed0fa92-47ea-4da7-bea7-f061652104b7

https://github.com/ppy/osu/assets/167953762/d824a905-330d-450a-8bd3-435f8b0abda7

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15088126/compressed-logs.zip)

**Comment by bdach** [comment]
Are you using a tablet? If yes, then are you sure that you have mouse buttons disabled?

**Comment by Jitro124** [comment]
No, Mouse only and I have the buttons disabled

**Comment by Jitro124** [comment]
Alright just for now I think it actually was on me, I got time to play it on another computer and nothing happened, meanwhile in this one it still happens so I unplugged and cleaned the keyboard and it looks like it works fine now, kinda weird since 3 days ago, it only happen on that specific map, and I could play fine on others until I replayed that map for some reason, I think I'm gonna close it until it somehow happens again and it's not a hardware or drivers issue from me
