### ISSUE TITLE
Typo in First-run setup when the language is set to "Português"

### ISSUE THREAD

**Issue by luizfern12** [ppy/osu#28016]
### Type

Cosmetic

### Bug description

In first-run setup set the language to "Português", proceed until the "Obtendo Beatmaps" section, then click on "Obter beatmaps recomendados". There is a missing space between the text and the number.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/48565831/47b97d36-dcd9-47c5-af27-bdfcd12255d7)

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15140470/compressed-logs.zip)

**Comment by Joehuu** [comment]
Have contributed a translation with a space in https://crowdin.com/editor/osu-web/574/en-pt?view=comfortable&filter=basic&value=0#17372. You may upvote mine (or improve it more if possible), but I've already -1'd the one without.
