### ISSUE TITLE
Beatmap background is applied inconsistently to main menu on startup when themed music is turned off

### ISSUE THREAD

**Issue by SupDos** [ppy/osu#28038]
### Type

Cosmetic

### Bug description

When the option *osu! themed music* is turned off, the game selects a random beatmap to play on startup. This alongside the *Background Source* option being set to *Beatmap* should make it so that the background is always whatever beatmap is currently being played. 

This seems to be inconsistent when the game is started: a lot of the time it uses the default pippi background (every once in a while it will use the triangles background instead of pippi), and sometimes will actually use the beatmap's background image/video/storyboard. 

### Screenshots or videos

Screen recordings showing two startups right after each other for all 3 intros

Welcome:

https://github.com/ppy/osu/assets/6813986/d594dbdc-5b6d-4bdc-a6f1-63724db0dedb

Circles:

https://github.com/ppy/osu/assets/6813986/f85311c4-082d-4f26-86e9-dce7748a9763

Triangles (two correct backgrounds at first, followed by a wrong one):

https://github.com/ppy/osu/assets/6813986/06cd4abc-62c7-4cf9-86d3-fb824cf314fe

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15166624/compressed-logs.zip)
(I restarted the game many times, so there are a ton of log files, sorry about that)

**Comment by peppy** [comment]
Probably an issue with supporter detection (not handling login state change correctly)
