### ISSUE TITLE
Replays made in lazer don't remember if a click was made with mouse or keyboard

### ISSUE THREAD

**Issue by nikunaku** [ppy/osu#28032]
### Type

Game behaviour

### Description
All clicks in a lazer replay say they are made with mouse when played back in stable. (I'm not a mouse-only player)
Sure, replays made in lazer shouldn't be played in stable, but IMO it should differentiate between input methods anyway.

### Screenshots or videos

![shouldnt_be_mouse](https://github.com/ppy/osu/assets/166950173/b9744126-2085-4e1b-8c49-1a42de93cca8) < - - - - numbers should appear on the "K₁" and "K₂" key counters

### Version

2024.412.1-lazer

### Logs

Logs below are just from exporting a random replay, the problem still occurs: (likely n/a though)
[compressed-logs.zip](https://github.com/ppy/osu/files/15151648/compressed-logs.zip)

**Comment by bdach** [comment]
lazer has fully rebindable key inputs and as such the distinction between "keyboard" and "mouse" presses is no longer attempted. It could be a controller key press or a midi key press for all you care.

I do not foresee this changing.

**Comment by peppy** [comment]
I agree it would be nice to show this for replays. We may add support at some point.

**Comment by bdach** [comment]
> We may add support at some point

Well this information is currently lost. All presses of both keybinds for either action (`LeftButton` / `RightButton`) are encoded to `leftButton1i` / `rightButton1i` (using stable vernacular). There's no feasible way anywhere in the `KeyBindingContainer` structure to distinguish whether an action press was triggered by the first or second binding. Unless you split them into four.

So technically even I'm not sure how we'd even do this given none of the underlying systems are ready or even designed to support it.
