### ISSUE TITLE
osu! crashes after ~30 minutes of gameplay

### ISSUE THREAD

**Issue by Ecstatify** [ppy/osu#28039]
### Type

Crash to desktop

### Bug description

The client crashed twice after playing for a while, and it closes immediately - no hang or freeze, just a wallpaper jumpscare.
I had the Vulkan Renderer selected.
OS: Windows 11
GPU: AMD RX 6600 (Adrenalin 24.3.1)
CPU: i5-9400F

Something else that happened earlier in the same session, which may or may not be related, was a massive lagspike followed by the client consuming an unusually high amount of RAM (around 6GB) immediately after it started responding again. Unfortunately, I only have a screenshot of task manager from right after this incident occurred. I checked event viewer but couldn't find any relevant error messages. I had no problems up to this incident and the client was already open for a while.

![Screenshot 2024-04-30 211653](https://github.com/ppy/osu/assets/48745639/4d6ee889-8393-489a-9390-d6155f021f00)
Screenshot is dated 9:16:53 PM

### Screenshots or videos

Event Viewer
1st Crash
Event 1026
![image](https://github.com/ppy/osu/assets/48745639/b0574cbf-48de-4eab-b5b7-aec0e0d70f78)
Event 1000
![image](https://github.com/ppy/osu/assets/48745639/5e8784b7-a9e3-4e5e-8f02-562ed66c77f8)

2nd Crash 
Event 1026 
![image](https://github.com/ppy/osu/assets/48745639/eb29ba4c-f803-4d16-b460-b2884acf928d)
Event 1000 
![image](https://github.com/ppy/osu/assets/48745639/93ce331c-6d2a-4543-8c6e-4285f9810105)

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15166860/compressed-logs.zip)

**Comment by bdach** [comment]
Likely overlaps with one of the reports in https://github.com/ppy/osu/discussions/27659#discussioncomment-9102265
