### ISSUE TITLE
Beatmaps lacking Description when viewing details in-game

### ISSUE THREAD

**Issue by OfficialCRUGG** [ppy/osu#28056]
### Type

Cosmetic

### Bug description

When viewing a beatmap, through the ingame view (either through right click -> "Details...", or the search) it doesn't show the Description. The massive empty space exactly where the description would be on web leads me to believe that this is not intended behavior?

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/25248999/cedb720a-8ef6-470f-bd01-e28dbe011860)
![image](https://github.com/ppy/osu/assets/25248999/4602c60b-85d2-49f3-840e-5b81808e5c1b)

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15180601/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/8023

**Comment by OfficialCRUGG** [comment]
I see. Sorry for the duplicate, GitHub issue search was only giving me results about "Beatmaps" anything that included the word "Description"
