### ISSUE TITLE
macOS unpredictable cursor snapping to center?

### ISSUE THREAD

**Issue by OfficialCRUGG** [ppy/osu#28053]
### Type

Other

### Bug description

When the game window is focused and the cursor is moved outside the window and then back in, the game either places the cursor at the edge where the cursor moves in (which is the expected behavior) or centers it. This appears to be random (?), but the latter scenario appears to occur more frequently.

### Screenshots or videos

https://github.com/ppy/osu/assets/25248999/f9c1b145-ca46-48bb-b754-62a1e7a42023

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15180107/compressed-logs.zip)

**Comment by peppy** [comment]
Can you check whether enhanced precision is turned on in settings?

**Comment by OfficialCRUGG** [comment]
Yes, it seems that was on. With it turned off, that issue no longer occurs.
