### ISSUE TITLE
Editor incorrectly playing hitsounds 

### ISSUE THREAD

**Issue by OneNiko727** [ppy/osu#28073]
### Type

Game behaviour

### Bug description

The osu! editor fails to play certain hitsounds while playing the beatmap. It seems to happen mostly on fast notes (Like streams) but it can also happen on sliders. I don't completely know how to navigate GitHub so I apologize if this is a duplicate bug report.

### Screenshots or videos

https://github.com/ppy/osu/assets/167723589/871ed36a-8eaf-45e7-9d79-addbbb1a9dd3

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip (idk what useful information this will have anyway)](https://github.com/ppy/osu/files/15195255/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/26559
