### ISSUE TITLE
Vulkan(experimental)

### ISSUE THREAD

**Issue by DeroXP** [ppy/osu#28072]
### Type

Crash to desktop

### Bug description

Sometimes while using the experimental vulkan and i go into my beat maps its glitches really bad and the UI just stays stuck or when i try to play a song. I don't know if it's my hardware, it shouldn't be because I do have good specs, but it just freezes. (May be because I play on win?)

### Screenshots or videos

![Screenshot (174)](https://github.com/ppy/osu/assets/96676237/a6521d1f-94f8-4e3a-b15f-40fa97359d07)
like here for example it's playing the song but the UI just froze.

### Version

2024.412.1

### Logs

[1714674827.runtime.log](https://github.com/ppy/osu/files/15192603/1714674827.runtime.log)

**Comment by Joehuu** [comment]
These reports currently reside in https://github.com/ppy/osu/discussions/27659, so please repost there.
