### ISSUE TITLE
Still possible to delay beatmap loading through cursor positioning.

### ISSUE THREAD

**Issue by RealistikDash** [ppy/osu#28130]
### Type

Game behaviour

### Bug description

This is a follow up to #26803 which has been mostly solved. It is still possible to delay loading by clicking the circle.

This is an issue because the circle is located at the natural hand resting position for tablet players (and in fact, the circle may act as a reference point on how to hold your pen), making it very easy for players that drag on their tablets to do this subconciously (I personally do it at least once every 5 retries).

The ideal solution would be to make interacting with the osu! logo on the loading screen do **nothing at all**.

### Screenshots or videos

https://github.com/ppy/osu/assets/36131887/70311228-8cf4-42b1-9518-47453c2ec9c3

### Version

2024.412.1-lazer

### Logs

N/A

**Comment by MTGPROD** [comment]
I though this was normal

**Comment by Joehuu** [comment]
> I though this was normal

There's https://github.com/ppy/osu/pull/22052#issuecomment-1374427279, but this can be a reason to not have this behavior. Leaving @peppy to decide.
