### ISSUE TITLE
Downloaded Beatmaps from website import don't work

### ISSUE THREAD

**Issue by Deminosa** [ppy/osu#28133]
### Type

Crash to desktop

### Bug description

Maps that you download from the Featured Arts and import into Lazer do not have hit objects. (Translate from german to English)
For more watch the video.

### Screenshots or videos

https://github.com/ppy/osu/assets/24417089/32202e25-3dc4-4ea9-b0f2-571b7ecfea0b

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15252307/compressed-logs.zip)

**Comment by bdach** [comment]
That is the point of these. These are pre-timed blank beatmaps that you can map to your heart's content.

See this text snippet at the very top of https://osu.ppy.sh/beatmaps/artists:

> All tracks in this section are provided as pre-timed .osz files and have been officially licensed for use in osu! and osu!-related content.

Actual mapped maps are [in the beatmap listing](https://osu.ppy.sh/beatmapsets).

**Comment by Deminosa** [comment]
> That is the point of these. These are pre-timed blank beatmaps that you can map to your heart's content.
> 
> See this text snippet at the very top of https://osu.ppy.sh/beatmaps/artists:
> 
> > All tracks in this section are provided as pre-timed .osz files and have been officially licensed for use in osu! and osu!-related content.
> 
> Actual mapped maps are [in the beatmap listing](https://osu.ppy.sh/beatmapsets).

Oh okay, Than Sorry.
