### ISSUE TITLE
Being able to change replay speed on OSU Lazer at the result menu.

### ISSUE THREAD

**Issue by DPH888** [ppy/osu#28139]
### Type

Game behaviour

### Bug description

Being able to change replay speed on OSU Lazer while the replay itself has ended and achieving that by holding the left button onto the spped adjustment slider from the end of the replay to the result menu. This also applies when the song changes its speed after the map itself and in the result menu (I just mean it changes its speed).

https://github.com/ppy/osu/assets/109276020/761cf20f-964b-4e47-9051-783ba2190e6f

### Version

2024.412.4

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15266832/compressed-logs.zip)

**Comment by peppy** [comment]
Just let go of your mouse and this should be fixed.
