### ISSUE TITLE
encounter an error when playing using vulkan

### ISSUE THREAD

**Issue by SoraDolla** [ppy/osu#28132]
### Type

Crash to desktop

### Bug description

 i got this message and the game just crash 
 OS: win11 pro
 pc spec: i3 10100f, 6600xt, 16gb DDR4 2666

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/169220683/76c33fa5-307c-4725-a5cd-f098435f90b4)

### Version

2024.412.1

### Logs

none

**Comment by peppy** [comment]
https://github.com/ppy/osu/discussions/27659

**Comment by SoraDolla** [comment]
[DxDiag.txt](https://github.com/ppy/osu/files/15243958/DxDiag.txt)
here the dxdiag txt
