### ISSUE TITLE
Game does not start from Time=0

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2814]
Even though there is already several countermeasures to ensure this happens, there is still a blocking delay before the game starts processing frames. This causes the intro or loading screen to display halfway through its animation, rather than from the beginning.

In stable, we processed frames until frame time became stable, if I recall correctly. We should investigate why this is happening and take appropriate action.

**Comment by smoogipoo** [comment]
I'm going to move this into the backlog since it's not high priority and there are many other productive things to do towards getting feature parity.

**Comment by peppy** [comment]
I think this has actually been resolved (there was a previous shortcoming in the `LoadCOmponentSingleFile` code which was single resolved).

**Comment by peppy** [comment]
Definitely resolved. Have not noticed this cropping up in years.
