### ISSUE TITLE
osu!catch editor on lazer loading all objects at once

### ISSUE THREAD

**Issue by SecreOsu** [ppy/osu#28150]
### Type

Performance

### Bug description

Hello! Currently the osu!catch editor on lazer is completely unusable. This is because whenever you go to test a beatmap in lazer, every single object prior loads all at once causing massive lagspikes and a severe volume warning. This has been an issue for several months, but I don't believe it was an issue on release.

volume warning on video

### Screenshots or videos

https://github.com/ppy/osu/assets/80791374/4586cd9d-5ea5-433e-ae6b-310b8c367b06

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15283378/compressed-logs.zip)

**Comment by bdach** [comment]
#20221, please search
