### ISSUE TITLE
Clearly buggy Score on leaderboard

### ISSUE THREAD

**Issue by Fanest** [ppy/osu#28164]
### Type

Game behaviour

### Bug description

Saw the highest score In Leaderboard of this map https://osu.ppy.sh/beatmapsets/2090933#osu/4382515 it had just one 300 but a crazy high combo of 3.4k was achieved also it showed a D-Rank.

I hope I haven't missed this bug when searching the issues. I also hope this is the right place for such a bug.

Amazing work on lazer <3

### Screenshots or videos

![Screenshot 2024-05-12 181504](https://github.com/ppy/osu/assets/53376250/a1e6a1fc-3a74-4778-a71c-5be6082d63b9)
![Screenshot 2024-05-12 182226](https://github.com/ppy/osu/assets/53376250/eafa16b4-a0e0-417f-b2f4-e1742d6a931c)

### Version

2024.421.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15286992/compressed-logs.zip)

**Comment by Joehuu** [comment]
That score seems to be gone now, closing.
