### ISSUE TITLE
Qualified beatmap on map selection doesn't get updated

### ISSUE THREAD

**Issue by FeellsBadSkillz** [ppy/osu#28168]
### Type

Game behaviour

### Bug description

A qualified beatmap doesn't get updated map selection as show on the screenshot  

Maybe a bug on my side of the client? ¯\_(ツ)_/¯ 

### Screenshots or videos

![osu_2024-05-13_18-27-52](https://github.com/ppy/osu/assets/57463038/d39d34d8-a8d5-436f-930c-4789fdb3d384)

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15297486/compressed-logs.zip)

**Comment by bdach** [comment]
Duplicate of https://github.com/ppy/osu/issues/21332

Please upload your `client.realm` in that issue.
