### ISSUE TITLE
Taiko editor drum pulses (kiai?) incorrectly when scrolling trough beatmap backwards

### ISSUE THREAD

**Issue by 1ivyatan** [ppy/osu#28163]
### Type

Cosmetic

### Bug description

In editor with argon or triangles skin, I have noticed that pulses on the drum pulse oddly when I scroll backwards. 

If drum hit glow appears and fades out in normal scrolling direction after a note is on the drum, should the glow fade-in and instantly disappear when the note is on the drum in opposite scrolling direction? If these skins aimed for that effect, then this effect is being executed incorrectly.

This might has to do with #27981

### Steps to reproduce

1. Use either argon or triangles skin
2. Find any taiko beatmap and open it with editor
3. Find taiko notes
4. Tap and hold arrow keys forwards and backwards and watch the drum pulse as notes pass through the drum before they get hit.

### Screenshots or videos

https://github.com/ppy/osu/assets/143333830/0a655e94-03b9-4396-9ca3-f789b8cca643

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15286474/compressed-logs.zip)

**Comment by smoogipoo** [comment]
It's the same issue as #27981, yes.
