### ISSUE TITLE
Clicked hit circle takes away cursor

### ISSUE THREAD

**Issue by shiumano** [ppy/osu#28161]
### Type

Game behaviour

### Bug description

Even a circle that has been hit and disappeared will cause a direct touch and take away the tracked cursor.
In addition to ZX in the playfield, this also occurs when the cursor moves off-screen due to Depth, etc.

### Screenshots or videos

https://github.com/ppy/osu/assets/75152752/debcc9ac-a891-419e-b2c5-b2b9c66cd184

### Version

2024.412.1

### Logs

[logs.zip](https://github.com/ppy/osu/files/15286363/logs.zip)

**Comment by smoogipoo** [comment]
I'm not really making sense of this issue, sorry. It looks like you're touching with two fingers, but retouching with the first finger? This would be expected behaviour.

**Comment by bdach** [comment]
I agree that the issue report is kinda inscrutable but looking at the implementation:

https://github.com/ppy/osu/blob/87f2a2326360c88950537a442df36550b95efc9d/osu.Game.Rulesets.Osu/OsuInputManager.cs#L45-L50

it does like we could use a `CanBeHit()` check in there somewhere just in case. I haven't even checked if this causes an actual issue but it looks like it might.

**Comment by ShiroWhiteowo** [comment]
i seem to have a similar problem...
i use a stylus to move and use another finger to click the circle, but sometimes the cursor moves to the finger i clicked the circle

https://github.com/ppy/osu/assets/161538284/04474b2e-b8fb-44db-9dc0-2dccb812fd08

**Comment by shiumano** [comment]
I apologize for always explaining myself so poorly.

The cursor position moves directly to the finger that tapped the circle. This is not a problem. Excellent.
However, if I tap the position of a circle that has already been clicked and disappeared from the game, the cursor moves to that finger. This does not make sense. Obviously there is no hit circle there, and there is no intention to tap it.

**Comment by shiumano** [comment]
We have reproduced the problem in slow motion whenever possible.
1. hit the circle
2. drag the cursor
3. Tap the location where the circle was (now there is nothing)
4. The cursor moves to the location where you tapped.

https://github.com/ppy/osu/assets/75152752/2323db6b-87a2-4378-bb04-413ae818925f


Is this expected behavior?

**Comment by smoogipoo** [comment]
Are you releasing the dragging finger (the primary finger) in that scenario? Or does it remain pressed at all times?

**Comment by shiumano** [comment]
It is still dragging. I think I recorded a video that makes it easy to see that this is so.

**Comment by shiumano** [comment]
> i seem to have a similar problem... i use a stylus to move and use another finger to click the circle, but sometimes the cursor moves to the finger i clicked the circle
> 
>  YouCut_20240513_155633193.mp4

Hmmm, this seems to be a different issue.
In Android, you can overlay the input by displaying the pointer position from the developer options.
Check to see if the stylus input is interrupted.
![Screenshot_20240514-010539](https://github.com/ppy/osu/assets/75152752/5259094e-0061-4fdf-827a-57ba87772c18)


A way to solve this problem is to define a ZX input area.
You can display a button overlay as in CTB, or you can define it as forcing the outside of the playfield to be used as such.
