### ISSUE TITLE
Sliders with soft bank in osu!lazer's editor will always turn into sliders with normal bank (volume 100)

### ISSUE THREAD

**Issue by CloudedCanadian** [ppy/osu#28160]
### Type

Crash to desktop

### Bug description

This bug has been occurring ever since I started beatmapping on osu!lazer (around 1 and a half years ago). When I insert a soft slider (volume does not matter in this case) into my beatmap, it will always turn into a normal (volume 100) slider after some time, unless the slider was already a normal slider. This bug also happenes when I leave the editor and return to it (before I left, it was a soft slider, but if I enter the editor again, it will turn into a normal slider). Adding hitsounds doesn't seem to work, nor does undoing and then redoing an action. This bug does not apply to hitcircles. The device I am using is a macbook air.

### Screenshots or videos

![B8E8C528-B98E-4D4C-B363-0C421E32D6B8_1_102_o](https://github.com/ppy/osu/assets/169593198/83985d16-bff2-4d71-95b4-478df5c80b27)

### Version

Newest version (osu!lazer)

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15286308/compressed-logs.zip)

**Comment by bdach** [comment]
same issue as https://github.com/ppy/osu/issues/25488 probably
