### ISSUE TITLE
Taiko mouse input issue

### ISSUE THREAD

**Issue by tomdenty1** [ppy/osu#2817]
Using mouse in taiko for hitting drums ends up in a sort of 'double' input, with the game viewing a mouse click as 2 simultaneous keyboard clicks (left click is handled like F and J are being pressed simultaneously.)

**Comment by peppy** [comment]
Is that not the same as on stable? Is it actually actuating hits on two separate objects?

**Comment by Lolihunter1337** [comment]
Its different. on stable with default settings the Blue and the right one get pressed while the right side stays unused
