### ISSUE TITLE
Hidden beatmap disappeared forever

### ISSUE THREAD

**Issue by Neon095** [ppy/osu#28178]
### Type

Game behaviour

### Bug description

I hidden a taiko beatmap with only one difficulty and i can't make it appear again

### Screenshots or videos

https://github.com/ppy/osu/assets/97938542/e97244a4-fbe2-4980-813a-cce13128a211

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15320645/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Click the "restore hidden beatmaps" button at the bottom of settings.

**Comment by Neon095** [comment]
That fixed it. Thx
