### ISSUE TITLE
Discord RPC error reported and not updated when multiplayer room name is a single character

### ISSUE THREAD

**Issue by taku1417** [ppy/osu#28192]
### Type

Game behaviour

### Bug description

When creating or editing a multiplayer room name with a single letter, an error is reported as shown in the first screenshot.
The second one shows that the room name is a but is not updated and is [name]'s awesome room.
The third and fourth screenshots are full screenshots. discord is omitted as it contains sensitive information (will provide if needed).

(This may be difficult to read because I am a non-English speaker. Please understand.)

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/58448175/1bb6fb7a-8745-41ca-9c8c-c1d58df7b91e)
![image](https://github.com/ppy/osu/assets/58448175/92ad45cb-d9af-49f0-b691-c0bf30a888ca)
![image](https://github.com/ppy/osu/assets/58448175/0cb17284-208c-4a4e-9af9-755d578a5dcc)
![image](https://github.com/ppy/osu/assets/58448175/62c031e0-33fb-48d1-ad21-2fcdba7f1e01)

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15337646/compressed-logs.zip)

**Comment by Ladwick** [comment]
This applies for playlists too
