### ISSUE TITLE
Hitcircle sprite size discrepancy

### ISSUE THREAD

**Issue by peppy** [ppy/osu#282]
Hitcircle sprites are currently sized to have a diameter of 144px when they should in fact be 128px. Also, the @2x version should be double the size it is now (and scales of `0.5` in game code should be removed.

@arflyte could you please export the hitcircle assets such that the ring portion is 128px width (256px for @2x).

**Comment by Tom94** [comment]
This is _almost_ fixed. We have correct sprite sizes now, but we do not yet account for transparent pixels around the sprites of the stable game client.

**Comment by Joehuu** [comment]
Is this resolved? Not sure what was being asked here.

**Comment by smoogipoo** [comment]
Yes, this has since been resolved.
