### ISSUE TITLE
Ranked map behaves as unranked

### ISSUE THREAD

**Issue by V3rald** [ppy/osu#28202]
### Type

Game behaviour

### Bug description

Few maps behaves as unranked (no pp (grey), no leaderboard, no ranked text in songselect) meanwhile on the site it shows as ranked. I have tried to delete and download the map again.
Just to give one example: https://osu.ppy.sh/beatmapsets/2049742#taiko/4597695

### Screenshots or videos

![osu_2024-05-18_14-05-48](https://github.com/ppy/osu/assets/46054316/f2704daa-0efa-4993-bdc7-3d4aa031114c)
![osu_2024-05-18_14-06-07](https://github.com/ppy/osu/assets/46054316/014a2c2a-c157-482b-91cf-83cd708a03a9)

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15363104/compressed-logs.zip)

**Comment by V3rald** [comment]
Quick update: it appears that my play did went through, submitted on the site. its just the client that does not respond properly

**Comment by BlockHead007** [comment]
Probably one of #23804 or #21332
