### ISSUE TITLE
Game freeze on the first note of the beatmaps and randomly through the beatmaps

### ISSUE THREAD

**Issue by LJW21-GitHub** [ppy/osu#28210]
### Type

Performance

### Bug description

Game always freeze when displaying the first notes of the first beat maps, and randomly freeze in beatmaps. Idk if it's just a tricky effect of for real, but it seems that it especially occurs in fast maps. Attached where the bug looks particularly present. Also attached settings that could influence this and phone specs. Don't hesitate to ask for more settings screenshots if it's helpful.
I've made some experiences in the comments

Map : https://osu.ppy.sh/beatmapsets/2154999#osu/4541962

I'm on LineageOS android 13,
Phone specifications: https://m.gsmarena.com/fairphone_4-11136.php

### Screenshots or videos

![Screenshot_20240519-092953](https://github.com/ppy/osu/assets/142221566/03bdcec6-8b91-42de-83ea-b70446c6075e)
![Screenshot_20240519-093008](https://github.com/ppy/osu/assets/142221566/6c458a6c-1bdf-4988-8d24-b6d32e23c647)
![Screenshot_20240519-093020](https://github.com/ppy/osu/assets/142221566/e6702c61-2fd7-49c8-8e52-2396b3649abb)
![Screenshot_20240519-092924](https://github.com/ppy/osu/assets/142221566/d6b0a734-ff0e-48fe-8f39-640a33fb6b9a)

### Version

2024.519.0

### Logs

[1715534203.auth.log](https://github.com/ppy/osu/files/15368540/1715534203.auth.log)
[1715534203.database.log](https://github.com/ppy/osu/files/15368541/1715534203.database.log)
[1715534203.input.log](https://github.com/ppy/osu/files/15368542/1715534203.input.log)
[1715534203.network.log](https://github.com/ppy/osu/files/15368543/1715534203.network.log)
[1715534203.performance.log](https://github.com/ppy/osu/files/15368548/1715534203.performance.log)
[1715534203.runtime.log](https://github.com/ppy/osu/files/15368549/1715534203.runtime.log)

**Comment by LJW21-GitHub** [comment]
Update : After restarting the game it's significantly less visible. Idk why...

**Comment by LJW21-GitHub** [comment]
Update : After restarting the game it's significantly less visible. Idk why...

**Comment by LJW21-GitHub** [comment]
Even more disturbing: I launched the game and directly tried the map with AP. The bug occurred and froze when the first notes appeared. I've tried with no fail and it didn't freeze, so I returned to AP and it didn't freeze this time...
Another experience : 3 times the same map with AP on each run
Results : freeze only the first time
Witness experience : 3 times the same map without mods
Results : Didn't freeze that much ? I'm pretty sure I've failed at least one map with this freeze...

**Comment by bdach** [comment]
this is https://github.com/ppy/osu/issues/22488 and either https://github.com/ppy/osu/issues/26879 or just low android performance
