### ISSUE TITLE
Skin editor glitches out when using big (scaled down) SkinnableSprite objects 

### ISSUE THREAD

**Issue by Cookiaria** [ppy/osu#28215]
### Type

Game behaviour

### Bug description

Skin editor glitches out when dragging a scaled down skinnable sprite object (when dragging an image in the osu window)

Steps to reproduce are in the video

### Screenshots or videos

https://github.com/ppy/osu/assets/67294862/c27ce0db-8734-4365-b4c7-754a762418c2

### Version

2024.519.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15368798/compressed-logs.zip)

**Comment by Cookiaria** [comment]
Still happening on hotfix (2024.519.1)

**Comment by bdach** [comment]
yes, the hotfix wasn't supposed to be fixing this.
