### ISSUE TITLE
Fullscreen and Windowed Mode issues on macOS

### ISSUE THREAD

**Issue by itsirfan05** [ppy/osu#28220]
### Type

Game behaviour

### Bug description

A few issues I've noticed after upgrading from 2024.412.1 to 2024.519.1:

- Command+Tab from Desktop or Application to osu! causes a noticeable, annoying delay.
- Switching from 'Fullscreen' to 'Windowed' causes graphical issues, and a temporary game freeze.
- At times (when tabbing into osu!), some areas of the screen are inaccessible.
- 'Revert to Default' button is pointless and the 'Fullscreen' disclaimer message is not required, as the 'Borderless' is no longer a setting.

These above issues were not present in the previous update (2024.412.1), as the 'Borderless' option worked flawlessly on macOS.

### Screenshots or videos

'Fullscreen' -> 'Windowed' graphical issue and 'Revert to Default' button:

https://github.com/ppy/osu/assets/90500019/1f1c8f81-beae-49b9-bd9f-7888fc103db9

Command+Tab to osu! and forced screen area:

https://github.com/ppy/osu/assets/90500019/d9b70000-cf4a-4716-bd97-98d4df4d2c19

Both are separate videos, as there is a file size limit

### Version

2024.519.0 & 2024.519.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15368900/compressed-logs.zip)

**Comment by bdach** [comment]
Let's track at https://github.com/ppy/osu/issues/28222
