### ISSUE TITLE
SDL3: "Disable Windows key during gameplay" doesn't work

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#28229]
### Type

Game behaviour

### Bug description

This is a known issue with SDL3 and the way raw input is handled on a separate thread. See https://github.com/libsdl-org/SDL/issues/9409.
This can be "fixed" by disabling raw/high precision mouse and keyboard, but that would be silly.

First reported in https://discord.com/channels/188630481301012481/1097318920991559880/1241678846953259029.

### Version

2024.519.1

### Logs

-

**Comment by Susko3** [comment]
The [workaround](https://stackoverflow.com/questions/13128692/wh-keyboard-ll-hook-doesnt-capture-input-in-own-process) linked in https://github.com/libsdl-org/SDL/issues/9409#issuecomment-2028899236 works. I have tested this by starting gameplay and then reloading an AutoHotkey script that installs a keyboard hook. The windows key remains blocked as long as the autohotkey hook is the latest installed hook. If our hook is reinstalled (eg. by pausing and resuming gameplay), then it breaks again.

We can implement this workaround by starting another process after installing our winkey blocker hook. In that process, it would be enough to just install a dummy hook that does nothing. The only thing that worries me is dangling child processes in case the game crashes, or if cleanup doesn't happen.

@ppy/team-client do we care about this feature enough to add a hacky workaround?

**Comment by bdach** [comment]
> We can implement this workaround by starting another process after installing our winkey blocker hook. In that process, it would be enough to just install a dummy hook that does nothing. The only thing that worries me is dangling child processes in case the game crashes, or if cleanup doesn't happen.

I would sooner remove the window key blocking feature than allow this to be merged.

That is *asinine*. That is the sort of windows hook hackery I would make fun of parsec for doing.

**Comment by Joehuu** [comment]
Seems fixed since https://github.com/ppy/osu/releases/tag/2024.718.1.
