### ISSUE TITLE
Continuation of gameplay after pausing doesn't make osu wait for player to place cursor in right place.

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2822]
Sorry if this is wanted effect, but

when you pause gameplay and after that you click 'continue', osu should wait until player places cursor in place where it was before pausing, but isn't waiting as stable is doing.

i'm thinking about this effect in stable:

![screenshot002](https://user-images.githubusercontent.com/32620809/41502868-32a17dc0-71c4-11e8-81a0-e4f005711099.jpg)
![screenshot001](https://user-images.githubusercontent.com/32620809/41502867-3274dd74-71c4-11e8-91d9-efbab9e05c74.jpg)

if it changes something, i'm using win 10 machine.

**Comment by peppy** [comment]
This is being worked on here: 
https://github.com/ppy/osu/pull/2061

**Comment by UselessToucan** [comment]
@peppy as far as I remember, #2061 is bad and should be reworked. Could you please provide the design and describe how it should be implemented?

**Comment by peppy** [comment]
To be honest I haven't properly reviewed it yet, but last time I did it had weird variable names, lots of cross-class pollution and also used reflection.

**Comment by ticotaco72** [comment]
resolved by #4529
