### ISSUE TITLE
Videos in maps do not expand to full screen after update

### ISSUE THREAD

**Issue by hiprivsid** [ppy/osu#28224]
### Type

Cosmetic

### Bug description

I updated today osu and found background video bug

### Screenshots or videos

before update
![image](https://github.com/ppy/osu/assets/75212472/9177355d-e863-426e-9837-e49a8032dfe4)

after update
![image](https://github.com/ppy/osu/assets/75212472/93d92dc9-7e9d-42c2-84fa-223c91afcb7f)

### Version

2024.519.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15369031/compressed-logs.zip)

**Comment by bdach** [comment]
This is intentional, see https://github.com/ppy/osu/issues/27634.
