### ISSUE TITLE
Spinners should always be behind other hit objects

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#2823]
Updated images from https://github.com/ppy/osu/issues/5450

**Screenshots or videos showing encountered issue:** 
![You can't see the hit circle, only the approach circle](https://user-images.githubusercontent.com/21059358/61833996-cbfa6900-ae3b-11e9-8104-82a799d1dbf0.png)
![With Hidden, the hit circle is completely invisible](https://user-images.githubusercontent.com/21059358/61834281-e5e87b80-ae3c-11e9-8c4a-0e68f68f4977.png)

**Comment by peppy** [comment]
This was actually an intentional choice while working on lazer. We may need to iterate on the design to make sure work, but for the time being I'm going to leave it this way.

Will leave this open to track the issue though.

**Comment by Joehuu** [comment]
Related to #2147. In https://github.com/ppy/osu/issues/5203#issuecomment-507256083 and https://github.com/ppy/osu/issues/2823#issuecomment-397874707, a design change (of lazer's skin) won't actually fix existing user skins.

I think only depth change to match stable is the only viable way.

**Comment by peppy** [comment]
We may be able to add a special case for legacy skins.
