### ISSUE TITLE
Dropped input on mania (android)

### ISSUE THREAD

**Issue by Wildthing0** [ppy/osu#28253]
### Type

Game behaviour

### Bug description

Mania drops keys when pressing many at once, hold notes carry previously pressed notes (I think 3 notes at once on touch breaks it)

### Screenshots or videos

https://github.com/ppy/osu/assets/90672169/81085b01-079b-41a9-88da-fce2870312c5

### Version

2024.519.0

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/28211
