### ISSUE TITLE
Pauses in maps sometimes causes the game to stop registering keyboard input

### ISSUE THREAD

**Issue by AyumiToshiyuki** [ppy/osu#28269]
### Type

Game behaviour

### Bug description

After a pause (the countdown in maps, not pressing escape) sometimes key input stop being registered until I fail

It's been doing this ever since yesterday's update, but I'm not sure what is causing it, since it doesn't seem to be consistent (sometimes it just works fine)

The bug occured on every map I tried (as long as they have a pause in them)

Also the inputs seem to be "kinda" registered by the game, because the input overlay counts them all at once when I failed, but not during a replay

[Video proof](https://youtu.be/754IbdY8V_4)

EDIT: I also tried with NoFail, and it seems like the amount of time when I can't press any circles is the same as the duration of the pause itself. 
Replay because I didn't record a video of this attempt: [replay_with_nofail.zip](https://github.com/ppy/osu/files/15381463/replay_with_nofail.zip)

### Version

Lazer 2024.519.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15381207/compressed-logs.zip)

**Comment by bdach** [comment]
I can't reproduce this the obvious way. I don't rule out this being some sdl-shaped failure.

@AyumiToshiyuki please check the newest hotfix (2024.521.2) and see if things improve

**Comment by AyumiToshiyuki** [comment]
I played for an hour on 2024.521.2 and the bug never occured, it seems fixed for now
