### ISSUE TITLE
SDL3: IME regressions

### ISSUE THREAD

**Issue by bdach** [ppy/osu#28261]
Should arguably only do the IME part.

### Discussed in https://github.com/ppy/osu/discussions/28162

<div type='discussions-op-text'>

<sup>Originally posted by **cdwcgt** May 12, 2024</sup>
![image](https://github.com/ppy/osu/assets/34775378/ed842066-d13d-4cf1-9c92-18d6dfbf3340)

also for beatmap search</div>

**Comment by bdach** [comment]
Seems like before https://github.com/ppy/osu-framework/pull/6234 we were able to suppress IME events from emitting SDL key down events and now we're not.

@Susko3 any bright ideas? other than scheduling (please god no)?

**Comment by bdach** [comment]
> With [ppy/osu-framework#5790](https://github.com/ppy/osu-framework/pull/5790) / [ppy/osu-framework@6fb7adc](https://github.com/ppy/osu-framework/commit/6fb7adc2a626fc9d923abe74fe6f7f50ddfbc67d) we could do it in a smarter way

I'm all for this but https://github.com/ppy/osu-framework/pull/6229 is a prerequisite for that pull is it not? That has unresolved reviews still.

**Comment by Susko3** [comment]
> Disabling SDL_HINT_WINDOWS_RAW_KEYBOARD works around the issue, but that increases keyboard latency by a tiny bit.

The hint is now [disabled by default](https://github.com/libsdl-org/SDL/commit/a9a51cebde21fb198abc661f1d57f48d40eb2327). There were other issues with raw keyboard, so the SDL3 folks decided to disable it.

Also, I'm unable to reproduce the original issue, even with envvar SDL_WINDOWS_RAW_KEYBOARD set to 1.
