### ISSUE TITLE
'Wacting' a replay sends you back to the 'Tutouial'.

### ISSUE THREAD

**Issue by PLGGitHub1** [ppy/osu#28264]
### Type

Game behaviour

### Bug description

Whyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

### Screenshots or videos

https://github.com/ppy/osu/assets/167148240/f7ebf6b7-60e2-4bac-889a-8d5f49aca126

### Version

Lazer 2024.159.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15378372/compressed-logs.zip)

**Comment by bdach** [comment]
This will be caused by the same thing as #28216

**Comment by PLGGitHub1** [comment]
> This will be caused by the same thing as #28216

:sob:

**Comment by bdach** [comment]
The fix for both of these issues is coming.
