### ISSUE TITLE
Osu lazer freezes inside of input settings

### ISSUE THREAD

**Issue by snowonster9000** [ppy/osu#28270]
### Type

Performance

### Bug description

I decided to put my tablet area into osu lazer and now every time I either go past the Input settings or into it my fps drops to 10 or the game freezes.

### Screenshots or videos

https://github.com/ppy/osu/assets/170374293/92723c1a-2e71-4bcd-943f-da3df6e63adf

### Version

2024.159.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15382233/compressed-logs.zip)

**Comment by bdach** [comment]
From the logs attached it appears like you had a skin & beatmap import going on in the background while you recorded this - was that the case?

**Comment by snowonster9000** [comment]
> From the logs attached it appears like you had a skin & beatmap import going on in the background while you recorded this - was that the case?

ohh i forgot i was doing that
