### ISSUE TITLE
Animated long notes start at frame 1 instead of 0

### ISSUE THREAD

**Issue by Luminatron** [ppy/osu#28284]
### Type

Game behaviour

### Bug description

I imported my skin to Lazer. It's jarring coz there's a stark contrast with the only 2 frames my animated long notes have, and the first frame is dark for very important reasons, so I can read LN spam charts and identify when I'm actually holding a long note.

### Screenshots or videos

![files](https://github.com/ppy/osu/assets/46986218/42ca6f79-5775-4c21-8329-39686cf64cf9)
![oldbehaviour](https://github.com/ppy/osu/assets/46986218/20354c8d-7578-4771-b5d0-d9e9e977dacb)
![newbehaviour](https://github.com/ppy/osu/assets/46986218/b8f63581-f6b4-42df-9266-2a247fbd2150)

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15397807/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Please provide the skin.

**Comment by Luminatron** [comment]
Dropbox (I hit the 25mb limit uploading here) https://www.dropbox.com/scl/fi/xpgt98oegqtqjh4p0iiqx/Aesthetic-VOEZ-CodeName-Bloo.osk?rlkey=9rd8n99xq45uby9smccefog9l&st=2yqltymf&dl=0

**Comment by bdach** [comment]
@Luminatron Did you encounter this in normal gameplay? The only scenario where I can make this happen is rewinding (which is still an issue, but I just wanna make sure I'm not missing anything).

**Comment by Luminatron** [comment]
Just normal gameplay.
