### ISSUE TITLE
Cursor skipping + delay for taiko

### ISSUE THREAD

**Issue by bozzis** [ppy/osu#28319]
### Type

Performance

### Bug description

The game is unplayable because every second the cursor is skipping.
And for taiko, the game mode I play, it's unplayable because the keys don't register for like 2-3 seconds and then they play all at once after not registering for the previous 2 seconds.
This was not happening last week, not sure what changed since then. I didn't change anything on my PC.
Osu stable is working normally.

### Screenshots or videos

https://github.com/ppy/osu/assets/24719518/662100ee-a3b8-4c9e-9442-7286d6a28160

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15447090/compressed-logs.zip)

**Comment by BlockHead007** [comment]
Probably #27227

**Comment by bdach** [comment]
Probably. Tentatively closing as duplicate.
