### ISSUE TITLE
Cinema mod does not hide playfield skin elements

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#28321]
### Type

Game behaviour

### Bug description

Skin elements on the playfield layer are shown when the Cinema mod is turned on.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/43639171/36061388-e880-432e-a76a-c5117c3c3b69)

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15447450/compressed-logs.zip)

**Comment by peppy** [comment]
Very cool skin btw
