### ISSUE TITLE
Osu launching the wrong song

### ISSUE THREAD

**Issue by Owexiii13** [ppy/osu#28324]
### Type

Game behaviour

### Bug description

The bug i am encountering is osu launching the wonrg beatmap when i click play I don't know how to replicate this bug I have no screenshots of it but I will try to screen record it happening I have closed the game after it happend so I don't have the logs

### Version

Intel Lazer 2024.521.2

### Logs

I didn't download the logs

**Comment by PLGGitHub1** [comment]
i cant understand what your talking about. 'mabey' you changed the song playing in the player?
adding a video may make more sense

**Comment by bdach** [comment]
There is no information in this issue report that would allow to even begin investigating. Closing until *anything* relevant is provided.
