### ISSUE TITLE
Conflict popup in mania input key binding

### ISSUE THREAD

**Issue by DaiterGG** [ppy/osu#28325]
### Type

Game behaviour

### Bug description

I have to rebind my layouts frequently. I can create a conflict within a keymod while rebinding and the game will wait for your input, defeating the purpose of the quick mania rebind. I can also trigger several times in a row depending on layout.
It should unbind the conflicting bind without a popup or at least not prevent you from binding further.

### Screenshots or videos

![Screenshot_6](https://github.com/ppy/osu/assets/64665908/bb8d16d3-cab1-46c7-9f9a-556697744f49)

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15449231/compressed-logs.zip)

**Comment by PLGGitHub1** [comment]
sorry, its not a bug. 'maby' you were imputing the same keys

**Comment by bdach** [comment]
https://github.com/ppy/osu/discussions/25639

You can press enter after each binding conflict to confirm overwrite. Note that this will clear any conflicting bindings.
