### ISSUE TITLE
FC Sudden Death, but the replay had a miss error

### ISSUE THREAD

**Issue by hachuyenden** [ppy/osu#28340]
### Type

Game behaviour

### Bug description

This is a replay: https://osu.ppy.sh/scores/2901700065
This is a clip:
https://m.youtube.com/watch?v=dhGQ9FwFBiA. ( 1m33s )
This is a specific comparison between liveplay and replay:

https://github.com/ppy/osu/assets/128424762/aab1d9ae-9875-4771-895f-b418997fa403

I don't know the reason, maybe the mod I'm playing.

### Version

2024.521.2 Latest version

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15471502/compressed-logs.zip)

**Comment by longnguyen2004** [comment]
Can't find a related issue, but it's well known that there are replay accuracy issues

**Comment by BlockHead007** [comment]
#23709 ?

**Comment by smoogipoo** [comment]
Duplicate, as above.

**Comment by ssz7-ch2** [comment]
I think this should be kept as a separate issue since afaik, it's the only example where a circle is hit in gameplay but shows a miss in the replay

**Comment by hachuyenden** [comment]
> I think this should be kept as a separate issue since afaik, it's the only example where a circle is hit in gameplay but shows a miss in the replay

As @BlockHead007 mentioned in #23709, when I looked at #23709 and thought that maybe the playback rounded the milliseconds on touch to an integer, that resulted in me getting slippage during playback. It is also good to be able to close this case properly to limit the workload as this has also been mentioned. However, knowing the reason clearly, I'm not too negative.
