### ISSUE TITLE
Unexpected HP restoration and lag spikes when using EZ

### ISSUE THREAD

**Issue by ethan-davies** [ppy/osu#28351]
### Type

Game behaviour

### Bug description

Upon playing any map of any difficulty using the Easy mod, I encounter random lag spikes/freezing, when looking at my FPS counter I do not see any frame drops except for maybe the few 1-3 frames. Along with this, the healthbar at the top seems to regenerate. This healthbar "regeneration" seems to occur a consistent 3 times per map. Usually near the start. I have tried all FPS limiting options but that doesnt seem to affect it. Also, it should be noted that this only occurs once the player starts to miss notes.

### Screenshots or videos

https://github.com/ppy/osu/assets/80976096/7013c036-1b47-45ab-9e45-cda8b3402d23

### Version

Stable 20240513.1

### Logs

As I am on stable I just zipped my `osu!\Logs` folder: [logs.zip](https://github.com/ppy/osu/files/15486872/logs.zip)

**Comment by Zerfax** [comment]
With the Easy mod, you get 3 "extra lives" when you would otherwise fail. The game pauses for a brief moment, and some amount of health is restored. This behavior is normal.

**Comment by peppy** [comment]
Probably needs to be better conveyed visually. It really does look like a bug at the moment.

From recollection stable would more gracefully increase the hp bar back to full (and the red fail tint would fade out)

**Comment by smoogipoo** [comment]
Note that the video above is stable/issue is for stable.

**Comment by peppy** [comment]
🙈
