### ISSUE TITLE
Cursor behaviour in the end of text on searchbox texts

### ISSUE THREAD

**Issue by FeellsBadSkillz** [ppy/osu#28372]
### Type

Cosmetic

### Bug description

I think it's related to Issue #21280 ,

By using the apple pencil and bring it up the keyboard on screen and use the keyboard, 
the cursor goes in the end but writes at the start making a massive space in between.

System info:
iPad Pro 3rd gen (11 inch)
Apple Pencil USB-C
iPadOS 17.5.1

![IMG_0003](https://github.com/ppy/osu/assets/57463038/3c473c25-9d84-4a13-8b12-d336346f1769)

How to reproduce this issue:

You need to use only the Apple pencil, no touch 
(By using the normal touch on any part of the steps, it doesn't do this strange behaviour)

1.  Fully close osu!lazer
2.  Open it up
3.  Go on one of the search box (Beatmap search, Settings Search, Chat msgs)
4.  Click on the search box
5.  Bring up the keyboard on screen
6.  And use the keyboard on screen

Massive space in between

### Screenshots or videos

I did manage to get two different angles:

From Ipad view:

https://youtu.be/hd5-jZf0njc

Liveview:

https://youtu.be/pb68e-XZ3Ok

### Version

2024.521.2-lazer

### Logs

[logs_iPadOs.zip](https://github.com/user-attachments/files/15521091/logs_iPadOs.zip)

**Comment by frenzibyte** [comment]
I cannot reproduce this, and I was not able to write into any text box with a floating keyboard anyway. With https://github.com/libsdl-org/SDL/pull/11406 however, I can write correctly and I do not see any presence of those spaces being inserted in text.
