### ISSUE TITLE
Mouseclick + F10 = Crash

### ISSUE THREAD

**Issue by estorio** [ppy/osu#2840]
When i hold Leftclick while playing and toggle off the mouse buttons via F10 the game crashes. It happens everytime.
This is just here to report this bugs, since i am not able to do it via the launcher.
I hope this will be patched sometime in the future, i know there is more important stuff to do

**Comment by LittleEndu** [comment]
[runtime.log](https://github.com/ppy/osu/files/2115788/runtime.log) of the issue

**Comment by estorio** [comment]
https://gist.github.com/estorio/78dd154d65129a97688d9d0370068aa7
This is the runtime.txt of mine.

**Comment by FreezyLemon** [comment]
Is this still reproducible? I just tried it on the latest master, and couldn't get it to crash.

**Comment by ekrctb** [comment]
This is not reproducible right now due to #2868. The solution of this issue should close this issue as well.
