### ISSUE TITLE
Total score in playlist leaderboard does not convert into classic scoring

### ISSUE THREAD

**Issue by ominoussage** [ppy/osu#28411]
### Type

Cosmetic

### Bug description

I noticed that switching the score display mode to "Classic" does not change the values in the playlist leaderboard scores even though when trying to switch the score display mode to "Classic" while in the results screen, the values change appropriately.

### Screenshots or videos

https://github.com/ppy/osu/assets/105097625/5075d90f-eb58-4b14-bec2-4e94548c28d8

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15605439/compressed-logs.zip)

**Comment by bdach** [comment]
This is somewhat intentional. See https://github.com/ppy/osu/issues/17824.
