### ISSUE TITLE
Bugs 

### ISSUE THREAD

**Issue by Azilux** [ppy/osu#28419]
### Type

Crash to desktop

### Bug description

Recently I've been collecting this errors like they are damn pokemon. On the recent update it would go telling me to update my game even though I'm up to date which means non of my scores were submitted. And the game signed me out a whopping 16 times. And no it's not my internet it is the crappy lazer bug fixing.

### Screenshots or videos

![Uploading Screenshot 2024-06-06 185030.png…]()
![Screenshot 2024-06-06 184713](https://github.com/ppy/osu/assets/172005880/1154ecdd-f84d-443d-9136-fbc5387a1003)
![Screenshot 2024-06-06 183936](https://github.com/ppy/osu/assets/172005880/da6abb8d-f3e1-482e-b452-0544d44c0fad)
![Screenshot 2024-06-06 184411](https://github.com/ppy/osu/assets/172005880/79113a25-a673-41c0-bf90-1d74f39025a9)

![Uploading Screenshot 2024-06-06 184233.png…]()
![Screenshot 2024-06-06 183915](https://github.com/ppy/osu/assets/172005880/14da5f9e-d382-410f-b7c5-8254a7cdc06e)
![Uploading Screenshot 2024-06-06 183656.png…]()
![Uploading Screenshot 2024-06-06 183901.png…]()
![Uploading Screenshot 2024-06-06 183322.png…]()
![Uploading Screenshot 2024-06-06 183420.png…]()
![Screenshot 2024-06-06 183650](https://github.com/ppy/osu/assets/172005880/718b5024-b3b4-4cc6-8de4-7b1165867e9f)

### Version

Lazer 521.2

### Logs

I can't access them and my laptop is unavailable and on android I can't access them either.

**Comment by bdach** [comment]
This looks like connection issues but without logs I can't say more. Not enough information to keep this report open.
