### ISSUE TITLE
[MacOS] Sounds are very broken when in full screen (or maximized) with "game mode" on

### ISSUE THREAD

**Issue by MuresanSergiu** [ppy/osu#28415]
### Type

Game behaviour

### Bug description

Basically title. I also notice a lot more lag than without this "game mode" being on

### Screenshots or videos

https://github.com/ppy/osu/assets/5781599/3f6459ad-89e9-4017-9c8e-8f68f246eb49

### Version

Lazer 2024.521.2 and MacOS Sonoma 14.4

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15686737/compressed-logs.zip)

**Comment by longnguyen2004** [comment]
#27669
