### ISSUE TITLE
Offline names on stable link to actual profiles on Lazer

### ISSUE THREAD

**Issue by emxlo** [ppy/osu#28414]
### Type

Replays issue

### Bug description

I was looking at some replays on Lazer and i noticed that a play that i made offline on standard now had a profile pic, so i checked it and it linked to some canadian guy i never knew existed??
This play is not on his profile
My profile : https://osu.ppy.sh/users/15073898
This guy's profile : https://osu.ppy.sh/users/1825762

### Screenshots or videos

![screenshot006](https://github.com/ppy/osu/assets/119593265/eaedb123-b150-4aa7-a4b4-a5077e1c0e2e)
![osu_2024-06-06_21-13-47](https://github.com/ppy/osu/assets/119593265/e95bd846-1588-4d36-8e26-bec39d8fe4a1)
![osu_2024-06-06_21-14-00](https://github.com/ppy/osu/assets/119593265/6af6e4e2-a09d-4503-93a2-5d2b393bc38f)

I also recreated later like this example : 

![osu_2024-06-06_21-41-15](https://github.com/ppy/osu/assets/119593265/19727431-f6c7-4291-b31e-48bcdc14c722)
![osu_2024-06-06_21-41-19](https://github.com/ppy/osu/assets/119593265/106a40e2-350e-45ac-9660-6e645fc953b5)

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15683853/compressed-logs.zip)

**Comment by BlockHead007** [comment]
Probably #24624

**Comment by bdach** [comment]
This was fixed but not retroactively (as in replays imported before the fix will not have been fixed).

Unless the replay was imported after the latest update this is a wontfix. The fix would be to delete and reimport the replay(s) in question.
