### ISSUE TITLE
connection bug

### ISSUE THREAD

**Issue by Azilux** [ppy/osu#28426]
### Type

Crash to desktop

### Bug description

my connection is completely stable, i have been through this for the past week after exactly 2 hours all of the bugs "MaKE sURe tO UpdATE yoUr GaMe TO tHE nEWeST VerSiOn" and all those other very annoying bugs.

### Screenshots or videos

![Screenshot 2024-06-06 183322](https://github.com/ppy/osu/assets/172005880/879ece21-fa7b-4e45-b217-0eb4410d63f4)
![Screenshot 2024-06-06 183420](https://github.com/ppy/osu/assets/172005880/cb7a085c-c121-4a71-818b-ebbdb857ab53)
![Screenshot 2024-06-06 183650](https://github.com/ppy/osu/assets/172005880/97f0e689-f4ab-4585-a11d-5da123f77f9b)
![Screenshot 2024-06-06 183656](https://github.com/ppy/osu/assets/172005880/618eeaf9-0a11-4a1f-9581-b2f90819e849)
![Screenshot 2024-06-06 183901](https://github.com/ppy/osu/assets/172005880/4d04cc0f-9f7f-4e91-884c-d28be947fb77)
![Screenshot 2024-06-06 183936](https://github.com/ppy/osu/assets/172005880/197a1f75-9dbc-4438-98bb-944ff9e20a0e)
![Screenshot 2024-06-06 184224](https://github.com/ppy/osu/assets/172005880/774d580e-bdbe-4282-9f0c-2606f363067f)
![Screenshot 2024-06-06 184233](https://github.com/ppy/osu/assets/172005880/5a3b89f9-58ab-42be-a79b-0c49db920881)
![Screenshot 2024-06-06 184411](https://github.com/ppy/osu/assets/172005880/1d9b4856-c69f-4393-884c-03d11e3e93a5)
![Screenshot 2024-06-06 184713](https://github.com/ppy/osu/assets/172005880/27addcc4-6d3c-41d6-bfae-18b728cef5f3)
![Screenshot 2024-06-07 183422](https://github.com/ppy/osu/assets/172005880/36f7b04d-91a8-4621-8ce5-cc1c1b2f1e91)
![Screenshot 2024-06-07 190154](https://github.com/ppy/osu/assets/172005880/34ae2955-8eb7-4a87-839f-fcca8349ff3f)
![Screenshot 2024-06-07 190429](https://github.com/ppy/osu/assets/172005880/fac3f284-3b5a-4d05-94e8-3eaad168293c)
![Screenshot 2024-06-07 190721](https://github.com/ppy/osu/assets/172005880/8cc2d3a4-8a93-426a-a853-e05cdeb35d43)

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15743717/compressed-logs.zip)

**Comment by Azilux** [comment]
and i also cant sign in too, way to make things worse

**Comment by bdach** [comment]
Currently the website is experiencing heavy load. Nothing to do with the game. Mitigations are in progress.
