### ISSUE TITLE
Slider head circle textures are size constrained and may not render completely

### ISSUE THREAD

**Issue by vicky5124** [ppy/osu#28422]
### Type

Cosmetic

### Bug description

When a `sliderstartcircle` skin element is (approximately) over twice as big as the circle size, the texture gets cut out in a square pattern, which is not only ugly and distracting, but it's also a miss-match between the behaviour in stable.

The map used in the screenshots is [Tenacious D - BEELZEBOSS (THE FINAL SHOWDOWN)](https://osu.ppy.sh/beatmapsets/593032), but the bug is reproducible in any map, with any CS (from 0 to 11), in gameplay, the map editor, and the skin editor.

Note that this issue may exist in other skin elements such as `hitcircle`, but I did not test for this because modifying skin elements in lazer is annoying, unergonomic, and there's no way to identify different versions of the skin in the list without changing the skin name in the skin.ini file on every modification.

### Screenshots or videos

osu!lazer sceenshots showing the bug in gameplay and the editor:
![osu_2024-06-07_11-25-20](https://github.com/ppy/osu/assets/8344197/e87ad1a1-0c1f-428e-9936-24d2b26e2bf7)
![osu_2024-06-07_11-25-23](https://github.com/ppy/osu/assets/8344197/9bb7fdc9-6445-4c59-9adc-7dfa0e3b6040)
![osu_2024-06-07_12-48-34](https://github.com/ppy/osu/assets/8344197/18eb5d25-4682-4aab-b79a-3ca68dacc7f4)

osu!stable showing the intended look.
![screenshot002](https://github.com/ppy/osu/assets/8344197/a5d54c52-dd33-40c4-b61e-e75652360c2f)
![screenshot004](https://github.com/ppy/osu/assets/8344197/c82257be-1548-4ad2-87ed-8c84998befe9)

The skin elements used. Taken from `boom 0524 edit (spro_-GN).osk`
![sliderstartcircle@2x](https://github.com/ppy/osu/assets/8344197/1d943d7e-376b-47d7-92dc-a980699424cb)
![sliderstartcircleoverlay@2x](https://github.com/ppy/osu/assets/8344197/42798093-09e7-4db8-8baa-f08a36ad07b4)

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15738075/compressed-logs.zip)

**Comment by bdach** [comment]
This is an intentional departure from stable. Please read https://github.com/ppy/osu/pull/25023 for context.
