### ISSUE TITLE
Taiko finisher sound activates when there is no finisher

### ISSUE THREAD

**Issue by HexaMaster** [ppy/osu#28429]
### Type

Game behaviour

### Bug description

When two non-finisher circles of the same color are hit close together, the finisher sound plays when it is not supposed to. Having two notes of the same color placed close together is intended to represent a different kind of sound in the song, so having the finisher sound play disrupts the flow of the beatmap.

### Screenshots or videos

https://github.com/ppy/osu/assets/103844030/a428e5fb-c650-4a40-9179-66e76d506696

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15747725/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/discussions/25026
