### ISSUE TITLE
Game say i am not on right version when i am on latest

### ISSUE THREAD

**Issue by TobyJ-B** [ppy/osu#28435]
### Type

Game behaviour

### Bug description

Game says score will not be uploaded as i am not on latest version when i clearly am.

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15753265/compressed-logs.zip)

**Comment by BlockHead007** [comment]
Been reported many times
#27652, #27290, #28197

**Comment by smoogipoo** [comment]
You're using a non-official package. For the AUR make sure you're using https://aur.archlinux.org/packages/osu-lazer-bin and not https://aur.archlinux.org/packages/osu-lazer
