### ISSUE TITLE
Spinners (bursts) do not fade properly

### ISSUE THREAD

**Issue by HexaMaster** [ppy/osu#28430]
### Type

Cosmetic

### Bug description

In osu!stable, spinners in osu!taiko fade in about one second or so before the player interacts with them, so on occasion, mappers will set a spinner's SV speed to a very low number (such as 0.01) so that the spinner fades in directly on the player. However, in osu!lazer, spinners appear from the right of the screen like any other object, which means that low SV spinners can be on the screen for multiple minutes, heavily distracting from gameplay and the author's intended experience. This can be seen in multiple ranked maps. 

Shown below are instances of this occurring in One of Us, mapped by X a v y, and 《/nttld.:beings》~Truth in Uncertainty~, mapped by Hivie. Both are ranked maps.

### Screenshots or videos

https://github.com/ppy/osu/assets/103844030/534f71f6-5757-4e63-a992-c1a662400e40

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15748017/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21769
