### ISSUE TITLE
osu autopilot doesn't sync with notes in some songs when using the half time mod

### ISSUE THREAD

**Issue by Pacuwu** [ppy/osu#28449]
### Type

Other

### Bug description

When I use halftime and autopilot, it doesn't sync with the notes and makes me crash and die on Android

### Version

2024.521.2

### Logs

It's just a problem with one of the osu mods, it has nothing to do with the game logs

**Comment by shiumano** [comment]
Unrelated but interrupting.
Perhaps,
+ Attach screen recording if possible.
+ Which map it occurs on.
+ If crashing, attach logs

I think the solution will be smoother if you do

**Comment by Pacuwu** [comment]
> Unrelated but interrupting. Perhaps,
> 
> * Attach screen recording if possible.
> * Which map it occurs on.
> * If crashing, attach logs. (Is a crash a stoppage of the application?)
> 
> I think the solution will be smoother if you do

It does not require logs since it is a bug in the game, and it happens on maps like Yobikomi Kun and Centipede
