### ISSUE TITLE
Perfect curve algorithm differs slightly from osu!stable

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#2844]
osu!stable (equivalent):
```
amountPoints = (int)(thetaRange * r * 0.125f);

List<Vector2> output = new List<Vector2>(amountPoints);

for (int i = 0; i < amountPoints; ++i)
{
    double fract = (double)i / amountPoints;
    double theta = thetaStart + dir * fract * thetaRange;
    Vector2 o = new Vector2((float)Math.Cos(theta), (float)Math.Sin(theta)) * r;
    output.Add(centre + o);
}

output.Add(c);
```

Current osu!lazer:
```
amountPoints = 2 * r <= tolerance ? 2 : Math.Max(2, (int)Math.Ceiling(thetaRange / (2 * Math.Acos(1 - tolerance / r))));

List<Vector2> output = new List<Vector2>(amountPoints);

for (int i = 0; i < amountPoints; ++i)
{
    double fract = (double)i / (amountPoints - 1);
    double theta = thetaStart + dir * fract * thetaRange;
    Vector2 o = new Vector2((float)Math.Cos(theta), (float)Math.Sin(theta)) * r;
    output.Add(centre + o);
}
```

Discussed earlier today, the proposed solution is having a `LegacySliderCurve` attached to `ConvertSlider`, which is then passed to the converted hit objects.

I also wanna know @Tom94 's thoughts since he was the one that implemented osu!lazer's algorithm this way - whether osu!lazer's algo is indeed correct.

**Comment by Tom94** [comment]
That change was conscious. Stable would put the same amount of points regardless of the radius of the perfect slider, resulting in visible kinks on small perfect sliders.

The lazer implementation picks the number of points such that the curvature per-kink is below some tolerance that leads to them being invisible.

This leads to very slight length differences but is for the better, imho.

I'm not sure I like `LegacySliderCurve`. If we really want maximum compatibility, then sure, but do we? Does this change many converts?

**Comment by smoogipoo** [comment]
Closing as the effect of this is very minor and bordering on the edge of not being detectable.
