### ISSUE TITLE
Audio playback rate becomes non-realtime on some systems

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2845]
When I left the game open, but didn't do anything, after some time music got crashed. It didn't play or was too fast. Playing was'nt possible too. I've left it for next few minutes and it started playing normally.

I think it could be something with time.

Logs:
[database.log](https://github.com/ppy/osu/files/2119586/database.log)
[network.log](https://github.com/ppy/osu/files/2119587/network.log)
[performance.log](https://github.com/ppy/osu/files/2119588/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2119589/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2119590/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2119591/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2119592/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2119593/runtime.log)

Windows 10 on my machine, if it changes anything.

**Comment by ticotaco72** [comment]
[database.log](https://github.com/ppy/osu/files/2134324/database.log)
[network.log](https://github.com/ppy/osu/files/2134325/network.log)
[performance.log](https://github.com/ppy/osu/files/2134326/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2134327/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2134328/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2134329/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2134330/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2134331/runtime.log)

osu! gets some way slow when this bug is occuring
that bug isn't occuring everytime when above situation is occuring

**Comment by ticotaco72** [comment]
[database.log](https://github.com/ppy/osu/files/2134837/database.log)
[network.log](https://github.com/ppy/osu/files/2134838/network.log)
[performance.log](https://github.com/ppy/osu/files/2134839/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2134840/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2134841/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2134842/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2134843/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2134844/runtime.log)


bug occurs after 20 or more minutes of running in background

video:
https://drive.google.com/file/d/1x53qrhYg2q6QHTxnPYt_20_5qARiCaiL/view?usp=sharing

3 minutes after end of recording music started playing normally.
if it changes something, it was staying this 3 minutes quiet.

[database.log](https://github.com/ppy/osu/files/2134861/database.log)
[network.log](https://github.com/ppy/osu/files/2134862/network.log)
[performance.log](https://github.com/ppy/osu/files/2134863/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2134864/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2134865/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2134866/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2134867/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2134868/runtime.log)

**Comment by ticotaco72** [comment]
that bug is only about songs, interface sounds work nice

**Comment by ticotaco72** [comment]
[database.log](https://github.com/ppy/osu/files/2215629/database.log)
[network.log](https://github.com/ppy/osu/files/2215630/network.log)
[performance.log](https://github.com/ppy/osu/files/2215631/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2215632/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2215633/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2215634/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2215635/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2215636/runtime.log)

what is strange, that when closing osu! bug disapeared when this last black circle appeared

**Comment by peppy** [comment]
Actually saw this happen recently. It was game-wide for all audio tracks (ie. changing beatmap did not fix it, and required a full restart to resolve) and may be an issue with how we are consuing or passing data to bass (could be related to the `AsyncBufferStream` / `DataStreamFileProcedures` code).

**Comment by peppy** [comment]
Haven't seen any reports of this in recent times, so am going to close for the time being. Please comment on this issue if you are still experiencing it.
