### ISSUE TITLE
Long notes can look broken on other skins rather than osu!lazer skins if using Inverse mod in osu!mania

### ISSUE THREAD

**Issue by serobor** [ppy/osu#28459]
### Type

Game behaviour

### Bug description

I used Inverse mod while playing osu!mania.
And noticed that some long note looked broken.
I wanted to report that and decided to use lazer agron skin to watch replay and find that LN.
But surprisingly, LN looked normal than on skin I was playing with.

### Screenshots or videos

![osu_2024-06-12_20-18-02](https://github.com/ppy/osu/assets/16684745/203aa8e8-1dca-4248-b263-7c7f5306c1b1)
![osu_2024-06-12_20-21-35](https://github.com/ppy/osu/assets/16684745/cdb22bd3-d339-447a-8525-e024ed0aca78)

https://github.com/ppy/osu/assets/16684745/26cb9f2a-154f-482e-9a19-58cbd86223fc

[beatmap and replay.zip](https://github.com/user-attachments/files/15807624/beatmap.and.replay.zip)

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15807603/compressed-logs.zip)

**Comment by smoogipoo** [comment]
There's actually some more weirdness around that area, like this random black cutoff towards the bottom:

<img width="536" alt="image" src="https://github.com/ppy/osu/assets/1329837/1b896d83-fef3-437d-bc7a-db1874a3c55e">

Will look into this one
