### ISSUE TITLE
Black Screen and Crashes on startup

### ISSUE THREAD

**Issue by KittoniuM** [ppy/osu#2846]
using a Thinkpad X220T with Intel Integrated Graphics 3000, running windows 10 enterprise ltsb 2016 with all the latest updates, 8gb ram, intel i5-2520m.

start the game, it spawns a window, its fully black for about 5 seconds then it crashes.

log files that i could find:
https://i.imgur.com/D7Jbygp.png

crash:
https://i.imgur.com/pS5JLUJ.png

fix pls :D?

**Comment by peppy** [comment]
This looks to be an issue with your drivers not correctly supporting OpenGL. I'd attempt to install the latest versions from intel's website and see if that helps.

Also could you please attach the log files rather than a screenshot of the log files?

**Comment by jvyden420** [comment]
After researching, it looks like your system is perfectly capable of running lazer. You just need to update your GPU Drivers, as peppy said. Your drivers can only run OpenGL 1.1, while the game requires OpenGL ES 2.0.
After further research, it looks like your operating system is too new for the GPU, so you have two choices:
Downgrade your OS
Get a better GPU

**Comment by KittoniuM** [comment]
:) I upgraded to win 7 enterprise, issue seems to be fixed.

windows 10 is like rubbing poop in your face
