### ISSUE TITLE
Changing mode after playing osu!mania with nonstandard number of keys crashes game

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2847]
Played osu!mania with different number of keys, and changed mode to osu!. Game freezed for few seconds and crashed.

It does the same with other game modes.

logs:
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2121212/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2121213/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2121214/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2121215/runtime.log)
[database.log](https://github.com/ppy/osu/files/2121216/database.log)
[network.log](https://github.com/ppy/osu/files/2121217/network.log)
[performance.log](https://github.com/ppy/osu/files/2121218/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2121219/performance-gamethread.audio.log)

Playing on win 10 if it changes anything.

**Comment by peppy** [comment]
This looks like a pretty serious oversight in bindables

**Comment by ticotaco72** [comment]
Problem still exists for me
logs:
[database.log](https://github.com/ppy/osu/files/2153245/database.log)
[network.log](https://github.com/ppy/osu/files/2153246/network.log)
[performance.log](https://github.com/ppy/osu/files/2153247/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2153248/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2153249/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2153250/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2153251/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2153252/runtime.log)

**Comment by ticotaco72** [comment]
''01.07.2018 21:46:35: fatal error:
01.07.2018 21:46:35: System.InvalidCastException: Nie można rzutować obiektu typu 'osu.Game.Rulesets.Osu.Beatmaps.OsuBeatmapConverter' na typ 'osu.Game.Rulesets.Mania.Beatmaps.ManiaBeatmapConverter'.
01.07.2018 21:46:35: w osu.Game.Rulesets.Mania.Mods.ManiaKeyMod.ApplyToBeatmapConverter(IBeatmapConverter beatmapConverter)
01.07.2018 21:46:35: w osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(RulesetInfo ruleset)
01.07.2018 21:46:35: w osu.Game.Screens.Select.BeatmapInfoWedge.BufferedWedgeInfo.getInfoLabels()
01.07.2018 21:46:35: w osu.Game.Screens.Select.BeatmapInfoWedge.BufferedWedgeInfo.load(LocalisationEngine localisation)
01.07.2018 21:46:35: 
01.07.2018 21:46:35: ''

**Comment by smoogipoo** [comment]
There hasn't been a new release yet, please wait.

**Comment by peppy** [comment]
Can you take a video of how you are still making this fail? I can't seem to locally.

**Comment by ticotaco72** [comment]
[database.log](https://github.com/ppy/osu/files/2156600/database.log)
[network.log](https://github.com/ppy/osu/files/2156601/network.log)
[performance.log](https://github.com/ppy/osu/files/2156602/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2156603/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2156604/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2156605/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2156606/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2156607/runtime.log)

version 2018.701.0

does the same with 2018.702.0


https://drive.google.com/open?id=12IR6fxKaU_RcknbySGQke7bo4o-vrMoQ

**Comment by ticotaco72** [comment]
after deselecting all mods problem disappears

**Comment by ticotaco72** [comment]
maybe it is connected with thing that only mania have usable mods that aren't in other modes
just deselect not possible to open in osu! for example, same in future with autopilot and relax

**Comment by peppy** [comment]
Have reproduced a lingering issue and am working on a fix.

**Comment by Lolihunter1337** [comment]
is #2788 related to it?

**Comment by peppy** [comment]
Yes, looks like a duplicate.
