### ISSUE TITLE
"Please ensure you are using the latest version of the official game releases." Error when using most recent version.

### ISSUE THREAD

**Issue by Toasterly** [ppy/osu#28483]
### Type

Game behaviour

### Bug description

This started happening after I clicked update on a map and played that same map while it was importing. I do not have a clip and cannot recreate because it still appears after restarting osu, I can no longer play online.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/37195727/e8d115b0-96b5-4dc9-80bb-c4369eea5e54)

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15839519/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Is there a `.require_update` file in `%APPDATA%/osu`?

**Comment by Toasterly** [comment]
![image](https://github.com/ppy/osu/assets/37195727/171106dc-56d6-4718-bda2-45daea355ff7)
It does not.

**Comment by smoogipoo** [comment]
Can you upload that `.auth_startup` file too?

**Comment by Toasterly** [comment]
Can't upload, but the content is only
"
log started
auth loaded
"

**Comment by smoogipoo** [comment]
Have you tried restarting your PC? Other users report that it's fixed it for them. We're unsure why this is happening at the current moment...

**Comment by Toasterly** [comment]
Restarting fixed the issue.

**Comment by smoogipoo** [comment]
That's super weird. A few more questions then:
- From your logs, it looks like the last time that any scores were submitted successfully was 4 startups ago on `2024-06-13 21:09:31` UTC time. Since then, have you installed any Windows updates? In the restart you just did, did you have to wait for any updates to install?
- Please re-export and upload the logs again.

**Comment by Toasterly** [comment]
[compressed-logs.zip](https://github.com/user-attachments/files/15841798/compressed-logs.zip)
Last night I updated windows to shutdown without a full restart afterwards. 
Did not have to update anything on restart that fixed the issue.

**Comment by smoogipoo** [comment]
Thanks. I'll close this issue for now since there's nothing much else to do here.
