### ISSUE TITLE
Can't import file beatmap

### ISSUE THREAD

**Issue by Baduull** [ppy/osu#28495]
### Type

Other

### Bug description

Version Android Q(10)

### Screenshots or videos

.

### Version

2024.521.2-lazer

### Logs

.

**Comment by BlockHead007** [comment]
So... what's the issue? Why you can't? What you tried to do it?

**Comment by Stoppedpuma** [comment]
Might be #11911, please provide logs by doing the following: "On Android, navigate to Android/data/sh.ppy.osulazer/files/logs using a file browser app."

**Comment by bdach** [comment]
I'm just gonna close this outright because the report is so low effort that I don't think it's worth having this open even with "missing details". And odds are it's one of the issues with android storage support that we're already aware of.
