### ISSUE TITLE
Runtime: "Please ensure you are using the latest version of the official game releases." bug after I downloaded lazer 15 minutes ago

### ISSUE THREAD

**Issue by kanseiyume** [ppy/osu#28502]
### Type

Game behaviour

### Bug description

I've been having this problem for the past few days, and I've completely uninstalled and reinstalled both stable and lazer, yet this error has persisted over the (now) three times I've completely deleted all of the osu! files (as in, %appdata%/Local and the other normal lazer installation locations). I've looked around the filesystems for the .dll's that have been listed in other threads that I "should delete and it'll fix my problems", but either I've been unable to find them or deleting them does nothing. I've blocked and unblocked the realm, turned my PC off and back on again, gone through all the hoops over and over only for this same ranking error to reappear each and every time.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/70236472/2759f111-f17c-4e84-a2f5-42ffe3d562eb)

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15859929/compressed-logs.zip)

**Comment by Stoppedpuma** [comment]
Two things stick out to me, one is a permission error and the other is network:

`2024-06-16 21:26:35 [verbose]: Failing request osu.Game.Online.API.Requests.DownloadBeatmapSetRequest (System.UnauthorizedAccessException: Access to the path 'C:\Users\sawri\AppData\Local\Temp\tmp5jfzu5.tmp' is denied.`

`2024-06-16 21:22:52 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.Http.HttpRequestException: No such host is known. (osu.ppy.sh:443)`

Are you running any custom network rules such as proxies, vpns, custom dns, or firewall rules which may be blocking the host domain?

**Comment by kanseiyume** [comment]
No- my DNS is set to the default addresses, and the other things you mentioned are all either disabled (in the case of VPNS or proxies) or set to default as well. With the permission error you mentioned, how would I fix that? Obviously, launching osu! as an administrator would work, but there's a message in-game warning me that I shouldn't launch lazer as admin.

**Comment by Stoppedpuma** [comment]
> launching osu! as an administrator would work

Please **do not** do this, this will only cause more issues for you. You should instead be able to change permissions in the properties of the folder and going to the security tab.

**Comment by smoogipoo** [comment]
The primary issue is the temp file path. Have you ever changed permissions to the `C:\Users\sawri\AppData\Local\Temp` folder? You should reset that.

**Comment by kanseiyume** [comment]
I went to the folder that @smoogipoo mentioned and the "Everyone" permissions were just completely turned off (which is weird, but oh well). After changing the permissions back to the way they should be, everything seems to work as normal. Thanks!
