### ISSUE TITLE
HP bar disappears before drum rolls on some maps

### ISSUE THREAD

**Issue by ast-r** [ppy/osu#28512]
### Type

Cosmetic

### Bug description

On some maps, the HP bar disappears right before a drum roll and then reappears afterward. It seems like this happens more frequently on maps where there's more time before the drum roll. For example, the first drum roll on this map has this issue: https://osu.ppy.sh/beatmapsets/1622678#taiko/3313151

I can't say for certain, but it feels like this issue has been present for at least half a year.

### Screenshots or videos

https://github.com/ppy/osu/assets/63571583/67b341c6-3f35-45d2-9658-e6a61ce4f6d4

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15873955/compressed-logs.zip)

**Comment by smoogipoo** [comment]
I can't repro. Have you tried/can you still replicate with the default skin (argon, triangles, or even classic)? If those skins work, then post your skin.

Based on that it not only disappears but looks like the masking completely changes as evidenced by the background becoming rectangular, it might be a graphics issue.

**Comment by ast-r** [comment]
@smoogipoo The error does not reproduce with the default skins.

I have cleaned up my skin to include the minimal number of files necessary to reproduce the error. If needed, I can also provide the original, unmodified skin.
[skin.zip](https://github.com/user-attachments/files/16531671/skin.zip)

**Comment by smoogipoo** [comment]
Thanks. I'm able to reproduce with that skin.
