### ISSUE TITLE
Game freezing when the Telegram notification shows up

### ISSUE THREAD

**Issue by Airkek** [ppy/osu#28527]
### Type

Performance

### Bug description

Reproduces on Linux (X11) and Windows 11
STR:
1. Play any beatmap (any gamemode, fullscreen or borderless)
2. Receive a Telegram notification *on the same screen as Lazer*
3. Get microfreeze

I don't remember seeing this issue on older versions of Lazer; it's quite annoying.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/45855057/26c0c4ac-ec45-4fb7-9bf2-366f408576a4)

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15898841/compressed-logs.zip)

**Comment by bdach** [comment]
I'm not sure why we're responsible for this, rather than the telegram app, or the x server, or whatever else in your linux stack.

I'd move to discussion but I'm not even sure that's productive so I'm just gonna close directly. I'd ask for proof that this is the game's fault, especially that this is a linux report.

**Comment by Airkek** [comment]
> I'm not sure why we're responsible for this, rather than the telegram app
> 
> I'd move to discussion but I'm not even sure that's productive so I'm just gonna close directly. I'd ask for proof that this is the game's fault.

it reproduces even with native kde plasma notifications (probably when any top layer window appears)

**Comment by smoogipoo** [comment]
That's an issue for the KDE compositor to resolve. There's nothing we can do other than... disable notifications? And I'm not sure we can even/should even do _that_ - it's not our business as a game to do so.
