### ISSUE TITLE
Songs don't start playing with dotnet on linux

### ISSUE THREAD

**Issue by Criminalllz** [ppy/osu#2852]
Songs don't start playing when running osu on linux with  
'dotnet osu.Desktop/bin/Release/netcoreapp2.1/osu\!.dll'
This means that no music works, including "circles!".

Beatmaps also don't start playing perhaps as a cause of this. In the same way as this comment [#1302](https://github.com/ppy/osu/issues/1302#issuecomment-336760733).

I am kind of confused as to how i am supposed to build for dotnet, i am building it with
`msbuild /property:Configuration=Release` currently. However i would like to use an IDE, but monodevelop only builds the .exe for mono. How should i build it if i want to run it with dotnet?

[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2123752/performance-gamethread.audio.log)
[dotnet --info](https://github.com/ppy/osu/files/2123755/dotnet.txt)

**Comment by peppy** [comment]
Please try using the provided vscode debug tasks

**Comment by Criminalllz** [comment]
Okay, i got it running in vscode now (apparantly building it myself didn't work), what am i looking for?

Also what i think the song is playing backwards, making it seem like it doesn't start
![output](https://user-images.githubusercontent.com/21371374/41727080-c86f488e-7573-11e8-9406-66f79368e53b.gif)

Also regarding the artifacts in the video, and the graphics issues i talked about in #2843, it seems like it's just that my gpu is just starting to fail.

**Comment by Criminalllz** [comment]
![dotnet](https://user-images.githubusercontent.com/21371374/41730209-92182be0-757b-11e8-870d-88e4d0c606fe.png)
![mono (2018.616.0)](https://user-images.githubusercontent.com/21371374/41730239-a566f58c-757b-11e8-99a0-dce011edb791.png)

That looks interesting.

**Comment by VPeruS** [comment]
Do you hear sound effects(on circle size increase in menu)?

**Comment by Criminalllz** [comment]
Yes, on button clicks as well. I also get hitsounds in osu.Game.Tests when it isn't using a beatmap.

**Comment by VPeruS** [comment]
Run:
` % cd osu.Game/bin/Debug/netstandard2.0 `
` % sudo cp libbass_fx.so /usr/lib`
And provide feedback : )

**Comment by Criminalllz** [comment]
`Loaded '/home/kristian/.nuget/packages/nunit/3.10.1/lib/netstandard2.0/nunit.framework.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 28389 has exited with code 0 (0x0).
Loaded '/home/kristian/.nuget/packages/sharpcompress/0.18.1/lib/netstandard1.3/SharpCompress.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 28435 has exited with code 0 (0x0).
Loaded '/home/kristian/.nuget/packages/managedbass.fx/2.0.0/lib/netstandard1.4/ManagedBass.Fx.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 28439 has exited with code 0 (0x0).
The program '[28267] dotnet' has exited with code 0 (0x0).`

It just crashes with this as output

**Comment by VPeruS** [comment]
How are you running and building program? Did you install bass lib as separate package?

**Comment by Criminalllz** [comment]
I'm compiling and running it with vscode with the provided debug tasks, i tried using libbass.so from the same directory and the same thing happens when i add libbass_fx.so

**Comment by peppy** [comment]
Based on the provided screenshots, you have two completely different builds of osu!. If you're going to compare, please use the same git ref.

**Comment by VPeruS** [comment]
You get crash because of libbass_fx. Run find -name libbass_fx.so | xargs rm -r from osu project dir, run with dotnet "path". You should have graphics without songs but effects, if it so then I am currently working on it

**Comment by Criminalllz** [comment]
You are correct, the issue above is present on both mono and dotnet, i'll file another issue for that.

Apparently ManagedBass does not work with dotnet under linux.
https://github.com/ManagedBass/ManagedBass/issues/48

**Comment by VPeruS** [comment]
Consider to use lower version of bass, because mamaged bass is almost just DllImports. So it's may be bass's devs broke something. Also win works well

**Comment by Criminalllz** [comment]
I just tried the suggested fix, it worked. I think it is because it uses global linking, maybe it is because of lazy linking as well which might be because of a bug in something that osu never actually uses. How much do we need ManagedBass? Could we replace it, or would it be better to submit an upstream patch?

https://github.com/ManagedBass/ManagedBass/issues/48#issuecomment-367412287

**Comment by VPeruS** [comment]
Which fix?

**Comment by Criminalllz** [comment]
https://github.com/ManagedBass/ManagedBass/issues/48#issuecomment-367412287

**Comment by VPeruS** [comment]
If you get songs up and running then it must be something with netcore

**Comment by Criminalllz** [comment]
We can use 0x100 to define RTLD_GLOBAL, nothing more is needed.

RTLD_GLOBAL needs to be set, and if ManagedBass doesn't set it, mono is setting it without being asked to, which means that mono is doing it wrong as RTLD_LOCAL is supposed to be default.

RTLD_GLOBAL definition
`The symbols defined by this library will be made available for symbol resolution of subsequently loaded libraries. `
RTLD_LOCAL definition
`This is the converse of RTLD_GLOBAL, and the default if neither flag is specified.  Symbols defined in this shared object are not made available to resolve references in subsequently loaded shared objects.
`

**Comment by VPeruS** [comment]
All you need to do is to insert Bass.Version in main before anything

**Comment by Criminalllz** [comment]
That would be ManagedBass.Bass.Version right?

If i use that i get this error:

Property or indexer 'Bass.Version' cannot be assigned to -- it is read only [osu.Desktop]

**Comment by VPeruS** [comment]
Yes
```
 // to other usings
 using ManagedBass;
 
 // somewhere in main
 var d = Bass.Version;
```

**Comment by Criminalllz** [comment]
What does that help with?
Version is 2.4.12.

**Comment by VPeruS** [comment]
It may kick runtime loader to load bass before fx.

**Comment by Criminalllz** [comment]
That doesn't work.

I'm guessing libbass_fx needs libbass to be set RTLD_GLOBAL, or it will segmentation fault as it is trying to access something it can't

So LD_PRELOAD=libbass also works, and if libbass_fx is not present, it doesn't segfault anymore.

**Comment by VPeruS** [comment]
It's happens because libbass_fx depends on libbass's symbols, which means that load order must be {bass, bass_fx}, with RTLD_GLOBAL of course. And libbass don't have libbass_fx as it's library dependency(it's user responsibility to load it correct), you can check it with `ldd`. So we have two ways: trick dotnet to load bass before fx, or manually load them in correct order,

**Comment by Criminalllz** [comment]
DllImport only lets you use the specified command of the library in your program, it does not allow other libraries to use it, hence something as simple as this
[sample code](https://github.com/ppy/osu/files/2130125/test.txt)  won't work, because DllImport can not do RTLD_GLOBAL. 


I assume you meant that libbass_fx does not have libbass as a defined dependency, which is true, and that means that the system has no idea where to look for BASS_GetVersion because no one told it where to look.

The issue is not about loading order, which is why loading ManagedBass.Bass.Version works, but we still get the same error.

Here is the output before the crash:
/usr/lib/libbass_fx.so: error: symbol lookup error: undefined symbol: BASS_GetVersion (fatal)

Ideally libbass_fx would make the system aware that it needs libbass to work, but for now we need to find another method to load libbass so that libbass_fx can use it.

**Comment by VPeruS** [comment]
Then it's easy: dlopen "bass" with GLOBAL, dlopen "fx" in static constructor of AudioManager

**Comment by VPeruS** [comment]
https://github.com/dotnet/coreclr/issues/18599 this is our problem

**Comment by peppy** [comment]
Has anyone tested ppy/osu-framework#1645 yet?

**Comment by VPeruS** [comment]
Works perfect with tests
