### ISSUE TITLE
Hit Taiko Beats layering bug

### ISSUE THREAD

**Issue by tomdenty1** [ppy/osu#2853]
After being hit, seemingly randomly taiko beats disappear.

https://youtu.be/BZAs3-W3uUI

**Comment by tom-arrow** [comment]
It's caused by this
https://github.com/ppy/osu/blob/9cec76919147629049ff0c930afc94d9d4f9acb7/osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs#L96-L99

I don't get why this condition is necessary, it's seems to work well without it (even when rewound)
