### ISSUE TITLE
Beatmap listing doesn't show beatmaps from deleted account or with username change

### ISSUE THREAD

**Issue by OscarRoussel** [ppy/osu#28530]
### Type

Other

### Bug description

After changing hard drives and attempting to find maps that I played previously I was not able to find some maps.

**It appears that the beatmap listing tab and search functions do not show some beatmaps from removed/banned/username changed accounts while they still appear on the website.**

Example beatmap : https://osu.ppy.sh/beatmapsets/352624#osu/777073
Example search through osu website with title `kitsune no yomeiri` and tags `loved` : https://osu.ppy.sh/beatmapsets?q=kitsune%20no%20yomeiri&s=loved
The same search on the beatmap listing tag in lazer does not appear.

This seems to be linked to the fact that the author of the beatmap has since removed their account, or has been banned, or has changed username.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/45663923/3aad8a87-2c32-4ee6-8a9f-2879b4bc05cc)

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15903432/compressed-logs.zip)

**Comment by Joehuu** [comment]
It's because the linked beatmap is explicit and the "explicit content" filter is saved separately from lazer and web,
