### ISSUE TITLE
Custom Playfield layout (osu!mania only) scales depending on the number of keys

### ISSUE THREAD

**Issue by Airkek** [ppy/osu#28545]
### Type

Cosmetic

### Bug description

The component scaling for 4k and 7k doesn't match. I want to place the HP bar on the right side of the playfield, but it breaks on 7k (or 4k, depending on the number of keys in the map I was editing the skin on) :c

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/45855057/99f83f57-5513-44d8-aae4-8cb030b478e8)
![image](https://github.com/ppy/osu/assets/45855057/855bd20e-2fc7-48d3-a92b-c0f219797b4e)

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15932439/compressed-logs.zip)

**Comment by Airkek** [comment]
Noticed that this can be done by using argon health bar with relative size option off
Still idk what to do with argon song progress :(

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/24388
