### ISSUE TITLE
lazer thinks specific diff in ranked set isn't ranked

### ISSUE THREAD

**Issue by kevinboiiii** [ppy/osu#28551]
### Type

Other

### Bug description

after importing from stable, lazer thinks specific diff isn't ranked, and won't submit scores/load leaderboards, while it does for every other diff.
map: https://osu.ppy.sh/beatmapsets/2091512#osu/4642440
I did not download/play the map before it was ranked, and only the diff that was affected was the one that i had set scores on in stable, then imported those onto lazer.
I have tried reimporting the map.

### Screenshots or videos

https://www.youtube.com/watch?v=UaDX2YckS2g

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15937821/compressed-logs.zip)

**Comment by kevinboiiii** [comment]
NOTE: I don't know why it says crash to desktop I didn't see that field while making it. Sorry!

**Comment by SupDos** [comment]
```
2024-06-21 19:40:05 [verbose]: [d8117] [APIBeatmapMetadataSource] Online retrieval mapped Mutsuhiko Izumi - Snow Goose (Riana) [Cellina's Extra] to 2091512 / 4642440.
2024-06-21 19:40:05 [verbose]: Discarding metadata lookup result due to mismatching online ID (expected: 4642417 actual: 4642440)
```
seems to be another case of https://github.com/ppy/osu/discussions/28295, have added a comment there

**Comment by Jedop** [comment]
I am facing the same problem as well. Is there any fix to this?
