### ISSUE TITLE
Score not submitted caused by wrong latest version

### ISSUE THREAD

**Issue by cyrianR** [ppy/osu#28556]
### Type

Game behaviour

### Bug description

For every map I play I get this warning in osu lazer. (cf screenshot)
I've seen several issues with the same bug but I'm on Arch linux and all similar issues were found on Windows so I don't find a similar way of resolving the issue.

Note that I had a previous install of osu on a Windows computer (not lazer) and I copied all osu files on an external drive in order to import beatmaps in osu lazer on my current computer, which worked very well. However, I guess I started having this issue after that.

### Screenshots or videos

![swappy-20240623-201830](https://github.com/ppy/osu/assets/149821230/50a61526-8da5-474b-a00a-c4a280c11df4)

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15945634/compressed-logs.zip)

**Comment by BlockHead007** [comment]
2024-06-23 17:15:00 [verbose]: Request to https://osu.ppy.sh/api/v2/beatmaps/1863231/solo/scores failed with System.Net.WebException: UnprocessableEntity.
2024-06-23 17:15:00 [verbose]: Response was: {"error":"missing token header"}
2024-06-23 17:15:00 [verbose]: Failing request osu.Game.Online.Solo.CreateSoloScoreRequest (osu.Game.Online.API.APIException: missing token header

#27290

**Comment by smoogipoo** [comment]
In this case there is no `auth.log` file and they're running under Linux. @cyrianR how exactly did you obtain this version of osu!?:
- What operating system (arch/nix/debian/etc)?
- If you used a package manager, which one and which package?

**Comment by smoogipoo** [comment]
I've checked the logs again and one of the earlier logs has:
```
2024-06-16 19:50:38 [verbose]: ⚠️ This is not an official build of the game. Scores will not be submitted and other online systems may not work as intended.
```

Which is an important distinction, because this indicates that there's no foul play other than that this is not a binary build of the game by us.

If you're using the AUR, make sure you use [`osu-lazer-bin`](https://aur.archlinux.org/packages/osu-lazer-bin) and _not_ [`osu-lazer`](https://aur.archlinux.org/packages/osu-lazer) or any of the other incarnations.

**Comment by cyrianR** [comment]
Thank you @smoogipoo and sorry for late response. I made it work using the AppImage application. I might try the osu-lazer-bin package if i get bored with the AppImage but it's working so I will stay with it for now.
