### ISSUE TITLE
Graphical overlap on direct panels

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2855]
![Pasted Image 1.png](https://shipusercontent.com/c911ab2228bd8dd02a2de8ca65b73f20/Pasted%20Image%201.png)

The download button should have a non-transparent background or the difficulty icons should be contained.

**Comment by peppy** [comment]
Should be resolved with design change in #2855.

**Comment by Joehuu** [comment]
Should reference #2856 instead.

**Comment by peppy** [comment]
Was supposed to be #2888 in fact, but good catch.
