### ISSUE TITLE
Long notes bug

### ISSUE THREAD

**Issue by Netherun** [ppy/osu#28584]
### Type

Game behaviour

### Bug description

After last update 2024.625.0-lazer long notes dont display on all of skins, except "argon", "argon" pro, "triangles" from the osu team.

### Screenshots or videos

https://github.com/ppy/osu/assets/73305873/e0d08614-1a46-47b1-821c-31652e9d9b73
this is fully ln map, however it doesnt show a single ln

### Version

2024.625.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15970400/compressed-logs.zip)

**Comment by peppy** [comment]
This will be fixed in a hotfix release, please wait a bit.
