### ISSUE TITLE
The rank display component start flickering once its drop from SS to S in classic mod

### ISSUE THREAD

**Issue by jkh675** [ppy/osu#28593]
### Type

UI

### Bug description

During replay or gameplay, when the rank drops from SS to S, the rank display components start flickering. This issue seems to occur on all maps and specifically when the rank is S.

### Screenshots or videos

https://github.com/ppy/osu/assets/52519933/bf2a936a-b90f-4c07-b834-0572fe06c422

https://github.com/ppy/osu/assets/52519933/96351b90-6ca4-44c0-bfc5-0dbfeb6ec92c

### Version

latest release 2024.625.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15974018/compressed-logs.zip)

**Comment by jkh675** [comment]
New update: this issue only happen when the classic mod is on

**Comment by bdach** [comment]
Please check out the latest hotfix that just came out (2024.625.2) that contains a fix for this.
