### ISSUE TITLE
Startup crash on linux

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu#2861]
![screenshot](https://user-images.githubusercontent.com/14909211/41772609-8d98f498-7619-11e8-8a8e-1a06ff4c62c2.png)
If I click continue it keeps running but no window or console output appears.
[runtime.log](https://github.com/ppy/osu/files/2127389/runtime.log)

[debug console output](https://paste.ee/p/Qk4lF)

**Comment by VPeruS** [comment]
Same cause as in #2852

**Comment by LastExceed** [comment]
Doubt it. In the issue you referenced the game at least starts and plays **some** sounds. Also I tried the provided fix and it didn't help.

**Comment by LastExceed** [comment]
I disabled JustMyCode and finally got a useful error message. Turns out it's because of #2386 which was supposed to be fixed in ppy/osu-framework#1617 but apparently wasn't. A temporary fix can be found in ppy/osu-framework#1540

**Comment by peppy** [comment]
Are you saying the fix in that merged PR doesn't work? Are you understanding it correctly (it only works if you run via vscode)?

**Comment by LastExceed** [comment]
Sorry, should have actually looked at the PR before reporting (didn't expect that I have to apply it myself).

Yes that fixes it, but why do I have to edit launch.json myself? Shouldn't it be part of the repo by default?

**Comment by peppy** [comment]
You don't (that's what the PR fixed. Note what it says in the description of the PR: it *only fixes when opening from visual studio code*.

Please no more comments on these issues unless you are PRing a solution. This is just going around in circles.

**Comment by peppy** [comment]
Will probably be resolved by ppy/osu-framework#1645.
