### ISSUE TITLE
Editor becomes laggier and laggier while paused with a slider selected

### ISSUE THREAD

**Issue by memikri** [ppy/osu#28625]
### Type

Performance

### Bug description

I was in the editor (paused) and had the game minimized for several minutes. When I came back, the game was lagging terribly.

### Screenshots or videos

<img width="1284" alt="image" src="https://github.com/ppy/osu/assets/49217372/0c5fd590-3f67-4820-9849-c74f332d1f34">

<img width="1920" alt="image" src="https://github.com/ppy/osu/assets/49217372/92801c38-84fa-44da-85bf-64b0a6fe0647">

<img width="610" alt="image" src="https://github.com/ppy/osu/assets/49217372/0d51951e-6f0d-4cb0-9d88-ba093f551fd6">

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15994178/compressed-logs.zip)

**Comment by smoogipoo** [comment]
cc @bdach is this https://github.com/ppy/osu/issues/28618 ?

**Comment by peppy** [comment]
It is, yes.
