### ISSUE TITLE
Dragging outside of an overlay doesn't dismiss it

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2862]
This most definitely regressed recently.

https://puu.sh/AJYK0/f40d582b1e.mp4

**Comment by ticotaco72** [comment]
video is corrupted

**Comment by peppy** [comment]
It's fine here. No big deal if you can't see it; the description should be ample.

**Comment by Joehuu** [comment]
Confused about the labels. Should be input. Also drag clicking on buttons doesn't work. Might be linked.

**Comment by Joehuu** [comment]
This has regressed.
