### ISSUE TITLE
Performance issues when playing storyboard for the first time

### ISSUE THREAD

**Issue by Glebsin** [ppy/osu#28633]
### Type

Performance

### Bug description

When playing storyboard for the first time performance drops, but after probably buffering it playing with acceptable performance (when rewind backwards in the same replay)
<details><summary>Stable</summary>

https://github.com/ppy/osu/assets/49247750/debaef72-b035-4f42-9513-192f5b61a2dd
</details> 
<details><summary>Lazer</summary>

https://github.com/ppy/osu/assets/49247750/b4426299-8ba3-4b0d-a16c-5a8b32c85fbe
</details> 

Link to map: https://osu.ppy.sh/b/4646109

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16009144/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/4976
