### ISSUE TITLE
Incorrect "Connected joystick device" notification

### ISSUE THREAD

**Issue by Flanster** [ppy/osu#2863]
So, I updated to latest (2018.622.0) and got a few notifications

> 22.6.2018 2:36:15: Connected joystick device: 07b2045e-0000-0000-0000-504944564944
> 22.6.2018 2:36:15: Connected joystick device: 07b2045e-0000-0000-0000-504944564944
> 22.6.2018 2:36:15: Connected joystick device: 07b2045e-0000-0000-0000-504944564944
> 22.6.2018 2:36:15: Connected joystick device: 07b2045e-0000-0000-0000-504944564944

I've tested this out and it turns out its picking up my wireless mouse's USB tranceiver as a joystick apparently.

**Comment by peppy** [comment]
See https://github.com/ppy/osu-framework/pull/1643

**Comment by Joehuu** [comment]
Can close this. You referenced the wrong issue in the PR.
