### ISSUE TITLE
No in-game text when building with Mono on Linux

### ISSUE THREAD

**Issue by helveticau** [ppy/osu#2864]
I'm trying to run osu! on Arch Linux using Mono (MonoDevelop). I've successfully built osu, but when I run it, there is no in-game text at all.
By the way, osu!.exe runs osu!lazer. Is it possible to run osu!stable on Linux?
![2018-06-22-225944_1920x1080_scrot](https://user-images.githubusercontent.com/40447739/41798639-0b7d0eb4-7677-11e8-99aa-0efe84beefa1.png)

**Comment by VPeruS** [comment]
Possible duplicate #2843

**Comment by Criminalllz** [comment]
If you want you can use https://aur.archlinux.org/packages/osu-lazer/ in the mean time. It is using v2018.616.0 which doesn't have this issue. Or just reset it to https://github.com/ppy/osu/commit/b9d63ee7b1e6cb27d1c516c6bb7a87e456353cb1 yourself.

Osu-stable probably runs via wine, you can look at https://aur.archlinux.org/packages/osu

**Comment by helveticau** [comment]
Resetting to `b9d63ee` fixed my issue. Thanks. I hope this issue will be fixed in future commits.
