### ISSUE TITLE
Dropdown button not working if the arrow part is clicked

### ISSUE THREAD

**Issue by vatei** [ppy/osu#28679]
### Type

Game behaviour

### Bug description

Tried clicking a dropdown on the arrow part of the button, however nothing happened until I actually moved my cursor a bit to the left and clicked.
Attached a recording of the issue

### Screenshots or videos

![dropdown](https://github.com/ppy/osu/assets/45978249/5de7989e-438e-4121-9765-a0728c7c6999)

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16042646/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Will be fixed in the next release, https://github.com/ppy/osu-framework/pull/6315
