### ISSUE TITLE
Removing a break time isn't reflected on editor timeline

### ISSUE THREAD

**Issue by Wildthing0** [ppy/osu#28678]
### Type

Crash to desktop

### Bug description

place objects in editor with a gap to make a break, delete object at end of break, break time stays on timeline

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/90672169/9e61be7b-ff12-4a01-a9f7-8b9c66b443d4)

### Version

2024.625.2

### Logs

for some reason my logs folder is empty and the export logs button doesn't work (am on ubuntu using osu in old windows folder)

**Comment by peppy** [comment]
To clarify, this is talking about the *bottom* timeline.
