### ISSUE TITLE
Long hold "percy" note sprite endings placed incorrectly on screen

### ISSUE THREAD

**Issue by beeberies** [ppy/osu#28673]
### Type

Cosmetic

### Bug description

Skins with the long "percy" hold note sprite have their sprite ending "earlier" than in stable. This makes it near-impossible to differentiate short hold notes from medium-length hold notes, as well as throwing off the release timings for mania players transitioning to lazer that use this as their long note sprite. This happens on both bojii(a top mania player)'s skin and my skin where I took the LN_BODY file (the 20,000 pixel long image) from bojii's skin and replaced it in my own.
[bojii's skin](https://www.mediafire.com/file/58ie1jxwihd2xu8/bojii_04-02-2023.osk/file)
[my skin](https://www.mediafire.com/file/sycmyf5twezgefa/E%255Bdited_LN%255Dliminate294%2527s_Mania_Skin.osk/file)

### Screenshots or videos

NOTE: my skin has circles, bojii's has bars
### in stable:
GHOST VIP:
https://github.com/ppy/osu/assets/171388105/66e98383-ac03-4266-ab29-8dc82ee6a36b
FULL FLAVOR ODON (downscroll):
![Screenshot 2024-06-29 035441](https://github.com/ppy/osu/assets/171388105/f11b49ac-f665-4986-aefe-6e4f90f749e1)

### in lazer:

GHOST VIP:
https://github.com/ppy/osu/assets/171388105/bdfd9b02-aa68-4ee0-ab09-8d142e7e7b5c
FULL FLAVOR ODON (upscroll):
![Screenshot 2024-06-29 035255](https://github.com/ppy/osu/assets/171388105/2a8a0113-5d72-4668-ac7c-f0cbc80da563)

Even with identical scroll speeds, there is some differences in where the LN sprite ends.

Also, with bojii's skin in FULL FLAVOR ODON, where the hold note fades much earlier (judging by the next yellow and blue notes), I believe the small vertical rectangle is displayed as the LN tail, which is shown noticeably earlier in lazer than in stable.

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16039486/compressed-logs.zip)

**Comment by beeberies** [comment]
Oh wait my bad, the vertical rectangle in bojiis skin is NOT the end of a hold note, oversight in my part.

However, I still notice a difference when comparing stable to lazer

**Comment by smoogipoo** [comment]
This is intentional for now. Support is only approximate but not exact as mentioned in the original PR https://github.com/ppy/osu/pull/22599

**Comment by beeberies** [comment]
ah, didn't see this at first. thanks!
