### ISSUE TITLE
Unhandled exception when starting a map and entering a 0 match search result at the same time

### ISSUE THREAD

**Issue by gBasil** [ppy/osu#28675]
### Type

Other

### Bug description

Firstly, this only works if entering the character causes the beatmap search to yield 0 matches. For example, I don't have any maps with`\` in their name, so typing that gives me 0 matches.

On the level select screen, with the difficulty of a map selected, you have to type the character into the search box and press enter at roughly the same time. I'm not sure if one should be pressed before the other, but due to human error, press them at exactly the same time, and it should eventually work. Doing this correctly causes an exception to be thrown. In addition, when exiting the level, even though there should be 0 matches, it considers the currently selected song matched.

There might be more behavioral errors that arise from doing this action, such as desyncing the search results, but I'm not entirely sure.

### Screenshots or videos

https://github.com/ppy/osu/assets/57513430/196a05bb-faca-47f4-8603-122866294af1

https://github.com/ppy/osu/assets/57513430/bfeb7faf-8e72-40c8-bd57-61be2305c704

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16041637/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21120

**Comment by gBasil** [comment]
Gotcha, I didn't see that one when I was checking for duplicates. Thanks!
