### ISSUE TITLE
osu!(lazer) does not run after updating

### ISSUE THREAD

**Issue by Saerdna123** [ppy/osu#28680]
### Type

Other

### Bug description

game opened fine before the update, now does nothing when I click it.
tried restarting computer but didnt work

### Version

2024.625.3-lazer

### Logs

cant open lazer to export logs

**Comment by Saerdna123** [comment]
wait it launched when i opened a downloaded map here is logs:
[compressed-logs.zip](https://github.com/user-attachments/files/16042973/compressed-logs.zip)

**Comment by normalid-awa** [comment]
+1 i have this issue too, after updating to the new 625.3version the game didn't launch up, but when i use the source code and run it in debug build it can run successfully but when i rin the release version it just didn't respond

**Comment by emanh1** [comment]
+1

**Comment by normalid-awa** [comment]
![image](https://github.com/ppy/osu/assets/52519933/85233190-c7ca-4a01-80e8-22a5a6d821a3)
![image](https://github.com/ppy/osu/assets/52519933/f0a3c0bd-e766-42b8-829c-ce3fc5e71e22)

windows event logger said the osu throw an error seems related to the 'osu.Framework' file non exist.

**Comment by Saerdna123** [comment]
fix
![08a4beda8647318a0a2358f2daf954b8](https://github.com/ppy/osu/assets/33616260/146820b8-3cdf-448c-9ed4-6ccec760ee76)

**Comment by carpspet** [comment]
also now for some reason i can unhide my task bar while in lazer? (tried cycling through all display modes) 
![image](https://github.com/ppy/osu/assets/121141414/9f0e3082-476e-4118-93f7-814dcd96bd88)

**Comment by Joehuu** [comment]
Build has been pulled.
