### ISSUE TITLE
Latest update does not launch on Linux

### ISSUE THREAD

**Issue by lando07** [ppy/osu#28681]
### Type

Crash to desktop

### Bug description

When updating my appImage to the latest version, it doesn't launch.
Here's my terminal output:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'osu.Framework, Version=2024.627.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'osu.Framework, Version=2024.627.0.0, Culture=neutral, PublicKeyToken=null'
Aborted (core dumped)
```
Something to note is that the previous release did work, only this new version is broken

### Version

2024.625.3

### Logs

I cannot export logs.

**Comment by Joehuu** [comment]
Build has been pulled.
