### ISSUE TITLE
Changing Slider Velocity makes the Distance Snapping Visual Off

### ISSUE THREAD

**Issue by CuredDDN** [ppy/osu#28699]
### Type

Cosmetic

### Bug description

I was messing with the slider velocity but when i tried to align the hit object with the distance snapping, it wasn't following the distance snapping lines.

### Screenshots or videos

https://github.com/ppy/osu/assets/148664525/b3a1203c-ca31-4761-a113-79827f0572e3

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16061759/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21347
