### ISSUE TITLE
missing hotkey for volume change while hovering over a scrollable container

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu#2869]
the mouse wheel can be used to change the volume, unless you're hovering a scrollable container (e.g. song selection, scoreboards, social browser, direct, etc). stable features the hotkey alt+mouse wheel to change volume in these cases. This hotkey seems to be missing in lazer.

**Comment by peppy** [comment]
If anything, using alt should work with all existing bindings rather than be an explicit binding.

**Comment by camellirite** [comment]
alt + mouse wheel still doesn't work in the osu!direct, social browser, chat, sign in/signed in, notifications, or settings container, and doesn't work at all in the editor. I don't think the pr fixed the issue unless I'm misunderstanding

**Comment by peppy** [comment]
The PR specifically mentions it doesn't fix those cases. They are a bit more involved. I guess we can keep this issue open until those are fixed too.
