### ISSUE TITLE
Editor timeline break period ignores the Approach circle timing

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#28703]
### Type

Game behaviour

### Bug description

Hi. It's the problem:
![image](https://github.com/ppy/osu/assets/89677246/7cb8d1de-7376-4e60-9c3b-f7f72b970d9d)
![image](https://github.com/ppy/osu/assets/89677246/8bad5bc0-2dc3-4604-ab39-a8dd1589d0d6)

Also, there is no option to remove the break time.

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16067739/compressed-logs.zip)

**Comment by bdach** [comment]
See https://github.com/ppy/osu/pull/28528

> 2 beat lengths between the break's end and the first object after break. This is a departure from stable wherein this was ruleset- and AR-dependent (by way of using preempt time), but in talking with the NAT it looked like most didn't know the specifics of how that worked so I decided I'd just use something simpler. This also probably works better for something like mania wherein the "preempt time" is largely user-settings-dependent (scroll speed).

That said there are less than 2 beat lengths on the attached screenshot. Did you change the break's duration manually via the drag handles?

**Comment by aL1NaZ4R** [comment]
In the above screenshot, yes I did. but it's automatic break also overlaps the approach rate.

https://github.com/ppy/osu/assets/89677246/659bcfce-c52a-4653-8dcb-aa1fc47a6e98

**Comment by aL1NaZ4R** [comment]
I'm not into professional things btw, but I think it would be better to implement stable's one, because with this system, mappers would have to look up those break times again, for ranking issues.

**Comment by aL1NaZ4R** [comment]
As for this one, I didn't touch it. It's exactly after reenter.
>  2024-07-02_19-20-01.mp4

**Comment by frenzibyte** [comment]
This is probably not as relevant but since you mentioned "NOT removable at all", technically you can remove them next release with https://github.com/ppy/osu/pull/28707.
