### ISSUE TITLE
osu!mania scroll speed is indicated in milliseconds but scales with BPM

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu#2870]
in stable, bpm scaling is standard behaviour and can be turned off in the options. In lazer however, that option doesn't exist and scrollspeed is indicated in scrolltime which suggests the speed to be fixed, however it's not. Currently it seems to be ```indicated_scrolltime x 50 / BPM = final_scrolltime``` (based on observation) making the result of a given value unpredictable (just like stable where no player knows what the number actually means and everyone has to try out different values to find one that "feels right").

Indicating the speed in scrolltime is a good thing as it gives the number an understandable meaning, but if BPM scaling is active then the overlay that shows up when you change the scrollspeed should display both the input value and the resulting time after BPM scaling is applied.

This brings along the problem that lazer currently doesn't have an option for fixed scrollspeed, which is a must-have. I'd even go so far to question whether or not we want to keep BPM scaling (and if yes, which of the two should be default). It is important to note that even though the default in stable is BPM scaling, almost all players use fixed scrollspeed.

**Comment by smoogipoo** [comment]
I'm definitely a fan of removing BPM scale.

**Comment by peppy** [comment]
Sounds fine. Not sure if we need a toggle for it – does anyone out there prefer bpm scaling by default?

**Comment by AlFasGD** [comment]
I always play with my custom scaling. Many players also do so since that's what they're used to. Maybe not entirely removing it, but keeping it as an alternative option, while custom scaling is the default would be great.

**Comment by LastExceed** [comment]
idk when this changed but scrollspeed is now fixed speed, however the indicated scrolltime is still inaccurate. it seems to apply roughly 2/3 of the user setting, eg when setting scrollspeed to 5000ms the notes take ~3333ms to travel from top of the stage to judgement line.

**Comment by peppy** [comment]
Are you sure you are testing on a beatmap with no timing changes?

**Comment by LastExceed** [comment]
yes, i have tested multiple beatmaps (both high and low bpm)

**Comment by smoogipoo** [comment]
The displayed scroll speed is only a guide as to the scrollspeed if the longest timing point in the map was 60bpm. We will change this into a "multiplier" at some point similar to stable.

**Comment by LastExceed** [comment]
that would however contradict your suggestion of removing bpm scaling. i believe using scroll time is already a great way to indicate scroll speed

**Comment by peppy** [comment]
I kinda like the scroll time as a metric. Should probably look into why this is wrong?

**Comment by smoogipoo** [comment]
My bad the "at 60bpm" part is incorrect, it should just be the scrollspeed of the longest timing point, but I can replicate the incorrect scroll speed and am investigating.

**Comment by EVAST9919** [comment]
As a mania player can agree: I personally prefer "multiplier" over milliseconds. Not because it's better or worse, more because "I used to". And it's easier to read, I guess? Two digit number is easier to read and memorize.

**Comment by hhirtz** [comment]
Hello,

Scroll speed isn't fixed for me (downloaded a zip after this issue's been closed). For example these two beatmaps don't scroll with the same speed:

- https://osu.ppy.sh/beatmapsets/575053#mania/1217803
- https://osu.ppy.sh/beatmapsets/176972#mania/426032

**Comment by smoogipoo** [comment]
Please test using https://github.com/smoogipoo/osu/tree/fix-mania-scrolling-speed instead. It looks very close to me.
