### ISSUE TITLE
Editor Setup tab: Clicking penetrates the background image

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#28702]
### Type

Game behaviour

### Bug description

Hi. You can click through the background image field. Same if you import an image too.

### Screenshots or videos

https://github.com/ppy/osu/assets/89677246/7de93353-4281-4f47-a4cd-f47b937e4ad5

### Version

2024.625.2

### Logs

no need?

**Comment by bdach** [comment]
Screen will be getting redesigned anyways most likely.

**Comment by Joehuu** [comment]
Fixed in new design (https://github.com/ppy/osu/pull/30099 / https://github.com/ppy/osu/pull/30109).
