### ISSUE TITLE
Editing Sliders make huge FPS drop

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#28701]
### Type

Performance

## Description
Hi. After opening the editor to edit a map, everything is fine at the first, and my FPS is around 130-150. After messing around with the sliders, the Performance gets a significant drop, decreasing the FPS to 20-30.
There will be no FPS drop if you're idle after entering the Editor, or don't touch sliders at all.
I recorded a video editing [KIRA - WILDCARD (RavenSenpa1).zip (It's made by me)](https://github.com/user-attachments/files/16067470/KIRA.-.WILDCARD.RavenSenpa1.zip). I've also tested other maps by others, and the performance drop was smaller.

## Settings
**1920x1080** , **Exclusive FS** , **Multi-Threaded** 
**Renderer:** Automatic (d3d 11)
**Frame limit:** 2x refresh rate (mine is 75)

### Screenshots or videos

https://github.com/ppy/osu/assets/89677246/99fb618a-acfe-45f2-89e5-afd220c114a9

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16067520/compressed-logs.zip)

**Comment by aL1NaZ4R** [comment]
> #28618

I think it's not a problem with multiple sliders in my case. It happens only with 1 slider for me. idk!

**Comment by bdach** [comment]
Either way there are pending fixes to editor performance that have not seen a release yet. 99% chance the fix for the above fixes this too.
