### ISSUE TITLE
Break not showing in lazer

### ISSUE THREAD

**Issue by KnowScratcher** [ppy/osu#28717]
### Type

Game behaviour

### Bug description

The game doesn't show the break countdown in lazer.
There are three breaks in this beatmap, and the first and second break show but the last doesn't.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/103301742/1c4d14e3-c682-430e-862a-56dcea3845a2)

![image](https://github.com/ppy/osu/assets/103301742/c216bf9c-d9b4-4c28-99c6-766f9cf0e0bc)

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16077902/compressed-logs.zip)

**Comment by frenzibyte** [comment]
@KnowScratcher Please link the beatmap.

**Comment by KnowScratcher** [comment]
I haven't upload it yet, but here's the osz file
https://drive.google.com/file/d/1_eWI7jzjszp7ErewwOGM_-qSz31DbAM5/view?usp=sharing
The issue occurred in the last break of the "easy" difficulty

**Comment by frenzibyte** [comment]
Okay I can see what's going on. This can be reproduced by creating a beatmap with two auto-generated break periods, modify the duration of the second break period, then trigger the auto-generation logic again by moving the time of any object.

`BreakOverlay` expects break periods to be in chronological order, but the auto-generation logic outputs an unordered break periods as it keeps `ManualBreakPeriod`s and adds the auto-generated break periods on top of it regardless of the interval of the manual break periods.
