### ISSUE TITLE
Hotkeys ignore keyboard layout

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu#2871]
most notable case is the default buttons for osu!std (XZ). On a german keyboard for example Z and Y are swapped but if Y is pressed on a german layout during gameplay it is still registered as Z and thus triggers a click.

Other examples would be the hotkeys for chaning osu!mania scrollspeed ( [ctrl] + [+] / [ctrl] + [-] ) which on a german keyboard turn into [ctrl] + [ß] / [ctrl] + [´] or just the general key configuration menu in the settings (if I try to map something to Y, a Z appears instead).

It is probably a result of reading scan codes (hardware keys) instead of virtual keys, which however is a requirement for raw input.

This does not affect text boxes.

**Comment by jorolf** [comment]
I would go for showing whatever the key is on the current layout while using and saving the hardware key. 
If we go for saving the "layout" key we'd have some problems: what if the default keys are in a different position? (i.e. the french/german keyboard layout) and how do we save them in the config?

**Comment by KoleckOLP** [comment]
I use dvorak keyboard layout and when I type into a search bar my dvorak layout works, but when binding keys they get set as if I was using qwerty layout.

**Comment by peppy** [comment]
Text input to the search bar uses a different API. We are already aware of keyboard layouts being completely unsupported (long-standing issue https://github.com/ppy/osu-framework/issues/252).

**Comment by peppy** [comment]
Has been resolved.
