### ISSUE TITLE
Fast typing makes issues when changing sample volume

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#28713]
### Type

Game behaviour

### Bug description

Hi. As you can see in this video, I'm trying to change those volumes to "60" but it looks like my 0 overwrites the 6

https://github.com/ppy/osu/assets/89677246/249891f2-4a6b-4d9d-80e5-e22c102f2a58

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16071327/compressed-logs.zip)

**Comment by frenzibyte** [comment]
You can select multiple objects and adjust the volume of all of them at once (although you will have to do it for each piece of the slider, i.e. head/tail/whatever-you-name-the-middle).

I think we can further improve the experience of interacting with a number box by selecting the entire number when clicking on them, instead of requiring the user to drag? @peppy thoughts?

**Comment by bdach** [comment]
> I think we can further improve the experience of interacting with a number box by selecting the entire number when clicking on them, instead of requiring the user to drag?

What does that have to do with the issue? The video shows the user selecting the entirety of the text, but some of their input is apparently getting eaten? That sounds like the bigger issue to me here.

**Comment by peppy** [comment]
I do agree the content should be selected for both of the textboxes in this popup.

I don't have a mouse connected to test with, but it looks like this may be a bug from typing while a drag operation has not yet finished on the textbox? If possible we'd want to be cancelling the drag operation as soon as the user types anything.

**Comment by frenzibyte** [comment]
> I don't have a mouse connected to test with, but it looks like this may be a bug from typing while a drag operation has not yet finished on the textbox? If possible we'd want to be cancelling the drag operation as soon as the user types anything.

That does indeed seem to be the underlying cause of the issue. Couldn't notice it out immediately.
