### ISSUE TITLE
can't import skin on osu Lazer chromebook

### ISSUE THREAD

**Issue by cool271** [ppy/osu#28724]
### Type

Crash to desktop

### Bug description

doesn't let me import osu Lazer skin

### Version

newest version 3 july

### Logs

please help

**Comment by bdach** [comment]
Can't help if there is no link to the skin and there are no logs.

**Comment by cool271** [comment]
> Can't help if there is no link to the skin and there are no logs.

it doesn't work on any skin

**Comment by cool271** [comment]
> Can't help if there is no link to the skin and there are no logs.

It might be because i'm on chromebook
