### ISSUE TITLE
Editor performance regression when many newly added sliders are visible

### ISSUE THREAD

**Issue by TheMask3** [ppy/osu#28725]
### Type

Performance

### Bug description

The exact way to reproduce this is unknown, but it often happens after I add quite a few sliders while editing beatmap in editor. While the newly added sliders are in screen, FPS can drop to as low as 15FPS. When this happens, quit editor, enter again, previously added sliders will not cause problems, but FPS will drop again after I add some more sliders and keep them in screen.

### Screenshots or videos

There are 4 videos below.

First showing what happens when this bug occurs, as you can see in the video, old sliders don't cause frame drops.

https://github.com/ppy/osu/assets/13573720/3dd72ab8-7550-4457-983b-8da6db9dfb24

Second showing a failed attempt to reproduce this problem (2.0x speedup), adding sliders alone don't seem to make things as bad as last time.

https://github.com/ppy/osu/assets/13573720/85a6fc66-bd33-41da-9d34-3a5c1d99e5c9

Third recorded after I did some web browsing and switching back to osu, this time some mere 4 sliders dragged FPS down to 20s.

https://github.com/ppy/osu/assets/13573720/cdc8d35c-ab54-44fc-91f4-c8ce3395a1e3

Fourth recorded after deleting sliders added in third video, wrote some bug description for this post and switching back to osu again, this time even worse, two sliders and a hit circle dragged FPS down to 16. Note, I didn't touch these objects for this session.

https://github.com/ppy/osu/assets/13573720/dac10257-a023-460f-86be-9e60a716ab95

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16088234/compressed-logs.zip)

**Comment by peppy** [comment]
Already fixed for the next release (maybe we need a hot fix at this rate of report)
