### ISSUE TITLE
backspace key doesn't work globally

### ISSUE THREAD

**Issue by tomdenty1** [ppy/osu#2872]
Title says it all, seems like other people are having this issue too
(windows 10)

**Comment by peppy** [comment]
I'm guessing this is in text boxes?

**Comment by ekrctb** [comment]
I figured out this and indeed this is a yet another regression from my ppy/osu-framework#1611.
To reproduce this bug, first scroll mouse wheel and then press any key binding e.g. backspace.

KeyBindingContainer does access ScrollDelta on OnKeyDown but ScrollDelta is not modified except on the scroll change so previous value will be read and this produce InputKey.MouseWheelDown/Up and this simultaneous presses is ignored for SimultaneousBindingMode.NoneExact key bindings.
I'm working to only pass deltas on relevant events for now so maybe this issue will be resolved along with that.

**Comment by ticotaco72** [comment]
yeah, you can see this effect (if i understood it in good way) when you're chnaging key configuration:
when you change it takes your key and mousewheel.
