### ISSUE TITLE
"..." button in "Sort by" sometimes dont show dropdown

### ISSUE THREAD

**Issue by ktnk-dev** [ppy/osu#28732]
### Type

Cosmetic

### Bug description

In song select menu, `...` button in `Sort by` doesnt work in some cases 

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/63897347/6a758c53-1313-4281-87be-7d5ce704c9f5)

https://github.com/ppy/osu/assets/63897347/a8a6533b-10af-4ddd-9ccd-6e784103e62f

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16092941/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Will be fixed in next release.

**Comment by peppy** [comment]
For reference, where's the fix for this coming from?

**Comment by smoogipoo** [comment]
https://github.com/ppy/osu-framework/pull/6315

**Comment by ktnk-dev** [comment]
> [ppy/osu-framework#6315](https://github.com/ppy/osu-framework/pull/6315)

makes sense why it doesnt work
![image](https://github.com/ppy/osu/assets/63897347/6e014ac9-47bf-4b12-bda4-a4a2cc4b6476)
![image](https://github.com/ppy/osu/assets/63897347/6d282d48-6ddb-4596-bc5a-e9bd0f87140a)


thank you for help!<3
