### ISSUE TITLE
Song length in SongProgress Bar not following changed song length from speed-changing mods

### ISSUE THREAD

**Issue by ominoussage** [ppy/osu#28736]
### Type

Game behaviour

### Bug description

Noticed it when I was looking on the SongProgress Bar how long the song will be while I was playing. I was playing a map with DT so I expected it to be shorter but the SongProgress Bar still showed the map's normal song length (it was just counting down faster than normal)

On the beatmap carousel, it's ~2 minutes with DT but while playing, it's ~3 minutes.

I would prefer it to follow what's on the beatmap carousel since that already follows speed-changing mods. I also want it that way so that I can know what real time is left for playing a map with DT (I'm sure I'm not the only one thinking like this).

### Screenshots or videos

![osu_2024-07-04_16-47-23](https://github.com/ppy/osu/assets/105097625/ee5d79c4-1d16-4146-9ad4-4a3ee9a5e308)
![osu_2024-07-04_16-47-34](https://github.com/ppy/osu/assets/105097625/c39df845-7845-406b-8b0a-266b4eb1c816)

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16096072/compressed-logs.zip)

**Comment by bdach** [comment]
I dunno if this is an issue. See: https://github.com/ppy/osu/discussions/25255#discussioncomment-7396482.

**Comment by smoogipoo** [comment]
This is intended.
