### ISSUE TITLE
Refresh rate incorrect under dotnet on linux and macOS

### ISSUE THREAD

**Issue by morguldir** [ppy/osu#2875]
~VSync always locks the fps to 60fps, it is supposed to lock the fps to the monitor refresh rate.~
Nevermind, apparently my driver is broken

Refresh rate under dotnet is set to 50, so 2x refresh rate becomes 100 fps. This happens on linux and macOS

**Comment by peppy** [comment]
On windows it is correct, for what it's worth.

**Comment by Criminalllz** [comment]
Does vsync work properly too?

**Comment by peppy** [comment]
Yes, that's how vsync works. It's driver managed.

**Comment by morguldir** [comment]
It's a problem with OpenTK, both their git repo and the version osu uses returns the wrong refresh rate when using dotnet

Something i found on their issue tracker

> You are running OpenTK under .NET Core. This is, at the moment, an unsupported configuration and will cause issues like the above.
https://github.com/opentk/opentk/issues/756#issuecomment-388991754

It works correcly with OpenTK.NetCore from nuget, but that introduces some issues for example ambigous RectangleF references.

OpenTK is looking at supporing .netstandard2.0 in version 4.0.0 apparently.
https://github.com/opentk/opentk/milestone/10

**Comment by peppy** [comment]
For the time being we are maintaining our own [netstandard fork](https://github.com/ppy/opentk/tree/netstandard). If this is a known bug, we should probably cherry pick the fix across to our fork. Help would be appreciated with this if you feel you can!

**Comment by morguldir** [comment]
Fixed by https://github.com/ppy/opentk/pull/27

**Comment by morguldir** [comment]
Fixed by https://github.com/ppy/opentk/pull/27
