### ISSUE TITLE
.osz compatibility issue 

### ISSUE THREAD

**Issue by tadatomix** [ppy/osu#28784]
### Type

Game behaviour

### Bug description

After exporting beatmap to compatible format .osz, which using multiple curve types on slider's control points, and opening that beatmap in osu!stable, osu!stable says that beatmap header is might be corrupt and doesn't let edit or open this beatmap ever. 

I maneged to fix that, only after I removed unknown event, which appeared after I exported this beatmap in laser. Line of that unknown event:
`2,61663,140254.4347826087`

### Screenshots or videos

https://github.com/ppy/osu/assets/55669793/cd711932-d8ec-472f-8b4b-a705da67f9f9

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16137106/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Is fixed by https://github.com/ppy/osu/pull/28609 but hasn't made it into a release yet.
