### ISSUE TITLE
Lazer on android doesnt detect any file opened with "Share/Open with"

### ISSUE THREAD

**Issue by notamudkipiguess** [ppy/osu#28790]
### Type

Cosmetic

### Bug description

When trying to add a skin or beatmap with the "Share" or "Open with" button in file managers, lazer doesnt say anything about importing the file. No notifications, no new skins, no new maps, no nothing.

### Screenshots or videos

not really necessary, but basically: 
you get your osu file, click share or open with, click osu, then it basically goes "what the heck is this" and osu doesnt import anything.

### Version

2024.625-2-lazer

### Logs

[logs.zip](https://github.com/user-attachments/files/16142911/logs.zip)

**Comment by bdach** [comment]
Apparently this regressed because it only works here if the game is already open in the background and doesn't work if the game starts at the time when the file is shared to it. I'm pretty sure it used to work in both cases.

**Comment by frenzibyte** [comment]
Why has this been closed?

**Comment by notamudkipiguess** [comment]
> Why has this been closed?

Forgot about it a while ago, its fixed now

**Comment by frenzibyte** [comment]
Please **refrain** from closing the issue thread, you're not providing anything showing that a change from our side has fixed this issue, we'll handle that ourselves thank you.
