### ISSUE TITLE
Changing Break Duration continually decreases Performance.

### ISSUE THREAD

**Issue by XeZey** [ppy/osu#28794]
### Type

Performance

### Bug description

The more breaks are present, the faster the perfomance decreases. Adjusting the end of a slider if its placed before the break also causes the same effect (gamemode doesnt matter), even if it doesnt impact the duration of the break. this only happens if a break is present, which makes me assume that these two are correlated. Also, the perfomance wont decrease if the slider change is done via the timeline.
Perfomance wont recover until the editor is fully reloaded.

### Screenshots or videos

https://github.com/ppy/osu/assets/83080509/c0f7cac7-370e-45d3-ac4c-58573cddfff0

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16145721/compressed-logs.zip)

**Comment by bdach** [comment]
Already fixed in master.
