### ISSUE TITLE
Slider end volume does not save

### ISSUE THREAD

**Issue by ZenoG2** [ppy/osu#28799]
### Type

Game behaviour

### Bug description

title
note: this does not affect hitsounds. Only the volume.

### Screenshots or videos

https://youtu.be/D4hDIDH-CUY

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16158255/compressed-logs.zip)

**Comment by bdach** [comment]
Already fixed for next release.
