### ISSUE TITLE
Changing beatmap offset affects all difficulties of a beatmap set

### ISSUE THREAD

**Issue by Sukuratchi** [ppy/osu#28817]
### Type

Game behaviour

### Bug description

When changing the offset of a beatmap, it also changes the offset of all the other difficulties in that beatmap set
Also happens when using auto offset

### Screenshots or videos

Manually changing:

https://github.com/ppy/osu/assets/66184829/bf3bfaef-06c6-4a74-99be-aba3282076f2

Using auto offset:

https://github.com/ppy/osu/assets/66184829/60775e26-6574-41e2-8b26-babae785b43c

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16170168/compressed-logs.zip)

**Comment by peppy** [comment]
This is intentional. Timing is the same across all difficulties in 99.88% of beatmaps.
