### ISSUE TITLE
Changing volume with arrow buttons behaves incorrectly

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2881]
when you change volume with mousewheel and then you try to make it with arrow buttons it makes only in that direction that you have done with mousewheel regardless of whether you are pushing up/down arrow.

Possibly connected with #2872

**Comment by Joehuu** [comment]
Not connected to the referenced issue. Problem still persists in latest master.

**Comment by ekrctb** [comment]
This is an another case of my regression like #2872.
ScrollDelta is accessed in VolumeMeter.adjust.
