### ISSUE TITLE
Sudden log out

### ISSUE THREAD

**Issue by UcraNerd** [ppy/osu#28812]
### Type

Other

### Bug description

I'M SCARED
I was playing in a multi with strangers and at the end of a map, as you can see in the screenshot, my game logged me out saying that someone logged in with another device. I didn't receive a confirmation code in my e-mail (maybe cookie steal), but I already changed my password and logged in again. I don't know if it was caused by a security flaw in the multiplayer system, a random bug, or something else. It would be better if in the osu! website you could view devices where you are logged in, not only the website but also the game.

UPDATE: I run rkhunter on my local machine and didn't find any rootkit (I'm using arch linux).

### Screenshots or videos

![240427_16h21m30s_screenshot](https://github.com/ppy/osu/assets/102480084/927132e8-dbba-4b16-93ff-255aeb6ceb0b)

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16168628/compressed-logs.zip)

**Comment by Joehuu** [comment]
You are just experiencing the same issue as https://github.com/ppy/osu/issues/26338, checked logs. The notification is misleading in this case.

**Comment by UcraNerd** [comment]
> You are just experiencing the same issue as https://github.com/ppy/osu/issues/26338, checked logs. The notification is misleading in this case. Closing as duplicate.

Thx
