### ISSUE TITLE
Moving slider control points causes severely degraded performance

### ISSUE THREAD

**Issue by hiderikzki** [ppy/osu#28811]
### Type

Performance

### Bug description

I noticed my performance dropping randomly every now and then to be stuck at ~60FPS, and had to quit out of the editor to fix it, so after a couple times I just decided to track down what was causing it.

When moving a slider control point, it seems to constantly create more and more draw calls for some reason.

### Screenshots or videos

https://github.com/ppy/osu/assets/75042403/019eda32-5c29-4b98-a1ad-7dd86782d693

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16167756/compressed-logs.zip)

**Comment by bdach** [comment]
Will be fixed in next release
