### ISSUE TITLE
Performance issues modifying sliders in some maps

### ISSUE THREAD

**Issue by vicky5124** [ppy/osu#28835]
### Type

Performance

### Bug description

Modifying the length or shape of sliders in some maps drops the FPS permanently until exiting the editor.

In some maps, when the modification is stopped (even when the mouse button is still being held), the FPS return to their value before the modification of the slider started, but in some other maps, modifying a slider, drops the performance permanently until exiting the editor to the song select menu. The FPS drop does not seem to have any correlation with map length, timing settings, length of the slider, control points, position in the timeline, amount of sliders in the map or hit sound used. When creating a new difficulty on the map, utilizing the same timing point, the issue does not persist. The issue may actually happen on all maps, but with different performance drops (different difficulties of a beatmap set have different performance drops, but they all experience the permanent performance drop)

Beatmap that does not present the issue: https://osu.ppy.sh/beatmapsets/1016145
Beatmap that presents the issue extremely: https://osu.ppy.sh/beatmapsets/648360
Beatmap that presents the issue slightly: https://osu.ppy.sh/beatmapsets/690556
Beatmap set that presents different levels of the issue: https://osu.ppy.sh/beatmapsets/1214150

The issue persists with different renderers (Tried OpenGL, Vulkan (Exp) and OpenGL (Exp)).
Memory RES usage does not seem to be affected by this issue, it increases by 2 MB at most.
I do not think #23658 is related, but it may also be worth a look.

### Screenshots or videos

Uploaded on YouTube due to large filesize: https://youtu.be/yT3sV1ugttY

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16199434/compressed-logs.zip)

**Comment by Joehuu** [comment]
Already fixed by https://github.com/ppy/osu/pull/28621.
