### ISSUE TITLE
flashing black bars then crashing whenever i try to play

### ISSUE THREAD

**Issue by mifluffy** [ppy/osu#28842]
### Type

Crash to desktop

### Bug description

when i complete a play it doesn't make it to the score screen and instead flashes black bars and then crashes. Afterwards if i try to boot it up again and play a beatmap the same thing happens where it crashes. This bug has only been going on for like the last 2 days for me. Randomly it gets better where i can play a beatmap but still crashes when i get to the score screen.
The video didnt capture the flashing bars for some reason.

### Screenshots or videos

https://github.com/user-attachments/assets/57774c10-c57b-47b9-89da-fa812b855a85

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16200195/compressed-logs.zip)

**Comment by nisheri-ascar** [comment]
Is your graphics driver on latest? If not try updating it
