### ISSUE TITLE
"sort by" dropdown menu can be only activated by clicking on the left side of button

### ISSUE THREAD

**Issue by Guanran928** [ppy/osu#28850]
### Type

Other

### Bug description

Reproduce steps:
1. go to song selection screen
2. click on the "..." beside "sort by"

System info:
https://linux-hardware.org/?probe=828ea2e910

### Screenshots or videos

https://github.com/user-attachments/assets/ff18b0ec-2b75-4df5-9a9f-6cd53ca50bd2

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16201963/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Will be resolved next release.
