### ISSUE TITLE
Sort filter dropdown button on song select having limited trigger area

### ISSUE THREAD

**Issue by ominoussage** [ppy/osu#28857]
### Type

Game behaviour

### Bug description

The button that shows the other filters for sorting beatmaps on song select (three dots button).

The dropdown only shows up if you click at the left side of the button. Clicking everywhere else does not trigger the dropdown. Custom UI scaling and custom window size does not fix it.

### Screenshots or videos

https://github.com/user-attachments/assets/699969f2-5312-4050-a834-4d536d4ac8d1

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16215814/compressed-logs.zip)

**Comment by Joehuu** [comment]
Already fixed in https://github.com/ppy/osu-framework/pull/6315.
