### ISSUE TITLE
Texture glitches on Intel HD Graphics 3000

### ISSUE THREAD

**Issue by NamOpt** [ppy/osu#28869]
### Type

Performance

### Bug description

Just open the game, and wolla! The glitch is appear.

### Screenshots or videos

![20240715_150342.jpg](https://github.com/user-attachments/assets/78af1815-dc10-4204-aeb0-17d68d3b951f)

### Version

lastet

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16231642/compressed-logs.zip)

**Comment by Stoppedpuma** [comment]
See if changing your renderer to "OpenGL" fixes this.

**Comment by NamOpt** [comment]
Video: https://drive.google.com/file/d/1m9Y8B3HSBEF0_KulnjwRNXcNMwYCXQ1B/view?usp=drivesdk

**Comment by frenzibyte** [comment]
Make sure your graphics drivers are up to date, and also try other renderers as mentioned above.

**Comment by NamOpt** [comment]
I have updated my video card to the latest version and tried another render, still the same problem

**Comment by NamOpt** [comment]
I have updated my video card to the latest version and tried another render, still the same

**Comment by smoogipoo** [comment]
Try running the game with the environment variable: `OSU_SDL3=1`

I don't (yet) recommend keeping this on, but it would be a good test to see if it fixes it.

**Comment by NamOpt** [comment]
After switching to **OpenGL**, the game did not open at all, **there was no error message, and no logs were recorded.**

**Comment by smoogipoo** [comment]
Check if there are any error logs in the event viewer (https://docs.microsoft.com/en-us/host-integration-server/core/how-to-check-the-windows-event-logs-for-errors1).

**Comment by NamOpt** [comment]
Log Name:      Application
Source:        .NET Runtime
Date:          7/18/2024 9:54:25 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-2R9N046
Description:
Application: osu!.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at osuTK.Graphics.ES30.GL.UseProgram(Int32)
   at osu.Framework.Graphics.OpenGL.GLRenderer.BeginFrame(osuTK.Vector2)
   at osu.Framework.Graphics.Rendering.Renderer.osu.Framework.Graphics.Rendering.IRenderer.BeginFrame(osuTK.Vector2)
   at osu.Framework.Threading.DrawThread.OnInitialize()
   at osu.Framework.Threading.GameThread.Initialize(Boolean)
   at osu.Framework.Threading.GameThread.<createThread>g__runWork|66_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-07-18T16:54:25.529903400Z" />
    <EventRecordID>28219</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-2R9N046</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at osuTK.Graphics.ES30.GL.UseProgram(Int32)
   at osu.Framework.Graphics.OpenGL.GLRenderer.BeginFrame(osuTK.Vector2)
   at osu.Framework.Graphics.Rendering.Renderer.osu.Framework.Graphics.Rendering.IRenderer.BeginFrame(osuTK.Vector2)
   at osu.Framework.Threading.DrawThread.OnInitialize()
   at osu.Framework.Threading.GameThread.Initialize(Boolean)
   at osu.Framework.Threading.GameThread.&lt;createThread&gt;g__runWork|66_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          7/18/2024 9:54:26 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-2R9N046
Description:
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x66470000
Faulting module name: coreclr.dll, version: 8.0.624.26715, time stamp: 0x66479681
Exception code: 0xc0000005
Fault offset: 0x00000000001cca96
Faulting process id: 0x2268
Faulting application start time: 0x01dad933203ab914
Faulting application path: C:\Users\Administrator\AppData\Local\osulazer\app-2024.625.2\osu!.exe
Faulting module path: C:\Users\Administrator\AppData\Local\osulazer\app-2024.625.2\coreclr.dll
Report Id: ec8fe8bc-c0dc-461a-8b64-3699fa256053
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-07-18T16:54:26.030198600Z" />
    <EventRecordID>28220</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-2R9N046</Computer>
    <Security />
  </System>
  <EventData>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>66470000</Data>
    <Data>coreclr.dll</Data>
    <Data>8.0.624.26715</Data>
    <Data>66479681</Data>
    <Data>c0000005</Data>
    <Data>00000000001cca96</Data>
    <Data>2268</Data>
    <Data>01dad933203ab914</Data>
    <Data>C:\Users\Administrator\AppData\Local\osulazer\app-2024.625.2\osu!.exe</Data>
    <Data>C:\Users\Administrator\AppData\Local\osulazer\app-2024.625.2\coreclr.dll</Data>
    <Data>ec8fe8bc-c0dc-461a-8b64-3699fa256053</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by smoogipoo** [comment]
That looks like a driver issue. 

- Check if there are any driver updates available for your system.
- Provide a [dxdiag log](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe).
- Additionally, I'm not sure HD 3000 is even supported on Windows 10, so you'll likely have to wait for future work/fixes.
