### ISSUE TITLE
Editor precise Scale and Rotate tools starts blinking when hovering over right toolbox

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#28865]
### Type

Game behaviour

### Bug description

If you use 1.0x UI scaling, open the precise scale or rotate tool popover, scroll to the top of the right toolbox, and hover the right toolbox, the popover starts rapidly blinking back and forth every frame.

### Screenshots or videos

Due to the framerate of the recording you can't see how it moves back and forth every frame.

https://github.com/user-attachments/assets/80f8bc53-a981-41bd-8acd-33b9c4db89b2

### Version

current master branch 14/07/2024

### Logs

n/a

**Comment by frenzibyte** [comment]
I thought this was gonna be a simple reordering of containers, but never mind...
