### ISSUE TITLE
Changelog overlay

### ISSUE THREAD

**Issue by jorolf** [ppy/osu#2886]
Now that the changelog page has been implemented on the website we can consider including it in the client.
![twitterpost](https://user-images.githubusercontent.com/12570757/41904586-0d9a6a6a-7939-11e8-9854-ea3bd9d52b75.png) (taken from twitter)

- [ ] Build Header
![header](https://user-images.githubusercontent.com/12570757/41905366-3ec37418-793b-11e8-96ff-91ce94e8d237.png)
If the json on the website is the one being returned it should look something like this:
![headerjson](https://user-images.githubusercontent.com/12570757/41905631-0d84f542-793c-11e8-8780-e62a5e3f185b.png)
Important are:
  - display_version: obvious
  - users: this should probably be hidden when users == 0
  - is_featured: if the "panel" should be wide (?)
  - update_stream.display_name: obvious

  This object is inside an array which contains one for every build stream. The order of the array should probably match up with what's being shown.
~~**I'm unsure how the colour should be decided.**~~ Edit: Colours are going to be hardcoded for now until web returns them

- [ ] Chart
![chart](https://user-images.githubusercontent.com/12570757/41906070-2dc21b40-793d-11e8-8aba-4e93211f0590.png)
~~Same problem as the header: How should the colours be decided?~~
I also don't know how this could be drawn, but it should probably be buffered.
- [ ] Changelog
![changelog](https://user-images.githubusercontent.com/12570757/41910593-681f1362-794a-11e8-989f-da862f317d31.png)
The changelog json object is simlar to the one of the header but has an additional array containing the changes
![changelogjson](https://user-images.githubusercontent.com/12570757/41910678-abdbf7dc-794a-11e8-8e62-2450854d9b82.png)
  - type: the type of the change: fix (*), add (+) and probably misc (?)
  - category: categories are grouped
  - message_html: contains an additional message which also contain pictures, this somehow has to be converted to something usable in lazer

**Comment by peppy** [comment]
You can get most all the information you need from `osu-web`, which is open source and has implementation details.

**Comment by jorolf** [comment]
I'd guess that the request should return markdown instead of html... which also means that we'd need a Markdown parser

**Comment by HoutarouOreki** [comment]
Are there any updates on the design apart from this?
![image](https://user-images.githubusercontent.com/3632750/42498208-88e92566-8466-11e8-9b43-f502950bb311.png) ![image](https://user-images.githubusercontent.com/3632750/42498220-8f426468-8466-11e8-82dc-7cec30d010ea.png) 
![image](https://user-images.githubusercontent.com/3632750/42498216-8d13436a-8466-11e8-9476-cf7dcc209fa5.png)

**Comment by HoutarouOreki** [comment]
Are there any updates on the design apart from this?
![image](https://user-images.githubusercontent.com/3632750/42498208-88e92566-8466-11e8-9b43-f502950bb311.png) ![image](https://user-images.githubusercontent.com/3632750/42498220-8f426468-8466-11e8-82dc-7cec30d010ea.png) 
![image](https://user-images.githubusercontent.com/3632750/42498216-8d13436a-8466-11e8-9476-cf7dcc209fa5.png)

(in case I missed anything that's also meant to be implemented on web, but isn't)
