### ISSUE TITLE
osu!direct beatmap cards don't get removed

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#2888]
<img width="1248" alt="screen shot 2018-06-27 at 4 32 20 pm" src="https://user-images.githubusercontent.com/1329837/41959377-ba8af052-7a27-11e8-8273-4edfcaf63f8a.png">

They're supposed to get removed when the download completes, but they're remaining in a "downloading" state, although the beatmaps have been imported.

**Comment by peppy** [comment]
Been this way for ages, not even sure it can be called a regression. Also I don't mind the behaviour; it's really jarring to have them disappear completely. Could probably do with a different colour for the bar once completed, though.

**Comment by naoey** [comment]
Shouldn't there be a filter option to show/hide maps that have already been downloaded?

**Comment by smoogipoo** [comment]
This broke within the last 3 weeks. I'm calling this a regression based on just that.

Furthermore, the cards don't hide even when you enter osu!direct with the beatmaps. They just sit there without a download button.

I would prefer that beatmaps do get hidden when you have them. It's much easier to tell which beatmaps you have when they're not there.

**Comment by peppy** [comment]
Having an option to hide them would be fine, but the default should not be hidden. We are aiming to have a similar experience to the website.

That said, it should be easily distinguishable that they are downloaded.

**Comment by naoey** [comment]
It's been discussed to change the download button on the cards to "open" buttons in #2731

**Comment by arflyte** [comment]
![74a06df428](https://user-images.githubusercontent.com/3632750/42023766-a06b8266-7afb-11e8-90bb-1a7be8ae0cff.png)

Download state indicators. Press grey button to download, changes to blue when download in progress (with slow fading-in-out icon). Downloaded maps green button with a checkmark; clicking the beatmap tile will take player to the song select screen.

**Comment by naoey** [comment]
How should the button look in the list view (as in the image below) of the direct overlay? Replacing the current button with this would make a big green/blue/grey box that looks odd.

![image](https://user-images.githubusercontent.com/3889501/42222682-78edeb92-7ef3-11e8-89e1-34053fbbd9a3.png)

**Comment by peppy** [comment]
For the time being add it somewhere I guess.

**Comment by naoey** [comment]
Have better screenshots now. Drop in replacement to the existing button would look like this:

![image](https://user-images.githubusercontent.com/3889501/42225055-44e8f85e-7ef9-11e8-973b-c5f1905c0de9.png)

![image](https://user-images.githubusercontent.com/3889501/42225076-502c61b0-7ef9-11e8-9714-72e4faa84e90.png)

**Comment by peppy** [comment]
I think this is fine for now.
