### ISSUE TITLE
Grid rotation does not save. (editor)

### ISSUE THREAD

**Issue by ZenoG2** [ppy/osu#28895]
### Type

Game behaviour

### Bug description

title

### Screenshots or videos

https://youtu.be/JAcqn3C9IN8

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16270552/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Known issue, see: https://github.com/ppy/osu/pull/28473

**Comment by frenzibyte** [comment]
Let's just mark this as a duplicate of https://github.com/ppy/osu/issues/20883
