### ISSUE TITLE
About mania touching input system

### ISSUE THREAD

**Issue by DrrrrrrZM** [ppy/osu#28894]
The new touching input system (in the picture) is not suitable for everyone. Please create a mania touching input system option in the next version.(Just remain the old or use new input system)
![Screenshot_2024-07-17-22-09-03-405_com android browser-edit](https://github.com/user-attachments/assets/53c99c53-e4fb-4b80-a10f-49a707b733cb)

_Originally posted by @DrrrrrrZM in https://github.com/ppy/osu/discussions/28893_

**Comment by frenzibyte** [comment]
Please keep this as a discussion thread, we will create an issue thread when applicable.
