### ISSUE TITLE
PP rounding difference in lazer and web

### ISSUE THREAD

**Issue by ondatraCZ** [ppy/osu#28914]
### Type

Game behaviour

### Bug description

PP in lazer replay summary is rouned differently than on the web.  When the pp is x.56 and smaller in lazer its rounded down on the web its up.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/27b9e1f7-53b5-477d-9d5e-3c4a7307607c)
![image](https://github.com/user-attachments/assets/2081ff00-a107-4f63-8344-7bb2cd29dcff)
![image](https://github.com/user-attachments/assets/ece05f27-f7e3-4e5d-aa8e-9cda910ee5d8)
![image](https://github.com/user-attachments/assets/d1bfe564-3763-4a75-8493-9f7b5bd25dd1)

![image](https://github.com/user-attachments/assets/e50d4510-a2ec-40a2-a846-e8a7d0dd9068)
![image](https://github.com/user-attachments/assets/df800aa3-0a49-4e4a-b5de-ff13b2995fca)

### Version

2024.718.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16283532/compressed-logs.zip)

**Comment by peppy** [comment]
I'm pretty sure you'll find that they are both using different algorithms, rather than this being a rounding consideration.

**Comment by ondatraCZ** [comment]
> I'm pretty sure you'll find that they are both using different algorithms, rather than this being a rounding consideration.

Yea, you are right the values are different even before rounding.
![image](https://github.com/user-attachments/assets/97db32fb-bad4-4200-8843-3fc15a504d2c)
![image](https://github.com/user-attachments/assets/f97f667f-b7c6-4c35-aba7-4903220c7db5)

**Comment by smoogipoo** [comment]
As above - it doesn't look like there's anything actionable here.
