### ISSUE TITLE
No Release mod completely bugs the skin animation for a hold note hit

### ISSUE THREAD

**Issue by Matheus493943** [ppy/osu#28918]
### Type

Game behaviour

### Bug description

When using No Release, if the hold note is over when held down, the game uses the note hit animation but never deletes it causing it to loop forever

### Screenshots or videos

https://github.com/user-attachments/assets/ac6ce38c-c358-4314-9b30-572add2422e0

(sorry for bad quality)

### Version

2024.718.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16284615/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Will be fixed in the next release https://github.com/ppy/osu/pull/28905
