### ISSUE TITLE
Phantom control points in skin editor

### ISSUE THREAD

**Issue by vatei** [ppy/osu#28911]
### Type

Game behaviour

### Bug description

After opening the skin editor and not touching anything, there are control points stacked together in the top left corner, as if a super small object was already selected.
I tried switching to multiple skins to make sure it wasn't due to a bad object placement on my part, but the issue is still there no matter the skin.

### Screenshots or videos

![osu_TimlFJXliT-cut](https://github.com/user-attachments/assets/1b820bb3-cd5d-4bea-bdc1-eb09a4229b11)

### Version

2024.718.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16282042/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Those are just selection box drag handles incorrectly being visible.
