### ISSUE TITLE
Performance dropping when clicking to go to beatmaps

### ISSUE THREAD

**Issue by iLelesan** [ppy/osu#28913]
### Type

Performance
### Bug description

when clicking on the solo option the game freezes and goes to the beatmaps

### Screenshots or videos

https://github.com/user-attachments/assets/29dafb6a-15e9-43e0-b7b8-55caeaeb41cd

### Version

2024.718.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16283412/compressed-logs.zip)

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/issues/28929 received more activity than this so closing as duplicate
