### ISSUE TITLE
Taskbar right-click menu not opening

### ISSUE THREAD

**Issue by MegaGamer22** [ppy/osu#28927]
### Type

Other

### Bug description

THIS ONLY HAPPENS WITH OSU!LAZER.
I updated the game and another osu icon appears on my taskbar and not the one that's pinned. I tried to unpin it but the right-click menu does not appear. This also makes the taskbar not hide on fullscreen until I restart the explorer.

### Screenshots or videos

https://github.com/user-attachments/assets/0379b19d-69ce-49f2-af46-173f37741482

### Version

2024.718.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16288288/compressed-logs.zip)

**Comment by frenzibyte** [comment]
This is supposed to have been resolved long ago by https://github.com/ppy/osu/pull/17972 but apparently it regressed? cc @peppy @caesay

**Comment by peppy** [comment]
I believe it will be fully fixed once we move away from squirrel to velopack (right now pinning is a mess due to the main executable's path changing per-update).

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/28743.
