### ISSUE TITLE
After pausing osu!, the game doesn't detect the first input after

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu#28931]
### Type

Game behaviour

### Bug description

Problem details: While playing osu!standard i had to pause the game in a section for whatever reason and i discovered what i think is a bug. Basically - when you pause the game while holding b1 or b2 (aka z and x), after resuming the game, the game still holds your button. The game holds your button for you, until you give another imput, or when you stop holding a button - and since the game holds the button for you, you have to click before clicking on another note, because if you click only on the note the game just stops holding the imput, and doesn't detect a another one. This might be a intentional mechanic, but i decided to report it just in case

Copy of: https://osu.ppy.sh/community/forums/topics/1950626 requested by - Marco -(https://osu.ppy.sh/users/1273955)

### Version

osu! version: Lazer 2024.718.0 (latest)

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16290004/compressed-logs.zip)

**Comment by MegaGamer22** [comment]
What I noticed about this is that you could press and hold a key for when the countdown ends, now it seems that they removed that. An early input will guarantee a miss.

**Comment by frenzibyte** [comment]
When pausing while a key is held then resuming while the same key is still being held, releasing said key should work, but it seems that that part has regressed for some reason...

**Comment by Tenexxt** [comment]
> When pausing while a key is held then resuming while the same key is still being held, releasing said key should work, but it seems that that part has regressed for some reason...

Yea, that also doesn't work for some reason, but also when you hold, pause and while the game is paused you stop holding, after you resume your input is still not being counted, unless you click two times (one to stop the hold, 2 to hit the note)

**Comment by frenzibyte** [comment]
This is intentional, the game should not give you advantage of performing a click at the point of resuming gameplay. There are only two valid scenarios:
1. You resume while no key was being held at pause, at which point no input will be triggered.
2. You resume while a key was held at pause (e.g. for sliding in a slider), at which point holding that same key at resume should keep it held, and releasing it before resume should release at point of resume.

**Comment by Tenexxt** [comment]
> 2. You resume while a key was held at pause (e.g. for sliding in a slider), at which point holding that same key at resume should keep it held, and releasing it before resume should release at point of resume.

The problem is that it doesn't stop holding in 2, and as you mentioned before - still holding while the game is paused, resuming with the hold, and releasing the key also doesn't work. So basically the pause is not giving the expected result. As I tested this only on standard, I'll see if this happens in other gamemodes while doing this.

**Comment by Tenexxt** [comment]
> This is intentional, the game should not give you advantage of performing a click at the point of resuming gameplay.

 I must've worded it incorrectly, because that's what I also meant - if you stop holding, the game stops holding, I'd you don't, it continues. I didn't meant to add a click on moment of resume, but as mentioned in my last comment - I tested this for every gamemode (now I did, didn't before), and it works correctly, but is very easy to see it in mania. Pick a map that starts with a slider and try performing these 3 things:
1. Hold and pause before the slider. When you resume you don't hold the button anymore - Result: as expected, the game stops holding the button
2. While holding the slider, pause and let go of the button - Result: when resumed, as expected, the game let's go of the button
3. While holding the slider, pause and after you stop holding it, hold it again before resume, or just hold it already - Result: when resumed, as expected, the game holds the button.

But in standard for whatever reason If we apply any of these points to it, it doesn't give the same, correct and expected result.

**Comment by frenzibyte** [comment]
> The problem is that it doesn't stop holding in 2

I'm aware already, this is why I kept the issue thread open and assigned myself.

> But in standard for whatever reason If we apply any of these points to it, it doesn't give the same, correct and expected result.

This is probably caused by the click-to-resume step in standard, but good observation.
