### ISSUE TITLE
screen recorders can't record osu!lazer

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2893]
After one of last updates every recording from obs looks like this:
https://drive.google.com/open?id=1Zay_zT4OPqPJPEjaO8wdvKSHno71YjeM
i think it's not fault of obs, because it was working fine, and there was'nt update for obs since that time.

**Comment by ekrctb** [comment]
Cannot reproduce. Did you try again on an older version of osu!lazer and it worked?

**Comment by ticotaco72** [comment]
It was working nice week ago.
How can i install older version on windows? - it is making update itself

**Comment by ekrctb** [comment]
Just download install.exe and install from https://github.com/ppy/osu/releases should be working I think.

**Comment by ticotaco72** [comment]
it isn't working with 2018.618.0

**Comment by ekrctb** [comment]
Do you remember (or you can probably inspect file info of a recording) when it is working? Try a version around that date and if it isn't working on that version then the problem is yours and not osu!lazer.

**Comment by ticotaco72** [comment]
it isn't working on 2018.622.0 which was best.
sorry for making problem
