### ISSUE TITLE
mod multiplier color is swapped

### ISSUE THREAD

**Issue by Revivess** [ppy/osu#28940]
### Type

Cosmetic

### Bug description

multiplier is red when should be green and green when should be red
could be intended idk

### Screenshots or videos

![osu_2024-07-18_20-43-16](https://github.com/user-attachments/assets/af16f901-35ea-4011-a25d-ef63171d7d9b)
![osu_2024-07-18_20-43-22](https://github.com/user-attachments/assets/63b3a440-8c21-4036-8a39-bcecb67b3a34)

### Version

2024.718.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16300973/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Red means difficult, green means easy. This is already displayed as such in mod select overlay, and also partly the same in adjusted beatmap difficulty attributes.

Open a discussion thread if you want to discuss this further.
