### ISSUE TITLE
osu! scoring bug - not recognizing latest version as the latest one

### ISSUE THREAD

**Issue by XxBojitoxX** [ppy/osu#28960]
### Type

Game behaviour

### Bug description

When entering any beatmap in the game I am being met with the error "Please ensure that you are using the latest version of the official game releases. Your score will not be submitted."
This started happening after the latest update of osu!lazer.
OS Version: Windows 11 23H2

### Screenshots or videos

![image](https://github.com/user-attachments/assets/9518ebd8-4165-4274-a8a3-6edd83a15b42)

https://github.com/user-attachments/assets/4b7535ae-3f70-4cb8-a81d-dd2c31a54b9a

### Version

2024.718.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16317586/compressed-logs.zip)

**Comment by smoogipoo** [comment]
This issue has been reported for a while now. Unfortunately there's not much we can really investigate at this point, for a few more days.

The solution seems to be to restart your PC. Please report back if it still happens after that.
