### ISSUE TITLE
0 length taiko sliders behave differently from stable

### ISSUE THREAD

**Issue by Zoggoth** [ppy/osu#2896]
04:20:057 timestamp on [this map](https://osu.ppy.sh/beatmapsets/481441) (fixed link, thanks AlFasGD)

The 0 length sliders in this sections are converted to circles in gameplay

**Comment by AlFasGD** [comment]
Map appears unavailable, perhaps you might intend to remove the 0 from the link provided.

**Comment by nyquillerium** [comment]
part of https://github.com/ppy/osu/issues/750

**Comment by nyquillerium** [comment]
actually seems to be fixed, let me know if this is not the case
