### ISSUE TITLE
osu! iOS build 2024.718.0+ crashing on startup

### ISSUE THREAD

**Issue by Star-Clara** [ppy/osu#28977]
### Type

Crash to desktop

### Bug description

Force quit on my iPados device:
iPad Air 5:iPadOS 18.0 developer beta 3
The application can’t start successfully.

### Version

latest(2024.718.0/2024.718.1)

### Logs

[1721492295.runtime.log](https://github.com/user-attachments/files/16321698/1721492295.runtime.log)
[1721492295.network.log](https://github.com/user-attachments/files/16321699/1721492295.network.log)
[1721492295.input.log](https://github.com/user-attachments/files/16321700/1721492295.input.log)
[1721492295.auth.log](https://github.com/user-attachments/files/16321701/1721492295.auth.log)

**Comment by mik3se** [comment]
Can confirm.
Release [2024.625.2](https://github.com/ppy/osu/releases/tag/2024.625.2) and prior work on my device

Can see splash screen beggining to load, sometimes the beginning of the "Welcome to osu!" audio can be heard
Will attach log files upon request, though OPs should be sufficient

### Device Information
Device: iPhone 13 Pro Max
System Software: iOS 15.7 w/ Dopamine rootless jailbreak
IPA sideloaded with TrollStore

### Video
https://github.com/user-attachments/assets/5758a45d-48b2-4349-8604-f3d2c89798bf

**Comment by TorriFwu** [comment]
Can’t get inside the game. The game forceclosing by itself when i try to open the newest update 2024.781.01 

**DEVICE**
Iphone Xr
IOS. 17

I download from Ipa using Esign. Even scarlet. I try both of it but it just forceclosing:/. Sometimes the audio can be heard like the comment before.

Uploading RPReplay_Final1721520076.mp4…

**Comment by peppy** [comment]
This is the reason we haven't pushed the build out to testflight. Please use a previous release. I'll pull the IPA to stop people hitting this.

**Comment by peppy** [comment]
Unfortunately still an issue even on the latest deploy. 🙄

**Comment by Joehuu** [comment]
Fixed in latest release.
