### ISSUE TITLE
Score changes after the replay is watched

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu#28974]
### Type

Game behaviour

### Bug description

Basically, the score overall, and my rating for one score change after watching a replay for a certain score, and i thought that its some sort of bug for the scoring system or something, or that before watching the replay the game doesn't judge as intended because the timing values dont match. i dont care about the score change, i have a better score anyway, but i wanted to report this so that the issue doesn't repeat in later versions 
_(im kind of impressed i clicked so perfectly somewhere that the game is confused about the score)_

### Screenshots or videos

https://github.com/user-attachments/assets/425c9404-9128-41fb-a9e6-5f49fac86392

### Version

osu! version: Lazer 2024.718.1 (the score was set on a different version, but the issue stayed)

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16321393/compressed-logs.zip)

**Comment by bdach** [comment]
Many other issues about this sort of thing exist already, closing as duplicate
