### ISSUE TITLE
The "osu!" button ticks at 60 bpm while songs are paused

### ISSUE THREAD

**Issue by MeerukYang** [ppy/osu#28988]
### Type

Game behaviour

### Bug description

it can be seen clearly in the attached video.
when pause the song that is currently playing, place the cursor on the "osu!" button and it still ticks. the button ticks at 60 bpm and this doesn't change no matter the paused song's bpm. 
the button only would tick at the song's bpm if resume playing the song (by using shortcut keys etc).
**but it should just freeze and be silent when the song being paused.**

### Screenshots or videos

https://github.com/user-attachments/assets/3a2cf3d2-53c5-4e0f-88d0-b2697e6e22a9

### Version

2024.718.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16325179/compressed-logs.zip)

**Comment by bdach** [comment]
Intentional
