### ISSUE TITLE
Some visual differences between Lazer and Stable in osu!catch

### ISSUE THREAD

**Issue by its5Q** [ppy/osu#28997]
### Type

Cosmetic

### Bug description

I've tried osu!catch in Lazer and it felt just a little bit off compared to Stable, so I decided to compare them side by side by playing the same map and there are several discrepancies between the two.
1. Dash trail effect intervals are much larger in Lazer than in Stable. This takes away some sense of speed when dashing.
2. Hyperdash intervals in Lazer are lower than regular dashes, when in Stable the interval is constant, so when you hyperdash, the distance between trail afterimages is larger in Stable, but in Lazer it's the same.
3. Albeit minor, I think it should also be mentioned - the fade speed of bounced fruits and droplets are a bit quicker than stable.

I think it's important to be as close as possible to Stable in terms of gameplay visuals so people have a smoother experience switching to Lazer.

#### Stable vs Lazer dash
![Stable vs Lazer dash](https://github.com/user-attachments/assets/acd6a320-3875-422c-920d-a81358e01ffa)

#### Stable vs Lazer hyperdash
![Stable vs Lazer hyperdash](https://github.com/user-attachments/assets/9b4f2644-3f37-4cf8-a2fc-648231b7ad8b)

### Version

2024.718.1

### Logs

Not applicable

**Comment by Smoodie7** [comment]
I think is something they did on purpose, personally i dont play osu!catch but i prefer Lazer visuals.

**Comment by its5Q** [comment]
I'd love to hear more opinions on this, and if the trail should be changed to look more like it does in Stable.

**Comment by peppy** [comment]
> Albeit minor, I think it should also be mentioned - the fade speed of bounced fruits and droplets are a bit quicker than stable.

This will require a bit more attention (ie. implementing local gravity rather than using fixed transforms to match stable).  Probably best to open a separate issue for it if you consider it important.
