### ISSUE TITLE
Tutorial task: Key Counter

### ISSUE THREAD

**Issue by peppy** [ppy/osu#29]
This is a task everyone should attempt before diving in.

Because the lazer code-base is under very rapid refactoring, your task is to create an osu!next inspired UI element in the scratch area (use TestCaseScratch and probably create your own TestCaseKeyCounter before pull requesting). You should design all classes to be decoupled (they don't have knowledge of their calling site).

![](https://puu.sh/pMc1v/da2032c891.png)

Implement this key counter (from scratch).
- The KeyCounter itself should have an `IsCounting` property which can be set by the parent class to decide whether counts should be incremented or not.
- Initialisation of the KeyCounter should allow for different buttons to be added dynamically. Like so:

```
KeyCounter kc = new KeyCounter();
kc.AddKey(new KeyboardCount(@"Z", Key.Z));
kc.AddKey(new KeyboardCount(@"X", Key.X));
kc.AddKey(new MouseCount(@"M1", MouseButton.Left));
kc.AddKey(new MouseCount(@"M2", MouseButton.Right));
Add(kc);
```
- `KeyboardCount : Count` and `MouseCount : Count`. `Count : Drawable` and will contain the draw logic for a single counter.
- `KeyboardCount` and `MouseCount` will contain the increment logic by overriding mouse or keyboard events within themselves. make sure to return false when handling input so we can still pass the input back to the rest of the game.
- The font used by this counter is not yet in-game. Just use the default provided by SpriteText (for the counter) and FontText (for the key name) for now.
- `KeyCounter` and `Count` will need a special override to handle events outside of its drawable bounds. See [this comment](https://github.com/peppy/osu-lazer/issues/77#issuecomment-230079268) for more info.

You should start with the smallest part first (`Count`) and work outwards. Make the Count appear correctly with the key name and current count. make the on-press and on-release as a state property `IsLit` and have it apply a nice looking tween between states.

Once you have the `Count` class done and working, make the `KeyboardCount` and `MouseCount`, which will add input handling logic depending on the source, toggling the `IsLit` state.

Once you have all the necessary count types, make the KeyCounter container. It should use FlowContainer to arrange the four counts into the final layout.

To become familiar with Anchor and Origin settings, my [blog post](http://blog.ppy.sh/post/140087699883/sprites-and-containers-in-osu) may help.

Avoid specifying pixel locations and use a `FlowContainer` or `SizeMode`/`InheritMode.XY` to get relative support.

Ask any questions at all in this thread. This is intended to be a self-guided tutorial for future audiences, so I want to make it as straight-forward as possible. Your feedback will help improve on this process.

**Comment by peppy** [comment]
Required resources:

[key_glow.png](https://cloud.githubusercontent.com/assets/191335/16511430/17abe536-3f8b-11e6-9039-dcfbbf1dacaf.png)
[key_glow@2x.png](https://cloud.githubusercontent.com/assets/191335/16511434/17ac76ea-3f8b-11e6-88cc-eae0715ae460.png)

[key_hit.png](https://cloud.githubusercontent.com/assets/191335/16511435/17acd2f2-3f8b-11e6-8b50-5fccba819ce5.png)
[key_hit@2x.png](https://cloud.githubusercontent.com/assets/191335/16511433/17ac468e-3f8b-11e6-8cfc-580148fa103e.png)

[key_up.png](https://cloud.githubusercontent.com/assets/191335/16511432/17ac5232-3f8b-11e6-95b7-33f9a4df0b7c.png)
[key_up@2x.png](https://cloud.githubusercontent.com/assets/191335/16511431/17ac116e-3f8b-11e6-8a9e-e01a5d2ab1bf.png)

**Comment by JFRN** [comment]
Excuse my ignorance, but where is the scratch area? I didn't understand the part of `TestCaseScratch`. Is it in `osu.Desktop.VisualTests`?

**Comment by peppy** [comment]
sorry, this is a bit outdated since i copied the text from the old repo. you can just make a new TestCaseKeyCounter and treat that as scratch!

**Comment by UselessToucan** [comment]
Hello.
I am trying to create key counter and I need help with drawing.
As far as I understand, the first thing I should do is to load resourses in my Counter class(something like `Game.Textures.Get(@"<name>")`, Game = field of type Game in Drawable class).
The problem is that Game is null(when I call it from Load method in my Counter class).
[Here is what I have now(Did not PR because it is not completed yet)](https://github.com/UselessToucan/osu/commit/cefd426461f211b25a149144732c6511a5c85636)


I also would like to clarify something about Key Counter design. As far as I understand, KeyCounter class itself is a container for specific counters. Should it provide access to these specific counters somehow?(for example, by index like kc[2])

**Comment by huoyaoyuan** [comment]
@UselessToucan Currently if a `Drawable` is Loaded immediately after added to a `Container`, but if the `Container` haven't been added to the game, the `Game` will be null. So you should add the `Container` to the game first(to `TestCase` for example), then add keys to it. This behavior may be changed later.

**Comment by UselessToucan** [comment]
#42

**Comment by lunafreya** [comment]
Did the key counter got implemented already?
