### ISSUE TITLE
Dragging select in Timing tab textboxes will not affect by your clicking position

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#29009]
### Type

Game behaviour

### Bug description

Hi. As you can see in this video, when you drag in the BPM/Offset textbox (which you're not focused on) to select the number, it doesn't implement your dragging position and uses very first position of the textbox instead.
I know it might be intended, but this is a normal thing in other apps and UI's, so people might find it uncomfortable to work.

https://github.com/user-attachments/assets/174c7f85-1570-429c-ba44-0af5430085b2

### Version

2024.718.1

### Logs

No need

**Comment by bdach** [comment]
Drag works correctly in other text boxes. This is a regression from https://github.com/ppy/osu/pull/28805. @frenzibyte
