### ISSUE TITLE
Replay score shows abnormal than actual play score

### ISSUE THREAD

**Issue by MizuIro-H** [ppy/osu#29007]
### Type

Game behaviour

### Bug description

as the title said, when you replay a score(whether it was played by lazer or stable) with lazer, it will show a score that isnt the actual play score and pp.
video below shows what happens.

### Screenshots or videos

https://github.com/user-attachments/assets/bd6beb51-76c9-48ea-8a6b-83da54925fde

### Version

2024.718.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16336984/compressed-logs.zip)

**Comment by bdach** [comment]
Many duplicates of this open already, without a replay I see no point having this open too

**Comment by MizuIro-H** [comment]
In my point of view almost every replay can cause this so I think no need for a paticular replay file.
