### ISSUE TITLE
SS Rank in osu!mania should cover scores that has 300/Great judges instead of only MAX/Perfect

### ISSUE THREAD

**Issue by MizuIro-H** [ppy/osu#29002]
### Type

Game behaviour

### Bug description

Just as the title said.
The reason is that i think it should keep the same behavior as Stable.
Otherwise, you can also choose to change back to v1 Accuacy system, which is more straightfoward for most players?

### Version

2014.718.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16336668/compressed-logs.zip)

**Comment by bdach** [comment]
#24238
