### ISSUE TITLE
PP Caculator in lazer is different from online/stable client

### ISSUE THREAD

**Issue by MizuIro-H** [ppy/osu#29005]
### Type

Game behaviour

### Bug description

as the title said, the pp shown in gameplay and result(play/replay)screen doesnt match the pp that shown in stable/web.
I guess that lazer use a different pp algorithm, but I think it should be the same as the stable/web to get user the best experience.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/d0a2ec51-e16e-4f38-bc4b-a56a05918135)
![image](https://github.com/user-attachments/assets/47aa4bc7-e0d7-47ce-bbfa-c31db15282fb)

### Version

2024.718.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16336831/compressed-logs.zip)

**Comment by bdach** [comment]
Yes we know. It will eventually be rectified. No point tracking this here.
