### ISSUE TITLE
Removing the number before comma (,) causes the textbox to reset

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#29010]
### Type

Game behaviour

### Bug description

Hi. If you remove the Number before comma (like in editor or elsewhere), it resets the number instead of ignoring the comma.

https://github.com/user-attachments/assets/e89a52b0-ca6e-45bd-a604-e461d505d151

### Version

2024.718.1

### Logs

No need

**Comment by agatemosu** [comment]
`,123` should convert to `0,123` instead of the previous value

**Comment by peppy** [comment]
I'd kinda argue the `,` shouldn't be in a textbox in the first place 🤔

**Comment by aL1NaZ4R** [comment]
> `,123` should convert to `0,123` instead of the previous value

In many other applications, textboxes usually ignore commas and read the numbers only.

**Comment by peppy** [comment]
> In many other applications, textboxes usually ignore commas and read the numbers only.

This doesn't work if a european user is entering a decimal number using their local culture (where `,` is the decimal point).

**Comment by peppy** [comment]
In testing this actually looks to be working how I'd expect it to.
