### ISSUE TITLE
OSU! Lazer keeps saying im running a "Unofficial" build of the game

### ISSUE THREAD

**Issue by The-Grace-God** [ppy/osu#29017]
### Type

Game behaviour

### Bug description

About 80-90% of the time when i boot OSU! lazer it will complain that my score could not be submitted and that i should reinstall from a official source (I installed the game from the installer from git not even a day ago)

### Screenshots or videos

[https://youtu.be/92rWpCqFUfQ](url)

### Version

2024.718.1-Lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16340964/compressed-logs.zip)

**Comment by Stoppedpuma** [comment]
`Running osu! as administrator does not improve performance, may break integrations and poses a security risk. Please run the game as a normal user.` Might have something to do with this, try running the game normally.

**Comment by The-Grace-God** [comment]
> `Running osu! as administrator does not improve performance, may break integrations and poses a security risk. Please run the game as a normal user.` Might have something to do with this, please listen to the games warnings and try running the game normally.
> 
> Other issues which stick out in network log:
> 
> `Failing request osu.Game.Online.API.Requests.GetUpdatesRequest (System.Net.WebException: User not logged in)` `Failing request osu.Game.Online.API.Requests.GetChangelogBuildRequest (System.OperationCanceledException: Request cancelled)` `Failing request osu.Game.Online.API.Requests.GetScoresRequest (System.OperationCanceledException: Request cancelled)` `Failing request osu.Game.Online.Solo.CreateSoloScoreRequest (osu.Game.Online.API.APIException: missing token header`

looking into what you said and it mentions a missing token
tried signing out and logging back in and it seems to have fixed the issue at least for now not sure why the token was having issues though
for the admin part thats just my build of windows being unable to run anything as user everything is run with admin or higher privilege's due to some other software i run

**Comment by Stoppedpuma** [comment]
> windows being unable to run anything as user everything is run with admin

This is likely because UAC is set to the lowest level which for some reason just runs everything as admin.

**Comment by smoogipoo** [comment]
This (and all similar issues like it) should now be fixed.
