### ISSUE TITLE
Left Click stays held down

### ISSUE THREAD

**Issue by Traytorr** [ppy/osu#29016]
### Type

Game behaviour

### Bug description

Every time i play lazer, my left click stays held down in game randomly preventing me from clicking and there is nothing i can do to stop it. My key bind for left click while clicking circles is 'K' and my right click is 'L'

### Version

2024.718.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16339582/compressed-logs.zip)

**Comment by bdach** [comment]
Are you using a tablet? If yes, did you disable mouse clicks during gameplay?

**Comment by Traytorr** [comment]
that seems to have resolved the issue. yes i use tablet. i never thought to disable it as on stable it works fine even with it enabled. thanks for the help though
