### ISSUE TITLE
[UX] Timing point selection should not reposition the timeline marker

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#29012]
### Type

Game behaviour

### Bug description

Hi. When **stable** editors want to change a timing point's offset based on the hit objects, they use Arrow keys to move on the desired hit object (mostly snapped by a beat division), then press F6 to open the Timing menu, select their desired timing point, and press "Use current time".

In lazer editor it's the same procedure, but when you click on a timing point, it does reposition the timeline marker to it's own offset and here we go again. then "Use current time" button is useless. It makes a pain in the head to write down the offset, then comeback and write it in the offset box.

I know sometimes it's just neccecary to reposition the marker when you click on it, but it's not always. So my opinion is to make it require a double click to jump. Like first click just selects the timing point in case you want use "Use current time" button, and if you don't, just do another click to jump on it's timeline position.

### Version

2024.718.1

### Logs

No need

**Comment by bdach** [comment]
#23147

**Comment by aL1NaZ4R** [comment]
It's still the same, despite that issue & PR that you mentioned. (I think)

**Comment by bdach** [comment]
I'm saying that this is a duplicate
