### ISSUE TITLE
Visibility and differentiation between beat markers on timeline is not great

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#29024]
### Type

Other

### Bug description

Hi. Time signature is so useful when sampling hitsounds, but in lazer, they're not that recognizable. 
Take a look:

![image](https://github.com/user-attachments/assets/6db90043-90ea-408b-86fc-e803b7310fc0)
<sup>1/4 is way longer than other beats.</sup>

![image](https://github.com/user-attachments/assets/b140ef21-3b6f-403d-9bfb-9f6d3c615fa1)
<sup>1/4 is slightly longer, and thicker than other beats.</sup>

and I think it's still so much harder to recognize, compared to stable one.
We can make the \*other beats\* grey, thinner, and shorter to make it easier to recognize.

### Version

2024.718.1

### Logs

No need

**Comment by peppy** [comment]
The height difference was drastically reduced recently and I agree it's not great.  But consider that you're not comparing 1/4 to 1/4, you're comparing 1/1 to 1/4 (lazer lines are all white, aka 1/1).

**Comment by bdach** [comment]
> The height difference was drastically reduced recently

...to fix the fact that in some situations the tick could be *entirely obscured*.

Just to make sure this is clearly stated.

**Comment by peppy** [comment]
Should be resolved via https://github.com/ppy/osu/pull/29545.
