### ISSUE TITLE
Compatibility issues with "Edit externally", despite #28609

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#29022]
Hi. There was an issue with editor map export, which was making them un-readable for osu!stable. (Corrupt file error) fixed by #28609
The same thing still happens if you try to import and edit your map with stable edtior while using "Edit externally" option.
I figured it out right after inventing an idea to compose maps with lazer and add hitsounds with stable simultaneously😂😂

**Comment by bdach** [comment]
If not being able to edit mounted beatmaps in stable is what you wanted to report, then it's not an issue we will fix. lazer by default uses a variation of the osu! file format that will not be compatible with stable. Use legacy export option for that.
