### ISSUE TITLE
Context menu bank changing doesn't change multi-bank sliders, Normal & Auto only

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#29025]
### Type

Game behaviour

### Bug description

Hi. Right clicking a slider, which has multiple banks for each part, and clicking one of the banks to apply it for all of those parts. Drum and Soft are OK but strangely, Normal & Auto is broken.

https://github.com/user-attachments/assets/e5b83b68-9135-4dcb-9216-7f55fdfdb7bf

(Edit: Auto is broken too)

### Version

2024.718.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16350673/compressed-logs.zip)

**Comment by aL1NaZ4R** [comment]
Update: "Auto" has the issue too (forgot to check)

**Comment by peppy** [comment]
Tracking at https://github.com/ppy/osu/issues/29361 (this one was first but my issue has a better subject line so 🤷 ).
