### ISSUE TITLE
Difficulty filter doesn't adjust when using difficulty altering mods such as DT, and uses the base difficulty

### ISSUE THREAD

**Issue by QueenOfDancingStars** [ppy/osu#29031]
### Type

Cosmetic

### Bug description

I came across this issue when trying to use filter the difficulty of maps while having double time applied. An example would be a 5 star map that become 7 stars with DT. When having my difficulty filter set for 6 stars or above, it does not consider the fact that double time alters the difficulty of the mod, and doesn't show it because the original difficulty is 5 star, rather than filtering by the new star ratings with the alterations. I'll attach a screenshot below as an example.
The map is 6.5* with double time, and the original star rating is 4.61*. The filter counts the non-DT star rating, so it filters the map even then it's above 5.5 as the filter shows.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/d239c283-157b-4aae-9fbe-0b3fdb2c34a4)
![image](https://github.com/user-attachments/assets/0841c0e3-627e-4765-beef-c32681a8d5c9)

### Version

2024.718.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16354185/compressed-logs.zip)

**Comment by Stoppedpuma** [comment]
#12628

**Comment by peppy** [comment]
Please search before opening an issue, thanks.
