### ISSUE TITLE
Large stutter when exiting leaderboard view after completing daily challenge

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#29050]
### Type

Performance

### Bug description

The game seems to have a pretty bad performance hit when leaving the leaderboard section after completing the daily challenge, this spike can vary from a drop to single digit frames to a complete freeze for a few seconds. I'm going to guess this is because of the high amount of numbers being shown from everyone submitting scores being shown when exiting the leaderboard screen.

### Version

.

### Logs

2024.725.0

**Comment by peppy** [comment]
Already mentioned in discord, but both leaderboard refreshes and new events seem to not be debounced as much as they should be.
