### ISSUE TITLE
Press space when result panel loading will cause error

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#29066]
### Type

Game behaviour

### Bug description

1. click score in daily challenge (or view result in playlist for per beatmap)
2. press space before score appear
3. error occuer

### Screenshots or videos

https://github.com/user-attachments/assets/3a2aa670-61c4-45b2-8a83-813292158667

### Version

2024.725.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16372851/compressed-logs.zip)

**Comment by bdach** [comment]
Not strictly in daily challenge code, more of a reveal of an existing possible bug.
