### ISSUE TITLE
Daily challenge chat doesn't send message when pressing enter on Android (Gboard)

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#29089]
### Type

Game behaviour

### Bug description

In the chat window inside daily challenge, when typing a message in the bar below and pressing enter on Gboard, the game does nothing.

### Version

2024.726.0

**Comment by bytenekos** [comment]
Probably similar to #28966?

**Comment by yesseruser** [comment]
> Probably similar to #28966?

Yes, this is exactly the issue. Sorry for duplicate.
