### ISSUE TITLE
Vulkan crash my laptop

### ISSUE THREAD

**Issue by GGchung69** [ppy/osu#29102]
### Type

Crash to desktop

### Bug description

Vulkan crash my laptop and if not it throw this error
but most of the time it just kernel panic without bsod
I don't know if other hardware is afected but it certantly does with mine

### Screenshots or videos

![image](https://github.com/user-attachments/assets/bc645b62-3546-437e-a05c-814ffaa2b840)

### Version

2024.726.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16390128/compressed-logs.zip)

**Comment by bdach** [comment]
The vulkan renderer is experimental and broken to the point that it'll probably be replaced at some point if we can get a hold of one. If it doesn't work for you, then don't use it.

**Comment by GGchung69** [comment]
oh ok, i just want to let pepole know this bug exist
