### ISSUE TITLE
Difficulty settings stuck at 0, even when adjusting difficulty adjusting mods on Daily Challenge.

### ISSUE THREAD

**Issue by dooperdoops** [ppy/osu#29106]
### Type

Crash to desktop

### Bug description

When applying mods to a map on Daily challenge, Star rating, OD/AR/HP/CS stays at 0 and doesn't change, along side the BPM.

### Screenshots or videos

![osu_2024-07-26_12-13-50](https://github.com/user-attachments/assets/28441803-11bc-444e-8e82-f089d5bec965)

### Version

2024.726.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16390808/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/29094, will be fixed with next hotfix (today?)
