### ISSUE TITLE
Found a bug with the numbers on the circles

### ISSUE THREAD

**Issue by SpeckyYT** [ppy/osu#2911]
![image](https://user-images.githubusercontent.com/40666126/42040117-30f182de-7aef-11e8-9a2d-bb559b32a74d.png)

Like you can see there is a circle with (0 and 1), another with (1 and 1), (2 and 1), (3 and 1), (4 and 1)..... and so on..... can you fix that?
Osu! version b20180626.1

(I don't know if it's a problem with the skin)
((The skin is "personal use only"))

**Comment by LittleEndu** [comment]
This repository isn't for issues with stable client. But the term to google is ``HitCircleOverlap``

**Comment by SpeckyYT** [comment]
ok, thx

**Comment by SpeckyYT** [comment]
ok, fixed
