### ISSUE TITLE
Large amount of text objects after a long gameplay in daily challange

### ISSUE THREAD

**Issue by LmanTW** [ppy/osu#29110]
### Type

Performance

### Bug description

When you exit from the gameplay, the event text and the score text will all pop up at once. However if the gameplay duration is long (like keep restarting), the number of the text objects can become huge, leading to performance issues.

### Version

2024.726.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16392770/compressed-logs.zip)

**Comment by bdach** [comment]
Fixed in master / next release
