### ISSUE TITLE
Sliders don't receive correct combo information

### ISSUE THREAD

**Issue by muscularcandy67** [ppy/osu#2912]
Just like the title, all sliders have the number 1

LOGS
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2146017/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2146018/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2146019/runtime.log)
[database.log](https://github.com/ppy/osu/files/2146012/database.log)
[network.log](https://github.com/ppy/osu/files/2146013/network.log)
[performance.log](https://github.com/ppy/osu/files/2146014/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2146015/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2146016/performance-gamethread.draw.log)

SCREENSHOT
https://imgur.com/a/IwwXRZd

**Comment by plootia** [comment]
[video](https://youtu.be/yWhl2QkaNZU)

**Comment by peppy** [comment]
Another regression from https://github.com/ppy/osu/pull/2635/files/1a8aa6eab10d677a0622b111bbab5d796730b58e#r198183234
