### ISSUE TITLE
Game shows amount of plays in daily challenges other menus

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu#29122]
### Type

Cosmetic

### Bug description

I don't know how to explain it properly, but its visible what i mean in the video

### Screenshots or videos

https://github.com/user-attachments/assets/dce6381b-6c23-4c39-8737-4922b46cf653

### Version

osu! version: Lazer 2024.727.0 (latest)

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16397115/compressed-logs.zip)

**Comment by nagi-desuuu** [comment]
https://discord.com/channels/188630481301012481/188630652340404224/1266464930325069956
