### ISSUE TITLE
Consider adding back a global event feed akin to  `#highlights`

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#29120]
Channel histories are not preserved, mention notifications become useless if the user doesn't open it for at most an hour.

Opened an issue thread instead of a discussion just to raise visibility, but it can be converted to a discussion if it's not important enough.

**Comment by bdach** [comment]
Why would it be a channel?

**Comment by peppy** [comment]
I'm okay with using a channel if that's still deemed the best way to communicate this information. But it wouldn't be displayed in chat. I'd see this kind of thing displayed on the main menu or somewhere similar.

**Comment by peppy** [comment]
Oh, the theme here is for mentions?

We'd want to fix the notification flow, rather than add back highlights channel.

**Comment by frenzibyte** [comment]
My issue here is when someone highlights me in a public channel and their message gets lost because it was removed due to too many messages coming after it. I supposed a `#highlights` channel is the way to go for that, just to keep a copy of the message's content. Anything similar would be fine as well (like the mention inbox in discord).

**Comment by peppy** [comment]
> I don't understand what the web-side notification system entails for the issue I brought up.

Because notifications are currently not persisted locally, which is another large issue here.

> My issue here is when someone highlights me in a public channel and their message gets lost because it was removed due to too many messages coming after it.

Optimally we'd want to load history back to the point of the message. I believe the server-side requirements for doing this are already fulfilled.
