### ISSUE TITLE
Skin elements on playfield layer get unintentionally (?) scaled based off of circle size

### ISSUE THREAD

**Issue by frarg** [ppy/osu#29149]
### Type

Cosmetic

### Bug description

This is most noticeable with the UR bar for me since it's the only element I use in the playfield, but happens with any element added there (I added the BPM counter to illustrate).

CS0 (elements are almost entirely off-screen):
![osu_2024-07-27_17-19-15](https://github.com/user-attachments/assets/99429867-2366-4f17-9fd7-edd17f4114ee)

CS3:
![osu_2024-07-27_17-19-36](https://github.com/user-attachments/assets/e1b09690-766e-4e07-a250-4f5761d50fe2)

CS7:
![osu_2024-07-27_17-22-52](https://github.com/user-attachments/assets/7e1a784e-40d5-46de-9833-6d0d85c60b4d)

CS10:
![osu_2024-07-27_17-20-11](https://github.com/user-attachments/assets/f935552a-8a84-4a18-83a2-360bb57e41e2)

I can't think of any reason this behaviour should be intended.
Let me know if you need more details or information on my settings

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16401506/compressed-logs.zip)

**Comment by MingxuanGame** [comment]
https://github.com/ppy/osu/blob/565107205c60f14488f1642011808d286d712c31/osu.Game/Screens/Play/HUDOverlay.cs#L248-L256

Skin playfield follows game playfield. I can't be sure if this is a bug.

**Comment by bdach** [comment]
This was intentionally changed. See https://github.com/ppy/osu/discussions/28579.

**Comment by frarg** [comment]
Would it be possible to add another layer that acts the same as the UI layer, but doesn't get hidden when the interface is hidden? Or at the very least, add an option to make the UR bar act the same way it does in stable (stays visible all the time, regardless of interface is enabled or not)? 
I don't think many people want it to move around the way it does in my screenshots

**Comment by bdach** [comment]
In some indeterminate future it will probably be toggleable on a per element basis as to whether interface hiding hides that element.

**Comment by frarg** [comment]
Thank you for the info!
