### ISSUE TITLE
Editor fails to parse timestamp links from discussion page

### ISSUE THREAD

**Issue by kadambishreyas** [ppy/osu#29145]
### Type

Game behaviour

### Bug description

repro:
1. download this beatmap: https://osu.ppy.sh/beatmapsets/999367#osu/2090130
2. import the beatmap and open [III.A Nice Derangement of Epitaphs]
3. navigate to the timestamp link in [this comment](https://osu.ppy.sh/beatmapsets/999367/discussion/2090130/timeline#/1257834) and click the link

expected behavior:
notice that the ranked version of this beatmap DOES in fact have an object with combo number 11 at 00:38:526.
as such, i expect that the editor would move the timeline to the ms of the timestamp. given that the combo numbers line up, it should also automatically select this object (and all objects in the timestamp).

result:
i receive the notification "Failed to parse editor link". 

### Screenshots or videos

https://github.com/user-attachments/assets/6dfef617-295c-4f42-bf04-da9780f44db7

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16401104/compressed-logs.zip)

**Comment by zihadmahiuddin** [comment]
Looks like `timestamp` [on this line](https://github.com/ppy/osu/blob/4ad7d900c17ed3de6e405f6f25d29f2b5f40bb5c/osu.Game/Screens/Edit/Editor.cs#L1329) is `00:38:526%20(11)`, it works fine if I replace the `%20` with a space so I think just URL-decoding it will fix it but not sure what's the right place to do that, maybe it should be done on all strings received via `osu://` URIs?
