### ISSUE TITLE
Watching a replay with mods in the Daily Challenge forces those mods when playing

### ISSUE THREAD

**Issue by SupDos** [ppy/osu#29153]
### Type

Game behaviour

### Bug description

If you view a replay from someone that has mods enabled, those mods will be enabled for you until you select a mod yourself

### Screenshots or videos

https://github.com/user-attachments/assets/12a68b88-9002-4537-a78c-c816e5c97767

### Version

2024.727.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16401895/compressed-logs.zip)

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/29133
