### ISSUE TITLE
Daily challenge: Score breakdown hints showing on other tabs

### ISSUE THREAD

**Issue by MitsukaiDokuro** [ppy/osu#29175]
### Type

Cosmetic

### Bug description

The hints/labels from the score breakdown diagram show up by hovering over certain area on the other pages, too. I think this is not intended behaviour - See the screenshot attached.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/42cbf123-a10e-43bd-8c98-89b10534e355)

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16404721/compressed-logs.zip)

**Comment by felipemarins** [comment]
Duplicate from #29122
