### ISSUE TITLE
Holding the button when resuming gameplay doesn't hold the button in gameplay unlike in Stable

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#29174]
### Type

Game behaviour

### Bug description

In stable, if you click and hold the button when mousing over the cursor to resume gameplay, the button is held within gameplay, so you can for example immediately start spinning (if you accidentally thought it's the end of the song, clicked Esc, but there was still a spinner at the end).

In lazer holding doesn't transfer to gameplay and you need to click and hold a second time for it to get registered.

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16404525/compressed-logs.zip)

**Comment by bdach** [comment]
@frenzibyte?

**Comment by peppy** [comment]
Tested against an old release. This is a regression, and a very bad one at that.
