### ISSUE TITLE
Number of passes for a score range still show despite a different panel being displayed when hovering over it

### ISSUE THREAD

**Issue by Serterd** [ppy/osu#29206]
### Type

Cosmetic

### Bug description

When in the Daily Challenges screen, if you hover over the space where a bar from the "Score breakdown" panel would be, it displays the stats despite being on a different panel like the "Time remaining" or the "Total pass count/Cumulative total score".
This seems to happen everytime, even after a fresh start of the game.

### Screenshots or videos

![osu_2024-07-30_18-52-45](https://github.com/user-attachments/assets/f62d4beb-ceb8-4942-9e77-0d266c6de9bb)
![osu_2024-07-30_18-52-49](https://github.com/user-attachments/assets/ce555467-c6d6-4aa3-a0b8-c079ae038245)

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16431158/compressed-logs.zip)

**Comment by Joehuu** [comment]
Already fixed in https://github.com/ppy/osu/pull/29159 / https://github.com/ppy/osu/pull/29187.
