### ISSUE TITLE
client crashes when spamming mouse buttons

### ISSUE THREAD

**Issue by 9hax** [ppy/osu#2920]
The osu!lazer client stutters, then crashes if both mouse buttons are spammed anywhere in the app while the mouse is moved and the normal mouse arrow cursor is active. (This means it doesn't crash while playing a beatmap because there is a ring cursor there.) I think the crash has something to do with the turning mouse arrow while dragging, not being able to turn the arrow fast enough.
OS: Win10, Build 1803 (17134.112)
osu!lazer version: 2018.629.0
I have not found any evidence of the crashes in the logs here: [logs.zip](https://github.com/ppy/osu/files/2150865/logs.zip)

I also made a screen recording
[here](https://github.com/ppy/osu/files/2150867/crash.mp4.zip)
 in 720p (because my graphics card is too bad for 1080p recording with obs) where you can see the game crash.

sincerely, a osu! player who clicks real fast in loading times.

**Comment by ekrctb** [comment]
I think this is the same bug as ppy/osu-framework#1646. But I think it is okay to open here because the bug is actually osu-side and not framework side.
