### ISSUE TITLE
Bug during the creation of a duplicate

### ISSUE THREAD

**Issue by alphaziod** [ppy/osu#29229]
### Type

Cosmetic

### Bug description

Hello, I've found a bug on Lazer.

When I try to create a duplicate to practice a difficult section of a map, and then return to the interface, there's a kind of bug (I'm not sure if it's just a display issue).

The copied and edited map seems normal (see Screenshot 1). However, the ranked map, which I haven't touched, appears to have been modified locally in the selection screen. Yet, where all the map info like AR and BPM are displayed, it still shows as ranked, and the leaderboards are still available (see Screenshots 2 and 3).

### Screenshots or videos

![image](https://github.com/user-attachments/assets/6f82c377-289f-41fb-a110-514568871ec3)
![image](https://github.com/user-attachments/assets/c56ce989-de9e-4020-8df4-d2d0e99ee22e)
![image](https://github.com/user-attachments/assets/22e0f38b-9dab-4d85-ab22-0d1301e611a6)

### Version

2024.731.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16454281/compressed-logs.zip)

**Comment by Drison64** [comment]
I think that is the intended behavior, even though it could lead to confusion.

As far as I understand the panel on the left references to the selected Beatmap's Difficulty where as the Beatmap header references to the BeatmapSet's Online status.

**Comment by alphaziod** [comment]
Yes, but even after deleting the modified one and uninstalling the beatmap, it is still recognized as modified (I couldn't save a score to try to prove it). I could do it tomorrow if you want.

**Comment by smoogipoo** [comment]
This is intentional because:
1. You're sorting by difficulty, so it's displaying two set panels, even though it's actually the same beatmap set.
2. You've modified a beatmap in the set - the panel shows the set's modification status.

Song select is being redesigned so this will likely change, no need to keep open.
