### ISSUE TITLE
Flashlight stops working when too many things are rendered on screen

### ISSUE THREAD

**Issue by sojudev** [ppy/osu#29237]
### Type

Cosmetic

### Bug description

Made a stupidly long slider, multiplied it by a lot and found that at a certain point of slider balls/ticks, the flashlight literally just turned off.

Lowest ever priority, since it's only for stupid maps. I can't imagine a ranked or loved map actually having such an issue

### Screenshots or videos

![screenshot014](https://github.com/user-attachments/assets/c034cead-aec1-461d-a8a6-462ceebcac08)

### Version

osu!stable a/o 8/1/2024

### Logs

none

**Comment by Stoppedpuma** [comment]
This repo is not for stable, please report this [here](https://github.com/ppy/osu-stable-issues).
