### ISSUE TITLE
Target Practice mod is compatible with Synesthesia mod

### ISSUE THREAD

**Issue by SenorNikicho** [ppy/osu#29232]
### Type

Game behaviour

### Bug description

When playing with the Target Practice mod, the circles are repeated every 1/1 beat, which is why the Synesthesia mod is useless. I think it's worth making these mods incompatible.

### Screenshots or videos

![osu_2024-08-01_17-11-45](https://github.com/user-attachments/assets/63bba38b-f7b7-4021-96f5-70a3d2d85d15)

### Version

2024.731.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16456224/compressed-logs.zip)

**Comment by smoogipoo** [comment]
I don't think this is important.
