### ISSUE TITLE
Daily Challenge results start loading from personal best on subsequent scores

### ISSUE THREAD

**Issue by 424ever** [ppy/osu#29240]
### Type

Game behaviour

### Bug description

When setting a score which is ranked lower on the leader-board than a previously obtained score on the Daily Challenge, the result screen starts at the position of that personal best and scrolls backwards, loading all scores between the personal best and the new score.

### Screenshots or videos

https://github.com/user-attachments/assets/722cfb5f-5bf1-47e4-ac2c-0df957590551

### Version

2024.731.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16460360/compressed-logs.zip)

**Comment by 424ever** [comment]
There is also some funky layering going on, where the loading spinner is drawn above the result screen while the scores are loading:

https://github.com/user-attachments/assets/1eb17aa1-06b9-415c-8c17-f88be2b2a8f4

**Comment by peppy** [comment]
Bumping in priority because this looks to be spamming a lot of web requests.
