### ISSUE TITLE
Options Button is unhittable at high ui scales with lots of mods enabled

### ISSUE THREAD

**Issue by Lyti4n** [ppy/osu#29252]
### Type

Game behaviour

### Bug description

While I can't imagine this would happen often its probably best to show less of the mods selected when settings menu reaches the osu cookie, so that its still usable.

### Screenshots or videos

![osu!_hmDFo2qqfz](https://github.com/user-attachments/assets/a6a050a5-af85-412f-9e2e-ebfdc19ebef6)

### Version

2024.731.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16467972/compressed-logs.zip)

**Comment by peppy** [comment]
Song select is being redesigned. The new design already avoid this issue.

![osu Game Tests 2024-08-02 at 11 03 59](https://github.com/user-attachments/assets/7ec7271b-55ec-48e0-ba45-f4b0047d42cd)
