### ISSUE TITLE
Mod tiles cut off weirdly when scrolled down in mod select screen

### ISSUE THREAD

**Issue by Lyti4n** [ppy/osu#29251]
### Type

Cosmetic

### Bug description

This is very minor but When scrolled down the mod cuts of weirdly it should probably go below the light green trim instead. The problem is much more noticeable on higher UI scales  

### Screenshots or videos

![Visual bug](https://github.com/user-attachments/assets/2429adbe-2867-41c7-b22a-ff7485cc93de)

### Version

2024.731.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16467845/compressed-logs.zip)

**Comment by peppy** [comment]
Where did the "after" image come from here?

**Comment by Lyti4n** [comment]
i just edited it in paint to show what i think it should look like, is there a better term to use for that?
