### ISSUE TITLE
Pressing apostrophe right before entering a map sometimes causes an error

### ISSUE THREAD

**Issue by hiderikzki** [ppy/osu#29261]
### Type

Other

### Bug description

When pressing apostrophe (') right before entering a map on a difficulty that is supposed to get filtered out by that (mostly non-quest difficulties) instead causes an error and continues into the difficulty.

Normal behaviour (ex. typing anything else that is supposed to filter out that difficulty) is to switch difficulty / map and enter that instead, but with apostrophe it somehow fails in this case and continues into the initial difficulty.

### Screenshots or videos

https://github.com/user-attachments/assets/6079301b-3be0-4959-9cdc-145c6591f7db

### Version

2024.731.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16475556/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/21120
