### ISSUE TITLE
Difficulties/Replay Files Connect to Wrong/Multiple Songs

### ISSUE THREAD

**Issue by OnlyJustEthan** [ppy/osu#29262]
### Type

Game behaviour

### Bug description

Bug was found during normal playtime. When looking for old replays of [Triple Play](https://osu.ppy.sh/beatmapsets/697726#osu/1477910) none were present. When I tried to import them, the files attempted to go to [Komarovo (DVRST Phonk Remix)](https://osu.ppy.sh/beatmapsets?q=title%3D%22%22Komarovo%20%28DVRST%20Phonk%20Remix%29%22%22). The replays were viewable when the notification was clicked with the Triple Play chart and the Komarovo song.

### Screenshots or videos

[Proton Drive Link Containing .osr Files and Proof Video](https://drive.proton.me/urls/0AT6CX0ABG#brhQvipJEvE2)

### Version

2024.731.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16476708/compressed-logs.zip)

**Comment by peppy** [comment]
I have no idea how your beatmaps got into this state, and unless it happens again I'm probably going to turn a blind eye here. Re-downloading both beatmaps should fix the issue though.

Video provided in OP for reference:

https://github.com/user-attachments/assets/ba10c284-d301-40cf-9407-fe56d542f4c0
