### ISSUE TITLE
Add hint to press enter key for focusing in-gameplay chat

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#29264]
I've had to navigate through PRs to figure out that you can focus the chat by pressing <kbd>Enter</kbd>.

Right now the chat text box only shows "type message..." when unfocused, it should be "press enter to type message..." or something similar.

![CleanShot 2024-08-03 at 06 50 15](https://github.com/user-attachments/assets/ca3ac7d8-579a-4b06-9a03-1781d808497f)

**Comment by kstefanowicz** [comment]
This is pulled from `osu.Game.Resources.Localisation.Web.ChatString`, which is party of the [separate repository osu-resources](https://github.com/ppy/osu-resources).

I have opened [PR #335](https://github.com/ppy/osu-resources/pull/335) in that repo to address this issue.
