### ISSUE TITLE
Vulkan/Steam Deck: glitched rendering on desktop mode when invoking the compositor

### ISSUE THREAD

**Issue by DaVince** [ppy/osu#29267]
### Type

Cosmetic

### Bug description

Note: I reported this here rather than in q&a discussion because I feel that an unmodded Steam Deck with regular SteamOS is a consistent/reproducible enough setup to be able to report it here. Let me know if it's not.

This issue happens specifically on Steam Deck running SteamOS in desktop mode, when using Osu!'s Vulkan (experimental) renderer only.

How to reproduce:
* Run Osu! in borderless or fullscreen mode.
* Change the volume or alt-tab between other applications and return to Osu!; basically perform any action that involves the window compositor.
* The visuals are now glitching out.
* The behavior will sometimes start getting worse, like freezing up all visuals whenever a confirmation dialog appears.

Workaround:
* Fullscreen mode stays broken until Osu! is restarted.
* Borderless mode can be fixed by switching into windowed mode, then back into borderless.

**Other notes:**
* Running the Flatpak version.
* This issue doesn't happen with OpenGL or OpenGL (experimental).
* Changing the Threading mode doesn't get rid of this behavior, although visually the lines that glitch out do shift down (I assume due to different timings).
* Changing the Frame limiter setting momentarily fixes this, until actions are performed on the compositor again.
* The monitor runs at 240 Hz, but this happens on any framerate on any external display using any connection (USB-C and DisplayPort were tested).
  * Interestingly, on the Deck's internal display, it doesn't show the flashing lines, but the game's framerate halves instead.
* This issue happens faster if I do run Osu! through Steam, because then the screen keyboard attempts to pop up on the song selector, immediately causing the graphical glitches.

### Screenshots or videos

https://youtu.be/LCbnRE3_iUI

Settings:
![osu_2024-08-03_10-40-49](https://github.com/user-attachments/assets/dfb0e787-edaf-446f-bd90-9a82483fe725)

### Version

2024.731.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16478906/compressed-logs.zip)

**Comment by LGRain** [comment]
try reinstall vulkan drivers idk what video card steam desk

**Comment by smoogipoo** [comment]
Don't use Vulkan.

**Comment by DaVince** [comment]
> Don't use Vulkan.

If this is a known issue, please let me know, otherwise I'm a little confused why this makes it close-worthy? I'm reporting an issue specifically on the experimental renderer in the hopes of getting the renderer improved.

**Comment by smoogipoo** [comment]
Yes, it's a known issue. Feedback for experimental renderer goes here -> https://github.com/ppy/osu/discussions/27659 but there's already many reports of this.

**Comment by DaVince** [comment]
> Yes, it's a known issue. Feedback for experimental renderer goes here -> #27659 but there's already many reports of this.

Alright, fair. Thanks for letting me know!

**Comment by DaVince** [comment]
> try reinstall vulkan drivers idk what video card steam desk

Thanks for trying to help! On Deck, drivers are a part of the OS itself, which is up to date. But since the issue has been confirmed regardless of that, I'll just wait on renderer improvements.
