### ISSUE TITLE
Make it easier to delete objects in the editor

### ISSUE THREAD

**Issue by Lyti4n** [ppy/osu#29277]
### Type

Game behaviour

### Bug description

Currently the only way to delete objects is to shift right click or right click and click the the delete button. While I do understand why right click no longer deletes objects I think a reasonable compromise would be to make middle click delete objects as it currently does the same thing as left click.

### Version

2024.731.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16486270/compressed-logs.zip)

**Comment by peppy** [comment]
I'm okay with assigning middle click and seeing if this grows on people, sure.

I also toyed with making right click delete work when in placement mode only, but this inhibits the ability to use the context menu which I think may be detrimental to some people's editing style. Can be tested easily with this diff:

```diff
diff --git a/osu.Game/Rulesets/Edit/PlacementBlueprint.cs b/osu.Game/Rulesets/Edit/PlacementBlueprint.cs
index 2817e26abd..60b979da59 100644
--- a/osu.Game/Rulesets/Edit/PlacementBlueprint.cs
+++ b/osu.Game/Rulesets/Edit/PlacementBlueprint.cs
@@ -209,9 +209,7 @@ protected override bool Handle(UIEvent e)
 
                 case MouseButtonEvent mouse:
                     // placement blueprints should generally block mouse from reaching underlying components (ie. performing clicks on interface buttons).
-                    // for now, the one exception we want to allow is when using a non-main mouse button when shift is pressed, which is used to trigger object deletion
-                    // while in placement mode.
-                    return mouse.Button == MouseButton.Left || !mouse.ShiftPressed;
+                    return mouse.Button == MouseButton.Left || PlacementActive == PlacementState.Active;
 
                 default:
                     return false;

```
