### ISSUE TITLE
[osu!lazer] Discord Rich Presence not working on Ubuntu 24.04LTS

### ISSUE THREAD

**Issue by QuantumS14** [ppy/osu#29284]
### Type

Other

### Bug description

Ubuntu 24.04LTS

Lack of integration with Discord Rich Presence. The game settings are set to: Full, but it still doesn’t work. Discord simply shows that the game is running, but does not display any data.
The game was installed from https://flathub.org/apps/sh.ppy.osu

I just manually built the latest version of osu!(lazer) from source on linux, but Discord Rich Presence still doesn't work. I'm crying.

### Screenshots or videos

![2024-08-04_12-21](https://github.com/user-attachments/assets/a2aae6f6-5065-4337-8bb5-d060fa0454b0)

### Version

osu!(lazer) version: 2024.731.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16489386/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Yup. Welcome to flatpak / sandboxing in general.

There appears to be a [workaround](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)) but I'm not sure if it'll work even then, depending on how our underlying library is doing stuff.

**Comment by bdach** [comment]
Shouldn't this go live in https://github.com/flathub/sh.ppy.osu/issues then?

**Comment by bdach** [comment]
In fact, https://github.com/flathub/sh.ppy.osu/issues/132. Closing as duplicate
