### ISSUE TITLE
Lazer treat specific beatmap as being unsubmitted.

### ISSUE THREAD

**Issue by phucdtd** [ppy/osu#29318]
### Type

Game behaviour

### Bug description

[Beatmap link](https://osu.ppy.sh/beatmapsets/1725456#taiko/3602577)
[Discussion on osu! forum](https://osu.ppy.sh/community/forums/topics/1959709?n=1)
osu! version: Lazer 2024.727.0

Description: osu!lazer behave as if the difficulty [Hivie's Beginnings] is unsubmitted, despite the other 2 difficulties behaving as expected. This problem persisted through re-downloading of the beatmap via osu!direct.
The bugged map show no User Rating, Difficulty spread, Points of Failure, Leaderboard, and the play is not submitted to the osu! server (doesn't show in osu! api or the map leaderboard). The issue is not with the version of the game as I've been able to submit other scores within the same session.

Note: I'm aware that similar issues has been submitted before (like #28202), but for my case the game behave as if the map is unsubmitted instead of unranked / graveyarded.

Note 2: While exporting the logs for this specfic issue, I've deleted the map and redownload it 2 more times, with the second one succeed in solving the issue (and 2 subsequent tries show that it indeed has resolved itself). However, as mentioned in the osu! forum discussion thread, it is reproducible so I still think it's worth being reported and investigated.

### Screenshots or videos

https://streamable.com/3npksy

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16521481/compressed-logs.zip)

**Comment by bdach** [comment]
```
2024-08-07 09:30:04 [verbose]: [2e843] [APIBeatmapMetadataSource] Online retrieval mapped Hayakore Tatsumi - Uninstalled Children (KuroKuroKuro) [Hivie's Beginnings] to 1725456 / 3602577.
2024-08-07 09:30:04 [verbose]: Discarding metadata lookup result due to mismatching online ID (expected: 3608756 actual: 3602577)
```

This is another case of https://github.com/ppy/osu/issues/27332
