### ISSUE TITLE
No way to view hitwindows and hit object radius

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#29335]
### Type

Game behaviour

### Bug description

In stable you could hover over the difficulty values in song select to get detailed information about what they meant, showing exact hit windows and hit object radius for the CS. In lazer this is missing, and there is no way to view this information as far as I know.

![osu!_WG2FWRPtgF](https://github.com/user-attachments/assets/591d3ec9-c2dc-48f7-8d67-ad5dba66bbfc)

### Version

2024.731.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16532561/compressed-logs.zip)

**Comment by Ch3mson** [comment]
Hey, I'm new to game dev and C# but have coding experience elsewhere. I would assume this is just an implementation of a hover  in the difficulty component and make a new component that shows up to display these details. Any guidance on how to start?

**Comment by smoogipoo** [comment]
At the end of the day you're going to have to try things out for yourself, as we don't really have the bandwidth to describe how to do things.

You can search for usages of `IHasTooltip` to see how to add them. It'll probably go somewhere inside `BeatmapDetails` or `AdvancedDetails`, and there should already be an example there for how to use the `WorkingBeatmap`/`GetPlayableBeatmap()`. You'll probably want to do something like what `DrawableRuleset.FirstAvailableHitWindows` does.

**Comment by shiumano** [comment]
#6202 
This is a similar proposal.

**Comment by peppy** [comment]
Let's track at #6202. This seems like a 100% duplicate.
