### ISSUE TITLE
Mod Overlaps with Accuracy When Window Width is Shrunk to Minimum

### ISSUE THREAD

**Issue by Ch3mson** [ppy/osu#29348]
### Type

Cosmetic

### Bug description

When the osu window is shrunk to the smallest possible width, the mods overlap with the difficulty numbers, as well as the % once there is more than 3 mods on the score.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/e9786e4e-b656-4501-bb57-a1a05ee15d07)

### Version

2024.731.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16539235/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Song select is being redesigned.
