### ISSUE TITLE
osu!lazer closes while starting

### ISSUE THREAD

**Issue by 9hax** [ppy/osu#2935]
osu!lazer wont run on my Fujitsu Lifebook PH530. 
Specs: i3-330UM, integrated graphics, 4GB RAM
OS: Win10 17134.1 (1803)
osu!lazer just Shows a black screen, then Closes without any error Messages. Logs attached [here](https://github.com/ppy/osu/files/2154689/logs.zip).

**Comment by FreezyLemon** [comment]
Looks like a duplicate of #2846.

**Comment by 9hax** [comment]
@FreezyLemon seems like that. I will try writing a custom driver version because downgrading the os is not an option for me.

**Comment by 9hax** [comment]
Maybe there should be an error message to point that incompatibility out.
