### ISSUE TITLE
"Default" audio device in lazer causes audio latency when applying rate change mods on windows

### ISSUE THREAD

**Issue by Spok5508** [ppy/osu#29353]
### Type

Game behaviour

### Bug description

Ever since I experienced the issue where HT and DT cause early/late audio latency respectively (windows only), I have been trying to track down the root of this issue. A couple weeks ago I discovered that toggling the use of exclusive audio got rid of this issue, but after some more experimenting I'm pretty sure that I found a way to reproduce the bug.

You can reproduce the latency issues following these steps (video attachment follows all steps):
1. Open lazer, set the audio output device as "Default", close lazer
2. Go into windows sounds, have 1 playback device with exclusive audio enabled, 1 device with exclusive audio disabled
3. Set your default playback device to the one WITHOUT exclusive audio
4. Open lazer, start a map, close lazer again
5. Set your default playback device to the one WITH exclusive audio
6. Open lazer, you now experience variable audio latency when applying rate changes

To revert the bug, all you have to do is change your audio device in lazer to a specific setting instead of "Default"
As soon as you do this, the audio will behave as expected again.

Worth noting that I tested this method on 2 additional different PC's at COE, reproducing the issue in both cases.

I've also heard multiple reports that changing audio device from "Default" helped people reduce perceived audio latency instantly.

### Screenshots or videos

https://github.com/user-attachments/assets/5e24bd5a-00b4-4cb0-a368-357a7ac00521

### Version

2024.731.0

### Logs

The export logs button currently fails and displays an error. I have zipped all contents of my logs directory.
[logs.zip](https://github.com/user-attachments/files/16548825/logs.zip)

**Comment by peppy** [comment]
Sounds like eldritch bass bugs at large.

**Comment by Spok5508** [comment]
I am unable to reproduce this bug on the latest version of lazer!

**Comment by peppy** [comment]
Great to hear! Let's close this for now.
