### ISSUE TITLE
Daily challenge statistics display does not have suffixes

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#29355]
![image](https://github.com/user-attachments/assets/6cdfdbfc-9505-4289-9532-b7f73a6fda59)

The localisation strings `ShowDailyChallengeUnitDay` and `ShowDailyChallengeUnitWeek` appear to not have the suffixes added to them. cc @smoogipoo

**Comment by smoogipoo** [comment]
It's impossible for this to be handled with the way localisations currently work. We'll need to define osu!-specific localisation strings or use Humanizer instead.

**Comment by peppy** [comment]
just implement locally without localisations.

**Comment by frenzibyte** [comment]
Resolved in #29414
