### ISSUE TITLE
Change song location

### ISSUE THREAD

**Issue by nobbele** [ppy/osu#2936]
Right now songs installs into C:/Users/xxxx/AppData/Roaming/osu/files but i want to install these on my D: drive because my C: drive is a tiny SSD and i have over 5gb of songs. I have looked into it and i *think* it's a framework thing since that's where DesktopStorage is located but i am not sure. Having a location option in options would be great

**Comment by Frontear** [comment]
When would this actually be useful?

**Comment by jorolf** [comment]
Like he said, when your main drive is small and osu is too big. (my songs folder is 9.3gb with "just" about 1.5k sets)

**Comment by Draylynn** [comment]
Any update on this issue? I'm also one of those who can't play Lazer, with a 100+GB library in OSU!, and my main drive practically full, I cannot import songs.

**Comment by bdach** [comment]
This issue is backlog, which means it's relatively low priority - there are more pressing issues to deal with. Please look into setting up symlinks as a temporary alternative.

**Comment by peppy** [comment]
Going to close this as a duplicate of https://github.com/ppy/osu/issues/960, which has more information about available workarounds.
