### ISSUE TITLE
osu!mania touch input shows up with "touch" setting disabled

### ISSUE THREAD

**Issue by osulover9000** [ppy/osu#29378]
### Type

Game behaviour

### Bug description

Using a laptop keyboard and DFG {SPACE] IOP keys, touchpad directly below those keys, wrist or palm sometimes clicks the touchpad. It would be expected for all touch inputs to be disabled with the touch option disabled, but for mania it is clearly not the case.

### Screenshots or videos

https://github.com/user-attachments/assets/20bcd3a2-287d-4e57-b743-9f19fee229ef

### Version

2024.731.0-lazer

### Logs

not working for some reason?
![image](https://github.com/user-attachments/assets/54e8e2ad-1e57-44fa-a1bc-fcb5744fc3ab)

**Comment by bdach** [comment]
A standard laptop touchpad is treated as a mouse. So a touch setting does nothing here.

There should be another such option for mouse but I'm not sure it'll help much. So if anything that should get fixed.

**Comment by Doksha** [comment]
yeah mouse shouldn't trigger the touch buttons at all, dont think it needs an option
