### ISSUE TITLE
Ruleset only components not visible

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#29397]
### Type

Cosmetic

### Bug description

Components which set in ruleset only was hidden.

looks like only std and ctb

### Screenshots or videos

https://github.com/user-attachments/assets/cfa59664-9044-44d7-9974-bda2947ede1b

### Version

16f6e26c2e

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16590484/compressed-logs.zip)

**Comment by peppy** [comment]
Please attach your skin.

Also please try disabling beatmap skins in visual settings and see if it helps.

**Comment by cdwcgt** [comment]
yes, turn off beatmap skin will help
But the strange thing is that this beatmap does not have skin

https://github.com/user-attachments/assets/7beece61-2ab8-4a38-9aa4-c7d3a1465a19

https://osu.ppy.sh/beatmapsets/1841885#osu/3783210
