### ISSUE TITLE
Switch skin when playing replay may will cause crash

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#29398]
### Type

Crash to desktop

### Bug description

1. switch to legacy skin
2. enable classic mod and autoplay (I'm not sure if this is necessary, when I tested it, it only crashed when the classic mod was enabled)
3. switch anothor skin (need to rewind before this)
4. playing for a while, when play to the point where it started to rewind will cause a crash

### Screenshots or videos

The first video is a video recording I found by chance

the second one is my test

https://github.com/user-attachments/assets/a6733b4f-d0b7-4506-b1ae-11fe5301320e

https://github.com/user-attachments/assets/d978f9d0-49d0-4434-81f3-86dbe51e3c16

### Version

2024.731.0 also 16f6e26c2e

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16591146/compressed-logs.zip)

**Comment by cdwcgt** [comment]
This is the information I collected myself, I hope it helps

I found that disposed drawable's parent will be a `SkinableDrawable` or `OsuJudgementPiece` or `LegacyJudgementPieceOld` (see 1723486301.runtime.log)

for `SkinableDrawable`, its `ComponentLookup` will be a `HitResult`

<details>

<summary>image</summary>

![image](https://github.com/user-attachments/assets/e7c618e2-8e87-472d-a03f-47c2857d7e5d)
![image](https://github.com/user-attachments/assets/2a6b6dc0-a2ce-4eda-9482-ac8db0efb480)
![image](https://github.com/user-attachments/assets/a8548afa-b52f-4050-86fa-86057dc7d431)
![image](https://github.com/user-attachments/assets/b3f8cb60-bc02-4b63-8642-cd3d0ccf097b)
![image](https://github.com/user-attachments/assets/02c9a1d3-5e24-491b-be19-4beaea4e5c7d)

</details>

**Comment by peppy** [comment]
Your logs don't contain any exceptions. Did you upload the wrong log files?

**Comment by cdwcgt** [comment]
there is no way, because the game will crash when the exception is triggered
I exported the log on the next startup after the crash
next time I'll try to filter it out
