### ISSUE TITLE
Up and down arrow keys pass through chat

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2941]
arrow keys should scroll the chat, i think
but now they're changing beatmap in the background

logs:
[database.log](https://github.com/ppy/osu/files/2157014/database.log)

[performance.log](https://github.com/ppy/osu/files/2157016/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2157017/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2157018/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2157019/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2157020/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2157021/runtime.log)

don't know why, but can't upload network.log to github:
https://drive.google.com/open?id=1Q5bgX10VvfMG1z_VsEIo08XwuBC36WOj

video:
https://drive.google.com/open?id=1XPXjy4D3xGPQQzi0H0UXxwZ4c40ubTnK

**Comment by ticotaco72** [comment]
same with volume change
while hovered arrow keys should change volume not beatmap

**Comment by smoogipoo** [comment]
Should be resolved when we have OverlayContainer blocking `UIEvent`s via https://github.com/ppy/osu-framework/pull/1713

**Comment by plankp** [comment]
Does this still happen on the latest release?

**Comment by smoogipoo** [comment]
Seems fine on the latest master.
