### ISSUE TITLE
SkinnableSprite not working

### ISSUE THREAD

**Issue by fuyukiSmkw** [ppy/osu#29444]
### Type

Cosmetic

### Bug description

SkinnableSprite cannot show any asset although it exists.

### Screenshots or videos

![osu_2024-08-16_19-13-55](https://github.com/user-attachments/assets/8adb2dee-d07d-416a-a06c-cc100d146b18)

https://github.com/user-attachments/assets/498da95b-b003-4d6c-8883-337d2cd9d9c6

### Version

2024.816.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16636425/compressed-logs.zip)

**Comment by cdwcgt** [comment]
The first commit where this problem occurred was dcafee7cb7a938bd08ef4986a7541e5b25a54e37

git reset --hard 657da34f76 will be fine

I haven't watched it specifically, but it should be the regress of https://github.com/ppy/osu/pull/26249

**Comment by iwa** [comment]
just to add a bit on that, happens on all the layers, not only on HUD layer

**Comment by bdach** [comment]
@frenzibyte @peppy FYI

**Comment by peppy** [comment]
yeah, on my radar thanks.
