### ISSUE TITLE
Music doesn't restart if editing a skin and alt-tab-out'd

### ISSUE THREAD

**Issue by iwa** [ppy/osu#29449]
### Type

Game behaviour

### Bug description

I was searching to see if someone reported the issue about SkinableSprite not working (cf #29444) when this happened

- Go into Skin editor
- Launch a map with the "Gameplay" button
- Alt-tab the game
- Wait until the song ends
- Map restarts without the music

The map restarts with music when the game is focused
Music can be restored if you click on the progress bar

### Screenshots or videos

https://github.com/user-attachments/assets/7f8311c6-baa3-4a80-abad-9f856431b387

### Version

2024.816.0-lazer

- Game in fullscreen
- Direct3D 11 Experimental renderer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16637566/compressed-logs.zip)

**Comment by bdach** [comment]
#26022

**Comment by iwa** [comment]
mb
