### ISSUE TITLE
New Daily Challenge Intro Always Plays

### ISSUE THREAD

**Issue by Soggy-Pancake** [ppy/osu#29463]
### Type

Game behaviour

### Bug description

The new daily challenge intro animation should only play the first time it is opened. The intro animation currently plays every time the daily challenge page is opened.

### Screenshots or videos

[daily intro repeat.webm](https://github.com/user-attachments/assets/08bd3c76-b3b9-4a63-9bcd-4f8284c5b2fc)

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16641034/compressed-logs.zip)

**Comment by dravpin** [comment]
Idk i personally like seeing it everytime cause its just so clean

**Comment by Gabixel** [comment]
If opinions are accepted, perhaps a reasonable compromise would be to run it only once per session (so each time lazer is started, and not once a day), including of course the case where the challenge ends and a new one starts.

**Comment by Soggy-Pancake** [comment]
Once per session is something I thought of after dravpin said they wanted
to see it more. I think its a good comprimise for people that would like to
trigger the animation more than once per day.

**Comment by Wrongwayscout** [comment]
It could also just be made skippable.

**Comment by peppy** [comment]
Thanks for your feedback. It will not be skippable.
