### ISSUE TITLE
After resuming the game in osu!mode, there was an issue with the keyboard input.

### ISSUE THREAD

**Issue by ThirteenRoil** [ppy/osu#29483]
### Type

Game behaviour

### Bug description

When K1 is pressed before pausing the game, and then used to resume the game by pressing the orange cursor, the K1 input will fail once.

### Screenshots or videos

https://github.com/user-attachments/assets/35b61e98-0068-4219-8f4f-f84bbd358994

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16645636/compressed-logs.zip)

**Comment by bdach** [comment]
@frenzibyte

**Comment by frenzibyte** [comment]
o_o
