### ISSUE TITLE
Traceable mod ignores skin's slider border color, defaulting to white

### ISSUE THREAD

**Issue by zeklewa** [ppy/osu#29484]
### Type

Game behaviour

### Bug description

Tried a skin with blue slider border, color doesn't work with traceable mod enabled.

### Screenshots or videos

![osu_2024-08-18_00-12-37](https://github.com/user-attachments/assets/bf8707f0-d7db-42da-9cf3-70be566b820d)

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16645678/compressed-logs.zip)

**Comment by bdach** [comment]
Not a bug. Sliders in traceable use the combo colour as their border colour.
