### ISSUE TITLE
Leaderboard in replays problems

### ISSUE THREAD

**Issue by Shavixinio** [ppy/osu#29498]
### Type

Game behaviour

### Bug description

When you watch a replay **with autoplay**, the leaderboard for the map is visible, but it doesn't hide despite toggling it off.
A similar bug occurs when you watch **someone's replay**, the leaderboard is hidden but when toggling it on, nothing happens.

### Screenshots or videos

https://github.com/user-attachments/assets/bb600251-ac97-4741-a277-c4ee4960d960

### Version

2024.817.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16651471/compressed-logs.zip)

**Comment by bdach** [comment]
Intentional. See discussion at https://github.com/ppy/osu/discussions/24869.

**Comment by Shavixinio** [comment]
Intentional such as "we made it this way temporarily so we can fix this later" or intentional such as "we made it this way intentionally and it will stay this way"?, if the 2nd scenario is true, then why even add a toggle for the leaderboard when watching a replay? In stable you can normally toggle the leaderboard in any replay regardless of context.

**Comment by bdach** [comment]
The latter. If there is significant community support then maybe it can be reconsidered, but implementing this feature did not happen by omission / "fix later".
