### ISSUE TITLE
Existing objects get un-hitsound-able after saving the beatmap

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#29496]
### Type

Game behaviour

### Bug description

Hello. Self-explanatory video:

https://github.com/user-attachments/assets/a26cce45-866d-4012-bbe4-7d278dfd7063

Files:
![image](https://github.com/user-attachments/assets/116a6997-d930-4fd6-9677-0fdd6ad9459e)

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16651452/compressed-logs.zip)

**Comment by aL1NaZ4R** [comment]
I could do a temporary fix by importing it into stable, and setting all timing points sample on Normal Custom1 (was Normal default)

**Comment by kstefanowicz** [comment]
See #29028 - PR #29311 is attempting to fix

**Comment by bdach** [comment]
@kstefanowicz how are you claiming this exactly? The issues don't seem related.

**Comment by aL1NaZ4R** [comment]
> @kstefanowicz how are you claiming this exactly? The issues don't seem related.

I feel it does, since both of them fix by switching timing points to Custom via stable editor.

**Comment by aL1NaZ4R** [comment]
But the way that it plays the hitsound for newly placed objects, then it disappears after saving/reloading seems like a seperate thing.

**Comment by kstefanowicz** [comment]
@bdach the behavior in this issue's video is consistent with the behavior investigated in #29028. 

The editor plays the correct custom hitsound after placing the hit object, but when saving/testing the legacy encoder writes the song's timing points to the `.osu` file with CSS 0. This causes the hit objects to revert back to default/skin's hitsounds.

@aL1NaZ4R you can work around this currently by manually changing the CSS values in the `.osu` file from 0 to 1:
![image](https://github.com/user-attachments/assets/1b24cc4d-61f4-4ba7-b682-cebf69bcc9d4)

**Comment by aL1NaZ4R** [comment]
Umm. Looks like you're right. my bad
