### ISSUE TITLE
I don't have any text

### ISSUE THREAD

**Issue by Animenosekai** [ppy/osu#2949]
Okay just have a big problem on osu!lazer.
When I open it with Visual Studio (i can't open it without because I'm on Mac OS), the game run but I don't have any text. I put you a video with me opening osu!lazer
Hope you will propose a solution for that problem because i really want to test it on my Mac
the video:
https://youtu.be/KHninDBJtIk

**Comment by morguldir** [comment]
Duplicate of #2843 

run it with
`dotnet run -f netcoreapp2.1 --project osu.Desktop`

**Comment by peppy** [comment]
We do not support mono execution any more. Please use net core instead.
