### ISSUE TITLE
Pausing during an input bugs the next input

### ISSUE THREAD

**Issue by osu803** [ppy/osu#29507]
### Type

Game behaviour

### Bug description

I sometimes use spinners as checkpoints in long maps, which led to my discovering this bug.

Here are the conditions to reproduce the bug:
1. Hold down a button, and without releasing it, pause. 
2. Hit continue.
3. On the 'Click the orange cursor to resume' screen click the cursor using the same key/button you were holding down when you paused. This shouldn't count as an additional input on your key overlay because you have simply resumed holding the button you were previously holding down.
4. Your next input will be registered in the key overlay but will be initially ignored by the game. I.e., you will miss on a hitcircle, miss on a slider (but still be registered as following the slider), and there will be virtually no effect on spinners. 

When viewing the replay of a score affected by this bug, any miss caused by the bug will not happen, combo is not dropped, and pp is calculated according to the player's recorded inputs. Conversely, the submitted score of an affected play is calculated using the partially ignored input and corresponding miss. 

This bug is 100% consistently reproducible and I can record a video if need be but it shouldn't be too difficult for others to reproduce assuming the bug isn't somehow isolated to my version of the game.

On a totally unrelated note, could you pretty please recalculate my Save Me [Tragedy] score ppy?
I know you probably can't but it's worth asking lol.
https://osu.ppy.sh/scores/3363824564

### Submitted score viewable prior to watching replay
![osu_2024-08-19_06-14-45](https://github.com/user-attachments/assets/08bba255-414d-4739-a3e1-ef18bce3dc83)
### Recalculated score after watching the replay (idk why sliderends changed)
![osu_2024-08-19_06-21-29](https://github.com/user-attachments/assets/1704f474-2a96-459b-903a-adc2d76e454e)

### Version

2024.817.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16658413/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/29483

**Comment by osu803** [comment]
> #29483

Didn't see this, sorry.
