### ISSUE TITLE
The editor side panel repeatedly expands and shrinks after clicking the polygon button

### ISSUE THREAD

**Issue by cihe13375** [ppy/osu#29511]
### Type

Cosmetic

### Bug description

See the video. It stops when the cursor is moved away from the side panel.

### Screenshots or videos

https://github.com/user-attachments/assets/d888128d-283e-44fe-ba89-d2175f4be783

### Version

master

### Logs

-

**Comment by peppy** [comment]
Relevant: https://github.com/ppy/osu/discussions/28970

**Comment by bdach** [comment]
See also https://github.com/ppy/osu/issues/30308#issuecomment-2416364546

**Comment by peppy** [comment]
Should be kinda resolved via https://github.com/ppy/osu/pull/30387.
