### ISSUE TITLE
Slider borders are slightly bigger in lazer for classic skins

### ISSUE THREAD

**Issue by vatei** [ppy/osu#29522]
### Type

Game behaviour

### Bug description

It seems like slider borders are a few pixels wider for classic skins in lazer compared to stable.

### Screenshots or videos

Here is a comparison shot between stable and lazer
![slider-comparaison](https://github.com/user-attachments/assets/c978ac2f-a464-496b-8d0b-f68f35e13f94)

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16663367/compressed-logs.zip)
[skin.zip](https://github.com/user-attachments/files/16663381/-._CK_.Bacon.boi.1.0.-.1.-._.NM.Bacon.boi.1.0.cyperdark.lz.zip)

**Comment by bdach** [comment]
There have been several attempts to match stable with respect to this, the latest being #10041. I'm not sure we can do any better.
