### ISSUE TITLE
beatmaps are not sorted correctly by difficulty with mods that adjusts difficulty 

### ISSUE THREAD

**Issue by Airkek** [ppy/osu#29524]
### Type

Game behaviour

### Bug description

The list of difficulties is sorted (and filtered) by nomod star rating values. In stable, it's easy to farm, for example, 7.2* DT maps in a row; lazer lacks this feature. :(

### Screenshots or videos

![Screenshot_2024-08-19-23-59-26-34_25a1a32208bbcdc1d450b7aa854bb161](https://github.com/user-attachments/assets/9ff0697f-3037-4df9-8d73-b0a740e2895d)
![Screenshot_2024-08-19-23-59-29-00_25a1a32208bbcdc1d450b7aa854bb161](https://github.com/user-attachments/assets/42b6c21b-1de1-4c26-8f1f-177aee30ac28)

### Version

2024.816.0-lazer

### Logs

[logs.zip](https://github.com/user-attachments/files/16665360/logs.zip)

**Comment by ssz7-ch2** [comment]
https://github.com/ppy/osu/issues/12628
