### ISSUE TITLE
When Daily Challenge has a forced mod that is only on a certain ruleset, the game will display a "unknown" mod

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu#29559]
### Type

Cosmetic

### Bug description

Pretty self explanatory

![image](https://github.com/user-attachments/assets/c0af4c8a-e1d7-4dca-86aa-6ef3c173cd21)

### Version

osu! version: Lazer 2024.817.0 (latest)

### Logs

-cosmetic issue

**Comment by Octostomp** [comment]
Didn't happen today with hidden, maybe because it has an icon.

**Comment by Tenexxt** [comment]
I think it's because every (main atleast) ruleset has a Hidden mod, so it has an icon
