### ISSUE TITLE
left/right arrow buttons don't work properly in text boxes globally

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2955]
they just aren't working anywhere but chat, where sometimes work as wanted sometimes rewind beatmaps when you are in beatmap selection menu or don't work too

logs:
[database.log](https://github.com/ppy/osu/files/2162621/database.log)
[network.log](https://github.com/ppy/osu/files/2162622/network.log)
[performance.log](https://github.com/ppy/osu/files/2162623/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2162624/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2162625/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2162626/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2162627/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2162628/runtime.log)

**Comment by peppy** [comment]
This has been resolved (can no longer reproduce keys hitting song select when chat is displayed).
