### ISSUE TITLE
Cannot scrub on timeline of now playing overlay in online screens

### ISSUE THREAD

**Issue by Wrongwayscout** [ppy/osu#29563]
### Type

Game behaviour

### Bug description

The timeline bar on the now playing window is not interactable while in the daily challenge menu.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/cbb2843d-e490-43f2-8ce2-a807e6dc220c)

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16707496/compressed-logs.zip)

**Comment by bdach** [comment]
It's also not interactable in multiplayer and playlists, for the same reason.

https://github.com/ppy/osu/blob/df94c22a29dc4000bf1187f941eeaf387472cfbe/osu.Game/Overlays/MusicController.cs#L116-L122

If it's an issue in daily challenge (which is arguable, although I tend to agree), it's an issue everywhere else as well.
