### ISSUE TITLE
Performance Issues to certain a map

### ISSUE THREAD

**Issue by lendell2000** [ppy/osu#29561]
### Type

Performance

### Bug description

Huge performance loss with storyboard to this specific map. Compared it with Osu! Stable and there are no performance issues to be seen. Check attached screenshots for comparison
Crack Traxxxx - Lite Show Magic (t+pazolite vs C-Show): https://osu.ppy.sh/beatmapsets/139525#osu/348549

### Screenshots or videos

![Osu Lazer Lag](https://github.com/user-attachments/assets/bd183a1d-0b39-4c19-ac77-d4a323455ded)
![Osu stable no lag](https://github.com/user-attachments/assets/b9de195f-be07-439f-880f-8d776db45bb8)

### Version

2024.821.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16706419/compressed-logs.zip)

**Comment by smoogipoo** [comment]
There's already a few issues regarding storyboard performance: https://github.com/ppy/osu/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Astoryboard+label%3Atype%3Aperformance
