### ISSUE TITLE
Leaderboards breaking with too many mods.

### ISSUE THREAD

**Issue by MineTurtlee** [ppy/osu#29574]
### Type

Cosmetic

### Bug description

This level named "Internet Yamero" with the hard difficulty has this bug (Daily Challenge) but I just kinda found it in the map finder

### Screenshots or videos

![image](https://github.com/user-attachments/assets/ffb037e4-4ac9-4c02-aee6-c801f0a45b4e)

### Version

2024.807.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16726280/compressed-logs.zip)

**Comment by MineTurtlee** [comment]
I suggest a fix that does "+x" when theres too many (though this is not planned haha sorry)

**Comment by bdach** [comment]
Re-read what I said, look at how the daily challenge leaderboard looks, and reconsider whether you needed to type that out.
