### ISSUE TITLE
osu!catch droplets efect stacking in the editor

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu#29575]
### Type

Cosmetic

### Bug description

In the editor, if the catcher is in a spot where a droplet is, and the slider is edited the effect stacks, resulting in a big white ball

### Screenshots or videos

https://github.com/user-attachments/assets/2669366a-968c-4fc4-a5ec-73e11c6a1ede

### Version

osu! version: Lazer 2024.817.0 (latest)

### Logs

Cosmetic issue

**Comment by snalgae** [comment]
duplicate of #28535
