### ISSUE TITLE
Crash when you change the time of a song quickly back and forth

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#2958]
[runtime.log](https://github.com/ppy/osu/files/2164562/runtime.log)

This only happens in the song selection. osu! gets very laggy and does crash after a while

**Comment by peppy** [comment]
Could you reproduce this and provide another log file? The one you provided does not contain any crash information.

**Comment by Lolihunter1337** [comment]
just reproduced it.
[runtime.log](https://github.com/ppy/osu/files/2192233/runtime.log)
[performance.log](https://github.com/ppy/osu/files/2192234/performance.log)

This is everything i get

**Comment by peppy** [comment]
Could you check event viewer for any further information on the crash?

**Comment by Lolihunter1337** [comment]
nothing there.

**Comment by Lolihunter1337** [comment]
should i redo it with performance logging enabled?

**Comment by peppy** [comment]
Could you please re-test this? There is a high probability it was the result of a thread deadlock which has since been resolved.

**Comment by Lolihunter1337** [comment]
still happens
