### ISSUE TITLE
mania combo counter can overlap break overlay on some legacy skins

### ISSUE THREAD

**Issue by bdach** [ppy/osu#29599]
### Type

Cosmetic

### Bug description

Forwarding from community forums: https://osu.ppy.sh/community/forums/posts/9651623

As I said there: 

> This is pretty awful. Not sure what the solution is. Maybe make break overlay be part of skinning system or something so that old skins can get a break overlay that doesn't interfere with gameplay visuals.

### Screenshots or videos

![CXhh2id](https://github.com/user-attachments/assets/562b02f9-acba-4c47-be8e-98cb90e2181c)

### Version

not reported but I assume latest master should do

### Logs

n/a

**Comment by peppy** [comment]
While we could fix this locally, I think we may just need to redesign the break overlay. Because if users place skin elements around the same are the same issue is going to arise.

@arflyte I don't suppose you've had a look at any improvements around the break overlay?

**Comment by arflyte** [comment]
Damn the break overlay is pretty dated; I think it's one of my first year stuff. Haven't looked into it. Any new functions to it or just need a new design?

**Comment by peppy** [comment]
It probably needs to show the current rank, and potentially be user customisable in the future to show more information.

It should also be beat-synced in animation.

I'm fixing it up with a temporary improvement for now.
