### ISSUE TITLE
Mouse cursor cant go below a portion of the screen when fullscreen is activated on mac

### ISSUE THREAD

**Issue by axellank** [ppy/osu#29601]
### Type

Crash to desktop

### Bug description

Sometimes when playing on fullscreen the cursor cant go below a portion of the screen this portion is bigger if the resolution is set to a higher one, it gets fixed when you change the resolution to any res and then revert it back to the one you use 

### Version

2024.731.0 lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16742213/compressed-logs.zip)

**Comment by PLGGitHub1** [comment]
Borderless Fullscreen?

**Comment by frenzibyte** [comment]
Duplicate of https://github.com/ppy/osu/issues/26865
