### ISSUE TITLE
 Linux distribution via distribution agnostic format

### ISSUE THREAD

**Issue by lionirdeadman** [ppy/osu#2960]
It would be nice if osu were distributed on Linux through one of the many distro agnostic formats such as Snap, Flatpak or AppImage.

(Reposting this from https://github.com/ppy/osu-framework/issues/1650, I created the issue on the wrong repository, sorry about that.)

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by peppy** [comment]
Is it feasible to create AppImages from a non-linux system? If someone makes me a script to do this, I'm happy to manually create them for each release for the time being.

script should

- run on macOS
- create a signed package from the output of `dotnet publish`

for reference, this is what i'm using for mac builds currently:

```sh
cd ~/Projects/osu
dotnet publish -f netcoreapp2.1 -r osx-x64 osu.Desktop --configuration Release
rm -r /Applications/osu\!.app/Contents/MacOS/*
cp -r osu.Desktop/bin/Release/netcoreapp2.1/osx-x64/publish/* /Applications/osu\!.app/Contents/MacOS
codesign --deep --force --verify --verbose --sign "$DEPLOY_CERT" /Applications/osu\!.app
ditto -ck --rsrc --keepParent --sequesterRsrc /Applications/osu\!.app osu\!.app.zip

# check code signing
spctl --assess -vvvv /Applications/osu\!.app
```

**Comment by peppy** [comment]
Builds must be able to be produced on any platform. This is a personal requirement.

**Comment by user5145** [comment]
If wine is ok then there is a project which wraps games into wine and flatpak, It's winepak/applications. Osu's an issue number 25. Games can be installed by e.g. gnome-software, if repository was added.
 
there is a good comparison. 
https://askubuntu.com/questions/866511/what-are-the-differences-between-snaps-appimage-flatpak-and-others

And if I can say i prefer flatpak, like this flatpak > snap > appimage, and it seems to be the same for major linux distributions, except ubuntu. Flatpak is supported in gnome-software and chromium OS and is being tested with steam. Appimage probably never was liked :<

I'm just porting one application to flatpak and it's really easy. it's basically copy-paste of a game and necessary libraries and it just works.

And thanks for this beautiful game :)

**Comment by peppy** [comment]
This is lazer, which does not require wine.

**Comment by user5145** [comment]
^^ I makes it even easier.
Thanks for the info, I haven't known about lazer.

**Comment by lionirdeadman** [comment]
I'll try building a flatpak since I don't think there'll be the possibility of any of those package managers being built on windows. I'll post updates here. I hope you don't mind, @peppy

**Comment by peppy** [comment]
Go for it, just don't publish it on a package manager. Optimally we're looking to have a packaging script PR'd so we can do this ourselves.

**Comment by lionirdeadman** [comment]
Yes, I'd PR that script. We'd probably build it with Travis-CI since none of the formats mentioned here can easily be built on all platform. It also makes it very easy for you.

**Comment by probonopd** [comment]
If you build on Travis CI then it is easy to build an AppImage as well.

**Comment by peppy** [comment]
As food for thought, appveyor also supports linux runs too.

**Comment by lionirdeadman** [comment]
I will consider AppVeyor but will prioritise Travis-CI since that's something that seems to be more standard.

Also, yeah, Travis CI could also easily build an AppImage but I personally prefer Flatpak because of the repositories, it makes it easier to discover software.

Since I decided this wouldn't be used in favour of flatpak bundles until osu becomes more stable, it makes that argument a bit less valuable other than making it easier in the future to publish on Flathub.

I'm already working on a flatpak with someone (they're doing most of the work honestly) so let's not make the same effort in different ways.

(Sidenote: I don't know if it was an accident but you edited probonopd's comment)

**Comment by peppy** [comment]
The host is less important.

Also for what it's worth, you will likely want to commit this to [ppy/osu-deploy](https://github.com/ppy/osu-deploy)

Your PR should not be dependent on any CI engine. It should just create the packages.

**Comment by lionirdeadman** [comment]
That script will not be dependent on any CI engine then, I'll leave that up to you.

I was simply mentioning CIs because you can't create a flatpak on Windows or Mac (although it could be done through WSL or simply a VM but that just sounds like a pain).

**Comment by peppy** [comment]
See osu-deploy. There's already platform specific code for macOS.

**Comment by lionirdeadman** [comment]
I think you're misunderstanding. 

Flatpak does not work on MacOS or Windows, it is Linux exclusive and can only be built on Linux. My script will not use any of the code in that repository.

I will simply make a PR to that repository to add the files required for flatpaks. (YML for build, .desktop for desktop shortcut, icon and the Appstream.xml to allow viewing of general package information inside gnome-software or similar package managers)

**Comment by peppy** [comment]
Yes, so add that to osu-deploy in a similar way to the macOS specific deploy (which only runs on macOS).

**Comment by lionirdeadman** [comment]
Ah, sorry. My bad, I'll look at it. I feel dumb, haha.

**Comment by probonopd** [comment]
> Also, yeah, Travis CI could also easily build an AppImage but I personally prefer Flatpak because of the repositories, it makes it easier to discover software.

Why not have both :-) they address different needs.

**Comment by lionirdeadman** [comment]
> > Also, yeah, Travis CI could also easily build an AppImage but I personally prefer Flatpak because of the repositories, it makes it easier to discover software.
> 
> Why not have both :-) they address different needs.

Having two builds for linux would be both redundant, require more maintenance and would be counter-productive to saving developers' time.

**Comment by probonopd** [comment]
> Having two builds for linux would be both redundant, 

No, as they serve different goals. AppImages are single-file portable apps whereas the others are not.

> require more maintenance and would be counter-productive to saving developers' time.

That's true though ;-)

**Comment by sr229** [comment]
@probonopd we can always try Flatpak and Snaps

**Comment by kirbyfan64** [comment]
Don't Flatpak and Snap overlap a lot more than Flatpak and AppImage?

As a side note, I'm currently working on an osu!lazer Flatpak, so *Coming soon to a repository near you*.

**Comment by probonopd** [comment]
> Don't Flatpak and Snap overlap a lot more than Flatpak and AppImage?

Indeed. AppImage uses a no-repository, no-install, portable single-file approach.

**Comment by sr229** [comment]
@probonopd @kirbyfan64 Flatpaks and Snaps can come in a no-repository distribution FYI, though AppImage is still winning on this, tbf

**Comment by lionirdeadman** [comment]
The no-repository model of AppImage is also it's biggest disadvantage. The advantage of Flatpak (can't talk for snap) is that the environment is fully-reproduceable since they often rely and run on standard platforms which is not something you can say about AppImage which will undoubtedly mean distro-specific bugs..

In any case, I think one format is enough, let's not start a format debate and feel free to PR your own format if @peppy wants more than one. Thanks @kirbyfan64 :heart:

**Comment by lionirdeadman** [comment]
Whether we distribute through Flathub or not will be @peppy's decision in the end, we can always just do flatpak-bundles.

**Comment by sr229** [comment]
Setting this on my TODO right now: you can track it over at sr229/osu#1

**Comment by peppy** [comment]
As stated above, please do not add travis as it is unnecessary.

**Comment by sr229** [comment]
Initial PR now done on ppy/osu-deploy#1 - Will now package osu! into a GPG-signed AppImage (current cert will not work)

**Comment by QuantumAnon** [comment]
What's the status on this ppy/osu-deploy#1? I notice it's been left untouched for quite some time.

**Comment by peppy** [comment]
Hasn't been tested yet.

**Comment by probonopd** [comment]
Can the AppImage be downloaded somewhere for testing? Thanks.

**Comment by peppy** [comment]
The idea would be running the `osu.Deploy` application to *generate* it to test.

**Comment by SlawekNowy** [comment]
Forked osu.Deploy and modified it to create AppImages (still requires few files for AppDir though).

https://github.com/SlawekNowy/osu-deploy

**Comment by peppy** [comment]
Rather than forking, are you able to PR your changes?

**Comment by SlawekNowy** [comment]
Yes, it's mostly the same, only that I changed last lines and added AppDir stuff.

Appimage now wants env variable ARCH to be set, and --comp argument doesn't work right now.

**Comment by sr229** [comment]
@SlawekNowy recommend you merge your work with mine and let's work together to get osu.Deploy to work properly on AppImage should you wish.

**Comment by SlawekNowy** [comment]
@sr229 sent pull request to your fork of osu-deploy.

**Comment by jai-x** [comment]
Just to provide an additional opinion, I disagree with using an AppImage or any other pre-packaged format for distributing on Linux.

The normal distrubution format for Linux is simply a `.tar.gz` tarball containing the program executable and any additional config files and program directories. This allows for better integrations with Linux package managers and using the system package manager should be the preferred method of keeping the program updated.

Supplying shared object program libraries with the program should also not be a responsibility of the program package and should delegated to the system package manager. In the case of `libbass` and other non-standard libraries, it may be acceptable to bundle them.

**Comment by lionirdeadman** [comment]
> The normal distrubution format for Linux is simply a .tar.gz tarball containing the program executable and any additional config files and program directories.

Which doesn't work on all linux distributions, doesn't integrate in the desktop environment without effort, doesn't auto-update and is just kinda bad. There's a reason people wanna move away from that.

> This allows for better integrations with Linux package managers and using the system package manager should be the preferred method of keeping the program updated.

Should a game be part of the system though? Should osu! have to wait 10years for Debian to update it? No, that's why these agnostic formats were created, one source, updated regardless of system, works everywhere. Although... AppImage doesn't provide that which is really a bummer.

>Supplying shared object program libraries with the program should also not be a responsibility of the program package and should delegated to the system package manager.

In the case of AppImage, it is osu!'s responsability to update them but in the case of Flatpak or Snap, most libraries are provided by their respective runtime which means osu! developers don't have to care about them.

**Comment by jai-x** [comment]
@lionirdeadman I understand the relative advantages and disadvantages that both approaches have. I was just stating my preference for the record for how I think osu!lazer should be packaged for Linux systems. I don't expect anyone to change their mind based on my comments.

**Comment by probonopd** [comment]
> Should a game be part of the system though? Should osu! have to wait 10years for Debian to update it? No, that's why these agnostic formats were created, one source, updated regardless of system, works everywhere. Although... AppImage doesn't provide that which is really a bummer.

AppImage is a self-mounting disk image that executes whatever the developer has put inside it. It can't magically fix the issues the "Linux desktop" is suffering from (fragmentation, lack of clear long-term compatibility guarantees). A well-built AppImage can run on all current mainstream distributions; if that is not sufficient one would have to bundle everything (down to glibc and ld-linux) as a private copy and use nothing (besides the kernel and Xorg) from the system. Can be done with AppImage, too - although it's generally not recommended since it may be perceived as "bloated".

**Comment by sr229** [comment]
I want to disagree with some of the contradictions here, while I agree library management should not be our problem, a game should NEVER be part of the system. Take a look at Steam's game handling for example. The only time you want it to be part of anything of the system if its from a package manager, or its just an updater for the game (which makes more sense). I also want to disagree using `.tar.gz` as a de facto method since that's not **VERSIONED** properly by the **package manager** because it was **never** part of the database to update the thing.

**Comment by lionirdeadman** [comment]
> It can't magically fix the issues the "Linux desktop" is suffering from (fragmentation, lack of clear long-term compatibility guarantees).

I think trying to make the free desktop non-breaking is a respectable goal but I believe that trying to make the free desktop standardized in the ways needed for platform agnosticism would be near impossible or restrict distributions to do what they want because of other people's decisions unless they want to forfeit applications being usable on their desktop which would simply be horrible. It would no longer give the freedoms that it once gave.

> A well-built AppImage can run on all current mainstream distributions; if that is not sufficient one would have to bundle everything (down to glibc and ld-linux) as a private copy and use nothing (besides the kernel and Xorg) from the system. Can be done with AppImage, too - although it's generally not recommended since it may be perceived as "bloated".

And that's exactly why I think it's the wrong way of doing things. 

If I truly want AppImage to be available for everything like it wants to be, I need to bundle the whole desktop basically which is just... a terrible idea on the storage-side for one since there is no deduplication of any kind between AppImages and even more so on the security-side, I really don't want to leave a whole desktop stack in the hands of application developers no matter how good they are, it's just much harder that way and will result in problems.

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu-deploy/pull/36.
