### ISSUE TITLE
Difficulty multipliers do not apply in daily challenges

### ISSUE THREAD

**Issue by iijj22gg** [ppy/osu#29617]
### Type

Cosmetic

### Bug description

Similarly to [#29313](https://github.com/ppy/osu/issues/29313), the difficulty color and star rating are not affected by mods in daily challenges. 

### Screenshots or videos

![osu_2024-08-27_09-50-39](https://github.com/user-attachments/assets/f05bffc8-f047-488a-a03a-542f169c0f7b)

+Reference:
![osu_2024-08-27_09-21-47](https://github.com/user-attachments/assets/5bf7721c-79f6-41b4-b30d-070c64b8809b)

### Version

2024.817.0-lazer

### Logs

None provided

**Comment by bdach** [comment]
I'll close this as duplicate because it likely is.
