### ISSUE TITLE
Components using loadComponentSingleFile need to be checks for not-yet-loaded safety

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2962]
Foe example, `UserProfileOverlay.ShowUser` may be called before the `UserProfileOverlay` is ready for display. `api` will be `null` as a result because `BDL` hasn't been run yet.

We should check each of these single file components to ensure all such cases are correctly guarded against (`Schedule` or even better, blocking for load).

This should hopefully never have to happen – components initial load should be light enough that they are ready in time – so I think hard blocking is an OK scenario if we can find a method of implementation (currently it doesn't seem possible as `LoadTask` is not exposed).

I only managed to repro this by attaching a debugger in its currently underperforming state (see https://github.com/ppy/osu-framework/issues/1664)

**Comment by Joehuu** [comment]
Seems to be addressed in https://github.com/ppy/osu/commit/f038c579f01b89327c57f0ff307c0917957c9667.
