### ISSUE TITLE
Pausing in standard while a key is held makes the next key not count for hitcircles/sliderheads after unpausing.

### ISSUE THREAD

**Issue by MegaGamer22** [ppy/osu#29664]
### Type

Game behaviour

### Bug description

I already saw a closed issue about a similar problem, but I'm not sure if it's still the same as now.

When pausing while a key (B1 or B2) is held, after unpausing, no matter how long the player takes on performing the next input, it will NOT count for clicking a circle.
Just to clarify, this will NOT get the input stuck at holding, it'll be released.

I'm not sure if this is intentional or not, but it's been driving me off for a while now.

### Screenshots or videos

https://github.com/user-attachments/assets/6b68bcaa-208c-4490-b39b-10c8fd24f43a

https://github.com/user-attachments/assets/e7238840-167f-45d5-9db5-5f23dacb2d53

### Version

2024.817.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16821645/compressed-logs.zip)

**Comment by Joehuu** [comment]
Already fixed in https://github.com/ppy/osu/pull/29500. Just need to wait for next release.
