### ISSUE TITLE
Beatmap panel shows star rating without considering applied mod

### ISSUE THREAD

**Issue by Proxima36** [ppy/osu#29689]
### Type

Cosmetic

### Bug description

it shows correct star rating in song select, but not in daily challenge, multiplayer and playlists

### Screenshots or videos

Song select
![osu!_2024-09-04_10-22-36](https://github.com/user-attachments/assets/41e9b410-b6af-430f-a2ef-e2df2522bc1f)

Daily challenge
![osu!_2024-09-04_10-23-07](https://github.com/user-attachments/assets/93a0a53f-6011-47bb-a9c8-150472d04dab)

Multiplayer
![osu!_2024-09-04_10-24-44](https://github.com/user-attachments/assets/1400b3e5-ca81-4ccb-b385-ae740260c32a)

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16862515/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/14701
