### ISSUE TITLE
keyboard and mouse issue

### ISSUE THREAD

**Issue by Rrebmoz** [ppy/osu#29684]
### Type

Game behaviour

### Bug description

K1 blocks M1, K2 blocks M2 and vice versa.
K1 does not block M2, K2 does not block M1 and vice versa.
"Disable mouse buttons in play mode" option is not enabled.

### Version

b20240820beta

### Logs

[Logs.zip](https://github.com/user-attachments/files/16852500/Logs.zip)

**Comment by Joehuu** [comment]
Behavior is intentional for both stable and lazer. It'll only be changed with a mod, see https://github.com/ppy/osu/discussions/18024#discussioncomment-2678389.
