### ISSUE TITLE
(mania) Issues with looping "gameplay" section in lazer skin editor

### ISSUE THREAD

**Issue by GameTilDead** [ppy/osu#29694]
### Type

Game behaviour

### Bug description

Opening up and using the skin editor works normally, it's what happens to the actual gameplay when being in the editor for long enough. Here are some things I've noticed, in order of how important I think they are to fix (descending):

1) The bot sometimes misses a note after the song loops, likely due to the scrolling replay and notes existing within the time it takes to scroll completely. As I'm writing this issue, it's still looping and every few minutes the miss sound plays (despite the window being out of focus? I have minimized volume set to 0)
2) After exiting the editor (not the song), the song will still loop but fails to play the music.
3) The combo counter doesn't completely reset after scrolling finishes, additive with each loop of the song. This is the main reason I came here, and started finding other things as I went on.

### Screenshots or videos

Context: I just exited the skin editor after being in the gameplay section, however after the next song loop there is still combo (it's quite possible the custom DT mod had something to do with it)
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/cccba9bf-bd66-4996-9016-d026e174918a">

### Version

2024.817.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16873107/compressed-logs.zip)

**Comment by Tenexxt** [comment]
>After exiting the editor (not the song), the song will still loop but fails to play the music.

More specificaly: when the song loops when the game is minimised for some time before the loop, the game will stop playing the music, but the auto will keep playing.
This fixes itself if you enter the game again and the loop restarts without it being minimised, or if you just skip/go back to a another part of the replay.

1. and 3. doesn't occur to me, or atleast i don't know how to make them appear more specifically.
If you know, could you tell me what could make them happen more specifically?

**Comment by bdach** [comment]
This is three separate issues and be reported as such. And all of them have been reported already.

1. https://github.com/ppy/osu/issues/17413
2. https://github.com/ppy/osu/issues/26022
3. https://github.com/ppy/osu/issues/21732

**Comment by GameTilDead** [comment]
> 1 and 3 [don't] occur to me, or at least I don't know how to make them appear

To get 1 to happen, I think it depends on the song. My guess is that it has to have a higher scroll-to-playback ratio than length-to-break (i.e. the start of the song happens before the loop has finished scrolling back to the beginning).
For 3, I have no clue. I think it's this whole "game goes back a frame" thing they've been having over at osu!standard and the loop is intended to happen the moment the last notes are hit. This in theory would cause the game to first process the end of the song, reset the combo counter to zero (while scrolling, it keeps that internally), and then process the final notes.

**Comment by GameTilDead** [comment]
> This is three separate issues and should be reported as such. And all of them have been reported already.
> 
> 1. [Rewinding some replays can cause incorrect misses #17413](https://github.com/ppy/osu/issues/17413)
> 2. [Beatmap song does not restart in the skin editor if the window is minimised #26022](https://github.com/ppy/osu/issues/26022)
> 3. [The combo adds +1 when rewinding to the beginning of the mania replay #21732](https://github.com/ppy/osu/issues/21732)

How did I not find any of this, I looked for several minutes
