### ISSUE TITLE
Daily challenge intro SR not taking mods into account

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu#29696]
### Type

Game behaviour

### Bug description

Self explainatory, here is a comparison:

The intro SR: 
![image](https://github.com/user-attachments/assets/180962f8-1003-4e5b-a0f8-c5ef63b178c4)

Actual SR: 
![image](https://github.com/user-attachments/assets/196cc928-6b14-4118-953c-6aab64e3f129)

### Version

osu! version: Lazer 2024.817.0 (latest)

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16873850/compressed-logs.zip)

**Comment by bdach** [comment]
tracking with https://github.com/ppy/osu/issues/14701
