### ISSUE TITLE
scrolling in social browser

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2969]
there's no slider to scrool in social browser
when you try to scroll social browser with up/down arrow keys they're changing volume
so scrolling is possible only by mouse wheel and by draging list with mouse

logs:
[database.log](https://github.com/ppy/osu/files/2172119/database.log)
[network.log](https://github.com/ppy/osu/files/2172120/network.log)
[performance.log](https://github.com/ppy/osu/files/2172121/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2172122/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2172123/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2172124/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2172125/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2172126/runtime.log)

**Comment by ticotaco72** [comment]
and maybe left/right arrow should change category
e.g. rank->name

**Comment by ticotaco72** [comment]
same with osu!direct
scrolling should be possible with arrows and scrolling bar
left/right arrows should work as mentioned higher, i think

**Comment by peppy** [comment]
See ppy/osu-framework#1362.
