### ISSUE TITLE
Can't play song after the music has ended

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#297]
* Summary: In the song select screen, if you try to play the song when no music is playing the game field will open but no hitobjects will appear. Everything else (keycounters, volume sliders, debug tools) still works.
* Expected: Normal gameplay.
* Actual: Silence and nothing to hit.
* Steps to reproduce: [Short beatmap](https://new.ppy.sh/beatmapsets/398977#osu/867511), wait for music to be over, wait 10 more seconds (we want the file not to be playing), start playing. 100% reproducible.

**Comment by peppy** [comment]
Thanks for the report, but please read the issue template as to why we aren't accepting reports like this for now.

**Comment by LittleEndu** [comment]
It's not like I wanted to fix that or anything.
Found the cause, [Line 38](https://github.com/ppy/osu-framework/blob/2f03fae533293bf255a942569c07396f853378f3/osu.Framework/Audio/AudioCollectionManager.cs#L38), but have no idea how to fix it...
