### ISSUE TITLE
Clicking on the song artist/title will search without the `artist/title=""{keyword}""` filter in beatmap listing

### ISSUE THREAD

**Issue by ZenoG2** [ppy/osu#29708]
### Type

Game behaviour

### Bug description

title

### Screenshots or videos

![Screenshot 2024-09-06 093335](https://github.com/user-attachments/assets/97aa7e02-56ce-4b3e-89ae-81ec5c8fdb3b)
![Screenshot 2024-09-06 093341](https://github.com/user-attachments/assets/47b51fbb-4538-4e9a-8f71-11bf6a9dc543)
![Screenshot 2024-09-06 093401](https://github.com/user-attachments/assets/2f3ae290-e670-4304-8371-47f687d6c136)

### Version

2024.817.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16903845/compressed-logs.zip)

**Comment by Joehuu** [comment]
Should have double quotes like in web.

**Comment by ZenoG2** [comment]
This issue still applies to the source of the song.
Requesting the issue to be reopened.

**Comment by Joehuu** [comment]
That has been implemented in https://github.com/ppy/osu/pull/30400.
