### ISSUE TITLE
Osu!lazer scoring broken

### ISSUE THREAD

**Issue by n3vesl1s** [ppy/osu#29716]
### Type

Game behaviour

### Bug description

I just updated osu!lazer and i get this message every time I want to play

### Screenshots or videos

![osu!_GKPy5k2ZN0](https://github.com/user-attachments/assets/d3121e04-6862-42ac-94e7-22310a600551)
![osu!_8L0ipMQbV1](https://github.com/user-attachments/assets/d9494cad-2c3e-4a11-8b67-6a43465f919a)

### Version

2024.906.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16907190/compressed-logs.zip)

**Comment by peppy** [comment]
We're aware and working on a fix.

Your options are to downgrade to the last version or wait a bit longer while we resolve it.
