### ISSUE TITLE
Arrrow keys change settings at too big intervals

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#2972]
When changing settings, e.g. the audio offset, it is often easier to just hover the cursor over it and use the arrow keys to adjust the setting than to drag the bar with the mouse.
![image](https://user-images.githubusercontent.com/35152647/42420187-231b93c2-82c2-11e8-8e45-682dda8a1740.PNG)
However, in osu!lazer using the arrow keys is not an accurate way of adjusting, as the intervals the setting gets changed by are way too big. For the audio offset, it's 100ms, where stable changes it at 1ms at a time. Other setting like background dim also get changed by a large amount when using the arrow keys.

As this is not comfortable to work with and does not provide any accuracy, I propose that the behavior of stable is copied so that arrow keys change the selected setting at the smallest possible interval (for audio offset that would be 1ms).

**Comment by HoutarouOreki** [comment]
I think I'm able to handle this.
