### ISSUE TITLE
Mirror mod flips objects on wrong axis

### ISSUE THREAD

**Issue by Skylandia** [ppy/osu#29720]
### Type

Game behaviour

### Bug description

Using the horizontal mirrored axes mod will mirror the map on the vertical axes and vice versa.

### Screenshots or videos

Normal:
![osu_2024-09-07_00-26-50](https://github.com/user-attachments/assets/a76b6d1e-b49a-4823-ba05-60b3c65aed77)
Using Mirrored (horizontal axes)
![osu_2024-09-07_00-26-33](https://github.com/user-attachments/assets/159da86f-1359-4084-90aa-71e7784a78e2)
Using Mirrored Mod (vertical axes)
![osu_2024-09-07_00-28-32](https://github.com/user-attachments/assets/90b31a93-29bc-4661-8acd-58d4b66a04fe)

### Version

2024.906.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16907827/compressed-logs.zip)

**Comment by bdach** [comment]
looks correct to me?

**Comment by Skylandia** [comment]
![Untitled](https://github.com/user-attachments/assets/5be66339-9d09-4c84-aff1-fff2f7afd58d)

**Comment by bdach** [comment]
![CNX_Precalc_Figure_01_05_012.jpg](https://github.com/user-attachments/assets/0bad61b1-428a-4737-b7e1-eaf4467d96a7)

**Comment by Skylandia** [comment]
I understand a horizontal reflection mirrors over the vertical axis and vice versa, but that contradicts the tooltip message
![osu_2024-09-07_01-41-10](https://github.com/user-attachments/assets/382d038c-c404-4ed5-bad2-4a9c1f9c62e6)
