### ISSUE TITLE
Game "nukes" itself after the latest update

### ISSUE THREAD

**Issue by Halbour** [ppy/osu#29722]
### Type

Game behaviour

### Bug description

I downloaded the game normally from the auto-updater. After restarting, a window popped up saying "updating to version 2024.906.1" and when it finished, it just deleted my taskbar and desktop shortcuts, and launched the game. I exited, and went to the osu! folder to search for the .exe, but it just _doesn't exist_... I have 0 idea about what and why.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/3b3a2032-dd6e-4b5b-a874-cac14593daeb)
![image](https://github.com/user-attachments/assets/e040be52-595b-46ef-8fb3-a3c0c2b1b3eb)

### Version

2024.906.1

### Logs

**I'm unable to provide the logs file, as I can't access osu!lazer anymore.**

**Comment by bdach** [comment]
> ![image](https://private-user-images.githubusercontent.com/86569310/365166280-3b3a2032-dd6e-4b5b-a874-cac14593daeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjcxMTksIm5iZiI6MTcyNTYyNjgxOSwicGF0aCI6Ii84NjU2OTMxMC8zNjUxNjYyODAtM2IzYTIwMzItZGQ2ZS00YjViLWE4NzQtY2FjMTQ1OTNkYWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEyNDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YTUyMjk5ZGQ2MzUxZjViYWE2NjNmYTQ2OTk5MmIxYjVmYjExN2Y0MjY1ODEwYjZjMmViNTdlYTQyNWI0MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLcP3Hcn_Es_RsxwGwGU4spd7mdBRL_GfqvNqvuFMDs)

What is this screenshot showing? That looks like something osu! still exists? What happens when you click this item?

Currently we're aware of lazer changing shortcut title from "osu!(lazer)" to "osu!" but nothing about it just deleting itself.

**Comment by necocat0918** [comment]
it also happens to me, but instead of deleting literally everything, it replaces "osu! (lazer)" to "osu!" so stable is gone
just please change it back

**Comment by Halbour** [comment]
> > ![image](https://private-user-images.githubusercontent.com/86569310/365166280-3b3a2032-dd6e-4b5b-a874-cac14593daeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjcxMTksIm5iZiI6MTcyNTYyNjgxOSwicGF0aCI6Ii84NjU2OTMxMC8zNjUxNjYyODAtM2IzYTIwMzItZGQ2ZS00YjViLWE4NzQtY2FjMTQ1OTNkYWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEyNDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YTUyMjk5ZGQ2MzUxZjViYWE2NjNmYTQ2OTk5MmIxYjVmYjExN2Y0MjY1ODEwYjZjMmViNTdlYTQyNWI0MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLcP3Hcn_Es_RsxwGwGU4spd7mdBRL_GfqvNqvuFMDs)
> 
> What is this screenshot showing? That looks like something osu! still exists? What happens when you click this item?
> 
> Currently we're aware of lazer changing shortcut title from "osu!(lazer)" to "osu!" but nothing about it just deleting itself.

I did not know that, apparently. That deleted my stable shortcut, I guess. 
This is becoming weirder... I know see lazer is installed in my A: drive, but I guess it installed itself to C: too?
Even if this is not a bug, this update was insanely confusing, even for a techie like me.
I mean - how do I change the installation location? the installer was really weird and doesn't give me any options, and I can't seem to find a "repair osu!" like it had on stable.

**Comment by bdach** [comment]
> it also happens to me, but instead of deleting literally everything, it replaces "osu! (lazer)" to "osu!" so stable is gone just please change it back

yes we know

> This is becoming weirder... I know see lazer is installed in my A: drive, but I guess it installed itself to C: too?

yes the game always puts some files (the executables) on C: drive even if you change location.

> Even if this is not a bug, this update was insanely confusing, even for a techie like me.

well this is the one update where we happened to change the installer.

**Comment by Halbour** [comment]
I still want to know - why did it place _all_ of my songs in C:, abandoning A:? And how do I move the installation location?
Anyway that was confusing but not a bug, thanks for your time that I wasted...! 🥲

**Comment by bdach** [comment]
> I still want to know - why did it place _all_ of my songs in C:, abandoning A:?

i don't know what your setup is. did you install lazer the first time? did you previously have it installed? did you previously have lazer beatmaps on A:?

> And how do I move the installation location?

there's a change folder button in settings

> Anyway that was confusing but not a bug, thanks for your time that I wasted...! 🥲

please keep this open to track the remaining breakage (there is remaining breakage)

**Comment by Halbour** [comment]
Yes, I installed it to A: and I have BM's there, buuuuuut I guess lazer didn't like A: one day. Is this for another issue?

**Comment by bdach** [comment]
> Yes, I installed it to A:

how did you install lazer to A: if you didn't know how to move location? i'm very confused now.

are you sure you're not confusing it with stable or something?

**Comment by Halbour** [comment]
Well, I am confused like you. I am _sure_ I originally did... and that is a separate folder from stable. Here, look:
![image](https://github.com/user-attachments/assets/74300cc4-428f-45b5-873f-22093e34eee7)

**Comment by peppy** [comment]
This is more than likely just the shortcut being renamed.

This is now fixed, we pushed an updated installer / update content. If you'd like the fix to be applied immediately, please download and run `install.exe` once (https://github.com/ppy/osu/releases/download/2024.906.1/install.exe).
