### ISSUE TITLE
When there are many collections, the "add to collection from results screen" function will overflow

### ISSUE THREAD

**Issue by Ladwick** [ppy/osu#29736]
### Type

Game behaviour

### Bug description

When the user has a lot of collections, the dropdown menu will overflow without the chance to scroll to the part that is outside of the screen.

### Screenshots or videos

https://github.com/user-attachments/assets/f3852483-fb32-42b4-af54-92a2a2c68c32

### Version

2024.906.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16911757/compressed-logs.zip)

**Comment by cyperdark** [comment]
same here, cant scroll to bottom

https://github.com/user-attachments/assets/02c90bc5-f79e-4b6e-8a1a-246e7bab39fa
