### ISSUE TITLE
Keys conversion mods on osu! mania do not work

### ISSUE THREAD

**Issue by Sclafus** [ppy/osu#29734]
### Type

Game behaviour

### Bug description

I noticed that using the conversions mods for keys (1k, 2k, ...) on osu! mania seems to have no effect. 

### Screenshots or videos

https://github.com/user-attachments/assets/522d342e-a620-4c09-a1e9-338a84be10c7

### Version

2024.906.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16911519/compressed-logs.zip)

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/18562
