### ISSUE TITLE
On Windows, file associations aren't registered correctly when updating to Velopack in game

### ISSUE THREAD

**Issue by SupDos** [ppy/osu#29730]
### Type

Game behaviour

### Bug description

When updating from 2024.817.0 to the newest release in game, the file associations seem to still be linked to the previous `osu!.exe` location.

Originally thought this was only me but someone else on the Discord server had the [same issue](https://discord.com/channels/188630481301012481/1097318920991559880/1281588379741585492)

Files are registered correctly after running the latest `install.exe` manually and pressing repair on the popup.

### Screenshots or videos

https://github.com/user-attachments/assets/ef2f1c65-6de3-4fde-8605-50216a4b807d

### Version

2024.906.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16909744/compressed-logs.zip)
[Velopack.log](https://github.com/user-attachments/files/16909745/Velopack.log)

**Comment by smallketchup82** [comment]
Can you open `HKEY_CURRENT_USER`, navigate to `Software\Classes`, then look for `osu.File.osz`, then send the value of `Shell\Open\Command`?

This should allow me to confirm what it's set to.

**Comment by SupDos** [comment]
After updating the value in regedit is still `"C:\Users\SupDos\AppData\Local\osulazer\app-2024.817.0\osu!.exe" "%1"`

**Comment by smallketchup82** [comment]
Thanks! I'll try to tackle this (associations refactor) during the weekend.
