### ISSUE TITLE
combining EZ and SD does not match expected behavior

### ISSUE THREAD

**Issue by VelamyGH** [ppy/osu#29731]
### Type

Game behaviour

### Bug description

its obvious WHY this is happening, i just highly doubt it is intentional. combining easy and sudden death means you are allowed to miss 2 (by default/ranked play) times before failing since ez allows you to fail twice before the play ends. meaning if you are going for an ezsd score you can miss twice and still submit with sd, ive mentioned this once in the server and was told its not intentional fwir so i think making an issue here to see if it gets resolved would be a good idea

### Screenshots or videos

![image](https://github.com/user-attachments/assets/0ff64b9b-210c-45d6-8bdb-4a0a5056f3d4)

### Version

2024.906.1

### Logs

[Uploading compressed-logs.zip…]()

**Comment by VelamyGH** [comment]
also im not sure how this is going to affect already submitted plays, but its niche enough for now and i think resolving it sooner than later is a good idea

**Comment by bdach** [comment]
The "expected" behaviour is subjective. Last this was brought up (https://github.com/ppy/osu/discussions/13857) everyone was fine with the current status quo.

If you have reservations then probably bring them up in that discussion thread.
