### ISSUE TITLE
[Vulkan] Weird, artifact-like issues when switching resolution.

### ISSUE THREAD

**Issue by ziv-vy** [ppy/osu#29760]
### Type

Performance

### Bug description

When switching resolution, the game causes weird artifact-like bars to pop up. This is not a hardware issue and is only present in the Vulkan renderer.

### Screenshots or videos

Unfortunetly, this bug (somehow) does not appear on OBS, so I had to manually record it with a camera...
https://youtu.be/NjqY3smA7nA

### Version

2024.906.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16915211/compressed-logs.zip)

**Comment by ZenoG2** [comment]
Oh wait wrong place to post this...
