### ISSUE TITLE
Unpleasant distortion in the map selection menu in osu!stable

### ISSUE THREAD

**Issue by coccmocc** [ppy/osu#29763]
### Type

Cosmetic

### Bug description

It’s just a distortion that I highlighted in the screenshot, I never had this before. It looks like 2 bars on the screen

### Screenshots or videos

![photo_2024-09-07_16-38-22](https://github.com/user-attachments/assets/a9a73bdf-23fa-4557-a114-d7034c84265b)
![photo_2024-09-07_16-38-27](https://github.com/user-attachments/assets/6f3b1255-fac9-4d75-a7d2-98df10ff2fcd)

### Version

b20240820.1

**Comment by bdach** [comment]
https://github.com/ppy/osu-stable-issues/
