### ISSUE TITLE
Osu!Lazer Random Mod Bug

### ISSUE THREAD

**Issue by endqrfqxonosu** [ppy/osu#29765]
### Type

Game behaviour

### Bug description

So I enable the Random mod from the Conversion mod menu. And I was playing a map that had some reverse sliders that goes on 1/4 and 1/8 ticks and with the random + cl mod combination, the sr spikes so much, from 3,61 to 6,57 LOL WHAT? this is a 3 star map how did it get so buffed just from the reverse sliders LOL

### Screenshots or videos

![image](https://github.com/user-attachments/assets/2c2fbbc6-8b3f-419d-97e2-d079c09b6bfc)
![image](https://github.com/user-attachments/assets/0b18682f-3a7d-42bc-9e14-b218d33b4617)
![image](https://github.com/user-attachments/assets/3e37212d-97f1-4697-bcce-5702ed148e7f)

### Version

2024.906.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16918510/compressed-logs.zip)

**Comment by endqrfqxonosu** [comment]
also, the "bug" also works for every map with fast reverse sliders

**Comment by bdach** [comment]
#29729
