### ISSUE TITLE
Audio glitches in editor, during fast scrolling

### ISSUE THREAD

**Issue by tadatomix** [ppy/osu#29775]
### Type

Other

### Bug description

For some reason, when beatmap is played in lazer's editor and person decides to scroll, using wheel or bar at the bottom, song starts glitching, adding some strange noise. Stable lacks of it, as I noticed. 

### Screenshots or videos

https://github.com/user-attachments/assets/926f36f8-7256-4af3-9939-d70691fdcf5c

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16920352/compressed-logs.zip)

**Comment by bdach** [comment]
I don't think this is a valid report. Of course the song is going to sound garbled if you spaz out with the seek bar. Yes we could probably do something like debounce the seek but I'm not sure that is productive use of time.

**Comment by tadatomix** [comment]
> I don't think this is a valid report. Of course the song is going to sound garbled if you spaz out with the seek bar. Yes we could probably do something like debounce the seek but I'm not sure that is productive use of time.
Okay, I just thought that it might be a bug or so
