### ISSUE TITLE
Turning on Generate Shape Tool options causes the toolbox to twitch

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#29781]
### Type

Cosmetic

### Bug description

click the polygon in generate section, and then move mouse back to toolbox

### Screenshots or videos

https://github.com/user-attachments/assets/fb2894cf-aee5-4f2a-8942-889f30b7a259

### Version

2024.906.2

### Logs

NA

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/29511
