### ISSUE TITLE
Song select sort by difficulty regression

### ISSUE THREAD

**Issue by kafibu** [ppy/osu#29780]
### Type

Game behaviour

### Bug description

When sorting by any other type of sorting after sorting by difficulty it select a random mapset instead of the mapset of the selected diff. This regress during recent update

### Screenshots or videos

https://github.com/user-attachments/assets/219b4ea8-da30-4132-a530-c8216be9704b

**2024.817**

https://github.com/user-attachments/assets/32ab86a7-ee18-46c3-b1b3-62ff555d836d

**2024.906.2**

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16921605/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/29738
