### ISSUE TITLE
Replay analysis HD issue

### ISSUE THREAD

**Issue by YoYo745** [ppy/osu#29796]
### Type

Game behaviour

### Bug description

When using replay analysis on replay with Hidden mod you cannot see the hitcircle, thus making the analysis of cursor placement impossible. For this it would be nice to have option to disable Hidden mod. Adding a video with example.

### Screenshots or videos

https://github.com/user-attachments/assets/f8dfca5a-bdbc-470a-85e2-1418a9c2516b

### Version

2024.906.2

### Logs

N/A

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/29748

**Comment by Joehuu** [comment]
This is a duplicate of https://github.com/ppy/osu/issues/8357 then.
