### ISSUE TITLE
Windows uninstaller entry has wrong publisher/author

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#29806]
### Type

Other

### Bug description

A brief investigation is that the deploy process is not seeing this nuspec line or is not using the nuspec at all:
https://github.com/ppy/osu/blob/f0e2b803ded7a3f7a826c05a0138bcc923dde9a9/osu.Desktop/osu.nuspec#L7

### Screenshots or videos

![ApplicationFrameHost_hgvZThr7TG](https://github.com/user-attachments/assets/e2c69a96-429a-4d3f-8ae9-8a19d6d13d26)

### Version

Since 2024.906.1

### Logs

N/A

**Comment by smallketchup82** [comment]
cc @caesay

**Comment by caesay** [comment]
Did you set the --packAuthor argument when packing?

**Comment by peppy** [comment]
Added, thanks!
