### ISSUE TITLE
Cannot move object with ctrl+left/right arrow key due to function overlap with Seek to the previous/next hitobject

### ISSUE THREAD

**Issue by Alib234** [ppy/osu#29803]
### Type

Game behaviour

### Bug description

since 2024.906.1-lazer the feature of seeking to the previous/next hitobject was added however it seems that moving objects with ctrl+arrowkeys was forgotten? and now it is only possible to move objects up/down, this can be worked around by temporarily unbinding/rebinding the Seek to previous/next hitobject binds.
I think the fix is probably changing the default keybinds of the new feature to possibly alt+left/right arrow.

### Version

2024.906.1-lazer

### Logs

-

**Comment by peppy** [comment]
I have a very strong feeling ctrl-left/right was already in use but didn't test when already having a selection.

To me, ctrl+arrows for movement feels very wrong but alas, we have too many operations to cover.
