### ISSUE TITLE
Dropping slider tails doesn't provide visual feedback on `argon`, `argon pro` and `triangles`.

### ISSUE THREAD

**Issue by Delta-official** [ppy/osu#29804]
### Type

Cosmetic

### Bug description

Dropped slider ends are seemingly supposed to have a visual indicator (See: https://github.com/ppy/osu/discussions/25968, https://github.com/ppy/osu/pull/25972, https://osu.ppy.sh/community/forums/topics/1890272?n=1), but I've noticed a lack of them in the `argon`, `argon pro` and `triangles` skins (`classic` does have them for some reason though).

### Screenshots or videos

Argon Pro (same situation with Argon and Triangles):

https://github.com/user-attachments/assets/66bb61bd-2a41-45d6-aaef-948e8412c018

Classic:

https://github.com/user-attachments/assets/d24f9427-7953-4a96-ba1f-82c2e602bdd3

### Version

2024.906.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16924182/compressed-logs.zip)

**Comment by bdach** [comment]
The videos you took _show the indicator_.

![IMG_20240909_064205.jpg](https://github.com/user-attachments/assets/14913b5f-6eb2-4c88-9dc7-eb5adfff89ee)

The red dot is a tick miss. The gray dot is the dropped slider end.

**Comment by Delta-official** [comment]
Ah, I do apologize. I thought the gray dot was a generic slider indicator instead of a dropped indicator (here one could argue that the skins are ambigious and the indicator should be changed, but that's for a discussion thread). Thanks for your time!
