### ISSUE TITLE
The Touch Device mod is hidden from replays

### ISSUE THREAD

**Issue by ZenoG2** [ppy/osu#29817]
### Type

Cosmetic

### Bug description

Touch devices are not signaled correctly.

### Screenshots or videos

![Screenshot 2024-09-09 133103](https://github.com/user-attachments/assets/61d00c2e-8cb0-4030-b9e0-a7b0c055264c)
![Screenshot 2024-09-09 133114](https://github.com/user-attachments/assets/6b3eb568-966e-4084-a9b0-179fdb6cb662)
![Screenshot 2024-09-09 133120](https://github.com/user-attachments/assets/68ca7aeb-61b5-40cb-ab13-118cc078627e)
![Screenshot 2024-09-09 133126](https://github.com/user-attachments/assets/10153e83-382c-4b1a-9eb6-27302fa7160c)

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16929185/compressed-logs.zip)

**Comment by bdach** [comment]
So I _presume_ this is happening if the user starts the play using mouse but then starts touching midway through the game. This is not conveyed to `osu-server-spectator`, which is responsible for recording replays, and thus is blissfully unaware of this; submission happens at the _end_ of the score, with TD successfully present, but web will serve the replay recorded by `osu-server-spectator` raw which means that the information about TD is dropped from the replay.

The two obvious fixes are to either:

- have `osu-server-spectator` know that mods changed (probably by sending them in the frame bundles - possibly wasteful if not done with a bit of deduplication to only send changes),
- have `osu-web` correct the replay in post when serving it, similarly to how I believe it currently manufactures the replay headers for stable replays?

@ppy/team-client opinions?

**Comment by peppy** [comment]
> probably by sending them in the frame bundles - possibly wasteful if not done with a bit of deduplication to only send changes

Frame bundles are already seldom enough that sending in them should be okay. As long as it's not some insanely huge json blob.
