### ISSUE TITLE
Ui

### ISSUE THREAD

**Issue by NeofetchNpc** [ppy/osu#29820]
### Type

Ui

### Bug description

this ui is not in place, i am using osu!lazer on android.

### Screenshots or videos

![Screenshot_20240909_213935](https://github.com/user-attachments/assets/634f5b12-d9ad-411e-87ec-a721f869c1f1)
![Screenshot_20240909_214641](https://github.com/user-attachments/assets/ea7fd78a-e825-4ecc-8963-0a33f2debcd3)

### Version

latest

### Logs

-

**Comment by bdach** [comment]
Most of these are already known and tracked elsewhere.
