### ISSUE TITLE
osu!std hitsounds playing in osu!taiko editor when setting don object volume anywhere from 60 to 85

### ISSUE THREAD

**Issue by ChromaCat248** [ppy/osu#29832]
### Type

Game behaviour

### Bug description

i couldn't test it with a different skin because i stopped being able to replicate the issue at all for some reason

### Screenshots or videos

https://github.com/user-attachments/assets/7e69710c-50cb-4653-96ea-d100ff75f4b8

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16945743/compressed-logs.zip)

**Comment by TryhardPickles** [comment]
hm. weird
