### ISSUE TITLE
Replay Analysis cursor not lined up to Barrel Roll replays

### ISSUE THREAD

**Issue by raybeanosu** [ppy/osu#29839]
### Type

Game behaviour

### Bug description

Looked at a replay of one of my Daily Challenges runs that had Barrel Roll on.
The replay analysis cursor works according to the placement of the hitobjects on the map itself rather than where it is during gameplay (that being spinning).

### Screenshots or videos

![osu_2024-09-11_17-45-14](https://github.com/user-attachments/assets/b0880828-2486-47bb-9c80-bca452408ba9)
![osu_2024-09-11_17-48-23](https://github.com/user-attachments/assets/43b2d5e7-c3c4-438f-bbed-93006f60688e)

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16963676/compressed-logs.zip)

**Comment by bdach** [comment]
Mostly for convenience, can you provide the replay?

**Comment by hyyhsuzy** [comment]
sure, here you go! had to send as a ZIP, hope that's alright
[Raybean playing Station Earth - Cold Green Eyes feat. Roos Denayer (Sotarks) [Kowari_s Hard] (2024-08-08_17-26).zip](https://github.com/user-attachments/files/16963932/Raybean.playing.Station.Earth.-.Cold.Green.Eyes.feat.Roos.Denayer.Sotarks.Kowari_s.Hard.2024-08-08_17-26.zip)
