### ISSUE TITLE
Can't select combo in skin layout editor

### ISSUE THREAD

**Issue by shinobu-uwu** [ppy/osu#29835]
### Type

Game behaviour

### Bug description

Using [this skin](https://drive.google.com/file/d/1DQcb26m93jxrFDoiX7fgfeMvl1zvgr0Q/view?usp=drive_link) I can't select the combo counter widget in order to remove it, you can see it in the video below

### Screenshots or videos

https://github.com/user-attachments/assets/dd500253-a764-46dc-8a07-a6bbf5b060f9

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16948814/compressed-logs.zip)

**Comment by Alib234** [comment]
I believe combo counters have been moved from the HUD layer to the gamemode specific HUD layer, you can change the layer on the left above the components

**Comment by shinobu-uwu** [comment]
Ooops, I didn't see that
