### ISSUE TITLE
Entering a playlist room causes music player unable to play any songs but current one

### ISSUE THREAD

**Issue by MerukYang** [ppy/osu#29847]
### Type

Game behaviour

### Bug description

Entering a playlist room causes music player unable to play any songs but current one.
To reproduce this bug: 

1. entering playlist lounge, check if music player work well.
2. then entering a specific room, check if music player work well.

video attached.

https://github.com/user-attachments/assets/d5708f8f-27b7-45eb-9b9d-b9d15256a8e3

Also, when current song finished, the player would replay this song from the preview point rather than form very beginning.

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16973581/compressed-logs.zip)

**Comment by peppy** [comment]
This is intended. The game locks the current playing track as you're in a playlist room.
