### ISSUE TITLE
Daily Challenge breaking after foul player's score was removed

### ISSUE THREAD

**Issue by rodrigopina360** [ppy/osu#29857]
### Type

Game behaviour

### Bug description

During today's Daily Challenge a user achieved number 1 on the leaderboard through foul play, and was promptly banned and his score removed. After the incident, when the leaderboard tried to reload it just loaded forever, with no end. Given score submissing was still working and website leaderboard was also working fine I had the random assumption to be cache related, which after clearing proved to be the issue. It's not a serious issue to fix, given clearing cache or likely restarting should fix the issue, but I'm reporting the issue so devs can take a look at it and hopefully fix it.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/32b21025-4e1f-4db7-b13e-cd37e11e3b0d)

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16985283/compressed-logs.zip)

**Comment by frenzibyte** [comment]
This has long been fixed, thanks for the report.
