### ISSUE TITLE
Weird(different) transition on beatmap details

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#2985]
Tested this on high and low-end. Low-end looks more noticeable.

High-end:
On 2018.702.0:
![2018-07-09_09-48-34](https://user-images.githubusercontent.com/35318437/42464335-95f8a52e-835d-11e8-93cf-6d89accbe9c6.gif)

After:
![2018-07-09_09-50-33](https://user-images.githubusercontent.com/35318437/42464338-97ff46ca-835d-11e8-9af1-6094a03fa10f.gif)

**Comment by peppy** [comment]
Could you explain what "high end" and "low end" mean?

**Comment by Joehuu** [comment]
Oh just the performance of a fast and a slow computer.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu-framework/pull/2932.
