### ISSUE TITLE
Maps with storyboard over notes will display note when background dim is 100%

### ISSUE THREAD

**Issue by minhperry** [ppy/osu#29867]
### Type

Game behaviour

### Bug description

This only applies for maps that are dependant on storyboard like [this map](https://osu.ppy.sh/beatmapsets/1485845#osu/3046792)

From what I can understand, stable will always draw the storyboard layer over the notes layer for such maps, even with 100% background dim. However, on lazer, with 100% background dim, notes will always be drawn instead, completely ignoring the storyboard layer being over it. This will ruin the whole gimmick of the map where the player is supposed to only play using the storyboard.

### Screenshots or videos

https://github.com/user-attachments/assets/470f8bdd-e308-4777-8213-abc3f0b88b7a

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16999541/compressed-logs.zip)

**Comment by TryhardPickles** [comment]
I don't know if this is intended behavior, but I will make a fix for this.

**Comment by bdach** [comment]
Relevant: https://github.com/ppy/osu/issues/9315

At this point we probably need to reconsider making the storyboard not-present when fully dimmed. Or add conditions that prevent both issues.

**Comment by minhperry** [comment]
This bug is kinda back with some maps like Nino's Acid Rain rendering incorrectly?? But linked MIFN is still fine
