### ISSUE TITLE
'Open with' context menu shows both osu!stable and osu!lazer as 'osu!'

### ISSUE THREAD

**Issue by ItsDiamondblade** [ppy/osu#29865]
### Type

Cosmetic

### Bug description

When opening a file for osu (i.e. a skin), both osu!stable and osu!lazer show up as 'osu!' in the 'open with' context menu.

### Screenshots or videos

![Screenshot_359](https://github.com/user-attachments/assets/cd0147ad-fdfb-4439-92b4-fc8b3dcd7d13)

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16998420/compressed-logs.zip)

**Comment by smallketchup82** [comment]
Fixed in #29822
