### ISSUE TITLE
tourney client screen auto advances for every ban

### ISSUE THREAD

**Issue by MikkelCornelius** [ppy/osu#29876]
### Type

Game behaviour

### Bug description

Idk what update this started in, but when autoadvance is enabled, the scenes switch from mappool to gameplay for every single ban pick. It is only supposed to advance when a map is picked. 

### Version

2024.906.2

### Logs

uhm I don't think tourney client has an export logs button

**Comment by peppy** [comment]
Checking the code, it looks to be written correctly. The screen will only change when the latest operation was a "pick". Could you share a screen capture showing what you're seeing?

**Comment by MikkelCornelius** [comment]
It'll be 6 hours before I'm home, but I can test it again there. In the mean time here is the STT4 stream where it messed up: https://www.twitch.tv/videos/2250865990 Bans are 4 minutes 12 seconds in. 

I discussed the issue with the other streamer of the tourney affirmedcheese. And they said they experienced the same issues. 

In the second match later in the stream I fixed the issue by spam clicking the mappool scene after each ban, but that's an annoying solution.

**Comment by MikkelCornelius** [comment]
Okay the issue is gone. I was streaming two different tournaments on September 14th, and I experienced this issue on both occasions. So even with a reboot the issue stayed. Have you made any updates since then?

**Comment by bdach** [comment]
That particular code has not been changed for at least a year now. So either you were using an ancient version of the tournament client or there is some other hidden circumstance that makes this issue present itself.

**Comment by MikkelCornelius** [comment]
I talked to affirmedcheese again, and it seems the issue is entirely gone now. I can't explain what happened on september 14th but i guess this issue is closed for now.
