### ISSUE TITLE
Imported local scores missing profile picture & country flag, and not appearing on difficulty selection

### ISSUE THREAD

**Issue by Ningoji** [ppy/osu#29881]
### Type

Game behaviour

### Bug description

After importing all scores from osu!stable, some scores are missing flag/picture and appear on the left side scores, but not next to the difficulty.
Also, some scores dated older do not have this issue but then on the same beatmap newer scores still have this issue

### Screenshots or videos

![image](https://github.com/user-attachments/assets/9bd9ce9d-ec09-4907-a957-d5e3c8bfdd98)
![image](https://github.com/user-attachments/assets/e7ded000-657f-42ac-83cb-2d89fad9dbf4)

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17004443/compressed-logs.zip)

**Comment by bdach** [comment]
Can you attach one of the scores that are missing the flag and avatar? 

The likely explanation is that those scores were set offline or did not upload online for some other reason, and because of that they do not get associated with your profile. This was an intentional change because the replay only contains your username which means it was possible to easily falsify replays by logging out and putting someone else's username in the login box on stable.

That said, that's a hypothesis I still would want to confirm.

**Comment by Ningoji** [comment]
[Ningoji playing Frederic - oddloop (n0ah) [oldloop] (2022-09-12_23-00).zip](https://github.com/user-attachments/files/17004624/Ningoji.playing.Frederic.-.oddloop.n0ah.oldloop.2022-09-12_23-00.zip)
Here's an example from Oddloop

**Comment by bdach** [comment]
I can confirm that the score attached above does not have an online score ID, which means it likely wasn't submitted online, which means it cannot be safely associated with your profile. Unfortunately I'm not sure we can do anything about that.

See https://github.com/ppy/osu/pull/28082, https://github.com/ppy/osu/issues/24624 as rationale.

**Comment by Ningoji** [comment]
Damn, I don't remember ever intentionally playing offline or what not, oh well though, thanks for help!

**Comment by Akosih97** [comment]
I have the same problem after importing scores from osu!stable on linux mint. What puzzles me about the online score ID explanation is that all of my local scores with missing profile picture actually show up in the global ranking and are therefore clearly in the online database and shoud be uploaded. I have this score error for about 50% of my scores and all of them show up in the online database. Maybe I am not getting the full picture here. Is it the same for you?

**Comment by bdach** [comment]
@Akosih97 please attach an example of such a score for inspection

**Comment by bdach** [comment]
Well I can say for sure that the replay provided does not have an online ID inside (last 8 bytes are all zeroes). Additionally, the [online display](https://osu.ppy.sh/scores/3349585014) for this score has no associated replay...

Not sure what that means or what can be done here. @peppy any ideas? you probably know stable better than I do.

**Comment by Ningoji** [comment]
Looking further into some of my scores, I actually have the same issue as Akosih97

**Comment by Phippe** [comment]
Sorry for the necropost, but I just wanted to ask what the possible reasons are for the online ID being missing from scores (if you know of any).

I've just switched to lazer as my main client and realised that quite a few scores lack profile pictures. As bdach mentioned, all of these scores have the last eight bytes indeed set to zero. I can also confirm that these zero bytes exist when exporting directly from stable, so there are no issues with importing.

However, I can't identify a pattern as to when these bytes are set to zero. One of the replays is my current high score on the map, so it should definitely have an online ID, shouldn't it? There are also worse replays on the same beatmap, and these have pictures. It all seems so random.

I guess there is not a lot you guys can do regarding missing data, but it would still feel better to have a reason as to why the bytes are missing :D

**Comment by bdach** [comment]
My barely educated untested guess based on cursory source inspection would be that it has to do something with exiting results screen before the score actually completes submission.
