### ISSUE TITLE
Osu audio bug in newer versions

### ISSUE THREAD

**Issue by nvmend** [ppy/osu#29892]
### Type

Audio bug

### Bug description

Game audio sounds like its breaking/glitching when it is slowed down, when making a map or editing one, slowing down to 25% 50% 75% makes audio strange behaviour. I thought it was a driver issue on my computer but I decided to download an older version to test first since it wasn't like this months ago. 

I installed a build from April, and it works fine (I test both versions on the video so its possible to see the difference in audio between versions) I thought maybe this is a bug with newer versions since works fine on older ones.

### Screenshots or videos

https://www.youtube.com/watch?v=V559EsL5_Ow

### Version

2024.906.2 and newer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17022937/compressed-logs.zip)

**Comment by peppy** [comment]
I think this is intended (better precision at the cost of making audio sound a bit less natural). We changed it recently to match stable. You can check stable to confirm it sounds the same for you there too.

**Comment by nvmend** [comment]
Oh I understand now, thanks for the info peppy, hope you having a great day
Yes it sounds the same on stable, I'll close this issue.
