### ISSUE TITLE
Editor clock unstable when resuming playback / seeking while playing

### ISSUE THREAD

**Issue by minetoblend** [ppy/osu#29909]
### Type

Game behaviour

### Bug description

Currently ([on latest master](https://github.com/ppy/osu/tree/ea94f903c1ef72ef79dff19d923fdbd4bfcf2357)), when starting playback and when seeking during playback the clock time seems to skip forwards/backwards for a split second directly after resuming/seeking before playback continues like normal.
As far as I can tell, it only happens for resuming when pressing play for the first time, and when resuming after seeking while paused. When pausing and then resuming directly without seeking it will resume normally.

I narrowed down the commit where this starts happening and it appears to be the latest framework update (#29848).

### after #29848:

https://github.com/user-attachments/assets/5a9d3397-cbbb-4fa6-bef8-92df1d062292

### before #29848:

https://github.com/user-attachments/assets/51d35ef0-771c-4b64-9ac8-dad2a5fe324a

### Version

Master (18ab4ee929dd6ccf2ffadaab7fb9ca71be6c5c64)

### Logs

There was well over 100 files in my logs folder and it stopped uploading them halfway through and now I'm rate limited and can't upload any more files, so I had to upload them to gdrive instead
https://drive.google.com/file/d/1QHMLOYBxeB84KBaQaev-8ZMMgZomCiIN/view?usp=sharing

**Comment by Joehuu** [comment]
You are on an outdated commit (as linked in the version). The change that caused this was reverted in https://github.com/ppy/osu/commit/d34e8ea69e78f80940b2cade87b9c0dba6f066b0.
