### ISSUE TITLE
The "PlayerAvatar"'s Corner Radus has the weird shape

### ISSUE THREAD

**Issue by ShirohanaHikari** [ppy/osu#29919]
### Type

Other

### Bug description

The corner shape is so weird when you change the radus

### Screenshots or videos

https://github.com/user-attachments/assets/1f2ceb89-5b85-46e5-a010-9295eb6159ec

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17045036/compressed-logs.zip)

**Comment by peppy** [comment]
This is because you've applied uneven scaling to the avatar. Please try right-clicking and choosing "reset scale".

We can probably fix this to not occur, but this should repair your skin for now.
