### ISSUE TITLE
Slider timing is not snapped after changing curve type

### ISSUE THREAD

**Issue by peppy** [ppy/osu#29915]
We should definitely be forcing a re-snap here.

---

### Discussed in https://github.com/ppy/osu/discussions/29903

<div type='discussions-op-text'>

<sup>Originally posted by **cihe13375** September 17, 2024</sup>
1. create a linear slider
2. change the first anchor to perfect curve
3. now the sliderend is unsnapped

it also happens in the reverse way, i.e. create a perfect curve first and then change to linear.

I once thought this is a feature but decide to report it after seeing someone with 99999 sliderends unsnapped in the verify tab and *I guess* this is the most likely reason

https://github.com/user-attachments/assets/8c49a821-e35e-4b96-ac22-146754c4aefe

</div>

**Comment by OliBomby** [comment]
The behaviour that it changes the slider length to the max when you change a curve type I considered a feature, but now that you have the ability to change the slider length by just dragging the end this is obsolete.

I think a fix would be to not change the slider length at all if the slider path is still long enough to accomodate the length, and resnap the slider end if the slider path became shorter than the slider length.

**Comment by peppy** [comment]
Sure.

**Comment by peppy** [comment]
Sure.
