### ISSUE TITLE
Song doesn't play if you don't seek first in editor

### ISSUE THREAD

**Issue by bytenekos** [ppy/osu#29946]
### Type

Game behaviour

### Bug description

If you create a new beatmap with a song and press play without seeking anywhere, audio doesn't play. Only way to fix this (based on what I've tested) is to just seek anywhere in the song and audio plays (see video attached for a better explanation)

### Screenshots or videos

https://github.com/user-attachments/assets/3e050ad5-dfed-429a-9511-e2581295bffe

Media info of song shown in the video:
[03 - Virtual Riot - Hysteria.mp3.MediaInfo.txt](https://github.com/user-attachments/files/17082455/03.-.Virtual.Riot.-.Hysteria.mp3.MediaInfo.txt)

Also media info of another song I tried and exact same issue
[04 - Chef's Suggestion.ogg.MediaInfo.txt](https://github.com/user-attachments/files/17082471/04.-.Chef.s.Suggestion.ogg.MediaInfo.txt)

Not sure if the media infos are needed but they're there for reference I guess

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17082440/compressed-logs.zip)

**Comment by Joehuu** [comment]
FWIW, this seems to only be reproducible on Windows and the timestamp starts at `00:00:015` for some reason. At least on macOS, I can't reproduce and the timestamp is `00:00:000`.

**Comment by bytenekos** [comment]
> the timestamp starts at 00:00:015 (when entering editor) for some reason

Idk if it's related but the waveform starts before "00:00", just noticed this

![image](https://github.com/user-attachments/assets/af740e59-4764-42b9-a7d6-8e53da55bf23)

![image](https://github.com/user-attachments/assets/ec4ff575-34f8-4e49-aa86-5c4bbff48837)
