### ISSUE TITLE
auto sometimes can't hold full speed for spinners in osu!standard

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2994]
video (look at 0:36):
https://drive.google.com/open?id=1OVl0I9s15uJSzFMLsDNjAIffxMcFkwat

sometimes auto on spinners has speed change 477 ->476 -> 477 , while spinner isn't ending

logs:
[database.log](https://github.com/ppy/osu/files/2181666/database.log)
[network.log](https://github.com/ppy/osu/files/2181667/network.log)
[performance.log](https://github.com/ppy/osu/files/2181668/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2181669/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2181670/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2181671/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2181672/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2181673/runtime.log)

**Comment by peppy** [comment]
No longer relevant.
