### ISSUE TITLE
4k(osu!mania) mod doesnt work

### ISSUE THREAD

**Issue by ArtemChik103** [ppy/osu#29952]
### Type

Game behaviour

### Bug description

i apply 4k mod to a 7k map and it stays 7k, nothing changes

### Screenshots or videos

![osu_2024-09-22_00-03-50](https://github.com/user-attachments/assets/d6512e10-c45b-4c05-82a3-a95dd532a1e7)

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17084498/compressed-logs.zip)

**Comment by bdach** [comment]
#18562
