### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by miaucz** [ppy/osu#29954]
### Type

Other

### Bug description

typo is visible on the screenshot but im not sure if its typo

### Screenshots or videos

![erfagesgwseg](https://github.com/user-attachments/assets/6f8e9bda-1cdd-414b-9252-5c1728c8cbc3)

### Version

b20240820.1

### Logs

.

**Comment by bdach** [comment]
The screenshot is so cropped that I cannot tell what this is attempting to show. A slightly less cropped version would be helpful. Then again, these sort of tooltips only exist on the website, so assuming I'm correct, this is best reported at https://github.com/ppy/osu-web/.

**Comment by miaucz** [comment]
![obraz](https://github.com/user-attachments/assets/23974141-5fdb-4a32-8348-c8d763ab08e3)

**Comment by smoogipoo** [comment]
Dunno. Looks fine here:

<img width="204" alt="image" src="https://github.com/user-attachments/assets/7c901632-3c09-4382-ab07-911f828506d2">

May be based on your system language? I see references to "Algieria" in other languages (https://grep.app/search?q=Algieria), but no matches on that string in either either osu! or osu!web resources.

Regardless, this is not an osu!/osu!web issue, and certainly not one _we_ can fix.

**Comment by miaucz** [comment]
Maybe but when i switch to my country language it seems normal like in english: Algeria and when i switch to english its says Algieria

**Comment by bdach** [comment]
It'll probably be something like web using the localised country name in the flag tooltip, but using the English country name itself because it comes from the database and it's not localised there.

summon @ppy/team-web

**Comment by notbakaneko** [comment]
We only have one version of the country name stored for flag tooltips regardless of language and it's `Algeria`

**Comment by bdach** [comment]
Yeah in checking I can't make this happen either. No idea what's going on there. Maybe some sort of browser stupidity (like it doing a partial auto-translation or whatever).

**Comment by cl8n** [comment]
looks like the fallback behavior of https://github.com/Cavitedev/osu-subdivide-nations for players that have no region data. if you use that extension, report the issue there instead
