### ISSUE TITLE
Move the osu!taiko leaderboard during gameplay below the gameplay field

### ISSUE THREAD

**Issue by AFasterSlowpoke** [ppy/osu#29965]
### Type

Cosmetic

### Bug description

The gameplay leaderboard in taiko overlays the gameplay field, which is distracting. I'd recommend you move the leaderboard in osu!taiko to below the gameplay field like it is in stable so it doesn't obstruct gameplay.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/72bd02a8-4f39-48b5-8044-14ed4d881dd4)

### Version

2024.906.2

### Logs

uh this isnt a bug but more of a design oversight.

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/20422
