### ISSUE TITLE
osu! while closing wanted to read not existing memory

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2999]
sorry, but i haven\'t saved window with exception: it was containing adresss of non existing/non available memory and 'couldn\'t done read'.

i haven\'t done anything special before it

only used stable and lazer at the same time, but closed stable few minutes before lazer, but i think that it didn't change anything

logs:
[database.log](https://github.com/ppy/osu/files/2182208/database.log)
[network.log](https://github.com/ppy/osu/files/2182209/network.log)
[performance.log](https://github.com/ppy/osu/files/2182210/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2182211/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2182212/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2182213/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2182214/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2182215/runtime.log)

**Comment by peppy** [comment]
Unfortunately nothing in the provided log files is useful. Could you check event viewer on your system to try and find the actual error report?

**Comment by ticotaco72** [comment]
Nazwa dziennika:Application
Źródło:        .NET Runtime
Data:          10.07.2018 23:24:52
Identyfikator zdarzenia:1026
Kategoria zadania:Brak
Poziom:        Błędy
Słowa kluczowe:Klasyczny
Użytkownik:    Nie dotyczy
Komputer:      GminaDobrcz
Opis:
Aplikacja: osu!.exe
Wersja architektury: v4.0.30319
Opis: proces został przerwany z powodu nieobsłużonego wyjątku.
Informacje o wyjątku: System.AccessViolationException
   w OpenTK.Platform.Windows.Wgl.DeleteContext(IntPtr)
   w OpenTK.Platform.Windows.WinGLContext.DestroyContext()
   w OpenTK.Platform.Windows.WinGLContext.Dispose(Boolean)
   w OpenTK.Graphics.GraphicsContextBase.Dispose()
   w OpenTK.Graphics.GraphicsContext.Dispose(Boolean)
   w OpenTK.Graphics.GraphicsContext.Dispose()
   w OpenTK.GameWindow.Dispose()
   w osu.Framework.Platform.GameHost.Dispose(Boolean)
   w osu.Framework.Platform.DesktopGameHost.Dispose(Boolean)
   w osu.Framework.Platform.GameHost.Dispose()
   w osu.Desktop.Program.Main(System.String[])


Kod XML zdarzenia:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-07-10T21:24:52.204848400Z" />
    <EventRecordID>14189</EventRecordID>
    <Channel>Application</Channel>
    <Computer>GminaDobrcz</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Aplikacja: osu!.exe
Wersja architektury: v4.0.30319
Opis: proces został przerwany z powodu nieobsłużonego wyjątku.
Informacje o wyjątku: System.AccessViolationException
   w OpenTK.Platform.Windows.Wgl.DeleteContext(IntPtr)
   w OpenTK.Platform.Windows.WinGLContext.DestroyContext()
   w OpenTK.Platform.Windows.WinGLContext.Dispose(Boolean)
   w OpenTK.Graphics.GraphicsContextBase.Dispose()
   w OpenTK.Graphics.GraphicsContext.Dispose(Boolean)
   w OpenTK.Graphics.GraphicsContext.Dispose()
   w OpenTK.GameWindow.Dispose()
   w osu.Framework.Platform.GameHost.Dispose(Boolean)
   w osu.Framework.Platform.DesktopGameHost.Dispose(Boolean)
   w osu.Framework.Platform.GameHost.Dispose()
   w osu.Desktop.Program.Main(System.String[])

</Data>
  </EventData>
</Event>

**Comment by ticotaco72** [comment]
@peppy do you mean this?

**Comment by peppy** [comment]
Thank you, this is very helpful.

**Comment by ticotaco72** [comment]
do you want something else?

**Comment by peppy** [comment]
@ticotaco72 can you still reproduce this?

**Comment by ticotaco72** [comment]
Sorry, but I migrated to Linux some time ago. I have changed hardware too. Anyway I haven't seen this bug for a long time on Windows before migration.

**Comment by bdach** [comment]
I suppose let's close this for now then. Please reopen if you run into this sort of thing again.
