### ISSUE TITLE
Spinning Cursor

### ISSUE THREAD

**Issue by MrDakio** [ppy/osu#30006]
### Type

Cosmetic

### Bug description

In the menu(any menu), if you hold down left click and rotate your cursor around that point several times, when you release left click, it will all rewind out at once.

### Version

2024.906.2

### Logs

none?

**Comment by nb-programmer** [comment]
Demo video of it happening in case anyone wants to see. Kind of funny how it just unwinds.
Since this is intended behavior, this video is posted just for demonstration of the issue.

https://github.com/user-attachments/assets/11ad2e64-2f64-4ef0-ae0f-5ce8ff6d244e
