### ISSUE TITLE
standard ingame seems to be really laggy or stuttering compared to last month

### ISSUE THREAD

**Issue by KimoriWasTaken** [ppy/osu#3000]
I haven't played on lazer for about a month now and was excited to check out the new implementations etc. but for some reason when I try to play a map the appearing circles and especially the slider seem to stutter a LOT compared to live or lazer 1-2 month ago. Cursor movement looks fine to me and the menu too, but ingame looks more like the game is running on less than 60 fps and I use a 144hz monitor, so I should be able to see a clear difference or when it's actual 144fps gameplay.
I'd love to share more details or even proof, but Steam FPS counter says it's running on 500+ fps and of course I am using unlimited fps and fullscreen.
I also completely reinstalled lazer, deleted the lazer folder in roaming manually before, or using a different skin, but nothing seems to make a difference.

Is this just for me, or am I imagining things? If so then please forget what I wrote.

**Comment by peppy** [comment]
Are you watching replays? If so, this is known.

**Comment by KimoriWasTaken** [comment]
I played the maps myself, tried autoplay and several different maps, but it looks the same.

**Comment by peppy** [comment]
This is a known issues for auto play and replays. Peease *triple check* you are seeing this when playing yourself.

**Comment by KimoriWasTaken** [comment]
Either updating Windows 10, restarting my pc several times, setting priority of Lazer in Task Manager>Details>above normal, or all of them fixed the issue for me.

Sorry for the unneccesary worries, I'm gonna go ahead an close the issue here.
