### ISSUE TITLE
Converted beatmaps, when displayed in a playlist show their standard-mode star rating instead of their converted one.

### ISSUE THREAD

**Issue by snalgae** [ppy/osu#30009]
### Type

Game behaviour

### Bug description

I got into converted beatmaps lately and I decided I wanted to create a playlist of some of them. Upon making one I noticed that they're showing wrong star ratings and having not found my issue listed, I decided to make this bug report. I'm sure that the difficulties are showing the original star ratings of standard-mode beatmaps instead of their converted ones.

I believe this issue is not catch-related and it affects mania and taiko too.

### Screenshots or videos

![osu_2024-09-26_23-20-17](https://github.com/user-attachments/assets/f479f114-7d9c-446a-a1e9-458e39d24051)
![osu_2024-09-26_23-20-53](https://github.com/user-attachments/assets/81311f9f-4835-4cf8-add8-af7acff44847)

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17152440/compressed-logs.zip)

**Comment by bdach** [comment]
Same issue as #29313
