### ISSUE TITLE
combo counter is inconsistent when using non-default skin

### ISSUE THREAD

**Issue by yoyyoy** [ppy/osu#30013]
### Type

Cosmetic

### Bug description

when using a skin that is not the default, the combo counter is different from the true combo, which can be seen on the leaderboard ingame. I can't replicate when using the default skin. in the video i pause at the beginning to keep it short but it's easiest to see at the first break. it's 87 combo but counter shows 89. this doesn't affect the score that gets saved
beatmap: https://osu.ppy.sh/beatmapsets/1581056#osu/3340977
skin: [Chino Kafuu [main Skin] (ArchieA7).zip](https://github.com/user-attachments/files/17155956/Chino.Kafuu.main.Skin.ArchieA7.zip)

### Screenshots or videos

https://github.com/user-attachments/assets/1924c5bc-db21-471a-b4e1-cdc74b5efd51

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17155787/compressed-logs.zip)

**Comment by Joehuu** [comment]
Already fixed in https://github.com/ppy/osu/pull/29838.
