### ISSUE TITLE
I've lost the in-game leaderboard and can never give it back on Windows version

### ISSUE THREAD

**Issue by CattyCathy** [ppy/osu#30010]
### Type

Game behaviour

### Bug description

As the title said. Using tab or shift + tab is not usable, I even set the skin to default style. While the android version can toggle the leaderboard normally,

### Screenshots or videos

![osu_2024-09-27_00-20-32](https://github.com/user-attachments/assets/3c82b2b2-b975-4bc3-9de3-7e4e623f7c6d)

### Version

lazer 2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17152417/compressed-logs.zip)

**Comment by peppy** [comment]
Have you set song select to show local scores? You need to change it to global if so.

**Comment by CattyCathy** [comment]
> Have you set song select to show local scores? You need to change it to global if so.

Thanks, it works!
