### ISSUE TITLE
Distance Snapping follows last object beat divisor, hard to work with

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#30023]
### Type

Game behaviour

### Bug description

Hi. When I change the beat divisor to common, it doesn't affect distance snapping. Still applies triplets, because the last object (slider end) is using triplets. I know it might be intended, but it's a little annoying.

https://github.com/user-attachments/assets/6f080886-b624-4cfe-b8fd-e5572ab26045

### Version

2024.906.2

### Logs

no need

**Comment by bdach** [comment]
I'm not sure what you're expecting to happen here? The previous slider is essentailly unsnapped with that beat divisor.

I think this is a wontfix personally.

**Comment by cihe13375** [comment]
I'm not the op poster, but I think at least the timing grids in the playfield and the timeline should be consistent - currently e.g. at 00:09 the note is "snapped to the grid" in the playfield but does not in the timeline. I don't even know how should I interpret this.

Also it breaks in a somewhat different way when the previous object is a circle (grids are shifted by 1/4):
![33333](https://github.com/user-attachments/assets/f71608d3-d15d-4029-b624-963c9e34425d)

It's not rare that songs have mixed swing and straight beats, and low diffs requires (or benefits from) DS, so I think such scenarios should be supported.

**Comment by bdach** [comment]
> I'm not the op poster, but I think at least the timing grids in the playfield and the timeline should be consistent - currently e.g. at 00:09 the note is "snapped to the grid" in the playfield but is not in the timeline

Sure this is fair, I guess the first ring's radius should be proportionally smaller. If there's anything to fix here it'd be that.
