### ISSUE TITLE
iPad Crash

### ISSUE THREAD

**Issue by RatonLaveurexe** [ppy/osu#30028]
### Type

Crash to desktop

### Bug description

Osu chrashes on IPad 10th gen,I need help please

### Screenshots or videos

https://github.com/user-attachments/assets/4e29c82b-9a49-41c0-9d20-4a3e1dd7e0be

### Version

2024.906.2

### Logs

I have no logs :(

**Comment by RatonLaveurexe** [comment]
> The build is not ready.

Then why did it appear on the releases?

**Comment by smoogipoo** [comment]
Because we're trying to get it ready.

**Comment by RatonLaveurexe** [comment]
> Because we're trying to get it ready.

What should I do now?

**Comment by RatonLaveurexe** [comment]
> Because we're trying to get it ready.

?

**Comment by RatonLaveurexe** [comment]
> Because we're trying to get it ready.

Should I downgrade??

**Comment by smoogipoo** [comment]
Yes, that's your only option. The last working build is https://github.com/ppy/osu/releases/tag/2024.625.2
