### ISSUE TITLE
For deletion

### ISSUE THREAD

**Issue by Y2nn1c** [ppy/osu#30049]
Trash

**Comment by bdach** [comment]
I dunno this seems kinda nitpicky, even on the screenshot it's clear what you have to click and it *is* orange on the inside. Yes it's not exactly tint (it's multiplicative application of orange) but still works kinda?

**Comment by Y2nn1c** [comment]
> I dunno this seems kinda nitpicky, even on the screenshot it's clear what you have to click and it _is_ orange on the inside. Yes it's not exactly tint (it's multiplicative application of orange) but still works kinda?

Sure, it "kinda" works, but it would still be nice to be fixed. So either we have a cursor-point to click thats always orange or you change it to "click the cursor to resume".

**Comment by tadatomix** [comment]
Actually, it's orange. The problem is, that your cursor is mint colored. So when mint multipled with color, whatever they call "orange" it turns into this color. Maybe they need to make cursor grayscaled, so it'll be exactly orange
