### ISSUE TITLE
Random Mod -Broken PP amounts

### ISSUE THREAD

**Issue by the-wildguy** [ppy/osu#30048]
### Type

Crash to desktop

### Bug description

Play a map such as [sewing machine [hard]](https://osu.ppy.sh/beatmapsets/350295#osu/773905)
Use random mod
Get 149pp (my top play is currently 90pp)

### Screenshots or videos

[the play](https://osu.ppy.sh/scores/3599514358)
[download](https://drive.google.com/file/d/1urUnpqHeDRPeR7jkZc-jVQqX9q0TN3bm/view?usp=sharing)

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17179030/compressed-logs.zip)

**Comment by bdach** [comment]
1. #29729
2. The random mod is unranked so you're not "getting" any pp anyway.
