### ISSUE TITLE
Stable scores have a chance to be missing the profile picture in lazer

### ISSUE THREAD

**Issue by Y2nn1c** [ppy/osu#30066]
### Type

Game behaviour

### Bug description

Scores set on stable have a chance to display the default profile picture on lazer, furthermore both can be the case for the same score.

### Screenshots or videos

![osu_2024-09-30_21-40-00](https://github.com/user-attachments/assets/4c17f65c-0fe5-41bd-baa2-6859f034a603)
![osu_2024-09-30_21-40-03](https://github.com/user-attachments/assets/9e3730b7-8e4b-41ea-978c-0f5a1e2baf03)
![osu_2024-09-30_21-39-03](https://github.com/user-attachments/assets/cda844b1-9bda-41d7-b78e-8ec2e77738eb)

### Version

Lazer: 2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17195767/compressed-logs.zip)

**Comment by bdach** [comment]
This can happen if the replays in question do not have an online score ID assigned (i.e. did not submit). This is intentional to avoid possible impersonation (see https://github.com/ppy/osu/issues/24624).
