### ISSUE TITLE
While you're in beatmap selection menu you can't change volume with arrows while volume is hovered with mouse

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3007]
logs:
[database.log](https://github.com/ppy/osu/files/2184790/database.log)
[network.log](https://github.com/ppy/osu/files/2184791/network.log)
[performance.log](https://github.com/ppy/osu/files/2184792/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2184793/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2184794/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2184795/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2184796/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2184797/runtime.log)

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/8090.
