### ISSUE TITLE
volume wheels are hidden behind options menu

### ISSUE THREAD

**Issue by tuszmak** [ppy/osu#30082]
### Type

Cosmetic

### Bug description

Reproduction:
1. Open the options tab
2. Try to change the volume with alt + mouse wheel

### Screenshots or videos

https://github.com/user-attachments/assets/7c83641c-70dc-4ec4-ba50-d67beee3e77b

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17212564/compressed-logs.zip)

**Comment by bdach** [comment]
#11077
