### ISSUE TITLE
Social Browser doesnt load the flag and wrong rank-letter

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3009]
![ss 2018-07-11 at 05 43 25](https://user-images.githubusercontent.com/17437302/42583817-0f37e154-8532-11e8-95a3-bac2a0b60f32.png)

It loads right when you re-load it. but the first time it doesnt
![ss 2018-07-11 at 05 50 27](https://user-images.githubusercontent.com/17437302/42584193-eb1836a6-8532-11e8-8fc6-9846da3388dd.png)

**Comment by HoutarouOreki** [comment]
Only happens the first time since starting the client, then every single one loads fine.

**Comment by HoutarouOreki** [comment]
Happens after changes from #2977.
