### ISSUE TITLE
GitHub Wiki page incorrectly states behavior of slider tails

### ISSUE THREAD

**Issue by TechniKris** [ppy/osu#30103]
### Type

Other

### Bug description

This isn't about the osu! wiki, it's about [this GitHub repository's wiki](https://github.com/ppy/osu/wiki).
This page https://github.com/ppy/osu/wiki/Anatomy-of-a-slider incorrectly states that:
- missing a slider tail on stable causes a miss,
- hitting a slider tail on lazer doesn't increase combo.

The part about stable is clearly incorrect. The part about lazer hasn't been the case for a long time already.
I would've committed a PR, but I'm pretty sure it's not possible to do with GH Wikis.

As for numerical values: (I'm not sure whether my assumption is correct, since there's `combo_bonus` mentioned, but):
- slider tail on lazer is listed as awarding `10(SmallTick)`.

Since https://github.com/ppy/osu/pull/26248 the tail should be listed as awarding `150(SliderTailHit)`, based on this page https://github.com/ppy/osu/wiki/Scoring

The part about classic mod's issue is still true.

### Screenshots or videos

Highlighted incorrect parts in yellow:

![image](https://github.com/user-attachments/assets/cd9b88bd-8a72-46fd-8898-920893c383d9)

### Version

revision: 6268b27

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17247467/compressed-logs.zip)
lol

**Comment by bdach** [comment]
I've updated the page, although not entirely in the way you claim it should be updated, as I'm pretty sure some of your claims were incorrect. That said, we've deeply complicated this stuff, so if you want to double-check the new version for correctness then by all means.
