### ISSUE TITLE
Render (Vulkan) freezes if you have no beatmaps installed

### ISSUE THREAD

**Issue by makisukurisu** [ppy/osu#30105]
### Type

Game behaviour

### Bug description

I've just installed the game with no beatmaps (not even the tutorials), and went to change the renderer to Vulkan (IIRC, it gave more performance on my setup), then I opened "Play" -> "Solo" and the rendering froze.

I've tried to do the same with DirectX 11, and it worked OK (as you can see in the video bellow)

### Screenshots or videos

https://github.com/user-attachments/assets/d9f4fa7f-88d9-492c-bd5e-78fa1acd6855

*I've added relevant captions and speed up some parts of the recording

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17249250/compressed-logs.zip)

I believe that logs with `1727982893` and `1727984169` prefixes would be of value.
(`1727984169` was one where I've closed the game and opened it again with no maps, `1727982893` was the one where I've had a downloaded beatmap and then removed it within the game, in this case the beatmap list didn't crash the rendering)

**Comment by makisukurisu** [comment]
Sorry if not the most correct terms were used in the postulation of the issue.

Also sorry for the amount of log files in the zip archive, I went overboard to ensure how and why the issue occurred.

**Comment by bdach** [comment]
If vulkan is broken for you then don't use it. We're not willing to commit development time to fix the current vulkan implementation because it's terminally broken.
