### ISSUE TITLE
Music speeds up and stutters.

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#3011]
Logs: [logs.zip](https://github.com/ppy/osu/files/2185548/logs.zip)
YouTube Video: youtu.be/vznlDTBZI2k

After playing map and quitting it music speeds up and selecting any other song = stuttering.
Yt video should explain everything.

**Comment by Morilli** [comment]
These logs don't show much, you should enable performance logging under debug settings ingame.

**Comment by ToIGLAK** [comment]
Weird... I restarted osu! 5 times and bug still appeard but now everything looks fine. Oh i updated windows in the meantime. Whatever

Sorry for unnecessary posting :/
