### ISSUE TITLE
Analysis Cursor misaligned on replays with Barrel Roll

### ISSUE THREAD

**Issue by Wrongwayscout** [ppy/osu#30119]
### Type

Crash to desktop

### Bug description

Replays with Barrel Roll show the cursor path as if the map was not altered when using the analysis cursor.

### Screenshots or videos

https://github.com/user-attachments/assets/ab1df771-6511-4afb-93de-4e73899a9086

### Version

2024.906.2

### Logs

.

**Comment by ssz7-ch2** [comment]
will be fixed in next release https://github.com/ppy/osu/pull/29841
