### ISSUE TITLE
Selecting a group sort from the difficulty sort doesn't keep the same map selected

### ISSUE THREAD

**Issue by bencecile** [ppy/osu#30127]
### Type

Game behaviour

### Bug description

Steps to reproduce:
1. Sort beatmaps by difficulty
The same beatmap selection is kept when moving to difficulty sort from a group sort 
2. Sort by any other grouping sort (Last Played, Artist, Title, etc.)
The current selected beatmap and beatmap group is now different than what was selected after step 1

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17270524/compressed-logs.zip)

**Comment by bdach** [comment]
Already fixed, fix will be out in next release
