### ISSUE TITLE
2018.710.0 - "Disable mouse buttons during gameplay" doesn't do anything

### ISSUE THREAD

**Issue by whizvox** [ppy/osu#3012]
Made a little video showcasing it: https://www.youtube.com/watch?v=bQMmLM0dcRQ

(Sorry, I accidentally covered up the input display, but it also shows the mouse buttons being clicked even as the option to disable them is on)

I show off the bug first: I disable mouse buttons, but I can still click the notes with my mouse. Enabling them back yields the expected effect, so the toggle in general doesn't do anything. The only way to get the intended effect was to remove the mouse buttons from the key configuration, which shouldn't be necessary.

I don't show it in the video, but "Disable mouse wheel during gameplay" works just fine.

**Comment by Morilli** [comment]
This was already fixed in #2948. You'll have to wait for next public release which should fix this issue.

**Comment by whizvox** [comment]
I searched "disable mouse" and nothing came up. Better check closed issues next time.
