### ISSUE TITLE
Proposal: downloading beatmaps in osu!direct by non-supprters

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3013]
When non-supprters try to download beatmap with osu!direct menu osu! should open beatmap page in external browser e.g. Firefox 
i think it will be much more comfortable and logical/easy for players
Now if you aren't osu!supporter you have to:
1. Open beatmap details
2. Click link to beatmap page

**Comment by peppy** [comment]
what is “this menu”? also please make issue titles shorter.

**Comment by HoutarouOreki** [comment]
it's probably osu!direct

**Comment by ticotaco72** [comment]
Updated
