### ISSUE TITLE
Skin Editor: Crashes on save

### ISSUE THREAD

**Issue by necocat0918** [ppy/osu#30138]
### Type

Crash to desktop

### Bug description

saving using "ctrl + shift + s" in skin editor will cause lazer to crash for some reason

### Version

2024.906.2

### Logs

[compressed logs.zip](https://github.com/user-attachments/files/17278316/compressed.logs.zip)

**Comment by necocat0918** [comment]
I have osu-development build using the same folder, maybe that is the issue

**Comment by bdach** [comment]
> I have osu-development build using the same folder, maybe that is the issue

What does this even mean? Did you point your dev build at the release game directory?

Also please include video of this because I can't reproduce. And also information about what skin is this happening on.

**Comment by necocat0918** [comment]
I pointed my dev build directory to my release directory, so they are all using the same data

I don't know how to make the crash happen again, it just won't let me put object and crash after save

**Comment by bdach** [comment]
If you're sharing dev data and release data (which is an unsupported configuration), you can't make it happen again, and you don't have a reproduction scenario, then there's nothing to go on here. I'm not spending however much time spending something that - chances are - could not ever happen in a real configuration or is a direct result of your local dev changes.
