### ISSUE TITLE
Vulkan renderer freezes graphics when entering play mode

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#30150]
### Type

Game behaviour

### Bug description

After entering play mode (on osu! ruleset) with Vulcan (experimental) renderer, the game's graphics seems to freeze, but it **still responds** to keyboard/mouse input (Esc, Alt + F4) and **plays** the beatmap's **song** (and fails after a while)
Furthermore, holding ; to restart the beatmap **crashes** the game entirely.

This happens with any framerate limit, on **Windows**, Multithreaded, Fullscreen and on 3440x1440 resolution. (ultrawide monitor) 

### Screenshots or videos

https://github.com/user-attachments/assets/a3395a2a-9779-4b04-9db1-f6ed23a7f6d7

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17298445/compressed-logs.zip)

**Comment by yesseruser** [comment]
I've been able to play on a Linux machine with Vulkan renderer with no problems.

**Comment by yesseruser** [comment]
I can confirm this doesn't happen on Linux.

**Comment by bdach** [comment]
We don't accept vulkan bug reports. If it's broken don't use it. It will not receive fixes in its current state.
