### ISSUE TITLE
Updater will downgrade the client if running a newer version than latest release

### ISSUE THREAD

**Issue by Seercat3160** [ppy/osu#30166]
### Type

Other

### Bug description

Version [2024.906.2](https://github.com/ppy/osu/releases/tag/2024.906.2), when asked to check for updates, doesn't update to [2024.1009.0](https://github.com/ppy/osu/releases/tag/2024.1009.0) as that version is marked as a pre-release. However, manually updating to [2024.1009.0](https://github.com/ppy/osu/releases/tag/2024.1009.0) and running the game causes an automatic downgrade to [2024.1009.0](https://github.com/ppy/osu/releases/tag/2024.1009.0) in the background. 

A prompt is shown saying "Update ready to install. Click to restart!". Doing so results in 2024.906.2 running again.

There is no indication that a downgrade will occur.

### Screenshots or videos

As can be seen, it both shows that it has been updated, and notifies of the available upgrade (which is actually a downgrade).
![2024-10-09_21-55-04_grim](https://github.com/user-attachments/assets/1af8a528-0474-4588-bd06-08ccfdfebcf1)

### Version

2024.1009.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17306852/compressed-logs.zip)

**Comment by bdach** [comment]
Very much intentional to allow us to pull terminally broken builds if necessary, which is what happened today.

Please wait for an updated build.

**Comment by Seercat3160** [comment]
Ah, that makes more sense. Thanks for the swift response. I still feel that some UX improvements could be added for this scenario though, to prevent (for example) someone re-updating manually to the pulled build, given there is no indication that anything's wrong with it, and perhaps filing an issue (not unlike this one, oops).
