### ISSUE TITLE
Game screen is just dark when opening on Android 14

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#30168]
### Type

Crash to desktop

### Bug description

I've tested this with and without Angle (on Android 14, rooted)
The screen is just black. No osu! logo gets shown (except for app icon splash screen).
The screen orientation doesn't get locked to horizontal, I can rotate it freely.

### Screenshots or videos

https://github.com/user-attachments/assets/77aa0292-96bf-44dc-9c0e-bde35d4e05e4

### Version

2024.1009.0

### Logs

[logs.zip](https://github.com/user-attachments/files/17307367/logs.zip)
I couldn't get to the export logs button, so I just zipped them up.

**Comment by bdach** [comment]
Please try 2024.1009.**1**.

**Comment by yesseruser** [comment]
> Please try 2024.1009.**1** which went out recently.

Thank you, the new version works.
Sorry for bothering.
