### ISSUE TITLE
Settings Pop-up dialog doesn't show the decimal part of the value

### ISSUE THREAD

**Issue by rvneXe** [ppy/osu#30176]
### Type

Game behaviour

### Bug description

Hi. Grid settings' sliders can be set on a decimal value. The value which is displayed by the pop-up dialog is likely an integer, so it doesn't exactly match the setting's value if it's decimal.
![image](https://github.com/user-attachments/assets/e124ad0a-c04f-4132-b840-885b8dba5ad1)

### Version

2024.1009.1

### Logs

no need

**Comment by shinmorisawa** [comment]
will try!

**Comment by shinmorisawa** [comment]
i have a question, does this include other settings as well?

**Comment by rvneXe** [comment]
> i have a question, does this include other settings as well?

Ah sorry for delay. 
No, seems like it's only affecting Grid settings sliders.
