### ISSUE TITLE
Difficulties not in order, no difficulty color

### ISSUE THREAD

**Issue by Szyszqu** [ppy/osu#30174]
### Type

Cosmetic

### Bug description

Difficulties on some beatmaps are not in order like they were before the update (from the easiest to the hardest). There is also no difficulty color like shown on the image. 

### Screenshots or videos

![image](https://github.com/user-attachments/assets/01108023-2525-4119-8f5c-e0045dcc5469)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17308808/compressed-logs.zip)

**Comment by SoundBoomer** [comment]
Experiencing the same issue, difficulties inside beatmap sets are organized by alphabet instead of stars

**Comment by Szyszqu** [comment]
Well I'm still gonna leave the issue open but for me it just suddenly started working normally. I did not change any settings or reset my game.

**Comment by bdach** [comment]
This is normal while star rating recalculations are in progress. Please wait for them to complete.
