### ISSUE TITLE
Can't launch AppImage after latest update

### ISSUE THREAD

**Issue by LotEep** [ppy/osu#30187]
### Type

Crash to desktop

### Bug description

Trying to launch the osu AppImage immediately fails, no matter what I try to do. This started happening immediately after I update to the latest version. The flatpak works fine but it's out of date.
This is the error:
```
$./osu.AppImage
exec: Failed to execute process './osu.AppImage': The file exists and is executable. Check the interpreter or linker?
```

 I have tried using AppImage-launcher, but it returns a different error.
When selecting the "run once" option after executing the AppImage:
```
$./osu.AppImage
execv error: No such file or directory
```
And when selecting the "Integrate and run option"
```
$./osu.AppImage
WARNING: No icons found at "usr/share/icons"
WARNING: Using .DirIcon as default app icon
ERROR: Entry doesn't exists: .DirIcon
ERROR: No icon was generated for: /home/bob/Applications/osu_c1608c8d413ff673a688613c50bfa68d.AppImage
ERROR: appimage_register_in_system : Entry doesn't exists: .DirIcon
gtk-update-icon-cache: The generated cache was invalid.
```

They all seem to be related in some way but I have no clue where to start in terms of trying to debug this. Any help is appreciated.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/6c091524-459a-4bdf-8744-2b666b923b0d)
![image](https://github.com/user-attachments/assets/15c3412c-2364-4cef-b7f2-23e365d2b8d2)

### Version

2024.1009.1

### Logs

[osu-logs.tar.gz](https://github.com/user-attachments/files/17318199/osu-logs.tar.gz)

**Comment by DuckyShine004** [comment]
Refer to #30175, where the current solution is to use an older build.

**Comment by bdach** [comment]
The appimage was updated with a fix to this ~14 hours ago. Please try redownloading the appimage afresh and seeing if it is fixed.

**Comment by Electrenator** [comment]
> I also have this issue, even with the latest appimage. I've tried just running it, won't even open the game. Trying to integrate it gives me the error: "Failed to register AppImage in system via libappimage".

Sounds like the same issue as with #30175 (closed but not fixed). The only working workaround I know of currently is to uninstall appimagelauncher and restart.

**Comment by bdach** [comment]
I have no idea how that is still the issue if the compression format has changed?

@Electrenator can you try the command listed in https://github.com/ppy/osu-deploy/pull/178#issue-2576527026?

**Comment by smoogipoo** [comment]
You will have to uninstall AppImageLauncher to fix it for now. I can't say yet whether this will change.

**Comment by Electrenator** [comment]
> I have no idea how that is still the issue if the compression format has changed?
> 
> @Electrenator can you try the command listed in [ppy/osu-deploy#178 (comment)](https://github.com/ppy/osu-deploy/pull/178#issue-2576527026)?

![
$ dd if=osu_latest_2024.1009.1.AppImage bs=1 skip=$(./osu_latest_2024.1009.1.AppImage --appimage-offset) count=32 2>/dev/null | file -
/dev/stdin: Squashfs filesystem, little endian, version 4.0, zlib compressed, 0 bytes, 472 inodes, blocksize: 131072 bytes, created: Thu Jan  1 00:00:00 1970
$ dd if=osu_2024.906.2.AppImage bs=1 skip=$(./osu_2024.906.2.AppImage --appimage-offset) count=32 2>/dev/null | file -
/dev/stdin: Squashfs filesystem, little endian, version 4.0, xz compressed, 0 bytes, 471 inodes, blocksize: 16384 bytes, created: Thu Jan  1 00:00:00 1970
$ dd if=osu_2024.817.0.AppImage bs=1 skip=$(./osu_2024.817.0.AppImage --appimage-offset) count=32 2>/dev/null | file -
/dev/stdin: Squashfs filesystem, little endian, version 4.0, zlib compressed, 0 bytes, 478 inodes, blocksize: 131072 bytes, created: Thu Jan  1 00:00:00 1970
](https://github.com/user-attachments/assets/6c289a0e-8625-4954-95ab-038fb69604f1)

Of these all except 2024.1009.1 seem to work without issues. So both have a pre and post-velopack builld which work

**Comment by smoogipoo** [comment]
Has now been fixed in the latest release.

**Comment by LotEep** [comment]
Alright it works like normal now thanks.
