### ISSUE TITLE
Playfield elemets shift towards the center of the layer but doesn't in the HUD layer.

### ISSUE THREAD

**Issue by ParaliyzedEvo** [ppy/osu#30191]
### Type

Game behaviour

### Bug description

When trying to match positions on the playfield layer to the elements in the HUD layer, elements in the playfield shift to the center instead of staying where I want it to be. It seems to be only happening in that layer as the other HUD layers work as intended. Ngl it was kind of a struggle to match the positions on the HUD layer since I had to move elements offscreen via arrow keys. I'm trying to move elements into different layers as I want those elements visible when I shift+tab.

### Screenshots or videos

https://github.com/user-attachments/assets/b7204add-eedc-4beb-8d2b-5763d6d169a0

### Version

2024.1009.1

### Logs

[logs.zip](https://github.com/user-attachments/files/17321387/logs.zip)

**Comment by bdach** [comment]
The behaviour of the playfield layer you mention is intentional, and it can't change as it would defeat half the purpose of the layer.

> I'm trying to move elements into different layers as I want those elements visible when I shift+tab.

This shall be supported by having a per-element toggle for visibility when HUD is hidden, whenever that eventually happens.
