### ISSUE TITLE
Rectangles everywhere in osu!

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3020]
logs:
[database.log](https://github.com/ppy/osu/files/2189057/database.log)
[network.log](https://github.com/ppy/osu/files/2189058/network.log)
[performance.log](https://github.com/ppy/osu/files/2189059/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2189060/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2189061/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2189062/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2189063/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2189064/runtime.log)

screenshot:
![osu_2018-07-12_16-39-32](https://user-images.githubusercontent.com/32620809/42640910-a2555252-85f3-11e8-8d5d-bbee9c562130.jpg)

rectangle disappeared after a moment with opened notifications

**Comment by ticotaco72** [comment]
is it
'12.07.2018 14:37:57: Drive:                      {0.0.0.00000000}.{d89fb9af-45ba-4e3b-b0b2-3b056a7cdbd5}'
in runtime.log

**Comment by ticotaco72** [comment]
![osu_2018-07-12_16-47-22](https://user-images.githubusercontent.com/32620809/42641461-e1f6683c-85f4-11e8-8390-475689a30706.jpg)
in left lower corner

**Comment by ticotaco72** [comment]
logs for blue square:
[database.log](https://github.com/ppy/osu/files/2189549/database.log)
[network.log](https://github.com/ppy/osu/files/2189550/network.log)
[performance.log](https://github.com/ppy/osu/files/2189551/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2189552/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2189553/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2189554/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2189555/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2189556/runtime.log)

**Comment by ticotaco72** [comment]
![osu_2018-07-12_19-36-03](https://user-images.githubusercontent.com/32620809/42650284-4654e954-860c-11e8-9995-d05c4a986837.jpg)
logs:
[runtime.log](https://github.com/ppy/osu/files/2189660/runtime.log)

[database.log](https://github.com/ppy/osu/files/2189653/database.log)
[network.log](https://github.com/ppy/osu/files/2189654/network.log)
[performance.log](https://github.com/ppy/osu/files/2189655/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2189656/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2189657/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2189658/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2189659/performance-gamethread.update.log)

**Comment by peppy** [comment]
I have no idea what this is, but it doesn't look osu! related. Do you have any other overlays running on your PC?

**Comment by ticotaco72** [comment]
i have discord and this stupid xbox overlay in win 10
this isn't matter from xbox beacause it didn't cange anything earlier
i've installed discord last time and maybe it could be the matter, but then more people would have problem.

and rectangles are covering hit objects but not corsor except this blue. 
obs is recording them as they belong to osu! window

**Comment by ticotaco72** [comment]
and i can't reproduce it today

**Comment by ticotaco72** [comment]
above screenshots are osu! made

**Comment by ticotaco72** [comment]
okay i'm closing it. if i encounter it in future time i'll reopen
