### ISSUE TITLE
The built-in skin editor scale some element bigger than preview page

### ISSUE THREAD

**Issue by Levin-7** [ppy/osu#30200]
### Type

Cosmetic

### Bug description

When use some element in vertical, it will be scaled bigger in play than I saw in editor.
(now I found it happen on ArgonHealthDisplay, ArgonSongProgress and DefaultSong Progress)
I repeat it on my another machine.
I will give you a example below, and if it is designed or it has been solved, please give me a link.

### Screenshots or videos

Let's take the timeline in the center as a example
This is where it stay 
![osu_2024-10-10_20-21-03](https://github.com/user-attachments/assets/b1c0f7b3-6574-49c7-9ad6-e0abfbffc6b3)
This is what i expect
(The time stay in screen)
![osu_2024-10-10_20-18-52](https://github.com/user-attachments/assets/c8ec72fc-3e4b-423b-91ed-d317ec3c25dd)
And this is what it become
(The time has been scaled out of screen)
![osu_2024-10-10_20-21-19](https://github.com/user-attachments/assets/e80aeeb4-2857-433c-9a31-49cba9f10211)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17328545/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/24388
