### ISSUE TITLE
cursor wont move when using tablet on mouse mode

### ISSUE THREAD

**Issue by LyKxrma** [ppy/osu#30216]
### Type

Game behaviour

### Bug description

cant play when i use my pen when its on "mouse", registering the movement as a mouse. and im too far in to switch my playstyle, ive been playing like this for years now.im not the only one with this playstyle, even "worst hr player" plays just like this. when i reported this issue a while back i simply got ignored and the issue was closed by someone else. 

### Screenshots or videos

https://streamable.com/ebb9e7

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17341841/compressed-logs.zip)

**Comment by bdach** [comment]
It wasn't "closed", it was converted to a discussion, because it's likely something specific to your setup.

Continuing back at your original discussion in https://github.com/ppy/osu/discussions/26767.
