### ISSUE TITLE
LAZER/ failed to submit score

### ISSUE THREAD

**Issue by skrllM1** [ppy/osu#30210]
### Type

Game behaviour

### Bug description

Any map i play it shows me these messages and after i finish map scores are not uploading. I tried to turn off my firewall, since it might be the problem but it occured even atfer i did it. Command sfc /scannow didn't do anything either

### Screenshots or videos

![изображение_2024-10-11_022859083](https://github.com/user-attachments/assets/a01b6531-5274-4b7a-8161-118205419586)
![изображение_2024-10-11_022959331](https://github.com/user-attachments/assets/405009e0-1e06-40df-b4bb-c7376efcf3b8)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17335371/compressed-logs.zip)

**Comment by smoogipoo** [comment]
It looks like this may be an intermittent connection failure do to your ISP, and there's not much that can be done here other than retrying score uploads which is covered under https://github.com/ppy/osu/issues/24609
