### ISSUE TITLE
Argon wedge transforming working incorrectly in the gameplay tab

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu#30229]
### Type

Game behaviour

### Bug description

Not sure how to explain it beyond that, but you should be able to see what i mean in the vid bellow

### Screenshots or videos

https://github.com/user-attachments/assets/96a062a2-96fa-45db-a37b-197c8850da96

### Version

osu! version: Lazer 2024.1009.1 (latest)

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17347612/compressed-logs.zip)

**Comment by peppy** [comment]
Track in #24388.
