### ISSUE TITLE
Make new release rather than modify an existing release

### ISSUE THREAD

**Issue by gepbird** [ppy/osu#30235]
### Type

Other

### Bug description

I understand that the latest release caused some difficulties. In my opinion 2024.1009.0 being released then pulled in a span of minutes is acceptable. However in a span of multiple hours, after the release of 2024.1009.1 only the AppImage was changed at least 2 times. With all the 3 AppImages I tested the basics and found no critical issues like crashes or database corruptions. May I ask what was the reason for changing it that many times (I know I could've done more research for this)?

For linux distributions like NixOS this is a big problem, because users who have for example the first AppImage's version and hash will be unable to download the seemingly same version's AppImage due to a hash mismatch. Experienced users can overwrite the hash themselves, but for others it causes some annoyance. This would be solved by making new hotfix releases in the future.

### Version

2024.1009.1

### Logs

-

**Comment by smoogipoo** [comment]
First issue: https://github.com/ppy/osu/issues/30175
Second issue: https://github.com/ppy/osu/issues/30187 (after the above fix)

We probably could have done two point-releases to fix the issues, and we'll keep that in mind for next time.
