### ISSUE TITLE
Weird slider not matching stable

### ISSUE THREAD

**Issue by namooTH** [ppy/osu#30238]
### Type

Game behaviour

### Bug description

In this beatmap on the difficulty `Emilia's C9H13NO3` https://osu.ppy.sh/beatmapsets/539221#osu/1267365, the slider at `03:38:662 (1)` does not match the stable client, this happens in both the editor and the gameplay.

### Screenshots or videos

https://github.com/user-attachments/assets/fa39bb7f-41a1-410a-9943-a92b91c885d1

### Version

2024.906.2 and 2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17350100/compressed-logs.zip)

**Comment by smoogipoo** [comment]
This is because the slider uses an "infinite BPM" trick which is not supported by lazer, and falls into the category of Aspire-like maps that break the game.
