### ISSUE TITLE
Slider cheese for easy PP (New PP system)

### ISSUE THREAD

**Issue by xenaiosu** [ppy/osu#30230]
### Type

Other

### Bug description

I'm not sure where to report this, but I hope this is the right way to report an issue. 

But I've noticed that you can **cheese sliders** way to much with the **new PP system**, especially slider breaks. It seems like slider breaking barely causes any dent in your PP (see video for an example).
Slider ends feel the same way too, you lose acc like normal but you don't lose much PP for them either. (accuracy PP also doesn't get affected by that, although idk if that was intentional or not)

This wasn't the case before, at least with slider breaking due to Combo Scaling. Slider ends didn't lose much but still got affected a little since they didn't give combo.

Not sure if the video shows enough info, so here is the full score link: https://osu.ppy.sh/scores/3666046260

The last image is someone that got a 1k from https://osu.ppy.sh/beatmapsets/1376308#osu/2844649 , where they didn't even track the sliders.

Last edit: https://osu.ppy.sh/scores/3667083315 (this is probably the best example. I got 128/144pp even though I only hit a single sliderend and slider broke like crazy)

### Screenshots or videos

https://github.com/user-attachments/assets/ef7e5c63-2996-495c-8979-9c7b988adbfd

![image](https://github.com/user-attachments/assets/9db88d5b-1028-4f8a-a9e6-4ba37978da9b)

![image](https://github.com/user-attachments/assets/577cab8f-7024-4625-9a4f-0f7ec213d9b7)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17347841/compressed-logs.zip)

**Comment by smoogipoo** [comment]
cc @ppy/osu-pp-committee

**Comment by stanriders** [comment]
Will be fixed by https://github.com/ppy/osu/pull/27691

@smoogipoo this is indeed a deploy blocker until that PR is merged

**Comment by Givikap120** [comment]
> Will be fixed by #27691
> 
> @smoogipoo this is indeed a deploy blocker until that PR is merged

only partially
Flami score is only down to 770
consider also merging https://github.com/ppy/osu/pull/29991
