### ISSUE TITLE
Using MR and ST mods makes slider tick appear at the head of the sliders

### ISSUE THREAD

**Issue by xDololow** [ppy/osu#30237]
### Type

Cosmetic

### Bug description

Notices this when played daily challenge. 

### Screenshots or videos

https://files.xxxd.org/revo1/NAJUhOjA45.mp4 here's video (sound warning)

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17350046/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/blob/2de19558923160116a0139a955fa431008ef5d89/osu.Game.Rulesets.Osu/Utils/OsuHitObjectGenerationUtils.cs#L168-179

is no longer necessary or correct after https://github.com/ppy/osu/pull/30021
