### ISSUE TITLE
mania

### ISSUE THREAD

**Issue by laoqijun1** [ppy/osu#30249]
### Type

Game behaviour

### Bug description

移动端的mania很有问题。mania目前的操作方法与移动端大部分同类型的玩法背道而驰，我希望能还原以前的操作方法。
The mobile gaming mania is a problem. The current operation method of mania goes against the operation method of most similar games on mobile devices, and I hope to restore the previous operation method.

### Version

2024.1009.1

### Logs

no

**Comment by bdach** [comment]
https://github.com/ppy/osu/discussions/28361
