### ISSUE TITLE
Very Bad Performance

### ISSUE THREAD

**Issue by LossBG** [ppy/osu#30248]
### Type

Performance

### Bug description

It's already happen when I download the game!Enter the game,UI is bug and sometime lead me to crash or even shut down my phone.Into the gameplay,some of the sliders get disappear and it's hard/unable for me to play.Please fix the bug as soon as possible! 

### Screenshots or videos

https://github.com/user-attachments/assets/2a064a06-e00f-4bad-90e2-46c8c12dab80

### Version

2024.1009.1

### Logs

[logs.zip](https://github.com/user-attachments/files/17351314/logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25189, most likely
