### ISSUE TITLE
Delete beatmap dialog uses romanised name

### ISSUE THREAD

**Issue by Parsa-GP** [ppy/osu#30242]
### Type

Cosmetic

### Bug description

When you try to delete a beatmap, it shows the Romanized name of the artist and the beatmap name.

I suppose the dialog code is in this line if it helps:
https://github.com/ppy/osu/blob/master/osu.Game/Screens/Select/BeatmapDeleteDialog.cs#L17

### Screenshots or videos

![osu_2024-10-12_16-19-44](https://github.com/user-attachments/assets/88e5c196-d5fc-47f7-ba79-cd8c9622445f)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17350585/compressed-logs.zip)

**Comment by shinmorisawa** [comment]
i'm currently working on a fix, but i'm unsure how to access settings.

**Comment by shinmorisawa** [comment]
you guys did good here. thanks for all who helped!
