### ISSUE TITLE
Chat loads forever when not logged in

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3024]
when you are logged out and open chat and there will be only loading animation
i think chat should be available to read when you aren't logged in or possibly there should be info about that chat isn't available for not logged in users

**Comment by peppy** [comment]
It won't be available for reading, but it should show that you require login in some way (or not open/be disabled).

**Comment by HoutarouOreki** [comment]
Should it show login panel or push a notification telling the user to sign in when trying to open chat?

**Comment by peppy** [comment]
We'll probably need to devise a common design for this.

**Comment by smoogipoo** [comment]
Pinging @arflyte again
