### ISSUE TITLE
osu!lazer doesn't do anything when opening

### ISSUE THREAD

**Issue by Owta** [ppy/osu#3025]
any time i open lazer, it loads the window, allocates 36kb of ram, and hangs, without any error messages, logs being made or any message from windows 7 or 10 saying it stopped working.
just in case, i'll list my specs here

Intel Core i5-2520m @2.5GHz, 8GB RAM, Intel HD 3000 iGPU, using the PHDGD Omega 4.0 custom driver on windows 10, and the standard Intel driver on windows 7.
![taskmgr_2018-07-12_22-01-09](https://user-images.githubusercontent.com/20073478/42667073-65f8bfac-861f-11e8-914f-e5f268bd916a.png)

**Comment by AlFasGD** [comment]
Are there any log files?

**Comment by Owta** [comment]
nope, no log files were made at all. kinda odd to be honest

**Comment by Owta** [comment]
okay so i installed lazer again and removed the osu folder in Roaming, now i actually have logs.
[performance.log](https://github.com/ppy/osu/files/2194311/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2194312/runtime.log)

**Comment by peppy** [comment]
It looks like you have no valid graphics drivers installed. osu! is unable to get a valid OpenGL 2.0+ context.

**Comment by Owta** [comment]
okay so i reinstalled my graphics drivers on both windows 10 and windows 7, now lazer opens fine on both
