### ISSUE TITLE
Failed to submit score (BadGateway)

### ISSUE THREAD

**Issue by ashandelle** [ppy/osu#30265]
### Type

Game behaviour

### Bug description

I was just playing and I got a message saying that my score failed to submit. After leaving the results screen the leaderboard didn't load for a minute so I might have disconnected for a minute. My score did not get updated.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/9bc439ef-b983-4b18-81bb-b9fcff73abf5)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17356223/compressed-logs.zip)

**Comment by bdach** [comment]
The website had a moment. Should be back up now.
