### ISSUE TITLE
Failure to update due to System.Net.WebException: Forbidden

### ISSUE THREAD

**Issue by hiderikzki** [ppy/osu#30267]
### Type

Game behaviour

### Bug description

Opened up osu! to see notification to make sure to update the game when going into a beatmap, even though I should have the latest version.

Trying to log in again did not fix the issue. Multiple failed requests to auth-files.ppy.sh

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17356811/compressed-logs.zip)

**Comment by bdach** [comment]
#30266
