### ISSUE TITLE
lazer not allowing me to submit scores (even though im on latest version)

### ISSUE THREAD

**Issue by Panguwuk** [ppy/osu#30266]
### Type

Game behaviour

### Bug description

This pop-up appeared when I tried to play a map today.

I've tried checking for updates and restarting the game, with no success.
please help

(It reappears every time i try to play a map)

### Screenshots or videos

![image](https://github.com/user-attachments/assets/35239cae-af39-4db7-8dcb-8a1ace6d2238)
![image](https://github.com/user-attachments/assets/6cf21a73-bee0-424e-afb0-76ecabf80ffa)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17356804/compressed-logs.zip)

**Comment by crumpledmint** [comment]
I have the same issue

**Comment by xzyq2** [comment]
same here
![image](https://github.com/user-attachments/assets/8177db26-0147-4bbd-a668-6ad5deffd303)

**Comment by bdach** [comment]
Please try again now. Might take a game restart to check.

**Comment by Panguwuk** [comment]
> Please try again now. Might take a game restart to check.

fixed, thanks
