### ISSUE TITLE
when hovering the progress bar pop up shows up even while not on breaktime

### ISSUE THREAD

**Issue by Jinkkuu** [ppy/osu#30289]
### Type

Cosmetic

### Bug description

Popup shows up and can be distracting sometimes if the song bar is on the playfield 

### Screenshots or videos

![osu_2024-10-14_18-28-48](https://github.com/user-attachments/assets/5accbe77-ada5-488f-ad3e-a9e7c8b95cb2)

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17369958/compressed-logs.zip)

**Comment by SchiavoAnto** [comment]
Has been fixed in [this PR](https://github.com/ppy/osu/pull/30199).
