### ISSUE TITLE
Song progress bar expanding leads to canvas expansion off the screen

### ISSUE THREAD

**Issue by shsh-x** [ppy/osu#30286]
### Type

Cosmetic

#### Description
When hovering argon song progress bar, the progress bar extends, extending a canvas (if the bar is vertically flipped), therefore moving all the objects that have origins at top a little bit up.

#### Expected behavior
Extending progress bar off the screen doesn't lead to canvas extension (i.e. the other objects that are not linked to the progress bar itself shouldn't move).

#### How to reproduce
1. Add extendable progress bar (e.g. argon)
2. Flip it vertically
3. Place it at the very top and move it upper more to hide the part of it
4. Hover it in the replay view

### Screenshots or videos

https://github.com/user-attachments/assets/70034983-5b7b-4e36-be89-d932430fd9d3

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17368143/compressed-logs.zip)

**Comment by bdach** [comment]
Cannot reproduce. Please attach skin.

**Comment by shsh-x** [comment]
[progressbar1 [test] (shshx).zip](https://github.com/user-attachments/files/17481072/progressbar1.test.shshx.zip)
you can actually just take the MainHUDComponents.json here
I honestly dont understand how this works, but i tried 12 different ways to reproduce it and it worked only once. I didn't even realize what steps i have done. The point of this component alignment is that progressbar shall expand
