### ISSUE TITLE
Crash to desktop on windows 10

### ISSUE THREAD

**Issue by gaugea** [ppy/osu#30285]
### Type

Crash to desktop

### Bug description

i was playing Save Me and around 3 minutes into the map my screen went black, i heard the sound of usb disconnected and reconnected, there were a couple lines on the screen (like what happens during a graphics driver update sometimes), and after a few seconds my screen came back on. i honestly was so confused as to what happened that i forgot i was even playing osu when it happened, and only realized that the game crashed when i checked event viewer (log attached). 

other details:
this has never happened to me before, and lazer typically runs very well and ive used it many times
im on DirectX 11 now, but earlier today I was trying out the other renderers to see how they run on my pc
i installed and started using rawaccel today, unsure if related

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17365506/compressed-logs.zip)
[eventviewerlog.zip](https://github.com/user-attachments/files/17365526/eventviewerlog.zip)

**Comment by SchiavoAnto** [comment]
Were you using the regular Direct3D renderer or the experimental one?

![image](https://github.com/user-attachments/assets/8a07280f-4a68-45ac-af2f-4c10c83a154f)

**Comment by gaugea** [comment]
> Were you using the regular Direct3D renderer or the experimental one?
> 
> ![image](https://private-user-images.githubusercontent.com/63348037/376292411-8a07280f-4a68-45ac-af2f-4c10c83a154f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTc5MTYsIm5iZiI6MTcyODkxNzYxNiwicGF0aCI6Ii82MzM0ODAzNy8zNzYyOTI0MTEtOGEwNzI4MGYtNGE2OC00NWFjLWFmMmYtNGMxMGM4M2ExNTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE0NTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTI4NjhiY2NiNTA2MzE5YTg3NTM0ODM0MTg0NDY4MzdiMjcxNzMzMTdkOThkNjdkNWI0YmI4MWQyYzEwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NJCp7tX-pLgEE87PTty_dFj72S73hBoz-4Qs0oKPTDo)

regular, but i tested out the experimental version earlier today (switched back because it gives me lower fps)

**Comment by smoogipoo** [comment]
Error is `DXGI_ERROR_DEVICE_REMOVED`, which appears to indicate a GPU driver hang/crash.

Dunno. It's possible that we _could_ be causing this but it's not something that can be immediately actioned on.
