### ISSUE TITLE
Remove Red Light Warning When Using No-Fail Mod

### ISSUE THREAD

**Issue by syzyxy** [ppy/osu#30291]
### Type

Cosmetic

### Bug description

NF is meant to eliminate the worry of failing, these warnings are unnecessary and can be disruptive. Players use NF to focus on improvement without the stress of failing, so the warnings contradict the mod's purpose. The Stable version does not have this so might be better to be consistent with that. 

Or at least make the warning appear just once. Having the red warnings flash on the sides every time you're near failing/have failed is really distracting, especially when you're trying to recover.

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17371810/compressed-logs.zip)

**Comment by bdach** [comment]
There's a setting for this already. Search for "Fade playfield to red when health is low" in settings.

**Comment by syzyxy** [comment]
perhaps this 

> There's a setting for this already. Search for "Fade playfield to red when health is low" in settings.

Thanks, but perhaps this should be off by default.

**Comment by bdach** [comment]
That was actually a mistake, the setting I was originally thinking of is "Show health display even when you can't fail".

**Comment by syzyxy** [comment]
I see now, but again I'd suggest making this off by default given the said reasons in the main post if possible.

**Comment by peppy** [comment]
It wouldn't be completely again having it disabled in NoFail mod, assuming that's what stable used to do.
