### ISSUE TITLE
Polygon menu in editor makes right menu act weird

### ISSUE THREAD

**Issue by shsh-x** [ppy/osu#30308]
### Type

Other

#### Description
In editor, when the polygon menu is opened the right menu can't open with its max width on hover and start doing weird things which I'm sadly unable to describe due to the lack of language knowledge.
#### Expected behavior
1. When the polygon menu is opened, right menu should open wide on hover and not try to minimize itself until unhovered.
2. When the polygon menu is opened, it should not try to stick to right corner of the screen when right menu is scrolled up.
#### How to reproduce
1. Open map editor
2. Open Polygon
3.1. Hover right menu for a few seconds
3.2. Scroll right menu up with mouse wheel (the more the better)

### Screenshots or videos

https://github.com/user-attachments/assets/6ffd28e9-e351-44b7-8d36-0621088ef199

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17393470/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/29511

**Comment by shsh-x** [comment]
Im sorry for commenting the closed issue but mentioned issue doesn't cover the horizontal displacement of polygon menu on right menu scroll

**Comment by bdach** [comment]
Let's just track both there, I left a comment on the old one to remember about that second thing too.
