### ISSUE TITLE
Metal renderer capped at 60 FPS but I have 4x refresh rate set

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#30302]
### Type

Performance

### Bug description

For some reason, on OpenGL I'm able to hit 200 FPS but on Metal the FPS is capped at 60. My frame limiter is at 4x refresh rate.

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17385397/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25985
