### ISSUE TITLE
Where is 10 pp?

### ISSUE THREAD

**Issue by lMikoFoxl** [ppy/osu#30325]
### Type

-

### Bug description

osu displays more pp than https://osu.ppy.sh

### Screenshots or videos

![1](https://github.com/user-attachments/assets/e9ee6822-7512-4337-8d17-0522dddf3d4d)
![2](https://github.com/user-attachments/assets/ee3889f7-b458-4535-a057-7771d486b928)

### Version

2024.1009.1-lazer

### Logs

-

**Comment by Joehuu** [comment]
The website pp is not updated yet. You can watch the video in https://osu.ppy.sh/home/changelog/lazer/2024.1009.1 for clarification.
