### ISSUE TITLE
Perfect combo and accuracy aren't highlighted in `DrawableTopScore`

### ISSUE THREAD

**Issue by 424ever** [ppy/osu#30342]
### Type

Cosmetic

### Bug description

On the website, a perfect combo and 100% accuracy are highlighted in green in the section showing the personal best and number 1 score on a beatmap (the same way they are highlighted in the score table). This is not the case in-game.

### Screenshots or videos

website
![firefox_fEHsRRXVEm](https://github.com/user-attachments/assets/51b78164-d983-41b3-89be-dba27fe2dfe8)

lazer
![osu_2024-10-18_21-06-40](https://github.com/user-attachments/assets/227a9504-dd2d-4c0a-ad57-083fbe192455)

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17439781/compressed-logs.zip)

**Comment by TaterToes** [comment]
Personally, I do think it should be highlighted in game, but I will wait to see if others disagree

**Comment by Joehuu** [comment]
Implemented in https://github.com/ppy/osu/pull/30346.
