### ISSUE TITLE
Setting to VSync on multithreaded and fullscreen causes Draw FPS Cap to reach 1000

### ISSUE THREAD

**Issue by TaterToes** [ppy/osu#30344]
### Type

Performance

### Bug description

Operating System: Windows 10 Pro
Processor: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz   3.50 GHz
RAM: 12 GB
Refresh Rate: 99.93 Hz

as shown in the video, setting it to 2x refresh rate works as expected. But when set to VSync, the draw fps cap isn't set to the refresh rate but 1000 fps.

### Screenshots or videos

https://github.com/user-attachments/assets/f9491afd-5a68-4218-bfa7-3b73289a2bcd

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17441539/compressed-logs.zip)

**Comment by Joehuu** [comment]
Did you modify this setting? With it off or fast, vsync seems to limit at 4x refresh rate for some reason.

![nvcplui_yg8aXjyI0F](https://github.com/user-attachments/assets/306bfdc2-1874-4a47-8743-bf081f8bd631)

**Comment by TaterToes** [comment]
it seems like that was the issue
