### ISSUE TITLE
Slider tails have a slice missing visually

### ISSUE THREAD

**Issue by cloudrac3r** [ppy/osu#30350]
### Type

Cosmetic

### Bug description

The tail of the first slider of the second combo `00:01:901 (1) - ` on this map https://osu.ppy.sh/beatmapsets/499488#osu/1114962 (Andrea's Insane difficulty) has a piece visually missing from it. There is a wedge-shaped piece cut out from the slider tail.

**This is only visible in certain scaling modes. I only tested on fullscreen 1920x1080.**

It happens regardless of the snaking sliders setting. Most sliders do not have this issue but this particular slider in this difficulty does reliably reproduce the issue. I have seen this on other maps too but I forgot which ones.

### Screenshots or videos

It is visible in the editor for argon skin if you have screen scaling off and the top bar is visible (press Ctrl+T):

![image](https://github.com/user-attachments/assets/4fa3a81f-1b20-486f-9b15-4c99ea62afff)

Argon skins in gameplay (ensure top bar is hidden, set screen scaling vertical scale to 89%):

![image](https://github.com/user-attachments/assets/d32d40b2-5548-4865-a323-53eb43d65607)
![image](https://github.com/user-attachments/assets/24dbbff1-e4bb-4c65-8254-a3f644fe6b05)

Triangles skin in gameplay (ensure top bar is hidden, set screen scaling vertical scale to 88%):

![image](https://github.com/user-attachments/assets/7c97b591-9f6e-45b7-9777-d5debed6f007)

Image skins (except for classic 2013) (ensure top bar is hidden, set screen scaling vertical scale to 88%):

![image](https://github.com/user-attachments/assets/5cd04c8f-d5a0-4bf0-b21c-67074ffbc20f)
![image](https://github.com/user-attachments/assets/820699f3-a263-44a9-9f15-7bdea0188def)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17444880/compressed-logs.zip)

**Comment by bdach** [comment]
#29645
