### ISSUE TITLE
note counting on result screen not working properly

### ISSUE THREAD

**Issue by object022** [ppy/osu#3036]
![image](https://user-images.githubusercontent.com/9292406/42720254-de900ace-86f1-11e8-892f-d492f4bfff53.png)

This image should be self-explanatory. I got an S on this map, but it still says I have 1 miss(I didn't).

This is on the latest build for mac / 2018.713.1. I'm running this on a MacBook Pro(early 2015 build) with High Sierra 10.13.5.

**Comment by LovelyA72** [comment]
I think that's how lazer's scoring system(score v2) works... You will get a S if your ACC is higher than 95% even you have miss.

**Comment by HoutarouOreki** [comment]
Just tested this by purposefully doing a full FC and then doing an FC with missing sliderends. These misses are missed sliderends.

**Comment by peppy** [comment]
I don't think this has been correctly implemented yet; is currently placeholder.

**Comment by Joehuu** [comment]
There have been several changes to https://github.com/ppy/osu/commits/master/osu.Game.Rulesets.Osu/Objects/SliderTailCircle.cs, but right now it gives a SmallTickHit (which doesn't give a hard miss, see https://github.com/ppy/osu/wiki/Scoring#score).

Essentially resolved in https://github.com/ppy/osu/pull/10288 (internally) and https://github.com/ppy/osu/pull/10405 (UI portion).
