### ISSUE TITLE
Sometimes can't reach results screen after completing a map

### ISSUE THREAD

**Issue by object022** [ppy/osu#3037]
![image](https://user-images.githubusercontent.com/9292406/42721922-b6045c4e-8710-11e8-8d09-4781dbda1754.png)

I hope this image is self-explanatory again. What happened is I completed a map, but did not see the usual screen of rating and is softlocked into this situation. I could hit escape and call the menu, but that means I have to forfeit this run(which I completed already).

The map being played is https://osu.ppy.sh/beatmapsets/13223#osu/53555. It's my first time playing a 6 minute map, so I'll probably play some other long maps and see if this is a issue for long map in general.

My spec can be found at issue #3036.

**Comment by Morilli** [comment]
Just got it too. I have a video of half the map, but there really isn't anything interesting to show in there. The map I was playing was 3 minutes, so length it probably not the cause of this issue.

**Comment by cthbleachbit** [comment]
This issue is also reproducible in version `2019.216.0` on mania mode with this [beatmap](https://osu.ppy.sh/beatmapsets/440925#osu/964622).

Hope this can be fixed soon.

**Comment by peppy** [comment]
See #4095, may already be fixed.

**Comment by cthbleachbit** [comment]
Can no longer reproduce in latest git snapshot over around 4 hours of play time.

**Comment by peppy** [comment]
Thanks for reporting back. We're pretty confident this is fixed.
