### ISSUE TITLE
There's no way to add a friend in-game

### ISSUE THREAD

**Issue by peppy** [ppy/osu#30386]
Should be possible from profiles at very least.

![Safari 2024-10-22 at 10 32 25](https://github.com/user-attachments/assets/206b0bdf-65d6-4893-b376-73b9cadb158b)

Super high priority because this is like, one of the core online features.

**Comment by bdach** [comment]
Blocked on https://github.com/ppy/osu-web/issues/10789. cc @ppy/team-web

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
