### ISSUE TITLE
Updating a beatmap jump to the next song

### ISSUE THREAD

**Issue by MeerukYang** [ppy/osu#30384]
### Type

Game behaviour

### Bug description

If click the "update" button when a beatmap needs to update, after finishing downloading the latest map, the menu would select the next song.

https://github.com/user-attachments/assets/250f9c50-c842-4683-bccd-7fe4ccb8aada

In this video attached, updating YUC'e's _Cosmic Air Ride_ jumps to Agressor Bunx's _Tornado_, while the updated _Cosmic Air Ride_ is right above it; it is confusing.

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17470902/compressed-logs.zip)

**Comment by peppy** [comment]
This was some very fragile logic that likely broke with recent refactors. In theory it should be simpler to make this work now (in theory). I'll take a look.
