### ISSUE TITLE
File permission issues in osu!.app

### ISSUE THREAD

**Issue by l2dy** [ppy/osu#3039]
Contents/* and above are 777 (too permissive), main executable (`osu!.app/Contents/MacOS/osu!`) is 744, so I can't run it as another user after installing it to /Applications.

**Comment by peppy** [comment]
Does this happen when double-clicking the zip? Please note that using `unzip` is *not* supported.

**Comment by l2dy** [comment]
Yes, it happens when double-clicking.

**Comment by peppy** [comment]
This has been fixed via https://github.com/ppy/osu-deploy/commit/9654796212d28d89c60242b886e64dc6a89a7041.
