### ISSUE TITLE
User skin sprites display opacity different under Metal

### ISSUE THREAD

**Issue by peppy** [ppy/osu#30399]
This needs investigation. We're potentially still doing premultiplied alpha wrong.

### Discussed in https://github.com/ppy/osu/discussions/30148

<div type='discussions-op-text'>

<sup>Originally posted by **cdwcgt** October  9, 2024</sup>
on iOS(iPadOS) and MacOS:

| on iOS(iPadOS) and MacOS | on Windows |
| -- | -- |
| ![on iOS(iPadOS) and MacOS](https://github.com/user-attachments/assets/e41b524a-7b51-42df-b049-6ba4202bb3c8) | ![on Windows](https://github.com/user-attachments/assets/b0c40cb3-a581-4919-a7e7-f5e4b6a8fdf1) |

The fruit is noticeably darker

| on iOS(iPadOS) and MacOS | on Windows |
| -- | -- |
| ![on iOS(iPadOS) and MacOS](https://github.com/user-attachments/assets/63c27321-da63-44a7-95d9-8ef93d38603d) | ![on Windows](https://github.com/user-attachments/assets/5bf2d972-71ea-4398-a812-884e9030e06c) |

The area around the cursor(and tail) is noticeably darker

std skin: https://files.catbox.moe/01isxd.osk
ctb skin: https://files.catbox.moe/f7172e or https://www.swisstransfer.com/d/d800340d-c3b0-4244-92ca-56a4a3932087</div>

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by smoogipoo** [comment]
The issue says iOS _(and macOS)_, but I can't replicate on macOS. And I'm very well aware that this is an issue on iOS, I've both been told IRL many times how shocking the cursor trail looks and I think there's an o!f issue for that specifically.

But, for macOS, can anyone confirm this to be broken there?

**Comment by peppy** [comment]
Definitely going to be iOS/iPadOS only. Skins look fine here on macOS.

**Comment by Joehuu** [comment]
Same here.

The framework issue is https://github.com/ppy/osu-framework/issues/2194. Not sure what the stance is now on having the same issue in framework and here for visibility. I would close in this case because it's only on iOS.

**Comment by smoogipoo** [comment]
Let's close this one and keep tracking there.
