### ISSUE TITLE
Ability to close playlists within time period after creation

### ISSUE THREAD

**Issue by peppy** [ppy/osu#30401]
It's quite easy to make a mistake and want to recreate a playlist. I've had several requests for manual deletion for cases like this.

### Discussed in https://github.com/ppy/osu/discussions/30393

<div type='discussions-op-text'>

<sup>Originally posted by **Hiviexd** October 23, 2024</sup>
would be a very appreciated UX improvement imo. 

in multiple past cases related to spotlights/loved (most recently in [osu!dev](<https://discord.com/channels/188630481301012481/384640068847009792/1298386123210625165>)), we had to request manual edits/deletions to playlists due to mistakes during the creation process (wrong mods, title typo, wrong deadline). so it would be great if users were allowed to close their playlists within 5 minutes after creation, that'd help with solving any potential mistakes while preserving the long-term integrity of playlist leaderboards.</div>

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by bdach** [comment]
How did you perform the 'deletion' logistically? Did you just set `ends_at` on the room, or did you actually delete rows? I was probably gonna do the former.

**Comment by peppy** [comment]
Just setting `ends_at` is fine I think. We can "actually" delete it if there's reason provided by users to do so.
