### ISSUE TITLE
Off center spinner!!

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#3041]
I might be really silly here, But im SURE the dot in this spinner in the edit section (and maybe even ingame) is off center, And i cant unsee it.
https://i.imgur.com/kHxEEYq.png

**Comment by Hubza** [comment]
https://i.imgur.com/7dRLyCy.png In-game too

**Comment by Morilli** [comment]
It seems to me as if the dot is initally centered but doesn't rotate perfectly in the middle when spun.

**Comment by peppy** [comment]
This is a known issue with the spacing bakes into font glyphs currently.

**Comment by hbnrmx** [comment]
Looks like this has been fixed?

**Comment by HoutarouOreki** [comment]
Yes, not an issue anymore. https://streamable.com/qzwr7
