### ISSUE TITLE
No support for bluetooth devices on iOS

### ISSUE THREAD

**Issue by Tougore** [ppy/osu#30427]
### Type

Game behaviour

### Bug description

After connecting keyboard to my iPhone, game can't register any key presses. 

### Screenshots or videos

https://github.com/user-attachments/assets/6b2e69e5-0c38-46ca-8dc0-97669bfcd2ac

### Version

2024.1009.1-lazer

### Logs

i guess in this case logs don't give anything..

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by frenzibyte** [comment]
Tracking in https://github.com/ppy/osu/issues/23290
