### ISSUE TITLE
Global leaderboard only available for osu!supporter in lazer

### ISSUE THREAD

**Issue by Hrabanor** [ppy/osu#30420]
### Type

Game behaviour

### Bug description

Recently, after update I can't access global leaderboard. It states that global leaderboard is for osu supporters, which is odd becasuse in previous version I did have access to leaderboard.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/dba845e6-080f-4b76-b163-6d16001b70ab)

### Version

Lazer 2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17517965/compressed-logs.zip)

**Comment by Gabixel** [comment]
You enabled the "selected mods" option, which is supporter-only. Let's hope the filter is a bit more noticeable with the future carousel redesign
