### ISSUE TITLE
Start time of some beatmaps are too late

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3043]
logs:
[database.log](https://github.com/ppy/osu/files/2196069/database.log)
[network.log](https://github.com/ppy/osu/files/2196070/network.log)
[performance.log](https://github.com/ppy/osu/files/2196071/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2196072/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2196073/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2196074/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2196075/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2196076/runtime.log)

video:
https://drive.google.com/open?id=1EaXYADAhl28U7-PujJzYJykMuYBMTtZU

maybe it's connected to that this beatmap has shorter time before hitobjects appear (maybe another bug, i don't know, maybe this beatmap is build in that way)

**Comment by ticotaco72** [comment]
update:
it occurs in beatmaps that have shorter time before hitobjects are drawn. that's not problem in only one beatmap
next example:
https://osu.ppy.sh/beatmapsets/629217#osu/1328734

**Comment by ticotaco72** [comment]
update:
it occurs even if you're not clicking

**Comment by ekrctb** [comment]
"Freeze" (animation stops during fade-in) is intentional I think. What is the issue is the first hit object is already visible during fade-in.

**Comment by Morilli** [comment]
This does not seem to be resolved completely. You can still see a circle fading in while the freeze is in place.

**Comment by peppy** [comment]
Which map are you testing with?

**Comment by Morilli** [comment]
https://osu.ppy.sh/beatmapsets/629217#osu/1328734 normal difficulty

**Comment by Morilli** [comment]
Additionally I've noticed this problem on quite a lot of maps now where it didn't occur before.

**Comment by peppy** [comment]
The beatmap you specify works correctly. Are you sure you are on the latest master?

**Comment by Morilli** [comment]
Should be, else I would not see the change done by the PR related to this issue. I will make a video of what I see.

**Comment by Morilli** [comment]
https://streamable.com/uhjoy the beginning of the slider is visible in the beginning.

**Comment by peppy** [comment]
Do you have a universal offset setting?

**Comment by Morilli** [comment]
Global offset is 0ms.

**Comment by ekrctb** [comment]
Now reproducible on various maps not only with low AR ones.

**Comment by peppy** [comment]
I still cannot reproduce on any map, including the above one.

**Comment by ekrctb** [comment]
I'm using Windows.

**Comment by peppy** [comment]
Ah yes, it's definitely UO related. With a UO of zero on windows it is slightly visible.
