### ISSUE TITLE
import fail, because of unathorized access

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3044]
retrying does nothing
logs:
[database.log](https://github.com/ppy/osu/files/2196091/database.log)
[network.log](https://github.com/ppy/osu/files/2196092/network.log)
[performance.log](https://github.com/ppy/osu/files/2196093/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2196094/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2196095/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2196096/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2196097/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2196098/runtime.log)

![osu_2018-07-15_22-35-38](https://user-images.githubusercontent.com/32620809/42738254-f804e908-8880-11e8-8383-ee2a158433af.jpg)
![osu_2018-07-15_22-35-42](https://user-images.githubusercontent.com/32620809/42738255-f8253d48-8880-11e8-86a4-7f255eb4437d.jpg)

**Comment by peppy** [comment]
This looks like a permissions issue. Can you check the file and folder permissions on that beatmap and make sure your local user has permission to access them?

**Comment by ticotaco72** [comment]
all application packages and my user have access to `read and execute` and `read`.
owner of file is other user.
is that making change that beatmap was downloaded by other user?
do osu! need permision to `write`?

**Comment by MLisDreaming** [comment]
Yeah, osu! is 'writing' those files to the folder not 'read' them into place I would think.

**Comment by peppy** [comment]
Closing as stale.
