### ISSUE TITLE
osu!editor will sometimes drop hit sounds when the window is inactive

### ISSUE THREAD

**Issue by BunnyTub** [ppy/osu#30444]
### Type

Game behaviour

### Bug description

I was trying to listen to the beatmap I was making and do some other things in the background, and then suddenly heard some of the hit sounds randomly not playing along, or sometimes being slightly delayed, and I'm not sure why. This happens with other skins I've tried, and other maps besides this one.

### Screenshots or videos

https://github.com/user-attachments/assets/fd0d859d-c137-455b-aa7d-b947141c0a97

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17549594/compressed-logs.zip)

**Comment by BunnyTub** [comment]
I'm not sure if I should make a separate issue, but I've noticed that this also happens during game play.

**Comment by bdach** [comment]
Pretty much the same general thing as https://github.com/ppy/osu/issues/20747
