### ISSUE TITLE
return arrow snaking in sliders

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3045]
when snaking in sliders in short, broken sliders, return arrow should change angle laniently 

video (look at 0:17-0:19):
https://drive.google.com/open?id=19Fo2yqGgePvna4lna9wr2ykZPuPo_TC3

**Comment by peppy** [comment]
Are you saying the rotation should be more smooth, rather than an instant change?

**Comment by ticotaco72** [comment]
Yes
