### ISSUE TITLE
Right-clicking beatmap options activates "Right mouse drag to absolute scroll"

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3046]
I don't know how to explain it better than with a video: https://streamable.com/j3i20
Basically, right clicking an option in this menu will scroll the beatmap selection screen, where I would expect one of the two following behaviours:
1. Do nothing; ignore the right click on that menu.
2. Select the option.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/17962 (temporarily), so closing. Will be properly handled in https://github.com/ppy/osu-framework/pull/5128.
