### ISSUE TITLE
Inconsistent buttons/dropdowns

### ISSUE THREAD

**Issue by shinmorisawa** [ppy/osu#30476]
### Type

Cosmetic

### Bug description

This has been an issue for a long time, but the design just seems "inconsistent".
In the screenshots below, I have opened the add to collections menu. it just seems "inconsistent".

I think it would be more appealing to look at if everything followed the same color scheme.

### Screenshots or videos

![osu_2024-11-02_10-33-40](https://github.com/user-attachments/assets/636fdea2-6055-4c97-a382-3fb0d47eaf51)
![osu_2024-11-02_10-33-45](https://github.com/user-attachments/assets/c89aa9eb-7e0d-4e51-8492-5d766d69fe75)

### Version

<=2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17606554/compressed-logs.zip)

**Comment by bdach** [comment]
Both screens on these screenshots need to be redesigned 2 years ago. I don't see the point of opening this in light of that.

Please don't open issues of this kind. You can do discussions instead if you want to talk design.

**Comment by shinmorisawa** [comment]
oh, ok i see. thanks!
