### ISSUE TITLE
osu!lazer hides itself if I double click the title bar on macOS

### ISSUE THREAD

**Issue by l2dy** [ppy/osu#3047]
1. Open osu! on macOS
2. Double click the title bar
3. Game window is hidden and I can't unhide it.

**Comment by swoolcock** [comment]
Related to https://github.com/ppy/osu-framework/issues/1598 and https://github.com/ppy/opentk/pull/21
OpenTK window state/border state are not propagated back to the app, nor is fullscreen correctly handled.
