### ISSUE TITLE
SV timing points less than 0.1x get reverted to 0.1x after saving a beatmap

### ISSUE THREAD

**Issue by Splat3r-is-not-available** [ppy/osu#30472]
### Type

Game behaviour

### Bug description

when saving and reloading a beatmap all SV timing points less than 0.1x are set to 0.1x

### Screenshots or videos

https://github.com/user-attachments/assets/dac5259c-7c7e-4d0a-9a00-0c17115d81ef

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17605067/compressed-logs.zip)

**Comment by shinmorisawa** [comment]
i have been able to reproduce this.

**Comment by shinmorisawa** [comment]
it also doesn't ask you to save, so this could be an obscure issue.
