### ISSUE TITLE
Toggling "Finish" on drumrolls hides the body of the drumroll

### ISSUE THREAD

**Issue by 12beesinatrenchcoat** [ppy/osu#30480]
### Type

Cosmetic

### Bug description

Was trying out mapping osu!taiko. Toggling "Finish" on a Drumroll would hide the body of the Drumroll until another toggle was toggled, or until the object was well off-screen.

### Screenshots or videos

https://github.com/user-attachments/assets/3a182a39-6311-44ad-8cbc-b9aebf9696ca

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17608422/compressed-logs.zip)

**Comment by shinmorisawa** [comment]
testing this out, but when i exit fullscreen, it also fixes the issue.
