### ISSUE TITLE
Catch does not let final banana shower finish playing

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3049]
When I was playing catch in osu lazer (On mac 2018.713.1 app.zip),
the beatmap always finishes before the last banana shower finishes.

Taking https://osu.ppy.sh/beatmapsets/595580#osu/1260494 (difficulty Hard) as an example,
you see the banana shower starting, but before it reaches to a catchable height,
the beatmap stops, the results screen shows up, and you cannot do anything about the remaining notes.

This also happens when you use the Autoplay mod.

**Comment by ticotaco72** [comment]
isn't it duplicate of #2956 ?

**Comment by plankp** [comment]
It might be, I understood sliders as the small fruit droplets between bigger fruit instead of banana showers (which are spinners)

**Comment by ticotaco72** [comment]
sorry then i has mistaken in title of #2956

**Comment by plankp** [comment]
I will close this issue then?

**Comment by ticotaco72** [comment]
yeah i think it's good idea
