### ISSUE TITLE
Beatmaps star ratings recalculating every launch

### ISSUE THREAD

**Issue by shrublet** [ppy/osu#30494]
### Type

Game behaviour

### Bug description

Game requires the same set of beatmaps to be recalculated every launch, degrading performance until it's done. I believe these maps all previously had local diffs that I've since deleted and were previously labeled local. Let me know anything additional I should attach.

### Version

2024.1009.01

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17613755/compressed-logs.zip)

**Comment by bdach** [comment]
Please attach `client.realm` from game files.

**Comment by bdach** [comment]
I'm not sure how this happened, but this database looks corrupted.

There are several `BeatmapInfo` objects with star rating missing:

![1731066193](https://github.com/user-attachments/assets/d6119b10-5c3c-4eb3-a136-eef5bf64852a)

These would presumably be some sort of practice difficulties, I guess. The rows with null beatmap set are weird but ultimately not that interesting; what is more worrying is the rows where the beatmap set is present. Examining any one of them by going back to the beatmap set, and then examining the set of backlinks from beatmaps yields this:

![1731066255](https://github.com/user-attachments/assets/704a345b-11d7-44f3-95f0-9019de05d576)

Or, in other words, *the beatmap set object is reachable from the beatmap objects, but the beatmap objects are not reachable from the beatmap set object*. That's not how foreign key relationships are supposed to ever work. Not sure what the remediation steps are.

@shrublet You can try replacing your `client.realm` with https://drive.google.com/file/d/1ahYwQ2KPb75Z118hNFLWNj55I92zgzkG/view?usp=drive_link to fix this (probably back up your existing one before, to make sure I haven't screwed up anything too bad when manually fixing). You might lose some difficulties though.

**Comment by bdach** [comment]
I'll just tentatively close this as a one-off and hope I never see anything like this again...
