### ISSUE TITLE
choosing beatmap with lef/right arrows is broken

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3051]
when you rewind beatmaps with left/right arrow in beatmap solection menu, it sometimes freezes and goes to up of list instead one up/ one down

logs:
[database.log](https://github.com/ppy/osu/files/2199136/database.log)
[network.log](https://github.com/ppy/osu/files/2199137/network.log)
[performance.log](https://github.com/ppy/osu/files/2199138/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2199139/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2199140/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2199141/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2199142/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2199143/runtime.log)

video:
https://drive.google.com/open?id=18Lby7tLooPEGnz-KW5R0oVOXg_OXs7Zw

**Comment by Morilli** [comment]
Could reproduce. I imagine the lag caused by the scrolling to be connected to this issue.

**Comment by ticotaco72** [comment]
i have noticed that when you rewind with left arrow (to up) then after freeze you go to down of list
and similarly with right arrow
