### ISSUE TITLE
There is no option to stop the music from replaying over and over on the Homepage 

### ISSUE THREAD

**Issue by linda072** [ppy/osu#30517]
### Type

Other

### Bug description

This issue is more of an improvement. I find it very annoying for the same music to play on repeat. There is no way for me to pause the music unless I turn off my volume on my device.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/2a71439d-3acf-4ce6-a49c-eeb4ad529ea3)

### Version

1.3.3.7

### Logs

No log file found

**Comment by bdach** [comment]
This repository is for issues on the lazer client, and the screenshot you've attached is from stable. Stable is feature locked and isn't really accepting feature requests. 

In lazer you can press ctrl-f4 to mute the music.
