### ISSUE TITLE
[stable] Local leaderboards may show global highscore during play

### ISSUE THREAD

**Issue by Y2nn1c** [ppy/osu#30533]
### Type

Game behaviour

### Bug description

While playing a map and having the leaderboard set to local leaderboard, the leaderboard may additionally display the top play a second time, but the card for that play is in red and under the local top play. I think that the red play is the gloabl top play since your play is highlighted in red if you play with global leaderboards on.
However, this does not seem to have anything to do with whether or not a play is in the top 1000 and therefore saved serverside, as I had the same issue with a play which was back then only at rank 1807, which I mentioned [in Discord](https://discord.com/channels/188630481301012481/1097318920991559880/1301967842475905115) first. However, I just checked and the play has fallen to rank 1809, however this issue appears to have vanished from that play for some reason. Another thing is, that this has happened to me for a very long time now, if not always, which was during a time where I was way to bad to get a play into the top 1000. This issue is also very rare and it doesn't matter if a score is new or old.
Also yes, in stable the play is at rank 1809 and on the web its at 1812.
### Screenshots or videos

![screenshot187](https://github.com/user-attachments/assets/295af8fd-e4ec-4d28-93d7-be9a2666e02e)
![screenshot188](https://github.com/user-attachments/assets/802f5e15-0ec4-420c-9388-e7a4b664219c)
![grafik](https://github.com/user-attachments/assets/afda8f68-4a81-4b67-accb-2976960bfb99)

### Version

b20241030

### Logs

[1730970938.nauth.log](https://github.com/user-attachments/files/17659360/1730970938.nauth.log)

**Comment by bdach** [comment]
https://github.com/ppy/osu-stable-issues
