### ISSUE TITLE
Failed to set Nvidia threaded optimizations

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#30546]
### Type

Game behaviour

### Bug description

Lazer has been failing to set threaded optimizations for some time on my machine, regardless of the current option of the setting, though i remember it working when it was added.
I reinstalled windows before making this post (for reasons unrelated to osu), installed the official nvidia driver, but the issue persists.

### Version

2024.1009.1

### Logs

[1731054362.network.log](https://github.com/user-attachments/files/17675593/1731054362.network.log)
[1731054362.performance.log](https://github.com/user-attachments/files/17675594/1731054362.performance.log)
[1731054362.runtime.log](https://github.com/user-attachments/files/17675595/1731054362.runtime.log)
[1731054362.auth.log](https://github.com/user-attachments/files/17675596/1731054362.auth.log)
[1731054362.input.log](https://github.com/user-attachments/files/17675597/1731054362.input.log)
[1731054362.nauth.log](https://github.com/user-attachments/files/17675598/1731054362.nauth.log)

**Comment by bdach** [comment]
Extra logging shows

```
[runtime] 2024-11-08 09:28:08 [verbose]: [NVAPI] GetProfileInfo call failed with status code INCOMPATIBLE_STRUCT_VERSION
```

but I don't see why that would be the case. The only struct involved is [this one](https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/struct__NVDRS__PROFILE__V1.html) and things look to check out to me. I wanted to try [gpuview](https://nvidia.custhelp.com/app/answers/detail/a_id/3507/) again but that tooling is apparently cobbled together using dreams and duct tape and I can't get it to work again.

@smoogipoo you're the most likely the one that will know most / best person to ask; is there some secret pathway to nvidia people that we could use to debug this or something?

**Comment by smoogipoo** [comment]
Unfortunately I have nothing to help with here, can't see anything wrong in the code.

**Comment by Joehuu** [comment]
After bisecting, https://github.com/ppy/osu/commit/dda691b8c219f104a938d5a8c0bc29a88acfc19e seems to be the culprit.

**Comment by bdach** [comment]
I'm dumbfounded that bisecting died anything here, and that apparently it's that commit (haven't checked myself yet). For all intents and purposes, I'd expect that size spec to be correct as per https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/struct__NVDRS__GPU__SUPPORT.html...?

**Comment by smoogipoo** [comment]
Nah, it's incorrect. Those are actually 1-bit fields 🙃
