### ISSUE TITLE
argon progress bar shows timestamp when hovering even when im playing

### ISSUE THREAD

**Issue by MinecraftPEayer** [ppy/osu#30548]
### Type

Game behaviour

### Bug description

i think the timestamp should not shows while playing

### Screenshots or videos

https://github.com/user-attachments/assets/51d3c8f7-3649-4a42-91ac-9dbc31ee5540

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17678041/compressed-logs.zip)

**Comment by MinecraftPEayer** [comment]
Occurs at 00:01 close to 00:02

**Comment by bdach** [comment]
Already fixed for next release
