### ISSUE TITLE
Inconsistency in Classic mod replay

### ISSUE THREAD

**Issue by minhperry** [ppy/osu#30556]
### Type

Game behaviour

### Bug description

For this score: https://osu.ppy.sh/scores/3752556524

The one buzz slider at around combo 881 if viewed normally will result in a sliderbreak (which is obviously a desync with the real score). However if i skip forward or backward with arrow keys, or ingame buttons, it sometimes still play it as normal.

### Screenshots or videos

https://youtu.be/jIa4dpLG8Ew

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17684646/compressed-logs.zip)

**Comment by ssz7-ch2** [comment]
Same issue as https://github.com/ppy/osu/issues/27704#issuecomment-2016851626 but for SliderRepeat

There's a SliderRepeat at `117111.20930232557` and replay frame at `117111`
In stable, the SliderRepeat is truncated to `117111` so it counts as a hit.

In lazer, update does not check SliderRepeat until `117111.20930232557`. But the cursor leaves the follow area at around 
`~117111.6`
This means that in order for the SliderRepeat to count as a hit, update must check between `117111.20930232557` and `~117111.6`

**Comment by minhperry** [comment]
> Same issue as https://github.com/ppy/osu/issues/27704#issuecomment-2016851626 but for SliderRepeat
> 
> There's a SliderRepeat at `117111.20930232557` and replay frame at `117111`
> In stable, the SliderRepeat is truncated to `117111` so it counts as a hit.
> 
> In lazer, update does not check SliderRepeat until `117111.20930232557`. But the cursor leaves the follow area at around 
> `~117111.6`
> This means that in order for the SliderRepeat to count as a hit, update must check between `117111.20930232557` and `~117111.6`
> 

But what would cause the inconsistency though?

**Comment by ssz7-ch2** [comment]
> So the inconsistency was caused by me skipping right within that timeframe?

Yes

**Comment by frenzibyte** [comment]
Let's track this in https://github.com/ppy/osu/issues/21659
