### ISSUE TITLE
The "Edit externally" button in the editor is in English regardless of the selected language.

### ISSUE THREAD

**Issue by MrCatGitHub** [ppy/osu#30567]
### Type

Cosmetic

### Bug description

In the editor, the "Edit externally" button is in English rather than the language osu! is set to.

### Screenshots or videos

![german](https://github.com/user-attachments/assets/31423811-3d8c-4b63-8ec8-a90f3bdf8779)
![japanese](https://github.com/user-attachments/assets/b606c443-8781-4128-a7f0-5a3ca4688381)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17688585/compressed-logs.zip)

**Comment by Joehuu** [comment]
There are many other strings hardcoded/unlocalisable, like the right side of editor, and that it's not strictly enforced for new strings, so closing for those reasons.

If you want, you can follow https://github.com/ppy/osu/wiki/Localising-the-client#localising-hardcoded-strings and make a pull request for the specified string you mentioned and possibly more that you can find.
