### ISSUE TITLE
iPad physical keyboard can't type on osu

### ISSUE THREAD

**Issue by Star-Clara** [ppy/osu#30564]
### Type

Performance

### Bug description

The iPad’s keyboard software works great on osu!, but typing with an external keyboard is a real pain. I can use the “z” or “x” keys or other shortcut keys to play and use game shortcuts, but I can’t type in the input box.
***
* i’m using…
iPad air 5 th generation (iPadOS 18.2 developer beta2)
SmartDevil Keyboard

### Screenshots or videos

https://github.com/user-attachments/assets/a67d8e13-17ff-43ed-9053-d7c1695aae8a

* 00:10 * I cant type when my physical keyboard is turned on
* 00:20 * I turned off my physical keyboard,i can type in the input box now 

### Version

2024.1009.1

### Logs

[logs.zip](https://github.com/user-attachments/files/17687361/logs.zip)

**Comment by bdach** [comment]
#23290
