### ISSUE TITLE
Launching game offline drops you from game account

### ISSUE THREAD

**Issue by rust2** [ppy/osu#30582]
### Type

Game behaviour

### Description

As the title says, if you launch osu!lazer with no access to the internet, you absolutely must log in again next time. Is the password gets dropped on connection fail? And is this fixable?

### Version

2024.1009.1-lazer

### Logs

N/A

**Comment by peppy** [comment]
Please include logs. Logs are not N/A.

**Comment by rust2** [comment]
I'm sorry. It seems this was false alarm. When I opened the issue the behavior was: I open osu without internet, it asks me to enter password. The end. And now it asks the password but almost immediately changes to "no connection" popup and it connects after restarting with internet.

**Comment by peppy** [comment]
Can you include a video showing it ask for the password briefly? This sounds weird.

**Comment by rust2** [comment]
https://youtu.be/e7YAx3YzQFQ
I remember how it was kicking me from account completely before. But it changed somehow...

**Comment by Joehuu** [comment]
Seems like the vpn is causing that problem.

**Comment by rust2** [comment]
> Seems like the vpn is causing that problem.

I'm not sure because with vpn ON and internet OFF it either says "no connection" from start of after some delay. Anyway it's a mistake from my side

https://github.com/user-attachments/assets/4e56e29a-1a7d-4042-85cb-dc1dde9319ec
