### ISSUE TITLE
Beatmap with duplicated difficulties

### ISSUE THREAD

**Issue by 7molP** [ppy/osu#3059]
I happened to have some beatmaps include a copy of itself in its folder
(I probably import these beatmaps twice, I remember there is a time if you import a beatmap multiple times osu! will act like this)
Stable seems to ignore duplicated difficulties, but lazer did not

***Beatmap folder like this↓***
![image](https://user-images.githubusercontent.com/16501720/42824276-16f21038-8a12-11e8-89e8-5c44df17b8fc.png)

***Stable↓***
![screenshot158](https://user-images.githubusercontent.com/16501720/42825533-cc01a6ee-8a14-11e8-926d-02d473a31925.png)

***lazer↓***
![osu_2018-07-17_21-59-32](https://user-images.githubusercontent.com/16501720/42824154-d20154b6-8a11-11e8-8133-82acd5b22382.png)

**Comment by peppy** [comment]
This is intentional. Please delete the beatmaps you don't want.
