### ISSUE TITLE
Using ESC before the result screen is shown exits the map

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3060]
After a beatmap has finished, but before the results screen is shown, there is usually a short time window before the result screen actually shows up. For some maps, be it cause of shoryboards or something else, this time window is pretty long. In stable, it is possible to immediately jump to the result screen by pressing ESC, which I like to do for the reasons described above. However in lazer the map is quit and returns you back to the song select screen, completely skipping the results screen, which it shouldn't do in my opinion.

**Comment by cyanidee** [comment]
If you succeed to do this, osu! also won't save the score.

**Comment by Morilli** [comment]
I believe scores are not implemented yet, so they aren't saved anyway.

**Comment by cuskig** [comment]
Still occurs for me.

**Comment by bdach** [comment]
@cuskig please read https://github.com/ppy/osu/issues/13644#issuecomment-867280514 - direction has changed since this issue was originally opened.
