### ISSUE TITLE
Kiai time offset can sometimes appear to be off by 1ms on compatibility-exported lazer beatmaps

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#30606]
### Discussed in https://github.com/ppy/osu/discussions/30595

<div type='discussions-op-text'>

<sup>Originally posted by **felipemarins** November 13, 2024</sup>
As the title says, sometimes, when you export a lazer beatmap to .osz, the kiai time may be off by 1ms. I suppose this is due to timing point's precision that is not supported by stable.

Here are some beatmap files where it occurs (one is the .osz, and the other is a .olz for comparison):
[beatmaps-for-testing.zip](https://github.com/user-attachments/files/17727361/beatmaps-for-testing.zip)

Edit: It seems that it happens to hit objects too (but it doesn't trigger AiMod in this case).</div>

---

The problem seems to be that we are truncating the offset of the uninherited timing point without taking into account that it changes the snapping for all objects that come after it. This isn't fixed by rounding instead of truncating.

We'll need to offset all the objects in the timing section by the offset due to truncating the uninherited timing point, and then truncate the objects themselves. For example if the uninherited point is at 1000.4 ms and an object is at 2000.2 ms, we need to first move the object back 0.4 ms to 1999.8 ms and then truncate it to 1999 ms.

_Originally posted by @OliBomby in https://github.com/ppy/osu/discussions/30595#discussioncomment-11238775_

**Comment by bdach** [comment]
And this just as compatibility export was going to see way more use due to work on BSS...

@OliBomby is this solution something you're going to be looking at, or do I need to make a detour for this? It doesn't *sound* like a major problem in principle or something that would need to be fixed quickly, am I wrong?

**Comment by OliBomby** [comment]
> And this just as compatibility export was going to see way more use due to work on BSS...
> 
> @OliBomby is this solution something you're going to be looking at, or do I need to make a detour for this? It doesn't _sound_ like a major problem in principle or something that would need to be fixed quickly, am I wrong?

Its a pretty minor problem for the beatmap as I don't think it affects gameplay at all, but I think this problem will be present for most maps made in lazer and exported to osz. We would see a lot of maps uploaded with this small imperfection.

I'll look into making a fix today, so you don't have to detour.
