### ISSUE TITLE
Song select doesn't update when changing rulesets while loading

### ISSUE THREAD

**Issue by yellowbadbeast1** [ppy/osu#30610]
### Type

Game behaviour

### Bug description

https://github.com/user-attachments/assets/370d6820-d4ce-4040-9549-22f3d10e7987

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17738078/compressed-logs.zip)

**Comment by bdach** [comment]
I think there's a high chance this is fixed by https://github.com/ppy/osu/pull/30425, so I wouldn't touch this issue until the next release is out sometime this week and re-check with OP whether it's fixed.

**Comment by Joehuu** [comment]
On a 200+MB database without files that it somewhat fixes. It does show the last ruleset beatmaps for a split second though, and spamming enter during that time can still break like 25% of the time (i.e. osu! ruleset with osu!mania beatmap in this video below). First attempt wasn't spamming enter to showcase the split second update, while the other attempts were spamming enter right after switching rulesets.

https://github.com/user-attachments/assets/f31622f9-dbb2-427d-89da-f979b8866bb9

**Comment by bdach** [comment]
How are you testing this?

**Comment by Joehuu** [comment]
This is on latest master. Not sure how to clarify further/better than what I had last comment and a video, but you need a 200+MB database with at least one beatmap with the files. I'd recommend https://osu.ppy.sh/beatmapsets/241526#osu/557821. In the video:
1. Enter song select with ruleset set to mania.
2. While carousel is loading, change ruleset to osu.
3. Immediately spam enter. The broken state happens ~25% of the time.
	- If it doesn't happen, switch back to mania and repeat.

**Comment by bdach** [comment]
Where are you getting the database from?

**Comment by Joehuu** [comment]
It's my own database copied to `osu-development`. I thought you already have large database files. Let me know if you need mine if you can't reproduce.

**Comment by yellowbadbeast1** [comment]
seems fixed

**Comment by Joehuu** [comment]
Have made another issue for the edge case.
