### ISSUE TITLE
Map drops to 150 fps

### ISSUE THREAD

**Issue by SandwichPlays** [ppy/osu#30630]
### Type

Performance

### Bug description

Idk when I play a map it's 360 fps at first then drops to 150 at seemingly random? Didnt happen before only since yesterday

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17767613/compressed-logs.zip)

**Comment by smoogipoo** [comment]
- Press Ctrl+F11 twice to show the frame time graphs and capture a video of what you're seeing.
- What skin are you using? Have you tried with the default skin?
- Does it happen on every beatmap?
- Have you checked for any processes running in the background? Have you tried closing all programs (discord, web browsers, and anything to do with "overlays" like [tosu](https://github.com/tosuapp/tosu))?
- Checked your CPU temperatures?
- Does it happen even when there are no hitobjects on the screen, or does it happen in places where there's a lot on the screen?
- Does it happen while being logged out?

Just a few things you can try... Can't do much with this issue as is.

**Comment by SandwichPlays** [comment]
Update: I usually play with screen scaling, and when I change to no scaling it happened, dropped to 150 then to 75 (which is my native fps) when there are more objects, when I switched back it's fine again. I have a i5 10400F and a GTX 1650 so I dont think it's my pc

**Comment by SandwichPlays** [comment]
Ok wtf this is weird, when I opened OBS it worked fine again? And when I close it it started to have problems, also some maps drop to 150, and some to 75

**Comment by SandwichPlays** [comment]
yknow what imma close this i think i fixed it somehow
