### ISSUE TITLE
Tapping fast retry doesn't retry

### ISSUE THREAD

**Issue by the-wildguy** [ppy/osu#30640]
### Type

Game behaviour

### Bug description

When pressing the fast retry key without holding for long enough the screen fades to black before going back to normal.

It should retry even if you just tap the keys

### Version

2024.1115.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17774046/compressed-logs.zip)

**Comment by Ladwick** [comment]
Go to settings and set the hold to confirm option to 0ms, I think that should fix it.

**Comment by the-wildguy** [comment]
I think this is more similar to the pause button change they made to make that instant

I think fast retry should be fast by default

**Comment by peppy** [comment]
Change the setting please.
