### ISSUE TITLE
Velopack crashed on update

### ISSUE THREAD

**Issue by necocat0918** [ppy/osu#30645]
### Type

Other

### Bug description

I was in the last version of lazer, and once the update is downloaded, velopack showed a window about lazer is being updated, but velopack crashed because it can't find some components

### Screenshots or videos

the "current" folder is gone
![image](https://github.com/user-attachments/assets/394d5aa7-a444-470f-94e6-14bfe0d39335)

### Version

2024.1009.1 ~ 2024.1115.1

### Logs

[Velopack.log](https://github.com/user-attachments/files/17775499/Velopack.log)

**Comment by smoogipoo** [comment]
> but velopack crashed because it can't find some components

What happened more exactly? Did you get a standard Windows crash log? If so, maybe try checking for any errors in the event viewer (https://docs.microsoft.com/en-us/host-integration-server/core/how-to-check-the-windows-event-logs-for-errors1).

There's these ominous lines in the log:
```
[update:14164] [20:29:11] [WARN] Failed to locate app manifest (This application is missing a package manifest (.nuspec) or it could not be parsed.), trying legacy package resolution...
[update:14164] [20:29:11] [INFO] Attempting to auto-detect package in: C:\Users\necos\AppData\Local\osulazer\packages
[update:14164] [20:29:13] [INFO] Found 2024.1115.1: 'C:\Users\necos\AppData\Local\osulazer\packages\osulazer-2024.1115.1-full.nupkg'
[update:14164] [20:29:13] [INFO] Found full package to read: C:\Users\necos\AppData\Local\osulazer\packages\osulazer-2024.1115.1-full.nupkg
[update:14164] [20:29:13] [ERROR] Start error: Unable to find executable to start: '"C:\\Users\\necos\\AppData\\Local\\osulazer\\current\\osu!.exe"'
```
But apart from that last one I'm not sure if they're relevant. We're definitely packing a nuspec (well... Velopack does that itself):
<img width="519" alt="image" src="https://github.com/user-attachments/assets/c858f616-90fa-4afb-8155-ffced70aa6d1">

Can you start the game fine a second time?

Maybe cc @caesay

**Comment by necocat0918** [comment]
> There's these ominous lines in the log

the package file does exist, the current folder is gone so the app won't run 

> Can you start the game fine a second time?

no, neither the updater nor the osu!.exe in the root folder will run

**Comment by caesay** [comment]
Update.exe process appears to have crashed during the update.

The last log printed was "Backing up current dir to C:\Users\necos\AppData\Local\osulazer\packages\VelopackTemp\tmp_7zRRNYZ8Kx06lNHE" - and then nothing.

**Comment by smoogipoo** [comment]
@necocat0918 please check if there's an error in event viewer.

**Comment by necocat0918** [comment]
> @necocat0918 please check if there's an error in event viewer.

[event logs.zip](https://github.com/user-attachments/files/17784549/event.logs.zip)
it seems like nothing related is inside the log

**Comment by smoogipoo** [comment]
Likely because Velopack was updated, actually. Closing since it seems it's now resolved.
