### ISSUE TITLE
Sometimes stuck on map loading screen when beatmap have complex storyboard

### ISSUE THREAD

**Issue by KevZhi** [ppy/osu#3064]
![2018-07-18 12 07 17](https://user-images.githubusercontent.com/32162677/42859540-2debcd82-8a86-11e8-8620-5acf80975b84.png)

if I turn off the storyboard, the map will be able to start or it will stuck on loading screen
[database.log](https://github.com/ppy/osu/files/2204431/database.log)
[network.log](https://github.com/ppy/osu/files/2204432/network.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2204433/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2204434/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2204435/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2204436/performance-gamethread.update.log)
[performance.log](https://github.com/ppy/osu/files/2204437/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2204438/runtime.log)

**Comment by peppy** [comment]
Have you tried leaving your mouse cursor in the middle of the screen? Currently if you're hovering the visual settings the map will never start.

**Comment by KevZhi** [comment]
Yeah for sure I’ve tried or I won’t post that issue, i keep it Center for a minute. I think it’s some compatibility over complex storyboard or something. If I turn off storyboard it can goes in. Or I met a single try when storyboard opens that goes in successfully but without storyboard displayed.

支天 | Kevin Zhi

________________________________
收件人: Dean Herbert <notifications@github.com>
发送时间: 星期三, 七月 18, 2018 13:04
收件人: ppy/osu
抄送: Kevin Zhi; Author
主题: Re: [ppy/osu] Sometimes stuck on map loading screen when beatmap have complex storyboard (#3064)


Have you tried leaving your mouse cursor in the middle of the screen? Currently if you're hovering the visual settings the map will never start.

―

**Comment by peppy** [comment]
Okay, good to know. Beatmap in question: https://osu.ppy.sh/beatmapsets/407186#mania/884696

**Comment by KevZhi** [comment]
Yeah and that storyboard works fine on osu!wine on my Mac and unfortunately osu!wine does not work anymore on macOS mojave developer beta 4 released yesterday

支天 | Kevin Zhi

________________________________
收件人: Dean Herbert <notifications@github.com>
发送时间: 星期三, 七月 18, 2018 13:10
收件人: ppy/osu
抄送: Kevin Zhi; Author
主题: Re: [ppy/osu] Sometimes stuck on map loading screen when beatmap have complex storyboard (#3064)


Okay, good to know. Beatmap in question: https://osu.ppy.sh/beatmapsets/407186#mania/884696

―

**Comment by bdach** [comment]
Seeing that #4976 is open as well I'm going to close this stale issue as a duplicate.
