### ISSUE TITLE
Borderless Windowed Screen Mode option is now dead on MacOS after 15 November 2024 Update

### ISSUE THREAD

**Issue by hueykohwf** [ppy/osu#30643]
### Type

Game behaviour

### Bug description

After opening Osu Lazer after updating and closing today, the resolution would not go back to Windowed Borderless. It'll only allow me to set "Windowed" or "Fullscreen", even after hitting the reset button. 

Osu game itself says they "recommend windowed borderless" but it's dead after the update.

The Fullscreen viewing mode feels buggy for some reason.

### Screenshots or videos

<img width="1478" alt="Screenshot 2024-11-15 at 7 56 25 PM" src="https://github.com/user-attachments/assets/e69acf4b-7d26-4a71-bc39-c900f9585c25">

### Version

2024.1115.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17775049/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/28222 / https://github.com/ppy/osu/pull/30636
