### ISSUE TITLE
Replay is not saved when quick retrying at the end of a beatmap

### ISSUE THREAD

**Issue by Easowon** [ppy/osu#30642]
### Type

Game behaviour

### Bug description

When pressing "quick retry" after the final note of the beatmap (and before the scorecard appears), a replay is not saved locally even though the score has been submitted.

### Screenshots or videos

https://github.com/user-attachments/assets/ad429e5b-b441-40c8-9a92-c5fcfa89efc3

![osu_lazer](https://github.com/user-attachments/assets/aab264d8-8462-4dc3-b2d7-76305b9f1603)

### Version

2024.1115.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17774368/compressed-logs.zip)

**Comment by bdach** [comment]
I would... not have suspected any of the retry changes to break this as they only touched `PlayerLoader`. This needs to be investigated all the same though.

**Comment by frenzibyte** [comment]
This actually regressed with https://github.com/ppy/osu/pull/30623, as it made the quick restart path no longer call `PerformExit` in `Restart`, which prevented the score from being imported.
