### ISSUE TITLE
Songs not progressing through collection like in Stable.

### ISSUE THREAD

**Issue by verysmallgiant** [ppy/osu#30651]
### Type

Game behaviour

### Bug description

How did you find the bug?
attempting to listen to music

### Screenshots or videos

Lazer

https://github.com/user-attachments/assets/65992484-16ce-4995-be47-43a6f5d340af

Stable

https://github.com/user-attachments/assets/48d482d0-e6e6-45c0-9ae4-72cb3c823d9b

### Version

Lazer 2024.1115.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17776021/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/pull/30343
