### ISSUE TITLE
Extremely quick flashing red when restart on fail is enabled

### ISSUE THREAD

**Issue by Tohkie** [ppy/osu#30657]
### Type

Game behaviour

### Bug description

Turning on the "Restart on fail" option quickly flashes red, possibly only for a few frames and is very distracting. Tested with Accuracy Challenge, Perfect, and Sudden Death mods. Occurs a majority of the time. In the video file attached it occurred all three retries recorded but the frame rate isnt high enough to catch the blink on the 1st retry - it can be visibly seen still in the 2nd and 3rd auto retries though.

### Screenshots or videos

https://github.com/user-attachments/assets/303cdbd7-45d1-4da9-8c7c-ac812cfc6685

### Version

2024.1115.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17778204/compressed-logs.zip)

**Comment by Inconsist** [comment]
If it helps in any way, I have a higher speed recording of this because screen capture didnt get it.

https://github.com/user-attachments/assets/a771b503-0362-48ec-be54-f97838b50d49
