### ISSUE TITLE
Changing a song to a previous track doesnt stay the same after getting into song select

### ISSUE THREAD

**Issue by SAMUELLL41** [ppy/osu#30653]
### Type

Cosmetic

### Bug description

When you are in menu and you change the music with f5 (next track), the song matches after you go to the song select. That doesnt happen with song that are changed through F1 (previous track).

### Screenshots or videos

https://github.com/user-attachments/assets/307d1e5a-a7ce-4e63-87a5-619f2c30eccb

### Version

2024.1115.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17776712/compressed-logs.zip)

**Comment by bdach** [comment]
That's not what is happening there, what's happening there is that you have songs selected in main menu which are not valid for the current ruleset (as indicated by the top toolbar), and you have converts disabled in song select filters. Therefore if you enter song select when a beatmap set's audio is playing and the beatmap set doesn't have a playable non-converted difficulty, the song changes.

**Comment by SAMUELLL41** [comment]
My apologies, I forgot about the setting because i dont use it very often. Also I got confused with the changing not happening when hitting next track.
