### ISSUE TITLE
osu mania slider ends excessively stretched

### ISSUE THREAD

**Issue by mktwos** [ppy/osu#30650]
### Type

Game behaviour

### Bug description

This seems to happen on most mania skins I have, I've compared stable and lazer and noticed there is quite noticeable stretching on the slider ends.
I can't figure out how to send my skin here, but it seems to happen with skins that have slider textures with absurd resolutions, such as 12x20000

### Screenshots or videos

# stable
![Screenshot 2024-11-15 214244](https://github.com/user-attachments/assets/02a4cd85-8ece-4ee4-8bd1-8c60659114fa)
# lazer
![Screenshot 2024-11-15 214215](https://github.com/user-attachments/assets/e644aca1-877b-4217-af87-2a06a1001f9b)

### Version

2024.1115.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17776391/compressed-logs.zip)

**Comment by longnguyen2004** [comment]
"Percy" skin support is best effort and will not match stable exactly

**Comment by smoogipoo** [comment]
As above, and see https://github.com/ppy/osu/discussions/20576 for more discussions on the topic.
