### ISSUE TITLE
Adjusting any mod in multiplayer gives you 0 score and breaks spectate mode for the whole lobby

### ISSUE THREAD

**Issue by diediediebitch** [ppy/osu#30662]
### Type

Game behaviour

### Bug description

Playing with any adjusted mod will give you 0 score while you're playing the map, and then it fixes itself on the results screen. So while the match is happening it shows you on the bottom of the leaderboard with 0 score, but after the match ends it fixes itself. Also breaks if its forcemod

this also breaks spectate mode if anyone in the lobby is playing with an adjusted mods

It only happens when u adjust the mods, so like hidden alone wont do anything, but hidden set to only approach circles will break the lobby. This also happens with random even without any adjustments, im assuming from the random seed or something. Also changing anything with difficulty adjust will have the same effect

edit: this also breaks DT adjust, so putting a map with adjusted dt will just break the scoring for everyone. please fix soon :)

### Version

2024.1115.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17779282/compressed-logs.zip)

**Comment by diediediebitch** [comment]
ok spectate mode doesn't actually break, but it takes like 30 seconds for it to start working and it doesn't show the players who use a adjusted mod.

**Comment by peppy** [comment]
I believe this may be due to a missing server-spectator deploy. We're attempting to fix this now.

**Comment by smoogipoo** [comment]
Fixed with new multiplayer server.
