### ISSUE TITLE
Scores imported from stable can not have replays downloaded

### ISSUE THREAD

**Issue by theredpro-sj** [ppy/osu#30676]
### Type

Game behaviour

### Bug description

This specifically pertains to scores that are 1. Not in the top 50 of a beatmap ranking and 2. Scores you set. You can not download the replay from lazer no matter how much you try. It would make sense to be able to do this for scores you set for analysis, local leader boards and likely many other things I am not thinking of

### Screenshots or videos

<img width="1470" alt="Screenshot 2024-11-15 at 7 59 44 PM" src="https://github.com/user-attachments/assets/e7885372-de4b-4d6e-a198-b621ea4a0db8">
<img width="1470" alt="Screenshot 2024-11-15 at 8 00 02 PM" src="https://github.com/user-attachments/assets/66671b1b-38aa-4aa9-b604-370bb26ee620">
<img width="1470" alt="Screenshot 2024-11-15 at 7 59 58 PM" src="https://github.com/user-attachments/assets/457f320f-99ef-4968-8de9-ba3bf955f917">
<img width="1470" alt="Screenshot 2024-11-15 at 7 59 48 PM" src="https://github.com/user-attachments/assets/6851c870-0c3a-4329-bdf0-3c54a036ec63">

### Version

2024.1115.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17782808/compressed-logs.zip)

**Comment by Joehuu** [comment]
Did you mean scores *played* from stable?

Only the top 1000 *stable* scores provide replays, see https://osu.ppy.sh/wiki/en/Beatmap#leaderboards. The only way you can get that score's replay is if you still have the replay locally on stable and import it to lazer.

**Comment by theredpro-sj** [comment]
I did mean score played from stable. In that case this is not an issue as you mentioned only the top 1000 stable scores have replays.
