### ISSUE TITLE
Game crashes when sending message in online channel.

### ISSUE THREAD

**Issue by cyanidee** [ppy/osu#3068]
No idea why it happens. It might be related to state of my account though, because my account is restricted and I can't send messages, but person who isn't restricted can do that. I am going to debug it now and let you know what's the issue of the crash.

**Comment by peppy** [comment]
Definitely related to user being restricted

**Comment by turbedi** [comment]
Seems to be a duplicate of issue #3134, which has already been closed, so I assume this issue can be closed as well.
