### ISSUE TITLE
Issues with right click and left click bound each bound to 2 keys

### ISSUE THREAD

**Issue by ulumunderscored** [ppy/osu#30693]
### Type

Input Bug

### Bug description

There's an issue where if you have left click bound to for example "x" and "c", and you press on for example "c", the "x" cant be pressed anymore because i have already pressed on c. This is an issue because if i want to play on four keys at the same time I can't because of this bug being super annoying. If you could make it so that there's four inputs that are seperate from each other that would hopefully solve the issue. (btw if you do put 5 inputs that would be nicer because maybe new meta with thumb?)

### Screenshots or videos

https://youtu.be/n1NxGixcahQ?si=PTLxD0pZxqiqDiUz
here's a youtube video about it. you might want to pause, to understand the text.

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17786902/compressed-logs.zip)

**Comment by bdach** [comment]
That's not a bug. You're not supposed to be able to press more than two keys at a time. This is explicitly intended.

**Comment by ulumunderscored** [comment]
can you make it a feature or something? or is it not allowed? because I really want to play with 4 or 5 fingers but I can't. maybe there's a software but with osu it's easier. I mean ADOFIA has multiple keys press with. I don't know it's up to you.

**Comment by frenzibyte** [comment]
It is not allowed, no. This goes against the core mechanics of the game.

**Comment by ulumunderscored** [comment]
wait isn't uwu pad 3 keys? So I think people use 3 keys? no?
