### ISSUE TITLE
Multiplayer matches quitting immediately after pressing esc

### ISSUE THREAD

**Issue by yomikomanda** [ppy/osu#30697]
### Type

Game behaviour

### Bug description

The new update introduced hold to activation doesnt affect game pause. But now it quits multiplayer matches immediately too. I have my pen button mapped to press esc, and when I accidentally press it in a multiplayer match is quits me out. So I'm reporting this cuz I don't think that was intentional.

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17787521/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Marking p:0 purely because it is a regression and a bit of a bad one.
