### ISSUE TITLE
Pressing scale keybinds also types in chat

### ISSUE THREAD

**Issue by yellowbadbeast1** [ppy/osu#30703]
### Type

Game behaviour

### Bug description

I am holding ctrl in the video.

### Screenshots or videos

https://github.com/user-attachments/assets/2c461a50-1e3e-43f8-a74f-9758f9e7fc03

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17787849/compressed-logs.zip)

**Comment by Joehuu** [comment]
Seems to happen only on Linux (tested on Linux Mint 21.2).

**Comment by shinmorisawa** [comment]
testing in gentoo, i can confirm that this happens.

**Comment by peppy** [comment]
cc @Susko3 for visibility

**Comment by Susko3** [comment]
<kbd>Ctrl</kbd>+<kbd>{key}</kbd> doesn't produce text on most keyboard layouts. Do other programs (web browser, graphical text editor) also exhibit this behaviour (text being typed even if <kbd>Ctrl</kbd> is held)? Try to test with keys that aren't keyboard shortcuts.

Please enable SDL logging with envvar `SDL_EVENT_LOGGING=1` and reproduce the issue, uploading the osu! logs.

Please also try reproducing in SDL3, by setting envvar `OSU_SDL3=1`.

**Comment by yellowbadbeast1** [comment]
SDL_EVENT_LOGGING=1 logs: [compressed-logs.zip](https://github.com/user-attachments/files/17807803/compressed-logs.zip)

OSU_SDL3=1 logs (successfully reproduced): [compressed-logs.zip](https://github.com/user-attachments/files/17807807/compressed-logs.zip)

Seems to not work properly with ctrl + plus/minus, zero, one (which oddly seems to override the hotkey to switch to the osu! ruleset entirely), comma, period, semicolon, and quote. All other keybinds seem to work properly.

I can't seem to reproduce it on Firefox and Kate.

**Comment by yellowbadbeast1** [comment]
SDL_EVENT_LOGGING Logs: [compressed-logs.zip](https://github.com/user-attachments/files/17807856/compressed-logs.zip)

OSU_SDL3 Logs (Successfully reproduced): [compressed-logs.zip](https://github.com/user-attachments/files/17807869/compressed-logs.zip)

Ctrl + plus/minus, zero, nine, one (which blocks the osu! rulset keybind), comma, period, semicolon, and quote all add text in the text box. Everything else works fine.

I couldn't reproduce this on Firefox and Kate.
