### ISSUE TITLE
Profile Freeze Bug

### ISSUE THREAD

**Issue by fntStique** [ppy/osu#3070]
-Bugs:
While clicking on users in chat,and seeing the profile the game will freeze,and I can move my mouse cursor,but the music along with the game freezes. I can't use the Win button so I need to shut down the game via CTRL+ALT+DEL.

-Suggestions:
The new osu!lazer skin looks pretty dope,but the yellow circle when dragging on sliders looks too big in my opinion.

**Comment by Joehuu** [comment]
Can't reproduce.

**Comment by peppy** [comment]
i don't believe this still happens
