### ISSUE TITLE
Clicking Visual/Audio settings sliders on beatmap loading will keep them selected permanently

### ISSUE THREAD

**Issue by imvanni** [ppy/osu#30716]
### Type

Game behaviour

### Bug description

Tapping any slider (this also applies to drag begin) on settings while the beatmap is loading will keep that slider selected, prompting the map to not load until it is unselected. While it is not game breaking, it is quite annoying sometimes.

Previously, moving the sliders would not keep them in a "selected" state.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/6c9dcff3-1f7c-42c4-b081-011b388690b9)

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17790174/compressed-logs.zip)

**Comment by shinmorisawa** [comment]
i think this is intentional. idk though

**Comment by peppy** [comment]
> prompting the map to not load until it is unselected. While it is not game breaking, it is quite annoying sometimes.

i'm not sure this should be closed if the OP is correct.

**Comment by smoogipoo** [comment]
Ah, I missed that part. I agree.

**Comment by imvanni** [comment]
Should've attached a video to this earlier.

https://github.com/user-attachments/assets/ab700290-477c-4e56-9f77-800582650c0f

**Comment by imvanni** [comment]
Not load as in not start? Did I use the wrong wording back there? I don't know. 

If this is supposed to be intentional behavior, then we can close it. Though I preferred the old behavior.
