### ISSUE TITLE
Beatmap "Solace of Oblivion" Bug

### ISSUE THREAD

**Issue by ulumunderscored** [ppy/osu#30726]
### Type

Beatmap Bug

### Bug description

there's a part in a beatmap called solace of oblivion which lags so bad and can't be cleared

### Screenshots or videos

https://youtu.be/7T07WdHPnHI
Here's a youtube video about it

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17791711/compressed-logs.zip)

**Comment by peppy** [comment]
[seraching is powerful](https://github.com/search?q=repo%3Appy%2Fosu+Solace+of+Oblivion&type=issues)
