### ISSUE TITLE
Endscreen displays incorrect combo after watching scores that were set on stable. [osu!mania]

### ISSUE THREAD

**Issue by theredpro-sj** [ppy/osu#30739]
### Type

Game behaviour

### Bug description

The issue first stems from the differences relating to combo given by long notes in stable compared to lazer. In lazer no matter the duration of the long note only 2 combo is given while in stable the amount of combo received is dependent on how long the long note is. This can result in maps having a max combo higher or lower (more often lower) than that in stable. On the leaderboards scores set in stable show the amount of combo and max that is seen in stable, however if you watch the replay the combo seen during it matches combo that would be seen in lazer, not stable. Then when the endscreen pops up the scores max combo is different than what is seen on the leaderboard.

### Screenshots or videos

The first 2 screen shots are from before watching the replay
![Uploading Screenshot 2024-11-17 at 9.45.41 PM.png…]()
![Uploading Screenshot 2024-11-17 at 9.45.48 PM.png…]()
At the end of the song, notice the difference in combo.
![Uploading Screenshot 2024-11-17 at 9.46.40 PM.png…]()
Endscreen displays a different combo now.
![Uploading Screenshot 2024-11-17 at 9.47.47 PM.png…]()

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17794008/compressed-logs.zip)

**Comment by theredpro-sj** [comment]
Screenshots didnt upload properly but here they are in the same order that the post wouldve had
<img width="1470" alt="Screenshot 2024-11-17 at 10 07 34 PM" src="https://github.com/user-attachments/assets/bf297421-6c5c-4f6a-babf-2b144b2f12f5">
<img width="1470" alt="Screenshot 2024-11-17 at 10 07 39 PM" src="https://github.com/user-attachments/assets/9a9f3be0-6766-4b99-aca7-a38ee2602b3a">
<img width="1470" alt="Screenshot 2024-11-17 at 10 08 19 PM" src="https://github.com/user-attachments/assets/de268eb4-480f-492d-9426-3f38d0fc4836">
<img width="1470" alt="Screenshot 2024-11-17 at 10 08 36 PM" src="https://github.com/user-attachments/assets/7c156e4a-a662-42ed-9388-8af4c2583fa7">

**Comment by smoogipoo** [comment]
This is intentional and I don't know if we'll ever change this (combo) to work like osu!stable...
