### ISSUE TITLE
The entire screen starts flickering in osu!(lazer).

### ISSUE THREAD

**Issue by ghoioihoi** [ppy/osu#30758]
### Type

Game behaviour

### Bug description

When opening osu lazer with graphic renderer set to OpenGL, the entire screen will start flickering and cursor movement is also restricted, but the issue can be temporarily resolved if you are recording screen with Microsoft recording toolbar. the issue will reoccur once screen recording ends. Due to this i cant screen record the problem. The issue doesnt appear on Direct3D 11.

### Screenshots or videos

https://github.com/user-attachments/assets/35b940d8-08ea-4c90-94c0-5f57f9126f5c

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17802061/compressed-logs.zip)

**Comment by bdach** [comment]
We can't do anything about that, it's gonna be a driver issue. If direct3d works then please use that. 

If you can't switch back because of the brokenness, please go to the game directory (`%appdata%/osu`) and remove the line starting with `Renderer =` in `framework.ini`.
