### ISSUE TITLE
Left side of gameplay skin editor is covered by ui components

### ISSUE THREAD

**Issue by gowon11** [ppy/osu#30753]
### Type

Cosmetic

### Bug description

Was messing around with the skin editor on lazer to position the "BarHitErrorMeter" on center-left. When positioning on the center left of the visible playfield it got placed on the left side of the playable area, not on the left corner of the screen (my mistake as shown in the video below i was just doing it wrong). Just out o curiosity i tried to shove it to the left as much as i could and it actually moved to the left of the screen, behind the skin components list on the left where it can't be clicked. Now i have a BarHitErrorMeter on the left of the screen but i can't click on it to move, resize, or make changes to it.

### Screenshots or videos

https://github.com/user-attachments/assets/af35a31b-4637-4f88-87be-0c518eb5270c

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17798125/compressed-logs.zip)

**Comment by peppy** [comment]
ctrl-a, delete, start over.

or ctrl-a then arrow keys to move them back on screen.

in the future we'll offer better management of this. for now just avoid breaking it.
