### ISSUE TITLE
Editor forgets hitsound addition choice when moving between objects

### ISSUE THREAD

**Issue by cloudrac3r** [ppy/osu#30839]
### Type

Game behaviour

### Bug description

The bug is happening to me in the osu!catch editor and I confirmed it exists in the osu! editor too. If the **addition** sample is changed to anything other than auto, then after moving between objects, the choice is often forgotten.

Sometimes it does remember the choice - in my video it would always keep *at least one* of the fruit's addition samples on S (soft), but I could *never* get it to keep all three of them at the same time.

A similar issue occurred for me across multiple maps.
Here is the map I was creating in the video: https://cadence.moe/friends/SiLiS-Hebe-Cadence.olz
I was editing from this featured artist template: https://osu.ppy.sh/beatmaps/artists/434

This issue might be related to #28741, but it's a bit different because for me the standard bank works fine and it's just the addition bank that's strange.

I tried these steps, but none of them helped at all:

- Reopening the editor
- Restarting the game
- Changing other object properties, like position, samples, or new combo
- Exporting as olz, deleting map, and importing olz 
- Exporting as osz, deleting map, and importing osz

### Screenshots or videos

[osu lazer editor addition bank.webm](https://github.com/user-attachments/assets/6ca8de77-7cdb-4b2d-83df-601a0fd8afaf)

In the video there are 3 fruit with sample additions. The standard bank is N (normal). Trying to change the addition bank of any of these objects to S (soft) initially works, but after switching objects, the editor usually forgets my choice. I try changing additions through the samples panel on the left, the hitsounding popover, and the right click menu, but it's the same behaviour of all of them.

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17870079/compressed-logs.zip)

**Comment by peppy** [comment]
So I started looking into this and was like "okay, it's just a standard case of event feedback... but the same kinda logic has been around for the new combo toggle for ages, why isn't it broken??"


https://github.com/user-attachments/assets/b83b260f-9291-4307-9328-8d891c9c83c8

**Comment by cloudrac3r** [comment]
The logic of that code goes over my head, but if you'd like, I can make your change locally, keep mapping, and see if I encounter any related issues in the coming days?

**Comment by peppy** [comment]
You can if you like. The reply was for other developers tracking this issue.
