### ISSUE TITLE
HP bar is smaller than stable/previous version

### ISSUE THREAD

**Issue by MisaLiu** [ppy/osu#30841]
### Type

Cosmetic

### Bug description

In this version, the HP bar is smaller than previous versions/osu!stable.

For example ([this skin](https://skins.osuck.net/cn/skins/2922?v=0)), the HP bar looks like this:

![osu_2024-11-22_21-43-18](https://github.com/user-attachments/assets/1515e22e-7b86-4de3-9d28-4d3f2677db97)

However in previous versions/osu!stable, it should looks like this:

![screenshot376](https://github.com/user-attachments/assets/baf57848-c809-4388-b22b-1dbce4b4bce3)

Is this a bug or it's intended?

### Screenshots or videos

See above.

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17871237/compressed-logs.zip)

**Comment by bdach** [comment]
Are you using UI / screen scaling?

**Comment by MisaLiu** [comment]
> Are you using UI / screen scaling?

Somehow I set UI scale to 0.94.

Which means skin size/position now related to UI scale?

**Comment by bdach** [comment]
Yes, skin elements are affected by UI scale. And this won't be fixed. The skin you're using is using a dumb hack to draw the playfield border. Use the one that is built into lazer instead (check settings),
