### ISSUE TITLE
Replay score not the same as actual score

### ISSUE THREAD

**Issue by ProjWyrd** [ppy/osu#30850]
### Type

Game behaviour

### Bug description

Originally this was gonna be about skipping time within a replay causes score calculation to be wrong, but upon investigating this further the whole replay score is completely wrong. pp, score, and somehow even hits and spinner bonuses are all wrong. I've tested this on serveral beatmaps and it all happens to varying degrees. If I'm not mistaken shouldn't all inputs on a beatmap be deterministic so this behaviour is very confusing (correct me if I'm wrong on this). 

### The score I got after completing the beatmap and is on the local leaderboard
![actual score](https://github.com/user-attachments/assets/38897bde-75bd-4985-8129-b6e4120b220d)
### The score I got after watching the replay without any time change
![replayed score](https://github.com/user-attachments/assets/5735f3bb-234f-4b67-9ea8-8ee84b1d36e3)
### The score I got after watching the replay and using the time skip button in top left
![time skip score](https://github.com/user-attachments/assets/3c3a7b57-5714-4028-b86b-d94c7f70bc65)

Also if it wasn't clear, when I refer to 'time skip' buttons I mean these ones
![image](https://github.com/user-attachments/assets/349da7ae-1e8b-4cce-8e89-c08f60c9f45b)

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17878702/compressed-logs.zip)

**Comment by ProjWyrd** [comment]
Ah didn't realize #29217 already existed. But don't think the time skipping thing affecting the score was known. So for the moment I'm *not* gonna close it. But feel free to close it either way :)

**Comment by frenzibyte** [comment]
Please attach your score replay next time you report an issue surrounding an incorrect behaviour on specific replays.

Judging from the screenshot, the comparison between the first and second screenshot indicate #29217. That is correct. You may attach your replay in that issue thread in case there is another underlying issue lurking in your replay.

The comparison between the second and third screenshot indicate unexpected sliderbreaks (245 vs 252 on slider end stat), and there are three separate issue threads related to this: https://github.com/ppy/osu/issues/21659, https://github.com/ppy/osu/issues/17413, and https://github.com/ppy/osu/issues/13352

Closing as duplicate.
