### ISSUE TITLE
Music losts bypass effect when Effects volume is set to 0

### ISSUE THREAD

**Issue by asrieldashie** [ppy/osu#30870]
### Type

Game behaviour

### Bug description

The bypass effects that applies when a confirmation window show up does not apply when Effect volume is set to 0
The effect applies when the volume is set up any number above 0

### Screenshots or videos

https://github.com/user-attachments/assets/bc9de978-5420-404f-802d-30643efd5c96

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17908364/compressed-logs.zip)

**Comment by frenzibyte** [comment]
This is intentional for now, see https://github.com/ppy/osu/discussions/28984. As the thread already mentioned, whether the user should be able to disable UI sounds completely is questionable in the first place, but that's a topic for another day.
