### ISSUE TITLE
Lazer web overlay inconsistency where mappers with changed names have inconsistent naming between map comments and actual profile name.

### ISSUE THREAD

**Issue by fatnerd3566** [ppy/osu#30882]
### Type

Cosmetic

### Bug description

Bug found by clicking on the beatmap details in song select and noticing the inconsistency between mapper naming.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/7f068f32-c343-4eba-91cb-a040d515e155)
![image](https://github.com/user-attachments/assets/4df85239-2161-4737-a21f-598475561d5c)

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17916755/compressed-logs.zip)

**Comment by bdach** [comment]
It's the same on the website: https://osu.ppy.sh/beatmapsets/1411839#osu/2910528

Issue belongs in https://github.com/ppy/osu-web/issues. *If* this isn't explicitly intentional, that is. Which it might be.
