### ISSUE TITLE
IME (fcitx5) placed in wrong place on when using scaling on Wayland

### ISSUE THREAD

**Issue by kuroya2mouse** [ppy/osu#30919]
### Type

Cosmetic

### Bug description

When using 2x scale on Wayland (Sway 1.9), language tooltip is placed in wrong place.

### Screenshots or videos

When 1x scale:
![1x](https://github.com/user-attachments/assets/00c5e354-955e-4e39-af47-3ca7375239c4)

When 2x scale:
![2x](https://github.com/user-attachments/assets/18155168-45e3-4bb3-8903-700af6ee0a63)

### Version

2024.115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17959824/compressed-logs.zip)

**Comment by bdach** [comment]
It's either your compositor, fcitx, SDL2, or wayland itself somehow. Nothing can be done about this in this repository, and I'm not willing to recreate your exact linux setup to investigate this sort of breakage.
