### ISSUE TITLE
Score with more combo than the maximum allowed

### ISSUE THREAD

**Issue by Valerus9** [ppy/osu#30916]
### Type

Other

### Bug description

I was scrolling through my maps when I saw this unacceptable score.

### Screenshots or videos

![Unacceptable](https://github.com/user-attachments/assets/30c62bdd-bbec-4cd4-81c6-e93809001154)

### Version

2024.1115.3

### Logs

[logs.txt](https://github.com/user-attachments/files/17957922/logs.txt)

**Comment by Valerus9** [comment]
Link: https://osu.ppy.sh/scores/3914259228

**Comment by frenzibyte** [comment]
Report it instead.
