### ISSUE TITLE
Kiai time disappearing from timeline when create a new difficulty

### ISSUE THREAD

**Issue by MeerukYang** [ppy/osu#30920]
### Type

Game behaviour

### Bug description

https://github.com/user-attachments/assets/1bb278d9-2e9a-4e62-bf15-e8de84f2479d

This could happen between any two difficulties, whatever gamemode. Unless you create a deplicate of the current difficulty, the kiai time would always disappear.

btw, in taiko and mania, scroll speed is totally a different thing from kiai time;these two effects should be treated separately.

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17960191/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Right now we only copy the timing points of the beatmap when creating a blank difficulty:
https://github.com/ppy/osu/blob/110e4fbb30503114779e18348e098d062a9ea378/osu.Game/Beatmaps/BeatmapManager.cs#L157-L158

Changing the code to copy effect points as well sounds easy, but I guess it's unexpected for the user to have scroll speed specifications copied across as well? OP says so at least. Not sure. cc @ppy/team-client

**Comment by bdach** [comment]
Copying across kiai specs sounds fine. Not sure about scroll speed, I could see arguments for and against. Maybe safest to just drop scroll speed changes.

**Comment by peppy** [comment]
I'd probably say copy all types and leave it up to the user to remove any they don't work.

Usually the same parts of the map would see some kind of scroll speed changes regardless of difficulty.
