### ISSUE TITLE
Latest release does not contain updated Android app

### ISSUE THREAD

**Issue by NeofetchNpc** [ppy/osu#30931]
### Type

Other

### Bug description

please update the apk file in tags, please it's been 2 weeks, I thought you guys realized it but you didn't. 

### Version

latest

### Logs

.

**Comment by frenzibyte** [comment]
Android build process has only been fixed a few days, calm down.

**Comment by peppy** [comment]
@NeofetchNpc  the update contains no noticeable changes, for what it's worth. there should be no reason you need this other than to silence the update notification.

**Comment by peppy** [comment]
Gonna wait for the next releas at this point, since we're already scheduling it.
