### ISSUE TITLE
Ctrl+Shift+Enter  shortcut doesn't start the play with Cinema Mod like in stable version

### ISSUE THREAD

**Issue by SenorNikicho** [ppy/osu#30930]
### Type

Game behaviour

### Bug description

When using Ctrl+Shift+Enter shortcut in the map selection menu, the play starts with Auto unstead of Cinema mod like in stable version.

The comparison between stable and lazer is in the video below.

The video 1: stable

https://github.com/user-attachments/assets/a5d37d94-0aa4-43d1-84b5-b0579060a2d5

The video 2: lazer

https://github.com/user-attachments/assets/6d805511-e890-4da4-9773-3b28b5db8400

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17966163/compressed-logs.zip)

**Comment by peppy** [comment]
I don't know that we'll bring this back. It's such a niche feature and is probably not used by many.

**Comment by bdach** [comment]
We've had 2 pull requests attempting to add this back (https://github.com/ppy/osu/pull/9224, https://github.com/ppy/osu/pull/11047) and neither got anywhere. I'm just gonna close this as "not happening" in light of that.
