### ISSUE TITLE
Incorrect beatmap creator title

### ISSUE THREAD

**Issue by netflexy** [ppy/osu#30943]
### Type

Crash to desktop

### Bug description

When clicking on mapper of a map on the top left while being on difficulty of another mapper displays a mapset creator, but takes you to the diffiuclty mapper.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/b9bb2a10-3d38-4b26-805b-746e0510cea9)
![image](https://github.com/user-attachments/assets/f4c69032-a273-46a5-8ff9-65e589e792d7)

### Version

2024.1115.3Lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17974960/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/12965
