### ISSUE TITLE
Double cursor in gameplay

### ISSUE THREAD

**Issue by tutis12** [ppy/osu#30942]
### Type

Game behaviour

### Bug description

When I go above the menu bar in-game (I'm using borderless mode) double cursors appear in gameplay which is very annoying. Also had very similar things happening during alt-tab, pauses and map breaks, but maybe it got patched.

Also, would be cool if you guys would found a way to maximize the area for the game on macs, that menu bar is wasted space.

### Screenshots or videos

https://github.com/user-attachments/assets/6ef4697b-1a37-47e4-9cb8-83674351fd69

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17974273/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/24620
