### ISSUE TITLE
Switching to a different frame limiter setting while watching a replay slows down backwards seeking on osu!taiko

### ISSUE THREAD

**Issue by ominoussage** [ppy/osu#30974]
### Type

Game behaviour

### Bug description

Found it while trying to seek backwards on a replay. To replicate:

1. Watch a replay (with or w/o auto).
2. While on the replay, change FPS limiter setting.
3. Seek backwards a couple of times (either using arrow keys or via the argon/triangles progress bar).

Some ways to fix/avoid it would be to retry the replay or just not mess with the FPS limiter at all.

It's just a seemingly wrong behavior that can only be observed in niche use cases like I do (changing FPS limit often) but I just thought it's still worth a bug report. (If you're wondering, I use VSync to watch replays with no screen tearing, 4x refresh rate while playing.)

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18007008/compressed-logs.zip)

**Comment by ominoussage** [comment]
Doesn't happen on other gamemodes from my further testing.

**Comment by smoogipoo** [comment]
It's intentional. Seeking runs only as fast as the game itself is able to, and you're limiting it.

**Comment by peppy** [comment]
Hmm, I changed [the way that seeking works](https://github.com/ppy/osu/pull/26600) a while back in a way which means it's not limited to the frame limiter anymore, so this feels a bit suspicious. There's likely something at play causing frames to take longer to process with the different limiter applied. Not sure it's worth looking into unless very easily reproduced.
