### ISSUE TITLE
Searching by source in beatmaps not working properly

### ISSUE THREAD

**Issue by hiderikzki** [ppy/osu#30988]
### Type

Game behaviour

### Bug description

Clicking the ``source`` text in beatmap details tab pastes ``source=""[text]""`` into search, but the ``source`` attribute does not seem to actually be usable?

### Screenshots or videos

https://github.com/user-attachments/assets/ca272332-affd-4a90-b7b8-e0b66a727365

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18039736/compressed-logs.zip)

**Comment by Joehuu** [comment]
I've already fixed this in https://github.com/ppy/osu/pull/30684.
