### ISSUE TITLE
Wayland issue

### ISSUE THREAD

**Issue by user-naa** [ppy/osu#30985]
### Type

Game behaviour

### Bug description

If you start game in Fullscreen or Borderless game not launch on full screen. Changing mod to another fixes issue until restart.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/a01cd29c-6999-43b8-900b-8db5de9aa945)

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18035721/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Likely an SDL2 issue fixed in SDL3. You can try running the game with the environment variable `OSU_SDL3=1`.
