### ISSUE TITLE
Opening a playlist that has ended will visually show that it is open, until some time after exiting it

### ISSUE THREAD

**Issue by snalgae** [ppy/osu#31009]
### Type

Game behaviour

### Bug description

I was looking at my playlists and I noticed that the "Ended" icon changed into "Open". I couldn't submit any scores on it, so I think it's just a visual bug. When exiting it it also stays open some amount of time? But it's not the same for different playlists. I think it works with any playlist that have ended.

### Screenshots or videos

https://github.com/user-attachments/assets/44c00768-6703-4707-a782-d424b774fd6a

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18052608/compressed-logs.zip)

**Comment by Joehuu** [comment]
Already fixed in https://github.com/ppy/osu/pull/30805.
