### ISSUE TITLE
iOS home indicator no longer auto hides

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#31005]
This was supposed to be fixed by https://github.com/ppy/osu-framework/pull/6385 but the hint is set to `2` instead of `1`.

As per [SDL's documentation](https://wiki.libsdl.org/SDL3/SDL_HINT_IOS_HIDE_HOME_INDICATOR), setting the hint to `2` makes the home indicator still visible but dimmed, making it still not look as appropriate with other game components, as can be seen in the screenshot below:

![IMG_1775](https://github.com/user-attachments/assets/d86be4d0-6d1d-4ac5-90ad-5e5532b6d748)

This is unlike what the previous PR https://github.com/ppy/osu-framework/pull/5009 achieved (hiding the home indicator until the user swipes up), which is the equivalent of setting the hint to `1`.

Opening this issue thread for tracking purposes, and for if an opinion is to be raised before I get to this.

**Comment by peppy** [comment]
can you show the apple API which allows completely using it? i don't believe this is possible.

**Comment by frenzibyte** [comment]
Setting https://developer.apple.com/documentation/uikit/uiviewcontroller/prefershomeindicatorautohidden?language=objc to true will make it vanish. This is what we have used in https://github.com/ppy/osu-framework/pull/5009.

For reference, this is what SDL does with the value of the hint (0 = don't hide, 1 = hide, 2 = dim aka master):
https://github.com/libsdl-org/SDL/blob/19cc04a162532423eb6384b123ced6fdb8886f8d/src/video/uikit/SDL_uikitviewcontroller.m#L224-L249

**Comment by peppy** [comment]
I'm 99.9% sure you won't get what you are hoping for. Give it a try yourself I guess.

**Comment by smoogipoo** [comment]
It makes it vanish, sure, but I'm pretty sure if you gesture that area it'll still activate?

**Comment by frenzibyte** [comment]
That is correct, but I don't see what the point is. Do we not want the home indicator to be hidden? If so then sure, I can close this and move on. It looked silly to me when mixed with our current user interface (it even obstructs existing buttons in song select footer for example), so I would rather we switch to the mode that makes it auto-hide at least.

**Comment by smoogipoo** [comment]
Consider the case where someone's following a slider at the bottom of the screen, or spinning a spinner. The reason I made the fix is because I noticed it during gameplay so I'm absolutely certain we want the indicator to be non-interactive first and hidden second.

Unfortunately, Apple doesn't give us the option to do both. Going to close this one.

**Comment by peppy** [comment]
Just to make things very clear, there are two options:

- You can hide the marker but it will minimise the app on first drag
- You can dim the marker but it will minimise the app on second drag

The latter is the closest to what we need.

**Comment by frenzibyte** [comment]
I see.
