### ISSUE TITLE
Daily Challege Notification's go to beatmap button not working correctly

### ISSUE THREAD

**Issue by zznyjidi** [ppy/osu#31003]
### Type

Game behaviour

### Bug description

The go to Beatmap button (>>) on the daily challenge notification will bring you to the song in the song selection list instead of the daily challenge page if it is already downloaded

### Screenshots or videos

https://github.com/user-attachments/assets/4dae28fb-afe6-4d30-a39e-60ca2bcda6ba

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18050404/compressed-logs.zip)

**Comment by frenzibyte** [comment]
You have to click on the notification itself, not specifically the "Go to beatmap" button in the beatmap card embedded in the notification.
