### ISSUE TITLE
No volume wheel when in settings popout

### ISSUE THREAD

**Issue by superfetthammerbombe** [ppy/osu#31001]
### Type

Cosmetic

### Bug description

Pressing CTRL+O in the song select and scrolling volume with ALT shows behind the settings popout. To see it, you'
d have to close the settings. Not really a big problem, but a nice thing to fix for a full release.

### Version

2024.1115.3

### Logs

there really isnt a log for this problem

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/11077
