### ISSUE TITLE
Item anchors don't work as well in the map selector as they would in-game

### ISSUE THREAD

**Issue by FAJIFBEFJHA** [ppy/osu#31018]
### Type

Game behaviour

### Bug description

I try to put a text that says the maximum pp of the map in the map selection but it is not placed in the place that I want, so to speak, but rather it goes noticeably forward. The video explains better what I mean

### Screenshots or videos

https://github.com/user-attachments/assets/abae0752-8779-4fb2-ba39-aba5edc4f7db

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18056347/compressed-logs.zip)

**Comment by N0Y0U2114** [comment]
This is due to the way the anchor system and how objects interact with aspect ratio. Easiest way to fix this would be:
Right click> Anchor > Center

**Comment by shinmorisawa** [comment]
> This is due to the way the anchor system and how objects interact with aspect ratio. Easiest way to fix this would be: Right click> Anchor > Center

this should fix this issue
