### ISSUE TITLE
Resuming osu! ruleset gameplay on mobile may need reconsideration

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#31042]
For people who play purely by just tapping and sliding on the screen, when gameplay is paused by the user pressing the "hold for menu" button or an external action interrupting the game, resuming happens instantaneously due to the cursor not being last located in the screen.

I think it would at least be more appropriate to fall back to the time-based resume overlay when the cursor is not within the gameplay area. At first, I thought about implementing this by completely using `DelayedResumeOverlay` when the score has "touch device" in the mods list (similar to autopilot), but mobile players which use one hand for tapping and another for pointing will probably be annoyed by it.

Opening for tracking and/or opinions.

**Comment by peppy** [comment]
I think always using the delay version is fine personally.
