### ISSUE TITLE
Mods display override Accuracy display

### ISSUE THREAD

**Issue by NotEnderVN** [ppy/osu#31075]
### Type

Other

### Bug description

The accuracy display is being overridden because multiple mods. (sorry for bad english)

### Screenshots or videos

![image](https://github.com/user-attachments/assets/662e5bdc-25b6-4bf2-be4f-add401877b5e)

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18091101/compressed-logs.zip)

**Comment by bdach** [comment]
Has been reported several times, this leaderboard is pending a redesign, etc etc
