### ISSUE TITLE
Can open multiple instances on Linux

### ISSUE THREAD

**Issue by LittleLilyBun** [ppy/osu#31072]
### Type

Game behaviour

### Bug description

You can open multiple instances of the game on Linux, either by opening the appimage another time, or by opening an osu!direct link.

### Screenshots or videos

https://github.com/user-attachments/assets/1852baf8-4604-4626-a646-de962b2f62ff

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18088108/compressed-logs.zip)

**Comment by bdach** [comment]
Probably was always broken because of linux appimage sandboxing wangjangs.

**Comment by LittleLilyBun** [comment]
I know it worked as expected before, since osu!direct links previously would open in the already running instance just fine, but I'm not sure what version it stopped working in.

**Comment by bdach** [comment]
Might be a regression from the recent ipc changes then. Something something named pipe gets created inside of the sandbox rather than outside.

**Comment by peppy** [comment]
Also hit this one, am looking at a fix.
