### ISSUE TITLE
Do not show view settings in the skin editor

### ISSUE THREAD

**Issue by MrLimeick** [ppy/osu#31088]
### Type

Cosmetic

### Bug description

It seems that the view settings should not be active when customizing the skin.

### Screenshots or videos

https://github.com/user-attachments/assets/3e56b847-c37f-4400-a878-2bd0b8d7bfc6

### Version

2024.1208.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18103747/compressed-logs.zip)

**Comment by frenzibyte** [comment]
That looks like a very bad regression for skin editing. Assigned p:0.

**Comment by ComBoh23** [comment]
Hmm
