### ISSUE TITLE
Music in Skin Editor doesn't play after tabbing out and map restart

### ISSUE THREAD

**Issue by HenintsoaSky** [ppy/osu#31092]
### Type

Game behaviour

### Bug description

In the skin editor, if you enter gameplay mode, then tab out and wait for the map to restart, the music will not play. However, hitsounds will still play.

Steps to Reproduce:
- Open the skin editor.
- Enter gameplay mode.
- Tab out of the game.
- Wait until the map restarts.

### Version

2024.1208.0 -Lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18111485/compressed-logs.zip)

**Comment by Gabixel** [comment]
I think this is related to / a duplicate of #26022 (see https://github.com/ppy/osu/issues/26022#issuecomment-1872319019)

**Comment by HenintsoaSky** [comment]
Duplicate of https://github.com/ppy/osu/issues/26022
