### ISSUE TITLE
Beatmap skipped notes and then froze

### ISSUE THREAD

**Issue by drgndk** [ppy/osu#31116]
### Type

Game behaviour

### Bug description

Beatmap just skipped randomly 1-2 seconds forward and then froze.

Arch Linux (CachyOS Kernel), Hyprland

### Screenshots or videos

https://github.com/user-attachments/assets/ccfe7186-3769-437a-b72e-bed3df68cdc3

### Version

2024.1208.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18129107/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Either duplicate of https://github.com/ppy/osu/issues/26879 or something may be messed up with your linux configuration, likely the first.
