### ISSUE TITLE
Unable to change sensitivity when looking up "sensitivity" in the settings if "Raw Input/High precision" is disabled

### ISSUE THREAD

**Issue by WitherFlower** [ppy/osu#31119]
### Type

Game behaviour

### Bug description

Title.
Stable solves this by turning on Raw Input if you drag the sensitivity slider

### Screenshots or videos

https://github.com/user-attachments/assets/ef252a5d-7576-4c93-acc1-0da102334bc6

### Version

2024.1208.0-lazer

### Logs

Reported from someone else, lmk if you actually need the logs for this one

**Comment by bdach** [comment]
> Stable solves this by turning on Raw Input if you drag the sensitivity slider

I dunno about that. I'd say that that shouldn't happen. At least not currently when it's the case that turning on raw input can break other stuff.
