### ISSUE TITLE
Double or Triple Cursors showing when OBS is on in MacBook Pro

### ISSUE THREAD

**Issue by yesluck** [ppy/osu#31122]
### Type

Game behaviour

### Bug description

When playing osu!lazer on a MacBook Pro and simultaneously running OBS, multiple cursors (two or even three) appear on the screen.

macOS version: 14.7.1
OBS version: 31.0.0
osu! lazer version: latest

### Screenshots or videos

It's hard to capture the screenshot as the screenshot will automatically remove the cursors. But if necessary, I can try to take a photo of it.

### Version

Lazer 2024.1208.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18136820/compressed-logs.zip)

**Comment by peppy** [comment]
Can you provide a screnshot?

**Comment by peppy** [comment]
Please track at https://github.com/ppy/osu/issues/24620. This is basically the same issue.
