### ISSUE TITLE
can't pause immediately after unpausing when in intro/break

### ISSUE THREAD

**Issue by JWD-II** [ppy/osu#31124]
### Type

Game behaviour

### Bug description

when you unpause in the intro or break you have a 1 second-ish delay before you can pause again. this is especially annoying when its the end of a break and you can't pause before gameplay continues.

### Version

idk, as long as i can remember

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18137560/compressed-logs.zip)

**Comment by frenzibyte** [comment]
It should be fine to exclude pause cooldown penalty during breaks.
