### ISSUE TITLE
Replay options opening in skin editor?

### ISSUE THREAD

**Issue by yomikomanda** [ppy/osu#31120]
### Type

Game behaviour

### Bug description

Recent update made the replay options open when hovering to the right side of the screen. Since the skin editor preview is a replay, it caused the options to open when reaching for objects on the right. This shouldn't happen (atleast in my opinion) since you can't change any of the options in the skin editor anyway.

### Screenshots or videos

https://github.com/user-attachments/assets/42d60fd2-5889-4fe0-b8c0-32db9984a557

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18135826/compressed-logs.zip)

**Comment by Joehuu** [comment]
Already fixed in https://github.com/ppy/osu/pull/31105.
