### ISSUE TITLE
Mods in leaderboard overlapping other elements

### ISSUE THREAD

**Issue by Dott-rus** [ppy/osu#31130]
### Type

Cosmetic

### Bug description

I think mods need to not overlap the area with other stats, now I can't see how much accuracy he has without going into the replay

### Screenshots or videos

![image](https://github.com/user-attachments/assets/f26ed835-61b1-4498-8d31-eb2b852a1508)

### Version

2024.1208-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18139156/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Please search first before posting.

![CleanShot 2024-12-15 at 01 31 52](https://github.com/user-attachments/assets/1e212475-f2d0-49ea-aecb-83acec18ed96)
