### ISSUE TITLE
Mute hitsounds during rewind

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu#3113]
Because 100s of hitsounds playing at the same time doesn't make for a _sound_ experience.

https://streamable.com/21r39

**Comment by ekrctb** [comment]
I think clicking on the timeline should time-warp instantly, not "super fast-forwarding" in the first place.

**Comment by peppy** [comment]
My intention was to have the audio rate transform up then back to current speed while doing short seeks (<10 seconds?) and doing an instant seek for longer seeks.
