### ISSUE TITLE
Trailing and leading spaces in login credentials cause authentication issues.

### ISSUE THREAD

**Issue by GabuTheDev** [ppy/osu#31159]
### Type

Other

### Bug description

The `username` and `password` input values are not trimmed before being sent to the API, which results in login errors. Neither usernames nor passwords should begin or end with whitespace. 

I initially discovered this issue on mobile. When using the keyboard suggestions to autofill my username, a trailing space was automatically added after it. This is a common behaviour that occurs on mobile devices. 

I've attached a video that shows the issue on the desktop client and a picture from osu-web that advises against the use of spaces in a username.

### Screenshots or videos

https://github.com/user-attachments/assets/aff9f574-d677-4785-8899-73628c2faf32

![image](https://github.com/user-attachments/assets/fcd0b4a8-bf37-44ae-acca-2c76e58cad59)

### Version

2024.1115.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18151361/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Resolved in ppy/osu-web#11751
