### ISSUE TITLE
osu!lazer uses lots of RAM even when map loading is cancelled

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3115]
osu!lazer will use up a certain amount of memory for each map, but it does that even if map loading is cancelled immediately after selecting the map by pressing ESC. This means that a lot of unused data is stored. What's even more problematic is that redoing this multiple times will make osu!lazer use even more ram, even though the same map is loaded again. This can shoot up ram usage in the 10gb+ range, where osu!lazer becomes laggy and may crash.
This is easily reproducable by trying to load in very ram intensive maps, e.g. https://osu.ppy.sh/b/450198 or https://osu.ppy.sh/b/1332830.

**Comment by Morilli** [comment]
Can no longer reproduce this exact issue on the current master. Even though ram usage for these maps is obviously still high and ram usage isn't really cleared after a map has been finished, the main issue of maps using ram even though their loading was cancelled does no longer exist (for me).

**Comment by peppy** [comment]
ah yes, this is fixed as we now have cancellation support game-wide.
