### ISSUE TITLE
Score card doesn't display guest mappers

### ISSUE THREAD

**Issue by yellowbadbeast1** [ppy/osu#31167]
### Type

Cosmetic

### Bug description

It should say "Mapped by Tycani", not Pho

### Screenshots or videos

![osu_2024-12-16_16-22-57](https://github.com/user-attachments/assets/4f376c92-a291-4176-921c-15252e9db456)

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18158521/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Duplicate of https://github.com/ppy/osu/issues/12965. Try searching first.
