### ISSUE TITLE
Osu! randomly scrolling by itself

### ISSUE THREAD

**Issue by evvev** [ppy/osu#31163]
### Type

Game behaviour

### Bug description

Sometimes, while I’m playing osu!, the game starts scrolling down uncontrollably out of nowhere, and there’s no way for me to stop it. I’ve tried restarting the game, repairing it, and even reinstalling it, but nothing has worked so far.

### Screenshots or videos

https://github.com/user-attachments/assets/29507467-0b1a-4ad3-ae8c-e131453ecf9f

### Version

Stable 20241030

### Logs

[Logs.zip](https://github.com/user-attachments/files/18156025/Logs.zip)

**Comment by Joehuu** [comment]
This repo is for lazer issues not stable, but I can redirect you to https://osu.ppy.sh/community/forums/topics/299015 (tl;dr something to do with numlock or a controller plugged in).
