### ISSUE TITLE
Issues when using mods

### ISSUE THREAD

**Issue by 0wUCat** [ppy/osu#31168]
### Type

Cosmetic

### Bug description

idk if this is just lazer or stable, but when you add mods, it doesnt change the order the maps appear in , im using 2x doubletime on tanuki chi no bouken, it also doesnt change the color of the difficulties with mods below where the title is, anyway thx ppy for this amazing game

### Screenshots or videos

![image](https://github.com/user-attachments/assets/441ac073-e446-46e3-91a5-17d05765e880)

### Version

lazer latest whatever

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18159204/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Thanks for the report. We're aware of these issues already, tracking in https://github.com/ppy/osu/issues/12628 / https://github.com/ppy/osu/issues/10242. Try searching first!
