### ISSUE TITLE
HUD Overlay Visibility stays off in skin editor

### ISSUE THREAD

**Issue by EyeonizedOSU** [ppy/osu#31183]
### Type

Game behaviour

### Bug description

If 'Hud Overlay Visibility Mode' is set to 'Never' or 'Hide During Gameplay', It will stay that way even if you go to the skin layout editor. 
This should probably be automatically switched to 'Always' instead upon entering the layout editor, or allow users to toggle while in the menu.

### Screenshots or videos

![Screenshot 2024-12-18 135656](https://github.com/user-attachments/assets/12ed019e-65eb-44c9-a372-b730013189ed)
Where it should look like this:
![Screenshot 2024-12-18 135856](https://github.com/user-attachments/assets/f97487de-93f6-45c1-9fb3-41fd1f0724d3)

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18183557/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/27304
