### ISSUE TITLE
Toolbox and Inspector are 1 pixel from the edge

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu#31197]
### Type

Cosmetic

### Bug description

The Inspector and toolbox ui are not attached to the edge of the screen, there's a pixel gap.

Dissapears when I turn my screen scaling settings of. 

Settings:

1920x1200
UI Scaling 1,00x
Screen Scaling Everything
vertical scale 90%

### Screenshots or videos

![Skärmavbild 2024-12-19 kl  13 53 49 (2)](https://github.com/user-attachments/assets/8dfc5216-3daa-4609-8ea5-e88be13e6e10)

Zooming in on the right edge you'll see a blue note and on the left edge the border of the playfield

### Version

2024.1219.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18198199/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/4591
