### ISSUE TITLE
Beatmap freezes on ultra wide screen

### ISSUE THREAD

**Issue by WebFreak001** [ppy/osu#3119]
Set your screen size to 7680x1080 (on a full HD monitor on linux you can do `xrandr --output DISPLAY --scale 4x1`)

Observe that map just freezes shortly after startup, but you can advance it by pausing and unpausing to a next frozen state. UI still works, can exit and pause.

```
Linux archlinux 4.17.5-1-ARCH #1 SMP PREEMPT Sun Jul 8 17:27:31 UTC 2018 x86_64 GNU/Linux
```

**Comment by UselessToucan** [comment]
It is not obvious from the description which screen modes are affected. @WebFreak001 Can you clarify this?
![osu_2018-07-29_00-02-04](https://user-images.githubusercontent.com/22450664/43360678-d5770fe6-92c2-11e8-9a7e-61074e5e308d.jpg)

**Comment by WebFreak001** [comment]
It's on windowed. It might be a linux specific bug too.

Also I have noticed that the actual size doesn't matter, just make it ultra small in height compared to width.

**Comment by peppy** [comment]
@WebFreak001 can you still reproduce this?

**Comment by WebFreak001** [comment]
seems fixed
