### ISSUE TITLE
Invisible hit circles

### ISSUE THREAD

**Issue by fewizz** [ppy/osu#31200]
### Type

Game behaviour

### Bug description

After update (from 2024.1208.0 to 2024.1219.2), skin hit circles became invisible.

Skin in question (file extension was changed from osk to zip): 
[Dar_Bojiy_v1.6(Haenes).zip](https://github.com/user-attachments/files/18202491/Dar_Bojiy_v1.6.Haenes.zip)

### Screenshots or videos

2024.1219.2:
![image](https://github.com/user-attachments/assets/25b9aaac-d3f4-4ec5-9ead-9d841453b05d)

2024.1208.0:
![image](https://github.com/user-attachments/assets/22299991-0d49-46dd-92cb-ac345b10bf60)

### Version

2024.1219.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18201153/compressed-logs.zip)

**Comment by Joehuu** [comment]
The skin didn't finish uploading. Please reupload.

**Comment by fewizz** [comment]
> The skin didn't finish uploading. Please reupload.

Fixed the link.

**Comment by Joehuu** [comment]
This regressed in https://github.com/ppy/osu/pull/31052.

**Comment by Anczak** [comment]
I have the same issue with hitcircle but it's the border that is invisible
![obraz](https://github.com/user-attachments/assets/a1a49537-fd73-40c3-91f8-041c72a99c26)

**Comment by Joehuu** [comment]
Another complaint: https://osu.ppy.sh/comments/3426726

Gonna put this as priority 0 because at least 3 users are experiencing this.

**Comment by EgorBogdanov** [comment]
Just rename hitcircleoverlay-1 to hitcircleoverlay
