### ISSUE TITLE
Capslock on Mac does not work

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3120]
I am using 2018.722.0.

Steps to reproduce:

1. Enter the song selection menu
2. Hit capslock button (the indicator light on keyboard turns on)
3. Type to search

Expected capital letters, did not get that...

(That also happens in the settings search bar and the text bar for chat)

**Comment by Joehuu** [comment]
Can someone confirm if this still happens on SDL?

**Comment by frenzibyte** [comment]
Yeah this is fixed on SDL with its [text input events](https://wiki.libsdl.org/SDL_TextInputEvent).
