### ISSUE TITLE
difficulty filtering in beatmap search isnt working for converted maps

### ISSUE THREAD

**Issue by Janaijanai** [ppy/osu#31203]
### Type

Game behaviour

### Bug description

if you filter by diff like stars>5 while on other mode(taiko catch mania) but converts enabled the game detect the original standard difficulty of maps that are >5* but actually those are very low SR after conversion like in here: 

### Screenshots or videos

![osu_2024-12-20_02-29-50](https://github.com/user-attachments/assets/07309700-b967-4ab9-aafd-1c50da3cc5b0)

### Version

2024.1219.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18204895/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/12628
