### ISSUE TITLE
Circle charts's starts seem to have a -90° offset

### ISSUE THREAD

**Issue by Bowarc** [ppy/osu#31201]
### Type

Cosmetic

### Bug description

It's purely a visual bug, and is not very important but i figured it should still be reported.

The map progression pi-chart when playing a map and the grade on the end screen seem to have their start angle weirdly offsetted (see screenshots)

The behavior is consistent across reboots.

SOFTWARE/OS VERSIONS
Operating System: Fedora Linux 41
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.12.4-200.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: NV166
Graphic driver: Default (Nouveau)

### Screenshots or videos

Take this screenshot for example
![image](https://github.com/user-attachments/assets/3a311532-d205-4b20-81be-65867b95cd3a)
In this screenshot, i played around 45% of the map.
It looks like the end position is fine, it shows a bit less than half, but the start position is at 3/4.  

Here, uhm my theory don't work anymore :c
![image](https://github.com/user-attachments/assets/21049cef-9b52-4112-8cb0-af363b88c40e)
I have no idea what happened.

I recorded the animation, hope it helps

[Screencast_20241219_222935.webm](https://github.com/user-attachments/assets/abb20ab2-8a47-4f47-baff-b9fcf56a3ad7)

Looks like the end angle is fine, but the start is broken

### Version

2024.1219.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18203437/compressed-logs.zip)

**Comment by Joehuu** [comment]
There's a discussion in https://github.com/ppy/osu/discussions/30290 that uses the same driver. Tracking there as a discussion instead because it is a driver issue.
