### ISSUE TITLE
Osu Lazer! Doesn't show up

### ISSUE THREAD

**Issue by DenshaOtk** [ppy/osu#3121]
Hi im using win10 and i downloaded osu lazer.. after install it should automatically opens like on my windows 7 pc but here on my windows 10 nothing... here's the log
[runtime.log](https://github.com/ppy/osu/files/2230122/runtime.log)

**Comment by HoutarouOreki** [comment]
Try this:
- press <kbd>Windows</kbd>+<kbd>R</kbd>
- type in `%appdata%` and press <kbd>Enter</kbd>
- search for a folder `osu` (without an exclamation mark) and enter it
- rename or delete the `client.db` file

**Comment by DenshaOtk** [comment]
IT WORKS!! THANKS!

**Comment by MTGPROD** [comment]
**Close this issue**
