### ISSUE TITLE
Opening an .osz file from file explorer on Linux opens 2nd instance of the game

### ISSUE THREAD

**Issue by TechniKris** [ppy/osu#31221]
### Type

Game behaviour

### Bug description

If the game is already running and I open a mapset file externally (e.g. through a file explorer or through a web browser's downloaded files list) it opens a 2nd instance of the game, instead of importing the mapset through the currently running game instance.
I remember it used to work properly somewhat recently (I can't pinpoint the exact version when things broke) so it seems like a regression in osu!.

osu! is installed through the AUR package [`osu-lazer-bin`](https://aur.archlinux.org/packages/osu-lazer-bin) and MIME handler providing the ability to open from file explorer is provided by [`osu-mime`](https://aur.archlinux.org/packages/osu-mime) (a dependency of `osu-lazer-bin`).
Uninstalling these packages and trying the standalone AppImage, it doesn't seem to register its own MIME handlers in the first place.

### Screenshots or videos

![two_lazers](https://github.com/user-attachments/assets/af15606f-c2cb-4d91-865b-7f930c3b8f81)

https://github.com/user-attachments/assets/55f6bd74-aa94-450d-86ea-b31e2c32f1c8

### Version

2024.1219.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18218669/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Probably meant to be resolved in this release (see https://github.com/ppy/osu/issues/31072 / https://github.com/ppy/osu-framework/pull/6452) but the framework update was skipped. cc @peppy

**Comment by peppy** [comment]
what's the prio 0 action here? test this is fixed on master then close..?

**Comment by frenzibyte** [comment]
Looks like something that may need a hotfix to me so I've assigned priority:0 to keep it visible. If you think it shouldn't then feel free to close /shrug

**Comment by TechniKris** [comment]
> Probably meant to be resolved in this release (see #31072 / [ppy/osu-framework#6452](https://github.com/ppy/osu-framework/pull/6452))

Ahh, I didn't think to check closed issues, sorry for the duplicate 😅

**Comment by G4PLS** [comment]
So this should be resolved with the next framework update?

**Comment by peppy** [comment]
It should, yes.

**Comment by peppy** [comment]
Please reopen or comment on this issue if things aren't fixed in the next release.
