### ISSUE TITLE
iOS/iPadOS native cursor overlaps with the in-game cursor

### ISSUE THREAD

**Issue by adaniel52** [ppy/osu#31233]
### Type

Game behaviour

### Bug description

Pretty sure no one has reported this yet.

I’m a new player and sideloaded/installed osu! via SideStore.
Play with USB mouse and bluetooth keyboard.
Expected the native cursor to be hidden.

### Screenshots or videos

In the menu (there’s a transparent black circle):
![KIMG0575](https://github.com/user-attachments/assets/b3a4b4f5-1488-406c-9d74-fefe6884e9af)

In a game (there’s a transparent white circle inside the in-game cursor):
![KIMG0580](https://github.com/user-attachments/assets/9c34b678-75d1-4ea5-8b3e-6974e3059ea6)

### Version

2024.1219.2-lazer

### Logs

Can’t access logs via iTunes, sorry :\

**Comment by frenzibyte** [comment]
Good timing, I've submitted a fix for that already yesterday https://github.com/ppy/osu/pull/31226. Will be resolved next release.

**Comment by adaniel52** [comment]
Oh, glad to hear that.
Thanks :D
