### ISSUE TITLE
Alt+Scroll no longer controls volume in editor

### ISSUE THREAD

**Issue by kongehund** [ppy/osu#31276]
### Type

Game behaviour

### Bug description

As per title.

I was pleasantly surprised to see https://github.com/ppy/osu/discussions/31060 addressed by https://github.com/ppy/osu/commit/d97ea781364323383fa59512e45cac494387fb4b (thanks peppy), but somewhere along the way, Alt+Scroll to control volume was regressed.

### Version

2024.1224.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18247385/compressed-logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/31267
