### ISSUE TITLE
[osu!stable] Extremely low offset in osu!mania can make last note impossible to hit if its right as the song ends

### ISSUE THREAD

**Issue by ItsCollector** [ppy/osu#31293]
### Type

Game behaviour

### Bug description

This bug is in osu!stable in osu!mania (however it could be in other gamemodes, I didn't test this).

If you use an extremely low audio offset, like -250, it can cause the song to end earlier and if there is a note on the last beat, it becomes impossible to hit as the client pretty much cancels out the input. I have provided a video with a key press overlay to show. 

### Screenshots or videos

https://youtu.be/Vz1em7DBSIs provides a demonstration.
[Test map files.zip](https://github.com/user-attachments/files/18254631/Test.map.files.zip) contains the ranked maps, the test map I made which is the ending of the final ranked map, and the replay for the test map.

### Version

b20241219.2

### Logs

[Logs.zip](https://github.com/user-attachments/files/18254541/Logs.zip)

**Comment by bdach** [comment]
https://github.com/ppy/osu-stable-issues
