### ISSUE TITLE
osu!taiko The ranking pannel will affect gameplay

### ISSUE THREAD

**Issue by Msoobe** [ppy/osu#31309]
### Type

Game behaviour

### Bug description

During normal gameplay, the ranking panel can be hidden, but it cannot be hidden when using autoplay
![osu_2024-12-27_23-13-16](https://github.com/user-attachments/assets/3d547572-adff-45d6-b89b-686bfb3fdd85)
![osu_2024-12-27_23-13-12](https://github.com/user-attachments/assets/ca641bc8-7a4b-4eab-b21c-7224d603e2a6)

### Screenshots or videos

![osu_2024-12-27_23-13-16](https://github.com/user-attachments/assets/3d547572-adff-45d6-b89b-686bfb3fdd85)
![osu_2024-12-27_23-13-12](https://github.com/user-attachments/assets/ca641bc8-7a4b-4eab-b21c-7224d603e2a6)

### Version

2024.1224.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18261553/compressed-logs.zip)

**Comment by bdach** [comment]
#20422

**Comment by Msoobe** [comment]
这是来自QQ邮箱の自动回复邮件。Oh，shit.
