### ISSUE TITLE
Incorrect slider nodes deleted 

### ISSUE THREAD

**Issue by kelinimo** [ppy/osu#31308]
### Type

Game behaviour

### Bug description

When one node is selected and then you try to delete some other node (not holding Control or anything) it deletes both nodes.

I'd expect the node selection to be "reset" on middle mouse click

### Screenshots or videos

https://github.com/user-attachments/assets/178ad89d-2393-46f2-bb47-2c6186888b0d

### Version

2024.1224.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18261234/compressed-logs.zip)

**Comment by peppy** [comment]
I can't reproduce this. Also the code says this would only be the case if you had the node that you're targeting to delete selected.

**Comment by kelinimo** [comment]
What were the buttons you tried? Because for me the issue is very consistent. It doesn't happen when using Shift + Right Click. But on middle click it happens every time

**Comment by hrfarmer** [comment]
Can repro as well 
The click on the first node is a left click, and the click on the second node is middle click.
https://github.com/user-attachments/assets/56a7b86b-77c4-4305-aedb-b0a29fe6c263
