### ISSUE TITLE
The beatmaps search no longer works

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#3131]
Since I launch osu!lazer in borderless the beatmaps search function doesn't work anymore, BUT when I put osu!lazer in windowed or full screen bah it works again. Weird.

**Comment by MTGPROD** [comment]
Other things if we change for example in full screen then we return in borderless the function works

**Comment by Morilli** [comment]
Works for me. Can you provide some system specifications?

**Comment by MTGPROD** [comment]
Name of the machine:
LATITUDE_E5530
 Operating system:
Microsoft Windows 10 Professional 64 bit (build 10.0.17134)
 Motherboard:
Dell 0XJY67 A00 (BIOS A20)
 Processor:
Intel Core i5-3340M 2.70 GHz (Intel64 Family 6 Model 58 Stepping 9)
 Memory:
Total Capacity: 8 GB
Clip #1 : M471B5173BH0-YK0 (4 GB)
Clip # 2 : M471B5173BH0-YK0 (4 GB)
 Storage:
WDC WD10JUCT-63CYNY0 (931.51 GB)
 Graphics card:
Intel HD Graphics 4000
 Network card:
Card #1: Broadcom Dell Wireless 1540 802.11a/g/n (2.4GHz/5GHz)
Map #2: Broadcom NetXtreme 57xx Gigabit Controller

Translated with www.DeepL.com/Translator

**Comment by UselessToucan** [comment]
Tried to reproduce on [0d8701d0cb53d17ce6a189d108dfed256380566f](https://github.com/ppy/osu/commit/0d8701d0cb53d17ce6a189d108dfed256380566f) (.NET Core) using the following steps.

1. Launch the game. (windowed screen mode)
2. Navigate to the song select screen.
3. Enter "tsuka" to the textbox.
4. Navigate to the home screen.
5. Change screen mode to the borderless.
6. Navigate to the song select screen.
7. Enter "tsuka" to the textbox.

Beatmaps were filtered correctly. I also tried to launch the game in the borderless screen mode and got the same result.

**Comment by peppy** [comment]
Please provide a video of what you were seeing if you can still reproduce it.

**Comment by MTGPROD** [comment]
I'm mostly sure it's windows 10 and discord that plays tricks on me with 300 overlay too. I'll test with the discord overlay

**Comment by MTGPROD** [comment]
Ok I think I understood osu!lazer has really trouble with the overlay especially with the windows 10 overlay the HDR bar or something like that and the overlay discord doesn't work and it prevents to interact with lazer auf if you disable it so my theory is that when I started lazer there was an overlay bug so what prevented describing up to "updated" the state of the game to unlocked the interface. Basically it's small bug with the overlay that happens 1 time out of 5 that quickly becomes boring
