### ISSUE TITLE
[Skin editor] Withdrawing the first operation will mess up everything

### ISSUE THREAD

**Issue by Miuzarte** [ppy/osu#31315]
### Type

Cosmetic

### Bug description

Enter `Skin layout editor` with a default skin

Place an element then press `Ctrl+Z`

### Screenshots or videos

https://github.com/user-attachments/assets/3cbfaad9-72ea-4d10-9576-57dc41ae8877

### Version

Lazer 2024.1224.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18262415/compressed-logs.zip)

**Comment by bdach** [comment]
#29429
