### ISSUE TITLE
Lag when USB device goes to sleep/wakes up

### ISSUE THREAD

**Issue by invtblWalrus** [ppy/osu#31325]
### Type

Performance

### Bug description

Bit of a weird one, and it took me a while to figure out what was happening at all. It seems that lazer lags when a USB device (in this case my mouse) goes to sleep or wakes up. My temporary workaround is to just turn my mouse off entirely and use my tablet, but this doesn't happen in stable, I can even disconnect and reconnect my mouse entirely without the game stuttering.

I'd prefer to leave my mouse on during gameplay for when I need to tab to my other monitor/click specific UI elements/etc.

Can provide additional details if they'll help.

For clarity, I slowed down the first video to make the graphs easier to see at 60fps.

### Screenshots or videos

https://github.com/user-attachments/assets/79e30d3e-fbd9-40e3-a557-7388d8c337f0

https://github.com/user-attachments/assets/a626139e-353a-4255-9687-fa7224be1a5c

### Version

2024.1224.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18267621/compressed-logs.zip)

**Comment by bdach** [comment]
This is more or less https://github.com/ppy/osu-framework/issues/6181 again, and will likely be resolved along with it (if that one ever gets resolved).

**Comment by Susko3** [comment]
Correct, but this is a useful repro case.

@invtblWalrus could I ask you to do some testing for me?

I see you are using single-threaded mode. Could you test in multithreaded and compare the behaviour? (Screen recording is useful!)

Could you also test both threading modes in SDL3? [Set the user environment variable](https://phoenixnap.com/kb/windows-set-environment-variable#Set_Environment_Variable_in_Windows_via_GUI) `OSU_SDL3` to `1`, and then open osu!(lazer).

**Comment by invtblWalrus** [comment]
> Correct, but this is a useful repro case.
> 
> @invtblWalrus could I ask you to do some testing for me?
> 
> I see you are using single-threaded mode. Could you test in multithreaded and compare the behaviour? (Please provide screen recordings and logs.)
> 
> Could you also test both threading modes in SDL3? [Set the user environment variable](https://phoenixnap.com/kb/windows-set-environment-variable#Set_Environment_Variable_in_Windows_via_GUI) `OSU_SDL3` to `1`, and then open osu!(lazer).

No problem.

2 videos attached, one is turning on and off my mouse with osu!lazer running in single-threading, other in multi-threaded. The issue is present in both.

https://github.com/user-attachments/assets/d93b8e1a-7889-4fbf-b278-29b31bbbb3f0

https://github.com/user-attachments/assets/d7c5d08b-0405-4c46-b374-6d2821f1a363

I did both of these with the user environment variable set to 1, though I'm not 100% sure I did that correct (maybe this screenshot will tell you I did something wrong.)
![image](https://github.com/user-attachments/assets/307a5204-a6cf-4755-922f-6def3c1274d1)

Logs as well attached.
[compressed-logs.zip](https://github.com/user-attachments/files/18383887/compressed-logs.zip)

Let me know if there's anything else I can provide to assist.

**Comment by Susko3** [comment]
It's not set correctly, you can tell by the "Mode: Borderless (SDL2)" above the FPS meters. Make sure that there aren't any spaces around the variable name and value. Type out the values as copying can sometimes include trailing spaces.

**Comment by invtblWalrus** [comment]
I think I just forgot to hit OK on the second dialogue so it didn't set correctly, oops.

Attaching 2 new videos here:

https://github.com/user-attachments/assets/e1e163a6-5f12-44b8-9d1f-f02044b31371

https://github.com/user-attachments/assets/64601727-870a-40d6-a62f-8f62ca6aaf38

Fresh logs:
[compressed-logs.zip](https://github.com/user-attachments/files/18384077/compressed-logs.zip)
