### ISSUE TITLE
Bug at song selction menu

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3132]
i was rewinding list with left/right arrow and this beatmap showed like this:
![osu_2018-07-27_23-00-22](https://user-images.githubusercontent.com/32620809/43346459-80dcb142-91f1-11e8-972d-e8725253d15b.jpg)

when i made screenshot it became normal

logs:
[database.log](https://github.com/ppy/osu/files/2237231/database.log)
[network.log](https://github.com/ppy/osu/files/2237232/network.log)
[performance.log](https://github.com/ppy/osu/files/2237233/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2237234/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2237235/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2237236/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2237237/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2237238/runtime.log)

**Comment by peppy** [comment]
This is going to be a hard one to figure out without a reproducible process for triggering it.

**Comment by smoogipoo** [comment]
I haven't replicated this in recent times, and given the age of this issue I'm going to close it.

Please report back if this still happens.
