### ISSUE TITLE
× and x are not linked

### ISSUE THREAD

**Issue by the-wildguy** [ppy/osu#31336]
### Type

Game behaviour

### Bug description

Typing "SPYxFAMILY" into the search bar should pop up with all maps containing "SPY×FAMILY", however [this map](url) doesn't show up as it doesn't contain a tag saying "SPYxFAMILY" only the source saying "SPY×FAMILY". I believe that the "×" and "x" character should both show when typing either of them as the character is visually simular and means the same thing. just like lowercase and uppercase letters are linked i believe these characters should be too

### Screenshots or videos

With ×
![image](https://github.com/user-attachments/assets/4e1b3a30-94f6-4f72-9895-02e8e99e9326)
With x
![image](https://github.com/user-attachments/assets/e134250f-cb80-4a6e-bd6b-4e020adccb16)

### Version

2024.1224.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18269007/compressed-logs.zip)

**Comment by smoogipoo** [comment]
There are many such occurrences, this is not happening. Add some spaces and the tags will cover it.
