### ISSUE TITLE
osu!lazer crashing after trying to send a Message in chat #lazer

### ISSUE THREAD

**Issue by WhiteRedWolf** [ppy/osu#3134]
I've been looking in the osu!lazer client what was new and all and i logged into my Account and tried typing something in the Chat, and after it tried sending it crashed. I dont know if thats because of my Account being Locked / Restricted (there was no point in actually trying to send a message anyway) but I dont know.

**Comment by FreezyLemon** [comment]
Probably related to #3068.

Could you provide log files? They're located in `%appdata%\osu\logs`.

**Comment by WhiteRedWolf** [comment]
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2238720/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2238721/performance-gamethread.update.log)
[performance-input.log](https://github.com/ppy/osu/files/2238722/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/2238723/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/2238724/runtime.log)
[database.log](https://github.com/ppy/osu/files/2238725/database.log)
[network.log](https://github.com/ppy/osu/files/2238726/network.log)
[performance.log](https://github.com/ppy/osu/files/2238727/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/2238728/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/2238729/performance-draw.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2238730/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2238731/performance-gamethread.draw.log)

**Comment by smoogipoo** [comment]
I believe this is fixed now.
