### ISSUE TITLE
Leaderboard placeholder glitchy transition

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#3136]
Happens after the word wrap support.

https://puu.sh/B5t1W/6609435583.mp4

**Comment by peppy** [comment]
Seems to be resolved.

**Comment by peppy** [comment]
Interesting, I cannot repro here. Can you confirm you're on `2018.906.0`?

**Comment by Joehuu** [comment]
Can confirm.
Another example:
https://puu.sh/BqXy3/fe7ef44e27.mp4

**Comment by smoogipoo** [comment]
This isn't resolved until the referencing PR is merged. Since it's framerate dependent you'll only really notice it if you record inside the visual test.

**Comment by Joehuu** [comment]
Outdated milestone.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu-framework/pull/2249.
