### ISSUE TITLE
Why the choice of a JSON API over Websocket?

### ISSUE THREAD

**Issue by Itsyuka** [ppy/osu#314]
I'm just curious why you chose JSON API's over Websocket or even a traditional TCP connection. Is it because you want to have an easier time coding or have the horizontal scalability? Just seems like it'll cause too much of an overhead if you plan to continue with your JSON API, but that's just me.

**Comment by peppy** [comment]
what are you talking about? wrong repo?

**Comment by Itsyuka** [comment]
It'll be the correct repo as osu will be utilizing it

**Comment by peppy** [comment]
okay so for a start, your terminology is weird.

JSON is a data encoding format. websocket and TCP are communication methods (websocket uses TCP too soo.

JSON overheads are minimal, so where do you see this being an issue?

**Comment by Itsyuka** [comment]
Well, all the calls per second (in a large scale) to the server, seems a like it'll hurt the server more than it should.

**Comment by peppy** [comment]
We don't run the infrastructure on 386s.

Decoding JSON is not intensive.

Please don't worry about this.
