### ISSUE TITLE
Strange loss of graphics quality

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3142]
I encountered it when i leftgame open for some 2-4 hours in background
![osu_2018-07-30_14-33-41](https://user-images.githubusercontent.com/32620809/43398199-a126cc90-9407-11e8-8424-044b49bb8403.jpg)

video:
https://drive.google.com/open?id=1j_VFupakOIUX9W5hOGcOeUQMYGjeGlp0

logs:
[database.log](https://github.com/ppy/osu/files/2241156/database.log)
[network.log](https://github.com/ppy/osu/files/2241157/network.log)
[performance.log](https://github.com/ppy/osu/files/2241158/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2241159/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2241160/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2241161/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2241163/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2241164/runtime.log)

**Comment by peppy** [comment]
Is the issue you're mentioning the weird text on settings, or is there more to it?

**Comment by ticotaco72** [comment]
The text and that graphics are pixelated and in some places goes some white pixels in black place eg at left of user avatar(maybe not visible on the video)

**Comment by peppy** [comment]
@ticotaco72 Could you please confirm whether this is now fixed?

**Comment by ticotaco72** [comment]
I'll see, but now I'm away from computer. This bug was occurring randomly, so i think that I'll close it in week if i won't encounter this. Possibly I'll open it again if I'll see it.

**Comment by peppy** [comment]
We made a change to the shader to resolve a very similar issue, so there is a high chance it will also fix your issue. If it doesn't, it may just be heat or memory corruption related (at a hardware level), at which point we cannot really fix this one from our end.

Will close for now. Please re-open if you have new information.
