### ISSUE TITLE
Selected mods should be more obvious on songselect screen

### ISSUE THREAD

**Issue by jacksonisiah** [ppy/osu#3143]
Not exactly obvious, I played a few maps with NoFail on and didn't realize it was still on.

![image](https://vgy.me/4sWvdP.png)

stable has some text near the mod select button.

**Comment by arflyte** [comment]
![photoshop_180731-145305](https://user-images.githubusercontent.com/3632750/43440229-81cc86f8-94d1-11e8-8ed4-0c546130641c.png)

Mod button expands, showing activated mods.

**Comment by TPGPL** [comment]
should unassign?
