### ISSUE TITLE
osu-lazer linux sensitivity doesn't work

### ISSUE THREAD

**Issue by ghost** [ppy/osu#3170]
**Distros that the problem occurs on:** Antergos (KDE,Openbox,XFCE), ArchLabs Openbox, KDE Neon, Anarchy Linux (KDE,XFCE,Budgie) I have tried all this distros for real i was a distro hopper.

**Problem:** 
The problem is that when i turn on raw input and change the sensitivity a little or much higher than the cursor gets extreme sensitivity and flies all over the place when moving the mouse. If i change the sensitivity for a little or much lower then the cursor gets stuck in the place where i had it last and when i move it out of that place it rubberbands back. This basically means that i cant change my sensitivity and i would need it to be a little higher to play osu well.

**Extra Info:**
This problem occurs in osu-lazer native for Linux.
I have tried this on 2 different mouses and it have been the same problem. One time on a deltaco mouse and one time on a coolermaster storm mouse.

**Comment by fobekyo** [comment]
For me changing the confine mouse setting from fullscreen to always or from always to fullscreen (somehow mouse is not confined after startup and you have to set it again by doing this) after each startup fixed it.

**Comment by mrtuxblux** [comment]
It didnt fix it for me

**Comment by ylxdzsw** [comment]
Hi, I'm not sure if I'm experiencing the same bug. When I turn on "raw" mode and do not change the sensitivity (set to 1) it works fine. But if I change the sensitivity slightly larger (1.02), It seems that the pointer will keep moving at the same speed in my last direction all the time after I leave my mouse (thus resulting finally stopping at a corner). I'm on Archlinux with Gnome and Xorg and libinput.

**Comment by peppy** [comment]
We haven't tested raw input extensively with non-windows operating systems. Need some help to get this worked out.

**Comment by levifox54** [comment]
For people who have this bug:

if you have raw input OFF and use an input device with absolute positioning and press either left or right mouse click while the cursor is over the osu!lazer window, does the cursor act weird?

OR

if you have raw input ON and use an input device with absolute positioning, does the cursor act weird?

Two things I said above happens to me, and I have the bug mentioned by OP as well, so I was wondering if the two things above are related to the bug described by OP.

**Comment by nmjbhoffmann** [comment]
I've also seen this issue in Linux Mint 19.1 (Ubuntu 18.04 base), turning on raw mouse input is fine, the moment you touch that sensitivity slider the mouse goes nuts.
One think I'd like to add to this is that the mouse doesn't seem to register 100% correctly, for lack of a better term, if seems like it's dropping the input when moving fast.

An example of this is if you try to spin the mouse in a circle, you have to keep repositioning the mouse to keep it in the center. This doesn't happen with standard Osu! in wine, nor does my mouse have trouble staying in the middle of the screen when spinning it normally. regardless of Raw input or not.

**Comment by levifox54** [comment]
> One thing I'd like to add to this is that the mouse doesn't seem to register 100% correctly, for lack of a better term, if seems like it's dropping the input when moving fast.
 
> An example of this is if you try to spin the mouse in a circle, you have to keep repositioning the mouse to keep it in the center. This doesn't happen with standard Osu! in wine, nor does my mouse have trouble staying in the middle of the screen when spinning it normally. regardless of Raw input or not.

Yea, it seems its skipping some dots even at sensitivity 1 if raw input is on. I had way higher mouse drift with raw input on than with it off.

**Comment by mrshroomy** [comment]
Yep this does still not work, If anyone want to test this at any time then just do CTRL + ALT + R (that will reset the mouse settings) after testing if raw input works.

**Comment by theinventor143** [comment]
When i turn on raw in put my cursor gose flying of screen.

Operating System: Manjaro Linux 
KDE Plasma Version: 5.16.4
KDE Frameworks Version: 5.60.0
Qt Version: 5.13.0
Kernel Version: 5.2.8-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-4570 CPU @ 3.20GHz
Memory: 7.6 GiB of RAM

**Comment by peppy** [comment]
Closing as outdated. This should work now.
