### ISSUE TITLE
Fatal error when launching on Linux

### ISSUE THREAD

**Issue by jedenastka** [ppy/osu#3173]
Hi. I build osu!lazer from source using [this](https://gbatemp.net/threads/run-osu-on-linux-without-wine.502448/) tutorial. But if I try to launch it from command line like in README file (`dotnet run --project osu.Desktop`), I get a fatal error: [https://pastebin.com/mtVvAK7c](https://pastebin.com/mtVvAK7c). I'm using Debian 9.

**Comment by VPeruS** [comment]
Do you have x11/mesa/graphical driver installed?

**Comment by LastExceed** [comment]
The tutorial you linked is way outdated. It is trying to use .NETframework via mono instead of .NETcore natively.
-----
I highly recommend using vscode with the C# IDE extension to run osu!lazer on linux (you can do it without it but with vscode things will be much easier). Other than that you'll need git and the dotnet SDK.

```
git clone --recurse-submodules http://github.com/ppy/osu
cd osu
dotnet restore
```
then open the repo in vscode and build the project using the preset launch tasks.

**Comment by morguldir** [comment]
Sigh...

Debian has the package libgbm1 which provides "libgbm.so.1", but we look for "libgbm.so".

Install the "libgbm-dev" package for now.

**Comment by morguldir** [comment]
They actually seem to do this for everything, this means that we need to replace every occurrance of DllImport in OpenTK, osu-framework and osu with something more advanced.

**Comment by VPeruS** [comment]
You cannot have libgbm.so.1 without libgbm.so, it's means something on your system went wrong

**Comment by VPeruS** [comment]
Also gdm is from "super native" linux part of OpenTK, which means it cannot find xlib or sdl2

**Comment by morguldir** [comment]
>You cannot have libgbm.so.1 without libgbm.so

Yes you can:

![libgbm](https://user-images.githubusercontent.com/21371374/43671552-73424320-979c-11e8-8b60-1c9aeeb1cf6d.png)

Image from a debian install on https://distrotest.net



Yes, you probably won't have much luck running it on debian based distros right now.

**Comment by jedenastka** [comment]
I installed `libgbm-dev` and now `libgbm.so` is present:
`grzesiek11@debianek:~/osu$ find /usr/lib -name *gbm*
/usr/lib/x86_64-linux-gnu/pkgconfig/gbm.pc
/usr/lib/x86_64-linux-gnu/libgbm.so.1
/usr/lib/x86_64-linux-gnu/libgbm.so.1.0.0
/usr/lib/x86_64-linux-gnu/libgbm.so
grzesiek11@debianek:~/osu$ 
`
But I still have same problem:
[https://pastebin.com/ve0V0hTD](https://pastebin.com/ve0V0hTD)
(sorry for Polish, but I don't want to change system language again)

**Comment by morguldir** [comment]
Arch seems to be one of the only distros that include libgbm.so without a version number, which means that dotnet core can convert gbm to libgbm.so. Other distros however only give libgbm.so.1, but dotnet can't convert gbm to libgbm.so.1, so unless we want to say that most linux distros are wrong, this is not your systems fault.

If you look closer, you will se that the error is not the same this time, it isn't complaining about gbm anymore.

I'll fix this behaviour soon, however if you want to run it now you'll at least need libX11-dev, also you need to either run it with vscode, or with:
`LD_LIBRARY_PATH=$PWD/osu.Desktop/bin/Debug/netcoreapp2.1/ dotnet run --project osu.Desktop`

**Comment by jedenastka** [comment]
Closing.
