### ISSUE TITLE
Slider ticks and ends always have the same volume as the start

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3176]
In stable every part of a slider can have different volume settings, however in lazer the slider ticks, reverse arrows and the end part inherit the volume setting the first circle of the slider had. This is mostly an issue for cases where a slider end should not be emphasized but still produces a loud hitsound in lazer.

**Comment by Mahua233** [comment]
Slider ends always have the same hitsound as the start.
> https://osu.ppy.sh/beatmapsets/308485#osu/689867
this map is mixed fine in stable version osu.

**Comment by smoogipoo** [comment]
@Mahua233 can you isolate a slider which demonstrates the issue? Possibly as a timestamp into the beatmap?

**Comment by Mahua233** [comment]
@smoogipoo this map has same trouble https://osu.ppy.sh/beatmapsets/177187#osu/426550 
00:06:757(4)

**Comment by Morilli** [comment]
Alright, I tested this and apparently the volume is correct now most of the times, although there seems to be an issue with millisecond timing. Some timing points that are located at the very end of a slider don't apply their volume setting to the slider (although they do in stable), but moving this timing point one millisecond earlier resolves this issue. For example in [this map](https://drive.google.com/open?id=1K-oNy8po-YMk2sZ7r32BJJ5tAgBiYCrw), the second slider always ends with a loud hitsound, even though there is a 5% volume timing point.
