### ISSUE TITLE
The lazer icon in the Volume Mixer is huge

### ISSUE THREAD

**Issue by freeesh** [ppy/osu#3177]
If you open the volume mixer while lazer is running the icon for it will be huge.
Appears on Windows 7 x64.
I've restarted the system and it's still like that.

![image](https://user-images.githubusercontent.com/38793338/43676284-e2a989e4-97f6-11e8-80d4-0cd3e06759f7.png)

**Comment by jorolf** [comment]
Duplicate of #2424
