### ISSUE TITLE
Nightcore mod causes crackling audio

### ISSUE THREAD

**Issue by OussamaDanba** [ppy/osu#3189]
The nightcore mod produces noticeable crackling in the audio for me.
Doesn't seem to be related to any particular startup or whether I've already played other maps.

Video can be found [here](https://streamable.com/9vxgy). Cycling between normal, double time, and nightcore to show the difference. In the second part I tab out of the game to show that there it persists.

For what it's worth my audio devices are set at 48kHz (rather than the usual 44.1) so there is some upsampling but shouldn't be the cause as double time seems to have no problems.

Might be related to some of the other audio issues but I think this is specific enough to warrant an issue.

**Comment by OussamaDanba** [comment]
I can no longer reproduce this with exactly the same setup as yesterday. This might have been a bad windows boot I guess. Feel free to close if no one else can confirm.

**Comment by peppy** [comment]
Going to close for now. Please reopen if it comes up again.
