### ISSUE TITLE
Mania setting "scrolling direction" has no effect

### ISSUE THREAD

**Issue by themoonisacheese** [ppy/osu#3190]
Hi,

today i pulled and compiled a fresh copy of the repo. I hopped in mania to discover that not only mania now scrolls up by default, but that the setting in the section named "osu!mania settings" called "scrolling direction" does absolutely nothing; whether it is set to up or down has no effect, and the notes keep scrolling up, even after a restart.

running latest push as of 2018-08-07, 18:01 utc+1 on debian 9.

**Comment by Aergwyn** [comment]
This is known and already worked on as seen in #3187.

**Comment by smoogipoo** [comment]
Fixed via https://github.com/ppy/osu/pull/3187
