### ISSUE TITLE
Huh, next issue with Linux osu!

### ISSUE THREAD

**Issue by jedenastka** [ppy/osu#3191]
I succesed with building osu!lazer after [this](https://github.com/ppy/osu/issues/3173) issue. After I ran osu! for first time, tested, and exited. Now, after few hours I'm trying to run it again. But there's a problem (something with OpenGL?):

[https://pastebin.com/FXTcBn8U](https://pastebin.com/FXTcBn8U)

I tired to download and compile again, but nothing changed.

EDIT: Using Debian 9.

**Comment by fobekyo** [comment]
should be the same as #1834 , fix is included

**Comment by jedenastka** [comment]
Soo... After some rebuilds, file editing, reboots and things like this... It works. And I don't even know what was wrong. Closing.
