### ISSUE TITLE
osu!mania scrolls up despite being set to scroll down

### ISSUE THREAD

**Issue by SneverdleSnavis** [ppy/osu#3193]
After changing the setting multiple times and restarting osu!lazer twice, osu!mania continues to scroll up.

![osu lazer](https://user-images.githubusercontent.com/42214295/43847749-624e9382-9aff-11e8-9d78-b360151a8657.png)

**Comment by peppy** [comment]
This is already fixed via https://github.com/ppy/osu/pull/3187.
