### ISSUE TITLE
Song select is broken when mania is selected

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3194]
As you can see in the video ( https://streamable.com/an388 ) going through the list randomly the map info does get stuck and has some black layer over the Details section and entering a map ends in a loading-loop. The whole client laggs which doesnt go away until you restart the game

**Comment by smoogipoo** [comment]
This is mania's beatmap conversion having an infinite loop. I'll add some safety checks to prevent this, but it would be nice to have the exact beatmap which causes this - it seems to be the `On My Own (Ft Ruff Sqwad) (Part 2)` beatmap, but it looks to have been deleted from the beatmap listing as far as I'm aware.

Can you provide the .osu file? If you imported from osu!stable, it should be easy to go into the editor and save the .osu.

**Comment by Lolihunter1337** [comment]
The Map which causes it is: https://osu.ppy.sh/s/121591 The problem for me appears when a map is long like about 20mins. ( mania only )

**Comment by peppy** [comment]
This should now be fixed. Please reopen if you find it failing still.
