### ISSUE TITLE
Judgements do not scale with circle size

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3195]
The ingame judgements should scale with CS so their size fits the size of the clicked circle. Currently every judgement has the same set size which looks a bit weird for maps with high/low CS values.

**Comment by Frontear** [comment]
This definitely sounds like a good idea, especially with smaller circles. I'm curious though, couldn't it become potentially unreadable, especially by CS 7 + HR?

**Comment by Morilli** [comment]
I don't think they would get too small to become readable. Also keep in mind that judgements are supposed to give quick feedback, therefore their color is the most important part imo.

**Comment by peppy** [comment]
This is a bug.
