### ISSUE TITLE
Map settings

### ISSUE THREAD

**Issue by WebFreak001** [ppy/osu#3201]
I think a new UI for configuring maps before playing would be a cool feature to add.

Being able to change settings like:
* Playback rate (more finely controllable than DT/HT)
* AR (instead of EZ/HR which have other effects)
* HP (instead of EZ/HR which have other effects)
* OD (instead of EZ/HR which have other effects)

Changing the settings would make it unranked.

It would practically be a replacement for some mods for practicing or doing cool plays. Also open for more settings suggestions.

It could also be a place where Mods could put in settings (like FL radius, floatiness the new arrange mod which is being discussed in the PRs, hidden fade in time, etc.)

Maybe it would be placed in the beatmap settings thing at the top right corner when you start a map (where you can enable/disable storyboard, change dim, etc.)

I am considering adding it, how would such a feature be received?

**Comment by ZapTech43** [comment]
Same Like These? : 
- https://osu.ppy.sh/community/forums/topics/141204
- https://osu.ppy.sh/community/forums/topics/774895?start=6730968

**Comment by WebFreak001** [comment]
yeah pretty much like those. Before you would always create copies of the difficulties in the editor, so I think this would be useful to simply skip that step.

**Comment by jpsouzasilva** [comment]
The McOsu client has the whole beatmap configuration available even during gameplay (you press F1 and it brings up this overlay below).

![screenshot2](https://user-images.githubusercontent.com/17429390/46641182-91db0780-cb46-11e8-81c0-3eae1230f604.png)

What about creating a "Training" mod that enables this kind of panel when it's on? It could be brought up before the beatmap starts, like https://github.com/ppy/osu/blob/master/osu.Game/Screens/Play/PlayerSettings/VisualSettings.cs
