### ISSUE TITLE
osu!lazer Main Menu Bug / VGA Driver Failure 

### ISSUE THREAD

**Issue by ZapTech43** [ppy/osu#3204]
When I'm At The Main Menu And Playing Songs, Suddenly the screen goes black and became like this :

![osu_2018-08-11_09-14-44](https://user-images.githubusercontent.com/30797591/43987228-e971dde8-9d47-11e8-944d-0bc0aacd23e2.jpg)

And Then After I Changed The Music That I'm Playing (Next Music) The Screen Became Like This : 

![osu_2018-08-11_09-15-17](https://user-images.githubusercontent.com/30797591/43987238-03e5b5b4-9d48-11e8-9eef-169d85d9dc15.jpg)

And Then, After That NVIDIA Driver Failure Came : 

![bug](https://user-images.githubusercontent.com/30797591/43987246-1cff0fd2-9d48-11e8-8c7c-f5aa7925b920.jpg)

This Is The Problem Event Signature :
  Problem Event Name :	CLR20r3
  Problem Signature 01:	osu!.exe
  Problem Signature 02:	2018.722.0.0
  Problem Signature 03:	f96b96ee
  Problem Signature 04:	osu.Framework
  Problem Signature 05:	2018.721.0.0
  Problem Signature 06:	cf3d9a02
  Problem Signature 07:	1f8
  Problem Signature 08:	32
  Problem Signature 09:	System.InvalidOperationException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	65a2
  Additional Information 2:	65a2168c2f6320fa16fdb8a1bc2ab95e
  Additional Information 3:	5ad6
  Additional Information 4:	5ad65ecb8bdbf5fd3e8487105f94bf9d

Is The Problem From the Game / My Driver, Thanks!

**Comment by smoogipoo** [comment]
Post the runtime.log file found in the osu! folder (settings -> "open osu! folder" ingame)

**Comment by ZapTech43** [comment]
@smoogipoo Unfortunately, I Can't Because It Was Using A Computer That I Rent on A Internet Cafe 😢 
But Before the bug is happening, it was so laggy and at the song select menu i switch up songs really fast then go back to the menu and skipped the playing song, May It'll Reproduce The Bug 😄.

**Comment by ZapTech43** [comment]
> Do you know how much vRAM the PC had, out of curiosity?

Sorry for replying it now, it's been a year... And i haven't opened my GitHub for a long time..

The VRAM is around 1gb i'm not sure since its a Computer on an Internet caffee

**Comment by peppy** [comment]
Going to close this one. It is either already resolved by various fixes to issues like this, or will be resolved with compatibility mode / directx support.
