### ISSUE TITLE
[Suggestion] Add Option To Disable Animations

### ISSUE THREAD

**Issue by ZapTech43** [ppy/osu#3205]
Dear Peppy,

I Have An Idea, Because osu!lazer is too Big & Advanced Graphics Is Everywhere
Why Don't add an option to disable the triangles animation that are moving in The osu! Logo, Difficulty Select, osu!direct Menu & etc.

Why? Because May It Occurs Lag for Med-Spec Players that the PC Are Not Powerful Enough To Execute the Animation, And May It Can Decreases The Drop Frames & Lag While Playing Or When Waiting At The Menu.

~Sincerely, T4Z3R

**Comment by peppy** [comment]
It’s not the triangles. Further optimisations will come in time. Please be patient.
