### ISSUE TITLE
Circles that stack on each other looks like just one circle.

### ISSUE THREAD

**Issue by toiglak** [ppy/osu#3207]
Example:
![hard to read overlapping circles](https://user-images.githubusercontent.com/37531387/44001475-532051f2-9e33-11e8-8882-a3bed43783fe.png)

2 and 3 circles are stacking, but they're not as noticeable as they should be. They look like just one circle because of pure white borders. In faster maps I find reading this pattern really demanding. I suggest adding a slight shadow under the circle to exhibit those two circles.

**Comment by Morilli** [comment]
I have noticed this before, and I think the large white border plays a large role in this. If it were thinner the second circle could be distinguished from the first one.

**Comment by H1ROYUKII** [comment]
I think they did this intentionally

**Comment by peppy** [comment]
There should be a gap here. Which beatmap are you seeing this on?

**Comment by ToIGLAK** [comment]
https://osu.ppy.sh/beatmapsets/39804/#osu/129891 FOUR DIMENSIONS

At:
01:48:514 (4) -
01:49:189 (2,3,4) - 
01:49:594 (6,7) - 
01:49:796 (8,9) - 
and so on.

**Comment by peppy** [comment]
Have looked into this and it is indeed still an issue. Can be avoided by adjusting the RingPiece border size down by one pixel (without too many visible side effects) but internally debating whether we should do that. @smoogipoo thoughts?

![image](https://user-images.githubusercontent.com/191335/95075938-0522ae80-074c-11eb-8b84-c7fa73159ed5.png)

![image](https://user-images.githubusercontent.com/191335/95075972-15d32480-074c-11eb-83b8-6f72256c8959.png)

Note noticeable even without adjusting sliders' radius (which seems to be specified in a very different way .. to the point I don't really want to touch it).

**Comment by smoogipoo** [comment]
I think that sounds fine? If anything the slider borders in your SS look a lot closer to the ring size in the OP.

**Comment by peppy** [comment]
you... might be right. at some point we probably need to get both of those specified in the same coordinate space.
