### ISSUE TITLE
Proposal: Creating your own playfield

### ISSUE THREAD

**Issue by toiglak** [ppy/osu#3208]
While playing osu! I don't want to be distracted by stuff like HP bar, accuracy and score, but having combo toggled (so you can tell did you break combo) would be awesome. Also turning off all objects might not be the best option (Shift+Tab). I had the idea of creating in the options menu list of playfield's stuff to turn on/off.

Here's an example:
![concept](https://user-images.githubusercontent.com/37531387/44002162-dcf04954-9e3e-11e8-9049-acb875eea54e.png)

And some variations of it:
![acc score](https://user-images.githubusercontent.com/37531387/44002181-07c9a5bc-9e3f-11e8-8791-a80320d758ed.png)
![acc combo passed remain](https://user-images.githubusercontent.com/37531387/44002248-25a4c336-9e40-11e8-9469-db1e70323195.png)
![acc passed remain](https://user-images.githubusercontent.com/37531387/44002178-038b575c-9e3f-11e8-9c4d-c7414c1c2059.png)
![acc progress](https://user-images.githubusercontent.com/37531387/44002180-056b78ae-9e3f-11e8-96cf-64f864996ae5.png)

Also allowing to edit placement of object (e.g., combo) on playfield would be even more cool!

PS. I'm not a designer :P

**Comment by stanriders** [comment]
Pretty sure thats already planned in skins

**Comment by ToIGLAK** [comment]
Like in skin.ini? That would be much more frustrating to edit placement of objects every time you want
Could you sent me this milestone so i can check it?

**Comment by peppy** [comment]
This is the eventual plan, at a per-skin level. We don't have a completed design for the skin setup screen, but if you are interested in implementing it please say so and we will provide it.

**Comment by ToIGLAK** [comment]
I would highly appreciate that addition!

**Comment by peppy** [comment]
This is now possible with the skin editor.
