### ISSUE TITLE
Proposal: Adding support for media buttons on keyboard to controll music

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#3213]
<miss click on enter>
Controlling music in osu! by using these keys:

![media](https://user-images.githubusercontent.com/37531387/44024057-7dde6be0-9eec-11e8-9d52-d9fee4a9cc10.jpg)

**Comment by coldrage101** [comment]
In Stable you can use the Z, X, C and V keys, along with the F1 to F5 keys to control the currently playing song on the main menu. This is very convenient if you are like me and use osu! as your music player.

**Comment by coldrage101** [comment]
On laptop keyboards it is uncommon to see media keys, so I think dual bindings would be more optimal as the default.

**Comment by iiSaLMaN** [comment]
> In Stable you can use the Z, X, C and V keys, along with the F1 to F5 keys to control the currently playing song on the main menu. This is very convenient if you are like me and use osu! as your music player.

> On laptop keyboards it is uncommon to see media keys, so I think dual bindings would be more optimal as the default.

First of all, this is something you should say at the PR to notify the developer solving this #5268, second of all, it's already implemented as suggested by someone else, check the PR for more information.
