### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by WithoutKnock** [ppy/osu#3214]
Is this normal?

![unbenannt](https://user-images.githubusercontent.com/41303944/44027768-f1cba51c-9ef7-11e8-93ba-fcad941c5280.PNG)

**Comment by WithoutKnock** [comment]
should I just delete it or what?

**Comment by WithoutKnock** [comment]
Ok just deleted it. (I was a bit confused)

**Comment by VPeruS** [comment]
You need to read about github and git basics. https://guides.github.com/
