### ISSUE TITLE
Autoplay issue on one map

### ISSUE THREAD

**Issue by H1ROYUKII** [ppy/osu#3216]
So, I wanted to see how this map [](https://osu.ppy.sh/beatmapsets/150945#osu/372245) looked on osu lazer, it worked perfectly in the stable build (granted no human can play it, only the auto bot can) And so I booted up this map, it startedout fine, with just this long spinner, as the map doeson the stable build. the problem arises as soon as the circles appear, this map has a high circle dencity, and I don't expect osu lazer to have it completely perfect yet, so when it was choppy and I couldnt see the visualization I was looking for, I was dissapointed, but not supprised. the thing I find weird was at the end of the map for a couple of minuted it just kept looping a hitsound over and over, eventually it stoped and I was able to go back to the menu, however when I did the hitsound came back and all the audio was choppy and weird. I have no clue what caused this, and I hope this helps with development, good luck to the people developing this, I hope it isnt too  stressful.

**Comment by Joehuu** [comment]
Centipede performance was improved in https://github.com/ppy/osu/pull/7967 and https://github.com/ppy/osu/pull/7968 to the point it doesn't become choppy. Still low fps but performance is a constant work in progress, so closing as resolved.
