### ISSUE TITLE
Crash on startUp

### ISSUE THREAD

**Issue by K-osA** [ppy/osu#3226]
When I first started osulazer, it shows up a black screen and suddenly shutdown itself. From now on, No response running osulazer. I'm using Windows 10, GTX 1060 Graphic card(driver downloaded) and 16GB RAM.

Here are the log files:
[performance.log](https://github.com/ppy/osu/files/2287015/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2287016/runtime.log)

And event logs:
[error.txt](https://github.com/ppy/osu/files/2287017/error.txt)

**Comment by MTGPROD** [comment]
Change de carte mère 
Change d'ordinateur 
ou attend ATTEND

**Comment by K-osA** [comment]
My computer is a laptop. (MSI GP72MVR 7RFX Leopard Pro)

**Comment by peppy** [comment]
osu! cannot locate your graphics card, it would seem. do you happen to have two gpus in the machine?

**Comment by K-osA** [comment]
Yes, Intel(R) HD Graphics 630/NVIDIA GeForce GTX 1060.

**Comment by K-osA** [comment]
Resolved.
