### ISSUE TITLE
osu!lazer has some trouble understanding "CMYKA" color model

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#3228]
In this map: https://osu.ppy.sh/beatmapsets/712125#osu/1505448 background is saved in "CMYKA" color model and to be more accurate: 
![acc](https://user-images.githubusercontent.com/37531387/44096553-d5283562-9fdb-11e8-80e8-4cb69a0b9e6c.jpg)

Because of that image looks strange. After converting it to "RGB" everything looks fine:
![difference](https://user-images.githubusercontent.com/37531387/44096891-ac10f064-9fdc-11e8-9bb8-69f4b37e0186.png)

**Comment by peppy** [comment]
support for anything non-rgb is not required. this beatmap should be fixed.
