### ISSUE TITLE
Building osu! on Linux (warning as error)

### ISSUE THREAD

**Issue by TiberiumPY** [ppy/osu#323]
> Platform/Windows/WindowsGameWindow.cs(39,21): error CS0219: Warning as Error: The variable `errorCode' is assigned but its value is never used

> CSC: error CS2001: Source file `Overlays/Options/OptionDropDown.cs' could not be found

Maybe just disable warnings as errors or fix this?

**Comment by kj415j45** [comment]
It's still coding ,so sometimes build failed

If you want a build passing version,run xbuild in branch `release`

**Comment by TiberiumPY** [comment]
@kj415j45 yeah, I know, but release version is 2 months old :)

**Comment by kj415j45** [comment]
I've forgot the last build passing's commit :D

**Comment by TiberiumPY** [comment]
@kj415j45 ok, https://github.com/ppy/osu/pull/324 is changing name.

**Comment by TiberiumPY** [comment]
@kj415j45 pls give it to me

**Comment by kj415j45** [comment]
don't use at so frequently.
just reply is ok
I'm watching this repo

**Comment by Tom94** [comment]
Fix it yourself and make a PR or wait. This is not appropriate for an issue. Read the message shown to you before opening an issue.
