### ISSUE TITLE
Screenshot doesn't work in macOS

### ISSUE THREAD

**Issue by 45gfg9** [ppy/osu#3242]
OS: macOS 10.13.6 (High Sierra)
osu!: 2018.816.1

<img width="2048" alt="2018-08-17 11 55 17" src="https://user-images.githubusercontent.com/37043529/44247080-7887a000-a214-11e8-8ee4-3a963072555c.png">
This is what happens when I press F12 to take screenshot. (This one was taken by Cmd+Shift+3)

(BTW where are the screenshot and logs folders? Thanks.)

**Comment by peppy** [comment]
Sentry issue: [OSU-LAZER-2H](https://sentry.io/ppy/osu-lazer/issues/650529379/)

Requires code updated to use `ImageSharp` rather than `System.Drawing`
