### ISSUE TITLE
Proposal: Faster rotating and scaling objects in editor.

### ISSUE THREAD

**Issue by toiglak** [ppy/osu#3247]
Today I was doing something in Affinity (Photoshop replacement) and then it got me. Why I can't rotate object in osu! by simply dragging cursor!
![affinity-rotating](https://user-images.githubusercontent.com/37531387/44266935-aa0c6580-a22c-11e8-95f9-9210e9ad6211.gif)

I think this option would fit perfectly with that boxes around circles and sliders that were added to lazer editor.
My concept is about adding small draggable circle above slider box and selected objects box. 
Also scaling objects this way would be awesome. 
Visualisation:
![slider](https://user-images.githubusercontent.com/37531387/44267598-30c24200-a22f-11e8-8a7b-2f36583211c1.png)
![objects](https://user-images.githubusercontent.com/37531387/44267599-30c24200-a22f-11e8-8b4e-c77b0ddc835b.png)

And yes, I know that there are two ways of rotating (by origin).

**Comment by smoogipoo** [comment]
This is planned.
