### ISSUE TITLE
Only part of the storyboard is working

### ISSUE THREAD

**Issue by LovelyA72** [ppy/osu#3249]
The map was https://osu.ppy.sh/beatmapsets/154470#osu/728746
It works as expected on osu!stable.
Here is a video demo of the issue. Subtitles are made for real-time description. 
https://www.youtube.com/watch?v=rS3VFMa80pE

**Comment by Wieku** [comment]
I've found what happens. Paths don't get standardized while uploading to BeatmapSetFileInfo table. Storyboard sprites use standardized paths. "SB\alien.png" is not the same as "SB/alien.png", so sprite loading is cancelled: https://img.wieku.me/18/DB%20Browser%20for%20SQLite_2018-09-08_03-08-30.png

**Comment by LovelyA72** [comment]
I don't think that's the problem.
545737 REOL - YoiYoi Kokon stores all if it's sb assets in BG folder but still displays nothing.
![image](https://user-images.githubusercontent.com/29054052/45252522-8bb9f700-b30c-11e8-8d53-4da25d2e7448.png)

**Comment by Wieku** [comment]
@LovelyA72 Are you [sure](https://img.wieku.me/18/7zFM_2018-09-08_12-05-54.png)?

**Comment by LovelyA72** [comment]
sorry, not BG, it's SB. Typo...
And that does not work for me...

**Comment by e8035669** [comment]
My computer has two OS.
storyboard not working in Windows, but all working in Ubuntu.

**Comment by Wieku** [comment]
@e8035669 It's because that linux uses slash (/) so PathStandardize does nothing and all filenames are compared properly. If you replace windows database with linux one it will also work.

**Comment by LovelyA72** [comment]
Tried on ubuntu 18.04(unity desktop). the storyboard doesn't have any issue. So I also believe this causes by file path separater in the database.
