### ISSUE TITLE
Mania 10K maps can't be played

### ISSUE THREAD

**Issue by ghost** [ppy/osu#3251]
osu!lazer 2018.817.0
OS : Windows 7

When you start a mania 10K map, an error occurs and loading stops.
https://osu.ppy.sh/s/332673
https://osu.ppy.sh/s/351167
https://osu.ppy.sh/s/330793

Proposal : Change mania 5K Co-op to general 10K mode like mania 9K. It's fun and intuitive enough to the existing mania players. There are many 10K players in osu already.

**Comment by CraDow** [comment]
By the way, this was already a request in old feature request server: https://osu.ppy.sh/forum/t/379786
In main osu client 10k is still playable by making the skin SplitStages: 0 and changing the 5kcoop layout to something usable.
5k-coop or 5k+5k skin is not used by anyone I know, who plays mania with 10 keys plays it single player, therefore I think lazer should have 10k and 5k+5k as separate keycounts/manias submodes: 10K for single player and 5k+5k to play while cooperating with another player, but remember most players play 10K (single player).
Lazer currently doesn't have a way to bind 10K (single player) nor 10K skin.

**Comment by smoogipoo** [comment]
Closing because the original issue has been fixed. The recent issue is addressed in https://github.com/ppy/osu/issues/8723
