### ISSUE TITLE
Add Linux requirements to "Requirements" chapter in README.md

### ISSUE THREAD

**Issue by ZeroAurora** [ppy/osu#3257]
When running osu!lazer on Linux, there must be BASS(`libbass.so`) and BASS FX(`libbass_fx.so`) in `/usr/lib64`(for 32-bit system, the path should be `/usr/lib`), or the game will crash and exit when starting.

The BASS's and BASS FX's archive can be downloaded from [Un4seen](http://www.un4seen.com/bass.html). The `libbass.so`(or `libbass_fx.so`) lives in `x64/` directory in 64-bit system or in the root directory of the archive in 32-bit system.

I've looked in the package manager in my system(Fedora 28), but I didn't find anything about "bass" or "bassfx".

BTW, I'm sorry for my bad English because English is not my native language.

**Comment by LastExceed** [comment]
This problem has been addressed before. Unfortunately I can't find the particular issue where it was mentioned (as there have been lots of issues and PRs for problems with the BASS library on linux), but the closing note was that this problem won't occur when osu! is published as a self-contained program and therefore won't be addressed any further, so this issue can be closed.

**Comment by morguldir** [comment]
You can't package it anyway because of how un4seen manages the releases.

Also, if we do what is suggestd in https://github.com/ppy/osu-framework/issues/1638, this issue will be fixed.
