### ISSUE TITLE
Importing beatmaps before entering song select throws an error on enter

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3259]
If beatmap importing is started before entering song select, and the process hasn't finished when song selection is entered, osu!lazer will throw an error and stop the importing process. This error will continue on showing up every time song select is entered until osu!lazer is restarted.
Video: https://streamable.com/0wjqi

**Comment by peppy** [comment]
Please include `runtime.log`

**Comment by Morilli** [comment]
Here you go [runtime.log](https://github.com/ppy/osu/files/2302920/runtime.log)

**Comment by Morilli** [comment]
I can no longer reproduce this very issue on the current release, so I'm gonna consider this issue fixed for now.
