### ISSUE TITLE
osu!lazer won't unload from RAM

### ISSUE THREAD

**Issue by Krper1111** [ppy/osu#3269]
So, I closed the game and then opened Task Manager. And I saw 2(then I reopened osu again) osu.exe processes. I've tried to kill the process, but it still here. Why? Windows 7.
![2018-08-21_16-54-19](https://user-images.githubusercontent.com/31844440/44405859-f58f7e00-a562-11e8-9fa1-ce1301d55a35.png)

**Comment by peppy** [comment]
Does this happen every time?

**Comment by Krper1111** [comment]
Yes

**Comment by peppy** [comment]
Does it happen after a restart? Could you please re-test on the latest build?

**Comment by Krper1111** [comment]
It works fine on the latest build. Maybe, that was human factor or incomparability of older(July) and latest(Aug) builds. Anyway, it seems to be fixed. (for some reason, I want to apologize)

**Comment by peppy** [comment]
We made a huge number of fixes and threading changes, so there's a high possibility something we did caused it to resolve. Thanks for confirming!
