### ISSUE TITLE
Some characters and icons are not displayed

### ISSUE THREAD

**Issue by kawaemon** [ppy/osu#3277]
Maybe this problem is same as "No text is displayed #2297"..
Characters that are not displayed seem to be random.
Using Windows10, .NET SDK 2.1.401, and Osu!lazer 2018.821.0

![Song select screen](https://user-images.githubusercontent.com/34652535/44440622-e44a7e00-a603-11e8-86f3-b5a0fb43af3c.png)

![Screen at startup](https://user-images.githubusercontent.com/34652535/44440710-502ce680-a604-11e8-8b2c-d4f80f8c468d.png)

**Comment by peppy** [comment]
Is there anything weird in `runtime.log`? First thought is saturated GPU memory (could you include your GPU model?)

**Comment by kawaemon** [comment]
Sorry for my late reply. 
My GPU is GTX980TI (RAM 6GB).
runtime.log is here.
![untitled](https://user-images.githubusercontent.com/34652535/45586517-92132900-b933-11e8-96f6-2bacb836e58a.png)
and this is screenshot of task manager while running osu lazer.
![screenshot 17](https://user-images.githubusercontent.com/34652535/45586606-07cbc480-b935-11e8-96f9-74ea30aca21d.png)

Thank you for support.

**Comment by peppy** [comment]
🤞 please reopen if this still occurs after the next release
