### ISSUE TITLE
osu!lazer deletes shortcuts after updating - still occurs - 30.08.2018

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#3290]
osu!lazer deletes shortcuts from menu start and desktop after updating. Also lazer is not auto opening itself after that. This bug happens every time I update it. 

You can see all this stuff in this vid (new):
https://www.youtube.com/watch?v=D4_JMHSph74&feature=youtu.be

**Comment by ToIGLAK** [comment]
I read that some changes were made to ose framework that started causing all those bugs.
Closed.

**Comment by peppy** [comment]
A fix for this is just to run the jnstaller once
