### ISSUE TITLE
VSync Issue in Windows 10

### ISSUE THREAD

**Issue by RedErick2903** [ppy/osu#3301]
I updated osu!lazer to version 2018.822.0 and when I started the game, I had 1 fps(draw) constantly and that was because the game finds vsync as infinite hz instead of 60 in my case. After I managed to get to the settings and set the frame rate at 2x refresh rate everything was fine and it said 120hz draw. There were no errors shown anywhere on the screen when I launched it or anything like that. If you need a log I will try to get one.

**Comment by peppy** [comment]
That's actually how vsync works - your graphics card becomes responsible for the vertical sync. Could you please include runtime.log so we can check your hardware setup?

**Comment by RedErick2903** [comment]
sure
[runtime.log](https://github.com/ppy/osu/files/2314476/runtime.log)

also I meant that only in the latest version of osu!lazer it happens that vsync makes my game go only 1 fps and I tried reversing to a older version (2018.705.0) and the game was running fine with vsync.

**Comment by RedErick2903** [comment]
Issue got fixed with version 2018.830.0 somehow.
