### ISSUE TITLE
In-Song Scores not working correctly

### ISSUE THREAD

**Issue by AN0NISN4P** [ppy/osu#3302]
When clicking on a circle you get the "Great", "Good" or "Meh" text showing, I noticed that neither "Great" or "Good" had the "G" in the words, so it shows as "reat" and "ood"

![ezgif com-crop](https://user-images.githubusercontent.com/42655737/44548679-156ba100-a71f-11e8-969c-0ba83860f575.gif)

**Comment by smoogipoo** [comment]
Can you confirm whether this is still happening?

**Comment by AN0NISN4P** [comment]
Just reinstalled the osu!lazer client and it seems, that the bug still exists

**Comment by peppy** [comment]
Likely framework level, GPU memory consumption, texture atlas handling.

**Comment by Joehuu** [comment]
Does this still happen @AN0NISN4P?

**Comment by peppy** [comment]
I'm 99.99% sure we solved this (was a race condition issue with atlasing code). @smoogipoo confirm?

**Comment by smoogipoo** [comment]
Maybe but it’s been so long I can’t confirm

**Comment by peppy** [comment]
Going to close this for now then. @AN0NISN4P please comment if you are still able to reproduce this issue.
