### ISSUE TITLE
Game freezes after clicking Solo

### ISSUE THREAD

**Issue by segalll** [ppy/osu#3303]
I have something around 60000 total difficulties, and the game freezes when I click solo to play. I assume it has to do with the amount of songs causing a lot of lag to the game. Maybe optimization is necessary?

**Comment by segalll** [comment]
It loads eventually, but the song selection screen is very laggy and even after exiting the song select screen, it remains laggy.

**Comment by peppy** [comment]
This is a known issue.

**Comment by segalll** [comment]
Oh. Apologies for bringing it up again.

**Comment by peppy** [comment]
Things should now be considerably better. Could you please report back on how it's looking compared to 14 days ago?

**Comment by peppy** [comment]
Thanks for the update.

**Comment by segalll** [comment]
It has been a long time since the previous update, so I thought I should update again. As of 2018.1108.0, it takes approximately 2 minutes to load the song select screen after clicking Solo. At which point, gameplay and song select screen suffer significant lag. After waiting a minute or two, everything seems to smooth out. At that point, it behaves just like stable. Must be loading all my maps I guess.

**Comment by peppy** [comment]
We’re quite aware of these issues. Thanks for the update. I believe we’ll have a chance to look into this in the coming months.

**Comment by Joehuu** [comment]
@segalll do you still have this issue?

I think entering song select lag is fixed in #5371?

**Comment by peppy** [comment]
This should be resolved, yes.
