### ISSUE TITLE
Lazer stutters and has increases audio offset after watching auto play

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3314]
I have noticed this issue in the past, and now I found a very simple way to reproduce it. Turning on auto play and watching a single play through of the map https://osu.ppy.sh/b/894090&m=0 kinda bugs out the game for me, in that the ingame audio offset is wrong, even though the setting itself wasn't changed (only for one session though) and lazer may randomly start stuttering.
Video showing the issue: https://streamable.com/thx2j (stutter starts at 7:20)
Log files from that session: [logs stutter + offset.zip](https://github.com/ppy/osu/files/2319090/logs.stutter.%2B.offset.zip) (even though I don't think there is much useful information in there regarding this issue)

**Comment by peppy** [comment]
Does this still occur?

**Comment by Morilli** [comment]
Couldn't reproduce in the slightest anymore, so I'm gonna say no.
