### ISSUE TITLE
Wrong beatmap hitsounds are played, sliders are silent

### ISSUE THREAD

**Issue by Wieku** [ppy/osu#3315]
This [beatmap](https://osu.ppy.sh/beatmapsets/197747#osu/468997) has some problems with custom hitsounds. Sliders don't emit any sound, circles work fine till 3/4 of the map, then sample sets get messed up.

[How it should sound](https://youtu.be/z0DrfAUe5uo?t=2m)
[How it actually sounds](https://youtu.be/pohSqVGtM4o?t=1m47s)

It happens on the latest (2018.824.0) release.

**Comment by Ephemeralis** [comment]
Same issue very visible on [this beatmap](https://osu.ppy.sh/beatmapsets/56847/#osu/171678) as it uses sliderend/starts to maintain a snare pattern throughout.
