### ISSUE TITLE
Error during updating

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3317]
i think that can help with some other problems too:

![osu_2018-08-25_19-23-52](https://user-images.githubusercontent.com/32620809/44620975-563df400-a89e-11e8-82c9-85faf3b17452.jpg)
![osu_2018-08-25_19-23-53](https://user-images.githubusercontent.com/32620809/44620976-56d68a80-a89e-11e8-8eac-9f3d0c8bc70b.jpg)
![osu_2018-08-25_19-23-55](https://user-images.githubusercontent.com/32620809/44620977-56d68a80-a89e-11e8-8d41-c20c522d7820.jpg)

logs:
[database.log](https://github.com/ppy/osu/files/2320893/database.log)
[network.log](https://github.com/ppy/osu/files/2320894/network.log)
[performance.log](https://github.com/ppy/osu/files/2320895/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2320901/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2320905/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2320898/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2320906/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2320900/runtime.log)

**Comment by ticotaco72** [comment]
updating from 2018.808.0
and downloaing update is stuck after this error

**Comment by peppy** [comment]
Could you confirm that the update does still download? It should fall back to a non-delta update method.

**Comment by ticotaco72** [comment]
runned 2018.816.0
delta patching failed
download is stack
![osu_2018-09-20_20-35-21](https://user-images.githubusercontent.com/32620809/45840490-50a9c180-bd17-11e8-8a2c-7838ed07084f.jpg)
[database.log](https://github.com/ppy/osu/files/2402669/database.log)
[performance.log](https://github.com/ppy/osu/files/2402670/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2402671/runtime.log)
[SquirrelSetup.log](https://github.com/ppy/osu/files/2402673/SquirrelSetup.log)
[SquirrelSetup.log](https://github.com/ppy/osu/files/2402676/SquirrelSetup.log)

**Comment by Joehuu** [comment]
I think the delta patching errors are resolved?

**Comment by peppy** [comment]
Have not seen this happen recently. Will close for now.
