### ISSUE TITLE
Is the judgement of osu!lazer Spinner the same as that of osu! Spinner?

### ISSUE THREAD

**Issue by MikiraSora** [ppy/osu#3322]
Hey I wanna make a replay tool which can able to analyse replay file .So I have to simulate object hitting and I get a trouble that I dont know what's Spinner judgement&rules&implements.
Thus I just ask for if osu!lazer has implemented Spinner(even it's same as old osu!) or others about old osu! Spinner.

**Comment by peppy** [comment]
The spinner algorithm in stable is very hard to reproduce. I don't believe we are going for 1:1 behaviour, but rather something more reproducible in replays.
