### ISSUE TITLE
Game not launching at all on Windows 10

### ISSUE THREAD

**Issue by jmontineri** [ppy/osu#3323]
The game is not launching at all. Running the executable file (or "dotnet osu!.dll" in the game folder) leads to nothing appearing, compiling and running from source through Visual Studio leads to dotnet.exe exiting with an Access Violation error. No log files are created anywhere.

Using .NET Core SDK and Runtime 2.1.3 on latest Windows 10.

**Comment by peppy** [comment]
Have you tried using the installer?

**Comment by jmontineri** [comment]
Yes. The installer ran fine and installed the game, and then the game doesn't run. I'm assuming it crashes in the same way as when I'm building it from source.

I tried debugging it further, and it seems to crash when creating the game host, at line 25 of Program.cs in osu.Desktop. I do not have the source for osu!framework (haven't had much time to work on getting it running recently) so I can't trace it back further, though I'll try to get more information when I can.

It runs fine on my laptop, so I'm guessing something about the setup on my desktop is causing the issue.

**Comment by peppy** [comment]
Could you check event viewer for any crash logs related to the osu! or dotnet processes?

**Comment by jmontineri** [comment]
I just checked the event log. There is in fact an Application Error related to osu! in there.

```
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5b36971d
Faulting module name: ntdll.dll, version: 10.0.17134.228, time stamp: 0x6d15b6d7
Exception code: 0xc0000005
Fault offset: 0x00000000000068fc
Faulting process id: 0x6f0c
Faulting application start time: 0x01d44a352bc85c72
Faulting application path: C:\Users\jmont\AppData\Local\osulazer\app-2018.824.0\osu!.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 9ee7ea38-f697-4be3-9c28-6e6e82399542
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by peppy** [comment]
Is there any further content to that error?

**Comment by peppy** [comment]
Unfortunately that doesn't give us much to work with. I'd be curious to see the debug output when you said you got stuck on line 25 of `Program.cs`. You may actually get closer to the error if you try running the VisualTests project on [osu-framework](https://github.com/ppy/osu-framework) instead, since it looks to be dying before it hits game code.

**Comment by jmontineri** [comment]
I'll do that and get back to you.

**Comment by jmontineri** [comment]
The osu-framework test runner runs the 226 first tests, and then aborts for no reason.

```
[9/11/2018 9:46:27 PM Informational] ------ Run test started ------
[9/11/2018 9:46:28 PM Informational] NUnit Adapter 3.10.0.21: Test execution started
[9/11/2018 9:46:28 PM Informational] Running all tests in C:\Users\jmont\Source\Repos\osu-framework\osu.Framework.Tests\bin\Debug\netcoreapp2.1\osu.Framework.Tests.dll
[9/11/2018 9:46:28 PM Informational] NUnit3TestExecutor converted 487 of 487 NUnit test cases
[9/11/2018 9:46:31 PM Error] The active test run was aborted. Reason: 
[9/11/2018 9:46:31 PM Informational] ========== Run test finished: 226 run (0:00:03.7879999) ==========
```

**Comment by peppy** [comment]
If you set the startup project to `VisualTests` and run in debug, you might get something more helpful (as opposed tor running tests directly).

**Comment by jmontineri** [comment]
Alright - stepping through VisualTests, it seems like line 167 in GameHost.cs, in osu!framework, is crashing when trying to initialize OpenTK. It simply exits with an access violation that Visual Studio doesn't catch.

**Comment by peppy** [comment]
Can you provide screenshots or error text verbatim? It sounds like this should contain something useful for us to help you resolve the issue. Anything will help.

**Comment by jmontineri** [comment]
There is no error text, aside from the not-very-useful `The program '[12440] dotnet.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.` which appears when trying to progress past line 167 in any way. I can try to find a way to debug into OpenTK to narrow it down even further if that could help. The most useful screenshot I could provide is a blank console window running dotnet.exe.

**Comment by jmontineri** [comment]
When stepping through OpenTK's code, the crash seems to occur when checking whether EGL is supported. It sounds like an issue with OpenTK and my machine rather than an issue with osu!framework.

**Comment by boswelja** [comment]
Whenever I clone the source and try to run osu.Desktop nothing happens for me either, I've found switching to .NET Core 3.0 fixes it, not sure if it's related to this specific issue though

**Comment by peppy** [comment]
If you're not seeing an error, it could be that you have another instance of osu! running?

**Comment by boswelja** [comment]
I'll have to double check for a rogue instance running in the background, but I don't think thats it. Does this project normally depend on .NET Core 3? Every time I clone the source it also seems to default to 2.X

**Comment by peppy** [comment]
we do not officially support 3 yet.

**Comment by boswelja** [comment]
![image](https://user-images.githubusercontent.com/15526339/62920431-da63f100-bdf9-11e9-818e-e1b706a7c11a.png)
Project defaulted to .NET Core 2.2, tried running but got no window and this message along with a non-zero exit code

**Comment by boswelja** [comment]
Just tried with .NET Core 2.1, which worked fine. I suspect something is wrong with my 2.2 install

**Comment by Joehuu** [comment]
Closing as stale (installer/running from source shouldn't be causing any problems at this point, at least on Windows 10).
