### ISSUE TITLE
Game sometimes gives a rating screen, and sometimes not.

### ISSUE THREAD

**Issue by Skylius** [ppy/osu#3324]
Usually I never get one on really old maps. (Such as Unknown Orchestra mapped by Lumino)
I mean the game literally soft locks, to the point to where I have to exit to menu. I waited for a menu for a good minute to see if it wasn't just some growing pains of Laser.... but...

**Comment by peppy** [comment]
Which ruleset were you playing on when you experience this?

**Comment by Skylius** [comment]
Uhm, sorry for the late reply peppy, I don't get what you mean by ruleset, I just booted the game up and went to play Hard on various maps.

**Comment by Aergwyn** [comment]
`Ruleset` is the gamemode you're playing in. Standard, Mania, Taiko or Catch.

**Comment by welsar55** [comment]
I have been unable to replicate the issue. I have attempted to do it both logged into a user account and on guest. With autoplay and without autoplay. I have tried this this on the easy, normal and hard difficulty of Unknown Orchestra.

**Comment by peppy** [comment]
I believe this has since been fixed.
