### ISSUE TITLE
Polish keyboard input (IME) doesn't work

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3326]
When you're typing polish letters any new letters aren't showing, when you paste them it works.

logs:
[database.log](https://github.com/ppy/osu/files/2329044/database.log)
[network.log](https://github.com/ppy/osu/files/2329045/network.log)
[performance.log](https://github.com/ppy/osu/files/2329046/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2329047/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2329048/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2329049/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2329051/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2329052/runtime.log)

**Comment by ticotaco72** [comment]
1. When you try to write `ó` settings overlay opens
2. When you write some polish letters, then some standard english letter then: appear those letters that you have typed and this normal one but some of these polish is changed for non standard characters like `³` (when you're typin `ł`)
3. When you type polish letters and no one english after them, then they won't appear in textbox

**Comment by AtomCrafty** [comment]
opentk/opentk#269
opentk/opentk#666
opentk/opentk#758

**Comment by peppy** [comment]
@ticotaco72 can you test this on the latest release? we have far better IME support now.

**Comment by ticotaco72** [comment]
> 1. When you try to write `ó` settings overlay opens
> 
>     2. When you write some polish letters, then some standard english letter then: appear those letters that you have typed and this normal one but some of these polish is changed for non standard characters like `³` (when you're typing `ł`)
> 
>     3. When you type polish letters and no one english after them, then they won't appear in textbox

Tested anyway and on latest version on Windows points 1. And 2. seem to be resolved.
Point 3. is still unresolved. Pasting still works.

**Comment by smoogipoo** [comment]
Should be fixed via https://github.com/ppy/osu-framework/pull/4985
