### ISSUE TITLE
borderless mode is incorrectly positioned under multiple monitors

### ISSUE THREAD

**Issue by koukuko** [ppy/osu#3329]
this happens when my taskbar is on the left side.

- version: osu!lazer 2018.824.0
- screenshot
![qx780 kzf si9yc403b_mo](https://user-images.githubusercontent.com/3916013/44768760-f2187a00-ab94-11e8-87fa-65582467d022.png)

**Comment by peppy** [comment]
See https://github.com/ppy/osu-framework/issues/1833.
