### ISSUE TITLE
Reduce RAM consumption by unloading the not present components

### ISSUE THREAD

**Issue by Peaceultime** [ppy/osu#3336]
I was testing a couple of things on the code of osu!lazer and I realized by looking at the visual studio diagnostics tools that the game keep loading things and never unload them. As a example, look at the BeatmapCarousel, the game keep the background image for each BeatmapSet. So, in my case, I can go up to 4 Go of RAM consumption in the MainMenu when I loaded all the background images. I suggest to unload the background images like in the actual osu!

**Comment by peppy** [comment]
They are already unloaded. What you are seeing is .net holding on to ram because it can

**Comment by peppy** [comment]
This has since been heavily optimised via #3370. Now panels are unloaded even while still at song select.

Alongside this, multiple reference leaks were fixed which could cause memory to take much longer to free up than expected (after exiting song select), which is what you originally reported.
