### ISSUE TITLE
setup error? & can't run latest osu!lazer

### ISSUE THREAD

**Issue by AimsterZ** [ppy/osu#3337]
setup error... and run osu!lazer is Nothing happened
[help me?](https://pastebin.com/nNFVKdb7)

but old version is work for me (2018.730.0)

**Comment by Liebelts** [comment]
for me this happens too

**Comment by Ladwick** [comment]
Same

**Comment by peppy** [comment]
Please update to a 64 bit operating system or wait for 32 bit support.
