### ISSUE TITLE
raw input: mouse acceleration, scroll

### ISSUE THREAD

**Issue by danil1petrov** [ppy/osu#3338]
Greetings!
I have a problem with raw input. When i turn it on - scroll wheel stops working, when i turn it off - all is well.
Also: when raw input is turn on, i feel mosue acceleration. Very difficult click the circle with raw input, but i can not change mouse speed/sensetivity/resolution in X11 pereferences, only disable/change mosue accel with libinput. :(

When mouse accel and raw input is turn off, i can play with pleasure, but mouse speed/sensetivity/resolution is very low for me (with raw input in freeware "osu!" i play with 9x on 1000dpi, in lazer it is impossible)
scroll test - https://youtu.be/JcPklitYpqQ
today replay in lazer ond old replay with not a lazer - https://youtu.be/IyAmqWPLaZ0 (forgot to add scroll test)
logs do not say anything
my apartment was flooded so I did everything very quickly
thank you

sorry my english, thank you.

**Comment by danil1petrov** [comment]
Debian 10, Intel Pentium N4200, Dotnet SDK 2.1.400

**Comment by peppy** [comment]
Raw input has not been heavily tested on linux. This will require further investigation.

**Comment by rickymohk** [comment]
Also experience raw input acceleration issue here on Manjaro Linux KDE. I have my system mouse acceleration profile set to flat but it doesn't feel right in osu!lazer 2019.418.0 with raw input turned on. Even the wine version of the orignal osu! client feels better.

**Comment by BernardZhao** [comment]
Also getting the exact same problem on Arch Linux and Debian 9.8.

**Comment by jsferrarelli** [comment]
I'm on Ubuntu 18.04 LTS and when Raw Input is enabled, my cursor flies to the nearest corner of the viewport.

**Comment by Wello6143** [comment]
@peppy so can we disable it by editing any game configuration file?

**Comment by bdach** [comment]
@Wello6143 the combination of <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>R</kbd> should disable raw input in game.

**Comment by Joehuu** [comment]
Closing as stale.
