### ISSUE TITLE
Option button overlaps with osu!lazer text in mac when placed side by side

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3342]
I placed osu lazer and a web browser side by side in one of the desktops.
The option button (beside mods and random) is overlapped by the osu!lazer text.
Clicking on the option button works, it just looks a bit awkward.

I think the bottom bar should either be higher or the osu!lazer text should be moved to the gap between the option button and the osu button.

![image](https://user-images.githubusercontent.com/7527421/44912101-33289f80-acf7-11e8-9760-1a41213b719a.png)

**Comment by peppy** [comment]
The lazer text is a temporary overlay and will eventually be removed. This amount of overlap is allowed for now.
