### ISSUE TITLE
Lazer does not run on integrated graphics

### ISSUE THREAD

**Issue by snowdrifft** [ppy/osu#3343]
Not sure if this issue only happen to me as my Laptop has a custom display driver given by Asus. The custom driver is to somehow solve the problem of code 43 after updating to Windows 10 ver 1803. Using the integrated graphics, lazer would almost instantly crash without creating any logs.
Lazer runs fine on the Nvidia graphics selected in the Nvidia control panel.
[Display Infomation](https://user-images.githubusercontent.com/38553052/44922433-f650bd00-ad77-11e8-996f-416181e15ee7.png)

Dropping the logs when it is on the Nvidia graphics here if it helps!
[debug.log](https://github.com/ppy/osu/files/2340685/debug.log)
[performance.log](https://github.com/ppy/osu/files/2340686/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2340687/runtime.log)
[database.log](https://github.com/ppy/osu/files/2340688/database.log)

The prev version (2018.502.0) I installed for troubleshooting works with integrated display but I did not test the newer versions until the latest release (2018.830.0).

**Comment by danil1petrov** [comment]
Works good on Intel HD 505 ~70 fps

**Comment by Vsyncrooo** [comment]
i also use integrated graphics. I can't say it runs smooth. But its acceptable for its current state.

But did lazer work before the driver update?

**Comment by snowdrifft** [comment]
Not sure about that, I usually run lazer on my desktop computer

**Comment by boswelja** [comment]
Seems to work fine for me, the results screen is a bit stutter but otherwise fine
Running at 1080p on Intel UHD Graphics 620, Latest manufacturer drivers and Windows 10 as my OS. I have an external GPU too, it doesn't seem to give any performance increase which is weird

**Comment by snowdrifft** [comment]
hmmmm might be just an issue only on my laptop, closing it since there is not much info about it
