### ISSUE TITLE
Lazer won't run properly

### ISSUE THREAD

**Issue by Ototap** [ppy/osu#3359]
I'm not sure if this is just me, but whenever I open lazer, all that I see is a black screen, the music and sound effects play, but I can't see anything, I will attach a screenshot here of it.
![image](https://user-images.githubusercontent.com/40903589/45094434-9e8ec900-b15e-11e8-93fd-8e14a8b436da.png)

I don't know if this matters, but here are my computer specs
Graphics Card: NVIDIA GeForce 6150SE nForce 430
Operating System: Windows 10 Pro
Processor: AMD Athlon 7550 Dual-Core Processor  2.50GHz
RAM: 4.00GB
System Type: 64bit Operating system, x64-based processor

**Comment by LastExceed** [comment]
please provide logs. Also try switching to fullscreen using alt+enter and see what happens there

**Comment by jai-sharma** [comment]
@Ototap Log files and be found when clicking the `Open osu! folder` in the settings menu.
Please attach them to your next reply so we can help in debugging

**Comment by Joehuu** [comment]
Closing as stale and tracking it on https://github.com/ppy/osu/issues/6387 which is probably the same issue but more recent.
