### ISSUE TITLE
Add a fade-out animation before the fail menu

### ISSUE THREAD

**Issue by knuxify** [ppy/osu#3361]
In the standard osu!, there's a small animation where all the circles fall to the bottom of the screen before the fail menu appears (retry/exit).

In osu!lazer the fail menu appears without any animation. I find that quite distracting, as I don't have any time to realize what happened, as the menu appears all of a sudden, without a warning (except for the HP bar, of course). It also makes it easier to accidentally click on an option after failing. 

In my opinion, some sort of animation, whether it's a simple fade-out or falling circles, should be added into the game, at least as an optional graphics setting.

**Comment by peppy** [comment]
Yes, this will be coming soon.

**Comment by iiSaLMaN** [comment]
I'm currently implementing it, i'll open a PR as soon as i get it done perfectly
