### ISSUE TITLE
Easy mod doesn't allow continuing after fail

### ISSUE THREAD

**Issue by ghost** [ppy/osu#3372]
On the [2018.906.0](https://github.com/ppy/osu/releases/tag/2018.906.0) release, Instead of Easy mod's normal 3 lives of there is only 1 life.

EDIT:
Looked through the code for Easy mod, and found nothing about the lives yet. So I guess you haven't gotten around to making that work yet (priorities and all).

**Comment by RORIdev** [comment]
I'm working on that issue at the moment. The only problem i've got so far its on trying to replicate the stable's effect, i weren't able to set the player's health to 100%, If I were able to do so, It would be already done.
This is my alterations so far.
```csharp
//issue #3372
            if (Beatmap.Value.Mods.Value.Any(x => x is ModEasy))
            {
                if (Lives <= 3) 
                {
                    Console.WriteLine($"[[[[[[[[[[[[[[[[[[[[ RC = {RestartCount}");
                    
                    Lives++;
                    return false;
                }
                else
                {
                    GameplayClockContainer.Stop();
                    HasFailed = true;
                    FailOverlay.Retries = RestartCount;
                    FailOverlay.Show();
                    return true;
                        
                }

            }
// at osu\osu.Game\Screens\Play\Player.cs : 328
```

**Comment by iiSaLMaN** [comment]
Can be closed.
