### ISSUE TITLE
Updating osu!lazer makes the game remove all of its shortcuts

### ISSUE THREAD

**Issue by knuxfanwin8** [ppy/osu#3377]
Reposted from ppy/osu-framework#1873.

When I use the "Update is ready, click to restart" notification, the game turns off and deletes all of its shortcuts, it's no longer seen in the start menu or while searching. Interestingly enough, the game's files are still in their right place, even the updated ones.

Specs:
- Processor: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, 2701 Mhz, 2 Core(s), 4 Logical Processor(s)
- RAM: 8GB DDR3 SODIMM
- Drive: 128gb SSD
- Laptop model: Dell Latitude E7240
- OS: Windows 10 Home x64 English, Version 10.0.17134 Build 17134

[Here are the logs.](https://1drv.ms/u/s!AiBiGzZBnITMjgQOmiGm8eFSfrhR)

**Comment by Wieku** [comment]
I have the same issue. Game just turns off and deletes its shortcut.

OS: Windows 10 Pro x64 Version 10.0.17134 Build 17134

[Logs](https://img.wieku.me/18/logs180907.zip) (but there's nothing about that in them)

**Comment by peppy** [comment]
More interesting will be `SquirrelSetup.log`, likely in your temp folder

**Comment by Wieku** [comment]
[Here you go](https://img.wieku.me/18/SquirrelSetup1.log)

**Comment by LittleEndu** [comment]
Pretty sure it disappeared (again) form desktop icons too. Or are we expecting the shortcut to stay now that we are updated??

**Comment by Edduaardo** [comment]
yeah, same happened to me when I updated from 915 to 920

**Comment by peppy** [comment]
Got a new squirrel log?

**Comment by Edduaardo** [comment]
The only Squirrel Log I found after updating was in the root folder called SquirrelSetup.txt and it contains only this:

`2018-09-21 22:03:26> Program: Starting Squirrel Updater: --processStartAndWait osu!.dll
2018-09-21 22:03:28> Program: Want to launch 'C:\Users\deae\AppData\Local\osulazer\app-2018.920.0\osu!.exe'
2018-09-21 22:03:28> Program: About to wait for parent PID 2088
2018-09-21 22:03:28> Program: About to launch: 'C:\Users\deae\AppData\Local\osulazer\app-2018.920.0\osu!.exe': `

And the SquirrelTemp folder is empty, I don't think that's useful info though.

**Comment by Morilli** [comment]
I am having this issue too; it has never been fixed.

**Comment by LastExceed** [comment]
This issue should be reopened as the deskop shortcut still disappears during every update

**Comment by Wieku** [comment]
Issue still exists. I updated lazer from 1004.1 to 1017.0
SquirrelSetup (both of SquirrelTemp dirs are empty):
```
2018-10-18 23:41:13> Program: Starting Squirrel Updater: --processStartAndWait osu!.dll
2018-10-18 23:41:13> Program: Want to launch 'C:\Users\Wieku\AppData\Local\osulazer\app-2018.1017.0\osu!.dll'
2018-10-18 23:41:13> Program: About to wait for parent PID 2028
2018-10-18 23:41:15> Program: About to launch: 'C:\Users\Wieku\AppData\Local\osulazer\app-2018.1017.0\osu!.dll': 
2018-10-18 23:41:15> Program: Failed to start process: System.ComponentModel.Win32Exception (0x80004005): No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
```

**Comment by Mempler** [comment]
I can approve that. it still does exists.

**Comment by Wieku** [comment]
I've just reinstalled lazer as stated in #3555. I had an `update.exe` from 09.09.2018 which means that this .exe is not updated. After doing a fresh install of `2018.1004.1` it updated properly to `2018.1017.0`

**Comment by Wieku** [comment]
Update:
Reinstall helped with auto restart, but shortcut issue still exists
There is no logs about that.

**Comment by WRMSRwasTaken** [comment]
Just updated to `2018.1017.0` and had the same issue.
[SquirrelSetup.log](https://github.com/ppy/osu/files/2497424/SquirrelSetup.log)

**Comment by lolita-is-godddd** [comment]
same as do to 1020.0, it doesn't work.

**Comment by LastExceed** [comment]
please don't post any "me too" comments, they just clutter the issue and serve no new information.

**Comment by lebaaru** [comment]
Why would this post be closed...? It's still happening...

**Comment by peppy** [comment]
@lebaaru are you able to provide a video showing what you're seeing? we've updated the version of the updater we are using and can no longer reproduce these kinds of issues at our end.
