### ISSUE TITLE
Confirming the deletion of all skins/beatmaps use the same confirmation design for both

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#3384]
It even says "Confirm deletion of everything?" for both which seems like a copy paste error.

There should even be room for more visual design, like a stream of hitcircles to notify that you are about to delete all maps and a paint brush to notify you are about to delete all skins.

**Comment by peppy** [comment]
They are basically temporary maintenance tasks. They are not supposed to be pretty or over-the-top designed.

**Comment by smoogipoo** [comment]
Intended.
