### ISSUE TITLE
Unsable to interact with settings when music controller is visible

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3387]
when audio overlay is opened you can't rewind settings overlay. instead you're only changing volume.
no matter what was first opened.

logs:
[database.log](https://github.com/ppy/osu/files/2362410/database.log)
[debug.log](https://github.com/ppy/osu/files/2362411/debug.log)
[network.log](https://github.com/ppy/osu/files/2362412/network.log)
[performance.log](https://github.com/ppy/osu/files/2362413/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2362414/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2362415/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2362416/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2362417/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2362418/runtime.log)

**Comment by ticotaco72** [comment]
yes

**Comment by peppy** [comment]
This is the intended behaviour of overlays. Overlays take dedicated full screen input. Clicking once should dismiss the overlay and return input - is this not working?

**Comment by ticotaco72** [comment]
it's working
