### ISSUE TITLE
taiko slider velocity problem

### ISSUE THREAD

**Issue by ZinerX** [ppy/osu#3389]
I play taiko mainly in osu! , I tried the taiko mode in osu!lazer and found the slider velocity is a little bit strange, the speed of the note seems to be changed really suddenly, people can't realize what will happen first time playing the difficulty. 
Let's make an example: d = red note, k = blue note
dkkdk kkdkdd kkdkkdkk
all the notes come into the game from right to left normally
what happens is that dkkdk kkdkdd is at 1.00x slider velocity and kddkkdkk is at 2.00x slider velocity
but kddkkdkk is after dkkdk kkdkdd at 1.00x and turns into 2.00x suddenly as it reaches the timepoint.
This is not as serious as other gaming breaking bugs, but this would be really annoying when playing maps with big and frequent sliver velocity change as the speed becomes unpredictable and weird for some players.

**Comment by peppy** [comment]
Under options set "visualise speed changes" to "overlapping".

![image](https://user-images.githubusercontent.com/191335/45253682-24508580-b3a6-11e8-8d62-b7735cd44173.png)

Eventually this will be a per-ruleset setting with correct defaults.

**Comment by ZinerX** [comment]
Looks way better now!
