### ISSUE TITLE
Score numbers of result screen are too big and go out of bounds.

### ISSUE THREAD

**Issue by Onlinegamer2013** [ppy/osu#3390]
![image](https://user-images.githubusercontent.com/37511342/45254021-960ddc80-b370-11e8-8b1c-6cacc8422625.png)

As you can see here, the score numbers are too big and only show a small part of the number it's supposed to reveal.
My screen is 1366x768, just if you want to know.

**Comment by peppy** [comment]
This may be a regression with the new `SpriteText` implementation. The spaces are not supposed to be so wide.

**Comment by smoogipoo** [comment]
Hmm this is just the wideness of two fixed-width space characters, so basically the space of two 'D' characters side-by-side... Not sure what the best solution is here, but it would occur with the previous implementation also.

**Comment by peppy** [comment]
Yeah, best fix for now would be to force culture or specify manual formatting.
