### ISSUE TITLE
Random invisible difficulties

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3391]
From a few days ago, I found this strange issue:
When I use F2 (random button) sometimes it doesn't load correctly one of the difficulties of a map (sometimes can be the first one, sometimes the last one, but can be anyone).

Here's an example of what I mean:

![unfixed 3](https://user-images.githubusercontent.com/43073074/45254110-8ee7ce00-b372-11e8-9c3d-edb6fe2529d5.jpg)

And even if I move the cursor in the "invisible zone" it doesn't appear, only when I take a screenshot with F12 or scrolling up/down the list.

This is how appears when I scroll/take a screenshot:

![fixed 3](https://user-images.githubusercontent.com/43073074/45254126-17666e80-b373-11e8-83b0-efe534073796.jpg)

(basically auto-fixes itself)

I think it's caused by performance things (and my laptop isn't the best for performance), and not by a certain map.
To be sure, here are the main components (and OS):
OS: Windows 10 Home
RAM: 4GB
CPU: AMD E1-6010 APU with AMD Radeon R2
GPU: (CPU integrated)

And here's a little video (sorry for lag, recording on this PC is like killing it):
https://streamable.com/72vym (you can skip on 0:19 to see the issue)
In the video, I show that the invisible one doesn't appear with the cursor or opening a window like profile/song list or changing the scoreboard, but only when I scroll (or take a screenshot).

Another last example (even stranger):

![invisible 1](https://user-images.githubusercontent.com/43073074/45254333-dbcda380-b376-11e8-90e0-e30fc393b313.jpg)

**Comment by mwkjim** [comment]
might be somewhat related to #3132

**Comment by Gabixel** [comment]
I think so too, sometimes even the "folder/header" is invisible (the small one with the song name and all the difficulties of it) as you can see in the last picture

**Comment by peppy** [comment]
This sounds like an issue with GPU ram exhaustion or something along those lines (if screenshotting fixes). Each panel uses a `BufferedContainer` currently.

**Comment by Gabixel** [comment]
I tried to reproduce the issue, and I think isn't the screenshot itself to make it appear: it's because the screenshot opens the notification center, and if I try to just open the notification center without screenshot, the invisible difficulty appears.
But can be the screenshot too: the panel opens too quick to understand if it's the real cause to make it appear.

**Comment by Gabixel** [comment]
(maybe useful, it's almost all Italian, but I think you can understand what's happening with numbers. And yeah, I know the CPU is at 99%, don't remind me that haha..)

![task manager](https://user-images.githubusercontent.com/43073074/45265605-d2fbd100-b44d-11e8-8699-c609e648171c.png)

**Comment by Gabixel** [comment]
Few updates:

I tried to reproduce it again a few minutes ago, but with logging switched to on, and here's the output of _runtime.log_ (1) and _performance-gamethread.update.log_ (2) of when I found a song with an invisible difficulty (hoping that can be useful):

1.  `10/09/2018 15:29:30: updating selection with beatmap:61 ruleset:0`
`10/09/2018 15:29:30: beatmap changed from "Manuel - Gas Gas Gas (SunBla) [Short Normal]" to "Robbie Williams - Bodies (Larto) [Insane]"`
`10/09/2018 15:29:31: working beatmap updated to Robbie Williams - Bodies (Larto) [Insane]
`

2.  https://pastebin.com/ivM458ZK  (too long and i don't know why GitHub didn't make the entire log a `code`)

**Comment by Gabixel** [comment]
This bug seems to have disappeared from the latest release but, on the contrary, there's a new bug similar to this. Should I close this and make a new issue?

**Comment by smoogipoo** [comment]
I haven't replicated this in recent times, and given the age of this issue I'm going to close it.

Please report back if this still happens.
