### ISSUE TITLE
Beatmaps with same name don't have a second option to default to while ordering themselves

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#3393]
This results in some pretty funky behavior where they will change their order every time a new letter is added in the search bar. Easily noticeable when searching for maps with many sets like "Bravely you" or "Harumachi Clover" etc.

**Comment by LittleEndu** [comment]
The same funky behaviour happens when importing beatmaps

**Comment by bdach** [comment]
This is due to `List<T>.Sort`, used to order beatmaps here:

https://github.com/ppy/osu/blob/de08115e8506ef0f5004a11cc48c15808d9a1800/osu.Game/Screens/Select/Carousel/CarouselGroup.cs#L86

not being a stable sort algorithm.
