### ISSUE TITLE
weird cursor shifting using tablet in latest lazer build

### ISSUE THREAD

**Issue by Vsyncrooo** [ppy/osu#3394]
so i have been checking out all the new features since the last time i checked lazer. But when i went over "osu direct" my windows cursor would become visible and the cursor would shift for some odd reason. 
I didnt have the  problem with mouse 

https://youtu.be/XdDGo3beTj8

Sorry if this is a already known issue

**Comment by smoogipoo** [comment]
Perhaps you have some other program above/below osu!lazer periodically stealing focus. Nothing has changed recently that could cause this.

**Comment by Vsyncrooo** [comment]
weird. im going to check that later.

**Comment by jai-x** [comment]
@Vsyncrooo Are you still able to reproduce this issue with the current releases?

**Comment by Vsyncrooo** [comment]
No , i waited until i had my pc i did the video with. but i used my other one with the same options/drivers/ etc. and the problem is gone. i have never seen a cursor act so weirdly for something in the background though.

**Comment by Vsyncrooo** [comment]
i think this can be closed now. unless there is something wrong with how osu reacts to other programs but thats not a big issue.

**Comment by Joehuu** [comment]
Closing as stale.
