### ISSUE TITLE
Osu! Cursor Glitches

### ISSUE THREAD

**Issue by Sans1738** [ppy/osu#3400]
First Glitch: Cursor disappears after going from fullscreen to windowed 
https://youtu.be/ei7z_pNYaHU?t=30s

Second Glitch: Tablet not working when raw input is added
https://youtu.be/FAWy-u7sNZE  at 0:32 using tablet

I know there is other issues posted that are the same.

The Device I'm using: 13" Retina Macbook Pro 2015  OS: High Sierra
Tablet: XP-Pen G430S

**Comment by stanriders** [comment]
So why did you make a new issue if you know that there are others already?

**Comment by Sans1738** [comment]
I think the first Glitch is new but I don't know. Has anyone noted about this on Macs too?

**Comment by peppy** [comment]
For case 1 I can't even tell what's going wrong because the video fps is so low.

**Comment by Sans1738** [comment]
Running this and recording is hard for my laptop to handle

**Comment by Sans1738** [comment]
This should be more clearer https://www.youtube.com/watch?v=-vlDjsmh82A

**Comment by smoogipoo** [comment]
It would be better to tell us how the cursor is broken. Is it coloured differently, is it hidden, etc...

**Comment by Sans1738** [comment]
The cursor disappeared from osu! lazer

**Comment by peppy** [comment]
Going to close this as I believe these issues were resolved with the migration to SDL2.
