### ISSUE TITLE
Sharp Crackle When Switching Songs (Mac OS?)

### ISSUE THREAD

**Issue by Mintww** [ppy/osu#3401]
When switching from one song to another, there's occasionally a sharp crackle in the audio as the switch happens. https://osu.ppy.sh/beatmapsets/26198#osu/88529 and https://osu.ppy.sh/beatmapsets/22360#osu/77200 are two songs I've noticed it happening somewhat consistently with (switching between them, though only switching to/from the middle of the latter song to the first song. However, song select starts you in the middle anyways.) but there are many songs/song pairs it happens with.

**Comment by smoogipoo** [comment]
Yup I get this too, has been a long-standing issue and is probably at BASS's end.

**Comment by peppy** [comment]
Should be fixed via https://github.com/ppy/osu-framework/pull/2128.
