### ISSUE TITLE
Return to large logo after idle period

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#3406]
**This concept** is about exiting song select or anything where player currently is back to osu!logo after some time of inactivity:
![image](https://user-images.githubusercontent.com/37531387/44999687-73ba3e80-afbf-11e8-8962-3d67b32923ad.png)

Adding option to the settings to turn it on/off is needed in case of implementing it.

_ᴵˢ ᶦᵗ ᶜᵃˡˡᵉᵈ ˢᶜʳᵉᵉⁿˢᵃᵛᵉʳˀ_

**Comment by Gabixel** [comment]
Maybe they can make a black&white screensaver, like the one when you are closing osu!lazer:

![screensaver concept](https://user-images.githubusercontent.com/43073074/45316621-df5c5880-b537-11e8-9fb5-5460a53845ac.PNG)

For slow devices can be a nice feature I guess

**Comment by ToIGLAK** [comment]
Awesome idea! I think it should also bounce to the song playing in the background!

**Comment by ToIGLAK** [comment]
Awesome idea!

**Comment by UselessToucan** [comment]
Looks useless to me. Especially saving battery part of the idea since running Lazer is expensive regardless game state.
![image](https://user-images.githubusercontent.com/22450664/45318468-c195f000-b545-11e8-8b5c-4050806d86ed.png)

**Comment by ToIGLAK** [comment]
While saying screensaver i didn't meant actually saving battery but rather some cool feature that runs while you afk

**Comment by Gabixel** [comment]
That's true but theoretically, for battery, a "black screen" should consume less power (as far as I know), not too much but can be a good solution.

**Comment by peppy** [comment]
A good way to save power is to turn your laptop off. On most (non-OLED) screens black will consume more power (a good opportunity to go learn how an LCD screen works).

That said, we will be adding back an idle state similar to stable. The game should return to the large osu! logo (non-black) if left at the main menu. Undecided about other screens such as song select; that feels like something which would need to be a setting, or limited to when arcade mode is switched on.

**Comment by ToIGLAK** [comment]
I join the question
What is arcade mode?

**Comment by UselessToucan** [comment]
You can find a couple of old videos here
https://www.youtube.com/user/peppyhax/videos

**Comment by peppy** [comment]
Locking thread as off-topic. If someone wishes to implement this, please go ahead by implementing as per how stable does it (menu should return to logo after around 10 seconds of idle).
