### ISSUE TITLE
Fullscreen music controller

### ISSUE THREAD

**Issue by UselessToucan** [ppy/osu#3409]
Since we have a huge music library and some interest in having cool AFK feature(see #3406 ), we might want to have fullscreen version of the music controller.
What is wrong with the existing one? The thing is that it does not provide immersive UX. By immersive I mean something that is big and has WOW effect. For example, I like this huge japanese girl below with UI controls all over the screen.

This suggestion is inspired by the SoundCloud mobile app. We do not need to replicate it as is, but I'm sure we can create something similar using our existing UI controls like waveform.
Here are a couple of screenshots.

Android:
playback
![screenshot_2018-07-21-23-19-03-219_com soundcloud android](https://user-images.githubusercontent.com/22450664/45322807-fa3bc680-b551-11e8-8d97-1bb91d7bd256.png)
rewinding
![screenshot_2018-07-21-23-19-34-467_com soundcloud android](https://user-images.githubusercontent.com/22450664/45322806-f9a33000-b551-11e8-8087-a7f47e43e3e2.png)
playlist
![screenshot_2018-07-21-23-19-13-399_com soundcloud android](https://user-images.githubusercontent.com/22450664/45322805-f9a33000-b551-11e8-9d2e-76769390e7f3.png)

Windows 10(UWP):
![soundcloud_windows](https://user-images.githubusercontent.com/22450664/45322928-5d2d5d80-b552-11e8-80c9-7d104280571e.PNG)

**Comment by peppy** [comment]
osu! is not a music player and I am strongly against it going in this direction. For instance, the Featured Artist licencing we have is for music to be used during gameplay. If you wish to listen to music in an immersive way I'd recommend supporting artists via subscription streaming or direct purchasing on a dedicated service.
