### ISSUE TITLE
osu!lazer doesnt start until i reinstall it

### ISSUE THREAD

**Issue by Nyanekoy** [ppy/osu#3410]
I cannot start osu! directly. everytime i close it i have reinstall it. this seems to happen for me since last week. there no logs showing up for that

**Comment by Wieku** [comment]
Does the game update when you run it? Maybe it's the same issue as #3377

**Comment by Gabixel** [comment]
When you reinstall lazer, do you "uninstall" it before (all game files) or you just download the installer and launch it? Also, what OS are you on? (I think can be useful for devs)

**Comment by Nyanekoy** [comment]
I use Windows 10 x64 and i have to run the installer to start it ( uninstalling and reinstalling doesnt make any difference ) i know of the bug where the shortcut gets removed however usually i could work-arround it with pinning lazer on my taskbar

**Comment by peppy** [comment]
This is a known issue.

**Comment by peppy** [comment]
This should be resolved in the latest release (via #3423). It may take one more update cycle to completely fix. Please report back if it is still occurring in the update after the current one (ie. even if it's not fixed in `2018.915.0`, it likely will be in the update after).
