### ISSUE TITLE
Add letterboxing functionality back

### ISSUE THREAD

**Issue by Alfa-Q** [ppy/osu#3428]
Letterboxing does not currently work in OsuLazer! on Windows 10

The game display does not get smaller when lowering the resolution with letterboxing enabled.  Changing the resolution with letterboxing enabled in fullscreen mode causes the entire game to be scaled at a lower resolution.

**Comment by peppy** [comment]
Letterboxing has not been implemented yet. When it is, it will work.

**Comment by peppy** [comment]
Keeping this open until it's implemented.

**Comment by FreezyLemon** [comment]
For reference: Is letterboxing supposed to be implemented at the framework level, or at the osu! level? The current setting values are stored on the framework-level, but you questioned whether this belongs to the framework level in ppy/osu-framework#1455
