### ISSUE TITLE
Exception occurs if skin folder is not present when importing?

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3432]
(I am aware that in the `.osu` folder, the skins folder is not present)

I just feel like this should not be an *unobserved error*.
Instead the game should have a notification telling the user that the folder cannot be found,
Or just have the same message when importing beatmaps from stable fails (No installation found)

**Comment by manuth** [comment]
I think It'd be most comfortable if the user would be prompted whether `osu!` should create a `skins`-folder automatically and throwing an exception if the folder couldn't be created.

I'll give it a go to implement such a behavior.

**Comment by peppy** [comment]
I think you misunderstood the issue here. The problem is that there is no check for whether the `SKins` folder exists before the new-user import prompt attempts to import the skins.
