### ISSUE TITLE
Unclear Mods Overlay can be scrolled?

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3433]
It took me a while to realize the newly introduced mods are only accessible after you scroll up the mods overlay.

Is there anyway to make it more obvious that the mods overlay can be scrolled up-down? (like having a scrollbar on the side or something to show there is still content below)

**Comment by jorolf** [comment]
The scrollbar has been hidden intentionally.

**Comment by Gabixel** [comment]
Maybe just adding "(scroll down for more mods)" in the Mods Description can be a good solution?

**Comment by peppy** [comment]
The scrollability needs to be exposed either via UI elements or animation on appearing.

**Comment by Joehuu** [comment]
Closing in favor of https://github.com/ppy/osu/issues/16917 (already resolved in new design).
