### ISSUE TITLE
Incorrect hit object position when Transform and Wiggle are both activated

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3434]
(Unless this behaviour is intended...)

When activated separately, the hit objects look like they appear at the same place.

When both are activated, it seems like Transform does not bring them in, so it starts wiggling at the point at which it starts to slide in.

This is a problem because sometimes, the hit objects end up out of the playing field, which is really awkward.

**Comment by Gabixel** [comment]
I tried with autoplay and yeah.. that's not intended: https://streamable.com/jdeqv

**Comment by peppy** [comment]
Yep, they need to be marked as incompatible.
