### ISSUE TITLE
Starting a song when the player ends the music, a different song starts.

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3439]
I found this issue a few hours ago, but I took some time to reproduce it, and now I have different results (a total of 4).
**Note**: the framerate and the audio of the following videos are quite bad, but it's enough to understand what's happening (you can even watch without audio). I even added some texts and edited the videos to explain more

## Issue
Every time I start to play a song when the player is about to restart the music, a different song starts.

## How to reproduce it (if it's possible with powerful PCs)
Play a song when the music player tries to restart the music, sometimes it can be easy.

## Why this happens
Honestly, I don't know, but maybe something happens between the loading screen and starting a song

---
## The first time I saw it (no crash)
https://streamable.com/q6z4c

I had "autoplay" and "transform" activated, but they seem to don't affect the performance in this video. Something weird happened when I restarted the song. (The logs here seems to be normal, but I think I still lost something when exiting the song)

## Second try (game crash)
https://streamable.com/bzzme

The second time the game crashes and it's very similar to the first time. (I remembered I used only AutoPlay)

## Third try (no crash)
https://streamable.com/5sawo

No crash, no AutoPlay, but different background (already updated on the loading screen, maybe opening a few seconds later made the difference)

## Last try (game crash)
https://streamable.com/x5jyn

Similar to the other crash (with AutoPlay on)

---
## Logs
The things that associate them are logs.

On the **runtime.log**, every time the game freeze in the previous videos, it spams *[this error](https://pastebin.com/yhkmfAsE)* as much as it can (except for the last one: it has no `Unhandled exception has been denied .`)

On **performance-gamethread.update.log** the only strange "slow frame" is this:
```
15/09/2018 13:17:37: | Slow frame on thread "GameThread.Update"
15/09/2018 13:17:37: |
15/09/2018 13:17:37: | * Thread time  : 608.373ms
15/09/2018 13:17:37: | * Frame length : 233ms (allowable: 172ms)
15/09/2018 13:17:37: |
15/09/2018 13:17:37: | Stack trace:
15/09/2018 13:17:37: |- GCFrame
15/09/2018 13:17:37: |- DebuggerU2MCatchHandlerFrame
15/09/2018 13:17:37: 
```

**Comment by bdach** [comment]
Looking at the error stack trace this might be connected to / the same issue as #6362. Since this report is more stale I'll close it for now as potentially no longer valid (and the other one had a PR that could possibly fix it too).
