### ISSUE TITLE
Drag and Drop import of Beatmaps broken on Linux

### ISSUE THREAD

**Issue by Chronody** [ppy/osu#3444]
When trying to import a Beatmap by dragging and dropping it into the Lazer window on current master (and also already on Release commit [2018.915.0](https://github.com/ppy/osu/commit/8cb0b5e98d74fd3995d3f3f4ae4a902d4d804c00)) on Linux, it doesn't import the Beatmap nor does it show any reaction in the logs, console or otherwise. 

Other applications react to Drag 'n Drops normally so it shouldn't be a local issue.
Tested on two different Linux Machines, same results.

Works normally when I revert to [2018.910.0](https://github.com/ppy/osu/commit/5e5a74293e2710690328dda0086ec0fe9617ac24).

**Comment by peppy** [comment]
Are you sure you aren't running under a different elevation level (ie. triggering a `sudo`)? I do not believe anything has changed which should cause this to occur from our end.

**Comment by Chronody** [comment]
Pretty sure. Both Lazer and my filemanager are listed as running under my user on both versions. 
Running just my filemanager or both as `sudo` doesn't change the behaviour either.

I run the exact same command to test the two versions:
`LD_LIBRARY_PATH=/home/chronody/MyStuff/osu/osu.Desktop/bin/Debug/netcoreapp2.1/ dotnet run --project osu.Desktop`
Just with a `git checkout <commit>` in between to revert.

I can try and pinpoint the commit that seemingly caused it to break over the coming days.

**Comment by Chronody** [comment]
Allright, testing went rather quick.

[dbcbd82](https://github.com/ppy/osu/commit/dbcbd82554c15005ddfe3ed0e4a1e1bdb660dedc) is the last commit importing worked on.
[96b4cb7](https://github.com/ppy/osu/commit/96b4cb7821f197517022886516fe9c3f2010ae82) doesn't build and [067bc39](https://github.com/ppy/osu/commit/067bc39185149ac34be800fdbefdba7190539356) is the first one to run and be broken.
