### ISSUE TITLE
Transform + Wiggle mods cause a lot of issues

### ISSUE THREAD

**Issue by Onlinegamer2013** [ppy/osu#3445]
If you select the Transform and Wiggle mods at the same time, a lot of issues pop up.

The transform effect doesn't happen anymore, so hit objects stay where they are. That causes Auto to mess up. Finally, the message saying "miss", "good", etc. appears at the place where the hit object should be, and not where it is currently. (i can't put a video because my computer isn't powerful enough, but you can try it yourself)

Here's a screenshot on the map "deltaMAX" with Transform, Wiggle and Auto.
![osu_2018-09-16_14-09-36](https://user-images.githubusercontent.com/37511342/45596330-b49c5500-b9ba-11e8-9018-0eea24e0d8d0.jpg)

**Comment by Onlinegamer2013** [comment]
You can also still play the map if you have Auto disabled, but every hit object will be out of place.

**Comment by Onlinegamer2013** [comment]
okay

**Comment by miterosan** [comment]
"Wiggle and Tramsform mod do not function properly if used together" would be a more fitting 
 title.
