### ISSUE TITLE
Can't Install Osu!Lazer at all

### ISSUE THREAD

**Issue by Drax47** [ppy/osu#3446]
It just happens that just whenever I try to install it it just doesn't work and says that installation failed, I'm not sure if I'm missing any programs like net framework or whatever
[Log.txt](https://github.com/ppy/osu/files/2386898/Log.txt)

**Comment by Ladwick** [comment]
Actually I have the same problem, the log is the same... I tried to uninstall and erase any osu!lazer archive from the pc but nothing worked...

**Comment by FajsiEx** [comment]
Do you have 32 or 64-bit Windows?

**Comment by jai-x** [comment]
If you look at the logfiles, it seems to be trying to install lazer within the same path as Discord app running on your computer and then failing when it cannot find the executables in the regular `appdata/osu!lazer` path.

Are you trying to install the game in a non-standard way, e.g. from executable someone sent you on discord?

Please be sure to only use executables found from the releases page here: https://github.com/ppy/osu/releases/latest

Try to open the file from a standard windows location, e.g. download to the desktop or a folder in my documents, and open it from there.

**Comment by FajsiEx** [comment]
The log file also shows
(0x80004005): The specified executable is not a valid application for this OS platform.

I tried to install lazer on 32-bit windows a while back and I found that error in the log file too...
Now that I've switched to 64-bit windows everything works just fine. :/

**Comment by peppy** [comment]
The installer currently only supports 64 bit host systems. You can follow discussion

**Comment by NikitaFoxSp** [comment]
> The installer currently only supports 64 bit host systems. You can follow discussion [here](https://github.com/ppy/osu-framework/issues/1619)

Please make it for 32bit, alot of people want to try out the Osu!Lazer

**Comment by ticotaco72** [comment]
https://github.com/ppy/osu/blob/master/README.md
Method described here works with 32 bit
