### ISSUE TITLE
Osu!Lazer Stats not Showing

### ISSUE THREAD

**Issue by ItzSnowZz** [ppy/osu#3447]
![osu_2018-09-16_15-58-05](https://user-images.githubusercontent.com/43325715/45602240-69d90800-b9cf-11e8-9999-03a020f7acf3.jpg)

i can play beatmaps fine i just don't have my stats showing up at all

**Comment by Gabixel** [comment]
That's weird, it doesn't show up any error? Try to find what's happening on logs (like _runtime.log_, if you know where is located)

**Comment by peppy** [comment]
`network.log` is probably of interest here. also whether they can see other users' profiles.

**Comment by ItzSnowZz** [comment]
Peppy you want me to paste bin you the logs but I can’t find them on Mac though

**Comment by ItzSnowZz** [comment]
I need to know what logs you want

**Comment by peppy** [comment]
It is in the osu! folder (you can open it from the settings). Also please answer the question I just asked about other users' profiles.

**Comment by smoogipoo** [comment]
Closing due to 2 weeks with no response. @ItzSnowZz feel free to re-open if still an issue.
