### ISSUE TITLE
Make hitcircle number skinnable

### ISSUE THREAD

**Issue by Dragicafit** [ppy/osu#3455]
The actual skin for number is given by an OsuSpriteText.
It contains a font and a size, so is it possible to modify them using for exemple skin.ini or should it be better to use the previous method based on default-n.png ?

**Comment by peppy** [comment]
A derived `OsuSpriteText` needs to be created supporting legacy skins for this purpose.

**Comment by Dragicafit** [comment]
So, I have to transform the default-n.png in characters and put it in the global FontStore or there is an other place to store it ?
