### ISSUE TITLE
make an option to turn the sRGB stuff off, please

### ISSUE THREAD

**Issue by SevenChords** [ppy/osu#3459]
title is pretty much self explainatory

**Comment by peppy** [comment]
This makes no sense. What are you talking about here?

**Comment by SevenChords** [comment]
i don’t really know if i got it right that it’s the sRGB thing, but i would like an option to turn off the random color changing of the objects, since i can’t see the approach circles of the darker colors because i am playing with 100% background dim

**Comment by AtomCrafty** [comment]
Are you talking about combo colors?

**Comment by AtomCrafty** [comment]
Haven't really looked into this much, but as far as I can tell that can be achieved in stable by a custom skin. A quick test shows that it does not currently work in lazer, but I'm pretty sure there will be a similar option once the skinning system is fully implemented.

**Comment by SevenChords** [comment]
only problem for me:
i am a mac user
i can only run the standard client using wine emulation
this causes huuuuuuge performance issues
like, i sometimes am at 3fps systemwide while osu standard client is running through wine
with the macos dedicated lazer client i have no issues whatsoever 
therefore i wish the skinning system would be fully implemented in lazer rather sooner than later or a dedicated macos standard client like there is one for lazer

**Comment by peppy** [comment]
Closing in favour of #3460.
