### ISSUE TITLE
OsuModNightcore.cs doesn't have Name and ShortenedName

### ISSUE THREAD

**Issue by U-siro** [ppy/osu#3468]
https://github.com/ppy/osu/blob/a8579c49f9327b0a4a8278a76167e081d14ea516/osu.Game.Rulesets.Osu/Mods/OsuModNightcore.cs doesn't have any name and/or shortenedname.

Is it ok if I add it?

**Comment by ekrctb** [comment]
Doesn't `OsuModNightcore` inherit those properties from its superclass `ModNightcore`.

**Comment by Hanamuke** [comment]
I'm pretty sure it does

**Comment by U-siro** [comment]
Thanks @e
