### ISSUE TITLE
osu! on iOS

### ISSUE THREAD

**Issue by Lakikkii** [ppy/osu#3475]
When I open up osu! on iOS it just crashes. I try to open it again, **it crashes again!**. After the second try, I try to open it up again, and it works. This happens **every single time**.

**Comment by peppy** [comment]
Are you actually trying to build and deploy lazer yourself? If not, you are probably talking about osu!stream, which is not supported here.

**Comment by Lakikkii** [comment]
I am talking about osu!stream. And I don't even know what is osu!lazer.

**Comment by peppy** [comment]
Closing because this is not the correct place for discussion. osu!stream is currently in an unsupported state, but will receive a maintenance patch later this year.
