### ISSUE TITLE
Can't find songs downloaded thru Osu direct

### ISSUE THREAD

**Issue by NotaaaEgg** [ppy/osu#3481]
What I did: 

1. opened osu!lazer;
2. downloaded songs from osu direct;
3. imported;
4. closed osu!lazer;
5. opened osu!
6. checked for new songs;
7. found no new songs;

Can anyone help me find the downloaded songs?

**Comment by peppy** [comment]
Are you download beatmaps for the correct ruleset?

**Comment by NotaaaEgg** [comment]
I'm not sure that I understand what ruleset means
![image](https://user-images.githubusercontent.com/43516772/45928419-8dc7bb00-bf86-11e8-9b21-064bd57d5a1b.png)
Do you mean this?

**Comment by peppy** [comment]
As in is your osu!direct set to taiko while your song select is set to osu! mode?

**Comment by NotaaaEgg** [comment]
Oh I'm sure I selected the correct mode

**Comment by qwewqa** [comment]
If I understand correctly, you are downloading songs on lazer and then opening stable. I believe that lazer saves beatmaps in a different directory in its own format so that beatmaps installed in lazer are not accessible from stable.

**Comment by Edduaardo** [comment]
If that's the case, yes, lazer save the beatmaps in a complete different folder than stable. Lazer just copy the stable beatmap folder, the inverse (stable copying from lazer folder) won't occur

**Comment by NotaaaEgg** [comment]
Done! That's ok if it answers are correct.  Ty guys!
