### ISSUE TITLE
Toggle mute keybind conflicts with Alt+F4

### ISSUE THREAD

**Issue by AtomCrafty** [ppy/osu#3483]
The default keybinding for "Toggle mute" is currently F4, which interferes with Alt+F4.
When force-quitting the game, the "See you next time" animation will therefore be silent, if you release Alt before the F4 key.

**Comment by Joehuu** [comment]
I'm proposing we change it to `CTRL` + `SHIFT` + `M`. Discord also uses this to mute mic (TIL when going to https://defkey.com/search?irq=mute).

**Comment by peppy** [comment]
I propose we change nothing and investigate why this is happening. The key matching mode is already set to `KeyCombinationMatchingMode.Modifiers`, so Alt-F4 should *not* trigger an F4 bind.
