### ISSUE TITLE
Dropdown windows shouldn't have a reaction to scrolling?

### ISSUE THREAD

**Issue by someDerpyPineapple** [ppy/osu#3486]
_For example, i'm going to talk about the skin selection dropdown cause that's the one that i found the design flaw in:_
There's an animation and scrollbar that appear when you scroll up and down while your cursor is on the skin selection dropdown (see below screenshot, try ingame to see animation i'm reffering to). 

It implies that scrolling down actually scrolls down your skin list when it really does nothing.
![osu_2018-09-24_00-28-07](https://user-images.githubusercontent.com/43484729/45940934-be145700-bf90-11e8-8786-1b52309fe881.jpg)

The only way to scroll down this list is to put your cursor between the skin dropdown and the edge of the settings menu (see below screenshot) 

Then, scrolling down/up actually scrolls up and down the setting menu and the dropdown.
![osu_2018-09-24_00-27-59](https://user-images.githubusercontent.com/43484729/45941007-1f3c2a80-bf91-11e8-997f-9a13c99788af.jpg)

This is really unintuitive because clicking on a dropdown already reveals the whole list anyways, why is there an animation and a scroll bar that implies that the full list isn't being displayed?
 
i suggest that **when your cursor is on a dropdown**, a dropdown menu does 1 of 3 things:

- The dropdown menu will just scroll as if your cursor was in the position in the 2nd screenshot.  This seems the most intuitive.
- The dropdown acts as a seperate "window" that you can scroll up and down a list of options with. It would show, for example, 5 options/skins/choices at any given time, and scrolling would show other options/skins. For a visualization, it's like scrolling through a website; you only see a certain part of it at any given time, and scrolling lets you see more.
- just copy current osu!'s behavior lol

hope my suggestions made sense. I'll clarify if needed.

**Comment by peppy** [comment]
There’s already an open framework PR related to limiting the height of drop downs, of I recall correctly.

**Comment by benpigchu** [comment]
ppy/osu-framework#1768

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/5531.
