### ISSUE TITLE
Impossible osu!lazer Slider

### ISSUE THREAD

**Issue by AdrianClem** [ppy/osu#3490]
In this https://youtu.be/auJ9fgrMrbI video in a GRAVEYARD beatmap a slider is impossible...

IDK how it's possible but I tested in original osu! the slider works...

Thanks, AdriaAyl.

**Comment by Xinnoh** [comment]
Can confirm something is up, works fine on the previous build but seems like sliders are a bit buggy now

**Comment by peppy** [comment]
Id your universal offset set to 0?

**Comment by AdriaAyl** [comment]
Audio offset is set to 0ms

**Comment by Joehuu** [comment]
Can't seem to reproduce at all in the latest release.

While trying to find what fixed this (by release tags in 2018-2019), there were times where it froze at the time in the OP, other places, or never (by deleting, restoring, and testing a bunch of times). Tentatively closing as I couldn't find the exact change that fixed this.
