### ISSUE TITLE
Mouse is stuck after switching cursor confinement

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3495]
This happened on my mac (not sure if this happens on other platforms),
running 2018.920.0.

Steps to reproduce:
1. Set *confine mouse cursor to window* to anything but always
2. Set it to always

After doing that, the cursor is gone from the screen (or is it stuck at the bottom right corner, cannot really tell).

**Comment by someDerpyPineapple** [comment]
running 2018.920.0, not reproducible for me on windows 10 (insider build i think)

**Comment by jeffrypig23** [comment]
It might just be a macOS issue. 

I also had the issue occur on 2019.418.0 where the cursor would jump to the bottom left corner, outside the game window

![bug](https://user-images.githubusercontent.com/10385195/56532589-e5250e00-650a-11e9-9b79-6515b1273559.gif)

**Comment by peppy** [comment]
This has since been resolved (although there are other bugs related to high precision being turned on under macOS).
