### ISSUE TITLE
Import Beatmaps doesn't import

### ISSUE THREAD

**Issue by takoz53** [ppy/osu#3501]
Skins just work fine. They all imported.
Importing beatmaps (Got about 87k) just imports 1 beatmapset.
**To note:** Always imports the same beatmapset when trying to re-do the process.

**What I did (Reproduce):**

- Open the game
- Play a round
- Imported Skins
- Played a round
- Imported Beatmaps

**Sidenote:**
- I had stopped the very first auto-processing.
- After restarting osu!lazer and trying without the steps listed over this and just importing, it will still import just one beatmapset.
- Build is **2018.920.0** (Already compiled version, which is downloadable)

**[Result](https://puu.sh/BBQWA/46bab26c42.jp)**

**Comment by peppy** [comment]
Logs please?

**Comment by takoz53** [comment]
[logs.zip](https://github.com/ppy/osu/files/2424524/logs.zip)

**Comment by peppy** [comment]
@takoz53 are you able to try this again? your logs make it look like lazer was only able to *find* one beatmap to import (there are no errors).

**Comment by takoz53** [comment]
I'm sorry I haven't seen the message. I'm on a new computer. On that one it just seems fine, so I'm sorry I can't provide you with that information 😢

**Comment by smoogipoo** [comment]
Going to close until the next report then. Thanks.
