### ISSUE TITLE
country

### ISSUE THREAD

**Issue by kojikondonintendo** [ppy/osu#3502]
can i change the country of living? or not show it on my profile?

**Comment by ticotaco72** [comment]
You should look at osu.ppy.sh for answer.
It isn't possible if you don't really need it and you should ask osu support team.

Please close this issue

**Comment by kojikondonintendo** [comment]
can you like comment the answer

**Comment by ticotaco72** [comment]
i answered your question. You can't change account country if you live in country that you have on account now. 

https://osu.ppy.sh/help/wiki/Help_Centre this is where you should look always at first.

CLOSE THIS ISSUE. this page isn't support page. it's page for development of next osu version. when you ask for help with normal osu here, you're disturbing other people
if you steel need help go here https://osu.ppy.sh/community/forums/5

![2018-09-27 2](https://user-images.githubusercontent.com/32620809/46175103-28880880-c2ab-11e8-91be-3ba73b2ad9c9.png)

**Comment by kojikondonintendo** [comment]
ok sorry man i entered your private space. like i killed you, smh. thanks and bye cya later
