### ISSUE TITLE
Fullscreen Issue on dotnet core GNU/Linux

### ISSUE THREAD

**Issue by Alexmitter** [ppy/osu#3503]
Full screen behave different if Package is build.
As in X window system, a Full screen App should be a border less window taking full screen space.
osu!lazer does that but only if i start osu!lazer by "dotnet run", if i create a package, and run the "osu!" binary it created. All my other screens turn off.
The setting "Borderless Window" also don't help because it does not stick to the primary monitor.

Edit:
I was wrong about the behavior. First time you run it per "dotnet run", it will start in windowed mode, go to settings and change it to fullscreen, it will work fine. But the second time you start it, it will start as a single x screen fullscreen, only deleting the osu folder under ~/.local fix this until the next start.

**Comment by morguldir** [comment]
Could you try installing libsdl2-dev?

**Comment by Alexmitter** [comment]
@morguldir Sure, I will do that. But could this be realistic? I mean if it needs that shared object, would it not need a hard reference, so always require this lib?
