### ISSUE TITLE
Can't import skins and songs because osu!stable is on a different harddrive

### ISSUE THREAD

**Issue by r3tikle** [ppy/osu#3506]
as title says i can not import skins and songs because my stable osu in on a different hard drive, so my idea was you guys could make it so you can manually choose the songs and skins folder that you want to import or you can set the songs and skins directory that you want.

**Comment by Wieku** [comment]
I think it's connected to #1907

**Comment by r3tikle** [comment]
> I think it's connected to #1907

it cant be, because it doesnt even see an installation of osu stable https://gyazo.com/b6407a4e608f04e40c92d29835c47aa7

**Comment by plankp** [comment]
@r3tikle Hi what platform are you on? My suggestion for a temporary workaround (if you want to avoid copying all your osu!stable data) is to create a shortcut (or symbolic link) to where it expects the osu data to be (a folder called `.osu` in your user's home directory)

**Comment by r3tikle** [comment]
> @r3tikle Hi! What platform are you on? My suggestion for a temporary workaround (if you want to avoid copying all your osu!stable data) is to create a shortcut (or symbolic link) to where it expects the osu data to be (a folder called `.osu` in your user's home directory)

im on Windows, and also do you know where does stable osu originally install to? If i can find that out i have a software that can redirect folders and stuff that i can use.

**Comment by plankp** [comment]
`/C/Users/your_user_name_here/AppData/Local/osu!/`

You could navigate close to there if you navigate (with file explorer) to `%APP_DATA%`.

**Comment by r3tikle** [comment]
Alright new problem, after importing over 6000 beatmaps game stutters alot after pressing solo on the play tab. game will lag for a long time then randomly will be fine, tested it 3 times, with restarting osu!lazer.

**Comment by smoogipoo** [comment]
Please make a separate issue for that.

**Comment by TheDoctorPotter** [comment]
I have a similar problem. I have just downloaded osu!lazer on Ubuntu 20.04, and am trying to add a skin, but I can't because my osu!stable is on my Windows hard drive that, for some reason, I can no longer access or boot to. I was able to redownload the skin's .osk file; is there any way for me to spoof an osu!stable install on Ubuntu for Lazer to take the skin file from?

**Comment by bdach** [comment]
There is - see #7234 for instructions, although if you have the `.osk`, I'm struggling to understand why you would even need to "spoof a stable install" to begin with.
