### ISSUE TITLE
IPv6 failures don't fallback to IPv4

### ISSUE THREAD

**Issue by DCNick3** [ppy/osu#3507]
I've checked out and built master branch. I run it natively on linux.
I've tried to log in into my account ([DCNick3](https://osu.ppy.sh/u/DCNick3)). After like 20 seconds of connecting, login form returned into previous state.

Here is the log. Output does not depend on login/password (my account credentials and random characters have the same result).

```
9/30/18 10:08:56 AM: We just went Connecting!
9/30/18 10:09:06 AM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
9/30/18 10:09:16 AM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
9/30/18 10:09:16 AM: Processing response from https://osu.ppy.sh/oauth/token failed with System.ArgumentNullException: Value cannot be null.
9/30/18 10:09:16 AM: Parameter name: value
9/30/18 10:09:16 AM: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
9/30/18 10:09:16 AM: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
9/30/18 10:09:16 AM: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse()
9/30/18 10:09:16 AM: at osu.Framework.IO.Network.WebRequest.Complete(Exception e).
9/30/18 10:09:16 AM: Login failed!
9/30/18 10:09:16 AM: We just went Offline!
```

Login to stable osu! running in wine works just fine.

**Comment by Edduaardo** [comment]
It just happened once? Or is still happening? 
It's looks like the server cold not be reached to validate your login, perhaps the server was instable when you attempted to login?

**Comment by Wieku** [comment]
I think my workaround for that was infinite pinging osu.ppy.sh in terminal. But i thought it was an issue only on my side.

**Comment by Edduaardo** [comment]
So it must be an issue where the connection with the server rapidly close and can't complete the login validation.

**Comment by DCNick3** [comment]
> I think my workaround for that was infinite pinging osu.ppy.sh in terminal

Fun fact: `osu.ppy.sh` does not answer ICMPv6 packets. But it answers http over IPv6. Maybe it has something to with it.

> It just happened once? Or is still happening?

I haven't be able to login. Tried now - same result.

Also, 
```curl -X POST https://osu.ppy.sh/oauth/token```
completes and returns 
```{"error":"unsupported_grant_type","message":"The authorization grant type is not supported by the authorization server.","hint":"Check the `grant_type` parameter"}```
So server is probably OK.

Maybe this has something to do with internet censorship of my ISP, I'll check if that looks like it.

**Comment by DCNick3** [comment]
The problem was on my end. IPv6 just stopped working. Other software usually falls back to IPv4 if IPv6 fails, but osu! did not, so I haven't noticed it.

Probably, osu! should do this too.

**Comment by Wieku** [comment]
That would have sense because on my network IPv6 doesn't work except DNSv6

**Comment by smoogipoo** [comment]
osu!stable had manual fallback to ipv4 on ipv6 failures. We briefly discussed this and would like to avoid adding the functionality into osu!lazer/osu!framework for the time being - it should probably be something done at .NET Core level.

**Comment by peppy** [comment]
Please leave this open as we likely want to fix this.

**Comment by DCNick3** [comment]
Well, @smoogipoo written, that it should be fixed on dotnet core side, so I decided, that issue for osu!lazer should be closed. Would you add such a fix into osu! or what?

**Comment by peppy** [comment]
Unsure yet, but we keep issues open as long as they are relevant.

**Comment by peppy** [comment]
Bumping to milestone as this seems to still be an issue. Will take a look into it.

**Comment by peppy** [comment]
I'm going to look into this today or tomorrow. Definitely something we should get resolved.

**Comment by Cholapat** [comment]
Disabling ipv6 works for me
For people who don't know how to disable ipv6, type network connection in the start menu and click the first option
![image](https://user-images.githubusercontent.com/29303173/107461942-a5387c00-6b20-11eb-91e6-be5e7d3df5c1.png)

Right click the network adapter you use (usually Wi-Fi or Ethernet) and select properties
![image](https://user-images.githubusercontent.com/29303173/107462158-1b3ce300-6b21-11eb-91be-f2f7b7c428c5.png)

Uncheck the box for Internet Protocol Version 6 and click OK
![image](https://user-images.githubusercontent.com/29303173/107462216-3e679280-6b21-11eb-920f-afc14ea9dbd9.png)
