### ISSUE TITLE
installation by setup.exe

### ISSUE THREAD

**Issue by lolita-is-godddd** [ppy/osu#3509]
Even do "Run As Admin", that just makes "access denied."
Exit without even confirm admin's password, so I'd like to know where it'll installed?
Device: Windows 7, x64 (if need more infomation, asc me please)

**Comment by Edduaardo** [comment]
osu!lazer typically install in C:\Users\YourUser\AppData\Local\osulazer

After osu!lazer installing, it should create a shortcut in you Desktop, so you know it's successfully installed.

**Comment by peppy** [comment]
This sounds like your system’s permissions are broken, but it’s hard to say with no logs provided.

**Comment by lolita-is-godddd** [comment]
Also, I tried build from src and run. but csproj files are denied by the V.S.2015. (its log said some version of component are invalid or just like that, but i didn't remember that message correctly.) So I could not build.

@Edduaardo Should I make folder manually?
@peppy I don't know where logs are...

**Comment by HoLLy-HaCKeR** [comment]
This project won't compile with Visual Studio 2015 as it uses C# 7 and the new csproj format, you should upgrade to Visual Studio 2017 if you want to compile yourself.

The logs should be in `C:\Users\<user>\AppData\Roaming\osu\logs` or `%appdata%\osu\logs` (same folder).

**Comment by Edduaardo** [comment]
> @Edduaardo Should I make folder manually?

No, the installer creates everything for you.

If what peppy said is correct, you are probably using an user with no permissions to execute the installer or your system is really broken (since you said that you used Admin's password and was still denied). If that's the case it's better to backup everything and format.

**Comment by lolita-is-godddd** [comment]
I'm very suprized because ~~effected god power~~ reinstall `install.exe` and run, it works!!!!!
Also, installed vs code, but the C# extension could not download, so can't build either.
