### ISSUE TITLE
Game lags like crazy after importing 6000+ beatmaps

### ISSUE THREAD

**Issue by r3tikle** [ppy/osu#3519]
after importing over 6000 beatmaps game stutters alot after pressing solo on the play tab. game will lag for a long time, tested it 3 times, with restarting osu!lazer each time.

video proof:
https://www.youtube.com/watch?v=yOuFfV83BGs
it actually looks different from the monitor than recording it with obs

**Comment by peppy** [comment]
How many cores do you have? This is likely due to background difficulty calculation, which is something that will receive further optimisation at a later stage.

**Comment by smoogipoo** [comment]
If you watch the video, it happens when entering song select, not during the import.

**Comment by r3tikle** [comment]
> How many cores do you have? This is likely due to background difficulty calculation, which is something that will receive further optimisation at a later stage.

i have an i7 2600 and 16 gbs of ram
so 4 cores 8 threads

**Comment by r3tikle** [comment]
> If you watch the video, it happens when entering song select, not during the import.

yea its in entering song select, it took me like 2-3 hrs to import 6k songs

**Comment by peppy** [comment]
What are you recording using? The video looks incorrect (inaccurate) after the first half).

COuld you confirm that gameplay does not look like what you managed to record?

**Comment by AtomCrafty** [comment]
>it actually looks different from the monitor than recording it with obs

I believe this answers both of your questions

**Comment by r3tikle** [comment]
> What are you recording using? The video looks incorrect (inaccurate) after the first half).
> 
> COuld you confirm that gameplay does not look like what you managed to record?

gameplay doesnt look exactly like that but it is very stuttery https://www.youtube.com/watch?v=YF18usb-V9w

and yes first half of video is fine until i press on the solo button which takes a long time to load in

**Comment by Joehuu** [comment]
Fixed in #5371.
