### ISSUE TITLE
Show informative error message when trying to install on a 32-bit system

### ISSUE THREAD

**Issue by jai-x** [ppy/osu#3525]
## Feature proposal

Not sure if this is possible, but it would be good if the installer would be able to tell
the end user that 32-bit is not supported when trying to install osu!lazer on a 32-bit system.

**Comment by Edduaardo** [comment]
It would be a good ideia, since some people come here thinking that's a bug.

**Comment by Hanamuke** [comment]
Maybe this needs a osu-deploy patch ? One can do IntPtr.Size to know if the .NET install is 32 bits, but I don't know if this is what we want

**Comment by Liebelts** [comment]
oh no so i'll cant play osu!  :((

**Comment by peppy** [comment]
Closing in favour of #3984.
