### ISSUE TITLE
Beatmaps that use older osu file format don't properly show as ranked.

### ISSUE THREAD

**Issue by nathanielcwm** [ppy/osu#3528]
osu!lazer is currently still under heavy development!

Please ensure that you are making an issue for one of the following:

- A bug with currently implemented features (not features that don't exist)
- A feature you are considering adding, so we can collaborate on feedback and design.
- Discussions about technical design decisions

If your issue qualifies, replace this text with a detailed description of your issue with as much relevant information as you can provide.

Screenshots and log files are highly welcomed.

It seems like beatmaps that use an older osu file format don't show up properly as ranked. Currently i've tested that beatmaps with osu file format v12 and up currently work as intended.

**Comment by Gabixel** [comment]
Could you show some screenshots and log files (if you know where they're located)?
Also, you can say what OS are you running.

(And please, remove the "default comment" next time)

**Comment by nathanielcwm** [comment]
#3529 seems to be the same problem
