### ISSUE TITLE
Game does not request some scoreboards

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3529]
From a couple of versions ago, I noticed that the game doesn't request some ranked map's scoreboard.
It doesn't seem to be a session bug or something like that, but it only happens with some specific maps without any explainable reason.

Here's an example:

![no leaderboard](https://user-images.githubusercontent.com/43073074/46354287-8a0af700-c65e-11e8-8f22-082ae2890139.png)

but it did not end here: these maps seem to be bugged on `osu!direct`, and their `Details`' button doesn't work. Here's a demo video (**no audio**): https://streamable.com/w7hwp

`network.log` seems to have nothing after `osu.Game.Online.API.Requests.GetScoresRequest` about these maps
(For previous screenshot example, it should give something like `Request to https://osu.ppy.sh/api/v2/beatmaps/43522/scores successfully completed!` (that's his Beatmap ID if I don't mistake), and instead it gives nothing)

---
Here's the list of maps with this problem:
--
- [[Gym Class Heroes feat. Adam Levine] Stereo Hearts](https://osu.ppy.sh/beatmapsets/43522)
- [[Owl City] Angels](https://osu.ppy.sh/beatmapsets/32179)
- [[ATC] Around the World](https://osu.ppy.sh/beatmapsets/25707)
- [[Robbie Williams] Bodies](https://osu.ppy.sh/beatmapsets/14279)
- [[ALTIMA] Burst The Gravity (TV Size)](https://osu.ppy.sh/beatmapsets/54839)
- [[Aqua] Candyman (Speedy Mix)](https://osu.ppy.sh/beatmapsets/7300)
- [[Barbie Young] DDR -- CARTOON HEROES (Speedy Mix)](https://osu.ppy.sh/beatmapsets/8245)
- [[Coldplay] Charlie Brown](https://osu.ppy.sh/beatmapsets/50831)
- [[Fall Out Boy] Dance, Dance](https://osu.ppy.sh/beatmapsets/43686)
- [[Queen] Don't Stop Me Now](https://osu.ppy.sh/beatmapsets/5381)
- [[Aqua] Dr Jones](https://osu.ppy.sh/beatmapsets/22856)
- [[C418] Droopy likes ricochet](https://osu.ppy.sh/beatmapsets/41545)
- [[Kim Leoni] Emergency (Nightcore Mix)](https://osu.ppy.sh/beatmapsets/45791)
- [[Cascada] Every Time We Touch](https://osu.ppy.sh/beatmapsets/4253)
- [[The Simpsons] Everyone hates Ned Flanders](https://osu.ppy.sh/beatmapsets/3900)
- [[Yasuharu Takanashi] Fairy Tail Main Theme](https://osu.ppy.sh/beatmapsets/13686)
- [[Owl City] Fireflies](https://osu.ppy.sh/beatmapsets/10550)
- [[Katy Perry] Firework](https://osu.ppy.sh/beatmapsets/22164)
- [[Lily Allen] F**k You](https://osu.ppy.sh/beatmapsets/7256)
- [[Pitbull ft. Ne-Yo, Afrojack & Nayer] Give Me Everything (Tonight)](https://osu.ppy.sh/beatmapsets/30426)
- [[Daft Punk] Harder, Better, Faster, Stronger](https://osu.ppy.sh/beatmapsets/9183)
- [[Klaus Badelt] He's a Pirate](https://osu.ppy.sh/beatmapsets/2587)
- [[F-777] He's a Pirate](https://osu.ppy.sh/beatmapsets/33119)
- [[Black Eyed Peas] I Gotta Feeling](https://osu.ppy.sh/beatmapsets/12668)
- [[Baracuda] I Leave The World Today (Special D. Remix Edit)](https://osu.ppy.sh/beatmapsets/6528)
- [[Hatsune Miku] levan Polkka](https://osu.ppy.sh/beatmapsets/1287)
- [[Eiffel 65] I'm Blue (Da Ba Dee)](https://osu.ppy.sh/beatmapsets/42481)
- [[Jason Derulo] In My Head](https://osu.ppy.sh/beatmapsets/14576)
- [[Nightcore] Jump Jump](https://osu.ppy.sh/beatmapsets/12191)
- [[Love Generation] Just a Little Bit](https://osu.ppy.sh/beatmapsets/48713)
- [[Baracuda feat. Groove Coverage] La Di Da (Nightcore Mix)](https://osu.ppy.sh/beatmapsets/44180)
- [[Barauda] La Di Da (Nightcore Mix)](https://osu.ppy.sh/beatmapsets/17852)
- [[Cascada] Last Christmas (Nightcore Mix)](https://osu.ppy.sh/beatmapsets/40717)
- [[Usher] More](https://osu.ppy.sh/beatmapsets/29006)
- [[Hanataba] Night of Knights](https://osu.ppy.sh/beatmapsets/5445)
- [[daniwellP] ico Nico Douga - Nyanyanyanyanyanyanya!](https://osu.ppy.sh/beatmapsets/31419)
- [[Melanie Flash] One in a Million (Nightcore Mix)](https://osu.ppy.sh/beatmapsets/37235)
- [[fripSide] only my railgun (TV Size)](https://osu.ppy.sh/beatmapsets/10067)
- [[Smash Mouth] Pacific Coast Party](https://osu.ppy.sh/beatmapsets/614)
- [[Jason Paige] Pokemon Theme (TV Edit)](https://osu.ppy.sh/beatmapsets/3733)
- [[Lady Gaga] Poker Face](https://osu.ppy.sh/beatmapsets/6297)
- [[Eric Cartman] Poker Face](https://osu.ppy.sh/beatmapsets/14672)
- [[Cascada] Ready For Love (Nightcore Mix)](https://osu.ppy.sh/beatmapsets/24899)
- [[Kana Hanazawa] Renai Circulation [TV Size]](https://osu.ppy.sh/beatmapsets/9573)
- [[Initial D] Running in the 90's](https://osu.ppy.sh/beatmapsets/2103)
- [[Mutsuhiko Izumi] Russian Snowy Dance](https://osu.ppy.sh/beatmapsets/38872)
- [[Darude] Sandstorm](https://osu.ppy.sh/beatmapsets/6180)
- [[Scatman John] Scatman](https://osu.ppy.sh/beatmapsets/18)
- [[Nintendo] Super Mario Bros Medley](https://osu.ppy.sh/beatmapsets/1281)
- [[Owl City] The Christmas Song](https://osu.ppy.sh/beatmapsets/40650)
- [[Haru] U.N. Owen was her? (Instrumental)](https://osu.ppy.sh/beatmapsets/7055)
- [[MT Nightcore] Welcome To The Club](https://osu.ppy.sh/beatmapsets/15489)
- [[The Village People] Y.M.C.A.](https://osu.ppy.sh/beatmapsets/745)
- [[Bangbros] Yeah Yeah Yeah! (Nightcore Mix)](https://osu.ppy.sh/beatmapsets/53096)
- [[Lazy Town] You Are a Pirate](https://osu.ppy.sh/beatmapsets/6626)

**Comment by nathanielcwm** [comment]
@Gabixel looks like we were having the same issue #3528
![screenshot1](https://cdn.discordapp.com/attachments/474530040894455811/496664478696603648/unknown.png)

**Comment by nathanielcwm** [comment]
Also looks like details doesn't load anything as well
![image](https://user-images.githubusercontent.com/22572406/46361650-c2332980-c6a0-11e8-9adc-cfe3ea902e56.png)

I'll add my beatmaps that aren't working here:
https://osu.ppy.sh/beatmapsets/92
https://osu.ppy.sh/beatmapsets/29161
https://osu.ppy.sh/beatmapsets/16520
https://osu.ppy.sh/beatmapsets/4851
https://osu.ppy.sh/beatmapsets/27936
https://osu.ppy.sh/beatmapsets/50763
https://osu.ppy.sh/beatmapsets/12341

**Comment by nathanielcwm** [comment]
Haven't tested your ones but all of my beatmaps that don't properly request scoreboards seem to use an osu file format that's v9 or older.

**Comment by peppy** [comment]
Maps listed above work correctly here.

**Comment by Gabixel** [comment]
I've just updated the list.. but, if you don't have this issue, there's probably a strange condition that make this error.

**Comment by plankp** [comment]
@Gabixel Could it be because of an osu-web update? Last update, a similar issue happened to me (chat also keeps on loading forever). Resolved after updating the client.

**Comment by nathanielcwm** [comment]
Still occurs with 2018.1023.0

**Comment by nathanielcwm** [comment]
actually now it's fine after i click on all of my beatmaps to update the leaderboards

**Comment by nathanielcwm** [comment]
![image](https://user-images.githubusercontent.com/22572406/47905321-c9c53880-dec1-11e8-8e26-65c9652d6eae.png)
actually nope looks like i just overlooked it

**Comment by peppy** [comment]
Please reimport the maps and see if that resolves the issue. It should. Note that to do so, you should delete all your loaded beatmaps, then restart lazer completely, *then* reimport maps.

**Comment by peppy** [comment]
Fine to close IMO
