### ISSUE TITLE
Auto play on CTB has bugs

### ISSUE THREAD

**Issue by lolita-is-godddd** [ppy/osu#3530]
With seeking, acc is not 100%, score doesn't decrease, and game doesn't erase sprite (fruit).
Build is "2018.928.0".
![osu_2018-10-03_21-51-39](https://user-images.githubusercontent.com/25249461/46411469-de919d80-c756-11e8-8315-2b89b43b724d.png)
[for debug.log](https://github.com/ppy/osu/files/2442043/debug.log)

**Comment by Hanamuke** [comment]
I've already opened PR #3518 to fix, autoplay accuracy. It still miss some fruits on 8*+ maps (1 miss on speed of link for instance), and the fruits are still buggy on rewind, but those are rendering issues.

**Comment by Hanamuke** [comment]
I'm expect there will still be problems on maps with stacked objects, i may right some further fixing, but that will be significantly more difficult to fix

**Comment by lolita-is-godddd** [comment]
thanks for work

**Comment by lolita-is-godddd** [comment]
also, speed up makes miss even catch correctly

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/6032, not sure about the linked PR now.
