### ISSUE TITLE
Classic scores will cover other elements during gameplay

### ISSUE THREAD

**Issue by ringosham** [ppy/osu#3531]
A very minor issue. Just simply have a look at the screenshot.
![screenshot 2](https://user-images.githubusercontent.com/7325740/46419335-95752580-c725-11e8-9687-575906e23edc.png)

**Comment by Hanamuke** [comment]
Aren't scores supposed to be limited to 1 000 000 + spinners ?

**Comment by smoogipoo** [comment]
The "classic" scoring mode has no such limitation.

**Comment by peppy** [comment]
Needs some better flow logic.
