### ISSUE TITLE
Chat contains char, is out of ascii, makes broken

### ISSUE THREAD

**Issue by lolita-is-godddd** [ppy/osu#3537]
e.g. 
![osu_2018-10-04_22-47-37](https://user-images.githubusercontent.com/25249461/46478269-89718c80-c827-11e8-95cb-32a2e51e406d.png)
Typed "てすと" (means test in japanese), but appeared broken charcters instance of that.

**Comment by Hanamuke** [comment]
Duplicate of #3230 i think

**Comment by smoogipoo** [comment]
Closing as duplicate.
