### ISSUE TITLE
[Proposal]beatmap label clicking

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3540]
when there's only one difficulty in beatmapset if you click main label not difficulty label it could start gameplay too

**Comment by Gabixel** [comment]
Can be interesting for songs with multiple difficulties too, like a substitute for the osu! logo on bottom-right corner to play the selected difficulty. Not really useful but seems more natural I guess

**Comment by peppy** [comment]
I disagree this feels more natural. When clicking the easer it should probably flash the difficulties to let the player know where to click, though.
