### ISSUE TITLE
Hitobject placement design style

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#3547]
Hitobject selections and placements are displayed as "masks", which sit as a layer on-top and overlay the underlying hitobjects.

Hitcircle selection:
<img width="224" alt="image" src="https://user-images.githubusercontent.com/1329837/46526402-20daec00-c8c9-11e8-8eec-fdb76f541b3b.png">

Slider selection:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/1329837/46526409-26d0cd00-c8c9-11e8-972e-c8246381fd72.png">

For placement, the underlying hitobject doesn't exist, so I'm using the same mask as for selection. These generally follow the cursor:

Hitcircle placement:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/1329837/46526500-5f70a680-c8c9-11e8-957c-38ef7aa45619.png">

Which, after clicking, places the underlying hitobject:
<img width="211" alt="image" src="https://user-images.githubusercontent.com/1329837/46526529-78795780-c8c9-11e8-8daa-6ca93c905210.png">

For sliders, they start out as hitcircles, which drag out to form the head and tail. They're joined by the slider path:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/1329837/46526559-8cbd5480-c8c9-11e8-8eb8-26dcf58a3499.png">

By clicking, you add a control point:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/1329837/46526588-a494d880-c8c9-11e8-8d14-56c1a975b234.png">

By double clicking you add a segment (shown as a red controlpoint):
<img width="881" alt="image" src="https://user-images.githubusercontent.com/1329837/46526967-cb9fda00-c8ca-11e8-9ba4-67d09c99a120.png">

And again, the underlying slider is placed when right-clicking:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/1329837/46527025-e83c1200-c8ca-11e8-989f-f25b6aa3de61.png">

This all looks very "raw" right now...

1. We're going to need a grid at some point (I was sort of imagining the placement layer to have a half-opaque background, thoughts?).
2. The border-circle as the placement object looks very empty imo. At the very least it needs a crosshair.
3. In general everything looks raw.
4. We're going to need a way to choose the type of segment for sliders - bezier, linear, circular.
5. Control points are going to need to be draggable when they're part of the selected slider.

@arflyte requesting a designer-san to look into proper visuals for the masks.

**Comment by jvyden420** [comment]
This may sound like a stupid idea, but I think that the different types of circles should be color coded. (red for circles, blue for sliders or something...) I get confused sometimes when editing and realized what I thought was a hitcircle was actually a slider, so I end up wasting a whole 2.5 seconds.

**Comment by peppy** [comment]
We're just self-designing this at this point.
