### ISSUE TITLE
Can't auto update

### ISSUE THREAD

**Issue by lolita-is-godddd** [ppy/osu#3550]
I accepted update from 2018.928.0, and launched osu!.exe. But "Cannot access specified path, directory, or device. Maybe you didn't permitted." message appeared. I also tried run Update.exe with `update --install 2018.1004.1` manually. It ran a few seconds, but closed silent.
Should I re-download install.exe on `20181004.1`?
[SquirrelSetup.log](https://github.com/ppy/osu/files/2450279/SquirrelSetup.log)

**Comment by Hanamuke** [comment]
Have you tried running as administrator ?

**Comment by lolita-is-godddd** [comment]
The administrator has been to somewhere, either can't connect.
If you meant propaty, tried, and same.

**Comment by lolita-is-godddd** [comment]
I'm stupid, `update --install app-2018.1004.1`, got it: ```
2018-10-06 23:01:28> Program: Starting Squirrel Updater: --install app-2018.1004.1
2018-10-06 23:01:29> Program: Starting install, writing to C:\Users\Obsidian550D\AppData\Local\osulazer\app-2018.1004.1
2018-10-06 23:01:29> Unhandled exception: System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.InvalidOperationException: シーケンスに要素が含まれていません
   場所 System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   場所 Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Squirrel.Update.Program.executeCommandLine(String[] args)
   場所 Squirrel.Update.Program.main(String[] args)
---> (内部例外 #0) System.InvalidOperationException: シーケンスに要素が含まれていません
   場所 System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   場所 Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```

**Comment by Hanamuke** [comment]
What does the manual build say ?

**Comment by lolita-is-godddd** [comment]
I meant packageing exe from source code (release > src.zip) by vscode using C# extension and Runner extension.

**Comment by lolita-is-godddd** [comment]
Yesterday I retried run ozulazer, then it works (and updated 1004.1)

**Comment by lolita-is-godddd** [comment]
It might happen sometimes, but when??????????
(Just update 2018.1228 -> 2019.117, happen.)

**Comment by peppy** [comment]
Could you pleaseinclude the error / logs this time too?

**Comment by Joehuu** [comment]
Closing as there haven't been update issues reported recently.
