### ISSUE TITLE
NightCore on CTB

### ISSUE THREAD

**Issue by lolita-is-godddd** [ppy/osu#3552]
TL;DR:
- freezes on some map at begin the game (e.x. [Fright March](https://osu.ppy.sh/beatmapsets/486142#fruits/1038400) , but not always)
- converted long sliders (idk name) for ctb are very slow in drawing
- freeze and exit when too many fruit (e.x. [Der Wald](https://osu.ppy.sh/beatmapsets/406881#fruits/884085))

version is 2018.928.0 (2018.1004.0 and .1 are could not build correctly, #3550).

**Comment by LastExceed** [comment]
please link the example map. judging by your encounter of the window being faded in white I assume you use windows?

**Comment by lolita-is-godddd** [comment]
yes, I ran on Windows 7, x64.
Also, edit for link.

**Comment by smoogipoo** [comment]
Never before have I seen osu!lazer doing 50k cached refreshes per frame. That Der Wald map is a good benchmark.

**Comment by smoogipoo** [comment]
Can you clarify what "NC" means?

**Comment by LastExceed** [comment]
Probably NightCore

**Comment by lolita-is-godddd** [comment]
yes

**Comment by Joehuu** [comment]
Doesn't seem to freeze at all on those maps on latest release (and also doubt nightcore was the cause), closing as resolved.
