### ISSUE TITLE
Pre-loaded channels aren't marked as joined

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3554]
I noticed this from a few releases, I guess this happens from the release for the new API version (#3494):
## Issue
Pre-loaded channels aren't marked in `Chat Channels` as joined (except for `#lazer` and `#osu`: they are marked)
## Video (no audio)
https://streamable.com/hhbsn
In the video, I show `#italian` and `#help` channels as an example, then I try to close them (with middle mouse, to clarify), and opening them again solves the problem (but it would not surprise me if reopening the game the issue appears again).

**Comment by plankp** [comment]
Seems to have reoccurred in 2018.1120.0

![image](https://user-images.githubusercontent.com/7527421/48767072-dbf5f380-ec83-11e8-9186-d2695148f670.png)
