### ISSUE TITLE
After updating, osulazer closes and opens osu!.dll

### ISSUE THREAD

**Issue by Flanster** [ppy/osu#3555]
Yeah thats a thing, Last two times I've updated when it finishes applying an update it opens osu!.dll in whatever program I have associated with said file extension.

**Comment by smoogipoo** [comment]
I thought this was fixed with our squirrel fork... o_O

**Comment by peppy** [comment]
All I can think is that the user's `update.exe` is an old version and not being replaced for whatever reason.

@Flanster please try reinstalling from the github releases page. Do not uninstall first.

**Comment by Flanster** [comment]
Ah so thats why it kept saying delta patching failed before each update.
I've reinstalled as you instructed, will post here again when an update happens.

**Comment by peppy** [comment]
Just to confirm: the update from .0 to .1 works correctly?

**Comment by Flanster** [comment]
Yes.
