### ISSUE TITLE
Raw Input Makes Cursor Move on its Own

### ISSUE THREAD

**Issue by MEXdave1997** [ppy/osu#3559]
Hi All! So I downloaded osu!Lazer through the releases tab,a dnI figured I would try to get my preferences back to how I have them on the older version of osu!. However, as soon as I turned on Raw Input, my mouse all of a sudden decided to start moving without me moving the mouse at all across the screen. This is an odd bug, and I was wondering if I there is anyway to revert the Mouse Input setting (since I can't even click on the setting to turn it off >.<).

**PC Specs:** 
1. Intel i7-5500U
2. 8GB DDR3 RAM
3. Windows 10 Education
4. Razer Aetheris Wireless Mouse (using Bluetooth Functionality - broke included receiver, need to RMA)

**Comment by AtomCrafty** [comment]
This issue has been reported numerous times already.
You can revert your settings by deleting `%appdata%\osu\framework.ini`.

**Comment by MEXdave1997** [comment]
I understand this issue has been reported dozens of times, but my experience is as described, which is something that I haven't actually read about in any of the other issues :/

Sorry for clogging it though I guess. I fixed it and will stay away from the raw input setting until it gets resolved in later builds.

**Comment by peppy** [comment]
Ctrl-Alt-Shit-R resets input settings.

I haven't heard of movement happening on its own. Could you please take a video of what you're seeing?

**Comment by Leeo97one** [comment]
Do you mean, like this: https://youtu.be/lsfJ96dCIL0 ?

**Comment by MEXdave1997** [comment]
Yup, pretty much... looks like I should have dug for more issues (was probably buried in there)... 😅

**Comment by Joehuu** [comment]
Closing as stale. Raw input (now high precision mouse) should be better now (at least for Windows).
