### ISSUE TITLE
Line between hit objects appear before hit objects appear

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3560]
On 2018.1004.0, https://osu.ppy.sh/beatmapsets/596704#osu/1262832 (that particular difficulty),
The line (dotted line?) between the hit objects appear as soon as the song starts.

While I am not sure if this happens on stable, seeing the line before the hit objects appear does not look right...

![image](https://user-images.githubusercontent.com/7527421/46589409-3a219b00-ca77-11e8-85ca-e3db31b5862c.png)

**Comment by Morilli** [comment]
Related/duplicate to #3043

**Comment by plankp** [comment]
If it is related, then the problem described also happens on macs as well. Not just on Windows.

**Comment by bdach** [comment]
Double-checked this map and it looks correct as far as I can tell now, so closing as stale/resolved.
