### ISSUE TITLE
Switch taiko controller is not working

### ISSUE THREAD

**Issue by LovelyA72** [ppy/osu#3561]
This new controller works fine on osu!stable. 
The tako controller for Nintendo Switch is not working on lazer.
When configuring the controller, the game can recognize the controller and display the key that I hit. But in the game, there is a big, unplayable delay.
I can record a video tonight.

**Comment by peppy** [comment]
This sounds like it could be related to the driver you are using to map the controller's bluetooth to a HID device. Are you able to notice a similar latency in other games with gamepad support?

**Comment by LovelyA72** [comment]
This is not a bluetooth device. This drum uses USB cable (connect with switch dock)
And the computers will recognize it as a regular game controller.(Can be used as a nes controller on fceux)

**Comment by LovelyA72** [comment]
[runtime.log](https://github.com/ppy/osu/files/2460675/runtime.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2460676/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2460680/performance-gamethread.update.log)

Just reproduced on my own computer. And here are some logs if they help.

**Comment by goatdavid** [comment]
i assume you are trying to use the actual taiko drum, and not joy-con?

**Comment by LovelyA72** [comment]
Yes,the USB taiko drum for Nintendo switch that works fine on osu!stable.

**Comment by goatdavid** [comment]
okay--i was just trying to clarify because joycon via Bluetooth doesn't
work on stable, I think it doesn't know how to interpret motion or you need
to use a third party mapper

**Comment by LovelyA72** [comment]
Update: Xbox one controller on USB mode have the same issue. Bluetooth mode not 
yet tested.

**Comment by peppy** [comment]
Please test with a more recent release, as much progress has been made on controller support. Feel free to reopen if it's still not working.
