### ISSUE TITLE
How to get the score of the live end window?

### ISSUE THREAD

**Issue by C8N16O32** [ppy/osu#3581]
I want to make a program that shows the scores of the small windows on the live side. 
These programs will be used for live head to head mode.
How can I make the program "know" these scores?(requires the location of the relevant page)

**Comment by smoogipoo** [comment]
Do you mean the scores of all players that's displayed at the left side of the screen? There's no public API for this at the moment.

**Comment by C8N16O32** [comment]
>           Do you mean the scores of all players that's displayed at the left side of the screen? There's no public API for this at the moment.

This is not the case. I am referring to the live broadcast started after joining tournament.cfg in the osu folder. The score in the upper right corner of each window displayed in the live broadcast.

**Comment by peppy** [comment]
You are talking about the stable client. Such questions are currently handled on the forumss (but I can't guarantee any response here, since this data endpoint is not implemented and we don't have the resource to add it right now).
