### ISSUE TITLE
Viewing beatmap information freezes the draw thread, until details have been loaded

### ISSUE THREAD

**Issue by WRMSRwasTaken** [ppy/osu#3582]
When browing with osu!direct and clicking on a beatmap with a black background (then there are no information prefetched for this beatmap I think), It'll freeze the draw thread, until all information for that selected beatmap have been loaded, but the music keeps playing. So I think it's a download thread / job which blocks the draw thread, until fetching all information from the API has been finished.

When waiting in the list for selecting / searching beatmaps for the background picture to load, then viewing the detail of that beatmap is no issue.

I don't know which update caused this, but this hasn't been an issue a few releases ago. I'm noticing this, because my internet here is somewhat slow, causing this those times.

Since my gif exceeds GitHub's 10MB limit, I uploaded it to imgur: https://imgur.com/a/sp519bi

While trying to get back into developing C#, I'm seeing a lot of messages like 
```
[performance:verbose] Drawable [DrawableRank] took 709,84ms to load and was not async!
[performance:verbose] Drawable [DrawableScore] took 1571,85ms to load and was not async!
```
when this happens.

**Comment by Joehuu** [comment]
Did #5042 resolve this issue?

**Comment by peppy** [comment]
Yep, thanks.
