### ISSUE TITLE
Ability to hide mouse cursor in certain game modes

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3587]
For example, in osu mania or catch (without the mod), there should be an option to hide the mouse cursor

**Comment by Hanamuke** [comment]
I have openened PR #3449 for that. I've been asked to change a few things i'll get back on it

**Comment by Hanamuke** [comment]
Although it's not exactly the same, for instance. If a player want to use mouse clicks for instance the cursor will be visible since it's not idle.

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/2901
