### ISSUE TITLE
Run slowly on specific map and memory management problem

### ISSUE THREAD

**Issue by FlintyLemming** [ppy/osu#3588]
spent long time to load a specific map and run slowly (about 1 frame per 3 seconds)
and won't release used memory after a quit this map
map link:https://osu.ppy.sh/beatmapsets/470977#osu/1006822

Compuer Spc
CPU  -  i7-4790K
Memory  -  16GB
Video Card  -  RX 560
System  -  macOS 10.14.1 Beta

video:
https://youtu.be/GXzQF4uaBDw

**Comment by Wieku** [comment]
It's not a problem with this map exclusively. Lazer suffer from too much update and hitobject render overhead, because storyboard rendering is batched (so it should render in the same time as in osu!stable). I get like 70-300fps on NOMA - Brain Power [Overdrive] on GTX1070, which is pretty low.

**Comment by Wieku** [comment]
I think it can be partially connected to #3252

**Comment by peppy** [comment]
Tracking via #3756.
