### ISSUE TITLE
Reimporting beatmaps with no changes does not cause a reprocess to occur

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3589]
Steps to reproduce:
1. Delete some beatmap that hasn't got status field about being ranked(only to see effects)
2. Reimport all beatmaps from stable(assuming that dleted beatmpa was there)
3. Status field isn't generated.
4. Delete this beatmap again.
5. Close osu!.
6.Open osu! and reimport all beatmaps. Status field is generated.

logs:
[database.log](https://github.com/ppy/osu/files/2475862/database.log)
[debug.log](https://github.com/ppy/osu/files/2475863/debug.log)
[network.log](https://github.com/ppy/osu/files/2475864/network.log)
[performance.log](https://github.com/ppy/osu/files/2475865/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2475866/runtime.log)

**Comment by Aergwyn** [comment]
That is intended. If you delete a beatmap(set) it's only marked and only really purged on closing osu!-lazer. Regarding ranked status, there's no update functionality yet. So only fresh imports fetch it.

**Comment by ToIGLAK** [comment]
In options menu there is an option to recover deleted songs.

**Comment by peppy** [comment]
Updating of existing beatmaps will be eventually added.

**Comment by peppy** [comment]
This has actually been fixed now. If a beatmap is reimported it will be re-queried.
