### ISSUE TITLE
[proposal] icons on beatmap info wedge shouldn't move

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3591]
i mean these small icons on bottom that contain info about e.g. how many circles are in beatmap.
the reason for this propasl is that this move don't look smooth/natural; it could stay in one place to let only numbers change
video:
https://drive.google.com/open?id=1hEkvdcKE6H9QE4FJoLFPnFw4dd3QqVG6

**Comment by Joehuu** [comment]
Closing, already addressed in the new design with a different layout and is not worth tracking here.
