### ISSUE TITLE
[Proposal] osu! should be distributed as a Self-Contained app

### ISSUE THREAD

**Issue by sr229** [ppy/osu#3592]
Prior  to ppy/osu-deploy#1, In the Linux case I used `--self-contained` flag so its easier to package as a AppImage.

However I think we can extend the following to current platforms for the reason:

- Easier package management. SCD apps contain the app's dependencies and the .NET Core Runtime with the exception of its native dependencies.

- it generates a executable binary, depending on runtime, which is close to the .NET Framework compile target.

**Comment by peppy** [comment]
As discussed, it's default true. Nothing would have worked if this wasn't the case.

**Comment by smoogipoo** [comment]
It's default `true` if a runtime specifier is present, to be precise. Which should work in OP's case already.

Closing.
