### ISSUE TITLE
Occasional loud audio clipping in menu

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu#3601]
Sometimes after a few minutes of running lazer, in the song select the game's audio will clip and create a loud sound at the computer's max volume for a fraction of a second which is quite painful to hear.

I've had this issue happen around a dozen times over the past few months, but I don't have video of it because it's pretty random and to record sound on osx I need to disable headphone output, which means I won't know if the issue happened.

(unsure if logs needed and where to find)

**Comment by AtomCrafty** [comment]
Sounds similar to #3401

**Comment by Xinnoh** [comment]
seems like it, searched for loud / sound / clipping / audio, didn't find any matching titles
