### ISSUE TITLE
After failed map key overlay still counts key clicks

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3603]
when you fail a map key overlay still counts key clicks but not updates key state(clicked/not clicked)
checked for mania and osu!standard
this doesn't occur when you pause the game

logs:
[database.log](https://github.com/ppy/osu/files/2489268/database.log)
[debug.log](https://github.com/ppy/osu/files/2489269/debug.log)
[network.log](https://github.com/ppy/osu/files/2489270/network.log)
[performance.log](https://github.com/ppy/osu/files/2489271/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2489272/runtime.log)

**Comment by iiSaLMaN** [comment]
I don't think that issue is present now, this can be closed.

**Comment by peppy** [comment]
Still counts during the fail transition, but I don't see this as being incorrect.
