### ISSUE TITLE
osu!lazer beatmap dropping is broken on Linux

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#3619]
Just tested with Manjaro, built directly from source, and beatmaps will not drag and drop to import.

Current workaround seems to be `dotnet /path/to/osu!.dll /path/to/a/beatmap/file.osz`

**Comment by morguldir** [comment]
Duplicate of #3444 

Fixed by: https://github.com/ppy/opentk/pull/29

**Comment by Frontear** [comment]
Closing the issue then.
