### ISSUE TITLE
Osu crashes at startup on Mac OSX

### ISSUE THREAD

**Issue by Scurax** [ppy/osu#3621]
The game crashes instantly as soon as i open it, i dont know where to find logs, but if i can do anything to help fix this problem, i will # #

**Comment by peppy** [comment]
You may be able to find logs in `.local/share/osu/logs`. Also please let us know which version of macOS you are on.

**Comment by Scurax** [comment]
[database.log](https://github.com/ppy/osu/files/2506549/database.log)
[debug.log](https://github.com/ppy/osu/files/2506550/debug.log)
[performance.log](https://github.com/ppy/osu/files/2506551/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2506552/runtime.log)
Im on Mac OSX Mojave

**Comment by morguldir** [comment]
This will be resolved by https://github.com/ppy/osu-framework/pull/1961

For now you will have to uninstall SDL2, likely with `brew uninstall sdl2`

**Comment by Scurax** [comment]
> This will be resolved by [ppy/osu-framework#1961](https://github.com/ppy/osu-framework/pull/1961)
> 
> For now you will have to uninstall SDL2, likely with `brew uninstall sdl2`

you sure? i dont even have homebrew installed

**Comment by VPeruS** [comment]
Try run app from console, it may produce some additional info, pack output into file and pin here.

**Comment by Scurax** [comment]
> Try to run app from console, it may produce some additional info, pack output into file and pin here.

nothing happened, just ran the app, nothing on the console except the command prompt entry and the usual closing process stuff

**Comment by VPeruS** [comment]
Can you submit it?

**Comment by morguldir** [comment]
Could you search for `libSDL2.dylib` on your system?

**Comment by Mahua233** [comment]
ffmpeg is required to sdl2.
> Error: Refusing to uninstall /usr/local/Cellar/sdl2/2.0.8
because it is required by ffmpeg, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies sdl2

maybe wait for new release is better.

**Comment by peppy** [comment]
This should be fixed in our next release, which forcefully ignores SDL. It should be available tomorrow.

**Comment by Scurax** [comment]
Thanks a lot guys, sdl2 is on my system, strangely osu is working fine out of nowhere, i checked the log directory and it was all deleted tho... probably ccleaner deleted them, but it probably deleted what was creating the problem

**Comment by peppy** [comment]
We actually fixed this in the latest release! Good to know it worked.
