### ISSUE TITLE
Profile detail display does not truncate excess text

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ppy/osu#3633]
Where the website truncates lengthy text and adds an ellipsis, the game client tries to display the entire text without truncating which causes it to overflow.

[Comparison between game client and web](https://imgur.com/a/rGLsv4j)

**Comment by swstegall** [comment]
A similar issue exists when strings are too long on a given line, as demonstrated [here.](https://imgur.com/a/OXJcwKa)

**Comment by Joehuu** [comment]
Fixed in new design (by expanding).
![](https://puu.sh/DlOzT/54c2b61e2c.jpg)
![](https://puu.sh/DlOAa/d8599a5807.jpg)

**Comment by peppy** [comment]
These should probably be server side limited, but yeah, fixed for now.
