### ISSUE TITLE
"pending" state of beatmap isn't showed on beatmap listing

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3634]
[database.log](https://github.com/ppy/osu/files/2512445/database.log)
[debug.log](https://github.com/ppy/osu/files/2512446/debug.log)
[network.log](https://github.com/ppy/osu/files/2512447/network.log)
[performance.log](https://github.com/ppy/osu/files/2512448/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2512449/runtime.log)
![osu_2018-10-24_23-37-23](https://user-images.githubusercontent.com/32620809/47463725-551a3c00-d7e7-11e8-92fd-ffd74849d099.jpg)

**Comment by ticotaco72** [comment]
propably the same isuue as #3635

**Comment by peppy** [comment]
Closing as duplicate – see other issue for potential solution.
