### ISSUE TITLE
OSU! eating up all the CPU on macOS

### ISSUE THREAD

**Issue by Naville** [ppy/osu#3636]
Hi:
Just tried the latest release for macOS and it seems like it quickly eats up all the CPU. FPS is quite stable at around 15fps which, apparently, makes osu! unplayable
[runtime.log](https://github.com/ppy/osu/files/2513350/runtime.log)
[debug.log](https://github.com/ppy/osu/files/2513351/debug.log)
[database.log](https://github.com/ppy/osu/files/2513352/database.log)
[performance.log](https://github.com/ppy/osu/files/2513353/performance.log)
[network.log](https://github.com/ppy/osu/files/2513354/network.log)

Running OSU! in windowed mode seems fine, however it seems like there is some issue with mouse capturing so after some window switching, the pointer in osu and the OS's mouse pointer is separate and completely out of sync

**Comment by Naville** [comment]
It was all good until I decided to actually play a map in mania mode, as you can see from the screenshot the kernel almost instantly ate all the CPU power available, this issue persists even after I leave the song and return to main screen
<img width="395" alt="image" src="https://user-images.githubusercontent.com/5205699/47477360-caecca80-d81c-11e8-88ca-1bb9b28515e6.png">

However, as soon as I force quit osu(Command+Q), the CPU usage dropped back to normal almost instantly
<img width="309" alt="image" src="https://user-images.githubusercontent.com/5205699/47477412-0be4df00-d81d-11e8-8428-c8978cbba203.png">


Since this issue seems to relate to kernel, I also tried to list my current installed kernel extensions:

```
λ : >>> kextstat | grep -v com.apple
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
   83    0 0xffffff7f80e70000 0x17f000   0x17f000   at.obdev.nke.LittleSnitch (5207) 9FEE069A-6B44-395D-B154-411C856CB951 <7 5 4 3 1>
  169    0 0xffffff7f810c8000 0x41000    0x41000    com.paragon-software.filesystems.ntfs (11.4.15) F1DBCE74-4409-37F5-9291-9B2E23D6F578 <7 5 4 1>
  180    0 0xffffff7f810b8000 0x9000     0x9000     com.steelseries.ssenext.driver (1.6.11) 9E56C506-F1EF-3BA5-9517-D7C42B6D522B <42 5 4 3>
  183    0 0xffffff7f84d1e000 0x19000    0x19000    com.github.kbfuse.filesystems.kbfuse (3.8.2) AD9F1D6C-A49E-3EBA-8CAA-3A1382719128 <7 5 4 3 1>
```

Which in my humble opinion have very little to do with osu

**Comment by Naville** [comment]
I did some further digging by kextunloading SS's kext and seems the issue no longer persists. Still I'm not entirely sure if this is a osu bug or should I blame SS. Since Google didn't show up any other use with similar issue

**Comment by sr229** [comment]
Trying to reproduce on a Macbook Air and I can't seem to reproduce it. osu! seems to operate fine within standard CPU metrics.

**Comment by Naville** [comment]
Yeah I digged around and it seems only reproducible with SteelEngine and its kernel extension up and running. I'm currently using their keyboard and mouse as well. I'm not sure if it's a bug on SteelSerie's Kernel Extension or something wrong with osu, though
