### ISSUE TITLE
osu!lazer daycore glitch

### ISSUE THREAD

**Issue by 00023** [ppy/osu#3645]
[18-1746.zip.003.zip](https://github.com/ppy/osu/files/2521324/18-1746.zip.003.zip)

unzip with 7zip or winrar and convert to video

**Comment by AtomCrafty** [comment]
Your zip file is incomplete. You probably only attached part 3 of multiple.

**Comment by 00023** [comment]
ok ill try to put part of the video in

**Comment by smoogipoo** [comment]
Upload to youtube or streamable.

**Comment by 00023** [comment]
dont have either

**Comment by 00023** [comment]
how do i cut part of a video off so it fits the 10mb limit

**Comment by Lolihunter1337** [comment]
@00023 For Streamable you dont need an account

**Comment by peppy** [comment]
Please actually provide a text description of what is wrong and use something like youtube to upload the video.

**Comment by 00023** [comment]
sorry! got flagged when trying to upload files so here is the link https://streamable.com/ebzcz

**Comment by 00023** [comment]
here is the correct link https://streamable.com/4ynzg

so what happens is that all the speed changing mods breaks the music expect daycore but playing with daycore lags hard

**Comment by AtomCrafty** [comment]
wait... did you just link a video without audio to demonstrate that the game music is playing incorrectly?

**Comment by 00023** [comment]
it was both 
So where do i put the audio? streamable does not support audio

**Comment by AtomCrafty** [comment]
Of course Streamable supports audio, just look at the first video you linked...
I'm not sure anymore whether this is a legitimate issue or just an attempt at wasting everyone's time.

If you want help resolving a problem, please provide us with the necessary information.
Since you seem to have issues with audio and performance, a good start would be to name your operating system and audio driver manufacturer, as well as attach the log files generated by lazer (found under `%appdata%\osu\logs` on windows or `~/.local/share/osu/logs/` on linux).

**Comment by 00023** [comment]
[network.log](https://github.com/ppy/osu/files/2532364/network.log)
[performance.log](https://github.com/ppy/osu/files/2532365/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2532366/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2532367/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2532368/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2532369/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2532370/runtime.log)
[database.log](https://github.com/ppy/osu/files/2532371/database.log)
[debug.log](https://github.com/ppy/osu/files/2532372/debug.log)

**Comment by ohyeahsoldier** [comment]
Sorry for (probably) breaking some necro etiquette, but 727 this is the worst github issue I've ever seen
