### ISSUE TITLE
Change the way that zero's are handled in the game client?

### ISSUE THREAD

**Issue by nathanial292** [ppy/osu#3647]
Hi there, this problem has plagued me for my entire time on osu, my name in the game is "b00" with two zeros. https://osu.ppy.sh/users/3929650
<img width="885" alt="sharex_2018-10-27_18-29-42" src="https://user-images.githubusercontent.com/26060905/47607325-482f5f80-da16-11e8-8f42-f650b8abbbc9.png">

The problem is that when in game, zeros are handled the same way as "o"'s (the character)
I have a couple ranked maps in the game and I think it is frustrating for other people when they see my name in the game client, and they try to get to my userpage or find out about me. Only to end up with this completlely inactive person: https://osu.ppy.sh/users/3540539
![osu _2018-10-27_18-28-06](https://user-images.githubusercontent.com/26060905/47607308-13bba380-da16-11e8-9e40-32332aa0b695.jpg)

If this is at all possible to fix it would be very cool to see! Thank you for taking your time to read my problem, have a good day :)

**Comment by HoLLy-HaCKeR** [comment]
How do you mean, they are "handled the same"? They are 2 different characters, the only this that is similar is how the font renders them. Are you suggesting to make changes to the default font so it's easier to tell the difference? Because I don't think that's likely going to change.

**Comment by jorolf** [comment]
This repository is for osu!lazer only.
fyi lazer uses the same font as the website meaning that you won't have that problem in lazer.

**Comment by nathanial292** [comment]
Yes they are 2 different characters, however the way the game engine renders them makes them look indentical. Even in chats and what not the characters appear the same. I'm just suggesting that the font used should make the zero actually look like a zero

**Comment by HoLLy-HaCKeR** [comment]
I'm not sure if we're even allowed to edit the font according to the license, but it doesn't really seem like much of a problem with Exo 2:
![image](https://user-images.githubusercontent.com/13605369/47607395-cc3a1500-da1f-11e8-805d-391943909060.png)

**Comment by nathanial292** [comment]
Exo 2? I checked lazer and thats working correctly, so at least thats working but if it is possible to change it in the normal client that would be nice to see.

**Comment by HoLLy-HaCKeR** [comment]
Exo 2 is the name of the main font that lazer uses. The stable client uses a different font (Aller, most likely) but this is not the place for issues related to stable. You should be at the forums for that.

**Comment by nathanial292** [comment]
I didn't know that. Do you mean just the web forums? Can I get a link?

**Comment by HoLLy-HaCKeR** [comment]
[Feature Requests subforum](https://osu.ppy.sh/community/forums/4)
