### ISSUE TITLE
32-bit version

### ISSUE THREAD

**Issue by Liebelts** [ppy/osu#3651]
Hey a time ago i discovered the game doesnt run in 32-bit computers so if you can do a 32 bit version i would be thankful

**Comment by smoogipoo** [comment]
Duplicate of https://github.com/ppy/osu/issues/3524 .

32-bit binaries are not provided right now. Feel free to go ahead and compile osu! yourself.

**Comment by Liebelts** [comment]
But doing it as last plan isn't viable ?

**Comment by smoogipoo** [comment]
You're part of the literal 1%, it just isn't worth it at this point to get all the systems in place (redistribution + updater) while development efforts are focused elsewhere.

**Comment by Liebelts** [comment]
Oh OK sorry
