### ISSUE TITLE
Odd StartTime and EndTime values for older mania converted beatmaps

### ISSUE THREAD

**Issue by Adrriii** [ppy/osu#3659]
When converting a [very old standard beatmap](https://osu.ppy.sh/beatmapsets/3#osu/91) to mania using ManiaBeatmapConverter, the HitObjects that were generated contained odd StartTime and EndTime values.

I don't know if it's intentionnal, but when writing these to console : 
- maniaHitObject.StartTime.ToString()
- (maniaHitObject as HoldNote).EndTime.ToString()

I would either get a normal Time (in ms relative to beginning of the map), or a string with this format : 
Time,UnknownNumber

[Example when I print the HoldNote objects of the map i stated earlier](https://cdn.discordapp.com/attachments/280800346484244480/506842077028548608/unknown.png)

It happened with a Note object as well

**Comment by smoogipoo** [comment]
Please make a new issue if this is still valid.
