### ISSUE TITLE
Starting a map gave an error and loaded another map

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3666]
No idea how to reproduce this it happend random
[runtime.log](https://github.com/ppy/osu/files/2537544/runtime.log)

**Comment by qwewqa** [comment]
Seems that this happens if the beatmap is changed right as you start a stage. Haven't had it randomly happen, but if you spam an arrow key for a while to change beatmaps and hit enter while the animation is still playing I'm able to get the same error.

**Comment by Lolihunter1337** [comment]
yea just tried that and it happend as well.

**Comment by peppy** [comment]
I do not believe this is still possible.
