### ISSUE TITLE
Cannot fix specified missing dependencies during build (linux)

### ISSUE THREAD

**Issue by LinuxGamer** [ppy/osu#3669]
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbass: cannot open shared object file: No such file or directory

can someone help me?

**Comment by LinuxGamer** [comment]
System: ElementaryOS 5.0 Juno [Based on Ubuntu 18.05]

**Comment by morguldir** [comment]
https://github.com/ppy/osu#building-and-running

Note: If you run from command line under linux, you will need to prefix the output folder to your LD_LIBRARY_PATH. See .vscode/launch.json for an example
