### ISSUE TITLE
Game crashes when trying to take a screenshot

### ISSUE THREAD

**Issue by czapek1337** [ppy/osu#3672]
I've built osu! from source, using latest master (as of 03/11/2018 03:43 am)

I can't really debug it, I think it's because of the screenshot handler being asynchronous, I've placed breakpoints in screenshot handler on both `shutter.Play();` and `TakeScreenshotAsync();`, but as soon as the first gets hit, the game closes, and debugger detaches making it unable for me to debug it.

The only debug info I may rely on is this: https://gist.github.com/cyanidee/17830248048b7acd826985641a332dcf
It exits with message "Access violation", which could mean that it couldn't save the screenshot. I am not sure, if it's not related to my git repository being on other drive than the system one. From what I've seen osu! saves debug logs to `%appdata%\osu`, while the "installation" is somewhere else.

**Comment by cyanidee** [comment]
Some more debugging info after I disabled "Just my code" debugger setting, now it seems to show a bit more stuff, but still nothing I can understand, nor use to fix the issue: https://gist.github.com/cyanidee/53de9bc34c821e9dbe0f439a98f09855

**Comment by UselessToucan** [comment]
Did you check Windows event viewer? It may contain some exceptions from osu!.

> I am not sure, if it's not related to my git repository being on other drive than the system one.

This is not related, I store osu! on a separate HDD and making screenshots works ok(commit 54fede4559d739dfbe86ec6d6f2bb8d01e8b2df4).

**Comment by qwewqa** [comment]
I believe that f12 is reserved on windows for the debugger. Does this happen if you use a different keybind for screenshots or if you run without the debugger?

**Comment by peppy** [comment]
Closing this one for now. Haven't seen it happen and is probably not a thing any more (seemed like it may have been something specific to the user's setup anyway - overlays or drivers doing something weird).
