### ISSUE TITLE
broken custom-made skin from stable

### ISSUE THREAD

**Issue by Arimodu** [ppy/osu#3673]
if i use this skin in Osu!lazer it turns the game in to a "pro mode" 
here is the skin and video of the game

[fni.zip](https://github.com/ppy/osu/files/2545083/fni.zip)
[ms.zip](https://github.com/ppy/osu/files/2545074/ms.zip)

**Comment by qwewqa** [comment]
Delete `hitcircleoverlay.png` and rename `hitcircleoverlay-0.png` to `hitcircleoverlay.png`.

**Comment by smoogipoo** [comment]
This is a compatibility issue - in most cases the animated version is preferred to the static version, we just don't have animations implemented in skinning yet.
