### ISSUE TITLE
Can not Login to account

### ISSUE THREAD

**Issue by MoriokaMario** [ppy/osu#3676]
Cant login!I have checked my email address and password.Even changed my password and checked if it works.
I can login in the old version of osu!
But
Cant login in the new version.
Hope that Im not the only one with this problem.
And I also hope that I will get a solution soon.

Keep up the good work. 👍

**Comment by daelvn** [comment]
This is happening to me, too, when registering my account. I've tried to redo the process without luck, getting this solved asap would be great.

**Comment by peppy** [comment]
Could you please include your `network.log` file after attempting to log in?

**Comment by MoriokaMario** [comment]
by Network.log 
You mean this...?
[network.log](https://github.com/ppy/osu/files/2553270/network.log)

**Comment by peppy** [comment]
is this still occurring? looks like you were trying to login during we were having issues with an incoming attack.

**Comment by daelvn** [comment]
It's still happening for me, but I couldn't find the `network.log` file under Linux

**Comment by MoriokaMario** [comment]
Its still happening.It wont say if its wrong password or network problem.Its just shows connecting then It will show me to write the password again.

**Comment by daelvn** [comment]
Well I tried six hours after (just now) and it still doesn't login. When should we *not* try to log in?

**Comment by peppy** [comment]
It should work okay now. If possible, could you please provide a new network.log?

**Comment by peppy** [comment]
Ah, this won't currently work. You will need to complete registration using the stable client, sorry.

**Comment by daelvn** [comment]
Yeah, that's going to be an issue since I'm on Linux. Is it possible to get the stable one running on Arch? I haven't managed to do it yet

**Comment by peppy** [comment]
There’s a pretty good guide [here](
https://osu.ppy.sh/community/forums/topics/367783)

**Comment by daelvn** [comment]
I'll try that and see if it compiles for me, thanks!

**Comment by daelvn** [comment]
Well, I've run into the first installation problem by getting this error, and I don't know how to work around it.
```
Executing cd /home/daelvn
------------------------------------------------------
sha256sum mismatch! Rename /home/daelvn/.cache/winetricks/dotnet462/dotNetFx462_Full_x86_x64_Slim.exe and try again.
------------------------------------------------------
```

**Comment by daelvn** [comment]
Well, the `osu` package worked this time, surprisingly, so now I could login in osu-lazer.

**Comment by MoriokaMario** [comment]
This time I got this from network.log

11/9/2018 4:40:30 AM: We just went Connecting!
11/9/2018 4:40:30 AM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Forbidden.
11/9/2018 4:40:30 AM: Processing response from https://osu.ppy.sh/oauth/token failed with Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
11/9/2018 4:40:30 AM: at Newtonsoft.Json.JsonTextReader.ParseValue()
11/9/2018 4:40:30 AM: at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
11/9/2018 4:40:30 AM: at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
11/9/2018 4:40:30 AM: at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
11/9/2018 4:40:30 AM: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
11/9/2018 4:40:30 AM: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
11/9/2018 4:40:30 AM: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse()
11/9/2018 4:40:30 AM: at osu.Framework.IO.Network.WebRequest.Complete(Exception e).
11/9/2018 4:40:30 AM: Login failed!
11/9/2018 4:40:30 AM: We just went Offline!
11/9/2018 4:40:41 AM: We just went Connecting!
11/9/2018 4:40:52 AM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
11/9/2018 4:41:02 AM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
11/9/2018 4:41:02 AM: Processing response from https://osu.ppy.sh/oauth/token failed with System.ArgumentNullException: Value cannot be null.
11/9/2018 4:41:02 AM: Parameter name: value
11/9/2018 4:41:02 AM: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
11/9/2018 4:41:02 AM: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
11/9/2018 4:41:02 AM: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse()
11/9/2018 4:41:02 AM: at osu.Framework.IO.Network.WebRequest.Complete(Exception e).
11/9/2018 4:41:02 AM: Login failed!
11/9/2018 4:41:02 AM: We just went Offline!
11/9/2018 4:41:22 AM: We just went Connecting!
11/9/2018 4:41:22 AM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Forbidden.
11/9/2018 4:41:22 AM: Processing response from https://osu.ppy.sh/oauth/token failed with Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
11/9/2018 4:41:22 AM: at Newtonsoft.Json.JsonTextReader.ParseValue()
11/9/2018 4:41:22 AM: at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
11/9/2018 4:41:22 AM: at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
11/9/2018 4:41:22 AM: at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
11/9/2018 4:41:22 AM: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
11/9/2018 4:41:22 AM: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
11/9/2018 4:41:22 AM: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse()
11/9/2018 4:41:22 AM: at osu.Framework.IO.Network.WebRequest.Complete(Exception e).
11/9/2018 4:41:22 AM: Login failed!
11/9/2018 4:41:22 AM: We just went Offline!

Plus 
I also got this patch fail 
![osu_2018-11-09_10-41-03](https://user-images.githubusercontent.com/44748531/48243870-d2ab9200-e40c-11e8-92fc-f03a26b74c9a.jpg)

**Comment by peppy** [comment]
@MoriokaMario can you actually provide the raw response? You can access `ResponseString` or similar during debug.

**Comment by MoriokaMario** [comment]
How can I provide the raw response?Sorry Im not good with this stuff.

**Comment by KevZhi** [comment]
> Apparently the error is different for me. This is what I get:
> 
> ```
> 11/7/18 8:19:44 PM: ----------------------------------------------------------
> 11/7/18 8:19:44 PM: Network Log for daelvn (LogLevel: Verbose)
> 11/7/18 8:19:44 PM: osu 0.0.0.0
> 11/7/18 8:19:44 PM: Running on Unix 4.18.16.1, 4 cores
> 11/7/18 8:19:44 PM: ----------------------------------------------------------
> 11/7/18 8:19:44 PM: We just went Connecting!
> 11/7/18 8:19:45 PM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Unauthorized.
> 11/7/18 8:19:46 PM: Login failed!
> 11/7/18 8:19:46 PM: We just went Offline!
> ```

looks exact same as mine
https://github.com/ppy/osu/issues/3018

@peppy @daelvn

**Comment by morguldir** [comment]
@KevZhi That was concluded to be because the registration was not complete, has your account been used in the osu!stable client before?

**Comment by KevZhi** [comment]
> > @KevZhi That was concluded to be because the registration was not complete, has your account been used in the osu!stable client before?
> 
> @morguldir Yes, my account was registered in 2013, but since macOS 10.14 comes out, osu stable skin didn't work on it anymore, I'm not able to log on stable.
> Another point, I'm a Chinese user, due to internet censorship, I often use VPN, which sometimes trigger the email auth when login in stable ver before because I'm changing IP, if that was a reason?

@morguldir Awesome, I've tried just now, the 1108.0 ver seems login successfully on my Mac,which the 10xx version can't login.
but I'm curious about in which occasion will this error exist in log. If its only because email auth?
> Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Unauthorized.

**Comment by MoriokaMario** [comment]
@peppy just wanna let you know I can login now after the new release.Thanks 👍

**Comment by peppy** [comment]
Great to hear!
