### ISSUE TITLE
how can I build the game on linux?

### ISSUE THREAD

**Issue by LinuxGamer** [ppy/osu#3682]
Hi, i'm trying to build the game on linux, but all the time that I try to build it, it always compile the game to an exe installer.
is it that is supposed to happen?

**Comment by LovelyA72** [comment]
git clone --recurse-submodules https://github.com/ppy/osu
cd ./osu
dotnet restore
cd ./osu.Desktop
dotnet run

**Comment by peppy** [comment]
There is a file with instructions.
