### ISSUE TITLE
Exception with 'PlaylistItem' key not found

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3692]
**Describe your problem:** Just found this problem when I had almost done eliminating all songs from lazer (trying to fix another issue), I don't know how to replicate it.

**Screenshots or videos showing encountered issue:** Nothing to describe the problem.

**osu!lazer version:** 2018.1108.0.0

**Logs:** [runtime.log](https://github.com/ppy/osu/files/2559459/runtime.log) (don't pay attention to the _katia_ username: long story). The error starts in this line: `07/11/2018 21:47:37: Unhandled exception has been allowed with 0 more allowable exceptions .`
[performance.log](https://github.com/ppy/osu/files/2559486/performance.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2559488/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2559491/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2559492/performance-gamethread.update.log)

**Comment by Gabixel** [comment]
- [x] Added `performance` logs with at least an output in that time frame

**Comment by smoogipoo** [comment]
Fixed via https://github.com/ppy/osu/pull/3746
