### ISSUE TITLE
Editor Toolbox is broken

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3700]
[runtime.log](https://github.com/ppy/osu/files/2566161/runtime.log)

Its not possible to click anything in the toolbox it throws an Error. The Circles / Slider / Spinner also do not appear at all. if you click them fast the game crashes https://streamable.com/d6ums

**Comment by peppy** [comment]
Fixed via #3697? Was already merged when you posted this.

**Comment by Lolihunter1337** [comment]
soooo should i close it? or wait until next patch?
