### ISSUE TITLE
Lazer Social/Multiplayer

### ISSUE THREAD

**Issue by Kardzhilov** [ppy/osu#3703]
Note: Running on Linux

There are 2 bugs or just disabled features that i discovered.

- 1 If i go to the "social browser" and look for users no matter what you search for and if you pick "acceding" or "descending". The users listed are always the same. Also you appear as offline for people running normal OSU no matter the online status you pick.

- 2 When you go to the multiplayer game screen and and pick multiplayer you get sent to the "multiplayer lounge" but its empty and you effectively can not play with anyone.

The networking itself seems to be working since if i go to the chat tab and the chat pops up, the #osu channel is lively but i am not sure if that is just an IRC client or what so i might be wrong.

**Screenshots**
![screenshot from 2018-11-11 19-37-21](https://user-images.githubusercontent.com/15326512/48316867-56ba7100-e5e9-11e8-8298-2caa5a2d40d5.png)
![screenshot from 2018-11-11 19-36-43](https://user-images.githubusercontent.com/15326512/48316865-53bf8080-e5e9-11e8-8c7d-d4a118feb397.png)

**osu!lazer version:** 
1108.0-1
**Logs:** 
[database.log](https://github.com/ppy/osu/files/2569686/database.log)
[debug.log](https://github.com/ppy/osu/files/2569687/debug.log)
[network.log](https://github.com/ppy/osu/files/2569693/network.log)
[performance.log](https://github.com/ppy/osu/files/2569689/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2569690/runtime.log)

**Comment by TPGPL** [comment]
multiplayer lounge isnt finished so it doesn't work for anyone and social browser sorting is just not finished so it's not working

**Comment by sTiKyt** [comment]
:(
