### ISSUE TITLE
Crashing with Intel HD Graphics 3000

### ISSUE THREAD

**Issue by Yolkis** [ppy/osu#372]
![image](https://cloud.githubusercontent.com/assets/17850844/23094452/4c5f2712-f623-11e6-9655-5fa54186fba4.png)
¯\_(ツ)_/¯

**Comment by Poliwrath** [comment]
Did you not read the text in the issue box?

"osu!lazer is currently in early stages of development and is not yet ready for end users. Please avoid creating issues or bugs if you do not personally intend to fix them."

**Comment by TiberiumPY** [comment]
@Yolkis btw it may be not an issue with your graphics card, but rather with your PC configuration ;)
может сможешь всё-таки пофиксить, удачи :)
