### ISSUE TITLE
New chat system doesn't splits words that are too long at the end of the chatbox.

### ISSUE THREAD

**Issue by BeasttrollMC** [ppy/osu#3721]
https://i.imgur.com/1wQ9fEO.png

The word "whatever" in the message sent by TerraioYT was cut off instead of bringing the entire word to the next line. This also happened to "even" in my response to him.

First bug report on github so apologies if this isn't the right place/format for the matter.

**Comment by Joehuu** [comment]
Should be on https://github.com/ppy/osu-web/issues.
