### ISSUE TITLE
Cannot import new songs

### ISSUE THREAD

**Issue by Rasphino** [ppy/osu#3723]
**Describe your problem:** 
platform: archlinux

1. Download songs from https://osu.ppy.sh/beatmapsets
2. Double click the songs
3. Cannot import new songs

ps. I have downloaded a lot of songs and none of them can be imported.

**Screenshots or videos showing encountered issue:** 
![](https://i.loli.net/2018/11/15/5bed07b23812d.jpg)

**osu!lazer version:**
2018.1108

**Logs:** 
[logs.zip](https://github.com/ppy/osu/files/2583779/logs.zip)

**Comment by morguldir** [comment]
The issue is with the arch package for dotnet. https://bugs.archlinux.org/task/60816?project=5&string=dotnet-runtime

This can be closed.

**Comment by TobiichiAmane** [comment]
> The issue is with the arch package for dotnet. https://bugs.archlinux.org/task/60816?project=5&string=dotnet-runtime
> 
> This can be closed.

Confirmed. If I remove all spaces from the filename and the path, it works perfectly.

**Comment by peppy** [comment]
I ask that you do not maintain/distrbute packages without asking first, thanks.

**Comment by TobiichiAmane** [comment]
> I ask that you do not maintain/distrbute packages without asking first, thanks.

Sorry for that. Arch CN repo is basically a service pre-compile and pre-package packages from AUR. 
The package in Arch CN repo will be removed periodly until I get the permission.

**Comment by zsrkmyn** [comment]
@peppy, just out of curiosity and with no offense, why don't you want others to maintain/distribute the package? The MIT License [here](https://github.com/ppy/osu/blob/master/LICENCE) grant

> ... any person ... the rights to use, copy, modify, merge, publish, *distribute*, sublicense, and/or sell copies of the Software ...

If you don't want to do so, why not change it to a proprietary license or make it more clear in the license?

**Comment by peppy** [comment]
The licence is for the *code*, not the osu! trademark. You can not publish this project under the osu! name yourself. You are more than welcome to strip the osu! name completely and then publish it yourself, as per the licence.

Reasoning:
- Going forward we will need some level of control over builds to provide online services (currently we are being lenient but this can not be a permanent thing).
- Implied by last point, but as a result we can not have end users (player) compiling from source. Source compiled builds will not function online.
- Maintaining a level of quality behind the osu! name/brand that I am happy with.

**Comment by peppy** [comment]
Even though it is implicit, you can note the clause under the licence section which I made for people that do not understand how this works:

![image](https://user-images.githubusercontent.com/191335/53708116-43236680-3e75-11e9-85d9-60025b3b19cb.png)
