### ISSUE TITLE
osu!taiko Health point behavior under Hard Rock conflicting with osu-stable and osu!wiki

### ISSUE THREAD

**Issue by jeffswt** [ppy/osu#3730]
**Describe the feature:** 
1. Open any taiko song.
2. Enable *Hard Rock* mod.
3. Play it.
4. When encountering a large note, pressing only one of the two keys will deal significant damage to the health bar. However, this is not the case in osu-stable. In fact, health bar restores (though slower) instead.

This difference brings big problems to taiko players who do *not* finish the large notes with both keys.

**Designs:** 

https://osu.ppy.sh/help/wiki/Game_Modes/osu!taiko

https://github.com/ppy/osu-wiki/blob/master/wiki/Game_Modes/osu!taiko/en.md

> If the note is a LARGE circle, press or hit both of either inner or outer drum depending on the colour of the note for double point (a single correct hit will give single point instead).

> Hit objects judgement
> Small/Large Notes
> 
> GREAT given if drummed inside the judgement circle perfectly with correct colour.
> GOOD given if drummed slightly away from the judgement circle with correct colour.
> MISS/BAD given if drummed too early, too late, missed the judgement circle, or drummed the wrong colour.

> The following will result in health recovery:-
>
> Getting GREAT or GOOD on small/large notes.

Apparently, the behavior in osu!lazer is violating the description on the wiki.

Please clarify if this change is intended or not, and in the case which it is, there should be accessible docs leading to this statement. Thanks!

**Comment by peppy** [comment]
Going to close this issue for now then.
