### ISSUE TITLE
Please re-run this installer as a normal user instead of "Run as Administrator"

### ISSUE THREAD

**Issue by sTiKyt** [ppy/osu#3734]
I'm tried to install it using PlayOnLinux

![image](https://user-images.githubusercontent.com/35602029/48681773-25274400-ebad-11e8-93af-97f18d3d287d.png)

**Comment by peppy** [comment]
Sorry but this is not supported behvaiour. Please compile for linux rather than trying to WINE it.

**Comment by sTiKyt** [comment]
@peppy, I tried to compile for mono, when I was - where no one .exe file like osu.exe or osu!.exe...
