### ISSUE TITLE
Opening Playlist with lots of songs Gets lazer stuck on low FPS

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3747]
**Describe your problem:** If you open the playlist on lazer the FPS gets heavely reduced and stays low until you restart the game. Sometimes it does recover by going into the song selection but not always

**Screenshots or videos showing encountered issue:** https://streamable.com/996a0

**osu!lazer version:** 2018.1120.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/2601294/runtime.log)
[performance.log](https://github.com/ppy/osu/files/2601296/performance.log)
[debug.log](https://github.com/ppy/osu/files/2601297/debug.log)

**Comment by peppy** [comment]
How many beatmaps do you have loaded?

**Comment by Lolihunter1337** [comment]
9.200

**Comment by smoogipoo** [comment]
The reason for this is that the `MusicController` is always present. We can probably do a simple workaround for now but the proper fix is implementing something like an `OptimisedScrollContainer` that limits the number of items visible.

**Comment by RevertedClock** [comment]
would it be possible to have the proper fix soon? its kinda annoying when i wanna open the music player to search quickly for a song and lazer just gets a slideshow :(

**Comment by peppy** [comment]
This issue was already fixed. If you are experiencing an issue please follow the new issue template.
