### ISSUE TITLE
Private messaging shows the wrong "channel type", and it seems to not work properly

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3750]
**Describe your problem:**
I just updated to the latest version and I found several problems. The problem here is that you cannot start a private chat.

**Screenshots or videos showing encountered issue:**
https://streamable.com/oy6i3
(In the video you can see that actually there's a private chat, but because I was the receiver of that message)

**osu!lazer version:** 2018.1120.0.0

**Logs:**
[performance.txt](https://github.com/ppy/osu/files/2605287/performance.txt)
[runtime.txt](https://github.com/ppy/osu/files/2605288/runtime.txt)
(I don't know why GitHub didn't accept `.log` files)

**Comment by peppy** [comment]
This should be fixed in #3749 already.

**Comment by smoogipoo** [comment]
This has been fixed in #3749
