### ISSUE TITLE
crash when trying to delete all songs

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3752]
**Describe your problem:** If i try to delete all songs the game freezes and then crashes

**Screenshots or videos showing encountered issue:** N/A

**osu!lazer version:** 2018.1120.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/2605442/runtime.log)

**Computer Specifications:** Intel Core i3 6100 3.7GHz 2 Cores 4 Threads, GTX 1050Ti, 8GB RAM,Windows 10 Pro x64 1809

**Comment by peppy** [comment]
This is likely already fixed in master (via #3746). Please test against master if you can.

**Comment by Lolihunter1337** [comment]
mhm seem fine on my end

**Comment by smoogipoo** [comment]
👍
