### ISSUE TITLE
DependencyNotRegisteredException on Launch

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3760]
**Describe your problem:**
After launching lazer, it gave me an *unhandled exception* message (see runtime.log attached).
Chat overlay cannot be opened by clicking on the chat button.

**Screenshots or videos showing encountered issue:**

**osu!lazer version:** 2018.1123.0 (also is it normal for the osu site to not have the changelogs yet?)

**Logs:**
[database.log](https://github.com/ppy/osu/files/2609498/database.log)
[debug.log](https://github.com/ppy/osu/files/2609499/debug.log)
[performance.log](https://github.com/ppy/osu/files/2609501/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2609502/runtime.log)

**Comment by plankp** [comment]
Might only happen on first launch, because after reopening osu, the exception does not happen

**Comment by Lolihunter1337** [comment]
got the same issue is that the same problem? 
[runtime.log](https://github.com/ppy/osu/files/2609524/runtime.log)

**Comment by smoogipoo** [comment]
Yup it’s the same issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
