### ISSUE TITLE
Allow importing beatmaps using custom location

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [ppy/osu#3763]
I have osu!stable installed on a folder in my desktop, and on a flashdrive. Lazer doesn't allow me to import from them.

**Comment by peppy** [comment]
That’s a bit weird. There is already code present to locate your stable installation using the registry key, Could you try doing a “repair permissions” from the stable options and see if it helps? You’ll need to restart lazer after doing so.

**Comment by Illuminati-CRAZ** [comment]
When I installed, I didn't allow the program to "make changes to my computer," causing the registry key to not be made(?). Repairing folder permissions and allowing the program to make the changes fixed it. I t would be nice to be able to select the installation from my flashdrive though, without having to repair folder permissions from there.

**Comment by peppy** [comment]
Great to hear that worked. I'd rather keep things simple for now. Once we have a file selector dialog I can imagine it would pop up if lazer is unable to find a stable installation.

**Comment by frank89722** [comment]
@peppy I edited the BeatmapDirectory in osu stable cfg file and it can't import.

**Comment by ReinforceZwei** [comment]
I am not able to import any existed beatmaps or skins on my Mac because I am not able to install osu! on my Mac. I have about 30GB beatmaps and I want to play these maps using my Mac without re-downloading all beatmaps into osu!Lazer. Please add this function >.< Thank you

**Comment by peppy** [comment]
Please place your beatmaps at `~/.osu/Songs`

**Comment by Game4all** [comment]
I currently have a working branch for this (altough still a bit messy, so needs refactoring before PR-ing) and I'm wondering when the directory selector for locating manually a stable installation should open. Should it open after clicking yes on the initial import prompt when opening the select screen with no beatmaps or should it be available in the settings as a button, maybe both?

**Comment by frenzibyte** [comment]
Should probably appear once when the user doesn't have a manual stable path set (as a some form of "we can't locate your stable installation, please direct us to it"), and then save that path to osu config to remember it in future lookups.

**Comment by bdach** [comment]
> save that path to osu config to remember it in future stable import processes.

disagree with that part.

**Comment by peppy** [comment]
It should lookup the config. Not provide a directory selector.

**Comment by AstroOrbis** [comment]
On MacOS, it seems to be `~/.local/share/osu`. That's the only osu!lazer directory I could find...

**Comment by frenzibyte** [comment]
> On MacOS, it seems to be `~/.local/share/osu`. That's the only osu!lazer directory I could find...

what's this comment about / to who is this replying to? are you talking about how to import form a stable directory? symlink the stable directory to `~/.osu` so osu!lazer can import from it

**Comment by AstroOrbis** [comment]
> > On MacOS, it seems to be `~/.local/share/osu`. That's the only osu!lazer directory I could find...
> 
> what's this comment about / to what is it replying to? are you talking about how to import form a stable directory? symlink the stable directory to `~/.osu` so osu!lazer can import from it

There is no `~/.osu` directory, only a alias to a non existing folder... for integrity's sake I migrated my `~/.local/share/osu` to inside my osu!lazer .app file, do I move it to a new folder called ~/.osu? I'm confused...

**Comment by bdach** [comment]
@AstroOrbis what are you trying to achieve *exactly*?

**Comment by AstroOrbis** [comment]
> @AstroOrbis what are you trying to achieve _exactly_?

I'm trying to do 2 things:

1. Sync osu!stable and osu!lazer files
2. When a osu! file is downloaded (osz, osr, etc.) I want it to be moved to my stable or lazer directory (won't matter which one because they would be synced).

I am on MacOS Big Sur, Latest update, latest osu!stable beta and osu!lazer update. Stable is osu!.app and Lazer is osu!lazer.app.

**Comment by bdach** [comment]
this is (a) not currently possible automatically because stable and lazer storage structures are incompatible, (b) not the topic of this issue thread. if you want to sync, then symlinking stable song storage to `~/.osu` as mentioned above, and periodic full reimports are the best that can be done.

locking as off-topic. feel free to reopen your wishes as a separate issue but i wouldn't hold my breath that this will happen as it's a low-priority item that is difficult to get right and we don't have the bandwidth to do that instead of actually bringing lazer up to par with stable.

**Comment by bdach** [comment]
This is partially supported via https://github.com/ppy/osu/pull/11603 now. I think that about the only thing that anyone could ever want added to that is being able to manually select a folder if stable isn't located (due to denied permissions), I suppose.
