### ISSUE TITLE
osu!lazer win7 x64 not work (from 2018.801.0 - latest)

### ISSUE THREAD

**Issue by Trigger-b0y** [ppy/osu#3769]
**Describe your problem:** osu!lazer win7 x64 not work

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** ***UPD:*** from the version 2018.801.0 to latest released 2018.1123.1 not runing but installed
Latest working version 2018.730.0

**Logs:** No logs in %appdata%\osu\logs.
osu!lazer quickly close, so i press enter on osu!.exe and make screenshot
 ![2018-11-25_19-00-54](https://user-images.githubusercontent.com/23249869/48981293-7622c500-f0e4-11e8-8a7f-b141fe47b2e2.png)

------------------------------

## This log from "Windows Logs" -> "Application":

Контейнер ошибки , тип 0
Имя события: PCA2
Ответ: Нет данных
Идентификатор CAB: 0

Сигнатура проблемы:
P1: osu!.exe
P2: 0.0.0.0
P3: osu!.exe
P4: unknown
P5: unknown
P6: 200
P7: -1
P8: 
P9: 
P10: 

Вложенные файлы:
C:\Users\user\AppData\Local\Temp\{68c98976-9947-4501-81e7-fdd0712514fb}\appcompat.txt
C:\Users\user\AppData\Local\Temp\Tab9964.tmp

Эти файлы можно найти здесь:

Символ анализа: 
Повторный поиск решения: 0
Идентификатор отчета: 4bf862d8-f0c8-11e8-b9eb-0025223fcc67
Состояние отчета: 0

------------------------------

**Computer Specifications:** Windows 7 Ultimate 64-bit SP1
Installed runtimes:
VC++ redist 2005-2017 (x32-x64)
XNA Framework v2.0-v4.0
.NET Framework v4.7.2

**Comment by LastExceed** [comment]
just to make sure i understood this correctly: you managed to install it but when you try to start the game nothing happens because the process immediately closes itself. is that correct?

**Comment by Trigger-b0y** [comment]
Exactly

**Comment by peppy** [comment]
It looks like there are two instances running in your task manager. One is 32-bit. Do you happen to have an instance of `osu-stable` open or something?

**Comment by peppy** [comment]
That error log doesn't seem to have anything useful. Are there any other logs in event viewer?

**Comment by smoogipoo** [comment]
Event viewer should show two errors, each from a different source.

We need the one that lists `.NET Runtime` as the source.

**Comment by Trigger-b0y** [comment]
> Event viewer should show two errors, each from a different source.
> 
> We need the one that lists `.NET Runtime` as the source.

I know but no logs when i trying run osu!lazer

**Comment by Trigger-b0y** [comment]
@smoogipoo 
![image](https://user-images.githubusercontent.com/23249869/51454526-3419a680-1d56-11e9-81ea-497f35c13581.png)

~~https://puu.sh/CzWAN/b399e1deb0.mp4~~

UPD: watch this https://puu.sh/CzWMx/987e49367e.mp4

**Comment by smoogipoo** [comment]
Thanks! It seems like this is mentioned in the prerequisites listed in https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x , which was new to us. We'll add it to the readme.
