### ISSUE TITLE
Message 'import failed' when import new maps

### ISSUE THREAD

**Issue by zzhenryquezz** [ppy/osu#3771]
When I download new maps for osu!lazer i have this message some times.
If i look for the maps in game they are there, but can't say if some one was lost, because i import a lot of they so i don't know if some map are lost or not.

The way that i import the maps is clicking in they in the folder.

My PC:
OS: Linux Manjaro Kde
Intel G4560
GTX 1060
Ram 8 gb 
Hd 1 Tera

Prints:
![screenshot_20181127_024406](https://user-images.githubusercontent.com/43827016/49059250-17963d80-f1ef-11e8-93d9-c2cc2f450d4a.png)

Osu!lazer version: osu-lazer-git  2018.1123.1_15_g83b040fdd-1 from AUR

Logs: 
[database.log](https://github.com/ppy/osu/files/2618380/database.log)
[debug.log](https://github.com/ppy/osu/files/2618381/debug.log)
[performance.log](https://github.com/ppy/osu/files/2618383/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2618384/runtime.log)

**Comment by morguldir** [comment]
Looks like you are trying to import beatmaps that you already imported, which doesn't work because they get consumed when you import them.

**Comment by zzhenryquezz** [comment]
Maybe could be for someone, but i import something like 20 beatmaps and this message appears like 10 times in the importation. 
But i will make some tests here to check this and i return late.

**Comment by zzhenryquezz** [comment]
I try made more imports in the game with maps that i have sure that i don't have in the game, and the message don't came again so i think that it was just a mistake my, sorry.

**Comment by smoogipoo** [comment]
It’s possible this may have been some modification you had locally. Please re-open if you encounter the same again.
