### ISSUE TITLE
More in-game search queries

### ISSUE THREAD

**Issue by Epicm14** [ppy/osu#3781]
For a while now I've felt the need for more ways of sorting/listing beatmaps:

1.  Number of Objects ex. (objects>500) (o>500)
        -I feel like this would be efficient for picking out more dense maps, finding streamy maps to 
          practice. 
        -Also for finding maps that give the most score, for faster level ups.
2. Score achieved 
        -Especially for mania, this would be efficient for finding maps you can improve more on.
        -For someone who likes to go for million scores, they can easily see how many they have, how many they almost have.

3. Date Ranked
      -To separate older maps from newer maps.
      

Thanks

**Comment by Hubza** [comment]
i'd love this, i've always wanted to search for songs with the most hitcircles.
