### ISSUE TITLE
Seeking in CTB's autoplay makes crashes

### ISSUE THREAD

**Issue by lolita-is-godddd** [ppy/osu#3782]
**Describe your problem:** When seek in autoplaying too diffcult map (e.g. <https://osu.ppy.sh/beatmapsets/406881#fruits/884085>)

**Screenshots or videos showing encountered issue:** no (tried record, but couldn't)

**osu!lazer version:** 2018.1123.1

**Logs:**
[performance.log](https://github.com/ppy/osu/files/2628793/performance.log)
[debug.log](https://github.com/ppy/osu/files/2628794/debug.log)
[runtime.log](https://github.com/ppy/osu/files/2628795/runtime.log)
[database.log](https://github.com/ppy/osu/files/2628797/database.log)
(\* missed network.log by Github denied with "We don't support that file type")

**Computer Specifications:** Windows 7, Pro

**Comment by smoogipoo** [comment]
The logs you provided don't list any error, can you re-replicate and post another set of logs?

**Comment by peppy** [comment]
This should no longer be an issue (cannot repro).
