### ISSUE TITLE
Chat TabsArea transparent when ChannelSelectionOverlay is visible

### ISSUE THREAD

**Issue by jorolf** [ppy/osu#3793]
You can currently see through the chat header but not throught elements around it:
![image](https://user-images.githubusercontent.com/12570757/49291188-b3eb6900-f4a9-11e8-9429-5e2498e6976b.png)

I would extend the channel selection down so it covers the chat header, too.

*I don't remember flyte's designs but the current behavior could've been intented* 🤔

**Comment by smoogipoo** [comment]
@arflyte thoughts on this? / intended?

**Comment by arflyte** [comment]
it's not intended to be that way; clearly an oversight. will think of a way to fix that weirdness.

**Comment by peppy** [comment]
Take into consideration that if anything we need to *reduce* transparency here, not increase it.

**Comment by arflyte** [comment]
yeah, I'm reducing the amount of transparency for both client and web.

**Comment by Joehuu** [comment]
Closing in favor of https://github.com/ppy/osu/issues/17001.
