### ISSUE TITLE
osu!lazer support

### ISSUE THREAD

**Issue by tRbaXn** [ppy/osu#3795]
Yeah I know that osu!lazer is already available on mac but would it be possible to get it to run on El Capitan?

Much love,
                 Very Tall Person.

**Comment by LovelyA72** [comment]
lazer builds on dotnet core 2.1 which does not support osx 10.11 or lower. I am not sure if you can use wine or not... Have you tried it yet?

**Comment by peppy** [comment]
For now this is completely out of scope of this project sorry. We are focused on platforms which can run netcore2.1+.
