### ISSUE TITLE
Beatmap Tags/Description section are in the wrong place 

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3798]
**Describe your problem:** Sometimes after you quit a map and then go to the Beatmap Details the Tags/Description section bugs into the rest of the details

**Screenshots or videos showing encountered issue:** 
![osu_2018-12-01_21-17-34](https://user-images.githubusercontent.com/17437302/49332543-18dcb700-f5af-11e8-8591-cba7adf17fab.jpg)

**osu!lazer version:** Latest Master 

**Logs:** N/A

**Comment by peppy** [comment]
If possible could you please provide a video of this happening? I can't seem to reproduce it.

**Comment by UselessToucan** [comment]
> osu!lazer version: Latest Master

Can you specify the concrete git commit?

**Comment by Lolihunter1337** [comment]
I think its resolved now anyways i havent been able to reproduce it. Will re-open if it happens again

**Comment by Lolihunter1337** [comment]
so it happend again. but i have *no* idea how to reproduce it as it happens really random. im on the commit  312efbd and were just playing a couple of maps. https://streamable.com/4e8qn

**Comment by Joehuu** [comment]
To reproduce:
- go to `Details` if not already
- go to any leaderboard
- resize window
- go back to `Details`

**Comment by peppy** [comment]
looks like it may be a fill flow invalidation issue

**Comment by Joehuu** [comment]
Will be fixed in https://github.com/ppy/osu-framework/pull/3307.
