### ISSUE TITLE
It's hard to pm the user that send the newest chat.

### ISSUE THREAD

**Issue by LovelyA72** [ppy/osu#3799]
As shown in the picture, the right click menu is blocked by the text box.

The version is a git pull of the master branch yesterday(Dec 1, 2018, 15:00 GMT+8).

And here is the image:
![image](https://user-images.githubusercontent.com/29054052/49335024-7dcff580-f61f-11e8-8f22-c60996730900.png)

**Comment by Joehuu** [comment]
This still happens when you right click a user on the bottom of the bounding container, midway of the scroll container.

![](https://puu.sh/E4Wh2/b29a0e5bcd.png)

**Comment by peppy** [comment]
Thanks for bringing this up. It requires a smaller local fix in addition to the framework one.
