### ISSUE TITLE
ChannelSelectionOverlay doesn't focus when there are no chats

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3802]
**Describe your problem:** The game no longer focus the `ChannelSelectionOverlay` when the user closes the last chat (or private chat).

**Screenshots or videos showing encountered issue:** 
https://streamable.com/fir1i

**osu!lazer version:** 2018.1201.0.0

**Logs:** [runtime.log](https://github.com/ppy/osu/files/2637062/runtime.log)

**Comment by smoogipoo** [comment]
I don't see an issue here? It is "focused" but you're unable to type. In-fact I believe the textbox remaining focused is the real issue.

**Comment by Gabixel** [comment]
Well... that's another issue for sure, but the problem that I mentioned is that the game should trigger the "Chat Channels" section when the user closes his last joined chat (or private chat, as seen in the video), or was this option intentionally removed?

![chat channels](https://user-images.githubusercontent.com/43073074/49378099-180d6780-f70c-11e8-9851-334d840442de.png)
