### ISSUE TITLE
Graphical glitches on linux

### ISSUE THREAD

**Issue by nbvdkamp** [ppy/osu#3803]
**Describe your problem:**
Lazer has strange graphical glitches where some UI elements flash at seemingly random intervals and some elements become invisible when you hover over them.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/4kmgv

**osu!lazer version:** 
Built from latest master
(commit 8f1d53400e882349d679b5df5cb0645827b753c9)

**Logs:**
[database.log](https://github.com/ppy/osu/files/2637544/database.log)
[debug.log](https://github.com/ppy/osu/files/2637545/debug.log)
[performance.log](https://github.com/ppy/osu/files/2637547/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2637548/runtime.log)

**Specs**
CPU: i5 4670K
RAM: 16GB DDR3
GPU: RX Vega 56

Edit: I'm running Ubuntu 18.10

**Comment by nbvdkamp** [comment]
I had to return the Vega 56 and now I'm back to my GTX 770 and the problem is completely gone so it seems the problem is that the framework doesn't work properly with the linux AMD drivers.

**Comment by LazyLea** [comment]
Same issue here on Vega 64, mesa-18.3.3.

Friend with RX580 has no issues, so this might be a Vega problem.

**Comment by Ferdi265** [comment]
Which AMD drivers were you (@nbvdkamp) or is your friend (@LeaPhant) using? Open-Source drivers or the proprietary ones? The driver quality between those two varies quite a lot and it might be an issue with that.

**Comment by LeaPhant** [comment]
@Ferdi265 We are both using mesa, I also have another friend on an RX 480 + mesa without problems.

**Comment by LeaPhant** [comment]
This issue is fixed for me with Mesa 19.0.4 on my Vega 64. I've tried an older version of lazer and there were no graphical glitches either. It seems like this has been resolved on the driver side, at least for my GPU.

**Comment by sciuridae0603** [comment]
** Spec **
Windows 10
RX 580 ( Driver Version : 19.7.5 )

**osu!lazer version:** 
2019.813.0

Maybe I found similar problem at Setting -> Input -> Key configuration (?

![image](https://user-images.githubusercontent.com/13612494/62949898-a1d40f80-be19-11e9-83fc-f4dce9a325dc.png)
![image](https://user-images.githubusercontent.com/13612494/62949677-368a3d80-be19-11e9-9489-8f17871c8f8c.png)
![image](https://user-images.githubusercontent.com/13612494/62949689-3d18b500-be19-11e9-8a7d-5abc4cdc49ca.png)

**Comment by jai-x** [comment]
Does enabling "Bypass front-to-back render pass" in the settings make any difference?

**Comment by peppy** [comment]
I believe the one just reported is a slightly different issue to the original posted. I can also reproduce this on my main dev PC for what it's work. Cause unknown, but probably shader-level.

**Comment by Jordan-Jay** [comment]
I would suggest looking back into this issue. Seems driver related. Mesa has come a long way since early 2020 and very likely is fixed at this point but if it's still not functional. Proprietary AMD drivers are recommended as the quality of the Driver is better until a shader level fix is done.

**Comment by smoogipoo** [comment]
Let's close this issue due to inactivity.
