### ISSUE TITLE
Shouldn't be able to Ctrl+Tab into channel selection dialog

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#3804]
1. Select the last tab in the chat overlay.
2. Press Ctrl+Tab.
3. Channel selection dialog will open.
4. Press Ctrl+Tab.
5. Last tab will be re-selected.

Instead, Ctrl+Tab should cycle through the non-channel selection tabs.

**Comment by swoolcock** [comment]
Pretty sure it's a regression from #2371 

Need to add `public override bool IsSwitchable => false;` to `ChannelSelectorTabItem` as it wasn't brought across in the refactor.
