### ISSUE TITLE
ObjectDisposedException when clicking on chat overlay button

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3805]
**Describe your problem:** 
Does not happen all the time, but both times the game instantly closes immediately after clicking on the chat overlay button.

**Screenshots or videos showing encountered issue:**
(Could not take screenshot)

**osu!lazer version:**
2018.1201.0.0

**Logs:** (runtime.log is the one with the exceptions)
[database.log](https://github.com/ppy/osu/files/2637755/database.log)
[debug.log](https://github.com/ppy/osu/files/2637756/debug.log)
[network.log](https://github.com/ppy/osu/files/2637757/network.log)
[performance.log](https://github.com/ppy/osu/files/2637758/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2637759/runtime.log)

**Computer Specifications:**
MacOS High Sierra 10.13.6 MacBook Pro 13-inch 2017

**Comment by peppy** [comment]
Fixed via #3810
