### ISSUE TITLE
ModSelectOverlay causes the Home button to work incorrectly

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3812]
**Describe your problem:** The issue basically happens when the `ModSelectOverlay` is open: the `Home` button doesn't send you to the `MainMenu`, but it just closes the `ModSelectOverlay`.

**Comment by Gabixel** [comment]
Seems like this issue happens again

**Comment by Joehuu** [comment]
Regressed in #5149.

**Comment by peppy** [comment]
This regression was intentional for now.

**Comment by Joehuu** [comment]
Can reopen.

**Comment by Gabixel** [comment]
Seems like this issue also happens when pressing the `X` button on Windows with the new `2019.919.0` version

**Comment by Joehuu** [comment]
When the mod select is open, should clicking back button close it (current implementation) or exit to main menu?

![](https://puu.sh/EmZxe/34b913ddb9.png)

We have this close button and the escape key already.

**Comment by smoogipoo** [comment]
I think we intended the back button to close mod select.

**Comment by peppy** [comment]
Yep, for now this is intended.

**Comment by Joehuu** [comment]
I'm trying to fix this, and wondering if there's something to check if a drawable (in this case a button) is clicked.

I'm planning to make `BackButton` public in `OsuGame`, DI `OsuGame` to `SongSelect`, and add a clicked check to the current logic inside `OnExiting`.

**Comment by peppy** [comment]
A better way is likely going to be adding a new interface `ICustomBackButtonAction : IOsuScreen { Func<bool> OnBackButton() }`, then adding code in the `BackButton.Action` delegate in `OsuGame` to check whether the current screen implements this new interface, then give it a chance to handle and block (don't call `ScreenStack.Exit()`) if it returns `true`.

**Comment by peppy** [comment]
In fact, you can probably get away with just adding it to `IOsuScreen` / `OsuScreen` as `protected virtual bool OnBackButton() => false;`
