### ISSUE TITLE
osu!lazer won't detect a new account creation process

### ISSUE THREAD

**Issue by rustyJS** [ppy/osu#3814]
**Problem:** osu!lazer is unable to detect when a new account is trying to be made with this version, like the account I'm trying to register as. Is this feature broken, in development, or am I suggested to use regular osu? (in this case, it won't install at all on the current installer. Haven't tried the Legacy installer yet, though).

The sign-in button doesn't do anything either. 👌

**Screenshots or videos showing encountered issue:** 
![image_49](https://user-images.githubusercontent.com/40505269/49410641-32f9cf00-f740-11e8-9169-d3ae186e6d2b.png)

**osu!lazer version:** 2018.1203.0 (development build) 

**Logs:** 
[debug.log](https://github.com/ppy/osu/files/2641841/debug.log)
[network.log](https://github.com/ppy/osu/files/2641837/network.log)
[performance.log](https://github.com/ppy/osu/files/2641838/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2641839/runtime.log)
[database.log](https://github.com/ppy/osu/files/2641840/database.log)

---

In all seriousness, osu!lazer is amazing. Features I always wanted (in-game beatmap downloading, killer intro theme, better performance on lower-end devices, UI improvements, and overall great) got added, and it's stunning to see how far this went. I'd love to help out if possible in the art category, UI mainly, maybe redesign the logo a little bit too.

osu!lazer pretty much ties out NITG. Both are equally great! Can't wait to see these changes happen in the main osu! releases.

**Comment by peppy** [comment]
The account registration behavior is intended. New account registration support will be added to lazer very soon but for the time being you will unfortunately have to use stable.

**Comment by rustyJS** [comment]
That was **fast**, wow.

Anyways thanks for the response, will respond back if stable's legacy installer works or not, and if signing in works after the account is created.

While we're here, you have any official discord for osu? Would like to be more involved with this game, maybe even work on it too if any spots are available (art-wise, mainly with UI and GUIs).

**Comment by peppy** [comment]
our dev-focused discord is at https://discord.gg/ppy.
