### ISSUE TITLE
Easy way to build the game for tests purpose

### ISSUE THREAD

**Issue by darkyne** [ppy/osu#3818]
Hi,

I am willing to contribute (at my little level) so I'm trying, at first, to build the game pulled from the master branch (should go fine).

But, in my opinion, this very little task is already not that simple or maybe it could be usefull to add few little more information in the readme.

In my case, all the automatic tests are running fine under visual studio but when I try to "generate osu.game" I can't find any executable file generated to launch the game.
On the other side, if I try to run "dotnet run --project osu.Desktop" it stays blocked on "Loading shader Texture2D/Texture" for hours. 

So I guess I am doing something wrong or something could be more clear in the instruction from the readme. 

I guess the readme is already clear for every one who is used to the project or to visual Studio but not really for every beginner.

**Comment by peppy** [comment]
This project is not intended to be a tutorial for how to become a developer. 

If you are looking for help to solve your issue, please provide logs, video, console output - anything that may help us help you diagnose the issue.

**Comment by darkyne** [comment]
I understand that Osu is not a tutorial for future developers and in my case, indeed, I am really a beginner especially with C# and dotnet. 

But what I was suggesting was really not a big change juste (for example)  a clarification that actually with Visual Studio no .exe is generated but we should launch dll via dotnet instead (if I understood correctly).

Anyway, it was just a suggestion I had while noticing I was not the only one having some issues building correctly the game ([#3375](https://github.com/ppy/osu/issues/3375)) .

For my specific case, I ended up figuring out it was a problem with my dotnet configuration, now I can run it correctly.

PS: I'm not thinking of Osu as a tutorial for beginners... I just thought if it's easier to build even for beginners, you may have (with time) more people working on it, finding bugs quickly and even helping with bugs (since beginners don't stay beginner all their life :D).

**Comment by darkyne** [comment]
This is just a little suggestion, go as you want :)

**Comment by peppy** [comment]
What was the problem with your dotnet configuration out of curiosity?

**Comment by darkyne** [comment]
Actually I'm not sure what it was but I realised it was working on linux (ubuntu 16.04) but not on my windows... I totally removed and reinstalled dotnet and it worked... So... Magic :D
