### ISSUE TITLE
Game does not try to reconnect to internet

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3835]
**Describe your problem:**
Followup to launching without internet (#3572), the game now does not crash, but after reenabling internet connection, it does not try to reconnect.

**Screenshots or videos showing encountered issue:**
The user profile badge will keep showing connecting... while in the network log nothing new happens.

**osu!lazer version:**
2018.1207.0

**Logs:** (network.log will complain about not being able to connect due to launching without internet. Game will not crash, but there will be no more *Performing requests* afterwards)

**Comment by peppy** [comment]
Got a network log for this one?

**Comment by plankp** [comment]
https://cdn.discordapp.com/attachments/188630652340404224/520652281520324618/network.log

**Comment by peppy** [comment]
This may be resolved in the latest master/release via #3838. Could you please re-test (`2018.1214.0`)?

**Comment by plankp** [comment]
Still happens

[network.log](https://github.com/ppy/osu/files/2683929/network.log)
