### ISSUE TITLE
Problem with Raw input and Tablet

### ISSUE THREAD

**Issue by quangaming2929** [ppy/osu#3842]
When I using XP-Pen G640 and Raw input, I can't move the cursor to the corner

In-game Screenshot:
![image](https://user-images.githubusercontent.com/33594017/49698572-2f5ec000-fbf8-11e8-951c-ea451961a297.png)
Update, All four corner have the same issue, not just the bottom-right corner

My Tablet Setting:
![image](https://user-images.githubusercontent.com/33594017/49698587-806eb400-fbf8-11e8-8653-8799aa514c45.png)

Version: osu!lazer 2018.12070.0

**Comment by peppy** [comment]
Does adjusting the sensitivity in-game help at all?

**Comment by Joehuu** [comment]
Closing for now, I have the same tablet and didn't witness this issue. Updates from the driver and possibly SDL maybe already fixed this.
