### ISSUE TITLE
Spinner can't play when object exchange time and endtime 

### ISSUE THREAD

**Issue by Mahua233** [ppy/osu#3844]
I don't know it's stable version bug or lazer version bug. But it can autoplay in stable version.

>https://osu.ppy.sh/beatmapsets/99602#osu/264825
https://osu.ppy.sh/beatmapsets/665530#osu/1408449

In Blue Light: 03:13:644 - End. This map can SS when play on stable ver. And I can't get result.
In GHOST: 05:35:211 - End.

**Comment by Joehuu** [comment]
Autoplay not SSing the first map is fixed in https://github.com/ppy/osu/pull/9779. Not sure what fixed the results screen not being pushed as there have been multiple fixes to that without having to spend time bisecting.
