### ISSUE TITLE
Possible future bug with opening skin during gameplay

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#3845]
Right now on stable osu! can't handle importing a new skin while playing beatmap. In most cases it will crash. I don't know is it a known bug, but I'm writing it here just to prevent this happening in lazer.

The simplest way to reproduce this bug is just downloading some skin on chrome, then clicking open after download and opening beatmap.

Also, I can't try it in lazer because osz file is directly linked to the stable.

**Comment by peppy** [comment]
You can drag files into the lazer window to test. Please only report issues after you confirm they actually exist.
