### ISSUE TITLE
Some titles/diff names can cause bancho to display them incorrectly

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu#3846]
![screen shot 2018-11-20 at 9 58 58 am](https://user-images.githubusercontent.com/30382015/49740317-e3cb1580-fcce-11e8-98e0-1c2de36dbc8c.png)

https://osu.ppy.sh/s/860963

probably due to the </ in the diff name

**Comment by peppy** [comment]
Which channel are you in to see this?

**Comment by Xinnoh** [comment]
this was in #announce, I think the error might be due to bancho's code telling it to send something else, rather than a client issue

**Comment by peppy** [comment]
I've been stalking announce for a similar occurrence but have not found one yet. Please let me know if you see it come up again (or if you can trigger it).

**Comment by Xinnoh** [comment]
I would be able to trigger an announce by reviving something from the graveyard with </ in the artist or title, will see what happens next month.

**Comment by peppy** [comment]
Closed with `osu-web-10` fix. Was affecting both osu-stable and lazer, as this was a database-level issue.
