### ISSUE TITLE
Cursor sometimes gets missing while playing

### ISSUE THREAD

**Issue by RikkYT** [ppy/osu#3856]
When I was playing a beatmap, the cursor is so small its unable to see it.
It's hard to see the cursor in the red tiles.

__Edit__ (As UselessToucan said, I will provide steps on how the devs can fix this problem)

- Make the cursor bigger and make it look better so that it does not blend in with any of the colours
- Make the tiles a bit  bigger so that it matches with the cursor  and try to brighten up the colours of the tiles.
That's all I could think of, if anyone of you could think of an idea please post it! It will be helpful!

**Comment by UselessToucan** [comment]
@RikkYT Can you reproduce this again? If yes, please provide steps to reproduce the problem.

**Comment by EVAST9919** [comment]
Incorrect user-profile label

**Comment by peppy** [comment]
This was probably before cursor scaling was added. I'm not sure it needs to remain open.
