### ISSUE TITLE
Per-ruleset shortcut buttons for key configuration window

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3859]
**Describe the feature:** The idea is basically to add few shortcut buttons on the `key configuration` section for the various game modes (and global option), allowing the player to find keys faster because I noticed that it can be dispersive sometimes (especially with osu!mania keys)

**Proposal designs of the feature:** 

Here's an example (made with Photoshop):
![shortcuts for various keys configuration](https://user-images.githubusercontent.com/43073074/50017594-d6fb3a00-ffcc-11e8-8ee3-a88488efe1cb.png)

**Comment by peppy** [comment]
Yep, this is definitely something we planned on having.
