### ISSUE TITLE
Upon update, hitting restart causes lazer to close and remove itself from computer.

### ISSUE THREAD

**Issue by Novitt** [ppy/osu#3868]
I tried to update to the latest version of the development build, and it gave me a 'delta patching failed' error.  After it finishes installing the update it gives me the message to restart.  After clicking lazer closes, does not restart, and removes itself from my computer.  I have to run the install for the previous version to run it again.

![ss 2018-12-17 at 12 05 26](https://user-images.githubusercontent.com/45946952/50103644-148edb80-01f6-11e9-9810-1520657d64fd.jpg)

**2018.910.0:**

[runtime.log](https://github.com/ppy/osu/files/2687124/runtime.log)

**Comment by Novitt** [comment]
Accidentally closed, issue may be version of lazer I had before trying to update.  Didn't realise how behind I was.

**Comment by peppy** [comment]
This can be fixed by running the latest `install.exe`. Has 100% been fixed.
