### ISSUE TITLE
Ability to mute notifications while importing beatmaps.

### ISSUE THREAD

**Issue by CordEmpire** [ppy/osu#3877]
**Describe the feature:** It is really annoying when importing beatmaps that every time a beatmap is added it stops whatever i am doing to tell me that something has been imported.

**Proposal designs of the feature:** Don't have notifications for new beatmap, or at least have them non-obtrusive and silent

**Comment by peppy** [comment]
Hmm, this shouldn’t be a thing. Importing should create a single progress notification and only alert when it has finished.

Are you sure you are in the latest build?

**Comment by HoutarouOreki** [comment]
Only the "import from stable" feature works like that.

Importing by hand creates many tasks that pop up a notification on every map imported: https://streamable.com/8zqeh

**Comment by peppy** [comment]
That's a definite bug if that's the case. I'll take a look into it.

**Comment by CordEmpire** [comment]
> Hmm, this shouldn’t be a thing. Importing should create a single progress notification and only alert when it has finished.
> 
> Are you sure you are in the latest build?

Yes, when reported this was the latest version.
