### ISSUE TITLE
Game freezes when searching and importing/checking maps at the same time

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3878]
**Describe your problem:** I was trying to search a map meanwhile the game was checking for new maps, and suddenly a bunch of errors appeared and the game started to lag and freeze during this process.

How to replicate:
1. Let the game checks for new maps;
2. Use the search function

**Screenshots or videos showing encountered issue:** https://streamable.com/eg5x9

**osu!lazer version:** 2018.1214.0.0

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/2692509/performance.log)
[network.log](https://github.com/ppy/osu/files/2692510/network.log)
[debug.log](https://github.com/ppy/osu/files/2692512/debug.log)
[database.log](https://github.com/ppy/osu/files/2692513/database.log)
[runtime.log](https://github.com/ppy/osu/files/2692514/runtime.log) (very strange repetitive "working beatmap" update)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2692516/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2692518/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2692519/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2692520/performance-gamethread.update.log)

**Comment by peppy** [comment]
Closing as stale.
