### ISSUE TITLE
Hard rock great meh not in position

### ISSUE THREAD

**Issue by hafizdkren** [ppy/osu#3883]
this is what happen when play on hr

![screenshot 44](https://user-images.githubusercontent.com/10624578/50210675-5d3ac600-03a9-11e9-8108-29a14a07318b.png)
![screenshot 45](https://user-images.githubusercontent.com/10624578/50210676-5dd35c80-03a9-11e9-98c9-36d6b65e3fe5.png)
![screenshot 46](https://user-images.githubusercontent.com/10624578/50210677-5dd35c80-03a9-11e9-9e71-b027be7b6e5a.png)
![screenshot 47](https://user-images.githubusercontent.com/10624578/50210678-5e6bf300-03a9-11e9-8e8a-002d345e0a63.png)
![screenshot 48](https://user-images.githubusercontent.com/10624578/50210679-5e6bf300-03a9-11e9-8ca9-89a75020998f.png)
![screenshot 49](https://user-images.githubusercontent.com/10624578/50210680-5e6bf300-03a9-11e9-9ac5-9fd2d003dcdc.png)
![screenshot 50](https://user-images.githubusercontent.com/10624578/50210682-5f048980-03a9-11e9-9836-8a0b2871d739.png)
![screenshot 51](https://user-images.githubusercontent.com/10624578/50210683-5f048980-03a9-11e9-8c51-b80d7d5f209a.png)
![screenshot 52](https://user-images.githubusercontent.com/10624578/50210684-5f048980-03a9-11e9-8c63-52f199baf67a.png)
![screenshot 53](https://user-images.githubusercontent.com/10624578/50210685-5f9d2000-03a9-11e9-8e09-db176d8bb14b.png)
![screenshot 54](https://user-images.githubusercontent.com/10624578/50210688-5f9d2000-03a9-11e9-9661-4a71c70a5c20.png)
![screenshot 55](https://user-images.githubusercontent.com/10624578/50210690-6035b680-03a9-11e9-919a-430d55e7f733.png)
![screenshot 56](https://user-images.githubusercontent.com/10624578/50210691-6035b680-03a9-11e9-8c3e-20b2f3585a6a.png)
![screenshot 57](https://user-images.githubusercontent.com/10624578/50210692-60ce4d00-03a9-11e9-981f-038e30b3d659.png)

**Comment by Gabixel** [comment]
You should not close the issue if it isn't resolved, you should keep it open. Anyway, I tried to reproduce it and seems that some random "hit words" appear when playing with Hardrock (I tried with all other mods and I can confirm it). Here's a video where this happens: https://streamable.com/ibsxb

**Comment by hafizdkren** [comment]
Sorry for closing the issue. I think it is just my eye or something happen on my screen. Nope that's real
