### ISSUE TITLE
@ character does not display in textboxes until a different character is pressed

### ISSUE THREAD

**Issue by carlobolla** [ppy/osu#3884]
**Describe your problem:** Typing the character '@' in any textbox won't make it appear, until another character is typed. It is unknown to me whether the same issue happens with other characters

**Screenshots or videos showing encountered issue:** https://youtu.be/hE1o-iJzGow

**osu!lazer version:** 2018.1214.0

**Logs:** 
[debug.log](https://github.com/ppy/osu/files/2694979/debug.log)
[performance.log](https://github.com/ppy/osu/files/2694980/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2694981/runtime.log)
[database.log](https://github.com/ppy/osu/files/2694982/database.log)

**Comment by peppy** [comment]
What keyboard layout are you on?

**Comment by carlobolla** [comment]
Italian Layout (qwerty, normal)

**Comment by jorolf** [comment]
This is probably a duplicate of https://github.com/ppy/osu-framework/issues/1965

**Comment by carlobolla** [comment]
I guess it is, note that the combination for @ in italian keyboards is `Alt Gr + ò`

**Comment by peppy** [comment]
Closing as duplicate of https://github.com/ppy/osu-framework/issues/1965.
