### ISSUE TITLE
Spacebar as shortcut key for "Deselect All" in Mods Selection

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3885]
**Describe the feature:** I suggest to use the spacebar as the shortcut key to deselect all mods or, more in general, a key that triggers this function for players that frequently use this shortcut in the stable version.

**Designs:** No needed. Just a screenshot of the `Deselect All` option:
![deselect option](https://user-images.githubusercontent.com/43073074/50230131-5f525400-03ac-11e9-92bd-ce37278f7db5.png)

**Comment by UselessToucan** [comment]
I would prefer exactly the same behaviour as in osu! stable which is "1" for resetting mods and "2" for closing the overlay.
![screenshot004](https://user-images.githubusercontent.com/22450664/50242335-0d74f280-03db-11e9-80c5-7feec647a888.jpg)

**Comment by akainocode** [comment]
A suggestion to add on, could this be added as a modifiable keybind?

**Comment by Joehuu** [comment]
Fixed in #4841, shortcut key being `1`. Not sure about spacebar.

**Comment by peppy** [comment]
We can add customisation for this later, maybe. Closing for now.
