### ISSUE TITLE
Where is the Song folder located under macOS (osu-lazer)?

### ISSUE THREAD

**Issue by AndyChen2005121** [ppy/osu#3910]
I'm a Mac user but **I'm using a Wine-bottled Windows Client before soooo I can't find the beatmap folder for osu!lazer on mac**. Where is it?

**Comment by AndyChen2005121** [comment]
I can't use the "load beatmap from osu stable" feature. **(Because I'm using a Wine-bottled Windows Client) x2**

**Comment by peppy** [comment]
If you want to migrate your beatmaps, you can move or symlink them to `~/.osu/Songs`.

**Comment by lucytao01** [comment]
Doesn't work. Going to ~/.osu/Songs leads me to my home page.

**Comment by theonlygusti** [comment]
Where is the song folder?

I want to share a song with a friend.

**Comment by bdach** [comment]
@theonlygusti If you're looking to pull songs from lazer, the new storage structure is different from stable and not intended to be used by humans straight out (files are stored in `~/.local/share/osu/files` under their sha256 hashes).

If you want to link someone an online beatmapset, right click on it in song select, click *Details...*, and then the *View in browser* icon near the song name in the overlay. It'll direct you to the web version which you can share by link.

**Comment by theonlygusti** [comment]
@bdach 

![Screenshot 2019-10-17 at 17 08 07](https://user-images.githubusercontent.com/10684786/67026973-b629d680-f100-11e9-96be-0b590ef64f12.png)

where is the icon?

**Comment by bdach** [comment]
![image](https://user-images.githubusercontent.com/20418176/67027120-4c61fa80-f109-11e9-99fd-6e32c15e0b6e.png)

**Comment by theonlygusti** [comment]
@bdach what if that button isn't there?

I just found a beatmap without it.

How can I share this beatmap with someone else?

**Comment by bdach** [comment]
> I just found a beatmap without it.
> 
> How can I share this beatmap with someone else?

That sounds like a beatmap that didn't come from web (either edited locally, or downloaded from another source). For now I don't think there is a way to export those. That functionality will come eventually when the editor is complete.
