### ISSUE TITLE
Option to revert back to stalbe's skin model/design

### ISSUE THREAD

**Issue by RedErick2903** [ppy/osu#3920]
**Describe the feature:** For those of us who don't like how lazer's skin looks(and any other skin made for Lazer or tried in Lazer), you could add a button, specifically in the settings, under skins, which makes skins look like in the current stable. This should only change the skin when playing a beatmaps, not reverse everything else like menus, etc. Things which I would like to see changed would be sliders - slider start does not move with your cursor as you complete it and the slider design in itself.
**Proposal designs of the feature:** Just as in the current stable, the button in settings should really be like any other option in settings. No screenshots because it is straight forward. I will try my best to get a screenshot of it if it's really needed.

**Comment by peppy** [comment]
You can already load the stable skin in (google osu skin template and drag into lazer window). You can disable slider snaking in settings.
