### ISSUE TITLE
In beatmap details, missing source text results in a larger gap

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#3922]
**Describe your problem:** I'm not sure if this design was intended, but when a beatmap does not specify Source a larger gap is produced between Description and Tags.

**Screenshots or videos showing encountered issue:**

Beatmap with Source: ![beatmap with source](https://i.imgur.com/xlGijpz.jpg)

Beatmap without Source: ![beatmap without source](https://i.imgur.com/YkCXuyM.jpg)

**osu!lazer version:** 2018.1219.0

**Logs:** unnecessary

**Comment by Appreciativeness** [comment]
Likely accidental, due to the spacing being equal to the padding between the Description and Source sections and the Source and Tags sections. Could easily be fixed by making an if statement for the second padding, or by displaying "There is no source." or something similar when there is no source.
