### ISSUE TITLE
Taiko Multiplayer does not Submit score

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3931]
**Describe your problem:** After completing aTaiko map it doesnt submit and i get a error

**Screenshots or videos showing encountered issue:** N/A

**osu!lazer version:** 2018.1227.0

**Logs:** 
[network.log](https://github.com/ppy/osu/files/2712370/network.log)
[performance.log](https://github.com/ppy/osu/files/2712371/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2712372/runtime.log)
[database.log](https://github.com/ppy/osu/files/2712373/database.log)

**Comment by peppy** [comment]
Can you confirm other rulesets work fine?

**Comment by MillhioreF** [comment]
I just tried a timeshift map in osu! mode (with easy mod enabled) and my score didn't submit either.

`12/27/2018 12:37:13 PM: Request to https://osu.ppy.sh/api/v2/rooms/24/playlist/24/scores/269 failed with System.Net.WebException: UnprocessableEntity.
12/27/2018 12:37:13 PM: Failing request osu.Game.Online.API.Requests.SubmitRoomScoreRequest (System.Net.WebException: UnprocessableEntity)`
