### ISSUE TITLE
Scrollbar extends behind masked off area in PlaylistOverlay

### ISSUE THREAD

**Issue by jorolf** [ppy/osu#3942]
**Describe your problem:** the scrollbar/scrollpancake scrolls outside of the scrollcontainer and becomes invisible

**Screenshots or videos showing encountered issue:** 

![playlistoverlay](https://user-images.githubusercontent.com/12570757/50484987-97344980-09f3-11e9-88ab-867ee844653b.gif)

**osu!lazer version:** 2018.1227.1

**Comment by jorolf** [comment]
It still happens for me

**Comment by smoogipoo** [comment]
Fixed by referencing PR.
