### ISSUE TITLE
When changing keyboard bindings, the game freezes momentarily

### ISSUE THREAD

**Issue by daduckMSFT** [ppy/osu#3950]
**Describe your problem:** Using osu! lazer, version 2018.1227.1
I went into the menu to modify my  key bindings (from the default of A/S to Z/C). When I press the key, to change the binding, the game freezes momentarily. I don't recall this happening previously in the past, so I thought it might be noteworthy. 

Note - the issue is not happening consistently. I logged in, started this, and went to take a video and now the issue hasn't happened - whereas, before, it was consistently doing it regardless of game restarts etc. I haven't been able to reproduce it either.. but I did get logs from the install where it happened. 

I've also attempted a reinstall , but it's seeming to have my settings and I haven't ran a procmon to find where these may exist - so 

**Screenshots or videos showing encountered issue:** 
Screenshot of what I'm looking at: 
![Screenshot of the bindings in the menu](https://i.upsetdavid.com/img/b70c0afc-a6fc-40fd-a797-4a38747ca954.png)

**osu!lazer version:** 2018.1227.1

**Logs:** [logs.zip](https://github.com/ppy/osu/files/2713093/logs.zip)

**Comment by peppy** [comment]
May be resolved via #11461, should double-check.

**Comment by peppy** [comment]
There's a slight spike on rebinding due to reconstructing / propagating all changes rather than just the changed key. Nonetheless, I wouldn't consider this a serious freeze any more.
