### ISSUE TITLE
Prompt/confirm before exiting game when actions are taking place

### ISSUE THREAD

**Issue by daduckMSFT** [ppy/osu#3952]
**Describe the feature:** Currently, I am setting up a reinstall of osu! lazer. 
As part of my import from Stable (beatmaps and skins), I instinctively closed the game when doing the previous reinstall - but the game was active importing beatmaps and skins (a timely procedure). 

It'd be nice if there are certain actions (such as importing skins/beatmaps) that - _**when you attempt to close the game via a graceful method**_ - that you get told something such as:

> You are currently importing your beatmaps (or) skins (or) beatmaps and skins! Are you sure you would like to exit?
> Exit, Cancel

**Comment by takoz53** [comment]
Agree, might even break some osu! files while mid-import (Can't be sure. Don't know how its handled). It would be great if there was a message to it and a proper way to Dispose the import if attempted to exit.

**Comment by Gabixel** [comment]
A first release with a dialog before closing the game has been released, but I don't know if the "- _when actions are taking place_" part is planned.

**Comment by smoogipoo** [comment]
I think it's fine with the current prompt, @peppy ?

**Comment by peppy** [comment]
Let's leave this open. UX can be improved similar to stable, with better messaging based on what is currently going on.

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu/pull/23987.

**Comment by naworm** [comment]
It is not nice, how to get rid of this !? There is no option...

<img width="1044" height="546" alt="Image" src="https://github.com/user-attachments/assets/bbc7d6ee-1fde-4ebf-8066-37193a06be7b" />
