### ISSUE TITLE
Multiplayer games somehow created with no beatmap

### ISSUE THREAD

**Issue by peppy** [ppy/osu#3958]
Unsure how this happens as of yet. Probably also requires server-side validation.

![image](https://user-images.githubusercontent.com/191335/50503023-1171d600-0aa7-11e9-8212-8e121e3b2508.png)

**Comment by smoogipoo** [comment]
I'm really not sure how this could happen client-side unless it's the result of client modification. The apply button is not enabled until there's 1 playlist item.

**Comment by peppy** [comment]
If anyone replicates this (it should show an error when you actually hit the "create room" button) please report it here in as much detail as possible.

**Comment by peppy** [comment]
This is guarded against server-side and there have been no recent user reports. Closing for now.
