### ISSUE TITLE
Song select group/sort modes don’t work as expected

### ISSUE THREAD

**Issue by unhappyjap** [ppy/osu#3961]
When ordering beatmaps, I have mine set to No grouping and Date added in the stable osu! client
![screenshot010](https://user-images.githubusercontent.com/46220576/50514382-8960f000-0ae9-11e9-9069-1f3fa326308d.jpg)

In osu!lazer I have the same setting but the maps are ordered differently for some reason.

osu!lazer 2018.1228.0

**Comment by Gabixel** [comment]
If I don't mistake, groups and "sort by" filters don't work at the moment, but I'm not 100% sure

**Comment by peppy** [comment]
Replaced by https://github.com/ppy/osu/issues/4919.
