### ISSUE TITLE
No space in profile info text

### ISSUE THREAD

**Issue by unhappyjap** [ppy/osu#3962]
I found that the text here doesn't have any spaces when viewing someones profile
![inkedosu_2018-12-28_21-54-35_li](https://user-images.githubusercontent.com/46220576/50515210-0e9ad380-0aef-11e9-94eb-abb85b1df5de.jpg)

osu!lazer 2018.1228.0

[runtime.log](https://github.com/ppy/osu/files/2714829/runtime.log)
[database.log](https://github.com/ppy/osu/files/2714830/database.log)
[network.log](https://github.com/ppy/osu/files/2714831/network.log)
[performance.log](https://github.com/ppy/osu/files/2714832/performance.log)

**Comment by Gabixel** [comment]
The "0pp" problem is a duplicate of #3937 
For the text problem maybe this issue can be relevant

**Comment by unhappyjap** [comment]
i will edit out the duplicate issue. thank you
