### ISSUE TITLE
Crash related to having multiple notes at one time in osu!catch

### ISSUE THREAD

**Issue by Appreciativeness** [ppy/osu#3965]
**Describe your problem:** Was playing [this](https://osu.ppy.sh/beatmapsets/802442#fruits/1684112) map, converted in AutoPlay. Got right up to the first section where there are multiple notes at one time. This map plays fine in osu!stable.
Tried it again afterwards, it happened again about 100ms later. Therefore, I am almost certain the two parts are related.

**Screenshots or videos showing encountered issue:** N/A

**osu!lazer version:** 2018.1228.0

**Logs:**
I don't know why but you really gotta inform me that X was supposed to be finite, but it was infinity.
So much so, that you cause the log file to be 1.15 MB
[runtime.log](https://github.com/ppy/osu/files/2716023/runtime.log)

**Computer Specifications:** 
Operating System: Windows 10 (x64)         
OS Version: Build 17134                    
CPU: Intel Core i3-7100U                   
CPU Speed: 2.40 GHz (2400 MHz)             
GPU: Intel HD Graphics 620                 
RAM: 4 GB (4096 MB)

**Comment by ekrctb** [comment]
Probably fixed by #5035.
