### ISSUE TITLE
Add skinning support for osu!catch fruits

### ISSUE THREAD

**Issue by Appreciativeness** [ppy/osu#3967]
**Describe the feature:** Skinning Elements for osu!catch

**Designs:**
![screenshot242](https://user-images.githubusercontent.com/46136945/50537855-8c95c380-0b5d-11e9-833c-84cc8d491df0.jpg)
![screenshot243](https://user-images.githubusercontent.com/46136945/50537860-b18a3680-0b5d-11e9-8adb-d531a43d922c.jpg)
![screenshot244](https://user-images.githubusercontent.com/46136945/50537869-db435d80-0b5d-11e9-90a6-4e14d0d98bef.jpg)

**Comment by phosphene47** [comment]
What is the issue? If you mean replacing the default osu!lazer skin with this, it will not happen. You will be able to customize the gameplay using skins.

**Comment by Appreciativeness** [comment]
I don't mean replacing the default. I mean allowing for osu!catch elements to be skinned in osu!catch. Those are examples of skinned elements.

**Comment by GSculerlor** [comment]
Not sure if all skinning element is implemented all, osu mode itself still missing many element and I'm sure people still working on it so making this issue is kinda pointless

**Comment by peppy** [comment]
You can easily follow example and add skinning support if you'd like to contribute!

**Comment by lolita-is-godddd** [comment]
(I thought latest build can change the elements, can't be?)
