### ISSUE TITLE
random suggestions for osu!lazer

### ISSUE THREAD

**Issue by 00023** [ppy/osu#3972]
Mods:

Rain(osu!std, for fun) works like transform expect notes move down(or fall) to their places

Sunlight(osu!std, diff increase, goes under flashlight) like flashlight but the radius near your cursor is full white(or sun bright) and you can't see any notes there, gets bigger with higher combo(like flashlight)

Distraction(osu!anything, for fun) have random objects fly across the screen(objects can be anything, how many distraction objects on screen at a time should be based on diff)

Easy (for high star maps)(osu!std, diff reduction, over Easy or under, doesn't matter)It's like easy expect the AR doesn't get lowered, make it only work on +4* maps

Other:

Import osu!stable default skin into osu!lazer so people can choose between either skin when they first download osu!lazer(some people might want a nice looking skin)

Allow option on what happens when notes are clicked(1. disappear; 2. pulse out, short fade; 3. pulse out, no short fade)(the feedback upon clicking circle feels strange because the circle just disappears

Allow spinners to have bonus pts(ex. If no spinners are on a beatmap and someone gets 100%, then score=1,000,000; If there's spinners but the person spins just fast enough to get "300 or great" but no bonus pts and  they get a 100%, then score=1,000,000; If the spinners result in 6000 bonus pts and 100%, then score=1,006,000 (I suggest to have the spinner bonus pts that aren't combo affected and to show spinner pts separate from other pts))

Have the "update the map" button be set as drawer style at the song box thing like this ASCII art example:

                              _____________________________________________________________________________
                            /                           /  SONG NAME                                                                                                           |     
                            |    Update!        |  ARTIST                                                                                                                      |
                            \                           \ (DIFFS)                                                                                                                      |
                              _____________________________________________________________________________ 

Have the option to set the mods option as full screen or current osu!lazer design (it seems like you can use the whole screen instead of part of the screen and a scroll bar although some people may prefer the osu!lazer design)

Show HP over the map graph at the song results screen, place by the side
-If you want to add once, a accuracy graph, have it below the HP graph or mix it with the HP graph(acc graph only starts counting acc after 20 notes) (can be useful to gauge performance)  

Have the option to choose between osu!lazer gameplay design and osu!stable

If a mod changes diff, keep the original diff yellow colored and have the extra part for diff increases be redder and other way around(use green or blue) for diff lowering (showing diff changes will be needed so people don't misjudge map diff) 

Thanks for considering.

**Comment by daniel11420** [comment]
"Import osu!stable default skin into osu!lazer so people can choose between either skin when they first download osu!lazer(some people might want a nice looking skin)"

Do you mean import skins from stable? Thats already a feature, bottom of settings

**Comment by 00023** [comment]
what i mean by that is import the default skin from osu!stable (current version)

**Comment by peppy** [comment]
Please open individual issues.

**Comment by 00023** [comment]
@peppy by individual, you mean post each suggestion on its own post, right?

**Comment by Poyo-SSB** [comment]
Yes.
