### ISSUE TITLE
Failing to import maps with spaces

### ISSUE THREAD

**Issue by Deathray-II** [ppy/osu#3973]
**Problem:**
When attempting to import any map which contains spaces osu will fail to import, saying that it cannot import "(Size).osz" if the file I attempt to import is "87630 Linked Horizon - Guren no Yumiya (TV Size).osz".
When I attempt to import it via the commandline (in my case by giving `osu-lazer filename`) it will output the following if the filename is `/home/jasper/Downloads/87630\ Linked\ Horizon\ -\ Guren\ no\ Yumiya\ \(TV\ Size\).osz`:
```
Importing /home/jasper/Downloads/87630
Importing Linked
Importing Horizon
Importing -
Importing Guren
Importing no
Importing Yumiya
Importing (TV
Importing Size).osz
```
This is also the same output that I will get if I encapsulate the filename as a string and thus use the following command
```
osu-lazer "/home/jasper/Downloads/87630 Linked Horizon - Guren no Yumiya (TV Size).osz"
```
However if I change all the spaces into underscores happily imports the beatmap.

**What I think is going on:**
What this looks to me like is that at some point these paths are getting parsed and split base on spaces, presumably in case a list of files in passed to it and then these split files get all called one by one to import but the system will report that it is not a valid archive since these are all files that do not exist. I can guarantee that this does not happen at the level of the shell because the first one was properly escaped and the second one will get passed entirely as a single parameter to the script.
What the `osu-lazer` script does in this case is the following:
```
#!/bin/sh
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/osu-lazer"
exec dotnet '/usr/lib/osu-lazer/osu!.dll' "$@"
```
It simply passes all the parameters as strings, so in this case it passes a single parameter (the filename) as a string to osu itself.

**Screenshots or videos showing encountered issue:** 
![screenshot_20181230_155031](https://user-images.githubusercontent.com/17166465/50548367-94339600-0c4b-11e9-875b-e69a8a283de3.png)
![image](https://user-images.githubusercontent.com/17166465/50548356-6d755f80-0c4b-11e9-9879-0e7aea878e77.png)

**osu!lazer version:**
local version but I am using osu-lazer-git-2018.1228.0-1, which should be a build from the latest master at the time of submitting this issue

**Environment:**
Arch Linux
osu-lazer-git-2018.1228.0-1
mono-5.16.0.220-1
**Logs:**
[database.log](https://github.com/ppy/osu/files/2717231/database.log)
[performance.log](https://github.com/ppy/osu/files/2717233/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2717234/runtime.log)
[network.log](https://github.com/ppy/osu/files/2717236/network.log)

**Comment by morguldir** [comment]
Duplicate of https://github.com/ppy/osu/issues/3723


It’s a bug with the arch package for dotnet

https://bugs.archlinux.org/task/60816?project=5&string=dotnet-runtime

**Comment by Deathray-II** [comment]
ah I see, it's the exact same thing that I checked the `osu-lazer` script for. Thank you for pointing this out.
