### ISSUE TITLE
Options counter could not be opened nor closed

### ISSUE THREAD

**Issue by Examsheep** [ppy/osu#3978]
When I open osu, it drops to very low fps,click on options, the overlay is not seen and I couldn't adjust the settings.
Or I open the options when it didn't drop to low fps,it immediately drop to low fps and the optipons tab couldn't be closed.
But the other buttons could work normally.

Conclusion: When there is low fps, the options tab did not respond.

Osu version: Stable20181231.2
[runtime.log](https://github.com/ppy/osu/files/2719184/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/2719185/update_success.log)

**Comment by peppy** [comment]
Hey,

This repository is for osu!lazer issues. Please report your issue on the [forum](https://osu.ppy.sh/community/forums/5).
