### ISSUE TITLE
Editor gives hitobjects incorrect combo numbers

### ISSUE THREAD

**Issue by Appreciativeness** [ppy/osu#3979]
**Describe your problem:** So, I created the Note marked as 4 that's lower down first, then made 5 after it. I then switched to 1/2 and placed another note, and now there are two notes marked 4.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/46136945/50573026-d5e74c80-0dc3-11e9-8450-52d3c9bb564a.png)

**osu!lazer version:** 2018.1228.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/2719319/runtime.log)
[performance.log](https://github.com/ppy/osu/files/2719320/performance.log)

(Edited to remove top comment, whoops)

**Comment by shavitush** [comment]
@Appreciativeness is this still a bug? i have tried to reproduce this on my setup in order to implement a fix but i am unable to reproduce the bug

**Comment by peppy** [comment]
Has since been resolved.
