### ISSUE TITLE
Unable to login at lazer

### ISSUE THREAD

**Issue by rinimotion** [ppy/osu#3981]
**Describe your problem:** While trying to log in; The token authorization page just gives no actual response.

**Screenshots or videos showing encountered issue:** https://drive.google.com/file/d/1IgxtAuQJBWKmJIAtj87-BA5Vvp8mu_gt/view?usp=drivesdk

**osu!lazer version:** 2018.1228.0, stable

**Logs:** 
```
1/1/2019 5:43:52 PM: ----------------------------------------------------------
1/1/2019 5:43:52 PM: Network Log for rini (LogLevel: Verbose)
1/1/2019 5:43:52 PM: osu 2018.1228.0.0
1/1/2019 5:43:52 PM: Running on Microsoft Windows NT 6.2.9200.0, 4 cores
1/1/2019 5:43:52 PM: ----------------------------------------------------------
1/1/2019 5:43:52 PM: We just went Connecting!
1/1/2019 5:44:02 PM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
1/1/2019 5:44:12 PM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
1/1/2019 5:44:12 PM: Login failed!
1/1/2019 5:44:12 PM: We just went Offline!
```

**Comment by peppy** [comment]
Hey,

Looks like you are getting timeouts. Can you access the osu! website okay?

**Comment by rinimotion** [comment]
> Hey,
> 
> Looks like you are getting timeouts. Can you access the osu! website okay?

Yep, I can login completly fine in website and stable osu. The issue is only with lazer.

**Comment by peppy** [comment]
Do you use a proxy setup, or anything weird with your network? Are you able to test on a different connection to see if it works?

**Comment by rinimotion** [comment]
> Do you use a proxy setup, or anything weird with your network? Are you able to test on a different connection to see if it works?

I don't use any proxy setups, and i'm unable to test on another connection as of right now.

**Comment by rinimotion** [comment]
Huh. for some reason my WebClient was disabled when i never really touched it. Issue solved!
