### ISSUE TITLE
Crash while installing osu!lazer

### ISSUE THREAD

**Issue by Nebbilies** [ppy/osu#3983]
**Describe your problem:** When I ran the osu!install.exe, A installation error dialog show up with the log below.

**Logs:** https://drive.google.com/open?id=15CaR_1LTIH26R2xJr0B9QMjBGkUsrv9G

**Computer Specifications:** 
RAM: 2GB
Windows 7 32bit
Processor: Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz, 2401 Mhz, 2 Core(s), 2 Logical Processor(s)
Graphics Card: Mobile Intel(R) 4 Series Express Chipset Family

**Comment by RevertedClock** [comment]
lazer does not support 32 bit

**Comment by peppy** [comment]
Closing in favour of #3984.
