### ISSUE TITLE
Add 32bit windows installer / update route

### ISSUE THREAD

**Issue by peppy** [ppy/osu#3984]
Currently we do not support 32 bit OS/platforms in the deploy process. We should add support as there are plenty of users still needing this.

Continues trail from #3651.

(see ppy/osu-framework#1619)

**Comment by mcendu** [comment]
Should we put it in osu-deploy?

**Comment by peppy** [comment]
yes.

**Comment by caesay** [comment]
Just FYI - 32bit and win7 is currently supported in Velopack but I do plan on deprecating support for both soon. I just don't have the automated testing infrastructure for it, and it takes a very long time to manually do these types of tests.

**Comment by peppy** [comment]
I'm not sure we'll be adding 32 bit support ever, at this point. Seems pretty pointless.
