### ISSUE TITLE
Osu!Lazer black screen on start

### ISSUE THREAD

**Issue by ScribbleNerd** [ppy/osu#3988]
I have already put this is the Osu! discord and no one was able to help so I'm putting it here
Whenever I launch Osu!Lazer, it just displays a black screen https://youtu.be/8h4_HdW5wpM
The logs contain almost no information but I will still upload them:
[logs.zip](https://github.com/ppy/osu/files/2721734/logs.zip)

**Comment by ScribbleNerd** [comment]
reinstalling Osu!Lazer has fixed this issue

**Comment by peppy** [comment]
Glad to hear.
