### ISSUE TITLE
HD,HR Mods can not be worked in osu!catch.

### ISSUE THREAD

**Issue by serenityP** [ppy/osu#3989]
**Describe your problem:** 
 HD is completely invalid in osu!catch. HR is only workable to CS, not to AR (OD HP unknown).     

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2018.1228.0
**Logs:**

**Comment by peppy** [comment]
Yes they are not implemented yet.

**Comment by peppy** [comment]
it's fine to leave this open.

**Comment by Joehuu** [comment]
Hidden mod implemented in https://github.com/ppy/osu/pull/5176.

**Comment by ekrctb** [comment]
HD is implemented.
HR alters AR.
