### ISSUE TITLE
How about CTB editor?

### ISSUE THREAD

**Issue by lolita-is-godddd** [ppy/osu#3991]
**Describe the feature:** It is hard to emulate CTB map from OSU map, also it has worse effective to convert. So I want to ability of setting distance, switch HyperDash,fruit color, etc can set stable .

 

**Proposal designs of the feature:**  preparing...

**Comment by peppy** [comment]
Yes, it is planned.

**Comment by lolita-is-godddd** [comment]
yeahhhhhhhhhhhh
!!,!

**Comment by lolita-is-godddd** [comment]
ah sry
btw should i attach designs?

**Comment by peppy** [comment]
You can if you'd like, but keep in mind we generally produce UI designs ourselves.

**Comment by lolita-is-godddd** [comment]
![img_0480](https://user-images.githubusercontent.com/25249461/50622911-52a93080-0f54-11e9-8775-7244e35be6bc.PNG)
weird image... but it is my suggestions .
would you review design?

**Comment by peppy** [comment]
Thanks, but this kind of design input is not helpful. Please leave it to us.

**Comment by lolita-is-godddd** [comment]
well- the tool bars?
above bar can set background, timing, storyboard (same as stable)
right click shows setting color, hyperdash turns
shortcut bar contain test play and exit editor
also, it is important to put ruler shows millisecond , isn't it?

**Comment by peppy** [comment]
Please stop.

**Comment by peppy** [comment]
Closing for now as having such a general issue tot rack this task is not required.
