### ISSUE TITLE
Don't put beatmaps into Disk C

### ISSUE THREAD

**Issue by serenityP** [ppy/osu#3995]
**Describe the feature:** 
Please make the client to recognize beatmaps which are in the "osu" folder .  I played lazer for 3 hours and Disk C was almost full ! So I turn in this issue immediately. I hope this small feature will be added.
Thank you!
**Proposal designs of the feature:** 
osu!lazer can recognize "files" folder everywhere in any Disk if players move this folder to Disk D due to the small space of Disk C. 
![20190103195457](https://user-images.githubusercontent.com/13845063/50636554-7b9be680-0f91-11e9-9b7e-d9eb2fc897ba.jpg)

**Comment by STCapricorn** [comment]
duplicate of #960

**Comment by RevertedClock** [comment]
for the time beeing you can "symlink" the folder / game to another place.

**Comment by serenityP** [comment]
thank you,I has created mklink to deal with this issue.
