### ISSUE TITLE
osu!catch star difficulty and rank system are not implemented

### ISSUE THREAD

**Issue by serenityP** [ppy/osu#4002]
**Describe your problem:** 
The star rating system in osu!catch is not implemented( only valid in converted beatmaps ).
Rank system is the same as the one in mania. 98%acc S  94%acc A  but now is 95%acc S  90%acc A
Some sildes can not be converted into droplets correctly, some of droplets miss.
ACC does not be decreased when missing droplets and it only calculates notes.    

I don't know that OD system is implemented in osu!catch.
It seems that OD0 is almost the same as OD10.(maybe stable = lazer)

Maybe revise “show converted beatmaps” to "only show converted beatmaps"
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2018.1228.0

**Logs:**

**Comment by Ratchet0203** [comment]
Oh, I didn't notice this was already covered. Glad to know people are catching on.

**Comment by Joehuu** [comment]
This was long since implemented.
