### ISSUE TITLE
Notifications/Settings bar uncomfortably pushes the multiplayer lounge screen away

### ISSUE THREAD

**Issue by PancakeGD** [ppy/osu#4003]
**Describe your problem:** 
When notifications or settings are opened the multiplayer lounge screen is pushed and the background below it is then visible Maybe make the screen "wider" so this doesn't happen?

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=6-8LRden25w&feature=youtu.be

**osu!lazer version:** 2018.1228.0

**Logs:**
[debug.log](https://github.com/ppy/osu/files/2730263/debug.log)
[network.log](https://github.com/ppy/osu/files/2730264/network.log)
[performance.log](https://github.com/ppy/osu/files/2730265/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2730266/runtime.log)
[database.log](https://github.com/ppy/osu/files/2730267/database.log)

**Comment by Aergwyn** [comment]
Hint that the [ModSelectOverlay](https://github.com/ppy/osu/blob/dfc903fec2891e5dfa9ac35a0024f0c5858ca0e3/osu.Game/Overlays/Mods/ModSelectOverlay.cs#L33) had to solve the same issue.
