### ISSUE TITLE
Crash when beatmap gets imported in the multiplayer lobby

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#4018]
**Describe your problem:** When a map gets imported on the multiplayer screen you get the notification that the beatmap import failed however at the same time it says that it got imported. clicking on this notification causes a crash. 

**Screenshots or videos showing encountered issue:** n/a

**osu!lazer version:** 2c94b54c0..e4ff36a5b  master 

**Logs:** 
[network.log](https://github.com/ppy/osu/files/2736881/network.log)
[performance.log](https://github.com/ppy/osu/files/2736882/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2736883/runtime.log)
[database.log](https://github.com/ppy/osu/files/2736884/database.log)

**Computer Specifications:** i3 6100 8gb ram windows 10 x64 1809

**Comment by peppy** [comment]
This can potentially use the new leased bindable pathway for some amaze. TBD.

**Comment by smoogipoo** [comment]
I can't replicate this, also your logs say the last screen you were in was solo play song select?

**Comment by Lolihunter1337** [comment]
@smoogipoo might be my bad for the bad wording it does happen on the multiplayer *create room* screen where you set up the lobby at.

**Comment by smoogipoo** [comment]
Ah, managed to replicate, thanks!
