### ISSUE TITLE
Make osu!, along with osu!lazer, detect a graphic card's poor power management mode setting

### ISSUE THREAD

**Issue by TicClick** [ppy/osu#4019]
For instance, that could be (and should be) [NVIDIA's "Power management mode"](https://nvidia.custhelp.com/app/answers/detail/a_id/3130/~/setting-power-management-mode-from-adaptive-to-maximum-performance) set to "Adaptive" instead of "Maximum performance". Would love to have this specific issue detection backported to stable version of osu!, too.

**Comment by HoLLy-HaCKeR** [comment]
Not everybody wants to kill their laptop's battery with osu!. I think this is out of scope.

**Comment by ticotaco72** [comment]
And you can do this manually or automatically in windows

**Comment by peppy** [comment]
Asaptivw mode is generally there for a reason and doesn’t eeducr performance beyond core (“turbo boost”) clock adjustment curves, right?

**Comment by Banbeucmas** [comment]
@HoLLy-HaCKeR we can just implement a caution rather than automatically set it. 
It took me a while to know that my fps is locked down due to AMD power management plan also

**Comment by peppy** [comment]
See above comment. You can't be against it without first investigating.

**Comment by TicClick** [comment]
> Adaptive mode is generally there for a reason and doesn’t affect performance beyond core (“turbo boost”) clock adjustment curves, right?

At least for NVIDIA, there's actually three options, as far as I can remember: low power consumption, adaptive mode, and full performance. A friend of mine had a hard time starting and minimizing/restoring osu! running in fullscreen; took us both a while to find the cause.

What I'm suggesting is not to force the best performance but show a warning, like that for f.lux running simultaneously with osu!.

**Comment by peppy** [comment]
Closing as out of scope. We shouldn't be looking to change settings that a user has set (and lazer should be optimised to a point any of the power modes should be enough to run it).
