### ISSUE TITLE
In timeshift if the selected beatmap is deleted, a different beatmap can be played

### ISSUE THREAD

**Issue by qwewqa** [ppy/osu#4033]
**Describe your problem:**
In timeshift, when creating a room, if a map is selected, it is possible to reenter song selection and delete the beatmap. When returning to the new room screen, the now deleted beatmap remains selected. After the room is created, pressing start will take you to a different beatmap than the one selected in the room and the score will be submitted if the beatmap is completed.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/bxkia

**osu!lazer version:**
2018.1228.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/2743339/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2743340/runtime.log)
[database.log](https://github.com/ppy/osu/files/2743341/database.log)
[network.log](https://github.com/ppy/osu/files/2743342/network.log)

**Comment by ekrctb** [comment]
Is #4093 relevant or addressing this issue? Probably should be tackled after that change.
