### ISSUE TITLE
SourceLink isn't working in rider

### ISSUE THREAD

**Issue by peppy** [ppy/osu#4039]
Appreciate whether people could check if it's working in other IDEs or if something is misconfigured.

**Comment by smoogipoo** [comment]
For me, it worked until the point where the relevant PR was merged :/

**Comment by miterosan** [comment]
Sourcelink is currently disabled. EnableSourceLink needs to be set to true in the csproj

**Comment by miterosan** [comment]
That was done with the disable sourcelink on mono PR.

**Comment by miterosan** [comment]
This is most likely cause by the not working Condition on the sourcelink itemgroup. When you remove the condition it works again.
