### ISSUE TITLE
can't find osu stable version to import beatmaps

### ISSUE THREAD

**Issue by Akirakurusu0** [ppy/osu#4043]
**Describe your problem:** After downloading lazer! i wanted to import all my beatmaps from stable osu..problem is lazer can't find my stable version..here is the screen plus the logs..using latest lazer btw
tried everything like installing again or deleting osu stable and retrying...i changed osu stable install directory btw!

![osu_2019-01-11_12-18-34](https://user-images.githubusercontent.com/46596185/51030878-0df84780-159b-11e9-9834-bfa374a5b10f.jpg)

[debug.log](https://github.com/ppy/osu/files/2749396/debug.log)
[performance.log](https://github.com/ppy/osu/files/2749397/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2749398/runtime.log)
[database.log](https://github.com/ppy/osu/files/2749399/database.log)

**Comment by peppy** [comment]
lazer will attempt to find your stable installation by checking the registry along with other methods. did you allow osu! (stable) UAC permissions when you start it up? If not you may be missing the registry hint.

**Comment by Akirakurusu0** [comment]
@peppy when I started OSU (stable) I gave it the permissions when it asked me..and always gave it when updating

The full path to my OSU installation is:
D:\Username\osu!2

It's not username..I don't want to put my name y'know...and the 2 in osu!2 is Normal..i don't have 2 osu installations or something..just that I wanted to put a 2

**Comment by dragonGod97677** [comment]
Yeah me too.. i try repair osu and UAC is turned off but nothing.. still not found

**Comment by darsparx** [comment]
I'm having issues as well....I decided to test it out on my mac and it just refuses to find the stable....and the issue that led me here said something about changing where stable is(which it's where it always has been since installing stable years ago) and I can't find that option just so maybe it'll import all those maps and skins...

**Comment by Gabixel** [comment]
Seems to happen also to me with the latest release: ([2019.330.0](https://github.com/ppy/osu/tree/2019.330.0))

![osu_2019-03-30_13-24-58](https://user-images.githubusercontent.com/43073074/55276067-21d85d80-52ef-11e9-82fa-78a018d5eabd.jpg)

**Comment by Morilli** [comment]
Can confirm this does not happen on 2019.323.0 but on the newest release (2019.330.0).

**Comment by dragonGod97677** [comment]
its ok now for me, it founded the location of stable but now it shows "import failed"... heres the logs
[logs.zip](https://github.com/ppy/osu/files/3200408/logs.zip)

and screenshot **
![image](https://user-images.githubusercontent.com/38875906/58062811-6d500f00-7bae-11e9-92a9-6a62279efe6e.png)
**

**Comment by dragonGod97677** [comment]
2019.530.0 is showing the error too, Import failed

**Comment by dragonGod97677** [comment]
I think this should be closed. Importing from stable is working
