### ISSUE TITLE
osu!taiko only ends if last note is hit

### ISSUE THREAD

**Issue by GHOSTBEAR** [ppy/osu#4048]
Most of the times when I play osu!taiko the game only ends if I hit the last note, and sometimes this doesn't work either. 

[Screen Recordings.zip](https://github.com/ppy/osu/files/2751513/Screen.Recordings.zip)

osu!lazer version: 2019.111..0

[logs.zip](https://github.com/ppy/osu/files/2751504/logs.zip)

**Comment by peppy** [comment]
Possibly inadvertently related to #3827.

**Comment by GHOSTBEAR** [comment]
Seems to be fixed in the latest version 2019.227.0
