### ISSUE TITLE
ios osu lazer crashes everytime I go into osu! direct. 

### ISSUE THREAD

**Issue by Rubmybabies** [ppy/osu#4053]
So basically osu lazer for ios works fine until I go to osu! direct. When I click that button, it takes me to the osu! direct page but it doesn't show any beatmaps and after a few seconds the app crashes. 

I have an up to date Iphone 6 (Model a1549).  Pls help.
<3 peppy

**Comment by peppy** [comment]
Thanks for your report, but it's a bit too early to report iOS bugs yet (iOS support is not yet merged). I can almost definitely say this is memory related, though.
