### ISSUE TITLE
Crash when you hit ESC while joining a lobby

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#4055]
**Describe your problem:** If you join a lobby and press ESC fast enough the game crashes

**Screenshots or videos showing encountered issue:** https://streamable.com/3pl3i

**osu!lazer version:**  dfc903f

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/2754755/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2754757/runtime.log)
[network.log](https://github.com/ppy/osu/files/2754758/network.log)

**Computer Specifications:** i3 6100, 8GB ram, Windows 10 x64 1809

**Comment by peppy** [comment]
Possibly related to #3050 (screen level escape handling).
