### ISSUE TITLE
black screen on start, only sound

### ISSUE THREAD

**Issue by HipHopCat** [ppy/osu#4067]
**Describe your problem:** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:** 

**Computer Specifications:**

**Comment by smoogipoo** [comment]
Does it fix itself when you resize the window by any chance?

**Comment by smoogipoo** [comment]
Duplicate of https://github.com/ppy/osu/issues/4068, closing this one.
