### ISSUE TITLE
Slider glitches after placing one

### ISSUE THREAD

**Issue by s0m3guy2004** [ppy/osu#4070]
**Describe your problem:** When i place a slider and try to edit the anchors the slider glitches and slidertick doesn't move.

**Screenshots or videos showing encountered issue:** https://streamable.com/0nfgo

**osu!lazer version:** 2019.111.0

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/2763224/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2763225/runtime.log)

**Comment by yusdacra** [comment]
I think the issue is resolved, i don't get the behavior from the video. It works perfectly now.
