### ISSUE TITLE
"Floating Partciles" Proposal

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#4073]
**Describe the feature:** My idea is about to adding to visual effects "floating partciles".

**Proposal designs of the feature:** I got inspired by playing this [beatmap](https://osu.ppy.sh/beatmapsets/662120#osu/1401608) with storyboard **on**.
Here is preview:  https://youtu.be/hrJEdFXjEhY
And screenshots: 
![ex](https://user-images.githubusercontent.com/37531387/51283945-0ea13b80-19ea-11e9-994a-c7ba67de06bb.png)
![osu_2019-01-16_23-43-44](https://user-images.githubusercontent.com/37531387/51283515-bae22280-19e8-11e9-9c52-8848dc2f9537.png)
![osu_2019-01-16_23-44-01](https://user-images.githubusercontent.com/37531387/51283516-bae22280-19e8-11e9-85b6-e3e54ff27257.png)

**Comment by jorolf** [comment]
I don't think this belongs into the visual settings. Not a lot of people are going to use it because it's distracting. However this could be added as a skinning/scoreboard feature

**Comment by peppy** [comment]
These kind of visualisations will be possible at a skin level. I don't believe we will be adding them at a game level, though. If anything, we will make a tasteful "combo fire" return, but it will not cover the gameplay area.

Keep a watch when we flesh out the skinning system!
