### ISSUE TITLE
cannot login when making a new account

### ISSUE THREAD

**Issue by james-munson** [ppy/osu#4076]
cannot login when making a new account, 
installed the game on linux using this https://github.com/Alexmitter/osu-lazer-linux-installer
make a osu account and when it ask me to login, i cannot login on this build of the game.

**Comment by james-munson** [comment]
making an account, account name is seogod

**Comment by peppy** [comment]
I cannot find this account. You need to show us how you are making the account and provide runtime and network log files.

**Comment by james-munson** [comment]
having a issue with getting in game now, turned on raw input and now my mouse is all over the place.
deleted the game folder but seems like the setting stuck?

**Comment by james-munson** [comment]
just made a new account for this test, account name : hellofbi



`1/18/19 11:41:58 PM: ----------------------------------------------------------
1/18/19 11:41:58 PM: Network Log for formatme (LogLevel: Debug)
1/18/19 11:41:58 PM: osu 0.0.0.0
1/18/19 11:41:58 PM: Running on Unix 4.19.0.15, 4 cores
1/18/19 11:41:58 PM: ----------------------------------------------------------
1/18/19 11:41:58 PM: We just went Connecting!
1/18/19 11:41:58 PM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Unauthorized.
1/18/19 11:41:58 PM: Response was: {"error":"invalid_credentials","message":"The user credentials were incorrect."}
1/18/19 11:41:58 PM: Processing response from https://osu.ppy.sh/oauth/token failed with System.ArgumentNullException: Value cannot be null.
1/18/19 11:41:58 PM: Parameter name: value
1/18/19 11:41:58 PM: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 818
1/18/19 11:41:58 PM: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 786
1/18/19 11:41:58 PM: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse() in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\JsonWebRequest.cs:line 21
1/18/19 11:41:58 PM: at osu.Framework.IO.Network.WebRequest.Complete(Exception e) in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\WebRequest.cs:line 479.
1/18/19 11:41:58 PM: Login failed!
1/18/19 11:41:58 PM: We just went Offline!
1/18/19 11:43:51 PM: We just went Connecting!
1/18/19 11:43:51 PM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Unauthorized.
1/18/19 11:43:51 PM: Response was: {"error":"invalid_credentials","message":"The user credentials were incorrect."}
1/18/19 11:43:51 PM: Processing response from https://osu.ppy.sh/oauth/token failed with System.ArgumentNullException: Value cannot be null.
1/18/19 11:43:51 PM: Parameter name: value
1/18/19 11:43:51 PM: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 818
1/18/19 11:43:51 PM: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 786
1/18/19 11:43:51 PM: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse() in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\JsonWebRequest.cs:line 21
1/18/19 11:43:51 PM: at osu.Framework.IO.Network.WebRequest.Complete(Exception e) in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\WebRequest.cs:line 479.
1/18/19 11:43:51 PM: Login failed!
1/18/19 11:43:51 PM: We just went Offline!`

It's saying invalid_credentials but im 100 percent the password im using works

**Comment by james-munson** [comment]
![image](https://user-images.githubusercontent.com/38226001/51418401-2c7cb680-1b38-11e9-8fc5-3551dcdc7ebb.png)

Making an account with the normal osu site.
https://osu.ppy.sh/p/register

**Comment by james-munson** [comment]
i see there is a way to signup in the client, didn't try that.
trying it now but the client thinks i'm logged or something?

![image](https://user-images.githubusercontent.com/38226001/51418528-c93f5400-1b38-11e9-9b0a-262a87de4c1a.png)

**Comment by peppy** [comment]
Click the second button.

The old site registration process wil definitely not work.
