### ISSUE TITLE
Star difficulty display setting is not implemented. 

### ISSUE THREAD

**Issue by serenityP** [ppy/osu#4084]
Star difficulty display setting is not implemented. There is no change after setting display range for many times with different numbers.
**Describe the feature:** 
I hope that this feature can be available soon. ( Fixing in the next update is much more better ! )
In fact, that is not very convenient for players who play maps randomly(it consumes stamina to select a map).
Can it accurate to two decimal places like stable ? Thank you !
**Designs:** 
UI is pretty : )

**Comment by Aergwyn** [comment]
Potential duplicate to #2536?

**Comment by peppy** [comment]
Closing as duplicate.
