### ISSUE TITLE
User login/oauth failures provide no feedback

### ISSUE THREAD

**Issue by GSculerlor** [ppy/osu#4086]
**Describe the feature:** Basically right now, no feedback or any indicator why user can't login in-game (like wrong password, can't connect to server, etc)

**Proposal designs of the feature:** Adding a notification or maybe pop-up, or the simplest one is an message on login box that indicate why user can't login. Using popup dialog like when user went to registration is quite too much tho

**Comment by yusdacra** [comment]
Something like [this](https://streamable.com/nhkmz) maybe? I could try adding this, seems easy enough. But i have yet to understand most of the codebase so it will take time for me to do it.

**Comment by GSculerlor** [comment]
Maybe like that one, but not sure pushing notification panel when login window is active is correct behavior

**Comment by ticotaco72** [comment]
@arfylte should say what is correct.
