### ISSUE TITLE
Move beatmap skins button to general settings.

### ISSUE THREAD

**Issue by nwabear** [ppy/osu#4088]
**I believe that having the "beatmap skins" button in a different area than in the original osu! causes confusion, and that the button should be moved to the general settings.**

**![screen shot 2019-01-17 at 2 05 26 pm](https://user-images.githubusercontent.com/35433620/51345587-07694480-1a61-11e9-8b5a-9fdf7bb03d8f.png)**

**Comment by Gabixel** [comment]
Maybe a better idea could be having that option in both section: the first one in "skin" settings and the other one before gameplay, like for the "Disable mouse buttons" toggle
