### ISSUE TITLE
Not losing health on map

### ISSUE THREAD

**Issue by nwabear** [ppy/osu#4090]
**On Der Wald: Maze, the health bar never goes down. The drain of the map is 0, but health should still go down regardless**

https://youtu.be/97WEW47oYwc

**osu!lazer version: 2019.117.0**

**Logs:
[runtime.log](https://github.com/ppy/osu/files/2771080/runtime.log)
[performance.log](https://github.com/ppy/osu/files/2771081/performance.log)
[network.log](https://github.com/ppy/osu/files/2771082/network.log)
[debug.log](https://github.com/ppy/osu/files/2771083/debug.log)
[database.log](https://github.com/ppy/osu/files/2771084/database.log)**

**Comment by peppy** [comment]
HP drain has not yet been realised, so this applied to all maps (not just drain 0 maps)

**Comment by smoogipoo** [comment]
This is due to objects becoming !IsAlive before getting judged. Pretty major issue, adding to january milestone.

**Comment by smoogipoo** [comment]
Why are you closing this issue? o_O
