### ISSUE TITLE
reproduceable crash (anywhere)

### ISSUE THREAD

**Issue by chrisny286** [ppy/osu#4100]
**Describe your problem:** steps to reproduce the crash
1. Startup the game 
2. hit the keyboard shortcut to bring up the settings menu (ctrl+o)
3. left click anywhere to close the settings menu => Crash

**Screenshots or videos showing encountered issue:** https://puu.sh/CzCFi/92165d2d18.mp4

**osu!lazer version:** latest commit 161d0f0

**Logs:** 
[visual studio crash details](https://puu.sh/CzCPa/e495c001bc.txt)
[network.log](https://puu.sh/CzCSu/ee64500b45.log)
[performance.log](https://puu.sh/CzCTQ/5615d76bcf.log)
[runtime.log](https://puu.sh/CzCUl/fda932203a.log)

**Computer Specifications:** 
[systeminfo.txt](https://puu.sh/CzCZ4/27cb50a9d7.txt)

**Comment by ekrctb** [comment]
This is the same issue as #4098.
