### ISSUE TITLE
Expose game state via API for external consumption (lighting etc.)

### ISSUE THREAD

**Issue by CeH9** [ppy/osu#4113]
Hi, does osu provides something like Valve's [Game State Integration](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration) for CS:GO? If it doesn't consider this issue as **feature request** ^_^

Accordingly to doc from mentioned link:

> There are many ways for third parties to integrate their services with the game: activate stage lighting and pyrotechnics during a competitive match, activate lighting or haptic elements in peripherals connected to the player's PC during the game, complement streaming overlay with custom interactive graphics synchronized with game state, collect all game state changes to annotate recorded VODs, etc.

**Comment by peppy** [comment]
Yes, this is planned.

**Comment by nevespt** [comment]
any ETA for the feature?

Its could be awesome to have rgb effects on the game based on the color hits and misses

**Comment by peppy** [comment]
It's a backlog issue. If someone wishes to work on it, we can give design and support with it, but it's not a core focus until the rest of the game is complete for the main team.

**Comment by ticotaco72** [comment]
idk if this belongs here, but multimedia integration could be a thing, like start stop music button on app minimised in system belt

**Comment by peppy** [comment]
This API would be read-only and not cover such a scenario. Also we would likely not implement such a feature as osu! is a game, not a media player.

**Comment by avinashraja98** [comment]
I am looking to figure this issue out. Would really like the chroma integration. Going to dig around the code base but any design help is appreciated. I have previous experience with chroma.

**Comment by avinashraja98** [comment]
One question would be which is more preferred, a game state publish via an API or just use a simple C# Chroma library implementation.

**Comment by peppy** [comment]
The state publishing would be the overall goal, but adding local chroma support could directly feed off that api without requiring an external app. A starting point would be to make a component that exposes the state class and then consume that using an available chroma library via nuget.

**Comment by avinashraja98** [comment]
Makes sense. Going to try that. Thanks.
