### ISSUE TITLE
Editor: When moving Objects followpoints dont update() to connect the new positions

### ISSUE THREAD

**Issue by chrisny286** [ppy/osu#4126]
**Describe your problem:** When moving hitobjects the followpoints remain at their old positions and dont update for the new positioning.

**Screenshots or videos showing encountered issue:** [video](https://puu.sh/CAN3X/e2e6565942.mp4)

**osu!lazer version:** 2019.122.1

**Comment by peppy** [comment]
Closing in favour of #6681.
