### ISSUE TITLE
FPS Display doesn't scale when UI scale is changed

### ISSUE THREAD

**Issue by nathanielcwm** [ppy/osu#4141]
When you change the ui scaling and enable the fps display the fps display doesn't seem to scale along with the ui.

**osu!lazer version:** 2019.122.0 (iOS)

**Comment by peppy** [comment]
The FPS display is current the framework level one. Framework-level UI is not scaled with screen/UI. We need to implement a local osu! one at some point.

**Comment by nathanielcwm** [comment]
Damn that was a fast response

**Comment by nathanielcwm** [comment]
1.1x
![image](https://user-images.githubusercontent.com/22572406/51675955-298a3600-2010-11e9-9bdf-c499cd29d451.png)
0.8x
![image](https://user-images.githubusercontent.com/22572406/51676098-96053500-2010-11e9-87c3-53498d85170b.png)

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/19250.
