### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by nathanielcwm** [ppy/osu#4143]
**Describe your problem:** When playing the Tewi Maze difficulty of https://osu.ppy.sh/beatmapsets/90935/#fruits/265177 osu! on iOS crashes

*Auto was used*

**Screenshots or videos showing encountered issue:** Coming in a bit

**osu!lazer version:** 2019.122.0 (iOS)

**Logs:** 
[osu.iOS.wakeups_resource-2019-01-24-203430.ips.txt](https://github.com/ppy/osu/files/2791688/osu.iOS.wakeups_resource-2019-01-24-203430.ips.txt)
[osu.iOS-2019-01-24-203504.ips.beta.txt](https://github.com/ppy/osu/files/2791689/osu.iOS-2019-01-24-203504.ips.beta.txt)

**Computer Specifications:** iPad Pro 9.7 (Wifi), iOS 12.0.1

**Comment by nathanielcwm** [comment]
It also incidentally crashes always at the same point in the beatmap

**Comment by nathanielcwm** [comment]
Logs edited

**Comment by peppy** [comment]
Works correctly on desktop. For the time being we're not accepting iOS specific bug reports like this (safe to say it's likely memory related).

**Comment by nathanielcwm** [comment]
since ios bug reports are now accepted could this be reopened?
still occurs on 2019.214.0 ios 12.1.1
also it doesn't occur when auto is not in use
