### ISSUE TITLE
Mod selection screen & Mod setup

### ISSUE THREAD

**Issue by peppy** [ppy/osu#415]
Will be completed by #385 

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=42592133)](https://www.bountysource.com/issues/42592133-mod-selection-screen-mod-setup?utm_source=42592133&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Tom94** [comment]
This is completed, but I am hestitant to close because of the bounty.

**Comment by peppy** [comment]
you can still close issues with bounty, it'll still be open for @DrabWeb to claim if he wants.
