### ISSUE TITLE
Key counters ordered incorrectly

### ISSUE THREAD

**Issue by Llaurence** [ppy/osu#4159]
The positions of the keys in the counter don't match those on the stage.

For example, here every key is pressed except the middle one:

![osu_2019-01-26_15-11-03](https://user-images.githubusercontent.com/40535137/51788317-f0bb9f80-217c-11e9-91eb-0a183d41500c.jpg)

Other example (3 leftmost keys are pressed):

![osu_2019-01-26_15-15-02](https://user-images.githubusercontent.com/40535137/51788341-3c6e4900-217d-11e9-8e7d-caddba80ee42.jpg)

**osu!lazer version:** 2019.126.0

**Comment by DJKero** [comment]
I'm checking this, what I THINK it's happening is that it has to do with the way the keys are arranged in the ruleset.

What I don't get is why they start from the Button 11, I'll try to check if this is what is happening and edit this.
