### ISSUE TITLE
Switching between a few songs in songselect menu makes the next play on a mania map lag

### ISSUE THREAD

**Issue by ghost** [ppy/osu#4160]
> Import Jaron sonder https://osu.ppy.sh/beatmapsets/710995#mania/1503100
> Restart the game
> Go the the song select menu
> Click on half a dozen songs, one at a time just to let the music start playing
> Play on jaron sonder

Expected: the scrolling is fluid (except when there's sv)

Actual: lots of small freezes

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2019.126.0 windows x64

**Logs:**

performance-gamethread.update.log has a lot of stack traces.

[network.log](https://github.com/ppy/osu/files/2799094/network.log)
[performance.log](https://github.com/ppy/osu/files/2799095/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2799096/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2799097/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2799098/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2799099/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2799100/runtime.log)

**Comment by Llaurence** [comment]
Can reproduce on another machine with a linux build (commit 718136a89) except performance-gamethread.update.log doesn't have stack traces.

[database.log](https://github.com/ppy/osu/files/2799251/database.log)
[network.log](https://github.com/ppy/osu/files/2799252/network.log)
[performance.log](https://github.com/ppy/osu/files/2799253/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2799254/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2799255/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2799256/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2799257/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2799258/runtime.log)

**Comment by peppy** [comment]
Does it eventually recover?

**Comment by Llaurence** [comment]
The whole play is laggy and is laggier the more notes is on the screen, but the next ones aren't.

**Comment by peppy** [comment]
So it does eventually recover, yes?

**Comment by Llaurence** [comment]
It recovers if and only if:   i restart the game.

**Comment by Llaurence** [comment]
On https://osu.ppy.sh/beatmapsets/376293#mania/823842 I've ran into the same problem.
This time all is needed is to run autoplay on the map (no need to switch between songs), and the update loop drops below 150hz.
The performance decreases during the replay, reaching 10hz at the end.
It also decreases during dense sections of the map.

![screenshot-20190206002037](https://user-images.githubusercontent.com/40535137/52311362-9f8e8580-299e-11e9-9274-6db553680911.png)
![screenshot-20190206002122](https://user-images.githubusercontent.com/40535137/52311363-a0271c00-299e-11e9-9266-0663f8b69d0c.png)
![screenshot-20190206002242](https://user-images.githubusercontent.com/40535137/52311364-a0271c00-299e-11e9-8124-4af4d83e71c7.png)
![screenshot-20190206002355](https://user-images.githubusercontent.com/40535137/52311365-a0271c00-299e-11e9-9b5e-a35d17861c1f.png)
![screenshot-20190206002409](https://user-images.githubusercontent.com/40535137/52311366-a0271c00-299e-11e9-9d69-0e7ed61987ea.png)
![screenshot-20190206002539](https://user-images.githubusercontent.com/40535137/52311368-a0bfb280-299e-11e9-889d-121149f2ac17.png)
![screenshot-20190206002553](https://user-images.githubusercontent.com/40535137/52311371-a0bfb280-299e-11e9-8149-5fe33e42c534.png)
![screenshot-20190206002623](https://user-images.githubusercontent.com/40535137/52311372-a0bfb280-299e-11e9-999e-dbd4c2ce579f.png)


[database.log](https://github.com/ppy/osu/files/2834271/database.log)
[network.log](https://github.com/ppy/osu/files/2834272/network.log)
[performance.log](https://github.com/ppy/osu/files/2834273/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2834274/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2834275/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2834276/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2834277/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2834278/runtime.log)

**Comment by Llaurence** [comment]
Reproduced on windows.

Setting the frame-rate to "v-sync" makes the performance really worse, compared to the other settings.

**Comment by Llaurence** [comment]
Here's a video of the autoplay on PLANET//SHAPER with the full performance overlay: https://streamable.com/k3gqn

You can see the "Invalidations" and "Refreshes" gradually increase from 1k to 5k with peaks above 100k (at 4:45). The same thing happens to "CheckChildrenLife".

**Comment by Joehuu** [comment]
Closing for these reasons:
- the author of this issue deleted their account and cannot confirm improvements
- stale
- this was a performance issue (with memory?) and likely resolved in https://github.com/ppy/osu/pull/10494
