### ISSUE TITLE
RankChartLineGraph gets clipped at the bottom

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ppy/osu#4163]
**Describe your problem:** The rank history chart in the user profile overlay gets clipped at the very bottom.

**Screenshots or videos showing encountered issue:** 
![clipped rank chart](https://user-images.githubusercontent.com/13605369/51790220-0d120900-218a-11e9-9f34-88e8b6918aa9.png)
![clipped rank chart](https://user-images.githubusercontent.com/13605369/51790264-945f7c80-218a-11e9-8769-b7d208e241a9.png)

**osu!lazer version:** 2019.126.0 (commit 718136a8928db9f1a3cd9122f33d6bb650820c90)

**Logs:** N/A

I tried fixing this myself but didn't immediately find the cause, since simply offsetting all vertex positions in the graph doesn't change the visible result, and all values are within the expected bounds. Perhaps framework-level?

**Comment by Morodar** [comment]
In my case, it looks even worse
![image](https://user-images.githubusercontent.com/10113399/52978347-29901280-33d1-11e9-9863-dedc525bf4a9.png)
