### ISSUE TITLE
Add live placement mode in the osu!mania editor

### ISSUE THREAD

**Issue by tekn0killerbong** [ppy/osu#4164]
I've made a few beatmaps on mania editor and I've found it really often discouraging to keep on making them because the editor is not as efficient as it could be. I find clicking one note at a time with the mouse is very long and live mapping hardly usable when u ur not making easy beatmaps. This is why I suggest a step recording mode as we find it in DAWs and music workstation. Here's a video to help you get the idea : https://www.bing.com/videos/search?q=step+recording+music+production&view=detail&mid=C45B87DB2390F4853859C45B87DB2390F4853859&FORM=VIRE

This editing mode would allow you to map notes one STEP at a time by PRESSING and RELEASING keys, regardless of the tempo of the song. First, you'd find yourself at the current step, a time location in the song let's say the beginning of the tenth bar. Then, not necessarily synchronistically, you'd press the keys you want to put at this time location or step. Only then you would release the keys you decided to put there. At that moment, when every key is released, the notes you chose would be inserted at the step you were, AND you'd be automatically sent to the next step OF WHICH the value would have been defined initially by the grid value (1/1, 1/2, 1/3, 1/4, 1/8, 1/12 or 1/16). So, if the assigned value was 1/4, you'd be at the second beat of the tenth bar after you released all the keys you pressed. If the value was 1/1, a whole bar, you'd be at the first beat of the eleventh bar of the song. And so, ready to restart the process. Much quicker with the fingers instead of the cursor right ?

And what if you don't want to insert any note on the next step ? Simply, a "rest" command would make you skip a step or more. I suggest a customizable key, by default 'B' cause it's usable by the thumbs even in 9k.

And what if you want to insert a LN ? A command would change the length of the note you are pressing with same value of the step. I suggest the same customizable key again, 'B' by default because its function is of the same nature as the "rest" command which is advancing in steps.

What about multiple long notes ? The same command would change the length of every note you're pressing at the same time. If there's shorter notes, just release them and continue with the longer ones. Since you'd have to release ALL the keys before going to the next step, you'll be able to continue lengthening the other notes until you released every one of them. What would be really convenient is that the screen follows the end of the long notes during the lengthening and return to the next step after releasing them.

Of course, this could only work with on-grid notes. If you want some groove you'll have to edit them with the cursor and unsnap them. Unless we find a way to unsnap them while pressing keys but I'm out of inspiration let's discuss !

So yeah there it is, the step recording mode idea. Like live mapping mode, it'd have to be a separate editing mode from the selective mode (the default mode where you place every note one by one with the cursor) that you toggle to be able to use it because of the swapping, inversing keys that some are normally used to play.

This would be a mode that would allow beatmappers to enter way more easily a WORKFLOW that is so hard to reach currently. I honestly find it a pain in the assigned to make a beatmap, but I still so much want to map songs that I love. We'd be less tempted to try to find a more rapid way to finish to map. We'll have more focus to spend on creating original or idk patterns that we "identify with" just patterns we can kind of get the feel of while we're making it.

So yeah I hope this starts the process to get 
to build this together and to enter a new era of mania beatmapping !!

**Comment by peppy** [comment]
Definitely planned in some fashion.

**Comment by peppy** [comment]
Let's group this under https://github.com/ppy/osu/issues/6608
