### ISSUE TITLE
Background Dim persists from PlayerLoader to PlaySongSelect

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu#4165]
**Describe your problem:** Background persists when hovering over Visual Settings in loading then going back to Song Select.

**Screenshots or videos showing encountered issue:**
![image](https://user-images.githubusercontent.com/20495991/51796528-34bbac80-2230-11e9-9d9e-1c24b75b87df.png)
![image](https://user-images.githubusercontent.com/20495991/51796531-38e7ca00-2230-11e9-9259-eb6ef9795ed2.png)

**osu!lazer version:** 2019.126.0

**Logs:** 
[performance-framework.draw.thread.log](https://github.com/ppy/osu/files/2799774/performance-framework.draw.thread.log)
[runtime.log](https://github.com/ppy/osu/files/2799775/runtime.log)
[debug.log](https://github.com/ppy/osu/files/2799776/debug.log)
[performance-draw.log](https://github.com/ppy/osu/files/2799777/performance-draw.log)

**Comment by peppy** [comment]
Likely regression from #4131.
