### ISSUE TITLE
MusicXML support (proposal)

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#4167]
**Describe the feature:**  It would be nice, if beatmap could be created on top of musicXML file. If mp3 wasn't provided for the file, music could be generated too.
https://www.musicxml.com/

**Comment by HoLLy-HaCKeR** [comment]
Would be similar to converting midi file to a beatmap, although that has less information stored in it.

**Comment by peppy** [comment]
I don't foresee this being implemented unless the person who wants it implements themselves. Not against that happening, but no reason to keep this issue open.
