### ISSUE TITLE
Replace with "rewind" the "random" button text while holding shift

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4174]
**Describe the feature:** I was considering the idea of making the text of the “random” button more dynamic: because of its very cool rewind function using the `shift` key, I suggest to change its text to “rewind” (or something like that) when holding `shift`, and turn it back to “random” when `shift` is released. This can be useful for new players or, in general, for anyone that didn't noticed this function (and it can be visually nice) because so far it has always been very hidden as a function, so only a few people use it.
Also, if you're considering adding a sort of "hint box" (like on stable) on the main menu, maybe you can add this thing to the list.

**Comment by phosphene47** [comment]
I think instead of pressing shift, long-pressing the random button would be better for mobile.

**Comment by ToIGLAK** [comment]
I was thinking about adding "rewind" button that lifts from under the "random" button after using it. It'd stay visible for 2-3 seconds after which it'd slide back under the "random" button. I guess it'll be more intuitive for many users.

**Comment by peppy** [comment]
May be better to poke @arflyte for this one, to fix the usability-without-keyboard issue at the same time.

**Comment by arflyte** [comment]
Doesn't sound intuitive. I had no idea what is "rewind" in the first place. I'll figure out a better way to solve this.

**Comment by Joehuu** [comment]
Better implementation of rewind design not established yet.
