### ISSUE TITLE
Play only part or section of the map

### ISSUE THREAD

**Issue by GSculerlor** [ppy/osu#4175]
**Describe the feature:** Sometimes players want to try to play only part of the map (where they fail or where the hard pattern appears) and not full of the map. At this point at stable, a lot of players can only create a new diff on the map that only contains a part that they want to play to do that.

**Proposal designs of the feature:** Add feature maybe like training mod or something like that, specify the start and end point/time on the map that player wants to try so players can play that specific part without creating new difficulty

**Comment by ticotaco72** [comment]
It something like Autoplay but you can in any moment change it to normal gameplay

**Comment by c0linw** [comment]
I think it would be nice to have it implemented as a separate part of the game instead of as a mod. An ability to "scroll" through the beatmap in real time a la McOsu would be nice in a "Practice" mode alongside "Play" and "Edit" out of the main menu.

**Comment by Aergwyn** [comment]
Isn't Target Practice an unimplemented mod for exactly that or am I remembering wrong?

**Comment by LeNitrous** [comment]
Target Practice is where random targets appear in triangles. Not the one they're looking for.
