### ISSUE TITLE
Charts ranking button takes you to a wrong link

### ISSUE THREAD

**Issue by ShinKeyKai** [ppy/osu#4176]
_I don't know if I can report bugs for osu!stable here. Sorry if this is only for lazer._

When you click on the charts ranking button after a play. It takes you to a not found page.
![charts ranking button](https://user-images.githubusercontent.com/47122537/51865879-55662e00-2326-11e9-9994-8ec8310b90da.JPG)
[This is the wrong link](https://osu.ppy.sh/rankings/fruits/charts?spotlight=SEASONAL2)

**Comment by ticotaco72** [comment]
Sorry it's Lazer only. Go the support forums at osu.ppy.sh

**Comment by ShinKeyKai** [comment]
Ok, sorry. The help forum, right?

**Comment by ticotaco72** [comment]
Yes
