### ISSUE TITLE
Multiplayer rating system / matchmaking

### ISSUE THREAD

**Issue by Epicm14** [ppy/osu#4178]
To anyone familiar with Mario Kart Wifi ratings or chess ratings. This concept is similar to that.
**Gameplay**

- Players start out with a certain rating say 1,500.
       -gain rating when you beat higher rated players.
       -lose rating when lower rated players beat you.
       -When beating lower rated players, you don’t gain very many points.
       -When everyone fails a map, nothing is awarded?

- No maximum rating. Top players will hit a wall eventually.
- Rating only affected by ranked/loved maps.
- Separate rating for star category.

 

**Multi**

- Show multi rating on your profile in game after choosing multi in the main menu.
- Not necessary to show PP rank in multi lobbies, just rating, and possibly rank in the multi rating category. 
- Everyone can only play in rooms that they are capable of passing maps.

 
          -Ex. If a player doesn’t have the 6★ pass medal, they are ineligible to play in 6★ rooms, and can unlock that once they earn the medal.

![image](https://user-images.githubusercontent.com/38800690/51873296-a415c700-232a-11e9-8a0f-87f83651b974.png)
![image](https://user-images.githubusercontent.com/38800690/51873312-b4c63d00-232a-11e9-8745-01e64d3806ef.png)

- Option in multi to declare which ★ the room will be

![image](https://user-images.githubusercontent.com/38800690/51873349-cdceee00-232a-11e9-8915-075b716d3e5f.png)
![image](https://user-images.githubusercontent.com/38800690/51873360-d6272900-232a-11e9-8606-7fe4c7eefb8f.png)

- ★ of room shown in room title when choosing category.
- This means there can be a drop-down option to filter multi rooms by ★.
- Once category is chosen, only maps in that category can be chosen unless the category  
 is changed.
- Players ratings are shown with the category when its chosen.

**Leaderboard**

- I’m envisioning something like on https://lichess.org/player where it shows the highest rated players in a certain category (modes and star for osu).
- This as a leaderboard would be very dynamic and would encourage lots of competition.

**Website**

- Separate leaderboards for multi.
- Show top 100 for each? 1000 sounds like a bit much.

![image](https://user-images.githubusercontent.com/38800690/51873444-31591b80-232b-11e9-848d-c244696d8408.png)
![image](https://user-images.githubusercontent.com/38800690/51873448-36b66600-232b-11e9-87c0-a5969d7ce570.png)
-I don't know how it would be best displayed on your profile, I'm seeing under country ranking with a drop-down menu for star category.
![image](https://user-images.githubusercontent.com/38800690/51873461-42a22800-232b-11e9-8555-20d8e57988ad.png)

**Pros**

- Increase competition in multis by a large margin.
- Give a more accurate skill representation than pp.
- Caters to every skill level so that everyone can compete.
- Shifts attention from PP.

          -Make it easier to stay in the same star range.
          -So that there aren’t clickbait room titles all the time.

 **Cons**

- Shift focus from PP if you consider that a downside.
- Too many ratings to keep track of?
- That rank bug in multi where it displays the wrong rank for the mode you're in, I assume there would be a lot of.

**Calculation**

- I really like the Glicko 2 system used in chess ratings.
- Say the calculation occurs with every win/loss against one person. If this is applied individually for each win/loss depending on # of players after playing one map in a multi, this should work.
- Use initial rating and add up each change in rating for a total change after the one map played.
- This link gives a good example of the calculation.
http://www.glicko.net/glicko/glicko2.pdf

**Comment by peppy** [comment]
It is intended to have an ELO or otherwise ranking system in multiplayer, eventually. Still a bit far away but will leave this issue open as there's no similar one created yet.
