### ISSUE TITLE
Main menu background cuts off at top edge

### ISSUE THREAD

**Issue by ProgrammaticNajel** [ppy/osu#4197]
Due to parallax effect, the background gets cut off at the very top, and black background is shown instead. This only happens when the top bar (with the game mode selections, music controller and whatnot) is shown.

Screenshots:
![dotnet_2019-02-02_16-39-04](https://user-images.githubusercontent.com/17925396/52162102-d730cf80-2709-11e9-99bf-c4056c7ff35d.png)
![dotnet_2019-02-02_16-39-15](https://user-images.githubusercontent.com/17925396/52162103-db5ced00-2709-11e9-90be-ed4a3cea8323.jpg)
![dotnet_2019-02-02_16-39-28](https://user-images.githubusercontent.com/17925396/52162107-de57dd80-2709-11e9-8425-86ab8fe066b7.jpg)

**Comment by peppy** [comment]
Looks like a regression in the application of parallax container's scale.
