### ISSUE TITLE
osu!lazer doesn't run

### ISSUE THREAD

**Issue by Trojan7z7VZX** [ppy/osu#4200]
**Describe your problem:** 
When I try to start osu!lazer it doesn't run and crashes immediately and I get this: ``` Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	osu!.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5c0ab1b7
  Fault Module Name:	coreclr.dll
  Fault Module Version:	4.6.27207.3
  Fault Module Timestamp:	5c0a9582
  Exception Code:	c0000005
  Exception Offset:	00000000001bd149
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	4105
  Additional Information 1:	f425
  Additional Information 2:	f425748a82fa3ff1bfb6279a2851b08f
  Additional Information 3:	3474
  Additional Information 4:	3474b12e43100f224807cc6760b7731f ```
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/31652809/52170033-cbb1c880-274a-11e9-94ee-a93eaab0a205.png)

**osu!lazer version:** 
2019.131.0
**Logs:** 
"logs" folder is not present in my osu!lazer directory
**Computer Specifications:** 
Windows 7 Home Premium SP1 x64
4GB RAM (3.75GB useable)
Processor: Pentium Dual-Core CPU   E5700 @ 3.00GHz

**Comment by peppy** [comment]
This may be relevant to you: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x
