### ISSUE TITLE
Notifications button hitbox not clickable on right upper corner pixels when notifications closed

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#4216]
**Describe your problem:** 
When trying to click on the notifications button from the right upper corner of the screen it exceeds the button hitbox and is not clickable. Does not occur when notifications are opened.
Does happen to the back button too on the left down corner and to the chart info button on the right down corner (makes a strange sound when hovering on the left side of the corner).
https://streamable.com/wk4vl

**Screenshots or videos showing encountered issue:** 
Cursor on the button
![osu_2019-02-06_14-41-34](https://user-images.githubusercontent.com/13122796/52345552-ce980c00-2a1d-11e9-9560-a5a2d2e0a75e.png)
Cursor on the uppor right corner (not visible)
![osu_2019-02-06_14-41-58](https://user-images.githubusercontent.com/13122796/52345551-ce980c00-2a1d-11e9-9177-d3fe74849ed7.png)
Cursor on the uppor right corner (not visible & notifications open)
![osu_2019-02-06_14-41-43](https://user-images.githubusercontent.com/13122796/52345553-ce980c00-2a1d-11e9-9b14-37b55098b699.png)

**osu!lazer version:** 
2019.131.0

**Comment by Joehuu** [comment]
Did you have raw input on?

**Comment by oSumAtrIX** [comment]
I dont remember, I think I had it on but I had the mouse confined to fullscreen This issue does not happen anymore, probably because I have downgraded from windows 7 to windows 10 .

**Comment by Joehuu** [comment]
This is similar to https://github.com/ppy/osu/issues/18159, but closing this instead as that one has a repro comment.
