### ISSUE TITLE
Cookie hitbox uncentered

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#4217]
**Describe your problem:** 
The hitbox of the osu logo is smaller than it should be and is not centered to the osu logo (see pictures) 

**Screenshots or videos showing encountered issue:** 
Cursor shortly above logo hitbox
![osu_2019-02-06_14-50-23](https://user-images.githubusercontent.com/13122796/52345964-ca202300-2a1e-11e9-9f13-4d5584ffc213.png)
Cursor shortly below logo hitbox
![osu_2019-02-06_14-50-15](https://user-images.githubusercontent.com/13122796/52345965-ca202300-2a1e-11e9-88f7-72660be945bf.png)

**osu!lazer version:** 
2019.131.0

**Comment by yesseruser** [comment]
This also happens to the left and right, where the play/settings button is focused/clicked instead.
