### ISSUE TITLE
Game mode buttons background exceeds hitbox

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#4218]
**Describe your problem:** 
The background of the game mode buttons goes over the hitbox of those. This is not the case for the player info button for example

**Screenshots or videos showing encountered issue:** 
![osu_2019-02-06_15-03-45](https://user-images.githubusercontent.com/13122796/52346851-d6a57b00-2a20-11e9-873b-1c564dc880c6.png)

**osu!lazer version:** 
2019.131.0

**Comment by Joehuu** [comment]
Intended design?

**Comment by peppy** [comment]
I don't actually recall. Would have to see how it looks when changed (the side padding would probably need to be removed).

**Comment by Joehuu** [comment]
![](https://puu.sh/EC13F/695da862e6.png)

**Comment by peppy** [comment]
Can you PR the change? need to see it in motion.

**Comment by iiSaLMaN** [comment]
I think it'll look better with a small padding (`5` at most)
