### ISSUE TITLE
Sound overlapping when clicking on buttons

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#4219]
**Describe your problem:**
When clicking on a button which opens osu direct menu for example and clicking on another button which results in closing the opened menu their sounds overlap and make a strange mix of sound.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/wmoql

**osu!lazer version:** 
2019.131.0

**Comment by Joehuu** [comment]
Closing as sound effects have improved since.
