### ISSUE TITLE
External keyboard not supported in iOS client

### ISSUE THREAD

**Issue by xmcp** [ppy/osu#4225]
**Describe your problem:** When a physical keyboard is connected, I cannot type anything in iOS client (eg. the search bar in osu!direct or settings panel)

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/6646473/52428869-d3ec7800-2b3d-11e9-8587-1b8b55e75b3c.png)

(My device is iPad Pro 2018 and the keyboard is connected from the USB-C port. The keyboard works well in other apps, but I am not able to type anything in osu)

**osu!lazer version:** Latest TestFlight version (2019.131.1)

**Logs:** Not available

Btw it will be very nice if physical keyboard is supported in the gameplay.

**Comment by swoolcock** [comment]
Are you able to test with a Smart Keyboard?  I know for a fact they work, as that’s what I use for development.

I don’t see how the current implementation could work for one but not the other, but I’ll look for a USB-C keyboard myself to verify.

What brand/model keyboard is it?

**Comment by peppy** [comment]
smart keyboard also does not work

**Comment by MiraiSubject** [comment]
[Apple's Bluetooth keyboard](https://www.apple.com/shop/product/MLA22LL/A/magic-keyboard-us-english?fnode=56) and a generic USB keyboard in the Type-C port both work for me in-game typing in textfields, also the one shown in the screenshot. 


Using a 2018 iPad Pro as well. 
This is on 2019.131.1 (latest testflight as of writing)

**Comment by xmcp** [comment]
I am using [AmusingKeypad Pro](https://github.com/Antecer/AmusingKeypad) and maybe the bug is with that keyboard. Actually I have found some other problems with its key mapping on iOS.

(So this problem might be due to the keyboard layout?)

I don't have other (Bluetooth/USB/"Smart") keyboards to test right now, but I will provide more details when possible.

**Comment by xmcp** [comment]
I tried another keyboard (Apple's bluetooth keyboard) and it worked in textfields.
(Although it's still not possible to use it in the gameplay)
