### ISSUE TITLE
"Did you like this map?" prompt on completing beatmap

### ISSUE THREAD

**Issue by LevKatenin** [ppy/osu#4230]
At first I thought about user rating being too wide (10-star system), but that problem had already been brought up. Then I thought about why people might not rate a map: quickly closing a map after playing, deleting maps, etc. But often people visit their own page to see their progress.

What about a "Did you like this map?" question near every top play, and every recent play? That seemed the most logical to me. You could also suggest to rate random recent plays as pop-ups of some sort. I don't care whether the system will be 3-rating (like/neutral/dislike) or 2-rating, but the idea to _casually_ remind people to rate maps is very attractive to me.

The result should be more accurate, more player-oriented user rating, which is definetly better than the current system

**Comment by HoutarouOreki** [comment]
I too think it should not be an intrusive reminder, don't we all hate those things?

**Comment by LevKatenin** [comment]
> I too think it should not be an intrusive reminder, don't we all hate those things?
I completely agree. The idea I wanted to convey is that there are many ways to go about raising feedback level and quality, maybe even try something completely new, if possible.

Thanks for the feedback
