### ISSUE TITLE
Background dim is disabled when in gameplay

### ISSUE THREAD

**Issue by serenityP** [ppy/osu#4231]
**Describe your problem:** 
Background dim seldom is disabled randomly when in gameplay since the last update in my PC.
When I meet the BG with the main color of white and trigger this bug, I can not see notes clearly.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.131.0
**Logs:**

**Comment by HoLLy-HaCKeR** [comment]
Duplicate of #4204?

**Comment by nyquillerium** [comment]
Closing as a duplicate of https://github.com/ppy/osu/issues/4204
