### ISSUE TITLE
HP bar glitch in osu!mania

### ISSUE THREAD

**Issue by Gavator234** [ppy/osu#4233]
**Describe your problem:**
Simply the fact that the hp bar doesn't go down completely, yet I still fail a song. This happens most of the time when I fail, and it's getting kind of annoying. I think that osu! thought I pressed a note after the game over screen and added a little more to the bar. That's all I could tell. As you can probably tell by the picture, I was playing osu!mania in 4k mode. This song was about 4 1/2 stars.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/37884919/52525824-fa60ff00-2c74-11e9-8ed2-2f9016085b83.png)

**osu!lazer version:**
2019.131.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/2848223/database.log)
[network.log](https://github.com/ppy/osu/files/2848224/network.log)
[performance.log](https://github.com/ppy/osu/files/2848225/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2848226/runtime.log)

**Comment by peppy** [comment]
I believe this is just a matter of the transform not finishing playing out before the gameplay is paused by the exit screen. Will likely be resolved when we add a proper fail animation.

**Comment by Gavator234** [comment]
(Sorry for taking so long to respond) Thanks! I hope it will be fixed soon,
and I can't wait to see the new startup animation!

**Comment by Joehuu** [comment]
The fail animation has since been implemented and I don't think this happens anymore, so closing.
