### ISSUE TITLE
osu!lazer is not even opening

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#4235]
**Describe your problem:**
Ok, so I press the shortcut and NOTHING happens. This is the 3rd time I tried to install osu!lazer. The last two times, a black screen came for about 5 seconds instead of nothingness. Please help/fix!

**Screenshots or videos showing encountered issue:**
![hi](https://user-images.githubusercontent.com/32044067/52526517-ae6b8580-2c87-11e9-8b04-4819e7464807.gif)

**osu!lazer version:**
Version: 2019.131.0 (most recent)

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/2848288/runtime.log)
[performance.log](https://github.com/ppy/osu/files/2848289/performance.log)

**Comment by jorolf** [comment]
What GPU do you have? Have you tried updating the driver?

**Comment by AqilCont** [comment]
My graphics driver: Intel(R) Q45/Q43 Express Chipset
My drivers are up to date

**Comment by jorolf** [comment]
Seems like your chipset is too old for osu!lazer. Lazer requires OpenGL 3+ while your chipset only supports OpenGL 2.1

**Comment by AqilCont** [comment]
Oh... will this also affect me in the future when osu!lazer becomes osu? Or will I have to get a new graphics card?

**Comment by ringosham** [comment]
Well obviously.
Core 2 Duo is OLD. You really need to upgrade your pc.

**Comment by peppy** [comment]
We can't support opengl 2.0 in lazer, so the above advise is the best we can provide for now. Your hardware is almost 2 decades old.

**Comment by Leandro170-succ** [comment]
Peppy,you're going to make me cry.

while i respect your work in this game,i must warn you.
**_this is going to make a lot of players quit._**

**Comment by peppy** [comment]
No it is not, because

> More support may be added down the line via angle/directx, though.
