### ISSUE TITLE
Multiplayer chat input problem

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#4236]
Chat in the multi room can recieve input even when play screen has been pushed.
How to reproduce:
1. After clicking "Start" press some keys immediately.
2. Continue playing.
3. When you came back to the room screen you will see all the in-game-pressed keys in the chat.

**Comment by peppy** [comment]
Is this on latest master (post the new screen changes)?

**Comment by EVAST9919** [comment]
yeah, noticed it there
