### ISSUE TITLE
Approach Rate wrongly set

### ISSUE THREAD

**Issue by Yutsuten** [ppy/osu#4237]
**Describe your problem:** The music _agony - KOTOKO_ has AR 5 in osu!lazer, while in stable osu! and the [website](https://osu.ppy.sh/beatmapsets/13510#osu/49952), it has AR 8. Circle Size, HP Drain and Accuracy are correctly set.

Tried deleting it and downloading it again through osu!direct, but the problem remained (it was originally imported from stable). I can't play it with AR 5, too slow >_<

Haven't noticed this problem in any other beatmap, so this is really strange...

**Screenshots or videos showing encountered issue:** 
![Screenshot](https://i.imgur.com/Qge7kNZ.jpg)

**osu!lazer version:** It always updates automatically as I open it, so it is the newest version published as for today (2019-02-10).

**Comment by Poyo-SSB** [comment]
This appears to happen because the map's AR is not set, and lazer is failing to assume an AR from the OD as stable does for some reason.

**Comment by UselessToucan** [comment]
It is ok on 23435575175671c18c971fb5fefde3f6f3d314bb
![osu_2019-02-14_21-49-41](https://user-images.githubusercontent.com/22450664/52809992-9db17a00-30a2-11e9-9b02-cbf3c7e3e3ec.jpg)

**Comment by Yutsuten** [comment]
As I'm not able to reproduce this bug anymore, I'll close this issue.
