### ISSUE TITLE
Open osu! folder crashes iOS

### ISSUE THREAD

**Issue by jjjoshiii** [ppy/osu#4245]
Pressing the Open osu! folder button on iOS crashes the game instantly 
Heres a video of the issue. https://drive.google.com/file/d/14SiPt1rdFp2OYpNQnhGR9I6gzDeGjuiP/view?usp=sharing
Version is 0.0.0
Can't get logs on iOS.
I knew it would crash but if its literally a crash button why is it there?

**Comment by peppy** [comment]
Why indeed. Generally because (as the iOS testing notes say) iOS is not a focus and many things are broken.

**Comment by Joehuu** [comment]
Resolved by #4353.
