### ISSUE TITLE
Menu bar and dock automatically display in macOS fullscreen mode

### ISSUE THREAD

**Issue by TsukiPoi** [ppy/osu#4260]
**Describe your problem:** Menu bar and dock automatically pop up in macOS fullscreen mode, in response to mouse movements. It keeps capturing mouse in game.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/46295491/52847794-259d8f80-3148-11e9-9b7d-a14b313b2e78.png)

**osu!lazer version:** 2019.214.0

**Comment by peppy** [comment]
- Does this only happen with raw input enabled?
- What is that weird horizontal line in the middle of the screenshot? Irrelevant?

**Comment by TsukiPoi** [comment]
- The problem occurs when the raw input is enabled and disable.
- It's irrelevant, a divide of two screenshots.  

Menu bar (or dock) pop up when the mouse is on the top (or bottom) area of the screen.  
It's a problem of something like UIPresentationMode key in macOS.

**Comment by peppy** [comment]
Does it only happen when you hold the mouse there though? if so, this is expected behavior.

**Comment by TsukiPoi** [comment]
Yes, I see. Therefore it is expected behavior.
