### ISSUE TITLE
Proposal: Render Resolution in Options for iOS

### ISSUE THREAD

**Issue by CobaltMK1** [ppy/osu#4262]
**Describe the feature:** 
The frame rate usually drops below 60 FPS during some animations and sometimes during gameplay on iOS so a render resolution feature would help prevent this. The option should have a slider which moves in intervals of 0.1 from 0.5 to 1 with 1 being the native resolution and 0.5 being half the resolution of the screen.

**Comment by peppy** [comment]
We prefer to fix this with optimisations. Don't worry, we have some large ones incoming.
