### ISSUE TITLE
Proposal: Music playback integrated with Music in control centre

### ISSUE THREAD

**Issue by CobaltMK1** [ppy/osu#4263]
**Describe the feature:**
Currently, when osu! Is minimised on iOS music playback stops and it cannot be controlled from control centre.

**Proposal designs of the feature:**
![5625cdcb-e2d3-4d52-9f48-39974d6fc50c](https://user-images.githubusercontent.com/38002802/52852802-5cce6980-3165-11e9-9012-8e93381e5fdf.png)

**Comment by peppy** [comment]
osu! is a game, not a music player.
