### ISSUE TITLE
can't load beatmaps anymore

### ISSUE THREAD

**Issue by toovs** [ppy/osu#4269]
Just updated to latest version and osu-lazer can't play beatmaps anymore, when I load them in the song selection screen I get the errors shown below, and if I try and load a beatmap it just sits on the loading screen forever.

![2019-02-16-091600_1920x1080_scrot](https://user-images.githubusercontent.com/857940/52902865-cc773f80-31cb-11e9-88f7-e2333168a0e2.png)
[logs.zip](https://github.com/ppy/osu/files/2872201/logs.zip)

**Comment by peppy** [comment]
You are likely not correctly providing the library path. See https://github.com/ppy/osu#a-note-for-linux-users

**Comment by TeamSoldierNub2** [comment]
@peppy I am on iPhone. I think that requires jailbreaking it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toovs** [comment]
not really sure what to do with this. it was working fine, all I did was update to the latest version.

https://hastebin.com/raw/buxorosowi

**Comment by smoogipoo** [comment]
There is no project file there. You want to be using `dotnet osu\!.dll`.

**Comment by toovs** [comment]
I still don't understand what command I should be running. I don't know where the "build directory" is referred to in peppy's link. running `dotnet osu\!.dll` does start it up but I just get the same error.

**Comment by toovs** [comment]
I am still getting the same error with `LD_LIBRARY_PATH="src/osu/osu.Desktop/bin/Release/netcoreapp2.2" dotnet /usr/lib/osu-lazer/osu\!.dll`

**Comment by VPeruS** [comment]
If you copied all published files into /usr/lib/osu-lazer then LD_LIBRARY_PATH should also contain it.

**Comment by toovs** [comment]
same error using absolute path

**Comment by VPeruS** [comment]
`tree /usr/lib/osu-lazer/` and tree `src/osu` , also post console log generated by running osu!lazer

**Comment by toovs** [comment]
http://ix.io/1BIL

running `osu-lazer` doesn't produce any console output.

**Comment by toovs** [comment]
any more ideas on how to possibly reset this? I tried removing `~/.local/share/osu` but didn't help.
