### ISSUE TITLE
Can only play regular osu! on mobile

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4270]
The following bugs are not currently fixed from my experience

can only play osu! regular due to tapping being mapped to left click only:
 •Taiko requires l/r mouse clicking/keyboard, but tapping only triggers inner left (left click) 
• osu!mainia requires the keyboard
•osu!ctb requires the keyboard, and the mod for it being mouse instead is disabled and can’t be enabled. Moving the mouse is like moving your finger on the touchscreen
-can’t do anything that has to do with tapping a user name And doing the following in mobile.
 •Spectate
 •Add friends
 •invite people

-some storyboards will load, some will not (widescreen format not supported)

These bugs are from osu!lazer!mobile. Plz fix (:

**Comment by TeamSoldierNub2** [comment]
The following bugs are not currently fixed from my experience
- can only play osu! regular due to tapping being mapped to left click only
-can’t add skins even though beatmap assigned skins will load
-can’t do anything that has to do with tapping a user name And sound the following: 
 * Spectate
 * Add friends
 *all while in mobile

**Comment by peppy** [comment]
already an issue open for this please search.
