### ISSUE TITLE
Trying to create too many multiplayer rooms simultaneously results in an exception

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4271]
![GitHawk Upload by TeamSoldierNub2](https://i.imgur.com/hlRQA3Z.jpg)![GitHawk Upload by TeamSoldierNub2](https://i.imgur.com/ORyDZwk.jpg)

Had an issue making a room while another one I made is up

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peppy** [comment]
Would be great if you could include logs, not a screenshot of logs.

Also, this is intended behavior for non-supporters, but it obviously shouldn’t throw an error.

**Comment by TeamSoldierNub2** [comment]
@peppy Kay... I’m on iPhone and I tried to copy the log (aka tap and hold... yep didn’t work) but it would not let me lol. Thanks for the info tho!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Morodar** [comment]
Could reproduce bug
Added logs
[network.log](https://github.com/ppy/osu/files/2877591/network.log)
[performance.log](https://github.com/ppy/osu/files/2877592/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2877593/runtime.log)
[database.log](https://github.com/ppy/osu/files/2877594/database.log)
