### ISSUE TITLE
ios 10 - 10.3.3 support,

### ISSUE THREAD

**Issue by minefreaky** [ppy/osu#4272]
I would like to see ios 10 support added because many poeple are still on ios 10-10.3.3 (me included).
I cant download many apps because i am on ios 10.3.3 and i would be devastated if i cant play Osu!

i know its hard to add support for different ios versions but please consider it,

Kind regards,

Minefreaky

**Comment by peppy** [comment]
Which device are you using?

**Comment by peppy** [comment]
Duplicate of #4239

**Comment by minefreaky** [comment]
Im using ios 10.3.3 build (14G5053A)
