### ISSUE TITLE
taiko pp calculation way off on /b/1594500

### ISSUE THREAD

**Issue by Francesco149** [ppy/osu#4275]
not sure whether i should post this on osu-tools or here, but since the pp calc code is in osu i figured I'd post here

when using osu-tools to calculate the number 1 score on this https://osu.ppy.sh/beatmapsets/353583#taiko/1594500 the pp value is completely off even though the star rating matches stable

```
$ dotnet run -- simulate taiko 1594500.osu -m fl -m dt -m hd --combo 1776 -G 63 --misses 12
Pendulum - Showdown (fieryrage) [n1doking's Ultimatum]
Accuracy       : 98.125%
Combo          : 1776 (76.55%)
Misses         : 12
Goods          : 63
Greats         : 2245
Mods           : FL, DT, HD
Strain         : 316.768898301662
Accuracy       : 179.762755725603
pp             : 566.283813631097
```

it's almost as if this particular score is ignoring combo scaling, I'm really curious on what's going on here, there's also other low combo scores on this map that are seemingly unaffected by combo scaling like vzk's

**Comment by cory2067** [comment]
I'd like to revive this.

It's interesting that the calculation here even has "combo scaling," because the observed behavior on osu-stable is that **pp is independent of your combo**

A pretty accurate community [pp calculator for taiko](https://mon.im/taikopp/) doesn't even ask for your combo (just the beatmap max possible combo).

The top play on Showdown right now is 709pp, but this calculator yields:
```
dotnet run -- simulate taiko beatmaps/showdown.osu -m fl -m dt -m hd --combo 1362 --misses 4 -G 39
2320
Pendulum - Showdown (fieryrage) [n1doking's Ultimatum]
Accuracy       : 98.9870689655172%
Combo          : 1362 (58.71%)
Misses         : 4
Goods          : 39
Greats         : 2277
Mods           : FL, DT, HD
Strain         : 315.845500480028
Accuracy       : 204.965914104266
pp             : 593.046788358559
```

This is very far off, but if you just remove the combo argument, the calculation is close to the expected value
```
dotnet run -- simulate taiko beatmaps/showdown.osu -m fl -m dt -m hd --misses 4 -G 39
2320
Pendulum - Showdown (fieryrage) [n1doking's Ultimatum]
Accuracy       : 98.9870689655172%
Combo          : 2320 (100%)
Misses         : 4
Goods          : 39
Greats         : 2277
Mods           : FL, DT, HD
Strain         : 412.221019443605
Accuracy       : 204.965914104266
pp             : 705.208785024822
```

**Comment by smoogipoo** [comment]
This is intentional for now. The current (osu!stable) SR calculator is bugged and isn't outputting the combo scaling, whereas lazer is (and is more correct in that sense). It'll be formally removed from osu-performance soon (https://github.com/ppy/osu-performance/pull/117).
