### ISSUE TITLE
Osu lazer not opening

### ISSUE THREAD

**Issue by Leorux** [ppy/osu#4276]
**Describe your problem:** Osu!Lazer isn't opening

**Screenshots or videos showing encountered issue:** 
![captur](https://user-images.githubusercontent.com/47729277/52924899-58848680-32f4-11e9-9ee5-88c22285091c.PNG)
![captur2](https://user-images.githubusercontent.com/47729277/52924902-5c180d80-32f4-11e9-9099-2e7c7fb6acde.PNG)
**osu!lazer version:** 2019.216.0
**Logs:** 
[update_success.log](https://github.com/ppy/osu/files/2873850/update_success.log)
[runtime.log](https://github.com/ppy/osu/files/2873852/runtime.log)

**Comment by peppy** [comment]
`update_success` isn't from lazer.

note you are probably hitting the windows 7 issue: https://github.com/ppy/osu#requirements

**Comment by Leorux** [comment]
here is the thing, it meets all the requirements and I'm in windows 10
