### ISSUE TITLE
osu!direct - sorting does not work when search field is empty

### ISSUE THREAD

**Issue by Morodar** [ppy/osu#4284]
**Describe your problem:** 

As title says, osu!direct does not refresh/sort content by plays  (and for other sort options too) when the search field is empty.

How to reproduce:
- Open osu!lazer
- Click on osu! symbol
- Click on osu!direct
- Click on sort option: `Plays`
(nothing happens, (First Screenshot))
- Click on list symbol
(Content is empty, (Second Screenshot))

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/10113399/52977968-94404e80-33cf-11e9-8b44-3da07c11b47e.png)

When selecting list symbol, content is empty

![image](https://user-images.githubusercontent.com/10113399/52977988-acb06900-33cf-11e9-8d94-c6b7d25cc8cc.png)

**osu!lazer version:** [2019.216.0](https://github.com/ppy/osu/tree/2019.216.0)

**Logs:**
[database.log](https://github.com/ppy/osu/files/2877511/database.log)
[network.log](https://github.com/ppy/osu/files/2877512/network.log)
[performance.log](https://github.com/ppy/osu/files/2877513/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2877514/runtime.log)

**Comment by Morodar** [comment]
Just a Side note:
When I enter something in the search bar everything behaves as expected.

Another Side note:
When I enter something in the search bar, then sort by `Plays` and then remove the content in search bar, the sort by jumps from `Plays` back to `Ranked` - is this expected?

**Comment by peppy** [comment]
I'm 99% sure sorting just isn't implemented yet?

**Comment by Morodar** [comment]
**Here a side-by-side comparison of sorting by plays:***
![image](https://user-images.githubusercontent.com/10113399/52991545-65e16400-340d-11e9-9326-9fc625bb55ae.png)

I played further around and figured out that:

**osu!lazer and website do have **the same** behavior for:**
- Artist
- Difficulty
- Plays

**osu!lazer and website do have **different** behavior for:**
- Revelance
- Ranked
- Rating

**osu!lazer only:**
osu!lazer offers`Sort by` **Creator**, while the Website doesn't (I also checked it's `More Search Options`

**Here a side-by-side example of sort by `Rating`:**
![image](https://user-images.githubusercontent.com/10113399/52991801-8f4ebf80-340e-11e9-9b18-1a9f2456c50b.png)

**Yet another side note:**
Website does offer sort order **Descending** and **Ascending** while osu!lazer doesn't

**Comment by Morodar** [comment]
Should I create multiple issues for different aspects for things like **Descending**, **Ascending** and different behavior for **Relevance, Ranked, Rating**?

**Comment by TeamSoldierNub2** [comment]
>Should I create multiple issues for different aspects for things like **Descending**, **Ascending** and different behavior for **Relevance, Ranked, Rating**?

@Morodar probably

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Morodar** [comment]
@peppy 

I just figured out that the **Most Played** button works.
However the described bug still persists. 
(clicking on **Plays** instead of **Most Played** causes the bug)

![picture](https://puu.sh/CQiKB/f91800d6d4.jpg)

**The other view works too**

![picture](https://puu.sh/CQiM9/333b1fae4d.jpg)

**Comment by smoogipoo** [comment]
Fixed by https://github.com/ppy/osu/pull/4324/files
