### ISSUE TITLE
SliderBall updates one frame behind

### ISSUE THREAD

**Issue by peppy** [ppy/osu#4288]
Currently DrawableSlider transfers the `Tracking` value from `SliderBall` in its own `Update`. This occurs before `SliderBall` has been updated for the current frame, which is likely too late.

Note that we cannot resolve by moving to UpdateAfterChildren as that will be too late for other components to react to the incoming value change.

**Comment by TeamSoldierNub2** [comment]
Got it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by smoogipoo** [comment]
This may not be an issue anymore because the tracking value is updated in a separate component now.
