### ISSUE TITLE
Wrong grades: S in osu! possible even if you miss circles/sliders

### ISSUE THREAD

**Issue by Morodar** [ppy/osu#4291]
**Describe your problem:** 

When I **miss a circle/slider** in osu! stable, I won't be able to receive a **S grade**.
However, in **osu!lazer I actually can** - is this intended?

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/10113399/52995064-de4e2200-3419-11e9-99aa-8495b751f786.png)

**osu!lazer version:** 
[2019.216.0](https://github.com/ppy/osu/releases/tag/2019.216.0)

**Comment by Poyo-SSB** [comment]
Related issue: #4184.

**Comment by smoogipoo** [comment]
Going to close as a duplicate. As pointed out in the referenced issue, we're trying to standardize scoring and we'll need to figure out ranges that make more sense.
