### ISSUE TITLE
Blinds Mod Causes Game to Crash on iOS

### ISSUE THREAD

**Issue by ghost** [ppy/osu#4293]
**Describe your problem:** 
When the blinds mod is selected and the player attempts to play a beatmap, the game crashes after loading.

**osu!lazer version:** 2019.216.0

**Device:** iPad 6th generation non-cellular

**Comment by CobaltMK1** [comment]
I’m reporting waaay to many iOS bugs lol

**Comment by TeamSoldierNub2** [comment]
What mode did you try?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CobaltMK1** [comment]
> What mode did you try?
> 
> Sent with [GitHawk](http://githawk.com)

Normal osu

**Comment by WebFreak001** [comment]
blinds only exists for standard. I think maybe this could have to do with the blinds panel texture? It's relatively big (752 KB, 1310x2048) and not a power of 2 on the X axis

**Comment by Joehuu** [comment]
Doesn't seem to happen anymore with all the improvements with performance.
