### ISSUE TITLE
Widescreen storyboards (default) won’t load

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4297]
Widescreen storyboards, which are default for osu, won’t load opposed to old storyboards (comparison below)

![GitHawk Upload by TeamSoldierNub2](https://i.imgur.com/CJa8Khs.jpg)![GitHawk Upload by TeamSoldierNub2](https://i.imgur.com/HpTovN8.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TeamSoldierNub2** [comment]
Actually nvm, i think it’s due to old storyboards still being supported and newer ones not loading correctly. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by smoogipoo** [comment]
Got a beatmap link handy?

**Comment by TeamSoldierNub2** [comment]
>Got a beatmap link handy?

@smoogipoo https://osu.ppy.sh/beatmapsets/50763#osu/155915 test this in iOS lazer. I think t might depend on the device 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nekodex** [comment]
That beatmap uses video and not a storyboard... and video is not yet implemented, see #1963.
