### ISSUE TITLE
RoomInspector image (multiplayer lounge) will change when game creation is cancelled

### ISSUE THREAD

**Issue by nekodex** [ppy/osu#4309]
Steps to reproduce:
- Attempt to create a new multiplayer room
- Select any beatmap
- Exiting without creating the room/game (by hitting esc, etc)

Expected behaviour:
The RoomInspector background image should remain as the placeholder

Actual behaviour:
The RoomInspector background image will change to the above selected beatmap's background

**Comment by nyquillerium** [comment]
this no longer seems to happen on my branch on https://github.com/ppy/osu/pull/4400. Possibly fixed with the local background logic fix.
