### ISSUE TITLE
Local Leaderboard not showing Avatar correctly

### ISSUE THREAD

**Issue by Morodar** [ppy/osu#4315]
**Describe your problem:**

When you finish a beatmap and then look at the results, switching to **Local Leaderboard** (at the bottom mid, button on the right) does show your score, however the profile picture is not shown. When clicking on that profile picture, an empty profile is shown.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/10113399/53277252-44c98d80-3703-11e9-89c8-c9109ed2ba1c.png)

**When you click on the "empty" profile picture:**

![image](https://user-images.githubusercontent.com/10113399/53277281-64f94c80-3703-11e9-9c19-b435efa6ec3d.png)

**Same problem occurs in song selection > Local**

![image](https://puu.sh/CQigB/5b14ada280.png)

**However, Global Rankings do work**

![image](https://puu.sh/CQigP/0c132c0d10.jpg)

**osu!lazer version:**
[2019.216.0](https://github.com/ppy/osu/tree/2019.216.0)

**Logs:**
-

**Comment by Lolihunter1337** [comment]
Not sure if i should make a new issue for this. but adding a replay does the same. 
i think replays should also lead to the user profile instead of showing an empty page?
![Unbenannt](https://user-images.githubusercontent.com/17437302/55525732-83535000-5692-11e9-9c94-17d28e5812e3.PNG)

**Comment by peppy** [comment]
Replay metadata does not have user ids. This cannot be solved.
