### ISSUE TITLE
Multiplayer username overlapping chat in time shifted room

### ISSUE THREAD

**Issue by Morodar** [ppy/osu#4316]
**Describe your problem:**

The usernames in the chat of a time shifted multiplayer room can cause overlapping.

**Screenshots or videos showing encountered issue:** 

![picture](https://puu.sh/CQjeG/15857e0b82.png)

**osu!lazer version:**

[2019.216.0](https://github.com/ppy/osu/tree/2019.216.0)

**Logs:**

Not needed.

**Comment by AltenGD** [comment]
Seems to be a duplicate of #2819
