### ISSUE TITLE
Gameplay performance drops with high numbers of hitobjects on screen

### ISSUE THREAD

**Issue by XDmarieteXD** [ppy/osu#4323]
Playing the map ''centipede, knife party'' (https://osu.ppy.sh/s/150945#) the game lags a lot. In that moment I had putted an skin on osu! lazer. The map was with the mod autoplay.

screenshot:
![e1894e6d-e489-4064-8bf1-97b1f282759e bmp](https://user-images.githubusercontent.com/46970493/53300445-a8f56a00-3847-11e9-8625-64ebe3dc308e.jpg)

osu!lazer version->.216.0

**Logs:**->
[network.log](https://github.com/ppy/osu/files/2897978/network.log)
[performance.log](https://github.com/ppy/osu/files/2897979/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2897980/runtime.log)
[database.log](https://github.com/ppy/osu/files/2897981/database.log)

**Computer Specifications:**-> 
[DxDiag.txt](https://github.com/ppy/osu/files/2897985/DxDiag.txt)

**Comment by peppy** [comment]
After recent performance improvements, this is back on par with early days of lazer. @XDmarieteXD can you confirm that it has considerably improved?

While we are confident we can optimise these cases to run smoother than stable, this will likely come a bit later.

**Comment by XDmarieteXD** [comment]
Peppy, it stills lagging, but lower than before. I leave you a screenshot here:


![7b2fc294-c90b-4654-8f32-02f86daedd87 png](https://user-images.githubusercontent.com/46970493/53730482-5edc3c00-3e78-11e9-9f5a-f19ae86178f9.jpg)

And sorry for my bad English :'(

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/7968.
