### ISSUE TITLE
FPS Drop at start of map

### ISSUE THREAD

**Issue by aspriddell** [ppy/osu#4327]
When a map is selected, after it starts the FPS drops a lot and then builds back up after a few seconds. (I checked the skin and it's the same with the default one). I know that screen recording drops FPS, but when you see the FPS counter, it still drops to under 20 and goes back up to 70-80 (Mine's capped at 120)

Videos:
- [1](https://drive.google.com/open?id=1zqdsADwwu78-Mx0dGT6RObIow80O9UsT)
- [2](https://drive.google.com/open?id=1Zkb_MWQzDXzTnrxcwefWN06Sk1FydirP)

Version: 2019.216.0
Logs attached but I doubt you'll find anything useful:
- [Logs](https://drive.google.com/open?id=1P051Q9jhMEHBcKYjmMCODeUDfrJzqy-s)

**Comment by peppy** [comment]
This has mostly been resolved via performance improvements we've made over the last week. @aspriddell please confirm.

**Comment by aspriddell** [comment]
yup, frames are nice and high, cheers @peppy
