### ISSUE TITLE
MIDI devices support

### ISSUE THREAD

**Issue by lenzfilipski** [ppy/osu#4328]
**Describe the feature:** Make compatible the use of midi devices directly, without third-party software. 

**Proposal designs of the feature:**
- possibility of assigning the midi keys in "Key configuration"
- if possible, turn on the midi note/key set for better recognition by returning a signal to the note/key
- live light feedback when clicking 
![osu_midi_launchpad](https://user-images.githubusercontent.com/29278669/53308746-eee01b80-38a3-11e9-99c9-a31667030cef.jpg)

I've got a lot of fun playing osu! with my Launchpad S. Normally I use Bome's Midi Translator so I can use my Launchpad as a keyboard but it does'n work in osu!laser. So i got this idea.
Also sorry for my english.

**Comment by peppy** [comment]
Definitely needs to be added (I believe stable already had support).

**Comment by HoLLy-HaCKeR** [comment]
I previously looked into adding this to the framework, but the nuget package for ManagedBass.Midi does not expose the right methods (see ManagedBass/ManagedBass#54).

**Comment by HoLLy-HaCKeR** [comment]
Midi input is now in the framework since ppy/osu-framework#2804, so once we have a framework update it should work.
