### ISSUE TITLE
Cannot create multiplayer rooms with "Grow" Mod

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4336]
**Describe your problem:** It gives WebExceptions and other things when trying to create a room.

**Screenshots or videos showing encountered issue:** 
![osu_2019-02-26_14-31-34](https://user-images.githubusercontent.com/43073074/53416957-d7548000-39d4-11e9-9d35-feb55ded0773.jpg)
(Also seems like there's an error sending messages on multiplayer rooms)

**osu!lazer version:** 2019.226.0.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/2905730/runtime.log)
[network.log](https://github.com/ppy/osu/files/2905731/network.log)

**Comment by LeNitrous** [comment]
Seems to be fixed.

![image](https://user-images.githubusercontent.com/20495991/53670984-951e8d80-3cb7-11e9-9150-61f3436b0f0e.png)
