### ISSUE TITLE
Score List Filter not correctly filtering

### ISSUE THREAD

**Issue by Slyrboy** [ppy/osu#4339]
Currently playing osu! beta. osu.cfg says:  _ReleaseStream = Beta40

When choosing a filter for the score list (Friend Ranking, Country Ranking, ect.) the filter does not actually filter correctly.

If its "Friend Ranking", it will display the top 50 ranks, then your score will display at the bottom of the list.
![image](https://user-images.githubusercontent.com/24701441/53456540-d7687600-39fc-11e9-8542-1182dc011f12.png)

If you choose anything else other than local, it will show the top 50 plays (regardless if there is a mod as a filter)

The local filter works fine.

**Comment by katame-no-shi** [comment]
i have this same issue, started osu! as normal and this problem came up :(
![screenshot220](https://user-images.githubusercontent.com/48037140/53457142-2e6f4a80-39ff-11e9-8554-956e16ad71a3.jpg)

(i just created this account for this issue)

**Comment by katame-no-shi** [comment]
the issue got fixed for me

**Comment by smoogipoo** [comment]
This repo is for osu!lazer only.
