### ISSUE TITLE
Multiplayer room's text-box keeps focus while playing a beatmap

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4350]
**Describe your problem:** I just finished a song in a multiplayer room and saw the chat with all `z` `x` keys I pressed.

**Screenshots or videos showing encountered issue:** 
![zxzxzxzx](https://user-images.githubusercontent.com/43073074/53495923-3f709800-3aa1-11e9-8902-dc268f494602.png)

**osu!lazer version:** 2019.226.0.0

**Logs:** N/A

**Comment by peppy** [comment]
This was intended to be fixed (see https://github.com/ppy/osu/issues/4029). Can you confirm a regression?

**Comment by Gabixel** [comment]
Well, I just found out that the problem is not the focus while playing a beatmap (this was just a coincidence, it works correctly, no regression), the real problem is with some weird non-focus moments instead of being focused. I guess it's better creating a new issue explaining this.

**Comment by nyquillerium** [comment]
It seems that the textbox is still getting input when in playerloader.
