### ISSUE TITLE
Proposals for mobile device performance and etc

### ISSUE THREAD

**Issue by KevZhi** [ppy/osu#4360]
1. Potato device Mode
Obsolete iOS device (A8 chip or older) and most non-flagship Android device cannot run Lazer on a acceptable fps, not only MEM issues.
· Restrict Resolution to 0.5x (e.g. force iPad Air to 1024*768 instead of 2048*1536
( certain music game have done that and it exactly helped fps)
· Defaultlly disable and hide Storyboard, blur settings for them
· Reduce circles and sliders animation if needed
· Reduce any animation if needed

For MUG, and FPS, FPS is always first to consider about, then image quality.

2.(Backlog) AirPods mode
 More and more iOS users only carry Airpods or other bt headphones when outside, and Airpods has a fixed 193 ms latency. So When Airpods connected, automatically configure latency and turn off SFX.
That truly works when I play other MUG on iPhone, but unfortunately I had to do it manually if I switch between headphones.

3. Hide unnecessary options in settings for mobile 
E.g. Hide : audio output device, mouse settings.. etc
Lock 2x refresh limit or even Vsync for mobile device for battery reasons.
Hide mouse cursors for sure now😂 

also for PC and MAC version when Catch, Taiko, Mania, that shit disgusting when covering on objects but you have no time move it to edge

4. (Backlog) Mania, Catch and Taiko input 
For mania seems full screen of note stands and portrait layout is best, just like guitar hero, landscape is worth a try
Catch, just provide four buttons on left and right bottom- left right ldash rdash, or even use 3D touch
Taiko, now T-Aiko on Android is cool

5. Potential Copyright issues of osu!direct when publishing to App Store.

Like osu!WP ( Long history lmao) can only open osz files from OneDrive or browser. Using iCloud drive or Files App is cool here.
As long as osu! doesn't provide any directly music download in app, and everything is downloaded by users from outside, that's reasonable for apple

**Comment by smoogipoo** [comment]
Please make a single issue per point.
