### ISSUE TITLE
Client crashes when enter is pressed to go into a beatmap

### ISSUE THREAD

**Issue by Pokidots** [ppy/osu#4361]
Client crashes after using enter to go into beatmap

2019.227.0

[runtime.log](https://github.com/ppy/osu/files/2913697/runtime.log)
[database.log](https://github.com/ppy/osu/files/2913698/database.log)

[performance.log](https://github.com/ppy/osu/files/2913700/performance.log)

I7 6700k 4.0ghz
16gb ddr4 ram (unsure of branding)
Windows 10 home 64bit
Asrock h170m pro4 motherboard
Gigabyte GTX 1050TI OC Edition
2x 2tb hdd 1x 1tb hdd (All seagate )

**Comment by nyquillerium** [comment]
I was able to produce a crash by rapidly leaving and entering PlayerLoader using enter. Is this the same crash that you are running into?

**Comment by Pokidots** [comment]
> I was able to produce a crash by rapidly leaving and entering PlayerLoader using enter. Is this the same crash that you are running into?

Not, it happens randomly, i sinply changed skin within the previous 2 or 3 minutes and hit enter to go into a beatmap, which then crashed the client

**Comment by nyquillerium** [comment]
May be a different issue then, going to open a new one

**Comment by peppy** [comment]
The runtime.log provided does not show any crashes. Could you please check event viewer for any issues (and also see if you can still reproduce this on the latest release)?
