### ISSUE TITLE
Import from stable does not work as expected on mac

### ISSUE THREAD

**Issue by darsparx** [ppy/osu#4370]
**Describe your problem:** On the windows installation I have I know import from stable works, but for some reason between trying to transfer back to my mac for spring break it seems to not work at all to import from stable since I had hoped to possibly start messing around with code and helping out. When I attempt to do so it reports that there is no stable install found. And just let me be clear here: I know that import exists and that it works, but for me it only works on windows not mac. Lazer refuses to acknowledge that I have it installed.

**Screenshots or videos showing encountered issue:** <img width="249" alt="image" src="https://user-images.githubusercontent.com/16845458/53610092-a4a6b500-3b97-11e9-8d59-08579af7d385.png">

**osu!lazer version:** 2019.227.0
**Logs:** 
[database.log](https://github.com/ppy/osu/files/2917564/database.log)
[network.log](https://github.com/ppy/osu/files/2917565/network.log)
[performance.log](https://github.com/ppy/osu/files/2917566/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2917567/runtime.log)

Side Note: Thanks to PPY to pointing me to https://github.com/ppy/osu/blob/master/osu.Desktop/OsuGameDesktop.cs#L135
but from what I understand of it, and the UI for it, there should be no issues, but it refuses to import no matter what I do.

**Comment by peppy** [comment]
Move your installation to a supported location. or symlink or something.

**Comment by darsparx** [comment]
Should the application folder not work? Because that's literally where it is unless I'm missing something and it expects it somewhere else than in the application folder

**Comment by peppy** [comment]
I already provided you the location in the code which checks locations. Please use this as reference and fix your installation to match.
