### ISSUE TITLE
iOS lazer crashes when tapping on the songs in the list

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4384]
**How to replicate**

_Go to singleplayer _

_Tap on the different songs on your list up to down_

_do not click on the difficulties_

_keep on doing steps 2 and 3 until it crashes_

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by swoolcock** [comment]
Likely related to https://github.com/ppy/osu-framework/issues/2200
