### ISSUE TITLE
Rates Mod

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu#4391]
**Describe the feature:** A more flexible rate-changer mod.

**Proposal designs of the feature:**
For the context of this proposal, "rate" will be defined as the speed of the map being played. Currently in osu! there are two rate changing mods namely Double Time and Half Time which changes the rate of a map to 1.5x or 0.75x respectively.

The issue is that the options seem too limiting and not to mention not friendly. There are cases where other people prefer to speed up or slow down maps for the purpose of training. An example is from DJ Shrapnel's loved set [TAKECORE OF YOURSELF](https://osu.ppy.sh/beatmapsets/480479) where each difficulty is a separate audio with matching difficulty file for that specific rate.
![image](https://user-images.githubusercontent.com/20495991/53682147-c6d23b80-3d2d-11e9-852e-28b7cd6633c1.png)

The community already made third party tools such as smoogipooo's [Map Speed Changer](https://osu.ppy.sh/community/forums/topics/114765) although it only makes a difficulty that is tied to what rate you set not to mention you still have to edit the audio file in any audio editing software.

I would also like to participate in implementing this although I reckon that I'd post this as an issue first to get the general gist of how the implementation should be if ever this gets accepted.

**Comment by peppy** [comment]
At some point we will be adding per-mod settings, at which point DT/HT could have such a setting.

**Comment by LeNitrous** [comment]
Closing as this can now be achieved under the rate adjustment mods.
