### ISSUE TITLE
Beatmap cover not zoomed correctly for the host on his first exit

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4393]
**Describe your problem:** The beatmap background is not zoomed correctly on the cover image of the room for his creator when he exits the room for the first time.

**Screenshots or videos showing encountered issue:** 
First exit:
![before](https://user-images.githubusercontent.com/43073074/53683457-3da50f80-3d01-11e9-9e2e-1ce8741d3df8.png)
After updating the list:
![after](https://user-images.githubusercontent.com/43073074/53683474-51e90c80-3d01-11e9-8ccb-e29d6f88737f.png)

**osu!lazer version:** 2019.302.0.0

**Logs:** N/A

**Comment by Gabixel** [comment]
Actually, I don't know which of the two images is the desired one

**Comment by arflyte** [comment]
The thumbnail supposed to fit the cover, not zoomed in.
