### ISSUE TITLE
When osu! is opened, it does not force landscape mode

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4394]
It needs to be in landscape mode to even play right.![GitHawk Upload by TeamSoldierNub2](https://i.imgur.com/szy9BxP.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peppy** [comment]
This is intentional for now. We will probably consider limiting per device at some point.

**Comment by FanghanHu** [comment]
can you please make this an option instead?

**Comment by peppy** [comment]
All mobile devices support screen orientation locking. Please look into your device settings.

**Comment by Joehuu** [comment]
Resolved since https://github.com/ppy/osu/pull/16733.
