### ISSUE TITLE
Multi room overlays shouldn't have any linked text

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#4395]
Not good at design or anything, but having linked text on a background that is clickable is going to cause problems (i.e. misclicks).

Anyway, they are also linked on the right side of the screen, so redundant?
![](https://puu.sh/CUigl/70e5caacfe.png)

**Comment by TeamSoldierNub2** [comment]
That’s on purpose

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by arflyte** [comment]
Looking into it

**Comment by Joehuu** [comment]
We can use `ShouldBeConsideredForInput` like on `DrawableRoomPlaylistItem`, and I would consider it resolved.
