### ISSUE TITLE
Multiplayer needs proper playlist support

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#4397]
Right now, multiplayer assumes that there is ever only one beatmap which is ever played.

<img width="1732" alt="image" src="https://user-images.githubusercontent.com/1329837/53709389-60f3ca00-3e7b-11e9-9c6d-07d20ee56757.png">

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/1329837/53709500-f68f5980-3e7b-11e9-9e64-726fc6805299.png">

Going into song select allows you to pick only one beatmap/ruleset/mod combination, rather than multiple.

Song select should:
- Provide a way to select multiple beatmap/ruleset/mod combinations.
- Provide a way to delete playlist items.
- Display a list of playlist items.

Lounge should:
- Provide an overview of the playlist to the user.

Match screen should:
- Allow the user to select a playlist item they want to play (perhaps need a button or something) or display a song select screen with the playlist items only.
    - Special consideration is required for marathon modes, where players are forced to play beatmaps in order (maybe with and without breaks inbetween?).
- Provide an overview of the playlist to the user.

Would like designs for this.

**Comment by iiSaLMaN** [comment]
I guess this is mostly resolved? the other issues should be opened separately.

**Comment by smoogipoo** [comment]
Yep this is resolved for now. Any further changes are new functionality to do with modes, which we don’t have the functionality for yet.
