### ISSUE TITLE
Multiplayer lounge screen sometimes does not use local backgrounds even if they're available

### ISSUE THREAD

**Issue by nyquillerium** [ppy/osu#4401]
As discovered from https://github.com/ppy/osu/issues/4393, the local background is not being used at seemingly random times. However, the first time the host exits from his own room, the background will be set correctly to the local background. 

The times where the local background check fails, the beatmap ID is incorrectly retrieved as 0 inside UpdateableBeatmapBackgroundSprite.

**Comment by peppy** [comment]
This seems to no longer be an issue.
