### ISSUE TITLE
wrong name of user in private conversation

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#4414]
![osu_2019-03-05_21-10-45](https://user-images.githubusercontent.com/32620809/53834569-a99aa880-3f8b-11e9-8602-4e5d27a71cfd.jpg)

instead of lazermp blah blah should be "Strolluj trolla"
when entering conversation it goes right, when leaving its wrong again
conversation was saved from last turning on of lazer

**Comment by peppy** [comment]
that's not the username; that's the next channel. private tabs do not have text until you click them to expand.

**Comment by Joehuu** [comment]
Can be closed?
