### ISSUE TITLE
hamburger menu not visible in chat if too many chats are open

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#4415]
![osu_2019-03-05_21-10-45](https://user-images.githubusercontent.com/32620809/53834868-63921480-3f8c-11e9-83de-5da057d1384e.jpg)

**Comment by sunny-lan** [comment]
Can be fixed by just adding something along the lines of
```cs
Depth = -10;
```
to the OsuTabDropdown.

Although the class says 
```
// todo: this needs to go
```

Not sure what this means? Would be happy to help if possible.

**Comment by peppy** [comment]
Adding a depth sounds like a great temporary solution, if it fixed the problem!

**Comment by sunny-lan** [comment]
Unfortunately not, seems to break other stuff (the x's on the other tabs disappear).
