### ISSUE TITLE
Crash & errors on multiplayer song selection

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4421]
**Describe your problem:** On multiplayer song selection, if you go back to the room creation page, an error shows up and the page remains empty.
Then if you go back again (using ESC or the Home button) another error shows up, and then if you press the "Create Room" button again (or going to Solo) the game crash.
I initially thought this was a regression of #4282 because I was using the ESC key, but then I discovered that also happens pressing back or any other button with that function.

**Screenshots or videos showing encountered issue:** https://streamable.com/fegjl

**osu!lazer version:** 2019.305.0.0

**Logs:** (logs shows an example going to Solo after doing that)
[runtime.log](https://github.com/ppy/osu/files/2937222/runtime.log)
[performance.log](https://github.com/ppy/osu/files/2937223/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2937224/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2937225/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2937226/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2937227/performance-gamethread.update.log)

**Comment by nyquillerium** [comment]
I believe @nekodex was looking into this after I brought it up with him last week
