### ISSUE TITLE
OsuModTouchDevice missing in OsuRuleset.GetAllMods() IEnumerable results

### ISSUE THREAD

**Issue by Piotrekol** [ppy/osu#4441]
**Describe your problem:** 
Calling GetAllMods() on OsuRuleset instance returns all mods except for OsuModTouchDevice.

**osu!lazer version:** master branch

If that's intentional then maybe that method should be renamed to indicate that it only returns user-selectable mods.

**Comment by peppy** [comment]
for context, would you be looking for a method which *does* expose all? maybe a bool argument to this method could work (`bool includeSystemMods` or similar).

**Comment by Piotrekol** [comment]
Yes, ideally I'm looking for a way to get all of them.

For my exact use case: I'm looking for a method that returns all mods for given ruleset that affect output performance values. TouchDevice is one of them as seen [there](https://github.com/ppy/osu/blob/312efbdc34a8a7e8db63d8f6edca9092e204ebbb/osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs#L93)
