### ISSUE TITLE
Escape not responding the first time after pressing escape and resuming

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#4446]
**Describe your problem:** 
Pausing the game and resuming requires you to press escape two times to pause again

**osu!lazer version:** 
2019.308.0

**Comment by jorolf** [comment]
This only happens when you click the resume button. If you resume by pressing escape again it works like it should.

**Comment by peppy** [comment]
This is something I'm aware of and in my current path forward (while implementing click-to-resume)

**Comment by peppy** [comment]
This is due to `HoldForMenuButton` not received the `OnReleased` event.
