### ISSUE TITLE
osu! doesn't run

### ISSUE THREAD

**Issue by SyumSenpai** [ppy/osu#4449]
Hello, when I want to run osu! so nothing happens, no error just nothing , yeah and the installer the same

[network.log](https://github.com/ppy/osu/files/2950072/network.log)
[performance.log](https://github.com/ppy/osu/files/2950073/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2950074/runtime.log)
[database.log](https://github.com/ppy/osu/files/2950075/database.log)
[debug.log](https://github.com/ppy/osu/files/2950076/debug.log)
[runtime.log](https://github.com/ppy/osu/files/2950077/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/2950078/update_success.log)

**Comment by swoolcock** [comment]
Please provide some details about your system.  Hardware, etc.

**Comment by SyumSenpai** [comment]
windows 7 professional service pack 1 
Intel Pentium G4500 3,5GHz
Kingston HyperX Fury Black 2133 MHz 8 GB DDR4
nvidia geforce gt 1030

**Comment by peppy** [comment]
From the logs, it looks like it was working at one point. Can you confirm this? Do you remember anything you did recently (system / software upgrades) that could have affected the game?

**Comment by SyumSenpai** [comment]
I installed new ones C++ and .net framework s

**Comment by peppy** [comment]
Could you try installing the required hotfix in https://github.com/ppy/osu#requirements for windows 7?

**Comment by SyumSenpai** [comment]
yes I tried

**Comment by SyumSenpai** [comment]
yeah and the installer the same

**Comment by peppy** [comment]
Can you check event log for any crashes?

**Comment by SyumSenpai** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/32436087/54255166-3aa6ec00-4557-11e9-8638-49453999d57f.png)

**Comment by peppy** [comment]
This looks like you have a pretty broken .net installation. That said, those errors aren't related to osu! crashing. Could you try starting osu! again then refreshing the event viewer window to find other relevant logs?

**Comment by SyumSenpai** [comment]
just after the start
![Screenshot_7](https://user-images.githubusercontent.com/32436087/54332709-b7050200-461f-11e9-9d66-3ae44632c8b9.png)

**Comment by peppy** [comment]
Is this under the application or system tab?

**Comment by SyumSenpai** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/32436087/54333535-1e708100-4623-11e9-9d88-6b0732fc8d3c.png)

**Comment by SyumSenpai** [comment]
nowhere where it was written osu! so it is not

**Comment by peppy** [comment]
Sorry but we cannot help you further. Please try deleting all data files (`AppData/Roaming/osu`) or setup development environment to debug further.
