### ISSUE TITLE
TimeSpan overflowed because the duration is too long.

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#4450]
**Describe your problem:** Going on a map crashes the game https://osu.ppy.sh/beatmapsets/478093/#osu/1029976 [Negative Infinity Fragmentation]

**Screenshots or videos showing encountered issue:** N/A

**osu!lazer version:** 61330a6

**Logs:** 
[database.log](https://github.com/ppy/osu/files/2950178/database.log)
[network.log](https://github.com/ppy/osu/files/2950179/network.log)
[performance.log](https://github.com/ppy/osu/files/2950180/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2950181/runtime.log)

**Computer Specifications:** i3 6100, GTX1050Ti, 8GB RAM

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/54103074-53f05100-440e-11e9-8351-f8b2b9b69db8.png)

The last slider has an insanely large `Distance` value.
