### ISSUE TITLE
Parallax continue to follow mouse cursor outside the window/screen

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4463]
**Describe your problem:** When `confine mouse cursor to window` option is set to `never`, the parallax continue to follow the cursor when it's outside the window, and results in a weird situation (like in the following video). This works with any Screen Mode.

**Screenshots or videos showing encountered issue:** https://streamable.com/ris68

**osu!lazer version:** 2019.308.0.0

**Logs:** N/A

**Comment by Gabixel** [comment]
To clarify: I've just noticed that the cursor can go outside the window (or screen) because of Raw Input. When it's disabled, the confine mouse feature works as expected.

**Comment by jorolf** [comment]
Then you should probably create an issue for that on the osu-framework repo.

**Comment by Gabixel** [comment]
Closing for a new issue on osu-framework
