### ISSUE TITLE
Proposal for a feature where the game will automatically create collection backups for player

### ISSUE THREAD

**Issue by xecus922** [ppy/osu#4464]
So recently in osu! I had about 1/3 of my collection songs go poof, many collection folders each having beatmaps removed, songs I had spent several months sorting into my collection folders. And to be clear I'm talking about collections, data regarding what songs were in what collection folder, not beatmaps just going missing. 

This brought up the idea of having the client periodically create collection backups for the player. You could have an option to opt in or opt out and how often you would like the backups created. 

Losing your osu! collection is devastating, especially when you've spent months or even years putting it together, all for it to just randomly disappear or have huge chunks of it disappear, it's one of the most important things to an osu! player so I think this would be a huge convenience to players in case the worst happens and they don't regularly back up their collection or may not even know about this bug that causes collections to disappear. 

I don't have any screenshots as this would be up to you to decide how you would like to implement it but there is a collection manager that Piotrekol created which might give you some inspiration or ideas on how you would like to do this if/when you decide to add it to osu!. Maybe collaborating with him when you get to it, he's a great programmer. Here is his collection manager he made that you might want to look at and how it works, might help you out: https://osu.ppy.sh/community/forums/topics/131103

**Comment by peppy** [comment]
This is not lazer related.
