### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by Bixybob** [ppy/osu#4481]
Describe your problem: 
I have downloaded sdk 2.2 as required but the game still does not opening. I am on windows 7

Screenshot: 
![Capture](https://user-images.githubusercontent.com/48629581/54492650-4d6c4880-48ea-11e9-9526-d47bba599dbe.PNG)

osu!lazer version: 
2019.314.0

Logs:
[runtime.log](https://github.com/ppy/osu/files/2975238/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/2975239/update_success.log)

Computer Specifications: 
[Info.txt](https://github.com/ppy/osu/files/2975259/Info.txt)

**Comment by peppy** [comment]
Read the readme. There's information about windows 7 requirements.

**Comment by Bixybob** [comment]
Thanks :D That was so silly of me.
