### ISSUE TITLE
Pause and fail screen can show at the same time [again]

### ISSUE THREAD

**Issue by NotAJumbleOfNumbers** [ppy/osu#4482]
**Describe your problem:** 
Yes, I know this has been closed multiple times before.  It happened to me anyways when I paused when running out of HP.
**Screenshots or videos showing encountered issue:** 
<img width="960" alt="osubug" src="https://user-images.githubusercontent.com/39015243/54500427-a76d0e00-48ea-11e9-9faa-88bf6e8409be.PNG">
**osu!lazer version:** 
2019.314.0

**Comment by peppy** [comment]
Yep, I'm aware of this and am working on a permanent solution for it (with unit tests over [here](https://github.com/peppy/osu/tree/pause-logic-simplification)

**Comment by peppy** [comment]
This should be resolved (with tests) via #4487.
