### ISSUE TITLE
Logo misaligned on player loader screen

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#4483]
**Issue:** When loading a beatmap, with mods or no-mods, the osu!logo isn’t positioned to its expected spot. The logo’s position is not affected by the texts and mods below it.
**Version:** _2019.314.0_
**Image:**
![GitHawk Upload by dscnnctd](https://i.imgur.com/JkQ1fPA.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nyquillerium** [comment]
I can't reproduce this on current master. Is there a specific resolution you're using or a device/platform?

**Comment by peppy** [comment]
I can see how it would happen. Look into `ModDisplay` and its display delay.

**Comment by LeNitrous** [comment]
This is more noticeable when using scaled UI.

**Comment by nyquillerium** [comment]
This is more of an issue with the fact that the logo always shifts up by a constant amount, as mentioned by OP. Will look into a solution.
