### ISSUE TITLE
Some invisible graphics

### ISSUE THREAD

**Issue by Bixybob** [ppy/osu#4492]
Describe your problem: Whenever I go from windowed mode to full screen mode and then restart osu lazer, some of the visual are invisible. I was in windowed mode so i could take the screenshots, but usually when i restart the game while in windowed mode, there are no problems with the visuals.

Screenshots or videos showing encountered issue: 
![Capture](https://user-images.githubusercontent.com/48629581/54628677-db396680-4a97-11e9-9f59-62951d79769c.PNG)
![Capture1](https://user-images.githubusercontent.com/48629581/54628683-dd9bc080-4a97-11e9-907d-6da7d5d19e4d.PNG)
![Capture2](https://user-images.githubusercontent.com/48629581/54628690-e1c7de00-4a97-11e9-8a25-1c50d41ede63.PNG)

osu!lazer version: 2019.314.0
Logs: 
[database.log](https://github.com/ppy/osu/files/2984759/database.log)
[network.log](https://github.com/ppy/osu/files/2984760/network.log)
[performance.log](https://github.com/ppy/osu/files/2984761/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2984763/runtime.log)

**Comment by HoutarouOreki** [comment]
I've also encountered this in my own application, elements randomly disappearing / not rendering, but didn't really think about it too much. Will record next time.

**Comment by peppy** [comment]
Potentially related to #3277. Looking for people who can reproduce this to look into it further (likely using renderdoc or otherwise to check what's happening at a gl level).

**Comment by Bixybob** [comment]
I think that this happens for low end pcs mostly. Low end pcs might have difficulties loading these resulting in an error or this could occur only for EXTREMELY slow pcs. Slow pcs might cause a lot of script errors including mine.

**Comment by HoutarouOreki** [comment]
My PC is definitely not low-end except for a dated (about 8 years old) GeForce GT240. I thought it was naturally breaking and that's why I didn't really pay any attention to this issue. It could be the case.

**Comment by smileyhead** [comment]
Same thing happens on another Windows 7 machine I've tried the game on. Maybe it's a problem with the OS?

**Comment by flashwave** [comment]
lazer runs fine on my Windows 7 box, so that's not it

**Comment by HoutarouOreki** [comment]
Windows 10 here, so no

**Comment by smileyhead** [comment]
Some things to add to this issue:

- Whenever I encounter this bug, I cannot Alt + Tab out of the game window: it will always stay on top of everything (even though the mouse pointer changes, indicating that the window focus moved).
- !taiko has no colours, you can only distinguish the notes based on if there's a circle inside or not; if there's a spinner on-screen, the colours temporarily return.
- !mania's notes and sliders are completely invisible, making the game mode unplayable.

Also, this issue happens to me 99% of the time if the game is launched in full-screen mode.

**Comment by iiSaLMaN** [comment]
@Bixybob can you check if that issue is still present

**Comment by Bixybob** [comment]
> @Bixybob can you check if that issue is still present

Not it is not. The texts are not invisible but there is a new problem, all the layout is invisible. I do not see any colors/colours and some visuals are missing. It is even worst.
![osu_2019-07-01_02-41-52](https://user-images.githubusercontent.com/48629581/60402501-1aed0f80-9baa-11e9-8618-ffe99a6f9016.jpg)
![osu_2019-07-01_02-41-55](https://user-images.githubusercontent.com/48629581/60402507-2cceb280-9baa-11e9-9723-1cac51147460.jpg)

![osu_2019-07-01_02-41-59](https://user-images.githubusercontent.com/48629581/60402508-31936680-9baa-11e9-9e68-4386c8de8259.jpg)

![osu_2019-07-01_02-42-03](https://user-images.githubusercontent.com/48629581/60402510-36f0b100-9baa-11e9-90d3-f45028c34251.jpg)


![osu_2019-07-01_02-42-55](https://user-images.githubusercontent.com/48629581/60402519-4243dc80-9baa-11e9-8ac6-121562b7498d.jpg)

**Comment by iiSaLMaN** [comment]
Exactly like mine, i should probably start looking at duplicated issues and close them, can you give me information about your CPU, GPU, Memory

And also, i'm pretty sure enabling bypass front-to-back will give you a result of the same problem you had before

**Comment by Bixybob** [comment]
> Describe your problem: Whenever I go from windowed mode to full screen mode and then restart osu lazer, some of the visual are invisible. I was in windowed mode so i could take the screenshots, but usually when i restart the game while in windowed mode, there are no problems with the visuals.
> 
> Screenshots or videos showing encountered issue:
> ![Capture](https://user-images.githubusercontent.com/48629581/54628677-db396680-4a97-11e9-9f59-62951d79769c.PNG)
> ![Capture1](https://user-images.githubusercontent.com/48629581/54628683-dd9bc080-4a97-11e9-907d-6da7d5d19e4d.PNG)
> ![Capture2](https://user-images.githubusercontent.com/48629581/54628690-e1c7de00-4a97-11e9-8a25-1c50d41ede63.PNG)
> 
> osu!lazer version: 2019.314.0
> Logs:
> [database.log](https://github.com/ppy/osu/files/2984759/database.log)
> [network.log](https://github.com/ppy/osu/files/2984760/network.log)
> [performance.log](https://github.com/ppy/osu/files/2984761/performance.log)
> [runtime.log](https://github.com/ppy/osu/files/2984763/runtime.log)
