### ISSUE TITLE
Switching between ButtonSystem states rapidly causes buttons to be briefly positioned incorrectly.

### ISSUE THREAD

**Issue by BlauFx** [ppy/osu#4514]
**Describe your problem:** If clicking on the buttons and press too fast escape causing a frame bug

**Screenshots or videos showing encountered issue:** https://streamable.com/990xb

**osu!lazer version:** 2019.323.0

**Comment by peppy** [comment]
I'm 10% sure this is already documented somewhere but can't find it.

**Comment by Joehuu** [comment]
Scroll down:
https://blog.ppy.sh/july-2018-development-update/
