### ISSUE TITLE
Make the background image behind the game customizable.

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu#4516]
Currently it uses the same default background image every time. It should be a skinnable element. Opening this as an issue for suggestions either to use "menu-background.jpg" or make it a different skinnable element instead.

Preferably another supporter-only feature.
![image](https://user-images.githubusercontent.com/20495991/54876357-82781e00-4e49-11e9-8d77-817725634643.png)

**Comment by peppy** [comment]
Sharing menu-background may be a good first step.
