### ISSUE TITLE
Game freezes while playing a beatmap

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#4545]
**Issue:** When playing 3-5 star beatmaps, the game would freeze, then fails. I think it’s because of excessive use of memory, and lack of optimization. It used to run well in _2019.302.0_ before the new update which includes the Wind Up and Down mod.
**Version:** _2019.323.0 (iOS 12 iPhone 7)_
**Video:** https://youtu.be/R8DUoHKGsRY

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peppy** [comment]
Is this reproducible every time? Across multiple beatmaps?

**Comment by dscnnctd** [comment]
When playing some beatmaps like xi - Blue Zenith, yes. Game sometimes crashes though.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
It often happens when _2019.305.0_ got released, and still does the same as of the latest release.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
Another example but game freezes in a split second.
https://youtu.be/Isfz5Ox9xys

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
I also forgot to mention that this affects all iOS players that have an iPhone 6s/7 as well. I don’t know if this occurs on iPhone 8 or higher.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
Closing due to optimisation improvements in previous and latest release.
