### ISSUE TITLE
osu!direct when a user isn't logged in

### ISSUE THREAD

**Issue by kawaemon** [ppy/osu#4550]
**Describe the feature:**
osu!direct when a user isn't logged in doesn't show anything even click search button. I think it should show something to tell the user not logged in.

**Proposal designs of the feature:**
I created a sample. 
![Screenshot](https://user-images.githubusercontent.com/34652535/55178671-29054b80-51c9-11e9-8cbc-2f7224ae0f2d.png)

**Comment by kawaemon** [comment]
Should I create pull request which contains sample code?

**Comment by jorolf** [comment]
Pull requests are always welcome. However I'm not sure if this is the right way. Maybe we should show a message inside the center of the overlay instead or we could just block opening the overlay at all.

**Comment by kawaemon** [comment]
I agree. I'll wait for discussion!

**Comment by peppy** [comment]
@arflyte we need a general way of disabling/notifying the user they need to login to use some elements. do we have anything for this currently?

**Comment by arflyte** [comment]
Hmm, there's no design for now. I'll come up with something.

**Comment by Game4all** [comment]
How about graying out the whole overlay and displaying a placeholder message in the middle of it like it is done on Leaderboards on SongSelect ?

I tried implementing it on DirectOverlay on my fork
https://streamable.com/lejop

**Comment by LeNitrous** [comment]
Why not just simply gray out the osu!direct icon and not open the overlay in the toolbar?

**Comment by Gabixel** [comment]
and when the user clicks the button the game notifies him on the notification panel explaining that you need a supporter tag (maybe with a link sending to the support page)

**Comment by LeNitrous** [comment]
You no longer need supporter to use osu!direct @gabixdev

**Comment by gabixdev** [comment]
wrong mention reeee

**Comment by smoogipoo** [comment]
For now it should use the same text as what's shown in the leaderboard.

![image](https://user-images.githubusercontent.com/1329837/64679070-e1902480-d4b5-11e9-9721-3b61d5ca7bd5.png)

**Comment by lucarou** [comment]
Hello,
As a part of our engineering studies, some friends and I tried our hands at this issue. Is this (in the screenshot) what is expected ?


![screen](https://user-images.githubusercontent.com/62743587/98102186-9ee89300-1e93-11eb-85e9-0b570e47ffad.png)

**Comment by peppy** [comment]
Seems like a good start.

**Comment by lucarou** [comment]
We have finished adding an error message telling the user they should be connected in order to access the different overlays info to all overlays, and we have tested it. You can find the code at https://github.com/Remenems/osu. Even though we have read the contribution guideline, this is our first opensource experience. We understood that we had to wait for an eventual confirmation on your side before asking for a pr. Is this how things will go ?

**Comment by peppy** [comment]
You can PR as per normal. Please read some github guides if you're unsure of how to do this.

**Comment by bdach** [comment]
@lucarou as far as I can tell your changes are in your fork's `master` - please move them to a topic branch before PRing as mentioned in the contributing guidelines.

**Comment by Remenems** [comment]
Thank you, I will do it as soon as possible

**Comment by peppy** [comment]
Closed via #11823
