### ISSUE TITLE
Japanese text is broken

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#4556]
If it hasn't been noticed yet.

**Screenshots or videos showing encountered issue:**

![](https://puu.sh/D6WQt/1cbd063b83.png)

**osu!lazer version:** master

**Comment by dscnnctd** [comment]
Can’t see this happening on the latest release, is this a specific version that is separated from the current release?
![GitHawk Upload by dscnnctd](https://i.imgur.com/ZtKtCuL.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Joehuu** [comment]
Latest `master`, which is code compiled with an IDE, shows this.

Latest release (`2019.323.0`) is fine.

**Comment by peppy** [comment]
This is fixed via https://github.com/ppy/osu-framework/pull/2308. Will be updated today with a framework build/version bump.
