### ISSUE TITLE
SkinManager should probably be a container

### ISSUE THREAD

**Issue by peppy** [ppy/osu#4572]
Currently `SkinReloadableDrawable`s are only valid in gameplay, but going forward we probably want to use them anywhere (example being #4566). As a result `SkinManager` may not need to be cached for usage directly.

**Comment by smoogipoo** [comment]
I don't believe this issue is valid. `SkinReloadableDrawble` is already usable external to gameplay, since `SkinManager` is cached as an `ISkinSource`. The referenced PR could already use `SkinReloadableDrawable`.

**Comment by peppy** [comment]
hmm, weird. surely i would have considered that...

**Comment by smoogipoo** [comment]
I've already tested this with LogoVisualisation to confirm it, for what it's worth. Closing.
