### ISSUE TITLE
BeatmapSetOverlay can cause music to stop and to play without selected mods

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4575]
**Describe the bug:** (The title I gave to this issue is not the best, it's hard to explain this in a few words, so now I'll explain how to reproduce it).
Basically, trying to click the green download button on a BeatmapSetOverlay, it sends you to a "random" difficulty of that map (I don't know how the game process this, but it's different for each map). Then, if you try to press again the green download button when you're already on the difficulty selected before, the music stops and the next play of that difficulty is without selected mods (even trying to disable/re-enable them).

**Screenshots or videos showing encountered issue:** https://streamable.com/e30vw

**osu!lazer version:** 2019.401.0.0

**Logs:** [runtime.log](https://github.com/ppy/osu/files/3031544/runtime.log) seems normal, but I'll attach it with the [performance-gamethread.update.log](https://github.com/ppy/osu/files/3031545/performance-gamethread.update.log) to see at what time each overlay was open/focused.

**Comment by peppy** [comment]
Closed via #4581.
