### ISSUE TITLE
i cant install osu lazer

### ISSUE THREAD

**Issue by Dopaminos** [ppy/osu#4579]
**Describe the bug:** i can't install lazer. Win7x32

**Screenshots or videos showing encountered issue:** no

**osu!lazer version:** newest

**Logs:** 
https://pastebin.com/qzK3zWqt

**Comment by qauland** [comment]
Windows 32-bit is not supported yet.

**Comment by smoogipoo** [comment]
Duplicate of https://github.com/ppy/osu/issues/3984
