### ISSUE TITLE
Lazer now crashes on iOS

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#4590]
**Issue:**
This might be a high priority since after updating to the new version, osu!lazer crashes completely without seeing the disclaimer screen.
**Version:**
_2019.406.0 (Latest Version, iOS 12 iPhone 7)_
**Video:**
https://youtu.be/ZA18cHzqrWU

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peppy** [comment]
Build has since been pulled, please use an older one.

**Comment by dscnnctd** [comment]
Alright, thanks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
