### ISSUE TITLE
Game freezes after entering beatmap selection

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#4592]
**Describe the bug:** Entering beatmap selection cause game freezing for about 0,5 Sec.

**Screenshots or videos showing encountered issue:** https://youtu.be/VkAlhGDlBEA

**osu!lazer version:** 2019.406.0

**Logs:** Should I include it?

I couldn't find any exact issue related to this.

**Comment by BlauFx** [comment]
I noticed it as well
Sometimes it's freezing for about 0.5 sec but sometimes it loads perfect

**Comment by jai-x** [comment]
@ToIGLAK Including logs would be helpful, they contain performance information.

**Comment by ToIGLAK** [comment]
There you go: 
[logs.zip](https://github.com/ppy/osu/files/3050236/logs.zip)

**Comment by peppy** [comment]
How many beatmaps do you have loaded? There's currently some known issues that will cause lockups when entering song select:

#3340 
#3058

**Comment by ToIGLAK** [comment]
About 1077

**Comment by Joehuu** [comment]
Fixed in #5371.
