### ISSUE TITLE
Login Overlay is behind Notification Overlay

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#4598]
![wat](https://user-images.githubusercontent.com/27222621/55667015-f5749200-5856-11e9-8487-be4ab233e6a5.png)

Bonus would be if clicking on that notification would actually open the Login Overlay.

**Comment by Game4all** [comment]
Since they overlap, shouldn't they be not allowed to be both opened at the same time ?

**Comment by peppy** [comment]
Not sure which is the correct order for this, but I think switching may feel a bit more natural.

**Comment by Game4all** [comment]
It looks a bit better but since both overlays are transparent, I think we should  either disallow having both opened at the same time or add an opacity layer to login overlay.

![image](https://user-images.githubusercontent.com/20256717/55669970-49df3800-587e-11e9-89b2-01518bae17a1.png)

**Comment by Aergwyn** [comment]
Opacity in the overlay is a whole different issue to begin with, which I'd love to have not at all or at least as a setting because sometimes you can't read anything.

**Comment by Game4all** [comment]
Oh you're right

**Comment by RORIdev** [comment]
If the overlays overlap, i personally thing that they shouldn't stack ontop of each other, or at least makes the topmost one not transparent .
