### ISSUE TITLE
MusicController not working in Lobby Select Screen

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#4599]
**Describe the bug:**
When you switch into Multiplayer and stay in the menu to select a lobby the `MusicController` is not interact able. You can open it to look at it but everything is disabled because the `Beatmap` got disabled.
Additionally the music is neither looping nor playing the next song if you reach the end of the current one.

**Screenshots or videos showing encountered issue:** [Youtube (0:45)](https://youtu.be/EacS2b-TNr4)

**osu!lazer version:** 2019.406.0

**Logs:** not needed

**Comment by peppy** [comment]
This is actually intended for the time being (as in intentionally done this way) but obviously not optimal. At very least pause and seek should probably work.

**Comment by Joehuu** [comment]
Fixed in #5041 for some reason. This issue can be closed alongside PR #4779.

**Comment by peppy** [comment]
Yep, I ended up fixing the flow in #5041. Thanks for pointing this out.
