### ISSUE TITLE
Hover sound rapidly triggered by dragging

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#4600]
**Describe the bug:** If you start dragging close to an element that has a hover sound the cursor will trigger it when dragging in the direction that move the mouse over the element. This happens as fast as updates happen I assume as it's just a constant noise. See attached video.

**Screenshots or videos showing encountered issue:** [Youtube (0:34)](https://youtu.be/XKcgG524P5w)

**osu!lazer version:** 2019.406.0

**Logs:** not needed

**Comment by peppy** [comment]
Probably needs some amount of debounce logic for sample playback (that is how stable got around this).
