### ISSUE TITLE
Taiko Method for mobile users in the future (what if)

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4604]
This is based on each position the mouse is in when left clicked/when screen is tapped. GitHawk wouldn’t let me pull a request. ![GitHawk Upload by TeamSoldierNub2](https://i.imgur.com/HVQX6MV.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peppy** [comment]
Duplicate of https://github.com/ppy/osu/issues/4201.
