### ISSUE TITLE
Cursor behaves strangely after returning from multitask

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#4605]
**Describe the bug:** When alt-tabbing at the same time that a beatmap is starting, the pause menu immediately shows up (as expected), but alt-tabbing back in shows some distorted graphics (see video).

I am using Windows 10 Pro x64, build 17763.404.
My graphics card is a nvidia geforce 1060 6GB.

**Screenshots or videos showing encountered issue:** https://streamable.com/thwmp

**osu!lazer version:** master / 2019.406.0

**Logs** (not from the video session though)**:** [logs.zip](https://github.com/ppy/osu/files/3051561/logs.zip)

**Comment by peppy** [comment]
That looks like the cursor trail trying to interpolate over some weird movement. Very interesting.

**Comment by Morilli** [comment]
In case that's helpful, a git bisect shows that the first bad commit should be [1e36962](https://github.com/ppy/osu/commit/1e369628a5c1181cd1e681478a7baff218d15ab4).

**Comment by nyquillerium** [comment]
This seems to no longer happen since b9a39fb7880b3dfa818a0e3e59f89343b2241d51 judging from a bisect. However, I don't see an obvious reason why this was fixed, and is likely still broken. Might still be worth looking into.

**Comment by peppy** [comment]
What does this mean? Can you test on master more and confirm broken or not?

**Comment by nyquillerium** [comment]
It does not happen on master, and hasn't happened since the commit mentioned.
