### ISSUE TITLE
RAM usage increases in song select by switching between 2 songs endlessly 

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#4608]
**Describe the bug:** 
If you switch between 2 songs up and down RAM usage gets higher each time. 
**Screenshots or videos showing encountered issue:** 
https://streamable.com/8ihac
**osu!lazer version:** 
Latest commit f2f60f6 also happens on 2019.406.0
**Logs:** 
doesnt show anything other than the beatmap switches

**Comment by peppy** [comment]
If you wait (or force GC from debug options) does it recover? If so, this is a non-issue.

**Comment by Lolihunter1337** [comment]
It doesnt fully recover for me. and re-entering the song select just goes back to about the same amount as before ( about 50-100MB less ). waiting does nothing.

**Comment by peppy** [comment]
What you are saying is useless. Please provide actual metrics. If it is recovering to the same memory usage and not infinitely increasing this is likely *normal execution*.

**Comment by Lolihunter1337** [comment]
yea ok nvmd i had to press GC multiply times. so it goes back to normal usage.
