### ISSUE TITLE
Autoplay!Bot favors BT1

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4609]
In autoplay, it seems to favor BT1 than the others.

Footage: https://streamable.com/tu00x

Beatmap: https://osu.ppy.sh/beatmapsets/671722#osu/1653225

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jorolf** [comment]
This is a feature and not a bug:
https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu/Replays/OsuAutoGenerator.cs#L212

**Comment by Poyo-SSB** [comment]
This is intended behavior—the auto mod in stable also exhibits this. Such a playstyle is typically referred to as "singletapping" in the community, where one key is used by default and the other is only used when the notes are too fast. "Too fast," as shown above, is 266ms.

**Comment by peppy** [comment]
Yeah, this is part of the autoplay algorithm.
