### ISSUE TITLE
UI issues while running on Fullscreen Mode

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#4621]
**Describe the bug:** UI Design issues in the main menu game while running on fullscreen mode.

**Screenshots or videos showing encountered issue:** 
![1](https://user-images.githubusercontent.com/22781491/56100977-da291700-5f27-11e9-8eb7-27f0b3dc2c85.PNG)
![2](https://user-images.githubusercontent.com/22781491/56100904-39d2f280-5f27-11e9-9dd3-56cd4f17b8b7.PNG)

**osu!lazer version:** 2019.406.0

**Logs:** Native Fullscreen 1920x1080
**OS:** Windows 10

**Comment by jorolf** [comment]
Judging from the issue title this only happens when in fullscreen mode and not in boderless or windowed, right?

Can you please include *actual* logs and your system specifications (CPU, GPU, etc.)?
(You can find your logs under settings -> general -> open osu! folder -> logs)

**Comment by iiSaLMaN** [comment]
> Judging from the issue title this only happens when in fullscreen mode and not in boderless or windowed, right?
Yeah, only in fullscreen mode

> Can you please include _actual_ logs and your system specifications (CPU, GPU, etc.)?
> (You can find your logs under settings -> general -> open osu! folder -> logs)

CPU: Intel Core i5-2430M 2.40 GHz, can go up to 3.00 GHz thanks to Intel Turbo Boost Max
GPU: Intel HD Graphics 3000 Switchable with AMD Radeon HD 6630M
Memory: 6 GB DDR3 1600MHz

Logs: 
[network.log](https://github.com/ppy/osu/files/3078080/network.log)
[performance.log](https://github.com/ppy/osu/files/3078081/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3078082/runtime.log)
[database.log](https://github.com/ppy/osu/files/3078083/database.log)

**Comment by peppy** [comment]
Can you confirm it's fine when running borderless?

**Comment by iiSaLMaN** [comment]
**Borderless Mode:**
![osu!lazer on Borderless](https://user-images.githubusercontent.com/22781491/56174658-32314d80-5ffc-11e9-8fde-29a988ad1dc4.PNG)
**Windowed Mode:**
![osu!lazer on Windowed](https://user-images.githubusercontent.com/22781491/56174672-483f0e00-5ffc-11e9-9951-5b5f60756fe7.PNG)
**Fullscreen Mode:**
![osu!lazer on Fullscreen](https://user-images.githubusercontent.com/22781491/56174680-4d9c5880-5ffc-11e9-8460-8748eceb2842.PNG)

**Comment by iiSaLMaN** [comment]
related to #4492 but this is only in fullscreen mode, i think it's related to Intel HD Graphics 3000

**Comment by iiSaLMaN** [comment]
Turns out the issue is still present, but i found something
first: i get texture glitches just like #5018 on the latest release
second: when enabling bypass-front-to-back, it gives me the same output i got in [this issue](#4621)

**Comment by iiSaLMaN** [comment]
Closing as duplicate of #5199, has nice details than this.
