### ISSUE TITLE
Catch diffcalc is off when compared against stable

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#4622]
This is an issue tracking progress on bringing lazer diffcalc more in-line with stable.

I've compiled the following spreadsheet from around 450k beatmaps, including ~15K catch-specific (non-converted) beatmaps:  
https://docs.google.com/spreadsheets/d/1M6Disj19FQOFfs7gv7CdJgvyd4fovJFHszwrFiIMW0k/edit#gid=0

The more_than_0.1_diff sheet is hugely trimmed down, and I will update once the existing large differences are reduced.

**Comment by HoLLy-HaCKeR** [comment]
I'm looking into this right now. One of the differences between stable and lazer is that stable uses an unstable sort for sorting hitobjects by StartTime. Some of the beatmaps I picked from the list seemed to be 2B maps, so the order in which stable grades 2B notes is semi-random. It's not the cause for the massive difficulty values (found a fix for that, will PR), but it may cause the smaller differences.

**Comment by smoogipoo** [comment]
Small differences relating to the unstable sort are fine imo. There's nothing we can really do there, unfortunately, since the sorting algorithm changed with .NET 4.5/core.

**Comment by peppy** [comment]
@HoLLy-HaCKeR any updates on this one? are there still remaining tasks here or did #4770 bring us close enough?

**Comment by smoogipoo** [comment]
I've just updated the spreadsheet mentioned in the OP with a new round of beatmaps. Let me know if all of these can be justified. Particularly interested in the larger ones (~10 stars) and the smaller ones (~1-2 stars).

We need to check:
1. How much effect randomisation has on HR. If it's negligible then we can probably be fine using the current un-seeded RNG.
2. To get the changes working I've had to hack in a maximum of 10000 slider ticks. This can happen if velocity is infinity I believe, and we'll need a solution for this.

**Comment by HoLLy-HaCKeR** [comment]
I'll take a look at the new set, but I'm currently in my exams so it may take a few days.

**Comment by HoLLy-HaCKeR** [comment]
Are the pp values for stable correct? The values I'm getting in the stable client (b20190603.2) are way closer to the lazer values than the spreadsheet suggests.

| id | Spreadsheet stable | Spreadsheet lazer | Ingame stable |
| -- | ------------------ | ----------------- | ------------- |
| 1608232 | 66.0697 | 448.715 | 463.78 |
| 959866 | 514.284 | 397.271 | 403.51 |

**Comment by smoogipoo** [comment]
The build I'm using for stable is about 2-3 years old at this point, and I'm not sure if it's even been correctly brought up-to-date to that point. It's likely that some changes were made since then that affected hitobject generation, because my build generates ~3000 hitobjects whereas cutting edge generates ~80000, most of which are simultaneous.

For cases that don't generate simultaneous hitobjects, it should still be fine to get the general gist of things. Otherwise, double check with in-game.

**Comment by smoogipoo** [comment]
As a bit of an update, I've managed to update my stable diffcalc branch which seems to give roughly the correct result (463*). A full reprocess will take a couple of days/a week though.

**Comment by smoogipoo** [comment]
I've updated the sheet with values from my updated stable build. They seem to look a lot closer now. All the -1's are beatmaps which stable couldn't compute.

Again, probably worthwhile to pick a few maps and checking over why their differences occur, such as `/b/61411`.

**Comment by smoogipoo** [comment]
Updated the sheet with the change in #5028
