### ISSUE TITLE
Various skin/visual/gameplay related requests

### ISSUE THREAD

**Issue by KirbyJoe** [ppy/osu#4623]
**Describe the new feature:** 
I have many skin/visual/gameplay related feature requests while I playing osu!lazer:

- Support for animated/segmented elements: As mentioned in #3673, the animated/segmented elements is not supported right now.
- skin.ini version support: Some skins has elements from the old skin versions (mostly for spinners, countdowns and osu!catch elements).
- Combo fire 2.0: I saw a video that demonstrates the revised and redesigned version of combo fire (the visual element that is featured in early versions of osu! and removed due to performance concerns) for a long time ago (I can't remember the title of video and who posted it). The new version of combo fire has rising triangles, and it seems to be good for performance.
- Support for videos: Some beatmaps has videos, but it doesn't shows up on osu!lazer.
- Support for custom life bar, score counter, accuracy meter, mod icons and combobursts: These are not showing up on osu!lazer (life bar, scour counter, accuracy meter and mod icons uses the osu!lazer default, combobursts are not showing up even on default skin).
- Missing spinner sound: The sound effects for spinner is missing on osu!lazer.
- Full skin support for all non-standard gamemodes: Skins for gamemodes other than osu!standard are not supported yet in osu!lazer (support for osu!catch is mentioned at #3967)
- Countdowns: Countdowns are missing on osu!lazer.
- Triangle visualization on main menu and song selection: On old cutting edge versions of osu! which are released in November 2014, the game shows the triangles on background of main menu and song selection, but it's removed due to performance issues. Since the triangles are working fine on osu!lazer, I think it's good to add it as an optional feature.
- Geki and Katu: In non-lazer versions of osu!, there's two scoring terms are used which are depends on the level of accuracy of every comboset: Geki and Katu. It's missing on both gameplay and result screen in osu!lazer (add it as an optional feature).
- Classic judgements: If the player likes the old judgement (along with classic score display), the player can enable the classic judgements optionally by settings.
- Drain Time: Drain time is missing on osu!lazer (add it as an optional feature).
- Classic warning arrow: On non-lazer versions of osu!, when the player reaches the few moments before the break ends, the arrow shows up. The player can enable it optionally from settings.

**Comment by peppy** [comment]
We don't do batch issues like this. Please search and open individual issues. You'll find many pieces of what you asked for already had issues.

**Comment by KirbyJoe** [comment]
I'm currently opening individual issues from this.
