### ISSUE TITLE
Support for animated/segmented skin elements

### ISSUE THREAD

**Issue by KirbyJoe** [ppy/osu#4627]
**Describe the missing feature:** 
As mentioned at #3673, the support for animated/segmented skin elements is missing on osu!lazer.

**Comment by KirbyJoe** [comment]
It seems fixed on #5202. Does this should be closed?

**Comment by peppy** [comment]
Animations aren't implemented. That PR just fixes the hacky first-frame behaviour some skin creators used.

Will leave this open until animations are supported.

**Comment by jorolf** [comment]
Has somebody already started working on this or is it still left?

**Comment by peppy** [comment]
It was on my list, but go for it.

**Comment by Joehuu** [comment]
OP:
> As mentioned at #3673, the support for animated/segmented skin elements is missing on osu!lazer.

Duplicate of #3673. Not sure why this issue was opened if it was literally the same.
