### ISSUE TITLE
New Accuracy Calculation

### ISSUE THREAD

**Issue by FoyerAsDer** [ppy/osu#4638]
**Describe the new feature:** 

A new selectable accuracy calculation mode that allows you to visualize the accuracy based on the total amount of objective in the map. It will always start as 100%, and drop if you hit any 100 or 50 or miss, without increasing. For example. if you hit the very first note of a song as a 100, the accuracy won't go from 0% to 33%, but it will drop from 100% to XX,XX%, calculated on the total hits of a map.

**Comment by camellirite** [comment]
so..

make accuracy start at 100% instead of 0?

**Comment by FoyerAsDer** [comment]
Yes and no. It's true that acc will start as 100, but it can only decrease. Like if I get to a pause on the map and I see 99.88%, I will know that if I SS from that point I will get 99.88 on the map.

**Comment by camellirite** [comment]
that's a quite misleading though, accuracy is based on what you've already hit and how you've played the map so far, not based on the best case scenario for the map

I think this idea would work better as mod like sudden death or perfect, if enabled it'll automatically replay the map if you fall under a given accuracy like 98% or something the player sets

**Comment by peppy** [comment]
Definitely sounds like something which may be better geared as a mod.

**Comment by LeNitrous** [comment]
A mod that ignores judgement and all hits count as 300s?

**Comment by peppy** [comment]
Sure.

**Comment by LeNitrous** [comment]
Don't mind if I do ;)

**Comment by peppy** [comment]
I think this is fine to go ahead and implement, along with the scoring type we already have.

**Comment by iTzHard** [comment]
Personally I would prefer it to be a selectable option since it wouldn't affect gameplay in any means since you would get the same accuracy and score at the end of the map regarding the accuracy display option you choose.

Also, how could this be implemented as a mod? What would it exactly change gameplay wise?

**Comment by peppy** [comment]
As I just mentioned, it would be a setting, not a mod. See the existing score display mode.

**Comment by bdach** [comment]
Closing in favour of #9336 as that issue includes this one and has a wider scope.
