### ISSUE TITLE
In-game PP Leaderboards

### ISSUE THREAD

**Issue by aireulain** [ppy/osu#4639]
**Describe the new feature:** PP leaderboard in-game which sorts scores on the map by highest pp achieved

**Proposal designs of the feature:** [Something like this](https://i.imgur.com/lkipe3O.png)

**Comment by nbvdkamp** [comment]
Might be better to have this as a separate option from the global/country/etc. leaderboards so that it can be applied to non global leaderboards too, would also make it easier to then add more kinds of leaderboards like acc or combo.

**Comment by EVAST9919** [comment]
In most cases Higher score = Higher PP.
Imo it's not worth it

**Comment by awesomecuber** [comment]
IMO the end goal should be to merge pp and score into one system. Seems kinda dumb to me that it's possible to get a higher score but less pp.

**Comment by peppy** [comment]
I’d hope this is no longer required with lazer’s scoring method.

**Comment by huoyaoyuan** [comment]
> In most cases Higher score = Higher PP.

My personal thoughts:
- Scoring should be very stable, while PP may change when adjusting the algorithm.
- When applying the same mods, good algorithms should ensure higher score = higher PP. But when **comparing across mods**, this will probably not be true.
