### ISSUE TITLE
Osu!lazer!ios crashes on latest build when exiting chart listing

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4645]
https://streamable.com/nxoyr

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iiSaLMaN** [comment]
What version of osu!lazer are you using?

**Comment by dscnnctd** [comment]
>What version of osu!lazer are you using?

@iiSaLMaN he’s using the latest version _2019.418.0_, can confirm I also had this happen to me.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iiSaLMaN** [comment]
Does it only crash when going back from **ChartInfo** or even when going back from **ChartListing**?

**Comment by dscnnctd** [comment]
>Does it only crash when going back from **ChartInfo** or even when going back from **ChartListing**?

@iiSaLMaN no, when you select a beatmap and picking another simultaneously, it will crash the game. I managed to reproduce it afterwards.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iiSaLMaN** [comment]
There's a way of fixing this by blocking clicks while the game is in a busy state handling a previous click

**Comment by swoolcock** [comment]
Likely related to https://github.com/ppy/osu-framework/issues/2200 will get to it when I can.

**Comment by TeamSoldierNub2** [comment]
>Does it only crash when going back from **ChartInfo** or even when going back from **ChartListing**?

@iiSaLMaN I tested it. Both.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TeamSoldierNub2** [comment]
> ...

@dscnnctd hey fellow GitHawk user!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
> ...

@TeamSoldierNub2 hello!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TeamSoldierNub2** [comment]
> ...

@dscnnctd by the way whether you enter the purple chart menu or not it still crashes when you get out of chart listing. Just some info

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
> ...

@TeamSoldierNub2 game sometimes crashes when you exit a purple difficulty beatmap, but it does not happen very often. In older iOS builds, this commonly happens.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TeamSoldierNub2** [comment]
> ...

@dscnnctd I mean it only exits when you go in chart info then go out of chart listing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
> ...

@TeamSoldierNub2 please rephrase.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
> ...

@TeamSoldierNub2
I don’t really know the problem for this, whether it used excessive memory or the app can’t handle the timing, which crashes lazer.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
