### ISSUE TITLE
Clicking the text before Lazer starts on iOS will crash

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4650]
https://streamable.com/nzs95 

Version: latest

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TeamSoldierNub2** [comment]
Build: Lazer
Platform: iOS 11.3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
Can’t reproduce. Does this only happen on iOS 11 and below?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
I managed to reproduce this by spamming the text link simultaneously.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peppy** [comment]
Please turn off the spammy signature or spot posting.

**Comment by nevespt** [comment]
So sad, i cant join to the beta 😭

**Comment by Hubza** [comment]
Im guessing the text link at the start (the discord link or support link)

if so i cant reproduce this, im guessing its fixed.

**Comment by peppy** [comment]
I've tried and can also not crash the game any more.

**Comment by Joehuu** [comment]
Nah, the external link overlay doesn’t appear until in main menu. Happens in both iOS and desktop.
![](https://user-images.githubusercontent.com/35318437/60352815-83a37480-997d-11e9-81dd-ecb102ab11b8.png)

**Comment by Joehuu** [comment]
Making another issue for iOS crash when opening external links.

**Comment by jorolf** [comment]
Maybe we should add a property to links that bypasses the overlay?

**Comment by peppy** [comment]
Crash resolved via https://github.com/ppy/osu-framework/pull/2592.
