### ISSUE TITLE
Option to share collections

### ISSUE THREAD

**Issue by Phippe** [ppy/osu#4651]
I'd like to see a share option for collections, so you could send something like an osk-file to a friend and they'll have the same collections (as long as the corresponding maps are available in their library).

**Comment by RORIdev** [comment]
Any idea on what could be the best way to implement this? What would be the new file extension and would it be a custom file format or a JSON object that contains the data of a given `BeatmapCollection`?

**Comment by Tresquel** [comment]
What about just uploading the collection to the server and just sending a friend the collection? Like a button to "Share to friends" or something like that

**Comment by peppy** [comment]
Uploading collections is a completely different feature, which I believe is already being tracked on `osu-web`.
