### ISSUE TITLE
Osu! .Exe has stopped working

### ISSUE THREAD

**Issue by BitZGD** [ppy/osu#4656]
The bug happens when opening osu! Lazer does not start me and says it has stopped working ... sometimes lasts a little longer the app and then I throw the same error ... I tried everything and the error is not removed. .please help....

My data is
Intel (R) Core (TM) i5-4570 2.9GHz
4GB ram
Windows 7 (custom post)

Screens:

https://www.mediafire.com/view/3y301x80vqhih8s/aaaaaaaaaaaaaaaaaaaaaaaaa.PNG/file

Osu! Lazer version:

2019.418.0

Logs:

https://www.mediafire.com/view/6c744c14yhzrd63/12.PNG/file

https://www.mediafire.com/view/a9t3cfvb0f19mqr/11.PNG/file

I appreciate your kindness and please give me your help to solve this problem..Thanks :D!!

**Comment by peppy** [comment]
The logs you linked are for audactiy. Also, you likely haven't read the prerequisites in the readme.

**Comment by BitZGD** [comment]
How? When trying to enter the osu! Lazer leaves me those two errors in the register of events ;3;

**Comment by BitZGD** [comment]
lmao apologize take catches without realizing

**Comment by BitZGD** [comment]
https://www.mediafire.com/view/zn8w32dvzb73f8o/13.PNG/file
