### ISSUE TITLE
Osu! Lazer has stopped working

### ISSUE THREAD

**Issue by BitZGD** [ppy/osu#4657]
The bug happens when opening osu! Lazer does not start and says it has stopped working ... sometimes lasts a little longer the app and then I throw the same error ... I tried everything and the error is not removed. .please help ....

My data is
Intel (R) Core (TM) i5-4570 2.9GHz
4GB ram
Windows 7 (custom post)

Screens:

https://www.mediafire.com/view/3y301x80vqhih8s/aaaaaaaaaaaaaaaaaaaaaaaaa.PNG/file

Osu! Lazer version:

2019.418.0

Logs:

https://www.mediafire.com/view/zn8w32dvzb73f8o/13.PNG/file

https://www.mediafire.com/view/kra0f1jookjev85/14.PNG/file

Sorry for making me wrong in the previous comment I did not fix lmao

I appreciate your kindness and please, help me solve this problem ... Thanks: D!

**Comment by peppy** [comment]
Please do not open multiple issues.

Is your windows 64 bit?

**Comment by BitZGD** [comment]
yes

**Comment by BitZGD** [comment]
I also have the updated NET and the C ++

**Comment by BitZGD** [comment]
;3;

**Comment by peppy** [comment]
kindly fuck off
