### ISSUE TITLE
osu! lazer freezing when changing scrolling speed

### ISSUE THREAD

**Issue by Pixelfaust** [ppy/osu#4664]
**Issue**
osu! lazer is freezing for a couple of seconds when changing the scrolling speed for osu! mania.

**Video**
https://youtu.be/TTwSpN298R4

**osu!lazer version**
2019.418.0 

**Logs ** 
[performance.log](https://github.com/ppy/osu/files/3103523/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3103524/runtime.log)

**Comment by peppy** [comment]
Can you please include a link to the beatmap you are testing with?

**Comment by LastExceed** [comment]
[beatmap link](https://osu.ppy.sh/beatmapsets/324369#mania/724634)

**Comment by DCNick3** [comment]
Freezes are there if you use slider in settings too
