### ISSUE TITLE
Flashlight should expand and contract for lead-in and break times

### ISSUE THREAD

**Issue by nyquillerium** [ppy/osu#4666]
In stable, when entering a break with flashlight mod, the flashlight area expands when entering the break and contracts when gameplay resumes. This is not currently implemented.

**Comment by Flaviu1817** [comment]
I seen there are some problems when having AP on. On the map I tested the flashlight would fade in and out much faster than setted `breakPeriod.StartTime + FLASHLIGHT_FADE_DURATION` and `breakPeriod.EndTime - FLASHLIGHT_FADE_DURATION` (around 2 times faster, ~ 15 secs earlier), and without AP, it was around 2 seconds earlier, but this one may be just an intended behaviour.
