### ISSUE TITLE
Lead-in time for many (all?) beatmaps is way too short

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#4670]
**Describe the bug:** The lead-in time of any beatmap before the actual circles start to appear seems to be way shorter than it should be. This does not occur on the latest release 2019.418.0, but it does on current master. Although I believe this is not an issue for all maps, here are two that I used in the video below: https://osu.ppy.sh/beatmapsets/678213#osu/1434103 and https://osu.ppy.sh/beatmapsets/358679#osu/788662.

**Screenshots or videos showing encountered issue:** https://streamable.com/xprgl

**osu!lazer version:** master / 3bfd2a4d2f83f821468152fe75ac569dfd1815a0

**Comment by RonnieMoir** [comment]
Caused by this change https://github.com/ppy/osu/commit/55c5ef898d2cba265b877bf1d4a5195a1b14c6bc
