### ISSUE TITLE
Two beatmaps with the same BeatmapID can't be imported

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#4683]
**Describe the bug:** When two beatmaps are imported that share the same BeatmapID (e.g. an old version of a now ranked map) and are imported, osu!lazer will only import the last one and seemingly deleted the other one. This can be reproduced the following way:
1. Import [Egor Nuts - I'm getting married to an anime girl.zip](https://github.com/ppy/osu/files/3122736/Egor.Nuts.-.I.m.getting.married.to.an.anime.girl.zip).
2. Import [Egor Nats - Ya zhenyus' na devochke iz anime.zip](https://github.com/ppy/osu/files/3122734/Egor.Nats.-.Ya.zhenyus.na.devochke.iz.anime.zip).
3. Check which map still exists in song select.

I can't really read the log that well, but it should look like this: [database.log](https://github.com/ppy/osu/files/3122742/database.log). It seems to have some issues importing the maps, but in-game there is no error shown.

**osu!lazer version:** 2019.418.0

**Comment by peppy** [comment]
Is your expectation here that you can have both existing harmoniously?

**Comment by Morilli** [comment]
Yes, because it works that way in stable too. I also believed that at one point in time it was possible to import (and have) both beatmapsets at the same time, but I couldn't reproduce that on any older release.

**Comment by peppy** [comment]
This will require some further thinking. Probably a user interaction to give them the choice of replacing, skipping or duplicating.

**Comment by peppy** [comment]
This scenario now works. The first import will keep its beatmap IDs while the second will see the first and dissociate from them during import.

**Comment by idkman2021** [comment]
this is still the case (for beatmapid set to 0 as well so idk how to import generated beatmaps now like what am i supposed to put into the beatmapid)

**Comment by peppy** [comment]
Please provide the two beatmaps you are seeing issue with.

**Comment by idkman2021** [comment]
they ah_d the sane file na_mes so *th**eu  had th**e sme fu they had the same filenames and osu took the `last` one e.g. one was song1/easy.osz naother another one was song2/easy.o`sz so osu m`ergend them into 1

**Comment by frenzibyte** [comment]
Please attach a link to those two beatmaps, there's nothing to take from your comment.
