### ISSUE TITLE
Alt-tabbing pauses instantly

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#4685]
**Describe the bug:** The game pauses instantly on alt-tabbing, which is generally intended behavior. Yet currently (as per #3686) there is a 1 second delay between starting to hold the esc key and the pause menu coming up. Using alt-tab this delay can be completely avoided, which is probably not how it should be.

**osu!lazer version:** 2019.418.0

**Comment by flashwave** [comment]
it'd be neat if the delay were scrapped entirely for the escape key, it's very annoying when you're playing a long map and wanna take a quick break

**Comment by LastExceed** [comment]
@flashwave I think stamina abuse is precisely the reason why it got introduced

**Comment by flashwave** [comment]
that's absolutely ridiculous, but if you say so
