### ISSUE TITLE
Convert PP Leaderboards For osu!catch, taiko and mania

### ISSUE THREAD

**Issue by Kurtsi** [ppy/osu#4687]
Leaderboards for convert pp for osu!catch, taiko and mania. There is big difference between playing specific maps and convert maps so they attract very different players and playstyles. Here's an example from osu!catch players making their own leaderboard for convert pp (this leaderboard is only manually updated and doesn't include any scores outside of top 100 scores on the convert map leaderboard):

https://pakachan.github.io/osustuff/ppconvert.html

**Comment by peppy** [comment]
I don't think this is the correct place for this to exist. I guess osu-web, but it seems like a strange idea (maybe something which could be done via the new lazer multiplayer instead?).
