### ISSUE TITLE
osu! Lazer randomly crashes after 10 minutes of usage

### ISSUE THREAD

**Issue by FaizKTG** [ppy/osu#4688]
**describe your problem:**
whenever I use osu lazer for more than 10 minutes, it just randomly crashes with an error saying ".NET core Host has crashed, a problem has caused the program to crash..."

![Capture](https://user-images.githubusercontent.com/49793233/56868284-499f0c00-69e8-11e9-84f0-fe3ae7be6021.PNG)

**osu!lazer version:** 
local build

**logs:**
[runtime.log](https://github.com/ppy/osu/files/3125318/runtime.log)

**specs:**
cpu: intel i3-2328M
system type: 32 bit system, 64 bit type processor
ram: 4gb
graphics card: Intel HD 3000

**Comment by peppy** [comment]
It looks like your GPU is completely out of memory (not a good sign).

**Comment by smoogipoo** [comment]
This looks to be RAM-related, not VRAM. Vertex buffers aren't created at construction point, where this seems to be failing.

@FaizKTG can you check osu!lazer's RAM usage near to the crash?

**Comment by FaizKTG** [comment]
yeah of course, here:
![ram](https://user-images.githubusercontent.com/49793233/57094754-2f776d80-6d09-11e9-8b57-04a56e96a974.PNG)
the ram usage is: 2.30 GB. 

sorry for responding late.

**Comment by Joehuu** [comment]
Probably alleviated with pooling of carousel and hit objects, closing.
