### ISSUE TITLE
ScoreV1 and submiting support

### ISSUE THREAD

**Issue by byDave251** [ppy/osu#4689]
**Describe the new feature:** 
Player should be able to turn on ScoreV1 which is used in current client which would allow score submiting. Players should be also able to rank up with this feature.

**Proposal designs of the feature:** 
ScoreV1 should be added as a switch in settings or as a mod and score submition will be turned on automatically.

Edit: If approved, I'd love to give a small bounty on this (if I knew how).

**Comment by peppy** [comment]
scoring display is already a toggle in settings. "v1" scoring is likely not a thing coming to lazer, nor a current focus.

**Comment by byDave251** [comment]
@peppy Can I ask why?

**Comment by peppy** [comment]
Because we don't plan on using that scoring algorithm going forward.
