### ISSUE TITLE
osu!Lazer code "Fails" to load

### ISSUE THREAD

**Issue by ProgrammingCatss** [ppy/osu#4692]
when i open the osu!Lazer Source Code on Visual Studio 2019 it always "Fails" to load.
https://prnt.sc/nj4lxv
i'm just gonna report this and wait until it gets fixed.

**Comment by peppy** [comment]
This is an issue with your configuration. I'd suggest you look into this yourself and follow the readme, or reopen the issue with more details on what error you are getting.

**Comment by ProgrammingCatss** [comment]
ok thanks
