### ISSUE TITLE
Optimize osu!lazer performance

### ISSUE THREAD

**Issue by xKeksbyte** [ppy/osu#4695]
In the normal osu! i have on stream maps etc over 240FPS And on Osu!Lazer about 40-70
Looks pretty laggy, When i stream i had on osu! still 240 fps and on Osu!Lazer about 15-30fps

I would be very happy when this is getting fixed lol

PC:
CPU: Intel core i7-2630QM
Ram: 8gb ddr4 corsair
Graphic card: gtx 660 ti (because i just play games like osu)

- sorry for bad english i am german xd

**Comment by Tsubajashi** [comment]
Its literally Work in Progress. at first, there will be adding features. After every Feature is in the game, optimizing for every platform will be a thing.

**Comment by smoogipoo** [comment]
Performance is a constant work in progress, but is not the only thing we're setting our sights on, as previously mentioned.
