### ISSUE TITLE
Spamming enter from main menu kinda breaks stuff.

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#4697]
When spamming the enter button from the main menu osu!lazer throws an error and also the osu!logo does not move off the text. (in song area)

https://i.imgur.com/mCJHDnK.gifv

2019.502.0 Development Build

**Comment by LastExceed** [comment]
the video you uploaded seems to be broken so I recorded it myself:
https://streamable.com/i17ij

This bug appears when transitioning
**main menu -> song selection -> loading a beatmap**
 too fast, either by spamming the enter key but also when using spacebar or even clicking (if you manage to aim that fast).
> the osu!logo does not move off the text

When everything goes right: ![](https://puu.sh/DmRed/3645cfa745.png)

When transitioning too fast: ![](https://puu.sh/DmRfd/04460b64b9.png)

I don't think it's relevant, but just in case: [beatmap link](https://osu.ppy.sh/beatmapsets/189224#mania/450928)

**Comment by peppy** [comment]
@nyquillerium

**Comment by Hubza** [comment]
Right yes, imgur sometimes does that to my gifs.
