### ISSUE TITLE
big fall of fps at beatmaps launches

### ISSUE THREAD

**Issue by Tamanegy** [ppy/osu#4699]
almost everything is in the title, at the launch of the beatmaps my fps decends to 2 or 4 then goes back to 120.

I know that there are already open issues about it but my problem is still not settling

**Comment by iiSaLMaN** [comment]
Can you please give us your specs such as CPU, GPU, etc...

**Comment by Tamanegy** [comment]
gpu : gti 1050
cpu : intel core i5 7th gen

**Comment by iiSaLMaN** [comment]
Does that issue occurs on **every beatmap** or long beatmaps or beatmaps with heavy storyboards? and please attach the log files, you can find them at `%appdata%\osu\logs` if you're using windows

**Comment by Tamanegy** [comment]
it does it on all beatmaps, I want to send them to you but there are many, so I'll send them all to you
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3138744/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3138745/runtime.log)
[database.log](https://github.com/ppy/osu/files/3138746/database.log)
[network.log](https://github.com/ppy/osu/files/3138747/network.log)
[performance.log](https://github.com/ppy/osu/files/3138748/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3138749/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3138750/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3138751/performance-gamethread.input.log)

**Comment by Tamanegy** [comment]
so ?

**Comment by iiSaLMaN** [comment]
I'm not sure what the problem is, try playing without perfomance log and log overlay turned on and see if the issues still occurs

**Comment by Tamanegy** [comment]
how to activate log overlay and deactivate performance log ?

**Comment by Game4all** [comment]
Toggle for Log Overlay is CTRL + F10
Toggle for Performance Overlay is CTRL + F11

**Comment by iiSaLMaN** [comment]
@Tamanegy i meant to disable all of them

**Comment by Tamanegy** [comment]
[2019-05-02-1755-47.zip](https://github.com/ppy/osu/files/3138886/2019-05-02-1755-47.zip)

**Comment by iiSaLMaN** [comment]
I don't see any huge drops, is it working now..?

**Comment by Tamanegy** [comment]
nop

**Comment by iiSaLMaN** [comment]
Can you please describe exactly where does your issue occur...

**Comment by Tamanegy** [comment]
when the beatmap starting
