### ISSUE TITLE
osu!direct is free

### ISSUE THREAD

**Issue by yousef157** [ppy/osu#4702]
I'm not an osu!supporter (I wish I was) but osu!direct in osu!lazer is free?
Like, wtf?

I have not tried if it's also free while not logged in, but, like, why is it free when i'm not an osu!supporter?
Is it intentionally free?

**Comment by peppy** [comment]
This is intentional, yes.

**Comment by cainy-a** [comment]
> 
> 
> This is intentional, yes.

wait really?!?!? thanks!

**Comment by torskyy** [comment]
@peppy when osu!lazer will be osu!stable, will it still have the osu!direct thing for free?

**Comment by bdach** [comment]
@torskyy see [this comment on the official lazer FAQ blogpost](https://blog.ppy.sh/a-definitive-lazer-faq/#comment-606).

**Comment by torskyy** [comment]
> @torskyy see [this comment on the official lazer FAQ blogpost](https://blog.ppy.sh/a-definitive-lazer-faq/#comment-606).

oh ok, thanks
