### ISSUE TITLE
osu!mania random mod

### ISSUE THREAD

**Issue by johnmwu** [ppy/osu#4708]
**Describe the new feature:** Is random mod coming to o!m? AFAIK, it was one of the most popular mods for training in the original.

**Comment by Gabixel** [comment]
I guess it's already implemented (or planned, I don't know). As you can see, the Random Mod is included in the mod list: 
![Random Mod](https://user-images.githubusercontent.com/43073074/57185892-f55ac700-6ed4-11e9-8c97-d82c352c2f8e.png)

**Comment by peppy** [comment]
Already implemented (scroll down on mods). Please elaborate if you feel the current implementation is lacking in some way.
