### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by JSR-Gaming-x** [ppy/osu#4711]
I found out what has been causing the login error on macOS for many users including me, and a work-around.

I found out what the problem is. I recently tried logging in with my username to see if it would work, and I couldn't type any capitals. Then it hit me, this whole time i couldn't see the password because it is hidden, but it was all lowercase, and since I couldn't type the capital in my password it wouldn't work. I just had to change my password to all lowercase.

Work-Around:

1. Login to osu.ppy.sh, click your profile, and click settings.
2. Scroll down till you see change password and change it from there.
3. Make sure you have your password at least 8 characters or else it won't save.
4. If the password saves correctly, it will say "saved" in green.
5. Login to osu!lazer.

**Comment by peppy** [comment]
Typing capitals works fine here. What version of macOS are you on, and do you have any custom apps installed which could be interfering with keyboard input?

**Comment by JSR-Gaming-x** [comment]
I'm on macOS High Sierra 10.13.6, and I've also tested it on macOS Mojave with the same luck. I can test it on any version of macOS you want I'm a nerd with a crap ton of drives and installers. I use karabiner elements for key mapping, but caps works everywhere but osu!, and with it disabled I still have the same issues. There have been multiple threads about login not working on macOS so maybe their capitals aren't working. I will try to go back to the old threads and ask them if they can type capitals to see if my issue is isolated.

**Comment by peppy** [comment]
Wait, are we talking caps lock key specifically? I have not tested that, only shift.

Also please confirm whether copying and pasting text works correctly.

**Comment by JSR-Gaming-x** [comment]
Wow, intresting, I can paste capitals, and holding shift works (I didn't know that was a thing), but caps lock does not work.

**Comment by peppy** [comment]
Framework issue.
