### ISSUE TITLE
Cant unpause game due to "click orange cursor" popup

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#4715]
Was playing a map, in a break i alt tabbed to another window and came back,
https://i.imgur.com/ne5jHQ5.png
As shown here, the orange cursor popup is going under the break overlay and the orange cursor is nowhere to be found, i luckily was recording when this happened but had to blur a few things in the alt tabbed window

Video can be found [here.](https://youtu.be/BzevLwlq0-k)

2019.504.0

This seems to be a pretty bad bug, lets say your in a middle of a really big map and theres a break and you alt tab, you cant continue the map to get that pp you were so close to getting.

**Comment by LastExceed** [comment]
I've tried reproducing this for a while with no success. can you give us some more info?
- beatmap link
- input device (mouse/tablet)
- window mode (windowed/borderless/fullscreen)
- number of monitors and their arrangement (if its more than 1)

**Comment by Hubza** [comment]
I dont remember the beatmap.

Tablet and Keyboard (Huion H420, Trust Wireless Keyboard)
1 Monitor (4:3 1280x1024)
Borderless

@LastExceed

**Comment by Joehuu** [comment]
Fixed in #4607.

**Comment by peppy** [comment]
I don't believe it was, as this was reported one month after that issue was closed.

**Comment by Joehuu** [comment]
You should be seeing the date the PR was merged (5/12).

That PR made it impossible for click to resume to happen during breaks.

**Comment by peppy** [comment]
Haven't heard it reported again recently, so let's hope for the best then :).
