### ISSUE TITLE
osu!lazer wont open

### ISSUE THREAD

**Issue by maks418** [ppy/osu#4725]
**Describe the crash:** 

after launching the game, nothing appears (even an error window).
Nothing happens

**Screenshots or videos showing encountered issue:** 

I don't know how to show it, nothing happens.

**osu!lazer version:** 
 
2018.1228.0

**Logs:** 

Everything I found in the folder in the logs:
[runtime.log](https://github.com/ppy/osu/files/3151889/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/3151890/update_success.log)

**Computer Specifications:** 

[DxDiag.txt](https://github.com/ppy/osu/files/3151904/DxDiag.txt)

**Comment by maks418** [comment]
I use windows 7 basic, well, at the expense of the download, I could not find where to download it except github (yes, I’m so dumb) with the hitb htb downloaded install.exe and I installed this version :\

(I apologize for not writing for so long)

**Comment by peppy** [comment]
I think those logs are from an `osu-stable` installation. Could you check `AppData/Roaming/osu/Logs` instead?

**Comment by maks418** [comment]
on the way AppData / Roaming there is nothing even similar (unless osu!Lazer)
![H8W9BbU](https://user-images.githubusercontent.com/40042551/57474068-17788e80-72b3-11e9-8622-6c8a39520f80.png)

**Comment by smoogipoo** [comment]
Make sure you have the prerequisites for .NET Core installed, as described [here](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x).

Specifically, you need https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows and https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot.

**Comment by maks418** [comment]
Initially, it wasn’t serious, because the installation (or the .NET update) rarely helped. But I decided to try, and it worked! 
Thank you for your help.
