### ISSUE TITLE
Login crash

### ISSUE THREAD

**Issue by rayenraad** [ppy/osu#4737]
When i click cancel while the game attempting to connect the game crashes.
**osu!lazer version:** osu!lazer 2019.508.0
![Untitled](https://user-images.githubusercontent.com/50429684/57419984-04a38280-71fd-11e9-82d3-499e4fcfccd6.png)

**Comment by peppy** [comment]
Could you please provide your runtime.log after this crash happens?

**Comment by rayenraad** [comment]
**Log files**
[runtime.log](https://github.com/ppy/osu/files/3159844/runtime.log)
[network.log](https://github.com/ppy/osu/files/3159845/network.log)

**Comment by rayenraad** [comment]
i tried to login again
[runtime.log](https://github.com/ppy/osu/files/3159849/runtime.log)

**Comment by peppy** [comment]
Unfortunately the exception isn't in either of those logs. Please try and make the game outright crash and then post again.

**Comment by rayenraad** [comment]
Signing out crashes the game.
I think it did catch logs this time.
[runtime.log](https://github.com/ppy/osu/files/3160254/runtime.log)
Cancel button crashes the game immediately maybe that's why it did not catch logs.
