### ISSUE TITLE
Taiko skipping bugs map

### ISSUE THREAD

**Issue by takoz53** [ppy/osu#4740]
**Bug:**
I made a short version of Raise my sword at the hard part to play and train it. I tried it in taiko (converted map), but after skipping, the game seems to speed up the playfield (as if it is trying to catch up to the part where I skipped to). From there on, the notes are invisible and FPS drops are occuring (probably due to the very fast scrolling speed?). The FPS drops average at ~5FPS. 
**Video:**
https://puu.sh/DpO5V/5a9a684329.flv
**osu!lazer version:** 
2019.508.0, Development build.
**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3160182/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3160183/runtime.log)

**Comment by peppy** [comment]
Could you please link the beatmap?

**Comment by takoz53** [comment]
https://puu.sh/DpONH/decf77db52.osz

**Comment by peppy** [comment]
Reproduced, thanks!
