### ISSUE TITLE
Discord Overlay crashing the game when resizing the window

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#4741]
Reported by @gabixel in #4517:

> Perhaps what I said was misunderstood @Aergwyn (watch this as reference: https://streamable.com/34s9r):

> With Discord Overlay disabled Lazer never crash, but it snaps to a certain value when resizing the window (like you said). Instead, with the Overlay enabled, there's like an 80% chance that Lazer will crash (and like a 10% that the UI becomes invisible and glitchy, but that's not the case with the previous video) when resizing the window.
So I guess the main issue is the first one (your one) and, if this framework-level issue will be fixed, the conflict with the Discord Overlay should automagically disappear (that's why I reported this here and not with a new issue).

**Comment by Joehuu** [comment]
Seems to be fixed in SDL.

**Comment by Joehuu** [comment]
Fixed in SDL as of now.
