### ISSUE TITLE
ScoreProcessor judgement counts factor in various hitobjects incorrectly

### ISSUE THREAD

**Issue by nyquillerium** [ppy/osu#4747]
Split out from https://github.com/ppy/osu/issues/4597

Currently, various objects that should not be counted towards great/perfect judgements are done so anyway. They tend to coincide with the objects that override `Judgement.AffectsCombo`, of which a list of can be found here:

* CatchBananaJudgement (Should not be added)
* CatchTinyDropletJudgement (Should not be added)
* HoldNoteJudgement (Handled by base note judgement)
* HoldNoteTickJudgement (Should not be added)
* OsuSliderTailJudgement (Handled by base slider judgement)
* TaikoDrumRollJudgement (should not be added)
* TaikoDrumRollTickJudgement (should not be added)
* TaikoStrongJudgement (handled by base judgement)
* TaikoSwellJudgement (should not be added)
* TaikoSwellTickJudgement (should not be added)

**Comment by smoogipoo** [comment]
Adding to this our discussion from before/today:

`HitResult` should have 4 more types: `SmallBonus`, `LargeBonus`, `SmallTick`, `LargeTick`, which most of these will fall under.
This'll also help address catch's ticks + pp calculation.

To handle supplementary judgements (e.g. `SliderTailJudgement`), I think we'll need a property somewhere - maybe just a `IncreaseCount` bool at `Judgement` level or something like that.

**Comment by smoogipoo** [comment]
Putting this on the back-burner for now since it's a very big task. A few critical systems need to be considered here:

1. Database / API
2. Interaction with the `ScoreInfo.Statistics` dictionary, profiles, results, etc.
3. Ordering of enum members, maybe not having it as part of the enum at all.

**Comment by nyquillerium** [comment]
We're shelving this for now, but just a note that this will eventually also need `SmallBonusMiss`, `LargeBonusMiss`, `SmallTickMiss`, `LargeTickMiss`. This is required to distinguish from normal miss counts, as well as potentially needed for whatever performance/scoring related stuff we may need.

**Comment by smoogipoo** [comment]
Judgements have since been simplified and this has been resolved.
