### ISSUE TITLE
Rank icons missing (Player Info)

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#4749]
Rank icons? (i think thats what they're called, like the S and stuff) are missing in the player info. 
https://i.imgur.com/mSn7C6v.png

2019.508.0

Windows 10 Pro Insider

also, they're the old rank style might wanna fix that

**Comment by Gabixel** [comment]
Already fixed with https://github.com/ppy/osu/pull/4733, you have to wait for the next release to see the changes.

**Comment by Hubza** [comment]
was looking for an issue of this, must have been dumb and forgot to check closed ones
