### ISSUE TITLE
Cutting Edge: Target Practice on Some Unsubmitted Maps Crashes osu!

### ISSUE THREAD

**Issue by stageosu** [ppy/osu#4758]
**Describe the crash:** When attempting to play target practice, on most unsubmitted maps, there is an infinite loading screen as shown below that you cannot back out of without force quitting osu!.

**Screenshots or videos showing encountered issue:** https://streamable.com/dt95f

**osu!lazer version:** N/A...osu!cuttingedge (20190511.1)

**Logs:** None.

**Computer Specifications:** AMD Ryzen 5 2600, GTX 1080Ti, 32GB DDR4 RAM.

**Comment by Game4all** [comment]
This repository only tracks issues for the lazer client

**Comment by stageosu** [comment]
My mistake then, thanks.
