### ISSUE TITLE
Figure out mod application

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#476]
Mods should:
- [x] Have access to _everything_ inside the playfield, including the HitObjects.
- [x] Should be able to be applied/removed at will.
- [x] Should be able to be stored in such a way that they can be referenced in places such as mod selection.
- [ ] Should be able to be applied/referenced in DifficultyCalculator.

To follow up with a discussion that occurred 2017/03/13: Mod currently has an Apply<T> method, but there is currently no way to remove a mod. The plan is to re-initialize the internals of HitRenderer (including the base converted HitObjects) when a mod is applied.

**Comment by peppy** [comment]
Marking off point 2 as we have decided that removal is not going to be a thing.
