### ISSUE TITLE
No osu!lazer sound

### ISSUE THREAD

**Issue by MalyKulek** [ppy/osu#4766]
No osu!lazer sound

I cant show at image sound issue

osu!lazer version: 2019.510.00 DEVELOPMENT BUILD

[database.log](https://github.com/ppy/osu/files/3170287/database.log)
[network.log](https://github.com/ppy/osu/files/3170288/network.log)
[performance.log](https://github.com/ppy/osu/files/3170290/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3170292/runtime.log)

**Comment by peppy** [comment]
Have you tried changing outputs in options? Also rolling mouse wheel up to increase volume?

**Comment by MalyKulek** [comment]
Yes, I tried to do it but nothing happened

**Comment by HoutarouOreki** [comment]
Check if you haven't muted lazer in the volume mixer
![image](https://user-images.githubusercontent.com/16261733/57628079-86970100-7599-11e9-86f6-cc5377880aa0.png)

**Comment by MalyKulek** [comment]
I tried to look at volume mixer but there was not osu!lazer

**Comment by MalyKulek** [comment]
I know what is the problem, but I dont know how to fix it

Look

**Comment by MalyKulek** [comment]
osu!lazer is at secound speakers but I have only one speaker set

**Comment by MalyKulek** [comment]
![obraz](https://user-images.githubusercontent.com/50551826/57632130-2efc9380-75a1-11e9-8e1d-14ac162a60dd.png)

**Comment by MalyKulek** [comment]
> gfffgd
