### ISSUE TITLE
Lazy Flashlight mod

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ppy/osu#4772]
**Describe the new feature:** With PR #4771, the Flashlight texture has a slight movement smoothing delay when following the cursor. When turning this delay up, the flashlight texture more noticeably "lags behind" the cursor. This makes the game harder and could serve as a fun mod.

**Proposal designs of the feature:** 
The delay of the movement could either be constant or scale with the current combo. It would be placed behind the current flashlight mod and would give a slightly higher score multiplier. This could work for both standard and Catch.

Here's a video with 1200ms of smoothing (10x the default value) to give an idea: 
[Video](https://www.youtube.com/watch?v=ol64L4J55As)

**Comment by LeNitrous** [comment]
Would be cool if the cursor was above the flashlight itself.

**Comment by peppy** [comment]
I think that spoils the effect a bit?

**Comment by smoogipoo** [comment]
Definitely sounds like a fun idea when mod settings get implemented (rather than a whole new mod altogether).
