### ISSUE TITLE
Button is clickable outside of the button itself

### ISSUE THREAD

**Issue by BlauFx** [ppy/osu#4778]
**Describe the bug:** Button is clickable outside of the button itself

**Screenshots or videos showing encountered issue:** https://streamable.com/cm1n8

**osu!lazer version:** 2019.510.0

**Logs:** /

**Comment by peppy** [comment]
This is by design, as with the checkboxes in options being clickable anywhere on the row etc.

**Comment by BlauFx** [comment]
No it's not an actual issue but it should be fixed someday.

**Comment by peppy** [comment]
I think in general this is the direction we want to go, to allow accessibility via touch platforms etc.

Don't see this as an issue for now.
