### ISSUE TITLE
Results statistics overflows the inner circle

### ISSUE THREAD

**Issue by TheNikku** [ppy/osu#4791]
**Describe the bug:** 

Tiny issue but in this screen I can't quite see all the numbers.
most noticeable with the word 'Great' and 'Miss'.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/50621709/57693711-3f8a3800-768d-11e9-967f-b439d4703ed9.png)

**osu!lazer version:** 
2019.510.0

**Logs:**

**Comment by Gabixel** [comment]
I think that the score doesn't scale based on resolution. This is more noticeable when resizing the UI:
![Screen1](https://user-images.githubusercontent.com/43073074/57712933-cb8e6680-7671-11e9-9b70-6606ce897bf2.png)
![Screen2](https://user-images.githubusercontent.com/43073074/57713088-13ad8900-7672-11e9-9932-ffb4889fc04a.png)

**Comment by peppy** [comment]
It is based on "resolution", as in it's the same at all resolutions (as everything else is in lazer).

The results screen is going to see a complete redesign, but a temporary fix could be applied by reducing vertical spacing for the time being (or increasing the circle size, maybe).

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu/pull/8311.
