### ISSUE TITLE
Cant scroll using click

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#4793]
In the song select, the scrollbar on the right is going behind an overlay, i cant click it - it also goes under the osu! cookie

https://i.imgur.com/ENTj42W.png

I'm running a local debug, cloned today, but same bug is on 2019.514.0

**Comment by smoogipoo** [comment]
Will probably be fixed when we have new designs from flyte.

**Comment by Joehuu** [comment]
Duplicate of #2241.
