### ISSUE TITLE
Replays rewind right after a beatmap ends

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu#4799]
**Describe the bug:** Beatmaps with audio files that end immediately causes unwanted replay player behavior. Beatmap: https://osu.ppy.sh/beatmapsets/193980
![image](https://user-images.githubusercontent.com/20495991/57745222-e2c76580-76fe-11e9-9078-885537c8fd39.png)

**Screenshots or videos showing encountered issue:** https://streamable.com/3jo6n

**osu!lazer version:** 2019.514.0

**Logs:** N/A

**Comment by iiSaLMaN** [comment]
Duplicate of #4705

**Comment by LeNitrous** [comment]
Closing. I'll move over the solution to that issue.
