### ISSUE TITLE
Number text isnt centered (hitcircle)

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#4803]
The text on the hitcircle is 2px off on the Y axis, CS4.2 1280x1024

![image](https://user-images.githubusercontent.com/33783503/57789332-9bf26380-7730-11e9-9952-2e3b5dfc3a6d.png)

2019.514.0

**Comment by Hubza** [comment]
yes, i pay very close attention to these things, im mad for correct centering

**Comment by peppy** [comment]
This is likely the case with all fonts (at the generation end). Might be related to why the loading sprite is also not centered.

**Comment by Joehuu** [comment]
@Hubza can you do that test again on the recent release?

**Comment by Hubza** [comment]
![image](https://user-images.githubusercontent.com/33783503/64992237-62db2300-d8cb-11e9-9d42-b0b6fd3e68da.png)
@Joehuu same issue on latest release, same CS and Resolution (dont ask me why its bigger)

2019.913.0

**Comment by peppy** [comment]
This is specific to the font being used (and likely the metrics contained by it being incorrect). It can be observed that on skinned hit circles the alignment is correct.

As this is only off by one pixel I do not see it being a huge issue.
