### ISSUE TITLE
Add ability to skin/move the HP bar

### ISSUE THREAD

**Issue by vrii** [ppy/osu#4805]
I haven't been here long, and from first impressions (about 10 minutes of playing), I think the performance meter (the bar along the top) should have, perhaps, a scaling option? I much prefer the performance meters of classic osu!, and if this is the future of osu!, I would at least personally appreciate (as I'm not sure of the rest of the community's opinion) an option to revert it to the classic top-left-only bar if so inclined. The high sensitivity of the bar on maps with an hp over 6.5 and its erratic motions easily distract from the gameplay itself, and it even feels inaccurate at times. Thanks! 
-Arya-

**Comment by peppy** [comment]
This is going to be a skinnable feature.

**Comment by Joehuu** [comment]
Gonna track this in https://github.com/ppy/osu/issues/4632.
