### ISSUE TITLE
Add audio fade in/out transition when window becomes active or inactive

### ISSUE THREAD

**Issue by ddasutein** [ppy/osu#4806]
The old osu client had some sort of fade in, fade out effect when the window becomes inactive or active. In osu!lazer, since you have the ability to change the inactive volume, if the Master volume is set to 100% and the inactive volume set to maybe 30% or less, it can be jarring to hear the music blast at your ears when the window becomes active again. It would be easier on the ears to have a smoother audio transition between inactive and active window.

**Comment by peppy** [comment]
Dependent on https://github.com/ppy/osu-framework/pull/2396

**Comment by Joehuu** [comment]
The PR only did the transition when active -> inactive which is nice, but the original issue also wanted a transition when inactive -> active.

**Comment by someDerpyPineapple** [comment]
I think there's a brief inactive-to-active transition - here's an audio waveform I recorded in audacity, where i tabbed in and out of lazer and stable. Both were playing songs at the song select screen. 

(left is lazer recording, right is stable recording, red markings denote transitions)
![image](https://user-images.githubusercontent.com/43484729/94897389-5e38cc80-0444-11eb-83e9-7abf495cd574.png)

_However,_ I still find the inactive-to-active transition to be too short. As OP stated, inactive volume can be set much lower in lazer, so the volume can change much more dramatically compared to stable. Are there any plans to allow players to control the audio fade-in speed, or possibly vary the fade-in speed based on the difference between inactive and active volume?

If nothing else, I guess the short fade-in wakes me up, lol.

**Comment by peppy** [comment]
I'm pretty happy with how it feels currently.
