### ISSUE TITLE
osu!visualizer should react to volume strength.

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#4807]
The osu!logo’s visualizer should react to the volume. For example, when the master volume is at 50%, the visualizer will only do 50% of it, and when it’s in 0%, the visualizer won’t react at all.

**Comment by BlauFx** [comment]
But this feature should be in the settings to enable/disable it

**Comment by dscnnctd** [comment]
>But this feature should be in the settings to enable/disable it

@BlauFx - Not really, this will not affect anything at all, only the visualizer. I disagree that this should be an **on and off** feature since it will only affect the visualizer.

**Comment by Hubza** [comment]
I like the idea of this, if i have my volume at 0 the visuallizer shouldnt be doing anything, atleast thats how i think a visuallizer should work anyway.

**Comment by peppy** [comment]
Checking other apps with build-in visualisers, this goes contrary to expectations (music players keep the visualisation running at a constant level regardless of output volume – they are operating on the data stream, not the output to speakers).

That said, I'm not necessarily against this if it is decided it feels better.

**Comment by aspriddell** [comment]
I'm happy to be assigned this (as I have already started the pull request).
In my opinion, I think it does feel better and gives a nice touch to the volume strength.

**Comment by peppy** [comment]
As discussed in the PR, this direction doesn't feel correct.
