### ISSUE TITLE
Add notification toasts

### ISSUE THREAD

**Issue by toiglak** [ppy/osu#4811]
_Well, I don't know is there any design ready (if there is, you can put it here) for that little dude (below) so i post my crappy proposal._

![Untitled](https://user-images.githubusercontent.com/37531387/57868492-623e5d00-7803-11e9-9b01-0dc904ebcb24.png)

**Proposal** 
It is based on a new lazer design... still... it's poor:
![message](https://user-images.githubusercontent.com/37531387/57870092-b0a12b00-7806-11e9-91be-1c3ab563ed89.gif)
Notification could be shown in top-right corner while playing. 

**Design may also work with different icons:**
![info](https://user-images.githubusercontent.com/37531387/57870462-6f5d4b00-7807-11e9-8efe-ee29c6e15f52.png) ![direct](https://user-images.githubusercontent.com/37531387/57870464-6f5d4b00-7807-11e9-9e74-2dd55d8cd6a6.png) ![accept — kopia](https://user-images.githubusercontent.com/37531387/57870537-9ca9f900-7807-11e9-8507-82c053ec2216.png)

**More old-osu!-like style:**
![design2](https://user-images.githubusercontent.com/37531387/57871006-ae3fd080-7808-11e9-9b53-a75545cf9ad0.png)
_edit:_ Yet another idea: https://youtu.be/pjHQSG_0_6k

_So that's my idea on notification bar. Feel free to change it completely or delete it._

**Comment by ticotaco72** [comment]
I think it can be not needed, because there's indicator when you get new notification already (there's a number on notifications button), and very important notifications are force-opening the bar

**Comment by ToIGLAK** [comment]
When you're playing, it's not visible I guess. I mean I tried force notification while playing, but just it wasn't showing.

**Comment by ticotaco72** [comment]
yes, and that's fine; it discourages hitting pause button, which is unwanted behaviour last times

**Comment by ToIGLAK** [comment]
hmm, you're right, notifications aren't actually that important to interrupt your gameplay but getting a message from someone should at least play the characteristic sound of arriving.

**Comment by peppy** [comment]
Thanks for the contribution, but this is very far from our design language and does not match the notification style we are using going forward (see `osu-web`).

I'll leave this issue open as a place to discuss toast notifications when we get around to implementing that. @arflyte drop a design if you already have one.

**Comment by recapitalverb** [comment]
IMO:
Mid-game, clicking on a notification toast and clicking the "(x) hold for menu" button should do the same thing - pausing the game. Based on that I think it's better to make that button transform into a notification instead.
![image](https://user-images.githubusercontent.com/41869184/77226108-53090800-6ba8-11ea-96a7-124d3251ee88.png)
Upon notification:
![pogu](https://user-images.githubusercontent.com/41869184/77226331-15a57a00-6baa-11ea-815e-fc6af164d262.png)

**Comment by Theighlin** [comment]
Can be closed in favour of #18885
