### ISSUE TITLE
Multiplayer forces the track to play

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#4820]
Looking into being able to seek and pause tracks on certain screens I noticed that I'm not able to pause the track in the `MatchSubScreen`.
This happens because the track is forced to play each frame via the `Update` method, which it most likely shouldn't do.

**Comment by Aergwyn** [comment]
Most likely needed to be able to properly address #4599.

**Comment by AuracleTech** [comment]
Same problem here, I re-open the issue.

31 seconds debug video.
https://clips.twitch.tv/IncredulousCourteousDootSMOrc

Only happens in a room in multiplayer.
