### ISSUE TITLE
More centering issues - Mod icons arent centered

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#4825]
The mod icons are not centered, especially noticeable in the Fun mods.

https://i.imgur.com/Cwq9JOa.png

2019.518.0

**Comment by Aergwyn** [comment]
As those come from a *font* too if I'm not mistaken this is most likely a duplicate to #4803.

**Comment by Hubza** [comment]
> 
> 
> As those come from a _font_ too if I'm not mistaken this is most likely a duplicate to #4803.

They are much more uncentered though, with the numbers i had to look super close to see it but here it was instantly noticeable to me, but i think your correct there.

**Comment by peppy** [comment]
That's because the custom icons were exported to ttf/otf without much checking or thought given to the metrics, i believe.

**Comment by Hubza** [comment]
Right that makes sense, maybe an update to the ttf/otf would be required.

**Comment by nyquillerium** [comment]
This seems to be looking much better on my branch that I'm working on for resolving another issue:
![Screen Shot 2019-05-20 at 5 49 40 PM](https://user-images.githubusercontent.com/5578000/58008742-0556e580-7b28-11e9-8674-1931fccf51fa.png)

**Comment by Hubza** [comment]
That looks basically the same to me - maybe its screen resolution?

I have 1280x1024, so i dunno, all i know is its still very off center.

**Comment by nyquillerium** [comment]
The above image has only adjusted horizontal alignment. Happily, the vertical alignment was also resolved.

![Screen Shot 2019-05-21 at 3 19 19 PM](https://user-images.githubusercontent.com/5578000/58076386-10bc1680-7be5-11e9-8d48-f2f6490b34c7.png)

**Comment by Joehuu** [comment]
Fixed via #5796 and recent font changes.
