### ISSUE TITLE
Context Menu issue when it's not on screen

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4838]
**Describe the bug:** The context menu of a beatmap on the carousel behaves very weird when it goes outside of the screen:
- On the first part of the following video, the menu reappears near to the leaderboard container
- On the second part of the video, the menu seems to have the ability to scroll the carousel down infinitely

Also, I've noticed that you can reproduce it better when searching for some maps (an easy example is on the following video), not with the entire list.

**Screenshots or videos showing encountered issue:** https://streamable.com/yu2oh

**osu!lazer version:** 2019.518.0

**Logs:** N/A

**Comment by nyquillerium** [comment]
probably resolved by https://github.com/ppy/osu/pull/5709

**Comment by Joehuu** [comment]
It's still happening on beatmap carousel. Please try to reproduce before closing.

**Comment by nyquillerium** [comment]
Thanks for confirming

**Comment by Joehuu** [comment]
I think #5730 resolved all the points listed in OP.
