### ISSUE TITLE
Beatmaps not showing up 

### ISSUE THREAD

**Issue by Thepiotug** [ppy/osu#4839]
This happened like a week ago, i started osu normally, updated it, an then the beatmaps stopped showing. after i deleted osu!.db most of them would show up, but after playing they again disappeared. 
Video here: https://youtu.be/YWEO9a50waw
Edit:
I caught a softlock when loading maps
Video here: https://youtu.be/p1SbiFkFo6I

**Comment by peppy** [comment]
This is not lazer. You can try hitting F5 at song select to reload maps, though.
