### ISSUE TITLE
Cursor shake can prevent opening mapsets in the carousel 

### ISSUE THREAD

**Issue by JackLee9355** [ppy/osu#4842]
**Describe the bug:** 
Cursor shake can prevent opening mapsets in the carousel. I believe this is due it being interpreted as dragging the carousel up and down, but is present movements smaller than it should be. It happens with or without raw input enabled. This is especially prevalent on tablet where cursor shake is more common.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
osu!lazer 2019.518.0

**Logs:**

**Comment by peppy** [comment]
Are people still having this issue? We do have support to discern between drags and clicks already. If anything the tolerance need to be tweaked if users are still experiencing discomfort.

**Comment by JackLee9355** [comment]
I could no longer detect it even with a slight anti-smoothing filter on.

**Comment by peppy** [comment]
@JackLee9355 having a bit of a hard time understanding if this means the issue is fixed for you now. can you confirm everything is OK in the latest releases?

**Comment by JackLee9355** [comment]
Sorry. Yes, it is fine in the latest released. I delayed closing the issue in case others were still experiencing it.
