### ISSUE TITLE
Ability to change default UI font

### ISSUE THREAD

**Issue by lunafreya** [ppy/osu#4849]
**Describe the new feature:** 
Currently, there is no official option to change the font of the osu! UI. This issue will call for an option that will allow the player to change the UI font (Exo 2) to a font of the player's choice.

**Proposal designs of the feature:** 
The option will be implemented under the "General" or "Graphics" category, if appropriate, should the font change be global (will affect all skins). Or it can be under the "Skin" category for per-skin font setting.

The option can take the shape of either a button that says "Change font" or a dropdown that will preview the fonts available to the user's device.

**Comment by Joehuu** [comment]
Going to close this as a recent duplicate (https://github.com/ppy/osu/issues/9736) was insta-closed.
