### ISSUE TITLE
Make the multiplayer position indicator disable-able

### ISSUE THREAD

**Issue by Negaosu** [ppy/osu#4853]
**Describe the new feature:** 
Currently, although you can disable the leaderboard in multiplayer, you cannot disable the indicator in the bottom right that says what place you are in (1st/2nd/16th/etc.) My proposal is that there is an option added that allows you to disable it.

**Proposal designs of the feature:** 
It could just be in the options menu under multiplayer as an option like "Enable position indicator in multiplayer" and you could tick it or untick it.

I know that this has been requested 6 years ago and you denied it (https://osu.ppy.sh/community/forums/topics/147966) however, it has come to a point where people are able to skin this out in their skin anyway by using a black element which covers it, meaning they do not have to see it when playing tournaments as it is very distracting/can add to nerves, and because tournaments are much more relevant now than they used to be, people want to do everything they can to make sure they play their best. However, people with lower end PCs/laptops are unable to skin it out in this way because it increases lag by a considerable amount, and in interest of not being (almost) pay to win I feel like it could be a good addition to just be able to disable it.

**Comment by HoLLy-HaCKeR** [comment]
This repository is only for issues related to osu!lazer, not stable. You should use the forums for feature requests and bug reports related to stable.

**Comment by jorolf** [comment]
That being said, a checkbox for that would be a good change for osu!lazer.

**Comment by HoLLy-HaCKeR** [comment]
Since lazer doesn't have synchronous multiplayer yet, I don't think now is the time to discuss small details like that. From what I can remember, problems like this will be solved through skinning anyway.

**Comment by Negaosu** [comment]
> This repository is only for issues related to osu!lazer, not stable. You should use the forums for feature requests and bug reports related to stable.

oh sorry lol
