### ISSUE TITLE
Make TestcaseGameField work again

### ISSUE THREAD

**Issue by smoogipooo** [ppy/osu#486]
TestCaseGameField hasn't been working for a while now, broken since 02cab41d34ea4df6f1d1458c008bc904b693a244. It would be nice to get this running again.

From some preliminary testing I have gathered the following information:
* The test case shows for 1 update frame.
* The above finding may lead to a HitObject lifetime issue.
* HitObject lifetime will be reworked soon, so perhaps that will fix it.

**Comment by smoogipooo** [comment]
I'm unassigning this from Gamemode Improvements as it is no longer an immediate priority.

Seems to be some weird stuff going on with clocks, needs more investigation.

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu-framework/commit/b72bea60eb6369838f68c95e3a65fdfdd7c4098f.
