### ISSUE TITLE
Sort by date added does not work

### ISSUE THREAD

**Issue by DCNick3** [ppy/osu#4867]
**Describe the bug:** 
Even though sorting marked as done in #988, sorting by date added is somewhat wrong. At the first glance sorting by BPM and Length is somewhat wrong too.
**Screenshots or videos showing encountered issue:** 
![Screenshot_20190527_141807](https://user-images.githubusercontent.com/10363282/58416477-57e55400-808a-11e9-8985-52cdd14d3c79.png)
![Screenshot_20190527_141905](https://user-images.githubusercontent.com/10363282/58416490-6469ac80-808a-11e9-9c83-16cbb23492b6.png)

**osu!lazer version:** 
git revision 0e8517ebaedda65f1b3f30a134c911a3add99dbf
**Steps to reproduce:**
1. `rm -rf ~/.local/share/osu`
2. Download some beatmaps
3. See the sorting wrong

**Comment by peppy** [comment]
I believe this is the underlying data not being correctly populated, while the sort control itself is correct.

**Comment by welsar55** [comment]
This issue applies to sorting by BPM, date added, length, and rank achieved. None of them are implemented so the client will sort by artist instead.

**Comment by arphox** [comment]
I started inspecting this area of code and I thought I'll document some of it for others (implementors) to get started faster:

When you select a sorting criteria, the setter of `osu.Game.Screens.Select.FilterControl` class' `Sort` property will be activated, so putting a breakpoint there should help to get started debugging the issue.
