### ISSUE TITLE
Back Button on Map Load screen

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#4886]
**Describe the new feature:** 
Right now it's especially annoying if I accidentally start a map and i'd need to wait for it to load in order to go to song select.

Edit: The context is mobile.

**Proposal designs of the feature:** 
![IMG_5489](https://user-images.githubusercontent.com/50823728/58748466-b5c7d080-84bc-11e9-8c0f-598424081b8e.png)

**Comment by LeNitrous** [comment]
But you can hit escape to cancel loading? Pretty sure it should be the same for stable.

**Comment by jai-x** [comment]
On mobile where it's touchscreen only, you would not be able to press the escape button. I agree that we would need a back button to cancel loading.

**Comment by LeNitrous** [comment]
Might as well be a good QoL button since in my case for Android, my OS blocks navigational input like home and back buttons when in games.

**Comment by peppy** [comment]
The back button needs to be moved to a global level element.

**Comment by yuuiko** [comment]
back button should appear on the multi lobby too. 

Side note: Are you sure multi should be an overlay? It’s kind of jarring to use because its not consistent with the full page layout of singleplayer song select and editor...

**Comment by peppy** [comment]
It was designed as an overlay so one could browse games while still using other elements, such as solo or edit. This has yet to be fully realised, but for the time being the design remains as such.

**Comment by yuuiko** [comment]
Thing is, this would be the case if it was in the top bar, but its not and instead is treated like a game mode in the main menu. 

Plus, I don’t think that people would have the need to get into multiplayer while editing or playing solo, so thats a bit questionable to me.

Current design is understandable from your comment, but i’d advise to reconsider. If you want to keep as is, add a multi button to the top menu, but as the design is not final and you may have plans I’m not aware about, I’ll see what happens in the end.

**Comment by peppy** [comment]
It was intended to be in a global bar. As I said, this is not yet raelised.
