### ISSUE TITLE
Adjust Circle Size for Mobile / Add "Bigger CS" Mod 

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#4888]
**Describe the new feature:** 
CS for standard is a bit small for phones. Is it legal for ranking to add say 3-5 to the CS of a map if played on a phone?

Otherwise a “Big” mod could be added behind easy, which does the above.

Sorry if this is a duplicate, I accidently pressed enter at the title textbox and it sent it off.

**Comment by peppy** [comment]
The gamefield scale will likely be adjusted for smaller screen sizes.

**Comment by bdach** [comment]
Closing in favour of #6490.
