### ISSUE TITLE
mania playfield design peeve

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#4889]
Instead of a little window in the centre for the mania playfield, I think it would be better if it went full screen height, going behind the hitobject graph and score.

The squares on the keys would still be in the same position though, they’d just be taller to fit the bottom of the screen.

Also where did the circular lighting from long ago go?

**Comment by peppy** [comment]
This will be customisable or skinnable worst case.

**Comment by smoogipoo** [comment]
This has been addressed in recent times.
