### ISSUE TITLE
Background should be dimmed during loading screen.

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#4893]
**Issue:** When loading a beatmap, the metadata is a little bit hard to see when a beatmap has a bright background. A solution for this is to dim the background by a little amount so that the metadata will be easier to see. The text also blends in with the background when a bright part _(white)_ is close to the text.
**Image:**
![GitHawk Upload by dscnnctd](https://i.imgur.com/AAA9hOf.jpg)

**Comment by peppy** [comment]
@arflyte are there any updates to this screen or should we be dimming further?

**Comment by arflyte** [comment]
Dim the background to black by 20%
