### ISSUE TITLE
Crash when chatting with yourself

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4895]
**Describe the crash:** There's still a way to chat with yourself; and if you try to open that chat, the game instantly crashes.

1. Open the chat
2. Send a message
3. Right-click your name and then click "Start Chat"

**Screenshots or videos showing encountered issue:** https://streamable.com/c7nh5

**osu!lazer version:** 2019.530.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3245222/runtime.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3245223/performance-gamethread.update.log)

**Comment by peppy** [comment]
Should probably be disallowed.

**Comment by arphox** [comment]
@peppy I see this has been marked as a **good first issue**. Can I take it? :-)

_(Also, I don't remember I saw it anywhere in the contributing part of the README so I'll ask: should I open a "WIP" (Work In Progress) pull request while I work on anything?)_

**Comment by Aergwyn** [comment]
PR's are usually opened with your result. WiPs happen if you need opinions on details, are stuck or there are some issues found afterwards.

**Comment by peppy** [comment]
The best solution here would be to disable (or hide) the ability to open a chat when the target is yourself. There should also be a second check in the `ChatManager`'s channel open code to block the operation (doing nothing instead), just in case the user got around the menu items being disabled.
