### ISSUE TITLE
Basic skinning support for osu!mania

### ISSUE THREAD

**Issue by CtrlAltWaverick** [ppy/osu#4896]
When using an osu!mania skin with a texture for the rainbow 300, the default "perfect" skin still shows if you score a rainbow 300, but shows the correct image for everything else (50/100/200/300/miss).

**Comment by peppy** [comment]
Skinning for mania is not yet implemented.

**Comment by mcendu** [comment]
Should generalize the description. The specific issue in the current description has already been addressed.

**Comment by CrazinessUwU** [comment]
can this be fixed?

**Comment by bdach** [comment]
It will be in due time, as it's required for parity with stable - however please understand that there are many areas that need work still.

**Comment by smoogipoo** [comment]
This has been resolved in recent times.
