### ISSUE TITLE
Import of osz file with toplevel directory results in missing some (all?) assets

### ISSUE THREAD

**Issue by DCNick3** [ppy/osu#4912]
**Describe the bug:** 
If you follow [this](https://osu.ppy.sh/help/wiki/osu%21_File_Formats#from-an-archiver) guide and create a [zip archive with one top-level directory inside](https://github.com/ppy/osu/files/3253564/map.zip), renaming it to .osz, you will encounter problems when importing it: it will miss the song itself, background and storyboard sprites and hitsounds. It probably has to do with not using path relative to .osu file as stated in [storyboard scripting specification](https://osu.ppy.sh/forum/viewtopic.php?p=12468#p12468):
>filepath: relative path of the image file (should be in the same directory as the .osu file)

**Screenshots or videos showing encountered issue:** 
![Screenshot_20190604_195021](https://user-images.githubusercontent.com/10363282/58897856-ff552d00-8701-11e9-82eb-acd27a2a16a9.png)

**osu!lazer version:** 
revision 0e8517ebaedda65f1b3f30a134c911a3add99dbf

**Comment by peppy** [comment]
Is it intentional that you have a .osz in a .zip?

**Comment by DCNick3** [comment]
Yes, it is to upload it to github. The problematic osz is the one inside zip.

**Comment by peppy** [comment]
This is because the osz contains a folder inside it. This is not a valid osz file.

**Comment by DCNick3** [comment]
Well, this is all this issue is about. I haven't found any official specs on it, so I had no way to ensure. The thing is: the linked guide on osu wiki results in creation of such osz. Another thing: stable handles such osz right.

**Comment by peppy** [comment]
Do you have any examples of ranked beatmaps in such a broken state?

**Comment by DCNick3** [comment]
Not yet, I think. It depends on whether osu-web re-zips beatmap packs, I think..

**Comment by peppy** [comment]
the client would not UPLOAD a beatmap in that state.

**Comment by DCNick3** [comment]
How about early beatmaps? Were they uploaded by client too?

**Comment by peppy** [comment]
We do not support hand-crafted osz files. Please use the editor to make them.
