### ISSUE TITLE
Skin-level settings

### ISSUE THREAD

**Issue by peppy** [ppy/osu#4924]
Right now, there are quite a few pull requests coming through which implement new customisation options which don't fit at a game-wide level. They also don't fit well in ruleset-specific options, as those are generally considered player settings which you would never want overridden by a skin.

This will add databased skin settings, with user customisation via a UI. Note that this does not encompass a full skin editor (ie. sprite changing) but focuses on settings specifically – things you would find in `skin.ini` historically.

- [x] Depends on #4921
- [x] Depends on #4922

**Comment by jorolf** [comment]
What about a way to sync these settings between skins? Having to switch them everytime you change the skin can be a bit repetitive.

**Comment by peppy** [comment]
User overrides will not be attached to specific skins. You will also eventually be able to modify skins though, should you wish to change skin-specific settings. I have all bases covered.

**Comment by peppy** [comment]
Deprioritising (editor is higher priority for now).

**Comment by peppy** [comment]
The scope of this has changed slightly. The new settings will be part of the skin editor (exposed as a property dialog and using similar automatic setting logic as what we use for mods). Hoping to get to this in the next few months.

**Comment by peppy** [comment]
This has since been implemented 🎉
