### ISSUE TITLE
User Rating / Rating Spread and Points of failure does not show up in the Beatmap overlay

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#4928]
**Describe the bug:** 
Looking at Beatmaps in the client overlay does not show the rating / spread or the Points of Failure. 

**Screenshots or videos showing encountered issue:**
Web: 
![image](https://user-images.githubusercontent.com/17437302/58950087-412bb500-878e-11e9-8f47-ba9916d38d84.png)

Client:
![image](https://user-images.githubusercontent.com/17437302/58950064-307b3f00-878e-11e9-8bf1-2f4830d9e51e.png)

**osu!lazer version:** 
2019.530.0
**Logs:** 
[network.log](https://github.com/ppy/osu/files/3256735/network.log)
[database.log](https://github.com/ppy/osu/files/3256753/database.log)
[runtime.log](https://github.com/ppy/osu/files/3256754/runtime.log)

**Comment by Nyanekoy** [comment]
isnt the Description on beatmaps also missing? 🤔

**Comment by peppy** [comment]
Yes. This is not implemented yet.
