### ISSUE TITLE
Difficulties do not wrap correctly on the BeatmapSetOverlay or DirectOverlay

### ISSUE THREAD

**Issue by welsar55** [ppy/osu#4929]
**Describe the bug:** 
On sets with the 21 or more difficulties (e.g. Sotark's Quaver) difficulties flow off the right-hand side of the screen.

**Screenshots or videos showing encountered issue:** 
![osu_2019-06-05_12-12-06](https://user-images.githubusercontent.com/6157330/58975711-420f1780-878b-11e9-9385-c21f54c83d0d.png)

**osu!lazer version:** 
2019.530.0

**Comment by lunafreya** [comment]
I believe this might be fixed with the new beatmap page design to be implemented both on o!web and the new o!client, pending approval and testing. Right, @peppy and @arflyte?

**Comment by smoogipoo** [comment]
For now it should wrap as on o!web: https://osu.ppy.sh/beatmapsets/873811

**Comment by arphox** [comment]
Performing this change helps with the wrapping but causes additional problems: contents overlap. I'll investigate it further soon.
![kép](https://user-images.githubusercontent.com/17320094/59377100-d102cd80-8d51-11e9-8513-254bad0d81f2.png)

**Comment by welsar55** [comment]
Just discovered the same issue is present in the direct overlay. 
![Capture](https://user-images.githubusercontent.com/6157330/59459726-14f1e300-8de3-11e9-842d-a016fb028a68.PNG)

**Comment by iiSaLMaN** [comment]
Thanks, will include the fix in the PR, i'll handle it just like the web version
![image](https://user-images.githubusercontent.com/22781491/59459887-899a4100-8e26-11e9-892f-65c22c69f53b.png)

**Comment by Joehuu** [comment]
Fixed in referencing PRs.
