### ISSUE TITLE
osu! logo has "shaky" hover animation if lazer isn't focused

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4930]
**Describe the bug:** The osu! logo on the main menu has a weird shaky/bouncy animation if you hover it when the game is not focused.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/103649548-f3c18c00-4f5e-11eb-941f-d4c4c974d59a.mp4

(I made the video slow by 50% to make the difference more visible. Note that, in the video, the game **is** focused when the window's top bar is blue)

**osu!lazer version:** `2019.530.0` (updated video: `2020.1229.0`)

**Comment by peppy** [comment]
This is a combination of some of low frame rate and a one or two frame delay in the propagation of updates.

**Comment by Gabixel** [comment]
I noticed today that this issue is happening again. No idea of when the regression began.
This time, it doesn't seem to be (optionally) related to threading mode; it only occurs when the window is inactive.

I guess it would be best to reopen the issue.

Here's an example:

- [Demo video at normal speed. Can ignore if you want.](/user-attachments/assets/dca2869d-d7d8-4377-a409-8212c8599f63)
- Slowed down version, with only the interesting part. You can see that the logo is misaligned in some frames.
  
  https://github.com/user-attachments/assets/3c03c836-c220-4fb6-89c7-ce7e54b0e03b
- A gif showing the exact frames. The best way to visualize it.
  
  ![demo](https://github.com/user-attachments/assets/3a6709da-c0be-4c08-af17-bd7f050c4605)
