### ISSUE TITLE
osu!direct is missing a back button on mobile.

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#4932]
Whenever I search a map in osu!direct, the game is not giving me a _back_ option. It is annoying to close out the direct window and opening it again.
**Image:**
![“Back” button is missing in direct window (mobile). by dscnnctd](https://i.imgur.com/brofp6D.jpg)

**Comment by peppy** [comment]
Duplicate of https://github.com/ppy/osu/issues/4886. Also you can click on the edges of the screen or hit escape to dismiss.
