### ISSUE TITLE
Music preview doesnt output sound

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#4937]
**Describe the bug:** 
When you click play to preview the music in direct or the beatmap overlay, the normal background music from the game doesnt stop and keeps playing. the music preview doesnt output any sound but the progress bar works. If i have the music on MAX i can hear like a little pop sound but thats about it
**Screenshots or videos showing encountered issue:** 
https://streamable.com/vi8qb
**osu!lazer version:** 
2019.606.0
**Logs:** 
[network.log](https://github.com/ppy/osu/files/3261682/network.log)
[runtime.log](https://github.com/ppy/osu/files/3261683/runtime.log)

**Comment by peppy** [comment]
`PreviewTrackManager` is no longer able to exclude itself from the mute it applies to game-wide audio tracks. We will need to re-think how the audio subsystem exposes nesting (or consider a drawable alternative) to resolve this.

Likely requires some framework-side changes. I'm unable to find a quick hotfix for this one.
