### ISSUE TITLE
Profile Rank line graph does not draw properly.

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu#4938]
**Describe the bug:** You can no longer see the line in the line graph in the profile. Opening and closing the overlay (or causing any kind of movement) will momentarily show the line though.

**Screenshots or videos showing encountered issue:** 
- https://streamable.com/5fl28

![image](https://user-images.githubusercontent.com/20495991/59040838-18004700-88aa-11e9-85de-831898068295.png)
**osu!lazer version:** 2019.606.0

**Logs:** N/A

*updated the screenshots/videos*

**Comment by smoogipoo** [comment]
What's going on in your second screenshot? All the content is missing? Is that what you're expecting there or is that a bug of its own?

**Comment by LeNitrous** [comment]
I was just resizing the screen showing that the line graph is still there. I'll try and get a recording instead.
