### ISSUE TITLE
Allow highlighting changes in changelog

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#4942]
Highlighting changes isn't currently available in Changelog Listing, as it is on the website

![](https://user-images.githubusercontent.com/19843905/59065217-7d553780-88ac-11e9-88da-dd382d8134bb.png) web

![](https://user-images.githubusercontent.com/19843905/59065254-8e9e4400-88ac-11e9-8808-ac01e92fce25.png) lazer

**Comment by Game4all** [comment]
What is the color used for highlighted changes ?

**Comment by peppy** [comment]
It should match the web. You can use the inspector in your browser to check.
