### ISSUE TITLE
Cursor trail is rendered above chat overlay

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ppy/osu#4953]
**Describe the bug:** 
The cursor trail will be drawn above the chat overlay, when opened.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/13605369/59119214-78e35a00-8952-11e9-8061-6412a97c4f36.png)

**osu!lazer version:** 
2019.607.0

**Logs:** 
N/A

**Comment by Gabixel** [comment]
The cursor trail seems to be above buttons on failed/paused overlay too:
![cursor trail](https://user-images.githubusercontent.com/43073074/59120406-982fb680-8955-11e9-9094-160a14f5a0d3.png)

**Comment by HoLLy-HaCKeR** [comment]
Seems to be due to the new FTB render pass, as this doesn't happen when it's turned off in the debug options.
