### ISSUE TITLE
Sprite icon for PlaylistOverlay is not completely visible

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4955]
**Describe the bug:** The sprite icon for the PlaylistOverlay located in the Music Controller looks cut off

**Screenshots or videos showing encountered issue:** 
![Music Controller](https://user-images.githubusercontent.com/43073074/59121465-6ec45a00-8958-11e9-8bc0-23bff16fcda9.png)
![PlaylistOverlay Sprite Icon](https://user-images.githubusercontent.com/43073074/59121601-dc708600-8958-11e9-98d2-2cfc69117315.png)

**osu!lazer version:** 2019.607.0

**Logs:** N/A

**Comment by peppy** [comment]
corner radius is causing this. padding should be added equal to the cor er radius so the icon is not affected by it.

**Comment by Gabixel** [comment]
Looks fixed now:
![PlaylistOverlay](https://user-images.githubusercontent.com/43073074/59554332-b9ba1f00-8fa1-11e9-8c66-27e315eee495.png)
But I've noticed there's another button with this issue, this time in the `PlaybackControl` of the osu!editor:
![osu!editor](https://user-images.githubusercontent.com/43073074/59554387-5b417080-8fa2-11e9-877e-db1a36f7606f.png)
_(new issue for this or can I easily modify this one?)_
