### ISSUE TITLE
Dimming containers in carousel don't resize correctly when UI Size changes

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4968]
**Describe the bug:** Basically if you change the UI Size when you're in Solo, the following container, which contains the beatmap background's dimming, has its pieces all separate.

**Screenshots or videos showing encountered issue:** https://streamable.com/0zhc4

![dimming issue](https://user-images.githubusercontent.com/43073074/59151607-29765a00-8a36-11e9-9784-be72eea25235.png)

**osu!lazer version:** 2019.608.0 (the first time I've noticed this is from 2019.518.0 to be exactly)

**Comment by peppy** [comment]
Do you mean UI scale in settings?

**Comment by Gabixel** [comment]
Yes, as you can see with the attached video

**Comment by Gabixel** [comment]
Also, this seems to happen when scrolling through the carousel and hiding/unhiding the toolbar at the same time: https://streamable.com/wrrfz
