### ISSUE TITLE
Sort by date order is reversed to osu!stable variant

### ISSUE THREAD

**Issue by DCNick3** [ppy/osu#4975]
In osu!stable sorting by date places newer beatmaps to the bottom. In lazer this is currently opposite, which is counter-intuitive after using stable.

**osu!lazer version:** 
revision 164b05abd6debb5b817d2f47620e593c006a24b2

**Comment by arphox** [comment]
Relates to #4867, probably can be closed as a duplicate.

**Comment by DCNick3** [comment]
Not quite right. The feature has been implemented in #4914. This issue is about wrong order, not the missing sorting.

**Comment by peppy** [comment]
Newest is at the top. This is intentional.

**Comment by arphox** [comment]
@peppy If it is already implemented as @DCNick3 wrote, maybe we should make the checklist up-to-date in PR #4919.
