### ISSUE TITLE
Music player scroll list scroll bar goes off menu

### ISSUE THREAD

**Issue by SpikyPillow** [ppy/osu#4979]
**Describe the bug:** 
On the home screen's music player, the list of songs and scroll bar keeps scrolling past the point where the scroll bar reaches the bottom.

**Screenshots or videos showing encountered issue:** 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/51576746/59173931-c60f2980-8b14-11e9-9e80-aa4a35979acf.gif)

**osu!lazer version:** 
Latest

**Logs:** 
N/A (I hope)

**Comment by peppy** [comment]
Can't seem to reproduce this. Does it happen on startup?

**Comment by SpikyPillow** [comment]
Consistently happens every time I've checked. Also, it's been there for at least several versions, and I've only just reported it.
I do have a large amount of beatmaps ported into lazer, I think maybe a couple thousand? It's probably related to that.

**Comment by nyquillerium** [comment]
I've seen this happen for other `ScrollContainer`s with a large amount of items too. Probably should be framework-side.

**Comment by Joehuu** [comment]
Duplicate of #3942.

**Comment by nyquillerium** [comment]
closing as a duplicate of https://github.com/ppy/osu/issues/3942
