### ISSUE TITLE
Implement new grade sprites on lazer.

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#4980]
The grade sprites in _lazer_ needs to be replaced with the new ones shown on _web_.
**Web:**
![GitHawk Upload by dscnnctd](https://i.imgur.com/zyflUQL.jpg)
**lazer:**
![GitHawk Upload by dscnnctd](https://i.imgur.com/f8MSHsz.jpg)

**Comment by iiSaLMaN** [comment]
It is implemented #4967, you need to manually build osu!lazer, there will be a release soon with the new grades, close this

**Comment by dscnnctd** [comment]
Closing.
