### ISSUE TITLE
Loading screen freezes for one second when loading a beatmap with a different slider colour

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#4981]
This usually happens on this beatmap when you load it once.
**Beatmap:** https://osu.ppy.sh/beatmapsets/875530#osu/1829658
**Version:** _Latest Release (iPhone 7 iOS 12)_
**Video:** https://youtu.be/DAHHB33zkYk

**Comment by peppy** [comment]
How are you discerning that this is related to slider colours?

**Comment by dscnnctd** [comment]
This doesn’t seem to happen on other beatmaps that has no slider colour. Other beatmaps with no slider colour does not freeze for a second in loading screen at all.

**Comment by dscnnctd** [comment]
Closing since this no longer happens in latest build.
