### ISSUE TITLE
Retry/Watch Replay Buttons

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#4991]
![osu_2019-06-11_15-13-22](https://user-images.githubusercontent.com/32044067/59261634-7ab36300-8c5b-11e9-9d56-01b1cc59f8f2.jpg)
**Describe the new feature:** 
I would really appreciate a Retry, Watch Replay, and Save Replay button on the song ending screen where it displays the score, accuracy, amounts of Greats, Goods, Misses, etc.
Also, when clicking a score in the leader-board, Lazer will take you to the play 
stats and such, but will not let you see the replay(because there is no button). This makes Stable the only way to watch replays and can be really inconvenient. I know you are planning to add this(because this is an essential feature) but I would still like to express my opinions in case this can be added in the next update(if you happen to notice this).

**Proposal designs of the feature:** 
You should add a "Watch Replay" and "Retry" button somewhere on the Play Overview screen like in osu!stable.

**Comment by iiSaLMaN** [comment]
For the replay stuff, there is a pull request open for that #4985, as for the other buttons, they will be added soon

**Comment by AqilCont** [comment]
Oh ok...
###### *lol i sent to pull requests right after i made this issue and literally was looking at that exact pull request when you referenced it*

**Comment by iiSaLMaN** [comment]
Should be closed
