### ISSUE TITLE
"Friends" not ordering based on selected tab

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#4995]
**Describe the bug:** 
Lazer doesn't order "Friends" by the tab selected on the top(which I am very sure orders them by either rank, name, or location)

**Screenshots or videos showing encountered issue:** 
![osu_2019-06-11_18-25-31](https://user-images.githubusercontent.com/32044067/59273645-53b65a80-8c76-11e9-8c7e-640efc55b020.jpg)

**osu!lazer version:** 
2019.611.0 (Latest)

**Logs:** (I don't think they are necessary but will send if asked to)

**Comment by Aergwyn** [comment]
Yes it's completely missing because (at the time of me working on the social browser) the API doesn't support any of it yet.
See https://github.com/ppy/osu-web/issues/2162. Although the issue talks about "rankings" iirc that includes not being able to do the same for friends.

**Comment by peppy** [comment]
I believe the website is doing local filtering with the new friends implementation. We should replicate what it's doing.
