### ISSUE TITLE
Osu! Stable skin doesn’t take effect?

### ISSUE THREAD

**Issue by JarrenJ** [ppy/osu#4999]
**Describe the bug:** 
I made a .osu folder in my home directory so osu!lazer would find all my songs and skins after I copied the files over from the Mac wineskin version. It found all of them and imported them just fine - that being said when I select one of my skins - it doesn’t get activated?

Is this feature not fully supported yet - or is it indeed a bug, as from what I have read it sounds like other users are able to use their skins, but I might be mistaken?

**Screenshots or videos showing encountered issue:** 
Don’t have any screenshots as I am currently at work - but i think the problem is pretty easy to picture.
**osu!lazer version:** 
Latest Mac Binary

**Comment by Altenhh** [comment]
as far as I've seen, the only elements that are supported for skinning currently are HitCircles and Main Menu background (if you are a supporter)

**Comment by JarrenJ** [comment]
Oh. Well in that case I’ll close this issue as it isn’t really a bug then. 

To any devs/contributors could you consider adding in at least the option for now to alter the beat map skin for Mania - as in I really don’t like the bars - I prefer arrows. Could you provide us an easy way to change the img source for those elements?

**Comment by peppy** [comment]
It's important to note that the skins you imported are imported in their whole. When mania skinning is added, they will magically start working.

We are in need of people to implement skinning for other rulesets. It's a pretty simple process and there's lots of examples in osu! ruleset. I'd recommend having a try at it  if capable.
