### ISSUE TITLE
Some hit objects have incorrect transforms after rewinding

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#5013]
https://streamable.com/68e34

The changes in https://github.com/ppy/osu/pull/5012 have not fixed this issue.

**Comment by peppy** [comment]
I believe this is fixed via recent lifetime reset changes. @smoogipoo do you remember which beatmap this is?

**Comment by smoogipoo** [comment]
This is https://osu.ppy.sh/beatmapsets/788233#osu/1654647 (not sure on the difficulty), but I can't seem to replicate it anymore.
