### ISSUE TITLE
Windows icon issue.

### ISSUE THREAD

**Issue by SanderKvenild** [ppy/osu#5019]
# This is osu!stable.
I just wanted to notify you that the icons are (probably) set up wrong. You should sort the layers small to big.
I was unable to find any documentation on how to set up a ".ico" file properly so I did my own research.
On the windows desktop I had an ugly broder around the icon:
![osu! desktop icons](https://user-images.githubusercontent.com/5667285/59477697-9fbff580-8e56-11e9-8d3c-b8358c4bf4a2.png)
I used a software called IconsExtract to look up the images (appears as layers in GIMP) within the icons for osu!.exe and got this:

ID | Dimentions | Colors
------------ | ------------- | -------------
1 | 16x16 | 16
2 | 32x32 | 256
3 | 16x16 | 256
4 | 256x256 | 21060 Bits
5 | 128x128 | 32 Bits
6 | 64x64 | 32 Bits
7 | 48x48 | 32 Bits
8 | 32x32 | 32 Bits
9 | 16x16 | 32 Bits

###
I took a look at the logo for Mozilla Firefox (as a reference):

ID | Dimentions | Colors
------------ | ------------- | -------------
1 | 16x16 | 32 Bits
2 | 32x32 | 32 Bits
3 | 48x48 | 32 Bits
4 | 256x256 | 32 Bits

###
I also took a look at the logo for Google Chrome (as another reference) to look for any diferences and noticed this one has 3 layers dedicated to 256 colors:

ID | Dimentions | Colors
------------ | ------------- | -------------     
1 | 16x16 | 256
2 | 32x32 | 256
3 | 48x48 | 256
4 | 16x16 | 32 Bits
5 | 32x32 | 32 Bits
6 | 48x48 | 32 Bits
7 | 256x256 | 32 Bits

If I extract the icon, open it in GIMP and sort the layers from smallest to largest (like the table below), the exported file works as intended.

ID | Dimentions | Colors
------------ | ------------- | -------------
1 | 16x16 | 16
2 | 16x16 | 256
3 | 32x32 | 256
4 | 16x16 | 32 Bits
5 | 32x32 | 32 Bits
6 | 48x48 | 32 Bits
7 | 64x64 | 32 Bits
8 | 128x128 | 32 Bits
9 | 256x256 | 32 Bits

**Comment by iiSaLMaN** [comment]
`21060 Bits` does that even exist?

**Comment by SanderKvenild** [comment]
Probably just a bug in the program i was using. File size looks normal.

**Comment by iiSaLMaN** [comment]
wait.., isn't that osu!stable's icon, everything here is dedicated to osu!lazer, not osu!stable

**Comment by SanderKvenild** [comment]
Where should I post it?

**Comment by peppy** [comment]
If you send me an email with a modified (corrected) logo I'll see what I can do (pe@ppy.sh). Thanks!
