### ISSUE TITLE
Performance regression on 2019.612.0

### ISSUE THREAD

**Issue by SaggitariusAStar** [ppy/osu#5026]
**Describe the bug:** Before the update I was able to get 3x the (Draw) frames I'm getting now during gameplay. For example I used to get around 300fps or more during gameplay, now I'm getting around 100fps and it is not consistent in any way. A lot of frame drops inbetween so it feels laggy as hell (though frame drops were present even before the update, they weren't as bad as they are now). Even though it says it's 100fps it feels like I'm playing with 30fps.

**Screenshots or videos showing encountered issue:** I don't think it's of any use showing screenshots or a video.

**osu!lazer version:** 2019.612.0

**Logs:** 
[network.log](https://github.com/ppy/osu/files/3291762/network.log)
[performance.log](https://github.com/ppy/osu/files/3291763/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3291764/runtime.log)
[database.log](https://github.com/ppy/osu/files/3291765/database.log)

**Comment by SaggitariusAStar** [comment]
I also have to mention that I don't know whether 2019.611.0 suffers from the same issue because I haven't played on that version.

**Comment by SaggitariusAStar** [comment]
Another observation is that performance seems to decrease with difficulty increase on beatmaps. It starts to becomes significant above 4.5* to me.

**Comment by peppy** [comment]
As a sanity check, can you turn on “bypass front to back” at the bottom of settings and see if your frame rate improves substantially?

Also please include your PC specs (cpu/gpu)

**Comment by SaggitariusAStar** [comment]
Turning on **Bypass front-to-back render pass** offers no significant performance increase in Draw frames.

**PC specs (CPU/GPU):** AMD FX 6300 / Nvidia GTX 950

I don't see how knowing the specs would help since on stable osu I'm getting constant frames capped at 240 never going below that. Or unless maybe it happens that you might have that specific hardware to test it on so that's why you're asking? Either way, it's almost never the hardware, but the software. I wouldn't be reporting this issue if I knew my PC doesn't even have a dedicated GPU and the performance would be trash anyways.

Is there any way to obtain more information on performance that could help you help me? Since the logs seem to be lacking in information.

**Comment by peppy** [comment]
Have you tried restarting your PC and ensuring no background applications could be causing issues? Checking the changes that went into the build you mention, nothing should have altered performance. I can confirm at my end that performance has not changed.

**Comment by iiSaLMaN** [comment]
What version of lazer did you get good perfomance at?

**Comment by peppy** [comment]
This is stated in the issue title.

**Comment by SaggitariusAStar** [comment]
It could be that sometimes when the PC goes to sleep automatically, windows derps and the performance becomes horrible in certain games (FPS not constant and lowered, etc.). Could've been that (known issue with windows going to sleep causing performance resgression). Now the FPS is fairly constant but it's still low. Guess that just simply must be lazer as before not being optimized and me not noticing this low peformance because there were no frame drops to bother me.

**Comment by SaggitariusAStar** [comment]
That being said, when are we supposed to expect a significant boost in performance on osu!lazer?

**Comment by peppy** [comment]
Depending on hardware and platform, you may already get up to 5x boost. On my main gaming PC I can get 4-5x high frames on lazer under certain conditions.

It's all dependent on where you are currently bottlenecked and if we've optimised for that scenario.

Either way, closing this issue as resolved.

**Comment by SaggitariusAStar** [comment]
The hardware is fine. It's no excuse getting around 100 fps in a circle hitting game with this hardware. On osu! stable the performance is waaay better.

**Comment by peppy** [comment]
Please read my previous reply. This is still a work in progress and it will depend on where you are currently bottlenecked and if we've optimised for that scenario yet.

**Comment by SaggitariusAStar** [comment]
GPU bottleneck. My CPU can do more.
