### ISSUE TITLE
Multiplayer scoring is broken/not shown after beatmap being played

### ISSUE THREAD

**Issue by SaggitariusAStar** [ppy/osu#5027]
**Describe the bug:** Simply put, whenever I play a map on multiplayer, after I'm finished playing it, the score is not publicly shown but is kept local.

**Screenshots or videos showing encountered issue:** Don't think it's necessary.

**osu!lazer version:** 2019.612.0.0

**Logs:** 

[performance.log](https://github.com/ppy/osu/files/3291800/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3291801/runtime.log)
[database.log](https://github.com/ppy/osu/files/3291802/database.log)
[network.log](https://github.com/ppy/osu/files/3291803/network.log)

**Comment by peppy** [comment]
That's very weird. The submission request is showing up in your network log, so it seems like it should be submitting.

```
2019-06-14 06:32:20: Performing request osu.Game.Online.API.Requests.CreateRoomScoreRequest
2019-06-14 06:32:21: Request to https://osu.ppy.sh/api/v2/rooms/5037/playlist/4949/scores successfully completed!
```

I'll check server-side to see what is happening here.

**Comment by Gabixel** [comment]
It doesn't seem to work for me too ([network.log](https://github.com/ppy/osu/files/3293252/network.log)).

Also, it says that I'm placed `#0` if I get the top score
![position 0](https://user-images.githubusercontent.com/43073074/59553025-94bcb080-8f8f-11e9-9fcd-690af4c618ac.png)

**Comment by smoogipoo** [comment]
We're looking for a `SubmitRoomScoreRequest`, not a `CreateRoomScoreRequest`. That one doesn't seem to be in any of the logs.
