### ISSUE TITLE
Game screen texture rendering breaks when window is resized while gameplay

### ISSUE THREAD

**Issue by byDave251** [ppy/osu#5030]
**Describe the bug:** 
While I was testing how osu!lazer works with different aspect ratios in taiko, I switched to windowed and dragged and resized the window. While resizing, the whole game just broke. May be related to https://github.com/ppy/osu/issues/2420 in some way.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/25853767/59549437-c452c500-8f5d-11e9-95ef-f14d194f1b74.png)
![image](https://user-images.githubusercontent.com/25853767/59549438-c74db580-8f5d-11e9-8d9b-839ffd74bf72.png)
![image](https://user-images.githubusercontent.com/25853767/59549440-cb79d300-8f5d-11e9-91df-c9b6290446f9.png)
![image](https://user-images.githubusercontent.com/25853767/59549441-cf0d5a00-8f5d-11e9-92c0-f6b860678cd1.png)

**osu!lazer version:** 
2019.612.0

**Logs:** 
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3292915/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3292916/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3292917/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3292918/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3292919/updater.log)
[database.log](https://github.com/ppy/osu/files/3292920/database.log)
[network.log](https://github.com/ppy/osu/files/3292921/network.log)
[performance.log](https://github.com/ppy/osu/files/3292922/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3292923/performance-gamethread.audio.log)

**Comment by byDave251** [comment]
I am sorry, I haven't noticed there is already an issue for this. https://github.com/ppy/osu/issues/5018

**Comment by smoogipoo** [comment]
Please test again on the latest release and let us know if it's still happening in #5018 .
