### ISSUE TITLE
please add compatibiliy mode 

### ISSUE THREAD

**Issue by BlueBoyGitHub** [ppy/osu#5038]
so osu! laser is very laggy at time's so maybe for those people who don't have the best computer in the whole world to have compatibility mode.

**Comment by jorolf** [comment]
Compatibility modes are there so you can *start* the specific game on an older machine, it disable the use of newer apis (which can be faster!) and instead uses older ones. Introducing one wouldn't make the game faster necessarily.

**Comment by peppy** [comment]
We are still working towards optimisations for older hardware. Please continue using osu-stable and check back later.
