### ISSUE TITLE
UI Scale covers the warning icon by 1/4 on external link warning.

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#5040]
When UI Scale is on, the warning icon on _external link warning ui_ is covered by 1/4. This should not happen when UI Scaling is above _**x1.0**_.
**Image:**
![GitHawk Upload by dscnnctd](https://i.imgur.com/W5VYivH.jpg)

**Comment by TPGPL** [comment]
should be closed i guess as the fix PR has been merged
