### ISSUE TITLE
Icon on changelog screen is distorted.

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#5043]
The icon/logo on changelog screen is not supposed to look like this. Possibly regression, or it’s not stretched properly?
**Image:** ![GitHawk Upload by dscnnctd](https://i.imgur.com/T43M5Zt.jpg)

**Comment by peppy** [comment]
Can't reproduce this. What build are you on?

**Comment by dscnnctd** [comment]
Latest Release on iOS 12 (w/ UI Scale) iPhone 7

**Comment by peppy** [comment]
This is very weird. With no amount of UI scale can I make this happen..

Can you take a full screenshot rather than a clipped portion?

**Comment by dscnnctd** [comment]
![GitHawk Upload by dscnnctd](https://i.imgur.com/EXy4Dbg.jpg)
UI Scale is x1.18
