### ISSUE TITLE
Game freeze upon loading long (54 minute) beatmap followed by fast forward through said beatmap

### ISSUE THREAD

**Issue by mdkt** [ppy/osu#5045]
[This](https://www.youtube.com/watch?v=quRLPsy08JU) recording explains the bug better than I can.
I can replicate the bug with varying degrees of severity every time on my machine.
The editor seems to be bugged too, 
[Beatmap](https://osu.ppy.sh/beatmapsets/970063#osu/2029377)

**Comment by Joehuu** [comment]
Fixed by pooling.
