### ISSUE TITLE
Inactive volume doesn't work when alt tabbing too fast

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#5048]
Regressed from #5047.

**Comment by peppy** [comment]
too fast from what?

**Comment by Joehuu** [comment]
alt tabbing back and forth fast

**Comment by peppy** [comment]
It has a transition now, so you will not notice it instantly.

**Comment by Joehuu** [comment]
To reproduce:
- Set inactive volume to 0% (to notice it)
- Alt tab out (inactive volume working)
- Alt tab in and out fast (not working)

**Comment by Aergwyn** [comment]
Saying it's working vs it's not working is not really helpful. What do you expect to happen and what does happen?
Anyways, see above comment (https://github.com/ppy/osu/pull/5047). This issues seems obsolete now? Or is it broken in a different way?

**Comment by peppy** [comment]
I can see why this would happen. An oversight of how `Add`/`RemoveAdjustment` work.
