### ISSUE TITLE
Favorites in osu!direct do not match up with my favorites on the website

### ISSUE THREAD

**Issue by Silquetoast** [ppy/osu#5051]
**Describe the bug:** 
Several songs that aren't in my favorites on the site(the site is accurate) are listed as my favorites in osu!lazer

**Screenshots or videos showing encountered issue:** 
For example... 
https://i.imgur.com/7u8iA7s.jpg 
"Pika Girl" has never been in my favorites, but is listed here anyways. This list is *maybe* 40% accurate.

https://i.imgur.com/3t4X1Aq.png
Just to be thorough, I did a ctrl+F search for "pika" on the website with my favorites list fully expanded, and there are no results. 

**osu!lazer version:** 2019.616.0

**Logs:** (I didn't know where to find logs, but if they're needed I will edit them in here)

**Comment by Joehuu** [comment]
That is favorites sorting of **all beatmaps**. For **your favorite beatmaps**, it's located in the right dropdown:
![osu_2019-06-17_21-57-40](https://user-images.githubusercontent.com/35318437/59654446-02610c00-914b-11e9-930d-af679cbafb49.jpg)

**Comment by smoogipoo** [comment]
Probably could do with an interim fix of adding some text before the dropdown.

**Comment by Joehuu** [comment]
Will be fixed when the new beatmap listing overlay replaces direct overlay.
