### ISSUE TITLE
Where is the songs folder located in macOS? (osu!lazer)

### ISSUE THREAD

**Issue by frobuddyharry** [ppy/osu#5062]
I got osu!lazer for mapping songs and dragging in mp3's just doesn't do it. Where is the songs folder located so I can make mania maps? (PS: When I do Go to Folder and put in ~/.osu/Songs it just puts me in the home folder.)

**Comment by peppy** [comment]
The editor is not quite in a usable state yet sorry. Please check back in a month or two!
