### ISSUE TITLE
Add a "Import Local Plays From Stable" button

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#5065]
**Describe the new feature:** 
In the Settings, there is an "Import beatmaps from stable"(which imports all [new] beatmaps from stable) button and an "Import skins from stable"(which imports all skins from stable) button. In addition to this, I would also appreciate a "Import Local Plays from stable" button which imports all local plays from stable so the play history and other stuff is also recovered instead of just skins and beatmaps.

**Proposal designs of the feature:** 
At the first Lazer startup, add a question at also asks if the user wants to import beatmap history. Also add 2 buttons in Settings below the "Delete ALL skins" button that say "Import beatmap history from stable" and "Delete ALL beatmap history" which do exactly as they say they do on click.
![osu_2019-06-19_10-05-12](https://user-images.githubusercontent.com/32044067/59737060-cd070c00-9279-11e9-8427-38b231bb2215.jpg)

**Comment by peppy** [comment]
This should be a 15 minute change. Only special part to consider is that beatmaps should be imported first (before the score import starts) as scores currently exist without a beatmap, I believe.

**Comment by AqilCont** [comment]
Wait, does osu!stable delete beatmap play history when you delete a beatmap?
