### ISSUE TITLE
Negative SS counter

### ISSUE THREAD

**Issue by ZayyKen** [ppy/osu#5066]
**Describe the bug:** [osu!mania] A few months ago, i've noticed that some of my 1millions play were deleted, i decided to replay them and since that day I've got a negative SS counter...

**Screenshots or videos showing encountered issue:** 
![Screenshot_1](https://user-images.githubusercontent.com/51994902/59758281-dac68c80-928d-11e9-9df1-e4460e866e3f.png)

**osu!lazer version:** /

**Logs:** N/A

**Comment by HoLLy-HaCKeR** [comment]
I don't think this is a Lazer issue

**Comment by Game4all** [comment]
This is rather an osu-web issue as the API / web shows the same results

**Comment by ZayyKen** [comment]
Oww, yep didn't see that i'll fix it !
