### ISSUE TITLE
HeaderTexts in ScoreContainer are not hidden for unranked maps in BeatmapSetOverlay

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5069]
**Describe the bug:** If you load an unranked beatmap details' page (e.g. Graveyard maps), everything seems normal, but if you load the page of a ranked map and then the page of an unranked one, the `HeaderText`s of the `ScoreContainer` are not cleared/hidden. 
(Also this probably needs a similar design for #4568)

**Screenshots or videos showing encountered issue:** 

- https://streamable.com/0ldsm

![Unranked map details' page](https://user-images.githubusercontent.com/43073074/59778413-bc28bb80-92b6-11e9-9c51-53a9ea52e8e4.png)

**osu!lazer version:** 2019.616.0

**Comment by EVAST9919** [comment]
@peppy do we want a placeholder like "There's no scores for unranked maps" or just remove that completely?

**Comment by peppy** [comment]
Just hidding the header is fine for now. Reference the web if unsure (example: https://osu.ppy.sh/beatmapsets/990027#osu/2070986)
