### ISSUE TITLE
Add cursor ripples

### ISSUE THREAD

**Issue by aqilc** [ppy/osu#5070]
**Describe the missing feature:**
Like in stable, there is a "Cursor Ripples" option in the Settings. I want that same option in Lazer.

**Proposal designs of the feature:** 
Add a "Cursor Ripples" option in Settings which makes a ripple like effect on click.

**Comment by peppy** [comment]
Will probably come with a different visual effect. The stable one is pretty half-assed.

**Comment by AqilCont** [comment]
Lol, ikr.
On this 4k display, the ripples on stable are really small and don't scale up with resolution.

**Comment by MatthieuHernandez** [comment]
Hello @peppy, 
I'm a C++/C# dev and very interested in this feature.
If you want help I can try to develop this feature and propose a Pull Request. So you can focus on other more important features.

**Comment by peppy** [comment]
I've already finished implementing this.
