### ISSUE TITLE
Settings panel is non-interactable when opened at startup

### ISSUE THREAD

**Issue by Craftplacer** [ppy/osu#5075]
**Describe the bug:** 
When you spam Ctrl+O at startup it causes the settings panel to appear but will "freeze" even after splash screen has been finished.

Temporary fix of the user would be to open (a duplicate) settings panel within the main menu, and then closing it. (also shown in video)

**Screenshots or videos showing encountered issue:** 
https://streamable.com/albkt

**osu!lazer version:** 
2019.616.0 (latest at the time of writing this)

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3308632/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3308633/runtime.log)

**Comment by peppy** [comment]
This is due to it not being loaded yet (overlays are loaded slowly in the background on startup). The long-term solution to this is adding a "loading" state to overlay containers. So they can display while they are loading at a lower overhead.

**Comment by Joehuu** [comment]
The overlay actually stays "non-interactable" for the remainder of the game session, and the only fix (as said above) is to open the overlay again.

Can seem to only reproduce with a release (where there's a disclaimer). Can't reproduce when building on IDE (have to enable disclaimer).

**Comment by nyquillerium** [comment]
I've PRed a fix for the issue mentioned here (the overlay being stuck and not taking any input), but its worth noting that the issue Peppy mentioned still exists, and should probably be tracked separately.

**Comment by Joehuu** [comment]
> its worth noting that the issue Peppy mentioned still exists, and should probably be tracked separately.

Tracked in #5715.
