### ISSUE TITLE
Osu Skin Store

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#5079]
## Describe the new feature:
A skin store where osu skin creators can upload unique skins, and if possible, sell them. Osu!supporters can then temporarily "borrow" skins when playing replays from other players to see what the play really looked like when the player was playing the map. You can also change the price of osu!supporter to $5 or $10 per month with the addition of them getting access to every skin on the store.
I know this is likely not going to happen but if it does, it would help osu!supporter's popularity and would really promote Dean Herbert and the creators spending hours creaking unique skins for millions of users. Also, surfing the forums for skins is really a pain sometimes as you can't preview the skins before you click on about 3 links for 1 skin.

## Proposal designs of the feature:
A new button by the osu!direct button on the top bar which opens an overlay displaying blocks which song select preview image with the skin on, the price, and the username of the creator(and they would kind of look like a map block on osu!direct).

**Comment by peppy** [comment]
Online skin support is coming further down the track. We already have designs and basic framework for it in place. It would not be paid or anything like that.

Closing this because it's not the correct repository or vision (this should be opened against `osu-web` if anything).
