### ISSUE TITLE
Pressing Escape in Key configurations sets Escape as the key binding

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#5080]
**Describe the bug:** 
In Settings, when you go to Keyboard configurations and accidentally click something, it says "Press Escape to cancel" but when you press `Esc`, it sets `Esc` as the key binding.

**Screenshots or videos showing encountered issue:** (was unable to take one)

**osu!lazer version:** 2019.616.0 (latest)

**Logs:** (i don't think they are needed)

**Comment by AqilCont** [comment]
(the reason i was unable to take a picture was because it kept setting F12 as the key binding and Print Screen doesn't properly work with osu for some reason)

**Comment by Game4all** [comment]
I guess there are certain actions that the user would like to bind to Escape key, so the key combination to cancel key binding should be modified or simply deleted (as you can already cancel key binding by clicking elsewhere on the keybinding overlay), or allowing certain actions to be bound to the escape key.

**Comment by smoogipoo** [comment]
This must have regressed at some point. Esc used to be treated as a special key that could never be bound.
