### ISSUE TITLE
Add a toggle for disabling Discord Rich Presence

### ISSUE THREAD

**Issue by Vezqi** [ppy/osu#5090]
**Describe the new feature:** 

Adding a toggle to the settings menu, which would allow you to either disable the Rich Presence feature completely, or hide rank and username info (but still display the current game mode + map info).

**Proposal designs of the feature:** 

If a user has the 'Hide User Info' feature toggled, it would be neat if the the RPC could update with 'Anonymous' instead of the user's username.

Two toggles, which are listed below could be added to the settings menu:

→ Enable/Disable Discord Rich Presence.
→ Show/Hide User Info

**Comment by peppy** [comment]
Aren't toggles for this already at discord's end? Should we really be adding our own?

**Comment by Vezqi** [comment]
Discord only allows you to disable all game info. I think it would be a nice feature so that my friends can still see that I'm playing osu, but without the RPC + user info and whatnot.

**Comment by Gabixel** [comment]
Maybe this can be implemented using the "Do not disturb" option in the future _(because right now it's just W.I.P.)_

![DoNotDisturb](https://user-images.githubusercontent.com/43073074/59917153-6fadbf00-9421-11e9-9dc3-5e08f34f2ea8.png)

**Comment by Craftplacer** [comment]
> Aren't toggles for this already at discord's end? Should we really be adding our own?

You've done them for Windows Live Messenger, so.....

![](https://files.catbox.moe/vp23v1.png)
![](https://files.catbox.moe/l4adr6.png)

Also, the rich presence option allows me and others to "hunt down" players on osu!.

**Comment by Joehuu** [comment]
Recently added in stable, so not a proposal now. Closing and making https://github.com/ppy/osu/issues/1109 track this implementation.

**Comment by Joehuu** [comment]
Reopening as this hasn’t been added in the initial implementation.
