### ISSUE TITLE
Hidden mod doesn’t work in osu!catch

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu#5099]
Hidden mod can be selected, but in game nothing happens (ie the notes look the same as no mod).  Sounds like this is a known issue and that the mod should be disabled until fixed/implemented 

![A2937D30-8489-4DD8-A352-2B863E91C04A](https://user-images.githubusercontent.com/49334335/59906962-8e836580-93cf-11e9-8eca-1da42d0a5dbf.jpeg)

**Comment by Aergwyn** [comment]
I'll look into implementing HD for CtB. Seems pretty simple as all types of objects behave identically if I see that right.
Any input (from the team) on exact values as in when the fade should happen etc?
