### ISSUE TITLE
CtB: Custom skins do not apply

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu#5101]
When selecting a custom skin everything appears to work in Standard, but in CtB (and Mania) the skin doesn't apply and the default Lazer skin is used instead

**Comment by Game4all** [comment]
Skinning for catch and mania gamemode isn't implemented yet.

**Comment by Game4all** [comment]
Duplicate of #3967

**Comment by nyquillerium** [comment]
Closing as duplicate of https://github.com/ppy/osu/issues/3967
