### ISSUE TITLE
Add option for combo following catcher

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu#5103]
In stable combo is counted right above the ryuuta/center screen ish and moves back and forth (left/right) as you move the ryuuta.  Not having this at least as an option makes ctb play feel very uncomfortable as I cannot easily tell when I've dropped a note or just see how far I've made it etc.  

This is compounded by issue #5102 making it so the only way to tell "did I just miss that?" is by looking at the top of the screen to see the combo count, which is not possible in the middle of playing any fast/difficult song

**Comment by iiSaLMaN** [comment]
This would actually require per-ruleset HUD modifications to solve this correctly.

**Comment by smoogipoo** [comment]
As much as I disagree with the conclusion, I've been told per-ruleset HUD modifications aren't going to happen.

I think the way this is to be done is to duplicate the combo counter, if that's done at all.

**Comment by peppy** [comment]
Adding a catch-specific combo counter is definitely the way forward here. It can be done for legacy skins only to begin with.

**Comment by Snowleopard-osu** [comment]
If it makes more sense to have both (ie leave the current one but also add one above the catcher) I think that would be fine.  Having above catcher only would also be fine.

However, I think it would be a major complaint for most catch players if it wasn’t above the catcher at all though. I’m glad to hear there is potential for it to be implemented at least for legacy skins

**Comment by Snowleopard-osu** [comment]
As per [this peppy tweet](https://twitter.com/ppy/status/1281797986792509442?s=21) + this issue being open for over a year without resolution + recent complaints from others about this issue

Making a bump comment

**Comment by frenzibyte** [comment]
Oh I actually missed the above comments, I'll work on this one now that the direction is clear to me.

**Comment by frenzibyte** [comment]
@peppy As per the second paragraph in https://github.com/ppy/osu/issues/5103#issuecomment-610232084, are you against having a combo counter above the catcher in the default osu!lazer skin?

**Comment by peppy** [comment]
It should only be implemented for legacy skins for now. We do not have a design for the lazer default, and there is also a completely redesign incoming so it's not a good time to make changes there.
