### ISSUE TITLE
Non numerical input in ID fields

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#5105]
**Describe the bug:**
In the tournament tools I can input any character into ID fields (e. g. beatmap / player IDs) instead of just numbers.

**Screenshots or videos showing encountered issue:**
![wat](https://user-images.githubusercontent.com/27222621/59917063-29f0f680-9421-11e9-87fd-a2cd53a120e1.png)

**osu!lazer version:**
no

**Logs:**
no

**Comment by peppy** [comment]
Yeah, it's best-effort. Does this cause a crash?

**Comment by Aergwyn** [comment]
No. It's a minor thing. Will open a PR Soon™ unless characters were intended.

**Comment by peppy** [comment]
Oh sure, if you're going to fix it no issues! I just wouldn't bother myself.
