### ISSUE TITLE
Start Time of rounds are not saved

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#5106]
**Describe the bug:** 
As title says. No matter if I set a specific start time of a round or explicitly remove it. Saving the changes doesn't seem to do anything in this case as restarting the program resets the field back to current time.

**Screenshots or videos showing encountered issue:** 
![wat](https://user-images.githubusercontent.com/27222621/59918408-f1ebb280-9424-11e9-80a4-565c035b09ca.png)
what I set up

![wat](https://user-images.githubusercontent.com/27222621/59918666-b00f3c00-9425-11e9-88e3-3854f0dafd6e.png)
what it reverts to after a restart

**osu!lazer version:** 
-

**Logs:** 
[logs.zip](https://github.com/ppy/osu/files/3314181/logs.zip)

**Comment by peppy** [comment]
I've tested and it looks to be saving for m.

- Did you press enter after changing the value?
- Did you pres the "save changes" button bottom-right?

**Comment by Aergwyn** [comment]
I did press the button but I don't think I pressed enter. I can't start it to try it out as it instantly crashes all the time (see https://github.com/ppy/osu/pull/5107).

**Comment by Aergwyn** [comment]
Retesting shows that I have to use enter and the button to save changes.  
Leave either out and it doesn't save the time although name and description save just fine with just the button.

**Comment by peppy** [comment]
I'm making a fix for this (to not require the pressing of enter).

**Comment by peppy** [comment]
incorrectly referenced as closing – this requires an osu!-side change too.
