### ISSUE TITLE
Beatmap Diffs going off screen

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#5110]
**Describe the bug:** 
This beatmap has 27 beatmap difficulties and not all of them are shown by osu... This is not a problem on the website but it is on the Lazer client.

**Screenshots or videos showing encountered issue:** 
![osu_2019-06-21_18-34-28](https://user-images.githubusercontent.com/32044067/59924699-f24f7200-9453-11e9-94de-8d9c3f850340.jpg)
![osu_2019-06-21_18-43-37](https://user-images.githubusercontent.com/32044067/59924961-96d1b400-9454-11e9-8294-6e5323cf0433.jpg)

**osu!lazer version:** 2019.616.0 (latest)

**Logs:** (not needed)

**Comment by Aergwyn** [comment]
Duplicate to https://github.com/ppy/osu/issues/4929 and will be adressed by https://github.com/ppy/osu/pull/5015.

**Comment by nyquillerium** [comment]
Closing as duplicate
