### ISSUE TITLE
Possible Memory Leak Issue

### ISSUE THREAD

**Issue by MarbleStarry** [ppy/osu#5115]
**Describe the bug:** 

osu!'s memory usage constantly increases during runtime.

Current observations:
Memory usage do slowly increase steadily when game is in background and playing music.
Memory usage do increase substantially (around by 50mb to 200mb depending on the map) with each beatmap played during that session.
Memory usage do increase when same map is played over and over albeit less than it did on first play.
Memory usage do increase and stay that way until forcing garbage collection.
Enabling mods don't change any of this behaviour.
Forcing garbage collection frees up around ~~1 GB~~ 500 MB of memory used **after** clicking the button 2-3 times after going through around 10 beatmaps or so.
Increasing the memory usage again by playing beatmaps or keeping osu! running in background and forcing garbage collection again doesn't get it all the way back to it's previous usage, final memory usage do slowly accumulate as this action gets repeated.

At the time of writing the highest usage I could get was 3.5 GB before my system started aggressively swapping memory (I have 7 GB of memory total), it went down to 2.2 GB after repeatedly forcing garbage collection until it didn't go down anymore.

~~*Update:* Memory usage also increases when keeping osu! running in background with nothing playing. Forcing garbage collection doesn't seem to do anything when usage increases while game is idle.~~

**osu!lazer version:** 
2019.621.0

**OS:**
Linux Mint 19.1 Cinnamon
Kernel: 4.15.0-20-generic

**Comment by peppy** [comment]
Have you checked previous versions to see if this was a recent regression?

**Comment by MarbleStarry** [comment]
So far I have tested these releases and the behaviour is same:
2019.616.0
2019.612.0
2019.518.0

Sorry testing each one takes quite a bit of time. However the latest release seems to be eating memory more quickly. Also I couldn't reproduce one of the observations I made, I will be crossing that out on my first comment. Should I go back even more on releases to check them as well?

**Comment by peppy** [comment]
We've done some further investigation and possibly identified one source of memory leakage, which will be fixed via a framework PR (https://github.com/ppy/osu-framework/pull/2580). Please re-test in the next release.

**Comment by Joehuu** [comment]
You didn't update the framework after that PR for the recent osu release.

**Comment by peppy** [comment]
Yep, gotta wait for the next release.
