### ISSUE TITLE
Scrubbing Autoplay is not very good

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#5119]
**Describe the bug:** 
Pretty sure this is just a placeholder for a more advanced system, but currently, scrubbing in a replay isn't very good. It just plays the beatmap at a high speed. It takes a long while to catch up to the scrubhead in a long song.

**Screenshots or videos showing encountered issue:** 
<img width="549" alt="Screen Shot 2019-06-22 at 1 24 15 pm" src="https://user-images.githubusercontent.com/50823728/59958885-0f864e00-94f1-11e9-845f-2ae7406c05c8.png">

**osu!lazer version:** 
2019.616.0

**Comment by peppy** [comment]
tHis is limited by the actual performance of playing back the replay currently. It will improve over time until we can make it feel much better.
