### ISSUE TITLE
Quickly exiting the PlayerLoader, re-entering PlaySongSelect updates the selection to a null beatmap

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5120]
**Describe the crash:** If you go to the `PlayerLoader` and quickly (very fast) pressing `Esc` to reach the `MainMenu`, re-entering the `PlaySongSelect` causes the game to crash because it updates the selection to a `null` beatmap (saying that "_Can not set value to "please load a beatmap! - no beatmaps available! () []" as bindable is disabled_").

**Screenshots or videos showing encountered issue:** https://streamable.com/txh0w

**osu!lazer version:** 2019.621.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3316693/runtime.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3316698/performance-gamethread.update.log)

(notice how the runtime has not registered the `Screen changed → PlayerLoader` part (same log of the video), maybe I exited it too fast? In the video you can hear that I entered the `PlayerLoader` for a moment)

**Comment by peppy** [comment]
Are you able to reproduce this on previous releases?

**Comment by Gabixel** [comment]
Yes, tested on
- [2019.616.0](https://github.com/ppy/osu/releases/tag/2019.616.0)
- [2019.612.0](https://github.com/ppy/osu/releases/tag/2019.612.0)
- [2019.530.0](https://github.com/ppy/osu/releases/tag/2019.530.0)
- [2019.518.0](https://github.com/ppy/osu/releases/tag/2019.518.0)

**Comment by Gabixel** [comment]
Little update: I managed to make it crash also using the `Home` button instead of pressing `Esc` (It's more difficult but.. same error, nothing special), but I guess it's more likely to happen if someone uses the Escape key. It's rare, but it can happen.

**Comment by nyquillerium** [comment]
This is happening because `PlayerLoader` never gets disposed or exited, as it will never have been pushed if `PlaySongSelect` gets exited before the async load task can be completed. There's similar logic in place to handle this scenario inside `PlayerLoader`:
```
if (isDisposing)
{
       // if the player never got pushed, we should explicitly dispose it.
       loadTask?.ContinueWith(_ => player.Dispose());
}
```
Was thinking this might be a use case for something like a `PushScreenAsync` method that would dispose the loading screen if the current screen is exited, otherwise it could also be fixed locally again inside `PlaySongSelect`

**Comment by peppy** [comment]
Wouldn't it make more sense to change `LoadComponentAsync` to dispose not-yet-loaded tasks itself? Since if you're making a `PushScreenAsync` the exact same issue will still on `LoadComponentAsync`.
