### ISSUE TITLE
Install folder selection?

### ISSUE THREAD

**Issue by lunafreya** [ppy/osu#5121]
The current o!client can allow the user to choose which location they want to install osu! at. Is this also implemented in the new client?

**Comment by peppy** [comment]
We may eventually use a custom installer with this kind of support. Not sure yet.

**Comment by peppy** [comment]
If you are just looking to store your beatmaps elsewhere, this issue exists: https://github.com/ppy/osu/issues/960.

**Comment by Stargon** [comment]
Has there been an update on whether or not this feature will be implemented? Being able to control where to install osu!lazer is important for a user's disk management.

**Comment by smoogipoo** [comment]
There has been no work into a selector for it, but we do have support for portable installations now.

All you need to do is make a `framework.ini` file in the directory containing the .exe and all other files.

**Comment by peppy** [comment]
This has since been resolved; you can now choose your game data directory.
