### ISSUE TITLE
Notification Menu steals scroll focus from web 

### ISSUE THREAD

**Issue by SpikyPillow** [ppy/osu#5134]
**Describe the bug:** 
When trying to scroll on the web player with the notifications menu open instead of scrolling on the page it changes the audio volume. Particularly annoying because opening the changelog  from the notifications menu (on a new version startup) doesn't close the notification menu, so you have to click first before you can scroll through.

**Screenshots or videos showing encountered issue:** 
![ezgif com-optimize](https://user-images.githubusercontent.com/51576746/59994223-b74a6b80-9618-11e9-974f-499474b2cd2d.gif)

**osu!lazer version:** 
2019.621.0

**Comment by smoogipoo** [comment]
It'd probably feel fine if the darkening overlay was applied to the changelog overlay also.

**Comment by peppy** [comment]
I think the scrolling should still work in this scenario. It feels insanely weird that the notifications overlay makes volume controls work screen-wide.
