### ISSUE TITLE
Joining a channel with no channels joined does not always automatically select the new channel

### ISSUE THREAD

**Issue by nyquillerium** [ppy/osu#5152]
To reproduce:

- If no channels are open, join a channel
- Leave all channels so that none are open
- Join a new channel

Video showing this process: https://streamable.com/m6bwd

Typically, the channel would open itself if its the first channel joined by the user. However, because the check is for whether or not the `CurrentChannel` is null, and the `CurrentChannel` is actually being set to the `ChannelSelectorTabChannel`.

**Comment by Joehuu** [comment]
As the channel listing is moved to the same area as chat, this is no longer valid as only one can be displayed at a time. It will stay in the listing when joining channels now.
