### ISSUE TITLE
Channel selector will close when the channel is switched indirectly

### ISSUE THREAD

**Issue by nyquillerium** [ppy/osu#5157]
Because joining a channel when no channels are joined will automatically switch to the newly joined channel, the channel selector will automatically close.

Similarily, closing a channel that is currently active will cause the next available channel to be selected, closing the channel selector.

Both of these scenarios can be blocked locally in `ChannelTabControl`.

**Comment by peppy** [comment]
This seems to imply that the current channel is getting out of sync, which should never happen.

**Comment by nyquillerium** [comment]
In that case, then the chat should probably be deselected when opening channel selector. 

What would you expect chat overlay to do in this scenario? Should it keep receiving and displaying messages from the last joined channel, even though it is no longer the current channel?

**Comment by peppy** [comment]
As I said yesterday, it should probably be null.

**Comment by nyquillerium** [comment]
Simply blocking the propagation of channelselector has not quite fixed this issue, since there's still manual selections being done when tabs are opened or closed. A separate fix will be made for this.

**Comment by Joehuu** [comment]
As the channel listing is moved to the same area as chat, this is no longer valid.
