### ISSUE TITLE
Channel selector will not automatically open if there are no channels joined

### ISSUE THREAD

**Issue by nyquillerium** [ppy/osu#5161]
This logic was deliberately removed in https://github.com/ppy/osu/pull/5156 until we can fix it.

This needs to account for the fact that we may be still loading in, and a simple check for JoinedChannels is not enough as it might not have been populated. In the case we are still loading, the selector should not be toggled until we can confirm there are no channels joined. 

This can potentially be done using a check for whether or not there are anything in `AvailableChannels`.

**Comment by Joehuu** [comment]
As the channel listing is moved to the same area as chat, this is no longer valid.
