### ISSUE TITLE
Beatmap set overlay download button doesn't get updated with direct panel

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#5165]
Normally, when you download a beatmap set from the direct panel itself, opening the overlay will show the download button in downloading or downloaded or locally available state, but now it doesn't 

Regressed from #5000

**osu!lazer version:** Latest commit

**Comment by peppy** [comment]
Can you bisect where it regressed?

**Comment by iiSaLMaN** [comment]
[Before](https://streamable.com/1oczu)  -- [After](https://streamable.com/43tpn)
Sorry for the lag

**Comment by peppy** [comment]
I mean `git bisect` to find the responsible PR.
