### ISSUE TITLE
Highlight the recommended difficulty

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5172]
**Describe the new feature:** The feature is simple: highlight the recommended difficulty of a player on the carousel.

The feature is already implemented on the _Beatmaps Listing_ web page with a filter, and I think that can be very cool to see it in-game too:
![image](https://user-images.githubusercontent.com/43073074/60278016-f4f01280-98fe-11e9-9412-5869f2345a8f.png)

**Proposal designs of the feature:** 

- The idea is to highlight the recommended difficulty, based on my idea, with a golden colour and a star on the left side (but that's optional):
![Recommended Difficulty](https://user-images.githubusercontent.com/43073074/60278234-57e1a980-98ff-11e9-8b70-14e0d8e6a680.png)

- I added that star for maybe a future proposal for other "warnings" (like missing maps with a `(!)` red icon), and the player can hover with the mouse to see what does it represent:
![Recommended Difficulty pt 2](https://user-images.githubusercontent.com/43073074/60278523-ea824880-98ff-11e9-8aeb-3f719591e1f4.png)

- And we can add another text saying something like "_This is the recommended difficulty_" on the info wedge (or even inside the "Details" tab):
![Recommended Difficulty pt 3](https://user-images.githubusercontent.com/43073074/60278885-73997f80-9900-11e9-9726-5e84c0c8ab92.png)
![Recommended Difficulty pt 4](https://user-images.githubusercontent.com/43073074/60279166-dc80f780-9900-11e9-8b4f-92405d3fceee.png)

**Pros:** A gold colour makes the recommended difficulty easy to see. If the player doesn't like that, he can disable the feature in the settings.
**Cons:** Many things are already coloured yellow/gold.. obviously I don't want to make everything yellow, so you can choose what's the best colour.

**Comment by nyquillerium** [comment]
dunno if this is something @arflyte would like to give input on
