### ISSUE TITLE
Show More button doesn't appear for user beatmaps in User Overlay

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#5174]
The problem is what API returns 5 beatmaps by default, but ShowMoreButton logic expected 6. So we just need to add a `limit` into the request to make it works for any value we want.
Will be fixed via https://github.com/ppy/osu/pull/5365

**Comment by iiSaLMaN** [comment]
That's not an osu! side issue, it should be in osu-web, and isn't an issue from the beginning, you have to take the count of favourited beatmaps from the user response, and do a loop to manually store them in a list
```csharp
List<BeatmapSetInfo> favouritedBeatmapsets;

for (int i = 0; i < favouritedCount / 5; i++)
{
    var req = new GetUserBeatmapsRequest(userId, BeatmapSetType.Favourite, i);
    /* get api response */
    favouritedBeatmapsets.Concat(apiResponse.Select(b => b.ToBeatmapSet(rulesets)));
}
```
