### ISSUE TITLE
SearchTextBox no longer clears text when pressing Escape

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5177]
**Describe the bug:** The expected behaviour, when pressing `Esc`, is that the `SearchTextBox` on the carousel clears the text it contains. After that, the next `Esc` key pressed should return to the Menu.

**Screenshots or videos showing encountered issue:** https://streamable.com/116sk

**osu!lazer version:** 2019.628.0

**Comment by Joehuu** [comment]
Can reopen.
