### ISSUE TITLE
Invalid memory access

### ISSUE THREAD

**Issue by peppy** [ppy/osu#5179]
- Go into song select
- Delete a beatmap (set)
- Exit to main menu
- Force GC

![image](https://user-images.githubusercontent.com/191335/60348454-82645d00-99fa-11e9-9584-1bd0e2b5519e.png)

**Comment by Joehuu** [comment]
Can't reproduce on `2019.702.0` / `master`. Not sure what framework PR fixed this.

**Comment by peppy** [comment]
Resolved via https://github.com/ppy/osu-framework/pull/2608
