### ISSUE TITLE
Shift-Delete to delete beatmap at song select no longer works

### ISSUE THREAD

**Issue by peppy** [ppy/osu#5180]
Likely due to tab control change.

**Comment by Aergwyn** [comment]
It is the `TextBox` of the `FilterControl` eating all input. If you disable it Shift-Delete works just fine.

**Comment by peppy** [comment]
We should be able to fix this one locally in `SearchTextBox`.

**Comment by nyquillerium** [comment]
Wondering how you would propose to resolve this in `SearchTextBox`. Should we interrupt the input flow and fire an Action locally that gets handled by `SongSelect`?
