### ISSUE TITLE
Relax mod is broken in latest release.

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#5184]
In latest release **_2019.628.1_**, the relax mod appears to be broken. The relax mod does not hit the circles even if your cursor is exactly in the circle’s position on time.
**Video:** https://youtu.be/euQ06KIJRys

**Comment by dscnnctd** [comment]
**For specific device requirement:** _iPhone 7 (iOS 12)_

**Comment by Aergwyn** [comment]
Warning, loud video.
Also what I noticed. Half the time it doesn't recognize any "key"press as you can see on the counter. Can you try on a less intensive (difficult) map if it still persists?

**Comment by dscnnctd** [comment]
>Warning, loud video. ...

@Aergwyn Sorry for the loud audio, I tried to tone it down with my editing app but that does not seem enough I guess. I will try doing it with an easier one.

**Comment by dscnnctd** [comment]
**Here you go:** https://youtu.be/a0jHPHrT7Rk

**Comment by Aergwyn** [comment]
That's specifically occurring with that mod? Everything's alright with other mods or without any?

**Comment by dscnnctd** [comment]
Only Relax mod, all other mods work fine as of now.

**Comment by iiSaLMaN** [comment]
Based on what I saw, the drawable hit circles are the ones that don't get hit

**Comment by iiSaLMaN** [comment]
PR Regression #5167
