### ISSUE TITLE
Cursor freeze during osu! game play

### ISSUE THREAD

**Issue by jc-hiroto** [ppy/osu#5193]
**Describe the bug:** 
This situation just happened after I update to 2019.628.1. When playing osu!, the cursor freezes (I'm moving my mouse but the cursor is not moving for 500ms ). And the cursor immediately reposition to the new position after the freeze happened. This situation happens about every 10 secs during gameplay.

**Screenshots or videos showing encountered issue:** 
I'm sorry that I can't provide a screen recording, because when recording the game will run very slow and lags a lot.

**osu!lazer version:** 
2019.628.1

**system specs:** 
- MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
- macOS Mojave 10.14.2
- 2.9 GHz Intel Core i5
- 8GB RAM
- Intel Iris Graphics 550 1536 MB

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3342656/database.log)
[performance.log](https://github.com/ppy/osu/files/3342658/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3342659/runtime.log)
[network.log](https://github.com/ppy/osu/files/3342660/network.log)

**Comment by iiSaLMaN** [comment]
Try changing the refresh rate to Unlimited or any other option (Settings -> Display -> Refresh Rate -> Unlimited or any other option)

**Comment by peppy** [comment]
Are you running fullscreen?

**Comment by jc-hiroto** [comment]
@peppy Yes, it is in full screen mode and refresh rate set to Unlimited.

**Comment by VeiLooooo** [comment]
@jc-hiroto this is happening to me too! it started happening after i updated the game anyone has a fix??

**Comment by peppy** [comment]
For the time being, please switch from full screen. A proper fix is in the next release.
