### ISSUE TITLE
Song select absolute scroll is incorrect with large number of beatmaps

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5195]
**Describe the bug:** The absolute scroll doesn't follow the mouse correctly.

**Screenshots or videos showing encountered issue:** 
![Absolute Scroll](https://user-images.githubusercontent.com/43073074/60395714-053f0200-9b38-11e9-8830-df14d1653869.png)

**osu!lazer version:** 2019.628.1

**Comment by peppy** [comment]
Seems to work okay for a small number of beatmaps.
