### ISSUE TITLE
Bouncing animation and MenuSideFlashes not immediately visible

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5215]
**Describe the bug:** The `MenuSideFlashes` and the bouncing animation for sprite icons on the main menu seem to appear/load only in certain circumstances:
- [Entering Solo](https://streamable.com/tqi8f)
- [Entering osu!editor](https://streamable.com/jsg98)
- [Opening `MusicController`](https://streamable.com/pvk7b)

**Screenshots or videos showing encountered issue:** (Click the texts above)

**osu!lazer version:** 2019.702.0

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu/pull/5133.
