### ISSUE TITLE
Code style for object initializers

### ISSUE THREAD

**Issue by smoogipooo** [ppy/osu#522]
# Brief introduction
osu! uses object initializers extensively to construct objects. The biggest users of this methodology are objects that pertain to the draw hierarchy such as `Sprite`, `Container`, and `Box`. An example of this usage scenario can be found [here](https://github.com/ppy/osu/blob/master/osu.Game/Screens/Select/BeatmapInfoWedge.cs#L116).

At the moment there are no strict style guidelines for object initializers. This thread attempts to address this issue by resolving the following three items:
1) How items in object initializers should be ordered.
2) How items in object initializers should be grouped, and how to achieve this grouping.
3) What is the immediate plan of attack to resolve this issue and maintain further code quality standards adhering to the outcome of this issue.

# My response
I've looked through the code-base and for the most part I haven't seen a set ordering of the items. This is what bothers me the most, because I want to be able to visualize the draw hierarchy as I read the code without having to run it. This is made even more important due to the fact that object initializers are used almost exclusively with anything in the draw hierarchy.

## On: ordering
To address this issue I have adopted a bit of a methodical approach to my orderings. I have built a mental priority list of what I want to see the most, and it seems to not have changed all that much. The following is my ordering:
1) Anchors and Origins
2) Sizing + Positioning (both relative and auto) + Scale (although less strict on this)
3) Any other single-line initializers, e.g. Depth, BorderThickness, Colour
4) Any multi-line initializers, e.g. EdgeEffect, ColourInfo
5) Children (_always_ the last element)

The reasoning is simple - between priorities 1-3 I determined it's much easier to visualize the placement of the elements and the reason for the elements being there if the positioning + sizing is grouped and closer to the top. You can then very easily cross-reference to the running game and figure out where elements reside in code or where elements in code reside on the screen.
Between priorities 3-5 I determined that single-line initializers can be very easily missed if they follow a multi-line initializer. Consider the following:
```
new Container
{
    Anchor = Anchors.Centre,
    Origins = Anchors.Centre,
    Size = new Vector2(50),
    EdgeEffect = new EdgeEffect
    {
        Type = EffectType.Glow,
        Radius = 50,
        Colour = Color4.White
    },
    Colour = Color4.Black,
    Children = new Drawable[]
    {
        ...
    }
}
```
Which looks a bit less readable to me than:
```
new Container
{
    Anchor = Anchors.Centre,
    Origins = Anchors.Centre,
    Size = new Vector2(50),
    Colour = Color4.Black,
    EdgeEffect = new EdgeEffect
    {
        Type = EffectType.Glow,
        Radius = 50,
        Colour = Color4.White
    },
    Children = new Drawable[]
    {
        ...
    }
}
```

## On: grouping
A secondary method I've adopted is to group elements by their relevance. Positioning items near other positioning items, anchor items near other anchor/origin items, etc. This is achieved by "splitting" groups with a newline.
[This file](https://github.com/ppy/osu/blob/master/osu.Game/Screens/Tournament/Drawings.cs) is an extensive example of this method being used. 

## On: resolution + maintenance
The ordering of items should be consistent and strictly enforced throughout the code. However most coding practices have already lead to a pretty uniform ordering - e.g. [this](https://github.com/ppy/osu/blob/master/osu.Game/Screens/Select/BeatmapInfoWedge.cs) is not all that much different to [this](https://github.com/ppy/osu/blob/master/osu.Game/Screens/Tournament/Drawings.cs), even though the code was written independently by two (or more) different parties.

It is already very easy to determine which initializers belong to which objects as a result of the multiple indentation levels. Newlines may be used _sanely_ to show that items are grouped together, but are not strictly required or enforced and the grouping is user-defined. The following is an okay grouping:
```
new Container
{
    Anchor = Anchors.Centre,
    Origins = Anchors.Centre,

    Size = new Vector2(50),
    Colour = Color4.Black,

    EdgeEffect = new EdgeEffect
    {
        Type = EffectType.Glow,
        Radius = 50,
        Colour = Color4.White
    },

    Children = new Drawable[]
    {
        ...
    }
}
```
As is the following:
```
new Container
{
    Anchor = Anchors.Centre,
    Origins = Anchors.Centre,
    Size = new Vector2(50),

    Colour = Color4.Black,
    EdgeEffect = new EdgeEffect
    {
        Type = EffectType.Glow,
        Radius = 50,
        Colour = Color4.White
    },

    Children = new Drawable[]
    {
        ...
    }
}
```
However the following is not an okay grouping:
```
new Container
{
    Anchor = Anchors.Centre,

    Origins = Anchors.Centre,

    Size = new Vector2(50),

    Colour = Color4.Black,

    EdgeEffect = new EdgeEffect
    {
        Type = EffectType.Glow,

        Radius = 50,

        Colour = Color4.White
    },

    Children = new Drawable[]
    {
        ...
    }
}
```

As for maintenance... Because most of the code already follows the resolution set out above, there's no immediate need for a code-wide refactoring. If there are places in code that are unreadable (I believe [this](https://github.com/ppy/osu/blob/master/osu.Game/Graphics/Backgrounds/Triangles.cs#L102) is a prime example), they should be fixed on a per-case basis.

At least, that's just my $0.02 /shrug.

**Comment by Tom94** [comment]
I don't think grouping adds much in terms of readability. Although I may be biased since I've gradually started coding more densely over the recent years. (I also tend to prefer `if (foo) {` and `} else {`). Feel like it wastes less vertical space, and I haven't noticed any troubles reading.

I do very much like ordering. Most important is `Children` coming last imho, but the rest also makes sense.

**Comment by SirCmpwn** [comment]
The only rules I follow or care about are:

* Children goes last
* If nesting gets too deep, make a new subcontrol

I just eyeball it for the rest and generally it seems fine imo.

**Comment by smoogipooo** [comment]
Conclusion was reached in #osu-client.

Object initializers should be ordered such that `Children` is last. Newlines should not be used.

Closing this issue, but it can be referenced back to in the future if this comes up again.
