### ISSUE TITLE
Skip Button Fades out if you hold buttons on it

### ISSUE THREAD

**Issue by SpikyPillow** [ppy/osu#5223]
**Describe the bug:** 
If you hold either keyboard button over the skip button, it'll fade out, and do nothing. In the video I hold down mouse button once its faded out and it locks the fade out until I let go/click again.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/bkl8h

**osu!lazer version:** 
2019.702.0

**Comment by nyquillerium** [comment]
The skip button probably shouldn't be fading out when you're hovered over it imo.

**Comment by SpikyPillow** [comment]
Holding down a keyboard button is not required and i'm stupid. Having skip fade out while cursor is over is up to debate, I agree with it shouldn't be fading out, I had assumed it wouldn't normally.

The part where when you hold click once its faded out and it stays faded out is still true, though. As a tablet drag user this means it's disappeared without reason. Though to skip i'd probably need to lift my pen and click it anyway, it's still worth noting.

**Comment by peppy** [comment]
Fading on hover is intentional. It should fade unless there is user interaction with the screen (to avoid it getting stuck on the screen when the mouse is over it).
