### ISSUE TITLE
Switching Gamemodes in song select unpauses song

### ISSUE THREAD

**Issue by SpikyPillow** [ppy/osu#5224]
**Screenshots or videos showing encountered issue:** 
https://streamable.com/2wjkp

**osu!lazer version:** 
2019.702.0

**Comment by iiSaLMaN** [comment]
I don't see any issues with this, you paused the song, went back to the main menu, switched "gamemodes", the song should still be paused because **you** paused it

**Comment by SpikyPillow** [comment]
The issue is the song unpauses when you switch gamemodes _in song select_. It works fine in the main menu, which is way that's included.
If it's intentionally that way, it feels off.

**Comment by iiSaLMaN** [comment]
well, the playback overlay and the song select screen are bound together, and i don't think it needs to be fixed, because the playback overlay's actual use is inside any other screen, not in the song select screen

**Comment by peppy** [comment]
This is a valid issue. At very least, the song should not be unpaused unless it was changed (by the ruleset change request, ie. if the user has converts hidden).

**Comment by Joehuu** [comment]
Fixed in #5289.
