### ISSUE TITLE
Flashlight doesnt render HitObjects correctly

### ISSUE THREAD

**Issue by Altenhh** [ppy/osu#5234]
![image](https://i.imgur.com/jprNSAN.png)

v2019.704.0

**Comment by iiSaLMaN** [comment]
please attach the logs

**Comment by Altenhh** [comment]
i dont think logs should be required for this, but here are the logs:

[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3356944/performance-gamethread.draw.log)
[runtime.log](https://github.com/ppy/osu/files/3356945/runtime.log)

**Comment by Joehuu** [comment]
That's flashlight not hidden.

**Comment by Altenhh** [comment]
i always get that mixed up -_-

**Comment by peppy** [comment]
Can reproduce on all platforms.
