### ISSUE TITLE
osu!lazer iOS crashes whenever i try to play a beatmap

### ISSUE THREAD

**Issue by infinitygmd** [ppy/osu#5235]
I have the current version of the osu!lazer beta on iOS (iPad) and i can load the game just fine. Whenever I open a beatmap it will load, after it is done loading and I go to actually play the beatmap the game freezes and then crashes.

**Comment by swoolcock** [comment]
Some things that might help us:

1) What model iPad and which version of iOS?
2) Which beatmap(s) are you trying to load?
3) How many beatmaps do you have installed?
4) Does it show any hitobjects before crashing?

**Comment by peppy** [comment]
Probably memory exhaustion. Welcome actual logs.

**Comment by infinitygmd** [comment]
1. iPad mini 2 & iOS 12.3.1
2. Razihel & Virtual Riot - One For All, All For One  (Celsius Insane).
3. I have 3 beatmaps installed.
4. No it did not show any objects before installing.
(I should probably add that when i loaded a beatmap in OSU! Mania it let me load in the map).

**Comment by Joehuu** [comment]
> Probably memory exhaustion. Welcome actual logs.

Yep.

I have the same device, and now it should be somewhat playable (i.e. gameplay can load, but can be slow with high diff maps and crash). Closing as this is a performance issue and is a constant work in progress.
