### ISSUE TITLE
Chat gets hidden behind mobile software keyboard 

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#5236]
**Describe the bug:** 
when the chat is opened on iOS, the software keyboard obstructs it

**Screenshots or videos showing encountered issue:** 
![F7465C64-2B74-4A19-9768-237429B52D20](https://user-images.githubusercontent.com/50823728/60635407-13ea2980-9e56-11e9-8bca-61bab7838505.png)
![0C87A6B3-A7E2-4418-A15D-BB3FEA321412](https://user-images.githubusercontent.com/50823728/60635408-13ea2980-9e56-11e9-935d-075f893fabcf.png)

**osu!lazer version:** 
2019.702.0

**Comment by swoolcock** [comment]
Known issue, merging https://github.com/ppy/osu-framework/pull/2420 will be the first step in supporting this.

**Comment by Joehuu** [comment]
Fixed in iOS and Android with SDL.
