### ISSUE TITLE
“Return” on iOS Software keyboard, on song select search, shouldn’t start a beatmap

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#5237]
**Describe the bug:** 
Pressing return on the iOS software keyboard on song select shouldn’t start a map, but hide the keyboard.

![B856FA57-8B5E-4345-80D9-5682568C23D7](https://user-images.githubusercontent.com/50823728/60641730-69cbcb00-9e70-11e9-856c-ae6659ddad2f.png)

**osu!lazer version:** 
2019.702.

**Comment by peppy** [comment]
Not sure about this one. Isn't there always a "hide keyboard" button?

**Comment by yuuiko** [comment]
Hitting enter will enter the easy map that becomes active. It’s not desired..

iPhone keyboards don’t have a hide button.
Added screenshot into the issue

**Comment by frenzibyte** [comment]
Cannot reproduce anymore, likely because we moved input handling to SDL.
