### ISSUE TITLE
Implement wiki overlay

### ISSUE THREAD

**Issue by MikelJohnson** [ppy/osu#5250]
It would be really convenient have in-game wiki, especially for the new players, it would also increase it's visibility thus increasing the amount of contributions.

**Comment by peppy** [comment]
This is planned. Markdown parsing support is already there, as well as general overlay logic. It should be a fairly trivial implementation.

**Comment by iiSaLMaN** [comment]
Are there planned designs for this? @arflyte

**Comment by arflyte** [comment]
The design is almost the same as the new web content pages (news, changelog, etc), haven't adapted wiki designs to it yet.
