### ISSUE TITLE
Watching your own replays throws an unhandled exception

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#5258]
**Screenshots or videos showing encountered issue:** https://streamable.com/0p0e8

**osu!lazer version:** 2019.704.0

**Logs:** [runtime.log](https://github.com/ppy/osu/files/3361134/runtime.log)

After looking at the logs and where the exception was thrown, it seems that the user's replays are not being saved, which results in a score info with empty files.

**Comment by peppy** [comment]
The button should not be visible in such cases.
