### ISSUE TITLE
Fail to open local replays to watch

### ISSUE THREAD

**Issue by serenityP** [ppy/osu#5271]
**Describe the bug:** 
Cannot open the local replay to watch.
But global online ranking replays can be watched smoothly.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.704.0
**Logs:**

**Comment by iiSaLMaN** [comment]
#5260 disabled that for now as we don't save local replays currently, better to close this and open a feature request for saving local replays
