### ISSUE TITLE
Storyboard switcher only works one way

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5280]
**Describe the bug:** 
You can disable the storyboard if you enabled it when the beatmap was loading, and then reenable it again, but you can't do the opposite, black screen comes up. Video shows how the bug could be recreated.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=3l2yBSHg0U8

**osu!lazer version:** 
2019.704.0

**Comment by peppy** [comment]
It seems like the toggle *does* work, but playback starts at a point far too late in the storyboard.
