### ISSUE TITLE
Flashlight doesn't work correctly on android

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5282]
**Describe the bug:** 
Circular passive dim is not applied which leads to a full visible map as long as you are not clicking the hit objects, but if you rotate the screen it goes back to normal.
Might be a duplicate of #4961 

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=hYmRtDiqtgM

**osu!lazer version:** 
2019.704.0

**Android device Specifications:**
OS | Android 8.0 (Marshmallow); MIUI 10.2
Chipset | Qualcomm MSM8996 Snapdragon 821
CPU | Quad-core (2x2.35 GHz Kryo & 2x1.6 GHz Kryo)
GPU | Adreno 530

**Comment by peppy** [comment]
I believe this also applies to iOS.
