### ISSUE TITLE
On-screen keyboard bug only appears once

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5284]
**Describe the bug:** 
The on-screen keyboard will only appear once, and after that, to reopen it, user will have to reopen the whole Messages tab. Also, as shown in the video, I believe that the UI of the messages container should also move up to match the height of the on-screen keyboard. Because right now it is not possible to see what you are trying to write. 

**Screenshots or videos showing encountered issue:** 
https://youtu.be/jgzQ5CKJwSE

**osu!lazer version:** 
2019.704.0

**Android device Specifications:**
OS | Android 8.0 (Marshmallow); MIUI 10.2
Chipset | Qualcomm MSM8996 Snapdragon 821
CPU | Quad-core (2x2.35 GHz Kryo & 2x1.6 GHz Kryo)
GPU | Adreno 530

**Comment by swoolcock** [comment]
The UI portion of your issue will be addressed in #5236
