### ISSUE TITLE
heelp lazer wont open

### ISSUE THREAD

**Issue by lolis-are-mine** [ppy/osu#5286]
installition has failed
help REEEEEEEEEEEE

lazer version:
2019.704.0-1

specs pls dont bully me:
processer:AMD A8-7650k Radeon R7,10 compute cores 4c+4g
3.30 ghz
 
windows 10 32-bits x 64
-based processor
16 gb 2.96 gb usable 

[THE LOG.txt](https://github.com/ppy/osu/files/3365601/THE.LOG.txt)

**Comment by iiSaLMaN** [comment]
Can you please open a clean issue and save the "super long" log in a file and attach it, because literally no one will help you with this type of information.

**Comment by naoey** [comment]
This issue is a duplicate. It's being tracked at #3984.

**Comment by lolis-are-mine** [comment]
oh shit no one will help me welp have to fix shit
lol
