### ISSUE TITLE
Crashing from the main menu after exiting the editor

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5288]
**Describe the crash:** 
I was looking at the beatmap, did some timeline jumps, then exited back to the main menu and the game crashed after like 5 seconds (actually maybe it was an instant crash when i got into the song select)

**osu!lazer version:** 
2019.704.0

**Logs:** 
[network.log](https://github.com/ppy/osu/files/3365770/network.log)
[performance.log](https://github.com/ppy/osu/files/3365771/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3365772/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3365773/updater.log)
[database.log](https://github.com/ppy/osu/files/3365774/database.log)

**Computer Specifications:** 
CPU - I7 4790
GPU - GTX 1070Ti
RAM - 8GB

(sorry for no video footage, will set up shadow play from now on)

**Comment by peppy** [comment]
This is fixed in master and will be fixed in the next build (via https://github.com/ppy/osu/pull/5243).
