### ISSUE TITLE
Sometimes when selecting another beatmap the track restarts

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#5292]
**Describe the bug:** Sometimes when selecting another beatmap in the same beatmap set (that contains the same track), the track restarts

**Screenshots or videos showing encountered issue:** https://streamable.com/w3yvh

**osu!lazer version:** 2019.704.0

**Logs:** [runtime.log](https://github.com/ppy/osu/files/3365963/runtime.log)

**Comment by Aergwyn** [comment]
Can you check if it's actually the same track? It should only restart inside the same set if that's the case iirc.

**Comment by l3lackShark** [comment]
@Aergwyn can confirm that issue. Was having it earlier this day. It seems to apply to every beatmap, it's just not consistent https://youtu.be/M2htORtyyDs (also any thoughts on that black screen at the end of the video, couldn't repeat it afterwards)

**Comment by iiSaLMaN** [comment]
> Can you check if it's actually the same track? It should only restart inside the same set if that's the case iirc.

Yes, they use one mp3 file
