### ISSUE TITLE
Leaderboard sections should be hidden if no beatmap are available.

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#5300]
When you don't have beatmaps, `DummyWorkingBeatmap` is used as the working beatmap to tell on the wedge that there are no beatmaps, the problem is you get wrong messages when viewing the leaderboard `Leaderboards are not available for this beatmap`

the leaderboard should probably be hidden if there are no beatmaps available.

**Comment by iiSaLMaN** [comment]
@peppy @arflyte What do you think about hiding the leaderboard sections, although it doesn't feel right having an empty section, what are your opinions?

**Comment by peppy** [comment]
I think the current path forward is changing the message but leaving it visible.

**Comment by iiSaLMaN** [comment]
> I think the current path forward is changing the message but leaving it visible.

Not sure what type of message to show, suggestions?

**Comment by peppy** [comment]
"No beatmap selected" maybe
