### ISSUE TITLE
cannot even install the game, don't have an acccount error

### ISSUE THREAD

**Issue by SlapLumehsBooteh** [ppy/osu#5301]
[Image](https://i.redd.it/3zwmcgzv73931.png)

**Comment by iiSaLMaN** [comment]
Can you please give us information about your specs, CPU, GPU, Memory, OS Version, Architecture (is it 32-bit or 64-bit)

**Comment by peppy** [comment]
This repository is for help with lazer. Please use the forums for support for stable.
