### ISSUE TITLE
Lazer on Android can't realy change audio devices

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5302]
**Describe the bug:** **Probably framework side** If you attempt to change audio output device on android it shows you only 4 options: default, default, default(alarm), default(voice),
tried fixing by adding "MODIFY_AUDIO_SETTINGS" permision into manifest but it didn't help

**Screenshots or videos showing encountered issue:** 
![Screenshot_2019-07-08-21-33-11-063_sh ppy osulazer](https://user-images.githubusercontent.com/32620809/60837645-f35cff00-a1c8-11e9-8be8-d7b873b9df2c.png)
**osu!lazer version:** commit ffc3c9f8f670c98a10900d5451f354920d7433c1

**Logs:** Didn't find the way to reach them at android

**Device:**
Xiaomi redmi 5a
android 7.1.2

**Comment by Fabricio10** [comment]
Hi, could you provide me the app for me to test?

**Comment by ticotaco72** [comment]
closing in favor of https://github.com/ppy/osu-framework/issues/2884 cause this is surely framework side
