### ISSUE TITLE
Add osu!catch poison fruit/mines

### ISSUE THREAD

**Issue by chrsbell** [ppy/osu#5304]
**Describe the new feature:** 

I think we could spice up osu!catch mapping and the gamemode in general by adding poisonous fruits, or mines, which will break your combo if you touch them. They could also possibly have some other effect like causing a random AR change for a certain amount of seconds to throw off players. Mappers could use the poison fruits to add visual flair to their maps as well as restrict movement without changing the CS.

**Proposal designs of the feature:** 

A simple design of a regular fruit but with poison oozing from it. Of course this should be skinnable. Note that the poison fruits would need to be mapped specifically for ctb, so they wouldn't exist in converts. That pretty much covers what I had in mind, please share ideas and criticism!

**Comment by dscnnctd** [comment]
In my opinion, this should be a _mod_ instead of implementing it as a part of the gameplay.
