### ISSUE TITLE
osu!lazer crashes when watching replay (Android)

### ISSUE THREAD

**Issue by Hazuki-san** [ppy/osu#5308]
**Describe the crash:** osu!lazer crashes when click Watch Replay button

**Screenshots or videos showing encountered issue:** https://youtu.be/5SfjUpbQGq4

**osu!lazer version:** 2019.704.0 (Android)

**Logs:** None (I don't know where to get it)

**Computer Specifications:**

**Comment by iiSaLMaN** [comment]
You can't watch your own replays as we don't save it yet. check if you can watch a replay of someone in the global section

**Comment by Hazuki-san** [comment]
Ah, I see. It's working, yup.

**Comment by iiSaLMaN** [comment]
@Hazuki-san i already opened a one.
