### ISSUE TITLE
Scoring

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#5310]
Basically, no matter how well I do in Lazer, I can never get above 1,000,000 points in Lazer
<img width="2048" alt="Screen Shot 2019-07-09 at 10 15 15 AM" src="https://user-images.githubusercontent.com/50627538/60895466-b75e8400-a232-11e9-987f-4ddb17984a27.png">

I am currently playing on the MacBook version of Lazer. If the scoring can change, it would be great.

**Comment by peppy** [comment]
This is the default lazer scoring. You can change the display in options if you want something closer to stable.

**Comment by X4X5** [comment]
The only options I see are Classic and Standarized. Even Classic seems very close to Standarized.

**Comment by peppy** [comment]
It shouldn't be.

**Comment by X4X5** [comment]
The score I posted just now was when I chose Classic as the scoring

**Comment by peppy** [comment]
Now go and compare with stable.
