### ISSUE TITLE
[Android] Crashes right before game starts

### ISSUE THREAD

**Issue by tasnimtamim** [ppy/osu#5312]
**Describe the crash:** 
Launching the game will show a blue-black tinted screen for few seconds and then goes to black screen to what I assume the game starting to launch and then it immediately crashes. 
**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/dqmvfpi.jpg
**osu!lazer version:**  2019.704.0 (Play Store)

**Logs:** 
Logcat+dmesg+Device info (Please ignore device info, it's not correct)
http://s000.tinyupload.com/index.php?file_id=89106199449990171915 
**Computer Specifications:** 
Phone: LAVA Iris 702
CPU: MediaTek MTK 6580 @1.30GHz
GPU: Adreno 530 @624MHz
RAM: 1GB
OS: Android 6.0 (Custom ROM with false Samsung branding)

**Comment by peppy** [comment]
Please build from master and debug the issue and/or provide actual osu! logs. System-wide ones are not helpful in this case.

**Comment by TheComputerGuy96** [comment]
Duplicate of #4235? That's the same underlying issue but on the desktop version

**Comment by iiSaLMaN** [comment]
@TheComputerGuy96 No, this is not. the cause of #4235 is because the OpenGL version of their GPU card is below OpenGL 3 (OpenGL 2.X), as for this one, it seems that Adreno 530 supports OpenGL 3.1

**Comment by tasnimtamim** [comment]
@peppy Sorry for very late response, just got the notification. I don't have access to a PC so can't build. How can I retrieve osu! logs if it crashes right away? I have tried searching every path on sdcard and there's none. It doesn't even creates a folder onto sdcard/Android/data which one of my other phone did. I tried searching log files on /data/data/ppy.osu.lazer and /data/app/ppy.osu.lazer-1 too and there's none.

**Comment by iiSaLMaN** [comment]
> @peppy Sorry for very late response, just got the notification. I don't have access to a PC so can't build. How can I retrieve osu! logs if it crashes right away? I have tried searching every path on sdcard and there's none. It doesn't even creates a folder onto sdcard/Android/data which one of my other phone did. I tried searching log files on /data/data/ppy.osu.lazer and /data/app/ppy.osu.lazer-1 too and there's none.

Check for lazer's game data and attach the logs folder here.

**Comment by TheComputerGuy96** [comment]
@iiSaLMaN The OP mistyped the GPU name sur

**Comment by l3lackShark** [comment]
I believe that Android version of Lazer doesn't store logs as of yet.  https://imgur.com/a/FNkCoPa

**Comment by tasnimtamim** [comment]
This is the GPU/Spec info I got from a website:
Chipset:Mediatek MT6580M
CPU #1 freq.:1300.0 MHz (4-core)
GPU Type:ARM Mali-400

**Comment by TheComputerGuy96** [comment]
> This is the GPU/Spec info I got from a website:
> Chipset:Mediatek MT6580M
> CPU #1 freq.:1300.0 MHz (4-core)
> GPU Type:ARM Mali-400

Please edit your issue with the correct GPU

**Comment by iiSaLMaN** [comment]
@TheComputerGuy96 Just noted, thanks for your correction.

> This is the GPU/Spec info I got from a website:
> Chipset:Mediatek MT6580M
> CPU #1 freq.:1300.0 MHz (4-core)
> GPU Type:ARM Mali-400

seems that ARM Mali-400 supports up to OpenGL 2, that's why it crashes, OpenGL 2 is not supported at all.

**Comment by tasnimtamim** [comment]
Last time I checked on my Linux PC (8 months ago), Lazer was able to launch on my OpenGL 2.1 GPU. Didn't knew it was changed. Thanks for the info.

**Comment by TheComputerGuy96** [comment]
Some more observations:
If I change GLES3 to GLES2 in https://github.com/ppy/osu-framework/blob/master/osu.Framework.Android/AndroidGameView.cs#L47, the game loads and I can hear audio and press the buttons of the osu!lazer interface, but the screen is black (with a few exceptions): https://imgur.com/a/HDCWwvb

**Comment by TheComputerGuy96** [comment]
@swoolcock Why have you disliked my comment? 🌚

**Comment by swoolcock** [comment]
Because I very much doubt it is related to the ticket you linked.

**Comment by TheComputerGuy96** [comment]
@swoolcock But both issues are OpenGL version-related

**Comment by swoolcock** [comment]
OpenGL is not the same as OpenGL ES, so you can’t make broad assumptions of version conflicts.
