### ISSUE TITLE
osu!lazer not registering input from soft keyboard

### ISSUE THREAD

**Issue by Stalemated** [ppy/osu#5315]
**Describe the bug:** 
Whenever you click on a text box (beatmap search, osu!direct search, even text boxes for login credentials) soft keyboard shows up, but doesn't let you input anything, meaning that you can't even log in to the game

**Screenshots or videos showing encountered issue:** https://streamable.com/0mio7

**osu!lazer version:** 2019.704.0

**Android device specifications:** 
Brand: Google
Model: Pixel XL
OS: Android 9.0 (Pie)
Chipset: Qualcomm MSM8996 Snapdragon 821

**Comment by peppy** [comment]
https://github.com/ppy/osu-framework/issues/2631
