### ISSUE TITLE
Star Rating does not update with mods

### ISSUE THREAD

**Issue by JuanM4T** [ppy/osu#5320]
Describe the missing feature: The sr of a map does not update with easy, half time, hr, dt. The original map sr is the same as shown in the picture.

![Screenshot_20190710-121906](https://user-images.githubusercontent.com/52723130/60963944-69b94880-a312-11e9-9d3d-2aaf6a7a4c56.jpg)

**Comment by JuanM4T** [comment]
https://i.imgur.com/rIu91cZ.png

**Comment by iiSaLMaN** [comment]
Are we gonna use the same design as the stable version?, yellowing the star rating and any changed details (cs, hp, acc, ar)

**Comment by JuanM4T** [comment]
acc=od?

**Comment by Poyo-SSB** [comment]
#3271 and #3272 from about a year ago intended to implement this—they might be useful as a starting point.

**Comment by HerendraTJ** [comment]
Still no update with the issue?

**Comment by peppy** [comment]
There have been no updates.

**Comment by smoogipoo** [comment]
Implemented via https://github.com/ppy/osu/pull/9637
