### ISSUE TITLE
Song duration always shows 0:00 on maps added before #5290

### ISSUE THREAD

**Issue by Desconocidosmh** [ppy/osu#5324]
The song duration in the SongSelect menu always shows 0:00 on maps which has been added before PR #5290. Re-downloading the map seems to fix the issue.

Screenshots or videos showing encountered issue: https://imgur.com/a/WcHb6xz

**Comment by iiSaLMaN** [comment]
Looks like a regression from PR #5290 

*oops..*

**Comment by Desconocidosmh** [comment]
I kinda suspected it, since it seems to be a rather new bug.

**Comment by iiSaLMaN** [comment]
Sorry, it's not a regression, the length property has been moved to `BeatmapInfo`, that means you need to re-download your beatmaps, please download a new beatmap and check if the length is still 0

**Comment by Desconocidosmh** [comment]
Yep, seems like that's it. Any newly downloaded map has valid duration. So, the issue's closed?

**Comment by Joehuu** [comment]
The BeatmapSetOverlay's time is 0

**Comment by iiSaLMaN** [comment]
> Yep, seems like that's it. Any newly downloaded map has valid duration. So, the issue's closed?

You can rename the issue to something like `Beatmap length 0 on old beatmaps` or something like that (don't take my title)

> The BeatmapSetOverlay's time is 0

Please open another issue for this

**Comment by Desconocidosmh** [comment]
@iiSaLMaN `Song duration always shows 0:00 on maps added before #5290`. Sounds good?

**Comment by iiSaLMaN** [comment]
> @iiSaLMaN `Song duration always shows 0:00 on maps added before #5290`. Sounds good?

let's go for that for now

**Comment by peppy** [comment]
This is intentional. Please re-import your beatmaps or wait until we have the ability to reprocess already-loaded beatmaps.
