### ISSUE TITLE
Mouse rapidly sliding across game screen

### ISSUE THREAD

**Issue by jkitl** [ppy/osu#5328]
I build and run osu!lazer on my Linux Mint MATE PC running Tessa 19. I ran it, played a couple times, then shut it down. I messed with the sensitivity settings of the game, and now moving my mouse on screen at all causes it to slide that direction to the other side of the games screen!

PS. I just reinstalled it... still doing the same thing!

**Comment by peppy** [comment]
ctrl-alt-shift-r should reset all input options.

**Comment by jkitl** [comment]
thank you!
