### ISSUE TITLE
osu! crashes if the music finishes before the replay ends (Android)

### ISSUE THREAD

**Issue by minhducsun2002** [ppy/osu#5329]
**Describe the crash:** 
After doing a fast-forward during replaying (by seeking using the bottom progress bar), the replay itself will speed up to catch up with the current music. However, if the music finishes before the replay could catch up, osu! would then crash.

**osu!lazer version:** 2019.704.0
![Screenshot_2019-07-11-17-25-38-321_com miui bugreport](https://user-images.githubusercontent.com/32769878/61043798-546f1780-a401-11e9-8374-5f8b04647485.png)

**Computer Specifications:** Xiaomi Redmi 6, 3GB - 32GB variant
![Screenshot_2019-07-11-17-36-31-110_com termux](https://user-images.githubusercontent.com/32769878/61044280-7ddc7300-a402-11e9-95cc-ea9e717b6fdf.png)

**Comment by peppy** [comment]
Please debug or provide actual osu! logs (reopen if you manage either).
