### ISSUE TITLE
Make the Android version support screen touch

### ISSUE THREAD

**Issue by TMAKERNz** [ppy/osu#5337]
Well i just got news from the community that Osu!! Is arrived on mobile version and i glad to hear it
But when i tried to played it. It gone really wrong
Some of the mode doesn't support screen touch
It really dissapointing me because i can't play it. can you guys make the game is support with touch screen? I really want to play this game on android version

**Proposal designs of the feature:**

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/4201
