### ISSUE TITLE
Replay imports fail with database errors

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#5342]
**Describe the bug:** Importing scores / replays from stable results in database errors for a lot of them. As an example: Download https://osu.ppy.sh/beatmapsets/243411#osu/561497 and try to import 
[this replay](https://github.com/ppy/osu/files/3386489/zip.cuz.github.zip).

**osu!lazer version:** 2019.704.0

**Logs:** 
[error.txt](https://github.com/ppy/osu/files/3386500/error.txt)

**Comment by peppy** [comment]
This looks like you're importing the same replay twice. Is that the case?

**Comment by Morilli** [comment]
That is the entire log that gets created when drag-and-dropping this very replay file into the osu!lazer window (just once).

**Comment by Morilli** [comment]
The errors are fixed via #5508. The replays can not be watched though.

**Comment by peppy** [comment]
Could you explain why they cannot be watched?

**Comment by Morilli** [comment]
> Could you explain why they cannot be watched?

Yes, it seems like they aren't being put into the database or something. Importing the replay and trying to watch it will either

- Crash the game
- Select a different replay instead

See [video](https://streamable.com/zti1z).
Note that for all replays that cannot be watched it opens the very same replay (of ``Taking Over``) every single time. I reimported all scores; before I did that it would crash the game every time instead.

**Comment by peppy** [comment]
i need logs, not video.

**Comment by Morilli** [comment]
Not sure what kind of logs you expect there to be. The game doesn't log (or I haven't found anything about it in the log files) about which replay file is played, it also doesn't show any kind of errors.

**Comment by peppy** [comment]
Your previous post said it will "crash the game". A log of this crash would be a great start.

**Comment by Morilli** [comment]
After I reimported all scores I was unable to get the game to crash again, it will just choose a different replay (or even the correct one) to play. However I was able to find a crash log in windows' event viewer:
[event_crash.log](https://github.com/ppy/osu/files/3444309/event_crash.log)

**Comment by peppy** [comment]
Thanks, that's perfect. Could you please test against my PR if you are able?

**Comment by Morilli** [comment]
Seems to work perfectly fine on that PR 👍
