### ISSUE TITLE
Finishing a beatmap while importing maps freezes the game

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#5346]
**Describe the bug:** When a beatmap import is running (in my case the ``Import beatmaps from stable`` option) and a map is finished, the game just freezes for a long time, but never long than the beatmap import takes. This is a relatively major issue because it forces you to either wait multiple minutes or force-close the game.

**Screenshots or videos showing encountered issue:** https://streamable.com/hka2w

**osu!lazer version:** 2019.704.0 / master

**Logs:** (Couldn't find anything related to this)

**Comment by peppy** [comment]
Worth investigating further.

**Comment by Injabie3** [comment]
+1, encountered the same thing on Lazer 2019.730.0.
