### ISSUE TITLE
Leaderboard display does not comply with user score display setting

### ISSUE THREAD

**Issue by ZeroAurora** [ppy/osu#5350]
**Describe the bug:** 
I've known that osu!lazer will use the "Standardised" scoring method by default and "Classic" still exists in settings. However, when I played one beatmap using two different scoring method, the two different scores showed in the same leaderboard.

~~*Solutions I came up with: The "Classic" score can be shown to players who choose it, but they should see their "Standardised" score and be prompted that "This is the real score being uploaded to the server". All the scores in the server before should also be converted to "Standardised" score when lazer is officially released.*~~

**Screenshots or videos showing encountered issue:** 
![Image1](https://user-images.githubusercontent.com/25359455/61165805-b93c8600-a557-11e9-8ffb-acf3bbcebf6c.png)

**osu!lazer version:** 
2019.704.0

**Logs:** 
(No logs needed)

(I'm sorry if it is duplicated or I chose a wrong type of issues. And I'm also sorry for my bad English.)

**Comment by peppy** [comment]
The leaderboard has not been updated to use the new display method. Currently it's reading from a statically stored score value, whereas it should be recalculating per score.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/10106.
