### ISSUE TITLE
all beatmaps times are 0 seconds

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#5351]
**Describe the bug:** 
all beatmaps are 0 seconds according to the calc

**Screenshots or videos showing encountered issue:** 
![osu_2019-07-12_23-00-45](https://user-images.githubusercontent.com/44514667/61166799-60d69b80-a4f9-11e9-960d-38d6dcaf5291.jpg)
![osu_2019-07-12_23-00-43](https://user-images.githubusercontent.com/44514667/61166800-646a2280-a4f9-11e9-9317-24e8a102db73.jpg)
![osu_2019-07-12_23-00-40](https://user-images.githubusercontent.com/44514667/61166801-66cc7c80-a4f9-11e9-9140-7a1615fdc881.jpg)

**osu!lazer version:** 
20190713

**Logs:** 
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3388420/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3388421/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3388422/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3388423/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3388424/runtime.log)
[database.log](https://github.com/ppy/osu/files/3388425/database.log)
[network.log](https://github.com/ppy/osu/files/3388426/network.log)
[performance.log](https://github.com/ppy/osu/files/3388427/performance.log)

**Notes:**
the bug occurred after updating to 20190713

**Comment by peppy** [comment]
This can be fixed by reimporting beatmaps. Eventually we will have a process that automatically reprocesses when required.
