### ISSUE TITLE
Global score of a beatmap appears on local leaderboard.

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#5352]
Standardized global score in a global leaderboard appears in local leaderboard for unknown reason. Possibly after watching a replay of a player in a global leaderboard?
**Image:**
![16E95BB8-CF09-4183-86F1-7B2FF97A66AE](https://user-images.githubusercontent.com/48611569/61167072-11db3700-a4f6-11e9-952c-547679820b5e.jpeg)

**Comment by dscnnctd** [comment]
**Version:** _latest release_

**Comment by Joehuu** [comment]
Yes, you downloaded the replay locally. There should be an option to watch directly and not download though.

**Comment by dscnnctd** [comment]
So that means, this is intended to happen?

**Comment by peppy** [comment]
Yes, this is intentional. Just like in osu-stable, when you download a replay it is added to your local scores.
