### ISSUE TITLE
Unable to login on Debian Buster (10)

### ISSUE THREAD

**Issue by minhducsun2002** [ppy/osu#5356]
**Describe the bug:** 
Logging in simply fails and exits to the login form.

**Screenshots or videos showing encountered issue:** [`simplescreenrecorder-2019-07-14_18.39.36.mp4.zip`](https://github.com/ppy/osu/files/3389818/simplescreenrecorder-2019-07-14_18.39.36.mp4.zip)

**osu!lazer version:** 
2019.713.0, self-compiled with `dotnet publish osu.Desktop --configuration Release`
![image](https://user-images.githubusercontent.com/32769878/61183130-5d612280-a667-11e9-8a60-5bfc5e427624.png)

- Compilation & runtime platform :
![image](https://user-images.githubusercontent.com/32769878/61183159-b761e800-a667-11e9-8db0-c927f509dad1.png)

**Logs:** [`network.log`](https://github.com/ppy/osu/files/3389823/network.log)

**Comment by iiSaLMaN** [comment]
Looks like the issue is deep inside .NET Core libraries (check https://github.com/dotnet/corefx/issues/33179)

**Comment by iiSaLMaN** [comment]
It's a problem with .NET Core 2.X when upgrading from Debian Stretch (9) to Debian Buster (10), you need to manually tell .NET Core Runtime to load `libssl` in version 1.1 instead of 1.0, check https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Compatibility#debian-buster-upgrade for how to do that

**Comment by minhducsun2002** [comment]
Thanks.

I cannot remove the obsolete package though - I'm still on .NET Core 2.2. I guess specifying `CLR_OPENSSL_VERSION_OVERRIDE=1.1` does the trick.

Not sure if this counts as fixed or not.

**Comment by iiSaLMaN** [comment]
> Thanks.
> 
> I cannot remove the obsolete package though - I'm still on .NET Core 2.2. I guess specifying `CLR_OPENSSL_VERSION_OVERRIDE=1.1` does the trick.
> 
> Not sure if this counts as fixed or not.

We need to upgrade to .NET Standard 2.1 to get this fully fixed, you can keep this closed (also, please change the title to match the exact issue `Unable to login on Debian Buster (10)`)

**Comment by minhducsun2002** [comment]
Well it means upgrading to a preview version. Worth taking risk though (after all, I've been using Buster since it was still beta, and right now I'm still using Debian Unstable).

Okay, closing this issue for now.

(I see you on Discord :smiley:)
