### ISSUE TITLE
No Music in PlayerSongSelect

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5358]
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=22tasgfcAF0

**osu!lazer version:** 
#5294 

**Logs:** 
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3390137/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3390138/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3390139/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3390140/updater.log)
[database.log](https://github.com/ppy/osu/files/3390141/database.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3390143/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3390144/performance-gamethread.draw.log)

I'm still in this broken state, so if you want to make me do some additional tests, please provide some additional information on how I should do it. Might be a duplicate of #4937

**Comment by peppy** [comment]
Did you pause via the music controller?

**Comment by l3lackShark** [comment]
No, I think I was just afk for like an hour in the fail menu and then got back to the song selection and it happened immediately.

**Comment by peppy** [comment]
Does toggling pause in the music controller fix this?

**Comment by ticotaco72** [comment]
This sounds similar to https://github.com/ppy/osu/issues/2845

**Comment by l3lackShark** [comment]
@peppy Unfortunately I had to close this game, I'll try to reproduce this if I can.

**Comment by l3lackShark** [comment]
@peppy And I did actually. Yes, I can confirm that toggling the controller fixes this. (Keep in mind that I'm using [this](https://github.com/peppy/osu/tree/skin-circle-fade-out) version of lazer and it might be outdated to the point that fix for #4937 is not applied.
https://www.youtube.com/watch?v=8V5ueboce2k

**Comment by l3lackShark** [comment]
@peppy Alright, I managed to capture the process that is required to reproduce this (2019.713.0)
https://www.youtube.com/watch?v=K7BG7FLtK-8

**Comment by l3lackShark** [comment]
Actually no, scrap all of that, if you just pause the song in the music controller it will be paused even if the map is being changed.

**Comment by Gabixel** [comment]
Also on the latest release, seems that pausing the music is the best way to reproduce this issue: https://streamable.com/n9xdm

**Comment by peppy** [comment]
This is an intentional change, which may be adjusted in the future.
