### ISSUE TITLE
lag frame

### ISSUE THREAD

**Issue by cmaster25** [ppy/osu#5360]
when i have storyboard on with background blur and dim on 100% it lags

https://drive.google.com/file/d/1hvHofMXQCTtIiuyy7kHFqBXAyLxH8SRm/view?usp=drivesdk

2019.713.0

please fix it for people like me who have it like this.

**Comment by l3lackShark** [comment]
Please open up the video for public access.

**Comment by iiSaLMaN** [comment]
Missing details, please provide the logs, does it happen only when setting the blur and dim to 100%? do you get the lag when disabling storyboard?

**Comment by peppy** [comment]
Cannot reproduce with same settings.
