### ISSUE TITLE
Mods Leaderboard doesn't show scores with only selected mods

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5361]
**Describe the bug:** If I understand correctly, the "Mods" leaderboard should return scores with *only* the selected mods, but it doesn't seem work exactly like that.
In the following screenshots, you can see that I have `Hard Rock` and `Hidden` enabled, but leaderboards also show scores with:
- `Hard Rock`, `Double Time` & `Hidden`
- `Double Time`/`Nightcore` & `Hidden`
- `Sudden Death` & `Hidden`
- `Hidden` only
- `Hard Rock` only (etc.)

**Screenshots or videos showing encountered issue:** 
![Mods1](https://user-images.githubusercontent.com/43073074/61187976-e9c81100-a678-11e9-89af-d825e5645748.png)
![Mods2](https://user-images.githubusercontent.com/43073074/61187987-f9dff080-a678-11e9-8366-eb55cd71ef82.png)
![image](https://user-images.githubusercontent.com/43073074/61187991-07957600-a679-11e9-8dae-5e1fff486bfb.png)

**osu!lazer version:** 2019.713.0

**Comment by iiSaLMaN** [comment]
Can you please give me the name of the beatmap of this leaderboard

**Comment by iiSaLMaN** [comment]
That's exactly how the web handles it, it checks if the score contains one of the mods selected, not all of them, as you can see in the combination of mods you showed us:
> Hard Rock, Double Time & Hidden
Double Time/Nightcore & Hidden
Sudden Death & Hidden
Hidden only
Hard Rock only (etc.)

They all have at least one of the selected mods

**Comment by Gabixel** [comment]
[**Sure**](https://osu.ppy.sh/beatmapsets/779173), but it seems to happen for any leaderboard (like this one):

![Leaderboard](https://user-images.githubusercontent.com/43073074/61188953-db80f180-a686-11e9-80a9-134124f811b1.png)

**Comment by Gabixel** [comment]
I see. Closing because it's not an issue.

**Comment by smoogipoo** [comment]
I actually disagree with the current behaviour based on how osu!stable works - showing scores with _all_ selected mods. I believe it is cumbersome to scroll through all mods before finding that a mod combination hasn't been played at all/by very few people.

Going to re-open as a proposal.

**Comment by naoey** [comment]
Maybe there should just be an option for the user to select, having the "Mods" checkbox have 3 states: "none", "some" or "all"? Would need a corresponding change in osu-web to support and/or logic in the API.

**Comment by bdach** [comment]
Referencing ppy/osu-web#4994 (allowing PF/SD scores to show on leaderboards alongside the scores set with the same mods minus PF/SD) here as an exception to consider while implementing this lazer-side for posterity.

**Comment by Joehuu** [comment]
Just need to fix local leaderboards now.

**Comment by Joehuu** [comment]
Closing this in favor of https://github.com/ppy/osu/issues/21322.
