### ISSUE TITLE
Add access to tournament chat display for normal users

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5366]
**Describe the issue:** 

I'm going to run a tournament soon and I want to use lazer's tourney client for it. I already tested it on the tourney that I was casting recently and I managed to get all things going besides chat.
I just don't get on how it works. Also, I'm considering writing an article about the whole lazer tournament client on osu-wiki, so if the hacky implementation of the chat is okay for the public eye, then I'm going to write it. Please inform me if the current state of the tourney client is not ready for public use yet.

**Comment by peppy** [comment]
Congratulations on getting the lazer tournament stuff working. If you could help write the wiki I would be in debt to you multiple times over (reach out if you have any other questions).

As for chat, I believe I can modify the underlying APIs to work correctly, but the main issue is permissions granting (to read chat of potentially passworded multiplayer games).

Can I presume all matches will be made with `!mp` commands? That may be a way of defining access rules.

**Comment by l3lackShark** [comment]
Thanks for spending some time with me on that topic! Yes, they are supposed to be created with the **!mp make** command (I usually do it with the auto referee bot that I have, over IRC) And about further questions.. I can join the discord and ask some stuff later on if that's appropriate.

**Comment by peppy** [comment]
This has been implemented. Will work for all games made via `!mp make` that aren't marked as private.
