### ISSUE TITLE
Black screen upon beatmap completion while importing beatmaps.

### ISSUE THREAD

**Issue by ansxor** [ppy/osu#5368]
**Describe the bug:** 
As the title says, while importing beatmaps I am met with a black screen when I should be met with the results. I assume this is not an intended behavior of the importing.

**Screenshots or videos showing encountered issue:** 
![there's nothing to show lol](https://i.imgur.com/RfBwlbzg.png)
not really much to show

**osu!lazer version:** 
https://github.com/ppy/osu/releases/tag/2019.713.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3393420/database.log)
[network.log](https://github.com/ppy/osu/files/3393421/network.log)
[performance.log](https://github.com/ppy/osu/files/3393422/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3393423/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3393425/updater.log)

**Comment by iiSaLMaN** [comment]
Related to #5346, could be a duplicate

**Comment by peppy** [comment]
Looks like a duplicate.
