### ISSUE TITLE
Length / Duration is still 0:00 for all beatmaps in 2019.713.0

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu#5375]
#5326 this one?
Screenshot:
https://i.gyazo.com/50a77375db2850e37fee917806e2cdf1.png 

Version:
2019.713.0

**Comment by iiSaLMaN** [comment]
That PR was for the duration of the song in beatmap set overlay (on osu!direct), if you've read the changelogs, you can see in the description of one of the changes that you need to reimport all of your beatmaps to get the correct length

**Comment by GrilledCheeese** [comment]
Alright closing
