### ISSUE TITLE
Add automatic reprocess support on database migrations

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#5376]
All beatmaps in the database should be automatically reimported if a change occurred to the database.

**Comment by Game4all** [comment]
Guess this could be useful, especially when a DB migration occurs

**Comment by thd14** [comment]
how to do this manually?

**Comment by Game4all** [comment]
For now there's no such way to reprocess already imported beatmaps automatically or manually. 

You'll have to delete all your lazer beatmaps and reimport them (from the settings button) in order to achieve a similar effect.

**Comment by thd14** [comment]
ok thank, do you intend to add this feature? it is to resolve the 0:00 beatmap length issue

**Comment by peppy** [comment]
That is why this issue is open. Please do it manually for now.

**Comment by peppy** [comment]
We make migrations in a better way these days. Shouldn't be an issue going forward.
