### ISSUE TITLE
Possible regression regarding performance and osu!direct

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#5377]
**Describe the bug:** 
When downloading maps from osu!direct, this type of text appears “Found 3 songs” which is normal but the maps never appear in the list. Then, attempting to play a map, the song list doesn’t load. The UI loads but the song list itself fails to appear. Clicking the osu! cookie does nothing either. See attached screenshot to see what I mean.
Reporting as a bug because this happens every single time I try it and is easily replicable (atleast for me). Sorry if duplicate.

**Screenshots or videos showing encountered issue:** 
![98E7E68B-5317-4586-9DEF-4D81A27FBCE4](https://user-images.githubusercontent.com/10524728/61317374-db8d0880-a7d0-11e9-9783-9e4dadb7957c.png)

**osu!lazer version:** 
2019.713.0
iPad Pro 11” on iPadOS Public Beta 2

**Logs:** 
Unavailable on iOS?

**Comment by peppy** [comment]
Please provide a video showing the full process / issue you're seeing.

**Comment by ThatsNiceGuy** [comment]
I haven’t been able to reproduce this today at all, it might have been the servers or my connection not functioning properly. Marking as resolved for now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
