### ISSUE TITLE
Proposal: new osu!direct

### ISSUE THREAD

**Issue by kathelynn** [ppy/osu#5382]
A redesign of lazer's osu!direct inspired by the website
Adds search filter and ascending/descending order for the sort by bar
I also removed the mode selection as it was already on the toolbar so it felt unnecessary to have both.
![osudirect](https://user-images.githubusercontent.com/50712757/61363538-c68aa500-a8b6-11e9-83cf-6ea7baf94bde.png)

**Comment by peppy** [comment]
Thanks for the proposal, but we already have designs for all UI and overlays going forward. If you are interested in implementing, please ask and we will provide designs (this is mentioned in the main README for reference!)
