### ISSUE TITLE
Android compile error

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5392]
**Describe the bug:** exception:
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1898,2): error XA2002: Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `Microsoft.CodeAnalysis`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `Microsoft.CodeAnalysis`.
```
installing `System.Threading.Tasks.Extensions` in android props helps if installed version is 4.5.0 or below; higher versions provide empty dlls for android `_._`

**osu!lazer version:** commit e570970

**Environment:**
OS: win10 pro 1803
Visual studio 15.9.13
Xamarin android sdk: 9.1.7.0

**Comment by peppy** [comment]
Have you found the dependent code on this library? It may make more sense to remove that from mobile distributions so we don't require every project (and potentially every framework consumer?) to implement this hack.

**Comment by swoolcock** [comment]
Pretty sure we only use CodeAnalysis for dynamic compilation, which isn’t supported on iOS (and hasn’t been tested on Android if it’s even possible).

**Comment by a44281071** [comment]
@ticotaco72 Can you show your email or chat way?
Can I learn how to build target android with you? And, Are you Chinese, mi fance?

**Comment by Rifju** [comment]
I have the same problem

**Comment by SKYRajan** [comment]
Hi Solve this issue Down Version Of Xamarin.HotReload

**Comment by peppy** [comment]
For now we recommend updating to visual studio 2019 to fix this.
