### ISSUE TITLE
Sliderscorepoint and Reversearrow not scaled from circle size

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu#5395]
Reversearrow and Sliderscorepoint not scaled with the high circle size

 Screenshot: https://puu.sh/DU9PZ/5dab62db5a.png

2019.717.1

Sliderscorepoint and Reversearrow don't scaled this circle size. Not fixed that the actual client.

**Comment by peppy** [comment]
Please include your skin for reference.

**Comment by peppy** [comment]
Closing as duplicate of #3158.

**Comment by Fatal3ty** [comment]
Oh, i didn't see that Post, i will use "search" for the future. That is my personal skin (Ameliorate Fatal v2.2 Lazer), i try anoter Skins - all the same bugs with reversearrow and sliderscorepoint.
