### ISSUE TITLE
Mouse rapidly sliding across game screen

### ISSUE THREAD

**Issue by Groctel** [ppy/osu#5398]
**Describe the bug:** Sames as #5328, enabling raw input makes the mouse go extremely fast or slow if its speed is other than 1.0. The slider becomes unusable due to extremely low mouse speed if it's lower than 1.0 and the mouse travels from corner to corner at the slightest move if it's higher than 1.0. Pressing Ctrl+Alt+Shift+R or Ctrl+Alt+R does not alter the mouse input either.

**osu!lazer version:** 2019.717.1 

**Logs:** Can't find where they're stored :(

**Comment by peppy** [comment]
Please don't open a new issue.

**Comment by Groctel** [comment]
Sorry, I forgot to specify in the body. The issue is the same, but it was closed with an explanation on how to revert the raw input configuration. How can the mouse speed be changed without having this issue? Playing at default speed is almost never an option.

**Comment by peppy** [comment]
Please open an issue against osu-framework with proper reproduction and maybe a video showing what you're seeing. Along with your window system and everything else custom about your linux setup.
