### ISSUE TITLE
Press to retry keybind

### ISSUE THREAD

**Issue by kathelynn** [ppy/osu#5402]
**Describe the new feature:** 
Most people are used to pressing to retry on the stable. There's no point to disallowing anyone to instantly retry their game, it makes the game feel slower and pointless to reach for tilde on a high-level map when you're going to fail anyway. Hold is useful for new players, but press for long time osu players.
**Proposal designs of the feature:** 
Add a keybind option to retry on the Gameplay section (exactly where the hold to retry is placed). Then maybe acknowledge players if they want to use hold or press next time.

**Comment by peppy** [comment]
Can you explain how having "press" instead of "hold" changes "reaching for tilde"?

**Comment by HoLLy-HaCKeR** [comment]
I assume he means that if you need to hold the retry key anyway, you may as well let the map fail and use the fail screen's retry button instead. It wouldn't be (much) faster to use the hold-to-retry button.

**Comment by peppy** [comment]
The time to hold is 400ms at the moment. We may reduce it depending on how far into the map (or just reduce it overall), but I am not sure about removing it.

**Comment by kathelynn** [comment]
Not remove it, but provide an option to press instead of hold.

**Comment by LastExceed** [comment]
What is the idea behind the design decision of having to hold these hotkeys for a moment rather than quickly pressing (pause hotkey has it as well) ? It doesn't seem very intuitive to me

**Comment by ticotaco72** [comment]
it has meaning for e.g. when you click it by mistake and it makes you think more when you do it so you do it less often, @LastExceed and for me it realy feels more intuitive especially with animation that's there

**Comment by peppy** [comment]
You hold it until the screen fades. It avoids accidental key brushes and was a requested feature for any action which could potentially exit the game unexpected.

It also consolidates logic across platforms where a short hold works better.

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu/pull/6166.
