### ISSUE TITLE
VS2019 fails to archive an apk for osu.Android

### ISSUE THREAD

**Issue by YoDevil** [ppy/osu#5410]
The project builds fine, but when trying to pack it into an apk, VS2019 fails with:
"Invalid Android Archive (no .APK files)"
Using VS2017 instead (with #5394 workaround) just works.

It may be a known issue to VS2019 already: 
https://developercommunity.visualstudio.com/content/problem/530265/vs-2019-v161-creating-android-archive-fails-with-n.html

**Comment by Morilli** [comment]
Having the very same issue.

**Comment by a44281071** [comment]
yes, have same problem, just use usb debug to deloy the app.

**Comment by peppy** [comment]
Out of scope of this project.
