### ISSUE TITLE
song select doesn't re center itself when changing orientation

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5413]
**Describe the bug:** open song select vertically on mobile, turn to landscape and song that you have chosen is outside view if you have enough beatmaps

**Screenshots or videos showing encountered issue:** 
https://1drv.ms/v/s!Ar8asfoEwiDmhOBtff8VxFvHRU5LzQ?e=0a4yXh

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/11405.
