### ISSUE TITLE
Allow for room creators to specify what scoring types they want

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#5417]
~~A user shouldn't be able to submit a standardised score while other submit with classic, that'll allow for that user to simply pass them by playing with standardised~~

We should add an option for room creator to select scoring type and force the players to that scoring type

**Comment by peppy** [comment]
Score submission should be forced

![image](https://user-images.githubusercontent.com/191335/61586691-7876e980-abb5-11e9-8e57-d754ee989ba4.png)

Could you please provide more details as to how you are seeing this happen?

Also, going forward this is not going to be an issue. The total score will not be submitted and only the underlying statistics will.

**Comment by iiSaLMaN** [comment]
> Score submission should be forced
> 
> ![image](https://user-images.githubusercontent.com/191335/61586691-7876e980-abb5-11e9-8e57-d754ee989ba4.png)
> 
> Could you please provide more details as to how you are seeing this happen?
> 
> Also, going forward this is not going to be an issue. The total score will not be submitted and only the underlying statistics will.

Just realized that, my bad. although can be a proposal for those who want the classic scoring

**Comment by peppy** [comment]
The idea is that scoring is 100% client-side. This needs to be implemented. Scores returned from the server should not be used. The classic/standardised scores can both be recalculated in real-time from the provided statistics.

**Comment by smoogipoo** [comment]
This should not be a thing, the scoring mode is purely cosmetic and client-side only. It doesn't change ordering/value of scores.
