### ISSUE TITLE
Why is the difference between the radius of the circle of osu lazer and osu so large? (My English is not very good, I may have expressed an error)

### ISSUE THREAD

**Issue by YUKON233** [ppy/osu#5425]
![image](https://user-images.githubusercontent.com/40208202/61627777-3338e180-acb3-11e9-837b-97caa044df8d.png)
The outer ring of the osu lazer is too small, which leads to increased difficulty. Is there any way to adjust the size of the outer ring?

**Comment by peppy** [comment]
Do you mean the slider follow circle?

**Comment by YUKON233** [comment]
> Do you mean the slider follow circle?

I mean, when the outer ring is reduced to the same size as the inner ring, we will click on it. I am referring to the appearance time and size of the outer ring.

**Comment by YUKON233** [comment]
![image](https://user-images.githubusercontent.com/40208202/61628676-91ff5a80-acb5-11e9-9bff-11015fde228d.png)
Is this circle

**Comment by EVAST9919** [comment]
Looks like he is talking about an approach circle.

**Comment by peppy** [comment]
I'm currently doing a pass on skin / gameplay accuracy, so this should be resolved as part of that.

**Comment by iiSaLMaN** [comment]
I think this should be closed once it's actually resolved, currently, it isn't yet.

**Comment by EVAST9919** [comment]
This one must have been fixed already.
