### ISSUE TITLE
Crash when loading songs

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#5430]
**Describe the crash:** 
When i click solo it leads to the song select, however it just stays like this 
![osu_2019-07-22_18-19-08](https://user-images.githubusercontent.com/17437302/61647248-3a5cf100-acad-11e9-9cbb-3e9f09e70999.jpg)
and crashes after the "intro" song ends

ok little correction it does crash in the main menu as well just let the intro song finish 

**Screenshots or videos showing encountered issue:** 
https://streamable.com/lzju2
**osu!lazer version:** 
 3fde4ef 
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3418319/runtime.log)

**Computer Specifications:** 
i3 6100, GTX1050Ti, 8GB Ram, Windows 10 x64 1903

**Comment by Joehuu** [comment]
Probably fixed via https://github.com/ppy/osu/pull/8903 and other performance fixes during that time.
