### ISSUE TITLE
 Beatmap Crashes Suddenly And Resumes After a Few Milliseconds

### ISSUE THREAD

**Issue by joaodanilo123** [ppy/osu#5434]
**Describe the bug:** 

When you are in the middle of the song, the beatmap simply stop and resume 
quickly. This is very bad because you lose all the objects in this small time.

It appears to be more common in imported beatmaps.

The song doesn't stop, only the beatmap.

Look like a performance issue too, but this never happened to me in the stable ver.

**Screenshots or videos showing encountered issue:** 
I don't have a screenshot/video because it's too rare/fast to take.

**osu!lazer version:** 
2019.719.0

**Logs:**
I doesn't finded anything. 

**Notes**
Notebook Specs.:
i7-4510U, 8GB RAM DDR3, Nvidia Geforce 710M(2GB VRAM)

My english is bad, my native language is portuguese. Anyway, i will try to reply any question.

**Comment by peppy** [comment]
If possible, could you please turn on performance logging (at the bottom of settings) then reproduce this once and exit the game immediately.

Then attach your log files (start -> run -> `%AppData%\osu\logs`.

**Comment by joaodanilo123** [comment]
i will try

**Comment by joaodanilo123** [comment]
Here:
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3419903/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3419904/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3419905/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3419906/performance-gamethread.update.log)


I will try to bring more if necessary, because I don't know exactly what should appear in the logs so I can't offer much accuracy

**Comment by joaodanilo123** [comment]
again:

[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3420009/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3420010/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3420011/performance-gamethread.update.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3420012/performance-gamethread.audio.log)


most logs relate to slow frames, reaching 12 seconds(performance-gamethread.draw.log)

**Comment by joaodanilo123** [comment]
i don't know why, but the this problem hasn't happened anymore
