### ISSUE TITLE
Where are the song/skin files located on macOS?

### ISSUE THREAD

**Issue by graghu782** [ppy/osu#5444]
Trying to find the beatmaps that are installed but I can't seem to access the location of the beatmaps on osulazer.

**Comment by peppy** [comment]
Click "open osu! folder" in settings to open the game data folder.

If you are looking to import beatmaps, please us osu!direct or drag files into the window. The structure is completely different on lazer.

**Comment by graghu782** [comment]
So I am looking to transfer my files onto another machine and I wanted to copy the ones I have on lazer. Also I can't find the beatmaps in the osu! folder. 

this is what the folder looks like 
![image](https://user-images.githubusercontent.com/15662021/61766463-c77b7500-ad95-11e9-9f7c-b686a9117f89.png)

this is what the "files" folder looks like 
![image](https://user-images.githubusercontent.com/15662021/61766421-a4e95c00-ad95-11e9-9ec6-90cd2494c135.png)

Where would the beatmaps be located?

**Comment by peppy** [comment]
Copy the whole game folder or it will not work.

**Comment by graghu782** [comment]
is there no way to retrieve the .osz files then?

**Comment by peppy** [comment]
lazer is not backwards compatible.
