### ISSUE TITLE
Beatmap carousel is clickable through the footer

### ISSUE THREAD

**Issue by nyquillerium** [ppy/osu#5452]
This is purposely regressed in https://github.com/ppy/osu/pull/5440. 

It should not block positional input. Instead, the carousel should be contained within the area above the footer, and be unmasked by the footer to provide visibility.

**Comment by nyquillerium** [comment]
So I have an implementation ready for this, which involved confining the Carousel area above the footer and below the filter area. This meant I had to update the fading/item removal logic inside `BeatmapCarousel`. 

While I succeeded in updating the logic such that it matches the existing implementation, it now relies on the parent container's sizing and padding, which is kind of ugly. It needs the parent container's sizing (as well as upper and lower padding) to calculate its fade factor and whether or not its on screen.

I can try to do a refactor pass to remove this requirement, or I can pass down the upper and lower padding from `SongSelect` to make this more sane.

**Comment by peppy** [comment]
why not just expose constants at sognselect
