### ISSUE TITLE
Taiko hit object renaming

### ISSUE THREAD

**Issue by smoogipooo** [ppy/osu#547]
In the process of re-implementing taiko in osu!lazer, we're going to change the naming of hit objects to move away from TnT. The new terms for taiko hit objects are supposed to sound/be common in drumming.

- [x] Don -> Centre
- [x] Katsu -> Rim
- [x] Spinner -> Bash
- [x] Bash -> Swell
- [x] Finisher -> Strong

**Comment by skielred** [comment]
I think "_Double_" is more appropriated instead of "_Accented_". It is not a term reservered to Taiko and "_Accented_" isn't very explicit.
"_Swell_" isn't very explicit either. "_Drumroll_" or "_roll_" is a generic term in musicology and instruments.

**Comment by peppy** [comment]
- we decided against "double" because it makes the naming dependent on input (which isn't always true).
- drumroll is already used for... drumrolls.

**Comment by skielred** [comment]
- I think "_Double_" evokes that it's a bigger note. "_Accented_" feels weird to me. I can't come up with another idea than "_Double_" or "_Big_" for it.
- I misunderstood what the "_Bash -> Swell_" is then.

**Comment by smoogipooo** [comment]
Bash -> Swell is probably confusing... Should be Spinner -> Swell, but it's currently called Bash everywhere in code in osu!lazer so that's why there're two relevant items in the list.

The reasoning for Swell is because it's going to be hitsounded like a cymbal swell.

As for "Double"... I dislike it also in part due to double drumroll, which makes no sense. Although with that being said my current train of thinking is that finisher drumrolls should be removed altogether as they currently serve no purpose in the game.  
I do also agree with peppy that "double" makes things too dependent on input - having it as "accented" allows us to re-purpose it for other hitobjects in the future in ways that don't imply double key presses. It also technically not a "double" considering you can hit finishers with one key anyway.

**Comment by peppy** [comment]
That said, if this terminology is to be used by end-users too, I feel like "strong" is a better choice than "accented" still.

**Comment by skielred** [comment]
I like the "_strong_" idea more than "_accented_" too.
I don't think double drumrolls should serve no purpose. In the original game, giant drumrolls score twice as much as regular notes. In osu! they should score more too, since it permits to emphasis on certain parts of the song and add diversity without using confusing mechanics..

**Comment by smoogipooo** [comment]
Strong sounds interesting. As for "strong" drumrolls - they do provide more score, but there's no additional mechanics for it, to the point where you might as well just play normal drumrolls.

At the very least if they were kept, they should require some additional mechanics imo.

**Comment by smoogipooo** [comment]
Closing this for now as we have decided on the following naming:

| Old | New |
| ----- | ---- |
|  Don | Centre |
| Don Finisher | Strong Centre |
| Katsu | Rim |
| Katsu Finisher | Strong Rim |
| Drum Roll | Drum Roll |
| Finisher Drum Roll | Strong Drum Roll |
| Spinner | Swell |
