### ISSUE TITLE
Some mods don't work correctly

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5478]
**Describe the bug:** Grow & Deflate mods don't work correctly.

**Screenshots or videos showing encountered issue:** 
Grow Mod: https://streamable.com/35a3l
Deflate Mod: https://streamable.com/1cn70

**osu!lazer version:** 2019.726.0

**Comment by Gabixel** [comment]
Also Wiggle Mod has this problem, Transform seems to work fine

**Comment by Phippe** [comment]
Hidden mod too

**Comment by iiSaLMaN** [comment]
Regressed in #5424
