### ISSUE TITLE
Sliders are displayed incorrectly

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#5480]
**Screenshots or videos showing encountered issue: there's a recording attached to the tweet https://twitter.com/Sinamer0714/status/1154769716700991490** 

**osu!lazer version: 2019.726.0** 

**Logs:  
[performance.log](https://github.com/ppy/osu/files/3436380/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3436381/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3436382/updater.log)
[database.log](https://github.com/ppy/osu/files/3436383/database.log)
[network.log](https://github.com/ppy/osu/files/3436384/network.log)

**

**Comment by peppy** [comment]
@smoogipoo highlight on this one, you might have some ideas or questions
