### ISSUE TITLE
Taiko sliders aren't show a visual feedback and hitsounds issue

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu#5481]
Taiko Sliders aren't show a visual feedback when hit a sliders. Very hard to play without a visual feedback and hitsounds are quiet or play with osu standard hitsounds.
![osu_2019-07-26_18-51-44](https://user-images.githubusercontent.com/53025167/61967921-f16faa00-afd6-11e9-9227-15378a11047a.png)
![osu_2019-07-26_18-53-06](https://user-images.githubusercontent.com/53025167/61967923-f2a0d700-afd6-11e9-9cc5-9dcb17cd0668.png)

And Hitsounds for Taiko don't worked correct, some maps hear a osu!std Hitsounds. My Skin have a custom taiko hitsounds, didn't worked. Same with default skin issue.

osu!lazer version: 2019.726.0

Logs: nothing, is a visual feedback and hitsounds issue

**Comment by turbedi** [comment]
This issue can be closed now that #8675 has been merged, right?
