### ISSUE TITLE
Files app integration for iOS import/export

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#5485]
Related to #5272 and #5445 
**Copy to** option in share UI and **file location** in _Files_ does not show up.
**Version:** _latest release_
**OS:** _iOS 13 Public Beta 3_
**Images:**
![9078F761-4920-48A4-8961-66BEED1A4FA6](https://user-images.githubusercontent.com/48611569/61982651-b0699c80-afba-11e9-8bff-d046dfbe9aec.png)
![AD941896-121B-47DF-A465-92633DEA6A57](https://user-images.githubusercontent.com/48611569/61982653-b0699c80-afba-11e9-9495-52fd6967d723.jpeg)

**Comment by swoolcock** [comment]
The share UI functionality will be in the next iOS release, as it was added in this pull request: https://github.com/ppy/osu/pull/5445

The Files application is out of scope for Lazer as we do not provide “files” internally for beatmaps.

**Comment by peppy** [comment]
I think we can provide files support via an "Import" folder, which lazer reads from on next startup. May work quite well IMO.

**Comment by swoolcock** [comment]
As an iOS user I would expect that saving files implies I can copy them out again.

**Comment by peppy** [comment]
Even if the folder is called `Inbox` or `Import`?

**Comment by swoolcock** [comment]
The Files app is intended to be used for accessing the `Documents` directory of supported apps (in the same way that iTunes does) and for files/data that are potentially managed by a remote server or sync (DropBox etc.) which requires a separate FileProvider extension to be registered on the provisioning portal.

https://developer.apple.com/documentation/fileprovider?language=objc

"Importing" files to me implies the use of the file sharing UI (which was recently added).  Lazer doesn't have the concept of files or documents so I don't think we require Files integration.

We could give it a shot and see how well it works, but it feels weird to me.

**Comment by swoolcock** [comment]
Note that I *CAN* see this as being useful for unsubmitted beatmaps if players want to import/export their progress from the beatmap editor, but I don't know what the end goal is for that.  Not sure if there were any plans for a cloud sync or something with beatmap editing.

**Comment by peppy** [comment]
Thinking we will probably want an export folder to--

**Comment by dscnnctd** [comment]
One reason I want Files app integration is because there is no option to delete one specific skin in iOS yet. It only lets you delete all of it than just deleting only one skin.

**Comment by peppy** [comment]
File integration would not solve that due to the reasons listed above.

**Comment by dscnnctd** [comment]
So then it will be done in-game instead of doing it with integration?

**Comment by peppy** [comment]
correct. lazer uses a completely managed files solution. manually deleting any files would corrupt your database.

**Comment by dscnnctd** [comment]
All makes sense now, thanks.

**Comment by swoolcock** [comment]
Reopening for visibility if we decide to implement Files integration for import/export.
