### ISSUE TITLE
Game pauses every ~3 seconds after random spam in song select

### ISSUE THREAD

**Issue by SpikyPillow** [ppy/osu#5489]
**Describe the bug:** 
After spamming random (i've also gotten it to do happen just by moving the scollbar a lot around rapidly) the game will freeze for a short moment every about three seconds. Going back to the main menu sometimes stops it. Very likely related to my large amount of beatmaps.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/jbbz2

**osu!lazer version:** 
2019.727.0

**Comment by peppy** [comment]
Could you please turn in performance logging in settings and provide log files after this happens? Also maybe you can use frame statistics to get an idea of where the stall is happening (update or draw thread) - carl-f11 twice to enable.

**Comment by Joehuu** [comment]
Possibly fixed in https://github.com/ppy/osu/pull/10494.
