### ISSUE TITLE
Crash on SongSelect

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5492]
**Screenshots or videos showing encountered issue:** 
https://www.twitch.tv/l3lackshark/clip/ScaryAcceptableSushiCharlietheUnicorn

**osu!lazer version:** 
2019.727.0

**Logs:** 
[logs.zip](https://github.com/ppy/osu/files/3439169/logs.zip)

**Computer Specifications:** 
CPU - I7 4790
GPU - GTX 1070Ti
RAM - 8GB

**Comment by peppy** [comment]
I believe @smoogipoo is looking into this one.

**Comment by Joehuu** [comment]
Probably fixed in https://github.com/ppy/osu/pull/8933.
