### ISSUE TITLE
Add iOS document configuration 

### ISSUE THREAD

**Issue by peppy** [ppy/osu#5500]
> ITMS-90737: Missing Document Configuration - By declaring the CFBundleDocumentTypes key in your app, you've indicated that your app is able to open documents. Please set the UISupportsDocumentBrowser key to "YES" if your app uses a UIDocumentBrowserViewController. Otherwise, set the LSSupportsOpeningDocumentsInPlace key in the Info.plist to "YES" (recommended) or "NO" to specify whether the app can open files in place. All document-based apps must include one of these configurations. For more information, visit https://developer.apple.com/document-based-apps/.

Required in addition to https://github.com/ppy/osu/pull/5445

**Comment by ThatsNiceGuy** [comment]
Hmm I was about to make an issue regarding this as I can’t open any beatmaps with lazer on iOS yet but it appears that this is the cause.
