### ISSUE TITLE
Missing OpenTK hint reference on osu.Desktop project file.

### ISSUE THREAD

**Issue by ElegantMonkey** [ppy/osu#551]
When building with Mono 4.4.1 under Gentoo Linux, the build fails due to a missing hint reference to the OpenTK assembly on osu.Desktop. I think opening an issue is standard practice, so...

**Comment by Arefu** [comment]
Install the OpenTK package needed. This doesn't look like an osu issue.

**Comment by a1batross** [comment]
Seems you need to restore NuGet packages at first. MonoDevelops ships with NuGet 2.8 for some reason, 2.12 taken from mono/nuget-binary repository was enough for me.

**Comment by ElegantMonkey** [comment]
Nope, for me it still fails on the first build, although the second one goes fine. Tried with both NuGet 2.12 and NuGet 4.0.0.2283 from mono/nuget-binary.
