### ISSUE TITLE
Replays are inaccurate

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#5514]
**Describe the bug:** Not sure how intended this is for now, but thought I'd at least mention it. Replays are currently very inaccurate, a replay might miss a slider or circle in lazer while that isn't happening in stable (or vice-versa, haven't seen that personally though). Besides that, replays can also just fail in lazer because of mismatches regarding how sliders are handled. 
An example for a missed note in lazer is the current top play of idke in [euphoria](https://osu.ppy.sh/beatmapsets/890438#osu/1861487). In lazer, the slider at around 1:50 will always be missed, whereas that doesn't happen in stable.

**osu!lazer version:** 5fa820cdd439c90e2f8a14c17ca138dace549e21

**Comment by peppy** [comment]
There are still many minor differences in gameplay and timing between versions. Also, replays are currently favouring performance over correctness (interpolating even when interpolation may cause inaccuracy). Best-effort for now.

**Comment by ShiiTsuin** [comment]
Was wondering whether this was still being looked into?

Been using lazer for getting nice and clean videos of replays of my maps, but have had issues like those described above (using osu!lazer version 2021.416.0). 

Would enforcing classic mod onto osu!stable replays (similar to what was suggested in #12114) help? Know at least some cases of replays lining up are from different slider behaviour.

**Comment by peppy** [comment]
Yeah, we will likely want to apply classic mod to `.osr` files from stable. In addition, there are still other mismatches, like HP drain rate, which we may still need to address.

**Comment by frenzibyte** [comment]
Should the classic mod be applied as if it's part of the legacy score's mods (i.e. appear in leaderboard scores, beatmap info overlay scores, etc..)? or should it be automatically appended when watching legacy replays only.

If we were to go with the former, I think it would be best to add classic mods for all other legacy rulesets as well.

**Comment by peppy** [comment]
I think it should be displayed everywhere.
