### ISSUE TITLE
Beatmap backgrounds in the main menu

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#5516]
We might want to add an ability to allow players select beatmap backgrounds instead of default in the main menu.
Since we have an ability to skin that, we can make a dropdown in settings like

Main menu background
- default
- skin
- beatmap
- seasonal (in the future)

Some elements like "skin" and "beatmap" will be visible for supporters only (or not).

**Comment by peppy** [comment]
Already in stable so should exist in lazer.

**Comment by EVAST9919** [comment]
There was no issue, I was asking about that in the discord a while ago

**Comment by KoziLord** [comment]
I feel like there should also be a dim and a blur slider available just like during the map loading

**Comment by peppy** [comment]
That will not be an option. If you want this you can blur your skin image yourself.
