### ISSUE TITLE
Skin cursor size is incorrect

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#5534]
**Describe the bug:** Changed / regressed in #5465. 
How the cursor looked in lazer before the PR: 
![lazer cursor before](https://user-images.githubusercontent.com/35152647/62143649-af08de80-b2f0-11e9-993b-799b7f9ca5ef.png)
How it looks afterwards:
![lazer cursor after](https://user-images.githubusercontent.com/35152647/62143663-b4662900-b2f0-11e9-8d33-eb67d6d7b2dd.png)
How it looks in stable: 
![stable cursor](https://user-images.githubusercontent.com/35152647/62143667-b92add00-b2f0-11e9-8a27-9abd92c851d6.png)

The skin I'm using: https://drive.google.com/file/d/1tJt0RWWkUAocyL5BJriywa9_05zhPnAa/view?usp=sharing

**osu!lazer version:** 2019.730.0

**Comment by nyquillerium** [comment]
It seems that the expanded state of the cursor on lazer would match the size of the unexpanded state of cursors on stable. Currently lazer doesn't respect the `CursorExpand` setting and will always expand cursors on click. 

Lazer on the left vs stable on the right (both in an unexpanded state):
![unknown](https://user-images.githubusercontent.com/5578000/62521177-1c28f080-b86a-11e9-8dc8-fbb19f0e5584.png)

I tested this using skin.inis from [yugen](https://osu.ppy.sh/community/forums/topics/365036), [stoof's skin](https://circle-people.com/skins/?osu=Stoof&download=0), and the skin provided above.

**Comment by peppy** [comment]
It doesn't have to do with expanding; all tests were done when the cursor was not expanded.
