### ISSUE TITLE
osu goes into wrong resolution?

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5535]
**Describe the bug:** 
when i am in fullscreen
1. i go to 1024x768
2. go to default (which is 1280x1024)
3. osu goes to this
![2019-07-30 (2)](https://user-images.githubusercontent.com/32620809/62153981-0ebdb480-b306-11e9-8bdf-2c05fe5f1294.png)

when i go to 1280x1024 by clicking this value insted of default it is all right

**osu!lazer version:** 2019.730.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3448276/database.log)
[network.log](https://github.com/ppy/osu/files/3448278/network.log)
[performance.log](https://github.com/ppy/osu/files/3448279/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3448280/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3448281/updater.log)

**Comment by ticotaco72** [comment]
2 next things:
1. turning osu off and on makes you back to 1024x768
2. you have to switch back to 1024x768 or other non default resolution (if you have switched to default as described above) and then to 1280x1024 to resolve this

**Comment by UselessToucan** [comment]
@ticotaco72 can you reproduce the problem using framework visual tests?

**Comment by ticotaco72** [comment]
@UselessToucan visualtests don't run in full screen

**Comment by UselessToucan** [comment]
> @UselessToucan visualtests don't run in full screen

https://github.com/ppy/osu-framework/blob/master/osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs

**Comment by ticotaco72** [comment]
ok i can reproduce this in framework visualtests

**Comment by Joehuu** [comment]
Fixed in SDL.
