### ISSUE TITLE
Circle Expand Version issue (numbers expands)

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu#5537]
Circle expand from lazer version issue, that one use from like version 1:
![expand lazer](https://user-images.githubusercontent.com/53025167/62157957-a1625180-b30e-11e9-98eb-db787a073d0f.png)
Osu Stable with skin.ini Version 2.0+:
![expand stable](https://user-images.githubusercontent.com/53025167/62158004-c0f97a00-b30e-11e9-8895-879d4d54914f.png)

Same Skin and that use verison: 2 or latest
Skin: Clear Skin Ultra 3.0 (https://osu.ppy.sh/community/forums/topics/606260)
Same issue with another skins.

osu!lazer version: 2019.730.0
Logs: none

**Comment by peppy** [comment]
Is this an issue? I was aware of this when implementing this, but it looked better with the number expanding to me. Would appreciate more detail on why you prefer it not expand.

**Comment by Fatal3ty** [comment]
Mostly people like without numbers expand. I think that one can be config on skin.ini, like example this:

Example:
CircleExpand: 0 or 1 (sould be use circle expand or not?
NumbersExpand: 0 or 1 (only worked if CircleExpand is set to 1)

**Comment by b4mbus88** [comment]
Please dont take us the possibility to change the fadeing. In my opinion as a skinner it would be great if we could costumize the fadeout time in skin.ini. I always played without the animation with only default0-9.png as hitcircle and i dont want to miss it. This also would solve the problem with numbers above 10 (stacking default pngs/numbers). So the ajustment in skin.ini would solve all problems and fit for every player i guess.

And it would make alot of skins out there right now playable for me :D

**Comment by iiSaLMaN** [comment]
I'm actually a bit confused here, so the issue is that `NumbersExpand` is ignored?
