### ISSUE TITLE
No-Fail mod scores are broken.

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#5541]
Tested in both **standardised** and **classic**.
**Standardised:**
![5100F281-8D84-4347-A0CF-02BCFC191D4B](https://user-images.githubusercontent.com/48611569/62187183-c44c3000-b325-11e9-9ac2-a6f5e41101f9.jpeg)
**Classic:**
![F19DD1A9-91D2-42BB-AEF0-CD786B5FD82D](https://user-images.githubusercontent.com/48611569/62187254-fb224600-b325-11e9-9a0d-4b21c70aaab2.jpeg)
**Version:** _latest_

**Comment by iiSaLMaN** [comment]
Uhh, what's broken? all I'm seeing as different scores, how can you prove that they all are the same?

**Comment by dscnnctd** [comment]
>What's broken? all I'm seeing is different scores, how can you prove that they all are the same?

Standardised score seems to exceed above its limit (500,000). It does not behave like that in older releases.

**Comment by iiSaLMaN** [comment]
Can you check if the score multiplier works correctly, it seems like an issue with the multiplier

**Comment by dscnnctd** [comment]
Tried HDNF and here are the results.
**Standardised:**
![C8178D4A-4149-498F-8807-24916B61C1D2](https://user-images.githubusercontent.com/48611569/62193802-cb7b3a00-b335-11e9-9025-effa702f2b2b.jpeg)
**Classic:**
![C5399F43-5F07-42A4-9FA1-0C0C30B480B9](https://user-images.githubusercontent.com/48611569/62193853-e0f06400-b335-11e9-9244-7512ba733cc9.jpeg)

**Comment by iiSaLMaN** [comment]
Well, the score multiplier isn't applied to the total score in `ScoreProcessor.getScores`, unless I missed something.

**Comment by dscnnctd** [comment]
**EZHD** showed similar scores as I double checked in replay. **Standardised** score gave me exactly 1,000,000 while **classic** score gave me 2,000,000. So it’s probably the _score multiplier_ that has the problem.
