### ISSUE TITLE
Shuffle for Music Player

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#5542]
**Describe the new feature:** 
Add a shuffle button for playing music shuffled.

**Proposal designs of the feature:** 
<img width="1081" alt="osushuffle" src="https://user-images.githubusercontent.com/50823728/62191257-84815900-b3b6-11e9-9528-1d1b77855f3e.png">

**Comment by peppy** [comment]
isn't it shuffled by default?

**Comment by Gabixel** [comment]
Nope, it follows the playlist order. But a shuffle button could be a great addition, it's a normal feature for a music player

**Comment by yuuiko** [comment]
Let me add on the behaviour for this.

When the person presses the shuffle button, you’ll see the currently playing song in the list go to the top, and all the other songs in the list shuffle. Then lazer will play through this shuffled list top to bottom. The shuffle button turns yellow.

This allows you to still drag around the order to set songs to play next.

When the user disables shuffle, the list returns to default alphabetical order, and the yellow is removed from the icon.

**Comment by signedinteger** [comment]
Not sure if this fixed intentionally or not, but I find the music player now already has shuffled play order upon startup. Begs the questions whether a "shuffle button" is still required
