### ISSUE TITLE
Accent the progress bar in the music player

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#5543]
**Describe the new feature:** 
Currently it's hard to tell where to click to scrub the music in the music player, as there's no background to the non-filled part of the scrubber.

Add some background to the music scrubber. Maybe give it a subtle mouseover lighten.

**Proposal designs of the feature:** 
<img width="1081" alt="osushuffle" src="https://user-images.githubusercontent.com/50823728/62191466-dcb85b00-b3b6-11e9-9412-ffceba7c660c.png">

**Comment by peppy** [comment]
might be nice if it got vertically taller on hover.

@arflyte

**Comment by yuuiko** [comment]
> might be nice if it got vertically taller on hover.
> 
> @arflyte

And show current time, remaining duration?

**Comment by UselessToucan** [comment]
> might be nice if it got vertically taller on hover.

might be nice to display a wave form in this case

Here is an example (AIMP).
![1204ac91-e73e-4a12-9f11-ea8ad2e0cfa4](https://user-images.githubusercontent.com/22450664/62197189-14f47500-b388-11e9-80ca-d3fb1a15bbb5.jpg)

**Comment by yuuiko** [comment]
> might be nice to display a wave form in this case

Might be a bit much for the simple music player...
