### ISSUE TITLE
Music Player skips a song when a "non-default" difficulty is selected

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5547]
**Describe the bug:** If you select a different difficulty from the Song Select and go back to the Main Menu, when the song ends the Music Player seems to skip a song.

With _different difficulty_ I mean a difficulty that is not the "default" one (an example with the following video, _Freedom Dive_ has the first difficulty by default when entering Song Select / switching to that song: "Asteroid", so if you select another difficulty you can reproduce this bug)

**Screenshots or videos showing encountered issue:** https://streamable.com/ak0gb

**osu!lazer version:** 2019.730.0

**Comment by iiSaLMaN** [comment]
Can you make sure it doesn't skip a song with the default difficulty? that isn't covered in the video

**Comment by Gabixel** [comment]
[**Here's the video**](https://streamable.com/2z0kk). (it seems to work normally with the "default" one)

**Comment by iiSaLMaN** [comment]
Weird, tried to reproduce it and it skipped 2 songs instead
