### ISSUE TITLE
Screenshot bug when storyboard is enabled

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu#5551]
Weird Screenshot bug, map with a played storyboard. (Background is trasparent, screenshotted with png from press F12)

Storyboard on and dim 100%:
![osu_2019-07-31_21-47-35-1](https://user-images.githubusercontent.com/53025167/62243162-01272e00-b3dd-11e9-88d4-7e4b4f598032.png)

Storyboard on and dim 0%:
![osu_2019-07-31_21-51-36](https://user-images.githubusercontent.com/53025167/62243339-64b15b80-b3dd-11e9-970f-1c2e91178a84.png)

Storyboard is disabled:
![osu_2019-07-31_21-50-26](https://user-images.githubusercontent.com/53025167/62243272-43e90600-b3dd-11e9-98db-b829e8a59ea6.png)

Map: https://osu.ppy.sh/beatmapsets/756794#osu/1605148

osu!lazer version: 2019.730.0

Logs: none

**Comment by peppy** [comment]
can you try toggling the "bypass front to back pass" at the bottom of setting and see if that helps?

**Comment by Fatal3ty** [comment]
> can you try toggling the "bypass front to back pass" at the bottom of setting and see if that helps?

Doesn't help, same issue with enabled "bypass font to back pass".

**Comment by peppy** [comment]
@smoogipoo any ideas about this one? seems very weird...

**Comment by smoogipoo** [comment]
Does this happen on non-storyboarded maps, by setting the dim to 100%?

**Comment by Fatal3ty** [comment]
Non-Storyboard Maps is 100% dimmed and worked fine. background is black. But with Storyboard, is weird when take a screenshot.

Dim 0% worked normal with non-storyboard (storyboard disabled on this map):
![osu_2019-08-09_19-52-19](https://user-images.githubusercontent.com/53025167/62798722-4505eb80-badf-11e9-8c96-c3134d528277.png)

**Comment by Craftplacer** [comment]
Does osu!framework have a default black background or is the game elements being written on a transparent canvas?

I assume the background and pretty much everything behind it is removed, leading to transparent background.

**Comment by peppy** [comment]
I believe that is a correct assumption. We may be missing an implicit clear if the clear colour is considered to not have changed.

![image](https://user-images.githubusercontent.com/191335/62829485-97f3b600-bc39-11e9-85e1-e601904010e0.png)

**Comment by Craftplacer** [comment]
@peppy, if fixed, do you think it would be neat to include that issue as a separate screenshot format? With the name @Fatal3ty and I proposed "PNG (lossless, transparent background)".

**Comment by peppy** [comment]
No, this would not be a thing.
