### ISSUE TITLE
Crash when trying to navigate to web browser.

### ISSUE THREAD

**Issue by ojh050118** [ppy/osu#5562]
Describe the crash:
When I click the button, it crashes and I can not go to the web browser.

Screenshots or videos showing encountered issue:
https://www.youtube.com/watch?v=9mr5ixP5T0g&feature=youtu.be

osu!lazer version:
2019.730.0

Logs: 
[log.txt](https://github.com/ppy/osu/files/3457586/log.txt)

Android Device Specifications:
Model: Galaxy S8 (SM-G950N)
OS: Android 9.0 (API 28) One UI
CPU: Samsung Exynos Octa 8895 2.31 Ghz
GPU: Mali-G71

**Comment by iiSaLMaN** [comment]
Not implemented it seems.
