### ISSUE TITLE
Malfunctioning chat on removing part of the link

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5567]
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=lCtejB1qQgY

**osu!lazer version:** 
2019.730.0

**Comment by l3lackShark** [comment]
Might be related to #5283

**Comment by peppy** [comment]
What platform are you on?

**Comment by l3lackShark** [comment]
Windows

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu-framework/pull/3196.
