### ISSUE TITLE
Inconsistency of avatar cropping

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5570]
**Describe the issue:** 
This is not a bug, but a question, rather. As far as I understand, lazer's in-game browser trying to catch up with the new site. But there are some inconsistencies with the avatars at the moment. For example, the avatar on the top of the website has circular cropping, but square-like on the beatmap page. And so, this leads into some problems with avatars that have square outlines at the edges. Also, when it comes to the lazer only, the avatars on the profile page are being rounded a lot more than on the beatmap page. I just wanna know the end goal of all of this and is it considered as done?

**Screenshots or videos showing encountered issue:** 
![ApplicationFrameHost_E2VTCSM8yF](https://user-images.githubusercontent.com/20248967/62354063-769e1600-b525-11e9-9359-1ac1a1a30f35.png)

**osu!lazer version:** 
2019.730.0

**Comment by peppy** [comment]
We have not yet decided on one style. To be safe I'd recommend you do not add borders to support all shapes.
