### ISSUE TITLE
the game did not record any keyboard input on Android

### ISSUE THREAD

**Issue by Ooggle** [ppy/osu#5571]
Hi, i noticed in the issues some persons with keyboard problems, My keyboard doesn't return any value to the textbox. Even specials characters.

The issue seems to be resolved in osu-framework at : ppy/osu-framework#2631
But not merged with this project.

video: https://streamable.com/pezr5

osu!lazer version: 2019.730.0

Redmi k20 pro
Android Pie 9.0

Thanks

**Comment by Ooggle** [comment]
Also it's work great with an usb keyboard.

**Comment by peppy** [comment]
That framework *is* being used. Please test against framework and re-report there if you can reproduce.

**Comment by Ooggle** [comment]
@peppy So i need to made the same build using the updated osu repo ? Or i need to deal with osu-framework files too ?

**Comment by peppy** [comment]
just osu-side should be fine

**Comment by Ooggle** [comment]
Ok so sorry for the time i take to do that. I built the game from the latest release (2019.807.0) and i still don't have any input from system keyboard.

Video showing the keyboard issue in latest release : https://streamable.com/5glnw

osu!lazer version : 2019.807.0
build : release, api level 29
Redmi k20 pro
Android Pie 9.0+

Thanks

**Comment by Ooggle** [comment]
@peppy if i need to do anything else for testing or stuff like that ping me !

**Comment by FajsiEx** [comment]
Seems to be problem only with gboard. Tested out other software keyboard (swiftkey) and it works just fine.

**Comment by Ooggle** [comment]
Oh yeah, that right. Need to implement some sort of fix with gboard then ? That a very weird issue, anyway thanks !

**Comment by Game4all** [comment]
You should probably this issue to something like "Keyboard input doesn't work with Gboard on Android"
