### ISSUE TITLE
Audio issues (BASS Problem?)

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5581]
**Describe the bug:** 
So lazer was in afk mode for like an hour and then the sound disappeared altogether. [1]
Then, after like another hour the sound of mp3's came back, but nothing else. Looks like custom hitsounds do work, but nothing default from the game. This is what happens on changing audio devices: [2]

I am still in this broken state, so give me instructions on how to investigate this if you have some.

**Screenshots or videos showing encountered issue:** 
[1](https://www.youtube.com/watch?v=0YAbtdx94zg)
[2](https://youtu.be/iqq31JZzo74?t=14)
**osu!lazer version:** 
2019.730.0
**Logs:** 
[performance-gamethread.audio.log](https://cdn.discordapp.com/attachments/601048335130034189/606898255196061717/performance-gamethread.audio.log)
[runtime](https://cdn.discordapp.com/attachments/601048335130034189/606897814756392993/runtime.log)

**Comment by iiSaLMaN** [comment]
You mean the track channel where the beatmap music would play

**Comment by l3lackShark** [comment]
I assume so, but all the in-game sounds are dead.

**Comment by l3lackShark** [comment]
UPD: Possible memory leak or malfunctioning garbage collection 
![image](https://user-images.githubusercontent.com/20248967/62411202-1a142700-b609-11e9-8eb5-3d13341f3d81.png)

**Comment by peppy** [comment]
Going to close this one as it's likely already resolved.
