### ISSUE TITLE
Mouse keys on input overlay

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5583]
**Describe the missing feature:** 
Currently, lazer merges input from the mouse and the keyboard. I think that it's important to have mouse keys displayed separately. For simplicity and design reasons we don't even need a second overlay, just glowing the keys with different color would be more than enough.  

**Proposal designs of the feature:** 
https://www.youtube.com/watch?v=4whB6MRANw4

**Comment by peppy** [comment]
How does this work with joystick inputs? midi inputs? is each category going to be separated? I'm not sure I see the point.
