### ISSUE TITLE
Crash after offline on osu!lazer

### ISSUE THREAD

**Issue by XIDigbyKun** [ppy/osu#5584]
I open osu!lazer on android with offline after open osu!lazer, osu!lazer is crash and i got code bug. Idunno what it is code but you can show this 

![Screenshot_Chrome_20190803-185836](https://user-images.githubusercontent.com/47943587/62411723-ccf07f00-b621-11e9-99d8-192f2cfa43a9.png)

**Comment by VPeruS** [comment]
Can you create full copy of last line?

**Comment by iiSaLMaN** [comment]
We need actual logs for this.

**Comment by XIDigbyKun** [comment]
Here we go

time: 1564833464000
msg: Native crash: Segmentation fault
stacktrace: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/oxygen/oxygen:7.1.1/NMF26F/8.11.8:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 10350, tid: 10376, name: Thread Pool Wor  >>> sh.ppy.osulazer <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  0000000000000000  x3  00000077409f99a0
    x4  000000778e9bf1a0  x5  00000077409f9a30  x6  0000000000000000  x7  0000000000000000
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000000  x11 0000000000000000
    x12 0000000000000000  x13 0000000000000000  x14 00000000ffffffff  x15 0000000000000000
    x16 000000774bad31f8  x17 000000774b8fa670  x18 000000774020d71c  x19 000000774baea560
    x20 0000000000000002  x21 0000000000000000  x22 0000000000000006  x23 0000000000000077
    x24 0000000000000000  x25 0000000000000000  x26 00000077409f9b20  x27 00000077bf2ed628
    x28 000000778e9be800  x29 00000077409f8e40
    sp  00000077409f8e40  lr  000000774b841658  pc  000000774b8fa678

backtrace:
    #00 pc 0000000000177678  /data/app/sh.ppy.osulazer-x28bWrz4BwEHEUjKMLmt-A==/lib/arm64/libmonosgen-2.0.so (mono_jit_info_get_method+8)

**Comment by peppy** [comment]
Need actual lazer logs. Very hard to tell what is going on without them (should be in the logs/ folder of lazer data).

**Comment by XIDigbyKun** [comment]
Where i get a file .log 
I see on android/data/sh.ppy.osu!lazer is not found

**Comment by TheComputerGuy96** [comment]
> Need actual lazer logs. Very hard to tell what is going on without them (should be in the logs/ folder of lazer data).

For some reason, there's no such folder in both /data/data/<package name>/files and /sdcard/Android/data/<package name>/files (I've even tried enabling "Performance logging" with no changes)

**Comment by XIDigbyKun** [comment]
Idunno where file log but you can watch this video
[https://youtu.be/bb4pskwHVGE](url)

**Comment by XIDigbyKun** [comment]
After update this osu!lazer 
Offline mode is work now
