### ISSUE TITLE
Different Installations for Different Rulesets

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#5592]
**Describe the new feature:** 
Is it going to be possible for you to download different "packages" of osu from the website? Like light installation packages that only include one ruleset, and then if you want, you can download and add more rulesets. This can be beneficial because it will probably decrease lag and will definitely decrease the installation space required. This will also require a design change in top bar which houses the 4 official game modes and will most likely have to be a single one or will require a different list for each installation.

**Proposal designs of the feature:** 
A change in the osu website that lets you pick which ruleset/mode you want by going to a page called Custom Downloads with (maybe) a dropdownlisting all the current available rulesets/modes(standard, taiko, mania, etc) and you are given different installation files for each of them. After installing, you only get to play the game mode you have downloaded.

I would love a feature like this because sometime I switch game modes and osu starts lagging because it is calculating beatmap difficulties.

**Comment by EVAST9919** [comment]
You can just delete needed ruleset if you want to.

**Comment by peppy** [comment]
Irrelevant because this is not how things will be implemented.
