### ISSUE TITLE
Lazer Tournament Client - Custom backgrounds

### ISSUE THREAD

**Issue by DMills94** [ppy/osu#5599]
**Describe the new feature:** 
Ability to add custom backgrounds to the individual sections of the Lazer tournament client, currently they have to be added to the client through specific names (linked to OWC)

We've found these ones:
![image](https://user-images.githubusercontent.com/31848108/62425760-b35c3f80-b6d4-11e9-8929-58d9febce26d.png)

But it would be better to generify these and/or allow the user to add them via the client! We tried drag + drop `m4v` format stuff, no success!

Also a list of accepted formats would be handy too!

We believe the screens benefitting from a custom background would be:

Standard background
- Bracket
- Schedule
- MapPool
- Intro
- Win screen (one for red, one for blue)
- Gameplay

**Comment by l3lackShark** [comment]
About formats... they are just formats, not containers. So you can just change the extension of your mp4 video to m4v and it will work. Also, if you are interested in using the tools, then I would not recommend doing so as long as #5366 is not resolved. But if you really want to, then DM me in Discord **BlackShark#6201** and I will drop you a video tutorial about tournament tools in it's currnet state.

**Comment by peppy** [comment]
You could just link the tutorial here. Removing discord links as this seems silly.

**Comment by DMills94** [comment]
Just to add the video is really informative, I would recommend @l3lackShark to share however as it is his video I will respect his choice and hope he brings it forward sooner as it might help improve the client from the already good state it's in!

**Comment by Micro-kernel** [comment]
@l3lackShark can you link me the video too please?

**Comment by l3lackShark** [comment]
@Micro-kernel https://www.youtube.com/watch?v=3UZq5WrcOqk

**Comment by peppy** [comment]
I believe this is now fulfilled, and you are able to provide videos per screen.
