### ISSUE TITLE
Negative SS counter

### ISSUE THREAD

**Issue by ZayyKen** [ppy/osu#5604]
[Osu!Mania] A few months ago, I've noticed that some of my million play were deleted. I seen they were replaced by oooooooold play like 2017 one then, I decided to replay them, and since that day I've got a negative yellow SS counter... I'm an Hidden player so I don't understand how can I have -4 yellow SS ? (All the ranked and loved maps I've ever play are donwloaded)
![Screenshot_3](https://user-images.githubusercontent.com/51994902/62431894-08777000-b72c-11e9-8bea-b20d0ae49d07.png)
![screenshot420](https://user-images.githubusercontent.com/51994902/62431957-aff4a280-b72c-11e9-94d6-44b7578151c2.png)
![screenshot421](https://user-images.githubusercontent.com/51994902/62432032-7ec8a200-b72d-11e9-8905-752f2beba234.png)

**Comment by smoogipoo** [comment]
This is not related to osu-lazer but I'm unsure where it should go. @peppy

**Comment by peppy** [comment]
I'll fix this one up.
