### ISSUE TITLE
Exiting the result screen *immediately* results in a deadlock

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#5608]
**Describe the bug:** After a map is completed, exiting it immediately, as in the moment it would start to show up by pressing escape seemingly results in a deadlock. The music will continue playing, but the screen is just frozen and can't be interacted with.
I have been able to reproduce this multiple times, it seems relatively consistent given the timing to trigger it is really precise.
I also still have my debugging window open with lazer in the frozen state but I can't really make use of all the tools provided there (thread stack traces, ``parallel stacks`` graph...). The only thing I could understand is that there are a lot of threading-related threads active.

**Screenshots or videos showing encountered issue:** https://streamable.com/3645m

**osu!lazer version:** bf0f6e1053a72048be37693d63308eba82af01eb

**Logs:** Couldn't find anything remotely related.

**Comment by peppy** [comment]
may be related to the import/results stalls (https://github.com/ppy/osu/issues/5346)
