### ISSUE TITLE
Autoplay button showing incorrect design.

### ISSUE THREAD

**Issue by revelsix** [ppy/osu#5615]
**Describe the bug:** Sorry for the confusing title. In the mod selection screen, mods that have multiple sub-mods (i.e. Sudden Death and Perfect) show a design that has two buttons. Automod has this same design, but no sub-mods are available. 

**Screenshots or videos showing encountered issue:** 
![osu_2019-08-06_01-51-57](https://user-images.githubusercontent.com/45189851/62514567-99625000-b7ed-11e9-8c4f-1033db0053b2.jpg)

**osu!lazer version:** 2019.730.0

**Logs:** not necessary here

**Comment by dscnnctd** [comment]
>**Describe the bug:** Sorry for the confusing title. In the mod selection screen, mods that have multiple sub-mods (i.e. Sudden Death and Perfect) show a design that has two buttons. Automod has this same design, but no sub-mods are available.  ...

@revelsix The missing sub-mod is **Cinema** or **Autopilot** and it hasn’t been added by anyone yet.

**Comment by peppy** [comment]
It's correctly in the overlay but in a disabled state. This is intended behaviour for now.
