### ISSUE TITLE
Exit button an android

### ISSUE THREAD

**Issue by Krper1111** [ppy/osu#5616]
**Describe the bug:** 
As the title says, there is no exit from osu button in main menu on Android. And it's not closing via holding the back button either. Android 5.0.2, device Redmi Note 2

**Screenshots or videos showing encountered issue:** 
I can't get GitHub to upload any image, so I had to upload it on [different](https://paste.pics/6B48P) site

**osu!lazer version:** 
2019.730.0, self-compiled

**Logs:** 
I can't find them. Maybe they're in the app's data, but it requires root and I don't want root it now.

**Comment by peppy** [comment]
This is intentional. Please use the hardware button to return to your home screen.

**Comment by ojh050118** [comment]
Closing the app with the hardware button is inconvenient. The hardware button should be used as the back button.

**Comment by l3lackShark** [comment]
Also, for some reason, the hardware button doesn't exit the game for all the devices that I have.

**Comment by ojh050118** [comment]
So you need to create an exit button for convenience.

**Comment by swoolcock** [comment]
Mobile apps do not have exit buttons.
