### ISSUE TITLE
lazer doesn't free up memory completely

### ISSUE THREAD

**Issue by GetterSetterAndDot** [ppy/osu#5620]
**Describe the bug:**  When I open map, it loads to memory, but when I close it, memory still is busy (this problem occurs with any map, but I've used heavy map for showing bug)

**Screenshots or videos showing encountered issue:**

![image](https://user-images.githubusercontent.com/47123924/62545789-0667fb00-b86b-11e9-987e-de17995bc8c6.png)
![image](https://user-images.githubusercontent.com/47123924/62545846-239cc980-b86b-11e9-9ca6-9fc993a1283f.png)

If you want, you can watch the video how to I took these screenshots (streamable was blocked in my country, so that I have archived the video)
[bug.zip](https://github.com/ppy/osu/files/3472646/bug.zip)

**Comment by peppy** [comment]
This is remaining issues with VBO optimisations and delayed GC. We have confirmed there are no remaining leaks as such.
