### ISSUE TITLE
High precision mouse doesn't respect Windows primary mouse button

### ISSUE THREAD

**Issue by Royce551** [ppy/osu#5628]
**Describe the bug:** 
Pretty much the title. I have my primary mouse button set to be the right mouse button, but osu! still treats the left mouse button as the primary button. Not a gigantic issue, just slightly annoying.
**Screenshots or videos showing encountered issue:** 
Sorry, not the most clear (OBS plugins being annoying)
https://streamable.com/uaype
**osu!lazer version:** 
2017.730.0
**Logs:** 
don't think it's necessary for this kind of issue? please correct if wrong

**Comment by smoogipoo** [comment]
We may not fix this on our side just yet, and see if moving to SDL (via Veldrid or otherwise) will automatically handle this for us.

**Comment by Royce551** [comment]
Looks like this doesn't happen if raw input is off, but obviously, having raw input on is pretty much a requirement when it comes to osu.

**Comment by peppy** [comment]
When using raw input, this would need to be queries manually via registry or other means, I believe.

**Comment by Royce551** [comment]
Fixed when using SDL with raw input

**Comment by bdach** [comment]
I'm like 99% sure the SDL implementation doesn't even have raw input yet...?

**Comment by smoogipoo** [comment]
@bdach You're right. The checkbox should probably be disabled in SDL...

**Comment by peppy** [comment]
This is an (upstream issue)[https://github.com/libsdl-org/SDL/issues/3808], which looks to have already been fixed in newer SDL2 releases. Which reminds me that we need to attempt updating again, and see if the issues we were experiencing last attempt still apply.

**Comment by peppy** [comment]
Confirmed resolved (via https://github.com/ppy/osu-framework/pull/4320)
