### ISSUE TITLE
Quick download button in multiplayer room

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#5636]
It would be useful to have a quick download button in multiplayer room instead of opening the beatmap overlay just to download the beatmap.

**Comment by iiSaLMaN** [comment]
> It would be useful to have a quick download button in multiplayer room instead of opening the beatmap overlay just to download the beatmap.

I would suggest that it takes the overlay download button with yellow colour.

**Comment by peppy** [comment]
This can be solved by showing a beatmap card on the multiplayer screen (same design as osu!direct). The "View Beatmap" button can be removed as a result.

![image](https://user-images.githubusercontent.com/191335/62671762-126ecc80-b9d3-11e9-905f-9c5e7f3564ae.png)

Has been confirmed with @arflyte.
