### ISSUE TITLE
Some elements in results screen are covered when UI Scale is above x1.00

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#5640]
With **UI Scaling** above _x1.00_, some elements in the results screen aren’t scaled correctly.
**without ui scale:**
![A00819E1-B917-4148-8F69-E96E325DF22B](https://user-images.githubusercontent.com/48611569/62657675-417a3500-b924-11e9-88b1-d18a63d53190.png)
**with ui scale (x1.18):**
![E50B9C65-8600-421D-9837-EC9834E69D7E](https://user-images.githubusercontent.com/48611569/62657706-5787f580-b924-11e9-8e30-133c0c623122.png)

**Comment by iiSaLMaN** [comment]
Duplicate of #4791

**Comment by dscnnctd** [comment]
Closing.
