### ISSUE TITLE
Deflate mod causes crash on first slider on some iOS devices

### ISSUE THREAD

**Issue by peppy** [ppy/osu#5645]
Likely related to framebuffer drawing (too big? or just memory exceeded?)

Needs debugging.

**Comment by smoogipoo** [comment]
Temporarily hotfixed by https://github.com/ppy/osu-framework/pull/2742. Keeping this PR open until a proper fix is made or hotfix is justified.

**Comment by peppy** [comment]
Closing (https://github.com/ppy/osu-framework/pull/2744).
