### ISSUE TITLE
Seeking in editor is laggy

### ISSUE THREAD

**Issue by kawaemon** [ppy/osu#5648]
**Describe the bug:** 
Map seeking is very laggy in the editor. 

**Screenshots or videos showing encountered issue:** 
https://streamable.com/0my1e

**osu!lazer version:** 
2019.807.0.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3482264/runtime.log)
[performance.log](https://github.com/ppy/osu/files/3482266/performance.log)
[network.log](https://github.com/ppy/osu/files/3482267/network.log)
[database.log](https://github.com/ppy/osu/files/3482268/database.log)

**Comment by jai-x** [comment]
It looks like the editor is playing though the map using the replay seeking behaviour.
I would imagine it would be better just to jump to that position without playing through it.

**Comment by peppy** [comment]
The editor is an overlay layer on top of gameplay (this is intentional).

We will eventually do an optimisation pass to improve the seeking performance.
