### ISSUE TITLE
Background text in login window wrong.

### ISSUE THREAD

**Issue by Neowise33** [ppy/osu#5650]
**Describe the bug:** 
When logging into your account you have to use your username. The background text in that window states email even though it's not working when using the email.
**Screenshots or videos showing the encountered issue:** 

**osu!lazer version:** 
2019.807.0
**Logs:**

**Comment by iiSaLMaN** [comment]
Is it an account you have already or a new registered account?

**Comment by peppy** [comment]
it worms with email and eventually will only work with email. please provide more details.

**Comment by iiSaLMaN** [comment]
> it worms with email and eventually will only work with email. please provide more details.

I think he's talking about his email, appearing in the profile username at the toolbar, could be about this: https://streamable.com/v7b4d

**Comment by Neowise33** [comment]
Ok, I have to apologize I was just stupid. The account is years old. I copied the email address from Lastpass and pasted into the login window at the top right. That somehow didn't accept it. It also didn't work when I had an accidental space at the end. Both stupid user errors.
