### ISSUE TITLE
Bluetooth audio delay on Android.

### ISSUE THREAD

**Issue by GittyMac** [ppy/osu#5651]
**Describe the bug:** 
Bluetooth audio is delayed, which makes it not sync with the visuals.

**osu!lazer version:** 
local release (Built today)

**Comment by HoLLy-HaCKeR** [comment]
Bluetooth audio always has latency to it, I've noticed it vary from nearly unnoticeable to over a second when watching videos. I don't think this is something that can be fixed in lazer itself.

**Comment by swoolcock** [comment]
All rhythm games are nigh unplayable with bluetooth audio unless you manually set a very large offset in the game settings.  This cannot be fixed in osu! or the framework.

**Comment by peppy** [comment]
There is a setting you can adjust to fix this (universal offset).
