### ISSUE TITLE
BeatmapSetOverlay does not handle multiple backgrounds

### ISSUE THREAD

**Issue by UselessToucan** [ppy/osu#5654]
**Describe the bug:** 
Some beatmap sets have multiple background images(https://osu.ppy.sh/beatmapsets/586889). Song select screen can show different background image for each difficulty, but beatmapset overlay does not do it.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=jlSnmgmlNHs

**osu!lazer version:** 
https://github.com/ppy/osu/commit/0f5af25defccaa739aacd069349ef987b296def8

**Logs:** 
none

**Comment by iiSaLMaN** [comment]
Good first issue. Can be easily implemented

**Comment by peppy** [comment]
how can this be implemented? we don’t even generate these backgrounds web-side (and have no short term intentions of doing so).

**Comment by peppy** [comment]
closing as invalid. you’re welcome to open a proposal osu-web side but i don’t believe it is worth the effort.

**Comment by Joehuu** [comment]
I made one a while ago https://github.com/ppy/osu-web/issues/2687.
