### ISSUE TITLE
Importing maps and skuns

### ISSUE THREAD

**Issue by YTTheNewKiller26** [ppy/osu#5655]
So i need help with importing beatmaps on Osu!Lazer can i get some help

**Comment by swoolcock** [comment]
Issues in this repository are for bug reports and feature requests, not general game help.

To answer your question, there is a button in the settings to import maps from stable, and you can also drag and drop into the window.

**Comment by jai-x** [comment]
Beatmaps can be imported from a local install of stable via a button in the setting.

osu!direct is available for free for anyone to use in lazer.

Skins can be imported by dragging the skin file into the osu!lazer window.
