### ISSUE TITLE
Raw Input

### ISSUE THREAD

**Issue by jkitl** [ppy/osu#5662]
OS: Linux Mint 19
Lazer Version: Latest

Basically, you probably already are aware of this. To make this short, raw input completely breaks when you build on Linux from what i see. However, keeping raw input off keepd you in ctronol of your cursor. With it on, you COMPLETELY lose control of your cursor, thus i'm not able to change my cursor sensitivity from what i see. Not sure if this happens for windows users too, just thought i'd point it out!

Keep up the good work!

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/3489
