### ISSUE TITLE
Connection android

### ISSUE THREAD

**Issue by TrustMeh** [ppy/osu#5667]
Osu! on android won't let me use any of internet related futures even when i have stable and good connection, restarting doesn't work neither waiting for a long time to connect or login ( on 1st screenshoot i couldn't login and on 2nd nothing is loading)

![Screenshot_2019-08-09-21-52-37](https://user-images.githubusercontent.com/36709208/62805759-3fb19c80-baf1-11e9-8259-39aa52ec0cf6.jpg)
![Screenshot_2019-08-09-22-01-19](https://user-images.githubusercontent.com/36709208/62805774-4d672200-baf1-11e9-9c5a-e542dfa07759.jpg)

Version:v2019.704.0

**Comment by l3lackShark** [comment]
Do you use cellular network to connect? If so, try using Wi-Fi or switch your phone to Airplane mode and then turn it off again. Also, are you sure about your build number? 2019.713.0 was the first version to add Android solution as far as I'm concerned. If you used to self-compile before that, then try to upgrade to the latest release first.
