### ISSUE TITLE
Keymode display and filter for osu!mania special styles

### ISSUE THREAD

**Issue by abraker95** [ppy/osu#5668]
Dependent on https://github.com/ppy/osu/issues/2203

**Describe the new feature:** 
When looking for or at maps, players need indicators telling whether a map is special style. Adding a filter for this property would also help players search for just special style or just normal style maps.

**Proposal designs of the feature:** 
-  **Keymode display in song select:** Special styles are better recognized by the keymode+1 format so key count display in song select can show keymodes as: 8k, 7k+1, 6k, 5k+1, etc.
- **Filtering:** Not entirely sure what the best way of going about this. Perhaps something like this: `key=8 special=true`

**Comment by awesomecuber** [comment]
Can I propose filtering be done like: "keys=7+1" and "keys=8"? I'd assume that most mania players view 7k+1 (special style) completely differently from 8k (not special style).

**Comment by peppy** [comment]
Can be considered after we get the basics in (https://github.com/ppy/osu/pull/3906).

**Comment by kkartaltepe** [comment]
+1 and since `keys=X` is a valid filter in standard, so it would be nice to have parity.

**Comment by peppy** [comment]
Adding to february milestone; should be a pretty low effort implementation, in theory.

**Comment by bdach** [comment]
It is a low effort implementation if we're fine with a hard-coded `Beatmap.RulesetID == 3` check in `CarouselBeatmap` to only interpret the key filter when it makes sense. Otherwise there'll be a fair bit more of work to develop a ruleset API for extending the standard set of filters.

**Comment by smoogipoo** [comment]
It's worth doing this properly with a ruleset API.

**Comment by peppy** [comment]
I'm going to close this issue out as the display of key count is now completed (via https://github.com/ppy/osu/pull/25711). Of note, special styles are not yet being displayed, but they are also not implemented anywhere yet, so that can come later.
