### ISSUE TITLE
Attempted to scroll to end of 10 minute map, osu! crashed (editor)

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#5670]
I opened osu! and jumped into the editor after loading a song - i scrolled to the end and the Notifications panel opened with 4 errors and the game froze

Logs: I opened osu! again before reporting, so im not sure if they'll help but they're attatched
[network.log](https://github.com/ppy/osu/files/3488855/network.log)
[performance.log](https://github.com/ppy/osu/files/3488856/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3488857/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3488858/updater.log)
[database.log](https://github.com/ppy/osu/files/3488859/database.log)

2019.809.0

AMD Ryzen 1500X - 16GB Ram - AMD Radeon HD 7700 - Windows 10 1903

**Comment by iiSaLMaN** [comment]
> I opened osu! again before reporting, so im not sure if they'll help but they're attatched
No. they will never help, the logs are all reset. finding the exception name and when it occurred exactly would help.

**Comment by Lolihunter1337** [comment]
i tried it with a longer map and this is the result. hope those help

[performance.log](https://github.com/ppy/osu/files/3494818/performance.log)

[runtime.log](https://github.com/ppy/osu/files/3494819/runtime.log)

**Comment by smoogipoo** [comment]
Related to #5676 and will be fixed via the same solution.
