### ISSUE TITLE
Login Prompt for TournamentTools

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5671]
**Describe the new feature:** 
Currently, if a user has not saved his password in the main client, the online part of tournament tools will not work and throw this into logs:

>!2019-08-10 03:41:59: Request to https://osu.ppy.sh/api/v2/users/1/ failed with System.Net.WebException: Unauthorized.

I think it's necessary to add some kind of way of telling the user what he has to do in order to connect. Login Prompt might be one of the solutions.

**Proposal designs of the feature:** 
https://www.youtube.com/watch?v=72I5FC8rLDc

**Comment by iiSaLMaN** [comment]
The issue seems to be that the API requests do not have an authorization key due to the user not logging in.

**Comment by peppy** [comment]
I do have intention on making a setup screen which guides through all the prereq steps to having the tournament tools ready for use.

**Comment by iiSaLMaN** [comment]
I believe this is fixed in #6211.
