### ISSUE TITLE
Beatmap track restarts to the preview point on track ending

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5672]
**Describe the bug:** when song in song select ends it should start at start of the song not preview point

**Comment by iiSaLMaN** [comment]
Please change the title to be descriptive a bit: `Beatmap track restarts to the preview point on track ending`

**Comment by Aergwyn** [comment]
It was intentionally changed to restart at preview point according to stable.

**Comment by ticotaco72** [comment]
but when starting again it should go at start of the song i think

**Comment by Joehuu** [comment]
Duplicate of #4684. Should continue playing at the same point in gameplay, not the beginning.

**Comment by Joehuu** [comment]
Whoops wrong thought

**Comment by peppy** [comment]
Closing as duplicate of #4684.

**Comment by ticotaco72** [comment]
It is not a duplicate as I mean here case that you aren't playing but you are in song select long enough that whole song has played and starts again

**Comment by peppy** [comment]
this already matches stable, which i believe is correct for now.
