### ISSUE TITLE
CPU and GPU are being underutilized

### ISSUE THREAD

**Issue by SaggitariusAStar** [ppy/osu#5673]
**Describe the bug:** Hello. So I've decided to benchmark osu and see how it performs under my new system. My GPU stood at around 50-60% most of the time in game and my CPU cores never hit 100% utilization (not a single core or virtual core). And my conclusion was that it clearly seems that my system is being underutilized. 

My thoughts are as follows:
1. The CPU may be continously waiting for I/O operations and cannot fully feed the GPU the information at full speed.
2. Bad quality code.
3. Maybe loading beatmaps directly into VRAM instead of DRAM may improve performance? Since the CPU doesn't need to send as much information about what's happening on the screen to the GPU then.

Ideal scenario: GPU at 100% utilization, CPU feeding information with more than one real core

_My system:
CPU: Ryzen 7 3700X (stock clocks)
GPU: RTX 2060 Super (with a bit of an OC from fabric)
RAM: 16 GB at 3200 MHz with CAS Latency: 16 (full latency: 16-18-18-18)_

**Screenshots or videos showing encountered issue:** Below are recordings of plays and live information on screen about my GPU and CPU utilizations. Sofware used for recording was OBS (don't know why but the videos turned out to be really laggy with last run using NVENC to record being the laggiest one, my experience was butter smooth though):

_Everything was recorded at my native resolution 1920x1080 at 60fps._

**Run 1:**
Played around with CPU scheduling and gave OSU the first CCX and OBS the second CCX. 
Recorded on the CPU with H.264.
![OBS](https://user-images.githubusercontent.com/36274223/62826725-3562d180-bbc9-11e9-8b0b-56949b80e71b.PNG)
![osu](https://user-images.githubusercontent.com/36274223/62826726-3562d180-bbc9-11e9-9415-33d9c630fddb.PNG)
Results are as follows: https://drive.google.com/open?id=1-UmxqS9v4x7yRMsRTct--SxieSYHhCa8

**Run 2:**
This time I left windows to decide which cores the respective apps should use. That means the CPU Affinity setting was All Cores for OBS and OSU.
Recorded on the CPU with H.264.
Results are as follows: https://drive.google.com/open?id=19yR3YKdec39d7K9JJTJzVyXbH4AGoqtY

**Run 3:**
CPU scheduling as on Run 2 but this time I recorded with NVENC using the GPU instead of the CPU.
Results are as follows: https://drive.google.com/open?id=1r7oubLwTe9zg1MAKEwbzb8YsChZ67W6n

**osu!lazer version:** 2019.809.0

**Logs:** 
[network.log](https://github.com/ppy/osu/files/3489284/network.log)
[performance.log](https://github.com/ppy/osu/files/3489285/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3489286/runtime.log)
[database.log](https://github.com/ppy/osu/files/3489287/database.log)

P.S. Forgive my osu plays. I had dry eyes. I promise I'm not that bad.

**Comment by peppy** [comment]
This is all very wrong, sorry. We are never aiming for 100% utilisation. This is energy inefficient and bad to the environment.

Our goal is to render as few GPU frames as possible, and keep update running at 1000hz. No more, no less.

**Comment by SaggitariusAStar** [comment]
> _"This is all very wrong (or at very least, irrelevant), sorry. We are never aiming for 100% utilisation. This is energy inefficient and bad to the environment."_
This is one way to improving FPS. You fully make use of the hardware you have. People have VSYNC you know? If they think it's bad for the environment they can turn it on. You should leave the choice to the people, not you make that choice.
> _"Our goal is to render as few GPU frames as possible, and keep update running at 1000hz. No more, no less."_
So your goal is to **reduce** FPS? Now that's just plain wrong. Again, leave the choice to the user. If the user wants all the frames, leave him have all the frames.
> _"We still have remaining performance improvements to make to reduce cpu/gpu usage (not increase) but our focus is NEVER going to be on utilisation."_
Fair enough. Optimization.
> _"This is also a bad measurement to use when benchmarking because cpu/gpu differences on different target PCs could cause completely different saturation points."_
That is true. And it happens with almost every game there is. It is unavoidable. Your CPU could be bottlenecking your GPU if your setup isn't right. That's the user's fault most of the time, not the developer's. Now in this game, there is no saturation point (if you define it as 100% utilization for either GPU or CPU), so it doesn't matter. The point of these benchmarks was to showcase how osu!lazer underutilizes my system.

**Comment by EnjoyTheNoise** [comment]
So what is the point of opening an issue, if it's really targeting only your system?
Ryzen 7 3700X / RTX 2060 Super may be underutilized from you point of view, but not everyone has that powerful setup. Many people will still try to play on integrated GPU with some old crappy Intel.

As for trying to render less frames, how can it lead to fps drop? It's only one of the factors tbh. The point is - team is trying to request as few frames as possible and keep pretty high update rate (correct me if I'm wrong).

**Comment by SaggitariusAStar** [comment]
Rendering GPU frames is what you see on the screen. The less frames, the laggy it will feel. My point is that even with an RTX 2060 Super (not even the top card in NVIDIA's lineup) is being underutilized. So people may have GPUs that are even better which are being underutilized. Now, I don't know if there actually is a cap on utilization regardless of the GPU speaking (don't have my old system now), but either way, this is about giving choice to the user, not taking away things from the user.

**Comment by peppy** [comment]
Closing this thread for now. We are very aware of how and what to optimize for, after 10+ years of experience.
