### ISSUE TITLE
taiko gameplay doesnt have the correct scaling for other resolutions

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#5685]
**Describe the bug:** 
scaling for taiko seems off and not just a little bit i would say. my native resolution is 1280x1024 and i would never be able to play with such a small playfield. i dont use any extra options to scale the gameplay. (it doesnt really make it better in this case)

**Comparison below:**
osu!stable:
![screenshot276](https://user-images.githubusercontent.com/43358824/62840619-e9ce2780-bc9d-11e9-8b4d-1a2e90574056.png)

osu!lazer:
![osu_2019-08-12_00-12-14](https://user-images.githubusercontent.com/43358824/62840651-8264a780-bc9e-11e9-82ec-175cfc9868a2.png)
i hope i forgot nothing

**osu!lazer version:**
2019.809.0

**Logs:** 
not needed i suppose

**Comment by peppy** [comment]
This is intentional currently to keep the playfield in a constant scale across all aspect ratios. If it was to change, you would have less visibility of hitobjects at square aspect ratios – is that what you want?

**Comment by mouzedrift** [comment]
yes, at least for legacy skins.

**Comment by ayyEve** [comment]
There are many people who play 4:3 because of the different play-field. I believe it would be unfair to them to force this change. I would keep the field consistent between resolutions but change based on aspect ratio (at least between 4:3 and 16:9).
