### ISSUE TITLE
Difficult to select maps with Tablet in Song Select

### ISSUE THREAD

**Issue by Emoished** [ppy/osu#5689]
https://streamable.com/0nqfg

In stable the game favours clicking the map far more, whereas on Laser even a very slight movement on the pen as you touch the tablet surface causes scrolling instead of a *click*.

**Comment by zzahkaboom24** [comment]
Yup, same here.

**Comment by mouzedrift** [comment]
duplicate of #4842 i would say

**Comment by Emoished** [comment]
Agreed covered by #4842. I will close
