### ISSUE TITLE
Song select design suggestions

### ISSUE THREAD

**Issue by Emoished** [ppy/osu#5690]
1. 
https://imgur.com/a/Ff0ZCC4

2.
~~https://streamable.com/ad9km~~

3.
https://imgur.com/a/DoYzOo7

Various UI/UX suggestions - happy to split this up if necessary.

1. The Song specific setup details (CS/HP/AR) should be view-able from the Local / Country Leaderboards, a neat solution here could be to add them as a second layer underneath the Song duration, BPM & # of objects in a similar style.
In addition to this the user rating / points of failure are (imo) very rarely used / unimportant & take up valuable space ~ so I would be suggesting a removal of the details tab entirely & just keeping this beatmap info on the website.

~~2. Sorting by difficulty will not make sense unless the individual difficulties can be split out from the "Song Folder". This causes issues with the current design choice of not including the Song name on each difficulty.~~ Covered by #2547 thx ppy

3. Song name in the top left box needs a darker shadow behind it for visibility on white backgrounds & needs to be wrapped in order to avoid clipping for long song names. Like the design on the right hand side of the screen (& in stable) the Song name should be above the difficulty name.

Apologies if any of this info is already well known, I did review the UI/UX issue tickets, but could have missed things.

**Comment by peppy** [comment]
1. the details haven't been completely implemented and will match something like web when done
2. https://github.com/ppy/osu/issues/2547
3. sure, could do with some more tinting.

**Comment by Joehuu** [comment]
Song select will have a redesign as seen in https://github.com/ppy/osu/issues/10869#issuecomment-727989583 and I'm mostly sure the concerns here will be resolved. Closing for the same reason as that issue.
