### ISSUE TITLE
Game Crashes intermittently when playing beatmapson standard mode

### ISSUE THREAD

**Issue by rmjanowitz** [ppy/osu#5692]
Sporadic crashes during standard gameplay. Seems to happen after playing a few maps. Map will freeze during play, then after several seconds pause or fail menu appears. At this point you can quit the map and restart map from the main menu or restart the map from the pause/fail menu but an exception will be thrown.

**Screen of Exception:** 
![exception](https://user-images.githubusercontent.com/49151955/62884995-a8189d80-bcec-11e9-9205-766246fb3ce6.JPG)

**Video of A Crash:**
https://www.twitch.tv/miss_moxi/clip/DeafInnocentStarlingVoteYea

**osu!lazer version:** 2019.809.0

**Logs:** 
[updater.log](https://github.com/ppy/osu/files/3493671/updater.log)
[database.log](https://github.com/ppy/osu/files/3493672/database.log)
[network.log](https://github.com/ppy/osu/files/3493673/network.log)
[performance.log](https://github.com/ppy/osu/files/3493674/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3493675/runtime.log)

**Comment by peppy** [comment]
That looks like something at your system's end (it's a native crash).

Please refer to google for possible solutions.

https://www.google.com/search?q=%22exception+processing+message%22&rlz=1C1CHBD_enJP777JP777&oq=%22exception+processing+message%22&aqs=chrome..69i57.3434j0j7&sourceid=chrome&ie=UTF-8
