### ISSUE TITLE
Key bindings for song control in main menu

### ISSUE THREAD

**Issue by coldrage101** [ppy/osu#5693]
**Describe the missing feature:** 
In Stable you can use the Z, X, C and V keys, along with the F1 to F5 keys to control the currently playing song on the main menu. This is very convenient if you are like me and use osu! as your music player.

**Proposal designs of the feature:** 
Implement key bindings, with defaults the same as stable but changeable in Settings/Input/Key configuration

**Comment by iiSaLMaN** [comment]
Duplicate of #3213 and will be fixed in #5268

**Comment by coldrage101** [comment]
I have added the detail from here to https://github.com/ppy/osu/issues/3213
I will now close this issue as a duplicate.
