### ISSUE TITLE
Interests/Occupation's profile text starts a new line if it's added from the old website

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5702]
**Describe the bug:** I was looking at the Friends tab when I found a profile with a weird text format on the `interests` part. I tried to reproduce it and managed to find the cause.

If you modify `occupation` or `interests` from the **new** site, you _can't_ start a new line (and that's the correct one), but on the **old** one you _can_ do that, and from the new website the text is converted to a single line, but not on Lazer.

**Screenshots or videos showing encountered issue:** 
Editing from the old website:
![old website](https://user-images.githubusercontent.com/43073074/62930842-80ddd100-bdbd-11e9-8583-af05f56ad2e4.png)
Profile on Lazer client:
![Lazer client](https://user-images.githubusercontent.com/43073074/62930865-8dfac000-bdbd-11e9-887f-908119ccb5f5.png)
Profile on new website:
![new website](https://user-images.githubusercontent.com/43073074/62931125-0feae900-bdbe-11e9-99f2-16bfd5326bc5.png)

**osu!lazer version:** 2019.809.0

**Comment by peppy** [comment]
Does this apply to any other fields, or just interests?

**Comment by Gabixel** [comment]
Only to `Interests` and `Occupation`'s fields

**Comment by Gabixel** [comment]
Seems fixed:
![edit](https://user-images.githubusercontent.com/43073074/63635454-12253100-c663-11e9-81df-21e7d86018c6.png)
![profile](https://user-images.githubusercontent.com/43073074/63635455-13565e00-c663-11e9-8c7f-65310b4c024f.png)

but I don't know if I should close it: in #5732 you talked about a possible server-side fix in the future.

**Comment by peppy** [comment]
Safe to close for now.
