### ISSUE TITLE
Osu! installer not working

### ISSUE THREAD

**Issue by LandMarkSugar6** [ppy/osu#5703]
I had to take a break from osu because of school and stuff, but i wanted to start playing it again
So, i downloaded the osu! installer a week ago and kept it for download.
everytime it reached above 50% it goes back to 0 and i cant download osu!
 Please help me with this issue.

PS : I never had this issue before

**Comment by Gabixel** [comment]
Please describe your system information, like the Operating System and architecture (32 or 64) etc. Also, this repository is for osu!azer, not osu! stable, so you probably have to ask this somewhere else (I don't know if it's better via mail or from the forum, @peppy ?)

**Comment by mouzedrift** [comment]
> I had to take a break from osu because of school and stuff, but i wanted to start playing it again
> So, i downloaded the osu! installer a week ago and kept it for download.
> everytime it reached above 50% it goes back to 0 and i cant download osu!
> Please help me with this issue.
> 
> PS : I never had this issue before

are you talking about osu!lazer or osu!stable?

**Comment by Kashouryo** [comment]
He mentioned download. Probably a osu!stable issue since lazer installer does not download any content(doesn't even have a gui while installing)
