### ISSUE TITLE
Follow points are not shown

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#5704]
**Describe the bug:** On the skin I'm using, I can not see follow points at all. I've noticed the feature is implemented because a beatmap skin displays them correctly, but I currently just don't have any follow points.

Skin I'm using: https://drive.google.com/open?id=1tJt0RWWkUAocyL5BJriywa9_05zhPnAa

**osu!lazer version:** latest

**Comment by iiSaLMaN** [comment]
the follow points of that skin seems to be animated, animated skin elements are not supported as of yet.

**Comment by peppy** [comment]
Should be resolved via https://github.com/ppy/osu/pull/5497

**Comment by iiSaLMaN** [comment]
> Should be resolved via #5497

I don't think so, but is related:
`This implements general handling for animatable components, however most components haven't been marked as animatable yet.`
