### ISSUE TITLE
Unable to log in and now won't launch

### ISSUE THREAD

**Issue by StrawberryMahjong** [ppy/osu#5706]
I recently compiled an android build of Lazer and when I tried to log in, it got stuck on 'Attempting to connect...'. Is this an issue with Android 9? If so, is there a way to fix this myself in Visual Studio?

**Comment by iiSaLMaN** [comment]
please attach the logs, there should be a network exception somewhere that would help us debug your issue

**Comment by StrawberryMahjong** [comment]
Where would the logs be located?

**Comment by StrawberryMahjong** [comment]
And now I've got a new issue. I thought I'd try to build it again, maybe update the source code with git pull but now it doesn't even launch. It starts, cuts to a black screen, then closes.

**Comment by EVAST9919** [comment]
We are aware of most common issues _like this one_ and that's why android build is not public for users yet.

**Comment by iiSaLMaN** [comment]
@StrawberryMahjong why closed? reopen and check if the logs are in `android/data/lazer`
