### ISSUE TITLE
no welcome to osu sound and "blank" sound

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5707]
**Describe the bug:** i opened lazer and i didnt hear "welcome to osu!" sound but after it i  normally heard triangles soundtrack; when it ended(i didn't enter song select); next song started; and after around 10 seconds it "froze" it wasn't possible to hear it but eg music player was scroling fine; changing the song didn't help 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2019.813.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3498369/database.log)
[network.log](https://github.com/ppy/osu/files/3498370/network.log)
[performance.log](https://github.com/ppy/osu/files/3498371/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3498372/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3498373/updater.log)

**Comment by iiSaLMaN** [comment]
> **Describe the bug:** i opened lazer and i didnt hear "welcome to osu!" sound but after it i normally heard triangles soundtrack; when it ended(i didn't enter song select); next song started; and after around 10 seconds it "froze" it wasn't possible to hear it but eg music player was scroling fine; changing the song didn't help
> 
> **Screenshots or videos showing encountered issue:**
> 
> **osu!lazer version:** 2019.813.0
> 
> **Logs:**
> [database.log](https://github.com/ppy/osu/files/3498369/database.log)
> [network.log](https://github.com/ppy/osu/files/3498370/network.log)
> [performance.log](https://github.com/ppy/osu/files/3498371/performance.log)
> [runtime.log](https://github.com/ppy/osu/files/3498372/runtime.log)
> [updater.log](https://github.com/ppy/osu/files/3498373/updater.log)

so the intro is there but you don't hear the samples?

**Comment by mouzedrift** [comment]
> **Describe the bug:** i opened lazer and i didnt hear "welcome to osu!" sound but after it i normally heard triangles soundtrack; when it ended(i didn't enter song select); next song started; and after around 10 seconds it "froze" it wasn't possible to hear it but eg music player was scroling fine; changing the song didn't help
> 
> **Screenshots or videos showing encountered issue:**
> 
> **osu!lazer version:** 2019.813.0
> 
> **Logs:**
> [database.log](https://github.com/ppy/osu/files/3498369/database.log)
> [network.log](https://github.com/ppy/osu/files/3498370/network.log)
> [performance.log](https://github.com/ppy/osu/files/3498371/performance.log)
> [runtime.log](https://github.com/ppy/osu/files/3498372/runtime.log)
> [updater.log](https://github.com/ppy/osu/files/3498373/updater.log)

can you provide a video? that would probably be the fastest way

**Comment by ticotaco72** [comment]
i see everything but don't hear "welcome to osu!" words; video comming in a minute

**Comment by iiSaLMaN** [comment]
can you just make sure the sample volume is not 0?

**Comment by ticotaco72** [comment]
@iiSaLMaN this no an issue i'm not changing volume in this process; i hear the song after it

i can't reproduce for now so no video;

i couldn't reproduce on circles intro too
