### ISSUE TITLE
In game tablet driver

### ISSUE THREAD

**Issue by Nouko61** [ppy/osu#5712]
Is it possible to add an in-game tablet driver to configure tablet area?
Just like hawku's, everyone can get lower input latency.

**Comment by Nouko61** [comment]
In other words, is it possible to bypass official-driver's smoothing and noise reduction witch increase input latency?

**Comment by l3lackShark** [comment]
I was thinking about the same idea, but for mobile devices. Some tablets do have native android/iOS support, but you can't configure the Area as far as I know. Also, Wacom tablet drivers are a pain to set up on Linux. Would be a cool addition if it's possible to implement.

**Comment by Faithy3** [comment]
This would be a brilliant idea, but I'm not sure how possible it would be. I don't know much about how the drivers work, but I know that for Hawku's drivers, you have to completely uninstall the official Wacom driver to get it working. If it's possible to bypass Wacom's drivers without uninstalling or stopping them, then that would be absolutely incredible, allowing for all the features of Wacom's drivers (mostly per-app settings) outside of osu!, And then low-latency drivers while in osu!. That said, I'm not sure how possible that is.

On Aug 14, 2019 02:05, l3lackShark <notifications@github.com> wrote:

I was thinking about the same idea, but for mobile devices. Some tablets do have native android/iOS support, but you can't configure the Area as far as I know. Also, Wacom tablet drivers are a pain to set up on Linux. Would be a cool addition if it's possible to implement.

**Comment by peppy** [comment]
We will be implementing in-game mapping for tablets. It WILL not and SHOULD not be a driver level.

Use manufacturer drivers.
