### ISSUE TITLE
New Intro - Outlined Part Does Not Appear on macOS.

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#5716]
**Describe the bug:** 
The "Outlined" or "Trace" segment of the new intro does not appear on mac.

**Screenshots or videos showing encountered issue:** 
https://puu.sh/E54Km/2684934f9c.mov

**osu!lazer version:** 
2019.813.0

**Logs:**

**Comment by smoogipoo** [comment]
Resolved by https://github.com/ppy/osu-framework/pull/2761

Will be resolved next release.
