### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5717]
**Describe the crash:** Exiting SongSelect, the background turned black, then re-entering SongSelect and switching between songs, a few of them didn't have their panel background, and osu! crashed.

**Screenshots or videos showing encountered issue:** 
(The only useful screenshot I have is this one with the black background)

![Menu](https://user-images.githubusercontent.com/43073074/63014658-50666780-be8f-11e9-85c8-6f1cff1bb6f0.jpg)

**osu!lazer version:** 2019.813.0 (local release)

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3500948/database.log)
[runtime.log](https://github.com/ppy/osu/files/3500949/runtime.log)
[performance.log](https://github.com/ppy/osu/files/3500950/performance.log)
[network.log](https://github.com/ppy/osu/files/3500951/network.log)

**Phone Specifications:** 
Model: GALAXY Note 3 Neo Lite
OS: Android 5.1.1 (Lollipop)
RAM: 2GB
CPU: Exynos 5 5260 (6 core: 2x 1.3GHz, 4x 1.7GHz)

(The Internal Storage is almost full and Lazer is located there, I don't know if that caused the crash)

**Comment by peppy** [comment]
Probably memory related?

**Comment by Theighlin** [comment]
This is a stale issue and can probably be closed unless OP can reproduce the crash on the same phone with the most recent version of the game.
