### ISSUE TITLE
osu!direct difficulty preview

### ISSUE THREAD

**Issue by revelsix** [ppy/osu#5722]
**Describe the new feature:** On the osu! site, you can hover over the little difficulty circles and preview their exact star rating, which something I think would be pretty useful in osu!direct

**Proposal designs of the feature:** 
![difficulty preview](https://user-images.githubusercontent.com/45189851/63027110-569e1900-be7a-11e9-9083-d3f7372f328d.jpg)
 excuse my poor MS Paint skills

**Comment by jai-x** [comment]
This already being worked on, see here: https://github.com/ppy/osu/pull/5036
