### ISSUE TITLE
Hits have wrong hitsound if it's changed before (or during) first gameplay

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5723]
**Describe the bug:** When entering playerloader, if you switch the "Beatmap hitsounds" option, on the first play the hitsounds are not the selected ones (example: if beatmap hitsounds were **off** and you switch them **on** when in playerloader, the first play has the hitsounds of the Lazer default skin and not of the beatmap).
But this seems to happen when also changing skin during gameplay (In the second video I used Autoplay, but you can reproduce the issue without it)

**Screenshots or videos showing encountered issue:** 
Hitsounds switch - https://streamable.com/j0zzd
Changing Skin during gameplay - https://streamable.com/2eiov

**osu!lazer version:** 2019.814.0

**Comment by iiSaLMaN** [comment]
You mean that the hit sounds do not update corresponding to the option or the new selected skin, right?

**Comment by Gabixel** [comment]
Exactly
