### ISSUE TITLE
Toggles in PlayerLoader reproduce on/off sound twice

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5724]
**Describe the bug:** The toggles in playerloader reproduce the on/off sound two times.

**Screenshots or videos showing encountered issue:** https://streamable.com/o7uz2

**Comment by Desconocidosmh** [comment]
Are you using the latest version? It seems to be [working fine for me.](https://youtu.be/X7VzjKTBuvo)

**Comment by peppy** [comment]
This can be reproduced by opening settings at least once after startup.
