### ISSUE TITLE
Enabled raw input; cursor now moves too fast

### ISSUE THREAD

**Issue by thetylerwolfman** [ppy/osu#5727]
**Describe the bug:** 
I enabled raw input to adjust the sensitivity and now  the cursor moves so fast and it only goes from corner to corner and I cannot find a way to change it.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.814.0
**Logs:**

**Comment by peppy** [comment]
Please use ctrl-alt-r to reset input settings.
