### ISSUE TITLE
Quick retry transition sound effect is abrupt / wrong

### ISSUE THREAD

**Issue by Kamilake** [ppy/osu#5735]
**Describe the bug:** 
The background music is played where the background music should not be.(loading page)
It's not always happening, it's sometimes happening.
**Screenshots or videos showing encountered issue:** 
[Please see this video https://youtu.be/D6GgwXGGTZM ](https://youtu.be/D6GgwXGGTZM)
Please turn up the volume of video
**osu!lazer version:** 
2019.814.0
**Logs:** 

(I am new to Github today. Please tell me if I did something wrong)

**Comment by peppy** [comment]
The transition for this is currently not implemented correctly (can be abrupt).
