### ISSUE TITLE
Beatmap Panel on Song Select is blank

### ISSUE THREAD

**Issue by mackyclemen** [ppy/osu#5736]
**Describe the bug:** 
Instead of the usual song information and the beatmap background showing in the panel, it shows a white panel instead.

It's working before the 2019.807.0 build.

**Screenshots or videos showing encountered issue:** 
Video: https://youtu.be/3hIfHPZyOiM
Screenshot:
![Screenshot_20190816-061238](https://user-images.githubusercontent.com/17867386/63130510-48243e80-bfed-11e9-8ad3-479e5a98f6ca.jpg)

**osu!lazer version:** 
2019.814.0 local release

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3507355/runtime.log)
[performance.log](https://github.com/ppy/osu/files/3507356/performance.log)

**Device Specifications:**
OS: Android 8.0
Device: Samsung Galaxy S7 edge (SM-G930FD)

**Comment by mackyclemen** [comment]
A little bit of update while I was playing with my phone resolution settings...
Apparantly it's getting sort of visible when the phone's screen resolution is at around 720p.

![Screenshot_20190922-202128](https://user-images.githubusercontent.com/17867386/65387165-fce11680-dd76-11e9-8dc3-f8824b07d763.jpg)

The screenshot above is in 720p...

![Screenshot_20190922-202544](https://user-images.githubusercontent.com/17867386/65387203-6cef9c80-dd77-11e9-8010-8228bf6641ca.jpg)

then in 1080p...

![Screenshot_20190922-202644](https://user-images.githubusercontent.com/17867386/65387207-75e06e00-dd77-11e9-8df5-8ed1c150486a.jpg)

then in 1440p...

**Comment by peppy** [comment]
Can you see any other issues with sliders or other game elements? Is the wedge the only place this occurs?

**Comment by smoogipoo** [comment]
Also just to rule it out, does it improve if the "bypass front-to-back pass" option is enabled at the bottom of settings?

**Comment by Joehuu** [comment]
Does this still happen @mackyclemen?

**Comment by peppy** [comment]
99% sure this has been fixed (looks like an invalidation failure on the buffered container). Let's close for now pending any follow-up from the user.
