### ISSUE TITLE
The game can run in the background unpaused

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#5740]
**Describe the bug:** Usually, tabbing out will result in the game being paused. However, if the game was just unpaused when alt-tabbing, the animation for the "hold for menu" button in the bottom left will play, but it won't actually pause the game, thus resulting in the game running in the background without being paused (which I believe shouldn't be possible).

**osu!lazer version:** uh master / 2019.814.0

**Comment by peppy** [comment]
The game should probably continue to attempt to pause until it succeeds in this scenario.

**Comment by peppy** [comment]
@frenzibyte were you looking into the logic surrounding this?

**Comment by frenzibyte** [comment]
Yeah, will fix this as you stated above (pause again when the cooldown is off).
