### ISSUE TITLE
Implement Score Meter

### ISSUE THREAD

**Issue by jai-x** [ppy/osu#5743]
The score meter gameplay element is not present in lazer yet.

In stable, it is able to display as list of colors representing hits as they are made or as a bar displaying hit error.

Color type:
![score_meter_color](https://user-images.githubusercontent.com/8362491/63197779-a47c7200-c070-11e9-8d81-fc249ccc587c.png)

Hit error type:
![score_meter_error](https://user-images.githubusercontent.com/8362491/63197788-acd4ad00-c070-11e9-80b5-054621953b63.png)

**Comment by peppy** [comment]
There is already a design for this (and and a wip PR by @EVAST9919).

**Comment by jai-x** [comment]
Is the new design and PR available to view anywhere? I can't seem to find them ¬_¬

**Comment by iiSaLMaN** [comment]
> Is the new design and PR available to view anywhere? I can't seem to find them ¬_¬

For the design:
![image](https://user-images.githubusercontent.com/22781491/63217664-001f2c00-c153-11e9-8a54-39061fc9278b.png)

As for the PR, I think his branch got deleted by accident

**Comment by EVAST9919** [comment]
> As for the PR, I think his branch got deleted by accident

Nope, It's not
