### ISSUE TITLE
Quick retry button should skip song intro (by default)

### ISSUE THREAD

**Issue by abbradar** [ppy/osu#5745]
**Describe the new feature:** 

In osu! pressing quick restart button also automatically skips song intro. This is quite useful for drum controllers: you bind one button on the controller to quick replay, push it with a stick and continue trying. At the same time this is not always a desirable behaviour.

**Proposal designs of the feature:** 

Add an option to restore old behaviour (skipping intro after quick restart), disabled by default.

**Comment by peppy** [comment]
It is intended that this would be implemented as previous.

**Comment by LittleEndu** [comment]
Just so the issue shows up when searching for it, it's called quick retry in game, not quick restart.
