### ISSUE TITLE
Taiko isn't playable in 2019.814.0

### ISSUE THREAD

**Issue by mackyclemen** [ppy/osu#5748]
This bug might be related to #5736 but decided to make another bug report instead.

**Describe the bug:** 
The taiko strip is black. You can't see the hit notes, but they're still... there. (see video)

**Screenshots or videos showing encountered issue:** 
video: https://youtu.be/ns86dFXp7vo
screenshot:
![Screenshot_20190818-043737](https://user-images.githubusercontent.com/17867386/63217182-43d65d80-c174-11e9-8181-232acff34df0.jpg)

**osu!lazer version:** 
2019.814.0 local release

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3512440/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3512441/runtime.log)

**Device specifications:**
OS: Android 8.0
Device: Samsung Galaxy S7 edge (SM-G930FD)

**Comment by smoogipoo** [comment]
This looks like a front-to-back related issue. Can you try enabling the "bypass front-to-back pass" checkbox at the bottom of options?

**Comment by mackyclemen** [comment]
Enabling the "bypass front-to-back pass" didn't work

**Comment by peppy** [comment]
Not sure what his one is, but as there have been no other reports I think it's safe to close. @mackyclemen would be appreciated if you can try a recent release and see if things are better for you now.
