### ISSUE TITLE
Being muted prevents usage of osu!direct & search in song select

### ISSUE THREAD

**Issue by tomdenty1** [ppy/osu#5749]

**Comment by iiSaLMaN** [comment]
Missing details. can you please provide a video on what your issue is, you can even describe in details how you produced this issue. also, can you attach the logs since they may be useful.

**Comment by tomdenty1** [comment]
Issue isn't something that i'd like to replicate since I would prefer not to be muted again.

In the limited time that I was muted, Trying to type into text feilds such as chat, osu!direct search and the song select search didn't do anything. 

Chat is understandable since it's a chat mute, but I'm assuming that preventing the use of direct and song search isn't intentionally done.

[How to reproduce]
>Get muted
>Try to type in search feilds

**Comment by peppy** [comment]
Works as expected here. Please reopen with a screenshot or video showing this breaking (plus `network.log`) if you can reproduce.
