### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#5751]
When opening osu!lazer, I find that I can't log in. I compiled it earlier, so now I don't have a computer to recompile it. What do I do at this point?

**Comment by iiSaLMaN** [comment]
What do you get when trying to log in, stuck an infinity loop of `Connecting...`? can you please attach the logs, you can find them in `%appdata%\osu\logs`

**Comment by X4X5** [comment]
I should have mentioned that I'm on Android.
