### ISSUE TITLE
Music playback bugs/improvements

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#5755]
I'm very happy this functionality was added to lazer (#5268)!
(and I'm referring to it saying keybindings)

Now, there are a few things I want to mention.
- osu intro (when you open osu) can be bugged if you switch song while the animation is playing (intro freezes)
- keybindings don't work in song select (using media keys)
- in song select, if you pause a track and change _**beatmap**_, music is not unpausing (it would be more intuitive if it did)

**Comment by peppy** [comment]
Please file one issue per issue.
