### ISSUE TITLE
Music playback keybindings not working in song select

### ISSUE THREAD

**Issue by ToIGLAK** [ppy/osu#5766]
(sorry #5755)
Music playback keybindings don't work in **song select** if you use **media keys**.
After I remapped those to different keys (F5, F6, F7) keybindings started working.

What is interesting is that music playback box says "no key bound" even if it is.
![image](https://user-images.githubusercontent.com/37531387/63237307-bc572000-c241-11e9-81d5-470c6c06b5ad.png)

**Comment by Game4all** [comment]
It is intentionnal for the now that the OSD displays "No Key Bound" as we have at the moment no way of telling which key combination was used to trigger the action (eg: changing / pausing track)
