### ISSUE TITLE
Make LegacySkin implementations per-ruleset

### ISSUE THREAD

**Issue by peppy** [ppy/osu#5786]
Currently it is not able to DI a DrawableHitObject and cast to a ruleset specific type, as `LegacySkin` is in the `osu.Game` project.

The proposal would be to have a method of making per-ruleset legacy skin implementations to work around this.

**Comment by peppy** [comment]
I've been trying to think of the best way to make this happen (it seems like we should try and get this right out of the box).

```csharp
class Ruleset
{
    virtual LegacySkin CreateLegacySkin() => null;
}
```

Potential implementations:
- SkinManager could receive the ruleset store and create an instance of each ruleset as startup.
- Player could register the active ruleset against SkinManager and the SkinManager would create prioritised skin source for only the active ruleset.

@smoogipoo thoughts?

**Comment by iiSaLMaN** [comment]
Keep in mind that LegacyBeatmapSkin inherits LegacySkin directly, we would need to rewrite that
