### ISSUE TITLE
mod selection category text overlaps with the mods and icons are at the wrong position?

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#5794]
**Screenshots or videos showing encountered issue:** 
latest build at the left side and osu!lazer 2019.814.0 at the right side
![osu_2019-08-21_12-11-47](https://user-images.githubusercontent.com/43358824/63424081-f117d280-c40d-11e9-995e-36424a886fd7.png)

**osu!lazer version:** latest build (self-compiled)

**Comment by iiSaLMaN** [comment]
Regressed in #5777

**Comment by iiSaLMaN** [comment]
Fixed in #5796
