### ISSUE TITLE
change scroll rate values in osu!mania to be a multiplier if it is BPM scale

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#5802]
i suggest that the scroll rate in osu!mania to change from a ms value to a multiplier on BPM scale because a ms value is inaccurate because the BPM also changes the scroll speed

**Comment by smoogipoo** [comment]
BPM scale hasn't been implemented yet. Do you actually use it?

**Comment by abraker95** [comment]
I am not sure what the benefit is in playing at BPM scroll speed tbh.
