### ISSUE TITLE
Can't install osu

### ISSUE THREAD

**Issue by reed-cat** [ppy/osu#5815]
**Describe the crash:** I can't install osu

**Screenshots or videos showing encountered issue:** 
![resim](https://user-images.githubusercontent.com/47327665/63588425-227bd400-c5af-11e9-8045-4f18ce3258f3.png)

**osu!lazer version:**

**Logs:** 

**Computer Specifications:** 
NVIDIA GEFORCE 920M
8GB RAM
INTEL I5200U
500GB HARD DISK

**Comment by dscnnctd** [comment]
Is this lazer you’re installing? If you’re installing stable, please do not make an issue here since this repo is for lazer only.
