### ISSUE TITLE
Game will freeze when playing beatmaps on iOS

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#5818]
****Describe** the crash:** 
Lazer ‪will randomly freeze when playing any beatmaps. music sometimes continues playing but touching the screen doesn’t do anything and a keyboard over usb-c won’t do anything either.‬
If it helps, the beatmap shown is [here](https://osu.ppy.sh/beatmapsets/122390#osu/313050)

**Screenshots or videos showing encountered issue:**
https://youtu.be/AVeO2ro9dqM
and
![C2CFCEC4-AC73-4DB0-83D7-0747045BED48](https://user-images.githubusercontent.com/10524728/63597105-ee39f080-c579-11e9-80d2-0fb90104f771.jpeg)

**osu!lazer version:** 
2018.823.0 (TestFlight)

**Logs:** 
Inaccessible on the iOS TestFlight build to my knowledge.

**Computer Specifications:** 
iPad Pro 11” 64GB

**Comment by dscnnctd** [comment]
Also happens even without storyboard on.
**Possibly related to:** 
https://github.com/ppy/osu-framework/issues/2773 **as if rendering freezes.**
This render freeze became way worse in this update, this never happened in the previous build of iOS as I know so far.

**Comment by peppy** [comment]
can you please switch back to the previous build and confirm beyond doubt that this is a new issue? you can do this from testflight.

**Comment by dscnnctd** [comment]
Tested on previous release **2019.813.1**, does not freeze on the same beatmap that I tested with on latest release. So this is pretty much new since this does not happen on the previous build.

**Comment by dscnnctd** [comment]
**Used beatmap:** 
https://osu.ppy.sh/beatmapsets/431697#osu/995533
**Device Specification:** iPhone 7 (iOS 13 Public Beta 7)

**Comment by ThatsNiceGuy** [comment]
Yep, this is a new issue. Tested using the previous build just like dscnnctd did and no issues occurred. No freeze either with or without storyboard enabled on the same map in my original post.
Tested on an iPhone XR and iPad Pro 11”. Both on iOS 13 public beta 7

**Comment by swoolcock** [comment]
I can’t reproduce this.  I’ll take a better look this evening if I can.

**Comment by ThatsNiceGuy** [comment]
[Here’s](https://youtu.be/Gw1HXQV0wr0) another video where this time the music keeps playing.
(this is on the latest build, just saying to avoid confusion)

**Comment by swoolcock** [comment]
Do you have an iOS 12 device you could test on to verify that it's not iOS 13 specific?  If you can show that iOS 13 is the likely culprit then I can find and update an iPad to test myself.

**Comment by ThatsNiceGuy** [comment]
>Do you have an iOS 12 device you could test on to verify that it's not iOS 13 specific?  If you can show that iOS 13 is the likely culprit then I can find and update an iPad to test myself.

@swoolcock yes I have another iPad I could test, it’s an iPad 6th gen running 12.4. Would that suffice?

**Comment by dscnnctd** [comment]
That’s good enough, I’ll be testing it also with my iPad Mini 2.

**Comment by swoolcock** [comment]
Any iOS 12 device should be enough.  I'm running the latest master on an iPad Pro and iPhone X with no problems, but I haven't updated to iOS 13 beta yet.

**Comment by ThatsNiceGuy** [comment]
Just got it to happen on the iPad 6 too, will try to get it on camera as it happens.

https://youtu.be/MpEtqlSRrgc
(iOS 12.3.1, lazer 2019.823.0)

**Comment by swoolcock** [comment]
Alright, thanks.  I’ll look into it this arvo.

**Comment by ThatsNiceGuy** [comment]
Okay here’s the best one, got it to happen while I was playing.
https://youtu.be/2awRGUVXqBY

Hope all this helps in some way. 
(iPad 6, iOS 12.3.1, lazer 2019.823.0)

**Comment by ContestedWheel** [comment]
This is pretty weird, do you have anything else besides a IPad 6 and IPad Pro? Or no? I'm gonna try to test this on my IPad Air 2, I let you know if I see anything specious.

**Comment by ThatsNiceGuy** [comment]
> This is pretty weird, do you have anything else besides a IPad 6 and IPad Pro? Or no? I'm gonna try to test this on my IPad Air 2, I let you know if I see anything specious.

I have an iPhone 6s Plus I can test but that’s basically the last ios device I have that can run lazer

**Comment by peppy** [comment]
On a guess, this is either related to some gl change we've made or a change in xamarin.ios. Quite likely the second.

@swoolcock the build server *is* building on latest xamarin preview, when i last checked.

**Comment by dscnnctd** [comment]
Can’t do tests on my iPad Mini 2 since performance got worse and keeps crashing in this release.

**Comment by ContestedWheel** [comment]
> I have an iPhone 6s Plus I can test but that’s basically the last ios device I have that can run lazer
Can you please test it on the iphone and send me a video?

**Comment by ThatsNiceGuy** [comment]
alright, ill be sure to do that tomorrow since its late

**Comment by RLukas2** [comment]
Well same to me too, using Iphone 6S+ with iOS 13 and Osu version lazer 2019.823.0

**Comment by swoolcock** [comment]
If one of you has macOS and Xcode, could you please get the device logs?  Even without symbols it may at least give us a starting point.

1) Load Xcode
2) Plug in device
3) Window > Devices and Simulators
4) Select your device
5) Click View Device Logs
6) Select the most recent crash for osu!
7) Copy paste the text on the right (or pastebin etc.)

**Comment by swoolcock** [comment]
I know what the springboard is. :) Worth a look anyway.

**Comment by peppy** [comment]
please only post here with actual useful logs or a solution. we are already aware of the fact it is crashing.

**Comment by smoogipoo** [comment]
I can replicate this on the testflight build but not a local build from master+framework master.

Mono Framework MDK
Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

Xamarin.iOS
Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

**Comment by peppy** [comment]
I've switched the build environment back to stable Xamarin.iOS for the next build. Let's see how that goes.

**Comment by peppy** [comment]
Can we get some confirmation that the latest build resolved this? It looks to be performing fine on my end.

**Comment by ThatsNiceGuy** [comment]
oof I’m the only only one replying but the game no longer freezes on iOS 13.1 or 12.4.1. Tested on an iPhone 7, 6s+, XR, iPad 2018, and pro 2018. I’d say you fixed it

**Comment by dscnnctd** [comment]
Confirmed, this issue no longer occurs on the latest testflight release.

**Comment by Crazyhamburgeer** [comment]
I can't add it :(
