### ISSUE TITLE
Discord overlay and non English letters

### ISSUE THREAD

**Issue by KoleckOLP** [ppy/osu#5819]
When I open Discord overlay over osu!lazer and try to type some non English letters I get the wrong letters. I use czech dvorak layout, but this issue was also happening with standard qwertz (czech layout).

When I tried to type čeština (whitch means Czech in czech) I got what you can see in the screenshot. This happens only in osu!lazer in other games and osu!stable everything work as it should.

![Snímek obrazovky (84)](https://user-images.githubusercontent.com/22729896/63603317-b9558a00-c5c9-11e9-9dd2-4771564839b1.png)

It's been an issue for a while now and still is in build 2019.823.0

I have no idea how to provide logs from osu!lazer sorry.

**Comment by peppy** [comment]
i'm not entirely sure this is our fault..

**Comment by bdach** [comment]
For what it's worth, the character switch issue seems to be the same as in #5827, except this time for the [Windows-1250](https://en.wikipedia.org/wiki/Windows-1250) code page (i.e. `č` = `0xE8` in cp1250 = `è` in Unicode), so if that gets fixed this might resolve itself too. Although it's a bit strange that an external overlay is picking up the same issue.

**Comment by Susko3** [comment]
Fixed with switch to SDL.
