### ISSUE TITLE
Ability to delete a single skin.

### ISSUE THREAD

**Issue by KoleckOLP** [ppy/osu#5820]
I'd like to remove one skin, and as far as I know there is only a way to delete all skins.

If we could simply right click a skin and delete it. Or placing cursor on a skin and hitting delete key. Or a delete current skin (would not be there for default skin or would be grayed out) button above delete all skins button. (the button makes it acceptable for osu!lazer on touch devices)

I don't really care how it would be implemented but if we can't do it trough folders please give us another way.

**Comment by peppy** [comment]
The full skin management UI is not quite ready yet. Of course this will be possible once it is.

**Comment by darkralts** [comment]
hey how do i delete all skins? i just need to get rid of this skin and change an element and reimport the osz

**Comment by bdach** [comment]
@darkralts use the settings overlay. it's right at the end, in "maintenance". there is also a search box there.

**Comment by Game4all** [comment]
As an aside, dragging in the modified .osk onto lazer window would just reimport the skin and works aswell.

**Comment by darkralts** [comment]
ah thank you very much both of you

**Comment by peppy** [comment]
Would have been nice to use the collection dropdown menu for this (to add an inline "remove" button) temporarily but it's a bit too hard-coupled with collections right now.

**Comment by developomp** [comment]
are there ways to manually delete them as of the moment?

**Comment by frenzibyte** [comment]
Nope, you will have to reset your entire game data in order to delete them, but skin editing is the current focus either way, so this feature may come sooner rather than later.

**Comment by peppy** [comment]
There's a "delete all skins" button. You do not need to "reset your entire game data".
