### ISSUE TITLE
Can’t sign in to my account 

### ISSUE THREAD

**Issue by fatgibby64** [ppy/osu#5825]
Won’t let me sign in just keeps connecting or stops

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
Recent
**Logs:**

**Comment by Ruoibeishi** [comment]
Make sure every character is being typed when you click the keyboard's key. There's some issues with some special characters. In my keyboard, for example, the numpad dot (.) only appears after I type another key ([example](https://s3.gifyu.com/images/GIF2b31e64a5d705ff50.gif)). Can you check it?

**Comment by fatgibby64** [comment]
It works now :) Thank you

**Comment by Game4all** [comment]
This issue can then be closed
