### ISSUE TITLE
Spinners too short are in-completeable

### ISSUE THREAD

**Issue by PoltixeTheDerg** [ppy/osu#5826]
**Describe the missing feature:** 
If a spinner is too short, it will not be able to be completed, making a map un-fcable, even with auto
an example of a map that has this issue is : https://osu.ppy.sh/beatmapsets/600897#osu/1269591
**Proposal designs of the feature:** 
in stable if a spinner is too short to complete the spinner will auto complete itself, it should do the same in lazer, if a spinner can't be completed normally it should just complete itself and give a 300

**Comment by iiSaLMaN** [comment]
Should we allow spinners like that at all? making the spinner auto-complete itself even if the autoplay didn't get the required spins seems hacky to me, although stable is different than lazer in terms of calculating required spins so I'm not sure if that's how stable does it

**Comment by peppy** [comment]
In stable we automatically complete spinners that can't be completed otherwise. We should reproduce this behaviour in lazer for compatibility.
