### ISSUE TITLE
Keyboard does not work on Android

### ISSUE THREAD

**Issue by Drison64** [ppy/osu#5828]
When you try to login or type anywhere, you can't.

**Comment by nathannino** [comment]
If you are using gboard, it's probably a duplicate of #5571
(Also, I believe that gboard is the default keyboard for android)

**Comment by dscnnctd** [comment]
You’re missing details. Please provide more info like a video for example.

**Comment by dscnnctd** [comment]
And I’m also unsure if you’re using the built-in keyboard for Android or a bluetooth/wired one.

**Comment by Drison64** [comment]
Sorry for not including details.

Here is a video, https://youtu.be/I_CY6i4XJss

(Just uploaded)

**Comment by dscnnctd** [comment]
>Sorry for not including details. ...

It looks like that needs a framework fix I believe.

**Comment by Game4all** [comment]
Issue should be reopened on framework side as it affects all android users using Gboard as their IME

**Comment by Drison64** [comment]
> @Drison64 please close this issue.

Closing issue.
