### ISSUE TITLE
Make skin select menu like key configuration menu

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#5831]
**Describe the new feature:** 
A better skin select UI as per in the proposal design below.

Kinda the same concept as the key config.

**Proposal designs of the feature:** 
![osu skin picker](https://user-images.githubusercontent.com/50823728/63687537-3857f600-c848-11e9-9590-6cebd9d81e9a.png)

**Comment by EVAST9919** [comment]
UI looks cool, but looks like it will be implemented in another way.
https://github.com/ppy/osu/issues/5820#issuecomment-524520655

**Comment by peppy** [comment]
Thanks for the suggestion but we already have a design direction for this!
