### ISSUE TITLE
shortcut to enable/disable autoplay is missing in osu!lazer

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#5839]
**Describe the missing feature:** 
you can enable/disable autoplay in osu!stable by pressing ctrl+a in the song selection menu but in osu!lazer you cant

**Proposal designs of the feature:** 
add a shortcut to enable/disable autoplay by pressing ctrl+a in the song selection menu

**Comment by EVAST9919** [comment]
You can press Ctrl+Enter to do that. If you want to - go to settings and change key bindings to Ctrl+A

**Comment by mouzedrift** [comment]
i cant find a setting for that, am i blind?

**Comment by mouzedrift** [comment]
nvm i found it but i still think ctrl+a should be included to match stable

**Comment by peppy** [comment]
i'm not sure whether we should add ctrl-a back (as it conflicts with text selection).

**Comment by mouzedrift** [comment]
closing because it conflicts with text selection (i didnt know that this was possible in the selection menu)
