### ISSUE TITLE
Long usernames overflow on multiplayer chat

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#5843]
**Describe the bug:** Long usernames overflow into timestamps on multiplayer chats.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/19843905/63715397-faf16980-c843-11e9-963c-bc9db083adfd.png)

**osu!lazer version:** 2019.823.0

**Logs:** not needed

**Comment by EVAST9919** [comment]
Duplicate of https://github.com/ppy/osu/issues/2819
