### ISSUE TITLE
osu!lazer launches from installer, never from shortcut

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#5851]
**Describe the bug:** 
From launching the shortcut from in the Start Menu or Desktop, osu!lazer does nothing, even after a complete reinstall. But when launching it through the installer after reinstalling osu!lazer it works fine.
**Screenshots or videos showing encountered issue:** 
No need
**osu!lazer version:** 
All of them
**Logs:** 
No need

**Comment by peppy** [comment]
Need logs or event log or something.

**Comment by Hubza** [comment]
I can't find any logs, it seems, sadly.

**Comment by Hubza** [comment]
It boots from the `AppData\Local\osulazer\app-2019.823.0` folder but not the osu!.exe in `AppData\Local\osulazer`, neither the shortcut

**Comment by peppy** [comment]
We can't do anything without logs. Please check Event Viewer.

**Comment by Hubza** [comment]
Nothing in Event Viewer from what i can see.

**Comment by Hubza** [comment]
Got it, upon osu!lazer install the osu!.exe was for some reason being tagged with running as "Compatibility Mode" with Windows 8, every time. 
![image](https://user-images.githubusercontent.com/33783503/63749091-93b6d200-c8a2-11e9-819e-94008e60c4b2.png)
