### ISSUE TITLE
Skin samples are not read correctly

### ISSUE THREAD

**Issue by gloomy-ghost** [ppy/osu#5854]
regressed by 62641c149d96d33ec56542764b3d2a8ddd7258cb

cf. #5723 needs changing options but this one doesn't. This regression happened after #5723 is filed.

**Comment by peppy** [comment]
Please explain the issue better. What is overridden by what?

**Comment by gloomy-ghost** [comment]
emm, the hitsound of a skin selected by the user is overridden by the hitsound from the default osu!lazer skin. I tested 2 skins and both lost their hitsound after 62641c1

**Comment by peppy** [comment]
Thanks, figured it ou.
