### ISSUE TITLE
Replay bug on mobile

### ISSUE THREAD

**Issue by RLukas2** [ppy/osu#5859]
When you're watching replay, you're able to move to certain spot of the map but if you using it too fast, it'll be glitch (or out of sync)
(Ver Lazer 2019.823.0)

Video: https://youtu.be/oJ0FyC7ICEc

![image](https://user-images.githubusercontent.com/44022992/63781523-12982300-c914-11e9-8cae-b8f2b0111912.png)

**Comment by iiSaLMaN** [comment]
This is not a mobile issue or even a bug, the playfield catches up with the gameplay, but i think it's a placeholder and won't stay like that
