### ISSUE TITLE
Song select footer shouldn't be transparent

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5861]
**Describe the bug:** bar on down of the song select should become darker/less transparent when mod selector is on screen

**Screenshots or videos showing encountered issue:**
![osu_2019-08-27_20-13-35](https://user-images.githubusercontent.com/32620809/63798645-c98fa100-c90a-11e9-9301-da01be2e8145.jpg)
 

**osu!lazer version:** latest

**Comment by iiSaLMaN** [comment]
I think matching the bottom colour of the mod select overlay (purple-ish) to the bottom toolbar would look better imo

**Comment by peppy** [comment]
This is already resolved in a future design revision.

**Comment by Joehuu** [comment]
Closing as this doesn't require tracking because the figma designs are already public (no more transparency in the new design).
