### ISSUE TITLE
The circles in every level are the same size instead of varied by design

### ISSUE THREAD

**Issue by cooldude101** [ppy/osu#5864]
**Describe the new feature:** 
Currently, all levels that are imported from the original osu have huge circles when some levels are supposed to have much smaller circles, this makes it difficult for mouse players to adapt as there's a larger travel distance than what we're used to, so this leads to constant deaths. Please change this.
**Proposal designs of the feature:** 
Make circles size dependent on the design of the original level

**Comment by peppy** [comment]
Could you please provide more details? Circle size is implemented in lazer, so if you're seeing this, it may be specific to a subset of beatmaps

**Comment by Volnetiks** [comment]
I've seen someone who said that circles sizes werent defined by doubles values but by int, maybe it would explain this?

**Comment by Volnetiks** [comment]
Just checked, circles size are different, i tried on 5 beatmaps, imported from the original osu

**Comment by TPGPL** [comment]
could you please link the mapset instead?

**Comment by mouzedrift** [comment]
> could you please link the mapset instead?

https://osu.ppy.sh/beatmapsets/186318#osu/459845 

he used the last difficulty

**Comment by TPGPL** [comment]
it's because of the skin, not because of the game

![image](https://user-images.githubusercontent.com/19843905/63897096-519da580-c9f4-11e9-864f-dc931741820d.png)

you can see here that the circles are of the exact same size on the same skin, on both clients

**Comment by cooldude101** [comment]
> it's because of the skin, not because of the game
> 
> ![image](https://user-images.githubusercontent.com/19843905/63897096-519da580-c9f4-11e9-864f-dc931741820d.png)
> 
> you can see here that the circles are of the exact same size on the same skin, on both clients

i see, thank you!

**Comment by peppy** [comment]
i don't understand. why is it "because of the skin"?

**Comment by Fatal3ty** [comment]
I overlapped the image with Skin and default Skin, edited with paint.net. Default Skin is Circle Size bigger than with skin.
![size error](https://user-images.githubusercontent.com/53025167/64052460-d4eb0280-cb7e-11e9-97c2-e8b5d1f947bd.png)

**Comment by peppy** [comment]
if you mean lazer default, this is intentional. it now matches the hit area 1:1

**Comment by Fatal3ty** [comment]
> if you mean lazer default, this is intentional. it now matches the hit area 1:1
I mean, when i use a some skins -> that is smaller than the lazer default skin. (Slider and Circle, see Screenshot)
![osu_2019-08-31_21-25-16](https://user-images.githubusercontent.com/53025167/64068266-11c60080-cc36-11e9-8a44-1a7390879733.png)
![osu_2019-08-31_21-24-45](https://user-images.githubusercontent.com/53025167/64068268-14c0f100-cc36-11e9-9133-8bb58c585484.png)

See 2 Screenshot, you see Lazer Default is bigger than all custom skins. Is hard to play when Size aren't the same. And why is my sliderb blue now (is not a tinted), normal are white.

Osu!Stable have a default Skin and with Skin same size.

Version: 2019.831.0
