### ISSUE TITLE
Triangles intro freezes with no audio device available

### ISSUE THREAD

**Issue by notpushkin** [ppy/osu#5866]
**Describe the bug:** 

Builds successfully, but only black screen with the “osu!lazer development build” bar on the bottom is shown. Additional controls are shown on resizing window (resolution), pressing alt+enter (screen mode name) or scrolling (volume controls). No music is playing, so I think it's unrelated to #4068 or #5199 (and other similar issues).

**Screenshots or videos showing encountered issue:**

<details>
<summary>Click to open</summary>

![black screen](https://user-images.githubusercontent.com/1298948/63850312-6c443000-c99c-11e9-982a-811214db1667.png)

![resizing](https://user-images.githubusercontent.com/1298948/63850304-68181280-c99c-11e9-92d3-94cccc00f329.png)

![changing mode](https://user-images.githubusercontent.com/1298948/63850321-72d2a780-c99c-11e9-9de0-9968a9f9f64b.png)

![changing volume](https://user-images.githubusercontent.com/1298948/63850510-e4aaf100-c99c-11e9-999d-d0118df641bd.png)

(Debug build behaves the same way)

</details>

**osu!lazer version:** 2019.823.0

I have tried both Debug and Release builds:

```
LD_LIBRARY_PATH="$(pwd)/osu.Desktop/bin/Release/netcoreapp2.2" dotnet run --project osu.Desktop -c Release
LD_LIBRARY_PATH="$(pwd)/osu.Desktop/bin/Debug/netcoreapp2.2" dotnet run --project osu.Desktop
```

**Logs:** 

Release:
[database.log](https://github.com/ppy/osu/files/3550502/database.log)
[performance.log](https://github.com/ppy/osu/files/3550503/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3550504/runtime.log)

Debug:
[database.log](https://github.com/ppy/osu/files/3550522/database.log)
[performance.log](https://github.com/ppy/osu/files/3550523/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3550524/runtime.log)

**Comment by peppy** [comment]
I'd say there is likely an issue with audio playback on your system.

**Comment by notpushkin** [comment]
@peppy Probably it is: I've tried an older build, namely 2019.530.0, and it runs fine, but I've had to change the sound device in settings before sound appeared. 

I still think the game should load at least to the main menu in this kind of “buggy” environments (so the user can do some basic troubleshooting like I did :)

**Comment by Game4all** [comment]
Having a black screen on launch of newer builds is likely due to the new triangles intro sequence relying on the audio track (#5789 should resolve this).

Try changing the `IntroSequence` value to `Circles` in the `game.ini` config file of lazer and try launching again. You should be able to reach main menu.

**Comment by Chronomly** [comment]
I'm having this issue as well on Fedora 30

> Having a black screen on launch of newer builds is likely due to the new triangles intro sequence relying on the audio track (#5789 should resolve this).
> 
> Try changing the `IntroSequence` value to `Circles` in the `game.ini` config file of lazer and try launching again. You should be able to reach main menu.

Doing this does fixes video but there is still no audio

**Comment by Game4all** [comment]
Audio issue has probably to do with BASS itself

**Comment by peppy** [comment]
See https://github.com/ppy/osu/issues/1302

**Comment by bdach** [comment]
Expanding this in scope to make this issue a catch-all for freezes with the triangles intro, as this can happen on any platform given no audio device is picked up by BASS.

**Comment by notpushkin** [comment]
:heart:
