### ISSUE TITLE
problems with osu lazer DdataBase

### ISSUE THREAD

**Issue by Methosss** [ppy/osu#5870]
**Describe the bug:** 
osu lazer datata base is unstable, and can't handle 8k beatmaps (8196) after update db crashes and in effect i was lost acces to sesttings osu direct editor etc, in play mode i was had only back button. why its encrypted like this: folders a,b,c,d,e,f,g,h 1,2,3,4,5,6,7,8 etc. that's weird and normal f5 to load /reload beatmaps is impossible.
**Screenshots or videos showing encountered issue:** 
i don't have i was deleted .db files and now im importing beatmaps
**osu!lazer version:** 
 after update to app-2019.823.0
**Logs:** 
i don't have ;/

**Comment by peppy** [comment]
Please provide logs or a database file. There is absolutely nothing to go off in this report.

**Comment by Methosss** [comment]
i fucked up, i don't have
so... for next time  i'm first make screenshots and copy logs before trying fix bug. issue to close ;/

nice new intro btw. you can delet mesages on #arrival if there's any possibility plese verify me on discord
