### ISSUE TITLE
Approach circle ends in centre of circle

### ISSUE THREAD

**Issue by paps416** [ppy/osu#5873]
**Describe the bug:** 
When i tested some skins that i loaded in osu!lazer i find that in one skin approach circle ends in centre of circle.i don't know if that problem of osu!lazer or that skin but yeah

**Screenshots or videos showing encountered issue:** 
https://youtu.be/WZbSNOmojCg
sorry for 30 fps video ><

**osu!lazer version:** 
2019.828.0

**Comment by peppy** [comment]
This happens on skins where the approach circle is mis-sized. We will eventually figure a way to support them.

**Comment by Joehuu** [comment]
Duplicate of #2358.
