### ISSUE TITLE
The OSU icon in the lower right corner will be mistakenly touched

### ISSUE THREAD

**Issue by LamGC** [ppy/osu#5874]
**Describe the bug:** 
Trigger environment: Windows 10 1903
When the OSU window is near the Windows Notification Center button in the lower right corner (Figure 1), the OSU icon will also be triggered when the Notification Center button outside the window is clicked.
PS: This happens only when the window is focused.
![Figure 1](https://user-images.githubusercontent.com/16975255/63883987-eeb60980-ca07-11e9-9381-66862d6ae476.png)

**Screenshots or videos showing encountered issue:** 
https://1drv.ms/v/s!AuZ8JMPu3cmekhQACVghx7Vghu7w
(Notice the lower right corner of the video)

**osu!lazer version:** 
commit 67151afa9a33529282bfaf70ad0dfd88a4411041

**Logs:** 
(There is no log associated with this issue.)

**Comment by Gabixel** [comment]
This happened to me too, I can confirm that this happens with some of the Windows' UI button (like Cortana, Search, Notification Center and similar). Also, this doesn't happen with `Raw Input` enabled.

**Comment by LamGC** [comment]
Testing between opening Raw Input and disabling Raw Input found that the OSU icon was triggered before defocusing when Raw Input was not opened.
In other words, during Raw Input disabled, a click notification center will also have a click event in the OSU window (the wrong click event will cause the settings menu to be closed when it opens)
