### ISSUE TITLE
Circles/sliders fade in later compared to the old client

### ISSUE THREAD

**Issue by PizzaLovers007** [ppy/osu#5877]
**Describe the bug:** 
The approach and hit circles in osu!lazer tend to fade in slower compared to the old client. This definitely affects gameplay at higher approach rates since the player is given less time to react. I've included a video of what it looks like at AR9 and at AR10. Footage was recorded at 60fps.

Normal hit circles fade in approximately the same on both clients. However, slider hit circles fade in slower than normal hit circles (~4 frame difference).

Both the normal and slider approach circles fade in slower compared to the old client. The normal approach circle has a ~4 frame difference, but the slider approach circle is much more noticeable at an ~8 frames difference.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/z-0gw2ZjiBU

**osu!lazer version:** 
2019.828.0

**Logs:**

**Comment by peppy** [comment]
Are you 101% sure you are one 2019.828.0? This should be fixed by #5865.

**Comment by PizzaLovers007** [comment]
Oh everything looks right now. I must have updated right after recording or something. Thanks!
