### ISSUE TITLE
Not Responsive on ChromeOS

### ISSUE THREAD

**Issue by ReclusionsHD** [ppy/osu#5882]
I have put an effort into trying to make osu!lazer work on ChromeOS (which is a Linux-kernel based Operating System), but all I get is a black screen. Approx. 20 seconds later, it crashes. If you want, you can crash it by switching to another app and going back.

I self-compiled the .apk file, and installed it just like any Android device.

![screenshot 1](https://user-images.githubusercontent.com/54677067/63952039-70c42380-ca44-11e9-9fc0-2d6436b13188.jpg)

**osu!lazer version:** 
2019.828.0

**Computer Specifications:** 
Lenovo N23 Chromebook 
CPU: Intel® Celeron® N3060

**Comment by ReclusionsHD** [comment]
Forgot to add, nothing is responsive. You can't control the volume, you can't hear anything, all you can do is look at the black screen. Triangles won't even play.

**Comment by aspriddell** [comment]
There have been all sorts of issues with android gameplay so I wouldn't worry - it'll probably get fixed soon. If you can, I would suggest getting some logs (if you can find any) and posting them here. Also bear in mind that ChromeOS _is_ linux based but isn't the same as android, so you may want to look at trying to build a linux one copy use Crostini (an experimental ChromeOS feature) that supposedly allows running linux apps. Who knows? that may even work

If you need to know how to enable it (Crostini), search `how to install linux apps on chromebook` into search and choose one.

**Comment by peppy** [comment]
Unless you can debug yourself, this is not so useful. Please provide logs or debug and provide some kind of information that can help us (reopen if you manage this).
