### ISSUE TITLE
Hit Samples do not stop playing when exiting the beatmap

### ISSUE THREAD

**Issue by Shaehl** [ppy/osu#5884]
**Describe the bug:** 
When i resume the game, then additional game will continue playing.

**Screenshots or videos showing encountered issue:** 
https://www.dropbox.com/s/y8i8ro5f43ya12p/2019-08-29%2020-56-29.mp4?dl=0 (mp3 update into mp4)

**osu!lazer version:** 
2019.828.0

**Logs:** 
no need.

**Comment by iiSaLMaN** [comment]
Samples (i think) do not stop from playing when exiting the game which causes long like these stay playing, this title can be renamed to "Hit Samples do not stop playing when exiting the beatmap"

**Comment by Shaehl** [comment]
> 
> 
> Samples (i think) do not stop from playing when exiting the beatmap which causes long samples like these stay playing, this title can be renamed to "Hit Samples do not stop playing when exiting the beatmap"

ok

**Comment by MikelJohnson** [comment]
Actually it also affects storyboard sounds ([for example](https://osu.ppy.sh/beatmapsets/1011011#osu/2116202)), so really it's a problem with all audio samples.

**Comment by iiSaLMaN** [comment]
@MikelJohnson "Storyboard sounds" are also samples, so nothing new.
