### ISSUE TITLE
Text characters have a black background

### ISSUE THREAD

**Issue by LobinhoFofinhu** [ppy/osu#5885]
**Describe the bug:when I open osu leisurely I come across some black squares I think it's a graphical bug I already tried to restart osu leisure but the black squares are still the same
** 

**Screenshots or videos showing encountered issue:** 
![IMG_20190829_220409485_HDR](https://user-images.githubusercontent.com/54693187/63986143-101b0200-caa9-11e9-9c7b-7db8fc3c28f8.jpg)
![IMG_20190829_220342303_HDR](https://user-images.githubusercontent.com/54693187/63986144-10b39880-caa9-11e9-8b8a-1cfdfd058892.jpg)

**osu!lazer version:2019.828.0** 

**Logs:**

**Comment by iiSaLMaN** [comment]
Can you provide us with your hardware info, such as the CPU, GPU, etc..

**Comment by Altenhh** [comment]
could be related to #5199 (although much more extreme than this)

**Comment by iiSaLMaN** [comment]
> could be related to #5199 (although much more extreme than this)

Probably because the glyphs in the new text builder use the same shaders as the ones that cause graphics glitches in some way, but I'm not quite sure how it worked with old text sprites.

**Comment by iiSaLMaN** [comment]
Regressed in ppy/osu-framework#2765

**Comment by smoogipoo** [comment]
Is it fixed by changing all those newly added lines to `highp` instead of `lowp`?

**Comment by iiSaLMaN** [comment]
> Is it fixed by changing all those newly added lines to `highp` instead of `lowp`?

Nope.
