### ISSUE TITLE
allow ability to choose a skin for each gamemode seperate from other gamemode

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#5890]
the idea is to be able to use a certain skin for a gamemode and have a different skin for another gamemode without having to change the skin itself

my suggestion is to have osu!lazer sort the skin into 5 parts, 1 for each gamemode and 1 for general gameplay

you can then choose the part of the skin for the gamemode that you like

**Comment by peppy** [comment]
There is an ongoing refactor of skinning which will address this (vaguely covered by https://github.com/ppy/osu/issues/4924).
