### ISSUE TITLE
"installation has failed" trying to download osu lazer

### ISSUE THREAD

**Issue by bl1tzAndrew** [ppy/osu#5891]
i believe it is trying to download in the discord folder. Does anyone know the fix for this
![yoimapirate](https://user-images.githubusercontent.com/54649729/63994895-2033e100-caab-11e9-9504-a4afb9030d1d.PNG)

its the latest osu lazer version

**Comment by dscnnctd** [comment]
Are you using 32-bit Windows?

**Comment by dscnnctd** [comment]
If yes, osu!lazer is not yet supported on 32-bit operating systems. Please see #3984 for more details. This issue can then be closed.

**Comment by aspriddell** [comment]
@bl1tzAndrew Have you tried looking at the setup logs? They'll probably tell you what is going on and somebody can give you pointers on how to fix it.

**Comment by bl1tzAndrew** [comment]
im running 64 bit windows, i have the setup logs, i just need to know what to show.

**Comment by ThatsNiceGuy** [comment]
can you send the setup logs so we can see where and how it failed?

**Comment by bl1tzAndrew** [comment]
![savemepls](https://user-images.githubusercontent.com/54649729/64052083-16a18c00-cb32-11e9-9973-b7e6fe143ad1.PNG)
this is the first part of the setup log. Pls tell me what i need to do from here.

**Comment by iiSaLMaN** [comment]
just attach the entire file here.

**Comment by bl1tzAndrew** [comment]
what do you mean by this?

**Comment by ThatsNiceGuy** [comment]
by that we mean to attach the entire log file (likely in .txt or .log format)

**Comment by bl1tzAndrew** [comment]
oh ok

**Comment by ThatsNiceGuy** [comment]
Save the “SquirrelSetup” log file somewhere and then from there upload the entire thing here

**Comment by bl1tzAndrew** [comment]
[SquirrelSetup.log](https://github.com/ppy/osu/files/3561615/SquirrelSetup.log)

**Comment by bl1tzAndrew** [comment]
think i did it

**Comment by dscnnctd** [comment]
>think i did it ...

Yep, that should do.

**Comment by bl1tzAndrew** [comment]
now what to do?

**Comment by iiSaLMaN** [comment]
you can rest now and let us investigate the problem.

**Comment by bl1tzAndrew** [comment]
thanks so much!

**Comment by ThatsNiceGuy** [comment]
Isolated the log to just be for lazer, here it is. Some lines I do see that could be interesting are these:
[Log.zip](https://github.com/ppy/osu/files/3561658/Log.zip)
(Sorry for it being compressed, on ipad and iOS file manipulation isn’t so robust yet)

**Comment by bl1tzAndrew** [comment]
so what do i do now?

**Comment by ThatsNiceGuy** [comment]
you can chill, I posted that for other collaborators to take a look at. It’s the same file you posted but I took out everything that had to do with discord as that isn’t relevant to this issue.

**Comment by bl1tzAndrew** [comment]
ok thanks. Ill be here

**Comment by bl1tzAndrew** [comment]
any news i can use?

**Comment by bl1tzAndrew** [comment]
any updates?

**Comment by Joehuu** [comment]
We didn't have any installation issues (related to squirrel) opened for months, apart from post-installation problems with incompatible hardware or just software prereqs not being downloaded. Windows 10 should run it right out of the box if updated regularly.

Will close and unlock. @bl1tzAndrew if you are still here and still have problems, please leave a comment if you want this reopened.
