### ISSUE TITLE
input not supported

### ISSUE THREAD

**Issue by Dragibuly** [ppy/osu#5898]
**Describe the bug:** 
When i lauch Osu!lazer, a black screen with a pop up "Imput NOT Supported" appears. I can't do anything, and I don't know how to fix screen resolution in file explorer

**osu!lazer version:** 
2019.828.0

**Comment by aspriddell** [comment]
Have you tried the latest version? Yours is slightly outdated (Latest as of this comment is `2019.830.0`)
Also, what OS are you on and what devices are you using?

**Comment by iiSaLMaN** [comment]
Telling what you see only wouldn't help enough, can you provide us with your hardware info, your running OS, also attach the logs, they may help.

**Comment by Dragibuly** [comment]
I've try the new release in a Windows 10 64 Bit OS, and when I put my game in 800x600 resolution, and the pop up "Input NOT Supported". So, I can't rechange the resolution.

**Comment by peppy** [comment]
Could you please tell us the display modes your monitor supports? Also could you check your monitor's on screen display to see if you can find out the requested mode from lazer?

**Comment by peppy** [comment]
Closing as abandoned. Also likely resolved via SDL.
