### ISSUE TITLE
Settings and Notifications Overlays have different focus with Music Player

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5901]
**Describe the bug:** The `Settings` Overlay steals the focus of the Music Player, but the `Notifications` Overlay doesn't. So I guess the correct one is the `Notifications` Overlay (or is intentional that they have a different focus?).

**Screenshots or videos showing encountered issue:** https://streamable.com/1ao1d

**osu!lazer version:** 2019.830.0

**Comment by peppy** [comment]
I believe this is actually correct at the moment (settings is the most important overlay in the game). It's just a bit confusing because we don't have multi-level overlay dim implemented yet.
