### ISSUE TITLE
Beatmap skins colors do not work

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5903]
**Describe the bug:** 
Beatmap skins colors stopped working. Default colors are being forced on all maps.  
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/20248967/64048519-606a9080-cb8b-11e9-824a-1f963a2c67ac.png)

**osu!lazer version:** 
2019.830.0

**Comment by dscnnctd** [comment]
lazer skin is also affected by this.

**Comment by peppy** [comment]
Is it safe to assume this is being reported as a regression?

**Comment by dscnnctd** [comment]
Yes, this is possibly a regression.

**Comment by Fatal3ty** [comment]
Same problem with skin combo colors (i don't use map skin). Don't worked, is default.

**Comment by iiSaLMaN** [comment]
Regressed in #5833

**Comment by l3lackShark** [comment]
Fixed in 2019.831.0

**Comment by dscnnctd** [comment]
Fixed in #5911. Yes I was about to say that too.
