### ISSUE TITLE
Add date tooltip to scores

### ISSUE THREAD

**Issue by AriizuCA** [ppy/osu#5906]
**Describe the new feature:**
When you put your cursor over a score in the live client, you can see when a score was set as well as the number of 300's, 100's, 50's, misses, accuracy, and mods enabled.  I do not believe the accuracy and the mods are necessary but having the date the scores were set as well as the 300's, 100's, 50's, and misses would make sense to have when hovering scores in lazer.

**Proposal designs of the feature:**
[Suggestion](https://i.imgur.com/Bv4YcLA.png)
I find myself constantly looking at previous scores that I've set, whether that be looking specifically at 50's and misses or the date that I set the score on to see improvement and compare on the fly.  Preferably, I like the "Or" design since it has most of the features are are currently live already minus the ones that show up visually as default.

**Comment by peppy** [comment]
There's an actual design for these tooltips (score cards). @arflyte can you share it please?

**Comment by arflyte** [comment]
![Figma_190902-132323](https://user-images.githubusercontent.com/3632750/64090188-e69df700-cd84-11e9-9ef0-50df76309fe6.png)
Draft design. Hover card will show more details available from Performance Page.

**Comment by Game4all** [comment]
What do represent the progress bar at the top of the scorecard (maximum achievable score)?. Same thing for the vertical graph at the end

**Comment by smoogipoo** [comment]
@arflyte Got a figma link? It's easier to get exact font sizes and stuff that way.

**Comment by arflyte** [comment]
@smoogipoo the design is still very drafty. it's far from done, I need to work on the user card first before moving on to it's expanded modes :(

**Comment by peppy** [comment]
@arflyte note that it's missing theone thing requested here (date achieved).

**Comment by dekrain** [comment]
I haven't noticed that there was design prepared already, but I implemented a small tooltip window. Maybe it can suffice for the time being until the proper design gets done?

![obraz](https://user-images.githubusercontent.com/19158291/151916572-722d42dc-328d-4bef-a2f6-8989fd5da62d.png)

**Comment by peppy** [comment]
Looks great, apart from the alignment of the mod settings (should be centered next to the mod icon)

Make sure the mods wrap correctly too.

**Comment by dekrain** [comment]
Ok, I will submit a PR soon.

**Comment by dekrain** [comment]
> Make sure the mods wrap correctly too.

What exactly do you mean by that?

**Comment by peppy** [comment]
Just submit what you have and we'll take it from there. Hard to say whether it will be merged, based on code quality (since you've not followed the provided designs, I don't want to spend a huge amount of effort getting it in a usable state if it's not up to scratch).

**Comment by frenzibyte** [comment]
Closing as implemented by #16726.
