### ISSUE TITLE
osu!lazer crash in the song select menu after filtering all beatmaps by difficulty (?) im not sure if that was the cause

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#5907]
**Describe the crash:** 
i just started osu!lazer, went into the song selection screen and filtered all maps by difficulty and then it suddenly crashed. i dont know if it actually crashed because i filtered the maps or not

**osu!lazer version:** 
2019.830.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3561665/database.log)
[network.log](https://github.com/ppy/osu/files/3561666/network.log)
[performance.log](https://github.com/ppy/osu/files/3561667/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3561668/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3561669/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3561670/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3561671/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3561672/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3561673/updater.log)

**Computer Specifications:** 
- **CPU:** i5-4440
- **iGPU:** intel hd graphics 4600
- **RAM:** 8GB DDR3

**Comment by iiSaLMaN** [comment]
the `runtime` log seems to be empty, did you restart the game? if so, please reproduce it and attach the logs again, also can you explain in detail how you produced this?

**Comment by mouzedrift** [comment]
> the `runtime` log seems to be empty, did you restart the game? if so, please reproduce it and attach the logs again, also can you explain in detail how you produced this?

i didnt restart the game and i cant reproduce it either.

> can you explain in detail how you produced this?

i just started the game and went to the song selection menu and selected the difficulty filter for both sides and it crashed

**Comment by peppy** [comment]
Can't reproduce. Please re-open if you catch the actual crash stack trace in a log.
