### ISSUE TITLE
Hit arrow estimation exceeds Hit error height

### ISSUE THREAD

**Issue by Altenhh** [ppy/osu#5912]
As explained from the title, the Hit Arrow Estimation exceeds the Hit Error height.

![image](https://cdn.discordapp.com/attachments/188630652340404224/617205117690576938/unknown.png)

In order to reproduce this, hit atleast 5-10 objects late/early and you will see the arrow go above/below the Hit error height

**Comment by peppy** [comment]
Could you please include details of the beatmap (does it happen on all beatmaps?) and possibly a video showing this? Is your UI scale set to a non-default or anything else weird?

**Comment by Altenhh** [comment]
this will happen on any beatmaps. but i think this mainly happens on only taiko (although i could be completely wrong on this).
###### (sorry for my poor performance on the other gamemodes)

https://videobin.org/+1245/17us.html

**Comment by peppy** [comment]
Can you include the timestamps of when it happens in the video? I think this may be related to certain ruleset judgements having incorrectly populated judgement offsets.

**Comment by Altenhh** [comment]
0:25 @1x, 1:13 @1.6x

**Comment by phosphene47** [comment]
I can also reproduce this with a spinner in Taiko.

https://streamable.com/jq7i9
