### ISSUE TITLE
Broken taskbar pinned shortcuts after each update

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#5917]
**Describe the bug:**

Pinned shortcuts in the taskbar break after each update.
I guess this is related to Squirrel, but this does not happen with Discord which also uses Squirrel.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/27663662/64063457-cdd3fb00-cc37-11e9-88dd-412aa520d923.png)

Ignore the leftmost icon which is osu! stable.

**osu!lazer version:** 2019.830.0

**Logs:** 

[updater.log](https://github.com/ppy/osu/files/3562405/updater.log)

**Comment by phosphene47** [comment]
Forgot PC specs:
![image](https://user-images.githubusercontent.com/27663662/64064081-a9c8e780-cc40-11e9-8c93-b2d2f15d351c.png)

Also, the shortcut still works but clicking on it spawns another icon like https://streamable.com/wnigu which is pretty unsettling.

**Comment by peppy** [comment]
This doesn't seem to happen for me. Could you try unpinning your existing shortcut, starting the app, then repinning?

**Comment by phosphene47** [comment]
Did not fix. In fact, I managed to get two osu!lazer icons in my taskbar this time.

The first icon's tooltip says `osu!lazer` and the second says `osu!`.
![image](https://user-images.githubusercontent.com/27663662/64095097-31c60300-cda1-11e9-89a6-43a323ba67fb.png) ![image](https://user-images.githubusercontent.com/27663662/64095224-8e292280-cda1-11e9-912f-6264719d9343.png)

Video: https://streamable.com/90ixj

`osu!lazer` icon was created in Windows search using 'Pin to taskbar' button. It links to `%LocalAppData%\osulazer\osu!.exe`. However the instance that spawns when I click that icon is the second `osu!` which links to `%LocalAppData%\osulazer\app-2019.831.0\osu!.exe`. I assume these are different programs because their sizes are different: 283kb and 228kb.

**Comment by peppy** [comment]
Try keeping just the second one going forawrd

**Comment by phosphene47** [comment]
> Try keeping just the second one going forward

I'll do that for now, but that shortcut will probably break with every update.

**Comment by peppy** [comment]
As I've said, it has worked for me (just as vscode does) for over a year of releases.

Closing for now - please reopen if it breaks again.
