### ISSUE TITLE
osu! logo should continue beating when the track is stopped

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#5919]
**Describe the bug:**

osu! log does not continue to beat when the track is stopped, which is in contrast to stable behavior.

**Screenshots or videos showing encountered issue:** 

Stable: https://streamable.com/pknbh
Lazer: https://streamable.com/bmzzc

**osu!lazer version:** 2019.830.0

**Logs:** irrelevant

**Comment by peppy** [comment]
If someone looks at this, it should fall back to a 60bpm beat.
