### ISSUE TITLE
osu taiko beatmap freezes the client at the beginning of the map for a few seconds and continues then

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#5933]
**Screenshots or videos showing encountered issue:** https://streamable.com/81js0

**Beatmap:** https://osu.ppy.sh/beatmapsets/1001218#taiko/2095795

**osu!lazer version:** 2019.831.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3562822/database.log)
[network.log](https://github.com/ppy/osu/files/3562823/network.log)
[performance.log](https://github.com/ppy/osu/files/3562824/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3562825/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3562826/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3562827/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3562828/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3562829/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3562830/updater.log)

**Comment by bdach** [comment]
Reproduces for me too with every play (also when restarting or quitting out and reentering beatmap). CPU profiling shows a single logical core peaking. This is the hot path:
```
Function Name	Total CPU [ms, %]	Self CPU [ms, %]	Module
| - osu.Game.Rulesets.UI.FrameStabilityContainer::UpdateSubTree	9196 (88,58%)	0 (0,00%)	osu.Game.dll
| - [External Call] osu.Framework.Graphics.Containers.CompositeDrawable::UpdateSubTree	9194 (88,57%)	6 (0,06%)	Multiple modules
| - osu.Game.Rulesets.UI.Scrolling.ScrollingHitObjectContainer::Update	9185 (88,48%)	0 (0,00%)	osu.Game.dll
| - osu.Game.Rulesets.UI.Scrolling.ScrollingHitObjectContainer::computeInitialStateRecursive	9180 (88,43%)	2 (0,02%)	osu.Game.dll
| - osu.Game.Rulesets.UI.Scrolling.Algorithms.OverlappingScrollAlgorithm::TimeAt	9118 (87,83%)	79 (0,76%)	osu.Game.dll
| - osu.Game.Rulesets.UI.Scrolling.Algorithms.OverlappingScrollAlgorithm::PositionAt	9028 (86,97%)	100 (0,96%)	osu.Game.dll
| - osu.Game.Rulesets.UI.Scrolling.Algorithms.OverlappingScrollAlgorithm::controlPointAt	8704 (83,85%)	201 (1,94%)	osu.Game.dll
| - [External Call] osu.Framework.Lists.SortedList`1[System.__Canon]::BinarySearch	8457 (81,47%)	793 (7,64%)	Multiple modules
| - osu.Game.Rulesets.Timing.MultiplierControlPoint::CompareTo	7664 (73,83%)	1578 (15,20%)	osu.Game.dll
```

**Comment by mouzedrift** [comment]
i could only guess that this has something to do with the SV changes since this map has an insane amount of SV changes

**Comment by phosphene47** [comment]
Seems to be related to my issue #5922 except I can reproduce this at the start and also whenever I resize the playfield.
