### ISSUE TITLE
Terminate music upon entering lazer on mobile.

### ISSUE THREAD

**Issue by 59xa** [ppy/osu#5942]
Any music playing before opening lazer needs to be force stopped when entering the app.

**Platform Specification:** _iPhone 7_ `iOS 13.1 Public Beta`

**Comment by iiSaLMaN** [comment]
I don't think that's something we can handle, and afaik entering an app automatically pauses any playing music?

**Comment by elleyer** [comment]
I'm not sure, but probably it's a thing that could help us to fix this issue: 
https://www.c-sharpcorner.com/blogs/audio-focus-request-xamarin-android-audio-player

**Comment by peppy** [comment]
Please provide details such as operating system and device.

**Comment by dscnnctd** [comment]
This could be applied to any device, I don’t know about android though. Just like in osu!stream, music gets paused when entering the app.

**Comment by peppy** [comment]
I know for a fact this work on iOS. This report is missing platform details.

**Comment by dscnnctd** [comment]
**Platform specification:** _iPhone 7_ `iOS 13.1 Public Beta`

**Comment by UselessToucan** [comment]
Note that LLSIF (Android) does not do this.
https://www.youtube.com/watch?v=VhmTbsyy1ew
