### ISSUE TITLE
Game has no menu content after gameplay

### ISSUE THREAD

**Issue by AlphaS-code** [ppy/osu#5943]
**Describe the bug:** 
I pressed button of restart map (R) and game is frozen

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/26285012/64081714-7902b400-cd0d-11e9-80ae-b79c30a346d9.png)
https://youtu.be/PPwa_9TafSo

**osu!lazer version:** 
2019.831.0.0

**Logs:** 

[performance.log](https://github.com/ppy/osu/files/3563869/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3563870/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3563871/updater.log)
[database.log](https://github.com/ppy/osu/files/3563872/database.log)

**Comment by peppy** [comment]
- logs don’t match report
- platform unclear
- title needs work

**Comment by smoogipoo** [comment]
At what point did you press the restart button? Was it at the very end of the map?
