### ISSUE TITLE
Crash when maximize or move the window

### ISSUE THREAD

**Issue by KDovatti** [ppy/osu#5944]
Crash when maximize or move the window

2019.831.0

I played it with this config:
- Intel Core i7 6700K
- Geforce GTX 1070 STRIX
- 16GB DDR4 3200Mhz RAM Corsair Dominator

**Comment by iiSaLMaN** [comment]
Can you please attach the logs, located in `%appdata%\osu\logs`

**Comment by smoogipoo** [comment]
Can you make sure you are actually on 2019.831.0? This should be fixed by https://github.com/ppy/osu-framework/pull/2810

**Comment by peppy** [comment]
Please reopen if you can reproduce this. As said above, this should not be possible.
