### ISSUE TITLE
Passive HP drain implementation

### ISSUE THREAD

**Issue by racer8412** [ppy/osu#5946]
Health drain is not yet implemented but should be (to match stable).

**Comment by peppy** [comment]
I've reworded every word of your issue to actually make it usable. Please open a second issue for smoke, as it is a second issue.

**Comment by iiSaLMaN** [comment]
Before you do that, there's already an issue about that: #5721

**Comment by genericthing** [comment]
shouldn't this be a option because a lot of people do not like hp drain to exist

**Comment by MightyHelper** [comment]
> shouldn't this be a option because a lot of people do not like hp drain to exist

For the mapper?
