### ISSUE TITLE
Abysmal performance on iOS after running for a while

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#5976]
**Describe the bug:** 
Performance is abysmal meaning under 30 FPS or even under 10 at some points. Music is garbled up as well. This happens when you’ve been playing for half an hour or more.
NOTE! After restarting the game, performance was perfectly fine again.

**Screenshots or videos showing encountered issue:** 
[Bad performance](https://youtu.be/c6xEdYNMI5Y) 
[After restart performance ](https://youtu.be/RUvbLnc_t1I) 

**osu!lazer version:** 
TestFlight 2019.903.0

**Logs:**

**Comment by peppy** [comment]
This is not iOS specific. It's likely due to memory constraints and is an ongoing issue we are looking at resolving. Mostly related to vertex buffers never being recovered (framework side): https://github.com/ppy/osu-framework/issues/2729

**Comment by ThatsNiceGuy** [comment]
I see. Well guess that’s solved
