### ISSUE TITLE
"click to view logs" crashes on mobile devices

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5984]
If notification center prompts an error and asks user to view the logs, then the game will crash on click. 

**Logs**
https://pastebin.com/kzD64FTE

**Comment by swoolcock** [comment]
Known issue, is caused by the loss of OpenGL context and the current workaround of force closing the app.

**Comment by peppy** [comment]
This is a different issue to the GL context loss (see attached log).

**Comment by ThatsNiceGuy** [comment]
happens on iOS too

**Comment by frenzibyte** [comment]
Has long been resolved since https://github.com/ppy/osu-framework/pull/5075
