### ISSUE TITLE
HitCircleOverlap are regressed and numbers scaled are wrong

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu#5996]
HitCircleOverlap in the skin are regressed now from this https://github.com/ppy/osu/pull/4264 

And numbers size are discaled - bigger than 1:1 (see on short slider)

Older Osu!Lazer version, before numbers are broken from .830, worked HitCircleOverlap and Size normal.

Osu Lazer:
![lazer](https://user-images.githubusercontent.com/53025167/64286045-0851d680-cf5d-11e9-9f45-56adce510ad9.png)
![osu_2019-09-04_22-01-21](https://user-images.githubusercontent.com/53025167/64287313-9e86fc00-cf5f-11e9-9074-9e8008cea336.png)

Osu Stable:
![stable](https://user-images.githubusercontent.com/53025167/64286068-130c6b80-cf5d-11e9-944f-8f73979f27a3.png)
![screenshot10779](https://user-images.githubusercontent.com/53025167/64287320-a21a8300-cf5f-11e9-92ee-50c63ca82b8c.png)

**osu!lazer version:** 
2019.903.0
**Logs:** 
Is a visual bug.

**Comment by peppy** [comment]
Please test against https://github.com/ppy/osu/pull/5969

**Comment by peppy** [comment]
Also please provide a link to the skins you are testing with.

**Comment by Fatal3ty** [comment]
@peppy Sorry for the too late, here a skin for the testing:
WWW Skin: http://puu.sh/EevkC/b4628a4769.osk
SeoulessHD: http://puu.sh/EevmU/8b47502fee.osk

Same skin with on screenshot as example.

**Comment by peppy** [comment]
This seems to be working correctly for me. Could you please confirm?

**Comment by Fatal3ty** [comment]
@peppy HitCircleOverlap are fixed, but Numbers are not 1:1, is bigger than normal:

Osu!Lazer:
![osu_2019-09-09_19-39-08](https://user-images.githubusercontent.com/53025167/64553516-d1533a80-d339-11e9-836a-8d9dc427f3ac.png)

Osu!Stable:
![screenshot10776](https://user-images.githubusercontent.com/53025167/64553702-24c58880-d33a-11e9-950c-90af78f8eedf.png)

Osu!Lazer Version: 2019.906.0

**Comment by peppy** [comment]
how are you measuring..?

**Comment by mouzedrift** [comment]
@Fatal3ty is just measuring by sight. the number files are skinned as numbers AND hitcircles so the hitcircle image is just a transparent file.

**this is the default-1.png for an example:**
![default-1](https://user-images.githubusercontent.com/43358824/64641169-e5676c80-d40b-11e9-80b5-6030915fbaa6.png)
so the problem @Fatal3ty encounters here is that the "hitcircle" doesnt fit on the slider as you can see here:

**Osu!Lazer:** 
![osu_2019-09-09_19-39-08_2](https://user-images.githubusercontent.com/43358824/64641868-565b5400-d40d-11e9-8872-49d0b38900b0.png)


**Osu!Stable:**
![screenshot10789](https://user-images.githubusercontent.com/43358824/64641831-417ec080-d40d-11e9-8260-b2fcd15a2e29.png)

**Comment by peppy** [comment]
Oh, thank you for pointing this out! This clears things up.
