### ISSUE TITLE
It's not the full source code

### ISSUE THREAD

**Issue by Menci** [ppy/osu#6]
I built it and it's only a welcome UI.

When can I get the full source code?

**Comment by TPGPL** [comment]
what

**Comment by Shadoxfix** [comment]
The main menu is currently everything that is available. Nearly everything is being rewritten and this is the progress thus far.

**Comment by thehowl** [comment]
No shit, sherlock.

If you want to get the full source code now, see this http://blog.ppy.sh/post/144539340703/early-bird-contributors .

From what I understood, source code will be gradually released on this repository, and not all in one shot.
