### ISSUE TITLE
Hitobjects have no color and sound with default skin

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#6005]
**Describe the bug:** All hitobjects are white with the default Lazer skin, and they have no hitsound.

**Screenshots or videos showing encountered issue:** https://streamable.com/x4455

**osu!lazer version:** 2019.905.0

**Comment by bdach** [comment]
Yeah, I also have this.

Seems to have regressed in two separate commits. The lack of colours bisected down to bebc330, but hitsounds were working at f58ca82. I can investigate further and/or bisect the hitsounds too if necessary.

**Comment by bdach** [comment]
Hitsounds disappearing bisected down to 6197c7f.

**Comment by Gabixel** [comment]
Fixed by https://github.com/ppy/osu/commit/fbdef9749828326767e6c999e5b3300a38c2976b I guess
