### ISSUE TITLE
Support for dotnet CORE 3.0 preview (about to be stable)

### ISSUE THREAD

**Issue by zackarycw** [ppy/osu#6012]
I notice the prerequisites for osu! is "A desktop platform with the .NET Core SDK 2.2 or higher installed." I use the dotnet CORE 3.0 preview. However upon trying to build osu! after setting up the variables in my bashrc, I get:
```
It was not possible to find any compatible framework version

The specified framework 'Microsoft.NETCore.App', version '2.2.0' was not found.

- The following frameworks were found:

3.0.0-preview9-19423-09 at [/media/Media/linux apps/dotnet SDK/shared/Microsoft.NETCore.App]


You can resolve the problem by installing the specified framework and/or SDK.


The .NET Core frameworks can be found at:

- https://aka.ms/dotnet-download
```

So it's clear that there is not yet support for dotnet CORE 3.0. Configuring things like OpenSSL is way easier on 3.0 than it was on versions like 2.2. However, with the upcoming stable release of 3.0 to be replacing 2.2, I think it's time to add support for the 3.0 preview to get proper testing done before the stable release if possible; that would be ideal.

**Comment by zackarycw** [comment]
To clarify the OpenSSL stuff, there are more and more linux distros that are starting to use LibreSSL as opposed to OpenSSL. The dotnet CORE 3.0 preview (about to be stable release) works well with building OpenSSL yourself.

**Comment by jai-x** [comment]
Changing the `TargetFramework` element value in the `.csproj` files from `netcoreapp2.2` to `netcoreapp3.0` will probably allow you to build correctly.

**Comment by peppy** [comment]
You can manually make the change as proposed for now. We will add support time permissive (needs to be done for all projects, starting with framework).

**Comment by zackarycw** [comment]
Thanks for the suggestion, jai-x. It seems to work perfectly when running `$ dotnet run --project osu.Desktop`. Now, possibly a dumb question, but I'm not too familiar with dotnet. The command builds and runs it, right? If I wanted to say, just write up a .desktop file, where would just the binary of the game be so I don't have to build it everytime at launch? I'd also like to know this so I know what I should tell firefox how to open .osz files for example. Thanks

**Comment by peppy** [comment]
Please look into the (unofficial) AUR package or just use `dotnet publish` yourself.
