### ISSUE TITLE
osu!classic - skin issues

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#6013]
the new osu!classic skin is missing quite a lot from the osu!classic of osu!stable. the circles at the end of sliders are gone, (most likely intended) - sliders are too dark it seems, circles seem slightly too big, - I'm also slightly disappointed that the gameplay UI hasnt gotten osu!stable-ified

The trail is wrong, it seems

hits are missing particles, i loved those particles.

**Comment by bdach** [comment]
As for the trail, you probably want #5721.

**Comment by Hubza** [comment]
@bdach osu!classic trail
![image](https://user-images.githubusercontent.com/33783503/64385589-b9747180-d02e-11e9-8ff0-1636da65499c.png)
osu!stable trail
![image](https://user-images.githubusercontent.com/33783503/64385619-d446e600-d02e-11e9-92e4-1b1e47025b38.png)

these both seem pretty different to me

Disclaimer: i'm talking about the new built in "osu!classic" skin in osu!lazer.
![image](https://user-images.githubusercontent.com/33783503/64385646-e3c62f00-d02e-11e9-95f1-69fcc34a43b6.png)

**Comment by TPGPL** [comment]
its because those skin features are NOT implemented in lazer for any skin, it has nothing to do with the classic skin

**Comment by smoogipoo** [comment]
Please make a separate issue for each of these.
