### ISSUE TITLE
Clicking circles after death

### ISSUE THREAD

**Issue by TreeCube** [ppy/osu#6017]
**Describe the bug:** 
you can continue to click circles, sliders, and gain health after death. 
**Screenshots or videos showing encountered issue:** 
![osu_2019-09-05_22-33-15-1](https://user-images.githubusercontent.com/54969128/64396899-3868aa80-d02d-11e9-96eb-913e60a69610.jpg)

**osu!lazer version:** 
most recent, 2019.905.0 dev build
**Logs:**

**Comment by smoogipoo** [comment]
Intended, they don't affect score.
