### ISSUE TITLE
Cannot exit overlays with M4

### ISSUE THREAD

**Issue by hbnrmx** [ppy/osu#6026]
`GlobalAction.Back` doesn't work on Overlays when bound to mouse buttons (e.g. `M4` (mouse back button))
only when it's bound to keyboard keys (e.g. `Esc`)

Looks like key presses and mouse clicks are handled differently in general.
**osu!lazer version:** 
2019.906.0

**Comment by peppy** [comment]
This is due to positional input (all mouse buttons) being blocked by `OverlayContainer`s. We may want to consider allowing non-primary buttons to act as non-positional input, or make a similar exception for them.
