### ISSUE TITLE
Relax mode no longer works for catch

### ISSUE THREAD

**Issue by anexistantperson** [ppy/osu#6027]
**Describe the bug:** 
Relax mode for catch now just makes the player not able to move instead of being controlled by the mouse.

lazer version: 2019.906.0

**Comment by iiSaLMaN** [comment]
Since when was it implemented..? Duplicate of #5765

**Comment by anexistantperson** [comment]
Its in the stable build right now. and I forgot to check to see if it was already an issue so sorry about that ;-;

**Comment by iiSaLMaN** [comment]
> Its in the stable build right now.

I meant that since when was it implemented in lazer because you said "Relax mode **no longer works**"
