### ISSUE TITLE
Cinema mod is unaccessable

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#6029]
**Describe the bug:** You can't access Cinema mod by double clicking Auto mod.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=_CZ8KV77CHc

**osu!lazer version:** 2019.906.0

**Logs:** -

**Comment by iiSaLMaN** [comment]
More like: `Add Cinema Mod Support`

**Comment by TPGPL** [comment]
oh i thought it was added already, as you can see that there are stacked mods here. It looks pretty confusing for me

**Comment by ObiDriftKenobi** [comment]
If there's cinema mode added in the future, maybe it could have a toggleable music visualizer. Just a suggestion.

**Comment by peppy** [comment]
The idea is to be able to watch the storyboard of a beatmap. A visualiser would detract from that.
