### ISSUE TITLE
speedy spinners make misses

### ISSUE THREAD

**Issue by TreeCube** [ppy/osu#6036]
**Describe the bug:** 
spinners that are fast make misses. such as scattered faith where in stable, the spinners show, but dont count. 
**Screenshots or videos showing encountered issue:** 
obs dont work ~ sorry
**osu!lazer version:** 
2019.906.0
**Logs:**

**Comment by bdach** [comment]
It appears to me that you're describing the same issue as in #5826?

**Comment by iiSaLMaN** [comment]
Please describe what your issue is, too short spinners cannot be completed with auto?

**Comment by peppy** [comment]
Duplicate of #5826.
