### ISSUE TITLE
When playing a song on main menu or song select, error notification appears non stopped

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu#6051]
Weird bugs, when play a song and switch a next song automatically, new error notifications appears always repeating (same bug on when i use a song select, new error appears non stopped)

**Screenshots or videos showing encountered issue:** 
![ss (2019-09-09 at 08 02 28)](https://user-images.githubusercontent.com/53025167/64555125-f5fce180-d33c-11e9-973d-2a16962590f7.jpg)

Example this maps, when have a too low or high bpm:
https://osu.ppy.sh/beatmapsets/997827#osu/2087153 (loved)
https://osu.ppy.sh/beatmapsets/948643#osu/1981090 (loved)
https://osu.ppy.sh/beatmapsets/540207#osu/1145512
https://osu.ppy.sh/beatmapsets/639704#taiko/1356692 (taiko, loved)

**osu!lazer version:** 
2019.906.0
**Logs:** 
I checked all log file, but error appeared only on runtime.log
[runtime.log](https://github.com/ppy/osu/files/3591935/runtime.log)
http://puu.sh/EfiAU/19da0842be.log (too big upload for github, performance.log 33MB)

**Comment by smoogipoo** [comment]
The errors are intentional but the UX could probably be improved. Showing on MusicController change is a bit too much.

**Comment by peppy** [comment]
These should only be shown when entering gameplay, I believe. Right now it's happening because we are parsing the .osu file way too early/often.

**Comment by Theighlin** [comment]
These errors have since been silenced for the users, because they could not do anything about it. Verified with one of the linked maps that this is the case. Can be closed.

**Comment by bdach** [comment]
Resolved by https://github.com/ppy/osu/pull/18435
