### ISSUE TITLE
startup crash on linux

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu#6057]
```
git clone https://github.com/ppy/osu
cd osu
LD_LIBRARY_PATH="$(pwd)/osu.Desktop/bin/Debug/netcoreapp2.2" dotnet run --project osu.Desktop
```
window shows up for a split second, then terminates immediately

[performance.log](https://github.com/ppy/osu/files/3594473/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3594474/runtime.log)
these logs don't look very useful so I logged the terminal output (including stderr in case thats relevant) which shows a stack trace: 
[output+stderr.log](https://github.com/ppy/osu/files/3594496/output%2Bstderr.log)

specs: [neofetch.txt](https://github.com/ppy/osu/files/3594520/neofetch.txt)

**Comment by peppy** [comment]
https://github.com/ppy/osu-framework/issues/2272
