### ISSUE TITLE
Skin custom numbers not being imported or loaded properly

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#6058]
The custom skin numbers in my skin do not load in osu!lazer

[This is the skin i'm using](https://github.com/eclipsedteam/Simplify/releases/download/1.0/Simplify.osk)

In this skin, hitcircles use the prefix "hitnum"
![image](https://user-images.githubusercontent.com/33783503/64599701-c0dea680-d3b1-11e9-9f17-8a3493a05092.png)
and it also uses hitnum in the skin.ini
`[Fonts]`
`HitCirclePrefix: hitnum`
`HitCircleOverlap: 6`

but when loading in osu!lazer, the skin still uses the default osu!lazer font
![image](https://user-images.githubusercontent.com/33783503/64599887-2337a700-d3b2-11e9-916c-0a653f1f6c1f.png)
osu!stable gameplay
![image](https://user-images.githubusercontent.com/33783503/64599941-3a769480-d3b2-11e9-9bdb-0050f5d8a574.png)

2019.906.0

**Comment by Hubza** [comment]
fixed by #6059

**Comment by smoogipoo** [comment]
Let the PR close the issue.
