### ISSUE TITLE
Long usernames are not truncated in multiplayer chat

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#6061]
**Describe the bug:** The latest update added the ability to truncate long usernames in chat, but not in the multiplayer's one.

**Screenshots or videos showing encountered issue:** 
![multiplayer chat](https://user-images.githubusercontent.com/43073074/64627420-e7233700-d3ef-11e9-80dc-8de961eff6a2.png)

**osu!lazer version:** 2019.910.0

**Comment by FullTablet** [comment]
Is truncating the best solution? If my name didn't fit in the space, I'd rather have it look squished instead.

**Comment by peppy** [comment]
This has been completed via https://github.com/ppy/osu/pull/6023. We can't really "squish" names because it would look bad, so truncation is our current solution.

**Comment by peppy** [comment]
Sorry, didn't see that this issue was for a different area.
