### ISSUE TITLE
OSX editor will not allow to delete

### ISSUE THREAD

**Issue by starsgaze** [ppy/osu#6077]
**Describe the bug:** When editing any map the editor will not allow to delete

**Screenshots or videos showing encountered issue:** None

**osu!lazer version:** 2019.910.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3602815/database.log)
[performance.log](https://github.com/ppy/osu/files/3602817/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3602818/runtime.log)

**Comment by smoogipoo** [comment]
It works using fn+delete. Probably should also work using cmd+delete - I'm not sure if just `delete` itself should be allowed (opinions @peppy ?)

**Comment by peppy** [comment]
This has since been resolved by platform actions, as far as i can tell.
