### ISSUE TITLE
Scoring System CTB not 1M when SS NoMod

### ISSUE THREAD

**Issue by HerendraTJ** [ppy/osu#6080]
**Describe the new feature:** 
The scoring system in CTB when I played a map is not 1M exactly. The ScoreV2 goal is to make the scoring is 1M when you have 100% Accuracy No Mods. I Just figured out why this issue was happened. After digging the replays, the scoring system count the Banana bonus as a score. In osu! STD , this is like the spinners and the spinners won't affect your scoring even though you are spinning at certain SPM. As long as your spinning is passed the minimum requirements it counts as 300.

**Proposal designs of the feature:** 
There is the certain amount of banana required to pass it , like the Spinners in STD , certain SPM pass the spinners. But the banana is not count as a score as well. Instead it counts as passing grade. What I mean is can you pass the banana bonus or not.

Picture Links
[https://imgur.com/a/018UPPD]

**Comment by smoogipoo** [comment]
This is intentional to match osu!stable's ScoreV2 for the time being, and we can likely consider changes to scoring in the future after osu!lazer is rankable.

**Comment by HerendraTJ** [comment]
Ok thanks dude, please refer this issue after the osu!lazer is rankable. Issue Closed.
