### ISSUE TITLE
Add ability to export skins

### ISSUE THREAD

**Issue by HerendraTJ** [ppy/osu#6084]
**Describe the missing feature:** 
In osu!Stable , skin can be exported to *.osk* in settings. Now in Lazer , that feature is missing. Why I want this happened ? Because some elements in Lazer isn't available in osu!. Example for the image mod, beatmap selection, scoring number, HP Drain bar , progress bar.
**Proposal designs of the feature:** 
Creating the Export Skin Button so people can make and port the skin to the newest one. All the elements of the skin including HP Drain bar, score bar, button bar , progress bar, BG Selection, Ranking Section,etc.

**Comment by peppy** [comment]
Exporting of skins and beatmaps is still some way away. New formats for export will be defined first.

**Comment by HorizonCode** [comment]
one quick question here(i think it may not be relevant, but i am really fucked)
i accidentally deleted all my skins in stable, but imported them all 3 months ago in lazer, is there some method to get them back from osu!lazer to stable? qwq

**Comment by smoogipoo** [comment]
Resolved via https://github.com/ppy/osu/pull/9101
