### ISSUE TITLE
Can't drag click dialog buttons

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#6089]
Regressed in 2019.828.0. Happens on `ModSelectOverlay`'s deselect all and close buttons too.

![](https://puu.sh/Eguol/49eb181a7b.gif)

**Comment by bdach** [comment]
Bisect turned up ac0628d as the first bad revision that builds, as b59973c doesn't. So this seems to be related to the framework bump at #5856.

The above is even more likely considering drag clicks work on 2019.828.0 in `TestScenePopupDialog`, but not `TestSceneDialogOverlay`.

**Comment by iiSaLMaN** [comment]
Maybe regressed in ppy/osu-framework#2786

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu-framework/pull/2960.
