### ISSUE TITLE
Beatmap leaderboards don't expire correctly when on details tab

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#6090]
![](https://puu.sh/EguBN/27844d2a32.gif)

**Comment by peppy** [comment]
Not sure what this one entails, and the linked image is no longer available. @Joehuu happen to recall any details?

**Comment by Joehuu** [comment]
When navigating from global -> details -> local for example, you can see the previous leaderboard (global) for one frame when navigating from details to local:

https://user-images.githubusercontent.com/35318437/175331596-180a1240-060a-422f-8a17-0d9ab0775542.mp4

The new design separates the detail display and leaderboards, so closing this is probably not worth fixing now.
