### ISSUE TITLE
Add customisable key bindings to toggle mods

### ISSUE THREAD

**Issue by RoARene317** [ppy/osu#6092]
**Describe the missing feature:** 
In stable release , people could trigger the mods button by pressing keyboard shortcut. Now in lazer it's missing.
**Proposal designs of the feature:*
Mods can be toggle by keyboard , for the custom mods (Grow mods , Transform mods) Can be triggered by pressing F1-F12 (By Default).

**Comment by HerendraTJ** [comment]
![image](https://user-images.githubusercontent.com/24410807/64904897-fe696980-d6fa-11e9-94f4-421dc763af18.png)
2019.913.0 Since this comment is submitted and still not shown

**Comment by iiSaLMaN** [comment]
@HerendraTJ It's hardcoded to the ruleset! itself I think, you can't modify the key binding

**Comment by HerendraTJ** [comment]
> @HerendraTJ It's hardcoded to the ruleset itself I think, you can't modify the key binding

I think maybe the next update they should add to the key binding since it's a lot of easier than editing the config file.

**Comment by peppy** [comment]
the key bindings on the mod select screen are not intended to be customisable. we may add special mod selection hotkeys which can be used globally, but that is a different scope.
