### ISSUE TITLE
game crash after scrolling on a user profile

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#6094]
i tried to reproduce it a second time but it doesnt work so im not sure what exactly caused the game to crash

**osu!lazer version:** latest build

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3608815/runtime.log)
[database.log](https://github.com/ppy/osu/files/3608816/database.log)
[network.log](https://github.com/ppy/osu/files/3608817/network.log)
[performance.log](https://github.com/ppy/osu/files/3608818/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3608819/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3608820/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3608821/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3608822/performance-gamethread.update.log)

**Comment by peppy** [comment]
Are you running on a low memory system?

**Comment by mouzedrift** [comment]
8GB ram DDR3 should be fine i think

**Comment by Gabixel** [comment]
For me, on mobile, with very low memory (like 1GB), Lazer seems to freeze for a while when loading the Beatmaps' Cover part in a profile (this one:)

![image](https://user-images.githubusercontent.com/43073074/64855692-bb3ac800-d620-11e9-9ecd-cefb9b7e0fb4.png)

I have no logs right now but.. maybe it's related to this? (if you need logs, just ask)

**Comment by Joehuu** [comment]
Closing as stale. There is not enough information to reproduce this problem.
