### ISSUE TITLE
Video playback fails on certain maps

### ISSUE THREAD

**Issue by Snowmander** [ppy/osu#6099]
**Describe the bug:** 
Video does not play in some maps.
(Tested on a fresh install.)

**Screenshots or videos showing encountered issue:** 

![](https://i.imgur.com/wclIW1A.jpg)

https://osu.ppy.sh/beatmapsets/506771
https://osu.ppy.sh/beatmapsets/62852

**osu!lazer version:** 
Latest 2019.913.0
iPad Pro
**Logs:**

**Comment by Snowmander** [comment]
Oops, this should be on osu-framework.

**Comment by ThatsNiceGuy** [comment]
Same thing here, videos don’t play for me. I did delete and reimport the maps using osu!direct first before.
lazer 2019.913.0
iPad Pro 11”

**Comment by EVAST9919** [comment]
These maps have .flv format videos. Looks like `VideoSprite` can't handle such format.

**Comment by peppy** [comment]
flv should still work in theory. need error logs.

**Comment by EVAST9919** [comment]
That's interesting:
`2019-09-14 03:37:10: Video too far out of sync (0), seeking to -9,22337203685478E+18`

**Comment by EVAST9919** [comment]
Tested other maps. Still happens only with .flv files so far.

**Comment by huupoke12** [comment]
I have the same problem on Arch Linux.
I use these 2 beatmaps for testing:
For FLV: https://osu.ppy.sh/beatmapsets/494768
For AVI: https://osu.ppy.sh/beatmapsets/57762
Here are the logs:
[osu-lazer-logs-avi.zip](https://github.com/ppy/osu/files/3658318/osu-lazer-logs-avi.zip)
[osu-lazer-logs-flv.zip](https://github.com/ppy/osu/files/3658319/osu-lazer-logs-flv.zip)

Only black background is shown when playing FLV video beatmap.
After running osu!lazer and play the FLV video beatmap, this is the output of the terminal:
[osu-lazer-terminal-flv.txt](https://github.com/ppy/osu/files/3658347/osu-lazer-terminal-flv.txt)
And this is the ouput of the terminal after playing AVI video beatmap:
`
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
`

**Comment by huupoke12** [comment]
This bug has been fixed in the build 2020.221.0. Maybe https://github.com/ppy/osu-framework/pull/3019 fixed this.

**Comment by peppy** [comment]
Awesome stuff.
