### ISSUE TITLE
Video playback is stretched

### ISSUE THREAD

**Issue by Snowmander** [ppy/osu#6100]
**Describe the bug:** 
Video playback probably shouldn’t be stretched.
~~Happens on all maps.~~ Doesn’t happen on [some maps ](https://osu.ppy.sh/beatmapsets/361740#osu/794670) if the screen is in landscape.

**Screenshots or videos showing encountered issue:** 
![](https://i.imgur.com/HktYCkt.jpg)

**osu!lazer version:** 
Latest 2019.913.0
iPad Pro

**Logs:**

**Comment by Snowmander** [comment]
Also, the video timing is off to a different degree depending on the map. Perhaps something to do with video offset on an .osu file?

Not making another issue because it’s spammy

**Comment by iiSaLMaN** [comment]
> Not making another issue because it’s spammy

We never say that. keep in mind separating one issue per GitHub issue is much better than listing a couple of issues in one GitHub issue (and to allow us closing the issue automatically on PR merge)
