### ISSUE TITLE
Video playback doesn't consider offset value

### ISSUE THREAD

**Issue by Snowmander** [ppy/osu#6101]
**Describe the bug:** 
Videos on most maps are out of sync with the music. Suspected reason: video offset in .osu file is not being applied correctly.

The discrepancy is especially big on [this map](https://osu.ppy.sh/beatmapsets/42532#osu/133729), which I believe is a map with a very large video offset.

https://osu.ppy.sh/beatmapsets/42532#osu/133729
https://osu.ppy.sh/beatmapsets/45404#osu/141786
https://osu.ppy.sh/beatmapsets/945049#osu/2026320

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
Latest 2019.913.0
iPad Pro
**Logs:**

**Comment by peppy** [comment]
The offset is not being read at all. In fact the current method of video playback initialisation is very wrong and temporary at best (it should be read as part of the storyboard, where the information exists).
