### ISSUE TITLE
Spinning rate doesn't match stable

### ISSUE THREAD

**Issue by jcolzee** [ppy/osu#6107]
The spin on osu lazer is not right and is off with its spin calculator i spin 350 on a map in osu lazer but in normal osu i only spin 290 on the same map with consistent spins and i checked with a bot and the spins are different even with a bot

**Comment by iiSaLMaN** [comment]
Currently, osu!lazer spinner spin calculations are inaccurate with osu!stable as there seem to be some accelerations with stable spinner.

**Comment by peppy** [comment]
After accounting for acceleration differences, the rates should be almost perfectly matching (as they both measure RPM). Needs further investigation to see if there is actually a discrepancy here.
