### ISSUE TITLE
Replays should not fail

### ISSUE THREAD

**Issue by HerendraTJ** [ppy/osu#6108]
**Describe the bug:** 
Some replays showing failed plays in the middle of the game play. Please Fix this.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/Cgz87fVWhxo
**osu!lazer version:** 
2019.913.0
**Logs:** 
No Logs

**Comment by aspriddell** [comment]
Have you tried other replays? I have tried a few myself (with hidden, hard rock and double time) and can't recreate the issue. That being said you should also try with the default skin. The replay only holds the mouse position and keys hit at that time so it could be a bug with the skin?

**Comment by Lolihunter1337** [comment]
> Have you tried other replays? I have tried a few myself (with hidden, hard rock and double time) and can't recreate the issue. That being said you should also try with the default skin. The replay only holds the mouse position and keys hit at that time so it could be a bug with the skin?

Only happens on plays with "perfect" mod for me

**Comment by bdach** [comment]
#5514 might be relevant here.

**Comment by HerendraTJ** [comment]
> #5514 might be relevant here.

Yes , looks like it's relevant to the issue. Can I Close this issue right now due to the duplicate?

**Comment by HerendraTJ** [comment]
> > Have you tried other replays? I have tried a few myself (with hidden, hard rock and double time) and can't recreate the issue. That being said you should also try with the default skin. The replay only holds the mouse position and keys hit at that time so it could be a bug with the skin?
> 
> Only happens on plays with "perfect" mod for me. ( so same issue as Herendra said in title )

For my suggestion is just remove the current global ranks right now in lazer until it's final stable release. For now , I think there should be a separate ranking system , like Lazer Rank is separate from the real Rank (Beatmap only).

**Comment by Joehuu** [comment]
Nah, non of those issues are relevant. That replay technically got a 100 on a slider which stable doesn't count as 100. That's why lazer's perfect mod fails.

**Comment by aspriddell** [comment]
> Nah, none of those issues are ~relevant~ duplicates. That replay technically got a 100 on a slider which stable doesn't count as 100. That's why lazer's perfect mod fails.

If you slow it down it **does** show the 100 on screen (https://youtu.be/Cgz87fVWhxo?t=43) for a small fraction

In this case for legacy replays maybe use old judgement logic???

**Comment by peppy** [comment]
Fail should not trigger on replays regardless; if that's what currently happening then that is incorrect.

**Comment by iiSaLMaN** [comment]
> Fail should not trigger on replays regardless; if that's what currently happening then that is incorrect.

Honestly, the correct solution in my opinion is to just not judge on the drawable slider head, at least for legacy replays.

Also to allow supporting failed replays.

**Comment by peppy** [comment]
We have not yet decided what to do with legacy plays and it is too early to make a call on this one.
