### ISSUE TITLE
Osu!Lazer won't launch

### ISSUE THREAD

**Issue by Talkative-Cloud** [ppy/osu#6111]
I downloaded Osu!Lazer today, clicked the installer, and the installing window hasn't shown
It was only visible in the start bar but did not appear
The installer has turned off and on my desktop appeared the osulazer.ink, but when clicked, nothing happens. Task manager doesn't show any activities from the game also
It's like it was a ghost app or something
It's hard to explain. Here's the video of the entire process including installing

https://youtu.be/f7eZ8eWdPlI

The game just won't start even for a second

**Comment by bdach** [comment]
Does the `%AppData%/osu/logs` directory exist? If so, please attach anything that might be there in here; if not, would you mind taking a look at the Windows Event Viewer for anything relevant?

Also, are you running 32bit Windows 7 by any chance?

**Comment by Talkative-Cloud** [comment]
> Does the `%AppData%/osu/logs` directory exist? If so, please attach anything that might be there in here; if not, would you mind taking a look at the Windows Event Viewer for anything relevant?
> 
> Also, are you running 32bit Windows 7 by any chance?

Nope. I'm using Windows 7 64bit

If you mean appdata/roaming then there is no osu folder
In appdata/local and osu/logs, there are only these 2 files
[runtime.log](https://github.com/ppy/osu/files/3612734/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/3612736/update_success.log)

**Comment by bdach** [comment]
> Nope. I'm using Windows 7 64bit

OK, was just making sure, since 32bit binary support isn't there yet.

> If you mean appdata/roaming then there is no osu folder
> In appdata/local and osu/logs, there are only these 2 files
> [runtime.log](https://github.com/ppy/osu/files/3612734/runtime.log)
> [update_success.log](https://github.com/ppy/osu/files/3612736/update_success.log)

These show a connection issue, you seem to be unable to connect to bancho (https://c6.ppy.sh). I'm not sure if that's transient or not, and it's probably unrelated to the squirrel silent installer failure, but you might want to look into that part on your side.

**Comment by Talkative-Cloud** [comment]
> > Nope. I'm using Windows 7 64bit
> 
> OK, was just making sure, since 32bit binary support isn't there yet.
> 
> > If you mean appdata/roaming then there is no osu folder
> > In appdata/local and osu/logs, there are only these 2 files
> > [runtime.log](https://github.com/ppy/osu/files/3612734/runtime.log)
> > [update_success.log](https://github.com/ppy/osu/files/3612736/update_success.log)
> 
> These show a connection issue, you seem to be unable to connect to bancho (https://c6.ppy.sh). I'm not sure if that's transient or not, and it's probably unrelated to the squirrel silent installer failure, but you might want to look into that part on your side.

Well I indeed have some internet issues but it shoudn't be that much of a problem
In osu!stable it takes around 4 seconds to connect to the bancho, starting from the main menu being loaded

Osu!Lazer seems to not even try to turn on. It doesn't appear in the task manager even for a second

Is there anything I can do? Or should I wait for the fix from the osu side

**Comment by kravque** [comment]
Try Downloading the update from here: https://github.com/ppy/osu/issues/3966#issuecomment-456013952

**Comment by Talkative-Cloud** [comment]
> Try Downloading the update from here: [#3966 (comment)](https://github.com/ppy/osu/issues/3966#issuecomment-456013952)

Still the same issue

Also I'm not even using Intel HD

I have normal GTX650ti 2GB

**Comment by bdach** [comment]
Thus far there's not much to go on here in terms of diagnosing this. Mind looking into the Event Viewer after all? You'd be looking for some sort of application error around the time of launch.

**Comment by Talkative-Cloud** [comment]
> Thus far there's not much to go on here in terms of diagnosing this. Mind looking into the Event Viewer after all? You'd be looking for some sort of application error around the time of launch.

No errors nor warnings

I even tried reinstalling Lazer to see if will there be any errors then but nope

**Comment by peppy** [comment]
We will need logs from event viewer to take this further.

**Comment by timofeybasalygo** [comment]
There is a screenshot: https://user-images.githubusercontent.com/57365766/68144070-e6b4a180-ff43-11e9-99cf-61bb8a4ac775.png

I have the same problem as this dude, and I also looked into the event viewer, I took a screenshot of the properties of the event, I’ll leave it here, maybe this will somehow help to find a solution.Something tells me that this link (https://go.microsoft.com/fwlink/?linkid=798306) will be the solution to the problem, I’ll check later, I just want to make sure that I'm doing everything right

**Comment by bdach** [comment]
@timofeybasalygo Yeah, if you follow that link and install all the necessary prerequisites you should be fine.

**Comment by timofeybasalygo** [comment]
> @timofeybasalygo Yeah, if you follow that link and install all the necessary prerequisites you should be fine.

Yup,i installed few win updates,than installed all prerequisites and now osu!lazer working

**Comment by smoogipoo** [comment]
Closing as resolved.

**Comment by bdach** [comment]
@Jack13213 I would suggest to try reading the thread above, and if any of the above resolutions fail to help, providing any details at all (which you haven't) such as lazer or windows event viewer logs.

**Comment by sirloinsteak11** [comment]
Hey, I'm having the same problem as well. This is what I got from the event viewer: https://imgur.com/c3rvu8n

**Comment by bdach** [comment]
@sirloinsteak11 that is *not* the same issue. please reopen as a separate issue, and include logs in the issue template.

**Comment by Kurbynow** [comment]
> There is a screenshot: https://user-images.githubusercontent.com/57365766/68144070-e6b4a180-ff43-11e9-99cf-61bb8a4ac775.png
> 
> I have the same problem as this dude, and I also looked into the event viewer, I took a screenshot of the properties of the event, I’ll leave it here, maybe this will somehow help to find a solution.Something tells me that this link (https://go.microsoft.com/fwlink/?linkid=798306) will be the solution to the problem, I’ll check later, I just want to make sure that I'm doing everything right

and... what specifically i  havely downloadly?

**Comment by smoogipoo** [comment]
@Kurbynow https://docs.microsoft.com/pt-br/dotnet/core/install/windows?tabs=net60#windows-7--vista--81--server-2008-r2--server-2012-r2

**Comment by Kurbynow** [comment]
> @Kurbynow https://docs.microsoft.com/pt-br/dotnet/core/install/windows?tabs=net60#windows-7--vista--81--server-2008-r2--server-2012-r2

i already download this

**Comment by smoogipoo** [comment]
Please read https://github.com/ppy/osu/discussions/15188 and provide logs, and your operating system version.

**Comment by Kurbynow** [comment]
> Please read #15188 and provide logs, and your operating system version.

[runtime.log](https://github.com/ppy/osu/files/7942755/runtime.log)

@smoogipoo

**Comment by smoogipoo** [comment]
Sounds like a driver issue, please install all Windows updates and drivers.

**Comment by Kurbynow** [comment]
> Sounds like a driver issue, please install all Windows updates and drivers.

are already installed

**Comment by smoogipoo** [comment]
Since you're on Windows 8 you won't be able to run osu! anyway, Windows 8.1 is the minimum we support.

**Comment by Kurbynow** [comment]
> Since you're on Windows 8 you won't be able to run osu! anyway, Windows 8.1 is the minimum we support.

windows 10

**Comment by smoogipoo** [comment]
In that case, you might have compatibility mode turned on for osu!. Right click the osu! icon -> Properties -> make sure this compatibility setting is turned off:
![image](https://user-images.githubusercontent.com/1329837/151192384-b1d6ad10-4410-4978-9732-2803cdf7ba97.png)

**Comment by Kurbynow** [comment]
> In that case, you might have compatibility mode turned on for osu!. Right click the osu! icon -> Properties -> make sure this compatibility setting is turned off:

I've already disabled it but it still doesn't start, I'll restart to apply the updates

**Comment by Kurbynow** [comment]
@smoogipoo I restarted, and... the osu! leisure opened in background, didn't open tab, just shows in task manager, and then closed.

**Comment by Relax134** [comment]
hi mine was successfully installed but its not opening, i opened task manager and saw osu!lazer running at the backround 
![image](https://user-images.githubusercontent.com/124537637/216854370-848748ff-4f0d-411c-b553-567c781ed97a.png)
then it will close and nothing happens please help

**Comment by Relax134** [comment]
![image](https://user-images.githubusercontent.com/124537637/216854415-82ac1002-0447-407f-8ba2-5f29da8811fa.png)
here is a full picture of my task manager when i open osu!lazer

**Comment by peppy** [comment]
Please close both tasks and run again.

Also please provide hardware specs. From the resolution you're running at I have doubts your PC specs are up to the level of being able to run lazer in its current state.

**Comment by Relax134** [comment]
ok so i upgraded to windows 11 now i get another error
osu!.exe - System Error
X    Exeption Processing Message 0xc0000005 - Unexpected parameters
                                                                                              OK
i dont know what to do

**Comment by Relax134** [comment]
this is the error
![image](https://user-images.githubusercontent.com/124537637/217678199-16c4e1d3-4ce0-45e7-954b-774323b5a06e.png)

**Comment by Relax134** [comment]
here are my hardware specs
![Untitled](https://user-images.githubusercontent.com/124537637/217678538-ade4ad0c-2a99-48da-8d70-efbc00241fa2.png)

**Comment by smoogipoo** [comment]
That looks like it's going to be a GPU driver issue.

If it's even resolvable (I'm not sure how you're running W11 on a Pentium T4400), you're likely going to have to wait until we get Direct3D support in. In any case please provide your [dxdiag output](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe).
