### ISSUE TITLE
Getting high cursor input latency on OSU Lazer(don't have the delay on standard OSU)

### ISSUE THREAD

**Issue by scowlingsoup** [ppy/osu#6119]
**Describe the bug:** when playing game, the cursor has a high latency, it cant be related to computer because the RAM have a lot of free space 

**Screenshots or videos showing encountered issue:**(I can't make videos , sorry) 

**osu!lazer version:** 

**Logs:** 
(PS:I can't use English properly yet, but the bug is exist)

**Comment by peppy** [comment]
Maybe related to https://github.com/ppy/osu/issues/6075. Missing any details worth keeping open.
