### ISSUE TITLE
Truncated text should have tooltips of full text

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#6120]
To match with web behavior.

**Comment by HerendraTJ** [comment]
Could you please explain the details about the new concept of your design?

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/64932892-ee799300-d87c-11e9-9b9e-51ac8de9f321.png)

Here's an example. Wherever truncation occurs there should be a tooltip showing the full content. @Joehuu where are you seeing truncation where you expect this?

**Comment by Joehuu** [comment]
Should be every truncated text. Right now in lazer, it's only chat channels and username.

I was going implement truncation on direct titles, and other places temporarily until the moving text (https://github.com/ppy/osu/issues/3504#issuecomment-425780613) is implemented.
