### ISSUE TITLE
Allow skin (and skin settings) to be defined per ruleset

### ISSUE THREAD

**Issue by Craftplacer** [ppy/osu#6124]
*I tried to ask the same question in the COE lazer stream but failed to phrase it correctly, so I re-submitted it with more details.*

**Describe the new feature:** 
You would see a button next to the option like skin or background dim. Clicking it would expand the option with each game mode. These options will be applied with the game mode the user is currently playing with.

Behavior A: The options won't show "*various*" but an indicator (maybe an asterisk/star?) but the some modes will show "*inherited*" or "*default*".

Behavior B: The options show "*various*" and you have to set the options for each mode manually.

**Proposal designs of the feature:** 
![image](https://user-images.githubusercontent.com/22963120/64921256-5d91b180-d7c1-11e9-8b1a-ec6a9d81f87f.png)
![image](https://user-images.githubusercontent.com/22963120/64921324-55864180-d7c2-11e9-838c-a896fabace09.png)

This feature would be practical for me when I want a Taiko No Tatsujin looking osu! when playing osu!taiko, a simple skin for osu! and a futuristic looking one for osu!mania.

Also, the same with background dim since the background doesn't bother me too much except playing standard.

**Comment by LeNitrous** [comment]
I suggest the design be similar to how keybindings per-ruleset are handled in Settings for a streamlined design.

**Comment by Craftplacer** [comment]
> I suggest the design be similar to how keybindings per-ruleset are handled in Settings for a streamlined design.

That would require making a sub side panel wouldn't it?

**Comment by peppy** [comment]
Per-ruleset skin settings are already planned.

**Comment by Craftplacer** [comment]
> Per-ruleset skin settings are already planned. Design feedback is not required at this point.

Does that only include skins though?

**Comment by peppy** [comment]
Yes. And skins inherently include all settings.

**Comment by MLisDreaming** [comment]
I'm gonna make the argument that this should also be able to apply to different osu!mania keycounts. Mainly because, in full honesty, (not even mentioning including other keycounts) osu!mania 4k and osu!mania 7k are treated as two different rulesets (to the point of having separate OWCs) so it would make sense to allow separate skins here. Treating it just like how it is treated in the input settings.

**Comment by peppy** [comment]
This is already how we have things setup internally. Rulesets have variants and settings can be defined at that level.

**Comment by peppy** [comment]
Tracking via https://github.com/ppy/osu/issues/22388.
