### ISSUE TITLE
Changing the volume during gameplay/in the results screen causes lag

### ISSUE THREAD

**Issue by reflect-git** [ppy/osu#6129]
**Describe the bug:** 
Changing the volume with the scroll wheel while in the results screen lags/freezes the game. How much it lags appears to be directly related to the length of the beatmap. 
On a 12 second beatmap, there is a spike on the update graph but no noticeable slowdown.
On a 1:27 beatmap, there are major slowdowns.
On a 4 minute beatmap it hangs for seconds after stopping the intense scrolling

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=gEq3Ngf18jY
12 second map lag is at 0:44 
1 minute 27 second map lag is at 7:22
4 minute map lag is at 5:15
Game settings are at 7:45

**osu!lazer version:** 
2019.913.0

**Comment by peppy** [comment]
This will be fixed via DrawableHitObject pooling. We could consider a temporary fix but it wouldn’t resolve the fact that the same lag can be felt during gameplay, not jut at the results screen.

**Comment by smoogipoo** [comment]
Will be resolved through #6136

**Comment by Joehuu** [comment]
Resolved by pooling.
