### ISSUE TITLE
osu!taiko controls for iOS osu!lazer

### ISSUE THREAD

**Issue by Meowstuffs** [ppy/osu#6130]
**Describe the new feature:** 

Instead of using an external keyboard or controller, you would instead be able to tap on the screen to play osu!taiko

**Proposal designs of the feature:** 

You would be able to tap on different areas of the screen to hit either Don or Ka
(sorry for the bad ms-paint)
![taiko ios controls](https://user-images.githubusercontent.com/35438740/64928260-3ea01900-d7db-11e9-9222-913b05c87004.png)

**Comment by bdach** [comment]
Virtual controls (that of course won't look anything like the above) are planned for all rulesets and oftly-requested, have a look at #4195 and #4201 for more info.
