### ISSUE TITLE
Some tests make the game crash and freeze

### ISSUE THREAD

**Issue by elleyer** [ppy/osu#6133]
**Describe the crash:** 
Some tests (Intro triangles and disclaimer) freeze/crash osu!
**Screenshots or videos showing encountered issue:** 
https://streamable.com/e8b2k
**osu!lazer version:** 
Latest(test)
**Logs:** 
Exception, thrown with disclaimer freeze and crash : 
[disclaimer.txt](https://github.com/ppy/osu/files/3615357/disclaimer.txt)
Exception, thrown with Intro freeze and crash : 
[Triangles.txt](https://github.com/ppy/osu/files/3615358/Triangles.txt)
**Computer Specifications:** 
G4560,
16GB RAM,
RX 470
I'm not sure this issue should be reported in this repository (probably it should be osu!framework).

**Comment by peppy** [comment]
You are getting some very weird errors on these tests. Are you sure you don't have local changes? Can you run osu! fine in non-test mode?

**Comment by elleyer** [comment]
Yes, I'm sure and yes, I can. I thought the same, but just downloaded and opened a new repository, so there are no local changes.
https://streamable.com/sdnrk

**Comment by smoogipoo** [comment]
I can't replicate the triangles crash at all.

**Comment by elleyer** [comment]
@smoogipoo , You could watch this full video. https://streamable.com/7t05r

**Comment by BlauFx** [comment]
Can reproduce it:
https://streamable.com/u7lzb
log:
[runtime.log](https://github.com/ppy/osu/files/3620800/runtime.log)

**Comment by peppy** [comment]
I *think* this is fixed?

**Comment by bdach** [comment]
Since it's been 3 days without any protest let's just close for now. Please comment if this is still an issue and we'll reopen.
