### ISSUE TITLE
DrawableHitObjects should be pooled and re-used

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#6136]
The `Drawable` representations of `HitObject`s should be re-used by multiple `HitObject`s, based on the lifetime of the `HitObject`s.

This is going to resolve most/all performance issues during gameplay.

**Comment by peppy** [comment]
Dropping back to candidate; work on editor will be prioritised first.

**Comment by bdach** [comment]
Do we want to close this one yet, or possibly use it for tracking remaining work for other rulesets?

**Comment by peppy** [comment]
I'd probably close it and open a tracking issue per ruleset if anything.
