### ISSUE TITLE
Exiting osu!editor makes osu! greet player again

### ISSUE THREAD

**Issue by Philosoph228** [ppy/osu#6139]
It is just planned? Turning back from non-overlayed screen (ex. editor) to the title screen makes narrator say "Welcome to osu!" again, but I'm here, already in game.

osu!lazer 2019.913.0
Windows 7 SP1 x64

**Comment by elleyer** [comment]
That's because "Welcome to osu!" intro and "trieangles" song aren't split. 
![image](https://user-images.githubusercontent.com/41483607/65026279-e97e1780-d940-11e9-8c5a-72920d1ad34e.png)

**Comment by Philosoph228** [comment]
Ok then. Maybe, split this sound and bgm? Or it's not so important?

**Comment by smoogipoo** [comment]
It's intended for now. Triangles/Circles should not be editable but the Editor doesn't have a beatmap selection screen yet either.
