### ISSUE TITLE
Editor action history

### ISSUE THREAD

**Issue by gidra5** [ppy/osu#6143]
The idea is to log events during mapping process like creating, moving, copying etc., linking properties and displacement of copied objects to their parents and allowing for fast changes across the map or preserving relations between objects without manually adjusting them.

This feature have great implementation in Autodesk Fusion 360 and provides great flexability in desing, which i miss while desinging maps.

**Comment by peppy** [comment]
You touch on multiple concepts here, some of which are not related to "history". We are still far off having a working editor so it is too early to discuss "linking properties" or similar, but we do have plans on implementing action history in a more useful way than undo/redo.

**Comment by Craftplacer** [comment]
So osu! keeps a relative history of actions and recalculates the beatmap when you do a change in the past?
