### ISSUE TITLE
Particles are not implemented

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#6149]
**Describe the bug:** 
My skin "tranquil sublimity" isn't getting rendered properly. My "100" and "50" images aren't appearing and I don't get the aesthetic of my skin from stable.

**Screenshots or videos showing encountered issue:** 
*Stable:*
![screenshot083](https://user-images.githubusercontent.com/32044067/65096008-58835c80-d991-11e9-8cc6-446a51f4c5b5.jpg)
*Lazer:*
![osu_2019-09-17_19-07-12](https://user-images.githubusercontent.com/32044067/65096023-6b962c80-d991-11e9-8d14-836cc1ae2701.jpg)

**Skin File:**
[tranquil sublimity.zip](https://github.com/ppy/osu/files/3623994/tranquil.sublimity.zip)

**osu!lazer version:** Latest

**Logs:** (not required)

**Comment by AqilCont** [comment]
Try it out in both stable and lazer, and you will see the difference. I would love to have full osu skin support on lazer as soon as possible because I sometimes like playing in Lazer.

**Comment by peppy** [comment]
Looking at the files in your skin, all your 100 and 50 sprites are empty. So they will not display. Could you provide some more information on what you think is incorrect? It's looking pretty good to me.

**Comment by AqilCont** [comment]
Sorry, I had to take some things out before uploading so it would fit the required file size... Should I give you the whole skin folder?

My 100s and 300s animations aren't showing at all, plus the hit animation image isn't showing either. All that was showing was misses, sliders, approach circles, and hit circles.
(Hit animation image, if you are confused by what I mean)
![screenshot085](https://user-images.githubusercontent.com/32044067/65191749-fd11a700-da42-11e9-8cee-3a2d7297150b.jpg)

**Comment by AqilCont** [comment]
Also, my 100s and 50s sprites all appear in osu! stable... so I don't know what you mean by empty.

**Comment by AqilCont** [comment]
![screenshot090](https://user-images.githubusercontent.com/32044067/65192214-4e6e6600-da44-11e9-842c-fe711b34f1eb.jpg)
This is my 100 animation. Its basically yellow exploding yellow particles. My 50 animation looks just like this except its blue.

**Comment by bdach** [comment]
To clarify here: your 100 and 50 sprites actually *are* empty, as in they're completely transparent PNG files, but your 100 and 50 *particles* are not.

Particles are not yet implemented, as noted in #6013. I guess this issue could stay open if it was scoped down to just that part.

**Comment by AqilCont** [comment]
Ohhh, I see.. I was looking through my skin file wondering about that too. I did find the particle50 and particle100 and realized that those were the actual particle images.

**Comment by peppy** [comment]
Particles are one of the few remaining pieces missing in legacy skinning. Will be added back soon (if anyone is interested, stable implementation details can be provided).

**Comment by AqilCont** [comment]
Thanks for implementing them! This makes lazer all the more playable :D
