### ISSUE TITLE
skin.ini or skin.xml in the future

### ISSUE THREAD

**Issue by Malavolence** [ppy/osu#6153]
1. Some text-based options for the skins are currently saved in skin.ini
    Will this ever be changed to a skin.xml or something like that

2. Currently in FooterButton[Name].cs: 
    `SelectedColour = colours.[color];`
    This could be changed to a option in the skin.ini to change the color.

**Comment by ticotaco72** [comment]
In future everything will be saved in database I think. If so, this issue can be closed

**Comment by peppy** [comment]
Skin export format is not yet defined, and we're still a long way off from this. Closing in favour of https://github.com/ppy/osu/issues/6084.
