### ISSUE TITLE
Mods checkbox above score leaderboard (possibly) inverted

### ISSUE THREAD

**Issue by NickDuijndam** [ppy/osu#6163]
**Describe the bug:** 
The 'Mods' checkbox above the score leaderboard in the song select screen is unchecked when the mods are shown and checked when the mods are not shown. To me it seems that this behavior should be reversed. Is this true or is this done by design?

**Screenshots or videos showing encountered issue:** 
<img width="914" alt="osu!_3fwAtmByMD" src="https://user-images.githubusercontent.com/16774572/65183863-a6b56000-da64-11e9-83c4-1dec5bf7d7d4.png">
<img width="918" alt="osu!_Sgmfdqr4WT" src="https://user-images.githubusercontent.com/16774572/65183864-a6b56000-da64-11e9-81bf-f860764355d5.png">

**osu!lazer version:** 2019.913.0

**Logs:** N/A

**Comment by iiSaLMaN** [comment]
The purpose of that checkbox is to allow you to filter leaderboard scores by the mods you are currently selecting, which is web's mod filtering behavior.

**Comment by NickDuijndam** [comment]
Ah it does work like the web version. But yeah it's a little misleading the way it is now, changing the text would make it a bit more clear.

**Comment by revelsix** [comment]
I believe it should be a `Selected Mods` button instead, to make it a bit less ambiguous. 
P.S. I'm trying to solve this issue but am having problems with Visual Studio ;-;

**Comment by peppy** [comment]
Probably depends on https://github.com/ppy/osu-web/issues/4674.

**Comment by iiSaLMaN** [comment]
> Probably depends on [ppy/osu-web#4674](https://github.com/ppy/osu-web/issues/4674).

Do they? that issue is about the web's current behaviour with mods filtering while this issue talks about misleading checkbox name?

**Comment by peppy** [comment]
Renaming to "Selected Mods" should be done, too.
