### ISSUE TITLE
Confirm Exit Dialog sends the user to an empty screen

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#6173]
**Describe the bug:** The Confirm Exit Dialog sends you to an "empty" screen, where the only thing you can do is.. exit the game.

**Screenshots or videos showing encountered issue:** https://streamable.com/9gijp

**osu!lazer version:** 2019.919.0

**Logs:** [runtime.log](https://github.com/ppy/osu/files/3632351/runtime.log)

**Comment by peppy** [comment]
is this via alt-f4?

**Comment by Gabixel** [comment]
From the Main Menu yes, works fine. This seems to happen with `Alt+F4` or using the `X` button, same scenario for both cases.

**Comment by Gabixel** [comment]
Note that by the `X` button I mean the Windows' one, not the in-game "Exit" button in Main Menu.

**Comment by iiSaLMaN** [comment]
I cannot reproduce this with 0 delay and `Alt+F4` on song select?

**Comment by iiSaLMaN** [comment]
Nevermind, this can be reproduced by doing `Alt+F4` or using the `X` button on the window and then cancel the dialog (pressing `Just a little more`).
