### ISSUE TITLE
HTML entities not displayed correctly in Changelog Overlay

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#6174]
**Describe the bug:** HTML entities like quotations marks are not displayed correctly in-game in the changelog overlay.

**Screenshots or videos showing encountered issue:** 
Lazer:
![Lazer](https://user-images.githubusercontent.com/43073074/65265801-03bb1f80-db12-11e9-86e3-d24d803e4b49.png)

web:
![web](https://user-images.githubusercontent.com/43073074/65265814-0f0e4b00-db12-11e9-94bc-8532845434d3.png)

**osu!lazer version:** 2019.919.0

**Comment by Game4all** [comment]
Looks like strings are being escaped in the JSON payload but not being unescaped lazer-side
