### ISSUE TITLE
Enable slider ball tint for legacy skin

### ISSUE THREAD

**Issue by Malavolence** [ppy/osu#6176]
At least for me in 2019.919.0 the `AllowSliderBallTint = 1` doesn't have any effect yet.

Looking at the code the only reference I found to SliderBall was in OsuSkinColour.cs, if that property fixes this please tell me which value it needs.

**Comment by peppy** [comment]
Hasn't been implemented yet.

**Comment by iiSaLMaN** [comment]
Can this title be changed to `Implement slider ball tinting` or similar?

**Comment by smoogipoo** [comment]
Seems like this has regressed.

**Comment by iiSaLMaN** [comment]
Don't see any regression on latest master?

**Comment by peppy** [comment]
I don't believe this has regressed; it's just the legacy skin which hasn't turned it on.

![image](https://user-images.githubusercontent.com/191335/71049046-a07a7100-2184-11ea-8fa1-8fa468ae399c.png)
