### ISSUE TITLE
The lenght of the songs aren't showed

### ISSUE THREAD

**Issue by SuperFat-Fat** [ppy/osu#6182]
I'm using the latest version of osu : 2019.919.0 and there's a bug since... Always.
Anyway, the bug is : The lenght of the songs aren't showed in the song selection screen. For EVERY song.

If more details are needed, i'll reply.

**Comment by iiSaLMaN** [comment]
what do you mean by not shown, all contain `0:00`? if so, reimport your beatmaps because a database change occurred and affected length column. (see #5376)

**Comment by SuperFat-Fat** [comment]
Okay, i'm gonna try right now.

**Comment by iiSaLMaN** [comment]
This can be closed then.

**Comment by Joehuu** [comment]
Closing as resolved.
