### ISSUE TITLE
Key counters going negative on some beatmaps

### ISSUE THREAD

**Issue by starsgaze** [ppy/osu#6198]
**Describe the bug:**  after skipping and then it freezing i pressed the keys to warm up and got a negative input...

**Screenshots or videos showing encountered issue:** 
![Screen Shot 2019-09-20 at 2 35 49 PM 1](https://user-images.githubusercontent.com/42686995/65354053-33226880-dbb4-11e9-93ee-2f8cb011189d.png)

**osu!lazer version:**  2019.919.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3637466/database.log)
[network.log](https://github.com/ppy/osu/files/3637467/network.log)
[performance.log](https://github.com/ppy/osu/files/3637468/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3637469/runtime.log)

**Comment by iiSaLMaN** [comment]
Can you replicate this anytime or does it happen suddenly? if anytime, giving us the beatmap and what you did exactly is much helpful.

**Comment by starsgaze** [comment]
This happens with a few beatmap and doesnt happen suddenly on this beatmap, https://osu.ppy.sh/beatmapsets/332673#mania/736490 around 63% on any difficulty auto does not do this for some reason. ( when it occurred the last time i had on half time.)

**Comment by peppy** [comment]
This sounds like it could have something to do with beatmaps using negative bpm or something equally weird?

**Comment by starsgaze** [comment]
Yup, this doesn't happen in any other mode

**Comment by starsgaze** [comment]
@peppy ive recently tried to watch Centipede and this bug happens with that map too, its not an osu mania thing.

**Comment by peppy** [comment]
A video would be super helpful. Also based on it being centipede, there's a chance it also has weirdly broken control points too.
