### ISSUE TITLE
Ghost Beatmaps

### ISSUE THREAD

**Issue by floomster** [ppy/osu#6199]
**Describe the bug:**  After deleting a map from solo it still appears as if you still have it downloaded in multi

**Screenshots or videos showing encountered issue:** 
![Screen Shot 2019-09-20 at 3 09 34 PM](https://user-images.githubusercontent.com/42686995/65355960-db3a3080-dbb8-11e9-85e6-c6ac617f750e.png)

**osu!lazer version:**  2019.919.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3637560/database.log)
[network.log](https://github.com/ppy/osu/files/3637561/network.log)
[performance.log](https://github.com/ppy/osu/files/3637562/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3637563/runtime.log)

**Comment by peppy** [comment]
Beatmaps are soft deleted, which means they are not truly deleted until a restart. Maybe from a UX perspective we should pretend it's gone in this case.

**Comment by starsgaze** [comment]
^ Ignore

**Comment by peppy** [comment]
Tracking in https://github.com/ppy/osu/discussions/16558.
