### ISSUE TITLE
Stutter when starting a song on IOS

### ISSUE THREAD

**Issue by vlee489** [ppy/osu#6200]
When starting a song on the **iPad Pro 2018** , as the ring approaches the first slider/circle to be clicked on there's an issue where the game will momentarily stutter and freeze with the music still playing and then continue from where it is on the song. 

This issue doesn't look to exist of the PC build of osu!Lazer `2019.919.0` 

videos showing the encountered issue: https://photos.app.goo.gl/pzkzU9MFzkTQKYKc7

osu!lazer version: IOS Testflight `2019.919.0`

Device Used: 2018 iPad Pro 11" 64gb, Apple Pencil 2

Logs: *I'm not sure how to get a log off the iPad version. If given instructions I can probably get them.*

**Comment by vlee489** [comment]
Note: The video recording is done with IOS native recording, however, the recording doesn't affect the appearance of the bug in any way.

**Comment by iiSaLMaN** [comment]
Out of curiosity, does this happen on any beatmap or just this one? can you check whether this issue happens on the first slider or on any object?

**Comment by vlee489** [comment]
This issue exists on any beatmap on the regular osu! mode, the other 3 modes aren't affected by this bug. It only affects the first hit object/slider in the song. But the game feels to still be looking for input on that object/slider being hit at what feels like the correct timing. 

Here's 2 more video of the bug on 2 different beat maps, one for a slider and one for a hit object.
1. [Slider](https://photos.app.goo.gl/3xQm924JTkSmYmt38)
2. [Hit Object](https://photos.app.goo.gl/bnZK5vfagGRynLSy7)

Just as an extra point this issue didn't exist in the last testflight release.

**Comment by iiSaLMaN** [comment]
> It only affects the first hit object/slider

Keep in mind `Hit Object` is any object that can be hit (hit circle, slider, spinner).

> Just as an extra point this issue didn't exist in the last testflight release.

You mean 2019.913.0?

**Comment by vlee489** [comment]
> Keep in mind Hit Object is any object that can be hit (hit circle, slider, spinner).
My bad, sorry

> You mean 2019.913.0?
Yeah, there is still a stutter, but it not anywhere as noticeable as in `2019.919.0`.
Here's a recording from `2019.913.0` to show what I mean. (*I'm using assistive touch with a mouse to make it easier to see where my "curser" is*) https://photos.app.goo.gl/RcXC25C4QnNBBhxx9

**Comment by peppy** [comment]
This is likely the framebuffer creation for sliders. That said, if it's something which just started it may be unrelated and require further investigation. On a quick test of `2019.919.0` (on same hardware) I can't seem to reproduce.

**Comment by vlee489** [comment]
I forgot to mention I'm also on the iPad OS 13 beta. But I don't know how much that changes this problem. 

Are there any instructions for building the IOS version so I can try and slide load it via my Macbook?

**Comment by peppy** [comment]
It should just-build (visual studio). If you're not aware of the build process, building it is not going to give us any advantage over testflight releases.

**Comment by vlee489** [comment]
I was thinking if I could run the program with a visible log output like from Rider. 

Cause when the stutter happens, the FPS counter also stutters along with it, so I don't think it's just the framebuffer creation for sliders.

**Comment by peppy** [comment]
FPS counter is rendering with the game. If there is a stutter it will stutter too.

**Comment by Joehuu** [comment]
Closing as stale. @vlee489 please let us know if this still happens on the current release.
