### ISSUE TITLE
Focus on Most Recent Difficulty When Opening a Beatmap

### ISSUE THREAD

**Issue by OrangeC7** [ppy/osu#6201]
**Describe the new feature:** When opening a beatmap in the beatmap selection area, automatically open to the most recent difficulty or recommended difficulty for the user, instead of the easiest difficulty. There could also be a setting (either in settings and/or the beatmap list) that lets you toggle between those three. Just a small quality-of-life feature. :D

**Comment by bdach** [comment]
Partially overlaps with #5172 scope-wise.

**Comment by peppy** [comment]
This has since been implemented!
