### ISSUE TITLE
Database undeletions don't work correctly in tests

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#6204]
[`TestImportWithDeletedBeatmapSet`](https://github.com/ppy/osu/blob/db90d211cba2efaf4befe14553c56b32cc861674/osu.Game.Tests/Scores/IO/ImportScoreTest.cs#L121) should fail on https://github.com/ppy/osu/commit/c99b48f9342189ba0290702893fbdcc1a7b72f2f , but doesn't. It is also likely that tests within `ImportBeatmapTest` are also inadequate as they don't test the `DeletePending` flag post-undeletion.

Investigation:
1. [`DeletePending = false`](https://github.com/ppy/osu/blob/c99b48f9342189ba0290702893fbdcc1a7b72f2f/osu.Game/Database/MutableDatabaseBackedStore.cs#L91) does get hit.
2. Removing the [detached state check](https://github.com/ppy/osu/blob/c99b48f9342189ba0290702893fbdcc1a7b72f2f/osu.Game/Database/DatabaseBackedStore.cs#L28) from `Refresh` doesn't help.
3. Forcing a DB update via `usage.Context.Update(item);` does not help.
4. Querying the database via `context.Find(item.ID)` _does_ return an item with `DeletePending = false` as expected.
5. Sqlite does not seem to detect changes to the model internally - as if the model which it is reflecting `DeletePending` on is different to the one which we set `false` to. This also means that EF+Sqlite do not save changes to the database file - `DeletePending` remains `true`.
6. Turning off the multithreaded flag in `OsuDbContext` does not help.

This may be an issue with thread-local contexts, but has not been tested to that point yet.

**Comment by peppy** [comment]
Should be resolved with realm.
