### ISSUE TITLE
Menu progression keyboard shortcuts don't work to enter menu from osu! logo

### ISSUE THREAD

**Issue by reflect-git** [ppy/osu#6207]
**Describe the missing feature:** 
Pressing valid keyboard shortcuts (p for play, d for osu!direct, e for editor etc) while in the title screen (the one with just the logo and nothing else) will not progress the menus. Once you press enter or spacebar to get to the main menu will they work normally. 

ESC does not clear the beatmap search bar, instead it goes back to the main menu.

Hold-to-confirm activation setting affects both going to the menu in-game and quick-reset. In stable, the menu was instant but quick-reset had a delay.

**Proposal designs of the feature:** 
If these aren't intentional behavior changes, these should be brought over from stable.
 
**Notes**
Personally, I am very used to launching stable and pressing "p" 3 times to go to beatmap select.

Interestingly enough, ESC does clear the search bar in osu!direct. If the search bar is clear, it will go back to the main menu. On stable's osu!direct however, ESC goes straight back to the title screen regardless of if the search bar is empty or not. I'd say it behaves worse on stable.

Regarding the hold-to-confirm behavior, I'd argue they deserve to have different timings. 
The menu button serves as a pause button, so no delay means you pause exactly where you want to and a situation where you didn't pause because you didn't hold down the key long enough doesn't happen.
The quick-reset button delay however prevents accidental presses from resetting your current progress. Unlike with a pause button, the delay isn't a problem as you weren't going to resume anyways. Accidental presses can happen when quick-reset is bound to be near something else. For me quick-reset is on tilde, so I've definitely had a situation where both ESC and tilde get pressed.
I realize this can be solved by just changing keybinds to be further away, but it's worth proposing in my opinion.
 
**osu!lazer version**
2019.919.0

**Comment by peppy** [comment]
#1 should be addressed
#2 is a regression which will be fixed via https://github.com/ppy/osu/pull/5501
#3 is intentional and will remain that way.

I'm going to rename this issue to track the first one.
