### ISSUE TITLE
Unable to re-summon iOS keyboard if osu!direct search bar is selected

### ISSUE THREAD

**Issue by Criticaldiamonds** [ppy/osu#6209]
**Describe the bug:** 
When the "hide keyboard" button is pressed in osu!direct with the search box selected, you are unable to re-summon the keyboard without tapping outside the search box to deselect it first.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/k32gd

**osu!lazer version:** 
2019.919.0

**Comment by swoolcock** [comment]
Not sure what could be done about this other than forcing a `becomeFirstResponder` when tapping a text field.  Generally dismissing the keyboard means you don’t want the keyboard.

**Comment by peppy** [comment]
Either that, or change these focused textboxes to allow rescinding focus in certain scenarios (when "nothing" is tapped, ie. empty space).

**Comment by peppy** [comment]
(or completely removing the focus mechanism of `FocusedTextbox`es on mobile)

**Comment by swoolcock** [comment]
When manually hiding the keyboard on iOS, I believe the system will automatically `resignFirstResponder`.  We could pass this on to the framework to drop the focus on the text field, which would give a similar user experience.

**Comment by peppy** [comment]
Oh right, I just realised we already handle this scenario for taps away. So yeah, that sounds like the best resolution by far.

**Comment by Joehuu** [comment]
Duplicate of #5284.
