### ISSUE TITLE
custom cursor trail decreases fps significantly

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#6212]
**Describe the bug:** using a custom cursor trail decreases my fps significantly. i have without recording around 250 fps (cursor trail off) and around 60-70 fps when the cursor trail is enabled.
keep in mind that the default cursor trail from the osu!classic and osu!lazer skin doesnt change my fps at all.

**Skin:**
[Unknown.zip](https://github.com/ppy/osu/files/3640151/Unknown.zip)

**Beatmap:**
 https://osu.ppy.sh/beatmapsets/115729#osu/298880

**Screenshots or videos showing encountered issue:** 
https://streamable.com/eo3ok

**osu!lazer version:** 
2019.919.0

**Specs:**
CPU: i5-4440
iGPU: intel hd graphics 4600
RAM: 8GB

**Logs:** 
[logs.zip](https://github.com/ppy/osu/files/3640149/logs.zip)

**Comment by peppy** [comment]
Seems very weird. Cursor trail implementation is quite optimised and shouldn't cause any drop.

**Comment by mouzedrift** [comment]
seems weird but the longer you move the cursor the lower the fps get. the fps drop again once you start moving your cursor for a while. it looks like it kinda sticks to 60 fps so i cant really decrease it further (maybe related to the monitors refresh rate?) 

i made a second video that shows that my decreased fps are kinda "stable" if i dont move my cursor and it starts decreasing again if i move it: https://streamable.com/4eyk6

**Comment by bdach** [comment]
I did some rudimentary testing on my hardware yesterday (my notebook has double graphics cards - an Intel HD Graphics 530 and an NVIDIA GeForce GTX 960M). When running on the GTX toggling the attached trail had zero impact on rendering performance, while the Intel card dropped about ~20 fps (from 80-ish to 60-ish). So this might be a low-end card issue, or even an Intel-specific one.

Unfortunately I don't have any details yet - need to figure out how to force Visual Studio to use the integrated card when profiling.

**Comment by iiSaLMaN** [comment]
> Unfortunately I don't have any details yet - need to figure out how to force Visual Studio to use the integrated card when profiling.

Have you tried disabling the other card in Device Manager?

**Comment by mouzedrift** [comment]
i dont have any noticeable lags when i use a smaller image for the cursor trail.
might be related to #6246 ?

**Comment by turbedi** [comment]
I did a quick test on my computer (i5 4590, GTX 1060 3GB)
2 runs on the same map with NF on. One without cursor movement and one with cursor movement.
The FPS difference was pretty big for me (about 30%), so I did some profiling with VS and it actually seems to be an issue.
[Without cursor movement](https://i.imgur.com/pN2MZPw.png)
[With cursor movement](https://i.imgur.com/SRBjDrA.png)
I can provide some more tests if necessary.

**Comment by peppy** [comment]
those results require context. 30% change in fps means nothing if it's 10,000fps to 7,000fps, for instance.

**Comment by turbedi** [comment]
It dropped from 1700-800 FPS to ~1000 FPS

**Comment by peppy** [comment]
that's a change of under 0.5ms per frame. update? draw? both?

**Comment by mouzedrift** [comment]
i just checked the latest build and the fps drops are gone. 
can anyone else confirm?

**Comment by bdach** [comment]
It'll probably be due to #7229 coming in.
