### ISSUE TITLE
Mis-aligned beat bar in mania mode

### ISSUE THREAD

**Issue by cthbleachbit** [ppy/osu#6215]
**Describe the bug:** 

Falling beat hint lines in mania mode are not aligned with actual beat nor the falling notes (with correct timing of course). The beatmap used in the screenshots is [787919](https://osu.ppy.sh/beatmapsets/787919#osu/1653685), but the issue isn't limited to this one only.

**Screenshots or videos showing encountered issue:** 

* Missing beat hint bars and later misaligned ones at commit `af3bb5a2c`
![osu_2019-09-23_00-02-45](https://user-images.githubusercontent.com/3353318/65402809-4bea7400-dd96-11e9-963f-74f191ab17d5.png)

* Correct display of beat hint bars at commit `fc7e8dcbf1`
![osu_2019-09-23_00-00-18](https://user-images.githubusercontent.com/3353318/65402821-5b69bd00-dd96-11e9-8b56-55ced6f9f0ba.png)

**osu!lazer version:** 

The issue was discovered on git master, at the time of writing, `9fe7675be81`. I attempted git bisect and I think the issue is introduced with commit `af3bb5a2c` and merge request #6054.

**Logs:** 
[network.log](https://github.com/ppy/osu/files/3640679/network.log)
[performance.log](https://github.com/ppy/osu/files/3640680/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3640681/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3640683/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3640685/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3640686/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3640687/runtime.log)

**Comment by bdach** [comment]
After analysis, af3bb5a introduced two changes to bar line generation in mania:

* Before, bar lines were generated on every beat:
https://github.com/ppy/osu/blob/2bc64cd6e1dcf09a35103b9c85bfb0e39b387177/osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs#L63-L70
If I understand the terminology correctly, the commit changed the generation to generate a bar line on every *new measure*:
https://github.com/peppy/osu/blob/af3bb5a2cdf7084cc14a988a0610e636438ad4fc/osu.Game/Rulesets/Objects/BarLineGenerator.cs#L44-L53
In taiko bar lines were generated every new measure too, so no regression there:
https://github.com/ppy/osu/blob/2bc64cd6e1dcf09a35103b9c85bfb0e39b387177/osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs#L76-L81
* The other change, more severe, was moving out `DrawableBarLine` out from the ruleset-specific projects into `osu.Game`. This meant that the new `DrawableBarLine` could no longer inherit from `DrawableManiaHitObject`, and unfortunately the base mania hitobject sets appropriate anchoring depending on scrolling direction, leading to the incorrect alignment:
https://github.com/ppy/osu/blob/e1ed5dfa7d50807809f13ad85121ff2962e8d510/osu.Game.Rulesets.Mania/Objects/Drawables/DrawableManiaHitObject.cs#L44-L47
I (incorrectly and temporarily) re-applied `Anchor.BottomCentre` to the extracted bar line and that fixed alignment.

For a visual summary, you can look at [this comparison video](https://streamable.com/pjqc8). Left - commit before regression, upper right - current `master`, lower right - `master` with my band-aid fix.

I'm pretty sure this will show up on almost any beatmap without fail.

@peppy If you're not going to end up reverting, I can try to take a shot at this - unless you'd rather take this yourself.

**Comment by smoogipoo** [comment]
Yeah I knew this was the case when I merged the original PR.

**Comment by peppy** [comment]
The rate of bar lines is not a regression – the change was intentionally made to match stable (was not previously matching).
