### ISSUE TITLE
Add custom DoubleTime offset slider in settings

### ISSUE THREAD

**Issue by ackhack** [ppy/osu#6218]
**Describe the new feature:** 
A lot of Player play with a custom offset for DT (-20ms). So adding another offset Slider for DT would safe Players some Time changing their offest everytime they play DT.

**Comment by peppy** [comment]
This sounds so wrong. Why would you add a custom offset?

**Comment by ackhack** [comment]
i feel more comfortable playing with -20ms with DT, like some better DT Players do aswell.

**Comment by peppy** [comment]
If this is a bug with audio speed changing then it should be fixed in code. Please confirm that the audio is adjusted incorrectly and we can consider making a change.

Any other reason is not valid.

**Comment by ackhack** [comment]
no, audio is fine, just feels more comfortable with an offset.
