### ISSUE TITLE
Differing scores between Multi and Solo

### ISSUE THREAD

**Issue by floomster** [ppy/osu#6221]
**Describe the bug:**  Score shows ~800,000 is lower than my multi score 234,851. (peppy is cheating me out of a good score)

**Screenshots or videos showing encountered issue:** 
![osu_2019-09-23_10-04-17](https://user-images.githubusercontent.com/42686995/65438260-d2c93c00-ddea-11e9-9dbd-f018c8936ad0.jpg)
![osu_2019-09-23_10-04-26](https://user-images.githubusercontent.com/42686995/65438261-d2c93c00-ddea-11e9-8519-27589a6fc40f.jpg)

**osu!lazer version:** 2019.919.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3642815/database.log)

[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3642817/performance-gamethread.audio.log)

[performance-gamethread.update.log](https://github.com/ppy/osu/files/3642820/performance-gamethread.update.log)

[runtime.log](https://github.com/ppy/osu/files/3642821/runtime.log)

**Comment by starsgaze** [comment]
Classic, that might be the problem.

**Comment by Aergwyn** [comment]
I think that multiplayer lobbies always displays as standardised at the moment.

**Comment by starsgaze** [comment]
OK, thanks.

**Comment by peppy** [comment]
Is there an issue open for this? Because it should probably be fixed at some point.

**Comment by Aergwyn** [comment]
Please keep it open. Unless otherwise stated by those with more insight I do believe that the numbers should adjust.

**Comment by bdach** [comment]
I guess #5350 would fit the bill here?

**Comment by iiSaLMaN** [comment]
I guess https://github.com/ppy/osu/issues/5417 is the most related issue here.

**Comment by smoogipoo** [comment]
This should no longer be an issue since we're recomputing scores on the fly now.
