### ISSUE TITLE
Not to support legacy mania skins in part

### ISSUE THREAD

**Issue by RBRat3** [ppy/osu#6228]
There are sprite layout issues in stables mania mode that I don't wish to be transposed into lazer due to increasing the bar of entry to skinning mania and to help keep the codebase less convoluted while also providing a prosperous architecture for textured based skinning for lazer.

Stables mania skinning is built around an original default skin to where it ignores texture sizes at face value without an input from the skin.ini such as "ColumnWidth:". you can test this yourself by making a key and note at any width as long as they're the same and you wont get the result you created in your software package. This creates a problem as it requires guesswork on the skinners part to input the required value for "ColumnWidth:" in order to obtain a square pixel ratio of 1:1. To add also for instance if your special key and note happens to share the same width but different from others well even if you set it up right you'll never get your notes height corrected, "WidthForNoteHeightScale:" can correct it but this doesn't work on a per key/lane basis.

What im asking is for the original mechanics as to how manias textured sprites are handled to not be carried over into lazer, I'd like manias textured sprites to be rebuilt from the ground up.

**Comment by peppy** [comment]
Skinning in lazer is being completely reworked, but all legacy skins will still be supported. The code is split into two discrete paths so there is no chance of polluting things in a negative way.
