### ISSUE TITLE
Taiko beatmaps skip at the beginning

### ISSUE THREAD

**Issue by memesnightmares** [ppy/osu#6242]
**Describe the bug:** 

Whenever I start a beatmap in taiko mode, it skips a bit for the first few seconds. This is slightly reduced when I spam keys.

**Screenshots or videos showing encountered issue:** 

[Here's a video (sorry for the low quality, but it shows the issue) (it's also zipped because github wouldn't let me upload a video file)](https://github.com/ppy/osu/files/3647840/osu.zip)

**osu!lazer version:** Since I started using lazer

**Logs:**

**Comment by bdach** [comment]
Looks similar in symptom to #5933, except perhaps not as severe and triggered on first hitobject instead of on loading screen. Possibly another issue that is going to be resolved when hitobject pooling (#6136) comes in?

By the way, do you mind listing your hardware specs, just for extra info?

**Comment by bdach** [comment]
Thanks for the info. Pooling is most likely going to be used in multiple places, and it's definitely not a straightforward change - it will require more discussion and will also end up being implemented by one of the core contributors who have extensive experience with the codebase.

**Comment by peppy** [comment]
It's probably related to first load of textures (or FBOs in the case of sliders), which pooling alone will not fix.

In stable, we found that on some GPUs we had to blit textures to a framebuffer once in order to fully transfer them to GPU memory. There was actually a method specifically doing this before startup. In lazer this has not yet been addressed but will need to be at some point.

**Comment by peppy** [comment]
@memesnightmares does this still happen for you on recent releases?

**Comment by memesnightmares** [comment]
Yes, but to a much lesser degree. It varies, but it feels like it's usually under 100ms.

**Comment by memesnightmares** [comment]
Actually, I just opened it up again and it appears to be fixed! There's still a slight sub-100ms pause at the start of most songs, but that's almost certainly a different issue. Thank you for fixing this!
