### ISSUE TITLE
Add ability to leave sub settings by clicking tab item

### ISSUE THREAD

**Issue by scatteredf** [ppy/osu#6244]
**Describe the bug:** 
When you configure your key bindings you have a sub menu that appears that lets you choose a game mode or the global key bindings. I don't know if it's a bug or even worth mentionning but you can't get out of this menu without clicking on the "Back" or by clicking outside of the menu. You can't go back to the main options by left clicking on the main bar on the left. The only way I found to do this is by right clicking between the 2 menu bars on the left with my right mouse button.

**Screenshots or videos showing encountered issue:** 

https://www.youtube.com/watch?v=abRrnd5BfkY&feature=youtu.be

**osu!lazer version:** 

2019.919.0

**Logs:** 
I don't know where to get them or if it's needed in this case

This is my first time submitting a "bug" and I really don't know if it's worth or if it's even important. And sorry for my bad english i'm french.

Edit : I realised it's not really a bug, it's more of a quality of life improvement.

**Comment by EVAST9919** [comment]
"Esc" works just fine and I personally don't see any problems with that.

**Comment by swoolcock** [comment]
> "Esc" works just fine and I personally don't see any problems with that.

Mobile (usually) does not have "Esc", so I agree with this suggestion.  Currently the only way to get out of a submenu on mobile is by tapping the dimmed area.

**Comment by EVAST9919** [comment]
And back button too.
But yeah, I didn't take into account touch devices

**Comment by swoolcock** [comment]
> And back button too.
> But yeah, I didn't take into account touch devices

iOS devices do not have a back button.

**Comment by EVAST9919** [comment]
I mean this one
![Screenshot_1](https://user-images.githubusercontent.com/22874522/70388318-1b8f9a80-19c1-11ea-8214-2fe47f6f67ec.png)

**Comment by Joehuu** [comment]
Seems to be resolved in https://github.com/ppy/osu-framework/pull/5118.
