### ISSUE TITLE
Back button spamming sounds in fullscreen mode

### ISSUE THREAD

**Issue by Nickelony** [ppy/osu#6247]
**Describe the bug:** 
When the mouse cursor is moving at the lowest point of the screen underneath the "Back" button in **fullscreen mode**, the button starts spamming sounds.

**Screenshots or videos showing encountered issue:** 
![kw92r2JeWM](https://user-images.githubusercontent.com/20436882/65550814-baf3d400-df20-11e9-8515-152cef8724f0.gif)

**osu!lazer version:** 
2019.919.0

**Logs:** 
None.

**Comment by Gabixel** [comment]
This seems to happen also with other UI elements (like `Notifications` button). Could this be related to https://github.com/ppy/osu/issues/4216 because of the 1px issue? (https://github.com/ppy/osu/issues/4591)

**Comment by mouzedrift** [comment]
hmm that doesnt happen when raw input is enabled

**Comment by Luxiono** [comment]
I don't have any real knowledge on this stuff, but I assume that the normal cursor (when raw input is off)  messes up the reactions with the game's cursor. It seems that it alternates between checking if the game's cursor is touching and checking the normal cursor. It seems to be a single pixel at the bottom where the game cursor can't go but the normal one can, it very quickly alternates between a `Touched` state and `Untouched` state. 

You need to either add the last pixel to the game's mouses' confines or get rid of that last pixel.

This is really the only thing I can come up with. Also, this hasn't been updated in a while.

**Comment by Joehuu** [comment]
This is similar to https://github.com/ppy/osu/issues/18159, but closing this instead as that one has a repro comment.
