### ISSUE TITLE
Options dropdowns are hard to see with main menu dimmed.

### ISSUE THREAD

**Issue by Szwagi** [ppy/osu#6251]
**Describe the bug:** Main menu gets dimmed when options are opened. The already dark dropdowns are hard to spot.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/12988954/65558237-da452e00-df2d-11e9-90fe-307685fc6d34.png)

**osu!lazer version:** 2019.919.0

**Logs:**

**Comment by smoogipoo** [comment]
This will be addressed by future redesigns of the game in its entirety, in a similar fashion to https://github.com/ppy/osu/issues/2434. The sidebars are going to have some sort of opaque background as per current designs, but design is still WIP.

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu/pull/15020.
