### ISSUE TITLE
osu!mania doesn't register misses at high scroll speeds

### ISSUE THREAD

**Issue by Baumstyler** [ppy/osu#6252]
Dunno if already reported but most Osu!mania Notes are getting ignored when missing them with scrollspeed 50 , sliders are working.

Video:
https://youtu.be/vP2gY7rSDlk
in the other diff of this track are some single notes that are still registering.

osu!lazer version: 2019.919.00

Logs if needed:
[Logs.zip](https://github.com/ppy/osu/files/3650602/Logs.zip)

**Comment by smoogipoo** [comment]
This affects any scrolling rulesets since their lifetime ends are determined by the parenting container. We likely don't want this in the first place and let DHOs handle their own lifetimes
