### ISSUE TITLE
Some Searchbar filters missing + other small stuff.

### ISSUE THREAD

**Issue by Baumstyler** [ppy/osu#6253]
Dont looked at all filters but From a fast lookup: 

The mode= command (Ex. Mode=Osu!mania) isnt working.
The Keys= Keys< and Keys> (Ex. Keys>3  keys<7) commands arent working x_x
The Stars= Command isnt working,while Stars> or < are working.

OTHER:

I think the manage collections button is missing from beatmaps in selectscreen, at least i didnt found it.
 
cant access beatmap modding community page for beatmaps from map-select screen with lazer build while possible in stable via the quick web access button.

In settings are still too much settings than im willing to count not in lazer.

**Comment by bdach** [comment]
* The mode filtering doesn't really make a lot of sense in lazer now that beatmaps are separated by gamemode in the top header.
* Key filtering was already proposed in the past (see #3906). I'm not sure if there's anything blocking an implementation of it right now, might check and add it if there isn't.
* Can you be more specific as to how does the `stars` command not work? I'm pretty sure it should work alright even on the last release (without #6206), but I feel you might be expecting it to do something different than how it's implemented right now.

As for the other stuff (which should really be in a separate issue):

* Collections support is not yet implemented, but is on the to-do list (see #988).
* Beatmap modding links might be superseded by an implementation of #5379.
* Some settings might be pending implementation (e.g. in the skin area), while some might not return. Please search the issues for what you're missing, it might be already on the waiting list or declared to be a dropped feature. If you find nothing, feel free to open an issue and we'll decide how to proceed.

**Comment by Baumstyler** [comment]
1. - True,totally forgot that.

2. - Nice

3. - its a very unimportant issue, when searching for only a specific starrate (ex:  stars=4 ) it doesnt find anything ,was no problem in stable see https://youtu.be/jkKuV46QdFg
i dont think anyone really needs to find a map with an exact rating,  just found it weird that my one of my searchbar macros gave me 0 results in lazer.

as for the other points
 - i just didnt felt like open other issues rn since there are enough big fixes to do before anything of this is becomes important if ever and just wanted to throw it somewhere in.

**Comment by bdach** [comment]
A fix for equality filters has been merged in #6206 and will be deployed in the next release. I tested on one of your maps and you should get at least one result after it. Note however that lazer's star ratings in mania are currently not always the exact same as stable's.

**Comment by smoogipoo** [comment]
Since the main issues were fixed, I'm going to close this. The "other" issues are non-issues.
