### ISSUE TITLE
Specified key count when searching for mania maps. (osu!direct)

### ISSUE THREAD

**Issue by SheepeyDarkness** [ppy/osu#6254]
**Describe the new feature:** 

Simply either a drop-down menu or a command such as key=4 for osu!direct to filter maps based on key count. 
In the case that a map set has maps that are 7k and 4k, the user has a bubble ( similar to that of free mods in multi ) that can be selected to exclude all maps for that are not in the specified key range when downloading. 

Ex. If bubble is selected mapset would still show that there are indeed 7k maps in the mapset, but said maps would not be downloaded.

I do know this is for osu!lazer. I am not sure what the ui for it is at the moment, although whatever the osu!lazer equivalent of a bubble is would be nice.

**Comment by bdach** [comment]
Note that this feature request concerns direct; a similar one for song select was made in #5668.

Adding more filters to direct in general might be worth considering, however it is up for consideration if we want to do it using song select-like filters, or something more like web's beatmap advanced search criteria.

**Comment by Joehuu** [comment]
Added in https://github.com/ppy/osu-web/pull/7300.
