### ISSUE TITLE
Virus total detected an PUA file

### ISSUE THREAD

**Issue by phileas0408** [ppy/osu#6259]
https://www.virustotal.com/gui/file/f1620dfa2dd248b39e45ce61ff7e840589559cee1479bf54f2016012755eb4ed/details
here is the result, its weird because nothing changed on my computer

**Comment by bdach** [comment]
Downloaded latest release installer from github and ran through `sha256`:
```
$ sha256sum.exe install.exe
f1620dfa2dd248b39e45ce61ff7e840589559cee1479bf54f2016012755eb4ed *install.exe
```
Checksum matches, so I'd wager it's a false positive. I very much doubt anyone here is trying to pass malware around. Possibly that one engine flagged some malware using squirrel and now flags everything that uses it.

**Comment by peppy** [comment]
Please mark as a false positive and move on. Builds happen on a secured server and there is zero chance of infection.
