### ISSUE TITLE
Osu! scroll speed vs. Lazer scroll speed (Mania)

### ISSUE THREAD

**Issue by Nick-77ab2** [ppy/osu#6263]
**Describe the new feature:** 
Well, when changing the scroll speed in lazer it just moves the notes closer together and doesn't really change the "speed" of the notes like Osu! trying to hit the notes feels like i'm just playing at standard scroll speed with the notes closer together. The new feature would give the user the opportunity to choose the way they want their scroll speed.
**Proposal designs of the feature:** 
give a drop down before the scroll speed option on whether you want to use Osu! scroll speed or Lazer scroll speed

As there are so many issues, i realize that there is a chance that this has been stated. I searched for this, or if I happened to miss an option that changed the actual speed like Osu. I apologize ahead of time if this is so.

**Comment by peppy** [comment]
I think you must be confused. "closer together" *is* changing the speed. it has to be.

**Comment by Nick-77ab2** [comment]
Technically you could make the options "Note distance" and "note speed"

**Comment by smoogipoo** [comment]
> notes can move fast and be further apart, notes can move slow and be closer together

Yes, that's what speed is.

> "Note distance" and "note speed"

The distance between notes is inherently tied to speed.

**Comment by Nick-77ab2** [comment]
it feels nothing like osu!mania from osu! it's basically unplayable, that's why i made this post.
