### ISSUE TITLE
Visual problems in osu!editor when music is paused

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#6268]
**Describe the bug:** I don't know how to reproduce the issue 100% of the time, but it seems to happen when scrolling through the timeline while the music is paused.

**Screenshots or videos showing encountered issue:**

- Video: https://streamable.com/xgrlt (the beatmap in the video is [The Pretender - by Infected Mushroom](https://osu.ppy.sh/beatmapsets/79498#osu/221777), but it seems to happen with any map)

- Screenshot:
![image](https://user-images.githubusercontent.com/43073074/65631464-e2f23e80-dfd7-11e9-8733-629549dd885a.png)

**osu!lazer version:** 2019.925.0

**Comment by smoogipoo** [comment]
Duplicate: https://github.com/ppy/osu/issues/5995
