### ISSUE TITLE
Latest song starts anyways after entering on an empty search  

### ISSUE THREAD

**Issue by SusieDroid** [ppy/osu#6271]
**Describe the bug:** 
Hi I'm new to this community and I really love the  game. I noticed that after a search without results, the latest song starts anyways if I press enter. I don't know if it is a real issue or just a default action but it would be nice to catch the event and notify the user about their action. I only tried in solo mode. Thanks!

**Screenshots or videos showing encountered issue:** 
![aa](https://user-images.githubusercontent.com/55773786/65650066-a0ccfb00-dfdf-11e9-95a8-7760ba4c16cd.gif)

**osu!lazer version:** 
stable 20190924.2

**Comment by Altenhh** [comment]
Please open this issue into [osu-stable-issues](https://github.com/ppy/osu-stable-issues) other than here, this is only for osu!lazer related issues.
