### ISSUE TITLE
Allow mods to have their own settings

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu#6272]
**Describe the new feature:** Allow mods to be customized with their own settings. For instance: https://github.com/ppy/osu/issues/4391, https://github.com/ppy/osu/issues/4175 and https://github.com/ppy/osu/issues/3201

Creating this issue for visibility as well as to discuss the implementation details.

**Proposal designs of the feature:** Create a new interface `IModHasSettings` which is different from `IReadFromConfig` as that persists through sessions and also an added benefit to avoid the need of creating new options and ending up cluttering the settings sidebar.

Mod settings will be found a sidebar alongside Input Settings and Visual Settings before starting the map. It's contents will be created from `IModHasSettings` method that should return a new drawable (or better yet implement a new class like `PlayerSettingItem` for streamlining) and the values of those controls will be read by the mod.

Mod settings will by dynamically created when we reach `PlayerLoader` depending on the mods selected

Current Implementation (Rate Mod as example)
![image](https://user-images.githubusercontent.com/20495991/65656387-4751e400-e052-11e9-875e-8b57f3566147.png)

**Comment by peppy** [comment]
This sounds exactly in line with what we eventually have planned. Are you going to attempt to undertake this?

**Comment by LeNitrous** [comment]
I will. I just made an issue just to confirm on how the implementation should go.

**Comment by smoogipoo** [comment]
@arflyte have a design for mod settings?

On the topic of structure, I think the best way forward is to make a settings object. Currently the structure of multiplayer room mods is:
```
{
    "acronym": "DT",
    "settings": []
}
```

Which isn't gonna work well. We'll probably want something like:

```
{
    "acronym": "DT",
    "settings": {
        "rate": 2
    }
}
```

**Comment by LeNitrous** [comment]
It would be probably best to move those settings beside the mod select overlay. It will definitely overflow past screen boundaries when used with other mods that have settings and also mods should apply changes **before** `PlayerLoader`.

**Comment by arflyte** [comment]
I don't have anything in mind for mod settings for now, but that example seems fine. We can go with that. What other crazier settings you can imagine for mods?

**Comment by Craftplacer** [comment]
Considering there are rate settings, wouldn't it make sense to replace or merge DT, NC and Wind Up?

**Comment by abraker95** [comment]
It makes more sense to make them presets.

**Comment by Craftplacer** [comment]
> It makes more sense to make them presets.

We're about to hit a new stage of osu! mods.
