### ISSUE TITLE
Crash After few seconds on Android !

### ISSUE THREAD

**Issue by SuperFat-Fat** [ppy/osu#6276]
I'm using the latest osu version (2019.259.0), and I wanted to try the Android version !

After like 10-15 in the menu, an error happen and osu crashes.
(On BlueStacks, osu does exactly the same thing)

[network.log](https://github.com/ppy/osu/files/3656888/network.log)
[performance.log](https://github.com/ppy/osu/files/3656889/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3656890/runtime.log)

**Comment by smoogipoo** [comment]
Duplicate: https://github.com/ppy/osu/issues/6264
