### ISSUE TITLE
Keyboard called at startup

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#6282]
**Describe the bug:** On Android (specifically my tablet; my phone doesn't have this issue), the keyboard opens as the game starts every time, for no apparent reason.

**Screenshots or videos showing encountered issue:** https://streamable.com/hn2vc

**osu!lazer version:** 0.1 / 2019.925.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3659587/database.log)
[network.log](https://github.com/ppy/osu/files/3659588/network.log)
[performance.log](https://github.com/ppy/osu/files/3659589/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3659590/runtime.log)

**Comment by peppy** [comment]
Please include details of device and OS. Cannot reproduce on any test device we've tested on.

**Comment by smileyhead** [comment]
Ah, sorry.
I have a Huawei BAH2-L09 running Android 8.0.0 (the stock, skinned one; build number `BAH2-L09 8.0.0.217(OCEC432)`)

**Comment by HoLLy-HaCKeR** [comment]
Happens to me on my Huawei P8 Lite (PRA-LX1), running Android 8.1.

**Comment by iiSaLMaN** [comment]
Cannot reproduce on Huawei Y9 2018 (Android 9.1).
