### ISSUE TITLE
Random intro sequence

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#6284]
**Describe the new feature:** Seeing as the Circles intro with its song is still in the game and can be chosen if desired, how about adding a random option in the dropdown so that both can be used at the same time and for a bit of variety? ~~Hell, maybe even add more sequences in the future, or support for custom ones?~~

**Proposal designs of the feature:** 
![image](https://user-images.githubusercontent.com/15932372/65720890-37192380-e0a9-11e9-9896-24a3e8800414.png)

**Comment by V1ntagezTV** [comment]
#6310
