### ISSUE TITLE
Crash when pressing the back button on android

### ISSUE THREAD

**Issue by miterosan** [ppy/osu#6285]
Pressing the back button crashes osu!android

Error:
````
Mono	Loading reference 7 of /storage/emulated/0/Android/data/sh.ppy.osulazer/files/.__override__/osu.Framework.Android.dll asmctx DEFAULT, looking for System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
ziparchive:	Unable to open '/data/app/sh.ppy.osulazer-MecxcqS_vHOPt8BrYgvj7A==/base.apk': No such file or directory
m.lge.launcher	Failed to open APK '/data/app/sh.ppy.osulazer-MecxcqS_vHOPt8BrYgvj7A==/base.apk' I/O error
ResourcesManager	failed to add asset path /data/app/sh.ppy.osulazer-MecxcqS_vHOPt8BrYgvj7A==/base.apk
PackageManager	Failure retrieving resources for sh.ppy.osulazer
DDTIcon	getIconDrawableAsIconFrameTheme got null as icon. Replace it to default one for sh.ppy.osulazer
InputDispatcher	channel 'f851d8b sh.ppy.osulazer/md59c875562ee5070384021e1e981f7bd4e.OsuGameActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
InputDispatcher	channel 'f851d8b sh.ppy.osulazer/md59c875562ee5070384021e1e981f7bd4e.OsuGameActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
ActivityManager	Process sh.ppy.osulazer (pid 29186) has died: fore TOP 
````

Mobile: lg g7 thinq

**Comment by peppy** [comment]
the log shows nothing useful. this is likely your phone returning to home screen and killin the process (as intended)?

**Comment by miterosan** [comment]
osu.Framework.Tests.Android does not close when you press the onscreen back button. In osu.Framework.Tests.Android pressing the android onscreen back button just triggers the opentk ESC key.

Currently we handle the back button press. 

The only way that the app may be closed when pressing the back button is that somewhere Environment.Exit is called.

**Comment by bdach** [comment]
While that might be true, your issue doesn't have a reproduction scenario or a log that would help pinpoint the cause (at least I don't see anything), so unless your intent is to handle this yourself I can't tell how anyone else is supposed to even attempt to fix this.

**Comment by miterosan** [comment]
The problem is that there is not a proper stacktrace anywhere for this.
Also the .Destroy of the view is never called.

I will try to find the reason for this issue, but I cannot guarantee anything.

**Comment by miterosan** [comment]
Not a crash. The error is unrelated
