### ISSUE TITLE
[macOS] Tablet not working with Raw input 

### ISSUE THREAD

**Issue by skorotkiewicz** [ppy/osu#6290]
My tablet is an XP-Pen Deco 03. I connected it to my computer, then turned on raw input. When I tried to use my tablet, nothing happened. The cursor wouldn't move or click.
I tried adjusting sensitivity and switching screen modes, but nothing happened either.

Tablet works properly on Windows 10 with raw input.
On MacOS tablet works properly without raw input.

MacBook Pro version Mojave 10.14.5
osu!Lazer 2019.925.0
![Screenshot 2019-09-27 at 11 51 22](https://user-images.githubusercontent.com/899351/65760436-4e91f400-e11d-11e9-80a0-3ffc11eaea6f.png)

**Comment by peppy** [comment]
macOS doesn't support raw input (there's no such API). We've disabled this in recent versions, so this should no longer be an issue.
