### ISSUE TITLE
Additional randomization

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#6296]
**Describe the bug:** when you start osu up and wait for end of traingles song, and then random song starts, and then when you go into song select it opens on new random map not on the one that was playing before

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2019.925.0

**Logs:**

**Comment by bdach** [comment]
I can't seem to reproduce on 2019.925.0, mind uploading a video or sharing more details as to how did you notice this?

**Comment by ticotaco72** [comment]
maybe i missaw something because i can't reproduce it too. i thought that i saw one song in music player and entered song select and diffrent showed up. maybe the first song just ended. sorry
