### ISSUE TITLE
Wind up and down effects not always playing in song select

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#6298]
**Describe the bug:** music sometimes isn't speeded up or down when wind up or wind down mods are turned on.
steps to reproduce:
1. chose wind up/wind down
2. enter beatmap
3. let it start and go for a few seconds
4. go out of gameplay
5. switch to other difficulty/ beatmap to hear the diffrence

**Screenshots or videos showing encountered issue:** 
https://streamable.com/ck79o

**osu!lazer version:** 2019.925.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3664290/database.log)
[network.log](https://github.com/ppy/osu/files/3664291/network.log)
[performance.log](https://github.com/ppy/osu/files/3664292/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3664293/runtime.log)

**Comment by Gabixel** [comment]
I think logs are not needed. Anyway, the mods' effect **is** playing, but it seems like there's an issue with the pitch level (or how it's called in the code), like if it does not update/return to its initial level when exiting the beatmap (at any moment), but only changing mods/difficulty/beatmap.

**Comment by ticotaco72** [comment]
yeah, that's what i meant

**Comment by LeNitrous** [comment]
This happens due to "ApplyToClock" not running when coming back from the Player. Just my two cents.

**Comment by iiSaLMaN** [comment]
> This happens due to "ApplyToClock" not running when coming back from the Player. Just my two cents.

I don't think "ApplyToClock" has anything to do with this, Check it's usage.
