### ISSUE TITLE
Minimum System Requirements

### ISSUE THREAD

**Issue by recognitionmark** [ppy/osu#6302]
What does osu!lazer android need to run smooth in minimum requirements? My phone is a Samsung Galaxy Tab A 2016, bundled with 12GB of storage, and 2GB of memory. Please make lazer mobile more suitable for low-end devices, if possible.

**Comment by iiSaLMaN** [comment]
Why don't you try it yourself?

**Comment by recognitionmark** [comment]
I've tried so, and it ran horribly.

**Comment by recognitionmark** [comment]
Also my OS is Android Nougat, 7.1.1.

**Comment by iiSaLMaN** [comment]
Do other games work smoothly on your device? if not, then this isn't really an issue in our game.

**Comment by recognitionmark** [comment]
Other games actually run smooth in my device, the thing is it lags hell, even audio came first before visual.

**Comment by Denver323** [comment]
tried it on my vivo which is a budget phone, Samsung a5-midrange, Sony C5-midrange and a Samsung Note 5-2015 flagship. The note 5 launched the game fastest but running the game all of them lag and heat up in the same manner. I saw someone with the same problem on a S8 which is a 2017 flagship. Might try it on the note 9 next.

**Comment by bdach** [comment]
Please note that at the current time the APK Android release is an added bonus, not a priority for the dev team. Overall performance improvements *will* be coming (to desktop as well as mobile), but Android-specific issues will not be resolved until the game is functionally complete, unless there are external contributions from the community that improve the state of the Android version.
