### ISSUE TITLE
Show current time and how long osu is running

### ISSUE THREAD

**Issue by LanTenDragon** [ppy/osu#6303]
**Describe the missing feature:** On stable, the first and second screen header shows how many beatmaps you have, what is the current time and also the duration osu has been running. 

**Proposal designs of the feature:** 
1. On laser, this should behave similarly (to stable) on the main menu screen
2. Also be available on the song select screen, but remain hidden until being hovered by mouse

**Comment by peppy** [comment]
I plan to have a statistics section (likely in settings) with this plus other game information listed.

**Comment by iiSaLMaN** [comment]
> I plan to have a statistics section (likely in settings) with this plus other game information listed.

Should be fairly easy once #6216 is merged. I'll take a look at it.

**Comment by LanTenDragon** [comment]
> I plan to have a statistics section (likely in settings) with this plus other game information listed.

I would disagree, IF all statistics are buried to the bottom of the settings. Should be fine if just time is immediately visible (at the top) while other information are at the bottom.
