### ISSUE TITLE
Missing graphics on AMD 760G GPU

### ISSUE THREAD

**Issue by Swampergonner** [ppy/osu#6313]
**Describe the bug: 
![image](https://user-images.githubusercontent.com/55937529/65826324-e7a34500-e2ac-11e9-822f-5da9ee67af9f.png) how to fix that?
** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:**

**Comment by peppy** [comment]
please provide details on your system specs and your runtime.log

**Comment by Swampergonner** [comment]
![image](https://user-images.githubusercontent.com/55937529/65826597-166fea00-e2b2-11e9-8ed9-735dd09dc4d8.png)

Процессор = Processor

ОЗУ = RAM

Гб = Gb

**Comment by mouzedrift** [comment]
what about your GPU and the runtime log?
just press the <kbd>windows</kbd>+<kbd>r</kbd> key and paste ``%appdata%\osu\logs`` in there to open the osu logs directory.

**Comment by Swampergonner** [comment]
About runtime log: 
![image](https://user-images.githubusercontent.com/55937529/65826922-dcedad80-e2b6-11e9-9747-1926cd6028f2.png)

![image](https://user-images.githubusercontent.com/55937529/65826926-e7a84280-e2b6-11e9-8b98-bb1c1d053d56.png)

About gpu: idk how watch my gpu

**Comment by mouzedrift** [comment]
## heres a short version of his pc specs:

**OS:** Windows 7 Ultimate
**CPU:** AMD FX-4300
**RAM:** 4GB
**GPU:** AMD 760G

also, please attach logs instead of taking screenshots. (drag and drop it into the text box)

**Comment by TheComputerGuy96** [comment]
@mouzedrift The GPU name is misleading, because the 760G northbridge doesn't support FX CPUs

I think the motherboard has a 980G northbridge

**Comment by Swampergonner** [comment]
@mouzedrift i dont have that

**Comment by Swampergonner** [comment]
@mouzedrift okay, im found it: AMD 760G

**Comment by TheComputerGuy96** [comment]
> @mouzedrift okay, im found it: AMD 760G

What's inside of Display adapters (Видеоадаптеры) in Device Manager (take a screenshot as well)?

You can open Device Manager by pressing Win+R, typing "devmgmt.msc" and pressing Enter

**Comment by Swampergonner** [comment]
> > @mouzedrift okay, im found it: AMD 760G
> 
> What's inside of Display adapters (Видеоадаптеры) in Device Manager (take a screenshot as well)?
> 
> You can open Device Manager by pressing Win+R, typing "devmgmt.msc" and pressing Enter

![image](https://user-images.githubusercontent.com/55937529/65829384-48437980-e2cf-11e9-9b2e-9e01631d5ef1.png)

**Comment by iiSaLMaN** [comment]
Can this title be changed, please?

**Comment by smoogipoo** [comment]
Have you tried updating your GPU driver?

**Comment by Swampergonner** [comment]
> Have you tried updating your GPU driver?

that doenst work (okay, my english sucks)

**Comment by smoogipoo** [comment]
Please do the following:
1. Press WinKey+R
2. Type "dxdiag"
3. In the window that opens, click "Save All Information..."
4. Post it here.

**Comment by Swampergonner** [comment]
![image](https://user-images.githubusercontent.com/55937529/66314878-ee7e2780-e93e-11e9-9483-9f8f180b8eff.png)

**Comment by smoogipoo** [comment]
Your driver is 5+ years old. You need to update it before we can investigate further: https://www.amd.com/ja/support/chipsets/amd-7-series-chipsets/760g

**Comment by Swampergonner** [comment]
> Your driver is 5+ years old. You need to update it before we can investigate further: https://www.amd.com/ja/support/chipsets/amd-7-series-chipsets/760g

Im download new drivers, and again missed graphic

**Comment by smoogipoo** [comment]
@Swampergonner please check if it's fixed in osu!'s latest release

**Comment by peppy** [comment]
Closing as stale for now.
