### ISSUE TITLE
Normal osu! multiplayer

### ISSUE THREAD

**Issue by StarZorroww** [ppy/osu#6314]
Bring back the old osu! multiplayer where you can verse others instead of playing the map whenever you want, also bring back the readying aspect so no the host can't start till everybody's ready.

**Proposal designs of the feature:** <---- idk what this means..

**Comment by Game4all** [comment]
Please note that multiplayer is a WIP and for the time being , only the new timeshift mode has been implemented. AFAIK versus games like on stable are planned but haven't been implemented yet so please be patient.

**Comment by StarZorroww** [comment]
> 
> 
> Please note that multiplayer is a WIP and for the time being , only the new timeshift mode has been implemented. AFAIK versus games like on stable are planned but haven't been implemented yet so please be patient.

thanks so much for the reply, means a lot to know that this is going to be implemented.
