### ISSUE TITLE
Cursor/Cursortrail setting

### ISSUE THREAD

**Issue by Axeanz** [ppy/osu#6317]
I change cursors and cursortrail pretty often, so I usually make a file in my skinfile full of cursors, but I still don't like to have to go all the way into 3 files(because you can't use a file named 'cursor(2).png' as a cursor, I have to make files seperating them so I don't need to rename them everytime), just to change cursors.

Possible settings I'd love to see in the menu:
- ''Activate CursorMiddle", so you don't have to go into your files just to put in 'cursormiddle.png' for a long trail.
- "Change color", giving the cursor a setting to change color with RGB numbers, just like in the 'skin.ini' with combocolors and such.
- "Allow cursorrotate/cursorexpand", a setting that will change the values from 'skin.ini' cursorrotate and expand without having to go there manually to change them.

They're ofcourse not needed to make the game more playable, but it's a pain to go deep into the skinfiles just to change cursors. I also don't like having 7 skins named Axeanz' (color). I have enough skins without the color-seperation.

**Comment by bdach** [comment]
`skin.ini` value modifications would probably fall within the scope of #4924.

**Comment by peppy** [comment]
Yep. A full skin editor is coming which will allow control over all settings, too.
