### ISSUE TITLE
DragBar should not exist

### ISSUE THREAD

**Issue by peppy** [ppy/osu#632]
We should be using SliderBar instead

**Comment by jai-sharma** [comment]
Since `DragBar` is used in two places (MusicController and SongProgress), would it be better to replace it with a general "song seeking bar" class to be used in both places or use a custom class in each case?

**Comment by MrTheMake** [comment]
I assume this can be closed as it is revolved via https://github.com/ppy/osu/pull/966.

**Comment by peppy** [comment]
Resolved by #966
