### ISSUE TITLE
Beatmap import priority when importing from stable

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#6322]
**Describe the issue** 
If you have beatmap import from stable running in the background, then the map downloaded from osu!direct will be at the bottom of that list (next task which will only run when the import from stable is finished). It could result in a really long wait for user to get the map from direct. The same applies for skins but it's not that important there since well, you can't download skins from direct (at least as long as osu!themes is not a thing)

**Comment by peppy** [comment]
Known issue which we will eventually tackle.

**Comment by peppy** [comment]
Closed via https://github.com/ppy/osu/pull/11802.
