### ISSUE TITLE
Storyboard moves even if paused

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#6324]
Describe the bug: storyboard moves while Lazer is paused with this beatmap https://osu.ppy.sh/beatmapsets/236697 (i dont know about other beatmaps) regardless of mode

Screenshots or videos showing encountered issue: https://streamable.com/9myho

osu!lazer version:2019.925.0 

Logs:
[performance.log](https://github.com/ppy/osu/files/3668440/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3668441/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3668442/updater.log)
[database.log](https://github.com/ppy/osu/files/3668443/database.log)
[network.log](https://github.com/ppy/osu/files/3668444/network.log)

**Comment by EVAST9919** [comment]
Happens only with looped animations

**Comment by EVAST9919** [comment]
Works okay in the TestScene, happens in-game only.

**Comment by enoslayd** [comment]
apparently this solved????
