### ISSUE TITLE
Pressing Back Button kill the game not back to previous menu (Android)

### ISSUE THREAD

**Issue by HerendraTJ** [ppy/osu#6325]
**Describe the bug:** 
**Expected Behavior:**
When pressing back button will back to the previous menu
**Reality:**
Pressing back button will kill the game.
**Solution:**
Please make pressing the back button willl go to the previous menu. Thanks For the attention

**Screenshots or videos showing encountered issue:** 
https://youtu.be/mTrdI9_D_Po

**osu!lazer version:** 
2019.925.0

**Logs:** 
No Logs

**Comment by bdach** [comment]
Will be resolved by #6321.

**Comment by Optimalgitit** [comment]
A simple fix to it would be to map the back button to the ESC button.

**Comment by LittleEndu** [comment]
It already is mapped to ESC for mobile, it just doesn't work correctly on android.

**Comment by HerendraTJ** [comment]
This issue will close when ppy/osu-framework#2877 is merged

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu-framework/pull/2877.
