### ISSUE TITLE
low end computers lag on osu lazer 

### ISSUE THREAD

**Issue by recall296** [ppy/osu#6326]
**Describe the new feature:** can you make low graphics for low end computers as osu! lazer lags my laptop and the normal osu works well and it would be good for others who have low end pc's or laptops that have low spec

**Comment by bdach** [comment]
Overall improvements in that area are planned, check out the _performance_ tag for examples of concrete issues that are already known.

However please refrain from opening non-specific issues like the above. Without describing what specifically is the problem it is impossible to know whether or not it is fixed later on.

**Comment by smoogipoo** [comment]
Performance is a constant work in progress.
