### ISSUE TITLE
uso lazer lags my pc 

### ISSUE THREAD

**Issue by recall296** [ppy/osu#6327]
i have a low end pc specs are 
CPU amd a9-9420 dual core
8bg of ram
GPU amd radeon (TM) 530
windows 10 
and it lags on every part and can't play maps as the frame rate drops to like 20 but i should be able to get 80fps as that's my hz but GPU usage goes to 100% and same with CPU but with normal osu it goes to 60-80% usage same with CPU is there anyways to mix it so it doesn't lag when i play?

**Comment by smoogipoo** [comment]
As I mentioned before, performance is a continuous work in progress. Further issues do not need to be opened on this.
