### ISSUE TITLE
Incompatibility with MSI vendor software resulting in freeze

### ISSUE THREAD

**Issue by MuTong233** [ppy/osu#6328]
**Describe the bug:** 
osu! won't run when I click the icon on the desktop.It will show the first screen then go blank with a version.
![snap](https://user-images.githubusercontent.com/34769123/65876670-61762400-e3bc-11e9-9a69-a7190cdc6e4b.png)

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.925.0 and 2019.917.0 and more...
**Logs:** 
No log file I've found

**Comment by MuTong233** [comment]
ok,it crashed after a few minutes.And it won't start anymore.Here is the log.
[logs.zip](https://github.com/ppy/osu/files/3670940/logs.zip)

**Comment by iiSaLMaN** [comment]
Do you hear any sound on the game? You can't proceed anywhere if nothing is playing, which is an issue already opened I believe.

**Comment by MuTong233** [comment]
> Do you hear any sound on the game? You can't proceed anywhere if nothing is playing, which is an issue already opened I believe.

No,it just went blank and nothing will happened.

**Comment by MuTong233** [comment]
I recorded a video for some troubleshooting.
https://youtu.be/C4Ks_T7Oxic

**Comment by iiSaLMaN** [comment]
Can you run this with debug configuration? Would be helpful for us to detect your problem easily.

**Comment by MuTong233** [comment]
> Can you run this with debug configuration? Would be helpful for us to detect your problem easily.

![asa](https://user-images.githubusercontent.com/34769123/65936470-502a2780-e44f-11e9-98b0-3b5e96bbc6cd.png)

**Comment by iiSaLMaN** [comment]
Please attach the logs as you can see it's being limited:
`Console output is being limited. Please check runtime.log for full logs`.

**Comment by MuTong233** [comment]
> Please attach the logs as you can see it's being limited:
> `Console output is being limited. Please check runtime.log for full logs`.

[runtime.log](https://github.com/ppy/osu/files/3674587/runtime.log)
The same as before.

**Comment by iiSaLMaN** [comment]
I don't see any trace of `BASS` being initialized here?

**Comment by MuTong233** [comment]
> I don't see any trace of `BASS` library being initialized here? :/

I've no idea,sorry :(

**Comment by MuTong233** [comment]
> I don't see any trace of `BASS` library being initialized here? :/

It stopped here.I have already waited for an hour but nothing happened.BTW I installed 925 and it could perform an update.But it still shows a blank screen.

**Comment by iiSaLMaN** [comment]
After a bit of investigating, I think that the audio manager somehow hit this:
https://github.com/ppy/osu-framework/blob/master/osu.Framework/Audio/AudioManager.cs#L259

**Comment by MuTong233** [comment]
> After a bit of investigating, I think that the audio manager somehow hit this:
> https://github.com/ppy/osu-framework/blob/master/osu.Framework/Audio/AudioManager.cs#L259

hmmmmm...I reinstalled Windows on another drive and the osu!lazer magically launched without any problem :p Now I really think if there is something wrong with my audio driver :(

**Comment by peppy** [comment]
It would be a good start to add log output at the early return mentioned above. Silent failing is not good.

**Comment by peppy** [comment]
Also could you tell us whether osu! (stable) runs without issue on your system?

**Comment by MuTong233** [comment]
> Also could you tell us whether osu! (stable) runs without issue on your system?

Stable/Beta/CuttingEdge works pretty fine.I tried to reinstall the audio driver but I got the same screen on lazer,it just won't work for some reason.

**Comment by peppy** [comment]
Thanks for confirming. First step forward is to get more log output in framework.

**Comment by MuTong233** [comment]
I think I can reopen a issue because I seems to be found the main issue.

**Comment by bdach** [comment]
Reopening with changed title due to found root cause.

**Comment by MuTong233** [comment]
Forgot it,just a driver issue.The latest version has fixed this problem
