### ISSUE TITLE
osu!lazer won't start at all

### ISSUE THREAD

**Issue by RealTRG** [ppy/osu#6333]
For some reason, when I try to open up osu!lazer, nothing shows up. I have tried multiple ways to open it but it just won't. It shows up in Task-Manager but disappears after a second

**Comment by peppy** [comment]
Please check existing cases of [startup crashes](https://github.com/ppy/osu/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22hard+crash%22) as your issue may already be reported. If not, please reopen with logs from runtime.log or event viewer.
