### ISSUE TITLE
Play from beginning hotkey is missing

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6335]
**Describe the new feature:** A hotkey that will seek to the start of the current song and starts playing it (It's F2 or X key in stable)

**Comment by LittleEndu** [comment]
There are five keys used in stable. F1/Z for last track, F3/C for pause/unpause, F5/V for next track. These three are present in lazer. The next two (one I didn't know of) are missing, F2/X for seek to start and play, F4 for stop and seek to start. 

These are useful to have when searching for beatmaps in the song selection and then wanting to listen to the full song.

**Comment by bdach** [comment]
Some music players use the "previous" key to rewind to the start of the *current* track, and if you press it again in quick succession again, only then it will actually go to the previous track. Might that be a viable substitute for <kbd>F2</kbd>/<kbd>X</kbd>?

The <kbd>F4</kbd> binding seems marginally useful to me, but if the above behaviour was implemented it could be equivalent to pause + rewind.

**Comment by LittleEndu** [comment]
Using previous key as rewind should be a config option. So that it would also apply to just clicking the ⏮️ on now playing overlay

**Comment by bdach** [comment]
Again, spurious addition of more and more config options is detrimental to both development and the end-user. There are plenty of settings already, no need to make more where there shouldn't be.

**Comment by peppy** [comment]
I tend to agree with the above stated logic change, as it is generally the expected UX for a music player these days.

**Comment by peppy** [comment]
https://twitter.com/ppy/status/1181773682898661377

**Comment by GSculerlor** [comment]
I assume the decided behavior will be using prev button to restart and double click prev to jump to previous track, no?

**Comment by smoogipoo** [comment]
Seems that way.
