### ISSUE TITLE
Song player doesn't start playing the next song on android

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6336]
**Describe the bug:** When sitting idle in main menu, when the song finishes playing the next song gets selected but doesn't start playing.

**osu!lazer version:** 2019.930.0

**Comment by bdach** [comment]
I updated to 2019.930.0, left it on idle after the intro, and it seems fine to me - mind giving more details?

**Comment by LittleEndu** [comment]
I'm running this on Xiaomi Redmi Note 5 Pro, MIUI Global 10.3.2, Android 9

Logs didn't seem useful but I'll generate new ones right now.

**Comment by LittleEndu** [comment]
Oh, it seems to happen on the triangles intro too. It just finished while I was downloading another beatmap, the game selected the only beatmap that I have, but didn't start playing it. I can go to the song select screen and see the beatmap selected, it appears in the now playing overlay but is seeked to beginning with a ▶️ instead of a ⏸️

**Comment by LittleEndu** [comment]
Weird, I thought this had a 100% reproduction rate for me but I now have it not happen twice in a row without really changing anything.

**Comment by peppy** [comment]
Could you please provide a screen recording showing this happening?

**Comment by LittleEndu** [comment]
https://youtu.be/CuLqPHrDvVY

This might be beatmap specific. I only got [from under cover](https://osu.ppy.sh/beatmapsets/150739) to not play at the start.

**Comment by peppy** [comment]
I believe this has been since fixed via framework-side bass fixes.
