### ISSUE TITLE
With only one beatmap, android doesn't use triangles as fallback for song player

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6337]
**Describe the bug:** When you have downloaded only one beatmap and the song player finishes playing it, instead of playing triangles, it starts playing the same song again and not from beginning but from preview point.

**osu!lazer version:** 2019.930.0

**Logs:** [logs.zip (google drive)](https://drive.google.com/file/d/11UF6vpx7W1uALakeXKrpn7SZpzu_z0TT/view?usp=drivesdk)

**Comment by LittleEndu** [comment]
This might not be restricted to android. Just finished a play on windows and the song started again. I had direct open so I'm not 100% sure if I was backed out to main menu or still in song select.

**Comment by peppy** [comment]
what are you expecting it to do? i don't quite understand what this is.

**Comment by LittleEndu** [comment]
On Windows when you have only one beatmap the song player will play that to the end and then play the intro song again. I would expect the same thing to happen on Android.

**Comment by peppy** [comment]
The intro song should only ever be played once. If that's happening on windows, that is the true bug.

**Comment by LittleEndu** [comment]
It must have been my old install treating triangles as a beatmap or something. The intro plays only once on fresh install.

As for the track being played from preview point and not from beginning, I can't seem to replicate that either. So I think it's safe to ignore this issue entry for now. Going to close it.
