### ISSUE TITLE
osu!lazer install error

### ISSUE THREAD

**Issue by miloszewski2006** [ppy/osu#6340]
![screen](https://user-images.githubusercontent.com/55999255/65907867-74412680-e3c5-11e9-8fba-14726d3c1bde.png)

osu!lazer version: every

[logs.txt](https://github.com/ppy/osu/files/3672804/logs.txt)

I don't know what to do pls help ;'-(

windows 8.1 64-bit

**Comment by bdach** [comment]
Good thing I'm Polish, so I can read the localised exception messages. The fatal error of the installer seems to be an inability to write uninstaller entries to the registry (relevant message translated below):

```
2019-09-30 20:53:35> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the registry key 'HKEY_CURRENT_USER\Uninstall' is denied.
   in Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   in Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   in Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck)
   in Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
```

This indicates a permission issue. Could you try running the installer with administrator privileges and see if that changes anything?

**Comment by miloszewski2006** [comment]
Niestety próbowełem i nic

**Comment by bdach** [comment]
Even though I can read you, not all the others might be able to - please keep all communications in English.

On a second thought that registry key looks wrong - I had a look at squirrel issues and found Squirrel/Squirrel.Windows#1445, which seems to have exactly the same sympton.

**Comment by miloszewski2006** [comment]
but here is no solution

**Comment by iiSaLMaN** [comment]
Please be patient, the internal issue has not been fixed yet. (Squirrel/Squirrel.Windows#1445)

**Comment by caesay** [comment]
@frenzibyte this can be closed I believe, unless there is still an issue in Clowd.Squirrel that I'm unaware of.
