### ISSUE TITLE
Hold-to-confirm should have a sane minimal value

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6341]
Setting hold-to-confirm to 1ms is functionally identical to 0ms but removes all the confirmations 0ms has. A sane minimal value like 50ms (1/3 the average reaction time of a human) in addition to 0ms should be used.

**Comment by smoogipoo** [comment]
Nothing stops you from setting such a small value though. 0ms is intentional and the confirmations are too. Care to explain further?

**Comment by peppy** [comment]
I think the proposal here is to make the slider's precision higher so values between 0 and 50 are not selectable. This was one concern I did have, and something we may want to consider.

**Comment by iiSaLMaN** [comment]
I think 10ms precision is better.

**Comment by peppy** [comment]
I think you missed the point of this discussion.

**Comment by iiSaLMaN** [comment]
This can go for a good first issue as the solution should be fairly simple.

**Comment by LittleEndu** [comment]
If the design and implementation for such a slider exists, then yeah it's a simple thing to add
