### ISSUE TITLE
Wind-up mod slows Android device down significantly

### ISSUE THREAD

**Issue by Missingno74** [ppy/osu#6347]
Using the wind up mod will cause significant audio and gameplay stuttering. I linked a video below that shows only the gameplay, as I couldn't get the audio to record. Phone is Galaxy S9+ on the latest firmware. Map used below was this one: https://osu.ppy.sh/beatmapsets/1021450#osu/2162144

Video showcasing the issue: 
https://streamable.com/79djw

Version is 2019.9.30, although it occurs on 2019.9.25.

Unsure of how to get the logs.

**Comment by peppy** [comment]
Does the same happen in double time? wind down?

**Comment by LeNitrous** [comment]
Doesn't happen on Xiaomi Redmi 5A.

**Comment by Optimalgitit** [comment]
Either not optimized or OneUI bug.

**Comment by Missingno74** [comment]
Sorry for the late response.
Does not happen on double time or wind down.

**Comment by peppy** [comment]
Sounds like it's likely a device specific issue. As I dont think this is something our end i'm going to close this for now. You will likely see it resolve as we improve overall gameplay performance.
