### ISSUE TITLE
When exiting a play, track position seeks to preview point instead of staying

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6350]
When exiting a play to go to song select, the track currently playing seeks to preview point instead of staying where it was before pausing the play. 

It sounds nicer when the song continues to play from where you failed or exited.

Keeping the track position where it was is also the behaviour stable uses.

**Comment by LittleEndu** [comment]
That is one awful title for that issue. Makes it sound like the song actually stops. But oh well.

**Comment by peppy** [comment]
Updated title
