### ISSUE TITLE
the cursor gets out of the screen

### ISSUE THREAD

**Issue by kravque** [ppy/osu#6354]
**Describe the bug:** 
moving the cursor far away to the right or left makes it get out of the area of the game's screen
( Only on windowed mode )

**Screenshots or videos showing encountered issue:** 
https://streamable.com/tylcf

**osu!lazer version:** 
2019.930.0
**Logs:** 
Not Needed.

**Comment by Joehuu** [comment]
Did you have raw input on?

**Comment by kravque** [comment]
Yes.

**Comment by Gabixel** [comment]
Duplicate of / similar to https://github.com/ppy/osu-framework/issues/2247 ?

**Comment by smoogipoo** [comment]
Closing as duplicate ^^
