### ISSUE TITLE
LifetimeManagementContainer updates gradually become slower during gameplay

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#6358]
**Describe the bug:** 
On an LG V20 running the stock h91810p ROM, some beatmaps don’t keep up with the audio file, causing hit sound timing to be very messed up as well as super low update FPS (under 15 in some cases)

**Screenshots or videos showing encountered issue:** 
https://youtu.be/LzvIWwjyv7k

**osu!lazer version:** 
2019.930.0

**Logs:** 
nah

I’m pretty sure this is a performance thing.
LG V20 H918 64GB | 4GB RAM

**Comment by dscnnctd** [comment]
Same goes to iOS due to improper handling of memory usage.

**Comment by smoogipoo** [comment]
This is a known issue, not due to memory usage. It'll likely improve with https://github.com/ppy/osu/issues/6136. It also seems like `LifetimeManagementContainer` gets slower over time (I've seen >220k check child life invocations) on centipede.

**Comment by peppy** [comment]
We further tested this recently and found it to just be that replay playback was getting further and further behind. `LifetimeManagementContainer` is not at fault and already in quite an optimal state. Further improvements will come as a result of #6136 as mentioned above.
