### ISSUE TITLE
Legacy skins should position their UI similar to stable

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#6361]

**Comment by peppy** [comment]
If you mean the positioning of skinned elements, this will come automatically with legacy skins.

**Comment by mouzedrift** [comment]
im talking about everything that can be seen on the playfield e.g. 
* old progress bars
* combo, accuracy, score and the HP position/length
* old leaderboard (im not sure how the lazer design will look like)

**Comment by peppy** [comment]
This will come with legacy skinning. I'll rename this issue to track that.

**Comment by jorolf** [comment]
This might be a duplicate of https://github.com/ppy/osu/issues/4632

**Comment by bdach** [comment]
Yeah, pretty sure that issue is a superset of this one. Closing this & bumping up milestone on the original to match this.
