### ISSUE TITLE
Maps have no lenght shown in the menu

### ISSUE THREAD

**Issue by Vespure** [ppy/osu#6366]
About 25% of my maps (imported from stable) have no length (0:00) in the menu.
Ingame it works fine.
![osu_2019-10-02_14-59-28](https://user-images.githubusercontent.com/56077469/66046190-889c3500-e525-11e9-97f8-ae3bc84346f3.jpg)
![osu_2019-10-02_14-57-39](https://user-images.githubusercontent.com/56077469/66046273-b84b3d00-e525-11e9-9ea2-e120f5950bc5.jpg)
(both sorted by length)

osu!lazer version: 2019.930.0

**Comment by iiSaLMaN** [comment]
This is intentional. please re-import your beatmaps until we have an automatic way to do that (check #5376). Can be closed.
