### ISSUE TITLE
I cant login. I remember my pass and email but cant login.

### ISSUE THREAD

**Issue by thefirstmine** [ppy/osu#6380]
**Describe the bug:** 
I cant login but I remember password and email. Im using an  Samsung Galaxy S7 edge for the osu!lazer. Android 7 if your asking.
**Screenshots or videos showing encountered issue:** 
I cant show you vids or pics or you will see my email-
**osu!lazer version:** 
It said Version 0.1 for Android.
**Logs:** 
IDK how to check logs on osu!lazer android

**Comment by iiSaLMaN** [comment]
Missing details. Can you explain a bit more about what you see? does it try to login endless-ly, or do you get an error?

Also, logs can be found in `Android/data/sh.ppy.osulazer/logs`, they're helpful for your case, please attach them.

**Comment by thefirstmine** [comment]
All of the logs?

**Comment by iiSaLMaN** [comment]
> All of the logs?

The `runtime.log` and `network.log` are probably what we need, though if you're concerned. attaching all of them is harmless ;)

**Comment by thefirstmine** [comment]
[database[1].log](https://github.com/ppy/osu/files/3686829/database.1.log)
[network[1].log](https://github.com/ppy/osu/files/3686830/network.1.log)
[performance[1].log](https://github.com/ppy/osu/files/3686833/performance.1.log)
[runtime[1].log](https://github.com/ppy/osu/files/3686835/runtime.1.log)

**Comment by thefirstmine** [comment]
That should work

**Comment by thefirstmine** [comment]
Also when I try to login, No error what so ever.

**Comment by thefirstmine** [comment]
Just looked at the network.log file and found the error? It said incorrect credentials... But I have the right password and email

**Comment by bdach** [comment]
Please post full messages in comments instead of single sentences - issues are not chat rooms.

Relevant excerpt from `network.log`:
```
2019-10-03 01:51:48: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Unauthorized.
2019-10-03 01:51:48: Response was: {"error":"invalid_credentials","message":"The user credentials were incorrect."}
```
It appears that your credentials aren't correct after all. Can you log in to the web interface (https://osu.ppy.sh/) using them? If not, you probably need to perform password recovery steps and this can be closed.

**Comment by iiSaLMaN** [comment]
> Please post full messages in comments instead of single sentences - issues are not chat rooms.
> 
> Relevant excerpt from `network.log`:
> 
> ```
> 2019-10-03 01:51:48: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Unauthorized.
> 2019-10-03 01:51:48: Response was: {"error":"invalid_credentials","message":"The user credentials were incorrect."}
> ```
> 
> It appears that your credentials aren't correct after all. Can you log in to the web interface (https://osu.ppy.sh/) using them? If not, you probably need to perform password recovery steps and this can be closed.

Though what if there was an issue with keyboard input?

**Comment by jai-x** [comment]
From network.log
```
2019-10-03 01:51:20: We just went Connecting!
2019-10-03 01:51:21: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Unauthorized.
2019-10-03 01:51:21: Response was: {"error":"invalid_credentials","message":"The user credentials were incorrect."}
2019-10-03 01:51:21: Login failed!
```

It seems your email or password is incorrect. Double check you are entering it correctly.

If you are using a non-english locale setting/keyboard on your phone there might be a bug relating to how text input is handled.

**Comment by thefirstmine** [comment]
Yep I can login to https://osu.ppy.sh/ with my credentials I entered with my phone. I use the English(US) keyboard

**Comment by thefirstmine** [comment]
Gonna try to login again and see what happens.

**Comment by iiSaLMaN** [comment]
> Yep I can login to https://osu.ppy.sh/ with my credentials I entered with my phone. I use the English(US) keyboard

As I said above, can you check whether keyboard input is fine on osu!lazer? (by typing in a non-masked text box).

**Comment by thefirstmine** [comment]
wait what now i can login? i think it was a issue with servers and stuff

**Comment by bdach** [comment]
[osu!status](https://status.ppy.sh/) doesn't seem to be showing any issues. Anyways, closing as resolved.

**Comment by iiSaLMaN** [comment]
> wait what now i can login? i think it was a issue with servers and stuff

Please consider trying whether this issue is reproducible next time.
