### ISSUE TITLE
Exit confirmation appears when closing the window

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6383]
I'm mean using the X while in windowed mode or when closing the window while it's minimized.

**Comment by bdach** [comment]
For windowed mode this is intended behaviour (see description of #6175). Not sure how the minimized case should be handled.

**Comment by LittleEndu** [comment]
![](https://i.imgur.com/jc487uC.png)

Why is the exit button treated differently then? Shouldn't they all forgo the confirmation because the user clicked on them. I can see how pressing alt+F4 might not be confirmation enough, but clicking on something should be all the confirmation needed.

**Comment by bdach** [comment]
I imagine the primary reason is to avoid accidentally closing the game when misclicking the notifications button in the header. While doing so is not *impossible*

**Comment by peppy** [comment]
Confirmation is shown when exit is triggered via external means while something in-game is still happening. This is intended behaviour for now.
