### ISSUE TITLE
Mobile players should also play osu!mania, osu!taiko and osu!catch

### ISSUE THREAD

**Issue by LukaTV939** [ppy/osu#6384]
**Describe the new feature:** 
There should be some buttons for other game modes for mobile players, instead of using bluetooth keyboard to play osu!mania on phone there should be added button functionality on setings for mobile users only 
**Proposal designs of the feature:** 
Just some visual buttons that you can see through gameplay, nothing else.

**Comment by bdach** [comment]
This is planned by way of virtual controls, see #4201 - closing as duplicate.
