### ISSUE TITLE
KeePassXC incompatibility

### ISSUE THREAD

**Issue by Craftplacer** [ppy/osu#6386]
**Describe the bug:** When auto-typing your credentials into osu!lazer using KeePassXC, osu!lazer doesn't recognize the key strokes until you manually press a key in a text box.

**Screenshots or videos showing encountered issue:** https://streamable.com/waj3x

**osu!lazer version:** 2019.930.0

**Logs:** N/A

**Operating system:** Windows 7

IIRC, this used to work.

**Comment by bdach** [comment]
Just to clarify what I'm looking at here, is the scenario as follows?

* Open password manager, select desired entry
* Select textbox in lazer
* Press autofill button, no input shows up in the selected textbox
* Press any keyboard to insert a new character, the autofilled text shows along with extra typed character
* Inserted character has to be removed to match the actual entry in password manager

Is the above accurate? Regardless, this will most likely require a framework-side resolution.

**Comment by Craftplacer** [comment]
> Just to clarify what I'm looking at here, is the scenario as follows?
> 
> * Open password manager, select desired entry
> * Select textbox in lazer
> * Press autofill button, no input shows up in the selected textbox
> * Press any keyboard to insert a new character, the autofilled text shows along with extra typed character
> * Inserted character has to be removed to match the actual entry in password manager
> 
> Is the above accurate? Regardless, this will most likely require a framework-side resolution.
Yes, it's not really "shows", it's actually missing like demonstrated in the video.

> Also, do you recall when did you see this work last? Would help pin it down if it's a regression.
Maybe around the time I still used Windows 10.

**Comment by bdach** [comment]
> Yes, it's not really "shows", it's actually missing like demonstrated in the video.

My phrasing comes from my suspicion that the autofilled text has actually arrived in the underlying buffers, but just hasn't been displayed due to a lack of key-events, but I'd have to dig into the implementation of autofill used by the particular password manager to say for sure.

> Maybe around the time I still used Windows 10.

I meant to ask if you remembered a release number on which this worked properly, sorry if that was unclear.

**Comment by Craftplacer** [comment]
> > Yes, it's not really "shows", it's actually missing like demonstrated in the video.
> 
> My phrasing comes from my suspicion that the autofilled text has actually arrived in the underlying buffers, but just hasn't been displayed due to a lack of key-events, but I'd have to dig into the implementation of autofill used by the particular password manager to say for sure.

https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/windows/AutoTypeWindows.cpp

> > Maybe around the time I still used Windows 10.
> 
> I meant to ask if you remembered a release number on which this worked properly, sorry if that was unclear.

Sorry, I don't necessarily know that since I didn't report it right away.

**Comment by Craftplacer** [comment]
I recently figured out that I noticed the same issue manually with my German keyboard layout.
Me trying to enter brackets (`Ctrl`+`Alt`+`8`/`9`) has the same behavior.
[This also gets handled by the chat overlay (switching tabs), instead of only of the textbox.]

**Comment by peppy** [comment]
Might be fixed with SDL2 switch without effort on our end.

**Comment by Semro** [comment]
> * Open password manager, select desired entry
> * Select textbox in lazer
> * Press autofill button, no input shows up in the selected textbox
> * Press any keyboard to insert a new character, the autofilled text shows along with extra typed character
> * Inserted character has to be removed to match the actual entry in password manager

That's exactly what's happening. I've attached new video, since original is not available anymore.
osu!lazer 2022.128.0

https://user-images.githubusercontent.com/3332159/152422195-ab7ff314-5a31-4eeb-8249-aa4bf7d803d4.mp4

**Comment by Susko3** [comment]
Will probably get fixed once https://github.com/ppy/osu-framework/pull/4985 gets into the osu! release,

**Comment by Craftplacer** [comment]
Confirmed as fixed :+1:
