### ISSUE TITLE
Black screen on launch

### ISSUE THREAD

**Issue by That1GuyWSSC** [ppy/osu#6387]
Describe the crash: When i open osu!lazer the game just blacks out but i can still hear the music and my mouse works as well.

Screenshots or videos showing encountered issue: https://www.youtube.com/watch?v=WFQLRdv18CA&feature=youtu.be

osu!lazer version:![Capture](https://user-images.githubusercontent.com/33987876/66168141-47df1180-e634-11e9-90ef-67239e89b50d.PNG)

Logs: dont know 

Computer Specifications:
[DxDiag.txt](https://github.com/ppy/osu/files/3688284/DxDiag.txt)

**Comment by bdach** [comment]
The logs are located in `%AppData%/osu/logs`; mind attaching them here so we can inspect them for anything suspicious?

**Comment by That1GuyWSSC** [comment]
[performance.log](https://github.com/ppy/osu/files/3688337/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3688338/performance-gamethread.audio.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3688339/performance-gamethread.input.log)
[runtime.log](https://github.com/ppy/osu/files/3688340/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3688341/updater.log)
[database.log](https://github.com/ppy/osu/files/3688342/database.log)
[network.log](https://github.com/ppy/osu/files/3688343/network.log)

**Comment by bdach** [comment]
Thanks, besides some worryingly long audio/input frames (~500ms!) I can't see much in particular. Did you try going to windowed mode by pressing <kbd>Alt</kbd>+<kbd>Enter</kbd> and then restarting? Does that help at all?

**Comment by That1GuyWSSC** [comment]
its very inconsistent sometimes it works and sometimes it just crashes

**Comment by bdach** [comment]
I see, thanks for all the info. If it's inconsistent, this might be quite hard to pin down. Something that could potentially help resolve the issue is updating your graphics device driver, if they aren't currently up-to-date.

**Comment by smoogipoo** [comment]
@That1GuyWSSC Please try the newest release (2020.714.0).
