### ISSUE TITLE
CTB touch drag

### ISSUE THREAD

**Issue by BojayB** [ppy/osu#6388]
Since in using the .apk version of osu!laser and don't have any wireless keyboards or mice, I'd like to propose the idea of mouse/cursor dragging.

I am very poor at playing standard osu! with a touchpad, so I decided that I might have some fun playing Catch the Beat. I cannot play CTB because I can't move the character left or right, either from tapping the left/right side of the screen, or dragging the character around. 

I'd like to ask that touchpad options for ctb and any other unplayable mode be added so that we can tap or drag to move the character or whatever it is the other modes would need. I could not tell you how the shift would work (making the character in ctb speed up) because I have no idea myself. 
Thank you

**Comment by peppy** [comment]
Virtual controls are coming. See https://github.com/ppy/osu/issues/4201.
