### ISSUE TITLE
the old auto mod

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#6389]
The mod should work like auto but without the smooth flow or slow down, it just moves from object to object nonstop

**Comment by smoogipoo** [comment]
I don't think this needs an issue. Auto mod works as intended and is adequate for now. If someone wants to work on a better looking auto generator they're free to do so, but it won't be a consideration for us until much later.

For those interested, there's already been work on a better auto generator in https://github.com/ppy/osu/pull/1962.
