### ISSUE TITLE
Game crashes when the game window is selected/focused.

### ISSUE THREAD

**Issue by ChitoseSG** [ppy/osu#6391]
The game crashes when the game window is selected/focused. I had to switch to another window for the game to launch properly, and when I click on the game window again it will just crash. Game seems to be working properly and has sound if I don't click on it.

It happens 100% of the time for me. The version I used works fine a few hours ago and re-installing it won't help.

![image](https://user-images.githubusercontent.com/56144810/66179667-7264b500-e69c-11e9-9a3d-0bd624098a8b.png)
If launched normally without switching to another window it will freeze here and crash

![image](https://user-images.githubusercontent.com/56144810/66179696-8f998380-e69c-11e9-974b-f2d24d8400fd.png)
If switched to another window and clicked on the game later it will freeze here and crash

osu!lazer version: 2019.930.0

No logs are available

AMD Ryzen 5 2900 Six-core 3.4GHz
16GB RAM
x64
NVIDIA RTX2060
Two monitors

**Comment by ChitoseSG** [comment]
Here are the logs:
[database.log](https://github.com/ppy/osu/files/3688892/database.log)
[network.log](https://github.com/ppy/osu/files/3688893/network.log)
[performance.log](https://github.com/ppy/osu/files/3688894/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3688895/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3688896/updater.log)

**Comment by bdach** [comment]
I don't see anything in the logs that I'd consider a conclusive cause for the issue you describe - would it be possible for you to drop us a video of this happening? Also, could you review the system Event Viewer for any error events around the time of the crash?

**Comment by ChitoseSG** [comment]
[6391gameFreeze20191004_144542.zip](https://github.com/ppy/osu/files/3689285/6391gameFreeze20191004_144542.zip)

Thank you for responding! Here is a video I took with my phone. Sorry, but I couldn't use the event viewer. The version works fine before with the FPS counter from Geforce experience on and disabling it doesn't seem to resolve the problem.

**Comment by smoogipoo** [comment]
If you go into event viewer (WinKey+R -> type "eventvwr"), and go into Windows Logs -> Application, does anything appear in there after a crash?

**Comment by ChitoseSG** [comment]
![image](https://user-images.githubusercontent.com/56144810/66187708-efe9ee80-e6b7-11e9-8177-61569b009f87.png)
![image](https://user-images.githubusercontent.com/56144810/66187869-5b33c080-e6b8-11e9-9b5d-b3f197783616.png)

I managed to striped these out of the event viewer. It seems to be an issue with OpenGL?

**Comment by smoogipoo** [comment]
Seems like a problem with your graphics card driver, yes. Update it and try again.

**Comment by ChitoseSG** [comment]
Issue has been reslouved by reinstalling the graphic card driver and rebooting the pc.

Sorry it wasn't helpful to the development of the program. But thanks a lot!
