### ISSUE TITLE
Still can hit the circles after fail.

### ISSUE THREAD

**Issue by kravque** [ppy/osu#6392]
**Describe the bug:** 
As the title, still can hit the circles after fail,
i'm not sure if people talked about it or if this is really a bug because i don't see it on osu!stable.
**Screenshots or videos showing encountered issue:** 
https://streamable.com/xncxl
**osu!lazer version:** 
2019.930.0
**Logs:** 
Not Needed.

**Comment by iiSaLMaN** [comment]
This is intended behaviour, can be closed.
