### ISSUE TITLE
Disable animations option

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#6395]
**Describe the new feature:** 
Allow user to disable moving triangles/unnecessary animation from skin/interface
**Proposal designs of the feature:** Add an option to the settings to disable animation. User can customize what animation they can disable.

**Comment by iiSaLMaN** [comment]
Why though? I don't see why they should be disabled.

**Comment by bdach** [comment]
This has been suggested before (#3205). If you are concerned with performance, we assure you it's a constant work-in-progress and we don't see that particular concern as a valid reason for disabling animations.

**Comment by enoslayd** [comment]
Oh ok. Its just a suggestion
