### ISSUE TITLE
Selected mods get reset when going to main menu

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6398]
When you exit song select to go to main menu, your selected mods will reset to no selection.

**osu!lazer version:** 2019.930.0

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/3186

**Comment by LittleEndu** [comment]
Yeah I could have sworn there indeed was an issue opened. That issue should be labeled or make use of the word reset...

**Comment by bdach** [comment]
Renamed & labeled.
