### ISSUE TITLE
Toolbar button labels off-center

### ISSUE THREAD

**Issue by iamanai** [ppy/osu#64]
All of the buttons in the toolbar have their icons shifted to the left. I was hesitant to report this because in peppy's video he shared on twitter, they were centered and everything looked fine. But that's not the case for me. I have not as of yet made any changes to the codebase, so it's not anything on my end.

![new osu bug](https://cloud.githubusercontent.com/assets/3515394/19329929/808e58a0-9098-11e6-932e-018e1b7d8f1c.png)

I apologize in advance if I'm just being ignorant.

**Comment by peppy** [comment]
try updating to the latest master?

**Comment by iamanai** [comment]
Oh, I didn't think to check for new commits because I just forked the repository last night. I'm not used to working in such an active repository. That fixed it!

I apologize for my ignorance.
