### ISSUE TITLE
Date/time information displayed in system language

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#6409]
![](https://cdn.discordapp.com/attachments/265143239978385408/630347188056227850/unknown.png)
![](https://cdn.discordapp.com/attachments/265143239978385408/630347391291097088/unknown.png)

**Comment by bdach** [comment]
This is going to be due to Humanizer usage, which automatically matches the system's culture when looking up resources for humanizing. I don't know if there are any localization plans for lazer in general, so this behaviour might be desired as an end-goal or not.

**Comment by peppy** [comment]
Can you explain why non-localised is preferred? I would have thought regional tournaments would prefer display using their localised display formats.

**Comment by smoogipoo** [comment]
Sometimes (I'd almost say usually), the people that stream the matches are not from the same country as the one which the tournament is based in, since they're community volunteers. A separate region selection dropdown may be useful for these cases.

**Comment by peppy** [comment]
I guess it should probably be something that is offered in standard settings too, possibly the same setting as the display language.

**Comment by jorolf** [comment]
Just wanna point out that this also happens inside osu!lazer itself where it's even worse (english and german mixed together)
![webm](https://user-images.githubusercontent.com/12570757/66513231-ea870c80-eada-11e9-85b8-16e6be0d86ef.png)

**Comment by peppy** [comment]
This is because localisation of other strings is not complete yet.
