### ISSUE TITLE
avoid using inactive difficulties in sorting

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#6412]
an example is this:

before(sorting by difficulty(highest) on standard):

mapset 1:

std, 1.51*
std, 2.59*
ctb, 9.43*

mapset 2:

std, 3.99*
std, 5.43*

mapset 3:

std, 8.99*
    
mapset 4:

std, 0.11*
ctb, 0.22*
taiko, 0.55*
mania, 11.97*
--sorted into--
mapset 2, mapset 3, mapset 1, mapset 4

when inactive diffs(nonstandard maps in this case)are removed:
mapset 4, mapset 1, mapset 2, mapset 3

**Comment by bdach** [comment]
Could potentially be resolved by splitting up beatmapsets when sorting by star rating, as proposed for length in #5390. Would then depend on design for #2547.
