### ISSUE TITLE
Audio preview on beatmap starts from beginning when clicking osu!direct download notification

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#6413]
I think title does not describe it enough, so the beatmap’s audio is automatically paused. The audio does not start on preview as well if downloaded on direct and pressed its notification.
[Here’s the video](https://youtu.be/L2Njni1u1xI)

**Comment by Joehuu** [comment]
Regressed in https://github.com/ppy/osu/pull/5934.
