### ISSUE TITLE
Z-Index Storyboard Error

### ISSUE THREAD

**Issue by afichemist** [ppy/osu#6415]
**Describe the bug:** 

Z-Index error
sorry for image is something copyrighted.but its someting wrong in z-index or anything else
**Platform : Ubuntu 18.04**
**Screenshots or videos showing encountered issue:** 
![osu_2019-10-07_13-16-26](https://user-images.githubusercontent.com/52690797/66288823-f325ea00-e904-11e9-8e89-03d169019878.jpg)

**osu!lazer version:** 
20191006

**Logs:** 
No Logs for this,its seems graphical error

**Comment by smoogipoo** [comment]
Got a link to the beatmap handy?

**Comment by afichemist** [comment]
https://osu.ppy.sh/beatmapsets/559622

**Comment by PercyDan54** [comment]
Should be closed now as resolved
![osu_2021-07-19_19-28-22](https://user-images.githubusercontent.com/50285552/126153426-ccf2666a-7871-4b20-863a-db3f14833fce.jpg)

**Comment by nathanielcwm** [comment]
Appears to still be an issue on [Don't stop me now](https://osu.ppy.sh/beatmapsets/5381#osu/)

![image](https://user-images.githubusercontent.com/22572406/145924019-57cd985b-02c6-4631-8bcc-6af1b4fd1074.png)
![image](https://user-images.githubusercontent.com/22572406/145924183-d5b217bc-0bbf-49e3-979a-85205bb4a1bb.png)

**Comment by smoogipoo** [comment]
What the... This must have regressed because I'm sure it was fixed.

**Comment by nathanielcwm** [comment]
I don't recall it ever being this bad in a previous version so yeah...

**Comment by nathanielcwm** [comment]
![image](https://user-images.githubusercontent.com/22572406/145924666-13c4e932-9059-4657-bda2-34ac96d6ed68.png)

Interestingly the other beatmap seems to not exhibit this issue.

**Comment by peppy** [comment]
I guarantee this isn't the same issue. Don't stop me now has always had playback issues, probably more likely due to the different pass/fail layers not being handled yet.

**Comment by smoogipoo** [comment]
Pass/fail layers are handled. This is looking like a lifetime issue, likely regressed via https://github.com/ppy/osu/pull/11990
