### ISSUE TITLE
A different account to test some other features out

### ISSUE THREAD

**Issue by starsgaze** [ppy/osu#6422]
**Describe the new feature:** 
This account would be sorta like allowing users to be able to see how it would be if it was stable: as in submitting scores, possibly multi,  and a few other features. To make it easier for devs, this could be a account exclusive to lazer and all scores will not be shown on osu!web or osu!stable, just osu!lazer.

**Comment by jai-x** [comment]
Is there any reason you are unable to use your normal osu! account when using osu!lazer?

As far as I am aware, osu!lazer will not affect any of your account stats in a negative way so I'm not sure why a separate test account would be needed.

**Comment by lunafreya** [comment]
What you're saying is that we're gonna need to add support for "test" accounts, right, @starsgaze?

@peppy, we're gonna have to make some meta-issues for both o!lazer and o!web to support a new kind of account that will facilitate developer use with the game - "devtesting-type accounts."

**Comment by bdach** [comment]
While developing a test feature enabling developers to "impersonate" a particular type of user and test out changes on different types of accounts is not an unheard of practice, I'd imagine properly-written visual tests are able to fill that hole by themselves without having to inject a battery of test profiles into the actual client.

**Comment by peppy** [comment]
See @bdach's response for reasoning as to why this is not required.
