### ISSUE TITLE
Lazer Unplayable (Linux in Chrome OS)

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#6434]
**Describe the bug:** When I open Lazer, everything is laggy. From the intro to when I close it, the game is so laggy, that it basically renders the game unplayable

**Screenshots or videos showing encountered issue:** Tried to screen record, but it crashed Lazer

**osu!lazer version:** 2019.930.0

**Logs:** Hidden to the point to where I can't find them

**Comment by smoogipoo** [comment]
There’s nothing we can do at this stage. Performance is a constant work in progress but we are prioritising finishing the game first. We are aware of low power devices struggling with the game.
