### ISSUE TITLE
Add a system clock to the main game interface

### ISSUE THREAD

**Issue by jai-x** [ppy/osu#6436]
**Describe the new feature:** 

It would be nice to have a small game wide system clock as an overlay that could sit on one of the corners of the screen. Most likely should be an option to have it visible as a setting. Makes it more convenient to get the time instead of tabbing out from the game when in exclusive full screen mode.

**Comment by Craftplacer** [comment]
Any design proposals for this, if approved?

**Comment by iiSaLMaN** [comment]
I would like it to be in the toolbar, probably at the top right corner next to the notifications button.

**Comment by Altenhh** [comment]
id go for more of thise digital clock designs, i already have some code functioning properly and have already done the design on another repo

!()[https://cdn.discordapp.com/attachments/467894740382121985/548647142235963402/good_af.png.png]

**Comment by Craftplacer** [comment]
By the way, how about adding time statistics on the clock if the user hovers over it?

Something like 
> **Total time played** 1 week(s), 10 hours...
> **Time played in this session** 30 minutes

**Comment by iiSaLMaN** [comment]
> By the way, how about adding time statistics on the clock if the user hovers over it?
> 
> Something like
> 
> > **Total time played** 1 week(s), 10 hours...
> > **Time played in this session** 30 minutes

I believe these type-of statistics are gonna be bundled with #6303

**Comment by peppy** [comment]
I believe this is planned for a later design revision of the toolbar systems.
