### ISSUE TITLE
Result screen should have a restart button

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#6439]
**Describe the new feature:** 
Just like on stable you should have the ability to restart a map from the result screen

**Proposal designs of the feature:** 
![osu_2019-10-08_23-21-25](https://user-images.githubusercontent.com/17437302/66434406-c5cf5e00-ea22-11e9-9a87-fccd5718aac6.jpg)

**Comment by bdach** [comment]
Judging from other previously opened issues pertaining to the results screen it is up for a redesign anyways, so this might be added back whenever it happens.

**Comment by theonlygusti** [comment]
I would like the button to be big and in the middle

![66434406-c5cf5e00-ea22-11e9-9a87-fccd5718aac6](https://user-images.githubusercontent.com/10684786/67619292-afcae700-f7f1-11e9-8a27-a77e21d32c8f.jpg)

**Comment by iiSaLMaN** [comment]
Seems like an unfitting place to put it in, I would rather put it alongside the replay download button with a small gap in-between.

**Comment by GSculerlor** [comment]
![osu_2019-10-26_20-10-39](https://user-images.githubusercontent.com/6506864/67620040-c478a080-f82c-11e9-86f3-fb5842cd1f78.png)

I'm not sure about the new design for result screen, but I think we can add something like this for now, probably

**Comment by peppy** [comment]
Seems fine to add as specified above. Much better than nothing!
