### ISSUE TITLE
Beatmap video not synced and lag

### ISSUE THREAD

**Issue by LukaTV939** [ppy/osu#6446]
**Describe the bug:** 
When you play the beatmap with video on android it lags like you're playng auto Centipede, the video doesn't sync with the gameplay and song witch is a boomer.
**Screenshots or videos showing encountered issue:** 
https://photos.app.goo.gl/N8wkLMg9XDYWYQ6b7
**osu!lazer version:** 
2019.930.0
**Logs:** 
bug, gameplay, android.

**Comment by bdach** [comment]
As noted above, the desync problem has been reported before. Additionally, we have already been made aware of performance issues on lower-end devices - performance is a constant work-in-progress, but completing functionality currently has higher priority.

Closing as duplicate on both counts.

**Comment by LukaTV939** [comment]
Like I know how many duplicates of reports are there, but ok

**Comment by bdach** [comment]
It is not my goal to discourage reports, please don't take it personally - but please do try to use the search functionality and/or issue tags before deciding to submit a report.
