### ISSUE TITLE
Unable to parse config key UIHoldActivationDelay

### ISSUE THREAD

**Issue by LanTenDragon** [ppy/osu#6447]
**Describe the bug:** Appears only once, during startup, and only appears on certain times (not every startup). The hold delay itself did not feel off and is working as normal for me.

**Screenshots or videos showing encountered issue:** ![osu_2019-10-09_22-53-21](https://user-images.githubusercontent.com/43511642/66493809-4193de00-eae9-11e9-970f-74c5e66afd28.jpg)

**osu!lazer version:** 2019.930.0.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3708044/runtime.log)

**Comment by iiSaLMaN** [comment]
I believe you've been switching between latest master and latest release versions of the game, because you've changed the type of `UIHoldActivationDelay` to `float`. (as can be seen in #6359)

Can be closed as this isn't really an issue.
