### ISSUE TITLE
Download replay button incorrectly available upon completing a play

### ISSUE THREAD

**Issue by Azn9** [ppy/osu#6448]
**Describe the crash:** The game crash if we rapidly click on the download replay button. Maybe this is related to the issue the game alert for when clicking on the download button?

**Screenshots or videos showing the encountered issue:** https://youtu.be/zI7Bzxofo3g

**osu!lazer version:** 2019.930.0.0

**Logs:** [runtime.log](https://github.com/ppy/osu/files/3708808/runtime.log)

**Computer Specifications:** CPU: Intel Core i5 8th generation, RAM: 8Go, Graphics card: NVidia GTX 1060 3Go, Windows 10 64bits

**Comment by bdach** [comment]
This is the original location for the error:

https://github.com/ppy/osu/blob/d2ee08ad7b1fc3d8d2328832e17a241cd2ab5963/osu.Game/Scoring/LegacyDatabasedScore.cs#L19

It would appear that even though the download button looks like the replay *should* be downloaded, the replay file is not actually present in the database. Do you mind uploading your database file? It's located at `%AppData%/osu/client.db`.

**Comment by Gabixel** [comment]
Did you complete a map playing Lazer? I can reproduce this issue when finishing a map, where the replay download button is "completed". But for what I know, replays from Lazer gameplay are not implemented yet.

**Comment by Azn9** [comment]
Sorry for the delay ^-^'

Here is the file @bdach : [client.zip](https://github.com/ppy/osu/files/3708978/client.zip)
Yes @Gabixel I completed the map on lazer, this is the score screen showing up at the end of the gameplay

**Comment by bdach** [comment]
Strange, when I try to reproduce this by completing a play on 2019.930.0 the download button is showing *Replay unavailable* as it should... I'll take a look at the DB file now, but to tell you the truth I don't currently understand why there is a difference.

**Comment by bdach** [comment]
I've renamed this to track the actual problem better. Still not sure how to get this to reproduce.

**Comment by Joehuu** [comment]
Should not happen anymore since replays for lazer plays are implemented in https://github.com/ppy/osu/pull/8428.
