### ISSUE TITLE
"All Players" tab from Social Overlay fails to load

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#6459]
![Social Overlay](https://user-images.githubusercontent.com/43073074/66571863-4cde1c80-eb70-11e9-926e-bb3ecca39a7f.png)

The Friends' one seems to work fine:
![Friends Tab](https://user-images.githubusercontent.com/43073074/66571918-65e6cd80-eb70-11e9-8d9a-014cf4e82a56.png)

**Logs:** 
[network.log](https://github.com/ppy/osu/files/3712686/network.log)

**Comment by bdach** [comment]
Seems to be an API contract mismatch after pagination changes web-side - this is the json that is being deserialized:
```
{
  "cursor": {"page": 2},
  "ranking": [
    // actual user list
  ],
  "total": 10000
}
```
Not sure why it starts from *page 2* either, since WhiteCat (current no. 1 in ranks) was the first profile on that list? It seems like it's misnumbering pages.

**Comment by EVAST9919** [comment]
That's because rankings API (which is temporary used to get users) has been updated today

**Comment by bdach** [comment]
Okay, from the description in ppy/osu-web#5084 it looks like `page` is actually pointing to the *next* page. Naming could have been better, but alright, guess it's just a question of updating the contract lazer-side now.
