### ISSUE TITLE
Objects are overlapped with HP bar or score display

### ISSUE THREAD

**Issue by cihe13375** [ppy/osu#6460]
Describe the bug: in some maps, objects near the top of the screen are overlapped with HP bar or score display, while in stable they don't

Screenshots: from Monstrata's Road of Resistance
![osu_2019-10-10_21-00-00](https://user-images.githubusercontent.com/33959010/66571666-410b4e00-eba2-11e9-8df3-c0e408f5a27a.png)
![osu_2019-10-10_21-00-25](https://user-images.githubusercontent.com/33959010/66571667-410b4e00-eba2-11e9-8e82-b15a87a384ec.png)
![osu_2019-10-10_21-00-34](https://user-images.githubusercontent.com/33959010/66571669-41a3e480-eba2-11e9-820b-7893c56b70d7.png)

osu!lazer version:2019.930.0

**Comment by bdach** [comment]
I guess this would fall within the purview of #5239, but hesitant to outright close as duplicate.

**Comment by cihe13375** [comment]
> 
> 
> I guess this would fall within the purview of #5239, but hesitant to outright close as duplicate.

Actually similar problems, but I don't think it's a good idea to let users disable score or HP display during gameplay to avoid this issue (while disable keyinput overlay is probably more acceptable?). Maybe rescaling the playfield a bit smaller to fix this?

**Comment by bdach** [comment]
Actually now I remembered there are settings already that can help with this - setting *Screen scaling* to *Gameplay* and adjusting the play area helps alleviate the problem:

![2019-10-10-155145_505x299_scrot](https://user-images.githubusercontent.com/20418176/66575332-08557f80-eb76-11e9-99bc-fa476680a669.png)

Only thing that might be an issue here is that if this is only a problem for specific beatmaps then forcing a reduced play area for all of them is not necessarily desired.

**Comment by jai-x** [comment]
Given that hitobjects can be placed anywhere in the valid play area, this isn't really a matter of changing the setting for some beatmaps, but that it should not be possible for the overlap to happen for any beatmap as a matter of correctness.

Either the default scale of the playfield could be adjusted or the UI elements made smaller as not to interfere.

**Comment by peppy** [comment]
This is intended behaviour (for now). The playfield size matches stable and will continue to.
