### ISSUE TITLE
Crash when trying yo search

### ISSUE THREAD

**Issue by loweare** [ppy/osu#6476]
So i tried to search music (on osu mobile)
I typed some words it crashes
No videos because it dosent show
Well the version is latest
IDK
IDK

**Comment by jai-x** [comment]
Sounds like a duplicate of https://github.com/ppy/osu/issues/6264

Additionally, please try to be more descriptive of your issues in the future. 
Improper spelling and using "IDK" when asked for deatails is not helpful.

**Comment by loweare** [comment]
I dont know what is it

**Comment by dscnnctd** [comment]
Duplicate of #6264, please close the issue.

**Comment by loweare** [comment]
> So i tr
