### ISSUE TITLE
Replay playback plays frames before gameplay start in unintended way

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#6477]
**Describe the bug:** 
On very start of the replay there's a random key smash and a small playfield jump.
Happens for replays only, autoplay is fine.
**Screenshots or videos showing encountered issue:** 
https://streamable.com/wd37g
**osu!lazer version:** 
2019.1011.0
**Logs:** 
Not needed, I guess.

**Comment by bdach** [comment]
I'm pretty sure this is a regression, but I can't bisect it properly. I've tried like three times and I haven't gotten a sensible answer yet. I'm pretty sure it's not a new one - as far as I can tell the range seems to be (2019.401.0, 2019.502.0).

**Comment by EVAST9919** [comment]
Also happens for "osu" mode now.

**Comment by Wieku** [comment]
I think I've noticed something similar, but on higher fps autoplay (1000fps in the video). It seems to happen when update and draw falls near 200fps: https://streamable.com/0gq8l
It looks like some replay sync issue. Looking at the video @EVAST9919 shared "random key smash" looks like first few replay frames are being played in the same frame but right after it gets rewound back to the beginning.

**Comment by EVAST9919** [comment]
@Wieku I have around 50 fps there
