### ISSUE TITLE
macOS Catalina Unable to use/see cursor in client resulting in not being able to interact with the client

### ISSUE THREAD

**Issue by JarrenJ** [ppy/osu#6478]
**Describe the bug:** On macOS Catalina (not the beta version, the public version). When you start osu!, your cursor does not get displayed. You can kind of see it on the side of the screen but are not able to move it at all. This is preventing me from playing osu! at all as I am unable to interact with the client.

I have tried with a fresh install as well and the same issue was encountered.

**Screenshots or videos showing encountered issue:** No relevant screenshots or videos as the cursor is just not showing up.

**osu!lazer version:** Latest Version

**I understand Catalina is still new so if a fix is not possible relatively soon, I completely understand. I just wanted to make this issue known.**

**Comment by peppy** [comment]
Try turning off raw input. Cmd-Opt-Shift-R, hopefully.

**Comment by JarrenJ** [comment]
Cmd-Opt-Shift-R seemed to not do anything. Is there anyway to exit fullscreen mode without using a cursor? That could potentially be the problem? The app has permissions to do everything it needs to do so that is not an issue.

**Comment by JarrenJ** [comment]
OK. Going to mark this as closed now.

It appears it was just something weird. It moves the cursor to the bottom left hand corner of the screen. Upon switching screens/apps and going back to osu!, it tracks the cursor again.

**Comment by bdach** [comment]
I haven't interacted with a Mac for more than five minutes at a time in my life, but if the hotkeys are anything like the other versions, <kbd>Option</kbd>+<kbd>Enter</kbd> might work?

**Comment by JarrenJ** [comment]
Wow. actually same time for the comments lol. I guess its just a bug that makes the cursor go way to the left of the screen.

**Comment by bdach** [comment]
We've had reports of snapping to screen corners with raw input enabled before, hence the suggestion to disable it above. If it does boil down to that being enabled, this can stay closed, otherwise we should probably look into it further.

**Comment by JarrenJ** [comment]
Ok. The hotkey is ctrl-alt-r. That being said, I can not use that hotkey unless I do what I suggested above; switching apps and then coming back to osu!. This initially made me believe that when the cursor snaps out of the main window, the osu! client is no longer focused, but using Enter and and Backspace both still interact with the client, so I don't think that's the case. Sounds like it might be similar to previous reports of raw input interfering. But in this case, it seems just switching apps and coming back to osu! seems to allow me to interact with the client again.

If you have anything else you would like me to try on Catalina, I'd be happy to help.
