### ISSUE TITLE
Non-ranked map disclaimer

### ISSUE THREAD

**Issue by Craftplacer** [ppy/osu#6480]
**Describe the missing feature:** 
osu!stable warns the player that a map isn't ranked. osu!lazer should probably reimplement this. The warning should only appear inside `PlayerLoader` (or as another form), since if you skip a map in stable the warning is still visible, interferring with gameplay.

**Proposal designs of the feature:** 
![image](https://user-images.githubusercontent.com/22963120/66694212-5327e200-ecb1-11e9-8d13-bf577b2ac4b7.png)

I would take care of this issue as a PR, if the design is set.

**Comment by peppy** [comment]
I think this would create more confusion than anything if implemented *before score submission itself* was.

**Comment by Joehuu** [comment]
Probably something that should be prioritized nearing the end of the year?

Can be reused to show more visibility of the second bullet point of https://discord.com/channels/188630481301012481/188630652340404224/1185083869037330502:
> Consider the first few months after we switch things on to be somewhat of a testing ground. There might be a need to delete some scores. Of course, we’ll try our best not to, but if there is significant pushback from the larger community on game mechanics which can only be recovered by removing scores, we will prioritise getting-things-right.
