### ISSUE TITLE
[osu!lazer Suggestion]: The ability to convert imported beatmaps to the new score system 

### ISSUE THREAD

**Issue by TheDWPCer** [ppy/osu#6482]
**Describe the new feature:** 
The ability to convert imported scores to the new score system. I think score v2.  Personally, I would love this feature, just so I could know I was improving  
**Proposal designs of the feature:** 
I think a good place for a button to convert scores would be in-between those two buttons.
![osu_2019-10-12_00-30-23](https://user-images.githubusercontent.com/15698234/66695524-417e1480-ec88-11e9-9823-32f682d38b79.jpg)

Another place that comes to mind is:
![osu_2019-10-12_00-45-05](https://user-images.githubusercontent.com/15698234/66695773-fdd8da00-ec8a-11e9-89e9-6044a3d8c91a.jpg)
but I don't like that as much.

**Comment by bdach** [comment]
This will be addressed by recalculating scores upon switching between the *Classic* and *Standardised* scoring methods in settings (see #5350). Closing as duplicate.
