### ISSUE TITLE
Some TextBoxes should be able to move the caret between letters

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#6484]
**Describe the bug:** TextBoxes like the settings' one, the _filter_ one from the music controller and the social/osu!direct's one can't move the caret between letters. I think they should be able to do that, like in the chat overlay (except for the carousel's one, because with <kbd>left</kbd> and <kbd>right</kbd> you change beatmap): it could be useful for typos (especially when searching for payers/maps in the social/osu!direct's one, instead of deleting the entire text with <kbd>Escape</kbd>).

**osu!lazer version:** 2019.1011.0

**Comment by peppy** [comment]
Sure, this can be done in any place the left/right keys are not used by other elements.
