### ISSUE TITLE
Cursortrail doesn't move when opening options

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ppy/osu#6485]
**Describe the bug:** When opening the options menu during gameplay, the cursor trail will not move with the rest of the playfield.

**Screenshots or videos showing encountered issue:** [video](https://streamable.com/n9239)

**osu!lazer version:** 2019.1011.0

**Logs:** N/A

**Comment by peppy** [comment]
This is actually correct to some extent. All of gameplay, including the cursor, is paused at this screen. The second cursor you're seeing is the resume cursor.

**Comment by smoogipoo** [comment]
This may be related to https://github.com/ppy/osu/issues/6168

**Comment by peppy** [comment]
I was mistaken, this is actually a duplicate of #6168.
