### ISSUE TITLE
No audio in game

### ISSUE THREAD

**Issue by papifoxy** [ppy/osu#6486]
**Describe the bug:** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:**

**Comment by bdach** [comment]
We can't help you if you don't give us any details at all. What's your platform? Can you describe what you've tried, your device specifications, attach logs and/or a video showing what the problem exactly is at all?

**Comment by peppy** [comment]
Please reopen this after providing logs / screenshots.
