### ISSUE TITLE
Change "email address" text to "email address/username" on login prompt.

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#6489]
Typing your username instead of your email address on login prompt works as well. "email address" text should be changed to "email address/username" instead.
![B32044EE-44DA-49B0-8425-7E9AD10D3A88](https://user-images.githubusercontent.com/48611569/66710866-0f2eee80-ed3e-11e9-8f6b-eb93e110af1e.jpeg)

**Comment by Joehuu** [comment]
This is intentional. See https://github.com/ppy/osu-web/issues/2465#issuecomment-366494726.
