### ISSUE TITLE
Increase size of playfield on mobile devices

### ISSUE THREAD

**Issue by MikelJohnson** [ppy/osu#6490]
Would be really helpful on Android/IOS.
Probably should also have a disclaimer that some gameplay elements might not be visible.

**Comment by peppy** [comment]
Renamed in line with our intentions. Should probably be an automatic change.

**Comment by LittleEndu** [comment]
Wouldn't circle size modifying mean that there needs to be a separate leaderboard for mobile players?

**Comment by Game4all** [comment]
Duplicate of issue #4888 (basically asking for automatic adjusting of CS for mobile) ?

**Comment by bdach** [comment]
I'm actually going to go against standard practice here and close the *old* one, since this one has a better title.

**Comment by Vernonlim** [comment]
> Wouldn't circle size modifying mean that there needs to be a separate leaderboard for mobile players?

I believe that separate leaderboards were already planned regardless, if i'm not mistaken

**Comment by Joehuu** [comment]
Closing as modifying circle size is possible now. We can revisit the CS automation and how this (or anything new really) affects the score/pp leaderboards when lazer replaces stable.
