### ISSUE TITLE
Unnecessary transition to gameplay after ban phase

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#6491]
In my head, it should go **BAN>BAN>PICK>GAMEPLAY**, but this transition makes it **BAN>BAN>GAMEPLAY>MAPPOOL>PICK** 
Is there any particular reason it does it this way? 

[Video for reference](https://www.twitch.tv/videos/493658188?t=00h04m02s)

**Comment by peppy** [comment]
That's weird, it should wait there for a pick.
