### ISSUE TITLE
Add judgement counter to score display

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#6492]
**Describe the new feature:** There could be some detailed stats under the score (or somewhere else along the top) saying how many you've hit of each judgement.

**Proposal designs of the feature:** 
![image](https://user-images.githubusercontent.com/15932372/66715396-3c71b000-edc3-11e9-8a03-f7aa25bf7530.png)

**Comment by peppy** [comment]
This is planned for sure. We have a design for mania currently, but it will probably be redesigned to support all rulesets.

**Comment by Theighlin** [comment]
Has since been added in the form of a skin component. Can be closed.

**Comment by bdach** [comment]
Closed by https://github.com/ppy/osu/pull/21620
