### ISSUE TITLE
osu!catch

### ISSUE THREAD

**Issue by Oxyl44** [ppy/osu#6497]
**Describe the bug:** well everytime i do a map on osu!catch on osu!lazer the score wont go more than 1,000,000 like to 2,000,000 or 3,000,000 idk why even if i have 600 combo 

**Screenshots or videos showing encountered issue:** 
![Screenshot_10](https://user-images.githubusercontent.com/56519766/66722080-3b1ba400-ee12-11e9-8812-ba55c79cd777.png)
![Screenshot_11](https://user-images.githubusercontent.com/56519766/66722082-3e169480-ee12-11e9-995a-263509ab91f6.png)
![Screenshot_12](https://user-images.githubusercontent.com/56519766/66722083-4078ee80-ee12-11e9-895e-c3eabf27943d.png)
![Screenshot_13](https://user-images.githubusercontent.com/56519766/66722084-4242b200-ee12-11e9-83be-ca5589de46eb.png)
**osu!lazer version:** 2019.1011.0

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3722447/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3722448/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3722449/updater.log)
[database.log](https://github.com/ppy/osu/files/3722450/database.log)
[network.log](https://github.com/ppy/osu/files/3722451/network.log)

**Comment by iiSaLMaN** [comment]
I believe you're using the `Standardised` scoring mode (selected by default), go to settings and search for `Scoring Mode`, select `Classic` to get a similar algorithm to stable's scoring.

**Comment by bdach** [comment]
Closing, as @iiSaLMaN pointed out this isn't really an issue.

**Comment by Oxyl44** [comment]
Umm you guys couldve set it as default to classic and when i told you guys on twitter you couldve told me just to select  classic mode but ty

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 13, 2019 at 11:41 PM, Salman Ahmed<notifications@github.com> wrote:   
I believe you're using the Standardised scoring mode (selected by default), go to settings and search for Scoring Mode, select Classic to get a similar algorithm to stable's scoring.

**Comment by bdach** [comment]
Note that the classic scoring algorithm is mostly considered legacy in lazer, hence the default choice of *Standardised*.

**Comment by Oxyl44** [comment]
Didn't know that soo but ty 

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 14, 2019 at 10:03 AM, Bartłomiej Dach<notifications@github.com> wrote:   
Note that the classic scoring algorithm is mostly considered legacy in lazer, hence the default choice of Standardised.
