### ISSUE TITLE
Touchscreen unplayable, fix proposal

### ISSUE THREAD

**Issue by TsavyPrince** [ppy/osu#6499]
**Describe the new feature:** 
Whenever I lift my finger from the screen and press it back on the screen, the cursor stays in the same spot until I lift my finger again or slide. This makes kick sliders and streams unplayable. Like in [here](https://youtu.be/aO5Ujii8dp4).
**Proposal designs of the feature:** 
Just make touchscreen like stable or make a feature to make touchscreen like stable.

**Comment by LeNitrous** [comment]
Already WIP in this PR https://github.com/ppy/osu/pull/6114

**Comment by iiSaLMaN** [comment]
In addition to the above, there are already issues opened about this: #4201 & #4195.

Please try doing a quick search on the currently opened issues to find whether your issue is a duplicate rather than opening a duplicate. Can be closed.

**Comment by smoogipoo** [comment]
This isn't related to virtual input handlers, but rather the lack of correct input handling on touchscreens. There is already a framework issue tracking this: https://github.com/ppy/osu-framework/issues/1514 .
