### ISSUE TITLE
Every time opened, prompts for "receive keystrokes from any app"

### ISSUE THREAD

**Issue by theonlygusti** [ppy/osu#6505]
**Describe the bug:** 

Every single time the app is opened, it prompts

> "osu!.app" would like to receive keystrokes from any application.
>
> Grant access to this application in Security & Privacy preferences, located in System Preferences.

Despite it already having access granted in System Preferences.

**OS Version**: macOS Catalina 10.15

**Screenshots or videos showing encountered issue:** 

![Screenshot 2019-10-14 at 15 15 13](https://user-images.githubusercontent.com/10684786/66758197-b8d4c380-ee95-11e9-8318-0f95ac679de1.png)
![Screenshot 2019-10-14 at 15 17 32](https://user-images.githubusercontent.com/10684786/66758214-c1c59500-ee95-11e9-9343-5a444691abfb.png)

**osu!lazer version:** 2019.1011.0

**Comment by swoolcock** [comment]
Welcome to macOS Catalina.

Are you able to eventually load osu! with access to the keyboard?

**Comment by theonlygusti** [comment]
@swoolcock the app works fine

**Comment by peppy** [comment]
Try removing the app from the accessibility pane, then running and adding again. It may be due to installing an update to osu!, leaving the incorrect version in there.

**Comment by theonlygusti** [comment]
@peppy I'll try that next and let you know what happens.

I wonder though, is this popup necessary?

Since the first few times I just hit "Deny" every time now, and the app still seems to work fine...

**Comment by theonlygusti** [comment]
@peppy 

> Try removing the app from the accessibility pane, then running and adding again

doesn't fix this.

The popup still appears every time.

**Comment by peppy** [comment]
Fixed via notarisation i believe.
