### ISSUE TITLE
Don't prompt "Are you sure you want to exit?"

### ISSUE THREAD

**Issue by theonlygusti** [ppy/osu#6506]
**Describe the new feature:**

Have an option to turn off this confirmation when I press cmd-q

![Screenshot 2019-10-14 at 15 20 36](https://user-images.githubusercontent.com/10684786/66758467-42849100-ee96-11e9-89c2-2db02130d4cf.png)

**Proposal designs of the feature:**

**Comment by bdach** [comment]
The exit dialog is very much a deliberate and intended UX choice with a clear reasoning behind it ([see comment](https://github.com/ppy/osu/issues/6383#issuecomment-538197548)). I'm unconvinced this should be a setting.

**Comment by HoLLy-HaCKeR** [comment]
I believe having an option would be more useful than having to spam alt+f4 or having to spam + holding esc to close the game. I understand that this is intended, but I found it very annoying so I'd appreciate a toggle too.

**Comment by peppy** [comment]
cmd-q-q
alt-f4-f4

There will not be a setting, but eventually it will likely be reduced to how stable does it (the confirmation will only be shown when a download or ongoing operation is active).

**Comment by bdach** [comment]
In my opinion the most important criterion for a setting being a setting is having enough users to justify the maintenance cost.

**Comment by theonlygusti** [comment]
I realised this is intended behaviour. That's why this is a feature request, not a bug report. And it's also why I would like an _option_ added, because this current behaviour might still be desired by some users.

Just because it's currently intended doesn't mean an option to disable it can't be added.

Also, I'm not sure if it's the best UX decision in the first place.

Looks like the reason it is intended behaviour is to prevent accidental exits. This makes sense for mouse clicks, who knows where your cursor is flying when you are playing osu.

But I think keyboard shortcuts like cmd-q, alt-f4, ctrl-w or w/e etc. are quite hard to press accidentally, _especially_ in OSU since afaik there are no keyboard shortcuts, so your fingers won't be near "cmd", "alt" etc. the other modifier keys at any point, and definitely not in a shape that makes pressing keyboard shortcuts easy.

I think it's very worthwhile making it easier to perform a common action (quitting via keyboard shortcut), even if there are rare cases where people accidentally press the "quit" keyboard shortcut.

**Comment by theonlygusti** [comment]
https://ux.stackexchange.com/questions/117159/is-it-a-good-practice-to-ask-before-exiting-an-application-with-nothing-to-save

Looks like it's standard to have a confirmation when

> there is an existing process is in progress in the application and user clicked on exit button

or

> when exiting might be costly

I guess an "existing process" could be that the game is running, and that "exiting might be costly" — the cost would be losing progress through current map (because you're in the middle of playing).

In those cases maybe it makes sense to have a confirmation when you keyboard-shortcut to close.

I know that I won't press the keyboard shortcut by accident, so I'd rather have a more convenient confirmation-less experience of exiting the app.

This is why I hope an option can be added.

(also, currently the confirmation appears all the time, but I guess that's unintended — "the confirmation will only be shown when a download or ongoing operation is active")

**Comment by bdach** [comment]
Please understand that additional settings come with both a maintenance cost and an accessibility cost to new users - the settings are wide enough in scope as-is that they require a search field. We've already had instances where users couldn't find the settings they wanted, even if they were already implemented.

> (also, currently the confirmation appears all the time, but I guess that's unintended — "the confirmation will only be shown when a download or ongoing operation is active")

Note the future tense in that statement; there are other, more pressing issues to attend to.

**Comment by bdach** [comment]
Since the desired final change in behaviour
