### ISSUE TITLE
Enabling raw input makes mouse unusable

### ISSUE THREAD

**Issue by sawe871** [ppy/osu#6512]
**Describe the bug: When enabling raw input for the mouse on Manjaro Linux, the cursor will jump around randomly and renders the game completely unusable.** 

**Screenshots or videos showing encountered issue
![BadMouse](https://user-images.githubusercontent.com/44216789/66787797-9dc07e80-eeaa-11e9-8dd0-a85dc78ff4b5.gif)
:

** 

**osu!lazer version: 66d3a71** 

(The strange colors are just a result of OBS being weird)

**Comment by bdach** [comment]
Raw input on non-Windows platforms is known to have issues (see: #2623, #3170, #3489, among others). Closing.
