### ISSUE TITLE
wont start-up

### ISSUE THREAD

**Issue by dragonGod97677** [ppy/osu#6516]
**Describe the crash:** it doesnt crash, it just wont run, .net framework 4.7.1 is installed

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/38875906/66810554-0fa7cf00-ef62-11e9-8272-978bd639adb4.png)

**osu!lazer version:** 2019.1011.0

**Logs:** 
[log from event viewer.txt](https://github.com/ppy/osu/files/3727913/log.from.event.viewer.txt)

**Computer Specifications:** 
![Untitled](https://user-images.githubusercontent.com/38875906/66810910-bf7d3c80-ef62-11e9-838e-c5bafb240e56.png)

**Comment by peppy** [comment]
Installing .NET Core prerequisites might help resolve this problem. https://go.microsoft.com/fwlink/?linkid=798306
