### ISSUE TITLE
Osu Lazer won't load anymore

### ISSUE THREAD

**Issue by Avriiii** [ppy/osu#6518]
Hello,

**Describe the bug:** 
Osu Lazer won't load anymore, with the same version that works before ... it just launch wihout sound and stuck on ths screen i will link. Really strange

**Screenshots or videos showing encountered issue:** 
https://imgur.com/a/uNje4WC

**osu!lazer version:**  the last one (but the other before do the same)

hmm i try to find for the logs, but i don't get where it is... sry

Thx for help

**Comment by bdach** [comment]
Please attach log output from the `%AppData%/osu/logs` directory.

**Comment by Avriiii** [comment]
there are many txt files

[database.log](https://github.com/ppy/osu/files/3730532/database.log)
[performance.log](https://github.com/ppy/osu/files/3730533/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3730534/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3730535/updater.log)

**Comment by bdach** [comment]
The database log is stale and the rest doesn't show anything conclusive, unfortunately. BASS seems to be initializing fine, the only suspect thing is the fact that it stops at the intro - could have to do with the video decoding libraries perhaps?

Does the game respond to input (as in, can you adjust volume using the scrollwheel), or is it a hard freeze? Also mind looking into the Windows Event Viewers for any related errors?

**Comment by Avriiii** [comment]
i can adjust all them by going over, but i don't see the mouse

**Comment by Avriiii** [comment]
fpr windows event viewer i don't rly know what you talking about, sry

**Comment by bdach** [comment]
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by Avriiii** [comment]
Here, this should be that  (i needed to .zip to upload) : 


[all.zip](https://github.com/ppy/osu/files/3730676/all.zip)

**Comment by bdach** [comment]
Thanks! It looks like Windows is intervening and claiming the game window is idle (see the newest error in that log):
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Application Hang" /> 
  <EventID Qualifiers="0">1002</EventID>
  <!-- ... -->
 </System>
 <EventData>
  <Data>osu!.exe</Data> 
  <Data>0.0.0.0</Data> 
  <!-- ... -->
  <Data>Top level window is idle</Data>
  <!-- ... -->
 </EventData>
</Event>
```
The log also shows that there might be some additional files for debugging available at this path:
```
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Critical_osu!.exe_79fcc2d69bdc56ec1f53ff898ed7691c6989799e_6e0fafde_36b3dcb4
```
Mind having a look if that directory still exists, and then trying to attach this here too? I don't think we'll need much more than this, although I'm wary that this might be quite large if the directory contains minidumps.

You could also try checking if upgrading video or audio drivers (if not current) will resolve the problem.

**Comment by Avriiii** [comment]
i find something in this directory, a file .wer i .zip it and add it . Will check my audio and video driver
[Report.zip](https://github.com/ppy/osu/files/3730775/Report.zip)

**Comment by Avriiii** [comment]
no chance with the drivers :(

**Comment by smoogipoo** [comment]
1. Can you try to find the last version that worked by going through https://github.com/ppy/osu/releases ?
2. Try open the `game.ini` file in `%AppData%/osu`, find the line `IntroSequence = Triangles` and change it to `IntroSequence = Circles`.

**Comment by Avriiii** [comment]
ok sry for the long time response, so i don't find any version that work by going thought some...

but you solve my problem with the change in game.ini ! the game start !


thx a lot to both of you !

**Comment by Avriiii** [comment]
hmm so it start but.... i can't play and it's rly weird, no song, just strange noises
![bug](https://user-images.githubusercontent.com/56600148/66968295-b5535f00-f084-11e9-91aa-ff8ffeca3e18.PNG)

[performance.log](https://github.com/ppy/osu/files/3736900/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3736901/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3736902/updater.log)



i can't launch a song and the game go crazy in the choice of song , going up and down, can make a video if you want

**Comment by bdach** [comment]
This is quite concerning:
```
2019-10-17 12:16:00: osu.Framework.Graphics.Containers.CompositeDrawable+InvalidThreadForChildMutationException: Cannot mutate the children of a Loaded CompositeDrawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
2019-10-17 12:16:00: at osu.Framework.Graphics.Containers.CompositeDrawable.ensureChildMutationAllowed()
2019-10-17 12:16:00: at osu.Framework.Graphics.Containers.CompositeDrawable.ClearInternal(Boolean disposeChildren)
2019-10-17 12:16:00: at osu.Game.Screens.Edit.Components.Timelines.Summary.Parts.TimelinePart.LoadBeatmap(WorkingBeatmap beatmap)
2019-10-17 12:16:00: at osu.Game.Screens.Edit.Components.Timelines.Summary.Parts.ControlPointPart.LoadBeatmap(WorkingBeatmap beatmap)
2019-10-17 12:16:00: at osu.Game.Screens.Edit.Components.Timelines.Summary.Parts.TimelinePart.<.ctor>b__2_0(ValueChangedEvent`1 b)
2019-10-17 12:16:00: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2019-10-17 12:16:00: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2019-10-17 12:16:00: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2019-10-17 12:16:00: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2019-10-17 12:16:00: at osu.Game.Overlays.MusicController.next(Boolean instant)
2019-10-17 12:16:00: at osu.Game.OsuGame.currentTrackCompleted()
2019-10-17 12:16:00: at osu.Framework.Audio.Track.TrackVirtual.UpdateState()
```
and then a bunch of
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
```
when switching tracks, which explains the symptoms. I'm not entirely sure it is related to the original issue with the intro, though.

**Comment by Avriiii** [comment]
the thing is the game work used to work just fine on this computer... i just don't get it

**Comment by Avriiii** [comment]
ok i solve the problem, it was the firewall....

**Comment by Avriiii** [comment]
or maybe not, but i try again and now it works

**Comment by Avriiii** [comment]
if i put the intro version triangle it won't work thought lol

**Comment by bdach** [comment]
Both the intro issue and that other nasty stack probably warrant a looking into.

For more clarification - did you hear any sound on the triangles intro before the freeze? Asking to determine whether it's audio or video that seems to be most likely related to the crash.

**Comment by peppy** [comment]
the triangles intro depends on having an active and working audio device, so this is 99% an issue with the user's audio device selection.

**Comment by Avriiii** [comment]
no it's total silence (but the thing is i already see this intro on this computer working) but as i say before it's not freeze i can go around the switch on the left and even make noise with the mute button

just make some test right now and everything else seems to work, just the triangle intro is a problem (wiht isn't a issue for me but if i can help solve something for other)

**Comment by smoogipoo** [comment]
Maybe something with razer's drivers in this case. Are you able to try out any other headphones?

**Comment by Avriiii** [comment]
I try to unload everything about razer on my computer (i go into the task manager to be sure) , use the sound of my screen (hdmi) but the problem persist .

I try to check if my audio driver were outdated but nothing seems wrong there

**Comment by cogitantium** [comment]
Under Linux, it turned out that my `AudioDevice` was not set in `framework.ini`. I manually set it to `AudioDevice = PulseAudio Sound Server` which allowed the intro to play, although it seems you had the first frame loaded, which I did not. This resolved it for me.

**Comment by Avriiii** [comment]
I just try re installing the game with the new version and my problem is actually solve so i didn't had to try this. but thx for trying to help
