### ISSUE TITLE
cursor disappear with raw input on macOS

### ISSUE THREAD

**Issue by hsgyc** [ppy/osu#6519]
Describe the bug:
  Previously osu!lazer was working normally. When I turned on raw input, my mouse cursor disappeared. Then neither move nor click is permitted. And when I move mouse outside this application, it stuck on the boundary.  I can't find the configuration file on my computer so I can't change this setting without launch this app.

osu!lazer version:
2019.1011.0
macOS version:
Catalina 10.15

**Comment by bdach** [comment]
Has been reported before (#6478), but as you're saying that this used to work, going to allow this one to be open for tracking at least, since it's unlikely to be related to the any of the other raw input woes.

**Comment by hsgyc** [comment]
Amazingly that the cursor appear without power so I can disable raw input.
