### ISSUE TITLE
Auto saving last mods

### ISSUE THREAD

**Issue by deissh** [ppy/osu#6520]
Probably everyone who plays with mods enters F1 and enables the necessary mods every time.
I suggest saving the last selected mods and by default turning them on when we enter the game.

**Comment by iiSaLMaN** [comment]
What about making something like mod combinations where you can save your own list of mods and then when selecting the combination, it loads the saved mods ;)

**Comment by EVAST9919** [comment]
Probably everyone is not everyone. At least should be an option in settings IMO

**Comment by peppy** [comment]
I believe this is being considered in @arflyte's redesign of the mod select overlay.
