### ISSUE TITLE
Day divider for chat

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#6521]
**Describe the new feature:** A simple divider that separates the chat in days.

**Proposal designs of the feature:** I don't know if you already have a design for this, but here are some examples I've done (with a little inspiration from Discord in the first one, but with a brighter color of the Lazer chat):
<details>
<summary>Design 1</summary>

![Design 1](https://user-images.githubusercontent.com/43073074/66960628-24bd5480-f06d-11e9-90d7-d0bcaf7019a0.png)
</details>
<details>
<summary>Design 2</summary>

![Design 2](https://user-images.githubusercontent.com/43073074/66960688-4e767b80-f06d-11e9-97da-416451f29946.png)
</details>
<details>
<summary>Design 3</summary>

![Design 3](https://user-images.githubusercontent.com/43073074/66960694-51716c00-f06d-11e9-9f4b-53ba60c86ee1.png)
</details>
<details>
<summary>Design 4</summary>

![Design 4](https://user-images.githubusercontent.com/43073074/66960699-53d3c600-f06d-11e9-8736-f550f5a7614f.png)
</details>

**Comment by iiSaLMaN** [comment]
+1 for the first design the most.

**Comment by ThatsNiceGuy** [comment]
Design 2 looks epic and with some tweaks it could fit lazer’s aesthetic

**Comment by smoogipoo** [comment]
@arflyte would like your input on the proposal

**Comment by arflyte** [comment]
yeah, a day divider would be nice. i'd personally go for the first one for now.
