### ISSUE TITLE
UI Plugin Support

### ISSUE THREAD

**Issue by intwineger** [ppy/osu#6524]
**Describe the new feature:** 
I would love to see LUA or related plugin support for the UI of osu!lazer.
**Proposal designs of the feature:** 
I think UI level plugin support will open up unlimited control to user-end UI management.

**Comment by smoogipoo** [comment]
We're not going to go with LUA, but instead our own markup system. There has already been some preliminary work on this in https://github.com/ppy/osu-framework/pull/2395, and will be fulfilled by further skinning improvements.
