### ISSUE TITLE
Import skins by opening the osk (Android)

### ISSUE THREAD

**Issue by Hexality** [ppy/osu#6525]
I don't know if it's already implemented but:
The possibility to import maps and skins by openning respective files in the app (Click-to-import)

Method: going to file manager, clicking the file, selecting it to open with osu! and import the skin/beatmap

**Comment by jai-x** [comment]
There seems to be a WIP pull request for that functionality here: https://github.com/ppy/osu/pull/5265

@EdrowsLuo are you still going to work on that?

**Comment by bdach** [comment]
#5761 is definitely related. Not sure which one to close here, though.

**Comment by clay53** [comment]
#5761 is related but this issue seems to be more of "open with" functionality instead of "choose a file to import" in-game (specifically, they're asking for a button to automatically search for importable files and import them - opsu! has a similar feature to that). I don't think either should be closed as of yet.

**Comment by MTGPROD** [comment]
So, someone have a idea for how implementing this ? Personally i though that add a bouton to scan the phone's files to find osk and import it. Or at the start of the game that'll automatically import downloaded skins.

**Comment by Moltanicaa** [comment]
Let upload .osk files to the root folder of the application so the osu will automatically unpack them on startup? It may look like this (the skin is at the bottom)
![Screenshot_2020-07-31-16-03-43-61_e24af01bec3189413074866d0f854b7c](https://user-images.githubusercontent.com/59089206/89005265-5a56d400-d347-11ea-8d4d-a9742593a082.jpg)

**Comment by peppy** [comment]
Please wait for proper support.

**Comment by Zeravu** [comment]
![Screenshot_20201129-063843](https://user-images.githubusercontent.com/75187039/100528280-a0e11000-320d-11eb-91bf-ededcaca2dd3.png)
there is no option to open with osu

**Comment by Game4all** [comment]
As said above, support for importing skins by opening them with lazer on android isn't still implemented yet as shows the fact that this issue is still open. So please wait for proper import support to land on android
