### ISSUE TITLE
Could not find a stable install

### ISSUE THREAD

**Issue by Fwippin** [ppy/osu#6531]
**Describe the bug:** Upon trying to import skins, beatmaps or scores, Lazer sends me two notifications that it could not find a stable installation.

**Screenshots or videos showing encountered issue:** 
![osu!_UvlhpJ5Egd](https://user-images.githubusercontent.com/56694091/67031602-28ef7d80-f112-11e9-80b1-6db8da72c507.png)

**osu!lazer version:** 2019.1011.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3740531/database.log)
[network.log](https://github.com/ppy/osu/files/3740532/network.log)
[performance.log](https://github.com/ppy/osu/files/3740533/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3740534/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3740535/updater.log)

Some extra notes, on the stable client I clicked on "Repair folder permissions", game asked for admin permissions, I allowed it, yet it showed me this error message: 
![osu!_Kml9AsMcjs](https://user-images.githubusercontent.com/56694091/67032293-96e87480-f113-11e9-81b0-68b7309181d6.png)

**Comment by bdach** [comment]
For now I can't pinpoint the cause from the logs alone, since the exception is not logged explicitly:

https://github.com/ppy/osu/blob/47a395d6f2ed088b22f83965941f9f27ad67bfe4/osu.Desktop/OsuGameDesktop.cs#L37-L45

The fact that permission repair failed does seem to suggest this being a permissions issue, however - perhaps stable's dir (`C:/Users/[username]/AppData/Local/osu!`) has stricter perms than maybe necessary? Can you try seeing if your user account has read permissions to that directory without having to escalate privileges?

**Comment by peppy** [comment]
Can you confirm where your stable install is located on disk?

**Comment by Fwippin** [comment]
It's on D:\osu!
Not on my system drive.

**Comment by peppy** [comment]
It sounds like for whatever reason, stable is unable to write the path to your registry. Do your osu-stable associations work per chance (ie. being able to double-check an osz file in explorer to load it)?

**Comment by Fwippin** [comment]
Nope, upon clicking on an .osz file Windows asked me which application should it use to open it. I selected osu! and also checked in Windows Settings to see what application is associated with .osz, .osk and other osu! related files and nothing was there. So I've selected osu! for all of them and now those files open with osu! by themselves but Lazer still doesn't find the stable client.

**Comment by peppy** [comment]
For the time being, this is a touch out of scope (is an issue with stable not being able to write to registry). We may add a browse-for-stable option at a later point in time, but I'd hope we don't need to.

**Comment by Fwippin** [comment]
I managed to get around the issue by logging into the Administrator account on my PC and from there doing the "Repair folder permissions" option. This time Lazer did find a stable install and everything imported flawlessly. Thank you for your help!
