### ISSUE TITLE
Number of types of hits in mania gets hidden behind boarder

### ISSUE THREAD

**Issue by skrrtskrrtman** [ppy/osu#6540]
**Describe the bug:** 
Tested on full screen, windowed and boarder less all produce the same results. I am using 1x scaling here on a 1080p monitor.

**Screenshots or videos showing encountered issue:** 
![osu maniaend screen scailing issue](https://user-images.githubusercontent.com/50763036/67086558-9d3e2580-f1d3-11e9-831b-3d3e64415818.PNG)

**osu!lazer version:** 
2019.1011.0

**Logs:**

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/4791
