### ISSUE TITLE
Disable hold thing

### ISSUE THREAD

**Issue by TsavyPrince** [ppy/osu#6545]
**Describe the new feature:** 
I use touchscreen and keyboard, so I tap the screen and use my keyboard to stream. However, when I tap somewhere my cursor stays in the same place until I move or lift my finger. This makes osu!lazer unplayable.
**Proposal designs of the feature:** 
Add an option in the settings to disable this.

**Comment by iiSaLMaN** [comment]
We currently lack correct input handling. Which is being tracked at here: ppy/osu-framework#1514. Can be closed.
