### ISSUE TITLE
Use backgrounded lazer as music player on mobile devices

### ISSUE THREAD

**Issue by odenstyle** [ppy/osu#6546]
osu!lazer music to play while the app is closed in iOS devices
![DC3C3F99-88A9-4930-95E4-04B322CD59E7](https://user-images.githubusercontent.com/56468112/67152190-32d9c380-f26d-11e9-9b4b-8065241271ac.jpeg)

there’s a music player in-app, why not make it a feature off-app?

**Comment by peppy** [comment]
Out of scope. osu! is not a music player.
