### ISSUE TITLE
osu! have a compatibility issue with MSI Applications.

### ISSUE THREAD

**Issue by MuTong233** [ppy/osu#6548]
**Describe the bug:** 
osu!lazer won't run normally when the Nahimic VR App,MSI Gaming App are installed on the computer.
**Screenshots or videos showing encountered issue:** 
Refer to issue #6328 
**osu!lazer version:** 
2019.630.0 and more...
**Logs:** 
Refer to issue #6328

**Comment by peppy** [comment]
Please reopen the original issue and update the title.
