### ISSUE TITLE
Beatmap loading becomes very long when storyboard is enabled

### ISSUE THREAD

**Issue by ojh050118** [ppy/osu#6549]
**Describe the bug:** 
Some beatmap will load very long when storyboards are enabled.
It took around 2 minutes to fully load the beatmap.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=eq3vtBBuEBw&feature=youtu.be

**osu!lazer version:** 
2019.1011.0

**Logs:** 
I will upload it if necessary.

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/4976
