### ISSUE TITLE
Ctrl+A to toggle Auto mod

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#6551]
**Describe the missing feature:** In stable, pressing `Ctrl+A` toggles Auto mod in song selection. In lazer, this shotcut selects all text of the search box.

**Comment by Game4all** [comment]
I don't think it is necessary to add another keybind to toggle auto as doing `CTRL + Enter` in song selection will launch selected map with auto enabled

**Comment by bdach** [comment]
Duplicate of #5839.
