### ISSUE TITLE
New Mod Idea : Finger Control

### ISSUE THREAD

**Issue by LanTenDragon** [ppy/osu#6555]
**Describe the new feature:** A new multimod: Finger Control & Finger Control Strict

**Proposal designs of the feature:**

* Finger Control (FC): subtracts from the current score depending on how many extra presses

* Finger Control Strict (FS): Instant fail if key presses at this moment is more than the amount of hitobjects that have appeared up to this point. Note that player is allowed to have less than or equal keypresses, but not more.
  
* This mod should be a **difficulty increase** mod, as you are restricting yourself to a limited amount of keypresses. This mod should be incompatible with Sudden Death, Perfect. 

* This mod is not really an anti-mashing mechanism per se, its just an artificial handicap to showcase one's finger control ability. Plus, with the fail criteria, it would not prevent Hidamari no Uta esque double tapping.  

**Topics needing further discussion:**
* Acronym of FC conflicts with Full Combo (also called FC in rhythm game jargon)
* Should key presses before the first hit object be ignored?
* How would 2B mapping interfere with this mod?
* Should spinners be taken into account?
* If there are anti-mashing mechanisms planned, then this mod is not needed.
* How much score multiplier to give.

**Comment by dscnnctd** [comment]
I have a question for this. Will this mod be useable across different game modes?

**Comment by bdach** [comment]
It appears to me that this mod would only make sense in the case where there are distinguished keyboard inputs you need to press to the beat (by which I mean taiko and mania), since these are the ones you might try to press "too many keys" on and still get hits, and not very much sense in standard (where a hit is a hit) or in catch (not sure how it would have to even be interpreted there). But I see no reason for it to be impossible to reuse the same mod in taiko and mania if it is implemented in a way that enables it.

**Comment by dscnnctd** [comment]
If this was to be implemented for catch mode, it will be based on the amount of transitions (fruit change) you need to do without exceeding the maximum limit on a specific beatmap, correct?

**Comment by bdach** [comment]
I suppose it could be done by calculating the minimum amount of left-right input switches autoplay does to pass, true.

**Comment by dscnnctd** [comment]
So which proposal are you in favour of based on discussion, this issue or #5686? I would like to know which one is a better proposal than the other.

**Comment by bdach** [comment]
Personally I don't feel comfortable making that sort of decision, I just mostly code here. Going to defer to the core team and/or opinions of players if they are around to give some on this matter.

**Comment by LanTenDragon** [comment]
With this being discussed further recently, I realised my proposal lacked some extra details.

>Will this mod be useable across different game modes?

@dscnnctd Yes I intend it to be implemented in the four main rulesets. For future custom rulesets, it is up to the ruleset author to implement.

>PP was not involved in the punishment?

@genericthing I intended score penalty as punishment, as I had lazer's scoring system in mind. Lazer seems to bring 1 million scoring into focus and potentially shift away from PP. But I do agree that if you FC any rhythmically complex beatmap with this mod turned on, then you should be rewarded a healthy amount of PP.

>Not an anti-mashing mechanism

I really forgot to add this part in. I was speaking specifically about being unable to prevent standards ruleset's mashing. That's why I mentioned ```Hidamari No Uta```.

**Comment by LanTenDragon** [comment]
>not very much sense in standard (where a hit is a hit)

@bdach There are situations in standard mode where players would do (for a lack of a better word) an empty press. Check the keypress counter at the end of these comparison video.

https://www.youtube.com/watch?v=Qyo9coEuj2k   
https://www.youtube.com/watch?v=OaOBsbwZ7SM

Out of four players accross two maps, it seems only one had `keypresses == number of hitobjects`

Looks like this would become a really difficult mod on maps with complex rhythms, especially with strict mode.
