### ISSUE TITLE
macOS Player Info trackpad scroll not working

### ISSUE THREAD

**Issue by elisamalzoni** [ppy/osu#6571]
**Describe the bug:** 
In macOS I couldn't scroll without a external mouse.

**osu!lazer version:** 
Development build

**Comment by peppy** [comment]
raw input on or off?

**Comment by elisamalzoni** [comment]
Raw input was off, when I turned on scroll started working. That's what is expected?

**Comment by peppy** [comment]
Not sure, but let's go with it for now.
