### ISSUE TITLE
Unique constraint errors when importing from stable

### ISSUE THREAD

**Issue by wigoor** [ppy/osu#6572]
**Describe the bug:** 
Got a lot of DB errors while importing maps from stable.
"osu.game.database.osudbcontext"
"dbcommand"

**osu!lazer version:** 
osu 2019.1021.0.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3755778/database.log)

**Comment by peppy** [comment]
Potentially a regression; this was addressed recently.
