### ISSUE TITLE
osu only work normally on Vsync on macOS

### ISSUE THREAD

**Issue by hsgyc** [ppy/osu#6576]
Describe the bug:
osu can only work normally on Vsync. When I switch to other setting like 2x or unlimited, the frame suddenly drop to approximately 20-30. And the input also become very unstable.Then I check Activity monitor ,finding that it only consume a little memory, cpu and gpu.

osu!lazer version: 2019.1021.0
macOS version: Catalina 10.15

**Comment by bdach** [comment]
Please attach logs from `~/.local/share/osu/logs` so that we have more info to work with.

**Comment by hsgyc** [comment]
@bdach
[logs.zip](https://github.com/ppy/osu/files/3760522/logs.zip)

**Comment by bdach** [comment]
The log you've attached cuts out at when you opened the main menu, so there's no actual performance data to analyse. If possible, please open the game, play a map, close the game and then post fresh logs again here.

**Comment by smoogipoo** [comment]
That sounds like you're at your GPU limit. Please provide your system's specs.

**Comment by hsgyc** [comment]
the utilization of cpu and gpu are all about 30%-50%
[logs.zip](https://github.com/ppy/osu/files/3765650/logs.zip)
[system_specs.txt](https://github.com/ppy/osu/files/3765651/system_specs.txt)

**Comment by peppy** [comment]
you say the "frame suddenly drop" but fail to mention which thread is dropping. it's highly likely that your system is throttling due to higher update frame rates.

**Comment by hsgyc** [comment]
I talked to apple advisor, getting that there is no system throttling for any applications. This performance is very like a limitation of hardware, but the strange thing is that the utilization is not so high.

**Comment by peppy** [comment]
Closing this as a per-system issue. Will likely get better as we improve performance.
