### ISSUE TITLE
Discord Rich Presence not working properly

### ISSUE THREAD

**Issue by tonyleechicken1** [ppy/osu#6586]
**Describe the bug:** 
Discord detects that osu! is running but the custom rich presence that is used doesn't show, it instead shows as a regular game
**Screenshots or videos showing encountered issue:** 
![Screenshot_8](https://user-images.githubusercontent.com/47640864/67420439-3e422d00-f594-11e9-8f4f-a191c9f69f44.png)

**osu!lazer version:** 
2019.1021.0
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3763756/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3763757/updater.log)
[database.log](https://github.com/ppy/osu/files/3763758/database.log)
[network.log](https://github.com/ppy/osu/files/3763759/network.log)
[performance.log](https://github.com/ppy/osu/files/3763760/performance.log)

**Comment by Joehuu** [comment]
Not implemented on lazer yet. Tracking in https://github.com/ppy/osu/issues/1109.
