### ISSUE TITLE
Where can I find the osu!lazer skin?

### ISSUE THREAD

**Issue by TechAdvancedCyborg** [ppy/osu#6587]
Where can I find the osu!lazer skin in the game files?

**Comment by jorolf** [comment]
If you're searching for ``.png`` files you're probably out of luck. Most skin elements are "coded" and don't have a texture file. There are however some exceptions: 
https://github.com/ppy/osu-resources/tree/master/osu.Game.Resources/Textures/Gameplay

**Comment by TechAdvancedCyborg** [comment]
Oh, thanks anyway.
