### ISSUE TITLE
Date and time spacing issue at result screen

### ISSUE THREAD

**Issue by LanTenDragon** [ppy/osu#6592]
**Describe the bug:** When the date and time is too long, no additional spacing / padding is provided.

This issue happenened on Windows, and when I checked Linux for a similar issue, it isn't an issue as my time was in 24 hour format (no am/pm text). 

**Screenshots or videos showing encountered issue:** 
![osu_2019-10-25_00-06-29](https://user-images.githubusercontent.com/43511642/67504796-abe97880-f6bc-11e9-9e8d-114afbaeeab6.png)

**osu!lazer version:** 2019.1021.0

**Logs:** Not needed

**Comment by bdach** [comment]
Yet another thing to consider when the planned redesign of this screen happens, I suppose.
