### ISSUE TITLE
Osu! crashes if i try to run it in the background on android

### ISSUE THREAD

**Issue by zzahkaboom24** [ppy/osu#6593]
If i open my settings and get back in Osu! it seems to be "restarted". Thats happening every time if the game is put in the background. My Osu! Version is 2019.1021.0 and its happening on all my mobile devices except on my pc and i understand that this is normal but can you fix this pls? also no logs to share.

**Comment by zzahkaboom24** [comment]
i just posted this because since android 9 you cant connect to wifi from the quicktools. i have to manually press and hold the wifi button and connect to it.

**Comment by bdach** [comment]
This is actually not a straightforward fix, unfortunately - the causes of this run very deep and require some pretty substantial changes. The primary reason for this behaviour is that Android will switch the OpenGL context upon minimising, which then we currently don't have a way to properly restore when returning to the app, so any context switch will cause lazer to force-close and restart from the intro.

This has been known for a while now and it'll probably be a while still until this gets addressed, but we are aware of it and there are plans to tackle this - see ppy/osu-framework#2448 as something that could facilitate an engine change that will fix this problem.
