### ISSUE TITLE
Dragging hitobjects between distance snaps bypasses editor playfield

### ISSUE THREAD

**Issue by revelsix** [ppy/osu#6594]
**Describe the bug:** When first placing hitobjects using distance snap, objects fall within the editor playfield as intended. This breaks, however, when you drag an already placed hitobject. It is now able to easily bypass the playfield restrictions. 

**Screenshots or videos showing encountered issue:** https://youtu.be/5rQojp3pfGg

**osu!lazer version:** 2019.1021.0

**Logs:** not necessary

**Comment by revelsix** [comment]
There's also another bug(?) showcased in the video where the triangles inside the slider start to freak out, I'll make a separate issue if it hasn't already been discovered.

**Comment by smoogipoo** [comment]
Triangles "freaking out" is intended.
