### ISSUE TITLE
Skin elements replaces text on some settings options 

### ISSUE THREAD

**Issue by Mr-Emerald** [ppy/osu#6602]
**Describe the bug:** 
Updated to Stable 20191023.4 and notices that some elements of the skin i was using
replaced the text used for some of the options in settings

**Screenshots or videos showing encountered issue:** 
![screenshot592](https://user-images.githubusercontent.com/52552280/67565540-050ee600-f769-11e9-8335-278402750136.png)

**Comment by peppy** [comment]
Not a lazer issue. Also Looks like graphical corruption on your system so please don't report this. Update your graphics card drivers and check for overheating.
