### ISSUE TITLE
Osu Lazer Android crashed when i use a custom android keyboard

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu#6613]
Osu Lazer Android crashed when i use a custom keyboard, like messagease or another 3rd apps keyboard

**Screenshots or videos showing encountered issue:** 
I see shows a error.

**osu!lazer version:** 
Android 2019.1021.0
**Logs:** 
How can i send a logs from mobile phone

**Computer Specifications:** 
Huawei P30 Lite

**Comment by bdach** [comment]
Please attach logs from `Android/Data/sh.ppy.osulazer/logs`.

**Comment by Fatal3ty** [comment]
> 
> 
> Please attach logs from `Android/Data/sh.ppy.osulazer/logs`.

I mean how? Is my first on try for android.

**Comment by peppy** [comment]
Out of scope for now, unless you plan on fixing yourself.

**Comment by Craftplacer** [comment]
@Fatal3ty provided me the following logs:
[runtime.log](https://github.com/ppy/osu/files/3774162/runtime.log)
[network.log](https://github.com/ppy/osu/files/3774163/network.log)
[database.log](https://github.com/ppy/osu/files/3774164/database.log)
[performance.log](https://github.com/ppy/osu/files/3774165/performance.log)

**Comment by bdach** [comment]
Yeah, it's not the keyboard, it's #6264 again...

**Comment by Fatal3ty** [comment]
Oh okay thanks, i didnt know sorry.
