### ISSUE TITLE
Osu!mobile crashesh

### ISSUE THREAD

**Issue by wintea** [ppy/osu#6615]
**Describe the crash:** 
osu!lazer crashing sometimes during maps
**Screenshots or videos showing encountered issue:** 
https://youtu.be/SYWe-c_H-70
**osu!lazer version:** 
2019.1021.0
**Logs:** 
No logs yet since neither does testflight or iOS supports it 
**Computer Specifications:** 
iPhone XS Max

**Comment by dscnnctd** [comment]
Duplicate of #6355, please close this issue.
