### ISSUE TITLE
Unable to sign in anymore Osu!Lazer 2019.1021.0

### ISSUE THREAD

**Issue by zwlwz** [ppy/osu#6624]
Unable to sign into Osu!Lazer but i was yesterday
I've tried with both email and username, also am able to log into regular Osu!
gets stuck, doesn't give me an error saying wrong credentials,
Osu! name; Born To Meme
![image](https://user-images.githubusercontent.com/57032385/67629167-c09a4d80-f82f-11e9-823a-1fa3e1259986.png)

Osu!Lazer 2019.1021.0

**Logs:** 
[network.log](https://github.com/ppy/osu/files/3775486/network.log)
[performance.log](https://github.com/ppy/osu/files/3775481/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3775482/runtime.log)
[database.log](https://github.com/ppy/osu/files/3775483/database.log)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/4234
