### ISSUE TITLE
crushed while installing

### ISSUE THREAD

**Issue by wolfpat01** [ppy/osu#6646]
windows 8.1
normal osu works fine
osu lazer doesnt
![Capture](https://user-images.githubusercontent.com/57036855/67712260-f1ab8700-f9c3-11e9-938f-a34097e132e6.PNG)
[SquirrelSetup.log](https://github.com/ppy/osu/files/3780371/SquirrelSetup.log)

**Comment by bdach** [comment]
You seem to be on a 32-bit OS, we don't currently deploy 32-bit executables (see #3984). Closing as duplicate.
