### ISSUE TITLE
On screen z,x buttons(mobile)

### ISSUE THREAD

**Issue by Heavlieddor** [ppy/osu#6659]
It would look like there is a nearly invisible rectangle divided into two on left/right side of the screen. If you touch it it would work like z and x buttons on pc. Like you play normally but instead of clicking the circles individually you just control the cursor and use these on screen buttons.

**Comment by jai-x** [comment]
Duplicate of https://github.com/ppy/osu/issues/4201

Also note: We are not accepting any new issues regarding osu!lazer on mobile at the moment. You should have seen this warning when creating this issue.

**Comment by Heavlieddor** [comment]
oh sorry
