### ISSUE TITLE
Half time mod hourglass should be tilted differently

### ISSUE THREAD

**Issue by theonlygusti** [ppy/osu#6660]
The halftime icon looks like this when it's not selected

![Screenshot 2019-10-29 at 16 34 06](https://user-images.githubusercontent.com/10684786/67788351-11958600-fa6a-11e9-81fa-6d3573b3dbaa.png)

Because of the way the hourglass is tilted, when glancing at all mods, it can look like it is selected.

When your eyes/subconscious notice this, you are forced to double check.

Double-checking this is a bit annoying and distracting.

The icon should be changed slightly so this is less of a problem. (Personally I think an upright hourglass would look good, the sand within is already slanted anyway so it will still have that "whacky" fun feeling)

**Comment by peppy** [comment]
All mod icons are getting a redesign in the near future.
