### ISSUE TITLE
How much of the beatmap editor is meant to be working atm?

### ISSUE THREAD

**Issue by theonlygusti** [ppy/osu#6661]
I can't seem to get much of the editor working.

If I edit another song, I can play the song, but I don't know how to make a new beatmap for one of my own songs.

I can put hit objects, but I can't undo anything (trying cmd-z), I can't delete them once they're placed (trying backspace, cmd-backspace, after selecting with the "select" tool). I can't figure out how to save any changes either. Maybe I am meant to export it and then re-import it?

Is there a public page somewhere that documents how much functionality should currently be available, and when it's planned to add more?

**Comment by peppy** [comment]
editor is a wip
