### ISSUE TITLE
Spinners and touchscreens

### ISSUE THREAD

**Issue by EmattpoYou** [ppy/osu#6665]
**Describe the bug:** 
If you put 2 or more fingers/pens on a touchscreen (laptop, tablet, etc), it recognizes it as clicking (or dragging) to the touch points. This can be used to get 700 spins per minute.
**Screenshots or videos showing encountered issue:** 

https://youtu.be/Jy8j_o9EDWg

**osu!lazer version:** 
2019.1029.0

**Comment by peppy** [comment]
Known issue, will be solved with proper touch support at a framework side (WIP).
