### ISSUE TITLE
USB OTG cable input devices (Android)

### ISSUE THREAD

**Issue by ManuelZuttion** [ppy/osu#6674]
Playing with touchscreen is pretty difficult on my phone so I tried connecting mouse and keyboard to it through an OTG cable and a USB hub. I was disappointed to see that it simply did not work...
I think it would be nice to see those input sources implemented on Android osu!Lazer.

Maybe RAW input could support tablets too?

**Comment by bdach** [comment]
Essentially a duplicate of ppy/osu-framework#2863; closing as such and expanding scope of framework issue.

Please note we are not currently accepting mobile issues; you should have seen a warning about that when submitting this report.

**Comment by enoslayd** [comment]
Actually it works for me but to play it you need to disable Mouse buttonns and keep on pressing the left mouse button while hovering over notes
