### ISSUE TITLE
Osu!Lazer wont start

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#6675]
**Describe the bug:** 
Osu!Lazer wont keep going after "This is an Early development build" message
**Screenshots or videos showing encountered issue:** 
Video attached 
[Osu!Lazer Wont Start.zip](https://github.com/ppy/osu/files/3792115/Osu.Lazer.Wont.Start.zip)

**osu!lazer version:** 
app-2019.1029.0
**Logs:** 
%appdata%/roaming/osu  
[%appdata% roaming osu.zip](https://github.com/ppy/osu/files/3792135/appdata.roaming.osu.zip)

%appdata%/local/osulazer
[%appdata% local osulazer.zip](https://github.com/ppy/osu/files/3792136/appdata.local.osulazer.zip)

PC infomation
![PC infomation](https://user-images.githubusercontent.com/56265123/67918596-f052a800-fbd7-11e9-9b88-1547b24ac43e.PNG)

**Comment by peppy** [comment]
Your audio device is probably broke. Try changing the default audio output in windows and see if it helps.

**Comment by Kiddo-Kris** [comment]
I has changed setting to default setting and disconnected extra device,but seems not working

**Comment by Kiddo-Kris** [comment]
Sorry that I made a missstake, the game **will start**,but **wont loading** after the message showed,it keep at black screen and nothing happen,

**Comment by Game4all** [comment]
Out of curiosity, does applying the steps 
described in this comment https://github.com/ppy/osu/issues/5866#issuecomment-526224867 make the game boot to main menu?. If so, this is definitely something to do with your audio device.

**Comment by Kiddo-Kris** [comment]
> Out of curiosity, does applying the steps
> described in this comment #5866 (comment) make the game boot to main menu?. If so, this is definitely something to do with your audio device.

sorry but I cant find [game.ini] file in osu!lazer or osu!stable

**Comment by Kiddo-Kris** [comment]
It did fix,but no sound played.
I tried to reinstall my sound driver and disable or enable my devices but not working at all.

**Comment by iiSaLMaN** [comment]
Does osu!stable work fine with **audio**?

**Comment by Kiddo-Kris** [comment]
> Does osu!stable work fine with audio?

yes,osu!stable and other games work well

**Comment by Kiddo-Kris** [comment]
ok I changed my setting and now is totally fixed
