### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by manmathew** [ppy/osu#6695]
When I try to sign in to osu! lazer, it hangs on the "attempting to connect" for about 20 seconds, and then returns to the sign in. I had the problem yesterday, but I noticed that I still had stable open then. I don't have stable open today, so I am unsure of why it won't work. I didn't have this problem with previous versions of lazer.

[https://www.youtube.com/watch?v=2_-CJaR30Yo&feature=youtu.be](url)

2019.1029.0

I am unsure of where I can find the logs or any sort of information that might help solve the problem. I'd love to find any important files and give them to you if you can instruct me on how to get them (sorry, I'm inexperienced with programming).

**Comment by Altenhh** [comment]
The logs file can be located in your %appdata% folder (%appdata%/osu/logs)

**Comment by manmathew** [comment]
I believe those log files are for osu! stable, however in case I am wrong, which file should I upload?

**Comment by Altenhh** [comment]
no the logs for osu!stable is in the local appdata. upload `network.log`, this will give us information on your problem.

**Comment by manmathew** [comment]
[network.log](https://github.com/ppy/osu/files/3800076/network.log)

**Comment by manmathew** [comment]
Started working even though I didn't do anything. I'll close this, but if it happens again I'll reopen it.
