### ISSUE TITLE
Music Controller

### ISSUE THREAD

**Issue by arflyte** [ppy/osu#67]
![](https://puu.sh/rHfWc/5b0bdc0b6b.png)

The music controller displays and controls the playback of the background music, attached to the lower right of the screen.

The music controller is accessible via clicking the music icon on the chatbar or the shortcut key.
## Controller

![](https://puu.sh/rHg0B/e9ca4eda00.png)

The dimension of the box is 400*130 with 5px corner radius. Beatmap's background image is used for the background, center aligned, with 50% black overlay on top.

Song title (20px Exo 2 Medium Italics, followed by Artist name in the next line (12px Exo 2 Bold Italic).

The controller section is 50% black bar 50px high inclusive of 10px orange high progress bar occupying the bottom section. The middle controller buttons are Prev, Play/Pause and Next.

When skipping tracks, the background image slides left or right accordingly.

The hamburger button on the right displays the search function and playlist. Buttons goes orange when the playlist window is displayed.
## Playlist

![](https://puu.sh/rHgLy/1d593d5ee5.png)

Song Search Box. The results are displayed in the playlist.

Collection List. Dropdown list that lists out player's song collection.

Playlist. Song Title (14px Exo 2 Regular, White), followed by Song Artist (12px Exo 2 Bold, #999). 10px indent for line breaks. Orange song title for current track.

![](https://puu.sh/rHhtR/c6c2bc6209.png)

Hamburger icon appears on hover, allows the track to be rearranged in the list by dragging the icon.

**Comment by UselessToucan** [comment]
Looks great. I would like to implement it. :)

**Comment by peppy** [comment]
Before you take this on, keep in mind it needs to be developed *component by component*. That means that we need:

- A search textbox
- A filtering search list
- A dropdown menu

At very least the dropdown should first be implemented at a framework level (without styling).

Then each piece of this UI should be implemented in individual classes, such as

- MusicController (bottom half)
- PlaylistController (top half)
- PlaylistItem

It will also need better implemented database access and some other things no doubt. Start small and don't skip ahead to implementing the UI recklessly without first having the underlying infrastructure in place.

**Comment by lunafreya** [comment]
Would like to also add that as shown (very little exposure) in the teaser trailer, the "music controller" thingy (I'll henceforth dub it the osu! in-game music player) can also be seen at the top menu bar (only evident at the song select screen and other places other than the main menu, the play mode layer itself and the result screen).

**Comment by AstarothRekt** [comment]
Just wondering, why would `Extra Long Title` ([http://puu.sh/rI3fR/8b1e235101.png](url)), be tabbed in? it seems like it would look cleaner without the tab-in and it would still be readable/understandable

**Comment by swangboy55** [comment]
I'd like to contribute.

**Comment by ZLima12** [comment]
@swangboy55 then contribute. Get something working and make a pull request if you believe it is in good enough shape.

**Comment by shortthu** [comment]
could the button look bigger?

**Comment by amphineko** [comment]
I think it would be better using relative sizing units for text fields, instead of pixels.

**Comment by peppy** [comment]
Closing this as 99% complete
