### ISSUE TITLE
osu!lazer won’t launch

### ISSUE THREAD

**Issue by fairyboy21** [ppy/osu#6714]
**Describe the crash:** 
when i try to launch it... it doesn't open it just stop working i dont have a log and any pic to show you and i cant make videos
**Screenshots or videos showing encountered issue:** 
none
**osu!lazer version:** 
2019.1029.0
**Logs:** 
none
**Computer Specifications:** 
hp

**Comment by Gabixel** [comment]
Without logs or at least a video, we don't know what's the problem, and we cannot find a way to solve it (check `%AppData%/osu/logs`). Also if you can provide more info of your PC (Windows 10, 32/64 bit. etc.), it would be important.

**Comment by bdach** [comment]
In case of an absence of logs in the location mentioned above, please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by swoolcock** [comment]
Closing due to lack of details. Please attach a video and/or logs and reopen.
