### ISSUE TITLE
Tournament client crash on beatmap change

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#6715]
**Describe the crash:** 
The client crashed mid _**Showcase**_ and it resulted in a broken bracket.json file. (client refuses to open with it). It seems that it happened during a beatmap change. Here's the [link ](https://osu.ppy.sh/beatmapsets/694200#osu/1468735
)to it.

**Screenshots or videos showing encountered issue:** 
[Twitch VOD](https://www.twitch.tv/videos/503914535?t=0h51m47s)

**osu!lazer version:** 
somewhere around 2019.903.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3805812/runtime.log)
[bracket.txt](https://github.com/ppy/osu/files/3805818/bracket.txt) 

**Computer Specifications:** 
AMD Ryzen 7 2700X
RTX 2080 Ti
16GB RAM

**Comment by bdach** [comment]
Immediate cause is the presence of three empty JSON objects in the one of the beatmap sections (for finals, I think) on lines 3683-3685, removing them causes the tournament client to start. Unsure how those might have ended up there in the first place, however.

**Comment by peppy** [comment]
@l3lackShark were any manual edits made to the .json over the course of usage?

**Comment by l3lackShark** [comment]
@peppy No, there wasn't any manual changes to the file.
