### ISSUE TITLE
Hard crash when switching from the timing panel to the compose panel while editing an osu!mania beatmap.

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#6746]
Switching from the timing to compose tab **when a timing section is selected** when editing an osu!mania map hard crashes the game. More info in logs.
occurs in version 2019.1106.0
[Logs](https://www1.zippyshare.com/v/Y6CcEhKt/file.html)

i5-7500
GTX1060
8GB DDR4

**Comment by peppy** [comment]
Unrelated to timing panel. `HoldNoteSelectionBlueprint` is trying to access `DrawableObject.Head` / `DrawableObject.Tail` before the object has been loaded.

![image](https://user-images.githubusercontent.com/191335/68305283-bd824580-00ea-11ea-95e1-28538f040103.png)
