### ISSUE TITLE
Manually importing osu!stable data from wine emulator

### ISSUE THREAD

**Issue by gemverse** [ppy/osu#6751]
hello, sorry if this isn't the right way to go about this issue, i played osu!stable via wine before macos catalina came out and screwed up everything. osu!lazer can't find my osu!stable files. is there a way to manually import data from stable? if not, how can i get lazer to find my stable install?

**Comment by iiSaLMaN** [comment]
I believe checking whether we're running under wine isn't a thing anymore (check ppy/osu-framework#2936), and that marks this issue as impossible to fix.

**Comment by gemverse** [comment]
to clarify, stable was running on wine, i'm using the latest lazer build from this github. i've tried looking through as much of lazer's folders as possible and i can't find where to put anything.

**Comment by jai-x** [comment]
You can manually import beatmap files (`.osz`), skin files (`.osk`), and replay files (`.osr`) by dragging them into the running osu!lazer window. Support for automatic import from osu!stable is only available on Windows at the moment. Please note, that osu!direct is available free for anyone to use without supporter on osu!lazer, if that helps in getting your beatmaps imported.

**Comment by gemverse** [comment]
is there a way to "rezip" beatmaps after they've been opened? sorry if this is a dumb question but i tried to drop them in and nothing happened

**Comment by jai-x** [comment]
I'm not entirely sure what you mean. If you are trying to import the contents of the osu!stable `/songs/` folder, I don't believe that is supported.

**Comment by gemverse** [comment]
that's what i was trying to do, thanks anyways :') i think i'll just redownload the maps i was using (hopefully i won't lose any progress)

**Comment by jai-x** [comment]
Just to add onto this, dragging and dropping an existing osu!stable `/songs` folder or individual beatmap folders seems like a valid use case. This may be added in the future.

**Comment by bdach** [comment]
At this point there seems to be no viable user-facing way to do this, even with a hacky workaround/script. The mechanism to do this is already mostly in place though (see `LegacyDirectoryArchiveReader`).

The remaining work to allow arbitrary folder drag-and-drop would be to properly handle directory structures and recognize which directory holds what. I'd rather honestly allow a limited version of this, such as drag-and-dropping the entire stable directory triggering an import from stable in the same way it already works on Windows, but skipping the platform-specific paths and registry entry lookups and just using the user-provided path instead.

**Comment by peppy** [comment]
```
ln -s /Applications/osu!.app/Content/Resources/drive_c/osu\! ~/.osu;
```

This should allow you to import.

**Comment by peppy** [comment]
Closing as the above solution should be valid.
