### ISSUE TITLE
Can preview two songs at the same time in osu!direct

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#6757]
**Describe the bug:** I can get the game to play two songs at the same time in osu!direct.

Steps to reproduce:

1. Preview song 1
2. Preview song 2. This will stop song 1 as expected.
3. Preview song 1 when song 2 is still playing. This doesn't stop song 2.

**Screenshots or videos showing encountered issue:**
![Screenshot](https://i.imgur.com/krpFi0L.png)

**osu!lazer version:** 2019.1106.0

**Comment by iiSaLMaN** [comment]
Seems like the current logic to stop currently playing track is not fitting well with scheduling.., will take a look.

**Comment by iiSaLMaN** [comment]
Regressed in #6738, it seems that the current track is nullified in a scheduled stopped event causing it to be after the new track has been assigned to the current track, therefore the last track is never stopped.

**Comment by peppy** [comment]
Are you going to fix this one?

**Comment by iiSaLMaN** [comment]
Yes, I will try to.

**Comment by recapitalverb** [comment]
I just want to add that sometimes previewing songs doesn't stop the main music player either; reproducing the bug described above with a song already playing beforehand doesn't stop it:

![Screenshot](https://i.imgur.com/gShQgMa.png)

**Comment by iiSaLMaN** [comment]
Seems out of scope for this current issue, please consider opening another one for it.
