### ISSUE TITLE
support decimals in bpm

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#6759]
this is because osu!lazer doesn't show decimals in bpm

pictures to show:
![osu_2019-11-07_22-07-15](https://user-images.githubusercontent.com/44514667/68449097-727c3700-01ab-11ea-975e-b8c5fe747baf.jpg)
![import](https://user-images.githubusercontent.com/44514667/68449104-7b6d0880-01ab-11ea-8473-94a4473754bd.PNG)

**Comment by peppy** [comment]
I don't think any meaning can be drawn from decimal places so they should remain hidden.

**Comment by genericthing** [comment]
i still suggest the decimals should be shown because it's better to show the most accurate bpm rather than a rounded bpm

**Comment by peppy** [comment]
It's pointless as you cannot draw any useful information from it.
