### ISSUE TITLE
Launching game causes weird behaviour on KDE Plasma

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#6773]
**Describe the bug:** On Linux with KDE Plasma, launching the game causes the desktop environment to act weird. Closing the game makes it go away.

**Screenshots or videos showing encountered issue:**
For example, compositing seems to be one of the things that break when the game is running.
While it is not running: ![normal KDE](https://i.imgur.com/NL33tQp.png)

While it is: ![glitching KDE](https://i.imgur.com/2eB0w2t.png)
Notice that the background blur is gone, and there is also a weird gray border around windows and panels.

**osu!lazer version:** 2019.1106.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3825210/database.log)
[network.log](https://github.com/ppy/osu/files/3825212/network.log)
[performance.log](https://github.com/ppy/osu/files/3825213/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3825214/runtime.log)

**Comment by jai-x** [comment]
Since KDE uses wayland now, I'm guessing this *might* be an issue with how compositing works with xwayland, as the osu!lazer window will attempt to create an SDL Xwindow surface by default.

Try setting the environment variable `SDL_VIDEODRIVER` to `wayland` before running:

```shell
$ export SDL_VIDEODRIVER=wayland
$ dotnet run --project osu.Desktop
```

**Comment by recapitalverb** [comment]
That seems to have fixed the problem - and also a lot of other things like tearing and such. I 
 found that it's nice to change the launch command for the game to something like `SDL_VIDEODRIVER=wayland /usr/bin/osu-lazer %F` and it will work fine.

Is is possible to change how osu!lazer behaves so that it doesn't cause this problem without having to set `SDL_VIDEODRIVER` to `wayland` before every launch?

**Comment by jai-x** [comment]
Default support for wayland has been raised before in this issue https://github.com/ppy/osu/issues/5198 

This may not be fixed soon though, as it would require changes to the `osuTk` graphics library that we will eventually move away from in favour of `veldrid`.

**Comment by bdach** [comment]
Since the issue linked by @jai-x above looks to be pretty much the same thing I suppose I'll close as duplicate. But yes, this will be also closely tied to ppy/osu-framework#2448, since other video backends might also need to autodetect and properly handle wayland.
