### ISSUE TITLE
Approach circles appear inside circle after hit time

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6775]
If a circle is not hit, and a semi-transparent hit circle skin is active, the approach circle will be seen inside the circle after its time.
![image](https://user-images.githubusercontent.com/32612290/68518735-1200fe80-026c-11ea-9ca7-bd99b79b07bd.png)
![image](https://user-images.githubusercontent.com/32612290/68518792-686e3d00-026c-11ea-9838-b277d6289682.png)
Not sure if intentional, but very distracting.

**Comment by peppy** [comment]
Please attach the skin.

**Comment by MightyHelper** [comment]
[MHSkin1-Reduced.zip](https://github.com/ppy/osu/files/3826764/MHSkin1-Reduced.zip)
(osz)
Removed all sounds ( .wav ) to make file lighter

**Comment by peppy** [comment]
Thanks for the skin. This is due to oversized approach circles. This is being tracked via https://github.com/ppy/osu/issues/2358.
