### ISSUE TITLE
Visual - Cursor rotate option

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6776]
**Describe the new feature:** 
On osu!stable the cursor rotates arround it's centre.
**Proposal designs of the feature:** 
It makes the cursor look less boring in low star maps and when the cursor is textured.

**Comment by MightyHelper** [comment]
After a bit of digging, I found that this is actually implemented in stable in the form of an option in the `skin.ini`.
```cson
...
CursorRotate:1
...

```
Should this be now considered a **Bug**?

**Comment by bdach** [comment]
A lack of implementation isn't really a bug. Please be patient, this will make its way into lazer eventually like other legacy skinning aspects that are pending implementation.
