### ISSUE TITLE
Input - Keyboard keys in pause menu

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6777]
**Describe the new feature:** 
In the pause menu, the only way to select an option is to:
**use up and down arrows** and **enter**, or
move the **cursor** and **click**.
I suggest that you can
move the **cursor** and use the **hit keys ( x+z by default)** to select.

**Comment by bdach** [comment]
I suppose the pause menu is another place to add support for the existing *Select* keybinding (see #3551). Going to group all similar requests under that and close this as duplicate.
