### ISSUE TITLE
Alt+Scroll wheel to change volume in song selector.

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6779]
**Describe the new feature:** 
In the song selector Scroll wheel scrolls the songs.
I suggest that Alt+Scroll should act like Scroll in the main menu or in-game.

(Sorry that I'm posting a lot of issues and suggestions one after another like this, I just was making a list and I finally got round to doing it.)

**Comment by bdach** [comment]
Unsure if we want this. For now volume can be controlled by using the scroll wheel on non-scrolling elements of the screen (like the footer, toolbar or beatmap wedge).

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/2869
