### ISSUE TITLE
Pressing express button on Wacom tablet closes game

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#6783]
**Describe the crash:** Pressing any express buttons on my Wacom tablet closes the game.

**Screenshots or videos showing encountered issue:** ![Output in console](https://i.imgur.com/AQ6m9N7.png)

**osu!lazer version:** 2019.1106.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3827222/database.log)
[network.log](https://github.com/ppy/osu/files/3827223/network.log)
[performance.log](https://github.com/ppy/osu/files/3827224/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3827225/runtime.log)

**Computer Specifications:**
Tablet: Wacom Intuos Art Small (CTH 490)
Tablet driver: [xf86-input-wacom](https://www.archlinux.org/packages/?name=xf86-input-wacom)
OS: Arch Linux x64
Kernel: 4.19.81-1-lts
Resolution: 1920x1080
DE: Plasma
WM: KWin
CPU: Intel i5-9400F (6) @ 4.100GHz
GPU: NVIDIA GeForce GTX 1650

**Comment by bdach** [comment]
This might be far out of our hands, as this looks like an xinput error, although [there seems to be an old bugzilla report for a similar crash](https://bugs.launchpad.net/ubuntu/+source/xinput/+bug/563457) that should have been fixed years ago. Would you mind running the following:
```bash
$ xinput --version
$ xinput list
$ xinput list props [id_of_device_from_xinput_list]
```
and attaching the output here?

**Comment by recapitalverb** [comment]
`xinput --version`:
```
xinput version 1.6.3
XI version on server: 2.3
```
`xinput list`:
```
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ Wacom Intuos PT S 2 Pen stylus            id=12   [slave  pointer  (2)]
⎜   ↳ Wacom Intuos PT S 2 Finger touch          id=13   [slave  pointer  (2)]
⎜   ↳ Wacom Intuos PT S 2 Pad pad               id=14   [slave  pointer  (2)]
⎜   ↳ Logitech USB Optical Mouse                id=15   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Power Button                              id=7    [slave  keyboard (3)]
    ↳ Sleep Button                              id=8    [slave  keyboard (3)]
    ↳ SINO WEALTH USB KEYBOARD                  id=9    [slave  keyboard (3)]
    ↳ SINO WEALTH USB KEYBOARD System Control   id=10   [slave  keyboard (3)]
    ↳ SINO WEALTH USB KEYBOARD Consumer Control id=11   [slave  keyboard (3)]
```
`xinput list-props 12/13/14`: [props.txt](https://github.com/ppy/osu/files/3827275/props.txt)

**Comment by bdach** [comment]
It all looks correct... A bit of a long shot, but could you try running lazer with `LD_DEBUG=all` and then attaching the dynamic linker console output here? I want to make sure there aren't any old library versions somewhere that could cause confusion.

Since I don't own the hardware it's going to be very hard to tell what this could be caused by if the linker log doesn't turn anything up.

**Comment by gonX** [comment]
Just FYI, it looks like you are using Wayland which seems to have some issues according to #5198.

It is likely the `xf86-input-wacom` driver does nothing as the `xf86` stands for XFree86 and therefore are meant for Xorg. Likewise for anything you're trying to do with `xinput` would potentially only affect applications using XWayland.

**Comment by recapitalverb** [comment]
@bdach Here you go, sorry that I couldn't upload the file directly because GitHub doesn't accept files over 10MB: https://drive.google.com/file/d/1XzbnWi19TpGJymtx3Z5J_KW69S2s9PQ0/view?usp=sharing

@gonX It seems like you are right, since I cannot reproduce this problem if I run `osu-lazer` without setting `SDL_VIDEODRIVER` variable to `wayland`.

**Comment by bdach** [comment]
Judging by this:
```
      5400:	symbol=XGetAtomName;  lookup in file=/opt/dotnet/dotnet [0]
      5400:	symbol=XGetAtomName;  lookup in file=/usr/lib/libpthread.so.0 [0]
      5400:	symbol=XGetAtomName;  lookup in file=/usr/lib/libdl.so.2 [0]
      5400:	symbol=XGetAtomName;  lookup in file=/usr/lib/libstdc++.so.6 [0]
      5400:	symbol=XGetAtomName;  lookup in file=/usr/lib/libm.so.6 [0]
      5400:	symbol=XGetAtomName;  lookup in file=/usr/lib/libgcc_s.so.1 [0]
      5400:	symbol=XGetAtomName;  lookup in file=/usr/lib/libc.so.6 [0]
      5400:	symbol=XGetAtomName;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
      5400:	symbol=XGetAtomName;  lookup in file=/usr/lib/libX11.so.6 [0]
      5400:	binding file /usr/lib/libX11.so.6 [0] to /usr/lib/libX11.so.6 [0]: normal symbol `XGetAtomName'
```
this is most likely going to be some wayland-x11 crosstalk getting in the way, and is most likely not a problem we can resolve here. I suppose if native wayland support happens then the x11 input interfacing part is *possibly* going to be replaced with something like `wlroots`?

Going to close as this is relatively low-priority anyways, let's treat #5198 as a catch-all for wayland-related problems for now.
