### ISSUE TITLE
Beats still heard when osu minimized and music paused in main menu.

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6784]
**Describe the new feature:** 
Beats still heard when osu minimized and music paused in main menu at the bpm of the last song you heard if when you minimized the client, the cursor was over the osu! logo

**Comment by bdach** [comment]
Can't reproduce - any way I try to minimize (tried <kbd>Win</kbd>+<kbd>D</kbd>, <kbd>Alt</kbd>+<kbd>Tab</kbd>, via taskbar), the window losing focus makes the beats stop for me. Mind providing more details (like game version, Windows version) and maybe a video of the bug?

**Comment by MightyHelper** [comment]
I can't seem to get it to happen again. Maybe it was to do with another application grabbing focus. Or the bug where you see the cursor and the windows mouse, and clicking has no effect( also a bug on sable ). I fixed this by doing Win+D, select and deselect desktop icon, Alt+Tab back to osu!, and now it is fixed.
However, this stopped happening in osu!lazer(it used to happen) it seems and I don't know why since it didn't update(Maybe Windows update?).
