### ISSUE TITLE
Hit lighting too small on custom skin

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#6786]
**Describe the bug:** 
The hit lighting is very small for some reason. 

**Screenshots or videos showing encountered issue:** 
Couldn't make one in the middle of gameplay... I think you might be able to test it yourself.
**osu!lazer version:** Latest
**Logs:** Don't think they are needed 
**Skin:** [tranquil sublimity.zip](https://github.com/ppy/osu/files/3827822/tranquil.sublimity.zip)

**Comment by naoey** [comment]
Fixed in [21ceb7f](https://github.com/ppy/osu/commit/21ceb7f85dbbffb771c443f394a98385a3b75b87)
