### ISSUE TITLE
Skin Preview

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#6787]
**Describe the new feature:** 
Some sort of a skin preview, like in the original osu! client. This will allow users to experience the skin, take note of the ~~bugs~~ implementation. This would reduce the amount of loading and work the user does significantly when testing out skins(maybe even from the upcoming osu skin store 🤞 ).

**Proposal designs of the feature:** 
I think it should be about the same as it is in osu!stable. There aren't any problems with the one from stable, and its not a bad idea. The only addition I can think of is the preview of the skin elements themselves, instead of just gameplay.

**Comment by jai-x** [comment]
While there isn't currently a skin preview mode, this can be easily replicated by:

1. Playing any beatmap with Auto mod enabled
2. Opening the options menu while the beatmap is playing with <kbd>Ctrl</kbd> + <kbd>o</kbd>
3. Using the options menu to pick a skin, which will apply while the beatmap is playing.

**Comment by EVAST9919** [comment]
Kinda relatable to https://github.com/ppy/osu/issues/5831

**Comment by AqilCont** [comment]
Yeah, I kind of realized that you can preview skins like how you mentioned while writing it...

**Comment by peppy** [comment]
As mentioned, previewing can already be done via settings. A skin editor is planned to allow inspecting skins in a more in-depth way, along with a better method of previewing (probably as part of https://github.com/ppy/osu/issues/4923).
