### ISSUE TITLE
Skin Elements

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#6788]
**Describe the new feature:** 
I would like to have the rest of the game-play elements to be implemented:
- Cursor Smoke
- All spinner elements
- Particles

I know you already are planning this, but I wanted to remind you because you seemed to be shifting your focus on other stuff without completing everything you were working on before.

**Proposal designs of the feature:**
You should add the elements into gameplay.

**Comment by EVAST9919** [comment]
I bet "shifting focus" was intentional.
Anyway, these elements are planned. Also you can track unimplemented features in https://github.com/ppy/osu/issues/988 (which is outdated, but still)

**Comment by peppy** [comment]
Please avoid making accusing / general issues like this.

One issue per issue, not compilation issues. Please do not talk about "focus" because that is up to us, not you.
