### ISSUE TITLE
Wrong key shown in Key configuration

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#6791]
**Describe the bug:** 
In Key Konfiguration when you change for ex. "Left click" to "y" it shows a "z" and other way arround ( using German keyboard layout ) used virtual keyboard just to show it its with a normal kb as well.  

**Screenshots or videos showing encountered issue:** 
https://streamable.com/9nmil

**osu!lazer version:** 
2019.1106.0
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3827983/runtime.log)

**Comment by swoolcock** [comment]
Likely to do with keyboard layout (qwertz/qwerty etc.) and related to https://github.com/ppy/osu-framework/issues/1965

**Comment by swoolcock** [comment]
Closing as duplicate for now.
