### ISSUE TITLE
Can i move osu!lazer folders (in Local and Roaming) to "D" drive?

### ISSUE THREAD

**Issue by vladciphersky** [ppy/osu#6792]
My "C" drive is very small, and i move osu!stable to drive "D". Can i move the osu!laser there too?
![image](https://user-images.githubusercontent.com/32297717/68540564-f43fb080-03b5-11ea-9e7e-a000e0f82349.png)

**Comment by mcendu** [comment]
Possibly implement a way in options/config files to allow changing the data directory for lazer?

**Comment by peppy** [comment]
Please look into symlinks or junctions as a temporary solution. And please [search next time](https://github.com/ppy/osu/issues/5121).
