### ISSUE TITLE
heavy memory issue, pls fix...

### ISSUE THREAD

**Issue by RzoregDe96** [ppy/osu#6794]
**Describe the bug:** 
this particular version is chewing my ram heavily than it's previous version, it gets on 2mil k readings on my task manager... and it's loading slower and sometimes lagging and not responding... pls fix...
**Screenshots or videos showing encountered issue:** 
none
**osu!lazer version:** 
2019.1106.0
**Logs:** 
too big, it's 30.9MB

**Comment by huoyaoyuan** [comment]
In a word: bad performance.
When talking for performance, please tell your hardware at least. And the operation you are doing.

**Comment by RzoregDe96** [comment]
no running backgrounds, and only running osu!lazer

win 7 x64, 4gb ram
amd a4-3400 apu

**Comment by huoyaoyuan** [comment]
Maybe related to #6795 , as 4GB is quite small for x64.
