### ISSUE TITLE
"No key bound" on play/pause key bind pressed

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6798]
**Describe the bug:** 
I have bound Play/pause in the main menu to C ( like stable ), and when I press it, it will do as expected but it states that no key is bound to it.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/32612290/68547995-f9f1c200-03c6-11ea-87f0-10fffd918457.png)
**osu!lazer version:** 
2019.1106.0

**Comment by Game4all** [comment]
This is intended for now as there is no way to retrieve which key combination was used to trigger an action
