### ISSUE TITLE
Cursor ripples

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6799]
**Describe the new feature:** 
On click, add ripples like in osu!stable.
**Proposal designs of the feature:** 
I suggest you make this togglable in settings.

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/5070

**Comment by iiSaLMaN** [comment]
Adding to that, please consider searching for existing issues to avoid opening duplicates.

**Comment by MightyHelper** [comment]
Oops yeah. Sorry.
