### ISSUE TITLE
Replace all Console.WriteLines with Logger.Log

### ISSUE THREAD

**Issue by peppy** [ppy/osu#68]

**Comment by iamanai** [comment]
I would be willing to do this, but I'm at school for the next eight hours. Someone else will probably beat me to it.

**Comment by SirCmpwn** [comment]
Doubtful. It's all you, guy.

**Comment by iamanai** [comment]
Well then I'll get working on it after I get home.

**Comment by peppy** [comment]
either commit a fix, ask a question, or don't talk please. no need to call dibs on issues. useless spam.

**Comment by ZLima12** [comment]
I believe this issue can be closed now.
