### ISSUE TITLE
Add ability to replay intro songs

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6800]
**Describe the new feature:** 
I would like the music player ( from the main menu ) to have a repeat toggle so that when the song reaches the end it repeats. ( Also love the new design )

Since it's related, could you add triangles and circles to the list of songs(because if you start osu!, open music player, click next song, then prev song, it's strange to get a different song)?

**Comment by bdach** [comment]
Intro songs are supposed to only play once per launch ([see comment](https://github.com/ppy/osu/issues/6337#issuecomment-537975145)).

**Comment by peppy** [comment]
I'm okay with making the intro tracks selectable from the playlist, but I do not believe we will be adding a repeat button.

**Comment by Gabixel** [comment]
(As a second proposal) Maybe a button under the "Intro Sequence" option (something like "Watch Intro") could be handy? In this way, you can play again the selected intro and its song. I've seen this kind of thing in a few games.

**Comment by MightyHelper** [comment]
I suggested it because I found myself writing a small python script that reads the osu! Songs folder and plays them in a loop as background music for coding, felt since Lazer was indev, could maybe suggest to add it.

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu/pull/9492.
