### ISSUE TITLE
Lazer not launching after install

### ISSUE THREAD

**Issue by AyeNash** [ppy/osu#6813]
I was trying to update to the latest version of Lazer to see if an issue I've been dealing with was fixed, once it got done reinstalling it never opened. it would launch then instantly end itself. I even tried deleting the whole osu Lazer install and reinstalling it. and that didn't work either

**Comment by bdach** [comment]
This is not nearly enough detail for us to begin helping you resolve this problem. Please state your system specifications and attach logs from either:
* `%AppData%/osu/logs` (on Windows),
* `~/.local/share/osu/logs` (on Linux and macOS).

**Comment by AyeNash** [comment]
Hp pavilion dv6 3225dx 
core i3, 4gb ram, integrated graphics
[runtime.log](https://github.com/ppy/osu/files/3833076/runtime.log)

**Comment by bdach** [comment]
The log you've attached looks to me like a cropped log from stable (it's missing the header), not from lazer (extrapolating by date format and the `GL Context` line which I can't see in my lazer logs). Are you sure you haven't mixed anything up?

**Comment by AyeNash** [comment]
i can't find logs in lazer? where would they be?

**Comment by bdach** [comment]
See my first comment: `%AppData%/osu/logs`, which should expand to something like `C:\Users\[username]\AppData\Roaming\osu\logs`.

If there is nothing in there, please attach Event Viewer logs instead.

**Comment by AyeNash** [comment]
[runtime.log](https://github.com/ppy/osu/files/3833137/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/3833138/update_success.log)
these are the only two things in my logs folder. and i found an error in event viewer 

Log Name:      Application
Source:        Application Error
Date:          11/11/2019 2:20:39 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Nash
Description:
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5d7bb03a
Faulting module name: coreclr.dll, version: 4.700.19.46205, time stamp: 0x5d7ace6c
Exception code: 0xc0000005
Fault offset: 0x00000000001b4523
Faulting process id: 0x1014
Faulting application start time: 0x01d598cd7b83f084
Faulting application path: C:\Users\monst\AppData\Local\osulazer\app-2019.1106.0\osu!.exe
Faulting module path: C:\Users\monst\AppData\Local\osulazer\app-2019.1106.0\coreclr.dll
Report Id: 930cf567-6452-4789-bd17-6038c4de5434
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-11-11T20:20:39.677376300Z" />
    <EventRecordID>93264</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Nash</Computer>
    <Security />
  </System>
  <EventData>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5d7bb03a</Data>
    <Data>coreclr.dll</Data>
    <Data>4.700.19.46205</Data>
    <Data>5d7ace6c</Data>
    <Data>c0000005</Data>
    <Data>00000000001b4523</Data>
    <Data>1014</Data>
    <Data>01d598cd7b83f084</Data>
    <Data>C:\Users\monst\AppData\Local\osulazer\app-2019.1106.0\osu!.exe</Data>
    <Data>C:\Users\monst\AppData\Local\osulazer\app-2019.1106.0\coreclr.dll</Data>
    <Data>930cf567-6452-4789-bd17-6038c4de5434</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by bdach** [comment]
You're still attaching stable logs for some reason, but the event viewer message seems to be legitimately originating from lazer. Since it broke after updating and you're on an Intel card, I'm guessing this is going to be another instance of #6496, and therefore I'll close this as such. Please reopen if reverting to 2019.930.0 or earlier again does not fix the problem.
