### ISSUE TITLE
Automatic bookmarks for replays

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#6827]
**Describe the new feature:** Mainly for evaluation of plays. There could be some bookmarks added automatically that you can see on the scrub bar and click them to jump to that part of the song.
I was thinking of having bookmarks for these situations:
- Loss of 100%
- Chokes
- Misses
- Maybe some other stuff idk

**Proposal designs of the feature:** 
(Icons are illustrations)

![image](https://user-images.githubusercontent.com/15932372/68690462-5b09c900-0572-11ea-9e85-c2aa633d0bfe.png)

**Comment by bdach** [comment]
Already planned, see #5681. Closing.
