### ISSUE TITLE
opening osu!direct crashes the game  

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#6831]
**Describe the crash:** 
Open osu!direct and it crashes ( doesnt matter if logged in or not )

**Screenshots or videos showing encountered issue:** 
https://streamable.com/1nrak

**osu!lazer version:** 
commit 70a02d2

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3839225/runtime.log)

**Computer Specifications:** 
i3 6100, 8GB RAM, Windows 10 x64 1909 GTX1050Ti

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu/pull/6830
