### ISSUE TITLE
Negative outcomes in Don't Stop Me Now don't play.

### ISSUE THREAD

**Issue by nathanielcwm** [ppy/osu#6842]
**Describe the bug:** 
Instead of playing the negative outcome the storyboard continues with the intended outcome at the HP checks.

**Screenshots or videos showing encountered issue:** 
Expected:
https://gfycat.com/bareinfatuatedinsect
Actual:
https://gfycat.com/helplessconfusedhedgehog

**osu!lazer version:** 
2019.1113.0

**Logs:** 
[network.log](https://github.com/ppy/osu/files/3841541/network.log)
[performance.log](https://github.com/ppy/osu/files/3841542/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3841543/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3841544/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3841545/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3841546/performance-gamethread.update.log)
[updater.log](https://github.com/ppy/osu/files/3841548/updater.log)
[database.log](https://github.com/ppy/osu/files/3841549/database.log)

**Comment by bdach** [comment]
There are some z-ordering mishaps visible there too (another case of #6415).

**Comment by bdach** [comment]
Upon investigation this seems to be caused by `DrawableStoryboard.Passing` never actually being set during gameplay:
https://github.com/ppy/osu/blob/378f8103fbaad88cb731bef12ea3a70e4311af4c/osu.Game/Storyboards/Drawables/DrawableStoryboard.cs#L26-L36

**Comment by peppy** [comment]
I believe this hasn't yet been implemented, as observed above.
