### ISSUE TITLE
Still able to click circles when player are dead

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#6850]
**Describe the bug:** 
Still able to click circles when player are dead

**Screenshots or videos showing encountered issue:** 
[Still able to click circles.zip](https://github.com/ppy/osu/files/3844944/Still.able.to.click.circles.zip)

**osu!lazer version:** 
app-2019.1113.0

**Logs:** 
[logs.zip](https://github.com/ppy/osu/files/3844946/logs.zip)

**Comment by peppy** [comment]
This is intended.
