### ISSUE TITLE
Hellish Mod

### ISSUE THREAD

**Issue by nathanielcwm** [ppy/osu#6859]
**Describe the new feature:** 
Combination of Easy and Hard Rock
**Proposal designs of the feature:** 
Decrease Circle Size + AR. Raise OD and HP.
No revive.

**Comment by Faithy3** [comment]
That sounds awful. I love it.

**Comment by peppy** [comment]
This is jut another combination of modified difficulty values. We plan on allowing changing these using mod-level configuration, rather than introducing many new mods. Check #4924.
