### ISSUE TITLE
Pressing ESC after finishing beatmap causes game to not exit back to beatmap selection menu

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#6865]
**Describe the bug:** After playing a beatmap and the song is over but the game has not gone back to the beatmap selection menu yet, pressing ESC causes the game to stay in that screen. Pressing ESC again exits the game and progress is lost.
**osu!lazer version:** 2019.1113.0
**Logs:** 
[database.log](https://github.com/ppy/osu/files/3854148/database.log)
[network.log](https://github.com/ppy/osu/files/3854152/network.log)
[performance.log](https://github.com/ppy/osu/files/3854150/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3854151/runtime.log)

**Comment by huoyaoyuan** [comment]
Also reproduces for watching replay.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/7362.
