### ISSUE TITLE
High UI Scale causes beatmap details panel to not act properly

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#6866]
**Describe the bug:** Adjusting UI Scale to a value higher than about 1.5x causes problems in the beatmap details panel.
**Screenshots or videos showing encountered issue:**
![image](https://user-images.githubusercontent.com/41869184/68993067-2c5b5d80-08a6-11ea-9d1b-6d041cbc8946.png)
**osu!lazer version:** 2019.1113.0
**Logs:** 
[database.log](https://github.com/ppy/osu/files/3854157/database.log)
[performance.log](https://github.com/ppy/osu/files/3854158/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3854159/runtime.log)
[network.log](https://github.com/ppy/osu/files/3854160/network.log)

**Comment by bdach** [comment]
Duplicate of #4931.
