### ISSUE TITLE
Video is sometimes just a black screen.

### ISSUE THREAD

**Issue by nathanielcwm** [ppy/osu#6868]
**Describe the bug:** 
Sometimes instead of playing the video the background is just a black screen

**Screenshots or videos showing encountered issue:** 
https://osu.ppy.sh/beatmapsets/14898:
The video for this map only starts part of the way in and the normal background is displayed before this time.
![image](https://user-images.githubusercontent.com/22572406/69002247-4046a400-0926-11ea-8998-4dd73472ff32.png)
![image](https://user-images.githubusercontent.com/22572406/69002259-8f8cd480-0926-11ea-9f06-bbe531b5d423.png)
![image](https://user-images.githubusercontent.com/22572406/69002261-99aed300-0926-11ea-86a6-1b7265532706.png)

https://osu.ppy.sh/beatmapsets/267995:
![image](https://user-images.githubusercontent.com/22572406/69002291-63be1e80-0927-11ea-9988-4ee6b8af6859.png)
![image](https://user-images.githubusercontent.com/22572406/69002296-759fc180-0927-11ea-9ea0-a89b2e37f299.png)

https://osu.ppy.sh/beatmapsets/28687:
![image](https://user-images.githubusercontent.com/22572406/69002329-0080bc00-0928-11ea-87d1-c2000cd22b27.png)
![image](https://user-images.githubusercontent.com/22572406/69002324-ee9f1900-0927-11ea-9725-42d036cad443.png)

https://osu.ppy.sh/beatmapsets/29426
https://osu.ppy.sh/beatmapsets/404204
https://osu.ppy.sh/beatmapsets/6535 (I'm certain this one has a video but instead of a black screen it shows the lazer background)
https://osu.ppy.sh/beatmapsets/12756
https://osu.ppy.sh/beatmapsets/641285

**osu!lazer version:** 
2019.1113

**Logs:** 
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3855179/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3855180/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3855181/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3855182/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3855183/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3855184/updater.log)
[database.log](https://github.com/ppy/osu/files/3855185/database.log)
[performance.log](https://github.com/ppy/osu/files/3855187/performance.log)

**Comment by huupoke12** [comment]
Which do you want to describe with "sometimes"?
If it happens for some beatmaps (and always happens for that beatmap) but not the others then it might be a duplicate of https://github.com/ppy/osu/issues/6099
If it's still the same beatmap but video sometimes plays and sometimes not, then it isn't.

**Comment by bdach** [comment]
Except for [this map](https://osu.ppy.sh/beatmapsets/6535) these are just cases of #6099 - all the other have `.flv` videos. Unsure what causes the remaining one, on stable it plays during the first break.

**Comment by nathanielcwm** [comment]
oh yep it's a dupe of #6099 sorry

**Comment by huupoke12** [comment]
I have tried that map. After inspecting it, I see its Video and Background Event was not being written to the .osu files, instead they are written to a seperate .osb (storyboard) file. So I moved it to the .osu files and it works fine now (both BG and Video).
