### ISSUE TITLE
Crash after use shadowplay record

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#6869]
**Describe the crash:** 
Crash after use shadowplay record

**Screenshots or videos showing encountered issue:** 
Sorry that I cant capture on PC,so I used my phone
[Crash.zip](https://github.com/ppy/osu/files/3855311/Crash.zip)

**osu!lazer version:** 
app-2019.1113.0

**Logs:** 
[LOG.zip](https://github.com/ppy/osu/files/3855312/LOG.zip)

**Computer Specifications:** 
![SYSTEM](https://user-images.githubusercontent.com/56265123/69004342-c1b12d00-094c-11ea-8bed-4de987552bc2.png)

**Comment by bdach** [comment]
Logs look clean. Please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by Kiddo-Kris** [comment]
![image](https://user-images.githubusercontent.com/56265123/69008030-bed02f80-0980-11ea-9760-94d19b469ea5.png)
sorry I didn't find _Actions_ pane

**Comment by bdach** [comment]
![image](https://user-images.githubusercontent.com/20418176/69008223-6ed57680-0948-11ea-8a69-0f8b80fb5267.png)

**Comment by Kiddo-Kris** [comment]
[Application Events.zip](https://github.com/ppy/osu/files/3855600/Application.Events.zip)

**Comment by bdach** [comment]
Event logs seem to suggest this was the NVIDIA OpenGL driver dying:
```
A large number of errors have been detected.
The error threshold has been exceeded and recovery is no longer possible.
This could indicate a serious problem. The application must close.


Error code: 1
 (pid=14848 tid=22440 osu!.exe 64bit)
```
Please try to check for graphics drivers updates and see if installing a newer version (if available) fixes this problem. Otherwise this might well be out of our hands and need reporting to NVIDIA.

**Comment by nautzz** [comment]
Also having the exact same issue, [here's the Windows Event Logs.](https://m.put.re/SukCGjiu.zip)

**Comment by LeNitrous** [comment]
I don't experience crashes when using Shadowplay's record or instant replay feature. Tested in Windowed Mode, Exclusive Fullscreen and Borderless Fullscreen. I have a GeForce GTX 1050 Ti as a dedicated GPU. This also doesn't affect the framework as well as I was able to record my self-made game as well.

**Comment by smoogipoo** [comment]
This looks like an issue with your driver. Please update your driver and/or try posting on nvidia's forums. The following thread might be of use to you: https://nvidia.custhelp.com/app/answers/detail/a_id/3335/kw/crash/session/L3RpbWUvMTU3NDE0MjE2NC9zaWQvZlV5ZUlrNUhqSDIxT0VMS0JsaVdIUm40d3VCaUR2eFpmdkx2SmFydmk4MU5sZ19Nd1NjZlF2cmlaRmNjWENFaTlST0ZUYjhJcTRqMUN6NHlNVHE1elc4bENWel9Fd2tYSjZ3czM4dm9kYTFQJTdFNE1qdmRDYWpPNkElMjElMjE%3D
