### ISSUE TITLE
Key stuck

### ISSUE THREAD

**Issue by HDAcai** [ppy/osu#6870]
When playing a map, the key mapped as the left key on the keyboard will get stuck, therefore not registering the input and making the game nearly impossible to play.

**Screenshots or videos showing encountered issue:** 

2019.1106.0 

**Logs:**

**Comment by mcendu** [comment]
Is this hardware problem?

________________________________
发件人: HDAcai <notifications@github.com>
发送时间: Sunday, November 17, 2019 3:16:45 PM
收件人: ppy/osu <osu@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [ppy/osu] Key stuck (#6870)


When playing a map, the key mapped as the left key on the keyboard will get stuck, therefore not registering the input and making the game nearly impossible to play.

Screenshots or videos showing encountered issue:

2019.1106.0

Logs:

―

**Comment by HDAcai** [comment]
No, as I was able to change the mapped keys and the problem persisted. I was also able to type all of this in without a problem.

**Comment by bdach** [comment]
What input device are you using? Does this happen consistently? Do you have a reproduction scenario we could use here? I don't remember ever hitting anything like this when I played.

**Comment by HDAcai** [comment]
For the input I am using a amazon basics keyboard but it seems to be a game issue instead of a hardware issue. It does happen in every chart which makes the game almost unplayable since from then I only have the option to single tap. Going on to the pause menu seems to get the key unstuck but when I press it again it gets stuck.

**Comment by bdach** [comment]
We can't diagnose this off the information you have provided thus far. Please attach logs, state your platform/system specifications or record a video, preferably all of the above.

**Comment by HDAcai** [comment]
Using an IPad Pro 3rd gen 12.9 inch with 256 go of storage running IPadOS 13.3
![C0A8C20C-D8F1-4C1D-85D3-C723F2339C65](https://user-images.githubusercontent.com/57856097/69011484-98c67300-091f-11ea-9c3f-83d0134715ee.png)

**Comment by swoolcock** [comment]
Wired or Bluetooth?  I have the same model iPad and OS version and I’ve never seen this problem before with the Smart Keyboard, so maybe it’s a third party thing.

Either way, handling raw keyboard input is fiddly on iOS, so it may be a hard one to diagnose.

**Comment by HDAcai** [comment]
It’s wired running through a usb-c female to usb-a female adaptor.

**Comment by frenzibyte** [comment]
Tested on a wired 3rd-party keyboard (Keychron K4) and seen no issues of the sort. Safe to say this has long been fixed by switching to SDL and doing away with the private API that we used back then (which actually became public over time, the API being `GCKeyboard`), and/or the other method we used to do where we accept key input via text input. Either way, this shouldn't be an issue anymore.
