### ISSUE TITLE
More sorting options for osu!direct and Song Select 

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#6882]
**Describe the new feature:** 
I feel like osu!lazer could do with a bunch more sorting options, song selection and most importantly to me osu!direct, something along the lines of the options on https://osusearch.com

It could make finding maps of specific genres much easier, and it'd be some sort of dropdown (see proposal designs)

**Proposal designs of the feature:** 
![image](https://user-images.githubusercontent.com/33783503/69173173-24dec300-0af7-11ea-9e74-4346bdc44e79.png)
I didn't have enough time to make sure everything was aligned correctly and add them all, but thats my general idea

**Comment by bdach** [comment]
Song select sorting support is not yet complete and is being tracked at #4919. When it comes to direct there are a few issues with specific requests open already.

**Comment by peppy** [comment]
direct should match the web design.
