### ISSUE TITLE
[OSX] input issue

### ISSUE THREAD

**Issue by toutouyoutoo** [ppy/osu#6887]
hi, after activating raw input, the ingame cursor froze. mouse or trackpad, none is capable of moving the cursor.
I now can't go back even uninstalling/reinstalling the game does not change anything(maybe a settings file is hidden somewhere).

**Comment by swoolcock** [comment]
Duplicate of #6845, please search in future.

Press Ctrl+Alt+R.

**Comment by toutouyoutoo** [comment]
@swoolcock sorry i'm new on GitHub i searched in the issue tab but found nothing about OS X, thanks a lot
