### ISSUE TITLE
Descriptive settings search

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#6888]
**Describe the new feature:** 

Searching in settings is inconvenient because it only filters using the description text. Having a set of keywords associated with an option would be good.

For example, when searching for UI scaling, "scal" or "scaling" is accepted but "scale" is not.

![image](https://user-images.githubusercontent.com/27663662/69211265-a2670980-0bb1-11ea-84aa-5a21288143f4.png)
![image](https://user-images.githubusercontent.com/27663662/69211298-bad72400-0bb1-11ea-9878-fdceade8329c.png)

Other similar cases:
- Frame limiter settings with "fps"
- Audio device selector with "speaker"
- Volume sliders with "sound"
- Mouse sensitivity slider with "speed"

**Comment by peppy** [comment]
Keywords can easily be added. Please go ahead.
