### ISSUE TITLE
Import files from game

### ISSUE THREAD

**Issue by VPeruS** [ppy/osu#689]
How about to add something like this and point people at first start that they can import beatmaps with this thing?

![file](https://cloud.githubusercontent.com/assets/7927055/25555847/84bc74c2-2cf9-11e7-8cde-88279cfe198e.png)

**Comment by huoyaoyuan** [comment]
Currently we have drag&drop support on windows(how about other platforms?), and double-click support will come in future(I think).
I think it's a bad design to let user input the path.

**Comment by VPeruS** [comment]
Linux doesn't have d&d support. It just concept, maybe make it look like window file chooser.

**Comment by Jorolf** [comment]
You could just start osu with the file as an argument

**Comment by peppy** [comment]
How about we at least attempt to get file association and drag&drop support working on linux before resorting to this kind of this?

**Comment by VPeruS** [comment]
Ok. I understand.
