### ISSUE TITLE
Hidden cursor mod

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6894]
**Describe the new feature:** 
Mod that hides the cursor.
**Proposal designs of the feature:** 
Things to take into account
- Bad name(Pls suggest)
- RIP Mouse users (So maybe unranked?)
- Score multiplier (Could be unranked soo?)
- Maybe show light cursor trail?
- Before the song starts need cursor to adjust dim and so on...
- Pause every few secs to see the cursor on pause screen

**Comment by smoogipoo** [comment]
Could be implemented as a setting for the existing hidden mod.
