### ISSUE TITLE
Line endings to CRLF

### ISSUE THREAD

**Issue by peppy** [ppy/osu#69]
Currently in a bad state.

**Comment by huoyaoyuan** [comment]
Tabs to spaces, trailing whitespace and ending new line could be standardized in one PR.

**Comment by peppy** [comment]
Make it happen :).

We also need measures in place to make sure going forward the same issues don't crop up.

**Comment by huoyaoyuan** [comment]
It's easy to write a small tool for these things.
Is there any way to let CI system check this? That will help a lot.

**Comment by Shredder121** [comment]
Just my 2 cents.
If you change the `.gitattributes` to not use `-text` but `text` the resolving happens automatically.

If you then run `rm .git/index` and then `git reset` git rebuilds the index and applies all the eol conversions.

**Comment by ZLima12** [comment]
This issue can be closed now.

**Comment by peppy** [comment]
Actually let's leave this open until .gitattributes is updated with *.cs rules

**Comment by ZLima12** [comment]
@peppy Could it not be solved with a quick '*.cs text eol=crlf'?
