### ISSUE TITLE
Certain sliders cannot be loaded properly

### ISSUE THREAD

**Issue by TheNathannator** [ppy/osu#6909]
**Describe the bug:** 
Sliders that last as long as a normal hit circle would are incorrectly interpreted. These are used abundantly in [Aleph-0, mapped by Pikaquim](https://osu.ppy.sh/beatmapsets/791900#osu/1680610), which is the beatmap I encountered this bug with.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/1ildGeth6nc (I made this video when I suspected that it was the importation of the beatmap that caused the problem, but that may not be the case)
**osu!lazer version:** 
2019.1113.0
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3878033/runtime.log) (it's a download)

**Comment by smoogipoo** [comment]
I'd say lazer is acting exactly as expected here. This map is all kinds of messed up, from having near-0 BPM, to having infinity BPM, to having -1 length sliders. We have limited values to sane ranges to suppress stuff that completely breaks the game.

**Comment by TheNathannator** [comment]
That's understandable. I just thought I might bring this up just in case.
