### ISSUE TITLE
Fix AppVeyor integration

### ISSUE THREAD

**Issue by huoyaoyuan** [ppy/osu#6913]
Appveyor only collects warnings automatically when either
- specify `project: xxx.sln` in yml
- load their logger, which is only available for `MSBuild.exe` that runs at .NET Framework (the one shipped with VS)

Here're ways I've found to fix it:
#### Use some cake addin to report issues to AppVeyor.
I do find certain addin to do that. But, cake support for dotnet core is not so good. I haven't found necessary apis to setup the logger bridge in minutes, but nearly. If you prefer this I can still investigate it.

#### Don't use cake for build. Only use it for InspectCode.
Personally, I'm a non-fan of custom build scripts.

Unlike .NET Framework Era, in .NET Core we have `dotnet xxx` to drive everything. There's no need for custom scripts to simulate IDE commands in command line.
Let's have a peek about what's contained in the build processes:
- Build desktop components. It's perfectly covered by every IDE and `dotnet build`.
- Run unit tests. I tried the simple command `dotnet test Desktop.proj` and it works very well. We also carry settings for every IDE.
- Build/Test Xamarin components. Current cake script is even skipping them because of invoking `dotnet build` only! I've tested they are happy with VS MSBuild.
- Run tests with HttpBin. It's usually only running in CI, and can be handled perfectly by before_test/after_test.
- Publish to nuget. AppVeyor has a straight built-in support for it.
- Deploy Xamarin apps. Seems not executed by CI at all? Or at some other mac pool not integrated. 
- Run InspectCode. This is the only task that cake **doesn't make regressions**.

#### Don't use cake totally.
In fact InspectCode can be installed and invoked using nuget without cake. Due to the Windows-only fact, a ps1 should be enough.
The only difference with the old CI-only inspection is the way to install it. Not everyone has chocolatey, but everyone is definitely to have nuget.

**Comment by bdach** [comment]
I'm pretty sure the plan was to get rid of cake altogether eventually in favour of just stringing together `dotnet` CLI commands. Was not very high-priority at the time, though, and I'm not sure the lack of warnings changes that much.

**Comment by huoyaoyuan** [comment]
I treat compiler warnings as high-priority, because it's the fundament of cross-platform/IDE analyzers integrated into the compiler.

**Comment by bdach** [comment]
I'm not trying to downplay the importance of warnings, however the risks of potential disruptions in the process of replacing the build/deployment system are more severe in my opinion.
