### ISSUE TITLE
Anti-aliasing on selected beatmap dissapears on hover

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#6915]
**Describe the bug:** In the beatmap selection menu, selecting a beatmap and hovering over it causes its white outline to appear jagged.

**Screenshots or videos showing encountered issue:**
Not hovering:
![image](https://user-images.githubusercontent.com/41869184/69441603-a051a600-0d7d-11ea-8a3e-2a9e4b848be3.png)
Hovering:
![image](https://user-images.githubusercontent.com/41869184/69441684-b95a5700-0d7d-11ea-98a4-832b7da32907.png)

**osu!lazer version:** master branch, commit 4063135a3a894e262f880cca2b91904c51fb33c2

**Logs:**
[database.log](https://github.com/ppy/osu/files/3880374/database.log)
[network.log](https://github.com/ppy/osu/files/3880375/network.log)
[performance.log](https://github.com/ppy/osu/files/3880377/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3880378/runtime.log)

**Comment by algiuxass** [comment]
Just a thought... What if the skin is not anti-aliased and when you hover it shows original image and when you're not hovering it just scales down with anti-aliasing?
