### ISSUE TITLE
plans to search online maps within the app and play them?

### ISSUE THREAD

**Issue by theonlygusti** [ppy/osu#6918]
Currently it's necessary to visit websites (osusearch.com etc., browse forums looking for map packs and so on) to find beatmaps you may/may not even enjoy playing on.

Then you have to download these maps to a local folder somewhere, then drag and drop them into the app to finally be able to play them.

I'm hoping it will be supported that in the app I can just play all online maps: search/browse in online mode instead of local mode, choose map to play, it downloads, then you can play it. And maybe if OSU is using up too much space, less played maps get removed locally.

I think it would be nice to have map search and download integrated into the app.

**Comment by bdach** [comment]
You seem to be basically describing osu!direct, which is already a thing in lazer and doesn't even require supporter contrary to stable...?

**Comment by peppy** [comment]
Closing as already-available. osu!direct integration will be fornt and foremost in lazer for all  users (to some extent).
