### ISSUE TITLE
Replay button doesnt update when replay download finished

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#6928]
**Describe the bug:** 
Download a replay from the scoreboard. Button goes yellow and stays yellow even when the Notification says it finished downloading

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/17437302/69479390-e6018380-0dfc-11ea-9e92-374feae3a2ef.png)
![image](https://user-images.githubusercontent.com/17437302/69479394-eac63780-0dfc-11ea-9573-4c9c949fba6e.png)

**osu!lazer version:** 
2019.1122.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3882486/runtime.log)
[database.log](https://github.com/ppy/osu/files/3882487/database.log)

**Comment by Joehuu** [comment]
Regressed in https://github.com/ppy/osu/pull/6886.
