### ISSUE TITLE
Osu! Update seems to be corrupt..

### ISSUE THREAD

**Issue by Kittyneko-the-glitch** [ppy/osu#6930]
Hello, Kittyneko here. Unfortunately as of November 23rd, 2019. I cannot install the latest Android update because the package is corrupt. Can somebody tell me what is going on? Thanks.

**Comment by peppy** [comment]
Please try re-downloading. It was replaced a few minutes ago.

**Comment by Kittyneko-the-glitch** [comment]
Thanks peps, I'll meet you in #lazer chat! See you later!!!
