### ISSUE TITLE
I cant accsess my account

### ISSUE THREAD

**Issue by Elumati** [ppy/osu#6931]
**Describe the bug:** 
I type in my details to sign in and it doesn't let me sign in in would normally say attempting to connect but that didnt show and it made me type my details again and that kept happening 
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.1122.0
**Logs:**

**Comment by bdach** [comment]
Please double check that your credentials work on the osu! website and if they do, attach logs from lazer, located at:

* `%AppData%/osu/logs` (on Windows),
* `~/.local/share/osu/logs` (on Linux and macOS).

A video could also be helpful.

**Comment by Elumati** [comment]
I'm playing this on android if that helps :)

**Comment by bruh-droid** [comment]
it is logs Network Logs in android
[network.log](https://github.com/ppy/osu/files/3882568/network.log)

**Comment by bdach** [comment]
Since this is another episode of online being broken for xamarin/android, closing in favour of #6264.

**Comment by Kittyneko-the-glitch** [comment]
I also have this issue.. (〒﹏〒) hellllllpppp
