### ISSUE TITLE
Zipping Song Folder and Importing Puts All Songs Into One Set.

### ISSUE THREAD

**Issue by nathanielcwm** [ppy/osu#6936]
**Describe the bug:** 
I know this isn't intended at all but when I zip my entire song folder and import it the whole song list is shown as part of one beatmap set, leaderboards and ranking details all work as expected however.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/22572406/69480953-78c71000-0e47-11ea-8b3e-967cb0c63467.png)

**osu!lazer version:** 
2019.1122.0
**Logs:** 
*i accidentally restarted the game whoops lemme do that again*
[database.log](https://github.com/ppy/osu/files/3882605/database.log)

**Comment by nathanielcwm** [comment]
![image](https://user-images.githubusercontent.com/22572406/69480974-b88df780-0e47-11ea-9dda-449bbf1936fa.png)
The game thinks its all one beatmap too.

**Comment by peppy** [comment]
Please do not do this.

**Comment by nathanielcwm** [comment]
Just thought it was interesting that it actually worked.
