### ISSUE TITLE
"Show Online" button in social browser

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#6939]
**Describe the new feature:** 
In the Social Browser in osu!stable, it only shows online players.
I feel like this needs to be an option, if not planned already in osu!lazer's social browser, as i always message friends and its slightly annoying to have to search for that "online" tag.

![image](https://user-images.githubusercontent.com/33783503/69482502-26b8c700-0e14-11ea-988d-6838285f6575.png)
Just a checkbox around here, i guess

**Comment by peppy** [comment]
Design should be updated to match https://osu.ppy.sh/home/friends
