### ISSUE TITLE
Cant launch osu!Lazer in tournament mode since last update

### ISSUE THREAD

**Issue by PANIGE** [ppy/osu#6942]
**Describe the crash:** Cant launch osu!Lazer in tournament mode since last update, it just wont launch, i see it in task manager but it close 15 seconds later

[**Screenshots or videos showing encountered issue:**  ](https://youtu.be/WgcEwS09IRU)

**osu!lazer version:** 2019.1122.0

[**Logs:** ](http://93.6.41.243:2048/logs.zip)

**Computer Specifications:** 
CPU : I7 7700 3.6 Ghz turbo 4.0 Ghz
GPU : GTX 1070 Nvidia 8 Go
Ram : 16 Go DDR4 3000 Mz corsair vengeance
SSD1 : OS 118 Go
OS : Windows 10 [18362.476]

**Comment by peppy** [comment]
Please compile/run master or rollback temporarily.

**Comment by PANIGE** [comment]
After analysing, it come from bracket.json in roaming, it runs after deletion of that file
