### ISSUE TITLE
Distance Snap Grid causing crash when placing sliders.

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#6949]
**Describe the crash:** 
Game crashes in editor when placing sliders. This is not reproducable every time. Didn't happen on the osu lazer intro song beatmap. Video shows more details.
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=NzRNsElJAGc
**osu!lazer version:** 
2019.1122.0
**Logs:** 
https://pastebin.com/JBBMx29n
**Computer Specifications:** 
i7 6800k, GTX 1080, 16GB ram, 500gb ssd

**Comment by bdach** [comment]
Crash site will be here:
https://github.com/ppy/osu/blob/0804d8d7a45be9ba20618f2a6cfd3a6166df5d2f/osu.Game/Screens/Edit/Compose/Components/CircularDistanceSnapGrid.cs#L78
The lower clamping bound seems to have gone negative. Since `distance` is a constant, this'll most likely be due to negative `radius`/`DistanceSpacing`, so this might depend on the map being edited.

**Comment by bdach** [comment]
This is actually somewhat more complicated than I said above. The thing that's actually negative here is `MaxIntervals`. This arises when attempting to place a hitobject when another hitobject is in progress.

The snap grid operates on the assumption that when placement of the new object finishes, the next object will remain next. Now for reasons I'm not entirely certain of, this invariant is broken in such a scenario, and `StartTime` actually becomes *larger* than `nextHitObject.StartTime`, which I verified experimentally with logging:
```
2019-12-08 06:59:08: this: 50652.428571428565, next: 50292
```
Making `MaxIntervals` non-negative fixes the immediate crash but does not address the fact that placing objects at the same time as other objects doesn't appear to be fully working correctly. I might try to investigate further but I'm very unfamiliar with editor code and it could take me a while.

**Comment by smoogipoo** [comment]
I have a fix ready for this.
