### ISSUE TITLE
Left/Right clicking/holding & dragging combinations have an unexpected behaviour.

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#6950]
**Describe the bug:** 
I encountered this on the confirmation dialog when opening external links. Basically when you get prompted and click outside the confirmation dialog the expected behaviour, the dialog getting closed, is the outcome. 
While holding the left mouse button outside the dialog and dragging it into the dialog though, should not disgard the dialog, which is not the case. 
Holding the left mouse button and additionally holding the right mouse button and dragging the mouse outside the dialog closes the dialog, which should not happen. 

You can compare the general behaviour of how it should look like with the close button of any windows window. Dragging out the mouse, while holding the left mouse button over the close button does not close the window. Either does the combination with the right mouse button do.
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=ZnK1xEE-i5o
**osu!lazer version:** 
2019.1122.0
**Computer Specifications:** 
i7 6800k, GTX 1080, 16GB ram, 500gb ssd, Windows 10 64-bit Pro

**Comment by peppy** [comment]
Easiest solution is to probably dismiss the dialog on mouse down, not click.
