### ISSUE TITLE
Mods button content is not centred when there are mods selected

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#6953]
When there are mods selected, the right margin becomes shorter, making the contents look off-centre.

![Untitled](https://user-images.githubusercontent.com/15932372/69501096-cd2ec600-0f01-11ea-9063-bf06a74dd3ce.png)

**Comment by fixture94** [comment]
where is this written in?

**Comment by Joehuu** [comment]
The fix is in either `FooterButton` or `FooterButtonMods`. See https://github.com/ppy/osu-framework/wiki/Debug-Overlays:-Draw-Visualizer for finding drawable names.

**Comment by LucasSquassoni** [comment]
I'm brand new to the opensource game.
I've started to skim through the code. I'm having trouble setting up the VisualTest to help fix it. Could I get a direction to that?

Sorry if I've asked in the wrong place, please delete this if I've made a mistake. :)

**Comment by mcendu** [comment]
For .NET Core SDK:
`> dotnet run --project osu.Game.Tests`
Expect startup crashes if you are using Linux.
