### ISSUE TITLE
Automatically download beatmaps on installation

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#6967]
**Describe the new feature:** This would basically be the same as osu!stable preloading beatmaps upon installation of the game, when the game installs a few beatmaps from osu!direct (granted, this is a backlog consideration, this is just here for reference for the future)
**Edit**: Lazer should preload beatmaps that aren't already "preloaded beatmaps" in osu!stable. Simply put, the preloaded maps in Stable should be replaced with maps like it for Lazer, so instead of using the "Fright March" map, we could use "quaver" for something like that (I know, bad example, but it gets the point across)

**Proposal designs of the feature:** (Kinda already explained it)

**Comment by phosphene47** [comment]
I think this should be renamed as

> Automatically download some beatmaps on installation

because "preload" can be misunderstood for something else.

**Comment by X4X5** [comment]
> I think this should be renamed as
> 
> > Automatically download some beatmaps on installation
> 
> because "preload" can be misunderstood for something else.

Didn't realize that.

**Comment by Joehuu** [comment]
There is now the first run setup that guides you to download maps and is optional / not automatic. Personally, I like the new UX and always found it weird when clean installing stable that it forcefully downloads things out of the blue.

Not sure if that is the direction forward so I'm not closing myself.

**Comment by peppy** [comment]
The plan is to go with what we have no, yep. If anything the first run setup will become more user friendly rather than forcefully downloading anything.
