### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by zzzeddyzzz** [ppy/osu#6969]
I cant login into my account on osu!lazer.

 

![Screenshot_20191125-234810](https://user-images.githubusercontent.com/58180395/69555403-1a806580-0fde-11ea-9ee1-0babfcc17439.png)
![Screenshot_20191125-234807](https://user-images.githubusercontent.com/58180395/69555413-20764680-0fde-11ea-833a-bbc7d673d5e4.png)
![Screenshot_20191125-234803](https://user-images.githubusercontent.com/58180395/69555422-25d39100-0fde-11ea-89da-0c9082e30f08.png)

2019.704.0

(I dont know what logs is)

**Comment by jorolf** [comment]
Email login has been disabled afaik, use your username

https://twitter.com/osugame/status/1198819888556412928?s=19

**Comment by GSculerlor** [comment]
Related to #6964
