### ISSUE TITLE
crushed while build

### ISSUE THREAD

**Issue by wolfpat01** [ppy/osu#6971]
using CMD to build
its showing that when i enter
>dotnet run --project osu.Desktop
i tried using >dotnet restore but error showed up

osu!lazer v2019.1122.0

sorry i don't have the log but i have screenshots of it

windows 8.1 x86 tablet
this when i tried to build
![dfasdf](https://user-images.githubusercontent.com/57036855/69568890-cadd7200-0fbc-11ea-90a6-f5bca5ab3233.PNG)
this when i tried dotnet restore
![when i tried restore 1](https://user-images.githubusercontent.com/57036855/69568998-0a0bc300-0fbd-11ea-9013-14a4b60bb31b.PNG)
![when i tried restore 2](https://user-images.githubusercontent.com/57036855/69568999-0aa45980-0fbd-11ea-81d5-5293dac258ff.PNG)

**Comment by bdach** [comment]
This is a problem with restoring packages from NuGet, not with osu! per se. The URLs in the error messages work fine for me. Check your network configuration for any issues and try again.
