### ISSUE TITLE
Multiplayer host rotate

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#6975]
**Describe the new feature:** 
-

> Beatmap selector will be rotated automatically after a play

> A example:
> **_The room just open_**
>   Kiddo_Kris is the Host  (able to choose beatmap)
>   Kris_the_Kiddo is a player.  (unable to choose beatmap)
> 
> **_After 1 round of gameplay_**
> 
>   Kiddo_Kris **is still** the Host  (BUT **unable** to choose beatmap)
>   Kris_the_Kiddo **is still** a player.  (BUT **able** to choose beatmap)
> 

**Proposal designs of the feature:** 
-

- Host can choose use this option or not

- Host will NOT change but beatmap Selector will rotate

- Set up a select time limit to prevent player AFK to destroy the game experience

**Comment by LanTenDragon** [comment]
**How to prevent players that are AFK?**

Manual host rotations are quite an issue on stable already. When the host is rotated to an AFK player, you have no choice but to wait, or leave the lobby.

I propose an addition to this idea, which is at the start of the multiplayer room, everybody selects one beatmap at the start of a round. When the first round ends, the lobby automatically moves on to the next beatmap.

**Comment by Kiddo-Kris** [comment]
> How to prevent players that are AFK?
> Manual host rotations are quite an issue on stable already. When the host is rotated to an AFK player, you have no choice but to wait, or leave the lobby.
> I propose an addition to this idea, which is at the start of the multiplayer room, everybody selects one beatmap at the start of a round. When the first round ends, the lobby automatically moves on to the next beatmap.

Maybe set up a time limit can solve this problem

**Comment by UnderSampled** [comment]
There is a good design precedent from the the website plug.dj (no longer running). It was a way to listen to YouTube music videos together, and it worked like this:

- Rooms can be made by anyone, and have owners/moderators like IRC.
- When you join a room, you can listen to the currently playing song and chat
- If you have permission (by default, everyone does), you can join the end of the DJ queue.
- At any time, you can manage your playlists, adding songs or rearranging them, and selecting your active playlist
- When a song is finished, the DJ queue rotates, and the first song on the next DJ's selected playlist starts playing (no input required). Also, the song that just played is moved to the end of the playlist it was in, so the next time it's that DJ's turn, it will play the mid next song.
-  Moderators can control the title and description, and often set up bots/plugins to have blacklists/whitelists for what song can be played.

I really like this ability to prepare your playlists ahead of time, but still manage them or choose a specific song when you're waiting for your turn. And, you don't have to wait for the next DJ to choose (though, for Osu! it would not start immediately, I hope)

You could even enable automatic downloading, and it could fetch the beatmap for the next song before you even get to it! (If automatic downloading is ever desired.)

**Comment by abraker95** [comment]
@UnderSampled Sounds like a map queue. Other than allowing players to download maps ahead of time, what other benefits does this bring?

**Comment by UnderSampled** [comment]
It resolved the above stated issue of if a player is AFK: the host can choose to start at any time, while the players gave their input of what songs to play.

Over the other proposed option ("at the start of the multiplayer room, everybody selects one beatmap at the start of a round."), the setlist can be managed by the players on their own time, using existing playlists functionality.

This is more than just a "map queue" (assuming you define map queue to be one playlist), as it's a runtime combination of multiple players playlists.

The autodownloading is really just an extra bonus feature, and not important.

**Comment by peppy** [comment]
I did have an original goal of making the multiplayer system use the playlists UI internally, allowing this kind of queueing to be supported. Server-side, this is already how things work, to a point.

If we are to implement this as a queue system we can probably benefit from this, although the hard part is going to make the UX work well.

**Comment by baileywjohnson** [comment]
I'm currently working on a separate external utility for something like this (eventually functional at [mapqueue.io](https://mapqueue.io)).  I don't expect it to gain much attention- really just building it for the experience and for my friends to use.

The idea here is that players could issue a command to "Queuebot" (probably a fork of [Autohost](https://github.com/ekgame/osu-auto-host)) that links to a queue of beatmaps created via the MapQueue web application.  Queuebot will then hit the Mapqueue API to pull the list of beatmaps and auto-rotate through them in the multi lobby.

This doesn't really accomplish what @UnderSampled is proposing as it's really just a way to share map queues but I thought I'd bring it up since it's somewhat related.  I think it'd be neat to see some kind of queueing system officially integrated into multi in the future.

**Comment by Theighlin** [comment]
Is this issue resolved with the newly introduced queue modes? Missing features or suggestions can be pointed out in discussions

**Comment by smoogipoo** [comment]
Yep, resolved with the new queue modes.

**Comment by baileywjohnson** [comment]
> Yep, resolved with the new queue modes.

Sweet!
