### ISSUE TITLE
Switch tab shortcuts don't work in chat

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6976]
**Describe the new feature:** 
Add a key bind to switch chat tabs.
**Proposal designs of the feature:** 
Defaults:
```
Alt+left  to go left  a tab ( cycles if on end )
Alt+right to go right a tab ( cycles if on end )
```

---

Edit: Shortcut already exists, potentially `PlatformAction` contention.

**Comment by swoolcock** [comment]
Should already exist as a `PlatformAction`, please verify.
Ctrl+Tab/Ctrl+Shift+Tab on Windows, macOS, and Linux.
Also Cmd+Option+Left/Right on macOS.

**Comment by MightyHelper** [comment]
`Ctrl+Tab/Ctrl+Shift+Tab` Does the same as `Ctrl+Avpag/Ctr+Repag` : cycle the current mode `[osu!,osu!taiko,osu!catch,osu!mania]`

**Comment by swoolcock** [comment]
The point is, the shortcut exists.

**Comment by bdach** [comment]
Sounds like there might be some contention for the platform action, though - maybe we'd want the chat overlay to handle it first over the ruleset selector if it's open?

**Comment by swoolcock** [comment]
Reopening as bug.

**Comment by peppy** [comment]
Ruleset overlay should probably disable keyboard input for now.
