### ISSUE TITLE
"Show converted beatmaps" doesn't take effect when resuming song select

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#6980]
https://streamable.com/bh4fm

Seems to only take effect when changing the ruleset or _entering_ song select, but not when it's resumed from gameplay.

**Comment by bdach** [comment]
Regressed at 5b416eb (#6833) with the introduction of the following guard:

https://github.com/ppy/osu/blob/4d4e17f7c094316995d0092dbb3fb02a91537444/osu.Game/Screens/Select/SongSelect.cs#L263-L267

Straight up removing the guard seems to resolve the issue and pass tests, but I'm hesitant to PR that without context as to why it was added.
