### ISSUE TITLE
Storyboard sample playback

### ISSUE THREAD

**Issue by nathanielcwm** [ppy/osu#6981]
**Describe the bug:** 
The audio of the start of the song doesn't play the audio only starts after the 2nd break

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.1122

**Logs:** 
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3896689/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3896690/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3896691/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3896692/runtime.log)
[performance.log](https://github.com/ppy/osu/files/3896694/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3896696/performance-gamethread.audio.log)

**Comment by peppy** [comment]
This is due to some storyboard elements not being implemented yet.
