### ISSUE TITLE
I Run Osu!lazer in windows 7 with dotnet latest not launching

### ISSUE THREAD

**Issue by bruh-droid** [ppy/osu#6983]
I went to the internet cafe and I installed the latest version of dotnet and osu! lazer. After installing osu! lazer not launch Please help me

**Comment by huoyaoyuan** [comment]
Is your operation system 64bit?
Do you have latest Windows Update installed?
The installer is only for 64bit currently.

**Comment by bruh-droid** [comment]
Yes 64 bit

**Comment by bruh-droid** [comment]
I read  README.md there is a special name for Windows 7 and unfortunately the link is error 404  
(additional prerequisites)

**Comment by huoyaoyuan** [comment]
The link changed several days ago. Latest link should be https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore30&pivots=os-windows .

**Comment by bruh-droid** [comment]
how to download?

**Comment by huoyaoyuan** [comment]
The easiest and suggested way is using Windows Update, at least every several months.
The page provides following links:
<img width="214" alt="image" src="https://user-images.githubusercontent.com/5644458/69726457-981db000-115b-11ea-8fb9-0977722271fe.png">

**Comment by bruh-droid** [comment]
thank you I'll try it next week at the internet cafe. I want to take an exam
