### ISSUE TITLE
Option to adjust strength of parallax on menus

### ISSUE THREAD

**Issue by Luxiono** [ppy/osu#6987]
(This is my first try at adding an issue for osu! Please let me know if I can improve anything.)

**Describe the new feature:** 
A slider in Options that allows for the ability to adjust the strength of the parallax on menus if the setting was on from 0.1 to 10.0. This may be useful to those with problems like motion sickness but can handle it to a certain point or mostly just for those who hate the strong movement.
**Proposal designs of the feature:** 
Would look a little different because the stupid hold-to-activate thing is RIGHT in front of the 'Parallax' option:
![osu_2019-11-27_20-05-49](https://user-images.githubusercontent.com/55364481/69769865-b338f180-1154-11ea-99d9-36f4216dec3c.png)
I tried my best to make it look good.

**Comment by peppy** [comment]
Parallax is already dialled down during gameplay. Are you talking about the menu one specifically?

**Comment by Luxiono** [comment]
mostly, yes.

**Comment by Luxiono** [comment]
also, that was fast.

**Comment by EVAST9919** [comment]
Not really sure about this one. As mentioned before, parallax now has a way less motion. Also you can turn it off in settings.
I don't see a reason to configure it between 0 and the current value, since it will be probably unnoticeable.

**Comment by peppy** [comment]
If it is to be customisable, it may be a skin setting. Let's let it be for now though.
