### ISSUE TITLE
Social browser avatars keep async loading while the overlay isn't visible

### ISSUE THREAD

**Issue by Elepover** [ppy/osu#6989]
**Describe the bug:** 

- Open Social Browser via the top-right button
- Close by clicking anywhere outside the popup
- Enter beatmap editor
- Meet the empty screen

(update rate will jump to ridiculous high ~10,000fps)
(after a while, the editor will come back and prompt an error notification)

**Screenshots or videos showing encountered issue:** 

[osu!lazer 2019_11_28 12_49_52.zip](https://github.com/ppy/osu/files/3899884/osu.lazer.2019_11_28.12_49_52.zip)

**osu!lazer version:** 

`2019.1122.0`

**Logs:** 

[logs.zip](https://github.com/ppy/osu/files/3899905/logs.zip)

**Comment by peppy** [comment]
Can't reproduce here. Could you provide a video please?

**Comment by jai-x** [comment]
There's a video included in the zip file.

**Comment by smoogipoo** [comment]
This is an issue with all the avatars from social browser loading in the background and blocking the LCA threadpool.

Probably should cancel those loads when the overlay is hidden.
