### ISSUE TITLE
about the login

### ISSUE THREAD

**Issue by wolfpat01** [ppy/osu#6993]
its not an huge bug but..
![username](https://user-images.githubusercontent.com/57036855/69806923-5422bd80-11e4-11ea-92a0-f6761996180f.PNG)
we don't use email in login right

**Comment by huoyaoyuan** [comment]
already fixed by #6964 .

**Comment by GSculerlor** [comment]
Already done in #6964

**Comment by BastianInuk** [comment]
This screen doesn't allow option key modifier either, I thought I couldn't write my mail address

**Comment by wolfpat01** [comment]
oh , i haven't update my git yet , thx
