### ISSUE TITLE
Tournament client does not add beatmaps in **Rounds Editor**

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#6996]
**Screenshots or videos showing encountered issue:** 
![unknown](https://i.imgur.com/eqJqFb9.png)

**osu!lazer version:** 
2019.1122.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3902320/runtime.log)
[network.log](https://github.com/ppy/osu/files/3902321/network.log)

**Comment by peppy** [comment]
This has since been fixed via https://github.com/ppy/osu/pull/6924
