### ISSUE TITLE
Song Select Screen

### ISSUE THREAD

**Issue by arflyte** [ppy/osu#70]
![song-select----difficulty-select](https://cloud.githubusercontent.com/assets/3632750/19348719/4b12b110-918a-11e6-9308-96274854e30c.png)

This is the design for the Song Select screen.

I might miss something here as this was designed many moons ago; so new features and design updates might have been missed here.

There's a lot of components here, I'll do my best to explain each components in detail.
## Search & Filter

![](https://puu.sh/rHlCG/fe70d447b2.png)

Functions same as current osu!. Type something, and the carousel will show the results.

![](https://puu.sh/rHlGB/eea604514b.png) ![](https://puu.sh/rHlHK/2cffa41694.png)

Functions on the left side are the grouping filter. "All" and "Recently Played" should be displayed at all times. The third option should be the last used option.

On the right is the sorting options. Extra filter options revealed by clicking the ellipsis.
## Carousel

![](https://puu.sh/rHlNi/27cfc013d9.png)

The carousel should feel the same as current osu! build. However, by default, all beatmaps are grouped by song. Beatmap tiles fades away as it reaches the top or bottom.

![](https://puu.sh/rHmI9/03b5a4ff04.png)

Song title, song artist and available difficulties are displayed on beatmap tile with text shadow.

Beatmap's cover image is used as background, with 50%-0& black gradient overlay. Blue glow outline on hover.

![](https://puu.sh/rHuLR/cf00e8841a.png)
Above is the carousel area without the carousel. The entire background image is a blurred version of the background (Gaussian Blur 20px, or whatever equiv to it). 50% black overlay on the map and score details area.

![](https://puu.sh/rHmdv/90a1721975.png)

Once selected, available difficulties are revealed under the beatmap tile. difficulty title, followed by mapper details are displayed. Star difficulty are shown in the 2nd line. Same blue glow outline on hover.
### Beatmap Info

![](https://puu.sh/rHmOb/3d0f2a0b7f.png)
![](https://puu.sh/rHmPO/f0d7f29811.png)

Cover image (or beatmap background image) is shown with beatmap details on it. 50%-0% Black gradient overlay on the cover image. 

![](https://puu.sh/rHmP8/3f1c0980f1.png)

Beatmap song title and song artist, followed by mapper details. Song length, tempo, node count and slider count.
## Score Ranking

![](https://puu.sh/rHrkg/7bef131473.png)

Displays the ranking for selected map and difficulty. Ranking filters on top and additional filter on the left. Pressing the ellipsis will reveal additional filter just like the search mod.

Every score tile displays player's avatar, player's name, player's country and team flag, max combo chain, accuracy percentage, total score, score rank and mods used.

Score's font is Venera 500 and rest is Exo 2.

Last displayed tile is slightly faded to indicate there's more. Max 50. No scrollbars.

![](https://puu.sh/rHv2i/fcb0d06368.png)
I'll make a separate new issue for the above.

I'll update these if I missed something.

**Comment by uww** [comment]
wow dude cool

**Comment by UselessToucan** [comment]
It is just my opinion, but in comparison with the old one this new screen is difficult for understanding. On the other hand, in terms of beauty it is much more better.

**Comment by Antaresque** [comment]
As far as it looks pretty cool, I can't see AR/OD/etc listed anywhere and it's extremely important for playes to know those compared to circle/slider amount. Additionally, exact star rating would be also necessary somewhere. I think BPM and time could use some larger font? Maybe its just me being used to old design x)

**Comment by aerouk** [comment]
Adding on to what @Antaresque said about AR/OD missing, the icons (if you decide to go down that route) should probably have some hover text to make it easier to adapt from the current system ![](https://iaero.me/i/FF6Na)

**Comment by peppy** [comment]
This issue is for allowing people who are skilled to help implement the
screen, not provide feedback on the design.

While we do appreciate feedback, this is not the final implementation and
as such I'd ask you refrain from masking such discussion here!
2016年10月14日(金) 2:29 Tom B <notifications@github.com>:

**Comment by SirCmpwn** [comment]
@arflyte please add the difficulty background texture to osu-resources:

![](https://camo.githubusercontent.com/96e792850db51def4394367a71006d83537bd1a1/68747470733a2f2f7075752e73682f72486d64762f393061313732313937352e706e67)

**Comment by Sellyme** [comment]
@peppy so where are we meant to give feedback then? Because even if this isn't a final implementation, without feedback the actual final implementation is going to be just as bad.

**Comment by peppy** [comment]
You can give feedback once the game is made public. Until the. please watch and learn.

**Comment by Sellyme** [comment]
@peppy with all due respect, you should probably take in the opinions of people who _actually play the game_ well before release. It's obvious that the osu! team has some absolutely fantastic designers, but if you release something like this without significant user feedback from the actual playerbase beforehand it's going to get an extremely poor reception, and for good reason.

Making things skinnable and/or open-source is not an excuse for degrading usability and just expecting everyone else to fix it.

**Comment by peppy** [comment]
Thank you for your concerns in my inability to make a game, but as I already said, this is not a final implementation and is a work in progress. Please stand down and watch and learn. 

Thank you.

**Comment by Dmoayad** [comment]
This is amazing. How can I use it or test it?

**Comment by avail** [comment]
This is just a mockup. It's being worked on, though. You can view the progress at https://github.com/ppy/osu/pull/61

**Comment by xakku** [comment]
im curious to how this will affect skins for layout in song select and so on.

**Comment by 2yangk23** [comment]
Is anyone working on these dropdowns? If not, I'd like to take a shot at it.  I know there are dropdown menus already but I couldn't find them in this style.

![68747470733a2f2f7075752e73682f72486c47422f656561363034353134622e706e67](https://cloud.githubusercontent.com/assets/7710340/23299690/6060a502-fa37-11e6-9c2e-f4917090ca61.png)
![68747470733a2f2f7075752e73682f72486c484b2f326366666134313639342e706e67](https://cloud.githubusercontent.com/assets/7710340/23299701/69e1ba44-fa37-11e6-9114-d3dcf0343f33.png)

**Comment by peppy** [comment]
it's part of a TabControl implementation, so keep that in mind (any tabs which can't fit should be shown in the list).

**Comment by 2yangk23** [comment]
From the requirements, it states that
> "All" and "Recently Played" should be displayed at all times.

I noticed that "Recently Played" is in the dropdown list, while "All" is not.  For consistency purposes, should they be in the list or not?

**Comment by peppy** [comment]
The dropdown should only show any tabs which can't be fit in the tabs area.

**Comment by peppy** [comment]
This has been completed. There are more design improvements in the pipeline, but they are out of scope of the issue.
