### ISSUE TITLE
The starts of sliders move with the slider ball

### ISSUE THREAD

**Issue by Azureharp** [ppy/osu#7005]
**Describe the bug:** 
The the beginnings of sliders move along with the slider ball starting right in the middle of the timing window when the slider ball starts, so it's only evident when the slider get's clicked slightly late or not at all.
**Screenshots or videos showing encountered issue:** 
![slippy slide](https://user-images.githubusercontent.com/42692316/69832899-4ece6e80-11f6-11ea-8f2f-90f692a944fa.gif)
![osu_2019-11-28_15-09-07](https://user-images.githubusercontent.com/42692316/69832976-c8665c80-11f6-11ea-81db-8cd455117fe2.png)
**osu!lazer version:** 
2019.1128.0

**Comment by MightyHelper** [comment]
Not sure if it's intended but I like it.

**Comment by smoogipoo** [comment]
This is intentional.
