### ISSUE TITLE
Ability to change stack direction

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7006]
**Describe the new feature:** 
When two circles are close in time and in the same place, osu!stable stacks them.
I suggest that you can change the _angle_ at which the circles are displaced.
**To be decided:** 
- Changing this setting affects previous occurrences in the map?
- Also, change stack distance?

**Comment by genericthing** [comment]
i suggest adding them to the inherited points and uninherited points so that changing the angle in that will only affect that section

(stack distance also sounds good)
