### ISSUE TITLE
Editor "plugins"

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7007]
### **Where the idea came from**
Currently, on osu!stable in the `Compose` section, there are buttons like
- Create Polygon Circles
- Convert slider to stream
That ( I think ) are not known by everyone and I find fantastically useful.
### **Describe the new feature:**
Add some way to make new plugins that do similar things ( Rotate around an origin, shear, transform, etc a selection of objects )(#3247,#2213).
**_This is, of course, a long term thing, and quite a way off_**, since the editor has to be completed first and requires a lot of other things to be implemented alongside it, but I thought that it could be a good idea to suggest this now as it _might affect desitions_ while making the editor.
That way people (with a bit of an idea about programming ) can write simple-ish code that ties in with the osu!editor.
### **Things to be implemented:** 
- Interface plugin-osu
- Some way to stop *viruses* that could crash osu!
- Some way for the user to manually bypass this (if they are making something for fun)
- Interface plugin-user generation.
- Some format for an osu!editor plugin
- Some language ( maybe new or not ).
- Documentation for anyone interested in using this.
### **Really long term things**
- Multithreading?
- Some page to post your plugin and get new ones
- Validation for plugins (by user votes?) for this page
- Also allow the plugin to edit the storyboard, the timing section
- Interact with #6143
- Allow plugins to do something like #3947

Not really sure to what extent this should go, but it seems like a generalised way to add stuff to the editor.
Hope you like the idea.

**Comment by smoogipoo** [comment]
At the moment we are not planning to allow arbitrary code execution by way of plugins. We _may_ consider this at a later point, but the current goal of the editor is to be complete enough to not require plugins to do things in the first place.

That is also to say that we are not coding the editor with plugins in mind. Let's complete it first and get the necessary structures in place (there's a _lot_ to do), then we can consider re-opening this and re-considering the path taken.
