### ISSUE TITLE
Comments support

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#7013]
This issue tracks the remaining tasks to be completed to have the comments container in a usable state.

# General
* [x] Fix async loading isn't really async
* [x] Allow refetch comments using a method (rather than passing parameters in the ctor)
* [x] Ability to work for logged-out users
* [x] Placeholder for no-comments case
* [x] `TotalCommentCounter` integration
* [x] Colour schemes (shared with overlays)
* [x] Remove `CommentsPage` component
* [ ] Custom tooltip
* [x] Don't use margin for deep-level comments (https://github.com/ppy/osu/issues/8012)
* [x] Handle pinned comments (https://github.com/ppy/osu/pull/14272)

# Overlays integration
* [x] Changelog
* [x] BeatmapSet
* [ ] News

# User interaction
* [x] Loading long sub-comments trees (more known as "Load replies" and "Show more" buttons)
* [x] Ability to leave a comment
* [x] Ability to leave a reply
* [x] Ability to delete own comments
* [x] Report comments (if necessary)

# Testing
* [x] Ability to set local `CommentBundle`

**Comment by enoslayd** [comment]
Is this the comments type of "scrolling on top while replaying a map"?

**Comment by GSculerlor** [comment]
> Is this the comments type of "scrolling on top while replaying a map"?

That kind of comment should be part of #4796

**Comment by enoslayd** [comment]
Comments like in the beatmap section?

**Comment by Feodor0090** [comment]
What's the URL to request for reporting a comment? I did not find it in v2 api docs.

**Comment by Joehuu** [comment]
Going to close this as completed as it is usable.

The "custom tooltip" can be clarified in another issue, and news posts are yet to be implemented (https://github.com/ppy/osu/issues/5479).
