### ISSUE TITLE
Mobile osu is freezing and making it unplayable

### ISSUE THREAD

**Issue by willywizard** [ppy/osu#7015]
I have been playing the laser beta on iPhone for a while, but the game hasn’t been working for the last few updates. I have been playing mobile non stop usually because it’s fun, and recently due to hardware issues I have suddenly been unable to play normal osu (because of hardware and input delay issues

I have beaten these songs on mobile before some with great scores and some with almost dying scores.
The maps that tend to freeze up for reference:

Inferno - Mrs green apple (TV Size)
(5* Fire Force)
Mapped by Amandia 

Holdin On (Skrillex and Nero remix)
(6.5* Immortal)
Mapped by Sotarks

Naruto-(Japanese letters)-Silhouette
(5.5* Kage)
Mapped by Kagetsu

When I launch the app it runs fine until I try to play a song. When I try to play a song, at around the 5-20 second mark of these songs they normally seem to freeze. There are a few very rare exceptions where it will actually let you play through the song. This issue doesn’t seem to be effecting 2 star/lower star maps. But for me this glitch makes the game un-playable. I thought a bunch of other people would be having this bug and I would have assumed that after about 3 weeks (and 2 updates) you guys would have been able to fix it. But because it’s still not I thought I would make this post about it.

Video:
https://youtu.be/afjEJhi8iEI

Sorry if the formatting is wrong or I did this wrong, I haven’t really used github before other than once a few years ago. If I am missing anything I was suppose to require please let me know. I just want to be able to have fun playing osu on my phone!

**Comment by EVAST9919** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/22874522/69887367-a3a5de00-12f7-11ea-85bd-01d14dce18bd.png)

**Comment by bdach** [comment]
Also, #6355.
