### ISSUE TITLE
crash during launch on linux

### ISSUE THREAD

**Issue by fishfishfish2104** [ppy/osu#7018]
**Describe the crash:** 
dotnet run --project osu.Desktop will exit after loading fonts
**Screenshots or videos showing encountered issue:** 
![crash](https://user-images.githubusercontent.com/16485618/69893522-4fdad980-1377-11ea-9439-d99b3ce33eaa.gif)
**osu!lazer version:** 
2019.1128.0
and master currently
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3906612/runtime.log)

**Computer Specifications:** 
OS: Arch linux
CPU: Ryzen 5
GPU: Radeon RX 590

**Comment by swoolcock** [comment]
Has it worked in the past?  If so, it would help if you could `git bisect` to find the commit at which it stopped working.

Could you attach the other log files too?

**Comment by recapitalverb** [comment]
Reproducible for every commit from a4f584c6a4771c0f8c40bafaa544d4e83e8a571e onwards.

For you, executing `export DOTNET_ROOT=/opt/dotnet` might fix the problem as per [this part on the Arch Wiki](https://wiki.archlinux.org/index.php/.NET_Core#%22the_required_library_libhostfxr.so_could_not_be_found%22_error). For me, doing so doesn't fix anything, and running the binary directly shows this:
```
reverb ~/Repos/osu/osu.Desktop/bin/Release/netcoreapp3.0 ➜ ./osu\!                   
[1]    33848 segmentation fault (core dumped)  ./osu!
```
This is the only logfile that appears: [runtime.log](https://github.com/ppy/osu/files/3906754/runtime.log)
Here is my output acquired from `export LD_DEBUG=all` and trying to run it again: [log.txt](https://github.com/ppy/osu/files/3906755/log.txt

**Comment by fishfishfish2104** [comment]
i did a git bisect between commits b02ff01 4063135 where 4063135 is known to work and b02ff01 is known not to. when I was doing this bisect commit d1e371803 gave a different error then usual saying BufferedContainer' does not contain a definition for 'FrameBufferScale' so I git bisect skip and got `There are only 'skip'ped commits left to test.
The first bad commit could be any of:
d1e3718038f806afff93aaebd9bf8a1481312f34
a4f584c6a4771c0f8c40bafaa544d4e83e8a571e
We cannot bisect more!
`

**Comment by recapitalverb** [comment]
I think we can then confirm that the commit a4f584c6a4771c0f8c40bafaa544d4e83e8a571e is the one causing the problem here based on your `git bisect skip` output and my testing.

**Comment by fishfishfish2104** [comment]
when setting LD_DEBUG=libs running dotnet osu\!.dll in master gives libbass_fx.so: error: symbol lookup error: undefined symbol: BASS_GetVersion (fatal)

**Comment by swoolcock** [comment]
I can just about guarantee you it will be this change:
https://github.com/ppy/osu-framework/commit/6b8ff8a1809286ada21b541defafe74049c478c0#diff-913b7fdafad54d1a356c8ce8f30728bc

**Comment by fishfishfish2104** [comment]
works when commit 6b8ff8a is reverted

**Comment by swoolcock** [comment]
> works when commit 6b8ff8a is reverted

Feel free to make a pull request then. :)

**Comment by fishfishfish2104** [comment]
alright created pull request https://github.com/ppy/osu-framework/pull/3057
