### ISSUE TITLE
When Fix Performance In mobile?

### ISSUE THREAD

**Issue by bruh-droid** [ppy/osu#7019]
When to fix fps drop in Low smartphone ?!

**Comment by GSculerlor** [comment]
I'm pretty sure we don't accept any mobile issue unless you willing to fix it yourself right now. Also your issue is not a "good quality" issue tho

**Comment by bdach** [comment]
We are aware of performance problems on lower-end devices. It is a constant consideration on all platforms, which you would know if you searched for similar previously closed issues. Please be patient and understand mobile is *not* a priority right now.
