### ISSUE TITLE
Inner Error?

### ISSUE THREAD

**Issue by bruh-droid** [ppy/osu#7020]
![Screenshot_20191130-211142](https://user-images.githubusercontent.com/58106217/69901591-65bbbf00-13b6-11ea-9ff8-baf6791c5c57.png)

**Logs**
[performance.log](https://github.com/ppy/osu/files/3907168/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3907169/runtime.log)
[database.log](https://github.com/ppy/osu/files/3907170/database.log)
[network.log](https://github.com/ppy/osu/files/3907171/network.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3907172/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3907173/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3907174/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3907175/performance-gamethread.update.log)

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/69901636-c56e9600-13c7-11ea-9f17-cb94e7150495.png)
