### ISSUE TITLE
Carets in text input should blink to currently playing music

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#7027]
**Describe the new feature:** I think the title is self-explanatory - the cursor (seen in the image below) should blink to the beat of the currently playing song.
![image](https://user-images.githubusercontent.com/41869184/69909612-0c907180-1430-11ea-8840-55d7765cf64f.png)

**Comment by GSculerlor** [comment]
Afaik caret loop duration is hardcoded on framework side (See https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/TextBox.cs#L380)

**Comment by bdach** [comment]
Doing this might not look great with high BPM tracks. Would need to try and see.

**Comment by HoLLy-HaCKeR** [comment]
> Doing this might not look great with high BPM tracks. Would need to try and see.

Could be scaled down similar to how CtB bananas are handled: keep dividing by 2 until you get to a reasonable number

**Comment by MightyHelper** [comment]
I'm not sure how this would look so I'll suggest it:
If the current playing song is in a Kiai section, then make the text `jump` in time with the music. ( could be in time with the caret.)
By `jump` I mean, increase the thickness ( kinda like bold but **not half as much** )
I suggest making it togglable if it gets too annoying on any specific map/song.

**Comment by bdach** [comment]
Personally I'm quite opposed to messing with the text thickness, I'm 99% sure it'll be too distracting.

**Comment by KaiHicks** [comment]
> 
> 
> > Doing this might not look great with high BPM tracks. Would need to try and see.
> 
> Could be scaled down similar to how CtB bananas are handled: keep dividing by 2 until you get to a reasonable number

What about maps with a high prime BPM? In those cases, it would probably be best to just revert to the standard blink-rate.

**Comment by InvisibleSymbol** [comment]
I think you all are overthinking this, as there already is an implementation of this behaviour in lazer, see https://github.com/ppy/osu/blob/master/osu.Game.Tests/Visual/UserInterface/TestSceneBeatSyncedContainer.cs. Pretty sure this can also be applied here.
