### ISSUE TITLE
Audio track playback stacking when spamming music player prev/next controls

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#7028]
**Describe the bug:** 
-
Volume overlay when your click is super fast in menu music player, I've made a video to show you

**Screenshots or videos showing encountered issue:** 
-
[Video](https://github.com/ppy/osu/files/3907878/ITS.SO.LOUD.zip)
 _**Volume Warnning!**_

**osu!lazer version:** 
-
2019.1128.0

**Logs:** 
-

[logs](https://github.com/ppy/osu/files/3907879/logs.zip)

**Comment by LanTenDragon** [comment]
The video you sent does get quite loud!

Its best to have a loudness warning for those who want to view the video.

**Comment by Kiddo-Kris** [comment]
> The video you sent does get quite loud!
> Its best to have a loudness warning for those who want to view the video.

oh Im sorry, loudness warning added

**Comment by bdach** [comment]
Can't reproduce by spamming mouse1 on the prev/next controls. Not sure if that's my APM not being good enough or if there's a trick to it. Probably would make sense to debounce the button presses anyways, though.

Also on a partially related note, weirdly enough using <kbd>F1</kbd>/<kbd>F5</kbd> doesn't seem to cause that noticeable stutter on switch the same way the player buttons do, so there's potentially some performance investigating to be done there.

**Comment by LastExceed** [comment]
> Not sure if that's my APM not being good enough

judging by the ui sounds, op is probably using a click bot with 100+ clicks per second. But even with a click bot I can't reproduce. I also can't reproduce the difference between clicking the button and pressing `F1`/`F5`

**Comment by Kiddo-Kris** [comment]
> Can't reproduce by spamming mouse1 on the prev/next controls. Not sure if that's my APM not being good enough or if there's a trick to it. Probably would make sense to debounce the button presses anyways, though.
> Also on a partially related note, weirdly enough using F1/F5 doesn't seem to cause that noticeable stutter on switch the same way the player buttons do, so there's potentially some performance investigating to be done there.

I'm using a Mouse macro, I did this just for fun and discovered this glitch

**Comment by Kiddo-Kris** [comment]
> judging by the ui sounds, op is probably using a click bot with 100+ clicks per second. But even with a click bot I can't reproduce. I also can't reproduce the difference between clicking the button and pressing F1/F5

I'm using a mouse macro, should probably faster than 100 click per second

**Comment by Kiddo-Kris** [comment]
probably this problem can be soved by setting up a limit of max click action. There should 
not so much thing can click fast like a mouse macro

**Comment by smoogipoo** [comment]
don't use the mouse macro
