### ISSUE TITLE
Crash Intro "welcome to osu!"

### ISSUE THREAD

**Issue by bruh-droid** [ppy/osu#7030]
![Screenshot_20191201-161954](https://user-images.githubusercontent.com/58106217/69912022-8a677380-1456-11ea-8206-e3a24dec73d8.png)

Logs:
[runtime.log](https://github.com/ppy/osu/files/3908019/runtime.log)

**Comment by LanTenDragon** [comment]
Potentially a duplicate. 

Based on your runtime log, you are having the same exception as https://github.com/ppy/osu/issues/6507

That said, I'm unsure why your app execution just stops...

**Comment by swoolcock** [comment]
Looks the same to me.  Also please stop making mobile issues.
