### ISSUE TITLE
osu!Lazer on android won't track mouse and isn't able to map gamepad buttons

### ISSUE THREAD

**Issue by michel333alfa** [ppy/osu#7032]
**Describe the bug:** 
osu!Lazer on android(galaxy S10+ android 10(one ui 2 latest stable) can't track mouse movements and isn't able to map gamepad buttons(only the d-pad is mappable). Please, fix it. Opsu is able to do both the mouse tracking, and is able to map HID gamepad buttons(tested with DualShock4, Gamesir G4S, moga pro power)

**Screenshots or videos showing encountered issue:** 
https://youtu.be/k8zYiJWBzHo

**osu!lazer version:** 
2019.1128.0
**Logs:** 
I believe no logs needed.

**Comment by bdach** [comment]
See ppy/osu-framework#2863, but more importantly, please do not open mobile-related issues as we're not currently accepting them, which you should know if you read the quite visible warning placed in the issue submission process.

**Comment by DotsTeaLab** [comment]
delete this please
