### ISSUE TITLE
Change slider speed while the slider is in motion

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7035]
**Describe the new feature:** 
Add a way to change the slider speed while the slider is in motion.
Eg: Slider speed X px/s
Slider is 10X px long
Slider starts moving ( would take 10s )
but at 50% (5X px) the slider speed changes to 2 X px/s
the slider now finishes in 2.5s, a total of 7.5s
**Proposal designs of the feature:** 
Maybe add an option to timing section to update existing sliders in movement.

**Comment by genericthing** [comment]
i think this should be done with a new file format so the older maps don't break, also have this apply to red lines too

**Comment by peppy** [comment]
Closing in favour of https://github.com/ppy/osu/issues/4305.
