### ISSUE TITLE
Quitting while not focusing on osu! window causes process to stall

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#7042]
**Describe the crash:** When asked to exit, osu! closes its window but the process stalls when the window is not focused.

Steps to reproduce:
1. Exit game
2. Focus on a different window while osu! is still fading out
The game window closes, but the process still continues to run.

**Screenshots or videos showing encountered issue:**
Screenshot of game window not available.
(task manager)
![image](https://user-images.githubusercontent.com/41869184/69961683-f3c2b180-153e-11ea-9bb0-4f78e83fed72.png)
(console)
![image](https://user-images.githubusercontent.com/41869184/69961749-19e85180-153f-11ea-9dbd-67fe3e96e962.png)

**osu!lazer version:** master branch commit 149c284ef327d482f0087a2fde5ddeb5c84885ef

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3911383/database.log)
[network.log](https://github.com/ppy/osu/files/3911384/network.log)
[performance.log](https://github.com/ppy/osu/files/3911385/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3911386/runtime.log)

**Computer Specifications:** 
OS: Arch Linux x64
Kernel: 4.19.86-1-lts
Resolution: 1920x1080
DE: Plasma
WM: KWin
CPU: Intel i5-9400F (6) @ 4.100GHz
GPU: NVIDIA GeForce GTX 1650

**Comment by peppy** [comment]
Have you tested under a different window manager?

**Comment by recapitalverb** [comment]
Not yet, will try asap

**Comment by recapitalverb** [comment]
Only reproduces if `SDL_VIDEODRIVER=wayland` is set. Closing this because https://github.com/ppy/osu/issues/5198 exists.
