### ISSUE TITLE
Allow imports via Files.app iOS

### ISSUE THREAD

**Issue by BastianInuk** [ppy/osu#7049]
**ATTENTION**: Plan to implement myself.
Related: #6525, #5265
I noticed there was a lack of a way to import Osu! skins and beatmaps, I propose that the Osu! files structure on iOS be exposed to the files app so that people can move in skins manually either from download or otherwise. Alternatively, a mobile module for exposing the relevant dirs could be made.

**Comment by peppy** [comment]
The related issues you link are android.

On iOS, you can load skins and beatmaps via the "Share" menu. Exposing osu! in files (if we decide this is what we want) at very least requires us first moving the game files out of the documents location, as they are currently incorrectly placed.

**Comment by BastianInuk** [comment]
Thanks ppy! I'll close this issue from here then

**Comment by BastianInuk** [comment]
Oh wait, nvm

**Comment by ThatsNiceGuy** [comment]
Maybe this is an incorrect bump but this never worked for me on any devices or even my friend’s device

> On iOS, you can load skins and beatmaps via the "Share" menu.

**Comment by nathanielcwm** [comment]
yeah for me the other day i downloaded and tried opening one through the files app but it didn't appear as an option in the share menu however it got recognised as a beatmap by ios but i couldn't install the beatmap

**Comment by ThatsNiceGuy** [comment]
epic

**Comment by dscnnctd** [comment]
indeed
