### ISSUE TITLE
Editor - Change volume/SV

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7052]
**Describe the new feature:** 
An option to change the volume of hit objects/SV in the editor, but inside the context menu/top bar.
**Proposal designs of the feature:** 
When clicked :
Open dialog with 
- Volume slider / SV slider or input
- Volume lerp checkbox (refer to #7501 ) / --
- Ok/Cancel button

When these are clicked, they will automatically create a new time frame with the selected parameters.

**Comment by smoogipoo** [comment]
Gonna make an executive decision here to close this issue on the premise that the editor is a loooooooooong way off being complete and this is already planned. We also have designs in place for this which fit it into the bottom timeline.
