### ISSUE TITLE
Seasonal backgrounds

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#7055]
**Describe the new feature:** It would be exactly like Stable in the sense that with every season, you can enable seasonal backgrounds instead of the default background when you open Lazer. Different from Stable, however, each picture would be present for, lets say 10 seconds, then it changes to a new picture. So it basically constantly refreshes the pictures instead of staying on just one picture.

**Proposal designs of the feature:** Button under skinning? Maintenance? Since I have a Chromebook, I can't go back to the Stable client to remember where that button was on that client to know where to put it in Lazer.

**Comment by MightyHelper** [comment]
Maybe change when the song changes?
Sometimes they have a lot of detail and I like to look at them for a while.

**Comment by peppy** [comment]
This can be added in the menu background dropdown. It should be implemented to pull from an online API source, and load the backgrounds as required. It would change once on song change or resuming as per the existing implementation.

**Comment by mcendu** [comment]
Are there any machine readable index (i.e. not the news posts) of art contests and winners, so that I can access them from assets.ppy.sh/contests/[name your id]/winners/[name your background]?

**Comment by peppy** [comment]
An API endpoint would need to be made for this. I believe we already have stuff databased so it should not be a huge effort required.

**Comment by Wieku** [comment]
I thought there is an endpoint already because osu!stable downloads them when needed. Or was it added during this season?

**Comment by mcendu** [comment]
Should we move it to candidate (or just un-backlog this)?

**Comment by iiSaLMaN** [comment]
> Should we move it to candidate (or just un-backlog this)?

From what i've seen, `Backlog` milestone goes for issues / features that don't need to be resolved at the moment and may require huge effort to resolve, you can check the `Candidate Issues` and other milestones and compare with them to understand which is more important.

**Comment by smoogipoo** [comment]
A v2 endpoint for this has been PR'd. You can code against the specification provided there: https://github.com/ppy/osu-web/pull/5506, route: `seasonal-backgrounds`

**Comment by hbnrmx** [comment]
Would like to give this a shot, while the Halloween event is still running.

Currently https://osu.ppy.sh/api/v2/seasonal-backgrounds is returning `{}`
so I'm assuming `SEASONAL_CONTEST_ID` env var is not set.

if it's not too much work, could you set it for testing purposes? 
Thank you.

**Comment by peppy** [comment]
is set now
