### ISSUE TITLE
Colour of X difficulty is hard to read in tooltip

### ISSUE THREAD

**Issue by huoyaoyuan** [ppy/osu#7058]
Comparing:
<img width="172" alt="image" src="https://user-images.githubusercontent.com/5644458/70146009-44234600-16dc-11ea-9a27-f1887a3e1caa.png">
<img width="128" alt="image" src="https://user-images.githubusercontent.com/5644458/70146029-50a79e80-16dc-11ea-99d6-e67b016e9334.png">

Needs to change the colour of either background or the text.

**Comment by GSculerlor** [comment]
Alongside with diff star colour for `ExpertPlus`, should we  change the tooltip background to match with web as well? It's a bit off currently

Lazer tooltip:
![Annotation 2019-12-04 224037](https://user-images.githubusercontent.com/6506864/70157096-84d48c80-16e7-11ea-9ff4-27da28f79dfe.png)
Web tooltip (profile):
![Annotation 2019-12-04 224114](https://user-images.githubusercontent.com/6506864/70157097-856d2300-16e7-11ea-8758-d72e97d7c0f3.png)
Web tooltip (beatmap page):
![Annotation 2019-12-04 224634](https://user-images.githubusercontent.com/6506864/70157337-fd3b4d80-16e7-11ea-8e91-ebc8926e8f6d.png)
