### ISSUE TITLE
osu!catch with relax mod active doesn't accept mouse input for most of the screen when vertical

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7069]
**Describe the bug:** If the game window is vertical, the playfield doesn't accept mouse input with Relax on outside of a small area in the middle (approximately marked with a green rectangle).

**Screenshots or videos showing encountered issue:** 
[Screenshot_20191205-105449](https://user-images.githubusercontent.com/15932372/70228812-55f4ff80-1755-11ea-9fb3-cc064db9f713.png)

**osu!lazer version:** 2019.1205.0

**Comment by bdach** [comment]
This is due to the mod only capturing mouse input inside of the playfield area instead of the whole window height.
