### ISSUE TITLE
not enter the record on osu lazer android

### ISSUE THREAD

**Issue by bruh-droid** [ppy/osu#7071]
**Describe the bug:** 
Where is my record even though I've played it got "A" but it didn't make my record
**Screenshots or videos showing encountered issue:** 
![Screenshot_20191205-210456](https://user-images.githubusercontent.com/58106217/70242779-04c02c80-17a4-11ea-9b7d-1ac5acc0cb92.png)
![Screenshot_20191205-211405](https://user-images.githubusercontent.com/58106217/70242873-333e0780-17a4-11ea-8a27-5c6ae6f481b5.png)
Lp Easy that I play on the computer osu!stable
**osu!lazer version:** 
Latest
**Logs:** 
None

**Comment by huoyaoyuan** [comment]
Score uploading hasn't been enabled for Lazer yet. It will be enabled only when the project becomes "ready to publish".

**Comment by X4X5** [comment]
Like it didn't upload to the website?
