### ISSUE TITLE
Pop-out button on music player

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#7073]
**Describe the new feature:** 
A button on the music player to allow you to drag it anywhere over the osu! game window, and use the other UI elements at the same time. So you could overlay it over osu! direct, or the song select screen, anything really.

**Proposal designs of the feature:** 
![image](https://user-images.githubusercontent.com/33783503/70260245-c4eb4c00-1787-11ea-8160-d76f1b97ab52.png)

**Comment by peppy** [comment]
This is not currently planned.
