### ISSUE TITLE
Custom score submission conditions

### ISSUE THREAD

**Issue by wisnoi** [ppy/osu#7086]
**This proposal would allow players to choose the conditions under which a score submits a request to the score submission server.**
  
I believe that with the invention of an invisible userstate in the Lazer client, the process of abstracting osu! from an online-only game has already begun, giving this proposal helpful prior precedent.

There are a number of niche and popular reasons for an implementation of this system, such as SS-only players, players who desire to maintain a certain account accuracy, or even just the lack of an existing PP > score structure.  
  
This would also remove the requirement to circumvent score submission through offline play or other methods. (previous popular methods being the now-removed Cutting Edge debug tools, external local programs, and physically disabling internet access before submission could occur)  
  
Optimally this setting would be under in-game online settings or in the game mods panel.

**Comment by smoogipoo** [comment]
This isn’t gonna happen. osu! is an online game, you log on to to receive the benefits of score submission, chat, seeing leaderboards/players, spectating, etc. If you don’t want to submit scores, feel free to play offline.

The cutting edge tools were not supposed to be for public use, the functionality was intended for debug purposes only.
