### ISSUE TITLE
Mania score processing + judgements

### ISSUE THREAD

**Issue by smoogipooo** [ppy/osu#709]
osu!stable currently has a rough ScoreV2 implementation we need. Perhaps we can do general adjustments here and there.

**Comment by smoogipooo** [comment]
We're working with the following naming scheme for judgements:

| old | new |
|----|-----|
| 300g | PERFECT |
|300|GREAT|
|200|GOOD|
|100|OK|
|50|BAD|
|MISS|MISS|

**Comment by Tom94** [comment]
Turns out "completes" doesn't actually close the accompanying issue.
