### ISSUE TITLE
Slider balls in legacy skin goes still after a rewind in replay

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7096]
**Describe the bug:** After a rewind in replay, the animation of a slider ball in legacy skins temporarily stop.

Similar things happen to cursor.

**osu!lazer version:** Commit `4d4e17f`. Beatmap ID 703957 [Akitoshi's Normal] with Autoplay enabled is used to reproduce this bug.

**Comment by mcendu** [comment]
A replay label might be appropriate.

**Comment by bdach** [comment]
I can't reproduce this any longer, most likely due to pooling/skinning changes since the time this was reported. Closing as stale/resolved.
