### ISSUE TITLE
Import failure

### ISSUE THREAD

**Issue by Shadow10183** [ppy/osu#7097]
**Describe the bug:** 
Even though its supposed to be fixed, the newest release shows that it cannot find a stable install
**Screenshots or videos showing encountered issue:** 
![Screenshot 2019-12-08 at 21 44 21](https://user-images.githubusercontent.com/58657585/70390214-fbcd9600-1a03-11ea-89ce-a8560c2eb179.png)*osu!lazer version:** 
**Version:**
2019.1205.0
**Logs:** 

[performance.log](https://github.com/ppy/osu/files/3936270/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3936271/runtime.log)
[database.log](https://github.com/ppy/osu/files/3936272/database.log)

**Comment by bdach** [comment]
What is your stable installation path? Also, did you try the *Repair folder permissions* option in the stable client settings?

**Comment by Shadow10183** [comment]
i dont fully understand what u mean by installation path but ill try what u suggested

**Comment by Shadow10183** [comment]
still could not find the stable install

**Comment by bdach** [comment]
> i dont fully understand what u mean by installation path but ill try what u suggested

When you click *Open osu! folder* in stable settings, what's the path you get redirected to?

Also, do osu!-associated files (`.osk`s, `.osz`s) have osu!-styled icons and automatically open in stable?

**Comment by Shadow10183** [comment]
/Applications/osu!.app/Contents/Resources/drive_c/osu!/
yes, they do
is it too late to add that im on MacOS?

**Comment by peppy** [comment]
To make things work you will need to run this from terminal:

`ln -s /Applications/osu!.app/Contents/Resources/drive_c/osu!/ ~/.osu`

Please close the issue if it works.

**Comment by Shadow10183** [comment]
it does not appear to work

**Comment by peppy** [comment]
Please note you will need to restart lazer for it to work.

**Comment by Shadow10183** [comment]
what i mean is that there is no positive response from the terminal itself
