### ISSUE TITLE
Adding visual settings to the main menu background

### ISSUE THREAD

**Issue by ojh050118** [ppy/osu#7098]
**Describe the new feature:** 
In Settings adjust the background dim or blur of the main menu.

**Proposal designs of the feature:**

**Comment by Joehuu** [comment]
I think this will not happen. See peppy's comment after https://github.com/ppy/osu/issues/5516#issuecomment-516210935.

**Comment by ojh050118** [comment]
Ah okay. I personally want to make that option, how do I apply the blur effect to the main menu?

**Comment by ojh050118** [comment]
I'm sorry but can you help me..?

**Comment by smoogipoo** [comment]
`Background` supports `BlurTo`. You'll need to find a way to call that function, probably by making a config setting and binding to it from `BackgroundScreen`.
