### ISSUE TITLE
Slider ball no longer tints

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7104]
**Describe the bug:** Same as #6176. I do not know when tinting was un-implemented nor know about any options for that.

**Screenshots or videos showing encountered issue:** 
![Screenshot from 2019-12-09 09-32-32](https://user-images.githubusercontent.com/43639171/70400637-da51c600-1a66-11ea-93cd-78cac86b7fb3.png)

**osu!lazer version:** Commit `4d4e17f`; Screenshot taken with PR 7095 on

**Logs:** Not required

**Comment by mcendu** [comment]
Possibly close as dupe when we decide to reopen that.

**Comment by smoogipoo** [comment]
Closing as duplicate.
