### ISSUE TITLE
Undownloadable replays can be accessed via country/friends leaderboard

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#7106]
Trying to download them will cause an error
![osu_2019-12-09_06-19-40](https://user-images.githubusercontent.com/22874522/70404696-eed49500-1a4b-11ea-8982-33f6f51ff34a.png)

**Comment by smoogipoo** [comment]
This isn't a regression - the API needs to somehow return whether the replay download is available.

**Comment by peppy** [comment]
https://github.com/ppy/osu/blob/master/osu.Game/Online/API/Requests/Responses/APILegacyScoreInfo.cs#L92

**Comment by smoogipoo** [comment]
`ScoreInfo` should itself also have a similar parameter imo. Currently it's based on the `Hash` so a temporary fix could be to not give an "online" hash if false.
