### ISSUE TITLE
Editor guide markers

### ISSUE THREAD

**Issue by leduyquang753** [ppy/osu#7120]
**Describe the new feature:** This feature allows the beatmap editor to place markers on the timeline to help them specify the notes' locations.

**Proposal designs of the feature:** There can be an UI where the editor can listen to the song and click/tap in time with the song's notes/beats. When done, the markers can be displayed as small lines on the timeline. Those lines serve purely as visual guides and do not affect snapping of the actual notes (because this is a human tapping).

**Comment by peppy** [comment]
You can do this with bookmarks (or live mapping) if you so wish. Doesn't need to be its own feature.
