### ISSUE TITLE
Custom Beatmap parameters

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#7124]
**Describe the new feature:** 
-

> Add sliders on the mods interface to modify CS, AR, OD, HP, BPM
> This feature allows players to practice on a specified Beatmap

**Proposal designs of the feature:** 
-
![image](https://user-images.githubusercontent.com/56265123/70439815-cab89880-1acb-11ea-9cab-39804a9abdcf.png)

**Comment by huoyaoyuan** [comment]
Should be covered by #6432
