### ISSUE TITLE
Add ability to reverse sliders

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7126]
An idea for when the Editor is almost done.
**Describe the new feature:** 
Add a new button to flip the direction of the slider ( end will be where the start is and vice versa )
**Notes**: 
Extra segments added on the end to meet the beat snap divisor would need to be accounted for.

**Comment by peppy** [comment]
All features in the existing editor will eventually be added.

**Comment by MightyHelper** [comment]
Just to clarify, I didn't mean reverse as in the reverse arrow. but to reverse the direction of the control curve.

**Comment by Joehuu** [comment]
Added in https://github.com/ppy/osu/pull/10432.
