### ISSUE TITLE
Change osu!stable search directory manually

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7128]
**Describe the new feature:** 
"Couldn't find osu!stable install directory", makes sense, since stable is installed under the windows partition.
I've mounted it onto /mnt and have access to the osu! stable folder.
Is there a way to pass in this folder path to osu!lazer?

**Comment by peppy** [comment]
Please symlink it to `~/.osu`

**Comment by MightyHelper** [comment]
![file ~/osu\!](https://user-images.githubusercontent.com/32612290/70452198-7ab6e300-1a85-11ea-86a2-140028d80c07.png)
![Osu Notification](https://user-images.githubusercontent.com/32612290/70451919-0419e580-1a85-11ea-92fe-fb51a2103450.png)

**Comment by peppy** [comment]
Please re-read my reply.

**Comment by MightyHelper** [comment]
Ooff, sorry.
Thanks
