### ISSUE TITLE
fix HitCircle numbers not appearing on skin even when available

### ISSUE THREAD

**Issue by Luxiono** [ppy/osu#7133]
**Describe the bug:** 
I am creating my own skin right now, and even though all numbers for HitCircles are available, they do not show up.
**Screenshots or videos showing encountered issue:** 
![osuthing](https://user-images.githubusercontent.com/55364481/70479475-6ede1780-1aab-11ea-91cb-74a86171a96f.png)
**osu!lazer version:** 
2019.1205.0 on Windows 10
**Logs:** 
None found.

**Comment by peppy** [comment]
You need to provide `hitcircle` and `hitcircleoverlay`. Skinning just numbers is not supported.

**Comment by Luxiono** [comment]
How come you changed that from `osu!stable`?

**Comment by peppy** [comment]
lazer uses a different skinning system. once we are done, it will be possible again, but for now we are supporting legacy skins on a per-component level. if the piece(s) of the component which lazer uses to decide whether that component is skinned or not are not present, that component will use the lazer default.

On further checking, the numbers should be their own component. SO the fact it's not showing up for you means you may have made an error in your sprite files. Could you attach them to this issue?

**Comment by Luxiono** [comment]
[Simple Skin.zip](https://github.com/ppy/osu/files/3957098/Simple.Skin.zip)
Here's a zip of the current files.

**Comment by peppy** [comment]
I've checked the attached skin and it works as expected.

**Comment by Luxiono** [comment]
I did add the `hitcircle` and `overlay` files, and it worked just fine. The numbers did appear.

**Comment by peppy** [comment]
Even without the extra files, it works fine here:

![image](https://user-images.githubusercontent.com/191335/71141851-d4bf6180-2258-11ea-8777-05ff8a32128d.png)

Closing issue for now.
