### ISSUE TITLE
Select audio for toggles repeat on scroll

### ISSUE THREAD

**Issue by Squiddu** [ppy/osu#7134]
**Describe the bug:** 

**Screenshots or videos showing encountered issue:** 
https://streamable.com/s/x2508/zxpflr
Quality is low, sorry.
**osu!lazer version:** 
2019.1205.0 on Windows 10
**Logs:** 
None.

**Comment by peppy** [comment]
This likely requires a framework-side fix. Can reproduce easily locally and feels like it might be an off-by-one issue with scrolling containers.

**Comment by peppy** [comment]
The video for this report is gone, but I think it's referring to the hover sound while dragging in a scroll view? If so, this has since been resolved.
