### ISSUE TITLE
Visual Bug on wake up from suspend - Linux

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7135]
**Describe the bug:** 
Loss of Text when re-opened **after** waking up from suspend
**Screenshots or videos showing the encountered issue:** 
![osu_2019-12-09_21-17-02](https://user-images.githubusercontent.com/32612290/70484084-701e3d00-1ac9-11ea-870c-677801ba2885.jpg)

**osu!lazer version:** 
did a `git pull` today
version says local debug
**Logs:** 
Visual. ( For future reference cant find `runtime.log` anywhere in the tree )

**Comment by peppy** [comment]
I believe this may be out of scope of our project. It looks like a driver issue/shortcoming, and not something we will be able to fix with the information you provided. Feel free to re-open if you come across diagnostic information (such as console output while running or `syslog` output mentioning a specific GL misuse) and we can potentially look into it further.

I'd start by ensuring your drivers are up-to-date and maybe googling for issues with your hardware/drivers in linux.
