### ISSUE TITLE
Alt + Enter For Fullscreen also starts a game

### ISSUE THREAD

**Issue by LanTenDragon** [ppy/osu#7137]
**Describe the bug:** While cycling through Alt + Enter, borderless and windowed mode works fine, but when it comes to Fullscreen, the window enters fullscreen mode but also triggers the song select and enters you to a game. 

**Screenshots or videos showing encountered issue:** https://streamable.com/y00q9

**osu!lazer version:** 1a36179c8d7127f1fd017792423b4f6a0b170279 (current master)
**OS:** Manjaro
**DE:** KDE

**Logs:** [runtime.log](https://github.com/ppy/osu/files/3942894/runtime.log)

**Comment by enoslayd** [comment]
Also you cant alter the fullscreen state using alt + enter on num pad

**Comment by Joehuu** [comment]
This is fixed in SDL (tested using Ubuntu).

**Comment by Joehuu** [comment]
Fixed in SDL as of now (using Ubuntu).
