### ISSUE TITLE
Returning from minimised fullscreen window breaks resolution

### ISSUE THREAD

**Issue by LanTenDragon** [ppy/osu#7141]
**Describe the bug:** This is an intermittent bug. I am actually not sure how to reliably reproduce this bug. All I know is when the game is in fullscreen mode, Alt+Tab or press the Start menu key (and perhaps perform some action such as opening your audio manager and adjust the volume) When you return, the game resolution is wrong. Restarting the program solves it every time.
 
**Screenshots or videos showing encountered issue:** https://streamable.com/is5kf
![Screenshot_20191210_202207](https://user-images.githubusercontent.com/43511642/70529676-1b8fc600-1b8c-11ea-88f7-529dbe86f3d7.png)

**osu!lazer version:** current master

**Logs:** 
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3944834/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3944835/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3944836/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3944837/performance-gamethread.update.log)
[performance.log](https://github.com/ppy/osu/files/3944838/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3944839/runtime.log)

**Comment by LanTenDragon** [comment]
Just found the steps to reproduce.
1. Lauch the game in windowed / borderless.
2. While it is loading, Alt-Enter to change to Fullscreen
3. The error below **MIGHT** appear. If not, try again
```X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x2003511
  Serial number of failed request:  676
  Current serial number in output stream:  678
```
4. Launch the game again, now it should be running in fullscreen, Alt+Tab out and come back.

**Comment by Joehuu** [comment]
Fixed in SDL as of now (using Ubuntu).
