### ISSUE TITLE
osu!catch autoplay looks glitchy on specific map

### ISSUE THREAD

**Issue by GSculerlor** [ppy/osu#7145]
**Describe the bug:** 
Probably caused by multiple notes at same point, but *should be* not related with #3965
Map: https://osu.ppy.sh/beatmapsets/90935#fruits/265177 

**Screenshots or videos showing encountered issue:** 
https://streamable.com/t9mgb

**osu!lazer version:** 
commit `f3ec98d`

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3945079/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3945080/runtime.log)

**Comment by peppy** [comment]
This is probably due to hitobjects not being sorted by time, causing the game to need to rewind to correctly play the beatmap.

**Comment by GSculerlor** [comment]
safe to close, I guess. the map linked on the post is playing correctly the last time I tested it.
