### ISSUE TITLE
Ability to delete scores

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7146]
Title is descriptive enough.

**Proposal designs of the feature:** Right-click for a context menu with item "Delete". Clicking it gives a dialog asking for confirmation.

**Comment by wltu** [comment]
Hi, 

May I work on this issue? Unless @mcendu or someone else is already working on it.

**Comment by Joehuu** [comment]
Feel free to do so. Will assign it to you. Just ask when you want to back out, so someone else can take this.

**Comment by wltu** [comment]
Sounds good. Will update on the progress or any questions on this thread.
