### ISSUE TITLE
ModTimeAdjust should has ability to roll-back when unselect

### ISSUE THREAD

**Issue by andy840119** [ppy/osu#7156]
**Describe the bug:** 
After some mod like `ModDaycore` or `OsuModDoubleTime` unselected, track's playback speed is not recovered.

**Screenshots or videos showing encountered issue:** 
See this video : 
https://streamable.com/2m2ur

**osu!lazer version:** 
2019.1205.0

**Logs:** 
Nope

**Fix suggestion**
`IApplicableToTrack` should have a method like `void ReverseApplyToTrack(Track track);`.

**Comment by peppy** [comment]
Should be fixed via https://github.com/ppy/osu/pull/7121. Please confirm.

**Comment by l3lackShark** [comment]
@peppy This PR does fix this issue!
