### ISSUE TITLE
Add avatar to results screen

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7159]
**Describe the new feature:** It would make sense, since the player's name and cover are already displayed and there's an empty space above the name.

**Proposal designs of the feature:** 

![image](https://user-images.githubusercontent.com/15932372/70643381-28babc80-1c41-11ea-8000-b9b5ea544c88.png)

**Comment by iiSaLMaN** [comment]
I believe results screen will have a new design, no need to modify current design for now.

**Comment by timrowland-wq** [comment]
This should be closed by [#8311 ](https://github.com/ppy/osu/pull/8311)

**Comment by Joehuu** [comment]
Resolved in #8311.
