### ISSUE TITLE
Graphical oversights on results screen

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7160]
**Describe the bug:** When either side panel is opened, all shadows become lighter, and two of the outer circles don't darken.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/15932372/70644346-1f325400-1c43-11ea-968a-96c348224521.png)

**osu!lazer version:** 2019.1205.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3951676/database.log)
[network.log](https://github.com/ppy/osu/files/3951677/network.log)
[performance.log](https://github.com/ppy/osu/files/3951678/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3951679/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3951680/updater.log)

**Comment by Gabixel** [comment]
duplicate of https://github.com/ppy/osu/issues/4229 (mentioned in [this](https://github.com/ppy/osu/issues/4229#issuecomment-461888393) comment)

**Comment by smileyhead** [comment]
Closing and commenting about shadows on #4229
