### ISSUE TITLE
Mods that change clock speed are not resetting

### ISSUE THREAD

**Issue by aspriddell** [ppy/osu#7162]
**Bug**
When a song is selected and a mod like `DT`, `NC`, `HT` or `DC` is picked, the music clock is changed but is being multiplied and not reset. For example, if nightcore is picked, it applies the clock speed multiplier for DT then adds NC multipliers on top, making the map a lot faster (or slower in daycore's case) than expected. If one of these mods is selected, enabling/disabling any other mod causes them to multiply up as well.

**Video** 
https://drive.google.com/open?id=1iSnLUYN7ZTmkvnwbdTrrh9XREPRoT81d
https://drive.google.com/open?id=1jNNJnNQ7jDOK20SDlLuKKB6jRs7JEbqo

**Version**
osu!lazer version 052d0f4 release build

**Comment by bdach** [comment]
See #7156 and #7158; please check if #7121 fixes it. I'll leave this open so we don't get any more.
