### ISSUE TITLE
osu!lazer replay unavailable

### ISSUE THREAD

**Issue by JensDaBaws** [ppy/osu#7164]
**Describe the bug:** 
it says the replay is unavailable even though i just completed it
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.1205.0 (current)
**Logs:** 
![d fdgs](https://user-images.githubusercontent.com/58792611/70664486-c4acee00-1c6a-11ea-86d6-2af7892dc095.PNG)

**Comment by iiSaLMaN** [comment]
See https://github.com/ppy/osu/issues/5309, can be closed.
