### ISSUE TITLE
Regarding Slider Accuracy in osu!Lazer

### ISSUE THREAD

**Issue by 232313** [ppy/osu#7176]
As the release of osu!Lazer is closing in (soonTM >.>), I was thinking about the slider accuracy feature of osu!Lazer. Me amongst others I've talked to about this have shown distaste for this feature.
So my suggestion, (Although it may seem idiotic as I have NO experience when it comes to coding) is as follows;

If we were to make the slider accuracy feature a modification, such as Hidden or Hardrock, which modify the gameplay. From this, I feel we could accomplish a silver lining, for those who want slider accuracy and those who don't. Perhaps, another solution could be making it the other way around. Having slider accuracy a permanent feature so to speak, and having a mod which removes this slider accuracy, but perhaps works like the mods; EZ HT and such (Make the multiplier something like 0.75x or something fitting).

Again, this might very well either not be possible, or not be a good idea. Just thought I'd share my thoughts.

**Comment by peppy** [comment]
We may offer a "classic scoring" mod for that classic experience. The final direction is not yet established and I would hesitate to even have this discussion just yet until you actually see how things play out.

In the mean time, I would highly recommend getting-better. Slider head accuracy is making it possible to judge your performance better than ever before. It's taking the half-assed-ness out of sliders.

If your distaste lies in that it will "play bad with x y z maps" then please understand that we are aware of such issues and will aim to address them.
