### ISSUE TITLE
sound problem

### ISSUE THREAD

**Issue by MrDemiurge** [ppy/osu#7177]
**Describe the crash:** 
The sound comes with the effect of electronic music
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
app-2019.1205.0
**Logs:** 
No
**Computer Specifications:** 
ProcessorIntel(R) Xeon(R) CPU E5-2689 0 @ 2.60GHz
Video Card:AMD Radeon HD 5670
RAM16 GB
Operating System:Windows 10

**Comment by peppy** [comment]
Please at least include a video of what you are seeing/hearing, along with logs.

**Comment by MrDemiurge** [comment]
https://drive.google.com/open?id=1YmWO9mLjd6gLdl8ksefA23lkHsUs48XO

**Comment by stanriders** [comment]
It sounds like it's in mono if anything. I don't hear any effects there

**Comment by MrDemiurge** [comment]
![image](https://user-images.githubusercontent.com/58777316/70734667-b8359d80-1d1d-11ea-9568-6ac5cc829265.png)
Found the problem by the method of poke, the reason was in the surround sound of Windows sonic!
