### ISSUE TITLE
Fullscreen bug where lazer starts to flicker

### ISSUE THREAD

**Issue by KimoriWasTaken** [ppy/osu#7178]
**Describe the bug:**
Either the latest Lazer update or what is more likely to be the cause, newest Radeon Adrenaline 2020 Edition update causes issues in Fullscreen mode
For me Lazer starts to sort of "flicker" where portions of the screen turn black for 1ms or get replaced by portions of a different part of the screen for 1ms whenever I move the cursor
They seem random in size and on random positions but are always more wide than high
It happens in menu and in game

**Screenshots or videos showing encountered issue:**
For some reason I can not screenshot or record it, it seems to only affect whats projected on the monitor

**osu!lazer version:**
latest

**Comment by KimoriWasTaken** [comment]
I also can't rollback drivers with Radeon easily and test it, but will report back once they release a new update, because looking through the feedback on 2020 Edition there are a lot of bugs so it might get resolved by them next update

**Comment by smoogipoo** [comment]
This is a driver issue - nothing's changed at our end.
