### ISSUE TITLE
Another aproach circle mod idea

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7180]
**Describe the new feature:** 

Idea 1: Make the **approach circle** go from **diameter 0** to the **width** of the **hit circle** or vice versa.
Notes: Approach circle needs to somehow be visible inside the circle which brings me to idea 2
Idea 2: Same idea as 1 but **swap** hit the **circle** with **approach circle**: approach circle is still and hit circle grows to size.

**Comment by smoogipoo** [comment]
Idea 2 is already implemented as the grow and deflate mods.

Idea 1 sounds like a mess due to visual overlaps. Going to close for now - feel free to make a PR and see how it looks yourself and can resolve the inherent issues therein.

**Comment by osu-Zaike** [comment]
Ooh like how Jubeat does their approach timings.
