### ISSUE TITLE
Hang on intro

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#7187]
**Describe the bug:** 
Booted up osu!lazer, and as the intro was playing alt tabbed to discord and typed to someone, when alt tabbing back the intro is just frozen on the "welcome to osu!" text.

edit: happens every osu!lazer bootup too, not just time. I'll try reinstalling.
edit 2: switched to circles bootup sequence using the game.ini, boots just fine now. seems like the "welcome to osu!" sound effect never plays, though. triangles nor circles
edit 3: switched back to triangles, hangs again now 
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/33783503/70804446-6be66e00-1dae-11ea-8882-f2ef9c0ea433.png)

**osu!lazer version:** 
2019.1205.0 

**Logs:** 
[logs.zip](https://github.com/ppy/osu/files/3961057/logs.zip)

**Comment by iiSaLMaN** [comment]
1. Are you sure it's related to you switching between lazer and discord?
2. Does running again stuck at `welcome to osu!` part or just nothing appears.

**Comment by Hubza** [comment]
@iiSaLMaN 

1. its not related at all, completely closed discord and it still does the same thing (check edits)
2. yes, it continues to get stuck (attaching video soon) 
3. no, let me try that now

**Comment by iiSaLMaN** [comment]
Before trying to remove the data, please save it as we may need it soon.

**Comment by Hubza** [comment]
removed the data from the osu folder, loads perfectly fine, will slowly load back in all the files i had in that folder until it crashes again. there's also an update so i'll move all the files back instantly after that to see if it does anything.

**Comment by Hubza** [comment]
copied every folder but "files" back in, still launches fine.
upon copying the files folder in, it continues to crash. it seems the update fixed it but i will research more

**Comment by bdach** [comment]
Attached logs look clean. Please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by peppy** [comment]
Did you happen to somehow import the triangles intro osz from `osu.Game.Resources`? This is the only thing that comes to my mind if moving `files` helped.

Either that or a corrupt initial (automatic) import of triangles to the files folder.

**Comment by Joehuu** [comment]
@Hubza can you still reproduce?

**Comment by Joehuu** [comment]
@Hubza made a recent performance test video, so closing as resolved.
