### ISSUE TITLE
Trackpad not working on macOS with raw input disabled

### ISSUE THREAD

**Issue by edisonlee55** [ppy/osu#7188]
**Describe the bug:** 
I encounter this issue after update to osu!lazer `2019.1213.0`.

Trackpad on MacBook Pro running macOS is **not working** when raw input disabled but works when raw input enabled.

I am not sure if an external mouse would also encounter this issue.

Also, Tablet would still work with raw input disabled but **doesn't work** when raw input enabled.

---

**Screenshots or videos showing encountered issue:** 
<img width="1440" alt="截圖 2019-12-13 下午10 59 47" src="https://user-images.githubusercontent.com/5277788/70809309-7e879400-1dfc-11ea-85d5-d37b8659fb46.png">

> The cursor (when using trackpad) is stuck in the bottom right corner.

---

**osu!lazer version:** 
2019.1213.0

---

**Logs:** 
No error logs.

**Comment by bdach** [comment]
Tablets not working with raw input on is already tracked at #6290. Leaving open for the trackpad part, since I cannot test if this reproduces.

**Comment by smoogipoo** [comment]
Weird, I can't replicate this. What version of macOS? Also is this a hackintosh?

**Comment by edisonlee55** [comment]
I am using macOS Catalina 10.15.1（19B88）
Not a hackintosh, using Apple MacBook Pro (13-inch, 2017)

**Comment by edisonlee55** [comment]
The issue not reproducible after updating to `2019.1216.0`.

**But still have a weird behavior when opening osu!.**
When opening osu!, I must switch the window to another application and switch back to osu! so that the mouse can be clickable.
This issue has already happened in many versions of osu!lazer on my end.

**Comment by rayriffy** [comment]
I can confirm this issue on version **2019.1216.0**. This can be temporary fix by hitting `Option + Enter` and go back into fullscreen. But when application is reopened on fullscreen state, cursor will go to top-right corner first at disclaimer page, and then followed by bottom-right corner when startup animation started.

**Comment by smoogipoo** [comment]
Thanks, I've managed to replicate it.

**Comment by pjcdesmond** [comment]
turning off mouse accel via terminal and then logging off manages to work around this problem
cursor will be able to move but unable to click.
tabbing out to another application and then back to osu restores the full functions

not sure if this will be a long term fix, or if this needs to be done every time it boots.

**Comment by peppy** [comment]
Is this still an issue? We have since switched to SDL2 so there's a high likelihood that this has been resolved.

**Comment by edisonlee55** [comment]
No, the issue is resolved. Thank you!
