### ISSUE TITLE
Add "cancel download" button to osu!direct search screen

### ISSUE THREAD

**Issue by DCNick3** [ppy/osu#7190]
**Describe the new feature:** 

As for now, after you click the "download" button it changes it's colour and becomes non-clickable:

![Screenshot_20191213_182256](https://user-images.githubusercontent.com/10363282/70810878-9992dd80-1dd5-11ea-983c-e2c17f471865.png)

I propose to change it to cancel button, instead of just disabling it, to allow to cancel the download right away, without going to notifications and searching appropriate entry there.

I've been downloading songs for quite a while now, and the idea of such cancellation came to me several times... I even clicked the button unconsciously in order to cancel the download. That is why I think it would be natural to make it that way

**Proposal designs of the feature:** 

Change the icon to "cross" and make it red on mouse hover. Click works in same way as cancellation in the notifications.

**Comment by GSculerlor** [comment]
#6125

**Comment by DCNick3** [comment]
Yes, it's a correct one. Don't know how could I miss it, even after doing the appropriate search. Sorry.
