### ISSUE TITLE
Length is 0:00 for every beatmap

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#7194]
**Describe the bug:** Basically the Length icon indicates that every beatmap has the length of 0:00; probably a regression as i think it worked before.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/19843905/70827726-1af46b00-1dea-11ea-90c6-b26abda34bbd.png)

**osu!lazer version:** 2019.1023.0

**Logs:** -

**Comment by iiSaLMaN** [comment]
Does this also happen for newly downloaded beatmaps? if not, then do a full reimport of your beatmaps (see #5376)

**Comment by TPGPL** [comment]
oh actually it works with newly downloaded beatmaps
