### ISSUE TITLE
Lazer will not start

### ISSUE THREAD

**Issue by simon1925** [ppy/osu#7195]
I recently installed the latest version of osu!lazer as I wanted to try it out, however, when I attempted to start lazer, nothing happened. I tried re-installing and running as an administrator but it did not help.

Google Drive link to video of me running lazer and then opening Task Manager to show that it is not running (Sorry for poor quality but my PC cannot handle video recording very well).
https://drive.google.com/open?id=1y8-CS-14XfHYP5IErYdc46pLX3oUKMMd

**Comment by bdach** [comment]
Please attach logs from `%AppData%/osu/logs`.

**Comment by simon1925** [comment]
[runtime.log](https://github.com/ppy/osu/files/3963050/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/3963051/update_success.log)
These are the logs in my normal osu folder. There aren't any in my lazer folder

**Comment by bdach** [comment]
Please attach Windows Event Viewer info after trying to run lazer by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by simon1925** [comment]
I have uploaded it here:
https://drive.google.com/open?id=10IZO1h18f1Ty3GK1kWF0YpqE4EXWLdqK

**Comment by bdach** [comment]
Well, there is *something* in that event log, but it's very opaque:
```
Application: osu!.exe
CoreCLR Version: 4.700.19.51502
.NET Core Version: 
Description: The process was terminated due to an internal error in the .NET Runtime at IP 000007FECCF84523 (000007FECCDD0000) with exit code c0000005.
```
I'm not sure how to proceed here without actually debugging, but more information could maybe help.
* What are your hardware specifications?
* Could you try upgrading .NET Core from 3.0.1 to 3.1? I want to eliminate the possibility of this being a coreclr bug that might already have been fixed.

**Comment by smoogipoo** [comment]
Please try installing the prerequisites listed on https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore30&pivots=os-windows for your system.

Specifically, you will need:
1. https://www.microsoft.com/en-us/download/details.aspx?id=52685
2. https://support.microsoft.com/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

**Comment by simon1925** [comment]
I have installed the prerequisites you have linked to and also tried running an older version of the game but nothing has changed.
These are my hardware specs:
![image](https://user-images.githubusercontent.com/58862638/70853460-4177dc00-1ea6-11ea-811d-6f71436bdab3.png)
My graphics are on an Intel 4 Series Internal Chipset

**Comment by bdach** [comment]
This might be some Intel funkiness again - they have a tendency to leave their discontinued hardware in a broken state. I'd try checking for driver updates (especially for the graphics card), if that doesn't work then I'd say we can't really proceed without you actually debugging.

**Comment by simon1925** [comment]
I just updated my drivers but it's still not working
