### ISSUE TITLE
Lazer Tournament client won't open.

### ISSUE THREAD

**Issue by nekoraw** [ppy/osu#7197]
**Describe the crash:** 
after today's update, osu!lazer tourney client won't open anymore. osu!lazer still opens normally.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/98i5t

**osu!lazer version:** 
local after  #7191 solved

**Logs:** 
[runtime](https://nekoraw.s-ul.eu/QZfABgix)
network, runtime, updater and database didnt seem wrong.

**Computer Specifications:** 
https://valid.x86.fr/5ezh6s

**Comment by l3lackShark** [comment]
@nekoraw The client does run fine for me. Please try to rename your bracket.json file to bracket2.json (%appdata%\osu) and see if that helps.

**Comment by nekoraw** [comment]
@l3lackShark renaming bracket2.json worked fine 
after i saved changes, the client created another bracket.json
after relaunching the client, it wouldn't work anymore, even without any team/match added

**Comment by nekoraw** [comment]
found a workaround: [delete the Ruleset segment from bracket.json](https://nekoraw.s-ul.eu/mnlTJznF). It will show back again when you save changes on the client. Didn't test with actual gameplay if everything is working fine.
[video example](https://streamable.com/g57c6)
