### ISSUE TITLE
display final results of mod customization

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#7201]
where the customization section is it will display whatever is the result of having slider bars in certain positions

an example is when the mods DT and WU are activated and they are set to 1.5 and 1.1 respectively, it should display that the final speed rate is x1.5-x1.65 in the customization box near the bottom

**Comment by peppy** [comment]
final difficulty changes will come with https://github.com/ppy/osu/pull/7175.
speed display will be a HUD element in the future.

mods aren't aware of each other's adjustments, so it's not possible or logical to display aggregates in the settings area itself.
