### ISSUE TITLE
Add a  button to reset customization of a mod

### ISSUE THREAD

**Issue by timrowland-wq** [ppy/osu#7202]
When using the new mod customization feature (e.g. altering speed increase of DT), it is somewhat tedious to return the slider back to the original speed it was set at. I believe adding a button to do this below the customization slider would be very helpful!

**Comment by peppy** [comment]
When you change a slider, a little yellow light appears to the left. Click it to reset.

**Comment by timrowland-wq** [comment]
Ah my bad!
