### ISSUE TITLE
Notelock/Shake behavior does not match stable

### ISSUE THREAD

**Issue by McKay42** [ppy/osu#7215]
**Describe the bug:** 
In lazer, the next hitobject can be clicked as soon as the slider has started sliding.

In stable, the next hitobject can only be clicked after the entire slider is finished. (However, there also seems to be a special exception for [2B maps](https://osu.ppy.sh/beatmapsets/474413#osu/1013379) which allows clicking through simultaneous hitobjects.)

Not many beatmaps are affected by this, but apparently some people click sliders by hitting both keys at the same time, like here (0:50): https://osu.ppy.sh/beatmapsets/874835#osu/1828342
Which would currently cause an early miss/50/100 (for the circle underneath the sliderstartcircle) in lazer but not in stable.

**Screenshots or videos showing encountered issue:** 
stable:
![stable](https://user-images.githubusercontent.com/16856443/70854932-0637d600-1ec3-11ea-9821-04b907e30f66.gif)

lazer:
![lazer](https://user-images.githubusercontent.com/16856443/70854934-0b952080-1ec3-11ea-9b94-87ef4e4cd8e2.gif)

**osu!lazer version:** 
2019.1213.0

**Comment by Coppertine** [comment]
You know this is one of the major reasons lazer was developed right? No notelock in lazer? So it does allow an object that is later than the previous to be hit not matter what..

**Comment by MightyHelper** [comment]
I am still intrigued as to why you aren't getting a miss on the circle since you clicked too early.

**Comment by peppy** [comment]
Note lock is not yet implemented to any degree. We are still assessing whether to add it back in some way, but a decision has not been made yet.

It may return as a toggle or as a forces thing (but more lenient than stable).

As this is a controversial topic and we are a bit far away from the experimentation / decision phase, I’m going to close this for now.

**Comment by McKay42** [comment]
> 
> 
> Note lock is not yet implemented to any degree. We are still assessing whether to add it back in some way, but a decision has not been made yet.

Ah I see, the shake is only caused by being outside of even the miss range ([HitResult.None](https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs#L121)).


> 
> 
> I am still intrigued as to why you aren't getting a miss on the circle since you clicked too early. ( In lazer )

I misinterpreted the shake being caused by a notelock implementation, while the timing was just right to be too early for the miss window until the slider started.
