### ISSUE TITLE
Osu!lazer not start

### ISSUE THREAD

**Issue by hutowar** [ppy/osu#7224]
My PC:
https://ibb.co/0Bmy87y
https://ibb.co/sjnjsnv
https://ibb.co/bv9RjS5

**Comment by bdach** [comment]
Please attach logs from `%AppData%/osu/logs`.

**Comment by hutowar** [comment]
I do not have %AppData%/logs

**Comment by hutowar** [comment]
%AppData%/osu/logs*

**Comment by bdach** [comment]
Please attach Windows Event Viewer info after attempting to launch lazer by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by peppy** [comment]
Reopen if you can provide details as asked in the template.
