### ISSUE TITLE
Hard Rock mod's changes to objects persist

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu#7231]
**Describe the bug:** `OsuModHardRock` or basically any mod that alters an object's position persist after and outside gameplay.

**Screenshots or videos showing encountered issue:**
Before:
![image](https://user-images.githubusercontent.com/20495991/70886171-c9302880-2015-11ea-9fd3-e1534eae452f.png)
With Hard Rock:
![image](https://user-images.githubusercontent.com/20495991/70886200-dbaa6200-2015-11ea-821f-4c736ab5fb3f.png)
Hard Rock removed:
![image](https://user-images.githubusercontent.com/20495991/70886220-ecf36e80-2015-11ea-9266-3084651c3646.png)
In Editor:
![image](https://user-images.githubusercontent.com/20495991/70886262-0ac0d380-2016-11ea-9a2a-3727df559c59.png)

**osu!lazer version:** master

**Logs:** N/A

**Comment by smoogipoo** [comment]
Fixed via https://github.com/ppy/osu/pull/7230 (you'll want to re-fetch since the fix only happened 5 minutes ago).
