### ISSUE TITLE
Place to specify location of osu! folder if not automatically found.

### ISSUE THREAD

**Issue by nathanielcwm** [ppy/osu#7234]
When the stable folder isn't found automatically could there be an option to point the client to the stable install directory?

**Comment by peppy** [comment]
This is not planned because detection should be automatic. Can we instead try and fix the reason why it's not finding your folder? Where is your stable install located, and did you perhaps deny osu-stable the ability to write to the registry?

**Comment by nathanielcwm** [comment]
I was trying lazer on linux and my stable install is on my pendrive which probably explains that.

**Comment by peppy** [comment]
If on linux, you can symlink your osu! folder to `~/.osu` and it will import as expected.

**Comment by nathanielcwm** [comment]
ahh good to know

**Comment by nathanielcwm** [comment]
yep works perfectly fine now

**Comment by nathanielcwm** [comment]
would be nice if it explicitly stated that it looks for beatmaps in ~/.osu on linux though.
