### ISSUE TITLE
Switching to Winter Season

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#7235]
*[Winter is there](https://osu.ppy.sh/home/news/2019-12-10-winter-is-here) but not in here yet!*

Here are some tasks required for switching to winter season (I suppose):
- [ ] Wintery osu! logo
- [ ] [carol of the circles](https://www.youtube.com/watch?v=Uaz-vy5Rt1s) Intro
- [ ] Winter season backgrounds (can be [implemented statically](https://github.com/ppy/osu-resources/tree/master/osu.Game.Resources/Textures/Menu) or wait for https://github.com/ppy/osu/issues/7055)

**Comment by peppy** [comment]
Not going to happen this year unless you are planning on implementing. Too many prereqs.

**Comment by iiSaLMaN** [comment]
Closing, can be reopened next year.
