### ISSUE TITLE
Ability for slider heads to have a different texture from hit circle

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7245]
[Feature already in stable.](https://osu.ppy.sh/help/wiki/Skinning/osu!#slider)

**Comment by frenzibyte** [comment]
[This has since been supported](https://github.com/ppy/osu/commit/fb4b334ce2f9a5e44bf82cd846a7af98f7487388), and has also been improved in https://github.com/ppy/osu/pull/17878 to match stable 1:1 with regards to skin sources.
