### ISSUE TITLE
Osu!lazer not start

### ISSUE THREAD

**Issue by hutowar** [ppy/osu#7246]

**Comment by hutowar** [comment]
https://drive.google.com/file/d/1HGlHvDrxK2ZCu4ExodDafiplF8AigAUb/view?usp=sharing
event windows

**Comment by bdach** [comment]
You haven't installed the [.NET Core Runtime](https://docs.microsoft.com/en-us/dotnet/core/install/runtime?pivots=os-windows), which is a prerequisite for lazer. Please install and try running again; closing.
