### ISSUE TITLE
Multiple difficulties of the map in a multiplayer lobby

### ISSUE THREAD

**Issue by vruss** [ppy/osu#7249]
**Describe the new feature:** 
Give users the option to enable "Multiple difficulties of the map". Similar to how there's currently an option for free mod. This option could also enable ScoreV2 which would normalize the score and make it competitive for all players.

This would allow casual players to play with their friends of all ranks without forcing a potential bad experience for newer players. And experienced players have a greater incentive to play with newer players since they can still play on a higher difficulty if they desire it.

**Proposal designs of the feature:** 
I'm thinking maybe a dropdown of possible difficulties with difficulty name and star rating could appear if clicked on the map name in the lobby.

**Comment by GSculerlor** [comment]
Kinda similar with #5578

**Comment by smoogipoo** [comment]
Closing as duplicate.

**Comment by vruss** [comment]
> 
> 
> Kinda similar with #5578

I'm thinking this could be implemented in a more classic lobby, not necessarily Timeshift
