### ISSUE TITLE
Can't load/play beatmap with storyboard

### ISSUE THREAD

**Issue by MikiraSora** [ppy/osu#7265]
**Describe the bug:** 
In beatmap all diff [Hikouki Gumo (el poco maro DnB EDIT)](https://osu.ppy.sh/beatmapsets/357161).
Ifenable storyboard and it will keep loading.
If disable , it work and enter play field.

I check performance.log and found a lot exception were logged.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
[2019.1216.0](https://github.com/ppy/osu/releases/tag/2019.1216.0)

**Logs:** 
[log files](https://puu.sh/EQKPG/3567a29213.zip)

**Comment by smoogipoo** [comment]
It does actually load, it just takes a long time. This is due to the storyboard elements having hundreds of transforms, which we _could_ optimise a little bit given some refactoring, but the eventual goal is to fix this via https://github.com/ppy/osu/issues/6136
