### ISSUE TITLE
osu!direct beatmap flow container doesn't respect scaling

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7273]
**Describe the bug:** If the window size is too small (<684px) for osu!direct to display two columns at 1x UI scale, osu! will not update the column count if the UI scale is changed to be able to account for two columns.

**Screenshots or videos showing encountered issue:**

![image](https://user-images.githubusercontent.com/15932372/71113360-b3fdfa00-21cd-11ea-897a-e31b0a8332f7.gif)

**osu!lazer version:** 2019.1216.0

**Comment by bdach** [comment]
The converse is also true - when resizing the UI to be able to fit two items in a row, the rows will overflow when upscaling:

![image](https://user-images.githubusercontent.com/20418176/71115391-1b1dad80-21d2-11ea-9ebc-6b2c71ad96fb.png)

**Comment by smoogipoo** [comment]
Ouch. I believe this is related to https://github.com/ppy/osu-framework/issues/223, which we have no current solution to.

Other elements are also broken, like the tab control, which should display the dropdown button if it's overflowed.

I'll look into investigating this and other issues this weekend...

**Comment by peppy** [comment]
Just for completeness, another case in the new multiplayer layout:

![2020-02-16_18-32-10](https://user-images.githubusercontent.com/191335/74605080-d649c080-5107-11ea-96ae-2b0a1c564ef3.gif)
