### ISSUE TITLE
Add song ticker to main menu

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7274]
**Describe the new feature:** (This is something that's in stable, but not yet in lazer.) A ticker that would show up briefly (or indefinitely, if the user prefers) as a new song starts playing in the main menu.

**Proposal designs of the feature:** 

![image](https://user-images.githubusercontent.com/15932372/71113937-f70c9d00-21ce-11ea-8a90-e7fff608cfd6.png)

**Comment by peppy** [comment]
Requires input from @arflyte

**Comment by arflyte** [comment]
Hmm, that works for now. I'll make a design for it so it fits well with the rest of the indicators at the corner.

**Comment by peppy** [comment]
If we go with the design in the screenshot, make it a gentle fade with no movement.
