### ISSUE TITLE
Wrong button animates if exiting via window X button

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7275]
**Describe the bug:** If I exit the game using the OS's X button, in the confirmation dialogue, ‘Just a little more’ animates instead of ‘Good bye’.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/15932372/71114387-f294b400-21cf-11ea-8ec8-050ceb955186.gif)

**osu!lazer version:** 2019.1216.0

**Comment by bdach** [comment]
Going to link [this old comment of mine](https://github.com/ppy/osu/pull/6826#issuecomment-552920729) as an example way of how this can be done.
