### ISSUE TITLE
Osu Lazer Won't start on Android

### ISSUE THREAD

**Issue by noidea-productions** [ppy/osu#7282]
**Describe the bug:** 
When I open osu!lazer, it shows a blank screen then it crashes.
**Screenshots or videos showing encountered issue:** 
N/A
**osu!lazer version:** 
2019.1219.0
**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3983779/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3983780/runtime.log)

**Comment by bdach** [comment]
Relevant error:
```
2019-12-19 13:31:28: An unhandled error has occurred.
2019-12-19 13:31:28: System.NotImplementedException: The method or operation is not implemented.
2019-12-19 13:31:28: at osuTK.GameViewBase.get_Bounds () [0x00000] in <7484b4753167456b82f11e78c0669d25>:0
2019-12-19 13:31:28: at osu.Framework.Platform.GameWindow.get_Bounds () [0x00000] in <e18e737b2cc541c4a021200f3c60500e>:0
2019-12-19 13:31:28: at osu.Framework.Platform.GameWindow.get_CurrentDisplay () [0x00000] in <e18e737b2cc541c4a021200f3c60500e>:0
2019-12-19 13:31:28: at osu.Framework.Platform.GameHost.<SetupConfig>b__131_1
```
Quite strange that it hasn't popped up before to my knowledge.

**Comment by OWER396** [comment]
> **Describe the bug:**
> When I open osu!lazer, it shows a blank screen then it crashes.
> **Screenshots or videos showing encountered issue:**
> N/A
> **osu!lazer version:**
> 2019.1219.0
> **Logs:**
> [performance.log](https://github.com/ppy/osu/files/3983779/performance.log)
> [runtime.log](https://github.com/ppy/osu/files/3983780/runtime.log)

same actually

**Comment by Jusoko** [comment]
[performance.log](https://github.com/ppy/osu/files/3984353/performance.log)
Another log from my side of story

**Comment by bdach** [comment]
Please do not post "+1" comments under this issue. Either you're having the same issue, in which case your comments are not needed (you can use reactions if you so desire instead), or you're not, in which case you should open a new issue instead.

**Comment by bdach** [comment]
Regressed with ppy/osu-framework#3117; should probably fall back to the old method wherever the new one is unsupported.

**Comment by bdach** [comment]
I didn't intend to suggest reverting entirely, just at most hacking the code together somehow to get the old code path back on Android, as this is all temporary anyways indeed.

**Comment by rubiksmaster02** [comment]
mine just doesn't start at all. it just instantaneously closes

**Comment by peppy** [comment]
The build has been pulled. Please use the previous build.
