### ISSUE TITLE
Loading bar on song load

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7286]
**Describe the new feature:** The current loading screen only contains a spinning circle. I think replacing it with a bar would be more informative, especially with slower computers / larger maps.

**Proposal designs of the feature:** 

![image](https://user-images.githubusercontent.com/15932372/71181616-cda64c80-2274-11ea-9f8b-2b0d412dd9a4.png)

**Comment by Gabixel** [comment]
The loading bar seems a good design, but I would like to propose a second one just in case. Something similar to the animation that I saw on the Epic Games launcher: the image **is** the loading bar, the "unloaded" part is dark, and the "loaded" one is brighter.

![design](https://user-images.githubusercontent.com/43073074/71182743-f3ccec00-2276-11ea-87eb-eb3037feaf88.png)

**Comment by bdach** [comment]
Load times will probably go down still, so this might end up being a non-issue.

**Comment by EVAST9919** [comment]
Not sure if there's an ability to calculate the time of drawable loading

**Comment by peppy** [comment]
The load time will be reduced further, to the point a progress bar should not be necessary.
