### ISSUE TITLE
Multiple hover sound when Lazer window is on a secondary display

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#7287]
**Describe the bug:** I tried to put Lazer on my secondary display, and I noticed that when I enter/leave the cursor on something like a menu button or a slider in the settings, it makes multiple hover sounds. Also, if I'm not wrong, the desired behaviour should be that Lazer doesn't have to play the hover sound when leaving those buttons. (This issue doesn't happen on my main display)

**Screenshots or videos showing encountered issue:** [Video](https://drive.google.com/file/d/1ewRXi8gxpQNhmp_4K7DddDuEvUkcf4mw/view?usp=sharing)

**osu!lazer version:** 2019.1219.0

**Comment by Gabixel** [comment]
Updated the video (since the previous one was dead). This issue still happens with the latest release but seems fixed using SDL!

**Comment by Joehuu** [comment]
Can't seem to reproduce in osuTK in the first place on my two monitor setup. @Gabixel can you confirm that the latest release still fixes this?

**Comment by Gabixel** [comment]
Yep, the latest release fixed this.

Closing as resolved.
