### ISSUE TITLE
Combined error and colour score meter

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7292]
**Describe the new feature:** While one of the score meters from stable has been added, the other one hasn't. I suggest we change that. Here's a suggestion for a more modern-looking behaviour, though: instead of having the newest element scroll through the entire bar and go back to the beginning and start again, how about always having the topmost indicator be the most recent one, and with each new hit, the others would scroll down a spot (with a fluid animation) with the bottom-most one disappearing?
I would also like to take this chance to suggest an option to have both score meters displayed at the same time.

**Proposal designs of the feature:** 

![image](https://user-images.githubusercontent.com/15932372/71188707-c20d5280-2281-11ea-90e7-989d4bbf9707.png)

**Comment by peppy** [comment]
I think that looks fine for an initial implementation. If implementing, make sure it is a separate component from the existing display, and make them use a `FillFlow` to align as you have in the mockup.

**Comment by EVAST9919** [comment]
Gonna work on this

**Comment by smoogipoo** [comment]
Has been fulfilled via https://github.com/ppy/osu/pull/12845 (add two error meters via the skin editor).
