### ISSUE TITLE
Multiplayer screen should display selected mods for each room

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#7293]
Opened for discussion, since there's no design available (I guess).
**Proposal designs of the feature:**
![Screenshot_1](https://user-images.githubusercontent.com/22874522/71189867-8def5d00-2294-11ea-8eb1-de40c34b2578.png)

**Comment by peppy** [comment]
Unsure how this will work, since mods are per playlist item. Will need some thought.

**Comment by huoyaoyuan** [comment]
May require an additional visual representation of FreeMod.

**Comment by EVAST9919** [comment]
Closing as resolved since each room have playlist with mods for each map.
