### ISSUE TITLE
the "..." sprites overlap with the filters when you scale your UI in the beatmap selection menu

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#7296]
**Screenshots or videos showing encountered issue:** 

## 1.20x UI Scale
![osu!_NQRhdrYRmC](https://user-images.githubusercontent.com/43358824/71211662-e2540600-22af-11ea-9120-7612355d3586.png)

## 1x UI Scale
![osu!_ystYLSrpL2](https://user-images.githubusercontent.com/43358824/71211726-06174c00-22b0-11ea-89b3-b45bf41bfc14.png)

## 0.85x UI Scale
![osu!_u0mE0UOVVC](https://user-images.githubusercontent.com/43358824/71211109-bab06e00-22ae-11ea-976a-7e946338e91e.png)

**osu!lazer version:** 2019.1219.0

**Comment by bdach** [comment]
Probably going to be resolved the same way #7273 will. I'm going to close this on that basis.
