### ISSUE TITLE
Impossible to load into gameplay on a certain map 

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#7305]
Open this map to reproduce: https://osu.ppy.sh/beatmapsets/644332#osu/1365637

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=1OzXF3IxqeI

**osu!lazer version:** 
current master

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3988045/runtime.log)

**Comment by Game4all** [comment]
What is stable behaviour for truncating beatmap info in rich presences when it exceeds the max length? Would a basic truncation of the string to 128 bits suffice?

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/7311
