### ISSUE TITLE
Add Musicplayer-Only Mode

### ISSUE THREAD

**Issue by MaxKruse** [ppy/osu#7306]
I would like to see a Musicplayer-only mode for osu. This could be useful for folk that has rather weak computers and cant afford osu to take up GPU, even when tabbing out. 
Bonus Feature: Enable Hitsound playback, as if the map is being played by auto, while being minimized. For this, one would take the highest star-rating difficulty in the set, parse, and then just add the hitsounds to be played when their time comes.

Similar to the boss-key on stable, minimize the window, but keep playing the music from the music player. It could also be a single button in the UI, maybe "Ctrl+Click" on the Musicplayer once one has searched for whatever he wanted to listen to.

**Comment by peppy** [comment]
osu! is a game, not a music player. This is out of scope of the project.
