### ISSUE TITLE
Did the transfer of replays break?

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#7307]
1. After the last update, the transfer of maps and replays began to work with very strong errors. I attach the strangest in the video. 
https://youtu.be/AwdENeDCSZ8
I do not know how to repeat this bug. He didn’t appear anymore.

2. The lazer refuses to import the map if it is transferred in the OSZ format, if the map has already been downloaded (but one more difficulty was added, for example). However, if you re-enter the lazer, then there is no more error. I think this may be due to local difficulties.

Lazer 2019.1219.0

Logs (only for the second error):
[database.log](https://github.com/ppy/osu/files/3988368/database.log)
[network.log](https://github.com/ppy/osu/files/3988369/network.log)
[performance.log](https://github.com/ppy/osu/files/3988370/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3988371/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3988372/updater.log)

**Comment by bdach** [comment]
Please attach your `client.db` file for inspection.

When it comes to point 2., do you mean to say that you've taken a pre-existing online beatmap and locally added a difficulty that is nowhere to be found online?

**Comment by Moltanicaa** [comment]
https://drive.google.com/open?id=19eMtZgtwgX61nyGLPBqqFFfJFC22g5V8 - file client.db, I just don’t quite understand how to upload it here if it weighs 25 MB.

Concerning point 2 - you correctly understood everything. this did not cause any problems before, because I also added diff and that’s it.

**Comment by Moltanicaa** [comment]
In recent releases, this problem no longer exists, is it worth closing this problem?

**Comment by smoogipoo** [comment]
Seeing as this issue hasn't been touched in the last 7 months, I think it's ok to close it. We're looking at eventually replacing the existing DB engine.
