### ISSUE TITLE
Maina long hold note wired behaviour.

### ISSUE THREAD

**Issue by whatheword** [ppy/osu#7309]
Hold note count as miss at the end regardless you release early or late, it only happen to the long hold notes, but suddenly release and press back the hold note (red cross appears but no combo break)fix it.

redcross no break:
![ezgif-4-deba9ee83509](https://user-images.githubusercontent.com/58687370/71257601-14786d00-236f-11ea-8111-977ec0de4dbd.gif)

release at the end but_break:
![ezgif-4-c026985ee60f](https://user-images.githubusercontent.com/58687370/71258228-9c12ab80-2370-11ea-9016-790036d4fad5.gif)

**Comment by whatheword** [comment]
Here's a song for your reference btw
https://osu.ppy.sh/beatmapsets/361117#mania/1037392
4K Insane

**Comment by smoogipoo** [comment]
This was handled super dodgily. Regressed from keybinding container changes.
