### ISSUE TITLE
Legacy skins don’t support HitCircleOverlayAboveNumber

### ISSUE THREAD

**Issue by maotovisk** [ppy/osu#7312]
**Describe the new feature:** The HitCircleOverlayAboveNumber parameter in skins makes the hitcircleoverlay sprite be rendered over the default sprite (numbers). At theoretical levels it makes no difference at all, but gameplay-wise it makes a total difference, instead it being fading out with the Circle Sprite, the number should instantly disappear as it is hit.

**Proposal designs of the feature:** As it is in stable.

- HitCircleOverlayAboveNumber = 1: renders as it is rendered currently;

- HitCircleOverlayAboveNumber = 0: default sprite instantly disappear as it is hit;

**Comment by bdach** [comment]
Closing as resolved by #8502.

**Comment by EVAST9919** [comment]
As a side note: this property has nothing to do with the fade animation even in stable, it just changes the draw order of the sprites.
