### ISSUE TITLE
'Battery low' warning on Windows 10 breaks lazer

### ISSUE THREAD

**Issue by Luxiono** [ppy/osu#7314]
**Describe the bug:** 
Windows 10 opens a 'Your battery is low' warning when battery is around <10%. Unlike `stable` however, lazer doesn't let this warning overlay the game, making it impossible to do anything until the computer is charged.

Note: This only happens on W:10 computers.

**Screenshots or videos showing encountered issue:** 
I don't have this, but as long as you have a Windows 10 computer, do this:

1. Open up lazer at a lower battery, and be in the menus until your computer's cursor overlays the game's. This shows that the warning has appeared.
2. Click around and see if anything happens besides the noise that plays.
3. Plug the computer back in and this should be fixed.

**osu!lazer version:** 
2019.1219.0 (Windows 10)

**Logs:** 
None.

**Comment by peppy** [comment]
Is it a normal windows notification? Do other notifications have the same issue on your PC?

**Comment by Luxiono** [comment]
https://images.app.goo.gl/ywRpZmCTgpN2iKzDA it overlays everything as long as it's allowed. Oddly enough, when it's closed out, it remains as shown on the taskbar with a File Manager icon.

Since it's a system notification, it has more priority over others and is required to be in a 'shown' state, even if the user can't see it.

**Comment by Luxiono** [comment]
Other notifications have no problems whatsoever, mostly because the 'battery low' warning is the only system notification I get. Everything else is just not seen, but the battery warning tries to show, and can't, but still forces the game window out of focus, allowing nothing to be done until the computer is plugged in.

**Comment by Morilli** [comment]
Are you playing in fullscreen? If so, does this issue occur even when playing in windowed mode?

**Comment by Luxiono** [comment]
This only occurs in fullscreen mode.

**Comment by Morilli** [comment]
I have a feeling this could be connected to the issue of osu!lazer not using exclusive fullscreen.

**Comment by peppy** [comment]
I'd say it's more likely because it *is* exclusive,  to the opposite.

Would be interested to hear if other games break in the same way, since we're not doing anything special.

**Comment by Luxiono** [comment]
I'll edit this comment to add games that break this way, if any:
- osu!lazer

**Comment by peppy** [comment]
How about you test at least one other game and post a comment after you've tested.

**Comment by Luxiono** [comment]
From past use, the games Clone Hero and Electric Zine Maker don't break.

**Comment by peppy** [comment]
could you 100% confirm with a game running exclusive full screen and comment when you have? i will consider reopening the issue

**Comment by Luxiono** [comment]
While it seems I can't screenshot the screen when this appears, I can confirm that in-game on Clone Hero, when this notif. appears, it pauses the game, and does not break.
