### ISSUE TITLE
a mod where it shows bpm, sv and other timing point changes in gameplay

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#7315]
this mod will be difficulty reduction mod or a fun mod

how it would work is that there will be a spot(a line) where timing point values (displayed in a object that has a different shape depending on what change is it (bpm, sv, or some other thing like ar) with the value of what the timing point has in the object) using timing points will apporach that spot and when it touches the line, it shows the changed value it will be at that point

an example would be a square containing sv x1.6 that apporaches the line, when it touches the line, it would show that the sv would be x1.6 at that point in time

the speed that the objects apporach can be based on ar or bpm, sv, and scroll speed

**Comment by smoogipoo** [comment]
I think this can be classified under https://github.com/ppy/osu/issues/6683, and it shouldn't be a mod but something that is always visible or toggled at worst.
