### ISSUE TITLE
Allow background blur to affect StoryBoard&Video

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#7321]
As title said, allowbackground blur to affect StoryBoard&Video

![Video](https://user-images.githubusercontent.com/56265123/71316093-6fac7b80-24a5-11ea-95d7-52e6aa53022e.png)
![Storyboard](https://user-images.githubusercontent.com/56265123/71316094-6fac7b80-24a5-11ea-99ba-db72cd705206.png)

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/3631
