### ISSUE TITLE
All hits are missing.

### ISSUE THREAD

**Issue by uwucal** [ppy/osu#7323]
**Describe the bug:** 
Heya! I have been testing out lazar on mobile and PC. I have discovered on both platforms that when you hit a circle, it registers as a miss.
**Screenshots or videos showing encountered issue:** 
Cant OBS doesnt work.
**osu!lazer version:** 
2019.1219.0
**Logs:** 
Sorry, how do I get those?

**Comment by bdach** [comment]
Cannot reproduce on 2019.1219.0. Your report does not contain enough details to start diagnosing this issue, therefore I'm closing this until you provide more details.

Please double check your input devices, attach logs from either:
* `%AppData%/osu/logs` (on Windows),
* `Android/Data/sh.ppy.osulazer/logs` (on Android),
state what input devices you're using and provide a video if possible.
