### ISSUE TITLE
InvalidThreadForChildMutationException when dismissing notification

### ISSUE THREAD

**Issue by huoyaoyuan** [ppy/osu#7333]
_I'm not able to reproduce it. Maybe a race condition here._

**Describe the bug:** 
Steps I did in the session: 
1. Download a map via direct. Used https://osu.ppy.sh/beatmapsets/829511#osu/1737885
2. Download a replay and watch it. Used iMay's HardRock score. Did seek during the replay.
3. Open mods overlay and select HardRock. Forgot whether I've deselected it.
4. Dismiss the notification about map download completed, via dragging.

Unhandled exception: InvalidThreadForChildMutationException

**Screenshots or videos showing encountered issue:** 
N/A

**osu!lazer version:** 
Current master( https://github.com/ppy/osu/commit/5e8afccfee22674fa53d08bc9863c5feabd1cdea )

**Logs:** 
N/A. I've checked that overwritten by following sessions.

Partial call stack:
```
lambda for Current.ValueChanged registered in ModDisplay.ctor
called by ReplayPlayerLoader.CreateChildDependencies
```

It looks strange that `ReplayPlayerLoader` is called when dismissing notification.

**Comment by smoogipoo** [comment]
This is 100% replicable by importing and trying to view a replay from the Menu.
