### ISSUE TITLE
RulesetInfo ID parameter gets passed incorrectly

### ISSUE THREAD

**Issue by Altenhh** [ppy/osu#7335]
regressed from https://github.com/ppy/osu/pull/7256/

Even though from the database you can clearly see that it has a set id, it however does not get passed when creating the Ruleset. therefore `CreateConfig()` does not get called

![database](https://cdn.discordapp.com/attachments/188630652340404224/658855234562686982/unknown.png)
![createconfig()](https://cdn.discordapp.com/attachments/188630652340404224/658740745976545311/unknown.png)

Though when debugging from RulesetStore it shows that it _does_ have an id.
![rulesetstore](https://cdn.discordapp.com/attachments/188630652340404224/658860404642021376/unknown.png)

**osu!lazer version:** 2019.1219.0

**Comment by smoogipoo** [comment]
An `internal set;` on `RulesetInfo` is probably ok.
