### ISSUE TITLE
stacking bug

### ISSUE THREAD

**Issue by ScubDomino** [ppy/osu#7339]
stacks seem to switch around the positions of the objects rapidly to the point where it's almost impossible/very time consuming to stack simple objects without turning stacking off.

here's a video: https://twitter.com/ScubDominoes/status/1209356623006711808

i have no idea how to make issues lol
edit: i just realized this is lazer but i had no idea where i could have posted this anyways

**Comment by LanTenDragon** [comment]
Should be posted to https://github.com/ppy/osu-stable-issues

Although there is already a (closed?) issue tracking this https://github.com/ppy/osu-stable-issues/issues/279

Can be closed.
