### ISSUE TITLE
Beatmap Auto Generation

### ISSUE THREAD

**Issue by ejmejm** [ppy/osu#734]
Something I would be interested in working on would be auto-generating a beatmap from a song. If there is any interest in this, as a feature for the game, I would love to mock something up to see how well it might work.

This is just an idea, nothing I've tried yet. But now that there are so many good user-created beat maps, it might be possible to do some of the work using a neural network to train on current beatmaps. Again, just an idea right now, I would have to mock it up to see if it would work.

Does this sound like something that would be worth me looking into?

**Comment by peppy** [comment]
You're welcome to look into this, but I'm not sure where/if it would fit in the osu! ecosystem.

**Comment by Disinterpreter** [comment]
Probably it has the right to life.

**Comment by IOExceptionOsu** [comment]
Generating patterns might be easy, but determining rhythm from the song will probably be the hardest part of what you're trying to do. In particular, you'd probably have to find strong beats vs. weak beats, and adjust slider velocity accordingly. It'd also be hard to do mapping gimmicks unless you hard-code it into your program.

If you're looking to use your neural network training on current maps, you might want to look into first _remapping_ existing maps with the timing and rhythmical elements done, and then just generate the placement of the notes.

**Comment by peppy** [comment]
Closing this just to clean things up. This is still a welcome experimentation area for anyone interested.
