### ISSUE TITLE
Wrong difficulty

### ISSUE THREAD

**Issue by JoaoMancilla** [ppy/osu#7340]
**Describe the bug:** 
I tried to restart the game but it still goes on. It really isn't 7 star, it looks like a 2 star map and I didn't get any achievements.

**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/exl3Jkd.png

**osu! version:** 
Stable 20191223.6 (latest)

**Comment by HoLLy-HaCKeR** [comment]
https://github.com/ppy/osu-stable-issues/
