### ISSUE TITLE
Unable to send chat messages [Manjaro]

### ISSUE THREAD

**Issue by Mikasu-X14** [ppy/osu#7341]
**Describe the bug:** 
When I try to send a message with the integrated chat of the client, it fails to send the message all the time. I can login just fine though and osu!direct works too.
Just to give more infos, I run Manjaro and not Windows so it is extremely unlikely that it is a virus. It's also an almost fresh reformatting.
**Screenshots or videos showing encountered issue:** 
a test message before sending
![osu_2019-12-24_22-25-06](https://user-images.githubusercontent.com/40552956/71430886-6802f780-269c-11ea-978c-eb8e6770a521.png)
after sending the test message
![osu_2019-12-24_22-25-34](https://user-images.githubusercontent.com/40552956/71430888-6b967e80-269c-11ea-8706-df8f76f61fbe.png)

**osu!lazer version:** 
2019.1219.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3999493/database.log)
[network.log](https://github.com/ppy/osu/files/3999494/network.log)
[performance.log](https://github.com/ppy/osu/files/3999495/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3999496/runtime.log)

**Comment by peppy** [comment]
Did you create the account via lazer?

**Comment by Mikasu-X14** [comment]
I did but I made sure it was fine on the website afterwards

**Comment by Mikasu-X14** [comment]
I can chat via the osu! website but i can't in the client

**Comment by Mikasu-X14** [comment]
I should also point out that every attempts at sending a message via the client gives me an email for verification (which is already done) and the link in the email (even if it was only seconds ago) is always invalid

**Comment by peppy** [comment]
We're making an API fix for this. Please try again in a day or so!

**Comment by Mikasu-X14** [comment]
Alright, sure will!

**Comment by Mikasu-X14** [comment]
so is it on the server side or on the client side? not sure i understand very well
