### ISSUE TITLE
Beatmap stops playing as song starts

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7344]
The beatmap and music will stop playing ~~as the first note is hit~~ (see edit) as if the game froze. Every other aspect of the game remains fully responsive, though.
**EDIT:** After some investigation, it seems the map stops as the music is about to start playing. The file seems to play fine in the song carousel, though. (End of edit)
This seems to occur on some specific beatmaps and not others. It also doesn't _always_ happen. Game mode, difficulty, or mods don't matter. I didn't experience it on PC; only on mobile. (Nokia 7 Plus running Android One 9 Pie.)
https://streamable.com/pfhlp (Sorry for the audio quality, internal audio recording is only supported from Android 10 onward for some reason.)

[database.log](https://github.com/ppy/osu/files/4000353/database.log)
[network.log](https://github.com/ppy/osu/files/4000354/network.log)
[performance.log](https://github.com/ppy/osu/files/4000355/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4000356/runtime.log)

**Comment by smileyhead** [comment]
Here is a list of maps I've seen it happen with:
[Hoshi o Tadoreba - Yumeno Himiko](https://osu.ppy.sh/beatmapsets/584787#osu/1240804)
[Ink Me Up - OzzyOzrock](https://osu.ppy.sh/beatmapsets/368343#taiko/807618)
[Koyoi mofumofu!! (TV Size) - Rizen](https://osu.ppy.sh/beatmapsets/954691#osu/2003923)
[Now or Never - OzzyOzrock](https://osu.ppy.sh/beatmapsets/380864#taiko/833289)
[Wa -cycle- - Mirash](https://osu.ppy.sh/beatmapsets/815119#osu/1709556)

**Comment by Pizzabelly** [comment]
This happens to me too. It started after https://github.com/ppy/osu-framework/commit/68b13482d867c852ec74cbc1de2ff9bcd5a1e073. Changing the line https://github.com/ppy/osu-framework/blob/master/osu.Framework/Audio/Track/TrackBass.cs#L169 to `isRunning = running;` fixes it, but I'm not sure if that's the actual solution.

**Comment by bdach** [comment]
@Pizzabelly Which platform are you seeing this on, and which version? Maybe this is #6355 again?

**Comment by Pizzabelly** [comment]
@bdach Android 10, with the latest version of osu.

**Comment by bdach** [comment]
Latest as in latest release (2020.226.0), or are you building from `master`?

**Comment by Pizzabelly** [comment]
osu built from `master` and the latest osu-framework release.

**Comment by bdach** [comment]
From my initial investigation it would seem that the claim that [stalled tracks automatically resume](https://www.un4seen.com/doc/#bass/BASS_ChannelIsActive.html) is false at least on Android.

* Current code upon transition into `Player`:
  * `Track.Reset()` calls stop; channel state: `Playing` -> `Paused`
  * `DecoupleableInterpolatingFrameClock.Seek()` calls

**Comment by peppy** [comment]
On PC this also shows up as a brief pause during track start. I'm going to look into this one (at least fixing the PC side of things).

**Comment by peppy** [comment]
@bdach thanks for the above investigation. made it very easy to understand the cause within seconds (just knowing we were hitting the `STALL` scenario).

**Comment by VB304** [comment]
Is there no plan on fixing this? it's still present in Android

**Comment by peppy** [comment]
Please open a new issue describing what you're seeing, with video and logs.
