### ISSUE TITLE
An "override" option for Difficulty Adjust mod 

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#7345]
**Describe the new feature:** 
Currently, the mod updates all it's parameters every time the beatmap changes, but I could see this being a problem for people that want to practice, for example.. AR8 only. They would have to change the AR slider every time they change the map. This could be implemented by having an "override" checkbox in the Customizations tab. 
Let me know if this is not the direction the project is heading towards, and I'll close this.

**Comment by LeNitrous** [comment]
The difficulty settings default to the map's settings.

**Comment by stanriders** [comment]
"Lock slider" option would be useful though

**Comment by peppy** [comment]
I can see the need for this. A bit of thinking will need to be done on how to best show this in the UI area with minimal custom logic.

**Comment by EVAST9919** [comment]
Imo it should be handled by default rather than having addition checkbox
