### ISSUE TITLE
Extra lives for the "Difficulty Adjustment"

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#7346]
I suggest adding support for extra lives for the "Difficulty Adjustment".

Because if this mod is made exclusively for practice and is not compatible with the Easy-mod, then this combination looks just the way. Although I understand that the mod is combined with the nofail, but it seems to me that lives will not be superfluous.

**Comment by peppy** [comment]
No fail is your best option here. We don't want to overload on settings.
