### ISSUE TITLE
"Difficulty Adjust" mod doesn't update any values

### ISSUE THREAD

**Issue by SigmaTheFox** [ppy/osu#7348]
**Describe the bug:** 
When enabling the "Difficulty Adjust" mod, instead of showing the current map's values and updating on map change, all sliders stay in the middle.
When actually trying to change values, the map won't use them and reset them to the beatmap's original values (the sliders won't be in the middle anymore).
Sadly these are the only information I was able to gather.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/CMYM8KH90Ac

**osu!lazer version:** 
2019.1225.0

**Logs:** 
It seems to give me errors when trying to attach the files directly so I uploaded them on pastebin
[database.log](https://pastebin.com/8TfuNw1F)
[network.log](https://pastebin.com/pXkPVRkh)
[performance.log](https://pastebin.com/Uv4EFdiB)
[runtime.log](https://pastebin.com/J8UmXEtM)
[updater.log](https://pastebin.com/fKbyXnt5)

**Comment by Gabixel** [comment]
It seems to work only when the `Details` tab is open. Please check if it works for you too

**Comment by timrowland-wq** [comment]
This is occurring because you are switching maps after changing the settings. The difficult override mod does not permanently change a maps settings. Try adjusting the settings and then not shifting to a different map after doing so and it should work.

**Comment by SigmaTheFox** [comment]
> It seems to work only when the `Details` tab is open. Please check if it works for you too
> ![Details tab](https://user-images.githubusercontent.com/43073074/71448779-f6c95000-2740-11ea-817c-b5dffe178e86.png)

yeah that seems to work

> This is occurring because you are switching maps after changing the settings. The difficult override mod does not permanently change a maps settings. Try adjusting the settings and then not shifting to a different map after doing so and it should work.
> 
> EDIT: I think i misunderstood the issue here. For me the mod only works when the beatmap that is selected when applying the mod is played. When trying to play a different beatmap afterwards the effects of the mod no longer take place - which i believe is the issue.

according to the video peppy tweeted, it should update the sliders with whatever value the new beatmap has, and changing without switching map doesn't fix it
