### ISSUE TITLE
osu!lazer fails to install and closes with completely blank squirrelsetup logs

### ISSUE THREAD

**Issue by throwawaosu** [ppy/osu#7355]
basically here for tech support since i'm computer illiterate. this has happened for the last few updates.

when i try to open the osu lazer installer the image below happens. this happens regardless of the name of the file
![1 installation has failed](https://user-images.githubusercontent.com/59243554/71459244-c9da6480-2763-11ea-98d5-9c3669b4d742.PNG)

squirrel setup logs are blank 
![2 squirrel](https://user-images.githubusercontent.com/59243554/71459345-40776200-2764-11ea-8040-216a52d65955.PNG)

here's the important stuff from event viewer

![3 event](https://user-images.githubusercontent.com/59243554/71459416-9a782780-2764-11ea-8de0-a450c9219b03.PNG)

![3 event 1](https://user-images.githubusercontent.com/59243554/71459414-9946fa80-2764-11ea-941d-3116d30e00e3.PNG)

**Comment by bdach** [comment]
I couldn't find any Squirrel-side issue that matches these symptoms.

Out of curiosity, what is your Windows build version and installed .NET Framework version?

**Comment by mcendu** [comment]
> I couldn't find any Squirrel-side issue that matches these symptoms.
> 
> Out of curiosity, what is your Windows build version and installed .NET Framework version?

Looks like .NET Framework 4.0.x and Windows 10.

**Comment by throwawaosu** [comment]
yea, the event viewer says framework 4.0.30319 and my specific build is windows 10 version 1903 (os build 18362.239)

**Comment by bdach** [comment]
4.0.30319 might be a misleading number since [I'm thinking it might be obscuring the actual .NET Framework version I'm looking for here](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#use-the-environment-class), since the fourth version segment (build number?) isn't there. Anyway, I'd suggest trying to update to the latest version and trying to install again.

**Comment by throwawaosu** [comment]
.net installer says i already have 4.8.
 should i try uninstalling and reinstalling .net framework?

**Comment by bdach** [comment]
> should i try uninstalling and reinstalling .net framework?

I'm skeptical if this will have much effect, but I'd probably try, seeing that if that doesn't help we might need help from squirrel devs. I checked upstream, no significant changes to our fork near the crash call site at `AnimatedWindow`.

**Comment by peppy** [comment]
Squirrel is largely not maintained, we run our own fork. That said, the issue above looks like it might be something deeper with the .net install. unless we get more than one report i'd argue it's not something we should be fixing at our end.

**Comment by throwawaosu** [comment]
i can't even uninstall .net because of an error related to windows update, this is 99% a problem on my end
