### ISSUE TITLE
Change speed of cursor rotation

### ISSUE THREAD

**Issue by battleof3** [ppy/osu#7356]
Proposing a variable for skin.ini to change animation frames of cursor rotation. Currently, the rotation is slow and uninteresting for visual affect in my opinion.

**Comment by l3lackShark** [comment]
skin.ini is a legacy format and will probably not going to be used in Lazer as a base. Instead, the game will have its inbuilt skin editor. However, It's still too early to talk about its features. Please wait for the proper implementation of the editor, and then, if the setting that you want is not going to be in the game by that time, please open an issue.

**Comment by battleof3** [comment]
Got it. thanks for the information!

**Comment by Paladynee** [comment]
is this still planned?
