### ISSUE TITLE
Mod select overlay overflows at max ui scale

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#7369]
Just want to make sure this is right. First, we can make it relative size (not 100% though). We can then share the resize implementation in `ChatOverlay`, so portrait players won't be stuck with the higher height.

**Screenshots or videos showing encountered issue:** 
![osu_2019-12-26_16-55-20](https://user-images.githubusercontent.com/35318437/71495040-87b33080-2800-11ea-884d-81d4dc06957a.jpg)

**Comment by peppy** [comment]
This is an interesting one, since I'm not sure we want it to be relative height in the final implementation. But I think making it relative will be a UX improvement short-term, so that's fine to do.

**Comment by Joehuu** [comment]
Regressed in https://github.com/ppy/osu/pull/12852.

![osu_2021-05-25_09-02-07](https://user-images.githubusercontent.com/35318437/119530479-e5baaf00-bd37-11eb-9b48-f3283adc2342.png)

---

First step is to revert. As for fixing the mod select height in multi/playlists, we can reuse the ugly grid container workaround in song select, but I think we should implement a `MaxHeight` property instead.

**Comment by Joehuu** [comment]
Closing as same reason as https://github.com/ppy/osu/issues/17501.
