### ISSUE TITLE
HP drains passively in mania

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7370]
**Describe the bug:** See title. In stable, HP does not drain passively. Looks like a good first issue.

**osu!lazer version:** Since commit 750b0746cdab35f89df274ddb14babf167d1d784

**Comment by aspriddell** [comment]
The HP bar in mania (in stable) **does** go down when you miss a note. Do you mean the rate is inconsistent?

**Comment by mcendu** [comment]
What I mean is that HP does not seems to naturally go down.

**Comment by aspriddell** [comment]
Have you watched an automated play? I have and it doesn't drain on stable

**Comment by mcendu** [comment]
Watched. No drain in stable but drains in lazer master.

**Comment by aspriddell** [comment]
Ok, I get it now. I was using a release copy, so the edit was made since the last release. I've looked and it was added in the last hour, so it'll probably be fixed soon

**Comment by aspriddell** [comment]
Had a go at [fixing it here](https://github.com/aspriddell/osu/tree/fix-mania-drain), which I believe does work but is not PR ready. I'll have another look later in more depth

**Comment by smoogipoo** [comment]
This is intentional for now, I'm not interested in 100% replicating stable behaviour here until there's a consensus that it's undesired.
I'd like to play around with it a little bit more especially after the game is in a more mature state, before removing it.

**Comment by peppy** [comment]
Let's change HP drain to be passive. It's clear that the community doesn't want change and wants to play things exactly as history has engrained in their minds, so let's match that to make the game playable for the majority.

**Comment by Walavouchey** [comment]
resolved with https://github.com/ppy/osu/pull/22129
