### ISSUE TITLE
Add bounce animation to reverse arrow

### ISSUE THREAD

**Issue by wojexe** [ppy/osu#7374]
Reverse arrow is bouncing to the beat in the stable version, so I think it should be doing so in osu!lazer as well. Maybe add an settings toggle to deal with this?
Personally I am used to seeing the reverse arrow bouncing and the animation makes maps a little easier to read for me.

**Comment by bdach** [comment]
This was actually reported before at #5980, but for some reason since the reporter had deleted their GitHub account the issue seems to just straight up disappear from search results, so I'm going to close that one and leave this open.
