### ISSUE TITLE
osu!lazer freezes on certain songs when a break time starts on iOS 13.1

### ISSUE THREAD

**Issue by xTerraUWU** [ppy/osu#7375]
For the time I’ve been testing osu!lazer all seemed to work well besides some freezes and crashes. A thing I saw happen frequently was freezing whenever a breaktime starts. 
![A8FC2189-E3E9-4868-8F90-63B3F08F0AF9](https://user-images.githubusercontent.com/58949994/71521826-ef608e80-2887-11ea-8c60-77a3e5af66f2.png)

I don’t know if this issue has been cleared up already but I’m still here trying to help out. I’m willing to try and figure out what’s causing it to do so.

**Comment by xTerraUWU** [comment]
I’m also fairly new to GitHub so my apologies if I do something wrong

**Comment by bdach** [comment]
Issues with freezing on iOS are already known (see #6355), although it's interesting that you state that it has to do with break time starting. I'm going to tentatively close as duplicate and ask in the original issue if that's what the other users are experiencing.
