### ISSUE TITLE
Difficulty adjust mod should allow AR to be set up to 11

### ISSUE THREAD

**Issue by Waidxd** [ppy/osu#7378]
I think the mod should allow up to AR 11 at the very least since this is actually an achievable AR by applying DT to AR 10.

Also I can see many players who would want to practice AR 10.3 on certain maps where it would other wise be much higher (10.4-11).

**Comment by LeNitrous** [comment]
Should all settings be allowed to be set up to 11 for consistency then?

**Comment by genericthing** [comment]
i think so because 
people can train on OD11 to be more accurate, 
HP11 would still be doable (because HP drain will not kill you if you're really consistent.)
CS11 would be interesting to see

(also for some reason you can't set any setting to 0)

**Comment by peppy** [comment]
for now we will be leaving the adjust mod as one which only exposes settings mappers can access. we can potentially add a new mod or an "extreme" setting for going beyond this, but it should not be exposed by default via difficulty adjust sliders.
