### ISSUE TITLE
Add support for updating stats on profile

### ISSUE THREAD

**Issue by RyouNagumo** [ppy/osu#7379]
Osu Lazer is refusing to update my stats on my mac, I remain at level 1, nothing updates and it remains a blank slate before it said I havent been online for 3 months straight (the creation date) i only now check it because i play casually. Relogging fixed this issue but it still remains a blank slate
![Screen Shot 2019-12-27 at 7 43 15 PM](https://user-images.githubusercontent.com/59298142/71536794-4b0b3600-28e1-11ea-905b-6b00d21ccdcd.png)
_last seen 17 minutes ago when im currently on now with online status_

**Comment by peppy** [comment]
Stat updating isn't quite ready yet. I'd say we're 1-3 months having a solution to this.

**Comment by huoyaoyuan** [comment]
Note that lazer(project lives in this code base) hasn't enable score submission. The server has never recieved any score from you, so it displays "never played" and level 1.
To achieve scores admitted by the server, you must use the stable client now.

**Comment by Joehuu** [comment]
Closing as basic stat updating has since been implemented.
