### ISSUE TITLE
Order/Naming of Difficulty Adjust settings are different from beatmap details

### ISSUE THREAD

**Issue by Antaruv** [ppy/osu#7387]
**Describe the bug:** 
The order of the settings and the names of the settings are different between the beatmap details listed in song select and the settings panel for Difficulty Adjust. This can cause some confusion when looking between the settings and the beatmap details.

**Screenshots or videos showing encountered issue:** 
Details in song select:
![image](https://user-images.githubusercontent.com/19866321/71550551-8f76fe80-29d3-11ea-8377-4cb192eae8e8.png)
Difficulty Adjust settings:
![image](https://user-images.githubusercontent.com/19866321/71550553-97cf3980-29d3-11ea-8610-1499d8d7b346.png)

**osu!lazer version:** 
2019.1227.0

**Logs:** 
Not applicable.

**Comment by peppy** [comment]
for now just changing file order to resolve this should be fine.

**Comment by huoyaoyuan** [comment]
I suggest to follow the order showing at header in stable. It should be CS, AR, OD, HP?

**Comment by peppy** [comment]
follow the web order. if the order is to change a change should be proposed against osu-web.

**Comment by Antaruv** [comment]
Looking into it, the exact cause of it is the fact that the order is decided by `GetProperties()`, which in this case is ordering it by `Implementation` -> `Abstract`. As a result, for the case of osu!, both Circle Size and Approach Rate (osu!-specific) are forced to appear above HP Drain and Accuracy (in the abstract class for the mod). This means that just changing the order of the attributes in the files cannot achieve the order from osu-web, and a more robust solution is likely required.

**Comment by ICantDrive** [comment]
for song select, the attribute order can just be changed in `osu.Game.Screens.Select.Details.AdvancedStats`. As for the difficulty adjust mod, by adding Drain Rate and Overall Difficulty to `OsuModDifficultyAdjust`, hiding the inherited members, it's possible to also just change the order there. This probably isn't an great solution though, as the same attributes will be in multiple files, but it works.

![image](https://user-images.githubusercontent.com/35839101/71605528-c252fb00-2b69-11ea-9fa1-912c47f12769.png)
