### ISSUE TITLE
Sorting by friend rank in Social browser is broken

### ISSUE THREAD

**Issue by vruss** [ppy/osu#7391]
**Describe the bug:** 
When sorting by rank in the friends tab, it's still sorting by Alphabet

**Screenshots or videos showing encountered issue:** 
![Screenshot](https://i.imgur.com/enI7fPy.png)

**osu!lazer version:** 
Local debug - current master branch

**Logs:**

**Comment by vruss** [comment]
As pointed out by Evast in discord:

> For now you can't. friends endpoint returns users without statistics

Does this mean an update to the ```friends``` endpoint is necessary if I wanted to sort by ```statistics.ranks.global```

**Comment by EVAST9919** [comment]
It's okay to leave this issue open, but not because it's "broken", but because it's not implemented yet.
