### ISSUE TITLE
Standard legacy skin circle fade-in behavior doesn't match stable

### ISSUE THREAD

**Issue by Royce551** [ppy/osu#7392]
**Describe the bug:** 
In stable, circles fade-in at partial brightness, and then fade-in again to full brightness just before you click them.
**Screenshots or videos showing encountered issue:** 
Hopefully these 2 videos of the same map with a low AR illustrate my point, but if they don't, I can make an edited video.
[Lazer](https://streamable.com/f0jd6)
[Stable](https://streamable.com/jgwul)
**osu!lazer version:** 
2019.1227.0
**Logs:** 
Doesn't apply

**Comment by peppy** [comment]
This is part of the "note lock" display, not related to fade in as such. It shows which hitobject is currently hittable.

I agree we should probably bring it back for the miss region at very least (ie. it should undim when a miss is possible).

**Comment by Royce551** [comment]
Appears to be fixed in #20572

**Comment by peppy** [comment]
Thanks for following up after all these years 😅 . Didn't realise this was tracked.
