### ISSUE TITLE
Allow scrolling beatmap listing with pageup/pagedown along with home/end

### ISSUE THREAD

**Issue by DCNick3** [ppy/osu#7395]
**Describe the new feature:** 

Handle pageup/pagedown and home/end keys in beatmap listing allowing for more efficient keyboard usage.

**Comment by peppy** [comment]
May want to consider adding this to the framework side `ScrollContainer`.

**Comment by Joehuu** [comment]
It's already added. The problem is that textboxes are blocking the input. That's why I'm leaning towards a local fix, might need to add a bool in framework though.

**Comment by peppy** [comment]
Aha, I see! Probably just a local fix for search textboxes, since they shouldn't be handling those actions.
