### ISSUE TITLE
Auto misses on taiko maps that have been converted from standard

### ISSUE THREAD

**Issue by yeSpud** [ppy/osu#7397]
**Describe the bug:** 
Auto will miss on beatmaps that have been converted from standard to taiko.

(map used to test was [Celestial Horizon - Extra](https://osu.ppy.sh/beatmapsets/751846#osu/1582771))

**Screenshots or videos showing encountered issue:** 
Video had to be stored in a zip due to size
[taiko.mp4.zip](https://github.com/ppy/osu/files/4009076/taiko.mp4.zip)

**osu!lazer version:** 
2019.1227.0

**Comment by mouzedrift** [comment]
probably a duplicate of #5677

**Comment by yeSpud** [comment]
I did see that issue, but from what I could tell that issue corresponds to taiko beat maps, whereas this is converted beat maps. 


Not to mention I don't think it has to do with the 1/8 speed limit :p

**Comment by smoogipoo** [comment]
Same as the mentioned issue.
