### ISSUE TITLE
LegacySkinDecoder does not support [Mania] sections

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7401]
Effort don't seem to be trivial due to section data being specified across lines (1 line for common data and 2 lines for keycount-specifics):
```
[Mania]
// Common section

[Mania]
Keys: 4
// 4K section

[Mania]
Keys: 7
// 7K section
```

**Proposed design:** Lookup of keycount-specific settings still call `GetConfig<TLookup, TValue>()`.

**Comment by peppy** [comment]
Documentation: https://osu.ppy.sh/help/wiki/Skinning/skin.ini#%5Bmania%5D

**Comment by smoogipoo** [comment]
Keep in mind that the `Keys` attribute can occur at any point within each `[Mania]` section. It's unnecessarily complex, unfortunately...

**Comment by huoyaoyuan** [comment]
Sections can be treated list-like, instead of dictionary-like.
`sections.SingleOrDefault(s => s.Name == "Mania" && s["Keys"] == "4")`

**Comment by mcendu** [comment]
I think that the main problem is in how to retrieve it i.e. how can `ManiaLegacySkinTransformer` know the keycount so that it can retrieve the correct value.

**Comment by smoogipoo** [comment]
That’s not the job of the transformer to know. The transformer must receive in a skin that is already in the appropriate key-variant.

It’s gonna need implementation that doesn’t already exist. @peppy and I will discuss this soon.
