### ISSUE TITLE
Cannot launch with local checkout of osu-framework

### ISSUE THREAD

**Issue by d-v** [ppy/osu#7404]
Also posted this in osu-framework issues, I apologize about the duplicate, just wasn't sure if this is more of an osu-framework or osu!lazer issue
**Describe the bug:** 
Attempting to launch with a local fork of osu-framework in the hopes of figuring out why BASS isn't detecting sound devices. However, I cannot launch osu!lazer with a fresh fork of osu-framework having followed [these directions](https://github.com/ppy/osu-framework/wiki/Testing-local-framework-checkout-with-other-projects) in VSCode.
**Screenshots or videos showing encountered issue:** 
Can't really provide screenshots of something not launching, hope the build output is helpful.
**osu!lazer version:** 
v2019.1227.0
**Logs:** 
[Framework build output](https://github.com/ppy/osu/files/4010608/framework_build_output.txt)
[Osu!lazer build output](https://github.com/ppy/osu/files/4010609/lazer_build_output.txt)
[Osu!lazer debug output](https://github.com/ppy/osu/files/4010610/vs_code_debut_output.txt)

**Comment by bdach** [comment]
No reason to open this in both places. Closing this one, will transfer if deemed necessary.
