### ISSUE TITLE
Lazer won't start because I changed names on the skin folders

### ISSUE THREAD

**Issue by sorslars42** [ppy/osu#7406]
**Describe the bug:**
 Title, I'm not 100% sure if it's this but the game worked before I changed names. When I go to open lazer it shows a black screen for like 2s and the quits

**osu!lazer version:** 
Version is 2019.1227.0

**Logs:**
Don't have any coz I tried re-installing lazer but it didn't help

**Comment by bdach** [comment]
I'm confused, what do you mean, you "changed names on the skin folders"? Do you mean the `%AppData%/osu/files` folder (or its analogue on other OSes)? If so, please change it back, custom folder layouts are not supported and I'm not sure they'll ever be. Custom installation locations might come at a later date (see #5121).

In case this is not what you've done, please attach logs even after the re-install and your `client.db` file.

**Comment by sorslars42** [comment]
I mean I changed the names of the skins inside the skin folder
![45675675755](https://user-images.githubusercontent.com/59373583/71598778-ea823000-2b50-11ea-8367-a298c1c4acf1.png)

**Comment by bdach** [comment]
I'm pretty sure lazer doesn't _have_ a skin folder and you're confusing it with stable. Please proceed by attaching the logs as requested above.

**Comment by sorslars42** [comment]
Where can I find the logs?

**Comment by bdach** [comment]
The root path for the lazer install is `%AppData%/osu`. It contains (among other things) the `client.db` file and the `logs` directory. Please attach all the files here (the db might get too big to attach here so you might have to end up using offsite hosting).

**Comment by sorslars42** [comment]
[logs&clientdb.zip](https://github.com/ppy/osu/files/4010905/logs.clientdb.zip)

**Comment by bdach** [comment]
Looks like my hunch that it's DB-related was correct:

```
2019-12-30 20:17:55: ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
2019-12-30 20:17:55: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
2019-12-30 20:17:55: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
2019-12-30 20:17:55: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
2019-12-30 20:17:55: at System.Data.Common.DbCommand.ExecuteReader()
```

As a stop-gap fix you can move away/delete your `client.db` file and reimport everything from stable, should solve the problem. The underlying problem itself would usually warrant further analysis, but taking #7057 into account I'll hold off on it since it might go away once the migration to realm is complete.

**Comment by sorslars42** [comment]
Removing client.db fixed the issue, thank you!

**Comment by peppy** [comment]
Keeping this open to investigate further.

**Comment by sorslars42** [comment]
maybe needs some thing that when lazer doesn't find the skin last used it goes to the default skin like in stable

**Comment by peppy** [comment]
Going to close this one for now. Looks like the database got in a bad state, likely due to lack of correct transaction handling. As we are likely going to migrate away from ef-core, we're just going to let this one be for now.
