### ISSUE TITLE
Rewinding in autoplay w/slider does not automatically jump

### ISSUE THREAD

**Issue by Luxiono** [ppy/osu#7408]
**Describe the bug:** 
When clicking on the slider in autoplays to change time, the game is just played really fast, trying to jump back to that spot, resulting in lots of unnecessary hits.

**Screenshots or videos showing encountered issue:** 
https://gifyu.com/image/mILz
Was converted to GIF, so quality is very low..

**osu!lazer version:** 
2019.1227.0 on Windows 10

**Logs:** 
*None.*

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/5119
