### ISSUE TITLE
Lazer won't open on Windows 7

### ISSUE THREAD

**Issue by maia011** [ppy/osu#7410]
**Describe the crash:** 
nothing happens upon clicking the osu!.exe file, I have tried deleting the osulazer folder in AppData/Local and reinstalling the game about 3 times and it still doesn't work. Looking into the task manager I can see that the osu!.exe process pops up for a split second only to go away instantly.
**osu!lazer version:** 
2019.1227.0
**Computer Specifications:** 
Windows 7 Ultimate SP1, AMD E-450 with 4 GB ram and Radeon HD 6320 graphics.

**Comment by l3lackShark** [comment]
Is your system 32 or 64bit? Lazer only supports 64 at the moment.

**Comment by maia011** [comment]
> Is your system 32 or 64bit? Lazer only supports 64 at the moment.

Sorry, I forgot to specify. I'm on a 64 bit system.

**Comment by Stedoss** [comment]
Make sure you have the [additional prerequisites](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windowsl) required for dotnet on Windows 7 (as shown in the Requirements section of the readme).

**Comment by maia011** [comment]
> Make sure you have the [additional prerequisites](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windowsl) required for dotnet on Windows 7 (as shown in the Requirements section of the readme).

well it seems that I was missing an update + the .net core 3,1 sdk. I can open lazer now, thanks a lot!
