### ISSUE TITLE
osu!lazer right click doesn't work in osu!

### ISSUE THREAD

**Issue by unmellow** [ppy/osu#7411]
**Describe the bug:** 
whatever i bind the osu! right button too will stop working at some point in the middle of any song i do

**Screenshots or videos showing encountered issue:** 
i don't have a keyboard camera so idk how to demonstrat this

**osu!lazer version:** 
i found this in version 2019.930.0-1
and version 2019.1205.0_15_g52a0d9801-1 compiled from source

**Logs:** 
it didn't crash so not sure what to send

**Comment by bdach** [comment]
Mind capturing a video of this with the ingame key overlay on and maybe an external program that can capture and display keyboard presses, so that we know it's not an OS/hardware issue? (I'm partial to [nohboard](https://github.com/ThoNohT/NohBoard) myself)

**Comment by unmellow** [comment]
> Mind capturing a video of this with the ingame key overlay on and maybe an external program that can capture and display keyboard presses, so that we know it's not an OS/hardware issue? (I'm partial to [nohboard](https://github.com/ThoNohT/NohBoard) myself)

nohboard doesn't have a native linux version i'll try it with wine though

**Comment by unmellow** [comment]
nohboard is just blue and when i search for a keyboard visualizer for linux the only thing i see is something to change my keyboard rgb based on audio

**Comment by unmellow** [comment]
this https://github.com/CalcProgrammer1/KeyboardVisualizer

**Comment by unmellow** [comment]
also i use manjaro linux i should have mentioned that

**Comment by unmellow** [comment]
i'm using a drawing pad and forgot to set "disable mouse wheel during gameplay" to true closing

**Comment by unmellow** [comment]
here's the video though https://drive.google.com/file/d/191ZhhCwU3OS38Fss7A2aakT9WsJ0UTew/view?usp=sharing
