### ISSUE TITLE
Uncaught exception occurred when showing update log

### ISSUE THREAD

**Issue by dtsdao** [ppy/osu#7416]
**Describe the bug:** 
An uncaught exception occurred when showing the update log. This shouldn't be an unknown error.
On mobile, this causes a crash.

**Reproduce:**
Go offline -> Settings -> Debug -> (Version Code)

**Screenshots or videos showing encountered issue:** 

![osu](https://user-images.githubusercontent.com/15965311/71641694-14675e00-2cdb-11ea-9c36-013c4d4d25aa.png)

**osu!lazer version:** 2019.1227.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/4014077/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4014078/updater.log)
[network.log](https://github.com/ppy/osu/files/4014079/network.log)
[performance.log](https://github.com/ppy/osu/files/4014080/performance.log)

**Comment by bdach** [comment]
Logs show an unhandled nullref; should be straightforward to prevent the error by guarding. Question remains if we want to also add a placeholder message indicating the user is indeed offline as to not leave an empty screen.
