### ISSUE TITLE
Add a button to reset Customisation settings

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#7429]
**Describe the bug:** 
-
Add a new button to reset Customisation settings

**Screenshots or videos showing encountered issue:** 
-
![MOD](https://user-images.githubusercontent.com/56265123/71713194-a2f6ef00-2e43-11ea-8edb-5b0351440643.png)

**osu!lazer version:** 
-
Lazer 2019.1227.0

**Logs:** 
-
Seems not required

**Comment by mcendu** [comment]
Do you mean resetting all at once or resetting individual options?
For individual options, clicking the yellow bar on the left does the trick.

**Comment by smoogipoo** [comment]
Clicking the yellow bar to the left is the intended way of doing this.
