### ISSUE TITLE
osu!taiko finisher shows up too late

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#7436]
**Screenshots or videos showing encountered issue:** 
https://streamable.com/z45h5

**Beatmap:** 
https://osu.ppy.sh/beatmapsets/1003952#taiko/2101202 (last diff)

**osu!lazer version:** 
latest build on linux (self compiled)

**Comment by bdach** [comment]
Most likely going to have to do with #7367. I'll investigate whenever I get the chance.

**Comment by bdach** [comment]
Can confirm that this seems to have regressed with #7367, although worryingly enough this only shows up on certain resolutions (widescreen ones are usually fine, it's the narrower ones that cause problems). I'm have a bad feeling this might have to do with scaling containers.

**Comment by bdach** [comment]
As an update: I think I have a pretty decent idea of why this arises - #7367 wasn't fully correct for overlapping scroll. The fix will most likely have to do with what this comment mentions:

https://github.com/ppy/osu/blob/0804d8d7a45be9ba20618f2a6cfd3a6166df5d2f/osu.Game/Rulesets/UI/Scrolling/Algorithms/OverlappingScrollAlgorithm.cs#L42-L44

In the case of a negative position we want the *earliest* control point to be able to properly offset for origin.
