### ISSUE TITLE
Importing Beatmaps From External Drive

### ISSUE THREAD

**Issue by AnimeDasher** [ppy/osu#7439]
I Have Osu Stable on a external SSD and Osu Lazar cannot find my Osu Stable Beatmaps or skins, making it an inconvenience to switch to Osu Lazar at this point in time.

**Comment by recapitalverb** [comment]
Use a symlink

**Comment by jai-x** [comment]
Duplicate of https://github.com/ppy/osu/issues/3763 I think

**Comment by AnimeDasher** [comment]
now the game won't even open -_- , i will check taht post and see if it works, if it does not work i will keep this open
