### ISSUE TITLE
Osu Lazar shows a black screen then crashes

### ISSUE THREAD

**Issue by AnimeDasher** [ppy/osu#7440]
Osu Lazar was working fine until I tried to open it for the 2nd time on my computer and the screen went black as it tried to load and then it closed and put me on the desktop.

**Comment by jai-x** [comment]
Please attach logs and system information as specified in the issue template.

**Comment by AnimeDasher** [comment]
I am gonna write here on how i fixed it, i went to the osu directory in appdata/local and deleted it and now it boots lazar in windowed mode, so your settings will be gone but it will boot.
