### ISSUE TITLE
Classic Score Overlay

### ISSUE THREAD

**Issue by RyanLaFauci** [ppy/osu#7446]
Apologies if this already exists in the game options somewhere.

**Describe the new feature:** 
User would be able to enable classic score overlay, so that accuracy appears in the top-right and the combo in the bottom left. Also would bring back the classic break screen.
**Proposal designs of the feature:** 
See above.

**Comment by iiSaLMaN** [comment]
Duplicate of https://github.com/ppy/osu/issues/4632
