### ISSUE TITLE
Performance problems on some macOS PCs

### ISSUE THREAD

**Issue by petak5** [ppy/osu#7447]
**Describe the bug:** 
Framerate drops frequently, on all options except 60FPS with VSync - framerate is the most stable with this option while setting it to 8x or Unlimited results in the worst frame rates and response times. While recording it couldn't even get to 120fps, but when not recording I can get 150-200fps.
On the other hand osu!stable runs smoothly with "Optimal" setting, 480fps all the time.

I am running it on MacBook Pro 13" 2018, four thunderbolt 3 ports with 8GB RAM, using external display with native resolution of 1920x1080px (laptop's display is not used, though the issue was present when I tested it on the display alone too). I is running fresh install of macOS 10.14.6 (Mojave).

**Screenshots or videos showing encountered issue:** 
https://youtu.be/GZ_9uv_R07s
https://youtu.be/PdzdWu-mnaM - performance logs were created while I recorded this video

**osu!lazer version:** 
osu 2020.104.0.0

**Logs:** 
https://drive.google.com/file/d/1s4an-vG6x5tufFckuS4QFmYcPvSSdKep/view?usp=sharing

**Comment by GSculerlor** [comment]
Similar with #6576

**Comment by Wieku** [comment]
How the cpu/gpu temperature curves look then? For me it looks like the system is throttling because you try to put too much work on gpu. Remember that lazer is more effect packed, so there's no guarantee that it will perform the same as osu!stable.

**Comment by petak5** [comment]
I recorded the gameplay with performance monitors: https://youtu.be/J4r16x1ABxM
Neither CPU nor GPU is topping out, temperatures are low. Although I have noticed that the GPU usage is capped at a certain points while in a game (while playing a map), every frame sync setting results in a different level of GPU usage.

**Comment by petak5** [comment]
Here is my small test:
I have changed frame sync drawLimiter in the osu-framework to match the values of VSync option (update = 240FPS and draw = 60FPS). The option with VSync ON has stable FPS while the other one does not: https://youtu.be/1ZaB8BkpeRE

**Comment by peppy** [comment]
Known issue. Haven’t really looked into why it happens yet, but only does in some hardware (newer it would seem).

Use vsync for now.

**Comment by petak5** [comment]
I'm fairly new to the codebase and don't know how exactly VSync is implemented but a quick search led me to a part of code that gets executed when VSync is enabled (`GL.Finish();` in `osu.Framework/Platform/GameHost.cs` on line ~378). When I changed the code so that that part gets executed no matter if VSync is ON or OFF (theoretically enabling VSync for all Frame Sync options) I got great performance improvement, I could say it completely eliminated FPS instability on my machine. Here is a video demonstrating my story (note that I am also recording the screen and it runs this well!) https://youtu.be/Wuf_I5_K06g

UI toggle for VSync would be really useful for people experiencing this kind of issue.

How VSync works in this project is a mystery for me, When I imagine VSync it should cap framerate to display's refresh rate, which my workaround definitely doesn't.

**Comment by Wieku** [comment]
VSync is not something you implement. It is always managed by graphics drivers.

**Comment by peppy** [comment]
As above, manually implementing vsync is the exactly opposite of what vsync is. You may want to read up about it.

The `glFinish` call change is an interesting one. In `osu-stable` we actually offer this choice to the user as it does help in some scenarios (even on PC).

In general you don't want to call this unnecessarily, but we may need to investigate having it on as a default for macOS if it is deemed to solve the issue.

**Comment by ThatsNiceGuy** [comment]
Occurs on both my Hackintoshes as well. It’s worse on my laptop with the Intel UHD 630 only producing like 40 FPS.

**Comment by EVAST9919** [comment]
I don't think Hackintosh is a stable thing by it's own. (and not legal, I guess)

**Comment by ThatsNiceGuy** [comment]
I am not going to discuss the legality of Hackintoshing but note that I observe the same issue on real Macs, and that my systems are properly configured and are stable. It only occurs with osu!lazer and not stuff like Final Cut or 3D apps from the App Store

**Comment by peppy** [comment]
@ThatsNiceGuy to make sure you're actually hitting the same issue, could you please try the proposed fix and see if it helps?

**Comment by ThatsNiceGuy** [comment]
sure, lemme do that real quick

**Comment by peppy** [comment]
On testing locally, it doesn't look like frame rate is negatively affected in a huge way by enabling `glFinish`, but it [generally](https://stackoverflow.com/questions/2143240/opengl-glflush-vs-glfinish) [isn't](https://community.khronos.org/t/glflush-or-glfinish-with-mulithreading/61309) [recommended](https://www.chromium.org/nativeclient/how-tos/3d-tips-and-best-practices) [practice](https://software.intel.com/en-us/articles/opengl-performance-tips-avoid-opengl-calls-that-synchronize-cpu-and-gpu), so am hesitant to make it a default.

Maybe as a temporary fix for macOS hosts if we can determine that it resolves the issue in many cases.

I'm waiting for feedback on [this twitter conversation](https://twitter.com/ppy/status/1225661060557852673) to determine how to move forward next. If the user (or others) can confirm this does indeed help then we will roll out a framework release with glFinish forced on for macOS hosts for further testing.

**Comment by Snowmander** [comment]
Since that twitter conversation seems to be dead, I tested it myself and saw significant performance increase.

- Latest release on Catalina
- 2019 13 inch Base Macbook Pro (i5)
- Tested by opening osu direct

2x frame limiter: Severe stuttering, fps ranges from 30-80
Vsync: Holds 60 fps

Let me know if you need anything else.

**Comment by peppy** [comment]
@Snowmander could you please try this build:

https://drive.google.com/file/d/1vlUyh6Cu990ucfUdheBkHGbMcKlf8aDN/view?usp=sharing

Note that you may need to right-click then choose open, as I haven't signed this. Let me know if you need it signed.

With this build, please try setting vsync *off* and see if your performance is better.

**Comment by GSculerlor** [comment]
Tried that build and now it doing better at 2x refresh rate

**Comment by peppy** [comment]
Does the performance remain high ever above that? Unlimited also improved?

**Comment by GSculerlor** [comment]
Yes, it better and almost no frame drops on my device (Macbook Pro 2017 Catalina 10.15.3)

**Comment by peppy** [comment]
Thanks. We'll deploy this in the next release (specifically for macOS) and see how things go.

**Comment by Snowmander** [comment]
Can confirm as well, fps is now stable at around 70 in osu direct with frame limiter disabled.
