### ISSUE TITLE
Non-Unicode text

### ISSUE THREAD

**Issue by Kyorie** [ppy/osu#7456]
**Describe the bug:** 
Non-Unicode symbols don't display correctly (russian in my case)
**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/hzS4aEv.png
https://i.imgur.com/JINaaC2.png
**osu!lazer version:** 
2020.104.0

**Comment by EVAST9919** [comment]
Duplicate of https://github.com/ppy/osu/issues/5827
