### ISSUE TITLE
osu terminates when the beatmap reaches the end of it

### ISSUE THREAD

**Issue by mir99712** [ppy/osu#746]
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
____
TargetInvocationException: Exception has been thrown by the target of an invocation.
NullReferenceException: Object reference not set to an instance of an object.

**Comment by huoyaoyuan** [comment]
I think providing more information (where the exception was thrown, and the call stack) will help debugging it.

**Comment by Eojk** [comment]
When i start debug mode he return me: "The program '[9840] osu!.exe' has exited with code 0 (0x0)."

**Comment by apap04** [comment]
@Eojk thats normal
lol

**Comment by ColdVolcano** [comment]
This is caused at the point of time the results screen is pushed, although I guess it needs a lot more info than that

**Comment by peppy** [comment]
A call stack would be enough to help diagnose the problem. Any less than that is quite useless.

For what it's worth I haven't been able to reproduce tis locally yet.

**Comment by ColdVolcano** [comment]
```
   en System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   en System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   en System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   en osu.Framework.Allocation.DependencyContainer.<>c__DisplayClass7_1.<register>b__5(Object instance) en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu-framework\osu.Framework\Allocation\DependencyContainer.cs:línea 78
   en System.Collections.Generic.List`1.ForEach(Action`1 action)
   en osu.Framework.Allocation.DependencyContainer.<>c__DisplayClass7_2.<register>b__7(DependencyContainer container, Object instance) en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu-framework\osu.Framework\Allocation\DependencyContainer.cs:línea 90
   en osu.Framework.Allocation.DependencyContainer.Initialize[T](T instance, Boolean autoRegister, Boolean lazy) en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu-framework\osu.Framework\Allocation\DependencyContainer.cs:línea 173
   en osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, DependencyContainer dependencies) en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu-framework\osu.Framework\Graphics\Drawable.cs:línea 182
   en osu.Framework.Graphics.Containers.Container`1.loadChild(T child) en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu-framework\osu.Framework\Graphics\Containers\Container.cs:línea 88
   en osu.Framework.Lists.LifetimeList`1.Add(T item) en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu-framework\osu.Framework\Lists\LifetimeList.cs:línea 81
   en osu.Framework.Graphics.Containers.Container`1.AddInternal(T drawable) en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu-framework\osu.Framework\Graphics\Containers\Container.cs:línea 289
   en osu.Game.Screens.Ranking.Results.<load>b__19_0(ResultMode mode) en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu.Game\Screens\Ranking\Results.cs:línea 280
   en osu.Framework.Configuration.Bindable`1.BindableValueChanged`1.Invoke(TValue newValue)
   en osu.Framework.Configuration.Bindable`1.TriggerValueChange() en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu-framework\osu.Framework\Configuration\Bindable.cs:línea 114
   en osu.Framework.Configuration.Bindable`1.TriggerChange() en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu-framework\osu.Framework\Configuration\Bindable.cs:línea 108
   en osu.Game.Screens.Ranking.Results.load(OsuColour colours) en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu.Game\Screens\Ranking\Results.cs:línea 283
   en osu.Game.Screens.Play.SongProgressGraph.set_Objects(IEnumerable`1 value) 
en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu.Game\Screens\Play\SongProgressGraph.cs:línea 19
   en osu.Game.Screens.Ranking.ResultsPageScore.load(OsuColour colours) en C:\Users\LavainstranterCV\Source\Repos\osu-a\osu.Game\Screens\Ranking\ResultsPageScore.cs:línea 43
```
That's the nearest I could get

**Comment by huoyaoyuan** [comment]
`DependencyContainer`, seems `BackgroundDependencyLoader` of some class broken

**Comment by mir99712** [comment]
![image](https://cloud.githubusercontent.com/assets/27609690/26023393/7148ffee-37f5-11e7-9cb2-0d2706ca83c1.png)

(줄 means Line. 줄 342:Line 342
외부 코드 means External Code)

**Comment by huoyaoyuan** [comment]
Oh, I've met this issue several weeks ago. If you are not logged in, result screen will fail to construct, seems your user is passed into it.
@peppy seems not cannot repro

**Comment by mir99712** [comment]
Ahh, I see..
After logging in, result screen appears with a little lag and delay, and osu doesn't terminate.

**Comment by MinecraftPlaye** [comment]
I've just found this crash report on your blog in the comment section (it seems to be related to the problem):

> `Problem signature
Problem Event Name:	CLR20r3
Problem signature 01:	osu!.exe
Problem signature 02:	2017.503.0.0
Problem signature 03:	5909d32a
Problem signature 04:	osu.Game
Problem signature 05:	1.0.0.0
Problem signature 06:	5909d328
Problem signature 07:	986
Problem signature 08:	43
Problem signature 09:	System.NullReferenceException
OS Version:	10.0.14393.2.0.0.256.48
Locale ID:	1031
Additional Information 1:	9375
Additional Information 2:	9375fb0814421e27461bc7f608448f0f
Additional Information 3:	5c68
Additional Information 4:	5c68440089df80d024fc18d587d4acce

Additional Information about the problem
Bucket-ID:	eed1bdc899492f6419b76ea424ea5ced (129437122931)

Garbage Collector: SubstainedLowLatency`

I could also get this information from Windows (well, I just exited the task after Windows started trying to solve the problem itself which never results in anything usefull):

> `Problem signature
Problem Event Name:	CLR20r3
Problem signature 01:	osu!.exe
Problem signature 02:	2017.508.0.0
Problem signature 03:	59106691
Problem signature 04:	Squirrel
Problem signature 05:	1.5.2.0
Problem signature 06:	58893cda
Problem signature 07:	160
Problem signature 08:	14
Problem signature 09:	System.Threading.AbandonedMutex
OS Version:	10.0.14393.2.0.0.256.48
Locale ID:	1031
Additional Information 1:	8afa
Additional Information 2:	8afa7489330e24836d7d16fd3774e2ff
Additional Information 3:	feca
Additional Information 4:	feca3f342441657d180e398e16f758c7

Additional Information about the problem
Bucket-ID:	1ed9cf8636300f98d4a65bc4c8a5721d (129441540893)`

If more information is required, let me know, so I might be able to provide it (after installing Visual Studio again as I've got only Eclipse currently).

Some additional information about my system:
Windows 10 Pro x64 Version 1607
Intel Core i7 6800k
DDR4 RAM
GTX 960 (latest driver 382.05)

Also this problem seems only to occur when you play the beatmap yourself AND are not logged in (so you play as a guest) (tested with multiply beatmaps). When autoplay is active the result screen appears just fine. The crash seems also to affect all versions since the result screen was introduced.

**Comment by Zalmez** [comment]
I have no issues reproducing this while being logged in.

Call stack while not being logged in:
`osu.Game.dll!osu.Game.Screens.Ranking.ResultsPageScore.UserHeader.UserHeader(osu.Game.Users.User user) Line 341	C#
 	osu.Game.dll!osu.Game.Screens.Ranking.ResultsPageScore.load(osu.Game.Graphics.OsuColour colours) Line 42	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__5(object instance) Line 77	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__8(System.Action<object> init) Line 89	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__7(osu.Framework.Allocation.DependencyContainer container, object instance) Line 89	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.Initialize<osu.Framework.Graphics.Drawable>(osu.Framework.Graphics.Drawable instance, bool autoRegister, bool lazy) Line 172	C#
 	osu.Framework.dll!osu.Framework.Graphics.Drawable.Load(osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.DependencyContainer dependencies) Line 184	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.loadChild(osu.Framework.Graphics.Drawable child) Line 87	C#
 	osu.Framework.dll!osu.Framework.Lists.LifetimeList<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable item) Line 81	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.AddInternal(osu.Framework.Graphics.Drawable drawable) Line 291	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable drawable) Line 177	C#
 	osu.Game.dll!osu.Game.Screens.Ranking.Results.load.AnonymousMethod__19_0(osu.Game.Screens.Ranking.ResultMode mode) Line 278	C#
 	osu.Framework.dll!osu.Framework.Configuration.Bindable<osu.Game.Screens.Ranking.ResultMode>.TriggerValueChange() Line 111	C#
 	osu.Framework.dll!osu.Framework.Configuration.Bindable<osu.Game.Screens.Ranking.ResultMode>.TriggerChange() Line 105	C#
 	osu.Game.dll!osu.Game.Screens.Ranking.Results.load(osu.Game.Graphics.OsuColour colours) Line 281	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__5(object instance) Line 77	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__8(System.Action<object> init) Line 89	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__7(osu.Framework.Allocation.DependencyContainer container, object instance) Line 89	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.Initialize<osu.Framework.Graphics.Drawable>(osu.Framework.Graphics.Drawable instance, bool autoRegister, bool lazy) Line 172	C#
 	osu.Framework.dll!osu.Framework.Graphics.Drawable.Load(osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.DependencyContainer dependencies) Line 184	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.loadChild(osu.Framework.Graphics.Drawable child) Line 87	C#
 	osu.Framework.dll!osu.Framework.Lists.LifetimeList<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable item) Line 81	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.AddInternal(osu.Framework.Graphics.Drawable drawable) Line 291	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable drawable) Line 177	C#
 	osu.Framework.dll!osu.Framework.Screens.Screen.Push(osu.Framework.Screens.Screen screen) Line 141	C#
 	osu.Game.dll!osu.Game.Screens.Play.Player.onCompletion.AnonymousMethod__40_0() Line 319	C#
 	osu.Framework.dll!osu.Framework.Threading.ScheduledDelegate.RunTask() Line 244	C#
 	osu.Framework.dll!osu.Framework.Threading.Scheduler.Update() Line 115	C#
 	osu.Framework.dll!osu.Framework.Graphics.Drawable.UpdateSubTree() Line 377	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 346	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Platform.GameHost.UpdateFrame() Line 232	C#
 	osu.Framework.dll!osu.Framework.Threading.GameThread.ProcessFrame() Line 112	C#
 	osu.Framework.dll!osu.Framework.Threading.GameThread.runWork() Line 101	C#
`


Call stack while being logged in:


` 	[External Code]	
>	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__5(object instance) Line 77	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__8(System.Action<object> init) Line 89	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__7(osu.Framework.Allocation.DependencyContainer container, object instance) Line 89	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.Initialize<osu.Framework.Graphics.Drawable>(osu.Framework.Graphics.Drawable instance, bool autoRegister, bool lazy) Line 172	C#
 	osu.Framework.dll!osu.Framework.Graphics.Drawable.Load(osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.DependencyContainer dependencies) Line 184	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.loadChild(osu.Framework.Graphics.Drawable child) Line 87	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.load(osu.Framework.Game game, osu.Framework.Graphics.Shaders.ShaderManager shaders) Line 79	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__5(object instance) Line 77	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__8(System.Action<object> init) Line 89	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__7(osu.Framework.Allocation.DependencyContainer container, object instance) Line 89	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.Initialize<osu.Framework.Graphics.Drawable>(osu.Framework.Graphics.Drawable instance, bool autoRegister, bool lazy) Line 172	C#
 	osu.Framework.dll!osu.Framework.Graphics.Drawable.Load(osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.DependencyContainer dependencies) Line 184	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.loadChild(osu.Framework.Graphics.Drawable child) Line 87	C#
 	osu.Framework.dll!osu.Framework.Lists.LifetimeList<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable item) Line 81	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.AddInternal(osu.Framework.Graphics.Drawable drawable) Line 291	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable drawable) Line 177	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable drawable) Line 179	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.Add(System.Collections.Generic.IEnumerable<osu.Framework.Graphics.Drawable> range) Line 189	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.Children.set(System.Collections.Generic.IEnumerable<osu.Framework.Graphics.Drawable> value) Line 125	C#
 	osu.Game.dll!osu.Game.Screens.Ranking.ResultsPageScore.load(osu.Game.Graphics.OsuColour colours) Line 42	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__5(object instance) Line 77	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__8(System.Action<object> init) Line 89	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__7(osu.Framework.Allocation.DependencyContainer container, object instance) Line 89	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.Initialize<osu.Framework.Graphics.Drawable>(osu.Framework.Graphics.Drawable instance, bool autoRegister, bool lazy) Line 172	C#
 	osu.Framework.dll!osu.Framework.Graphics.Drawable.Load(osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.DependencyContainer dependencies) Line 184	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.loadChild(osu.Framework.Graphics.Drawable child) Line 87	C#
 	osu.Framework.dll!osu.Framework.Lists.LifetimeList<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable item) Line 81	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.AddInternal(osu.Framework.Graphics.Drawable drawable) Line 291	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable drawable) Line 177	C#
 	osu.Game.dll!osu.Game.Screens.Ranking.Results.load.AnonymousMethod__19_0(osu.Game.Screens.Ranking.ResultMode mode) Line 278	C#
 	osu.Framework.dll!osu.Framework.Configuration.Bindable<osu.Game.Screens.Ranking.ResultMode>.TriggerValueChange() Line 111	C#
 	osu.Framework.dll!osu.Framework.Configuration.Bindable<osu.Game.Screens.Ranking.ResultMode>.TriggerChange() Line 105	C#
 	osu.Game.dll!osu.Game.Screens.Ranking.Results.load(osu.Game.Graphics.OsuColour colours) Line 281	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__5(object instance) Line 77	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__8(System.Action<object> init) Line 89	C#
 	[External Code]	
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.register.AnonymousMethod__7(osu.Framework.Allocation.DependencyContainer container, object instance) Line 89	C#
 	osu.Framework.dll!osu.Framework.Allocation.DependencyContainer.Initialize<osu.Framework.Graphics.Drawable>(osu.Framework.Graphics.Drawable instance, bool autoRegister, bool lazy) Line 172	C#
 	osu.Framework.dll!osu.Framework.Graphics.Drawable.Load(osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.DependencyContainer dependencies) Line 184	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.loadChild(osu.Framework.Graphics.Drawable child) Line 87	C#
 	osu.Framework.dll!osu.Framework.Lists.LifetimeList<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable item) Line 81	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.AddInternal(osu.Framework.Graphics.Drawable drawable) Line 291	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.Add(osu.Framework.Graphics.Drawable drawable) Line 177	C#
 	osu.Framework.dll!osu.Framework.Screens.Screen.Push(osu.Framework.Screens.Screen screen) Line 141	C#
 	osu.Game.dll!osu.Game.Screens.Play.Player.onCompletion.AnonymousMethod__40_0() Line 319	C#
 	osu.Framework.dll!osu.Framework.Threading.ScheduledDelegate.RunTask() Line 244	C#
 	osu.Framework.dll!osu.Framework.Threading.Scheduler.Update() Line 115	C#
 	osu.Framework.dll!osu.Framework.Graphics.Drawable.UpdateSubTree() Line 377	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 346	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Graphics.Containers.Container<osu.Framework.Graphics.Drawable>.UpdateSubTree() Line 358	C#
 	osu.Framework.dll!osu.Framework.Platform.GameHost.UpdateFrame() Line 232	C#
 	osu.Framework.dll!osu.Framework.Threading.GameThread.ProcessFrame() Line 112	C#
 	osu.Framework.dll!osu.Framework.Threading.GameThread.runWork() Line 101	C#
 	[External Code]	
`
Beatmaps tested with:
https://new.ppy.sh/beatmapsets/331190#osu/733755
https://new.ppy.sh/beatmapsets/574214#osu/1216208
results same on both maps

**Comment by peppy** [comment]
Please test out https://github.com/ppy/osu/issues/765 and see if it fixes your issues.
