### ISSUE TITLE
Changelog text is broken into separate lines

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu#7463]
**Describe the bug:** 
The text in the changelog is broken into different lines and the check symbol is not in the right position. But it's normal on the web though.
**Screenshots or videos showing encountered issue:** 
![osu_2020-01-07_16-17-29](https://user-images.githubusercontent.com/16283764/71883712-8f13fb80-3169-11ea-9914-abd85d39148c.png)

**osu!lazer version:** 
Latest git (commit c3024e68f5c6d4afc3d24081870b62b460de7f4b)
**Logs:** 
No need

**Comment by EVAST9919** [comment]
That's how this text looks like in response:
`"title":"Adjust scrolling container object lifetime to account for origin choice\r\n\r\n---\r\n\r\nFixes taiko hitobjects appearing without fade in."`
Looks like `\n` counts like a new line here.

**Comment by peppy** [comment]
This was actually my fault. Has been fixed.
