### ISSUE TITLE
Display storyboards and video in main menu

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7467]
**Describe the new feature:** If the user is on the title screen listening to songs, the background could be replaced by the current song's storyboard or video.

**Comment by Wieku** [comment]
I tried this when I was making my own client and I find it too noisy for main menu: https://streamable.com/06bgu

**Comment by iiSaLMaN** [comment]
Maybe if the user is idle for like 2 seconds or something, make the menu fade out to view the video / storyboard fully.

**Comment by peppy** [comment]
i think this one will not be added and reside in cinema mod only. If anything, this would be implemented as a demo mode (turning on arcade mode, for instance) where it will replay player replays (not just showing video/storyboard but full gameplay) when idle.
