### ISSUE TITLE
Crashing when open and close status changing dropdown

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu#7471]
**Describe the crash:** 
- Open game
- Go to solo
- Click your username at the top-right corner
- Click "Online" (the status dropdown)
- Click it again (not changing status)

**Screenshots or videos showing encountered issue:** 
https://youtu.be/hxnPnoqKuWk
**osu!lazer version:**
Latest git (c3024e68f5c6d4afc3d24081870b62b460de7f4b)
**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4033497/runtime.log)
**Computer Specifications:** 
- OS: Arch Linux
- CPU: Intel® Core™ i5-4690 Processor
- GPU: GeForce GT 1030
- RAM: 2x4GB DDR3

**Comment by smoogipoo** [comment]
You're seeing / will be fixed by https://github.com/ppy/osu-framework/pull/3160

**Comment by recapitalverb** [comment]
It seems that this issue is still occuring after the merge - will this be resolved in https://github.com/ppy/osu/pull/7466?

**Comment by peppy** [comment]
you need to update your framework checkout, or wait for it to be updated.
