### ISSUE TITLE
Playback speed affects all situations

### ISSUE THREAD

**Issue by XDmarieteXD** [ppy/osu#7476]
Describe the bug: when you change the playback speed in the osu!editor it affects all the situations in the game including gameplay.

Screenshots or videos showing encountered issue: [bug.zip](https://github.com/ppy/osu/files/4035814/bug.zip)

osu!lazer version: 2020.104.0

(sorry if my english level is too low, hope I can help)

**Comment by EVAST9919** [comment]
Duplicate of https://github.com/ppy/osu/issues/7468

**Comment by XDmarieteXD** [comment]
oh, i didnt know, sorry :(
