### ISSUE TITLE
Missing rounded corners in status selection dropdown menu

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#7489]
**Describe the bug:** There are missing rounded corners in the status selection dropdown menu.

**Screenshots or videos showing encountered issue:** 
![Screenshot_20200110_215945](https://user-images.githubusercontent.com/41869184/72163082-b54dcb80-33f5-11ea-82c6-2c0f5b6a8b32.png)

**osu!lazer version:** master branch commit f745d746666031b785abf88c0b0d8062f0103694

**Logs:**
[database.log](https://github.com/ppy/osu/files/4046258/database.log)
[network.log](https://github.com/ppy/osu/files/4046260/network.log)
[performance.log](https://github.com/ppy/osu/files/4046261/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4046262/runtime.log)

**Comment by smoogipoo** [comment]
This is by design, but the rounded style should match every other dropdown in the game:

![image](https://user-images.githubusercontent.com/1329837/72166786-3d8b9b00-340d-11ea-99f5-a545c438bb3b.png)

I.e. The corners should be larger and it should be inset.
