### ISSUE TITLE
Mania should always use standardized score

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7493]
(Maybe) matches stable behavior, as there seems to be no v1 score scheme for mania.

**Comment by peppy** [comment]
What's the reasoning for this?

**Comment by enoslayd** [comment]
maybe because of this?
(score display mode is set to classic BTW and i use auto since i cant score that high)
![osu_2020-01-12_16-28-18](https://user-images.githubusercontent.com/41866328/72216188-e8f53680-3558-11ea-98b7-4c3791d51d13.png)

**Comment by enoslayd** [comment]
update: no auto but score is set to classic and this time i scored 5million, which must not be possible since classic should limit it to 1 million

![osu_2020-01-12_16-37-27](https://user-images.githubusercontent.com/41866328/72216260-e8a96b00-3559-11ea-9a07-ba9da0e3250f.png)

**Comment by smoogipoo** [comment]
This is intentional. Scoring does not match and will not match Stable, this is a completely new algorithm.

**Comment by enoslayd** [comment]
I mean it should be, right? Since it should match stable cause its score display is in classic mode

**Comment by smoogipoo** [comment]
That isn't quite what "classic" means in lazer's context. It may be renamed to "exponential" in the future to avoid this confusion.
