### ISSUE TITLE
Changing volume in game changes cursor

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7499]
**Describe the bug:** 
Changing the volume while in game and moving cursor over wheels changes the cursor to the menu cursor and makes game cursor almost invisible.
Circles can still be clicked.
Not sure if it's intentional, but I find it slightly distracting, maybe add a toggle?
**Screenshots or videos showing encountered issue:** 
![screenshot](https://user-images.githubusercontent.com/32612290/72209150-2474ff80-348a-11ea-9a3c-6f38c64edd04.jpg)
**osu!lazer version:** 
`$ git rev-parse HEAD`
9a9c01bc92549f3acee4af8e2caf6265d0c7b5fb
**Logs:** 
Visual

**Comment by peppy** [comment]
This is intended.
