### ISSUE TITLE
osu exception: System.ArgumentException: '0' cannot be greater than -1.

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#7506]
**Describe the bug:** this happened to me a few times, im not quite sure how to reproduce it.

**osu!lazer version:** 
2020.112.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/4049845/runtime.log)

**Comment by EVAST9919** [comment]
Related to https://github.com/ppy/osu/issues/7505. (Not sure if duplicate)

**Comment by bdach** [comment]
Immediate stack trace looks close enough, so closing as duplicate.
