### ISSUE TITLE
Console outputs the same thing over and over again while minimized

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7507]
**Describe the bug:** 
The same bunch of messages comes up repeatedly in the console output while osu is minimized
**Screenshots or videos showing encountered issue:** 
Just console output
**osu!lazer version:** 
9a9c01bc92549f3acee4af8e2caf6265d0c7b5fb
**Logs:** 
This, repeated every 50 or so ms
```
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
```
Might help with #7500 ?
Is this something to do with my install?

**Comment by bdach** [comment]
That just looks like some linux audio misconfiguration on your side and maybe it'll resolve the other issue if you get it sorted. Closing as out of scope for us to handle.
