### ISSUE TITLE
Mania holds and taiko drum roll fades are jarring

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7508]
The short fade duration makes them appear as if they're popping out of existence immediately after a judgement.

To reproduce, in `osu.Game.Rulesets.Mania.Tests`:
1. Run `TestSceneColumn` or `TestSceneStage`.
2. Click the `hold note` step, then play the note that appears.

Taiko is not tested.

**osu!lazer version:** 2020.112.0

**Comment by peppy** [comment]
Just to confirm, this is specific to the test scenes yes?

**Comment by mcendu** [comment]
Not specific.

**Comment by smoogipoo** [comment]
It's not instant. It's fading, with a very short duration. In the case of mania, this is done as a stop-gap measure while we figure out a better animation for it.

**Comment by peppy** [comment]
Bumping up in priority. To me this is the number one most awkward part of mania at the moment.
