### ISSUE TITLE
Request: Low Spec Mode

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#7511]
**Describe the new feature:** 
Tickbox in the settings menu, sometimes disabled by default depending on system specs, that disables the most intensive effects, or maybe gives the user an option of what ones to disable. (Blur, glow, transitions, etc, any of the intensive effects)

**Proposal designs of the feature:** 
None, really

**Comment by bdach** [comment]
Variations of this have been requested before (#3205, #6395, #6829). I think it's vastly preferable to optimize the effects we have as much as possible rather than start adding settings to disable them.

**Comment by peppy** [comment]
We don’t intend on having such an option. If effects are deemed to not be feasible on the host system they will be automatically disabled.
