### ISSUE TITLE
Lazer doesn't start at all.

### ISSUE THREAD

**Issue by Kidyeon** [ppy/osu#7512]
**Describe the crash:** 
On attempt to start the game, I get a loading circle on my mouse for a couple of seconds, and task manager shows a noticeable increase in my CPUs performance. After that, nothing happens and my CPU returns to normal.

**Screenshots or videos showing encountered issue:** 
Nothing to show

**osu!lazer version:** 
2020.112.0

**Logs:** 
Got two things via event viewer. For whatever it's worth, I tried to update .net framework as soon as I first had this happen, but didn't fix anything.

> Log Name:      Application
> Source:        .NET Runtime
> Date:          1/12/2020 9:50:32 PM
> Event ID:      1026
> Task Category: None
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Computer:      Kidyeon-PC
> Description:
> Application: osu!.exe
> CoreCLR Version: 4.700.19.56402
> .NET Core Version: 
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Kidyeon\AppData\Roaming\osu\logs'.
>    at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
>    at System.IO.Directory.CreateDirectory(String path)
>    at osu.Framework.Platform.NativeStorage.GetFullPath(String path, Boolean createIfNotExisting)
>    at osu.Framework.Platform.Storage.GetStorageForDirectory(String path)
>    at osu.Framework.Platform.GameHost.SetupForRun()
>    at osu.Framework.Platform.DesktopGameHost.SetupForRun()
>    at osu.Framework.Platform.Windows.WindowsGameHost.SetupForRun()
>    at osu.Framework.Platform.GameHost.Run(Game game)
>    at osu.Desktop.Program.Main(String[] args)
> 
> Event Xml:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name=".NET Runtime" />
>     <EventID Qualifiers="0">1026</EventID>
>     <Level>2</Level>
>     <Task>0</Task>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2020-01-13T03:50:32.932047400Z" />
>     <EventRecordID>12914</EventRecordID>
>     <Channel>Application</Channel>
>     <Computer>Kidyeon-PC</Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>Application: osu!.exe
> CoreCLR Version: 4.700.19.56402
> .NET Core Version: 
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Kidyeon\AppData\Roaming\osu\logs'.
>    at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
>    at System.IO.Directory.CreateDirectory(String path)
>    at osu.Framework.Platform.NativeStorage.GetFullPath(String path, Boolean createIfNotExisting)
>    at osu.Framework.Platform.Storage.GetStorageForDirectory(String path)
>    at osu.Framework.Platform.GameHost.SetupForRun()
>    at osu.Framework.Platform.DesktopGameHost.SetupForRun()
>    at osu.Framework.Platform.Windows.WindowsGameHost.SetupForRun()
>    at osu.Framework.Platform.GameHost.Run(Game game)
>    at osu.Desktop.Program.Main(String[] args)
> </Data>
>   </EventData>
> </Event>

as well as
e
> Log Name:      Application
> Source:        Application Error
> Date:          1/12/2020 9:50:32 PM
> Event ID:      1000
> Task Category: (100)
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Computer:      Kidyeon-PC
> Description:
> Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5dcec899
> Faulting module name: KERNELBASE.dll, version: 10.0.18362.535, time stamp: 0x50cc8d5a
> Exception code: 0xe0434352
> Fault offset: 0x000000000003a839
> Faulting process id: 0x1e6c
> Faulting application start time: 0x01d5c9c49ae7b1dd
> Faulting application path: C:\Users\Kidyeon\AppData\Local\osulazer\app-2020.112.0\osu!.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 142a712c-e2bf-4307-9c02-6e9ea21d58b7
> Faulting package full name: 
> Faulting package-relative application ID: 
> Event Xml:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name="Application Error" />
>     <EventID Qualifiers="0">1000</EventID>
>     <Level>2</Level>
>     <Task>100</Task>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2020-01-13T03:50:32.992011900Z" />
>     <EventRecordID>12915</EventRecordID>
>     <Channel>Application</Channel>
>     <Computer>Kidyeon-PC</Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>osu!.exe</Data>
>     <Data>0.0.0.0</Data>
>     <Data>5dcec899</Data>
>     <Data>KERNELBASE.dll</Data>
>     <Data>10.0.18362.535</Data>
>     <Data>50cc8d5a</Data>
>     <Data>e0434352</Data>
>     <Data>000000000003a839</Data>
>     <Data>1e6c</Data>
>     <Data>01d5c9c49ae7b1dd</Data>
>     <Data>C:\Users\Kidyeon\AppData\Local\osulazer\app-2020.112.0\osu!.exe</Data>
>     <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
>     <Data>142a712c-e2bf-4307-9c02-6e9ea21d58b7</Data>
>     <Data>
>     </Data>
>     <Data>
>     </Data>
>   </EventData>
> </Event>

**Computer Specifications:** 
Windows 10
i5-4690k
Radeon RX 580
16GB RAM

**Comment by peppy** [comment]
Can you check how much of the path specified exists on disk `C:\Users\Kidyeon\AppData\Roaming\osu\logs`?

**Comment by Kidyeon** [comment]
Well, just going there solved my issue. I had an MK-link hooked to nothing, so the game couldn't generate any files. Undid that and the game was instantly able to start.

Seems it was just something on my end, sorry.
