### ISSUE TITLE
Ability to adjust SV in difficulty adjust mod

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#7513]
**Describe the new feature:**

Add a slider to adjust overall SV in difficulty adjust mod. The slider will start at 1.0x and all timing points with SV will be multiplied with the slider value.

This is useful in Taiko when you want to practice a beatmap with faster/slower scrolling. I'm not sure if osu! standard or other modes will break with this feature.

**Comment by huoyaoyuan** [comment]
This would be taiko specific that adjusts scrolling speed.

Maybe scrolling speed in taiko can be unlocked like mania? This should be somehow related to the discussion of unlocking AR.
