### ISSUE TITLE
Difficulty adjustment panel should open automatically

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#7514]
**Describe the new feature:** 

Difficulty adjustment panel should open automatically when adding a mod that supports adjustments, and "Customize" button should be removed because it is completely redundant.

The fact that a user adds Difficulty Adjust mod already signifies that they wish to drag sliders that adjust the beatmap. It is inconvenient to click a button to reveal what should already be visible.

**Comment by mcendu** [comment]
Object. This can be inconvenient on mobile devices if we apply such a change.

**Comment by peppy** [comment]
I tend to agree with this. Maybe `Mod` can expose a `RequiresConfiguration` bool which can be set in such cases, causes the configuration to be displayed on selection.

**Comment by Joehuu** [comment]
> "Customize" button should be removed because it is completely redundant.

Still needs a toggle as the window will block mod buttons on the right.

**Comment by peppy** [comment]
The thing is, Difficulty Adjust *requires* customisation to make it purposeful. So there's no reason to not have it automatically open on selecting. The user can close it once they are done changing the options.
