### ISSUE TITLE
Tooltip capitalization inconsistencies across the game

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#7515]
**Describe the bug:** 

There are many inconsistencies in capitalization of tooltip texts across the game which should be unified.

**Screenshots or videos showing encountered issue:** 

Here are a few that I've found:

Mixed case:

![image](https://user-images.githubusercontent.com/27663662/72242810-a4879a80-362d-11ea-8f5c-6150b730bf1c.png)

![image](https://user-images.githubusercontent.com/27663662/72242884-c5e88680-362d-11ea-9995-8d23c98764f5.png)

Title case:

![image](https://user-images.githubusercontent.com/27663662/72243001-0a742200-362e-11ea-8334-0c4e1534cf10.png)

Lowercase:

![image](https://user-images.githubusercontent.com/27663662/72242851-b5d0a700-362d-11ea-8975-293ccb479bc4.png)

![image](https://user-images.githubusercontent.com/27663662/72242905-d1d44880-362d-11ea-9869-8fc5c2ef60ca.png)

**osu!lazer version:** 2020.112.0

**Comment by peppy** [comment]
should all be lower case, i think, except for country.

**Comment by revelsix** [comment]
For reference, are we only referring to the text that pops up when you hover over something?

**Comment by iiSaLMaN** [comment]
Yes, that's what we call a "tooltip".
