### ISSUE TITLE
Slider input does not match osu!stable

### ISSUE THREAD

**Issue by TheWildTree** [ppy/osu#7521]
There are some major differences that I've noticed when comparing lazer with stable:

- Slider head moves together with the sliderball, while on stable it stays in place with sliderball moving independently. Indirectly mentioned in #6088, almost certainly **causes replay inconsistencies** vs. stable, especially on sliders with high SV. This is best visible when sliderhead doesn't get hit at all (lazer left, stable right, full example [**here**](https://gfycat.com/ifr/DiligentMarvelousGuillemot)):

    ![image](https://user-images.githubusercontent.com/27722894/72260580-739a6c00-3613-11ea-8e5b-fea61db96e50.png)

    By the way, judgement sprites seem to be displayed 'behind' the sliders, stable has them on top (as seen above)

- ~~Slider circle range seems to be a bit different, same replay on lazer gives different results than stable. [**Video comparison here**](https://streamable.com/7jqj2).~~ Fixed.

Fixing these, especially the first one, should result in getting rid of major replay inconsistencies on maps with high SVs, [like this one](https://youtu.be/h3SkCJtSU3E?t=463) for example, since right now if a slider has very high SV and gets hit at least a bit late (even still in the 300 hitwindow), in lazer the head might move before getting hit, resulting in a miss.

**Comment by Wieku** [comment]
About slider head look at this *TODO*: https://github.com/ppy/osu/blob/f3bb47ffce87fb1077e6627d002c9add03ecf583/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderHead.cs#L41-L43

About slider follow circle, in stable sprite doesn't reflect actual allowable radius. If I remember stable follow circle radius is 2.4 the circle radius, not 2. And it's virtual size is changed instantly.
https://github.com/ppy/osu/blob/f3bb47ffce87fb1077e6627d002c9add03ecf583/osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs#L98-L99

**Comment by Wieku** [comment]
And I think one thing to reconsider with high SV maps is to bring back -36 ms offset on slider tail judgements, at least for replays coming from stable. They're visible in this video as white points, they denote if slider is fully completed or not: https://streamable.com/u0gbg

**Comment by TheWildTree** [comment]
Yup, just noticed that TODO as well. Fixing this needs an accompanying change to slider snaking-out behavior though, I'll try to work on that.

I'm kinda surprised the slider tail offset hasn't been implemented yet, considering how many maps rely on it to make sliders possible to hit without dropping sliderends / combo.

**Comment by peppy** [comment]
The 36ms hack isn't added because it was a hack. It may be added for legacy replays but should not apply to new plays.

**Comment by TheWildTree** [comment]
For clarity, from discussion in the PR above:

> Sliders are moving hitobjects. Lazer adds accuracy. Part of this addition is that if you hit late, the hitbox changes. This is intended for now.

Due to this, imo we should implement the 36ms hack + static sliderheads only for legacy replays (for now) to at least preserve consistency for old scores.

**Comment by bdach** [comment]
Note that replay inaccuracy is tracked at #5514.

**Comment by smoogipoo** [comment]
Fwiw, the 36ms offset is actually implemented. Check how nested hitobjects are generated for `Slider`.

The biggest gameplay difference is the tracking region. Static slider heads can be implemented for legacy skins.

**Comment by TheWildTree** [comment]
> Static slider heads can be implemented for legacy skins.

You meant legacy maps, right? Otherwise we'd have skins making a difference in gameplay mechanics and that's a no-go

**Comment by smoogipoo** [comment]
As mentioned in the closed PR, we aren't decided on that. The tracking region being 0.4 smaller than it should be is an actual bug, however.

**Comment by TheWildTree** [comment]
Sorry, I meant to ask about legacy replays*. My bad.

**Comment by smoogipoo** [comment]
Potentially, but there's a lot more that we'll have to consider if we're to go down that path. So I'm not interested in doing that for now.

**Comment by peppy** [comment]
@smoogipoo propose moving this out of milestone for now as I don't think legacy replay compatibility is a priority we have for February/March at least.

**Comment by peppy** [comment]
Going to milestone this for now because I think we need to come to a conclusion on how to handle snaking. Likely by fixating the hit position until hit or otherwise, even when `snaking out` is enabled. I have no issues with doing this as long as it looks visually convincing (which it won't without special attention).
