### ISSUE TITLE
Nightcore not properly syncing with doubletime speed modifier.

### ISSUE THREAD

**Issue by Galakey** [ppy/osu#7536]
**Describe the bug:** The nightcore mod's audio does not sync up correctly with doubletime when the speed has been modified.
**Screenshots or videos showing encountered issue:** https://youtu.be/p3LgsqxJnn8
**osu!lazer version:** 2020.112.0

**Comment by LanTenDragon** [comment]
@Galakey Your video is set to private.

**Comment by Galakey** [comment]
@LanTenDragon Sorry, fixed,

**Comment by smoogipoo** [comment]
I don't understand, it seems to be syncing up perfectly in the video.

**Comment by bdach** [comment]
Closing - as far as I can see there's no issue here.

**Comment by Firmatorenio** [comment]
I experience this problem quite strongly, the samples that Nightcore adds are significantly off-sync (late) with the song in play. Here's my video, maybe it'll be more audible there: https://www.youtube.com/watch?v=dc-oBGSIVbQ

I also notice this problem in the sample played when you hover over the osu! logo in the main menu, when it pulses to the music's beat, it's slightly delayed there too.

**Comment by peppy** [comment]
Probably covered by https://github.com/ppy/osu/issues/8774

**Comment by Firmatorenio** [comment]
I would think that one issue is more about the relation of overall audio to input, while here it's relating the song audio track to the nightcore added layer, which should be synced perfectly as if they were one track even before adding NC. Again, this issue I have doesn't seem to be affected by the universal offset, like the one in the linked issue.
