### ISSUE TITLE
Ram Consumption and Battery Drainage

### ISSUE THREAD

**Issue by StrageFaithApernum2019** [ppy/osu#7539]
The Issue so far Discovered are already Common to My Computer and so far there is a Major issue to both of them

1.Ram Consumption
The Ram usually Loads in a good pace in normal Ozu! however in the Current Build of Ozulazer the Ram takes up at around 90% of Ram Capacity to the Point it Lag's the System and it is also Affected if the "Game Bar" of Microsoft Windows is on It increases the Lag to the point you have to shut down the system 

so far I have a Low spec's on My Current Laptop and the Main Issue it Usually Faces is Ram Consumption

2.Battery Drainage
The Battery if "Okay" in a few "Play's" in which I mean 1-2 Hours of Ozulazer can be played in Just 1-2 Hour and again Is you Have a Good Setup it doesn't Affect Anyone and the Difference from Osu! from Osulazer is that the original Unit Takes around 2-3 Hours Maximum while Osulazer takes 1-2 Hours and Both Fully Charged 

so Far It is my Concern however it depends if anyone would like this for the Osulazer Build

Computer: Lenovo Ideapad 320-14ISK | Intel i3 | 1TB Storage | 22GB Sub-Storage | 4GB Ram (Not a Replaceable Kind)

Link to Computer Type:
https://ph.priceprice.com/Lenovo-Ideapad-320-14ISK-24249/
https://pcsupport.lenovo.com/ph/en/products/laptops-and-netbooks/300-series/320-14isk

STRage FAITH APERnum

**Comment by enoslayd** [comment]
Performance wise, I think it will improve in the future

**Comment by bdach** [comment]
As stated above, performance issues are a constant consideration on all platforms. We're aware of problems in that area, but your report is not really actionable, as it is too general. Closing for now; please continue to watch this space for future performance improvements.

**Comment by peppy** [comment]
To get more battery life you may want to consider setting the frame limiter to vsync.
