### ISSUE TITLE
Osu!lazer doesn't respect skin's AnimationFramerate

### ISSUE THREAD

**Issue by power9maker** [ppy/osu#7547]
Basically if you have in your skin's skin.ini file parameter "AnimationFramerate" osu doesn't respect it and plays animations in the speed it wants.

**Comment by RBRat3** [comment]
This will have to get pretty specific to certain sprite elements as stable didn't respect it for a lot of other things for good reason, it's pretty much standard and HUD specific so it's a good place to start.
