### ISSUE TITLE
Pause/Resume for beatmap import from osu!stable

### ISSUE THREAD

**Issue by ylight67** [ppy/osu#7551]
**Describe the new feature:** For some reason, importing about ~16.000 beatmaps from osu!stable takes many hours long, so even if it can't be done in a smoother way, it'd be nice to be able to pause import and resume later. Having the progression saved to continue the next time I run my PC (and osu!Lazer as well), would be the handiest.

**Proposal designs of the feature:** 'Pause Import' button and 'Resume Import' button

**Comment by peppy** [comment]
It actually does "save" - the second time should generally run much faster.

We could further improve this by avoiding the online lookups as a flag for import-from-stable (as it used to be).

**Comment by ylight67** [comment]
Maybe I did something wrong somehow. I tried several times, but it always starts from 0. Talking about the clean stat of first run, when there's no beatmaps at all, so it offers to import from osu!stable and I accept it.

Also in case online lookups are like, a "safer" function, to avoid any errors, it could be optional. I don't know much about how that works exactly, just a smartass thought.

**Comment by peppy** [comment]
It will start from zero but skip the expensive portions of the import (it can see that the beatmaps already exist in lazer). The online lookups are likely the limiting factor, but we do have plans on improving this process.

**Comment by ylight67** [comment]
I see. Thank you for looking into this issue so quickly and for the explanation as well! I guess it can be considered resolved, so I close this topic, if you don't mind.

**Comment by peppy** [comment]
Fine to keeep open ti track the issue.

**Comment by peppy** [comment]
Closing in favour of https://github.com/ppy/osu/issues/8265.
