### ISSUE TITLE
Low Performance

### ISSUE THREAD

**Issue by tsunadegodaime** [ppy/osu#7552]
**Describe the bug:** 
4x times lower performance compared to osu!stable.
**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/5mI1UXn.png
https://i.imgur.com/R6GRys4.jpg
**osu!lazer version:** 
2020.112.0

**Comment by peppy** [comment]
We are constantly working on performance. The particular case you point out likely will be improved by hit object pooling or otherwise.
