### ISSUE TITLE
mouse drifto

### ISSUE THREAD

**Issue by creeperskinmaker1** [ppy/osu#7553]
when opening my mouse starts to drift
using kubuntu launching thought lutris

https://youtu.be/HJK80hoOj3o

**Comment by enoslayd** [comment]
Try turning off raw input (ctrl+r might help?)

**Comment by creeperskinmaker1** [comment]
Yeah, that helped. What does raw input even do?

**Comment by peppy** [comment]
You can read more about raw input here:  https://docs.microsoft.com/en-us/windows/win32/inputdev/about-raw-input

This issue is being tracked [framework side](https://github.com/ppy/osu/issues/3489)
