### ISSUE TITLE
Where is the build binary?

### ISSUE THREAD

**Issue by Lockna** [ppy/osu#7560]
Hi! i'm using arch linux and builded it succesfully, it started and worked fine. But when I closed it and wanted to restart it, I was't able to find the build binary or a method to start it. Sorry for using a feature request...

**Comment by peppy** [comment]
maybe you want the (unofficial) package https://aur.archlinux.org/packages/osu-lazer/

you may also build a binary yourself using `dotnet publish -r linux-x64`.

**Comment by Lockna** [comment]
Thanks
