### ISSUE TITLE
Different backgrounds for each mod in the map

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#7565]
I believe that a new part of skinning may be the ability to set different backgrounds for each individual mod (to choose) when creating a map, which could more clearly show what kind of "difficulty" the action is taking.

**Proposal designs of the feature:** 
You can change not only the background color, but also the color of the notes.

**Comment by peppy** [comment]
This sounds over-the-top to me. We're designing mods to be modular so a beatmap should not be aware of what mods are applied.

**Comment by Moltanicaa** [comment]
> This sounds over-the-top to me. We're designing mods to be modular so a beatmap should not be aware of what mods are applied.

Maybe then just for the viewer mode? It seems to me that with a proper approach from the mapper, this can add epic

**Comment by smoogipoo** [comment]
As mentioned, mods have to be beatmap agnostic. And such mods as proposed (in a beatmap-agnostic fashion) are out of scope of what we want to achieve from lazer.
