### ISSUE TITLE
Default key clash in mania's dual stage mode

### ISSUE THREAD

**Issue by MikelJohnson** [ppy/osu#7575]
In osu!mania's dual stage mode special key is set to tilde by default

![image](https://user-images.githubusercontent.com/40336919/72733701-68ae8100-3ba9-11ea-9f35-d90e184baff5.png)
master: 1/20/20

**Comment by peppy** [comment]
@MikelJohnson in general what would you expect the default bindings to be here? It seems like it should be somewhere between the two finger rows for each player (so maybe W or S in the left player's case?)

**Comment by MikelJohnson** [comment]
Probably S for the left player. I'm not sure about the right one though. For some reason the second row is directly below the first one, so it needs be lowered. (`M` `<` `>` `?` I guess?)
