### ISSUE TITLE
FPS drops on beatmaps that are very long

### ISSUE THREAD

**Issue by nipunjamewar** [ppy/osu#7578]
Bug: I get heavy FPS drops on beatmaps that are 50+ minutes long. This doesn't happen in stable.

Video: https://youtu.be/eqloez-oYeE

osu!lazer version: 2020.118.0

PC Specs: [specs.txt](https://github.com/ppy/osu/files/4087300/specs.txt)

Logs:
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4087326/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/4087327/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4087328/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4087329/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/4087330/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4087331/updater.log)
[database.log](https://github.com/ppy/osu/files/4087332/database.log)
[network.log](https://github.com/ppy/osu/files/4087333/network.log)
[performance.log](https://github.com/ppy/osu/files/4087334/performance.log)

**Comment by bdach** [comment]
The video you've attached is private and therefore cannot be viewed by anyone but you.

Long beatmaps are known to cause issues (#5045), which are likely to be resolved with #6136.

**Comment by nipunjamewar** [comment]
Ah my bad! I made the video unlisted. So I see this is a known issue. Thanks for replying this quick.

**Comment by swoolcock** [comment]
Closing as duplicate.
