### ISSUE TITLE
Refactor mod customization container show/hide logic

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7579]
**Describe the new feature:** Currently the alpha of the container is used to determine whether the container is hidden. This is unfriendly if we are going to animate the container.

I propose hereby that whether the container is shown should be decoupled from its alpha to ease animating.

**Comment by LeNitrous** [comment]
The implementation was very minimal to begin with. It would be better to ask for designs as well if refactoring the container is planned.

**Comment by peppy** [comment]
I'm not sure this needs an open issue. A PR would work just as well making it into a stateful container or otherwise.

**Comment by smoogipoo** [comment]
Generally, code quality changes are the lowest of the low priority, and as such we don't need issues for them. They're generally items which will be changed in time (e.g. when required) or via random submissions as people trawl through the code.
