### ISSUE TITLE
Quick change of background songs severely lowers the number of FPS.

### ISSUE THREAD

**Issue by rafalbrozek98** [ppy/osu#7601]
Computer System: Windows 10.
Starting state: Main menu after launching the game.
Steps:
1.	Click a symbol with a note on the top-right side of the screen.
2.	Do a fast change of the songs clicking right/left arrow.
3.	FPS drops.

Results: Fast change of background songs can cause a drop in FPS.
Note: This problem happens often, but now always.

Video: https://drive.google.com/file/d/1cqWK4rjb2BUAIi_3ZIKu0lyAYVfR4eGu/view

osu!lazer version: 2020.118.0

**Comment by smoogipoo** [comment]
Performance is a constant work in progress that will improve over time. We're not able/ready to action on this issue yet.
