### ISSUE TITLE
Moving timestamp of a background song to the end stops the music with “play” button enabled.

### ISSUE THREAD

**Issue by rafalbrozek98** [ppy/osu#7602]
Computer System: Windows 10.
Starting state: Main menu after launching the game.
Steps:
1.	Click a symbol with a note on the top-right side of the screen.
2.	Click and hold the timestamp slider with the left mouse click.
3.	Drag it to the end of the song.
4.	Drag it back to some earlier timestamp.
5.	The song doesn’t play sound. The “Play” button is enabled.

Results: Background song bugs when we drag the timestamp slider to the end.
Note: Clicking “Pause” and then “Play” again solves the problem. 

Video: https://drive.google.com/file/d/1iAkUdTiYHV7KuMcKObA3-PwLH_hRvdCS/view

osu!lazer version: 2020.118.0

**Comment by Joehuu** [comment]
Closing in favor of https://github.com/ppy/osu/issues/9398.
