### ISSUE TITLE
Disabled “Show menu cursor in screenshots” option doesn’t make the cursor disappear at screenshots.

### ISSUE THREAD

**Issue by rafalbrozek98** [ppy/osu#7603]
Computer System: Windows 10.
Starting state: Main menu after launch.
Steps:
1.	Go to “settings”.
2.	Disable “Show menu cursor in screenshots”.
3.	Create a screenshot (F12).
4.	Open the file.
5.	The cursor is still on the picture.

Results: Option does not work properly.

Video: https://drive.google.com/file/d/1OCuVhT7woVJoadC2I3tw22bj1YWsJyZT/view
Screenshot taken right after the video ^: 
![Issue 8 screenshot](https://user-images.githubusercontent.com/47181218/73063107-4f098400-3e9e-11ea-997e-f4c909933486.jpg)

osu!lazer version: 2020.118.0

**Comment by peppy** [comment]
Can't repro on mac. Possibly operating system or setting specific?

**Comment by smoogipoo** [comment]
100% replicable on any OS.
