### ISSUE TITLE
HP drain is not on par with osu!stable

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#7606]
**Describe the bug:** The HP drain implementation in osu!lazer is not on par with osu!stable. (please see the video linked below first)

osu!lazer drains at times where there is nothing to hit, for example right after breaks but the first note shouldn't be hit yet (first half of video), or when notes are timed far apart (second half of video). osu!stable already accounts for these cases.

Another issue I think is present is that osu!lazer is too strict and drains too much at times (also second half of video), though this might be intentional.

**Screenshots or videos showing encountered issue:** https://youtu.be/h8W84EqYhh4 (first HP bar is lazer's, second HP bar stable's)

First demo: https://osu.ppy.sh/beatmapsets/668236#osu/1413768 [Desperate Tears difficulty], autoplayed

Second demo: https://osu.ppy.sh/beatmapsets/925999#osu/1941890 [Sotarks' Emotions difficulty], with replay file https://drive.google.com/file/d/1q5n0P7YbK_RDnG2FuPby_fzUgEZ34Uya/view?usp=sharing

**osu!lazer version:** master branch commit 9be3d7a16171ca4dbe15b0ad3689c4f18f35ae2c

**Comment by smoogipoo** [comment]
Please note that HP drain in lazer and stable are intended to be different. Lazer is greater simplified to a point where it can be explained as percentage HP targets (see: https://github.com/ppy/osu/blob/9be3d7a16171ca4dbe15b0ad3689c4f18f35ae2c/osu.Game/Rulesets/Scoring/DrainingHealthProcessor.cs#L80).

Besides that, drain rate being too harsh and drain happening during non-play sections should both be addressed and both are separate issues.

Please make an issue thread for each of those if you still feel like they are issues.
