### ISSUE TITLE
HP drains in non-play sections

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#7607]
**Describe the bug:** In osu!lazer, HP drain occurs in non-play sections, like right after a break or after skipping the beginning of the song but before the first note was hit.

This may be an issue that occurs in sections like before a break but after the last note, but I have not tested that yet.

**Screenshots or videos showing encountered issue:** https://youtu.be/lzn6P9MOdG4
Notice that osu!lazer immediately drains HP after the break, but osu!stable only drains upon hitting the first note.

**osu!lazer version:** master branch 52b66fdc167059ca0336dde474e2ee84073d04b1

**Comment by peppy** [comment]
We already have this correct for the start of the beatmap, but seemingly not after resuming from a break.

**Comment by kornkaobat** [comment]
Maybe ` if (!IsBreakTime.Value) ` can be added with `if (!IsBreakTime.Value && osucurrent.Hitobject is Hit) `of some sort? I don't know the wordings of the code though.
File : ...\osu\osu.Game\Rulesets\Scoring\DrainingHealthProcessor.cs Line 63

**Comment by smoogipoo** [comment]
There's no concept of a "current" hitobject in a health processor.

**Comment by kornkaobat** [comment]
`if (!IsBreakTime.Value && beatmap.HitObjects[0].StartTime <= Time.Current)`
Is this okay now?

**Comment by smoogipoo** [comment]
It's not. Please test for yourself before posting.
