### ISSUE TITLE
Alt+[number] combination, in Chat Overlay, starts from number 2

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#7608]
**Describe the bug:** (Use the image below as the example for this explanation)

When I press <kbd>Alt</kbd>+<kbd>2</kbd>, it opens `#announce`; <kbd>Alt</kbd>+<kbd>3</kbd> opens `#italian`, etc.
So it seems like it's skipping the number 1.

**Screenshots or videos showing encountered issue:**
![chat](https://user-images.githubusercontent.com/43073074/73098297-6457d000-3ee9-11ea-8fe2-73917e81c4fa.png)

**osu!lazer version:** 2020.118.0

**Comment by TheWildTree** [comment]
This regressed because of ppy/osu-framework#3183, the internal item order got switched (the `selectorTab` is now first in the items list), offseting the index of each channel by one.

![image](https://user-images.githubusercontent.com/27722894/73123764-d4229500-3f93-11ea-9b9d-5576ef082d8c.png)
