### ISSUE TITLE
Clicking Alt + F4 in main menu gives different exit dialog than clicking Escape

### ISSUE THREAD

**Issue by power9maker** [ppy/osu#7615]
After clicking Escape:

![Adnotacja 2020-01-25 121401](https://user-images.githubusercontent.com/42269909/73120335-e3dab300-3f6c-11ea-955b-b1dc93038e5b.png)

After clicking Alt + F4:

![Adnotacja 2020-01-25 121445](https://user-images.githubusercontent.com/42269909/73120337-ef2dde80-3f6c-11ea-8ae2-df1aa4e5a5d4.png)

**Comment by Gabixel** [comment]
If you are referring to the background colour, I think that's the expected behaviour when pressing <kbd>ESC</kbd> (it does a little fading animation, and the music volume drops to 0).

**Comment by power9maker** [comment]
Yeah, that's what I meant. But shouldn't it also do that when clicking Alt + F4 so it looks the same no matter what?

**Comment by Gabixel** [comment]
I guess it's possible, but it depends on the design they have in mind.

**Comment by peppy** [comment]
Honestly I don't think this is actionable. Holding escape is a specific hold action which causes the dim. It's going to look different.
