### ISSUE TITLE
Settings window not beeing closed on clicking certain tabs on the top

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#7626]
**Disclaimer** 
Less of a bug more of a quality of life improvement.

**Describe the bug:** 
The settings window is staying open regardless of clicking on the tab icons on the top bar except for the notifications and home icon.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=E8pjZ9KW5ow

**osu!lazer version:** 
2020.118.0 (also 2020.125.0 | latest on report date)

**Comment by bdach** [comment]
I'd say that is intended, at least in some cases. Switching rulesets, for example, should probably not close the settings. As for the other overlays - probably arguable if we want this effect or not.

**Comment by smoogipoo** [comment]
This is intended.
