### ISSUE TITLE
there should be an option to show difficulty for playing on a touchscreen

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#7629]
the suggestion would be to show touchscreen difficulty(switchable in the options) because it would be a good idea to know how hard is it when you play on a touchscreen as opposed to pc

the game will assume that you are playing touchscreen only(and with nothing else)

**Comment by mcendu** [comment]
How to calculate?

**Comment by genericthing** [comment]
i think aim sr should be worth a lot less and high note density(at a normal ar) worth higher sr than normal diff calculation

i don't know how exactly to calculate, it's just a suggestion after all

**Comment by AqilCont** [comment]
Aren't there players who tap with their keys while touching the screen when they need to? This would seriously break the PP and difficulty system for touchscreens. I definitely think that jumps should be nerfed a lot though.

**Comment by smoogipoo** [comment]
GitHub issues for SR calculation require at least some evidence that a reasonable attempt at an algorithm was tried. This isn't the area to start abstract proposals, but rather an area to get such proposals implemented in code.

"jumps should be nerfed", "aim should be worth a lot less", "high note density worth higher", all do not satisfy this, and I'll be closing this issue as such. 

Feel free to start discussions amongst yourselves or inside the #osu-performance discord channel.
