### ISSUE TITLE
OsuSliderBar Tooltip should only use percentage whenever necessary

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu#7640]
Currently the `OsuSliderBar` automatically changes it's tooltip to a percentage when the minimum value is greater than or equal to -1 and maximum value is equal to 1. There are some cases such as https://github.com/ppy/osu/pull/7222 where we want to display the exact value.

The main approach is to use a flag (a boolean) to tell the slider bar when to show the percentage. We can either calculate the percentage regardless of the minimum and maximum values or still limit the minimum and maximum values to -1 and 1 respectively.

Opening this as an issue for visibility and discussion on how to approach said issue.

**Comment by peppy** [comment]
`public bool DisplayAsPercentage { get; set; }` sounds fine. you will need to go through all usages and update them accordingly (and probably re-expose this via `SettingsSliderBar`).
