### ISSUE TITLE
Occasional severe stutter throughout the beatmap

### ISSUE THREAD

**Issue by ishitatsuyuki** [ppy/osu#7646]
**Describe the bug:** 

On occasions, there would be regular stutters that persists until you retry the map. "Stutter" means that the frame time jumps up to like 20ms (I run on VSync but the idea is that the frame time jumps significantly for one frame in 10 or like that). The issue persists after pausing and continuing.

There is no deterministic way to reproduce this yet - which suggest this might be GC related. (2020.125.0 seemed to consistently reproduce this on first play after launch - but after rebuilding to master the issue appears less often.) The computer is running a i7-6500U with clock capped at 1.8GHz on Linux. Resolution is borderless WQHD. The following actions might increase the chance to reproduce:

- Going back to the main menu, and proceed to solo play again.

**Screenshots or videos showing encountered issue:** 

Pardon the lack of videos, the video recording overhead on my laptop is probably too high.

**osu!lazer version:** `01cf417` on Arch Linux

**Logs:** (doesn't really seem interesting, since these spikes are not logged apparently)
[performance.log](https://github.com/ppy/osu/files/4120688/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4120689/runtime.log)

**Comment by peppy** [comment]
That is how vsync works. Frames will run at 33ms if a 16ms frame is missed.

Please test on a different frame limiter and provide screenshots of the frame time graph when this occurs.

**Comment by ishitatsuyuki** [comment]
It's not exclusive to VSync; it's visible at 120fps cap and the notes jump with the spike pretty similarly.

Here you go, the graph:

![Screenshot from 2020-01-28 13-57-43](https://user-images.githubusercontent.com/12389383/73236646-7af67380-41d6-11ea-9ce7-e5b6d9c9ad3f.png)

**Comment by peppy** [comment]
osu!mania has known performance issues. These will be solved as we continue development.
