### ISSUE TITLE
Hide home button when already at main menu

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#7657]
**Describe the new feature:** 
This would enable the home button in the toolbar to hide itself when you’re already at the main menu. Clicking it while already at the main menu does nothing, therefore I feel it should be hidden 

**Proposal designs of the feature:** 
Hide home button when at main menu
![1BB591F3-C585-4C63-9D9B-BCCD144EEC6F](https://user-images.githubusercontent.com/10524728/73309439-74202e80-41df-11ea-8de6-82511b5fb5e2.jpeg)

**Implementation**
I might have made a PR for this as I’ve made a build with this functionality but my code is a mess and barely functions. I feel someone with actual skill should make a PR with well made, commented and laid out code.

**Comment by TheWildTree** [comment]
Probably best to simply disable it instead of hiding when we're at the main screen, since it would cause the ruleset buttons to change positions, which doesn't sound like good UX if someone was to use them often - or if we prevented the movement, would leave ugly empty space behind which wouldn't be good either.

**Comment by bdach** [comment]
It's not entirely true that the home button has no purpose at the main screen - if any overlays are open, clicking it on the home screen will hide them. Whether that was intended I don't know, but for that reason I'm opposed to removal as it *is* a useful feature, and I'm not sure disabling is worth the effort.

**Comment by peppy** [comment]
I think it's fine as-is personally.

**Comment by smoogipoo** [comment]
We may reconsider this at some point in the future, but I also think it's fine as-is.
