### ISSUE TITLE
Skin support for iOS and Android osu!lazer

### ISSUE THREAD

**Issue by Inkninjaaa** [ppy/osu#7658]
There can be a specific file titles osu!lazer with skins, songs, and replays.

It can be useful for people who do skinning for others enjoyment as I've put 2 skins in the r/osuskins discord and it can be helpful to test them in Lazer.

**Comment by smoogipoo** [comment]
Are you going to be looking into this one yourself? We are generally not accepting mobile issues right now otherwise.

**Comment by ThatsNiceGuy** [comment]
if you’re referring to having game files organized like osu!stable then that isn’t gonna be a thing on lazer.
it uses its own way of storing stuff so you can’t just drop files in folders and have them load on next game start.

**Comment by peppy** [comment]
Going to close this one for now as it's already possible to import on iOS and there's an open issue to resolve this for android (it may already be resolved) https://github.com/ppy/osu/issues/6525
