### ISSUE TITLE
Lack of audio output (Arch Linux)

### ISSUE THREAD

**Issue by Clayative** [ppy/osu#7672]
**Describe the bug:** 
Osu!lazer fails to output any audio, but after looking through logs and similar issues I can't seem to figure out why. Originally, osu could not start at all until I changed `IntroSequence` to `Circles` in `game.ini` as I saw in #5866 , so now I can at least get into the game. Everything seems to me like it should work, but I probably just don't know enough.

It at least seems like it is making an effort to output audio though. pavucontrol shows an `ALSA plug-in [dotnet]` output stream, but it remains entirely inactive. This in itself seems wrong as it should be using PulseAudio, but since I have `pulseaudio-alsa` ALSA should work enough. Changing output devices in osu!'s output settings does not resolve the issue, except that rarely when changing devices from anything else to my headset, a fraction of a second of audio is able to play before stopping.
**Screenshots or videos showing encountered issue:** 
N/A due to this issue being an audio one.
**osu!lazer version:** 
2020.125.0 (the version in the AUR as osu-lazer, but it is important to note that the same issue is present when installing from osu-lazer-git)
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/4132094/runtime.log)
[performance.log](https://github.com/ppy/osu/files/4132095/performance.log)
[network.log](https://github.com/ppy/osu/files/4132096/network.log)
[database.log](https://github.com/ppy/osu/files/4132097/database.log)

Thank you!

**Comment by huupoke12** [comment]
Can you try deleting the osu!lazer folder in `~/.local/share/osu` and uninstalling `pulseaudio-alsa` and see if it works?

**Comment by Clayative** [comment]
That was unable to solve the issue, but thanks for the idea.

I've been unable to reproduce the issue in a fresh Manjaro I3 virtual machine (both with and without `pulseaudio` and `pulseaudio-alsa`) which seems to point to my system's configuration being the issue, but I can't figure out how. My Pulse configuration this install around should be entirely default.

Other things I've tried so far:

- Nuking `~/.local/share/osu` multiple times, both with and without `pulseaudio-alsa`
- Removing `pulseaudio-jack`, just in case
- Switching kernels: using `linux` instead of `linux-mainline`
- Recompiling from both AUR packages `osu-lazer` and `osu-lazer-git`

These logs most likely won't be of much use, but I figured there's no harm in providing them:
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4137218/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/4137219/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4137220/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4137221/performance-gamethread.update.log)

**Comment by huupoke12** [comment]
Did you do anything related to PulseAudio and its configuration? Did you follow ThePoon's guide to have low audio latency in osu!stable?

**Comment by Clayative** [comment]
No to the second question. I haven't tried to use osu!stable on this installation. It's fairly fresh, about 2 months old.

Here's a brief rundown of everything I've done with audio on this install:

I've previously messed around with `jack2` which did cause me to disable pulse for a while, but that was the only change I made, and I checked the usual pulse config files against the fresh ones in the Manjaro install I threw together (yes I know Arch and Manjaro are different distros, but I figured that their default pulse configs are probably the same). I did remember to stop autorunning jack when I was done with it.

In addition to that, I have a few pulse modules set to load on login, one `module-null-output` and one `module-loopback` but this shouldn't affect osu! (I've also tried with those modules unloaded).

Finally, I've added `volume-limit = 0.03` to my `/usr/share/pulseaudio/alsa-mixer/paths/analog-output.conf.common` to fix a problem with audio not scaling properly.

**Comment by huupoke12** [comment]
Then try uninstalling `jack`/`jack2`. And you may want to check [Jack article on ArchWiki](https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit) and see if there are problems/workarounds for them, and you can undoing those changes.

**Comment by Clayative** [comment]
I found what was causing my issue, and what do you know the problem was my own fault. I know for certain I didn't make it, but some program I installed must have created a `~/.asoundrc` that caused this whole mess. Removing it allows osu! to play audio as intended. Thanks for your help through this and sorry for making you spend your time with this. Hopefully at least if somebody has a similar issue they can find this.

Closing.
