### ISSUE TITLE
Timeline ticks duplicating

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#7681]
**Describe the bug:** 
Timeline ticks slowly duplicating over time whilst playing a map on the latest update, starts off laggy ends off laggier
https://osu.ppy.sh/beatmapsets/1041976#osu/2177668 (seems to happen on other maps too)
seems to be when the bpm changes mid map

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/33783503/73457282-57186680-436b-11ea-9a31-14c7840d4759.png)
https://youtu.be/EjALzAlTUsc

If it's a long map it gets super bad
![image](https://user-images.githubusercontent.com/33783503/73458342-0570db80-436d-11ea-9c98-9d130846449b.png)

**osu!lazer version:** 
2020.130.0

**Logs:** 
Anyone with a copy of osu!lazer can reproduce this, no need i dont think

**Comment by peppy** [comment]
This is to do with multiple timing points, easy to reproduce.
