### ISSUE TITLE
multi-functional key mod

### ISSUE THREAD

**Issue by Axeanz** [ppy/osu#7684]
Got the idea from [#7125](https://github.com/ppy/osu/issues/7125).

About the mod: it changes the way the keypresses get registered. How?
Pushing it in counts as a hit, holding it down counts as an hold. Releasing also counts as a hit and keeping your key untouched also counts as a hold. So any change in the key's state counts as a quick press. This would mean that in theory, you can play anything, including stream-maps, with just 1 key.

No idea if this is possible, but still an idea I felt like suggesting.

**Comment by peppy** [comment]
I don't really understand what your proposing here

**Comment by bdach** [comment]
If I understand correctly, the proposal is to affect key input in the way depicted in the following screenshot:

![image](https://user-images.githubusercontent.com/20418176/73609588-86c7a880-45cf-11ea-8953-91a898a72c37.png)

In other words, circles wouldn't respond to key down events, but keypress state change events (in signal processing terms, a click wouldn't be a rising edge, but any edge).

**Comment by mcendu** [comment]
From a mania player's perspective, this mod can turn e.g. a 1/8 note jack into a 1/4 jack of 1/4 holds

**Comment by peppy** [comment]
I see. Would need a name that describes this better.
