### ISSUE TITLE
Leak GPU uses 

### ISSUE THREAD

**Issue by MicRy2578** [ppy/osu#7694]
![Screenshot_2020-01-31-18-10-52-701_sh ppy osulazer](https://user-images.githubusercontent.com/58900147/73550243-d21a7380-4476-11ea-95cd-078a1f60ec45.jpg)
![Screenshot_2020-01-31-18-10-41-860_sh ppy osulazer](https://user-images.githubusercontent.com/58900147/73550244-d21a7380-4476-11ea-8d31-ba0093b584a1.jpg)
![Screenshot_2020-01-31-18-09-47-089_sh ppy osulazer](https://user-images.githubusercontent.com/58900147/73550245-d2b30a00-4476-11ea-9d88-2335426d4aa3.jpg)
![Screenshot_2020-01-31-18-07-27-613_sh ppy osulazer](https://user-images.githubusercontent.com/58900147/73550246-d2b30a00-4476-11ea-9119-7c098b2f1fc5.jpg)
![Screenshot_2020-01-31-18-17-40-648_sh ppy osulazer](https://user-images.githubusercontent.com/58900147/73550247-d2b30a00-4476-11ea-836c-a4e65e624d64.jpg)

**Describe the crash:** 
GPU uses increased when startup the game for the first time launch the new version and crashed after playing it for more than 40 minutes
The previews version only took 54% - 80% of GPU but now it takes a lot than it should be

**osu!lazer version:** 
osu!lazer 2020.130.0
**Logs:** 

**Phone Specifications:** 
https://www.google.com/amp/s/m.gsmarena.com/xiaomi_redmi_7-ampp-9498.php

**Comment by smoogipoo** [comment]
There have been no changes to graphics recently. This is likely an issue with your device.

Please go back a few versions and try to trace the first version that the issue occurs on.

**Comment by peppy** [comment]
i also noticed a slight performance drop on iOS, though i don't have specific metrics to back it up.

**Comment by MicRy2578** [comment]
i tried the previous version from 2020.125.0 until 2020.112.0 
and the best one with great performance is 2020.125.0
So for now, i'll use this version until there is a better version

**Comment by tsunadegodaime** [comment]
> 
> 
> i also noticed a slight performance drop on iOS, though i don't have specific metrics to back it up.

I have Honor 9x with kirin 810 soc (310k antutu) and I've set screen resolution of the device to 720p, disabled all interface elements and osu!lazer still manages to lag alot on hard maps with like 7+ stars. Drops to 30-40fps everytime.

**Comment by smoogipoo** [comment]
This issue isn't about FPS drops. We're generally not interested in performance for now as it'll improve over time and mobile is not our current focus.

This issue is about an FPS decrease since 2020.125.0.

**Comment by peppy** [comment]
From my end: I did update all xamarin components for this build, so there may have been some change there. Before investigating further we need confirmation from more users that this issue exists, though.

**Comment by tsunadegodaime** [comment]
> This issue is about an FPS decrease since 2020.125.0.

> we need confirmation from more users

I've tested previous version 2020.125.0 and I'm pretty sure it runs better than 2020.130.0

**Comment by ThatsNiceGuy** [comment]
on an lg v30+ us998 running Android 10 (snapdragon 835 4gb ram), i have noticed that performance is a bit worse than earlier releases.
iPad Pro 11” feels unchanged with maybe a bit more heat and battery drain.

**Comment by peppy** [comment]
The only this useful to post in this thread are actual benchmark statistics done in consistent environments. Don't need "feels like" reports.
