### ISSUE TITLE
[Possible Bug] Orientation of application does not remain in landscape mode

### ISSUE THREAD

**Issue by rhearmas** [ppy/osu#7696]
# Observations
**Expected result**: the application remains in horizontal mode.
**Actual result**: application is able to be rotated into any orientation, whether it be landscape or portrait mode.

# Notes for the developers
- I do _not_ have any knowledge of the coding language used here (C#, if I’m correct), so reporting this through here was my best option.
- I wasn’t sure if this was an intended mechanic; if this was intentionally implemented, feel free to close this issue.

# Device Information
- Model: iPhone 11
- Software version: iOS 13.3
- osu!lazer version: [Release 2020.130.0](https://github.com/ppy/osu/releases/tag/2020.130.0) (latest version at the time of this post)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bdach** [comment]
Thanks for the report, however this has been requested before at #4394; closing as duplicate.
