### ISSUE TITLE
Score multiplier remains the same on speed-adjusting mods even when reduced

### ISSUE THREAD

**Issue by 12beesinatrenchcoat** [ppy/osu#7698]
**Describe the bug:** 
Not entirely sure if you could call this a bug, but this really shouldn't happen...
Whenever you enable a speed-adjusting mod, (Double Time, Nightcore, Half Time, Daycore) you get options to customize the amount it speeds up / slows down the beatmap.
However, no matter how much you speed up / slow down the beatmap, the score multiplier remains the same - so if you were to play a map with Nightcore, but sped up by only 1.01x, you would have the same multiplier as someone playing with 2.0x speed. (multiplier for both is 1.12x.)

**Screenshots or videos showing encountered issue:** 
https://youtu.be/tJbYDlbXIGE 

**osu!lazer version:** 
2020.130.0

**Logs:** 
uhhhhh

**Comment by bdach** [comment]
This is actually something to consider for all customisable mods I suppose ([similar questions have already been raised](https://github.com/ppy/osu/pull/7331#issuecomment-569271039)). I'm unsure of the team's stance about this, but I'd consider it largely unimportant until time for score submission rolls around.

I suppose a sliding linear scale could be used at least temporarily, but I'm not sure if I want to open that kind of discussion right now.

**Comment by peppy** [comment]
I wouldn't be against adding a temporary linear scale, but no further consideration should be given just yet.
