### ISSUE TITLE
Nightcore + Wind Up = Pain

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu#7699]
**Describe the bug:** 
This seems very similar to #3189, but I'm opening a new issue anyways because this one involves the Wind Up mod.
When playing with Nightcore (with Speed increase at 2.0x) and Wind Up (Final Rate 2.0x), you get audio that's... very crispy? It's quite bad in gameplay.

**Screenshots or videos showing encountered issue:** 
It also causes this very nice circle visualizer:
![Screenshot from 2020-02-01 00-19-09](https://user-images.githubusercontent.com/25379179/73587458-17946c00-448a-11ea-81ff-027f94eedc78.png)

[Video Gameplay: https://streamable.com/bnu8x](https://streamable.com/bnu8x) (Bug occurs approx. 1:04 in video)

**osu!lazer version:** 
2020.130.0

**Logs:**

**Comment by LeNitrous** [comment]
Not sure if the mod combination is allowed to begin with. I can't replicate it on master.

**Comment by Craftplacer** [comment]
I agree with OP, the audio quality is degraded.

> Not sure if the mod combination is allowed to begin with. I can't replicate it on master.
It's possible.

I'm not sure if the speed even changes correctly.

**Comment by Craftplacer** [comment]
After giving my response more thought, it possible can be because of the forced pitch from NC, that the audio sounds a bit more crispy if played on both mods.

**Comment by bdach** [comment]
Probably shouldn't be a valid mod combination in the first place, and possibly should allow WindUp/Down mods to affect pitch.

**Comment by MishterKirby** [comment]
> Probably shouldn't be a valid mod combination in the first place

I personally think it should be a valid combination, as I can see it being used for fun, or even just for the challenge.

**Comment by frenzibyte** [comment]
It seems like a combination that's naturally incompatible, but I would suggest for these cases that you open a **discussions** thread with enough details about why it should be valid then it can be potentially considered.
