### ISSUE TITLE
Difficulty above 10.1 Stars doesnt show up

### ISSUE THREAD

**Issue by xCamper** [ppy/osu#7708]
Difficulty above 10.1 Stars doesnt show up

![Osu Lazer Bug1](https://user-images.githubusercontent.com/60553978/73598590-9ba62c80-453a-11ea-8572-ce86cf88bbae.png)

**osu!lazer version: 2020.130.0 **

**Comment by bdach** [comment]
That is incorrect. 10.1 is just how the `no limit` setting value is persisted in the configuration files. See:
https://github.com/ppy/osu/blob/52b66fdc167059ca0336dde474e2ee84073d04b1/osu.Game/Configuration/OsuConfigManager.cs#L27
and
https://github.com/ppy/osu/blob/52b66fdc167059ca0336dde474e2ee84073d04b1/osu.Game/Screens/Select/FilterControl.cs#L51-L52

**Comment by xCamper** [comment]
ok and why cant i see them anymore? i looked at settings and it was on 10 today so they must have changed something (last time i played everything was fine ~1 week ago). i set it back to max but my maps 10.1+ dont show up anymore.

**Comment by Aergwyn** [comment]
They actually don't show up though.
![image](https://user-images.githubusercontent.com/27222621/73598658-7b2aa200-453b-11ea-9663-38ec69f809bb.png)
![image](https://user-images.githubusercontent.com/27222621/73598661-81b91980-453b-11ea-9068-8d9394e88197.png)
