### ISSUE TITLE
Discussion over possible ticker/temporary overlay interface

### ISSUE THREAD

**Issue by Craftplacer** [ppy/osu#7713]
**Possible dependents:**
- #5117
- #4811

**Describe the new feature:** 
The type of interface explained in the title should be able to handle managing and tracking incoming tick(er)s, similar to NotificationOverlay.

**Proposal designs of the feature:** 
A feature (e.g. the chat ticker) should be able to specify...
- ... where its ticker is placed
  - maybe forced by the player?
- ... how it looks like (providing a drawable)
- ... make the manging interface remove the old one or append over it(?)
- ... tell the life span of the ticker before invoking to close/fade out it
- ... tell if it's interactable (can steal focus if player clicks on it)

(ticker may refer to one message or thing popping up)

Feel free to give your thoughts on this one and how it should be implemented.

**Comment by peppy** [comment]
Notification toasts and chat ticker are completely different components. I don't think this issue needs to stay open – discussion can continue in the respective issues.
