### ISSUE TITLE
Accuracy formatting is inconsistent

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#7718]
**Describe the bug:** `ScoreInfo.Accuracy` is formatted in different inconsistent ways throughout osu!lazer.

In some places, it is formatted using `$"{value:0.00%}"`, for example: https://github.com/ppy/osu/blob/0759752bb40abce02a0ca228927b3fcfce24cdad/osu.Game/Overlays/Profile/Sections/Ranks/DrawableProfileScore.cs#L185

In some other places, `$"{value:P2}"` is used: https://github.com/ppy/osu/blob/0759752bb40abce02a0ca228927b3fcfce24cdad/osu.Game/Screens/Ranking/Results.cs#L214

This line does it correctly, in line with stable and web, though I would use `P2` instead of `0.00%`: https://github.com/ppy/osu/blob/0759752bb40abce02a0ca228927b3fcfce24cdad/osu.Game/Screens/Select/LocalScoreDeleteDialog.cs#L35

I think it is best if we use the solution above, but pasting `string.Format(...)` anywhere we need to format accuracy seems repetitive. Should we:
- create an extension method on type `double` named `FormatAccuracy`? This makes it rather awkward as it would stutter:
```cs
score.Accuracy.FormatAccuracy(); // repeats "Accuracy"
```
- extend type `double` to `Accuracy` and either add a `Format` or `ToString` method?

**osu!lazer version:** master branch commit 0759752bb40abce02a0ca228927b3fcfce24cdad

**Comment by smoogipoo** [comment]
A util would be fine, imo.

**Comment by peppy** [comment]
Might be best to just expose a property on score `string DisplayAccuracy => $"{Score.Accuracy:0.00%}`
