### ISSUE TITLE
Channel selection popup

### ISSUE THREAD

**Issue by peppy** [ppy/osu#772]
Available channels are already being received by the client. We should make use of this to allow the local user to join/leave channels via a popup dialog (and also a button on tabs).

We also need to store the channels a user is participating in in the config, so it can be restored on startup.

Rough design:

![image](https://cloud.githubusercontent.com/assets/191335/26137554/d48cd0c0-3afd-11e7-8535-e6eca98f67db.png)

**Comment by Jorolf** [comment]
I could give this a try

**Comment by peppy** [comment]
Has since been implemented to completion (https://github.com/ppy/osu/pull/861)
