### ISSUE TITLE
Disk cleanup tool

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7729]
**Describe the new feature:** Over time, beatmaps can pile up on your hard drive and take up a lot of space. I'd suggest adding a cleanup tool that shows you what beatmaps you haven't played in a long time or at all, and then you could check the ones you want to delete and bam, they're gone.
Also, if a mapset has difficulties you don't have downloaded (either because you've deleted only the unplayed difficulties, or it's a WIP mapset getting new difficulties), they could also be displayed, but greyed out (or signified some other way), and by clicking one the client would download it.

**Comment by smoogipoo** [comment]
Way too early in development to consider this just yet. Will probably do something similar with the inclusion of online collections.
