### ISSUE TITLE
Private messaging support

### ISSUE THREAD

**Issue by peppy** [ppy/osu#773]
- Add right-aligned tabs to handle PMs.
- Add ability to start PMs via command or by clicking a username.

Rough design:

![image](https://cloud.githubusercontent.com/assets/191335/26137576/0c1887aa-3afe-11e7-83be-6eea710fe0cf.png)

**Comment by tsbreuer** [comment]
Should the selected chat channel be kept highlighted while opening a PM chat, or is that a design mistake on the image?

**Comment by peppy** [comment]
looks like a lazy mistake

**Comment by miterosan** [comment]
What's about closing the tabs? Where should the close button be?

**Comment by peppy** [comment]
Same place at it is on other tabs (only when expanded).

Not sure what you mean by colours of permission groups. Colours are sent with users.

**Comment by StartForKillerMC** [comment]
Can i help?

**Comment by naoey** [comment]
can be closed?

**Comment by peppy** [comment]
Closing for now. There's still a few features missing but everything in this issue has been completed.
