### ISSUE TITLE
Rumble support

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7736]
**Describe the new feature:** Having a gentle rumble would be nice when the player hits a finish, or a large note in Taiko for controller and mobile users.

**Comment by peppy** [comment]
Our focus is on desktop, and I do not foresee this being implemented in the near future so going to close the issue for now. Note that this doesn't mean we won't eventually consider adding this. It will probably be exposed/consumed as part of https://github.com/ppy/osu/issues/4113.
