### ISSUE TITLE
ResumeOverlay and FrameStabilityContainer should not be in DrawableRuleset

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#7737]
Only opening this for discussion about the disadvantages of this proposal as **I'll be working towards fulfilling it**.

Dependency for #7702 

This would allow adding frame-stable-required components without them being affected by the gameplay scaling container (see [`Player.cs`](https://github.com/ppy/osu/blob/e119040d5d3b09651e45dda703cb921852236ac5/osu.Game/Screens/Play/Player.cs#L196-L204) and [`DrawableRuleset.cs`](https://github.com/ppy/osu/blob/e119040d5d3b09651e45dda703cb921852236ac5/osu.Game/Rulesets/UI/DrawableRuleset.cs#L182-L196))

Also has small benefits (mostly code quality):
 - Removes `FrameStablePlayback` boolean as it is unnecessary anymore.
 - `ResumeOverlay` will never be created for any usage of `DrawableRuleset` other than `Player` (e.g. `DrawableEditRulesetWrapper`)
 - It mostly doesn't make sense for `ResumeOverlay` not being alongside `PauseOverlay`. (at least for me)

But unfortunately, it has problems that need to be discussed: 
 - The `ResumeOverlay` needs to have its own input manager to control it, that would require exposing `DrawableRuleset.CreateInputManager()` into `protected internal` visibility at minimal, is that a fine thing to go with for now?
 - `DrawableRuleset.CreatePlayfieldAdjustmentContainer()` is required for perfectly scaling the `ResumeOverlay` to the `Playfield`, which means another usage has popped up for a method that shouldn't be public.

**Comment by peppy** [comment]
In discussion, `FrameStabilityContainer` is in the correct place (it is basically *required* for `DrawableRuleset` to operate correctly, thus should be part of it). We can reassess this when we get to having multiple `DrawableRuleset`s displaying alongside each other, and any potential synchronisation that needs to be performed between them (potentially via `FrameStabilityContainer` DIing any available parent `FrameStabilityContainer` and synchronising to it).
