### ISSUE TITLE
scorebar-bg gets overlapped by numbers (layer bug)

### ISSUE THREAD

**Issue by OGValiente** [ppy/osu#7744]
**Describe the bug:** So I have this custom scorebar-bg overlay that I use for hiding the accuracy/score area to prevent any possible distractions. I don't disable all the UI because I'm using the play area borders aswell. However in CuttingEdge, the numbers started to get drawn on the front layer, don't know if this is an intentional change or a bug, decided to report here anyway.

Also, the bug remains in "Cutting Edge 20200203" but it first occured way before than this version.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/44140291/73980582-99304200-4941-11ea-8432-1479fa7ead47.png)

**osu version:** Cutting Edge 20200203

**Logs:**

**Comment by bdach** [comment]
This is the wrong place to be reporting stable issues. Please see [ppy/osu-stable-issues](https://github.com/ppy/osu-stable-issues/) instead.
