### ISSUE TITLE
Can't import maps from another disk

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu#7748]
Describe the bug: I can't import maps if they are on another disk

Screenshots or videos showing encountered issue: 
https://mega.nz/#!JVdzECxI!GsDgr6TcgBJi4p7yUIdos6XgFrwo6OY2AiTjqk4yjJg

osu!lazer version: 2020.130.0

**Comment by smoogipoo** [comment]
Custom beatmap directories do not work yet. Closing as this is mentioned in https://github.com/ppy/osu/issues/3763
