### ISSUE TITLE
Giant Notes

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [ppy/osu#7757]
**Describe the new feature:** 
This Note is in taiko no tatsujin Wii
**Proposal designs of the feature:** 
https://www.youtube.com/watch?v=xF-FL4Rye3I

**Comment by peppy** [comment]
Thanks for your suggestion! We're still a bit too early on to consider adding new hitobject types, but this may become relevant in the future.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
use clap to use a giant note, after giant note, if clap is used it shows even this is 可(good / 100), old songs that are taiko and if use clap or if the allowed mode is all, then converted to whistle
and if use new combo it stops
