### ISSUE TITLE
Latest release not starting on macOS

### ISSUE THREAD

**Issue by juney2008** [ppy/osu#7772]
**Describe the crash:** when i updated to the new version of osu lazer, the game wont start up anymore.

**Screenshots or videos showing encountered issue:none

**osu!lazer version:2020.208.0

**Logs:none

**Computer Specifications: mac os x 10.15

**Comment by peppy** [comment]
Please provide at very least your operating system version and computer model.

**Comment by juney2008** [comment]
im useing mac os x 10.15

**Comment by peppy** [comment]
You are going to have to provide Console.app output and your computer specifications / model at very least.

**Comment by GSculerlor** [comment]
Same issue on Macbook Pro 2017 Catalina 10.15.3

[console.log](https://github.com/ppy/osu/files/4176512/console.log)

**Comment by peppy** [comment]
Maybe a developer setting I have turned on is allowing me to run it. I've pulled the build for now from automatic updates (still accessible at https://github.com/ppy/osu/releases/download/2020.208.0/osu-maybe-broken.app.zip if anyone wants to test it further).

**Comment by swoolcock** [comment]
Just tested on Mojave 10.14.6 (Late 2015 iMac).

1) Double clicking osu!.app flashes the osu! icon in the dock, then closes
2) `open osu\!.app` from terminal gives: 
`LSOpenURLsWithRole() failed with error -10810 for the file /Users/samah/Downloads/osu!.app`
3) Executing the `osu!` binary in `Contents` gives:
`Failed to create CoreCLR, HRESULT: 0x80004005`
4) Starting the game with `dotnet osu\!.dll` works fine.

**Comment by peppy** [comment]
@smoogipoo noticed that we aren't specifying the [allow-jit](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-jit) entitlement, which is likely causing this to occur.

**Comment by juney2008** [comment]
maybe this could be patched on the next Latest release of osu!lazer

**Comment by juney2008** [comment]
i'm going use the old release of osu!lazer for now until this gets patched

**Comment by peppy** [comment]
I've made a new version available. Please test at earliest convenience.

**Comment by peppy** [comment]
Pulling once more, ran into another issue.

**Comment by peppy** [comment]
Back up again, tested to work on two systems.

**Comment by juney2008** [comment]
IT WORKS!
