### ISSUE TITLE
Changing beatmap while song select has text filter causes desync

### ISSUE THREAD

**Issue by peppy** [ppy/osu#7774]
![image](https://user-images.githubusercontent.com/191335/74100021-4f2ba400-4b6d-11ea-804f-824642abe5e6.gif)

- Enter song select
- Enter a filter which matches no beatmap
- Change beatmap from playlist
- Delete filter

Observe:

- Wedge showing no beatmap selected
- Carousel showing one beatmap selected
- Music overlay showing another beatmap selected

**Comment by Gabixel** [comment]
The same can be achieved when you search for a beatmap (so maps are shown with the filter) and you skip to a one that is not visible with the filter. Also, this can be reproduced using the download button from osu!direct and/or user profile, like in this example:

![direct](https://user-images.githubusercontent.com/43073074/74100795-f3442980-4b32-11ea-8fc7-407ce055f0d8.gif)

**Comment by peppy** [comment]
@Gabixel do you know if this has always been the case, or a recent regression?

**Comment by Gabixel** [comment]
I remember that it's not a recent one (probably this has always been the case). To be sure, I just tried for example on [2019.830.0](https://github.com/ppy/osu/tree/2019.830.0). Same result.
