### ISSUE TITLE
Different judgement styles

### ISSUE THREAD

**Issue by LumpBloom7** [ppy/osu#7787]
**Describe the new feature:** 
Allow the use of different judgement displays (Good, Great, etc.) to suit players' needs. This can be applied universally to other rulesets where applicable. This is a purely cosmetic change that only affects the judgement text, as there are mods (such as PF) to make judgements stricter already.

**Proposal designs of the feature:** 
An option to allow players to change the judgement display to one of several different styles(including turning them off). Each ruleset can share a common selection, or be set individually. 

Attached is an example ripped from maimaiDX.
![image](https://user-images.githubusercontent.com/12001167/74157577-79f02800-4c53-11ea-89cd-29cbd5100450.png)

**Comment by LumpBloom7** [comment]
Sorry. Pressed enter prematurely, will fill in details.

**Comment by mcendu** [comment]
Completely accomplishable by skins (without late/fast display) in the case of mania and std. Also as I know there is a pull request for displaying early/late alongside the judgements.

**Comment by LastExceed** [comment]
the above mentioned PR is #7310

**Comment by peppy** [comment]
This will 100% be done via skinning, so I'm going to close this issue for now. The late/early support is, as mentioned above, already in review stages and will be added soon.
