### ISSUE TITLE
Label clean-up

### ISSUE THREAD

**Issue by peppy** [ppy/osu#7796]
Right now it's easy to double-label an issue where one is 100% encapsulated by another (ie. UX issues are always user-interface).

We're looking to give labels a category, from which only one choice should be made at most per issue or PR.

- ruleset
	- ruleset:osu!
	- ruleset:osu!taiko
	- ruleset:osu!catch
	- ruleset:osu!mania
- area
	- area:song select
	- area:main menu
    - area:beatmap
	- area:editor
	- area:gameplay
	- area:skinning
	- area:database
	- area:storyboard
	- area:multiplayer
	- area:results
	- area:diffcalc
	- area:api
	- area:mods
	- area:direct
	- area:social
	- area:chat
	- area:settings
    - area:startup
	- area:tooling
- type
	- type:code quality
    - type:crash
	- type:performance
	- type:testing
	- type:ui
	- type:ux
- platform
	- platform:iOS
	- platform:android
	- platform:windows
	- platform:linux
	- platform:macOS
- special
    - framework fix required
    - good first issue
    - proposal
    - blocked

**Comment by peppy** [comment]
Changes have been applied. Feel free to comment on this issue if anything is not satisfactory.

**Comment by bdach** [comment]
Seeing that my way of labelling has probably been the catalyst for such a change I'll throw in my 2 cents, for what they're worth (which is probably not that much).

I don't have strong feelings about the label system. Thus far I've been using it as something similar to fuzzy tags. The primary example of this was the *user interface* tag, the primary purpose of which wasn't very clear to me, so it became an all-encompassing thing.

I have no qualms about using a category system to make visible a sort of Cartesian product in the labelling space by making clear what label corresponds to which category.

On the other side I kind of disagree with the premise of having only one label from each category per issue, as there could be issues or PRs spanning multiple or sort of "stuck-in-between" areas. What do I do if I get ie. an issue about persisting mod info to the database? Which area do I choose?

I see the point that the previous system did introduce some noise when trying to do stuff with the labels, but I'm not sure that can be 100% avoided. We could definitely iterate on the signal-to-noise ratio by making labels as disjunct from each other as possible (which this described split is a step towards).

**Comment by peppy** [comment]
For mod info -> database I'd choose database, fwiw.

**Comment by smoogipoo** [comment]
I'd also choose `database`, but I'd also be fine with `mods` equally as much. Let's see how categorising goes and we can adjust if it turn out to not be a good fit.

**Comment by bdach** [comment]
I can see how *database* would be a priority in that case. Maybe it was a bad example, but I can't conjure up a more ambiguous one on the spot, which might mean I'm worrying about an issue that doesn't matter in practice.

Let's try this out for now, I'll see how the labeling goes and how often I'm forced to make an educated guess on the proper set of labels, and see what changes might be helpful from there.
