### ISSUE TITLE
Music playlist crashes with async beatmap imports

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#7798]
See: https://ci.appveyor.com/project/peppy/osu/builds/30731352/tests

Since `RearrangeableListContainer` binds to items added/removed on constructor, it may be responding to additions/removals in an async context.

In this case, its `Items` is bound inside `NowPlayOverlay.load()`, which can cause collection changed exceptions if a beatmap is imported during the item addition loop.

One way to fix this is:
1. Make `BeatmapManager` (and all other AMM's) into `Component`s and scheduling their item additions/removals.
2. Move the `ItemsAdded`/`ItemsRemoved` events to `RearrangeableListContainer.LoadComplete()`.
3. Making RLC load components asynchronously inside `LoadComplete`.

**Comment by peppy** [comment]
I believe this has since been resolved (the code in question has been moved out of `load` via https://github.com/ppy/osu/pull/11716
