### ISSUE TITLE
Fatal error when trying to open lazer

### ISSUE THREAD

**Issue by uzervlad** [ppy/osu#7799]
I'm getting this error when trying to start osu! lazer
![image](https://user-images.githubusercontent.com/24654479/74323032-e5daa980-4d95-11ea-9ac7-14c685526af4.png)
![image](https://user-images.githubusercontent.com/24654479/74323066-f4c15c00-4d95-11ea-889f-58f03975b46c.png)

I've seen a few similar issues here, but none of them helped me

-----

Windows Event Viewer info - [events.zip](https://github.com/ppy/osu/files/4191622/events.zip)

**Comment by peppy** [comment]
What GPU?

**Comment by uzervlad** [comment]
![image](https://user-images.githubusercontent.com/24654479/74323785-1c64f400-4d97-11ea-9ed1-495c41efed14.png)

**Comment by bdach** [comment]
Please attach Windows Event Viewer info by performing the following steps:

1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

You could also try running Windows Sysinternals' Process Monitor and checking what throws that return code.

**Comment by uzervlad** [comment]
> 4. On the _Display Information_ popup, select the second option, then the checkbox to show all available languages, then _English (UK)_ (US would also do fine).
I don't have an option for English there, what should I do?

**Comment by uzervlad** [comment]
> You could also try running Windows Sysinternals' Process Monitor and checking what throws that return code.

Not sure what exactly you need, but I found this
![image](https://user-images.githubusercontent.com/24654479/74325078-153ee580-4d99-11ea-91fb-1770b0e8ac0e.png)

**Comment by uzervlad** [comment]
> I don't have an option for English there, what should I do?

Ok, I finally understood my mistake, here's the file
[events.zip](https://github.com/ppy/osu/files/4191622/events.zip)

**Comment by bdach** [comment]
Nothing conclusive in either the event log or attached screenshot of Process Monitor, as far as I can tell. Tough to go forward with nothing concrete to go on.

**Comment by peppy** [comment]
Based on the error, I'd suggest an update of graphics card drivers. It looks like a low-level opengl issue that *hopefully* isn't our fault.

**Comment by uzervlad** [comment]
Definitely is an issue with the drivers. I think osu!lazer should show an error similar to stable instead of that exception message
![image](https://user-images.githubusercontent.com/24654479/75142106-66d56180-5703-11ea-9a7e-782daa6365ef.png)
