### ISSUE TITLE
Scrolling on touchpad not behaving correctly

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#7802]
When scrolling on a touchpad in the osu UI, the window doesn't scroll until the mouse is moved.
Expected: window immediately scrolls instead of waiting to scroll until the cursor is moved.

video: https://youtu.be/tH-jNrAx6DI

version 2020.208.0

harware: intel i5 m520, 4gb RAM (touchpad: synaptics thinkpad ultranav pointing device)

**Comment by bdach** [comment]
Cannot reproduce on `master`, albeit I am on Windows 10. Might be either a Windows 7 quirk or an old device driver.

I seem to remember old Synaptics touchpads used to have some program running in the system tray (also leads to the mouse pointer icon changing) - maybe check if there's one on your system too and try exiting it?

**Comment by Joppe27** [comment]
> Cannot reproduce on `master`, albeit I am on Windows 10. Might be either a Windows 7 quirk or an old device driver.
> 
> I seem to remember old Synaptics touchpads used to have some program running in the system tray (it also caused the mouse pointer icon changing) - maybe check if there's one on your system too and try exiting it?

There isn't any program in the system tray. I did find a synaptics process running in task manager, but ending that process makes it impossible to scroll using the touch pad.

**Comment by peppy** [comment]
Have you tried toggling raw input in osu!?

**Comment by Joppe27** [comment]
> Have you tried toggling raw input in osu!?

When raw input is off, the window scrolls after moving the cursor as mentioned above.
When raw input is on, the window will not scroll at all, even when moving the cursor.

**Comment by Joppe27** [comment]
This has been resolved by switching to SDL. Scrolling works mostly as expected now, it's not super smooth but that can be improved upon later.
