### ISSUE TITLE
User and country names should be italic in the RankingsOverlay

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#7819]
**Screenshots or videos showing encountered issue:** 
lazer:
![osu!_3nwl3w8mca](https://user-images.githubusercontent.com/43358824/74450853-0599cc80-4e7f-11ea-8c97-53f35627181e.png)
![osu!_ESuRTo22wv](https://user-images.githubusercontent.com/43358824/74450875-0af71700-4e7f-11ea-9ade-501a0be551f4.png)
web:
![chrome_HGMYamt2q1](https://user-images.githubusercontent.com/43358824/74450950-25c98b80-4e7f-11ea-99e9-c8ae6e2dbb30.png)
![chrome_YX20yJ545r](https://user-images.githubusercontent.com/43358824/74450954-26fab880-4e7f-11ea-925b-315bc33d6f85.png)

the *filtered by country* country name shouldnt become italic though.

**Comment by peppy** [comment]
this seems so wrong. @arflyte is this intended?

**Comment by arflyte** [comment]
Country names shouldn't be in italics.

**Comment by peppy** [comment]
@arflyte also usernames? everything is italics on live site: https://osu.ppy.sh/rankings/osu/performance

**Comment by arflyte** [comment]
keep the username italics for designs with Exo for now.
