### ISSUE TITLE
Relax mod doesn't work on 2B maps

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#7821]
**Describe the bug:** Relax mod doesn't click like it is supposed to in 2B maps with overlapping sliders.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=teULM3qrmzQ

**osu!lazer version:** master branch commit c1924535fff2bf740663f2fc275561ef191913b6

**Comment by LastExceed** [comment]
[beatmap link](https://osu.ppy.sh/beatmapsets/756794#osu/1605148)
