### ISSUE TITLE
unhandled error after spamming the tabs in the RankingsOverlay

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#7823]
just for reference what i mean by "tabs"
![osu!_AqTvJ05tgO](https://user-images.githubusercontent.com/43358824/74454734-9e7f1680-4e84-11ea-8afb-474b9835fee4.png)

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/4199260/runtime.log)

**Comment by EVAST9919** [comment]
Can't reproduce. Can you provide a video please?

**Comment by EVAST9919** [comment]
Also: no need to create an issue for unmerged pr's. It's better to write it in the pull request itself

**Comment by mouzedrift** [comment]
> Also: no need to create issues for unmerged pr's. It's better to write it in the pull request itself

alright.

> Can't reproduce. Can you provide a video please?

this happened only one time to me and i couldnt reproduce it again. seems kinda inconsistent to me.

**Comment by mouzedrift** [comment]
alright i was able to reproduce it again while capturing. 
https://streamable.com/urfl1

**Comment by peppy** [comment]
@EVAST9919 can you explain where this is unmerged? all classes and methods in the error log are present in master.

**Comment by EVAST9919** [comment]
At first I thought since the error was presented in game and I couldn't reproduce it in tests - it's fault of my pr.
But it's not.

**Comment by bdach** [comment]
I think it might be, actually. From the looks of the log there is an attempt to assign spotlights after the selector drawable is disposed, which means you're letting requests run while they shouldn't be anymore.

**Comment by EVAST9919** [comment]
Yeah, but I though this thing should prevent this behavior:
![Screenshot_1](https://user-images.githubusercontent.com/22874522/74474358-5ed12280-4eb6-11ea-98fa-6cad7b365b6f.png)

But looks like sometimes we can hit timings when request is completed right before disposal, so that's why it's so hard to reproduce.

**Comment by bdach** [comment]
I'm pretty sure the order depicted above is wrong. Cancel the requests first, _then_ call base.

**Comment by smoogipoo** [comment]
Reordering isn't the correct fix to be done here. API web request callbacks are scheduled onto APIAccess' scheduler, which is always running in the game. Therefore it's possible that your drawable is getting disposed and then the scheduled callback is run.

Proper fix is to schedule the callbacks locally.

**Comment by bdach** [comment]
Yeah, I should have thought of that, my bad. I wouldn't say the reorder is _wrong_, but it is an incomplete fix.
