### ISSUE TITLE
Difficulty Adjust doesn't change cursor size

### ISSUE THREAD

**Issue by Avijojo** [ppy/osu#7826]
**Describe the bug:** 
Turn on "Adjust gameplay cursor size based on current beatmap" in the settings panel, then go to a map and adjust its circle size, the cursor size won't change.
**Screenshots or videos showing encountered issue:** 
 https://youtu.be/2N5gafv5Cyo
**osu!lazer version:** 
2020.208.0
**Logs:**

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/6342
