### ISSUE TITLE
Music sounds broken in Flatpak sandbox

### ISSUE THREAD

**Issue by protheory8** [ppy/osu#7840]
Not sure if that's a valid bug, because it only happens when the game launched in Flatpak's sandbox and never happens when I launch game without Flatpak. I decided to make a bug report anyway because it never happens with any other games.

Edit: second reason why I decided to make this bug report is because I think this issue is really weird: music sometimes works, sometimes it doesn't.

**Describe the bug:** 
Music sounds extremely broken, but if I pause music and resume it again, it starts to sound fine.

**Screenshots or videos showing encountered issue:** 
[Video](https://www.youtube.com/watch?v=dwiHNv27IVY)

**osu!lazer version:** 
2020.208.0, compiled from source and packaged as Flatpak using flatpak-builder and [this](https://github.com/protheory8/protheory8.github.io/blob/master/sh.ppy.osulazer.yaml) manifest 

**Logs:** 
[database.log](https://github.com/ppy/osu/files/4204842/database.log)
[network.log](https://github.com/ppy/osu/files/4204843/network.log)
[performance.log](https://github.com/ppy/osu/files/4204844/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4204845/runtime.log)

I uploaded flatpak for anyone who wants to try to reproduce the bug.
1. Install flatpak using instructions [here](https://flatpak.org/setup)
2. Open terminal
3. Execute `flatpak install https://protheory8.github.io/apps/sh.ppy.osulazer.flatpakref`
4. Start osu! by executing `flatpak run sh.ppy.osulazer`. If everything seems OK, close the game and start osu! using the same command several times.

**Comment by jai-x** [comment]
From your `runtime.log`:
```
2020-02-14 14:09:40: VideoDecoder faulted: System.DllNotFoundException: Unable to load shared library 'avformat' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libavformat: cannot open shared object file: No such file or directory
2020-02-14 14:09:40: at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
2020-02-14 14:09:40: at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
2020-02-14 14:09:40: at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
2020-02-14 14:09:40: at osu.Framework.Graphics.Video.VideoDecoder.<>c.<CreateFuncs>b__55_0(String name)
2020-02-14 14:09:40: at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__5_318()
2020-02-14 14:09:40: at FFmpeg.AutoGen.ffmpeg.avformat_alloc_context()
2020-02-14 14:09:40: at osu.Framework.Graphics.Video.VideoDecoder.prepareDecoding()
2020-02-14 14:09:40: at osu.Framework.Graphics.Video.VideoDecoder.StartDecoding()
```
Is seems the FFMPEG libraries used for video decoding cannot be found when running. This is may be an issue with your Flatpak manifest or the way Flatpak allows for the executable to detect system installed libraries. Missing FFMPEG libraries have been known cause stuttering in the past, especially after the video based Triangles intro

Additionally, I'm unsure if Flatpak support is intended at this point.

Following discussion made here https://github.com/ppy/osu/issues/2960, it was decided to use AppImage as the format for distrubting the game on Linux platforms.

A WIP pull request for adding AppImage support to the deploy process can be found here: https://github.com/ppy/osu-deploy/pull/36

You could try and building and running the deploy script against that branch and see if the resulting AppImage has the same issues.

**Comment by protheory8** [comment]
Yup, Flatpak support is unintended, I wanted to make a Flatpak and see if it works (I wasn't going to publish anywhere anyway). I don't think this bug should happen though?

I've tried building AppImage, it doesn't such issues because it doesn't use sandboxing.

**Comment by jai-x** [comment]
I'm not very familiar with the sandboxing mechanisms of Flatpak and how they may affect runtime behaviour so I don't think I can be much help :(

**Comment by bdach** [comment]
Please try setting the `LD_DEBUG=libs` envvar and attach the log here. I'm not familiar with flatpak either but that's the first obvious step to make when debugging runtime linking errors.

**Comment by protheory8** [comment]
Output is huge, so I uploaded it to pastebin.
https://pastebin.com/jmQQHRYq
Everything inside /app/bin is self contained build of osu! and everything else is part of org.freedesktop.Platform runtime.

**Comment by protheory8** [comment]
I built osu!lazer 2018.1227.0 from source and packaged it as Flatpak, same problem. Doesn't happen in Firejail though.

**Comment by smoogipoo** [comment]
We don't officially support Flatpak.

If you're building and packaging yourself, it's your responsibility to work with the constraints of your process and investigate any issues you encounter.

**Comment by protheory8** [comment]
OK, thanks, honestly I think it was library issue anyway.

**Comment by JaneSmith** [comment]
I was very disappointed to see that this isn't officially supporting Flatpak, given that Flatpak is the direction application packaging on Linux is moving in... AppImage is not an equivalent option at all, and I also couldn't find any information about which distros Osu is supporting with its AppImage (given that AppImage is not truly distro agnotic like Flatpak, and needs to actively support a chosen set of distros).

Anyway, I wanted to use this third-party Flatpak repo, but the link given in the OP doesn't work anymore. Has there been any progress on this, @protheory8?

**Comment by peppy** [comment]
We test across a broad range of distros and have not run into an issue with the appimage. Could you please describe why it does not work for you?

**Comment by protheory8** [comment]
@JaneSmith No, there haven't been any progress, but I feel like the issue was less common last time I checked. I can reupload the file if you want.

**Comment by bdach** [comment]
> given that Flatpak is the direction application packaging on Linux is moving in...

I don't really follow the goings-on of the perennial "linux on the desktop" efforts but claiming that flatpak is *the* direction, at least for me, requires some sort of citation. I'm aware of at least three competing standards (flatpak, appimage, ubuntu's snap), all slightly different with (as far as I can tell) no conclusive answer as to which one is "best", which is a bit funny considering the problem they're supposed to be solving. I guess it's to be expected, though, as per [this classic xkcd strip](https://xkcd.com/927/).

**Comment by protheory8** [comment]
Fixed
