### ISSUE TITLE
ArgumentNullException when playing a map downloaded using the "without video" option

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#7847]
**Describe the bug:**
- Download a map using the "without video" option
- Play the map
- "Video failed to load" notification appears

**Screenshots or videos showing encountered issue:** https://streamable.com/07lkn

**osu!lazer version:** 2020.215.0

**Logs:** [runtime.log](https://github.com/ppy/osu/files/4208614/runtime.log)

**Comment by smoogipoo** [comment]
Ah, this is a result of https://github.com/ppy/osu/pull/7784, where I made the error messages more prominent. This is one of those cases where `BeatmapManagerWorkingBeatmap` should be soft-handling.
