### ISSUE TITLE
Transform mod effects not applying

### ISSUE THREAD

**Issue by Frolie** [ppy/osu#7851]
**Describe the bug:** 
~~When transform mod is selected along with any other mod the effects of transform mod do not apply and the circles do not move~~ I was mistaken and the mod seems to just not work in general
**osu!lazer version:** 
2020.215.0
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/4208896/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4208897/updater.log)
[database.log](https://github.com/ppy/osu/files/4208898/database.log)
[network.log](https://github.com/ppy/osu/files/4208899/network.log)
[performance.log](https://github.com/ppy/osu/files/4208900/performance.log)

**Comment by mouzedrift** [comment]
The transform mod doesn't seem to work in general, no matter if other mods selected or not. The mod does work with osu!lazer version 2020.208.0 though.

**Comment by bdach** [comment]
According to bisection, regressed at f7ee6751.
