### ISSUE TITLE
Add a "contrast cursor" option

### ISSUE THREAD

**Issue by Jatoxo** [ppy/osu#7852]
**Describe the new feature:** 
An option to make the cursor contrast whatever is behind it, to increase visibility

**Proposal designs of the feature:** 
Self explanatory

**Comment by bdach** [comment]
Do you mean the UI cursor, or the gameplay cursor? The second can be skinned.

**Comment by Jatoxo** [comment]
> Do you mean the UI cursor, or the gameplay cursor? The second can be skinned.

The gameplay cursor. I thought it was just a png image? Sure you could change the color, but what I meant was that the cursor basically has the inverted color of the background at all times, so a static image wouldn't do

**Comment by bdach** [comment]
I think the most flexible way to achieve this would be a way to specify a blending mode for skinnable sprites (in this case, the difference blending mode).

**Comment by iiSaLMaN** [comment]
I would say better to wait for [OML](https://github.com/ppy/osu-framework/issues/3055) and drawable-based skinning for now.

**Comment by peppy** [comment]
as mentioned, this will be feasible via skinning in the future.
