### ISSUE TITLE
Max combo's aren't green highlighted when someone has a full combo on it

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#7862]
**Screenshots or videos showing encountered issue:** 

lazer:
![osu!_DfZGXP1u0U](https://user-images.githubusercontent.com/43358824/74608189-5ad41900-50df-11ea-8c5d-fc93fdf86ed8.png)
web:
![chrome_fKY8i83t8i](https://user-images.githubusercontent.com/43358824/74608195-61fb2700-50df-11ea-8015-a8de979579dd.png)

**osu!lazer version:** 
commit e80c310ab29030fd4d6c5d300a98f8f51c68067c

**Used beatmap:** https://osu.ppy.sh/beatmapsets/999868#osu/2091238

**Comment by TheWildTree** [comment]
I've looked into fixing this a while ago and I'm fairly certain there needs to be some API changes for that to happen.

Currently, API responses (either beatmap or score ones) don't contain any information about max possible combo on a given beatmap, even though web side of things has access to it. All we'd need is to have a`MaxCombo` property in the beatmap info response.

Haven't investigated too much though, it might also be that it's being sent somewhere but not properly parsed osu-side.

**Comment by smoogipoo** [comment]
cc @nanaya

**Comment by smoogipoo** [comment]
Seems like we should be able to use the max_combo provided by the api beatmap (currently not deserialized): 

![image](https://user-images.githubusercontent.com/1329837/74615031-4e43d500-5160-11ea-9b9f-96e1193bc5e0.png)

**Comment by TheWildTree** [comment]
Any reason why this is sent as an array instead of a single value?

**Comment by bdach** [comment]
PHP is inscrutable for me but [seems like it might not be intended](https://github.com/ppy/osu-web/blob/c3bff95ef0b2698ed13b6f0b7718dc6f67ea1059/app/Transformers/BeatmapTransformer.php#L116-L125) (noting the `->first()`).

**Comment by nanaya** [comment]
it was for a different reason and should be fixed by the next release

**Comment by peppy** [comment]
Should be resolved now.
