### ISSUE TITLE
Add the ability to change slider velocity from compose mode

### ISSUE THREAD

**Issue by stanriders** [ppy/osu#7882]
**Describe the new feature:** 
Current way of setting slider velocity is very unintuitive for new mappers because of how slider velocity must be set via a number instead of snapping it to the beats in the timeline
**Proposal designs of the feature:** 
Make slider duration setting the same way spinners are made and move reverse creation into a context menu when you right-click a slider.

**Comment by peppy** [comment]
slider velocity shouldn't be changed so easily. it is supposed to be something players can follow. adding adjustment on the timeline feels like a step backwards.

that said, we do plan on doing other ways (including context menu) for improving the user experience and discoverability of adding repeats.

**Comment by stanriders** [comment]
> it is supposed to be something players can follow.
Tell that to the current mapping meta :^)

Seriously though, I believe ranking criteria should enforce slider playability, not the editor. Current way of setting velocity is **VERY** unintuitive and also makes any form of sliderart (and any velocity changes honestly) a pain. Moving it to the timeline would be ideal for ease of use, especially considering currently mappers prefer to change velocity very often and end up with hundreds of green ticks just for the SV changes

**Comment by peppy** [comment]
we do plan on improving the mechanisms to change velocity, including potentially moving it away from control points completely. but do consider that my input to the mapping meta is controlling how easy certain things are to do (which may or may not be intentional).

I'm renaming this issue to track the more broad task of making SV adjustable from compose mode.
