### ISSUE TITLE
More variations of using combo colors

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#7883]
You need to be able to add more than 8 combo colors (at least 16) and allow you to arbitrarily set the color of the next combo, and not like in a stable, where everything goes in strict order. This also includes situations when I want to start the next combo without changing color (may be useful in aspire mapping)

**Comment by peppy** [comment]
It's a bit too early to be adding new features like this. We will keep this in mind when adding combo colour choices to the editor. Please check back in 3-6 months!

**Comment by Moltanicaa** [comment]
Can you opet it again now?

**Comment by peppy** [comment]
no. wait until combo colour selection and application is a thing.

**Comment by Moltanicaa** [comment]
Its time? Because #14088

**Comment by peppy** [comment]
Open a discussion.
