### ISSUE TITLE
First approach circle(s) pausing on certain beatmaps

### ISSUE THREAD

**Issue by SevenChords** [ppy/osu#7886]
I have noticed that on every beatmap where there is little to no empty space before the first hit circle, the first approach circle starts as normal, stops for a few milliseconds (noticeable pause), then continues closing in, but only on beatmaps where the first hit circle comes immediately. Running the latest version of lazer on the latest version of macos.

**Comment by peppy** [comment]
Sounds like `Bass_ChannelPlayer` potentially getting delayed, or some other woes with lead in time.

**Comment by SevenChords** [comment]
the links to 5 beatmaps with this issue present:
https://osu.ppy.sh/beatmapsets/288162#osu/673736
https://osu.ppy.sh/beatmapsets/107565#osu/281843
https://osu.ppy.sh/beatmapsets/527431#osu/1119026
https://osu.ppy.sh/beatmapsets/43466#osu/136400
https://osu.ppy.sh/beatmapsets/361740#osu/803704
in the last beatmap the issue extends to the first 2 hit circles, which makes me think this is somehow related to the circles being placed too early

**Comment by smoogipoo** [comment]
Fixed via https://github.com/ppy/osu-framework/pull/3354

**Comment by MTGPROD** [comment]
But this is not fixed

**Comment by bdach** [comment]
[see comment](https://github.com/ppy/osu-framework/pull/3354#issuecomment-597545410)

**Comment by MTGPROD** [comment]
[Proof](https://vimeo.com/396944585)

**Comment by MTGPROD** [comment]
Ah !
