### ISSUE TITLE
Transform doesn't working

### ISSUE THREAD

**Issue by nahkd123** [ppy/osu#7887]
**Describe the bug:** 
Transform mod doesn't working in osu!lazer 2020.215.0

**Screenshots or videos showing encountered issue:** 
https://streamable.com/jrnw4

**osu!lazer version:** 
osu!lazer 2020.215.0

**Logs:** 
idk which one, so I decide to upload all of them: https://mega.nz/#F!HgpHVSAa!TxAgqG8DCMWAp6a0WmCsRQ

**Comment by peppy** [comment]
Already fixed. Please wait for the next release.
