### ISSUE TITLE
osu!lazer only shows a corner on the top-left of screen

### ISSUE THREAD

**Issue by 4li77l3n00b** [ppy/osu#7895]
**Describe the bug:** 
I'm using a pc with AMD's RX480 graphics card and AMD Adrenalin 2020 driver.
osu lazer only shows a corner every time I start it.
**Screenshots or videos showing encountered issue:** 
![批注 2020-02-19 113533](https://user-images.githubusercontent.com/31160627/74799809-9b64aa00-530c-11ea-9c26-6c563168d7c5.png)

**osu!lazer version:** 
2020.215.1
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/4222980/runtime.log)
[performance.log](https://github.com/ppy/osu/files/4222994/performance.log)

**Comment by smoogipoo** [comment]
Which mode is osu! running in here, borderless or fullscreen?

**Comment by 4li77l3n00b** [comment]
> Which mode is osu! running in here, borderless or fullscreen? Cycle it by pressing F11 or Alt+Enter.
windowed, and it works well under fullscreen and borderless mode

**Comment by peppy** [comment]
Do you have multiple monitors?

**Comment by 4li77l3n00b** [comment]
> Do you have multiple monitors?

no, but used to

**Comment by peppy** [comment]
As a temporary measure, please select the lazer window and hit winkey-left or winkey-right to bring it back on screen so you can resize it.

**Comment by ojh050118** [comment]
It looks like osu!.exe --sdl window.

**Comment by 4li77l3n00b** [comment]
> As a temporary measure, please select the lazer window and hit winkey-left or winkey-right to bring it back on screen so you can resize it.

Thanks. It works.

**Comment by peppy** [comment]
Tracking at https://github.com/ppy/osu-framework/issues/3285
