### ISSUE TITLE
Relax mod in osu!taiko is not implemented

### ISSUE THREAD

**Issue by kawaemon** [ppy/osu#7914]
**Describe the bug:** 
If we pick Relax mod in osu!taiko, both of rim and centre key should hit all types of notes.
But it doesn't.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/e7s0a

**osu!lazer version:** 
2020.215.0

**Comment by bdach** [comment]
It doesn't work because as far as I can tell, it currently is not implemented properly yet.

**Comment by quat1024** [comment]
I took a look at this, but I'm not sure where to start.

Afaik these are the things taiko Relax does in stable:

* If there's a tap note with an active hit window (including the early-miss window), the drum input is *corrected* to the color of the tap note.
  * The corrected input is shown on the left-side drum icon, and the sound for the corrected input plays.
  * The corrected input is on the same side of the drum; left rim gets corrected to left center.
  * The second input on a strong note has to be within the 30ms window to be eligible for correction, I think?
* You don't have to time drum rolls very well, it's easy to complete them by mashing.
  * [Wiki](https://osu.ppy.sh/wiki/en/Gameplay/Game_modifier/Relax#osu!taiko) says that it gives "more lenient timing" but isn't specific on the details.
* Swells can be hit with any color sequence.

Some possible implementation paths:

* Littering the taiko drawable hit processing code with "is relax turned on" checks!!!
* Swapping out the implementation of hit objects kinda like [OsuModStrictTracking](https://github.com/ppy/osu/blob/08024e70ebce1af86b06476e0cedadfabb7ecc52/osu.Game.Rulesets.Osu/Mods/OsuModStrictTracking.cs) is doing
* Messing with `IKeyBindHandler`s like [InputBlockingMod](https://github.com/ppy/osu/blob/08024e70ebce1af86b06476e0cedadfabb7ecc52/osu.Game.Rulesets.Osu/Mods/InputBlockingMod.cs) to cancel inputs but I don't think you can inject new inputs with them
