### ISSUE TITLE
Request: Make Daycore mod logo in osu!lazer a snail.

### ISSUE THREAD

**Issue by Ratchet0203** [ppy/osu#7927]
Instead of Daycore just saying "DC," I think it deserves a logo like Nightcore has. Snails are slow, and daycore is slow, so in my opinion, making the Daycore logo a snail would be appropriate for this mod while still giving it something different than the normal hourglass logo for Half Time.

**Comment by smoogipoo** [comment]
Relates to https://github.com/ppy/osu/issues/6966 , let's wait on a design first.
