### ISSUE TITLE
Changelog overlay colours should match osu-web

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#7937]
**Screenshots or videos showing encountered issue:** 
lazer:
![osu!_cxjbfjrpk0](https://user-images.githubusercontent.com/43358824/75035323-81af9800-54af-11ea-8bcf-b0a1bef38750.png)

web:
![chrome_ryM8rKvlQM](https://user-images.githubusercontent.com/43358824/75035318-7c524d80-54af-11ea-90a4-14cc2c9c0d09.png)
**osu!lazer version:** 
commit 66bd8882279679f656360efbcfbb7daf72e2260e

**Comment by EVAST9919** [comment]
Already working on it
