### ISSUE TITLE
Falling fruits shouldn't be on a higher level than the catcher

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#7938]
**Screenshots or videos showing encountered issue:** 
https://streamable.com/n5bqb

**osu!lazer version:** 
2020.221.0

**Comment by peppy** [comment]
This is a known issue, but not so easy to fix.

**Comment by smoogipoo** [comment]
I don't remember why this isn't easy to fix but in any case we should be able to just proxy the whole hitobject container behind the catcher as a start.

**Comment by peppy** [comment]
So the issue here is that the fruit need to exist *between* already-caught fruit and the catcher. If we are to use proxying to fix this, it would likely be exposing and proxying the caught-fruit container to a level behind the playfield. @smoogipoo are you okay with this?

**Comment by smoogipoo** [comment]
Sounds fine
