### ISSUE TITLE
almost no controller support + lag on taiko, catch and mania

### ISSUE THREAD

**Issue by Rubenvp3** [ppy/osu#7939]
So: I wanted to play osu!taiko and noticed that it's impossible to play with just the touchscreen, wich forced me to connect my xbox one controller via bluethoot and bind the controls for playing, but it only recognised all the directional input from the left analog joystick (as the keyboard arrow keys) the dpad (it was recognised as if they were the arrow keys aswell) and menu (as scape).
When I was ready to play,  I decided test all the secondary gamemodes (osu!taiko, osu!catch and osu!mania [4k]), where I experienced a lot of lag on all of them
here is some footage (sorry for the terrible gameplay, it's hard to play with the dpad): https://gofile.io/?c=exAHWI
in osu!taiko, the game struggles a lot when there are a lot of notes on the screen. In osu!catch hoever, it only lags when there is a converted spinner and finally in osu!mania, it always lags during gameplay

**Comment by bdach** [comment]
I'm assuming you are on a mobile platform. Please note:

* Mobile/touchscreen input methods are planned (#4201).
* Issues with controller button mapping are likely to do with the operating system and therefore out of scope. You could try remapping keys through settings. Support for custom input devices has already been requested (closest issue is ppy/osu-framework#2863).
* The performance issues you mention are non-specific and therefore not actionable. Performance is a constant focus and improvements in that area will be coming.

Closing on all above counts.
