### ISSUE TITLE
Wrong scaling on loading animation during map loading

### ISSUE THREAD

**Issue by Snowmander** [ppy/osu#7942]
**Describe the bug:** 

Happens on Windows and iOS.

**Screenshots or videos showing encountered issue:** 
![F8D6AB86-83A6-4B87-B05E-C477AE4C48C7](https://user-images.githubusercontent.com/45163894/75047547-45f5ec00-550a-11ea-94f7-0a3696eb7cef.jpeg)

**osu!lazer version:** 
iPad Pro 12.9
Windows 10
UI scaling at 0%

**Comment by EVAST9919** [comment]
Also not sure, but this one may be related
![Screenshot_1](https://user-images.githubusercontent.com/22874522/75047947-c26fd700-54d8-11ea-9ee9-d03abea3aa3b.png)

**Comment by peppy** [comment]
If they have a local scale set, the solution is unsetting this scale.

**Comment by Snowmander** [comment]
Still happens at 1.00x scaling (default).

**Comment by peppy** [comment]
I'm talking about scaling in the code, not the setting.
