### ISSUE TITLE
Fruits aren't appearing immediately during gameplay

### ISSUE THREAD

**Issue by Larakagi** [ppy/osu#7945]
While in stable it doesn't have this fade effect, in lazer this fade effect when a fruit appears on top of the screen is noticeable (those three fruits on top is an example)
![изображение](https://user-images.githubusercontent.com/36848514/75048742-10d1a580-54da-11ea-8b94-75a00d48565b.png)

**Comment by mouzedrift** [comment]
duplicate of #6902
