### ISSUE TITLE
long Beatmaps significantly lower performance

### ISSUE THREAD

**Issue by chrisny286** [ppy/osu#7949]
The longer the beatmap is the lower the initial performance is.
In addition to this, over the course of a map of any length, performance goes downhill from the beginning to the end.

In the Screenshots taken for comparison you can see that the longer the map goes on, the time update needs to work is increased, resulting in sleeptime in draw.
Also the longer the map is the intial work time for update is longer the longer the map is.
This holds true as long as you compare beatmaps with a similiar notedensity in total.
In general: The more notes total the beatmap has makes performance worse.
Autoplay was taken because its easier to screenshot, the same happens when playing normally.

[short map](https://osu.ppy.sh/beatmapsets/433506#osu/960539) beginning:
![short initial](https://user-images.githubusercontent.com/25304259/75079248-6329bb00-5508-11ea-9674-9f4efe8a16a2.jpg)
at the end:
![short end](https://user-images.githubusercontent.com/25304259/75079255-68870580-5508-11ea-95ff-6d769c8b5e10.jpg)
[long map](https://osu.ppy.sh/beatmapsets/70744#osu/203315) beginning:
![long initial](https://user-images.githubusercontent.com/25304259/75079260-6de45000-5508-11ea-9e5f-bc8d9f6dcd4f.jpg)
at the end:
![long end](https://user-images.githubusercontent.com/25304259/75079265-72106d80-5508-11ea-86c8-8278e9744d50.jpg)
[Marathon map](https://osu.ppy.sh/beatmapsets/296952#osu/674188) beginning:
![marathon initial](https://user-images.githubusercontent.com/25304259/75079270-750b5e00-5508-11ea-9d39-43683bbd59b8.jpg)
at the end:
![marathon end](https://user-images.githubusercontent.com/25304259/75079279-789ee500-5508-11ea-8cab-50ab7c32d8be.jpg)

osu!lazer version 2020.221.0

PC Specs:
intel i7-4770
Msi Nvidia GTX 1070 (primary | main monitor)
Msi Nvidia GTX 760 (secondary | 2cnd and 3rd monitor)
16GB RAM

**Comment by bdach** [comment]
Mostly a known issue with maps that are demanding in various ways (see #3588, #6123, more technically - ppy/osu-framework#2729). I suppose I wouldn't mind leaving this open for now though.

**Comment by peppy** [comment]
we're aware of issues with specific rulesets (i have a fix in the pipeline for catch), but osu! is unexpected. will look into this - may be an issue with hitobect lifetimes.

**Comment by peppy** [comment]
I can't seem to reproduce what you are seeing, strangely enough (same maps and same settings as far as I can tell) using default or custom skins. My performance is consistent at the start and end of the beatmap.

- Can you confirm that you are not seeking forward using the seek bar?
- Could you include your configuration file (remove your credentials first) so I can check if it's a specific setting you have enabled?

**Comment by peppy** [comment]
I have since managed to reproduce, by disabling storyboards, never mind!

**Comment by chrisny286** [comment]
I can confirm its not from using the seek bar.
Yes, I am using disable storyboards and most of the other disable options. 
I can confirm enabling storyboards results in the same performance throughout the map.

Performance short vs long Beatmap still favors shorter maps though.

I'll add the config files for completion anyway:
[game(nocreds).txt](https://github.com/ppy/osu/files/4239364/game.nocreds.txt)
[framework.txt](https://github.com/ppy/osu/files/4239365/framework.txt)
