### ISSUE TITLE
Normal hitsounds playing as Soft hitsounds

### ISSUE THREAD

**Issue by JapanYoshi** [ppy/osu#795]
Title self-explanatory. If this is intentional, please just confirm it.

**Comment by peppy** [comment]
that's not how you report an issue

**Comment by peppy** [comment]
please provide at very least reproduction steps. attach a .osu file and specify the lines which are incorrect. point out where you thing the issue is. do something to help us help you.

**Comment by JapanYoshi** [comment]
Reproduction steps
1. play any map that has Normal hitsounds

**Comment by JapanYoshi** [comment]
There is no step 2
