### ISSUE TITLE
Choose between 2 versions of a beatmap

### ISSUE THREAD

**Issue by T0chi** [ppy/osu#7952]
**Describe the new feature:** A feature where it's possible to choose between 2 versions of a beatmap ingame and still be rankable. Can be used to seperate a beatmap with 2 versions of a storyboard like if it includes a theme for 2 different characters, different sprite files, or 2 different languages etc. It's a way to make the storyboard scene more interesting.

**Proposal designs of the feature:** A dropdown menu or 1-2 buttons beside each other with a custom text like

- "EN Version | JP Version"
- "Hatsune Miku | Aoki Lapis"

**Comment by iedesu** [comment]
pog that sounds interesting!!

**Comment by peppy** [comment]
I beleive this is too far in the future to keep open for now. Let's finish the editor first.
