### ISSUE TITLE
Add score submission

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#7957]
It would be cool to be able to break records on osu!lazer as on osu! normal. For example if we change the score display (from standardized to classic) in the options we could make a score on a ranked beatmap beat our current score on lazer and send it on the osu api as on the normal game what to win or lose pps

**Comment by mcendu** [comment]
Definitely won't be considered until it is in a good state.

**Comment by MTGPROD** [comment]
Is it not possible to add the score calculation of osu stable to lazer and make score submission possible ? Or it's too hard to do

**Comment by smoogipoo** [comment]
It'll happen eventually, but we're not currently at the point of considering score submission.
