### ISSUE TITLE
osu!catch can not display red fruits to hype jump 

### ISSUE THREAD

**Issue by serenityP** [ppy/osu#7958]
**Describe the bug:** 
I can not recognize whether these fruits are red or common.  And the fruit is much bigger than the previous verison, is it a update?
**Screenshots or videos showing encountered issue:** 
https://www.dropbox.com/s/c2ovglmjg48jg1p/Catch%20%28no%20red%20fruits%29.flv?dl=0
**osu!lazer version:** 
0221ver.
**Logs:**

**Comment by peppy** [comment]
Seems to have unintentionally regressed with the skinning changes.
