### ISSUE TITLE
Window doesn't resize correctly

### ISSUE THREAD

**Issue by vesterlay** [ppy/osu#7964]
**Describe the bug:** 
When I grab any corner and try to resize osu, window resizes to my pointer and stretches horizontally at the same time. 

**osu!lazer version:** 
2020.221.0-1

**logs:**
[database.log](https://github.com/ppy/osu/files/4239641/database.log)
[network.log](https://github.com/ppy/osu/files/4239642/network.log)
[performance.log](https://github.com/ppy/osu/files/4239643/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4239644/runtime.log)
**OS:**
Linux Manjaro 5.4.18-1-MANJARO

**Comment by bdach** [comment]
Can you explain in more detail? I don't understand the problem from your description.

If you mean to say that the content within the window preserves aspect ratio, that is expected behaviour.

**Comment by vesterlay** [comment]
@bdach 
https://youtu.be/DBhjf7b4IdM

**Comment by bdach** [comment]
That honestly seems like more of a window manager problem more than an actual issue with lazer. It'll be hard for anyone else without anything close to your setup to even begin investigating.

I'd try another WM and see if the issue still persists. I know for sure my i3 setup works fine, not sure about others.

**Comment by vesterlay** [comment]
Please also take a look at borderless and fullscreen screen modes, because they also appear to be  broken.
Borderless
![1](https://user-images.githubusercontent.com/39202451/75097319-a2f4af00-55a9-11ea-8067-526994cbb7ff.png)
Fullscreen after the alt+tab
![2](https://user-images.githubusercontent.com/39202451/75097321-a4be7280-55a9-11ea-8d5f-fb4e1695dc42.png)

**Comment by bdach** [comment]
They do seem broken, but again this is likely interference from your WM (gnome3 from the looks of it?)

Out of curiosity, mind trying to run lazer with the experimental `--sdl` flag and seeing if it changes for the better?

**Comment by vesterlay** [comment]
@bdach 

> They do seem broken, but again this is likely interference from your WM (gnome3 from the looks of it?)

My WM is Mutter and DM is gnome 3.34.2 to be precise. 

`--sdl` seem to repair the problem with resizing, although screen mode settings disappeared.
![Screenshot from 2020-02-22 19-52-27](https://user-images.githubusercontent.com/39202451/75097664-aa1dbc00-55ad-11ea-946a-7444ef919580.png)

**Comment by bdach** [comment]
Yeah, our SDL support is in the early/experimental stages. The modes will return as we progress in the transition away from openTK but it might take a while. Unfortunately `--sdl` is probably the best effort we can provide right now.

I'm going to close this for now as we can't really do much to immediately address this and a long-term solution is already in the works.
