### ISSUE TITLE
Only one button works

### ISSUE THREAD

**Issue by fawcett97** [ppy/osu#7965]
Often times after a break in the song I will find that one of my buttons stops responding (normally the one bound to left click)

**Comment by bdach** [comment]
Please state your platform, what input device you're using, and if you're using raw mouse input if it's a mouse.

**Comment by fawcett97** [comment]
I use a pc running Windows 10 with a tablet and keyboard

Idk why but the second I reported this is stopped happening, but me saying this is probably gonna magically make it start happening again

**Comment by bdach** [comment]
Going to close this for now, then. Please report back if it happens again, we'll reopen and investigate.
