### ISSUE TITLE
Loading sprite on beatmap loading screen is enlarged

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#7976]
The loading sprite for loading screen is bigger than expected. It shouldn’t look like this when you’re loading a beatmap:
![2050FDEB-1ECB-4EC3-9D64-F36F704377A0](https://user-images.githubusercontent.com/48611569/75110174-95164c80-55f0-11ea-8582-afbb20e2851c.png)

**Comment by TheWildTree** [comment]
Duplicate of #7942.

**Comment by dscnnctd** [comment]
Closing.
