### ISSUE TITLE
Crashing on Linux(From appimage file)

### ISSUE THREAD

**Issue by KotypeyPyEdition** [ppy/osu#7987]
**Describe the crash:** 
when i tried to launch osu it just crashes on start

**https://www.youtube.com/watch?v=S9NmOetBzYw&feature=youtu.be** 

**2020.221.0** 

**Logs:**
*please attach logs here, which are located at:*
https://drive.google.com/file/d/1vKFp9COQfSCi7rL3T840BEZwnbd45h-8/view?usp=sharing

**Computer Specifications:** 
OS: Ubuntu 18.04.4 LTS x86_64
Kernel: 5.3.0-40-generic 
CPU: Intel i3-6006U (4) @ 2.000GHz
GPU: AMD Radeon HD 8670A/8670M/8690M
GPU: Intel HD Graphics 520

**Comment by jai-x** [comment]
Duplicate of https://github.com/ppy/osu/issues/7947

**Comment by KotypeyPyEdition** [comment]
Ok
