### ISSUE TITLE
Beatmap disappeared in selection but not in osu!direct

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu#7990]
**Describe the bug:** Just downloaded centipede from the osu!direct, played it once (and failed after the spinner), then went to osu!direct to view info of others some centipede map, the returned to the map selection in solo and it disappeared. Tried redownloading from the osu!direct but it shown as downloaded, clicking on the downloaded button make it jump to other random available beatmap. Restarting the client does not help, still can't redownload.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/-__N4ueYS8Y

**osu!lazer version:** 2020.225.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4250351/database.log)
[network.log](https://github.com/ppy/osu/files/4250352/network.log)
[performance.log](https://github.com/ppy/osu/files/4250353/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4250354/runtime.log)

**Comment by EVAST9919** [comment]
Set star rating in settings unlimited (I guess it's just 10 stars max)

**Comment by huupoke12** [comment]
Ok, It worked now
