### ISSUE TITLE
Freeze when turning score overlay back on towards the later part of a beatmap

### ISSUE THREAD

**Issue by chrisny286** [ppy/osu#7992]
Starting with all Overlays disabled and playing a map, once you turn the Overlays back on with the shortcut shift+tab the client freezes up for a varying amount of time on the scale of 5-15 seconds.
The longer you played the map without Overlays visible, the longer is the resulting freeze.
Music continues to play. Once the client recoveres you failed the map and this is what is visible in the performance display(The blue spike in Draw is exactly the moment the game unfreezes):
![after the lag](https://user-images.githubusercontent.com/25304259/75277381-32979900-5808-11ea-9241-1b6c55aa3200.jpg)

**Game Settings:**
[framework.txt](https://github.com/ppy/osu/files/4251617/framework.txt)
[game(nocreds).txt](https://github.com/ppy/osu/files/4251618/game.nocreds.txt)
**Logs:**
[performance.log](https://github.com/ppy/osu/files/4251605/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4251606/runtime.log)

**Comment by bdach** [comment]
I can't reproduce anything noticeable like that, much less this bad, and I'm on much worse graphics cards (I tested on both my GT 555M and integrated Intel card). Mind attaching a video of this with the frame statistics on if at all possible? Maybe that will give us something to go on.

**Comment by chrisny286** [comment]
At exactly 1:40 in the video in the breaktime i press shift+tab. Its necessary to have the overlay disabled for a longer while.
[video](https://doc-00-30-docs.googleusercontent.com/docs/securesc/bs5uuo3lvc59p53qr09i0926fsvdfnhk/p4ohs6ghmqv4rmh3he4akfdeqicph91k/1582660800000/10982013516317027116/10982013516317027116/1hF9YekV-gOfG9VJI2NS1u8OSe2mnwr-Z?authuser=0&nonce=tpcg5f16mf7lg&user=10982013516317027116&hash=c3vimj6sll7ausmhrisstg923pggrf6u)

**Comment by bdach** [comment]
Not sure why but that link seems broken (can't see any video).

**Comment by chrisny286** [comment]
i edited the link i had the direct link to the google drive file of the .mp4 there maybe it produced an issue with view access even though it shouldve been accesible

**Comment by bdach** [comment]
Thanks, works now and looks helpful. Looks like the hang starts with a big stall on the update thread. Does disabling the score meters on the sides (hit error bars) alleviate the hang?

**Comment by chrisny286** [comment]
No disabling the score meter does not help, still the same.

**Comment by chrisny286** [comment]
The issue must be due to the healt display.
Playing with No Fail alleviates the issue, while turning on "show health bar display even when you can't fail" makes it appear again, also on no fail.
