### ISSUE TITLE
The changelog overlay should just dimmer the selected category when hovering

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#7998]
lazer:
![j55DoF8Hln](https://user-images.githubusercontent.com/43358824/75308678-56320200-584f-11ea-89ef-435dd55a6dce.gif)
web:
![aOEDOWI2tn](https://user-images.githubusercontent.com/43358824/75308618-3ac6f700-584f-11ea-971b-ba2efc8605ab.gif)

**osu!lazer version:** 
commit 1cb91b24278ff0815033cd17cfad718136a9a852

**Comment by smoogipoo** [comment]
I prefer the way lazer looks more than web here.

**Comment by peppy** [comment]
Lazer makes no UX sense. At very least the dimming should not be applied to the already dimmed items.

**Comment by smoogipoo** [comment]
Ah I was experiencing a visual illusion and didn't realise the cause was the double dimming. 👍

**Comment by EVAST9919** [comment]
Should be done like mod selector in `BeatmapSetOverlay
![nice](https://user-images.githubusercontent.com/22874522/75325310-a4fc8d80-5889-11ea-857d-1e9224dccfaf.gif)
`
