### ISSUE TITLE
Nightcore mode is broken (android) 

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#8009]
**Describe the bug:** 

When you enable the nightcore mode, some map you'll play will be stopped with no reason

**Screenshots or videos showing encountered issue:** 

https://youtu.be/QOZVzRmeebE

**osu!lazer version:** 

2020.225.0

**Logs:**
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*

I'm still on Android

**Comment by bdach** [comment]
I would be very surprised if this were a separate issue from #7991 / #7444 / #6355. Closing as likely duplicate for now.
