### ISSUE TITLE
Replies don't align properly when too many replies were added

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#8012]
**Screenshots or videos showing encountered issue:** 
lazer:
![chrome_3qfIvoixDY](https://user-images.githubusercontent.com/43358824/75364605-44d30f00-58bc-11ea-9519-d1f7bfb3c0a9.png)

web:
![Op8Co9aZYN](https://user-images.githubusercontent.com/43358824/75364680-6207dd80-58bc-11ea-821b-ee70010fc796.png)

**osu!lazer version:** 
commit f1c97451d976c3e1d3fcd4bb9701302b188d6378

**Comment by EVAST9919** [comment]
To be honest, I prefer lazer version, but web version makes more sense for very long trees
