### ISSUE TITLE
Upvote background opacity doesn't match osu-web

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#8013]
**Screenshots or videos showing encountered issue:** 
lazer:
![osu!_tlwLX2iuH4](https://user-images.githubusercontent.com/43358824/75364997-da6e9e80-58bc-11ea-960e-319e5abb9123.png)
web:
![chrome_ypp1Vq6reI](https://user-images.githubusercontent.com/43358824/75365014-dfcbe900-58bc-11ea-8e2a-70c121577be1.png)

**osu!lazer version:** 
commit f1c97451d976c3e1d3fcd4bb9701302b188d6378

**Comment by EVAST9919** [comment]
It was implemented before `OverlayColourProvider` so yeah
