### ISSUE TITLE
The in-game interface has a huge impact on the fps

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#8015]
I have around 300-370 fps with the in-game interface and 600-700 without. I know that lazer still needs lots of optimisations but i want to keep this issue for better visibility.

**osu!lazer version:** 
commit f1c97451d976c3e1d3fcd4bb9701302b188d6378

**Specs:**
RAM: 8 GB
CPU: i5-4440 4x 3.10 GHz
iGPU: intel hd graphics 4600

**Comment by peppy** [comment]
draw? update? input? when talking performance you need to give much more context than you have.

if the game rendering an empty screen is drawing at 600 and with many interface elements, is drawing at 300, i’d consider that normal.

**Comment by mouzedrift** [comment]
sorry, i was thinking about drawing fps when i created this issue.

My current overlay settings look like this:
![osu_2020-02-27_01-17-04](https://user-images.githubusercontent.com/43358824/75400421-833ded80-58ff-11ea-8002-0f4164c8ad8d.png)

i used the same map to measure the fps with and without interface. I think that lazer's in-game interface eats way more fps than it actually should.

I don't mind closing this issue if you're still confident that this is normal.

[Used skin](https://circle-people.com/wp-content/Skins/Rohulk/Rohulk%204.0-2017-08-10.osk)

**Comment by smoogipoo** [comment]
I think we can do better than a doubling of frametime here. Sure we're drawing more but it's a little more than I'd expect the overhead to be, for how little of the screen is taken up by the HUD.

**Comment by smoogipoo** [comment]
Let's close this for now, since we only keep actionable performance issues open, and this isn't really actionable right now.

There are plans that will result in draw performance improving over time in the future, but this is always going to be a thing due to the additional overhead (just potentially smaller in the future).
