### ISSUE TITLE
Spectrogram in the editor

### ISSUE THREAD

**Issue by Kyuunex** [ppy/osu#8034]
**Describe the new feature:** 
Spectrogram in the editor. It will be much more useful than waveform when timing **variable** or **multiple** bpm songs

**Proposal designs of the feature:**
preferably have options to adjust it like in audacity to make beats more visible
https://i.imgur.com/dIrn99K.png

**Comment by peppy** [comment]
This makes little sense. The waveform is already coloured by frequency ranges.

**Comment by Kyuunex** [comment]
here's the same section of a song in both lazer's waveform and audacity
i tried my best lining this up but couldn't
but i would say lazer's waveform not as clear as an actual spectrogram, in my opinion
https://i.imgur.com/MpPj1J5.png

**Comment by bdach** [comment]
After squinting at that screenshot for a second I can kind of distinguish beats:

![image](https://user-images.githubusercontent.com/20418176/75482523-475d6380-59a5-11ea-9664-94c9a272c9bc.png)

Although I admit I was looking for them. Maybe what we could experiment with is to have more contrast in the colour grading on the waveform (something like what audacity does, low-saturation blue to high-sat pink)

**Comment by Kyuunex** [comment]
[Here's a better comparison](https://i.imgur.com/bVTdMxp.png), sort of.
In some sections it's not that obvious. 
[Here's the song for reference](https://www.youtube.com/watch?v=GjPTGNNgFYA) (it's timing changes constantly)

II'm not good at explaining but my concern with waveform is that, those colors only represent one thing while the spectrogram represent everything and with variations in songs, current implementation of waveform may not help with timing all the time. (And with adjustments like we have in audacity, one could have a better time finding the beats that aren't that obvious on the graph)

If spectrogram is out of the question, I agree that this waveform could at least use some polish.

**Comment by peppy** [comment]
if you need a spectogram to time them please use an external app. the waveform isn’t there for timing purposes but only as a guide. use your ears for timing.
