### ISSUE TITLE
Unable to login or open chat (as well as view changelog)

### ISSUE THREAD

**Issue by nahkd123** [ppy/osu#8039]
**Describe the bug:** 
For some reason, I can't login to my account, as well as open chat. Look like it's timed out.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/20136708/75501406-88d02c00-5a02-11ea-8d06-469369466681.png)

**osu!lazer version:**
osu!lazer 2020.226.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4264840/database.log)
[performance.log](https://github.com/ppy/osu/files/4264841/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4264842/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4264843/updater.log)
[network.log](https://github.com/ppy/osu/files/4264848/network.log)

**Note:**
If I use my browser and go to https://osu.ppy.sh/api/v2/changelog, it works just fine.

**Comment by peppy** [comment]
Looks like probably a firewall thing?

**Comment by nahkd123** [comment]
I've disabled firewall before (both on my computer and my router).

**Comment by peppy** [comment]
Check you haven't disabled any critical windows services like `Web Client`

**Comment by nahkd123** [comment]
![image](https://user-images.githubusercontent.com/20136708/75502469-70addc00-5a05-11ea-8aec-d16a644b5178.png)
Look like the ``WebClient`` service and other Windows critical services are running.

You can take a look at the list of running/stopped services:
[services.txt](https://github.com/ppy/osu/files/4264891/services.txt)

**Comment by huupoke12** [comment]
Do any of your anti-virus or anti-malware software have additional firewall? Try disabling them.

**Comment by nahkd123** [comment]
> Do any of your anti-virus or anti-malware software have additional firewall/filter/Internet Protection...? Try disabling them.

I only have Windows Defender enabled. Trying to disable Windows Defender Firewall seem like doesn't work...
![image](https://user-images.githubusercontent.com/20136708/75511565-2a667600-5a21-11ea-997c-a68885c4ba29.png)

**Comment by huupoke12** [comment]
This is a list of things to try:
- Going to https://osu.ppy.sh/api/v2/changelog with Edge or Internet Explorer
- [Reinstalling .NET Core](https://dotnet.microsoft.com/download/dotnet-core)
- Execute `sfc /scannow` in an elevated command prompt to check for corrupted system files

**Comment by nahkd123** [comment]
Ok so I have to reinstall osu!lazer to make it works again.

**Comment by peppy** [comment]
Can you confirm that worked?

**Comment by nahkd123** [comment]
Yes it's works after reinstalled osu!lazer
