### ISSUE TITLE
Opening context menus on a touch screen

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#8046]
**Describe the new feature:** Currently it is impossible to open context menus using a touch screen. I would suggest adding the ability to touch & hold to open them.

**Comment by TheWildTree** [comment]
This would also be handy when using a tablet with its pen buttons disabled.

**Comment by bdach** [comment]
Support for touchscreen input is in general pretty non-existent, as for now we're pretending touches are mouse inputs (see ppy/osu-framework#1514 and linked issues). Going to go and close this for now as it's a known and obvious issue and work for mobile input is planned lazer-side anyways once we get round to it (tracked at #4201).
