### ISSUE TITLE
UI seemingly breaks when Alt+Tabbing on splash screen

### ISSUE THREAD

**Issue by inalone** [ppy/osu#8049]
**Describe the bug:** 
When I Alt+Tab out of osu!lazer on the initial "this is a development version" splash screen, and then Alt+Tab back in the UI seems to just completely break. This has happened with every version of osu!lazer since the first AppImage deployment version (cannot vouch for earlier versions). I am running Arch Linux.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/60921914/75588723-25c9ae00-5a71-11ea-96e2-8e404b7a644a.png)
![image](https://user-images.githubusercontent.com/60921914/75588785-4134b900-5a71-11ea-911d-baece451fb56.png)
![image](https://user-images.githubusercontent.com/60921914/75588807-4db91180-5a71-11ea-8c9e-19c448b4ff76.png)

**osu!lazer version:** 
2020.226.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/4269184/database.log)
[network.log](https://github.com/ppy/osu/files/4269185/network.log)
[performance.log](https://github.com/ppy/osu/files/4269186/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4269187/runtime.log)

**Comment by bdach** [comment]
Does the [reproduction scenario](https://github.com/ppy/osu/issues/7141#issuecomment-564011775) in #7141 match your case as well?

Also, could you try running the game with `--sdl` and seeing if it helps?

**Comment by inalone** [comment]
I'm not able to see if running with --sdl helps as I cannot change the display format (fullscreen etc.) in that mode.
That scenario did lead me to experiment, and although those exact steps did not personally yield me any results, spamming Alt+Enter did lead to this crash
```
  X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0xa32ca1
  Serial number of failed request:  43761
  Current serial number in output stream:  43762
```

I think I possibly didn't explain the scenario well. This issue arises when I'm in full screen, and alt tab back to my desktop, and then alt tab back into the game on the splash screen. No crash occurs, but the UI does seem to get a bit fucked

**Comment by bdach** [comment]
The two issues seem to be close enough in regards to the perceivable symptoms for me. Closing as duplicate for now.
