### ISSUE TITLE
Toolbar should stay hidden when the user hides it

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#8052]
Pressing <kbd>CTRL</kbd> + <kbd>T</kbd> hides the toolbar (when shown), but when navigating most screens it shows back and that makes the shortcut useless in this sense.

This may be also good for stable users who think the lazer ui has many elements on screen or just use shortcuts. Most overlays on the toolbar can be accessed using shortcuts already.

**Comment by Volnetiks** [comment]
Well, gonna fix it, do you have the list of the screens that make the toolbar back?

**Comment by Game4all** [comment]
Instead of applying the fix per screen, you may want to directly fix the screen logic behind this located in `OsuGame` https://github.com/ppy/osu/blob/5459b7e7da2d1de2b5e34d2541f17b85e8ac61b3/osu.Game/OsuGame.cs#L945-L952

**Comment by Volnetiks** [comment]
Thanks, i was looking for it, but cant find it, am gonna work on it

**Comment by cupppu** [comment]
Doing this seems to do the job, not sure this is logically sound though

https://github.com/cupppu/osu/blob/e0d0086fb23997d778ce8091915b363a93fbed4f/osu.Game/OsuGame.cs#L946-L959

**Comment by Volnetiks** [comment]
Well, it has been fixed, it will be in my next and first pull request

**Comment by cupppu** [comment]
I’ve replaced the entire if-else block to just running `Toolbar.Show();` and it seems to do the trick, not sure if this is logically sound though.

**Comment by Volnetiks** [comment]
> I’ve replaced the entire if-else block to just running `Toolbar.Show();` and it seems to do the trick, not sure if this is logically sound though.

I have replaced the else by an else if, it works and sounds logical

**Comment by cupppu** [comment]
Can I have a look at your implementation? I couldn’t find it in your repo

**Comment by bdach** [comment]
We can discuss the code when the PR is opened.

**Comment by Volnetiks** [comment]
Well, I only have this commit, but I can open the pr, or send the code here, as u prefer

**Comment by TheWildTree** [comment]
Opening a PR is fine I suppose.

**Comment by Volnetiks** [comment]
Well, lemme take my comp and open the pr

**Comment by bdach** [comment]
Issues aren't chat rooms - please keep idle chatter to a minimum.

**Comment by Volnetiks** [comment]
https://github.com/ppy/osu/pull/8055
