### ISSUE TITLE
Mania maps with slider velocity changes stutter when changing offset

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#8056]
If the audio offset is changed before playing a mania map that uses slider velocity changes, there will be a lot of stutters and extremely high update latency (update and draw fps will drop too). Unpredictable bug, doesn't always occur on the same audio offsets, also maps with more SV changes will stutter more often.
Video: https://youtu.be/SUlJauDumkl

No info in the logs as far as I can tell: https://www53.zippyshare.com/v/LvvZw2CM/file.html
Intel i5-7400, AMD HD7950, 8gb ram

**Comment by LanTenDragon** [comment]
Video is unavailable. Please check your permissions for the video?

**Comment by Joppe27** [comment]
> Video is unavailable. Please check your permissions for the video?
> 
> Even better if you link the beatmaps here directly.

Alright, these are the beatmaps that I tested: 
https://osu.ppy.sh/beatmapsets/484996#mania/1034385
https://osu.ppy.sh/beatmapsets/555076#mania/1174927
https://osu.ppy.sh/beatmapsets/1020073#mania/2134472

Video is on public seems like that link is just broken, try [this one.](shorturl.at/hFLP0)

**Comment by bdach** [comment]
That shortened link also seems broken, at least for me.

**Comment by Joppe27** [comment]
> That shortened link also seems broken, at least for me.

I'm sorry, can you try this one? https://youtu.be/SUlJauDumkI

**Comment by bdach** [comment]
Yeah, that one works. Thanks.

Looks like lots of things are happening on the update thread, but can't seem to reproduce myself. Would you mind taking another video, but this time with global statistics open? (press <kbd>Ctrl</kbd>+<kbd>F2</kbd> and scroll window that opens to the end). This section in particular I'd like to take a look at during gameplay:

![image](https://user-images.githubusercontent.com/20418176/75611617-5286cf80-5b1c-11ea-87ff-0e679666283a.png)

**Comment by Joppe27** [comment]
Here's the video: https://youtu.be/CR3nIZ6dtWw
Seems like ScrollingHitObjectContainer is the problem here, there is a lot of info in the performance logs now though, so make sure to take a look at that too: https://www19.zippyshare.com/v/xqWDvlYN/file.html
