### ISSUE TITLE
For "Increase visibility of first object when visual impairment mods are enabled," ignore Spinners and work after breaks.

### ISSUE THREAD

**Issue by CheeseManFuu** [ppy/osu#8063]
Spinners give no intuitive indication for rhythm, approach rate, circle size, or where the map will begin its structure, making this feature nearly pointless should a map start with a spinner (which for most cases will devolve into a normally usable spinner, just without the meter). 

My proposal is to find the first non-spinner object and remove visual impairment from it- whether spinners still have their visual impairment removed as well is neutral to me- and to also enable this for after breaks, to futureproof for maps that will feature variable AR and CS which most likely will be used in different sections with different pacing.

**Comment by peppy** [comment]
not sure about "after breaks", but definitely agree with the spinner change.
