### ISSUE TITLE
Switching keyboard layouts breaks input to textboxes

### ISSUE THREAD

**Issue by nathannino** [ppy/osu#8064]
**Describe the bug:** 
When doing the Windows + space shortcut to change keyboard layout, all textboxes will stop responding to keyboard input. I did check that it happened with the current version
**Screenshots or videos showing encountered issue:** 
Honestly, I thought I had already sent a bug report, but looking at my history, it seems I never got to reducing the length of the recording... anyways, here is a timed link of an older version:
https://youtu.be/ou1QkCFk1Bs?t=578
**osu!lazer version:** 
2020.229.1
**Logs:**
https://drive.google.com/open?id=1tcfRb6gjzGkXTP3f0bXn7uYCUOPq3G2I

**Comment by Gabixel** [comment]
Looks like the same problem with the Windows' Gaming Bar (see https://github.com/ppy/osu-framework/issues/2198). Could you please check if re-focusing the window fixes the issue?

**Comment by nathannino** [comment]
When refocusing and pressing another key, every key pressed in that textbox after doing the win + space shortcut appear, and the textboxes start functioning again. Thanks!

**Comment by bdach** [comment]
As this is tracked framework-side anyways I'll close this to avoid duplication. Thanks for confirming that this seems to be the same issue.
