### ISSUE TITLE
The mouse does not match the location in sliders 

### ISSUE THREAD

**Issue by miguel5862** [ppy/osu#8067]
Hello, 
Currently I am encountering this issue in beatmaps that have sliders, when the slider starts the game will recognize the initial click and if you follow the direction of the slide the game will register as if the cursor was slide properly, however once the slider ends the mouse pointer will be at the starting point not the end of the slider and it stays at that location for a while before I am able to move it afterwards, I hope this is not a duplicate error since I checked before posting but I did not find this specific error.

https://youtu.be/d7B3x2SjNHI

2020.229.1

[database.log](https://github.com/ppy/osu/files/4271541/database.log)
[network.log](https://github.com/ppy/osu/files/4271542/network.log)
[performance.log](https://github.com/ppy/osu/files/4271543/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4271544/runtime.log)

Looking forward to any updates on this, also thanks a lot for including to the Linux community :)

**Comment by bdach** [comment]
What input device are you playing with, and are you using raw input?

**Comment by miguel5862** [comment]
> What input device are you playing with, and are you using raw input?

I am currently using the trackpad of the laptop, I tried using raw input and add a little more of sensitivity, but somehow that ended up inverting the input on the vertical axis, so if I tried to go up would go down and trying to go down would make me go up, I did disable the scroll option of the trackpad to play and the physical buttons since Ubuntu by default disables the physical buttons and uses the tap option instead, and I like to play using the keyboard anyway.

**Comment by smoogipoo** [comment]
Short sliders can be completed by only pressing the circle. as long as your cursor remains within the big "follow circle".

This sounds like your trackpad is blocking input for a little while - perhaps it's trying to detect a double-tap or similar. This'll probably be improved with better touch recognition.

Does the same issue occur if you use the keyboard buttons to click the circles? (z/x or you can adjust in the settings).

**Comment by miguel5862** [comment]
> Short sliders can be completed by only pressing the circle. as long as your cursor remains within the big "follow circle".
> 
> This sounds like your trackpad is blocking input for a little while - perhaps it's trying to detect a double-tap or similar. This'll probably be improved with better touch recognition.
> 
> Does the same issue occur if you use the keyboard buttons to click the circles? (z/x or you can adjust in the settings).

I am currently using the x and z buttons, for the game video that I uploaded, is there any option to disable the touch as click on the game by any chance, or to modify in the code to see if that's the issue?

**Comment by smoogipoo** [comment]
You could try pressing F10 to disable mouse buttons during gameplay.

**Comment by miguel5862** [comment]
> You could try pressing F10 to disable mouse buttons during gameplay.

Those are actually disabled already, the same as scrolling, touchpads are kinda gimmicky so I disable those options at the beginning, but now I am wondering if maybe the game is recognizing any movement of the touchpad in general as a press of a button.

**Comment by miguel5862** [comment]
Update: So after playing with the settings for a while, it seems that I had the option of, disable trackpad while typing, on the mouse settings of Ubuntu, somehow while playing the system thinks that using the z/x buttons on the keyboard is actually typing on a text editor (maybe), instead of recognizing the input being used for a game, which is why the cursor does not move despite the game recognizing the sliders, turning off this option seems to solve the issue, even though is still get some drifting from time to time. 

Not sure whether this whether you would like me to close the issue as resolved or if this is something that needs to be patched later on, since I can see a lot of people having this feature active on their laptops and encountering this problem without knowing how to solve it, but I thought that I should let you know.

**Comment by smoogipoo** [comment]
Closing as resolved.
