### ISSUE TITLE
The Timing on Osu!mania doesnt work properly

### ISSUE THREAD

**Issue by CrazinessUwU** [ppy/osu#8069]
The timing in the gameplay doesn't work properly. i don't really know how to describe it but i can give an example.

Try this level in both Osu! and Osu!Lazer and you will see the differents 
- Aleph 0

**Comment by bdach** [comment]
"doesn't work properly" is nowhere specific enough for us to even begin investigating. Please elaborate or provide comparisons.

Closing until further details are provided.
