### ISSUE TITLE
Osu!mania Missing finished screen

### ISSUE THREAD

**Issue by CrazinessUwU** [ppy/osu#8071]
When i finished a level, i can't see my progress load,

**Comment by bdach** [comment]
I assume you mean there's no results screen. I can't reproduce this myself - please state your platform and provide logs or video if possible.

**Comment by smoogipoo** [comment]
Can't replicate either, need beatmap.

**Comment by smoogipoo** [comment]
Closing as this issue is stale and has likely been resolved in recent times.
