### ISSUE TITLE
Holding note past end in mania misses instead of giving 200

### ISSUE THREAD

**Issue by CrazinessUwU** [ppy/osu#8072]
In Osu! , we hold the slider to have the combos, when the slider is ended, although we didn't release the keyboard but it don't count as a MISS and give is lower points
 
In Osu!Lazer , sliders work the same way but somehow we didn't release the slider but it still count as a MISS
 
Pls fix it

**Comment by enoslayd** [comment]
I think the lazer one is the right implementation

**Comment by bdach** [comment]
Renamed to be a bit more descriptive.

Not a mania player but I vastly prefer lazer behaviour. Holding notes past their end to get the auto 200 punishes players who actually release notes but a bit late. This is however a point of gameplay discussion so I'll leave it open for now.

**Comment by enoslayd** [comment]
I think the lazer one is the right implementation

**Comment by peppy** [comment]
intentional for now
