### ISSUE TITLE
Display/timing of hold notes on map with low SV inconsistent with stable

### ISSUE THREAD

**Issue by CrazinessUwU** [ppy/osu#8073]
The timing in 2 differents gameplay will explain the detail of the issue since i can't explain it
- Osu!Lazer : https://youtu.be/NHaj2GvI3Kw at 2:00
- Osu! : https://www.youtube.com/watch?v=jE8wqdWHvWs at 1:40

Pls fix it

**Comment by enoslayd** [comment]
also, i noticed that theres a bar (maybe its a note) inside the sliders on the said part

**Comment by bdach** [comment]
The map seems to be leveraging extreme SV/BPM values to achieve visual effect seen in stable. Probably could bring under scope of #750.

**Comment by peppy** [comment]
please provide a link to the beatmap.

**Comment by bdach** [comment]
It's [this one](https://osu.ppy.sh/beatmapsets/518951#mania/1102580).

**Comment by smoogipoo** [comment]
For now this is intended. We might add compatibility for this at a later point, but for now we have sane limits in place that break these sort of maps. This is definitely under #750.
