### ISSUE TITLE
Hold note ticks give combo while they don't in stable

### ISSUE THREAD

**Issue by CrazinessUwU** [ppy/osu#8076]
In  Osu! sliders give combos, but Osu!lazer seems to be a little but error, so try to fix it

Also when holding sliders, the scoreboard shows that im 300 points ( perfect)  every beat so disable it too...

Fix fix fix

**Comment by bdach** [comment]
As far as I can see this was [explicitly intended](https://github.com/ppy/osu/pull/873/commits/9ec6e0b692cf14b31e07079264aeceb736025d49). lazer is not a 1:1 remake of stable in all cases, there have been some conscious changes, so it's not a "fix it" type of situation, more of a discussion point.

**Comment by smoogipoo** [comment]
Hold notes in stable don't actually "give" combo. They fake it, but it doesn't actually have any effect towards your score.

Lazer's is a little different in this regard, as it _does_ have an effect. This is intentional.
