### ISSUE TITLE
Perfect mod checks ignore judgements incorrectly

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#8078]
**Describe the bug:** 

When I got a GREAT I lose with perfect mode

**Screenshots or videos showing encountered issue:** 

https://youtu.be/Zs18Z9X8bz8

**osu!lazer version:** 

2020.229.1

**Logs:**
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*
Android

**Comment by bdach** [comment]
This is actually another regression from #7973. `IgnoreJudgement` has a `MaxResult` of `HitResult.Perfect`, but perfects aren't a thing in standard.

**Comment by MTGPROD** [comment]
Perfect is GREATs, so why if I get a GREAT which is the highest "grade" we can get can make us lose. Especially at the end of a slider. On a EASY map.

**Comment by bdach** [comment]
Perfects in _code_ nomenclature are mania- and catch-exclusive. As I said this is an actual bug that needs fixing. And please, drop the attitude.

**Comment by MTGPROD** [comment]
Sorry if I misspoke.
