### ISSUE TITLE
Seeking through autoplay on mania causes long notes to appear as "meh"

### ISSUE THREAD

**Issue by revelsix** [ppy/osu#8082]
**Describe the bug:** After seeking backwards using autoplay, any uninterrupted chain of long notes will be judged as meh

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=9Ux_KmvpYJ0

**osu!lazer version:** 2020.229.1

**Logs:** unnecessary

**Comment by smoogipoo** [comment]
Seems like some drawable states not being reset correctly on rewind.
