### ISSUE TITLE
Osu Lazer does not launch

### ISSUE THREAD

**Issue by GoldenGmrYT** [ppy/osu#8083]
The installer never shows up on screen, it just sticks on the taskbar and installs osu lazer. the shortcut for osu appears on the desktop but when i open it nothing happens

Video Here: https://youtu.be/6Tk5ocuTbVg

osu!lazer version: 2020.229.1

[runtime.log](https://github.com/ppy/osu/files/4273100/runtime.log)

My Specs:
Windows 10 Professional 64 Bit
4 GB Ram
Processor: Intel(R) Core(TM)2 Duo CPU    E7600 @2.93Hz  2.93 GHz
![Screenshot (22)](https://user-images.githubusercontent.com/61070658/75640529-62c5aa00-5c03-11ea-802a-6edd2dff55d4.png)

**Comment by smoogipoo** [comment]
Please post crash logs from Windows Event Viewer.

**Comment by GoldenGmrYT** [comment]
Where can i find them, cause windows event viewer is confusing

**Comment by GoldenGmrYT** [comment]
Nevermind i know where to get them

**Comment by GoldenGmrYT** [comment]
Ok so i cleared my crash logs then i tried launching osu lazer. here's the file. had to send in zip format because .evtx files are not supported


[Osu Crash Log.zip](https://github.com/ppy/osu/files/4273477/Osu.Crash.Log.zip)

Heres the log i had before clearing if needed:

[312020 event log.zip](https://github.com/ppy/osu/files/4273480/312020.event.log.zip)

**Comment by smoogipoo** [comment]
Ouch, that's a pretty rough one. There are two things you could try:

1. Make sure you've got all Windows updates installed.
2. The issue can occur due to your drivers. Try running osu! with the `--sdl` flag (via a shortcut, or via the command line).

**Comment by GoldenGmrYT** [comment]
All windows updates are installed. i think im using an insider build but i dont think that would cause any errors.

How do i run it with "--sdl flag"

**Comment by smoogipoo** [comment]
You could actually just edit the shortcut already on your desktop (right click -> edit), then add `--sdl` to the `Target` textbox.

**Comment by GoldenGmrYT** [comment]
Ok thanks, I'll try that tomorrow. Got to sleep

**Comment by GoldenGmrYT** [comment]
Tried but a blank screen shows up then it crashes without an error message. ask me for anything you need

**Comment by GoldenGmrYT** [comment]
Tried but a blank screen shows up without an error message. if you need any info ask me.

**Comment by smoogipoo** [comment]
I just noticed that your GPU is an Intel G41. This has a maximum capability of OpenGL 2.0, which lazer doesn't support yet.

Support will be added at some point in the future, but is not our current focus.

**Comment by GoldenGmrYT** [comment]
Welp i guess its time to upgrade. thank you for your help

**Comment by Gen-Kay** [comment]
> I just noticed that your GPU is an Intel G41. This has a maximum capability of OpenGL 2.0, which lazer doesn't support yet.
> 
> Support will be added at some point in the future, but is not our current focus.

I have the same exact problem shown in the video, tried two different graphics cards on my laptop with one that supports 1.2 to 4.6 and still no change in the issue.

**Comment by bdach** [comment]
@Gen-Kay please open a separate discussion for your problem as i do not believe it is the same.
