### ISSUE TITLE
Freeze after clicking a hitobject and then pausing/resuming

### ISSUE THREAD

**Issue by Kriper1111** [ppy/osu#8093]
**Describe the crash:** 
lazer completely freezes if I click the yellow cursor after clicking a slider and then pausing and resuming the game.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/qayjl

**osu!lazer version:** 
2020.229.1

**Logs:**
[network.log](https://github.com/ppy/osu/files/4275383/network.log)
[performance.log](https://github.com/ppy/osu/files/4275384/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4275385/runtime.log)
[database.log](https://github.com/ppy/osu/files/4275386/database.log)

**Computer Specifications:** 
Encountered on my Redmi Note 2
OS: Android 5.0.2
RAM: 2GB
Chipset: Mediatek MT6795 Helio X10

I was able to reproduce it on Lenovo TB-X304L
OS: Android 8.1.0
RAM: 2GB
Chipset: Qualcomm MSM8917 Snapdragon 425

**Comment by Kriper1111** [comment]
I managed to reproduce it using a spinner (on my [tablet](https://streamable.com/11jy3) and my [phone](https://streamable.com/q7w08)).
My guess it has something to do with pausing at/around the time when hitsound is playing.

**Comment by smoogipoo** [comment]
This should be fixed via https://github.com/ppy/osu-framework/pull/3354

Please test again on the next release.

**Comment by Kriper1111** [comment]
Yep, seems to be fixed.
