### ISSUE TITLE
Relax mod spams clicks when cursor is off note

### ISSUE THREAD

**Issue by Repulles** [ppy/osu#8096]
While using relax mode the game/relax is clicking keys like +/-100 times per note if the cursor is off the note. 
It's fine when cursor is on the note (single click).

**Comment by bdach** [comment]
Can't reproduce, mind linking the beatmap & providing some video evidence?

**Comment by Moltanicaa** [comment]
https://youtu.be/jqhQq_fXq7A - the cursor should be close to the note

**Comment by smoogipoo** [comment]
Can definitely be replicated, thanks.

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu/pull/8522.
