### ISSUE TITLE
Slider breaks should be counted and shown on the results screen

### ISSUE THREAD

**Issue by hostilew** [ppy/osu#8102]
**Describe the new feature:** The results screen should show sliderbreak count in some way. Sliderbreaks are a pretty important play statistic and one of the (hopefully) easiest to track that isn't already displayed. New players also get confused by them because they aren't tracked anywhere.

**Proposal designs of the feature:** No proposal for design.

**Comment by smoogipoo** [comment]
This will happen in some fashion.

**Comment by Moltanicaa** [comment]
I don’t know if this is a bug or the way it should be, but I am inclined to believe that it should be.

![osu_2020-03-26_14-52-51](https://user-images.githubusercontent.com/59089206/77611795-017ac780-6f72-11ea-95a9-0c9b81e8070d.png)

If you did not finish the slider, then the combo gets lost, but the accuracy is still 100%. Maybe it should be 100 points or miss? Although I would like it to stay that way.

**Comment by Joehuu** [comment]
Added in https://github.com/ppy/osu/pull/10405 (in the form of slider ticks/ends).
