### ISSUE TITLE
Hiding in-game UI doesn't hide "press for menu" 

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8110]
**Describe the bug:** 
When you press Shift+Tab, all in-game UI is hidden except for the "press for menu" X at the bottom right corner. It fades to low opacity but is still clearly visible when not surrounded by any other UI. 

**Screenshots or videos showing encountered issue:** 
![osu_2020-03-03_20-38-12](https://user-images.githubusercontent.com/11320483/75807961-f8417500-5d8e-11ea-8f42-d5debeea88ac.png)

**osu!lazer version:** 
2020.229.1

**Comment by bdach** [comment]
I'm pretty sure that is intended for UX/accessibility reasons.

**Comment by LittleEndu** [comment]
Could this at least fade to 0% ? It honestly feels like there's dirt on my monitor.
