### ISSUE TITLE
Using a notification to view a beatmap while search filter wouldn't display it breaks searching

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8111]
**Describe the bug:** 
After downloading a beatmap from direct, if you click on the notification that says "View this beatmap" some difficult of said beatmap is displayed no matter what, even if your current search query would filter the beatmap out. 
The result is some funcky unexpected behaviour. Sometimes the song shown to you isn't even the one you clicked the notification for. Searching is broken for some time but recovers after you clear the query. Navigating away from the selected beatmap seems to also restore search functionality.

**Screenshots or videos showing encountered issue:**
![osu_2020-03-03_21-23-40](https://user-images.githubusercontent.com/11320483/75811873-df888d80-5d95-11ea-9aca-765a0a92c63e.png)

**osu!lazer version:** 
2020.229.1

**Logs:**
[notification-bug-logs.zip](https://github.com/ppy/osu/files/4283208/notification-bug-logs.zip)

**Comment by peppy** [comment]
It is intended that it bypasses the search to display the beatmap, but it should be the correct one. Will look into this.
