### ISSUE TITLE
Mod selection hotkeys conflict with music player control ones

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8114]
**Describe the bug:** 
When in mod selection, trying to select mods with hotkeys will conflict with music player controls if you have them set to same keys. While music controls aren't mapped to <kbd>Z</kbd><kbd>X</kbd><kbd>C</kbd><kbd>V</kbd> by default they were in stable. And mod selection hotkeys aren't user remappable.

**osu!lazer version:** 
2020.229.1

**Comment by peppy** [comment]
If you set the music controller to use those keys, you won't be able to use them ANYWHERE in the game. They are global key bindings.

Out of scope.
