### ISSUE TITLE
Skins doesn't work on osu!lazer 2020.229.1

### ISSUE THREAD

**Issue by denielt** [ppy/osu#8120]
**Describe the bug:** I tried to create a folder "skins" in /home/user/.local/share/osu but when I start the game, there's nothing but the "osu! lazer" and "osu!classic" in the skin options, even after I put a theme folder inside the "skins" folder, I can only choose the default options. When I drag the "osk" file into osu!lazer the theme is loaded and installed perfectly, right after that it appears in my configuration options and things work. The problem is that I can't do something like that on Android, I can't drag the "osk" files into osu!lazer; on android, the themes are not installed after I create the "skins" folder inside the android/data/sh.ppy.osulazer/files/skins

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2020.229.1

**Logs:**
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*

**Comment by mcendu** [comment]
osu!lazer does not support the directory-based layout of the old client.

**Comment by peppy** [comment]
Android import support is still a work in progress.
