### ISSUE TITLE
UI QOL suggestions

### ISSUE THREAD

**Issue by Nepzd** [ppy/osu#8124]
I'll just list the things i noticed when i played lazer's current build (2020.229.1)

During key config screen, i cant click on the main settings tabs, forcing me to either click the small back button or click outside the window.

Scrolling down in beatmap select nukes my fps, i assume during map background loading, Maybe extend the number of beatmap images preloaded instead of the ones already in the screen?

In the menu select (the part that has solo, multi), maybe rename chart as leaderboard/ranking? It was misleading at first.

Clicking on the profile tab, and then the notification tab doesnt close the profile tab. Kinda annoying when you want to see notifications immediately, coz you have to close the profile tab first before opening the notif tab. Same goes with the music player, i feel like whenever you should click on any of the top right tabs, the current open tab should be minimized.

I dont think should have to click 2-3 times outside the open tabs to go to the main menu screen

Add an option to add a beatmap to a collection when right clicking a beatmap. (or im dumb and didnt notice a better way to do it)

Clicking on the the beatmap card (not the difficulty card, idk what to call it) should make me immediately play the selected map and not have to click on the smaller difficulty card, but still have the option to do so.

When viewing a score, the 300,100,50,miss count is cut from the circular background.

During map loading, the mapper should be the person who mapped the diff, not the one who posted it unless he/she is the one who made the diff.

A more lenient version of notelocking. It feels too cheesy at my level to spam and double tap bursts that i am aware is far beyond my current level.

Side note i noticed a lot of visual tearing which was absent in stable, is it my pc's fault or the game itself?

**Comment by peppy** [comment]
Please open one issue per issue. Also search first, as many are already covered.

Also, performance issues are a constant work in progress and don't need issues
