### ISSUE TITLE
Quickly changing beatmaps in song select screen using arrows can move you to the top

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#8126]
**Describe the bug:** When using right arrow to scroll downwards, it will move you to the top, and using the left one, it will move to the bottom of song select.

**Screenshots or videos showing encountered issue:** https://youtu.be/2stwzSzrwyY

**osu!lazer version:** 2020.229.1

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4285272/runtime.log)

**Comment by peppy** [comment]
Quite potentially related to https://github.com/ppy/osu/issues/8111, which I am currently investigating.

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/3051
