### ISSUE TITLE
Legacy skins incorrectly apply AllowSliderBallTint to sliderfollowcircle

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8137]
**Describe the bug:** 
Legacy skins have two elements that follow the slider: sliderbN and sliderfollowcircle. When AllowSliderBallTint is enabled in the skin.ini, slider ball is supposed to get tinted the same color as the combo color is (in stable there is an setting to overwrite this skin behaviour) but the follow circle is supposed to stay the same color as it is. 

**Screenshots or videos showing encountered issue:** 
Screenshots using stable's default skin template where only edit is ``AllowSliderBallTint = 1``

![osu_2020-03-04_20-42-39](https://user-images.githubusercontent.com/11320483/75912074-47ec7300-5e59-11ea-8a9e-8a849daf0e16.png)
![screenshot180](https://user-images.githubusercontent.com/11320483/75912122-5d619d00-5e59-11ea-8e5f-dd13dd35ffef.png)

**osu!lazer version:** 
2020.229.1

**Comment by LittleEndu** [comment]
This has regressed

**Comment by bdach** [comment]
Proof would be appreciated, but I guess I can check myself in a bit.

**Comment by LittleEndu** [comment]
I was curious how would the proof be any different than what I posted in the beginning? So if one says this has regressed and the state is the same as it was before, how would they prove it???

**Comment by bdach** [comment]
For example, by recording a video of the regression and then opening the settings menu and scrolling to end to show build version.
