### ISSUE TITLE
It takes the game a solid 20-30 seconds the load, both on startup and on the menus.

### ISSUE THREAD

**Issue by Nalalian** [ppy/osu#8144]
**Describe the bug:** Whenever I launch both the game and when I press the play button, it takes the game around 20-30 seconds to process and get to the menus.

**Screenshots or videos showing encountered issue:** https://vimeo.com/395738998 - Long loads on game startup. https://youtu.be/TfON3Kezh8E - Long loads from main menu to osu! interface
**osu!lazer version:** 2020.229.1

**Logs:** https://www.dropbox.com/s/ryjwzniz4a2bivk/logs.rar?dl=0

**Comment by peppy** [comment]
Could you please provide system specs?

**Comment by Joehuu** [comment]
Closing as stale. Performance should be greatly improved since.
