### ISSUE TITLE
quite big input lag

### ISSUE THREAD

**Issue by parvizchmo** [ppy/osu#8146]
1)while playing map (and moving cursor quite fast) fps drops well and input lag(or latency) goes from 4-6 to 7-11 (4-6 is too bad, but i don't know why it's so big). Also i see that lags become bigger when map have some sliders (3-5).
2)https://imgur.com/a/7GWWwyj
3)2020.229.1
4)https://www.dropbox.com/s/rzi13cnk7ugjcaj/logs.rar?dl=0
if i made mistakes in the text i'm sorry

**Comment by parvizchmo** [comment]
So, i did all things(+reinstall the game with deleting all files) and it didn't help at all. The same problem

**Comment by parvizchmo** [comment]
is it possible to solve this problem? Or i need to wait for new updates?

**Comment by peppy** [comment]
if you can't provide any more diagnosis information (or even include your system space) your best option is to wait.
