### ISSUE TITLE
First hitcircle not vanishing with HD

### ISSUE THREAD

**Issue by IzukWow** [ppy/osu#8153]
When you play Hidden on osu! stable the approach circle of the first object (unless changed in the settings) shows up while the object itself vanishes like all others.
In osu!lazer the object stays visible however.
This could lead to some weird reading situations if the beatmap starts with a stream or burst.

Screenshots:
https://imgur.com/a/Yg8nREW
The first screenshot is what the beginning of the beatmap looks like nomod.
The second one shows how it looks with HD on osu!lazer.
The third one shows how it would look on stable.

osu!lazer version:
2020.306.0

Logs:
[runtime.log](https://github.com/ppy/osu/files/4298136/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4298137/updater.log)
[database.log](https://github.com/ppy/osu/files/4298138/database.log)
[network.log](https://github.com/ppy/osu/files/4298139/network.log)
[performance.log](https://github.com/ppy/osu/files/4298140/performance.log)

**Comment by recapitalverb** [comment]
There's an option in the settings to disable this

**Comment by AlanGetar** [comment]
Yes

**Comment by Joehuu** [comment]
PR didn't address this issue, reopening.
