### ISSUE TITLE
no network connection

### ISSUE THREAD

**Issue by ackhack** [ppy/osu#8154]
**Describe the bug:** 
Login, osu!direct etc don't work. The only thing that needs an internet connection that works is the changelog.
game.ini does not cotain a token if that has any impact.
I have used wrong and right password, no change.
I have removed and readded osu! and osu!.exe in the firewall.
I already tried to reinstall the game.

**osu!lazer version:** 
2020.306.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/4298919/network.log)
[performance.log](https://github.com/ppy/osu/files/4298920/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4298921/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4298922/updater.log)
[database.log](https://github.com/ppy/osu/files/4298923/database.log)

**Comment by ackhack** [comment]
normal osu! works fine without any issues

**Comment by bdach** [comment]
Are you logging in with your username, or your email? Only username is supported since a while back.

**Comment by ackhack** [comment]
oh ok , that was the issue.
My email was still autofilled and i never read that this change happend
