### ISSUE TITLE
Can't find stable install folder

### ISSUE THREAD

**Issue by darc01** [ppy/osu#8156]
**Describe the bug:** 
I'm having problems importing skins from stable while all of the songs imported perfectly fine.
**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/vO8SwAV.png
**osu!lazer version:** 
2020.306.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/4299015/network.log)
[performance.log](https://github.com/ppy/osu/files/4299016/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4299017/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4299018/updater.log)
[database.log](https://github.com/ppy/osu/files/4299019/database.log)
[debug.log](https://github.com/ppy/osu/files/4299020/debug.log)

**Comment by jai-x** [comment]
Would you be able to specify the location where you have osu!stable installed?

**Comment by darc01** [comment]
D:\osu!

**Comment by jai-x** [comment]
osu!lazer only currently supports importing when osu!stable is installed in the standard install path. For windows this would be in `C:\\Users\<username>\%AppData%\Local\osu`. 

If you are using a custom install path such as on a different drive, then you will have to use a workaround such as using a symlink.

See: https://github.com/ppy/osu/issues/1907

Please also note that osu!direct is free on osu!lazer.

**Comment by xTerraUWU** [comment]
With also what they said. It needs to be in `C:\\Users\<username>\%AppData\Local\osu`. The problem should not happen again and if there is a problem again, most likely could be a loss of internet connection.

**Comment by bdach** [comment]
As an aside (as was also mentioned in discord): lazer should also be able to find your stable install if you've configured osu! file associations (`.osk`, `.osr`, `.osb`) to open with the stable client. Otherwise a symlink is your only escape hatch for now.

@xTerraUWU I fail to see why this particular error would have anything to do with network connectivity.

Closing as duplicate.
