### ISSUE TITLE
Skin Fonts do not load if directed to a subfolder

### ISSUE THREAD

**Issue by Gmaniko** [ppy/osu#8157]
Same issue as #6058 though they still won't load from a subfolder inside the skin folder. Here the HitCirclePrefix `blank` is located inside the subfolder `hitcircle4`:
`[Fonts]`
`HitCirclePrefix: hitcircle4\blank`

Lazer 2020.306.0

**Comment by bdach** [comment]
Please attach skin so that we can reproduce the issue.

**Comment by Gmaniko** [comment]
[here](https://azer1.s-ul.eu/ckGOMum0)

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu/commit/eff17c2da57f26fdafff02fc979e949abf7611c6.
