### ISSUE TITLE
Sporadic unusually loud hitsounds

### ISSUE THREAD

**Issue by AlanGetar** [ppy/osu#8162]
Sometimes a random loud hitsound appears when playing maps 

https://www.youtube.com/watch?v=37sbquNDYqQ (Time codes in comments)

2020.306.0

Logs
[network.log](https://github.com/ppy/osu/files/4300292/network.log)
[performance.log](https://github.com/ppy/osu/files/4300293/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4300294/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4300295/updater.log)
[database.log](https://github.com/ppy/osu/files/4300296/database.log)

**Comment by bdach** [comment]
For reference, maps:

https://osu.ppy.sh/beatmapsets/698526#osu/1479410
https://osu.ppy.sh/beatmapsets/689544#osu/1459621

I had a variant of the skin (albeit I *think* with different hitsounds) but could not reproduce.

**Comment by AlanGetar** [comment]
I'll check your questions tommorow (I'm almost sleeping) And this happens with all skins (as I remember, possibly I'm not right) I'll check that tomorrow and reply.

**Comment by AlanGetar** [comment]
Hi! so i tried this again today using 2 skins and playing the same map on osu! stable.
That's what i got  https://www.youtube.com/watch?v=nhFzcqKswek

Skins:
https://drive.google.com/open?id=1c5cfRJrCh4jwxVmqv17swfbRmM1nLpBz

Logs:
[network.zip](https://github.com/ppy/osu/files/4301760/network.zip)

**Comment by Spiritreader** [comment]
> 
> 
> For reference, maps:
> 
> https://osu.ppy.sh/beatmapsets/698526#osu/1479410
> https://osu.ppy.sh/beatmapsets/689544#osu/1459621
> 
> I had a variant of the skin (albeit I _think_ with different hitsounds) but could not reproduce.
> 
> @AlanGetar Is this consistent - every time on the same maps, on the same timestamps?

In my case it is not limited to the same map or the same timestamp. I can restart a map several times and usually trigger this behaviour within ~20-30 seconds.

**Comment by peppy** [comment]
@AlanGetar can you reproduce this with the default skin?
