### ISSUE TITLE
Gameplay clicking doesn't block global volume adjust

### ISSUE THREAD

**Issue by peppy** [ppy/osu#8169]
As reported [here](https://osu.ppy.sh/comments/1042399), it would seem that binding gameplay keys to down / up arrow don't block global volume adjust correctly.

**Comment by peppy** [comment]
I thought I could fix this one by returning `true` inside `RulesetKeyBindingContainer`, but apparently this doesn't actually block input from hitting things behind it? Am I missing something?

![image](https://user-images.githubusercontent.com/191335/76337609-f3566580-633a-11ea-9cba-e4b76edc6eb8.png)

**Comment by bdach** [comment]
Seems to be a side effect of `PassThroughInputManager` (and, by extension, `RulesetInputManager`) hard-returning false at the end of `Handle(UIEvent)`:

https://github.com/ppy/osu-framework/blob/2d2ec02f5551af99703b028eb386875c83071d59/osu.Framework/Input/PassThroughInputManager.cs#L116

The actual key binding container is returning `true` but then the input manager hard-coerces that to `false` and so it gets handled again on the way up at `GlobalActionContainer`.
