### ISSUE TITLE
Colour-related graphical glitches

### ISSUE THREAD

**Issue by rust2** [ppy/osu#8181]
I've updated osu!lazer and this happened to me...
Screenshots: https://4pda.ru/forum/index.php?act=findpost&pid=94568918&anchor=Spoil-94568918-1 (files deleted by moderators, sorry)

**Comment by bdach** [comment]
Seems like a GPU issue - judging from the colour mixups, I'd say most likely a pixel format mismatch (lots of cyan, red - so I'm betting on a channel mismatch).

* Does rolling back to a previous version help? If yes, which is the latest version that works?
* What is your GPU?
* Have you updated drivers recently?

**Comment by peppy** [comment]
Need details on what OS/hardware you're running on as well.

**Comment by rust2** [comment]
OS: Android 8.1 (Oreo); EMUI 8.1
Chipset | Mediatek MT6739 (28 nm)
CPU | Quad-core 1.5 GHz Cortex-A53
GPU | PowerVR GE8100

I forgot what ver. I played earlier

**Comment by bdach** [comment]
Has the situation changed in any way, or are the colours still broken?

**Comment by rust2** [comment]
> Has the situation changed in any way, or are the colours still broken?

Sorry i've deleted lazer 2 months ago and can't say changed it or no

**Comment by bdach** [comment]
I'll close this for now then. Please follow up if you decide to reinstall and it still happens.

**Comment by rust2** [comment]
> I'll close this for now then. Please follow up if you decide to reinstall and it still happens.

Sure
