### ISSUE TITLE
allow choosing which gamemodes can have converted beatmaps

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#8183]
this is being suggested because the converts are well converted in some gamemodes but not well converted in other gamemodes

**Comment by bdach** [comment]
Already supported:

https://github.com/ppy/osu/blob/e022352812371f6ce57cbbbbf0bc7b5ade7b856e/osu.Game/Beatmaps/WorkingBeatmap.cs#L92-L96

If you're questioning the *quality* of converts on some maps on existing rulesets then I guess the solution is to just not play them? I don't think heuristics or whitelists of convertible maps are going to happen.
