### ISSUE TITLE
Spikes on audio thread during device info retrieval

### ISSUE THREAD

**Issue by 2yangk23** [ppy/osu#8185]
**Describe the bug:** 
The game seems to be stuttering during gameplay. However, I don't see the frame rate really dropping, but you can tell from the video it's not quite right. Especially obvious from the hit-sounds, which are inconsistent (Auto)

**Screenshots or videos showing encountered issue:** 
https://streamable.com/5mbu0

**osu!lazer version:** 
2020.306.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/4304241/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4304240/runtime.log)

**Comment by peppy** [comment]
It looks like something on your audio thread is causing huge spikes. Does this happen at the menus as well?

If possible, could you turn on performance logging from settings and let it run for a bit, then attach the produced performance logs?

**Comment by 2yangk23** [comment]
Are those pink parts in the audio section the spikes? If so, they seem to always happen. When the game isn't focused, they are closer together, so it seems to be happening every X frames rather than on some time interval.

![image](https://user-images.githubusercontent.com/7710340/76180739-14bd2300-617c-11ea-9efd-667fcd1fa8d9.png)

Not able to find the setting to turn on performance logging, could you give more specifics for how to do this?

**Comment by peppy** [comment]
Right, my guess is that this may be related to checking for audio device changes. Also apologies, we changed the method of performance logging.

- Press ctrl-f2 to bring up the statistics overlay. the game is now logging in a high verbosity
- Wait a minute
- Close the overlay and attach performance log files (there should be one per thread, including audio).

Also, please go into your sound control panel and screenshot a list of your available audio devices.

**Comment by 2yangk23** [comment]
There was just 1 performance.log file (Compressed to keep it under 10MiB): [performance.zip](https://github.com/ppy/osu/files/4304853/performance.zip)
Was there somewhere else I should be looking for logs?

Audio Devices:
![image](https://user-images.githubusercontent.com/7710340/76186968-3ecd1000-6191-11ea-9ebd-74eb9768547d.png)

**Comment by peppy** [comment]
It looks like performance logging is not happening correctly. Will get back to you once this is fixed so we can analyse further.

In the mean time, please try disabling all audio devices except the one you are using and see if it helps.

**Comment by peppy** [comment]
Please give the above another shot after the next release (should come today or tomorrow). A fix for performance logging will be included.

**Comment by 2yangk23** [comment]
I built it myself to get the logs, not sure how much slowness is expected:
[performance-audio.log](https://github.com/ppy/osu/files/4315573/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4315574/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4315575/performance-update.log)

**Comment by peppy** [comment]
- Could you try using a different audio output
- Could you try disabling all devices you are not using
- Could you try updating your realtek audio drivers

**Comment by 2yangk23** [comment]
Tried other ouputs as well as all outputs disabled and still have high latency. Changed the polling rate in audio manager to be a lot slower and it fixed the problem so it's definitely the GetDeviceInfo call, though it's hard to say exactly what's making it slow.
