### ISSUE TITLE
Completing a beatmap can lead to its track having a low volume

### ISSUE THREAD

**Issue by MrTheMake** [ppy/osu#819]
Completing certain maps and waiting until the track has ended will result in a low volume track back at the song select screen.
The miscalculation of the volume is done in AdjustableAudoComponent::OnStateChanged(). The volumeAdjustments list contains 2 times the calculated volume modifier, resulting in the volume of the track being the square of the volume modifier. I could not point out why the list contains 2 items in this special case.

Video: https://streamable.com/x39l0 (recorded with v2017.520.0)
Beatmap: https://osu.ppy.sh/s/127712 played on Hard

**Comment by MrTheMake** [comment]
There are other situations in which the track's volume is low but the explained one seems to be the easiest one to reproduce.

**Comment by Jorolf** [comment]
I think the problem is that the Track gets reused and AudioCollectionManager::RegisterItem adds the dependency again

**Comment by Jorolf** [comment]
because of TrackManager::SetExclusive

**Comment by Jorolf** [comment]
So I guess there are three ways to fix this:
1. Disable adding the same dependency twice
2. Remove it and add it afterwards / check if it already has the dependency
3. don't reuse the track?
