### ISSUE TITLE
osu!Lazer "steals" audio

### ISSUE THREAD

**Issue by KittyLe** [ppy/osu#8191]
**Describe the bug:** 
When I start osu!Lazer and have something playing (i. e. YouTube video) I don't get sound in osu!, but as soon as I stop the video, osu! comes foreground and "steals" audio, so I can't get audio output in OBS and all YouTube videos stop working.

**Screenshots or videos showing encountered issue:** 
1. osu! "stole" the sound (osu! plays music, but OBS can't get audio and YouTube doesn't work)
![Снимок экрана от 2020-03-10 06-52-23](https://user-images.githubusercontent.com/41251521/76269413-95664700-6282-11ea-9013-c9f33ed6e65f.png)

2. YouTube works, OBS too but osu! doesn't output sound at all
![Снимок экрана от 2020-03-10 06-54-33](https://user-images.githubusercontent.com/41251521/76269479-e37b4a80-6282-11ea-8d07-fc6a6e5a2fe1.png)

**osu!lazer version:** 2020.306.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4309658/database.log)
[network.log](https://github.com/ppy/osu/files/4309659/network.log)
[performance.log](https://github.com/ppy/osu/files/4309660/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4309661/runtime.log)

**Comment by peppy** [comment]
Sounds like you have your audio device set to run in exclusive mode only. Or something else on your system is using exclusive mode. This is 99% not an osu! issue.

**Comment by KittyLe** [comment]
Yeah, after installing `pulseaudio-alsa` everything started working as it should.
