### ISSUE TITLE
Audio Latency

### ISSUE THREAD

**Issue by GDJason12** [ppy/osu#8207]
**Describe the bug:** When I play a map, the audio seems lag a bit and I hit the circle at a perfect time and hits a 50. I tried to move audio offset, changed audio device, nothing seems to fix the lag, and I am using wired headphones, and tried with speakers.

**Screenshots or videos showing encountered issue:** I don't have any video proof or screenshots(not reliable) screen recording not supporting my chromebook

**osu!lazer version:** 2020.306.0 for Linux

**Logs:** No logs

**Comment by peppy** [comment]
Note that you are on linux and this is likely a system configuration issue. Google for your audio subsystem (pulse or other) and how to improve latency.
