### ISSUE TITLE
Lazer will not open on osx versions older than 10.13

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu#8209]
**Describe the bug:** 
Laptop has some issues updating beyond 10.12.6, it will not open the app. Older instances of lazer work fine. Unsure when this was changed because the previous time I used lazer was in 2018.

**Screenshots or videos showing encountered issue:** 
![Screen Shot 2020-03-10 at 6 59 11 PM](https://user-images.githubusercontent.com/30382015/76374737-43183b00-6301-11ea-8e31-5fc0fc1a3d00.png)

**osu!lazer version:** 
latest

**Comment by peppy** [comment]
https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md

unfortunately no longer supported by .net core
