### ISSUE TITLE
Nested hit objects are loaded on the update thread

### ISSUE THREAD

**Issue by peppy** [ppy/osu#8210]
There's potential for moving this to `LoadAsyncComplete`. At the same time, this may need to change for pooling support, so is not an immediate focus.

![image](https://user-images.githubusercontent.com/191335/76376640-2412bb00-638c-11ea-810c-0ad611dc733f.png)

**Comment by peppy** [comment]
I think this can be closed as pooling has pretty much changed the flow here? Or should it be left open to track the fact that not all nested drawables are pooled?

**Comment by smoogipoo** [comment]
Well they're pooled where the ruleset supports it. Let's close.
