### ISSUE TITLE
Pause screen triggers immediate exit if mouse button is held

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#8214]
If you hold the left mouse button down while pausing a map, you'll immediately be booted to song select.

**Comment by peppy** [comment]
Can't seem to reproduce this one..

**Comment by smoogipoo** [comment]
This seems to be because I had Esc+M1 bound as a hotkey for quick exit. Not sure how that happened - I don't remember reordering the enum in such a way that this could've broken. Closing for now.

![image](https://user-images.githubusercontent.com/1329837/76728038-e7cec880-6798-11ea-8d14-b6c08419368b.png)
