### ISSUE TITLE
No exit button in tournament client when window is not wide enough

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu#8223]
**Describe the bug:** The tournament client should provide the exit button in accessible range so users who are using not wide enough monitor can (safely) exit tournament client instead of killing it.
My monitor is 1600x900.

**Screenshots or videos showing encountered issue:** 
![Screenshot_2020-03-11_20-44-02](https://user-images.githubusercontent.com/16283764/76423483-76c69400-63d9-11ea-99c8-d40cbf725826.png)

**osu!lazer version:** 2020.311.0

**Comment by peppy** [comment]
Alt-F4 or escape? I'm not sure I understand the issue here, did you resize the window off-screen?

**Comment by huupoke12** [comment]
Alt-F4 works but Esc doesn't exit the client. I have lazer running in fullscreen mode before (when in normal client), so it also opens the tournament client in fullscreen mode, so I can't adjust window.

**Comment by peppy** [comment]
F11 works to exit fullscreen (or alt-enter).

**Comment by huupoke12** [comment]
Ok, it works now. I think the existence of those shortcut key should be informed to the user.

**Comment by peppy** [comment]
They are pretty standard keys with decades of history. I think we'll be fine for now.
