### ISSUE TITLE
Change tournament score to using monospaced numbers

### ISSUE THREAD

**Issue by cupppu** [ppy/osu#8228]
**Describe the new feature:** 
~Not sure if it has been implemented yet because I don't know how to get the tournament client running but~ as titled, change display of team scores with monospaced number, should look cleaner
<img width="362" alt="image" src="https://user-images.githubusercontent.com/7279624/76443395-41f71480-63ba-11ea-8e07-7b8513324b87.png">

**Comment by peppy** [comment]
This was on my list of things to do but didn't get to it.
