### ISSUE TITLE
Autoplay doesn`t hit anything

### ISSUE THREAD

**Issue by Skandrax** [ppy/osu#8231]
The Autoplay mod misses everything but doesn't fail.
Tried different maps, doesn't seem to click.

![osu_2020-03-11_20-18-25](https://user-images.githubusercontent.com/61185857/76454847-8643de00-63d5-11ea-9e2a-1990cb242eeb.jpg)

osu!lazer version: 2020.311.0

Logs:
[database.log](https://github.com/ppy/osu/files/4320360/database.log)
[network.log](https://github.com/ppy/osu/files/4320361/network.log)
[performance.log](https://github.com/ppy/osu/files/4320362/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4320363/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4320364/updater.log)

**Comment by bdach** [comment]
Can't reproduce this. How are you triggering autoplay? I'm noticing a lack of the mod icon in the upper right corner in the screenshot you've attached - but then again, if the mod didn't apply the game should just outright fail...

**Comment by Skandrax** [comment]
Well, I just hit F1 then click on the Autoplay mod and start a map.

**Comment by Skandrax** [comment]
This is kind of akward...
I thought the right most mod was Auto (just like in normal osu!).
I selected autopilot -.-
Sorry for any inconvenience...
