### ISSUE TITLE
Keybinds disappearing from settings & no longer functioning ingame

### ISSUE THREAD

**Issue by Zamazenta** [ppy/osu#8232]
Installed lazer (2020.311.0) for the first time, after setting up everything I went to play and noticed I couldn't click anything with my left button, went to check settings and noticed that the keybind for "right button" was completely missing. I had changed both my left & right buttons before playing and both were in settings until I went to actually play. Even more strange, the right button functioned normally, and left button was the non-functioning one, despite "left button" being in the settings, and "right button" missing. Took a screenshot (below) before restarting the game which fixed the issue.

![osu_2020-03-11_15-16-14](https://user-images.githubusercontent.com/25157685/76456014-b75be880-63ac-11ea-93d9-9a21992b01b9.jpg)

**Comment by bdach** [comment]
* Please attach your `client.db` file (found at `%AppData%/osu/client.db`) and logs.
* If you rename `client.db` to anything else, does the binding return after restarting? (Please attach the DB *first* before checking that).

**Comment by Zamazenta** [comment]
Heres the files, but I've already restarted my game, so wouldn't that... "invalidate" the logs? Restarting WITHOUT renaming client.db also fixed the issue. I haven't been able to reproduce it to test if renaming client.db will have any effect.
[requested-files.zip](https://github.com/ppy/osu/files/4320575/requested-files.zip)

**Comment by bdach** [comment]
It does invalidate the logs. I was hoping the lack of binding would persist, but if it fixed itself upon restart and we no longer have any data to go on this is going to be nigh impossible to resolve.

**Comment by Zamazenta** [comment]
Aw, my bad. If I had known I would've grabbed the logs before restarting, but I thought I would at least do some basic checks myself before making an issue.
Heres a list of essentially EVERYTHING I did before this happened
<details>
  <summary>Heres a list of literally EVERYTHING I did before this happened</summary>

-  Installed lazer for the first time
-  Opened game, lowered volume
-  Changed framerate limiter to 4x refresh rate
-  Set game to fullscreen
-  Imported skins
-  Picked a skin (Can supply the exact one if requested)
-  Imported beatmaps
-  Set keybinds, I am left handed so this is what I changed:
     -  left button = left arrow
     -  right button = down arrow
     -  quick retry = up arrow
    -  pause (back) = right arrow
-  Changed "menu cursor size" to 1.5x, not realizing there was a separate slider for in-game cursor size
-  Went to play a map
-  Realized that my left/right button were changing the volume (haha oops)
-  Went into settings and changed every conflicting keybind using arrow keys
-  Set background dim, as I had forgotten to do so earlier
-  Set in-game cursor size to 1.5x as I had noticed I set the wrong one
-  Went to play and realized I couldn't click anything with my left button
-  Went to settings and saw that the "right button" was missing

</details>

Maybe someone else will be able to get this to happen for them.

**Comment by Joehuu** [comment]
You had `l` inputted in the search bar. Closing as non-issue.
