### ISSUE TITLE
Song select doesn't autoselect after entering on no-beatmap ruleset

### ISSUE THREAD

**Issue by peppy** [ppy/osu#8239]
- enter song select with a ruleset that has no beatmaps
- switch to ruleset with beatmaps
- selection doesn't autoselect

Note that after manually making a selection, this starts to work as expected. Currently no test coverage.

![image](https://user-images.githubusercontent.com/191335/76495712-c4dfa400-647a-11ea-86ee-3c5b2ad507e3.gif)

**Comment by LittleEndu** [comment]
Should the behaviour added in #2332 be replaced with what I suggested in #2638 

Or do we want beatmap selection to always be random (including in this case)

**Comment by peppy** [comment]
You can give that a try, but i'm not 100% confident how clean the implementation is going to be. Unless it makes the code more readable than currently (there's still plenty of improvement to be made – and make sure to wait for my QoL PRs from today to get merged first as they improve it further) it will be hard to merge.
