### ISSUE TITLE
Add resolution settings for Mac OS

### ISSUE THREAD

**Issue by cupppu** [ppy/osu#8249]
**Describe the new feature:**  
Add a resolutions settings for Mac OS builds much like what we already have on windows, personally lazer runs really bad for me on Mac OS, where the draw framerates are consistently <= 60, but it's butter smooth on windows (bootcamp) with resolution scaled down to 1920x1200
![image](https://user-images.githubusercontent.com/7279624/76546691-dbd6c400-6483-11ea-83e9-2043280f2446.png)

**Comment by peppy** [comment]
We don't yet support exclusive fullscreen on macOS (and it's a bit far away to consider this just yet). When we do, these choices will become available.
