### ISSUE TITLE
Lag spikes when displaying animated judgement sprites

### ISSUE THREAD

**Issue by cupppu** [ppy/osu#8250]
**Describe the bug:**  
- Big lag spikes as much as 500ms when the game tries to display an animated judgement sprite (e.g. 100, 50, miss...) 
- Skin tested: [FlyingTuna's skin](https://skins.osuck.net/index.php?newsid=640)
- Most prominent right after game start up, sometimes it goes away after a while sometimes it doesn't
- applies to both gameplay and replay

**Screenshots or videos showing encountered issue:** 
~~will add link after the video finished uploading~~  
https://streamable.com/nejq1

**osu!lazer version:**  
2020.312.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/4325887/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/4325889/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4325890/performance-update.log)

**Comment by peppy** [comment]
For reference, the skin is loading 60 frames per judgement (110x220x60 = 132,000 pixels). Not enough that this should happen. @cupppu could you please delete your logs folder, reproduce this once with ctrl-f2 view up (the whole time) and do immediately quit and provide the logs agin? The ones you provided are a bit cluttered.

**Comment by cupppu** [comment]
Same map same skin as in video

[performance-audio.log](https://github.com/ppy/osu/files/4457151/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4457152/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4457154/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/4457155/performance.log)
[network.log](https://github.com/ppy/osu/files/4457163/network.log)
[runtime.log](https://github.com/ppy/osu/files/4457164/runtime.log)
[database.log](https://github.com/ppy/osu/files/4457150/database.log)

**Comment by peppy** [comment]
Can you confirm that this is still reproducible with all performance overlays turned off (Ctrl-F11 to off, Ctrl-F2 to off), on *every* judgement? I can get a minor stutter on first judgement but all future ones seem fine.

**Comment by cupppu** [comment]
I should've clarified: the lag only appears for the first judgement and then the rest is fine, but the judgements are independent of each other i.e. 50, 100, miss gets their own lag spikes.
I still need to see if this is reproducible with Ctrl-F11 completely off
Do note though, my machine is a 2012 macbook so it's quite slow and might have magnified the issue

**Comment by peppy** [comment]
Thanks for the clarification. I think this is enough to understand how this could be an issue (since I can reproduce on a high end system with the provided skin).

**Comment by smoogipoo** [comment]
Should be addressed via https://github.com/ppy/osu/issues/6136 . Something like a "prepare" method which creates some initial objects during BDL-load.
