### ISSUE TITLE
Soft keyboard input not working on android

### ISSUE THREAD

**Issue by HailfirEthan** [ppy/osu#8264]
**Describe the bug:** 
When using the username/password field on android, only certain characters like @ will be recognized.
**Screenshots or videos showing encountered issue:** 
http://imgur.com/a/LYUHx9e
**osu!lazer version:** 
2020.306/311.0

**Comment by peppy** [comment]
Please try a different keyboard (and let us know which one is failing).

**Comment by HailfirEthan** [comment]
I used an external keyboard (dz65) and it worked fine. The keyboard I used
was the stock Samsung keyboard in an s20.

**Comment by MTGPROD** [comment]
For persons who meet this problem, use SwiftKey keyboard 👍

**Comment by aliencaocao** [comment]
> For persons who meet this problem, use the [SwiftKey keyboard](https://www.google.fr/url?sa=t&source=web&rct=j&url=https://play.google.com/store/apps/details%3Fid%3Dcom.touchtype.swiftkey%26hl%3Dfr%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Dswiftkey%26pcampaignid%3DAPPU_1_SH6PXpepJrSLjLsPvo-VwA0&ved=2ahUKEwiX7b7FkNzoAhW0BWMBHb5HBdgQ8oQBMAB6BAgREAM&usg=AOvVaw2B4oT7L_FVYZ0yuAceI45R)👍
> 
> (Until this is fixed) 

just tried microsoft swift keyboard, does NOT work at all.

MIUI 12.5 android 11 Oct security patch

**Comment by AruMoon** [comment]
Same issue

> For persons who meet this problem, use the [SwiftKey keyboard](https://www.google.fr/url?sa=t&source=web&rct=j&url=https://play.google.com/store/apps/details%3Fid%3Dcom.touchtype.swiftkey%26hl%3Dfr%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Dswiftkey%26pcampaignid%3DAPPU_1_SH6PXpepJrSLjLsPvo-VwA0&ved=2ahUKEwiX7b7FkNzoAhW0BWMBHb5HBdgQ8oQBMAB6BAgREAM&usg=AOvVaw2B4oT7L_FVYZ0yuAceI45R)👍
> 
> (Until this is fixed)

Same issue

**Comment by aliencaocao** [comment]
Wow so adding that the provided 'workaround' of swift keyboard does not work is being marked as 'spam'? What a hopeless development community! I used to think osu lazer is cool but now i cannot even login, guess it is too cool for me

**Comment by bdach** [comment]
just in case this gets posted somewhere: comments above were marked as spam as they were contributing nothing useful to the discussion. we know this is an issue, and there are changes pending review that may resolve the problem (https://github.com/ppy/osu-framework/pull/4907/). until then please be patient. i locked conversation to stop more "+1" comments from piling on.

**Comment by peppy** [comment]
Bumping to priority zero as the level of reports and competency of reports is getting noisy.

**Comment by peppy** [comment]
Also this issue is quite dated and likely a different issue altogether than the more recent regression we are seeing.

**Comment by bdach** [comment]
Today's hotfix release with IME changes included should have improved matters. I am going to unlock this thread and leave it open for a bit to see if we get any new reports about broken keyboard, and if it's silent for long enough, we can consider closing.

**Comment by Texrot** [comment]
Hello.
Unfortunately I face the same issue.I tried 4 keyboard applications and none of them worked including SwiftKey.
I also tried changing the language and the layout but none of them works.
Version : 2021.1211.0, downloaded from version release

**Comment by peppy** [comment]
@Texrot Could you please provide log files after typing something in the game? Not sure how helpful they will be but maybe we can figure something out from them.

**Comment by Texrot** [comment]
I don't know where log files are located and I can't find any directory related to osu lazer

**Comment by frenzibyte** [comment]
Should be located in `Android/data/sh.ppy.osulazer/files/logs`, copy and attach here after typing something out and before restarting the game again so the logs don't get overwritten.

**Comment by Texrot** [comment]
I opened the game and typed something in my own language and English. The game is in the background and the logs are like these right now. Tho I can't import the files here for some reason so I'll try to upload it to a third party site

**Comment by Feodor0090** [comment]
[runtime.txt](https://github.com/ppy/osu/files/7741790/runtime.txt)
MIUI 12.0.5. Default keyboard. 
Login form reacts only on Enter key. No characters can be typed. Settings search box too.
Maybe an important detail: text that i have tried to type into login field stays in keyboard autocomplete form even after keyboard closing and even after switching to setting's search. Seems like input is being accumulated somewhere and doesn't reach textboxes.

**Comment by Susko3** [comment]
@Feodor0090 if you tap on the autocomplete text, does it get typed in?

**Comment by Feodor0090** [comment]
> @Feodor0090 if you tap on the autocomplete text, does it get typed in?

Trying to type into login field:
![Screenshot_2021-12-20-11-01-31-058_sh.ppy.osulazer.jpg](https://user-images.githubusercontent.com/53872073/146737273-609617ac-8f37-40c5-b6ea-970146652e11.jpg)
Pressing on autocomplete:
![Screenshot_2021-12-20-11-01-40-387_sh.ppy.osulazer.jpg](https://user-images.githubusercontent.com/53872073/146737332-bf24f2b2-e7fd-458f-8d5c-e9ca292c99a4.jpg)
Typing qwerty as password:
![Screenshot_2021-12-20-11-01-57-232_sh.ppy.osulazer.jpg](https://user-images.githubusercontent.com/53872073/146737377-acd73a07-5642-4ff5-8d4f-f7735614f9ce.jpg)
Closing keyboard, switching to settings, typing "sets" there:
![Screenshot_2021-12-20-11-02-13-973_sh.ppy.osulazer.jpg](https://user-images.githubusercontent.com/53872073/146737491-8bfe8b78-1266-4a85-a050-3ca6730ab8bb.jpg)
Pressing autocomplete:
![Screenshot_2021-12-20-11-02-20-823_sh.ppy.osulazer.jpg](https://user-images.githubusercontent.com/53872073/146737548-b4e0cfcf-7fa2-4d74-8c20-b9a809976d98.jpg)

**Comment by Feodor0090** [comment]
Immediatly fields are reacting only on Enter and backspacing (characters are being removed from a field, but not from input system - first FE and one of login inputs were erased, but they stayed in keyboard's menu)
