### ISSUE TITLE
Osu!Mania scroll speed selection 

### ISSUE THREAD

**Issue by TheEZIC** [ppy/osu#8274]
Please add choice in option menu to select between new and old versions of scroll speed selection in osu!mania game mode. I and most of the players in our community cat`t normally play without old scroll speed system.

**Comment by bdach** [comment]
Discussion in #6263 is potentially related?

**Comment by TheEZIC** [comment]
I don`t think so. Because we wont to change scroll speed not in milliseconds, but in string number like in osu! stable.

**Comment by peppy** [comment]
it's the same thing?

**Comment by TheEZIC** [comment]
In osu!lazer we chose scroll time in milliseconds, and we can`t find same property like in osu!stable number system. It`s very important, because it is very difficult to get used to the new system.

**Comment by peppy** [comment]
so you just want to know the number to ms mapping?

**Comment by TheEZIC** [comment]
Yes. Common user doesn`t know how to convert number to ms. And I think this option should be in the game. It`s the main reason why I created this issue.

**Comment by V3rald** [comment]
Or just a way to decrease and increase the ms value by 1/10/50 maybe via arrows, shift+arrows and ctrl+arrows

50 is just too big of a number and i found the need of 25 or some other number smaller than 50 for a comfortable scrollspeed. With this system, anyone could set their original scrollspeed with some trial and error
