### ISSUE TITLE
Incorrect/missing resume animation in single-thread mode

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#8275]
**Describe the bug:** Resuming a play in single-thread mode doesn't seem to correctly show the animation on hit objects: they start a few milliseconds later. Can be reproduced on any map.

**Screenshots or videos showing encountered issue:** 
![gameplay](https://user-images.githubusercontent.com/43073074/76681101-99ca9100-65ef-11ea-93c8-aa848c60e3cd.gif)

**osu!lazer version:** 2020.312.0

**Comment by peppy** [comment]
You mean the single frame freeze? I think this is normal.

**Comment by Gabixel** [comment]
It looks a bit strange since in multithreaded mode the animation seems different (and smoother).
Here's the same situation above:

![gameplay](https://user-images.githubusercontent.com/43073074/76682667-3bf17580-65fe-11ea-83c2-93a887761b4f.gif)

**Comment by peppy** [comment]
in the first you weren't holding the mouse so it started contracting.

**Comment by Gabixel** [comment]
Maybe I'm misunderstanding, or it's hard to notice, but even in the first one I was holding Z/X (in my case, but that's the same with mouse buttons). I tried to make a video that compares them, so you can see better the difference (I used the slider because I think it's the best one to compare here): https://streamable.com/3pbjd

In short: looks like it skips some frames immediately after clicking the orange cursor in single-thread mode.

**Comment by peppy** [comment]
@Gabixel looking to prioritise this one - are you still able to reproduce this on the latest release?

**Comment by Gabixel** [comment]
I was trying to reproduce the issue, but I noticed that it no longer seems reproducible.
I took a look at the recent versions, and it seems that the most recent one ([`2021.424.0`](https://github.com/ppy/osu/releases/tag/2021.424.0)) has fixed the issue!

There still seems to be a weird "rewinding of time" when resuming the game (both single- and multi-threaded) by a few milliseconds (based on my poor perception of time). Not related to this issue, but I don't know if that's normal/intended.

**Comment by peppy** [comment]
The rewinding of time is to do with the platform/universal offset being applied as the clock kicks back in. Probably something we want to eventually address, but that can be tracked elsewhere (we're already aware of it and it will become more of an issue once we implement clock offset support in the editor, so even if an issue isn't tracking it it *will* get fixed).

Will close this one for now as it is specifically related to the threading mode.
