### ISSUE TITLE
Left Click input not being accepted

### ISSUE THREAD

**Issue by bennettcole418** [ppy/osu#8276]
**Describe the bug:** 
Osu! is ignoring whatever key is set as the left click input; changing it or clearing the cache causes it to be fixed for under a minute then input is rejected again. Checked to make sure the issue wasn't on my end by rebooting my laptop and making sure Osu!Stable recognized the key I have bound as left input. I'm no developer, but the only difference between when it was working before and now that it isn't working is the new Windows 10 feature update that I installed.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2020.312.0
**Logs:**

**Comment by bdach** [comment]
Honestly baffled by this report. I don't understand what the cache clearing has got to do with it, unless EF is being horridly unreliable...

* What key do you have bound currently?
* Are the remapping attempts you're making visible in the settings panel on the left afterwards?
* Could you attach `%AppData%/osu/client.db` or try to temporarily rename it and see if it resolves the problem?
* Could you attach a video of the entire process, with key counter overlay enabled?

**Comment by peppy** [comment]
Need far more details here. Sounds like a windows focus problem if anything.

Unclear if it's only happening in gameplay or everywhere. Unclear if it's just left-click or all mouse buttons.

**Comment by jurgentreep** [comment]
I think he means he can't bind the keys to the left and right mouse buttons. At least that's the problem I'm having.

Here's a video of my problem: https://transfer.sh/qcGtN/osu%21lazer%202020-03-14%2016-20-57.mp4

**Comment by bdach** [comment]
@jurgentreep Looking at the attached video it seems like you are likely to have another input device plugged in while capturing bindings (judging from the `JOYSTICK 2 JOYSTICK 3` text, it's probably picking up a combination of inputs). Unplugging or making the device "be in neutral state" would be the suggested solution IMO.

**Comment by jurgentreep** [comment]
@bdach I do not have any of those plugged in. I've got a single usb hub with a microsoft sculpt ergonomic keyboard and mouse plugged in. Apart from that I have an microphone, webcam and amp plugged in. I can't image any of those having problems.

I've tried binding the inputs in the old osu client and it works fine.

**Comment by bdach** [comment]
I can't reproduce what your video shows with my input devices, so it has to be connected to the hardware you're using in some manner. Info as to which device specifically would be helpful.

**Comment by bennettcole418** [comment]
The only input device I have connected is the Wacom CTL-4100; I had Q and W bound but it kept happening with a/s, 1/2, x/z. The remapping attempts are visible in the settings panel after each change. It only happens in Osu!Lazer specifically, not elsewhere in windows or the stable version of the game. I'll take a video here shortly, hopefully it will happen again. I'll also try renaming client.db as @bdach suggested. As for the device, I'm using a HP Spectre x360 Convertible 15-bl1xx (Don't know if this is relevant or not, but before I play I have to set my system resolution to 1920x1080 as both versions seem to have trouble running in 4k for some reason.)

[client.db.log](https://github.com/ppy/osu/files/4332979/client.db.log)

**Comment by bennettcole418** [comment]
I ended up deleting the client.db file, now I'm re-importing beatmaps and everything is working fine. Apologies if I've wasted y'all's time.
