### ISSUE TITLE
Turned on Raw Input and cursor won't move. (MacOS)

### ISSUE THREAD

**Issue by MageHunter64** [ppy/osu#8279]
I activated Raw Input and the mouse won't move. I've tried uninstalling the game but Raw Input is still on.
Version 2020.312.0

[database.log](https://github.com/ppy/osu/files/4334049/database.log)
[network.log](https://github.com/ppy/osu/files/4334050/network.log)
[performance.log](https://github.com/ppy/osu/files/4334051/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4334052/runtime.log)

**Comment by bdach** [comment]
Raw input issues are known on macOS (#7313, #7102, #6519, #4359, #3448).

Please try disabling it again with <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>R</kbd> or by deleting contents of `~/.local/share/osu`.
