### ISSUE TITLE
The cursor won't move after closing the game and opening it again. (Mac)

### ISSUE THREAD

**Issue by MageHunter64** [ppy/osu#8280]
It works the first time I open the game but if I close it and open it again the mouse won't move it sometimes does when I move my mouse really fast. Uninstalling the game and installing it again gives the same result.
Version 2020.312.0
[network.log](https://github.com/ppy/osu/files/4334135/network.log)
[performance.log](https://github.com/ppy/osu/files/4334136/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4334137/runtime.log)

**Comment by bdach** [comment]
Are you using the trackpad? Which window mode? Does tabbing out an then in again help?

**Comment by MageHunter64** [comment]
> Are you using the trackpad? Which window mode? Does tabbing out an then in again help?

I'm using the mouse but I've tried the trackpad too and it didn't work either. I'm using fullscreen. tabbing out and then in doesn't help either.

**Comment by peppy** [comment]
You can fix this by switching to another window then switching back. We're aware of this issue but it likely won't be fixed until the switch to SDL.

**Comment by MageHunter64** [comment]
> You can fix this by switching to another window then switching back. We're aware of this issue but it likely won't be fixed until the switch to SDL.

Switching windows doesn't fix it it just moves the mouse to wherever it was while switching windows.

**Comment by bdach** [comment]
Mind trying to run lazer with the `--sdl` flag and seeing if it's functional then?

**Comment by MageHunter64** [comment]
> Mind trying to run lazer with the `--sdl` flag and seeing if it's functional then?

Do you mind explaining how I don't know how to do that.

**Comment by MageHunter64** [comment]
> Mind trying to run lazer with the `--sdl` flag and seeing if it's functional then?

I've tried googling it but I can't find how to do it.

**Comment by cupppu** [comment]
1. Open terminal
2. Go to where you have installed osu!
3. Right click on osu!.app and click `Show package content`
4. navigate into Contents/MacOS and find `osu!` executable
<img width="586" alt="image" src="https://user-images.githubusercontent.com/7279624/76705758-44b77980-66da-11ea-8034-4f26d12bd24a.png">
5. drag that into the terminal
6. type a space and then --sdl at the end and run it

**Comment by GalvinGao** [comment]
I've got the exact same issue where my mouse will be stucking at the bottom right corner. Tabbing in and out doesn't fixed the issue. But this occurs to be happening occasionally since I was able to play osu without using the `--sdl` flag, fullscreening on my 2nd screen: it behaves normally.

With the `--sdl` flag osu is now running in the windowed mode and for me it seems to have no issue at all.

**Comment by peppy** [comment]
Are you sure you didn't accidentally turn on raw input at some point? Please hit ctrl-opt-r to reset your input settings.

**Comment by GalvinGao** [comment]
> Are you sure you didn't accidentally turn on raw input at some point? Please hit ctrl-opt-r to reset your input settings.

The raw input option is greyed out, so I'm sure it is disabled.

![image](https://user-images.githubusercontent.com/12567059/79468043-78810a00-7fcc-11ea-9240-89efcb4a61d4.png)

**Comment by smoogipoo** [comment]
I have been able to replicate this.

**Comment by Mic238** [comment]
Found the same issue, it happens only when the game is start in full screen mode. 

It can be solved by simply alt+enter x2 to go to window mode and switch back. Seems to be raw input would be enabled at some point when the game is starting in full screen.

OS: Catalina 10.15.4

**Comment by frenzibyte** [comment]
SDL indeed fixes this, I think this can be closed now.
