### ISSUE TITLE
Delayed video playback on video SB'd beatmaps (android lazer client)

### ISSUE THREAD

**Issue by Yuuhei** [ppy/osu#8281]
When i try to play a map with video on it, there seems a delay loading the video SB, so it's not synced to the beatmap

Android lazer client,
Running on:
Xiaomi Redmi Note 8
Android 9 Pie
3gb RAM (1.8 available)
Snapdragon 665 AIE
OpenGL ES 3.2

Sample video (sorry if it's in low quality)
https://streamable.com/b2wcw

**osu!lazer version:** 
2020.312.0 (android client)
**Logs:**
 [logs.zip](https://github.com/ppy/osu/files/4334164/logs.zip)

**Comment by smoogipoo** [comment]
Duplicate of https://github.com/ppy/osu/issues/6101
