### ISSUE TITLE
Disabling beatmap skins option does not fully disable beatmap's combo colors 

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8282]
**Describe the bug:** 
When the option ``Beatmap skins`` is disabled, combo color usage is wrong.

* Expected: Combo colors go to only selected skin's values
* Actual: I think it reverts to a modulo operator, so if your skin has two combo colors, every even numbered color in map skin's will be your skin's second color, every odd one your first.

**Screenshots or videos showing encountered issue:**
lazer side: https://www.youtube.com/watch?v=6e0_x9AzkRs
expected from stable: https://www.youtube.com/watch?v=3IZHCLjyXIo

**osu!lazer version:** 
2020.312.0

**Comment by iiSaLMaN** [comment]
What happens if `Beatmap skins` is on but no beatmap combo colour is available, same results?

**Comment by LittleEndu** [comment]
No. Then selected skin's combo colors are used correctly: https://www.youtube.com/watch?v=n03vo6jni9Y

**Comment by iiSaLMaN** [comment]
Weirdly, I can't reproduce with normal skins (one generated by code on test and other downloaded), can you please provide the skin you were reproducing against.

**Comment by LittleEndu** [comment]
It's available on https://github.com/LittleEndu/osuSkin/tree/master/u200B

**Comment by iiSaLMaN** [comment]
The actual issue here is not related to skin combo colours, but rather, it's about hit object manual combo colour assigning (also known as "color haxing") not being disabled when beatmap skin is disabled, will look into fixing this.
