### ISSUE TITLE
Reverse arrow follows snaking out sliders

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8283]
**Describe the bug:** 
When a repeating slider snakes out, the reverse arrow follows it instead of fading out on the spot. This looks weird on skins that have the "arrow" placed outside the slider.

**Screenshots or videos showing encountered issue:** 
Noticed on this vid from my last issue: https://www.youtube.com/watch?v=n03vo6jni9Y

**osu!lazer version:** 
2020.312.0

**Comment by peppy** [comment]
I think this looks fine?
