### ISSUE TITLE
osu!catch catcher hitbox is too big

### ISSUE THREAD

**Issue by CelegaS** [ppy/osu#8285]
**Describe the bug:** For example with cs4 catcher's hitbox is 24 unit bigger than in stable (12 from each side).

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/11272924/76708132-d207c780-66f4-11ea-8745-6a0ab394c087.png)
![image](https://user-images.githubusercontent.com/11272924/76708121-c3b9ab80-66f4-11ea-8ffb-47b2f095335a.png)

Map to test: https://osu.ppy.sh/beatmapsets/1125773#fruits/2352219

I placed the first fruit at the platter's border in stable. All next fruits I moved 1 unit to the left and right. So in stable you only catch the two first fruit. In lazer you catch up to 12 unit moved to left & right.

**osu!lazer version:** 
2020.312.0

**Comment by peppy** [comment]
Thanks for the comprehensive test case.
