### ISSUE TITLE
Editor tick colours are swapped on certain beatmaps

### ISSUE THREAD

**Issue by TheWildTree** [ppy/osu#8286]
When compared to stable, ticks on the editor's timeline have different colours - in this particular case it seems like red ticks are swapped with white ones.

![image](https://user-images.githubusercontent.com/27722894/76707959-a33d2180-66f3-11ea-828c-428246b16ccf.png)

This happens because lazer doesn't respect the ticks order being reset after passing a new timing point. Here's how stable does it (notice how the tick where the (2) slider is placed changes its colour) :

![2020-03-15_19-45-10](https://user-images.githubusercontent.com/27722894/76708228-8570bc00-66f5-11ea-8538-c82015136879.gif)

Lazer doesn't do that, causing the disprepancy here:
![2020-03-15_19-47-25](https://user-images.githubusercontent.com/27722894/76708269-cff23880-66f5-11ea-9436-30c710a2e535.gif)

Example beatmap to test: https://osu.ppy.sh/beatmapsets/1001507

**Comment by bdach** [comment]
I don't know if stable's behaviour makes sense *musically* - it's not like tempo changes in music notation affect the actual time signature/beat count. Maybe useful for mappers though, not sure, would need opinions from them.

**Comment by smoogipoo** [comment]
Hmm lazer should already be doing this. Can you provide the time in the listed beatmap at which this happens?

**Comment by TheWildTree** [comment]
Easiest to reproduce at the very beginning of the last diff (the green (1) shown in the GIF is the first hitobject there).

**Comment by smoogipoo** [comment]
Ah that's a case where lazer's being smart and de-duping timing points with the same beat length. This is intended.

**Comment by smoogipoo** [comment]
Actually going to re-open this as it is counter-intuitive for timing resets.

**Comment by Alchyr** [comment]
As far as I can tell, the easiest way of solving this is simply by also comparing time on the EquivalentTo test in TimingControlPoint. After all, a timing point with a different time results in different timing, even if it has the same bpm and beats per measure. This has some problems, though. The documentation on EquivalentTo states that "Whether this control point is equivalent to another, ignoring time."
Will this method be used in such a way that two timing points on different times should be considered equivalent?

**Comment by smoogipoo** [comment]
That solution makes sense to me.
