### ISSUE TITLE
PlaySongSelect::OnBeatmapChanged(...) is handled when it shouldn't be

### ISSUE THREAD

**Issue by MrTheMake** [ppy/osu#829]
Currently, the PlaySongSelect object should only exist at the song selection screen or any further screens. However, it exists when you enter it and exit it again. The callback PlaySongSelect::OnBeatmapChanged(...) is called when changing the current beatmap with the music controller while being at the main menu.
This results in track looping not working as intended.

**Comment by huoyaoyuan** [comment]
Seems the old one is exited, and not GCed so still handling events.
Maybe you can unregister events in `OnExit`.

**Comment by MrTheMake** [comment]
As explained by huoyaoyuan, the issue isn't that PlaySongSelect exists, but that it still handles events.
