### ISSUE TITLE
Skip button can't be pressed by K1/K2

### ISSUE THREAD

**Issue by willyosu** [ppy/osu#8296]
**Describe the bug:** In stable you can activate the skip button by pressing spacebar, clicking on it with either mouse button, or pressing K1/K2 (Left/Right buttons in lazer) on it, but in current version only spacebar and mouse left are able to click it. 

**Screenshots or videos showing encountered issue:** https://streamable.com/t1b7u

**osu!lazer version:** 2020.312.0

**Comment by iiSaLMaN** [comment]
Can be closed in favor of https://github.com/ppy/osu/issues/3551 as it covers the main issue of this.
