### ISSUE TITLE
Borderless performs differently than letterboxing

### ISSUE THREAD

**Issue by willyosu** [ppy/osu#8299]
**Describe the bug:** In stable I play with letterboxing (now the "Render at native resolution" setting) and the game runs properly but when trying out the borderless option on lazer my game was seemingly capped at 60fps. The game itself was rendering everything at the correct rate as shown below but the actual refresh rate that I was seeing was very obviously much lower than it should be on my 144hz monitor.
![image](https://user-images.githubusercontent.com/11691902/76791540-86f2c080-6797-11ea-9474-260087449b76.png)
My friend suggested it could have something to do with Windows 10 and my second monitor that's 60hz but everything displays at the correct rate in stable so I'm not quite sure what it could be.

**osu!lazer version:** 2020.312.0
**osu!stable version:** 20200304.1

**Logs:**
[performance.log](https://github.com/ppy/osu/files/4339958/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4339959/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4339960/updater.log)
[network.log](https://github.com/ppy/osu/files/4339961/network.log)

**Comment by TheWildTree** [comment]
Just to be sure: you're comparing against stable in borderless mode too? (settings like [this](https://user-images.githubusercontent.com/27722894/76797481-e66bc300-67cd-11ea-9d3b-0cc5ab0261d2.png))

**Comment by willyosu** [comment]
I've always played like this without fullscreen since letterboxing was first added because I can't deal with the screen tearing.
![image](https://user-images.githubusercontent.com/11691902/76798409-e9eb5400-67a5-11ea-87f2-348dedd09a7e.png)
Stable runs just fine like this so I really have no idea how lazer is handling it differently.

**Comment by peppy** [comment]
As above, lazer is pushing a correctly high number of frames so it's likely a setting in your graphics drivers or something on another monitor limiting output frame rate.

**Comment by willyosu** [comment]
Exactly, but the same capping doesn't happen in stable which is why this is so strange. I don't think there's anything in my graphics drivers that would be changing anything because it doesn't even detect stable or lazer as games. 
![image](https://user-images.githubusercontent.com/11691902/76830093-edf59100-67fa-11ea-8274-33da997ccecc.png)
I don't think it would be anything in here anyway.

**Comment by TheWildTree** [comment]
Your best bet right now might be to just wait for the Windows 10 2004 (201H) update, probably coming in April, which apparently fixes a few issues with handling multiple screens with different refresh rates. If this is a Windows issue, it should be gone after that update.

In the meanwhile, you could try to look for possible differences between how you launch stable vs. lazer - for example, many players have `Disable fullscreen optimizations` enabled for stable (RMB on the shortcut > Properties > Advanced) - maybe you're using that too, and even though it's for *fullscreen*, perhaps it somehow makes a difference when it's not enabled in lazer? I do realize this is kinda far-fetched, but who knows with Windows nowadays.

**Comment by peppy** [comment]
You should really turn on freesync (if your display supports it) and run exclusive fullscreen.

Closing this one for now as I don't believe there's anything we can do.
