### ISSUE TITLE
Game lags and beatmaps are desyncing with music

### ISSUE THREAD

**Issue by Lucky-fish** [ppy/osu#8303]
**Describe the bug:** 
On my poor computer, osu!lazer runs with less than 30 fps and sometimes less than 10 fps and makes unplayable. And when I opened a beatmap with auto, the beatmap gradually become out of sync with music.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
cloned source at commit 10eccbcf3..5e3668b2e
**Logs:**

I cannot upload my logs directly..

**Comment by peppy** [comment]
We are constantly working to improve performance and general issues like this will be closed if there's no specific new piece of information that we need to act on.

If you are running from source, please make sure you are building a *release* build and not attached a debugger. If it still runs slow, please attach your PC specs for further advice.
