### ISSUE TITLE
Result panel missing unstable rate stats

### ISSUE THREAD

**Issue by stanriders** [ppy/osu#8314]
Life graph as well but it's less important

**Comment by Theighlin** [comment]
Is there work going on on life graph? Trying to resurface this if not as it is a major feature I am (and probably others are) looking forward to. It could be put in the detailed statistics view now that it's there.

**Comment by bdach** [comment]
Is there a design for this? Asking partially because I would want to see if I could take a shot at it, and partially because if not we might want to take this out of August milestone.

**Comment by smoogipoo** [comment]
![image](https://user-images.githubusercontent.com/1329837/91057022-a86aa900-e661-11ea-8ee9-18fc2c21ef35.png)

I think it'd be one of the texts at the bottom below the timing distribution.

**Comment by bdach** [comment]
So the basic display for osu!/taiko/mania is in, but spinner UR is not in yet, neither is UR in catch (which is spatial-based in being the fruit-to-centre-of-catcher distance, and not time-based). I'm not entirely sure what to do with this issue at this point - are the things I mentioned above that aren't yet implemented important enough to enough people to bring back? I'm not sure I see much point in either myself, if I'm completely honest.

**Comment by smoogipoo** [comment]
I think this issue can be closed off for now. Those things are like extras, and in the case of catch, probably a different statistic altogether.
