### ISSUE TITLE
Song name extends outside of ranking result borders

### ISSUE THREAD

**Issue by Larakagi** [ppy/osu#8315]
**Describe the bug:** some long names such as the name of the artist or a song can extend outside of these borders

**Screenshots or videos showing encountered issue:** [Bliitzit - Team Magma & Aqua Leader Battle Theme (Unofficial)](https://osu.ppy.sh/beatmapsets/1002271#osu/2097898):
![изображение](https://user-images.githubusercontent.com/36848514/76870953-7ddb1f80-687b-11ea-9688-d9bacd25afd2.png)

**osu!lazer version:** 2020.317.0 (branch https://github.com/ppy/osu/commit/156a3db57d7841c7eb26a2d2ae76ca0a754b281a)

**Comment by Joehuu** [comment]
Part of https://github.com/ppy/osu/issues/3504, but will leave open as this was implemented recently (to avoid more duplicate issues).
