### ISSUE TITLE
unable to download osu

### ISSUE THREAD

**Issue by 666arc** [ppy/osu#8322]
**Describe the bug:** 
Everytime I try and download osu! it will not let me
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/62303837/76886170-4a4ac600-6878-11ea-9746-928c06cc42fc.png)

**osu!lazer version:** 

**Logs:**
 nothing. the osu file is not there.

**Comment by bdach** [comment]
Judging from the obfuscated stack trace I'm guessing it's stable you're having trouble with, and not lazer?

**Comment by peppy** [comment]
Please send me an email with the contents of that message (hit ctrl-c while it is focused to copy it).

pe@ppy.sh
