### ISSUE TITLE
A problem after play a beatmap

### ISSUE THREAD

**Issue by poly000** [ppy/osu#8324]
**Describe the bug:** 
the map isnt mapped by me, but in this interface it says the map is mapped by me
![https://sm.ms/image/8pw6EzbiYULaD7e](https://i.loli.net/2020/03/18/8pw6EzbiYULaD7e.png)

**Comment by bdach** [comment]
#8317

**Comment by jai-x** [comment]
Duplicate of https://github.com/ppy/osu/issues/8317

Please search for existing issues before opening new ones.

**Comment by poly000** [comment]
> 
> 
> Duplicate of #8317
> 
> Please search for existing issues before opening new ones.

sorry for my poor english
