### ISSUE TITLE
Beat Divisor Control value can be set outside of valid divisors

### ISSUE THREAD

**Issue by Fuewburvpoa** [ppy/osu#8326]
**Describe the bug:** When dragging marker it is possible to set value and position of marker outside of valid divisors, it happens only if you start dragging > marker jump > release mouse > it will land on wherever your mouse position was. 
That leading to having all red and small divisors in beatmap editor when it set to 1/7, 1/11 etc.

**Screenshots or videos showing encountered issue:** 
https://imgur.com/a/3nm2lSl

**osu!lazer version:** 2020.317.0

I don't know how to submit a fix.
So there is a fix, in BeatDivisorControl.cs TickSliderBar class, we need to override OnDragEnd to prevent base class from changing value of the slider.
`
protected override void OnDragEnd(DragEndEvent e) {}
`

**Comment by recapitalverb** [comment]
You can open a pull request with the fix applied.

**Comment by Fuewburvpoa** [comment]
Ugh, that looks is kinda hard, not sure how it works, maybe ill try it next time.
