### ISSUE TITLE
Missing date when viewing score results

### ISSUE THREAD

**Issue by a-strange-octopus** [ppy/osu#8330]
**Describe the new feature:** While I really appreciate the new design interface, I'm a little disappointed that I can no longer view the date when I bring up my results for a song. I believe the date used to be there in previous versions of osu!lazer.

**Proposal designs of the feature:** Maybe put the date next to the username & below the user icon on the top.

![Screen Shot 2020-03-17 at 4 50 31 PM](https://user-images.githubusercontent.com/39961132/76900314-7c0b5f00-686f-11ea-8074-6548688c0797.png)
(As you can see in the image, I can't tell when I completed the song)

**Comment by bdach** [comment]
It will return.
