### ISSUE TITLE
Missing assemblies after update

### ISSUE THREAD

**Issue by AirOne01** [ppy/osu#8331]
### Description:
I just updated to a new version of lazer and now i can't do anything network-related in the game. I checked the windows antivirus and created a special firewall rule for osu!laser. Can't find anything that can be a problem for laser. I have no proxy, VPN, haven't got Node JS running in bg and my internet configuration seems stable (~150 Mb/s). The only notable thing that comes to my mind is that i have Kali Linux running in background as a subsystem (refer to [this article](https://www.kali.org/tutorials/kali-on-the-windows-subsystem-for-linux/)).

### Video:
https://drive.google.com/open?id=1f0HOZQtboQVOk1Zzwis9qVslxyU__uop

### Version:
2020.317.0 (fresh update)

### Logs:
[runtime.log](https://github.com/ppy/osu/files/4345874/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4345875/updater.log)
[database.log](https://github.com/ppy/osu/files/4345876/database.log)
[network.log](https://github.com/ppy/osu/files/4345877/network.log)
[performance.log](https://github.com/ppy/osu/files/4345878/performance.log)

Thanks for your help!

**Comment by bdach** [comment]
This looks bizarre:
```
2020-03-17 20:50:59 [verbose]: Processing response from https://osu.ppy.sh/oauth/token failed with System.IO.FileNotFoundException: Could not load file or assembly 'System.Xml.ReaderWriter, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Le fichier spécifié est introuvable.
2020-03-17 20:50:59 [verbose]: File name: 'System.Xml.ReaderWriter, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
No wonder nothing online works if by some freak accident libraries upon which `Newtonsoft.Json` depends are missing... I'd try to reinstall afresh, but it's sort of worrying that the update process has done this altogether.

**Comment by AirOne01** [comment]
Alright i'll reinstall all that tomorrow and tell you.
Thanks for your help.

**Comment by AirOne01** [comment]
Worked again after launching the installer.
Thank you!
