### ISSUE TITLE
Switching to a beatmap of another ruleset can cause desync if the "Show converted beatmaps" option is enabled

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#8344]
**Describe the bug:** Switching to a beatmap (using the `UserProfileOverlay`) with a ruleset that accepts the conversion to the previous one (e.g. _osu!taiko_ → _osu!_), with the `Show converted beatmaps` option **enabled**, causes the `BeatmapInfoWedge` to desync.

**Screenshots or videos showing encountered issue:** https://streamable.com/g18k8
(The first example shows the normal behaviour with the `Show converted beatmaps` option disabled, the second one shows the issue)

**osu!lazer version:** 2020.317.0

**Comment by peppy** [comment]
Just to clarify, you would hope that it stays in taiko mode?

**Comment by Gabixel** [comment]
I think so. Another scenario may be, for example, with custom rulesets ([here's an example with tau](https://streamable.com/i2sk8t)), where the user just wants to switch beatmap (but I think it can become an option).

By the way, I just tried with `osu!direct` and the `BeatMapSetOverlay`, but there's no desync in those cases (so it seems to desync only with beatmaps in the `UserProfileOverlay`)
