### ISSUE TITLE
Invalid mapper displayed in result panel

### ISSUE THREAD

**Issue by LemonCaramel** [ppy/osu#8347]
**Describe the bug:** There is an error where the beatmap player is marked as a beatmap creator.

**Screenshots or videos showing encountered issue:** 
![osu_2020-03-19_02-12-42](https://user-images.githubusercontent.com/45729082/76987875-393caa80-6987-11ea-9d92-e65b2d57bb7c.jpg)

**osu!lazer version:** 2020.317.0

**Comment by Joehuu** [comment]
Already fixed in https://github.com/ppy/osu/pull/8318, need to wait for next release.
