### ISSUE TITLE
Various Issues With The New Ranking Screen

### ISSUE THREAD

**Issue by Squaduck** [ppy/osu#8348]
**Describe the bug:** 
Issue 1: PP counter doesn't work unless you look at someone else's replay.
Issue 2: It says the player mapped the map.
**Screenshots or videos showing encountered issue:** 
![osu_2020-03-18_18-49-09](https://user-images.githubusercontent.com/55469508/77015281-bbf34480-694a-11ea-9cec-7f28c0b33da2.jpg)

**osu!lazer version:** 
2020.317.0
**Logs:**

**Comment by EVAST9919** [comment]
1. https://github.com/ppy/osu/issues/8313
2. https://github.com/ppy/osu/issues/8317 (fixed)

**Comment by bdach** [comment]
#8313 is not related to the first point. I'm actually pretty sure PP calculation isn't even a thing anywhere for new scores in lazer, so this isn't an instant fix or even an issue with this particular screen.

Closing for now.
