### ISSUE TITLE
Track failed to load crash

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#8350]
**Describe the crash:**
The gameplay mechanics froze while playing and the game crashed after going back to the song select menu and selecting a new beatmap. I have unfortunately no logs since the streamer has already restarted the game and the logs have automatically been overwritten.

**Screenshots or videos showing encountered issue:** 
https://clips.twitch.tv/CuteManlyGalagoWholeWheat
gameplay freeze can be seen at 5 seconds and the crash at 30 seconds

**osu!lazer version:** 
2020.317.0

**Comment by peppy** [comment]
This is a weird one. It looks like lazer lost all concept of an active audio device. Possible related to the recent changes framework side?

**Comment by peppy** [comment]
Closing this for now. Haven't seen it come up in years.
