### ISSUE TITLE
Crash: "Cannot perform Push on a non-current screen."

### ISSUE THREAD

**Issue by 2yangk23** [ppy/osu#8352]
**Describe the crash:** 
Game crashed after finishing map. I think I pressed esc so maybe it caused some invalid state?

**Screenshots or videos showing encountered issue:** 
None

**osu!lazer version:** 
local dev version

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4352633/runtime.log)

**Computer Specifications:** 
See logs

**Comment by peppy** [comment]
I'll take this one. Need to rework some of this flow as it is very prone to error.
