### ISSUE TITLE
osu!direct not detecting an already installed map

### ISSUE THREAD

**Issue by Moorad** [ppy/osu#8353]
**Describe the bug:** 
Some maps that I already have installed is not detected by osu!direct as installed and I am able to download the map from osu!direct again then after it finishes downloading a couple of errors appear. Also, when I right-click the map there is no details option and I noticed that it only happens to approved maps. Those maps were imported from osu!stable a while ago (4 months maybe). The error doesn't affect anything and isn't breaking anything as far as I'm concerned.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=lvyDm0sg0KM

**osu!lazer version:** 
2020.317.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/4352642/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4352643/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4352644/updater.log)
[database.log](https://github.com/ppy/osu/files/4352645/database.log)
[network.log](https://github.com/ppy/osu/files/4352646/network.log)

**Comment by peppy** [comment]
This can happen if you weren't logged in during the import procedure. This will eventually be resolved. If you wish for it to work for now:

- Settings -> Delete all beatmaps
- Exit game
- Start game
- Make sure you're logged in
- Settings -> Import all from stable
