### ISSUE TITLE
"Prefer metadata in original language" setting is reversed on result screen

### ISSUE THREAD

**Issue by STCapricorn** [ppy/osu#8359]
**Describe the bug:** see screenshots

**Screenshots or videos showing encountered issue:** 
![2020-03-19 (18)](https://user-images.githubusercontent.com/7162510/77039124-dd563e00-69e7-11ea-8a86-99f8c460e840.png)
![2020-03-19 (20)](https://user-images.githubusercontent.com/7162510/77039218-10003680-69e8-11ea-9566-e030ec763b96.png)

**osu!lazer version:** 2020.317.0

**Comment by bdach** [comment]
Will be resolved next release as #8334 has been merged.
