### ISSUE TITLE
Video doesn't sync to the beatmap 

### ISSUE THREAD

**Issue by HerendraTJ** [ppy/osu#8361]
**Describe the bug:** 
Beatmap with video doesn't sync with the beatmap 
**Screenshots or videos showing encountered issue:** 
https://youtu.be/xYTb6qm0T28
**osu!lazer version:** 
2020.317.0
**Logs:**
https://drive.google.com/file/d/1vJ7d0qmp285c47uJP4uBIsSI29ABd2l6/view?usp=sharing

Beatmap:
https://osu.ppy.sh/beatmapsets/720223#osu/1538067

**Comment by bdach** [comment]
Beatmap has nonzero video offset - duplicate of #6101.
