### ISSUE TITLE
Transparency in Mod Menu

### ISSUE THREAD

**Issue by Fvern** [ppy/osu#8365]
Description:
The current mod menu takes up about 2/3rds of the screen, leaving only a tiny gap at the top to see the song selection menu when open. It felt like I couldn't see anything.
osu!stable meanwhile has a transparent mod menu, if rather dark, allowing players to see the entire song menu/screen.

Proposal:
Add an option to make the mod menu transparent.

To clarify, I'm talking about this pop-up menu:
![osu_2020-03-20_02-45-55](https://user-images.githubusercontent.com/25032854/77103169-f21ceb00-6a54-11ea-8fbc-1dfc2bfccff6.jpg)

**Comment by smoogipoo** [comment]
This is intended. The overlay won't look good with transparency as it is, and afaik flyte's designs are heading towards even less transparency rather than more transparency. That is also a direction I prefer from an optimisation standpoint.
