### ISSUE TITLE
Spinner length degrades update performance indefinitely

### ISSUE THREAD

**Issue by Azureharp** [ppy/osu#8367]
**Describe the bug:** 
Spinners even when not being spun lower the update performance, once the spinner finishes it causes a stutter, once that's done update promptly returns to normal. Tested on this map with a 2 minute long spinner https://osu.ppy.sh/beatmapsets/679738#osu/1437412

I'm also very unsure if the logs really picked it up in a clear way, so i'm sorry if that's the case 
**Screenshots or videos showing encountered issue:** 
Near the start
![osu_2020-03-19_15-23-59](https://user-images.githubusercontent.com/42692316/77118266-d50afc80-6a01-11ea-9449-1cea1360eb91.png)
By the end
![osu_2020-03-19_15-26-13](https://user-images.githubusercontent.com/42692316/77118248-c7557700-6a01-11ea-8cd4-f369ec52615e.png)
And not sure if this is helpful but I noticed CPU usage on SpriteIcon goes up with SpinnerDisc in this situation, albeit at a slower rate
![osu_2020-03-19_16-43-12](https://user-images.githubusercontent.com/42692316/77118304-ea802680-6a01-11ea-838d-5ea1a0a3e77f.png)

**osu!lazer version:** 
2020.320.1
**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4357165/runtime.log)
[performance.log](https://github.com/ppy/osu/files/4357166/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/4357167/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4357164/performance-update.log)

**Comment by Azureharp** [comment]
Though overall performance is now higher, the underlying problem is still there.

I've held off on bringing this up because when I looked for a regression it turned up nothing, so I assumed it needed a future optimization that was planned. But recently I tried one of the earliest builds with spinners and it was fine. so I sat down for the day, figured out how to use an IDE, and started checking old builds.

One thing I noticed at 2019.704.0 was auto was fine but only auto. Starting with 2019.713.0 update would also lower in auto.
After testing most commits https://github.com/ppy/osu/pull/5316 had the cause for that.
Specifically how it changed ` FrameAccuratePlayback = true` to `false`. Tested `true` in the master and still circumvents it somehow.
![osu_2020-07-04_15-12-56](https://user-images.githubusercontent.com/42692316/86520378-171d4a00-be09-11ea-9a99-1b94813af5f3.png)
Again this is only with auto, gameplay still drops to ~200 update.

Some more looking and it seems to regressed all the way back in 2017.1111.0 and 2017.1109.0 is the last build unaffected in gameplay. Sadly I couldn't test each commit, since I haven't been able to get it to build.

But if this could be reopened that'd be mighty appreciated.

**Comment by bdach** [comment]
It seems there is *some* kind of increase of the update duration of `DrawableSpinner` and `SpriteIcon` on long spinners which goes away after commenting these two transforms:

https://github.com/ppy/osu/blob/c29bf6cec18ee25e8b4b5b24540682691259225f/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs#L196-L198

so I suppose there is some merit in reopening this.
