### ISSUE TITLE
Hitsound sounds differently in stable and lazer (ctb)

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8375]
Describe the bug:
https://youtu.be/8UdbGXE4qbQ - stable
https://youtu.be/ijs1wDuEJmM - lazer
In the laser, the sounds seem to be interrupted or something like that
osu!lazer version:
2020.320.1
https://osu.ppy.sh/beatmapsets/777109#fruits/2160131

**Comment by peppy** [comment]
This is due to sample concurrency being lower on lazer (in conjunction with catch playing too many samples).
