### ISSUE TITLE
Can't see value of slider in options on Android because of fingers.

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#8377]
This isn't really a feature nor a bug but for now I'll put it here. On Android when moving sliders in the options, you can't really see the value because it follows the cursor, which is under the finger. I think on Android it should visually stay still close to the option.

The gray circle is where the finger is touching the screen.

https://streamable.com/unomq

**Comment by peppy** [comment]
We're not really ready to tackle mobile UX issues. Please use a different finger or increase UI scale for now.
