### ISSUE TITLE
Holding the "up" or "down" key will not scroll the map

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8379]
But "right" and "left" work as usual. Why can’t you move around inside a map that has many difficulties?
https://youtu.be/oeSzcD7VGLo
Here you can add a suggestion for setting the scroll speed (map per second)

osu!lazer version:
2020.320.1

**Comment by peppy** [comment]
This was a known regression from https://github.com/ppy/osu/pull/8090. A fix will require some changes to event flow to `KeyBindingContainer` to allow repeats (or potentially local handling if we decide that's not what we want).
