### ISSUE TITLE
Double cursor on Android when using tablet

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#8380]
When using tablet wired to the phone, two cursors are shown one on top of each other. This doesn't happen with others application on my phone.
I don't know whether it depends on the kind of tablet (mine isn't a renown brand) or something else so i don't know if you can replicate the issue.

https://streamable.com/gb00v

osu!lazer version: 2020.320.1

Phone is a Oneplus 3T running Android 9
[logs.zip](https://github.com/ppy/osu/files/4359520/logs.zip)

**Comment by Game4all** [comment]
Here's a frame from your recording showing the two displayed cursors separately:

![capture](https://user-images.githubusercontent.com/20256717/77165199-21157a00-6ab2-11ea-95bb-bf283b96e7db.png)

The android system cursor is being displayed on top of the game cursor.

**Comment by peppy** [comment]
We are not ready to tackle per input device per mobile platform issues. If you make a PR to fix this it will be revisited but there's no need to keep this issue open for now.
