### ISSUE TITLE
Add stereo shifted hitsound playback support

### ISSUE THREAD

**Issue by Craftplacer** [ppy/osu#8387]
**Describe the new feature:** 
If you listen carefully enough in stable you will notice some sounds are panned according where you hit stuff (e.g. taiko), I'd like to see this feature come back in osu!lazer.

**Comment by Snowmander** [comment]
This is something I don’t particularly like in stable and I would prefer to be able to turn off. Perhaps by a hidden option inside a config file or something.

**Comment by Craftplacer** [comment]
> This is something I don’t particularly like in stable and I would prefer to be able to turn off. Perhaps by a hidden option inside a config file or something.

Yes I agree it should toggable as it's a "bells and whistles feature".

**Comment by peppy** [comment]
If someone wants to look at adding this back, here's the logic:

```
protected virtual float PositionalSound { get { return (Position.X / 512f - 0.5f) * 0.8f; } }
```

Adding as a setting is fine, call it "Positional hit sounds"

**Comment by Craftplacer** [comment]
Sorry if I'm nitpicking, I don't see this feature having an implementation for osu!taiko.
https://streamable.com/10kp2e

**Comment by peppy** [comment]
taiko hitsounding is done completely differently. it can be addressed in its own PR.
