### ISSUE TITLE
Some songs show title with japanese letters

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#8388]
Describe the bug: Lazer shows some songs with unromanised title but can still be found by searching it's romanised one. Stable shows normal title instead.
Reopening the game or reimporting the map does nothing. This affects always the same beatmaps.

Screenshots or videos showing encountered issue: 
![Screenshot_3](https://user-images.githubusercontent.com/53081750/77231756-3a472500-6b9d-11ea-89c9-31900adf66b5.png)
![Screenshot_4](https://user-images.githubusercontent.com/53081750/77231757-3c10e880-6b9d-11ea-88ea-e56576140fd9.png)
![Screenshot_5](https://user-images.githubusercontent.com/53081750/77231771-521ea900-6b9d-11ea-8ac0-6a0b686584d1.png)

osu!lazer version: 2020.320.1

**Comment by bdach** [comment]
Please check if you have the "Prefer metadata in original language" enabled.

**Comment by Theighlin** [comment]
> Please check if you have the "Prefer metadata in original language" setting enabled.

My bad, I didn't notice i had it on, closing this (fake) issue.
