### ISSUE TITLE
Panels in beatmap carousel don't pop open correctly after deleting some amount of beatmaps

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8391]
Probably related to #8390

**Describe the bug:** 
After you delete many (idk how many) beatmaps, sets start popping open with incorrect vertical positions for their difficulty panels.

Expected result:  difficulty panels should appear right below their parent's set panel

Actual result: difficulty panels appear way below their parent set panel, sometimes inside the next set's set panel

**Screenshots or videos showing encountered issue:** 
Managed to trigger the bug at 1:06 or so https://youtu.be/jVbm1Tvgz0E?t=68

**osu!lazer version:** 
2020.320.1

**Comment by peppy** [comment]
not specific to deleting, can be randomly triggered otherwise. the issue is just to do with transform decisions (whether to apply or not).
