### ISSUE TITLE
Panels in beatmap carousel don't pop open correctly after restoring deleted beatmaps

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8392]
Probably related to #8390

**Describe the bug:** 
After restoring deleted beatmaps, sets that already existed start popping open with incorrect vertical positions for their difficulty panels.

Expected result: difficulty panels should appear right below their parent's set panel

Actual result: difficulty panels appear *way* higher than they should

**Screenshots or videos showing encountered issue:** 
https://youtu.be/jVbm1Tvgz0E?t=122 (ignore the rest of the video, that was for #8391)

**osu!lazer version:** 
2020.320.1

**Comment by bdach** [comment]
I don't think that needs to be a separate issue? I'd bring under scope of #8391.
