### ISSUE TITLE
Now playing overlay sometimes has to scroll to correct background when opened

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8393]
**Describe the bug:** 
When you open now playing overlay, it displays the background of the current beatmap. If the beatmap changes it scrolls to the correct background. This background should already be the current one when you first open the now playing overlay, but it sometimes (seemingly randomly) isn't.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/d-Mov8UJjco

**osu!lazer version:** 
2020.320.1

**Comment by peppy** [comment]
If you're going to make long videos, please state at what time point in the video the issue happens.

**Comment by LittleEndu** [comment]
The entire video is me repeating the same action just so that it records it at some point (I have a very cheap laptop so there's FPS drops in the recording). The issue happens 5 seconds into the video, the very first time I open the now playing overlay.

**Comment by peppy** [comment]
It looks correct to me?

**Comment by LittleEndu** [comment]
> This background should already be the current one when you first open the now playing overlay
It definitely can't be correct because it does two different things in the video. Sometimes it scrolls the background, sometimes it doesn't.

**Comment by peppy** [comment]
So not the one at 5s then. The movement is intentional.

The edge case is probably the `audioEquals` specification.

**Comment by LittleEndu** [comment]
Why would the movement be intentional? If it is, why does the background not scroll when you just keep opening and closing the overlay? 

https://youtu.be/ix2BhsOZHq0

**Comment by bdach** [comment]
[Because there have been no changes to current track.](https://github.com/ppy/osu/blob/a890afcac2a4266a5c7ff92fa186f758b166efb5/osu.Game/Overlays/MusicController.cs#L232-L263)

**Comment by LittleEndu** [comment]
#8397 is what I thought the fix would be. Unsure why behaviour like this isn't intended.
