### ISSUE TITLE
Importing beatmaps shouldn't be skipped without asking

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#8396]
When deleting a beatmap and redownloading it without restarting osu!lazer, the redownloaded beatmap will automatically be replaced by the previously deleted beatmap (including all of it's modifications) without asking. This can be confusing for some people (including me ppy/osu#8366). It would be nice if a dialog popped up giving the player a choice to save the redownload or restore the previously deleted beatmap. [something like this](https://imgur.com/a/F7TyVO2). This option should not pop up when the previous version of that beatmap is exactly the same, then the import can just be skipped without asking, or if there was no previous version of that beatmap found. Thanks! If this isn't somthing you're willing to implement that's completely fine too, this is just a suggestion.

**Comment by bdach** [comment]
Dialog is probably a bit much, but a hash check of the archive to compare with the soft-deleted version might be good. `BeatmapManager.CanUndelete` is probably the place to look at.

**Comment by peppy** [comment]
I believe this has since been resolved. Could someone test this out?

**Comment by frenzibyte** [comment]
I can confirm I can't reproduce the issue mentioned in OP (by editing a beatmap, saving, deleting, and redownloading), but I'm not quite sure how it's fixed since the previously existing `BeatmapManager.CanUndelete` was only called when there's an existing beatmap with the same hash as the new one... but I guess it's fine to just close for now?

**Comment by peppy** [comment]
I rewrote the reimport code quite a way back to ensure reimports like this work, with only the online IDs being dropped.
