### ISSUE TITLE
Issues with top of window and cursor position on Linux

### ISSUE THREAD

**Issue by ZLima12** [ppy/osu#84]
While working on osu on Linux, the top 30 pixels of the frame seem to be cut off and the cursor position offset from the actual cursor position.

![](https://cloud.githubusercontent.com/assets/17912528/19406305/7a486b74-9251-11e6-842d-29159fddff74.png)

However, (0,0) is still in the top left corner, in that 'dead' space. (I threw in something to log the input mouse location when it changes, as shown in the terminal)

![screenshot_20161014_205320](https://cloud.githubusercontent.com/assets/17912528/19406316/aff7436c-9251-11e6-9587-246b8beeb794.png)

Those two images were using Intel's integrated graphics/drivers, but it doesn't look so pretty with the open source AMD drivers:

![screenshot_20161014_205851](https://cloud.githubusercontent.com/assets/17912528/19406327/dfe40b64-9251-11e6-8dd7-1364d83f55d7.png)

**Comment by SirCmpwn** [comment]
https://github.com/ppy/osu-framework/pull/136

**Comment by ZLima12** [comment]
@SirCmpwn Apologies, I saw the thread but didn't notice that you had the same issue.
