### ISSUE TITLE
Taiko doesn't play hitsounds when not hitting an object

### ISSUE THREAD

**Issue by peppy** [ppy/osu#840]
Taiko drum should always play sounds, even if a hitobject isn't hit.

**Comment by FreezyLemon** [comment]
The hitsound has to be played as soon as the hitobject is missed, right?
Can't be earlier since it would possibly be out of sync with the user click, and later would make no sense.

**Comment by FreezyLemon** [comment]
Hm.. okay, definitely misunderstood in the beginning. But I still have questions (not a taiko player):
What hitsound should be played? Just pick a default one differentiating between rim and center, or in a mania-like style where you hear the (possibly custom) hitsound of the next hitobject on that line? 

Also, if the latter is the case, should a keypress indicating a rim hit play the next rim object's hitsound, even if the next hitobject is a centre hitobject? I think so, but still asking for clarification.

**Comment by peppy** [comment]
try playing on osu-stable to get a feel for it (or find a video on outline if that’s not an option)

**Comment by Shieyn** [comment]
would it be a good idea to have the InputDrum class play samples?
