### ISSUE TITLE
Mouse won't move ingame if you click raw input

### ISSUE THREAD

**Issue by Rainbuu** [ppy/osu#8401]
**Describe the bug:** I clicked raw input by accident, and now I can't move my mouse ingame.

**Screenshots or videos showing encountered issue:** http://www.mediafire.com/file/d74udhw16bw0gwx/Screen_Recording_2020-03-22_at_10.27.50_AM.mov.zip/file

**osu!lazer version:** 2020.320.1

**Logs:**

[database.log](https://github.com/ppy/osu/files/4365404/database.log)
[network.log](https://github.com/ppy/osu/files/4365405/network.log)
[performance.log](https://github.com/ppy/osu/files/4365406/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4365407/runtime.log)

**Comment by bdach** [comment]
Raw input issues are known on macOS (#8279, #7313, #7102, #6519, #4359, #3448).

Please try disabling it again with <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>R</kbd> or by deleting contents of `~/.local/share/osu`.

**Comment by Rainbuu** [comment]
PS: I'm on macOS Catalina.
