### ISSUE TITLE
Not being able to get my beatmaps from osu!(wineskin) to osu! lazer

### ISSUE THREAD

**Issue by elh192773** [ppy/osu#8411]
I have osu! on wineskin and something like 9k beatmaps, and re installing those into osu lazer would take nigh on months as it is wineskin import from stable does not work. I am wondering if there is another way to import those 9000 maps into lazer by file or other means.

**Comment by huupoke12** [comment]
Please create a symbolic link mentioned at: https://github.com/ppy/osu/issues/6751#issuecomment-550565164

**Comment by Joehuu** [comment]
Closing as the solution is https://github.com/ppy/osu/issues/6751#issuecomment-550565164.
