### ISSUE TITLE
On 100% dim, when a break time ends, storyboard stops being displayed too soon

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8418]
**Describe the bug:** 
As title says, when you are playing a map with a storyboard on 100% background dim, the storyboard is displayed when you have "Lighten playfield during breaks" enabled. But as soon as the timer reaches 0, before the background starts dimming to 100% again, storyboard stops being displayed and beatmap background is shown instead.

**Screenshots or videos showing encountered issue:** 
I don't have any. This happens only during gameplay so you can't record a replay to video...

**osu!lazer version:** 
2020.320.1

**Comment by peppy** [comment]
I can't reproduce this – for me the fade out is smooth and the background image does not display.

Could you please make a screen recording or at very least provide the beatmap you are seeing this occur in?

**Comment by LittleEndu** [comment]
I'll have to verify that again. I think I was also unable to reproduce it last time I played a map with storyboard on.

**Comment by LittleEndu** [comment]
Not sure what's going on here. Checked out d96f684077e28e4b2c15bc28fc9e875b06256706 and can't reproduce it anymore. And it also isn't in the latest release. Going to close.
