### ISSUE TITLE
as with my previous report cannot use the symlink to transfer wineskin osu! files to osu! lazer

### ISSUE THREAD

**Issue by elh192773** [ppy/osu#8422]
I used the command 

ln -s /Applications/osu!.app/Content/Resources/drive_c/osu\! ~/.osu;

But it seemingly returned an error
![image](https://user-images.githubusercontent.com/28768122/77366856-ae9fe500-6da4-11ea-95a7-c4dd03801da5.png)

So I once again ask can I mass transfer files. (I may just be dumb and have done this wrong)

-bash: !.app/Content/Resources/drive_c/osu\!: event not found    (the Error)

**Comment by tybug** [comment]
this is an issue with your bash command, make sure you escape both exclamation points: https://serverfault.com/a/208266

**Comment by elh192773** [comment]
So what should I do. This?

ln -s /Applications/osu!.aoo/Content/resources/drive_c/osu\! ~/.osu;\! 

That work?

**Comment by tybug** [comment]
You just added an extra bang (exclamation point), lol. You missed the bang after `osu`. Here's the command that should work, I haven't run it.

`ln -s /Applications/osu\!.app/Content/Resources/drive_c/osu\! ~/.osu;`

**Comment by elh192773** [comment]
The only thing is that I do not notice the data change. The command worked but no songs

**Comment by elh192773** [comment]
> You just added an extra bang (exclamation point), lol. You missed the bang after `osu`. Here's the command that should work, I haven't run it.
> 
> `ln -s /Applications/osu\!.app/Content/Resources/drive_c/osu\! ~/.osu;`

After running this the data in lazer did not change. No error in command but the data from lazer was not affected. Is there a command for lazer to read the directories again. Like in normal osu when you press F4 I think it was to check manual editing to the songs files
