### ISSUE TITLE
ScreenTitle class needs to be rethought to implement the new design

### ISSUE THREAD

**Issue by TheWildTree** [ppy/osu#8423]
Right now the`ScreenTitle` is used almost exclusively in `FullscreenOverlays` mimicking their web counterparts, the exception being the multiplayer screen - it's the only place where `ScreenTitle` is used for purposes other than matching the web design. 

As of a while ago the web design has been changed to a much simpler one, which can't really be shared with the multi screen as a whole anymore.

I'm working on implementing the new design and the question is: what should I do with the `MultiHeaderTitle`? It looks rather outdated and I'm sure it's due to be replaced by something newer. The new overlay title design can still share specific parts with it, though, so the question is, what would be better:

- removing `ScreenTitle`, completely moving the old design as-is to `MultiHeaderTitle` and making the new one into something like `OverlayScreenTitle` (in the `Overlays` namespace, where it really belongs) - this would cause some code duplication (for the icon + title text logic, the multi header would add its separator + section name in its own class), but I think it'd be acceptable since it'd allow for proper separation

or: 

- implementing the new design in the base `ScreenTitle`, leaving it where it is right now, only having the icon and title there (as needed by the new design) and adding the old separator + section name to the `MultiHeaderTitle` deriving from it. This would slightly change the old design (mostly spacing) and is a bit less clean IMO, since it still ties two kinda unrelated components together, but doesn't cause as much code duplication.

**Comment by EVAST9919** [comment]
I made some changes to it in https://github.com/ppy/osu/pull/8051 to allow empty `Section` value (in this case the separator circle will disappear)

**Comment by TheWildTree** [comment]
Oh, good to know. Might be a third way to solve this after all, although I'd still kind of want to see it more separated from the `MultiHeaderTitle` since it's literally the only part that needs the old version now.

**Comment by bdach** [comment]
I'd be in favour of option 1. Code duplication isn't always bad if the duplicated code is simple enough. If the components are semantically separate (and they are - overlays are homogenous in the design sense, and the multiplayer title is entirely different).

**Comment by peppy** [comment]
1 sounds best.
