### ISSUE TITLE
Last Issue Regarding File Transfer from WineOsu! to Osulazer!

### ISSUE THREAD

**Issue by elh192773** [ppy/osu#8424]
I used the transfer files command for osu! to osu lazer but nothing has happened.

*quote*You just added an extra bang (exclamation point), lol. You missed the bang after osu. Here's the command that should work, I haven't run it.

ln -s /Applications/osu\!.app/Content/Resources/drive_c/osu\! ~/.osu;
*quote*
After running this the data in lazer did not change. No error in command but the data from lazer was not affected. Is there a command for lazer to read the directories again. Like in normal osu when you press F4 I think it was to check manual editing to the songs files

**Comment by peppy** [comment]
You need to run the import process after doing so, from settings.
