### ISSUE TITLE
cursor completely disappears when in F9 menu

### ISSUE THREAD

**Issue by Victrixen** [ppy/osu#8429]
Cursor completely disappears in the F9 menu, appears again when menu is closed. Both cutting edge and stable seem to be affected for me.

**Screenshots or videos showing encountered issue:** 

![screenshot214](https://user-images.githubusercontent.com/37912472/77471936-85ee0e80-6de9-11ea-8148-7d86ca11b452.png) (notice how the user box is highlighted with no cursor on it)
issue persists in fullscreen and windowed

can still select things and click on things, but cursor is invisible 

this happens on Win10 Enterprise N for me, not tested on any other versons

**Comment by bdach** [comment]
This is the incorrect place to be reporting issues with the stable version of the game - only reports concerning lazer are accepted here. Please see [ppy/osu-stable-issues](https://github.com/ppy/osu-stable-issues) instead.
