### ISSUE TITLE
Enabling raw input stops tablets from working as expected (jumping cursor position)

### ISSUE THREAD

**Issue by usagi123** [ppy/osu#8434]
**Describe the bug:** 
Cursor jump randomly then back to the intended position when the pen pressing the tablet even when the mouse click (F10) was disabled. The problem only happens with raw input enabled.

I do found this https://github.com/ppy/osu/issues/1301 but it seems like it was closed and the problem was mentioned from 2017 and 2018.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/cunhp

**osu!lazer version:** 
2020.320.1

**Logs:**

[database.log](https://github.com/ppy/osu/files/4380586/database.log)
[network.log](https://github.com/ppy/osu/files/4380587/network.log)
[performance.log](https://github.com/ppy/osu/files/4380588/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4380590/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4380591/updater.log)

**Comment by peppy** [comment]
What operating system and what tablet? Are you using unofficial drivers? If so, please use official ones before testing again.

**Comment by usagi123** [comment]
I am using the Huion 420 (osu!tablet), the one that they sell on osu!store few years ago
I am using driver for 420 (not H420) version 12.4.2 downloaded from Huion website

**Comment by peppy** [comment]
Have you tried turning off raw input? I'm imagining that osu! may be handling that but the driver also sending a non-raw update which is causing the jumping.

**Comment by usagi123** [comment]
Yes, if I turn off raw input, the problem is not there anymore. Things is, this doesn't happen with the current osu, which I use raw input with this same tablet.

**Comment by HoutarouOreki** [comment]
Happens on lazer and not Stable https://youtu.be/gP0a5P7rmIM
Both raw input and fullscreen, latest Windows 10, lazer 2020.421.0, HUION PenTablet 12.4.2.1811112 drivers

Disabling raw input means tablet area has to be changed with drivers to change "cursor sensitivity". Which is a pain because I need full area for drawing and changing it every time is very not fun.

**Comment by peppy** [comment]
Closing this in favour of #3911.
