### ISSUE TITLE
Scores should showing relative time of newly created plays

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu#8435]
**Describe the bug:** 
There should be indicators next to scores which are newly created presenting relative time so users can know which score matching the one they just played instead of having to click every score to see their date.
**Screenshots or videos showing encountered issue:** 
![osu_2020-03-25_20-50-42](https://user-images.githubusercontent.com/16283764/77544151-3ab42880-6edb-11ea-857e-ca9ac1521970.png)
**osu!lazer version:** 2020.325.0

**Comment by peppy** [comment]
@arflyte what’s the plan forward for these score panels? i’m guessing we will match the web version?

**Comment by Moltanicaa** [comment]
Maybe you should add sorting by game date / accuracy / number of points?

**Comment by arflyte** [comment]
score panels will be updated to match the web version.

**Comment by huoyaoyuan** [comment]
Current score panels are showing too few scores comparing to stable. Please consider expanding its area when updating its design.

**Comment by smoogipoo** [comment]
@arflyte I don't really understand what you mean by the web version. Do you mean these?
![image](https://user-images.githubusercontent.com/1329837/86503969-58543080-bdee-11ea-9e67-302803f0609f.png)

If so, the info there doesn't match the sort of details we're expecting of the song select panels. It doesn't have: avatar, user names, total score, combo, separation of score from the one below it (+1234, etc).
Furthermore, because those panels are made for an overlay rather than an area less than half the size of the screen, it seems like the padding and everything in those panels is going to make them hard to fit.

Can you make a quick mockup of how it should look, in a songselect-like area?

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
Sorry, scratch that. I'm redesigning the scores area underneath the song details. It will have more info.

**Comment by peppy** [comment]
Removing from milestone as this is going to happen as part of the song select design refresh.

**Comment by smoogipoo** [comment]
@arflyte Can you make sure this happens please? I've mentioned it several times and it can't an on-hover thing. The current redesign doesn't have this.

**Comment by arflyte** [comment]
I'll try. It ain't easy squeezing dates in it and still make it look good at the same time :(

**Comment by smoogipoo** [comment]
It doesn't need to be full dates, in-fact I'd prefer it wasn't because people play multiple times per-session/per-day/per-week and that sort of data can get really dense.

A timescale of seconds/minutes/hours/days (<3 or so) is fine.

**Comment by peppy** [comment]
aka match web and stable.

**Comment by arflyte** [comment]
I tried using web design, but it doesn't look good for the flashy song select. I'll focus on this today.

**Comment by arflyte** [comment]
![Figma_201009-023202](https://user-images.githubusercontent.com/3632750/95493692-c6088d80-09d7-11eb-957e-23f55527d421.png)

Something like this?

**Comment by peppy** [comment]
Seems fine, except we'd always show relative time (absolute in tooltip)

**Comment by LittleEndu** [comment]
How would the tilt look like on song select?

**Comment by peppy** [comment]
it's part of a design update, it fits fine don't worry.

**Comment by Joehuu** [comment]
Recent plays should be distinguished better (like on stable). Maybe removing the date after the play gets too old or have more visual cues?
