### ISSUE TITLE
osu!mania hold notes don't feel good

### ISSUE THREAD

**Issue by danielkp1234** [ppy/osu#8440]
**Describe the new feature:** 
In the osu!stable in mania when you are hitting sliders you can clearly see the impact on the sliders in Lazer it isn't really visible
**Proposal designs of the feature:** 
A way to see the impact you have when you hit sliders in mania like in the current version of stable

**Comment by peppy** [comment]
The default skin is far from being usable right now. Not sure we need to keep this issue open and it will likely be fixed in the next revamp of the skin, along with most other issues you can think of.

**Comment by danielkp1234** [comment]
@peppy Yeah I really enjoy the normal osu in Lazer but ofc mania catch and so needs more work to feel good but the revamp is pretty impressive so far.
Also, you have probably been asked this a thousand times but when do you think lazer would be able to replace stable.
 and if you need any help translating anything from English to Danish i will be happy to help :)

**Comment by snowynguyen** [comment]
Because of recent changes to the default mania skin, I think this issue can be closed.

**Comment by peppy** [comment]
Will close for now, thanks for the bump.
