### ISSUE TITLE
User only has statistics for their default ruleset

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8443]
**Describe the bug:** 
``User`` class only provides ``UserStatistics`` for that user's default ruleset. There should be a way to get ruleset specific statistics.

**osu!lazer version:** 
master branch commit 1587d4b26fbad691242544a62dbf017a78705ae3

**Comment by bdach** [comment]
This is probably better suited web-side.

**Comment by peppy** [comment]
Already exposed by web. Not sure we want to store all locally. When proposing a change to data storage, please also mention why it is required so we can rationalise and potentially offer alternatives.

This is already exposed by web, for what it's worth:

https://github.com/ppy/osu-web/blob/1ce2df6936ac9a94603ffff401c02369e0d812a4/routes/web.php#L408

**Comment by LittleEndu** [comment]
Beatmap carousel would require local user's performance points to select recommended difficulties. I was unsure how to do it if this statistic isn't available.

Also profile overlay currently only shows statistics for user's default ruleset and would also need a way to access info for other rulesets.

**Comment by LittleEndu** [comment]
You can actually specify for which ruleset you want the user for and then it will have the statistics for that ruleset. ``api.LocalUser`` just is always user's default ruleset.
