### ISSUE TITLE
Result screen should not highlight score if the wheel shows accuracy

### ISSUE THREAD

**Issue by Stalzak** [ppy/osu#8445]
Currently on the result screen, the first thing shown is the big wheel depicting the rating, with the score highlighted below. But since ratings relie on accuracy rather than score, this makes for a confusing ui.
To keep everything tidy, the defining stat for the wheel's completion should be shown right next to it.
If the ratings are still to be tied to accuracy rather than score, maybe accuracy should be shown next to score, or inside the wheel directly.

**Comment by peppy** [comment]
It's not final that the grades will be based on accuracy. They likely won't in the future. Therefore we are not tying them to one display metric.
