### ISSUE TITLE
Unconfined cursor can travel infinitely far off screen in every direction

### ISSUE THREAD

**Issue by Maoman1** [ppy/osu#8449]
**Describe the bug:** 
When the cursor is set to never confine and the app is in borderless windowed mode, the mouse cursor can continue traveling off the screen in *every* direction rather than just directions where there is another monitor. This makes it much more difficult to click something on the edge of the screen.

**Screenshots or videos showing encountered issue:** 
I wanted you to see my hand moving my mouse so I took a video with my phone instead of with OBS
https://drive.google.com/file/d/17omiwLFeXGYuX8aBmyC37sRnjDXgHE5A/view

**osu!lazer version:** 
2020.325.0
(It's been happening since before this version, I just didn't make a report until now)

**Logs:**
[database.log](https://github.com/ppy/osu/files/4385493/database.log)
[network.log](https://github.com/ppy/osu/files/4385494/network.log)
[performance.log](https://github.com/ppy/osu/files/4385495/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4385496/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4385497/updater.log)

**Comment by swoolcock** [comment]
Do you have raw input enabled?  If so can you try it without?

**Comment by Maoman1** [comment]
I do and turning it off does fix it, but now I can't adjust my cursor speed.

**Comment by swoolcock** [comment]
I can reproduce it myself with raw input enabled, I'll check it out.  Thanks.

**Comment by peppy** [comment]
https://github.com/ppy/osu-framework/issues/2247
