### ISSUE TITLE
Taiko doesn't continue to results screen on completion

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#845]
Likely some issue to do with incorrect values on `drawableObjects.All(h => h.Judged)` in `HitRenderer`.

On a further thought drum roll ticks may be the cause since they don't result in misses. `HitRenderer.Judged` should probably be made virtual and then overridden in ticks to always be true.

**Comment by smoogipoo** [comment]
This must've been fixed along the way at some point (can't replicate anymore). Lots of changes have happened to scoring/judgements since this issue was made.

**Comment by plankp** [comment]
On 2018.1120.0 this happens on this beatmap:
https://osu.ppy.sh/beatmapsets/74658#osu/211879

(Also if you do autoplay on normal difficulty, fast forward to the end and then rewind replay to start from 0:06, it will start hitting invisible notes at around 0:03, followed by strange hit sounds if you quit to song selection menu with escape key)

**Comment by peppy** [comment]
Reopening for now
