### ISSUE TITLE
Fast rewind

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8453]
After the patch of February 25, during fast rewind, the sounds of the hitsound no longer sounded (they sound extremely annoying). Now they sound again. I think it makes sense to remove them again.

Screenshots or videos showing encountered issue:
https://youtu.be/eMQMDOXKgXw - until 25.02
https://youtu.be/uGrfTbdZDkI - after 25.02
https://youtu.be/VfSw1GbgF0w - March 26
osu!lazer version:
2020.325.0

**Comment by peppy** [comment]
Do you mean fast forward?

**Comment by peppy** [comment]
I don't think this was ever "fixed", and probably just sounds worse now due to the increased concurrency. Muting completely is being tracked here https://github.com/ppy/osu/issues/3113.
