### ISSUE TITLE
mouse pointer disappears when on the window (mac os)

### ISSUE THREAD

**Issue by mnkaaru1064** [ppy/osu#8457]
well, here's the problem:

https://youtu.be/ZEk2oHcGgR4

osu!lazer version: **2020.118.0** to **2020.325.0**

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/4389692/logs.zip)

**Comment by mnkaaru1064** [comment]
so apparently I fixed this problem by deleting the **cache** folder... nice.

**Comment by swoolcock** [comment]
Likely duplicate of #8279 and many others related to raw input on macOS.  Please follow the instructions in the linked issue if it happens again.
