### ISSUE TITLE
Osu lazer cursor not moving after enabling raw input (mac) 

### ISSUE THREAD

**Issue by JinYagamislayer** [ppy/osu#8458]
My cursor is not moving 

Screenshot or video: not available 

Latest version (I dowloaded it off Dean's twitter) 

I could not access logs

**Comment by bdach** [comment]
Raw input issues are known on macOS (#8279, #7313, #7102, #6519, #4359, #3448).

Please try disabling it again with <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>R</kbd> or by deleting contents of `~/.local/share/osu`.
