### ISSUE TITLE
Storyboards and videos are forced into 4:3 ratio

### ISSUE THREAD

**Issue by Luxiono** [ppy/osu#8459]
**Describe the bug:** 
Most beatmaps I have have widescreen support, but after the new March 25th update, the video or storyboard is always in 4:3 ratio.
**Screenshots or videos showing encountered issue:** 
![osu_2020-03-27_00-00-35](https://user-images.githubusercontent.com/55364481/77708064-64358880-6f9d-11ea-9414-37194846a48b.png)
**osu!lazer version:** 
2020.325.0
**Logs:**

[performance.log](https://github.com/ppy/osu/files/4390710/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4390711/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/4390712/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4390713/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4390714/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/4390715/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4390716/updater.log)
[database.log](https://github.com/ppy/osu/files/4390717/database.log)
[network.log](https://github.com/ppy/osu/files/4390718/network.log)

**Comment by peppy** [comment]
Can you give an example of the beatmap you're seeing this on?

**Comment by Luxiono** [comment]
A forgotten note, the background when storyboards/video is turned off is fullscreen. Definitely the storyboard. Lemme get a picture of settings from osu!stable.

**Comment by Luxiono** [comment]
![uh oh a problem](https://user-images.githubusercontent.com/55364481/77708850-9c3dcb00-6f9f-11ea-8546-abab91dc5b0a.jpg)

**Comment by jai-x** [comment]
This is reproducible with this beatmap set: https://osu.ppy.sh/beatmapsets/763337

In osu!stable the storyboard will take up the entire background in a 16:9 aspect ratio.

In osu!lazer the storyboard will be restricted to the size of the playfield, as show in the OP.

**Comment by MeguMario** [comment]
I've tested out with more maps, still the same 4:3 force, some even clearly show some element being cut off
https://osu.ppy.sh/beatmapsets/763337
![osu_2020-03-28_00-14-05](https://user-images.githubusercontent.com/44724359/77782717-4db92b00-708a-11ea-8855-3583d408bd6f.jpg)
https://osu.ppy.sh/beatmapsets/436611
![osu_2020-03-28_00-14-46](https://user-images.githubusercontent.com/44724359/77782720-4f82ee80-708a-11ea-9506-8a0e5af58b7f.jpg)
https://osu.ppy.sh/beatmapsets/470977#osu/1012836 (The code box is cut off)
![osu_2020-03-28_00-15-48](https://user-images.githubusercontent.com/44724359/77782723-501b8500-708a-11ea-8096-12a6a14ee635.jpg)
https://osu.ppy.sh/beatmapsets/700790#osu/1483485
![osu_2020-03-28_00-19-26](https://user-images.githubusercontent.com/44724359/77782725-50b41b80-708a-11ea-971c-09592df4aa86.jpg)
https://osu.ppy.sh/beatmapsets/756794
![osu_2020-03-28_00-20-27](https://user-images.githubusercontent.com/44724359/77782728-514cb200-708a-11ea-9b5f-921279373de0.jpg)
https://osu.ppy.sh/beatmapsets/463479#osu/992437
![osu_2020-03-28_00-21-43](https://user-images.githubusercontent.com/44724359/77782731-51e54880-708a-11ea-8068-c4c8787cbe7a.jpg)

**Comment by bdach** [comment]
This has regressed at #8426. Adding default per-layer masking has made it so widescreen support no longer matters, as all layers are in a hard-coded 640x480 container:

https://github.com/ppy/osu/blob/cf890efa420de62ccad053e62b7caac2407ebfdc/osu.Game/Storyboards/Drawables/DrawableStoryboard.cs#L51-L56

and have `RelativeSizeAxes` set to `Both`, ensuring that coordinates are properly handled.

As far as I can see stable doesn't really do any masking on storyboards (I have a lot of maps that have sprites that should probably not be visible on my 21:9 monitor). This does however bring back the issue that apparently [some maps might get letterboxed video if masking is moved back to the whole storyboard](https://github.com/ppy/osu/pull/8167#discussion_r392050948) (@voidedWarranties - mind providing an example of such a beatmap, since you brought it up?)

So it seems the desired behaviour is:
* if the storyboard has a video, don't mask
* if the storyboard doesn't have a video, mask

I guess the best way forward I can see here is having moving the 640x480 hard-coded sizing down to all layers such that the structure looks like this:

```
DrawableStoryboard (854x480 or 640x480, depending on widescreen support)
  Container (same size as parent)
    DrawableStoryboardLayer (same size as parent)
      Container (always 640x480, centered within parent, storyboard elements are only added to this)
```

which makes it possible to preserve the per-layer masking but I'd like to confirm this is the direction we want to go before proceeding.

**Comment by voidedWarranties** [comment]
> some maps might get letterboxed video if masking is moved back to the whole storyboard

In this case, maps with a video and `WidescreenStoryboard` set to `false` will do this, for example all diffs of [this map](https://osu.ppy.sh/beatmapsets/680251/#osu/1438380) except for Hard (which will display the video correctly).

**Comment by peppy** [comment]
@bdach your experience with stable sounds weird. stable definitely does some degree of masking (it adds "black" bars when not in widescreen mode)

![2020-03-30 10 40 47](https://user-images.githubusercontent.com/191335/77867657-1d80b080-7273-11ea-94f8-f6d5778ee41a.gif)

Could your skin possibly be removing these?

**Comment by bdach** [comment]
To clarify / correct my previous statement: it seems that if `WidescreenStoryboard` is off, then everything *is* masked to 4:3 on stable, and if it is on, then I see no masking whatsoever. If we're going for the same behaviour in lazer then I guess the fix becomes even easier (just disable masking of all layers on widescreen storyboards), but then resolutions with aspect ratio other than 16:9 might look bad.

**Comment by bdach** [comment]
I've tried a few solutions for this, and the situation is that while masking widescreen storyboards to 16:9 seems like a correct thing to do it incurs a performance hit, which is especially bad in the case of my [proposal from earlier](https://github.com/ppy/osu/issues/8459#issuecomment-605698881).

Per-layer masking performs really badly (2-3x times worse framerate [on `world.execute(me)`](https://osu.ppy.sh/beatmapsets/470977#osu/1012836)) in comparison to masking the entire storyboard. If you'd like to see / run that solution, [here's a WIP branch](https://github.com/bdach/osu/tree/fix-widescreen-storyboards).

I'm thinking we might want to revert to masking the entire storyboard, but just disabling that masking in case there's a video present. It feels really bad code-wise, but I'm not sure we can do better.
