### ISSUE TITLE
Problems with raw input.

### ISSUE THREAD

**Issue by VolantesOwO** [ppy/osu#8463]
When I turn on raw input, I can't mouse my cursor and can't click on the screen. Can't play anymore because of this problem. Mac btw

**Comment by enoslayd** [comment]
Turn it off cause raw input only works properly on windows for now

**Comment by VolantesOwO** [comment]
> Turn it off cause raw input only works properly on windows for now

The problem for me is that I can't click at all inside the game so I can't turn it off.

**Comment by peppy** [comment]
ctrl-shift-r
