### ISSUE TITLE
Background dim doesn't work on certain beatmaps with Storyboard turned on

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#8465]
Describe the bug: Background dim doesn't work on certain beatmaps with Storyboard turned on, even if there doesn't seem to be one. On stable you can see the background just fine.

Screenshots or videos showing encountered issue: https://streamable.com/9bu0t

osu!lazer version: 2020.325.0

[logs.zip](https://github.com/ppy/osu/files/4392997/logs.zip)

**Comment by bdach** [comment]
Did you happen to download the video-less version of this beatmap?

Logs show a nullref which should have been fixed with today's release (#8455), but the fact remains that on video-less variants of maps the background image should show for parity with stable.

**Comment by Theighlin** [comment]
So I deleted the beatmap and reimported it a couple of times directly into lazer, with and without video. It does the same thing. Also it was on 2020.327.0 the whole time, I didn't notice it, sorry.

**Comment by bdach** [comment]
Did you restart after deleting? Beatmaps are not actually purged until next restart - reimporting before that just restores the old data.

**Comment by Theighlin** [comment]
It works, thank you for your time.
