### ISSUE TITLE
Storyboards should have access to classic skin files

### ISSUE THREAD

**Issue by CtrlAltWaverick** [ppy/osu#8472]
**Describe the bug:** 
Beatmaps don't pull sprites from skins.

**Screenshots or videos showing encountered issue:** 
No screenshots available, but can be reproduced by attempting to play Supairo's aspire!taiko map "Function Phantom - Algebra" in osu!stable and comparing it to playing in osu!lazer.

**osu!lazer version:** 
2020.327.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4395360/database.log)
[network.log](https://github.com/ppy/osu/files/4395361/network.log)
[performance.log](https://github.com/ppy/osu/files/4395362/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4395363/runtime.log)

**Comment by enoslayd** [comment]
Taiko skins is not implemented yet

**Comment by peppy** [comment]
Will keep this open as we don't yet have an issue to track this task.

**Comment by CtrlAltWaverick** [comment]
this isn't quite "basic skinning support" in my opinion, as the skin displays properly for playing purposes, but not for storyboarding. not being able to use custom taiko skins is another issue entirely. i wasn't quite clear before, i meant maps couldn't pull even default assets for use in storyboarding

**Comment by peppy** [comment]
oh, that's a very different thing.

**Comment by CtrlAltWaverick** [comment]
sorry, i wasn't very clear originally
