### ISSUE TITLE
Supporter features not available offline

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8478]
Everything is described in the title.
![osu_2020-03-28_16-34-02](https://user-images.githubusercontent.com/59089206/77821661-adb9db00-7137-11ea-8732-d5e07d3b30f3.png)
osu!lazer version:
2020.327.0

**Comment by GSculerlor** [comment]
Beatmap as background source is supporter feature afaik, I think that's normal why it's not displayed when you offline

**Comment by Moltanicaa** [comment]
Maybe you’re right, you didn’t think so conceived.

**Comment by bdach** [comment]
@GSculerlor is correct - the beatmap background won't show if you're not logged in as there's currently no way to tell if you should have supporter features enabled when offline.

I imagine when users are going to be persisted to database this will improve.

**Comment by peppy** [comment]
I don't foresee this changing. You can use the "appear offline" option rather than logging out.
