### ISSUE TITLE
Not all maps have a "details" button.

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8480]
If I have a local map that is not on the site, then some of these maps do not have a "details" button, while others have the same ones. Pressing the "details" button leads to a blank page of the map, so it’s better to remove it, and write in the information "local map".
The first screenshot shows a map where one difficulty does not have this button, and the second one has.
![osu_2020-03-28_21-13-15](https://user-images.githubusercontent.com/59089206/77821889-67657b80-7139-11ea-965c-243cc296a8b6.png)
![osu_2020-03-28_21-13-22](https://user-images.githubusercontent.com/59089206/77821898-806e2c80-7139-11ea-812f-cd77860ebc08.png)
![osu_2020-03-28_21-13-32](https://user-images.githubusercontent.com/59089206/77821900-8237f000-7139-11ea-9a88-d734c7d1c32a.png)

osu!lazer version:
2020.327.0

**Comment by peppy** [comment]
Please give an example of a ranked map where this happens. The conditions for this look correct, so if anything the popup dialog should probably show an error if it can't load, rather than the "details" options being removed.

**Comment by Moltanicaa** [comment]
I mean only local map. They not have page on site, but have "details".

**Comment by peppy** [comment]
what is "local map"

**Comment by Moltanicaa** [comment]
This is a map that is not published on the site, but is in the .osz file format on my computer.

**Comment by peppy** [comment]
Could you please upload the map and link in this thread? It may be in a bad state.

**Comment by Moltanicaa** [comment]
A little bit later

**Comment by Moltanicaa** [comment]
[egu - EXIT THIS EARTH'S DUNGEON (Doomsday is Bad) [rrtyui].zip](https://github.com/ppy/osu/files/4398775/egu.-.EXIT.THIS.EARTH.S.DUNGEON.Doomsday.is.Bad.rrtyui.zip)

**Comment by Moltanicaa** [comment]
The second flatly refuses to boot

**Comment by peppy** [comment]
Both of these maps have online beatmap set IDs embedded that are incorrect. Will add a step to clear these on import.
