### ISSUE TITLE
Graphical glitch with lazer's icon in the windows 7 volume mixer

### ISSUE THREAD

**Issue by Maoman1** [ppy/osu#8482]
**Describe the bug:** 
The icon for osu lazer in the volume mixer is scaled up massively and covers the volume slider and mute buttons. I've never seen this happen with any other program, so despite the issue being in volume mixer I assume the bug has to do with osu rather than with windows. 

**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/GRFl1Ts.png

**osu!lazer version:** 
2020.327.0

**Logs:**
[updater.log](https://github.com/ppy/osu/files/4397278/updater.log)
[database.log](https://github.com/ppy/osu/files/4397279/database.log)
[network.log](https://github.com/ppy/osu/files/4397280/network.log)
[performance.log](https://github.com/ppy/osu/files/4397281/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4397282/runtime.log)

**Comment by EVAST9919** [comment]
Duplicate of https://github.com/ppy/osu/issues/2424

**Comment by Maoman1** [comment]
The icon in mine is scaled too though, not just too large an image. See the screenshot
