### ISSUE TITLE
Cursor missing when not playing a beatmap

### ISSUE THREAD

**Issue by plaggeds** [ppy/osu#8487]
**Describe the bug:** 
Cursor is missing when not Playing a beatmap.
**Screenshots or videos showing encountered issue:** 
https://drive.google.com/file/d/1r1WqQtnYKRv53CGBoi1urzBSYSLEYibh/view?usp=sharing
(Don't know if you can see it but my 'cursor' is hovering the osu editor menu.)
**osu!lazer version:** 
2020.327.0
**Logs:**
[session.log](https://github.com/ppy/osu/files/4398742/session.log)
[update_success.log](https://github.com/ppy/osu/files/4398743/update_success.log)
[runtime.log](https://github.com/ppy/osu/files/4398744/runtime.log)

**Comment by bdach** [comment]
The logs you've attached are from stable. Please recheck `%AppData%/osu/logs` and attach again.

I can't really reproduce this, so it's possible it'll be hardware specific. Mind giving your hardware specs & info on what sort of input devices you're using? Also, would you be able to attach a video of this?

**Comment by plaggeds** [comment]
Sorry for submitting the wrong logs. Here are the correct ones:
[network.log](https://github.com/ppy/osu/files/4401461/network.log)
[performance.log](https://github.com/ppy/osu/files/4401462/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4401463/runtime.log)
[database.log](https://github.com/ppy/osu/files/4401464/database.log)

My PC Specs are:
(Acer Aspire V3-571G)
Intel Core i7-3630QM
NVIDIA GeForce GT730M
8GB DDR3 Memory
1TB HDD

**Comment by peppy** [comment]
You've probably lost it off the edge of the screen due to lack of cursor confining on some PC configurations when raw input is on.

Hit Ctrl-Alt-R to disable raw input or Alt-Enter to disable fullscreen.

**Comment by plaggeds** [comment]
https://streamable.com/pv6n3

Still doesn't work.

**Comment by peppy** [comment]
No idea sorry.

**Comment by Pythonimous** [comment]
Had similar issue on Win. The cursor is clearly there, and it interacts with buttons (hovering over them, you can click, etc.), it just doesn't show up. It, however, reappears in beatmaps to disappear again in the menu.
Seems to sometimes occur randomly upon starting osu!, with no specific circumstances to intentionally reproduce; it just happens.

**Comment by plaggeds** [comment]
Tried opening Lazer and the cursor appeared. After a few minutes of leaving it closed, the cursor disappears.

**Comment by bdach** [comment]
Both cases with logs reported are from computers running Intel HD Graphics 4000, so I'm guessing this'll be another intel-specific issue.

I'd recommend everyone hitting this on that particular card to check for device driver updates. If anyone else is hitting this, but on a different graphics card, please let us know.

**Comment by AqilCont** [comment]
I updated my drivers a few days ago, before I took the screenshot(while lazer was on fullscreen and hovering on a button without a visible mouse). I don't spot any mouse/draw-related errors either in logs so I am clueless to whats going wrong with it.

**Comment by bdach** [comment]
Yes, well, if it were visible in logs we'd probably be on the way to fixing it already. As it stands we don't really have anything to go off with what we know, besides the hunch that this is hardware-specific.

**Comment by smoogipoo** [comment]
Just wondering... Can you try enabling the "bypass front to back render pass" at the bottom of settings?

**Comment by MTGPROD** [comment]
@smoogipoo 
Enable **bypass front to back render pass** change nothing. Big proof [here](https://youtu.be/_oSJrw2XnzQ)

**Comment by smoogipoo** [comment]
That's very weird that it happens the second time around. Can you press Ctrl+F3 in menu and take a picture of the dialog?

**Comment by MTGPROD** [comment]
https://maxsteel.karibsen.fr/image/lazer.png ( @smoogipoo )

But my theory is that if the we start and that the cursor is visible and if you restart it but it starts with the black screen bug the next restart the cursor disapear. (Like in the video)

**Comment by smoogipoo** [comment]
That's very strange. The cursor is supposed to reside in that second texture, but it's completely blank. Given that it did create the atlas and that nothing else is placed inside that atlas, I think it's a fair assumption to say it did read the image correctly, but that somehow the upload failed.

Also interesting to note that the atlas doesn't seem to even contain the white pixel.

**Comment by MTGPROD** [comment]
Just restarted the game, the cursor is here. That's so weird
![image](https://user-images.githubusercontent.com/40500781/84581169-88577780-adde-11ea-84c8-1552345b8906.png)

**Comment by peppy** [comment]
A good next step may be to add verbose `glGetError` output, or have the user attach a GL profiler which can log all errors (I forget which is best for this). Sounds like we're doing something wrong or some kind of threading anomaly is occurring.

**Comment by smoogipoo** [comment]
Best way I can think of getting more output here is by compiling osuTK in debug mode.

@MTGPROD Can you extract the following and replace the existing `osuTK.dll` in the installation directory with this one? Keep in mind that the installation directory is _not_ the same as the user directory (it'll be the latest `app-*` folder inside `%LOCALAPPDATA%\osulazer`).

[osuTK.dll.zip](https://github.com/ppy/osu/files/4777857/osuTK.dll.zip)

**Comment by smoogipoo** [comment]
I'm also curious on whether any notification pops up when the game starts, saying something like "Texture could not be loaded via STB".

**Comment by MTGPROD** [comment]
[DxDiag.txt](https://github.com/ppy/osu/files/4787780/DxDiag.txt) here is your file

**Comment by MTGPROD** [comment]
@smoogipoo

**Comment by smoogipoo** [comment]
Can you do the other thing I suggested too?

**Comment by MTGPROD** [comment]
@smoogipoo Ah yes I have no notification like this when the game starts, but I figured out something. When you start the game in fullscreen the cursor's texture do not load if the game has started in fullscreen (with the bug where you can't see the game, the screen remains black but you can hear and interact with the game.) But if we restart it in windowed the cursor's texture is loaded.

**Comment by TheWildTree** [comment]
I think smoogi meant the part about replacing `osuTK.dll` from his earlier comment.

**Comment by MTGPROD** [comment]
I already do this, nothing change

**Comment by yansaan** [comment]
Still cursor not visible in full screen mode

**Comment by smoogipoo** [comment]
As an update, I'm still tracking this issue, and am awaiting on a system to arrive that matches one of the ones posted in here.

**Comment by MTGPROD** [comment]
I'm sorry but 
![osu_2020-07-11_23-48-56](https://user-images.githubusercontent.com/40500781/87234463-7236da00-c3d1-11ea-9231-5ca0ebf7b84b.jpg) the cursor still invisible

**Comment by bdach** [comment]
can anybody else from this thread confirm or deny whether this is fixed? @plaggeds, @AqilCont?

@MTGPROD in the dxdiag attached I see you seem to have a different graphics card than the other users (`Intel HD Graphics` and not `Intel HD Graphics 4000`). please confirm whether that is really the full name of the graphics card on the machine you're testing on.

**Comment by AqilCont** [comment]
Oh, not at all. I played yesterday without a cursor... I just kind of got used to it.

**Comment by plaggeds** [comment]
Sorry but the laptop that I had was given away to my cousin. Sorry about that.

**Comment by bdach** [comment]
I guess given that we seem to be 0/2 when it comes to whether this is fixed this needs to be reopened...

**Comment by smoogipoo** [comment]
@AqilCont please post a [dxdiag report](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) and the runtime.log file from osu!

**Comment by LevelMasterGD** [comment]
Happenings to me too:
Device: Laptop
intergrated graphics processor: Intel(R) HD Graphics 4000
Graphics chipset: AMD RADEON HD 7670M

osu!lazer version: 2020.712.0

**Comment by smoogipoo** [comment]
@KilluaYT @AqilCont @MTGPROD Please try the newest release (2020.714.0).

**Comment by AqilCont** [comment]
I just tried it, and except for the rocky first start(gray screen + crash + reset of a bunch of random settings), it is a much better experience. Experiencing better performance(although not as good as stable), and the mouse is finally back. Thanks for the hard work, and I am sorry for the belated response since I was taking a break from GitHub for a bit.

**Comment by MTGPROD** [comment]
@bdach I'm on a Intel HD Graphics 2500

**Comment by MTGPROD** [comment]
Okay, now the cursor is back ! Good job everyone 
![osu_2020-07-16_15-46-13](https://user-images.githubusercontent.com/40500781/87678778-a288ca80-c77b-11ea-9136-a7571c85ef2b.jpg)
