### ISSUE TITLE
Overlapped break timer

### ISSUE THREAD

**Issue by Torikatou** [ppy/osu#8503]
**Describe the bug:** Break timer overlapping the pause screen

**Screenshots or videos showing encountered issue:** 
![osu_2020-03-30_17-41-30](https://user-images.githubusercontent.com/62882246/77903994-fabfbd80-72ad-11ea-996c-18cb9a3b3a44.jpg)

**osu!lazer version:** 2020.327.0

**Comment by TheWildTree** [comment]
Fixed in the next release (#8475)

**Comment by Game4all** [comment]
A PR fixing this issue has been merged recently (#8475). 
Please update your game

**Comment by bdach** [comment]
Closing as duplicate.
