### ISSUE TITLE
Changing volume on laptop causes fullscreen glitch

### ISSUE THREAD

**Issue by Pythonimous** [ppy/osu#8504]
Check screenshot. Changing volume via laptop key combinations causes game window (fullscreen) to move into corner; after sound icon disappears, the game returns to normal.

**Screenshots or videos showing encountered issue:** 
![Screenshot from 2020-03-30 13-59-08](https://user-images.githubusercontent.com/24483005/77907757-e3270b80-7292-11ea-8ce5-f2d7a1b91772.png)

**osu!lazer version:** 
2020.327.0

**Comment by peppy** [comment]
This is not something we can handle. Please consider running in borderless or uninstalling the volume overlay software.

**Comment by Pythonimous** [comment]
This issue did not occur until the latest patch.

**Comment by peppy** [comment]
Nothing has changed in the latest updates which affect such issues.

**Comment by TheWildTree** [comment]
If this really started happening in the latest release, perhaps something regressed in ppy/osu-framework#3401?

**Comment by peppy** [comment]
Very unlikely. That PR should have changed zero behaviour.

**Comment by Pythonimous** [comment]
It's not just changing volume, it is switching layout as well, where the is definitely no overlay software and also did not happen until the latest patch. Could you maybe at least consider looking into the issue?

**Comment by bdach** [comment]
It is borderline impossible for us to begin investigating this without having your exact linux setup and even then it's likely to be something deep in osutk which is on borrowed time as is anyway.

You could try running with the experimental `--sdl` flag and seeing if that changes behaviour. If yes, then you'll just have to wait for when the transition to SDL is done. If not, then you could help us diagnose the issue if you want to have it resolved.

**Comment by Pythonimous** [comment]
I am all up for debugging myself, if that is the case :)
Could you tell me what my possible next steps are, should `--sdl` not solve the problem?

**Comment by bdach** [comment]
To begin with, you could confirm that a version update indeed caused this to regress by comparing previous releases, or better yet, perform a git bisection if that's something you're familiar / comfortable with.
