### ISSUE TITLE
Choosing a map from profile shows incorrect mode icons in some cases

### ISSUE THREAD

**Issue by hwsmm** [ppy/osu#8505]
**Describe the bug:** 
When I click a mania map which also have other game mode diffs in play history on my profile, lazer shows the first mode icons (in order of osu, taiko, catch and mania) even if I clicked mania one

**Screenshots or videos showing encountered issue:** 
![asd](https://user-images.githubusercontent.com/9151706/77911023-171e2300-72cb-11ea-8d10-47161d8e83bd.jpg)

![aa](https://user-images.githubusercontent.com/9151706/77910845-c9091f80-72ca-11ea-9fb4-131779afac25.jpg)

**osu!lazer version:** 
commit 6907522cd7f24fb56a8503547478ef033af7e932

**Comment by peppy** [comment]
User profiles don't support per "mode" display yet, if that's what you mean. Not mod.

**Comment by coinworld** [comment]
Maybe my english is bad
In first picture, I picked a mania map then the song info shows standard mod icons for mania map

**Comment by coinworld** [comment]
I just noticed I made typos, sorry for this

**Comment by EVAST9919** [comment]
Selecting mania map doesn't force the overlay to select the mania tab, even seems like the mania map has been selected

**Comment by peppy** [comment]
I can't seem to make this happen. Do you have reproduction steps?

**Comment by coinworld** [comment]
Not sure this still happens but reproduction steps are:
- Suppose that there is a map which contains standard diff and mania diff
- If I play the **mania** diff once or more in stable, the map should be on play history
- then in lazer profile, select the mania diff in play history (Finding such map is too tiring in my profile, but I was able to reproduce with two maps)

**Comment by peppy** [comment]
Right, so you're just saying it's loading to the wrong beatmap info tab?

**Comment by coinworld** [comment]
No, information about the map is correct but mode icon is incorrect

**Comment by Joehuu** [comment]
Closing in favor of https://github.com/ppy/osu/issues/16566.
