### ISSUE TITLE
Unable to import replays

### ISSUE THREAD

**Issue by cupppu** [ppy/osu#8506]
**Describe the bug:** Replay download seems to work as usual, but the import has failed

**Screenshots or videos showing encountered issue:** 
![osu_2020-03-30_20-41-47](https://user-images.githubusercontent.com/7279624/77913940-b0e3d100-72c7-11ea-85bf-4d15588456ce.png)

**osu!lazer version:** master branch commit f25b1b

**Logs:**
[database.log](https://github.com/ppy/osu/files/4402845/database.log)
[performance.log](https://github.com/ppy/osu/files/4402847/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4402848/runtime.log)

**Comment by peppy** [comment]
Does this happen with all replays, or specific replays?

**Comment by cupppu** [comment]
Limited testing, I think it affects all replays, I haven’t tested manually imported replays

**Comment by peppy** [comment]
It looks like your database is in a weird state. Are you able to attach it (client.db)?

**Comment by cupppu** [comment]
It’s getting late now, will do tomorrow. 
Just to note, I’ve tested all commits from 2020.325.0 and f25b1b was the first commit to have this problem for me

**Comment by cupppu** [comment]
Looks like the latest commit (e0a876) fixed this issue, issue reappeared when I reset to commit 9da6bb

How should I attach client.db as I can't upload it through github

**Comment by peppy** [comment]
Nothing has changed which should affect the issue you reported.

You can upload it anywhere that isn't github then link it here, or email to me (pe@ppy.sh)

**Comment by cupppu** [comment]
I've emailed it to you but in case it didn't make it
[client.db](https://filebin.ca/5HTIoDvP11Vd)

**Comment by peppy** [comment]
@cupppu can you confirm whether you were trying to import mania replays specifically? the screenshot shows that you're in osu! mode so I didn't think much of it, but i can potentially see how this could happen if it is mania.

**Comment by cupppu** [comment]
no I was importing standard mode replays

**Comment by peppy** [comment]
From stable or .osr files directly?

**Comment by cupppu** [comment]
I was "importing" through score page replay downloads, I am trying manual .osr imports now

**Comment by cupppu** [comment]
I've just tested some more beatmaps, and I think it only affects certain beatmaps
on the 1 .osr import was successful but I don't that particular beatmap was affected

**Comment by peppy** [comment]
Could you please attach a failing .osr and also confirm it still happens on master?

**Comment by peppy** [comment]
I've figured out the cause of this, do not require the .osr.

Thanks for the bisecting!

**Comment by cupppu** [comment]
I was writing how I have 2 replays of the same beatmap but by 2 different players, one of them worked and other one doesn't

**Comment by peppy** [comment]
Yep, will only happen when certain mods are applied. All good.
