### ISSUE TITLE
Low Priority - consider enabling Raw Input checkbox on macOS

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#8508]
Consider reenabling the Raw Input checkbox on macOS because with raw input enabled and Input monitoring allowed for osu! in macOS Catalina, raw input really does work but only with USB mice. I've tested and with raw input enabled, Magic Trackpad 2 and Magic Mouse 1 do not work (cursor won't move with raw input enabled). Maybe consider reenabling this for people using USB mice.

osu!lazer version tested with: 2020.320.1

**Comment by bdach** [comment]
The reason that it was disabled anywhere else but Windows is due to a multitude of reports from linux & macOS users reporting their input being broken after turning it on (accidentally or not). It will return when there is a proper implementation that works cross-platform.

**Comment by ThatsNiceGuy** [comment]
Alright well yea I can see how people may have broken their input since trackpads and Magic Bluetooth peripherals don’t work. Well, I’ll have to wait then.
