### ISSUE TITLE
Osu Crashes at Startup

### ISSUE THREAD

**Issue by JennySkittle** [ppy/osu#8510]
**Describe the crash:** 
Basically I open osu!lazer and it shows a black screen for a couple seconds then it just closes. When i tried to re download it one time and opened it it showed the whole startup sequence and i was on the main screen but as soon as i pressed any button it just crashed again
**Screenshots or videos showing encountered issue:** 
This is normally what happens https://youtu.be/ybBOQA6X530

This video is a weird thing osu!lazer did when i started recording for an example but i dont even know how to describe it. This is the only time this has happened https://youtu.be/TyxS32X6QXQ
**osu!lazer version:** 
2020.327.0
**Logs:**
https://mega.nz/#F!IFlDUCBT!STj5zrqsyqBOxlsK7WqaZA

**Computer Specifications:** 
Graphics Card: Gigabyte GeForce GTX 1660
Processor: AMD Ryzen 7 2700X 
RAM: 16 GB

**Comment by bdach** [comment]
The logs you've attached are from osu!stable (lazer's logs are in a different directory). Please try to re-attach them. Additionally, please attach Windows Event Viewer info by performing the following steps:

1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by JennySkittle** [comment]
ok https://mega.nz/#F!9A0zlCBS!n2E1TlE8NM-GLT6g2Kt4gQ here you go @bdach

**Comment by bdach** [comment]
It's an NVIDIA driver crash:

```
Unable to recover from a kernel exception. The application must close.

Error code: 3 (subcode 7)
 (pid=17688 tid=21056 osu!.exe 64bit)
```

Please try to update your graphics card drivers; if that doesn't help, please report the issue on NVIDIA forums.

**Comment by JennySkittle** [comment]
alrighty @bdach
