### ISSUE TITLE
Suggestions to play taiko mode on mobile

### ISSUE THREAD

**Issue by blueingsh** [ppy/osu#8512]
**Describe the new feature:** 
There would be a drum in the middle to play taiko that would be like this https://youtu.be/lG_xOrGyp1k, For example in the video you can see the player clicks the drum to enable the inside of the taiko drum and to enable the side of the taiko drum you would tap by the drum.

**Comment by TheWildTree** [comment]
Has already been suggested multiple times and is being tracked in #4201.

**Comment by blueingsh** [comment]
Oh okay I’ll close this
