### ISSUE TITLE
Basic editor undo/redo

### ISSUE THREAD

**Issue by crocodilelawyer** [ppy/osu#8515]
**Describe the new feature:** 
A basic undo/redo feature would be immensely helpful in testing editor. 
I assume that this will be implemented eventually, but simple Ctrl+Z and Ctrl+Y shortcuts would be nice to have.

**Comment by peppy** [comment]
Probably covered by https://github.com/ppy/osu/issues/6143. Still a bit further away, as we want to have the editor in a good state before looking into this. If you're interested in implementation then please ask in the other issue and we can provide a direction for implementation.
