### ISSUE TITLE
Beatmap sometimes refuses to load if video file is .mp4

### ISSUE THREAD

**Issue by mmi-osu** [ppy/osu#8517]
I've had this happen twice on 2 separate beatmaps now, as per title, when the beatmap has a video present, in the .mp4 file format. When attempting to play, it just hangs with a spinning circle.

There is no option in the video to be disabled. When deleting the video in the beatmap folder, it loads normally

I tried again, after closing and re-opening osu! and it seems to load now, how bizzare, I also asked a friend to try and replicate this error to no avail.

https://osu.ppy.sh/beatmapsets/989457#osu/2069823 - example beatmap

**Screenshots or videos showing encountered issue:** 
https://osu.ppy.sh/ss/14689540/ddc6 - note the lack of 'disable video' check button

https://i.imgur.com/3vbbCBq.jpg - video file present in the beatmap folder (h264 codec)

**osu! version:**  - Latest Beta version
https://osu.ppy.sh/home/changelog/beta40/20200319

attatching the runtime log, but it doesnt seem to show anything from today
[runtime.log](https://github.com/ppy/osu/files/4406592/runtime.log)

**Comment by peppy** [comment]
This repository is for osu!lazer issues. You may be looking to report at osu-https://github.com/ppy/osu-stable-issues/issues instead, but I can also tell you that this is 99% something only affecting you and not something we will be looking to fix.
