### ISSUE TITLE
Hitsounds only in the left speaker specific map

### ISSUE THREAD

**Issue by Kert** [ppy/osu#8528]
**Describe the bug:** 
When playing https://osu.ppy.sh/beatmapsets/13931#osu/51692 map all hits are audible only through the left speaker. Doesn't happen on non-lazer osu!
**osu!lazer version:** 
2020.327.0 windows 7 x64

**Comment by peppy** [comment]
It looks like this beatmap uses `normal-hitnormal.wav` (panned far left) and `normal-hitnormal2.wav` (panned far right). If you are only hearing left speaker hitsounds, then we may be lacking support for `hitnormal2`.
