### ISSUE TITLE
Incorrect Autoplay results on the results screen

### ISSUE THREAD

**Issue by Moorad** [ppy/osu#8529]
**Describe the bug:** 
When I use the Autoplay mod on any map autoplay plays the map perfectly fine but when the results screen come up its all 0s and its a D rank. This happens regardless of what map I'm playing and what mods I have applied alongside autoplay. I'm sure it's not a big bug and can be solved easily.
 
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=6QasxsxXPmw

**osu!lazer version:** 
2020.327.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/4409674/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4409675/updater.log)
[database.log](https://github.com/ppy/osu/files/4409676/database.log)
[network.log](https://github.com/ppy/osu/files/4409677/network.log)
[performance.log](https://github.com/ppy/osu/files/4409678/performance.log)

**Comment by peppy** [comment]
already reported, already fixed.
