### ISSUE TITLE
Skinned mania notes don't match judgement area's size

### ISSUE THREAD

**Issue by peppy** [ppy/osu#8530]
Stable:

![image](https://user-images.githubusercontent.com/191335/78042735-663c8480-73ad-11ea-981c-0c934d546909.png)

master:

![image](https://user-images.githubusercontent.com/191335/78042913-aa2f8980-73ad-11ea-89bc-6635bb27aaa5.png)

Doesn't match the judgement area and visually looks stretched.

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/78043214-0692a900-73ae-11ea-9fb9-0763ec6ac5d8.png)

Also don't look to match each other

**Comment by smoogipoo** [comment]
Not sure what the OP in this issue is detailing. Are you talking about the 1px gap to the right? Stable has the same issue afaik.

**Comment by peppy** [comment]
No, talking about the height of the note being different to the judgement area's height.second screenshot shows where they differ from each other, too.

**Comment by peppy** [comment]
For better comparison:

![image](https://user-images.githubusercontent.com/191335/78100065-bdc70880-741e-11ea-8ac9-844fab4b7f41.png)

All three of these should match.

**Comment by smoogipoo** [comment]
I think it's close enough after the referencing PR:
![image](https://user-images.githubusercontent.com/1329837/78106445-5dd85e00-742e-11ea-832e-caac887441b4.png)

The height of the blue portion is ~18px (26 / 2 * 0.9 * 1.6026), the height of a note given a column width of 48 is ~15px (measured from the texture).

Stable has a similar issue, which is about the same size:
![image](https://user-images.githubusercontent.com/1329837/78106855-46e63b80-742f-11ea-95db-bcaf377ddccb.png)

**Comment by peppy** [comment]
The stable skin was meant such that the judgement should occur directly between the two (yellow) lines. Unfortunately that looks to have regressed at some point (and is currently wrong on stable) but the sizing does look correct for that.

Based on the screenshot in my OP it does match pixel perfect on stable:

![image](https://user-images.githubusercontent.com/191335/78107884-3e8f0000-7431-11ea-9f8b-3e6ee55246f8.png)

Note height fitting perfectly between the two yellow lines.

**Comment by peppy** [comment]
Latest master looks in line now:

![image](https://user-images.githubusercontent.com/191335/78108023-87df4f80-7431-11ea-87d0-32b15c6c172e.png)

**Comment by mcendu** [comment]
Still reproducible in [skins that contain variable column width](https://osu.ppy.sh/community/forums/topics/419180), for the "don't match each other" part.

**Comment by smoogipoo** [comment]
Reopening, for the minimum column size should be used in such cases, unless `WidthForNoteHeightScale` is provided by the skin.
