### ISSUE TITLE
osu!mania is not visible when a skin is used without osu!mania components

### ISSUE THREAD

**Issue by peppy** [ppy/osu#8532]
![image](https://user-images.githubusercontent.com/191335/78043455-53767f80-73ae-11ea-8f3e-3b94483f5c27.gif)

**Comment by smoogipoo** [comment]
This is the same issue as https://github.com/ppy/osu/issues/8019, fwiw.

**Comment by peppy** [comment]
It's a bit different though, since all other skinning implementations fall back to the default (lazer) implementation. At a bare minimum that should happen (I think this would be what people expect if they were using an osu! ruleset skin and went to play a different ruleset).
