### ISSUE TITLE
Hit explosions are too high in osu!mania

### ISSUE THREAD

**Issue by peppy** [ppy/osu#8533]
They look to be `BottomCentre` anchor when they should probably be centered.

![image](https://user-images.githubusercontent.com/191335/78043795-c2ec6f00-73ae-11ea-9dc7-f90be0f66f14.png)

**Comment by mcendu** [comment]
easy fix imo

**Comment by smoogipoo** [comment]
Yeah I missed a div-2 in the container's padding.
