### ISSUE TITLE
osu!mania holds / osu!taiko drum rolls do not stretch textures correctly

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8543]
Describe the bug:  long hold note appear dimmed near the tail note. beat map is https://osu.ppy.sh/beatmapsets/999735#mania/2091019 appears on 0:01 to 0:04

Screenshots or videos showing encountered issue:
![osu_2020-04-01_20-02-12](https://user-images.githubusercontent.com/41866328/78135322-490ec100-7454-11ea-899c-c5916fb35890.png)

osu!lazer version:  master commit 6d88ac2

Logs: not sure if needed but here (as im writing his issue, osu is still running)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4414955/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4414957/performance-gamethread.update.log)

[updater.log](https://github.com/ppy/osu/files/4414959/updater.log)
[database.log](https://github.com/ppy/osu/files/4414960/database.log)
[network.log](https://github.com/ppy/osu/files/4414961/network.log)
[performance.log](https://github.com/ppy/osu/files/4414962/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4414963/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/4414964/performance-gamethread.draw.log)
[runtime.log](https://github.com/ppy/osu/files/4414969/runtime.log)

**Comment by smoogipoo** [comment]
Please provide your skin.

**Comment by enoslayd** [comment]
both are the same skin just have different colors

[ok3.zip](https://github.com/ppy/osu/files/4414999/ok3.zip)
[ok.zip](https://github.com/ppy/osu/files/4415012/ok.zip)

also dimming appears on start of the hold note on classic skin
beatmap when converted to mania https://osu.ppy.sh/beatmapsets/140662#osu/351190
time stamp: 3:57
![osu_2020-04-01_20-25-10](https://user-images.githubusercontent.com/41866328/78136867-e79c2180-7456-11ea-9f78-a4c79d014362.png)

**Comment by enoslayd** [comment]
I also noticed this problem in taiko drumrolls

**Comment by peppy** [comment]
Yes, this is known. It's an issue with the blending being applied to stretched textures (at an atlas level). Will likely be fixed with shader changes in the future.

**Comment by enoslayd** [comment]
Closing since already resolved
