### ISSUE TITLE
Add the ability to transfer custom rullsets when updating the application

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8545]
When updating, they are not saved and are in the folder with the old patch

**Proposal designs of the feature:** 
I think that in the settings you can add a transfer button. Or enable automatic transfer

**Comment by Game4all** [comment]
One way to tackle this would be to create a Rulesets folder in the game data directory where the custom Rulesets assemblies are put and so aren't located at a path dependent of the game version. Or to have Rulesets databased like every other game content.

**Comment by HerendraTJ** [comment]
or the other selection is by overwriting the file when restarting the game.

**Comment by peppy** [comment]
Storing to the database may be the final goal, but for now I believe a `rulesets` folder is best (as we may be changing database engine in the near future and are avoiding making any large database changes).
