### ISSUE TITLE
Visual artifact on top left corner of some sprites

### ISSUE THREAD

**Issue by Kronos019** [ppy/osu#8547]
**Describe the bug:** 
small lines show up on the top left corner of the slider trail texture.
It also shows up on the top left corner of the osu cookie although a lot smaller and less noticeable.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/25570708/78163719-5e60fc80-740e-11ea-9f7d-f1d88bea5db5.png)

![image](https://user-images.githubusercontent.com/25570708/78164251-19899580-740f-11ea-89c1-1cf9cb093a7b.png)

its a lot more noticeable with the default skin
![image](https://user-images.githubusercontent.com/25570708/78164638-a6ccea00-740f-11ea-8d6f-d21341f58faa.png)

**osu!lazer version:** 
2020.402.0

**Comment by SevenChords** [comment]
can confirm, most noticable on the cursor itself, only while moving the cursor in my case, running osu lazer 2020.402.0 on macos catalina

**Comment by bdach** [comment]
Can confirm reproduction. Seems to have regressed at the framework bump at 4d8b6c4 (6d88ac2 looks fine).

If I were to guess it's going to be the atlasing change. Investigating.
