### ISSUE TITLE
Symlink Issue in Osu lazer

### ISSUE THREAD

**Issue by elh192773** [ppy/osu#8551]
I symlinked osu! to osu lazer using this command
`ln -s /applications/osu\!.app/Content/Resources/drive_c/osu\! ~/.osu;`

But after trying to import from stable again, it did not find the stable install once again. I cannot use the wineskin version of osu anymore as Catalina now exists.

**Comment by bdach** [comment]
Please recheck if the symlink is still there. If it is and it still fails, please provide logs.

**Comment by elh192773** [comment]
Alright here is proof it still exists

![image](https://user-images.githubusercontent.com/28768122/78345545-18a85d80-75e1-11ea-89ac-84df11c2c274.png)
Import Failing:

![image](https://user-images.githubusercontent.com/28768122/78345918-a5ebb200-75e1-11ea-8a22-50b4d0f8169c.png)

The strange thing is that normally a symlink links two folders but .osu as far as I can see is non existent. and currently the logs are found in 

<img width="252" alt="Screen Shot 2020-04-03 at 7 36 37 pm" src="https://user-images.githubusercontent.com/28768122/78346551-82753700-75e2-11ea-9a13-15ba2bcd11b7.png">


![image](https://user-images.githubusercontent.com/28768122/78346330-3fb35f00-75e2-11ea-8354-14521adaffe7.png)

Logs:

[database.log](https://github.com/ppy/osu/files/4426170/database.log)
[network.log](https://github.com/ppy/osu/files/4426171/network.log)
[performance.log](https://github.com/ppy/osu/files/4426172/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4426173/runtime.log)
