### ISSUE TITLE
Multi: Cannot leave a room

### ISSUE THREAD

**Issue by jennasisis** [ppy/osu#8552]
Basically what it says on the tin, when I join my maximum amount of rooms in the multiplayer lounge, I can't leave them until they expire. I think in regular osu! the leave button was the escape button, but here that just brings me back a menu.

**Comment by peppy** [comment]
Can you explain what error you're seeing, or maybe a video? There's no "max rooms" unless you are creating them.

**Comment by jennasisis** [comment]
Ah then I guess that's it then. When I've created a room, I can't delete it so I can make another one.

**Comment by peppy** [comment]
for now this is intentional
