### ISSUE TITLE
Legacy hold note lighting is not implemented

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8559]
Describe the bug: mania lightingn and lightingl is not applied form the skin. it uses the default lighting from lazer skin

Screenshots or videos showing encountered issue:
![image](https://user-images.githubusercontent.com/41866328/78216110-b15cb180-74eb-11ea-91e1-dd9e9a844308.png)

osu!lazer version: 2020.402.0

**Logs:**
not needed, i think

**Comment by mcendu** [comment]
lightingN part is fixed by #8556.

**Comment by enoslayd** [comment]
wrong screenshot
![osu_2020-04-02_14-10-17](https://user-images.githubusercontent.com/41866328/78216928-87a48a00-74ed-11ea-9a8a-dcfcbada726f.png)

**Comment by smoogipoo** [comment]
Repurposing this PR to relate to LightingL only, since N was implemented in the referenced PR above.
