### ISSUE TITLE
Replays use mods' default values

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#8569]
**Describe the bug:** For example, if you play with DoubleTime set to 1.01 speed, the replay will have its default speed value (1.50). The same happens with any other mod.

**osu!lazer version:** 2020.402.0

**Comment by peppy** [comment]
we currently have no mechanism for saving mod settings in the legacy replay format. the path forward here is *likely* going to be breaking the format altogether.

**Comment by tsunadegodaime** [comment]
Replays now work very strange. I tried to watch my replay played on Android with modifiers and it was a mess. Insteand of teleporting cursor (touch screen) it was moving like normal mouse or tablet and also replay did not cosinder any difficulty adjusting... I was playing with bigger circles and lowered diff. But replay system luanched map with stock settings, so there was lower accuracy, missing notes and so on....

**Comment by peppy** [comment]
Yes. Please read above.

**Comment by Joehuu** [comment]
This was fixed way back in https://github.com/ppy/osu/pull/12378.
