### ISSUE TITLE
osu!mania stage sprites are missing

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#8572]
**Describe the bug:** Looks like not all osu!mania skin elements are displayed properly, with the most important ones missing are mania-stage sprites. 

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/19843905/78252539-4ca55500-74f3-11ea-9a8e-459d09219d36.png)
lazer vs stable
![image](https://user-images.githubusercontent.com/19843905/78252700-87a78880-74f3-11ea-8db8-6fe17ceaa1b4.png)

![mania-stage-bottom](https://user-images.githubusercontent.com/19843905/78252844-c3425280-74f3-11ea-995f-3b1945e2ae20.png)

[Skin](http://puu.sh/FsdWT/f0cfbf750f.osk)

**osu!lazer version:** 2020.402.0

**Comment by TPGPL** [comment]
also the playfield seems to be rendered too high but that might be a seperate issue?

**Comment by bdach** [comment]
I think this is basically the same issue as #8558? Closing as such.

As for the vertical stage position, please do open a separate issue.
