### ISSUE TITLE
Sliderfollowcircle isn't scaled with Circle Size

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#8573]
**Describe the bug:** Sliderfollowcircle sprite has a constant size in lazer and isn't scaled with CS like in stable.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/19843905/78254688-904d8e00-74f6-11ea-800a-b46023338850.png)
lazer vs stable
![image](https://user-images.githubusercontent.com/19843905/78255111-2bdefe80-74f7-11ea-98a8-bcbe98adeeae.png)

[skin](http://puu.sh/Fselh/bd5be461b7.osk)

**osu!lazer version:** 2020.420.0

**Comment by peppy** [comment]
Looks fixed in latest release.
