### ISSUE TITLE
Bug with a loop from the cursor and sliders

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8575]
**Describe the bug:** 
After the last patch, some stripes appeared in the loop, which are displayed on all skins, especially on the standard one (but the lazer skin least of all displays them). I notice a certain pattern between the size of the track from the cursor and the number of these sticks. Near the sliders, they are displayed on the top left.
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=vOZspII-aBs
**osu!lazer version:** 
2020.402.0

**Comment by peppy** [comment]
already fixed
