### ISSUE TITLE
I can't title this

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#8578]
**Describe the bug:** 

There is too many bugs at the same time. 

1) When we cheese the spinner that "fake" the replay

2) We can cheese the spinner with the mouse (that's related to my issue about this) 

**Screenshots or videos showing encountered issue:** 

[Video](https://youtu.be/ANGAEvmLxig) 

**osu!lazer version:** 

Latest (2020.403.0) 

**Logs:**
 Android clan

**Comment by MTGPROD** [comment]
Interesting part at 1:55

**Comment by bdach** [comment]
I'm not really sure what you're trying to report here, so I think I'll just close this instead. All spinner weirdness will be tracked in the old issue.
