### ISSUE TITLE
GLSL skinning (feature request)

### ISSUE THREAD

**Issue by overlisted** [ppy/osu#8582]
**I don't know if you use OpenGL or Vulkan for graphics, if you do, here's my suggestion:**
Can you add custom fragment shaders support? You would draw all the GUI elements with specific shaders. The uniforms can be: 
```GLSL
vec2 onScreenPos;
vec2 posInElement;
vec4 elementEdgesDistance; 
float time; // not sure what measurement system can be used for time
``` 
and for font postprocessing, perhaps 
```GLSL
struct text {
  vec4 corners;
  sampler2D texture;
}

uniform text texts[/**<amount of texts in the element>*/];
```
and other specific uniforms for each element type. Also there can be a sampler2D called "triangles provider" for getting ready and monochrome triangles that was drawn _somewhere (I didn't search this in the code)_, and can be used in places like buttons in osu! settings and the logo.
I don't know if this will require much PC performance, but new skins will be very cool if you can add this feature.

**If you are not an OpenGL programmer, fragment shaders are scripts that can draw some effects on drawn shapes. Uniforms are variables that the scripts can use for adding more dynamic effects (based on current game state)**
This idea is very raw and needs some discussing, I think.

**Comment by overlisted** [comment]
This feature assumes that it'll fully replace the picture-based skinning and one skin can't use both features (GLSL and pictures)

**Comment by bdach** [comment]
As far as I'm aware the plan is to have a declarative markup language for the next version of skinning (see ppy/osu-framework#30 and ppy/osu-framework#3056). Whether custom shaders will play into that is very much up in the air, but there is a quite long way to go before we can even start considering that.

**Comment by overlisted** [comment]
> As far as I'm aware the plan is to have a declarative markup language for the next version of skinning (see [ppy/osu-framework#30](https://github.com/ppy/osu-framework/issues/30) and [ppy/osu-framework#3056](https://github.com/ppy/osu-framework/issues/3056)). Whether custom shaders will play into that is very much up in the air, but there is a quite long way to go before we can even start considering that.

For implementation processing just shaders is simpler than processing a declarative language

**Comment by bdach** [comment]
I'm not sure having skinning done entirely on shaders is viable either. The overhead of marshaling data from CPU to GPU and then back every update thread would probably kill performance.

**Comment by overlisted** [comment]
But in a _normal_ OpenGL application you do the same with default shaders

**Comment by bdach** [comment]
Not entirely true. Yes, the CPU->GPU run is currently there to upload OpenGL buffer data, but framework-side there are specific optimisations done to avoid overdraw (such as layout invalidation and front-to-back rendering) that *I think* in the case of what you're proposing would require the information (i.e. about drawable colour & bounds) be marshaled *back* to CPU from GPU, which is something that I'm pretty sure is not done currently and will be a performance hit. Well, unless that code is *also* migrated to shaders, but that sounds very unlikely.

**Comment by peppy** [comment]
we may add per element shader support in a distant future. too far forward to keep this issue open right now. let’s make the skinning system first.
