### ISSUE TITLE
HP drain does not properly account for break time

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#8585]
On https://osu.ppy.sh/beatmapsets/560330#osu/1202150, during + after the first break, the HP goes down to ~30% and on mania ~0%.
The map is HP 5 so it should only be going down to 70% minimum throughout the whole map.

**Comment by peppy** [comment]
I guess this is a completely different case from https://github.com/ppy/osu/issues/7607? It's actually draining throughout the break time here?

**Comment by smoogipoo** [comment]
I made a separate issue since that issue doesn't imply that there's a discrepancy between gameplay drain and the simulated drain. This issue does imply that though.

This is probably going to be fixed by the removal altogether, though, so I'll close it.

**Comment by peppy** [comment]
Not 100% sure of that.. As far as I know we're not draining during breaks already, but we *are* between break end and next hitobject. Is that already accounted for in simulation?

**Comment by smoogipoo** [comment]
The break here starts at ~31s, whereas the last object before it is at ~28s. We are draining during that time (since `!inBreakTime`), but we shouldn't be according to stable.

https://github.com/ppy/osu/pull/8542 also does not fix this.

I believe this is what's happening from the perspective of both systems:

```
Gameplay:

[H] - [H] - - - - - [B - - - - - B] - H
^^^^^^^^^^^^^^^^^^^^^             ^^^^^^

Simulation:

[H] - [H] - - - - - [B - - - - - B] - H
^^^^^^^^^                         ^^^^^^

^ - Drain time
[H] - Object
[B-B] - Break time
```
