### ISSUE TITLE
PP Counter In Completion Screen Not Working

### ISSUE THREAD

**Issue by unassignedxd** [ppy/osu#8587]
**Describe the bug:** 
After completing a map, the OSU PP counter does not display.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/45195284/78322054-e3413880-752a-11ea-97b4-56676d7ae5ae.png)

**osu!lazer version:** 2020.403.0

I dig some digging in the source code to try to find a solution myself, but I do not have enough cs experience to actually submit anything. It'd be nice if this score always displayed, even if the score wasn't submitted to the servers or if the play was unranked.

**Comment by smoogipoo** [comment]
It's not implemented yet. Could be nice to be displayed via running a PP processor on the score for the time being.

**Comment by unassignedxd** [comment]
@smoogipoo I see. I was trying to just implement it myself as it seems all the PP math is still there from stable, but I'm sure there will probably a different system implemented anyways. I tried digging around the ScoreProcessor and add it myself for my own use, but I have no idea the actual framework behind everything to get it work.

**Comment by peppy** [comment]
osu-stable did not have and pp implementation. there's examples of usage in [osu-tools](https://github.com/ppy/osu-tools/tree/master/PerformanceCalculator).

**Comment by smoogipoo** [comment]
It'll be something like `Ruleset.CreatePerformanceCalculator(beatmap, score)`.

**Comment by unassignedxd** [comment]
@smoogipoo I did see this method, but I do not see a way to get an instance of Ruleset or to a WorkingBeatmap. I'm able to set the score.PP, and it does display in the results screen, its just I have no idea how this PerformanceCalculator stuff works. Thanks, though.

@peppy Thanks, I'll take a look at this.

**Comment by HerendraTJ** [comment]
The PP system in osu!lazer still not implemented since this still in the early dev.

**Comment by smoogipoo** [comment]
Please refrain from commenting if you haven't made an attempt to read the code and/or understand the comments previously made. osu!lazer already has complete pp implementations.
