### ISSUE TITLE
Modify BPM Based On Double Time / Half Time Mod

### ISSUE THREAD

**Issue by unassignedxd** [ppy/osu#8588]
**Describe the new feature:** 
This is a feature in osu! stable. Once DT/HT is active, the BPM and other difficulty stats are changed to reflect the changes made with DT/HT. This would make using DT/HT customization a lot easier to see the exact BPM, because ATM you must do the math yourself.

**Proposal designs of the feature:** 
Have the original BPM listed, and the new BPM due to DT/HT changes.

**Comment by Joehuu** [comment]
Already implemented in https://github.com/ppy/osu/pull/11900.
