### ISSUE TITLE
Using Keyboard in Android

### ISSUE THREAD

**Issue by matthewanderson0607** [ppy/osu#8591]
**Describe the bug:** 
I can't use my keyboard to register an account or sign in help me
I tried to tap the keyboard but the game didn't respond

**Comment by MTGPROD** [comment]
Do you have a Samsung phone with the Samsung Keyboard ? Because i have the same problem with a Galaxy Note 9

**Comment by smoogipoo** [comment]
Duplicate of https://github.com/ppy/osu/issues/8264

**Comment by matthewanderson0607** [comment]
> Do you have a Samsung phone with the Samsung Keyboard ? Because i have the same problem with a Galaxy Note 9. 
> 
> And if you really want to use your keyboard on osu! NOW, you can install the SwiftKey keyboard. it is working.

Thanks for telling me, i'll try it now
