### ISSUE TITLE
lightingn is applied on hold notes

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8593]
Describe the bug: lightingn is applied on hold notes

Screenshots or videos showing encountered issue: 
![osu_2020-04-03_15-16-40-3](https://user-images.githubusercontent.com/41866328/78334529-7bd4c880-75be-11ea-8abc-7307f2bee1fb.png)

Skin:
[my skin.zip](https://github.com/ppy/osu/files/4425570/my.skin.zip)

osu!lazer version: 2020.403.0

Logs:
[performance.log](https://github.com/ppy/osu/files/4425597/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4425598/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/4425599/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4425600/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4425601/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/4425602/runtime.log)
[database.log](https://github.com/ppy/osu/files/4425603/database.log)

**Comment by smoogipoo** [comment]
This is intended due to the way LN's work for now. May change in the future but it depends on judgements changing, not skinning.
