### ISSUE TITLE
missed hold note doesnt gray out

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8594]
Describe the bug: in stable, hold notes (when released early, missed or not hold), it grays out (idk if same applies to regular notes. 
![screenshot051](https://user-images.githubusercontent.com/41866328/78336611-3adeb300-75c2-11ea-99d0-7c88105c56c9.png)

in lazer however it doesnt gray out
when not hold:
![osu_2020-04-03_15-48-10](https://user-images.githubusercontent.com/41866328/78336840-a0cb3a80-75c2-11ea-8837-b964e8ee4b1f.png)

when holded, then released early then re hold:
![osu_2020-04-03_15-40-21](https://user-images.githubusercontent.com/41866328/78336941-c35d5380-75c2-11ea-9e49-76318af073c8.png)

Skin:
https://github.com/ppy/osu/files/4425570/my.skin.zip

 

osu!lazer version: 2020.403.0

**Logs:**
not needed, i think

**Comment by enoslayd** [comment]
after some experiment, stable does gray out regular notes as well as hold notes if pressed near the judgement line (scroll speed set to 4, fixed) and it gives 100 or 50. if missed, regular notes just falls down while maintaining color while hold notes turns gray only after the head missed the judgement line and it gives miss and if holded and released in time, the tail will give appropriate score

**Comment by igontusuwu** [comment]
i think the strength of gray-out could be customized by skin
