### ISSUE TITLE
skin hitsounds overlap beatmap hitsounds

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8595]
**Describe the bug: skin hitsounds overlap beatmap the video begins with me trying out this beatmap ( https://osu.ppy.sh/beatmapsets/63089#mania/193128 ) in stable, as you can see in the video, the skin hitsounds wasnt present, only the beatmap ones. then i moved to lazer and try the same map, at the beginning i pressed the keys then the problem appear. i tried another beatmap near the end of the vid and it doesnt have the problem

Screenshots or videos showing encountered issue:
Video: (sorry for laggy video and loud audio cause my laptop is such a potato) just remove the zip extension
[2020-04-03 16-27-29.mkv.zip](https://github.com/ppy/osu/files/4425879/2020-04-03.16-27-29.mkv.zip)

stable settings:
![screenshot052](https://user-images.githubusercontent.com/41866328/78341129-c1e35980-75c9-11ea-8f83-8eca22e16d0f.png)

lazer settings:
![osu_2020-04-03_16-32-46](https://user-images.githubusercontent.com/41866328/78341186-daec0a80-75c9-11ea-80aa-eb195ed31f7d.png)

osu!lazer version: commit 4e061ce

Logs: 
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4425919/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/4425920/runtime.log)
[database.log](https://github.com/ppy/osu/files/4425922/database.log)
[performance.log](https://github.com/ppy/osu/files/4425923/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4425924/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/4425925/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4425917/performance-gamethread.input.log)

**Comment by enoslayd** [comment]
skin: https://github.com/ppy/osu/files/4425570/my.skin.zip

**Comment by enoslayd** [comment]
Should have mania tag as i observed this only in mania

**Comment by Coppertine** [comment]
I think the title should be "Legacy Skin Hit Sound Normals overlap with Mania Key Sample
"

**Comment by enoslayd** [comment]
Idk if it is the normals though
