### ISSUE TITLE
Star Rating is not centered in result screen when there are no mods

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#8599]
**Screenshots or videos showing encountered issue:** 
![container](https://user-images.githubusercontent.com/43073074/78350425-7f0f8a80-75a5-11ea-8c81-c703fdc9b938.png)
![star rating](https://user-images.githubusercontent.com/43073074/78350427-8040b780-75a5-11ea-9006-65607cf67ad2.png)

(Probably low priority)

**Comment by Joehuu** [comment]
Not yet resolved.
