### ISSUE TITLE
Videos are not centered

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#8600]
![Screenshot_1](https://user-images.githubusercontent.com/22874522/78377717-a3388f00-75d8-11ea-9435-9317c41dc82c.png)
![Screenshot_2](https://user-images.githubusercontent.com/22874522/78380975-5d31fa00-75dd-11ea-9124-8a3e9f3b2f04.png)

**Comment by treier57lol** [comment]
Videos are also not in sync with the music anymore. Bug occurs on 2020.404.0.

**Comment by treier57lol** [comment]
Also the results screen rank zone color things are missing, might be related to this.
![osu_2020-04-03_20-23-32](https://user-images.githubusercontent.com/33978534/78388101-1ba74c00-75e9-11ea-9bbf-907d9e6f9776.jpg)

**Comment by smoogipoo** [comment]
It is not related, please make a separate issue.

**Comment by peppy** [comment]
"videos not in sync with music" could you please provide a reference beatmap @treier57lol

**Comment by treier57lol** [comment]
https://youtu.be/tyBW-_g1yaw
Beatmap tested is https://osu.ppy.sh/beatmapsets/295480

**Comment by peppy** [comment]
I'm working on a solution for this (sharing layout code with `Animation` seems the correct way forward).

**Comment by treier57lol** [comment]
The issue isn't fixed, videos are still misalinged and desynced with the audio, but at least the intro sequence is fixed.

**Comment by treier57lol** [comment]
I built from source.

**Comment by LittleEndu** [comment]
That doesn't answer my question... If you were running the source correctly you would know what commit you are on and whether that includes the framework bump.

**Comment by LittleEndu** [comment]
Can confirm. On e610b5e5b7931b160291d20b99934db48aeb7ba8 videos don't appear centered. 
![osu_2020-04-06_20-18-54](https://user-images.githubusercontent.com/11320483/78586290-ea768800-7843-11ea-8cfc-59f0ce3f8fd7.png)

**Comment by treier57lol** [comment]
I cloned from source around 10 minutes ago when I commented, latest commit is e610b5e5b7931b160291d20b99934db48aeb7ba8

**Comment by treier57lol** [comment]
Issue is now fixed in 2020.408.0.
