### ISSUE TITLE
Weird audio hitches/spikes during gameplay

### ISSUE THREAD

**Issue by ObiDriftKenobi** [ppy/osu#8601]
**Describe the bug:** 
The audio makes weird hitches in gameplay. I'm not sure if it's caused by hardware or software, but I managed to record this, so it's probably caused by osu! itself.

**Screenshots or videos showing encountered issue:** 
I uploaded a short video about this on YouTube: https://www.youtube.com/watch?v=k7f11XqaTgU

**osu!lazer version:** 
2020.404.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/4428944/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4428945/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4428946/updater.log)
[database.log](https://github.com/ppy/osu/files/4428947/database.log)
[network.log](https://github.com/ppy/osu/files/4428948/network.log)

**Comment by bdach** [comment]
Cannot reproduce this myself. More detail would be helpful but I'm not even sure what details could help here.

**Comment by Pythonimous** [comment]
Appears identical to #8416 I've reported about 2 weeks ago.

**Comment by ObiDriftKenobi** [comment]
#8416 is identical, no problems on multi-thread. Closing

**Comment by Pythonimous** [comment]
Could you please include your logs, etc. into that thread, to possibly help investigate the issue further?
