### ISSUE TITLE
Animated judgements are missing

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8604]
**Describe the bug:** 
All expected judgements (100s and 50s) are missing from my skin ([LittleEndu/osuSkin](https://github.com/LittleEndu/osuSkin/tree/master/u200B)). This probably has something to do with animations, but I wasn't able to recreate this with any other skin I have :/

**osu!lazer version:** 
2020.404.0

**Comment by peppy** [comment]
I believe this will just be setting `startAtCurrentTime` correctly
