### ISSUE TITLE
Squirrel delta patching failure on start

### ISSUE THREAD

**Issue by xdTAGCLAN** [ppy/osu#8615]
When i open Osu!lazer nothing happens

https://youtu.be/325Z7IXDEzc

Happens on all versions

[runtime.log](https://github.com/ppy/osu/files/4431242/runtime.log)
[performance.log](https://github.com/ppy/osu/files/4431243/performance.log)

**Comment by bdach** [comment]
This is a squirrel patching failure:
```
8/12/2019 1:46:49 PM: ERROR: delta patching failed!
8/12/2019 1:46:49 PM: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
8/12/2019 1:46:49 PM: at DeltaCompressionDotNet.MsDelta.MsDeltaCompression.ApplyDelta(String deltaFilePath, String oldFilePath, String newFilePath)
8/12/2019 1:46:49 PM: at Squirrel.DeltaPackageBuilder.applyDiffToFile(String deltaPath, String relativeFilePath, String workingDirectory)
```
Please try reinstalling from a release and seeing if this persists.

**Comment by TheWildTree** [comment]
Before you do the above: could you please take a look at the content of your newest `%localappdata%\osulazer\app-2020.xxx.x` folder? 

I've had the same issue in the past and in my case most files there were missing compared to a working lazer installation - I'm curious if it's the same thing here.

**Comment by xdTAGCLAN** [comment]
Here is that folder:
http://www.mediafire.com/file/ar8mvabgvyhdl2h/app-2020.404.0.zip/file

**Comment by xdTAGCLAN** [comment]
Where do i download the releases?
I can't open the RELEASES file

**Comment by bdach** [comment]
[see README](https://github.com/ppy/osu#running-osu)

**Comment by xdTAGCLAN** [comment]
What do you mean? What do i download?

**Comment by TheWildTree** [comment]
In the readme, under the `Running osu!` section there's the `Latest build` part. In the table underneath click the OS you're using to download the installer for the newest release.

**Comment by xdTAGCLAN** [comment]
also doesnt work still doesnt open

**Comment by TheWildTree** [comment]
Uninstall your current lazer installation and then try installing the new one.

**Comment by xdTAGCLAN** [comment]
already did that
still didnt work

**Comment by xdTAGCLAN** [comment]
any thing else i can do??

**Comment by bdach** [comment]
If nuking the entire `%localappdata%/osulazer` folder altogether doesn't fix it then there's no info to go on here to attempt diagnosing this. It might be a permission issue on your system.

**Comment by xdTAGCLAN** [comment]
ok. so i deleted the osulazer folder entirely and reinstalled.
and it doesnt work...

**Comment by bdach** [comment]
As I said at this point it's very difficult to say what the particular problem here would be. If it was my machine I'd run [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to try and see which file squirrel is missing, but it's not an exactly beginner-friendly tool to use.

**Comment by xdTAGCLAN** [comment]
ill try

**Comment by xdTAGCLAN** [comment]
do you have like a tutorial maybe?

**Comment by smoogipoo** [comment]
Delta patch failures are completely intentional - they happen when the user is more than one version behind, and they trigger a full re-download rather than a patch. A notification is shown when this happens, as you can see in the runtime.log.

This is a case where the process is likely crashing before it even hits the logger in the first place. Could you try opening event viewer (`WinKey+R` -> `eventvwr` -> `Windows Logs` -> `Application`) and seeing if any errors pop up when you try to start?

**Comment by xdTAGCLAN** [comment]
Nope theres nothing only 'information' boxes. But those were already there before launching osu!lazer

**Comment by smoogipoo** [comment]
Not sure, you're going to have to use Process Monitor as previously mentioned then and see if you can collect more data on it.

**Comment by xdTAGCLAN** [comment]
i dont know how to use that

**Comment by peppy** [comment]
Please check back in a few months and try lazer again. It may work for you then. For now we can't deal with this level of support.
