### ISSUE TITLE
taiko, mania, and catch don't work on iOS

### ISSUE THREAD

**Issue by cainy-a** [ppy/osu#8627]
**Describe the bug:** 
- in osu!taiko on iOS, only the center drum can be hit.
- in osu!catch, it is impossible to move the person at the bottom,
- and in osu!mania, you can't press any of the buttons to hit the notes.

**Screenshots or videos showing encountered issue:** 
Videos in Zip (github wouldn't let me upload video files so i zipped them):
[Osu_iOS_Bug_Videos.zip](https://github.com/ppy/osu/files/4433792/Osu_iOS_Bug_Videos.zip)

**osu!lazer version:** 
`Version 0.1 (2020.404.0)` (According to TestFlight)
**Logs:**

Issue is on iOS, i will attach logs if anyone tells me how to get them

**Comment by peppy** [comment]
We are tracking this in many places. Please read the testflight info carefully.
