### ISSUE TITLE
Skin for each ruleset

### ISSUE THREAD

**Issue by SuperFat-Fat** [ppy/osu#8628]
Hi !
I think this could be a really helpul feature !
By "Each ruleset", I mean that instead of one global skin, there could be a skin only used for one ruleset !
It could be helpul because I'm playing classic and Mania, and switching so often is very annoying...

**Comment by LittleEndu** [comment]
Duplicate of #6124

**Comment by SuperFat-Fat** [comment]
Oh sorry !
