### ISSUE TITLE
Map result screen incomplete

### ISSUE THREAD

**Issue by Pythonimous** [ppy/osu#8629]
**Describe the bug:** 
The result screen scale for every map might have broken. Whereas earlier there were percentages and a complete scale, now there appear to be none, and only ranks up to that you have reached.

**Screenshots or videos showing encountered issue:** 
![Screenshot from 2020-04-05 19-24-45](https://user-images.githubusercontent.com/24483005/78504425-de23f980-7775-11ea-8abc-21751f46ff36.png)
(issue with non-full screen unrelated, reported earlier, was closed, scale is still seen clearly)

**osu!lazer version:** 
2020.404.0

**Comment by bdach** [comment]
Bisects to framework bump at f59479f. Probably an accidental casualty of the fix at ppy/osu-framework#3423?

**Comment by treier57lol** [comment]
Framework bump 00f390c850e31f86c3fbe5df759524bfb9e4bb5e fixes this.

**Comment by bdach** [comment]
Yes, ppy/osu-framework#3428 was a targeted temporary fix for this. Closing for now, remaining blending issues & necessary cleanups might as well be tracked framework-side.
