### ISSUE TITLE
Reduce Dropped Frames like in Stable

### ISSUE THREAD

**Issue by cainy-a** [ppy/osu#8633]
**Describe the new feature:** 
I would like to have the "Reduce dropped frames" option from stable in lazer.
I was finding the stutter and lag unbearable in taiko mode on both lazer _and_ on stable, but stable's reduce dropped frames option fixed it.
**Proposal designs of the feature:** 
Eliminates stutter problems, just like in stable.

**Comment by bdach** [comment]
Performance is a constant work in progress. Hopefully with enough optimisation work you won't even need the option.
