### ISSUE TITLE
One developer removed me from testing on iOS, and now I can't test osu!lazer in iOS at the future, even if I reusing the testflight invite link

### ISSUE THREAD

**Issue by Quochieu0211** [ppy/osu#8636]
When I returns to the TestFlight app, I've been surprised that osu!lazer app is now "Tester Removed", and when I trying to open it to find the good reason it says "One developer has removed you from testing this app." And when I stop testing osu!lazer and retesting using the testflight link again, I click Done and now osu!lazer isn't showing on the testing apps list there anymore

**Comment by enoslayd** [comment]
Peppy recently purged some testers, maybe youre one of them? And maybe the slots are full? I cant say for sure as i dont have any apple devices

**Comment by peppy** [comment]
Please use the new link from the readme and register again.
