### ISSUE TITLE
Osu! Lazer Background Video not aligned with the screen

### ISSUE THREAD

**Issue by lendell2000** [ppy/osu#8637]
**Background videos are not aligned in the screen
[performance.log](https://github.com/ppy/osu/files/4436673/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4436675/runtime.log)

** 

**Screenshots or videos showing encountered issue:
![image](https://user-images.githubusercontent.com/63226726/78534248-ae7bfc80-781c-11ea-9daf-89dbb718b49c.png)
** 

**osu!lazer version:** 

**Logs:**

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/8637

**Comment by Coppertine** [comment]
actual dupe of: #8600
