### ISSUE TITLE
osu!lazer tournament client videos doesn't fill the entire stream area

### ISSUE THREAD

**Issue by nekoraw** [ppy/osu#8645]
**Describe the bug:** 
after framework update to 2020.406, the osu!lazer tournament client videos doesn't fill the entire stream area
**Screenshots or videos showing encountered issue:** 
[after 00f390c](https://nekoraw.s-ul.eu/1G6nV3Gz)
[with 17ed2a4](https://nekoraw.s-ul.eu/NEBGQsPF)
**osu!lazer version:** 
00f390c has the problem, but 17ed2a4 doesn't. also tried with the last commit, but it has the same problem.
**Logs:**
[00f390c](https://drive.google.com/uc?id=1A5yzjBboVtsOpUN_0Glw9b07ayHUrW2E)
[17ed2a4](https://drive.google.com/uc?id=19TYKIf5rFuAD79vl4ju_3UxlIJgN89Mw)

**Comment by nekoraw** [comment]
im using a 1366x768 video as background.

**Comment by peppy** [comment]
If not too large, could you please attach the video you're testing (and which scene it's in)

**Comment by nekoraw** [comment]
it's a 117mb [video](https://drive.google.com/uc?id=1FurM32NXt1LbLE8EsQTZuISaYX9LBmHM). [here](https://nekoraw.s-ul.eu/TXtFK6vl) are the video properties
it happens on all scenes
[schedule](https://nekoraw.s-ul.eu/n1TddgMy)
[gameplay](https://nekoraw.s-ul.eu/I1yL4vBo)
[showcase](https://nekoraw.s-ul.eu/ucMQVo7t)
used the same video on all of them though

**Comment by peppy** [comment]
Thanks so much for testing on master, it's very helpful to us.

**Comment by timrowland-wq** [comment]
Is this fixed by [#3435](https://github.com/ppy/osu-framework/pull/3435)?

**Comment by nekoraw** [comment]
[works fine now](https://nekoraw.s-ul.eu/jX3nM5n2)
