### ISSUE TITLE
Fail animation should be adjustable per ruleset

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#8647]
For now fail animation handled in `Player` and there's no way to override it elsewhere. Probably we want to create it in the `Playfield` and override if needed.

**Comment by peppy** [comment]
https://github.com/ppy/osu/pull/5085 relevant

**Comment by peppy** [comment]
Maybe duplicate of https://github.com/ppy/osu/issues/4956.

**Comment by EVAST9919** [comment]
Yeah, last pr is what I'm looking for.
Closing as duplicate of https://github.com/ppy/osu/pull/5085 since mentioned pr should close it anyway.
