### ISSUE TITLE
game interface broken

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8654]
Describe the bug: feel free to close if not relevant. i have experienced this problem for almost a year (sorry for not reporting it. the first vid show lazer when started in fullscreen. but if started in borderless or windowed then fullscreened, game is normal (second vid)

before, the glitch doesnt affect the fps counter or the mouse cursor but recently (this year, i think) even the mentioned  elements became glitched too. i tried turning off the bypass front to back but it partially fixed the problem (screenshot)

Screenshots or videos showing encountered issue: (change remove zip extenstion)
![osu_2020-04-07_15-19-38](https://user-images.githubusercontent.com/41866328/78641369-ba7ec180-78e3-11ea-9d42-9fe5b40f4049.png)
first vid: https://drive.google.com/file/d/1ReCPQ_WbM4kFnjPBa0QqWLVNV4Vz3fXJ/view?usp=sharing
second vid: https://drive.google.com/file/d/1QxvNpqCKOmC3Ou_NFEkhFhsKYULpkIIO/view?usp=sharing

osu!lazer version: master (but also happens on release versions)

Specs:
intel pentium p6200
6GB ram
1st gen intel HD Graphics (only supports opengl 2.1)

Logs:
[database.log](https://github.com/ppy/osu/files/4442577/database.log) 
[performance.log](https://github.com/ppy/osu/files/4442578/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4442576/runtime.log)

**Comment by enoslayd** [comment]
BTW, it doesnt happen on linux (only windows) and i dont receive any driver updates anymore

**Comment by smoogipoo** [comment]
Does it help if you enable the "Bypass front-to-back render pass" option at the bottom of settings?

**Comment by enoslayd** [comment]
It partially fixed it ( like removing the black part of osu cookie seen in vid 1) but the gameplay elements is still broken (taiko don and katsu's, column bar line in mania)

**Comment by smoogipoo** [comment]
Interesting, you're reaching some GPU limits which we're not going to be able to solve in the next little while. You're going to wait until we add compatibility for older hardware.

But until then, can you provide your exact GPU specs via a `dxdiag`?

**Comment by enoslayd** [comment]
Ill post it later together with the vid showing some differences when turning on/off the bypass

**Comment by enoslayd** [comment]
Vid 3 (using 2020.404.0): https://drive.google.com/file/d/1Rvsjd5uzhef6ggGcEXRG_GyYe-ua3yxs/view?usp=sharing
more logs and dxdiag
[runtime.log](https://github.com/ppy/osu/files/4442823/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4442824/updater.log)
[database.log](https://github.com/ppy/osu/files/4442825/database.log)
[DxDiag.txt](https://github.com/ppy/osu/files/4442826/DxDiag.txt)
[network.log](https://github.com/ppy/osu/files/4442827/network.log)
[performance.log](https://github.com/ppy/osu/files/4442829/performance.log)

>You're going to have to wait until we add compatibility for older hardware.

Thats ok cause i can workaround it for a while. also thank you for noticing the problem, i can wait

**Comment by peppy** [comment]
is this worth keeping open?

**Comment by smoogipoo** [comment]
Nope, let's close for now.
