### ISSUE TITLE
Background video too large

### ISSUE THREAD

**Issue by HotSour-Sushi** [ppy/osu#8655]
**Describe the bug:** The background video goes way past the screen and is huge.

**Screenshots or videos showing encountered issue:** 
![Capture](https://user-images.githubusercontent.com/63284020/78644193-5966d780-786a-11ea-9fce-0452454f161a.PNG)

![wefwefwfure](https://user-images.githubusercontent.com/63284020/78644198-5bc93180-786a-11ea-8fef-01fc3cee62b3.PNG)

![yjryjryje](https://user-images.githubusercontent.com/63284020/78644208-5ec42200-786a-11ea-82ad-3c962727a475.PNG)

**osu!lazer version:**  2020.404.0

**Logs:**

**Comment by peppy** [comment]
Fixed in next release, see https://github.com/ppy/osu/issues/8637.
