### ISSUE TITLE
Cannot type on osu lazer android

### ISSUE THREAD

**Issue by XIDigbyKun** [ppy/osu#8659]
hey guys i got issues
i cannot type on login ui and search
i used android 10 (Q) 

[Video](https://youtu.be/7G7Bm92vqHg) 

osu!lazer android 2020.404.0

**Logs:**
no logs

**Comment by peppy** [comment]
Please switch keyboards for now.https://github.com/ppy/osu/issues/8264

**Comment by XIDigbyKun** [comment]
Hmm weird keyboard samsung
Thank pep
