### ISSUE TITLE
AFK error

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8662]
**Describe the bug:** 
The error occurs just like that when the application is in the background. Nothing happens with the application. The error just appears on its own. Something is happening in the logs. Appearance time and intervals are completely random
**osu!lazer version:** 
2020.404.0
**Logs:**
[performance.log](https://github.com/ppy/osu/files/4443789/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4443790/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4443791/updater.log)
[database.log](https://github.com/ppy/osu/files/4443792/database.log)
[network.log](https://github.com/ppy/osu/files/4443793/network.log)

**Comment by bdach** [comment]
The only error there is evidence of in the logs attached has to do with network access (`Этот хост неизвестен` - which per google translate means `This host is unknown`), making this an issue that is likely to be on your side.

Closing due to the above reason.
