### ISSUE TITLE
Editor Timeline causes severe performance issues when redrawn.

### ISSUE THREAD

**Issue by KoziLord** [ppy/osu#8663]
**Describe the bug:** 
The Update thread usage spikes whenever the Timeline in the Editor needs to be redrawn.
There are two causes to this:
- The beat snap divisor ticks, the more of them there are the worse this gets meaning this scales with both the song length and the divisor setting. ([video](https://drive.google.com/open?id=16Qb0yazmfDJX4KOMKuL4pNIQJz4pc0Rk))
- The waveform rendering which causes lots of GC collections. ([video](https://drive.google.com/open?id=19rSs_UiBQsUTRsiKDR49zYfviiOL6QtV))
  
**osu!lazer version:**
2020.404.0 

**Logs:**
[network.log](https://github.com/ppy/osu/files/4444024/network.log)
[performance.log](https://github.com/ppy/osu/files/4444025/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4444026/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4444027/updater.log)

**Comment by bdach** [comment]
This was acknowledged at the point of initial implementation and will be improved on as the editor enters a more stable state functionality-wise.

**Comment by smoogipoo** [comment]
Issue (1) is likely covered by https://github.com/ppy/osu/issues/6136, or if any other scrolling area optimisations are added before that happens. It's a well known issue that we don't need tracked at this point.

Issue (2) addressed by the framework PR.
