### ISSUE TITLE
Follow Points Visible on Skin With Invisible Follow Points

### ISSUE THREAD

**Issue by InfinityGhost** [ppy/osu#8664]
**Describe the bug:** 
Follow points are visible in a legacy skin with invisible follow points. `followpoint.png` is a 1x1px image with 0 alpha. This didn't occur in previous builds which is why I assume this is a bug. 
**Screenshots or videos showing encountered issue:** 
https://streamable.com/fznvfr
**osu!lazer version:** 
local debug development build at 2e8e451c176317d4ee09868d839c591b7999fad4
**Logs:**

[database.log](https://github.com/ppy/osu/files/4446248/database.log)
[network.log](https://github.com/ppy/osu/files/4446249/network.log)
[performance.log](https://github.com/ppy/osu/files/4446250/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4446251/runtime.log)

**Comment by LittleEndu** [comment]
Please include the skin in question.

**Comment by InfinityGhost** [comment]
[InfinityGhost.zip](https://github.com/ppy/osu/files/4446624/InfinityGhost.zip)

**Comment by bdach** [comment]
Closing as the above linked issue encompasses this one in scope.
