### ISSUE TITLE
Skin reverse arrow and follow points not importing

### ISSUE THREAD

**Issue by Kronos019** [ppy/osu#8665]
**Describe the bug:** 
Reverse arrow and follow point skill elements are not being imported from skins and are falling back to lazer default versions.
Regression from 2020.404.0

Skin used:
[https://archive.btmc.live/noel_v6/Komori%20-%20MC%20NOEL%20(VI).osk](url)

**Screenshots or videos showing encountered issue:** 

Screenshot from 2020.408.0
![image](https://user-images.githubusercontent.com/25570708/78711211-3c6aec80-78dc-11ea-8407-3aa322e9ebfb.png)

Screenshot from 2020.404.0
![image](https://user-images.githubusercontent.com/25570708/78711497-ad120900-78dc-11ea-8ddf-02f0cc9d0ede.png)

**osu!lazer version:** 
2020.408.0

**Comment by InfinityGhost** [comment]
Same issue as I described in #8664

**Comment by LittleEndu** [comment]
Add approach circles to the list.

**Comment by bdach** [comment]
I will close the other issue and leave this open. Please do not open further issues to list further elements.
