### ISSUE TITLE
Some wide playfield osu!mania skin elements are invisible

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#8667]
Some of the elements of wide playfield skins are completely invisible. This is different for all skins and makes mania completely unplayable for some skins, whereas on other skins it's not that big of a deal. 
Skins: 1 https://www44.zippyshare.com/v/LH5OkEmn/file.html (all of the notes are invisible)
2 https://www44.zippyshare.com/v/xvt7MFHC/file.html (only the 4th hold notes don't appear correctly)
Video: https://youtu.be/rg2vMRj9Zwo
Version: 2020.408.0 (latest)
Logs: none

**Comment by LittleEndu** [comment]
Please replace "latest" with the actual version number your lazer install is at.

**Comment by Joppe27** [comment]
> Please replace "latest" with the actual version number your lazer install is at.

Sorry, I changed it now

**Comment by smoogipoo** [comment]
Issue (2) is https://github.com/ppy/osu/issues/8019 - there is no `mania-note4L`.
