### ISSUE TITLE
Osu!tournament ladder onDrag bug.

### ISSUE THREAD

**Issue by TheEZIC** [ppy/osu#8670]
**Describe the bug:** 
In the "bracket editor"/"bracket" osu!lazer tournament menu matches disappear if i try to drag over the field. I try to change max_scale const in LadderDragContainer.cs and got the following result: the further I scroll the camera, the greater distance I can drag.
**osu!lazer version:**  
I try to test this on 402 and 404 versions of osu!lazer

**Comment by bdach** [comment]
[Video of the issue I think the report is trying to describe.](https://streamable.com/dz8srr)

Happens whenever the `LadderDragContainer` is scrolled just outside of window bounds. I don't imagine this being in any way a severe shortcoming of the tournament client, however.

**Comment by TheEZIC** [comment]
But if I scale too close, a window, where everything is displayed normally also get become less. I can`t normally drag on low zoom, without matches disappears.
