### ISSUE TITLE
Triangles intro video plays out of time

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#8678]
It finishes playing too soon. Likely a regression from the recent `Video` changes, something to do with `startAtCurrentTime`.

The offset was recently removed (https://github.com/ppy/osu/commit/51db361c32c2c1a3a97599ff5ea47490d1e8369c#diff-d3a2a9931378d9ae9aec9b784666d6fdL276) which may be contributing to the issue.

**Comment by bdach** [comment]
From what I saw `PlaybackPosition` will instantly get a value of 1000 leading to this problem. Setting it manually to 0 at the start of the absolute sequence seems to help but I'm unconvinced it's completely correct.

**Comment by smoogipoo** [comment]
`startAtCurrentTime = true` should fix this.

**Comment by peppy** [comment]
Closed via... https://github.com/ppy/osu/commit/61d8cfd2241453074c3d5067b18b7bda13afccbd
