### ISSUE TITLE
osu!campaign

### ISSUE THREAD

**Issue by Trislot** [ppy/osu#8684]
First, I don't know if something similar as already been posted but I'm doing it anyway.

So...osu!campaign , or something a bit similar in progress named osu!dan. The idea is to add a "solo" part into osu!lazer such as a campaign, a place where you need to do certain things in certain domain (more explanation later) to lvl up and unlock new things.

For example, imagine osu skillset such as aim, accuracy, reading, stream, etc.... For each of those categories, a certain number of maps that you need to finish to unlock the next lvl. Need to end every categories before getting to the next lvl.

In my opinion that would be a nice way to force new players (and actual player too) to discover different part of the game instead of being dropped in high stars maps and in the pp meta, because much new players (and less new) don't focus on things such as long maps, accuracy etc...

Edit : Adding badges with it, like circles badges for each categories who grow up every time u pass a level with your actual level in the center of it ; Showed on the profile as the same way as the level thing, why not in game too.

**Comment by Trislot** [comment]
yeah mb its campaign not campain :^)

**Comment by peppy** [comment]
Thanks for the idea. This can already be done (via betamaps and storyboards) and I believe there may be a group or two attempting it in the community. If it takes off and requires specific lazer functionality we can add it when that time comes.
