### ISSUE TITLE
Maximum Score on Osu! Mania

### ISSUE THREAD

**Issue by SuperFat-Fat** [ppy/osu#8689]
**Describe the bug:**
Hi ! I came here because i just finished a mania map on osu lazer, and i just get an impossible score : 1.000.596 as you can see here.
Isn't the best score possible supposed to be 1.000.000 ? If so, sorry to post that here, i'll close the issue.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/51210473/78839662-34ed3580-79f9-11ea-8ef8-197e3a673ea9.png)

**osu!lazer version:** 
2020.408.1

**Logs:**
[network.log](https://github.com/ppy/osu/files/4453098/network.log)
[performance.log](https://github.com/ppy/osu/files/4453099/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4453100/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4453101/updater.log)
[database.log](https://github.com/ppy/osu/files/4453102/database.log)

**Comment by bdach** [comment]
Hold note ticks are currently considered bonus judgements and as such are not part of the 1 million score cap. Each hold note tick will grant 20 points.

**Comment by SuperFat-Fat** [comment]
Oh okay ! Thx for the quick reply !
Should I close the issue ?

**Comment by peppy** [comment]
yep, i think this is expected for now.
