### ISSUE TITLE
Uh.... help?

### ISSUE THREAD

**Issue by Revonicka** [ppy/osu#8698]
So i've encountered a werid error message that i don't have .NET even tho i installed it.

I installed the before newest version of it.

Now i am installing the 5.00 version of the program, does that help?

 
![Screenshot_329](https://user-images.githubusercontent.com/63407613/78900316-f5fdc500-7a76-11ea-884a-bcf21618000d.png)

i've installed the newest version of Osu!lazer 

I actually dont know if this belongs in bugs or crashes, but i really need help.

I'm using windows 10 64x

i got the executable from the official osu!lazer releases here on Github.

Thanks to whoever can write me what should i do!

**Comment by peppy** [comment]
Please provide actual details:

- What version of windows are you using
- Where did you obtain the executable from?

**Comment by Revonicka** [comment]
> Please provide actual details:
> 
> * What version of windows are you using
> * Where did you obtain the executable from?

edited it

**Comment by peppy** [comment]
Did you install using `install.exe`?

**Comment by Revonicka** [comment]
Yes

**Comment by smoogipoo** [comment]
Please provide your exact system version. Press `WinKey+I` -> `System` -> `About`, and you should see something like this:

![image](https://user-images.githubusercontent.com/1329837/78904240-31b87f00-7ab7-11ea-95aa-935810cdc476.png)

We should also update our .net core version (we're currently on runtime 3.1.100 via `global.json`).

**Comment by Revonicka** [comment]
![Screenshot_331](https://user-images.githubusercontent.com/63407613/78905422-4298ce80-7a7e-11ea-8a56-47390c9af2ab.png)

**Comment by huoyaoyuan** [comment]
According to [the doc](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows), Windows 10 version 1607 should be enough.
osu!'s distribution bundles required .NET Core files. You shouldn't be required to download it manually.

**Comment by Revonicka** [comment]
> According to [the doc](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows), Windows 10 version 1607 should be enough.
> osu!'s distribution bundles required .NET Core files. You shouldn't be required to download it manually.

but I don't use this version as you see.(...)

**Comment by Coppertine** [comment]
He's saying that Windows 10 update 1607 up allows for osu!'s distribution with .Net Core bundles.

**Comment by peppy** [comment]
This is definitely something your end. Have you ever installed .net core packages yourself? If so, uninstall them (unless you are a developer using them – in this case please fix the issue at your end).

If none of the above apply, please update windows and try a complete reinstall (delete `AppData/Local/osu` `AppData/Roaming/osu`).
