### ISSUE TITLE
Game wont open after a failed update installation

### ISSUE THREAD

**Issue by Moorad** [ppy/osu#8702]
**Describe the crash:** 
I opened osu and then, as usual, the latest update started downloading. After the downloading process finished I clicked to install and a couple of errors appeared. After that, I tried restarting the game to see if that fixes it but the game does not open anymore. when I click on the game to open it nothing happens at all and I cant see it running on task manager. This might be related to storage since my C drive was very low on storage when I tried to install the update (but the whole update was downloaded ). I freed up some space but that doesn't seem to help much at this point. I'm also aware that reinstalling the game would most likely fix the issue but I just wanted to let you know about this.

**Screenshots or videos showing encountered issue:** 
none

**osu!lazer version:** 
was running 2020.403.0

**Logs:**

[network.log](https://github.com/ppy/osu/files/4459056/network.log)
[performance.log](https://github.com/ppy/osu/files/4459057/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4459058/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4459059/updater.log)
[database.log](https://github.com/ppy/osu/files/4459060/database.log)

**Computer Specifications:** 
CPU: AMD Ryzen 5 2600
Motherboard: MSI Tomahawk b450
GPU: GTX 1060 6GB
RAM: 16GB
OS: Windows 10 Pro

**Comment by peppy** [comment]
have you tried deleting all files in the AppData/Local/osu folder then installing again?

**Comment by Moorad** [comment]
That fixes the problem, should I close this issue?

**Comment by peppy** [comment]
Yeah for now. Squirrel is only a temporary solution for installation/updating so I would rather not track rare issues with it.
