### ISSUE TITLE
Option to "Prefer no-video downloads"

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8705]
**Describe the new feature:** 
On metered or slow connections having an option to download beatmaps with no video would be nice to have.

**Proposal designs of the feature:** 
Everywhere where osu!direct would download a beatmap without the user explicitly saying what type (video or not) they want, option stated in this new setting should be used (instead of defaulting to video included version)

**Comment by GSculerlor** [comment]
Having too much option in settings is not good in my opinion, probably can fetch the default from web setting? (I believe it's there already)

**Comment by LittleEndu** [comment]
Interesting. Is that already used in lazer? Then there should be an option to change that in the in-game settings.

**Comment by peppy** [comment]
It should be implemented locally and eventually be synchronised with web.
