### ISSUE TITLE
Transition between hovering over main panel's and sub panel's sub sections in settings should be seamless.

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8707]
**Describe the bug:** 
When you hover over the sections in the settings, they will expand their descriptions. When you transition between hovering over the main panel's sections to hovering sub panel's sections, the main panel will close its descriptions and then you are no longer hovering over the sub panel's sections. When you transition between hovering over the sub panel's sections to hovering main panel's sections, the main panel will still wait before displaying its descriptions.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/a3BA-LCTvek

**osu!lazer version:** 
2020.408.1

**Comment by peppy** [comment]
i don't think this current behaviour is too bad, personally..

**Comment by Joehuu** [comment]
Closing as it is always expanded now (https://github.com/ppy/osu/pull/26147).
