### ISSUE TITLE
Add a button “Copy URL-map” for quick sending to chat

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8715]
**Describe the new feature:** 
I think it can be added near the "open in browser" button, because it will allow sharing maps in the lazer itself (the command /np does not work yet, although this function can work with the /np command)
Maybe add the command /c for this action?
![osu_2020-04-11_21-10-21](https://user-images.githubusercontent.com/59089206/79042256-5a688200-7c39-11ea-9175-2e8f841925f0.png)

**Comment by LittleEndu** [comment]
Maybe all usages (currently only beatmap listing and user profile) of ``ExternalLinkButton`` should be replaced with two buttons, one for opening in browser, one for copying the link. Call it something like ``LinkButtons``. Going one step further, if nothing is going to use them separately, the ``ExternalLinkButton`` should just be renamed to ``LinkButtons`` that includes the two sprite icons.

**Comment by peppy** [comment]
LinkButton could just have a context menu for now with a copy action on it.

**Comment by Moltanicaa** [comment]
Can still make her a little bigger? She is very small

**Comment by Game4all** [comment]
Here are my two cents : how about copying the link when left-clicking on the button instead of adding a contexual menu ? (I know this won't work well on mobile, so it would be rather a long touch on the link button on touch devices)

**Comment by LittleEndu** [comment]
Context menu makes most sense because you could also include options like "Copy (set/difficulty) ID"

**Comment by Moltanicaa** [comment]
For phones, you can make the menu call a long tap
