### ISSUE TITLE
Showing tutorial pop-ups to new players

### ISSUE THREAD

**Issue by Pachiru** [ppy/osu#8717]
Having a pop-up when the game starts for the first time or based on the account stats (so it only show up for new players) asking to the player if they want to play the osu!tutorial. The new osu!tutorial is called "new horizons" which doesn't make it really intuitive for new players to find. 

Also, having some pop-ups here and there after the tutorial, explaining how leaderboards works, how mods works, how to get beatmap (even if I think it is explain when you create an account, so it could be optional), etc... 

I think having those small intentions given to rookies would make it very enjoyable and give a newbie-friendly atmosphere to the game so it doesn't feel like they're thrown alone in the jungle.

Sorry if the idea been brought already, I've quickly did a research but couldn't find anything so I gave it a try!

**Comment by bdach** [comment]
There's been some discussion already at #5577. The ideas are appreciated, but I'll close this for now as to not have multiple places where this is being discussed.

Also keep in mind that this is very low on the list of overall priorities for now.
