### ISSUE TITLE
Internal links don't open anything.

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8720]
**Describe the bug:** 
Clicking on links that are supposed to open in-game overlays don't do anything.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/fNrAlL53kpo

**osu!lazer version:** 
2020.408.1

**Comment by bdach** [comment]
Let's group under #6747.

**Comment by LittleEndu** [comment]
Note, it's specifically [the delimiter](https://github.com/ppy/osu/issues/6747#issuecomment-550527535) that causes the link in example to not work.
