### ISSUE TITLE
Missing the option to see (and save) your replay after failing the map.

### ISSUE THREAD

**Issue by ghost** [ppy/osu#8721]
**Describe the new feature:** 

We can't see the replay ( in the fail screen ) of a score we just failed by pressing F1 (or F2 I don't remember) like on stable.

In addition being able to save your failed replay with another key while in the fail screen would be very nice.

**Comment by szmarczak** [comment]
I think that replays of fails is crucial. That way you can easily see where you make mistakes.

**Comment by memesnightmares** [comment]
Expanding on this idea a bit, it would be nice to allow quick-replay or saving to local leaderboards from the fail screen (and maybe also atomic save and quit on the pause screen). These saved replays could be labeled in the local leaderboard with some icon indicating that they're incomplete/cut/severed replays.

**Comment by Joehuu** [comment]
Implemented in https://github.com/ppy/osu/pull/18785.
