### ISSUE TITLE
10k+ mania maps fail to load results screen without auto mod

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#8723]
mania maps with 10 or more keys plays fine but the results screen doesn't load, the escape button also stops working. the retry button can be used to get out of this situation as it still works

issue doesn't seem to occur with the auto mod on

can be replicated by finishing a mania map with 10 keys or more

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/79101178-f82b9080-7da2-11ea-8a89-1f35304ff431.png)

Seemed to work for me. Please provide logs and specific beatmap details.

**Comment by genericthing** [comment]
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4472193/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/4472194/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4472195/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4472196/performance-gamethread.update.log)
[performance-update.log](https://github.com/ppy/osu/files/4472197/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/4472198/runtime.log)
[database.log](https://github.com/ppy/osu/files/4472199/database.log)
[network.log](https://github.com/ppy/osu/files/4472200/network.log)
[performance.log](https://github.com/ppy/osu/files/4472201/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/4472202/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4472203/performance-draw.log)

i have no idea which log might help

**Comment by peppy** [comment]
which beatmap are you testing with?

**Comment by genericthing** [comment]
both of the maps i tested without autoplay led to this issue

https://osu.ppy.sh/beatmapsets/367540#mania/806127 
https://osu.ppy.sh/beatmapsets/394661#mania/858936

**Comment by peppy** [comment]
Able to see how this is happening thanks to the logs you provided (replay encoding is failing). The reason I was not reproducing is I never pressed a key high enough to matter while testing with NoFail.
