### ISSUE TITLE
Carousel shouldn't display scores played with unranked mods as top local rank

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8724]
**Describe the bug:** 
Carousel panels display your top local rank. The rank displayed shouldn't be chosen from unranked plays.

**Screenshots or videos showing encountered issue:** 
![osu_2020-04-11_19-50-50](https://user-images.githubusercontent.com/11320483/79049689-c6dd8400-7c2d-11ea-8bc5-2de32747357f.png)

**osu!lazer version:** 
2020.408.1

**Comment by peppy** [comment]
Why not?

**Comment by LittleEndu** [comment]
idk, stable doesn't and I was confused when I saw I played some hard difficulty and got an S, then I looked and it was with relax.

**Comment by LittleEndu** [comment]
to be fair, stable doesn't display it because it doesn't even save unranked plays

**Comment by peppy** [comment]
I'm pretty sure this is intended behaviour for now. It will likely be solved by ranks showing online (aka "ranked") plays when looking at global leaderboard at song select, once we have storage for that.
