### ISSUE TITLE
osu lazer save data?

### ISSUE THREAD

**Issue by Endersheep12345** [ppy/osu#8730]
Hello, I would like to ask is it possible to transfer or link osu score datas with osu lazer?

The save sata of osu should be Data, and there are 'bt' and 'r' folders, but I don't seem to find these in osu lazer. The score importing in osu lazer doesnt work.

Thank you very much for supporting

**Comment by bdach** [comment]
Import options from stable are available from the *Maintenance* section of settings.

![image](https://user-images.githubusercontent.com/20418176/79068600-7404da80-7cc8-11ea-831d-4b3a70ad3960.png)

Please note that lazer internally uses a different, incompatible storage structure.
