### ISSUE TITLE
PresentBeatmap should present recommended difficulty

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8732]
After #8731 and #8444 are merged, I think we should change ``PresentBeatmap`` to present the recommended difficulty.

**Comment by LittleEndu** [comment]
The way I see it, ``DifficultyRecommender`` might need to be moved to ``OsuGame`` or ``OsuBaseGame`` and cached there so that it could be accessed from anywhere we might need a recommendation.

**Comment by peppy** [comment]
Sounds fair.
