### ISSUE TITLE
Filter maps by game mode

### ISSUE THREAD

**Issue by Waidxd** [ppy/osu#8743]
In current stable release you can search "mode=taiko" and this would return only taiko maps. This currently does not work on lazer and I cant seem to find an alternative way to filter the search results to get same results.

going through a list that contains more standard converts than actual taiko maps is whats mostly stopping me from playing lazer at the moment.

**Comment by Game4all** [comment]
FYI, you can disable showing converts in song select in the game settings  (try searching for "Show converted beatmaps" in settings)

**Comment by Waidxd** [comment]
Thanks, 

Closing since the feature is basically already implemented
