### ISSUE TITLE
Android STB issues when loading beatmaps

### ISSUE THREAD

**Issue by tildearrow** [ppy/osu#8745]
Loading any beatmap causes this notification to pop up:
> Texture could not be loaded via STB; falling back to ImageSharp.

This was reproduced under Android 8.0 on Galaxy S9 (Qualcomm). I am not sure if it will reproduce in a different device.

Version used: 2020.413.0.

**Comment by bdach** [comment]
I'm betting on this being a duplicate of #7062 (old glibc); closing as such.

**Comment by peppy** [comment]
Happens on iOS too, fwiw.
