### ISSUE TITLE
Base scores for notes not giving the correct score\

### ISSUE THREAD

**Issue by HDAcai** [ppy/osu#8747]
**Describe the bug:** 
Base score for 300’s, 100’s and 50’s on lazer are different from the base scores from osu stable. Lazer scores: 300=12 , 100=4 , 50=2. Stable scores: 300=300 , 100=100 , 50=50
**Screenshots or videos showing encountered issue:** 
![876F1EAB-1044-4EF2-B4BF-9739E219DB81](https://user-images.githubusercontent.com/57856097/79160931-7d0caf00-7d8f-11ea-9674-8a4b29f1ed71.jpeg)
![DA711930-A6C5-4294-8862-9C916FAB56ED](https://user-images.githubusercontent.com/57856097/79160943-7f6f0900-7d8f-11ea-8724-4f227f21b7ad.jpeg)
![5AE28B5A-F32E-47AA-92EB-2BFF8B045343](https://user-images.githubusercontent.com/57856097/79160944-80079f80-7d8f-11ea-83fb-0668908019c3.jpeg)
![E0220FF2-43DB-41A4-9106-BC130128B3B1](https://user-images.githubusercontent.com/57856097/79160947-80a03600-7d8f-11ea-8619-85b20323c283.jpeg)
![5FD7E63D-67E7-448F-B659-8A86747C0E7C](https://user-images.githubusercontent.com/57856097/79160948-80a03600-7d8f-11ea-870c-1dd6a44c27ed.jpeg)
![AD31CDE0-8AE4-43B2-AA79-31B0FE9527D7](https://user-images.githubusercontent.com/57856097/79160949-8138cc80-7d8f-11ea-8e71-951f015607d8.jpeg)

**osu!lazer version:** 
2020.413.0

**Comment by bdach** [comment]
This is intended as lazer by default uses a new scoring system similar to score V2, in which the maximum number of points for non-bonus judgements is capped at 1 million (so your findings are kind of true only for this specific map).

To go back to the old scoring method, you can change it in the settings from *Standardised* to *Classic*.

**Comment by HDAcai** [comment]
Standardized scoring caps the score at 1,000,000 but the results I have shown are with the classic scoring system and this scoring method seems to be true for all played beatmaps.
