### ISSUE TITLE
Perfectly placed inherited timing points not applying to the bar line (taiko) but applying to the note

### ISSUE THREAD

**Issue by Alchyr** [ppy/osu#8749]
https://github.com/ppy/osu-stable-issues/issues/396
Tested and does occur in lazer.

Basically, an sv change placed exactly on a barline can sometimes not affect the barline it's on.

**Comment by bdach** [comment]
Not a 100% sure but it looks very much like it's floats.

![image](https://user-images.githubusercontent.com/20418176/82155153-14738f00-9873-11ea-87a0-31cb3453f2df.png)

Leaving paper trail just in case, but will see if I can do anything about this myself today.

**Comment by smoogipoo** [comment]
The editor applies a -1ms offset to resolve similar timing issues. May be a solution to consider here too...

**Comment by jmagine** [comment]
It appears to me that this isn't fully resolved. I've attached a beatmap with 2 examples of inherited timing points changing only the hitobject/note properties, but not the barlines on the latest stable osu! release. Every 3rd barline is impacted in this particular case, and I suspect it may have something to do with the way things are being rounded or truncated as the 3rd barline times would be very close to integer values (.999999...9 or .000000...1 values). Trying to find more examples, but hopefully it's not just me being crazy here :)

[Anar Software LLC - 10 Minutes of Silence.zip](https://github.com/ppy/osu/files/7666041/Anar.Software.LLC.-.10.Minutes.of.Silence.zip)

**Comment by peppy** [comment]
You are reporting this against lazer. Is that the intention?

**Comment by jmagine** [comment]
I just tried with Lazer (2021.1206.0) and the barlines appear to be correct there for this example. I'm not sure where I should report this, but I believe I am on Stable (20211122.1)
