### ISSUE TITLE
App was not installed

### ISSUE THREAD

**Issue by bemxio** [ppy/osu#8758]
**Describe the bug:** 
I can't install latest osu!lazer on my phone (Motorola Moto Z Play, Android 8.0) since it says "App was not installed".
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
latest one

**Logs:**
i'm on Android, so idk how to get these

**Comment by TheWildTree** [comment]
Do you have any previous lazer versions installed on your phone?

**Comment by bemxio** [comment]
i uninstalled one before installing latest one, but it was not working

**Comment by TheWildTree** [comment]
If that's the case, the Android package installer might be just wonky - try restarting your phone.

**Comment by bemxio** [comment]
ok, thanks!
