### ISSUE TITLE
There are files for android plans

### ISSUE THREAD

**Issue by Alarmbunny** [ppy/osu#8760]
If there are files for Android porting. The peppy needs to do it sooner in development  or later because we only have the beta Lazer version on Android.

**Comment by bdach** [comment]
I'm not sure what you're trying to convey here exactly. I'm guessing you're asking for the ability to read files from storage on Android, which has already [been](https://github.com/ppy/osu/issues/6525) [requested](https://github.com/ppy/osu/issues/5761) before and _will_ happen at some point, but it's not more important than actually having the game be on par with stable on desktop, which is the current focus.
