### ISSUE TITLE
Notelock working incorrectly for sliders

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu#8763]
**Describe the bug:** It seems that it judges miss for all the previous un-judged hit objects when clicking a hit object.

**Screenshots or videos showing encountered issue:** https://youtu.be/kbOMGZHIw48

**osu!lazer version:** 2020.413.0

**Comment by peppy** [comment]
Probably should be limited in scope as to how many objects (or how long in milliseconds) back it can cause to miss (maybe 1-2 would be more acceptable).

**Comment by smoogipoo** [comment]
I think the weirder part is that it missed _future_ hitobjects, from what it looked like.

**Comment by peppy** [comment]
Thought the same thing, but it didn't (check at 0.25 speed). Just a pattern designed to trip you up.
