### ISSUE TITLE
auto fail mod/customization options

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#8767]
this mod will force a fail to occur if the requirements are not met

the customization options are:
accuracy(if below, map is failed)
hp(if below, map is failed) 
a total amount/percentage of any judgement rating(if amount/percentage of not-best ratings is higher than threshold, map is failed or if amount/percentage of best ratings is lower than threshold, map is failed)

all options are disabled by default
an option to make a check on breaks or at the end of the map

these options can be put into customization box without the mod(meaning that the customization button will always be available to access these options)

**Comment by doughn0** [comment]
Also, an option to fail if it is no longer possible to beat your highscore on the map with the current play.

**Comment by enoslayd** [comment]
For mania (and maybe other modes as well), have at least x combo when finishing a beatmap (ex. 200 combo at the end to consider a pass)

**Comment by Joehuu** [comment]
> Also, an option to fail if it is no longer possible to beat your highscore on the map with the current play.

Idea already in https://github.com/ppy/osu/issues/6642.

**Comment by GSculerlor** [comment]
Looking into this one. Should it included on fun mod or can be included on same group with SD/PF? And also any idea about the name? Since I don't think "Auto Fail" is good name here

**Comment by bdach** [comment]
I'm not sure all of these proposed mechanics should be one customisable mod; seems like the mod would be doing too much to give it a single intelligible name or purpose. splitting per proposed fail condition (i.e. something like *Score Challenge*, *Accuracy Challenge*) might fare better. those then could be combined if need be, I suppose.

**Comment by genericthing** [comment]
maybe we should put these options into a new section called "challenge section" and also move sd/pf there

it's a section where you challenge yourself to do better after all so all those mods will fit

**Comment by peppy** [comment]
New section sounds fine.

**Comment by MitsukaiDokuro** [comment]
Shouldn't be a new mod. Would this implemented as Sudden Death mod options.
