### ISSUE TITLE
combo counter not resseting when long notes quickly pressed, unpressed and pressed

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8770]
Describe the bug: combo counter in mania not returning to zero when long notes quickly pressed, unpressed and pressed. sometimes it doesnt show the miss hitburst sometimes it shows but the combobreak hit sound doesnt play and the counter doesnt reset

Screenshots or videos showing encountered issue:  (rename to .mp4)
[My Movie.zip](https://github.com/ppy/osu/files/4485401/My.Movie.zip)

osu!lazer version: 2020.413.0

Logs:
[updater.log](https://github.com/ppy/osu/files/4485433/updater.log)
[database.log](https://github.com/ppy/osu/files/4485434/database.log)
[runtime.log](https://github.com/ppy/osu/files/4485436/runtime.log)
[network.log](https://github.com/ppy/osu/files/4485439/network.log)
[performance.log](https://github.com/ppy/osu/files/4485441/performance.log)

**Comment by enoslayd** [comment]
oops, similar problem to #8744 but when breaking, sometimes miss hitburst shown without the comboreak hitsound, sometimes not.

**Comment by bdach** [comment]
Tick misses showing up without breaking combo are explicitly intended for now, as a corollary giving bonus score for each tick hit:

https://github.com/ppy/osu/blob/09550283d0590f64117fb5b398765397a2426fbd/osu.Game.Rulesets.Mania/Judgements/HoldNoteTickJudgement.cs#L10

Closing as duplicate.
