### ISSUE TITLE
Audio offset does not scale properly with HT or DT

### ISSUE THREAD

**Issue by Maoman1** [ppy/osu#8774]
**Describe the bug:** 
When half time or double time is active, the global audio offset does not scale properly and leads to a mismatch in timing. Due to an issue with my soundcard I have a very high audio offset (-155ms) which means this effect is greatly exaggerated on my system, so it may not have been noticed by users with smaller offsets which would (I assume) only result in a tiny error in timing.

Edit: Just tested this and HT requires lowering the offset while DT requires increasing it, both by the same ratio as the speed. i.e. HT at 75% speed matched an offset of about -110 ms (which is ~75% of 155)

**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/Vf8WBfr.mp4 Normal speed, no mods (ignore the misses at the start, had to get used to the lag from running OBS)
https://i.imgur.com/JfM2LxY.mp4 Half time 75% speed
Don't know how to get sound in imgur uploads but you can see the timing bar on the left. I didn't bother taking a video of double time but it does the same thing in the opposite direction (i.e. all the marks are on the bottom of the timing bar)

**osu!lazer version:** 
2020.413.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4490141/database.log)
[network.log](https://github.com/ppy/osu/files/4490142/network.log)
[performance.log](https://github.com/ppy/osu/files/4490143/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4490144/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4490145/updater.log)

**Comment by peppy** [comment]
This was actually an intentional change as it seemed more correct in the way it is currently implemented (based on the assumption that sound card latency is constant over all playback speeds). We'll need to do some further testing here.

**Comment by Maoman1** [comment]
Since it's semi-related, are you already aware of how hit sounds also do not adjust their timing properly based on the audio offset? If not I'll try to get it on video and make a new issue for it (it'll probably require a video from my phone so you can see/hear my tapping as well as the hit sounds)

**Comment by peppy** [comment]
hitsounds cannot and will not adjust with audio offset. they are triggered by your input.

**Comment by peppy** [comment]
I've attempted to reproduce your issue and can understand how this is happening. You are correct in thinking what we have is actually wrong. We are always applying the same millisecond offset, but due to game time actually progressing at an adjusted rate, this is no longer applying a constant RTC offset but one relative to the playback rate.
