### ISSUE TITLE
Incorrect rendering of the osu! logo on macOS

### ISSUE THREAD

**Issue by lqf96** [ppy/osu#878]
The osu! logo is rendered incorrectly on macOS. All other UI elements seem normal.
From the console there is a libpng warning: iCCP: known incorrect sRGB profile
I'm running osu! with mono and mono-libgdiplus from Homebrew.

<img width="1280" alt="2017-05-29 7 36 44" src="https://cloud.githubusercontent.com/assets/11476527/26548332/33089aa6-44a6-11e7-9147-0cc279e081e9.png">
<img width="1280" alt="2017-05-29 7 36 57" src="https://cloud.githubusercontent.com/assets/11476527/26548333/3319e478-44a6-11e7-8bcf-988b3021d185.png">

**Comment by VPeruS** [comment]
Linux have save problem. Maybe some specific option was enabled when saving?

**Comment by VPeruS** [comment]
Removing logo.png completly from resources doesn't remove warning, so it may not related.

**Comment by peppy** [comment]
It's not the only one affected. Quite a few resources need fixing.

**Comment by VPeruS** [comment]
Resaving in Krita with this

![settings](https://cloud.githubusercontent.com/assets/7927055/26581745/c03fd11e-4546-11e7-93dd-f06a66d8bcfd.png)

Will solve logo problem in Linux(libpng warning still here).

**Comment by peppy** [comment]
If you google the issue, `mogrify -strip` is supposed to work, but it didn't seem to help for me. we need an `imagick` or equiv. command to run rather than some ui app.

**Comment by VPeruS** [comment]
I run ```mogrify -strip``` on every file in Textures directory and it remove warning but it also remove all textures.

**Comment by jai-sharma** [comment]
Libpng warning is also present on Linux. Instead of a garbled render of the logo, it is not rendered at all. 
![2017-05-31-175026_665x450_scrot](https://cloud.githubusercontent.com/assets/8362491/26643664/f7e2f05e-4629-11e7-807d-bd3814ec0838.png)

**Comment by peppy** [comment]
"me too" replies are not needed, thanks. either fix or wait for someone else to fix.

**Comment by jai-sharma** [comment]
Fix: Run the following imagemagick command on all .png files.
`convert file.png -colorspace sRGB PNG32:file.png`
