### ISSUE TITLE
Click that makes game window active again shouldn't close overlays

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8782]
**Screenshots or videos showing encountered issue:** 
https://youtu.be/dtAxbmBEHJ0

**osu!lazer version:** 
2020.408.1

**Comment by Joehuu** [comment]
This will be fixed once we move to SDL (or append `--sdl` atm).

**Comment by peppy** [comment]
not sure i agree with this

**Comment by Joehuu** [comment]
Fixed in SDL as of now, although I agree this is non-standard behavior so leaving open for now.
