### ISSUE TITLE
Add Local Score Modifier Info

### ISSUE THREAD

**Issue by Panthr75** [ppy/osu#8785]
**Describe the new feature:** 
For mods that have customizable options (like wind up/down, difficulty adjustment, etc), they should have a display of their value for the score selection screen.

**Proposal designs of the feature:** 
Some sort of button right below the score that would be three dots, and when opened, would show the modifier's values.

Here's what (I'm thinking at least) the popup ui could be:
<table>
    <tbody>
        <tr>
            <td>Modifier Name</td>
            <td>Modifier Value(s)</td>
        </tr>
    </tbody>
</table>

So for example, if I had no fail, wind-up from 0.75 to 1.25, and difficulty adjustment where I changed the accuracy down to 8.5 (from 8.7) and changed the circle size from 4.0 to 3.9, it could look like this:
<table>
    <tbody>
        <tr>
            <td>No Fail</td>
            <td></td>
        </tr>
        <tr>
            <td>Wind-Up</td>
            <td>From 0.75-1.25</td>
        </tr>
        <tr>
            <td>Difficulty Adjustment</td>
            <td>
                <ul>
                    <li><b>Accuracy</b>: -0.2 (8.5)</li>
                    <li><b>Circle Size</b>: -0.1 (3.9)</li>
                </ul>
            </td>
        </tr>
    </tbody>
</table>

**Comment by peppy** [comment]
there are already tooltip songs mod icons showing this. is that what you're asking for?

**Comment by Panthr75** [comment]
Oh!
