### ISSUE TITLE
red tint layer displays even though no fail is enabled

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8789]
Describe the bug: the red tint layer displays when failing even though no fail is enabled. doesnt happen to stable though. feel free to close if intentional

Screenshots or videos showing encountered issue:
stable w/ no fail
![screenshot059](https://user-images.githubusercontent.com/41866328/79631337-4d90e480-818b-11ea-9780-3fac36b2a7be.png)

stable w/o no fail
![screenshot060](https://user-images.githubusercontent.com/41866328/79631348-6a2d1c80-818b-11ea-8a6a-642c93058679.png)

lazer w/ no fail (std)
![osu_2020-04-18_15-34-09](https://user-images.githubusercontent.com/41866328/79631574-cd6b7e80-818c-11ea-8d63-8881b18a4805.png)

Lazer w/ no fail (mania)
![osu_2020-04-18_15-37-42](https://user-images.githubusercontent.com/41866328/79631588-e83df300-818c-11ea-89fb-19801d092ea0.png)

osu!lazer version: 2020.418.0

Logs: not needed???

**Comment by peppy** [comment]
Not sure this is so bad..

**Comment by LittleEndu** [comment]
In-fact stable not showing the red tint when you use NF and not showing misses when you use RX is pretty annoying and not fun at all.

**Comment by Game4all** [comment]
I was aware of these cases when I PR'ed , but decided to keep them for a follow-up PR to match stable behaviour. Looks like the direction for this is to display the tint regardless of the current mods but I guess it may be interesting to get other opinions on that behavior change compared to stable?

**Comment by LittleEndu** [comment]
Speaking of other options, mania might need the red tint to come from left and right side. But that should be tracked in another issue.

**Comment by Coppertine** [comment]
I would think that having the red tint on something with NF would confuse the player as they know they are not going to have low HP since there technically is no HP in the mod.

**Comment by enoslayd** [comment]
> In-fact stable not showing the red tint when you use NF and not showing misses when you use RX is pretty annoying and not fun at all.

i agree about rx but the no fail should not display the tint imo

**Comment by enoslayd** [comment]
> Speaking of other opinions, mania might need the red tint to come from left and right side. But that should be tracked in another issue.

very agree on this

**Comment by bdach** [comment]
While I don't think this is bad either, *maybe* the tint should tie into the "Show health display even when you can't fail" setting?

**Comment by peppy** [comment]
Sounds good.
