### ISSUE TITLE
rewinding replay as soon as it ends may result in incorrect result screen score

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#8793]
When the replay ends, if you try to rewind the replay it shows a result screen with incorrect score

The final score should be 1000000 but it's not.
https://streamable.com/zawmoz

osu!lazer 2020.418.0

**Comment by iiSaLMaN** [comment]
I feel like the best behaviour to this would be to cancel pushing results screen if the replay didn't rewind during the delay between the completion and push time, will look into fixing this.
