### ISSUE TITLE
Disable Windows key during gameplay

### ISSUE THREAD

**Issue by santerinogelainen** [ppy/osu#8795]
**Describe the new feature:** 
Just like you can disable mouse keys during gameplay, there should be an option to disable the 
Windows key during gameplay. I use the default Z/X keys to play osu! and accidentally press the windows key with my ring finger which results in the Windows start menu being opened and gameplay to be paused. I currently avoid this issue by taking the keycap off of my windows key but it does still sometimes happen.

**Proposal designs of the feature:** 
This is Windows specific, so I think the setting should only be there if you are playing on Windows (if lazer supports platform specific settings). Or maybe this shouldn't even be a setting and rather just always disable the key during gameplay. I don't really see a reason to press the winkey during gameplay. When the gameplay is paused or you are in the menus you should be able to use the winkey normally.

**Comment by Game4all** [comment]
Disabling the Windows key for an application require setting up a keyboard hook at a low level.  While it can definitely be done with C#, should it really be resolved by software ?

The overhead for implementing and maintaining this is such that it doesn't makes it worth to implement imo.

Furthermore, most gaming keyboards now boast a gaming mode, which disables the windows key on the hardware.

**Comment by iiSaLMaN** [comment]
I agree with @Game4all, disabling such platform-specific key from a game sounds like something it shouldn't handle at all.

**Comment by swoolcock** [comment]
This is not something we should be doing, as any solution is going to be very hacky.  If you want to disable the Windows key, do it yourself through the registry or buy a gaming keyboard that has a switch that does it.

**Comment by peppy** [comment]
This has been in stable forever after a large demand for it. Not sure we should throw away the suggestion so quickly.

**Comment by swoolcock** [comment]
Ah, I haven't played stable in quite a while, I never even noticed that.  Fair enough.

**Comment by Game4all** [comment]
Can be closed with the merge of #9439

**Comment by bdach** [comment]
I suppose, although it doesn't really work as far as end users are concerned, but that is tracked at #9741.
