### ISSUE TITLE
Storyboard overlay layer not shown in Cinema mode

### ISSUE THREAD

**Issue by T0chi** [ppy/osu#8797]
**Describe the bug:** the storyboard overlay layer isn't shown while playing a map with the cinema mod but is shown in the editor or while playing without the cinema mod.

**osu! version:** Stable 20200320

**Comment by iiSaLMaN** [comment]
Are you sure about this? The overlay layer is not supported at all currently (check https://github.com/ppy/osu/issues/8017), perhaps you're mistaking it for another layer?

**Comment by T0chi** [comment]
It's supported in the non-osu!lazer versions, I'm aware that it isn't implemented yet at all in osu!lazer.

Since it's already implemented in the non-osu!lazer versions then it's unfortunate that it's inconsistent and doesn't work with the cinema mod but in the editor or while playing without the cinema mod, the other layers works perfectly though

**Comment by T0chi** [comment]
I oversaw the other thread before opening this issue so this may be closed, I'm not sure if these bug issues are strictly for osu!lazer or both the other osu! versions and lazer, though sorry if I misunderstood!

**Comment by bdach** [comment]
Closing as duplicate.

The proper place to report stable issues is [here](https://github.com/ppy/osu-stable-issues/) (and even then your request might not happen if it requires a substantial amount of work).
