### ISSUE TITLE
Add warning when trying to acces multiplayer when servers are offline

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#8803]
**Describe the new feature:** 

It should be a good idea to add a warning text box when accessing the multiplayer when servers are offiline. Because actually the room browser stay empty and we can't create a room. 

**Proposal designs of the feature:** 

Add a warning text box that return us to the main menu or makes the multiplayer button unclickable.

**Comment by peppy** [comment]
Related to (and maybe duplicate of?) https://github.com/ppy/osu/issues/7417.

**Comment by MTGPROD** [comment]
It is more specific to the multiplayer menu so it's more related than duplicate of 🤔

**Comment by peppy** [comment]
Understand that the thing you're specifying is not handled well *anywhere*, which is why the other issue exists.

**Comment by peppy** [comment]
This looks to be handled correctly these days - a loading layer is protecting the rooms list and correctly handles disconnected  states.
