### ISSUE TITLE
osu lazer crashes after opening

### ISSUE THREAD

**Issue by ondradoksy** [ppy/osu#8804]
few weeks ago it worked fine, but now when i try to open osu lazer all I see is a black screen and then it crashes within 3 seconds
[network.log](https://github.com/ppy/osu/files/4499982/network.log)
[database.log](https://github.com/ppy/osu/files/4499983/database.log)
[runtime.log](https://github.com/ppy/osu/files/4499984/runtime.log)

**Comment by bdach** [comment]
Seemingly yet another case of database corruption in some fashion:

```
2020-04-19 19:09:10 [error]: An unhandled error has occurred.
2020-04-19 19:09:10 [error]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
2020-04-19 19:09:10 [error]: ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
```

Not sure if we're going to investigate in detail as sqlite is on its last legs but you could attach `client.db` here for posterity if anything. Moving it away / deleting it and reimporting should solve the problem.

**Comment by peppy** [comment]
deleting the database and reimporting is the recommended solution for now.

**Comment by ondradoksy** [comment]
Here is the client.db
I added .txt because github doesn't support .db

Deleting the file fixed the problem.

[client.db.txt](https://github.com/ppy/osu/files/4502609/client.db.txt)
