### ISSUE TITLE
Shaking looks incorrect with new ordered hit policy

### ISSUE THREAD

**Issue by peppy** [ppy/osu#8807]
Shaking should probably continue as long as a hitobject cannot be missed, rather than stopping when within the "valid" miss time of an object (ignoring the ordered hit policy):

![2020-04-20 11 44 16](https://user-images.githubusercontent.com/191335/79709316-de3b0200-82fc-11ea-9b80-596a811474b8.gif)

Shake time is being limited here:

https://github.com/ppy/osu/blob/70ef6df4fbe4d7ccbe7c91ac23939192ad63483a/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs#L125

**Comment by kornkaobat** [comment]
Change `Shake(Math.Abs(timeOffset) - HitObject.HitWindows.WindowFor(HitResult.Miss)); ` into `Shake(Math.Abs(timeOffset) + HitObject.HitWindows.WindowFor(HitResult.Miss)); ` maybe?

**Comment by bdach** [comment]
As far as I understand hit windows are not really relevant here (the ordered hit policy is, as per the issue title), so it's not a matter of a flipped sign.

**Comment by kornkaobat** [comment]
Create a list of all hitobject LifetimeStart and LifetimeEnd, then use 
```
for (i=0; i < LifetimeStarts.Count -1; i++)  {
if (Enumerable.Range(LifetimeStarts[i],LifetimeEnds[i]).Contains(Time.Current))
{
    return true;
}
}
```
Put this inside a checker function, rename some variables and add it to 
`if (result == HitResult.None || CheckHittable?.Invoke(this, Time.Current) == false)`

**Comment by bdach** [comment]
I'm somewhat certain that won't solve the problem, either.

Please think over and test your suggestions before proceeding to post them.

**Comment by frenzibyte** [comment]
Resolved in https://github.com/ppy/osu/pull/20398
