### ISSUE TITLE
Osu loses text input focus after holding WIN key and pressing some other key

### ISSUE THREAD

**Issue by BanD11** [ppy/osu#8812]
Well, it's not really loses text input focus, just appears to lose it.
**Describe the bug:** 
Anywhere in game, hold WIN and press SPACE, or hold WIN and press G (if pressed G, return back to game). Now text input (if you're searching a song, let's say) won't appear in its field. 
Regain focus (ALT+TAB, as example), press any text key (A, K, S, ...). All the text you've inputted will now appear. Osu continue to work as it was.

Also, while in bug state, F1, F2, F3 still works, Ctrl+F2 - don't. Z and X still works for rhythm input
**Where it occurs:**
_(any window mode, but fullscreen mode regains focus after clicking on osu window, so it's a less of an issue)_ Holding WIN and pressing G - opens Xbox Game Bar, return back to Osu in any way (WIN+G, ESC, mouse click) → bug
_(any window mode)_ Holding WIN and pressing SPACE - opens keyboard layout overlay, let go WIN or SPACE → bug
**Where it doesn't occurs:**
Pressing WIN and pressing G - opens Xbox Game Bar, return back to Osu in any way (WIN+G, ESC, mouse click) → no bug
Pressing WIN and pressing SPACE - opens keyboard layout overlay for split second and changing keyboard layout → no bug (it's kinda hard to do though)
**Screenshots or videos showing encountered issue:** 
https://youtu.be/IF_IB2nXNh4
(Though you can't see me press WIN+SPACE and then alt-tabbing)
**osu!lazer version:** 
osu 2020.418.0.0
Windows 10 1903
**Logs:**
[performance-audio.log](https://github.com/ppy/osu/files/4505497/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4505499/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4505500/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/4505502/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4505506/updater.log)
[database.log](https://github.com/ppy/osu/files/4505507/database.log)
[network.log](https://github.com/ppy/osu/files/4505508/network.log)
[performance.log](https://github.com/ppy/osu/files/4505511/performance.log)

**Comment by bdach** [comment]
Can reproduce. Does not happen on SDL which means this is an OpenTK-specific issue and could probably even be closed.

**Comment by bdach** [comment]
I actually found ppy/osu-framework#2525 when scanning through framework-side issues that could be fixed by SDL. Closing as duplicate.
