### ISSUE TITLE
Intro songs need a special /np case

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8827]
**Screenshots or videos showing encountered issue:** 
![2020-04-21 23_04_09-Window](https://user-images.githubusercontent.com/11320483/79908769-7d0e4e00-8424-11ea-8c70-5c9c8a94ab9d.png)
I would expect the [] to be missing for intro songs, or to not even be able to use /np on them.

**osu!lazer version:** 
2020.421.0

**Comment by peppy** [comment]
ToString should be changed to just exclude the brackets if there is no content.
