### ISSUE TITLE
Remove fade out on mania notes

### ISSUE THREAD

**Issue by vernonlim** [ppy/osu#8831]
Description:
Regular notes in lazer currently fade out over a short period, pictured here:
![osu_2020-04-22_13-55-55](https://user-images.githubusercontent.com/25032854/79946203-10d22f80-84a2-11ea-813c-0ffbf2492a64.jpg)
This is different from their behavior in stable where they disappear instantly. (pictured below somewhat)
![screenshot673](https://user-images.githubusercontent.com/25032854/79946273-32cbb200-84a2-11ea-9797-9c68704acf74.jpg)
This really put me off while playing because this is different from almost all mania rhythm games (they use instant fadeout), and gameplay-wise the feedback from hitting a note is no longer immediate (it kind of feels 'mushy' to me, and the notes still being visible past the judgement line is really off-putting).

I would like this to be a toggle/option somewhere, and make instant fade the default so it is in line with stable.

**Comment by peppy** [comment]
I think it should be a default that they do not fade. I think the fade was a temporary thing for the default skin until we got the "explosion" looking good (and covering the note completely).

**Comment by smoogipoo** [comment]
This has already been fixed since https://github.com/ppy/osu/pull/9909.
