### ISSUE TITLE
Gamemode Randomly Switches

### ISSUE THREAD

**Issue by IsaacElenbaas** [ppy/osu#8838]
**Describe the bug:** 
Gamemode changes when scrolling through beatmaps. I believe it to be related to autoconverted ones, as it often changes to standard but rarely others, and I used to delete all non-standard difficulties so have few that aren't. Not noticeable in the video, as the whole thing is a bit jittery, but my screen freezes very shortly when it happens. Perhaps beatmaps whose difficulties weren't processed yet? This was an issue before I installed the custom modes, so it isn't that.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/m_4GDX3gGaY
**osu!lazer version:** 
2020.421.0
01a5e40
**Logs:**
[database.log](https://github.com/ppy/osu/files/4517577/database.log)
[network.log](https://github.com/ppy/osu/files/4517578/network.log)
[performance.log](https://github.com/ppy/osu/files/4517579/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4517580/runtime.log)

**Comment by LittleEndu** [comment]
Are you sure you are not clicking on the difficulty icon? (It looks like you do on the video) That would change the selection to the difficulty you pressed regardless of what ruleset its from.

**Comment by IsaacElenbaas** [comment]
Ah, yup. Hadn't realized those take you to the specific diff. What are the greyed out ones (which switch my gamemode)? Are they not able to be converted? If so it makes sense to leave them there IMO, but a bit annoying when I accidentally click them.

**Comment by LittleEndu** [comment]
They are grey exactly because they could not be converted. Like there's no conversion algorithm from catch to taiko nor vice-versa.

**Comment by IsaacElenbaas** [comment]
Makes sense.
