### ISSUE TITLE
Taiko scoring on lazer is incorrect from osu!stable scoring

### ISSUE THREAD

**Issue by xTerraUWU** [ppy/osu#8839]
**Describe the bug:** 
So I was watching one of my replays from osu!taiko and while watching it the score was significantly different then what I had actually gotten in stable. I noticed this for other modes too, like mania, and catch the beat.
**Screenshots or videos showing encountered issue:** 
The first image shows my actual score I got on stable, the second shows the score in game on watching the replay
![A2FB87DF-9501-4125-B1D3-694470962115](https://user-images.githubusercontent.com/58949994/80009623-52a9a880-8497-11ea-85df-7e8e5d4db26b.png)
![885BE195-0BC4-48B7-8B80-19561413C022](https://user-images.githubusercontent.com/58949994/80009624-53423f00-8497-11ea-9b4e-dc80cbbadf57.png)

**osu!lazer version:** 
Latest version of lazer 2020.418

I could be wrong and that the scoring is meant to be like that but I may be wrong. It’s also not the 1 mil cap scoring system, it’s the old version

**Comment by bdach** [comment]
As far as I know lazer [intentionally does not implement the exact same scoring algorithm of stable even in osu!](https://github.com/ppy/osu/pull/8750#issuecomment-613157452) (and taiko's particular formula for score is not in the game sources, defaulting to standard's instead) to streamline the implementation and keep classic and standardised scores in the same ballpark, to avoid leaderboard order changing when switching between scoring modes.

Closing as mostly intended.
