### ISSUE TITLE
Allow bigger timeline skips in Editor while song is playing

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#8840]
In osu!stable, the mapping workflow for most mappers looks like this:

Play a song while rewinding it to listen to the same section on repeat and figure out how/when to place objects. This isn't currently possible in lazer because timeline jumps while a song is playing are too small.

In osu!stable this is handled with two separate values. One for paused songs which skips to the previous timeline tick, and a second for songs which are being played. I am unsure of the exact numbers osu!stable uses but parity would make the switch to lazer a lot smoother.

**Proposal designs of the feature:** Allow for bigger rewind jumps while a song is playing.

**Comment by peppy** [comment]
Yep, I stable has an increased rewind period when playing the track.

```csharp
if (AudioEngine.AudioState == AudioStates.Playing)
    rate *= (250 / (int)AudioEngine.BeatLength + 1);
```

Doesn't need to be implemented exactly the same as this code – just providing as a reference. This is applied to both backwards and forwards seeks.

**Comment by peppy** [comment]
Closed via https://github.com/ppy/osu/pull/10393
