### ISSUE TITLE
Taiko icons overlap

### ISSUE THREAD

**Issue by Tellilum** [ppy/osu#8844]
The drum icons overlap but only using this skin for an odd reason. https://mega.nz/file/jogFCSjb#U5bJXz3ZLUC30IBqbl133HfobPtY0bccdpgqiVA6Kyc

**Comment by peppy** [comment]
Please post a screenshot of what you are seeing.

**Comment by Fvern** [comment]
I just remembered I have a similar issue, so I'll just add on to this thread.
Taiko drums are not placed correctly on screen, and also overlap.
lazer:
![osu_2020-04-23_12-29-26](https://user-images.githubusercontent.com/25032854/80059350-5e13d700-855e-11ea-96c6-b02982c3225d.jpg)
stable:
![screenshot680](https://user-images.githubusercontent.com/25032854/80059411-826fb380-855e-11ea-968a-c504e0ff7ef3.jpg)

**Comment by peppy** [comment]
@Fvern  Could you please post your skin?

**Comment by Fvern** [comment]
https://drive.google.com/file/d/1FjLAzn0FXWqEp7i9vfaeN7X0NF3m8lFy/view?usp=sharing
4 mode mixed skin

**Comment by peppy** [comment]
Confirmed fixed via #8846 !

![image](https://user-images.githubusercontent.com/191335/80060170-d97a8600-8568-11ea-9243-3a2cb338b35c.gif)

**Comment by Luxiono** [comment]
Just to mention, this isn't the only skin. It also happens with the built-in osu!classic skin.

**Comment by peppy** [comment]
which is also fixed by the same fix linked above.
