### ISSUE TITLE
Mania doesn't factor DT/HT into scroll speed

### ISSUE THREAD

**Issue by cindsa** [ppy/osu#8851]
Right now when using Double Time / Half Time or any other speed modifier, scroll speed scales with it, making playing maps with double time impossible and with half time rather painful unless you adjust your scroll speed at the start of every map whenever you decide to play with ht/dt which is very inconvenient.

Played a map with nomod
Tried the same map with DT > having to spend time adjusting the scroll speed for it to be playable
Decided to play a different map with nomod/ht > having to spend time adjusting scroll speed back again for it to be playable.

People hop between maps they play with DT/Nomod/HT all the time, so having to adjust the scroll speed every single time is inconvenient and annoying. 

Would be nice having a "Scroll osu!mania scroll speed with BPM" option like in stable, or just not having DT/HT alter the scroll speed.

**Comment by peppy** [comment]
They should not be altering the scroll speed in the first place (the adjustment should be factored into the "base" scroll speed).
