### ISSUE TITLE
[SUGGESTIONS] Other Ruleset Accessibility 

### ISSUE THREAD

**Issue by MakcSan** [ppy/osu#8852]
**Describe the new feature:**  i saw the Custom Ruleset is start to spread (like tau! bosu! etc)
so i think we need Some accessibility for these,
1, **Importer of ruleset** (more easy to use custom ruleset i sometimes forced to update osu!lazer when i was installing some Custom ruleset and when i updated these rulesets were deleted (maybe cheat detection but its rule set)
By Using ruleset importer it detects is DLL file for only additonal ruleset and making sure not accessing to other things (because it may cause cheating with ruleset importer(or make fully support for Custom Ruleset by using some custom Formats or language (idk just custom things )to make ruleset)

2, **Custom Map of ruleset taggable**
_im really bad at english but yea_
it will allows you to ruleset tag a map you uploaded not only osu!standard osu!mania osu!taiko osu!CTB, also a **Custom ruleset tag**, beatmap uploader can use custom beatmap ruleset tag by using like "tau!"
This tag is shared between rulesets if tag is matched to ruleset side (Example"tau!") and beatmap side (Example"tau!") it will shown on osu!direct and also website would able to search by Ruleset tag

My personal comment:
Since osu! is looking to creativity by let peoples able to make custom maps, we need more creativity like minecraft modding so i think custom ruleset things were great idea also maybe a custom mods for fun(of course unranked))

**Proposal designs of the feature:** what do i have to say? :c

**Comment by MakcSan** [comment]
also im sorry if these features already exist or suggested

**Comment by peppy** [comment]
Ruleset "tagging" is already implemented. Import will come later via osu!direct. I do not want to make it more accessible until then due to security concerns.

**Comment by MakcSan** [comment]
what about importer of rulesets and custom mods?

**Comment by MakcSan** [comment]
also its feature suggestions you can make it anytime

**Comment by Coppertine** [comment]
Importing of rulesets have already been implemented and are going to be in the next version. Custom maps require a new file system (likely in json) for all the other types of beatmaps before they can get to rulesets.
