### ISSUE TITLE
Add a background video for the Showcase Scene on the lazer tournament client.

### ISSUE THREAD

**Issue by MiraiSubject** [ppy/osu#8854]
**Describe the new feature:** 
This feature would add a background video to the lazer tournament client in the same way it does currently to gameplay, schedule etc. 

**Proposal designs of the feature:** 

Right now I have an implementation in my own fork of osu! lazer that creates an Array of drawables with the TournamentLogo and TourneyVideo.
This is the before situation:
![osu!_2020-04-23_20-23-12](https://user-images.githubusercontent.com/803255/80135254-46f5d900-85a0-11ea-954d-540179d48175.png)

This is what it looks like with the feature implemented: 
![osu!_2020-04-23_20-11-33](https://user-images.githubusercontent.com/803255/80134210-b23eab80-859e-11ea-9d7d-ba7647846dde.png)

With chroma key implemented: 
![image](https://user-images.githubusercontent.com/803255/80139576-f46beb00-85a6-11ea-9996-a1a273fde6d0.png)

In this design the file is handled the same as all the TourneyVideos that are placed in "tournament/videos". The file in the directory will be called showcase.m4v. 

This is what it will looks like in a streaming program (stable runs here at a custom resolution of 1920x980 to completely fill the space):
![obs64_2020-04-23_20-53-43](https://user-images.githubusercontent.com/803255/80138084-8e7e6400-85a4-11ea-95d0-bf9d5b1807bb.jpg)

A possible side effect of this is that the user could get forced to offline mode when using this.

I've made a basic WIP implementation over here on a separate branch: https://github.com/MiraiSubject/osu/tree/showcase-video

**Comment by peppy** [comment]
If you already have a fork, why not PR the change following the way other screens do it?
