### ISSUE TITLE
osu!lazer doesn't load

### ISSUE THREAD

**Issue by CursedBM81** [ppy/osu#8855]
**Describe the crash:** 
I can't load osu!lazer at all.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
Newest version
**Logs:**

**Computer Specifications:** 
Windows 10

**Comment by bdach** [comment]
You have not provided enough information for us to begin investigating this problem (no logs, no hardware specs, no video). And I'm sure it's not a universal problem, as if it were, I would be expecting many more reports.

Closing until further details are provided.
