### ISSUE TITLE
ai player mod

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#8867]
the idea is that there will an ai playing at the same time as you play(with a ghost cursor), competing with you in realtime with the exact same mods you choose

you can set on how good the ai is with the customization options to set the star rating that ai can preform at where the ai will score about 95% at that level

if the ai fails, the ai fails

**Comment by Coppertine** [comment]
similar to #8658

**Comment by genericthing** [comment]
i was thinking of an ai to compete, it doesn't use your best score

i think we can have ghost, ai, and the player competing at the same time

**Comment by peppy** [comment]
Let's close this until #8658 is realised. This is too many levels deep (and would definitely be using the system implemented in #8658 to work).
