### ISSUE TITLE
When snapped to the beat, editor timeline hides current tick color

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8871]
**Describe the bug:** 
On the timeline, all ticks have their own color. The amount displayed is dependent on beat snap divisor and their color is an agreed upon convention. When your are snapped to the beat (music is stopped and you navigated the timeline using <kbd><</kbd> and <kbd>></kbd>) the current tick indicator hides the tick color.

**Screenshots or videos showing encountered issue:** 
I'm snapped to a blue tick aka 1/4 tick on both screenshots
![2020-04-26 21_24_56-osu!lazer](https://user-images.githubusercontent.com/11320483/80316148-ca176900-8804-11ea-8c5c-f298d7574c2f.png)
![2020-04-26 21_25_40-osu!cuttingedge b20200424 - ZYTOKINE - uni_Verse (Tracy Remix) (LittleEndu)  Mar](https://user-images.githubusercontent.com/11320483/80316150-caafff80-8804-11ea-93f5-c1a2ec24476e.png)

**osu!lazer version:** 
2020.421.0

**Comment by peppy** [comment]
We really want the ticks to be at the highest level here.
