### ISSUE TITLE
Custom tournament flags dont work

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#8890]
When placing a flag .png into the "Flags" (or "flags", but in the code its referenced as Flags) folder, and typing its name into the Flag area of the teams it just does nothing. (C:\Users\hubzi\AppData\Roaming\osu\Flags)

(didn't take image wide enough but it doesn't appear)
![image](https://user-images.githubusercontent.com/33783503/80499550-09f56200-8965-11ea-9461-460a6873c202.png)

Country flags work fine.

![image](https://user-images.githubusercontent.com/33783503/80499571-0f52ac80-8965-11ea-8dbf-dc5e4e485bbf.png)

Am i doing something wrong or is it just broken?

**Comment by jorolf** [comment]
The "Flags" folder you are mentioning is being loaded from the default resource store (in this case osu.Resources.dll) and not a flags folder from the storage directory.

**Comment by Hubza** [comment]
ah okay

**Comment by bdach** [comment]
Going to close this for now as custom flags are plainly not supported.

**Comment by peppy** [comment]
Actually you can use custom flags:

![image](https://user-images.githubusercontent.com/191335/80551652-2514b000-89ff-11ea-9748-0c7c715d1c9e.png)

You should place them inside a "tournament" folder along with other tournament resources. Note that built-in flags will take priority, so make sure to name it something unique, not a country acronym.

**Comment by Hubza** [comment]
aha, alright - thanks a bunch for explaining that
