### ISSUE TITLE
osu!taiko drum sprites are misaligned on legacy skins

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#8898]
**Describe the bug:** 

**Screenshots or videos showing encountered issue:** 

![Bug](https://user-images.githubusercontent.com/40500781/80606147-3c21c500-8a34-11ea-8a14-c7e0471ccd07.jpg)

**osu!lazer version:** 

2020.419.0

**Logs:**

**Comment by peppy** [comment]
Please describe your issues better.

**Comment by MTGPROD** [comment]
I'm sorry, I wanted to let you know quickly.

**Comment by peppy** [comment]
@MTGPROD can you reproduce this on the most recent release?

**Comment by enoslayd** [comment]
Isnt this #8681

**Comment by enoslayd** [comment]
Isnt this #8681?

**Comment by peppy** [comment]
Yes, quite possibly. If it's still reproducible I need some more details on how to do so.

**Comment by Fvern** [comment]
I'm experiencing this, in fact the same problem in issue in issue #8844, on the latest version (2020.429.0) where it was supposed to be fixed.
![osu_2020-04-30_18-57-55](https://user-images.githubusercontent.com/25032854/80703001-8da18100-8b14-11ea-8ad0-971985c88928.jpg)
Steps to Reproduce:
Use the skin I linked in the previous issue and play any map.

**Comment by enoslayd** [comment]
weird doesnt happen to me
![image](https://user-images.githubusercontent.com/41866328/80705105-6947a380-8b18-11ea-8e5c-968e36eee509.png)
![image](https://user-images.githubusercontent.com/41866328/80705134-75336580-8b18-11ea-99b3-8767ab67e74e.png)
![image](https://user-images.githubusercontent.com/41866328/80705153-7fedfa80-8b18-11ea-8102-17e1e0ad6418.png)
i even tried both skin on #8844 and it doesnt happen
2020.429.0

**Comment by Fvern** [comment]
I did

**Comment by Fvern** [comment]
Tried it, did not fix the issue.

**Comment by Joehuu** [comment]
Seems to happen when `Beatmap skins` is enabled.

**Comment by MTGPROD** [comment]
@peppy Same thing (I precise that i'm on Android) 
![Screen](https://user-images.githubusercontent.com/40500781/80781160-a68c4f80-8b71-11ea-91dc-31c876b9fa5c.jpg)

**Comment by MTGPROD** [comment]
@Joehuu Yes, you're right I deactivated beatmap skin and..
![Screen](https://user-images.githubusercontent.com/40500781/80781267-0f73c780-8b72-11ea-80e2-3ca1431d52a2.jpg)

**Comment by peppy** [comment]
I'll try and get to this, but if someone does happen to look into this before me, this is due to the skin version being read using the full fallback logic when we actually want to know the skin version-at-point-of-usage (in this case, the texture source).

Or maybe a better solution being that a beatmap should not be allowed to provide a skin version (needs regression testing if done this way).

**Comment by peppy** [comment]
Paper trail points to https://github.com/ppy/osu/pull/8643, which adds 1.0 fallback for the purpose of skins primarily (see linked issue). I'm wondering if we should just drop the version looking from `LegacyBeatmapSkin` for simplicity. @smoogipoo opinions? If we keep it, we're going to have to change the config lookup to be more like `GetSkinFromTextureLookup("texture").Configuration.LegacyVersion`..

**Comment by smoogipoo** [comment]
So the version would only come from the user skin? I think that's ok. Doesn't stable do that anyway?

**Comment by peppy** [comment]
I'd say stable also does this (the complex fallback logic doesn't look to be present at all in stable, probably with good reason).
