### ISSUE TITLE
Let the game running in background

### ISSUE THREAD

**Issue by SuperFat-Fat** [ppy/osu#8900]
**Describe the new feature:** 
I would love to see a setting that allows the gameplay to not pause when leaving the windows. Actually, when osu!lazer is no more the active windows, the gameplay stops automaticaly. 
But in fact, when using visualizer (like the Mvis ruleset), I can't let osu!lazer running on another screen and work... 

**Proposal designs of the feature:** 
A setting in "Gameplay" category labeled : "Pause the Gameplay when loosing the focus" or something like this !

**Comment by peppy** [comment]
This is an issue with the ruleset, not osu!. It should specify a replay so it will not pause.
