### ISSUE TITLE
The map list parallax can be dragged past it's limits

### ISSUE THREAD

**Issue by Panthr75** [ppy/osu#8902]
**Describe the bug:** 
When holding down the left mouse button and dragging, it "scrolls". This can lead to unintentionally dragging the parallax out of view.

**Screenshots or videos showing encountered issue:** 
[video.zip](https://github.com/ppy/osu/files/4555625/parallax.relaxed.zip)

**osu!lazer version:** 
2020.4.29.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/4555629/logs.zip)

**Comment by peppy** [comment]
This is due to https://github.com/ppy/osu-framework/pull/1408 and I swear an issue already exists covering it. Basically cursor confining is not implemented correctly for exclusive fullscreen.

**Comment by Gabixel** [comment]
You're probably talking about https://github.com/ppy/osu-framework/issues/2247 (seems to be the same issue)

**Comment by peppy** [comment]
Closing as duplicate of https://github.com/ppy/osu-framework/issues/2247.
