### ISSUE TITLE
Implement ability to close game during intro sequence

### ISSUE THREAD

**Issue by wisnoi** [ppy/osu#8904]
As it is, launching the game takes way too long before I can even close it. Closing also takes a significant amount of time. I believe it would be a helpful addition to be able to optionally make loading/exiting instant.

**Comment by peppy** [comment]
A disable option will not be added. The intro is integral to the game and also acts as a loading sequence.

If you are just interested in being able to close the application earlier, I am willing to leave this issue open and fix only that point (allow closing while intro is playing). How does that sound?

**Comment by wisnoi** [comment]
Sure! As it is, osu!lazer shows up in the Windows search menu before osu!, and muscle memory for typing "osu" and hitting enter means that I launch Lazer on accident.
I think this is a great compromise :) Thank you for the response
