### ISSUE TITLE
Store game data on a different folder on Android

### ISSUE THREAD

**Issue by MeguMario** [ppy/osu#8907]
**Describe the new feature:** 
Simply osu!lazer data folder in the root of internal storage or any folder other than /sdcard/Android/data (or /storage/emulated/0/Android/data)

**Proposal designs of the feature:** 
Store game data (and logs files) in a folder on the root of internal storage (like /storage/emulated/0/osulazer), this make accessing logs files easier, copying file from pc without going through so many folder, as well as going around Android 11 DP changes (apps no longer can access to other apps data & apps cache data, that means both /storage/emulated/0/Android and /storage/emulated/0/Android/data are impossible to access using normal file explorer)

**Comment by peppy** [comment]
This probably falls under https://github.com/ppy/osu/issues/960.

It will also likely change when we change iOS (as well) to use the system-documents folder for user file storage (https://github.com/ppy/osu/issues/7443).
