### ISSUE TITLE
Some dropdowns don't show selected option

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#8912]
**Describe the bug:** Some dropdowns don't show the selected option in the list until you change it manually (but the issue occurs again when re-launching the game).

**Screenshots or videos showing encountered issue:** 
These dropdowns seem to have this issue:
- Intro Sequence
![intro sequence](https://user-images.githubusercontent.com/43073074/80704057-32579a80-8ae4-11ea-8431-6f4ecc07e66d.png)
- Background Source
![background source](https://user-images.githubusercontent.com/43073074/80704615-32a46580-8ae5-11ea-83bd-f57c4b4bece1.png)

Expected Behaviour:
- Intro Sequence
![intro sequence](https://user-images.githubusercontent.com/43073074/80704729-641d3100-8ae5-11ea-92fb-56bef525af62.png)
- Background Source
![background source](https://user-images.githubusercontent.com/43073074/80704705-59fb3280-8ae5-11ea-809b-93d8c8f87153.png)

**Comment by smoogipoo** [comment]
Needs investigation but probably requires a framework fix.

**Comment by Joehuu** [comment]
Regressed since 2022.306.0 / https://github.com/ppy/osu-framework/pull/5054.

![osu!_2022-04-14_22-49-49](https://user-images.githubusercontent.com/35318437/163527065-d366996f-ffa0-4754-bb33-f39ed1e22782.gif)

**Comment by peppy** [comment]
I *thought* I was this recently but figured my eyes were playing tricks. Will investigate.
