### ISSUE TITLE
Ctrl+R To Restart Beatmap

### ISSUE THREAD

**Issue by Icymice** [ppy/osu#8916]
**Describe the new feature:** 
Allow players to quickly restart beatmaps by pressing Ctrl+R like in standard osu!
**Proposal designs of the feature:** 
Pretty self explanatory

**Comment by mouzedrift** [comment]
You can already do that in lazer (change your key bindings in the key configuration)
![osu!_AxUD8JKv5p](https://user-images.githubusercontent.com/43358824/80746827-c6485700-8b22-11ea-980e-6c4739c80af1.png)
