### ISSUE TITLE
Ignore preview points

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8918]
**Describe the new feature:** allow user to disable preview points (the one where a song starts from a certain point in song select). There will be several choices:

Default - default behavior
Only 1st preview - previews will use preview point only at the beginning of preview and after the song ends, will repeat the beginning of song
Disable - completely ignores preview point

**Proposal designs of the feature:** A dropdown box at the song select group in settings

**Comment by peppy** [comment]
I see this as unnecessary customisation, personally. If you want to listen to full songs using the main menu is recommended.

**Comment by enoslayd** [comment]
But maybe reconsider it? What if we want to repeat song?

**Comment by peppy** [comment]
It's a very common concept to repeat from the preview point, and gives the song select screen a feel of "selecting a song" to it. Changing this feels wrong to me.

**Comment by Joehuu** [comment]
> But maybe reconsider it? What if we want to repeat song? (Song select is the only way)

I think it should be implemented in the now playing overlay (with collections). Going with stable behavior, you can put one song in a collection and it'll repeat.

**Comment by peppy** [comment]
I'm going to close this one for now. We may revisit this at a later date, but song select audio behaviour is going to match stable for the time being.
