### ISSUE TITLE
Custom rulesets from folder load in ruleset tests

### ISSUE THREAD

**Issue by LumpBloom7** [ppy/osu#8927]
**Describe the bug:** 
During tests, rulesets are usually isolated when testing in the `TestSceneOsuGame`. After updating to `2020.429.0`, it is not the case anymore, and rulesets present in the `rulesets` directory also get loaded.

This doesn't cause any issues testing as the new test DLL takes priority over the same DLL within the `rulesets` folder.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/12001167/80867854-0f3a1000-8cc9-11ea-9577-1b2bd3328a7f.png)

**osu!lazer version:** 
2020.429.0

**Comment by peppy** [comment]
@smoogipoo what's your thought on this? currently because tests share the data folder, custom rulesets are inherently being loaded. is this incorrect? should we make an exception in `OsuTestBrowser` to not load user rulesets?

**Comment by smoogipoo** [comment]
I don't really see this as a bad thing...

**Comment by peppy** [comment]
Generally agree. We'll let it be until we (maybe?) isolate visualtests to its own data folder?

**Comment by peppy** [comment]
@LumpBloom7 can you confirm this isn't actually causing you any actual development problems and close the issue if so?

**Comment by LumpBloom7** [comment]
No it not directly causing any trouble, the current build always takes priority over the build in the rulesets directory.
