### ISSUE TITLE
Song remaining time doesn't represent real time when the song speed is modified

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#8929]
When you play a beatmap with double time or any mod that modifies playback speed, the time in the bottom corners is the normal time of the song duration but it goes by faster. I think it should represent the real time it takes to play the beatmap with the current speed value.

osu!lazer 2020.429.0

**Comment by LittleEndu** [comment]
For wind-up mod, little bit of algebra needs to be used when calculating the final duration. The resulting algorithm applies to all speed-up mods so this could probably just be slotted in as the calculation for all duration, including no-mod. The algorithm being: ``final_duration = 2 * original_duration / (initial_speed + final_speed)``

**Comment by LittleEndu** [comment]
Countdown during break time is also affected by speed modifications and also doesn't represent real time.

**Comment by bdach** [comment]
As a data point, music players (spotify/youtube/whichever) don't change the runtime if you set a custom playback speed, so I'm against this proposal.

**Comment by iiSaLMaN** [comment]
I agree with @bdach, Double-Time, Half-Time and other similar mods are more of changing the speed at which the clock advances rather than fully manipulating the displayed beatmap length while in-game, I would say if anything, just display the real-time duration next to the normal duration.

**Comment by Theighlin** [comment]
It didn't come to mind that music players too don't show the actual time the media will take to playback at set speed. I changed my mind on this so I'm okay with closing this issue unless someone wants to try adding an algorithm, even as a setting in the option (but that doesn't seem like a good idea either)

**Comment by Theighlin** [comment]
I want to add that i made this proposal because if you put a -x:xx time one would think that that is the time left until the end and when the speed is normal it does exactly that. I don't know if there are reasons why other media players don't do it but this was my thought process for this.

**Comment by peppy** [comment]
This is intentional.
