### ISSUE TITLE
Some form of parental controls

### ISSUE THREAD

**Issue by anexistantperson** [ppy/osu#8930]
**Describe the new feature:** 
There's a decently big sized portion of the osu! community that likes to make their map backrounds give 6 year olds the ability to open the game and think "ooooh tiddies :D"
Alot of parents wouldn't be fine with that, so I was thinking there could be some type of backround filter or other settings for parental controls.

**Proposal designs of the feature:** 
For the backround filter you could have multiple settings, never show backrounds ever anywhere, allow map creators to tag their backrounds as 18+, something like that, then make the game use an alternative backround for it. maybe decided by the skin or map.
For other types of parental controls I don't know what other things there could be.

**Comment by peppy** [comment]
We will probably add beatmap metadata to track "adult" content at some point, but not parental controls. This can be enforced by

- Watching over your children better
- Using OS level controls to prohibit osu! (if that is what you think if best for your children).

**Comment by peppy** [comment]
Here's a relevant issue I was trying to find earlier: https://github.com/ppy/osu-web/issues/5902?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDgxODc0ODY2MToxOTEzMzU%3D&notifications_after=Y3Vyc29yOjI1&notifications_query=repo%3Appy%2Fosu-web
