### ISSUE TITLE
Ruleset fails to load when version is changed

### ISSUE THREAD

**Issue by LumpBloom7** [ppy/osu#8936]
**Describe the crash:** 
A crash will occur when an ruleset gets updated with a different assembly version (File version, product version). Lazer treats such assemblies as completely new rulesets separate from the older version, and demands a unique ruleset shortname.

I have tested changing some properties in isolation and found that changing the `File Description`, `Product Name`, `Copyright` information doesn't affect lazer.

**Screenshots** 
Left (before, working), Right (after, broken)
![image](https://user-images.githubusercontent.com/12001167/80949983-a0bf9400-8e27-11ea-9612-35e9005eaa93.png)

**osu!lazer version:** 
2020.429.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4573662/runtime.log)

**Comment by peppy** [comment]
Dropping this one in current milestone as it should be a relatively easy fix.
