### ISSUE TITLE
Entering Song Select and leaving it a couple of times makes it crash

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#8942]
**Describe the crash:** 
Going to song select and leaving it a couple of times causes osu! to lock up really hard which also makes it crash after some time. can only reproduce with a big database
**Screenshots or videos showing encountered issue:** 
https://streamable.com/cawsb8 crash happens at arround 1:25
**osu!lazer version:** 
3bf58b7

**Logs:**
[network.log](https://github.com/ppy/osu/files/4577005/network.log)
[performance.log](https://github.com/ppy/osu/files/4577006/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4577007/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4577008/updater.log)
[database.log](https://github.com/ppy/osu/files/4577009/database.log)

**Computer Specifications:** 
i3 6100, 8GB RAM, Windows 10x 64 2004, GTX1050Ti

**Comment by bdach** [comment]
Direct cause is an obvious nullref here:

https://github.com/ppy/osu/blob/33f7e429a860ede4b5d1e317c0cfefd2d5f2e080/osu.Game/Screens/Select/DifficultyRecommender.cs#L89

Haven't tried to repro or checked why it's null. Could be a race against DI injecting the API provider, or it could be wrongly getting from the finaliser when `isDisposing = false`. Probably best to just guard and call it a day.

When it comes to overall song select performance, it's a little bit DB-limited right now. Some work has been done recently but further improvements in the future are certainly going to be looked at (regardless of whether we go forward with realm, or EF Core 3.1).

**Comment by LittleEndu** [comment]
If it's nullref at ``DifficultyRecommender``, it should be fixed by #8759
