### ISSUE TITLE
Add manual "Check for updates" button in settings

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#8947]
**Describe the new feature:** 
-------------------------------------
Some times the internet connection are unstable or too slow that take too long time to update, least I am.
The game are not trying to update everytime when start if you close it before downloading update finish

Please add a _**Check Update**_ button in settings below _**Open Osu! Folder**_ for manually start update or check update everytime the game starts

**Proposal designs of the feature:**
-------------------------------------

Add a _**Check update**_ button in settings below **_Open Osu! Folder_**
Check for update everytime the game starts

**Comment by bdach** [comment]
From what I can see the game *should* be checking for new updates every launch - but a manual check button might be an interesting proposal, I suppose.

**Comment by peppy** [comment]
Will eventually be added back, but super low priority. May be a good first issue for someone looking for something to do.

**Comment by kklosowski** [comment]
I'm looking to start contributing to the project and this seems like a great entry point. Mind if I have a go at it?
