### ISSUE TITLE
Rulesets can have access to the entire game components by DI

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#8954]
As per the title, this is very dangerous to users that like to download custom rulesets as there may be *troll rulesets* that do whatever they want with the user's game instance and data:
- by deleting all beatmap sets downloaded by the user.
- retrieving the `IAPIProvider` and performing unwanted web requests.
- spamming on chats with `ChannelManager` causing unfair mutes

or more bad / unwanted operations.

## My proposal

We should limit the dependencies inside the `Player`'s `CreateChildDependencies()` method to cache only simple, useful and non-harming components.

I was gonna go ahead with fixing this by the proposed way above, but the problem is what to cache and what not to cache.

IMO I think the following can be cached normally with the following reasons:
 - `TextureStore` – for retrieving the textures loaded inside the ruleset or provided by the skin.
 - `ISampleStore` – for retrieving the samples loaded inside the ruleset or provided by the skin.
 - `ITrackStore` – for retrieving the tracks loaded inside the ruleset or provided by the skin.
 - `FontStore` – for retrieving glyph stores to use for custom `SpriteText`s.
 - `ShaderManager` – for loading custom shaders or otherwise.
 - `OsuColour` – for using their provided colors or methods.
 - `ISkinSource` – for retrieving the current skin to use.

as for using potentially harmful components inside `Player`, passing it through the constructor or by setting it to a property added there are the best ways going forward.

**Comment by bdach** [comment]
Why is abuse being raised as a possibility now? Is there an actual ruleset that does things like that, or is it an imagined potential scenario?

**Comment by Game4all** [comment]
I would argue it is a bit early to raise such a concern now as there isn't a lot which has been done with rulesets yet but I agree in the end having a protection mechanism using a whitelist (or something so) to set dependencies which can be fetched may be eventually required as malicious extensions tend to appear in games / software which support user additions through code.

Sounds like something which could be done with a custom DependencyContainer and a bit of reflection.

**Comment by iiSaLMaN** [comment]
> Why is abuse being raised as a possibility now? Is there an actual ruleset that does things like that, or is it an imagined potential scenario?

It's just an imagined potential scenario, low priority for now but I think it's worth keeping track of it in a thread.

**Comment by peppy** [comment]
You could argue a ruleset could use reflection for similar purposes. This is out of scope for now.
