### ISSUE TITLE
Every kat sounds like a finisher if the map is mapped with whistles instead of claps

### ISSUE THREAD

**Issue by Firmatorenio** [ppy/osu#8955]
**Describe the bug:** Taiko: on Stable you can map kats by either putting a clap or a whistle on a circle, and in order to make a finisher kat you put either clap+finish or whistle+finish. Lazer doesn't read it well (or at least it doesn't with imported skins), and the ~15% of maps that players mapped with whistles become a hitsound mess.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=F6-0kmPuioU

**osu!lazer version:** 2020.429.0

**Comment by Firmatorenio** [comment]
Still happening as of 2020.515.0

**Comment by peppy** [comment]
Can you give more details? Has anything changed? In my testing it seemed to be resolved so any specific repro would be appreciated.

**Comment by Firmatorenio** [comment]
I'm quite unsure what else to provide, the only thing I note changed regarding what the notes sound like is that the actual kat finishers in the 'unaffected' maps now actually play a whistle sound (before they'd play clap+finish). The exact described in the issue's title problem still happens in both legacy and the default skin: https://www.youtube.com/watch?v=md7D2-X-rzI

Here's a small list of maps that this issue occurs in:
- pretty much all of my own taiko maps (https://osu.ppy.sh/users/4935188)
- searching for maps by "yassu-" generally brings up messed up things:
- - https://osu.ppy.sh/beatmapsets/739116#taiko/1565331
- - https://osu.ppy.sh/beatmapsets/725826#taiko/1532456
- - https://osu.ppy.sh/beatmapsets/539888#taiko/1144904
- - https://osu.ppy.sh/beatmapsets/953713#taiko/1991296
- searching for maps by "[Zeth]" generally brings up at least partially messed up things:
- - https://osu.ppy.sh/beatmapsets/866694#taiko/1943064
- - https://osu.ppy.sh/beatmapsets/868624#taiko/1815528
- - short parts of https://osu.ppy.sh/beatmapsets/925304#taiko/1954240
- - https://osu.ppy.sh/beatmapsets/949737#taiko/1983172
- some other examples
- - https://osu.ppy.sh/beatmapsets/44964#taiko/140655
- - https://osu.ppy.sh/beatmapsets/160466#taiko/394235
- - https://osu.ppy.sh/beatmapsets/55191#taiko/167980
- - https://osu.ppy.sh/beatmapsets/316779#taiko/705830

**Comment by peppy** [comment]
As far as I can tell the issue in your opening post has been resolved (logging and comparing sample playback in stable vs lazer for each combination of clap/finish/whistle)

What would be helpful:

- Making a test map with minimal hitobjects required to show the issue and attaching the .osu
- Making a video showing that test map sounding different in stable and lazer

**Comment by Firmatorenio** [comment]
Github doesn't let me attach weird file extensions, so puush links:
- [.osz](https://puu.sh/FLwnn/6743268842.osz) (with the .osu inside)
- just the [.osu](https://puu.sh/FLwsn/9daf2de9a1.osu)

And the [video](https://www.youtube.com/watch?v=fv1qFz5Q_j8).
I gave the same .osz to a friend and the [two small kats sound different for them on lazer as well.](https://www.youtube.com/watch?v=C4PwuGilJUU)

**Comment by Firmatorenio** [comment]
Seems to be resolved as of .523.0, thank you!

**Comment by bdach** [comment]
Good to hear, thanks for checking. This case has tests now, so closing for what is hopefully the last time!
