### ISSUE TITLE
Frame Drops on Moto z3

### ISSUE THREAD

**Issue by Inkninjaaa** [ppy/osu#8964]
This my first issue and my only issue, So on my phone the Moto z3 it's a pretty good phone for osu! and I'm coming back to osu after awhile and I downloaded the most recent version and after the intro my FPS was dipping is there anyway to fix this.

**Comment by bdach** [comment]
We are aware of performance issues on mobile devices. A significant amount of work has been done to optimise performance on all platforms, and it's a constant consideration.

However, there are not enough details given in this issue for it to be actionable - you haven't said exactly when the performance drops, how much does it drop by, provided any kind of video showing the problem, etc. As such I'm going to close this issue for now as we can't really address it - please watch this space for continued performance improvement.
