### ISSUE TITLE
osu terminates when returning to home screen on Android

### ISSUE THREAD

**Issue by chenxi050402** [ppy/osu#8967]
**Describe the bug:** 
osu terminates when returning to home screen on Android
**osu!lazer version:** 
2020.429.0
**Logs:**
[logs.zip](https://github.com/ppy/osu/files/4596772/logs.zip)
**Device:**
Xiaomi MIX 3
**System version:**
MIUI 11.0.2 (Android 10)

**Comment by peppy** [comment]
This is a known issue which we do not have a solution for just yet.
