### ISSUE TITLE
Deleted songs cant be "jump to" in osu!direct

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#8974]
**Describe the bug:** 
Currently when youre in osu!!direct and you stumble across a deleted song which is in your database there isnt a way to jump said song

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/17437302/81406343-ac69ce00-9139-11ea-8d88-ccc68b62f344.png)

The button should be accessable when you have the song.
its gone on the beatmap page fully as well. 

![image](https://user-images.githubusercontent.com/17437302/81406602-28fcac80-913a-11ea-90d7-40b33e65d2bf.png)

**osu!lazer version:** 
2d49210

**Logs:**
Shouldnt be needed?

**Comment by iiSaLMaN** [comment]
If this were to be applied, it should also be added inside the beatmap set overlay as well for consistency. maybe something like:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/22781491/81449623-54f34e80-9189-11ea-9f18-c1d7a4aaf209.png">

also the panel download button can be enabled if locally available, and with the same tooltip text:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/22781491/81453345-fd0d1580-9191-11ea-8491-be9ed87bd443.png">

**Comment by peppy** [comment]
way too verbose. if you have it locally the button should just open it and display whatever it normally does.
