### ISSUE TITLE
Long maps time out when loading through GetPlayableBeatmap with position-changing mods

### ISSUE THREAD

**Issue by stanriders** [ppy/osu#8976]
**Describe the bug:** Try to use `osu-tools simulate` command with http://osu.ppy.sh/b/1949106 and hard rock. It seems like its failing to convert all sliders in time because if you pause execution when its loading the map its always doing slider flipping.

**osu!lazer version:** 5ec8d4, 
**osu-tools version:** ecb290c

**Logs:**
```
Exception thrown: 'osu.Game.Beatmaps.WorkingBeatmap.BeatmapLoadTimeoutException' in osu.Game.dll
An exception of type 'osu.Game.Beatmaps.WorkingBeatmap.BeatmapLoadTimeoutException' occurred in osu.Game.dll but was not handled in user code
Timed out while loading beatmap (Aether Realm - The Sun, The Moon, The Star (ItsWinter) [Mourning Those Things I've Long Left Behind]).
```

**Comment by smoogipoo** [comment]
Does this happen on a release build?

**Comment by stanriders** [comment]
Yes
