### ISSUE TITLE
Replay issue

### ISSUE THREAD

**Issue by RiyadhAlmalki** [ppy/osu#8978]
**Describe the bug:**So, I’m a mobile player so i see a small circle size and it’s difficult to hit so i use dificulty adjust to make the circles bigger so what happened is i SS a map and i was so happy about it but i went to replay to record it and when i saw the replay the circle size back to normal and i saw multiple misses my acc drop from 100% to 86% if you see the video you will understand 

**Screenshots or videos showing encouraging  issue:* https://youtu.be/fPXK37LU3kk

** Lazer 2020.508.2 :** 

**Logs:** I don’t understand that

**Comment by cupppu** [comment]
Duplicate of #8569
