### ISSUE TITLE
Unable to use midi keyboard as an input device.

### ISSUE THREAD

**Issue by Kashouryo** [ppy/osu#8983]
**Describe the bug:** 
osu! can not create a keybind with my midi keyboard. I can see osu! is receiving midi events from the console. I also tried osu.Framework.Tests, which can successfully receive my midi input and show them on the screen.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/37679684/81481584-3b8ce980-91ff-11ea-9abb-116aff1b1fb1.png)

**osu!lazer version:** 
c9b1735

**Comment by bdach** [comment]
MIDI support still needs to be somewhat improved game-side. It makes sense that the bindings don't save as `KeyBindingRow` does not handle `OnMidi{Up,Down}`, so it might work once that is handled, but I don't know for sure as I don't own a MIDI device I can plug in to test. Further adjustments might be needed in individual rulesets.

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu/pull/8986
