### ISSUE TITLE
Stuck on black screen after the initial warning

### ISSUE THREAD

**Issue by Yoppez** [ppy/osu#8985]
**The issue:** 
After the "This project is an ongoing work in progress" text, the game freezes in a black screen.

**Screenshot:** 
![Istantanea_2020-05-10_00-18-35](https://user-images.githubusercontent.com/44178021/81488105-e929e800-9253-11ea-974d-7b39510eef01.png)

**osu!lazer version:**  2020.508.2

**Logs:**
[database.log](https://github.com/ppy/osu/files/4604935/database.log)
[network.log](https://github.com/ppy/osu/files/4604936/network.log)
[performance.log](https://github.com/ppy/osu/files/4604937/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4604938/runtime.log)

**Computer Specifications:** 
OS: Arch Linux
CPU: Intel Core i7-3770
RAM: 8GB
GPU: NVIDIA GeForce GTX 1650

**Comment by enoslayd** [comment]
Do you have ffmpeg installed?

**Comment by Yoppez** [comment]
Yes, I already have it for other software dependencies.

**Comment by bdach** [comment]
I'm going to hazard a guess that this will be due to the default device choice on linux being sometimes somehow wrong, which causes the intro track to not progress (#7970).

Please try editing the `~/.local/share/osu/game.ini` file and changing the  `IntroSequence = Triangles` to `Circles`.

**Comment by Yoppez** [comment]
Yeah, that worked, but now there are other problems:
1. The songs don't play on the menu and there are no sound effects;
2. The songs don't even play during the gameplay, and so the beatmaps remain in the beginning without starting.

**Comment by bdach** [comment]
Please try switching to other audio devices in the settings. From what other users have reported there should be something that works.

**Comment by Yoppez** [comment]
I switched to PulseAudio and Jack and now everything works fine. I even switched back to "Triangles" intro sequence without problems. Like you said, it seems a problem with osu that cannot correctly recognize the default audio device. Thanks a lot!

**Comment by bdach** [comment]
Good to hear.

Closing - let's track this framework-side at ppy/osu-framework#3297.
