### ISSUE TITLE
FPS Counters Moving to where screen is Scaled to

### ISSUE THREAD

**Issue by WhiteRedWolf** [ppy/osu#8987]
**Describe the new feature:** 
Addition to normal Screen Scaling, FPS Counters Moving to where the Screen is being scaled to

**Proposal designs of the feature:** 

So Currectly, you can Scale and move the enitre Screen Around in the Settings Menu, which is convinient for me because my monitors Left Side is somewhat broken,
What would be nice to have would be the FPS Counters moving to where the Screen Boundaries are, currently they are at the very bottom right edge of the Screen, it would be nice for them to move to where ever the bottom left of the screen is after Screen Scaling.

Here are some edited Screenshots to describe better what i mean:

This is how things are currently:
![currently](https://user-images.githubusercontent.com/33634370/81508644-93ae1380-9305-11ea-992b-ec032662f031.jpg)

How it would be better:
![like this](https://user-images.githubusercontent.com/33634370/81508652-9dd01200-9305-11ea-927f-ab685d4c593d.jpg)

**Comment by GSculerlor** [comment]
I believe it caused by frame counter overlay is not inside scaling container (it's way higher in hierarchy)

**Comment by peppy** [comment]
The fps display is a framework component. It should not be moving with a game's display. Eventually osu! may provide its own.
