### ISSUE TITLE
Alt-F4 during osu! intro hangs game

### ISSUE THREAD

**Issue by SpikeyScout** [ppy/osu#8991]
**Describe the crash:** 
Alt-F4ing during the osu! intro (where "welcome to osu!" is said) causes the game to hang
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=HLXDhFnTK6o
**osu!lazer version:** 
2020.508.2
**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4607555/runtime.log)
[network.log](https://github.com/ppy/osu/files/4607556/network.log)
[performance.log](https://github.com/ppy/osu/files/4607557/performance.log)

**Computer Specifications:** 
1070ti, AMD Ryzen 5 2600, 16GB ram, Windows 10 Home 1909

**Comment by smoogipoo** [comment]
Fixed via https://github.com/ppy/osu/pull/8982 but there hasn't been a release yet.
