### ISSUE TITLE
Long freezes after playing for a period of time

### ISSUE THREAD

**Issue by Snowbush** [ppy/osu#8992]
**Describe the bug:** 
After about 10-15 minutes of playing the game will start to slowly freeze for a few frames then a few minutes later the game starts to freeze up every second for a few seconds. Game usually starts with about 800mb of memory used then after a few songs and scrolling through the song list memory usage gets higher and higher
System:
i5 4670
8GB of RAM
GTX 745

**Screenshots or videos showing encountered issue:** 
https://imgur.com/a/Hdyb3qI
https://gyazo.com/01bda4ca0961f9fe71ad41a6cddac3f8 (gif of the game freezing) 

**osu!lazer version:** 
2020.508.2
**Logs:**

**Comment by peppy** [comment]
Please attach logs. Also note that 2.7gb is not necessarily a "leak" and may be normal operation, so please don't jump to a conclusion.

**Comment by Snowbush** [comment]
https://github.com/ppy/osu/files/4607551/network.log
https://github.com/ppy/osu/files/4607550/database.log
https://github.com/ppy/osu/files/4607549/updater.log
https://github.com/ppy/osu/files/4607548/runtime.log
https://github.com/ppy/osu/files/4607547/performance.log

**Comment by peppy** [comment]
Could you please reproduce the freezing behaviour, but open Ctrl+F2 before a freeze. Once it freezes once, you should see new log files generated (performance-update / performance-draw etc.) so please also attach those.

**Comment by Snowbush** [comment]
https://github.com/ppy/osu/files/4607637/performance-update.log
https://github.com/ppy/osu/files/4607638/performance-draw.log

**Comment by Snowbush** [comment]
The freeze above happened in the menu I can reproduce it in a beatmap as well if required

**Comment by Snowbush** [comment]
changing my framerate limiter from 4x to 2x seems to have fixed the problem had maybe 1 stutter in like 45 minutes

**Comment by bdach** [comment]
@Snowbush Could you double-check whether this is still an issue? There were some changes that could have ended up resolving this.

**Comment by Snowbush** [comment]
> 
> 
> @Snowbush Could you double-check whether this is still an issue? There were some changes that could have ended up resolving this.

It appears to be fixed. I set the frame limiter both to 4x and unlimited and the game seems to run fine after about an hour. After playing the game for about an hour I it froze 3 times all of them a few minutes apart rather than it consistently happening seconds apart. Ill still attach the log files if you do need them 
[network.log](https://github.com/ppy/osu/files/5256956/network.log)
[performance.log](https://github.com/ppy/osu/files/5256957/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5256958/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5256959/updater.log)
[database.log](https://github.com/ppy/osu/files/5256960/database.log)

**Comment by bdach** [comment]
Thanks. Nothing jumps out to me in particular in the attached log, so I'll tentatively close for now. Please let us know if this returns at some point.
