### ISSUE TITLE
Font fallback

### ISSUE THREAD

**Issue by VBChunguk** [ppy/osu#9]
Currently the font face is hardcoded as Exo. But it rarely contains foreign characters like CJK glyphs, so we need font fallback system. My idea is:

1. Find the glyph in Exo.
2. If it is not found, we need to fallback to system fonts. Iterate over the fallback list until the glyph is found. Fallback list will be written in font priority order.
  - In Windows, maybe we can find appropriate font in the system fonts folder. Run `System.Environment.GetFolderPath(System.Environment.SpecialFolder.Fonts)` and get the folder path.
  - In Linux, we can either run `fc-match` or use fontconfig library directly.

## Font fallback in Windows
We need font file name because we are using FreeType for text rendering. However, .NET Framework does not provide the file name of fonts. File names of the installed fonts can be found in the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`. In Windows without fontconfig, we should find the font file name in the registry. Maybe we can cache the font list at startup and use it.

Any feedback or suggestions are welcome.

**Comment by peppy** [comment]
Fonts (truetype) are planned to be removed in the coming days. This should not be an issue once this is complete.

**Comment by VBChunguk** [comment]
Then what will be used for text rendering?

**Comment by peppy** [comment]
sprite-based fonts

**Comment by VBChunguk** [comment]
Then we'll get an image file that contains all glyphs. Okay, I'll close this issue.
