### ISSUE TITLE
delay resuming gameplay or countdown after unpausing

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#9004]
**Describe the new feature:** i was thinking that std had that mechanic long ago (with the click to resume) but the other rulesets dont. so there are two ideas that i want to share for other rulesets (and maybe, custom rulesets as well????)

1. delay resuming the gameplay after unpausing like in stable but a little longer. stable has a 500ms (i think?) delay before resuming a game after unpausing. maybe make it a little longer like 700ms to 1.2 secs. (good for taiko and maybe catch???)

2. countdown. like the 3 2 1 when starting old beatmaps but instead of same speeds, make it bpm dependent (e.g slower for lower bpm and faster for higher bpms) but theres a limit. like if the bpm is 120 and below, it will use the same speed as 120 bpm and if bpm is 300 or higher, will use the 300 bpm speed instead. or you could just ignore the bpm thing and go for the old starting countdown speed. (good for mania or catch)

**Comment by peppy** [comment]
Resuming intentionally has no countdown. Pausing is not supposed to be something you do often.

**Comment by enoslayd** [comment]
>Pausing is not supposed to be something you do often.

Not me though since im always interrupted while playing any game

**Comment by peppy** [comment]
You will need to learn to live with that then. We will be making resuming harder if anything, not easier.

**Comment by enoslayd** [comment]
But std-

**Comment by peppy** [comment]
osu! ruleset requires you reposition your cursor where it used to be to avoid using pausing as a cheesing method. in the future the same may be applied to other rulesets (require the same keys to be re-pressed before resuming).
