### ISSUE TITLE
Can't serialize EZ mod

### ISSUE THREAD

**Issue by stanriders** [ppy/osu#9006]
**Describe the bug:** Serializing ModEasy into json fails on AllowFail

**osu!lazer version:** 5ec8d4

**Logs:**
```
Exception thrown: 'System.NullReferenceException' in osu.Game.dll
**health** was null.
```

**Comment by peppy** [comment]
Where are you seeing this exception occur? In a multiplayer lobby?

**Comment by stanriders** [comment]
Modified osu-tools. All other mods seem to be serializing properly
