### ISSUE TITLE
Unhandled exception: There is not enough memory available for this task.

### ISSUE THREAD

**Issue by MiraiSubject** [ppy/osu#9008]
**Describe the crash:** 

After updating to 2020.508.2 in-game. The game booted up shortly with a black screen and then crashed. The same happened with a build using the commit that I listed below. 

This happened on a setup that had maps and skins, but after resetting all of it (removing %AppData%/osu) the issue persists. 

**Screenshots or videos showing encountered issue:** 

System load when trying to run lazer: 

![image](https://user-images.githubusercontent.com/803255/81752011-e546d180-94b0-11ea-95fa-bb10b0b0a77b.png)

**osu!lazer version:** 

2020.508.2 & https://github.com/ppy/osu/commit/ab9149844af06a2a15dcab2c7f880b94dc6f73ee

**Logs:**

[performance.log](https://github.com/ppy/osu/files/4618759/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4618760/runtime.log)
[network.log](https://github.com/ppy/osu/files/4618761/network.log)

**Computer Specifications:** 

Windows 10 Pro x64 Version 2004 Build 19041.207
AMD Ryzen 7 1700
48 GB of RAM
Nvidia GTX 1080ti
Lazer is stored on an nvme drive.

**Comment by bdach** [comment]
This looks somehow related to MIDI support? It's so early in initialisation that I would really be surprised if it wasn't.

```
2020-05-12 22:25:36 [error]: System.ComponentModel.Win32Exception (7): There is not enough memory available for this task.  Quit one or more applications to increase available memory, and then try a (7)
2020-05-12 22:25:36 [error]: at Commons.Music.Midi.WinMM.WinMMMidiInput.DieOnError(Int32 code)
2020-05-12 22:25:36 [error]: at Commons.Music.Midi.WinMM.WinMMMidiInput..ctor(IMidiPortDetails details)
```

It's got to be either one of these:

https://github.com/atsushieno/managed-midi/blob/6b197af3ac2354067934a3af966633b19171a804/Commons.Music.Midi.DesktopShared/winmm/WinmmMidiAccess.cs#L89-L92

Do you have any MIDI devices plugged in?

**Comment by MiraiSubject** [comment]
Oh yes! I actually do have a MIDI device plugged in. It's the [Launchpad MK II](https://novationmusic.com/en/launch/launchpad-mk2) to be specific.

**Comment by iiSaLMaN** [comment]
Out of curiosity, do you have another program running that opened and receives input from your MIDI device? ([found this while doing a quick search in the underlying library](https://stackoverflow.com/questions/27407784/mmsyserr-nomem-when-calling-midiinopen-only-when-other-midi-apps-are-open))

**Comment by MiraiSubject** [comment]
Yes I do have another program running that is using the device. After closing it, I was able to boot up lazer as normally yeah.

**Comment by bdach** [comment]
While exclusive MIDI input is probably something we won't be able to work around it would be good to not have the game catch fire immediately if it is already using it.
