### ISSUE TITLE
Easy & Target mod description added

### ISSUE THREAD

**Issue by Kontorted** [ppy/osu#901]
Modifications done to OsuMod.cs

`
public class OsuModEasy : ModEasy
    {
        public override string Description => @"Reduces overall difficulty - larger circles, more forgiving HP drain, less accuracy required.";
        public override double ScoreMultiplier => 0.5;
    }
`
https://puu.sh/wbcXL/70a2b4d61b.png

`public class OsuModTarget : Mod
    {
        public override string Name => "Target";
        public override FontAwesome Icon => FontAwesome.fa_osu_mod_target;
        public override string Description => @"Train your BPM consistency";
        public override double ScoreMultiplier => 1;
    }
`
https://puu.sh/wbcYa/9ff311543a.png

**Comment by ColdVolcano** [comment]
You could just open a pr with these changes you know?

**Comment by peppy** [comment]
as above
