### ISSUE TITLE
Bug in taiko osu classic skin

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu#9010]
**Describe the bug:** 

- Change skin to **osu!classic** skin.
- Choose **osu!taiko** mode.
- Play any beatmap.
- The taiko skin is not align.

**Screenshots or videos showing encountered issue:** 

[![taiko](https://files.catbox.moe/a0bs87.png)](https://files.catbox.moe/gfb2ou.mp4)

(Click the image to watch video)

**osu!lazer version:** 

- 2020.508.2
- Linux Ubuntu 20.04.
- Resolution 1920x1080.

**Logs:**

- [database.log](https://files.catbox.moe/ejjuda.log)
- [network.log](https://files.catbox.moe/iqao9z.log)
- [performance.log](https://files.catbox.moe/ailckm.log)
- [runtime.log](https://files.catbox.moe/zgzoes.log)

**Comment by peppy** [comment]
Duplicate and already fixed on master https://github.com/ppy/osu/issues/8898

Will be fixed in the next release.
