### ISSUE TITLE
Selecting a beatmap changes currently active ruleset sometimes

### ISSUE THREAD

**Issue by santerinogelainen** [ppy/osu#9017]
**Describe the bug:** 
I play taiko and standard and sometimes when selecting a beatmap while playing taiko, the game will change the ruleset to standard and vice versa. I seem to remember this happening with other rulesets too, even though I do not play them. I have a suspicion this has something to do with the "Show converted beatmaps" option when it is disabled but haven't figured out exactly why this happens. This has been happening as long as I can remember.

**Screenshots or videos showing encountered issue:** 
[https://www.youtube.com/watch?v=IrfGU4UDrtE](https://www.youtube.com/watch?v=IrfGU4UDrtE)

**osu!lazer version:** 
2020.508.2

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4624338/runtime.log)

**Comment by GSculerlor** [comment]
That's because you click on osu difficulty icon. Same issue with #8838

**Comment by bdach** [comment]
Closing as duplicate/explicitly intended.

**Comment by Firmatorenio** [comment]
Maybe a less annoying approach would be to make it so clicking on the difficulty icon doesn't make you switch to that specific difficulty unless the song is already selected?

**Comment by peppy** [comment]
I think it may be enough to make it much more obvious that the difficulties are buttons (some kind of hover effect). This is the intended direction, we'll see how things are after that is eventually implemented.

**Comment by frenzibyte** [comment]
Looking to add that temporary visual feedback until the song select redesign UX happens, does this sound fine?

https://user-images.githubusercontent.com/22781491/125174725-2a0eeb00-e1d0-11eb-9d66-8dc8363eb919.mp4

**Comment by smoogipoo** [comment]
This has come up before and I vehemently disagree that making it more "visually button-y" is a solution. In cases where this comes up (i.e. where I've had it happen to me), people aren't even aware of where their cursor is, they're just clicking on a massive panel while just looking at the leaderboard/detail;s and expecting it to select the beatmap and nothing more.

The solution for me, which has been discussed before, is to stop those buttons from selecting unless the beatmap is already selected.
