### ISSUE TITLE
Suggestion: Make custom mods listings

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu#9019]
**Describe the new feature:** Make custom mods listing for all players and treat them like unranked mods.

**Proposal designs of the feature:** A special page where located all custom player mods, which can be downloaded and installed by anybody, like Terraria's tModLauncher.

**Comment by peppy** [comment]
This is out of scope for the foreseeable future. We will have rulesets downloadable, but mods should be merged into the repository.
