### ISSUE TITLE
Make rate adjustment setting on daycore and nightcore mod adjust pitch, not just rate

### ISSUE THREAD

**Issue by WRMSRwasTaken** [ppy/osu#9025]
**Describe the new feature:** 
When enabling the Daycore or Nightcore mod and adjusting the speed decrese / increase with the Difficulty Adjust mod, it would be great in my opinion to change the pitch instead of just adjusting the song's speed with a fixed lower/higher frequency which sounds a bit weird in my opinion. Half time and double time already have a fixed frequency with different speeds.

This is already the case with the Wind Down or Wind Up mod, where changing the Final rate on both mods changes the pitch of the song.

**Proposal designs of the feature:** 
Just a code change, no new design elements needed.

**Comment by peppy** [comment]
The current implementation was done so with intention. It's really a matter of opinion as to which is more correct. Will leave this open for future discussion.

**Comment by WRMSRwasTaken** [comment]
Looking at the latest lazer release (or 1-2 before that) a checkbox "Adjust pitch" has been added to the Wind up and Wind down mods, maybe could be added to daycore & nightcore mods aswell (unchecked by default)?

**Comment by prismotizm** [comment]
Artificially stretching audio also causes distortion & major loss in quality so having this as an option would be amazing, especially for people who would use Nightcore instead of DoubleTime on stable just because the audio sounded cleaner.
