### ISSUE TITLE
Beatmap listing search options not fully implemented

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#9030]
lazer:
![image](https://user-images.githubusercontent.com/1329837/82022082-0254ed80-96c7-11ea-9858-b2fc734a825a.png)

web:
![image](https://user-images.githubusercontent.com/1329837/82021994-d5a0d600-96c6-11ea-9fb5-ec7c4b2be173.png)

**Comment by vruss** [comment]
Currently, the Genre and Language filters seem to be not implemented as well. Does this issue cover both implementing the new Extra, Rank Achieved, Played and General filters, and fixing the old ones?

Or is it enough to just add them new filters visually with no functionality implemented like the rest of the filters?

**Comment by peppy** [comment]
Genre and language are now implemented via https://github.com/ppy/osu/pull/7924, but this issue still remains valid.

**Comment by Joehuu** [comment]
The remaining filter (general) was added in https://github.com/ppy/osu/pull/12190, closing.
