### ISSUE TITLE
undefined parameters error

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#9040]
error occurred when using osu!direct(game started having massive lag spikes when scrolling up through osu!direct in the loved section, sorted by difficulty, filtered by osu!catch. game kept having massive lag spikes until game was quit then the error below appeared)

![error](https://user-images.githubusercontent.com/44514667/82085566-ddef1600-96b2-11ea-9f5d-29f10873c32e.PNG)
[performance.log](https://github.com/ppy/osu/files/4636543/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/4636544/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4636545/performance-draw.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4636546/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/4636547/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4636548/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4636549/performance-gamethread.update.log)
[performance-update.log](https://github.com/ppy/osu/files/4636550/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/4636551/runtime.log)
[database.log](https://github.com/ppy/osu/files/4636552/database.log)
[network.log](https://github.com/ppy/osu/files/4636553/network.log)

version this error occurred in: 2020.515.0

**Comment by bdach** [comment]
Can't reproduce this. Logs don't seem to show anything useful (mind you, the performance logs are stale, dating back to April or even last year).

Please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by genericthing** [comment]
[events.zip](https://github.com/ppy/osu/files/4636876/events.zip)

**Comment by bdach** [comment]
Well, there is *something*, but nothing really that helpful that would help nail this down...

```
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFA0D900F8B (00007FFA0D770000) with exit code c0000005.
```

`0xc0000005` is an access violation, but we knew it was that error code already, and the IP value gives us nothing... If I were to debug this myself the next step would be to run [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) next and see what this fails on but it's not exactly an easy-to-use tool.

**Comment by genericthing** [comment]
i tried replicating the error but the error seems to be a one-off thing

i think this issue should be closed until/unless someone else discovers this error
