### ISSUE TITLE
Lazer doesn't open most of the time and if it does it opens without any image

### ISSUE THREAD

**Issue by OGSense** [ppy/osu#9044]
every time I open Lazer, the screen goes black and eventually closes itself, 1/20 times it opens succesfuly, tried reinstalling, and updating my drivers yet id still didi't work

**Comment by bdach** [comment]
Please attach logs as requested in the issue template, state your platform and system specifications.

**Comment by OGSense** [comment]
![Captur](https://user-images.githubusercontent.com/65460985/82126639-33f4b400-97ae-11ea-96c9-0c8dcd003c08.PNG)
GPU: Nvidia GeForce 1060 6GB 
CPU: i3 8100

**Comment by frenzibyte** [comment]
Isn't there any log files in the log folder? (at `%AppData%\osu\logs`)

**Comment by OGSense** [comment]
In the osu folder yes, but in the lazer folder there isn't one in the osu folder there is a file named runtime

**Comment by bdach** [comment]
Please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by OGSense** [comment]
https://drive.google.com/file/d/19XM9lt5dGoZfa0i5xKOKzPRxDLfVvNPi/view?usp=sharing
I cant find a way to attatch a .evtx to this thread so im sharing it through drive

**Comment by bdach** [comment]
NVIDIA OpenGL drivers seem to be at fault here.

```
Unable to recover from a kernel exception. The application must close.

Error code: 3 (subcode 7)
 (pid=23976 tid=24024 osu!.exe 64bit)

Visit http://www.nvidia.com/page/support.html for more information.
```

Given that you've already tried to update drivers and it didn't help I'm not sure what more can be done here. You could try reporting the issue to NVIDIA, but I'm afraid we're not going to be easily able to help diagnose this without your exact hardware.

Closing for now. (FWIW this isn't the first time I've seen something of the sort - see #8510.)
