### ISSUE TITLE
Cursor is blocked by drained part of the HP bar

### ISSUE THREAD

**Issue by TheUnkn0wnN00b** [ppy/osu#9046]
**Describe the bug:** 
When moving the cursor over parts of the HP bar that have drained, the path of the HP bar blocks the cursor.
**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/xs7sE7i.png
Issue persists with default and all legacy skins.
**osu!lazer version:** 
2020.515.0

**Comment by peppy** [comment]
All HUD elements are rendered above gameplay, so this is actually an intentional design decision. It will probably look more appropriate with the next HUD iteration, which will make this more obvious.
