### ISSUE TITLE
osu! Crash on startup, no log files were generated

### ISSUE THREAD

**Issue by nate-moo** [ppy/osu#9060]
**Describe the crash:** 
I double click the application/shortcut and osu! will open, say welcome and crash, sometimes making it to the login screen. logs aren't generated

Depending on where i launch it from (shortcut, start menu, or the exe file) it will last a different amount of time until crash. but it will always crash

**Screenshots or videos showing encountered issue:** 
[Youtube link to video](https://youtu.be/2HsohPsfr_8)

**osu!lazer version:** 
2020.515.0

**Logs:**

No Log files were generated

**Computer Specifications:** 
64-Bit Windows 10 Pro
AMD Ryzen 5 2600 @ 2.40GHz
Nvidia RTX 2060
16gb G.Skill Aegis DDR4 RAM
32in 1440p monitor

**Comment by frenzibyte** [comment]
You're in the wrong repo, here you should be posting issue about osu!lazer only, can be transferred to https://github.com/ppy/osu-stable-issues (where issues about osu!stable reside there).

**Comment by nate-moo** [comment]
> You're in the wrong repo, here you should be posting issue about osu!lazer only, can be transferred to https://github.com/ppy/osu-stable-issues (where issues about osu!stable reside there).

Sorry, ill do that there. my bad
