### ISSUE TITLE
osu!Lazer 2020.515.0 freezes on startup

### ISSUE THREAD

**Issue by IronBeagleonosu** [ppy/osu#9069]
**Describe the crash:** 
Whenever I open osu!Lazer it displays 'welcome to osu' and freezes
**Screenshots or videos showing encountered issue:** 
![welcometoosu](https://user-images.githubusercontent.com/65661892/82445603-6996e700-9aa5-11ea-928a-bd2206db0822.png)
**osu!lazer version:** 
2020.515.0
**Logs:**

[updater.log](https://github.com/ppy/osu/files/4656760/updater.log)
[database.log](https://github.com/ppy/osu/files/4656761/database.log)
[performance.log](https://github.com/ppy/osu/files/4656762/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4656763/runtime.log)
**Computer Specifications:**

**Comment by peppy** [comment]
Do you hear any sound?

**Comment by IronBeagleonosu** [comment]
> Do you hear any sound?

No, nothing at all

**Comment by bdach** [comment]
This isn't something I've seen before:

```
2020-05-20 12:13:54 [error]: Beatmap failed to load
2020-05-20 12:13:54 [error]: System.ArgumentNullException: Value cannot be null. (Parameter 'stream')
2020-05-20 12:13:54 [error]: at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
2020-05-20 12:13:54 [error]: at osu.Game.IO.LineBufferedReader..ctor(Stream stream, Boolean leaveOpen)
2020-05-20 12:13:54 [error]: at osu.Game.Beatmaps.BeatmapManager.BeatmapManagerWorkingBeatmap.GetBeatmap()
```

Immediate cause is probably that failing to load the audio track which makes the intro not progress, but the question is what caused the underlying stream to be `null`...

**Comment by smoogipoo** [comment]
The database log looks somewhat relevant here, though it seems to be from a previous instance. @IronBeagleonosu please provide your client.db file.

**Comment by peppy** [comment]
Sounds like the files folder may have been purged by the user while the database being retained. @IronBeagleonosu did you happen to touch the lazer files in some way (or maybe move some yourself)?

**Comment by IronBeagleonosu** [comment]
I haven't touched the lazer files, just downloaded it and tried to start it.
Github won't let me attach my client.db file.

**Comment by smoogipoo** [comment]
Github will allow you to attach it inside a .zip.

**Comment by IronBeagleonosu** [comment]
[client.zip](https://github.com/ppy/osu/files/4661335/client.zip)

**Comment by IronBeagleonosu** [comment]
Good news! Apparently Lazer fixed itself
