### ISSUE TITLE
Setting to choose between the "old" (stable) osu menu and the lazer one

### ISSUE THREAD

**Issue by kolikisabaddev** [ppy/osu#9074]
That would be cool to have a setting to choose between osu's stable menu or the lazer one beacuse i prefer the old one and i don't think im the only one to think this.
Thanks, kolikisabaddev
Oh and i know that would be really hard/long to add this feature

**Comment by bdach** [comment]
I am pretty sure the old stable song select design will not be returning to lazer.

If there are some specific UX problems with the new design, then feel free to submit proposals/feedback as to how to improve the current general experience - but if you'd like it back purely for the sake of preserving the status quo, then I'm afraid you'll have to get used to it.
