### ISSUE TITLE
Sending a direct message to a friend resulting in "Posting Message Failed"

### ISSUE THREAD

**Issue by EZ2ACTux** [ppy/osu#9076]
**Describe the bug:** 
As the title suggests, if I attempt to send a private message to someone on my friends list (and they haven't opened a dialog with me first, the error only happens if I try to open a dialog) attempting to send a message pulls up the notifications shade stating that "Posting Message Failed". I have attempted to restart the program with the same results.

Upon looking through the log files I noticed some API forbidden errors. I will attach all log files to this post. This particular errors were located in runtime.log

**Screenshots or videos showing encountered issue:** 
![osu_2020-05-21_17-38-47](https://user-images.githubusercontent.com/10949323/82527356-5ad63000-9b8a-11ea-95d5-f13bb7472aee.jpg)

**osu!lazer version:** 
2020.515.0
**Logs:**
[network.log](https://github.com/ppy/osu/files/4660766/network.log)
[runtime.log](https://github.com/ppy/osu/files/4660760/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4660762/updater.log)
[database.log](https://github.com/ppy/osu/files/4660763/database.log)
[performance.log](https://github.com/ppy/osu/files/4660765/performance.log)

**Comment by Game4all** [comment]
Looking at _network.log_ , here's the relevant exception:
```
2020-05-21 05:32:04 [verbose]: Performing request osu.Game.Online.API.Requests.CreateNewPrivateMessageRequest
2020-05-21 05:32:04 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/new failed with System.Net.WebException: Forbidden.
2020-05-21 05:32:04 [verbose]: Response was: {"error":"You do not have access to that channel."}
2020-05-21 05:32:04 [verbose]: Failing request osu.Game.Online.API.Requests.CreateNewPrivateMessageRequest (osu.Game.Online.API.APIException: You do not have access to that channel.
2020-05-21 05:32:04 [verbose]: ---> System.Net.WebException: Forbidden
2020-05-21 05:32:04 [verbose]: --- End of inner exception stack trace ---)
```
Looks like the channel failed to create.

**Comment by EZ2ACTux** [comment]
Interesting.

What I find rather strange is that my friend was able to send a message to me from lazer and I was able to reply but if I wanted to try and open a chat with him it threw this error. So he had no trouble messaging me from lazer but after I accidentally closed his chat tab and went to reply to him in a new chat tab (losing my chat history as well but that may be intended behavior) it started doing this

**Comment by peppy** [comment]
Do they have non-friend PMs blocked? And you aren't added as a friend?

**Comment by EZ2ACTux** [comment]
> 
> 
> Do they have non-friend PMs blocked? And you aren't added as a friend?

We're mutual friends so it shouldn't be a problem

**Comment by EZ2ACTux** [comment]
Ok so update. It looks like the only way I can get messages to work at least with this person is by manually going to the osu website, opening the chat area, refreshing once and then returning to the lazer client,

Somehow this magically causes lazer to reopen the chat tab that I had with this person, chat history and everything, and I can send messages.

Attempting to go to the users profile and opening chat from there by using the chat icon just pulls up a blank chat tab that causes the issue detailed in my first post

**Comment by peppy** [comment]
Sounds like you may potentially be hitting a bug osu-web / database side. I'll have a look into this for you – can you provide your / your friend's user id?

**Comment by EZ2ACTux** [comment]
My user ID is 1506631 (Username Tux)

His user ID is 2136721 (Username Fyurie)

**Comment by EZ2ACTux** [comment]
![image](https://user-images.githubusercontent.com/10949323/82718299-cb4d9000-9cf5-11ea-81dc-c82e1668cb71.png)

Did a bit of debugging and after a bit of fiddling with breakpoints I noticed that when I try to send a message to this user the client is attempting to create a new channel and send the message in that instead of opening the existing one which does indeed exist. 

Going to play around a little more and see what I can do

**Comment by peppy** [comment]
As a heads up, after re-reading your report I can reproduce this one. It looks like lazer is always sending the `/chat/new`  ("channel create") request but osu-web doesn't handle this correctly.

**Comment by peppy** [comment]
See https://github.com/ppy/osu-web/issues/6043

**Comment by peppy** [comment]
Fixed!
