### ISSUE TITLE
Cursor can go off-screen with raw input even when confine mouse cursor always on

### ISSUE THREAD

**Issue by shortthu** [ppy/osu#908]
https://streamable.com/pn46o

**Comment by Moar-Chan** [comment]
You can also see the background is following the mouse too far, so there are black boxes.

**Comment by peppy** [comment]
The report four days ago was *mentioned in the release notes as a bug*.
The bug mentioned 6 hours ago is *[already reported](https://github.com/ppy/osu-framework/issues/811) in the framework*.

Closing as invalid
