### ISSUE TITLE
osu!taiko "Good"s give less accuracy/score compared to osu!stable

### ISSUE THREAD

**Issue by Firmatorenio** [ppy/osu#9087]
**Describe the bug:** In Stable, mistimed but correct hits in taiko give 50% accuracy (and 150 base score instead of 100), Lazer grants 33% like the rest of the gamemodes. I originally thought this might be intended, but seeing all the chatter about ppcalc/SR on Discord made me think you actually want complete parity and I should report this, just in case.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=aRlsg2Qfk8k

**osu!lazer version:** 2020.515.0

**Comment by smoogipoo** [comment]
PP calculation is actually completely separate from scoring.

I'll leave this open as it's kinda intended but at the same time may be something to consider for when we unify scoring between all rulesets.
Reason being is I just noticed that the default `Judgement` still provides a numeric score of 0 or 1 requiring every ruleset to override it. osu! has 100 for GOODs, o!m has 200, and o!t has 150 in stable...

Furthermore, stable's strong hits provide provide 3x (or 7x if finisher) bonus score if hit accurately, whereas lazer only provides 1x at most. Again, something we may want to consider.

**Comment by Firmatorenio** [comment]
I'm still more worried about displayed accuracy than score itself. It's a perceived nerf for every single non-SS score accuracy-wise, I'm not sure you're doing anything of the sort to the other rulesets.

**Comment by peppy** [comment]
Scoring does not match on any ruleset currently. We are making breaking changes all over lazer intentionally to both see what sticks and because we are not ready to match 1:1.

**Comment by bdach** [comment]
I dunno, what are we reversing to parity with stable here precisely? Accuracy only? Scoring amounts? Classic score (which is currently derived from standardised)?

**Comment by bdach** [comment]
We probably need to gather feedback from taiko players on this one...

Is anyone from @ppy/taiko-pp-commitee up to the task of gathering such feedback, or even contacting us with _someone_ - like a community figure - who is able to? @sw1tchbl4d3r maybe you can provide advice, given you've contributed a bit to taiko already?

**Comment by sw1tchbl4d3r** [comment]
Since not too many taiko players are keen on trying lazer there hasn't been a lot of feedback regarding this yet, but so far accuracy is the one I most heard about, since it left many players confused as to why their accuracy is so much lower on lazer. I'd be able to take on the task of gathering the feedback needed however, will report here once I have some results.

**Comment by bdach** [comment]
@sw1tchbl4d3r anything on the feedback front?

**Comment by sw1tchbl4d3r** [comment]
In progress, been a bit busy recently, to that we (@zachmanthethird and me) have concluded that this might be a good opportunity to gather feedback on multiple issues at once, but are progressing smoothly now.

**Comment by bdach** [comment]
@sw1tchbl4d3r any progress?

**Comment by smoogipoo** [comment]
Moving this out of the project for the time being. We'll go with the current mechanics as they are and see how it is with more user feedback post-ranking.

**Comment by peppy** [comment]
I'm putting this back in the project because it keeps coming up. Specifically, it actually causes imported scores to have non-matching accuracy and grades.
