### ISSUE TITLE
Import skin in linux environment

### ISSUE THREAD

**Issue by hadocter** [ppy/osu#9090]
**Describe the new feature:** 
there's no possible ways for osu!lazer to import skins in linux 
so it would be great if there's a single button for import skins
**Proposal designs of the feature:** 
button click -> open new window to specify location of skin file(.osk)

sry i’m a complete novice at github

**Comment by peppy** [comment]
You should be able to drag skins into the window or load them as you would with any other linux application via command line.

You can also import from a stable folder if you put the folder at ~/.osu/
