### ISSUE TITLE
Some compromisement about new slider things

### ISSUE THREAD

**Issue by iedesu** [ppy/osu#9091]
An urge to change something due to lack of gameplay variation is good idea, but the problem is many parts of this game is already running under community participation. So, i'd like to suggest to add a additional options that asks mapper to decide if their map should follow old client slideracc mechanics or lazer one and display which kind of judge used for each map on song selection menu, and it would give more option to mappers and players, resulting in more variety on activities related to beatmaps. Additionally, add a mod to switch legacy/lazer judge with some pp reduction and it would comfort people familiar with old judges and make them to practice new judge cuz it gives more performance points.

**Comment by bdach** [comment]
Please see [the latest comment](https://github.com/ppy/osu/issues/8371#issuecomment-632840187) on this matter and do not continue opening further issues for now. Thank you.
