### ISSUE TITLE
Add a back button to certain screens

### ISSUE THREAD

**Issue by EZ2ACTux** [ppy/osu#9097]
**Describe the new feature:** 
Currently it isn't quite as obvious how a user is supposed to navigate back one screen which can lead to some confusion.

I feel that placing a back button on the screen when you say, open a beatmap listing from osu Direct or open a user page from your friends panel would help make things a little easier to navigate for new users or people who just aren't familiar with the UI yet. 

**Proposal designs of the feature:** 

A basic back button in the corner of the screen that spawns in certain situations would be the most basic way to implement this as you'd only need to spawn it when it's needed.

**Comment by bdach** [comment]
(cc: @arflyte)

I think overlays are the primary problem here. When transitioning to song select or multi for instance most existing users should be already okay with <kbd>Esc</kbd> through familiarity with stable (and it's a common game idiom to try it in those situations). Sidebars are also pretty self-explanatory in that you can dismiss them by clicking anywhere else on the screen, as it's a pre-existing UX pattern (see Material Design drawers for one example).

Overlays are however a little bit awkward in that area in that they appear centrally on the screen and can be layered one over another. They *do* have the "wave" pop in/out animation, which I think is supposed to partly convey the fact that the overlays are stacked on top of each other, but I suppose that may be mistaken for eye candy.

As I mentioned in #9095, <kbd>Esc</kbd> (and also clicking outside of the overlay) is an existing way to back out of an overlay, but I accept it might not be the most intuitive thing in that case.

**Comment by EZ2ACTux** [comment]
Yeah I'd say you're right on the money there.

Part of the reason I tried the universal back button thing was because it was a way to get a back button in there without being super invasive with the overlays but that didn't quite work out as intended.

Maybe it would make more sense to instead of trying to build back buttons and stuff, rejigging the existing system so that say, instead of opening an entirely new overlay for osu direct stuff it just slides out a side panel or something with beatmap info.

Alternatively another idea I had was putting a subtle accent or design on the white space outside the overlays to better convey that the area is clickable and will take you back one page.

**Comment by jai-x** [comment]
I would like to add onto this that the exiting/back behaviour is somewhat inconsistant and doesn't really map in to the metaphor of overlays stacking onto each other.

For example see this video: https://streamable.com/r8sm53

The overlay navigation order is `osu!direct beatmap listing` ->`beatmap info` -> `player info`.
Clicking outside of the overlay or pressing <kbd>Esc</kbd>as a "back" action should result in showing the `beatmap info` overlay again, but it actually goes back to the `osu!direct beatmap listing`.

**Comment by bdach** [comment]
@jai-x The case you mention is actually a [manually-checked exception](https://github.com/ppy/osu/blob/18d71c6894eca80838092cae149ca7c19a9d803f/osu.Game/OsuGame.cs#L661-L662) (only exactly one of beatmap/player info overlays can be open at the same time), so I'd say it's a separate point of discussion as the comment indicates that they should be stacking, but nobody got around to actually fixing that yet.

**Comment by frenzibyte** [comment]
This seems to be pretty much similar in scope to https://github.com/ppy/osu/issues/5063 that I would call it a duplicate.

**Comment by bdach** [comment]
Fair enough, closing. Discussion can be continued in the other thread.
