### ISSUE TITLE
In-game log notification points to wrong location after data folder change

### ISSUE THREAD

**Issue by CThreee** [ppy/osu#9100]
**Describe the bug:** 
The log notification message pointed to the original location in ~/.local/share/osu/logs which was empty and not to the correct, relocated directory. 
**Screenshots or videos showing encountered issue:** 
![Screenshot from 2020-05-23 17-31-22](https://user-images.githubusercontent.com/24468026/82743988-c2ce7700-9d40-11ea-937b-7fc8819ea891.png)
**osu!lazer version:** 
2020.523.0
**Logs:**
N/A

**Comment by frenzibyte** [comment]
The log files are likely important here (especially `runtime.log` and `database.log`), please attach them from your data folder.

**Comment by CThreee** [comment]
[database.log](https://github.com/ppy/osu/files/4672876/database.log)
[network.log](https://github.com/ppy/osu/files/4672877/network.log)
[performance.log](https://github.com/ppy/osu/files/4672878/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4672879/runtime.log)
These may have been overwritten because I have played and reopened a few times since.

**Comment by frenzibyte** [comment]
Yeah they are, is this issue reproducible or did it happen suddenly? also when did it happen, right after relocating the data folder?

**Comment by CThreee** [comment]
I relocated the data folder then imported my songs once and then reimported them again without deleting. The notification was gave the same original log folder location.

**Comment by frenzibyte** [comment]
Cannot reproduce that with the steps you mentioned. can you attempt doing that and attach the logs if you got somewhere?

**Comment by CThreee** [comment]
Sorry, I'm getting errors launching it now for some reason. I had relocated the folder through /mnt/ onto a separate drive.

**Comment by peppy** [comment]
As already mentioned, this discussion begins with providing correct logs.

**Comment by CThreee** [comment]
Here is an instance where In was able to 
[database.log](https://github.com/ppy/osu/files/4672943/database.log)
[performance.log](https://github.com/ppy/osu/files/4672944/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4672945/runtime.log)


![Screenshot from 2020-05-24 00-20-31](https://user-images.githubusercontent.com/24468026/82745643-d08df780-9d54-11ea-9e4e-9f174b157ee9.png)
![Screenshot from 2020-05-24 00-21-53](https://user-images.githubusercontent.com/24468026/82745644-d257bb00-9d54-11ea-953c-21c5ea953947.png)
![Screenshot from 2020-05-24 00-22-10](https://user-images.githubusercontent.com/24468026/82745645-d388e800-9d54-11ea-9272-e8e6e3b2ea89.png)

**Comment by EZ2ACTux** [comment]
Reopening this because I've been able to replicate this problem myself on my own machine. I've attached the log files from where lazer actually logs its files too. Can provide the log files from the directory I'm being sent to as well if required.

Worth noting is that in the directory I'm being sent to, one of the log files (runtime.log) is being actively updated according to the date modified value. Will attach this log as well 


[runtime.log](https://github.com/ppy/osu/files/4675420/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4675421/updater.log)
[database.log](https://github.com/ppy/osu/files/4675422/database.log)
[performance.log](https://github.com/ppy/osu/files/4675419/performance.log)
[network.log](https://github.com/ppy/osu/files/4675417/network.log)

From Roaming/osu/logs/
[runtime.log](https://github.com/ppy/osu/files/4675431/runtime.log)

**Comment by frenzibyte** [comment]
Hmm, the database log doesn't seem to be showing any issues here, is there a `database.log` from the original data folder (`%AppData%/osu/logs`)? although I doubt there's much helpful information from that.

**Comment by EZ2ACTux** [comment]
Here you go, I've attached the other 2 logs in there for good measure just in case

[database.log](https://github.com/ppy/osu/files/4675452/database.log)
[network.log](https://github.com/ppy/osu/files/4675453/network.log)
[performance.log](https://github.com/ppy/osu/files/4675454/performance.log)

**Comment by frenzibyte** [comment]
Yeah they're stale and don't provide any information, It's a bit weird that the message appears but never logged... can you confirm you got the exact same error as the one in the description of this thread? 

If so, can you breakpoint at `OsuDbContext.cs#L190` and read through all the error messages you get and send them here, also may be useful to know what the connection string of the context instance doing the operations is. (you can do that by attaching the instance to the logger by construction and read the connection string of the one logging errors)

**Comment by EZ2ACTux** [comment]
Tried setting a breakpoint on the line you mentioned as well as for log level important and debug just in case.

Strangely though none of the breakpoints were actually tripped when I triggered an error. Gonna do a bit more poking about since I probably missed something obvious
