### ISSUE TITLE
Selecting certain Beatmaps in Song Select or downloading them from Direct results in "Failed to process line: Value is too low"

### ISSUE THREAD

**Issue by EZ2ACTux** [ppy/osu#9103]
**Describe the bug:** 
If I attempt to download the following beatmap using osu direct or select it from the songlist for the first time after launching osu, 3 separate errors are thrown, all of them stating "Failed to Process Line: Value is too low". All of these errors are then recorded to the runtime.log file.

I've redownloaded the beatmap and the problem has persisted.
**Screenshots or videos showing encountered issue:** 
![osu_2020-05-25_17-43-03](https://user-images.githubusercontent.com/10949323/82782334-32af3f80-9eb0-11ea-9a53-ee451554d983.jpg)
![osu_2020-05-25_17-44-57](https://user-images.githubusercontent.com/10949323/82782341-35aa3000-9eb0-11ea-8454-5ab448f6c5de.jpg)
**osu!lazer version:** 
2020.523.0
**Logs:**
[performance.log](https://github.com/ppy/osu/files/4675401/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4675402/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4675403/updater.log)
[database.log](https://github.com/ppy/osu/files/4675404/database.log)
[network.log](https://github.com/ppy/osu/files/4675407/network.log)

**Comment by frenzibyte** [comment]
Covered by https://github.com/ppy/osu/issues/750, can be closed.
