### ISSUE TITLE
Cursor locks at right bottom corner on macOS Fullscreen (No Raw Input)

### ISSUE THREAD

**Issue by 45gfg9** [ppy/osu#9104]
**Describe the bug:** 
I'm not sure how to describe this... please watch the attached video

And I'm not sure exact steps to reproduce this. On my machine it happens frequently when launching. I believe it's related to window focusing or some such...
Changing to windowed mode will fix this
**Screenshots or videos showing encountered issue:** 
[comp.mp4.gz](https://github.com/ppy/osu/files/4676191/comp.mp4.gz)

**osu!lazer version:** 
2020.523.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/4676219/runtime.log)
[debug.log](https://github.com/ppy/osu/files/4676221/debug.log)

**Comment by frenzibyte** [comment]
Can reproduce as well, but I can workaround it with setting "Confine mouse mode" to "Never".

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/8280

**Comment by 45gfg9** [comment]
Oh.. thanks so much, it worked!
