### ISSUE TITLE
Ask user to provide path to the osu! stable installation himself if not detected.

### ISSUE THREAD

**Issue by Layerex** [ppy/osu#9116]
**Describe the new feature:** It would be useful on linux, where you run osu! stable in wine and it is impossible for a game to detect an actual installation path.

**Comment by Game4all** [comment]
Duplicate of #3763?

**Comment by EZ2ACTux** [comment]
> 
> 
> Duplicate of #3763?

I wouldn't call this one a dupe TBH. #3763 was on windows for one thing and this is focused on linux.

I do think that OP @Layerex needs to be more specific about what exactly they want from this feature i.e what would they gain from it. We need a bit more to work with here

**Comment by bdach** [comment]
The solution to the problem here would be mostly the same as the aforementioned issue, so I agree that this is a duplicate. Closing.

Platform differences don't warrant having separate issues.
