### ISSUE TITLE
osu!mania hit lighting doesn't rewind correctly

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu#9117]
**Describe the bug:*If you rewind while playing beat map, the special effects sometimes make mistakes
* 

**Screenshots or videos showing encountered issue:*
![bug](https://user-images.githubusercontent.com/52590027/82907314-08857c80-9f99-11ea-9f19-d1906fb2f14f.jpg)
![bug2](https://user-images.githubusercontent.com/52590027/82907323-0cb19a00-9f99-11ea-93dd-92c2ee79ae6c.jpg)

* 

**osu!lazer version:*2020.523.0
* 

**
[logs.zip](https://github.com/ppy/osu/files/4682567/logs.zip)
*

**Comment by bdach** [comment]
Potentially related to #8082.
