### ISSUE TITLE
Tournament Client can't input chinese

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu#9118]
**Describe the bug:*Tournament Client can't input chinese. error codes.If you input Chinese and save, you can't open Tournament client* 

**Screenshots or videos showing encountered issue:*
![bug](https://user-images.githubusercontent.com/52590027/82907771-9feacf80-9f99-11ea-8e18-22750f0f1b81.jpg)
![bug2](https://user-images.githubusercontent.com/52590027/82907791-a8430a80-9f99-11ea-9603-85ddcdff8851.jpg)

* 

**osu!lazer version:*2020.523.0
* 

**Logs:**

**Comment by mas-alone** [comment]
> The characters being wrong is a known issue ([ppy/osu-framework#2945](https://github.com/ppy/osu-framework/issues/2945)) and will be fixed by SDL.
> 
> I'm not sure what's that about not being able to "open tournament client" after saving. Does it crash?

yes,if you save chinese in input box,tournament won't be open again,only if you delete "Roaming\osu\bracket.json"

**Comment by peppy** [comment]
This is not specific to the tournament client (and being tracked elsewhere).

Please provide logs of the crash and the `bracket.json`.

Also confirm whether manually adding chinese text to the bracket.json file breaks this (it probablt won't). This is a solution you can use in the interim.

**Comment by mas-alone** [comment]
> This is not specific to the tournament client (and being tracked elsewhere).
> 
> Please provide logs of the crash and the `bracket.json`.
> 
> Also confirm whether manually adding chinese text to the bracket.json file breaks this (it probablt won't). This is a solution you can use in the interim.

my bad.do not crash now(2020.523.0).But the chinese characters being wronghttps://github.com/ppy/osu-framework/issues/2945

sorry can close now><

**Comment by peppy** [comment]
No worries. We'll continue to work on fixing input for various languages.
