### ISSUE TITLE
linux timing

### ISSUE THREAD

**Issue by rikupone** [ppy/osu#9122]
**Describe the bug:** 
all the timing feels off. the hitsounds and the song never seem to line up with the actual beatmap. it lines up perfectly on stable osu on windows. this makes it really difficult if not impossible to enjoy the game and makes it hard to play any beatmap, even the easiest. i'm using manjaro linux and i have a 144hz screen as well as a 60hz screen with vsync disabled in my system settings, if it's of any use.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=bxH2e72P4sU

**osu!lazer version:** 
2020.515.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4685024/database.log)
[network.log](https://github.com/ppy/osu/files/4685025/network.log)
[performance.log](https://github.com/ppy/osu/files/4685026/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4685027/runtime.log)

**Comment by peppy** [comment]
We are a bit too early on in development to be giving technical support to individuals (especially via github). On top of that, linux has so many configurations that we cannot support the platform efficiently.

It is almost definitely some kind of configuration issue with your system, so please look into your audio and graphics setup.

**Comment by smoogipoo** [comment]
This is almost certainly going to be an issue with the default PulseAudio config. The following will help you: https://juho.tykkala.fi/Pulseaudio-and-latency

**Comment by LiveLM** [comment]
I was able to reduce my audio latency from 80ms to 2ms, now the hitsounds line properly with the beatmaps.
Fantastic guide!
