### ISSUE TITLE
Lazer wont launch

### ISSUE THREAD

**Issue by satyrsaw** [ppy/osu#9128]
It wont launch on Windows 10 64 bits. Not logs in %appdata% only in event viewer. I have 2 errors from Lazer one is a 'Application Error' and the other is a '.NET Runtime' error.  How do i share those? Do you need my PC Specs?

**Comment by bdach** [comment]
You could attach a screenshot of the error messages here or export and attach the full application logs in `.evtx` format here.

**Comment by satyrsaw** [comment]
There i put everything into a .zip file.

[Event Viewer.zip](https://github.com/ppy/osu/files/4690212/Event.Viewer.zip)

**Comment by bdach** [comment]
It's a database issue - probably a migration mishap:

```
Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: s.MetadataID'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
```

Please delete/move away the `%AppData%/osu/client.db` file and try launching again.

As we're looking to make changes to the DB system in the long term this is the recommended solution for now; closing.

**Comment by satyrsaw** [comment]
Its Fixed Thanks, thanks for the fast support!
