### ISSUE TITLE
osu!ctb Editor Causes Crash on iOS

### ISSUE THREAD

**Issue by Elepover** [ppy/osu#9131]
**Describe the crash:** 
Can be reproduced every time. Steps to reproduce:
- Download beatmap [Almagest(for ctb)](https://osu.ppy.sh/beatmapsets/23210#fruits/79638)
- Switch to ctb mode
- Select it in solo song selection
- Switch back to main view, enter editor
- Tap "Timing" on the top right corner

**Screenshots or videos showing encountered issue:**
https://youtu.be/fQJ4g9ZBQeE

**osu!lazer version:**
`2020.523.0` (iOS, TestFlight)

**Logs:**
[osu.iOS-2020-05-27-230328.ips.beta.log](https://github.com/ppy/osu/files/4689655/osu.iOS-2020-05-27-230328.ips.beta.log)

**Computer Specifications:** 
iPad Pro 11-inch (64GB, Wi-Fi, 1st generation, codename `iPad8,1`)\
iPadOS 13.5 (17F75)

**Comment by bdach** [comment]
Does not seem to reproduce on neither Windows nor Android. Log attached seems to indicate a nullref, but it's not an actual lazer log, so tough to tell for sure.

**Comment by Elepover** [comment]
I tested it on Windows and Android and yes, it doesn't reproduce. Since I can stably reproduce this issue, is there any way I can get the logs on iOS? In production mode, the logs overlay doesn't seem to be outputting anything.

**Comment by peppy** [comment]
@Elepover can you try with other combinations of beatmaps / rulesets? I get the feeling this is not specific to that beatmap (either all rulesets+all beatmaps or any beatmap on osu!catch is what i suspect).

**Comment by Elepover** [comment]
@peppy Oh that's right. This is exactly what happened.

Demo: https://youtu.be/dgZ72DRWb4Q

**Comment by peppy** [comment]
Can reproduce, thanks.

**Comment by peppy** [comment]
Tracking here: https://github.com/xamarin/xamarin-macios/issues/8703

**Comment by peppy** [comment]
Also, "fixed" via https://github.com/ppy/osu-framework/pull/3587.

**Comment by frenzibyte** [comment]
Just gonna note that, for future readers, the PR mentioned above seem to have not worked around the underlying issue (https://github.com/mono/mono/issues/19900 / https://github.com/xamarin/xamarin-macios/issues/8703). It has been banned and no longer used in https://github.com/ppy/osu/pull/10684 for now.

Would hope that switching away from Xamarin avoids this issue, but I'm not sure whether .NET's iOS still relies on Mono. Xamarin could potentially be indirectly involved.
