### ISSUE TITLE
Self-edited beatmap can be played in multiplayer

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu#9132]
**Describe the bug:** 
It is possible to play the self-modified map in multiplayer

**Screenshots or videos showing encountered issue:** https://youtu.be/z-zDds7_M9U

**osu!lazer version:** 2020.530.0.

**Logs:** [runtime.log](https://gist.github.com/ilsubyeega/b3e04e3883c70022a8139796a734a575)

**Comment by bdach** [comment]
ppy/osu-web#6063 will probably tie into this well.

**Comment by peppy** [comment]
That was added as a first step to fix this, yep.

**Comment by ilsubyeega** [comment]
can we get checksum from beatmap object for checking ranked status for lazer (since it is not updating automatically and only a portion is shown o.o)

**Comment by bdach** [comment]
I'm not sure what you mean by that, care to elaborate? If you're talking about being able to update qualified beatmaps, #4823 would be the relevant issue.

**Comment by ilsubyeega** [comment]
> I'm not sure what you mean by that, care to elaborate? If you're talking about being able to update WIP/qualified beatmaps, #4823 would be the relevant issue.

![image](https://user-images.githubusercontent.com/37479424/83437256-6b37b600-a47a-11ea-9d76-1d2888f44908.png)
I mean sometimes it's not marked as ranked or something to get a map

**Comment by bdach** [comment]
> I mean sometimes it's not marked as ranked or something when getting a map

This discussion is off topic in this particular issue, but as far as I can see the mapset you've shown at the screenshot is [not ranked, but loved](https://osu.ppy.sh/beatmapsets/579235#osu/1226524). However the "Loved" badge should be showing in the upper right corner of the wedge.

I could not reproduce this myself when downloading from direct. Please open a separate issue for this problem, and if you decide to do so, please provide info as to how did you add the map to lazer and attach your `client.db` file (it's in the `%AppData%/osu` directory).
