### ISSUE TITLE
Add documentation 

### ISSUE THREAD

**Issue by rubiksmaster02** [ppy/osu#9133]
Add documentation to the c# code, I am wanting to make a game in osu!framework but the lack of documentation on osu!lazer or osu!framework makes it real hard to try and figure out how to correctly build a game with it

**Comment by bdach** [comment]
We are aware of a lack of documentation in some areas (in fact ppy/osu-framework#3233 is tracking precisely that). If there are areas you'd like to be covered by documentation in particular feel free to drop a comment there. However note that many public components have xmldoc in source and usage examples in visual tests.

Closing as duplicate.

**Comment by peppy** [comment]
Please also note that this is the wrong repository for suggesting this. You may, as such, have missed the documentation at https://github.com/ppy/osu-framework/wiki and the template projects that are made to get you started.

Also it would be handy to know which areas you found lacking in documentation so we can potentially focus on improving that area. Please follow-up in https://github.com/ppy/osu-framework/issues/3233.

**Comment by rubiksmaster02** [comment]
Oh I am sorry, I thought that this was the framework, I must have switched from the framework to this. But it could still apply, adding documentation/comments to the actual game itself. And I will post some suggestions at the link that you have provided.

**Comment by peppy** [comment]
We already add documentation where the code doesn't explain itself. We know we are missing higher level documentation, though, showing the flow of larger interactions (like the editor as a whole) which is our focus.

You really need to provide at least one example of where you expect code-level documentation so we can assess whether it's in line with our expectations.

**Comment by rubiksmaster02** [comment]
Yes, yes, I am in a hurry right now and I have to leave soon, but I will compile a list for game and framework related comments on the other link. I wont be able to do it right now though, I will try and be as straight forwards as possible.

**Comment by rubiksmaster02** [comment]
Once I get a better grasp on how everything works here I can help out with some of the documentation myself as well.
