### ISSUE TITLE
No resize possible windowed mode/graphical glitches after resizing (possible duplicate)

### ISSUE THREAD

**Issue by jubiman** [ppy/osu#9136]
There is no option to resize the window to a certain size in windowed mode

![Resize window graphics bug](https://user-images.githubusercontent.com/47221652/83126268-e2ff8c80-a0d8-11ea-9850-9a0a386f2313.png)

osu!lazer 2020.523.0

[performance.log](https://github.com/ppy/osu/files/4694704/performance.log)

**Comment by frenzibyte** [comment]
Do you have discord overlay enabled? if so, disable it and try resizing again.

If it happens to be due to the discord overlay, then this is a duplicate of https://github.com/ppy/osu/issues/5018

**Comment by jubiman** [comment]
That seem's to have fixed it indeed.
Though I think it would be nice to have preset window sizes in windowed mode
