### ISSUE TITLE
Framerate issue on Kubuntu 20.4

### ISSUE THREAD

**Issue by skitou** [ppy/osu#9140]
**Describe the bug:**  After switching to Kubuntu 20.4 from Ubuntu 20.4 (Full install, i just maked a backup of my personal files and osu folder) the framerate was verry laggy. I tried wihtout my osu folder (like a first start) and the game was still laggy (130 fps on Ubuntu vs 40~70 fps on Kubuntu).

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:**  2020.523.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4696470/database.log)
[performance-audio.log](https://github.com/ppy/osu/files/4696471/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4696472/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4696473/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/4696474/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4696475/runtime.log)

**Comment by smoogipoo** [comment]
This is a driver or distro issue.

**Comment by enoslayd** [comment]
Try turning off the compositor (shift alt f12). To determine that it is turned off, if the window borders have shadows or app windows have animation, then it is on, if not, it is off
