### ISSUE TITLE
Selection in Editor does not update to include new objects when playing

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#9141]
Selection in the editor does not automatically update to include new objects when a song is playing if the cursor is standing still. The selection only updates when the cursor is moving. To match stable behaviour, the former would also have to be true. I've tested this in both the osu!standard and osu!mania editor.

Gif showing the issue: https://i.imgur.com/GQeUE9z.gifv

**Comment by peppy** [comment]
This is already on my UX fixes list. It's working correctly in the timeline, for what it's worth.
