### ISSUE TITLE
Tooltips with keybindings

### ISSUE THREAD

**Issue by vruss** [ppy/osu#9147]
**Describe the new feature:** 
There's many global keybindings and names that are not common knowledge. A tooltip on hover with the name + keybinding would be a nice quality-of-life improvement.

**Proposal designs of the feature:** 
![osu_tooltip](https://user-images.githubusercontent.com/10886082/83261271-5c6fab80-a1bb-11ea-9fd5-a9786d08ef21.png)
(please ignore the inaccurate keybinding, I messed up)

**Comment by peppy** [comment]
Would love to see this.

**Comment by Game4all** [comment]
Would it be fine to reuse existing tooltip design of toolbar buttons on overlay buttons and to append them with a keybinding tooltip or something along those lines ?
![image](https://user-images.githubusercontent.com/20256717/83397761-72b97980-a3fe-11ea-9588-bc3a3256e3de.png)

**Comment by peppy** [comment]
The design should not change.

**Comment by Game4all** [comment]
![image](https://user-images.githubusercontent.com/20256717/83400816-d09c9000-a403-11ea-80c4-cc5ff497dcf8.png)
I actually meant something like this sorry (unless this is what you were thinking of).

**Comment by peppy** [comment]
Yes, that looks fine.

Although it may fit better on the second line.

**Comment by hbnrmx** [comment]
See also #5449

**Comment by Joehuu** [comment]
If anyone is doing this, it may not be as easy if we want to dynamically change the string to whatever keybinding the button is tied to.

**Comment by peppy** [comment]
Did you try and fail? Would be helpful if you explain why you think it's hard (maybe we can provide advice to help out).

**Comment by Joehuu** [comment]
Never attempted this, just a heads up for people who may just hard code the default keybindings to the string (from the looks of this comment thread).

**Comment by Flutterish** [comment]
The tooltip could just look if an `IHasTooltip` also has a keybinding and then just insert it like mod description does ( since tooltips update every few frames, it will update dynamically ), assuming you have implemented a common interface for keybound drawables.
