### ISSUE TITLE
Song panel icons missing

### ISSUE THREAD

**Issue by vruss** [ppy/osu#9148]
**Describe the new feature:** 
The BPM, Circle Count, Slider Count and Spinner Count should have their own distinct icons instead of the current placeholder circle icon

**Proposal designs of the feature:** 
![image](https://user-images.githubusercontent.com/10886082/83280102-72d73080-a1d6-11ea-962e-5164944abf51.png)
(^these are the icons I'm talking about^)

**Comment by frenzibyte** [comment]
Duplicate of https://github.com/ppy/osu/issues/2229
