### ISSUE TITLE
Bring back main menu fade to black on exit

### ISSUE THREAD

**Issue by GamerProYT54** [ppy/osu#9150]
**Describe the new feature:** 
Fade effect when osu!lazer is closed.
**Proposal designs of the feature:** 
Fade effect from osu!stable

**Comment by bdach** [comment]
There is a similar, but not precisely the same effect on exit; I'm guessing you'd like to see one that's closer to stable?

**Comment by GamerProYT54** [comment]
Yeah, after the first fade, there is a fade to the desktop. That is the one that is missing.

**Comment by peppy** [comment]
I'm not sure we want to add custom window operations like this. They are prone to failure and cannot be supported on other platforms (plus a very non-standard thing for a game to do).

**Comment by smoogipoo** [comment]
Yeah, I'm also going to say we don't want this.
