### ISSUE TITLE
Allow skipping intro disclaimer

### ISSUE THREAD

**Issue by GamerProYT54** [ppy/osu#9152]
**Describe the new feature:** 
A feature where you can skip the "Project Development" screen.
**Proposal designs of the feature:** 
Press any key at the "Project Development" screen in osu!lazer to skip the start screen.

**Comment by bdach** [comment]
I don't think this will happen as it seems intended that it always play out. The predecessor of that screen was also unskippable.

The reason that screen exists is that there were cases of people mistaking lazer as being a more stable release than it actually is, and so it aims to inform those users. As such it should be unskippable at least the first time the user launches the game.

**Comment by GamerProYT54** [comment]
You are right, there's gota be some disclaimer that something might go wrong. Thanks bdach!

**Comment by peppy** [comment]
Closing this for now. The disclaimer also helps hide loading right now, and isn't a huge inconvenience.
