### ISSUE TITLE
[MANJARO XFCE] Nothing displays when playing normally, but will run as root with no audio.

### ISSUE THREAD

**Issue by PrintStringName** [ppy/osu#9156]
[database.log](https://github.com/ppy/osu/files/4706179/database.log)
[network.log](https://github.com/ppy/osu/files/4706180/network.log)
[performance.log](https://github.com/ppy/osu/files/4706181/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4706182/runtime.log)

I've encountered a strange issue with osu!lazer, in that upon the game being loaded it will show the usual messages about it being an unstable version, after which it fades to black and nothing happens. The game is still responding however, since scrolling still changes the volume. If I start the game as root, then it loads and runs just fine, but there is no audio at all.

**Comment by bdach** [comment]
Most likely a case of a bad audio device being chosen leading to not being able to progress past intro; see #8985 for instructions how to bypass for now.

Closing as duplicate.
