### ISSUE TITLE
ability to disable nightcore drum sounds 

### ISSUE THREAD

**Issue by positonix** [ppy/osu#9157]
**Describe the new feature:** 
some songs sound nice with a higher pitch, which nightcore does, but it also adds these annoying drum sounds i really hate. sometimes they also dont line up with the song, and it ruins parts of the song which are supposed to be blank or almost blank. there should be a way to keep the pitch changed without the drums. 
**Proposal designs of the feature:** 
setting: "enable nightcore drumming sounds" checked by default, or in the mod select the ability to check or uncheck "nightcore drumming"

**Comment by peppy** [comment]
Please remove them via a skin. Such options won't be added as that's basically half of what nightcore mod is.

https://github.com/ppy/osu/blob/e64e44ecf957959412ba060da9f346cfbbb7fa67/osu.Game/Rulesets/Mods/ModNightcore.cs#L72-L75
