### ISSUE TITLE
Can someone explain this empty for loop i found while clean up code.

### ISSUE THREAD

**Issue by johnneijzen** [ppy/osu#916]
it located osu.Game > Ruleset > Objects > SliderCurve.cs Line 178

for (; i < calculatedPath.Count && cumulativeLength[i] < d0; ++i) { }

**Comment by RemieRichards** [comment]
It's not empty, it increments ```i``` which is used after the for loop.

**Comment by johnneijzen** [comment]
okey see just having {} makes look confusing i wonder if your remove {} will this code still work

**Comment by peppy** [comment]
Please consider joining our discord channel to follow up on questions like this; makes it much easier to help out! https://discord.gg/ppy
