### ISSUE TITLE
explicit songs warning

### ISSUE THREAD

**Issue by Redo11** [ppy/osu#9163]
**Describe the new feature:** 
Add some kind of way to block or inform user about explicit song.
**Proposal designs of the feature:** 
1. Setting that blocks all explicit songs.
2. Warning when downloading.
3. Marks on songs when searching and in song list.
4. Warning when starting a song.

I would also add a setting to disable warnings and marks. 

Good luck!

**Comment by bdach** [comment]
This would require new metadata and therefore be dependent on ppy/osu-web#5902.

**Comment by peppy** [comment]
I think it's fine to close this one as a duplicate. It would be added if we ever get around to doing so at a metadata level. The chain of dependency to make this kind of thing happen is huge (editor support, osu-stable support, osu-web support, application to old beatmaps, and *finally* osu-lazer support).
