### ISSUE TITLE
Options available during gameplay

### ISSUE THREAD

**Issue by GamerProYT54** [ppy/osu#9167]
**Describe the bug:** 

In osu!lazer, you can open options using the Ctrl + O keybind. In osu!stable, you can't open options during gameplay. Is this a bug, or was this implemented on purpose?

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:**

**Comment by jorolf** [comment]
This is intended, unlike stable lazer doesn't require a full reload when changing settings which allows this kinds of stuff while playing

**Comment by bdach** [comment]
In fact, one of the disclaimer screens [explicitly mentions this](https://github.com/ppy/osu/blob/00024f56fa6c5ac75d162e3de2d8aa555cb49b85/osu.Game/Screens/Menu/Disclaimer.cs#L192).
