### ISSUE TITLE
Option to play Taiko in two lanes

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#9169]
**Describe the new feature:** Okay, so this is something I saw in Splatoon 2's Taiko-like mini game and I've noticed how it makes the play field much more readable (especially when it's very busy). The idea is to separate dons and katus into two lanes -- dons go in the bottom lane, katus in the top. This would probably make the game mode more playable for colourblind people as well, so it would be nice to have it as an alternate layout.

![image](https://user-images.githubusercontent.com/15932372/83438568-ec268b80-a441-11ea-8e2d-2f79e130e83e.png)

**Comment by bdach** [comment]
Not sure how I feel about this proposal. It *could* be an unranked mod, but I imagine the implementation of this might stretch the limits of the mod system a little bit. Not to mention I hear there's a history of actual cheating in taiko that uses this [exact](https://twitter.com/K1zma/status/1238889988684754945) [strategy](https://www.youtube.com/watch?v=CUI5qanFDdg) to make reading easier... You could argue mania 2K fills this space I suppose.

**Comment by smileyhead** [comment]
In my opinion, readability _should_ be increased as much as possible. It's not cheating if it's implemented and anyone can use it. The map itself wouldn't become easier, you could only read it better.

**Comment by Kasumiikun** [comment]
I very much doubt this will go anywhere.
It feels like killing the whole point of the game in my opinion, and doubt devs will want to implement it, since bdach did say it was literally how the old cheating strategy worked.
Maybe someone else will make it as a custom mode, but I don't see it officially supported in any form.

**Comment by peppy** [comment]
The whole osu!taiko / Taiko no Tatsujin game style revolves around readability impairment. I don't think we are changing that at this point. Please try playing osu!mania 2k instead.

**Comment by enoslayd** [comment]
Also, osu rush custom ruleset kinda do this.
