### ISSUE TITLE
Add back pause sound

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#9170]
**Describe the new feature:** 
On Stable when you pause the song you hear a "calming" sound which makes the pauses less empty. It would be really nice if this gets added back in

**Proposal designs of the feature:** 
N/A ( https://streamable.com/4hmh25 ) to show what i mean

**Comment by BananeVolante** [comment]
I think that I'll start contributing by working on this issue.
But for now i don't know where i could get osu!'s background music.

**Comment by MiraiSubject** [comment]
@BananeVolante There's a PR open for it right now over at https://github.com/ppy/osu-resources/pull/104 that you could use, until the final file is merged.
