### ISSUE TITLE
importing on mac

### ISSUE THREAD

**Issue by skyde-py** [ppy/osu#9172]
**Describe the bug:** 
whenever you try to import any beatmaps/skins into osu!lazar it just says that there is not stable install found I do have a stable install on the same disk and even on the same directory (my desktop)
**Screenshots or videos showing encountered issue:** 
![Screen Shot 2020-06-01 at 7 49 46 PM](https://user-images.githubusercontent.com/63376310/83465199-28a5b780-a441-11ea-9cd5-a97c26db0902.png)
**osu!lazer version:** 
2020.523.0
**Logs:**

**Comment by peppy** [comment]
please symlink or move your songs folder to `~/.osu/Songs`
