### ISSUE TITLE
Rebind mods/random/options

### ISSUE THREAD

**Issue by boswelja** [ppy/osu#9176]
**Describe the new feature:** 
Add the ability to rebind the mods/random/options buttons in song select. Currently they're bound by default to F1-F3 respectively, and there doesn't seem to be a way to change this.
**Proposal designs of the feature:**

**Comment by boswelja** [comment]
I haven't looked at the code very much, but I feel like this would be a good place for me to start contributing. As long as it's something you guys want, can I have a go at it?

**Comment by peppy** [comment]
Yep, definitely
