### ISSUE TITLE
Grade letter prevents a contracted score panel from expanding

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9178]
**Screenshots or videos showing encountered issue:** 
![example](https://user-images.githubusercontent.com/43073074/83529843-30219b00-a4eb-11ea-9be5-1a672f328243.gif)

**osu!lazer version:** 2020.602.0

**Comment by bdach** [comment]
This is because `ScorePanel`, which handles the switching logic, doesn't actually span the full height of its contents:

![image](https://user-images.githubusercontent.com/20418176/83550660-7c7ad400-a507-11ea-901c-742776aa7a1b.png)

**Comment by peppy** [comment]
Milestoning, should be a simple fix.
