### ISSUE TITLE
Notification that an update is available no longer appears

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#9183]
**Describe the bug:** 

The notification that appears at the game start when an update is available don't work

**Screenshots or videos showing encountered issue:** 

![Screenshot_20200602_173906_sh ppy osulazer](https://user-images.githubusercontent.com/40500781/83540190-42560600-a4f8-11ea-81bf-21331acb95a9.jpg)

**osu!lazer version:** 

2020.523.0

**Logs:**
 Android

**Comment by frenzibyte** [comment]
Please attach your log files, sounds like this is some sort of a failure while performing a web request to fetch releases, did you make sure you're connected to the internet?

**Comment by MTGPROD** [comment]
Yes i'm connected to Internet. Try it yourself you won't receive the notification

**Comment by frenzibyte** [comment]
Can't do so as I have no android device to try with at the moment, please attach the logs yourself for further assistance. (I think it's stored at `/Android/data/sh.ppy.osulazer/files/logs`)

**Comment by bdach** [comment]
Can reproduce with 2020.523.0. When I bring up the settings overlay and scroll to the bottom I see "local release" instead of an actual version, so it seems to indicate that something is wrong with the assembly version:

https://github.com/ppy/osu/blob/9b277d52e52c926a30e9816393cd734d014c96c4/osu.Game/OsuGameBase.cs#L106-L107

`IsDeployedBuild` being `false` will also suppress checking for updates. This is very strange however as I do recall this working at some point in the past...

**Comment by peppy** [comment]
That sounds very bad. Has something regressed in the build process? Did I just break it because I made that 523 build manually?

```
[22:09:21]: ---------------------------
  | [22:09:21]: --- Step: app_version ---
  | [22:09:21]: -------------------------
  | [22:09:21]: Current Version is:
  | [22:09:21]:   Version: 0.1
  | [22:09:21]:   Build: 202006020
```

Is someone able to install the latest release and check what it says on the settings footer?

**Comment by bdach** [comment]
It says "local release" on 602.0 too, as far as I can tell:

![Screenshot_20200603-061120](https://user-images.githubusercontent.com/20418176/83595136-5b46d180-a561-11ea-802a-404e93b20518.png)

For reference I downloaded the very first official apk release (2019.1021.0) and got the update notification instantly, so it does seem like something regressed, but no idea where. Not sure how to pinpoint this well...

**Comment by Joehuu** [comment]
Regressed since 2020.508.2.

2020.429.0 was the last build that worked correctly.
