### ISSUE TITLE
Beatmap shown in tournament client desyncs with cuttingedge

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu#9184]
**Describe the bug:** Hi, I meet a problem when I use the tournament end of lazer to make live broadcast of the game. However, there are only two ways to trigger this error.

As you can see, the lower right corner of the lazer client wrongly displays a message of the beatmap when I quickly switch beatmap in the video.

As for another triggering method, it is that the stable client end will automatically change to the next beatmap if the player has not started the game after a beatmap is played. Then, the lazer client end will synchronize the beatmap of the stable client end. At this time, the lazer client end will also display the wrong beatmap information if the player starts the game.

I hope that the tournament client end of lazer can synchronize the songs played in the stable client end again before starting the game, so as to correct the displayed beatmap information.

Finally, thank you very much for seeing what I write here.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=XwXZJ0IjTAs

**osu!lazer version:** 2020.523.0

**Logs:** N/A

**Comment by bdach** [comment]
I'm not sure how to reproduce this; seems to be working fine for me when I spam <kbd>F2</kbd>. The issue might be on the side of cuttingedge from what I understand of how the IPC between it and the tournament client works.

Would you mind checking the `.osu` of that map and making sure it has `BeatmapID` and `BeatmapSetID` entries inside?

**Comment by peppy** [comment]
When this occurs, please figure out which component is going wrong. You can check the IDs in the ipc.txt files in the stable folder when it happens, and see whether stable is exposing the wrong beatmap or lazer has not read/updated from stable's exposed beatmap.

**Comment by mas-alone** [comment]
> When this occurs, please figure out which component is going wrong. You can check the IDs in the ipc.txt files in the stable folder when it happens, and see whether stable is exposing the wrong beatmap or lazer has not read/updated from stable's exposed beatmap.

okay,the "beatmapid" and "ipc.txt" is ture.but the shown in was wrong.
as you can see the pic
![1234](https://user-images.githubusercontent.com/52590027/83636507-aa7c1900-a5d8-11ea-88e5-8a8ff789ce59.jpg)
![5678](https://user-images.githubusercontent.com/52590027/83636515-ae0fa000-a5d8-11ea-9650-cb1007ccd814.jpg)
Actually, it doesn't happen very often.

**Comment by MiraiSubject** [comment]
It took me a couple of tries to reproduce it, but it seems like there's indeed something changing in stable's ipc.txt albeit for just a split second. 

This is how I reliably reproduced it:
1. Created a multiplayer room that can be recognized by Stable CEs tournament client
2. Connect to that room using Stable CE's tourney client
3. As host of that room, change it to any map using `!mp map`
4. Wait until the song ends
5. Observe Stable CE resetting the song and Lazer changing it. 

I believe Stable CE has a really short period where it loads the other song, but switches back. This causes a write to `ipc.txt` but it gets overwritten again really quickly (thus unobservable in the video below). Lazer doesn't catch this second write to the file and instead keeps the map that was in the file for a split second.

Demonstration of it happening (I had also attached breakpoints to `Beatmap` but the change can also be observed in the debug console): https://streamable.com/1iboqi

**Comment by peppy** [comment]
The weird part is that lazer is polling. So it should 100% be getting the latest version.

While investigating I have likely found the problem though, so will push a fix.
