### ISSUE TITLE
Settings menu button click not highlighted correctly

### ISSUE THREAD

**Issue by Fukashi13** [ppy/osu#9196]
![osu_2020-06-03_10-56-32](https://user-images.githubusercontent.com/48766178/83617127-eedfc880-a588-11ea-9297-2d8d50396772.jpg)

When clicking a section button in the settings menu, the game scrolls to the section, but the button is not highlighted. When changing the ScrollTo definition in SectionsContainer.cs to
`public void ScrollTo(Drawable section) =>
            scrollContainer.ScrollTo(scrollContainer.GetChildPosInContent(section) - (FixedHeader?.BoundingBox.Height ?? 0), false);
` 
to disable the animation of the scroll, the problem doesn't occur, implying that somewhere in the scrollTo definition of the framework (probably, I cant find it), UpdateAfterChildren is run before the scroll animation ends, which causes the Update to highlight the section before the correct

**Comment by power9maker** [comment]
It’s even worse on vertical device/small UI scaling
![IMG_0238](https://user-images.githubusercontent.com/42269909/83621115-8bf13000-a58e-11ea-9c80-d70ce46b5a77.png)
