### ISSUE TITLE
Visible playfield boundary

### ISSUE THREAD

**Issue by vruss** [ppy/osu#9198]
**Describe the new feature:** 
An optional setting that when enabled will display a rectangle containing the playfield. This will enable players to make adjustments to their tablet play-area to fit the playfield.
Bonus points if it's also skinnable.

**Proposal designs of the feature:** 
![screenshot010](https://user-images.githubusercontent.com/10886082/83624312-bf35be00-a592-11ea-9991-7a918f32dc64.png)

**Comment by bdach** [comment]
Not sure how players do this on stable, but if custom gameplay UI skinning happens one day this would be one place that seems good for it.

**Comment by cupppu** [comment]
Most common way currently is to skin the rectangle into the hp bar via `scorebar-bg.png`:
![scorebar-bg@2x](https://user-images.githubusercontent.com/7279624/83681201-a5d55600-a614-11ea-8d99-f0352ab43db4.png)

**Comment by peppy** [comment]
I think this is something we want as a default, and skinnable in a way that doesn't involve adding 1x overdraw and huge performance overhead (like done in basically every legacy skin).
