### ISSUE TITLE
Custom rulesets failed to load on Android

### ISSUE THREAD

**Issue by MeguMario** [ppy/osu#9205]
**Describe the bug:** 
I don't know if custom rulesets were written specifically for PC (or x86 platform or not), but it won't load and will error as if rulesets are invalid

**Screenshots or videos showing encountered issue:** 
![Screenshot_20200604-012515](https://user-images.githubusercontent.com/44724359/83674958-74ec2580-a602-11ea-93a9-2e9a53e5ce4b.png)

**osu!lazer version:** 
2020.603.0

**Logs:**
(will include one tomorrow, android 11 make it even more hassle to pull the log files)

**Comment by peppy** [comment]
android does not support AOT. this will not work for now
