### ISSUE TITLE
Lazer won't start

### ISSUE THREAD

**Issue by ImAPotatoDude** [ppy/osu#9206]
So i just download a brand new .603ver "install.exe" and it won't load anything after the "Welcome to osu"
The fps counter work tho

**Comment by frenzibyte** [comment]
Please attach the log files, can be found at `%AppData%/osu/logs` for windows, or at `~/.local/share/osu/logs` for macOS & linux.

**Comment by bdach** [comment]
Also, please state your operating system and hardware specifications.

**Comment by ImAPotatoDude** [comment]
[runtime.log](https://github.com/ppy/osu/files/4726361/runtime.log)
I't have an i5 (Lenovo Thinkpad idk it's my dad working labtop sry)

**Comment by ImAPotatoDude** [comment]
also it's win10 pro

**Comment by bdach** [comment]
As expected, it seems related to audio - there's no BASS initialisation header in that log. Worrying that `no device` didn't work, though... Not sure what's that about.

Does reverting to previous versions help?

**Comment by ImAPotatoDude** [comment]
I tried to run 523 (not sure but a previous one) and it didn't worked 
*I just tried w/o my headphone and the clicking of the sound controler worked just fine (i was able to change the master,effect thingy

**Comment by ImAPotatoDude** [comment]
but it was still locked on the "welcome to osu"

**Comment by bdach** [comment]
This is still consistent with a lack of audio. If you hover over the sound controller (namely over the mute button), can you hear sound effects?

**Comment by ImAPotatoDude** [comment]
yes

**Comment by bdach** [comment]
Did you happen to delete a lot of beatmaps lately? Try removing or renaming your `%AppData%/osu/client.db` file.

**Comment by ImAPotatoDude** [comment]
%AppData%/osu/client.db
i didn't find this doc anywhere, i've never seen that (i just searched and still can't)

**Comment by aspriddell** [comment]
> %AppData%/osu/client.db
> i didn't find this doc anywhere, i've never seen that (i just searched and still can't)

it probably won't show from a windows search. Try doing <kbd>Win</kbd>+ <kbd>R</kbd> then paste `%AppData%/osu` in the box that shows and press enter. You *should* then see the client.db file

**Comment by ImAPotatoDude** [comment]
I've already seen that file but there nothing named after "client" there...

**Comment by ImAPotatoDude** [comment]
And just for clarity it's not %AppData%/osu but it's lead me to %AppData%/Roaming/osu when i type %AppData%/osu

**Comment by frenzibyte** [comment]
Yes we're aware of that, `%AppData%` leads to `C:\Users\{user}\AppData\Romaing`.

Please state all the files / directories you see inside `%AppData%/osu`, if there are additional log files in `%AppData%/osu/logs` (other than `runtime.log`), please attach them.

Also, out of curiosity, do you have low space in the disk storage? does switching the intro sequence to `Circles` let you run the game just fine? (and do you hear any sound then?)

To switch your intro sequence:
 1. Open configuration file `%AppData%\osu\game.ini`,
 2. Edit the line where it says `IntroSequence = Triangles` into `IntroSequence = Circles`,
 3. Save the file and try running the game.

**Comment by ImAPotatoDude** [comment]
The only log i have is runtime
in %AppData%/osu there is "cache" "logs" with runtime/log framework.ini and storage.ini

**Comment by frenzibyte** [comment]
> The only log i have is runtime
> in %AppData%/osu there is "cache" "logs" with runtime/log framework.ini and storage.ini

Can you post the content of `storage.ini`?

**Comment by ImAPotatoDude** [comment]
Cannot rn but 2/3h and i'll be able to

**Comment by ImAPotatoDude** [comment]
FullPath = C:\AppData\osu-lazer

**Comment by frenzibyte** [comment]
Can you check if that path (`C:\AppData\osu-lazer`) is valid and there are files and directories inside, if so, please check the `logs` folder inside that path and attach all log files you see there.

**Comment by ImAPotatoDude** [comment]
[network.log](https://github.com/ppy/osu/files/4730226/network.log)
[performance.log](https://github.com/ppy/osu/files/4730227/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4730228/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4730229/updater.log)
[database.log](https://github.com/ppy/osu/files/4730230/database.log)
there you go

**Comment by frenzibyte** [comment]
OK, now we've got to a good point for investigating, seems like the intro beatmap for triangles has failed to load for some reason, can you please attach your `client.db` file, compress it in an archive file to be able to attach it here.

**Comment by ImAPotatoDude** [comment]
[client.zip](https://github.com/ppy/osu/files/4730306/client.zip)
2 MB... okay than

**Comment by frenzibyte** [comment]
Alright, the database file seems to be good, the game is freezing currently because it cannot find the beatmap file of triangles intro. 

Can you check whether `files` folder exists inside `C:\AppData\osu-lazer`, if it does, please check if the file at path `files/a/a1/a1556d0801b3a6b175dda32ef546f0ec812b400499f575c44fccbe9c67f9b1e5` exists.

Also, can you please confirm that you did not touch the `files` folder?

**Comment by ImAPotatoDude** [comment]
I just changed the game.ini "Triangles intro" to "circles" and it finally loaded

**Comment by ImAPotatoDude** [comment]
ok everything work just fine

**Comment by frenzibyte** [comment]
Please remember that the `files` folder is not something you can play with unless you know exactly what you're doing.

Now that you have a databased beatmap that leads to non-existent files, you may run into issues throughout the game, I would recommend cleaning up your game user data (by removing both `%AppData%/osu` and `C:\AppData\osu-lazer` while the game is closed) and then run the game again to create a new fresh one.

Though keep in mind the above operation will remove all of your beatmaps, skins and scores so it's your choice to do so, until a "retrieve missing files from beatmaps" feature is implemented which may be out-of-scope from now.

Issue can be closed for now.
