### ISSUE TITLE
Importing Beatmaps on Linux

### ISSUE THREAD

**Issue by 641i130** [ppy/osu#9208]
**Describe the new feature:** 
So, on Linux you're not able to import beatmaps since there is not osu!stable version native to Linux. Maybe there could be an option to select a folder of beatmaps from a windows or wine install for it to import. Is there a way to manually import beatmaps/skins? Would you copy certain directories to places it looks?

**Comment by peppy** [comment]
you can move of link your songs folder to `~/.osu/Songs` for now.
