### ISSUE TITLE
Unable to move mouse on mac

### ISSUE THREAD

**Issue by TwintailGun** [ppy/osu#9218]
**Describe the bug:** 
In osu!Lazer I am unable to move cursor in-game but have the ability to click and use keyboard shortcuts on Catalina. Similar to Issue #7188 but not quite the same.
**Screenshots or videos showing encountered issue:** 
Not able to as my cursor is stuck while in Osu!
**osu!lazer version:** 
2020.603.0
**Logs:**
No error logs

**Comment by frenzibyte** [comment]
Are you in fullscreen mode? have you checked if the cursor is actually locked at bottom right, you can do so by attaching a hot corner there and wait for any operations to be performed.

**Comment by TwintailGun** [comment]
Fullscreen, but I can change cursor locations by tabbing out and tabbing in

**Comment by dundeez** [comment]
I also have the exact same issue

**Comment by YeaToast** [comment]
I have an issue like this, but all the fixes mentioned don't work

**Comment by JarrenJ** [comment]
Adding support to this. On just about every version of osu! lazer from the beginning something similar has always happened to me, granted it has never been this persistent though. A fix would be greatly appreciated as it prevents me from playing. ): Currently the most recent binary release as of now and running macOS Catalina 10.15.4. In game the cursor knows when I click, but I cannot move my cursor unless I tab out of the game move my cursor on my desktop and then tab back in, but even then it doesn't always work / register clicks... Does anyone have any ideas / weird workarounds for this?

**Comment by peppy** [comment]
Switch to windowed mode. As above. Full-screen does not handle correctly.

**Comment by JarrenJ** [comment]
> Switch to windowed mode. As above. Full-screen does not handle correctly.
> 
> option-enter if you're stuck.

Thanks, didn't see that fullscreen didn't work just saw it was asked if it was being used ;). Any ideas as to why this happens?

**Comment by classicduck** [comment]
> > Switch to windowed mode. As above. Full-screen does not handle correctly.
> > option-enter if you're stuck.
> 
> Thanks, didn't see that fullscreen didn't work just saw it was asked if it was being used ;). Any ideas as to why this happens?
> 
> Edit: going from windowed to fullscreen makes fullscreen work normally.

Turn off confine mouse cursor in Full screen

**Comment by peppy** [comment]
If only this kind of knowledge was actually shared here. That sounds like something that can be easily fixed at our end, will look at this.
