### ISSUE TITLE
Improvements for the ranking page on the new website

### ISSUE THREAD

**Issue by Epicm14** [ppy/osu#9219]
Just some features from the old site's ranking page that a lot of us used and would like to see back on the new site if possible:
-overall accuracy
-sorting of columns
-exact numbers

**Comment by Kashouryo** [comment]
Please open an issue in https://github.com/ppy/osu-web
This is the place for lazer's client code.

**Comment by Epicm14** [comment]
> Please open an issue at https://github.com/ppy/osu-web
> This is the place for lazer's client code.

ah thanks, haven't been on github in a while

**Comment by Joehuu** [comment]
Moved to https://github.com/ppy/osu-web/issues/6128, closing.
