### ISSUE TITLE
Star rating filter not visible at song select

### ISSUE THREAD

**Issue by veryorginalusername** [ppy/osu#9220]
**Describe the bug:** 
When I go back to the main menu and click "play", all the beatmaps I downloaded before are dissapearing.
**Screenshots or videos showing encountered issue:** 
https://streamable.com/ag7pi0
**osu!lazer version:** 
2020.603.0

**Comment by bdach** [comment]
Could you check if the "Display beatmaps from... to" setting is set to its default values?

![image](https://user-images.githubusercontent.com/20418176/83947181-c9b3ba00-a815-11ea-8eae-bad365862f3c.png)

**Comment by veryorginalusername** [comment]
I checked it, and you were right, I just accidentally set "display beatmaps from" to highest value.
Holy fuck, I'm so stupid. Sorry for wasting your time.

**Comment by peppy** [comment]
We really need this to be displayed *on* song select.

**Comment by Gabixel** [comment]
The filter has been removed from the settings and is now visible in the carousel as a range slider (see https://github.com/ppy/osu/pull/18962)
