### ISSUE TITLE
Spike lag on Random beatmaps

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#9222]
**Describe the bug:** When random it'll be lag spike for a short peroid reguardless how frequent it is.

**Screenshots or videos showing encountered issue:** 
[Osu!Lazer.zip](https://github.com/ppy/osu/files/4740647/Osu.Lazer.zip)

**osu!lazer version:** 2020.603.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/4741127/network.log)
[performance.log](https://github.com/ppy/osu/files/4741128/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4741129/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4741131/updater.log)

**Comment by Game4all** [comment]
Could you please attach all the log files present in `logs` directory ? The logs you posted seem to be truncated.

**Comment by frenzibyte** [comment]
@IkaWaAyuMu If not the above, did you relocate your osu!lazer folder to another location, if so, please attach the logs from there instead.

**Comment by IkaWaAyuMu** [comment]
@Game4all @Ferdi265 Edited as file.

**Comment by peppy** [comment]
Can you explain what "random" is? Are you talking about the mod?

Performance is an ongoing goal and we will continue to iterate. If you cannot provide specifics, we aren't prepared to handle such reports just yet. There's a chance the issues are at your end and we don't have the bandwidth to diagnose right now.
