### ISSUE TITLE
Invalid ruleset resource store returned on a dynamically-compiled assembly

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#9225]
https://github.com/ppy/osu/blob/c3036c1d457adca48ce4c0a5c6c2262195f35ce3/osu.Game/Rulesets/Ruleset.cs#L164
Due to `GetType().Assembly` returning the dynamic assembly instead of the original one, which a `DllResourceStore` will not be able to read from (`assembly.GetManifestResourceNames()` is empty and `assembly.GetManifestResourceStream(...)` returns null)

It's kind-of incorrect that the dynamic compilation will not include the resources from the original assembly, tried googling it up but got nowhere so opening as an issue with an actual case for now.

cc @smoogipoo

**Comment by peppy** [comment]
For reference, which test are you seeing this on?

**Comment by frenzibyte** [comment]
I encountered this while running a player test scene for a custom ruleset (rush) and dynamically compiling it by changing code there (ruleset textures loaded from resources folder would not appear because of the invalid ruleset resource store). 

But going deep down, you can reproduce this in any ruleset as long as it has a resources folder by inserting this to their `Ruleset` subclass:
```csharp
public override IResourceStore<byte[]> CreateResourceStore()
{
    var assembly = GetType().Assembly;
    Logger.Log($"Resources of the ruleset instance assembly: {string.Join(", ", assembly.GetManifestResourceNames())}");
    return new NamespacedResourceStore<byte[]>(new DllResourceStore(assembly), @"Resources");
}
```

And running off a `PlayerTestScene` of that ruleset and trigger a dynamic compilation by changing anything there, original ruleset assembly would log all of its resources, while dynamically-compiled ruleset assembly would log no resources at all.

**Comment by bdach** [comment]
`CSharpCompilation.Emit` [can accept an `IEnumerable<ResourceDescription>`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.csharpfilesystemextensions.emit?view=roslyn-dotnet) that could be used in this case to embed the resources. Not sure yet how to get the list of all embedded resources in a project, though.

**Comment by smoogipoo** [comment]
Is this fixed by adding `[ExcludeFromDynamicCompile]` to your custom ruleset?

**Comment by frenzibyte** [comment]
> Is this fixed by adding `[ExcludeFromDynamicCompile]` to your custom ruleset?

This will block dynamically compiling anything in the ruleset assembly when testing on a simple `PlayerTestScene`:
```
2020-06-08 04:26:13 [verbose]: Updating file /Users/salman/Desktop/rush/osu.Game.Rulesets.Rush/UI/RushPlayfield.cs in solution...
2020-06-08 04:26:13 [verbose]: Building reference map...
2020-06-08 04:26:13 [verbose]: Compiling project osu.Game.Rulesets.Rush.Tests...
2020-06-08 04:26:14 [verbose]: Type RushRuleset referenced but marked for exclusion.
2020-06-08 04:26:14 [verbose]: Type RushRuleset referenced but marked for exclusion.
2020-06-08 04:26:14 [verbose]: Retrieving reference graph...
2020-06-08 04:26:14 [verbose]: Retrieving referenced files...
```

**Comment by smoogipoo** [comment]
Hmm, if you're able to try with a local framework, can you try the same exclusion but applying the following patch to https://github.com/ppy/osu-framework/blob/de08d134a3c26e4c86a76f23cc89d90440df1dc9/osu.Framework/Testing/RoslynTypeReferenceBuilder.cs#L356-L369 :

```diff
-                var node = directedGraph[s];
-
-                // This shouldn't be super tight (e.g. log_2), but tight enough that a significant number of nodes do get excluded.
-                double range = Math.Log(Math.Max(1, node.ExpansionFactor), 1.25d);
-
-                var exclusionRange = (
-                    min: range,
-                    max: node.ExpansionFactor - range);
-
-                // This covers for two cases: max < min, and relaxes the expansion for small hierarchies (100 intermediate nodes).
-                if (Math.Abs(exclusionRange.max - exclusionRange.min) < 100)
-                    exclusionRange = (double.MaxValue, double.MaxValue);
-
-                getReferencedFilesRecursive(directedGraph[s], result, exclusionRange);
+                getReferencedFilesRecursive(directedGraph[s], result, (double.MaxValue, double.MaxValue));

```

**Comment by frenzibyte** [comment]
Still blocked, I've made sure the changes should be updated by simply adding a commented throwing on the constructor of `DrawableRushRuleset` and uncomment to trigger the dynamic compilation. (and also made sure I was using the local framework by changing a logged message there)

This is the test scene I'm dynamically-compiling with:
```csharp
public class TestSceneRushPlayer : PlayerTestScene
{
    public TestSceneRushPlayer()
        : base(new RushRuleset())
    {
    }
}
```

Logs still showing same results:
```
2020-06-08 04:48:40 [verbose]: Updating file /Users/salman/Desktop/rush/osu.Game.Rulesets.Rush/UI/DrawableRushRuleset.cs in solution...
2020-06-08 04:48:40 [verbose]: Building reference map...
2020-06-08 04:48:40 [verbose]: Compiling project osu.Game.Rulesets.Rush.Tests...
2020-06-08 04:48:53 [verbose]: Type RushRuleset referenced but marked for exclusion.
2020-06-08 04:48:53 [verbose]: Type RushRuleset referenced but marked for exclusion.
2020-06-08 04:48:53 [verbose]: Retrieving reference graph...
2020-06-08 04:48:53 [verbose]: Retrieving referenced files...
```

**Comment by smoogipoo** [comment]
Ah, I guess there's no other reference to `DrawableRushRuleset` other than through `RushRuleset` in that case.
