### ISSUE TITLE
Lazer won't start

### ISSUE THREAD

**Issue by kitkatsim** [ppy/osu#9226]
**Describe the bug:** Starting up lazer resulting in blank screen. Blank screen after the disclaimer. This happened after updating to 2020.603.0, but I did a a huge version jump (from 2020.327.0 to 2020.603.0)
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/37004012/83956921-8d3d8980-a828-11ea-9cff-4a8ee0d3acd3.png)

**osu!lazer version:** 
2020.603.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4741200/runtime.log)

**Comment by peppy** [comment]
Please delete client.db and see if it helps.

**Comment by peppy** [comment]
Also looking at your logs, your audio device may be in a bad state. Please check on this and try using a different device if you have one available.

**Comment by kitkatsim** [comment]
Working after deleting client.db, also no longer seeing BASS error in the log, thank you very much!
