### ISSUE TITLE
Possible problems with the license

### ISSUE THREAD

**Issue by Illusiveman931** [ppy/osu#9235]
I noticed a couple of possible problems with the license.

First
The following quote, taken out of README.md, supposedly is contrary to MIT license.

> "Please note that this does not cover the usage of the" osu! "Or" ppy "branding in any software, resources, advertising or promotion, as this is protected by trademark law."

The problem is that it looks like copy-paste from a proprietary license that is not adapted for permissive software license. thereby all third parties who distribute this software under the same name, without the permission of the copyright holder (Copyright (c) 2020 ppy Pty Ltd), violate the license. which makes the software not covered by definition Free and open-source software (FOSS).
At least in part, the function of this quote is performed by the third clause in the New BSD License, but it matches FOSS

Second
The quote below may confuse users. you shoud better indicate that in specifically this repository (osu) there are no "resources" under a license different from MIT.

> "Please also note that game resources are covered by a separate license. Please see the ppy / osu-resources repository for clarifications."

The foregoing by me is only assumptions. I'm not a lawyer. I am not affirming anything, and I am not calling anyone for anything, for any kind of action. any of my possible mistakes are random, and could be caused by my poor knowledge of English.

**Comment by peppy** [comment]
Trademarks in my understanding have nothing to do with a code licence. They are a separate system with separate goals. Sure, we could switch to a licence / version which explicitly states the fact they exist, but not sure there's much point.

If having a reminder about trademarks breaks FOSS then that is unfortunate but also unimportant to the goals of this project. osu! is open source for the purpose of transparency and openness, not to meet some benchmark set by a third party.

I agree the statement about resources can be reworded to better convey that the resources are not in this repository (although we'd want to check all resources local to projects here first).

**Comment by Illusiveman931** [comment]
What I mean is that additional licenses, no matter what, for code or trademark, would be better not to write on the last line of the file readme, it’s better to put it in a separate license and distribute the software under a multi-license. Well, or at least just put it in a separate file with the name "trademarks clause" (or something like that, depends on the conditions for registering a trademarks) (duplicate can be left in the file readme). Otherwise, it may mislead people that this program is distributed purely by MIT license.

**Comment by peppy** [comment]
The code *is* distributed by MIT license. To re-state, trademarks are not part of a code license in my eyes. Trademarks only affect a few strings which would need to be changes only under very specific usage conditions. It is mentioned in the project-wide README, not the LICENCE to make sure people are aware when consuming the project as a whole, rather than as a library or as individual code files.

**Comment by Illusiveman931** [comment]
You are absolutely right. but these specific usage conditions is any  form of distribution that is an identical copy or fork. your paragraph about trademark does not allow distribution of the program under the same name without your written permission, personal for every who ask. for example, if you did not give written permission to all those who made a fork on the github with same name, then they violate your paragraph about trademark (the example is not the best). Of course you have the absolute right to distribute as you want, I just recommend making it more explicit

**Comment by peppy** [comment]
So your issue is that it isn't mentioned in the LICENCE file and only the README?

**Comment by Illusiveman931** [comment]
Given that this potentially creates many license violations left at the mercy of the copyright holder (but not legal rights). then for the most part yes it is

**Comment by peppy** [comment]
We'll consider this going forward. For now I personally believe it is explicit enough but will leave this open in case others also have issue.

**Comment by Illusiveman931** [comment]
I do not urge to waive the right to trademark law. the fact is that no matter how many people believe that the law on trademark is unnecessary (including you). as long as this is not on, roughly speaking, on paper it has no legal force.

**Comment by peppy** [comment]
Please include precedent (some kind of legal case where this was actually enforced) to further this conversation.

**Comment by Jeremiidesu** [comment]
While this may not be of any value, I think this is an example of what the difference between code license and trademark is: 

https://opensource.stackexchange.com/a/4277

Notably, this part:
> While the open source license gives away control of your program, trademark law means you still retain control of the brand.

**Comment by Illusiveman931** [comment]
https://twiki.org/cgi-bin/view/Blog/BlogEntry201207x1

Trademark:

Harley-Davidson mug
Let's get back to the Red Hat Enterprise Linux distribution to understand the trademark question. You may ask, couldn't someone who purchased RHEL simply redistribute the OS for free or a fee? This should be possible based on the GPL, right? Yes and no. Here is the criteria:

    Is the software pure GPL, or is it mixed with commercial license?
    Who has the commercial rights to the brand? 

RHEL is apparently purely open source, e.g. it is not mixed with proprietary code. However, the RHEL is shipped in binary form, and has the accompanying exclusive legal right to pass along the ISV certifications associated with the RHEL binary distribution. If you request the source code from Red Hat you have the right to redistribute it, but there is still the trademark question.

Red Hat has a registered trademark on the name Red Hat, e.g. they own the brand. The entity who owns the trademark has the legal rights to the commercial use of the brand. The owner can license the trademark so that others can use the brand for commercial purposes. Nobody can sell Harley-Davidson merchandize without permission from Harley-Davidson Financial Services. A trademark owner has the duty to defend a trademark - if a trademark is not defended it becomes common good, e.g. the trademark is lost. We had a case in 2010 where Seibert Media stated in Google ads that "TWiki, the grandfather of all enterprise wiki systems is no longer maintained" while promoting their own fork of TWiki. This was a clear violation of German laws on comparative ads and trademark laws, and we had to defend it.

So, is there a free (as in beer) distribution of RHEL? Yes, but under a different name: CentOS is a rebranded RHEL in binary form. CentOS is a very popular Linux distribution used by many ISPs; it is as stable and as secure as RHEL. Is the CentOS distribution legal? Absolutely, based on GPL, copyright and trademark. Red Hat's trademark is not infringed, so Red Hat has no need to defend it. Is it ethical? Questionable. Does Red Hat lose business? Possibly. On the other hand, companies currently using CentOS who want to get support can easily switch the RHEL. So the large footprint of CentOS can be a lead-gen for Red Hat.

**Comment by peppy** [comment]
That's actually arguing in the opposite direction and suggests that [GPL](https://wptavern.com/the-gpl-license-doesnt-provide-the-freedom-to-infringe-registered-trademarks) doesn't enforce trademark. Nor should MIT or any other licence.

Explicitly waiving that may be more helpful to users but if a user is planning on commercially distributing a project they should be reading the README.

I'm against having long-winded discussions on this repo regarding the intrinsics of open source licensing, so I think it may be best to close this discussion for now. I'll have a talk with the internal team whether we would consider switching to apache or firefox license just for the explicit mention that code-licencing-does-not-cover-trademark-or-patent-law, but probably not worthwhile continuing discussion here.

Thanks again for your input!
