### ISSUE TITLE
While holding down the left/right button in osu! standard, you can't toggle the ingame overlay (shift + tab).

### ISSUE THREAD

**Issue by Leixor** [ppy/osu#9237]
**While holding down the left/right button in osu! standard, you can't toggle the ingame overlay (shift + tab).** 

I didn't write this as a bug report as I assume that this is probably somewhat intended in the design of the input logic. 

Just wanted to ask here if it is indeed intended and if yes, why this is the case? If yes and you don't want to explain thats fine as well was just interested. 

I know I have probably a very specific use case here. I play with the ingame overlay disabled 99% of the time, but during spinners or long sliders I want to glance at my accuary/combo and as my left/right is A/D, I can press shift + tab while holding down A/D and this currently doesn't get registered as input.

**Comment by Joehuu** [comment]
I can't seem to reproduce. Notice that I'm holding B1.

![FN4exnUUxt](https://user-images.githubusercontent.com/35318437/84183438-c5b7b000-aa40-11ea-94af-60a3e1762786.gif)

**Comment by Gabixel** [comment]
Depending on the keyboard, it could be [the same / a similar problem that happened to me](https://github.com/ppy/osu/issues/7999#issuecomment-593908403) (something about a lack of _n_-key rollover). So I guess we should ask for some info of his keyboard (for example, if it's very old, the model etc.) (?).

**Comment by Leixor** [comment]
Okay the behavior described in the issue was tested on my linux **laptop**, which seems to be the culprit here. 

I normally play on windows + mechanical keyboard, just didn't think about the lack of n-key rollover for this specific issue. With my mechanical on my linux it works as expected.

The build in laptop keyboard can technically register more than 2 keys pressed at a time, but sometimes it just doesn't specifically if there is a great enough timewindow between the key presses, which seems to be a really weird behaviour.

Issue can be resolved then, as it seems to be a nkey-rollover problem at not something on your part.

**Comment by bdach** [comment]
Closing as resolved.
