### ISSUE TITLE
Add keyboard shortcuts for switching modes/toggling mods

### ISSUE THREAD

**Issue by uwu-osu** [ppy/osu#9238]
**Describe the new feature:** 

In stable, as many people do not use it, you can toggle mods by pressing certain keys, for example, Q is for to toggle easy mod.
Lazer nor stable do not let you toggle what mode you decide to play on the other hand, which to me, seems a little weird?
I wish to see this in the future for lazer, and also the same for toggling mods if that isnt in there yet ^^

**Proposal designs of the feature:** 

I can comment some links to images or things like that tomorrow, its 10:21PM and I just wanted to go ahead and make the feature request

I hope you understand where I am coming from, if not, please let me know

**Comment by bdach** [comment]
This actually is already implemented. Try <kbd>Ctrl</kbd>+<kbd>1</kbd>..<kbd>4</kbd>.
