### ISSUE TITLE
Relax replays imported from stable doesn't play properly

### ISSUE THREAD

**Issue by ciiii0001** [ppy/osu#9243]
**Describe the bug:**
Relax replays imported from stable doesn't play correctly in lazer. The cursor movement is correct, but it shows every note as a miss (even if the cursor is on the right place at the right time).
Relax replayer generated "natively" in lazer doesn't suffer from this issue.

How to reproduce:
1) Make sure you have relax scores in stable. If not, play a map with relax, press F2 to save replay at result screen, and double-click the .osr file to import that replay
2) Launch osu!lazer, choose settings->import scores from stable
3) watch the replay of imported relax scores

**Screenshots or videos showing encountered issue:**
![图片](https://user-images.githubusercontent.com/66686071/84164868-9dae6800-aaa5-11ea-822d-4a0475a65356.png)

**osu!lazer version:** 
2020.603.0

**Logs:**

[performance.log](https://github.com/ppy/osu/files/4752990/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4752991/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4752992/updater.log)
[database.log](https://github.com/ppy/osu/files/4752993/database.log)
[network.log](https://github.com/ppy/osu/files/4752997/network.log)

**Comment by frenzibyte** [comment]
Resolved in https://github.com/ppy/osu/pull/27145
