### ISSUE TITLE
Ctrl+Enter doesn't launch AutoPlay when relax mod is turned on

### ISSUE THREAD

**Issue by ciiii0001** [ppy/osu#9244]
**Describe the bug:** 
Usually, we press Ctrl+Enter to launch an AutoPlay on the selected map. But if the relax mod is turned on (in the mod selection), Ctrl+Enter doesn't launch AutoPlay anymore. Instead, it starts the map with relax mod (just like press Enter only).
(In stable, Ctrl+Enter always launch AutoPlay even if relax mod is on, and I guess lazer should match stable behaviour here)

**Screenshots or videos showing encountered issue:** not required I guess

**osu!lazer version:** 
2020.603.0

**Logs:** not required I guess

**Comment by peppy** [comment]
So we basically need a way of deselecting incompatible mods.
