### ISSUE TITLE
Osu! Lazer crashes on startup, works when not tabbed into game.

### ISSUE THREAD

**Issue by C4rter10** [ppy/osu#9251]
As soon as i start lazer up, it crashes, however if i alt+tab out before the intro begins the game will stay running, as soo as i try to go into the game it will crash.

![osucrashgif](https://user-images.githubusercontent.com/66751703/84316160-8d0ff780-ab62-11ea-9ef7-91e8cbf62f0e.gif)

osu!lazer version:2020.603.0

Couldnt locate logs for lazer.

Computer Specifications:
Processor: Intel(R) Core(TM) i7-6700 CPU @3.40GHz 3.40GHz
Installed RAM: 16.0GB
GPU: Nvidia GTX 1070
System type: 64-bit operating systen, x64-based processor
Edition: Windows 10 home version 1903

**Comment by peppy** [comment]
closing as no logs were provided. please provide them if you need further help (although the above reply will probably help you enough).
