### ISSUE TITLE
UBPorts app port

### ISSUE THREAD

**Issue by Qiangong2** [ppy/osu#9252]
**Describe the new feature:** A port of the Android/Linux app to UBPorts/Ubuntu Touch

**Proposal designs of the feature:** 
The general release of the pinephone has occurred and with it, a wider audience of UBPorts users. An osu client would be a great addition to the openstore on UBPorts. Any chance?

Here's the app documentation: http://docs.ubports.com/en/latest/appdev/

**Comment by peppy** [comment]
We are not opposed to contributions increasing platform support, but are not actively looking at this right now due to other focuses.
