### ISSUE TITLE
Unexpected input lag

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#9255]
Unexpected input lag
---------------------------------

Osu!Lazer: app-2020.603.0

Recently encountered a unexpected input lag in osu!lazer.
Usually the input lag in MULTITHREADED should be about 0.01-0.04ms, but in recent game, it gose to about 2.4 - 4+ ms with rendering by external graphics card. With integrated Graphics, it is about 200+ ms or cursor just teleporting.

Details about the latency please check video and logs attached to the issue.

Thanks for help.
### Additional information:
_Please notice that Draw lag in integrated graphics card video is because the screen capture, input lag are same as not caputring the screen. Some times you may notice that cursor are teleporting._

_This only happens when holding any keyboard key_

_Singlethreat also has this problem, but not serious_

### Logs and videos
Video(running with Integrated  graphics card (Multithreat)): https://streamable.com/2kbd0v
Video(running with external  graphics card (Multithreat)): https://streamable.com/ifhs6l

Logs: 
[SquirrelSetup.log](https://github.com/ppy/osu/files/4764090/SquirrelSetup.log)
[database.log](https://github.com/ppy/osu/files/4764100/database.log)
[network.log](https://github.com/ppy/osu/files/4764101/network.log)
[performance.log](https://github.com/ppy/osu/files/4764102/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4764103/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4764104/updater.log)

[DxDiag.txt](https://github.com/ppy/osu/files/4764116/DxDiag.txt)

**Comment by peppy** [comment]
Something on your system is likely causing this, if it only happens when holding a key. Either drivers or another application hooking your input.

**Comment by Kiddo-Kris** [comment]
The problem solved. I just leave a solution here for anyone may encounter same problem.

This problem in my case is caused by Windows 10 Input method. If you are using any input method that is NOT English (Chinese for me) , then holding a key will cause huge input lag.

The problem were solved by _**Removing any non-English input method**_ in Windows 10 - Language.
