### ISSUE TITLE
game not working in borderless mode

### ISSUE THREAD

**Issue by TriangleCow** [ppy/osu#9259]
I uninstalled Osu Lazer a couple days back and decided to reinstall it, but now, it just black screens and crashes whenever I try to run the game in borderless mode. It used to work fine. Here is the crashlog:

Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5e9fbf92
Faulting module name: nvoglv64.dll, version: 26.21.14.4614, time stamp: 0x5ebf2a80
Exception code: 0xc0000409
Fault offset: 0x0000000001000f9d
Faulting process id: 0x3874
Faulting application start time: 0x01d64040d3d4dc73
Faulting application path: C:\Users\BrianPC\AppData\Local\osulazer\app-2020.603.0\osu!.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d5216eae94436d77\nvoglv64.dll
Report Id: 974e122f-b874-4d14-b024-b57435b12039
Faulting package full name: 
Faulting package-relative application ID:

**Comment by smoogipoo** [comment]
> Faulting module name: nvoglv64.dll

This is an issue with your graphics driver. Try updating it.
