### ISSUE TITLE
osu!lazer not working

### ISSUE THREAD

**Issue by ILuvSkins** [ppy/osu#9262]
osu!lazer stopped working: whenever i tried to start osu!lazer, nothing would happen at all! nothing popping up, no error message, and i couldn't find anything weird in the logs. what should i do? should i just uninstall it and reinstall it again? please help me, i really like osu!lazer and i want it to work again. another bug i have found when osu!lazer was working was that the cursor sometimes wouldn't show up in the menus, but it would show up in gameplay.
here are the logs:
[database.log](https://github.com/ppy/osu/files/4769954/database.log)
[network.log](https://github.com/ppy/osu/files/4769956/network.log)
[performance.log](https://github.com/ppy/osu/files/4769957/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4769958/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4769959/updater.log)
OS  that I use: Windows 8.1
Specs:
Lenovo B50-70 laptop
Intel Core i5-4210U
4GB RAM
Intel Family HD Graphics
512GB HDD
Version of osu!lazer: 2020.413.0

**Comment by ILuvSkins** [comment]
what details should i add?

**Comment by ILuvSkins** [comment]
i uninstalled it now but osu!lazer is still in the start menu, but it doesn't show up in the "Uninstall programs" list... what do i do now?!

**Comment by Gabixel** [comment]
It's probably just a shortcut of the app that Lazer somehow didn't remove, try reinstalling it and see if it works now.

**Comment by ILuvSkins** [comment]
ok then

**Comment by ILuvSkins** [comment]
thx! it worked!

**Comment by peppy** [comment]
is it safe to close this issue?

**Comment by Gabixel** [comment]
I think so. Also, the "_cursor sometimes wouldn't show up in the menus_" part is probably related to https://github.com/ppy/osu/issues/8487

**Comment by bdach** [comment]
Closing as resolved.
