### ISSUE TITLE
Crash when opening a local score in solo

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9266]
**Describe the bug:**
- If you don't have any local score, download it from any online leaderboard (or play a beatmap)
- Click the score from the `Local` leaderboard
- [The game crashes]

**osu!lazer version:** 2020.613.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4772323/runtime.log)

**Comment by Gabixel** [comment]
Online scores seem to work correctly

**Comment by bdach** [comment]
This is due to unincluded navigational properties at

https://github.com/ppy/osu/blob/1587d4b26fbad691242544a62dbf017a78705ae3/osu.Game/Scoring/ScoreManager.cs#L66

Locally including up to `score.Beatmap.BeatmapSet.Metadata` works but I'm hesitant to outright PR that.

**Comment by peppy** [comment]
Just score.Beatmap.Metadata should be enough.

I think this is fine to add for the time being (with the expectation that such includes will be lazy/automatic with either EF3 or Realm).

**Comment by peppy** [comment]
You're actually correct... BeatmapInfo doesn't always have an associated metadata for whatever reason.
