### ISSUE TITLE
cursor not showing up in menus

### ISSUE THREAD

**Issue by ILuvSkins** [ppy/osu#9267]
**Describe the bug:** 
the cursor is invisible in menus, but it does show up in gameplay for some reason, this started happening after i updated osu!lazer to the latest version. i tried restarting it, but the cursor was still invisible in menus, i tried changing some settings but nothing worked.
**Screenshots or videos showing encountered issue:** 
![osu_2020-06-12_21-00-07](https://user-images.githubusercontent.com/66824635/84532905-c9249300-acef-11ea-93cb-da070636e8a5.jpg)
![osu_2020-06-12_21-12-35](https://user-images.githubusercontent.com/66824635/84533801-8a8fd800-acf1-11ea-844e-6447f316b591.jpg)
**osu!lazer version:** 
2020.613.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/4772462/database.log)
[network.log](https://github.com/ppy/osu/files/4772463/network.log)
[performance.log](https://github.com/ppy/osu/files/4772464/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4772465/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4772466/updater.log)

**Comment by bdach** [comment]
Are you on an Intel HD Graphics 4000 graphics card?

**Comment by ILuvSkins** [comment]
i can't remeber, but i think it was an Intel Family HD Graphics or something like that
and here is the "System" window:
![sys](https://user-images.githubusercontent.com/66824635/84536275-27547480-acf6-11ea-9ad5-46ea95cee4c9.PNG)

**Comment by ILuvSkins** [comment]
i don't remember, i think it is an Intel Family HD Graphics or something like that
and here is a screenshot of the "System" window:
![system](https://user-images.githubusercontent.com/66824635/84536446-874b1b00-acf6-11ea-96e5-05f4176b599b.PNG)

**Comment by bdach** [comment]
We're already aware of this issue - see #8487. Unfortunately it's hardware-specific.

**Comment by ILuvSkins** [comment]
oh, now it appeared - it seems to do this at random...

**Comment by ILuvSkins** [comment]
sometimes i start it and the cursor is not showing up, but i launched it again and now it is showing up

**Comment by Gabixel** [comment]
Maybe you can try enabling the "bypass front-to-back render pass" option in Lazer settings ([as proposed by smoogipoo](https://github.com/ppy/osu/issues/8487#issuecomment-618124942) in the linked issue), just to see if it does something...
