### ISSUE TITLE
Switching gpus on Graphics Settings won't work

### ISSUE THREAD

**Issue by kravque** [ppy/osu#9277]
**Describe the bug:** 
" this happened before 2 or 4 months i don't remember "

so i have two gpus which they are:
**Intel(R) HD Graphics 620
AMD Radeon r7 m340/m440**

- and i want to switch to the intel one because it provides a better support/performance on OpenGL apps !
- on osu!stable, the performance is way better with intel and now i'm trying to switch to it on lazer but it won't work for some reason.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/ycxpgi

**osu!lazer version:** 
2020.613.0

**Logs:**
not needed i think

**Comment by bdach** [comment]
I'm on an NVIDIA card, but I also have an option to choose a graphics processor via the context menu:

![image](https://user-images.githubusercontent.com/20418176/84575303-6cd37900-adac-11ea-96f1-9b8ee4933f4a.png)

Do you have such an option, and does it work? Also, have you looked whether the system-level setting isn't getting overridden by AMD drivers?

Although, as an aside, I find your claim that apps run better on the integrated cards quite strange...

**Comment by Jeremiidesu** [comment]
> Although, as an aside, I find your claim that apps run better on the integrated card quite strange...

In some situations, running directly on integrated graphics allows for better performance due to not needing to copy the rendered image from the dedicated GPU to the integrated GPU before displaying it onscreen

**Comment by kravque** [comment]
> Do you have such an option, and does it work? Also, have you looked whether the system-level setting isn't getting overridden by AMD drivers?

There's no option to manually start app with selected gpu, and yes i looked before and tried to make windows use intel gpu by lowering the power use of amd and still it didn't work, i looked into amd's control panel and found nothing useful

also i tried before using different drivers and still same issue.

> In some situations, running directly on integrated graphics allows for better performance due to not needing to copy the rendered image from the dedicated GPU to the integrated GPU before displaying it onscreen

So it wasn't because intel was better on OpenGL apps, but because amd gpu was just copying every image to the integrated graphics and then it starts to display the image on my screen which it causes huge effect on the performance when it comes to light games ? i was literally searching for this before because i was thinking why when i play something i had too many stutters/microstutters and the copy feature starts every time i play something.

**Comment by Jeremiidesu** [comment]
In Windows 10, there's an option in the System Settings, under "Display", called "Graphics settings", in which you can set which GPU to use for which apps. I believe that should work.

**Comment by bdach** [comment]
> In some situations, running directly on integrated graphics allows for better performance due to not needing to copy the rendered image from the dedicated GPU to the integrated GPU before displaying it onscreen.

Right, that makes more sense.

> In Windows 10, there's an option in the System Settings, under "Display", called "Graphics settings", in which you can set which GPU to use for which apps. I believe that should work.

That is the exact option which the video in the opening post shows.

<hr>

I'm not sure that we are able to do anything about this. Which card the OS uses is up to the OS's discretion and I don't think we should be adding any functionality to the game that would affect it. I'm going to close this issue for now.
