### ISSUE TITLE
show Windows cursor setting, and multi-touch for mobile

### ISSUE THREAD

**Issue by ILuvSkins** [ppy/osu#9278]
**Describe the new feature:** 
i have two new features:
1. a setting that displays the cursor from Windows, for those with the invisible cursor problem (i am one of those)
2. multi touch on osu!lazer on mobile: you can use one finger to aim, and two other to press Z/X buttons, like in osu!droid. i use osu!lazer on mobile too and it's pretty hard singletapping maps with only one finger :/

**Comment by bdach** [comment]
Point (1) isn't happening. The only acceptable goal is to fix the actual issue, not to add workarounds for it.

Point (2) is a duplicate of #4201.
