### ISSUE TITLE
Osu! Crash (on Macbook)

### ISSUE THREAD

**Issue by 1144Ping** [ppy/osu#9279]
**Describe the crash:** 
I just put in a new skin for Osu! and played a random map.  However, it just got stuck in one place without anything happening.  I tried to quit it but it just froze there.  I then had to use an activity monitor to force quit the whole Osu! application, but the screen is still there frozen.  I was panicking and for some stupid reason decided to delete the Osu application.  After that, I tried many ways to get rid of the screen but nothing works.

**Screenshots or videos showing encountered issue:** 
<img width="1440" alt="Screen Shot 2020-06-13 at 3 54 28 PM" src="https://user-images.githubusercontent.com/66885637/84577970-de043380-ad8e-11ea-9a05-ce8fce0a05ce.png">
By the way, the cursor won't move either
**osu!lazer version:** 
Not sure about this (I only downloaded the app for 2 days so I don't know too much about it)

**Logs:**

Not sure about how to get this
**Computer Specifications:** 
MacBook Pro

**Some extra stuff going on**
Unable to exit it, and then unable to redownload Osu! due to weird reasons, and unable to update computer because of this

**Comment by jai-x** [comment]
This Github repo is *only* for development and issues for osu!lazer.

osu!stable bug reports can be reported here: https://github.com/ppy/osu-stable-issues/

**Comment by 1144Ping** [comment]
oh sorry i am at the wrong one
