### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by f1reflyyyylmao** [ppy/osu#9280]
**Describe the bug:** 
I fill my username into the username field and the password into the password field. I press 'Sign in'. "Stay signed in" is unchecked (although apparently it doesn't matter). It seemingly does the request. It goes back to the login fields. The network log file reports:

```
http://ix.io/2p6W
```

When I try to log into my account on the website with the same credentials it works fine. My password consists of 26 ascii chars only. I made very sure I put my username and not my email.

**Screenshots or videos showing encountered issue:** 
Nothing interesting

**osu!lazer version:** 
2020.613.0.r16.a8e83c5be5-1

**Logs:**
[database.log](https://github.com/ppy/osu/files/4775351/database.log)
[network.log](https://github.com/ppy/osu/files/4775352/network.log)
[performance.log](https://github.com/ppy/osu/files/4775353/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4775354/runtime.log)

**Comment by bdach** [comment]
Please try unchecking both "Remember username" and "Stay signed in" and logging in again.

**Comment by f1reflyyyylmao** [comment]
Tried it, doesn't work. I also moved my whole osu directory to osu.old and started from scratch, still doesnt work unfortunately

**Comment by bdach** [comment]
Is this a new account, i.e. have you ever logged onto the stable client with those credentials before?

**Comment by f1reflyyyylmao** [comment]
No, I logged in before. Please discard my issue, I mistook a 0 for an O. I'm very, very sorry.
