### ISSUE TITLE
Storyboard samples starting at time 0 do not play

### ISSUE THREAD

**Issue by H2n9** [ppy/osu#9284]
**Describe the bug:** 
https://osu.ppy.sh/beatmapsets/1011011 uses event samples to play voice clips throughout the map.

Currently in master, the voice samples do not get decoded (and are skipped) if you follow the debugger through the decoding process.

I believe this is a regression over previous lazer versions.

Skipped events -
`//Storyboard Sound Samples
Sample,0,0,"easy1.mp3",100
Sample,5610,0,"easy2.mp3",100
Sample,35510,0,"easy3.mp3",100
Sample,64587,0,"easy4.mp3",100
Sample,79356,0,"easy5.mp3",100`

**Screenshots or videos showing encountered issue:** 
osu!lazer 2020.613.0
https://streamable.com/nni03p

osu!stable
https://streamable.com/m0uz02

**osu!lazer version:** 
2020.613.0 and master

**Comment by bdach** [comment]
From what I can see the assertion that the samples aren't getting decoded is incorrect. Storyboard sample playback is just broken right now.

With #9281 I can hear all of the storyboard samples, *except* for the first one. Possibly caused by more lifetime woes.

**Comment by bdach** [comment]
Actually, it's not lifetime in this case - it's this accursed conditional again:

https://github.com/ppy/osu/blob/2e6efebb17aa6747a59ba876d3f715436068cbe4/osu.Game/Storyboards/Drawables/DrawableStoryboardSample.cs#L54

The very first frame of playback, `Time.Current == Time.Elapsed`. If the sample starts at time 0, then the sample will fail this check and never play.

Fixing that particular case is trivial, but do we know of any storyboards that have samples playing at a *negative* time, and if so, how does stable handle that?

**Comment by H2n9** [comment]
I'm not sure if I'm making a mistake here but even with #9281, the voice samples still do not play correctly.

With #9281
https://streamable.com/bj24um

**Comment by bdach** [comment]
How did you acquire the map in question? I freshly downloaded it off direct and it doesn't seem to have the same issues.

You could try deleting the map, restarting and then re-downloading it through direct to see if anything changes.

**Comment by H2n9** [comment]
Ah, re-downloaded it and yeah, can hear all but the voice first sample as you said. Dunno how my beatmap was messed up like that. Thanks.

**Comment by peppy** [comment]
@bdach i believe `<=` is actually the more correct comparison in that failing statement. This should still work for negative timed samples, because in those cases the starting time of the clock is also equally negative.

**Comment by H2n9** [comment]
#9827 does not fix the problem when using mods that increase the playback rate above 1x ( DT, NC, WU ). Works in all other cases.

**Comment by peppy** [comment]
Sounds like the UO adjustment due to playback rate modification may be shifting the zero-point and thus missing sample playback. Not sure this is a huge issue. Beatmaps shouldn't be playing samples at the perfect entry point (why is there no lead-in time?)

**Comment by H2n9** [comment]
I'm finding more issues related to this - 
Sample playback in 2020.616.0 is very inconsistent.
With https://osu.ppy.sh/beatmapsets/1011011 the first few samples will play correctly but later samples will not trigger ( in both nomod and rate adjusted mods). I was able to sometimes get them to trigger by seeking near but its quite inconsistent.

With DT ( this also happens with nomod )
https://streamable.com/5acl42
Note that samples at 0:42 and 0:52

Should I compile this for a new issue?

**Comment by bdach** [comment]
I'm betting it'll be related to the lifetime issues I described in discussion of #8145.
