### ISSUE TITLE
Auto is broken in catch on maps with stacked spinners

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu#9304]
**Describe the bug:** 
The issue can be seen in the videos below.
While auto also can't fc Avalon in stable it doesn't have this weird speed-up effect when using it.
As far as I can tell it also skips certain parts of the map, the ones just after the spinner(s).
The same thing happens in Der Wald, at 0:49 there are multiple stacked spinners which cause auto to bug out again and speed up? for some time. 
I don't know for certain if this happens because of the stacked spinners, but this seems to be the case.
To me it looks like auto is trying to catch all bananas from the spinners and for some reason stacked spinners don't work well with this and start after one another (if that makes sense)
->stack 4 1s spinners, causes the 1s spinner to become 4s (to auto), but auto speeds up because there is other notes? 
The maps shown in the videos below:
https://osu.ppy.sh/beatmapsets/345834#fruits/765569
https://osu.ppy.sh/beatmapsets/406881#fruits/884085

**Screenshots or videos showing encountered issue:** 
https://twitter.com/KevKjef/status/1273160344748392450?s=20
https://twitter.com/KevKjef/status/1273161622010421251?s=20

**osu!lazer version:** 
2020.616.0

**Comment by CH-ND-N** [comment]
I am ready to work on this, please assign this to me.

**Comment by smoogipoo** [comment]
We don't really assign issues to non-team members, but feel free to take on the task!

**Comment by vltspr** [comment]
Please close this issue, the mentioned PR fixed the problem.
