### ISSUE TITLE
Visual quality of sprites / buffered containers degrades at very high resolutions

### ISSUE THREAD

**Issue by Elepover** [ppy/osu#9305]
**Describe the bug:**
Some images at different places have very low-quality rendering. I found this on both home background and beatmap preview.

This is platform-specific, can be reproduced stably on iPad here, but not on Windows or Android.

Device is iPad Pro 11 inch (2018).

**Screenshots or videos showing encountered issue:** 
![378806B1-013C-4235-8050-69DB7DEE5AC8](https://user-images.githubusercontent.com/11826985/84873674-2f296580-b0b6-11ea-9898-fdde8200743f.png)
![E8675FD1-AC93-422C-8206-7118A48F31CE](https://user-images.githubusercontent.com/11826985/84873698-36507380-b0b6-11ea-9d94-9493d797895c.jpeg)

**osu!lazer version:** 
2020.616.0 (TestFlight)

**Comment by smoogipoo** [comment]
Did you change the UI scale? The wedge is set to not refresh on resize so performance isn't degraded.

**Comment by peppy** [comment]
Another possibility is starting a screen in portrait and switching to landscape.

**Comment by Elepover** [comment]
> Did you change the UI scale? The wedge is set to not refresh on resize so performance isn't degraded.

Yeah, I did change UI scale up. After restoring to default, it now looks like:
![598C9326-D4CF-4ABF-BA6B-6B39EA5EB0FE](https://user-images.githubusercontent.com/11826985/84876314-a90f1e00-b0b9-11ea-8db9-19c9d65be10e.png)

Beatmap preview quality is now better.
![931938EB-8C60-4E83-94DD-8CD0889BD937](https://user-images.githubusercontent.com/11826985/84876560-ed9ab980-b0b9-11ea-86b0-25141cf8714c.jpeg)

> Another possibility is starting a screen in portrait and switching to landscape.

I tried the following:

| Start | Changed to | Background | Song Preview |
| --- | --- | --- | --- |
| Portrait | Landscape | bad | **good** |
| Portrait | (remains portrait) | bad | **good** |
| Landscape | Portrait | bad | **good** |
| Landscape | (remains landscape) | bad | **good** |

All at default UI scale.

**Comment by peppy** [comment]
I mean changing while you are already at a screen, not startup.

The main menu background is too lower resolution for the aspect ratio / pixel density of that device. I'm not sure if/when we will fix this.

**Comment by Elepover** [comment]
OK I found that if you don't turn up UI scale, image quality of the song preview wedge is fine. But any UI scale change will crap it (both changing it during runtime and startup with a non-default scale)

**Comment by peppy** [comment]
Depends if you're looking at the fonts of the background. There are two issues at play here, one which cannot be fixed (beatmap assets are low resolution).
