### ISSUE TITLE
Hyperfruits are unreadable when using skins

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu#9306]
**Describe the bug:** 
In lazer hyperfruits are different then in stable. Most notably the (red) glow on the outside has changed into a completely red fruit.
Since the hyperfruit is a different colour (=essentially a different object), it is harder to read, especially on dense hyper-sections (since this means red glowy circle-spam).
I do not know how far skin implementation is in lazer, but currently using ctb skins does not show hypers, presumably because the red glow isn't there anymore?
Although the red glow is actually there on the default stable skin, so this contradicts that statement and supports this being a bug.

Either way, myself and essentially all other players, use a variant of the square or circle skins shown below.
While not everyone uses full white fruits, red glows on hyperdashes are used everywhere (as far as I am aware).
Because of this, I see this as a bug, but I guess it is in some way a feature request to make it possible to only have the red-glowy outline on hyperfruits.

Also, while I can see some players using this new fruit as hyperfruits, more experienced players would prefer the red-glow instead of the red fruits, as this prevents them from reading hyperfruits as they did before and I/we are used to the red outline.

*Note: while it is possible to play without hyperfruits, it is significantly harder to do so.

**Screenshots or videos showing encountered issue:** 
Lazer standard skin:
![hypernoskin](https://user-images.githubusercontent.com/64087607/84873991-4a7b7d00-b084-11ea-81bd-507b11b0b5cd.PNG)
Lazer + Square skin:
![hypersquareskin](https://user-images.githubusercontent.com/64087607/84874003-4c454080-b084-11ea-8213-514d34723f2c.PNG)
Lazer + Circle skin:
![hypercircleskin](https://user-images.githubusercontent.com/64087607/84874012-4e0f0400-b084-11ea-8d2c-e3a227aadb9f.PNG)
Stable + Square skin:
![hypernormal](https://user-images.githubusercontent.com/64087607/84874279-acd47d80-b084-11ea-927e-aafd16f15876.PNG)

**osu!lazer version:** 
2020.616.0

**Comment by smoogipoo** [comment]
We're gonna need the skin for this one, because I can't replicate:
![image](https://user-images.githubusercontent.com/1329837/85541167-bc3e6280-b652-11ea-8ac5-17d6191881ab.png)

**Comment by KevKjef** [comment]
I used 'my' skin: https://www.dropbox.com/s/jo502fz6bl91oo1/nikS.osk?dl=0 (the squares) and DakkyChan's skin http://puu.sh/CIIJ0/831c0c03b5.osk for the circles

**Comment by smoogipoo** [comment]
Thanks, was able to replicate.
