### ISSUE TITLE
Images loading slower since 2016.616.0

### ISSUE THREAD

**Issue by Elepover** [ppy/osu#9307]
**Describe the bug:** 
After updating from 2020.612.0 to 2020.616.0, the background loading is much slower on both startup and first time entering song seletion.

Yet another iOS-specific bug. Android (Pixel 3) is fine.

**Screenshots or videos showing encountered issue:** 
![output](https://user-images.githubusercontent.com/11826985/84879415-c645eb80-b0bd-11ea-8d05-77e7b4279d2c.gif)

**osu!lazer version:** 
2020.616.0 (TestFlight)

**Comment by peppy** [comment]
Sounds like a potential regression from the front-to-back transparency check for sprites. @smoogipoo was any performance checking done on that?

**Comment by smoogipoo** [comment]
There wasn't, just appeared fine but didn't consider low power devices.
