### ISSUE TITLE
Fonts are replaced with strange lines and trackpad doesn't work (on macOS 10.14.6)

### ISSUE THREAD

**Issue by YeaToast** [ppy/osu#9308]
![Screen Shot 2020-06-17 at 7 56 40 PM](https://user-images.githubusercontent.com/51266541/84932493-aa9a0f80-b0d4-11ea-8f94-a91b03da42b6.png)
This is not normal. It worked before. I can't update. I can't even click as i'm playing with a weird playstyle (Trackpad+ZX). How do i reset my settings?

**Comment by bdach** [comment]
Please attach logs from `~/.local/share/osu` as requested by the issue template. Additionally, please press <kbd>Ctrl</kbd>+<kbd>F3</kbd>, take a screenshot of the *Texture Atlases* window and attach it here.

I'm not sure resetting settings can do much if the trackpad is the only pointing device you have.

**Comment by YeaToast** [comment]
[database.log](https://github.com/ppy/osu/files/4794348/database.log)
[network.log](https://github.com/ppy/osu/files/4794349/network.log)
[performance.log](https://github.com/ppy/osu/files/4794350/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4794351/runtime.log)
Here are the logs.
> Additionally, please press Ctrl+F3, take a screenshot of the _Texture Atlases_ window and attach it here.
I don't understand. what yo mean by "Texture Atlases". Can you be more clear?

**Comment by bdach** [comment]
<kbd>Ctrl</kbd>+<kbd>F3</kbd> should pull up this sort of window:

![2020-06-17-200838_556x673_scrot](https://user-images.githubusercontent.com/20418176/84933644-7fb0bb00-b0d6-11ea-9650-90f83f8878d5.png)

It'll help us be able to whether the font glyphs got uploaded wrong.

**Comment by YeaToast** [comment]
For me, it just selects finder in the dock. I think you got confused. I tried every combo, but nothing.
Is there an alternative?

**Comment by bdach** [comment]
Try <kbd>Ctrl</kbd>+<kbd>Fn</kbd>+<kbd>F3</kbd> then maybe? I don't own a mac myself but the team devs do and I assume they'd notice if the shortcut just plain didn't work.

**Comment by YeaToast** [comment]
> Try Ctrl+Fn+F3 then maybe? I don't own a mac myself but the team devs do and I assume they'd notice if the shortcut just plain didn't work.

I did. I tried every possible combination, tried to edit system preferences, with no prevail.

**Comment by frenzibyte** [comment]
Since you've mentioned focusing to finder, then you're probably having these shortcuts enabled:
![image](https://user-images.githubusercontent.com/22781491/84939332-d9b97c80-b0e6-11ea-8d37-c6efd18e24ee.png)
`^F1`, `^F2` and `^F3` conflict with toggling some handy tools inside osu!lazer, please go through and disable them then try again.

**Comment by bdach** [comment]
I'll close this as the trackpad issue is tracked over at #7188 and the texture artifacting can be tracked over at #9314 as it has more info. I am pretty sure the two issues will end up being related as they already are similar enough in presentation.

**Comment by YeaToast** [comment]
Hi. Fixed the issue with Texture Atlases. Nothing wrong with them.
![Screen Shot 2020-06-18 at 11 36 44 PM](https://user-images.githubusercontent.com/51266541/85074362-b52fd400-b1bc-11ea-8334-7a198700021a.png)

**Comment by bdach** [comment]
Out of curiosity, how did you manage to fix it?

**Comment by YeaToast** [comment]
No they don't. I entered this command in the terminal - `sudo rm -R ~/.local/share/osu` - and deleted the directory. No the text sprites don't look right, but at least the command fixed the mouse issue.
