### ISSUE TITLE
Cursor stay when using touchscreen with raw input

### ISSUE THREAD

**Issue by benz-phan** [ppy/osu#9309]
**Describe the bug:** 
When i use my touch screen with raw input turn on, the cursor stay at the top left corner

**Screenshots or videos showing encountered issue:** 
https://youtu.be/hZoKeTMOFtM

**osu!lazer version:** 
2020.616.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/4795877/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4795878/updater.log)
[database.log](https://github.com/ppy/osu/files/4795879/database.log)
[network.log](https://github.com/ppy/osu/files/4795880/network.log)
[performance.log](https://github.com/ppy/osu/files/4795881/performance.log)

**Comment by frenzibyte** [comment]
From what I'm seeing in the video, swiping from top-left edge all the way to bottom-right edge with raw input on would move the cursor very slightly, but not completely locked, right?

**Comment by peppy** [comment]
Please search first https://github.com/ppy/osu/issues/3911
