### ISSUE TITLE
If I modify my DT Speed it doesn't show in replay.

### ISSUE THREAD

**Issue by porkiedev** [ppy/osu#9310]
(This is a hybrid of a bug report and feature request, not sure how it was implemented so I'm not sure if it's 100% a bug or not.)

Describe the bug: In osu!lazer, you can enable DT and change the speed (I like playing on half DT meaning 1.25 speed) and my issue is that when I finish a map with 1.25 speed and look at the replay, it shows the replay as if it were at normal DT speed (1.50)

Screenshots or videos showing the encountered issue:
(I have a widescreen monitor so it's slightly stretched, sorry.)
I first played the map on DT 1.25 then watched my replay, that way you can see how to goes back to normal DT.
https://www.youtube.com/watch?v=5PjciGIFDVg

osu!lazer version: 2020.616.0

Logs:
(Not sure you're gonna find anything but hey, here ya go.)
[network.log](https://github.com/ppy/osu/files/4796433/network.log)
[performance.log](https://github.com/ppy/osu/files/4796434/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4796435/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4796436/updater.log)
[database.log](https://github.com/ppy/osu/files/4796437/database.log)

**Comment by peppy** [comment]
Please search first https://github.com/ppy/osu/issues/8569
