### ISSUE TITLE
Extreme latency issues in any mode while using a pen tablet in osu!lazer

### ISSUE THREAD

**Issue by Bloodfallen** [ppy/osu#9311]
**Describe the bug:** 

(Quick note, this relates to #6075 )
osu!lazer runs perfectly fine no matter the settings so long as a mouse is used. Attempting to use a pen tablet (drawing tablet or whatever else people call it) brings slight latency when in exclusive fullscreen. This worsens in Windowed and Windowed-Fullscreen modes. In exclusive fullscreen, the latency is noticeable by far, but it is possible to get used to as I have done before, but it does get very annoying, and forces me back into osu!stable. Attached is a video of one map being played where you can monitor the graphs and so on. (Ignore the brief stutter in the beginning, that's my hard drive being a hard drive)

 If this is happening to me, its happening to others, even if its a minority. My system specifications are:
Ryzen 5 3400G
16GB DDR4 Quad-Channel memory
250GB SSD boot drive
6TB HDD 3700RPM
NVIDIA GeForce RTX 2060 SUPER

If logs are still required even with this information (though I don't see how they would help, plus I'm lazy as hell) please feel free to ask, and I can provide.

On a side note, if help is needed to test fixes for this bug, I am more then happy to help out, as I love lazer, I just wish it was in a playable state on my machine.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/9Ay9AiNtMhQ

**osu!lazer version:** 

2020.616.0

**Logs:**

**Comment by peppy** [comment]
I'm not sure what the video is showing (there's nothing noticeable).

If it's only happening with your tablet, it may be related to the drivers. Try setting the lazer frame limiter lower to give them a chance to process (and if you're not using official drivers, fix that).

**Comment by Bloodfallen** [comment]
> 
> 
> I'm not sure what the video is showing (there's nothing noticeable).
> 
> If it's only happening with your tablet, it may be related to the drivers. Try setting the lazer frame limiter lower to give them a chance to process (and if you're not using official drivers, fix that).

It mostly exists to show the graph during gameplay, I don't have a camera else I would provide that alongside it, however I doubt the latency would pick up well that way.

Its basically identical to the issue mentioned above. I am using official drivers for both my tablet and GPU, and I've had the bug for some time now. It wasn't present in earlier versions of osu!lazer prior to mid-to-late 2019. I have attempted frame limiting today as well, in fact just before writing this issue up, it does not solve the issue, no matter the setting.

**Comment by peppy** [comment]
The issue above is specific about *not* entering exclusive fullscreen. You are saying it only affects your tablet. These are different.

**Comment by Bloodfallen** [comment]
> 
> 
> The issue above is specific about _not_ entering exclusive fullscreen. You are saying it only affects your tablet. These are different.

Correct, I apologize if I'm coming off rude, that's not my intent, its just how I type. What I meant by this was the issue is identical as to how it looks on screen and feels, not by how the bug happens.

**Comment by Bloodfallen** [comment]
I apologize for this, but upon checking Huion's website for driver updates (even though there hadn't been any for years) there is a new beta driver which was released a couple days ago. This seems to have solved the issue for now. I'll continue testing for a while to confirm.

**Comment by Bloodfallen** [comment]
Driver update has confirmed fixed the issue. Thanks.
