### ISSUE TITLE
Storyboard samples do not play if storyboard is fully dimmed

### ISSUE THREAD

**Issue by bdach** [ppy/osu#9315]
For any beatmap which has storyboard samples, if the storyboard is fully dimmed, the storyboard samples will not play as long as it is. (They will start playing again whenever undimmed.)

The cause is very simple - `UserDimContainer`'s `dimContent` stops being present whenever the storyboard is fully dimmed:

https://github.com/ppy/osu/blob/2bbff632c251c573c7547c57ed5ec73ce72a24ea/osu.Game/Graphics/Containers/UserDimContainer.cs#L71

The obvious fix (setting `AlwaysPresent = true`) works, but degrades performance on any storyboard-heavy map (even though nothing is displayed, those cases usually are associated with a lot of time spent on `LifetimeManagementContainer`'s update method each frame, which is entirely unnecessary). Another obvious thought (setting `AlwaysPresent` on the sample itself) doesn't work because the drawable is never reached during tree traversal.

The less-obvious fix I can think of would be to somehow move all of the samples into a separate layer that would be always present on its own, but I'm not sure whether that would be a direction we want to take.

**Comment by peppy** [comment]
I guess the important thing is to define what behaviour users expect. It sounds like you think that storyboard sampled should actually be considered the same as (and toggleable with) the beatmap hit sounds checkbox?

**Comment by bdach** [comment]
That seems a bit counterintuitive to me. I think the samples should still be toggleable using the "Show storyboard" option.

The scenario concerned here is one when "Show storyboard" is on, but the background dim level is set to 100%. It seems weird to me that setting visual dim like that will also silence samples.

**Comment by peppy** [comment]
Aha, right, misunderstood that part.
