### ISSUE TITLE
Cannot open osu! lazer before and after uninstalling and reinstalling

### ISSUE THREAD

**Issue by NasaZombies** [ppy/osu#9319]
Some time when I was using osu lazer I played a beatmap and it crashed, as I thought it would. (I think it was some aspire map). I had played it before and was able to open the game back up again, but when I tried booting it back up, it would just show a black screen with no sound for a few seconds before closing. 
      Because of this, I decided I should maybe uninstall and reinstall the program, but that did not do anything at all. The logs have a lot of errors, including a bunch about resizing things. In conclusion, I get why the game crashed, but no idea why nothing is working after reinstalling the program.

**osu!lazer version:** 
2020.6.16
**Logs:**
[database.log](https://github.com/ppy/osu/files/4805428/database.log)
[network.log](https://github.com/ppy/osu/files/4805429/network.log)
[performance.log](https://github.com/ppy/osu/files/4805430/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/4805433/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4805435/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4805436/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/4805437/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4805438/updater.log)
Barely used github, so hopefully these files were uploaded.
**Computer Specifications:** 
HP Elitebook 840 G2
Windows 10 Pro 64 Bit
Intel HD Graphics 5500
i5-5200U CPU

**Comment by jai-x** [comment]
From your runtime.log file:
```
2020-06-19 15:24:22 [error]: An unhandled error has occurred.
2020-06-19 15:24:22 [error]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
2020-06-19 15:24:22 [error]: ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
```
You may have some corrupted data in your local database.
Try deleting you `client.db` file in the osu!lazer folder.

**Comment by NasaZombies** [comment]
The program runs now, but there is zero sound for some reason in the program, the intro or beatmaps. Thanks for the help!

**Comment by frenzibyte** [comment]
Please attach `runtime.log`.

**Comment by frenzibyte** [comment]
```
2020-06-19 16:23:49 [verbose]: BASS Initialized
2020-06-19 16:23:49 [verbose]: BASS Version:               2.4.15.2
2020-06-19 16:23:49 [verbose]: BASS FX Version:            2.4.12.1
2020-06-19 16:23:49 [verbose]: Device:                     Speakers (VB-Audio Virtual Cable)
2020-06-19 16:23:49 [verbose]: Drive:                      {0.0.0.00000000}.{70cdd7c8-37b4-4e70-bc36-fb4e7ef726a2}
```
Please double-check your audio devices configuration from your OS, sounds like you have `Speakers (VB-Audio Virtual Cable)` set to default or otherwise.

**Comment by NasaZombies** [comment]
Everything works now, thanks for the help.
