### ISSUE TITLE
Folder migration fails.

### ISSUE THREAD

**Issue by Seventth** [ppy/osu#9322]
**Describe the bug:** 
Migration fails when using the in-game migration option.
**Screenshots or videos showing encountered issue:** 
[Error: The process cannot access the file "x" because it's being used by another process.](https://imgur.com/6hpO2sA)
**osu!lazer version:** 
2020.620.0.0
**Logs:**

**A general note**: When doing the folder migration, it actually makes two logs folders. One in the AppData folder where lazer was prior installed and also the folder where it was trying to be migrated to. I posted both logs below.
[logs.zip](https://github.com/ppy/osu/files/4807155/logs.zip)
[logs2.zip](https://github.com/ppy/osu/files/4807156/logs2.zip)

**Comment by peppy** [comment]
Which file was in use?

**Comment by Seventth** [comment]
Client.db file from the logs states that its being used by another process

**Comment by peppy** [comment]
Can you try restarting the game and then performing migration before doing anything else? It was likely that something else was running (like an import) causing this.

**Comment by Seventth** [comment]
Actually, seems that you are correct. After going straight in after reopening lazer, it now lets me migrate without any issues. Honestly weird, but nice to know that there wasn't a problem after all.

**Comment by peppy** [comment]
Awesome. A permanent fix for this will come once we finalise the database backend.
