### ISSUE TITLE
Error while submitting Loved maps 

### ISSUE THREAD

**Issue by xasuma** [ppy/osu#9323]
There are a some loved maps (https://osu.ppy.sh/beatmapsets/90893#osu/246322 this as an example) that do not allow users to submit scores on them. The moment you finish the map you will get an error message. 

All the scores in them were from users who submitted scores shortly after it becoming loved, for some reason they worked fine for a while after becoming loved but after a certain amount of time they stop taking score submissions.

**Comment by cupppu** [comment]
This looks like it’s a stable issue, for those you can report it [here](https://github.com/ppy/osu-stable-issues)
