### ISSUE TITLE
Swapping between osu!Stable and osu!Lazer changelogs in the changelog menu causes an unhandled error

### ISSUE THREAD

**Issue by EZ2ACTux** [ppy/osu#9324]
**Describe the bug:** 
Upon opening the changelog menu in Lazer, if I click on the changelog for osu!Stable and then click back to the changelog for osu!Lazer, the game throws an unhandled error and pops open the notification shade. 
**Screenshots or videos showing encountered issue:** 
Video attached as it shows the error off better than screenshots would.

https://imgur.com/bTuGKjj

**osu!lazer version:** 
2020.620.0
**Logs:**
[network.log](https://github.com/ppy/osu/files/4807497/network.log)
[performance.log](https://github.com/ppy/osu/files/4807498/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4807499/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4807500/updater.log)

**Comment by frenzibyte** [comment]
Can reproduce, not only specific to swapping between osu!stable and osu!lazer. seems to be some issue with propagating the new selected changelog build, where the header would try to remove the new build while it hasn't been added in the breadcrumb (and shouldn't remove anyway), will try to investigate further.

**Comment by frenzibyte** [comment]
OK this has regressed from https://github.com/ppy/osu-framework/pull/3614, when the header removes the old selected build from the breadcrumb, the `Current` switches to the listing tab, when previously `Current` would stay stale I think.

After going through possible fixes through this, the only one I think is sensible would be to first add the new build to the breadcrumb and select it, then remove the old build, tested and works as expected. 

IMO we may want to have some-sort of a `ReplaceTab` method at the framework-base class `TabControl`, it would remove a specific tab and add a new tab in replace to it without switching `Current` to another tab during the operation. And if the tab requested to be removed is the selected one, then selection will transfer to the new tab.

Also the incomplete `NewsOverlay` implementation will crash in the same way as it also has the same exact logic in `NewsOverlay.showPost()`.

**Comment by bdach** [comment]
For me the easy option would be making the "change current tab on remove" behaviour toggleable by a property or override, but honestly I'm wondering whether breadcrumbs are a valid use case for a `TabControl`. Maybe we want something more specialised for that as a replacement.

**Comment by frenzibyte** [comment]
> For me the easy option would be making the "change current tab on remove" behaviour toggleable by a property or override

Not sure about this one, although it's a small chance, but what if there's a component that wants both behaviours, replacing tabs on some situations, and removing tabs with expecting tab switching to happen on other situations.

> but honestly I'm wondering whether breadcrumbs are a valid use case for a `TabControl`. Maybe we want something more specialised for that as a replacement.

Yeah may need to change, but I think that's too much for fixing such an issue, maybe something to consider later on.

> Overriding `BreadcrumbControl`'s `RemoveTabItem` might be alright, but again it's a monkey-patch.

That sounds fine as well, with exposing a boolean for whether not to do the switching logic from the base method, I think it would work.

**Comment by smoogipoo** [comment]
Here's one more possibility that I've been toying with today: make `RemoveTabItem` not throw an exception if the item doesn't exist. This would also fix this but also make `TabControl` a bit more like `List<T>` in that regard.

Thoughts? If that's an acceptable solution I'll push it out.

As for whether `BreadcrumbControl` should be a `TabControl`... The only thing that `TabControl` provides that may be of value is automatic overflow into the dropdown. Kinda arguable whether it should be, but in any case I think this should probably be supported as a valid use-case.

**Comment by peppy** [comment]
I think that's fine. Sounds like standard behaviour for `Remove` methods. Maybe have it return a bool as to whether it actually removed something.

**Comment by Hubza** [comment]
for me, it straight up just crashed the entire game after a bit of spamming. [https://youtu.be/r6u_KvHiylM](https://youtu.be/r6u_KvHiylM)

**Comment by smoogipoo** [comment]
We don't need any more reports, thanks.
