### ISSUE TITLE
merge doubletime and nightcore leaderboards

### ISSUE THREAD

**Issue by positonix** [ppy/osu#9325]
**Describe the new feature:** 

osu has 2 different speed increasing mods; doubletime (dt), and nightcore (nc). they're both the same mods with only one major difference; doubletime doesnt affect the song's pitch, while nightcore does and also adds some background sounds to the song. currently, supporters can use mod specific leaderboards, like hdhr only leaderboards, hddt leaderboards, hd leaderboards, etc. the problem is that nightcore and doubletime are seperated in the mod specific leaderboards. these two mods are identical with only one difference that barely affects gameplay. the leaderboards for these two mods should be merged.

**Proposal designs of the feature:** 
when supporters use the mod specific leaderboards to view dt/nc scores, they should be shown both doubletime and nightcore scores in the same leaderboard, instead of having the two mods seperated. additionally, when lazer is released with the daycore mode, halftime and daycore leaderboards should also be merged.

**Comment by bdach** [comment]
The scope of such a merger would be far wider than just a lazer-side change - it would also encompass web and most likely also other parts of the infrastructure. I also feel like a github issue isn't appropriate for this discussion as it's a change that should get community feedback & support.

As a personal opinion I disagree that the differences DT and NC "barely affect gameplay". The backing beats that play with nightcore make keeping tempo easier (the same way it's easier to play in the correct tempo if you have a metronome/click track playing in the background).

**Comment by positonix** [comment]
> I also feel like a github issue isn't appropriate for this discussion as it's a change that should get community feedback & support.

the reason i posted this on github is due to the fact that the suggestions subforum on osu apparently isnt being actively monitored according to the pinned thread.
> 
> As a personal opinion I disagree that the differences DT and NC "barely affect gameplay". The backing beats that play with nightcore make keeping tempo easier (the same way it's easier to play music in the correct tempo if you have a metronome/click track playing in the background).

i have to disagree on that. nightcore's background drum noises dont align with every song perfectly.

even when it does align correctly, my point stands. nightcore and dt both serve an incredibly similar purpose, and i rarely see people benefitting directly from using nightcore over dt.

**Comment by frenzibyte** [comment]
I don't see a valid reason with merging this, as @bdach pointed out, NC does affect gameplay with its backing beats. 

I would say if anything, maybe open an issue web-side about merging DT and NC leaderboards, or propose a way to show both DT and NC leaderboards, rather than requesting a huge merger of both mods.

**Comment by bdach** [comment]
> the reason i posted this on github is due to the fact that the suggestions subforum on osu apparently isnt being actively monitored according to the pinned thread.

What I'm trying to say is that because this is a major change, I would expect to see some evidence that a substantial portion of the community wants this to happen, and this repository doesn't really get that sort of visibility unless something gets randomly posted to reddit/twitter.

Right now your voice and opinion is the only one that we can see, and in my view it's not nearly enough to begin considering this.

**Comment by peppy** [comment]
i think the correct direction here is allowing OR selection for mod leaderboards
