### ISSUE TITLE
My Tablet Cursor Doesn't Move in Osu!Lazer

### ISSUE THREAD

**Issue by SnowSnowSnowSnowSnow** [ppy/osu#9327]
My tablet is a Star G640, it works out of Osu!Lazer but in Osu!Lazer it doesn't move. I've downloaded the latest version (as of 21/6/2020) and the latest driver for my table. When my friend tries to use the tablet on his laptop, (same as mine 2018 Macbook air) it works just fine.

It does not work in full screen and in windowed
my mac is running in macOS Catalina 10.15.5

Logs:
[database.log](https://github.com/ppy/osu/files/4808797/database.log)
[network.log](https://github.com/ppy/osu/files/4808798/network.log)
[performance.log](https://github.com/ppy/osu/files/4808799/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4808800/runtime.log)

**Comment by frenzibyte** [comment]
Can you state the macOS version you're running the game on? on macOS Catalina 10.15.4, with drivers installed from latest versions, my tablet works just fine. (although mine is a Star G640s, probably different from yours)

Did you make sure that the tablet doesn't work with both fullscreen and windowed modes?

Also as a side note, the logs you have provided is of a crash from another issue https://github.com/ppy/osu/issues/9324, out-of-scope from this.

**Comment by SnowSnowSnowSnowSnow** [comment]
It does not work in full screen and in windowed
my mac is running in macOS Catalina 10.15.5

**Comment by SnowSnowSnowSnowSnow** [comment]
update:
osu!lazer version: 2020.725.0
mac update: macOS catalina 10.15.6
xp-pen driver: star g640 21/7/20 11:34 am

**Comment by SnowSnowSnowSnowSnow** [comment]
it still doesn't work in fullscreen and in windowed
osu!lazer: 2020.814.0
driver: XP-PenMac_2.1.7.200805 Aug 10,2020 PM 17:14

**Comment by bdach** [comment]
There's not much point bumping this issue if there aren't any new details.

Please try running lazer with the `--sdl` command line option and checking if the tablet works then.

**Comment by peppy** [comment]
@SnowSnowSnowSnowSnow if you are still tracking this issue, please try running with `--sdl` as above.

Moving out of milestone as likely `fixed-by-sdl`.

**Comment by Joehuu** [comment]
> When my friend tries to use the tablet on his laptop, (same as mine 2018 Macbook air) it works just fine.

Consistently resolved with OTD integration, closing. Also tested on Macbook Air M1 with same tablet.
