### ISSUE TITLE
Loading animation doesn't disappear when not logged in

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#933]
The loading animation doesn't disappear in various areas when you're not logged in, for example the leaderboard details tab:
![](https://u-gi.me/PCIgI)

Or the social browser:
![](https://u-gi.me/Qcz2L)

Furthermore what do we do in the cases where we're not connected for these areas? Should we be showing a message in the area or blocking access to it?

**Comment by smoogipooo** [comment]
Discussed with @peppy current consensus is that we will be blocking access to these areas when not logged in.

Moving this to lowprio.

**Comment by Aergwyn** [comment]
Isn't the original issue with permanent loading circles basically fixed? Leaderboards displays corresponding text and direct/social just stop loading.
The remaining task would be restricting access where necessary?

**Comment by LittleEndu** [comment]
This should be addressed sooner. Just spent 10 minutes trying to figure out why ``DircetListPanel`` objects weren't drawing only to find out I'm logged out.

**Comment by peppy** [comment]
There should be a standardised message added with a button allowing the user to bring the login screen up. @arflyte poke for some input here.
