### ISSUE TITLE
Beatmap tags section bouncing when there is no beatmap source in song select

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#9335]
**Screenshots or videos showing encountered issue:** 
![a3IsLZhTml](https://user-images.githubusercontent.com/35318437/85241992-8bf88900-b3f2-11ea-95f5-48c84b758c42.gif)

**osu!lazer version:** 2020.620.0

**Comment by johnemurphy1** [comment]
I'd like to work on this issue. I've read the contributing guidelines.
