### ISSUE TITLE
display maximum score/accuracy possible during gameplay

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#9336]
this should be a setting

the idea is that during gameplay, it shows the highest score/accuracy you can get if you hit everything perfectly

example:
let's say there are 100 notes in the map and i miss a note in the whole map
before i missed, the accuracy rating will read 100%
when i miss, the accuracy rating will read 99%, as the game will assume you will hit everything perfectly after that perfectly 

this can be used to determine the best performance possible when playing

**Comment by peppy** [comment]
Definitely something we want to see added eventually.

**Comment by bdach** [comment]
I'm pretty sure the accuracy part was suggested before (#4638). I'll close that one as this one also includes score in its scope.

**Comment by Flutterish** [comment]
Sudden Death / Perfect multimod should also have an unranked third mod which will make you fail when max possible score/accuracy falls below a certain user-set treshold.

**Comment by bdach** [comment]
@Flutterish already suggested at #6642 / #8767.

**Comment by genericthing** [comment]
i think i also want to add max combo to the scope, if you miss something, the max combo possible adjusts and if you already got the max combo currently possible, then the max combo highlights orange or something

**Comment by OsoCoco** [comment]
Hello, I'm currently working to solve this issue, ill like to present these 3 ideas for the UI and receive some feedback so that I can continue with my attempt.

![Test1](https://user-images.githubusercontent.com/61520900/165683114-a6072869-3c4e-4424-90e9-d4435464d00f.PNG)
![Test2](https://user-images.githubusercontent.com/61520900/165683119-2ebbfb90-7e06-449c-9ef8-44b823b03d8b.PNG)
![Test3](https://user-images.githubusercontent.com/61520900/165683120-372e46e5-c8b1-416e-8633-cdc0d6feabb1.PNG)
.

**Comment by peppy** [comment]
First of all, I think it should be attached to the accuracy display itself, and be exposed as a `SettingSource` setting (see https://github.com/ppy/osu/pull/17586 for an example of how this can be done), so proposal 2 best matches that.

I'm not sure "MAX" reads well, though. A potential alternative would be "final" or showing a fractional display

```
100.00%
   / 89.58%
```

I think as long as you structure things as proposed (inside the `DefaultAccuracyCounter` component) then we can figure out the speicfics of the UI in the pull request. Do what you think feels good to start with.

**Comment by peppy** [comment]
Actually I'm not 100% certain on putting it within the component. Unsure if players would want to put this display somewhere else on the screen. May be worth waiting for more opinions.

**Comment by peppy** [comment]
Another very strong argument is whether this should just be a setting on the accuracy counter itself. If a user wanted to show both, they could simply create two accuracy counters – one with each display mode.

**Comment by Paladynee** [comment]
i have a silly idea: instead of showing "maximum" accuracy, there could be an option that when enabled, starts counting the "inverse" accuracy from %0 to upwards, reaching higher counts as the user misses / hits 100s

**Comment by peppy** [comment]
If the counter was to have a display mode, that could also be added as a display method alongside the other two.

```
Standard (imminent accuracy)
Count up from zero
Count down from 100%
```

**Comment by Paladynee** [comment]
`Nelite: in this case i see why "max" would be used, although maybe a better alternative would be to show the avg/max next to each other?`
Displaying it could be compressed using X%Y, X being maximum accuracy, Y being the current one.
`99.75 % 81.75`

**Comment by peppy** [comment]
That can be done via the proposal I made above (https://github.com/ppy/osu/issues/9336#issuecomment-1111787510). No further discussion is required for now.
