### ISSUE TITLE
Huge RAM consumption

### ISSUE THREAD

**Issue by Lerkeer** [ppy/osu#934]
https://youtu.be/NeuBFdLXa74
Tried to play this without "Snaking in sliders" and "Snaking out sliders". Now nothing happens with distorted sliders, cause they're totally invisible. Looks just like a single note.

**Comment by Kontorted** [comment]
If you can, please leave a response in which way you believe this is caused and how it can be fixed.

**Comment by Kontorted** [comment]
We are aware of this issue.

**Comment by Lerkeer** [comment]
The same thing happens, when i played this map by myself, there was no difference with RAM consumption.

**Comment by peppy** [comment]
cool story

**Comment by peppy** [comment]
Closing for lacking detail.

While memory usage may still be high, this issue doesn't even let GC run before checking whether it is an actual leak or just high memory during play (which is likely related to expiration logic not being implemented yet).
