### ISSUE TITLE
Game crashes then Android UI is triggered

### ISSUE THREAD

**Issue by alvarosaez316** [ppy/osu#9344]
**Describe the bug:** 
I'm on LG K10 2017 (8-core CPU, 2GB of RAM, Mali-T860MP2 GPU), running android 8.1, with ES_es system language and no root. When any kind of UI pops up [E.G. OTG connected device, or Bluetooth mini Windows], the whole game shuts down as if it was exiting fullscreen in Windows (So, it returns to the last place you were in)
**Screenshots or videos showing encountered issue:** 
https://imgur.com/ITJ5JQR
**osu!lazer version:** 
2020.620.0
**Logs:**
UI:
[runtime[2].log](https://github.com/ppy/osu/files/4816277/runtime.2.log)
[performance[2].log](https://github.com/ppy/osu/files/4816278/performance.2.log)
[network[2].log](https://github.com/ppy/osu/files/4816280/network.2.log)
[database[2].log](https://github.com/ppy/osu/files/4816281/database.2.log)

**Comment by peppy** [comment]
This is a limitation of android GL contexts and intended (best-effort) behaviour for now.
