### ISSUE TITLE
Apple Silicon & Big Sur Issue / Inquiry

### ISSUE THREAD

**Issue by StrageFaithApernum2019** [ppy/osu#9346]
Will Osulazer run in MacOS Big Sur and run in a Apple Silicon Processor before any launch of any New Products of Apple.inc 

Even if the Additional Issue were to be found

Request / Inquiry is from,
Strage Faith Apernum

**Comment by smoogipoo** [comment]
It's been less than 24 hours since it was announced. We have no idea yet, this is dependent on how the .NET team handles things.
