### ISSUE TITLE
Lazer Android still crashing on beatmap load on Multithreaded mode

### ISSUE THREAD

**Issue by Yuuhei** [ppy/osu#9353]
Lazer still crashing on beatmap load on Multithreaded mode.
Same issue on #9321 

Videos and screenshots:
https://streamable.com/i3iksa
![Screenshot_2020-06-23-19-40-37-590_com miui bugreport](https://user-images.githubusercontent.com/12794279/85400298-c85eed00-b58a-11ea-98f9-23b753616f5c.jpg)
![Screenshot_2020-06-23-19-47-03-040_sh ppy osulazer](https://user-images.githubusercontent.com/12794279/85400322-cd23a100-b58a-11ea-8961-e27a12909643.jpg)

osu!lazer version:
2020.623.0

Logs:
https://mega.nz/file/ZosECAxb#jDCt7M_5DYMyAivkW_Fma68Dk6-4TAPfGH6bm7StVcQ

Running on:
Xiaomi Redmi Note 8
Snapdragon 665
3/32GB Variant
Android 9 (MIUI 11)

**Comment by Game4all** [comment]
Weird, the PR attached to the previous issue should have mitigated the issue. May need to look further into this.

**Comment by smoogipoo** [comment]
The last build didn't contain the fix, please wait until the next build.
