### ISSUE TITLE
Add an indicator for when tournament data is still loading or fails to load from the server

### ISSUE THREAD

**Issue by MiraiSubject** [ppy/osu#9354]
**Describe the new feature:** 

When there are issues on the server side, if a user boots up osu! lazer using `--tournament` while having existing data like user IDs or beatmap IDs stored for lookup, the client will attempt to fetch data and can (partly) fail. 

In the logs you can see that the client fails to connect to the server because it either times out, throws a bad gateaway error or something similar. So, during that time no window shows up yet. 

Because it takes very long (> 10 seconds) for the window to show up a user (or at least me, twice) can be inclined to force close it. 

I'm unable to reproduce this right now for a video, cause when I started to record this the server responded properly again. 

**Proposal designs of the feature:** 
I have a couple of design proposals to show some kind of indicator that the network requests are still ongoing: 

1. A loading indicator that blocks the whole screen before `SetupScreen` shows. This includes a button that the user can press to cancel this process with the consequence that no beatmap or player data that needs to be refreshed is refreshed. 

2. Have a loading indicator somewhere on the `SetupScreen` in an `ActionableInfo` section indicating that data is still trying to load from the server and show any failures. 

Both if these proposals mean that the lookups for users and beatmaps happen while the UI is being constructed rather than before. 

I included these logs, because I first considered it a bug report, to demonstrate a scenario that could need such a thing: 

[network.log](https://github.com/ppy/osu/files/4819074/network.log)
[performance.log](https://github.com/ppy/osu/files/4819075/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4819076/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4819077/updater.log)
[database.log](https://github.com/ppy/osu/files/4819078/database.log)

**Comment by peppy** [comment]
This should only happen once ever, correct? After the first load, it is saved out to the tournament json content.

**Comment by MiraiSubject** [comment]
Oh yeah that's right. I couldn't reproduce it any more with a speed limiter or a full on block of a connection to the client.
