### ISSUE TITLE
Make it clearer for the user that importing beatmaps from stable will create copies of the beatmaps

### ISSUE THREAD

**Issue by vruss** [ppy/osu#9357]
I realise this is probably something a lot of people take for granted but it would be a nice quality-of-life improvement. 

**Describe the new feature:** 
Make it clearer for the user that importing beatmaps from stable will create new copies of the beatmaps.

**Proposal designs of the feature:** 
A popup explaining the effect and consequences of importing beatmaps from Stable and that it may take a long time depending on the number of beatmaps.

**Comment by bdach** [comment]
Adding a confirmation dialog on the action with such an explanation would be simple enough, I suppose, similarly to how deletion asks for confirmation:

https://github.com/ppy/osu/blob/2432878614f6ef65155975c50fc78123013ba66c/osu.Game/Overlays/Settings/Sections/Maintenance/GeneralSettings.cs#L44-L55

**Comment by peppy** [comment]
This will be fulfilled when we have a more interactive user-welcome screen.
