### ISSUE TITLE
osu!lazer in android. can't load egl

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu#9359]
**Describe the crash:** 
i use the vs2019+Xamarin. i can't to run osu.android in "Android Emulator"
I'm a noob Android Developer,Do you have this problem？Or this is my development environment problem

**Screenshots or videos showing encountered issue:** 
![QQ图片20200624104012](https://user-images.githubusercontent.com/52590027/85492060-26311a80-b607-11ea-8578-ead489f358ff.png)
![QQ截图20200624104530](https://user-images.githubusercontent.com/52590027/85492496-d9017880-b607-11ea-8dcb-f5fd426158bf.png)

**osu!lazer version:** 
2020.623.0

**Computer Specifications:** 
Windows10 2004
Ryzen7 2700
16g

**Comment by peppy** [comment]
Even if you were to get this to work, we recommend you develop using an actual device, as performance is unusable in the emulator. If you are looking to work on the game for a non-platform-specific issue, please use a desktop project instead.
