### ISSUE TITLE
Full Storyboard Implementation

### ISSUE THREAD

**Issue by MandL27** [ppy/osu#9373]
**Describe the new feature:** 
Making this to catalog storyboard-related regressions I've noticed between stable and lazer. Wasn't sure whether to post this as a bug report or feature request.

**Proposal designs of the feature:** 
- [ ] Pass/fail layer display (#6842)
- [ ] Triggers (#2084)
- [ ] Correct animation speeds ([6482's map](https://osu.ppy.sh/beatmapsets/5381#osu/26547)'s arm-waving animations are far slower on lazer; haven't tested others on stable yet)
- [ ] Stop SB sounds if intro is skipped (first noticed on [this map](https://osu.ppy.sh/beatmapsets/8274#osu/34262); the short loop that plays over the intro keeps playing if the intro is skipped)
- [ ] Play outros, with skip option (current lazer instead skips to results after the last hit object)

**Comment by bdach** [comment]
Cataloguing like this is not required. Epic issues didn't really take in general, and we also have the storyboard tag & projects for the same purpose.

Please open separate issues for whatever you notice instead. (Also things that aren't implemented aren't regressions.)
