### ISSUE TITLE
Game crashes if storage location is not available

### ISSUE THREAD

**Issue by Elabar** [ppy/osu#9379]
**Describe the crash:** 
Nothing. Launch it, the app won't start and stop trying after few seconds. No pop up error whatsoever.

**osu!lazer version:** 
Lazer 2020.623.1

**Logs:**
2020-06-27 07:08:14 [verbose]: ----------------------------------------------------------
2020-06-27 07:08:14 [verbose]: runtime Log for leehoemun (LogLevel: Verbose)
2020-06-27 07:08:14 [verbose]: osu 2020.623.1.0
2020-06-27 07:08:14 [verbose]: Running on Unix 19.5.0.0, 8 cores
2020-06-27 07:08:14 [verbose]: ----------------------------------------------------------
2020-06-27 07:08:14 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions 

**Computer Specifications:** 
macbook pro 13.3 2019, 256+8gb, i5 1.4Ghz

**Comment by bdach** [comment]
The log seems to be cut short. Are there any more lines following it?

**Comment by Elabar** [comment]
no, thats everything.I only have a runtime.log

**Comment by Elabar** [comment]
Updated to 2020.629.0
Problem still exists. The log files in logs folder stays the same. But I got the unexpected quit error pop up this time.
https://pastebin.com/8drJZw2r

**Comment by smoogipoo** [comment]
Hmm I can't replicate on the same OS version. Can you post your client.db file (`~/.local/share/osu/client.db`, you'll have to compress it into a .zip for GitHub to accept it).

**Comment by Elabar** [comment]
![image](https://user-images.githubusercontent.com/15872787/86104550-c350ef00-baf0-11ea-9e78-dd758c648b59.png)
Here is the file structure i have. client.db is not exists in the folder.

**Comment by smoogipoo** [comment]
Hmm, what's inside `storage.ini`?

**Comment by Elabar** [comment]
Realised the issue. The path to the storage is external drive and the external drive was not plugged in.
Maybe should add a fallback path for this instead of hard crashing the game?
