### ISSUE TITLE
Osu!lazer jump map controls doesn't work well

### ISSUE THREAD

**Issue by iljamuskee** [ppy/osu#9380]
**Describe the bug:** 
i tried to play a jump in Osu!lazer but some times when i just clicked a circle right te game doesn't count it as a hit.
there is a lot of delay between clicking a circle and the game that count it as a hit.

**osu!lazer version:** 
osu!lazer version 2020.623.1

**Comment by bdach** [comment]
There is not enough actionable information in this issue for us to proceed in any way. Please attach a recording of some sort of the perceived delay and info about your platform & hardware specifications.

**Comment by iljamuskee** [comment]
link video:
https://mega.nz/file/V6pTyYhQ#V-yRv3IGgMBnPougk2ElCMEFA3YQv3-yKAqW8Y1USQ8

platform information and specifications: 64 bits operation system. intelcore i5-4300m cpu 2.60 GHz. 8 gb ram. windows 10 pro

**Comment by bdach** [comment]
The gameplay seems really choppy. Does it look the same on the screen as it does on the recording?

There are a few things to check here, namely:

* What graphics card do you have on your machine?
* Do you have any CPU-intensive tasks running in the background? If yes, try stopping them.
* Is the CPU/GPU overheating/throttling in any way?
* Try playing in exclusive full-screen mode.

All in all this is very likely specific to your hardware so I'd advise you to check for performance issues on your side first.
