### ISSUE TITLE
Hardcrash on cycling display modes

### ISSUE THREAD

**Issue by Craftplacer** [ppy/osu#9382]
**Describe the crash:** 
When cycling display modes (especially ??? -> fullscreen -> windowed -> borderless), osu!lazer hardcrashes.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/q3x27q

**osu!lazer version:** 
2020.603.0

**Logs:**
```
  X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0xe577e2
  Serial number of failed request:  18277
  Current serial number in output stream:  18277
```

**Computer Specifications:**
Linux 5.6.0-2-amd64 SMP Debian 5.6.14-2 (2020-06-09) x86_64 GNU/Linux
GNOME Shell 3.36.3
NVIDIA Driver Version 440.82
Server Version Number: 11.0
Server Vendor Version: 1.20.8

**Comment by bdach** [comment]
There's a chance SDL will resolve this for us, so I wouldn't pay much mind to this issue at this time.

**Comment by peppy** [comment]
@smoogipoo can you repro this? if not i'd be in favour of closing as user-linux-woe.

**Comment by smoogipoo** [comment]
Can't repro.

**Comment by peppy** [comment]
Closing for the time being. Wrong repo anyways (and not tested against SDL).
