### ISSUE TITLE
recording lazer's audio while using JACK

### ISSUE THREAD

**Issue by motorolah** [ppy/osu#9383]
Ok, so i play osu!lazer with JACK instead of PulseAudio and for some reason OBS won't pick up lazer's audio even though it does support JACK(and if i play something inside of Firefox which is using JACK as the output it does record it).
It seems like it bypasses the sink thing so i can't record the audio without using ALSA or PA.
Is there some way to record without changing driver? it's basically unplayable with ALSA/PA because of its latency

**Comment by peppy** [comment]
Please consult JACK documentation or otherwise. We cannot provide operating system level technical support here.
