### ISSUE TITLE
[iOS] Framerate drops when using trackpad or mouse

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#9388]
~~This has been happening for a long while now~~**tested to only happen with mouse or trackpad** on my iPad Pro 2020 11” 256GB, when playing the osu!standard ruleset with a keyboard and mouse connected over USB with a hub, my framerate will be “locked” to 80 FPS for some reason and randomly go back up to 120 FPS for a few seconds, then it goes back down to a consistent 80 FPS. This happens on any maps, it’s not just limited to any single map. I am also using singlethreaded mode with the 2x refresh rate FPS limiter.

I wrote in the title ‘possible’ because I have sometimes (rarely though) experienced similar behavior in other 3d applications on my iPad, so I want your opinion to see if it’s just a “me” problem or a lazer problem or both.

Also, very interesting discovery I made today. When attempting to screen record this to capture the extended/advanced FPS display, my framerate stayed at around 110 FPS and never went below that. Then when I stopped screen recording, the previous 80 FPS “lock” behavior continued

**Comment by smoogipoo** [comment]
Have you tried using multithreaded mode? I'm not sure there's anything we can really action on here - there hasn't been any changes that could affect this.

**Comment by peppy** [comment]
Can you confirm it's only when you connect the external accessories that it drops?

**Comment by ThatsNiceGuy** [comment]
It also happens with the accessories connected, and yea I’ve tried using multithreaded, input is at 120fps, audio is at 1000fps, update is at 240fps thanks to the 2x frame limited and draw is at the previously mentioned 80 with spikes to 120

**Comment by peppy** [comment]
"only" or "also"?

**Comment by ThatsNiceGuy** [comment]
always. doesn’t matter if accessories are connected or not

**Comment by peppy** [comment]
Why did you even mention them then? please avoid unnecessary detail as it makes diagnosing even harder.

I think this just sounds like we need further optimisation, i doubt it's specific to iOS.

**Comment by ThatsNiceGuy** [comment]
My bad. As for the optimization thing, I will test with older builds of the game to see when it regressed because I remember performance being stellar a few months ago

**Comment by ThatsNiceGuy** [comment]
Have started testing - Will edit this message as I go, don’t delete lol
Map tested: https://osu.ppy.sh/beatmapsets/1093465#osu/2285424
Tested with auto mod - frame limiter set to unlimited, multithreading on

2020.408.0 - perfect performance 120fps

**Comment by peppy** [comment]
Just so you hopefully learn for the future:

- There's no point in testing every release. You should bisect releases (test the oldest and newest) and if they behave the same for what you're testing, testing the rest is unnecessary.
- Now that you've established it's related to your peripherals, you should be testing an older build with the same usage. This would help us understand whether the osu!-side handling of the pointer device is causing issues, or the OS overhead (system usage) is reducing the available processing power available to osu!.

aka. please test your input devices against 2020.408.0.

**Comment by ThatsNiceGuy** [comment]
I know this is somewhat off topic but I can’t build for iOS anymore, both my hackintosh and Mac died and thus I can’t test custom builds on iOS anymore.
(Was gonna download 2020.408’s source then add the mouse input content, then run)

**Comment by peppy** [comment]
You can still test on `2020.418.0`, which is available on testflight.

**Comment by ThatsNiceGuy** [comment]
Problem is, mouse support (which I have definitely narrowed down to be the issue now) is the only thing that causes the drops and the support is unavailable in 418.0

**Comment by ThatsNiceGuy** [comment]
Done a bit of testing in the meantime and I’ve been able to deduct that:
- this is likely isolated to only the 2020 A12Z iPad Pros
- this issue does not happen when screen recording or mirroring to an external display whether over HDMI or AirPlay.

I think that this is the “enhanced performance controllers” in this model of iPad reducing graphics framerates to help reduce throttling due to the CPU’s load increasing, so when you add an additional GPU load like display capture, it bumps the GPU back into full power which helps the framerate stay over 80 FPS.

I don’t really think there’s a fix for this unless people decide that screen recording when they want to play lazer with a mouse is ok, or some “hack” is implemented to increase GPU load high enough to prevent power management kicking in.

**Comment by peppy** [comment]
going to close this as not-our-issue.

**Comment by ThatsNiceGuy** [comment]
Understandable response, Apple really fucked up 2020 iPad Pro’s power management for some applications

**Comment by ThatsNiceGuy** [comment]
https://github.com/utmapp/UTM/issues/440#issuecomment-688058508
Similar issue on another project for iOS.

**Comment by olly138** [comment]
Just like @ThatsNiceGuy mentioned - I have similar problem with less powerful iPad. VM doesn't stutter only with screen recording/ in app switcher or by entering notifications panel every few seconds.

**Comment by ThatsNiceGuy** [comment]
Completely fixed for me upon updating to iPadOS 14.1. Must be iOS/iPadOS dynamic power scheduling as I had thought

**Comment by s1rcheese** [comment]
@ThatsNiceGuy Apple likes ruining older products so people can buy their newer products instead.
