### ISSUE TITLE
Decrease in image quality and fonts

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9392]
**Describe the bug:** 
If you go to the results screen and exit it, the image and font quality in one part of the screen will drop.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/9QRyotxRlkQ
**osu!lazer version:** 
2020.629.0

**Comment by smoogipoo** [comment]
Duplicate of https://github.com/ppy/osu/issues/9305
