### ISSUE TITLE
Directory location can overflow on certain folder amount

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#9399]
**Describe the bug:** The directory location in choosing new osu! directory location can overflow if there are too many catalogs in it.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/19843905/86015172-836f0680-ba21-11ea-8444-c425da948a91.png)

**osu!lazer version:** 2020.629.0

**Logs:** -

**Comment by bdach** [comment]
I think it would look better if it had a reverse overflow menu (in a similar way that Windows Explorer/nautilus do - the most outer directories are hidden if they don't fit).

**Comment by bdach** [comment]
Closing in favour of framework issue (as that's where the component now resides).
