### ISSUE TITLE
Why not loop for "Welcome" osu theme!

### ISSUE THREAD

**Issue by yansaan** [ppy/osu#9401]
**Describe the new feature:** 
Add loop song like old osu in welcome osu theme
**Proposal designs of the feature:** 
https://youtu.be/YGJ8KI6nUhk

**Comment by frenzibyte** [comment]
Already requested and has been added, please wait for the next osu!lazer release for the feature to appear.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/9391.
