### ISSUE TITLE
Graphics are not properly displaying and the game is lagging A LOT

### ISSUE THREAD

**Issue by Sulu1415** [ppy/osu#9404]
**Describe the bug:** 
Fps doesn't go more than 25, and the graphics look too bad for some reason (please zoom in to see the problem)
**Screenshots or videos showing encountered issue:** 
![Screenshot from 2020-06-30 13-40-05](https://user-images.githubusercontent.com/67633239/86112005-7d882c80-bad8-11ea-814b-b7aa742c416c.png)
![Screenshot from 2020-06-30 13-40-13](https://user-images.githubusercontent.com/67633239/86112047-8aa51b80-bad8-11ea-9a8c-9e7a3a1e64f2.png)

**osu!lazer version:** 
latest
**Logs:**

[database.log](https://github.com/ppy/osu/files/4851038/database.log)
[network.log](https://github.com/ppy/osu/files/4851039/network.log)
[performance.log](https://github.com/ppy/osu/files/4851040/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/4851041/performance-audio.log)
[performance-update.log](https://github.com/ppy/osu/files/4851042/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/4851043/runtime.log)

**Comment by peppy** [comment]
We cannot accept your report without logs.

**Comment by Sulu1415** [comment]
How do I get the logs though? I'm on ubuntu Linux.

**Comment by peppy** [comment]
Please re-read the issue template which you deleted.

**Comment by Sulu1415** [comment]
I added the logs.

**Comment by smoogipoo** [comment]
:( There's a bug with the logging that's eating the lines we want to debug this. Please post your PC specs: GPU + CPU, maybe via `neofetch` or equivalent.

**Comment by Sulu1415** [comment]
> :( There's a bug with the logging that's eating the lines we want to debug this. Please post your PC specs: GPU + CPU, maybe via neofetch or equivalent.

![Screenshot from 2020-06-30 18-48-59](https://user-images.githubusercontent.com/67633239/86140926-7b3ac800-bb02-11ea-9823-dfbca2370dc8.png)
Here it is.

**Comment by smoogipoo** [comment]
Looks like your GPU isn't listed to have full support for OpenGL 3.0 which we currently require (i.e. it is too old).

Please check back later when we've implemented a compatibility mode for older systems.

**Comment by enoslayd** [comment]
Try starting it in window or borderless mode first before going to fullscreen, might solve the not displaying properly. Just dont forget to set to windowed or borderless before exiting
