### ISSUE TITLE
LG smartphone own recording software might crash osu!lazer

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu#9407]
**Describe the bug:** LG Smartphone VELVET (Android 10) crashes osu!lazer when recording by lg's own software

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=EDb05sf8Lto

**osu!lazer version:** 2020.629.0

**Logs:** 

(I dunno where is the logs from android}

**Comment by bdach** [comment]
Please attach the logs from `Android/Data/sh.ppy.osulazer/logs`.

**Comment by peppy** [comment]
This is probably because the application loses focus or otherwise. We can't support this sorry!

**Comment by ilsubyeega** [comment]
> This is probably because the application loses focus or otherwise. We can't support this sorry!

Thats sad :( 
If you need log whatever; [runtime.log](https://gist.github.com/ilsubyeega/4bf98182b59feaae83fbe4183fdafbdf)
