### ISSUE TITLE
First carousel load doesn't sort beatmaps with the user's choice

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9408]
**Describe the bug:** In my case, the carousel should sort by `Title`, but it seems to sort by `Artist`.
Also, looks like this issue happens when entering Solo right after starting the game (but I can't be precise on this).

**Screenshots or videos showing encountered issue:** [Video](https://drive.google.com/file/d/1mQnQZP-Ft6i-PtW7mXfs9AbHIbVt4w0P/view?usp=sharing)

**osu!lazer version:** 2020.629.0

**Comment by peppy** [comment]
@Gabixel can you reliably make this happen every startup? If possible, can you also try with only a few beatmaps loaded and see if it still reproduces?

If it does repro, please also include your `game.ini` as it may be related to another setting.

**Comment by Gabixel** [comment]
I did some tests.
On my first attempt (from scratch, 0 maps), the first time the issue happened was around 135 beatmaps (sets).
But then I decided to restart from 0 again and mark every attempt, and this is the result so far:

```
Beatmap(sets) Amount -- "issue" [carousel sorts by 'artist'] / "ok" [no issues] (at every startup)

85 --- ok
105 -- ok
125 -- ok
130 -- ok
131 -- ok
132 -- ok
133 -- ok
134 -- ok
135 -- ok
136 -- ok
137 -- ok
144 -- ok
150 -- ok
155 -- ok
165 -- ok
173 -- issue (1 time), ok (3 times in a row)
180 -- issue (3 times in a row), ok (5 times in a row)
185 -- ok (2 times in a row)
190 -- issue (1 time), ok (1 time), issue (1 time)
200 -- ok (5 times in a row)
225 -- ok (1 time), issue (1 time)
300 -- issue (4 times in a row), ok (2 times in a row), issue (1 time), ok (1 time), issue (1 time), ok (1 time), issue (2 times in a row)
// end //
```

This time, the issue happened around 173 maps (but I think it could have happened earlier if I had tried several times).
It's strange how sometimes the issue happens and sometimes it doesn't (maybe depends on the timing).
Should I include my `game.ini` anyway?

**Comment by Gabixel** [comment]
Interesting to note that when this issue happens, the carousel doesn't hide different ruleset.
As you can see, the selected ruleset is osu!, but the carousel also shows taiko/mania beatmaps in this screenshot:

![rulesets](https://user-images.githubusercontent.com/43073074/87032061-4e627100-c1e4-11ea-93f9-4b8be839b601.png)

**Comment by peppy** [comment]
Can you confirm this doesn't happen if, before going into song select, you change the currently playing track to something which isn't the intro theme? I think I may have an idea how this is happening.

**Comment by peppy** [comment]
I'd also appreciate runtime.log when this occurs.
