### ISSUE TITLE
Mod icons overlapping with accuracy on beatmap leaderboard 

### ISSUE THREAD

**Issue by vruss** [ppy/osu#9411]
**Describe the bug:** 
3+ mod plays will overlap the accuracy on the beatmap leaderboard. This happens on lower-than-native resolutions.

Similar to #9360

**Screenshots or videos showing the encountered issue:** 
4 icons overlapping accuracy:
![4 icons](https://user-images.githubusercontent.com/10886082/86134513-03f93a00-baea-11ea-9c4f-03bc429da384.jpg)

3 icons overlapping 100% scores
![3 icons](https://user-images.githubusercontent.com/10886082/86134661-330fab80-baea-11ea-8158-35d60c81af1f.jpg)

**osu!lazer version:** 
2020.629.0

**Comment by bdach** [comment]
I think these panels are up for a redesign/update anyway (as per #8435).
