### ISSUE TITLE
Screen stutter on windowed/borderless mode 

### ISSUE THREAD

**Issue by vesterlay** [ppy/osu#9413]
**Describe the bug:** 
When the game is set to windowed or borderless mode, while playing a map there are noticeable screen freezes that last for split second. Changing game to Full screen completely solves the issue. 

GPU: NVIDIA GeForce GTX 970 
Manjaro linux 5.6.16-1-MANJARO 

**osu!lazer version:** 
2020.620.0

**Comment by bdach** [comment]
Please attach the log files as requested in the issue template and also a video of this behaviour if possible, ideally with performance logging enabled (by pressing <kbd>Ctrl</kbd>+<kbd>F2</kbd>).

**Comment by vesterlay** [comment]
@bdach Lags are present even before I started playing the map. 
[runtime.log](https://github.com/ppy/osu/files/4853448/runtime.log)
https://youtu.be/xaTuFnwiSks

**Comment by bdach** [comment]
I'm not sure what stutters are being spoken of here. The video seems perfectly fine, the frame times are stable.

Off the FPS counter I am guessing you're running with the frame limiter off. I'd recommend trying out 2x or 4x limit and seeing how it feels.

**Comment by vesterlay** [comment]
Hmm, after some more testing I found out that rebooting a computer fixed it. Most likely there is a problem with the gnome shell because it turns out this stutter was system wide, but more subtle beside osu and that's why turning on Full Screen fixed it. Sorry for the inconvenience tho.
