### ISSUE TITLE
Initially opening the social browser causes a heavy frame drop

### ISSUE THREAD

**Issue by MrTheMake** [ppy/osu#942]
Video: https://streamable.com/x3b78

Seems to be caused by the displayed avatars. Removing
`Add(displayedAvatar = new AsyncLoadWrapper(new Avatar(user) {...}));`
in UpdateableAvatar::updateAvatar() resolves the frame drop.

**Comment by Kontorted** [comment]
I cant recreate this issue. Any ideas if your specs are causing this?

**Comment by MrTheMake** [comment]
Strangely enough it seems to only occur when starting osu! with visual studio's debugger. I don't know if this is an issue related to osu! or my visual studio 2017. Could anyone check this?

**Comment by Nabile-Rahmani** [comment]
@MrTheMake Debug builds are likely to perform worse than Release ones.

**Comment by MrTheMake** [comment]
Shouldn't be treated as an issue as it is caused by starting with a debugger and doesn't normally occur.
