### ISSUE TITLE
Discrepancy in behaviour with mouse clicks and scrolls between osu.app.zip release vs self-compilation in Mac OS

### ISSUE THREAD

**Issue by cupppu** [ppy/osu#9425]
**Describe the bug:** 
- might be related with #6612 where a framework fix is required
- The OS system setting `Scroll direction` for mouse is set to `natural` which inverts the vertical scrolling direction i.e. scrolling down on the mouse will result in scrolling up in the system and vice versa
- Mac OS catalina 10.15.5

***osu.app release (2020.629.0) behaviour:*** 
- mouse right click on song select does **NOT** work
- `ctrl` + `mouse right click` does **NOT** work
- **mouse scroll up** (with volume, song select etc.) = **scrolling up** (song select, volume **INcrease**)
- volume scrolling increments/decrements at intervals of 5

***Self-compiled lazer build (commit 4bf45ea99abaf079e6023a78442169bab699851c):*** 
- mouse right click on song select brings up context menu 
- `ctrl` + `mouse right click` also does **NOT** work
- **mouse scroll up** (with volume, song select etc.) = **scrolling down** (song select, volume **DEcrease**)
- volume scolling increments/decrements at intervals of 1

---
 
**Logs:**
[database.log](https://github.com/ppy/osu/files/4863927/database.log)
[network.log](https://github.com/ppy/osu/files/4863928/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/4863929/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4863930/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4863931/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/4863932/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4863933/runtime.log)

**Comment by bdach** [comment]
I'm not a Mac user but I am a little confused as to why you would be using the appimage on macOS, as opposed to the `osu.app.zip` package?

The difference might have to do with some middleware interference (xinput or something?)

**Comment by cupppu** [comment]
I mis-wrote, I meant to say the osu.app package

**Comment by peppy** [comment]
What macos version are you running on? Why do your logs say "unix"?

**Comment by peppy** [comment]
I can tell you why the difference exists: it's either sandboxing or the difference between having a proper app bundle versus running dotnet directly.

It's not really within scope to fix this as it's not easily fixable. SDL may help.

**Comment by cupppu** [comment]
It's fine, the only implication is that right clicking doesn't work on the proper app, just thought this might be something you'd like to know

**Comment by peppy** [comment]
It's 99.9% going to be something specific to your system (custom mouse drivers, software).

**Comment by cupppu** [comment]
I messed with this around further, and found out my mouse wheel click (recognised as M2) was able to trigger the right click actions, where the right click button was recognised as M3 and doesn't work.
Though, all the "buggy" behaviours I originally reported have been fixed by the latest release :)
