### ISSUE TITLE
Scrolling can sometimes be triggered through sliders

### ISSUE THREAD

**Issue by stanriders** [ppy/osu#943]
https://www.youtube.com/watch?v=aPgduEZRiBw

I assume there's some kind of fight for mouse focus between sliderbar and whole options overlay. When exactly that happens i could not find out so i hope you will do better job than me.

**Comment by Tom94** [comment]
That happens when you first move your mouse up/down rather then lefft/right. Right now it's based on 1-pixel movement which definitely needs to change to something larger like we do in osu stable.

**Comment by peppy** [comment]
Should definitely be done in a better way.

**Comment by 4rgc** [comment]
So, should the x and y difference value be changed or should the whole way of handling the slider drag be reworked?
Method from Framework.SliderBar is on the picture.
![image](https://user-images.githubusercontent.com/20543337/31587193-dd723bee-b1e5-11e7-87e3-9630f44d3e7b.png)

**Comment by FreezyLemon** [comment]
I've tested this a bit, and as it stands the InputState object does not update, so the method can only access the 1-pixel movement (or rather two absolute positions and the difference between them) which is mentioned/shown above. 
I don't think that will work, so the method should probably be changed in a way that allows it to access more mouse positions/movement.

**Comment by Blaizer** [comment]
This is fixed on the latest release. I believe it was fixed by #1389.

**Comment by Blaizer** [comment]
This is fixed in the latest release. I believe it was fixed by ppy/osu-framework#1389.

**Comment by peppy** [comment]
Closing as resolved by framework fix.
