### ISSUE TITLE
Overlay showing non-existent keytaps in taiko

### ISSUE THREAD

**Issue by Malox10** [ppy/osu#9443]
When playing taiko, pressing some buttons results in the overlay showing 2 buttons being pressed.

**Keys used**: 
S, D, L, Ö (from left to right)

When pressing D overlay showed S and D being pressed at the same time. (as seen in the video)

The bug only happens when pressing the buttons on the "left side"(S, D) and not on the "right side"(L, Ö). This was done on a friends PC and I couldn't reproduce the bug on the same version. Also this bug is exclusive to lazer and does not happen on stable. Restarting didn't fix it. 

**Video of the bug:**
https://youtu.be/yAknWvRRfsA

**Version:**
2020.629.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/4885182/logs.zip)

When searching for "taiko" and "bug" I couldn't find any similiar issues.

**Comment by bdach** [comment]
It's not only the overlay, the left rim on the playfield is also lighting up. Are you sure this wasn't just one key being bound to two actions?

**Comment by Malox10** [comment]
Yes that was the issue! Sorry for the trouble. 

Also from a feature request standpoint: Should this be possible to double bind keys?

**Comment by bdach** [comment]
Looking at stable it does not allow to bind one key to multiple ruleset actions (the other action gets unbound). Unsure whether that's something we want to be bringing back. I imagine having multiple bindings like that could be frowned upon in taiko/mania as it enables cheesing.
