### ISSUE TITLE
Beatmap List Exception If No Beatmaps Are Installed

### ISSUE THREAD

**Issue by Shadowtail117** [ppy/osu#945]
## If you run osu!lazer with no beatmaps (other than the theme song), it displays the theme song as the selected beatmap (with none in the menu) and creates an exception if you try to play it.
This is pretty much a known bug, but it might as well be created into an official issue. For clarification as to what exactly happens, if you attempt to play the beatmap, it launches into the loading screen (shown in the second screenshot) and then reverts back to the beatmap list.
Here's the exception message:
``Could not load this beatmap sucessfully (osu.Game.Rulesets.UI.BeatmapInvalidForRulesetException: Beatmap can't be converted for the current ruleset.
at osu.Game.Rulesets.UI.HitRenderer`1..ctor(WorkingBeatmap beatmap, Boolean isForCurrentRuleset)
at osu.Game.Rulesets.Osu.OsuRuleset.CreateHitRendererWith(WorkingBeatmap beatmap, Boolean isForCurrentRuleset)
at osu.Game.Screens.Play.Player.load(AudioManager audio, BeatmapDatabase beatmaps, OsuConfigManager config, OsuGame osu))!``

Screenshots:
![The theme song beatmap](https://pe8snq.bn1302.livefilestore.com/y4mTA39l4OZ3TLgQXEvQPG9Y5bLM_o5VYrf680CwK8JARsi3i6WYW-etpuuQAp5hr4Ds_Ea3AEAFSzvXCi5bow5q4FtPPQKjTXtjUQHdZM3zQaNjqu7bcC9mNxt2mmlpHeMMYopE6fkx9-doGlyqPxiqE_VU-4VukxHxFqRQQfEW2kjqisUTngzCbKwceoPOTOz8FsFKw62xAkm1xoVjYyfMrPgCdbfTLrLhj3QngbOm5I/2017-06-17%20%285%29.png?psid=1 "The theme song beatmap") 
![Error message](https://po8snq.bn1302.livefilestore.com/y4mfEGbQskLdlyQuRXCgXKbz_W4zBfeRSibFoFMA0Khv9ZiGLh4JEU645QIjywg5FCkDQhLVx4tcHssERYJrgbhAx_aukG9um4L5r2LFq1Nl21DX9AEo5bQjFjpNXywzsRjYxMudQqqcqpxtE94y4wcWPsuS4LwR9YN1YiEV2OFujZA0RV5KIhh_JfP30_vaKffM7iTEAoc_VKQXagLi-hV83qBLKpXed7zXMrGI5Scn-E/2017-06-17%20%286%29.png?psid=1 "Error message")

**Comment by Kontorted** [comment]
Isnt it just reading an osz2?

**Comment by Shadowtail117** [comment]
I haven't delved into the code that much, and I myself am not a professional coder by any means, but I imagine that when it loads the beatmap list an `if` statement can check how many beatmaps there are, and if there is only one (the theme song) then it will return a message to the player, e.g.:
```c#
public void LoadBeatmapList() //Placeholder method for it's actual name in the code
{
   if(beatmapList.length == 1)
    {
      /* This would display something like "You currently have no beatmaps installed. To fix this, you can:
      1. Go to the osu! beatmap listing, download a beatmap file, and either double click on it or drag it into 
      this window,
      2. Download a beatmap via osu!direct, or
      3. Make one yourself using the Editor."

      In addition, the visual on the left that would display the selected beatmap's information would all be 
      blank. */
   }
  //Rest of the code...
}
```

**Comment by Kontorted** [comment]
You're leaving behind a comment by using /*
I understand your motive and your idea is good, however I believe the plan is to show a huge splash text that states you have no beatmaps and sends you to osu.ppy.sh
Either that or it downloads the default pack (Kuba Oms, Rameses B, cYsmix)

**Comment by Shadowtail117** [comment]
Yeah, what I posted was just my idea of how it could check if there are no beatmaps. What it would actually say to the player is moot :P

**Comment by peppy** [comment]
This should be long-resolved.
