### ISSUE TITLE
Skins on osu! lazer MacOS Catalina

### ISSUE THREAD

**Issue by HoodCheese** [ppy/osu#9451]
I was wondering if it is possible to use custom skins on the macOS version of osu lazer because i cant find any skin folder inside of the files. Also i see there is an option at the bottom of the ingame settings that says “import skins from stable” but i dont have stable on my computer, so is there any other way of importing a skin? Thank you

**Comment by peppy** [comment]
Drag skin (.osk) into window.

**Comment by HoodCheese** [comment]
Drag the file where?

**Comment by jai-x** [comment]
Drag the file into the game window.

**Comment by HoodCheese** [comment]
OMG that wass sooo easy haha. Ive been playing with the default skin for months!!!
