### ISSUE TITLE
Spinner ring (and its sprite) spins in the wrong direction

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9455]
**Describe the bug:** As title. The inner ring (and its `*` sprite) spins in the opposite direction (when spinning counterclockwise).

**Screenshots or videos showing encountered issue:**
(I used a random graveyard map with spinners for this gif)
![spinner](https://user-images.githubusercontent.com/43073074/86939210-941a2d80-c141-11ea-852d-18b1c904dfda.gif)

**osu!lazer version:** 2020.707.0, but I tested this on the previous release ([2020.629.0](https://github.com/ppy/osu/releases/tag/2020.629.0)), and everything spins in the **correct** direction.

**Comment by Gabixel** [comment]
Actually, only the inner sprite seems to rotate in the opposite direction (just checked that using the draw visualiser)

**Comment by bdach** [comment]
I 100% regressed this with #9434.
