### ISSUE TITLE
SS Grade glowing effect is not visible at some point in its animation

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9458]
**Describe the bug:** As title. The glowing effect for the SS grade doesn't seem to be visible at some point of its animation. (For S, A, etc., the glowing effect looks normal)

**Screenshots or videos showing encountered issue:** 
(You can see that the effect disappears at some point for a few frames)

Normal Speed |
------------ |
![rank](https://user-images.githubusercontent.com/43073074/86946311-7b624580-c14a-11ea-83f5-90c58dff5d7a.gif) |

Slowed Down |
------------ |
![rank slow](https://user-images.githubusercontent.com/43073074/86946318-7ef5cc80-c14a-11ea-8bb1-5f6b9b00f3c6.gif) |

**osu!lazer version:** 2020.707.0

**Comment by bdach** [comment]
Can reproduce in the test scene. Seems like some sort of one-frame issue (does not respond to clock rate changing) and is not consistent. Looks to correlate with the score ticker completing for some reason...

**Comment by peppy** [comment]
Really annoying one, happens on all platforms at high probability.
