### ISSUE TITLE
Footer in results screen is not visible if UI scale is 0.96x or less

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9460]
**Describe the bug:** If the UI Scale is set to `0.96x` or less, at the end of a play the footer is not visible.

**Screenshots or videos showing encountered issue:** 
![missing footer](https://user-images.githubusercontent.com/43073074/86949458-f299d880-c14e-11ea-9af8-c9bc867c414c.png)

**osu!lazer version:** 2020.707.0

**Comment by bdach** [comment]
This has the same presentation as #9200 (auto-sized cell this time that presents as masked away despite having children of non-zero height):

![2020-07-08-194127_2547x978_scrot](https://user-images.githubusercontent.com/20418176/86952318-17904a80-c153-11ea-9d55-cd8ba6a4b600.png)

In this case `ScreenSpaceDrawQuad` is also affected by floating-point inaccuracies (as the tournament song bar was) and will report coordinates just slightly outside the screen bounds.

**Comment by bdach** [comment]
Confirming that this should be resolved with the linked PR next release.
