### ISSUE TITLE
Gameplay not starting on certain Android devices

### ISSUE THREAD

**Issue by GamerProYT54** [ppy/osu#9462]
**Describe the bug:** 
The rulesets failed to load, and beatmaps would never load, at all.
**Screenshots or videos showing encountered issue:** 
N/A
**osu!lazer version:** 
2020.707.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/4893808/database.log)
[network.log](https://github.com/ppy/osu/files/4893809/network.log)
[performance.log](https://github.com/ppy/osu/files/4893810/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4893811/runtime.log)

**Comment by bdach** [comment]
Ruleset loading exception is not relevant (and custom rulesets are not supported on mobile anyway due to lack of AOT). Regarding the beatmaps not loading, there is not enough information to go on; please provide info which beatmaps fail to load, logs from the device (`Android/Data/sh.ppy.osulazer/logs`) and a video of this if possible.

**Comment by GamerProYT54** [comment]
I will provide the logs, and I am not using custom rulesets

**Comment by GamerProYT54** [comment]
[network.log](https://github.com/ppy/osu/files/4893800/network.log)
[database.log](https://github.com/ppy/osu/files/4893801/database.log)
[performance.log](https://github.com/ppy/osu/files/4893802/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4893803/runtime.log)

**Comment by GamerProYT54** [comment]
If I try to record a video, osu! will crash, and all beatmaps fail to load, regardless of game modes, mods, etc.

**Comment by peppy** [comment]
Where do you have osu! installed?

**Comment by GamerProYT54** [comment]
osu! is installed in /Android/data/sh.ppy.osulazer

**Comment by GamerProYT54** [comment]
Does lag play a role in causing this problem?

**Comment by CakeReport** [comment]
This happen instead, when i tried to record osu!lazer (Android)

https://streamable.com/pirmzt

But when you're not recording, it runs fine

**Comment by bdach** [comment]
Would either of you be able to say which was the last version of the app that worked? I was doing android custom builds fairly recently and everything worked fine, so this seems like it could be device-specific.

**Comment by CakeReport** [comment]
2020.603.0 is the last version that works

**Comment by GamerProYT54** [comment]
This might help:
Device Name = Samsung Galaxy Tab 10.1-inch
Model Number = SM-T550

**Comment by bdach** [comment]
The last working version number given by @CakeReport seems to correlate with an android library version bump for BASS and ffmpeg (ppy/osu-framework#2865).

Could any of you check whether you have video/storyboard disabled, and if yes, does disabling them fix the issue in any capacity? Also listing the version of Android installed on your devices could be helpful.

**Comment by GamerProYT54** [comment]
I have Android 7.1.1 and the rulesets still do not load on 2020.603.0, but it's not very laggy compared to 2020.707.0

**Comment by bdach** [comment]
Ruleset loading error is irrelevant here, as is the performance.

**Comment by GamerProYT54** [comment]
In 2020.707.0 and 2020.603.0, they both run into the same error, `System.ArgumentException: The specified path is not of a legal form (empty).`

**Comment by bdach** [comment]
As I've stated twice at this point, this is error is a red herring and not the cause of the issues.

**Comment by GamerProYT54** [comment]
Disabling Storyboard/Video does not help.

**Comment by bdach** [comment]
Looks like we can safely rule out ffmpeg, then.

The device mentioned by @GamerProYT54 has a Snapdragon 410 SoC, which from my googling would fall under the `arm64-v8a` architecture which we haven't tested ourselves due to not owning 64-bit ARM devices.

@CakeReport Would be interested in your device specs to confirm whether this is an armv8-specific issue.

**Comment by GamerProYT54** [comment]
It seems that disabling the storyboard enables the beatmaps to load

**Comment by bdach** [comment]
so maybe ffmpeg indeed, then? need more info from more people to be sure.

@GamerProYT54 please stop claiming there is an issue with the rulesets. if the default rulesets couldn't be loaded you wouldn't be able to enter gameplay at all.

**Comment by GamerProYT54** [comment]
(I guess) this issue is resolved because I can enter gameplay

**Comment by bdach** [comment]
Is it fully resolved, on the latest version, with storyboard/video both on and off? If the answer in any case is "no", then no, this issue is not resolved.

**Comment by GamerProYT54** [comment]
On latest version (2020.707.0), the beatmaps can load without storyboard. I will need to test if beatmaps can load with storyboard

**Comment by GamerProYT54** [comment]
The beatmaps can load **with** storyboard, I don't know why it didn't work the last time

**Comment by CakeReport** [comment]
@bdach Running an Android 10 with Snapdragon 675 here

**Comment by GamerProYT54** [comment]
@bdach should we continue?
