### ISSUE TITLE
Seek with arrow keys during replay/auto

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#9479]
**Describe the new feature:** It would be nice if you could move in a replay with arrow keys for an amount of time, maybe 3/5 seconds (could be chosen by the user in the settings maybe).

**Proposal designs of the feature:**

**Comment by Gabixel** [comment]
You can already do that, but you have to hover the progress bar with the cursor:
![example](https://user-images.githubusercontent.com/43073074/87037244-368eeb00-c1ec-11ea-8736-80d6c8f2a2e5.gif)
But yeah, maybe this can be changed/modified (like adding a setting where you can choose the amount of time, as he proposed)
