### ISSUE TITLE
Skinning Area

### ISSUE THREAD

**Issue by JackVandenbrink** [ppy/osu#948]
Sorry if this is the wrong place, I read in the readme that if I'd like to contribute I should open an issue.

I'm SweetMate and I just finished a third party skinning program. I'd really love to make this an official feature in osu!Lazer if I could get the chance. 

I believe this will be a very welcome feature to the game as skinning is a huge part of the way users play it.

I have a section of the skinning app on my online portfolio.
http://jackvandenbrink.weebly.com/projects.html

**Comment by peppy** [comment]
We already have a design for a skinning system. If you are interested in helping implement that, we can provide designs which need implementation, but consider that *none* of the skinning framework is currently implemented. There is still a lot of groundwork to be done.

**Comment by JackVandenbrink** [comment]
Ahh I see, I'm still relatively novice with C#, I studied C++ so I'd hate to slow down progression in any way. I don't know of the procedures when working on github apart from commit often and keep files checked out for as little time as possible. If I could get a quick explanation of how things work around here then I'd be more than happy to help implement anything to do with osu!
