### ISSUE TITLE
No menu audio if no beatmaps are available

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#9480]
If the `No, I'd like to start from scratch`-option is selected after entering the beatmap-carousel with no beatmaps but a previous osu! directory, no music will be playing when returning to the main menu. This results in menu items awkwardly bouncing to a nonexistent beat.

For a rhythm game it seems quite weird that there's no fallback audio track for cases like these.

**video:** https://www.youtube.com/watch?v=I1DTCgirJOI
**osu!lazer version:** 2020.707.0

**Comment by Theighlin** [comment]
This also happens when joining a multi room, selecting a beatmap you don't have and then going back to the main menu. I think in this case it should go back to the last played/available beatmap. As for the original post case, maybe it should continue the intro song or choose a random one from triangles, circles and welcome to osu!

I was thrown a little off when i suddenly didn't hear music anymore.

**Comment by enoslayd** [comment]
I think the bouncing might relate to the fact that the osu cookie when hovered will beat to 60 bpm. Happens when paused or no audio playing

**Comment by peppy** [comment]
I agree with this. Right now the query for finding a track to play doesn't include the osu! intro music. The easiest fix is to make these also display in the playlist / music controller (aka. including `Protected` sets in the `GetUsableBeatmapSets` return, explicitly excluding `Protected` in the usages which require it).

I think this makes sense, @smoogipoo thoughts?

**Comment by smoogipoo** [comment]
Sounds like a good direction.

**Comment by peppy** [comment]
Might make more sense to add a new `BeatmapManager` property for this usage, rather than changing all-but-one existing. Not sure.

**Comment by Theighlin** [comment]
Now that i think about it, will osu lazer get released with bundled beatmaps? That would do it, but the multiplayer problem i described above would still need to be addressed.
