### ISSUE TITLE
"Use these mods" option when right-clicking a score

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9481]
**Describe the new feature:** As the title suggests, if someone wants to re-use the mods of a score (made by himself or someone else in any leaderboard) without having to manually select them.

**Proposal designs of the feature:** 
The user will have to right-click in the mods area of a score (or in any position).
I would also suggest renaming "delete" to "delete score" to make it clear what it refers to.

![Use These Mods concept](https://user-images.githubusercontent.com/43073074/87051582-0cdfbf00-c200-11ea-8e3c-1bd7ca8e28a1.png)

And in the mods button of the footer, you can see those mods selected from the score (previously selected mods will be deselected):

![Mods](https://user-images.githubusercontent.com/43073074/87051800-59c39580-c200-11ea-8d7d-fd705e455fac.png)

This feature could may also automatically select the customisations of each mod from the score (but not for now: see #8569)

**Comment by bdach** [comment]
We probably want a decent resolution to #9244 before attempting this as we're very likely to run into that sort of bug again with this.

**Comment by peppy** [comment]
@Gabixel did you already implement this, or just add the placeholder menu item? I think it'd be a pretty cool feature so go ahead if you've already got an implementation.

**Comment by Gabixel** [comment]
I made it with Photoshop (I forgot to say that!), but I managed to make it like a placeholder when right-clicking any of the mods inside the `modsContainer` (and it works in any leaderboard):

![score context menu](https://user-images.githubusercontent.com/43073074/87229693-a2b74d80-c3aa-11ea-8030-6b3876a6ea8c.gif)

Unfortunately, I'm still not very good at coding here :(
Two things are missing (and you can understand that I still need to learn by these):
- I added that in the `MenuItem` already present inside `LeaderboardScore.cs` ([here's the code with the 2 new lines for this](https://gist.github.com/Gabixel/ca2ae8a158f5649142b1a0676b3acb54), I will probably have forgotten some checks too), but it doesn't include the personal best score, and I don't know what's the best way to add a context menu to that:
![personal best](https://user-images.githubusercontent.com/43073074/87225545-2d3d8400-c38e-11ea-8d28-aac522052dcf.gif)

- I don't know how to set the score's mods to the carousel (that's why it's just a placeholder)

So... I think it's better if someone else implements it 😅

**Comment by Joehuu** [comment]
> We probably want a decent resolution to #9244 before attempting this as we're very likely to run into that sort of bug again with this.

Don't think so. For this one, we can first deselect all our current mods and then select the mods from the score.

This was actually easy to implement, but not sure I did it right though: https://github.com/Joehuu/osu/tree/select-mods-from-score

**Comment by peppy** [comment]
I think you can go ahead with PRing that, should be close enough to get it in.
