### ISSUE TITLE
Waveform jumps when zooming in Editor

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#9482]
If the timeline in the editor is zoomed, the waveform that should correspond to the song sometimes moves by a seemingly random amount even though the same timeline tick is selected.

**video:** https://www.youtube.com/watch?v=66tIe2eDxl4
**osu!lazer version:** 2020.707.0

**Comment by peppy** [comment]
I believe this is due to the waveform bucket / smoothing algorithm. Likely requires framework changes.

**Comment by Pentori** [comment]
Experienced similar behaviour

video: https://twitter.com/pentoriosu/status/1314212302929895425
version: 2020.1005.0

**Comment by peppy** [comment]
I no longer believe this is due to the bucket/smoothing algorithm. Looks like it's completely shifting to the wrong place in time.
