### ISSUE TITLE
Scroll containers don't support mouse wheel auto-scroll

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#9483]
Integrated osu! pages can't be scrolled by clicking M3 and moving the mouse. This makes browsing longer pages a chore.

**video:** https://www.youtube.com/watch?v=QCZwIXZ4bBs
**osu!lazer version:** 2020.707.0

**Comment by bdach** [comment]
As far as I know this is a sort-of-obscure feature of the mouse and a windows-ism to boot. From rudimentary googling it seems to be called "auto-scrolling" and is definitely not a universal pattern - on linux it doesn't work in either Firefox or LibreOffice unless explicitly enabled. I recall some devices adding driver-level support for this on windows.

Not sure whether we want to support this, so tagging as "proposal" for now.

**Comment by peppy** [comment]
This won't be implemented. To scroll long areas you can use "fling" scrolling, the scrollbar, or page up / page down / end keys.
