### ISSUE TITLE
osu!lazer crashes on gameplay

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#9496]
**Describe the crash:** Once you try to click a circle during gameplay the game suddenly crashes. osu!lazer crashes both on multiplayer and solo.

**Screenshots or videos showing encountered issue:**  https://youtu.be/4fiduWcYs4w

**osu!lazer version:** 2020.710.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4903334/runtime.log)
[database.log](https://github.com/ppy/osu/files/4903335/database.log)
[network.log](https://github.com/ppy/osu/files/4903336/network.log)
[updater.log](https://github.com/ppy/osu/files/4903337/updater.log)
[performance.log](https://github.com/ppy/osu/files/4903338/performance.log)

**Computer Specifications:** 
![image](https://user-images.githubusercontent.com/19843905/87159959-6f00f880-c2c2-11ea-9b2e-a2ee2b8f84d0.png)

**Comment by cupppu** [comment]
Can repro on mac, "abort() called"

[crash.log](https://github.com/ppy/osu/files/4903391/crash.log)

**Comment by bdach** [comment]
This will be fixed shortly.

**Comment by bdach** [comment]
Should be fixed now; please re-install to resolve.
