### ISSUE TITLE
Osu! Asking to revert to previous version

### ISSUE THREAD

**Issue by plaggeds** [ppy/osu#9498]
**Describe the bug:** 
Osu!Lazer prompts to revert back to 2020.707.0

**Screenshots or videos showing encountered issue:** 
![Screenshot_20200710-214511.jpg](https://user-images.githubusercontent.com/52777118/87161256-d769cd00-c2f6-11ea-8173-952bda0a8209.jpg)
**osu!lazer version:** 
2020.717.0
**Logs:**

**Comment by bdach** [comment]
The latest build has been pulled pending some hotfixes. Please ignore for now.
