### ISSUE TITLE
Glitches when resizing window during gameplay

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#9501]
The application glitches out when resizing the window a few times while playing a map. It starts switching between displays very rapidly, the only way to stop it is through task manager. This also happens when I'm not recording. Might be related to #6273
https://youtu.be/RhehB9G3ikc

version: 2020.707.0
logs: https://www2.zippyshare.com/v/XtWzcZoq/file.html (I'm pretty sure the slow frame times are not related to this bug)
pc: i5-7500, gtx 1060

**Comment by bdach** [comment]
Please try launching lazer with the `--sdl` command line options and seeing if it improves things. If not this might be a Windows issue.

**Comment by Joppe27** [comment]
> 
> 
> Please try launching lazer with the `--sdl` command line option and seeing if it improves things. If not this might be a Windows issue.

This forces osu! in borderless mode? I can't resize the window anymore so I can't test if the bug still happens.

**Comment by Joppe27** [comment]
It seems like the bug doesn't occur on sdl mode for me

**Comment by Joppe27** [comment]
Duplicate of #10342, closing.

**Comment by bdach** [comment]
Does this still happen on the latest release? It shouldn't, as SDL is the default now.

**Comment by Joppe27** [comment]
No, this was indeed fixed by switching to SDL.
