### ISSUE TITLE
Nickname's background colour is not dimmed when overlays are open

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9504]
**Screenshots or videos showing encountered issue:** 
Look on the right side (where the chat is located):

![image](https://user-images.githubusercontent.com/43073074/87170858-3537ee00-c2d2-11ea-8562-ab54f03b3b30.png)

**osu!lazer version:** 2020.710.0

**Comment by peppy** [comment]
This is an issue with how the effect (and global dim) is being applied. Not sure if it can be fixed osu!-side without framework adjustments or re-thinking the dim logic.
