### ISSUE TITLE
Window is not kept fullscreen after switching workspaces in i3wm

### ISSUE THREAD

**Issue by DavidHusicka** [ppy/osu#9505]
**Describe the bug:** 
When switching between workspaces, osu!lazer is not kept in fullscreen and pops into windowed mode telling it's in fullscreen. Correct behaviour should be keeping osu!lazer in fullscreen (same as other games do).

**Screenshots or videos showing encountered issue:** 
https://youtu.be/l9XiqzJIFBU
(the artefacts in video are caused by recording software)

**osu!lazer version:** 
2020.710.0

**Logs:**
Not necessary

**Comment by bdach** [comment]
I did notice this myself running i3 but it's definitely a niche setup so very low priority. Another one for the "osutk issue, fingers crossed for SDL" pile.

For now a reasonable workaround might be to enable cursor confining if on multiple monitors.

**Comment by smoogipoo** [comment]
Please test with the `--sdl` argument.

**Comment by bdach** [comment]
SDL doesn't have full screen yet, so that will have to wait a bit.

**Comment by IsaacElenbaas** [comment]
Not sure if this is WM-specific but I believe it's on focus lost, not anything fancy with how workstations work. On Herbstluftwm I have the same issue when focusing a window on another monitor (or switching workstations).

**Comment by DavidHusicka** [comment]
> Not sure if this is WM-specific but I believe it's on focus lost, not anything fancy with how workstations work. On Herbstluftwm I have the same issue when focusing a window on another monitor (or switching workstations).

I tried it today with dwm so it's not WM-specific.

**Comment by jai-x** [comment]
I suspect this is due to OpenTk/osuTK not adhering to the [EWMH specifications](https://en.wikipedia.org/wiki/Extended_Window_Manager_Hints) which X11 window managers rely upon.

I believe that optional SDL2 window implementation is more compliant in this regard. (I can't find any documentation for this but anecdotally I have found it more compliant from testing with smaller C programs.)

@DavidHusicka As suggested above, I would try running osu!lazer with the `--sdl` command line flag to test this.

**Comment by DavidHusicka** [comment]
> @DavidHusicka As suggested above, I would try running osu!lazer with the `--sdl` command line flag to test this.

SDL doesn't implement fullscreen as I am aware of. It was already mentioned here.

I will try [this](https://dwm.suckless.org/patches/ewmhtags/) dwm patch but I don't have any hopes it will help.

**Comment by bdach** [comment]
Well, SDL itself as a library does, we're just not using that functionality yet in the framework. I probably wouldn't hold my breath when it comes to WM patches, the version of opentk we're using right now has been broken many times over in multiple ways.

**Comment by DavidHusicka** [comment]
Doesn't happen on 2020.1203.0 anymore. Closing this issue.
