### ISSUE TITLE
Animated judgements can start playing from wrong frame

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#9507]
**Describe the bug:** You can see that the accuracy on the HUD drops, but visually, everything looks like it's being hit perfectly.
Important note, not every single judgement went away, in the start of the play there's a couple of 100-s and 50-s, and later during the map they became invisible. Also, it seems that misses are fine throughout the map

Here's the skin: http://bit.ly/35cLsDR

**Screenshots or videos showing encountered issue:** https://youtu.be/n7VSg7Quz5g

**osu!lazer version:** 2020.710.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/4904044/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4904045/runtime.log)
[database.log](https://github.com/ppy/osu/files/4904046/database.log)

**Comment by peppy** [comment]
Could you try with a skin where it is actually visible for clarity? The video is quite pointless as it stands.

**Comment by Sinamer** [comment]
Here's a comparison with osu! classic skin on the same replay: https://youtu.be/8MfdfRMWHTE

**Comment by peppy** [comment]
So can you confirm it's *correct* with the classic skin? If so, please also attach your skin..

**Comment by Sinamer** [comment]
Yes, it is correct on the classic skin. The skin I'm using is attached to the issue

**Comment by Sinamer** [comment]
Sorry for asking, are there any updates on this? Just making sure I'm not missing any details
I've also uploaded the skin to Google Drive in case Mediafire doesn't work
Here's the link: https://drive.google.com/file/d/1EuDjqluc1yb1JMU3nIsY3YloQPLlD0-H/view?usp=sharing

**Comment by peppy** [comment]
no

**Comment by bdach** [comment]
This seems to have regressed with the pooling changes. The skin in question uses animated judgements which fade in and then out over 35 frames; using primitive log statements I have ascertained that some animated judgements can start playing with invalid state (for example, having `CurrentFrameIndex == 34`, which makes them entirely invisible).

I have not properly looked at why this is the case yet, but I'm not sure there is much to investigate there - most likely a way is required to reset the animation of a judgement after it has already played once.
