### ISSUE TITLE
Changing the current track via the music controller in the song selection doesn't apply the preview seek

### ISSUE THREAD

**Issue by MrTheMake** [ppy/osu#951]
Video: https://streamable.com/uouc1

`SongSelect::OnBeatmapChanged(WorkingBeatmap beatmap)` is called right after SongSelect's `Beatmap` is changed. Subsequently, `SongSelect::selectionChanged(BeatmapInfo beatmap)` is called, but as `Beatmap` is already set, it is returned on the first condition.

We *may* want to consider changing `Bindable::ValueChanged(value)` to `Bindable::ValueChanged(oldValue, newValue)`, although this would be a pretty big change.

**Comment by peppy** [comment]
I think this is likely correct behaviour from a user's perspective.
