### ISSUE TITLE
Add filtering by friends to rankings overlay

### ISSUE THREAD

**Issue by MikelJohnson** [ppy/osu#9510]
![image](https://user-images.githubusercontent.com/40336919/87178287-92896a80-c2e5-11ea-8c5f-05fbee05f79d.png)

**Comment by peppy** [comment]
Please avoid contributing such low quality issues. If you are trying to help, provide screenshots, descriptions, etc. explaining what you are looking for in your feature requests rather than empty bodies.

I will close these if you continue.

**Comment by peppy** [comment]
I presume you mean "filtering" not "sorting", correct?

**Comment by MikelJohnson** [comment]
Yeah, sorry didn't mean to be unhelpful

**Comment by MikelJohnson** [comment]
Closed by #9563
