### ISSUE TITLE
Game not working when starting song

### ISSUE THREAD

**Issue by Triglceride** [ppy/osu#9512]
I'm an offline player and i personally like to play on lazer for whatever reason, since this newest update every time i try to play a song the entire game crashes within a few notes. Crashes have always happened but never this consistent

**Comment by peppy** [comment]
You have not provided logs and blatantly ignored the issue template.

Likely solution is to re-run the installer due to a recent emergency update, but please avoid posting to github if you aren't willing to provide minimum details!
