### ISSUE TITLE
big multiplayer rooms don't show all players

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#9516]
**Describe the bug:** The new osu! beatmap spotlight room doesn't show in the list all players participating. 140 joined the room but only about 50 are being displayed (inside the room panel too). Is there some kind of limit? Is this intended as big rooms are unusual?

**Screenshots or videos showing encountered issue:** 
![Screenshot_13](https://user-images.githubusercontent.com/53081750/87187300-3d515700-c2ed-11ea-98da-694013a592f8.png)

**osu!lazer version:** 2020.710.0

**Comment by peppy** [comment]
The display is called "recent" participants for a reason.
