### ISSUE TITLE
Scoring System for mania is too combo heavy compared to stable

### ISSUE THREAD

**Issue by Hydria** [ppy/osu#9518]
Right now on lazer, the mania scoring system closely resembles the standard scoring system, in which each note needs to be hit for the best score. 

Mania has always been a heavily accuracy based system, meaning misses are expected, and so can lead to users seeing scores where a B rank score is beating out someone that is close to 99% accuracy, just because of where they missed, as shown in the screenshot below. (also viewable in the artificial snow map scoreboard for mania spotlights playlist A)

This has left a myriad of people after playing spotlights claiming that the scoring is "broken" at this time and needs to fixed, aiming to be more like scorev2 system that is currently in place on stable.

![image](https://user-images.githubusercontent.com/13346079/87212002-473a8080-c314-11ea-8b6a-661e94b00357.png)

**Comment by peppy** [comment]
This was actually an intentional change to see how things work. From this screenshot it's obvious we need further tweaking.

The weirdest part here may be that having that many more "perfect" judgements doesn't give enough extra accuracy score to make the second user win in such a case.

**Comment by enoslayd** [comment]
I've seen somewhere that having 300 (great) instead of 300s (320, perfect) loses accuracy instead of gaining

**Comment by smoogipoo** [comment]
Resolved by https://github.com/ppy/osu/pull/9578 .

Please try out the next spotlights and open a new issue if you still believe there are problems with the updated portions!
