### ISSUE TITLE
Osu! Lazer for iOS

### ISSUE THREAD

**Issue by brenoaraujo8976** [ppy/osu#9520]
**Describe the new feature:**

they could advance the osu version for iOS, I've been waiting for a while, I would love to play, or if not, provide a new TestFlight link, so we can test the beta.

**Proposal designs of the feature:** 

in fact, I just want to play on my phone since I don’t have a computer, and there’s no way to create an account without a computer, so there’s no way to support the game, to win a beta link, but if you can create an account without the game,  would be nice.

can you send me a new beta link?  I really want to play :(

**Comment by peppy** [comment]
A "new link" will happen at some point in the future, but it not high priority (please understand that by making a "new link" other users already testing the game will no longer be able to test).
