### ISSUE TITLE
Mouse/Cursor doesn't always hide properly when playing a map

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu#9523]
**Describe the bug:** 
Sometimes the mouse/cursor doesn't hide when playing a map. 
I only had this happen to me in osu!catch but I imagine the same thing can happen in taiko and mania, as you also 'leave' your mouse alone, and use your keyboard to play.

It seems like this happens when you move your mouse around a bit while the map is still 'loading' in.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/do43SW5yqfI
Note that it doesn't always happen (as you can see in the video), but if you try it a couple times you should get the same result.
This also works on a couple other maps I tested, so I am assuming it can happen on all maps 

**osu!lazer version:** 
2020.710.0

**Comment by bdach** [comment]
The mouse will be visible outside the bounds of the actual playfield (so in mania/catch on the sides of the 4:3 playfield box, in taiko anywhere above/below the scrolling playfield), and also additionally if you hover over the "Skip" button during the intro; these behaviours are all intended from what I can tell (#7011).

What could be a point of discussion here is whether the cursor should be hidden on the entire screen in all playfields (except for when hovering over UI elements, like the skip button or pause overlay, obviously).

**Comment by peppy** [comment]
Yeah, the bound are specified in the playfield implementations. I think an addition may be to fade out the menu cursor when keyboard input is detected (like many apps / OSes do).

**Comment by Firmatorenio** [comment]
I think the cursor should automatically hide in the keyboard-only modes, even if it's not directly over the playfield - having it just hover around in a random spot of the screen is super distracting when you're tracking fast-moving objects. The option to fade it out when keyboard input is detected is pretty solid (so long as it doesn't affect o!s).

Stable's implementation is fairly decent, though closing chat tabs with a hidden cursor while the map is still loading/leading in can be difficult since it doesn't show up even when you start moving it there.

**Comment by NBBZ** [comment]
sorry if its considered inappropriate to write comments on a stale issue like that, but i was about to make a suggestion just about this, and didnt want to create a duplicate, I am not a developer, but i think adding this feature would be great, i play mania and every time i start a beatmap i have to move my cursor to the middle of the screen so it will be hidden, and its a little annoying to do it every time, esspecialy if I play 4k, where the playfield is smalll so i have to position the cursor exactly in the middle, i think adding an option for the behaviour would be best, but just changing the default behaiviour would work also, as i think not many players would object to the cursor being hidden everywhere during gameplay, and not just on the playfield
