### ISSUE TITLE
Fruits clip into the catcher

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu#9525]
**Describe the bug:** 
Fruits currently clip into the catcher. This doesn't seem as bad with the default skin, but with a custom skin you can clearly see the fruit over the catcher.
In stable it 'disappears' when it lands on the catcher. Gameplay seems really weird due to this difference.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/JYBZ-zW6iv0 
Slowing down the video at any point on which a fruit lands on the catcher will show the issue.

**osu!lazer version:** 
2020.710.0

**Comment by GSculerlor** [comment]
Duplicate of #7938, I guess

**Comment by KevKjef** [comment]
sorry for that, I only searched for clip into/stacking
