### ISSUE TITLE
Users can not see their own beatmap score and leaderboard position within Timeshift Lobbies

### ISSUE THREAD

**Issue by Loctav** [ppy/osu#9527]
Right now, users can not see their own beatmap score while being in the TImeshift Lobby. They would have to return to the singleplayer map wheel to see their best score, but even then it would be impossible to discern which of the scores displayed in the singleplayer map wheel are currently counting in the timeshift lobby they are playing in.

The only way for users to check their own beatmap score in a Timeshift Lobby is to check the beatmap's individual leaderboard. However, once the leaderboard exceeds 50 players, they can not find their score anymore when they aren't in the top 50. 

Same goes for the overall timeshift lobby leaderboard. They can only see their current leaderboard position when they are within the Top 50 of the lobby's leaderboard. Once they are below the top 50, they can not see their current position, their total score, their amount of completed maps and their amount of play attempts.

The web display of a timeshift lobby does not offer this feature either.

**Comment by bdach** [comment]
Temporarily marking as blocked on https://github.com/ppy/osu-web/pull/6564
