### ISSUE TITLE
Add back ability to pause gameplay on middle mouse click

### ISSUE THREAD

**Issue by Dev-Tan** [ppy/osu#9531]
**Describe the new feature:** 
clicking the middle mouse button should instantly pause the current gameplay meaning, the button should react exactly like it did in stable.

**Comment by Game4all** [comment]
Did you meant the M4 Button by "middle mouse button"?. If so, you should already be able to pause gameplay with it. Check that M4 is bound in the key bindings settings.

**Comment by bdach** [comment]
Middle mouse is M3, I'm pretty sure. I did check and it does pause on stable, although I can't see it listed on the keybinding screen there.

We could add middle mouse as a default alternative binding for pause but I don't think it should be bypassing the hold-to-pause mechanics added in lazer.

**Comment by Dev-Tan** [comment]
Yes, i meant M3 (sorry for not clarifying enough)
