### ISSUE TITLE
Intel ICD - Osu! crashed?

### ISSUE THREAD

**Issue by NakigitsuneLO** [ppy/osu#9537]
**Describe the crash: Osu! just can't be opened, instantly appears the window saying that Osu Crashed. I want to know why this happens. :c** 

**Screenshots or videos showing encountered issue: 
![Screenshot_7](https://user-images.githubusercontent.com/68176897/87239419-9f38bc00-c3d4-11ea-8b02-e1351e65e24b.png)
![Screenshot_1](https://user-images.githubusercontent.com/68176897/87239421-a8298d80-c3d4-11ea-8e81-37a3c0d2c56f.png)
![Screenshot_2](https://user-images.githubusercontent.com/68176897/87239422-a9f35100-c3d4-11ea-820e-7c5af38fcd20.png)** 

**osu!lazer version: 1.3.3.8** 

**Logs: There's no files, bc I unistalled Osu and installed again, but I can not open**

**Computer Specifications: Time of this report: 3/26/2020, 14:36:13
             Machine name: DESKTOP-VQCB3VB
               Machine Id: {DDAF60CB-32B5-4865-BC3D-B32EB996DC11}
         Operating System: Windows 10 Home Single Language 64-bit (10.0, Build 18362) (18362.19h1_release.190318-1202)
                 Language: Spanish (Regional Setting: Spanish)
      System Manufacturer: LENOVO
             System Model: F0CM0007LD
                     BIOS: O2NKT14A (type: UEFI)
                Processor: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8092MB RAM
                Page File: 5713MB used, 6983MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Supported
 DirectX Database Version: 1.1.3
           DxDiag Version: 10.00.18362.0387 64bit Unicode**

**Comment by gagahpangeran** [comment]
Isn't this the stable version?

This is common error, you can check this thread for solution https://osu.ppy.sh/community/forums/topics/691164
