### ISSUE TITLE
Offset gets off the longer you play

### ISSUE THREAD

**Issue by Feerum** [ppy/osu#9541]
**Describe the bug:** 
I am not sure if i am the only one with this bug but i already noticed it a while ago. I have tried lazer from time to time and i experienced it every time. I thought maybe it's just me and it get fixed with the next build, but it didn't yet.

My problem is, the offset of the beatmaps gets off the more i play in lazer. I could experience that pretty well during the first spotlight pool. After playing once through the complete pool and then starting over from the first beatmap, the offset is already of by a good amount of 20-30ms

There is a way to solve this, by restarting the game completely. But i don't think that should need to be done.

I also had this problem once in the stable client, but i could solve it by just activating the audio compatibility, which is apparently not an option in osu! lazer? (Maybe because that's on by default? I don't know).

On my side i keep everything always up to date. All drivers, everything. So it most likely shouldn't be an issue with that.

**osu!lazer version:** 
2020.712.0 and earlier

**Comment by bdach** [comment]
30ms is 2 frames at 60fps. I'm not good at the game but I don't think it's something I'd ever consciously notice.

That said even if this is an actual problem then some sort of supporting material for the claim and more detail (i.e. system specs) would be appreciated.

**Comment by Feerum** [comment]
The problem is that it gets more and more. It just don't stay at 30ms, it goes more and more off. Before it got too much i always restarted the client because it gets literally unplayable. So i don't know how far this can go or if the client crashes at some point.

Could try to provide a video too. 

Also sure can give system specs, playing on a laptop:

Lenovo Legion Y520-15IKBN 
Windows 10 Pro 64-Bit
Intel Core i5 7300HQ processor (4 x 2,50 GHz)
GeForce GTX 1050
8 GB DDR4 PC4-19200U (2400 MHz)
Realtek High Definition Audio

Not sure if you need anything more? Just let me know

**Comment by bdach** [comment]
not entirely sure how to even begin investigating this, but as a starting point: does the audio desync from the visuals, or do audio+visuals desync from input? I guess one way to tell if it's the former is to put on autoplay once the delay starts and see whether the auto movements match up with the sound.

also, what setting is the frame limiter on? what framerates are you getting? seems like something that might be potentially relevant.

**Comment by Feerum** [comment]
Some more infos:

I played so far only osu!mania, i am not sure if this also happens in the other game modes.
Additionally i used a custom skin. My skin i also use on stable.

Furthermore i might have notice something. After i played some "normal" osu!mania beatmaps, nothing happened. But as soon as i played osu!mania beatmaps which use a lot of SV changes they offset started to get off. It might be related to this?

However, here are some videos which actually show this pretty well:
**With correct offset**: https://www.youtube.com/watch?v=PU0RRoywx2E

**With offset being off:** https://www.youtube.com/watch?v=T0ADQaRUe-4

>Frame Limiter: I use VSync. Other start to cause lags for me.
>FPS look mostly like this during play (I have that disable normally, just looked it up now): https://i.imgur.com/lTk8Dun.png

As far as i see it's visual and audio are desync. The audio gets later (notes become earlier).

**Comment by bdach** [comment]
would you be able to link some maps that seem to trigger this for you? that way we can check whether this reproduces for us too or if it's somehow specific to your setup.

**Comment by Feerum** [comment]
Sure! I mainly played the osu!mania spotlight maps of this round which are following:
https://osu.ppy.sh/beatmapsets/649306#mania/1589629 
https://osu.ppy.sh/beatmapsets/1026319#mania/2146334 (hard diff)
https://osu.ppy.sh/beatmapsets/508572#mania/1081560 (Trigger Finger diff)
https://osu.ppy.sh/beatmapsets/961321#mania/2012530
https://osu.ppy.sh/beatmapsets/246853#mania/568463

After playing through this pool and then back to the first i noticed that they got off already (sometimes already earlier). The SV map in this one is the 3rd one, Finger VIP (in case it's really because of SV effects)

Otherwise i just played randomly beatmaps. Some with SV effects some without.

**Comment by peppy** [comment]
Please check https://github.com/ppy/osu-stable-issues/issues/306. Your issue may be resolved by a driver update / change.

**Comment by Feerum** [comment]
I guess i can close this now because i managed to solve this problem. Maaaaybe it will be also an solution for other people.

I figured out that osu! as well as osu! lazer automatically used the worse graphic card. It never used the GeForce GTX 1050 i have in my laptop. After trying here and there a bit i now forced osu! and osu! lazer to use the GeForce one.
So on my end it was not an audio card/driver related issue but graphic card related.

This completely solved all issues. Notes do not get late anymore and osu! and osu!lazer run like 200% more smooth. 

So i guess i can close this now
