### ISSUE TITLE
Extend background dim to storyboards and videos

### ISSUE THREAD

**Issue by MasterCritics** [ppy/osu#9550]
As it is, when storyboards/videos play they play at 0% dim, making it hard to see even for people who regularly play with storyboards/videos on. 

Could extend background blur as well, as a test.

**Comment by Joehuu** [comment]
I'm confused, background dim does work with storyboard/video.

As for blur, it is intentional for now because of performance issues.

**Comment by peppy** [comment]
As above, due to performance reasons we cannot support blurring video/storyboards yet.

**Comment by MasterCritics** [comment]
Ah yes, that's my bad. It must've been because blurring gets removed when storyboards/videos play I thought it was what I posted. 

Totally understand the performance issues thing. Once again, apologies.
