### ISSUE TITLE
Macintosh problem with cursors.

### ISSUE THREAD

**Issue by ShiroMeco** [ppy/osu#9552]
**Describe the bug:** 
Problem details: I cannot disable "Confine mouse cursor to window" In my MAC, The cursor moves diferently on my desk and on my osu! window, Unintentionally I've activate this option.
When I am out the osu! window the cursor of osu! works but I cannot click, if I click the cursor of my mac moves to a corner and the osu! cursor don't appear.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2020.712.0

**Logs:**

**Comment by peppy** [comment]
Please run windowed for now, there's a known issue with fullscreen.

If you are running windowed, you likely have mouse software installed causing issues. This may improve when we switch on SDL.
