### ISSUE TITLE
Replays with the relax mod work incorrectly

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9560]
**Describe the bug:** 
If I import a replay with a relax mod and try to scroll forward, the scroll scrolling will not display correctly. After that, there is a chance that the replay will break and stop displaying correctly (I don’t understand the principle).
**Screenshots or videos showing encountered issue:** 
1 video - demonstration of incorrect rewind replay.
https://youtu.be/eyu8a7jhDPs
2 video - demonstration of decline in performance and jerking image. The graph shows that at some points the load grows strongly. The graph turns on at 36 seconds.
https://www.youtube.com/watch?v=krw7G5fHB3k
3 video - broken replay
https://youtu.be/DGCT9UaiZFI
Replays and maps:
[Replays.zip](https://github.com/ppy/osu/files/4918252/Replays.zip)

**Describe the bug #2:** 
An additional problem that is not related to the previous ones. When playing a replay, keystrokes that I made during the game are not ignored. Because of this, the replay shows an incorrect passage. This is clearly seen in 3 videos, where (2:48) the game stopped reading after pressing the button (this is a RELAX mod).
**osu!lazer version:** 
2020. 712.0
**Logs:**
[performance.log](https://github.com/ppy/osu/files/4918162/performance.log)
[performance-update.log](https://github.com/ppy/osu/files/4918149/performance-update.log)
[performance-draw.log](https://github.com/ppy/osu/files/4918157/performance-draw.log)
[runtime.log](https://github.com/ppy/osu/files/4918143/runtime.log)
[network.log](https://github.com/ppy/osu/files/4918158/network.log)
[updater.log](https://github.com/ppy/osu/files/4918159/updater.log)
[database.log](https://github.com/ppy/osu/files/4918160/database.log)

**Comment by gagahpangeran** [comment]
Probably related #9243

**Comment by Moltanicaa** [comment]
No, that’s different. There is an incorrect reaction to pressing and playback in general.

**Comment by aticie** [comment]
@Moltanicaa can you share the replay file?

**Comment by Moltanicaa** [comment]
@aticie please take a closer look, they are already there.
