### ISSUE TITLE
Videos starting at the middle of the beatmap don't load

### ISSUE THREAD

**Issue by reiKishinami1803** [ppy/osu#9561]
Some beatmaps with video that starts at middle part of the beatmap doesn't load at all.

**Comment by enoslayd** [comment]
please attach a video and logs located at %appdata%/osu/logs. also link the affected beatmap

**Comment by bdach** [comment]
Closing for now. Will reopen if any details are provided.

**Comment by reiKishinami1803** [comment]
Here's the link to the beatmap: https://osu.ppy.sh/beatmapsets/364282#osu/799711 



[logs.zip](https://github.com/ppy/osu/files/4923804/logs.zip)

**Comment by reiKishinami1803** [comment]
Here's an in game footage, do note that this is the part where the video should load.
![GIF-200715_161408](https://user-images.githubusercontent.com/44336554/87521120-80794480-c6b6-11ea-93cc-4ecb5a5fdfa4.gif)

**Comment by bdach** [comment]
Can reproduce on my ubuntu setup - the video won't start in normal playback; it can sometimes start in a replay upon seeking past the point it's supposed to start, but then rewinding before it's supposed to start can also make it freeze at the first frame. Definitely lots of improvement to make here.
