### ISSUE TITLE
Legacy osu!mania converts should probably play hitsounds on tail

### ISSUE THREAD

**Issue by peppy** [ppy/osu#9576]
Legacy convert hitobjects generated sounds on their ends in stable, but no longer do here (see #2506). While the new behaviour is correct for osu!mania crafted beatmaps, we probably want to restore previous behaviour for converted beatmaps (up to a certain osu file version?) for parity.

**Comment by enoslayd** [comment]
Wait, converts do have tail hitsounds

**Comment by peppy** [comment]
I may have misunderstood then. Please advise to the remaining issue.

**Comment by enoslayd** [comment]
Add option to have hitsound at the tail (or maybe the body too) of a long note for mania specific maps

**Comment by agausmann** [comment]
More specifically, add an option to _force_ a hitsound at the end of a long note in mania, even where the map doesn't have hitsounds. I liked the audible feedback that was present before #9215  was merged.

**Comment by peppy** [comment]
Against mapper's will? That doesn't sound correct. Next we'll be adding options to force all hitsounds to one sound?

**Comment by agausmann** [comment]
Aren't there a few options already that allow the player to choose preferences "against the mapper's will"?

- Disabling the beatmap skin in favor of the user-selected skin
- Disabling the beatmap hitsounds in favor of the user-selected hitsounds

> force all hitsounds to one sound

This is already possible using custom skins and the options I've listed above. I've played that way myself in the past; though I don't prefer it now, how is that significantly different from custom hitsounds like the [clicky sounds](https://drive.google.com/file/d/1600Kkq-D4t2vnJEPa2oyGJAgKk2MzWp4/view) used by so many players already?

**Comment by peppy** [comment]
Hmm, based on my misunderstanding I'm going to close this issue. We are not add a point where we are adding customisations, especially controversial ones.

**Comment by enoslayd** [comment]
Im actually thinking of having this as an editor option. Beatmaps made on stable will not sound right especially if the slider is used as a closing note that visualizes fade out (like the first mania beatmap)

**Comment by peppy** [comment]
When creating a beatmap you can already choose to place samples on the end of hold notes.

**Comment by enoslayd** [comment]
> Aren't there a few options already that allow the player to choose preferences "against the mapper's will"?
> 
> - Disabling the beatmap skin in favor of the user-selected skin
> - Disabling the beatmap hitsounds in favor of the user-selected hitsounds
> 
> > force all hitsounds to one sound
> 
> This is already possible using custom skins and the options I've listed above. I've played that way myself in the past; though I don't prefer it now, how is that significantly different from custom hitsounds like the [clicky sounds](https://drive.google.com/file/d/1600Kkq-D4t2vnJEPa2oyGJAgKk2MzWp4/view) used by so many players already?

Also, i think we should minimize those "against the mapper" options.
