### ISSUE TITLE
Cursor lags behind when using autopilot + wind up mods

### ISSUE THREAD

**Issue by kindlyfire** [ppy/osu#9582]
**Describe the bug:** Cursor lags behind when using autopilot + wind up mods, making maps unplayable. This is the case on every map I've tested (recording of one below)

**Screenshots or videos showing encountered issue:** https://youtu.be/QtBn3-Gow_Q

**osu!lazer version:** 2020.714.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4931216/database.log)
[network.log](https://github.com/ppy/osu/files/4931217/network.log)
[performance.log](https://github.com/ppy/osu/files/4931218/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4931219/runtime.log)

**Comment by frenzibyte** [comment]
Curious to know if autoplay works at all for you, and whether wind mods are the reason for this lag, can you check for both of that?

**Comment by kindlyfire** [comment]
Autoplay works as expected, with or without wind up.

Autopilot works as expected without wind up. I basically only play with autopilot, but wanted to make a map a little harder, in between normal and DT, so that's how I discovered the issue.
