### ISSUE TITLE
 Section highligh should cover the whole visible range

### ISSUE THREAD

**Issue by Flutterish** [ppy/osu#9594]
**Describe the new feature:** Section highligh should cover the whole visible range

**Proposal designs of the feature:** The top of the highligh should be located at the top of the top-most visible section and the bottom of the highligh should be located at the bottom of the bottom-most visible section. I am unsure how sections are implemented so it might require moving the highligh from individual sections to the section container. Additionaly all visible sections should light up as well.

![osu](https://user-images.githubusercontent.com/40297338/87785671-dc6bd680-c838-11ea-93d8-a30f2400169f.png)

**Comment by recognitionmark** [comment]
wh- what do you mean?

**Comment by Alchyr** [comment]
In the example, the orange highlight on the left showing which section is currently viewed is expanded to cover all currently visible sections, rather than just the "primary" one.

**Comment by peppy** [comment]
Nah, should be the current section. Other sections should be dimmed like stable, though.

**Comment by Flutterish** [comment]
Which section is the current section, though? Given the current solution, ( in the example ) having the second and third last sections be active is not even possible. The active section jumps from last to fourth last when I scroll. ( Possibly related #9196  )

**Comment by peppy** [comment]
Empty space should likely be added to the bottom to make it possible, or the algorithm should be improved to consider display height.l
