### ISSUE TITLE
Add ability to disable older versions from submitting scores

### ISSUE THREAD

**Issue by Hydria** [ppy/osu#9599]
**Describe the bug:** 
User "medium kek" (11625617) has LargeTickHit, LargeTickMiss, SmallTickHit, and SmallTickMiss showing in their score screen in mania spotlight lobby, which then cuts off the rest of the score information. No other user has this on the leaderboards. Confirmed not local issue from other people.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/13346079/87817505-fcaf8b80-c860-11ea-8fbe-99d10bff8d5a.png)

**osu!lazer version:** 
2020.717.0

**Comment by mcendu** [comment]
Is it due to usage of an outdated client?

**Comment by peppy** [comment]
Probably, yes. We will add proper version restrictions in in coming releases.

**Comment by gagahpangeran** [comment]
It seems so. Maybe the old client send those data. But there should be a way to prevent it shows in new client.

**Comment by Game4all** [comment]
Is this still a thing, even after #9709 was merged?

**Comment by bdach** [comment]
Good point, should no longer be. Closing as resolved.
