### ISSUE TITLE
Move beatmaps and configurations to another location

### ISSUE THREAD

**Issue by taroxd** [ppy/osu#960]
I want to ask how to store beatmaps and configurations **not** in %Appdata%. That's because my C Drive is a small SSD, and beatmaps really take up a lot of space.
Also, writing these files to %Appdata% will make osu!lazer not portable. The current stable osu! release is portable so that I can put it in a USB drive.

I do not care about potential privacy or safety problem about these files. Even if I do, I would change ACL by myself.

Currently my workaround is to create a symlink with `mklink`, but I want an official solution to it.
What about checking whether `<installDir/Data>` exists? If it does, launch osu!lazer in portable mode, read and write all the beatmaps and configurations to  `<installDir/Data>` .
Or, what about implementing a command-line switch to specify where these files are, like `--user-data-dir="path/to/user data"` in Google Chrome?

**Comment by smoogipooo** [comment]
This will come when we have the ability to read osu!stable-formatted beatmaps from disk (or import them), and there will be an option to change the song directory.

Assigning as low priority.

**Comment by peppy** [comment]
That's not entirely correct (we will support importing, but there will be no "song" directory).

I agree with checking for a config file in the current working directory and changing storage's `BasePath` as a temporary measure, if you wish to implement this. Otherwise, it will come with the more advanced storage system which we will be migrating to before release.

**Comment by Kontorted** [comment]
I don't believe the program is set to force you to install in a certain directory. Since beatmaps seem to be located in its own root, I would assume it would have portability? Correct me if I am in the wrong!

**Comment by alexpado** [comment]
As a temporary mesure, you can change the `LocateBasePath()` value to `./`.
osu!lazer will store all beatmap etc... in the exe folder, making it runnable from a usb key (yeeeeay)

File to edit : `osu.Framework.Platform.Windows.WindowsStorage.cs:15`

**Comment by alexpado** [comment]
Okay I'm back with some more info.

peppy won't be supporting osu!lazer being "installed" outside the default folder. You should keep you osu!lazer installation in your AppData and just change the `LocateBasePath()` to the desired location (ex: `D:\`. "osu" will be appended by default.).

**Comment by Kazeragi** [comment]
hello, i dont quite understand where i can find the file on disk C:\ to change that configuration

**Comment by Gringo1337** [comment]
sooo, how to change locatoin?

**Comment by insomnyawolf** [comment]
I guess there are a lot of people that could not use lazer without this because they don't have a lot of  free space on their main disk.
Is there any estimated time for that feature to come?

**Comment by peppy** [comment]
no. you can use symlinks in the mean time

**Comment by insomnyawolf** [comment]
I didn't think on this O:
Thanks for the idea

**Comment by insomnyawolf** [comment]
If someone else is interested there's an example
You can run the following command and it ill create a link to a folder in D:\osu!lazer\files

`mklink /J "%AppData%\osu\files" "D:\osu!lazer\files"`

You can change the target folder to anything that you'ld like

**Comment by recapitalverb** [comment]
And for *nix users, it should be `ln -s ~/.local/share/osu /your/custom/path`.

**Comment by Gringo1337** [comment]
> no. you can use symlinks in the mean time

How?

**Comment by bdach** [comment]
@Gringo1337 Please read the two comments preceding yours.

**Comment by Gringo1337** [comment]
> @Gringo1337 Please read the two comments preceding yours.

That's not work

**Comment by insomnyawolf** [comment]
Open a terminal and run it there

**Comment by Gringo1337** [comment]
> # Quick Tutorial
> ## If you are on windows:
> * Win+R => Type "cmd" => hit enter
> * A black popup will appear, there paste `mklink /J "%AppData%\osu\files" "CHANGEME"`
> * Hit enter
> 
> ## If you are on linux
> * open a terminal anywhere
> * Paste there `ln -s ~/.local/share/osu CHANGEME`
> * Hit enter
> 
> Remember to put the path that you want where it says `CHANGEME`

The console writes that it already exists.
How to remove it to create a new and correct one?

**Comment by RatzzFatzz** [comment]
Then the folder "%AppData%\osu\files" exists. 
I'd suggest move all the content from that directory to the one you want to have the maps later. Then delete the files folder and then follow the tutorial again :)

**Comment by insomnyawolf** [comment]
@RatzzFatzz  Thanks for your explanation about this, i forgot to mention it

**Comment by peppy** [comment]
This has since been resolved; you can now choose your game data directory.

**Comment by epro124** [comment]
How can i see the beatmaps folder on osu! (Lazer)?

**Comment by peppy** [comment]
"Open osu! folder" in settings.
