### ISSUE TITLE
Users can currently submit spotlight scores from both 2020.714.0 and 2020.717.0 under two different scoring systems

### ISSUE THREAD

**Issue by Hydria** [ppy/osu#9600]
Don't know if you have any version control setup, more of an informative post.

**Describe the bug:** 
With the new score changes to taiko and mania, users can submit scores from both the old combo based scoring system and the new acc based scoring system, which leads to the following scenarios:

1. Users getting lower score from playing on older build and being confused, with the leaderboards looking incorrect, as shown here (medium kek and bok_choi being on 714):
![image](https://user-images.githubusercontent.com/13346079/87827238-65533400-c872-11ea-87a6-d72eec3e8110.png)

2. Abuse from players that can combo but not acc getting really high scores from downgrading to 714 and just FCing. Shown below is the difference between NEW and OLD scoring systems (in that order):
![image](https://user-images.githubusercontent.com/13346079/87827321-992e5980-c872-11ea-807d-ff38bfa572f8.png)
![image](https://user-images.githubusercontent.com/13346079/87827332-9e8ba400-c872-11ea-86ca-fb174f51900b.png)

**Comment by Joehuu** [comment]
Same issue as https://github.com/ppy/osu/issues/9599
