### ISSUE TITLE
Disable of hit circle fading animation

### ISSUE THREAD

**Issue by Vickywar09** [ppy/osu#9601]
An option to disable hit circle fading animation would be a great improvement in gameplay and a great addition.

**Comment by peppy** [comment]
In my eyes this kind of option is blasphemy and makes the game look like something I would quit developing. But one could argue that the customisation should be there for users that want to make their game look shit and I should turn a blind eye.

Will likely be possible via skinning, but will never be exposed as an option. It should not be accessible or easy to do.

**Comment by Vickywar09** [comment]
Ohh ok now I get your point of view, I respect it.
Recent updates are very nice thank you for that.
And have fun developing.
