### ISSUE TITLE
Storyboarded maps with lots of animations degrade in performance over time

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu#9605]
**Describe the bug:** 

Playing any version of [this beatmapset](https://osu.ppy.sh/beatmapsets/1130581#osu/2361608) with the storyboard enabled causes a cumulative loss of update FPS that continues until the map is quit, at which point it recovers completely.

**Screenshots or videos showing encountered issue:** 

[Video included.](https://puu.sh/G8mp2/4672467fa9.mp4)

**osu!lazer version:** 2020.717.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/4941408/performance.log)

[runtime.log](https://github.com/ppy/osu/files/4941407/runtime.log)

**Comment by bdach** [comment]
Storyboards in general need a lot of perf work still in lazer. This particular beatmap heavily uses animations, to the point of which some of the sprites have ~20k transforms queued over the duration of the whole map.

I guess we have #3756 as an issue already but seeing that this is more specific than just "storyboards are slow" I think it's better to leave this open.

**Comment by peppy** [comment]
The reason this particular storyboard stands out is that it uses the same sprite instances throughout the beatmap with very long chains of transforms. This is something we don't seem to have optimised for currently.
