### ISSUE TITLE
Scroll by right dragging is missing in song select

### ISSUE THREAD

**Issue by jeiea** [ppy/osu#9607]
In osu stable we can scroll top to bottom of a song list at once by right-click dragging vertically in the center of the screen. But it seems this feature is missing in the osulazer. I'm curious whether this is intentional.

Tablet users may use two finger touch to do the same things. And missing of this feature is personally dissatisfactory to me.

**Comment by mouzedrift** [comment]
There is a setting in the options for this (it's disabled by default).
![osu!_s0nnm0yOKr](https://user-images.githubusercontent.com/43358824/87853920-5a4de180-c90e-11ea-9664-c766d8adcdf3.png)

**Comment by peppy** [comment]
There's an option to turn this on.
