### ISSUE TITLE
Missing a hold note release causes random misses in inverse maps

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#9608]
When missing a hold note release, specifically on inverse maps or maps with a lot of LNs, there will be random misses throughout the rest of the map. I think it misses every perfect release in the specific column you missed on before, until you get a great, good, etc. (not a perfect/marvelous) on a release in that same column. 
It's hard to explain, please watch this video where I intentionally miss the first LN if it isn't clear: https://youtu.be/he3tHxYS7eU

map: https://osu.ppy.sh/beatmapsets/502203#mania/1111137
version: 2020.717.0
no logs

**Comment by bdach** [comment]
The hypothesis given above seems incorrect (as in I cannot reproduce anything like getting misses on one column after missing a release). I also am not sure what I'm looking at in the video.

I don't think we can do any investigation this until a replay is provided (which there is no convenient way to access right now). Or someone who can play mania good enough to be able to play the attached map looks into it. I'm certainly not that sort of person.

**Comment by Joppe27** [comment]
> 
> 
> The hypothesis given above seems incorrect (as in I cannot reproduce anything like getting misses on one column after missing a release). I also am not sure what I'm looking at in the video.
> 
> I don't think we can do any investigation into this until a replay is provided (which there is no convenient way to access right now). Or someone who can play mania good enough to be able to play the attached map looks into it. I'm certainly not that sort of person.

This bug only occurs on pretty dense LN maps like the one I attached, not on every mania map. You can see osu! displaying misses in the video while I'm not missing (i only missed the very first hold note). Let me know if you need any other info/video

**Comment by bdach** [comment]
I suppose if you provided your `client.db` file we should be able to fish out the replay from the depths of the `files` folder. (Or if we add the functionality to export replays, I guess - that's actually something that might be useful going forward...)

**Comment by Joppe27** [comment]
Should I include my files folder too? This is client.db: https://www1.zippyshare.com/v/KbDoRxup/file.html

**Comment by bdach** [comment]
You can just include `files/3/35/3571c14bdefbf8e278049542568e587056db7bc5ac10fc1305766cbc470cd757`. It should be the `.osr` for the play on the video if I'm not mistaken.

**Comment by Joppe27** [comment]
https://www95.zippyshare.com/v/6Pw1gtkM/file.html I get a no replay data message for this one, is that normal?

**Comment by bdach** [comment]
Thanks, can reproduce. Haven't looked into it in detail (will require a proper slowdown) but definitely something seems to be afoot. While it's not exactly the play captured on the video, some weird misses on the first column from the left are visible about ~45 secs in.

**Comment by Joppe27** [comment]
This bug has returned in the newest version 2020.820.0, can this issue be reopened or do I create a new one?

**Comment by bdach** [comment]
The fix applied previously is unlikely to have regressed as it's covered with automated tests. However as noted in the PR description this can still occur due to note lock which will be addressed separately.
