### ISSUE TITLE
osu!lazer doesn

### ISSUE THREAD

**Issue by oshawott9044** [ppy/osu#9609]
**Describe the bug:** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:**

**Comment by Joehuu** [comment]
Closing until the template is filled and title is complete.

**Comment by oshawott9044** [comment]
> Closing until the template is filled and title is complete.

My bad, something wen't wrong on my end and I submitted the issue to early

**Comment by bdach** [comment]
Do you use a custom beatmap folder?

**Comment by oshawott9044** [comment]
> Do you use a custom beatmap folder?

Yes I do, is that the issue?

**Comment by bdach** [comment]
Yes. See #3763.
