### ISSUE TITLE
Make Sudden Death mod immediately restart game like Perfect mod

### ISSUE THREAD

**Issue by ryancsh** [ppy/osu#9615]
If i miss a note with Sudden Death on, i can't do anything except wait the 2 seconds or so for the menu to appear before i can do anything. In fact, it's faster for me to not use Sudden Death at all and just ESC manually, which defeats the purpose of the mod.

I believe it would be better if Sudden Death simply restarted immediately on a missed note, no questions asked, just like Perfect mod does.

**Comment by recognitionmark** [comment]
Yeah, about that, why not press tilde (~) when you fail? It will restart, after all.

**Comment by gagahpangeran** [comment]
This can be a toggle option for those two mods.

**Comment by ryancsh** [comment]
> 
> 
> Yeah, about that, why not press tilde (~) when you fail? It will restart, after all.

Well, that's true, but Perfect immediately restarting and Sudden Death not doing the same makes the game feel inconsistent.

**Comment by Joehuu** [comment]
Right now lazer does implement both SD and PF by restarting immediately.

I think your intention was to change stable's behavior, which you can make an issue in https://github.com/ppy/osu-stable-issues, but I doubt it'll change there.

Closing as this is lazer.
