### ISSUE TITLE
Separate options for Video and Storyboard

### ISSUE THREAD

**Issue by ryancsh** [ppy/osu#9617]
**_Separate options for Video and Storyboard_**

The short term reason is so that players can avoid the massive fps drops from 400+ to 60.

The longer term reason is somebody might just not like storyboards.
Some storyboards have a lot of flashing, which can be a potential health concern for somebody prone to seizures whereas videos don't tend to have a lot of flashing from what I can tell.

**Comment by peppy** [comment]
Storyboards will be optimised to the point there is no frame drop.

I'm not sure "flashing" is a concern. There nothing saying a video won't have flashing.

**Comment by bdach** [comment]
Also see #3114 for the flashing part.

**Comment by ryancsh** [comment]
> 
> I'm not sure "flashing" is a concern. There nothing saying a video won't have flashing.

There is no guarantee obviously, but I find leaving video enabled doesn't distract from the gameplay while giving me something to watch when I'm waiting for breaks in the middle of a map to end.

Storyboards on the other hand tend to actually distract from the game itself. And some people go way overboard with the effects. 

My perspective is like so: Having separate options for them doesn't hurt but can potentially help. Assuming the effort to make it happen isn't too much, why not?

**Comment by peppy** [comment]
Simplification; unification of experience; mapper intent.
