### ISSUE TITLE
Solo results screen doesn't show user covers on panels but timeshift does

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#9618]
**Screenshots or videos showing encountered issue:** 
Solo:
![osu_2020-07-19_10-35-15](https://user-images.githubusercontent.com/35318437/87881099-ea8e3400-c9ab-11ea-950d-17fdc3412461.jpg)

Timeshift:
![osu_2020-07-19_10-35-31](https://user-images.githubusercontent.com/35318437/87881103-efeb7e80-c9ab-11ea-8bf5-45116c8c5fcc.jpg)

**osu!lazer version:** 2020.717.0

**Comment by Game4all** [comment]
Looks like the aggregated `User` objects returned by `GetScoreRequests` don't have their `Cover` property populated whereas the one returned by `GetRoomPlaylistScoresRequest` do. This may require a osu-web fix.

**Comment by Joehuu** [comment]
Closing as resolved, just need a osu-web update now.
