### ISSUE TITLE
Spinners adding health

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#9625]
**Describe the new feature:** i know the spinner bonus is not implemented yet, but can you at least make spinners add health (or temporarily pausing the drain) while spinning instead of health constantly draining with spinners. I searched open issues about spinners but nothing about health so i opened this issue.

**Comment by smoogipoo** [comment]
Not easy to do. Requires bonus points to be implemented https://github.com/ppy/osu/pull/5782

**Comment by enoslayd** [comment]
Just want to ask, what happened to the pr?

**Comment by smoogipoo** [comment]
It had issues and hasn't been updated yet.
