### ISSUE TITLE
Pressing escape with mod selection window open when beatmap search field is populated cancels the search before closing mod selection window

### ISSUE THREAD

**Issue by cupppu** [ppy/osu#9630]
**Describe the bug:** 
With the mod selection window open and the search field populated, escape will first cancel the search before closing the mod selection window, which is different to how this is handled with other windows e.g. settings or toolbar menu

**Screenshots or videos showing encountered issue:** 
https://streamable.com/bmixmw

**osu!lazer version:** 2020.717.0 

**Logs:**
[database.log](https://github.com/ppy/osu/files/4949415/database.log)
[performance-audio.log](https://github.com/ppy/osu/files/4949421/performance-audio.log)
[performance.log](https://github.com/ppy/osu/files/4949422/performance.log)
[performance-update.log](https://github.com/ppy/osu/files/4949423/performance-update.log)
[performance-draw.log](https://github.com/ppy/osu/files/4949424/performance-draw.log)
[runtime.log](https://github.com/ppy/osu/files/4949425/runtime.log)

**Comment by Joehuu** [comment]
Oops, I regressed this with https://github.com/ppy/osu/pull/9564. The `TextBox`'s platform action now goes first then `BackButton`'s global action.

Not sure how to fix if we still want the glow visual.

**Comment by Joehuu** [comment]
Actually its `FocusedTextBox` overriding the framework's and using it's own global action.

https://github.com/ppy/osu/blob/89d04f797f94838aac18e2c571fcd3c6bfbd24e5/osu.Game/Graphics/UserInterface/FocusedTextBox.cs#L58-L80
