### ISSUE TITLE
Fullscreen issues when running under wayland

### ISSUE THREAD

**Issue by Hexality** [ppy/osu#9634]
[**Describe] the bug:** 
Game gets extremely laggy when trying to run it on wayland (and it gets even worse when trying to put it into fullscreen). It also happened the fullscreen window turn into a 800x640 borderless window.

**Screenshots or videos showing encountered issue:** 
![osu_2020-07-21_00-36-09](https://user-images.githubusercontent.com/17398632/88009975-334c0700-caea-11ea-9d6b-5121ac2a4754.jpg)
![Screenshot from 2020-07-21 00-38-27](https://user-images.githubusercontent.com/17398632/88010108-86be5500-caea-11ea-9dc7-0a8bc38c1ebf.png)

**osu!lazer version:** 
2020.717.0

**Logs:**
[database.log](https://hastebin.com/raw/olohiwewiw)
[performance.log](https://hastebin.com/raw/xoyuranehi)
[runtime.log](https://hastebin.com/raw/emevayevog)
[network.log](https://hastebin.com/raw/nuxajisopa)

**Comment by gagahpangeran** [comment]
Maybe related #5198

**Comment by smoogipoo** [comment]
Please try running with the `--sdl` argument, and perhaps even `SDL_VIDEODRIVER=wayland`

**Comment by Alexmitter** [comment]
@smoogipoo running the appimage with --sdl results in an error:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at osu.Framework.Platform.Sdl.Sdl2WindowBackend..ctor()
   at osu.Framework.Platform.DesktopWindow..ctor()
   at osu.Framework.Platform.Linux.LinuxGameHost.CreateWindow()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Desktop/Program.cs:line 55
```
Running it with SDL_VIDEODRIVER=wayland only works, it is in wayland mode but with the known issues.

**Comment by Hexality** [comment]
@smoogipoo It got a better better, but the performance still gets too degraded.

**Comment by bdach** [comment]
More details would be good to have (system specs, maybe a video of the behaviour).

I noticed that the log lists nouveau instead of the proprietary drivers which could have an impact, but the fps counter seems fine. In general if the update/draw fps looks ok but the actual window doesn't then this will be some sort of wayland crosstalk I imagine.

**Comment by Hexality** [comment]
lists noveau but the driver installed is nvidia

**Comment by Hexality** [comment]
![Screenshot from 2020-07-21 18-39-54](https://user-images.githubusercontent.com/17398632/88109853-99d03400-cb81-11ea-9dc9-259d37cfa7b0.png)

**Comment by Hexality** [comment]
![image](https://user-images.githubusercontent.com/17398632/88110044-e582dd80-cb81-11ea-883a-65538e762715.png)

**Comment by 2str8** [comment]
everything seems fine with performance for me, but there is still bug with low color palette, switching from multi thread to single thread freezes game (backwards too), and unable to enter fullscreen mode with `--sdl` argument (even if in game settings i chose fullscreen mode). With only `SDL_VIDEODRIVER=wayland` fullscreen works.
![Screenshot_20200722_130912](https://user-images.githubusercontent.com/38224978/88145701-a9508b00-cc1c-11ea-9f87-5876985facfd.png)

![Screenshot_20200722_130950](https://user-images.githubusercontent.com/38224978/88145744-b8373d80-cc1c-11ea-818a-f626a757e7f8.png)

**Comment by bdach** [comment]
Going to close this for now - we'll track all wayland-specific breakage at #5198.
