### ISSUE TITLE
Song Length Missing in Solo Play Mode

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu#9644]
**Describe the bug:** 
When in song selection for solo play the song length is 0:00 for all songs.  This appears to be the case for every single song/every single mode.  The other stats appear to be fine.  The only way to see length is to open the details overlay that pulls up the map on the website. Note this doesn't fix the value in client, it is just a workaround.

Even weirder is it looks like 3 of the maps I downloaded 1.5 weeks ago for Spotlights do have a length value (see second screenshot).  Not sure if I already had the other 2 maps or not.  If I did then perhaps this issue is solved for any new downloads.

**Screenshots or videos showing encountered issue:** 
![0 length](http://s.owo.lt/F3iaUTdS)
![spotlights maps](http://s.owo.lt/KgLN8ZVt)

**osu!lazer version:** 
2020.717.0  however this has been an issue since at least 2020.710.0 or before

**Logs:**
Logs, memory dumps, etc from #9521 should apply here since this issue did exist during that time too, I just didn't get around to opening this issue until now.  I can re-upload/re-email dumps if needed.

**Comment by peppy** [comment]
Please re-import your maps.
