### ISSUE TITLE
Performance degradation when opening the notification panel

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9653]
**Describe the bug:** 
1. If the map (https://assets.ppy.sh/contests/101/category-101-entries.zip - 02i3 - Ring) contains aspire elements, the lazer always gives an error on them.
2. Together with the error, for some reason the FPS drops to 15.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/Cgyd5iFoJCo
**osu!lazer version:** 
2020.717.0

**Comment by peppy** [comment]
This is due to the notifications showing an error message with no truncation. It should be truncated.
