### ISSUE TITLE
Influence of AR on the appearance of a spinner

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9654]
**Describe the bug:** 
This is not really a bug, but rather a slight omission. A low AR makes the spinner appear earlier, and it does not become active immediately - it just appears. I'm not entirely sure if this should be so. It appears behind the current elements and can be a little confusing. In the stable, he always appears at the same time. I don’t think this requires an immediate decision.
**Screenshots or videos showing encountered issue:** 
The screenshot shows that it has already appeared, but the sliders have not passed yet.
![osu_2020-07-23_20-21-37](https://user-images.githubusercontent.com/59089206/88276656-c7081800-cd22-11ea-99e2-30ae5c231514.png)
**osu!lazer version:** 
2020.717.0

**Comment by smoogipoo** [comment]
I've noticed this too, definitely something that should be considered/fixed.

**Comment by peppy** [comment]
While on the topic, I should also mention that the SPM display appears too early currently (on mouse movement, even when you can't yet spin).

**Comment by Moltanicaa** [comment]
Problem solved
![osu_2021-05-01_11-44-05](https://user-images.githubusercontent.com/59089206/116776692-9784f980-aa72-11eb-9e37-23005a59b4ba.png)
![osu_2021-05-01_11-44-06](https://user-images.githubusercontent.com/59089206/116776693-98b62680-aa72-11eb-8a59-0f6dbcdabe57.png)
