### ISSUE TITLE
Add 2FA to osu!

### ISSUE THREAD

**Issue by C0NS03L** [ppy/osu#9655]
**Describe the new feature:**add 2FA to osu! to improve account security

**Proposal designs of the feature:** add options for users to enable 2fa by authenticator or via email. The 2FA code will be asked every time you log in or add the option to remember the computer.

**Comment by smoogipoo** [comment]
I think we do eventually plan to have an in-app authenticator, but that'll happen post-release if anything.

**Comment by peppy** [comment]
This is *relative* low priority as lazer does not have write access to a user account (outside of chat / timeshift).

**Comment by peppy** [comment]
Tracking via #20590
