### ISSUE TITLE
Slider sliding sample doesn't stop when gameplay is paused

### ISSUE THREAD

**Issue by Azureharp** [ppy/osu#9657]
**Describe the bug:** 
When paused mid slider the slider slide sample will continue to play until the cursor to resume gameplay is clicked. 
A hold-to-confirm activation time of 0ms makes doing this far easier.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/nz5jel

**osu!lazer version:** 
2020.723.0

**Logs:**
Unsure if this a bug where you'd want or need logs, but here's the runtime log anyway.
[runtime.log](https://github.com/ppy/osu/files/4967391/runtime.log)

**Comment by InfinityGhost** [comment]
This extends even past pausing, it can occur mid-play and loop until you exit the score screen.

**Comment by peppy** [comment]
@InfinityGhost please provide a sample of this happening, in a separate issue since it's likely a completely different cause.

**Comment by InfinityGhost** [comment]
> @InfinityGhost please provide a sample of this happening, in a separate issue since it's likely a completely different cause.

Do you need a clip of where it starts until the score screen, or just at the score screen?

**Comment by peppy** [comment]
A whole play would be good.

**Comment by InfinityGhost** [comment]
@peppy Posted my issue with video to #9698
