### ISSUE TITLE
 long freezes at the start of spinners in catch

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#9659]
**Describe the bug:** 

I saw manny comments regarding this problem in the spotlights rooms, before you start a spinner freezes for about 2 seconds, 
after freezing ends, performance while spinner lasts is very low.

**Screenshots or videos showing encountered issue:** 

https://drive.google.com/file/d/1NuY64atUPQYGzws8ZaRRSvZEvHvgjKmI/view?usp=sharing

**osu!lazer version:** 

2020.723.0

**Logs:**

[performance-update.log](https://github.com/ppy/osu/files/4968050/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/4968051/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4968052/updater.log)
[database.log](https://github.com/ppy/osu/files/4968053/database.log)
[network.log](https://github.com/ppy/osu/files/4968054/network.log)
[performance.log](https://github.com/ppy/osu/files/4968055/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/4968056/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4968057/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/4968058/performance-input.log)

**Comment by peppy** [comment]
Which beatmap do you see this on?

**Comment by Joehuu** [comment]
In the video, it's https://osu.ppy.sh/beatmapsets/679738#osu/1437412.

**Comment by Gonzalo-Bruna** [comment]
> Which beatmap do you see this on?

I didn't really tested this too much mainly because i am not catch player, just saw some comments in the catch spotlights room, i tried by my self with the only map i knew that had a spinner, and it happened.
 but because of the comments, i think it also happens with any other beatmap.

here's the conversation i saw, and i realized no one noticed, or at least there was not any github issue regarding this problem.

![osu_2020-07-23_21-52-12](https://user-images.githubusercontent.com/41755816/88354461-f6bd1d00-cd2e-11ea-85ab-49c8dd8f891e.jpg)
