### ISSUE TITLE
Can not change the osu folder in osu!lazer

### ISSUE THREAD

**Issue by yobrevelc** [ppy/osu#9660]
First I have to complain about the annoying intallation which don't give me any choice to decide the install folder and just install in my disk C.This is very UNACCEPATBLE to a player since osu could be a huge software with thousands of maps.
    For this reason, I tried to move osu!lazer into disk D and then I realized there is another folder seems like the main folder which named "osu" in AppData/Roaming. I moved it to the disk D. When I use the ingame options to reset the folder location, it failed and told me the folder in AppData/Roaming was being used by some program so the action was failed. Obviously, osu!lazer is using the folder and as a result the folder can't be change in anyway. Then I found that there was a new osu folder in AppData/Roaming.
    I don't know why the best rhythm game in the world can't set the installation position.Or, at least we should successfully change the osu folder. Hope this bugs could be solved.

p.s:Importing all the stable map is too slow, could options add a button to import assigned map?

**Comment by peppy** [comment]
Check options
