### ISSUE TITLE
Reduce spinner bonus weighting in osu! ruleset

### ISSUE THREAD

**Issue by Kingling664** [ppy/osu#9667]
Describe the bug: Not sure if this is a bug or not, but I really hope this isn't intentional. On lazer it is now possible to get more than 1 million points due to spinner bonuses. This causes a whole array of issues with the spotlights, meaning it is now substantially easier to get 1million point scores causing all previous weeks to be redundant.

Screenshots or videos showing encountered issue: https://imgur.com/gallery/Iv7zMYH - 19x 100 score over an SS

osu!lazer version: 2020.725.0

**Comment by bdach** [comment]
Pretty sure the "being able to score over 1M points" part is not a bug. Bonus points (which correspond to any judgement that does not affect combo, which bonus spins don't) don't factor into the 1M point cap in any game mode. Also pretty sure [the maximum number of bonus spins is already capped](https://github.com/frenzibyte/osu/blob/a6a7961af9c2788202055efff6a9e42cfd3a7344/osu.Game.Rulesets.Osu/Objects/Spinner.cs#L49).

What *could* be the problem here, perhaps, is the number of points awarded for spins *itself*. I'd see this as more of a balancing issue to get that correct rather than start factoring spinners into the 1M cap.

**Comment by KinglingOS** [comment]
I think it would be much better for the spinner bonus to have some sort of a cap, rather than how it is right now. So then the scores can be normalised back down to 1million.

**Comment by peppy** [comment]
As already mentioned, the spinner score *is "capped"*, and was chosen based on near-matching stable. If you find it is not matching stable please provide example beatmaps and we will assess whether a change is required.

**Comment by KinglingOS** [comment]
Since the effect of 100s is different between lazer and stable, I believe the effect of spinners on the overall score is much more drastic. As shown in the screenshot, the 19x 100 score is above an SS score, which would never happen on stable.

**Comment by peppy** [comment]
Yes, lazer uses different scoring.

**Comment by KinglingOS** [comment]
I think its worth mentioning that if you plan to do this, **please** do not implement it before the end of the spotlight season because it would result in scores set during this week to be unbeatable.

**Comment by peppy** [comment]
We are aware of awareness.

**Comment by reflexit** [comment]
Based on my observation, in stable, spinner bonus only matters if the accuracies of two scores are identical or very close. A 1x100 score can be possibly higher than an SS score, but only if the player puts considerable effort in spinners. It is rare, for example, to see a 3x100 score higher than an SS score.

If lazer is designed to near-match stable in spinners, then the spinner bonus might need to be reduced. Current implementation gives me the feeling that spinner bonus is made to allow players to "make up" lost accuracy scores with relative ease.

**Comment by Mic238** [comment]
It's ridiculous to keep the v1 spinning score, as a prefect score of v1 could be multi millions on an average map and gets to 100m+ for harder and longer maps, thats less than 0.1% for 10 extra spins for 11k. The weight of the spin is substantial with a 1 millions cap, saying 11k that 1.1%. The leaderboard can become a spinning competition easily over accuracy.

At the moment, please axe the spinning score to 0.03x-0.1x of v1 (3-10 points per spin and 33-110 per extra), as a temporary solution at least, before the final score is set. This is effectively scaling back a map with prefect score of 10-30m in v1 to the current 1m cap, should cover some average length and difficulty maps.

**Comment by bdach** [comment]
@Mic238 please see linked PR, which is already set to introduce spinner scoring changes within the range you suggested.
