### ISSUE TITLE
Performance leak after last update.

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9668]
**Describe the bug:** 
The speed of the application in the main menu dropped several times (about 3-4). It gets worse after each return to the lazer after closing.
**Screenshots or videos showing encountered issue:** 
Normal condition:
![osu_2020-07-25_11-59-40](https://user-images.githubusercontent.com/59089206/88446674-54f11980-ce6f-11ea-87ae-bbd61d6cef5a.png)
After the first attempt to use the search:
![osu_2020-07-25_11-57-46](https://user-images.githubusercontent.com/59089206/88446671-50c4fc00-ce6f-11ea-874e-fdb511cecfb8.png)
Further attempts to return to the laser:
![osu_2020-07-25_12-04-20](https://user-images.githubusercontent.com/59089206/88446675-591d3700-ce6f-11ea-8f3c-784c482b74bd.png)
![osu_2020-07-25_12-05-43](https://user-images.githubusercontent.com/59089206/88446679-5cb0be00-ce6f-11ea-9625-b1e8efa124ee.png)
**osu!lazer version:** 
2020.725.0
**Logs:**
[performance.log](https://github.com/ppy/osu/files/4974765/performance.log)
[updater.log](https://github.com/ppy/osu/files/4974766/updater.log)
[runtime.log](https://github.com/ppy/osu/files/4974767/runtime.log)
[network.log](https://github.com/ppy/osu/files/4974768/network.log)

**Comment by Moltanicaa** [comment]
Logs of attempts to use search. Maybe it will help.
[performance.log](https://github.com/ppy/osu/files/4974772/performance.log)
[updater.log](https://github.com/ppy/osu/files/4974773/updater.log)
[network.log](https://github.com/ppy/osu/files/4974774/network.log)
[runtime.log](https://github.com/ppy/osu/files/4974775/runtime.log)

**Comment by peppy** [comment]
Please try restarting your PC and updating drivers. "leaking" between application runs sounds like a system level issue, not osu!.

**Comment by Moltanicaa** [comment]
Really looks like something from the side of my system. Rebooting helped, I hope this problem will not occur again.
