### ISSUE TITLE
taiko mascot skin animation first frame doesn't show if not suffixed with frame index

### ISSUE THREAD

**Issue by Tellilum** [ppy/osu#9671]
**Describe the bug:** 
Already tested this with a known good skin. It seems that certain skins don't show pippidon-miss images. I noticed it with Cinnamon Special (https://mega.nz/file/L9oRVBIQ#YPR_nXA9rQI_w3o_fChTFQruzMpnyjkwBtWV3bs1jbs)
**Screenshots or videos showing encountered issue:** 
![osu_2020-07-25_04-03-09](https://user-images.githubusercontent.com/59491721/88452497-35390180-ce2d-11ea-9d97-218a8d8e138a.jpg)

**osu!lazer version:** 
2020.07.25
**Logs:**

[performance.log](https://github.com/ppy/osu/files/4975070/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4975071/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4975072/updater.log)
[database.log](https://github.com/ppy/osu/files/4975073/database.log)
[network.log](https://github.com/ppy/osu/files/4975074/network.log)

**Comment by bdach** [comment]
This particular skin is using `pippidonfail.png` as its sole animation frame for the "fail" mascot animation state, while lazer currently expects `pippidonfail0.png`. I suppose a simple fallback to an indexless filename for the 0th frame is the correct fix for this.
