### ISSUE TITLE
Add an unranked mod that removes unhitable HitObjects

### ISSUE THREAD

**Issue by Flutterish** [ppy/osu#9674]
**Describe the new feature:** Some maps contain overlapping hitobjects. Add an unranked mod that removes them.

**Proposal designs of the feature:** 
```cs
List<HitObject> valid = new List<HitObject>();
double lastEndTime = -10000;

foreach ( var i in Beatmap.HitObjects /* ordered by StartTime */ ) {
    if ( i.StartTime < lastEndTime ) {
        continue;
    }

    valid.Add( i );
    lastEndTime = i.GetEndTime();
}

Beatmap.HitObjects = valid;
```
This mod should not be ranked as these maps already have a leaderboard and it removes difficulty. The category should be conversion.

**Comment by bdach** [comment]
Not sure whether there is demand for this. It doesn't seem terribly useful to me.

**Comment by peppy** [comment]
I'd just not play said beatmaps.
