### ISSUE TITLE
The play ranking is based on the combo and not the grade.

### ISSUE THREAD

**Issue by s1rcheese** [ppy/osu#9677]
**Describe the bug:
After playing a beatmap, Osu! gives you a ranking on a play but the ranking is based on the combo and not the grade.** 

**osu!lazer version: 2020.725.0** 
![osu](https://user-images.githubusercontent.com/36133547/88467775-9d203400-ce8f-11ea-9e46-4e5783001624.PNG)
![osuWithNormalSkin](https://user-images.githubusercontent.com/36133547/88467776-9e516100-ce8f-11ea-9f3e-7dcd09d78df1.PNG)

**Comment by genericthing** [comment]
this doesn't look like osu!lazer

**Comment by gagahpangeran** [comment]
Yeah, this is osu stable.

The rank is based on score exactly (not combo). The grade is based on your accuracy.

You can learn about scoring system here https://osu.ppy.sh/help/wiki/Score

**Comment by s1rcheese** [comment]
I'm honestly stupid
