### ISSUE TITLE
Combo is still too heavily biased & 320s (Perfects) should reward more accuracy score

### ISSUE THREAD

**Issue by KcHecKa** [ppy/osu#9683]
![image](https://user-images.githubusercontent.com/12588776/88488294-3ca9f900-cf5a-11ea-84a3-c23aed074ee4.png)

The Accuracy/Combo split should be like 95%:5%
 
If lazer scoring counts pefects towards accuracy, then I feel like higher accuracy scores should always be higher, regardless of combo. Perfects could hold more weight of your score.

Combo could effect scoring but only when two plays have around the same accuracy (and the person with the higher combo would get the bonus)

**Current**
Cryolien
`(800000 * .9632) + (200000 * (3394/4181)) = 932,913`
Gonzaalooo
`(800000 * .9659) + (200000 * (2378/4181)) = 886,472`
KcHecKa
`(800000 * .9695) + (200000 * (1950/4181)) = 868,879`

**95:5 Split**
Cryolien
`(950000 * .9632) + (050000 * (3394/4181)) = 955,628`
Gonzaalooo
`(950000 * .9659) + (050000 * (2378/4181)) = 946,043`
KcHecKa
`(950000 * .9695) + (050000 * (1950/4181)) = 944,344`

I don't want to make it seem like I'm nitpicking because I'm unhappy with my scores, but in my opinion, combo should have little to no effect on score at all. It's so arbitrary on where you miss and the accuracy of the score entirely is a better indicator on your 'consistency.' Each note could simply have their own weight, depending on your judgments, and 320s/perfects could give a bit more weight than 300s/greats. Combo could be the deciding factor between similar accuracy scores; or a minuscule 1-2% combo weight of the total score.

**Comment by Gonzalo-Bruna** [comment]
I am one of those players in the screenshot (Gonzaalooo) and i pretty much agree with these changes, mainly because we are used to stable scoring system, where combo doesn't really affect score, and i think for a gamemode like mania it should be this way, or at least, combo should not affect as much as 20% of your total score.

**Comment by peppy** [comment]
Moving to milestone because I think we can action on this early (adopting 95:5 or something thereabouts) to get user feedback.
