### ISSUE TITLE
Way to disable hit circle expand/fade out after clicking

### ISSUE THREAD

**Issue by shrublet** [ppy/osu#9685]
**Describe the new feature:** 
With the default lazer skin, the hit circle expand becomes very distracting with the default triangle animation vs. a skin with no animation. Reducing the fade out time for the animation after hitting a circle or decreasing the amount it expands or an option to disable the expand/gradual fade out would all remedy how distracting it is. Another option is to have it act more like a stable skin and just briefly expand the static parts and not have the triangle animation stick on screen (or have whether the animation displays after clicking a circle as a toggleable option).

**Proposal designs of the feature:** 
If the ability to disable the expand/fade out is implemented, a toggleable option in the settings like hit lighting is all there would need to be or an option in the skin.ini folder to dictate how it acts.

**Comment by peppy** [comment]
I think you mean this? https://github.com/ppy/osu/pull/6345

**Comment by shrublet** [comment]
I'm not quite sure that's the same thing- from what I understand that issue has to do with the way numbers expand in relation to hit burst and legacy consistency. I was trying to ask for an allowance to disable hit burst and/or disable specifically the triangle animation of hit circles after a circle is clicked (they stay on screen much longer than a typical hitburst with a static skin). Apologies if I'm misunderstanding.

**Comment by peppy** [comment]
The triangle animation is part of the default skin. I'd suggest using a legacy skin for the time being if it bothers you. We do have plans to expand on the skinning system to allow more specific customisations but this is still a bit further away.
