### ISSUE TITLE
OAuth authentication failed with Bad Request

### ISSUE THREAD

**Issue by MatteoJoliveau** [ppy/osu#9694]
Hi!
Whenever I try to login to my account via Osu!Lazer, it immediately fails without any error message. The password field simply gets emptied. I can log into the website without any problem.

By looking at the log files, it seems that the OAuth resource owner password flow is failing. The error message is unfortunately very generic.

```
Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: BadRequest.
Response was: {"error":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
```

Here are all the log files available.

[database.log](https://github.com/ppy/osu/files/4983520/database.log)
[network.log](https://github.com/ppy/osu/files/4983521/network.log)
[performance.log](https://github.com/ppy/osu/files/4983522/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4983523/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4983524/updater.log)

**Comment by MatteoJoliveau** [comment]
Also I should point out, this is a fresh installation of 2020.725.0 downloaded a few minutes ago from GitHub

**Comment by jai-x** [comment]
I am able to reproduce this locally when I attempt to use my email to login rather than username.

Please note that osu!lazer only supports logging in by using your osu! username in the username field and **not your email**.

**Comment by MatteoJoliveau** [comment]
@frenzibyte I use a password manager, and the same password is accepted on the website. So I'm 99.9999% sure this is not a credentials issue

**Comment by MatteoJoliveau** [comment]
@jai-x ah, I'm actually trying with the email. Let met try with the username

**Comment by MatteoJoliveau** [comment]
That was it. It worked by using the username as the principal. Thank you @jai-x!

Maybe the error could be presented to the user in a clearer way. Having the form simply reset itself is not the friendliest approach. 

Thank you both btw!

**Comment by Joehuu** [comment]
Yeah, that is being tracked in https://github.com/ppy/osu/issues/4086. Closing as resolved.

**Comment by MatteoJoliveau** [comment]
Woah I missed it, sorry @Joehuu 

Guess I should have search for more keywords than just "oauth" 👍
