### ISSUE TITLE
Slider samples randomly continually loop

### ISSUE THREAD

**Issue by InfinityGhost** [ppy/osu#9698]
**Describe the bug:** 
While playing a map, sometimes a slider sample will continually loop past where they should end, and even into the score screen. It stops looping once the score screen exits or when retrying.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/v98ue6

**osu!lazer version:** 
debug build at e0df75d73594852e95ca5d54a2f84766f283fe39

**Logs:**

[database.log](https://github.com/ppy/osu/files/4985737/database.log)
[performance.log](https://github.com/ppy/osu/files/4985739/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4985740/runtime.log)
[network.log](https://github.com/ppy/osu/files/4985741/network.log)

**Comment by peppy** [comment]
After initial investigation, the only way I can see this happening is if `IsTracking` also remains in a `true` state.

**Comment by InfinityGhost** [comment]
This still seems to be occuring at 91ce06aaa70c8d38cfa7effb36e7716db866d579

**Comment by bdach** [comment]
That would be because the framework bump to 2020.729.0 hasn't happened yet. You can wait for that to be merged or try doing a framework checkout yourself to see if it is resolved (I assume you're building from source if you're referring to commit hashes).

**Comment by InfinityGhost** [comment]
> That would be because the framework bump to 2020.729.0 hasn't happened yet. You can wait for that to be merged or try doing [a framework checkout](https://github.com/ppy/osu-framework/wiki/Testing-local-framework-checkout-with-other-projects) yourself to see if it is resolved (I assume you're building from source if you're referring to commit hashes).

Oh I've gotcha, forgot that it was using a NuGet package instead of a direct project reference. Will test latest framework soon.
