### ISSUE TITLE
Multiplayer room should display grouped diff icon instead of single diff icon

### ISSUE THREAD

**Issue by GSculerlor** [ppy/osu#9703]
**Describe the new feature:** Since timeshift now support playlist, I think it's make sense to display grouped difficulty icon instead of first item difficulty on playlist.

**Proposal designs of the feature:** I've tried to implement this on my fork, but created this issue to make sure it's right direction and probably need more design thinking.

![osu_2020-07-28_16-29-33](https://user-images.githubusercontent.com/6506864/88647630-64cb6080-d0f0-11ea-8cd9-d3f42b2a1a4f.jpg)

**Comment by smoogipoo** [comment]
I think that might get crowded once there's too many icons (one for each mode + each difficulty?). It's definitely something we'll want but may be a little too early.

Fwiw, flyte has already redesigned these panels:
![image](https://user-images.githubusercontent.com/1329837/88648543-0b6c2d00-d102-11ea-9416-82bbc94a3cbd.png)

but they don't have mode markers.

**Comment by bdach** [comment]
I'd argue that the difficulty spread of the playlist is more important to be able to see at first glance, rather than count alone.

Not sure what the single icons on the screenshot are supposed to mean - is it the lowest diff, or just the first on the playlist?

**Comment by peppy** [comment]
The colours on the bar represent difficulty.

**Comment by bdach** [comment]
Yep, I got ninja'd when I was replying to this. Was referring to the screenshot in the opening post.

**Comment by Joehuu** [comment]
Resolved in redesign.

<img width="236" alt="Screen Shot 2021-08-27 at 10 48 55 PM" src="https://user-images.githubusercontent.com/35318437/131207817-91052f12-1b8a-42f9-96bc-afaa42d26f7f.png">
