### ISSUE TITLE
Keep the screen on while in the game (Android)

### ISSUE THREAD

**Issue by MeguMario** [ppy/osu#9705]
**Describe the new feature:** 
The screen will be kept on while in the game, this will benefit from watching replay or auto, or even listening to music, with the current state of the game, avoid crashing when screen lock on android 

**Proposal designs of the feature:** 
If possible, a switch to turn off this feature (except gameplay, replay which will always on). Default is on

**Comment by peppy** [comment]
The current behaviour is already exactly as you want it. The screen will only be kept on during gameplay. Are you suggesting this isn't working?

**Comment by MeguMario** [comment]
> The current behaviour is already exactly as you want it. The screen will only be kept on during gameplay. Are you suggesting this isn't working?

Yes, it is still turn off during gameplay and replay for me

**Comment by peppy** [comment]
Please include your device specs (hardware, OS, etc.) so we can look into it.

**Comment by MeguMario** [comment]
> Please include your device specs (hardware, OS, etc.) so we can look into it.

It's a Pixel 2 running on Android 11 (Beta 1.5),

The display setting to show that the game still respect the screen timeout setting
![Screenshot_20200728-193101](https://user-images.githubusercontent.com/44724359/88665703-3dcd5880-d109-11ea-948c-a8917461f2b1.png)

And here is the clip, notice that after 30s after the last interaction with the screen, the screen turn off automatically
https://streamable.com/egh3rl

**Comment by bdach** [comment]
This should be fixed next release after merge of ppy/osu-framework#3767. If it still isn't, please let us know and we'll reopen.
