### ISSUE TITLE
osu!lazer closed when switching to other app (Android)

### ISSUE THREAD

**Issue by CakeReport** [ppy/osu#9707]
**Describe the crash:** When you go back to home screen/switched to other apllication, osu!lazer will be closed/crashed

**Screenshots or videos showing encountered issue:** https://streamable.com/dm0tid

**osu!lazer version:** 2020.725.0

**Comment by Game4all** [comment]
This isn't a crash per se but rather a current limitation of the framework on android devices, having to do with the graphics context loss on switching apps IIRC.
