### ISSUE TITLE
Different number of combos in maps

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9715]
**Describe the bug:** 
Does the app calculate the number of combos in some other way? Why do I have 46 fewer combos than the stable?
**Screenshots or videos showing encountered issue:** 
![osu_2020-07-29_23-57-20](https://user-images.githubusercontent.com/59089206/88811161-95e38800-d1f9-11ea-8e27-fecc499e580a.png)
![screenshot091](https://user-images.githubusercontent.com/59089206/88811256-adbb0c00-d1f9-11ea-96d8-6cca25c1b5ef.jpg)
Map - https://osu.ppy.sh/beatmapsets/3959#osu/22993
**osu!lazer version:** 
2020.725.0

**Comment by peppy** [comment]
There are many scoring differences, yes.
