### ISSUE TITLE
Adjusting a mod's settings while in a playlist affects all songs in the playlist

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu#9727]
**Describe the bug:** 
If you have multiple beatmaps in a playlist with the same customizable mod (Nightcore, Double Time, Wind Up, etc.) changing the setting in the "customize" panel changes it for all other beatmaps.

Ex. If you have three beatmaps in the playlist with Nightcore, and you then set Nightcore to 1.7x speed, all other beatmaps with Nightcore now have 1.7x speed as well. Or at least, they appear to.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/36qtjj

**osu!lazer version:** 
commit https://github.com/ppy/osu/commit/e60c085bf2e6889bcc51ca6b47b3a50e460a5b8c

**Logs:**
[database.log](https://github.com/ppy/osu/files/5002449/database.log)
[network.log](https://github.com/ppy/osu/files/5002450/network.log)
[performance.log](https://github.com/ppy/osu/files/5002451/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5002452/runtime.log)

**Comment by Gabixel** [comment]
[I can still reproduce something similar](https://drive.google.com/file/d/1UAZbBb-LBp49UNr40_dCnx4ppdRgBAVd/view?usp=sharing) but in a different way:

you can do this by changing the mod settings after "refreshing" the selected mods (like when adding or removing one of them). In my example, the first item in the playlist had `Deflate (Starting Size 8.5)`, and at the end of the video it became `Deflate (Starting Size 20.6)`.

**Comment by Gabixel** [comment]
also, you can notice that "refreshing" the mods changed that setting to its previous value (from 5 to 8.5)
