### ISSUE TITLE
Rankings country selector implementation

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#9728]
So the question is: should we make a request to get all the available countries or make it locally? (Which is possible, but required to remove extra countries which are not displayed in the web-side)
Local implementation:
![Аннотация 2020-07-30 215515](https://user-images.githubusercontent.com/22874522/88962732-80309a00-d2af-11ea-9859-4cb4f75132b6.png)
![Screenshot_1](https://user-images.githubusercontent.com/22874522/88962737-8292f400-d2af-11ea-8b41-9bbd00c5fd8c.png)

**Comment by bdach** [comment]
I believe countries are added and removed as the player pool changes (countries with not enough players on them do not have rankings). So no, I'd say they need to be explicitly fetched from a web endpoint.

**Comment by EVAST9919** [comment]
Closing as resolved ([issue to track](https://github.com/ppy/osu-web/issues/6395))
