### ISSUE TITLE
Incorrect operation of the "view profile" button in multi.

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9730]
**Describe the bug:** 
An empty profile is displayed instead of a mapper profile if you click on a nickname. Not a big mistake, really.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/59089206/89001724-5c686500-d33e-11ea-8555-1032ac45df66.png)
![osu_2020-07-31_14-57-11](https://user-images.githubusercontent.com/59089206/89001729-60948280-d33e-11ea-81a5-58919f61810e.png)
**osu!lazer version:** 
2020.725.0

**Comment by gagahpangeran** [comment]
I can reproduce it.

- Create new room
- Edit playlist
- Select map
- Click the mapper's name in playlist card

**Comment by bdach** [comment]
Related to #5966 / https://github.com/ppy/osu/issues/7518#issuecomment-574084821. Unsure whether worth keeping open as those already cover the fail case of not having online IDs of some user references stored in local database.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/12805 but requires a reimport.
