### ISSUE TITLE
Selecting an item out of sight in the map editor for taiko.

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9732]
**Describe the bug:** 
Small problem, but I don't think it should work that way.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/59089206/89031726-68701900-d376-11ea-8bf0-52530fb3d2fd.png)

**Comment by peppy** [comment]
I'm just going to close this for now. I think it's fine to have hits select in that location because they are still on the playfield. In a similar way to osu! hitcircles being selectable even after the hittable radius.
