### ISSUE TITLE
SpinnerFrequencyModulate skin setting is not implemented

### ISSUE THREAD

**Issue by yansaan** [ppy/osu#9738]
**Describe the new feature:** 
Implement the SpinnerFrequencyModulate skin setting

**Proposal designs of the feature:** 
Turn off SpinnerFrequencyModulate in the skin for the spinner sound to not pitch up.

**osu!lazer version:** 
2020.801.0
**Logs:**
[performance.log](https://github.com/ppy/osu/files/5008454/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5008455/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5008456/updater.log)
[database.log](https://github.com/ppy/osu/files/5008457/database.log)
[network.txt](https://github.com/ppy/osu/files/5008471/network.txt)

**Comment by frenzibyte** [comment]
1. `SpinnerFrequencyModulater` is not yet implemented. 
2. osu!lazer now has a setting to always play combo break on first time, you can disable that if you don't want it to.

This issue can be renamed to track implementing `SpinnerFrequencyModulater`.

**Comment by Joehuu** [comment]
The setting seems to be removed from the ui in [`956980e` (#8802)](https://github.com/ppy/osu/pull/8802/commits/956980ee9055738a73dd9791ca52ff1a3de2ab18), and can only change it in `game.ini`.

**Comment by yansaan** [comment]
Btw, when combobreak setings added?

**Comment by smoogipoo** [comment]
We have intentionally made the first combo break play a sound, as it is the most-common use case. Probably not going to change for now unless a large sample of users who can make a strong argument against it.

I'm re-purposing this issue to cover the `SpinnerFrequencyModulate` issue.
