### ISSUE TITLE
"Disable Windows key during gameplay" not working with osuTK

### ISSUE THREAD

**Issue by PoIoMarco** [ppy/osu#9741]
On stable when I accidentally click my windows key, nothing happens. My game doesn't pause or anything. I can just keep on playing. 

On Lazer it doesn't work at all. It tabs out of the game and pauses my game

**Comment by Joehuu** [comment]
Seems be an oversight that devs didn't inform users in the changelog that it only works when you append the `--sdl` flag.

Closing as already implemented, just waiting for SDL to be fulfilled.

**Comment by peppy** [comment]
wait really? that doesn't sound right...

**Comment by Joehuu** [comment]
In https://github.com/ppy/osu/pull/9439:
> Opening this for potential review, as this is months away from getting merged as it only works with the SDL backend (Windows Keyboard hooks don't play nicely with osuTK GameWindow).

**Comment by smoogipoo** [comment]
Going to re-open this as we still don't know how far away SDL is, and this is probably something that should happen sooner if possible.

**Comment by peppy** [comment]
Took a quick look into this:

- The code matches stable and is not erroring
- The hook is working when the window isn't active (disabling the `Enable` function makes the window key no longer work when osu! isn't focused)

This suggests that something else is hooking and blocking the window message propagation, but I can't see anything like that happening on a quick check.

Not a resolution, but may help towards a future fix.

**Comment by peppy** [comment]
Have confirmed to be working under SDL. Given the above, I don't think it's worth looking into this as a priority.

**Comment by Joehuu** [comment]
Fixed in SDL as of now.
