### ISSUE TITLE
The display of spinners is not entirely correct

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9742]
**Describe the bug:** 
The spinner-meter and spinner-background files do not overlap each other exactly. The spinner-meter is higher than the spinner-background. It is found on many skins, but here you can see most of all (the background is made in the form of soft lighting around the edges of the girl). The spinner itself is located just above the middle of the screen, which is why it almost goes to the upper border. Maybe lower it a little lower?
**Screenshots or videos showing encountered issue:** 
![screenshot093](https://user-images.githubusercontent.com/59089206/89088348-1c0af480-d3db-11ea-9588-49db8cd5526a.jpg)
![osu_2020-08-01_09-26-31](https://user-images.githubusercontent.com/59089206/89088365-33e27880-d3db-11ea-8586-fc276d01ac87.png)
**osu!lazer version:** 
2020.801.0

**Comment by bdach** [comment]
Please attach/link the skin shown on the screenshots here.

**Comment by Moltanicaa** [comment]
https://drive.google.com/file/d/1LEepGaC3597qQ1iovSFVtUL79pe2G-ps/view?usp=drivesdk

**Comment by gagahpangeran** [comment]
The `spinner-approachcircle` also doesn't show.

![screenshot010](https://user-images.githubusercontent.com/4964985/89097949-b2f0a480-d40d-11ea-8e2d-957d38f266eb.jpg)

![osu_2020-08-01_15-40-53](https://user-images.githubusercontent.com/4964985/89097903-6dcc7280-d40d-11ea-8746-0884468a33de.jpg)

[skin.zip](https://github.com/ppy/osu/files/5010025/skin.zip)

**Comment by enoslayd** [comment]
I think the default spinner also doesnt have approach circle
