### ISSUE TITLE
Add an option to disable "ctr + key actions" in game 

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#9743]
**Describe the new feature:** 

As a mania player, I use s-d-f-space-j-k-l for playing, and on many occasions, I have pressed without intention the ctrl key with my left hand while playing, opening direct overlay, (ctr + d) and that has led me to lose several times.
I would like to have an option in the menu to disable ctr + key actions (just as the windows key) to disable these actions in gameplay.

**Proposal designs of the feature:** 

As an option in the main menu where you can choose to disable these actions if they bother you as it does for me.

**Comment by peppy** [comment]
Can you confirm you still want these keys to be on ctrl-<key> when not in gameplay? because a possible solution is to just bind them to something else, if not.

**Comment by vntxx** [comment]
It may be easier to add an option that disables hotkeys that interrupt gameplay (like calling certain overlays) while playing. This would allow to not just intercept ctrl based hotkeys but other types as well (if rebound for example).

**Comment by Gonzalo-Bruna** [comment]
> Can you confirm you still want these keys to be on ctrl- when not in gameplay? because a possible solution is to just bind them to something else, if not.

It is a solution but I am used to the ctr + key bindings tbh, I like the solution given above rather than changing key bindings, since for sure it will happen to someone else in the future
