### ISSUE TITLE
Settings -> Audio -> Devices scrollable list doesnt work

### ISSUE THREAD

**Issue by kkartaltepe** [ppy/osu#9744]
**Describe the bug:** 
When you have more than 18 devices in the list it goes off screen, you can scroll and see the devices past the bottom but they snap back below the screen. Similar to what happens if you try to scroll past the bottom of a list.

**Screenshots or videos showing encountered issue:** 
![typical_suffering_linux_user](https://user-images.githubusercontent.com/526419/89093399-e7f9ea00-d36e-11ea-98ed-183f2357b9e5.png)

In total I guess osu! is finding 20 or so devices but I can only see the devices past PulseAudio briefly while scrolling and cannot select them without using keyboard controls. Though it's hard to say where the thing you want to select is since the list still doesnt scroll even when using keyboard controls.

**osu!lazer version:** 
2020.725.0 Linux appimage

**Logs:**

**Comment by frenzibyte** [comment]
There seem to be no constraints to the height of the settings dropdown, they should probably follow the skin dropdown's max height: `200`.
