### ISSUE TITLE
Timing distribution graph appears to place all misses at the same point.

### ISSUE THREAD

**Issue by VisMajorSpeedruns** [ppy/osu#9748]
**Describe the bug:** All misses are placed on the same point of the timing distribution graph, creating an unnatural / inaccurate spike at the edge of the accuracy window. Increasing or decreasing the accuracy window with the difficulty adjust mod moves the millisecond mark of the spike.

**Screenshots or videos showing encountered issue:** 
![osu_2020-07-31_23-37-30](https://user-images.githubusercontent.com/35517046/89096538-323d9400-d38c-11ea-9ec3-2874a1388148.jpg)

**osu!lazer version:** 2020.801.0

**Comment by bdach** [comment]
Don't think misses should show up on the timing distribution graph at all myself, really. Makes sense that they would be concentrated in one spot given that they are assigned the offset at the end of the hit window.

**Comment by cupppu** [comment]
This doesn't seem to be the case all the time
https://cdn.discordapp.com/attachments/515489895783858177/739115335692845056/unknown.png

**Comment by VisMajorSpeedruns** [comment]
I think it's still there (tiny bump over the 0 in +30) but since you're much better than I am the relative size of it is very small. I had 13 misses and 333 hits distributed... all over the place, where you have 15 misses and 1954 hits with most of them exactly on time.
