### ISSUE TITLE
Map import from multiplayer silently fails if checksum doesn't match

### ISSUE THREAD

**Issue by AuracleTech** [ppy/osu#9753]
Map downloaded but impossible to start.

Video of encountered issue https://clips.twitch.tv/FurtiveSnappyMarrowCmonBruh

Osu!lazer version 2020.801.0

[network.log](https://github.com/ppy/osu/files/5011741/network.log)
[performance.log](https://github.com/ppy/osu/files/5011742/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5011743/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5011744/updater.log)
[database.log](https://github.com/ppy/osu/files/5011745/database.log)

**Comment by frenzibyte** [comment]
There seem to be checksum mismatches web-side, which leads to osu!lazer thinking the beatmap you're having is a modified version and thus doesn't let you start playing.

I've opened an issue there https://github.com/ppy/osu-web/issues/6407.

**Comment by bdach** [comment]
Going off the above what lazer does is *correct*, but could probably do with better UX/indication as to what went wrong.

**Comment by AuracleTech** [comment]
https://github.com/ppy/osu-web/issues/6407
Ephemeralis confirmed this issue is now fixed.
