### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by richp2k** [ppy/osu#9754]
I tried installing the latest version of lazer and it came up with an error.
![error](https://user-images.githubusercontent.com/66353518/89119496-e6b6e300-d47c-11ea-8e41-06babfbdb773.png)
log:
[SquirrelSetup.log](https://github.com/ppy/osu/files/5011880/SquirrelSetup.log)

**Comment by bdach** [comment]
The log does not contain any entries from today. Did you change its contents in any way?

**Comment by richp2k** [comment]
I didn't this is what it gives me when I click open setup log.

**Comment by richp2k** [comment]
Just tried clicking it again and it gave more in the log: 
[SquirrelSetup.log](https://github.com/ppy/osu/files/5011889/SquirrelSetup.log)

**Comment by bdach** [comment]
The log indicates that some other process has the lazer files open. Please check the Task Manager and see if there are any programs running that might be keeping them open.

**Comment by richp2k** [comment]
Restarted my computer and installer worked. Thanks!
