### ISSUE TITLE
Hide zero-length sliders

### ISSUE THREAD

**Issue by Wieku** [ppy/osu#9756]
**Describe the new feature:** 
Some loved maps (like [this](https://osu.ppy.sh/beatmapsets/884669#osu/1935058), [this](https://osu.ppy.sh/beatmapsets/791900#osu/1676490) (not really loved but a bit popular map) and [this](https://osu.ppy.sh/beatmapsets/832364#osu/1743837)) use a gimmick that when slider's pixelLength is set to <= 0 it completely disappears from playfield but its head is normally clickable. Map creators use this to replace them with storyboarded hitcircles or other shapes. I think It would be nice to add the same behavior in lazer.

**Comment by peppy** [comment]
In such cases, how does the slider behave different from a hitcircle? Describing the full behaviour here may help us decide whether we can support this bug abuse or not.

**Comment by abraker95** [comment]
taken from here https://osu.ppy.sh/community/forums/topics/801973

>All sliders have, by default, a different hitwindow. It's normal to hit the sliderhead and receive 300s, despite having clicked on them during the 100/50 hitwindow. Clicking way too early on a sliderhead also results in a "miss", breaking your combo and not registering your click.
>
>However, invisible sliders don't have a normal hitwindow.
If you click way too early into them, it works the same way as a slider.
However, after the +0ms mark (The precise time the hitobject is on the map), it gives a miss instantaneously.

**Comment by peppy** [comment]
So the hitwindow is already kinda weird to support as sliders in lazer have different lenience. Making them invisible is probably less of an issue.

**Comment by Wieku** [comment]
No no, changing the hit window behavior is out of question. Actually current lazer behavior is better, because those "hit circles" are clickable as normal hitcircles (even after slider's end time) with normal judgement. Only change needed is to hide them in such cases.

**Comment by GeNeRaL-ShAdOw** [comment]
Yes. If we listen carefully, for the map for aleph 0 by Mr Helix, at point 00:28:623 - to point 00:40:409 - it has double hitsounds for each object. The sliders are just invisible, they are still there. https://osu.ppy.sh/beatmapsets/884669#osu/1935058
I'm sorry if I just stated the obvious.
