### ISSUE TITLE
some mania skins have the input line under the key section making timing notes more confusing than normal

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#9758]
as a example, in lazer, the input line for this skin is under the key section which the notes go behind
this makes it confusing to determine when to hit the note because the input line is not visible as it's in the key section

this is easiest to see when you set the lane speed to a very high ms value

skin used as example:
https://osu.ppy.sh/community/forums/topics/365036

**Comment by peppy** [comment]
Please provide screenshots of lazer and expected.

**Comment by genericthing** [comment]
wait, i checked and it's just the problem with the skin itself
