### ISSUE TITLE
problem with raw imput

### ISSUE THREAD

**Issue by DMLFreal** [ppy/osu#976]
when i turn on raw imput it doesn't work with tablet but it works with mouse.
here is a video showing the problem:
https://www.youtube.com/watch?v=jRxc5xJrnwc

**Comment by Tom94** [comment]
We do not yet support tablet / touch input.

**Comment by benzrf** [comment]
Any ETA on that?

**Comment by peppy** [comment]
no, but you are welcome to help out to make it happen!
