### ISSUE TITLE
osu!lazer running with lag and latency (Mac)

### ISSUE THREAD

**Issue by CtrlAltWaverick** [ppy/osu#9767]
**Describe the bug:** 
I know this is one of the most vague things to file a bug for, but I don't know why it's happening. osu! is running at 15 fps and with about 200ms of input delay as far as I can tell.

**Screenshots or videos showing encountered issue:**
I can't screen-record on my computer, and screenshots don't show it well. sorry :/

**osu!lazer version:** 
2020.801.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5016776/database.log)
[network.log](https://github.com/ppy/osu/files/5016777/network.log)
[performance.log](https://github.com/ppy/osu/files/5016778/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5016779/runtime.log)
These logs show me opening osu!, trying to play a map I had already downloaded, downloading a new map, attempting to play it, and then watching auto play it.

Note: It's been going on for a while, and sometimes when I open lazer, I can't move the mouse at all.
I've tried:
-restarting
-updating to Mac OS 10.15 Catalina
-restarting again
-updating osu!
-clearing cache

**Comment by bdach** [comment]
You are right in saying that your report is vague - in fact currently it's too vague to be actionable. Please provide:

- your full hardware specs (I have some bits from the logs, but not all of it),
- a screenshot with the fps overlay (preferably in its expanded mode - you can do that by pressing <kbd>Ctrl</kbd>+<kbd>F11</kbd> twice),
- also maybe a screenshot of the performance overlay (please open it by pressing <kbd>Ctrl</kbd>+<kbd>F2</kbd> and scroll to the *Update (Top CPU consumers)* section at the end).

What I *can* notice from your log is a pretty low-end graphics card (Intel HD 4000) and a seemingly absolutely ancient opengl version (glsl version reported is 1.20, which would be either normal opengl 2.1 or GLES 2.0, both of which are at least a decade old). It might be that we just haven't optimised for lower-end devices yet.

**Comment by CtrlAltWaverick** [comment]
![Screen Shot 2020-08-03 at 12 57 09 PM](https://user-images.githubusercontent.com/35770107/89207802-53b79f00-d589-11ea-8747-0ec71d39cedd.png)
![Screen Shot 2020-08-03 at 12 55 43 PM](https://user-images.githubusercontent.com/35770107/89207804-54503580-d589-11ea-8734-c06e73fd1937.png)
![Screen Shot 2020-08-03 at 12 55 28 PM](https://user-images.githubusercontent.com/35770107/89207805-54503580-d589-11ea-9d64-b379f14f45ed.png)
![Screen Shot 2020-08-03 at 12 53 34 PM](https://user-images.githubusercontent.com/35770107/89207806-54503580-d589-11ea-8e30-d1777ca83c6d.png)
![Screen Shot 2020-08-03 at 12 53 24 PM](https://user-images.githubusercontent.com/35770107/89207807-54e8cc00-d589-11ea-8d5d-cd68ec8301bf.png)
![Screen Shot 2020-08-03 at 12 53 13 PM](https://user-images.githubusercontent.com/35770107/89207808-54e8cc00-d589-11ea-867e-61fd81f7b26b.png)
I think these screenshots should cover it. Let me know if you need any others. 

Regarding OpenGL, Apple hasn't supported OpenGL properly for a very long time. I'm surprised that things relying on it still work, honestly. (Should I open a feature request ticket for support for Metal, Mac's native graphics engine?)

As for the graphics card... my computer is a Mac Mini from 2013. That's really all there is to say on the matter.

**Comment by bdach** [comment]
Yeah, unfortunately looks like the GPU's not doing so well (update can easily support 60fps but draw thread is bottlenecking hard  - buffer swaps, highlighted in red, seem especially slow).

We have plans for adding support for other graphics backends (vulkan/direct3d) for compatibility/performance in the future, but that's probably not happening anytime soon, unfortunately. Not sure there's anything obvious we can do to fix this for you right now.

**Comment by Wieku** [comment]
@bdach Buffer swap is so slow because all queued GL commands are executed then if they're not flushed before

**Comment by bdach** [comment]
That might have to do something with the macOS always-on-regardless-of-vsync `glFinish` call (https://github.com/ppy/osu-framework/pull/3258), but (a) on some macs that apparently made things *faster*, and (b) those queued commands need to run at some point anyway, so if it's that, then there's not much that we seemingly *can* do?

**Comment by Wieku** [comment]
@CtrlAltWaverick How many FPS do you get when you turn VSync on?

**Comment by CtrlAltWaverick** [comment]
I don’t know the specific stats, but it’s notably worse.

**Comment by peppy** [comment]
Have you tried making the window smaller? This looks like either draw call or fill rate bottlenecks. We will see improvements over time to performance which may help your situation so please check back regularly.
