### ISSUE TITLE
Sourcetree Faching Error

### ISSUE THREAD

**Issue by RachelleVanmeter** [ppy/osu#9774]
**Describe the bug:** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:**

![image](https://user-images.githubusercontent.com/18639239/89306664-25ca7b80-d6ab-11ea-8ef3-93b1d0a5b2d9.png)
![image](https://user-images.githubusercontent.com/18639239/89306610-0f242480-d6ab-11ea-8f4d-00901e954b1d.png)

**Comment by peppy** [comment]
This is an issue with your local git checkout. Please ask for help elsewhere, or just re-clone from scratch if you aren't interested in retaining local history.
