### ISSUE TITLE
hitcircles hide behind the spinner

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#9775]
intended:
![screenshot011](https://user-images.githubusercontent.com/44514667/89349920-a7eb7d80-d674-11ea-9237-b1706eed0509.jpg)
unintended:
![osu_2020-08-04_17-02-35](https://user-images.githubusercontent.com/44514667/89349932-b043b880-d674-11ea-87b6-444469429510.jpg)

osu!lazer version: 2020.801.0

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/2823

**Comment by peppy** [comment]
please search before posting, this isn't the first time this has happened..
