### ISSUE TITLE
Long marathon causing freeze and crash

### ISSUE THREAD

**Issue by AuracleTech** [ppy/osu#9776]
Lazer seems freeze ultimately causing a crash when playing a 52:54 Marathon map.
The map is _The Unforgiving - Within Temptation_.
I also tested _paraparaMAX - Yoko Ishida_ and it seems to freeze and unfreeze quicker (Map 35:53) so probably the longer the map the bigger the lag.

11 sec video (freeze then crash) https://clips.twitch.tv/SuspiciousAnimatedSalamanderKeyboardCat

2020.804.0

[database.log](https://github.com/ppy/osu/files/5025015/database.log)
[network.log](https://github.com/ppy/osu/files/5025016/network.log)
[performance.log](https://github.com/ppy/osu/files/5025017/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5025018/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5025019/updater.log)

Ryzen 7 2700, RTX 2060, NVMe 1TB, 16GB RAM

**Comment by peppy** [comment]
there's no crash in your logs. are you sure you just didn't wait long enough? the freeze is known and due to memory clean-up, but it shouldn't crash.

**Comment by AuracleTech** [comment]
Made an entire 60sec clip this time in desktop mode, you can really see it stop working.
https://clips.twitch.tv/NurturingPreciousTitanTF2John

[network.log](https://github.com/ppy/osu/files/5025346/network.log)
[performance.log](https://github.com/ppy/osu/files/5025347/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5025348/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5025349/updater.log)
[database.log](https://github.com/ppy/osu/files/5025350/database.log)

**Comment by peppy** [comment]
Did you wait for several minutes after that?

**Comment by AuracleTech** [comment]
No I close it, if I wait 30sec osu lazer come back at normal, but would you like to keep it like this?

**Comment by Moltanicaa** [comment]
There is no way to repeat this error. The lazer closed both maps after a short wait. Here can have an impact that the Intel processor? It sounds funny, but maybe that's what it does.

**Comment by AuracleTech** [comment]
I'd be impressed if the CPU model changed something that drastically, I'll ask my friend to do a test on his intel hardware.

**Comment by peppy** [comment]
I'm asking you to wait several minutes (go get a coffee or something) to confirm it's not going to eventually recover (hypothesis).

**Comment by AuracleTech** [comment]
I'll do a recap of my tests:
Osu Stable
- Load : Instantly
- Unload : Instantly

Osu Lazer
- Load : about 20 seconds
- Unload : about 20 seconds but if anything is touched, windows take over and it's doom for minutes

**Comment by peppy** [comment]
Thanks for confirmation. This will likely be resolved with upcoming hitobject pooling optimisations.

**Comment by AuracleTech** [comment]
Digging the graveyard to find nice maps, I downloaded a map with 13k notes without noticing.
When I pressed play it was lagging, that's when I noticed. So I pressed escape to exit the play, and delete the map.
After deleting the map, lazer went ballistic, playing 3 musics _at the same time_ (could only pause 1), constantly freezing, borderline crashing while taking insane amount of ram, this map just broke apart the game.

Maybe in waiting for a new optimization system, lazer could show a _warning_ if a map exceed a reasonable amount of notes/time.
Entire desktop with osu taking 12gb of ram [https://i.snipboard.io/cUJVTD.jpg](url)
This is a major instability. I think it deserves at least a short-time solution.

2020.907.0

[performance.log](https://github.com/ppy/osu/files/5191902/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5191903/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5191904/updater.log)
[database.log](https://github.com/ppy/osu/files/5191905/database.log)
[network.log](https://github.com/ppy/osu/files/5191906/network.log)

**Comment by peppy** [comment]
Please wait patiently.

If you need a warning: you can see the count of hitobjects in the info on the left.

**Comment by Joehuu** [comment]
Seems to be fixed according to OP, probably by pooling improvements since.
