### ISSUE TITLE
Required to press skip twice to skip the break on some maps

### ISSUE THREAD

**Issue by AuracleTech** [ppy/osu#9787]
On some maps, we need to press skip twice to skip the break. _Not tested for mid-game breaks._

21 sec video of a map without the problem and one with https://clips.twitch.tv/RelatedEphemeralZucchiniTwitchRPG

2020.801.0

[runtime.log](https://github.com/ppy/osu/files/5032438/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5032439/updater.log)
[database.log](https://github.com/ppy/osu/files/5032440/database.log)
[network.log](https://github.com/ppy/osu/files/5032441/network.log)
[performance.log](https://github.com/ppy/osu/files/5032442/performance.log)

**Comment by Wieku** [comment]
This is intended behavior. [Alarm](https://osu.ppy.sh/beatmapsets/882649#osu/1845292) map contains storyboard and you have storyboards enabled. Some storyboards have intros which can be skipped to song start.

**Comment by AuracleTech** [comment]
Unexpected, I guess it's normal then.

**Comment by AuracleTech** [comment]
But wait if this is normal why on osu stable it's actually normal?
6 sec clip https://clips.twitch.tv/OilyVibrantAxeImGlitch

**Comment by AuracleTech** [comment]
But wait if this is normal why on osu stable it's actually normal?
6 sec clip https://clips.twitch.tv/OilyVibrantAxeImGlitch

**Comment by Wieku** [comment]
Yeah just checked that.
It seems in stable when intro is shorter than X it skips immediately to the map start.
But this feature does exist in osu: https://streamable.com/cqov62

**Comment by AuracleTech** [comment]
Strange, I'll let this ticket open as this is not the Osu! stable standard time of skip variable, probably a small adjustment required.

**Comment by AuracleTech** [comment]
This issue has been fixed along the way since 2020.
Just tested under multiple conditions, with and without skipping, with and without autopilot 👍

**Comment by Joehuu** [comment]
Still seems to happen with the linked beatmap from https://github.com/ppy/osu/issues/9787#issuecomment-669669479. Quick retrying also clicks two times.

https://github.com/ppy/osu/assets/35318437/9e6a9426-d6e5-488e-b80f-31d033968aa0

**Comment by Joehuu** [comment]
Closing in favor of https://github.com/ppy/osu/issues/25633.
