### ISSUE TITLE
Porting the legacy song collection to the new installation

### ISSUE THREAD

**Issue by WorldSEnder** [ppy/osu#979]
As far as I can see, osu!lazer uses a different song folder structure than the legacy version. Instead of human readable folder names for the songs, they now are named by hexadecimal hashes of some sort.

How exactly would I reuse my "old" song collection in this case? As far as I can see there are multiple possible resultions from best to worst

 - Make it possible to stick to the old format (read and write)
   I liked the human readable names and the easily found music files. You could point your favorite music player to the Song directory and enjoy all the songs from each beatmap. It would be awesome to keep it that way. Having said that, as osu!lazer is open source, maybe someone can write a program that has all songs in a virtual folder you can mount or something.

 - Make it possible to use the old songs folder as the new beatmaps folder
   My song collection is rather huge, and I don't think I'm the only one here. To be exact, my current Songs folder has a size of ~13GB. I'd rather not duplicate all that data once I switch

 - Automate the conversion
   If none of the above options is acceptable, it should at least be possible to import the old Songs folder without expensive redownloads of each and every map

**Comment by peppy** [comment]
This will be addressed before release by importing osu-stable beatmaps (the third of your bullet points).
