### ISSUE TITLE
[Request] Provide an IPA in releases

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#9795]
**Describe the new feature:** 
Provide an IPA file with game releases to allow for easier distribution on iOS as AltStore is now the easiest way to sideload applications onto an ios device since it runs on windows and macOS.  This way, you can sidestep TestFlight for those who want to sideload. (Of course altstore support issues would be redirected, you could just say “Issues in this repository are not for AltStore, you must contact AltStore devs for assistance”. 
Making it fakesigned for jailbroken users would also be great as this way jailbroken users can completely bypass TestFlight.

**Proposal designs of the feature:** 
idk maybe name it `sh.ppy.osulazer.ipa`

**Comment by peppy** [comment]
We are not doing this sorry. Please build it yourself.
