### ISSUE TITLE
osu! Heartbeat is out of time

### ISSUE THREAD

**Issue by Gmanuel1337** [ppy/osu#9796]
When I hover my mouse over the osu!cookie the heartbeat is out of time

https://youtu.be/RD5Kpp__wPI

**osu!lazer version:** 
2020.806.0

**Comment by Wieku** [comment]
I would say that's the problem of beatmap timing

**Comment by Wieku** [comment]
off-sync*
After listening for some time heartbeat feels off-sync on all songs.
After looking at `osu-logo-heartbeat.mp3` in audacity there's a 25ms offset after which "click" starts playing:
![image](https://user-images.githubusercontent.com/5307179/89606611-ab4b5880-d870-11ea-9b5b-87ae0ae6d1a9.png)

After applying -25ms offset here:
https://github.com/ppy/osu/blob/bb6e05404b29749bc93b2384ec94a344b5dd2057/osu.Game/Screens/Menu/OsuLogo.cs#L282

the heartbeat feels sync in all cases. But I think 25ms offset shouldn't be that noticeable as it's not a hitsound so actual delay has to be much higher.

So in my older lazer project I replaced `osu-logo-hearbeat.mp3` with WAV version of it (just opened mp3 in audacity and exported as WAV) and made two audio recordings: one using mp3 heartbeat and second one with wav heartbat.
After syncing the music it seems that the mp3 sample has 12ms of additional delay:
![image](https://user-images.githubusercontent.com/5307179/89608429-6544c380-d875-11ea-8f76-5b6ae6e90ee0.png)

So to fix that that empty space in mp3 sample should be trimmed and also should be used in WAV format.

**Comment by Wieku** [comment]
There's an Audacity project if anyone is interested:
[osu-logo-heartbeat.zip](https://github.com/ppy/osu/files/5039349/osu-logo-heartbeat.zip)

**Comment by peppy** [comment]
Audacity is likely not reading the mp3 offset correctly. Anyway, in the linked video
- The beatmap is probably not perfectly timed.
- The game is running badly, which will increase the inaccuracy of sample playback.

I do not believe this is a universal issue.

**Comment by Gmanuel1337** [comment]
The map is ranked so it's timed correctly (I tried with several maps), the most likely option is that the game is running badly but it would be weird since I don't experience any lag and I was just in the main menu playing music.

**Comment by Wieku** [comment]
> * The beatmap is probably not perfectly timed

@peppy As I mentioned in my comment, at least in my case, it's noticeable with all maps (to smaller or bigger degree, I think it depends on drum kicks and BPM)
And in osu!stable heartbeat on Protoflicker feels it's in sync.

And in my case draw/update ups hits over 1k/s, so this isn't the source of delays.

**Comment by Steffo99** [comment]
Following this issue, as I feel like I'm getting weird hitsound desync in the latest git version and it may be related to this.

**Comment by Wieku** [comment]
@Steffo99 This issue is not about hit sounds. It's about osu! heartbeat in the main menu. Hitsounds being delayed is most probably an issue on your end or with the skin you're using.

**Comment by Steffo99** [comment]
_nevermind then, i misread the issue, sorry!_

**Comment by peppy** [comment]
@Wieku feel free to PR the wav resource change if you can, trimming all silence (or close to) from the start of the sample.
