### ISSUE TITLE
Hit circle overlay positioned incorrectly in slider heads

### ISSUE THREAD

**Issue by Gmanuel1337** [ppy/osu#9797]
https://youtu.be/b7Cw1ObFHFY

1st Stable 2nd Lazer

(Skin: Yugen Final)

**osu!lazer version:** 
2020.806.0

**Comment by Joehuu** [comment]
Maybe not positioned incorrectly but because the slider border is more thick in lazer by default and not correctly handled with legacy skins yet.

Closing as a duplicate of https://github.com/ppy/osu/issues/8272.
