### ISSUE TITLE
Taiko hitsounds should be preferred over the normal ones

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#9800]
In taiko mode, stable prioritises `taiko-` samples over the normal ones. Our lookup order is inversed:
https://github.com/ppy/osu/blob/d8ffc00f75a06a9f0d802357a8acb79b247d0a05/osu.Game/Skinning/LegacySkin.cs#L373-L381

**Comment by peppy** [comment]
Reading over the referenced code, the lookup looks correct to me. I'm guessing you came across an issue with taiko skins - can you mention the details of that if so?

**Comment by smoogipoo** [comment]
The issue was actually reported by @osuShiro (please provide skin). But as far as I can see stable will check `taiko-` samples before falling back to the osu! default skin.

**Comment by pavlukivan** [comment]
Can confirm this is still happening, the sounds are pretty jarring.

**Comment by peppy** [comment]
@pavlukivan can you test on `master`, as we've recently made changes to sample lookup logic (over the last few days).

**Comment by pavlukivan** [comment]
they are still broken in my HD branch which is a bit outdated but still pretty recent

**Comment by peppy** [comment]
While looking into this, I've also noticed that `TaikoLegacySkinTransformer` is bypassing this logic in the base transformer:

https://github.com/ppy/osu/blob/00574a528868d1ef31907484e71623969c0cfeaf/osu.Game/Skinning/LegacySkinTransformer.cs#L39-L44

Not sure if this is important or not, but going to document here in case someone know better than I do.

**Comment by bdach** [comment]
I at one point [claimed](https://github.com/ppy/osu/pull/9340) that layered samples did not apply to taiko but on checking stable source I'm no longer too convinced that's true. May indeed be a factor here.

**Comment by peppy** [comment]
The issue pointed out in this thread does look to be fixed, though:

![20210611 170328 (JetBrains Rider-EAP)](https://user-images.githubusercontent.com/191335/121652825-05dbc380-cad7-11eb-8276-ed97a79c318b.png)

Regarding the opening post, stating the order is inverse: I believe this is an incorrect assumption. The first case is one with a lazer-default prefix, which would be silently ignored for legacy skins (making the `taiko-` prefixed lookups the first meaningful one).

Going to close this for now. If anyone is still able to reproduce these issues on the next public release, please provide your skin in this thread and I'll take another look.
