### ISSUE TITLE
 Please, add a directx compatibility mode

### ISSUE THREAD

**Issue by Xxitra** [ppy/osu#9803]
Hi ppy!
I wanted to ask you a great favor, I consider myself a big fan of your game "Osu!" and I think it is an excellent game, so I have bought osu! support to support you with the development of the game.
However, there is something that worries me, and that is that osu! Lazer (the future of osu!) Is not compatible with older computers :(
I don't have a dedicated graphics card or a good processor, osu! It works great for me and I have a lot of fun playing it, but osu! lazer doesn't open or run. I investigated through forums and I found one in which you said that osu! Lazer would not be compatible with directx or something like that, and the truth is I wish there was support for old computers, I would like to try it and play it, and in turn, stop worry so that in the future osu can play.
I hope you read my message and take it into account, have a great day! (Sorry for my English, I speak Spanish)

**Comment by peppy** [comment]
If you don't have a dedicated graphics card, I would highly recommend continuing to use stable for now.

We will offer more graphics options in the future but I cannot guarantee it will run under software rendering at the same performance. But it's not an impossible feat, either.
