### ISSUE TITLE
allow blocking maps from being chosen in multiplayer

### ISSUE THREAD

**Issue by igontusuwu** [ppy/osu#9804]
this is for normal multiplayer

the room creator can have a list of blocked maps so that people with host can't choose those maps

it can be used because you might not want people to spam certain maps because it gets annoying when it's just those maps

**Comment by peppy** [comment]
Either meant for stable, or too early to propose (real-time multiplayer has not been implemented yet).

**Comment by igontusuwu** [comment]
reopen this when real-time multiplayer gets put in lazer
