### ISSUE TITLE
Replay accuracy caculation different from stable

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#9806]
**Describe the bug:** 
Imported some replays from stable, and the accuracy is always incorrect.
**Screenshots or videos showing encountered issue:** 
![osu_2020-08-08_11-13-42](https://user-images.githubusercontent.com/50285552/89701440-a918f500-d969-11ea-89a3-3feb584f7781.jpg)
![osu_2020-08-08_11-25-51](https://user-images.githubusercontent.com/50285552/89701492-0d3bb900-d96a-11ea-9a21-0a5579d34fcc.jpg)
![osu_2020-08-08_11-26-25](https://user-images.githubusercontent.com/50285552/89701494-0e6ce600-d96a-11ea-8f66-5cd07a614ef5.jpg)
![osu_2020-08-08_11-27-55](https://user-images.githubusercontent.com/50285552/89701687-ccdd3a80-d96b-11ea-9664-feaf5b88ba1d.jpg)
![osu_2020-08-08_11-40-06](https://user-images.githubusercontent.com/50285552/89701696-eda59000-d96b-11ea-981d-15780d07511f.jpg)

**osu!lazer version:** 
2020.806.0

Replay files
[Replays.zip](https://github.com/ppy/osu/files/5044570/Replays.zip)
[Beatmap1](https://osu.ppy.sh/beatmapsets/1098490#osu/2298169)
[Beatmap2](https://osu.ppy.sh/beatmapsets/1097600#osu/2293451)
**Logs:**
[logs.zip](https://github.com/ppy/osu/files/5044584/logs.zip)

**Comment by peppy** [comment]
lazer scoring is different in many ways. this is to be expected.

**Comment by Wieku** [comment]
It's also a duplicate of #7521
