### ISSUE TITLE
Osu! Won't open in my android phone.

### ISSUE THREAD

**Issue by ZeroTw02** [ppy/osu#9807]
Osu! Won't open in my android phone please tell me what's happening and how to fix it.
https://youtu.be/LrA_g5O6O9Q
Go to this link and see the problem.
![Screenshot_2020-08-08-20-15-55](https://user-images.githubusercontent.com/69199165/89710378-e3f44a80-d9b4-11ea-8ccc-d6488b21bd32.png)
![Screenshot_2020-08-08-20-16-14](https://user-images.githubusercontent.com/69199165/89710383-f1113980-d9b4-11ea-92c8-ebc9797cbc95.png)
I also think that my phone specs affect this problem so here are some screenshots of my phone specs please tell me if there is something wrong with my specs.

**Comment by bdach** [comment]
Please attach logs from `Android/Data/sh.ppy.osulazer/logs`.

The attached screenshots also have nothing relevant on them except for how much storage space you have (no android version, no phone make & model info, no hardware specs).

**Comment by ZeroTw02** [comment]
Where do I find logs and how to attach them. I am playing osu! In my pc and it is my first time doing it on phone.

**Comment by bdach** [comment]
I have given you the path to the folder that should contain them in the comment above (please check both internal and external storage). They can be attached by transferring them onto your PC and then dragging them into the comment box.

**Comment by ZeroTw02** [comment]
I don't see the logs folder here.
https://youtu.be/BegRDu9bOMA

**Comment by ZeroTw02** [comment]
Its the only folder closest to osu!.

**Comment by ZeroTw02** [comment]
![Screenshot_2020-08-08-20-41-00](https://user-images.githubusercontent.com/69199165/89710663-99c09880-d9b7-11ea-9874-4756afa19f94.png)
Do I have to download any of this?

**Comment by bdach** [comment]
Something looks very off here. I don't recognise the package name (what is `ru.nsu.ccfit.zuev.osu...`?)

Where did you download the `.apk` from?

**Comment by ZeroTw02** [comment]
I downloaded it from the releases page.

**Comment by ZeroTw02** [comment]
Maybe that folder belongs to osu droid
![Screenshot_2020-08-08-20-44-50](https://user-images.githubusercontent.com/69199165/89710731-253a2980-d9b8-11ea-8684-896bacd10542.png)
But I don't see dual osu folder.I don't see the sh.ppy.osulazer folder one.

**Comment by bdach** [comment]
if it isn't there, it's likely this is a device compatibility issue, but i can't tell for sure as you still haven't provided any information about the hardware you're attempting to run on.

**Comment by ZeroTw02** [comment]
Do you have the sh.ppy.osulazer folder maybe you can send it to me and I
will just attach it to android/data/ folder.
Maybe it will work.

**Comment by bdach** [comment]
that's not how any of this works. the folder should be created automatically. if it isn't then it means that the app is refusing to start at all for some reason.

**Comment by ZeroTw02** [comment]
This is the permissions that I have on my settings.

**Comment by bdach** [comment]
this should not be a matter of permissions, either.

i'll restate again: please provide the actual manufacturer and model of the device you're attempting to run on.

**Comment by ZeroTw02** [comment]
My phone is huawei p8 lite.
![Screenshot_2020-08-08-20-55-30](https://user-images.githubusercontent.com/69199165/89710950-cb3a6380-d9b9-11ea-9580-c70429f553e6.png)
![Screenshot_2020-08-08-20-55-43](https://user-images.githubusercontent.com/69199165/89710952-d2617180-d9b9-11ea-93de-2cd014362cf4.png)

**Comment by bdach** [comment]
i have deleted your comment as it showed some information that should not be exposed (imei number, device serial number).

for the record: the stated device name was Huawei P8lite. investigating whether it has a GPU with an opengl version we support.

**Comment by ZeroTw02** [comment]
Huawei p8 lite is my phone here are the specs.(I put my screenshot of my ip adress so it got deleted)
![Screenshot_2020-08-08-20-55-30](https://user-images.githubusercontent.com/69199165/89711100-b6120480-d9ba-11ea-8196-496aa9077a01.png)

**Comment by bdach** [comment]
*please* wait. there is *no* need to repost the pictures. i explicitly requested only the manufacturer & model of the device.

**Comment by ZeroTw02** [comment]
https://www.devicespecifications.com/en/model/b95e33c3
I found this on chrome maybe it can help.

**Comment by bdach** [comment]
upon investigation it seems that the device you own uses a Mali-450MP4 GPU chipset, which only supports OpenGL ES 2.0 at the highest, which is not high enough for our uses. that's not something we can support for now.

closing as there's nothing we can do for you in the near future. in the future we'll be considering alternate graphics back-ends but that sort of work is months away currently.
