### ISSUE TITLE
Add support for writing in Thai

### ISSUE THREAD

**Issue by ikkue** [ppy/osu#9808]
**Describe the new feature:** 
Currently when typing with Thai as the language it comes up as gibberish Latin characters.
**Proposal designs of the feature:** 
Add the support for the ability to type in Thai for every Thai Unicode characters.

**Comment by bdach** [comment]
Other non-latin languages have this problem for now; we will be hopefully resolving this with a move away from SDL.

Closing as this is already tracked elsewhere (in #5827, for instance).
