### ISSUE TITLE
Exporting collections to a text document

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9809]
**Describe the new feature:** 
A collection can contain hundreds of maps and I would like to be able to somehow export them to a document where the name of the maps would be. It is very disappointing to lose collections after changing computers (copying the collection.db file does not help much). I understand that there are no collections in the lazer yet, but I believe that this function should be after their implementation.
**Proposal designs of the feature:** 
It can be a simple text document with a title + a link to a map (if possible)

**Comment by bdach** [comment]
Potentially could be stored web-side too (maybe as a supporter feature), but seeing that collections aren't even *in* yet, this will not be happening any time soon.

**Comment by smoogipoo** [comment]
Going forward collections will be stored web-side, and further features will follow on from there (e.g. sharing). This requires the implementation of collections first. I'm closing based on the previous two issues (premise is different to what we have in mind, and it's too early).
