### ISSUE TITLE
G-Sync is not working correctly in osu!lazer

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#9810]
When using G-sync while playing osu!lazer, the frame rate goes all over the place and gameplay gets pretty choppy. Turning off G-sync makes the stutters go away and makes the framerate go back to normal.

https://youtu.be/ss2oBDARF4I (this is a hardware fps counter. the fps counter in osu!lazer shows a stable 144 fps but that is not actually the case)

**osu!lazer version:** 2020.806.0

**Comment by Joppe27** [comment]
This bug is fixed in SDL. Sorry, I probably should've tested that before opening an issue...

**Comment by bdach** [comment]
We also have #5586 open already which seems related.

Closing this and marking aforementioned issue as `fixed-in-sdl`.
