### ISSUE TITLE
Improve error message upon failing to retrieve multiplayer score submission token

### ISSUE THREAD

**Issue by bieel1503** [ppy/osu#9813]
**Describe the bug:** 
When trying to play multiplayer, the error notification appears and the map doesn't load.

Using arch linux with Xorg, and i3 as window managaer. Lazer compiled using '[pikaur](https://github.com/actionless/pikaur)' and the '[osu-lazer-git](https://aur.archlinux.org/packages/osu-lazer-git/)' package from AUR.

**Screenshots or videos showing encountered issue:**
https://youtu.be/t_1DFnhVumc

**osu!lazer version:**
Lazer 2020.806.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5045983/database.log)
[network.log](https://github.com/ppy/osu/files/5045984/network.log)
[performance.log](https://github.com/ppy/osu/files/5045985/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5045986/runtime.log)

**Comment by bdach** [comment]
We are not responsible for maintenance of the AUR package you mention. This will happen as the score submission token is the hash of the binary, and we don't do reproducible builds as far as I'm aware, so it's incredibly likely the hash will be different.

Please use the official supplied appimage from the "Releases" page to play multiplayer.

**Comment by frenzibyte** [comment]
Should elaborate in the notification when entering multiplayer that playing is not gonna be allowed for self-compiled game instances.

**Comment by bieel1503** [comment]
Sorry, i wasn't aware of this. But this also happen on android using the .apk release.

**Comment by bdach** [comment]
We are also aware of that as there is currently no way to retrieve the hash of the appropriate binary on android (see #9737 for paper trail).

Will reopen for better error handling I suppose.

Also, cc: @huupoke12, as you seem to be listed as maintainer of the AUR package; this should probably be at least signposted on the package itself (if you don't want to pull the package, which I think would be better for everyone and avoid unnecessary confusion/fragmentation).

**Comment by dkanada** [comment]
Will this situation change in the future, or will distro builds be singleplayer only from this point forward? This seems like a great way to prevent unofficial builds so I can understand if nothing will change. As a side note, perhaps an official docker image might be possible as an alternative to AppImage? Are there any long term plans for reproducible builds?

**Comment by dkanada** [comment]
I don't exactly know how you're collecting the hashes on CI for the tokens, but I'd be willing to implement docker support so I can avoid adding AppImages to my workflow if that suggestion sounded okay.

**Comment by dkanada** [comment]
Will this situation change in the future, or will distro builds be singleplayer only from this point forward? This seems like a great way to prevent unofficial builds so I can understand if nothing will change. Are there any long term plans for reproducible builds?

**Comment by peppy** [comment]
Access to online systems will require the presence of some components from our end.

We may be able to support custom builds to some degree (ie. everything bar score submission), but that's not a top priority, as I'm sure you can understand for a competitive online game.

**Comment by dkanada** [comment]
Would you consider supplying portable binaries as an alternative to the AppImage builds? I tried the official release out yesterday and ended up with some unexpected audio skipping that has been present on older versions on Linux for quite some time, whereas the distro build had been working perfectly. I maintain another DotNet project that uses the `--self-contained` flag to provide distro agnostic builds which would allow for a semi-native package on the AUR and sidestep the AppImage releases.

**Comment by bdach** [comment]
[We already use `--self-contained`.](https://github.com/ppy/osu-deploy/blob/96dbe4afc503a0ae34aed247e04dcc97f6535d2f/Program.cs#L214)

This issue is caused by a lack of *build reproducibility*, as in even if you compile from a release tag, the compiler does not guarantee that it will spit out a binary with the exact same contents, which we then hash to ensure integrity. I don't think msbuild has a capability to do this, and even then I'm not sure we want to be spending time on such a niche setup right now.

**Comment by peppy** [comment]
You can extract the AppImage and have a portable binary.

**Comment by smoogipoo** [comment]
Perhaps we can look into providing deterministic builds in the future? https://gist.github.com/aelij/b20271f4bd0ab1298e49068b388b54ae

**Comment by dkanada** [comment]
@bdach I realize reproducibility is the issue at hand, I was just trying to think of alternate methods that would let non-AppImage builds use multiplayer. If you provided the binary independently and added the hashes to whatever whitelist you have on your infrastructure, those binaries could possibly work with multiplayer even when bundled on third party repositories. Now that you mention it, I could also just extract and use the binary on the AUR without an explicit release, but it would still need to be whitelisted for that to work.
