### ISSUE TITLE
Allow to update,reload custom rulesets at runtime

### ISSUE THREAD

**Issue by poly000** [ppy/osu#9820]
**Describe the new feature:** 
Allows [_Custom Rulesets_](https://github.com/ppy/osu/issues/5852) to be updated without restarting osu!
And allows add new Custom Rulesets at runtime.

**Comment by enoslayd** [comment]
This can be possible on linux (or maybe mac) but not windows since all open files are locked unlike linux

**Comment by bdach** [comment]
please leave the question of determining whether or not something is feasible to us.
