### ISSUE TITLE
Extreme lag on maps (especially hard maps.)

### ISSUE THREAD

**Issue by recognitionmark** [ppy/osu#9830]
**Describe the bug:** 
Maps with high amounts of objects in a time causes lag for low-end PCs and laptops.
An example of this is RAISE MY SWORD, where I tried playing it and it froze me to the point of the long s-like slider, then it froze me again.
**Screenshots or videos showing encountered issue:** 
None.
**osu!lazer version:** 
2020.716.0
**Logs:**
none.

**Comment by bdach** [comment]
Already aware of perf issues on edge-case maps (#9776, #8621, #6123, #5045, to name a few). Closing as duplicate.
