### ISSUE TITLE
Weird flickering graphical glitches

### ISSUE THREAD

**Issue by ILuvSkins** [ppy/osu#9835]
**Describe the bug:**
Some transparent black lines were flickering around very rapidly at the top left corner of the screen. Most of the maps I played had a storyboard, and the glitch would seem to be less intense on non-storyboarded maps. This glitch seems to only happen when that menu bar at the top isn't present. I also tried a Taiko diff and the glitch there was WAAAY more intense than usual. I wonder if it's just my crappy Intel Family HD (4400 I think) GPU dying or just osu!lazer being weird.
Specs:
![informationz](https://user-images.githubusercontent.com/66824635/90011762-d8ea3480-dcaa-11ea-8fe2-dbe560873f2d.PNG)

**Screenshots or videos showing encountered issue:**
video: https://www.youtube.com/watch?v=902HDXNOFzE
**osu!lazer version:** 
2020.806.0
**Logs:**
[performance-draw.log](https://github.com/ppy/osu/files/5062400/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5062401/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5062402/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5062403/updater.log)
[database.log](https://github.com/ppy/osu/files/5062404/database.log)
[network.log](https://github.com/ppy/osu/files/5062405/network.log)
[performance.log](https://github.com/ppy/osu/files/5062407/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5062408/performance-audio.log)

**Comment by peppy** [comment]
We cannot help you without visuals. Either a screen capture or a phone video if you really can't.

**Comment by ILuvSkins** [comment]
phone video is the best i can do i think, maybe when my phone is charged

**Comment by ILuvSkins** [comment]
umm why isnt the mp4 showing up

**Comment by smoogipoo** [comment]
You will probably have to .zip it.

**Comment by ILuvSkins** [comment]
k thx

**Comment by ILuvSkins** [comment]
the frick? i compressed it and github will still say that it is not supported, yet it also says it can support zip

**Comment by smoogipoo** [comment]
Try youtube.

**Comment by ILuvSkins** [comment]
nope, i don't have any youtube channel

**Comment by peppy** [comment]
Please email your video to pe@ppy.sh and stop posting to github. We will take it from here.

**Comment by peppy** [comment]
https://www.youtube.com/watch?v=902HDXNOFzE

**Comment by smoogipoo** [comment]
@ILuvSkins does it happen if you turn on `Bypass front-to-back render pass` at the bottom of settings?

**Comment by ILuvSkins** [comment]
yep, it still happens with ffront to back render pass. in fact, they flicker more rapidly with that option on...

**Comment by ILuvSkins** [comment]
i wonder if its just me or the lines flicker faster with front to back render pass...

**Comment by smoogipoo** [comment]
Check for any updates to your graphics drivers, and install the latest one.

**Comment by ILuvSkins** [comment]
yeah, ive searched for the latest video drivers for my laptop on Lenovo's website and they do not have what i'm looking for, so i guess ive already got the latest ones? i also cannot find out the driver version number so that's going to be even harder. i also don't really wanna mess up anything, i don't want my laptop to become unusable and a new one is gonna cost way over my budget

**Comment by smoogipoo** [comment]
Please provide a dxdiag log (https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) and also the full model name of the laptop.

**Comment by ILuvSkins** [comment]
here ya go
[DxDiag.txt](https://github.com/ppy/osu/files/5096061/DxDiag.txt)
also the full model name is Lenovo B50-70, thats all i could find on the sticker on the bottom

**Comment by smoogipoo** [comment]
I can't replicate this on the actual hardware you're using. The only difference in my test is I have Windows 10 installed, whereas you're using Windows 8.1

The driver for Win10 is a little bit newer, which may help. I tried to use the Win8.1 driver still without issue, but who knows if there's some OS-level trickery going on here.

Or, as you mentioned, it could be that your GPU is dying.

Either way, I'm closing this issue since it's not the game at fault, it's your GPU/driver/OS.
