### ISSUE TITLE
osu!direct search box input does not exclude keys with modifiers

### ISSUE THREAD

**Issue by 45gfg9** [ppy/osu#9836]
**Describe the bug:** 
osu!direct search input box does not exclude key combinations with keyboard modifiers (See steps below)

**Steps to reproduce**
1. Press Cmd+C ('c' should not be taken as input, right?)
2. Press V
3. You'll see "cv"

Same applies to other key combinations (Cmd/Opt/Ctrl + A/S/D/....). They do not appear in the input box immediately, but all pops up when an unmodified key is pressed.
And the combination does what it should (Cmd+C Copy, Cmd+A Select All), but the key is not excluded

**osu!lazer version:** 
osu! lazer 2020.806.0
macOS 10.15.6
Windows not tested

(I don't think this behavior is related to log?)

**Comment by frenzibyte** [comment]
I've noticed that issue a while ago, turns out it's a another weird thing with osuTK's keyboard state in macOS only, fixed in SDL though so I didn't bother opening an issue about it.

**Comment by Joehuu** [comment]
Don't have macOS, can someone confirm it's fixed as of now?

**Comment by peppy** [comment]
Works as expected now.
