### ISSUE TITLE
Taiko map starts going backwards

### ISSUE THREAD

**Issue by memesnightmares** [ppy/osu#9845]
**Describe the bug:** 

In the first map I launched after startup, the music started playing normally, but the screen started and the end of the map and then moved at ~4x speed backwards until it became even with the music, at which point everything worked normally again. I have no video because I can't seem to make it happen again and have no idea what caused it.

If this is report is useless because I can't reproduce the issue, feel free to close it.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2020.801.0

**Comment by bdach** [comment]
This report isn't really actionable now, as aside from not being able to reproduce yourself you also haven't given us any details as to how we could even try to (what map this was on, logs, etc.)

**Comment by memesnightmares** [comment]
Alrighty, thank you for taking the time to respond, I can't remember the map, and I think the logs are gone since I restarted lazer a couple times to try and reproduce it. I'll open a new issue with more info if I experience it again.
