### ISSUE TITLE
Background dim comes in too late on beatmaps that have a skip button

### ISSUE THREAD

**Issue by jalienet** [ppy/osu#9847]
On beatmaps where the intro is long enough for a skip button to appear, the background starts at a brighter dim level and darkens down to the user's preferred dim level when the gameplay starts.

This is fine and all (it seems intentional), but the dimming happens a few moments after hitting the skip button, so it feels weirdly delayed, like the game is lagging behind a bit--even though it isn't.

https://streamable.com/giexhv

**Comment by peppy** [comment]
I'm pretty sure this is just the skip button taking you to a point well before when gameplay starts (lead-in) and the fade being actuated much closer to gameplay start. It's the same as if you were to not hit the skip button.

What are you hoping for here – having skip take you closer or having the fade start earlier, even when not skipped?

**Comment by jalienet** [comment]
Having the fade start earlier. I'm aware that the fade starts at the same point in time when not skipping.
