### ISSUE TITLE
Audio pitch doesn't change correctly in some cases

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9850]
**Describe the bug:** In some cases (like in the following video), the audio pitch (modified by any mod that affects it) doesn't reset properly when using the "deselect all" button.

**Screenshots or videos showing encountered issue:** [Video](https://drive.google.com/file/d/13BplFRPYqkdDTBFYDJLcF0O-tBu0fz_p/view?usp=sharing)

**osu!lazer version:** 2020.806.0

**Comment by smoogipoo** [comment]
We may need a "RemoveFromTrack" reverse event for these mods.

**Comment by Gabixel** [comment]
I can't reproduce it (in [2020.814.0](https://osu.ppy.sh/home/changelog/lazer/2020.814.0))... Has something changed?

**Comment by bdach** [comment]
I would be surprised if it was due to any of the changes in that version, but I couldn't reproduce in the first place.

**Comment by smoogipoo** [comment]
I'm going to close this because none of us can replicate and it's properly handled in code via https://github.com/ppy/osu/blob/ca2bc0f08eae89cd9b322b09bd1888b5eaa63ae3/osu.Game/Overlays/MusicController.cs#L83 .

Please report back if you manage to replicate on the latest build.
