### ISSUE TITLE
Extreme freezes

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9851]
**Describe the bug:** 
I understand that this may be the hundredth problem, but for a very long time my lazer simply refuses to work normally. There is a large red zone on the performance graph, which is always there.
No manipulation will reduce it, the total consumption of the lazer does not change (the same as always). However, when recording, things get even worse. If you click on ctrl + f2, then several messages about a long load appear.

I doubt that the problem is with my computer, because if you start ONLY the lazer, the situation will be the same. The --sdl command does not help.
Only the inclusion of the Vsink helps a little (recording artifacts disappear).
**Screenshots or videos showing encountered issue:** 
https://youtu.be/t5sUs_cPzHY
**osu!lazer version:** 
2020.806.0
**Logs:**
[performance-audio.log](https://github.com/ppy/osu/files/5074267/performance-audio.log)
[database.log](https://github.com/ppy/osu/files/5074268/database.log)
[network.log](https://github.com/ppy/osu/files/5074270/network.log)
[updater.log](https://github.com/ppy/osu/files/5074271/updater.log)
[performance.log](https://github.com/ppy/osu/files/5074272/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5074273/runtime.log)
[performance-draw.log](https://github.com/ppy/osu/files/5074274/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5074275/performance-update.log)

**Comment by peppy** [comment]
Red is swap buffer. It is likely due to vsync being forced on, or running windowed / borderless.

Please ensure you're running full screen and don't have vsync forced.

**Comment by Moltanicaa** [comment]
The video shows the settings

**Comment by bdach** [comment]
Has this always been the case, or did it get worse with an update?

**Comment by peppy** [comment]
Yes, I watched the video. It 100% looks like vsync is enabled from the video. You can tell because every frame is swap buffering to a specific frame time value. Please follow my advice above.

**Comment by Moltanicaa** [comment]
2-3 months. This greatly interferes with video recording, because there are many artifacts on the recording. The problem may disappear and return at a random moment. Restarting the computer does not help, the computer is not loaded with anything. Now I will record another video

**Comment by Moltanicaa** [comment]
Pressing ctrl + f2 worsens the situation even more. And with the borderless mode there are no artifacts.
https://youtu.be/zsa3P4EmGDo

**Comment by smoogipoo** [comment]
Red with VSync on -> intended. That's how VSync works (by sleeping during the swapbuffer time).

Red with VSync off -> you're reaching GPU limits. There's either something running in the background on your system that's taking away GPU time - an overlay like Steam overlay or f.lux, a video in a browser, a recording program, or your GPU is just not powerful enough. Given that you have a 1650 I'm inclined to believe it's the former. How does task manager's GPU graph look with/without lazer open?

**Comment by Moltanicaa** [comment]
Strange, but on the graph it is 99%, but I guarantee it was not always so. I already wrote to Peppy about this a few months ago with the same problem, after which it just disappeared. Then she returned. Then she disappeared again. The lazer, in principle, loads it at 99% (without recording), although this clearly should not be.

**Comment by smoogipoo** [comment]
12% sounds pretty high for background load, is there something else using your GPU? Maybe check the details page in task manager for things using your GPU:

![image](https://user-images.githubusercontent.com/1329837/90246366-77bf8e00-de6f-11ea-8230-370fd96a1b91.png)

Also do you have Nvidia Shadowplay turned on? If so try disabling it.

**Comment by Moltanicaa** [comment]
Oh, 10% was consumed by the included (without recording) OBS. I don't use shadowplay.
![image](https://user-images.githubusercontent.com/59089206/90246541-367fac00-de78-11ea-854b-398189bf7ce3.png)

**Comment by smoogipoo** [comment]
Does it run better without OBS? Using the nvenc encoder in OBS can also cause this, so check if you have that enabled.

I'll source a 1650 locally to test, but I guarantee it's something on your system - that card isn't THAT bad.

**Comment by Moltanicaa** [comment]
Hm....He consumes as much as he consumes.
![image](https://user-images.githubusercontent.com/59089206/90247006-12709a80-de79-11ea-8cbe-afcc738040bf.png)

**Comment by smoogipoo** [comment]
Keep in mind that unlimited is supposed to drive your GPU through the roof. That's kinda the point. If your GPU is the bottleneck in your system, you're going to stutter on unlimited.

A better test is running one of the other frame limiters. In your previous video even 2x was stuttering for you, so it would be great if that's resolved.

**Comment by Moltanicaa** [comment]
After several switches from 2x to 4x and back, the red zone turned blue, but if you do at least something, the red zone returns. I can attach a video.

**Comment by smoogipoo** [comment]
I think we're just going to close this here and suggest that it's still an issue with your setup, given this is the first we've heard of such a degradation. I've ordered a GTX 1650 to test the performance on and confirm, but this is not immediately actionable in any case.

**Comment by Moltanicaa** [comment]
The problem vanished the next day. I have a suspicion that this is some kind of bug of Windows itself. When this bug is activated, the record lags everywhere. There is a suspicion that it breaks this whole remote desktop connection (although I don't understand why it is here). A complete shutdown of the computer for a while helps to get rid of this problem. A strange problem.
![image](https://user-images.githubusercontent.com/59089206/90299158-6d85aa00-ded8-11ea-984f-184986614770.png)
