### ISSUE TITLE
Osu!lazer crash when using borderless mode on 4k resolution

### ISSUE THREAD

**Issue by JustRed23** [ppy/osu#9852]
**Describe the crash:**
Osu!lazer will display a black screen on startup and crash right after that when a resolution of 3840x2160 (4k) is enabled 
**with borderless mode enabled!!**

**Screenshots or videos showing encountered issue:** 
[recording.zip](https://github.com/ppy/osu/files/5074484/recording.zip)

**osu!lazer version:** 
2020.806.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/5074493/logs.zip)

**Computer Specifications:** 
OS: Windows 10 Home version 2004

Screen: lg-27UD59-B 
(https://www.lg.com/nl/monitor/lg-27UD59-B)

Processor: Intel core i7-8700 
(https://ark.intel.com/content/www/us/en/ark/products/126686/intel-core-i7-8700-processor-12m-cache-up-to-4-60-ghz.html)

Graphics card: Nvidia GTX 1660 Ti
(https://www.gigabyte.com/Graphics-Card/GV-N166TWF2OC-6GD#kf)

RAM: 16GB ddr4

**Comment by smoogipoo** [comment]
Unfortunately the logs aren't much use here. Is there any application error entry in the event viewer?

**Comment by JustRed23** [comment]
Yes! I found an error in the Event Viewer:

Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5ec598f1
Faulting module name: nvoglv64.dll, version: 27.21.14.5167, time stamp: 0x5f021eb1
Exception code: 0xc0000409
Fault offset: 0x00000000010f6fc9
Faulting process id: 0x2200
Faulting application start time: 0x01d672342429c893
Faulting application path: C:\Users\[REDACTED]\AppData\Local\osulazer\app-2020.806.0\osu!.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_edab19158bdd0d0a\nvoglv64.dll
Report Id: 0c4e371e-4d08-4741-b40c-2af09dd1a213
Faulting package full name: 
Faulting package-relative application ID:

**Comment by bdach** [comment]
`nvoglv64.dll` will be nvidia's opengl driver, I'm pretty sure. Please check for driver updates and try again; otherwise I don't know if we can do anything there.

**Comment by smoogipoo** [comment]
May also be an indication of running out of GPU memory, though 6GB @ 4K should be plenty. I'm wondering if maybe something went wrong with lazer's configuration and it's trying to initialise a huge window much beyond 4K.

Do you have Nvidia DSR enabled by any chance?

@JustRed23 if your drivers are up-to-date and it still happens, please report back.

**Comment by JustRed23** [comment]
Okay so my drivers are up to date and DSR is turned off but it still does not work.

**Comment by smoogipoo** [comment]
If you open up task manager, how does the GPU memory look before/after starting lazer?

**Comment by JustRed23** [comment]
Before: (idle) 40%
After: 35%

Okay so i also noticed that when i alt + tab to another window osu!lazer starts but when i make the window active it crashes again

**Comment by bdach** [comment]
For whatever that's worth we've had these sorts of reports before (see #9251, #6391). One time there was no response and another time a driver reinstall and reboot helped.

**Comment by JustRed23** [comment]
It is weird that it starts in 1920x1080 like nothing is wrong though.

**Comment by smoogipoo** [comment]
Maybe try reinstalling the driver + rebooting as mentioned and see if that helps.

**Comment by JustRed23** [comment]
Okay so i reinstalled the game ready driver & rebooted but it's still the same

**Comment by Wieku** [comment]
I tried to reproduce this on my desktop with NVIDIA DSR (WQHD -> 4K) and it works normally: https://streamable.com/e9xfdc
My pc specs:
i7 8700K
GTX1080 with latest (451.67) drivers
48GB RAM
Windows 10 build 18363.959 (1909 update)

Did you update the drivers with express or custom option?

**Comment by JustRed23** [comment]
I used the express option. I'm using the 2004 update (19041.450) though so maybe its conflicting with that

**Comment by Wieku** [comment]
Try to do a clean install with custom. Express retains all settings, some of them may be broken in your case.

**Comment by JustRed23** [comment]
Ok look, i'm not going to do that... i have lots of settings configured with shadowplay and i dont want to lose those. Osu!stable runs just fine with 4k borderless but whenever i try to launch osu!lazer with 4k borderless it just crashes. Fullscreen mode works just fine but borderless crashes it.

**Comment by bdach** [comment]
stable is not comparable to lazer, as the latter is a from-the-ground-up rewrite of the former. the fact that one works doesn't tell anything about the other. this is clearly something in your setup as if this didn't work globally we'd be seeing these sorts of issues way more frequently.

if you're not willing to experiment with changing the settings on your side then i don't know how we can possibly help.

**Comment by JustRed23** [comment]
Ok fine. I reinstalled my drivers and did a clean wipe... It actually works now :p. The problem was that whenever osu!lazer started shadowplay would interfere and cause it to crash. Because when i start lazer now shadowplay wont start...
