### ISSUE TITLE
"Playing osu"

### ISSUE THREAD

**Issue by Drison64** [ppy/osu#9855]
**Describe the bug:** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:**

**Comment by bdach** [comment]
Please try to fill out the issue template if you are going to be opening issues.

**Comment by Drison64** [comment]
Oh, sorry. Accidentaly clicked enter without even knowing 😄. I have found a bug, but since there is a new version I will need to try it on the updated version.
