### ISSUE TITLE
Multiple selection in pause screen

### ISSUE THREAD

**Issue by Craftplacer** [ppy/osu#9856]
**Describe the bug:** 
- Pause the game
- Select and continue the game with your keyboard (down arrow)
- Try to pause shortly after again
- Select the exit option with the keyboard (up arrow)
- The game selects both continue and exit
- Press enter and the game will continue rather than exit.

**Screenshots or videos showing encountered issue:** 
![osu_2020-08-15_01-33-09](https://user-images.githubusercontent.com/22963120/90299926-5fb03480-de98-11ea-9c05-e8940ee75d43.jpg)

**osu!lazer version:** 
2020.806.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5077797/runtime.log)

**Comment by Gabixel** [comment]
With a little patience, you can also have all three buttons "selected". I can reproduce it very easily:

![image](https://user-images.githubusercontent.com/43073074/90301301-5d9da400-de9f-11ea-99f1-7d082aad381a.png)
