### ISSUE TITLE
default lazer judgement sprites appears alongside the taiko judgement images from the skin

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#9859]
**Describe the bug:** the default lazer judgement sprites appears alongside the taiko judgement images from the skin. the skin doesnt have any hit-(x).png since the skin is a taiko only

**Screenshots or videos showing encountered issue:** 
Lazer:
![osu_2020-08-15_14-29-33](https://user-images.githubusercontent.com/41866328/90307284-35499000-df07-11ea-8d9f-e3881ee476f6.png)

Stable:
![screenshot095](https://user-images.githubusercontent.com/41866328/90306699-4a6ff000-df02-11ea-90b0-5efe764296ff.png)

**osu!lazer version:** 2020.814.0

**Skin:** https://drive.google.com/file/d/1is63tvBoQQnVybxPTla2SNvxqDY2rvZc/view?usp=sharing

Logs:
[runtime.log](https://github.com/ppy/osu/files/5078288/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5078289/performance.log)

**Comment by bdach** [comment]
@enoslayd FYI the skin is inaccessible (google drive says no permission to access the file).

**Comment by enoslayd** [comment]
> @enoslayd FYI the skin is inaccessible (google drive says no permission to access the file).

Fixed

**Comment by bdach** [comment]
So what I think is actually happening here is that the taiko-specific sprite in the skin is more specifically an *explosion*, not a judgement, in lazer code terms. The new lazer default skin has both an explosion and a judgement text, but stable actually doesn't seem to use `hit300` (without the prefix) and friends at all in taiko - it just displays explosions (with the prefix) on the drum. This can even be seen in the default legacy skin in lazer (see 300/100s/50s fading in and out above the drum - they're not there on stable).

As the skin linked doesn't have normal hit judgements skinned, the fallback goes straight to default lazer skins, leading to the double text.

It seems to me that the way to resolve this is to entirely disable showing non-explosion judgements on legacy skins in taiko and just keep the explosions if we want compatibility, which does not seem to be immediately achievable using the current state of the skin transformer approach (`LegacySkin` would have to know if it's in a taiko context to determine whether it should block lookup of `GameplaySkinComponent<HitResult>` or not).

**Comment by peppy** [comment]
@bdach actually it is quite possible already!
