### ISSUE TITLE
taiko big dons/kats dont use taiko-300k

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#9860]
**Describe the bug:** taiko big dons/kats doesnt seem to use taiko-300k.png and instead will use taiko-300.png. in the screenshot, they both say great but taiko-300 is just a solid colored one while taiko-300k has a semi-transparent letters while having outer glow (edit: idk if it also affects taiko-100k)

**Screenshots or videos showing encountered issue:** 
Lazer: (edit for wrong screenshot)
![Screenshot (148)](https://user-images.githubusercontent.com/41866328/90309500-bdd22b80-df1b-11ea-9269-73093158fbf8.png)

Stable:
![screenshot096](https://user-images.githubusercontent.com/41866328/90307474-016f6a00-df09-11ea-89c4-c26be7eaa1d0.png)

**osu!lazer version:** 2020.814.0

**Skin:** https://drive.google.com/file/d/1is63tvBoQQnVybxPTla2SNvxqDY2rvZc/view?usp=sharing

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5078297/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5078298/performance.log)

**Comment by bdach** [comment]
So I was hoping this was going to be a quick and painless one, but it doesn't seem to be.

Making the sprite show up is the trivially easy part; the hard part is figuring out whether `300` or `300k` should show, and when. As the OP states, it has to do with strong hits, but the only reliable way I found of making the `300k` sprite show up is autoplay. At first I thought it shows if both hits of a strong hit are completed, but no, that doesn't seem to be the case (unless my timing is *this* bad - but I clearly saw two hits go to the health bar, but the explosion was still a `300`). If stable is expecting the double hit to be frame-perfect then it simplifies matters for the implementation, but I don't know if it makes much sense from a usability standpoint.

Unassigning for now as I'm not sure what direction is to be taken here.
