### ISSUE TITLE
Broken gameplay when audio buffer underruns

### ISSUE THREAD

**Issue by buratud** [ppy/osu#9865]
**Describe the bug:** 
So I hit the note, it shows great but then miss very quickly.
Moreover, the performance drops compared to previous version (2020.806.0)

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=4n3KkhfF0PA
https://www.youtube.com/watch?v=5OcAntay4m4

**osu!lazer version:** 
2020.814.0

**Logs:**
https://drive.google.com/drive/folders/1KQ2xd9IiA0x_knw1d-airNMW-3vAsRMC?usp=sharing

**Comment by bdach** [comment]
Cannot reproduce either case. Maps seem to be:

https://osu.ppy.sh/beatmapsets/648540#osu/1742226 (except the video shows it as qualified, so it might be an older version, possibly with something wrong with it),
https://osu.ppy.sh/beatmapsets/128931#osu/847313

Performance is a separate issue entirely but just saying "it drops" isn't helpful in itself without details what is different, what your specs are, etc.

**Comment by buratud** [comment]
My spec:
OS: Debian 10.4 64-bit
CPU: AMD Athlon(tm) X4 860K Quad Core Processor
RAM: 12GB
Storage type: Harddisk .

*Drop mean that it lags but not with previous version.
*Yes, the map is right.

**Comment by Elijah-ru** [comment]
Something similar is happening to me aswell. 

Here is what's happening : https://youtu.be/TVptTYN8o-4
It happens in all beatmaps

It also appeared with the newest version (2020.814.0)
What I did to adress the issue : 
- map the key to something else than the default "z" and "w" (didn't work)
- rollback to a previous version (works)

I'm running Manjaro Linux with an AMD 2700, 16GB of RAM, Radeon RX590

**Comment by bdach** [comment]
This is very confusing as I'm pretty sure there were no changes last update that affect input.

As a shot in the dark, please try running lazer with the `--sdl` command line option and checking if that changes anything.

**Comment by buratud** [comment]
When run
`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at osu.Framework.Platform.Sdl.Sdl2WindowBackend..ctor()
   at osu.Framework.Platform.DesktopWindow..ctor()
   at osu.Framework.Platform.Linux.LinuxGameHost.CreateWindow()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Desktop/Program.cs:line 55
Aborted
`

**Comment by bdach** [comment]
That's due to a lack of SDL dynamic libraries on your system; you would have to install them from your package manager to try.

Alternatively, @buratud I also notice you seem to be running the game single-threaded; does this also happen in multi-threaded mode?

**Comment by buratud** [comment]
Yes it is. Autoplay also miss.

**Comment by Elijah-ru** [comment]
The --sdl command seems to fix things here. Thanks for the tip.

**Comment by buratud** [comment]
Problem still persist to me when using `--sdl`

**Comment by Elijah-ru** [comment]
Strange, somehow the --sdl argument fixed the issue but it is now back to where I started. I noticed that there is also some other keys that are not working (for example the "²" on top of tab to retry).

**Comment by buratud** [comment]
Autoplay also fail using `--sdl`

**Comment by buratud** [comment]
For me, it sometimes laggy or glitch even I close every other program.

**Comment by bdach** [comment]
No idea, sorry. We've changed some audio settings to decrease latency, maybe that will be related; have any of you done any tweaking to alsa/pulseaudio settings?

**Comment by buratud** [comment]
Nope, same device and setting as the previous version.

**Comment by Craftplacer** [comment]
I can report the same audio glitching as well since yesterday after upgrading to 2020.814.0.

Even with and without using AutoPlay, I can see notes missing for literally no reason (playback time shifting), also the audio is crackling sometimes ever since (on some devices even with the game slowing down for a brief moment).

Additional footage: https://streamable.com/sidemm

**Comment by bdach** [comment]
Yeah, it seems that the newly-changed bass settings (https://github.com/ppy/osu-framework/pull/3823) might have been a little too extreme. Will be tuned back down soon enough, to hopefully sane levels.

**Comment by peppy** [comment]
Requires a framework fix, but also needs investigation osu!-side as to how this can happen. We should be guarding against it breaking gameplay.
