### ISSUE TITLE
Better error message on multiplayer game join failure

### ISSUE THREAD

**Issue by Craftplacer** [ppy/osu#9870]
**Describe the new feature:** 
Currently the game kicks out players who are running an older version with "Failed to retrieve a score submission token", this generally should be avoided and should guide the player to resolution.

**Proposal designs of the feature:** 
Pre-emptively checking if the client is outdated, if so, kicking out the player before joining a game and showing a specific notification.

**Comment by bdach** [comment]
This has been improved upon in #9818 and will be fixed going forward.
