### ISSUE TITLE
Multiplayer is Completely Broken on macOS Osu! Lazer Version 2020.814.0

### ISSUE THREAD

**Issue by KweenAriel** [ppy/osu#9872]
So I was looking to play osu multiplayer with my friends for the first time and unfortunately multiplayer is totally broken for me (single player still works fine). Whenever I try to commence any beatmap in multiplayer I get the error message "Failed to retrieve a score submission token. This may happen if you are running an old or non-official release of osu! (ie. you are self-compiling). This error has been automatically reported to the devs."

***I uploaded a screen recording of the error and and my logs folder as zip files since it's the only format Github supports besides picture files. So when you download them you have to unzip them, sorry for the inconvenience :(

<img width="1280" alt="Screen Shot 2020-08-15 at 6 58 21 PM" src="https://user-images.githubusercontent.com/69740198/90325083-fda10f00-df2b-11ea-8c26-9996b646d591.png">

[Proof.mov.zip](https://github.com/ppy/osu/files/5079859/Proof.mov.zip)

Osu! Lazer Version 2020.814.0

Also I'm running macOS Catalina Version 10.15.6

[logs.zip](https://github.com/ppy/osu/files/5079861/logs.zip)

**Comment by peppy** [comment]
Thanks for pointing this out. Turns out the hash was missing a character. This has now been fixed.
