### ISSUE TITLE
Have input handler on a different thread then the renderer

### ISSUE THREAD

**Issue by Menotdan** [ppy/osu#9873]
**Describe the new feature:** 
In osu!stable I like playing without vsync to get less input latency, but this causes screen tearing which for some reason really bothers me. I was curious if there was any reason you couldn't have the input handling be on a different thread then the rendering, so you could get vsync rendering with speedy input. I am aware that this may not be possible due to limiation of whatever libraries are used by osu! but I was curious anyways.

**Proposal designs of the feature:** 
You could add some settings in the input or rendering section in settings so you could limit input delay using a slider, and then have an fps limit slider (custom fps limiting would be epic)

Note:

 I have not touched osu!lazer yet, maybe this is already implemented, please fill me in on any missing details and ask me questions becuase I probably missed something.

**Comment by Alchyr** [comment]
in lazer it's separate

**Comment by Menotdan** [comment]
Ok, thanks, can't wait for lazer to be mainstream and more bug free lol

**Comment by peppy** [comment]
As a heads up, simply separating input (and updates) does not "fix" vsync. It improves it, but you will always be up to one frame behind. Less noticeable at higher refresh rates, but still a thing.

**Comment by Menotdan** [comment]
> As a heads up, simply separating input (and updates) does not "fix" vsync. It improves it, but you will always be up to one frame behind. Less noticeable at higher refresh rates, but still a thing.

Can you explain why that is? I don't quite understand. If you have one thread that renders whatever to the screen (with vsync), and one thread that handles user inputs and updates values and stuff for the renderer every x ms, wouldn't that make the input delay x ms?

Also this isn't really an issue it was more of a feature request, but I will try to remember to test in the future, was on mobile and wanted to get my ideas out before I forgot

**Comment by peppy** [comment]
Please google for more information on basic graphics concepts - there's plenty of information out there.

**Comment by Menotdan** [comment]
My only concern is input delay, don't see how graphics stuff would apply here, maybe i'm just being a dummy. Does whatever library you use only gather inputs every frame rendered? I think there might be some libraries that do that, idk, never done much stuff with graphics libraries in C#, I did use pygame at one point for a few things but I don't really have experience with common C# graphics libraries, whatever you might be using.

**Comment by Menotdan** [comment]
Hm, from a quick glance at the code it looks like you use an SDL wrapper for C#? 
It looks like there is also a fallback to some "osuTk"? What is that?

**Comment by jai-x** [comment]
I would suggest not continuously inquiring in this issue thread about a topic that is already well understood by the developers.

To answer your original question, multithreading is disabled on mobile platforms by default due to performance reasons and can be re-enabled in the settings, but this may caused issues on some devices.
