### ISSUE TITLE
Summarize what osu is in one sentence

### ISSUE THREAD

**Issue by probonopd** [ppy/osu#9875]
**Describe the bug:** 

> ![image](https://user-images.githubusercontent.com/2480569/90331350-20bad580-dfa3-11ea-9b91-d035dcd2483e.png)

I cannot figure out what this application does by looking at the first sentences of the README and even after opening the application for the first time.

* Is it a rythm/music composition tool?
* Somewhting with artificial intelligence?
* A game?
* Something where I need to log in on a server?

Only by going to its homepage I get a _tiny_ bit more information:

> free-to-win rhythm game

**Screenshots or videos showing encountered issue:** 

> Rhythm is just a click away. The future of osu! and the beginning of an open era! Commonly known by the codename osu!lazer. Pew pew.

This actually does __not__ tell one what the software actually is and what it actually does. Just vaguely that it has something to do with "rythm".

How would you describe the software e.g., in an app store?

**Comment by bdach** [comment]
"free-to-win rhythm game" is correct, as you noted from the front page. I'm not sure that's unnecessarily unclear.

**Comment by probonopd** [comment]
OK, then I think it would be useful to add that sentence as the first sentence in the README: 

![image](https://user-images.githubusercontent.com/2480569/90331465-0cc3a380-dfa4-11ea-926f-e10741b9e526.png)

**Comment by probonopd** [comment]
...and to the `osu!.desktop` file instead of

```
Comment=Rhythm is just a *click* away.
```

**Comment by peppy** [comment]
@probonopd curious: how did you find the project?

**Comment by probonopd** [comment]
@peppy by searching for projects that make AppImages from .NET/Mono applications. You seem to have found a great working way to do so :100: :+1:

**Comment by peppy** [comment]
aha, i see. will drop a link to the deploy script, responsible for the appimage creation, if you didn't find it already: https://github.com/ppy/osu-deploy

**Comment by probonopd** [comment]
It is already featured on https://github.com/AppImage/awesome-appimage#deployment-tools-for-net-core-mono-applications :+1: 

I'm especially happy since I had run into [issues](https://github.com/MatterHackers/MatterControl/issues/3536) bundling Mono apps in the past, which may have to do with the fact that I know everything about AppImage but practically nothing about Mono.

**Comment by bdach** [comment]
As clarification, if the `osu!.desktop` file is modified as suggested in subsequent releases, will action be required from us to propagate the change on the side of the `appimage.github.io` repository, or will it be updated (semi-)automatically?

**Comment by probonopd** [comment]
Once a new AppImage containing a new desktop file is available for download, please ping me and I will re-run the automated process for `appimage.github.io`.

**Comment by peppy** [comment]
I think this can be closed now.

**Comment by bdach** [comment]
I'll drop a ping here once the next release is out to update the required references in the appimage catalogue.

**Comment by bdach** [comment]
@probonopd 2020.820.0 has been released; the description should be more legible now. Thanks for bringing this to our attention!
