### ISSUE TITLE
Incorrect song control message

### ISSUE THREAD

**Issue by buratud** [ppy/osu#9876]
**Describe the bug:** 
Using F3 to pause and play track.
When the message say "Pause track", the song play. Same in vice versa.
Also happens using `--sdl` argument.
Restart and still happens.

**Screenshots or videos showing encountered issue:**
https://www.youtube.com/watch?v=m0UbuiNABbU

**osu!lazer version:** 
2020.814.0

**Logs:**
https://drive.google.com/drive/folders/1KQ2xd9IiA0x_knw1d-airNMW-3vAsRMC?usp=sharing

**Computer spec:**
OS: Debian 10.4 64-bit
CPU: AMD Athlon(tm) X4 860K Quad Core Processor
RAM: 12GB
Graphic card: Readon RX560 Series
Storage type: Harddisk

**Comment by bdach** [comment]
I can't seem to reproduce this one, either. Works perfectly fine here.

**Comment by peppy** [comment]
Going to close this in favour of #9880, which will probably resolve this issue.
