### ISSUE TITLE
Sliders lags

### ISSUE THREAD

**Issue by dimagtv** [ppy/osu#9881]
Sliders so laggy in gameplay, example: i'm holding slider and my game lags for 1-2 second
osu lazer version: 2020.814.0

**Comment by bdach** [comment]
This is not nearly enough information. Please attach a video or at least a screenshot with FPS counter showing and state your hardware specifications.

**Comment by dimagtv** [comment]
> This is not nearly enough information. Please attach a video or at least a screenshot with FPS counter showing and state your hardware specifications.

Not problem!

**Comment by dimagtv** [comment]
![image](https://user-images.githubusercontent.com/64431894/90343620-f7d62700-e01a-11ea-94fd-e8689fef6022.png)
17.27 lol. When im clicking circles i play with 5-6ms but when sliders starts ms going to fly

**Comment by dimagtv** [comment]
![image](https://user-images.githubusercontent.com/64431894/90343661-53a0b000-e01b-11ea-8445-0f8c066e1f8d.png)
or this

**Comment by Sinamer** [comment]
It seems that I have a similar issue. Sliders streams greatly lower Update and Draw fps and it creates a noticeable slowdown in gameplay. Here's a video showcasing the drop in framerate (it doesn't look like much, but it's more persistent when recording isn't on):
https://youtu.be/J3Q-I7TtZ6o
The map in the video: https://osu.ppy.sh/beatmapsets/1054045#osu/2202493
Another map with a more extreme case: https://osu.ppy.sh/beatmapsets/609057#osu/1286241 (one single slider stream at 40% of the map)

**Comment by dimagtv** [comment]
> It seems that I have a similar issue. Sliders streams greatly lower Update and Draw fps and it creates a noticeable slowdown in gameplay. Here's a video showcasing the drop in framerate (it doesn't look like much, but it's more persistent when recording isn't on):
> https://youtu.be/J3Q-I7TtZ6o
> The map in the video: https://osu.ppy.sh/beatmapsets/1054045#osu/2202493
> Another map with a more extreme case: https://osu.ppy.sh/beatmapsets/609057#osu/1286241 (one single slider stream at 40% of the map)

Yes, you have same freeze.

**Comment by dimagtv** [comment]
> It seems that I have a similar issue. Sliders streams greatly lower Update and Draw fps and it creates a noticeable slowdown in gameplay. Here's a video showcasing the drop in framerate (it doesn't look like much, but it's more persistent when recording isn't on):
> https://youtu.be/J3Q-I7TtZ6o
> The map in the video: https://osu.ppy.sh/beatmapsets/1054045#osu/2202493
> Another map with a more extreme case: https://osu.ppy.sh/beatmapsets/609057#osu/1286241 (one single slider stream at 40% of the map)

Try Camellia's maps, and you will see real problem.

**Comment by smoogipoo** [comment]
As mentioned above, please post your hardware specs. Please post logs (especially runtime.log). Please post [dxdiag output](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe).

**Comment by Sinamer** [comment]
[DxDiag.txt](https://github.com/ppy/osu/files/5083007/DxDiag.txt)
[performance.log](https://github.com/ppy/osu/files/5083010/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5083011/runtime.log)

**Comment by smoogipoo** [comment]
Yeah, with 4GB ram that's definitely going to be GC-related stutters. It'll improve over time and as we implement hitobject and storyboard pooling (https://github.com/ppy/osu/issues/6136).

Closing as this is not immediately actionable.
