### ISSUE TITLE
Stacked button hover sounds on bootup in the tournament client

### ISSUE THREAD

**Issue by MiraiSubject** [ppy/osu#9882]
**Describe the bug:** 

When booting up osu!lazer tournament when the UI gets constructed the hover sounds of many buttons can be heard at once, even if the cursor is not in the window. 

Repro instructions is just booting up the client, doesn't matter if it's focused or not focused. 

**Screenshots or videos showing encountered issue:** 

https://streamable.com/qitht0

**osu!lazer version:** 
2020.814.0 (found this while testing #9200 and haven't had the time to check other commits to see when this started)

**Comment by peppy** [comment]
Can you please include your tourney configuration (json)? I can hear one single sound, but not as many as you're reporting.

**Comment by peppy** [comment]
This looks to be a regression from https://github.com/ppy/osu-framework/pull/3289 / https://github.com/ppy/osu/pull/9216.

**Comment by MiraiSubject** [comment]
Zipped it here: [bracket.zip](https://github.com/ppy/osu/files/5083876/bracket.zip)

I could have sent it right away but 3 AM me didn't think about that.

**Comment by frenzibyte** [comment]
Thanks for the bracket configuration, can hear the amount of samples playing at once on bootup, and can also confirm all are from the same regression above, which shall be fixed in one PR framework-side.
