### ISSUE TITLE
Bringing Global Statistics menu freezes the game

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#9886]
**Describe the bug:** latest release that doesn't have this issue is 2020.725.0

**Screenshots or videos showing encountered issue:** https://youtu.be/vOqRizag5BI

**osu!lazer version:** 2020.814.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/5083131/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5083132/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5083133/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5083134/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5083135/runtime.log)

**Comment by smoogipoo** [comment]
Fixed in https://github.com/ppy/osu-framework/pull/3828
