### ISSUE TITLE
After updating to 2020.814.0 high audio latency

### ISSUE THREAD

**Issue by memesnightmares** [ppy/osu#9895]
**Describe the bug:** 

After updating, I had to set the audio offset to -180ms in order to be able to play the game. Prior to updating it was at 0ms and was working without a problem. This also isn't awful, like with the audio offset I can still play the game, it just seems like a bug. I'm running arch linux with pulseaudio, in case that information is useful.

**Screenshots or videos showing encountered issue:** 

Not sure what I could put here? Happy to take screencaps if told what I should be capturing.

**osu!lazer version:** 2020.814.0 (prior was 2020.801.0 I believe, although I'm not totally sure)

**Logs:**

Here are the lines that relate to versions:

```
2020-08-17 18:55:37 [verbose]: osu 2020.814.0.0
2020-08-17 18:55:37 [verbose]: Running on Unix 5.7.12.1, 16 cores
```

None appear to be relevant but I've saved them in case they're useful. runtime.log just shows song switches and performance.log just has a few Texture related messages. I'm happy to attach those if needed though.

**Comment by bdach** [comment]
There have been changes to audio settings last release (which were actually supposed to *decrease* latency). They have been reverted; please check whether it's back to normal next release.

**Comment by memesnightmares** [comment]
Thank you again for your quick response! I really appreciate the work y'all are putting into this and how responsive you are to new issues :)
