### ISSUE TITLE
New mod "Slider practice"

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9900]
**Describe the new feature:** 
A mod that would generate sliders of random length and speed (based on the current bpm). Or sliders with variable speed. This will improve your skills in controlling the sliders. 

**Proposal designs of the feature:** 
A very good example - https://osu.ppy.sh/beatmapsets/437683#osu/942356

**Comment by bdach** [comment]
I'm not sure how that could be a mod, as in how would it use the actual source beatmap. I guess it could just use it as a backing track but that feels a bit weird IMO.

**Comment by smoogipoo** [comment]
I think this is more suited to a custom implementation than a mod, where you have all the freedom in the world to do everything - generating _good_ spatial beatmaps is a non-trivial task and generally requires the involvement of some sort of machine learning algorithm.

I also don't like the concept of a "mod" completely butchering an entire beatmap and doing its own thing.
