### ISSUE TITLE
Hold note ticks gives score even if not pressed

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#9904]
**Describe the bug:** Hold note ticks gives score even if not pressed in my screenshot, i didnt press any buttons as evident with the key overlay. HP also goes down and displays miss. Accuracy sometimes goes up (depending on the current position in map or if there are notes present together with the hold)

**Screenshots or videos showing encountered issue:** 
Centipede (which has a Hold at the start) start (accuracy Low because of Head note)
![osu_2020-08-18_18-11-09](https://user-images.githubusercontent.com/41866328/90502254-1ace1b80-e180-11ea-824d-2308de8cf086.png)

Centipede (8 secs after, Accuracy goes higher)
![osu_2020-08-18_18-11-15](https://user-images.githubusercontent.com/41866328/90502375-494bf680-e180-11ea-82e6-b47200df4785.png)

A 7k Mania map with Holds at the middle
![osu_2020-08-18_18-15-58](https://user-images.githubusercontent.com/41866328/90501807-7e0b7e00-e17f-11ea-92b2-9ed62453d227.png)

**osu!lazer version:** 2020.814.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5089745/runtime.log)

**Comment by LastExceed** [comment]
[beatmap link](https://osu.ppy.sh/beatmapsets/150945#osu/372245)

**Comment by Flutterish** [comment]
I think this line of code is the problem. It should return 0 for `HitResult.Miss`
```cs
public class HoldNoteTickJudgement : ManiaJudgement {
	protected override int NumericResultFor ( HitResult result ) => 20; // << this

	protected override double HealthIncreaseFor ( HitResult result ) {
		switch ( result ) {
			default:
				return 0;

			case HitResult.Perfect:
				return 0.01;
		}
	}
}
```

**Comment by smoogipoo** [comment]
Please check the referencing PR...
