### ISSUE TITLE
Osu!Lazer unplayable performance on manjaro linux

### ISSUE THREAD

**Issue by zekiz774** [ppy/osu#9907]
**Describe the bug:**  The performance in Osu!Lazer is bad after I updated from version 2020.806.0 to 2020.814.0
The framerate is good, but it lags and I miss every circle

**osu!lazer version:**  2020.814.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5091298/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5091297/performance.log)
[network.log](https://github.com/ppy/osu/files/5091296/network.log)
[database.log](https://github.com/ppy/osu/files/5091295/database.log)

**Comment by bdach** [comment]
This report is nowhere near specific to be actionable. You haven't attached any videos, screenshots or an actual description of what the issue might be.

We've made some audio changes last release that could potentially contribute to this; they have now been reverted. Please check back after next release if things haven't improved.

**Comment by smoogipoo** [comment]
This is probably related to the recent audio device changes, which have since been reverted but there hasn't been a new release yet. Please wait for the next build.

**Comment by zekiz774** [comment]
Yes it is probably relatet with the changes. I compiled the latest version and it didn't had this issue.
