### ISSUE TITLE
Autoplay seemingly got selected automatically

### ISSUE THREAD

**Issue by Phippe** [ppy/osu#9915]
**Describe the bug:** I started osu!, downloaded a new map, but when I wanted to play, the autoplay mod had already been selected. Maybe there's a shortcut to it that I don't know of, which would make this issue useless. Otherwise, it's probably best to just have a look at the video.

Notable key presses:
(clicked on osu, then alt-tabbed between other windows before actually opening osu)
0:10 ctrl-alt-m
0:12 ctrl-alt
0:35 f and d, the controls bound to click the notes. Apparently my ctrl key is still registered, so it opens up osu!direct
0:47 esc key doesn't work (probably because of the ctrl key?)
1:08 ctrl, no more accidental osu!direct afterwards, esc works again

As you can see the mod only appeared in the menu at the bottom after I had specifically selected it at 1:40. After unselecting it afterwards, it was gone for good.

Hope this is enough information ^^"

**Screenshots or videos showing encountered issue:** https://streamable.com/0w4xwo

**osu!lazer version:** 2020.814.0.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/5095611/network.log)
[performance.log](https://github.com/ppy/osu/files/5095613/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5095614/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5095615/updater.log)
[database.log](https://github.com/ppy/osu/files/5095616/database.log)

**Comment by GSculerlor** [comment]
Selecting beatmap with ctrl key will activate autoplay mod

**Comment by Phippe** [comment]
I expected it could be something like this. Well, thanks for the new shortcut I guess
