### ISSUE TITLE
Moonwalking catcher in replays

### ISSUE THREAD

**Issue by ch4tie** [ppy/osu#9917]
**Describe the bug:** 
When watching osu!catch replays on lazer, there are instances where the catcher is facing the wrong way for some reason. This doesn't happen during gameplay, as demonstrated in the attached video. I think this only happens on dashes. Tested this on multiple maps and they all had the same problem.

**Screenshots or videos showing encountered issue:** 
https://icebearbestbear.s-ul.eu/TeKI4873

**osu!lazer version:** 
2020.814.0

**Logs:**

**Comment by peppy** [comment]
@ch4tie can you check whether this still happens on the latest release? i've checked the code and it doesn't look feasible. we have made quite a few catch improvements since this was posted so there's a high chance it was fixed along the way.

**Comment by ch4tie** [comment]
The bug is still there, unfortunately. After some more testing I did found out that:
-The bug only happens on replays made in osu!lazer, replays made in stable are fine
-It happens on both walks and dashes
