### ISSUE TITLE
HyperDashAfterImage custom color support doesn't work

### ISSUE THREAD

**Issue by ch4tie** [ppy/osu#9918]
**Describe the bug:** 
Copied from my comment on https://github.com/ppy/osu/pull/8200

Currently there doesn't seem to be support for the HyperDashAfterImage line in the skin.ini file. All hyperdash afterimages are a bright red, while this was changeable in the stable version. Not entirely sure if the cause is HyperDashAfterImage since I can't locate skin files in lazer. Regardless, would like to be able to customize the color of the glow. bdach suggested that it might be because of the beatmap skin option, I've tried playing with it both on and off and the issue persists.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
20.814.0

**Logs:**

**Comment by bdach** [comment]
Please attach the skin you're checking on for confirmation that this indeed does not work.

**Comment by ch4tie** [comment]
oh yeah, right. Skin I'm testing on is https://icebearbestbear.s-ul.eu/PV58DOMS

**Comment by bdach** [comment]
The value is being read *partially* right (as `0,0,0,1` instead of `0,0,0,0`) but then is seemingly unused.

**Comment by smoogipoo** [comment]
This shows up correctly if you change skin during gameplay. Some initialisation is likely missing from somewhere.
