### ISSUE TITLE
Taiko Major Barlines are too arbitrary

### ISSUE THREAD

**Issue by Alchyr** [ppy/osu#9919]
Currently, the BarLineGenerator uses
`Major = currentBeat % (int)currentTimingPoint.TimeSignature == 0`
to determine whether or not a barline is major (has triangles above and below), with currentBeat incrementing each measure and starting at 0 whenever a new timing point is reached.

This is problematic for a few reasons:

1. Major barlines may not necessarily line up with the time signature. A song in 4/4 may not have major beats every 4 measures, nor does this necessarily apply to any other time signature.

2. Timing points do not necessarily occur on major beats. In these cases, even if the song's major beats theoretically line up, every single major bar line would be incorrect. In the case of songs with variable bpm, this also results in far more major barlines than necessary.

I don't think there is a simple solution that guarantees these major barlines won't be incorrect, when taking into account songs with awkward pauses, or simply no clear pattern at all. The only method that guarantees no errors would be making it something mappers do, but this wouldn't solve the problem for older maps, in addition to requiring some sort of additional information attached to (effect? timing?) points, as well as a relatively significant amount of extra effort (in the cases of more complex songs, perhaps requiring every major barline to be marked individually?) on the part of mappers for very little benefit in terms of map quality.

Perhaps these major barlines could be something mappers can choose to add for emphasis, but I don't think auto-generating them is the right answer, which often places emphasis on random barlines that may have nothing on them at all.

**Comment by bdach** [comment]
I'm not sure what the expectation is here from reading the above post; if autogenerating isn't the answer, and neither is giving mapper a possibility to do so, apparently, then *what* is?

**Comment by Alchyr** [comment]
honestly, the easiest thing would just be to not have them by default, with mappers being able to choose to emphasize important barlines

Besides that, I don't think it'd be possible to guarantee incorrect barlines won't be emphasized

**Comment by peppy** [comment]
They should be correct for correctly made beatmaps. Not sure this requires action?

**Comment by Alchyr** [comment]
There are bars every four beats, but this is specifying "major" barlines as they're referred to in the code, which have additional triangles above and below them. It uses the time signature, but it counts bars, so in 4:4 it considers a major barline to be every 4 measures, which isn't necessarily the case. This is especially often not the case for more unusual time signatures, such as 5/4 or 7/4.

**Comment by peppy** [comment]
Aha, right. We changed the lines to not show every beat because it was too crowded.

The editor/beatmap format is going to support other time signatures better in the future but I'd say what we have is best-effort and works in most beatmaps. If a user doesn't like them they will have the option to skin them out of existence.

**Comment by Alchyr** [comment]
That makes sense to me
