### ISSUE TITLE
Hello, I can not play any music, I always get this error...

### ISSUE THREAD

**Issue by Suburbanno** [ppy/osu#992]
![osubug](https://user-images.githubusercontent.com/13632826/27939781-625d8252-629d-11e7-822d-08f8ec7f1fa1.PNG)

**Comment by Tsubajashi** [comment]
It's set on mania, as far as I know you cannot play mania on normal maps right now. Might be wrong here though. Click on the standard icon on the top left

**Comment by Shawdooow** [comment]
Converts are not functional yet, thats the "issue"

**Comment by Agrrox** [comment]
Converts should burn in hell.

**Comment by Kontorted** [comment]
Download a map specifically for your gamemode, since mode converting hasn't been implemented (No idea on current progress).
