### ISSUE TITLE
No sound when running through Wayland

### ISSUE THREAD

**Issue by 2str8** [ppy/osu#9920]
**Describe the bug:** 
Running on Wayland causes no sound. Everything is fine in X11. Arch Linux

**osu!lazer version:** 
2020.814.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/5100512/database.log)
[network.log](https://github.com/ppy/osu/files/5100513/network.log)
[performance.log](https://github.com/ppy/osu/files/5100514/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5100515/runtime.log)

**Comment by 2str8** [comment]
wait why logs from x11.. gimme a sec

**Comment by smoogipoo** [comment]
Maybe try running with the `--sdl` CLI argument, and possibly `SDL_VIDEODRIVER=wayland` environment variable. Not sure there's more we can do here at this point.

**Comment by bdach** [comment]
The segfault doesn't say much. Please see if `dmesg` has some relevant information (however that's unlikely - most likely going to have some useless instruction pointers and not much else).

Given that X works I'm half inclined to close this for now and track wayland issues under #5198.

**Comment by smoogipoo** [comment]
Let's do that. Probably need someone to run a Wayland system at some point and check out/fix all the bugs.

**Comment by 2str8** [comment]
if you can see [here](https://github.com/ppy/osu/issues/9634#issuecomment-662284384), i'm running lazer greatly, except some little bugs. So I think I'm missing some package, or something goes bad with alsa on wayland session.. idke.
