### ISSUE TITLE
Raw Input Can't Be Enabled on MacBook Pro

### ISSUE THREAD

**Issue by KweenAriel** [ppy/osu#9921]
I'm playing on a MacBook Pro and raw input cannot be enabled which means I can't adjust my cursor sensitivity in-game and have to boost my actual system cursor sensitivity to be able to play harder maps that are fast. The raw input button itself is greyed out and can't be clicked.

<img width="1280" alt="Screen Shot 2020-08-19 at 9 23 50 PM" src="https://user-images.githubusercontent.com/69740198/90716678-635e0580-e262-11ea-8f1c-8f487f873fae.png">

osu!lazer 2020.814.0
macOS Catalina 10.15.6

Logs:
[logs.zip](https://github.com/ppy/osu/files/5100656/logs.zip)

**Comment by smoogipoo** [comment]
Raw input is not supported on macOS right now.
