### ISSUE TITLE
gameplay random lag and log reporting textureAtlas exceed

### ISSUE THREAD

**Issue by Mic238** [ppy/osu#9924]
The gameplay randomly stuck for 0.3 seconds and it occurs multiple times during a game. performance log attached, reporting TextureAtlas exceeding each time a lag occur, running on Mac mini 2014 Catalina 10.15.4

![image](https://user-images.githubusercontent.com/20364101/90731900-a88b4180-e30d-11ea-95a4-92bdc79f5fae.png)

**Comment by bdach** [comment]
Please attach a video of what the "lag" looks like, preferably with the fps counter on.

I'm pretty sure that gameplay shouldn't be using textures that can't be atlassed and the messages shown above will be unrelated.

**Comment by peppy** [comment]
The log reports are on startup. Given the age of the system I don't think this is something we need to keep open. Last spikes will be improved upon over time, so keep checking back!
