### ISSUE TITLE
Hitsounds should not play at long note releases using inverse mod

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#9928]
Using the inverse mod, the hitsounds play twice every gap, once at the release of the previous long note and once at the start of the next long note. Hitsounds should not play at the release of every long note, only at the start.

https://streamable.com/2svsvc
version 2020.820.0

**Comment by bdach** [comment]
Was aware of this when reviewing, seemed intended:

https://github.com/ppy/osu/blob/3eac81eb52f3700a02b09c3693a67d85f4f950c7/osu.Game.Rulesets.Mania/Mods/ManiaModInvert.cs#L64-L68

@smoogipoo not sure about this one, maybe as an option or something?

**Comment by smoogipoo** [comment]
Remove it altogether since it's played on the next press. As it is it's also offset by 1/4 beat length so it sounds wrong too.

**Comment by frenzibyte** [comment]
Can be closed as https://github.com/ppy/osu/issues/9928 is merged (just realized it while sorting my notifications :p)
