### ISSUE TITLE
Applying conversion mod should force HitObject counts recalculation in BeatmapInfoWedge

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#9934]
Good example: Invert mod for mania. When enabled - it would be nice to show new HitObject counts.

**Comment by smoogipoo** [comment]
I’d probably like to see statistics reworked first to be emit by the difficulty calculator, and then have everything go through BeatmapDifficultyManager which is already async.

**Comment by EVAST9919** [comment]
Superseeded by https://github.com/ppy/osu/issues/18411 as having better explanation.
