### ISSUE TITLE
Opening beatmap details for certain mapsets leads to freeze

### ISSUE THREAD

**Issue by VisMajorSpeedruns** [ppy/osu#9937]
**Describe the crash:** 
Attempting to open the details for the beatmap set [Project Skylate - Green Tea mapped by capcom1500
](https://osu.ppy.sh/beatmapsets/1205458#osu/2510243) freezes my game and leads to a crash every time.

**Screenshots or videos showing encountered issue:** 
[Video of crash from startup](https://youtu.be/_1ARhXN53Bs)

**osu!lazer version:** 
2020.820.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5105520/database.log)
[network.log](https://github.com/ppy/osu/files/5105521/network.log)
[performance.log](https://github.com/ppy/osu/files/5105522/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5105523/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5105524/updater.log)

**Computer Specifications:** 
Windows 10 Home 64 bit
Intel Core i7-4770K @3.50 GHz
NVIDIA GeForce GTX 660
8GB ram

**Comment by bdach** [comment]
While this should probably be better guarded against client-side, it seems this is partially caused by some web-side mishap returning uneven collections in the `Metrics` property:

![image](https://user-images.githubusercontent.com/20418176/90828588-92e24000-e33e-11ea-86e1-5933b3d4a9b3.png)

**Comment by VisMajorSpeedruns** [comment]
Based on the logs it looks like the crash comes from line 33 of [osu.Game.Screens.Select.Details.FailRetryGraph.cs](https://github.com/ppy/osu/blob/master/osu.Game/Screens/Select/Details/FailRetryGraph.cs)
`float maxValue = fails.Any() ? fails.Zip(retries, (fail, retry) => fail + retry).Max() : 0;`
If fails.Any() returns true, but retries is empty, [Enumerable.Zip()](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip) will return an empty array, and [Enumerable.Max()](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.max) throws InvalidOperationException on an empty array.

Something like
`float maxValue = (fails.Any() && retries.Any()) ? fails.Zip(retries, (fail, retry) => fail + retry).Max() : 0;`
should prevent this crash.
