### ISSUE TITLE
Long opening time without sound

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9938]
**Describe the bug:** 
If you turn on the computer without sound, then when you turn on the application, it immediately freezes for a random period of time. After some waiting, it will still start. The wait may take 20 to 60 seconds. Windows writes that the application is not responding. If you turn on the sound and immediately turn it off, then turn on the lazer again, then everything will be fine. The problem is the first time you turn it on
**osu!lazer version:** 
2020.820.0 
[runtime.log](https://github.com/ppy/osu/files/5106256/runtime.log)

**Comment by peppy** [comment]
Have tested and cannot reproduce this. @Moltanicaa are you still getting it on the latest release?

**Comment by Moltanicaa** [comment]
Eeeh, no, there is no problem on the new device. Apparently, the problem was solved in one of the patches by itself
