### ISSUE TITLE
Hitsound tone/buzzing

### ISSUE THREAD

**Issue by MoshiBar** [ppy/osu#9939]
**Describe the bug:** 
some slider hitsounds seem to be playing just a constant tone
I've only noticed it in this beatmap [https://osu.ppy.sh/beatmapsets/855677#osu/1787848](https://osu.ppy.sh/beatmapsets/855677#osu/1787848)

**Screenshots or videos showing encountered issue:** 
[https://youtu.be/NiJOTGVdjJw](https://youtu.be/NiJOTGVdjJw)

**osu!lazer version:** 
2020.820.0
**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5106764/runtime.log)

**Comment by bdach** [comment]
The `sliderslide` sounds in the beatmap's skin are extremely short, bordering on empty:

![2020-08-31-170700_868x54_scrot](https://user-images.githubusercontent.com/20418176/91735380-85ce1800-ebac-11ea-9241-7c5c0cae5883.png)

Other utilities will outright refuse to list the length of said sample:

```
$ soxi soft-sliderslide.wav 

Input File     : 'soft-sliderslide.wav'
Channels       : 2
Sample Rate    : 44100
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

$ soxi -s soft-sliderslide.wav
0
```

Unsure of the correct way to proceed here - do we want to add a cutoff length for samples framework-side, to not bother playing such short "samples"? Also not sure why this isn't an issue in stable.

**Comment by peppy** [comment]
In stable, there's a cutoff to not load such samples:

![image](https://user-images.githubusercontent.com/191335/91790672-566ee800-ec4c-11ea-869f-9f296e7fac99.png)

It still creates a placeholder sample to maintain surrounding logic/state.

**Comment by bdach** [comment]
I've given the above idea of a legacy sample store a go; [here's a branch](https://github.com/ppy/osu/compare/master...bdach:legacy-sample-store).

The idea was to essentially have the legacy store as a decorator over the existing stores (as the framework-side `SampleStore` implementation is internal, so I can't derive from it). It's loosely coupled which is nice, but it's long-winded and also has a downside in that it reads the stream twice (once to determine length of sample data, the second time to actually load the sample). I'm not sold on this yet, so going to take some more time to think about this further before PRing and do more testing.

**Comment by peppy** [comment]
A couple of things:

- Having this at a legacy level seems fine, as we are probably going to guard against adding such small files to newer skins (or I guess, discourage from doing it by instead choosing a UI option to play "nothing" for a specific trigger).
- Reading twice should probably be avoided. Are you looking to avoid the bass sample creation overhead? If not, it may work to just request the `SampleChannel` then throw it away if it's too small.

**Comment by bdach** [comment]
I actually did it this way purely to minimise changes. Discarding the sample would also work but require framework-side changes to expose the sample length (I don't suppose we want naked BASS p/invokes game-side).

The linked branch is about the only way I can see to achieve this in this form only osu!-side without new framework APIs.

**Comment by peppy** [comment]
Oh, weird. I think we may want the length exposed regardless, sounds like something we would want to use.

**Comment by bdach** [comment]
Now that ppy/osu-framework#3891 is merged and should fix at least this one particular case, do we still want to add the 1024kb sample cutoff? Maybe better to not bother until it becomes a problem and close for now.

**Comment by peppy** [comment]
Can agree with this. Let's close and wait for it to be reported as an issue again.
