### ISSUE TITLE
have a option to hide the pp counter in the results screen

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#9955]
currently, the pp counter is displayed on the results screen(but not working)

the option to hide said counter would be for people who don't want to get pressured by being rated for their performance and just want to have fun

you can unhide it if you want to see your performances rated

your performances will still be rated but you don't have to see how much of a rating you got

**Comment by peppy** [comment]
I don't believe this will be a thing. If anything, it could be considered for when the relax mod is active.

**Comment by igontusuwu** [comment]
if you do hide it for relax, hide it for autopilot too

**Comment by Game4all** [comment]
i think the point was to disable the pp counter when a unranked mod is enabled
