### ISSUE TITLE
Cursor stuck at top-left corner when using Surface Pen and raw input

### ISSUE THREAD

**Issue by cihe13375** [ppy/osu#9961]
**Describe the bug:** I'm using Surface Pen on Surface Pro 6. If raw input is turned on, the cursor is stucked in a small region at the top-left corner no matter how I move my pen on the screen (see attached video). If I turn off raw input it's fine. Move by mouse/trackpad isn't affected.
Increasing sensitivity make it stucked at more top-left position (until reaching the "first" pixel on the screen), and decreasing sensitivity make it stucked at more down-right position (like, somewhere in the middle of the screen).

This issue also exists in stable but I'm not expecting it get fixed in stable so I post it here.

**Screenshots or videos showing encountered issue:** 
[issue.zip](https://github.com/ppy/osu/files/5114288/issue.zip)

**osu!lazer version:** 
2020.820.0

**Logs:** unrelated I guess

**Comment by Bios-Marcel** [comment]
how does one reset the settings :D

**Comment by bdach** [comment]
Raw input can be turned back off using <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>R</kbd>.

**Comment by cihe13375** [comment]
I tried the latest version and found the issue is mostly resolved (with the "high precision mouse" mode and 1.00x sensitivity). The only problem left is that the cursor location is a bit higher than my actual pentip location (see pic below; this happens both in menu and gameplay).
idk if I should close this and open a seperate issue for that
![Inked1619111070(1)_LI](https://user-images.githubusercontent.com/33959010/115755858-5e90b900-a3d0-11eb-8c9a-aa7ad3f75e96.jpg)

**Comment by peppy** [comment]
Please wait for the next release and see if this offset is still occurring. There are some incoming fixes for the game thinking the window is in a different position to where it actually is.

**Comment by cihe13375** [comment]
This seems fixed in 2021.424.0. Thanks for the efforts!
