### ISSUE TITLE
Add option to change (bar/pie) and move song progress display

### ISSUE THREAD

**Issue by stageosu** [ppy/osu#9965]
**Describe the new feature:** This feature would allow a user to select an option (under the "score meter type" drop-down menu) that allows the score meter to be on the bottom (like osu!Stable). Similarly, I would love to see an option for the "song progress meter" (I'm unsure of the official name) to be placed on the sides, instead of the bottom.

**Comment by Joehuu** [comment]
First part is a duplicate of https://github.com/ppy/osu/issues/5932, renamed to get other part of issue.

**Comment by frenzibyte** [comment]
Sounds like the other part lands in https://github.com/ppy/osu/issues/4632.

**Comment by bdach** [comment]
Yeah, let's close as duplicate.
