### ISSUE TITLE
AppImage in-game update doesn't update the game; have to clear all data to play new version

### ISSUE THREAD

**Issue by Alarg** [ppy/osu#9972]
Hey!

I've been trying to play osu!lazer on KDE Manjaro for a few days, but I keep encountering this issue.

When a new update comes out, I select to download the file.
It prompts me to choose via which app I should open, to which I type "AppImageLauncher %f".
Kioexec downloads the new AppImage and launches it. Everything seems fine - the game is updated.
However, when I start the game from the shortcut that points to original AppImage, it opens the previous version.

Location where I keep the original AppImage: `/home/alarg/Games/Osu/osu.AppImage`
Location of Osu data: `/home/alarg/.local/share/osu/`
Location of downloaded AppImage: `/home/alarg/.cache/kioexec/_NUMBERS_/osu.AppImage`

The only thing that worked for me was just changing paths to osu.AppImage, and that different paths somehow indicate to different AppImage files (instead of `/home/alarg/Games/Osu/osu.AppImage`, `/home/alarg/Games/osu/osu.AppImage`).
I'm not sure how any of this works since I'm still new to Linux, so I hope we can get this sorted out!

Best regards,
Alarg

EDIT: I forgot to add, clearing all data from .local folder in conjuction with changing paths is the method that worked with me.

**Comment by peppy** [comment]
I'm not even sure what to say. You need to point your shortcut to the correct appimage. Deleting game data has nothing to do with which verison of the game you are running.

**Comment by acedron** [comment]
Confirm. I just deleted old AppImage and replaced it with a new one. It didn't work. In-game updater also didn't work. It works after deleting `~/.local/osu/`. Weird that this wasn't the case for me until 2020.825.0.

**Comment by Alarg** [comment]
Sorry for not being clear enough, peppy. I'll add additional info since I forgot to make it obvious.

I download the new AppImage from inside the game. It downloads, I turn off the current instance and type `AppImageLauncher %f` from the currently present window for selecting the app to run the file with.
After that, the new version launches.

I turn off the new version, navigate to where it had been downloaded, and run it. It displays the newest version as the launched one.

I go to my firstly installed folder, that is, `/home/alarg/Games/Osu/osu.AppImage` that has been referenced above.
I delete the AppImage, replace it with the newly downloaded one, and run. It displays the old version even though I ran the new AppImage.

I hope it is clearer now. And don't get the wrong impression, I'm not a help leecher. I searched this beforehand, and didn't find anything similar happening generally with AppImages. Maybe I didn't pick right keywords, since I don't know what are the correct one to search with. That's what I meant with being new to Linux.

I think that the info I gave is plentiful to begin with, since I truly don't know from where to troubleshoot more.

**Comment by bdach** [comment]
> I delete the AppImage, replace it with the newly downloaded one, and run. It displays the old version even though I ran the new AppImage.

This makes no sense. How is this possible? Why would it downgrade after being copied from a location in which it worked previously?

**Comment by Alarg** [comment]
Give me 15 minutes and I'll upload it to Youtube, I truly have no idea myself.

**Comment by bdach** [comment]
For what it's worth I just tried to use the appimage management tool you describe and it worked flawlessly.

As long as the binary that the game downloads is of the correct version and that downloaded binary runs the version of the game the update notification claims to have downloaded, this issue is misdirected and is most likely a shortcoming in appimagelauncher.

**Comment by Alarg** [comment]
I understand now that it is a misdirected issue. I just tried running the game from my desktop PC running the same OS and the issue is nonexistent. I was running the game from laptop previously, so I guess it has something to do with the AppImageLauncher itself being messed up during installation. Either way, it really is a weird thing happening.

I'll close this issue then and seek support from them. Thank you for your assistance and sorry for bothering you.

Regards,
Alarg
