### ISSUE TITLE
Skin import does not work anymore 

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#9973]
**Describe the bug:** 
I tried to import my skins today. but after pressing the button nothing happens. its just gets stuck. aborting doesnt "refresh" the button. to retry i have to restart the game but then it just crashes.
**Screenshots or videos showing encountered issue:** 
https://streamable.com/1fo1m6
**osu!lazer version:** 
a1a1885 and on 2020.825.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/5119141/database.log)
[network.log](https://github.com/ppy/osu/files/5119142/network.log)
[performance.log](https://github.com/ppy/osu/files/5119143/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5119144/runtime.log)

i added my database as well just in case https://drive.google.com/file/d/1KasA2FMx0vJj82fbrq7sNlrr0BgvkEVW/view?usp=sharing

**Comment by peppy** [comment]
Something has your database in a locked state. Restart your PC and try again.

**Comment by Lolihunter1337** [comment]
i did that and the game works again after that. however the skins still dont import.

**Comment by smoogipoo** [comment]
Please post the updated log files.
