### ISSUE TITLE
Mod that forces alternation via combo break in osu!standard

### ISSUE THREAD

**Issue by ribbanya** [ppy/osu#9975]
I would like there to be a mod that causes a combo break if (assuming Z and X binds) you press Z twice before pressing X, or vice versa. The combo break would act like a slider break in the sense that it would play the break sound and end your combo, but would not affect your accuracy.

The score multiplier would be ×1.00, effectively handicapping you for no score benefit. Alternating is more ergonomic so having the game encourage you to adopt it is beneficial in the long run, to players interested in learning it.

EDIT: There could also be another mod, similar to PF vs. SD, that instead of combo breaking simply disallows you from pressing a key twice in a row (usually resulting in a miss anyway). Multiplier ×1.00.

**Comment by enoslayd** [comment]
Its already suggested and is being implemented
