### ISSUE TITLE
Maps on android not saving

### ISSUE THREAD

**Issue by timofey260** [ppy/osu#9980]
I do not save maps on osu! lazer on my phone, cook and is it possible to solve this problem. also after each exit the game starts over, crashes in some situations.

**Comment by bdach** [comment]
What is "saving maps" supposed to mean in this context? Saving from the editor?

The restart-on-exit is a known issue for now. See #6593 for explanation.

**Comment by timofey260** [comment]
no, from the browser in the game

**Comment by peppy** [comment]
Android user support is not something we can currently offer. Please use the in-game download facilities.
