### ISSUE TITLE
Game sometimes crash on systems with multiple GPUs connected to multiple displays

### ISSUE THREAD

**Issue by allu16** [ppy/osu#9986]
**Describe the crash:** 
When i launched the installer i saw the osu installer only in the taskbar but there was no window.
After the install osu!lazer.lnk appeared on my desktop.
When i try to launch osu!lazer it appears for a second in task manager but again there is no window.

If i go to the compatibility settings and turn on the "Run in 640 x 480 screen resolution" i get a black screen on my main monitor but no osu! window.

I also tried to disconnect my second monitor but nothing changed.

**osu!lazer version:** 
osu 2020.825.0.0

**Logs:**
This is with the compatibility setting turned on.
[runtime.log](https://github.com/ppy/osu/files/5130710/runtime.log)

This is with the compatibility setting turned off.
[runtime.log](https://github.com/ppy/osu/files/5130752/runtime.log)

**Computer Specifications:** 
GPU:
AMD Radeon HD 6450
NVIDIA GeForce GTX 1060 6GB

CPU:
Intel Core i5-8400 @ 2.80GHz

RAM:
24GB

**Comment by bdach** [comment]
This is the error in question:

```
2020-08-26 15:20:57 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2020-08-26 15:20:57 [error]: An unhandled error has occurred.
2020-08-26 15:20:57 [error]: osuTK.Graphics.GraphicsModeException: Device Primary: {X=0,Y=0,Width=1920,Height=1080} (139 modes available): Failed to change resolution to {X=0,Y=0,Width=1768,Height=992}x32@30Hz.
2020-08-26 15:20:57 [error]: at osuTK.DisplayDevice.ChangeResolution(DisplayResolution resolution)
```

Very weird display mode chosen (what is that resolution and refresh rate? Are 30Hz displays even a thing anymore?)

To confirm: you ran the game immediately after installing and haven't changed any display settings yourself, correct? What displays do you have connected? Do you think the parameters above match any of them?

**Comment by jai-x** [comment]
Just double checking, you have correctly listed two different GPUs as part of your computer specification?

I'm wondering if having two different graphics devices is causing the exception in osuTK.

**Comment by allu16** [comment]
> This is the error in question:
> 
> ```
> 2020-08-26 15:20:57 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
> 2020-08-26 15:20:57 [error]: An unhandled error has occurred.
> 2020-08-26 15:20:57 [error]: osuTK.Graphics.GraphicsModeException: Device Primary: {X=0,Y=0,Width=1920,Height=1080} (139 modes available): Failed to change resolution to {X=0,Y=0,Width=1768,Height=992}x32@30Hz.
> 2020-08-26 15:20:57 [error]: at osuTK.DisplayDevice.ChangeResolution(DisplayResolution resolution)
> ```
> 
> Very weird display mode chosen (what is that resolution and refresh rate? Are 30Hz displays even a thing anymore?)
> 
> To confirm: you ran the game immediately after installing and haven't changed any display settings yourself, correct? What displays do you have connected? Do you think the parameters above match any of them?

Correct I ran the game immediately and didnt change any display settings. 
I have these two monitors and the one below has the weird resolution and is indeed 30Hz.
Also if it matters it is an old TV.
![image](https://user-images.githubusercontent.com/62132801/91332314-ad039e80-e7d4-11ea-9a3e-2c80664fa83f.png)

**Comment by allu16** [comment]
> Just double checking, you have correctly listed two different GPUs as part of your computer specification?
> 
> I'm wondering if having two different graphics devices is causing the exception in osuTK.

Yes I have my old GPU (AMD Radeon) connected to one monitor and the GTX connected to the other.
I dont know if this is the cause to the "exception in osuTK".

**Comment by bdach** [comment]
Could you try disconnecting the TV and seeing if the game will launch then (and continue to launch after the TV is re-connected)? Also, could you try launching lazer with the `--sdl` command line option?

It looks like the display is forcing your GPU (probably the wrong one) to render at a weird display mode that it might not support. Not sure we'll be able to support that immediately as that's a... rare setup, to say the least.

**Comment by allu16** [comment]
Disconnecting the TV doesnt work.
And how would I go about launching lazer with the `--sdl` command line option?

**Comment by bdach** [comment]
Assuming windows, right click on shortcut -> *Properties* -> go to *Shortcut* tab -> click the *Target* text box and append `--sdl` (with a space preceding it) at the very end of it.

**Comment by allu16** [comment]
It works thank you! :)

**Comment by bdach** [comment]
I'll reopen this for tracking, as SDL support is at the experlimental stage for now, but as long as it works it's the recommended workaround.

**Comment by bdach** [comment]
Closing as SDL is now the primary windowing backend.
