### ISSUE TITLE
Screen Scaling set to Gameplay results in cut-off approach circles and spinners

### ISSUE THREAD

**Issue by Sobsz** [ppy/osu#9987]
**Describe the bug:** 
With `Screen Scaling` set to `Gameplay`, pixels outside the playfield aren't rendered, but the background is still full-screen. This results in a jarring cut-off of approach circles when at the edge of the playfield, as well as spinners with the default skin. Then again, this might be intended, and either way it's pretty minor, so...

**Screenshots or videos showing encountered issue:** 
![osu_2020-08-26_17-16-13](https://user-images.githubusercontent.com/18291848/91322471-10cf9c80-e7c0-11ea-9532-064f789fcbef.png)
![osu_2020-08-26_17-23-26](https://user-images.githubusercontent.com/18291848/91323372-18dc0c00-e7c1-11ea-9117-fcb0ae4b7b03.png)

**osu!lazer version:** 2020.825.0

**Comment by GSculerlor** [comment]
#5353

**Comment by bdach** [comment]
Closing as duplicate.
