### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by ThatBetaGuy** [ppy/osu#9989]
When playing there is no audio, even with my audio source is selected 

![image](https://user-images.githubusercontent.com/70305334/91379490-1341ee80-e7e0-11ea-9597-04f102b463e5.png)

osu!lazer 2020.825.0

[runtime.log](https://github.com/ppy/osu/files/5133828/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5133829/updater.log)
[database.log](https://github.com/ppy/osu/files/5133830/database.log)
[network.log](https://github.com/ppy/osu/files/5133831/network.log)
[performance.log](https://github.com/ppy/osu/files/5133832/performance.log)

**Comment by smoogipoo** [comment]
This is going to be something with your system. Maybe another app has taken exclusive control over the audio device, or you need to update your drivers.

**Comment by Poliwrath** [comment]
> Maybe another app has taken exclusive control over the audio device
I think it would be BASS_ERROR_BUSY if this was the case, if I understand the documentation right (http://www.un4seen.com/doc/bass/BASS_Init.html)
``BASS_ERROR_BUSY | Something else has exclusive use of the device.``
