### ISSUE TITLE
Allow tournament lobbies to be hosted on a separate server

### ISSUE THREAD

**Issue by Negaosu** [ppy/osu#9999]
**Although through no direct fault of your own mostly, the instability of bancho has increasingly meant that tournament matches are interrupted and delayed. In some cases the entire match has had to be rescheduled to a later date where they just have to hope that bancho is working at that time. I am not 100% sure of the logistics of the tournament server you use for OWC, but I was thinking that it might be beneficial to leverage the usage of a similar style server for badged tournaments, so that matches can go uninterrupted.** 

**Perhaps it could be in such a format that it is an additional parameter for the !mp make command and only people on a certain list can make lobbies on such a server (the list would contain badged tourney hosts/refs), but I just wanted to know your thoughts on the idea in general as I think this would greatly help the tournament scene.**

**Comment by smoogipoo** [comment]
This is not the forum to discuss this.

**Comment by peppy** [comment]
Sorry that your tournament suffered, but we are doing our best to resolve this. If things are not better within a week please reach out to pe@ppy.sh and I'll organise a custom arrangement.
